### ISSUE TITLE
Fix-up navigation property after DbContext.Remove

### ISSUE THREAD

**Issue by Materix** [dotnet/efcore#10008]
I have entity which can belong to many different containers (showing only two containers for clarity):

```c#
public class Account 
{
    [Key]
    public int Id { get; set; }

    public List<DiagramAccount> Diagrams { get; set; }

    public List<OtherContainerAccount> OtherContainers { get; set; }
}
```

```c#
public class Diagram
{
    [Key]
    public int Id { get; set; }

    public List<DiagramAccount> Accounts { get; set; }    
}
```

```c#
public class OtherContainer
{
    [Key]
    public int Id { get; set; }

    public List<OtherContainerAccount> Accounts { get; set; }    
}
```

```c#
public class DiagramAccount
{
    [Key]
    public int Id { get; set; }

    public Account Account { get; set; }
    public int AccountId { get; set; }
    public Diagram Diagram { get; set; }
    public int DiagramId { get; set; }
}
```

```c#
public class OtherContainerAccount
{
    [Key]
    public int Id { get; set; }

    public Account Account { get; set; }
    public int AccountId { get; set; }
    public OtherContainer OtherContainer { get; set; }
    public int OtherContainerId { get; set; }
}
```

I have to detach Account from Diagram (or from any other container) and, if it was last connection, remove that Account and then save changes to database.

```c#
using (var context = _accessor.CreateContext())
{
    // Remove join instance
    context.Remove(context.Set<DiagramAccount>().First(da => da.AccountId == accountId && da.DiagramId == diagramId));

    // Get instance of account without explicity loading DiagramAccount
    var account = context.Set<Account>().First(a => a.Id == accountId);
    // context.SaveChanges(); // I do not want to save it here due to operation consistency

    // ... other steps
}
```

After getting account from db in account.Diagrams is the same instance of DiagramAccount which was removed in the first line (due to automatic fix-up navigation properties). The account.Diagrams should be empty because the instance of DiagramAccount is actually marked as removed (and it is actually the only one loaded instance of DiagramAccount). Instead of this it contains this removed DiagramAccount instance). After context.SaveChanges() invocation (commented line), account.Diagrams is empty (and this is ok).

Is there possibility to refresh collection in tracked entity without calling SaveChanges or explicitly removing removed DiagramAccount instance from that collection? 
Shouldn't it match in memory state of data automatically?

### Further technical details
EF Core version: 2.0.0
Target Framework: net461
Database Provider: Microsoft.EntityFrameworkCore.Sqlite (for unit test)
Operating system: Window 10
IDE: VS2017 15.3

**Comment by Wain123** [comment]
In issue #8319, it was claimed that this behavior is intentional and the collections should only get updated after SaveChanges. But now this is tagged as a bug and collections should get updated immediately? Could you please clarify?

**Comment by ajcvickers** [comment]
@Wain123 Yes, it is supposed to happen after SaveChanges. But two things here:
* What if you query for an entity that has relationships to an already deleted entity? I need to look into the code for this and see what is happening.
* When I did a quick investigation of this it looked like things were not quite right after SaveChanges
* I'm thinking about filing an issue to make this configurable, but I need to do some more investigation.

**Comment by ajcvickers** [comment]
Analysis using current bits indicates everything is working correctly. That is, the behavior is the same regardless of whether the query for the principal is done before or after the Remove call. Fixup happens regardless of whether the dependent is marked as Deleted or not. After save, the reference to the deleted entity is removed, but the navigation on the deleted entity is not touched.

Issue #10114 tracks allowing the fixup to happen before SaveChanges is called.
