### ISSUE TITLE
Mvc Web App template inside docker tries to connect to localdb

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#10002]
Steps:
Create new ASP.NET Core Web Application
Choose Web Application template for 2.0
Add individual accounts auth
Enable Docker support for windows.
Restore packages/build solution etc.
Press F5

Above will fail due to https://github.com/aspnet/Mvc/issues/6923
Once you correct the URL to http://172.21.203.31/
Website loads correctly. But when trying to register User, it fails with following error
![image](https://user-images.githubusercontent.com/1528107/31301164-d558664e-aaac-11e7-8ea4-284f0abd6581.png)

Essentially it is trying to connect to localdb which does not exist inside docker container (for obvious reason)

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/templating/issues/52
