### ISSUE TITLE
RevEng: Don't scaffold facets for when type is aliased

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#10003]
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L846-L857

When we have aliased column type, we use underlying type to generate facets. But then we modify ScaffoldingTypeInfo so that we scaffold `HasColumnType`. But we still leave out other facets. That means for underlying type like `nvarchar(16)` aliased as `MyType` we generate `property.HasColumnType("MyType").HasMaxLength(16);` Which is redundant/ambiguous/incorrect.

Either we can null out all facets. or We can apply facets to property only if inferred type. Or we can leave facets on property (in case we want to generate maxlength like #9580 ), and skip them while writing out the file.

**Comment by bricelam** [comment]
We should leave the facets on and just always scaffold them. As you said, doing this would also fix #9580.

**Comment by ajcvickers** [comment]
Closing this for now since the demand seems low. If this is something you need, then please feel free to comment saying how this is impacting you and we we re-assess.
