### ISSUE TITLE
Can't build latest in Visual Studio

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#10007]
I pulled latest from dev and now I can't build in Visual Studio.  

I'm getting the following error from all projects.

`The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.`

Everything builds find from build.cmd.  

I have the latest .net 2.0 sdk installed.  

Per the instructions from build.com I have tried adding the directory 'C:\Users\pmiddleton\.dotnet\x64' to my path.  

Does anyone know if there is another step I need to take to get things building in VS again?

**Comment by smitpatel** [comment]
what is the output of `dotnet --version`. Unless its 2.1.0-* and you are opening from that terminal VS won't work.
That error simply indicates that for some issue in env variables, VS is not getting 2.1.0 preview SDK

**Comment by pmiddleton** [comment]
It is coming back as 2.0.0.

Korebuild has installed 2.1 here C:\Users\pmiddleton\.dotnet\x64\sdk\2.1.0-preview1-007042

Adding that directory to my path does not fix the issue.  Is there another env variable I have to set other than the path?

**Comment by ajcvickers** [comment]
@pmiddleton What does `which dotnet` return? Maybe the path change isn't being picked up? Did you put if before everything else in the path?

**Comment by smitpatel** [comment]
@pmiddleton - Check out https://github.com/aspnet/EntityFrameworkCore/wiki/getting-and-building-the-code#build-from-visual-studio I have added exact steps yesterday in the wiki on updating PATH to pickup preview SDK.

**Comment by pmiddleton** [comment]
That was the problem.  I the default core framework install was before the preview in my path.  I overlooked that when modifying the path.

Thanks @ajcvickers @smitpatel
