### ISSUE TITLE
MigrationCommandExecutor not rollingback failed migration

### ISSUE THREAD

**Issue by robert396** [dotnet/efcore#10019]
When running a migration that fails due to a custom raw sql script `migrationBuilder.Sql("..script_goes_here...");`, what has already been applied in the migration is not being rolled back.

### Further technical details
EF Core version: 2.0.0
Database Provider: Pomelo.Entityframeworkcore.MySql
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@robert396 It looks like this is probably an issue with the MySql provider--you might want to try filing an issue here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

The behavior is intended to be that the SQL will be executed inside a transaction for the migration such that if it fails, then the entire migration is rolled back. There are some cases where, at least on SQL Server, this is not possible, but in those cases the migration should explicitly configure that it is opting out of the transaction to execute the SQL.
