### ISSUE TITLE
Eager loading IEnumerable navigation collections : Related data not materialized

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#10015]
Describe what is not working as expected.
Include works when a navigation collection is simple List<T> but the reated objects are not materialized when the collection is an IEnumerable<T>.

I have a class that contains a one-many relationship with "Quotes". The quotes property is defined and added to as follows:

```C#
private readonly List<Quote> _quotes = new List<Quote> ();
public IEnumerable<Quote> Quotes => _quotes.ToList ();
public void AddQuote (string quoteText) {
       quoteText=StringManipulators.ReplaceBadWordWithAsterisks(quoteText);
      _quotes.Add (new Quote(GuidId,quoteText));
}
```
 I have added the following mapping in the dbcontext to force it to read from the _quotes backing field but it makes not change. IIRC, in another model, I couldn't even do an insert without this. But the insert was working just fine with/without.

```C#
var navigation = modelBuilder.Entity<Character>).Metadata.FindNavigation(nameof(Character.Quotes));
    navigation.SetPropertyAccessMode(PropertyAccessMode.Field);

```
When I issue a query with Include(c=>c.Quotes), I can see the SQL does retrieve the quotes, but the resulting object does not include the quotes. I am debugging and looking at the objects directly, so this is not about JSON support for spitting results out via an API. :)

When I change the above property to simply be 

```C#
public List<Quote> Quotes {get;set;}
```

The results contain the quote objects in the Quotes property.
With the IEnumerable, the database created by code first looks as expected.
Inserting quotes works as expected. The data in the database has the correct FK values.

Is there a mapping I'm forgetting I need to implement? I double checked Arthurs blog post about the backing properties & IEnumerable support but there's nothing about queries and I've been googling to no avail.

EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macos and win10
IDE: VS Code and VS2017

**Comment by ajcvickers** [comment]
@julielerman I wrote some test code below to try to reproduce this, but I'm seeing the Quotes navigation loaded correctly. Can you look and see what is different in your code that might be making this fail for you?

```C#
public class Quote
{
    private Quote()
    {
    }

    public Quote(Guid id, string text)
    {
        Id = id;
        Text = text;
    }

    public Guid Id { get; set; }

    public string Text { get; set; }
}

public class Character
{
    public Guid Id { get; set; }

    private readonly List<Quote> _quotes = new List<Quote>();

    public IEnumerable<Quote> Quotes => _quotes.ToList();

    public void AddQuote(string quoteText)
    {
        quoteText = "*" + quoteText + "*";
        _quotes.Add(new Quote(Guid.NewGuid(), quoteText));
    }
}

public class TestDbContext : DbContext
{
    public DbSet<Character> Characters { get; set; }
    public DbSet<Quote> Quotes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var navigation = modelBuilder
            .Entity<Character>()
            .Metadata
            .FindNavigation(nameof(Character.Quotes));

        navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var character = new Character();
            character.AddQuote("Quote1");
            character.AddQuote("Quote2");
            context.Add(character);
            context.SaveChanges();
        }

        using (var context = new TestDbContext())
        {
            var characters = context.Characters.Include(e => e.Quotes).ToList();
        }
    }
}
```
![image](https://user-images.githubusercontent.com/1430078/31349125-c6b7a3bc-acd6-11e7-9df5-06bca2f6c38c.png)

**Comment by julielerman** [comment]
thanks, Arthur! Off to play the Sesame Street game (one of these things is not like the other).  :)

**Comment by julielerman** [comment]
Aha...I think I discovered this when I was working on that article you helped me with...ORDER is important. ANd this one makes sense. All the code was correct.

I was putting the new metadata code at the top of the modelbuilding method ... BEFORE the code that explained to the context how to find the foreign key property which is private.

When I moved it after, it worked.
Thanks for clarifying that I at least had the right code. :)

By the way, Part 2 of the article is online now https://msdn.microsoft.com/magazine/mt826347

**Comment by julielerman** [comment]
Hey @ajcvickers ...I wanted to let you know that I was repeating this pattern (look at your code listing for ref) and spent some time hitting an exception when EF Core was trying to materialize the related data (_quotes List). I tried a number of things until I thought to change List<Quote> to ICollection<Quote> and it worked! This is with 2.0.1. Does that sound expected based on a change you made (assuming on the path to additional support for doing funky things with navigation properties...) ?? Thanks!

**Comment by ajcvickers** [comment]
@julielerman The code works for me with a List or an ICollection.

**Comment by julielerman** [comment]
Gah ..looks like I have to play "one of these things is ont like the other" yet again! LOL As annoying as it is, I'm glad it just me, not the API :)
