### ISSUE TITLE
Argument must be boolean

### ISSUE THREAD

**Issue by faust21** [dotnet/efcore#10028]
- Theses are the fragment of my linq expressions. And when i comment the bold lines, it runs no error.

> where (string.IsNullOrEmpty(searchParams.OrderNum) ? true : o.OrderNum.Contains(searchParams.OrderNum))
>                             && (null == searchParams.OrderStatus || searchParams.OrderStatus.Contains(o.OrderStatus))
>                             **&& (searchParams.IsBid ? (b == null || !b.SellerName.Contains(searchParams.SellerName)) : (o.SellerName.Contains(searchParams.SellerName) || (b != null && b.SellerName.Contains(searchParams.SellerName))))**
>                             && (dtBegin == null || o.CreatedTime > dtBegin.Value)
>                             && (dtEnd == null || o.CreatedTime < dtEnd)
>                             && (dtBidExpire == null || o.CreatedTime > dtBidExpire)

- The belows are the whole linq expressions.

> value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AnyGou2.SqlServerEF.TbOrder]).GroupJoin(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AnyGou2.SqlServerEF.TbBid]), o => o.OrderNum, bid => bid.OrderNum, (o, rb) => new <>f__AnonymousType4`2(o = o, rb = rb)).SelectMany(<>h__TransparentIdentifier0 => <>h__TransparentIdentifier0.rb.DefaultIfEmpty(), (<>h__TransparentIdentifier0, b) => new <>f__AnonymousType5`2(<>h__TransparentIdentifier0 = <>h__TransparentIdentifier0, b = b)).Where(<>h__TransparentIdentifier1 => (((((IIF(IsNullOrEmpty(value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.OrderNum), True, <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderNum.Contains(value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.OrderNum)) AndAlso ((null == value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.OrderStatus) OrElse value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.OrderStatus.Contains(<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderStatus))) AndAlso IIF(value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.IsBid, ((<>h__TransparentIdentifier1.b == null) OrElse Not(<>h__TransparentIdentifier1.b.SellerName.Contains(value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.SellerName))), (<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.SellerName.Contains(value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.SellerName) OrElse ((<>h__TransparentIdentifier1.b != null) AndAlso <>h__TransparentIdentifier1.b.SellerName.Contains(value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).searchParams.SellerName))))) AndAlso ((value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).dtBegin == null) OrElse (<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.CreatedTime > value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).dtBegin.Value))) AndAlso ((value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).dtEnd == null) OrElse (Convert(<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.CreatedTime, Nullable`1) < value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).dtEnd))) AndAlso ((value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).dtBidExpire == null) OrElse (Convert(<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.CreatedTime, Nullable`1) > value(AnyGou2.Seller.Controllers.OrderController+<>c__DisplayClass23_0).dtBidExpire)))).OrderByDescending(<>h__TransparentIdentifier1 => <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.CreatedTime).Select(<>h__TransparentIdentifier1 => new Order() {CreatedTime = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.CreatedTime.ToString(), DeliverMethod = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.DeliverMethod, ExpressFee = IIF((null == <>h__TransparentIdentifier1.b), <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.ExpressFee, <>h__TransparentIdentifier1.b.ExpressFee), IsBid = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.IsBid, CouponId = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.CouponId, OrderActualPay = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderActualPay, OrderMessage = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderMessage, OrderNum = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderNum, OrderState = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderStatus, OrderTotal = IIF((null == <>h__TransparentIdentifier1.b), <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.OrderTotal, <>h__TransparentIdentifier1.b.BidTotal), ReceiverName = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.ReceiverName, Telephone = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.Telephone, UserName = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.o.UserName})

**Comment by WHATSAF** [comment]
Sorry, it's my mistake.
