### ISSUE TITLE
Reset or invalidate HiLoValueGeneratorState

### ISSUE THREAD

**Issue by cknaap** [dotnet/efcore#10031]
I have an application with a function to reset the database (SQL >=2012). In the DbContext I use sequences with UseSqlServerHiLoSequence. When I reset the sequence with a raw SQL command, and then continue with normal operations (create new records), this happens:

1. Start application.
2. Start inserting entities -> SqlServerSequenceHiLoValueGenerator gets a new Lo value and 'reserves' sequence values 1 - 10.
3. Insert 7 entities, so sequence values 8, 9 and 10 are still available.
4. Reset the sequence with a raw SQL Command.
5. Create a new instance of the DbContext.
6. The remaining numbers before 'Hi' (8, 9 and 10) are still available in the SqlServerSequenceGeneratorState, let's say.
7. Insert 3 more entity, they get id's 8, 9 and 10.
7. Insert 8 more entities.
8. The SqlServerSequenceHiLoValueGenerator gets a new Lo value.
9. The sequence was reset, so it gets value 1 - 10.
10. When it hits nr. 8: exception - Entity with the same ID is being tracked already in the DbContext.

So I am looking for a way to invalidate the HiLoValueGeneratorState, other than restarting the application.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017
Database: SQL Server 2016

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
