### ISSUE TITLE
PMC Tools: Exception calling "AddFromFile"

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10044]
From VS Feedback:

I just upgraded my solution to .net core 2.0 and also find Entity Framework migrations to be working very inconsistently in the package manager.

I tend to get the following error on "add-migrations"

"add-migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with the null character."

**Comment by bricelam** [comment]
See also:
* [scaffold-dbcontext basepath exception on EntityFrameworkCore](https://stackoverflow.com/q/42929614/475031)
* [Add-Migration : Exception calling “AddFromFile” with “1” argument(s): “'basePath' cannot be an empty string (”")](https://stackoverflow.com/q/42823847/475031)

**Comment by smitpatel** [comment]
This made me curious. We would throw above exception when the generated file is essentially null coming out of reveng or add-migration. I am trying different things to achieve that but so far all I got is VS crash. :trollface:

**Comment by bricelam** [comment]
I can't repro this. If anyone has a solution that consistently fails with this error, please let us know so we can investigate further.
