### ISSUE TITLE
Create model of views by Scaffold-DbContext

### ISSUE THREAD

**Issue by netbidev** [dotnet/efcore#10055]
Hello everyone.

Is it possible to create model of views via Scaffold-DbContext?

**Comment by smitpatel** [comment]
@netbidev - At present there is no way.
There is some work-around posted by a user here https://github.com/aspnet/EntityFrameworkCore/issues/9854#issue-258984255

Duplicate of #1679

**Comment by cgountanis** [comment]
This seems to be an issue again with Core 3.1.
