### ISSUE TITLE
Guidance and Documentation for Provider Developers

### ISSUE THREAD

**Issue by kendallmiller** [dotnet/efcore#1007]
To maximize the value of EF 7, users should be able to quickly connect to all of the data sources they want to use.  To make that happen, the people behind those data sources need to create great providers and have them available as close to the launch of EF 7 as possible.  Traditionally, making EF providers has been a daunting task.  For EF 7, lets work together to lower the barriers to creating and validating these providers.  Additionally, having third party providers available earlier may help the EF core team improve the developer experience which is currently very difficult (Getting EF 6's designer to recognize VistaDB has become our top support item by a mile, necessitating [multiple passes of documentation](http://www.gibraltarsoftware.com/Support/VistaDB/Documentation/WebFrame.html#EntityFramework_GettingStarted.html) and [KB articles](http://support.gibraltarsoftware.com/support/solutions/articles/4000021684) and patient one-on-one help on our part which leaves a bad taste in the user's mouth both about us and EF).

**Comment by dazinator** [comment]
I would also love to have a provider ready when EF7 is launched.

I looked at the documentation here: 
https://github.com/aspnet/EntityFramework/wiki/Writing-an-EF7-Provider

The first thing that struck me was obviously the massive disclaimer:

THE INFORMATION ON THIS PAGE IS OUT OF DATE
WE WILL BE UPDATING IT SOON

My question - how accurate is this documentation - is it going to be a complete waste of my time if I start using it to implement a provider? Or is it largely correct / fairly up to date, with the obvious risk that some things may change as dev progresses prior to release?

**Comment by dazinator** [comment]
Also the template provider project (great idea by the way - should be very useful) was last updated 7 months ago. It would be nice if someone could verify if it is still accurate, or update it perhaps, if possible?

https://github.com/natemcmaster/entityframework-provider-starter

Thanks for your hard work so far on EF7 :)

**Comment by augusteiner** [comment]
:+1:

**Comment by rowanmiller** [comment]
@dazinator - The docs will give you some of the info you need, I don't think any of the info will send you in the wrong direction... it just won't give you the full picture of what you need. It also doesn't cover any of the guidance for naming conventions etc. we want to encourage for extension method naming etc. but you can probably work that out by looking at our providers.

**Comment by dazinator** [comment]
Ok thanks @rowanmiller  - I'll read the doc's then, but use your SQL server provider as the go to reference. 
Cheers.

**Comment by ErikEJ** [comment]
@kendallmiller  & @dazinator Feel free to have a look at the SQLCE provider(s) for inspiration as wll, and feel free to ping me with questions https://github.com/ErikEJ/EntityFramework7.SqlServerCompact

**Comment by dazinator** [comment]
Cheers @ErikEJ - that should help greatly, i will take a look this week

**Comment by rowanmiller** [comment]
Docs on docs.efproject.net are now much better
