### ISSUE TITLE
Required attribute ignored for Enum Fields, in Code First POCO's

### ISSUE THREAD

**Issue by sheam** [dotnet/efcore#10082]
In my POCO I have a field 

    [Required]
    public SaleType SaleType  { get; set; }

In EF6 this generates a non-nullable int column in the SQL database. In EF Core 2.0 it generates a _nullable_ int column in the database.

My understanding is that the behavior in EF6 is correct, it should be non-nullable.

**Comment by ajcvickers** [comment]
@sheam This seems to work fine on SQL Server:
```sql
CREATE TABLE [Foos] (
    [Id] int NOT NULL IDENTITY,
    [SaleType] int NOT NULL,
    CONSTRAINT [PK_Foos] PRIMARY KEY ([Id])
);
```

What version of EF Core are you using and which database provider?

**Comment by sheam** [comment]
Actually, a mistake on my part. It did create a non-nullable. It was flagged in the schema comparison tool when I compared the EF.Core generated DB to the EF 6 generated one. It seems it is nullable in my old schema (EF6) that I was comparing it too. I'll close this.
