### ISSUE TITLE
Is it possible to select few columns and return the result as typed variable?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#10087]
I have a method that use EF Core to get information, but I would like to get only few columns, so I am trying something like that:

return await myDbContext.MyType.Where(x => x.ID > 3)
select(x => new {x.ID, x.Name})
.ToListAsync();

The method returns a List, but I get an error that says that annonymous type can't be converted to List.

I have tried this too:

```
return await myDbContext.MyType.Where(x => x.ID > 3)
select(x => new {x.ID, x.Name})
.ToListAsync().cast<MyType>().ToList();
```

But it doesn't work.

So I would like to know what is the way to select just few columns and return as a typed result.

Thanks.

**Comment by smitpatel** [comment]
```C#
return await myDbContext.MyType.Where(x => x.ID > 3)
select(x => new MyType { ID = x.ID,  Name = x.Name})
.ToListAsync();
```
Does above work? If you want typed result, you can put that in projection and construct the object you want. EF will select only required columns and generate required typed object with proper binding.

**Comment by ComptonAlvaro** [comment]
Thanks, it works perfectly.

Thank yo so much.
