### ISSUE TITLE
Test failure with lates dev

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#10113]
[xUnit.net 00:01:09.6363630]     Microsoft.EntityFrameworkCore.DataAnnotationSqliteTest.DatabaseGeneratedAttribute_autogenerates_values_when_set_to_identity [FAIL]
[xUnit.net 00:01:09.6366255]       Assert.Contains() Failure
[xUnit.net 00:01:09.6366993]       Not found: @p0='' (DbType = String)
[xUnit.net 00:01:09.6367521]       @p1='Third' (Nullable = false)
[xUnit.net 00:01:09.6368045]       @p2='00000000-0000-0000-0000-000000000003' (DbType = String)
[xUnit.net 00:01:09.6368528]
[xUnit.net 00:01:09.6368973]       INSERT INTO "Sample" ("MaxLengthProperty", "Name", "RowVersion")
[xUnit.net 00:01:09.6369567]       VALUES (@p0, @p1, @p2);
[xUnit.net 00:01:09.6370142]       SELECT "UniqueNo"
[xUnit.net 00:01:09.6370731]       FROM "Sample"
[xUnit.net 00:01:09.6371487]       WHERE changes() = 1 AND "UniqueNo" = last_insert_rowid();
[xUnit.net 00:01:09.6372094]       In value:  @p0='' (DbType = String)
[xUnit.net 00:01:09.6372674]       @p1='Third' (Nullable = false) **(Size = 5)**
[xUnit.net 00:01:09.6373240]       @p2='00000000-0000-0000-0000-000000000003' (DbType = String)
[xUnit.net 00:01:09.6373754]
[xUnit.net 00:01:09.6374176]       INSERT INTO "Sample" ("MaxLengthProperty", "Name", "RowVersion")
[xUnit.net 00:01:09.6374710]       VALUES (@p0, @p1, @p2);
[xUnit.net 00:01:09.6375294]       SELECT "UniqueNo"
[xUnit.net 00:01:09.6375804]       FROM "Sample"
[xUnit.net 00:01:09.6376486]       WHERE changes() = 1 AND "UniqueNo" = last_insert_rowid();

### Further technical details
EF Core version: dev today
Database Provider: Sqlite
Operating system: Win 10
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by bricelam** [comment]
These should have been fixed by #9940. Can you confirm whether those changes are in your build?

**Comment by ErikEJ** [comment]
Sorry, my branch was stale/old
