### ISSUE TITLE
Global filter doesn't filter tracked entites

### ISSUE THREAD

**Issue by mailopoland** [dotnet/efcore#10120]
Global filters work correct for including/loading navigation collections if elements from collection aren't tracked. We get filtered record and filtered collection for it. 

But please take a look on case when these elements were gotten before without filters (and are tracked now). In this situation when we are trying to get record with global filters and include/load its navigation collection then we also get collection elements which should be filtered.

Please let me know if I'm missing something or is it a bug which will be resolved?

Configuration:
```C#

modelBuilder.Entity<PresentationRecord>((
                entityTypeBuilder) =>
            {
//for better readability other required parts of configuration are skipped (entityTypeBuilder.ToTable/HasKey etc.)

                entityTypeBuilder
                    .HasQueryFilter(x => !x.Deleted);
            });
modelBuilder.Entity<CompanyRecord>((
                entityTypeBuilder) =>
            {
//for better readability other required parts of configuration are skipped (entityTypeBuilder.ToTable/HasKey etc.)

                entityTypeBuilder
                    .HasQueryFilter(x => !x.Deleted);

                entityTypeBuilder
                    .HasMany(x => x.PresentationRecords)
                    .WithOne(x => x.CompanyRecord)
                    .HasForeignKey(x => x.CompanyId);
            })

```
Problematic case:

```C#
//IF below line is uncommented then all presentations are loaded for notDeletedCompanies (also these with Deleted == true)
                var all = ctx.Presentations.IgnoreQueryFilters().ToList();

                var notDeletedCompanies = ctx.Companies
                    .Include(x => x.PresentationRecords)
                    .ToList();
```

**Comment by ajcvickers** [comment]
@mailopoland We will discuss this, but as of now this behavior is as designed. The filters are _query_ filters. That is, they filter what comes from the database in a query. Once an entity is being tracked it behaves just like any other entity that is tracked. This includes automatic fixup to other tracked entities. In the code above, any PresentationRecord entities that are tracked by the first query will end up fixed up to any companies tracked by the second query.

It would be useful to have some more details on what you are trying to achieve here. At first glance it looks like either you could be using a single context instance for more than one unit of work, or you could need a no-tracking query if this is intended to be for query only.
