### ISSUE TITLE
Values generated by SequentialGuidValueGenerator are not sequential

### ISSUE THREAD

**Issue by Hevand** [dotnet/efcore#10130]
When using SequentialGuidGenerator.cs to generate new guids, I noticed that the values generated were not sequential. The root cause for this seems to be use of a method variable for guidBytes, as opposed to a class variable:

```C#
public class GuidGenerator
    { 
        private long _counter = DateTime.UtcNow.Ticks;

        //Change: Change the guidBytes variable to be a class variable, to ensure the same 'base guid' is used for all increments. 
        private byte[] guidBytes = Guid.NewGuid().ToByteArray();
        //end of change

        public Guid Next()
        {
            //Change: remove the promoted method variable
            //var guidBytes = Guid.NewGuid().ToByteArray();
            //end of change
            var counterBytes = BitConverter.GetBytes(Interlocked.Increment(ref _counter));
            
            if (!BitConverter.IsLittleEndian)
            {
                Array.Reverse(counterBytes);
            }

            guidBytes[08] = counterBytes[1];
            guidBytes[09] = counterBytes[0];
            guidBytes[10] = counterBytes[7];
            guidBytes[11] = counterBytes[6];
            guidBytes[12] = counterBytes[5];
            guidBytes[13] = counterBytes[4];
            guidBytes[14] = counterBytes[3];
            guidBytes[15] = counterBytes[2];

            return new Guid(guidBytes);
        }
    }
```

In addition, I observed the following:
- It seems that the values generated by this algorithm, versus the values generated by SQL's newsequentialid are different (this code changes with the last 8 bytes, vs SQL apparently starting with the first?). That may be a big or a small thing - it is inconsistent with the comments in the code file. 
- After running the operation for a substantial number of iterations (say, more than 2^16 times), the algorithm will encounter a situation where earlier values are greater than later values:

```
Item 2^0 : ac9880a3-780d-4ef1-9be6-08d517ec4399
Item 2^16: ac9880a3-780d-4ef1-9be6-08d517ec439a
Item N   : ac9880a3-780d-4ef1-9be5-08d517ec439b
Distinct: 131072
All incremental: False
Number of non-sequential steps: 2
```

Logic behind the validations:
```C#
        static void Main(string[] args)
        {
            GuidGenerator gg = new GuidGenerator();
            Dictionary<int, Guid> generatedGuids = new Dictionary<int, Guid>();
                        
            for (int i = 0; i < 135000; i++)
            {
                Guid generated = gg.Next();
                generatedGuids.Add(i, generated);
            }

            Console.WriteLine($"Item 0: {generatedGuids[0]}");
            Console.WriteLine($"Item N: {generatedGuids[generatedGuids.Count() - 1]}");
            
            Console.WriteLine($"Distinct: {generatedGuids.Values.Distinct().Count()}");
            
            //The following would return 'true'
            Console.WriteLine($"All incremental: {generatedGuids.All(kv => kv.Key == 0 || (generatedGuids[kv.Key - 1].CompareTo(kv.Value) == -1))}");

            //The following returns non-zero values for any iteration value larger than 2^16 (65k)
            Console.WriteLine($"Number of non-sequential steps: {generatedGuids.Where(item => item.Key != 0 && (generatedGuids[item.Key - 1].CompareTo(item.Value) == 1)).Count()}");

            Console.ReadLine();
        }
``` 

Just to make this explicit - I don't know a whole lot about generating GUIDS, just sharing my observations. If the suggested code returns in a increased probability for collisions, I would love to know.

**Comment by smathilakath** [comment]
How is Shifting Bytes in this manner ensure to avoid collision?

Ref  : 
            guidBytes[08] = counterBytes[1];
            guidBytes[09] = counterBytes[0];
            guidBytes[10] = counterBytes[7];
            guidBytes[11] = counterBytes[6];
            guidBytes[12] = counterBytes[5];
            guidBytes[13] = counterBytes[4];
            guidBytes[14] = counterBytes[3];
            guidBytes[15] = counterBytes[2];

Does return new Guid(guidBytes); should be part of gg.Next(); ?

Ref : 
https://en.wikipedia.org/wiki/Collision_resistance

**Comment by anpete** [comment]
@Hevand Guids are sorted differently in SQL Server vs. in .NET. See [here](https://blogs.msdn.microsoft.com/sqlprogrammability/2006/11/06/how-are-guids-compared-in-sql-server-2005/) for more information. Please let me know if this clarifies our behavior, or if you encounter any other issues.

**Comment by Hevand** [comment]
Hi @anpete,
That definitely clarifies the behavior, and does seem to make the range of generated values strictly incremental - as long as one handles them as unique identifiers. Thanks for providing that explanation.
