### ISSUE TITLE
EFCore 2 has unclear error message when performing insert involving many-to-many join table. The property 'prop' on entity type 'someType' has a temporary value..

### ISSUE THREAD

**Issue by redwards510** [dotnet/efcore#10165]
This is a continuation of another issue[1], as requested by @ajcvickers 

I am getting the following exception message when trying to create a new entity and add it to the database. The oddity here is the many-to-many table in between two tables with a composite key, as is necessitated by Entity Framework Core 2.0 currently. 

Exception message: The property 'ZipCodeId' on entity type 'ServiceAreaToZipCode' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.

It's not clear how to solve this issue when one must walk through the many-to-many table in order to create the desired Id value just so I can put it back in!

[1]:https://github.com/aspnet/EntityFrameworkCore/issues/9552
### Further technical details
EF Core version: 2.0.0
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: windows 8.1 and 10
IDE: (e.g. Visual Studio 2017 15.4.1)
## My stack
```xml
  <ItemGroup>
    <PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Mapster" Version="3.1.6" />    
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0" />    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="3.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
  </ItemGroup>
```

# Steps to reproduce

## A Visual of the relationships at play here
![class diagram](https://i.imgur.com/KFp9rCv.png "Class Diagram of the many to many relationship tables")

## The DBContext & OnModelCreating

```csharp
public DbSet<ServiceArea> ServiceAreas { get; set; }
public DbSet<ServiceAreaToZipCode> ServiceAreaToZipCodes { get; set; }
// note i do not have zipcodes here

// ServiceAreaToZipCode MANY<->MANY JOIN TABLE. 
// see https://docs.microsoft.com/en-us/ef/core/modeling/relationships at bottom
// and http://www.thereformedprogrammer.net/updating-many-to-many-relationships-in-entity-framework-core/
// make sure that "Id" as the key isnt going to screw things up
modelBuilder.Entity<ServiceAreaToZipCode>().HasKey(t => new { t.ServiceAreaId, t.ZipCodeId }); // composite key, watchout!

modelBuilder.Entity<ServiceArea>()
    .HasMany(z => z.ServiceAreaToZipCodes)
    .WithOne(z => z.ServiceArea)
    .HasForeignKey(f => f.ServiceAreaId);

modelBuilder.Entity<ZipCode>()
    .HasMany(pt => pt.ServiceAreaToZipCodes)
    .WithOne(t => t.ZipCode)
    .HasForeignKey(pt => pt.ZipCodeId);
```

## The entity classes

```csharp
using System.Collections.Generic;

namespace OL.Web.AffiliateDb.Model.Entities
{
    public class ServiceArea : IEntityBase
    {
        public int Id { get; set; }

        public ICollection<ServiceAreaToZipCode> ServiceAreaToZipCodes { get; set; }

        public ICollection<AffiliateService> Services { get; set; }

        public Affiliate Affiliate { get; set; }
        public int AffiliateId { get; set; }
    }

    /// the many to many join table. It's got a composite key inside. note it doesnt implement IEntityBase because it has no Id (which is all that that interface has)

    public class ServiceAreaToZipCode
    {
        public int ServiceAreaId { get; set; }
        public ServiceArea ServiceArea { get; set; }

        public int ZipCodeId { get; set; }

        public ZipCode ZipCode { get; set; }
    }

    /// <summary>
    /// you can't have collections of primitive types, so i had to create this little class to hold zip code collections.
    /// </summary>
    public class ZipCode : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// It was decided to disallow +4 zips, therefore max length = 5
        /// </summary>
        [MaxLength(5)]
        [MinLength(5)]
        public string Zip { get; set; }

        public ICollection<ServiceAreaToZipCode> ServiceAreaToZipCodes { get; set; }

        public override string ToString()
        {
            return Zip;
        }
    }
}
```

## The DTOs
They have no join table in between, which complicates the mapping. 
```csharp
using System.Collections.Generic;

namespace OL.Web.AffiliateDb.Api.DTO
{
    public class ServiceAreaDTO
    {
        public int Id { get; set; }
        public IEnumerable<ZipCodeDTO> ZipCodes { get; set; }
        public IEnumerable<AffiliateServiceDTO> Services { get; set; }
        public int AffiliateId { get; set; }
    }

    // Notice that there is no join table object here. For the DTO i want to hide that logic from the clients. 
    public class ZipCodeDTO
    {
        public string Zip { get; set; }
    }

}

```

## The mapper setup.
[Mapster](https://github.com/MapsterMapper/Mapster). based on AutoMapper but with less verbosity. This is "TypeAdapterConfig<source, destination>"

```csharp
////////////////////////////////////////////////////////////
// Service Area DTO -> Entity + children
////////////////////////////////////////////////////////////
TypeAdapterConfig<ServiceAreaDTO, ServiceArea>
    .NewConfig()
    .Map(dest => dest.ServiceAreaToZipCodes,
            src => src.ZipCodes)
        .Ignore(dest => dest.AffiliateId)
        .Ignore(dest => dest.Affiliate);


TypeAdapterConfig<ZipCodeDTO, ServiceAreaToZipCode>
    .NewConfig()
    .Map(dest => dest.ZipCode.Zip,
        src => src.Zip);
```                    

## The controller
```csharp
[HttpPost("/affiliate/{affiliateId}/serviceAreas", Name = "PostServiceArea")]		
public async Task<IActionResult> PostServiceArea([FromRoute] int affiliateId, [FromBody] ServiceAreaDTO serviceArea)
{	    		    

    var entity = serviceArea.Adapt<ServiceArea>();
    entity.AffiliateId = affiliateId;
    _serviceAreaRepository.Add(entity);
    await _serviceAreaRepository.Commit();
    // fail here, during Mapster mapping
    var dto = entity.Adapt<ServiceAreaDTO>();
    return CreatedAtRoute("GetServiceArea", new { id = entity.Id }, dto);                
}
```        

## The incoming JSON body
```json
{
    "zipCodes": [
        {
            "zip": "88666"
        },
        {
            "zip": "99999"
        }
    ],
    "services": [ // edited for brevity
    ],
    "affiliateId": 202
}
```

## The Exception
```
Exception message: The property 'ZipCodeId' on entity type 'ServiceAreaToZipCode' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
Stack trace:
```
{System.InvalidOperationException: The property 'ZipCodeId' on entity type 'ServiceAreaToZipCode' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(ModificationCommand modificationCommand)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OL.Web.AffiliateDb.Data.Repositories.EntityBaseRepository`1.<Commit>d__13.MoveNext() in C:\wkspaces\OL.Web.AffiliateDb\src\OL.Web.AffiliateDb\AffilDb.Data\Repositories\EntityBaseRepository.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OL.Web.AffiliateDb.Api.Controllers.ServiceAreaController.<PostServiceArea>d__4.MoveNext() in C:\wkspaces\OL.Web.AffiliateDb\src\OL.Web.AffiliateDb\AffilDb.Api\Controllers\ServiceAreaController.cs:line 61}

   ## Where I'm blocked and what I'm trying

   Supposedly the workaround for this issue would be to create the `ServiceAreaToZipCode` entry first and then add the `ZipCode` to it? But I cannot figure out how to apply that to the mapper config. There is an `.AfterMapping()` method you can call which might help, or you can use `.ConstructUsing()` which lets you supply a factory method to create the destination object. See [this page](https://github.com/MapsterMapper/Mapster/wiki/Object-creation-and-validation) for usages.

But that is all mapping stuff. The bigger issue is that it's unclear to me how to solve this from the message provided. Can the message say *how* to set a permanent value explicitly on a table with a composite key?

**Comment by ajcvickers** [comment]
@redwards510 I took the code above and put it in the console application below, then removed the Mapster calls and did the mapping manually. This works correctly for me, so it seems like Mapster is not creating the entity graph correctly. I would suggest taking the console application below and adding back the Mapster calls, then comparing the entity graph created manually with the one created by Mapster. That should let you figure out what is wrong about the graph created by Mapster such that hopefully you can then get it to create the correct graph.

```C#
public interface IEntityBase
{
    int Id { get; set; }
}

public class ServiceArea : IEntityBase
{
    public int Id { get; set; }

    public ICollection<ServiceAreaToZipCode> ServiceAreaToZipCodes { get; set; }

    public int AffiliateId { get; set; }
}

public class ServiceAreaToZipCode
{
    public int ServiceAreaId { get; set; }
    public ServiceArea ServiceArea { get; set; }

    public int ZipCodeId { get; set; }
    public ZipCode ZipCode { get; set; }
}

public class ZipCode : IEntityBase
{
    [Key]
    public int Id { get; set; }

    [MaxLength(5)]
    [MinLength(5)]
    public string Zip { get; set; }

    public ICollection<ServiceAreaToZipCode> ServiceAreaToZipCodes { get; set; }

    public override string ToString() => Zip;
}

public class ServiceAreaDTO
{
    public int Id { get; set; }
    public IEnumerable<ZipCodeDTO> ZipCodes { get; set; }
    public int AffiliateId { get; set; }
}

public class ZipCodeDTO
{
    public string Zip { get; set; }
}

public class TestDbContext : DbContext
{
    public DbSet<ServiceArea> ServiceAreas { get; set; }
    public DbSet<ServiceAreaToZipCode> ServiceAreaToZipCodes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ServiceAreaToZipCode>().HasKey(t => new { t.ServiceAreaId, t.ZipCodeId }); // composite key, watchout!

        modelBuilder.Entity<ServiceArea>()
            .HasMany(z => z.ServiceAreaToZipCodes)
            .WithOne(z => z.ServiceArea)
            .HasForeignKey(f => f.ServiceAreaId);

        modelBuilder.Entity<ZipCode>()
            .HasMany(pt => pt.ServiceAreaToZipCodes)
            .WithOne(t => t.ZipCode)
            .HasForeignKey(pt => pt.ZipCodeId);
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var dto = new ServiceAreaDTO
            {
                AffiliateId = 202,
                ZipCodes = new List<ZipCodeDTO>
                {
                    new ZipCodeDTO { Zip = "88666" },
                    new ZipCodeDTO { Zip = "99999" }
                }
            };

            var entity = new ServiceArea
            {
                AffiliateId = dto.AffiliateId,
                ServiceAreaToZipCodes = dto.ZipCodes
                    .Select(
                        e => new ServiceAreaToZipCode
                        {
                            ZipCode = new ZipCode
                            {
                                Zip = e.Zip
                            }
                        })
                    .ToList()
            };

            context.Add(entity);
            context.SaveChanges();

            var returnDto = new ServiceAreaDTO
            {
                Id = entity.Id,
                AffiliateId = entity.AffiliateId,
                ZipCodes = entity.ServiceAreaToZipCodes
                    .Select(
                        e => new ZipCodeDTO
                        {
                            Zip = e.ZipCode.Zip
                        })
                    .ToList()
            };
        }
    }
}
```

**Comment by redwards510** [comment]
thank you @ajcvickers! i'm sorry it didn't turn out to be an efcore issue.
