### ISSUE TITLE
Cannot drop the index 'AspNetUserRoles.IX_AspNetUserRoles_UserId'

### ISSUE THREAD

**Issue by conglnh** [dotnet/efcore#10166]
Hello,

I am trying to run update-database in package manage console : update-database command.
But i got error like the title.
I work with my college and i pull request with 3 migration file .
![image](https://user-images.githubusercontent.com/18566114/32048242-1508a9c2-ba73-11e7-9551-24611306cdc3.png)
But in Migration CreateIdentity Schema : 
![image](https://user-images.githubusercontent.com/18566114/32048271-2df50804-ba73-11e7-9d2e-afad7f6f0b95.png)
I have method Up create a index in database, but it doestn't create in database.
After that I try to update-database in migration version : _CreateTableInvoice
![image](https://user-images.githubusercontent.com/18566114/32048339-5ec8fbac-ba73-11e7-860b-0729c6c328e6.png)
It drop the Index which is does not exist in database.
 Enviroment : Asp.net core 2.0 , Visual Studio 2017 , Entity Framework core 2.0, SQL 2017
Can you help me to fix it.

**Comment by ajcvickers** [comment]
This is due to the initial migration not being up-to-date, which is being addressed here: https://github.com/aspnet/Identity/pull/1561
