### ISSUE TITLE
What's the difference between adding ConcurrencyCheck and not adding?

### ISSUE THREAD

**Issue by l2999019** [dotnet/efcore#10173]
I refer to this article: https://docs.microsoft.com/zh-cn/ef/core/saving/concurrency
Not added ConcurrencyCheck  
You can also access DbUpdateConcurrencyException
So I don't know what it means

**Comment by ajcvickers** [comment]
@l2999019 DbUpdateConcurrencyException is thrown when EF expected to update a row in the database, but that row was found. This means that the row must have been deleted or updated between the time that EF read the values for that row and the time it attempts to do the update. Concurrency tokens are a way to ensure that any update will be detected by EF, but it will still happen for deletes regardless, and may also happen for other updates in some situations.
