### ISSUE TITLE
Navigation properties for IdentityUserRole

### ISSUE THREAD

**Issue by Ghasan** [dotnet/efcore#10178]
I am migrating a website to ASP.NET Core, and I am trying to provide the navigating properties once existed before for ASP.NET.

Simple, enough, I go doing this.

```c#
public class UserRole : IdentityUserRole<int>
{
	public User { get; set; } // For the inherited property UserId
	public Role { get; set; } // For the inheritied property RoleId
}
```

For some reason, I get four properties in the generated table: UserId, RoleId, UserId1, RoleId1. Then I go doing this.

```c#
public class UserRole : IdentityUserRole<int>
{
	[ForeignKey("UserId")]
	public User { get; set; } // For the inherited property UserId
	
	[ForeignKey("RoleId")]
	public Role { get; set; } // For the inheritied property RoleId
}
```

And I get this exception which make no sense at all.

```
The relationship from 'UserRole.Role' to 'Role' with foreign key properties {'RoleId' : int} cannot target the primary key {'Id' : int} because it is not compatible. Configure a principal key or a set of compatible foreign
key properties for this relationship.
```

The other classes are like.

```c#
public class User : IdentityUser<int>
{
    // Some properties
    public virtual ICollection<UserRole> UserRoles { get; set }
}

public class Role : IdentityRole <int>
{
    public virtual ICollection<UserRole> UserRoles { get; set }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 x64 FCU
IDE: dotnet CLI 2.0.2

**Comment by ajcvickers** [comment]
@Ghasan This is because the call to base.OnModelCreating is explicitly defining the relationships to have no navigations. That code needs to be overridden as well. There is a full discussion of the issue here: https://github.com/aspnet/Identity/issues/1364
