### ISSUE TITLE
dbContext.<Entity>.Update() is creating new records when key not set

### ISSUE THREAD

**Issue by ssanderlin** [dotnet/efcore#10194]
Seeing the issue described in #3890 in 2.0. Also similar to #3953, but with a different provider in my case. An entity containing an Identity key was passed to Update() without the appropriate key set and EFCore created a new row instead of throwing an error, as I would have expected.

I would expect an invocation of Update() to attempt to process the entity as State.Modified and not arbitrarily decide to execute a State.Added action based on the caller omitting the key.

The documentation (https://docs.microsoft.com/en-us/ef/core/) doesn't appear to specify that the Update() method behaves this way. If this is considered "by design", the documentation should explicitly state that passing an entity to Update() without providing a key will create a new row when the key is an identity.

Offending code appears to be Line 71 in EntityGraphAttacher.cs (https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs).

EF Core Version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating System: Win10 Enterprise
IDE: VS 2017

**Comment by ajcvickers** [comment]
@ssanderlin This is by-design. It is a very useful behavior to have when attaching graphs. Issue to update the documentation is https://github.com/aspnet/EntityFramework.Docs/issues/505 and PR is https://github.com/aspnet/EntityFramework.Docs/pull/541

**Comment by ssanderlin** [comment]
@ajcvickers Thanks for the response - after reviewing the documentation, I understand the purpose of this change.

**Comment by onyand** [comment]
Hi All,
I am having issues with the Entity.Update statement. My entity keys are all specified but it is still defaulting to inserting the row based on the error message below, Is there a fix available? 

"Cannot insert duplicate key row in object '<db entity>' with unique index '<indexname>'. The duplicate key value is (<list of composite column key values).

**Comment by ajcvickers** [comment]
@onyand If you think this is a bug--that is, that there are not or should not be duplicate key values--then please file a new issue with a full description of what you are doing and a runnable solution/project or full code listing that will let us reproduce the problem.

**Comment by onyand** [comment]
Dear Arthur,


Thanks for your feedback. I managed to get a workaround on this by setting the key column attributes with the "IsModified" property to false as shown below.


context.Entry(rowobject).Property(p => p.<columnname>).IsModified = false;


Regards,

D.O.

________________________________

**Comment by bpaczkowski** [comment]
@ajcvickers Could this behavior be separated into a different method instead? `AddOrUpdate`? In my opinion `Update` should only do that, update, not insert new records. I would expect `Update` to throw if PK is not provided beforehand, or at least not try to insert a new record.

On a side note, the documentation only mentions disconnected entities, but for the main entity it says it will be added with `Modified` state no matter what, but that is not the case.

**Comment by LuthfieZikriR** [comment]
gak paham aku:(

**Comment by Ibn-Ahmed** [comment]
I'm currently facing an issue where update is adding a new record, instead of updating. It's almost 2024. If the behavior of update in that sense is good for working for graphs then an AddOrUpdate should be included and the Update should throw an error instead of adding a new record.
