### ISSUE TITLE
Documentation for EntityFrameworkCore?

### ISSUE THREAD

**Issue by SetTrend** [dotnet/efcore#10205]
Will we get a comprehensive, printed documentation on Entity Framework Core?

This is important for those professionals amongst us not dealing with this technology every day, so we can get a reference and a profound, structured and comprehensive knowledge without going out on a hunt for bits and pieces of information in issues, cobbled tutorials and [StackOverflow questions](https://stackoverflow.com/questions/47066175/are-there-database-initializers-in-entity-framework-core)?

**Comment by ralmsdeveloper** [comment]
Hello @SetTrend, you've already taken a look at https://docs.microsoft.com/en-us/ef/core/

**Comment by SetTrend** [comment]
Thanks, @ralmsdeveloper.

Yes, I did.

Yet, from my perspective, that documentation doesn't get clear about any of the administrative tasks in regard to EFC, like migrations, database initializers or configuration. Moreover, it doesn't give insights on creating a code-first project on an existing database.

I'm missing something like [this](http://shop.oreilly.com/product/0636920022220.do).

**Comment by ralmsdeveloper** [comment]
I understand, this is very cool your questioning, maybe there are people who want to contribute.

But if you're having trouble with that, I think there are a lot of people here to help you.

**Comment by SetTrend** [comment]
I'm absolutely aware about that. And I'm grateful for this option.

However, I feel there are a number of professional programmers who rather rely on compendiums to comprehensively grasp a technology and eventually fully apprehending what they'll be doing than going the iterative circular path of trying, failing, wondering, asking.

I daresay that decision makers demand such documentation before investing and deciding into using it. The comprehensive (printed) documentation path is quicker and more reliable in regard to budget and timeline than the trial and error path which I tend to believe was a rather venturous enterprise.

**Comment by ajcvickers** [comment]
@SetTrend There is a link on the [docs page](https://docs.microsoft.com/en-us/ef/core/) to download the documentation as a PDF. If the docs we have are missing information, then please file issues on the [docs repo](https://github.com/aspnet/EntityFramework.Docs). Beyond this, we are not investing in writing a book, but we have no problem with others writing books as has historically been the case.

**Comment by SetTrend** [comment]
@ajcvickers :
Thanks, AV. PDF would be perfectly sufficient.

I'll share my concerns at the docs repo then.
