### ISSUE TITLE
Query always pulls all columns

### ISSUE THREAD

**Issue by dbondarchuk** [dotnet/efcore#10201]
Hi,
I'm facing a problem with EF Core 2.0 (also latest 2.1.0-preview* builds too). When I try to select only specific properties from db (it can improve my performance a lot), i always get all columns in result:
```C#
_context.Tasks.Where(x => testsIds.Contains(x.TestId))
                .Select(x => new TaskSimplifiedModel()
                {
                    StartedTime = x.StartedTime,
                    FinishedTime = x.FinishedTime,
                    AdditionalDetailsJson = x.AdditionalDetailsJson,
                    Status = x.Status,
                    CreatedTime = x.CreatedTime,
                    Percentage = x.Percentage,
                    CoverageRunId = x.CoverageRunId,
                    CoverageRunTargetType = x.CoverageRunTargetType,
                    IsFailed = x.IsFailed,
                    TestName = x.TestName,
                    Id = x.Id,
                    TestId = x.TestId,
                    RunTimeMilliseconds = x.RunTimeMilliseconds,
                    TriggerType = x.TriggerType,
                    User = new UserListModel
                    {
                        Id = x.User.Id,
                        CreatedByUserId = x.User.CreatedByUserId,
                        Avatar = x.User.Avatar,
                        CreationTime = x.User.CreationTime,
                        Email = x.User.Email,
                        FirstName = x.User.FirstName,
                        LastName = x.User.LastName,
                        Role = x.User.Role,
                        UserName = x.User.UserName
                    },
                    UserId = x.UserId,
                }).OrderBy(request.SortModel).Skip((request.Page - 1) * request.ItemsPerPage).Take(request.ItemsPerPage)
```

It gives me all properties in SQL:
```SQL
SELECT [x].[Id], [x].[AdditionalDetailsJson], [x].[CompanyId], [x].[CoverageRunId], [x].[CoverageRunTargetType], [x].[CreatedTime], [x].[FinishedTime], [x].[IsCompleted], [x].[Percentage], [x].[RunTimeMilliseconds], [x].[RunnersJson], [x].[StartedTime], [x].[Status], [x].[TestId], [x].[TestJson], [x].[TestName], [x].[TriggerType], [x].[UserId], [x.User].[CreatedByUserId], [x.User].[Avatar], [x.User].[Email], [x.User].[FirstName], [x.User].[LastName], [x.User].[UserName], [x.User].[CreationTime], [x.User].[Role]
FROM [Tasks] AS [x]
LEFT JOIN [Users] AS [x.User] ON [x].[UserId] = [x.User].[Id]
WHERE [x].[TestId] IN (
    SELECT [x0].[Id]
    FROM [Tests] AS [x0]
    WHERE [x0].[ApplicationId] = @__applicationId_0
)
ORDER BY [x].[CreatedTime] DESC
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
```
I've seen issues related to EF < 2.0.0 and so upgraded to 2.0.0 (and later 2.1.0-preview1-27377). But issue still exists

**Comment by maumar** [comment]
Can you also provide listing for your entities (tasks and users) as well as contents of onmodelcreating?

**Comment by Tarig0** [comment]
Have you tried moving the select after the skip and take?

**Comment by dbondarchuk** [comment]
@Tarig0 Yes, I've tried it. Result is the same

@maumar Task:
`public class Task
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Trigger type
        /// </summary>
        public TriggerType TriggerType { get; set; }

        /// <summary>
        /// Id of the user, that created the task
        /// </summary>
        public long? UserId { get; set; }

        /// <summary>
        /// User, that created the task
        /// </summary>
        public virtual User User { get; set; }

        /// <summary>
        /// Task status
        /// </summary>
        public TaskStatus Status { get; set; }

        /// <summary>
        /// Completion percentage
        /// </summary>
        public int Percentage { get; set; }

        /// <summary>
        /// Task runners
        /// </summary>
        [NotMapped]
        public IEnumerable<TaskRunner> Runners
        {
            get => !string.IsNullOrEmpty(RunnersJson)
                ? JsonConvert.DeserializeObject<List<TaskRunner>>(RunnersJson)
                : null;
            set => RunnersJson = JsonConvert.SerializeObject(value ?? new List<TaskRunner>());
        }

        /// <summary>
        /// Is task completed
        /// </summary>
        public bool IsCompleted { get; set; }

        /// <summary>
        /// Is task failed
        /// </summary>
        [NotMapped]
        public bool IsFailed => Status == TaskStatus.Failed || (!Runners.IsNullOrEmpty() && Runners.Any(x => x.Status == TaskStatus.Failed));

        /// <summary>
        /// Task's company id
        /// </summary>
        public int CompanyId { get; set; }

        /// <summary>
        /// Task's company
        /// </summary>
        [JsonIgnore]
        public Company Company { get; set; }

        /// <summary>
        /// Task runners, serialized in JSON
        /// </summary>
        [JsonIgnore]
        public string RunnersJson { get; set; }

        /// <summary>
        /// Time of task creation
        /// </summary>
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// Time of task starting
        /// </summary>
        public DateTime? StartedTime { get; set; }

        /// <summary>
        /// Time of tasks finishing
        /// </summary>
        public DateTime? FinishedTime { get; set; }
        
        /// <summary>
        /// Test to run
        /// </summary>
        [NotMapped]
        public TestCacheModel Test
        {
            get => !string.IsNullOrEmpty(TestJson) ? JsonConvert.DeserializeObject<TestCacheModel>(TestJson) : null;
            set => TestJson = value != null ? JsonConvert.SerializeObject(value) : string.Empty;
        }

        /// <summary>
        /// Test, serialized in JSON
        /// </summary>
        [JsonIgnore]
        public string TestJson { get; set; }

        /// <summary>
        /// Additional details
        /// </summary>
        [NotMapped]
        public TaskAdditionalDetails AdditionalDetails { get; set; }

        /// <summary>
        /// Additional details, serialized in JSON
        /// </summary>
        [JsonIgnore]
        public string AdditionalDetailsJson
        {
            get { return AdditionalDetails != null ? JsonConvert.SerializeObject(AdditionalDetails) : string.Empty; }
            set { AdditionalDetails = !string.IsNullOrEmpty(value) ? JsonConvert.DeserializeObject<TaskAdditionalDetails>(value) : new TaskAdditionalDetails(); }
        }

        /// <summary>
        /// Id of the test to run
        /// </summary>
        public Guid TestId { get; set; }

        /// <summary>
        /// Application run id
        /// </summary>
        public Guid? CoverageRunId { get; set; }

        /// <summary>
        /// Coverage run target type
        /// </summary>
        public TargetType? CoverageRunTargetType { get; set; }

        /// <summary>
        /// Application Run
        /// </summary>
        public virtual CoverageRun CoverageRun { get; set; }

        /// <summary>
        /// Total time of task run (milliseconds)
        /// </summary>
        public long? RunTimeMilliseconds { get; set; }

        /// <summary>
        /// Total time of task run
        /// </summary>
        [NotMapped]
        public TimeSpan? RunTime => RunTimeMilliseconds != null 
            ? TimeSpan.FromMilliseconds(RunTimeMilliseconds.Value) 
            : (TimeSpan?)null;

        /// <summary>
        /// Test name
        /// </summary>
        public string TestName { get; set; }
    }`

User:
`public class User
    {
        /// <summary>
        /// Id
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// User's company id
        /// </summary>
        public int CompanyId { get; set; }

        /// <summary>
        /// User's company
        /// </summary>
        [JsonIgnore]
        public virtual Company Company { get; set; }

        /// <summary>
        /// Id of the user, that created this user
        /// </summary>
        public long? CreatedByUserId { get; set; }

        /// <summary>
        /// User, that created this user
        /// </summary>
        [JsonIgnore]
        public virtual User CreatedByUser { get; set; }

        /// <summary>
        /// User role
        /// </summary>
        public UserRole Role { get; set; }

        /// <summary>
        /// UserName
        /// </summary>
        [Required]
        [MaxLength(64)]
        public string UserName { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        [Required]
        [MaxLength(64)]
        public string Password { get; set; }

        /// <summary>
        /// First name
        /// </summary>
        [Required]
        [MaxLength(64)]
        public string FirstName { get; set; }

        /// <summary>
        /// Last name
        /// </summary>
        [Required]
        [MaxLength(64)]
        public string LastName { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        [Required]
        [MaxLength(300)]
        public string Email { get; set; }

        /// <summary>
        /// Time of user creation
        /// </summary>
        public DateTime CreationTime { get; set; }

        /// <summary>
        /// Avatar file name
        /// </summary>
        public string Avatar { get; set; }

        /// <summary>
        /// User language
        /// </summary>
        public Language Language { get; set; }

        /// <summary>
        /// TimeZone id to look up in TimeZoneInfo
        /// </summary>
        public string TimeZone { get; set; }

        /// <summary>
        /// NotificationSettings, serialized in JSON
        /// </summary>
        [JsonIgnore]
        public string NotificationSettingsJson
        {
            get { return NotificationSettings != null ? JsonConvert.SerializeObject(NotificationSettings) : string.Empty; }
            set { NotificationSettings = !string.IsNullOrEmpty(value) ? JsonConvert.DeserializeObject<UserNotificationSettings>(value) : null; }
        }

        /// <summary>
        /// Steps
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public UserNotificationSettings NotificationSettings { get; set; }

        /// <summary>
        /// UserRecover, serialized in JSON
        /// </summary>
        [JsonIgnore]
        public string UserRecoverJson
        {
            get { return UserRecover != null ? JsonConvert.SerializeObject(UserRecover) : string.Empty; }
            set { UserRecover = !string.IsNullOrEmpty(value) ? JsonConvert.DeserializeObject<UserRecover>(value) : null; }
        }

        /// <summary>
        /// User password recover
        /// </summary>
        [JsonIgnore]
        [NotMapped]
        public UserRecover UserRecover { get; set; }

        /// <summary>
        /// User's groups
        /// </summary>
        public virtual ICollection<UserGroupUser> UserGroupUsers { get; set; }
    }`

I want to get rid of all properties with 'Json' suffix, as they are large and I don't need them in list model. Only when I select only specific item

**Comment by Tarig0** [comment]
Looks like projection is only happening on the user property. Just to check could you do a select new {list of props} with out Newing a nested object. Just to see if the sql generates correctly

**Comment by dbondarchuk** [comment]
You mean not to create User object and property at all?

**Comment by dbondarchuk** [comment]
`SELECT [x].[Id], [x].[AdditionalDetailsJson], [x].[CompanyId], [x].[CoverageRunId], [x].[CoverageRunTargetType], [x].[CreatedTime], [x].[FinishedTime], [x].[IsCompleted], [x].[Percentage], [x].[RunTimeMilliseconds], [x].[RunnersJson], [x].[StartedTime], [x].[Status], [x].[TestId], [x].[TestJson], [x].[TestName], [x].[TriggerType], [x].[UserId]
FROM [Tasks] AS [x]
WHERE [x].[TestId] IN (
    SELECT [x0].[Id]
    FROM [Tests] AS [x0]
    WHERE [x0].[ApplicationId] = @__applicationId_0
)
ORDER BY [x].[CreatedTime] DESC`

**Comment by dbondarchuk** [comment]
If I set **User** property to null

**Comment by dbondarchuk** [comment]
My main point, that I don't want to see `[x].[RunnersJson]` and `[x].[TestJson]` props, as they are large and not needed in my show list. But i need *User* object there

**Comment by dbondarchuk** [comment]
Finally, got it.
The problem was in `IsFailed` property, which was auto calculated in *Task* model.

**Comment by Tarig0** [comment]
I guess that would make sense since EF isn't sure what properties are required for the "calculated field"
