### ISSUE TITLE
Entity with int? primary key results in "Unable to track an entity of type 'Settings' because primary key property 'Id' is null." exception even though it is using an identity column

### ISSUE THREAD

**Issue by jemiller0** [dotnet/efcore#10237]
I have an entity class defined as the following with a primary key column that is defined as a nullable int. By convention, the Id property is configured as the primary key and as an identity column.

```
public partial class Settings
{
    public virtual int? Id { get; set; }
    ...
}
```

When I attempt to save a Settings object like the following.

```
using (var oc = new OleContext())
{
    var s = new Settings();
    oc.Settings.Add(s);
    oc.SaveChanges();
}
```

An `InvalidOperationException` is thrown with a message of "Unable to track an entity of type 'Settings' because primary key property 'Id' is null."

```
[InvalidOperationException: Unable to track an entity of type 'Settings' because primary key property 'Id' is null.]
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry) +302
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue) +1095
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue) +140
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property) +253
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry) +422
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager) +353
   Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges() +64
   Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) +39
```

If I set the Id value to 0 before calling `SaveChanges()`, it object is saved without error.

I prefer to use a int? rather than an int for my primary key values because I think null represents no value better than 0. Also, I think it is better to do that that way with regard to data binding in the UI. I.e. if I have an Id field in the UI and it hasn't been assigned by the database yet, I prefer for it to appear as blank rather than 0.

Note, nullable int works fine in EF 6. I think the behavior should be changed to match EF 6.

I'm using .NET Framework 4.7.1 and EF Core 2.0.

**Comment by ajcvickers** [comment]
@jemiller0 I put your code into the console app below to attempt to reproduce this, but I don't see the behavior you are describing. Can you look at the listing and figure out how to change it until it shows the behavior you are seeing?
```C#
public class Settings
{
    public virtual int? Id { get; set; }
}

public class OleContext : DbContext
{
    public DbSet<Settings> Settings { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TestDatabase;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new OleContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using (var oc = new OleContext())
        {
            var s = new Settings();
            oc.Settings.Add(s);
            oc.SaveChanges();
        }

        using (var oc = new OleContext())
        {
            Console.WriteLine(oc.Settings.Single().Id);
        }
    }
}
```

**Comment by jemiller0** [comment]
@ajcvickers I think I see what is happening. The problem that I ran into was in the following code when `id` is `null`. It creates a new `Settings` object. Then it adds it to the context. Then is updates the object from the web form values. I checked it in the debugger. I noticed that when I called `Add()`, the `Id` value was set to `-2147482647`. Then it was set to null when I called `TryUpdateModel()`. I tried adding a second Settings object to the context and checked its value. It was `-2147482646`. I'm thinking that EF Core must use negative values starting at `int.MinValue + 1` as an id for identity columns until they've actually been assigned by the database? I'm thinking it must do this so that it can do hash table lookups. I don't know if EF 6 did this also. I just know that the code below works fine with EF 6, but, throws the exception on EF Core. Probably it would make more sense for me to not add the object to the context until after the `ModelState` is confirmed valid anyway. But, if there is a way to make EF Core behave the same way as EF 6 it might be nice from a compatibility standpoint. It's not the end of the world if not though. At first I was worried that I might have to change all my PK properties to `int` instead of `int?` since I think the example code may show it that way. I prefer to use nullables myself though. Now that I see what is happening, it is less of a worry.

```
        public void SettingsFormView_UpdateItem(int? id)
        {
            Settings s;
            if (id != null)
            {
                s = oleContext.Settings.SingleOrDefault(s2 => s2.Id == id);
                if (s == null)
                {
                    ModelState.AddModelError("InsertUpdate", "Settings was not found");
                    return;
                }
            }
            else
            {
                s = new Settings { CreationTime = DateTime.Now, CreationUserName = (string)Session["UserName"] };
                oleContext.Settings.Add(s);
            }
            TryUpdateModel(s);
            //if (s.Id == null) s.Id = 0;
            s.LastWriteUserName = (string)Session["UserName"];
            s.LastWriteTime = DateTime.Now;
            if (ModelState.IsValid)
            {
                oleContext.SaveChanges();
                Response.Redirect("Default.aspx");
            }
        }

```

**Comment by ajcvickers** [comment]
@jemiller0 There isn't a way to make this behave like EF6--it has a different architecture around entities in the Added state. Setting the values before Add seems most appropriate in this case.

**Comment by jemiller0** [comment]
No problem now that I see what it's doing. Thanks.

**Comment by ivanromakh** [comment]
I have such problem when used 'partial' keyword. Without partial no exception

**Comment by ajcvickers** [comment]
@ivanromakh If you believe you are seeing a bug, then please file a new issue with a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ivanromakh** [comment]
@jemiller0 Sorry just tried  to set up project but forget to create database and see this error. No bug:)

**Comment by Enter55** [comment]
Did you find a solution because I have a similar problem. I have set a string as primary key
