### ISSUE TITLE
SqlServerMigrationsSqlGenerator missing dependency object

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10233]
``` csharp
public SqlServerMigrationsSqlGenerator(
    MigrationsSqlGeneratorDependencies dependencies,
    IMigrationsAnnotationProvider migrationsAnnotations)
    : base(dependencies)
{
    // ...
}
```

**Comment by ajcvickers** [comment]
@bricelam Up to this point, provider implementations of services do not get dependency objects. This is because providers don't depend on the these base classes. However, I can see this would be useful for any public service implementations in the provider, but I don't think we have many of those.

**Comment by ajcvickers** [comment]
Make sure to do this in a non-breaking way.

**Comment by ajcvickers** [comment]
Part of #12084
