### ISSUE TITLE
System.IO.FileNotFoundException when using Xamarin Forms

### ISSUE THREAD

**Issue by frogcrush** [dotnet/efcore#10234]
When trying to use with a Xamarin Forms application, I keep receiving the following error message:

![image](https://user-images.githubusercontent.com/6116333/32520758-f28f6dde-c3c5-11e7-895e-a456ff7cdb2b.png)

It's happened over two computers (one with a fresh VS2017 install). 

Microsoft.EntityFrameworkcore.Sqlite and Microsoft.EntityframeworkCore is referenced in both the .NET Core "shared" project and the .Android project.

### Steps to reproduce
Attempt to use Microsoft.EntityFrameworkCore.Sqlite with a Xamarin Forms project

### Further technical details
EF Core version: 2.0.0
Database Provider: e.g. Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio Community 2017

**Comment by divega** [comment]
This issue was moved to xamarin/xamarin-android#1275

**Comment by divega** [comment]
Reopening to decide in triage whether we want to keep this for tracking purposes.
