### ISSUE TITLE
Consider support for no param BuildWebHost() detection in design tools

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#10230]
Say, I don't want to use `WebHost.CreateDefaultBuilder(args)`, but I have my own builder method where I don't use the `args` parameters, because its not necessary.

Example:
``` c#
public class Program
{
    public static void Main() =>
        BuildWebHost().Run();

    public static IWebHost BuildWebHost() => // Note that there is no `string[] args` parameter on this method.
        new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
}
```

Currently (in 2.0) the EFCore design tools will throw the the following error when trying to build the service provider: `An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Parameter count mismatch.`. This is because it tries to run `BuildWebHost(args)` instead of `BuildWebHost()`.

It would be nice to have support for a no args `BuildWebHost` method.

**Comment by bricelam** [comment]
The ASP.NET team defines the pattern--we just consume it. In 2.1, [it's changing](https://github.com/aspnet/Announcements/issues/275) to the following:

``` csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    // ...
}
```

To discuss supporting additional patterns, you'll need to create an issue on [aspnet/Hosting](https://github.com/aspnet/Hosting).

**Comment by nphmuller** [comment]
Will do. Thanks!
