### ISSUE TITLE
Make SqlServerHistoryRepository non-Internal

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10232]
Right now, the `SqlServerHistoryRepository` class is in a `.Internal` namespace. However, [Customizing the Migrations history table](http://www.bricelam.net/2017/01/04/efcore-history-table.html) should be a supported scenario.

**Comment by ajcvickers** [comment]
Note: when making this public add some notes to the API docs indicating the risks of customizing the history table and keeping it in sync--it doesn't play a part in the normal migrations process.

**Comment by bricelam** [comment]
I added a note to the docs too.

**Comment by ajcvickers** [comment]
We haven't heard any demand for this, so for now we are closing. Please comment if this is something you providing details of what you are trying to do and we will re-assess.
