### ISSUE TITLE
For Graphql, For OData in the feature

### ISSUE THREAD

**Issue by seven1986** [dotnet/efcore#10238]
For now, we need a strong query function， we can use 
### But, we need 
```
db.Users.FromOData("expression") 
db.FromOData<User>("expression") 

db.Users.FromGraphql("expression") 
db.FromGraphql<User>("expression") 
```

**Comment by ajcvickers** [comment]
@seven1986 This request could mean one of two things:
1. Somebody creates EF Core providers for OData (see #7759) or graphql and then these methods would be the natural equivalent of FromSql. We have no plans at this time to create these providers--see #7759--but others in the community could certainly do so, and we would provide guidance as much as possible.
2. These are extension methods that take some kind of raw OData or graphql expression and translate it into an expression tree that can be handled by EF. Note that this may be tricky or even prohibitively difficult for non-trivial expressions. We don't plan to implement these, but again others in the community could give it a try. We would not ship these with the core EF packages--they would be better delivered as third-party packages containing extension methods.
