### ISSUE TITLE
SqlServer.Design & UWP

### ISSUE THREAD

**Issue by GeorgeStephens** [dotnet/efcore#10240]
When adding Microsoft.EntityFrameworkCore.SqlServer.Design (2.0.0-preview1-final) to a project the following error occors on build:

Cannot find type Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames in module Microsoft.EntityFrameworkCore.Relational.dll

When only Microsoft.EntityFrameworkCore.SqlServer (2.0.0) is added the project builds (and runs) fine. 

`   <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">`
      `  <Version>2.0.0</Version>`
    `</PackageReference>`
    `<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design">`
      `<Version>2.0.0-preview1-final</Version>`
    `</PackageReference>`
    `<PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">`
      `<Version>6.0.1</Version>`
    `</PackageReference>`

System Info:
- Visual Studio 2017 (15.4.2) 
- OS Build 16299.19
- Targeting .NET Framework 4.6.1 & Min Target Version 16299

**Comment by ralmsdeveloper** [comment]
Just to understand, for which reason you add Microsoft.EntityFrameworkCore.SqlServer.Design:2.0.0-preview1-final and not Microsoft.EntityFrameworkCore.SqlServer.Design:2.0.0?

**Comment by GeorgeStephens** [comment]
Microsoft.EntityFrameworkCore.SqlServer.Design:2.0.0 does not appear in the NuGet Package Manager:

![image](https://user-images.githubusercontent.com/8162303/32550665-e5983ee2-c485-11e7-97e9-113136b252d2.png)

**Comment by ralmsdeveloper** [comment]
Is the nuget's origin correct?

![package](https://user-images.githubusercontent.com/16335882/32551460-ba0bc1c6-c477-11e7-890d-0c074f7adfda.png)

![02](https://user-images.githubusercontent.com/16335882/32551529-f985547a-c477-11e7-8405-b95f33474602.png)

**Comment by ErikEJ** [comment]
Microsoft.EFCore.SqlServer.Design is not available in version 2.0, the code is included in Microsoft.EFCore.SqlServer 2.0

**Comment by GeorgeStephens** [comment]
Yep

![image](https://user-images.githubusercontent.com/8162303/32555634-3fe7efbe-c495-11e7-9bac-ae3a8cecdc08.png)

**Comment by ralmsdeveloper** [comment]
Erik, you're right, I had not looked into this because I had in my NuGetFallbackFolder this compiled version.

No need to install. 
I just looked at Microsoft.EntityFrameworkCore.Design and not for Microsoft.EntityFrameworkCore.SqlServer.Design

Thank you Erik.
