### ISSUE TITLE
Adding child type of a registed type gives error

### ISSUE THREAD

**Issue by inlineHamed** [dotnet/efcore#10247]
Assume I have this model:
```
class A{...}
class B: A{...}
```
and A is registered for entity framework (by having `public DbSet<A> A{set;get;}` in DbContext) so its OK doing this:

```
// a is of type A
context.Add(a);
```
I was thinking that this should work too:
```
//b is of type B
context.Add(b)
```

and as B is not registed treat b as an A and add a row in A table
but It gives:
` The entity type 'B' was not found. Ensure that the entity type has been added to the model.`

**Comment by ajcvickers** [comment]
@hmdhasani Derived types are not discovered automatically in EF Core. You'll need to either create a `DbSet` property for B on the context, or make an `.Entity` call for it in OnModelCreating.
