### ISSUE TITLE
Question: how do I access the constraint name on a foreign key or index?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#10252]
I am trying to compare the `context.Model` with an actual database and I need to find the foreign key constraint name to compare. I have looked at `IEntityType`'s `GetForeignKeys()`  and `GetIndexes()` methods and what they, and `Relational()` return but I can't find a hint of the constraint name.

Any help gratefully received.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
On the IForeignKey object, call `.Relational().Name`.
