### ISSUE TITLE
dotnet cli error when executing: dotnet ef dbcontext scaffold

### ISSUE THREAD

**Issue by lymberl** [dotnet/efcore#10251]
Using EF CORE 2.0 with Mac OS terminal and visual studio for Mac.

the following dotnet cli command fails when the connection string password has a symbol like !(exclamation mark) You get error "-bash: !: event not found".

Command to replicate issue is. Just use your own azure DB: dotnet ef dbcontext scaffold "Server=tcp:test.database.windows.net,1433;Initial Catalog=test;Persist Security Info=False;User ID=test;Password=test!test!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c testDbContext

**Comment by ajcvickers** [comment]
Looks like you will have to make sure that character is escaped, as per however bash does escaping--quick search indicates bash uses the backslash `\`.

**Comment by Ibrokola** [comment]
Did you eventually solve this? Getting the same error, which is becoming quite frustrating right now...

**Comment by Ibrokola** [comment]
Solved
