### ISSUE TITLE
Is it possible to make a property with composite foreign key nullable when part of the key has value?

### ISSUE THREAD

**Issue by SirGordon** [dotnet/efcore#10250]
I'm sorry if this is a database question than ORM.

Structure must always have a valid RuleBook value, but it should sometimes have CurrentQuestion = null. Considering that CurrentQuestion in it's composite key uses the same RuleBookId field that is used for the RuleBook field, would it be possble to have a Structure with RuleBookId set, but CurrentQuestionId unset and have EF core consider this situation as CurrentQuestion == null instead of throwing exception?

Do i have to make another RuleBookIdForCurrentQuestion field with the same value as RuleBookId when CurrentQuestionId is set, and have no value when CurrentQuestionId is unset?

```
Exception message:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23503: insert or update on table "structure" violates foreign key constraint "FK_structure_question_current_question_id_rule_book_id"
Stack trace:
is it really needed?
```

```c#
class Structure {
  [Key]
  public int Id { get; set; }
  public int RuleBookId { get; set; }
  public int CurrentQuestionId { get; set; }

  [ForeignKey("RuleBookId"), Required]
  public RuleBook RuleBook { get; set; }

  [ForeignKey("CurrentQuestionId, RuleBookId")]
  public Question CurrentQuestion {get; set;}
}

class RuleBook {
  [Key]
  public int Id {get; set;}
}

class Question {
  public int Id { get; set; }
  public int RuleBookId { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder) {
  modelBuilder.Entity<Question>().HasKey(question => new { question .Id, question .RuleBookId });
}

void AddStructure(RuleBook ruleBook) {
  new Structure() {
    RuleBook = ruleBook,
  }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio Community 2017

**Comment by ajcvickers** [comment]
@SirGordon It looks like CurrentQuestionId could just be made nullable.

**Comment by SirGordon** [comment]
@ajcvickers Do you mean changing type to
```
public int? CurrentQuestionId { get; set; }
```

**Comment by ajcvickers** [comment]
@SirGordon Yes.

**Comment by SirGordon** [comment]
@ajcvickers wow, that worked, thank you very much!

**Comment by los93sol** [comment]
Sorry to dig up an old issue, but this nullable properties don't seem to work with composite keys in entity framework core 3.0....at least with the specific provider I'm using, npgsql.  Not sure if this issue should go here or on their repo

**Comment by ajcvickers** [comment]
@los93sol It shouldn't be here, since this is a closed issue. Create a small repro and test it against both SQLite (which has pretty much no infrastructure requirements) and PosrgreSQL. If it fails on both, then file a new issue on this repo, else file it on the PostgreSQL repo. Include your repro code either.
