### ISSUE TITLE
how to perform an EF Core operation and an ADO.NET SqlClient  operation in the same transaction,Using db.Database.BeginTransaction

### ISSUE THREAD

**Issue by zolf1983** [dotnet/efcore#10262]
```C#
public void  Mian()
{
 using (var transaction = db.Database.BeginTransaction())
            {try
                {
                   var aa = db.Bookes.ToList();
                   db.SqlQuery<SQLDTO.ReceiveUserNameDTO>(param);
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                }
            }
}

public static IList<T> SqlQuery<T>(this DbContext db, CommandType type, string sql, List<SqlParameter> parameters) where T : new()
        {
            var conn = db.Database.GetDbConnection();
            try
            {
                if (conn.State == System.Data.ConnectionState.Closed)
                    conn.Open();
                using (var command = conn.CreateCommand())
                {
                      using (var reader = command.ExecuteReader())
                     {
                     }
                }
}
```

How can i using transaction in SqlQuery?
using :EF Core 1.0+VS2015

thanks,

**Comment by ajcvickers** [comment]
@zolf1983 Can you be more specific about what you mean by "using transaction"? In general, if EF begins a transaction with BeginTransaction, then any commands executed on that connection can participate in that transaction.

**Comment by zolf1983** [comment]
@ajcvickers 
public IActionResult Index(int? companyId, int? serviceId, int? HospitalId)
        {
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var list = db.Users.ToList();
                    var list2 = db.SqlQuery<ResultDTO>(CommandType.Text,
                         " SELECT top 100 UserName,TrueName FROM [dbo].[AspNetUsers]", null).ToList();
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                }
            }
            return View();
        }

public static IList<T> SqlQuery<T>(this DbContext db, CommandType type, string sql, List<SqlParameter> parameters) where T : new()
        {
            var conn = db.Database.GetDbConnection();
            try
            {
                if (conn.State == System.Data.ConnectionState.Closed)
                    conn.Open();
               // conn.EnlistTransaction
                using (var command = conn.CreateCommand())
                {
                    
                    command.CommandText = sql;
                    command.CommandType = type;
                    if (parameters != null && parameters.Count() > 0)
                    {
                        foreach (var item in parameters)
                        {
                            DbParameter p = command.CreateParameter();
                            p.DbType = item.DbType;
                            p.ParameterName = item.ParameterName;
                            p.Value = item.Value;
                            command.Parameters.Add(p);
                        }
                    }
                    var propts = typeof(T).GetProperties();
                    var rtnList = new List<T>();
                    T model;
                    object val;
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            model = new T();
                            foreach (var l in propts)
                            {
                                val = reader[l.Name];
                                if (val == DBNull.Value)
                                    l.SetValue(model, null);
                                else
                                    l.SetValue(model, val);
                            }
                            rtnList.Add(model);
                        }
                    }
                    return rtnList;
                }
            }
            catch (Exception ex)
            {
                return null;
            }
        }


            public class ResultDTO
            {
                public string UserName { get; set; }
                public string TrueName { get; set; }
            }


In the main method, Begin EF core Transaction.  I using this dbcontext Connection CreateCommand in  SqlQuery.  Using this ADO.NET Operation database.

The program will be errors at command.ExecuteReader() . ExecuteReader requires commands to have transactions，Transaction property have not Initialization  of this command. have can i get db.transaction using command?

**Comment by ajcvickers** [comment]
@zolf1983 After creating the command it needs to have the transaction set. For example:
```C#
command.Transaction = db.Database.CurrentTransaction.GetDbTransaction();
```
