### ISSUE TITLE
Feature proposal: InMemoryStorage hooks per entity

### ISSUE THREAD

**Issue by AlphaGit** [dotnet/efcore#10261]
## Use case

I understand that the InMemoryStorage is currently meant to be a simple storage, non-relational "database" for simple testing. I also understand that the recommended approach when the application relies on database behavior is to use an in-memory database for testing.

However, given that not all database providers provide a simple way of using their database in an in-memory storage, and given that it's even less likely that there is a provider that can be hooked to EF Core -- this feature proposal is meant to shorten that gap a little bit.

## Idea

Let's say that we could customize the behavior of the InMemoryStorage, only applying changes to the entities simulating the transformations or the checks that a real database would perform. This behavior should not be built as part of the InMemoryStorage itself (first, because of it's primary goal, and second, because needs for each DB are different), so making it configurable and deferring the behavior to consumers makes it simpler and it allows for the community to extend on it.

Imagine if we could configure the provider in such a way (this is a half baked idea, so take it with a grain of salt):

```csharp
services.AddDbContext<MyDbContext>(options => 
    options.UseInMemoryDatabase<MyInMemoryConfigurator>();
);

class MyInMemoryConfigurator : InMemoryConfigurator
{
    override void OnProviderConfiguration(ProviderConfigurationBuilder builder)
    {
        // example one: simulating database generated values
        builder.Entity<MyEntity1>().OnRead(entity => {
            entity.MyDatabaseGeneratedColumn = someValue;
        });

        // example two: simulating referential integrity
        builder.Entity<MyEntity1>().OnUpdate((entity, currentStore) => {
            if (!currentStore.Any<Entity2>(e2 => e2.Id == entity.ForeignKeyValue))
                throw new ForeignKeyViolationException("some message");
        });
    } 
}
```

I haven't fully thought of the full design for this, but rather just these examples to illustrate the idea.

The only burden that the InMemoryStorage provider would have to implement (aside from invoking these registered classes) would be to invoke each actions with the right parameters when information is saved into the context or retrieved from it.

If you read so far, I really appreciate your attention and time, and I hope this is useful. If this is completely out of scope for the present or the future of EF, please let me know where so I can send these kind of recommendations to the right place.

Regards!

**Comment by ajcvickers** [comment]
@AlphaGit There are some interesting ideas here--specifically, the ability to create a "test double" database provider that is configured to work like a real database for the purpose of testing code that uses EF. However, it doesn't seem like the existing in-memory provider is the best place for this, although you could override some of the services and try things out if you wanted. Also, this is probably not something that the EF  team would do or that would live in the EF code--it seems like something that would be better run as a community project with a third-party package.

**Comment by AlphaGit** [comment]
@ajcvickers Thanks a lot for the response! Do you happen to have any pointers about which services I could look into for this? Thanks again!

**Comment by ajcvickers** [comment]
@AlphaGit Maybe `IInMemoryTableFactory`? The list of services added for the in-memory provider is probably a good place to start:

```C#
var builder = new EntityFrameworkServicesBuilder(serviceCollection)
    .TryAdd<IDatabaseProvider, DatabaseProvider<InMemoryOptionsExtension>>()
    .TryAdd<IValueGeneratorSelector, InMemoryValueGeneratorSelector>()
    .TryAdd<IDatabase>(p => p.GetService<IInMemoryDatabase>())
    .TryAdd<IDbContextTransactionManager, InMemoryTransactionManager>()
    .TryAdd<IDatabaseCreator, InMemoryDatabaseCreator>()
    .TryAdd<IQueryContextFactory, InMemoryQueryContextFactory>()
    .TryAdd<IEntityQueryModelVisitorFactory, InMemoryQueryModelVisitorFactory>()
    .TryAdd<IEntityQueryableExpressionVisitorFactory, InMemoryEntityQueryableExpressionVisitorFactory>()
    .TryAdd<IEvaluatableExpressionFilter, EvaluatableExpressionFilter>()
    .TryAdd<ISingletonOptions, IInMemorySingletonOptions>(p => p.GetService<IInMemorySingletonOptions>())
    .TryAddProviderSpecificServices(
        b => b
            .TryAddSingleton<IInMemorySingletonOptions, InMemorySingletonOptions>()
            .TryAddSingleton<IInMemoryStoreCache, InMemoryStoreCache>()
            .TryAddSingleton<IInMemoryTableFactory, InMemoryTableFactory>()
            .TryAddScoped<IInMemoryDatabase, InMemoryDatabase>()
            .TryAddScoped<IMaterializerFactory, MaterializerFactory>());
```
