### ISSUE TITLE
Tool for visualizing a model

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#1027]
Similar to the **View Entity Data Model (Read-only)** command in the EF Power Tools.

**Comment by rogerhendriks** [comment]
This would be a great feature. You once made that super difficult edmx with a nice designer so this should be easy ;) But please do not forget to support views better this time.

**Comment by bricelam** [comment]
Future @bricelam, don't forget about the super early prototype you started in [bricelam/EFDesigner](https://github.com/bricelam/EFDesigner). You didn't get very far, but it might be a good starting point. You at least got it to do this:

![image](https://cloud.githubusercontent.com/assets/1226749/7569562/77531178-f7be-11e4-9360-8bbd7c8f3605.png)

**Comment by divega** [comment]
Future @bricelam, it would be sweet if we could do something that worked with Visual Studio Code, although at present we don't know how that would look like :smile:

**Comment by itanex** [comment]
Is there any progress on the Model Visualizer? I would love to utilize this with my students who I teach EF basics to.

**Comment by bricelam** [comment]
@itanex No significant progress. [LLBLGen Pro](https://docs.microsoft.com/en-us/ef/core/extensions/llbl-gen-pro) and [DevArt Entity Developer](https://www.devart.com/entitydeveloper/) are the two EFCore-compatible modelling tools I that know about. (This is not an endorsement. 😇)

**Comment by itanex** [comment]
@bricelam Thanks for getting back. I was not impressed with DevArt tools. I will check out LLBLGen

**Comment by mguinness** [comment]
@itanex I had the opposite experience, I wasn't impressed with LLBLGen (not intuitive) but liked Entity Developer.  I guess we may have different requirements, but I thought that DevArt provides a similar experience to the old EDMX designer.

I'd recommend anybody that still needs database first take a look at the [express edition](https://www.devart.com/entitydeveloper/editions.html) which although limited to 10 tables does give you a flavor.  Ideally "future bricelam" will get to revisit his early prototype :)

**Comment by ErikEJ** [comment]
FYI: I am getting quite close to a implementation of this in my "EF Core Power Tools" https://github.com/ErikEJ/SqlCeToolbox/issues/462

**Comment by ajcvickers** [comment]
This is a good idea and we are fully supportive of community efforts in this area, but we don't intend at this time to implement or maintain this in the EF team.

**Comment by MarcoLoetscher** [comment]
It's a very bad decision to close this issue. This is a [high priority feature](https://github.com/aspnet/EntityFrameworkCore/wiki/roadmap#high-priority-features) on  your roadmap. If the costs are too high to ship the function with Visual Studio, it can be provided as an extension. I don't understand why the world's largest software company (Microsoft) cannot recruit enough staff for this project (EF Core). I hope that as many developers as possible will protest against it.

**Comment by ErikEJ** [comment]
@MarcoLoetscher Have you tried my free Visual Studio extension (EF Core Power Tools)?
I would be happy to work with you on anything that you miss.

**Comment by MarcoLoetscher** [comment]
@ErikEJ We use EF 6. x in an extensive WPF business application. Unfortunately, there are still some features missing in EF Core for us, so we haven't used EF Core Power Tools yet. Thank you for your work on this extension. The "DbContext Model Diagram" looks very rudimentary for me in comparison to the "Entity Data Model (Read-only)" view in EF Power Tools. I hope that this diagram can be displayed in the future like the old one.

**Comment by ErikEJ** [comment]
What are you missing - maybe I could add it?

Do you want to create a model from a diagram - this is not this "feature" and not supported/mentioned by the team (EDMX no longer exists) - you can look at the 2 third party tools listed here to help with that: https://docs.microsoft.com/en-us/ef/core/extensions/

**Comment by MarcoLoetscher** [comment]
No, I just want to display a read-only model of the DbContext. The Entity Data Model of the [old](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/advanced-entity-framework-scenarios-for-an-mvc-web-application/_static/image15.png) EF Power Tools was much clearer than that of the [new](https://raw.githubusercontent.com/ErikEJ/SqlCeToolbox/master/img/efcreveng3.png) one.

**Comment by mguinness** [comment]
@MarcoLoetscher IMHO your best bet would be to use [Entity Developer](https://www.devart.com/entitydeveloper/editions.html) as it's the closest replacement I could find for the old EDMX designer.  I'd encourage you to try the Express Edition (which is limited to 10 tables) to see if it meets your needs.

![image](https://user-images.githubusercontent.com/14002844/29324877-80a1a952-819a-11e7-97dd-3b11ce87ffbf.png)

**Comment by julielerman** [comment]
I agree with @MarcoLoetscher . It's a tool I cannot build models without and we need it for cross-platform work. I'm happy to use @ErikEJ tool when I'm on windows in vs2017. But that's not my most common scenario. Future @bricelam :  
![please](https://user-images.githubusercontent.com/5007120/37348316-2bf4ea80-26aa-11e8-8c1e-0ae2acb6e1ed.gif)
:)

**Comment by ErikEJ** [comment]
Would SVG format work for you, @Julielerman ?

**Comment by julielerman** [comment]
@ErikEJ The format is not the issue but where I can run it from. If you could take the work you did to make it happen in VS 2017 without depending on the class designer and have an extension for VS Code, that would be amazaballs!

**Comment by vslee** [comment]
Here's another project which can generate diagrams from existing code. It can also create code from diagrams, similar to "Model First" in EF Classic. 
https://github.com/msawczyn/EFDesigner
