### ISSUE TITLE
No DbContext was found in assembly

### ISSUE THREAD

**Issue by IsaaasI** [dotnet/efcore#10287]
Dears,
I am using VS2017 .NET Core 2.0 and I want to use entity framework MYSQL Database but I am facing issues on add-Migration 
------------
No DbContext was found in assembly 'ProjectName'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
-------------------
Microsoft.AspNetCore.All 2.0.0-preview1-final

any help
@bricelam

**Comment by bricelam** [comment]
It sounds like you may need to add an implementation of `IDbContextFactory` to your assembly. In version 2.0.0-preview1-final, we temporarily stopped using the ASP.NET Core application service provider to discover the DbContext. Have you considered upgrading to version 2.0.1?

**Comment by IsaaasI** [comment]
Many Thanks bricelam for your fast replay.
I updeted the package to v2.0.1 and I face the below issue.
Actually, If possible to contact with you on Skype and I will share my screen with you to solve the problem faster .
![image](https://user-images.githubusercontent.com/17950923/32889264-44662686-cadb-11e7-8427-4dbff595ac12.png)

Installed Packages & SDK
![image](https://user-images.githubusercontent.com/17950923/32889398-e2ecae38-cadb-11e7-8fef-d9cc0e8e0c77.png)

**Comment by ralmsdeveloper** [comment]
@IsaaasI 
Remove the _**Microsoft.EntityFrameworkCore.SqlServer.Design**_ dependency, it is not used in version 2.0.

**Comment by smitpatel** [comment]
Also upgrade `Microsoft.AspNetCore.All` to 2.0.3 version.

**Comment by IsaaasI** [comment]
@bricelam Still same issue. required your help.
@ralmsdeveloper I deleted both Microsoft.EntityFrameworkCore.SqlServer.Design & Entity Framework 6.2 and still I have below issue.
![image](https://user-images.githubusercontent.com/17950923/32936079-d56852a0-cb83-11e7-9fb7-4bc1746a9f5a.png)

@smitpatel  I tried many times to update to 2.0.3 but no luck . below the issue.
I already cleared the cache for NuGet and same thing.
![image](https://user-images.githubusercontent.com/17950923/32935890-1b4d34f8-cb83-11e7-831a-46ae24e0b8bf.png)

**Comment by ralmsdeveloper** [comment]
@IsaaasI,
Do this manually, edit your * .csproj file.

Search for:
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />

and replaced by:
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />

Also do this for System.Text.Encoding, the stable version is 4.3.0.

**Comment by IsaaasI** [comment]
@ralmsdeveloper 
I am not able to find the .csproj from the Solution Explorer. I think the structure for VS 2017 and .NET core 2.0 application is different than previous version.
![image](https://user-images.githubusercontent.com/17950923/32955987-9ce4cdc4-cbc8-11e7-88f7-e61961843013.png)

I open it from Window explorer by notepad 
![image](https://user-images.githubusercontent.com/17950923/32956041-bf7a5548-cbc8-11e7-950b-9f11b12bb0cf.png)
I found these statements.
![image](https://user-images.githubusercontent.com/17950923/32956186-2a7de012-cbc9-11e7-8052-8a34c041676e.png)

**Comment by ralmsdeveloper** [comment]
Check this file.

![32956041-bf7a5548-cbc8-11e7-950b-9f11b12bb0cf](https://user-images.githubusercontent.com/16335882/32959905-3a4403ba-cbaa-11e7-8b58-9f249b671cec.png)

**Comment by IsaaasI** [comment]
Yes , True

I fix it but still the migration not work :)

Can I chat with you on any chatting application to solve migration issue? I want only connect .NET Core2.0 app with MYSQL Database by entity framework .

@ralmsdeveloper @bricelam

**Comment by ralmsdeveloper** [comment]
Are you installing the **Microsoft.EntityFramework.SqlServer** package and want to try connecting to **MySQL**?

You will not, wrong package! 

Try using **MySql.Data.EntityFrameworkCore.**

**Comment by bricelam** [comment]
You may need to [update Program.cs](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#update-main-method-in-programcs) too.

**Comment by IsaaasI** [comment]
It is already installed , are you sure the  Entity Framework 6.2 not required ? Brcasue the below error is I think required Entity framwork.
No DbContext was found in assembly '***'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic. 


I delete SqlServer 
@ralmsdeveloper 

I will try update Program.cs now
@bricelam

**Comment by IsaaasI** [comment]
The program.cs is already updated.
![image](https://user-images.githubusercontent.com/17950923/32961644-67498490-cbda-11e7-8981-d22c246cd692.png)

**Comment by ralmsdeveloper** [comment]
Post your DbContext here.

**Comment by IsaaasI** [comment]
![image](https://user-images.githubusercontent.com/17950923/32966150-e9fe3ba6-cbe9-11e7-94fe-27783d0ee3b1.png)

![image](https://user-images.githubusercontent.com/17950923/32966185-ff5d7df4-cbe9-11e7-8061-492875bf80d7.png)

This is my error now.
![image](https://user-images.githubusercontent.com/17950923/32966200-0f81e5f8-cbea-11e7-860f-2471b8a69139.png)

**Comment by ralmsdeveloper** [comment]
I think it would be ideal, you see some articles before, to help you 
better understand, how to use EF Core:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/

https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud

**Comment by smitpatel** [comment]
@IsaaasI - Your project has errors. Before running migrations make sure you can build you project in VS without errors.

**Comment by IsaaasI** [comment]
Thanks a lot @ralmsdeveloper . Finally, I did it . The Migration work fine now.
But :) 
1.enable-migrations -> works fine.
2.Add-Migration -> works fine
![image](https://user-images.githubusercontent.com/17950923/32980187-2b00b550-cc73-11e7-871d-06971ccd8404.png)
3.update-database -> works fine
![image](https://user-images.githubusercontent.com/17950923/32980179-0ca036e4-cc73-11e7-8614-937a1d98a3a7.png)

But I didn't see the table created on my localhost database.

This is my connection string. I am wondering about my schema name , username and password of my database where I put it?
![image](https://user-images.githubusercontent.com/17950923/32980202-6c156220-cc73-11e7-9e40-d9c1a2015bb4.png)

Remark: I am using MySQL Workbenck 6.3 CE 
![image](https://user-images.githubusercontent.com/17950923/32980238-ccafa5d2-cc73-11e7-9e7c-cef0cc78d7c2.png)

**Comment by ralmsdeveloper** [comment]
Its Context is configured to use SQL Server and not MYSQL, so it is impossible to see the tables!

It would be very important to study the documentation!

https://docs.microsoft.com/en-us/ef/core/

or some article that shows how to use Asp.Net Core + EF Core

It looks like you're a little confused :)

I'm sure you can do that.

It would be important for you to search for articles on the internet, there are several good blogs for studies!

one of them is: https://channel9.msdn.com/

The EF team is wonderful, they are super attentive, they always try to respond in the best possible way.

But your case is a bit quirky, because here they usually discuss improvements or bugs in EF.

**Comment by ralmsdeveloper** [comment]
@ajcvickers
