### ISSUE TITLE
Migrations and race condition question

### ISSUE THREAD

**Issue by vitalybibikov** [dotnet/efcore#10291]
Hello,

Currently I'm implementing a Web API, which will be started by ServiceFabric with instance count > 1.
As an API is self-configurable it checks if the db is not fully updated and in case it's not, then it roll-ups all the new migrations it has.

Thus I have a question whether I should implement some kind of a protection (like sp_getapplock) over my database to avoid situation when 2 instances are trying to perform migrations at the same time?

**Comment by ajcvickers** [comment]
@EvilAvenger Yes, if you're going to run migrations as part of application startup, then you will need to make sure protection is in place such that it happens once and only once.
