### ISSUE TITLE
HasQueryFilter doesn't support "contains" in List or Array

### ISSUE THREAD

**Issue by cgehrmann** [dotnet/efcore#10295]
The method HasQueryFilter doesn't support "contains" and evaluates the Query in memory instead of generating an SQL statement like 

```
SELECT [x].AccountId, [x].Name,  [x].TenantId FROM Account as x where [x].TenantId in ( tenantId_0, ...,  tenantId_n)
```

Log Output:

```
Compiling query model: 
'from Account x in DbSet<Account>
select new <>f__AnonymousType0<Guid, string, Guid>(
    [x].AccountId, 
    [x].Name, 
    [x].TenantId
)'

The LINQ expression 'where ___tenantIds_0.Contains([f].TenantId)' could not be translated and will be evaluated locally.
```

### Steps to reproduce
```c#
public class Account{
	public Guid AccountId {get;set}
	public string Name {get;set;}
	
	public Guid TenantId {get;set;}
}

public class DemoContext : DbContext
{
	private readonly List<Guid> _tenantIds;

	public virtual DbSet<Account> Accounts { get; set; }

	public DemoContext(DbContextOptions<DemoContext> options, IEnumerable<Guid> tenantIds)
		: base(options)
	{
		_tenantIds = tenantIds.Where(x => x.HasValue).ToList();
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Account>().HasQueryFilter(e => _tenantIds.Contains(e.TenantId));
	}
}
```

Used Query

```c#
var data = context.Accounts
		.Select(x => new { x.AccountId, x.Name, x.TenantId })
		.ToList();
```

If you use the model without HasQueryFilter

```c#
 var data = context.Accounts
                    .Where(x => tenantIds.Contains(x.TenantId))
                    .Select(x => new { x.AccountId, x.Name, x.TenantId})
                    .ToList();
```

the generated Query looks like

```
SELECT [x].[AccountId], [x].[NAME], [x].[TenantId]
FROM [ng].[Accounts] AS [x]
WHERE [x].[TenantId] IN ('524996ea-5e4e-e611-80bd-0050569e091a', 'd5c43926-d830-e711-80c1-0050569e091a')
```

and works like expected.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows Server 2016
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
It is in a way by-design.
In QueryFilter `_tennantIds` is field on DbContext, which means its value can be changed based on the context running the query.
If we inline the values in the SQL, then when you change the value of `_tennantIds` in another context, we have to recompute the new SQL. Query compilation also has cost associated with it.
So instead we created parameter, so that we can use the already compiled query with new parameters to run the query. While it does client evaluation but it does not need to compile the query again.
Since SqlParameter cannot contain an array, it is client evaluated.

**Comment by ajcvickers** [comment]
Moving this to the backlog since the filter is functional by client evaluation and there may be some complexity in handling the expansion of the list in the filter case.

**Comment by maumar** [comment]
now the filter gets properly translated, rather than inlined
