### ISSUE TITLE
InMemory database data not shared between different DbContext types.

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#10318]
According to the xml docs the `name` parameter in `UseInMemoryDatabase()` should enable us to share the in-memory db anywhere the same name is used. Does this include different type of DbContext classes? Because in version 2.0.1 I can't get this to work.

See the following test:
``` c#
public class ShareMemoryDbTest
{
    [Fact]
    public void ContextsShouldShareData()
    {
        var name = Guid.NewGuid().ToString();

        using (var c1 = new Context1(name))
        {
            c1.Add(new MyEntity());
            c1.SaveChanges();
        }
        using (var c1 = new Context1(name))
        {
            c1.Set<MyEntity>().ToList().Should().HaveCount(1);
        }

        using (var c2 = new Context2(name))
        {
            c2.Set<MyEntity>().ToList().Should().HaveCount(1); // fails with: expected: 1, actually: 0.
        }
    }
}

public class Context1 : DbContext
{
    private readonly string name;

    public Context1(string name)
    {
        this.name = name;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase(name);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>();
    }
}

public class Context2 : DbContext
{
    private readonly string name;

    public Context2(string name)
    {
        this.name = name;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase(name);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>();
    }
}

public class MyEntity
{
    public int Id { get; set; }
}
```

**Comment by ajcvickers** [comment]
@nphmuller This will not work in 2.0.0/2.0.1. It should work in 2.1 with the fix for #9613. However, this might be fragile if the entity type configuration diverges between the two models. Can you give some more details on why you want to do this so we can understand the scenario better?

**Comment by nphmuller** [comment]
@ajcvickers My current scenario is that I have implemented query and save filters in one DbContext, but I want to easily insert objects in the database that bypass the filter. This data will be used in integration tests so I can test all filter logic.

I could extend the filters, so they could be turned on or off, but in that case all my tests rely on that on/off toggle logic. It would make for better tests if I could simply bypass the filter from a DbContext that has no filters defined at all.

**Comment by ajcvickers** [comment]
@nphmuller Thanks for the info.
