### ISSUE TITLE
Setting IsModified value of an 'owned' entity

### ISSUE THREAD

**Issue by ADringer** [dotnet/efcore#10317]
I have a model defined as:
```
 public class Run : Entity
 {      
        public int Id { get; set; }
        public RunAudit Audit { get; set; }
 }

public class RunAudit
 {        
        public string SubmittedBy { get; set; }
        public DateTimeOffset? SubmittedOn { get; set; }
        public string ApprovedBy { get; set; }
        public DateTimeOffset? ApprovedOn { get; set; }
        public string CheckedBy { get; set; }
        public DateTimeOffset? CheckedOn { get; set; }
 }
```

And this is configured as:

```
modelBuilder.Entity<Run>()
                .OwnsOne(x => x.Audit);
```

When I'm updating the `Run` entity, I want to exclude some of the properties of the `Audit` entity. I tried:

`context.Entry(run).Property(x => x.Audit.ApprovedBy).IsModified = false`

But this results in the error:

> The expression 'x => x.Audit.ApprovedBy' is not a valid property expression. The expression should represent a property access: 't => t.MyProperty'.
Parameter name: propertyAccessExpression

How can I manage properties of an owned class?

Thanks

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@ADringer The owned entity must be addressed directly. For example, 
```C#
context.Entry(run.Audit).Property(x => x.ApprovedBy).IsModified = false;
```
