### ISSUE TITLE
ForeignKey constraint not created

### ISSUE THREAD

**Issue by cdie** [dotnet/efcore#10313]
Tried to create a relationship between two tables, with one that have composed primary key, and the foreign key constraint is not created in one table (no exception thrown).

### Steps to reproduce
Here a demonstration code. Tested with EF Core 2.0, 2.0.1 and 2.1 preview last build, same result

```c#
class Tab
    {
        public int Id { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public Tab2 Tab2 { get; set; }
    }

    class Tab2
    {
        public string Val1 { get; set; }
        public string Val2 { get; set; }
        public Tab Tab { get; set; }
        public int? TabId { get; set; }
    }

    class Ctx : DbContext
    {

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
 var e2 = modelBuilder.Entity<Tab2>();
            e2.ToTable("Table2");
            e2.HasKey("Val1", "Val2");
            e2.HasOne(typeof(Tab), "Tab").WithOne("Tab2").IsRequired(false).OnDelete(DeleteBehavior.SetNull).HasForeignKey(typeof(Tab2), "TabId");

            var e = modelBuilder.Entity<Tab>();
            e.ToTable("Table1");
            e.HasKey(d => d.Id);
            e.HasOne(typeof(Tab2), "Tab2").WithOne("Tab").IsRequired().OnDelete(DeleteBehavior.Cascade).HasForeignKey(typeof(Tab), "Value1", "Value2");

        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=EF_Tests;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

    }
```
Here's result

![SSMS](http://imageshack.com/a/img922/3324/FSMVwO.png)

As you can see, TabId is not marked as ForeignKey constraint (which is annoying). Also, column is marked as not null.

Has a workaround, i've found that I have to modify migration by hand to create constraint.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017

**Comment by smitpatel** [comment]
Your `OnModelCreating` is incorrect. You have one set of navigation - `Tab` & `Tab2`. First you configure relationship using those navigations with FK `Tab2.TabId` then later you reconfigure relationship represented by both navigations with a composite FK `Tab.Value1,Value2` Both of them are conflicting. They uses different side as principal and different properties as FK. So when you reconfigure EF Core will remove the first one effectively. "Last one wins".
Define your relationships in code correctly as you really want them in database.
