### ISSUE TITLE
Saving / deleting / modifing data using EF Core 2.0 give random results

### ISSUE THREAD

**Issue by seb999** [dotnet/efcore#10320]
Dear All,

We are experiencing very unstable behaviour of our application since we migrated to EF Core 2.0. For example our users has to press 2 to 3 times a save button in the UI to get data saved in the database. After investigation we end up using the following command to tell the EF that we want to save, delete or update. Without those command it is working randomly. With EF core 1.0 those command were not necessary.

 misContext.Entry(expense).State = EntityState.Added;
 misContext.Entry(expense).State = EntityState.Modified;
 misContext.Entry(expense).State = EntityState.Deleted;

Best regards
Sebastien

Here is an expemple of code that save an object expenseTranfer to a table Expense in our database.
```C#
[HttpPost]
        [Route("saveExpense")]
        public void SaveExpense([FromBody]ExpenseTransfer expenseTransfer)
        {
            Expense expense = misContext.Expense.Where(p => p.ExpenseId == expenseTransfer.ExpenseId).FirstOrDefault();

            bool isAdd = false;
            if (expense == null)
            {
                isAdd = true;
                expense = new Expense()
                {
                    UserAdded = currentUser.UserId,
                    DateAdded = DateTime.Now,
                    ExpensePlatoStatusId = misContext.ExpensePlatoStatus.Where(p=>p.ExpensePlatoStatusName == "Temporary").Select(p=>p.ExpensePlatoStatusId).FirstOrDefault(),
                };
            }
            else
            {
                expense.DateMod = DateTime.Now;
                expense.UserMod = currentUser.UserId;
            }

            expense.ActivityId = expenseTransfer.ActivityId;
            expense.ExpenseName = expenseTransfer.ExpenseName;
            expense.BudgetLineId = expenseTransfer.BudgetLineId != 0 ? expenseTransfer.BudgetLineId : (long?)null;
            expense.ExpenseTypeId = expenseTransfer.ExpenseTypeId != 0 ? expenseTransfer.ExpenseTypeId : (long?)null;
            expense.ExpenseAmount = expenseTransfer.Amount;
            expense.ExpenseNote = expenseTransfer.ExpenseNote;
            expense.UserIdOwner = expenseTransfer.OrganiserId != 0 ? expenseTransfer.OrganiserId : (long?)null;
            expense.ExpenseStartDate = expenseTransfer.StartDate;
            expense.ExpenseEndDate = expenseTransfer.EndDate;
            expense.RecurrenceId = expenseTransfer.RecurrenceId != 0 ? expenseTransfer.RecurrenceId : (long?)null;
            expense.CapacityLevelId = expenseTransfer.CapacityLevelId != 0 ? expenseTransfer.CapacityLevelId : (long?)null;
            expense.ExpenseIsPriority20 = expenseTransfer.IsPriority20;
            expense.ExpenseIsPriority80 = expenseTransfer.IsPriority80;

            expense.MeetingDuration = expenseTransfer.MeetingDuration;
            expense.MeetingNumIntParticipants = expenseTransfer.MeetingNumIntParticipants;
            expense.MeetingNumExtParticipants = expenseTransfer.MeetingNumExtParticipants;
            expense.LocationCity = expenseTransfer.MeetingLocationCity;
            expense.LocationId = expenseTransfer.MeetingLocationId != 0 ? expenseTransfer.MeetingLocationId : (long?)null;

            expense.ProcConTypeId = expenseTransfer.ProcContractId != 0 ? expenseTransfer.ProcContractId : (long?)null;
            expense.ProcTypeId = expenseTransfer.ProcTypeId != 0 ? expenseTransfer.ProcTypeId : (long?)null;
            expense.ProcComment = expenseTransfer.ProcComment;

            expense.SpdKeyOutputId = expenseTransfer.SpdKeyOutputId != 0 ? expenseTransfer.SpdKeyOutputId : (long?)null;
            expense.SpdObjectiveId = expenseTransfer.SpdObjectiveId != 0 ? expenseTransfer.SpdObjectiveId : (long?)null;

            
            if (isAdd)
            {
                misContext.Add(expense);
                misContext.Entry(expense).State = EntityState.Added;
            }
            else
            {
                misContext.Entry(expense).State = EntityState.Modified;
            }

            misContext.SaveChanges();

            //Save FTE link to this expense
            SaveStaffList(expenseTransfer.ExpenseStaffList, expenseTransfer.ExpenseId, currentUser.UserId);

            //Added to fix a saving bug. Had to click 3 times save to saved
            misContext.Entry(expense).State = EntityState.Modified;
            misContext.SaveChanges();
        }
```

**Comment by ajcvickers** [comment]
@seb999 What is the lifetime of misContext?

**Comment by seb999** [comment]
Hello Arthur,

I'm loading the context in the startup page :

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContextPool<MISContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));`

Then in my class constructor, passing it with Dependency Injection:

`private readonly MISContext misContext;
        private readonly UserApplication currentUser;
        private readonly ILookupUser lookupUser;
        private readonly ILookupRepository lookupList;
        private readonly IHostingEnvironment hostingEnvironement;
        private readonly LogService logService;

        public PlatoController([FromServices]MISContext misContext, LogService logService, ILookupUser lookupUser, ILookupRepository lookupList, IHostingEnvironment server)
        {
            this.misContext = misContext;
            this.currentUser = lookupUser.CurrentUser;
            this.lookupUser = lookupUser;
            this.lookupList = lookupList;
            this.hostingEnvironement = server;
            this.logService = logService;
        }`

With my colleague we investigate the situation a bit last evening. Whouldn't be a problem with AddDbContextPool combined with LINQ where clause ? We found this [https://stackoverflow.com/questions/14720143/are-find-and-where-firstordefault-equivalent](url)

If you read the first answer it appears that using "where clause" load the entity from the memory and not from the database. Can it be the problem here ?

Best regards
Sebastien

**Comment by ajcvickers** [comment]
@seb999 We're probably going to need a full project or complete code listing that reproduces the issue before we can fully investigate. Is the behavior the same if you use AddDbContext instead of AddDbContextPool?

**Comment by halityurttas** [comment]
Did you get any error in debug mode? Your codes is not look fault. You should check your model configuration or you look to data transfer object values in debug mode. This problem does not belong to entity framework concepts.

**Comment by seb999** [comment]
Hello, we didn't get any error in debug mode. It would be difficult to send you the entire project with the database. 

For now on, we managed to get ride of this by aadding 
misContext.Entry(object).State = EntityState.Added; for add operation
misContext.Entry(object).State = EntityState.Modified; for update operation
misContext.Entry(object).State = EntityState.Deleted; for delete operation
