### ISSUE TITLE
Can't use Microsoft.EntityFrameworkCore.Sqlite

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10325]
VS Feedback:

In VS15.5 Preview, I created a Xamarin.Forms projects with .NET Standard code sharing strategy.
Add Microsoft.EntityFrameworkCore.Sqlite, Android Project can't run, if I run the android project, program will crash and vs will stop.

**Comment by ajcvickers** [comment]
Assigning to @divega along with other Android investigations. Feel free to de-dupe as needed.

**Comment by topfunet** [comment]
any news?

**Comment by bricelam** [comment]
Duplicate of  #8922?

**Comment by divega** [comment]
If this is not a duplicate of #8922 then it is no repro. Closing.
