### ISSUE TITLE
Question: why does a many-to-many linking table only have one foreign key index?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#10330]
I have a many-to-many linking table, called `BookAuthor` between a `Book` and an `Author` entity. I noticed that the  `BookAuthor` table only has a index on the `Author` foreign key - I expected another index on the `Book` foireign key too. Is this because the primary key index, which contains both the `BookId` and the `AuthorId` helps with the `Book` foreign key? 

I'm asking so that I understand better what EF Core is doing.

### Steps to reproduce
Create a many-to-many relationship and then look at the SQL Server database

```c#
public class BookAuthor               
{
    public int BookId { get; set; } 
    public int AuthorId { get; set; }
    public byte Order { get; set; }   

    //-----------------------------
    //Relationships

    public Book Book { get; set; }      
    public Author Author { get; set; }  
}
```
The SQL Indexes list contains
1. IX_BookAuthor_AuthorId (Non-Unique, Non-clustered)
2. PK_BookAuthor (Clustered)

Other classes (for completeness).
```c#
public class Book                        
{
    public int BookId { get; set; }

    [Required]
    [MaxLength(256)] 
    public string Title { get; set; }
    public string Description { get; set; }
    public DateTime PublishedOn { get; set; }
    [MaxLength(64)] 
    public string Publisher { get; set; }
    public decimal Price { get; set; }

    [MaxLength(512)] 
    public string ImageUrl { get; set; }
    public bool SoftDeleted { get; set; }

    //-----------------------------------------------
    //relationships

    public PriceOffer Promotion { get; set; }        
    public ICollection<Review> Reviews { get; set; } 
    public ICollection<BookAuthor> AuthorsLink { get; set; }                    
}
```

```c#
public class Author
{
    public const int NameLength = 100;

    public int AuthorId { get; set; }
    [Required]
    [MaxLength(NameLength)]
    public string Name { get; set; }

    //------------------------------
    //Relationships

    public ICollection<BookAuthor> BooksLink { get; set; }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@JonPSmith Yes, my understanding is that we don't generate an index in cases where it is covered by another index. So, in this case the index on the PK is for BookId, AuthorId, which means the index for just BookId is not created, but the index for AuthorId is.

However, leaving this open to discuss with @divega since @bricelam indicated that this may not be the correct thing to do for SQLite, and therefore possibly other relational providers.

**Comment by bricelam** [comment]
I take it all back. SQLite makes excellent use of [covering indexes](https://www.sqlite.org/queryplanner.html#covidx).
