### ISSUE TITLE
Create same migrations for different database systems

### ISSUE THREAD

**Issue by p-** [dotnet/efcore#10333]
Hello!

I did look around, but did not find yet a recommended way to create the same migrations for different database systems.

The use case is the following: a project that is developed on Windows with SQL Server, but also needs to be tested on Linux with a different database system like SQLite, PostgreSQL, ...
So the same migrations should be applied to databases on different db systems.

Now if we create a migration like:
`dotnet ef migrations add myMig`
The migration code seems to be only created for one database (*.Designer.cs files contain database specific types).

Now it would be nice if there were some kind of way to generate the same migrations for multiple database system. E.g. similar to the [scaffold command](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet) where the providers (e.g. Microsoft.EntityFrameworkCore.SqlServer) can be specified.

**Comment by ajcvickers** [comment]
@p- See this section in the docs: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers

**Comment by p-** [comment]
@ajcvickers Great! That's exactly what I was looking for, but unfortunately didn't find it. Thanks!
