### ISSUE TITLE
SQLite provider compilation error

### ISSUE THREAD

**Issue by sachinnagawade** [dotnet/efcore#1033]
I have followed steps given in
https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Traditional-.NET-Applications.

With only change that I am using SQLite provider. I have installed Nuget Packages for EntityFramework.SQlite, Microsoft.Data.SQLite and EntityFramework from https://www.myget.org/F/aspnetvnext/api/v2/.

Following source code does not compile ???
The compilation error is,
Error   1   'Microsoft.Data.Entity.Metadata.ModelBuilder.EntityBuilder.PropertyBuilder' does not contain a definition for 'GenerateValuesOnAdd' and no extension method 'GenerateValuesOnAdd' accepting a first argument of type 'Microsoft.Data.Entity.Metadata.ModelBuilder.EntityBuilder.PropertyBuilder' could be found (are you missing a using directive or an assembly reference?)   

I have re-verified steps given in link. I am not sure why is this compilation error and which assembly is missing?

using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata;
...
        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Blog>()
                .OneToMany(b => b.Posts, p => p.Blog)
                .ForeignKey(p => p.BlogId);

```
        // The EF7 SQLite provider currently doesn't support generated values
        // so setting the keys to be generated from developer code
        builder.Entity<Blog>()
            .Property(b => b.BlogId)
            .GenerateValuesOnAdd(false);

        builder.Entity<Post>()
            .Property(b => b.BlogId)
            .GenerateValuesOnAdd(false);
    }
```

**Comment by rowanmiller** [comment]
SQLite provider is temporarily on hold - http://blogs.msdn.com/b/adonet/archive/2014/12/02/ef7-priorities-focus-and-initial-release.aspx

As part of bringing it back into the dev branch we will update docs with current working samples.
