### ISSUE TITLE
Uniquify relational names on demand

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#10337]
Currently the relational identifiers are uniquified after the model is built, so querying one during the configuration could potentially return a different string.

**Comment by ajcvickers** [comment]
Discussed in triage and decided do backlog this for now. If we get feedback that this would be useful, then we could consider doing it for this and other "leaks" (e.g. type mapping/value gen flag) in a way that uses an on-demand convention when accessing the metadata through the API.

**Comment by AndriySvyryd** [comment]
Could be implemented by https://github.com/aspnet/EntityFrameworkCore/issues/9329
