### ISSUE TITLE
Assets file 'E:\****\obj\project.assets.json' doesn't have a target for '.NETPortable,Version=v4.0,Profile=Profile111'. Ensure that restore has run and that you have included 'portable40-net45+win8+wpa81' in the TargetFrameworks for your project.

### ISSUE THREAD

**Issue by Lily721** [dotnet/efcore#10331]
Hi guys, 

When I use multi target framework in my project like following:

`<TargetFrameworks>netstandard1.1;net45</TargetFrameworks>
<TargetFrameworkProfile>Profile111</TargetFrameworkProfile>`

And following is why I need TargetFrameworkProfile in my .csproj:

`<Import Project="$(MSBuildExtensionsPath)\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" />`

I faced upper problem, I thought I was right when I see this article [https://docs.microsoft.com/en-us/nuget/schema/target-frameworks],

Profile111 | .NETFramework 4.5 | portable-net45+win8+wpa81 | netstandard1.1

I've being working on this a whole day, didn't find any solution yet, does anyone know what's the problem? Thanks a lot.

**Comment by ajcvickers** [comment]
@Lily721 Looks like you are using the new project system in for portable targets, which I don't think it supported. Regardless, this does not seem to be related to EF Core, so if you feel this is a bug, then please file a new issue at https://github.com/dotnet/sdk/issues

**Comment by bricelam** [comment]
Have you tried removing `<TargetFrameworkProfile>`? It doesn't make sense in a cross-targeting project...
