### ISSUE TITLE
Querying for parent entity type with custom sql?

### ISSUE THREAD

**Issue by andrasg** [dotnet/efcore#10344]
I have a class hierarchy and use EF to store them in a SQL table. Works all fine, see the discriminators.

Is there a way to query among all of these entities using a custom SQL query?

Classes are setup this way:

```cs
public class Fruit
{
  public string Name { get; set; }
  public string Color { get; set; }
}

public class Apple : Fruit
{
  // some Apple properties
}

public class Banana : Fruit
{
  // some Banana properties
}
```

I am setting up a mapping on the `Fruit` entity to point to a specific table, so all subclasses will use the same table:

```cs
public class FruitMapping : IEntityTypeConfiguration<Fruit>
{
   public void Configure(EntityTypeBuilder<Fruit> builder)
   {
      builder.ToTable("Fruits");
   }
}
```

The query I am looking for would look something like:

```cs
string rawsql = "SELECT * FROM [dbo].[Fruits] WHERE Color = 'red'"
var redFruits= _dbContext.FromSqlUsingBoxing<Fruit>(rawsql);
```

I would then be able to iterate through the `Fruit` objects in `redFruits` and work with their common properties or even unbox them to `Apple`, `Banana`, etc. when necessary based on their real type.

Any way to do this in EF Core 2.0?

**Comment by andrasg** [comment]
In EF6 I was able to solve this by using `_dbContext.Database.SqlQuery<AggregateType>(rawsql)` where `AggregateType` would match onto the result of the `rawsql` query. Is there anything similar in EF Core 2.0?

**Comment by smitpatel** [comment]
try `var redFruits = _DbContext.Set<Fruit>().FromSql(rawsql);`

**Comment by halityurttas** [comment]
Actually this is imposible. But you make an object to contains apple and banana methods. For example apple have a property with name is color. And banana have height. You should make a type to contains whole properties. If you want to get reel types you must use mapping result to reel type. The unboxing possible on created reel object. So Fruits not applicable to convert Apple, but Apple to fruit possible. You have to use mapping methods.

**Comment by ajcvickers** [comment]
@andrasg Closing as @smitpatel's answer seems to be correct--please feel free to comment again and we can re-open if this is not working or not what you wanted.

@halityurttas I think you might be a bit confused--it might be worth reading up on some top-level docs: https://docs.microsoft.com/en-us/ef/core/
