### ISSUE TITLE
Xamarin.iOS app with EFCore 2.0 SQLitePCL.Batteries.Init()

### ISSUE THREAD

**Issue by alexdrl** [dotnet/efcore#10361]
A Xamarin.iOS app with EFCore 2.0 needs a call to 

```c#
SQLitePCL.Batteries_V2.Init();
```

If the call is not made, the app initialization throws this error message. 

```
You need to call SQLitePCL.raw.SetProvider(). If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
```
Like explained [here](https://github.com/ericsink/SQLitePCL.raw/wiki/SQLitePCL.Batteries.Init)

### Steps to reproduce
Xamarin.iOS project working with EFCore 2.0. Solution with a common .NET Standard project which shares code between iOS and Android, using PackageReference.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: iOS
IDE: Visual Studio 15.4

**Comment by bricelam** [comment]
Correct. I don't think Xamarin.iOS can handle [the Assembly.Load() call](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/rel/2.0.0/src/Microsoft.Data.Sqlite.Core/Utilities/BundleInitializer.cs#L15).

**Comment by alexdrl** [comment]
I use the EF Core dependency assembly that gets added as a transitive dependency, and call that Init method, the app works correctly. In the project assets json, the Xamarin.iOS SQLitePCLraw package gets restored correctly.

**Comment by bricelam** [comment]
We should probably document this on the [Supported .NET Implementations](https://docs.microsoft.com/ef/core/platforms/) page or thereabouts.

**Comment by alexdrl** [comment]
The documentation already stated that there are problems in Xamarin.iOS but there is no page that describes this (or other) workarounds.

**Comment by bricelam** [comment]
This issue was moved to aspnet/EntityFramework.Docs#597
