### ISSUE TITLE
Database.SqlQuery<TElement> Missing

### ISSUE THREAD

**Issue by clockwiseq** [dotnet/efcore#10365]
In Entity Framework, there is a method to execute a query against the database and return a specified object type.  Entity Framework Core does not have this and the only alternative is 4 times the amount of code.  Example below.

#### Database.SqlQuery<TElement> (Entity Framework 6.0)
This is the [SqlQuery](https://msdn.microsoft.com/en-us/library/system.data.entity.database.sqlquery(v=vs.113).aspx#M:System.Data.Entity.Database.SqlQuery``1%28System.String,System.Object[]%29) method found in Entity Framework 6.0

```c#
var integerList = db.Database.SqlQuery<int>("SELECT [MyIntegerColumn] FROM [MyTable]").ToList();

foreach (int id in integerList)
{
    // do something with each in the list or just return the list
}
```

#### SqlCommand (Entity Framework Core 2.0)
This is the [DbDataReader](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced) method found in Entity Framework Core 2.0

```c#
using (var command = context.Database.GetDbConnection().CreateCommand())
{
    command.CommandText = "SELECT [MyIntegerColumn] FROM [MyTable]";
    DbDataReader reader = await command.ExecuteReaderAsync();

    if (reader.HasRows)
    {
        while (await reader.ReadAsync())
        {
            // do something with each in the list or just return the list
        }
    }
}
```

Honestly, quadrupling the amount of code required to perform the same action and expecting the same result is not "more efficient" in my opinion.  I have literally dozens of "quick calls" as I call them in my code that will now require me to convert a single line of code over to 4 (or more).

**Comment by ajcvickers** [comment]
Raw SQL queries that return arbitrary types is being tracked by #9290.

**Comment by devel0** [comment]
Meanwhile you can try [netcore-ef-util](https://github.com/devel0/netcore-ef-util) and a code like follow

```csharp
using SearchAThing.EFUtil;
using System.Linq;

...
var integerList = db.ExecSQL<comptype1>("SELECT [MyIntegerColumn] FROM [MyTable]")
.Select(w=>w.MyIntegerColumn);
foreach (int id in integerList)
{
    // do something with each in the list or just return the list
}
```

having defined a composite structure to hold data result with

```csharp
public class comptype1
{
  public int MyIntegerColumn;
};
```

More complex example [here](https://github.com/devel0/worked-hours-tracker/blob/df807cfa04c239b48f5d0da01bcd23351b3cc6fc/WorkedHoursTrackerWebapi/Controllers/ApiController.cs#L296-L302) with [composite type](https://github.com/devel0/worked-hours-tracker/blob/df807cfa04c239b48f5d0da01bcd23351b3cc6fc/WorkedHoursTrackerWebapi/Controllers/ApiController.cs#L279-L283)

**Comment by enicolasgomez** [comment]
This is the exact reason why people is moving to NodeJS
