### ISSUE TITLE
EF Migrations - MaxLength, StringLength is ignored

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10369]
From VS Feedback:

Basic ASP.NET MVC template. Custom class in DbSet. Fields with data annotation MaxLength or StringLength are ignored for strings when doing Add-Migration/Update-Database cycle. Database reset also won't help - Update-Database -TargetMigration 0 | Update-Database -Force. 

What I've tried so far:
* Setting length as is and the change only it in migration
* Setting specific migration version with Update-Database -TargetMigration Migration
* Setting all the migrations from scratch with Update-Database -TargetMigration 0 | Update-Database -Force
* Recreating database (Deleting database in SQL Server Object Explorer)
And after all SQL definition still contains initial MAX constraint, as well as table definition.

Part of migration
```C#
AlterColumn("dbo.Gxxxx","Nxxx", c => c.String(nullable: false, maxLength:255));
AlterColumn("dbo.Gxxx","Vxxxxx", c => c.String(nullable: false, maxLength:255));
AlterColumn("dbo.Gxxx","Axxxxx_Id", c => c.String(nullable: false, maxLength:128));
```
Database definition after all migrations
```sql
[Nxxx] NVARCHAR (MAX)NULL,
[Vxxxx]     NVARCHAR (MAX)NULL,
[Axxxxx_Id] NVARCHAR (128)NULL,
```

**Comment by bricelam** [comment]
This is EF6 code: `c => c.String()`

**Comment by bricelam** [comment]
I'm not able to repro this. `[MaxLength]`, `[StringLength]`, and `.HasMaxLength()` are all reflected in the DDL generated by Migraitons.

``` sql
[Nxxx] [nvarchar](255),
[Vxxxx] [nvarchar](255),
[Axxxxx_Id] [nvarchar](128),
```

Can we get a project?

**Comment by avoidik** [comment]
Sure, I'll prepare it and let you know

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
