### ISSUE TITLE
How to use Lazy loading on Generic Function In .net Core

### ISSUE THREAD

**Issue by orahj** [dotnet/efcore#10364]
```C#
 public E GetBy<E>(object id) where E : class
        {
            try
            {
                return context.Set<E>().Find(id);
            }
            catch (Exception)
            {
                throw;
            }
        }
```
How do I use Lazy loading this generic function

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2015)

**Comment by ajcvickers** [comment]
@orahj Not sure exactly what you are asking for, but lazy loading in EF Core is not implemented yet and is being tracked by #3797

**Comment by orahj** [comment]
I am Using a Generic repository Which Means I pass In any Model, Now That Lazy Loading is not Working How do Use the include for Eager Loading? in my generic repository

**Comment by ajcvickers** [comment]
@orahj A good place to start is the documentation on loading related entities: https://docs.microsoft.com/en-us/ef/core/querying/related-data
