### ISSUE TITLE
SQLCE 2.1 provider - unable to get latest

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#10385]
Unable to use the latest EFCore.Relational package from aspnet-dev feed on Myget

```
Attempting to gather dependency information for package 'Microsoft.EntityFrameworkCore.Relational.2.1.0-preview1-27673' with respect to project 'EntityFramework.SqlServerCompact40', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 12,73 sec
Attempting to resolve dependencies for package 'Microsoft.EntityFrameworkCore.Relational.2.1.0-preview1-27673' with DependencyBehavior 'Lowest'
Unable to find a version of 'System.Collections.Immutable' that is compatible with 'Microsoft.EntityFrameworkCore 2.1.0-preview1-27673 constraint: System.Collections.Immutable (>= 1.5.0-preview1-25922-03)'.
Time Elapsed: 00:00:12.7728935
========== Finished ==========
```

### Further technical details
Feed: https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json 
EF Core version: .2.1.0-preview1-27673' 
Database Provider: N/A
Operating system: Win 10
IDE: VS 2017 15.3.2

**Comment by smitpatel** [comment]
We recently updated corefx dependencies https://github.com/aspnet/Universe/commit/641cc35d42ee282e6cba385d03620d502ecfc24a

I am trying to find from where we get that package.

**Comment by smitpatel** [comment]
@ErikEJ - I would recommend going back 1 version behind.
Universe build which produces the packages injects dependencies separate from what repos are using. I am not quite getting hold of from where it is getting particular package. But current source code of EF Core does not depend on that package. About weekly, we update dependencies in all our sources. I am certain that before that happens the package will be available on one of the feeds used by this repo (else local builds would fail). I suppose we can just wait out till that.

**Comment by ajcvickers** [comment]
@natemcmaster @ryanbrandenburg @pranavkm Any ideas what is going on here?

**Comment by pranavkm** [comment]
Looks like I had a typo in one of my commits and wasn't publishing dependencies to the feed. Redoing the build so this should get sorted shortly.

**Comment by pranavkm** [comment]
MyGet's being odd. I had to manually upload packages but that should resolve your issue. Feel free to reopen this issue if you continue seeing issues here.

**Comment by ErikEJ** [comment]
@pranavkm Thanks, working now
