### ISSUE TITLE
SQLite SuppressForeignKeyEnforcement is not working after upgrate version 2.0

### ISSUE THREAD

**Issue by olman21** [dotnet/efcore#10390]
I have a helper method for unit test my repositories using SQLite as store, really I'm not interested in verify Foreign Keys in Test mode, then I used SuppressForeignKeyEnforcement config method in order to avoid that validation, before I upgrade to version 2.0.1 it worked like a charm, as soon I make the upgrade it started validating FKs when I insert test data causing my tests to fail. I noticed if I manually run `PRAGMA FOREIGN_KEYS=OFF` as sql statement the FK enforcement was removed again, but that is not a so clean workarround. 

Exception message:
Stack trace:

>  Microsoft.Data.Sqlite.SqliteException : SQLite Error 19: 'FOREIGN KEY constraint failed'.

### Steps to reproduce
```
 var options = new DbContextOptionsBuilder<TContext>()
                    .UseSqlite(connection, x => x.SuppressForeignKeyEnforcement()) //SuppressForeignKeyEnforcement broke in 2.0.1 version, it does not remove FK Enforcement anymore
                    .Options;
```
As soon I added some data to my DBContext and call 
`await context?.SaveChangesAsync(); `
it fails

```c#
This is my complete test helper

```c#
 public static async Task UseSQLiteAsync<TContext>(Action<TContext> seedMethod, Func<TContext, Task> test) where TContext : DbContext
        {
            // In-memory database only exists while the connection is open
            var connection = new SqliteConnection("DataSource=:memory:");

            try
            {
                connection.Open();
                var options = new DbContextOptionsBuilder<TContext>()
                    .UseSqlite(connection, x => x.SuppressForeignKeyEnforcement()) //SuppressForeignKeyEnforcement broke in 2.0.1 version, it  
                    .Options;

                // Insert seed data into the database using one instance of the context
                using (var context = Activator.CreateInstance(typeof(TContext), options) as TContext)
                {
                    //it removes the FK enforcement again, but is kind of nasty
                    //context?.Database.ExecuteSqlCommand("PRAGMA FOREIGN_KEYS=OFF"); 
                    // Create the schema in the database
                    context?.Database.EnsureCreated();
                    seedMethod.Invoke(context);
                    await context?.SaveChangesAsync();
                    await test(context);
                }


            }
            finally
            {
                connection.Close();
            }
        }

```

Here I consume the method

```
[Fact]
        public async void
            GetByLocation_ExcludeProductsAreNotActive_2ProductsExcluded()
        {
            //It failes with In Memory Database
            await Helper.UseSQLiteAsync<MyDbContext>(
                context =>
                {
                    context.LocationCatalog.Add(Only_Active_ProductsDS.GetLocationCatalog());
                    context.Product.AddRange(Only_Active_ProductsDS.Get3Products1Inactive());
                    context.ProductExternalProvider.AddRange(Only_Active_ProductsDS.Get3ProductExternalProviders());
                },
                async context =>
                {
                    var repo = new HotelRepository(context, _mockLoggerFactory.Object);
                    var result = await repo.GetByLocation(1);
                    result.Should().NotBeNullOrEmpty().And.HaveCount(2);
                    result.Should().OnlyContain(e => e.Id == 1 || e.Id == 2);
                });
        }
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win10 Pro
IDE: Visual Studio 2017

**Comment by ralmsdeveloper** [comment]
Have you tried upgrading to version 2.0.1?

**Comment by olman21** [comment]
I update that part, actually I'm using the latest version (2.0.1) I started a laborious task to migrate our aspnet core 1.1 applications to 2.0 and as a part of this all packages were upgraded to lastest version, so yes this happens to me in Microsoft.EntityFrameworkCore.Sqlite version 2.0.1.

**Comment by ralmsdeveloper** [comment]
Out of curiosity, looking at something here, you can change 
this: 
`x => x.SuppressForeignKeyEnforcement () `
by: 
`x => x.SuppressForeignKeyEnforcement (false)`

**Comment by olman21** [comment]
@ralmsdeveloper no difference :(

**Comment by ralmsdeveloper** [comment]
I believe @bricelam, have any idea about this.

**Comment by smitpatel** [comment]
Breaking change as per #7527

In 1.1 EF used to send out PRAGMA command whenever connection internally opened in EF Core. With 2.0 release, we send out command only if the connection actually gets opened. In this case since you are passing open connection, we do not send PRAGMA command.

While I am leaving this open so that we can discuss in the meeting if this was intentional breaking change. But it is highly likely that if user is giving us open connection, user is also responsible to set any special things need to be set in connection.

**Comment by olman21** [comment]
I tried out to open connection after configure the dbcontext but SuppressForeignKeyEnforcement is still validating FKs.

**Comment by smitpatel** [comment]
If you are passing an open connection to DbContext using `UseSqlite` then order of dbcontext configuration does not matter. You are supposed to configure the connection yourself whenever you want.

**Comment by ajcvickers** [comment]
We discussed this in triage and decided that the current behavior is correct. That is, if EF opens the connection, then EF will send a PRAGMA based on the value of SuppressForeignKeyEnforcement. This is true regardless of whether or not EF created the connection. However, if the application opens the connection, then it is the responsibility of the application to send any pragmas desired for that open connection.

**Comment by olman21** [comment]
Got it.
