### ISSUE TITLE
AsNoTracking() returning different instances of the same entity.

### ISSUE THREAD

**Issue by mfronczyk** [dotnet/efcore#10396]
The documentation says that no tracking queries still perform identity resolution. I fetch the same Category entity 2 times: once using Include and once directly by a query:

 ```
return await _dbContext.Products
                .AsNoTracking()
                .Include(p => p.Listings)
                    .ThenInclude(l => l.Category)
                .Where(p => p.Id == numericId)
                .SingleOrDefaultAsync();

return await _dbContext.Categories
                .AsNoTracking()
                .Where(c => c.Id == numericId)
                .SingleOrDefaultAsync();
```

After adding AsNoTracking in both queries, I had to make the following change in the Product method to keep things working the same:

```
         public bool IsInCategory(Category c)
         {
-            return GetCategories(false).Any(x => x == c);
+           return GetCategories(false).Any(x => x.Id == c.Id);
         }
```
The docs say that you may get a new instance if a previous result with the same identity goes out of scope, which is definitely not the case here, but I still got 2 instances. Is identity resolution working across different queries?

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Mac OS X 10.12.6

**Comment by smitpatel** [comment]
Please post complete code listing which demonstrate the issue you are seeing.

**Comment by mfronczyk** [comment]
I'd need to spend some time to create a complete, runnable listing. Could you please first have a look at my description and check if it's the desired behaviour? If you agree that it should work, I'll create a more complete bug report. Does it work for you?

**Comment by smitpatel** [comment]
It should not do Identity Resolution across multiple queries when AsNoTracking used.

**Comment by mfronczyk** [comment]
So it looks like to be an expected behaviour. Please keep in mind that I run the queries one after another, despite of the async code.

You might want to consider changing the documentation here https://docs.microsoft.com/en-us/ef/core/querying/tracking. Currently it says:

> If a previous result with the same identity goes out of scope, and garbage collection runs, you may get a new entity instance. For more information, see How Query Works.

It should probably mention that if the same entity is returned from 2 different queries, then it's not resolved to the same object instance.

**Comment by ajcvickers** [comment]
@mfronczyk Thanks for the note about the docs--we will consider making it more explicit that identity resolution in no-tracking queries applies only to a single query while it is executing.

**Comment by ajcvickers** [comment]
Submitted https://github.com/aspnet/EntityFramework.Docs/pull/574
