### ISSUE TITLE
EntityType marked with NotMapped is still discovered by Conventions

### ISSUE THREAD

**Issue by DerGary** [dotnet/efcore#10414]
Bug described in #8151 is not fixed in 1.1.x Versions of EF Core and because we are using UWP we can't upgrade to 2.x.x.

### Further technical details
EF Core version: 1.1.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@DerGary By filing this are you requesting that this fix be back ported to 1.1.x?

Which issues are preventing use of UWP on 2.x.x?

**Comment by DerGary** [comment]
@ajcvickers yes that's what I would suggest. 

I wrote about the Problems with 2.x and UWP in the discussion thread [here](https://github.com/aspnet/EntityFrameworkCore/issues/8598#issuecomment-336878042) but I got no response. 

Also I would like to know what your plans about supporting uwp in the future are and how we users should handle errors in 1.1.x because we can't upgrade to 2.x. (because we need to target older versions of uwp)

**Comment by ajcvickers** [comment]
@DerGary There are a lot of different moving parts in the .NET Core/UWP/EF Core story and after thinking carefully about the bigger picture with the various stakeholders we made the call to target .NET Standard 2.0 only. It wasn't really about making things easier for us, but about setting things up for future success. I'm personally very sorry that this doesn't meet your needs, and we certainly take that feedback on-board. However, at this time, I don't think it's going to change the previous decisions that were made for 2.0.

With regard to fixing this bug in a 1.1.x release, I think that this is very unlikely. Currently only very high priority patches will be approved for 1.1.x releases, and I don't think this issue will meet that bar. However, we can certainly try to help find a workaround--can you let us know what workarounds you have tried so far?

**Comment by DerGary** [comment]
I tried using EF Core 2.0.0-preview1-final which didn't target .net standard 2.0 yet. This version of EF Core does include the fix of the mentioned bug and a Migration can be created. But using this version my tests failed because I got the error described in #8817 . 

I also tried only creating the migration with 2.0.0-preview1-final and then downgrading to 1.1.4 again but that didn't work either.

The only thing that I tried and that worked is instead of using properties I switched to methods that return the value.

**Comment by ajcvickers** [comment]
@DerGary I was able to workaround #8151 by adding:
```C#
modelBuilder.Ignore<ReportBase>();
```
as the first line in my OnModelCreating. Can you verify whether this workaround is applicable to your product code?

**Comment by DerGary** [comment]
@ajcvickers Thanks for the suggestion I just tried it and EF was able to create a Migration but i got some strange Columns in the database:

```C#
migrationBuilder.CreateTable(
	name: "ConcreteReports",
	columns: table => new
	{
		CompanyNumber = table.Column<string>(nullable: false),
		CustomerNumber = table.Column<string>(nullable: false),
		PartialKey = table.Column<int>(nullable: false),
		Discriminator = table.Column<string>(nullable: true), <-- what is this?
		State = table.Column<int>(nullable: false), <-- this is an attribute of a base class that is annotated with NotMapped
		TempId = table.Column<int>(nullable: false) <-- what is this?
	},
```

I used the following model to create this behaviour:

```C#
public class SubsidiaryCompany {
	[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
	public string Key { get; set; }
	public List<Customer> Customers { get; set; }
}
public class CustomerGroup {
	[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
	public int Key { get; set; }
	public List<Customer> Customers { get; set; }
}
public class Customer {
	public string CustomerNumber { get; set; }
	public string CompanyNumber { get; set; }

	[ForeignKey(nameof(CustomerGroup))]
	public int CustomerGroupKey { get; set; }
	public CustomerGroup CustomerGroup { get; set; }
	[ForeignKey(nameof(SubsidiaryCompany))]
	public string SubsidiaryCompanyKey { get; set; }
	public SubsidiaryCompany SubsidiaryCompany { get; set; }
	
	public List<SomeConcreteReport> ConcreteReports { get; set; }

	[NotMapped]
	public List<ReportGroup> ReportGroups { get; set; }
}

public abstract class SQLiteBase {
	[NotMapped]
	public int State { get; set; }
}

public abstract class ReportBase : SQLiteBase {
	[NotMapped]
	public abstract IEnumerable<FileBase> FilesBase { get; }
}
public abstract class ReportBase<T> : ReportBase where T : FileBase {
	public List<T> Files { get; set; } // relationship

	[NotMapped]
	public override IEnumerable<FileBase> FilesBase { get; }
}
public class SomeConcreteReport : ReportBase<SomeConcreteFile>{
	
	public int PartialKey { get; set; }
	public string CustomerNumber { get; set; }
	public string CompanyNumber { get; set; }

	public Customer Customer { get; set; }
}
public abstract class FileBase {
	[NotMapped]
	public abstract ReportBase ReportBase { get; }
}
public abstract class FileBase<T> : FileBase where T : ReportBase {
	public T Report { get; set; } //relationship
	[NotMapped]
	public override ReportBase ReportBase { get; }
}
public class SomeConcreteFile : FileBase<SomeConcreteReport> {
	public int PartialKeyFile { get; set; }
	public int PartialKeyReport { get; set; }
	public string CustomerNumber { get; set; }
	public string CompanyNumber { get; set; }

}
public class ReportGroup {
	public List<ReportBase> Reports { get; set; }
}

public class DatabaseContext : DbContext {
	public DbSet<SomeConcreteFile> ConcreteFiles { get; set; }
	public DbSet<SomeConcreteReport> ConcreteReports { get; set; }
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
		string databaseFilePath = "";
		try {
			databaseFilePath = Path.Combine(ApplicationData.Current.LocalFolder.Path, "db.s3db");
		} catch (InvalidOperationException) { }

		optionsBuilder.UseSqlite($"Data source={databaseFilePath}");
		base.OnConfiguring(optionsBuilder);
	}
	protected override void OnModelCreating(ModelBuilder modelBuilder) {

		modelBuilder.Ignore<FileBase>();
		modelBuilder.Ignore<ReportBase>();

		modelBuilder.Entity<Customer>()
			.HasKey(c => new { c.CustomerNumber, c.CompanyNumber });

		modelBuilder.Entity<SomeConcreteReport>()
			.HasKey(x => new { x.CompanyNumber, x.CustomerNumber, x.PartialKey });
		modelBuilder.Entity<SomeConcreteReport>()
			.HasOne(x => x.Customer)
			.WithMany(x => x.ConcreteReports)
			.HasForeignKey(x => new { x.CustomerNumber, x.CompanyNumber });
		modelBuilder.Entity<SomeConcreteReport>()
			.HasMany(x => x.Files)
			.WithOne(x => x.Report)
			.HasForeignKey(x => new { x.CompanyNumber, x.CustomerNumber, x.PartialKeyReport });
		modelBuilder.Entity<SomeConcreteFile>()
			.HasKey(x => new { x.PartialKeyReport, x.PartialKeyFile, x.CustomerNumber, x.CompanyNumber });

	}
}
```

**Comment by ajcvickers** [comment]
@DerGary How about this?
```C#
        modelBuilder.Ignore<FileBase>();
        modelBuilder.Ignore<ReportBase>();
        modelBuilder.Ignore<ReportGroup>();

        modelBuilder.Entity<SomeConcreteReport>().Ignore("Discriminator");
        modelBuilder.Entity<SomeConcreteReport>().Ignore("TempId");
        modelBuilder.Entity<SomeConcreteReport>().Ignore(e => e.State);
        modelBuilder.Entity<SomeConcreteFile>().Ignore("Discriminator");
```

**Comment by DerGary** [comment]
This seems to work but it looks like a janky workaround for a problem that shouldn't exist in the first place. 

Thats exactly why I do not approve with the decision to break support by targeting .net standard 2.0. The whole framework does not feel production ready and a lot of workarounds need to be used to get it up and running. And everyone who develops UWP is stranded on this version for a long time or has to use a different framework.

Nethertheless thank you for your support, I appreciate it. But I will not use this workaround because no one who reads that code will get why I did this and will have problems extending the current project.

Greetings Gary

**Comment by ajcvickers** [comment]
@DerGary Thanks for the feedback. Not sure there is much else we can do at this point, so closing this issue.
