### ISSUE TITLE
Cli migration fail with $(SolutionDir) in csproj

### ISSUE THREAD

**Issue by Xarkam** [dotnet/efcore#10428]
I want make a `dotnet ef migrations add InitialCreate -v` and build faild because I have a `$(SolutionDir)` in my csproj :
```
 <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(SolutionDir)bp.bat copydeps" Condition="'$(OS)' == 'Windows_NT'"/>
    <Exec Command="$(SolutionDir)bp.sh copydeps" Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'"/>
    <Exec Command="$(SolutionDir)bp.sh copydeps" Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'"/>
  </Target>
```
I have no exception, just a message telling me that the build failed.
```
D:\Developpements\Base\WebApplication\WebApplication.csproj(52,5): error MSB3073: The command "* Undefined *bp.bat copydeps" stopped with code 9009.

FAIL of the build.
```
### Steps to reproduce
To reproduce, simply add similar code given at the beginning of this issue and try to make a migration.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqllite
Operating system: Windows 10
IDE: Command line (powershell in vscode 1.18.1)

**Comment by bricelam** [comment]
The `$(SolutionDir)` is only set if you are building in Visual Studio or building the `*.sln` file directly. To make your project's more robust, you should add something like the following:

``` xml
<PropertyGroup>
  <SolutionDir Condition=" '$(SolutionDir)' == '' ">$(MSBuildThisFileDirectory)..\</SolutionDir>
</PropertyGroup>

**Comment by bricelam** [comment]
Another commonly used form: (so you don't have to type the correct number of `..`s)

    $([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), WebApplication.sln))

**Comment by Xarkam** [comment]
@bricelam thanks. 

I will look to test tomorrow
