### ISSUE TITLE
Why are AppendIdentityWhereCondition and AppendRowsAffectedWhereCondition abstract and rest is virtual?

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#10431]
Why are `AppendIdentityWhereCondition` and `AppendRowsAffectedWhereCondition` abstract and rest is virtual? 

In _FirebirdClient_ I don't have any code path where these could be used (but I do use other parts from `UpdateSqlGenerator` like i.e. `AppendInsertCommandHeader`), yet I still have to override these and have a dummy code there.

Would making these virtual brake anything?
Maybe even, given these are very much SQL Server specific (although I can imagine other providers can fit in), these could go into `EFCore.SqlServer` (but that would be breaking change).

**Comment by ajcvickers** [comment]
@AndriySvyryd This looks like update pipeline; can you answer @cincuranet's questions?

**Comment by AndriySvyryd** [comment]
@cincuranet These methods are required to be implemented for correct behavior and there's no standard SQL that could be placed in the base implementation as far as I can tell. What would you suggest to be generated that could reasonably be expected to work across different relational databases?

**Comment by cincuranet** [comment]
I would just make them `virtual` instead of `abstract`. Then these still can be overridden, yet if you don't use them, you can safely ignore them, as other virtual methods in `UpdateSqlGenerator`.

**Comment by AndriySvyryd** [comment]
@cincuranet If they are virtual they need to have an implementation, one that has reasonable behavior when not overridden.

**Comment by cincuranet** [comment]
Empty body or exception (neither is going to be breaking ATM) is good for me. Because there's no good general implementation every provider is either going to use skip it or override it, `SqlServer` provider included.

**Comment by AndriySvyryd** [comment]
@cincuranet It seems that you are overriding a lot of methods in `UpdateSqlGenerator`. Are there any that you actually leave as is? Would it make more sense for your provider to implement `IUpdateSqlGenerator` directly?

**Comment by cincuranet** [comment]
I override only `AppendXxxOperation`. The rest I (re)use (like `AppendInsertCommandHeader`, `AppendValuesHeader`, `AppendValues`, ...). So it doesn't make much sense to implement all this from scratch to use `IUpdateSqlGenerator` directly.

**Comment by AndriySvyryd** [comment]
Ok, we will consider extracting another base class that only has the more useful methods, but we need more feedback from another provider writer to make sure that the above is a good set.

**Comment by ajcvickers** [comment]
@cincuranet This issue is quite old; is this still something you need?

**Comment by cincuranet** [comment]
Yes.

**Comment by roji** [comment]
@cincuranet I'm sorry - I intended to get this done for 6.0, but it is now too late to get this in (we are now in principle only doing bug fixes). Part of the reason this got delayed, is that there's some probably related work on using the new ADO.NET batching API in the update pipeline (see #18990) - I'll likely work on both of these together at the beginning of the EF 7 work cycle.

**Comment by cincuranet** [comment]
@roji OK. :)
