### ISSUE TITLE
Error NU1605	Detected package downgrade: Microsoft.NETCore.App from 2.0.3 to 2.0.0

### ISSUE THREAD

**Issue by MikeYeager** [dotnet/efcore#10457]
I upgraded VS2017 to 15.4.5, verified that .NETCore SDK 2.0.3 is properly installed and upgraded all of the NuGet packages in my multi-project solution to the latest versions. The solution is configured to run all ASP.NET Core Web API projects in Docker/Linux. All of the updates went smoothly except for Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.1. It causes the build to break with this message in various places:

Error NU1605	Detected package downgrade: Microsoft.NETCore.App from 2.0.3 to 2.0.0. Reference the package directly from the project to select a different version. 
 MyProject.EF -> Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.1 -> Microsoft.NETCore.App (>= 2.0.3) 
 MyProject.EF -> Microsoft.NETCore.App (>= 2.0.0)

Removing this packages gets rid of the errors. Adding it back makes the errors re-appear.

Any help would be appreciated,
Mike
![efcoretoolserror](https://user-images.githubusercontent.com/7063813/33460638-a7b3c9fe-d5f4-11e7-9f08-63b82affaa99.png)

**Comment by bricelam** [comment]
It looks like you've included `Microsoft.EntityFrameworkCore.Tools.DotNet` as a `PackageReference`. It should only be included as a `DotNetCliToolReference`.

``` xml
<ItemGroup>
  <!-- Remove this -->
  <PakcageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet"
                    Version="2.0.1" />

  <!-- Keep this -->
  <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet"
                          Version="2.0.1" />
</ItemGroup>
```

**Comment by MikeYeager** [comment]
You are correct. I'm not sure how it got into my project file as a PackageReference, but that was it. Thank you.

**Comment by RaydelMiranda** [comment]
There is any way to tell dotnet to add cli tools reference in the proper section?

**Comment by bricelam** [comment]
NuGet/Home#4190

**Comment by oneal1801** [comment]
Thanks @MikeYeager  for the question and Thanks @bricelam for the answer it was very helpfull
