### ISSUE TITLE
Migration not working in a WebApi Project with an external Assembly reference

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [dotnet/efcore#10460]
**Steps to reproduce**

Create a new Solution and add a Class Library(.NET Core) Project. Add EntityFramework Core as a nuget package, and EntityFrameworkCore.Tools. This Project is called DAL. Set up a DataContext. Seen below.

```
public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options)
        : base(options)
    {
        }
        public DbSet<DisplayItem> DisplayItem { get; set; }
    }
```
Create a new Solution and add a WebApi project that injects and initializes the DbContext. This Project is called WebApi.
Reference the DAL Assembly in the WebApi Project. 

**The issue**

Your target project 'WebApi' doesn't match your migrations assembly 'DAL'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("WebApi")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.

**Steps in attempt to Solve**
1. I have attempted to add EntityFrameworkCore.Tools to the DAL project but there was an error. I'm assuming Doing Migrations from a class library is not something that should be done.

2. I have attempted to set my MigrationsAssembly to the DAL in this line.
     options.UseNpgsql(connection, b => b.MigrationsAssembly("DAL"))

### Further technical details

EF Core version: 2.0.1
Operating system:  Windows 10

Visual Studio version: 2017 -Command line Dotnet 2.0.1

Other details about my project setup:

This project is using for migrations
Npgsql.EntityFrameworkCore.PostgreSQL

**Comment by ChristopherLClark** [comment]
I needed to install EntityFrameworkCore in the DAL Project as well. I had installed the Tools but not the main nugetpackage.
