### ISSUE TITLE
Load objects into context before QueryClientEvaluation

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#10471]
Say I have a Post-Blog model and the Post has a member function IsPopular(). If I write:
`var popularPosts = ctx.Posts.Where(p => p.Blog != null && p.IsPopular());`
Then EF will fetch all posts that belong to a Blog from the DB, then evaluate IsPopular() on each of them client-side.

My problem is that, during evaluation of IsPopular(), the Post in question is not yet in the context, thus the function IsPopular() can't make use of navigation properties, change tracking, etc. The obvious workaround is to write ToList():
`var popularPosts = ctx.Posts.Where(p => p.Blog != null).ToList().Where(p => p.IsPopular());`
This puts all candidate Posts in the context, so IsPopular() can use their navigation properties.

I would like to do the above automatically - ideally, in Context.OnConfiguring, I would specify whether I want QueryClientEvaluation to put the objects in the context before doing client evaluation. Is such a thing possible?

**Comment by ajcvickers** [comment]
@Wain123 We spent some time discussing this with the following outcomes:
* It would be useful to make it easier for a function to generate an expression that can then be translated by the query pipeline. I have created issue #10497 to track this.
  * If the function expression uses navigation properties, then this will allow the query pipeline to ensure that they are populated in the normal way
  * It also means that the query won't necessarily be client evaluated anymore
* However, if the function actually needs the entity to be tracked, then there is nothing the query pipeline can do about this and the function will have to be evaluated after the query has completed.
  * We discussed adding some way to express this in the model, but it's not clear that this would have a lot of general value or that it would be significantly better than using ToList in the query. Therefore, closing this as by-design for now.
