### ISSUE TITLE
Scaffold-DbContext not producing output

### ISSUE THREAD

**Issue by kfitzuk** [dotnet/efcore#10473]
using VS2017v15.4.5, with an empty .NET core 2.0 class library, 

added Microsoft.EntityFrameworkCore.SqlServer (2.0.1), Microsoft.EntityFrameworkCore.Tools (2.0.1) through Nuget

running command Scaffold-DbContext "Server=XXX;Database=YYY;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

from tutorial on Reverse Engineering DB https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

Scaffold-DbContext does not report any errors, but does not produce any models, dbcontext classes. No exceptions are shown

**Comment by ralmsdeveloper** [comment]
I could not reproduce.

Which packages did you install?

Is Microsoft.EntityFrameworkCore.Tools really installed?

**Comment by bricelam** [comment]
Looks like you're hitting #10298. Add the following to your `*.csproj`:

``` xml
<PropertyGroup>
  <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
</PropertyGroup>
```
