### ISSUE TITLE
FromSql + composing throws SqlException when the sql has a trailing semicolon

### ISSUE THREAD

**Issue by gfoidl** [dotnet/efcore#10474]
When the sql statement has a trailing semicolon (;), then `FromSql` throws when there is further composing of the query.

```
Message: System.Data.SqlClient.SqlException : Incorrect syntax near ';'.
```
A trailing semicolon is not unusually. If the [docs](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql) state:
>  Transact-SQL statement terminator.Although the semicolon is not required for most statements in this version of SQL Server, it will be required in a future version.

So this should be supported. Furthermore this can prevent some subtle bugs, when T-SQL (with a trailing semicolon) gets copied over.

### Steps to reproduce

```c#
var actual = await context.Set<Customer>()
    .FromSql(@"SELECT * FROM ""Customers"";")
    .Where(c => c.ContactName.Contains("z"))
    .ToArrayAsync();
```
Like in _src/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs_

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 7, .net Core 2.0
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@gfoidl There are a few aspects to this:
* EF should be responsible for adding the semicolon or not as needed
  * That is EF would be responsible for the semicolon going in the correct place depending on whether FromSql is composed over or not.
* However, EF takes the approach of not adding the semicolon when SQL Server currently does not need it.
  * This is true for other generated SQL, not just in FromSql
  * If SQL Server ever really makes this required then we would update EF to start adding the smeicolon. However, such a change would be so breaking to the ecosystem that it seems unlikely to happen--if you have other information than that one document that this might actually happen, then we would be very interested to hear about it.

Based on this I'm closing this as by-design.

**Comment by gfoidl** [comment]
Thx for clarification.

**Comment by gfoidl** [comment]
@ajcvickers mybe you got me wrong. 
My intention is not that EF adds the semicolon -- no need to.
My intention is that _FromSql_ is tolerant against a semicolon in the given sql.

```c#
var query = context.Set<Customer>()
    .FromSql("SELECT * FROM Customers")  // no semicolon
    .OrderBy(c => c.Name)
```
works just fine, whilst
```c#
var query = context.Set<Customer>()
    .FromSql("SELECT * FROM Customers;")  // trailing semicolon
    .OrderBy(c => c.Name)
```
doesn't work. At runtime it will blow up with above mentioned exception.

That's why I mean EF / FromSql should just remove the trailing semicolon (cf. #10475). The rest remains untouched. It just a convenience to allow a trailing semicolon by the given sql statement.

If this change isn't possible (by design), so there should be at least a clear hint in [Raw SQL Queries - EF Core | Microsoft Docs](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) that no trailing semicolon is allowed.

**Comment by ajcvickers** [comment]
@gfoidl Thanks for the additional feedback. There are a couple of principles about FromSql that are relevant here:
* EF Core does not parse the SQL passed to FromSql and we don't want EF Core to start doing this because:
  * It adds a perf overhead that should be unnecessary in any case where the SQL is valid
  * EF Core is not the place to write or maintain SQL parsing and ensure that it is correct
* SQL passed to FromSql should be composable, and therefore should not have a trailing semicolon.

Based on these principles and the balance of value between doing something about a possibly invalid semicolon or not, we believe that not doing anything is the best option.

You comment on the documentation is valid and I will file a docs issue on that.
