### ISSUE TITLE
Yet another migrations with multiple projects question

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#10482]
[Related issue](https://github.com/aspnet/EntityFrameworkCore/issues/5900)
https://github.com/bricelam/Sample-SplitMigrations

Having reviewed above referenced example project demonstrating migrations, I am still unable to get it right.  I am only using two projects however.  Is it possible to configure migrations as follows: 

In my case I have two projects:
1.) MyProject.Services - contains DbContext
2.) MyProject.Migrations - this is an executable .net core console app.  Contains IDesignTimeDbContextFactory

From a powershell prompt in the directory containing .csproj file for MyProject.Migrations I run this:

    dotnet ef migrations add CreateDatabase
	
which of course yields the dreaded "Your target project 'MyProject.Migrations' doesn't match your migrations assembly...".

[Per the help file:](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)

"The target project defaults to the project in the current directory"
"The startup project is the one emulated by the tools when executing your project's code. It also defaults to the project in the current directory"

From the two lines above I presume I do not need to add --project or --startup-project because I am running from the directory containing MyProject.Migrations.csproj

	
This is .csproj file for MyProject.Migrations:	

	
	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>netcoreapp2.0</TargetFramework>
	  </PropertyGroup>

	  <ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
	  </ItemGroup>
	  
	  <ItemGroup>
		<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
	  </ItemGroup>
	  
	  <ItemGroup>
		<ProjectReference Include="..\MyProject.Services.csproj" />
	  </ItemGroup>

	</Project>

	
	
Also in Migrations project:

	public class MyContextFactory: IDesignTimeDbContextFactory<Db>
    {
        public Db CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<Db>();
            optionsBuilder.UseSqlServer(@"connection string", b =>  b.MigrationsAssembly("MyProject.Services"));
            return new Db(optionsBuilder.Options);
        }
    }

**Comment by bricelam** [comment]
`b.MigrationsAssembly("MyProject.Services")` says tells EF Core to look for migrations generated in the `MyProject.Services` project.
Running `dotnet ef migrations add` from the `MyProject.Migrations` directory will generate them there.

Where do you want your migrations generated?

**Comment by sam-wheat** [comment]
>>Running dotnet ef migrations add from the MyProject.Migrations directory adds them to that project.

That would be great if it did.... but I get the "assembly mismatch" error message.

I am running from the directory containing MyProject.Migrations.csproj I would like the migrations to be added to that project.

**Comment by bricelam** [comment]
Remove `b.MigrationsAssembly("MyProject.Services")`

**Comment by sam-wheat** [comment]
I took out b.MigrationsAssembly("MyProject.Services") as suggested and it still does not work.
I just started trying all combinations from directory containing executable (MyProject.Migrations) and nothing worked.
I changed working directory to MyProject.Services (contains DbContext) and I finally got it to work:

From MyProject.Services directory (not MyProject.Migrations):

    dotnet ef migrations add CreateDatabase --startup-project ../MyProject.Migrations --context Db --project ../MyProject.Migrations


IDesignTimeDbContextFactory (in MyProject.Migrations):



    public class MyContextFactory: IDesignTimeDbContextFactory<Db>
    {
        public Db CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<Db>();
            optionsBuilder.UseSqlServer(@"connection string", b => b.MigrationsAssembly("MyProject.Migrations"));
            return new Db(optionsBuilder.Options);
        }
    }
	
	
I think the help file is incorrect or there is a bug somewhere.  It appears the migration must be generated from the directory of the project containing the DbContext.

**Comment by bricelam** [comment]
Ah, sorry. I misunderstood your project layout. [This doc page](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects) might be useful.

You should be able to run from the MyProject.Migrations directory now without specifying `--startup-project` or `--project`. Getting the first migration generated is tricky.

**Comment by sam-wheat** [comment]
>>You should be able to run from the MyProject.Migrations directory now without specifying --startup-project or --project.

That's what I thought but I could not make it work.

**Comment by bricelam** [comment]
What error does it give?

    No executable found matching command "dotnet-ef"

or

    Your startup project 'MyProject.Migrations' doesn't reference Microsoft.EntityFrameworkCore.Design.

or something else

**Comment by sam-wheat** [comment]
Something like "Your target project 'MyProject.Migrations' doesn't match your migrations assembly...". 

Not sure if you read my entire post above but I ran the migration from the directory of the project containing the DbContext and I finally got it to work. 

I tried a lot of different parameters when running from the directory of the migrations project (just guessing) and always got the assembly mismatch error.

**Comment by bricelam** [comment]
I read that and saw that you were able to get it working. I'm just very surprised that you're still seeing a difference between these two commands:

    MyProject.Services> dotnet ef ... --startup-project ../MyProject.Migrations --project ../MyProject.Migrations
    MyProject.Migrations> dotnet ef ...

**Comment by sam-wheat** [comment]
One thing I noticed in the documentation link you posted is that the migrations project is supposed to be a class lib.  In my case it is a .netcoreapp application.

**Comment by bricelam** [comment]
It can be either. We just assume most people will want a class library.

**Comment by sam-wheat** [comment]
I tried to make a simple repro for you tonight but I could not get it to break.
I tried again with my live project and I could not get it to break there either.

I spent several hours last night trying every combination of parameters and nothing worked when running from MyProject.Migrations. 

Tonight I opened a command window from MyProject.Migrations and ran `dotnet ef migrations add junk `and it ran like a champ.

Does EF cache anything that might require a reboot of the machine?

**Comment by ajcvickers** [comment]
Closing this as it looks the questions have been answered.

@sam-wheat EF does not cache anything like that.

**Comment by cmaart** [comment]
Also happening to me.

I have two projects.
Web => Startup project containing ASP.NET
Application => Class Library containing my DbContext class and EF models (created by scaffold)

Fairly common I'd assume.

Anyway, I get this error when I run `dotnet ef migrations add Change` from cmd line in the Web project:
```
Your target project 'Web' doesn't match your migrations assembly 'Application'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
```

I already have this line in the startup class:
```
services.AddDbContext<MyDbContext>(options => options.UseSqlServer(connection, builder
                => builder.MigrationsAssembly("Application")));
```

Also when using --verbose it tells me that it uses the migrationAssembly parameter:

```
Using context 'MyDbContext'.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.1-rtm-30846 initialized 'MyDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=Application
```

I'm out of ideas and it takes me hours already. 
It seems to work though when going into the Application project folder, executing this line:
`dotnet ef migrations add Change --startup-project ..\Web\Web.csproj`

That is not the way it is intended though and is a workaround.

**Comment by bricelam** [comment]
> It seems to work though when going into the Application project folder, executing this line:
> `dotnet ef migrations add Change --startup-project ..\Web\Web.csproj`

You can also do it like this from the Web project folder.

    dotnet ef migrations add Change --project ..\Application\Application.csproj

**Comment by demonguru18** [comment]
Incase you face the issue in .Net Core 2.2.4 to update with multiple projects
`dotnet ef database update --startup-project ../Application/Application.csproj --project ../Application/Application.csproj`
