### ISSUE TITLE
Soft delete with shadow properties and query filters

### ISSUE THREAD

**Issue by SamazoOo** [dotnet/efcore#10492]
I've created an interface to try to do a soft delete, mixing shadow properties and query filters. But it's not working.
```c#
public interface IDeletableEntity {}
```
And then in my model builder
```c#
 builder.Model.GetEntityTypes()
                .Where(entityType => typeof(IDeletableEntity).IsAssignableFrom(entityType.ClrType))
                .ToList()
                .ForEach(entityType =>
                {
                    builder.Entity(entityType.ClrType).Property<Boolean>("IsDeleted");
                    builder.Entity(entityType.ClrType).HasQueryFilter(e => EF.Property<Boolean>(e, "IsDeleted") == false);
                });
```
But the line with the query filter doesn't compile. The error I got is "cannot convert lambda expression to type 'lambda expression' because it is not a delegate type"

If I do this it's working.

```c#
builder.Entity<MyEntity>().HasQueryFilter(m => EF.Property<Boolean>(m, "IsDeleted") == false);
```

there are any way to do this? It's in order to have an Interface with IDeletableEntity and not have to do it, in every Entity that I want to use a soft delete Entity

Many thanks in advance,

**Comment by ajcvickers** [comment]
@SamazoOo Creating an expression tree of the correct type is quite hard in this case, but there is some code in #10257 to help, and that issue is about making it easier in the future.
