### ISSUE TITLE
Why isn't it possible to add indexes via annotations?

### ISSUE THREAD

**Issue by JoshuaWalsh** [dotnet/efcore#10503]
Hi,

On [this page](https://docs.microsoft.com/en-us/ef/core/modeling/indexes) it states that "Indexes can not be created using data annotations." but I'm wondering why this is the case. For my project, data annotations seem like a much cleaner way of providing this sort of information. I'd love for my index code to be in the same place as the entity it applies to, rather than all gathered in by DbContext class.

Is there a technical reason this isn't possible/easy, or is it just not implemented?

Thanks,
Josh

### Further technical details
EF Core version: 1.1.4
Database Provider:Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10
IDE: Visual Studio 2017 (15.3.1)

**Comment by ajcvickers** [comment]
@YMIndustries It had issues the way it was implemented in EF6, but there is no reason it can't be implemented in EF Core--it is being tracked by #4050
