### ISSUE TITLE
Bug in Linq Where Clause

### ISSUE THREAD

**Issue by shankkushi** [dotnet/efcore#10505]
When we set where condition on collection with single equals sign by mistake with column type bool as like "IsActive" then it will not work properly i.e

.Where(e=> e.IsActive == true) : It will work correctly

But If write as below :
.Where(e=> e.IsActive = true) : It will update value of IsActive in collection and return all rows of collection without comparing condition.

You can also test on below link :
http://rextester.com/TZDD88407

**Comment by Dispersia** [comment]
Why do you think it should do a comparison on that? That's not true C#, That expression is doing the same as a `bool res; return res = true;` which will make res true, and return res (as true). Your expression without assignment is .Where(true).
