### ISSUE TITLE
It is not possible to remove all join entities and add only necessary join entities again

### ISSUE THREAD

**Issue by andrewtsw** [dotnet/efcore#10510]
Hi.
I am working with many to many relationships.
https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/
My sample based on this article.

When I edit a post I can change the post title, add new tags or remove some tags.
And when I save changes, I can implement it in two ways:
1. Remove all existing tags from the post and add tags again. It is not an elegant solution, but it is easy and fast to implement.
2. Remember added and deleted tags. In this case, I can just add references to new tags and remove references to removed tags.

I can not implement first way with EFCore 2.0 because I get an exception.
Is it possible to track entities by key and status? 
Because here we have two entities with the same key but with different status.

Exception message: 
The instance of entity type 'PostTag' cannot be tracked because another instance with the key value 'PostId:1, TagId:2' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
Stack trace:
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
at EFCoreManyToManyTest.Program.Main() in C:\Projects\EFCoreManyToManyTest\EFCoreManyToManyTest\Program.cs:line 67

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;
using Microsoft.Extensions.Logging.Debug;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EFCoreManyToManyTest
{
    public class Program
    {
        public static void Main()
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var tags = new[]
                {
                    new Tag { Text = "Golden" },
                    new Tag { Text = "Pineapple" },
                    new Tag { Text = "Girlscout" },
                    new Tag { Text = "Cookies" }
                };

                var posts = new[]
                {
                    new Post { Title = "Best Boutiques on the Eastside" },
                    new Post { Title = "Avoiding over-priced Hipster joints" },
                    new Post { Title = "Where to buy Mars Bars" }
                };

                context.AddRange(
                    new PostTag { Post = posts[0], Tag = tags[0] },
                    new PostTag { Post = posts[0], Tag = tags[1] },
                    new PostTag { Post = posts[1], Tag = tags[2] },
                    new PostTag { Post = posts[1], Tag = tags[3] },
                    new PostTag { Post = posts[2], Tag = tags[0] },
                    new PostTag { Post = posts[2], Tag = tags[1] },
                    new PostTag { Post = posts[2], Tag = tags[2] },
                    new PostTag { Post = posts[2], Tag = tags[3] });

                context.SaveChanges();
            }

            using (var context = new MyContext())
            {
                var post = context.Posts
                    .Include(p => p.PostTags)
                    .Single(p => p.Title == "Best Boutiques on the Eastside");

                // I removed tag 'Pineapple' and add tag 'Cookies'

                var tags = context.Tags.ToList();

                // Remove all tags from post
                post.PostTags.Clear();

                // Add unchanged tag 'Golden'
                post.PostTags.Add(new PostTag { Post = post, Tag = tags[0] });

                // Add new tag 'Cookies'
                post.PostTags.Add(new PostTag { Post = post, Tag = tags[3] });

                context.SaveChanges();
            }
        }

        public class Post
        {
            public int PostId { get; set; }
            public string Title { get; set; }

            public IList<PostTag> PostTags { get; } = new List<PostTag>();
        }

        public class Tag
        {
            public int TagId { get; set; }
            public string Text { get; set; }

            public IList<PostTag> PostTags { get; } = new List<PostTag>();
        }

        public class PostTag
        {
            public int PostId { get; set; }
            public Post Post { get; set; }

            public int TagId { get; set; }
            public Tag Tag { get; set; }
        }

        public static readonly LoggerFactory MyLoggerFactory
             = new LoggerFactory(new[] { new DebugLoggerProvider((s, ll) => ll != LogLevel.Debug) });

        public class MyContext : DbContext
        {
            public DbSet<Post> Posts { get; set; }
            public DbSet<Tag> Tags { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
                => optionsBuilder
                    .UseLoggerFactory(MyLoggerFactory)
                    .UseSqlite("Data Source=MyDatabase.db")
                .EnableSensitiveDataLogging(); // For debug purposes.

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<PostTag>()
                    .HasKey(t => new { t.PostId, t.TagId });
            }
        }

    }
}
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.3.4

**Comment by ajcvickers** [comment]
@andrewtsw Looks like you are hitting #7340, which is fixed in 2.1--you might want to test with a nightly build (feed on repo homepage) and let us know if it resolves the issue for you. For 2.0, the most common workaround is to make the change in two parts, with a call to SaveChanges between the two.
