### ISSUE TITLE
Query: Oracle: DateTimeOffset.Minute/Hour is client eval

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#10515]
See 
Where_datetimeoffset_minute_component
Where_datetimeoffset_hour_component

They generate different results from CLR. Presently client evaluated.

**Comment by ajcvickers** [comment]
Find to leave as client evaled for now. (We would consider a PR for this, but EF team is not planning to work on this.)

**Comment by ajcvickers** [comment]
This is an issue identified on the Oracle sample provider. We don't plan to fix this in the sample, but we would be happy for a community contributor to fix it. Also, anyone taking the sample as a starting point for production code should consider fixing this issue.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
