### ISSUE TITLE
Support for per-operation collation

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#10539]
Unless I am mistaken, international/multi-language database support in EntityFramework Core is very limited. Our only option right now is to set the collation at design time, but it is very limiting because no collation is good for every language. It would be very useful to be able to specify collation on a per-operation basis. Most database providers support it. PostgreSQL supports it and its syntax is very simple (https://www.postgresql.org/docs/9.1/static/collation.html): `SELECT * FROM test1 ORDER BY column1 COLLATE "fr_FR";` . Even better, EF Core could set the collation automatically based on the value of `CultureInfo.CurrentCulture`.

**Comment by ajcvickers** [comment]
@orobert91 Thanks for the suggestion. I've made a note to look at the comments here in #8813 and updated the title there to be more general. Closing as duplicate.
