### ISSUE TITLE
Handling token-based authentication with Azure SQL DB using Azure AD auth

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#10538]
A reader/reviewer of [the book I am writing](http://bit.ly/2m8KRAZ) has asked me to cover how to use EF Core with [Use Azure Active Directory Authentication for authentication with SQL Database or SQL Data Warehouse](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication).

I have looked but couldn't find anything on EF Core, but I did [find this](https://www.azuredockit.com/2017/08/16/azure-ad-authentication-with-azure-sql-entity-framework-and-dependency-injection/), but I'm not sure its for EF Core, and it doesn't handle the refresh.

Can you suggest a way I might add support for AAD token access to a SQL database in EF Core. Any information or thoughts gratefully received.

**Comment by ErikEJ** [comment]
Create the SqlConnection outside of EF and initialize with that?

**Comment by JonPSmith** [comment]
Hi @ErikEJ. Ok I can see the `DbConnection` class in the EF Core code, and I can see the `RelationalConnection`, which is used in classes like `SqlServerConnection`, but how do I get this injected into the options setup?

Have you got (another!) useful example I can look at?

**Comment by ErikEJ** [comment]
UseSqlServer has an overload that takes a DbConnection: 
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsExtensions.cs#L57

**Comment by JonPSmith** [comment]
OK, got it. I'll have a play with that.

**Comment by ajcvickers** [comment]
@JonPSmith For the time being @ErikEJ's suggestion (manage the SqlConnection in the app) is probably the way to go. However, I believe there are some improvements planned in this area that should make it easier in the future.

**Comment by JonPSmith** [comment]
Hi @ajcvickers. Thanks, that is helpful. I will leave this out of the book for now.
