### ISSUE TITLE
New UWP App, new .NET Standard  / Core data library - doesnt work

### ISSUE THREAD

**Issue by deanchalk** [dotnet/efcore#10549]
IVe tried ALL of the online docs. 
Ive fiddled with csproj files, ive installed different version of the EF Core tooling, ALL scenarios end with exceptions in PM console or the Add-Migration command failing silently. 

Many different exceptions depending on what 'fix' I was trying. Most common are a variety of incompatible project type exceptions (either with .net standard or core library project), but also 'System.Private.Corelib not found' exceptions amongst others.

This is a simple startup situation - haven't even got around to writing any code yet apart form a couple of model classes.

If EF is incompatible with UWP then i'll try something else, Only there seems to be no statement to that fact.

Any help would be appreciated. If someone n the know can create a solution with 1 or 2 projects - 1 = UWP, and if necessary 2 = lib. Get the migrations working then stick it all in a repo, I can download and use that as a start. Ive spent a day on this now - cheers

Desn

**Comment by bricelam** [comment]
You're hitting #10298. Add the following to your .NET Standard Class Library.

``` xml
<PropertyGroup>
  <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
</PropertyGroup>
```

We're working to get this patched as soon as possible.

**Comment by bricelam** [comment]
Here is [the documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/#frameworks) of our recommended approach for UWP.

**Comment by ajcvickers** [comment]
@deanchalk Here are some additional pointers in addition to the comments from @bricelam:
* [This walkthrough](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started) seems to be what you are looking for
* Make sure that you have the correct versions of Windows, Visual Studio, and EF Core, as listed in the walkthrough--older versions will not work correctly in this case
* The walkthrough has a link to a functional sample project that can be downloaded
* [This issue](https://github.com/aspnet/EntityFramework.Docs/issues/581) is tracking a problem with Visual Studio that you may run into if some of the steps in the walkthough are preformed in a different order than shown

**Comment by deanchalk** [comment]
thanks very much, I will give all of these suggestions a go.
