### ISSUE TITLE
F# .Net Standard 2.0 + Entity Framework Core

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/efcore#10541]
I am trying to use EF Core on F# but this error appears

```
FS1109	A reference to the type 'Microsoft.EntityFrameworkCore.Infrastructure.WarningsConfigurationBuilder' in assembly 'Microsoft.EntityFrameworkCore' was found, but the type could not be found in that assembly
```

### Steps to reproduce

```
Added NuGet package  
Microsoft.EntityFrameworkCore    2.0.1
MySql.Data.EntityFrameworkCore     8.0.9-dmr

module Contexto

open Microsoft.EntityFrameworkCore

type BloggingContext() =
    inherit DbContext()
        member val Blogs: DbSet<Blogs> = Unchecked.defaultof<DbSet<library.MyClass>> with get, set    // (*"valor padrao")
         //public DbSet<Post> Posts { get; set; }

        override OnConfiguring(optionsBuilder: DbContextOptionsBuilder) =
            optionsBuilder.UseMySQL(@"Server=192.168.10.102;Database=myDataBase;Uid=root;Pwd=abcf;")
            |> ignore
        
```

### Further technical details
EF Core version: 2.0.1
Database Provider: MySql.Data.EntityFrameworkCore 8.0.9-dmr
Operating system: Windows 10 Pro 64bits
IDE: Visual Studio 2017 15.6.0 Preview 1.0

**Comment by TonyHenrique** [comment]
I downgraded **MySql.Data.EntityFrameworkCore** to version 6.10.5
then the Project compiles OK.

**Comment by TonyHenrique** [comment]
If I try to use this F# Project containing this Entity Framework Core, from a WPF Project, this error appears:

`Unknown build error, 'Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.DesignTimeProviderServicesAttribute' from assembly 'Microsoft.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'	WpfApp2			
`

**Comment by bricelam** [comment]
Could you share your project? It seems like there may be some missing binding redirects or incompatible NuGet packages...

**Comment by TonyHenrique** [comment]
Sure. Can you please ask somebody to do a blog posting about:
Basic example just like the C# version ( Blog / Postings ) from https://docs.microsoft.com/en-us/ef/core/
**How to use Entity Framework Core in F#** 

My buggy solution, in a ZIP file
https://drive.google.com/open?id=1FLBCzAsuk49SriiA9a216ieebcOyFBPR

**Comment by bricelam** [comment]
I suspect a lot of your pain is coming from referencing a "new" F# project (.NET Standard class library) from a "classic" one (WPF). I know the C# and VB projects required a bit of work in this area to make it a nice experience...

**Comment by bricelam** [comment]
The MySQL provider may also not be compatible with EF Core 2.x yet.

**Comment by TonyHenrique** [comment]
This F# + .Net Standard + .Net Framework + Nuget packages 
seems to have some integration problems.
I also tried to use F# SqlProvider

> FS3053	O provedor de tipos 'FSharp.Data.Sql.SqlTypeProvider' relatou um erro: O construtor do provedor de tipos gerou uma exceção: **Invalid host of cross-targeting type provider.** Exception: System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.   em <StartupCode$FSharp-Data-SqlProvider>.$ProvidedTypes.referencedAssemblyPaths@8509.GenerateNext(IEnumerable`1& next)   em Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()   em Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()   em Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)   em ProviderImplementation.ProvidedTypes.ProvidedTypesContext.Create(TypeProviderConfig cfg, FSharpOption`1 assemblyReplacementMap)

**Comment by TonyHenrique** [comment]
More exceptions:

> System.TypeLoadException: 'Method ApplyServices on type MySql.Data.EntityFrameworkCore.Infraestructure.MySQLOptionsExtension do assembly MySql.Data.EntityFrameworkCore, Version=6.10.5.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d does not have an implementation.'

**Comment by TonyHenrique** [comment]
I am looking for a solution where I can use C#, F#, ASP.Net, ASP.Net Core, WPF, UWP, Xamarin, Entity Framework (Core), MongoDB (CosmosDB) seamlessy. I think that Microsoft should do a blog posting with all this. I am a little confused.

**Comment by ajcvickers** [comment]
@TonyHenrique Curious as to why you want to use all those technologies in a single solution. Can you provide some details?

**Comment by TonyHenrique** [comment]
I just tried to mix up everything avaliable in the .Net
This solution is just a test I am doing. 

The team here is using PHP, MySQL, C# (.Net Core)
Then I went to test if 

- F# + the mentioned databases / connection ways would work well.
- Interop between the .Net Core and .Net 4.7.1
- Xamarin Forms
- WPF
- UWP

etc.

I could make it work / interop well using .Net 4.7.1, Entity Framework 6

When it comes to .Net Core, EF Core, I could not make it work / interop well.

The problem is on .Net 4.7.1  I will not be able to use these Class Libraries on Xamarin Forms.

**Comment by aiba1805** [comment]
Use .NET Standard 2.0 Library with Xamarin with MySql/Connector EF Core,
but test throwing some exception : 
System.TypeLoadException : Type MySql.Data.EntityFrameworkCore.Infraestructure.MySQLOptionsExtension has invalid vtable method slot 4 with method Microsoft.EntityFrameworkCore.Infrastructure.RelationalOptionsExtension:ApplyServices (Microsoft.Extensions.DependencyInjection.IServiceCollection)
I think it's MySql ef core does not supporting .net standard 2.0
What you think about this?

**Comment by cartermp** [comment]
Hey @TonyHenrique, if you reference your .NET Standard library from a .NET Core console app, do you still see the same issue as when you reference it from your WPF project?

**Comment by bricelam** [comment]
Just saw this line in the release notes for Visual Studio 2017 version 15.6 Preview 3:
* .NET Standard projects can now be referenced by F#/.NET Framework projects.

**Comment by cartermp** [comment]
Yep, this is now enabled, though there is currently an issue in that because .NET Standard projects use the .NET Core SDK in VS, and the way in which FSharp.Core is resolved in that context is different than with .NET Framework. Thus, it's likely that doing this will result in a runtime error where the assembly manifests for FSharp.Core are mismatched.

Long story short is that today, it's probably in one's best interest to reference .NET Standard components from .NET Core components just so that tooling issues don't get in the way.

**Comment by divega** [comment]
Visual Studio 2017 version 15.6 includes several improvements to F# tooling's .NET Standard support (see [release notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes) for details). 

I am going to go ahead and close this issue as external, because there doesn't seem to be any actionable item for EF Core and I hope the underlying issue has been resolved. 

If it turns out that this still repros with Visual Studio 2017 15.6, please consider creating a new issue at https://github.com/Microsoft/visualfsharp/issues/new.
