### ISSUE TITLE
Want to migrate from dotnet core 1.x to 2.0 

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/efcore#10560]
Hi Team,

I am migrating my project from dotnet core 1.x to 2.0  and when I am updating nuget package references so found below issue 

Error : 
**NU1605	Detected package downgrade: Microsoft.VisualStudio.Web.BrowserLink from 2.0.1 to 1.0.1. Reference the package directly from the project to select a different version. 
 CenterManagementSystem.UI (>= 1.0.0) -> CenterManagementSystem.Platform (>= 1.0.0) -> Microsoft.AspNetCore.All (>= 2.0.3) -> Microsoft.VisualStudio.Web.BrowserLink (>= 2.0.1) 
 CenterManagementSystem.UI (>= 1.0.0) -> Microsoft.VisualStudio.Web.BrowserLink (>= 1.0.1)	CenterManagementSystem.UI	C:\My Project\HBI\yoyo-center-management-system\CenterManagementSystem\DEV\src\CenterManagementSystem.UI\CenterManagementSystem.UI.csproj**

and I am sharing you my code screen shot regarding above issue as below 

![image](https://user-images.githubusercontent.com/4157756/34005829-2e35bd06-e122-11e7-8f14-7cd588c67414.png)

Please update me any solution or any other reference url regarding same.

**Comment by ralmsdeveloper** [comment]
I recommend removing all references, then adding Microsoft.AspNetCore.All, and the rest that your project is dependent on.

**Comment by ralmsdeveloper** [comment]
Your project is still using dependencies from project.json.
If you can create a new project and migrate, do not hesitate to do it!

**Comment by ankurjasoria** [comment]
@ralmsdeveloper  Thanks for quick reply !
I am unable to create new project and need to migrate same 1.x to 2.0. I'll try to remove all current references and add one by one.

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/Home/issues/2313
