### ISSUE TITLE
InMemory: Unusual side-effects of seeding

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#10573]
Extracted from customer project
Repro code:  https://github.com/smitpatel/EFInMemory

Run command: dotnet run -f netcoreapp1.1 --no-restore ; dotnet run -f netcoreapp2.0 --no-restore

1.1 00:00:00.1375701
2.0 00:00:00.2253677

Removing 
            context.States.ToList();
            context.Countries.ToList();

From seed method (which is using different context)

1.1 00:00:00.3238214
2.0 00:00:00.2509411

Calling ToList on some DbSet in seed method should not affect query running in different context but it does.

**Comment by ajcvickers** [comment]
@AndriySvyryd This may be part of the customer issue, but could not be the whole story. Please contact @smitpatel for full details on the investigation.

**Comment by AndriySvyryd** [comment]
Closing unless this is still an issue in 2.x

**Comment by ardalis** [comment]
Has anyone confirmed whether this is fixed in 2.1? It's an issue in 2.0 (that's where the issue first occurred). I'm confused by the reason given for closing this issue...

**Comment by ajcvickers** [comment]
Re-opened to discuss in triage.

**Comment by ajcvickers** [comment]
Closing again--responded to @ardalis on email about the general issue from which this came, and confirmed previous triage decision.
