### ISSUE TITLE
How to Change Default Connection Factory

### ISSUE THREAD

**Issue by BingZL1983** [dotnet/efcore#10577]
When I create a console application and connect it to a database that was created in SQL Server Management Studio with Entity Framework 6.1.3, then the following code was created in the app.config. Which assume there is no explicit connection string, so it uses LocalDb instance for a context instead.

```C#
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
</configuration>
```

### My question is what do I need to do or what do I need to set up either on SQL Server Management Studio or Visual Studio in order to have app.config to have something like following in the first place?

```C#
<entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="Data Source=localhost; Integrated Security=True; MultipleActiveResultSets=True" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
</configuration>
``

**Comment by ajcvickers** [comment]
@BIngZL1983 This is the github repo for EF Core. EF6 can be found at https://github.com/aspnet/EntityFramework6

That being said, EF will create a default connection factory to localdb if it is installed, or to SQL Express if localdb is not found, but never to localhost. The connection factory is only used if your application does not specify a connection string. Docs can be found here: https://msdn.microsoft.com/en-us/library/jj592674(v=vs.113).aspx
