### ISSUE TITLE
Json.Net PopulateOject modifies 'id' and triggers error about modfying key

### ISSUE THREAD

**Issue by jefhai** [dotnet/efcore#10585]
I'm trying to take a json body and update an EFC model, i.e. only modify the members that have changed. The problem is it contains the id of the records, which is fine it is modifying that record or creating a new one. But it is flagging `id` as modified and causing an error when saving the record in EFC.

What do you guys recommend? How do you update a DB record using EFC?

**Comment by ajcvickers** [comment]
@jefhai Without more specifics it is hard to give a clear answer. In a nutshell, the key value cannot change. To update an existing entity it should be attached to the context with the correct key value. After that point it should not get into the modified state unless its value is changed--if it is getting marked as modified without the value changes, then please post a full repro for this so we can investigate.

These pages in the docs may help:
* Basics of saving changes: https://docs.microsoft.com/en-us/ef/core/saving/basic
* Disconnected scenarios: https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities
