### ISSUE TITLE
Oracle: Remove OracleCreateUserOperation

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10590]
I'm concerned about this code finding its way into an official provider; it feels pretty hacky--it always uses the username as the password and there is no way to specify it literately.

**Comment by ajcvickers** [comment]
Note from triage: we should decide how to better message the state of the sample and track issues found in it. For example:
* Update the readme with known issues?
* Add TODOs to the code?
* Put issues on the backlog with some tag or list so they can be found?

**Comment by ajcvickers** [comment]
This is an issue identified on the Oracle sample provider. We don't plan to fix this in the sample, but we would be happy for a community contributor to fix it. Also, anyone taking the sample as a starting point for production code should consider fixing this issue.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
