### ISSUE TITLE
SQLite: Make AUTOINCREMENT more first-class

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10597]
Right now, `AUTOINCREMENT` is more  or less an implementation detail of SQLite Migrations. We should make it more first-class like `IDENTITY` on SQL Server. This would include a convention, `ModelBuilder` API, validation, etc. for it.

**Comment by smitpatel** [comment]
Duplicate of #10228

**Comment by bricelam** [comment]
Thanks, I saw it but didn't read it since the title looked unrelated. I'll update its title.
