### ISSUE TITLE
How to add database in .NET Command Line Tools 2.2.0-preview

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#10599]
How do I set up a database using the powershell and add-migration in this new framework? Enable migrations wont even work... and how do I do automatic migrations?

**Comment by smitpatel** [comment]
There is no `Enable-Migrations` in EF Core. More information about powershell commands here https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell

As for Automatic migrations, https://github.com/aspnet/EntityFrameworkCore/issues/3760#issuecomment-158490686
There are ways to do automatic migrations programmatically. Stackoverflow would be good place to ask.

**Comment by ColbyBurke** [comment]
@smitpatel Thanks!
