### ISSUE TITLE
code First Migration 

### ISSUE THREAD

**Issue by coderdp** [dotnet/efcore#10605]
I have two versions：Init and EditPwdLength 
Q1:Use "Update-Database" How to select version?
Q2:How to generate script SQL？
thk。

**Comment by John0King** [comment]
use `Script-Migration`  and there are  parameters let you choose `From` and  `To`

**Comment by ajcvickers** [comment]
@coderdp For additional information, see https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/
