### ISSUE TITLE
ManyToOne() or OneToOne() issue

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/efcore#1061]
I have an application where I can't seem to figure out how a one to one (one-way) relationship is to be mapped. 

The model is pretty simple - Albums that have Artist and Tracks properties with one-way relationships (ie. no back link from these entities)

The problem here is the OneToOne or ManyToOne relationship of Album->Artist. No matter what I've tried (and Rowan and Diego as well) the artist is not filled and the .Include() call fails.

Initially I thought this was a problem with .Include() but I think it's a matter of the relationship being defined incorrectly.

You can find the model and context classes here:
https://github.com/RickStrahl/AlbumViewerVNext/tree/master/src/AlbumViewerBusiness/Models

The API controller code I've used for testing is here:
https://github.com/RickStrahl/AlbumViewerVNext/blob/master/src/AlbumViewerVNext/Controllers/MusicStoreApiController.cs

I mapped this model manually to an existing database which is also included in the App_Data folder if you want to try it out.

**Comment by housseinimaiga** [comment]
Very helpfull thanks @RickStrahl
