### ISSUE TITLE
EF Core Add Migration Issue

### ISSUE THREAD

**Issue by raskolniko** [dotnet/efcore#10611]
![efcorereport](https://user-images.githubusercontent.com/4662786/34383668-2dfcd938-eb30-11e7-8df2-d0895f8473ad.png)
I have this issue with adding migration. I tried to clear nuget cache. reinstalled all the packages. 
there's nothing in output window.

**Comment by ErikEJ** [comment]
Try with -Verbose

**Comment by raskolniko** [comment]
@ErikEJ  Hi, Erik, thank you for the response, I have tried with -Verbose, but unsuccessfully ...

**Comment by ralmsdeveloper** [comment]
Where is the project? There is no project selected.

**Comment by raskolniko** [comment]
@ralmsdeveloper  I Hide it.

**Comment by ralmsdeveloper** [comment]
I want to talk in the Package Manager Console

**Comment by raskolniko** [comment]
@ralmsdeveloper  I erased Project From There .....

**Comment by ralmsdeveloper** [comment]
All right, now it makes sense!

**Comment by bricelam** [comment]
You're probably hitting #10298.

Add the following to your `*.csproj`:

``` xml
<PropertyGroup>
  <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
</PropertyGroup>
```

**Comment by raskolniko** [comment]
@bricelam  Thank you, it worked.
