### ISSUE TITLE
Can EF support multiple databases and multiple tables, similar to Sharding-JDBC？

### ISSUE THREAD

**Issue by TimChen44** [dotnet/efcore#10622]
Can EF support multiple databases and multiple tables, similar to Sharding-JDBC？

**Comment by ajcvickers** [comment]
@TimChen44 I don't have a deep enough knowledge of Sharding-JDBC to be able to answer this directly. EF doesn't so any sharding directly or transparently, but it may be possible to use EF with lower-level sharding implementations.

**Comment by xuejmnet** [comment]
[sharding-core](https://github.com/xuejmnet/sharding-core) i‘m create this lib for efcore
