### ISSUE TITLE
Easily Filtered DB Set

### ISSUE THREAD

**Issue by granthoff1107** [dotnet/efcore#10623]
I want to use roles to limit access to my database.
Based off of my roles I have a written set of rules of what a person can access.
In a sense a default filter for each DBSet<Entities>.
This filter is based off of roles from an external Token server and works off 
of the foreign key relations.

There is no easy way to have a default filtered set.

Your context injects DbSets during creation.
Yet your InternalDbSet do not expose the _entityQueryable

`    public class InternalDbSet<TEntity> :
        DbSet<TEntity>, IQueryable<TEntity>, IAsyncEnumerableAccessor<TEntity>, IInfrastructure<IServiceProvider>
        where TEntity : class
    {
        private readonly DbContext _context;
        private IEntityType _entityType;
        private EntityQueryable<TEntity> _entityQueryable;
        //...
    }` 

Perhaps you have a QueryInterceptor somewhere???
wouldn't it make sense to just have an easy way to filter and control how your dbSet are created?

**Comment by ajcvickers** [comment]
@granthoff1107 Looks like you are looking for query filters: https://docs.microsoft.com/en-us/ef/core/querying/filters

With regard to the creation of DbSets, they don't need to be injected--you can create them with context.Set and expose them however you want. They only get injected if the context has a DbSet property with a getter and a setter.
