### ISSUE TITLE
multiple table to one foreign key relationship

### ISSUE THREAD

**Issue by ErliSoares** [dotnet/efcore#10620]
I know it's not a good practice, but I'm working on a project that contains "foreign key" referencing more than one table, the whole bank is this way, I wanted to know if the entity framework supports this type of relationship, so I studied and researched is not supported, if they have a solution, it helps a lot, I'm migrating to the entity framework. But without this feature I can not migrate, an example below:
Data Base:
```
Tasks
- Id
- SourceId
- TypeSource //Used to set the connection
- Description

OrderService
- Id
- Description

Schedule
- Id
- Description
```
Code:

```
ITaskSource
- Id -> int
- Description

Tasks
- Id -> int
- Source -> ITaskSource
- TypeSource -> string //Used to set the connection
- Description -> string

OrderService : ITaskSource
- Id -> int
- Description -> string

Schedule : ITaskSource
- Id -> int
- Description -> string
```

**Comment by Tarig0** [comment]
This reads as table per heirchy

Store all itasksources in one table with

Id
Type
Description

Fk tasks Id + types our cells to identify and type

**Comment by Tarig0** [comment]
Actually it might be easier to consolidate the three classes into one

**Comment by Tarig0** [comment]
After taking a closer look at this seems to be me like you have 2 types of tasks

OrderTask, ScheduleTask -> Task

Abstract Task
- Id -> int
- Description -> string

OrderTask -> Task
- Source -> OrderService

ScheduleTask -> Task
- Source -> Schedule


```c#
modelBuilder.Entity<Task>().HasDiscriminator("TaskSource").HasValue<ScheduleTask>("Schedule").HasValue<OrderTask>("Order")
```

**Comment by ErliSoares** [comment]
As soon as I get the time, I'll test, thank you.

**Comment by ajcvickers** [comment]
@ErliSoares Looks like you are asking for polymorphic relationships, which is being tracked by #7623
