### ISSUE TITLE
Question: Module based Migrations 

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#10630]
Is there a way that we can generate migrations in a module based way?

For example

BaseDbContext:DbContext{
Customers
}

QOMDbContext:BaseDbContext{
Orders
}

WorkflowDbContext:BaseDbContext{
WorkflowState
}

I would like to be able to generate migrations for each of these three (over simplified) contexts. Where Workflow and QOM won't generate changes on Customers (without having to edit the migrations after the fact)

**Comment by bricelam** [comment]
You may be looking for #2725

**Comment by Tarig0** [comment]
Correct Sir
