### ISSUE TITLE
Global Query Filter not working

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#10649]
I am using the SQLite provider in an xamarin app targeting netstandard 2.0 on monodroid80.
I have some records that have a status id.
I am attempting to provide a conditional global query filter.

```
modelBuilder.Entity<Callfile>().HasQueryFilter(e => !_filteringOn || e.StatusId == 1);
```

Basically when `_filteringOn` is false, I dont want to apply any filtering.
When `_filteringOn` is true, I want the status id == 1 filter to be applied.

When I use my DbContext, If I set `_filteringOn` to true, and do `dbContext.Callfiles.ToList()` - it doesn't return me any records. If i look at the individual callfile records though, they all have a status id == 1.

If i remove the global query filter - I get all the records as expected.

### Further technical details
EF Core version: 
```
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />  
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="2.0.3" />
```

Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlLite)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by dazinator** [comment]
I think I may have raised this prematurely. Will reopen once I have verified issue a bit more fully.

**Comment by LordMike** [comment]
@dazinator you also have another option: Using `IgnoreQueryFilters` on the `DbSet`. This bypasses all filters.

**Comment by dazinator** [comment]
@LordMike thanks, I knew about that but I have some additional filters I need to keep in place (like soft delete) so ignore filters wasnt an option for me. The above code actually did work in the end so it turned out to be a nice way to have conditional filters.

**Comment by challamzinniagroup** [comment]
@dazinator  I've run into this same type of thing - what I found also is that the DbContext caches the Modeling - meaning ` OnModelCreated ` is called once, the first time the context is spun; and not again as the results of that initial call are cached and re-used for performance.

You can disable this caching but for obvious performance reasons you don't really want to do that.

The solution I came up with was to inherit my primary context into a second context. The first contains all those global filters that you'll always want (eg. soft deletes) and the second, derived context adds the optional filters. Then, in my injection logic; I can determine which context to deliver based on the knowledge of whether I need the additional filtering or not, like so:

```
services
	.AddDbContext<MyRootDbContext>()
	.AddDbContext<MyExtendedFilteredDbContext>()
	.AddScoped(sp => 
		SomeVarDoINeedAdditionalFiltering == true
			? sp.GetRequiredService<MyExtendedFilteredDbContext>() as IMyDbContext
			: sp.GetRequiredService<MyRootDbContext>() as IMyDbContext);
```

Hope this helps!
