### ISSUE TITLE
Migration Entity Framework Core 2.0 / Asp net core 2.0

### ISSUE THREAD

**Issue by Elite182** [dotnet/efcore#10667]
Hi,

I will break my computer, I pass 2 days on this.
I start a new issue because, I found no solution after read a lot of similar issues.

I have two project in a solution, 
- First : Asp net core project, my web app.
- Second : the Core library.

I stock the DbContext and migrations in the core library.

When I use the Package Manager Console to add a new migration (Add-Migration Test), I get this error : 

![picture1](https://user-images.githubusercontent.com/1653138/34734670-e270136c-f56c-11e7-9f15-db29c0a8cd72.PNG)

Here is my csproj for the web app : 

![picture2](https://user-images.githubusercontent.com/1653138/34735010-296bf4d8-f56e-11e7-9367-ae8b5b19e605.PNG)

Here is my csproj for the core library : 

![picture3](https://user-images.githubusercontent.com/1653138/34735054-4cce3008-f56e-11e7-94b8-ce8434948fef.PNG)

Here is my program and startup class 
 of my web app : 

```javascript
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.AddDbContextPool<DataBaseContext>(options =>
            {
                options.UseSqlServer(
                    Configuration.GetConnectionString("SoluComDatabaseDeveloppement"),
                    x => x.MigrationsAssembly("SoluCom.Core")
                );
            });

            services.AddIdentity<User, IdentityRole>(config =>
            {
                config.User.RequireUniqueEmail = true;
                config.Password.RequiredLength = 6;
                config.Password.RequireNonAlphanumeric = false;
                config.Password.RequireDigit = false;
                config.Password.RequireUppercase = false;
            })
            .AddEntityFrameworkStores<DataBaseContext>();

            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = "Login";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
                options.LoginPath = "/Compte/Connexion";
                options.LogoutPath = "/Compte/Deconnexion";
                options.SlidingExpiration = true;
                options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
            });

            services.AddScoped<DataBaseRepository>();

            services.AddTransient<DataBaseContextSeedData>();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, DataBaseContextSeedData seeder)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            
            app.UseStaticFiles();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=DashBoard}/{action=Index}/{id?}");
            });

            seeder.SeedAsync(env.IsDevelopment());
        }
    }
```
Please help me... I'm completly lost.

Thanks

**Comment by bricelam** [comment]
Does `-Verbose` give any additional information?

**Comment by bricelam** [comment]
Looks similar to #8163, but that should be fixed...

**Comment by Elite182** [comment]
I read this thread before, but I don't log anything yet...

Here is the result of Verbose : 
![picture](https://user-images.githubusercontent.com/1653138/34762667-d1d5c7e6-f5e8-11e7-80a1-4f8f47ec1117.PNG)

I saw something strange, before he call the exception, we can see a sort of namespace or path : 
"rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]"

Is there a mistake when it parse something with the substring ?

My projet contains those two project and two others still in NetCore 1.x, and the Add-Migration still work on those projects.

**Comment by Elite182** [comment]
Still the same error with 2.1.4 and 2.0.5 upgrade

**Comment by bricelam** [comment]
For some reason, it's using `Microsoft.EntityFrameworkCore.Tools` version 1.0.0. Check your `*.csproj` files and ensure the following is somewhere.

``` xml
<PackageReferecne Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
```
