### ISSUE TITLE
The property 'ValidationFailure.AttemptedValue' could not be mapped

### ISSUE THREAD

**Issue by lucassvasconcelos** [dotnet/efcore#10663]
I added fluentValidations in my domainLib to validate my entities, but I didn't used ValidationFailure.
In my Data classlib when I'm trying to add-migrations, the package manager console shows me the error below.

> The property 'ValidationFailure.AttemptedValue' could not be mapped, because it is of type 'object' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

I'm using Visual Studio 2017 Community - Version 15.5.2, 

I have a web application(netcoreapp2.0) project where I'm referencing my classlib.
In my classlib netstandard2.0 I'm using EF Core 2.0.

-----

I tried to ignore the validationsfailure in my context, but nothing changes.
`modelBuilder.Ignore<ValidationFailure>();`

**Comment by ralmsdeveloper** [comment]
Can you show us more information?

Your OnModelCreating and Your Class: **ValidationFailure**

This **AttemptedValue** property is probably of the **object** type.

**Comment by ajcvickers** [comment]
@lucassvasconcelos Documentation on excluding properties is here: https://docs.microsoft.com/en-us/ef/core/modeling/included-properties. I would suggest just using the `[NotMapped]` attribute on the properties that you don't want to map.
