### ISSUE TITLE
GetColumnSchema not supported

### ISSUE THREAD

**Issue by dominicrooijackers** [dotnet/efcore#10686]
Overnight out .NET core 1.1.0 application broke on our development server. 
The application still works fine while running it from visual studio 2015

The error that I'm getting is 
An unhandled exception occurred while processing the request.
NotSupportedException: Specified method is not supported.
System.Data.Common.DbDataReaderExtensions.GetColumnSchema(DbDataReader reader)

Stacktrace as follows:

> 

System.Data.Common.DbDataReaderExtensions.GetColumnSchema(DbDataReader reader)
EntityFrameworkExtras.EFCore.DatabaseExtensions.GetModelFromQuery<T>(DatabaseFacade databaseFacade, string sql, Object[] parameters) in DatabaseExtensions.cs
EntityFrameworkExtras.EFCore.DatabaseExtensions.ExecuteStoredProcedure<T>(DatabaseFacade database, object storedProcedure) in DatabaseExtensions.cs
DocumentPortal.Components.FolderViewComponent+<>c__DisplayClass3_0.<GetFolderContentAsync>b__0() in FolderViewComponent.cs
System.Threading.Tasks.Task.InnerInvoke()
System.Threading.Tasks.Task.Execute()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
DocumentPortal.Components.FolderViewComponent+<InvokeAsync>d__2.MoveNext() in FolderViewComponent.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker+<InvokeAsyncCore>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker+<InvokeAsync>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper+<InvokeCoreAsync>d__12.MoveNext()

> 

The following code is causing the error

```c#
IEnumerable<string> actualNames = dr.GetColumnSchema().Select(o => o.ColumnName);
```

### Further technical details
EF Core version: 1.1.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Server 2012R2
IDE: Visual Studio 2015

No application updates have been made anytime recently, so I strongly believe it has something to do with the server environment.

**Comment by ajcvickers** [comment]
@saurabh500 Do you know if anything has changed recently with regard to the GetColumnSchema method?

@dominicrooijackers This doesn't look like an EF Core issue--GetColumnSchema is not an EF method, and from the stack trace it looks like it is coming from EntityFrameworkExtras, so it might be worth following up with the author of that package.

If this does seem to be an actual EF issue, then can you please post a runnable project/solution or complete code listing that demonstrates the issue?

**Comment by dominicrooijackers** [comment]
GetColumnSchema comes from dbdatareaderextensions 
https://msdn.microsoft.com/en-us/library/system.data.common.dbdatareaderextensions.getcolumnschema(v=vs.110).aspx

I do target the full .net framework

**Comment by mrswain** [comment]
I was curious so I looked up the dotfx source and that call relies on the provided DbDataReader implementing IDbColumnSchemaGenerator (a 4.7.1 only interface) otherwise it throws the error you reported. You can use CanGetColumnSchema to check if it is supported first, but unless the underlying DB provider that you tell EF to use supports it, it will most likely not. If you are using the stock providers of EF they are not compiled against 4.7.1 and thus cannot support its features. You could grab the source, and rebuild against that framework version and it may work.

I don't think this would be a supported issue until those interfaces make it into a .NetStandard version and EFCore is updated to be dependent on that version.

**Comment by ajcvickers** [comment]
Moved to https://github.com/dotnet/corefx/issues/26302
