### ISSUE TITLE
Current preview builds...

### ISSUE THREAD

**Issue by Bitsonthefloor** [dotnet/efcore#10684]
I dont know if there is a problem with the preview publish, or of I am looking in the wrong location but I have been getting the previews from: dotnet.myget.org/F/aspnetcore-dev and I have noticed that the last three preview releases 28042, 28045, and 28051 all are based on the same commit (7ee6e3c). I have been looking forward to trying out the QueryTypes but they are missing form those previews. Pulling the artifacts from the AppVeyor build I can see more recent commits, and they are flagged as passed, so I am unsure as to why the releases on the aspnetcore-dev are behind, commit-wise.

Is there a better repository to pull from or should I just wait for the aspnetcore one to catch up?

**Comment by mrswain** [comment]
looks like it either has been resolved, or it resolved its self as build 28066 is a more recent commit.
