### ISSUE TITLE
Sqllite on android, migrate and scopes

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#10692]
In my xamarin android app I build a ServiceProvider on startup and register my DbContext in the normal way using `AddDbContext`.

After I have built the IServiceProvider, but before I show my first view, I resolve a scope factory, create a new scope, and `ApplyMigrations()`.

The scope is then disposed, and then I proceed to creating the first view.

The viewmodel is resolved using the IServiceProvider and an instance of my DbContext is injected.

When I add a bunch of entities to the DbContext that involve a foreign key, and then SaveChanges(), I get an exception from sqlite about a foreign key violation. I look at the entities and the foreign keys are correct. 

If I restart the application, when I get to the view this time, and the exact same entities are added and SaveChanges is called - it works.

It seems to be only happening after migrations are applied, usage of the dbcontext instance causes this FK violation error. 

Also, if instead of injecting a DbContext into the view model, I inject a service scope factory, and resolve a DbContext from that new scope, and then add all my entities to that and call SaveChanges() then it works.

So it seems like its something to do with the fact that I have a single application level IServiceProvider and that I register using AddDbContext and that I dont create new scopes prior to resolution, except one temporary scope to apply migrations in. After migrations have run, future instances of my dbcontext results in FK exception. 

Guidance for how to handle DI and migrations for EF in an xamarin app in the form of some sample or integration tests would be most welcomed.

Ive raised this issue because in asp.net core there is middleware to create a new scope such that you dont have to worry about doing it. When you move to Xamarin it is not obvious how to handle the combination of registration and scope creation in order for things to work smoothly. 

I am assuming should be creating a new scope after I run migrations, and use that as my application level IServiceProvider to resolve from, so process would be:

1. AddDbContext()
2. BuildServiceProvider()
3.Create scope and run migrations
4. Create scope and use as new top level IServiceProvider

Is that right? Or should I be registering my DbContext differently and not using scopes in an xamarin app? I.e singleton

Many thanks

### Further technical details
EF Core version: 2.0.1
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite
Operating system: Visual Studio 2017 15.5.x

**Comment by ajcvickers** [comment]
@dazinator There is nothing in inherently "wrong" with what you described above, although it does seem to indicate a long-lived context instance, which is usually not recommended. A couple of other points:
* There is no requirement that you have to use D.I. and AddDbContext with EF. The DbContext is designed to be newed up and disposed in the normal, non-D.I. way, just like previous versions of EF.
* If you do use AddDbContext, then it by default registers the context as scoped, which means that it should never be resolved when there is not a scope--this is why the web apps have to create a scope explicitly for seeding.

To investigate what is happening beyond that will probably require a runnable project/solution or code listing so we can reproduce what you are seeing.

**Comment by dazinator** [comment]
Thanks for the reply.
I'll ensure my app creates a scope before resolution and I think that should hopefully solve this problem.
I know DI isn't a requirement to new up a dbcontext (would be alarming if it was) but those following modern principles will often leverage it, so I think there is some value to having some examples or docs for some netstandard scenarios outside asp.netcore (i.e xamarin). I expect this will happen in the fullness of time :-)

**Comment by dazinator** [comment]
Closing this for now, as creating a scope for my application to use, after applying migrations, seems to have solved it.
