### ISSUE TITLE
DbContext.ChangeTracker keeps entities in cache in multithreading when using a new dbContext for each thread

### ISSUE THREAD

**Issue by DOMZE** [dotnet/efcore#10697]
Creating a new DbContext in a Task doesn't create a new clean DbContext.ChangeTracker collection.

When a task enters the using, and another task enters it afterwards, without having a synchronization lock object, the DbContext.SaveChanges() returns a SQLException:
Cannot insert explicit value for identity column in table 'Table' when IDENTITY_INSERT is set to OFF.

Upon adding a synchronization lock, everything completes as normal, however, the DbContext.ChangeTracker keeps growing.
I suspect the first error is caused by this

The (example) output is the ManagedThreadId-HashCode of the DbContext
As I can see, the object is recreated, but overtime, the ChangerTracker collection keeps growing

Note the example output in the Debug.Console which is as follows (with the lock):
3-38155029 - Code-487743670
3-38155029 - Inserting 8 items. Expected Entries count: 9. Entries count: 9
4-50492551 - Code-177571956
4-50492551 - Inserting 2 items. Expected Entries count: 3. Entries count: 3
5-4032828 - Code-1295758708
5-4032828 - Inserting 3 items. Expected Entries count: 4. Entries count: 12
4-57733168 - Code-1586458227
4-57733168 - Inserting 9 items. Expected Entries count: 10. Entries count: 12
3-15368213 - Code-1907659802
3-15368213 - Inserting 2 items. Expected Entries count: 3. Entries count: 14
5-51484875 - Code-199731684
5-51484875 - Inserting 6 items. Expected Entries count: 7. Entries count: 20
7-12549444 - Code-507882843
7-12549444 - Inserting 2 items. Expected Entries count: 3. Entries count: 14
8-22008501 - Code-551384981
8-22008501 - Inserting 5 items. Expected Entries count: 6. Entries count: 19

### Expected behavior
Each time a new DbContext is created all the states/caches are clean and everything starts fresh with no concurrency problems

### Steps to reproduce
see github repository : https://github.com/DOMZE/EFCoreBugTest

### Further technical details
EF Core version: 2.0.X (tried 2.0.0 & 2.0.1. Project is in 2.0.1)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.3

**Comment by ajcvickers** [comment]
@DOMZE Looks like ByProduct is called multiple times for the same underlying Store object. When `context.Attach(product.Store)` is called it will attach all the entities in the graph, which includes the Products that were previously attached. The numbers match when looking at only entries that are not in the Unchanged state. It looks like this is also the underlying cause of the threading issue, since it means the same graph of entities is being updated concurrently.
