### ISSUE TITLE
What is the correct path to upgrade migrations from Core 1.x to 2.x?

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#10704]
I'm currently looking at upgrading an EF Core 1.x project to 2.x, although none of the tutorials I've been able to find offer any guidance on what to do with my migrations.

What's the way forward here?

**Comment by ajcvickers** [comment]
@atrauzzi Migrations created with EF Core 1.x should work with 2.x. If you are seeing issues, then please post full details.

**Comment by atrauzzi** [comment]
What are my steps for bringing them over?

**Comment by ajcvickers** [comment]
@atrauzzi I'm not sure what you mean. When you update your app to use 2.x, the migrations should remain unchanged.

**Comment by atrauzzi** [comment]
Gotcha, kk. Thanks!
