### ISSUE TITLE
Oracle: Only one column per table can be configured as 'Identity'.

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10719]
AFAIK, this restriction shouldn't exist on Oracle...

**Comment by ajcvickers** [comment]
This is an issue identified on the Oracle sample provider. We don't plan to fix this in the sample, but we would be happy for a community contributor to fix it. Also, anyone taking the sample as a starting point for production code should consider fixing this issue.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
