### ISSUE TITLE
Question: Resolving DbContext by marker interface

### ISSUE THREAD

**Issue by AccessViolator** [dotnet/efcore#10710]
Say in ASP.Net application I register DbContext using `services.AddDbContext<MyContext>(...)` or `services.AddDbContextPool<MyContext>(...)` (with default scoped lifetime) and then also do `services.AddScoped<IMyContext, MyContext>()` where IMyContext can potentially be just an empty marker interface that MyContext "implements", to be able to inject the context using IMyContext instead of MyContext.

Will my scoped registration screw anything up with MyContext resolution/lifetime (especially in case of a pooled registration)?

Apologies if this is not an appropriate place to ask such a question.

**Comment by ajcvickers** [comment]
@AccessViolator That should work fine for AddDbContext. For AddDbContextPool, there are a couple of issues (#9741, #9433) that are fixed for the 2.1 release, but may cause issues with the current 2.0 release. If you do hit issues, you could consider testing on the nightly builds for 2.1 which are listed on the repo homepage: https://github.com/aspnet/EntityFrameworkCore
