### ISSUE TITLE
Oracle Migrations: Column is already NOT NULL

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10718]
When altering a non-nullable column, DDL like this is generated:

``` sql
ALTER TABLE "Entities" MODIFY "Int32Property" NUMBER(10) NOT NULL
```

Which results in the following error.

> ORA-01442: column to be modified to NOT NULL is already NOT NULL

**Comment by ralmsdeveloper** [comment]
@bricelam 
Could we use that?
```csharp
var isNullable = operation.IsNullable == operation.OldColumn.IsNullable
    ? true
    : operation.IsNullable;

ColumnDefinition(
    operation.Schema,
    operation.Table,
    operation.Name,
    operation.ClrType,
    operation.ColumnType,
    operation.IsUnicode,
    operation.MaxLength,
    operation.IsRowVersion,
    isNullable,
    /*defaultValue:*/ null,
    /*defaultValueSql:*/ null,
    operation.ComputedColumnSql,
    identity,
    operation,
    model,
    builder);
```
 -> [Here](https://github.com/ralmsdeveloper/EntityFrameworkCore/blob/2a6f16a82e80ea0f98a0af2c1cd90dd3380958a6/samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs#L230-L248)

As no change occurred then it would not arrive [here](https://github.com/ralmsdeveloper/EntityFrameworkCore/blob/2a6f16a82e80ea0f98a0af2c1cd90dd3380958a6/samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs#L780)

It's just a suggestion!

**Comment by ajcvickers** [comment]
This is an issue identified on the Oracle sample provider. We don't plan to fix this in the sample, but we would be happy for a community contributor to fix it. Also, anyone taking the sample as a starting point for production code should consider fixing this issue.

**Comment by bricelam** [comment]
@ralmsdeveloper I considered doing the same, but ultimately, I decided `AlterColumnOperation` probably needs its own, more robust code separate from `AddColumnOperation`

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
