### ISSUE TITLE
Undesired restrictions are applied to composite indexes involving nullable FKs

### ISSUE THREAD

**Issue by eduherminio** [dotnet/efcore#10722]
### Issue description

Undesired restrictions are applied to composite indexes/unique constraints when **nullable FKs** are involved.

Providing the following restriction and `FK_TO_Entity2` being a nullable FK to another entity:
```
            modelBuilder.Entity<Sample>()
                .HasIndex(entity => new { entity.field, entity.FK_TO_Entity2 })
                .IsUnique();
```

In SQLServer, the following index is created:
```sql
          CREATE UNIQUE NONCLUSTERED INDEX[IX_field_FK_TO_Entity2] ON[dbo].[Sample]
          (
            [field] ASC,
            [FK_TO_Entity2] ASC
          )
          WHERE([field] IS NOT NULL AND [FK_TO_Entity2] IS NOT NULL)
```

That uniqueness condition is intended to be applied even when `FK_TO_Entity2` is null, but the restriction doesn't allow that to happen.

PD: `field` is a required property of `Sample`, I haven't tested if the behavior is the same with not-required but not FK fields (which would mean that the issue is related to all nullable fields) or the only restriction applied would only be `WHERE([field] [FK_TO_Entity2] IS NOT NULL` (and therefore, the issue would only have to do with nullable FKs)

### Steps to reproduce
A full example can be found in [this repo](https://github.com/eduherminio/EFCore-Issue10722).
Expected behavior is fully explained there, with samples.

### Workaround
Since these undesired constraints are just filters, a workaround we found was to 'override' those filters, by adding a custom, meaningless filter.

Since, as mentioned, `field` is a required field, unexpected behavior is avoided by using:
```
            modelBuilder.Entity<Sample>()
                .HasIndex(entity=> new { entity.field, user.FK_TO_Entity2 })
                .IsUnique()
                .HasFilter("field is not null");
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (behaviour tested in Sqlite too)

**Comment by AndriySvyryd** [comment]
@eduherminio The ANSI SQL standard says that nulls should not violate the unique constraint and that's what most of other databases implement. To make it easier to move configuration from one database to SQL Server we have a convention to add the filter to make the default behavior match the standard. If that's not what you want you can override it as you did or by removing the filter completely: `.HasFilter(null);`
