### ISSUE TITLE
Getting previously cached entity rather than updated entity from database

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#10732]
I have a scenario where EF is not giving me the latest data from the database, but instead returning an instance that was added earlier.
It's acting like both processes are inside some sort of transaction, but there are no transactions involved at all.

Here's what I'm doing:

1. Create an instance of EntityOne.
2. Add EntityOne to the DbContext.
3. DbContext.SaveChanges
4. A different process makes changes to EntityOne and saves them to the database.
5. Create query to re-fetch EntityOne.
6. If you check the ChangeTracker, you can see the original values from 1 are the only tracked entity.
7. Execute the query
8. SQL profile shows that a SELECT occurred, and that the updated values from the second process in 4 are present.
9. EF returns EntityOne with the *OLD* values from step 1.
10. If you do a GetHash() on the entity from step 1 and the one returned from step 6 and the one returned from step 9, all the HashCodes are the same, meaning EF is returning an existing instance rather than creating a new instance from the new values in the DB.

Is this expected behavior?  I assume not.  If not, I'll see if I can get you some code to reproduce.

```
// PROCESS 1
var instance = new EntityOne();
dbContext.Add(instance);
dbContext.SaveChanges();

...

// PROCESS 2
Another process updates the row in the database that represents EntityOne.

...

// PROCESS 1
var oldInstance = dbContext.ChangeTracker.Entries<EntityOne>().Single().Entity;
var newInstance = await dbContext.EntityOnes.Where(...).SingleAsync();
// newInstance does NOT reflect the values that were updated in the other process
// oldInstance.GetHashCode() == newInstance.GetHashCode()
// If I execute the SQL I saw generated directly above from SQL profiler, I see the new values as expected.
```

**Comment by Tarig0** [comment]
Looks like what you want is
```c#
oldInstance.Reload()
```

**Comment by joshmouch** [comment]
Hmm... this does work as a hack... kind of... except that you have to hit the database twice and know that this query has already been done previously.

Is that expected behavior?  The old EF didn't act this way, and this seems like it could easily cause unexpected bugs.

**Comment by Tarig0** [comment]
Another option is, dbcontext.Entityones.find(oldInstance.id), this should pull the current tracked entity 

Looks like what's going on is the tracker is replacing the ref pointer

**Comment by ajcvickers** [comment]
@joshmouch All versions/flavors of EF have this behavior. That is, if a query would return an entity that has already been loaded, then no new entity is created and the loaded entity is returned instead. A no-tracking query will always return a new entity in this case, or consider what the most appropriate unit of work is for your application and scope the context appropriately--maybe transient in this case. if you expect multiple updates might cause conflicts, then consider using optimistic concurrency.
