### ISSUE TITLE
There is no support for conditional deletes

### ISSUE THREAD

**Issue by imoscan** [dotnet/efcore#10738]
I was expecting that EF Core has support for natural deletes, based on specific query conditions without retrieving the data.

Sample:
```c#
db.Persons.RemoveRange(i => i.Age > 30);
db.SaveChanges();
```

I think this is a functionality that EF Core should have. 
The current implementation is generating a SELECT request and multiple deletes in a second request, which can generate performance issues and forces non-EF implementations/T-SQL.

Sample:

```c#
var query = db.Permissions.Where(i => i.UserTypeId = 1);
db.RemoveRange(query);
db.SaveChanges();
```
Generated SQL:

```SQL Request 1
exec sp_executesql N'SELECT [i].[UserTypeId], [i].[PermissionName]
FROM [UserTypesPermissions] AS [i]
WHERE [i].[UserTypeId] = @__Command_UserTypeId_Value_0',N'@__Command_UserTypeId_Value_0 int',@__Command_UserTypeId_Value_0=2
```

```SQL Request 2
DELETE FROM [UserTypesPermissions]
WHERE [UserTypeId] = @p0 AND [PermissionName] = @p1;
SELECT @@ROWCOUNT;

DELETE FROM [UserTypesPermissions]
WHERE [UserTypeId] = @p2 AND [PermissionName] = @p3;
SELECT @@ROWCOUNT;

DELETE FROM [UserTypesPermissions]
WHERE [UserTypeId] = @p4 AND [PermissionName] = @p5;
SELECT @@ROWCOUNT;

DELETE FROM [UserTypesPermissions]
WHERE [UserTypeId] = @p6 AND [PermissionName] = @p7;
SELECT @@ROWCOUNT;

DELETE FROM [UserTypesPermissions]
WHERE [UserTypeId] = @p8 AND [PermissionName] = @p9;
SELECT @@ROWCOUNT;

DELETE FROM [UserTypesPermissions]
WHERE [UserTypeId] = @p10 AND [PermissionName] = @p11;
SELECT @@ROWCOUNT;

',N'@p0 int,@p1 nvarchar(150),@p2 int,@p3 nvarchar(150),@p4 int,@p5 nvarchar(150),@p6 int,@p7 nvarchar(150),@p8 int,@p9 nvarchar(150),@p10 int,@p11 nvarchar(150)',@p0=2,@p1=N'PERM1',@p2=2,@p3=N'PERM2',@p4=2,@p5=N'PERM3',@p6=2,@p7=N'PERM4',@p8=2,@p9=N'PERM5',@p10=2,@p11=N'PERM6'
```

**Comment by Psypher9** [comment]
I for one think this is a good point. Have you been able to test out any implementations?

**Comment by Psypher9** [comment]
After looking over the code for RemoveRange the summary documentation stated that internally it was designed to iterate over each entity in the IEnumerable<TEntity>, so perhaps there is a limitation when the commands are being generated. I've not tracked it down yet, but I'm pretty sure that's where the bottleneck you're talking about is coming from.

Have you tried calling your query directly within the RemoveRange call? Example: _db.RemoveRange(_db.Person.Where(x => x.Age > 30))

**Comment by tangdf** [comment]
Maybe this repository can help you:
[zzzprojects/EntityFramework-Plus](https://github.com/zzzprojects/EntityFramework-Plus#batch-delete)

**Comment by imoscan** [comment]
I currently implemented something custom to make it work and I really hope that in the future we will have predicate expressions support with the deletes inside EF Core, because this is a basic functionality and can solve a lot of practical issues.

Sample:
```SQL
DELETE FROM Table WHERE Name = 'test';
```
