### ISSUE TITLE
EFCore.Proxies should not be strongly coupled to Castle.Core

### ISSUE THREAD

**Issue by alexinea** [dotnet/efcore#10746]
It is very exciting that EFCore team add Lazyload feature into this project. But one question that why you guy use/must use Castle.Core here? Why not allow users to choose themselves?

This is another choice, [AspectCore](https://github.com/dotnetcore/AspectCore-Framework), an Aspect-Oriented Programming based cross platform framework for .NET Core and .NET Framework. It works more efficient and better performing than Castle.Core.

I heard that this afternoon (2018-01-23, 15:00 GMT+8), the young author, @liuhaoyang, has completed an extension for EFCore.Proxies, AspectCore-based, in 3 hours. 

**BUT...THIS METHOD...** https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs#L89 This code makes it impossible for users to choose their own decision. There should be a scalable interface here.

Thank you.
Thank you all EFcore team members.

**Comment by ElderJames** [comment]
I like AspectCore more. 👍

**Comment by djl394922860** [comment]
I like AspectCore more too. 👍

**Comment by xingwen1987** [comment]
I'm love to use AspectCore rather than Castle.Core. :+1:

**Comment by liuhaoyang** [comment]
@alexinea  but so far,castle still works more efficient than AspectCore.

**Comment by liuhaoyang** [comment]
@alexinea we can have other ways to implement lazy loading based on AspeectCore.

**Comment by alexinea** [comment]
As the saying goes, it takes a good blacksmith to make steel. I'll close this issue and just waiting for @liuhaoyang 's works.
