### ISSUE TITLE
Cannot find type Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames

### ISSUE THREAD

**Issue by azizkazdal** [dotnet/efcore#10759]
Hi,
We are developing a UWP applicayion which referense SQLite .net standart data acces layer. 
We are having an error when building the UWP applicatin which err or is below

**Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot find type Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames in 
module Microsoft.EntityFrameworkCore.Relational.dll.	Mess.Weighbridge**

On the data access .net standart library got reference EFCore.Sqlite , EFCore.Sqlite.Design and EFCOre.Tools  and UWP application is getting reference Data Acces layer, EFCore.Sqlite , EFCore.Sqlite.Design and EFCOre.Tools

removing all reference and clean solution, reopen vs and add relative references still same above error.
could not find any solution 
Urgent help needed.
Thank you

### Further technical details
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@azizkazdal RelationalFullAnnotationNames is an internal class that existing in older versions of EF Core, but not in 2.0 or later. You'll need to update any code that uses this to build against the public surface of EF Core 2.0.

**Comment by steffhimes** [comment]
I had to remove some nuget packages that referenced earlier .NET core

**Comment by allanrsmith** [comment]
Had to remove `Microsoft.EntityFrameworkCore.Design.Core 1.0.0-preview2-final`

**Comment by ChickenFeett** [comment]
I fixed this issue by removing any `Microsoft.EntityFrameworkCore.X` where the version was older than other `Microsoft.EntityFrameworkCore.X` references. 
In my particular case I removed `Microsoft.EntityFrameworkCore.Relational.Design` v1.1.6 where my other `EntityFrameworkCore` references were v2.2.1

**Comment by bluebaroncanada** [comment]
@allanrsmith You're my personal hero.
