### ISSUE TITLE
 generated value no update

### ISSUE THREAD

**Issue by JohnHe404** [dotnet/efcore#10769]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
 generated value no update
```

### Steps to reproduce

in Book class

>     public class Book : BaseEntity
>     {
>         public string Name { get; set; }
>         public string Text { get; set; }
>         public DateTime? CreatedOnUtc { get; set; }
>         [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
>         public DateTime? LastedOnUtc { get; set; }
>     }

in BookMap class

>     public class BookMap : BestEntityTypeConfiguration<Book>
>     {
>         public override void Configure(EntityTypeBuilder<Book> builder)
>         {
>             builder.ToTable("Book");
>             builder.HasKey(b => b.Id);
> 
>             //builder.Property(b => b.CreatedOnUtc).HasDefaultValueSql("GETDATE()").ValueGeneratedOnAdd();
>             builder.Property(b => b.CreatedOnUtc).HasDefaultValueSql("GETDATE()");
>             builder.Property(b => b.LastedOnUtc).HasDefaultValueSql("GETDATE()").ValueGeneratedOnAddOrUpdate();
>         }
>     }

in Update.cshtml

> public async Task<IActionResult> OnGetAsync(string id)
>         {
>             if (id == null)
>             {
>                 return NotFound();
>             }
> 
>             Book = await _bookService.GetBookById(id);
> 
>             if (Book == null)
>             {
>                 return NotFound();
>             }
>             return Page();
>         }
> 
>         public async Task<IActionResult> OnPostAsync()
>         {
>             if (!ModelState.IsValid)
>             {
>                 return Page();
>             }
> 
>             //_context.Attach(Book).State = EntityState.Modified;
> 
>             try
>             {
>                 await _bookService.UpdateBook(Book);
>             }
>             catch (DbUpdateConcurrencyException)
>             {
>                 if (!await BookExists(Book.Id))
>                 {
>                     return NotFound();
>                 }
>                 else
>                 {
>                     throw;
>                 }
>             }
> 
>             return RedirectToPage("./Books");
>         }

I want to generated value LastedOnUtc in each update book model.But failed.Can you help me?

### Further technical details
EF Core version: (2.0.1)
Database Provider: (Microsoft SQL Server local db)
Operating system: windows 10 1709
IDE: (e.g. Visual Studio 2017 15.5.4)

**Comment by ajcvickers** [comment]
@HeMinzhang Have you tried `HasComputedColumnSql`?

**Comment by ralmsdeveloper** [comment]
@ajcvickers 
This is also related in: #3955 #4501 #4180

@HeMinzhang 
This is an ugly solution, but if you really need it you can temporarily fix it with this:
```csharp
public override int SaveChanges()
{
    var changes = ChangeTracker
        .Entries<Book>()
        .Where(e =>
                e.State == EntityState.Added
                || e.State == EntityState.Modified);

    foreach (var item in changes)
    {
        item.Property(p => p.LastedOnUtc).CurrentValue = DateTime.Now;

        if (item.State == EntityState.Added)
        {
            item.Property(p => p.CreatedOnUtc).CurrentValue = DateTime.Now;
        }
    }

    return base.SaveChanges();
}
```

**Comment by HeMinzhang** [comment]
I want this api:

https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties

modelBuilder.Entity<Blog>()
    .Property(b => b.LastUpdated)
    .ValueGeneratedOnAddOrUpdate();

**Comment by ralmsdeveloper** [comment]
@HeMinzhang , Yes I know, I just informed you of a workaround.

I'm sure @ajcvickers, will give you a better answer, why does this seem to be really broken.

**Comment by HeMinzhang** [comment]
@ralmsdeveloper Very thanks.

**Comment by ajcvickers** [comment]
@HeMinzhang I don't think there is a way to set this up in the database without triggers and custom update logic. This is not something EF is going to implement in the near future. The best option for now is to either setup the database to do it outside of EF, or override SaveChanges as shown above.

**Comment by HeMinzhang** [comment]
@ajcvickers Thanks a million.

**Comment by ajcvickers** [comment]
Filed #10862 to track an enhancement that would make this easier.
