### ISSUE TITLE
Included properties' foreign keys are case sensitive

### ISSUE THREAD

**Issue by Bonelol** [dotnet/efcore#10761]
Some of tables are using varchar as PK/FK, and database is set to case-insensitive. Even though EF correctly generated SQL script, it took some entities out as PK/FKs not matched in C#.

Is there an simple way to let EF compare string keys in case-insensitive way?

Thanks,
Max

### Steps to reproduce
```c#
var ticket = _db.Ticket.Include(t=>t.User).First(t=>t.ID = 12345);
 Debug.Assert(ticket.User != null);
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.3

**Comment by Bonelol** [comment]
Currently I have to convert Username, which is PK of User, to lower case in OnModelCreating method

```c#
 entity.Property(e => e.Username)
                    .HasConversion(p => p, s => s.ToLower())
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .ValueGeneratedNever();
```

**Comment by ajcvickers** [comment]
@Bonelol This is being tracked by #673 and is something that we plan to look at in the future.
