### ISSUE TITLE
How to update an entity without retreiving it first?

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#10779]
I actually have two questions related to the code below

1.) Is it possible to update an entity without retrieving it first as shown?
2.) Why am I still getting the tracking exception even with the .NoTracking behavior selected?

The real problem I am trying to solve here is updating my entities.  I am inquiring about NoTracking because it seems obvious but the issue I need to resolve is updating.

My business case is that I get thousands of rows from a web API, almost all of which exist on my database.  I want to new up an entity (a Category in this code) and just update my database without first selecting the data from the table.

It seems to me I should be able to write `context.Update(entity)` and EF should update the table assuming a row with the same ID exists.  Perhaps I am over-simplifiying this?
```C#
	public void UpdateTest1()
	{

		try
		{
                    // create new DbContext
			Db db = DatabaseUtilities.ResolveContext<Db>(EndPoints.First(x => x.Name == ConnectionStringName));
			
			// get the same error with or without this:
			db.ChangeTracker.QueryTrackingBehavior = Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTracking;  

			
			Category c = new Category
			{
				ID = 1,         // already exists
				ParentID = null,
				Name = "Test",
				DataProviderID = 1,
				NativeID = 10
			};
			db.Categories.Update(c);
			db.SaveChanges();
		}
		catch (Exception ex)
		{
			string y = ex.Message;
			// The instance of entity type 'Category' cannot be tracked because another instance with the 
			// same key value for {'ID'} is already being tracked. When attaching existing entities, ensure 
			// that only one entity instance with a given key value is attached. 
			// Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
		}

	}
```

**Comment by SSkovboiSS** [comment]
Regarding first question: it is tracked here #795

**Comment by ajcvickers** [comment]
@sam-wheat The simple answer to your second question is that there is no query so the query tracking behavior has no impact. More specifically, the call to Update attaches (as in tracks) the entity in the modified state. The exception is thrown because the context is already tracking an entity with the same key.

**Comment by sam-wheat** [comment]
@SSkovboiSS 
The question is not entirely dependent on the issue you cited although it is a related issue.
The direct answer to my question is "Yes", but the entity being updated must not be tracked by the context.  [See here](https://github.com/aspnet/EntityFrameworkCore/issues/10823).
