### ISSUE TITLE
EF Core 2.0 in Ubuntu 17.10

### ISSUE THREAD

**Issue by shimanbb** [dotnet/efcore#10799]
Did everything according to the following link:
https://cmatskas.com/scaffolding-dbcontext-and-models-with-entityframework-core-2-0-and-the-cli/

Ran
`dotnet restore`
`dotnet ef`

Got
`The specified deps.json [/home/.../.nuget/packages/.../Microsoft.EntityFrameworkCore.Tools.DotNet.deps.json] does not exists.`

Added 
`<OutputPath>bin\Latest\</OutputPath>`

in the "PropertyGroup", still no change. How do I make it work?

**Comment by smitpatel** [comment]
Share your csproj file. The link you shared have some inaccuracies in how & what packages needs to be installed. Docs would provide more accurate way on configuring the project correctly for scaffolding https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

**Comment by shimanbb** [comment]
Hi Smit,

Did exactly as per the Docs, same result. Please find the .csproj file below. Its a webapi project created by `dotnet new ...`

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <!--OutputPath>bin\Latest\</OutputPath-->
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
</Project>
```

**Comment by shimanbb** [comment]
All good now. `sudo` fixed it.
