### ISSUE TITLE
Different result: Single To (FirstOrDefault / Find)

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#10793]
Is this broken?
Getting different results:
```csharp
var author = db.Autor.Single (p => p.Id == 1);
```
```sql
SELECT TOP(2) [a].[Id], [a].[Nome]
FROM [Autores] AS [a]
WHERE [a].[Id] = 1
```
To: (FirstOrDefault / Find)
```csharp
var author = db.Autores.FirstOrDefault (p => p.Id == 1);
```
```sql
SELECT TOP(1) [p].[Id], [p].[Nome]
FROM [Autores] AS [p]
WHERE [p].[Id] = 1
```

**EF Core:** 2.1.0-preview2-28189

**Comment by ajcvickers** [comment]
@ralmsdeveloper If you are asking why Single gets TOP(2) it's because the contract for Single is to throw if there is more than one result, so we need to know if there is more than one. First does not have this contract, which makes First slightly more efficient since there is less checking to do, which is in turn why it is used in Find.

**Comment by ralmsdeveloper** [comment]
@ajcvickers Thanks for responding!!
Just to know if I really understood, will we always have a TOP(2) when using the Single?

Could you help me understand this more?
In my head, I think if "Single" is only unique, it would not make much sense to return 2 records.

This causes an exception.

I really believe the team has a reason for it.
I'm just asking you, so I can know the reason.
So I could share this with friends who asked about it.

**Comment by ralmsdeveloper** [comment]
Looking at your response, this is forcing you to throw an exception if you have more than one record.
Basically, is that it?

**Comment by ajcvickers** [comment]
@ralmsdeveloper Yes. That's the difference between Single and First. If you know there is only ever one and don't need a runtime check for it, then use First.
