### ISSUE TITLE
Question: How to set up collection backing fields that aren't initialised?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#10800]
I am trying to use a DDD-approach to using EF Core, and I would like to leave a collection backing field as null. That would allow me to check if the caller has loaded the the collection before calling the aggregate update method in my entity class, i.e. I check that the collection backing field is non-null. (see code below for example of what I am trying to do).

# UPDATE
**This does work - I just got my code incorrect. I have updated the code below to show the code that works.** My mistake was not taking the readonly keyword off the fields. I also needed to make the fields of type `HashSet<T>`. 

### Corrected code
This contains snippets of code, all from the `Book` entity class.

```c#
public class Book
{
    public const int PromotionalTextLength = 200;

    private HashSet<Review> _reviews;
    private HashSet<BookAuthor> _authorsLink;

    public int BookId { get; private set; }          
    //... other properties left out

    public IEnumerable<Review> Reviews => _reviews?.ToList();            
    public IEnumerable<BookAuthor> AuthorsLink => _authorsLink?.ToList();

    //... other code left out

    public void AddReview(int numStars, string comment, string voterName)
    {
        if (_reviews == null)
            throw new NullReferenceException("You must use .Include(p => p.Reviews) before calling this method.");

        var review = new Review(numStars, comment, voterName);
        _reviews.Add(review); 
    }

    public void RemoveReview(Review review)                          
    {
        if (_reviews == null)
            throw new NullReferenceException("You must use .Include(p => p.Reviews) before calling this method.");

        _reviews.Remove(review); 
    }
```
The configuration of the backing fields are
```c#
public class BookConfig : IEntityTypeConfiguration<Book>
{
    public void Configure(EntityTypeBuilder<Book> entity)
    {
        //... other non-collection configuration parts left out.

        entity.HasMany(p => p.Reviews)  
            .WithOne()                     
            .HasForeignKey(p => p.BookId);

        entity.Metadata
            .FindNavigation(nameof(Book.Reviews))
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        entity.Metadata
            .FindNavigation(nameof(Book.AuthorsLink))
            .SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

### Further technical details
EF Core version: V2.0.1
Database Provider: all
Operating system: all
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@JonPSmith EF can't initialize `_reviews` because it is readonly. If it still fails when the field is writable, then this might be a bug.

**Comment by JonPSmith** [comment]
Thanks @ajcvickers. That's what I get for converting code and not looking. Sorry to have troubled you.

I did have to turn the fields to HashSets<T>, which is fine. It all works now and I have updated my question to show the correct code in case someone else wants this solution.

**Comment by pnguyen535** [comment]
I couldn't get this to work with EF 2.1.2, the FindNavigation always return null to me
.Metadata.FindNavigation(nameof(Dinner.Rsvps)); 

Is there something else that I need to look for? I have the similar setup in the Domain as your code.

Thank you

**Comment by ajcvickers** [comment]
@pnguyen535 Typically this happens when the navigation property has not been configured using `HasOne`, `WithOne`, etc.

**Comment by pnguyen535** [comment]
I figured it out. The backing fields for navigation need to the HashSet<>.

Thanks

**Comment by vanillajonathan** [comment]
Is `HashSet<T>` preferred over `List<T>`?
Is `Enumerable<T>` a good way to expose a read-only collection from EF and with DDD?
It seems like ideally `IReadOnlyCollection<T>` would be preferred over `Enumerable<T>` but the `AsReadOnly()` method is only available on List, not HashSet.

**Comment by JonPSmith** [comment]
Hi @vanillajonathan,

If you are going to leave the private field collection uninitialized, then they have to be a `HashSet<T>`. See my [StackOverflow Answer](https://stackoverflow.com/a/54842727/1434764) as to why I think an collection should be uninitialized.

The use of `Enumerable<T>` is recommended by @ajcvickers in the EF Team - see his [blog post on this](https://blog.oneunicorn.com/2016/10/28/collection-navigation-properties-and-fields-in-ef-core-1-1/), which has some nice ideas like using .ToList() to create a defensive copy.

**Comment by ajcvickers** [comment]
@JonPSmith It certainly should not be required the that backing field is a `HashSet`. Can you file a bug with a small, runnable project/solution or complete code listing that demonstrates this behavior.

**Comment by vanillajonathan** [comment]
It seems that a initialized `List` works, but a uninitialized `List` does not work, because then EF creates a `HashSet` which it attempts to cast into the existing `List`.

Works:
```cs
private HashSet<Book> _books;
```

Works:
```cs
private List<Book> _books = new List<Book>();
```

Crashes:
```cs
private List<Book> _books;
```
    System.InvalidCastException: Unable to cast object of type 
      'System.Collections.Generic.HashSet`1[Example.Book]' to type
      'System.Collections.Generic.List`1[Example.Book]'.

**Comment by JonPSmith** [comment]
Hi @vanillajonathan,

Yes, that is what I found when I wrote the book "Entity Framework Core in Action". Thank you for confirming that with the latest version.

@ajcvickers - does @vanillajonathan comment provide enough for you to look at? Personally I don't think its a problem but you seemed to think it should work.

**Comment by ajcvickers** [comment]
Thanks @JonPSmith and @vanillajonathan. I filed #15506 for this.
