### ISSUE TITLE
Migrations in separate project than DbContext - not successful

### ISSUE THREAD

**Issue by gitfortee** [dotnet/efcore#10806]
I am not successful in adding ef core migrations in a separate project. I have provided the project structure at the end.

The DbContext class and the migrations are in separate projects such that the former is a class library and the migrations project is a console application. I added a reference to the DbContext project in the migrations project however, I am getting errors while running migration commands

`\EF.BlogsDb.Migrations > dotnet ef migrations add InitialCreate --project EF.BlogsDb.Migrations.csproj`

No DbContext was found in assembly 'EF.BlogsDb.Migrations'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

I followed advise from this [link](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects) but I am not sure of the following.

In which project should i add these lines? is it the migrations project or my web project or the DbContext project?

```
options.UseSqlServer(
    connectionString,
    x => x.MigrationsAssembly("MyApp.Migrations")); 
```

Why should i Add a reference to the migrations assembly from the startup assembly?

From which location/folder/project should i run this command?

`dotnet ef migrations add NewMigration --project MyApp.Migrations` 

Thanks in advance for the clarifications one might provide!

Here is my project structure looks like: 

![image](https://user-images.githubusercontent.com/22137496/35533253-ede1c68e-050a-11e8-9dc4-e01fcc7d7147.png)

Here is the source code: 
[CodeCamper.zip](https://github.com/aspnet/EntityFrameworkCore/files/1675143/CodeCamper.zip)

**Comment by Tarig0** [comment]
For me I used a design time factory

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#from-a-design-time-factory

and also passed in the additional argument --startupproject

**Comment by bricelam** [comment]
See https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects

**Comment by bricelam** [comment]
To add to the responses from @Tarig0 

> Why should i Add a reference to the migrations assembly from the startup assembly?

We need to load the migrations assembly, so it needs to be loadable by the startup project (the project we emulate at design-time)

> From which location/folder/project should i run this command?

Any one with a `DotNetCliToolReference` to the Tools.DotNet package. Both the startup project and the target project default to the one in the current directory, so you'll have to override at least one using `--project` or `--startup-project`.

**Comment by gitfortee** [comment]
@Tarig0 @bricelam thanks for the quick response. 

While I try the suggestions.. how do I avoid hardcoding the connection string in the design time factory implementation? Is there a way to use the connection string from the appsettings config file?

**Comment by gitfortee** [comment]
@bricelam I found your example ([link here](https://github.com/bricelam/Sample-SplitMigrations)) match my exact need. However, the core sdk/runtime versions that I use are different than the ones used in your example project. 

I don't know if that matters at all but in order for my application to work, I had to also add the design time db context factory implementation as suggested by @Tarig0 ([link here](https://github.com/aspnet/EntityFrameworkCore/issues/10806#issuecomment-361405507)). I added it to the project in which I defined the DbContext class. Otherwise, I was getting this error: 

> Unable to create an object of type 'BlogContext'. Add an implementation of 'IDesignTimeDbContextFactory<BlogContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time. 

One more hint  - to specify the migrations assembly even in the design time db context factory implementation in the .UseSqlServer() method 

> .UseSqlServer(connectionString,  options=> options.MigrationsAssembly("Name.Of.Migrations.Assembly"))

**Comment by Tarig0** [comment]
If the startup project is the web project the DBcontext should have been retrieved from the services DI container. 

I did not specify the Migration assembly in my implementation, Though that may be because I forced the startup project to be the migrations project

**Comment by xrkolovos** [comment]
it doesn't work in me..
