### ISSUE TITLE
Support required

### ISSUE THREAD

**Issue by skamath76** [dotnet/efcore#10816]
We need to have a data base where a set of table will be created by Platform team and Extended tables will be created by Respective Team.

Ex: Say Table (Study  will be created by Platform Team and Extended Study Table will be created by Respective team)

Currently we will not be knowing what is the type of table respective team will have.So i will not be able to create DBSet<ExtendedStudy> in the DBContext.I want to use code first approach to create DB.It would be great if i have migrations also enabled.

Is it possible to have DbContext inheritense possible...Where Connection string will be supplied by respective team

Can you guys help me

**Comment by ajcvickers** [comment]
@skamath76 It is possible to have a DbContext that defines some functionality and then have a different team inherit from the DbContext and add additional entities to the model. However, it is not currently possible to have entity types added purely dynamically at runtime. Without more specific details of what you are doing it is hard to give a more specific answer than that.
