### ISSUE TITLE
Problem with dependency resolve of DbContenxOptions

### ISSUE THREAD

**Issue by msmolka** [dotnet/efcore#10817]
By default DbContext and DbContextOptions are registered with scoped lifetime. This is all working.
I'm working on simple EntityFrameworkLogger: https://github.com/msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore. I would like to make it work in as many scenarios as possible ASP NET Core 2 and `ILoggerBuilder`.

However I have strange issue related to DI when `DbContenxOptions` are registered with default scoped lifetime or when ValidateScopes is enabled.

```
System.AggregateException: An error occurred while writing to logger(s). ---> System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions' from root provider.
   w Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
   w Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   w Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   w Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   w Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   w Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   w ZNetCS.AspNetCore.Logging.EntityFrameworkCore.EntityFrameworkLogger`3.WriteMessage(String message, LogLevel logLevel, Int32 eventId)
   w ZNetCS.AspNetCore.Logging.EntityFrameworkCore.EntityFrameworkLogger`3.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   w Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

### Steps to reproduce

Working Example attached.
[WebApplicationEFError.zip](https://github.com/aspnet/EntityFrameworkCore/files/1676958/WebApplicationEFError.zip)

registration in Program.cs

```c#
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging(
                    (hostingContext, logging) =>
                    {
                        logging.AddEntityFramework<Context>();
                    })
                .Build();

```

definition in `Startup.cs` `CofigureServices`

```c#
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFrameworkInMemoryDatabase();

            // Add framework services.
            services.AddDbContext<Context>(options => options.UseInMemoryDatabase("Database"));

            services.AddMvc();
        }
```

### Further details
With above configuration logger failing with exception provided above.
However when I set `optionsLifetime` to singleton or disable `ValidateScopes` in `Program.cs` all is working correctly.

I'm trying to find the place what I'm doing wrong, and why dependency for scoped options cannot be resolved, when singleton can. DbContext is still scoped.

**Comment by ajcvickers** [comment]
It looks like this line:
https://github.com/msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore/blob/master/src/ZNetCS.AspNetCore.Logging.EntityFrameworkCore/EntityFrameworkLogger.cs#L255
creates a context instance without creating a D.I. scope first.

**Comment by msmolka** [comment]
Thanks, fixed and working in https://github.com/msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore/commit/d20ec10e94a242bf514705c00ec02a6717abb28e
