### ISSUE TITLE
Isolated Context reuses SQL Connection Causes Concurrency Issues

### ISSUE THREAD

**Issue by GrantHoffman** [dotnet/efcore#10820]
I'm trying understand how to create a context with two lifetimes, I'm running async code and I need to separate my contexts so they don't run on the same connection, Entity Framework However, seems to be reusing connections on separate contexts, which is causing this error:

> System.InvalidOperationException: 'A second operation started on this context before a previous operation completed. 

In my `StartUp` I register two contexts:

```C#
    string connection = @"Server=localhost;Database=Custom;Trusted_Connection=True;";

    services.AddEntityFrameworkSqlServer().AddDbContext<CustomContext>(
                    options => options.UseSqlServer(connection))
            // I've also tried without this, it's weird but it still maps
            .AddDbContext<IsolatedCustomContext>(
                    options => options.UseSqlServer(connection));

    services.AddTransient<DbContext, CustomContext>();
    services.AddTransient<IsolatedCustomContext>();
```
My isolated context is a the same as the custom context so I've declared like so:

```C#
    public class IsolatedCustomContext : CustomContext
    {
        public IsolatedCustomContext(DbContextOptions<CustomContext> options,
            DbAuthorizationOptions<CustomContext> authorizationOptions, 
            IMemoryCache memoryCache) : base(options, authorizationOptions, memoryCache)
        {
        }
    }
```
and my custom context is declared like so:

```C#
    public partial class CustomContext: DbContext
    {
        public CustomContext(DbContextOptions<CustomContext> options,
             DbAuthorizationOptions<CustomContext> authorizationOptions, IMemoryCache memoryCache) : base(options, authorizationOptions, memoryCache)
        {
        }
     
        public virtual DbSet<User> Users { get; set; }
    }
```
In my `Startup` I sync the user profile with my identity server like so:
```C#
    o.JwtBearerEvents = new JwtBearerEvents
    {
        OnTokenValidated = async tvc => { await AuthenticationRule.ValidateToken(tvc); }
    };
```
My authentication uses the isolated context to update user info:
```C# 
    // Using shouldn't be required but I've tried with it and without it
    using (var context = serviceProvider.GetRequiredService<IsolatedAstootContext>())
    {
        var userId = await context.Users
                                  .Where(u => u.UniqueIdentifier == subjectId)
                                  .Select(x => x.Id)
                                  .FirstOrDefaultAsync();
    }
```
Looks like the Pipeline Split's and runs concurrently after the token is validate to execute the request  I have a controller that looks like so:
```C#
    [Route("api/[controller]")]
    public UsersController : Controller
    {
         CustomContext _context;

         public UsersController(CustomContext context)
         {
              this._context = context;
         }
        
         [HttpGet]
         public User GetCurrentUser()
         {
             var userId = User.GetUserIdFromClaims();
             return this._context.Users.Where(x => x.Id == userId).FirstOrDefaultAsync();
         }
    }
```
When I call `GetCurrentUser`, I get the concurrency error,  I can see in the call stack it has not exited the isolated context using still. What's weird is they are two separate contexts.

**EDIT** 
is it possible that by inheriting context, Entityframework is Viewing this context as the same and some how reusing the connection?

Does anyone know how I can register these so they can operate parallel over different connections?

**Comment by ajcvickers** [comment]
@GrantHoffman Looks like the context is registered as scoped, but then this line obtains it from the service provider without first creating a scope:
```C#
serviceProvider.GetRequiredService<IsolatedAstootContext>()
```
Instead a scope must be created and then disposed when done:
```C#
using (var scope = serviceProvider.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<IsolatedAstootContext>();
}
```

**Comment by GrantHoffman** [comment]
@ajcvickers the issue was actually caused by the the DBOptions `DbContextOptions<CustomContext> options`,   since I was reusing the base class it caused to reuse the connection
