### ISSUE TITLE
2.1 preview1 feed?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#10835]
This feed https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json is now at 2.1 preview2 - where is the feed for 2.1 preview1 - I need it for provider testing?

**Comment by ralmsdeveloper** [comment]
@ErikEJ
https://dotnet.myget.org/F/aspnetcore-release/api/v3/index.json 
?

**Comment by ErikEJ** [comment]
Of course - Thanks!
