### ISSUE TITLE
Code First: Infer FK required-ness when introducing FKs by convention

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#1083]
Given:

```
modelBuilder
       .Entity<ExpenseLine>(e =>
       {
           e.ManyToOne(el => el.ExpenseCategory);
       });

public class ExpenseLine
    {
        public int Id { get; set; }
        public int ExpenseCategoryId { get; set; }
        public ExpenseCategory ExpenseCategory { get; set; }
    }

```

I expected the introduced FK to be required because the CLR property was non nullable.

**Comment by divega** [comment]
@smitpatel this is now assigned to you. Please talk to @AndriySvyryd about the details of what needs to be done.

**Comment by AndriySvyryd** [comment]
This was already fixed and verified by ForeignKeyPropertyDiscoveryConventionTest
