### ISSUE TITLE
Performance Issue When Upgrading from EFCore 1.x to EFCore 2.0 - Solved But Should Be Noted

### ISSUE THREAD

**Issue by BradCurry** [dotnet/efcore#10848]
I recently joined an organization as an Architect to help improve the way in which the company utilizes technology. The company had embarked on creating several "microservices" using .NET Core 1.x and EFCore 1.x. We are planning to move these services to Docker and K8's in the near future. I know there were performance improvements as well as a more complete API footprint in .NET Core 2.0 and had done this migration in the past at a previous company. So I decided to spend an afternoon and convert one of the current applications to .NET Core 2.0 and EFCore 2.0. This went pretty well so we decided to deploy the application into our non production environments and test. We did this without issue.

We then proceeded to move the application to production. Immediately, we started seeing CPU & Memory spikes of 98% to 100% CPU and almost 1GB of RAM. We obviously rolled this back and proceeded to question what had changed. Our code hadn't changed, I quite literally just upgraded the project references, Nuget references, and target framework references. I left the code completely as I had found it.

I searched through the release notes and found nothing that would warn me of this type of problem. I spent some time looking at the forums and known issues finding a few instances where people were experiencing performance issues but nothing seemed to match my exact problem.

To make a long story short, **I found 1 line of code that was causing the issue of crazy CPU & Memory spikes.** It seems like it was a design decision to make this change in EFCore 2.0 as this worked great in EFCore 1.x

The problem was we were using string.Equals() in the Where clause. I can see how we would have made this mistake as in all the years I've been programming. StringComparisons are the most efficient way to compare two strings.

This code executed in a performent manner in EFCore 1.x
```c#
            var agreementsQuery = await _context.AgentAgreements
                .Include(x => x.Contracts)
                .Where(a => 
                    string.Equals(a.CompanyCode, companyCode, StringComparison.IgnoreOrdinalCase)
                .ToListAsync();
```
But in EFCore 2.0, the above code actually pulls all the data back from the database and executes that Where clause on the client side. (i.e. application code side) A bit of sql profiling gave us the 411. Removing the StringComparison code did the trick.

EFCore 2.0 - Without the StringComparison
```c#
            var agreementsQuery = await _context.AgentAgreements
                .Include(x => x.Contracts)
                .Where(a => a.CompanyCode == companyCode)
                .ToListAsync();
```
Understandably, you've made some very clear and good choices about which part of the queries operate on the sql server (i.e. the provider) and which part of the queries operate on the application side.
https://docs.microsoft.com/en-us/ef/core/querying/client-eval

**I have two reasons for bringing this to your attention.** 
**First,** it's possible this is an oversight and you didn't realize you made this change. Unlikely.
**Secondly,** and more importantly, if others run into the same issue it would be great for them to find this early.

I'm wondering if this is not an oversight, can we put a notice of this in the migration notes that everyone bings or googles to figure out how to migrate from EFCore 1.x to EFCore 2.0?

### Further technical details
EF Core version: 2.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows Server 2012 R2 & SQL Server 2012 R2
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@BradCurry Question: when EF decides to evaluate something like this on the client it will write a warning out to the log. Did you see this warning? If not, it would be good to figure out why not.

**Comment by BradCurry** [comment]
I didn't actually look in the entity framework logs because I didn't know it did that until after I found the solution. I also haven't checked to see if the warning was written in the logs. That is something I could easily do and report back if you'd like.

**Comment by ajcvickers** [comment]
@BradCurry We discussed this in triage and to answer your questions:
* The change was made intentionally since in general we cannot translate the StringComparision semantics to SQL. This is complicated by the fact that, even without any specific comparison specified, there may be differences between the database string semantics and the C# string semantics. This general issue is tracked by #673. However, if you specifically specify a comparison, then we honor that by forcing client eval, which is why your application was impacted.
* The way we warn people about client evaluation in their queries is through the warning in the log. This can optionally be configured (on the DbContextOptionsBuilder) to generate an error (exception) instead of a warning. At this time we don't plan to add any other mechanism to warn about these things, but it is something that we are aware can cause problems so we are open to doing more in the future if it proves valuable.

**Comment by BradCurry** [comment]
@ajcvickers thanks for the follow up on this. I completely agree with the path you've chosen here. Had I known about the warning system built into the DbContextOptionsBuilder earlier, it would have made this a pretty trivial find.

Thanks again for the work you guys are doing here.
