### ISSUE TITLE
Ignore Properties Without Setter

### ISSUE THREAD

**Issue by rjperes** [dotnet/efcore#10844]
Shouldn't we automatically ignore properties without a setter? Note that I'm not talking about properties with private setters.
What happens is, if we have getter-only properties in our model - for example, for doing some calculation - EF still tries to map them.

**Comment by ajcvickers** [comment]
@rjperes Only properties with a getter and a setter are mapped by convention, except for collection navigation properties where a setter is not needed. If you are seeing otherwise, then please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by rjperes** [comment]
@ajcvickers : thanks. I have a project which seems to demonstrate this - I had to manually exclude these properties. But when I was creating a very sample project to demonstrate this, I couldn't reproduce it. So, until I have a working case, I'll close this issue. Thanks, again!
