### ISSUE TITLE
Conditional ForeignKeyIndexConvention

### ISSUE THREAD

**Issue by MykhayloKonopelskyy** [dotnet/efcore#10855]
EF Core has ForeignKeyIndexConvention.
It conventionally adds indexes for FKs.
I would like to add indexes conditionally, not for all FKs.
For example, I would like to mark particular foreign key (for example with custom annotation), and to marked FKs ForeignKeyIndexConvention will not be applied.

Can I use something like this:

1) Create my custom ForeignKeyIndexConvention, it can check whether FK is marked and applies or not applies ForeignKeyIndexConvention logic:

```C#
 public class CustomForeignKeyIndexConvention : ForeignKeyIndexConvention
    {
        public override InternalRelationshipBuilder Apply(InternalRelationshipBuilder relationshipBuilder)
        {
            var foreignKey = relationshipBuilder.Metadata;
            if (foreignKey.FindAnnotation("MyCustomAnnotationName") == null)
            {
                return base.Apply(relationshipBuilder);
            }

            return relationshipBuilder;
        }
....................................
```

2) Create CustomCoreConventionSetBuilder which uses CustomForeignKeyIndexConvention instead of ForeignKeyIndexConvention.

```C#
public class CustomCoreConventionSetBuilder : CoreConventionSetBuilder, ICoreConventionSetBuilder
    {
        public CustomCoreConventionSetBuilder(
            CoreConventionSetBuilderDependencies dependencies)
            : base(
                  dependencies)
        {    }

        public override ConventionSet CreateConventionSet()
        {
            ...............................

            var foreignKeyIndexConvention = new CustomForeignKeyIndexConvention();

           ......................................
            
```

3) Replace CoreConventionSetBuilder with my custom because I would like to use my custom ForeignKeyIndexConvention:
```C#
 builder.ReplaceService<ICoreConventionSetBuilder, CustomCoreConventionSetBuilder>();
```
Is it a right way?

**Comment by ajcvickers** [comment]
@MykhayloKonopelskyy We're curious as to why you don't want the indexes?

**Comment by MykhayloKonopelskyy** [comment]
@ajcvickers Because some of conventonally created indexes have zero seek, zero scan, zero lookup but about 100k updates. It is better to remove them.

**Comment by ajcvickers** [comment]
@MykhayloKonopelskyy I have been investigating this and unfortunately there isn't a good way to remove indexes in EF Core 2.0, mainly due to #7605, which in turn leads to #10874. It's not yet decided whether this can be improved for 2.1 or will have to wait until a later release. For now, there are a couple of workarounds. 

The first workaround is to delete the index from the generated migration. However, future migrations may still refer to the index, so any future migrations may need to be edited appropriately.

The second workaround is to process the indexes at the end of OnModelCreating by iterating over the indexes and removing or not as appropriate. However, the conventions must be disabled before doing this otherwise the indexes will be added back automatically. This can be done with a call to 'ConventionDispatcher.StartBatch', but this is internal code and so use at your own risk--it may be changed breaking your code in any EF release. If that's okay, then here's an example of how to do it:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // Disable conventions--warning: this uses internal code and may break on any EF release
    ((Model)modelBuilder.Model).ConventionDispatcher.StartBatch();

    foreach (var entityType in modelBuilder.Model.GetEntityTypes())
    {
        foreach (var index in entityType.GetIndexes().ToList())
        {
            // Logic to decide whether to remove the index here...
            entityType.RemoveIndex(index.Properties);
        }
    }
}
```

**Comment by jjxtra** [comment]
I have plenty of tables with foreign keys that will only ever be joined to the primary key of the other table, not the other way around. Right now I hand edit the migration file to remove the indexes. I think it's always better to do nothing unless the user specifies they want something, otherwise you run into this situation.

**Comment by gambled** [comment]
I find it frustrating to have to go in and manually remove Up and Down migration instructions on every migration created.  Like @MykhayloKonopelskyy  mentioned, I often deal with models where querying is mostly "up" the parent child chain is the business requirements and there is a cost of maintaining an index that offers zero benefit to queries or day-to-day operations.

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/214 will allow to remove and replace conventions

**Comment by Rookian** [comment]
@ajcvickers and @AndriySvyryd  Is there a new approach available for EF Core 3.1.6?

**Comment by ajcvickers** [comment]
@Rookian What are you looking for in terms of a "new approach"?

**Comment by Rookian** [comment]
> @Rookian What are you looking for in terms of a "better approach"?

@ajcvickers Is there an official stable approach to disable a foreign key convention for a specific entity? You wrote about workarounds, using EF Core implementation details that might change in future" and so on.

**Comment by ajcvickers** [comment]
FYI for anyone looking at this issue, see https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#example-dont-create-indexes-for-foreign-key-columns

**Comment by QianMoXi** [comment]
> FYI for anyone looking at this issue, see https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#example-dont-create-indexes-for-foreign-key-columns

This solution removes the convention for all entities, how can I only target specific entities?

**Comment by ajcvickers** [comment]
@QianMoXi The intention that after removing the convention you add explicit configuration for the indexes you do want. That being said, if you know how to identify in code which ones you want and don't want, then you could replace this convention with one that did that, but that would be significantly more work.

**Comment by fawzlx** [comment]
in ef core version 7/8 I do this in this way:
- like you create custom convention for foreign key:
`public class CustomForeignKeyIndexConvention : ForeignKeyIndexConvention
{
    public CustomForeignKeyIndexConvention(ProviderConventionSetBuilderDependencies dependencies) : base(dependencies)
    {
    }

    protected override IConventionIndex CreateIndex(IReadOnlyList<IConventionProperty> properties, bool unique, IConventionEntityTypeBuilder entityTypeBuilder)
    {
        return base.CreateIndex(properties.Where(x =>
            x.PropertyInfo?.GetCustomAttribute<IgnoreIndexAttribute>() is null).ToList().AsReadOnly(),
            unique, 
            entityTypeBuilder);
    }
}`
- create custom attribute for determining which properties that should not create index on it:
`public class IgnoreIndexAttribute : Attribute
{
}`
- replace old foreign key convention with new one:
`protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.Conventions.Replace<ForeignKeyIndexConvention>(serviceProvider =>
        new CustomForeignKeyIndexConvention(
            serviceProvider.GetRequiredService<ProviderConventionSetBuilderDependencies>()));
}`
