### ISSUE TITLE
How to call Stored Procedure with join on multiple tables in Entity Framework Core?

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#10867]
I have to call a stored procedure which is selecting records from multiple tables.

I have tried the following code, but it's returning null for columns from other tables than the entity class.

```
private async Task<IEnumerable<TEntity>> InvokeStoredProcedureAsync(string input = "")
{
    var storedProcedureName = "sp_BulkSelect";

    using (var db = new MyDbContext(_options))
    {
        var result = await db.Set<TEntity>().FromSql(storedProcedureName + " @inputIds", new SqlParameter("inputIds", input)).ToListAsync();
        return result;
    }
}

```
**Stored procedure:**

```
SELECT 
    [MainTable].[Id],
    [Table1Id],
    [Table2Id],
    [MainTable].[Table1Code],
    [Table2].[Table2Code]
FROM
    [MainTable] [MainTable]
LEFT JOIN 
    [Table1] [Table1] ON [MainTable].Table1Id = [Table1].[Id]
LEFT JOIN 
    [Table2] [Table2] ON [MainTable].[Table2Id] = [Table2].[Id];
```
**MainTable class:**

```
[Table("MainTable")]
public class MainTable : FullAuditedEntity
{

    [ForeignKey("Table1Id")]
    public virtual Table1 Table1 { get; set; }
    public virtual int Table1Id { get; set; }

    [ForeignKey("Table2Id")]
    public virtual Table2 Table2 { get; set; }
    public virtual int? Table2Id { get; set; }      

}
```
So when I call this stored procedure, Table1Code and Table2Code are missing in the return value.

I tried to add the following code in MainTable class, but its also not working.

```
[NotMapped]
public virtual string Table2Code { get; set; }

[NotMapped]
public virtual string Table1Code { get; set; }
```
Then I removed [NotMapped] from both the properties and added migration, in this case, its returning proper value. But It will add two columns in MainTable. It's really a BAD design.

So my question is how to select columns from multiple tables in the stored procedure in Entity Framework Core.

**I'm using EF Core 2.0.**

I think there has to be some way to call the stored procedure with using Entity and then map it to any class because select columns from multiple tables using join is a very basic requirement.

I tried the similar [solution](https://stackoverflow.com/questions/25391619/sqlquery-into-a-notmapped-field), but its giving compilation error.

'DatabaseFacade' does not contain a definition for 'SqlQuery' and no extension method 'SqlQuery' accepting a first argument of type 'DatabaseFacade' could be found (are you missing a using directive or an assembly reference?)

**Comment by ajcvickers** [comment]
@viveknuna This will require "query types" (see issue #1862) which will be included in EF Core 2.1. This will allow the final shape of the query result set (including columns from all tables) to be defined as a nominal type which can then act as the target for FromSql.

When not using FromSql, a LINQ query can be written to join multiple entity types mapped to different tables in the normal way, potentially using a projection to combine the results into a single type.
