### ISSUE TITLE
Query: correlated collections optimization doesn't work if the outer query itself is correlated using outer parameter

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#10877]
see: GearsOfWarQueryTestBase -> Correlated_collections_nested_mixed_streaming_with_buffer1

the problem is interaction between CorrelateSubquery and InjectParameters, we should look for ways to make them work with each other.

**Comment by maumar** [comment]
note: if/when this is addressed, consider optimization for https://github.com/aspnet/EntityFrameworkCore/issues/10813 that @smitpatel mentions in the comment

**Comment by ajcvickers** [comment]
Note: optimization may not work with weak types.
