### ISSUE TITLE
generate Migrations error,not find SqlServerValueGenerationStrategy

### ISSUE THREAD

**Issue by JohnHe404** [dotnet/efcore#10873]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

not find SqlServerValueGenerationStrategy
```
Exception message:

>     [DbContext(typeof(ApplicationDbContext))]
>     [Migration("20180205145931_IdentitySchema")]
>     partial class IdentitySchema
>     {
>         protected override void BuildTargetModel(ModelBuilder modelBuilder)
>         {
> #pragma warning disable 612, 618
>             modelBuilder
>                 .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
>                 .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);//error

```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

My asp.net solution have four projects: 

> Zop.Web,  Zop.Core,  Zop.Data, Zop.Service

Zop.Web used Assembly: 

> Microsoft.EntityFrameworkCore.SqlServer

Zop.Data don't used.

I use Migration command(generate Migrations):

> Add-Migration IdentitySchema -c ApplicationDbContext -p Zop.Data

Zop.Data make a error not find SqlServerValueGenerationStrategy.The error cause is Zop.Data no used Assembly: Microsoft.EntityFrameworkCore.SqlServer.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1709
IDE: Visual Studio 2017 15.5.2

**Comment by ajcvickers** [comment]
@HeMinzhang That assembly will need a reference to all the EF Core assemblies being used, including the provider assembly. It looks like you are referencing most, but not the provider assembly. Is there a reason for this?

**Comment by HeMinzhang** [comment]
@ajcvickers yes.

**Comment by ajcvickers** [comment]
@HeMinzhang Will you share the reason?

**Comment by HeMinzhang** [comment]
I sort it because I'm poor at English,So sorry.

**Comment by HeMinzhang** [comment]
My solution: 
Zop.Data is a class library no reference assembly Microsoft.EntityFrameworkCore.SqlServer.
Zop.Web is web app  reference assembly Microsoft.EntityFrameworkCore.SqlServer and Zop.Data.

I use Migration command(generate Migrations):

> Add-Migration IdentitySchema -c ApplicationDbContext -p Zop.Data

Migration file generated by zop.data produces an error.
The reason for the error is because there is no Microsoft.EntityFrameworkCore.SqlServer.

**Comment by ajcvickers** [comment]
@HeMinzhang The short answer is that migrations are provider-specific and may use code from the provider assembly, which means whichever assembly contains the migrations must have a reference to the provider assembly.

**Comment by HeMinzhang** [comment]
@ajcvickers Thanks a million.
