### ISSUE TITLE
Add Code First API for creating non-primary keys

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#1087]
Otherwise it's not possible to add annotations to them without dropping down to metadata API.

**Comment by bricelam** [comment]
Because of this, the model snapshot will lose any alternate keys that are not the target of a foreign key. Also any annotations on alternate keys will be lost.
/cc @smitpatel

**Comment by rowanmiller** [comment]
Dupe of https://github.com/aspnet/EntityFramework/issues/2164
