### ISSUE TITLE
AspnetCore 2.0 dbcontext parameterless constructor

### ISSUE THREAD

**Issue by kessysam** [dotnet/efcore#10889]
Hi Everyone, Just wana to ask if the parameterless constructor in entityframework can be used to initialise a dbcontext.

If it can, how can i configure the connection string?

**Comment by ajcvickers** [comment]
@kessysam Yes, and the connection string can be set in OnConfiguring. See https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings
