### ISSUE TITLE
Remove a entity by Primary Keys

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#10893]
When need remove a entity from database first we must find it later remove it. why can not remove a entity when have primary keys and required for entities. please add remove overloading that can remove a entity by primary keys.

**Comment by ajcvickers** [comment]
Duplicate of #795

**Comment by mojtabakaviani** [comment]
Duplicate means many developers need it.

**Comment by Davilink** [comment]
Technically you can just create and empty entity with the primary key field setted, attach it to the context and finally removing it.

```
var entity = new Entity
{
  Id = "my-id"
};
context.MyDbSet.Attach(entity);

context.MyDbSet.Remove(entity);
context.SaveChanges();
```
