### ISSUE TITLE
Migrations: Error while setting foreignkey with IdentityUser

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#1090]
In ASP.NET 5 starter web app,
I have "Blog" Entity. Each blog has 1 creator (type ApplicationUser) and each user can have multiple blogs created by them.
Entity Classes are as follows:

``` C#
public class ApplicationUser : IdentityUser
    {
        public virtual ICollection<Blog> Blogs { get; set; }
    }
public class Blog
    {
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }

        public string CreatorId { get; set; }

        public virtual ApplicationUser Creator { get; set; }
    }
```

I have created ManyToOne relationship with following command

``` C#
builder.Entity<Blog>().ManyToOne<ApplicationUser>(b => b.Creator, au => au.Blogs).ForeignKey(b => b.CreatorId);
```

Following is the output when I add migration and apply it.

```
PM> k ef migration add foreignkey
Using context 'ApplicationDbContext'.
PM> k ef migration apply
Using context 'ApplicationDbContext'.
k : System.InvalidOperationException: A relational store has been configured without specifying either the DbConnection or connection string to use.
At line:1 char:1
+ k ef migration apply
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.InvalidO... string to use.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   at Microsoft.Data.Entity.Relational.RelationalConnection..ctor(DbContextConfiguration configuration, Connec
tionStringResolver connectionStringResolver)
   at Microsoft.Data.Entity.SqlServer.SqlServerConnection..ctor(DbContextConfiguration configuration, ConnectionStringResolver connectionStringResolver)

PM> 
```

The error message shown seems irrelevant since the web app itself configures everything (and it runs correctly too).
Moreover I tried adding Blog & Post entity and relationship between them which works.
For me the error is appearing only when I try to create foreignkey relationship with IdentityUser Class.

VS 2015 Preview - 14.0.22303.1 DP
EF - 7.0.0-beta1

**Comment by bricelam** [comment]
Everything seems to be working now apart from the temporary workaround to apply EF Migrations in the ApplicationDbContext constructor which prevents the Migrations commands from working correctly.

**Comment by divega** [comment]
@bricelam do you know if we have a bug on the templates to make sure we don't forget getting rid of the workaround?

**Comment by rowanmiller** [comment]
Not sure if there is an issue tracking it... but discussed with @rustd the other day and got agreement that it is definitely going away for the next release :tada: :cake:

**Comment by rowanmiller** [comment]
Template work is tracked by https://github.com/aspnet/Templates/issues/20

**Comment by mkarlsson** [comment]
@rowanmiller I get a 404 with your link,..

**Comment by rowanmiller** [comment]
@mkarlsson - it's an internal repo we use for tracking some issues... I removed the link
