### ISSUE TITLE
[question]When attach a disconnected entity to db context and set the state to Deleted or Modified, what the OriginalValues is?

### ISSUE THREAD

**Issue by xyting** [dotnet/efcore#10903]
When attach a disconnected entity to db context and set the state to Deleted or Modified, what the OriginalValues is?

I have an [issues](https://github.com/Arch/AutoHistory/issues/19) about this.

**Comment by ajcvickers** [comment]
@xyting If the code that attaches the entity knows the original values, then they should be set when the entity is attached. Otherwise the original values are assumed to be the same as the current values.
