### ISSUE TITLE
'Contain(null)' Exception in In Memory mode When using UnitTest

### ISSUE THREAD

**Issue by jingliancui** [dotnet/efcore#10906]
Hi,
I use the asp.net core 2.0 with efcore 2.0,sql server2008 r2.
Doing a business logic that search a "User Name" value.
Then do this :
```
System.Linq.Expressions.Expression<Func<Account, bool>> searchExpression;
                if (string.IsNullOrEmpty(searchValue))
                {
                    searchExpression = d => d.UserName.Contains(searchValue) == false;

                }
                else
                {
                    searchExpression = d => d.UserName.Contains(searchValue) == true;
                }
```
When "searchValue" is null .  (searchValue is a string type.)

Linq to sql is no exception throw and the expect result is showed,but Unit Test throw exception.

**Comment by ajcvickers** [comment]
@jingliancui It's not valid to pass null to String.Contains--see the docs here: https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=netframework-4.7.1#System_String_Contains_System_String_

So if this is evaluated in-memory, then there will be an exception. On the other hand, when this is translated to SQL the translation doesn't have the null limitation and so no exception is thrown in that case.
