### ISSUE TITLE
Consider adding ConfigureAwait(false)

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#10915]
After our discussion, it seems that the omission of `ConfigureAwait(false)` doesn't actually prevent all race conditions which could be produced in a UI application. In other words, if a user clicks twice on a button, then two `SaveChangeAsync()` invocations could be attempted at the same time, resulting in an exception. The only way around this would be for the user to make sure their application doesn't call EF APIs while another call is still in progress (i.e. by graying out buttons before starting the first request).

If `ConfigureAwait(false)` is added, then it's still an open question whether user callbacks should be executed in the user's synchronization context or in the thread pool (e.g. setting properties while materializing entities).

There's a good possibility this would be a breaking change - to be evaluated.

Related to #10914.

**Comment by ajcvickers** [comment]
We want to reconsider this and talk to people to understand better whether we should do it before...

**Comment by huysentruitw** [comment]
The lack of `ConfigureAwait(false)` in EF core totally breaks the graphql-dotnet dataloader way of working (currently, the only way to make it work is to call the EF Core sync methods). Any reason for closing this?
