### ISSUE TITLE
How to generate a migration with source of stored procedure?

### ISSUE THREAD

**Issue by vladanstrigo** [dotnet/efcore#10927]
Hi,

I want to make a tooling addition or in any way make a migration automate the versioning of stored procedures.

My goal is to do something like (pseudo code ahead):  add-migration --proc:xyz ....and have it pick up existing xyz from db, put it in Up() and Down() method as in Sql("alter...")...so when I change the Up() part , execute update-database I have old and new.

Is there a way to achieve this without writing a whole new toolset?

Is there an extension anywhere in the EF toolset for dotnet and sqclient to be able to make this?

Thnx!

Vladan Strigo

**Comment by bricelam** [comment]
Does this doc page help? [Custom EF Core Migrations Operations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations)
