### ISSUE TITLE
No response at all from Add-Migration (even with verbose)

### ISSUE THREAD

**Issue by filenda** [dotnet/efcore#10926]
Situation:

After a supposed corruption on my W10 notebook, I had to restore the system to a previous point. All my softwares were missing (including VS 2K17, SQL SERVER, Office etc). All my project files were untouched though.

After reinstalling them all I tried executing the following command:

Add-Migration 20180209 -verbose

Just to get back this:

More than one startup project found.
Using project '3 - Infrastructure\Any.Gym.Infrastructure.Context'.
Using startup project '3 - Infrastructure\Any.Gym.Infrastructure.Context'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\FILENGA\Source\repos\Any.Gym\Any.Gym.Infrastructure.Context\bin\Debug\netcoreapp2.0\Any.Gym.Infrastructure.Context.deps.json --additionalprobingpath C:\Users\FILENGA\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --fx-version 2.0 "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools\2.0.1\tools\netcoreapp2.0\ef.dll" migrations add 20180209 --json --verbose --no-color --prefix-output --assembly C:\Users\FILENGA\Source\repos\Any.Gym\Any.Gym.Infrastructure.Context\bin\Debug\netcoreapp2.0\Any.Gym.Infrastructure.Context.dll --startup-assembly C:\Users\FILENGA\Source\repos\Any.Gym\Any.Gym.Infrastructure.Context\bin\Debug\netcoreapp2.0\Any.Gym.Infrastructure.Context.dll --project-dir C:\Users\FILENGA\Source\repos\Any.Gym\Any.Gym.Infrastructure.Context\ --root-namespace Any.Gym.Infrastructure.Context

Any idea? I've already deleted bin an obj folders along the project and re-executed just to get back the same response

EDIT: Already deleted "MIGRATION" folder too. No success.

**Comment by vfilenga** [comment]
@bricelam Nailed it.
