### ISSUE TITLE
Move scaffolding tests to specification tests?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#10936]
SqlServerDatabaseModelFactoryTest is completely SQL Server-specific. If other providers copy this code to test their own scaffolding, it's impossible for them to know that a test was added.

This is more difficult, because unlike most tests these must contain provider-specific SQL to create and drop the database entities. You could have two methods on the base class: the test itself, which throws a NotImplementedException, and alongside it a method which accepts a model and performs the assertions. This would force the provider to override the test and to either skip it or implement it, calling the assertion method in the process.

Or maybe this is too much and there isn't enough value, not sure.

**Comment by bricelam** [comment]
I've wondered about this too. I don't think there's much value. `DatabaseModel` won't evolve much. It also feels silly and backwards to force you to provide DDL that matches the assertions--do you really want to use `dbo` as the schema name? 😉

**Comment by roji** [comment]
Yeah, I guess... it would be possible to work around the `dbo` issue (e.g. by allowing the fixture to provide the default schema or something), but it's true this gets more convoluted than the usual specification tests... I guess we can drop it.
