### ISSUE TITLE
EF Core 2.0 migrations ignore enviromnet

### ISSUE THREAD

**Issue by benrhere** [dotnet/efcore#10943]
ASP.NET Core 2.0.1 project includes:

appsettings.json
appsettings.development.json

I run:
PS C:\Users\ben> $Env:ASPNETCORE_ENVIRONMENT = "Development"

but when I then do
PS C:\Users\ben\Documents\GitHub\...\> dotnet ef database update

I hit the database whose connection string is specified in appsettings.json, not appsettings.development.json. I'm specifying config in the project like:

		public static IWebHost BuildWebHost(string[] args) =>
			WebHost.CreateDefaultBuilder(args)
				.UseStartup<Startup>()
				.Build();
	}
}

### Further technical details
EF Core version: 2.0.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.5.5)

**Comment by ajcvickers** [comment]
@benrhere Can you please post a runnable project/solution or full code listing that reproduces the issue?

**Comment by benrhere** [comment]
Hi Arthur, my apologies, this was user error. Your request for a repro showed me that this was not happening in the default template. When narrowing down the differences between a fresh project and mine, I eventually discovered that I had originally implemented IDesignTimeDbContextFactory, in which I had specified the production json config. Apologies for your trouble.
