### ISSUE TITLE
EntityFrameworkCore requires sysadmin privileges for dotnet ef scaffold

### ISSUE THREAD

**Issue by ststeiger** [dotnet/efcore#10948]
I tried using EntityFramework for schema generation today. 
Here are my complaints:
It's not possible to use dotnet ef with a .NET Core 2.0 project when having no administrative rights. 

First, install via nuget fails. 
Second, after painstakingly googling the problems, and a massive 1 hour manually fixing spree, it works on Windows 
Third, after further fixes, and more time wasted, it also works on Linux. 
Fourth, after pulling the fixed version for Linux from git on windows, it wants me to install .NET Framework SDK 2.0.3 on Windows.
But I have no administrative rights, so I cannot do that. 
==> Epic fail

Failure:
```
D:\username\Documents\Visual Studio 2017\Projects\BlueMine\BlueMine>dotnet ef dbcontext scaffold "Server=localhost\SQLEXPRESS;Database=Some_Existing_DB;Integrated Security=true;" Microsoft.EntityFrameworkCore.SqlServer --data-annotations -o Basigg
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.3' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.3'.
```

### Steps to reproduce
Adding entity framwork nugets to default .NET Core 2.0 project from VS 2017 V15.3.3 template. 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Db\" />
    <Folder Include="Views\Project\DisplayTemplates\" />
    <Folder Include="Views\Project\EditorTemplates\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
  <Import Project="..\Dapper\Dapper.projitems" Label="Shared" />
</Project>
```

### Further technical details
Problem is that it requires
`
    <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>
`

for the dotnet ef command. 
This is wrong. 
In addition, the following nonsense:

I use DB-first, and it has the following problems:
dotnet ef dbcontext scaffold "Server=localhost\SQLEXPRESS;Database=some_db;Integrated Security=true;" Microsoft.EntityFrameworkCore.SqlServer --data-annotations -o UtterCrap 

- All table and field names generated have '_' (underscore) removed. 
- Strings do not differentiate between varchar and nvarchar
- It says without option --data-annotations, it creates "fluent mappings", but it actually generates no mappings at all (is that called fluent nowadays?)
- If a table doesn't have a primary-key, it is omitted ? WTF ? Tables without PK are still required tables. You never need a table for data imports ? 
- No unique constraints
- no unique filtered index (where fieldname is not null, because MS-unique-constrains suck on multiple null values)
- database generated attributes missing on computed columns
- computation missing on computed columns (schema create anyone?). Meaning it doesn't even work from sql-server to sql-server - different db-enginge nonwithstanding.

### My conclusions from 2+ hours of using it
- no single source tutorial (including [docs.microsoft.com](https://docs.microsoft.com/en-us/ef/core/)) leads to a WORKING entity-framework-core project )
- EF doesn't work by default. 
- it doesn't even generate correct schemas for MS-SQL-Server
- it requires administrative rights (WTF ? utter nonsense - why should it ? ef .exe is a standalone tool - why can't you just bin-deploy it with framework ? )
- EntityFramework Core with DataBase first has to be a joke
- If I run scaffold from nuget/whatever-console, nothing happens. No error. No output. No nothing.  Just a black hole that swallows characters. 
- I can't see how this is supposed to work when I make changes to an existing db schema, db-first.
- i don't want to work code-first
- EF Core is a grabasstic pile of amphibian shit in general

**Comment by bricelam** [comment]
The first issue you're hitting is #10298.

Replace `<RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>` with `<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>`.

After doing this, you shouldn't need to install anything (or be admin). This is a super painful bug that is causing a lot of grief. It will be fixed in 2.0.2. This is also the reason `Scaffold-DbContext` fails silently.

---

To prevent the .NET-ification of class and property names, add `--use-database-names`.

The fluent API mappings are generated inside your DbContext's OnModelCreating method.

Currently, EF Core requires a primary key to perform identity resolution of domain object instances. #5719 will enable mapping to tables without a primary key.

Unique constraints are mapped via the `.HasAlternateKey()` fluent API.

Unique indexes create by EF Core do have a filter for `NOT NULL` on nullable columns because uniqueness of `NULL` on SQL server does suck.

Computed columns should be mapped appropriately using the fluent API.

#831 will help streamline the database-first workflow. The workflow today is to re-run `dotnet ef dbcontext scaffold`.

**Comment by ststeiger** [comment]
Hmmm, doesn't compile when I remove RuntimeFrameworkVersion while adding GenerateRuntimeConfigurationFiles...
As I said, no SDK > 2.0.0 installed. 

Thanks for `--use-database-names` though, much better already. 

Hmmm, now generates fluent mappings. 
Fluent seems to be a lot better than the data-annotation - data-annotation work in progress ?  
I see ForeignKeys and indices, that is an encouraging sign. 

Might have been that I specified -c, as in the [JetBrains tutorial  here](https://blog.jetbrains.com/dotnet/2017/08/09/running-entity-framework-core-commands-rider/).
Is it possible that -c only creates an empty context file ? 
e.g.
`dotnet ef dbcontext scaffold "Server=(localdb)\MSSQLLocalDB;Integrated Security=true;" Microsoft.EntityFrameworkCore.SqlServer -c AcmeDataContext`

Here's the output from `dotnet ef scaffold [...]` with `<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>.`

nice unicorn, by the way ;)

[![Command line][2]][2]
<br /><br /><br />
[![Visual Studio Message][1]][1]
<br /><br /><br />

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <!--
    <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>
    -->
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Db\" />
    <Folder Include="Views\Project\DisplayTemplates\" />
    <Folder Include="Views\Project\EditorTemplates\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SQL\various.sql" />
    <EmbeddedResource Include="SQL\classes.sql" />
    <EmbeddedResource Include="SQL\projects.sql" />
  </ItemGroup>
  <Import Project="..\Dapper\Dapper.projitems" Label="Shared" />
</Project>
```



  [1]: https://i.stack.imgur.com/ZJNCI.png
  [2]: https://i.stack.imgur.com/yQqkK.png

**Comment by ststeiger** [comment]
Pfff, never mind, works with the new options. 
Additionally needed to run dotnet -restore...

**Comment by bricelam** [comment]
This line shouldn't be there:

``` xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
```

That package should only be listed as a `<DotNetCliToolReference>`. I believe this is what's causing the **NU1605** error.

@ErikEJ provides a much friendlier reverse engineer experience in his [EF Core Power Tools](https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools).

**Comment by bricelam** [comment]
> Fluent seems to be a lot better than the data-annotation - data-annotation work in progress?

The data annotations have always supported less than the Fluent API. Issue #10864 is about bridging the gap.

**Comment by ststeiger** [comment]
I see what you mean. 
Yep, when I tried adding Microsoft.EntityFrameworkCore.Tools.DotNet via nuget and it didn't wok, I tried via the console, and hoped it would work. It was added, but I see now that the fact that this was possible is more bug then feature. 
Removed the entry. 

Here's a nice more real-life example of what it doesn't map:
Redmine mapping table changesets_issues, which is composed of a foreign key to changeset_id, and a foreign key to issue. 

Redmine never sets a foreign key. 
But instead of making this a composite primary key, they made this a composite unique index.
Peculiar construct - looks like one issue can have multiple changesets or vice-versa...

```
CREATE TABLE [dbo].[changesets_issues]
(
	[changeset_id] [int] NOT NULL,
	[issue_id] [int] NOT NULL
);
GO


CREATE UNIQUE NONCLUSTERED INDEX [changesets_issues_ids] 
    ON [dbo].[changesets_issues]
(
	[changeset_id] ASC,
	[issue_id] ASC
);

```

**Comment by bricelam** [comment]
Great feedback. I added a note to #5719 about falling back to unique constraints/indexes when no primary key is present.

**Comment by bricelam** [comment]
NuGet/Home#4190 is about fixing the terrible experience around `DotNetCliTool` packages.

**Comment by u2m4c6** [comment]
I am getting this same error in 2021 with .NET 6 preview 7 on an M1 mac.

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.1.18 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.9 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      6.0.0-preview.7.21377.19 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
 - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=osx.11.0-x64
 ```
 
When I run:

`dotnet ef dbcontext scaffold [connection string] Microsoft.EntityFrameworkCore.Sqlite --context-dir Data --output-dir Models --project [name].csproj`

Adding  `<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>` to the csproj file does not work but `<RuntimeFrameworkVersion>6.0.0-preview.7.21377.19</RuntimeFrameworkVersion>` does work. Obviously hard coding a specific preview version is not going to work great for CI/CD, let alone production.
