### ISSUE TITLE
Perf: Avoid boxing values as much as possible

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#10952]
We will use this issue to track optimizing hot paths in which we currently box instances of value types, e.g.:
- property values on the query pipeline become at some point a reference to an object
- parameters always go through boxing

In order to avoid boxing all the way through we need the underlying data source to also do it. @roji has done the work to avoid boxing in NpgsqlDataReader. 

Related: 
- #2079 Perf: Consider using entity instances for value buffer
- https://github.com/dotnet/corefx/issues/8955 API for writing parameters without boxing
- https://github.com/dotnet/corefx/issues/27074 SqlClient: Avoid boxing values as much as possible

**Comment by smitpatel** [comment]
#2079 is fixed
