### ISSUE TITLE
Visual Studio and dotnet scaffolded view generation does not follow new DbSet convention

### ISSUE THREAD

**Issue by mqudsi** [dotnet/efcore#10959]
_I feel as if this issue is certainly already filed, but I cannot locate anything that would be relevant._

With the improvements to naming deductions/generations in EF.NET Core 2, the existing tooling (both in Visual Studio 2017 Preview as of 15.6 Preview 4.0 and with the CLI `dotnet apsnet-codegenerator` utility) does not generate code compatible with the new `DbContext` table names.

In particular, while EF.NET Core 2 uses the existence of `DbSet<Entity> SetName` as a hint that the table for `Entity` is `SetName`, the code generated by the tooling is wholly ignorant of any such concept and instead relies on the presence of a table/`DbSet` in the `DbContext` that uses the name of the entity as the name of the `DbSet<Entity>` property and/or table.

Since the code for analyzing `DbSet<Entity>` members to automagically determine property names is already written, it should be reused by the tooling to generate compatible views that do not need to be hand-edited afterwards. Both tooling approaches for scaffolding generation already require the project to be compiled for analysis in all cases.

(Note that even overriding `OnModelCreate` and adding `builder.Entity<Model>().ToTable("ActualName")` is presently ignored by the tooling.)

**Comment by ajcvickers** [comment]
@mqudsi ASP.NET scaffolding is managing in the https://github.com/aspnet/Scaffolding repo. It looks like this issue was already reported there: https://github.com/aspnet/Scaffolding/issues/633

**Comment by mqudsi** [comment]
Awesome, thank you very much!
