### ISSUE TITLE
Version for package `Microsoft.EntityFrameworkCore.Tools.DotNet` [version 2.0.1] could not be resolved. (VS for Mac)

### ISSUE THREAD

**Issue by firrae** [dotnet/efcore#10957]
Describe what is not working as expected.
The EF command line tools are not able to be resolved and therefore used:

```
Exception message: Version for package `Microsoft.EntityFrameworkCore.Tools.DotNet` could not be resolved.
Stack trace: None provided.
```

### Steps to reproduce
I have a simple application I created using the boilerplate from VS2017 for Mac. I created a new .Net Core 2 Web API project then modified the .csproj file to be the following:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DockerComposeProjectPath>../docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.10-rc" />
    <PackageReference Include="MySql.Data" Version="8.0.10-rc" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.Dotnet" Version="2.0.1" />
  </ItemGroup>

</Project>
```

I have changed nothing else about the project files as the documentation never told me to: [https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet).

### Further technical details
EF Core version: 2.0.1
Database Provider: MySql.Data.EntityFrameworkCore (8.0.10-rc) - We are testing but I haven't even loaded this package yet into the project. The issue also happens if I remove this and the other MySQL packages.
Operating system: 
IDE: Visual Studio for Mac Community 2017 7.3.3 (build 12)
Dotnet Core info: dotnet --info
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by smitpatel** [comment]
@firrae - I created new Web API project in VS for mac and copied above csproj file in it. (Removed the docker line). VS for Mac showed me package restore successful. 

Though when I tried using dotnet ef on command line, it gave me error and when I did dotnet restore then it actually installed Tools.DotNet package. It seems that for some reason DotNetCliToolReference is not restored properly in VS for mac.

**Comment by firrae** [comment]
@smitpatel Interesting. Thanks for pointing that out. I will need to test this when I get into the office tomorrow morning.

I had been assuming that the restore method VS for Mac and the CLI were using were the same so I hadn't thought to try the CLI independently. Is that a Nuget issue or a VS issue? I know where to put issues for Nuget, but where would one submit bugs for VS, any ideas?

Also, does this mean that if I use VS to add packages to my application I have to jump to the CLI after each addition and restore by VS to re-run the restore from the CLI?

**Comment by smitpatel** [comment]
I also believed that VS doing restore should be full and CLI should be no-op but for some reason I got few packages getting installed. It may be issue in my machine since I also have preview build of SDK installed in my machine. There can be difference if VS & CLI are using different NuGets.

It would be really helpful if you are try out CLI to restore and see if there are differences or not. Ideally, adding package in VS should also restore it.

If you find that CLI restore is required even after VS restored packages then it would be VS issue. To report bugs for VS, in VS for mac app, goto Help->Report a problem

**Comment by firrae** [comment]
I can confirm that when I use the CLI's restore function the commands work. Interesting.

Thanks for pointing that out, I'll make a note to MS about the issue and maybe someday it'll get fixed.

**Comment by korirsammy** [comment]
Update Microsoft.EntityFrameworkCore.Tools.DotNet version to the lates version in Nuget. For me, the latest version was 2.0.3.

<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
  </ItemGroup>
