### ISSUE TITLE
Add fluent API for configuring value snapshot/comparison

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10961]
#9753 added support for DetectChanges to work with types that need a custom snapshot and/or equality comparison. This allows providers (e.g. for Postgres) to create type mappings with these things specified. This issue is about adding fluent API to make it easy for applications to specify equality/snapshot, which is important when using value conversions for model types that need such things.

**Comment by AndriySvyryd** [comment]
Is this fixed by https://github.com/dotnet/efcore/commit/1dc1788b53688c63f0b5bc70ca5c04fd9cb0391c?

**Comment by ajcvickers** [comment]
Duplicate of #18643
