### ISSUE TITLE
EntityFrameworkCore and Windows Forms apllication ?

### ISSUE THREAD

**Issue by Diaskhan** [dotnet/efcore#10964]
Could some body exmplain me How to make windows forms apllication using ef core 2.0?

I heard that support of windows app has dropped!

In Google i finded.
1.We could make Electron application 
2.Using Universal app!

Maybe have some work around that make Windows Form and Ef core 2.0 works togeher?

**Comment by ralmsdeveloper** [comment]
Yes it works!

**Comment by Diaskhan** [comment]
There have some guide or tutorial? Didnt finded in google !

**Comment by ralmsdeveloper** [comment]
Keeping in mind what you already use in the WEB application, it's basically the same file structure.
As a basic example, create a DBContext file and configure it, so it will be used on any part of your system.

**Comment by ralmsdeveloper** [comment]
There are some comments on this here: [https://www.reddit.com/r/csharp/comments/73ewhi/ef_core_20_with_winforms_fow_newbs/](https://www.reddit.com/r/csharp/comments/73ewhi/ef_core_20_with_winforms_fow_newbs/)

**Comment by Diaskhan** [comment]
Thanks ralms. topic could be closed !

**Comment by ralmsdeveloper** [comment]
Yes, feel free to close it!
