### ISSUE TITLE
How do I create linked entities for X entity using Many-to_Many

### ISSUE THREAD

**Issue by hitaspdotnet** [dotnet/efcore#10978]
I want create a **Product** entity and that entity can have list of Products as **Linked Products** but I don't know why my codes not working. I'm student and very newbie to EF core mapping. 
<br>
I create 2 Entity Classes for this Product.cs and ProductLink.cs, here is my classes <br>

**Product.cs**

        public class Product : Content
        {
            public virtual string Description { get; set; }
    
            public virtual Guid? ThumbnailImageId { get; set; }
    
            [ForeignKey("ThumbnailImageId")]
            public virtual Media ThumbnailImage { get; set; }
    
            public virtual List<ProductLink> ProductLinks { get; set; } = new List<ProductLink>();
        }

**ProductLink.cs**

        public class ProductLink : EntityBase
        {
            [ForeignKey("ProductId")]
            public virtual Product Product { get; set; }

            public virtual Guid? ProductId { get; set; }

            [ForeignKey("LinkedProductId")]
            public virtual Product LinkedProduct { get; set; }

            public virtual Guid? LinkedProductId { get; set; }
        }

Error : 

> Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'List<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by ralmsdeveloper** [comment]
@ajcvickers wrote on his blog a great content about many-to-many

Maybe this can give you some help:
[https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/)

[https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-2-hiding-as-ienumerable/](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-2-hiding-as-ienumerable/)

[https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-3-hiding-as-icollection/](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-3-hiding-as-icollection/)

[https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-4-a-more-general-abstraction/](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-4-a-more-general-abstraction/)

**Comment by CS-beglnner** [comment]
@ralmsdeveloper I read them for 2 day but I cant understand why my code not working. Can you give me a tips about that? whats my wrong? They articles is about using 2 different entity classes, I want use join entity type for my linked entities and haven't problem for using different entity one-to-may or many to-many but getting this error just for shared entities between up to 40 entities. Any idea please?

**Comment by ajcvickers** [comment]
@CS-beglnner See the example in my comment here: https://github.com/aspnet/EntityFrameworkCore/issues/10698#issuecomment-358087417
