### ISSUE TITLE
dotnet ef dbcontext scaffold treats multiple tables as single table 

### ISSUE THREAD

**Issue by livarcocc** [dotnet/efcore#10980]
_From @radhikagadde on February 15, 2018 9:32_

## Steps to reproduce

I am trying to build EF Core 2.0 application and tried to use reverse engineering using command line.

If i specify single table, classes are generated, where as if i specify two tables separated by "," CLI teats as single table and error is thrown.

dotnet ef dbcontext scaffold   "server=xxxxxx:6000;uid=newton;pwd=xxxx;database=xxxxx" "Microsoft.EntityFrameworkCore" -o Actual\ModelzOS —schema NEWTON —framework netcoreapp2.0 -c RevEngContext -f -t REVORDERDETAILS,FILTEREDOUT

<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
<PackageReference Include="xunit" Version="2.3.1" />
<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />

## Expected  behavior

should generate model

## Actual behavior

ERROR:
Unable to find a schema in the database matching the selected schema NEWTON.
Unable to find a table in the database matching the selected table REVORDERDETAILS,FILTEREDOUT.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

_Copied from original issue: dotnet/cli#8621_

**Comment by bricelam** [comment]
Specify multiple tables like this: `--table REVORDERDETAILS --table FILTEREDOUT`

**Comment by radhikagadde** [comment]
Is there any plan to consider this fix issue for CLI?
Its very difficult to specify --table for each table..
Same option worked for Core 1.1 
I see that scaffold-dbcontext is working with tables  separated by comma..then why not CLI support it?

**Comment by bricelam** [comment]
Scaffold-DbContext is a PowerShell cmdlet which natively supports array parameters. `dotnet ef` uses a command-line parser shared amongst the other ASP.NET and .NET Core teams. In it, the idiomatic way to specify multiple values is by specifying the option multiple times.

**Comment by radhikagadde** [comment]
Thanks! That answers!
