### ISSUE TITLE
Multiple cs files with backticks

### ISSUE THREAD

**Issue by odannyc** [dotnet/efcore#10998]
Is this intended?

![screen shot 2018-02-16 at 2 15 09 pm](https://user-images.githubusercontent.com/12864641/36331744-ee41ef92-1323-11e8-862c-e7a7905e923c.png)

Its located here:
https://github.com/aspnet/EntityFrameworkCore/tree/dev/src/EFCore/Diagnostics

**Comment by Eilon** [comment]
Yes - they represent the different generic types based on the number of type arguments that they have, each of the back-ticks represents 1 generic type argument.
