### ISSUE TITLE
Idea: WebSQL Provider (Sqlite on Blazor)

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/efcore#10999]
now that the blazor project is an official research project at Microsoft please consider creating a client side entity framework core provider for WebSQL so that blazor client can work with local data storage and utilise the power of entity framework core, linq etc.

**Comment by ajcvickers** [comment]
@grahamehorner This is an interesting idea that has been discussed recently, but we're not 100% sure that EF is a good fit here. Assigning to @divega to follow up more.

**Comment by grahamehorner** [comment]
@ajcvickers understand, the reason for asking was that IMHO if EF Core was able to target WebSQL within Blazor/Mono wasm runtime this would bring a great benefits to the developer have aligned data access in both client/server and allow client side caching of data and possibly offline functionality.

**Comment by HalidCisse** [comment]
Very useful for electron apps, where frontend size is not big issue.
Electron + blazor + EfCore = ?

**Comment by divega** [comment]
Here are some initial thoughts on this (based on a conversations with @SteveSandersonMS):

Reasons EF Core may not be a good fit for Blazor:
- Size constraints: I don't know what the effective constraints are, but perhaps @SteveSandersonMS can provide some more information. Presumably this maybe less of an issue for Electron apps (as [mentioned above in the thread](https://github.com/aspnet/EntityFrameworkCore/issues/10999#issuecomment-367833955))?
- Reliance on executing LINQ expressions that are compiled and cached at run-time, which Blazor may not be efficient at 

Reasons EF Core may be a good fit for WebSQL:
- We already have a Sqlite provider, so this should at least be less work than IndexDB

Regardless, we may want to have an EF Core-like experience for Blazor. We will keep this issue in the backlog, waiting to learn more.

**Comment by 970065574** [comment]
> I'm not sure if it helps, but github has various examples of modern SQLite compiled to WebAssembly. If that is functional, WebSQL Provider wouldn't be necessary.

can you recall that example link please? I am looking for the Blazor webassembly with sqlite (without .net core hosted).

**Comment by bricelam** [comment]
See also https://github.com/aspnet/EntityFrameworkCore/issues/18908
