### ISSUE TITLE
ConnectionTimeout not working

### ISSUE THREAD

**Issue by bigswede74** [dotnet/efcore#10991]
Hello,
I'm trying to set the ConnectionTimeout in my connection string but EntityFrameworkCore seems to ignore the value and default to 30 seconds.

### Steps to reproduce
Use the ConnectionTimeout parameter in the connection string.

connectionString="Server=10.10.10.10;Database=MyCatalog;User Id=sa;Password=123456;MultipleActiveResultSets=true;Application Name=MyApp;ConnectionTimeout=10"

### Further technical details
EF Core version: 2.0.0, targetFramework=net47
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.6

**Comment by ErikEJ** [comment]
Are you sure you are not mixing up connection timeout and command timeout?

**Comment by bigswede74** [comment]
@ErikEJ I'm trying to set the ConnectionTimeout.

**Comment by ErikEJ** [comment]
And it takes you more than 30 seconds to connect to your database??

**Comment by bigswede74** [comment]
I'm looking to detect if the database is reachable in 10 seconds as opposed to the default of 30 seconds.

**Comment by ErikEJ** [comment]
I think you need to adjust ConnectRetryCount and ConnectRetryInterval as well:
https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx (will always add 10 seconds with default values)

**Comment by bigswede74** [comment]
@ErikEJ the below code still takes 30 seconds to timeout.

```c#
                    var connString ="Server=10.10.10.10;Database=MyDb;User Id=sa;Password=123456;MultipleActiveResultSets=true;"

                    var sqlConnectionStringBuilder = new SqlConnectionStringBuilder(connString)
                    {
                        ConnectTimeout = 10,
                        ConnectRetryCount = 0,
                    };

                    using (var context = new MyContext(new DbContextOptionsBuilder<MyContext>()
                        .UseSqlServer(sqlConnectionStringBuilder.ConnectionString).Options))
                    {
                        var stuff = context.Stuffs.ToList();
                    }
```

**Comment by ralmsdeveloper** [comment]
@bigswede74 
Have you tried to make this connection outside EF Core?
I've gone through this, using only ADO.NET, the only way to really supply this was by doing a function to test the connection!

```csharp
public static class SqlExtensions
{
    public static bool TestConnection(this SqlConnection conn, int timeout)
    {
        var task = Task.Run(() =>
        {
            try
            {
                conn.Open();
                return true;
            }
            catch
            {
                return false;
            }
        });

        if (!(task.Wait(timeout * 1000) && task.Result))
        {
            throw new Exception("Servidor/Rede fora de operação!");
        }

        return conn.State == ConnectionState.Open;
    }
}
```

**Comment by bigswede74** [comment]
@ralmsdeveloper this approach works for me, thanks.

**Comment by Charles113** [comment]
This does nothing:

         b.UseSqlServer("Data Source=localhost;Initial Catalog=TestPW;" +
               "TrustServerCertificate=True;User ID=g;password=2;connect timeout=1", 
         options =>
         {
             options.CommandTimeout(1);
         });
         
I still get timeout after 30 seconds for my first query. 
Is this a general bug in `DbConnection` that all of the timeout settings are ignored?
