### ISSUE TITLE
Return JObject directly from ef core query

### ISSUE THREAD

**Issue by andrew-vdb** [dotnet/efcore#11009]
https://github.com/aspnet/Identity/issues/1361
```
var roles = roleManager.Roles.ToDictionary(r=>r.Id,r=>r.Name);
                                
var usersWithRoles = userManager.Users.Include(u=>u.Roles).AsEnumerable().Select(u =>
{                    
  var obj=(JObject)JToken.FromObject(u);
  var rolesName= string.Join(",",u.Roles.Select(r=>roles[r.RoleId]).ToArray());
  obj["Roles"]=rolesName;                    
  return obj;
 } 
); 
```

I think entity framework will create IEnumerable of ApplicationUser first and then I transform the data in memory.
```
userManager.Users.Include(u=>u.Roles).AsEnumerable()
```
It will be nice if the returned values from database in JObject format (from Newtownsoft), as I can modify its property, add/remove property

```
var roles = roleManager.Roles.ToDictionary(r=>r.Id,r=>r.Name);
var usersWithRoles = userManager.Users.Include(u=>u.Roles).AsJObjects(j =>
{
  var rolesName= string.Join(",",j["Roles"].Select(r=>roles[r.RoleId]).ToArray()); //simplified
  j["Roles"]=rolesName;                    
  return j;
 } 
```

**Comment by ajcvickers** [comment]
@andrew-vandenbrink This is not something we are going to build into EF Core. Instead it seems like something that could be done as an extension package, which somebody in the community might be interested in doing. Closing this as there is nothing actionable on the EF side.
