### ISSUE TITLE
Address any performance regressions in EF Core 2.1

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#11016]
Creating this issue as a reminder to look at our perf report and identify any regressions we want/need to address, then create separate issues for them.

Now that #10972 is done we should just need to update the report and wait for the data.

**Comment by ajcvickers** [comment]
Assigning to @bricelam for now to update the reporting for the new build combinations. Once this is done we will re-triage again for next steps.

**Comment by bricelam** [comment]
Clicked refresh.

**Comment by ajcvickers** [comment]
Filed:
* Include: #11197
* Change tracking: #11194
* Update pipeline: #11195
* Model building: #11196
