### ISSUE TITLE
Custom SQL Query with ToListAsync() Is ordered by ID (which is not intended nor given)

### ISSUE THREAD

**Issue by MarkusBrgr** [dotnet/efcore#11014]
Creating an custom SQL Query and executing it with ToListAsync(), gets ordered by the ID.
But because the Custom SQL Query is already ordered, the result set is in the wrong order.

### Steps to reproduce
In the following Code Example, the inner query has an order by statement. But EF Core puts, because of the .Include() statements, an Select over the given sql Statement, and puts an "ORDER BY ID" to the end of the Statement.
```c#
string sql = "SELECT [x].* 
              FROM (--Magic inner Select--) [temp] 
              JOIN [Table] [x] ON [x].[ID] = [temp].[ID]";

List<XEntity> result = await DbSet.FromSql(sql, sqlParameters.ToArray())
                                  .Include(t=>t.OtherTable)
                                  .Include(t=>t.AnOtherTable)
                                  .ToListAsync();
```

### Further technical details
EF Core version: 2.0.1
Database Provider: SqlServer

**Comment by ajcvickers** [comment]
@MarkusBrgr Include needs to have a well-defined ordering so that the results can be correlated correctly. When using FromSql, the SQL string is opaque to EF--it's not feasible to parse it--so we have no way of knowing whether there is already an ordering or not, and we therefore have to introduce one. If a different order-by is used in the LINQ query, then EF will attempt to use that order-by instead because it is known.

**Comment by MarkusBrgr** [comment]
Ich werde ab  21.02.2018 nicht im Büro sein. Ich kehre zurück am
22.02.2018.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [aspnet/EntityFrameworkCore] Custom SQL Query with ToListAsync() Is
ordered by ID (which is not intended nor given) (#11014)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2018 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen dürfen
über dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.
