### ISSUE TITLE
Extended error codes

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#11011]
How can I get the extended error code for an SQLite error? The SqliteException.SqliteErrorCode only returns the primary error code (fairly useless) not the extended error code. Note there is a function ([sqlite3_extended_result_codes](https://sqlite.org/rescode.html)) to put SQLite into a mode where the extended error code is returned, however I don't see how to apply this to an EF connection.

**Comment by bricelam** [comment]
Duplicate of aspnet/Microsoft.Data.Sqlite#404. In version 2.1.x, use `SqliteException.SqliteExtendedErrorCode`.

In version 2.0.x, you can drop down to SQLitePCL.raw:
``` csharp
catch (SqliteException ex)
{
    var extendedErrorCode = SQLitePCL.raw.sqlite3_extended_errcode(connection.Handle);
}
```

**Comment by sjb-sjb** [comment]
Thanks!
