### ISSUE TITLE
EFCore SQLite - Android - Error constructor call failed

### ISSUE THREAD

**Issue by Reshiru** [dotnet/efcore#11027]
SQLite database not useable in Xamarin.Forms with Android.
On try to initialize new DbContext error will be thrown. 
Expected:
-> Generate database and resolve connection / object to the linked configurations

```
Exception message:
System.InvalidOperationException: A suitable constructor for type 'Microsoft.EntityFrameworkCore.Internal.DiagnosticsLogger`1[Microsoft.EntityFrameworkCore.DbLoggerCategory+Infrastructure]' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
```

### Steps to reproduce
Run the given solution 

[Issue_Droid.zip](https://github.com/aspnet/EntityFrameworkCore/files/1745940/Issue_Droid.zip)

**Edit:**
Constructor call inside MainPage.xaml.cs

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.6

**Comment by ConX-Ryan** [comment]
Has this got something to do with the 
```
 <PropertyGroup>
    <TargetFrameworks>netcoreapp2;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
```

workaround we have to apply when using migrations in a class library?

I am hitting the same issue

**Comment by cwrea** [comment]
@Reshiru Your Android app project has its `AndroidLinkMode` set to `Full`, and so the linker has removed types from EF Core that appear not to be used from a static analysis perspective, but are actually required at run-time, accessed via reflection. **Try changing your `AndroidLinkMode` to `SdkOnly`.**

I have an adapted Xamarin app sample [available here](https://github.com/cwrea/XamarinTodo/tree/NETStd20_EFCore201) that demonstrates EF Core 2.0.1 working in a Xamarin.Forms Android app. The Android sample app uses `SdkOnly` linking.

FWIW, setting `AndroidLinkMode` to `Full` with EF Core is only likely to work when issue https://github.com/aspnet/EntityFrameworkCore/issues/10963 has been addressed.

**Comment by bipindalsaniya** [comment]
Hello Chris,

I have same issues. couldn't resolved it. i have tried to change AndroidLinkMode also.

**Comment by cwrea** [comment]
@bipindalsaniya I suggest you look at the sample I linked to previously. Compare your project settings to those in the sample. When I got the sample working with EF Core 2.0.1, I also [posted about it](https://forums.xamarin.com/discussion/comment/321267/#Comment_321267) in the Xamarin Forums.

**Comment by divega** [comment]
@cwrea based on your understanding, is there anything pending in this issue besides what is covered in #10963 (e.g. the fact that we don't have linker hints and that the developer may need to add their own)?

**Comment by divega** [comment]
Also @cwrea, I knew this class of issues affected Xamarin.iOS, but I wasn't aware that they affected Xamarin.Android as well. Can you confirm?

**Comment by divega** [comment]
@cwrea you can ignore my previous request for confirmation that this also affects Android development. I have read enough of your posts to understand this part now. Thank you for sharing all this information with everyone!

**Comment by divega** [comment]
Closing this issue as external. Working with EF Core on Xamarin.Android currently requires several workaround covered by the links at https://github.com/aspnet/EntityFrameworkCore/issues/11027#issuecomment-374425403. The part of this issue that is actionable for EF Core is already covered by #10963.

**Comment by cwrea** [comment]
@Reshiru I just tried running your sample with the linking change I suggested above. I can confirm that if you change Android linking in your Debug configuration from "Sdk and User Assemblies" (Full) to "Sdk Assemblies Only" (SdkOnly), then the exception re: missing constructor for DiagnosticsLogger goes away.

However, the app then crashes in a different way:

    Assembly Loader probing location 'System.Runtime.CompilerServices.Unsafe'.
    Could not load assembly 'System.Runtime.CompilerServices.Unsafe' during startup registration.

Fortunately, that's another [known open issue, with Xamarin.Android](httpsgithub.comxamarinxamarin-androidissues1196), and the workaround I used in my sample can work here too; i.e. reverting from newer `PackageReference`-style references in the Android project's `.csproj` file to using `packages.config`  instead.

I've made both changes to your sample, attached below. Should now run for you without any crash.

[Issue_Droid_With_Fixes.zip](https://github.com/aspnet/EntityFrameworkCore/files/1844770/Issue_Droid_With_Fixes.zip)

@bipindalsaniya As with above, to get your own attempts working, you might need to do *more* than just change your AndroidLinkMode to SdkOnly. Following that, pay particular attention to the messages in the debug output window: one crash is not always the same as another. As the wise Gerald Weinberg wrote: **"Once you eliminate your number one problem, number two gets a promotion."**

**Comment by bipindalsaniya** [comment]
@cwrea Thanks for support.  i have download your sample project and understand but your project is successfully work till now my project has same issues.
-> i have added LinkDescription.xml in android root project and build action to linkdescription.
-> also i have change Linker none, sdkonly and sdk and user assembly with debug mode and release mode both way i have tested. i am also finding and resolving this errors.
