### ISSUE TITLE
Update ADO.NET driver in Oracle sample

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11024]
To test on .NET Core.

**Comment by ajcvickers** [comment]
We will wait for the release of a NuGet package before testing--pulling in assemblies directly is too messy.

**Comment by divega** [comment]
Beta 2 is out in NuGet: https://twitter.com/oracledotnet/status/971179206750060544?s=21. Clearing up fields so we can re-assign in triage.

**Comment by ajcvickers** [comment]
@ralmsdeveloper Are you interested in submitting a PR to update the provider in the EF Core Oracle sample.

**Comment by ralmsdeveloper** [comment]
@ajcvickers  Yes
I was waiting for you to manifest.

**Comment by smitpatel** [comment]
Re-opening so i remember to update Universe

**Comment by smitpatel** [comment]
Reverted the change.

**Comment by ralmsdeveloper** [comment]
@smitpatel, just out of curiosity!
This has been reversed until the universe is updated, as commented @natemcmaster?

**Comment by smitpatel** [comment]
@ralmsdeveloper - Yes. We need to figure out licensing side before using that package in our code. So we will first get approval to use the package in the code then update. I will do that work. Regardless, thanks a lot for testing out the new package for us.

**Comment by ralmsdeveloper** [comment]
Many thanks for your explanation now I understand.

Good job!

**Comment by ralmsdeveloper** [comment]
> @ralmsdeveloper - Yes. We need to figure out licensing side before using that package in our code. So we will first get approval to use the package in the code then update. I will do that work. Regardless, thanks a lot for testing out the new package for us.

@smitpatel Any news on that?
