### ISSUE TITLE
EF Core Power Tools y Reverse Engineer to connect BBDD closes VS2017

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11029]
From VS Feedback:

Using EF Core Power Tools y Reverse Engineer to connect BBDD.
After adding de BBDD server and select the BBDD.
When select OK in window "Choose Database Connection" Visual Studio shows an popup error reporting that VS2017 stoped to works.

**Comment by ErikEJ** [comment]
This should be reported in the EF Core Power Tools repo, where is the original issue?

**Comment by ajcvickers** [comment]
@ErikEJ The original issue came from VS feedback. There is nothing more than I posted above. I closed that issue with a link saying further followup should happen here. Would you prefer this is closed and the issue be tracked at your end?

**Comment by ErikEJ** [comment]
Yes please, it is a Power Tools issue, and I am tracking it already.

**Comment by ajcvickers** [comment]
Since this is an EF Core Power Tools issue, it is now being tracked at: https://github.com/ErikEJ/SqlCeToolbox/issues/639. Any further follow up should go there.
