### ISSUE TITLE
HasComputedColumnSql expression  is not recalculated for InMemory functionality

### ISSUE THREAD

**Issue by Nikitos1991** [dotnet/efcore#11032]
HasComputedColumnSql expression  is not recalculated for InMemory functionality.
### Steps to reproduce
1) Add computed column 
2) Create in-memory context option
3) create unit test which consume this computed column
4) expected result: computed column should be evaluated and unit test should be able to check calculation result
actual result:  computed column returns null

### Further technical details
EF Core version: (EF Core 2.0.0)
Database Provider:Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.4

**Comment by smitpatel** [comment]
`HasComputedColumnSql` is relational provider specific functionality. Hence not available during in-memory provider.

**Comment by ajcvickers** [comment]
@Nikitos1991 As @smitpatel says, the in-memory provider is not a relational provider and knows nothing of SQL. This is one reason why we suggest using SQLite in in-memory mode for testing where relational functionality is needed.

That being said, issue #10862 on the backlog is partially about supplying expressions for these things that are then translated into SQL. Doing this would allow the expressions to be run on the in-memory store.
