### ISSUE TITLE
EnsureCreated (db) with owned types works in Visual Studio, fails when deployed

### ISSUE THREAD

**Issue by FrederickBrier** [dotnet/efcore#11045]
I am using the 2.1.0-preview2-28189 which has working owned types. Run within the Visual Studio environment, it works. The application creates the tables (using EnsureCreated) and initializes the data correctly.

After setting up a server, web deploying the application to the server, and starting with the dotnet command, when it attempts to set up the database via EnsureCreated() and seed it with data, it fails with the exception I saw when owned types were not implemented or broken (it jams all the fields in one table with a foreign key to itself). However, if the application is run from Visual Studio, and connect remotely to the server database, it will create the correct database and seed it correctly. I can then start the application on the server, and having a correctly created database, it works fine.

As part of the setup of the server, [.NET Core SDK 2.1.4](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.4-windows-x64-installer) was installed. The doc and the installer say that the SDK 2.1.4 includes .NET Core 2.0.5.

Is the problem that some older assembly, that has the old EF Core assembly, is getting executed, where that does not occur with the Visual Studio environment? Thoughts? Maybe I just need to swap out a 2.0.5 assembly? This is not a deployment process that can be automated. I'd love to understand why it is failing. Thank you.

### Further technical details
EF Core version: 2.1.0-preview2-28189
Database Provider: ngpsql (PostgreSQL 10)
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@FrederickBrier This should work assuming that this is a "self hosted" deployment--that is, all of the EF assemblies and any other required for 2.1 to work are also deployed with the application rather than using the ones already installed on the server. However, probably an easier path is to install the entire 2.1-preview1 runtime for .NET Core and use that in the deployment.

**Comment by FrederickBrier** [comment]
I got distracted. I meant to ask, is there a link on how to install the entire 2.1-preview1 runtime for .NET Core? Following that path would be very helpful. Thank you.

**Comment by ErikEJ** [comment]
@FrederickBrier  https://www.microsoft.com/net/download/all

**Comment by FrederickBrier** [comment]
Ah silly me, is there an install for the 2.1-preview2-<nightly build number>? That is what I meant to ask, because it the owned types that will be fixed (hopefully) in a new nightly build. And if not, how would I build and then deploy it?

**Comment by ajcvickers** [comment]
@FrederickBrier 2.1 preview2 is not released yet. The EF packages on our nightly feed are labeled "preview2" in anticipation, and you may be able to get other parts of it from other places, but I wouldn't attempt to try to get a full 2.1 preview2 install of the SDK at this point.
