### ISSUE TITLE
Using property of owned type as a foreign key

### ISSUE THREAD

**Issue by LadislavMalecek** [dotnet/efcore#11058]
Is it possible to use a property of nested owned type as a foreign key for one to many relationship? I was not able to achieve this.
When not specifying the relationship, entity framework creates new column with name ProfileId instead of using the AttendantParameter_ProfileId. 
I need to have the profile in attendant parameter optional (int? in AttendantParameter).
Thank you for any help.

### Steps to reproduce
```c#
public class Profile {
    public int Id { get; set; }
    public List<EventAttendant> EventsAttended { get; set; }
}

public class EventAttendant {
    public int Id { get; set; }
    public AttendantParameter AttendantParameter { get; set; }
}

public class AttendantParameter {
        public int? ProfileId { get; set; }
        public Profile Profile { get; set; }
}
```

```c#

modelBuilder.Entity<EventAttendant>()
                .OwnsOne(i => i.AttendantParameter);

modelBuilder.Entity<Profile>()
                .HasMany(p => p.EventsAttended)
                .WithOne(ea => ea.AttendantParameter.Profile);

```

```
Exception message (on creating new migration):
An error occurred while calling method 'BuildWebHost' on class 'Program'.
Continuing without the application service provider.
Error: The expression 'ea => ea.AttendantParameter.Profile' is not a valid property expression.
The expression should represent a property access: 't => t.MyProperty'.
Parameter name: propertyAccessExpression
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 x64

**Comment by AndriySvyryd** [comment]
@LadislavMalecek To use an owned type property you need to configure the relationship from the owned type:
```C#
modelBuilder.Entity<EventAttendant>()
                .OwnsOne(i => i.AttendantParameter)
                .HasOne(ap => ap.Profile)
                .WithMany()
                .HasForeignKey(ap => ap.ProfileId);
```
But `Profile.EventsAttended` cannot be used for this relationship as it's between `Profile` and `EventAttendant.AttendantParameter#AttendantParameter`. Non-ownership navigations cannot point to an owned type.

**Comment by LadislavMalecek** [comment]
@AndriySvyryd @ajcvickers  Thank you for your response, but my idea is that the owned type is a part of the owners table. Thus I could define the relationship I want directly from the database, or when not using the owned type.
The relationship you have described goes in the other way. I want to get EventsAttended when I have entities of type profile. And the code you have written just describes relationship that already exists automatically.

Wouldn't it be possible to add this functionality? Or is there something fundamentally blocking? Allowing of non-ownership owned-type navigations is possible on database level.

**Comment by Neme12** [comment]
@ajcvickers Why is this closed?

**Comment by AndriySvyryd** [comment]
@Neme12 The navigation limitation is fundamental in owned types definition. The metadata model also limits the navigation to point to the entity type containing the foreign key properties and we don't plan on changing this.

**Comment by virzak** [comment]
I have the same issue minus the Navigation property, so the  `AttendantParameter` would look like this:

```cs
public class AttendantParameter {
        public int? ProfileId { get; set; }
}
```

I just want a **foreign key** from the owned type to another entity. The reason I don't need navigation is because it is a lookup type. Is this achievable? Didn't find an example here: in the [OwnedEntityContext.cs](https://github.com/dotnet/EntityFramework.Docs/blob/e72ad0db2c00d5ce82021884983faa7aca9f91e3/samples/core/Modeling/OwnedEntities/OwnedEntityContext.cs)

**Comment by Neme12** [comment]
Will this at least be possible with value objects? Since value objects aren't their owned entities and are just a set of properties, this shouldn't be a problem with them, right?

**Comment by virzak** [comment]
I think #26505 is the one to vote for
