### ISSUE TITLE
Byte keys not generating by convention

### ISSUE THREAD

**Issue by bryanjhogan** [dotnet/efcore#11051]
I just migrated an old project from Entity Framework Core 1.1 to 2.0.

All my tests that use the InMemoryDatabase failed when adding entities to the context. 

It seems the EF Core 2.0 does not recognize my `public byte ProductId { get; set; }` as something to generate a key by convention for. 

If I change the code to `public int ProductId { get; set; }` it works fine. 
or if I add a `.ValueGeneratedOnAdd` to its configuration, it also works fine. 

```
Exception message:
System.InvalidOperationException : The instance of entity type 'Product' cannot be tracked because another instance with the same key value for {'ProductId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
```

### Steps to reproduce

```
public async Task GetById()
{
	// Arrange
	var options = new DbContextOptionsBuilder<ProductsContext>()
		.UseInMemoryDatabase(databaseName: "Get by id test")
		.Options;

	ProductsContext productsContext = new ProductsContext(options);
	Product product01 = new Product { Name = "laptop", Sku = "sku01" };
	Product product02 = new Product { Name = "monitor", Sku = "sku02" };

	productsContext.Products.Add(product01);
	productsContext.Products.Add(product02);
	await productsContext.SaveChangesAsync();
	ProductsController controller = new ProductsController(productsContext);

	// Act
	var actionResult = await controller.Get(product01.ProductId);

	// Assert
	var okObjectResult = actionResult as OkObjectResult;

	Product returnedProduct = okObjectResult.Value as Product;

	Assert.Equal(product01.ProductId, returnedProduct.ProductId);
	Assert.Equal("laptop", returnedProduct.Name);
	Assert.Equal("sku01", returnedProduct.Sku);
}

public class Product
{
	public byte ProductId { get; set; }
	public string Name { get; set; }
	public string Sku { get; set; }
}
```

### Further technical details
EF Core version: "Microsoft.EntityFrameworkCore" Version="2.0.1"
Operating system: Windows 10, Fall Creators
IDE: (e.g. Visual Studio 2017 15.5.6)

**Comment by popcatalin81** [comment]
This is a change in EF Core 2.0 please see:

https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties

>> By convention, primary keys that are of an integer or GUID data type will be setup to have values generated on add. All other properties will be setup with no value generation.

**Comment by bryanjhogan** [comment]
Thanks @popcatalin81. But the code works fine with `short`, `long`, not just `Guid` and `int` as the document suggests. 

The date of that document is `10/27/2016`, but here is the one [announcing EF Core 1.1](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/)  dated `November 16, 2016`. 

There is a [document on breaking changes](https://docs.microsoft.com/en-us/ef/core/miscellaneous/1x-2x-upgrade#breaking-changes) between 1.1 and 2.0, but this is not mentioned.

**Comment by ajcvickers** [comment]
@bryanjhogan The thing that is confusing me about this issue is that it worked at all in 1.1. It is my understanding that we blocked store-generated byte keys entirely prior to 2.0--for example, see #7161. In 2.0, we stopped blocking it and instead turned it into a warning. It's possible that there are some inconsistencies in the way the in-memory provider was working.

All that being said, the current behavior you are seeing is as designed. That is, byte properties will not be generated by convention (because the key space is very small) but can be configured to use value generation if needed, for which there should be a warning in the logs.

**Comment by bryanjhogan** [comment]
Thanks @ajcvickers. This is obviously a breaking change for me, but luckily the code base is small and easy to update. 

Is [https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties
](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties
) correct, and the plan is  - 

>By convention, primary keys that are of an integer or GUID data type will be setup to have values generated on add. All other properties will be setup with no value generation.

I ask because `long` and `short` work fine.

**Comment by ajcvickers** [comment]
@bryanjhogan I submitted a PR to update the docs. https://github.com/aspnet/EntityFramework.Docs/pull/637
