### ISSUE TITLE
Can we add a few more strongly-typed overloads of HasColumnType?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#11057]
EF Core version: 2.0.1
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: Win 10 x64
IDE: VS 15.5.7

Please add additional overloads to the [`RelationalPropertyBuilderExtensions.HasColumnType`](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/RelationalPropertyBuilderExtensions.cs#L56-L79) fluent API extension, or via a different extension class in the `Microsoft.EntityFrameworkCore.SqlServer`.

It makes a lot of sense to add an overload that accepts `SqlDbType` plus some overloads to cover precision, scale, length etc.
This way we'll be able to call `HasColumnType` in a cleaner way, so instead of:

```c#
fileRecord
  .Property(fr => fr.MyColumn)
  .HasColumnType("binary(16)");
```

or 

```c#
  .HasColumnType($"{SqlDbType.Binary}(16)");
```

We'd be able to call it as such:

`.HasColumnType(SqlDbType.Binary, 16);`

Please see [my comment](https://github.com/aspnet/EntityFrameworkCore/issues/11057#issuecomment-368722990).

**Comment by ErikEJ** [comment]
https://msdn.microsoft.com/en-us/library/system.data.sqldbtype(v=vs.110).aspx ??

**Comment by weitzhandler** [comment]
Oops I thought it was .NET only, nice to see it in .NET Core too.
I'll change the original issue.

**Comment by weitzhandler** [comment]
@ErikEJ 
Oops I thought it was .NET only, nice to see it in .NET Core too.
I've changed the original issue.

**Comment by ajcvickers** [comment]
@weitzhandler The "normal" way to do this is to use HasMaxLength rather than specifying the store type explicitly. We are adding IsFixedLength in 2.1. I suspect HasPrecision and HasScale, or something similar, will come soon as well.

We will look at this in triage, but I don't expect that we will implement this in the way you suggest.

**Comment by weitzhandler** [comment]
@ajcvickers 
Thanks for your clarification!
I'm closing this issue then.

**Comment by weitzhandler** [comment]
How about having some strongly typed overloads such as `HasColumnType(sqlDbType: SqlDbType.VarChar, length: 32)` or `HasColumnType(sqlDbType: SqlDbType.Decimal, precision:  7, scale: 2);`?

**Comment by smitpatel** [comment]
How about `HasColumnType($"{SqlDbType.Decimal}({precision}, {scale})");` ?
You could easily construct any type using string interpolation. Or add extension methods to call interpolated version.

**Comment by weitzhandler** [comment]
I was merely referring to a syntactic sugar where things are provided cosmetically.
We both know the string interpolation solution is still ugly.

**Comment by smitpatel** [comment]
> We both know the string interpolation solution is still ugly.

I am fan of string interpolation so when API takes string, I would be much more into write interpolated string for concise syntax.

Regardless, The `SqlDbType` enum values are mapped to types of SQL Server. Other database providers have types with similar names but not always. Therefore more appropriate way to do it in provider agnostic way would be to use `HasMaxLength` & other APIs. Though there is restriction in EF Core that if you are using string method then it has to specific fully qualified name. But we almost got all set of method to pick right server type out of TypeMappingSource.

We'll discuss this in triage meeting. I was just throwing out some ideas.

**Comment by weitzhandler** [comment]
For your consideration, the SQL-specific `HasColumnType` extension with the MSSQL-specific code can be defined in the provider package. For your consideration, I also mentioned it in my first post.
Additionally, there can be a `SqlDbColumnAttribute` inheriting from `ColumnAttribute`.

Thanks a lot for all your hard work and great productivity!

**Comment by ajcvickers** [comment]
Triage: discussed this again, but we still don't think that the value of adding these overloads outweighs the cost of the additional decision points in the API usage.

**Comment by weitzhandler** [comment]
Alright. Thanks for taking the time to review this.
