### ISSUE TITLE
Question: should the basic, built-in type mappings accept ValueComparers?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11071]
While working on value comparison for PostgreSQL, I noticed that all the built-in type mappings ( (e.g. IntTypeMapping) expose a public constructor which accepts a ValueComparer. While it's clear why a ValueConverter needs to be passed in, it seems that the ValueComparer is an internal detail of the type mapping that should never be overridden (by a provider or by a user).

Am I mistaken, have I missed some use for this?

(I'm asking this also to make sure that my mental model of how this all works is correct)

**Comment by ajcvickers** [comment]
@roji See my comments on #11072.
