### ISSUE TITLE
Request for EF.Functions.Like with numeric column support.

### ISSUE THREAD

**Issue by SPEMoorthy** [dotnet/efcore#11089]
SQL Server's like operator is accepting comparison against Integer column, whereas EF.Functions.Like method is not accepting comparison with integer column. 
```
             SELECT * FROM Tbl WHERE IntCol LIKE '%1%'  // Working in SQL Server
             p => EF.Functions.Like(p.IntCol,"%1%") //Not Working in EF Error	CS1503	Argument 2: cannot convert from 'int' to 'string'
```

### Further technical details
EF Core version: 2.0.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)

**Comment by SPEMoorthy** [comment]
@ajcvickers Thanks a lot

**Comment by StPaulis** [comment]
Doesn't seem to work on Ef Core 3.0 :/

**Comment by smitpatel** [comment]
@StPaulis - #17389 Fixed in EF Core 3.1

**Comment by brunofilho1** [comment]
> @SPEMoorthy This can be achieved by using a cast. For example:
> 
> ```cs
> context.Set<MyEntity>().Where(e => EF.Functions.Like((string)(object)e.IntCol, "%1%"))
> ```
> 
> Generates the following SQL:
> 
> ```sql
> SELECT [e].[Id], [e].[IntCol]
> FROM [MyEntity] AS [e]
> WHERE [e].[IntCol] LIKE N'%1%'
> ```

Finally found something, IT WORKS! THANKS!

**Comment by mihaidarieskyuk** [comment]
for me, using (string)(object) for casting generates CAST(ROUND(fieldHere, 0) AS nvarchar(max) and does not work

**Comment by roji** [comment]
@mihaidarieskyuk please open a new issue with a minimal code sample showing that - there should be a ROUND there.
