### ISSUE TITLE
[Question] How to set connection string environment variable on Linux in service file

### ISSUE THREAD

**Issue by joacar** [dotnet/efcore#11096]
This is probably not the right place, but closest that I can think of :)

I have a `.service` file to run my application.
```
[Unit]
Description=My app

[Service]
Environment=ConnectionStrings__Default=Server=tcp:... 

[Install]
WantedBy=multi-user.target
```

Running the above causes argument exception. Keyword "'server" not recognized. Enclosing the value in double quotes causes exception that the format is invalid at line 49. (Just after the 3 in ,1433).

`Server=tcp:***.database.windows.net,1433;Initial Catalog=***;Persist Security Info=False;User ID=***;Password=***;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;`

Setting it in `appsettings.json` works find and I use it as a workaround but requires file transformation of the file.

Thanks

### Further technical details
```
$ dotnet --version
2.1.4
```

```
$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Ubuntu 16.04

**Comment by ajcvickers** [comment]
@joacar Is this about using a "service file" with ASP.NET Core configuration? If so, https://github.com/aspnet/Configuration is probably a better place to file this, although I am not sure that "service files" are supported at all. (@HaoK?) 

Closing the issue here since it is not an EF issue.
