### ISSUE TITLE
Release plan for EFCore.Proxies

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11105]
https://github.com/aspnet/Universe/blob/15f5e82de0f88227fcef266f17fc6454fd99c9f4/build/artifacts.props#L211-L213

Currently marked as ship. Should it be shipoob?

**Comment by smitpatel** [comment]
@natemcmaster - Can you tell us what each flag means for category like noship/ship/shipoob?

**Comment by natemcmaster** [comment]
ship = NuGet.org
shipoob = Ships by some other delivery mechanism (out of band). E.g. in Visual Studio, inside the .NET Core SDK, etc.
noship = don't ship it. This is typically used for experimental features only and .Sources packages.

**Comment by ajcvickers** [comment]
@natemcmaster So a package with "ship" will not be included in the SDK or any other installer, correct?

**Comment by natemcmaster** [comment]
Shipping in the SDK is an orthogonal flag (the LZMA setting here: https://github.com/aspnet/Universe/blob/15f5e82de0f88227fcef266f17fc6454fd99c9f4/build/artifacts.props#L5-L20). That setting is off by default, so just marking it as "ship" does not mean it will end up in the SDK installer.
