### ISSUE TITLE
VSTS build gets broken with 2.1.0-preview1-final

### ISSUE THREAD

**Issue by Leon99** [dotnet/efcore#11128]
The moment I switch to 2.1.0-preview1-final, my VSTS build gets broken with 
     1>C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Unable to load the service index for source https://xxx.pkgs.visualstudio.com/_packaging/xxx/nuget/v3/index.json. [d:\vsts-agent\_work\5\s\xxx\xxx.csproj]
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   Response status code does not indicate success: 401 (). [d:\vsts-agent\_work\5\s\xxx\xxx.csproj]
         NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://xxx.pkgs.visualstudio.com/_packaging/xxx/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 ().

Any ideas?

**Comment by ajcvickers** [comment]
@Leon99 Is there a reason you posted this on the Entity Framework Core repo? It doesn't seem to be related to EF. Hard to know where to direct you with just the information above, but maybe NuGet? https://github.com/NuGet/Home/issues

**Comment by Leon99** [comment]
Strange resolution. There must be something different with the package in this release, since 2.0.1 worked just fine. Hardly NuGet or vsts teams would know what exactly you did different this time. I'm not saying that it's necessarily your problem, but close it straight away is definitely wrong.

**Comment by smitpatel** [comment]
```
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Response status code does not indicate success: 401 (). [d:\vsts-agent_work\5\s\xxx\xxx.csproj]
NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://xxx.pkgs.visualstudio.com/_packaging/xxx/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 ()
```

The stacktrace suggests that something went with NuGet. That too while loading some index rather than downloading/installing any particular package. Hence we suggested to file issue on NuGet. Those folks would have better understanding at the cause of error in their code.
