### ISSUE TITLE
Feature Request - dotnet ef migrations add without specifying name

### ISSUE THREAD

**Issue by zeus82** [dotnet/efcore#11138]
This is a feature request.

It would be nice if it was optional to specify a name when creating a migration.  When I'm developing, I like making small incremental changes to the db schema.  When I do this, more often that not, I can't come up with a meaningful name, so my require it?!

**Comment by bricelam** [comment]
Are you looking for something lighter weight than Migrations, like #3053?

**Comment by zeus82** [comment]
yeah - looks like that covers it!
