### ISSUE TITLE
Consider using Humanizer

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#11160]
Roslyn has taken a dependency on this lib for pluralization: http://humanizr.net

“Humanizer meets all your .NET needs for manipulating and displaying strings, enums, dates, times, timespans, numbers and quantities.”

Features 

• Humanize String
• Dehumanize String
• Transform String
• Truncate String
• Format String
• Humanize Enums
• Dehumanize Enums
• Humanize DateTime
• Humanize TimeSpan
• Humanize Collections
• Inflector methods 
• Pluralize
• Singularize
• Adding Words
• ToQuantity
• Ordinalize
• Titleize
• Pascalize
• Camelize
• Underscore
• Dasherize & Hyphenate
• Fluent date
• Number to Numbers
• Number to words
• Number to ordinal words
• Roman numerals
• Metric numerals
• ByteSize

**Comment by ajcvickers** [comment]
> ErikEJ commented 2 days ago
> @bricelam suggests adding Humanizer as a default pluralizer for Reverse eng. See ErikEJ/EFCorePowerTools#243 - willing to do a PR if there is interest in this?

> ErikEJ commented 2 days ago
Should it be an additional NuGet package, like your EF6 pluralizer, @bricelam ?

> bricelam commented 2 days ago • 
> No, I think EFCore.Design can reference Humanizer directly

**Comment by ajcvickers** [comment]
Note: this should only ever be a design-time dependency.

**Comment by Grauenwolf** [comment]
I'm starting to see complaints about this breaking workflows. Was there a reason why this new feature was enabled by default instead of being opt-in?

**Comment by ErikEJ** [comment]
@Grauenwolf It is explained here: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#pluralizer

**Comment by Grauenwolf** [comment]
That explains why it is available, not why it was necessary to make it the default, introducing a breaking change.

**Comment by ErikEJ** [comment]
Why

Using plural forms of words for collection properties and singular forms for types and reference properties is idiomatic in .NET.

**Comment by ajcvickers** [comment]
@Grauenwolf To expand on Erik's comments, we chose to make a breaking change here because we believe that the long term benefit to customers outweighs the short-term cost. This is based on:
* Feedback over the years from the first version of classic EF through EF Core 5 indicates that a large majority of customers want this behavior. (We could be wrong.)
* The change required to keep using the old behavior is trivial--a single flag to set
* The break is in a tooling scenario, which means it won't break running applications without notice. (It is in a tooling scenario that is often scripted, but changing the script should be simple.)

**Comment by Grauenwolf** [comment]
So what happens when Humanizer is updated to fix the numerous spelling errors it introduces? 

Will EF Core pick up the new version, introducing bragging changes again, or are we stuck with any misspellings?

**Comment by ajcvickers** [comment]
@Grauenwolf We intend to pick up the new version. The reason we couldn't do that in EF6 is because the pluralizer changed _runtime_ behavior. In EF Core it only impacts tooling behavior, and we consider it acceptable to fix bugs like misspellings in tooling.

**Comment by Grauenwolf** [comment]
Thank you for your time.
