### ISSUE TITLE
Value Conversion for Enumeration To String

### ISSUE THREAD

**Issue by Tidus972** [dotnet/efcore#11185]
I'm using  Entity Framework Core 2.1 Preview 1 and .Net Core 2.0
I have an entity Drn with a Type property of type TransactionType.
TransactionType is an enum.

```c#
public abstract class BaseEntity
    {
        public int Id { get; set; }

        public DateTime? CreationDate { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdatedBy { get; set; }
    }

public class Drn : BaseEntity
    {
        public int Code{ get; set; }
        public string Value { get; set; }
        public int SegmentRId { get; set; }
        public TransactionType Type { get; set; }
    }

public enum TransactionType
    {
        Type1,
        Type2,
        Type3 
    }
```

I want to store the name of the enumeration and not the value; so I used the HasConversion method as follow:
```c#
modelBuilder.Entity<Drn>().ToTable("Drn")
                .Property(d => d.Type)
                .HasConversion(d => d.ToString(),
                d => (TransactionType)Enum.Parse(typeof(TransactionType), d));
```
I seed some data with 
```c#
modelBuilder.Entity<Drn>().SeedData(
                    new Drn { Id = 1, Type = TransactionType.Test2, Code = 2 },
                    new Drn { Id = 2, Type = TransactionType.Test2, Code = 2 },
                    new Drn { Id = 3, Type = TransactionType.Test3, Code = 2 });
```

My result is that  my column is created as an nvarchar(max) but the values inside are the value of the enumeration (ex: 2 for Type2) and not the name as expected.

Did I miss something or is it a bug ?

**Comment by ajcvickers** [comment]
@Tidus972 Looks like you are hitting #11131, for which there is currently a PR out. Also, consider [reading the docs on value conversion](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions). In particular, to convert an enum to and from its string values requires only this:
```C#
modelBuilder
    .Entity<Drn>()
    .Property(e => e.Type)
    .HasConversion<string>();
```
There is no need to write your own conversions for this.
