### ISSUE TITLE
Query: Navigation fixup doesn't happen for query with include take and concat

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#11181]
query using GearsOfWar model:

```cs
ctx.Gears.OrderBy(g => g.Nickname).Include(g => g.Squad).Concat(ctx.Gears);
```
result is 10 elements, with all the gears having their Squad property populated.

```cs
ctx.Gears.OrderBy(g => g.Nickname).Include(g => g.Squad).Take(1).Concat(ctx.Gears);
```

results in 6 elements with only "Baird" (which is projected twice, from left and right part of concat), having his Squad property populated.

**Comment by smitpatel** [comment]
We don't allow both sides of set operations to have different includes.
