### ISSUE TITLE
Unable to build latest dev

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11187]
1: Get latest dev

2: Run "build.cmd" from command line.

3: Fails with:

C:\Users\Erik\.nuget\packages\internal.aspnetcore.sdk\2.1.0-preview2-15707\build\GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly C:\Users\Erik\.nuget\packages\internal.aspnetcore.sdk\2.1.0-preview2-15707\build\..\tools\netcoreapp2.0\Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Code\EntityFramework\src\EFCore.Analyzers\EFCore.Analyzers.csproj]
C:\Users\Erik\.nuget\packages\internal.aspnetcore.sdk\2.1.1-preview1-15535\build\GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly C:\Users\Erik\.nuget\packages\internal.aspnetcore.sdk\2.1.1-preview1-15535\build\..\tools\netcoreapp2.0\Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Code\EntityFramework\src\EFCore.InMemory\EFCore.InMemory.csproj]

**Comment by ajcvickers** [comment]
@ErikEJ Is this still an issue for you? Have you tried clearing all your NuGet caches and deleting all preview versions of the SDK installed by the build? (There were some versioning changes in the SDK a while ago that might cause this.)

**Comment by ErikEJ** [comment]
I will do that, the build passed on AppVeyor, so it is only an issue on my PC
