### ISSUE TITLE
Using SeedData can generate code that violates code analysis rules SA1118 and CA1814

### ISSUE THREAD

**Issue by edwiles** [dotnet/efcore#11190]
When using EntityTypeBuilder.SeedData, EF Core migrations can generate code that violates code analysis rules SA1118 and CA1814.

A workaround is to globally suppress these rules, with Target = "~M:\<project\>.Migrations.InitialCreate.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)".

### Steps to reproduce
1. Create an entity named MyEntity:
```
   public int Id { get; set; }
   public string Name { get; set; }
```

2. In OnModelCreating, seed the table as follows:
```
            modelBuilder.Entity<MyEntity>().SeedData(
                new { Id = 1, Name = "Test 1" },
                new { Id = 2, Name = "Test 2" };
```

3. Drop and recreate the database via migrations:
```
dotnet ef database drop -f
dotnet ef migrations remove
dotnet ef migrations add InitialCreate
dotnet ef database update
```

4. Enable code analysis by adding project references for Microsoft.CodeAnalysis.FxCopAnalyzers and StyleCop.Analyzers, and create a ruleset file.

5. Build the project.

Code analysis reports:

```
Migrations\20180302122836_InitialCreate.cs(118,17): warning SA1118: The parameter spans multiple lines
Migrations\20180302122836_InitialCreate.cs(118,25): warning CA1814: Up uses a multidimensional array of object[*,*]. Replace it with a jagged array if possible. 
```

The offending lines in 20180302122836_InitialCreate.cs are:

                values: new object[,]
                {
                    { 1, "Test 1" },
                    { 2, "Test 2" },
                });

In case of use, here is an extract from my csproj:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Professional
IDE: Visual Studio 2017 15.5.4

**Comment by ajcvickers** [comment]
For SA1118, the code generation has been changed slightly so that this pattern is only used in more limited cases, however we have no further plans to change where it is still being used.

For CA1814, this is by-design. It is intentionally not a jagged array.

**Comment by edwiles** [comment]
That's fine but how about adding suppression pragmas to the generated code?

**Comment by ajcvickers** [comment]
@edwiles Because adding suppressions makes the code less readable for everyone, even those people (which is a lot) who don't use these tools. The discussion in #10203 may be relevant to this point,
