### ISSUE TITLE
Migrations: Test using snapshot

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#11193]
The test suite with most scenarios for migrations - `MigrationsModelDifferTest` currently doesn't use the product pipeline to run the tests. It creates two models and then diffs them. Whereas the product generates a snapshot of the first model, compiles it, loads it and then diffs it with the second model.

The model snapshot could be significantly different from the model (e.g. it uses different CLR types for properties that have a value conversion). And we are missing cases where the generated code doesn't compile at all.

However doing this for every test case might be too slow.

**Comment by roji** [comment]
Is this a dup of #20157?

**Comment by smitpatel** [comment]
@roji - They are related.
Source model should be built from a snapshot. (tracked here)
Target model should be built using conventions (tracked in #20157)

**Comment by roji** [comment]
OK, probably good to tackle together...

**Comment by ajcvickers** [comment]
See also:
* Build target model with conventions in MigrationsTestBase #20157
* Remaining clean up for migration tests #19668

**Comment by roji** [comment]
Poching
