### ISSUE TITLE
Oracle Sample Documentation

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#11191]
If you enable to generate the document from the Oracle sample provider, all basically all code is broken!

`
<GenerateDocumentationFile>true</GenerateDocumentationFile>`

![documentacaooracle](https://user-images.githubusercontent.com/16335882/37170702-5697aa34-22ea-11e8-9806-f5953b0b0610.PNG)

Taking this to solve.

/cc @ajcvickers  @bricelam

**Comment by smitpatel** [comment]
@ralmsdeveloper - Probably not generating documentation is by design. It is a sample provider only and not for production use & may not need documentation.

**Comment by ralmsdeveloper** [comment]
Thanks @smitpatel !

So the answer is not to generate?
Or are you going to discuss this?

**Comment by bricelam** [comment]
> So the answer is not to generate?

Correct. We may eventually remove the comments that are there.

**Comment by ralmsdeveloper** [comment]
As soon as I complete other priorities, I'll clean it!
