### ISSUE TITLE
Support for "netcoreapp2.1" (in Tools, for example)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11212]
Not sure if it is an issue, but just noticed this:

https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/dotnet-ef/RootCommand.cs#L155 

and something similar in src\EFCore.Tools\tools\EntityFrameworkCore.psm1

**Comment by smitpatel** [comment]
But ef.exe is netcoreapp2.0 only
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/ef/ef.csproj#L4

**Comment by ErikEJ** [comment]
I guess we can just close, then?

**Comment by smitpatel** [comment]
Let Brice tell us the secret why it is this way. I was just adding another piece of info into suspense. 🔀

**Comment by bricelam** [comment]
We compile ef.dll against netcoreapp2.0 so it can run on .NET Core 2.0, 2.1, 2.2, etc.

**Comment by bricelam** [comment]
It always executes on the same runtime as the user's project.
