### ISSUE TITLE
Guidance: best place to implement provider-wide features

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11236]
As part of implementing external plugins for the Npgsql provider (Nodatime, NetTopologySuite...), I need to provide a method for users which changes some global provider behavior (specifically add mappings and translators, see https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/300). Now, these changes aren't specific to a context - they affect all usage of the Npgsql provider. So putting this as an extension on the DbContextOptionsBuilder doesn't seem like the right option, since that's specific to a context.

Is there any good/standard way to add ways for users to configure completely global provider behavior?

**Comment by divega** [comment]
I believe we have actively tried not to need something like this :smile: 

Curious, do you already have a global API for this at the ADO.NET layer? How does it look like? Could you factor things so that you only need to set these mappings at the ADO.NET layer and have the EF Core provider pick them up as well? (I thought that was implied when I read https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/300). 

cc @ajcvickers

**Comment by roji** [comment]
At the ADO.NET level, mapping changes can be added/modified either at the global level or at the connection level:

```c#
// Nodatime will be used implicitly by all connections;
NpgsqlConnection.GlobalTypeMapper.UseNodatime();
// Nodatime will only be set up on a single connection. When it's returned to the pool the mappings will be reset.
var conn = new NpgsqlConnection(...);
conn.TypeMapper.UseNodatime();
```

To be honest, the per-connection mapping is a bit far-fetched: I expect 99% of users will just set up Nodatime globally for their entire application, but I wanted the option to be there at least for completeness. For intensive short-lived connections, setting up the mapping every time is also a perf hit.

Originally it's true that I imagined that NpgsqlTypeMappingSource would pick up all mappings from the ADO.NET layer, but that turned out not to work. There are at least two reasons for that: mappings contain actual code (literal generation), and they're also quite useless if they don't come with method/member translators (imagine spatial mappings without operations mapped to SQL). So I changed the idea to having an EF Core plugin that would add the mappings and translators.

Back to the subject, even if at the ADO.NET level I set up mappings per connection rather than globally (not good for perf), that doesn't really work on the EF Core level... Unless I'm mistaken, ITypeMappingSource, ICompositeMethodCallTranslator and IMemberTranslator are singletons, so shared between all Npgsql contexts, no? That means that I either have to add my mappings and translations to the singletons (hence this question), or I demote them to being non-singletons, which I don't think is a good idea...

Hope this is all making sense.

(BTW in a prototype I already have .NET CLR types mappings to Nodatime types, including operators executing at the server, really nice!)

**Comment by ajcvickers** [comment]
@roji To Diego's point, we haven't enabled anything like this so far. The closest we have are things like .UseRowNumberForPaging, which changes the way the SQL Server provider works in several ways, or EnableSensitiveDataLogging, which changes the way all of EF works. In both of those cases, the common thing to do is have one setting that is used everywhere by your application, but it is still possible to create one context instance that behaves one way and another that behaves the other way. 

This works because these things are implemented as a ISingletonOption. What this means is that the provider (or indeed all of EF) is allowed to hard-code whatever option has been configured into its singleton services. This means that, for example, the type mapper can be implemented in a simple and non-dynamic (i.e. more performant) way so that the common case (option is not changed for different context instances) is handled efficiently. However, if the option is changed, then EF will build a new internal service provider for the changed option so that it can have singleton services that behave in a different manner.

Maybe something like this would work for you? Otherwise, if you think truely global configuration of the provider is a better approach then we can work together on APIs for that.

**Comment by roji** [comment]
@ajcvickers thanks for explaining that.

The problem here is that at the ADO.NET layer, these plugins modify global state. In other words, once you (globally) set up the Nodatime in the ADO.NET layer, then reading timestamp columns will suddenly start to provide Nodatime objects, and if EF Core expects ordinary .NET DateTime then we'll have a crash. The fundamental issue is that the ADO.NET layer is managed completely outside of EF Core and dependency injection...

There *is* another option - I could set up Nodatime mappings whenever a connection is opened, rather than globally: this could fit nicely as a dbcontext option. If I go down this route, then your proposal above seems to make sense: I'd have two instances of NpgsqlTypeMappingSource in the application, one without the Nodatime plugin and one with it (I'd find some way to encode the plugin or mapping information into an ISingletonOption). This scopes the mapping changes nicely, and it works at the ADO.NET layer as well, since the mappings live only for as long as the connection is open (mappings are reset when returned to the pool).

There's only one drawback, but it's significant - performance. Unless I'm mistaken you guys open and close ADO.NET connections quite frequently, and the overhead probably isn't trivial. In addition, applications will typically either use a plugin or they won't - I can't imagine a need for mixing both Nodatime and non-Nodatime in the same application - so it's a shame to pay this perf price. I'd rather just things up globally at the ADO.NET layer and in the TypeMappingSource (and translators), and that's it.

What do you think?

**Comment by ajcvickers** [comment]
I don't think we want to make the common case slow just to support a more obscure scenario. Sounds like your provider really does have global configuration, and this cannot be obtained purely from the ADO.NET provider because it needs to know things that ADO.NET doesn't know. We haven't done any work on global configuration, but there is the EF class which is the starting point for a lot of "static" stuff, so maybe hanging something off there would make sense? @divega Thoughts?

**Comment by ajcvickers** [comment]
@roji We discussed this in triage and came to the following conclusions. First, it would be great if this didn't really need to be global. Some of the ideas put forward were:
  * Have different connection pools for the different cases, which may make the perf hit in the common case less of an issue (@divega)
  * Integrate ADO.NET with D.I. such that it doesn't need true globals (@anpete)

However, ultimately it is your call whether or not this needs to be truly global configuration. So, second, assuming that it does then:
 * It's probably best to just have it be a mechanism of the Postgres provider, not coupled to an common EF configuration mechanism.
 * We would also consider a common mechanism such as "EF.Provider" which would allow providers to add extension methods for global configuration in a common, perhaps more discoverable way. If you have thoughts on this we would love to hear them, but even if it is something that happens in the future it would be presumably possible for you to opt-in to it in the future.

For now, I'm moving this to discussions.

**Comment by roji** [comment]
Thanks to you and the team for spending the time discussing this.

> Have different connection pools for the different cases, which may make the perf hit in the common case less of an issue (@divega)

This could be a good direction, but the problem (as we've discussed many times in the past) is that there's no ADO.NET concept of a pool (see https://github.com/dotnet/corefx/issues/26714), so at the ADO.NET level there's no easy place for users to specify they want the plugin (e.g. Nodatime)...

Even if this ADO.NET issue were solved (e.g. some way to register plugins on a connection string), at the EF Core level there's still a singleton TypeMappingSource (and method/member translator...). So unless I'm mistaken this would again lead to multiple instances of those classes, possibly reducing perf (although maybe with ISingleton as you suggested...).

> Integrate ADO.NET with D.I. such that it doesn't need true globals (@anpete)

Unless I'm misunderstanding the idea, this is quite a big architectural change, isn't it? It would mean the DbConnection would be injected into the DI context just like any other EF Core service... Not that I think this is a bad idea, but it's definitely not something that can be done quickly and easily, and I wouldn't expect to go into this just to support Npgsql plugins (although it may be interesting to pursue regardless).

> It's probably best to just have it be a mechanism of the Postgres provider, not coupled to an common EF configuration mechanism.

That's probably where I'm going to go, at least with this first release... I can always hack something, where the EF Core Nodatime plugin calls some special static method on NpgsqlTypeMappingSource to add some extra mappings. It wouldn't be pretty but it would definitely work.

> We would also consider a common mechanism such as "EF.Provider" which would allow providers to add extension methods for global configuration in a common, perhaps more discoverable way. If you have thoughts on this we would love to hear them, but even if it is something that happens in the future it would be presumably possible for you to opt-in to it in the future.

I guess that would depend on how much need for there is from other providers. I definitely wouldn't jump into something like this without a clear case for it.

Unless you guys think there's more to discuss, I think that for now I'll go with the special Npgsql static-based mechanism, which would entirely circumvent both EF Core and DI. This would just be a first release, and I can always change how it works a bit later.

**Comment by divega** [comment]
>  so at the ADO.NET level there's no easy place for users to specify they want the plugin (e.g. Nodatime)...

Absolutely not saying that this solves all the problems :), but FWIW, what I had in mind when I said this was:

- Alternative 1: create an "options" object that contains the setting and you pass to the DbConnection (using a method or a property) before you open it (i.e. before a physical connection is associated with the DbConnection). This options object would be equal-comparable and would act (together with the connection string) as part of the lookup key for the implicit connection pool

- Alternative 2: add these settings as a new connection string key

Of course alternative 2 only works if you have a fixed number of well-known alternative type mappings that come built-in with the provider, or some kind of convention to discover the right plug-in binaries based on values specified in the connection string.

**Comment by roji** [comment]
> Alternative 1: create an "options" object that contains the setting and you pass to the DbConnection (using a method or a property) before you open it (i.e. before a physical connection is associated with the DbConnection). This options object would be equal-comparable and would act (together with the connection string) as part of the lookup key for the implicit connection pool

That reminds me a bit how SqlClient includes the username in the pool key alongside the connstring (for "integrated security"). I like this option less then:

> Alternative 2: add these settings as a new connection string key

This could be interesting. Rather than asking users to set up their plugins (either globally or per-connection), a plugin would register a "plugin ID" with Npgsql, which the user would then be able to reference in the connstring. That would naturally scope the plugin to the connstring. The EF Core plugin could work the same way - register itself with with EF Core provider, so that based on the plugins specified on the connstring, extra mappings and translators are pulled in, with ISingleton ensuring the right contexts get the right "singletons'.

I'll try looking into this.

**Comment by divega** [comment]
Registration can fix the limitations of the connection string approach. Didn’t think of it :smile:

**Comment by divega** [comment]
Some time ago I was in a discussion about authentication plug-ins for another ADO.NET provider, and now that I think of it, I believe it ended up adopting a very similar pattern.

Makes me wonder if it could make sense to try make this a general extensibility mechanism for the provider or if it should be specific for type mapping.

**Comment by roji** [comment]
I actually do have a 2nd new extensibility point, which is a little obscure - how to load type from the database. Npgsql usually loads all type definitions from a set of internal tables, this how is we know which enums/composites/extension types are available. However, there are a lot of non-PostgreSQL databases based on PostgreSQL or using the PostgreSQL wire protocol (CrateDB, CockroachDB, Denodo...) which aren't compatible with this, so I'm letting them define their own type loading routines via an external plugin.

So yeah, this could be a more general mechanism, although at the moment I'm trying to not to over-engineer and prematurely build an architecture for it (which would be my natural tendancy...).

I think for the next version a simple, somewhat hacky, static-based global registration should be sufficient.

**Comment by roji** [comment]
Am closing this as I think we've discussed enough options and have found some satisfactory answers.
