### ISSUE TITLE
Owned types not included on GetDatabaseValues() on entry

### ISSUE THREAD

**Issue by ajeetys** [dotnet/efcore#11232]
When an entry with owned types is queried through entry.GetDatabaseValues(), owned types are not being retrieved.
Below is an example:
```c#
public class Student
{
	public int Id { get; set; }

	public string Name { get; set; }

	public Address Home { get; set; }
}

public class Address
{
	public string City { get; set; }

	public string Country { get; set; }
}

public class StudentContext : DbContext
{
	public DbSet<Student> Students { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Student>()
			.OwnsOne(s => s.Home);
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=StudentDb; Trusted_Connection=True;App=StudentContext");
		optionsBuilder.EnableSensitiveDataLogging();
	}
}
```

When  an existing student gets updated through a disconnected context...
```c#
static void Main(string[] args)
{
	var _context = new StudentContext();
	_context.GetService<ILoggerFactory>().AddConsole();
	_context.Database.EnsureDeleted();
	_context.Database.EnsureCreated();

	var student = InsertNewStudent(_context);

	UpdateStudent(student);

	Console.ReadLine();
}
private static Student InsertNewStudent(StudentContext _context)
{
	var student = new Student
	{
		Name = "Student_1",
		Home = new Address
		{
			City = "Sydney",
			Country = "AU"
		}
	};
	_context.Students.Add(student);
	_context.SaveChanges();
	return student;
}
private static void UpdateStudent(Student student)
{
	student.Home = new Address
	{
		City = "Perth", // new value
		Country = "AU"
	};
	var _context = new StudentContext();
	var entry = _context.Attach(student);
	entry.OriginalValues.SetValues(entry.GetDatabaseValues());
	_context.SaveChanges();
}
```
The above call ``entry.GetDatabaseValues()`` generates the below SQL

```SQL
exec sp_executesql N'SELECT TOP(1) [e].[Id], [e].[Code], [e].[Name]
FROM [Students] AS [e]
WHERE [e].[Id] = @__get_Item_0',N'@__get_Item_0 int',@__get_Item_0=1
```
How do I get to include the owned type and change track it?

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.5.7

**Comment by ajcvickers** [comment]
@ajeetys The Address is a different entity instance than the Student, and so GetDatabaseValues needs to be called for that instance. I'm curious as to why you expect the database values to be returned for the address when you call it for the student?

**Comment by ajeetys** [comment]
@ajcvickers Thanks for pointing this out. I was seeing Owned type in line with complex type of EF6. In EF6 we cannot get ``DbEntityEntry`` on Address instance.
EF6 includes data for complex types on GetDatabaseValues().

I was surprised I could do this with Core
```c#
var adEntry = _context.Entry(student.Home);
adEntry.OriginalValues.SetValues(adEntry.GetDatabaseValues());
```
The way owned types are retrieved when doing a ``_context.Find<Student>(student.Id)`` or you don't need to Include them when loading the parent, I was expecting the same behaviour when doing a GetDatabaseValues(). I wonder why it is being treated as a separate entity?

**Comment by ajcvickers** [comment]
@ajeetys Thanks for the additional information. It's important to remember that owned types are _not_ complex types even though they can be used for some of the same things. So, to answer your question, it is being treated as a separate entity because it is a separate entity.
