### ISSUE TITLE
Sqlite - System.InvalidOperationException: 'An exception occurred while reading a database value for property 'Schema.ReadOnly'. The expected type was 'System.Boolean' but the actual value was of type 'System.Boolean'.'

### ISSUE THREAD

**Issue by jonreis** [dotnet/efcore#11258]
I am trying to use EF Core with a version of Sqlite that supports encryption. Everything seems to work except for bool types. (see attached project that reproduces the problem) 

It does seem related to the fact that I am using System.Data.SQLite.Core 1.0.108. If I use an unencrypted database and do not pass in the SqliteConnection into the optonsBuilder, the bool is handled fine. 

      var connection = new SQLiteConnection(@"Data Source=..\..\Test.db;Password=FOOBAR;Read Only=true;PRAGMA temp_store=Memory;PRAGMA journal_mode=Memory");
      optionsBuilder.UseSqlite(connection);

If I change Readonly to an int instead of a bool and change from

                entity.Property(e => e.ReadOnly)
                    .IsRequired()
                    .HasColumnType("bit");

to:

                entity.Property(e => e.ReadOnly)
                    .IsRequired()
                    .HasColumnType("integer");

everything works.

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Sqlite

[SqliteBoolTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/1808682/SqliteBoolTest.zip)

**Comment by ajcvickers** [comment]
@jonreis Looks like you are not using [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) but instead using the System.Data.SQLite provider. The EF Core SQLite provider is designed only to work with Microsoft.Data.Sqlite since it behaves significantly differently than System.Data.SQLite.

More information about using Microsoft.Data.Sqlite with encryption can be found on @bricelam's blog: http://www.bricelam.net/2016/06/13/sqlite-encryption.html

**Comment by jonreis** [comment]
@ajcvickers, ok I'm 3 in 0 for bugs. 

Though, it seems like this should be prevented if it is not supported. It works, almost. Which means others are going to bump into this. Again, I am coming from the perspective of trying to get something that functioned will in EF6 migrated to EF Core 2.x. It has not been an easy migration.

Is it SQLitePCLRaw.bundle_sqlcipher that is compatible with  SQLite.Interop.dll's encryption? It is not clear from that blog post.

Appreciate the feedback.

**Comment by bricelam** [comment]
> Is it SQLitePCLRaw.bundle_sqlcipher that is compatible with SQLite.Interop.dll's encryption?

No. System.Data.SQLite [uses wincrypt](https://system.data.sqlite.org/index.html/artifact/d5323af6c6450b0f)--a deprecated Windows-only API.

**Comment by jonreis** [comment]
@bricelam on Windows it is pretty common to use this form of encryption as it was the one provided in the standard install of SQLite.Interop.dll. Which library can I use to be compatible with EF Core 2.1 and the database that were created with SQLite.Interop.dll?

**Comment by bricelam** [comment]
I think the best upgrade path is to decrypt the database using System.Data.SQLite and re-encrypt it using SQLCipher (or similar).

**Comment by jonreis** [comment]
Not the answer I was hoping for but thanks for letting me know

**Comment by bricelam** [comment]
@ericsink Do you know if there is an encryption technology compatible with System.Data.SQLite's?

**Comment by ericsink** [comment]
Not that I know of.
