### ISSUE TITLE
Can't mock DatabaseFacade

### ISSUE THREAD

**Issue by generik0** [dotnet/efcore#11254]
Hi

The DatabaseFacade is impossible to mock. 
Could the Facade not be an abstractions, without all those nasty extensions?

Your concrete DatabaseFacade could easily be abastracted=? This will also give you the ability to have different Facades for diiferent implemenations. Also allowing you to SO**L**ID .

Any thoughts?

**Comment by ajcvickers** [comment]
@generik0 The extension methods are a key part of allowing database providers to extend the API.

In general, creating test doubles for DbContext and related classes is not recommended. If you do need to create test doubles, then consider creating your own repository API and mocking that. You might also consider using DbContext with the in-memory database or with SQLite running in in-memory mode.

**Comment by generik0** [comment]
Hi
I would love to use the in mem dB.
But the migrations are unique from dB to dB. Hence i would need multiple migrations for each dB.

Also the sqlite does not support Removing columns etc. so the migration needs to rename the table, create a new table and transfer the data. Then set the constraints.

Would a abstract DatabaseFacade not help this?
So your migrations can be cross dbs and the facade implementation for the dB type adds the nessesary information?
Or you saying one should recreate the complete migration each time (which goes against the point of a migration)

I am just worried that your are going in the wrong way already with the new migrations. EF6 was smart, but you had to be very careful. Now EF7 is going that way also :-(
Very smart, but you need to be very carefully what you do....

Please note, extensions are essentially an antipattern, and make testing a pain. It does not follow the SOLID principles. You really should prefer a good OO abstraction and class over extensions.

**Comment by generik0** [comment]
@ajcvickers 

Please note, The only reason this came up was because i was implementing a uow pattern. So i needed to test it. And making a mock of the DatabaseFacade was easiest when it helps making the transaxtions. I also tried to make a proxy with NSubstitute .PartOf<> so i coul atleaset check that messages are received.
Nothing works with the DatabaseFacade :/

c#```
if (db.ConnectionState != ConnectionState.Open)
{
 db.Database.OpenConnection();
}
var transaction = db.DbConnection.BeginTransaction(isolationLevel) as DbTransaction;
_transaction = db.Database.UseTransaction(transaction);
```
