### ISSUE TITLE
EF Core does not reject queries using unmapped properties

### ISSUE THREAD

**Issue by mnmr** [dotnet/efcore#11299]
I have an entity with a simple auto-property that is ignored by EF (i.e. unmapped). When using the property in a query, EF issues a warning (saying that parts of the query can only be evaluated client-side), but does not outright reject the query.

Would it not make more sense to throw an exception in this scenario?

The are essentially two use cases here that I can think of:
1) The property is a simple auto-property and will always have the default value; using it in a query to filter results makes no sense, as all entities will always have the same (default) value.

2) The property is a computed property. In this case it might be desirable to be able to use the property to filter the results, but I'm not convinced it should be handled by EF. It's easy to omit the criteria from the query and and manually filter the retrieved entities, and it would result in fewer surprises/mistakes.

Given the current limits of the EF LINQ-to-SQL engine, we are unable to disable client-side evaluation of queries. However, it would be nice if client-side evaluation only happened when queries are too complicated (for EF to translate), not because the query is using an unmapped property (which in most cases is a bug anyway).

### Further technical details
EF Core version: 2.1.0-preview2-30355
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
@mnmr Thanks for your input. We discussed this in triage and for now we're going to keep a single warning. However, something we have discussed in the past that would help here is the ability to allow client evaluation only on selected queries, so that it is not a global on/off flag--I have filed #11306 to track this.
