### ISSUE TITLE
Implement IAsyncQueryable in DbSet

### ISSUE THREAD

**Issue by dotlogix** [dotnet/efcore#11300]
I think there is a use case to provide an implementation for IAsyncQueryable from the package System.Interactive.Async.Providers, instead of only implementing IAsyncEnumerable.

It would make it much more easy to have a consistent Async API above of entity framework.

So maybe I miss something, but I think even to write a wrapper to support this interface is not possible.

**Comment by ajcvickers** [comment]
@dotlogix We're not planning to take any additional dependencies on IxAsync packages or features at this time. There are various internal reasons for this, and we also want to have a good idea of where CoreFx/C# is going in terms of async support before doing anything new.
