### ISSUE TITLE
An exception has been raised that is likely due to a transient failure.

### ISSUE THREAD

**Issue by zhangxijing666** [dotnet/efcore#11303]
Hi All
When I upgrade my project from EF Core 1.1.1 to 2.0, and I get a linq bug.
Linq:
_var tax = DbContext.Agents.Where(a => a.Enable && !a.IsDeleted)Include(a => a.SalesTax).Where(a => a.Id == agentId).Select(a => a.SalesTax).FirstOrDefault();_

**I got a exception:**

2018-03-17 00:38:40.2461 Error Environment:Default
Message:An exception has been raised that is likely due to a transient failure.
StackTrace:   在 Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   在 Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   在 Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   在 lambda_method(Closure , QueryContext )
   在 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
----------------------Other Message--------------------------
An exception occurred in the database while iterating the results of a query for context type 'Qin.Core.Repository.QinDbContext'.
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. ---> Npgsql.NpgsqlException: Exception while reading from stream 

I don't understand the reaseon.
My project have a lot of similary linq. 
Please help me!

Thank you.

**Comment by ajcvickers** [comment]
@zhangxijing666 Are you saying that you occasionally see this? If so, are you sure it isn't really reporting a transient error? If this is a bug, then it looks like it's probably related to [the Postgres provider](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL), so you may want to file an issue there, including a runnable project/solution or complete code listing.

/cc @roji

**Comment by roji** [comment]
As @ajcvickers says this probably belongs in github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL. But not that your stack trace seems partial -
 NpgsqlException should have an inner IOException that explains exactly what went wrong.

**Comment by zhangxijing666** [comment]
@ajcvickers @ajcvickers Thank you for your suggestion

**Comment by barisates** [comment]
In my case, when I add **Command Timeout=0** to the connection string, the problem is solved.
