### ISSUE TITLE
Build Failed on Update-Database

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#11318]
I've upgraded my asp.net core 2.0.3 app to EF Core 2.1 and when I try to update database, I'm getting:

> PM> Update-Database -v
> Using project 'src\DevPortal'.
> Using startup project 'src\DevPortal'.
> Build started...
> Build failed.

But I'm able to build the project in Visual Studio

Full code:
https://github.com/Liero/vyvojari-sk/tree/2193d67facd5a284990478ebd21bb61a4c3522c0

**Comment by ajcvickers** [comment]
@Liero What issue are you reporting here?

**Comment by Liero** [comment]
I was able to build and run the project in visual studio but the `Update-Database` reported build failed. I tried to run dotnet build and found error in once of .Test projects that were not built by VS when I tried to run the project.
