### ISSUE TITLE
Visual Studio Community 2017 v15.6.1 and v15.6 EF Core related compile time errors when debugging a UWP project

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11327]
From VS Feedback:

Hi., I recently updated my Visual Studio IDE to 15.6 and then 15.6.1 successfully. I have a UWP project which referencing a .net standard project which is a database model project using SQLite data provider for EF Core as described at the link https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started. And, the db model project installed with respective nuget packages Microsoft.EntityFrameworkCore.Sqlite v2.0.1 and Microsoft.EntityFrameworkCore.Tools v2.0.1. In addition to these two projects (UWP and .Net Standard), my solution contains 2 Windows Runtime Component projects which in turn reference the same db model project, doing some background tasks using TimeTriggers. Before the successful installation of these two updates (15.6 and 15.6.1) for Visual Studio, my project and overall solution working fine, but, after the update entire solution throwing compile time exceptions/errors at random places when trying to debug the app. The strange thing is that, even though the errors occurring randomly in different projects time to time, they all are related to Entity Framework Core. And, even strange thing happening to the solution is that it sometimes succeed to build, deploy and open the app in the debug mode, but this also happens randomly. After changing the tags from <TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks> to <TargetFramework>netstandard2.0</TargetFramework> back and forth by editing the db model project .csproj file then the app runs normally, I can’t do this every time. I tried to clean the corresponding project and even the entire solution after I noticed the compile time exceptions/errors, but no use. I completely uninstalled and reinstalled a fresh copy of VS 2017 Community 15.6.1, still the issue persist. As I said the solution running perfectly well before the update. All the nuget packages used by the solution are up-to-date.

Nuget packages used by the solution 
Microsoft.NETCore.UniversalWindowsPlatform v6.0.8
NETStandard.Library v2.0.1
Microsoft.NETCore.App v2.0.5
Microsoft.EntityFrameworkCore.Sqlite v2.0.1
Microsoft.EntityFrameworkCore.Tools v.2.0.1
Microsoft.Toolkit.Uwp v2.2.0
Microsoft.Toolkit.Uwp.UI v2.2.0
Microsoft.Toolkit.Uwp.Notifications v.2.2.0
Microsoft.Toolkit.Uwp.UI.Controls v2.2.0
Microsoft.Xaml.Behaviors.Uwp.Managed v2.0.0
Magick.NET-Q16-AnyCPU v7.4.2
HtmlAgilityPack v1.7.1

**Comment by ajcvickers** [comment]
Notes from triage: this is likely an issue, as you found, with multi-targeting. Multi-targeting currently doesn't work well as an experience across VS, which is why we recently updated our guidance to not suggest it anymore for UWP/EF tooling. (See https://github.com/aspnet/EntityFrameworkCore/issues/10882 for some of the issues.) Beyond this, can you post the actual errors/stack traces that you are seeing?

**Comment by divega** [comment]
Part of the problem is that the guidance on the UWP tutorial hasn't been updated yet. Fixing it is tracked at https://github.com/aspnet/EntityFramework.Docs/issues/581. 

FWIW, the new guidance is to create a new .NET Core console app that targets "netcoreapp2.0" and execute the tools against it. The library should just target "netstandard2.0".
