### ISSUE TITLE
Deadlock issue on using SumAsync();

### ISSUE THREAD

**Issue by syedabdulaala** [dotnet/efcore#11321]
Having this issue https://stackoverflow.com/q/49262030/4209924 just in case of using SumAsync(); everything else is working fine...

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 (Version 1709, Build 16299.309)
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@syedabdulaala The first async call must be awaited before the second call is started.

/cc @anpete at @divega's request.

**Comment by syedabdulaala** [comment]
@ajcvickers so if I want to execute queries parallel then I have to make new instance of DbContext right? as I understand EF doesn't support processing multiple requests through the same DbContext object.

**Comment by ajcvickers** [comment]
@syedabdulaala Yes.
