### ISSUE TITLE
dbContext.Database.Migrate() is not working correctly when called from a asp.net test project.

### ISSUE THREAD

**Issue by paulvanbladel** [dotnet/efcore#11323]
I have a .net core asp.net project with localdb. Just an out of the box setup with migrations managed from the command prompt. So the migrations are managed in this project. There are not automagic migrations (by means of dbContext.database.Migrate() in this project. Working great.
Next, I have a corresponding test project based of TestServer and uses a slightly different Startup which I call TestStartUp which makes sure that I go to a dedicated localdb for testing (I deliberately don't want to use InMememory db) and that dbContext.Database.Migrate() is applied when a TestServer session is started. 
the dbcontext is setup with the specifying the migrations assembly:

```
            services.AddDbContext<MaterialDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
                o => o.MigrationsAssembly("MyMvcProject")));
```
When dbContext.Database.Migrate() is called the very first time (so when the test db doesn't exist yet), the test db is created but the migration history table is empty !

When dbContext.Database.Migrate() is called the next time (so after test db is created) I get following error:
```
 $exception | {System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'BoardMaterialPriceModel' in the database.    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)    at ....
```

**Comment by ajcvickers** [comment]
@paulvanbladel couple of things to check about "dbContext.Database.Migrate() is applied when a TestServer session is started.":
* Ensure that the context is resolved from a D.I. scope and that scope is disposed.
* Ensure that the migration is finished before the application is allowed to start and any requests get processed. (Or otherwise ensure that the database is migrated once and only once and there are non concurrency issues either from multiple threads on the same server or by multiple servers each attempting to migrate the database.

**Comment by paulvanbladel** [comment]
@ajcvickers Arthur, Thanks a lot. I could solve the issue with your suggestions.
