### ISSUE TITLE
Question: Missing aliases in GroupBy tests

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11339]
Any ideas why there is this difference in generated SQL? Aliases seem to be missing - what am I doing wrong?

     GroupBy_Property_Select_Key_Average

SQL CE:
```
            AssertSql(
                @"SELECT [o].[CustomerID], AVG(CAST([o].[OrderID] AS float))
FROM [Orders] AS [o]
GROUP BY [o].[CustomerID]");

```

SQL Server:
```
            AssertSql(
                @"SELECT [o].[CustomerID] AS [Key], AVG(CAST([o].[OrderID] AS float)) AS [Average]
FROM [Orders] AS [o]
GROUP BY [o].[CustomerID]");

```

**Comment by smitpatel** [comment]
@ErikEJ - Which version of EF Core package?

**Comment by ErikEJ** [comment]
@smitpatel  Sorry, missed that: 2.1-preview1-final

**Comment by smitpatel** [comment]
Alias-ing is added in a recent commit after 2.1.0-preview1. In preview1 packages they did not have alias in SqlServer either.

**Comment by ErikEJ** [comment]
@smitpatel Thanks! Makes sense...
