### ISSUE TITLE
DbUpdateConcurrencyException.Entries only contains one Entry in a split-table scenario

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#11348]
I have a one-to-one relationship between two entities that share the same table, with the PK property being used as the FK between them (so, a split table). If `SaveChanges` throws a `DbUpdateConcurrencyException`, the exception's `Entries` property contains only one of the two entities.

Is this intentional? How does it choose which of the two entities is in the exception?

If this is intentional: does a `DbUpdateException` *ever* have multiple entries?

**Comment by ajcvickers** [comment]
@AndriySvyryd Could you try to find the duplicate for this? I was unable to find it.

**Comment by smitpatel** [comment]
Duplicate of #1002
