### ISSUE TITLE
FromSql: Must use SqlParameters if variable names used inSQL

### ISSUE THREAD

**Issue by eriksendc** [dotnet/efcore#11344]
I've got a stored procedure that I'm calling using `FromSql()`. It has really long parameter names. (I'm very verbose / descriptive.) Initially I was formulating the first parameter to FromSql with the same, full parameter names as I use in the actual proc. When I do that I get an exception with the message "". I found that if I shortened the parameter names to p0, p1, ... etc. then things worked fine. Seems like when y'all concatenate things there's some kind of truncation going on. I'd think you could use up to nvarchar(4000) for whatever you're building up to execute.

```
Exception message: Must declare the scalar variable "@LockedByAdminUserId".
```

### Steps to reproduce

1. Create a table to select from.

````
CREATE TABLE [dbo].[ReviewLock](
	[ReviewLockId] [int] IDENTITY(1,1) NOT NULL,
	[LockedByAdminUserId] [nvarchar](36) NOT NULL,
	[LockedOn] [datetime2](7) NOT NULL,
	[RelatedEntityId] [int] NULL,
	[RelatedEntityType] [int] NOT NULL,
	[RelatedUserId] [nvarchar](36) NULL,
 CONSTRAINT [PK_ReviewLock] PRIMARY KEY CLUSTERED 
(
	[ReviewLockId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
````

2. Create a procedure that has a signature something like this that returns a collection of entities.

````
CREATE PROCEDURE [dbo].[uspReviewGetLock]
	@LockedByAdminUserId NVARCHAR(36),
	@RelatedEntityType INT,
	@RelatedEntityId INT,
	@RelatedUserId NVARCHAR(36)
AS
BEGIN
	SET NOCOUNT ON
	-- my proc has logic... but this would work for repro
	SELECT * FROM ReviewLock
END
````

3. Use FromSql.

````
List<ReviewLock> reviewLocks =
    _applicationDbContext.ReviewLocks.FromSql(
        "EXEC uspReviewGetLock @LockedByAdminUserId, @RelatedEntityType, @RelatedEntityId, @RelatedUserId",
        lockedByAdminUserId, (int)relatedEntityType, relatedEntityId, null).ToList();
````

The solution I found was to use this:

````
List<ReviewLock> reviewLocks =
    _applicationDbContext.ReviewLocks.FromSql(
        "EXEC uspReviewGetLock @p0, @p1, @p2, @p3",
        lockedByAdminUserId, (int)relatedEntityType, relatedEntityId, null).ToList();
````

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.4.4

**Comment by lillo42** [comment]
Try to remove `SET NOCOUNT ON`

**Comment by ErikEJ** [comment]
You must use SqlParameter values or just placholders: https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

**Comment by eriksendc** [comment]
@lillo42 No difference. What's the theory with your comment? I'm curious to learn your thinking / reasoning.

**Comment by eriksendc** [comment]
Hi @ErikEJ 

In fact I had already tried that, and doing so led me to theorize about the possible truncation that I mentioned in my original issue description. If I execute this...

````
List<ReviewLock> reviewLocks =
    _applicationDbContext.ReviewLocks.FromSql("EXEC uspReviewGetLock @LockedByAdminUserId, @RelatedEntityType, @RelatedEntityId, @RelatedUserId",
                new[] {
                new SqlParameter("@LockedByAdminUserId", lockedByAdminUserId),
                new SqlParameter("@RelatedEntityType", (int)relatedEntityType),
                new SqlParameter("@RelatedEntityId", relatedEntityId),
                new SqlParameter("@RelatedUserId", null) }).ToList();
````

or this...

````
List<ReviewLock> reviewLocks =
    _applicationDbContext.ReviewLocks.FromSql("EXEC uspReviewGetLock @LockedByAdminUserId, @RelatedEntityType, @RelatedEntityId, @RelatedUserId",
                new SqlParameter("@LockedByAdminUserId", lockedByAdminUserId),
                new SqlParameter("@RelatedEntityType", (int)relatedEntityType),
                new SqlParameter("@RelatedEntityId", relatedEntityId),
                new SqlParameter("@RelatedUserId", null)).ToList();
````

Then the message of the exception thrown is...

````
The parameterized query '(@LockedByAdminUserId nvarchar(36),@RelatedEntityType int,@Relat' expects the parameter '@RelatedUserId', which was not supplied.
````

Note how what's quoted in single quotes is truncated.

**Comment by smitpatel** [comment]
@ErikEJ is right. You must use SqlParameter if you are providing own names for parameters.

When you pass in values of parameters as scalar types instead of SqlParameter, we name the parameters for you in @p0, @p1... format. Either you can use those parameters in your query directly as found in your solution in first post. Else you can use placeholder like `{}` from string.Format. We will generate parameter and inject parameter name at correct place in SQL string for you.

If you want to name the parameter as you want in your SQL then you must pass in SqlParameters to indicate what is the parameter name & associated values as you did in last post.

It throws exception from SQL since RelatedUserId parameter has been passed with null value which your stored procedure definition expects to be non-null.

There is no truncation of parameter happening on EF side. The truncation just happen in printing out error message since you could have a lot of parameters in SQL. The main message from the exception is you are passing null value for a required parameter `@RelatedUserId`.
If you check SQL logs you would see EF Core is sending SQL correctly based on how it is written in linq without any truncation of parameter names.

**Comment by smitpatel** [comment]
This section describes in detail, different methods of passing in parameters and how to pass in values. https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters

**Comment by eriksendc** [comment]
@smitpatel @ErikEJ Thank you very much for taking the time to respond today. 

@smitpatel In fact my stored procedure doesn't require non-null values, but I missed a very basic thing from my database programming knowledge of long ago: When passing null via a SqlParameter object you must pass `DBNull.Value` (I had passed plain old `null`.) 

I re-ran my test from my comment above using SqlParameter objects, but for the fourth one using `DBNull.Value` and it worked.

Thanks again, and sorry for the trouble!

Regards,
-Brian

**Comment by smitpatel** [comment]
> When passing null via a SqlParameter object you must pass DBNull.Value (I had passed plain old null.)

Thanks for info. I did not know that 😄
