### ISSUE TITLE
Error while inserting record whose primary key set by AFTER INSERT trigger

### ISSUE THREAD

**Issue by gurutcr** [dotnet/efcore#11342]
I also posted this question in stackoverflow. Here is the link

[https://stackoverflow.com/questions/49370711/error-while-inserting-record-whose-primary-key-set-by-after-insert-trigger](url)

The table has a primary key column (Name=**ID**, Type=varchar) whose value is set by an **AFTER INSERT** trigger. The trigger actually gets the value from another column (Name=**ID_AUTO**, type=smallint, Identity, Increment by 1) and sets it as primary column's value.

When I insert a new record, I pass a dummy value for the ID column which will be replaced by the trigger after insert. But the EF Core tries to select the inserted record's details by using the dummy ID value that was initially passed.

Here is the exception I get:

> DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded

Earlier I was using Entity Framework (Not core) in another project which was using the same SQL table. To avoid this error, I added an additional line of code as explained in the below sections.

Original AFTER INSERT trigger

```
USE [MyDb]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TRIGGER [Lookup].[MyTable_Insert] ON [Lookup].[MyTable] AFTER INSERT        
AS
SET NOCOUNT ON
UPDATE Lookup.MyTable
SET ID = convert(varchar,ID_AUTO)
```
Additional line of code added:

`SELECT CAST(SCOPE_IDENTITY() AS varchar) AS ID`

This took care of the issue in Entity Framework. But this line of code generated another error in EF Core as below.

> InvalidOperationException: The database generated a null value for non-nullable property 'IdAuto' of entity type 'MyTable'. Ensure value generation configuration in the database matches the configuration in the model.

Looking at the query generated by EF Core using SQL profiler, here is what I see.

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Lookup].[MyTable] ([ID], [Active])
VALUES (@p0, @p1);
SELECT [ID_AUTO]
FROM [Lookup].[MyTable]
WHERE @@ROWCOUNT = 1 AND [ID] = @p0;

',N'@p0 varchar(5),@p1 varchar(3),@p0='9999',@p1='Y'
```

So looks like it always try to retrieve the ID_AUTO value by using the initially passed dummy ID value. Executing the same statement using SSMS, there is no error generated. 

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (2.0.2)
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.1

**Comment by AndriySvyryd** [comment]
@gurutcr Unfortunately this is not supported in EF Core. A value cannot be inserted and read at the same time. Usually you wouldn't need to provide values for generated columns, but since ID is the PK a non-default value has to be set.

There are some alternatives you could try:
1. Make ID_AUTO the PK
2. Generate the values on the server from a different object, such as a sequence
3. Generete the values on the client (it should be possible to create one similar to `SqlServerSequenceHiLoValueGenerator`, but that produces strings)
