### ISSUE TITLE
Add a foreign key to an existing table without dropping data

### ISSUE THREAD

**Issue by egmfrs** [dotnet/efcore#11349]
If I add a migration for a new table, then add a migration for altering an existing table to include a foreign key to the new table, it fails because of the existing data. I'm having to seed the foreign table manually, and set a default value of 1 for the foreign key. Is there a best practice way to solve this problem?

**Comment by ajcvickers** [comment]
@egmfrs Can you describe in more detail what you are trying to do and what the problem is? Also, please post the version of EF Core and the database provider that you are using.

**Comment by egmfrs** [comment]
Say you have an Orders table, you record Order ID and Order Date. You build up a few entries in this table. You now decide, it would be good to have an Order Status (Processing / Shipped / Delivered etc.) - So you want to add an OrderStatuses table, and a Foreign Key OrderStatusId to your Orders table. Add migrations for these (adding the table, and then adding the foreign key to that table, configure default value to 1). Update your initilizer code to add rows into the OrderStatuses. Run update database. Watch it explode! EF Core 2.0.0, MS SQL Server 2017

**Comment by bricelam** [comment]
If you make the foreign key column nullable, the existing rows will have null.

If you want the existing rows to point to a default status, you'll need to insert that status into `OrderStatuses` before adding the `OrderStatusId` column to `Orders`.

**Comment by egmfrs** [comment]
@bricelam thank you for this - I wasn't aware of that syntax for inserting data into the migration - I had been using `.Sql("INSERT...");` int he migration.

My question was asking if this is the only way / best practice (to insert seed data manually into the migration) as I have been led to believe that editing the migration file manually is bad practice. I know the default value can be set in an entity configuration `modelBuilder.Property(o => o.OrderStatusId).HasDefaultValue(1);` but can the seed data be successfully set in a configuration file too?
