### ISSUE TITLE
Value comparison issue when mapping isn't one-to-one

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11359]
When updating the Npgsql provider from preview2-30335 to preview2-30366, I started having this test exception:

```
 System.AggregateException : One or more errors occurred. (Unable to cast object of type 'System.DateTimeOffset' to type 'System.DateTime'.) (The following constructor parameters did not have matching fixture data: GearsOfWarQueryNpgsqlFixture fixture)
---- System.InvalidCastException : Unable to cast object of type 'System.DateTimeOffset' to type 'System.DateTime'.
---- The following constructor parameters did not have matching fixture data: GearsOfWarQueryNpgsqlFixture fixture
Stack Trace:

----- Inner Stack Trace #1 (System.InvalidCastException) -----
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.<>c__DisplayClass12_0.<HandleNulls>b__0(Object v1, Object v2)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.GearsOfWarContext.Seed(GearsOfWarContext context)
   at Npgsql.EntityFrameworkCore.PostgreSQL.TestUtilities.NpgsqlTestStore.Initialize(Func`1 createContext, Action`1 seed) in /home/roji/projects/EFCore.PG/test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestStore.cs:line 92
```

I tracked this down to the property `Mission.Timeline`, which is a DateTimeOffset.

PostgreSQL has no data type that corresponds to DateTimeOffset;  the ADO.NET provider does allow reading/writing it to a `timestamptz` (which is a timestamp that's meant to be in UTC), but the default for `timestamptz` is DateTime. So NpgsqlTypeMappingSource maps DateTimeOffset to a mapping who's ClrType which DateTime, and this seems to be triggering the issue.

I'm not sure if you guys have other cases of a non-one-to-one (CLR type X mapped store type Y, which by default is mapped backed to CLR type Z). This worked fine up to now, though, it's the first time I hit a snag.

Let me know if you need any other info.

**Comment by ajcvickers** [comment]
@roji It's always been intended that the CLR type of the mapping match the CLR type of the property it is used for. (Excluding that a type mapping for a non-nullable type can be used for the equivalent nullable type.) However, it has become apparent that the MySQL provider didn't so this, and it now seems that the Postgres provider doesn't do it either. Unfortunately, much of the work on value converters and comparers is dependent on the CLR types matching. At this point I think the best way forward is for providers to update to only return type mappings where the type mapping type matches the CLR type given when the mapping is requested. But we will discuss in triage in case there are other ideas.

**Comment by roji** [comment]
OK, understood. I just worked changed the mappings to have one mapping that does DateTime<->timestamptz, and another that does DateTimeOffset<->timestamptz. The first is used when looking up by ClrType=DateTime and by StoreType=timestamptz (so it's the default in that sense), and the second is used only when looking up by ClrType=DateTimeOffset. This makes the error go away.

I can only see one apparent problem with this - if I have a model with a DateTimeOffset property that happens to have its store type set to timestamptz by the user, the TypeMappingSource has to be made more intelligent - right now a given store type can only have one mapping (and so one ClrType) associated with it, but in this case we have two.

Thanks for your guidance, it may be a good idea to include the MySQL folk in this.

**Comment by divega** [comment]
Reopening so that we can still see this in our next triage.

**Comment by roji** [comment]
OK. Just to add that I changed my mappings to match what @ajcvickers described above and I don't have any issues. The only impact was the need to go over several mapping candidates when doing `FindMapping()` on a string StoreType (with different ClrTypes).
