### ISSUE TITLE
Using stored procedure & EF Core, how to get Id of newly created record ? The insert operation happens inside a stored procedure.

### ISSUE THREAD

**Issue by gitfortee** [dotnet/efcore#11355]
How can i get the Id of newly inserted record. The insert happens via stored procedure.. And i am reading that you have to use `Database.ExecuteSqlCommand` for exec stored procs that perform insert/update/delete.. kind of lost here.. 

thanks!

**Comment by Vasimovic** [comment]
You can use FromQuery or FromSql to return the newly created record

Your stored procedure needs to return the ID 

MS SQL has scope_identity()

**Example**: 
-- Do your insert
select scope_identity() as Id

Or, use the output clause

**Example**:
declare @insertedId as Int

insert TableName (Column1, Column2)
output inserted.Your_ID_Column 
    into @InsertedIdentityID
 values ("abc", 123)

select @InsertedIdentityID as Id

**Comment by gitfortee** [comment]
@Vasimovic it works. thanks. Do you also have an example that shows how to retrieve an output parameter from stored proc.? should i use the SqlParameter to retrieve output parameter values from stored procedure.? thanks!

**Comment by smitpatel** [comment]
@gitfortee - You can use SqlParameter with appropriate type to retrieve value of output parameter from ExecuteSqlCommand or FromSql
