### ISSUE TITLE
An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by livarcocc** [dotnet/efcore#11367]
_From @wh1t3cAt1k on March 20, 2018 18:38_

## Steps to reproduce

- Unpack the following project in VS Code: [CoreRestaurants.zip](https://github.com/dotnet/cli/files/1830653/CoreRestaurants.zip)
- `cd` into the directory
- `dotnet build`
- `dotnet ef dbcontext list`

## Expected  behavior

I see the dbcontexts list or a meaningful error.

## Actual behavior

I see an obscure error
```
Error:
  An assembly specified in the application dependencies manifest (CoreRestaurants.deps.json) was not found:
    package: 'CoreRestaurants', version: '1.0.0'
    path: 'CoreRestaurants.dll'
```
## Workaround

It took me 2 days to figure out that the problem might be in access rights, and running the above stuff with `sudo` fixes the issue.

In hindsight it is surprising how I didn't guess it from the outset, but hey, everything is obvious in hindsight.

My point is that the error could be more descriptive so that people spend less time figuring out what went wrong. Perhaps there should be additional explicit checks made by the tool.

*Note*: the same issue with `dotnet ef migrations list`.

## Environment data

I into the `~/Projects/CoreRestaurants` folder.

I run Mac OS 10.13.2 (17C88).

`dotnet --info` output:

```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

_Copied from original issue: dotnet/cli#8851_

**Comment by livarcocc** [comment]
It is not clear to me if this is coming from EF trying to load the assemblies in the deps.json or if this is the host trying to load assemblies from the deps.json. If the latter, please, move the issue to core-setup.

Assuming it is the former, I am moving this to EF.

**Comment by bricelam** [comment]
Similar to #11320. I suspect the error occurs before any EF code gets invoked..

**Comment by divega** [comment]
This issue was moved to dotnet/core-setup#3965

**Comment by PsMaster** [comment]
Just a comment for whoever is having this problem on VS2017. 
I was running the Scaffold-DbContext from nuget package manager console and was getting the error "An assembly specified in the application dependencies manifest (WhateverProjectName.deps.json) was not found". If you're running this command for another project in a solution (most likely a library) you have to ensure the startup project is the one you are running the Scaffold-DbContext  command for. Just choosing the Default project on nuget package manager is not enough.

**Comment by HQJaTu** [comment]
> Just a comment for whoever is having this problem on VS2017.
>  you have to ensure the startup project is the one you are running the Scaffold-DbContext command for. 

Thank you for this information.
Obviosly I never have my DB-models as a startup project. Selecting Default project from Package Manager Console won't solve the problem.

**Comment by JoeGC1969** [comment]
> Just a comment for whoever is having this problem on VS2017.
> I was running the Scaffold-DbContext from nuget package manager console and was getting the error "An assembly specified in the application dependencies manifest (WhateverProjectName.deps.json) was not found". If you're running this command for another project in a solution (most likely a library) you have to ensure the startup project is the one you are running the Scaffold-DbContext command for. Just choosing the Default project on nuget package manager is not enough.

This saved my day, thanks!

**Comment by armin1980m** [comment]
> > Just a comment for whoever is having this problem on VS2017.
> > I was running the Scaffold-DbContext from nuget package manager console and was getting the error "An assembly specified in the application dependencies manifest (WhateverProjectName.deps.json) was not found". If you're running this command for another project in a solution (most likely a library) you have to ensure the startup project is the one you are running the Scaffold-DbContext command for. Just choosing the Default project on nuget package manager is not enough.
> 
> This saved my day, thanks!

You save the day. that was the exact issue!
