### ISSUE TITLE
Analyzer: Guidance to help with query parameterization

### ISSUE THREAD

**Issue by xt0rted** [dotnet/efcore#11374]
With EF6 I had to do a refactoring of some of my queries so they would get parameterized and their execution plans cached. Section 4.2 at https://msdn.microsoft.com/en-us/library/hh949853(v=vs.113).aspx talks about this.

It'd be nice if there was one or more analyzers that could help the user out some by pointing out when their method usage might not behave as they're expecting. A good example of this is using the `.Skip(skip).Take(take)` pattern for paging which was in-lining my values instead of using parameters. Once switching to lambdas the query was cached and shared across all pages.

I haven't moved to EF Core yet so I'm not sure how this behaves compared to EF6. If this has been "fixed" then great, otherwise some analyzers could go a long way here I think.

**Comment by SSkovboiSS** [comment]
This was fixed in EF Core, see #3726

**Comment by divega** [comment]
@xt0rted feel free to suggest other analyzers that you think would be useful.
