### ISSUE TITLE
Owned type with sharing primary key default constraint

### ISSUE THREAD

**Issue by rkdrnfds** [dotnet/efcore#11381]
```
dbContext<User>().HasKey(u => UserId).HasDefaultValueSql("gen_random_uuid()")
dbContext<User>().OwnsOne(Inventory);
dbContext<User>().OwnsOne(House);
```
Inventory and House does not have UserId property explicitly. 
In this situation, if I do not specify 
```
dbContext<User().OwnsOne(Inventory)
    .Property("UserId").HasDefaultValueSql("gen_random_uuid()");
```
For every owned type User owns, it generates error like this,

```
Unhandled Exception: System.InvalidOperationException: 'Inventory.UserId' and 'House.UserId' are both mapped to column 'UserId' in 'Users' but are configured to use different default values ('gen_random_uuid()' and '').
```

I thought it would be enough to specify constraints for the owner type only. (User)
Why should I specify default constraint for every owned type User have. 
It would be better if owned type inherits primary key constraint from owner type.

**Comment by smitpatel** [comment]
Duplicate of #9771 

More specific duplicate as this problem #10308

It is fixed in nightly builds.
