### ISSUE TITLE
Conventions: Internal code usage in provider

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11404]
At presence when provider has to define their own convention they have to use
- Define convention using interface from internal, or
- Define convention by overriding one of the existing EF Convention (ValueGeneration/DbFunction/MaxIdentifierLength)
- Implementing convention requires access to InternalMetadataBuilder types
- To register new convention they have to override ConventionSetBuilder & Dependencies (Relational/Core or both)
- To register convention set builder in DI use IConventionSetBuilder which is also internal

It may also require full access to metadata.

**Comment by ajcvickers** [comment]
This is deeply coupled to #214, but rather than closing as a duplicate we are keeping both issues open so that we don't miss that this is an internal code issue for providers, which conceptually could be potentially partly addressed without full public conventions,

**Comment by ajcvickers** [comment]
Closing in favor of #214

**Comment by ajcvickers** [comment]
Re-opening as a place to track specific data about the internal types still being used:

Annotations Framework
- InternalEntityTypeBuilder
- RelationalAnnotationsBuilder
- ~ConfigurationSource~ Public
- InternalIndexBuilder
- InternalModelBuilder
- InternalPropertyBuilder
- InternalKeyBuilder
- InternalRelationalBuilder
- RelationalForeignKeyBuilderAnnotations
- RelationalPropertyBuilderAnnotations
- RelationalIndexBuilderAnnotations
- RelationalKeyBuilderAnnotations
- RelationalEntityTypeBuilderAnnotations
- RelationalAnnotationsBuilder
- Property
- DbFunction
- Property
- EntityType
- ~CoreAnnotationNames~ Public
- ConventionalAnnotation
- ~GetAllBaseTypesInclusive~ Public
- ~FindPrincipal~ Public
- ~FindSharedTableRootPrimaryKeyProperty~ Public
- ~GetDeclaredProperties~ Public
- ~GetDeclaredIndexes~ Public

Conventions
- DatabaseGeneratedAttributeConvention
- IModelInitializedConvention
- RelationalConventionSetbuilder
- RelationalConventionSetBuilderDependencies
- CoreConventionSetBuilder
- CoreConventionSetBuilderDependencies
- IConventionSetBuilder
- RelationalMaxIdentifierLengthConvention
- RelationalMaxIdentifierLengthConvention
- RelationalDbFunctionConvention
- IBaseTypeChangedConvention
- IIndexAddedConvention
- IIndexUniquenessChangedConvention
- IIndexAnnotationChangedConvention
- IPropertyNullabilityChangedConvention
- IPropertyAnnotationChangedConvention
- IEntityTypeAnnotationChangedConvention
- IKeyAddedConvention
- RelationalValueGeneratorConvention
- IModelInitializedConvention
- ValueGeneratorConvention
- RelationalDbFunctionConvention

**Comment by roji** [comment]
FYI just hit an internal warning on RelationalAnnotationsBuilder (referenced in NpgsqlPropertyBuilderAnnotations, NpgsqlModelBuilderAnnotations) while porting to preview5.

**Comment by ajcvickers** [comment]
Closing in favor of #15695
