### ISSUE TITLE
Query: Internal code usage in providers

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11406]
RelationalQueryCompilationContext has properties which providers may need to override to specify lateral join support or max identifier size.
ILinqOperatorProvider & both implementations of it + QCCDependencies are internal.

Apart from that, providers uses MemberAccessBindingExpressionVisitor.GetPropertyPath to check binding.
+ few methods from (Relational)ExpressionExtensions.

**Comment by ajcvickers** [comment]
Progress update:
- ~FindProperty(this expression, type)~ Public
- ~MemberAccessBindingExpressionVisitor.GetPropertyPath~
- QueryCompilationContextDependencies
- ILinqOperatorProvider
- LinqOperatorProvider
- AsyncLinqOperatorProvider
- LiftExpressionFromSubquery
- ~RemoveConvert~ Public
- IParameterBindingFactories (referenced in PropertyInfoExtensions)

**Comment by ajcvickers** [comment]
Closing in favor of #15695
