### ISSUE TITLE
Metadata: Internal code usage in provider

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11405]
To run conventions/define annotations/validate model, provider needs access to metadata items (including builder), configuration source, various extension methods to get metadata info.

Further annotations framework uses internal metadata builders.
It uses RelationalAnnotationsBuilder as base & if there is no provider specific annotations builder then provider needs to call into RelationalMetadataBuilderAnnotations. All of those are internal.

**Comment by ajcvickers** [comment]
Closing in favor of #214
