### ISSUE TITLE
Could not find type mapping for column 'dbo.xxxx' with data type 'geometry'. Skipping column.

### ISSUE THREAD

**Issue by patelneel1994** [dotnet/efcore#11418]
I have a SQL table for which I want to generate a model in my .Net Core API application. I have 5 columns and one of the column types has Geometry points for drawing a polygon.  
I use below command to generate .CS class model. Everything works find except Scaffold-DBContext skps the column that is type Geometry. 
`PM> Scaffold-DbContext "Server=SQLServer;Database=Corporate;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -force -OutputDir Modelsss`

### Further technical details
EF Core version: 1.1.5 (Microsoft.EntityFrameworkCore.SqlServer.Design)
Database Provider: 2.0.2
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ErikEJ** [comment]
In version 2.0 you cannot map to Geometry type in EF Core - in 2.1 it is possible when using full .NET Framework

**Comment by patelneel1994** [comment]
Thank you for you quick response. 

**EF Core - in 2.1 it is possible when using full .NET Framework**
EF Core - 2.1 hasn't been release, correct? Do you know when Geometry type will be supported for .Net Core application? 

Thanks
