### ISSUE TITLE
How to use case-insensitive query with Sqlite provider ?

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#11414]
I'm not sure if I remember wrongly, 
I see the  `COLLATE NOCASE` append in the sql query very long time ago (may be not `COLLATE NOCASE`,but something else , all I remember is my query is case insensitive),

but recently I use Sqlite again , and it is  case sensitive , and I can not compare an "Email" filed with `x.Email == myvariable`

**Comment by bricelam** [comment]
Some users have been successful by configuring the property like this: (although it's certainly not how the API was intended to be used)
``` csharp
modelBuilder.Entity<X>().Property(x => x.Email).HasColumnType("TEXT COLLATE NOCASE");
```

**Comment by bricelam** [comment]
Currently, the only way to do it per-query (not configuring the column) is by using raw SQL:
``` csharp
db.X.FromSql($"SELECT * FROM X WHERE Email = {myvariable} COLLATE NOCASE").Where(...);
```

**Comment by bricelam** [comment]
Also note, SQLite only performs case-insensitive comparisons of ASCII characters. Override the default to include all Unicode characters:
``` csharp
var connection = (SqliteConnection)db.Database.GetDbConnection();
connection.CreateCollation("NOCASE", (x, y) => string.Compare(x, y, ignoreCase: true));
```

**Comment by John0King** [comment]
@bricelam thanks a lot,  
but, I don't understand your last code,   what is  `SqliteConnection.CreateCollation()` ? 
and may I ask , does Sqlite "case-insensitive" in EF 1.x ?

**Comment by bricelam** [comment]
The last code listing uses SQLite's ADO.NET APIs (the layer underneath EF Core) to replace SQLite's built-in `NOCASE` comparison with .NET's implementation.

Yes, my first two comments also apply to EF Core 1.x.

**Comment by John0King** [comment]
@bricelam  Thanks again. 
> to replace SQLite's built-in NOCASE comparison with .NET's more complete implementation. 

Is that because Sqlite's ADO.Net provider is also the database engine  so it can do that ?  otherwise AFAK doing comparison in "client" side is pointless .

**Comment by bricelam** [comment]
SQLite is an in-process database. The snippet above works by passing a function pointer to SQLite that it can use to invoke the lambda. So technically, it *is* happening "on the server".

**Comment by bricelam** [comment]
This is different from EF's client-evaluated queries where extra data may be retrieved from the server so additional processing can be done before returning the final result set.

**Comment by bricelam** [comment]
I walk through the differences between client-eval and passing pointers to SQLite in my [SQLite & EF Core: UDF all the things!](http://www.bricelam.net/2017/08/22/sqlite-efcore-udf-all-the-things.html) post.

**Comment by ajcvickers** [comment]
@bricelam Can this be closed?

**Comment by bricelam** [comment]
Yep. @John0King feel free to continue the conversation here even though the issue is closed.

**Comment by nbelley** [comment]
Quick question, when should I execute the code:

```
var connection = (SqliteConnection)db.Database.GetDbConnection();
connection.CreateCollation("NOCASE", (x, y) => string.Compare(x, y, ignoreCase: true));
```

And, is it enough or I also need to use the .HasColumnType("TEXT COLLATE NOCASE"); trick?

**Comment by TMendys** [comment]
I have had luck with using `EF.Functions.Like()` and it works. You add the property and the searchstring like this: `EF.Functions.Like(person.LastName, $"%{searchString}%")`.

**Comment by roji** [comment]
For anyone seeing this, since this issue was opened, EF Core added support for collations - see [this page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity).

**Comment by fineboy0407** [comment]
Great! I've learned something new.
Thanks for your efforts.

**Comment by winstond** [comment]
I set a collation for a column to "NOCASE" and confirmed in SQLiteStudio that it was set properly.
However when doing a .Where, I'm still finding the results are coming back case sensitive (If I search for "a" I don't get things that have "A").
Is that an issue with .Where?

**Comment by roji** [comment]
@winstond please open a new issue with a minimal, runnable repro so we can see what exactly you're doing.
