### ISSUE TITLE
How to create a datetime column for both sql server and mysql with no precision after seconds

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#11416]
My entity:

    mb.Entity<DTOCategoryTag>().Property(x => x.CreatedDate).HasColumnType("datetime2(0)");

Desired datetime is no precision after seconds i.e. MM/dd/yyyy hh:mm:ss

MySQL migration (sytax error on table create):

    CreatedDate = table.Column<DateTime>(type: "datetime2(0)", nullable: false),

SQL Server migration (works):

    CreatedDate = table.Column<DateTime>(type: "datetime2(0)", nullable: false),

**Comment by ajcvickers** [comment]
@sam-wheat There are multiple parts to this:
* First, find the appropriate data type to use for each database engine. (I don't know if there is a MySQL type that supports what you want. If there isn't, then there isn't anything EF can do. Let's assume there is and continue.)
* Next, add conditional code in OnModelCreating that will configure the model differently for each provider. Something like:
```C#
modelBuilder
    .Entity<DTOCategoryTag>()
    .Property(x => x.CreatedDate)
    .HasColumnType(Database.IsSqlServer() ? "datetime2(0)" : "somemysqltype");
```
* Follow the guidance on [handling migrations with multiple database providers](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers).

**Comment by sam-wheat** [comment]
@ajcvickers Thanks very much.
