### ISSUE TITLE
Not found the executable file corresponding to the command "dotnet-ef".

### ISSUE THREAD

**Issue by tttrrryyyyeer** [dotnet/efcore#11417]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.2" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

</Project>

**Comment by ralmsdeveloper** [comment]
Look this: https://github.com/aspnet/EntityFrameworkCore/issues/8996#issuecomment-359484467

Can you post your ".csproj" here?

**Comment by rhires** [comment]
This is extremely easy to miss: 
![image](https://user-images.githubusercontent.com/12577765/37882885-f0c34c02-3074-11e8-8a31-4feaba823ffb.png)
I wish this little bit was installed by some CLI command or other. I had this exact problem, and discovered this gem by reading the docs _very carefully_. I hope this helps!

**Comment by ajcvickers** [comment]
@bricelam Can this be closed?
