### ISSUE TITLE
Wrong data type used by efcore on sqlite databases generated by migrations

### ISSUE THREAD

**Issue by Dinokin** [dotnet/efcore#11468]
basically sqlite databases generated by efcore migrations determines decimal values as TEXT instead of NUMERIC. this breaks linq functions like Max(), since it wont return the actual maximum value.

**Comment by bricelam** [comment]
Xref: aspnet/Microsoft.Data.Sqlite#498

**Comment by bricelam** [comment]
Related to #10534

**Comment by bricelam** [comment]
When #10642 is fixed, this will get you close to what you want:
``` csharp
var max = db.Entities.Max(e => (double)e.Decimal);
```
But of course, converting from `decimal` to `double` is lossy so the best thing will always be to calculate on the client:
``` csharp
var max = db.Entities.Select(e => e.Decimal).ToList().Max();
```
