### ISSUE TITLE
dll for taking picture using c# Core 1.1

### ISSUE THREAD

**Issue by IsaaasI** [dotnet/efcore#11470]
I am looking to dll library for capture a picture using Laptop camera or external camera and save it in database server . I am using VS 2017 Core 1.1

Any Suggestion dll or code that will help me ?

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: MySQL
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by bricelam** [comment]
.NET Core is primarily for server workflows at the moment, you'll have more luck using [UWP](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/camera), [Xamarin](https://developer.xamarin.com/recipes/android/other_ux/camera_intent/take_a_picture_and_save_using_camera_app/), or [.NET Framework](http://www.emgu.com/wiki/index.php/Camera_Capture_in_7_lines_of_code).

**Comment by Eilon** [comment]
This type of question might be better suited to a site such as StackOverflow.
