### ISSUE TITLE
AsMigrationsEnabled() API usability

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1149]
In order to access migrations functionality currently one has to call `context.Database.AsMigrationsEnabled()` to obtain an instance of `MigrationsEnabledDatabase`. Although one could argue that having this API is  more correct than exposing the functionality directly on RelationalDatabase, it is hard for me to see how it helps in usability and discoverability. The name itself looks very strange (`AsMigratable()` could be a bit better, although it is still strange), but I think we should revisit whether we could define functionality like `ApplyMigrations()` as an extension method over a more general type.

**Comment by rowanmiller** [comment]
Covered by https://github.com/aspnet/EntityFramework/issues/1525 (going back to AsRelational)
