### ISSUE TITLE
Name Navigation Property Key with an Attribute

### ISSUE THREAD

**Issue by WilliamABradley** [dotnet/efcore#11509]
It would be great to be able to easily name a Navigation Property, rather than the Automatically generated key, which goes by {typeName}{typeKeyPropertyName}. This produces a key that looks out of place in any model.

Two ways that could fix this is:

1.  Create a NavigationPropertyAttributeClass, with an Argument for the Shadow Property Name. You could then customise the Navigation property on the same attribute, such as specifying if it is a Zero or One to Many, One to One or Zero to One, etc.

2. Let us customise the Navigation Property naming scheme globally, so that we can remove the Type Name prefix on the Property.

**Comment by divega** [comment]
@WilliamABradley have you tried System.ComponentModel.DataAnnotations.Schema.ForeignKeyAttribute.
