### ISSUE TITLE
Move ApiConsistencyTestBase to specification tests

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11500]
I may have asked this before, but why is ApiConsistencyTestBase (and possibly others) not part of the specification tests? Right now, in order to take advantage of this very useful test, I must copy the entire class over (and remember to do so for each update)

**Comment by AndriySvyryd** [comment]
These tests don't test any functionality and we don't want to impose any rules at this level. But we'll look into a way of sharing them so any providers that do want to run them can do it without copy-pasting.

**Comment by ErikEJ** [comment]
Thanks, @AndriySvyryd

**Comment by roji** [comment]
BTW @ErikEJ you question led me to do [this huge PR](https://github.com/npgsql/efcore.pg/pull/1354), so thanks :)
