### ISSUE TITLE
ToTable name is not respected when it comes after OwnsOne

### ISSUE THREAD

**Issue by AlQuraian** [dotnet/efcore#11512]
Describe what is not working as expected.
I noticed that my database update creates a duplicate table of 2 names, one pluralized and one singular.

I found out that doesn't have the expected behavior:
```
private void Configure(EntityTypeBuilder<Table> builder)
        {
            builder.OwnsOne(ab => ab.Prop)
                .ToTable(nameof(Table));
        }
```

Where's the following doesn't create the pluralized version (the expected behavior):

```
private void Configure(EntityTypeBuilder<Table> builder)
        {
            builder.ToTable(nameof(Table))
                .OwnsOne(ab => ab.Prop);
        }
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.0.2
Operating system: Windows 10 64-bit
IDE: Visual Studio 2017 15.6.3
Entity Framework Core .NET Command Line Tools: 2.0.1-rtm-125

**Comment by divega** [comment]
@AlQuraian By convention, in order to decide the name of the table for a given type X, EF Core uses the name of a property of type `DbSet<X>` property on your DbContext. 

E.g. if the DbContext looks like this, the name of the table will be 'Xs':

``` csharp
public class MyContext : DbContext
{
   public DbSet<X> Xs { get; set; }
   /// etc
}
```

That seems to completely explain the behavior you are seeing, but let me know if anything needs clarification.

**Comment by AlQuraian** [comment]
@divega I know that this is the convention. However, I know that ToTable() is used to override that conventions. Which doesn't work on one of the given examples I mentioned earlier.

**Comment by smitpatel** [comment]
@AlQuraian - When you put `ToTable` call after builder (as in case 2), you are configuring table name for `Table` entity in database. That would override whatever name you have given to your DbSet property. By convention Owned type goes to same table as owner type hence there is just one table with singular name.

When you call `ToTable` after `OwnsOne` then you are actually configuring table name for owned entity and not for owner entity. So your owner entity `Table` takes same name as DbSet (plural one) and your table name configuring is actually overriding the convention which puts owned entity in same table. So now your owned entity will be stored in different table (singular name). Hence you got 2 tables with singular & plural names.

**Comment by AlQuraian** [comment]
@smitpatel Aha that makes sense. Thanks a lot for explaining that!
