### ISSUE TITLE
Expected release date for EF Core 2.1?

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#11528]
Please let us know the expected release date of EF Core 2.1. In the roadmap, its mentioned that final release on the second calendar quarter of 2018.

How can I track this?

**Comment by tuespetre** [comment]
Mind you I have no authority, but I'm going to guess that it will be around the time of the Build conference. Big updates like these are usually released along with some kind of event like that.

**Comment by Eilon** [comment]
Hi folks, the public roadmap for ASP.NET Core and EF Core with schedule is listed here: https://github.com/aspnet/Home/wiki/Roadmap. It's currently stated as "Q2 2018", so expect April/March/June.
