### ISSUE TITLE
SQLite: Translate Guid.NewGuid()

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#11520]
It should be OK to translate this to `randomblob(16)`...
...but it may not have the same guarantees and we should make sure it will be safe to do.

**Comment by divega** [comment]
Maybe we can tell SQLite to call back into Guid.NewGuid() as a mapped function.

**Comment by bricelam** [comment]
Looking into this, `randomblob(16)` should not be used to generate UUIDs since it doesn't comply to the standard and could result it collisions.

I'm also starting to doubt there's any real value in generating Guid values on the server instead of the client.

Closing as won't fix, but if you have a scenario for this, please let us know .

**Comment by bricelam** [comment]
SQLite 3.31.0 adds the uuid() function to do this.

**Comment by bricelam** [comment]
SQLite 3.31.0 added an *optional* extension with a function to do it. It is not enabled by default in SQLite.

**Comment by roji** [comment]
FWIW in PG UUID generation is also available via [an optional extension](https://www.postgresql.org/docs/current/uuid-ossp.html) (even if the uuid type is part of core). When using EFCore.PG, it's the user's responsibility to specify that the extension should be set up etc.

**Comment by groege** [comment]
> SQLite 3.31.0 added an _optional_ extension with a function to do it. It is not enabled by default in SQLite.

IMHO Sqlite should be identical for all platforms - how about including it for all platforms in the nuget packages.
If someone wants to use another sqlite version there could just be a function to supply your own lib.

I think this would have multiple advantages, including a consistent functionality everywhere and the inclusion of all optional extensions.

Hope I'm not writing nonsense here ^^

**Comment by ajcvickers** [comment]
Note from triage: there is no good translation on SQLite.
