### ISSUE TITLE
EF Core to implement lazy loading as it was done in EF 6

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#11536]
I have two entity classes: Gage and Status, and the DbContext (this is pseudo code). I can create a database and fill it with sample data with no problem. However, when I load sample gages from the database using the code shown below I get Gages that have Status and then that Status has its Gages navigation property filled. I have seen lazy loading detailed here

https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading

We are not using proxies nor did we use proxies when using EF 6, because we do not need tracking of our entities. This would then lead us to use lazy-loading without proxies, which would require us to inject ILazyLoader  into over one hundred entities and related properties. Anyone who has EF 6 code first database would need to make that change if they don't use tracking.

In order to minimize code change for deveoplers migrating to EF Core, could EF Core behave the way EF 6 did. If its not "Include"(ed) then honor the virtual navigation property
and don't load it. Otherwise it seems my only simple solution is to say use tracking and ignore it. 

Is there another way that I am missing here.

Code to load data:
	try
	{
		using ( var context = new MyContext() )
		{
			res =
				( from c in
						context.Gages.
							Include ( "Status" )
					select c ).ToList ();
		}

	}
	catch ( Exception ex )
	{
		throw ex;
	}

Entities

`    [Table("Gages", Schema = "MYSCHEMA" )]
	class Gage
	{
        #region Properties

		[Key]
        [System.Runtime.Serialization.DataMember]
		
        public virtual int Gage_RID
        { get; set; }

		[Required]
        [StringLength(255)]
        [System.Runtime.Serialization.DataMember]
		
        public virtual string Gage_ID
        { get; set; }

        [System.Runtime.Serialization.DataMember]
		
        public virtual int Status_RID
        { get; set; }
		
		#endregion
		
        #region Navigation Properties
		
        [System.Runtime.Serialization.DataMember]
        public virtual Status Status
        { get; set; }
		
        #endregion
		
	}

    [Table("Status", Schema = "MYSCHEMA" )]
	public class Status
	{
        #region Properties

        [Key]
        [DatabaseGenerated ( DatabaseGeneratedOption.Identity )]
        [System.Runtime.Serialization.DataMember]
		
        public virtual int Status_RID
        { get; set; }
        
        
        [Required]
        [StringLength(255)]
        [System.Runtime.Serialization.DataMember]
		
        public virtual string StatusName
        { get; set; }

        #endregion
		
        #region Navigation Properties
		
        [System.Runtime.Serialization.DataMember]

        public virtual ICollection<Gage> Gages
        { get; set; }
		
        #endregion
	}

    public partial class MyContext : DbContext
    {
        public virtual DbSet<Gage> Gages
        { get; set; }

        public virtual DbSet<Status> Status
        { get; set; }

	}
`

**Comment by tangdf** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/3aa82151f8b14575875b419758e6deb2ee7cf497/src/EFCore.Proxies/ProxiesExtensions.cs#L35-L40

```csharp
public class NorthwindContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
           
            optionsBuilder.UseSqlServer('******');
            
            optionsBuilder.UseLazyLoadingProxies();
            
            base.OnConfiguring(optionsBuilder);
        }

    }
```

Call the extension `UseLazyLoadingProxies` method.

**Comment by divega** [comment]
@dgxhubbard I believe the only problem might be that you didn't know that in EF6 you were using proxies but in EF Core 2.1 you do. The package dependency and the very small code that you need to add (i.e. `UseLazyLoadingProxies`) in EF Core 2.1 to enable the feature is by-design.
