### ISSUE TITLE
Oracle: User defined column type shredding causes unexpected results

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11558]
Test `Can_use_decimal_and_byte_as_identity_columns` has
```C#
modelBuilder
    .Entity<NumNum>()
    .Property(e => e.Id)
    .HasColumnType("number(18, 0)")
    .UseOracleIdentityColumn();
```
Where `NumNum.Id` is of type decimal. We shred `number(18, 0)` into parts making store type = number, precision = 18, scale = 0. Just `number` maps to integer in Oracle so we use IntTypeMapping and apply decimal to int converter. Which throws exception with value generation.

In Oracle, `number` is used for multiple different sized types based on parameter (count & values).
`number` -> int
`number(3)` -> byte
`number(10)` -> int
`number(19)` -> long
`number(18,0)` -> decimal

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
