### ISSUE TITLE
EF  Context  doesn't fetch latest data from DB

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/efcore#11573]
@smitpatel @AndriySvyryd 

I'm using .Net Core API 2.0 that gets data from DB using EF core 2.0 , have a simple query to fetch data form a table which doesn't get the latest on the table but always returns previous results that I got. 

injecting context in startup and pass it in the constructor. 

**in Startup**
            services.AddDbContext<CBContext>(options => options.UseSqlServer(sqlConnectionString), ServiceLifetime.Scoped);

**In Data ccess class,**

     public ExternalDataAccess(IMapper mapper, IConfigurationRoot config, CBContext context)
        {
            _mapper = mapper;
            _config = config;
            cbContext = context;
        }

getEntityData() Method

cbContext.Entity.Where("condtion"); 

Does EF caches the result ? and how to disable cahing the results? i see the query being sent to 
DB.

**Comment by ajcvickers** [comment]
@arunprasathv Typically the DbContext instance should be used for one unit-of-work. In a web request, that often maps to a single request. However, if a single request is performing multiple different operations, then using a transient lifetime may be more appropriate.

If there are cases within a single unit-of-work that you need to re-query the database to refresh values from the database, then consider using `context.Entry(foo).Reload`.

**Comment by arunprasathv** [comment]
@ajcvickers  Thanks for the update. I've fixed the issue using options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking) which always gets data from DB.
