### ISSUE TITLE
Possible Issue with Change Tracker Caching Entity State EF Core 2.0.2

### ISSUE THREAD

**Issue by skimedic** [dotnet/efcore#11612]
When pulling the Entries from the change tracker, state isn't updated properly. I have this test:

```C#
        [Fact]
        public void ShouldTrackChangesByDefault()
        {
            Product prod = _context.Product.First();
            
            List<EntityEntry<Product>> entries =
                _context.ChangeTracker.Entries<Product>().ToList();
            
            Assert.Single(entries);
            
            var name = prod.Name;
            prod.Name = "foo"; 
            
            Assert.Equal(name, 
                entries[0].OriginalValues[nameof(Product.Name)].ToString());
            
            Assert.Equal(prod.Name, 
                entries[0].CurrentValues[nameof(Product.Name)].ToString());
            
            Assert.Equal(EntityState.Modified,entries[0].State);
        }
```
This fails n the last asset - state is reported as Unchanged.

However, if I access the state, it then gets properly reported as Modified, as in this test:
```C#
        [Fact]
        public void ShouldTrackChangesByDefault()
        {
            Product prod = _context.Product.First();
            
            List<EntityEntry<Product>> entries =
                _context.ChangeTracker.Entries<Product>().ToList();
            
            Assert.Single(entries);
            
            var name = prod.Name;
            prod.Name = "foo"; //TODO: Log issue with EF Core Team 05_07
            
            Assert.Equal(name, 
                entries[0].OriginalValues[nameof(Product.Name)].ToString());
            
            Assert.Equal(prod.Name, 
                entries[0].CurrentValues[nameof(Product.Name)].ToString());

            //added this line and it fixes the test
            var foo = _context.Entry(prod).State;
            Assert.Equal(EntityState.Modified,entries[0].State);
        }
```
Is this by design, am I doing something stupid, or is this an issue?

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

### Further technical details
EF Core version: 2.0.1 and 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.5
[PossibleBugSample.zip](https://github.com/aspnet/EntityFrameworkCore/files/1896115/PossibleBugSample.zip)

**Comment by ajcvickers** [comment]
@skimedic This is because in order to know whether or not a property has been changed, EF needs to run DetectChanges, which does the diff to determine what has changed. This can be quite expensive, and so EF only calls it automatically as part of some top-level methods. In this case, it is called for Entry and Entries, but it is not called every time you access a property through the entry due to the perf cost. There are some [blog posts that describe DetectChanges in detail for EF6](https://blog.oneunicorn.com/2012/03/10/secrets-of-detectchanges-part-1-what-does-detectchanges-do/), and the concepts are basically the same for EF Core.

**Comment by skimedic** [comment]
@ajcvickers Thank you for the explaination. I figured there was a reason for it.
