### ISSUE TITLE
Allow query generation without execution

### ISSUE THREAD

**Issue by neurospeech** [dotnet/efcore#11625]
IQueryable<Products> q = db.Products.Where( p => p. ..... );

         DbCommand command = q.ToCommand();

It is so helpful to simply change command to convert it into `Update`, `Delete`, `Merge`, `Insert Select`.

Current variants of getting `DbCommand` via reflection is incomplete and requires non testable overheads. Some form of DbCommand does not returns parameters associated, so we can't execute them against database.

Reason, we don't want to use stored procedure for bulk operations as they are disconnected and non testable in `in-memory` context.

By using this `DbCommand` we can easily create testable extensions for various SQL operations which are out of EF next scope !!!

**Comment by neurospeech** [comment]
@ajcvickers 

The most important one is "SELECT INSERT".

Example, we need to send email notifications to many people who fulfill certain conditions such as schedule, their choices etc.

Here is some code,

          IQueryable<Account> pq = db.Accounts.Where( a => .... lots of conditions with many inputs ... );

          var sq = pq.Select( a => new EmailRecipient { 
                  EmailID = id, 
                  Name = a.Name, 
                  Email = a.EmailAddress });
          foreach(var ea in sq) {
                  // add recipients..
                  email.Recipients.Add(ea);
          }

This code is slowest in nature, for large datasets, for 1000s of email recipients, it turns out this is really not the way we should write code. 

Basically `Select` returns in some sort of `SELECT Name, Email FROM .... ` conditions, All I can do is, change command text to `INSERT INTO EmailRecipients (SELECT EmailID, Name, Email FROM ...)` and this code becomes single insert query that runs into server. And for unit testing, I can simply invoke expression and add it in context.

Alternative problem is, I can certainly create stored procedure and call it, but that breaks unit testing, while we are developing, we are changing filters and filters written stored procedures are not unit testable under .Net unit testing without writing too much of code.

In most cases, we don't need multiple DbCommands as we will not be using inline projections. 

So you can certainly create a method which will result in single DbCommand, for multiple commands, you can throw exception that it is not supported.

For bulk delete, bulk update and bulk select insert (this is not sqlcopy), we don't want to retrieve data in memory at all, we just want to execute query remotely which is testable.

If I have access to DbCommand, I can easily write an extension which I can customize for in memory and use DbCommand for live database, thus I can make sure my logic of filter is 99% accurate.

**Comment by smitpatel** [comment]
Sounds like https://github.com/aspnet/EntityFrameworkCore/issues/795

**Comment by neurospeech** [comment]
@smitpatel no it is not same as #795 , It does not address `SELECT INSERT` and this is useful for developing extensions which can support things like #795 but not limited only to bulk insert.

**Comment by sdanyliv** [comment]
@neurospeech, just for statistic. How often you have to create workarounds via stored procs or write raw SQL?

**Comment by neurospeech** [comment]
@sdanyliv Quite often (20% of all operations), initially when database was smaller, approx 1000 users, it didn't matter because most such queries would often finish in 1 second. But going beyond 100,000 users, many operations now take few seconds.

We eventually did switch to stored procedures, but it is really not testable, the worst part is versioning in stored procedure, often we have a staging, beta and production. Staging has separate database but we also have beta and production connecting with same live database for users to experience new features. Here comes multiple named stored procedure and lot of glue code which is not testable unless we set up sql localdb, and it is painfully slow.

Whole idea is to avoid stored procedure and use full featured LINQ to generate powerful business logic.

I am surprised that EF core is ignoring basic performance of bulk queries since couple of years now. But lack of DbCommand is not allowing others to create extensions. I have seen how bulkly other EF extensions are just because lack of this feature. Lot of reflection which breaks in next build of EF.

**Comment by sdanyliv** [comment]
That’s why i have left EF many years ago. Bulk operations MUST BE in framework that forced by Microsoft as the best and recommended way to access to database. Real projects shows that EF is good for prototyping - then it becomes a mess of workarounds.

**Comment by ajcvickers** [comment]
Triage: Putting this on the backlog as a more general issue to allow a query to be generated without executing it. The result of this would be whatever is useful in using the generated query, which may be a collection of DbCommands among other things, or may be some other structure altogether.

**Comment by AndriySvyryd** [comment]
@ajcvickers Isn't this fixed by https://github.com/dotnet/efcore/commit/dc1e8115b1fccba9e20fb53b9961073b9406767f ?
