### ISSUE TITLE
DbMigration.CreateStoredProcedure does not exist on EF Core

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#11626]
I am using EF Core (Code first) and I have a major requirement to include a number of stored procedures.
I dont know hot to add them in my migration scripts as EF6  ```DbMigration.CreateStoredProcedure``` does not exist on EF Core.

What is the alternative way of handling with stored procedures in EF Core Code first?

**Comment by ajcvickers** [comment]
@pantonis One way is to use the `Sql` method to include SQL to generate the stored proc. Another way is to [create your own operation for it](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations).

General stored procedure mapping support is tracked in #245

**Comment by pantonis** [comment]
@ajcvickers I already did that using Sql but is not the more elegant way. The issue that is being tracked on is 4 years old and still not progress :(
