### ISSUE TITLE
Exploratory Testing: Relationships & Graph behavior

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1164]
When working on this consider the following issues we closed and explore if we need to address any part of them for EF7.
- https://github.com/aspnet/EntityFramework/issues/1207
- https://github.com/aspnet/EntityFramework/issues/1206

**Comment by ajcvickers** [comment]
Unassigning this since the person doing the implementation should ideally not do the exploratory testing.

**Comment by AndriySvyryd** [comment]
This should also include testing how easy is to use entities with shadow primary keys
