### ISSUE TITLE
Build a Roslyn-based parser for the Code First model

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11659]
To facilitate tooling/AOT scenarios such as:
* A model visualizer that stays in sync with code edits #1027 
* A refactoring engine for the database where code changes can automatically generate and apply migrations to the database in real-time, always keeping the database and model in sync
* The same kind of thing, but driven by changes from the database into the model
* Entity re-writing for lazy loading #10788
* Compiled models #1906
* Analyzers that detect common mapping issues, unneeded fluent configuration, etc.

It doesn't have to be a perfect parser for many of these scenarios. That is, it does not need to be able to fully recreate the runtime model, it just needs enough information to identify entities and database structure.

Other ideas for things to build on encouraged--please post in comments.

**Comment by anpete** [comment]
As we have often discussed, the hardest part here is incorporating configuration code in OnModelCreating. We may be able to get "good enough" by building an interpreter for said code.

Additional benefits are likely faster design-time ops (no need to build/load).

**Comment by ajcvickers** [comment]
@anpete Yeah, that's what I was thinking. We can recognize common patterns and I think get to a place where most people can use it, even if they need to comply a little bit to a well-known way of doing things.

**Comment by anpete** [comment]
@ajcvickers Agreed. I think one first step is to de-couple CF from reflection. This should be pretty straight-forward - introduce an abstraction for CF metadata consumption.

**Comment by pmiddleton** [comment]
I bet @smitpatel can write this all in 1 line of code :)

**Comment by pmiddleton** [comment]
Something that needs to be watched out for with the real-time migrations would be data loss.  You could quickly screw up your dev data without a way to either back out the change or disable this ability.

**Comment by sam-wheat** [comment]
[If you are in the mood for building a parser please see this.... ](https://www.reddit.com/r/dotnet/comments/8abt2s/will_microsoft_ever_create_a_dbms_that_will/?st=jfx9lfjx&sh=a3b55163)

Just wishful thinking on my part but perhaps one day it will come to pass!

**Comment by ajcvickers** [comment]
Note from triage: Can of worms.
