### ISSUE TITLE
Provide any possible hint about in-memory- or in-sql-execution of queries via Roslyn analyzers

### ISSUE THREAD

**Issue by jongleur1983** [dotnet/efcore#11662]
In a previous project I had several issues with code that was quite slow as it wasn't executed on the Database but client side evaluated by EF (EF6 at that time).
As far as I know LINQ is not (and IMHO can't be) fully supported in the data store, because it can leverage endless complex information from the running code.

Nevertheless I think it would be great to have some indicator for clear cases:
If a certain statement can't be translated to a backend query, that could be issued as a compiler warning/hint/...

With Roslyn this might be possible by a set of analyzers, although I'm not sure how far that approach would work:

Issues I see:

whether translation is possible or not might depend 

- on the specific model
- on the Provider in use

Nevertheless 

At https://docs.microsoft.com/en-us/ef/core/querying/client-eval the example provides one possible issue that could be solved:

- If any statement's lambda contains any call to a function that is not registered and thus can't be mapped, this could issue a warning as it can't be executed server side
- if that applies, any subsequent call that makes use of the result can't be done server side as well - but a suggestion could ask to change order of the queries (as I guess - not sure though) EF breaks server side evaluation once and doesn't reorder the linq query pipeline across boundaries)

- GroupBy up to EF Core 2.1 prerelease according to Allen_Wang1 on the same page in the comments was not supported at all, so any Linq GroupBy could have lead to an issued compiler warning.

With some extensions to providers this could be enhanced even more:
- As providers are not enforced to support any command, providers could be asked to provide an interface that reports the supported functions. With that developers could be given a way to configure "add a hint for functions not supported in any of the given provider(s) ...".

From https://www.thereformedprogrammer.net/entity-framework-core-client-vs-server-evaluation/ I took another point that falls into the same category:

If we have some LINQ query on a EF context, and at some intermediate stage there is a method that can't be server side evaluated, I guess (see the first second bullet point above) EF is going to fall back to client side evaluation as soon as there's a non-mapped runtime/client side object involved.
In that case the query often can be re-ordered to provide some more help to the EF query compiler.

Derived from Jon's example there let's look at the following code:

```
var book = context.Books
  .Select(b => new NonMappedObject(X: b.Author.Name, Y: getSomethingExternal())
  .OrderBy(nmo => nmo.X)
  .First();
```

as the select statement can't be mapped and orderBy uses something from the Select statements result,orderBy and First must be evaluated off the database, but it's likely that as a developer I can change that when I get notice to

```
var book = context.Books
  .OrderBy(b => b.Author.Name)
  .Select(b => new NonMappedObject(X: b.Author.Name, Y: getSomethingExternal())
  .First();
```

(or even to the following of course, which is out of scope for EF, but just plain optimization)
```
var bookEntity = context.Books
  .OrderBy(b => b.Author.Name)
  .First();
var book = new NonMappedObject(X: bookEntity.Author.Name, Y: getSomethingExternal())
```

But the proposed analyzer could at least provide a hint on OrderBy, First(), Take(), Skip and such, combined with statements that are surely not server side evaluated, that a different order might improve performance.

### Further technical details
Compiler: Roslyn

**Comment by anpete** [comment]
@jongleur1983 We do this at runtime via our client eval warning. The best approach right now is to set this warning as an error, and then have unit tests that exercise your queries.

It is unlikely that we could do a decent Analyzer for this - we would need to be able to invoke our query compiler, which would involve building and running your app at design time.

**Comment by ajcvickers** [comment]
@jongleur1983 We discussed this in triage, and there is general agreement with @anpete that the current runtime logging/warning/exception is a more realistic and maintainable approach than using analyzers here.
