### ISSUE TITLE
Exception: The expression should represent a property access: 't => t.MyProperty'. 

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#11663]
bool someCondition = true; // some condition that is set elsewhere 
	int someID = 0;             // some identifier that is set elsewhere

	var query = db.Releases.Include(x => 
    x.SourceReleases.Where(y => someCondition || y.SourceID == someID))
    .ToListAsync();

	// In query above if someCondtion is true I want all rows. 
	// If someCondition is false I want only the row where SourceID == someID

	// Exception generated by above query:
	// One or more errors occurred. (The Include property lambda expression 'x => {from SourceRelease y in x.SourceReleases 
	// where True select [y]}' is invalid.The expression should represent a property access: 't => t.MyProperty'. 
	// To target navigations declared on derived types, specify an explicitly typed lambda parameter of the target type, 
	// E.g. '(Derived d) => d.MyProperty'. For more information on including related data, 
	// see http://go.microsoft.com/fwlink/?LinkID=746393.)		
		
I use this pattern often:  [Possibly related](https://github.com/aspnet/EntityFrameworkCore/issues/5736)
Project attached:
[InsertTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/1905452/InsertTest.zip)

**Comment by ajcvickers** [comment]
@sam-wheat What are you saying is the bug here?

**Comment by sam-wheat** [comment]
.Where(y => someCondition || y.SourceID == someID))

Since `someCondition` is true the right side of the OR condition should not execute

Expected query:

    select * from table where 1=1

**Comment by anpete** [comment]
@sam-wheat Did you intend to put the filter inside the call to Include?

**Comment by sam-wheat** [comment]
@anpete Yes

**Comment by ajcvickers** [comment]
@sam-wheat Not sure at all why you expect that SQL, but conditionals inside Include are commonly assumed to indicate filtered Include, which is not implemented and is being tracked by #1833.

**Comment by anpete** [comment]
@sam-wheat "Property access" is referring to the shape of the lambda expression that we pattern match to determine which model property you want to include. Include is like some of the APIs on ModelBuilder - we allow you to use a LINQ expression fragment to address a model property in a strongly typed way.

**Comment by niranjan2020** [comment]
Fixed my issue Thanks a lot

**Comment by karlenaleksanyan** [comment]
> 

@niranjan2020  I have the same problem, how you fixed issue ?
