### ISSUE TITLE
One to One relationship using association table

### ISSUE THREAD

**Issue by raskolniko** [dotnet/efcore#11665]
I Work on legacy project where I have database First  model, now trying to rewrite in asp net core and I have issue with one to one relationship using third table (association) and I can't write fluent api  for following models 

public class A
{
    public int AId { get; set; }
    public string Prop1 { get; set; }
    public string Prop2 { get; set; }
    public string Prop3 { get; set; }
    public B B { get; set; }
}
public class B
{
    public int BId { get; set; }
    public string Prop1 { get; set; }
    public string Prop2 { get; set; }
    public string Prop3 { get; set; }
    public A A { get; set; }
}
public class AB
{
    public int AId { get; set; }
    public int BId { get; set; }
}

**Comment by anpete** [comment]
@raskolniko Are you mapping ```AB`` in your model?

**Comment by Tarig0** [comment]
could you change your a and b model to be

```c#
public class A
{
public int AId { get; set; }
public string Prop1 { get; set; }
public string Prop2 { get; set; }
public string Prop3 { get; set; }
public AB AB { get; set; }
public B B => AB.B;
}
public class B
{
public int BId { get; set; }
public string Prop1 { get; set; }
public string Prop2 { get; set; }
public string Prop3 { get; set; }
public AB AB { get; set; }
public A A => AB.A;
}
public class AB
{
public A A { get; set; }
public B B { get; set; }
public int AId { get; set; }
public int BId { get; set; }
}
```

**Comment by raskolniko** [comment]
@Tarig0  very interesting solution but there is exception Invalid column name 'A_AID1

**Comment by Tarig0** [comment]
maybe just need to remove the AID and BID props from the AB class. 

I'm surprised they didn't auto map as is though.
 
`If the dependent entity contains a property named <primary key property name>, <navigation property name><primary key property name>, or <principal entity name><primary key property name> then it will be configured as the foreign key`

>https://docs.microsoft.com/en-us/ef/core/modeling/relationships

**Comment by ajcvickers** [comment]
@raskolniko Even though the title says one-to-one, it looks like it is actually a many-to-many through a join table. This will map by convention, except that AB needs to have a composite key define explicitly. You can find more information about many-to-many mappings in the documentation linked by @Tarig0 above, and in [a series of blog posts](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/) I published last year.

If after following the guidance you are still running into an issue, then please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by Tarig0** [comment]
Ah I see
```c#
public class A
{
public int AId { get; set; }
public string Prop1 { get; set; }
public string Prop2 { get; set; }
public string Prop3 { get; set; }
public IEnumerable<AB> AB { get; set; }
public B B => AB.FirstOrDefault()?.B;
}
public class B
{
public int BId { get; set; }
public string Prop1 { get; set; }
public string Prop2 { get; set; }
public string Prop3 { get; set; }
public IEnumerable<AB> AB { get; set; }
public A A => AB.FirstOrDefault()?.A;
}
public class AB
{
public int AId { get; set; }
public int BId { get; set; }
}
```

All that needs to be done in fluent is to set the key of AB as AId and BId and that should be the correct behavior

**Comment by raskolniko** [comment]
@Tarig0  I know this approach but FirstOrDefault causes some timeout exception........

**Comment by raskolniko** [comment]
@ajcvickers I know that architecture of this model is many to many, but for example Entity framework 5 database first works with this model.

**Comment by Tarig0** [comment]
timeout exception? are you not including the AB and using lazy loading?
