### ISSUE TITLE
Migrations: AddColumn should have parameter to set value for existing rows

### ISSUE THREAD

**Issue by AndrewBoklashko** [dotnet/efcore#11685]
I often find myself in a situation where I need a migration to set a value for existing rows that differs from a default value. Currently I am using `MigrationBuilder.Sql()` for this. For example:

```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AddColumn<bool>(
        name: "IsActive",
        table: "DeviceToken",
        nullable: false,
        defaultValue: false);
    
    migrationBuilder.Sql(@"UPDATE [dbo].[DeviceToken] SET [IsActive] = 1");
}

```

It would be nice if AddColumn had a parameter for that, see [comment](https://github.com/aspnet/EntityFrameworkCore/issues/6035#issuecomment-231579933).

**Comment by ajcvickers** [comment]
@SSkovboiSS Is the reason for doing this: that you explicitly want a default constraint on the column that has some value, and separate to that you want all existing records to have some other value? (As opposed to that the migration just uses the wrong value for existing columns.)
