### ISSUE TITLE
[WriteExtension] Lazy Loading for Properties/Columns

### ISSUE THREAD

**Issue by Int32Overflow** [dotnet/efcore#11708]
Hey,

I would like to write an extension for EFCore 2.1. I've already looked at a few issues, but I haven't found a solution yet. Maybe someone could give me some tips.

Links:

- [How to extend EF functionality with custom Extension Methods](https://github.com/aspnet/EntityFrameworkCore/issues/5845)
- [Modify query expression](https://github.com/aspnet/EntityFrameworkCore/issues/4048)

For related data there is already a solution in EFCore 2.1, but I would also like a lazy load function for large columns. For example for a byte[] column with a profile picture.

For this I would like to create an attribute "LazyLoad". Properties with this attribute should be automatically excluded from the "SELECT". The data is not loaded until it is accessed for the first time.

How could this problem be solved elegantly?

Thank you :-)

**Comment by anpete** [comment]
@Int32Overflow This is in the box in 2.1. Plenty of other work to do though 😁

**Comment by Int32Overflow** [comment]
@anpete Is LazyLoading implemented for large columns in EFCore 2.1?

**Comment by ajcvickers** [comment]
@Int32Overflow This is going to be hard to implement as an extension because the code isn't currently factored for hooks in these places. A couple of things to consider:
* Try implementing this as a PR instead. It won't be trivial, and will involve a fair amount of code in both metadata and query, but it shouldn't be indefeasibly difficult.
* Use table splitting to create a lazy-loading entity that contains the big data. For example:
```C#
public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(
                new Blog
                {
                    OwnerImage = new OwnerImage {Data = new byte[] {1, 2, 3, 4}}
                });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            foreach (var blog in context.Blogs)
            {
                Console.WriteLine($"Blog: {blog.Id}");
                Console.WriteLine(  $"Data: {blog.OwnerImage.Data}");
            }
        }
    }
}

public class Blog
{
    public int Id { get; set; }
    public virtual OwnerImage OwnerImage { get; set; }
}

public class OwnerImage
{
    public int Id { get; set; }
    public byte[] Data { get; set; }
}

public class BloggingContext : DbContext
{
    public static readonly LoggerFactory MyLoggerFactory
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLazyLoadingProxies()
            .UseLoggerFactory(MyLoggerFactory)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(
            b =>
            {
                b.HasOne(e => e.OwnerImage).WithOne().HasForeignKey<OwnerImage>(e => e.Id);
                
                b.ToTable("Blogs");
            });
        
        modelBuilder.Entity<OwnerImage>().ToTable("Blogs");
    }
}
```
Both Blog and OwnerImage entity types are mapped to the same table:
```sql
CREATE TABLE [Blogs] (
    [Id] int NOT NULL IDENTITY,
    [Data] varbinary(max) NULL,
    CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
```
But the Data column will only be returned when OwnerImage is loaded.

**Comment by Int32Overflow** [comment]
@ajcvickers Unfortunately, table splitting only works for a new database schema. But I already have an existing database schema without splitting.

**Comment by smitpatel** [comment]
@Int32Overflow - You could easily configure the model not to use table splitting and match your database schema.
