### ISSUE TITLE
Outbound proxy for EFCore Sql Connection

### ISSUE THREAD

**Issue by mjnorman** [dotnet/efcore#11723]
I have a situation where I am required to use an outbound proxy to get to the internet to be able to access a hosted SQL database.  How would I go about doing this?  All of the documentation I can find is on hosting a proxy via dotnet core but not about using a proxy for an outbound connection for EF Core.

**Comment by smitpatel** [comment]
@mjnorman - EF Core passes the user provided connection string to SqlConnection without any special processing. So if you can get SqlConnection working, it would work with EF Core too. I would suggest trying to use SqlClient directly to figure out solution. 
https://github.com/dotnet/corefx more appropriate repo to ask questions related to SqlClient.
