### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#11726]
Hi folks.

I'm unable to build the repo in a fairly new PC.
After getting the repo (forked - unchanged), and running the `build` command, I'm getting the following output:

>
```
D:\Users\Shimmy\Source\Repos\EntityFrameworkCore>build
Using KoreBuild 2.2.0-preview1-17035
D:\Users\Shimmy\Source\Repos\EntityFrameworkCore\build.ps1 : The term 'Install-Tools' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
 that the path is correct and try again.
At line:1 char:126
+ ... ulture = '';& 'D:\Users\Shimmy\Source\Repos\EntityFrameworkCore\build ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-Tools:String) [build.ps1], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,build.ps1

```

I also tried running the following in PS with the same result:

>
```
.\build /t:Compile
$env:PATH="$env:USERPROFILE/.dotnet/x64;"+$env:PATH
.\EFCore.sln
```

#### Further technical details

Operating system: Windows 10.0.16299 x64
IDE: VS 15.6.6

**Comment by smitpatel** [comment]
You are having mixture of buildtools mis-aligned.
I did git clone fresh and it is using `Using KoreBuild 2.1.0-preview3-17018` which consistent with code in dev branch. While BuildTools have moved forward but we have not taken a newer version. So you are getting it by mistake somewhere causing the error.

**Comment by weitzhandler** [comment]
Can it be related to having corefx cloned too?

**Comment by weitzhandler** [comment]
OK, let's keep it on Slack. Thank you. I'll post the final solution here for future similar issues.

**Comment by weitzhandler** [comment]
@smitpatel thanks for your help.
To sum up for future reference, a specific version of KoreBuild is required. My fork was behind and had an outdated version of KoreBuild. After pulling all commits from upstream issue was fixed.
