### ISSUE TITLE
Support Call `ToListAsync()` or other async method on None async `IQueryable`

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#11737]
https://github.com/aspnet/EntityFrameworkCore/blob/2d987b669db52095e4754aea86aa04f9d068d417/src/EFCore/EntityFrameworkQueryableExtensions.cs#L2837-L2858

Why not return `Task.FromResult<T>`  when the provider is not `IAsyncQueryProvider` ?

That allow us to call EF-Core's async extension mthod on any `IQueryable<T>` object.

**Comment by tuespetre** [comment]
I kind of agree but I am also kind of curious to see framework-defined async enumerables/queryables and their corresponding extension methods land (planned for C# 8.0.)

**Comment by ajcvickers** [comment]
Duplicate of #9179
