### ISSUE TITLE
unexpected behavior from Entity Framework with AutoMapper

### ISSUE THREAD

**Issue by dobrinsky** [dotnet/efcore#11739]
Describe what is not working as expected.

I am using AutoMapper in a project and today I found a really unexpected behavior from Entity Framework.

In the application I read from files rows of data in a list of Resource objects and then I want to map those Resources to an actual object and store each one in the database.

the initial code was
        
```C#
             List<CategorieProdus> processedCategorii = new List<CategorieProdus>();

            foreach (var categorieProdusResource in categoriiProdusResource)
            {
                        CategorieProdus categorieProdus = new CategorieProdus ();

                        ...validations...

                        mapper.Map(categorieProdusResource, categorieProdus);
                        processedCategorii.Add(categorieProdus);
            }

                await _context.CategorieProdus.AddRangeAsync(processedCategorii);
                await _context.SaveChangesAsync();
```

The result was that only the last element in the list was added. There were no exceptions or anything. In the Output window only one INSERT statement was shown. I do not know what I was doing wrong that it saw just one element since in the final step,  processedCategorii list had 35 elements.

Then I tried like this just to test:

```C#         
            List<CategorieProdus> processedCategorii = new List<CategorieProdus>();

            foreach (var categorieProdusResource in categoriiProdusResource)
            {
                        CategorieProdus categorieProdus = new CategorieProdus ();

                        mapper.Map(categorieProdusResource, categorieProdus);

                        ...validations...

                        await _context.CategorieProdus.AddAsync(categorieProdus);
                        await _context.SaveChangesAsync();
            }
```

I was getting the exception that I can't change the value of an identity column. But the value of Id was 0 and nobody was changing it right before the first await, but after AddAsync, Id got the next index in the database (e.g. 10021) instead of -9994345363453 or something like that which I saw Entity attributes after AddAsync to other objects until the SaveChangesAsync after which the object actually get the id of 10021. I was not setting the value, but Entity somehow saw that I was.

Then I remembered I was using the same algorithm in another place and it worked. The only difference was this:

```C#
            List<CategorieProdus> processedCategorii = new List<CategorieProdus>();

            foreach (var categorieProdusResource in categoriiProdusResource)
            {
                        mapper.Map(categorieProdusResource, categorieProdus);

                        var categorieProdus = mapper.Map<CategorieProdusResource, CategorieProdus>(categorieProdusResource);
                
                        processedCategorii.Add(categorieProdus);
            }

                await _context.CategorieProdus.AddAsync(categorieProdus);
                await _context.SaveChangesAsync();
```

Which works with no problems.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 and Windows Server 2016
IDE: Visual Studio 2017 15.5.7

**Comment by smitpatel** [comment]
Based on error it looks like you are using same reference of `categorieProdus`. While list have 35 elements, can you verify they are 35 distinct elements and not the same references?

**Comment by dobrinsky** [comment]
If I do "Object object = new Object()" inside of a loop, it shouldn't be the same reference. Yes, the behavior is that it sees the same reference, but the count of the List in debug was 35 as many elements as there are in the Excel that I was importing

**Comment by divega** [comment]
@dobrinsky, `List<T>` does not perform contains checks in Add, so it is perfectly possible to have the same element repeated.

It is hard to think of any way the surprising behavior could be coming from EF Core. 

If you are seeing in your repro that all elements in the list are the same, then the only cause @smitpatel and I can guess is that the compiler is somehow choosing to hoist `CategorieProdus categorieProdus = new CategorieProdus ()` outside of the loop.

Assuming your repro code looks exactly like the snippets you have included here, we suggest to create an issue at https://github.com/dotnet/roslyn/issues/new.

**Comment by dobrinsky** [comment]
Ok, thank you guys very much!
