### ISSUE TITLE
Make access to benchmarks dashboard public

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#11741]
Now that we are using Power BI, we can make the results public like the ASP.NET team. We should probably come up with some useful views over the data, e.g. that compare EF Core and EF6, different versions of EF Core, etc.

See https://github.com/aspnet/EntityFrameworkCore/issues/8285#issuecomment-382626375.

**Comment by divega** [comment]
We got customers at build asking for this. It can be useful to drive adoption of EF Core.

**Comment by ajcvickers** [comment]
@divega Move to 3.0 for further tracking?

**Comment by divega** [comment]
@ajcvickers okay

**Comment by ajcvickers** [comment]
Closing this as we are going to move to the ASP.NET infra, which already has public Power BI.
