### ISSUE TITLE
Make all dependencies of EFCore.Analyzers PrivateAssets=All

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#11752]
The package Microsoft.EntityFrameworkCore.Analyzers has two dependencies in its nuspec that it shouldn't. Analyzers typically should have no dependencies. The references to Roslyn packages are build-only dependencies so should be PrivateAssets="All"

cc @ajaybhargavb @smitpatel @ajcvickers 

![image](https://user-images.githubusercontent.com/2696087/39026109-0c6f9f98-4400-11e8-98fe-a8509c1ed8ce.png)

**Comment by ajaybhargavb** [comment]
Looks like this was already fixed. https://github.com/aspnet/EntityFrameworkCore/commit/a8c34a67bde2d6324e168fa794f2ba63f16689e2

**Comment by natemcmaster** [comment]
Ah yup, should have known.

Closed as a dup of https://github.com/aspnet/EntityFrameworkCore/issues/11633
