### ISSUE TITLE
Consider using product code to create databases

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1175]
Currently SqlServerTestStore (and presumably other TestStores) use custom code for creating databases. This means that changes made to product code such as the attempt to make database creation more resilient will not get used by the tests.

**Comment by smitpatel** [comment]
@AndriySvyryd

**Comment by AndriySvyryd** [comment]
@smitpatel We still have this code

**Comment by AndriySvyryd** [comment]
This requires https://github.com/aspnet/EntityFrameworkCore/issues/2969 for SQL Azure
