### ISSUE TITLE
EF CORE use fields instead of properties？

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#11768]
why query mapping uses fields instead of properties if field name same as property name.

```csharp
 public string ItemsJson
        {
            get { return _itemsJson; }
            set
            {
                if (this._itemsJson != value)
                {
                    this._itemsJson = value;
                    this._items = _ItemsJson.IsNullOrWhiteSpace() ? null : JsonConvert.DeserializeObject<IEnumerable<TestItem>>(this._itemsJson, Utility.JsonSerializerSettings);
                }
            }
        }
```

use .ToArrayAsync() method, the property was not work， It looks like it was assigned the field directly.

### Further technical details
EF Core version: 2.0.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by ajcvickers** [comment]
@endink To force use of properties for everything, add the following to OnModelCreating:
```C#
modelBuilder.UsePropertyAccessMode(PropertyAccessMode.Property);
```
