### ISSUE TITLE
SQLCE 2.1 type mapper update question

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11770]
When mapping from DateTimeOffset with the new type mapping classes, I get an unexpected result from this test:
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/b368170ad547d1d3fd426ac9ebc485d117df935a/test/EntityFramework.SqlServerCompact.Tests/SqlCeTypeMapperTest.cs#L29

Actual result is: nvarchar(48) !

### Further technical details
EF Core version: 2.1-preview2
Database Provider: SQLCE

**Comment by ajcvickers** [comment]
@ErikEJ Looks like there is no mapping for DatetimeOffset in SqlCeTypeMappingSource. Therefore, since the provider cannot map the type natively, EF instead does a conversion to a string.

**Comment by ErikEJ** [comment]
Cool, thanks
