### ISSUE TITLE
UWP: EntityFrameworkCore 2.1.0-preview2-final  gives: Internal compiler error

### ISSUE THREAD

**Issue by hwjSoftware** [dotnet/efcore#11772]
I have a simple UWP test program with a button and a ContentDialog.
 I use "VS 15.7.0" + "Microsoft.Net.Framework 4.7.02556 + "Build 16299 + "Microsoft.NETCore.UniversalWindows 6.0.8 + "Microsoft.EntityFrameworkCore 2.1.0-preview1-final 
No problems thus far. 
When I update EntityFrameworkCore 2.1.0-preview1-final with preview2, the app can be used in debug mode. 
In release mode VS gives: Internal compiler error: Object reference not set to an instance of an object. 

Can this be caused by an EF component?

The project is available as zip file at https://1drv.ms/u/s!AprCZJbD3fOTh6VZDyYGvUInJ5V7QQ (332MB)

**Comment by divega** [comment]
If I create a new blank UWP project using Visual Studio 2017 15.7 Preview 4, this failure does not occur. I have found that the main difference between this project and the original repro is the version of Microsoft.NETCore.UniversalWindowsPlatform:

Working version:
``` xml
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.1.0-preview1-26328-03</Version>
    </PackageReference>
```
Broken version (this appears to be the latest version published to NuGet.org): 
``` xml
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.0.8</Version>
    </PackageReference>
``` 

I have confirmed that the build passes by updating the package in the original repro.

**Comment by divega** [comment]
@MichalStrehovsky looks like an issue in the .NET Native pipeline. Not sure if the new version of the package is expected to be needed, but the compiler error is not very nice. Who is the right person to ping and repo  to move?

**Comment by divega** [comment]
cc @janvorli too.

**Comment by divega** [comment]
Thanks @MichalStrehovsky for figuring this out: one of the EF Core 2.1 dependencies uses System.Memory, which is not handled by .NET Native compiler prior to 2.1. 

So it seems that the workaround at https://github.com/aspnet/EntityFrameworkCore/issues/11772#issuecomment-383701830 is the right way to go. The right bits .NET Native 2.1 are part of Visual Studio 2017 15.7.
