### ISSUE TITLE
feature: command for cli to check if migrations matches up with the actual db, not just the history

### ISSUE THREAD

**Issue by ruant** [dotnet/efcore#11787]
Would be awesome to do complete db checks against the snapshot generated by the migrations process to actually check if the db is what it should be like from the cli.  

I guess it's possible from code per this SO: https://stackoverflow.com/questions/13089448/how-to-check-if-database-schema-matches-entity-framework-schema

**Comment by ajcvickers** [comment]
@ruant This kind of scenario is being tracked by issue #831. We're not planning to do anything outside of what is already covered there.
