### ISSUE TITLE
Table with Discriminator and non unique primary key causing InvalidCastException

### ISSUE THREAD

**Issue by SamWhitby** [dotnet/efcore#11815]
If you have a table with a discriminator and a primary key that is not unique across the entire table but is unique per virtual table i.e. discriminator + primary key, ef can not cast entities to the correct type.

For example I have the following entities (simplified to highlight the issue) 

```C#
    [Table("discriminatortest")]
    public abstract class DiscriminatorTest
    {
        public int Id { get; set; } //this value is not actually a primary key in the db as the ids are only unique across discriminator + primary key (legacy constraint)
    }

    public class EntityA : DiscriminatorTest
    {
    }

    public class EntityB : DiscriminatorTest
    {
    }

    [Table("discriminatortestrelationship")]
    public class DiscriminatorTestRelationship
    {
        public int Id { get; set; }
        public int EntityAId { get; set; }
        public EntityA EntityA { get; set; }
        public int EntityBId { get; set; }
        public EntityB EntityB { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<DiscriminatorTestRelationship> DiscriminatorTestRelationships { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<DiscriminatorTest>().HasDiscriminator<string>("Discriminator").HasValue<EntityA>("A").HasValue<EntityB>("B");            
        }
    }
```

And we create the following db tables and data

```sql
    CREATE TABLE [DiscriminatorTest](
	    [Id] [int] NULL,
	    [Discriminator] [varchar](1) NULL
    ) ON [PRIMARY]

    GO

    CREATE TABLE [DiscriminatorTestRelationship](
	    [Id] [int] IDENTITY(1,1) NOT NULL,
	    [EntityAId] [int] NOT NULL,
	    [EntityBId] [int] NOT NULL)
    GO

    insert into [DiscriminatorTest] values (1,'A')
    insert into [DiscriminatorTest] values (1,'B')

    insert into [DiscriminatorTestRelationship] values (1,1)
```

Calling the below code results in an invalid cast exception

```C#
    context.DiscriminatorTestRelationships.Include("EntityA").Include("EntityB").ToList();
```

I understand that the id should be unique across the entire table, but in the scenario of multiple entities per table, this seems like an annoying constraint because ef should be able to work out how to cast things correctly based on the discriminator supplied.

Exception message:"System.InvalidCastException"  Unable to cast object of type 'Models.EntityA' to type 'Models.EntityB'.
Stack trace:
{
              "level": 0,
              "method": "Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape",
              "assembly": "Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 1,
              "method": "Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedOffsetEntityShaper`1.Shape",
              "assembly": "Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 2,
              "method": "Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper+TypedCompositeShaper`5.Shape",
              "assembly": "Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 3,
              "method": "Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1+Enumerator.BufferlessMoveNext",
              "assembly": "Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 4,
              "method": "Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute",
              "assembly": "Microsoft.EntityFrameworkCore.SqlServer, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 5,
              "method": "Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1+Enumerator.MoveNext",
              "assembly": "Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 6,
              "method": "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext",
              "assembly": "System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            },
            {
              "level": 7,
              "method": "Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+<_TrackEntities>d__17`2.MoveNext",
              "assembly": "Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 8,
              "method": "Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor`1+EnumeratorExceptionInterceptor.MoveNext",
              "assembly": "Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 9,
              "method": "System.Collections.Generic.List`1.AddEnumerable",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 10,
              "method": "System.Linq.Enumerable.ToList",
              "assembly": "System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            },

**Comment by ajcvickers** [comment]
Notes for triage: I tried to do this by defining a composite key to include the discriminator, but ran into issues:
* The alternate key and foreign key constraints cannot be created in the database because they violate uniqueness
* Editing the database schema to not have these but leave the EF mapping results in issues with the state manager, possibly due to part of the PK being in shadow state.

Thoughts:
* The database constraints mean that I don't think we would ever support this in Migrations/EnsureCreated
* I imagine the discriminator part in the EF mapping could be made to work.

**Comment by ajcvickers** [comment]
Discussed again in triage and realized that even if the above could be made to work there still wouldn't be enough information in the DiscriminatorTestRelationship table to disambiguate which PK the FK references. This requires a composite FK to match the PK, at which point this becomes a normal composite key case. Therefore, closing as by-design.

**Comment by SamWhitby** [comment]
Yes, I agree, there is not enough information in the DiscriminatorTestRelationship table to disambiguate which PK the FK references, however in a code first approach this should not matter.
From the code side there is enough information to achieve this. EF has knowledge of both the discriminator and the id so should be able to deserialize the entities to the correct types.

    (modelBuilder.Entity<DiscriminatorTest>().HasDiscriminator<string>("Discriminator").HasValue<EntityA>("A").HasValue<EntityB>("B");)

    ....

    [Table("discriminatortestrelationship")]
        public class DiscriminatorTestRelationship
        {
            public int Id { get; set; }
            public int EntityAId { get; set; }
            public EntityA EntityA { get; set; }
            ...

The issue here seems like a failing in the EF deserialization logic. Presumably something to do with caching and nothing to do with the db structure/FK constraints.

**Comment by ajcvickers** [comment]
@SamWhitby When EF is reading rows from DiscriminatorTestRelationship table, it needs to pair up each FK value there with a primary key value in the principal table, but this is not possible because multiple primary key values will match.
