### ISSUE TITLE
efcore- change tracker is tracking not changed values

### ISSUE THREAD

**Issue by mhamri** [dotnet/efcore#11821]
let say i have a code like this as entity:

```c#
class Project{
   public int Id{get;set;}
   public ICollection<Item> Items {get; set;}= new HashSet<Item>();
}
````
somehwere in the code i'm query and update and then save like this:
````C#
var project= _db.Projects.where(x=>x.id==1);
var itemsCount= project.Items.Count(); //here let say i'm getting 99, means there is already 99 item in the Item Table
project.Items.Add(new Item(){name=1});
_db.SaveChanges();
````
until here everything is normal, query and save.

however, the audit event is holding 99 of the `Project.Items` as updated and 1 as inserted. this way each time i'm inserting something in this table, i'm reinserting everything as updated/inserted into the log. 

EF Core version: 2.0.2
Database Provider: mssql
Operating system: windows
IDE: vs2017 build 15.6.6

**Comment by smitpatel** [comment]
@mhamri - Before you call `SaveChanges` check that Item entities are not marked as Modified in changetracker. If their states are correct then it is issue in Audit.Net and you should report to them. If their states are incorrect then, check your code if you are not marking them as Modified unintentionally. If everything in user code is correct yet states are incorrect in change tracker then it would be easy to create a small repro out of it which uses only EF and nothing from Audit.Net. In which case, post such repro if any.

**Comment by mhamri** [comment]
sorry it's meant to post in audit.net github. it's their way of checking of modified that causing problem
i will delete this post
