### ISSUE TITLE
What is best practice to work with tracked untracked entities?

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#11825]
If i forget to load a entity in a service method with .AsNoTracking - i got a already tracked entity and return it to the application. 
If application is giving me later this already tracked entity (in a no more existing context) and try to attach this entity in the new context - i got an error - entity already tracked.

What would be the correct way to work with this?

Should all entities leaving the context scope be untracked - which then means i should always use .AsNoTracking? In this case it is difficult to reuse methods inside a context - so I will get methods for returning tracked und untracked entities - tracked for use inside context und untracked for use outside context.

Or is there a way to detach a entity from the already gone context or to check if there is some meta info inside? So I could check and detach it from the old context to attach it to the new context.

**Comment by ajcvickers** [comment]
@berndu The recommended approach is to use a short-lived context instance such that you're not attaching to the same context again later. That being said, some other things that might help:
* If you always want no-tracking, then configure no-tracking the context options: `optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)`
* If you really need to detach an entity from a context, then set it's state to Detached: `context.Entry(entity).State = EntityState.Detached`. However, this is may be quite an expensive option--throwing the context away and creating a new one is often cheaper.

But I would encourage you to look at the application architecture and attempt to use short-lived context instances where the only entities being tracked are the ones relevant to the single unit-of-work being processed.
