### ISSUE TITLE
Serialization of shadow properties

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#11822]
Is that possible to programatically serialize and deserialize shadow properties to/from JSON with custom contract resolver/converter? I'm trying to automate some things, and it would be cool if shadow properties were taken into consideration when serializing, deserializing things and to have some of them(like foreign keys) in swagger spec. Basically, is there some way to get those shadow properties using reflection from basic `Type` ? I wanted to add some magic that doesn't require me to create separate DTO or adding that property explicitly but not sure if that's possible and would perform well enough.

I could possibly add `ForeignKeyAttribute` explicitly to point to the shadow property and parse that, and do my magic from there, but I was thinking on even more transparent ways, like finding shadow foreign key property related with navigation property.

In other words, is this possible to get associated shadow property with model like this?:

```csharp
public class Order
{
    public int Id { get; set; }
    // Somehow retrieve ProductId property, without any attribute?
    // some json mechanism would automagically add productId to the output, and accept it in the input
    // possibly having some attribute like [Rel(Type = RelType.Identity)] that would decide whether or not
    // use shadow property in serialization and ignoring this navigation property that would embed it in the payload
    public Product Product { get; set; }
}
```

I wanted to achieve some form of AOP (Aspect Oriented Programming) that would save me from writing more code, creating DTOs.

so that `Order` class would serialize to:

```
{
    id: x,
    productId: x
}
```

and would accept payload like:

```
{
    productId: x
}
```

but without having to explicitly add ` public int ProductId { get; set; }` to my class.

**EDIT:**

After playing with it a bit I realized that shadow properties not explicitly added to the class have `CurrentValue` property set to `null` even despite navigation property was eager loaded and I can access Id from there. Also setting CurrentValue seems to be ignored.

```csharp
public class ForeignKeyContractResolver : DefaultContractResolver
{
    private readonly DbContext _dbContext;

    public ForeignKeyContractResolver(DbContext dbContext)
    {
        _dbContext = dbContext;
    }
    
    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        var jsonProperty = base.CreateProperty(member, memberSerialization);

        var entityType = _dbContext.Model.FindEntityType(member.DeclaringType);
        // Only EF entities (referenced in DbContext)
        if (entityType == null)
        {
            return jsonProperty;
        }

        var navigationProperty = entityType.GetNavigations().SingleOrDefault(navigation => navigation.Name == member.Name);
        if (navigationProperty != null)
        {
            var foreignKeyProperty = navigationProperty.ForeignKey.Properties.SingleOrDefault();
            if (foreignKeyProperty != null)
            {
                jsonProperty.PropertyName = NamingStrategy.GetPropertyName(foreignKeyProperty.Name, false);
                jsonProperty.PropertyType = foreignKeyProperty.ClrType;

                // Set new value provider to set shadow property's value instead
                jsonProperty.ValueProvider = new ForeignKeyValueProvider(_dbContext, member.Name);
            }
        }

        return jsonProperty;
    }
}

public class ForeignKeyValueProvider : IValueProvider
{
    private readonly DbContext _dbContext;
    private readonly string _navPropertyName;

    public ForeignKeyValueProvider(DbContext dbContext, string navPropertyName)
    {
        _dbContext = dbContext;
        _navPropertyName = navPropertyName;
    }

    public object GetValue(object target)
    {
        var nav = _dbContext.Entry(target).Navigation(_navPropertyName);
        var currentValue = nav.CurrentValue;
        if (currentValue != null)
        {
            var principalKey = nav.Metadata.ForeignKey.PrincipalKey.Properties.SingleOrDefault();
            return currentValue.GetType().GetProperty(principalKey.Name).GetValue(currentValue, null);
        }
        return null;
    }

    public void SetValue(object target, object value)
    {
        var nav = _dbContext.Entry(target).Navigation(_navPropertyName);
        var fkProperty = nav.Metadata.ForeignKey.Properties.SingleOrDefault();
        if (fkProperty != null)
        {
            // Doesn't seem to affect adding to database anyway.
            _dbContext.Entry(target).Property(fkProperty.Name).CurrentValue = value;
        }
    }
}
```

In the end I don't think it's worth the effort.

**Comment by ajcvickers** [comment]
@enemyofthedawn Shadow properties have their values saved in the DbContext state manager. They explicitly do not have any storage on the CLR type--that's what defines them as shadow properties.

For serialization there are two options:
* Don't use shadow properties. Instead define private properties and/or fields on the CLR types and map these as properties. This is often the pragmatically superior option if you are in control of the CLR types.
* Use tracking queries (else shadow property values will be discarded) and serialize using the facilities of the state manager. For example, just printing out instead of serializing:
```C#
using (var context = new BloggingContext())
{
    var posts = context.Posts.ToList();

    foreach (var post in posts)
    {
        Console.WriteLine($"Post {post.Id}:");

        foreach (var property in context.Entry(post).Properties)
        {
            Console.WriteLine($"  Property '{property.Metadata.Name}' has value {property.CurrentValue}");
        }
    }
}
```
For a few posts like this:
```C#
public class Post
{
    public int Id { get; set; }
    public Blog Blog { get; set; }
}
```
gives output
```
Post 1:
  Property 'Id' has value 1
  Property 'BlogId' has value 1
Post 2:
  Property 'Id' has value 2
  Property 'BlogId' has value 1
Post 3:
  Property 'Id' has value 3
  Property 'BlogId' has value 2
Post 4:
  Property 'Id' has value 4
  Property 'BlogId' has value 2
```
Notice that values for both non-shadow ('Id') and shadow ('BlogId') are output.
