### ISSUE TITLE
efcore- the internal on different object make it impossible to create custom provider

### ISSUE THREAD

**Issue by mhamri** [dotnet/efcore#11820]
I'm trying to write a new provider because the current provider can't understand correct change tracker and custom logging that I want from it. I will create another issue to discuss about the provider problem.

I tried to create a new provider by copying the current `EntityFrameworkDataProvider.cs` and do some modification. but unfortunately, different objects are marked as internal including 

`EventEntry.Entry` in `~\Audit.NET\src\Audit.EntityFramework\EventEntry.cs`
`EntityFrameworkEvent.DbContext` in `~\Audit.NET\src\Audit.EntityFramework\EntityFrameworkEvent.cs`

this makes it impossible to extend the provider since I don't have access to same objects to use in the provider

**Comment by ajcvickers** [comment]
@mhamri EventEntry is not a class defined by EF Core, Are you looking at code from some other source?

**Comment by smitpatel** [comment]
This issue should be directed to Audit.Net codebase.
