### ISSUE TITLE
DeleteBehavior.Restrict - exception isn't thrown in case of an inconsistent state on SaveChanges

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#11836]
From the description of DeleteBehavior.Restrict:
```
For entities being tracked by the Microsoft.EntityFrameworkCore.DbContext, the
values of foreign key properties in dependent entities are not changed. This
can result in an inconsistent graph of entities where the values of foreign key
properties do not match the relationships in the graph. If a property remains
in this state when Microsoft.EntityFrameworkCore.DbContext.SaveChanges is called,
then an exception will be thrown.
```

When I try to reproduce this, the SaveChanges sends a "delete" SQL command to the DB, and the DB throws an exception. EF doesn't throw its own exception before sending the command to the DB. So, the claim `then an exception will be thrown` is only correct if the DB is actually configured to throw an exception in this case.

Is this working as intended, i.e. EF is counting on the DB to throw an exception? Either way works fine for me, but I want to make sure.

**Comment by ajcvickers** [comment]
The database. And yes, if the database is not setup with FK constraints, then it won't throw, and you'll have corrupted data.
