### ISSUE TITLE
More than one DbContext was found. Specify which one to use

### ISSUE THREAD

**Issue by maxisam** [dotnet/efcore#11839]
`dotnet ef migrations script -i -o scripts.sql`

I can't find a way to generate one migration script for a project with multiple DbContexts

It kinda becomes an issue when you are trying to do it with VSTS CI/CD if you want to see the migration script first before you deploy it.

However, what I don't understand is when I use 
`dotnet ef database update -c ApplicationDbContext`

It actually generates every DbContext with every migration.

but  `dotnet ef migrations script -i -o scripts.sql -c ApplicationDbContext` only generates scripts for tables related to ApplicationDbContext.

**Comment by bricelam** [comment]
> It might not be a problem because they are all different DBContexts.

Correct. Migrations for different contexts shouldn't overlap (see also #2725). Their IDs are also sufficiently unique to never clash.

It shouldn't be a problem, but if it is, you can configure each context to have it's own history table:
``` csharp
protected override void OnConfiguring(DbContextOptionsBuilder options)
    => options.UseSqlServer(
        connectionString,
        x => x.MigrationsHistoryTable("__MyMigrationsHistory"));
```
