### ISSUE TITLE
Does the Context matter for an AsNoTracking query?

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#11840]
I have only one Context type. All my context instances do the same thing in OnConfiguring and OnModelCreating.

As far as I can see, the contents of a context are irrelevant for an AsNoTracking query - even if an entity is already tracked by the context, the query will create a new instance with the same key and return that instead.

But despite not tracking anything, an AsNoTracking query still requires a context instance. So, let's say I have two context instances `ctxA` and `ctxB` - is there any difference at all between these two lines?
```
var p = ctxA.Posts.AsNoTracking().First();
var p = ctxB.Posts.AsNoTracking().First();
```

**Comment by ajcvickers** [comment]
@Wain123 Depends if the two context instances are configured the same and whether or not they are sharing the same connection.

**Comment by ajcvickers** [comment]
@Wain123 To be more specific, assuming the two contexts are configured in the same way, and assuming that they both point to the same database, then there should be no difference. This is essentially what context pooling does.
