### ISSUE TITLE
Lazy-loading not able to find parameterless constructors when the constructors are set to private

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#11849]
When enabling lazy loading with ```.UseLazyLoadingProxies()``` parameterless constructors must be set to public or protected. Private parameterless constructors throw an exception. 

With lazy loading disabled, private parameterless constructors work as expected.

Exception message:
```
Castle.DynamicProxy.InvalidProxyConstructorArgumentsException: 'Can not instantiate proxy of class: Project.MyClass.
Could not find a parameterless constructor.'
```

### Steps to reproduce
1) Create an entity with a private parameterless constructor

2) Enable lazyloading via AddDbContext

3) Access the entity

### Further technical details
EF Core version:: 2.1. preview2

**Comment by smitpatel** [comment]
Lazy loading proxies work by creating a derived proxy class of entity type. A private ctor could not be called (or overridden) in derived class.

**Comment by vflame** [comment]
Forgot about that. Thanks
