### ISSUE TITLE
Whats the right way to use custom stored procedure in entity core?

### ISSUE THREAD

**Issue by HolyOne** [dotnet/efcore#11854]
I use some stored procedures in my app. But I dont think what I do is the right way.

1) To create Stored Procedures:   I create sql files with create procedure commands and I launch them on migration.

To use them I use functions like this like this.

``` C#
        public List<GetReportResult> GetReport(int MailListId, DateTime fromDate, DateTime toDate)
        { 
            return db.SP_GetReport.FromSql(
                "SP_GetReport @MailListId={0}, @fromDate={1}, @todate={2}", 
                MailListId, 
                fromDate, 
                toDate).AsNoTracking().ToList();
        }
```

But I have to create a class under my DbContext to get a result (because my sp returns a custom fieldset)
I can use my SP s but my DbContext creates an additional empty table on my database. Because I included that class to my DbContext .

Although I searched a lot, there is no documentation on how to create and use stored procedures which returns results with custom fields (not same as any table on the context).

So whats the right way to create and use stored procedures with EF Core on .net core 2.1 ?

**Comment by Vasimovic** [comment]
Did you try Query<>

`return dc.Query<GetReportResult>().AsNoTracking().FromSql("SP_GetReport @p0, @p1, @2", MailListId,  fromDate, toDate).ToList();`

Also, if you need named parameters you can use `SqlParameter`

Example: `new SqlParameter("@MailListId", MailListId)`

**Comment by HolyOne** [comment]
And how should I store my SP's on database creation?

**Comment by divega** [comment]
@HolyOne 

You can create stored procedure in the database by adding calls to the `Sql()` methods in your migrations. See [this documentation article](https://docs.microsoft.com/ef/core/managing-schemas/migrations/operations#using-migrationbuildersql) for more details.

There is more information about the `Query<T>()` method and query types [in the documentation]( https://docs.microsoft.com/ef/core/modeling/query-types).
