### ISSUE TITLE
I want to realize custom mechanism of migration schema.

### ISSUE THREAD

**Issue by Diaskhan** [dotnet/efcore#11851]
I want to realize custom mechanism of migration schema.
U could see it on picture. Its enterpise scenarion, when have many dev servers with dev database!

The main question is have api to create table, alter table, add foreign key on fly ?

For exmaple !

table = context.addtable('table1','dbo')
table.add_column('id',int)

And this code executes right now, not anachoring to dotnet executable!

It seems like ci\cd system, but without testing, and other option just Database schema update!

![image](https://user-images.githubusercontent.com/15046677/39405236-8bfadf1e-4bc3-11e8-908d-aa9a24592e45.png)

**Comment by Diaskhan** [comment]
And yes, the best solution will be not to link to provider of individual database, like mssql,mysql!

It just works above data_providers!

**Comment by divega** [comment]
@Diaskhan we have had a hard time trying to understand what you are trying to do. Is it that you want to use the parts of EF Core migrations pipeline to update the schema of a database without using the rest of EF Core?

**Comment by Diaskhan** [comment]
I want to use ef models,linq,mapiing, but mechanism of migration schema in guidelines is oriented to 
Customer Firm -Devevlopers Firm relations.

In my case I need system That Customer Firm developes by their self's!
And This case Is usually Enterpise scenario!  Firm byes Platform, and extens by their self, without Developers Firm!

**Comment by Diaskhan** [comment]
Thanks guyes.
I see that there have Migration comand that could migrate !
Needed some time to research sources.


https://github.com/aspnet/EntityFrameworkCore/blob/09c9b263d648dac4432b9dfb280f84f651c33949/src/EFCore.Relational/Migrations/MigrationBuilder.cs

 
Тесты проверки 
MigrationBuilder для SQL Server
 
 
https://github.com/aspnet/EntityFrameworkCore/blob/0e1d2ca3d7b4dc49b77368ede5ccb8b26a4fa1f3/test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
 
 
Эта штука кажется и исполняет Миграции
https://github.com/aspnet/EntityFrameworkCore/blob/09c9b263d648dac4432b9dfb280f84f651c33949/src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
 
Команда миграции
https://github.com/aspnet/EntityFrameworkCore/blob/09c9b263d648dac4432b9dfb280f84f651c33949/src/EFCore.Relational/Migrations/MigrationCommand.cs
