### ISSUE TITLE
Query: Add ForEachAsync operator with async lambda

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11866]
From #11861 

ForEachAsync takes sync lambda. We can add overload which takes async lambda too so async func can be called from it.

**Comment by tuespetre** [comment]
> soon

Ohhh? Do you know some knowledge about some things @divega?

**Comment by divega** [comment]
@tuespetre really nothing that isn’t public knowledge: https://github.com/dotnet/csharplang/issues/43 is marked as 8.0 candidate, and we have been discussing it for a long time now.

**Comment by tuespetre** [comment]
Dang, I was hoping your “soon” was sooner than the “soon” I’ve been telling myself for a while. 🤐

**Comment by divega** [comment]
Closing as duplicate of #12425.
