### ISSUE TITLE
sehexception EFCore 2.0.2

### ISSUE THREAD

**Issue by mysticdotnet** [dotnet/efcore#11877]
When i use ef core as orm i have a sehexception

```
Exception message: sehexception
```
### Steps to reproduce
Steps are described in this issue: [#1413](https://github.com/OData/WebApi/issues/1413)

### Further technical details
EF Core version: (2.0.2)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (Visual Studio 2017 15.6.7)

**Comment by divega** [comment]
Note from triage: the full information about the repro is in https://github.com/OData/WebApi/issues/1413. The OData team has already tried removing EF Core from the repro and the exception went away. Given it is an SEHException, I suspect it isn't a problem with EF Core, but if we run the repro we may be able to identify where it is coming from.

**Comment by divega** [comment]
@mysticdotnet is there a stack trace accompanying the exception?

**Comment by mysticdotnet** [comment]
Thank you for your prompt response.
I have only this message:
![sehexception](https://user-images.githubusercontent.com/38808237/39561756-fe0e1eb8-4ea7-11e8-8f80-eb4125842ef9.png)
