### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#11874]
I'm trying to clone object and insert a copy of it in the database when it's changed. What I want to do, is soft delete it and insert a copy with modifed values. As soon as I add new entity to the collection I get the exception that the collection was modified and enumeration operation may not execute. 

Is there any way to solve this?

The general idea in my project is that I can't really modify soft deletable entities when there are any references to it so I want to soft-delete it and insert a copy of it to preserve historical data.

```csharp
public override int SaveChanges(bool acceptAllChangesOnSuccess)
{
    foreach (var entry in ChangeTracker.Entries().Where(entry => entry.Entity is ISoftDeletable)) // InvalidOperationException: Collection was modified; enumeration operation may not execute
    {
        if (entry.State == EntityState.Deleted)
        {
            entry.State = EntityState.Modified;
            entry.CurrentValues["IsActive"] = false;
        }
        else if (entry.State == EntityState.Modified)
        {
            // Add a copy of it when it's modified
            var newEntity = (BaseEntity)entry.CurrentValues.ToObject();
            newEntity.Id = 0;
            Add(newEntity);
            
            entry.CurrentValues.SetValues(entry.OriginalValues);
            entry.CurrentValues["IsActive"] = false;
        }
    }
    
    return base.SaveChanges(acceptAllChangesOnSuccess);
}
```

**Comment by enemyofthedawn** [comment]
The solution was to add to collection outside the loop. It's probably by design.

**Comment by smitpatel** [comment]
Or you could call ToList on Where and buffer it, instead of enumerating.
