### ISSUE TITLE
Consider adding Blob and Queue to ATS provider

### ISSUE THREAD

**Issue by SychevIgor** [dotnet/efcore#1187]
For ef7 Azure table storage will be supported.
As I understand from design notes: table storage will be extremely simple.

I think it will be a great case if we will can store binary data as part of our entity in a azure blob storage with lazy loading.
example:
    public class Document
    {
        public string Name { get; set; }

```
    public DateTime UploadDate { get; set; }

    public virtual byte[] DocumentBinaryRepresentation { get; set; }
}
```

where DocumentBinaryRepresentation  could be loaded if/when necessary.

Such a case is supported by DocumentDB and I think will increase scenarios for EF7+ATS.

What do You think about such a feature for EF 7.1 version?

**Comment by divega** [comment]
Linked to main ATS provider issue and now closing.
