### ISSUE TITLE
Query: further optimize translation of StartsWith

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#11881]
Currently we translate `foobar.StartsWith(foo)` into:

```
(foobar like foo +'%' and left(foobar, len(foo)) = foo) or foo = '' -- last term is removed if foo is non-null constant
```

however @rmacfadyen pointed out that for some scenarios the last term actually makes the query non-sargable.

If the term is removed completely, we return (arguably) incorrect data for case: null.StartsWith(""). 

We could however use the following translation:

```
(foobar like foo +'%' and left(foobar, len(foo)) = foo) or (foo = '' and foobar is null)
```

(and if we know that foobar can't be null we could drop the term as well. 

We need to do some more investigation on which scenarios are getting better with this translation (i.e. if its worth complicating the sql)

**Comment by ajcvickers** [comment]
Triage: Do the second translation.

**Comment by rmacfadyen** [comment]
> If the term is removed completely, we return (arguably) incorrect data for case: null.StartsWith("").

In SQL any comparison against NULL is NULL. So a NULL value can never StartsWith(..) anything (empty string, NULL, or an actual value). 

In SQL LEFT(NULL, 0) returns NULL (not an empty string). Also SELECT 1 WHERE NULL LIKE '%' returns no rows.

All of which means that currently StartsWith('') is currently returning incorrect results when the column is NULL.

**Comment by divega** [comment]
> In SQL LEFT(NULL, 0) returns NULL (not an empty string). Also SELECT 1 WHERE NULL LIKE '%' returns no rows.

That is true but another point of view is that the behavior of these functions is simplistic and not consistent with what SQL does with NULL in other places, e.g.:

NULL OR true --> true
NULL AND false --> false

In these cases NULL clearly means an UNKNOWN value. In the case we are discussing, the fact that you don't know what a string value is doesn't change the fact that such string will start with an empty string: all strings do. There are more ways to reason about it as well:

1. In general translating .NET Boolean expressions that cannot be `null` to SQL that can be evaluated as NULL is problematic and breaks composability when used as part of a composite predicate, so we try to avoid it within reason. Of course there are many cases in which the translation of StartsWith when one or both of the arguments are null will result in NULL, but this one could be easily avoided, and as we have found so far, with the proposed translation, it does not get in the way of sargability.

2. We are talking about scenarios in which evaluating StartWith in-memory in a regular program would throw an exception, so we really get to choose how it behaves. 

3. Changing the translation to remove this term could break any application that uses StartWith in a predicate without any additional short-circuiting logic to prevent rows will NULL values from being incorrectly filtered out.

**Comment by dmitry-lipetsk** [comment]
```c#
class SqlServerStartsWithOptimizedTranslator
{
 //...
new SqlFunctionExpression("LEN", typeof(int), new[] { patternExpression }
 //...
}
```

If patternExpression contains 'char' or 'const string' (ConstantExpression), you may detect length localy and pass it to SQL.

**Comment by darcythomas** [comment]
My observation/ 2 cents:

For me:
`[Foo] LIKE @foo + '%' AND (LEFT([Foo], LEN(@foo)) = @foo)) OR (@foo = '')`
is 100X slower than `[Foo] LIKE @foo + '%'` 

This seems to be because the the query needs to perform a index scan rather than an index seek on `IX_TableName_Foo`

**Comment by roji** [comment]
Note that with #14657, when the pattern is constant we no longer translate the long/inefficient version, but escape the escape characters client-side (if needed) and simply send `LIKE %pattern`, which is the most efficient possible.

We could still look into improvements for non-constant patterns but I'm not really sure it's worth it.

**Comment by langdonx** [comment]
Currently..
> where wo.WorkOrderNumber.EndsWith("D") == false

Translates to..

> WHERE (([t].[work_order_number] IS NOT NULL AND ([t].[work_order_number] LIKE '%D')) OR (CAST(0 AS bit) = CAST(1 AS bit))) AND CASE
    WHEN [t].[work_order_number] IS NOT NULL AND ([t].[work_order_number] LIKE '%D') THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)

Did I do something wrong, or is that expected until this issue is resolve?

**Comment by langdonx** [comment]
Gets even crazier when two are used together:

> where wo.WorkOrderNumber.EndsWith("D") == false
> where wo.WorkOrderNumber.EndsWith("T") == false

Translates to..

> WHERE ((([t].[work_order_number] IS NOT NULL AND ([t].[work_order_number] LIKE '%T')) OR (CAST(0 AS bit) = CAST(1 AS bit))) AND CASE
    WHEN [t].[work_order_number] IS NOT NULL AND ([t].[work_order_number] LIKE '%T') THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END IS NOT NULL) AND ((([t].[work_order_number] IS NOT NULL AND ([t].[work_order_number] LIKE '%D')) OR (CAST(0 AS bit) = CAST(1 AS bit))) AND CASE
    WHEN [t].[work_order_number] IS NOT NULL AND ([t].[work_order_number] LIKE '%D') THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END IS NOT NULL)

Which is conflicting enough to stop returning records.

I'd expect this to translate to..

> WHERE [t].[work_order_number] NOT LIKE '%T' AND WHERE [t].[work_order_number] NOT LIKE '%D'

Seems like `StartsWith() == false` and `EndsWith() == false` could use some work as well.

**Comment by rotem925** [comment]
Is there going to be a fix for that? Not using LIKE for StartsWith is a killer for optimization. It seems to me like we really need to be able to use the index in large tables.

**Comment by nomz0101** [comment]
Hi,
I am encountering major performance issues as well using StartsWith().
It seems like there must be a better solution to be able to get the query translated using the "LIKE" method. I am running on big tables with a lot of data.

I am not able to use the EF.Functions.Like solution because I am working with Generic Repository Pattern. Is there a workaround for this?

**Comment by roji** [comment]
@langdonx please try the latest 5.0.0-rc2 - for constant patterns (e.g. `EndsWith("D")`) we translate to a simple and efficient `LIKE %D`; same with StartsWith.

Non-constant patterns are trickier, though we have some plans for how to improve that as well (client-side parameter transformation).

**Comment by rotem925** [comment]
@langdonx Thank you for the quick response! 
We actually need this for non-constant array parameters(joined with a query)

Is there any workaround replacing the current StartsWith implementation with a custom one that uses Like? Till there is a fix? I mean overriding the current implementation. 

The current implementation is a killer for us with a non usable product. 
Using LIKE takes 30ms on a large table (since it uses the index).
Using current implementation take around 3000ms with arround 3000ms cpu time.

Thanks!

**Comment by roji** [comment]
You can always explicitly use LIKE by using EF.Functions.Like instead of StartsWith/EndsWith. But be careful - if your the pattern your matching contains special characters (%, _), you'll get incorrect results (that's why we don't currently translate non-constant StartsWith with LIKE).

**Comment by glen-84** [comment]
It's not even using `LIKE` for MySQL:

```sql
 WHERE (@__val_0 = '') OR (LEFT(`u`.`username`, CHAR_LENGTH(@__val_0)) = @__val_0))
```

Why is it doing this? I don't think that this can use an index. This is such a simple case (`startsWith`).

**Comment by roji** [comment]
@glen-84 when the pattern to be matched is a parameter, it's not possible to use LIKE since there may be wildcards in there (%, _); that would cause incorrect results. When the pattern is a constant, EF can detect the wildcards and properly escape them.

Compare StartsWith with a constant pattern:

```c#
_ = await ctx.Blogs.Where(b => b.Name.StartsWith("foo")).ToListAsync();
```

... which yields the following SQL:

```sql
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE [b].[Name] LIKE N'foo%'
```

... with StartsWith with a parameter pattern:

```c#
var pattern = "foo";
_ = await ctx.Blogs.Where(b => b.Name.StartsWith(pattern)).ToListAsync();
```

... which yields the following SQL:

```sql
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE (@__pattern_0 = N'') OR (LEFT([b].[Name], LEN(@__pattern_0)) = @__pattern_0)
```

Note that the above is on SQL Server - MySQL may be doing something different.

**Comment by glen-84** [comment]
I'm fairly new to EF, so forgive me if this is a silly question, but why can't EF escape the wildcards?

**Comment by roji** [comment]
@glen-84 EF Core currently does not support manipulating parameter data before sending it. Note that you still have the option of using LIKE by calling EF.Functions.Like instead of String.StartsWith; if you do that, you take the responsibility in case there are wildcards characters.

**Comment by glen-84** [comment]
Is there an issue to track support for this?

**Comment by roji** [comment]
This is currently tracked as part of #17598 ("client-side parameter transformations"), but I've split it out to #28028 as it's different (and probably simpler to implement).

**Comment by 4865783a5d** [comment]
@roji I've noticed that the current (EF Core 6 - with the Sql Server provider) translation provides non-sargable query when using StartsWith.

```tsql
and (@__request_Filter_0 = N'') OR (LEFT([g].[Name], LEN(@__request_Filter_0)) = @__request_Filter_0)
```

![image](https://github.com/dotnet/efcore/assets/8995460/0c8478d8-26a5-4d98-bff7-eb916d4d0137)

Leaving the empty-check, it can provide an optimized query plan. Wouldn't it be possible to perform the empty-check within the expression visitor?
```tsql
and (LEFT([g].[Name], LEN(@__request_Filter_0)) = @__request_Filter_0)
```
![image](https://github.com/dotnet/efcore/assets/8995460/2a1cf874-b032-4a60-abeb-f6b992943163)

**Comment by 4865783a5d** [comment]
@roji  Apologizes for leaving an important detail out. There was another, preceeding predicate causing this behavior.

```tsql
SELECT id FROM data WHERE Id > 4000 and Id < 5000 and LEFT(name, LEN(@p)) = @p;
SELECT id FROM data WHERE Id > 4000 and Id < 5000 and @p = N'' OR LEFT(name, LEN(@p)) = @p;
```
Resulting in a Index Seek and an Index Scan respectively.
```
SET STATISTICS IO ON	1	1	0	NULL	NULL	1	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	SET STATS	0	NULL
DECLARE @p NVARCHAR(255) = '10';	2	2	0	NULL	NULL	2	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	ASSIGN	0	NULL
SELECT id FROM data WHERE Id > 4000 and Id < 5000 and LEFT(name, LEN(@p)) = @p;	3	3	0	NULL	NULL	3	NULL	315.9115	NULL	NULL	NULL	0.008084604	NULL	NULL	SELECT	0	NULL
  |--Clustered Index Seek(OBJECT:([iam-manag].[dbo].[data].[PK__data__3213E83F414D3DA5]), SEEK:([iam-manag].[dbo].[data].[id] > (4000) AND [iam-manag].[dbo].[data].[id] < (5000)),  WHERE:(substring([iam-manag].[dbo].[data].[name],(1),len([@p]))=[@p]) ORDERED FORWARD)	3	4	3	Clustered Index Seek	Clustered Index Seek	OBJECT:([iam-manag].[dbo].[data].[PK__data__3213E83F414D3DA5]), SEEK:([iam-manag].[dbo].[data].[id] > (4000) AND [iam-manag].[dbo].[data].[id] < (5000)),  WHERE:(substring([iam-manag].[dbo].[data].[name],(1),len([@p]))=[@p]) ORDERED FORWARD	[iam-manag].[dbo].[data].[id]	315.9115	0.006828704	0.0012559	270	0.008084604	[iam-manag].[dbo].[data].[id]	NULL	PLAN_ROW	0	1
SELECT id FROM data WHERE Id > 4000 and Id < 5000 and @p = N'' OR LEFT(name, LEN(@p)) = @p;	4	5	0	NULL	NULL	4	NULL	100258.3	NULL	NULL	NULL	4.322624	NULL	NULL	SELECT	0	NULL
  |--Parallelism(Gather Streams)	4	6	5	Parallelism	Gather Streams	NULL	NULL	100258.3	0	0.05197924	11	4.322624	[iam-manag].[dbo].[data].[id]	NULL	PLAN_ROW	1	1
       |--Clustered Index Scan(OBJECT:([iam-manag].[dbo].[data].[PK__data__3213E83F414D3DA5]), WHERE:([@p]=N'' AND [iam-manag].[dbo].[data].[id]>(4000) AND [iam-manag].[dbo].[data].[id]<(5000) OR substring([iam-manag].[dbo].[data].[name],(1),len([@p]))=[@p]))	4	7	6	Clustered Index Scan	Clustered Index Scan	OBJECT:([iam-manag].[dbo].[data].[PK__data__3213E83F414D3DA5]), WHERE:([@p]=N'' AND [iam-manag].[dbo].[data].[id]>(4000) AND [iam-manag].[dbo].[data].[id]<(5000) OR substring([iam-manag].[dbo].[data].[name],(1),len([@p]))=[@p])	[iam-manag].[dbo].[data].[id]	100258.3	3.923125	0.1375196	270	4.060645	[iam-manag].[dbo].[data].[id]	NULL	PLAN_ROW	1	1
```

**Comment by henning-krause** [comment]
I have the same problem on fairly large tables where the current implementation does not use the indexes on the table. Because I'm using [Odata](https://github.com/OData/AspNetCoreOData), which operates on IQueryable alone and is not bound directly to Entity Framework, I'm not able to use the EF.Functions.Like solution.

**Comment by roji** [comment]
@henning-krause we can't do much with the above - you'll need to post the SQL which EF generates, as well as ideally the LINQ query.
