### ISSUE TITLE
Add type mapping support for additional store type postfix

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#11896]
MySQL specifies the store type for an Unicode string in this manner: "VARCHAR(20) CHARACTER SET utf8" which is currently not supported by `RelationalTypeMapping`.

**Comment by AndriySvyryd** [comment]
Instead of computing the store type in the constructor we should do it in a virtual method to allow it to be extended for other special cases like "varchar(max)"

**Comment by ajcvickers** [comment]
It would be good to consider allowing more general modifiers, such as those use for collations.

**Comment by twsI** [comment]
Is anyone already working on this?

**Comment by ajcvickers** [comment]
@twsI Nope. It's tentatively planned for 3.0, but no work has started that I know of.

**Comment by roji** [comment]
@ajcvickers I can take this.

**Comment by ajcvickers** [comment]
@roji Great! Assigned to you.

**Comment by ajcvickers** [comment]
Also see high-level collations issue #19866

**Comment by roji** [comment]
Did a bit of investigations into collations on PostgreSQL.

> MySQL specifies the store type for an Unicode string in this manner: "VARCHAR(20) CHARACTER SET utf8" which is currently not supported by RelationalTypeMapping.

PostgreSQL [supports](https://www.postgresql.org/docs/current/collation.html) something that *looks* similar:

```sql
CREATE TABLE test1 (
    a text COLLATE "de_DE",
    b text COLLATE "es_ES",
    ...
);
```

However, `COLLATE` is part of the column definition spec and not part of the type name, as the following doesn't work:

```sql
SELECT CAST('hello' AS text COLLATE 'en_US');
```

In that sense it's similar to NULL/NOT NULL, or DEFAULT. As a result, at least for PostgreSQL it seems to make more sense to have this as a standard migrations-only annotation rather than to make it part of the type mapping. The situation in MySQL may be similar or not (/cc @lauxjpn).

**Comment by AndriySvyryd** [comment]
@roji I agree. Was that the last thing you were going to do for this issue?

**Comment by ajcvickers** [comment]
@lauxjpn We discussed this issue today and decided based on @roji's latest work on collation that Npgsql no longer needs us to do anything here. Is this something that is still needed for MySQL?

**Comment by lauxjpn** [comment]
For MySQL, the following statements _are_ valid:

```sql
SELECT CONVERT('test', CHAR CHARACTER SET utf8mb4);
SELECT CAST('test' AS CHAR CHARACTER SET utf8mb4);
```

However, we also went the migrations annotation route and implemented `HasCharSet()` and `HasCollation()` extension methods for EF Core 3.0+, that can be used to set corresponding annotations (currently only on a column level, but table and database levels will be added for .NET 5).

We have planned to make the current behavior of adding the default char set and collation in our `RelationalTypeMappingSource` implementation obsolete and removing it for .NET 5.

So as far as I can see, we have no reservations against closing this issue.

---

If extending `RelationalTypeMapping` in a provider specific way is a route that needs to be taken in the future, a general approach like enabling the possibility to add annotations to it could be a viable way.
But of course providers are already implementing their concrete `RelationalTypeMapping` derived types, so they could just implement some provider specific interface in accordance with their requirements well.

It might still come in handy though in the future, to give `RelationalTypeMappingSource.FindMapping()` (read) access through `RelationalTypeMappingInfo` to the annotations of the property for which the `RelationalTypeMapping` is currently requested.
However, we currently don't have a concrete scenario for this anymore for Pomelo.

**Comment by ajcvickers** [comment]
Thanks @lauxjpn. Closing for now.
