### ISSUE TITLE
Allowing multiple IEnumerable implementations for an entity property

### ISSUE THREAD

**Issue by thombrink** [dotnet/efcore#11892]
Because there is no many to many implementation like in ef 6, I made my own prototype for making my life a bit easier. This prototype contains two implementations, one of the join entity and one of the entity I'm trying to manage. To make this less vague you will find a sample below.

Imagine I have a 'Users' and a 'Permissions' table. A user can have multiple permissions and a permission can have multiple users. This requires me to create a join table called 'UserPermissions'. Currently I have to write something like this to get everything working:

```c#
private ICollection<UserPermission> userPermissions = new List<UserPermission>();

public IReadOnlyCollection<Permission> Permissions => userPermissions.Select(x => x.Permission).ToList().AsReadOnly();
```

Code like this increases the chance of mistakes. Although there might be a much simpler way of archiving the desired result?

To solve this problem I created a so called 'ManyToManyList' class where I combine the UserPermission and Permission tables.

 ```c#
public class ManyToManyList<TJoinEnity, TResult> : List<TJoinEnity>, IList<TResult> where TJoinEnity : IJoinEntity, new() where TResult : Entity {
    //removed the actual code to make the example simpler
}
```

With the ManyToManyList I can define my property like this.
 ```c#
public ManyToManyList<UserPermission, Permission> Permissions { get; set; } = new ManyToManyList<UserPermission, Permission>();
```

The only problem that's causing this not to work is found in the 'TryGetElementType' method, which is found in 'SharedTypeExtensions.cs' located at 'src/Shared/'. This method currently checks if there is only one IEnumerable implementation and returns null if this is not the case.

Instead of returning 'null' when multiple implementations are found, it would be great if it just gave the first implementation. I know, this would make things ambiguous, but what about a method called 'TryGetFirstElementType'?

Forgive me if I'm totally pointing in the wrong direction or created some weird code :)

**Comment by smitpatel** [comment]
What is the rationale behind picking the first implementation? Why not second one?

**Comment by anpete** [comment]
@thombrink Have you seen this blog post series? https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics

**Comment by thombrink** [comment]
@smitpatel To make my prototype work as I intended it, it had to be the first implementation, because a base class obviously has to be the first implementation, which in my case was the ```List<UserPermission>``` class. Besides that I would pick the first one because you have to draw a boundary somewhere and the first one seems the most logical choice to me.

**Comment by thombrink** [comment]
@anpete Yes I did. That's how I currently implement the many-to-many structure. The problem that I have with that approach is that it feels unnatural to use. I don't want UserPermissions, I want the Permissions of the queried User. It would even better if I didn't need a link table at all (like in ef 6). That's the reason why I created this prototype.

**Comment by ajcvickers** [comment]
@thombrink What are you hoping to do with the Permissions navigation property? The only thing that immediately comes to mind is to use it in queries--for example, Include--but I'm pretty sure this won't work because it would be treated as a navigation to the join entity, so eager loading would load the join entities, but not the entities on the other side of the join.

**Comment by thombrink** [comment]
@ajcvickers Just everthing I want, select, add, update and delete. I already made that part work. For example, when I add an Permission to the 'ManyToManyList' it automaticly creates and adds an join entity.

I also added a safety check to be sure I don't add an item which is already present, this could be removed for performance issues of course.
```c#
        public void Add(TResult item)
        {
            var parameter = Expression.Parameter(typeof(TSource), "x");

            Expression prop = Expression.PropertyOrField(parameter, resultGuidProperty.Name);
            Expression predicate = Expression.Equal(prop, Expression.Constant(item.Id));

            var lambda = Expression.Lambda<Func<TSource, bool>>(predicate, parameter).Compile();

            var existing = base.Find(new Predicate<TSource>(lambda));
            if (existing != null) return;

            var newItem = new TSource();
            sourceGuidProperty.SetValue(newItem, entityKey);
            resultGuidProperty.SetValue(newItem, item.Id);

            base.Add(newItem);
        }
```

Because I tested everything with a in memory database, I didn't had the eager loading problem. 
To solve this I could add an Include extension which combines the Include and ThenInclude methods trough reflection.

Something like this psudocode (I will add some fully working code later on)
```c#
public static IIncludableQueryable<TJoinEnity, TEntity, TProperty> Include<TJoinEnity, TEntity, TProperty>(
            [NotNull] this ManyToMany<TJoinEnity, TEntity> source,
            [NotNull] Expression<Func<TJoinEnity, TProperty>> navigationPropertyPath)
            where TEntity : class
        {
               var includableQueryable = Include(source, navigationPropertyPath);

               var parameter = Expression.Parameter(typeof(TJoinEnity), "x");
               var name = //get the property name of the TEntity object 
               var body = Expression.PropertyOrField(parameter, name);
               var expr = Expression.Lambda<Func<TJoinEnity, TEntity>>(body, parameter);

               return includableQueryable.ThenInclude(expr);
        }
```

My lunch break is over so I will create a working example of the above code when I'm home.

**Comment by thombrink** [comment]
@ajcvickers I just updated my previous comment, it now contains a 'Include' method that's fully working (to keep things clear I will create a new comment next time)

**Comment by thombrink** [comment]
A safer version of the 'Include' method, which uses less reflection. 

```c#
        public static IQueryable<TEntity> Include<TEntity, TProperty, TJoinEntity>(
            this IQueryable<TEntity> source,
            Expression<Func<TEntity, ManyToManyList<TJoinEntity, TProperty>>> navigationPropertyPath)
            where TEntity : class
            where TProperty : Entity
            where TJoinEntity : class, IJoinEntity, new()
        {
            var memberExpression = navigationPropertyPath.Body as MemberExpression;
            var memberName = memberExpression.Member.Name;

            var propertyType = typeof(TProperty);
            var joinEntityType = typeof(TJoinEntity);

            var matchingProperties = joinEntityType.GetProperties().Where(x => x.PropertyType == propertyType);
            PropertyInfo property = null;
            foreach (var p in matchingProperties)
            {
                if(property == null)
                {
                    property = p;
                }
                else
                {
                    throw new Exception($"Multiple properties of the type '{propertyType.Name}' are not allowed.");
                }
            }

            if(property == null)
            {
                throw new Exception($"The type '{joinEntityType.Name} does not contain a property of the type '{propertyType.Name}.");
            }

            var propertyName = property.Name;

            return source.Include($"{memberName}.{propertyName}");
        }
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
