### ISSUE TITLE
Pooled DBs should remove contexts that fail to connect

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#11912]
Describe what is not working as expected.

I have started an application with a bad sql connection string, in the appsettings.

I realize this when I get the network issue error when a dbcontext is configured.

I fix the connection string in the config and have intermittent issues after the fix. I believe this is because the dbcontext with the bad connection string is still in the dbpool.

```
Exception message:
Stack trace:
```

### Steps to reproduce

1. setup a dbpool
2. put in a valid sql connection string pointing to a bad host.
3. after the first dbcontext is created change the connection string in the appsettings.
4. keep utilizing the DI to get the dbcontext and find that it will pull the bad dbcontext every once in a while

```c#
// setup
services.AddDbContextPool<BloggingContext>(
    options => options.UseSqlServer(configuration.GetSection("connections")["db"])); 
//this will check the configuration file each time so is not a constant after startup

public class homecontroller{
private readonly BloggingContext  _db;
public homecontroller(BloggingContext db){
_db = db;
}

public IActionResult Index(){
  db.Posts.ToListAsync()
}

}
```

### Further technical details
EF Core version:2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017 15.5

**Comment by ajcvickers** [comment]
@Tarig0 What do you mean by "setup a dbpool"?

**Comment by Tarig0** [comment]
Sorry, by setup I mean to use the addDBContextpool function to setup the DI

and then after the DBContext is constructed, it will be added to the pool even though it's connection is bad. Then if you fix the connection string in the config file and new dbcontexts will get the corrected connection string, but the first dbcontext can still come back.

**Comment by Tarig0** [comment]
I think I filed this in error
