### ISSUE TITLE
Resetting nav property after SaveChanges causes items to be added to change that should not be

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#11930]
I am working with EF Core 2.1 and I am not sure if this is an issue, but it is not desired. I have a blog and post class as below: 

```C#
public class Blog
{
	[Key]
	public int BlogId
	{ get; set; }

	public string Name
	{ get; set;}

	public ICollection<Post> Posts
	{ get; set; }
}

public class Post
{
	[Key]
	public int PostId
	{ get; set; }

	public string Title
	{ get; set; }
	
	public string Text
	{ get; set; }
	
	public int BlogId
	{ get; set; }
	
	public Blog Blog
	{ get; set; }
}

public BlogContext : DbContext
{
	public virtual DbSet<Blog> Blogs
	{ get; set; }

	public virtual DbSet<Post> Posts
	{ get; set; }

	public void ShowChangeTracker ()
	{
		foreach ( var dbEntityEntry in ChangeTracker.Entries () )
		{
			if ( dbEntityEntry.Entity == null )
				continue;

			switch ( dbEntityEntry.State )
			{
				case EntityState.Added:
					Debug.WriteLine ( "Entity ADDED " + dbEntityEntry.Entity.ToString () );
					break;
				case EntityState.Modified:
					Debug.WriteLine ( "Entity MODIFIED " + dbEntityEntry.Entity.ToString () );
					break;
				case EntityState.Deleted:
					Debug.WriteLine ( "Entity DELETED " + dbEntityEntry.Entity.ToString () );
					break;

				case EntityState.Detached:
					Debug.WriteLine ( "Entity DETACHED " + dbEntityEntry.Entity.ToString () );
					break;
			}
		}
	}
}
```

We have a class with an update method as shown below. In this case we are passing in a list or posts that belong to the same blog, and the blog has already been created. Each post has its Blog nav property set and each blog will have a list of posts. The update clears the Blog property and then sets the Blog nav property to null, while setting the BlogId of the post. SaveChanges is called, and before restoring the Blog nav property we call ShowChangeTracker. And we expect nothing in the ChangeTracker because SaveChanges has cleared everything, which is the case. We reset the Blog nav property and call ShowChangeTracker again. The state of the change tracker now shows the Blog as added, and all its posts as added. The Blog has already been saved, and we are working on the posts attached to it. This causes another save to be done and repeated for every post. Is seeing the Blog and its post after resetting the Blog nav property, in the ChangeTracker, an expected result?

```C#
public PostRepo
{
	internal List<int> UpdateInternal ( BlogContext context, List<Post> items )
	{
		for ( int i = 0; i < items.Count; i++ )
		{
			var item = items [ i ];

			// clear nav properties per article below
			// this is only needed when services are in proc
			// Note:
			// https://msdn.microsoft.com/en-us/magazine/dn166926.aspx

			Blog savedBlog = null;
			if ( item.Blog != null )
			{
				item.BlogId = item.Blog.BlogId;
				savedBlog = item.Blog;

				item.Blog = null;
			}

			if ( item.PostId == 0 )
			{
				context.Posts.Add ( item );
			}
			else
			{
				var p = context.Posts.Find ( item.PostId );
				if ( p == null )
					throw new InvalidOperationException ( "Posts was not found " + item.PostId );

				context.Posts.Attach ( p );

				var a = context.Entry ( p );
				if ( a != null )
					a.CurrentValues.SetValues ( item );
			}

			context.SaveChanges ();
			///////////////////////////////////
			// restore nav properties
			///////////////////////////////////

			if ( savedBlog != null )
			{
				context.ShowChangeTracker ();
				item.Blog = savedBlog;
				context.ShowChangeTracker ();
			}
		}
	}
}
```

**Comment by ajcvickers** [comment]
@dgxhubbard The behavior is expected, but the real question is what is the intention here? Assuming that:
* Posts have store-generated keys
* Each Post is already associated with an existing Blog
* The intention is to insert any new Posts

Then this should work:
```C#
foreach(var post in items)
{
    context.Attach(post.Blog);
}
context.SaveChanges();
```
Since Attach is a graph operation it will start tracking both the Blog (as Unchanged) and each associated Post. Each Post will be Added if its Id is zero, or Unchanged if its Id has already been set.
