### ISSUE TITLE
One-to-one relationship not setting foreign key on save

### ISSUE THREAD

**Issue by nathankodilla** [dotnet/efcore#11947]
I have a one-to-one optional relationship, and when I set the dependent on the parent and save, it does not fill in the dependent id. It does save an entry into the dependent class table that is correct for its foreign key to the parent.

### Steps to reproduce
```c#
class ParentClass
{
  public int ID { get; set; }
  [ForeignKey("DependentID")]
  public DependentClass Dependent { get; set; }
  public int? DependentID { get; set; }
}

class DependentClass
{
  public int ID { get; set; }
  [ForeignKey("ParentID")]
  public ParentClass Parent { get; set; }
  public int ParentID {get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  modelBuilder.Entity<ParentClass>(entity =>
  {
                entity.HasOne(e => e.Dependent)
                      .WithOne(e => e.Parent)
                      .HasForeignKey<DependentClass>(e => e.ParentID )
                      .OnDelete(DeleteBehavior.Cascade);
  };
}
```

```c#
ParentClass parent = new ParentClass();
parent.Dependent = new DependentClass()
{
  Parent = parent
};

dbContext.SaveChanges();
// parent.DependentID is still null and null in the parent class table
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL

**Comment by ajcvickers** [comment]
@nathankodilla Can you clarify the semantics of "DependentID" and how it is mapped? Specifically, the code in OnModelCreating creates:
* A single relationship between ParentClass and DependentClass
* Uses the "Dependent" and "Parent" navigation properties for this relationship
* Specifies DependentClass.ParentID as the foreign key property for the relationship

Given that:
* Each relationship can only have one foreign key defined
* Multiple relationships cannot share navigation properties

Then what is "DependentID"?

**Comment by nathankodilla** [comment]
That appears to be a misunderstanding on my part then. I wanted "DependentID" to also be a foreign key back to the singular Dependent.
