### ISSUE TITLE
Property not being ignored by EntityTypeBuilder

### ISSUE THREAD

**Issue by CheloXL** [dotnet/efcore#11948]
I have a couple of classes that are extended and used as entities. I configure the navigation properties (and the properties to ignore) through the ModelBuilder.ApplyConfiguration methods.
When trying to run the application, I'm getting the exception "A key cannot be configured on 'CountryEf' because it is a derived type...". 

The thing is, the only reference to the *base* class is a property that I already ignored in the builder.
Making the setter private, removing the property, or ignoring the whole class in the modelbuilder (modelBuilder.Ignore<Country>()) makes the problem disappear. But those are more like workarounds.

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.DependencyInjection;

namespace ConsoleAppCore
{
	internal static class Program
	{
		public static void Main(string[] args)
		{
			var services = new ServiceCollection();
			services.AddDbContext<TestDBContext>(o => o.UseInMemoryDatabase("test"));
			var provider = services.BuildServiceProvider();

			using (var ctx = provider.GetService<TestDBContext>())
			{
				ctx.Database.EnsureCreated();
			}

			provider.Dispose();
		}
	}

	public class Country
	{
		public string Id { get; set; }
	}

	public sealed class CountryEf : Country { }

	public class State
	{
		public string Id { get; set; }
		public Country Country { get; set; }
	}

	public sealed class StateEf : State
	{
		public CountryEf CountryEf { get; set; }
		public string CountryId { get; set; }
	}

	public abstract class EfContext<T> : DbContext where T : EfContext<T>
	{
		protected EfContext(DbContextOptions<T> options)
			: base(options) { }
	}

	public sealed class TestDBContext : EfContext<TestDBContext>
	{
		/// <inheritdoc />
		public TestDBContext(DbContextOptions<TestDBContext> options) : base(options) { }

		public DbSet<CountryEf> Countries { get; set; }
		public DbSet<StateEf> States { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			//modelBuilder.Ignore<Country>();
			modelBuilder.ApplyConfiguration(new StateConfiguration());
			modelBuilder.ApplyConfiguration(new CountryConfiguration());
		}
	}

	internal sealed class CountryConfiguration : IEntityTypeConfiguration<CountryEf>
	{
		public void Configure(EntityTypeBuilder<CountryEf> builder)
		{
			builder.HasKey(x => x.Id);
		}
	}

	internal sealed class StateConfiguration : IEntityTypeConfiguration<StateEf>
	{
		public void Configure(EntityTypeBuilder<StateEf> builder)
		{
			builder.HasKey(x => x.Id);
			builder.Ignore(x => x.Country);

			builder.HasOne(x => x.CountryEf)
				.WithMany()
				.HasForeignKey(x => x.CountryId);
		}
	}
}
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Win10
IDE: (e.g. Visual Studio 2017 15.7.1)

**Comment by ajcvickers** [comment]
@CheloXL This is a limitation in the system for ignoring entities. While ignoring the navigation property should prevent the entity type from being in the model, due to performance reasons this doesn't work in some cases where an entity type has already been discovered and has contributed to model building. We don't intend to fix this because it would be very expensive, perf wise, to do so, and the workaround of ignoring the entire type seems reasonable. If there is some reason that you cannot ignore at the type-level, then please let us know.

**Comment by MesquitaEngineer** [comment]
I have a similar problem. But it is already trying to ignore the type (Pessoa).

My Base Context

 public abstract class BaseDbContext : DbContext
    {    
        public DbSet<Pessoa> Pessoas { get; set; }
         public DbSet<Membro> Membros { get; set; }
        
    }

My derived context

public class ConmembDbContext : BaseDbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();
            optionsBuilder.UseSqlServer(config.GetConnectionString("Conmemb"));
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Ignore<Pessoa>();
            modelBuilder.ApplyConfiguration(new MembroMap());
         }
        
    }

my configured to membro Map;

public class MembroMap : IEntityTypeConfiguration<Membro>
    {
        public void Configure(EntityTypeBuilder<Membro> builder)
        {
            builder.ToTable("tblMembros");

            builder.HasKey(b => b.codigo);
            builder.Property(b => b.codigo).HasColumnName("iCodigo").HasConversion<System.Int16>();
            builder.Ignore(b => b.codigoPessoa);
            
            //builder.Ignore(p => p.pessoa);

            //builder.HasOne(p => p.pessoa)
            //    .WithMany(p => p.membro)
            //    .HasForeignKey(p => p.codigoPessoa);
         
         }
    }

 public class Membro
    {
        public int codigo { get; set; }
        public int? codigoPessoa { get; set; }

        public Pessoa pessoa { get; set; }
     }

public class Pessoa
    {
        public int codigo { get; set; }
       
        public ICollection<Membro> membro { get; set; }
     }


I getting error in execution time:
"the entity type 'Pessoa' requires a primary key".

If i set key in Pessoa.Codigo, I getting erron: 
"The  property invalid 'PessoaCodigo' name.

Why?

**Comment by AdamJachocki** [comment]
Another one, really don't know what to do with this. I have a simple mechanism to map ONLY the properties that I want (like in nHibernate, actually I came from nHibernate), it's simple:

```
public class MyDbContext: IDentityDbContext<SystemUser, UserRole, Guid>
{

	protected override void OnModelCreating(ModelBuilder builder)
	{
		builder.Entity<Document>().Ignore(x => x.ParentDocument); //my last try
			
		builder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
	}
}
```

Now, I have one base class implementing IEntityTypeConfiguration. And it looks basically like this:

```
abstract class BaseMap<T>: IEntityTypeConfiguration<T> where T: class, IDbItem
{
	EntityTypeBuilder<T> theBuilder;
	List<string> mappedPropertyNames = new List<string>();

	protected EntityTypeBuilder ToTable(string tableName)
	{
		return theBuilder.ToTable(tableName);
	}

	protected PropertyBuilder<TProperty> Map<TProperty>(Expression<Func<T, TProperty>> x)
	{
		mappedPropertyNames.Add(GetPropertyName(x)); 
		return theBuilder.Property(x);
	}

	//other protected methods like HasOne and so on (removed for clarity), which work exactly like Map()

	protected abstract void CreateModel(SchemaInfo<T> schemaInfo);

	public void Configure(EntityTypeBuilder<T> builder)
	{
		theBuilder = builder;

		Map(x => x.Id).ValueGeneratedOnAdd();
		builder.HasKey(x => x.Id);

		SchemaInfo<T> si = new SchemaInfo<T>();
		si.Builder = builder;
		si.DatabaseType = DbInitializer.DatabaseType;

		CreateModel(si);		

		IgnoreUnmappedProperties(builder);
		
	}

	void IgnoreUnmappedProperties(EntityTypeBuilder<T> builder)
	{
		//Debugger.Launch();
		PropertyInfo[] propsInModel = typeof(T).GetProperties(BindingFlags.Instance | BindingFlags.Public);
		foreach (var prop in propsInModel)
		{
			if (!mappedPropertyNames.Contains(prop.Name))
			{
				builder.Ignore(prop.Name);
			}
		}
	}
}
```

So the idea is simple. I have to derive from BaseMap and then Map only those properties that I really want to be in database. Next, my base map just Ignores every other property that hasn't been added explicitily by my, for example:

```
class DocumentMap : BaseMap<Document>
{
	protected override void CreateModel(SchemaInfo<Document> si)
	{
		ToTable("documents");

		//Map(x => x.Name).IsRequired().HasMaxLength(255);
		//Map<Guid>("Owner_id").IsRequired();

		//HasMany(x => x.Periods)
		//	.WithOne(y => y.ParentDocument);

		//HasMany(x => x.Loans)
		//	.WithOne(y => y.ParentDocument);


		Map(x => x.Name).IsRequired();
		Map<Guid>("Owner_id").IsRequired();

		HasOne(x => x.Owner)
			.WithMany()
			.HasForeignKey("Owner_id")
			.HasConstraintName("FK_Users_Documents")
			.IsRequired()
			.OnDelete(DeleteBehavior.Cascade);

		HasMany(x => x.Periods)
			.WithOne(y => y.ParentDocument);

		HasMany(x => x.Loans)
			.WithOne(y => y.ParentDocument);
	}
}
```

My Document model, unfortunately has property (derived from other classes): ParentDocument. As you can see, I don't map in here, so it should be Ignored. And as I debug my app, I can see that this property it's really ignored in my BaseMap class. It works as it should. But then I get an exception:

> Unable to determine the relationship represented by navigation property 'Document.ParentDocument' of type 'Document'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

So, what's the solution?

**Comment by AndriySvyryd** [comment]
@AdamJachocki Please file a new issue with a small runnable project
