### ISSUE TITLE
Consider using backing field to determine whether or a property is a navigation

### ISSUE THREAD

**Issue by TangoSensory** [dotnet/efcore#11946]
I have the following model properties:

```C#
public virtual IList<ExchangeMarketSnapshot> DuringEventExchangeMarketSnapshots
 => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot)
          .OrderBy(d => d.TimeCreated).Where(d => d.TimeCreated >= StartTime)
          .ToList();

[InverseProperty("CoinPairEvent")]
public virtual ICollection<CoinPairEvent_ExchangeMarketSnapshot> 
    CoinPairEvent_ExchangeMarketSnapshots { get; set; }
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
System.InvalidOperationException: 'No field was found backing property 'DuringEventExchangeMarketSnapshots' of entity type 'CoinPairEvent'. Lazy-loaded navigation properties must have backing fields. Either name the backing field so that it is picked up by convention or configure the backing field to use.'

If I remove the "virtual" keyword from the DuringEventExchangeMarketSnapshots calculated property I see a different exception:
Unable to cast object of type 'ConcreteTypeMapping' to type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping'
as per [https://github.com/aspnet/EntityFrameworkCore/issues/11704](url)

```

### Steps to reproduce
The exception occurs at the first bit of EF code that is called upon application startup:

`                eventDefinitions = context.EventDefinitions
                    .Include(x => x.EventDefinition_EventStartTriggers).ThenInclude(x => x.EventStartTrigger)
                    .Include(x => x.EventDefinition_EventExitTriggers).ThenInclude(x => x.EventExitTrigger)
                    .ToList();`

the exact same exception also occurs if I comment out the .Include()'s

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: W10
IDE: Visual Studio 2017 15.7.0 Preview 5

**Comment by ajcvickers** [comment]
@TangoSensory A couple of things:
* The message "Unable to cast object of type 'ConcreteTypeMapping' to type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping'" is an indication that packages from multiple releases are being mixed--see #11704
* Assuming the package versions are correct, then "DuringEventExchangeMarketSnapshots" being defined as a navigation property is very strange. Can you post a runnable project/solution or complete code listing, or at least the model types and configuration, that results in this?

**Comment by TangoSensory** [comment]
I checked versions again - and netcoreapp was on a different version (now 2.1.0.rc1)

Ok, so still seeing the same "System.InvalidOperationException: 'No field was found backing property 'DuringEventExchangeMarketSnapshots'...." exception - occurring at the same point

If I remove the virtual keyword, I now get a different exception:

System.InvalidOperationException: 'Navigation property 'DuringEventExchangeMarketSnapshots' on entity type 'CoinPairEvent' is not virtual. UseLazyLoadingProxies requires all entity types to be public, unsealed, have virtual navigation properties, and have a public or protected constructor.'

I can't post the project but here's the "CoinPairEvent" class

`
    public class CoinPairEvent
    {
        public CoinPairEvent() : this(new CoinPair())
        {
        }

        public CoinPairEvent(CoinPair coinPair)
        {
            CoinPair = coinPair;
            StartTime = DateTime.UtcNow;
            LastUpdated = DateTime.UtcNow;
            this.PlacedOrders = new List<PortfolioOrder>();
            this.CoinPairEvent_ExchangeMarketSnapshots = new List<CoinPairEvent_ExchangeMarketSnapshot>();
            this.Exchange_CoinPairEvents = new List<Exchange_CoinPairEvent>();
        }

        public int Id { get; set; }

        [InverseProperty("CoinPairEvent")]
        public virtual ICollection<Exchange_CoinPairEvent> Exchange_CoinPairEvents { get; set; }
        public DateTime LastUpdated { get; set; }

        //public int CoinPairId { get; set; }

        //[ForeignKey("CoinPairId")]
        public virtual CoinPair CoinPair { get; set; }

        public int? ParentCoinPairEventId { get; set; }

        [ForeignKey("ParentCoinPairId")]
        public virtual CoinPairEvent ParentCoinPairEvent { get; set; }


        //public int EventDefinitionId { get; set; }

        //[ForeignKey("EventDefinitionId")]
        public virtual EventDefinition EventDefinition { get; set; }

        public EventType EventType => EventDefinition == null ? EventType.Unknown : EventDefinition.EventType;

        //public int? StartTriggerId { get; set; }

        //[ForeignKey("StartTriggerId")]
        public virtual EventStartTrigger StartTrigger { get; set; }

        public int? FirstValidationTriggerId { get; set; }

        [ForeignKey("FirstValidationTriggerId")]
        public virtual EventStartTrigger FirstValidationTrigger { get; set; }

        public bool IsValidated => FirstValidationTrigger != null;

        public int? SecondValidationTriggerId { get; set; }

        [ForeignKey("SecondValidationTriggerId")]
        public virtual EventStartTrigger SecondValidationTrigger { get; set; }

        public bool IsDoubleValidated => SecondValidationTrigger != null;

        //public virtual EventCloseDefinition CloseTrigger { get; set; }
        public DateTime StartTime { get; set; }

        public int SecondsSinceEventStart => (DateTime.UtcNow - this.StartTime).Seconds;

        public DateTime? FirstValidationTime { get; set; }
        public DateTime? SecondValidationTime { get; set; }

        public DateTime? CloseTime { get; set; }

        public int? ExitTriggerId { get; set; }

        [ForeignKey("ExitTriggerId")]
        public virtual EventExitTrigger ExitTrigger { get; set; }
        public DateTime? ExitTime { get; set; }

        public decimal StartPrice { get; set; }
        public decimal? FirstValidationPrice { get; set; }
        public decimal? SecondValidationPrice { get; set; }
        public decimal? ExitPrice { get; set; }


        public virtual RiskProfile RiskProfile => StartTrigger.RiskProfile;

        public virtual IList<ExchangeMarketSnapshot> PriorToEventExchangeMarketSnapshots => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderBy(d => d.TimeCreated).Where(d => d.TimeCreated < StartTime).ToList();
        public IList<ExchangeMarketSnapshot> DuringEventExchangeMarketSnapshots => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderBy(d => d.TimeCreated).Where(d => d.TimeCreated >= StartTime).ToList();

        [InverseProperty("CoinPairEvent")]
        public virtual ICollection<CoinPairEvent_ExchangeMarketSnapshot> CoinPairEvent_ExchangeMarketSnapshots { get; set; }

        public virtual ExchangeMarketSnapshot StartExchangeMarketSnapshot => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderBy(d => d.TimeCreated).First();
        public virtual ExchangeMarketSnapshot LatestExchangeMarketSnapshot => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderByDescending(d => d.TimeCreated).First();

        public virtual ExchangeMarketSnapshot MaxExchangeMarketSnapshot => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderByDescending(d => d.MaxPrice).First();
        public decimal MaxPrice => MaxExchangeMarketSnapshot != null ? MaxExchangeMarketSnapshot.MaxPrice : default(decimal);
        public virtual ExchangeMarketSnapshot MinExchangeMarketSnapshot => CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderBy(d => d.MinPrice).First();
        public decimal MinPrice => MinExchangeMarketSnapshot != null ? MinExchangeMarketSnapshot.MinPrice : default(decimal);
        public ExchangeMarketSnapshot ExitExchangeMarketSnapshot
        {
            get
            {
                if (ExitTrigger != null)
                {
                    return CoinPairEvent_ExchangeMarketSnapshots.Select(c => c.ExchangeMarketSnapshot).OrderByDescending(d => d.TimeCreated).First(d => d.TimeCreated < ExitTime);
                }
                else
                {
                    return null;
                }
            }
        }

        [InverseProperty("CoinPairEvent")]
        public virtual ICollection<PortfolioOrder> PlacedOrders { get; set; }

        public virtual IList<PortfolioOrder> FilledOrders => this.PlacedOrders.Where(x => x.IsFilled)?.ToList();

        public virtual IList<PortfolioOrder> OpenOrders => this.PlacedOrders.Where(x => !x.IsFilled && !x.IsRemoved)?.ToList();

        public virtual IList<PortfolioOrder> RemovedOrders => this.PlacedOrders.Where(x => x.IsRemoved)?.ToList();
    }
`

Also the EventDefinition class:

`
   public class EventDefinition
    {
        public int Id { get; set; }

        public int EventTypeEnumIndex { get; set; }

        public EventType EventType => (EventType)EventTypeEnumIndex;


        [InverseProperty("EventDefinition")]
        public virtual ICollection<EventDefinition_EventExitTrigger> EventDefinition_EventExitTriggers { get; set; }

        [InverseProperty("EventDefinition")]
        public virtual ICollection<EventDefinition_EventStartTrigger> EventDefinition_EventStartTriggers { get; set; }

        //public virtual ICollection<EventDefinition_EventCloseDefinition> EventDefinition_EventCloseDefinitions { get; set; }

        [InverseProperty("EventDefinition")]
        public virtual ICollection<EventDefinition_EventAction> EventDefinition_EventActions { get; set; }

        // TODO ActionTriggerTypes
        public virtual IList<EventAction> StartActions => EventDefinition_EventActions?.Select(e => e.EventAction).Where(a => a.ActionTriggerType == ActionTriggerType.Start).ToList();
        public virtual IList<EventAction> CloseActions => EventDefinition_EventActions?.Select(e => e.EventAction).Where(a => a.ActionTriggerType == ActionTriggerType.Close).ToList();
    }
`

**Comment by ajcvickers** [comment]
@TangoSensory Is "DuringEventExchangeMarketSnapshots" intended to be a navigation property in the EF model? That is, is it intended to be directly associated with an FK in the database? Also, are you creating the database from this model (using Migrations) or are you mapping to an existing database?

**Comment by TangoSensory** [comment]
Hi

I am creating the database via migrations yes. 

Not sure how to describe DuringEventExchangeMarketSnapshots... it's just a "filtered" collection from the CoinPairEvent_ExchangeMarketSnapshots navigation property (which corresponds to the many-many join table between CoinPairEvent and ExchangeMarketSnapshot)

`
    public class CoinPairEvent_ExchangeMarketSnapshot
    {
        public int ExchangeMarketSnapshotId { get; set; }
        public int CoinPairEventId { get; set; }

        [ForeignKey("ExchangeMarketSnapshotId")]
        public virtual ExchangeMarketSnapshot ExchangeMarketSnapshot { get; set; }

        [ForeignKey("CoinPairEventId")]
        public virtual CoinPairEvent CoinPairEvent { get; set; }
    }
`

Further observations:
If I comment out DuringEventExchangeMarketSnapshots, the same exception occurs but for one of the other similar expression bodied properties.

Switching to the older style "getter" syntax produces exactly the same results (unsurprisingly) - ie.

`        public virtual IList<ExchangeMarketSnapshot> DuringEventExchangeMarketSnapshots
        {
            get
            {
                return CoinPairEvent_ExchangeMarketSnapshots?.Select(c => c.ExchangeMarketSnapshot).OrderBy(d => d.TimeCreated).Where(d => d.TimeCreated >= StartTime).ToList();
            }
        }
`

**Comment by ajcvickers** [comment]
@TangoSensory This is what I think is happening:
* EF is detecting these properties as navigation properties, even though they are not intended to be
  * This results in FKs in the model for these relationships--if you look in the database table there should be additional FK columns that you're not expecting
  * Even though EF is treating this as a relationship, and may even be making updates to the FKs, it is not impacting the functionality of the application because, in essence, the FKs are ignored by the navigation properties.
* Navigation properties used for lazy-loading need to be backed by a field. Since these properties have no field the exception is thrown.

If this is correct then:
* The fix is to use the [NotMapped] attribute to tell EF that these properties are not navigation properties.
* We should consider if there is anything we can/should do in this case to not detect these as navigation properties.

/cc @AndriySvyryd @divega

**Comment by ajcvickers** [comment]
Triage: Next time we are able to make breaking changes we should consider whether or not discovering a backing field should influence us treating a property as a navigation by convention.

**Comment by TangoSensory** [comment]
Sorry for the delay - had a death in the family.

Thanks for the update. 

Definitely smells like a bug to me - I'll try the workaround, but really don't think it should be required for calculated properties like these

**Comment by ajcvickers** [comment]
Planning update: we decided not to do this independently of the more general feature tracked in #4356
