### ISSUE TITLE
QueryTypeBuilder.ToQuery is missing from the API Browser

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#11952]
I didn't know where to report this so ...here you go!

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.querytypebuilder?view=efcore-2.1

**Comment by dend** [comment]
This should be assigned to me. @julielerman 

cc: @danroth27 @Eilon

**Comment by divega** [comment]
Actually, the method is only defined on the generic version of the class. Cc @anpete to confirm that this is by design.

**Comment by julielerman** [comment]
Found it. Mea culpa. Sorry

Sent from my *** Phone

On May 10, 2018, at 2:10 AM, Diego Vega <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, the method is only defined on the generic version of the class. Cc @anpete<https://github.com/anpete> to confirm that this is by design.
