### ISSUE TITLE
EF Core 2.1.0-rc1-final bug with using DevArt dotConnector for Oracle.

### ISSUE THREAD

**Issue by sunshykin** [dotnet/efcore#11960]
I ve tried to use DB-First and it successfully produced classes + context. It's even saves new entities to DB. BUT when I try ENumerate Entities (foreach entity in db.Entities) it falls with an exception on trying get element (debugger on "in").

Also wrote to DevArt support, but exception handles with using last stable version of EF Core, so I think it's more yours area of fixing.

```
Exception message:
System.MissingMethodException: "Method not found: 'Void Microsoft.EntityFrameworkCore.Query.Sql.QuerySqlGeneratorDependencies..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory, Microsoft.EntityFrameworkCore.Storage.ISqlGenerationHelper, Microsoft.EntityFrameworkCore.Storage.IParameterNameGeneratorFactory, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
```

### Steps to reproduce
It's produces on the last and prev versions of Devart.Data.Oracle.EFCore. 
Last stable EFCore also doesnt have this problem.

```c#
 using (var db = new ModelContext())
            {
                foreach (var dept in db.Entities)
                {
                    //...
                }
            }
```

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Devart.Data.Oracle.EFCore 9.5.502
Operating system: Win 10 x64
IDE: Visual Studio 2017 15.6.7

**Comment by ajcvickers** [comment]
@sunshykin The DevArt provider should not be calling the QuerySqlGeneratorDependencies constructor--this is very clearly documented on the constructor.

**Comment by sunshykin** [comment]
@ajcvickers, ok, I'll transfer that to them, thx.
Just a bit weird it's working last stable version with calling this constructor and now not
