### ISSUE TITLE
Can't Enable-Migrations or Add-Migration : The term 'xxx' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by jbuiss0n** [dotnet/efcore#1196]
Hello,

I don't know if i'm in the right place to ask my question, sorry if not.

I want to try some little things using EF Code migrations, so i've created a new **ASP.NET 5 Console Application**, using Visual Studio 2015 Preview.
I then just go to my **Package Manager Console**, and put `Install-Package EntityFramework -Pre`. Everything is ok, i've the right dependencies in my **project.json**.

I write some code, adding a BlogContext with 2 little entities (Blog / Post), everything looks fine, as i just copy/paste the sample here https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Traditional-.NET-Applications.

Finally, i want to enable migrations, so i'm back in my **Package Manager Console**, and put `Enable-Migrations` but this error happens :  `The term 'Enable-Migrations' is not recognized as the name of a cmdlet`.

As this command is not indicated in the EF wiki, i proceed to directly execute the command `Add-Migration MyFirstMigration`, but same error: `The term 'Add-Migration' is not recognized as the name of a cmdlet`.

I've tried to reboot VS, to reboot Windows, to re-install Nuget, to reset the **Nightly Builds** packages source, but nothing went better...

So, i tried the exact same things using VS 2013 Update 4 and a classic Console Application, and it works fine !

But i really want to use ASP.NET 5, and the K projets style... Do someone have any idea about my problem ? Did i miss something ?

Thanks,
Jeremy

**Comment by egorpavlikhin** [comment]
@bricelam your blog doesn't work.
And I'm still getting this error in 7.0.0-beta3-11980

    G:\!Projects\Hostilling\src\Hostilling>k ef migration add 0001
    Using context 'ApplicationDbContext'.
    System.InvalidOperationException: No service for type 'Microsoft.Data.Entity.Infrastructure.DbContextService`1[Microsoft.Data.Entity.Relational.Migrations.Infrastructure.Migrator]' has been registered.
    at M icrosoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
    at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
    at Microsoft.Data.Entity.Commands.MigrationTool.CreateMigrator(DbContext context)
    at Microsoft.Data.Entity.Commands.MigrationTool.CreateScaffolder(DbContext context)
    at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String rootNamespace, String projectDir)
    at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context)
    at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass5_1.<Main>b__6()
    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
    at Microsoft.Data.Entity.Commands.Program.Main(String[] args)

**Comment by egorpavlikhin** [comment]
Figured it out:
This code must be in Startup.cs public void ConfigureServices(IServiceCollection services) method, not anywhere else, otherwise it won't work.

    services
        .AddEntityFramework(Configuration)
        .AddSqlServer();

**Comment by rowanmiller** [comment]
@egorpavlikhin - correct, we match that method by convention. We do have an item to make all this more robust by RTM.

**Comment by julielerman** [comment]
Hey I just want to clarify something here. I'm NOT using aspnet5 but instead a basic full .NET app ..console (and yes, I understand that it's not recommended, I'm just using that to explore) Instead of having a paramterless ctor on dbcontext and specifying UseSqlServer with connection string in onconfiguration, I am passing in the dbcontextoptions. So in this scenario, if I am not using d.i., I won't succeed with migrations, right? Therefore if I just want to show how you could continue to use migrations in a familiar way, I either have to use DI (on my own since not using aspnet5 or mvc etc) or I have to just go back to the "not grown up" <grin> pattern of usesqlserver with connection string in onconfiguring, right?

**Comment by AngelVenchev** [comment]
Hi, I still get this error with the latest version.

	D:\Programs\VS2015-Projects\MovieAngularJSApp\src\MovieAngularJSApp>k ef migration add initial
	Using context 'MoviesAppContext'.
	System.InvalidOperationException: No service for type 'Microsoft.Data.Entity.Infrastructure.DbContextService`1[Microsoft.Data.Entity.Relational.Migrations.Infrastructure.Migrator]' has been registered.
   		at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   		at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   		at Microsoft.Data.Entity.Commands.MigrationTool.CreateMigrator(DbContext context)
   		at Microsoft.Data.Entity.Commands.MigrationTool.CreateScaffolder(DbContext context)
   		at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String rootNamespace, String projectDir)
   		at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context)
   		at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass5_1.<Main>b__6()
   		at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   		at Microsoft.Data.Entity.Commands.Program.Main(String[] args)</code>

**Comment by julielerman** [comment]
I haven't done it in a few weeks, but have not had any problems with k ef migrations. The fact that it says no migrator registered makes me wonder if you've specified the provider somewhere. If not, here are ways to do that in an aspnet5 app: https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext#dependency-injection-scenarios

**Comment by 0xdeafcafe** [comment]
Did you ever get this fixed @AngelVenchev ? I'm not getting this bug locally, but when I deploy to azure though git I get it.

**Comment by AngelVenchev** [comment]
@0xdeafcafe I fixed it when I implemented with another configuration from @julielerman 's link.

**Comment by Vassi** [comment]
I'm assuming this currently also does not work if your context is elsewhere than the Web project. I don't like having the context and EF code in my web project so it usually moves into some Service assembly. In EF6 this is kind of similar where you have to make your web project the default startup, but tell the Package Manager console that you're targeting the assembly with the DbContext in it. There doesn't seem to be an equivalent right now for k ef, is that accurate? 

It complains theres no context if I run it in the web project folder and won't even recognize the k ef command in the services project folder, despite the Commands assembly being referenced there.

I understand it's a work in progress, I'm just trying to confirm that I'm not missing anything.

**Comment by ardalis** [comment]
Ran into this same issue as Vassi with ASP.NET 5 and using a separate project for EF. Currently there seems to be no way to refer to the connection string defined in the web project's config file when running migrations from the command line. My latest problem with CTP6 and a standard sample ASP.NET 5 project (after hard-coding the connection string) is that migrations are failing with "ALTER TABLE DROP COLUMN failed because column 'NormalizedEmail-' does not exist in table AspNetUsers. Not sure why that's happening...

**Comment by rowanmiller** [comment]
@ardalis - That latest issue is a bug with the scaffolded code. @bricelam is working on a fix... but in the meantime you just need to fix the scaffolded code to make sure it gets the right overload of `ForeignKey(...)`. Here is what the change looks like https://github.com/rowanmiller/UnicornStore/commit/b71cfc1ff155d0d580e4ca7fd70c4d019982cef3#diff-ead41050d624017563d55a02d52ab1e1R56

**Comment by rowanmiller** [comment]
@ardalis - Should also mention that we don't pick up Startup.cs from another project yet... so hardcoding connection string in UseSqlServer in OnConfiguring is the correct workaround.

**Comment by luisrudge** [comment]
@rowanmiller if I hardcode the connection string, I won't be able to publish to azure and use a different database.

**Comment by 0xdeafcafe** [comment]
I had this issue @luisrudge, what I did was check if `Configuration` in `Startup` was null, if it was, initialize a new one, and use that to check for connection strings in `config.json` or environment variables. This is my `OnConfiguring`:

```csharp
protected override void OnConfiguring(DbContextOptions options)
{
	var config = Startup.Configuration
		?? new Configuration()
			.AddJsonFile("config.json")
			.AddEnvironmentVariables();

	options.UseSqlServer(config.Get("Data:DefaultConnection:ConnectionString"));
}
```

**Comment by luisrudge** [comment]
Awesome @0xdeafcafe  Thanks!

**Comment by Padmanaabhah** [comment]
Try the following steps:

1) Remove all Microsoft.EntityFrameworkCore.Tools references from dependencies and tools sections inside a project.json

2) Close Package Manager Console (PMC) and restart Visual Studio

3) Add under dependencies section:

 "Microsoft.EntityFrameworkCore.Tools": {
  "version": "1.0.0-preview2-final",
  "type": "build"
 }
4) Add under tools section

"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
5) Restart again Visual Studio 2015

6) Open the PMC and type

Add-Migration $Your_First_Migration_Name$
That's because the PMC recognize the tools when Visual Studio is starting.
