### ISSUE TITLE
EF Core breaks with anything other than 2.0.0 when used with Azure Functions

### ISSUE THREAD

**Issue by johnwc** [dotnet/efcore#11964]
I'm creating this issue here to make sure that the EF Core team knows about this set back when using Azure Functions. Not sure if the issue resides with EF Core team or Azure Functions team.
https://github.com/Azure/azure-functions-core-tools/issues/335

**Comment by ajcvickers** [comment]
@johnwc Pinged people on that thread. Thanks for pointing this out.
