### ISSUE TITLE
Allow provider-specific arguments to be passed to the scaffolding process

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11982]
Here's a non-critical possible feature for your backlog.

When scaffolding an existing database, it may be good to be able to pass provider-specific arguments that would allow the user to customize the scaffolding process. The specific case I have in PostgreSQL is that when the spatial extension is installed (PostGIS), some system tables and views are installed, and these are uninteresting and shouldn't be scaffolded in 99% of cases. I'm making this the behavior of Npgsql, but it may be a good idea to allow users to request scaffolding of all tables. These tables/views aren't in any special schema so they can't be filtered out that way.

These arguments would simply be passed to the provider's DatabaseModelFactory. I'm guessing that this may be relevant for other providers, I wonder if you guys have had cases where this would have been useful.

**Comment by bricelam** [comment]
It's come up a few times, but we tend to look for alternative solutions.
For example, we'll probably only scaffold Geography/Geometry columns when the spatial types are installed into the project (i.e. we can `Assembly.Load()` them). So the gesture whether to reverse engineer them or not becomes install the package, or don't.

For your case, maybe excluding them by default is best, but if they explicitly pass them using `--tables`, you could include them.

**Comment by ajcvickers** [comment]
Note from triage: use cases for this seem limited, some of which can be handled by T4 template edits.
