### ISSUE TITLE
Very long Foreign Key names are not handled as expected when using the new HasData() method.

### ISSUE THREAD

**Issue by sjetha-pason** [dotnet/efcore#11995]
Describe what is not working as expected.

When using the new HasData() method, the migration that is produced names keys longer than 128 characters when it is required to drop and re-create a foreign key when inserting data.

This has two effects:
Firstly, the name that is used in the migration script doesn't match what is currently in the database.
Secondly, the lines that re-create the key end with a tilde (`~`) character instead of the correct name as it existed previously.

Example:
ClassName: ForecastEquipmentConfigurationRigForecastMethodConfiguration
PropertyName: ForecastEquipmentConfigurationId
Foreign Key name in database: FK_Forecast_Equipment_Configuration_Rig_Forecast_Method_Configurations_forecast_equipment_configuration_id

Code in new Migration script:
`
            migrationBuilder.DropForeignKey(
                name: "FK_Forecast_Equipment_Configuration_Rig_Forecast_Method_Configurations_Forecast_Equipment_Configurations_forecast_equipment_configuration_id",
                table: "Forecast_Equipment_Configuration_Rig_Forecast_Method_Configurations");
…
            migrationBuilder.AddForeignKey(
                name: "FK_Forecast_Equipment_Configuration_Rig_Forecast_Method_Configurations_Forecast_Equipment_Configurations_forecast_equipment_con~",
                table: "Forecast_Equipment_Configuration_Rig_Forecast_Method_Configurations",
                column: "forecast_equipment_configuration_id",
                principalTable: "Forecast_Equipment_Configurations",
                principalColumn: "forecast_equipment_configuration_id",
                onDelete: ReferentialAction.Cascade);
`

Also, there is an issue with the fact that this column is re-created with a Cascade OnDelete action. This was set to NoAction in the original migration where the column was created.

### Steps to reproduce
1. In a new Solution, create a property on a class that will produce an auto-generated foreign key name that will be longer than the permitted 128 characters.
2. Perform a migration to get the new column created.
3. Use the new HasData method on the modelBuilder to insert some data using the new column.
4. Add this as a new Migration using dotnet ef migrations add seeddata command.
5. Perform dotnet run and see the insertion operation complain about the foreign key being longer than 128 characters. Note that the foreign key in the migration is not the same as the one added by the previous migration.

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 April 2018 Update (1803)
IDE: Visual Studio 2017 15.7.1

**Comment by ajcvickers** [comment]
@bricelam I found #11473 but it was fixed in the RC1 release.

**Comment by bricelam** [comment]
This is one of those bugs that is only fixed after a new snapshot is generated, so you'll get one more bad migration (just manually remove the drops and creates), but the problem should go away after that.

**Comment by sjetha-pason** [comment]
Hi @bricelam. I was able to resolve this by removing the drop and create statements from the Up and Down methods of the new migration leaving all of the other changes in the migration intact, just as you described.
So far the migration seeded the database as expected, but I will keep an eye on any further migrations that happen, to see if this issue pops up again.

Thanks for your help.
