### ISSUE TITLE
Find types of entities that implement an interface in OnModelCreating

### ISSUE THREAD

**Issue by john1452** [dotnet/efcore#11991]
I would like to retrieve the `Type` of entities that implement a specific interface. I want to retrive this inside the OnModelCreating method.

Example
Assume that I have the following entity
```C#
    public class Product : IProductBase {
       public int ProductId {get;set;}
    }
```
I also have a entity that does not implement `IProductBase` for example:
```C#
    Public class ProductInventory {
      public int Id {get;set;}
    }
```

In the following onModelCreating I want to be able to retrieve all the `Type(s)` of entities that have implemented `IProductBase` interface.
```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    
         
    }
```
I have tried few things such as trying to retrieve the ClrType. But that does not seem to work.

**Comment by ajcvickers** [comment]
@john1452 Assuming that you want to find entity types that are already in the model (e.g because they have an associated DbSet property on the context), then you can iterate of all types in the model and look at the ClrType:
```C#
foreach (var entityType in modelBuilder.Model.GetEntityTypes()
    .Where(e => typeof(IHazSomething).IsAssignableFrom(e.ClrType)))
{
    Console.WriteLine($"Found {entityType.Name}");
}
```
