### ISSUE TITLE
RevEng: A table named TMyTable should result in an entity called TMyTable and not TmyTable

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12007]
Saw it in a blog post comment on our [2.1 RC1 announcement](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-entity-framework-core-2-1-rc-1/) and I was able to repro it. 

I may be missing something (or forgotten how we designed it to work) but I believe T, My, Table should be considered separate words.

**Comment by smitpatel** [comment]
Current logic in `CandidateNamingService` does not allow single character word.
