### ISSUE TITLE
mapping multiple entities to same table 

### ISSUE THREAD

**Issue by kishoretvk** [dotnet/efcore#12006]
Describe what is not working as expected.
when i try to map multiple entities to same table, it gives mapping error!
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
public class Person
{
public int PersonId { get; set; }
public string FirstName { get; set; }
public string MiddleName { get; set; }
public string LastName { get; set; }
public Address CurrentAddress { get; set; }
public Address PermanentAddress { get; set; }

}

public class PersonId
{
public int PersonId { get; set; }
public string FirstName { get; set; }
public string MiddleName { get; set; }

}

Instead of using separate data context can we still use same db contexzt and map them to the same table?
thus i can load only properties i want and hence have less burden on middle layer to carry around data. 
data here could be 200 million, so i want to load only very few columns

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment]
All you need is to create one to one relationship between them and map all the common properties to same columns.
Put following code in your OnModelCreating method and it will only need one table for both.
```C#
            modelBuilder.Entity<Person>(
                b =>
                {
                    b.ToTable("Person");
                    b.Property(e => e.PersonId).HasColumnName("PersonId");
                    b.Property(e => e.FirstName).HasColumnName("FirstName");
                    b.Property(e => e.MiddleName).HasColumnName("MiddleName");
                });

            modelBuilder.Entity<PersonSmall>(
                b =>
                {
                    b.ToTable("Person");
                    b.HasKey(e => e.PersonId);
                    b.Property(e => e.PersonId).HasColumnName("PersonId");
                    b.Property(e => e.FirstName).HasColumnName("FirstName");
                    b.Property(e => e.MiddleName).HasColumnName("MiddleName");
                    b.HasOne<Person>().WithOne().HasForeignKey<PersonSmall>(e => e.PersonId);

                });
```
P.S. I changed `PersonId` class name to `PersonSmall` since `PersonId` class cannot have `PersonId` property inside. Compilation failure.
