### ISSUE TITLE
DbContext.Entry lookup very slow

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/efcore#12017]
When switching from EF Core 2.0 to 2.1 RC1, a routine went from millisconds to minutes.
I tracked it down to this call:

var entry = _ctx.Entry(entity);

The context above had 1600 entities of type location with change tracking on. This lookup takes a few 100 ms each time, and happens thousands of times in my code. 

Removing the call returned my code to ms instead of minutes. Something to look into?

**Comment by ajcvickers** [comment]
Closing this as a duplicate of #9422, with a reference there to this issue.

**Comment by lakeman** [comment]
Do we really need to call TryDetectChanges() to examine *all* tracked entities? Can we limit the work here to the entry being examined in some cases?

**Comment by ajcvickers** [comment]
@lakeman See #13552
