### ISSUE TITLE
Setting a required Parent of a Child to null deletes the Child instead of throwing exception

### ISSUE THREAD

**Issue by GertArnold** [dotnet/efcore#12025]
Setting a required Parent = null of a  Child object deletes the Child object on SaveChanges
Using EF core 2.1.0-rc1-final on Sql Server 2016 localdb

Linqpad 5.26.01 program:

```C#
    public async Task Main()
    {
        var connectionString = @"Server=(localDB)\MSSQLLocalDB;Integrated Security=true;database=planetsDelMoonIssue";
        using (var db = new MyContext(connectionString))
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();
    
            var earth = new Planet{ Name = "Earth" };
            earth.Moons.Add(new Moon { Name = "Moon" });
            var mars = new Planet { Name = "Mars" };
            mars.Moons.Add(new Moon { Name = "Phobos" });
            mars.Moons.Add(new Moon { Name = "Deimos" });
    
            db.Set<Planet>().Add(earth);
            db.Set<Planet>().Add(mars);
    
            db.SaveChanges();
        }
    
        using (var db = new MyContext(connectionString))
        {
            using (var tran = db.Database.BeginTransaction())
            {
                var moon = db.Moons.Include(m => m.Planet).FirstOrDefault(m => m.ID == 3);
                moon.Planet = null;
                Console.WriteLine(db.Entry(moon).State);
                db.SaveChanges();
                tran.Commit();
            }
        }
    
        using (var db = new MyContext(connectionString))
        {
            db.Moons.Include(p => p.Planet).ToList().Dump();
        }
    }
    
    // Define other methods and classes here
    public class Planet
    {
        public Planet()
        {
            Moons = new HashSet<Moon>();
        }
        public int ID { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Moon> Moons { get; set; }
    }
    
    public class Moon
    {
        public int ID { get; set; }
        public int PlanetID { get; set; }
        public string Name { get; set; }
        public virtual Planet Planet { get; set; }
    }
    
    
    public class MyContext : DbContext
    {
        private string _connString;
    
        public DbSet<Planet> Planets { get; set; }
        public DbSet<Moon> Moons { get; set; }
    
        public MyContext(string connectionString) : base()
        {
            _connString = connectionString;
        }
    
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                //.UseLazyLoadingProxies()
                .UseSqlServer(_connString);
        }
    }
```
The line revealing the bug is 

    moon.Planet = null;

As expected (I guess), `moon`'s state is `Modified` at that point. However, `SaveChanges` doesn't throw an expected exception that `moon.PlanetID` can't be null, but it deletes `moon`!

If you might be wondering why on earth :) I'm doing this, it was to investigate EF-core's behavior in the light of my post [here](https://stackoverflow.com/a/32803161/861716).

**Comment by ajcvickers** [comment]
@GertArnold Since it is a required relationship (non-nullable FK) it is configured to cascade delete orphans by convention. See https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete

**Comment by GertArnold** [comment]
Thanks @ajcvickers I understand what you say about cascaded deletes, but nothing is intended to be deleted here, neither the parent, not the child. This mocks a scenario in which a required parent is set to null inadvertently. That would be a bug in application code and IMO it should throw an exception somewhere, probably when the change tracker detects changes. It shouldn't lead to data loss.

**Comment by ajcvickers** [comment]
@GertArnold Because it leaves an orphan, or because it is the navigation to the parent that is changed?

Note that the same argument can be made for any cascading behavior--for example, deleting a parent when it still has children. We discussed this at length, but ultimately decided to have cascading delete on by default because it seems the most useful.

**Comment by GertArnold** [comment]
@ajcvickers In an optional association, setting Parent = null leaves an orphan. That's intended behavior. _No deletes are involved_, it's just a SQL update. In a required relationship a parent shouldn't be nullified, normally, but noting keeps a developer from doing that in C# code. Of course it's buggy code if this happens, but _still no delete should be involved_.

I can't think of any application developer that will use this "feature" of setting a required parent to null in order to delete the child. I strongly plead for throwing an exception in this case, as EF "classic" does.

**Comment by ajcvickers** [comment]
@GertArnold It's a delete orphans behavior, which was requested frequently on EF6.
