### ISSUE TITLE
'Executed DbCommand' AppInsights Timing Discrepancy 

### ISSUE THREAD

**Issue by nex2null** [dotnet/efcore#12026]
I was trying to figure out why a query was intermittently running slow and turned on more verbose app insights logging messages.

The entire request call to our API took 3 minutes and it looks like the entirety of the time was spent executing a SELECT command, however the EF logs say that the command took less than a second.

Here's a screenshot of the app insights logs
![image](https://user-images.githubusercontent.com/828665/40119542-f5de1958-58ea-11e8-8a45-29a44abf4d81.png)

Any idea on why the logs are 3 minutes apart between executing, and executed...but EF says the duration was less than 1 second?

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Azure App Service - Windows

**Comment by ajcvickers** [comment]
Moved to https://github.com/Microsoft/ApplicationInsights-Home/issues/224
