### ISSUE TITLE
Query Types: Fluent API issue

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#12030]
QueryTypeBuilder.HasOne returns ReferenceNavigationBuilder that exposes some APIs which are not valid for QTs. E.g. Any wither method that allows a nav to be specified.

**Comment by ajcvickers** [comment]
@AndriySvyryd to investigate which members are exposed and what these may currently do.

**Comment by AndriySvyryd** [comment]
Also there's no `HasOne<TRelatedEntity>(string)` overload
