### ISSUE TITLE
Flaky test: Method_with_constant_queryable_arg

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/efcore#12037]
This test [fails](http://aspnetci/viewLog.html?buildId=469418&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
Assert.Equal() Failure
Expected: 1
Actual:   2
   at Microsoft.EntityFrameworkCore.Query.SimpleQueryTestBase`1.Method_with_constant_queryable_arg()
```

**Comment by ajcvickers** [comment]
@maumar to check test is disabled (or fixed!)

**Comment by maumar** [comment]
disabled in a9859a73f375765cf274d66259d05b20fa4e3e3c

**Comment by ajcvickers** [comment]
This is no longer relevant due to the query pipeline changes.
