### ISSUE TITLE
is there any way to use constant in data annotations

### ISSUE THREAD

**Issue by 5468sun** [dotnet/efcore#12042]
```
public const int MaxTitleLength = 50;

[Column(TypeName = "VARCHAR(50)")]
public string Title { get; set; } // 标题
```
can i use constant in data annotations? 

```
[Column(TypeName = "VARCHAR(MaxTitleLength)")]
public string Title { get; set; } // 标题
```
doesnt work。

### Further technical details
EF Core version: 2.0.2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Mac
IDE: (e.g. Visual Studio 2017)

**Comment by SSkovboiSS** [comment]
How about interpolated string:
`$"VARCHAR({MaxTitleLength})"`

**Comment by SSkovboiSS** [comment]
@ralmsdeveloper 
You are right, I completely forgot about this :confused:

**Comment by 5468sun** [comment]
thx. not exactly what i need.

**Comment by ralmsdeveloper** [comment]
@5468sun So a second option or the best option would be `Fluent API`

```csharp
public const int MaxTitleLength = 50;

protected override void OnModelCreating(ModelBuilder modelo)
{
    modelo.Entity<People>()
        .Property(x => x.Name).HasColumnType($"VARCHAR{MaxTitleLength}"); 
}
```

**Comment by 5468sun** [comment]
thx.
