### ISSUE TITLE
Tests where EF Core is failing to track some entities

### ISSUE THREAD

**Issue by tuespetre** [dotnet/efcore#12063]
Here is the final (as in `rc1-final`) list of tests that I found to be incorrect in their `entryCount`:

    - AsyncSimpleQueryTest
        - Join_customers_orders_with_subquery_anonymous_property_method
    - SimpleQueryTest
        - Join_customers_orders_with_subquery_anonymous_property_method
        - Queryable_simple_anonymous_subquery
    - AsyncGroupByQueryTest
        - Join_GroupBy_Aggregate_in_subquery
    - GroupByQueryTest
        - Join_GroupBy_Aggregate_in_subquery
    - QueryNavigationsTest
        - Select_collection_FirstOrDefault_project_entity
        - Take_Select_Navigation
        - Skip_Select_Navigation

**Comment by ajcvickers** [comment]
@smitpatel to investigate and file individual issues with specifics as appropriate.
