### ISSUE TITLE
[Question] - Caching and attaching

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#12066]
I have two `DbContext` instances.
The first instance is a singleton.
This instance creates an entity:

```
_database.Foo.Add(new Foo()
                    {
                        Name="Test",
                        Bar= 4                    
                    });
 _database.SaveChanges();
```

The second instance is scoped to a particular operation happening elsewhere.
The scoped instance updates the same record `Foo` and sets it's `Bar` property from `4` to `5` and commits.
If the scoped instance re-queries `Foo` it sees the change - as expected.

Sometime after that operation commits, back on the singleton instance, it needs to update the same `Foo` record a second time. So it does:

```
 var foo = _database.Foo.FirstOrDefault(a => a.Name== "Test");
 foo.Name = "Live";
_database.SaveChanges();
```

However it sees the old value of the entity that it originally created, not the most up to date record from the database that was just committed by the other dbcontext instance. So it ends up saving changes to the `Foo` record and reverting the value of 5 back to 4 again.

What is the correct way to handle this situation?
I would like for my query to with the singleton instance to pull back the latest values from the database - but not for read only purposes - I plan to make modifications.

I saw `AsNoTracking()` but the the use case for that looks primarliy read only purposes. Do I have to use this and then attach the entity somehow? Should I be using `TrackGraph()` ? It seems there should just be a shorthand for my scenario. Is there a way to clear the cached / tracked state for a given entity so that I can be sure that the next query hits the database without using `AsNoTracking`?

### Further technical details
EF Core version: 2.0.2
Database Provider: sqlite
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@dazinator The recommended approach is not use a long-lived context instance. Instead, create a new instance for each unit-of-work. That being said, you can use `context.Entry(foo).Reload()` to refresh values of an entity from the database, or use `context.Entry(foo).GetDatabaseValues()` and related APIs to do similar things. However, these are designed more for things like optimistic concurrency within a single unit-of-work; I would strongly recommend a short-lived context over this approach.

**Comment by dazinator** [comment]
Ok thank you. I will look at refactoring the code. There are a few singleton services in this xamarin app that have a DbContext instance injected, so will have to inject those with a Factory method instead so they can create short lived instances on demand.
However good to know the other ways to achieve this functionality.

**Comment by dazinator** [comment]
@ajcvickers - I can't see a `context.Entry()` method at all in `2.0.2`.. ?

**Comment by dazinator** [comment]
> I can't see a context.Entry() method at all in 2.0.2.. ?
Ignore me. Blind as a bat.
