### ISSUE TITLE
SqlServerTypeMappingSource readonly data member

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#12077]
EF Core version: dev

Why the data members of SqlServerTypeMappingSource (like _sqlVariant, _real ...) not defined as static?

**Comment by ajcvickers** [comment]
@dmitry-lipetsk Because it allows the type mappings to be garbage collected when the service provider root is collected. Things cached as statics persist for a long time, and that has traditionally caused problems for systems that need to dynamically use lots of different models.
