### ISSUE TITLE
Derived classes of RelationalTypeMapping

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#12076]
EF Core version: dev

From my point of view, all derived classes of RelationalTypeMapping, which have implementation "protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)" method, must be **sealed**

It will prevent incorrect inheritance without overriding of "Clone(parameters)" method.

The classes like IntTypeMapping should inherite IntTypeMapping_Base class, which does not define "Clone(parameters)" method or defines "Clone(paramerers)" method as abstract.

Thanks.

**Comment by ajcvickers** [comment]
@dmitry-lipetsk Thanks for your suggestion. This is one way to ensure Clone is overridden, but it would a) be a breaking change and b) result in an additional explosion of base classes, so we're not planning to implement this pattern.
