### ISSUE TITLE
Query: Refactor GroupBy aggregate to avoid dependency on Requires Materialization

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#12089]

**Comment by divega** [comment]
@smitpatel is there a more general issue for "delayed requires materialization" that we talked about in planning or is this the one?

**Comment by smitpatel** [comment]
@divega - We don't have tracking issue for that separately. Could be part of #7520

**Comment by divega** [comment]
@smitpatel ok, let's chat when we have a chance about how to best track it. If you add it to the list in #7520 that would be a good start.

**Comment by smitpatel** [comment]
@divega - #11215 I added note to that list.

**Comment by ajcvickers** [comment]
Make sure to test case in #12089

**Comment by ajcvickers** [comment]
Moved this into 2.2 since we believe it will help stabilize query. If, when working on it. it looks like it is going to have the opposite effect. then we should reconsider.

**Comment by smitpatel** [comment]
We do not have requires materialization visitor anymore. So this is no longer needed. We can do needful when we re-implement group by aggregate.

**Comment by a-a-k** [comment]
@smitpatel what does it exactly mean? Could you explain in simple terms?

**Comment by smitpatel** [comment]
In old pipeline, we had to determine in advance if we need to materialize entity or we can server eval. For GroupBy when you are applying aggregate, entity materialization is not required. But with mixed mode evaluation, it was not possible to determine in all cases, if we can translate to SQL group by since some client function or not mapped property can cause client eval. Hence we were having issues when advance determination was incorrect. This issue was tracking it. Now in new pipeline we don't do advance determination of materialization so this issue is no longer relevant.
