### ISSUE TITLE
Log a warning when Ignore is called on an explicitly configured property or type

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#12082]
When ignoring a property that is explicitly used in a key throw an error
### Steps to reproduce

```c#
modelBuilder.Entity<Counter>().HasAlternateKey(c => new { c.StyleKey, c.IsTest, c.Discriminator });
            modelBuilder.Entity<Counter>().Ignore(c => c.Discriminator);
```

### Further technical details
EF Core version: 2.1.0 rc1 final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system:  Win10
IDE:  Visual Studio 2017 15.7.1

**Comment by ajcvickers** [comment]
@Tarig0 Why are you both referencing and ignoring the property explicitly?

**Comment by Tarig0** [comment]
Because I wasn't ignoring the property when I was using the value converter feature, then switched to a private store variable, and didn't update the key.

**Comment by AndriySvyryd** [comment]
Unfortunately if `Ignore` threw an exception in this case then it would be impossible to remove that property from the model as there's no API for removing keys. But we could log a warning.

**Comment by Tarig0** [comment]
I think the issue I'm seeing is that the Model is invalid so the program shouldn't be able to continue with the configuration. Not that I want the model to remove the alternate key, but to say hey this alternate key is not valid bad program.
```c#
modelBuilder.Entity<Counter>().HasAlternateKey(c => new { c.StyleKey, c.IsTest, c.Discriminator }); //This should be c.StrDiscriminator
            modelBuilder.Entity<Counter>().Ignore(c => c.Discriminator);
```

**Comment by AndriySvyryd** [comment]
@Tarig0 I understand that in your case the model configuration is contradicting and doesn't produce the expected model. But `Ignore` is also used to remove previous configuration. For example that 'HasAlternateKey' call could be in the base context type that you are deriving from and you can't change that code, so calling `Ignore` would be the only way to remove that key.
