### ISSUE TITLE
How to debug duplicate key issue during SaveChanges

### ISSUE THREAD

**Issue by herme063** [dotnet/efcore#12090]
On the call to SaveChanges() an ArgumentException is thrown when a call to Dictionary.Add fails. Unfortunately the key is not readable `ArgumentException: An item with the same key has already been added. Key: System.Object[]` and there is no indication about the tracked entity type which has the issue.

How do we debug from here?

Thank you,

**Comment by smitpatel** [comment]
Seems like Duplicate of #11505

**Comment by ajcvickers** [comment]
@herme063 Can you confirm if #11505 covers the issue you are seeing?

**Comment by herme063** [comment]
In my scenario I am not using filter index. After deleting some of the many to many data I was able to get past this error. I am still not sure how. So I really do not have much of case here,
