### ISSUE TITLE
Error CS1061 'DbContextOptionsBuilder<EmployeeContext>' does not contain a definition for 'UseInMemoryDatabase' and no extension method 'UseInMemoryDatabase' accepting a first argument of type 'DbContextOptionsBuilder<EmployeeContext>' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by maqsoodahmad** [dotnet/efcore#12096]
UseInMemoryDatabase is not being recognised by compiler in .Net Core 2.0 Unit test application. I'm using Microsoft.EntityFrameworkCore.InMemory 2.3 package and passing database name in the method but it's not valid.

```
Exception message:
Stack trace:
Error	CS1061	'DbContextOptionsBuilder<EmployeeContext>' does not contain a definition for 'UseInMemoryDatabase' and no extension method 'UseInMemoryDatabase' accepting a first argument of type 'DbContextOptionsBuilder<EmployeeContext>' could be found (are you missing a using directive or an assembly reference?)	EmployeesHierachry.Test
```

### Steps to reproduce
Use code as below
 var builder = new DbContextOptionsBuilder<EmployeeContext>()              
                .UseInMemoryDatabase("EmpTestDB");
and compile will generate error

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Microsoft.EntityFrameworkCore.InMemory Version="2.0.3"
Microsoft.AspNetCore.All Version="2.0.8"
Microsoft.EntityFrameworkCore.Relational Version="2.0.3"
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.7.2

**Comment by smitpatel** [comment]
Need repro project for this given it works for others (and also in the unit test projects in this repo)

**Comment by maqsoodahmad** [comment]
Hi Smit

You can see my test project repo at
https://bitbucket.org/dr_maqsood/employeeshierarchy/src/master/EmployeesHierachry.Test/

**Comment by maqsoodahmad** [comment]
Thanks Smit for quickly recognising the issue and helping. I have fixed these issues 👍
