### ISSUE TITLE
DLL not found 'e_sqlite3.dll'

### ISSUE THREAD

**Issue by jwdavidson** [dotnet/efcore#12105]
ASP.Net Core 2.0 application using SQLite database does not publish using win-x64 correctly (works with no issue in Development on IIS Express)

System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Steps attempted to fix:
1.  Renamed SQLitePCLRaw.provider.e_sqlite3.dll => e_sqlite3.dll which corrected the dll not found error, but resulted in another error about missing libversion information.
2.  Copied sqlite3.dll from SQLite web site (win-x64) and renamed to => e_sqlite3.dll which fixed the errors. Application runs as expected

### Further technical details
Microsoft.AspNetCore.All (2.0.8)
Microsoft.EntityFrameworkCore (2.0.3)
Microsoft.EntityFrameworkCore.Sqlite (2.0.3)
Microsoft.Data.Sqlite (2.0.1)
Microsoft.Data.Sqlite.Core (2.0.1)
SQLitePCLRaw.bundle.green (1.1.7)
IDE: VS 2017 (15.7.2)
Win 10 publish to Win Server 2012 R2

**Comment by jwdavidson** [comment]
Thank you for indicating the correct repository. Should I close here?

**Comment by smitpatel** [comment]
@jwdavidson - Can you verify manually upgrading version of `SQLitePCLRaw.bundle.green` to 1.1.10 fixes the issue?

We may want to discuss in team if SQLite repo should react to this or not.

**Comment by vahapdemir** [comment]
I am using package SQLitePCLRAW.bundle_green 1.1.12 in a .NET standard 2.0 project. I had the same problem: "DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)". This .net standard project is used by .NET 4.7.2 project as well. I came across "https://windows-hexerror.linestarve.com/q/so51412189-Unable-to-load-DLL-e_sqlite3-after-Setup" saying "You need to set project build to either x86 or x64 for SQLite3. The x86 route will more compatibility , so use that option unless your doing some specific 64-bit stuff". I have changed my .NET 4.7.2 project to x86 and problem solved. I now have e_sqlite3.dll file in output folder. No more error.

**Comment by win7user10** [comment]
I had the same bug in a project. It has been successfully run once and then I got DllNotFoundException. In my case, my project2 has a reference to a project1 that has a link to Microsoft.EntityFrameworkCore.Sqlite 2.1.14. When I added the same library link to project2 it started work.

**Comment by BrenonOrtega** [comment]
Is there any definitive fix for this one?

After migrating my project from .NET5 to .NET8 and EF core 8 it started happening in jenkins pipeline only, it works normally in local running through visual studio 2022

I've tried 
- adding the  transitive dependencies to include sqlite 3 in the csproj
-  update sqlite3 directly in the amazon linux 2 EC2 machine but no avail.
- update glibc to 2.28 in the machine as well

```
 Error Message:
10:42:33     System.TypeInitializationException : The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
10:42:33    ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
10:42:33    ----> System.DllNotFoundException : Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/runtimes/linux-x64/native/e_sqlite3.so: cannot open shared object file: No such file or directory
10:42:33  /home/ec2-user/dotnet8/shared/Microsoft.NETCore.App/8.0.5/e_sqlite3.so: cannot open shared object file: No such file or directory
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/e_sqlite3.so: cannot open shared object file: No such file or directory
10:42:33  /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/runtimes/linux-x64/native/libe_sqlite3.so)
10:42:33  /home/ec2-user/dotnet8/shared/Microsoft.NETCore.App/8.0.5/libe_sqlite3.so: cannot open shared object file: No such file or directory
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/libe_sqlite3.so: cannot open shared object file: No such file or directory
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/runtimes/linux-x64/native/e_sqlite3: cannot open shared object file: No such file or directory
10:42:33  /home/ec2-user/dotnet8/shared/Microsoft.NETCore.App/8.0.5/e_sqlite3: cannot open shared object file: No such file or directory
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/e_sqlite3: cannot open shared object file: No such file or directory
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/runtimes/linux-x64/native/libe_sqlite3: cannot open shared object file: No such file or directory
10:42:33  /home/ec2-user/dotnet8/shared/Microsoft.NETCore.App/8.0.5/libe_sqlite3: cannot open shared object file: No such file or directory
10:42:33  /jenkins/workspace/MyProject_CI/src/Tests/MyProject.Domain.UnitTests/bin/Release/net8.0/libe_sqlite3: cannot open shared object file: No such file or directory
```

csproj file
`
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
 <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.17.0" />
    <PackageReference Include="Castle.Windsor" Version="5.1.1" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageReference Include="NServiceBus.Testing" Version="7.4.2" />
    <PackageReference Include="NSubstitute" Version="4.2.2" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit.Console" Version="3.15.0" />
    <PackageReference Include="NUnit.Runners" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NunitXml.TestLogger" Version="3.0.117" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.9" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.1.9" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.9" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.9" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="TimeZoneConverter" Version="3.2.0" />
  </ItemGroup>
</Project>

`

**Comment by BrenonOrtega** [comment]
One update in my previous comment.
Reverting all EntitryFrameworkCore related packages to version 7 and removing SQLitePCLRaw packages fixed the issue.
