### ISSUE TITLE
DbQuery<T> with .Include related entities

### ISSUE THREAD

**Issue by wernerb90** [dotnet/efcore#12116]
I want to use the new DbQuery / Query Types to query a SQL Server indexed view that does some joins, to simply the structure needed in EF Core - but upon querying, I need to include some relational entities.  How do you do that?

```
Exception message: InvalidOperationException: Unable to create a foreign key with the query type 'StoryQuery' as the principal type. Only entity types are allowed as foreign key principal types.
```

### Steps to reproduce

```c#
    public Story
    {
        public long Id { get; set; }
        public DateTime StoryDate { get; set; }
        public ICollection<StoryTag> StoryTags { get; set; }
    }

    public class StoryTag
    {
        public long Id { get; set; }
        public long StoryId { get; set; }
        public long TagId { get; set; }
        public string TagText { get; set; }
    }

            var result = await context.Stories()
                .Where(predicate)
                .Include(s => s.StoryTag)
                .OrderByDescending(s => s.StoryDate)
                .Skip(0)
                .Take(10)
                .ToListAsync(cancellationToken);
```

If I add [InverseProperty] or [ForeignKey] to any of the navigation properties in the above, then I get the above-mentioned error.  How do we include the related entities when querying DbQuery instead of DbSet ?

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: JetBrains Rider 2018.1

**Comment by ajcvickers** [comment]
@wernerbarnard It looks like the types have keys. Is there a reason you want to use query types for this rather than mapping these as entity types?

**Comment by wernerbarnard** [comment]
@ajcvickers 
No specific reason, thought it's the new "standard" way for working with sql views - i'm using views to create a optimized / simpler interface to query a complex structure.

It's all working now by mapping the views to Entity types - but was wondering what the correct use case is, or why you can't .Include entities from Query Types - or perhaps i'm understanding the use case wrong?  Even if it's read-only, I would have thought that you could do that.

**Comment by ajcvickers** [comment]
@wernerbarnard Docs for query types are here: https://docs.microsoft.com/en-us/ef/core/modeling/query-types They are about querying for types that don't have primary key. So more tables fall into the entity type bucket, and more views fall into the query type bucket, but both tables without keys and views with keys are also possible, just less common.

**Comment by norcino** [comment]
@ajcvickers I am having this problem as well and I don't use EntityType because I need to use a read only DBContext with OData, which is mapped to SQL queries, not even views because I cannot create them.
In my case I map the QueryType to a Query and not a view, I show you how below:

# In DbContext
public virtual DbQuery<A> As { get; set; }
public virtual DbQuery<B> Bs { get; set; }

# In Mapping configuration class
public void Configure(QueryTypeBuilder<B> builder)
{
    builder.ToQuery(() => _context.Bs.FromSql(Sql, _tenantProvider.GetTenant()).AsQueryable());
    builder.HasOne<A>(qml => qml.B);
}

I think I cannot do what I am trying to, but is there an alternative route for me to follow?
How can I map an entity with EF Core to a SQL script?

**Comment by ajcvickers** [comment]
@norcino Regardless of whether a type is mapped to a view, a table, or something else, if it's a query type (keyless entity type in 3.0), then it can't have a key. If it doesn't have a key, then that key cannot be used to setup a relationship with another type. However, if the type does have a key, then map it as an entity type with a key, even if it is backed by a view.

With regard to `ToQuery`, issue 13358 is tracking supporting this for all entity types.
