### ISSUE TITLE
Would like to scaffold few tables but entire schema is getting scaffolded

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/efcore#12125]
@smitpatel 
**Issue** 
Unable to scaffold single table when specified table name with --table option, but scaffolds all tables from the schema. 

**Command**
dotnet ef dbcontext scaffold "Data Source=servername;Initial Catalog=dbname;User ID=user;Password=billing"  Microsoft.EntityFrameworkCore.SqlServer -o Entities -c mycontext --schema dbo  --table tablename

Version
Entity Framework Core .NET Command-line Tools 2.1.0-preview1-28290

**Comment by smitpatel** [comment]
`--schema` & `--table` are connected by OR operator. So above command would scaffold everything from `dbo` schema and scaffold `tablename` from any schema.
To scaffold particular table inside dbo schema use schema qualified table names
e.g. `--table dbo.tablename`

**Comment by ErikEJ** [comment]
@arunprasathv Have you tried EF Core Power Tools?

**Comment by ErikEJ** [comment]
Have you tried closing and re-opening the file? Sounds like a VS issue more than a EF Core issue.

**Comment by arunprasathv** [comment]
In this case context file exists already and I'm trying to add few more additional tables to the context.

**Comment by ErikEJ** [comment]
Yes, I understand what you are doing, have you tried closing and re-opening the DbContext file??

**Comment by arunprasathv** [comment]
@ErikEJ after re-opening solution i see only the tables that i added now and i lost previous entities from context file.

**Comment by ErikEJ** [comment]
Are you using Power Tools or command line?

**Comment by ErikEJ** [comment]
If you use Power Tools, please raise an issue in the Power Tools repo: https://github.com/ErikEJ/EfCorePowerTools

**Comment by ErikEJ** [comment]
Pls raise an issue at Power Tools, with screenshots, thanks...

**Comment by ErikEJ** [comment]
I use the tool daily, and have never experienced this.

**Comment by arunprasathv** [comment]
![ef](https://user-images.githubusercontent.com/7142390/40502954-70ab8a38-5f5a-11e8-9b51-6a7cc34a51ed.png)

this is what i do after selecting a table

**Comment by ErikEJ** [comment]
As @smitpatel  says, select all the tabels you want to generate code for each time, not just the new tables(s)

**Comment by arunprasathv** [comment]
I got it, Thanks.!
