### ISSUE TITLE
Microsoft.EntityFrameworkCore.DbUpdateException   HResult=0x80131500   Message=An error occurred while updating the entries.

### ISSUE THREAD

**Issue by connecttoconnecticut** [dotnet/efcore#12127]
Microsoft.EntityFrameworkCore.DbUpdateException   HResult=0x80131500   Message=An error occurred while updating the entries. See the inner exception for details.  

 The INSERT statement conflicted with the FOREIGN KEY constraint "FK_City_Country_IdofCountry". The conflict occurred in database "MyVinylProject", table "dbo.Country", column 'Id'.
The statement has been terminated.
-whole exception code is under code

UPDATE: Well, i fixed this with ViewModels, how? I put under comment line(remove) field "Country CityCountry" , and left only making "int IdofCountry" where i will remember just Id, and when i need to write it, i will use ViewModel , or something like that.

IF ANYONE HAS BETTER SOLUTION, PLEASE EXPLAIN IT. I dont like this solution but since it works ..

Anyone knows what i did wrong, and what is solution ?! Thanks!
---------------------------------------------------------------------------
```C#

public class Country
    {
     [System.ComponentModel.DataAnnotations.ScaffoldColumn(false)]
[System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual IEnumerable<City> CitiesinCountry { get; set; }
    }

public class City
    {
      [System.ComponentModel.DataAnnotations.ScaffoldColumn(false)]
 [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        //public Country CityCountry { get; set; }                                   <----FIX
        //[System.ComponentModel.DataAnnotations.Schema.ForeignKey("CityCountry")] <----FIX
        public int IdofCountry { get; set; }
     }
public class VShContextClass : DbContext
    {
         public VShContextClass()
         {
         }
         public VShContextClass(DbContextOptions<VShContextClass> options)
            : base(options) { }
        public DbSet<Country> Country { get; set; }
        public DbSet<City> City { get; set; }
}
//controller
        public IActionResult CreateCity()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCity(CityViewModel City)
        {
            if (ModelState.IsValid)
            {
                City newCity = new City()
                {
                    Name = City.Name,
                    IdofCountry = City.CountryId

                };
                _repository.AddCity(newCity);
            }
            ModelState.Clear();

            return View();
        }


//repository
public void AddCity(VinylShop.Models.Record.City newCity)
        {
            db.City.Add(newCity);
            db.SaveChanges();                 //----> THROWS EXCEPTION HERE
        }
```

So i guess you see in code where it throws exception:

> 
Microsoft.EntityFrameworkCore.DbUpdateException   HResult=0x80131500   Message=An error occurred while updating the entries. See the inner exception for details.   Source=Microsoft.EntityFrameworkCore.Relational   StackTrace:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()    at VinylShop.Repository.ShopRepo.AdministratorRepo.AddCity(City newCity) in C:\Users\Bobejn\Desktop\MyProject-Core\VinylShop\VinylShop\Repository\ShopRepo\AdministratorRepo.cs:line 61    at VinylShop.Controllers.Administrator.AdminController.CreateCity(CityViewModel City) in C:\Users\Bobejn\Desktop\MyProject-Core\VinylShop\VinylShop\Controllers\Administrator\AdminController.cs:line 83    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()  Inner Exception 1: SqlException: Invalid column name 'CountryId'.

### Further technical details
EF Core version: 2.0.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer Version="2.0.2"
Operating system:  Windows 10
IDE: Visual Studio 2017 15.4

**Comment by smitpatel** [comment]
Does `Country` with `City.CountryId` exist in database?

**Comment by connecttoconnecticut** [comment]
No, it doesnt.

**Comment by smitpatel** [comment]
> No, it doesnt.

This is pretty much data dependent. The `newCity` you are trying to save has been assigned value to `IdOfCountry` property. If there is no `Country` in database which has `Country.Id` value same as `IdOfCountry` then it is going to fail. As exception message says
>The INSERT statement conflicted with the FOREIGN KEY constraint "FK_City_Country_IdofCountry". The conflict occurred in database "MyVinylProject", table "dbo.Country", column 'Id'.

You violated FK constraint so insert failed. That is the reason it works when you remove the navigation property or FK attribute.
