### ISSUE TITLE
Question: xxxConventionSetBuilder::Build need or not?

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#12131]
EF Core version: dev

Data providers for SqlServer and Sqlite have the public implementations:

SqlServerConventionSetBuilder::Build
SqliteConventionSetBuilder::Build

Inspection of code (Find All References) show that these methods used in tests only.

All as declared: 
```
 /// <summary>
 ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
 ///     directly from your code. This API may change or be removed in future releases.
 /// </summary>
 public static ConventionSet Build()
```

The primary problem of this method (from my point of view) - in call
` o => o.UseXXXXXXX("....")
`
with "dummy" connection string.

I want to remove this Build-method from my data provider.

Could you confirm, that this method really not need?

Thanks.

----
If such questions should be asked on another resources - please give me link to they.

Thanks again.

**Comment by smitpatel** [comment]
It is just a way to get provider specific convention set builder in tests. You can remove it and use some different mechanism in tests.

**Comment by dmitry-lipetsk** [comment]
Ok, thank you.

May be need mark such methods with prefix TestCode__ for avoid questions like my?

**Comment by ajcvickers** [comment]
Triage: no action needed here.
