### ISSUE TITLE
MySQL collation issue

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#12133]
My database is MySQL. I generate migration and update database, then I see the collation of table which is different on different machines. On my machine its **latin1 - default collation** and on a different machine, it is **utf8 - default collation**.

So due to this behavior, I'm getting an exception while inserting Japanese word (日本語) into a table which has a varchar(64) column. It works fine on another machine which has **utf8 - default collation** on this table.

EF Core Version: 2.0.1
MySql: 5.7.22

**Comment by ajcvickers** [comment]
@viveknuna This is an issue with the MySQL database provider. Please file an issue with the author of the provider--links can be found in the [EF docs](https://docs.microsoft.com/en-us/ef/core/providers/).
