### ISSUE TITLE
How can I set onUpdate constraint globally?

### ISSUE THREAD

**Issue by AuthorProxy** [dotnet/efcore#12134]
Currently, I can globally set onDelete constraint via DeleteBehavior
```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()).Where(r => r.DeleteBehavior != DeleteBehavior.Restrict))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }

            FixSnakeCaseNames(modelBuilder);
        }
```

How I can make something similar for `OnUpdate` constraint via attributes, conventions or|and globally like the sample upper

**Comment by ajcvickers** [comment]
@AuthorProxy The code you show is essentially the recommended way to do this. The convention system does not yet have public API (#214) and is designed more for providers than applications. That being said, once the API is public you should be able to use it to process a custom attribute, but it's not clear that it would be better than what you are already doing.

**Comment by AuthorProxy** [comment]
I am sorry, maybe i ask not clear, and should duplicate question at the body, the question is how to set `OnUpdate` constraint at EF Core 2+
