### ISSUE TITLE
How to add comments in ef core code first?

### ISSUE THREAD

**Issue by xBoo** [dotnet/efcore#12132]
I want to add some comments on field and when update database this comments can be add in db via create script, how can I do it?

**Comment by ajcvickers** [comment]
Putting this on the backlog for built-in support. See also #10258, which is about making it easier to flow information from the model into Migrations,.

**Comment by Muppets** [comment]
This looks like a duplicate of #15037?

**Comment by ajcvickers** [comment]
Thanks @Muppets. Closing this as a duplicate.

**Comment by roohial57** [comment]
You can use [EFCommenter](https://www.nuget.org/packages/EFCommenter/#versions-body-tab).

All summaries of entities, properties, and enums will be added as comments on the corresponding database tables and columns.

* Automatically adds **table comments** from entity class summaries.
* Adds **column comments** from property summaries.
* Supports **enum types** as column comments.
* Works with **SQL Server** and **PostgreSQL**.
* Easy to integrate into your EF Core project using a single extension method.

## Installation
```bash
dotnet add package EFCommenter
```

## Usage
Enable XML documentation in your project by adding this to your `.csproj`:

```xml
<PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
```

Then, call the extension method in your `DbContext`:

```csharp
using EFCommenter;
using Microsoft.EntityFrameworkCore;

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.AddEntitiesComments();
}
```

---

## Example

Your entities and enums include some comments.

```csharp
/// <summary>
/// The class declered a person!!!
/// </summary>
public class Person
{
    public int Id { get; set; }

    /// <summary>
    /// The full name of the person!!!
    /// </summary>
    public string Name { get; set; } = "";

    public PersonType Type { get; set; }
}

public enum PersonType
{
    Admin,
    User,
    Guest
}
```

After add migrations, the summaries will appear as table and column comments in created migration, and ready to update the database comments.

```csharp
migrationBuilder.CreateTable(
    name: "People",
    columns: table => new
    {
        Id = table.Column<int>(type: "int", nullable: false)
            .Annotation("SqlServer:Identity", "1, 1"),
        Name = table.Column<string>(type: "nvarchar(max)", nullable: false, comment: "The full name of the person!!!"),
        Type = table.Column<int>(type: "int", nullable: false, comment: "0: Admin | \n1: User | \n2: Guest | ")
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_People", x => x.Id);
    },
    comment: "The class declered a person!!!");
```
---

## Notes

* Make sure your EF Core project targets **.NET 8** or later.
* XML documentation file must be enabled for the summaries to be read.
* Tested with **PostgreSQL** and **SQL Server**.

**Comment by roji** [comment]
@roohial57 note that EF already scaffolds table and column comments, see #15037.

**Comment by ErikEJ** [comment]
@roji I think this is about writing the comments back as metadata in the database?

**Comment by ErikEJ** [comment]
@roohial57 Is you library mentioned in the EF Core Tools list in the docs? If not, maybe create a PR to get it added?

**Comment by roohial57** [comment]
> [@roohial57](https://github.com/roohial57) note that EF already scaffolds table and column comments, see [#15037](https://github.com/dotnet/efcore/issues/15037).

@roji 

In the migration adding, the summaries will be automatically added as table and column comments in the created migration file.
Note, EfCommenter automatically add the comments base on code(Entities, summeries, enums, ...).

**Comment by roohial57** [comment]
> [@roohial57](https://github.com/roohial57) Is you library mentioned in the EF Core Tools list in the docs? If not, maybe create a PR to get it added?

@ErikEJ  Thank you! 
Can you guide me to add it?

**Comment by ErikEJ** [comment]
@roohial57  I have done a PR and it is merged already: https://github.com/dotnet/EntityFramework.Docs/pull/5190
