### ISSUE TITLE
Query: ensure that providers can override when referencing more than one level deep

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12143]
In RelationalQueryModelVisitor we assume that we can safely bind to parent QM - `VisitSubQueryModel` sets `CanBindToParentQueryModel` to true,

However, if this gets changed (e.g. because a provider doesn't support it) we produce incorrect query plan. When translating a sql fragment that now requires client eval (because it binds via outer parameter) we don't pass that information from SqlTranslatingExpressionVisitor to QueryModelVisitor, so requires client eval is still set to false. 

This in turn makes us try to lift the subquery, which results in faulty query plan (dangling qsre and invalid sql)

**Comment by maumar** [comment]
Repro: switch CanBindToParentQueryModel to false in RQMV and run: Project_single_element_from_collection_with_OrderBy_over_navigation_Take_and_FirstOrDefault

query plan:

```
(QueryContext queryContext) => IEnumerable<int> _InterceptExceptions(
|__ source: IEnumerable<int> _Select(
|   |__ source: IEnumerable<ValueBuffer> _InjectParameters(
|   |   |__ queryContext: queryContext, 
|   |   |__ source: IEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |__ queryContext: queryContext, 
|   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |       SELECT COALESCE((
|   |   |   |           SELECT TOP(1) [t].[OrderID]
|   |   |   |           FROM (
|   |   |   |               SELECT TOP(1) [od].[OrderID], [od.Product].[ProductName]
|   |   |   |               FROM [Order Details] AS [od]
|   |   |   |               INNER JOIN [Products] AS [od.Product] ON [od].[ProductID] = [od.Product].[ProductID]
|   |   |   |               WHERE @_outer_OrderID = [od].[OrderID]
|   |   |   |               ORDER BY [od.Product].[ProductName]
|   |   |   |           ) AS [t]
|   |   |   |           ORDER BY [t].[ProductName]
|   |   |   |       ), 0)
|   |   |   |       FROM [Orders] AS [o]
|   |   |   |       WHERE [o].[OrderID] < 10300, 
|   |   |   |__ shaper: ValueBufferShaper), 
|   |   |__ parameterNames: new string[]{ "_outer_OrderID" }, 
|   |   |__ parameterValues: new object[]{ (object)Property([o], "OrderID") }), 
|   |__ selector: (ValueBuffer o) => (int)Nullable<int> TryReadValue(o, 0, null)), 
|__ contextType: TestModels.Northwind.NorthwindRelationalContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
```

**Comment by smitpatel** [comment]
The other side of #11941 
This one we are using outer parameter and still lifting. That one is not lifting still not using outer parameter. Perhaps _InjectParameter should be checked before lifting. Or Lift only Shaped Query.

**Comment by AndriySvyryd** [comment]
@smitpatel Not needed?

**Comment by smitpatel** [comment]
In single query mode you always have lift no matter how many level deep. So we are not going to provide a way for providers to override.
