### ISSUE TITLE
Psssst

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#12146]
Posting this for provider writers at request of @divega.

https://t.co/RHNAfkm3rS

@roji @ErikEJ @dmitry-lipetsk @caleblloyd @yukozh @cincuranet @ralmsdeveloper @bubibubi

**Comment by ErikEJ** [comment]
Shhhhh....

**Comment by roji** [comment]
Good one :) I'll be sure to keep it a secret...

**Comment by ErikEJ** [comment]
@tonysneed  !!

**Comment by tonysneed** [comment]
Nice! 🎉

**Comment by ralmsdeveloper** [comment]
Thanks!

**Comment by bubibubi** [comment]
😍

2018-05-26 21:27 GMT+02:00 Rafael Almeida <notifications@github.com>:

**Comment by ajcvickers** [comment]
Shhh. Don't tell anyone, but https://github.com/aspnet/Home/wiki/.NET-Core-2.1.1-Early-Access-Downloads is a link I heard about that could be interesting.

**Comment by ajcvickers** [comment]
FYI for anyone who downloaded, an issue was found and the build had to be re-spun. You may have to clear package caches.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
