### ISSUE TITLE
EntityFrameworkCore 2.0 to 2.1 Migration response time problem

### ISSUE THREAD

**Issue by canertosuner** [dotnet/efcore#12145]
I upgrade the my .Net Core 2.0 app. to 2.1 with all other Microsoft packages (2.1) and I use entityframework for db operations which is 2.1 rc1.

When I try to get data from my local sql-server database it works fine and the response time is around 75 ms but if I try to retrieve data from the database which is hosted in azure or any other cloud platforms using entity framework the response time is increasing for each request. 

For example; I get use of JMeter to test it and I am trying to request for 50 users for 1 minute. The results look like;

First request :      110 ms
Second request : 150 ms
Third request :     210 ms
.
.
.
Fiftieth request :   970 ms 
etc.

I tried it in different networks and as I described above I am having this problem. Anybody having the same issue ?

**Comment by ajcvickers** [comment]
@canertosuner There is not much information to go on here. Could you post a runnable project/solution or code listing that demonstrates the behavior you are seeing?

**Comment by canertosuner** [comment]
@ajcvickers it is the standart usage of entity framework core with generic repository pattern in a web api application. I can't share the exact code/project but it is very similar to  this [https://codingblast.com/entity-framework-core-generic-repository/](url)

**Comment by canertosuner** [comment]
Hi @ajcvickers You can see the sample project in this repo [address](https://github.com/canertosuner/entityframeworkcoreperfproblem)

**Comment by canertosuner** [comment]
@ajcvickers any news about it ?

**Comment by ajcvickers** [comment]
@canertosuner I have not been able to reproduce what you are seeing with the project posted. What steps do you take to make it call SaveChanges on the context, as is shown in the stack trace?

**Comment by canertosuner** [comment]
@ajcvickers I think it was about the development environment. We run the project on a server and the result of the load test for response time was normal which is around 70-80 ms but in the local machine I got the same result that I have shared above. Closing the issue thank you.
