### ISSUE TITLE
Magic of "ID" name

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#12156]
Hello.

EF Core version: dev

Currently, my data provider does not implement many required things. But can executes simple tests.

I found the next strange behavior.

**Please explain it.**

EntityFrameworkCore works with next structure:
```
  [Table("TEST_MODIFY_ROW_WD")]
  public class TEST_MODIFY_ROW_WD
  {
   [Column("TEST_ID")]
   public Int64 ID { get; set; } // <------------- property has name "ID"

   public Boolean COL_BOOLEAN { get; set; }
  };//class TEST_MODIFY_ROW_WD
```

But does not work with:
```
  [Table("TEST_MODIFY_ROW_WD")]
  public class TEST_MODIFY_ROW_WD
  {
   [Column("TEST_ID")]
   public Int64 TEST_ID { get; set; } // <-------------- property has name "TEST_ID"

   public Boolean COL_BOOLEAN { get; set; }
  };//class TEST_MODIFY_ROW_WD
```

Source of test code:
```
    using(var db=new MyContext(cn))
    {
     int nRecs=0;

     // Works with r.ID
     // Does not work with r.TEST_ID
     foreach(var rec in db.testTable.Where(r=>r.TEST_ID==(Int64)recID))
     {
```

Error text:
**Message: System.InvalidOperationException : The entity type 'TEST_MODIFY_ROW_WD' requires a primary key to be defined.**

Stack trace:
>	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(Microsoft.EntityFrameworkCore.Metadata.IModel model) Line 194	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(Microsoft.EntityFrameworkCore.Metadata.IModel model) Line 48	C#
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(Microsoft.EntityFrameworkCore.Metadata.IModel model) Line 53	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(Microsoft.EntityFrameworkCore.DbContext context, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.EntityFrameworkCore.Infrastructure.IModelValidator validator) Line 88	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel.AnonymousMethod__1() Line 60	C#
 	System.Private.CoreLib.dll!System.Lazy<Microsoft.EntityFrameworkCore.Metadata.IModel>.ViaFactory(System.Threading.LazyThreadSafetyMode mode) Line 327	C#
 	System.Private.CoreLib.dll!System.Lazy<System.__Canon>.ExecutionAndPublication(System.LazyHelper executionAndPublication, bool useDefaultConstructor) Line 351	C#
 	System.Private.CoreLib.dll!System.Lazy<Microsoft.EntityFrameworkCore.Metadata.IModel>.CreateValue() Line 439	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(Microsoft.EntityFrameworkCore.DbContext context, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.EntityFrameworkCore.Infrastructure.IModelValidator validator) Line 56	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel() Line 71	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.Model.get() Line 93	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices.AnonymousMethod__7_2(System.IServiceProvider p) Line 268	C#
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies>(System.IServiceProvider provider)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.DbContextDependencies.get() Line 330	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.InternalServiceProvider.get() Line 312	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.DbContextDependencies.get() Line 330	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.Model.get() Line 138	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.InternalDbSet<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD>.EntityType.get() Line 55	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.InternalDbSet<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD>.CheckState() Line 81	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.InternalDbSet<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD>.EntityQueryable.get() Line 88	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.InternalDbSet<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD>.System.Linq.IQueryable.Provider.get() Line 262	C#
 	System.Linq.Queryable.dll!System.Linq.Queryable.Where<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD>(System.Linq.IQueryable<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD> source, System.Linq.Expressions.Expression<System.Func<ef_core__lcpi_oledb__ntests.Work.DataTypes.Test_006__BOOLEAN.MyContext.TEST_MODIFY_ROW_WD, bool>> predicate) Line 39	C#

**Comment by ErikEJ** [comment]
By convention, EF regards columns named "Id" or "MyclassId" as keys, but not a column named Test_Id.

Use the Key attribute to tell EF that TEST_ID is the key.

    [Key]
    [Column("TEST_ID")]
    public Int64 TEST_ID { get; set; }

**Comment by dmitry-lipetsk** [comment]
THANK YOU VERY MUTH!
