### ISSUE TITLE
Migrations throw error when adding a non-nullable primitive array column

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#12154]
Item.cs
```
public class Item {
    public short[] WarningFlags {get; set;} = new short[]
}
```

ModelBuilder.cs:
` modelBuilder.Entity<Item>().Property(i => i.WarningFlags).HasColumnName("warning_flags").IsRequired();`

`dot net add-migration`
results in
`CSharpHelper cannot scaffold literals of type 'System.Int16[]'.`

Note that without `IsRequired()` it does not throw an error. 
It also does not throw an error when it is the InitialCreate migration.
Database provider is Npgsql.

**Comment by roji** [comment]
Can you please include the version of EF Core that you are using (both Npgsql and core)?

**Comment by roji** [comment]
Just noticed which repo this issue is on, please move this PostgreSQL-specific issue to https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL.

**Comment by orobert91** [comment]
I moved it, thanks
