### ISSUE TITLE
Allow Grouping of parameter attributes into a new attribute

### ISSUE THREAD

**Issue by mikewodarczyk** [dotnet/efcore#12160]
This is a new feature request: 

For a class parameter / Table column that appears in multiple classes / tables, I want to define data annotations like:

    [Column(DataType = "nvarchar")]
    [MaxLength(30)]
    [Required]
    public string CustomerNo {get; set;}

For each table that has string CustomerNo, I want to have exactly the same data type and the same max length, etc, but I don't want to have to keep repeating these lines over and over.  The best I can do now to keep the values from repeating in the code is to make separate const values to represent the datatype and maxlength:  e.g.

    public class SchemaDefinitions {
        public const string CustomerNoDataType = "nvarchar";
        public const int CustomerNoMaxLength = 30;
    }

    [Column(DataType = SchemaDefinitions.CustomerNoDataType)]
    [MaxLength(SchemaDefinitions.CustomerNoMaxLength)]
    [Required]
    public string CustomerNo {get; set;}

This is still a lot of repeated code and not very "DRY".

What I would rather do is create a new attribute that contains, implements, or has its own attributes that hold all of the other attributes together.

e.g.

    // Method 1: implements
    public class CustomerNoAttribute:  IMaxLengthAttribute, IColumnAttribute, IReqiredAttribute {
       public int MaxLength {get; private set;}
       public string DataType {get; private set;}
       public CustomerNoAttribute(string dataType, int maxLength) {
            this.MaxLength = MaxLength;
            this.DataType = datatype;
       }
    }

OR

    // Method 2: Has its own attributes
    [Column(DataType="nvarchar")] 
    [MaxLength(30)]
    [Requred]
    public class CustomerNoAttribute() {}

OR

    // Method 3: contains attributes
    public class CustomerNoAttribute() {
        public const MaxLengthAttribute = new MaxLengthAttribute(30);
        public const ColumnAttribute = new ColumnAttribute(DataType = "nvarchar");
        public const RequiredAttribute = new RequiredAttribute();
    }

I think that a compile time only Methods 1 and 2 will work.
What I expect to happen is that code first migrations should look for attributes containing attributes (for method 2) or Attributes implementing attributes (Method 1) to pick up the collection of attributes applied to a class parameter.  My first code snippet can be reduced down to:

    public class  AnyClass {
        [CustomerNo]
       public string CustomerNo {get; set;}
    }

**Comment by smitpatel** [comment]
@mikewodarczyk - Are you planning to use those attributes only for EF Core? If yes, then you can easily use fluent API to configure multiple facets like that in using abstraction in multiple places with DRY principal. If you want attributes because they are also being used by other frameworks (like MVC) then such approach wouldn't work across everything. Each framework which honors attribute needs to be updated to understand any of above patterns.

**Comment by mikewodarczyk** [comment]
I would like MVC to handle this as well as EF Core.  If Method 2 is used then each framework could implement it with their own recursive calls.  I.e. EF Core could do it independently.  If Method 1 was used, then I guess that each attribute owning framework would have to put in interfaces and only afterwards the attribute consuming frameworks could look for the interfaces.    Is there a higher level cross-framework forum in which this would be better introduced?

**Comment by smitpatel** [comment]
>  If Method 2 is used then each framework could implement it with their own recursive calls.

Still each framework has to react to it.

https://github.com/dotnet/corefx/issues is the place for Data annotations in general, which all framework depend on.

**Comment by mikewodarczyk** [comment]
Thanks,

I will move the issue there until that framework is ready for consumers to use whichever pattern they choose.
