### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by a641545621** [dotnet/efcore#12165]
![1](https://user-images.githubusercontent.com/33652128/40698286-e1ca9786-6400-11e8-842b-4dcaac33ed6a.png)
![2](https://user-images.githubusercontent.com/33652128/40698287-e227b984-6400-11e8-8399-434c42e62978.png)
![3](https://user-images.githubusercontent.com/33652128/40698288-e27af450-6400-11e8-9cdf-1255e8619931.png)
![4](https://user-images.githubusercontent.com/33652128/40698290-e2ce9722-6400-11e8-9752-a6ffb24ae683.png)

How should I set to solve this problem?

Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'RepositoryDbContext'.

**Comment by ajcvickers** [comment]
@a641545621 Please post the full stack trace.

**Comment by antonioortizpola** [comment]
@ajcvickers, this issue was posted already in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/567, the code does not use async correctly, should be closed.
