### ISSUE TITLE
Easy way to get which property is declared as IsConcurrencyToken (feature request)

### ISSUE THREAD

**Issue by kmolerov** [dotnet/efcore#12178]
Need an easy way to get which property is declared as IsConcurrencyToken from entity metadata.

### Steps to reproduce - Example
var entityMetadata = context.Model.FindEntityType(typeof(MyClass));
currently we have methods like:
var navigations = entityMetadata .GetNavigations();
var keys = entityMetadata .GetKeys();
what is needed:
**var concurrencyTokens = entityMetadata .GetConcurrencyTokens();** 

### Further technical details
EF Core version: 2.0
Database Provider: SqlServer & PgSql
Operating system: windows 8.1
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment]
`var concurrencyTokens = entityMetadata.GetProperties().Where(p => p.IsConcurrencyToken);`

**Comment by kmolerov** [comment]
I am closing the issue, as above solution works great. Getting concurrencyToken is not going to be a common operation, so there is no need to have specific method entityMetadata .GetConcurrencyTokens();.

**Comment by kmolerov** [comment]
@ajcvickers thanks for the clarification.
