### ISSUE TITLE
No migration path for EF6 to CORE that does not require massive rework

### ISSUE THREAD

**Issue by davidekarasek** [dotnet/efcore#12184]
There's no migration path for EF6 to EF CORE that does not require massive rework.
This is more than a shortcoming but a showstopper for many folks.
How do you explain to any customer how to budget for a conversion like this?

The other thing is that database first coding should never be treated as an edge case. For many people coding in the real world working with an existing database and table schema it is the case. Within database first performing CRUD operations. through stored procedures has proven for us to be the most separation-of-concerns-oriented way to interact with databases.  That's because the underlying schemas don't need to be messed with for enterprise stores where lots of existing apps rely on these not changing, and for which you don't want anyone having any kind of direct access to the tables, even via an API, for security reasons.

EF6 did a wonderful job mapping stored procedure results into .Net classes through complex types.  Now, in EF Core these are suddenly no longer supported.  Moreover, we get a bunch of lip from Microsoft's CORE developers saying how these won't be supported and now we have to manually create all these classes or manually convert them.  I'm thus crying FOWL. And as I've said for years, get these internal developers onto real projects for real people in the business world.

Thus for now, we're probably abandoning EF entirely for new API projects that use .Net CORE. There's just zero benefit to doing all that wiring anymore since we need to manually adapt stored procedures anyway.  Might as well just use straight ADO.Net.

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@davidekarasek We plan to [port EF6 to run on .NET Core](https://github.com/aspnet/EntityFramework6/issues/271) to cover cases where people want to port their existing application to .NET Core without porting to EF Core. However, that being said, if ADO.NET by itself works well for you, then by all means use it.
