### ISSUE TITLE
Error accessing metadata through context model FileNotFoundException in System.ComponentModel.Annotations, Version=4.2.0.0,

### ISSUE THREAD

**Issue by JuanIrigoyen** [dotnet/efcore#12186]
My project is in Windows Forms, using 4.7.1. When I try to access the model through the context, my program returns the following exception:

System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. The system cannot find the file specified.
Nombre de archivo: 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   en Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.CoreConventionSetBuilder.CreateConventionSet()
   en Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateConventionSet(IConventionSetBuilder conventionSetBuilder)
   en Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   en System.Lazy`1.CreateValue()

### Steps to reproduce
```c#
  using (MaldivasBaseContext mbc = new MaldivasBaseContext(connectionString))
                {
                    mbc.Model .... throw the exception
                   
                }
```

### Further technical details
EF Core version: EF Core 2.1.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2017 15.7.2)

**Comment by ajcvickers** [comment]
@JuanIrigoyen Can you post your csproj so we can see which dependencies you have?

**Comment by JuanIrigoyen** [comment]
Yes, thank you @ajcvickers
[Maldivas.Data.zip](https://github.com/aspnet/EntityFrameworkCore/files/2059692/Maldivas.Data.zip)
