### ISSUE TITLE
DateTime.Now.TimeOfDay  AND TimeSpan.Parse be client evaluated？

### ISSUE THREAD

**Issue by wangpengxpy** [dotnet/efcore#12187]
![image](https://user-images.githubusercontent.com/12961992/40800650-8f5f7ed2-6543-11e8-9a14-a6fa63290b9b.png)

### Steps to reproduce

```c#
    public class TestA
    {
        public int Id { get; set; }
        public string StrartEnd { get; set; }
        public string EndTime { get; set; }
        public TimeSpan TimeSpanStartEnd { get; set; }
        public TimeSpan TimeSpanEndTime { get; set; }
    }

    using (var context = new EFCoreDbContext())
    {
        var time = new TimeSpan(9, 00, 00);

        var test = context.TestAs.Where(d => d.TimeSpanStartEnd >= DateTime.Now.TimeOfDay && DateTime.Now.TimeOfDay <= d.TimeSpanStartEnd).ToList();

         OR

        var test1 = context.TestAs.Where(d => TimeSpan.Parse(d.StrartEnd) >= time && time <= TimeSpan.Parse(d.EndTime)).ToList();
     }
```

### Further technical details
EF Core version: (2.0.1)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.7.2)

**Comment by smitpatel** [comment]
@wangpengxpy - What is incorrect in that? You are asking for whole entity so we are going to fetch all the columns in SELECT. The Where predicate could be client evaluated. Try 2.1 release which has translations for DateTime.Now.TimeOfDay.

**Comment by wangpengxpy** [comment]
wow，It's my fault，tks。DateTime.Now.TimeOfDay can be translated in 2.1？？

**Comment by wangpengxpy** [comment]
@smitpatel  wow，It's my fault，tks。DateTime.Now.TimeOfDay can be translated in 2.1？？

**Comment by wangpengxpy** [comment]
@smitpatel  TimeSpan.Parse also be client evaluated？

**Comment by smitpatel** [comment]
`DateTime.Now.TimeOfDay` is translated to server only on SQLite. But on SqlServer it would be still client eval.
TimeSpan.Parse is client eval and may not have easy translation to server.

**Comment by wangpengxpy** [comment]
@smitpatel  thanks for your reply，get it。
