### ISSUE TITLE
Query: correlated collection optimization doesn't get applied for subqueries with AsQueryable

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12195]
Currently we only apply correlated collection optimization of the subquery doesn't have any result operators. We should allow AsQueryable, for cases like this:

```cs
var query = ctx.LevelOne.Select(l1 => new 
{ 
    l1.Id, 
    Collection = l1.OneToMany_Optional.AsQueryable().Include(l2 => l2.OneToOne_Required_FK).ToList() 
});
```

i.e. to apply include on a collection when the source qsre is not projected directly (https://github.com/aspnet/EntityFrameworkCore/issues/12181 has more details)

**Comment by maumar** [comment]
need to decide how we approach Include for those complex scenarios.

**Comment by ajcvickers** [comment]
@smitpatel to link to Include issue.

**Comment by smitpatel** [comment]
Based on include path interpretation we can determine if we need this kind of pattern supported. https://github.com/aspnet/EntityFrameworkCore/issues/12737

**Comment by ajcvickers** [comment]
Moving this to 3.0 to consider as part of the overall 3.0 query plan: #12795

**Comment by smitpatel** [comment]
@maumar - Given that nav rewrite converts methods to queryable, does it swallow away AsQueryable? If not, should it do it? Is this issue relevant anymore?
