### ISSUE TITLE
Second level Caching

### ISSUE THREAD

**Issue by sachinsu** [dotnet/efcore#12197]
Does EF Core support Second level Caching ? if not , is it being planned ?

**Comment by gwendallg** [comment]
Like hibernate ...

**Comment by ajcvickers** [comment]
@sachinsu @gwendallg This is being tracked by #5858. However, we aren't planning on implementing this. Instead, as stated in that issue, we are of the belief that a second-level cache could be implemented outside of EF Core, with EF Core plugging into as needed. Hopefully, this external second-level cache can be built using already available and tested caching implementations. We don't plan to implement a second-level cache in the EF codebase at this time, so we are closing this issue. However, we would be happy to work with others in the community to add appropriate hooks as needed to allow and external cache to be used.

**Comment by Deilan** [comment]
Consider looking at [EFSecondLevelCache.Core](https://github.com/VahidN/EFSecondLevelCache.Core).
