### ISSUE TITLE
I can´t set the connection string in the DbContextOptionsBuilder or DbContextOptionsBuilder<TContext> in a windows class library project

### ISSUE THREAD

**Issue by JuanIrigoyen** [dotnet/efcore#12202]
In the previous version I used the next code to configure my connection string, loggin, etc.
In the current version I can´t access to UseSqlServer to set my connectionstring and add the logger factory. How can I solve this?

### Steps to reproduce
Create a Library Class in 4.7.1 

```c#
MaldivasLoggerFactory mflp = new MaldivasLoggerFactory();
var optionsBuilderMain= new DbContextOptionsBuilder();
optionsBuilderMain.UseSqlServer(connectionString);
optionsBuilderMain.UseLoggerFactory(mflp);
return new MaldivasAccountContext(optionsBuilderMain.Options);
```
### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: Sql Server 2016
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.7.3)

**Comment by ErikEJ** [comment]
Do you reference the SQL server provider package?

**Comment by JuanIrigoyen** [comment]
No @ErikEJ!!!!, thank you very much. Do you know  what is the difference and how to use DbContextOptionsBuilder<TContext> for the same configuration?
