### ISSUE TITLE
EFCore2.0 upgrade to 2.1 compiler problems, unable to work?

### ISSUE THREAD

**Issue by cjlaravel** [dotnet/efcore#12222]
EFCore2.0 upgrade to 2.1 compiler problems, unable to work?

CSC: warning CS8032: cannot create an instance of parser Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer from C:\Users\Administrator\.nuget\packages\microsoft.entityframeworkcore.analyzers\2.1.0\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll: Could not load file o R assembly'Microsoft.CodeAnalysis,
The specified file is not found in Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
### Further technical details
EF Core version: 2.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: win7-x64
IDE: Visual Studio Code 1.23

**Comment by ajcvickers** [comment]
@fujianxiamen Can you post the output of `dotnet --info` inside the project directory?

**Comment by darthyoshi** [comment]
Getting the same warning, here's my output for `dotnet --info`:
```.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  fe590c614c

Runtime Environment:
 OS Name:     fedora
 OS Version:  27
 OS Platform: Linux
 RID:         fedora.27-x64
 Base Path:   /usr/lib64/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : N/A```

**Comment by smitpatel** [comment]
Need to install new .NET core.

**Comment by ajcvickers** [comment]
@fujianxiamen Can you post a project that has this behavior so that we can investigate?

**Comment by ajcvickers** [comment]
@fujianxiamen We discussed this and came to the conclusion that using VS Code without a warning will require installing the .NET Core 2.1. SDK.
