### ISSUE TITLE
can't migrate an entity with a byte[] property using mysql

### ISSUE THREAD

**Issue by kawazaku** [dotnet/efcore#12221]
i attempt to use two database providers sqlserver,mysql, and i have a property with a byte[] type.
applying migration has succeeded with sqlserver with varbinary(MAX), but failed when used with mysql.

Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `Sliders` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `BackgroundImage` varbinary NULL,
    `Test` text NULL,
    `Text` text NOT NULL,
    `Title` text NOT NULL,
    PRIMARY KEY (`Id`)
);
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL,
    `Test` text NULL,
    `Text` text NOT NULL,
    `Title` text NOT NU' at line 3

**Comment by ajcvickers** [comment]
This looks like an issue with the MySQL database provider. Please file an issue with the appropriate provider author--see https://docs.microsoft.com/en-us/ef/core/providers/
