### ISSUE TITLE
Expose DbContext._options through public property

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/efcore#12225]
Created on request from @divega https://github.com/aspnet/EntityFrameworkCore/issues/11657#issuecomment-394181131

[linq2db integration with EF.Core](https://github.com/linq2db/linq2db.EntityFrameworkCore) needs access to `DbContextOptions` for specific `DbContext` instance or more precisely, to  `DbContextOptions.Extensions` collection.

Current implementation uses reflection to read private field `_options`:  https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L300

**Comment by ajcvickers** [comment]
@MaceWindu For what reason do you need DbContextOptions? The reason I ask is because it is not intended that these options be obtained and used directly. Instead, the way to access options is from registered options extensions. For example:
```C#
var optionsExtension = context
    .GetService<IDbContextOptions>()
    .FindExtension<CoreOptionsExtension>();
```

**Comment by MaceWindu** [comment]
I think you are right here. Will check and close this issue, if it will help

**Comment by MaceWindu** [comment]
ok, we don't need it. Thank you :)
