### ISSUE TITLE
Expose DbContext from EntityQueryProvider class

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/efcore#12226]
Created on request from @divega https://github.com/aspnet/EntityFrameworkCore/issues/11657#issuecomment-394181131

[linq2db integration with EF.Core](https://github.com/linq2db/linq2db.EntityFrameworkCore) needs access to `DbContext` instance from EF.Core `IQueryable` instance.

We can access EntityQueryProvider using cast from `IQueryable.Provider`, but next we need to access several private fields and properties to extract required DbContext:
EntityQueryProvider -> _queryCompiler (private field) -> _queryContextFactory (private field) -> Dependencies (protected property) -> CurrentDbContext (public) -> Context (public)

https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L480

**Comment by ajcvickers** [comment]
@tuespetre Can you comment on how you integrated with EF for your Impatient query provider? Did you hook into our services or attempt to intercept at the LINQ layer, like above? How was the experience?

**Comment by tuespetre** [comment]
I implement `IQueryCompiler` which is injected with a few things, chief among them being `ICurrentDbContext`.

**Comment by ajcvickers** [comment]
@tuespetre Thanks for the input.

@MaceWindu We will look at putting in a better hook for this. However, you might consider integrating at the service provider level instead, as @tuespetre is doing, since that will give you more options for overriding services, participating in the pipeline, etc.

**Comment by ajcvickers** [comment]
We discussed this again and there is considerable feeling that this isn't the right extension point. We can revisit again later if this is still needed after the 3.0 query changes.

**Comment by codemunkie15** [comment]
Hi @ajcvickers 

Is there any movement on this please? I have an `IQueryable` extension method that transforms entities into different types based on some configuration and I'd really like to be able to get access to the `DbContext` inside the extension method (from the `IQueryable`).

Thanks

**Comment by roji** [comment]
@codemunkie15 can you provide a bit more context on why you need this?
