### ISSUE TITLE
Make AsQueryable unnecessary for Include calls on collections

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12238]
Lately we have discussed scenarios in which the Include method needs to be applied to a collection navigation inside the query’s projection. Because of the signature of Include, a call to AsQueryable has to be chained before Include in these scenarios. But unlike other query operators, Include is defined by EF Core, and we could choose to add versions work on `IEnumerable<T>`.

**Comment by ajcvickers** [comment]
Notes from triage: Consider whether this pattern is something we want to promote going forward before doing this, especially in relation to reference navigations as well. See https://github.com/aspnet/EntityFrameworkCore/issues/12181#issuecomment-394437344 and #2953

**Comment by smitpatel** [comment]
Irrelevant after #12737
