### ISSUE TITLE
Spatial API uniformity across providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#12246]
@bricelam out of curiosity...

I know you're working on spatial/GeoAPI/NTS support for SQL Server; are you doing anything at the EF Core level in general, or is the support purely SQL Server-specific? Is there anything we should align on to make spatial support as uniform across the providers? For example, I think you're looking at translating the GeoAPI interfaces whereas Npgsql translates the NetTopologySuite implementation?

**Comment by bricelam** [comment]
We're going to discuss this (and more) in an upcoming design meeting. I've been prototyping for SQL Server and SQLite (and looking at PostGIS) to gather notes and see what design decisions we need to make. We'll be sure to invite you to the design meeting, so we can get your thoughts.

**Comment by bricelam** [comment]
But yes, our hope is to establish a pattern for all providers to implement. Any code that can be shared will go into a common assembly. (e.g. EFCore.Relational.NTS)
