### ISSUE TITLE
Ability to Count Calls to Data Store / Raise Event After Accessing Persistence

### ISSUE THREAD

**Issue by ardalis** [dotnet/efcore#12259]
I'd like to be able to perform some action (in this case, incrementing a counter) whenever a call to persistence is made by an EF Core DbContext. This might be possible now, but I'm not seeing a way to do it.

**Example Scenario:**
I have an ASP.NET Core app which includes middleware, filters, controllers, repositories, and services, all of which will use the same Scoped instance of a DbContext. At the end of a request, I'd like to be able to see how many times this DbContext hit the database. I don't want to have to log the details of every individual query and then manually count them. I also want this count to (ideally) be consistent regardless of whether I'm using InMemory or SqlServer providers. The goal is simply to identify if a large number of requests are being made to persistence within the lifetime of a given DbContext (and web request).

Is this possible now? If not, can some method of performing this be added, such as providing an event I can handle for something like PersistnceCallCompleted() or similar?

Thanks!

**Comment by ardalis** [comment]
That might do the trick. I didn't see that off of my DbContext in its controller - how does one access it?

**Comment by ardalis** [comment]
Though, I don't see how that would *also* behave the same when using InMemory provider.

**Comment by ajcvickers** [comment]
@ardalis Can you provider a more concrete definition of what constitutes a "call to persistence"? Some examples of things that may or may not be:
* Opening a connection
* Executing a LINQ query against the database
* The resultant database query or queries that result from the LINQ query--also, would this be always one "call" or could be more if there were multiple queries generated?
* Rolling back a transaction
* SaveChanges. Also, is this one, or many "calls" if it results in multiple commands.
* And so on...

**Comment by ardalis** [comment]
Pretty much if I'm looking at SQL Profiler, and it results in a command being executed there, I would like that to be counted. Ideally, I'd like it to be counted the same way if I'm using the InMemoryProvider, but I understand if that's difficult (I'd still like *some* count even if it's not quite identical in that case).

In older versions of .NET, I could use tools like Performance Counters or Glimpse to track how many calls were being made to my database in the course of a given ASP.NET request. With ASP.NET Core, I'm unaware of the availability of such diagnostic tools that provide the simple measure of "how many hits to the db were there in this page request". That's what I'm going for. Of course, once I have that, I may ask for "and how long did that take" as an obvious next question, so if that's easily added from the start, so much the better.

A cross-platform approach that might work would be some kind of event that is raised whenever a call out to the persistence layer occurs. These could be multiple events based on the different kinds of things you've identified in your previous comment, or the event itself could simply include an `EventType` property with values like `OpenConnection`, `ExecuteQuery`, `ExecuteCommand` along with perhaps a `DurationMilliseconds` (to cover my follow-up request).

I don't care about `SaveChanges` as that isn't, in itself, a call to persistence. Sometimes, `SaveChanges` might not make any call to persistence (because there have been no changes) - I wouldn't want that counted. I assume it's possible that sometimes `SaveChanges` results in multiple separate commands being sent to the persistence layer. I'd want that to count more than once (probably - if it's a single batch operation it would probably just count as one  ExecuteCommand call).

At the end of the day, I'd like to be able to add a Filter or Middleware to my ASP.NET Core app that can do something like this:

ConfigureServices:

```
services.AddDbContext<AppDbContext>(options =>
{
  options.UseInMemoryDatabase("foo"); 
  // or  options.UseSqlServer("");
  options.OnPersistenceAccess += PersistenceAccessHandler;
}

public void PersistenceAccessHandler(PersistenceEvent e)
{
  // log the event or increment a counter
}
```

SomeFilterOrMiddlewareWrappingTheRequest:

`_logger.LogInformation("Persistence was accessed {counter.Count} times taking {counter.Duration}ms.");`

**Comment by ardalis** [comment]
Also, if it makes it easier to scope this into something that could be released sooner, I'd be fine if all it supported in the first version was queries. Not commands. Not transactions. Nothing else. Just queries. That's usually where the N+1 type performance problems occur, not in the other places.

**Comment by ajcvickers** [comment]
@ardalis I don't think it will be possible to achieve both these things:
* Get events that map to persistence as described for a relational database
* Have the same events generated for the in-memory provider

In fact, even for different relational providers the event counts will be different depending on what can be translated for queries and what capabilities are available for updates.

Given this, we feel that the events already being published for relational databases (see [RelationalEventId](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Diagnostics/RelationalEventId.cs)) should cover the types of calls you are asking for.

**Comment by ardalis** [comment]
I understand. Are there any docs on wiring up and consuming the relational events you linked to? I'm unfamiliar with them and my quick search didn't turn up anything useful. Are they only added as part of log messages, not raised as .NET events (that I could hook into with ` += handler`)? Thanks!
