### ISSUE TITLE
Wrong Entity returned from EnityEntry.Navigation() method

### ISSUE THREAD

**Issue by cdarrigo** [dotnet/efcore#12277]
I need access to the EntityEntry of a tracked entities child property. 

For example:   my DepositEntity has a navigation property called "Transaction" which is a TransactionEntity.

I'm trying to get to the entityEntry info as follows:

```
var entity = new DepositEntity
{
Id = 1,
Transaction = new Transaction { Id=1}
};

var entry = this.dbContext.Deposits.Attach( entity);
var transactionEntry = entry.Navigation("Transaction").EntityEntry;
```

so far so good.  However if I try to get a property off the Transaction object (like TransactionDate) I get an exception that states TransactionDate is not a property of **DepositEntity**.  Despite me getting the EntityEntry for the Transaction property, its underlying EntityEntry is that of its parent (DepositEntry) and not of its navigation Type (TransactionEntity).  As a result, I'm not able to access any of the property change tracking info for the nested Transaction property.

### Further technical details
EF Core version: 2.10
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@cdarrigo As the documentation for that property says, it returns the EntityEntry for the entity that contains that member. not the entry for the the entity pointed to by that member. For that, get the current value of the navigation and ask for its entry:
```C#
var transactionEntry = context.Entry(entry.Navigation("Transaction").CurrentValue);
```
