### ISSUE TITLE
Persistance of third party assembly models

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#12275]
I'd like to use particular classes of some library as entities to persist them in a database. For example [NodaMoney](https://github.com/remyvd/NodaMoney) I'd like to persist Currency class to be able to refer to it from my other entities by id. Of course Currency class doesn't have an Id.

What's the preferred way to do this in EF Core? Can I somehow re-use third-party models as my entities or I should create my own entity class and just use NodaMoney classes for my business logic?

**Comment by ajcvickers** [comment]
@lecoque The code below uses value-converters to setup a property mapping for the NodaMoney.Currency type. I chose to just store the ISO code in the database, but the converter could use any serialized format. Hope this helps.

```C#
public class Blog
{
    public int Id { get; set; }
    public NodaMoney.Currency Currency { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Blog>()
            .Property(e => e.Currency)
            .HasConversion(
                v => v.Code,
                v => Currency.FromCode(v));
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog { Currency = Currency.CurrentCurrency });
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var blog = context.Set<Blog>().Single();
            
            Console.WriteLine($"Blog {blog.Id} has currency {blog.Currency.Code}");
        }
    }
}
```

**Comment by lecoque** [comment]
@ajcvickers  definitely helps but wouldn't it be better to create currency entity and add all currencies to the database with `HasData` and later reference them by id?

**Comment by ajcvickers** [comment]
@lecoque Would you want to use the ISO code as the ID, or map it to some other value?

**Comment by ajcvickers** [comment]
@lecoque Also, can you explain the advantages of creating a table for the Currency class?
