### ISSUE TITLE
Query: consider expanding null safety beyond nav rewrite

### ISSUE THREAD

**Issue by AlekseyMartynov** [dotnet/efcore#12284]
Version: `2.1.1-rtm-30843` (nightly build)

Please consider this example:

Entity:
```c#
public class TestEntity {
    public int ID { get; set; }
    public DateTime? Date { get; set; }
}
```

Ensure there are records:
```c#
var set = context.Set<TestEntity>();
set.Add(new TestEntity());
context.SaveChanges();
```

Now, this is a query that is fully translated into SQL:

```c#
var result = set
    .GroupBy(obj => new {
        Year = (int?)obj.Date.Value.Year
    })
    .Select(g => new {
        g.Key.Year,
        Count = g.Count()
    })
    .ToArray();
```

```sql
SELECT DATEPART(year, [obj].[Date]) AS [Year], COUNT(*) AS [Count]
FROM [TestEntity] AS [obj]
GROUP BY DATEPART(year, [obj].[Date])
```

However, if I modify it as follows:
```c#
var result = set
    .GroupBy(obj => new {
        Year = (int?)obj.Date.Value.Year
    })
    .Select(g => new {
        g.Key.Year,
        Count = g.Count(i => i.Date != null) // change here: count only non-null dates
    })
    .ToArray();
```

then it is partially translated into SQL:
```sql
SELECT [obj].[ID], [obj].[Date]
FROM [TestEntity] AS [obj]
ORDER BY DATEPART(year, [obj].[Date])
```

but grouping is done in-memory.

It fails with `Nullable object must have a value.`

I understand that for LINQ 2 Objects I would have to add null-conditional:
```c#
Year = obj.Date == null ? null : (int?)obj.Date.Value.Year
```

**Finally the question:**

Should the user of EF Core proactively take care of  null safety as with L2O? Or on the contrary it is a bug and EF Core in-memory magic must hide it from me?

**Comment by ajcvickers** [comment]
We do perform some re-writing already to cover some similar cases. We will consider enhancing this for 3.0.

**Comment by AlekseyMartynov** [comment]
@smitpatel 

> In the absence of client eval, this may not provide much value.

Yes, this ticket is about cases where a query is executed partially in SQL and partially in memory.
Are you planning to drop client evaluation in 3.0?

**Comment by smitpatel** [comment]
> Are you planning to drop client evaluation in 3.0?
Brief answer, we are dropping it for most cases.
I will post long answer on #12795 soon.
