### ISSUE TITLE
Rendering DateTime contants as SQL timestamp literals breaks comparisons

### ISSUE THREAD

**Issue by filipelbc** [dotnet/efcore#12281]
This bug appears after updating from EF 2.0.3 to EF 2.1.0.

I'm using EF with PostgreSQL.

I have a model with a `DateTime` field (which becomes a `timestamp without timezone` in the database). 
Let's say it is looks like this:
```c#
class Model {
      public DateTime Date { get; set; }
}
```

And I have added some entries, like this:
```c#
var models = new[] {
    new Model() { date = DateTime.MaxValue };
    new Model() { date = DateTime.Now };
}
context.AddRange(models);
```

So that I have the following in the database:

| Date |
| ------ |
| `9999-12-31 23:59:59.999999` |
| `2018-06-07 11:41:34.6655` |

Then, when I try to select some entries, depending on how I pass the datetime value to the query, it gives different results (after updating to EF 2.1.0), because, as the logs show, in the first case, the value gets rendered into a SQL timestamp literal with only milliseconds precision.

## Case 1: Fails
```c#
Assert.Equal(1, context.Models.Where(x => x.Date == DateTime.MaxValue).Count());
```

## Case 2: Works
```c#
var date = DateTime.MaxValue;
Assert.Equal(1, context.Models.Where(x => x.Date == date).Count());
```

# Queries logged:

## Case 1:
```
[2018-06-07 11:50:56.867 -03:00] [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)::INT4
FROM "Models" AS x
WHERE x."Date" = TIMESTAMP '9999-12-31 23:59:59.999'
```

## Case 2:
```
[2018-06-07 12:04:43.101 -03:00] [INF] Executed DbCommand (0ms) [Parameters=[@__date_0='12/31/9999 23:59:59' (DbType = DateTime)], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)::INT4
FROM "Models" AS "x"
WHERE "x"."Date" = @__date_0
```

**Comment by ajcvickers** [comment]
@filipelbc Can you please file this on https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues since the issue is most likely that the PostgreSQL provider needs to override literal generation for this mapping.
