### ISSUE TITLE
Error in GroupBy after Concat or Union linq

### ISSUE THREAD

**Issue by mpetrinidev** [dotnet/efcore#12289]
I'm having a situation with group by clause after concat or union.

If i remove group by, the query works fine and return the results expected but not grouping and total points (Puntos).

Query

    var resultados = (from p in partidos
                        join e1 in equipo
                        join e2 in equipo
                        join g in grupo
                        join up in usuario_partido
                        join pr in pronostico
                        where ..
                        group up by g.Nombre into g
                        select new
                        {
                            Grupo = g.Key,
                            Posiciones = (
                            (
                                from g1 in g
                                select new
                                {
                                    Equipo = g1.Partido.Equipo1.Nombre,
                                    Imagen = g1.Partido.Equipo1.Imagen,
                                    Puntos = g1.Goles_Equipo1 > g1.Goles_Equipo2 ? 3 : g1.Goles_Equipo1 == g1.Goles_Equipo2 ? 1 : 0
                                }
                            ).Concat
                            (
                                from g1 in g
                                select new
                                {
                                    Equipo = g1.Partido.Equipo2.Nombre,
                                    Imagen = g1.Partido.Equipo2.Imagen,
                                    Puntos = g1.Goles_Equipo2 > g1.Goles_Equipo1 ? 3 : g1.Goles_Equipo2 == g1.Goles_Equipo1 ? 1 : 0
                                }
                            )).GroupBy(p => new { p.Equipo, p.Imagen }, (k, gr) => new
                            {
                                Equipo = k.Equipo,
                                Imagen = k.Imagen,
                                Puntos = gr.Sum(p => p.Puntos)
                            })
                        });

### Exception

> System.ArgumentException: Expression of type
> 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Usuario_Partido,Microsoft.EntityFrameworkCore.Storage.ValueBuffer],System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]],Microsoft.EntityFrameworkCore.Storage.ValueBuffer]]'
> cannot be used for parameter of type
> 'System.Collections.Generic.IEnumerable`1[System.Object]' of method
> 'System.Collections.Generic.IEnumerable`1[System.Object]
> Concat[Object](System.Collections.Generic.IEnumerable`1[System.Object],
> System.Collections.Generic.IEnumerable`1[System.Object])' 
> 
> Parameter name: arg0

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: vscode 1.24.0

**Comment by smitpatel** [comment]
Can you try the query with 2.1.0 version of the package?

**Comment by mpetrinidev** [comment]
@smitpatel same problem with 2.1.0 version! 

As in 2.0.3 it's work with OrderBy but not with ToList()

I put

    .OrderByDescending(p => p.Puntos)
    .GroupBy(p => new { p.Equipo, p.Imagen }, (k, gr) => new
    {
        Equipo = k.Equipo,
        Imagen = k.Imagen,
        Puntos = gr.Sum(p => p.Puntos)
    })

Works fine but if i put ToList() throw

>Could not parse expression 'g.Select(g1 => new <>f__AnonymousType163(Equipo = g1.Partido.Equipo1.Nombre, Imagen = g1.Partido.Equipo1.Imagen, Puntos = IIF((g1.Goles_Equipo1 > g1.Goles_Equipo2), 3, IIF((g1.Goles_Equipo1 == g1.Goles_Equipo2), 1, 0)))).Concat(g.Select(g1 => new <>f__AnonymousType163(Equipo = g1.Partido.Equipo2.Nombre, Imagen = g1.Partido.Equipo2.Imagen, Puntos = IIF((g1.Goles_Equipo2 > g1.Goles_Equipo1), 3, IIF((g1.Goles_Equipo2 == g1.Goles_Equipo1), 1, 0))))).OrderByDescending(p => p.Puntos).ToList()': 
>
>This overload of the method 'System.Linq.Enumerable.ToList' is currently not supported.

Thanks!

**Comment by ajcvickers** [comment]
@mpetrinidev If possible, could you please post either a project/solution or complete code listing that will allow us to reproduce the behavior you are seeing.

**Comment by maumar** [comment]
this query is not supported - we cant translate set operation after group by. However, groupby after set operation has been fixed in 3.0. 
However, currently we have a bug when result selector is used and grouping key is part of that result selector. https://github.com/aspnet/EntityFrameworkCore/issues/18267 Workaround is to use .Select rather than result selector
