### ISSUE TITLE
First commit

### ISSUE THREAD

**Issue by Matthiee** [dotnet/efcore#12302]
What are some good labels for a first commit?

**Comment by smitpatel** [comment]
We use `up-for-grabs` label for the issue which we think are good for community contributions. https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs

Some of them may require bit more expertise of code base so may not be suitable as first commit. Still, check out issues, see what interests you and start a discussion on issue. We would be happy to provide guidance as needed :)
