### ISSUE TITLE
Feature toggle for empty Sum equal zero?

### ISSUE THREAD

**Issue by AlekseyMartynov** [dotnet/efcore#12307]
I understand the rationale behind #800.
Now EF Core is consistent with L2O `Sum()` and [maths](https://en.wikipedia.org/wiki/Empty_sum).
But this can be unexpected/undesired from the perspective of previous experience with [SQL](https://dba.stackexchange.com/q/25435) and other LINQ providers (EF6 and NHibernate in particular).

May the behavior be made configurable?

**Comment by ajcvickers** [comment]
@AlekseyMartynov Thanks for the suggestion. We understand that this may be unexpected, but we believe that the functionality as it stands is correct, and we're not convinced at this time that there is enough value in adding a flag for this behavior.
