### ISSUE TITLE
Issue from 9659

### ISSUE THREAD

**Issue by Looooooka** [dotnet/efcore#12308]
I'm not saying the query code is correct in the old version but I've literally seen dozens of people use it online to get sums on empty tables.
The "select tr).SumAsync(cr => (Decimal?)cr.Value)" hack worked just fine in the previous version.
Right now it's ignoring the user telling it to cast it to a nullable so he can set the result to 0 if sum returns null
If you do it after upgrading to 2.1 it fails and there have been posts about people experiencing the same problem on multiple sites.
Now I fixed my queries but since it worked in the previous version perhaps changing it to the old behavior isn't necessarily a bad thing.
here's the solution demonstrating the problem:
my query is a multi join query and I didn't really have the time to go set up a more complex example...but I think the problem is pretty much similar to the one in this project.

https://drive.google.com/drive/folders/1fMJ-x58v1nH3xibRR_CPuApxNP3yUjoH

**Comment by ajcvickers** [comment]
Duplicate of #12307
