### ISSUE TITLE
Does not save DateTimeOffset value

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#12305]
Describe what is not working as expected.
When I'm SQLITE, DateTimeOffset columns are not saved.  I'm sure that #12262 is related.

This is in EFCore 2.1

**Comment by ajcvickers** [comment]
@TonyValenti I have not been able to reproduce this--see test code below. Can you please post a runnable project/solution or modify the code listing below so that the behavior you are seeing is reproduced?

```C#
public class Blog
{
    public int Id { get; set; }
    public DateTimeOffset Offset { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlite("DataSource=testdb");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog { Offset = new DateTimeOffset(DateTime.Now) });
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var blog = context.Set<Blog>().Single();

            Console.WriteLine($"Blog {blog.Id} has offset {blog.Offset}");
        }
    }
}
```

**Comment by TonyValenti** [comment]
I'm digging into this and I think I posted prematurely.  It looks like it
is an issue with Z.EntityFramework.Extensions.


Always glad to help,

[image: AlphaDrive for Clio] <https://www.alphadriveforclio.com/>

Tony Valenti
Software Engineer
T: 402-401-7568 <javascript:void(0);>
E: Tony.Valenti@AlphaDriveForClio.com
W: www.AlphaDriveForClio.com <https://www.alphadriveforclio.com/>

Schedule a Meeting with Me
<https://www.alphadriveforclio.com/schedule-meeting>
This message contains confidential information and is intended only for the
intended recipients. If you are not an intended recipient you should not
disseminate, distribute or copy this e-mail. Please notify us immediately
by e-mail if you have received this e-mail by mistake and delete this
e-mail from your system. E-mail transmission cannot be guaranteed to be
secure or error-free as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. Therefore we do
not accept liability for any errors or omissions in the contents of this
message, which arise as a result of e-mail transmission. If verification is
required please request a hard-copy version.

**Comment by TonyValenti** [comment]
@ajcvickers what are you reopening then reclosing these old issues?

**Comment by ajcvickers** [comment]
@TonyValenti to move them from closed as "complete" to closed as "not planned".
