### ISSUE TITLE
FK name (identifier) handling inconsistencies 

### ISSUE THREAD

**Issue by frdani** [dotnet/efcore#12301]
- After migrating from 2.0 to 2.1 the default FK generation / handling must have changed,
new migrations under 2.1 cap the FK names (errornously see bellow) while 2.0 generated the long names but caped them during migration. This is a breaking change and should be emphasized in the docs.

- 2.1 default naming (with the Pomelo Mysql driver) Caps wrongfully. The max length of an identifier is 64 chars to which it is capped and then a tidelwave is appended to it making the length one char too long again (FK_something_that_is_64_char_long + ~).

```
Exception message: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Identifier name 'FK_something_that_is_64_char_long ~' is too long ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Identifier name 'FK_something_that_is_64_char_long ~' is too long
```
### Steps to reproduce
- For the migration
Migrate from 2.0 where you had longer than 64 char length. 
And then try to update a new database.
- The bad keys are generated:
Simply have a FK that is longer than 64 char

### Further technical details
EF Core version: 2.1.300
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.1.0-rc1-final
Operating system: Linux (Manjaro) Kernel 4.14.48 also on Windows 10
IDE: console / RIDER / CODE doesn't matter
On Windows I tested it with Mysql 5.7 on Linux with a recent MariaDb.

**Comment by ajcvickers** [comment]
Created a docs issue for this: https://github.com/aspnet/EntityFramework.Docs/issues/757
