### ISSUE TITLE
Have crucial bugs for a good UWP experience been fixed in the latest EFCore 2.1?

### ISSUE THREAD

**Issue by sadqiang** [dotnet/efcore#12310]
I am reading a tutorial [Getting Started with EF Core on Universal Windows Platform (UWP) with a New Database](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started) and I find a notice as follows.

> This tutorial uses EF Core 2.0.1 (released alongside ASP.NET Core and .NET Core SDK 2.0.3). EF Core 2.0.0 lacks some crucial bug fixes required for a good UWP experience.

Because the tutorial might have not been updated yet, I am not sure whether or not this issue still exits in the latest EFCore 2.1. Could you confirm me?

**Comment by ajcvickers** [comment]
@sadqiang The docs should still work for 2.1--the fixes mentioned for 2.0.1 are also included in 2.1. We still have limited testing on UWP, but from the testing we have done and the reports of others the only known outstanding issue is being tracked here: https://github.com/dotnet/corefx/issues/30255

**Comment by ajcvickers** [comment]
@sadqiang Also, note that you will need the latest VS release and latest Windows build and SDK.

**Comment by Noemata** [comment]
The UWP docs are not yet valid for EF Core 2.0.1, please address.  Given the order of updating issues by @ajcvickers, that should have been addressed here.
