### ISSUE TITLE
Adding Microsoft.EntityFrameworkCore.Sqlite to UWP project and to class library project causes failure in Net Native compilation

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#12328]
I've created new Xamarin Forms project, updated Microsoft.NETCore.UniversalWindowsPlatform to version 6.1.5 and installed Microsoft.EntityFrameworkCore.Sqlite 2.1.0 package to UWP and class lib projects. After that, release mode compilation on UWP with Net Native Toolchain enabled - fails with error "Internal compiler error: Object reference not set to an instance of an object."

Can someone explain me what exactly causes that error and suggest a workaround, if possible

Sample of solution is [here](https://drive.google.com/open?id=1yfbeXguLGhNx-O3Fp6FLQqQicsfiPLlI)

Operating system: 
Windows 10.0.17134
IDE: (Visual Studio 2017 15.7.3)

**Comment by smitter86** [comment]
recent update to Microsoft.EntityFrameworkCore.Sqlite 2.1.1 fixed the problem

**Comment by divega** [comment]
This was probably due to problems in System.Memory.
