### ISSUE TITLE
How to persist computed properties

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#12333]
Is there some easy way to persist computed (getter only) properties?

For example:

```csharp
public decimal DiscountNetValue => NetValue - (DiscountRate * NetValue);
public decimal NetValue => NetPrice * Quantity;
public decimal GrossValue => GrossPrice * Quantity;
```

They're `NotMapped` by convention, but I'd like to persist them to not calculate them every time. I tried explicitly adding them in `OnModelCreating` but it didn't work. 

In this case should I calculate them in the constructor, or add a method like `CalculatePrices`? I want to calculate them only once when adding and read them after.

**Comment by Diaskhan** [comment]
Realize set method ! And define your logic to recalculate ! 

Or define get method and realize calc of yore property!

**Comment by Diaskhan** [comment]
https://stackoverflow.com/questions/8990319/have-a-custom-setter-on-property-for-ef-code-first-model-entity

**Comment by Tarig0** [comment]
To persist the property you need to store the information in a nullable or lazy field and access it using a public property

you would also need to add logic to NetValue, DiscountRate, Netvalue to invalidate the calculated fields so you don't store the wrong sum.

**Comment by Tarig0** [comment]
```C#
private decimal? netValue;
public decimal NetValue {
  get{
      if(netValue == null) {
        netValue = NetPrice * Quantity
      }
      return netValue
  } 
  private set {
    netValue = value;
  }
}


```

**Comment by Necronux** [comment]
I'm just revisiting the issue. 

@Tarig0 what about

```csharp
private decimal netValue;
public decimal NetValue {
  get => netValue;
  private set => netValue = value;
};
private decimal netPrice;
public decimal NetPrice {
  get => netPrice; 
  set {
    if (value != netPrice)
    {
      netPrice = value;
      netValue = NetPrice * Quantity
    }
  }
}
private decimal quantity;
public decimal Quantity{
  get => quantity; 
  set {
    if (value != quantity)
    {
      quantity = value;
      netValue = NetPrice * Quantity
    }
  }
}
```

instead of setting `null` or `default` to invalidate and calculating new value in property getter. I think the result is the same, drawback might be duplication of logic?

**Comment by Sigvaard** [comment]
This kinda sucks, the code would be much more readable and prettier if computed properties could be persisted easily.

**Comment by Diaskhan** [comment]
Calculated Field Is Function not ! not data !

**Comment by Sigvaard** [comment]
@Diaskhan 	it is, but still, even if it's calculated in code all the time it is accessed it would be helpful to persist it in the database for easier reports for example.

**Comment by Diaskhan** [comment]
Make abstract layer or extension to do that! without DI and DYnamic Linq its not possible!
If U need some magic then look to.

https://github.com/davideicardi/DynamicExpresso
Need some Linq or LambdaExperssion evaluator !

**Comment by Diaskhan** [comment]
There fore have another option
https://stackoverflow.com/questions/4706928/call-setter-when-any-property-of-a-class-changes

Using events!

**Comment by Tarig0** [comment]
Why are you worried about always calculating it in the code? Are you worried about performance?
