### ISSUE TITLE
GetType() on underlying entity not working

### ISSUE THREAD

**Issue by subprime** [dotnet/efcore#12336]
Hi all,

i have a problem after enable of Lazy Loading to get the type of the entity with GetType() which returns in some cases  Castle.Proxies.EntityName>Proxy and other type names. In my API i have endpoints which return different types of entities so that i need the entity type for mapping the entity against the right DTO.   

```c#
public async Task<Component> GetProjectComponentByIdAsync(int projectId, int componentId)
{
    var component = await _componentRepository.Get(p => p.Id == componentId && p.ProjectId == projectId)
        .SingleOrDefaultAsync();
    
    return component;
}

public async Task<IActionResult> GetProjectComponentByIdAsync(int projectId, int componentId)
{
    var component = await _projectService.GetProjectComponentByIdAsync(projectId, componentId);

    var typeOfComponent = component.GetType();

    if (typeOfComponent == typeof(ElectricalControlUnit))
    {
        var model = _mapper.Map<ElectricalControlUnit, ElectricalControlUnitDto>((ElectricalControlUnit) component);
        return Ok(model);
    }
    else if (typeOfComponent == typeof(MechanicalPart))
    {
        var model = _mapper.Map<MechanicalPart, MechanicalPartDto>((MechanicalPart) component);
        return Ok(model);
    }
    else
    {
        return BadRequest(new { message = "Type of component is invalid." });
    }
}
```

Is there a way to change this behavior or a solution? The amount of changes is big!

### Further technical details
EF Core version: 2.1
Database Provider: 2.1
Operating system: Windows 10
IDE: Visual Studio Pro 2017 15.7.3

**Comment by Tarig0** [comment]
try type.IsAssignableFrom(typeof(MechanicalPart))

**Comment by ajcvickers** [comment]
@subprime Lazy-loading using proxies relies on dynamically generating proxy classes that inherit from your actual entity types. These proxy types are what you are seeing, so if you want to find the entity type, then look at the base type of the proxy. Alternatively, you can implement types that support lazy loading but are not proxies--see the lazy loading docs for more info: https://docs.microsoft.com/en-us/ef/core/querying/related-data
