### ISSUE TITLE
Owned type is not table-split by default

### ISSUE THREAD

**Issue by andrewabest** [dotnet/efcore#12342]
I have a scenario where I want a simple `Owned` type as a property on an entity.

If I add the `Owned` type `BlobReference` as a property on my entity `CategoryItem` named `ImageReference`, I would expect to be able to create database fields with the naming convention `ImageReference_{PropertyName}` to house the table-split properties of my owned type.

If I do the above and create not-nullable database fields of the correct types to store the properties of my `BlobReference` owned type, and attempt to add a `CategoryItem` with a populated `ImageReference` property, I get the following exception:

`Cannot insert the value NULL into column 'ImageReference_Uri', table 'dbo.CategoryItem'; column does not allow nulls. INSERT fails` 

If I let Entity Framework create my schema instead of running my own migrations, I can see it creates a separate `BlobReference` table by default, with a FK reference back to the `CategoryItem` table.

I'd expect the default behaviour to be as indicated by the documentation found here https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#mapping-owned-types-with-table-splitting which states

> When using relational databases, by convention owned types are mapped to the same table as the owner.

### Steps to reproduce
Here is a full reproduction of the behaviour, built in LinqPad

```c#
void Main()
{
	var optionsBuilder = new DbContextOptionsBuilder<TestContext>();
	optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=ReadifyVotes;Trusted_Connection=True;MultipleActiveResultSets=true", providerOptions=>providerOptions.CommandTimeout(60));

	using (var context = new TestContext(optionsBuilder.Options))
	{
		context.Database.EnsureCreated();
		
		var item = new CategoryItem(Guid.NewGuid(), "Test item", new BlobReference("http://image"), "Test description", Guid.NewGuid());
		
		context.Add(item);
		context.SaveChanges();
	}
}

public class TestContext : DbContext
{
	public TestContext(DbContextOptions<TestContext> options) : base(options)
	{
	}
	
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);
		modelBuilder.RemovePluralizingTableNameConvention();
	}
		
	public DbSet<CategoryItem> CategoryItems { get; protected set; }
}

public static class ModelBuilderExtensions
{
	public static void RemovePluralizingTableNameConvention(this ModelBuilder modelBuilder)
	{
		foreach (IMutableEntityType entity in modelBuilder.Model.GetEntityTypes())
		{
			entity.Relational().TableName = entity.DisplayName();
		}
	}
}

public class CategoryItem 
{
	public CategoryItem()
	{
	}

	public CategoryItem(Guid id, string name, BlobReference imageReference, string description, Guid ownerId) : this()
	{
		Id = id;
		Name = name;
		ImageReference = imageReference;
		Description = description;
		CategoryId = Guid.Parse("00000000-0000-0000-0200-000000000000");
	}

	[Key] public Guid Id { get; protected set; }
	public Guid CategoryId { get; protected set; }
	public string Name { get; protected set; }
	public BlobReference ImageReference { get; protected set; }
	public string Description { get; protected set; }
}

[Owned]
public class BlobReference
{
	public BlobReference(string uri)
	{
		if (string.IsNullOrWhiteSpace(uri))
		{
			throw new ArgumentException("A uri must be supplied", nameof(uri));
		}


		Uri = uri;
	}

	public string Uri { get; protected set; }
}
```

### Further technical details
EF Core version: 2.1.300
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v2.1.0
Operating system: Windows 10 Pro
IDE: VS Code

**Comment by ajcvickers** [comment]
@andrewabest It's likely because of `RemovePluralizingTableNameConvention` See #12334
