### ISSUE TITLE
Better API for nulls in IValueReader.ReadValue

### ISSUE THREAD

**Issue by mikary** [dotnet/efcore#1234]
The behavior of a call to IValueReader.ReadValue<T> for a null value is not consistent between IValueReader implementations. The result can be either a null value or a DBNull. As a result, null value unit tests that use ObjectArrayValueReader (i.e. CompositeEntityKeyFactoryTest.Returns_null_if_any_value_in_the_entry_properties_is_null) do not cover DBNull edge cases.

**Comment by rowanmiller** [comment]
Clearing milestone, this was pri1 for RTM but not sure if we can make the change post-RTM

**Comment by rowanmiller** [comment]
What we have is working and it's super low level and can probably be changed in the future if needed
