### ISSUE TITLE
Allow same owned entity instance to be shared by many owners

### ISSUE THREAD

**Issue by elfrico** [dotnet/efcore#12345]
DDD style value object cannot be reused. Exception is thrown on context.SaveChanges().

```
Exception message: The entity of type 'Subscription' is sharing the table 'Subscriptions' with entities of type 'LocationValueObject', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values
Stack trace:    at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(Dictionary`2 sharedTablesCommandsMap)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IReadOnlyList`1 entries, Func`1 generateParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IReadOnlyList`1 entries)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ValueObjectIssue.Program.Main(String[] args) in E:\DEV\VS-SPIELWIESE\ValueObjectIssue\ValueObjectIssue\Program.cs:line 19
```

### Steps to reproduce
```c#
    public class LocationValueObject : ValueObject
    {
        public int LocationId { get; private set; }
        public string Name { get; private set; }

        protected LocationValueObject() { }

        public LocationValueObject(int locationId, string name)
        {
            if (locationId <= 0)
            {
                throw new ArgumentException("locationId invalid.", "locationId");
            }

            this.LocationId = locationId;
            this.Name = name;
        }

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return LocationId;
            yield return Name;
        }
    }

    public class Subscription
    {
        private Subscription(LocationValueObject locationId)
        {
            this.Location = locationId;
            this.DateCreated = DateTime.Now;
        }

        protected Subscription() { /* ORM, see https://github.com/aspnet/EntityFrameworkCore/issues/11074 */ }

        public static Subscription Create(LocationValueObject locationId)
        {
            return new Subscription(locationId);
        }
        
        public int SubscriptionId { get; private set; }
        public LocationValueObject Location { get; private set; }
        public DateTime DateCreated { get; private set; }
    }

    public class Context : DbContext
    {
        public DbSet<Subscription> Subscriptions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=SERVER;Database=value_object_issue;Trusted_Connection=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration<Subscription>(new SubscriptionConfiguration());
        }
    }

    internal class SubscriptionConfiguration : IEntityTypeConfiguration<Subscription>
    {
        public void Configure(EntityTypeBuilder<Subscription> builder)
        {
            builder.OwnsOne(p => p.Location);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new Context())
            {
                var location = new LocationValueObject(4711, "IDENT-NAME");

                var subscription1 = Subscription.Create(location);
                var subscription2 = Subscription.Create(location);

                context.Subscriptions.Add(subscription1);
                context.Subscriptions.Add(subscription2);

                context.SaveChanges();
            }
        }
    }
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017 15.7.3

**Comment by ajcvickers** [comment]
@elfrico Sharing owned entity type instances is not supported; I have created an issue to document this: https://github.com/aspnet/EntityFramework.Docs/issues/764

Triage: we will attempt to make the exception message better in this case since there is some expectation that owned types will act like value objects, which is true in some ways, but in general not the best way to view them conceptually.

**Comment by ajcvickers** [comment]
Another note from triage: when looking at this consider how feasible it would be to attempt to support this.

**Comment by elfrico** [comment]
@ajcvickers Thanks for investigation and clarification

**Comment by Tarig0** [comment]
Interesting looks like for value objects you would have to have the status be on the relationship instead of the entity, else you would have to copy the value object for each relationship.

**Comment by afranioce** [comment]
Attach same error https://github.com/aspnet/EntityFrameworkCore/issues/10578

**Comment by Cogax** [comment]
When I use `DbContextOptionsBuilder.UseInMemoryDatabase()`, this error doesn't occur. So if I test my application with that option, I don't get an Error. Shouldn't it behave the same way?

**Comment by ajcvickers** [comment]
Closing as this is no longer something we intend to implement.

**Comment by PTatsky** [comment]
How should we be implementing ValueObjects with Entity Framework Core?  I am using 3.1.5 and currently I am unable to support a DDD model with ValueObjects as I cannot share instances of value objects as owned entities between many owners.  This is a basic concept, I think.  I for example have an object ControlPanel with a value object ControlPanelNodeId.  I want to add a Zone to my ControlPanel.  The Zone also has a ControlPanelNodeId property.  When creating a Zone on the ControlPanel, the ControlPanelNodeId is populated with the value of the NodeId from the ControlPanel.  This means the Control Panel and the new Zone are sharing the same ControlPanelNodeId value object.

However, I encounter an error as the owned entity ControlPanelNodeID cannot be shared.

Please can you point me to documentation which shows me how to implement ValueObjects for a DDD model?

**Comment by AndriySvyryd** [comment]
Value object support will be implemented by https://github.com/dotnet/efcore/issues/13947

**Comment by PTatsky** [comment]
Thank you @AndriySvyryd.

For now I am having to implement a method on my value objects which allows me to clone them, effectively creating a new instance with the exact same value.  So when I assign a value object to a property on another aggregate, within the backing state that I have on an aggregate I call the .Clone() method in the property setter.

This allows me to get around the issue where EF Core is tracking the same instance by assigning an shadow ID to it.

Hopefully I can engineer this out when a better solution is offered either through #13947 or #9906?

**Comment by AndriySvyryd** [comment]
@PTatsky Yes, those two will likely be implemented together

**Comment by luisabreu** [comment]
I know this is closed, but is there any solution besides creating a clone method? I'm sorry, but coming from NH to EF is really a huge pain because EF seems to only understand tables...

**Comment by AndriySvyryd** [comment]
@luisabreu See https://learn.microsoft.com/ef/core/what-is-new/ef-core-8.0/whatsnew#value-objects-using-complex-types

**Comment by dario-l** [comment]
@AndriySvyryd @ajcvickers 

What about reusing the same type as owned in two different Entities?

We use typed identifiers and EF **throws** on `SaveChanges` because of mismatch between those two entity identifiers. To be clear we do not share an instance. It's all about a Type.

**Comment by AndriySvyryd** [comment]
Value objects are better represented with complex types

**Comment by dario-l** [comment]
> Value objects are better represented with complex types

@AndriySvyryd  I know but not usable because of this => https://github.com/dotnet/efcore/issues/32595#issuecomment-2916713943

Too many overlapping problems (bugs). 😞
