### ISSUE TITLE
Deleted entities are loaded indirectly?

### ISSUE THREAD

**Issue by jamiewinder** [dotnet/efcore#12359]
I've run into some surprising behaviour which I'm not sure is a bug or a misunderstanding on my part as to what the change tracker does. 

I have some code that loads an entity from the database and removes it. I then have another bit of code that (indirectly) tries to load that entity and it still appears.

```c#
var orderItem = db.OrderItems.Find(123);
db.OrderItems.Remove(orderItem);

var order = db.Orders
    .Where(order => order.Id == 123) // the order that contained the above item
    .Include(order => order.Items)
    .Single();

// order.Items still contains #123 despite it being removed
```
My understanding is that while the database would have returned `Order`#123 (since it's on the database and the removal hasn't been committed yet), EF's change tracker would recognise that it's effectively now gone and omit it? 

I've confirmed it's the exact same instance of `OrderItem` in the collection as was originally loaded so I don't think anything funny is going on in terms of not recognising it's the same item. 

Conversely, any previous *updates* to the entity do work as expected since of course it's the same instance. This makes the behaviour seem inconsistent if it's intentional?

**Comment by popcatalin81** [comment]
The item is not deleted, is marked for delete in current context.
