### ISSUE TITLE
Ef Core loads a property that is not part of an .Include.

### ISSUE THREAD

**Issue by HerraHak** [dotnet/efcore#12356]
What I'm doing is that I load some data from a sql server database like this : 
```C#
var ids = collection.SelectMany(c=>c.Table1).Select(io=>io.Id);
var properties = context.Table1.Where(io => ids.Contains(io.Id))
                .Include(io => io.Property3)
                    .ThenInclude(ioi => ioi.ChildProperty1)
                .Include(io => io.Property4);
```

Table1 presents itself like this : 
```C#
public class Table1{
   public int table2Id{get;set;}
   public Table2 Property2 {get;set;}
   public Table3 Property3 {get;set;}
   public Table4 Property4 {get;set;}
}
```

Now, after executing the query specified above, the Property2 is loaded even though it is not part of an Include.

Is there some hidden magic EntityFramework Core does ?
I use EntityFramework Core 2.0.3

thanks for your help everyone.
### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.0.3
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by Tarig0** [comment]
What does Tabe3 look like? Can you log the SQL?

**Comment by smitpatel** [comment]
Is that whole query (since it does not contain call to ToList)? ALso if Table2 is already loaded in context and if you are doing tracking query then the navigation would be populated even though its not in include.

We will need self-contained repro which demonstrate the issue you are seeing for investigation.

**Comment by HerraHak** [comment]
Indeed there's the ToList.Table2 is loaded in the context but for other queries it doesn't happen just for this one.
