### ISSUE TITLE
Migrations: Column max length missing in SQL after upgrading from 1.1

### ISSUE THREAD

**Issue by georgelanes** [dotnet/efcore#12368]
Migrating from asp.net core 1.1 to 2.1.0, the publish sql script is generated wrong.

### Publish generated from .net core 1.1 ( correct )
```sql
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20161014184435_dbv1')
BEGIN
    CREATE TABLE [Roles] (
        [Id] **nvarchar(450)** NOT NULL,
        [ConcurrencyStamp] nvarchar(max),
        [Name] nvarchar(256),
        [NormalizedName] nvarchar(256),
        CONSTRAINT [PK_Roles] PRIMARY KEY ([Id])
    );
END;
```

### Publish generated from .net core 2.1.0 ( wrong script )

```sql
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20161014184435_dbv1')
BEGIN
    CREATE TABLE [Roles] (
        [Id] **nvarchar(max)** NOT NULL,
        [ConcurrencyStamp] nvarchar(max) NULL,
        [Name] nvarchar(256) NULL,
        [NormalizedName] nvarchar(256) NULL,
        CONSTRAINT [PK_Roles] PRIMARY KEY ([Id])
    );
END;
```

**NOTE: Roles is Microsoft.AspNetCore.Identity.IdentityRole**

### Workaround
The workaround is change all migration and replace **nvarchar(max)** to **nvarchar(450)** for all **Id** column.

### Publish Output:

```
"IF NOT EXISTS(SELECT * FROM [__EFMigrationsHisto"
 Column 'Id' in table 'Roles' is of a type that is invalid for use as a key column in an index.
Could not create constraint or index. See previous errors. http://go.microsoft.com/fwlink/?LinkId=178587
  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_SQL_EXECUTION_FAILURE.)
Publish failed to deploy.

```

### Steps to reproduce
1. Have initial migration with EF Core 1.1 + Identity
2. Upgrade ASP.NET Core 1.1 to 2.1.0
3. Add new migration and update database.
4. Publish the project

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer "2.1.0-rtm-30799"
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2017 15.7.3)

**Comment by smitpatel** [comment]
Related #9795

**Comment by bricelam** [comment]
Works in 2.1.11, 2.2, and 3.0
