### ISSUE TITLE
HasData and updating the snapshot with the latest data.

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/efcore#12364]
If I add a column, I may want to add some seed data for that column now. But I noticed, snapshot has the hard coded data it must have gotten from `HasData`. How do I also update my initial seed?

**Comment by AndriySvyryd** [comment]
@VictorioBerra Just add the value in the `.HasData` call. The next migration will generate the corresponding update.

**Comment by VictorioBerra** [comment]
I did that and added a new migration for my new column via CLI but when I inspected snapshot the new data was not there. Maybe I did it wrong.

**Comment by ajcvickers** [comment]
@VictorioBerra Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by VictorioBerra** [comment]
I created a small project and did an initial migration, and then I added a column, modified HasData to add the additional data, and ran another migration and the snapshot was successfully updated... not sure what I must have done.
