### ISSUE TITLE
DbFunctions does not have DateDiff for DatetimeOffset

### ISSUE THREAD

**Issue by SamHuo213** [dotnet/efcore#12376]
Hi,

I am currently using EF Core 2.1 with Postgresql.  I have some Entities that use DatetimeOffset.  When I try to do a difference on two DateTimeOffset the operation is happening on client side.  I tried looking into DbFunctions for performing DateTimeOffset diff on client side but can't seem to find the methods in DbFunctions.

The following code is what I am trying to accomplish

context.Entity
 .Where(x => EF.Functions.DateDiffSeconds(x.ExpirationTime, DateTimeOffset.UtcNow))
 .ToList();

**Comment by ralmsdeveloper** [comment]
**AFAIK:** This is being supported only by SQL Server.

**Comment by SamHuo213** [comment]
Thanks for the reply.  Will this be supported in the future?  Is there any other way I can do Diffs on DateTimeOffset on the server side besides raw sql?

**Comment by B-Esmaili** [comment]
Then you better call it SQLServer.Functions not EF.Functions , and even better call the framework SqlSeverFramework not EntityFramework. That is a shame!
