### ISSUE TITLE
UWP EF Getting Started Docs are missing essential details.

### ISSUE THREAD

**Issue by Noemata** [dotnet/efcore#12370]
The documentation located here is incomplete:  https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started

The following lines need to be added in the Model csproj file in order to complete the build process.

`<PropertyGroup>
   <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
 </PropertyGroup>`

**Comment by ajcvickers** [comment]
@Noemata Docs issues should be filed on https://github.com/aspnet/EntityFramework.Docs

**Comment by ajcvickers** [comment]
Related docs issue: https://github.com/aspnet/EntityFramework.Docs/issues/748
