### ISSUE TITLE
Query filter samples don’t make sense

### ISSUE THREAD

**Issue by granthoff1107** [dotnet/efcore#12375]
The tenantId queryfilter samples make no sense

```C#
       #region Configuration
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>().Property<string>("TenantId").HasField("_tenantId");

            // Configure entity filters
            modelBuilder.Entity<Blog>().HasQueryFilter(b => EF.Property<string>(b, "TenantId") == _tenantId);
            modelBuilder.Entity<Post>().HasQueryFilter(p => !p.IsDeleted);
        }
        #endregion
```
The tenantId filter checks to see if the property which backed by _tenantId is equivalent to _tenantId, this should always return true

**Comment by ajcvickers** [comment]
@granthoff1107 TenantId is property on the entity type--in this base Blog. While it is backed by a _tenantId field, this is not the same _tenantId field that is used in the filter; the one in the filter is a member of the DbContext class. This one is captured into the query expression such that it can be changed on each context instance resulting the context filtering queries based on whatever _tenantId is set on the current instance.

**Comment by granthoff1107** [comment]
How so if you look at the blog class the tenantId is private, it doesn’t look like it’s set anywhere this is unclear from the documentation

**Comment by smitpatel** [comment]
> modelBuilder.Entity<Blog>().Property<string>("TenantId").HasField("_tenantId");

This line creates a shadow property named `TenantId` (which is being used in query filter), and assign the private field `_tenantId` to store its data. This way, while TenantId filter exists in data layer, to the consumers of the `Blog` class there is no exposure.

**Comment by granthoff1107** [comment]
@smitpatel, okay so the tenantId is assigned per say by some authorization service but who makes the assignment to the tenantId in the blog class?

**Comment by smitpatel** [comment]
@granthoff1107 - That is something user has to do. Generally it is done by overriding `SaveChanges` in derived DbContext.

Like showed in sample
https://github.com/aspnet/EntityFrameworkCore/blob/444a089a26bb3b31e783ce1b78ab7024652acdb1/samples/QueryFilters/Program.cs#L153-L170

We have https://github.com/aspnet/EntityFrameworkCore/issues/10862 making it more first class.

**Comment by granthoff1107** [comment]
The sample you provided sets the property to equal to the same property used in the DbContext, I still don’t see how this would evaluate to anything but true?

**Comment by granthoff1107** [comment]
Maybe I’m confused what tenancy is used for. I thought it was primarily used to filter values by companies, users etc...  I don’t understand why would someone one override savechanges to set a field on a value which is only backed by a property?

**Comment by mguinness** [comment]
@granthoff1107 Yep the examples are confusing all right.  The use case you suggested is covered in [Include the IsDeleted values when user is admin](https://stackoverflow.com/questions/50982252/include-the-isdeleted-values-when-user-is-admin) where the field is defined in the DbContext, not the model.

**Comment by vanillajonathan** [comment]
The comparison of the property is against `_tenantId` which is an field variable of the `DbContext` class not the entity, hence it will not always evaluate to true.

Here is a fuller example that illustrates it better:
```cs
    public class BlogContext : DbContext
    {
        private string _tenantId; // This field is what the entity is compared against

        public BlogContext(DbContextOptions options)
            : base(options)
        {
            _tenantId = "1"; // Hard-coded in this example case
        }

        public DbSet<Blog> Blogs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>().Property<string>("TenantId").HasField("_tenantId");

            modelBuilder.Entity<Blog>().HasQueryFilter(b => EF.Property<string>(b, "TenantId") == _tenantId);
        }
    }
```

The `_tenantId` field can be set in the constructor. Perhaps by dependency injection of perhaps [`IHttpContextAccessor`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.2).
Maybe something like this:
```cs
        public BlogContext(DbContextOptions options, IHttpContextAccessor httpContextAccessor)
            : base(options)
        {
            _tenantId = httpContextAccessor.HttpContext.User.FindFirstValue("TenantId");
        }
```
