### ISSUE TITLE
Subqueries may generate unneccessary joins

### ISSUE THREAD

**Issue by robertboeckel** [dotnet/efcore#12380]
Hi there,

given a simple 1:n relationship between productCategories and products the following query seems to result in an unnecessary inner join:

```c#
var query = from c in ctx.ProductCategories
            where c.ProductCategoryID == 5
            select c.Products.ToArray();

var result = query.ToArray();
```

The generated SQL queries for SQL Server are as follows:

```sql
SELECT [c].[ProductCategoryID]
      FROM [SalesLT].[ProductCategory] AS [c]
      WHERE [c].[ProductCategoryID] = 5
      ORDER BY [c].[ProductCategoryID]

SELECT [c.Products].[ProductID], [c.Products].[Name], [c.Products].[ProductCategoryID], [t].[ProductCategoryID]
      FROM [SalesLT].[Product] AS [c.Products]
      INNER JOIN (
          SELECT [c0].[ProductCategoryID]
          FROM [SalesLT].[ProductCategory] AS [c0]
          WHERE [c0].[ProductCategoryID] = 5
      ) AS [t] ON [c.Products].[ProductCategoryID] = [t].[ProductCategoryID]
      ORDER BY [t].[ProductCategoryID]
```

Ideally the subquery for products should not have to perform an inner join here, as we can put a condition on the foreign key directly. While this is a constructed example, at work we quite often have the scenario that we retrieve an entity by its primary key in the outer query and then collect and project data of related entites within subqueries. So this shows up quite often. It would be greate if EF Core could detect and optimize those scenarios.

Thanks!

Here are the C# classes of this example

```c#
    [Table("Product", Schema = "SalesLT")]
    public class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int ProductCategoryID { get; set; }
        public ProductCategory ProductCategory { get; set; }
    }

    [Table("ProductCategory", Schema = "SalesLT")]
    public class ProductCategory 
    {
        public int ProductCategoryID { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.7.3

**Comment by smitpatel** [comment]
We generate single SQL for above kind of query now.
