### ISSUE TITLE
Navigation Property Already Exists

### ISSUE THREAD

**Issue by gsayem** [dotnet/efcore#12387]
While the migration run with simple one to many relation, there are error occur with message  **The navigation property 'Blog' cannot be added to the entity type 'Post' because a property with the same name already exists on entity type 'Post'.**

```
Exception message: 
The property or navigation 'Posts' cannot be added to the entity type 'Blog' because a property or navigation with the same name already exists on entity type 'Blog'.
Stack trace:
System.InvalidOperationException: The property or navigation 'Posts' cannot be added to the entity type 'Blog' because a property or navigation with the same name already exists on entity type 'Blog'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddNavigation(PropertyIdentity propertyIdentity, ForeignKey foreignKey, Boolean pointsToPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Navigation(Nullable`1 propertyIdentity, ConfigurationSource configurationSource, Boolean pointsToPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.HasPrincipalToDependent(MemberInfo property, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.PrincipalToDependent(MemberInfo property, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasMany[TRelatedEntity](Expression`1 navigationExpression)
   at SQ.Data.Mappings.Mapping.QuestionMapping.MapEntity(ModelBuilder modelBuilder) in J:\..\..\..\src\..\Mapping\QuestionMapping.cs:line 22
   at XPTO.Data.Mappings.SQDataModel.UseSQModel(DbContextOptionsBuilder dbContextBuilder) in J:\..\..\..\src\..\XXXDataModel.cs:line 91
   at SQ.DataMigrator.App.SQDBContextFactory.CreateDbContext(String connectionString) in J:\..\..\..\src\..\XPTODBContextFactory.cs:line 17
   at SQ.DataMigrator.App.SQDBContextFactory.CreateDbContext(String[] args) in J:\..\..\..\src\..\XPTODBContextFactory.cs:line 28
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
Run the migration commad

Models:
```C#
public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public Blog Blog { get; set; }
    }
```
Mapping Classes:
BlogMapping:
```C#
modelBuilder.Entity<Blog>().ToTable("Blog");
modelBuilder.Entity<Blog>().Property(g => g.BlogId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();
modelBuilder.Entity<Blog>().HasMany(s => s.Posts).WithOne(a => a.Blog);
```
PostMapping:
```C#
modelBuilder.Entity<Post>().ToTable("Post");
modelBuilder.Entity<Post>().Property(g => g.PostId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();
//modelBuilder.Entity<Post>().HasOne(a => a.Blog).WithMany(s => s.Posts);
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" 
Operating system:  Microsoft Windows [Version 10.0.17134.112]
IDE: Visual Studio Enterprise 2017, Version: 15.7.3

**Maybe the issue already issued but I couldn't find.**

**Comment by MarS0K** [comment]
I'm pretty sure that mapping "HasMany->WithOne" is unnecessary.
BlogMapping:
```
modelBuilder.Entity<Blog>().ToTable("Blog");
modelBuilder.Entity<Blog>().Property(g => g.BlogId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();

```
PostMapping:
```
modelBuilder.Entity<Post>().ToTable("Post");
modelBuilder.Entity<Post>().Property(g => g.PostId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();
modelBuilder.Entity<Post>().HasOne(a => a.Blog).WithMany(s => s.Posts);
```

Am I wrong?

**Comment by gsayem** [comment]
It's can be use either way.

**Comment by ajcvickers** [comment]
@gsayem I have not been able to reproduce this; my test code is below. Could you either modify my code or post a runnable project/solution that reproduces what you are seeing so that we can fully investigate?

```C#
public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public Blog Blog { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().ToTable("Blog");
        modelBuilder.Entity<Blog>().Property(g => g.BlogId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();
        modelBuilder.Entity<Blog>().HasMany(s => s.Posts).WithOne(a => a.Blog);

        modelBuilder.Entity<Post>().ToTable("Post");
        modelBuilder.Entity<Post>().Property(g => g.PostId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();
        //modelBuilder.Entity<Post>().HasOne(a => a.Blog).WithMany(s => s.Posts);
    }
}
```
```PowerShell
PM> add-migration First
To undo this action, use Remove-Migration.
PM> update-database
Applying migration '20180618172132_First'.
Done.
PM> 
```

**Comment by gsayem** [comment]
Thanks @ajcvickers for your reply. I have found the problem that was for my **ITypeMappingSource** implementation and I was confused for the error message.  [Here ](https://github.com/gsayem/DatabaseMigrationEFCore/blob/51b19d00918177bab5d808e5c45a773d341f79a9/DataMigration.App/DataMigration.App/MyDataModel.cs#L65) is the link for the caused of error.

I was updating my project to Core 2.1 where I was using **ITypeMapper** that is currently **obsolete** in 2.1 and recommending to use **ITypeMappingSource**.

Though it's working fine now, I have created a project for you if you need . [Here](https://github.com/gsayem/DatabaseMigrationEFCore) is project link.

**Comment by ajcvickers** [comment]
@gsayem Can you explain a bit why you are implementing ITypeMapper/ITypeMappingSource? Are you creating a database provider?

**Comment by gsayem** [comment]
@ajcvickers, Not like the provider but if I more extend it, It'll be. 
It's actually development framework for my organization  that are/will using in all kinds of application for my organization with less effort. The previous version was .net core 1 and I have planning to move to latest core version.

**Comment by ajcvickers** [comment]
@gsayem Okay. The code looks very strange to me.

**Comment by gsayem** [comment]
@ajcvickers , well you are looking at sample code in a single a assembly that is only create for you from the original code.

**Comment by smitpatel** [comment]
@gsayem - The core of the issue is incomplete ConventionSet. You create ConventionSet based on core but you are missing Relational/SqlServer conventions, hence you are using incorrect type mapper too. These are EF internal services. You can implement one of them and replace in service provider but create a service correctly without using service provider is not easy task.
Look at following code to get the convention set builder.

https://github.com/aspnet/EntityFrameworkCore/blob/7de3ebb8f8fd18167fa9c701cea168d6029ed2b6/src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs#L88-L102

Note: above code is internal API and can be broken in future releases of EF Core. You either call the method directly or copy over the code.

**Comment by mmahditalachi** [comment]
For me it occur when I set blog to IsRequired in configuration and also use that in OnModelCreating to create y relation 


    `public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public List<Post> Posts { get; set; }
    }
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Blog Blog { get; set; }
    }`

```
 public class PostConfiguration : IEntityTypeConfiguration<Post>
    {
        public void Configure(EntityTypeBuilder<Post> builder)
        {
               //dont use IsRequired because it's already FK and it can not to be NULL
               builder.Property(x => x.Blog )
                .IsRequired();
        }
  }
```

```
`modelBuilder.Entity<Blog>().ToTable("Blog");
modelBuilder.Entity<Blog>().Property(g => g.BlogId).ValueGeneratedOnAdd().UseSqlServerIdentityColumn();
modelBuilder.Entity<Blog>().HasMany(s => s.Posts).WithOne(a => a.Blog);`
```

check this link 
[https://entityframeworkcore.com/knowledge-base/51919192/entity-framework-core-navigation-properties-error](url)

**Comment by HalilMertDeveli** [comment]
it worked for me
