### ISSUE TITLE
EFCore 2.1 lazy-loaded proxies do not load for new entity instances.

### ISSUE THREAD

**Issue by Metritutus** [dotnet/efcore#12389]
When I create a new instance of an entity that has properties that link to another entity, those proxies do not get loaded after the new entity starts getting tracked when I try to access them.  Accessing the properties of existing entities works as expected, so I know the lazy-loading is working at least in that regard.

The SQL scripts and application code are below.

#### SQL scripts
```SQL
CREATE DATABASE EFCoreLazyLoadingTest
GO

USE EFCoreLazyLoadingTest

CREATE TABLE [TestTable1]
(
    [Id]        INTEGER IDENTITY    NOT NULL    PRIMARY KEY,
    [Value]     VARCHAR(MAX)        NOT NULL,
)
GO

CREATE TABLE [TestTable2]
(
    [Id]            INTEGER IDENTITY    NOT NULL    PRIMARY KEY,
    [TestTable1Id]  INTEGER             NOT NULL    FOREIGN KEY REFERENCES [TestTable1]([Id]),
    [Value]         VARCHAR(MAX)        NOT NULL,
)
GO

INSERT INTO TestTable1([Value])
VALUES
('TestTable1Value1'),
('TestTable1Value2')
```

#### Application code
```c#
static void Main(string[] args)
{
    var context = new EFCoreLazyLoadingTestContext();

    var tr = new TestTable2() { TestTable1Id=1, Value = "Record 1" };

    context.TestTable2.Add(tr);
    context.SaveChanges();

    Console.WriteLine(tr.TestTable1.Value); //NullReferenceException.

    Console.Write("Press any key to continue . . . ");
    Console.ReadKey();
}
```

In the model for `TestTable1` I have `public virtual ICollection<TestTable2> TestTable2 { get; set; }`.  In the model for `TestTable2` I have `public virtual TestTable1 TestTable1 { get; set; }`.  In `EFCoreLazyLoadingTestContext` I have the call to ` .UseLazyLoadingProxies()` above the call to `UseSqlServer()`.  All the rest is as it was generated by the following scaffold command:

`Scaffold-DbContext "Server=DbServer;Database=EFCoreLazyLoadingTest;User ID=<REMOVED>;Password=<REMOVED>;" Microsoft.EntityFrameworkCore.SqlServer -Force -OutputDir Models`

Is there something I'm missing here that I should be doing?  Or is this a bug or a feature of the lazy-loading functionality that has not yet been implemented?

### Further technical details
EF Core version: netcoreapp2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.1
```

**Comment by ajcvickers** [comment]
@Metritutus Lazy-loading proxies work by creating a proxy type that inherits from your entity type. This type then overrides navigation properties to perform lazy-loading. In the code above, the entity instance is created by calling `new`, which means that it is not an instance of the proxy type and hence does not have lazy-loading behaviors. This situation can be handled in two ways:
* Build lazy-loading behavior into the entity type itself, as described in the docs here: https://docs.microsoft.com/en-us/ef/core/querying/related-data
* Use `context.CreateProxy<TestTable2>()` to create the entity instance to force it to be a proxy.

**Comment by Metritutus** [comment]
This makes a lot of sense and makes me feel a bit dumb for not thinking properly through how the lazy-loaded proxies were actually working (using derived classes).  It would be useful if that `CreateProxy()` method was mentioned on the related-data page you linked to though (unless we're not normally supposed to use it?).

Also this does lead to my next question:  Is there any convenient way to create a proxy instance from an existing instance of the base model?  ie an equivalent of doing something like `context.CreateProxy<TestTable2>(testTable2Instance);`, where there's a constructor in the model that takes an instance of itself.

**Comment by ajcvickers** [comment]
@Metritutus I created a docs issue for CreateProxy: https://github.com/aspnet/EntityFramework.Docs/issues/780

There isn't a method for creating a proxy instance from a non-proxy instance, partly because it can cause issues if not uses very carefully. Specifically, if the original instance is already tracked, then it would need to be detached before the proxy instance can be used, Further, if the original instance is part of a graph with references to other instances, then these would need to be moved to point to the new instance. And then the original instance should stop being used, which may not be obvious if it is being held onto by another part of the application. However, assuming all that is under control, then it can be done this way:

```C#
var blog = new Blog {  Id = 7, Title = "Cats and their muses" };
var blogProxy = context.CreateProxy<Blog>();
context.Entry(blogProxy).CurrentValues.SetValues(blog);
```
This creates a new proxy instance, then uses methods designed to work mainly with DTOs to set property values from the original instance onto the new one.

**Comment by Metritutus** [comment]
The model instance is in fact being created from a DTO (whose property names differ slightly from the model's).  I was also previously unaware of this `SetValues()` functionality!  It looks like it is briefly covered in the Disconnected Entities article.

Thanks very much for your help and in highlighting these pieces of functionality!
