### ISSUE TITLE
'Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.3' has a package type 'DotnetCliTool' that is not supported by project

### ISSUE THREAD

**Issue by kashif862** [dotnet/efcore#12388]
NU1605: Detected package downgrade: Microsoft.NETCore.App from 2.0.7 to 2.0.0. Reference the package directly from the project to select a different version. 
coremvcdbfirstapp -> Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.3 -> Microsoft.NETCore.App (>= 2.0.7) 
coremvcdbfirstapp -> Microsoft.NETCore.App (>= 2.0.0)
Package 'Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.3' has a package type 'DotnetCliTool' that is not supported by project 'coremvcdbfirstapp'.

**Comment by smitpatel** [comment]
Can you share your project file?

**Comment by ajcvickers** [comment]
@kashif862 For 2.1, that package no longer needs to be installed. For pre-2.1, it must be installed in a special way through editing of the csproj file. See docs here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
