### ISSUE TITLE
[Question] Best practice WPF Application with EFC

### ISSUE THREAD

**Issue by Int32Overflow** [dotnet/efcore#12396]
I am facing the task of implementing a large database application in WPF. I have already worked with small WPF database applications.
Unfortunately, I haven't found an example of large WPF EFC applications.

 **A brief summary of my task:**
- WPF application with MVVM
- Data with Entity Framework Core 2.1 
- IoC container with Repository pattern
- Data editors for master data. Simultaneous processing of data in split screens => No global DbContext possible
  - Add data
  - Edit data
     - Save changes
     - Discard changes
  - Delete data

## Example MockUp of an data editor

![grafik](https://user-images.githubusercontent.com/20139038/41546981-539f4d98-731f-11e8-829d-9a6e658a611f.png)

I start editing "Item 1", then I edit "Item 2" and save "Item 2". I now discard the changes of "Item 1".

How would you design this application?

**Comment by ajcvickers** [comment]
Moved to docs: https://github.com/aspnet/EntityFramework.Docs/issues/778
