### ISSUE TITLE
System.Reflection.Emit is delisted, affecting Castle.Core and the Proxies package

### ISSUE THREAD

**Issue by jbogard** [dotnet/efcore#12393]
The System.Reflection.Emit and System.Reflection.Emit.Lightweight packages have been delisted from NuGet, see discussion here:

https://github.com/dotnet/corefx/issues/29365

The EFCore.Proxies package references Castle.Core, which although targets `netstandard2.0`, may not target that framework anymore. See their discussion here: 

https://github.com/castleproject/Core/issues/374

Just a heads up, this will likely mean the Proxies package in the future can't target `netstandard2.0`, since Reflection.Emit isn't actually in the .NET Standard. You'll likely need to explicitly target whatever Castle.Core decides to target.

**Comment by jbogard** [comment]
Also, Remotion.Linq is `netstandard1.0`, so this means the core package is affected to. I've opened an issue with Remotion.Linq to directly support `netstandard2.0`:

https://www.re-motion.org/jira/browse/RMLNQ-122

**Comment by divega** [comment]
Thanks @jbogard for raising this here. There has been in fact a lot of discussion around this, and the latest decision was to [re-list the System.Reflection.Emit and System.Reflection.Emit.Lightweight pakages](https://github.com/dotnet/corefx/issues/29365#issuecomment-398130364).

It would still be nice and cleaner if Relinq added a .NET Standard 2.0 target (see https://github.com/aspnet/EntityFrameworkCore/issues/10968 for example), but we don't believe that our usage of Relinq is broken by the indirect dependency on System.Reflection.Emit. At least we haven't seen reports of this. 

Regarding Microsoft.EntityFrameworkCore.Proxies, it will currently only work on the .NET implementations supported by System.Reflection.Emit. That is, the same caveats that apply to Sytem.Reflection.Emit (per https://github.com/dotnet/corefx/issues/29365#issuecomment-398130364), also apply to any packages that depend on it. 

If in the future System.Reflection.Emit is supported beyond .NET Framework and .NET Core (that is, the [issue with TypeInfo coupling](https://github.com/dotnet/corefx/issues/29365#issuecomment-385093422) is solved) then likely you will be able to start using Microsoft.EntityFrameworkCore.Proxies in other implementations as well. 

That said, proxies are not going to ever work on .NET implementations that only support ahead of time code generation like UWP with .NET Native or Xamarin on iOS. In those implementation you can perform [lazy loading without proxies](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading-without-proxies ) using the building blocks we provide.

It seems to me that the clearest thing we need to follow up on is to figure out how to communicate that a package like [https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Proxies/](Microsoft.EntityFrameworkCore.Proxies), which claims to target .NET Standard 2.0, may in fact not work on all .NET implementations that implement .NST Standard 2.0. That is part of a larger ongoing discussion.

cc @davidfowl @terrajobst
