### ISSUE TITLE
Backing fields are not used as per convention when property is a navigational property

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#12401]
EFCore 2.1.0. See: https://github.com/aspnet/EntityFramework.Docs/issues/775

EF Core should use the backing field as per convention with the docs here: https://docs.microsoft.com/en-us/ef/core/modeling/backing-field

Currently it is not, unless `.Metadata.DependentToPrincipal.SetPropertyAccessMode(PropertyAccessMode.Field);`
is specified. 

DispatchItem.cs:

```C#
    public class DispatchItem {
        private PurchaseOrderItem _purchaseOrderItem;

        public Guid Id { get; set; }
        public PurchaseOrderItem PurchaseOrderItem {
            get => _purchaseOrderItem;
            set {
                throw new Exception("Shouldn't come here.");
            }
        }
        public Guid? PurchaseOrderItemId { get; set; }
    }
}
```

DbContext.cs:

```C#
    public class MyDbContext : DbContext {

        public MyDbContext(DbContextOptions options)
            : base(options) {
        }

        public DbSet<DispatchItem> DispatchItems { get; set; }
        public DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.HasPostgresExtension("uuid-ossp");

            modelBuilder.Entity<DispatchItem>().ToTable("dispatch_item").HasKey(di => di.Id);
            modelBuilder.Entity<DispatchItem>().Property(di => di.Id).HasColumnName("id");
            modelBuilder.Entity<DispatchItem>().Property(di => di.PurchaseOrderItemId).HasColumnName("purchase_order_item_id");
            modelBuilder.Entity<DispatchItem>().HasOne(di => di.PurchaseOrderItem).WithMany(poi => poi.DispatchItems).HasForeignKey(di => di.PurchaseOrderItemId);
                //.Metadata.DependentToPrincipal.SetPropertyAccessMode(PropertyAccessMode.Field);

            modelBuilder.Entity<PurchaseOrderItem>().ToTable("purchase_order_item").HasKey(poi => poi.Id);
            modelBuilder.Entity<PurchaseOrderItem>().Property(poi => poi.Id).HasColumnName("id");
        }
    }
```

Program.cs:

```C#
 var items = context.DispatchItems
                .Where(di => di.Id == Guid.Parse("c6185eb9-1644-4a8f-b8fd-ff98e45f4228"))
                .Include(di => di.PurchaseOrderItem)
                .SingleOrDefaultAsync().Result;
```

**I have attached a sample project as a minimal verifiable example to reproduce this problem.**

[EFBugDemo1.zip](https://github.com/aspnet/EntityFrameworkCore/files/2112665/EFBugDemo1.zip)

To repro with the project:
- Set up a PostgreSQL server with no database.
- Set the connection string in Program.Main() to the PostgreSQL server.
- Set the connection string in DesignTimeDbContextFactory.CreateDbContext() to the PostgreSQL server.
- Run the migrations and database update (Create Database.ps1)
- Run the app
- The setter is used even though it shoudn't.

If you uncomment line 22 of DbContext.cs, the setter is not used.

**Comment by ajcvickers** [comment]
@orobert91 With the additional detail provided here I re-opened the docs issue. Even though the docs say, "EF will write directly to that field when materializing entity instances from the database (rather than using the property setter). If EF needs to read or write the value at other times, it will use the property if possible." The first sentence does not apply to navigations because they are technically never set during materialization, so the second sentence applies which means the property is used. This does need clarifying in the docs.
