### ISSUE TITLE
Exploratory Testing: Commands

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#1242]
Think of this as the non-framework pieces surrounding Migrations. Here are a few things to look at.
- NuGet/DNX commands
  - "Smart" defaults that you can override
  - Tab-completion
  - Console logging
- Design-time execution
  - Assembly resolution
  - Relative paths
- Writing files
- VS integration
  - Opening documents
  - Setting window focus

**Comment by bricelam** [comment]
We should also test to make sure it plays well with TFS's read-only files.

**Comment by natemcmaster** [comment]
@bricelam Nuget no longer allows running a *.ps1 file on installation, correct? EF used to open a tab in VS.

**Comment by bricelam** [comment]
For `project.json` projects, it's not supported. It will still work for `packages.config` packages. The meta-package EntityFramework had an HTML README, but we got rid of that package. The Commands package has one to point users to `Get-Help about_EntityFramework`.
