### ISSUE TITLE
OriginalValues of an entity in Added state are equal to CurrentValues

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#12428]
I am adding an entity using `DbSet.Add`.
I am using `ChangeTrackingStrategy.ChangingAndChangedNotificationsWithOriginalValues`.

As far as I can tell, OriginalValues of Added entities are always equal to CurrentValues. The OriginalValues even change when I set a property value.

I expected the OriginalValues to either be equal to the property values at the time I called `DbSet.Add` or to throw an Exception.

**Comment by ajcvickers** [comment]
@Wain123 Asking for original values of an Added entity doesn't make much sense, but throwing requires conditional logic to be used to avoid asking for them on Added object, while returning the current values allows Added objects to often be treated the same as entities in other states.
