### ISSUE TITLE
Join with client side collections

### ISSUE THREAD

**Issue by xumix** [dotnet/efcore#12431]
It would be great to use .Contains and .Join as translated statements like it is do with simple ```.Contains(e.Id)```

For example:
```c#
var newKeys = lc.lotContract.Select(l => new { l.IdLot, l.IdContract }).ToHashSet();
var existingKeys = (from l in importDb.Set<lotContract>()
                              join k in newKeys on new { l.IdLot, l.IdContract } equals new { k.IdLot, k.IdContract }
                              select new { l.IdLot, l.IdContract })
                        .ToHashSet();
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: (e.g. Visual Studio 2017 15.7)

**Comment by smitpatel** [comment]
#17031

**Comment by roji** [comment]
Duplicate of #17031
