### ISSUE TITLE
using Microsoft.EntityFrameworkCore.Storage.ValueConversion does not exist everytime I add migration

### ISSUE THREAD

**Issue by punkouter2021** [dotnet/efcore#12442]
Describe what is not working as expected.

Whenever I add-migration I get two errors and always have to remove this statement

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'ValueConversion' does not exist in the namespace 'Microsoft.EntityFrameworkCore.Storage' (are you missing an assembly reference?)	Aamc.Ret.Data	C:\Users\MHerb\Downloads\AAMC RET\Aamc.Ret\Aamc.Ret.Data\Migrations\20180621135014_FixUserProgram.Designer.cs	8	Active

EF Core 2.1

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@punkouter2018 You likely have a mix of incompatible package versions. See the discussion here: #11704.

If you are still seeing this after updating either SDK (for ASP.NET Core apps) or all EF package versions (for other apps) then please post a project/solution that exhibits the behavior you are seeing.
