### ISSUE TITLE
Override (Id) property type in Identity (IdentityRoleClaim) Model

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#12458]
### Further technical details
EF Core version: 2.1.1

I have read [this](https://github.com/aspnet/EntityFrameworkCore/issues/8448) and [this](https://github.com/aspnet/Identity/issues/780) issues… But I cannot find a solution…

**I find no documentation about this subject**.

This EF Core **behavior I get, seems, to me, _unexpected_**; and what @ajcvickers wrote in issue 780 is too cryptic (for which entities, where, how?…)

> In a nutshell, you need to also redefine the relationships/FKs to also use a different type of key.

### Steps to reproduce
Using these following classes:

#### `ApplicationIdentityDbContext`

```
    public class ApplicationIdentityDbContext : IdentityDbContext<ApplicationIdentityUser<Guid>, ApplicationIdentityRole<Guid>, Guid,
        IdentityUserClaim<Guid>, ApplicationUserRole<Guid>, IdentityUserLogin<Guid>,
        ApplicationIdentityRoleClaim<Guid>, IdentityUserToken<Guid>>
    {
        public ApplicationIdentityDbContext(DbContextOptions<ApplicationIdentityDbContext> options):base(options){}

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            //AspNetRoleClaims
            modelBuilder.Entity<ApplicationIdentityRoleClaim<Guid>>(entity => {
                entity.ToTable("AspNetRoleClaims");
            }); 

            // AspNetRoleClaimsRoles Table
            modelBuilder.Entity<ApplicationRoleClaimRole<Guid>>(entity =>{
                entity.ToTable("AspNetRoleClaimsRoles");
                entity.HasKey(ur => new { ur.RoleId, ur.RoleClaimId });
            });

            modelBuilder.Entity<ApplicationRoleClaimRole<Guid>>()
                .HasOne(ro => ro.Role)
                .WithMany(rc => rc.RoleClaims)
                .HasForeignKey(ro => ro.RoleId);

            modelBuilder.Entity<ApplicationRoleClaimRole<Guid>>()
                .HasOne(rc => rc.RoleClaim)
                .WithMany(ro => ro.Roles)
                .HasForeignKey(rc => rc.RoleClaimId);
            

            // AspNetUserRoles Table
            modelBuilder.Entity<ApplicationUserRole<Guid>>()
                .ToTable("AspNetUserRoles")
                .HasKey(ur => new { ur.RoleId, ur.UserId });
            modelBuilder.Entity<ApplicationUserRole<Guid>>()
                .HasOne(ur => ur.Role)
                .WithMany(ur => ur.Users)
                .HasForeignKey(ur => ur.RoleId);

            modelBuilder.Entity<ApplicationUserRole<Guid>>()
                .HasOne(ur => ur.User)
                .WithMany(ur => ur.Roles)
                .HasForeignKey(ur => ur.UserId);
        }
    }
}
```
#### `ApplicationIdentityRoleClaim<TKey>`
```
    public class ApplicationIdentityRoleClaim<TKey> : IdentityRoleClaim<TKey> where TKey : IEquatable<TKey>
    {
        /// <summary>
        /// Gets or sets the identifier for this role claim.
        /// </summary>
        new public TKey Id { get; set; }

        /// <summary>
        /// Navigation property for the roles this user belongs to.
        /// </summary>
        public virtual ICollection<ApplicationRoleClaimRole<TKey>> Roles { get; set; }
```

#### `ApplicationUserRole<TKey>`

```
    public class ApplicationUserRole<TKey> : IdentityUserRole<TKey> where TKey : IEquatable<TKey>
    {
        /// <summary>
        /// Navigation property for the users this role belongs to.
        /// </summary>
        public ApplicationIdentityUser<TKey> User { get; set; }

        /// <summary>
        /// Navigation property for the roles this user belongs to.
        /// </summary>
        public ApplicationIdentityRole<TKey> Role { get ; set; }

    }

```

#### `ApplicationRoleClaimRole<TKey>`

```
    public class ApplicationRoleClaimRole<TKey> where TKey : IEquatable<TKey>
    {
        /// <summary>
        /// Gets or sets the primary key of the role that is linked to the claim.
        /// </summary>
        public virtual TKey RoleId { get; set; }
        
        /// <summary>
        /// Navigation property for the Roles this RoleClaim belongs to.
        /// </summary>
        public ApplicationIdentityRole<TKey> Role { get ; set; }

        /// <summary>
        /// Gets or sets the primary key of the claim that is linked to a role.
        /// </summary>
        public virtual TKey RoleClaimId { get; set; }

        /// <summary>
        /// Navigation property for the RoleClaims this Role belongs to.
        /// </summary>
        public ApplicationIdentityRoleClaim<TKey> RoleClaim { get; set; }

```
#### `ApplicationIdentityRole<TKey>`
```
    public class ApplicationIdentityRole<TKey> : IdentityRole<TKey> where TKey : IEquatable<TKey>
    {
        /// <summary>
        /// Navigation property for the roles this user belongs to.
        /// </summary>
        public virtual ICollection<ApplicationUserRole<TKey>> Users { get; set; }

        /// <summary>
        /// Navigation property for the claims this user possesses.
        /// </summary>
        public virtual ICollection<ApplicationRoleClaimRole<TKey>> RoleClaims { get; set;}

        
        public ApplicationIdentityRole()
        {
        }

        public ApplicationIdentityRole(string roleName) : this()
        {
            Name = roleName;
        }
    }
```
#### `ApplicationIdentityUser<TKey>`
```
    public class ApplicationIdentityUser<TKey> : IdentityUser<TKey> where TKey : IEquatable<TKey>
    {

        /// <summary>
        /// Navigation property for the roles this user belongs to.
        /// </summary>
        public virtual ICollection<ApplicationUserRole<TKey>> Roles { get; set; }
    }
```

I get, when trying `dotnet ef migrations add Initial --context ApplicationIdentityDbContext -v`, this:

> The specified field '<Id>k__BackingField' of type 'Guid' cannot be used for the property 'ApplicationIdentityRoleClaim<Guid>.Id' of type 'int'. Only backing fields of types that areassignable from the property type can be used.
### Questions
1. **How and Why the BackingField has the good type 'Guid', while the Property does not???**—I find this very strange…
2. Why some classes have their `Id` as "TKey", while other have int type specified?
3. ~~Is `'<Id>k__BackingField'` the real name of the BackingField? If yes, why it does not follow the [Backing Fields naming convention](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field#conventions)?~~ Ok, find that is the IL name…
4. Why there is no documentation about how to deal with such case (Override property type in Identity Model)???

**Comment by ckams** [comment]
Cannot find the logic behind…

if I try this `ApplicationIdentityDbContext` type signature:

#### `ApplicationIdentityDbContext`

`public class ApplicationIdentityDbContext : IdentityDbContext<ApplicationIdentityUser<Guid>, ApplicationIdentityRole<Guid>, Guid/>`

I get this "expected" message:

> CLR property 'Id' cannot be added to entity type `'IdentityRoleClaim<Guid>'` because it is declared on the CLR type `'ApplicationIdentityRoleClaim<Guid>'`.

But if I keep this `ApplicationIdentityDbContext` type signature—or keep the first, as in my first comment—, while modifying `ApplicationIdentityRoleClaim<TKey> as bellow:
#### `ApplicationIdentityRoleClaim<TKey>`

`        new public TKey Id { get {return (TKey) Id;}  set { Id = (TKey) value; }}`

I get this unexpected message:
>The specified field `'<Id>k__BackingField'` of type 'int' cannot be used for the property `'ApplicationIdentityRoleClaim<Guid>.Id'` of type 'Guid'. Only backing fields of types that are assignable from the property type can be used.

While I would have expect this message at first time (without specifying `(TKey)`)… I do not understand why
1. I get this behavior with the "wrong" type signature for `ApplicationIdentityDbContext`…
2. this time, the Backing Field has the wrong type, whereas the Property has the good type…

**Comment by ajcvickers** [comment]
@ckams I just finished a new doc on [customizing the Identity model](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1). Hopefully this will help make things clearer in this area.

To address your specific question, I don't believe it is reasonably possible to change the key type for  IdentityRoleClaim. The manager APIs rely on it being defined as an `int`.

**Comment by ajcvickers** [comment]
@ckams Also, future issues in this area should be posed to the [Identity repo](https://github.com/aspnet/Identity/issues).

**Comment by ckams** [comment]
@ajcvickers 

Thanks, but some questions remain unanswered (all about the core issue…):

- What did you mean in the issue [8448](https://github.com/aspnet/EntityFrameworkCore/issues/8448#issuecomment-301116404)?
 > In a nutshell, you need to also redefine the relationships/FKs to also use a different type of key.

Your documentation provides nothing about this point…

Where can I find, in this provided link, the answer to this question (related to the issue 8448)?
- **How to understand the BackingField behaviour?**

**Comment by ajcvickers** [comment]
@ckams What I meant in #8448 is that the primary (or alternate) key and the foreign key must have compatible types. For example:
```C#
public class Blog
{
    public int Id { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public int BlogId { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Blog>()
            .HasMany<Post>()
            .WithOne()
            .HasForeignKey(e => e.BlogId);
    }
}
```
Now if I want to change the type of the PK, then I must also change the type of the FK:
```C#
public class Blog
{
    public Guid Id { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public Guid BlogId { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Blog>()
            .HasMany<Post>()
            .WithOne()
            .HasForeignKey(e => e.BlogId);
    }
}
```
The document doesn't show this explicitly, since for the key properties that are valid to change in the Identity model all use the TKey generic for both primary and foreign key properties, so this happens automatically. In the case of the int key on IdentityRoleClaim, this should not be changed, since it is used by the manager APIs.

With regard to the backing field behavior, I have no idea how you got into that state--I have not been able to reproduce this. If you think this is a bug, then please file a new issue together with a runnable project/solution or complete code listing that demonstrates what you are seeing so that we can investigate.

**Comment by ckams** [comment]
@ajcvickers 
Did you try the same configuration than me? I mean using **many-to-many relationship** between `ApplicationIdentityRole<TKey>` and `ApplicationIdentityRoleClaim<TKey>`?

Or did you only try the configuration like the above post?

Anyway, I will open a new issue.
