### ISSUE TITLE
Stop configuring lazy-loading for properties that will always be eager-loaded

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#12462]
For example, for owner to owned navigation properties in aggregates.

See also https://github.com/aspnet/EntityFrameworkCore/issues/10787#issuecomment-399989313

**Comment by lajones** [comment]
Notes from discussion with @ajcvickers and @smitpatel:

Define "properties that will always be eager loaded" as an `INavigation` (either reference or collection) which:
- has `IsEagerLoaded == true`
- has `GetTargetType().IsOwned == true`

In that case set up such that a) we do not need the `virtual` keyword, and b) check that attempting to lazy-load should be a no-op as we should already have eager-loaded.

**Comment by AndriySvyryd** [comment]
> - has IsEagerLoaded == true

This isn't safe as [we'll add an opt-out](https://github.com/dotnet/efcore/issues/2953#issuecomment-555272371)

**Comment by lajones** [comment]
@AndriySvyryd What would be safe?

**Comment by AndriySvyryd** [comment]
@lajones 
* `navigation.ForeignKey.IsOwnership == true` for tracked enitites
* `navigation.ForeignKey.IsOwnership == true && navigation.IsOnDependent == false` for not tracked

**Comment by lajones** [comment]
We don't know whether the entity is being tracked at model validation time (which is when the current error is thrown). After more discussion with @AndriySvyryd we'll do something like:

```C#
if (navigation.ForeignKey.IsOwnership)
{
    if (navigation.IsOnDependent)
    {
        // issue a warning saying either make this virtual or this will only work if you
        // include the owner yourself i.e. do your own eager loading. Do not throw.
    }
    else
    {
        // do not throw - this will be eager loaded
    }
}
else
{
    // throw as normal
}
```
