### ISSUE TITLE
Full Text Search in EF Core 2.1

### ISSUE THREAD

**Issue by chobo2** [dotnet/efcore#12461]
Hi

I seen so many posts here about Full Text Search, it is a bit hard to know the state of this feature. 

Is it fully supported by EF Core 2.1? If show, anyone have examples?

If it is not fully supported by EF Core 2.1.  Can anyone show me a tutorial on how to implement something that will make it work EF Core.

Thanks

Edit I found this https://github.com/aspnet/EntityFrameworkCore/issues/1590

but I am confused on what the different is between full text and this free text. Nor does it say how to actually use it.  Is it a linq function? Do I need to create an index?

**Comment by divega** [comment]
@chobo2 in EF Core 2.1 we had a contribution that added support for translating EF.Functions.FreeText() to the FREETEXT function. There is now a PR being out that adds also support for CONTAINS in a similar way. We don't have first-class support for creating full-text indexes, but you can do that by dropping down to SQL in migrations.

Note for triage: I added Full Text Search to the list of workarounds for SQL Server features covered by https://github.com/aspnet/EntityFramework.Docs/issues/685.

**Comment by chobo2** [comment]
@divega  - I am new to the world of EF Core,so how do I make a migration script you talk about. I only done it by using the "add-migration" commands that goes through the code and creates the migration that way. Not by some custom sql script I made.

I am still looking into the freetext but still confused on what the difference is between it and Contains and how it is actually used in the C# code.

Is there any tutorial that is live today that I can reference or do you have a snippet of code that I can see how to use this freetext?

Thanks

**Comment by mguinness** [comment]
@chobo2 You need to use [MigrationBuilder.Sql()](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#using-migrationbuildersql) to manually create your index using DDL.  Your [question](https://stackoverflow.com/questions/51047514/how-to-use-freetext-in-ef-core-2-1) in SO has an answer providing the usage.  See [Query with Full-Text Search](https://docs.microsoft.com/en-us/sql/relational-databases/search/query-with-full-text-search) for examples of FREETEXT.
