### ISSUE TITLE
Seeding data with .HasData()

### ISSUE THREAD

**Issue by jdlm91** [dotnet/efcore#12464]
Hi,

I went through the issues related to EFCore 2.1 and data seeding, but was not able to solve my issue.

Not sure if this is the expected behavior of using EFCore's `.HasData()` method but this is what I am currently experiencing.

I have the two basic classes created from the EFCore tutorial on Microsoft's site, namely Blog and Post.

Blog.cs
```C#
public int BlogId { get; set; }
public string Url { get; set; }
public List<Post> Posts { get; set; } = new List<Post>();
```
Post.cs
```C#
public int PostId { get; set; }
public string Title { get; set; }
public string Content { get; set; }

public int BlogId { get; set; }
public Blog Blog { get; set; }
```

AppDbContext.cs

```C#
public AppDbContext(DbContextOptions options) : base(options)
{            
}

public DbSet<Blog> Blogs { get; set; }
public DbSet<Post> Posts { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
     modelBuilder.Entity<Blog>().HasData
     (
         new Blog
         {
             BlogId = 1,
             Url = "www.sample.com"
         }
     );

     modelBuilder.Entity<Post>().HasData
     (            
          new {BlogId = 1, PostId = 1, Title = "First post", Content = "Test 1"},
          new {BlogId = 1, PostId = 2, Title = "Second post", Content = "Test 2"}
     );
}
```
Using `dotnet ef migrations add ...` and `dotnet ef database update` commands work without any errors and the database gets seeded.

However, when I select the blog to be displayed through the controller I simply get back an empty array of posts.

<img width="965" alt="blogs" src="https://user-images.githubusercontent.com/40579019/41872228-d436ef3c-78de-11e8-88aa-c69a70788fa7.png">

Adding the post data directly into the blog data sometimes throws an error and sometimes it does not, but the outcome is still the same as the image above.

In my Blog.cs file when I change my `public List<Post> Posts { get; set; } = new List<Post>() ` to `public List<Post> Posts { get; set; } ` it would just provide a null value instead on the empty array.

Am I missing something in my code to get this to work properly?

**Comment by kjbetz** [comment]
What's your API controller look like?

```c#
_db.Blog
    .Where(b => b.Id == 1)
    .Include(b => b.Posts)
    .SingleOrDefaultAsync()
```

I think that should work.

**Comment by kjbetz** [comment]
Add the json options to your `Startup.cs`

```c#
    services.AddMvc()
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
        .AddJsonOptions(options =>
        {
            options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
        });
```

Here's a repro: https://github.com/kjbetz/BlogPosts

**Comment by Bud91** [comment]
@kjbetz Thanks a lot, that worked :)

**Comment by Bud91** [comment]
Sorry about that, new to GitHub and forgot to close the issue with  the comment itself.
