### ISSUE TITLE
Low-level state changes

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1247]
If you call Remove for an Added entity its state gets set to Detached. See #251 and #265. However, the same is true for setting the entity's state to Deleted--it actually becomes Detached. Should setting the state honor the state passed, while the Remove method does something different? Or is it better to be consistent, in which case maybe the SetState method should be called ChangeState and documented appropriately? Also, see #1246 since this could result in setting the state to Unchanged but getting Modified.

**Comment by rowanmiller** [comment]
Happy with the behavior we have
