### ISSUE TITLE
Migration rollback on exception?

### ISSUE THREAD

**Issue by jceddy** [dotnet/efcore#12479]
I just have a question and not sure where else to ask it. If an exception occurs while a migration is being applied, is the entire migration rolled back? Or does it just stop processing and throw the exception, or even continue processing the rest of the migration?

**Comment by ajcvickers** [comment]
@jceddy If the migration is being executed from the EF commands (PMC or dotnet CLI) then the migration is executed in a transaction, which is rolled back if an error occurs.
