### ISSUE TITLE
Shadow Properties and HasData

### ISSUE THREAD

**Issue by MIKE-R-PALMER** [dotnet/efcore#12496]
How do I use HasData with a shadow property.  I have defined my shadow property Deleted as a bool, if I set this to bool? and assign HasDefaultValue(false), my HasData works and sets the Deleted value to null (not what I want).  If I leave it as bool my HasData fails saying that the value cannot be null. When I look at the scripts, the HasDefaultValue(false) is being ignored for HasData.

EF Core 2.1.1 and AspNetCore 2.1.1

**Comment by ajcvickers** [comment]
@MIKE-R-PALMER To set shadow properties you can use an anonymous type, as shown here: https://github.com/aspnet/EntityFrameworkCore/issues/11083

**Comment by MIKE-R-PALMER** [comment]
That worked a treat, thank you for taking the time to assist me, very much appreciated.

**Comment by ajcvickers** [comment]
Closing this as question, but also filed #12525
