### ISSUE TITLE
Duplicate column names in Select when using table splitting

### ISSUE THREAD

**Issue by JakobFerdinand** [dotnet/efcore#12491]
When querying tables with Owned Entities Ef Core 2.1.1 creates a SQL statement that asks twice for Id column.

```csharp
public class Name
{
    public string First { get; set; }
    public string Last { get; set; }
}
public class Author
{
    public int Id { get; set; }
    public Name Name { get; set; }
    public string Description { get; set; }
}
```

`context.Authors.ToList()` creates this SQL query:
```sql
SELECT [a].[Id], [a].[Id], [a].[Firstname], [a].[Lastname], [a].[Description]
FROM [Authors] AS [a]
```
with two times `[a].[Id]`

There´s a [Sample Project](https://github.com/rzlsoftware/EfCoreSqlQueryWithOwnedEntity).

When you just use the sql to query the database it´s no problem, but when you reuse the sql for example for batch update like [ZZZ Projects](https://github.com/zzzprojects) does in there [create command functionality](https://github.com/zzzprojects/EntityFramework-Plus/blob/29acd6b1eea9191727d915bc66c384f29f43d03a/src/shared/Z.EF.Plus._Core.Shared/EFCore/IQueryable%60/CreateCommand.cs#L271) this makes huge problems.  

Example:
```sql
UPDATE A 
SET A.[Description] = 'Some very important information'
FROM [Authors] AS A
INNER JOIN ( SELECT [a].[Id], [a].[Description], [a].[Id], [a].[Firstname], [a].[Lastname]
FROM [Authors] AS [a]
WHERE CAST(LEN([a].[Firstname]) AS int) < 6
           ) AS B ON A.[Id] = B.[Id]
```

Exception Message: `The column 'Id' was specified multiple times for 'B'.`

### Further technical details
EF Core version:  2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 1803
IDE: Visual Studio 2017 15.7.4

**Comment by JakobFerdinand** [comment]
#### Same problem when also using TPH

```csharp
public class Name
{
    public string First { get; set; }
    public string Last { get; set; }
}
public abstract class Person
{
    public int Id { get; set; }
    public Name Name { get; set; }
}
public class Author : Person
{
    public string Description { get; set; }
}
public class Customer : Person
{
    public double AmountConsumed { get; set; }
}
```

`context.People.ToList()` creates this SQL query:
```sql
SELECT [p].[Id], [p].[Type], [p].[Description], [p].[AmountConsumed], [t].[Id], [t].[Firstname], [t].[Lastname]
FROM [People] AS [p]
LEFT JOIN (
    SELECT [p.Name].*
    FROM [People] AS [p.Name]
    WHERE [p.Name].[Type] IN (N'C', N'A')
) AS [t] ON [p].[Id] = [t].[Id]
WHERE [p].[Type] IN (N'C', N'A')
```

with once `[p].[Id]` and once `[t].[Id]` where both are the same.

I also added a own Project to the [Sample](https://github.com/rzlsoftware/EfCoreSqlQueryWithOwnedEntity)

**Comment by Ranmoro** [comment]
The number of [Id] equals the number of objects Owned Entities in model.

**Comment by JakobFerdinand** [comment]
Yes, but that is not what it´s supposed to do.

let´s take the simple example from upside:

In the database i have a row like where `Firstname` and `Lastname` are wrapped in an Owned Property:

Id | Description | Firstname | Lastname         |
--- | --- | --- | --- |
1  | "foo" | "Max" | "Mustermann" |

Why do i need a sql statement like this:
```sql
SELECT [a].[Id], [a].[Firstname], [a].[Lastname], [a].[Description], [a].[Id]
FROM [Authors] AS [a]
```

this should be enough:
```sql
SELECT [a].[Id], [a].[Firstname], [a].[Lastname], [a].[Description]
FROM [Authors] AS [a]
```

**Comment by BBGONE** [comment]
the select without  - UseRowNumberForPaging looks well because it has no subquery - the column names are repeated only in subquery:
```
exec sp_executesql N'SELECT [c].[CustomerID], [c].[CompanyName], [c].[ModifiedDate], [c].[NameStyle], [c].[PasswordHash], [c].[PasswordSalt], [c].[rowguid], [c].[SalesPerson], [c].[Suffix], [c].[Title], [c].[CustomerID], [c].[EmailAddress], [c].[Phone], [c].[CustomerID], [c].[FirstName], [c].[LastName], [c].[MiddleName]
FROM [SalesLT].[Customer] AS [c]
ORDER BY [c].[LastName], [c].[MiddleName], [c].[FirstName]
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=50
```

**Comment by smitpatel** [comment]
Using 5.0 preview7
Generated SQLs
```SQL
      SELECT [a].[Id], [a].[Description], [a].[Firstname], [a].[Lastname]
      FROM [Authors] AS [a]

      SELECT [p].[Id], [p].[Type], [p].[Description], [p].[AmountConsumed], [p].[Firstname], [p].[Lastname]
      FROM [People] AS [p]
````
