### ISSUE TITLE
Install Microsoft.EntityFrameworkCore.Proxies version 2.1.1 failed on macos

### ISSUE THREAD

**Issue by StarkShang** [dotnet/efcore#12506]
Hi.
I want to Install Microsoft.EntityFrameworkCore.Proxies version 2.1.1 on macos, but I get error infos as follows,

```bash
error: Unable to find package Microsoft.EntityFrameworkCore.Proxies with version (>= 2.1.1)
error:   - Found 4 version(s) in nuget.org [ Nearest version: 2.1.0 ]
```

However, this version of package Microsoft.EntityFrameworkCore.Proxies is already on the nuget website, and I have succeed install it on windows. On mac, I tried to install with dotnet cli, powershell and even visual studio for mac. But all the method were not work. What can I do now?

**Comment by ajcvickers** [comment]
@StarkShang There's not much to go on here, but maybe try cleaning your NuGet caches?
```
dotnet nuget locals all –clear
```

**Comment by StarkShang** [comment]
@ajcvickers 
Thanks. It does work.

**Comment by bricelam** [comment]
Also, make sure you've installed the latest .NET Core SDK
