### ISSUE TITLE
Version Microsoft.EntityFrameworkCore.Attributes

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#12513]
Any special reason for this package version **Microsoft.EntityFrameworkCore.Attributes**, stay in 2.1.0-preview1-final?

Just to know.

**Comment by smitpatel** [comment]
It was package introduced in 2.1 release. It was renamed to Microsoft.EntityFrameworkCore.Abstractions before RTM
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Abstractions/
