### ISSUE TITLE
SQLite not evaluating simple DateTime expressions in database

### ISSUE THREAD

**Issue by mqudsi** [dotnet/efcore#12517]
### Steps to reproduce
```c#
        public IQueryable<Listing> ActiveListings => Listings
            .Where(x => x.Status != ListingStatus.Sold)
            .Where(x => x.RenewTime > DateTimeOffset.UtcNow.AddDays(-7));
```

where the following is the definition:

```c#
...
        public DateTimeOffset RenewTime { get; set; } = DateTimeOffset.UtcNow;
...
```

This produces the following:

```
Microsoft.EntityFrameworkCore.Query:Warning: The LINQ expression 'where ([x].RenewTime > Convert(DateTimeOffset.UtcNow.AddDays(-7), DateTimeOffset))' could not be translated and will be evaluated locally.
```

I see that #10525 implemented `DateTime.Addxxx` for SQL-side values, so I'm really confused by why this won't work as it's a straight comparison between the raw db value and the evaluated C# value. I thought that perhaps it was the usage of `DateTimeOffset` instead of `DateTime`, but that was not the case.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.0 Preview 3

**Comment by pmiddleton** [comment]
There are two issues here.  

1) DateTimeOffset.UtcNow is not currently translated.

2) DateTimeOffset operations are not performed server side for Sqlite.  See #11889 

If you switch the model to use DateTime and then use DateTime.Now you should be ok.

**Comment by mqudsi** [comment]
Thanks for ge reply. This actually consumes me a bit though - is it not utc date stored in the database? I’d imagine utc operations would be the no-op implemented-by-default case and not the other way around? 

I tried DateTime but with DateTime.UtcNow, and that didn’t work.. but as it was the comparand shouldn’t that have been ok in all cases as the value is evaluated once prior to the function call in all cases?

**Comment by mqudsi** [comment]
Yes, minus the migration part as it was a no-migrations configuration. SQLite doesn't have a `DateTime` type let alone a `DateTimeOffset`, both can be deserialized from the text representation stored in the database column (`2018-07-02 02:21:38.3258299+00:00` with type `Text/Numeric`).

**Comment by bricelam** [comment]
I fixed a lot of DateTime SQLite translations in c360e894f74f9c295bb0021328a2489e6e329835, but it hasn't shipped in a release yet. (Try [the nightly builds](https://dotnet.myget.org/gallery/aspnetcore-dev).)

Operations on `DateTimeOffset` can't be translated to SQLite without registering user-defined functions for each operation. Just letting these evaluate on the client is the most pragmatic solution.

**Comment by ajcvickers** [comment]
Bringing together the comments above:
* Nothing on `DateTimeOffset` is translated
*  `DateTime.UtcNow` is translated in 2.1.1
* `DateTime.AddDays` is translated in 2.2 nightlies

**Comment by mqudsi** [comment]
@ajcvickers if that's the case, then there's a bug. `DateTime.UtcNow` on the C# side of the expression is _not_ translated in 2.1.1.

**Comment by ajcvickers** [comment]
@mqudsi It translates for me. Can you look at the repro code below and determine why it mighty be that you are seeing a different behavior?
```C#
public class Blog
{
    public int Id { get; set; }
    public DateTime RenewTime { get; set; }
    public ListingStatus Status { get; set; }
}

public enum ListingStatus
{
    Sold
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory _logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseLoggerFactory(_logger)
            .UseSqlite("DataSource=testdb");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Set<Blog>()
                .Where(x => x.Status != ListingStatus.Sold)
                .Where(x => x.RenewTime > DateTime.UtcNow)
                .ToList();
        }
    }
}
```
Generated SQL
```sql
      SELECT "x"."Id", "x"."RenewTime", "x"."Status"
      FROM "Blog" AS "x"
      WHERE ("x"."Status" <> 0) AND ("x"."RenewTime" > rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', 'now'), '0'), '.'))
```

**Comment by mqudsi** [comment]
@ajcvickers I actually retracted my comment so I could dig into it further locally before makings that assertion with more confidence. 

I'm assuming that the expression to determine the value of the righthand side of the comparison in `.Where(x => x == SomeExpr(notX))`  does not matter and will first be reduced to a single value prior to translation, so long as it does not depend on the value of x?

**Comment by ajcvickers** [comment]
@mqudsi I'm not sure if I 100% follow, but I don't think that assumption holds.

**Comment by mqudsi** [comment]
Basically, I am wondering if the entire lambda, including any function calls, must be reduced/translated by EFCore or if subexpressions not dependent on the value of the callback parameter may be first evaluated are first JIT'd before the translation is kicked off.

**Comment by pmiddleton** [comment]
The lambda will be converted to an expression tree by the c# compiler.  

Nothing will be evaluated before translation starts.

The translation will first look at the expression tree and preevaluate most anything it can (adding constants, run nonmapped functions, etc). 

 
The remaining will be translated to sql if possible.  If something is not supported in the translation then that section will be evaluated client-side after the rest of the query runs.

**Comment by mqudsi** [comment]
Thanks for the reply. I have filed a new issue with some remarks on this behavior.
