### ISSUE TITLE
Model Snapshot code: Generated code for non well-known types (like enum)

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#1252]
Model snapshot code is a serialized form of the model therefore it should include correct type as the model. But properties that are not well-known types (like user defined enum) comes from application code, so to including them in model snapshot code requires the reference to them to be added in C# code. Moreover it can cause problem if application code is changed. Therefore presently model snapshot code includes underlying type of non well-known types.
Using a JSON mode snapshot may help.

**Comment by rowanmiller** [comment]
We can swap to representing enums in the model if we need it in the future. For the moment using the base type of the enum is fine. We can change this when another feature requires it.
