### ISSUE TITLE
Why ef wants to Remove an entity when a required field of it is being null?

### ISSUE THREAD

**Issue by inlineHamed** [dotnet/efcore#12530]
I have a model like this:
```
class A{
[Required]
public int BId {set;get;}
public B B {set ;get;}
}
class B{
public int Id {set ;get;}
}
```

in my asp action:
```
// get 'a' from context
a.B=null;
a.BId=1;

context.Update(a);
await context.SaveChangesAsync();

```

 ef will remove the entire object from database.

**Comment by ajcvickers** [comment]
@hmdhasani There's not much to go on here, but this is likely due to cascading behaviors of required relationships, as described in the docs: https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete
