### ISSUE TITLE
Using IMutableProperty.AfterSaveBehavior from other than OnModelCreating?

### ISSUE THREAD

**Issue by SrinivasSrinivas** [dotnet/efcore#12547]
Can we do the AfterSaveBehavior from a place other than OnModelCreating?
I mean the AfterSaveBehavior should be dynamic, so that whenever I update I should be able to change the AfterSaveBehavior.

### Further technical details
EF Core version: 2.1.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.7.4)

**Comment by SrinivasSrinivas** [comment]
Hi,

The use case is, depending on the user permissions one user can update certain columns and the other user can't update those columns. So depending on the logged in user, the update should be changed dynamically.

Thanks,
Srinivas Pulla.

**Comment by ajcvickers** [comment]
@SrinivasSrinivas We discussed this in triage and agreed that this behavior is by-design a feature of the model that is intended to be used for things that are structurally required to be, for example, read-only after save. For example, PK properties. Dynamically deciding and implementing user-level behaviors should really be done in business logic, and not through mutation of the model.
