### ISSUE TITLE
V2.1 - Many thousands exceptions during first query execution

### ISSUE THREAD

**Issue by altmann** [dotnet/efcore#12548]
We updated from EF Core 2.0.1 to 2.1.1. Now we face one issue. We have two queries in our application (GetById() and GetAll()). 

If I execute one query the first time then the query takes longer (6 seconds) in comparison to Ef Core 2.0 (4 seconds). In Visual Studio in Diagnostic Tools we see that many thousands of Exceptions are thrown during these 6 seconds. Exception see attachment. 

If I execute the same query a second time then it is very fast (some ms).

Maybe our issue is very similar to https://github.com/aspnet/EntityFrameworkCore/issues/12489

[testhost.x86.exe_180704_132159_51b007fa-20c7-47bc-b05b-439f027d7933.zip](https://github.com/aspnet/EntityFrameworkCore/files/2163139/testhost.x86.exe_180704_132159_51b007fa-20c7-47bc-b05b-439f027d7933.zip)

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer and Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment]
@altmann Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by altmann** [comment]
I can't publish the code here. I can try to find a simplified data model which also produce this behavior but this will take time. I hope I can do that in the next week. 

I also looked to other issues here and found issue #11765. I think this is the same issue. 

We also found out that my described behaviour (producing many thousand exceptions) is not reproduceable on all machines. On some machines the diagnostic tools in VS show no exceptions but on some other machines the diagnostic tools in VS show many thousands exceptions which is not practical for us because the application is blocked. So is it a VS settings? In EF Core 2.0 it was working, in EF Core 2.1 not.

**Comment by altmann** [comment]
@ajcvickers We found a very simple setup which produce the exceptions. 
The exceptions are thrown when you nesting owned entities (a owned entity in a owned entity).

[EfCoreSample.zip](https://github.com/aspnet/EntityFrameworkCore/files/2183576/EfCoreSample.zip)

When you execute the application and set the breakpoint to line 39 of Program.cs then you see 4 ArgumentNullExceptions in the Diagnostic Tools of Visual Studio. 

Because we use nesting owned entities in our real codebase very often, the exceptions slows down our debugging experience. In EfCore v2.0 these exceptions aren't faced from us. 

If you have any questions please ask us.

**Comment by leak** [comment]
I have the same issue with my application after upgrading from 2.0 to 2.1.1.

**Comment by smitpatel** [comment]
@altmann , @leak - Are you guys talking about this exception?
![image](https://user-images.githubusercontent.com/1528107/43017910-b23906c2-8c0c-11e8-9c27-9b5eb4b65de2.png)

**Comment by leak** [comment]
Yes, that is the one. Not sure if the subsequent thousand ones are the same though.

**Comment by altmann** [comment]
@smitpatel Yes, that is the one. If you have one nested owned entity like in the attached codebase then you have 2 to 4 of this exception. If you have a real project with many nested owned entities then you have thousands of it.
