### ISSUE TITLE
SQLite provider sending Foreign_Keys ON command multiple times on same context instance

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#12545]
I'm logging SQL commands using the ConsoleLoggingProvider and SQLIte.

Each SQL query in the log output is prefaced with what looks like some kind of warm-up. I don't know if this is standard SQLite behavior (google is not helping me determine that) or a problem with the logging via the provider. It is _not_ happening when I switch to the SQL Server provider. In other words, with SQL Server, I only get the single [expected] command in the log.

Here is an example. From this simple LINQ query:
 var locations = context.Locations.ToList();

The logging output that has what looks like an extra command with no command text in it.
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "l"."LocationId", "l"."CloseTime", "l"."OpenTime", "l"."StreetAddress"
      FROM "Locations" AS "l"

```

Here is the logger provider:

  ```
public static readonly LoggerFactory MyConsoleLoggerFactory
         = new LoggerFactory(new[] {
              new ConsoleLoggerProvider((category, level)
                => category == DbLoggerCategory.Database.Command.Name
               && level == LogLevel.Information, true) });
```
I'm not spending the time to include a full code listing in hopes that you'll just look at this and say "yep, this is normal for SQLite".

### Further technical details
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by ErikEJ** [comment]
The command text is "PRAGMA foreign_keys on"! 

It enforces fk checks (off by default in SQLite)

**Comment by julielerman** [comment]
oh! (palm to forehead) so it is! ( the command text) duh!

Just reading up on that at https://sqlite.org/foreignkeys.html. It's not something I knew about before.

So my 3 commands are the first query followed by 2 lazy loading queries. As a warmup it makes sense on first query. But it's also being sent prior to each of the other 2 queries ..on the same instance of dbcontext. 

Found this statement in this issue (https://github.com/aspnet/EntityFrameworkCore/issues/10390):
" With 2.0 release, we send out command only if the connection actually gets opened."

And found this of course: https://github.com/aspnet/EntityFrameworkCore/issues/2380 :)

But aren't all 3 of my commands on the same connection though? 

Not at that computer but now that I have an idea of what's going on I will try out some difference scenarios.

**Comment by julielerman** [comment]
It's definitely repeating the FKs ON command when I have 3 LINQ queries executed by a single context instance.
Is that expected? Necessary?
Thanks

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "l"."LocationId", "l"."CloseTime", "l"."OpenTime", "l"."StreetAddress"
      FROM "Locations" AS "l"
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "l"."LocationId", "l"."CloseTime", "l"."OpenTime", "l"."StreetAddress"
      FROM "Locations" AS "l"
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "l"."LocationId", "l"."CloseTime", "l"."OpenTime", "l"."StreetAddress"
      FROM "Locations" AS "l"
Press any key to continue . . .
```

**Comment by ajcvickers** [comment]
@julielerman It is expected that this command is sent each time the connection is opened. So, as you know, since the connection is by default opened and closed for each query, then this expected. However, if you are opening the connection only once and this is still sent before each query, then that would be a bug.
