### ISSUE TITLE
Commands: Use "soft" package dependencies

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#1255]
Make the EntityFramework.Commands package not have a hard dependency on EntityFramework.Migrations and EntityFramework.Relational.

The idea is to remove the NuGet package dependency, but check that they're installed while executing a command.

**Comment by rowanmiller** [comment]
@bricelam is this something we still want to do?

**Comment by rowanmiller** [comment]
Discussed with @bricelam, this would only add value if you wanted to use commands with something other than a relational database... which is not a scenario at the moment. We can deal with this if that becomes a valid scenario in the future.
