### ISSUE TITLE
Incorrect documentation: ObsoleteAttribute referencing IRelationalTypeMappingSource

### ISSUE THREAD

**Issue by jholovacs** [dotnet/efcore#12554]
Latest release of EF Core has ObsoleteAttributes peppered across the code base with the following message or similar:

> "Use IRelationalTypeMappingSource.GetMapping(typeof(string)).GenerateSqlLiteral() instead"

...but there's a problem with that.  The aforementioned interface does not have this method.  There is a `FindMapping(Type)`, but its signature is of `CoreTypeMapping`, not the expected `RelationalTypeMapping`; `CoreTypeMapping` does not have a GenerateSqlLiteral() method.

**Comment by ajcvickers** [comment]
@jholovacs The GetMapping methods are extension methods--see https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs

However, I'm curious what you are doing that needs this--these methods are commonly used by providers or other low-level extensions. It's pretty unusual for applications to need them.

**Comment by jholovacs** [comment]
I was looking for a way to change the entity names in the db to all lowercase characters (I use PostgreSql and it's super annoying to use quotes when manually querying or writing scripts).

Still I think the documentation is not accurate.  The documentation pretty clearly indicates that these methods belong to `IRelationalTypeMappingSource`, and it's also clearly not the case.
