### ISSUE TITLE
Value Conversion generates invalid query

### ISSUE THREAD

**Issue by thomasdc** [dotnet/efcore#12561]
`EnumToStringConverter` works fine when persisting to the database, as documented [here](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions):

```
modelBuilder
    .Entity<Rider>()
    .Property(e => e.Mount)
    .HasConversion(new EnumToStringConverter<EquineBeast>());
```

However, when I query the database with a filter on the enum:

```
dbContext
    .Set<Rider>()
    .Where(_ => _.Mount == EquineBeast.Mule)
    .ToList();
```

EF Core underlying generates a SQL expression filtered on a number instead of the string representation.

``` 
SELECT ...
FROM   RIDER "_"
WHERE  "_".MOUNT = 1
```

This is of course an invalid query since the Mount column is defined as a string column in the database.
Is this a know issue? Without query support, the whole Value Conversion feature is useless imo.

### Further technical details
EF Core version: 2.1.1
Database Provider: Devart.Data.Oracle.EFCore

**Comment by ajcvickers** [comment]
@thomasdc This looks like a bug in the DevArt provider--please file an issue with them.

**Comment by thomasdc** [comment]
For those interested, the related issue on the Devart forum can be found here: https://forums.devart.com/viewtopic.php?f=30&t=37405
