### ISSUE TITLE
Hiding a property in a base class and then attempting to map both throws

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#12565]
Moved from https://github.com/aspnet/Identity/issues/1855

More information on the context can be found here:
- https://github.com/aspnet/EntityFrameworkCore/issues/12458

I get this:

>The specified field '<Id>k__BackingField' of type 'Guid' cannot be used for the property 'ApplicationIdentityRoleClaim<Guid>.Id' of type 'int'. Only backing fields of types that are assignable from the property type can be used.

Here a repo 
- https://github.com/ckams/-Buggy-__BackingField

**Comment by ajcvickers** [comment]
Note for triage: the issue is triggered by a hiding a property in a mapped base class with another property in the derived class when attempt is made to include them both in the model. Simplified repro:

```C#
public class Blog
{
    public int Id { get; set; }
}

public class ABlog : Blog
{
    public new Guid Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ABlog>(b =>
        {
            b.Property(e => ((Blog) e).Id);
            b.Property(e => e.Id);
        });
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

**Comment by ckams** [comment]
Why closing without fixing it?
