### ISSUE TITLE
Weak collections not included in group join

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#12583]
See `ComplexNavigationsWeakQueryTestBase.Include_with_groupjoin_skip_and_take`

**Comment by maumar** [comment]
Problem is actually somewhere else. Initially, when we construct Inlcude trees we can't associate qsre from grouping

```
join Level1 l1 in value(EntityQueryable`1[Level1]) on [t].OneToOne_Required_PK1?.Level1_Optional_Id equals Convert([l1].Id) into IEnumerable`1 grouping
```

with the qsre that include operator was declared on:

```
from Level1 t in value(EntityQueryable`1[Level1])
```

**Comment by maumar** [comment]
example that doesn't involve weak collections:
https://github.com/aspnet/EntityFrameworkCore/issues/13083

**Comment by AndriySvyryd** [comment]
Blocked by the decision on https://github.com/aspnet/EntityFrameworkCore/issues/17068

**Comment by smitpatel** [comment]
@AndriySvyryd - decision on #17068 has been made. What should we do with this now?

**Comment by AndriySvyryd** [comment]
Can close and delete/disable the test

**Comment by smitpatel** [comment]
Removed in #19017
