### ISSUE TITLE
Is there a way to disabled Lazy Loading temporarily in a query？

### ISSUE THREAD

**Issue by mokeyish** [dotnet/efcore#12607]

**Comment by mokeyish** [comment]
@smitpatel The code I written before using Lazy Loading may cause errors，so I want to disable Lazy Loading temporarily and migrate step by step later.

**Comment by smitpatel** [comment]
> When executing a query, lazy loading has no effect.

Can you show an example of code?

**Comment by divega** [comment]
@mokeyish you can use `context.ChangeTracker.LazyLoadingEnabled` to control this.
