### ISSUE TITLE
Regression: first migration timestamp

### ISSUE THREAD

**Issue by BalassaMarton** [dotnet/efcore#12626]
When adding the first migration, EF used to create it with timestamp '0000000000000'. Now it adds the current timestamp.
Using the 'null' timestamp for initial migrations is useful at the early stages of a project when migrations are not used yet, and the repo contains just an `InitialCreate` or similar migration for creating the database.

**Comment by BalassaMarton** [comment]
Then the documentation is a bit misleading:
https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/
It could be a useful feature.

**Comment by bricelam** [comment]
...should we replace the `0`s with `X`s?

**Comment by BalassaMarton** [comment]
That would screw up the ordering.

**Comment by BalassaMarton** [comment]
Oh you mean in the documentation? :) Yeah probably.

**Comment by bricelam** [comment]
Note to self: We wanted to investigate always using `00000000000000` as the timestamp of the initial migration. This would help with one of our internal use-cases.

**Comment by smitpatel** [comment]
@bricelam - Do we want to generate `00000` for initial migration? The current code already has information about last migration. So it can change migrationid appropriately.

**Comment by smitpatel** [comment]
Updated documentation. Leaving this issue open to make product change if any.
