### ISSUE TITLE
EF Power Tools 'Generate Views' not working

### ISSUE THREAD

**Issue by cankatabaci** [dotnet/efcore#12625]
I am trying to create the existing views in the  database. I am install Entity Framework Power Tools Beta 4 for this. (Scaffold-DbContext not working for views). When i right click to my DbContext class, choose 'Entity Framework>Generate Views'  getting an error.

Here is my Dbcontext Class (its auto generated from Scaffold-DbContext command):
```
    public partial class XXXXDevContext : DbContext
    {

        public XXXXDevContext()
        {
        }

        public XXXXDevContext(DbContextOptions<XXXXDevContext> options)
            : base(options)
        {
        }

//DbSets

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                    .AddJsonFile("appsettings.json")
                        .Build();
            optionsBuilder.UseSqlServer(configuration.GetConnectionString("XXXX"));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
	}
    }
```
```
Exception message:
A constructible type deriving from DbContext could not be found in the selected file.
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 Preview 15.8.0 Preview 4.0

**Comment by ErikEJ** [comment]
EF Power Tools do not work with EF Core, and the Generate Views feature does not relate to EF Core. In addition, Generate Views does not relate to SQL Views.

**Comment by cankatabaci** [comment]
@ErikEJ Thank you for the information
