### ISSUE TITLE
Side effects of setting EntityEntry.State

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#12631]
When I manually set the state of an entity to Unchanged, the CurrentValues automatically get set to be equal to the OriginalValues. This makes sense but isn't documented in EntityEntry.State metadata.

Are there any other undocumented side effects of setting EntityEntry.State that I might have missed?

**Comment by divega** [comment]
@Wain123 I cannot think of any other side effects that could be unexpected. I am going to move this issue to our documentation repo so that we can track adding conceptual topics about managing state with these APIs.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework.Docs#852
