### ISSUE TITLE
DbContext can support Parallel?

### ISSUE THREAD

**Issue by quan01994** [dotnet/efcore#12646]
````
const string connectString = "Server=localhost;Database=HYW.CRM;User ID=sa;pwd=123456;MultipleActiveResultSets=true";
using (var db = new HYWCRMContext(connectString))
{
    var employeeInfos = db.EmployeeInfo.AsNoTracking().Where(m => m.BranchCode == "0801" && m.Status == 0).ToList();
    var dic = new Dictionary<string,int>();
    employeeInfos.AsParallel().ForAll(e =>
    {
        var count = db.MemberInfo.Count(m => m.EmpCode == e.EmpCode);
        dic.Add(e.EmpName,count);
     });
    foreach (var d in dic)
    {
       Console.WriteLine(d.Key+" "+d.Value);
     }
}
````

if dbcontxt suppot , How can I use it?
If not, how can I optimize my code?
use dapper?

**Comment by quan01994** [comment]
I write this 
````
               employeeInfos.AsParallel().ForAll(e =>
                {
                    using (var _db = new HYWCRMContext(connectString))
                    {
                        var count = _db.MemberInfo.Count(m => m.EmpCode == e.EmpCode);
                        dic.Add(e.EmpName, count);
                    }
                });
````
but This will consume a lot of performance

**Comment by sdanyliv** [comment]
@quan01994, It is a simple SQL.

Code snippet is written on the knee. But it should work and processed on the server side. If not - it is another issue for EF Core with grouping.
```cs
using (var db = new HYWCRMContext(connectString))
{
    var employeeInfos = 
        from e in db.EmployeeInfo.AsNoTracking()
        where e.BranchCode == "0801" && e.Status == 0
        join m in db.MemberInfo on e.EmpCode equals m.EmpCode
        group m by e.EmpName into g
        select new 
        {
           EmpName = g.Key,
           Count = g.Count()
        }
   
    var dic = employeeInfos.ToDictionary(e => e.EmpName);
    foreach (var d in dic)
    {
        Console.WriteLine(d.Key+" "+d.Value);
    }
}
```
**Note**, that result a little bit different. If there no `MemberInfo` for specific `EmployeeInfo`  -  employee record will be filtered. 
For sure we can rewrite query using `LEFT JOIN`, but as i know, currently EF Core will fail with such queries.

```cs
using (var db = new HYWCRMContext(connectString))
{
    var employeeInfos = 
        from e in db.EmployeeInfo.AsNoTracking()
        where e.BranchCode == "0801" && e.Status == 0
        join m in db.MemberInfo on e.EmpCode equals m.EmpCode into members
        from pm in members.DefaultIfEmpty()
        group pm by e.EmpName into g
        select new 
        {
           EmpName = g.Key,
           Count = g.Count(member => member.EmpCode != null)
        }
}
```

**Comment by quan01994** [comment]
SELECT e.EmpName,me.RemarkNumber,me.RemarkPeopleNumber FROM EmployeeInfo e 
LEFT JOIN 
(SELECT COUNT(RemarkId) as RemarkNumber,COUNT(DISTINCT MemberId) as RemarkPeopleNumber,CreateUser FROM MemberRemark WHERE RemarkStatus=0 GROUP BY CreateUser) 
AS me on e.EmpName=me.CreateUser
WHERE BranchCode = '0000' and [Status]=0


in this sql ,COUNT(DISTINCT MemberId) how  to convert  linq

**Comment by sdanyliv** [comment]
@quan01994, as i know there is no way to do that with pure EF Core. But since I am the author of this library [linq2db.EntityFrameworkCore](https://github.com/linq2db/linq2db.EntityFrameworkCore), for sure i will propose its use :)
```cs
var emloyeeInfos = 
   from e in db.EmployeeInfo
   from me in (
      from memberRemarks in db.MemberRemark
      where 
         memberRemarks.RemarkStatus == 0
      group memberRemarks by memberRemarks.CreateUser into g
      select new  
      {
         CreateUser = g.Key,
         RemarkNumber = g.Count(),
         RemarkPeopleNumber = g.CountExt(m => m.MemberId, Sql.AggregateModifier.Distinct)
      }
   ).LeftJoin(me => me.CreateUser == e.EmpName)
   where
      e.BranchCode == "0000" &&
      e.Status == 0
   select new 
   {
      e.EmpName,
      RemarkNumber = Sql.ToNullable(me.RemarkNumber),
      RemarkPeopleNumber = Sql.ToNullable(me.RemarkPeopleNumber)
   };

var list = emloyeeInfos.ToLinqToDB().ToList();
```
Note that `CountExt`, `LeftJoin` and `Sql.ToNullable()` are **linq2db** extension methods.
- `CountExt` - custom aggregate
- `LeftJoin` - **linq2db** extension for simplifying join operations in linq queries
- `Sql.ToNullable` - since we have `LEFT JOIN` and `RemarkNumber` and `RemarkPeopleNumber` can be `NULL`, so we just changing their type from `int` to `int?`

**Comment by quan01994** [comment]
These two methods create conflicts ！
“Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(System.Linq.IQueryable<TSource>, System.Threading.CancellationToken)”
“LinqToDB.AsyncExtensions.ToListAsync<TSource>(System.Linq.IQueryable<TSource>, System.Threading.CancellationToken)”	
@sdanyliv 

using Microsoft.EntityFrameworkCore;
using LinqToDB;

How should I choose

**Comment by sdanyliv** [comment]
@quan01994, we know about that and i did everything to solve this conflict. Just write `ToListAsync()` it should process anyway.
Collision here because `IAsyncEnumerable` still not in .NET Framework and each linq provider have to define its own Async methods.

**Comment by quan01994** [comment]
@sdanyliv Thank you for your patience.   :)

**Comment by sdanyliv** [comment]
Also for achieving best performance i suggest to compare execution plan of previous query against [Window Functions](https://linq2db.github.io/articles/sql/Window-Functions-%28Analytic-Functions%29.html) usage:
```cs
var aggregatedInfos = 
   from e in db.EmployeeInfo
   from mr in db.MemberRemark.LeftJoin(mr => mr.CreateUser == e.EmpName)
   where
      e.BranchCode == "0000" &&
      e.Status == 0
   select new 
   {
      e.EmpName,
      RN = e.RowNumber().Over().PartitionBy(e.EmpName).OrderBy(e.EmpName).ToValue(),
      RemarkNumber = Sql.Ext.Count().Over().PartitionBy(e.EmpName).ToValue(),
      RemarkPeopleNumber = Sql.Ext.Count(mr.MemberId, Sql.AggregateModifier.Distinct).Over().PartitionBy(e.EmpName).ToValue()
   };

var emloyeeInfos = 
   from ei in aggregatedInfos 
   where ei.RN == 1
   select new 
   {
      e.EmpName,
      e.RemarkNumber,
      e.RemarkPeopleNumber
   };

var list = emloyeeInfos.ToLinqToDB().ToList();
```

**Comment by divega** [comment]
@smitpatel please link this scenario to GroupBy improvement.

**Comment by smitpatel** [comment]
#11976
