### ISSUE TITLE
Query: Allow non-deterministic runtime constants to be evaluated once per query

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#12651]
This can be used when non-deterministic runtime constant like `Datetime.Now` are used in the query but due to them being composed over, we cannot evaluate them on server in main query.

We can either evaluate DateTime.Now on client or run a command to get the value first (we would need to fix #11466), then pass the value to query as parameter to generate actual results.

**Comment by divega** [comment]
This affects DateTime.Now and friends now, but it may affect other non-deterministic functions, either in providers or user mapped.

**Comment by divega** [comment]
Superseded by #12672.
