### ISSUE TITLE
Warning when query materializes an entity outside the top projection

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12667]
One example of when this may happen is if an opaque method that takes an entity as an argument is invoked in the Where clause, e.g.:

``` c#
var query = context.People
    .Include(p => p.Addresses)
    .Where(p => p.Name.StartsWith(name) && IsCustomer(p));
```

Given the current behavior, the `p` passed to `IsCustomer` won't be tracked, and the `Addresses` navigation property won't be populated.  

If `IsCustomer(p)` returns false, then that person entity won't end in the query results. For a tracked query that means that the instance will be discarded and not tracked. Moreover, for specific providers (e.g. Cosmos DB), even if `IsCustomer(p)` returns true, `p` could be a different object instance from the one that will be included in query results. 

Hence the proposal is to make this situation trigger a warning.

**Comment by divega** [comment]
Note that the scenario above can become very inefficient because for the second query that we create to include the Addresses collection the evaluation of the client predicate will need to fetch from People again. @smitpatel is going to create an issue that optimizes cases like this (and some others) by filtering the second query in terms of the collection of key values obtained from the first query.

**Comment by smitpatel** [comment]
#12776

**Comment by smitpatel** [comment]
We decided not to do client eval outside of the top projection. Which means that above query would just throw rather than translating to server (full server translation is not possible). So we don't need to warn anymore.
