### ISSUE TITLE
Error	NU1202	Package Microsoft.EntityFrameworkCore 2.1.1 is not compatible with netcoreapp2.1

### ISSUE THREAD

**Issue by batwomankt** [dotnet/efcore#12665]
I've installed .Net Core SDK 2.1.302 on my development machine running VS 15.7.5.  I create a simple .Net Core WebApp from the VS templates and I get this error when trying to build the template without any modifications

```
Error NU1202 Package Microsoft.EntityFrameworkCore 2.1.1 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.EntityFrameworkCore 2.1.1 does not support any target frameworks.
```

### Steps to reproduce
Project file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>1c4b8384-23cc-46b6-a537-1f8abb24dc46</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
  </ItemGroup>

  <Target Name="CopySignalR" BeforeTargets="AfterBuild">
    <ItemGroup>
      <SignalRJSClientFiles Include="$(MSBuildThisFileDirectory)node_modules\@aspnet\signalr\dist\browser\*" />
    </ItemGroup>
    <Copy SourceFiles="@(SignalRJSClientFiles)" DestinationFolder="$(MSBuildThisFileDirectory)wwwroot\lib\signalr" />
  </Target>

</Project>
```

### Further technical details
EF Core version: 2.1.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win 10 x64
IDE: Visual Studio 2017 15.7

**Comment by Eilon** [comment]
@natemcmaster - any ideas on this?

**Comment by natemcmaster** [comment]
The only way I can imagine this happening with the setup described above is if you have a corrupt NuGet cache. NuGet determines framework compatibility by looking at the extract contents of a nupkg. So, if extraction of the package failed part way through or some contents of the package deleted, NuGet would not be able to determine that Microsoft.EntityFrameworkCore targets .NET Standard 2.0.

@batwomankt can you provide a binary log which helps us see more details? On command line, run `dotnet restore /binaryLogger:msbuild.binlog`. Note: this will capture some details about your machine, such as its environment variables. If you have stored secrets as environment variables, don't post the log file publicly.

**Comment by batwomankt** [comment]
I have already tried clearing the local NuGet cache by running: `dotnet nuget locals all --clear` and the same still happens.

I've attached the log file as requested.
[msbuild.zip](https://github.com/aspnet/EntityFrameworkCore/files/2193650/msbuild.zip)

**Comment by natemcmaster** [comment]
Thanks for the logs. You've stumped me. No clue what's going on. Let me forward to the NuGet team to see if they have any ideas.

**Comment by natemcmaster** [comment]
Can you try one more thing? Add this to your .csproj and rerun restore. This will help us identify it you have a corrupt fallback folder.
```xml
  <PropertyGroup>
    <!-- Don't restore from any fallback folder -->
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
   </PropertyGroup>
```

**Comment by batwomankt** [comment]
That did it - thank you, I'm very sorry - I should've thought to check that myself!

**Comment by natemcmaster** [comment]
So, this probably means you have a corrupt fallback folder, which `dotnet nuget locals clear` would not have removed. Can you share with me what this folder looks like? `C:\Program Files\dotnet\sdk\NuGetFallbackFolder`? Also, what does this file look like `%APPDATA%/NuGet/NuGet.config` ?

**Comment by batwomankt** [comment]
I did have a corrupt fallback folder - I blew it away and ran `dotnet restore` to get myself back to a good state.

**Comment by natemcmaster** [comment]
@batwomankt any ideas what might have led to the corruption of your fallback folder?

**Comment by batwomankt** [comment]
@natemcmaster I really don't - I wish I did
