### ISSUE TITLE
Should we be treating objects created by the user in a query differently from the ones we materialize?

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12668]
Currently we have an implicit assumption that if a user writes to code to explicitly create instances of a mapped type, it is ok not to track it. 

Creating this issue to have an opportunity to (re)discuss if this what we want, and how it plays with different features, present and future, like shadow properties and customer materialization through factory methods, etc.

**Comment by ajcvickers** [comment]
@smitpatel to cleanup.

**Comment by smitpatel** [comment]
We decided in meeting that, we will track entities in result if and only if they are created through materialization pipeline. Anything else we don't track.
