### ISSUE TITLE
How can I completely remove every trace of an entity from a context?

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#12679]
If I detach an entity, then it will still be contained in collections belonging to other entities. Is it possible to detach an entity in such a way that it gets removed from collections? Or, more generally, how do I thoroughly remove every trace of the entity from the context (assuming there are no FKs pointing to it)?

EF Core version: 2.1.0-rc1-30677
Database Provider: Microsoft.EntityFrameworkCore.Oracle
Operating system: Windows 10
IDE: Visual Studio Professional 2017 15.6.5

**Comment by ajcvickers** [comment]
There is nothing currently built-in that will do this.
