### ISSUE TITLE
Discrepancy between database and C# around null coalescing

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#12673]
https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/515 detailed a PostgreSQL FTS related issue around null coalescing which led me to think about the problem in general.

The following code demonstrates a discrepancy between how C# and SQL handle nulls when concatenating strings:

```c#
var blogs = new[] { new Blog { Name = null } };

ctx.Blogs.AddRange(blogs);
ctx.SaveChanges();

var dbCount = ctx.Blogs.Count(b => b.Name + "wat" == "wat");
var memoryCount = blogs.Count(b => b.Name + "wat" == "wat");

Console.WriteLine($"DB Count: {dbCount}, memory count: {memoryCount}");
```

While C#'s concatenation operator automatically coalesces nulls to empty strings, SQL doesn't (on PostgreSQL and SQLite, I'm pretty sure this is standard behavior). This forces users to systematically use the C# null coalescing operator `??`.

I'm not sure if there are many other examples of C# operators which implicitly coalesce in this way, but I wonder if this is something that EF Core should fix, with the general goal of making server-side execution as close as possible client-side execution.

Note that fixing this would in principle be a breaking change, as current code is written with the expectation that coalescing doesn't occur.

**Comment by divega** [comment]
**EF Triage:** We will look into adding coalesce operator for nullable strings in concatenation.

**Comment by smitpatel** [comment]
Duplicate of #3836
