### ISSUE TITLE
I accidentally clicked "No" to "Was this page helpful."

### ISSUE THREAD

**Issue by JosephFerry** [dotnet/efcore#12670]
When in fact the opposite is true. This web page is the most helpful page for me out there. It's like a checklist.

**Comment by divega** [comment]
@JosephFerry curious, which page was it exactly?

**Comment by JosephFerry** [comment]
Hi, Diego,


Sorry about that.


https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db


I copied the steps I needed to my own checklist to modify a few steps (such as to add flags to the Scaffold-DbContext command), but I know I can always search the web using keywords like "MVC Core 2.0 existing database getting started site:microsoft.com" if I'm not on my primary development computer and able to get to my checklist.


By the way, I'm interested in creating my own Razor template files that even generate .cs files (through tt5 concepts), and the articles I have found assume that I know a bit more than I do know. In particular, I am eventually interested in creating custom attributes that will affect code generation, if that is possible). Don't worry if you don't know this off the top of your head, I just thought I'd ask. I know the location of the folder where the template files are, and how to put my modified templates in a Templates folder of each application with additional, say, javascript and perhaps slightly modified Razor code.


I suppose that I could post this as a question, but people are such jerks if the question is not precisely worded that I will not bother.


Thanks.


Joe

________________________________

**Comment by divega** [comment]
@JosephFerry when you say that attributes would affect code generation, do you mean that code generation would use the attributes in the code they generate?

**Comment by JosephFerry** [comment]
I think we're talking about the same thing.?I want to create a custom attribute that can be used for an annotation in a model that a Razor template will use to generate conditional custom cshtml or cs code based on the custom attribute and (if it has one) its value. I might create an attribute on a property in a model that will trigger the creation of a search text box in a search form at the top of its index page for each field that has such an attribute, and the attribute might have a value of "Contains", "StartsWith" or "ExactMatch". Or the search field might be a dropdown list from unique values in the columns populating the index page, or a dropdown list based on a field associated in a navigation property. The model class might have an attribute that tells whether to use the NuGet package for pagination when creating an index page for that index, or put a combobox at the top of the page to show 5, 10, 25 or whatever rows per page. A primary key property might have an attribute that tells whether to show the primary key in the index page and/or, say, the Edit page (the primary key would not be editable, however).


Thanks.

**Comment by JosephFerry** [comment]
?Thank you very much, Diego. I'm sure I will be working on this in a while. Joe

________________________________
