### ISSUE TITLE
I cannot install EFCore or SQLite in my Virgin UWP project

### ISSUE THREAD

**Issue by maxmin88** [dotnet/efcore#12677]
Describe what is not working as expected.

PM> Install-Package Microsoft.EntityFrameworkCore.Sqlite
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/microsoft.entityframeworkcore.sqlite/index.json
Restoring packages for C:\Users\rtwic\Documents\Visual Studio 2017\Projects\Samples\TestSQLNuGet\TestSQLNuGet\TestSQLNuGet.csproj...
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063). Package 
Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm. Package 
Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm-aot. 
Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm64-aot. 
Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64. Package 
Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64-aot. 
Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86. Package 
Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86-aot. 
Package Microsoft.EntityFrameworkCore.Sqlite 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'TestSQLNuGet'.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Sqlite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by Trolldemorted** [comment]
I am unable to use any ef core versions after 1.1.6 in my uwp project.

>Package Microsoft.EntityFrameworkCore 2.1.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063). Package Microsoft.EntityFrameworkCore 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)

Unfortunately W10M did not receive the 16299 FCU, so we are stuck with 15063 and netstandard 1.4. We suspect we are being hit by https://github.com/aspnet/EntityFrameworkCore/issues/9994 and thus really would like to update, but we can't. Can you estimate when ef core 2 will be available for uwp?

**Comment by divega** [comment]
The reason installing the EF Core 2.1 packages fails with this error is that the UWP application targets a minimal version of Windows 10 that does not support .NET Standard 2.0. In order to avoid the error, set the minimal version to Windows 10 Fall Creators Update (build 16299.0) as documented in https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started#create-a-new-uwp-project. 

EF Core version 2.0 and later require .NET Standard 2.0 compatible .NET implementations. .NET Standard 2.0 support was added to UWP in Windows 10 Fall Creators Update (build 16299.0). There are no plans for retrofitting EF Core 2.x to non-.NET Standard 2.0 platforms.

Re #9994, there is a workaround described at https://github.com/aspnet/Microsoft.Data.Sqlite/issues/474#issuecomment-356419119. I hope this helps.

**Comment by Trolldemorted** [comment]
That is very unfortunate, especially if there are other bugs in 1.1.6 whose fixes won't be backported.

Since developers can't set the minimal version to 16299 because 16299 is not shipped to W10m devices, could you revise the decision to require .netstandard2.0 or higher? Otherwise you are shutting out every UWP app that wants to run on W10M.

**Comment by bricelam** [comment]
A community member created [Microsoft.Data.Sqlite.Core.Backport](https://www.nuget.org/packages/Microsoft.Data.Sqlite.Core.Backport/) to target older platforms with the 2.0.0 codebase of Microsoft.Data.Sqlite, but it looks like it hasn't been updated in a while. A similar effort could be done to the EF Core codebase.
