### ISSUE TITLE
Entity deletions without loading them into memory

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#12681]
Please consider adding an overload to the Remove() method accepting a predicate so we can delete entities matching the predicate without loading them into memory.

For example:

`MyContext.PurchaseOrders.Remove(po => po.Status == Status.Canceled);`

Currently the only way to delete entities in EF is by loading entities into memory and calling .Remove() or .RemoveRange().

**Comment by AmmarBashir** [comment]
Yes this is most awaiting feature since birth of Entity framework

**Comment by smitpatel** [comment]
Duplicate of #795
