### ISSUE TITLE
EF.Functions.Like  not  supported  N'value' like '%+model.Property+%'

### ISSUE THREAD

**Issue by milenstack** [dotnet/efcore#12685]
EF.Functions.Like  not  supported  N'value' like '%+model.Property+%'
I need to implement the following SQL from EF Core 2.1
SQL：
> SELECT tb.Property
> FROM [TABLE] tb
> WHERE model.Property LIKE N'value' OR N'value' like '%+model.Property+%'

Code:
> _table.Where(model => EF.Functions.Like(model.Property , "%value%") || EF.Functions.Like("value", "'%'+model.Property +'%'"))

**Comment by smitpatel** [comment]
Don't write `model.Property` inside quotes. You essentially passed in a string rather than expression from lambda parameter hence invalid.

Correct way to write the query
```C#
var query = db.Blogs
    .Where(model =>
        EF.Functions.Like(model.Property, "%value%")
        || EF.Functions.Like("value", "%" + model.Property + "%"))
    .ToList();
```
Generates SQL
```SQL
      SELECT [model].[Id], [model].[Property]
      FROM [Blogs] AS [model]
      WHERE [model].[Property] LIKE N'%value%' OR N'value' LIKE (N'%' + [model].[Property]) + N'%'
```
