### ISSUE TITLE
EF Core 2.1.1 (sometimes) generates shadow properties for foreign key relations defined inside owned classes

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12680]
Hi,

I have been using foreign key relationships inside owned classes for a while now and, without any reason, EF started to emit shadow properties for foreign keys even though the relationship is fully defined.

So I end up with a table with two columns (one with the right name, and one with the generated name) and two foreign keys (one with the right name, and one with the generated name)

The strange case is though that this behavior is not consistent. Some owned classes with foreign key relationships are generated the right way (one column, one foreign key) which leads me to the fact that it's impossible to supply anything useful to you guys you can work with to find out what's going on here.

I did look at the debug view of the entity builder and I indeed saw the generation of the shadow property

For completeness ... I generate most relationships like this

`
builder.HasOne(self => self.RelatedType).WithMany().HasForeignKey(self => self.RelatedTypeId).HasConstraintName("SomeFKName").OnDelete(DeleteBehavior.ClientSetNull);
`

NOTE: the "builder" is a **ReferenceOwnershipBuilder<.>** 

### Further technical details
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprise 2017 15.7.5

TIA

Bert

**Comment by divega** [comment]
@amoorthaemer have you noticed a change in the behavior in any specific version? I understand it is difficult, but it would really help a lot if you could provide a repro, even if it repros only sometimes.

@AndriySvyryd, thoughts?

**Comment by smitpatel** [comment]
Inconsistency could arise if the Owned Types are MEST.

**Comment by amoorthaemer** [comment]
Hi ... indeed that was the case ... removed the properties and now my database is generated correctly ... thanks for the help :)

**Comment by amoorthaemer** [comment]
Sorry forgot to close this ...
