### ISSUE TITLE
many-to-many relationships without a joining entity

### ISSUE THREAD

**Issue by zanate4019** [dotnet/efcore#12704]
I know this probably gets asked a lot, but is adding support for many-to-many relationships without a joining entity on the roadmap?  If so where?

Jason

**Comment by Diaskhan** [comment]
How do u imagine many to many withour midle entity ? 

By concept many many must use 3 entity !

**Comment by zanate4019** [comment]
It does currently in EF 6.x and previous versions of EF as well as in Resharper. I know linking tables are necessary in relational databases for many-to-many relationships, but they dont make a lot of logical in entities.

**Comment by Diaskhan** [comment]
The ef core is some kind new orm library! I think they not gona do some incorect errorrs in conceptual architecture!

**Comment by Diaskhan** [comment]
Could U create ERD diagram with table relationship ?
The Third table is need not for modern-fashionable style. 3 table is justified for perfomance and oprtimization purposes!

The current Firebird version database actually still read all space from Disk.
3-rd table this some kind compromise of perfomance vs comfortable usage!

**Comment by divega** [comment]
@zanate4019 to your question, the work item for this is https://github.com/aspnet/EntityFrameworkCore/issues/10508.
