### ISSUE TITLE
EF generates different SQL queries for expressions with type conversion using () operator vs 'as' operator

### ISSUE THREAD

**Issue by RoshanJeewantha** [dotnet/efcore#12717]
The generated SQL queries are different for an expression with type conversion using () operator vs. an expression with 'as' operator.

Please refer to the following code snippets and relevent log outputs.

**Code**
```
context.Set<Animal>().Where(x => x is Dog && ((Dog)x).Name == "Woof").ToList();
```
**Output**
```
 SELECT [x].[Id], [x].[AnimalType], [x].[Name]
 FROM [Animal] AS [x]
 WHERE [x].[AnimalType] IN (3, 2, 1) AND (([x].[AnimalType] = 3) AND ([x].[Name] = N'Woof'))
```

**Code**
```
context.Set<Animal>().Where(x => x is Dog && (x as Dog).Name == "Woof").ToList();
```
**Output**
```
SELECT [x].[Id], [x].[AnimalType], [x].[Name]
FROM [Animal] AS [x]
WHERE [x].[AnimalType] IN (3, 2, 1) AND ([x].[AnimalType] = 3)
```

### Steps to reproduce
Repro included at https://github.com/avinash-phaniraj-readify/EFCoreTestBed/tree/TypeConversionWithAsOperatorError

### Further technical details
EF Core version: 2.1
Database Provider: EntityFrameworkCore.SqlServerCompact35
Operating system: Windows 10.0.17134
IDE: Visual Studio 2017 15.7.4

**Comment by smitpatel** [comment]
`as` operator is not server translated hence when you use it in Where, it will be evaluated on client hence missing in SQL.

**Comment by optiks** [comment]
@smitpatel Is this by design, or has it just not been implemented yet? If the latter, is there a backlog item tracking this?

**Comment by RoshanJeewantha** [comment]
@smitpatel thanks for you response. I understand why it is not there (technically), but it is more of why it has to be like that (rationale) as @optiks mentioned.
