### ISSUE TITLE
IDE1002 - Analyzer assemblies conflicting identity between 2.1-rc1-final and 2.1 rtm

### ISSUE THREAD

**Issue by Antaris** [dotnet/efcore#12719]
Hi, 

I'd previously had the `2.1-rc1-final` build, and upgraded to RTM on release. Since then, I've had these errors appear in my build output in Visual Studio.

They are not failing errors, the build still completes. I no longer have the `2.1.0-rc1-final` bits installed, am I safe to remove the analyzers manually from `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.analyzers\2.1.0-rc1-final`?

> Analyzer assemblies 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.analyzers\2.1.0\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll' and 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.analyzers\2.1.0-rc1-final\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll' both have identity 'Microsoft.EntityFrameworkCore.Analyzers, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' but different contents. Only one will be loaded and analyzers using these assemblies may not run correctly.

This *may* be caused by transient dependencies still having dependencies on the `2.1.0-rc1-final` bits?

**Comment by divega** [comment]
@Antaris do you have any mixed versions of dependencies? E.g. if you are still using ASP.NET Core 2.1 RC1 and upgrade only EF Core you could end up getting both versions of the analyzer. Also, you may just need to remove the RC1 version of the .NET Core SDK or runtime.

**Comment by Antaris** [comment]
@divega Yeah I have a couple of transients that have dependencies on RC1-bits, I'll see about upgrading them to the RTMs and see that sorts it. I've already removed the RC1 sdk
