### ISSUE TITLE
Migrations: k ef migration apply should throw when unsuccessful 

### ISSUE THREAD

**Issue by lukewaters** [dotnet/efcore#1272]
When the connection string is invalid (i.e. no database is specified), the command `k ef migration apply` should return a failure message.  Currently it just prints the message `The database is up to date.`

**Comment by bricelam** [comment]
@lukewaters The default behavior of SqlClient is to use `master` if a database is not specified. The migrations are successfully applied there. :)

**Comment by lukewaters** [comment]
My issue with this behavior, is that, while migrations don't throw, and are applied to 'master', DbContext does throw and EntityFramework will not allow an application to run without a database specified in the connection string.  We need to be consistent here.

**Comment by bricelam** [comment]
Interesting. Could add an example of the inconsistency to the bug?

**Comment by lukewaters** [comment]
closing as no repro

**Comment by lukewaters** [comment]
bad default behavior for sqlclient is tracked as #1571
