### ISSUE TITLE
Migrations does not properly work with calculated properties

### ISSUE THREAD

**Issue by iamkarlson** [dotnet/efcore#12726]
I have a computed column for remaining amount. It's calculated as total amount minus amount. So, it has public getter and unavailable setter declared as 
``` c#
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public virtual decimal RemainingAmount {
  get => TotalAmount - Amount;
  internal set { }
}
```

So, when I'm adding a migration, without any additional manipulation it gets me an SQL error of the dependency this computed column on altering column.

I tried to manually add dropping and creation:

``` c#
            migrationBuilder.DropColumn(
                name: "RemainingAmount",
                table: "Orders");

            migrationBuilder.AlterColumn<decimal>(
                name: "Amount",
                table: "Orders",
                type: "DECIMAL(18,3)",
                nullable: false,
                oldClrType: typeof(decimal));

            migrationBuilder.AddColumn<decimal>(
                name: "RemainingAmount",
                table: "Orders",
                type: "DECIMAL(19,3)",
                nullable: false,
                computedColumnSql: "[TotalAmount] - [Amount]");

```
SQL profiled doesn't indicate that EF is trying to drop that column. Do I miss anything? How do I have to instruct EF to drop that column before altering main one? 

### Further technical details
EF Core version: 2.1.1

**Comment by bricelam** [comment]
I think fixing #6853 was the most we could do for computed columns without actually parsing the SQL (a complexity we desperately wish to avoid).

Manually rebuilding the computed column in the migration is the correct way to handle this. I was able to make this work locally. Hard to say what went wrong. Perhaps you forgot to save the migration after editing it?

**Comment by iamkarlson** [comment]
Hi @bricelam 
Thank you for your efforts! I don't think that I can recall anything from what was happening more than a year ago. However, I do remember that I used a workaround with a direct SQL script. Also, I think it's a good idea to close this ticket since I have no usage of it anymore. Please reopen it if you think that would be appropriate.
