### ISSUE TITLE
Query: Consider adding method to force client evaluation of an expression

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12736]
The fix for https://github.com/aspnet/EntityFrameworkCore/issues/12697 enables using a method defined like this in a query:

``` c#
public static T Client<T>(T s) => s;
```

The point being that the method is opaque to our query translator and therefore forces client evaluation.  I want to suggest that we consider adding a method like that somewhere under the static EF class for better discoverability. 

I haven't tested how well it works and I am not sure I understand all the implications but ideally this could be used both on the way in (to force funcletization of an expression that would otherwise be translated, i.e. a shortcut for having to write the expression outside the query) and on the way out (force client evaluation of an expression that would otherwise be translated).

Example usage:

``` c#
                var data = (from c in db.Checks
                                 join ct in db.CheckTemplates
                                      .Include(a => a.Implementers).ThenInclude(u => u.User)
                                 on c.CheckTemplateId equals ct.CheckTemplateId
                                 where c.CheckId == checkId
                                 select new
                                 {
                                     CheckId = c.CheckId,
                                     Description = ct.Description,
                                     Implementers = EF.Client(ct).Implementers,
                                     NumExaminers = ct.Examiners.Count
                                 };
```

**Comment by pmiddleton** [comment]
Could users misunderstand the feature and try passing a lambda to the Client method that references column data?  That won't be executable client side.

**Comment by divega** [comment]
@pmiddleton that is a reason to come up with a good name. Worst case that would cause N+1 queries (or throw).

**Comment by ajcvickers** [comment]
Tracking this as part of 3.0 query behaviors, so added to #12795
