### ISSUE TITLE
trying to use Add New Scaffolded Item

### ISSUE THREAD

**Issue by rentekcon** [dotnet/efcore#12744]
I select the one of the models that was generated and I press add, it runs a while then I get the following error:

There is an error running the selected code generator:
'Method not found: 'Void
Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations..ctor
(Microsoft.EntityFramworkCore.Design.Internal.OperationReporter,System.Reflection.Assembly,
System.Reflection.Assembly)'

That's all I get is a dialog box with this information, and I can only select OK.

### Steps to reproduce
I am taking the course Extend your Application with REST Services and I am in the section Create a WebAPI Data Access Layer -> Create WebAPI Project > Generate the WebAPI Controllers.

I created a new project and selected API.
Built the application the valuesController was created and it does show the values1, values2 when I bring up the app. 
Then I went to the Nuget Console and
Install-Package Microsoft.EntityFrameworkCore.SqlServer
Install-Package Microsoft.EntityFrameworkCore.Tools

Both were successful.
Then I ran the following:
Scaffold-DbContext "{MY-CONNECTION-STRING}" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

I added the connectionstring from the app.config

Then I tried to scaffold one of the models that was created and I got the above message.

Any help would be greatly appreciated.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
Using C#
EF Core version: (found in project.csproj or packages.config)
not sure what you are looking for: <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.19.8" targetFramework="net471" />
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system:  Windows 10
IDE: 
Microsoft Visual Studio Community 2017 
Version 15.7.5
VisualStudio.15.Release/15.7.5+27703.2042
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

ASP.NET and Web Tools 2017   15.0.40625.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40608.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40608.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.8.3-beta6-63029-08. Commit Hash: e9a3a6c0ba5b1fde8b1fff964bdfb3fb768ee2eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.7.18156.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.2
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.7.18156.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.7.18156.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.7.18156.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.7.18156.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-63029-08. Commit Hash: e9a3a6c0ba5b1fde8b1fff964bdfb3fb768ee2eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.2042
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

**Comment by ajcvickers** [comment]
@rentekcon We're having trouble understanding what is going on with just the info here. Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment]
@rentekcon It would be much more useful if you could create a minimal project/solution that demonstrates the behavior you are seeing. This should not have to depend on any passwords or other secrets.

**Comment by rentekcon** [comment]
Yes, that is what I was thinking too. I have an example that I might be able to use.

Thanks,
Renee
    On ‎Wednesday‎, ‎August‎ ‎01‎, ‎2018‎ ‎02‎:‎46‎:‎03‎ ‎PM‎ ‎MST, Arthur Vickers <notifications@github.com> wrote:  
 
 
@rentekcon It would be much more useful if you could create a minimal project/solution that demonstrates the behavior you are seeing. This should not have to depend on any passwords or other secrets.

**Comment by rentekcon** [comment]
The information in the output window is:

Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Patients'
Method not found: 'Void Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations..ctor(Microsoft.EntityFrameworkCore.Design.Internal.IOperationReporter, System.Reflection.Assembly, System.Reflection.Assembly)'.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

Does that help at all?

**Comment by rentekcon** [comment]
I have attached the files to recreate the problem. The database is in the C:\SQLServer Directory.
I right click on models, click add then click scaffolded Item and get the errors above.
[ProblemDemo.zip](https://github.com/aspnet/EntityFrameworkCore/files/2251579/ProblemDemo.zip)

**Comment by rentekcon** [comment]
I zipped the db in the main dir of the zip.

**Comment by ajcvickers** [comment]
@rentekcon This issue seems to be using a combination of packages from ASP.NET Core 2.0 and 2.1. Specifically, the two EF packages you installed explicitly are 2.1 versions, which the rest of the app is using ASP.NET Core 2.0. When I downgraded the EF packages to 2.0 things started working. You might instead want to use ASP.NET 2.1 throughout.

**Comment by rentekcon** [comment]
How do I do that?

**Comment by divega** [comment]
@rentekcon see https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1.

**Comment by rentekcon** [comment]
Thanks! I thought I did this, I guess not.
