### ISSUE TITLE
Add feature so that model properties can have an attribute to "override" built in conversion of .NET to SQL types

### ISSUE THREAD

**Issue by ImGonaRot** [dotnet/efcore#12754]
EF 6 "assumed" that all .NET DateTime properties should be converted into SQL DateTime2 data types when using SQL 2008+.
https://github.com/aspnet/EntityFramework6/issues/578

It would be nice if the person building the .NET models could "override" this "automatic" conversion by adding attributes to their .NET properties.
This way they have more control of the SQL data types.

Maybe EF Core could add this feature?

Something like this.
```
[Column(TypeName ="datetime2")]
public DateTime TestDate { get; set; }

[Column(TypeName ="datetime")] // Not needed by default
public DateTime AnotherTestDate { get; set; }
```

**Comment by amoorthaemer** [comment]
Hi,
It’s already there ... see https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types#data-annotations

Cheers

**Comment by ImGonaRot** [comment]
@amoorthaemer 
EF 6 also had a "Column / TypeName" attribute for the Data Annotations but it seems to ignore the "TypeName".
Which is why I can't use it with SQL 2016.

Anyway, thanks for the information link.

**Comment by divega** [comment]
@ImGonaRot if you have provide a repro that shows EF Core ignoring ColumnAttribute.TypeName please re-open. That shouldn't be the case.
