### ISSUE TITLE
SaveChangesAsync() doc page

### ISSUE THREAD

**Issue by etrigoco** [dotnet/efcore#12751]
Check out: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?view=efcore-2.1

Says signature for SaveChangesAsync is

`public virtual System.Threading.Tasks.Task<int> SaveChangesAsync (System.Threading.CancellationToken cancellationToken = null);`

If you try overriding SaveChangesAsync using the above example, it'll give you the following error:

![image](https://user-images.githubusercontent.com/14839910/43035677-92c77984-8cf4-11e8-9318-2aac3e55e7af.png)

Using `default(CancellationToken)` instead of `null` solves the issue:
`public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))`

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/EntityFramework.ApiDocs/issues/25
