### ISSUE TITLE
OnModelCreating and seed data

### ISSUE THREAD

**Issue by xanatos** [dotnet/efcore#12769]
In the OnModelCreating, how can I check if I need to generate the seed data? Because in the examples given the seed data is always generated "in memory", like:

```
modelBuilder.Entity<Post>().HasData(
    new {BlogId = 1, PostId = 1, Title = "First post", Content = "Test 1"},
    new {BlogId = 1, PostId = 2, Title = "Second post", Content = "Test 2"});
```

(taken from https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)

here the `new { }` are always executed every time the program is run and then, if I'm doing a migration it is saved (even here, unclear exactly in which case, only if I'm doing an `Add-Migration` from PowerShell? because if I do a `context.Migrate()` I think the data is taken from the `SomeMigrationClass.BuildTargetModel(ModelBuilder modelBuilder)`).

**Comment by ajcvickers** [comment]
@xanatos The seed data becomes part of the model and is inserted or updated in the database as needed when migrations are applied. So you don't try to decide when you need to generate it, you just add it to the model and then let migrations take care of it.
