### ISSUE TITLE
ef core question re: reversing a custom migration

### ISSUE THREAD

**Issue by githubfanster** [dotnet/efcore#12789]
Describe what is not working as expected.
this is a QUESTION ONLY
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
following the example in 
https://www.ryansouthgate.com/2017/05/22/entity-framework-core-custom-migrations/

i was able to create a CustomMigration.cs file that looked like ryan's code in:
https://github.com/ry8806/Blog-EFCore-CustomMigration/blob/master/EFCustomMigrations/Db/CustomMigrations/CustomerLocationMigration.cs
``` csharp
   [DbContext(typeof(ApplicationDbContext))]
    [Migration("CustomMigration_MyAdditions")]
//currently, with only one other migration (an init migration)
//this migration gets correctly executed AFTER that init migration
    public class MyAdditionsMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("..add a Postgresql check constraint to a created table.");
        }
       protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("..reverse of what was done in Up.; for example drop the Postgresql check constraint for a created table if the constraint already exists");
        }
}
```
when i did the following in the command prompt:

dotnet ef migrations add init
dotnet ef database update

Ef Core created a  <timestamp>_init.cs  and the other expected designer and snapshop files (so a total of just 3 files).

the <timestamp>_init.cs  contains migration code that did not include the migration code in my CustomMigration.cs file, but the database update  did create the Postgresql check constraint I needed to add to one of my tables, so that's my proof that the dotnet ef commands i executed DID PICK UP MY CUSTOM MIGRATION.

MY QUESTION:
Suppose I want to REVERSE my custom migration, what CLI command or other means would do this for me?

dotnet ef migrations remove did not do it for me. 

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Npgsql.EntityFrameworkCore.Postgresql
Operating system: 
IDE: Visual Studio 2017 15.7.7

**Comment by githubfanster** [comment]
so if the only other migration is an "init" migration, and the "last migration" is my custom migration, i can reverse my custom migration by doing:

dotnet ef database update init

so my FOLLOW-UP QUESTION IS:

the approach discussed in ryan's article (referenced in my first post) puts custom migration class file(s) under a CustomMigrations folder in the project containing the ApplicationDbContext.cs file.

i did not have to do any kind of

dotnet ef migrations add custom_blah

for my custom migrations.

a "dotnet ef database update" just seems to pick up all my custom migrations and these custom migrations seem to execute as the last set of migrations.  and also, apparently, by naming my custom migrations "systematically", i can get them executed in the order i want (migration named [Migration("CustomIShouldBeFirst")] executes before [Migration("CustomIShouldBeSecond"], etc).

WHAT IF I want to reverse only one or a few of my specific custom migrations?
How to do this ??
What's the suggested tactic or approach???

Thanks for helping!

**Comment by bricelam** [comment]
Here are the docs on [Removing and Reverting EF Core Migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#removing-a-migration). To rollback all migrations (or go back to the initial database), use `0` as the migration name.

You can also undo the changes of a previous migration by creating a new migration. This approach is better in team environments where re-writing the migrations history (e.g. removing a migration) will cause problems for other team members.

**Comment by githubfanster** [comment]
Thanks for replying. 

I think your advice to just write another migration to reverse my own custom migrations might work.

I wonder if I could ask follow-up questions just to satisfy my own curiosity.

The original problem:

There are certain things EF Core cant do for me that requires me to go down the custom migration / custom sql path.

These custom migrations would always have to be executed last to make sure the tables I'm adding constraints to have been created.

Because I already know what these custom migrations would have to do, I write them in advance by creating subclasses of Migration, annotating them with the DbContext and Migration attributes (e.g., [DbContext(typeof(AppDbContext))] and [Migration("CustomMigrationNameForEFMigrationsHistoryTable")], and putting them in a CustomMigrations folder inside my data project that contains my AppDbContext class, etc.

The name I'm giving to the Migration attribute does not conform to the expected pattern of xxxxxxxxxxxxxx_name where the xxxxxxxxxxxxxx represents a timestamp, and consequently, this could be the reason why i cannot refer to my custom migrations by name.

So I was wondering: 

Could I utilize some sort of naming trick that would enable me to refer to my individual custom migrations by name, like so:

yyyyyyyyyyyyyy_myfirstcustommigration     
zzzzzzzzzzzzzz_mysecondcustommigration

where yyyyyyyyyyyyyy and zzzzzzzzzzzzzz are guaranteed to always be greater than the last timestamp stored in the _EFMigrationHistory table (maybe they always start in the year 2058xxxxxxxxxx)?

would this trick then allow me to refer to my custom migrations by name such as myfirstcustommigration and mysecondcustommigration :-)

thanks for tolerating my questions :-)

**Comment by bricelam** [comment]
Why do you want to keep these migrations last? The normal workflow is just to edit the migration that adds the table (or immediately add another migration) that adds the additional constraints.

Think of it like using version control with your source code. You don't typically try to keep a specific changesets/commits at the tip. It's incredibly tedious and usually unnecessary.
