### ISSUE TITLE
Unable to perform a partial update

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12791]
Hi,

If recall correctly EF 6.x was able to do a partial updates. I tried the same scenario for EF Core, but the generated UPDATE statement includes all columns and therefore fails on a required column.

My question: Will the EF 6.x behavior on updates be part of EF Core?

TIA

Bert

**Comment by smitpatel** [comment]
EF Core does partial updates. Please provide a repro code to demonstrate behavior you are seeing.

**Comment by amoorthaemer** [comment]
Won’t be until tomorrow ... it’s almost 11 in the evening here. But I will send a repro

**Comment by amoorthaemer** [comment]
Hi,

Hereby the repro ...

`
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;

namespace TestEFCorePartialUpdates {
	class Entity {
		public long Id { get; set; }
		public string Name { get; set; }
		public int Value { get; set; }
	}

	class EntityContext: DbContext {
		public DbSet<Entity> Entities { get; set; }

		public EntityContext() : base() { }

		protected override void OnConfiguring(DbContextOptionsBuilder builder) {
			base.OnConfiguring(builder);
			builder
				.UseLoggerFactory(new LoggerFactory(new[] { new DebugLoggerProvider((_, __) => true) }))
				.UseSqlServer("{YOUR CONNECTION STRING}")
				.EnableSensitiveDataLogging(true);
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder) {
			modelBuilder.Entity<Entity>(b => {
				b.HasKey(p => p.Id).ForSqlServerIsClustered();

				b.Property(p => p.Id).ValueGeneratedOnAdd()
					.IsRequired(true);

				b.Property(p => p.Name)
					.HasMaxLength(20)
					.IsRequired(false);

				b.HasData(new {
					Id = 1L,
					Name = "TEST",
					Value = 0
				});
			});
		}
	}

	class Program {

		static async Task Main(string[] args) {
			using (var context = new EntityContext()) {
				await context.Database.EnsureDeletedAsync();
				await context.Database.EnsureCreatedAsync();

				var entity = new Entity() {
					Id = 1,
					Value = 2
				};

				var entry = context.Entry(entity);
				entry.Property(p => p.Value).IsModified = true;

				context.Update(entity);

				await context.SaveChangesAsync();
			}
		}
	}
}
`

Logging ...

Microsoft.EntityFrameworkCore.Database.Command:Debug: Executing DbCommand [Parameters=[@p2='1', @p0='' (Size = 4000), @p1='2'], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [Entities] SET [Name] = @p0, [Value] = @p1
WHERE [Id] = @p2;
SELECT @@ROWCOUNT;
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (87ms) [Parameters=[@p2='1', @p0='' (Size = 4000), @p1='2'], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [Entities] SET [Name] = @p0, [Value] = @p1
WHERE [Id] = @p2;
SELECT @@ROWCOUNT;

I can clearly see the "Name" column added to the UPDATE statement ... Which is not want I expect ...

Cheers

Bert

**Comment by amoorthaemer** [comment]
Ah! I think I made it problematic for myself ... I need to use Attach icm SaveChanges and remove the Update ... Sory guys ...
