### ISSUE TITLE
How to set the "encoding" of a field when "code first" is used with "mysql"

### ISSUE THREAD

**Issue by czd890** [dotnet/efcore#12809]
database default encoding “utf-8”

There is a field that needs to be modified to encoding "utf-8mb4".

How to do it with "code first"？

**Comment by ajcvickers** [comment]
@AndriySvyryd This looks related to an area you were looking at.

**Comment by AndriySvyryd** [comment]
You should be able to do it with something like `.HasColumnType("longtext CHARACTER SET utf-8mb4")`
