### ISSUE TITLE
Disabling "Sqlite:Autoincrement" annotation while preserving `ValueGeneratedOnAdd()`

### ISSUE THREAD

**Issue by Deilan** [dotnet/efcore#12811]
### Question / Problem

Is there a convenient way to get rid of "Sqlite:Autoincrement" annotation while preserving the implicit or explicit `ValueGeneratedOnAdd()` behavior?

### Context

I have an entity with an integer primary key:
```csharp
public class Student
{
    public int? Id { get; set; }

    /* the rest omitted for brewity */
}
```
and an entity type configuration for that:
```csharp
public sealed class StudentConfiguration : IEntityTypeConfiguration<Student>
{
    public void Configure(EntityTypeBuilder<Student> builder)
    {
        builder.HasKey(i => i.Id);

        /* the rest omitted for brewity */
    }
}
```

I use `Microsoft.EntityFrameworkCore.Sqlite` provider. When it comes to migration, here's what I have upon adding a migration with this entity:
```csharp
public partial class AddStudents : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Students",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false)
                    .Annotation("Sqlite:Autoincrement", true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Students", x => x.Id);
            });
        /* the rest omitted for brewity */
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "Students");

        /* the rest omitted for brewity */
    }
}
```

As a result I have an unwanted `"Sqlite:Autoincrement"` annotation for `Id` column.

### What I've tried so far

1. Using `ValueGeneratedNever()` on the property removes the unwanted annotation, but Entity Framework then refuses to save an entity without explicit provision of `Id` value.

```csharp
public sealed class StudentConfiguration : IEntityTypeConfiguration<Student>
{
    public void Configure(EntityTypeBuilder<Student> builder)
    {
        builder.HasKey(i => i.Id);
	builder.Property(i => i.Id).ValueGeneratedNever()

        /* the rest omitted for brewity */
    }
}
```

2. Explicit call `HasAnnotation("Sqlite:Autoincrement", false)` on the property doesn't have an effect at all:
```csharp
public sealed class StudentConfiguration : IEntityTypeConfiguration<Student>
{
    public void Configure(EntityTypeBuilder<Student> builder)
    {
        builder.HasKey(i => i.Id).HasAnnotation("Sqlite:Autoincrement", false);
	builder.Property(i => i.Id).HasAnnotation("Sqlite:Autoincrement", false);

        /* the rest omitted for brewity */
    }
}
```

### Possible workaround

I am aware of possibility of removing the annotation manually from the generated code such that it would look like this:
```csharp
migrationBuilder.CreateTable(
    name: "Students",
    columns: table => new
    {
         // manually removed Annotation("Sqlite:Autoincrement", true)
        Id = table.Column<int>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Students", x => x.Id);
    });
```

But because it involve manual editing, this approach is error-prone.

### Motivation
Sometimes I need to insert a row with `Id` supplied by the client. But when `Id` is not supplied, then I need to use a regular insert with a generation of `Id` by the database.

It's legit as per official documentation on [SQLite Autoincrement](https://www.sqlite.org/autoinc.html) feature:
> 1. The AUTOINCREMENT keyword imposes extra CPU, memory, disk space, and disk I/O overhead and should be avoided if not strictly needed. It is usually not needed.
> 2. In SQLite, a column with type INTEGER PRIMARY KEY is an alias for the ROWID (except in WITHOUT ROWID tables) which is always a 64-bit signed integer.
> 3. On an INSERT, if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use. This is true regardless of whether or not the AUTOINCREMENT keyword is used.
> 4. If the AUTOINCREMENT keyword appears after INTEGER PRIMARY KEY, that changes the automatic ROWID assignment algorithm to prevent the reuse of ROWIDs over the lifetime of the database. In other words, the purpose of AUTOINCREMENT is to prevent the reuse of ROWIDs from previously deleted rows.

### Further technical details
EF Core version: 2.1.1-rtm-30846
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows_NT x64 10.0.17134
IDE: Visual Studio 2017 15.7.5

**Comment by bricelam** [comment]
We prefer AUTOINCREMENT so that database-generated values aren't recycled. Here's a scenario where things can go wrong without it:

Step | Client 1 | Client 2
--- | --- | ---
1 | Query, get Id = 1 | Query, get Id = 1
2 | Remove where Id = 1
3 | Add, re-generates Id = 1
4 | | Update where Id = 1. Should throw, but instead updates the wrong row

**Comment by bricelam** [comment]
#10228 will make removing it easier

**Comment by ajcvickers** [comment]
Triage: closing this in favor of #10228, which will enable doing this if really needed.
