### ISSUE TITLE
Always allow navigation properties to be optional, even when foreign key is not nullable

### ISSUE THREAD

**Issue by yringler** [dotnet/efcore#12814]
As per the [official documentation](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#required-and-optional-relationships), the required-ness of a navigation property is controlled by the nullability of the foreign key.

In #6177, resolved in #6225, it was established that even if the foreign key is not nullable, the primary entity still has an optional relationship with the secondary entity, and navigation from primary to secondary results in a left join.

I suggest further that there should be a way to define non-nullable foreign keys as being optional in all directions, perhaps via IsRequired(false).

Here is an approximate explanation of my use case:

In my company, we have a permissions table which has a clientId column. The client id always has a value, and refers to a client on a clients table.  _However,_ it could be that the client is no longer with us, in which case we don't store his information in the clients table.

In effect, what we have is a foreign key which isn't null, and shouldn't/couldn't be null (as it always has a proper value), but describes an _optional_ relationship. But because of the [above referenced convention](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#required-and-optional-relationships), it is considered required, and generates an inner join, causing wanted data not to be retrieved.

Currently, I'm using a work-around wherein I use the foreign key as the primary key using HasPrincipalKey() and use the primary key on the client table as a foreign key. This causes a query of permissions to load contacts with an inner join, as per #6225.

This suggestion is as per my use case, and also in keeping with the spirit of flexibility, extensibility, and configurability which EF core is known for.

**Comment by ajcvickers** [comment]
@yringler So presumably this is not defined as a foreign key constraint in the database, otherwise "The client id always has a value, and refers to a client on a clients table. However, it could be that the client is no longer with us, in which case we don't store his information in the clients table." describes a referential constraint violation for which the database should generate an error.

**Comment by yringler** [comment]
Correct, it's not defined as a foreign key.

**Comment by yringler** [comment]
When describing a relationship with fluent syntax, EF core allows any property to be called a primary or foreign key.
I understand this as being a tacit allowance for describing "relationships" in a high level way, without being limited to the rigid constraints of a database.

Which is great; in general, the reason why any ORM exists is to make it easier for the developer to access information, not because there's some sort of empirical imperative, a law of nature if you will, that database schema must be replicated in programming environments.
In particular, the reason I define navigation-properties is to make it easier for me to access related information which I need, not because there happens to be a column in the DB which is defined as a foreign key. 

To conclude, two points:

- EF core supports pragmatic, non DB-defined relationships.
- A logical extension of that is supporting optional "foreign keys" which are non-nullable.

**Comment by AndriySvyryd** [comment]
This would require https://github.com/aspnet/EntityFrameworkCore/issues/13146

**Comment by yringler** [comment]
I think this issue is replaced by #13146, and should be closed.
@ajcvickers, is that correct?

**Comment by ajcvickers** [comment]
@yringler Correct--thanks!
