### ISSUE TITLE
Create a consistent relational model API

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#12846]
Add a new API that allows to configure and read relational mapping information. Adding this abstraction layer would allow to make the mapping more flexible and the implementation more efficient without additional changes to the consumers.

Some examples of queries that would benefit from this:
- Get all columns for a table
- Get all entity types mapped to a table
- Get all properties mapped to a column
- Get the database object that a navigation/relationship is mapped to

New mapping scenarios that this would be allow:
- Mapping an entity type to more than one table
- Different relational configuration for properties mapped to more than one column
- Different mapping for migrations, query and update pipeline

Tasks:
- [x] Add metadata implementation
- [x] Port migrations
- [x] Port update pipeline
- [x] Port query

**Comment by AndriySvyryd** [comment]
These are the entity type mappings that can be potentially used for an aspect of EF:

|  | Table | View | Def Query | Sproc | UDF | Nothing |
|---------------|-------|------|-----------|-------|-----|---------|
| **Migrations** |  ✔️  | ✔️ |  | ✔️ | ✔️ | ✔️ |
| **Query** | ✔️ | ✔️ | ✔️ |  | ✔️ |  |
| **CUD** | ✔️ |  |  | ✔️ |  | ✔️ |
| **Bulk CUD** | ✔️ |  |  |  |  | ✔️ |
| **Scaffolding** | ✔️(no hierarchy) | ✔️ |  | ✔️ |  |  |

With table mapping being any of the following:

- 1 to 1
- TPH
- TPT
- TPC
- Inherited (PostgreSQL)
- Table splitting
- Entity splitting

**Comment by AndriySvyryd** [comment]
# The core design:
![image](https://user-images.githubusercontent.com/6539701/74369647-904ccf80-4d8a-11ea-835e-4c4cfe99e277.png)

## This is how the metadata objects will look for each type of mapping:
### TPH
![image](https://user-images.githubusercontent.com/6539701/74369549-6abfc600-4d8a-11ea-8d44-5efeab3af4b3.png)
### TPC
![image](https://user-images.githubusercontent.com/6539701/74369769-cab66c80-4d8a-11ea-97ec-d87d09328345.png)
### TPT
![image](https://user-images.githubusercontent.com/6539701/74369816-e3268700-4d8a-11ea-8257-f178c52213c2.png)
### Table inheritance
![image](https://user-images.githubusercontent.com/6539701/74369857-f46f9380-4d8a-11ea-9eea-02de21d28123.png)
### Table splitting
![image](https://user-images.githubusercontent.com/6539701/74369903-05b8a000-4d8b-11ea-9891-23df1eca7251.png)
### Entity splitting
![image](https://user-images.githubusercontent.com/6539701/74369926-136e2580-4d8b-11ea-8985-557d0a9756fd.png)

**Comment by roji** [comment]
While syncing EFCore.PG, ran into the breaking change in 3574cfbddfdf485548b9e217f8e01a5ffeaf8562 (IModelFinalizedConvention/IModelFinalizingConvention), consider opening a separate issue for that (or documenting) as it's provider-breaking.

**Comment by ajcvickers** [comment]
@roji I thought we talked about this and decided `providers-beware` was enough. What am I missing?

**Comment by roji** [comment]
Just that this is an extremely wide issue (maybe an epic really), and this convention change doesn't necessarily seem part of the relational model. If we feel this one issue should cover everything, maybe a small list of breaking changes on it would help track things?

**Comment by AndriySvyryd** [comment]
That's why it was changed in a separate PR https://github.com/dotnet/efcore/pull/19872
Do you normally look at fixed issues or PRs for `providers-beware`?

**Comment by roji** [comment]
Sometimes :) I do it occasionally when something breaks when I try syncing to the latest, to help understand what's going on. Not critical if you don't feel it's worth it.
