### ISSUE TITLE
SaveChanges(false) generates duplicates (possible bug?)

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12863]
Hi,

Using the following scenario I discovered that SaveChanges(false) adds duplicates to the database.
(Hooked into the Tracked an StateChanged events)

- Add an entity instance => "Tracked" reports: **Added**
- call SaveChanges(false)
- Add another entity instance of the same type as the first => "Tracked" reports: **Added**
- call SaveChanges() => "StateChanged" reports: **Added** to **Unchanged** (**for 2 entities**)
- Check the database ... Ergo ... **3 database records instead of 2**

I dont think this is the desired result? Or is it?

Cheers
Bert.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017 Enterprise latest

**Comment by ajcvickers** [comment]
@amoorthaemer This is by-design. When you tell EF to not accept all changes by passing `false` to SaveChanges, it means that EF won't automatically change the state of it's objects to reflect the changes made in the database. This means that the entity remains in the Added state even though it has been inserted into the database, and an attempt will be made to insert it again when SaveChanges is called again.

Typically, passing `false` to SaveChanges is only done when your code is attempting to save from multiple contexts using the same transaction. It then becomes your responsibly to call AcceptAllChanges once the transaction succeeds. If the transaction doesn't succeed, then the database changes didn't happen, so the context remains in a state where SaveChanges can be called again.
