### ISSUE TITLE
dotnet migration not working after upgrading to 2.1

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#12870]
In my authentication API, I have 2 dbContexts: IdentityDbContext and ConfigurationDbContext(IdentityServer4) pointing to the same database. 

In 2.0.7 I use to be able to run migrations like this:
`dotnet ef database update --context <dbcontext>`

for each dbcontext, but now after upgrading my application to 2.1.2 with   

`Microsoft.EntityFrameworkCore.Tools.DotNet ` 2.0.3

I'm getting this error:

> Devart.Data.Oracle.OracleException (0x80004005): ORA-00955: name is already used by an existing object
>    at â€ˆâ€€.â€‚â€€â€€â€â€€()
>    at â€ˆâ€€.()
>    at â€ˆâ€€.â€‚â€€â€€â€â€€()
>    at â€‡â€.(â€ˆâ€€ , Int32 )
>    at â€‡â€.â€‡â€â€€â€â€€(Int32 , â€ƒâ€ )
>    at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
>    at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
>    at Devart.Data.Oracle.OracleCommand.ExecuteNonQuery()
>    at â€…â€.ExecuteNonQuery()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> ORA-00955: name is already used by an existing object

because it is trying to recreate the EFMigrationsHistory__ table for the second dbcontext. 

Do i need to downgrade my application to 2.0.7?

**Comment by ajcvickers** [comment]
@capiono TThis looks like an issue with the Devart Oracle provider. Can you please file an issue with them.
