### ISSUE TITLE
Allow scaffolding of the DbContextModelSnapshot file

### ISSUE THREAD

**Issue by GZidar** [dotnet/efcore#12877]
Would it be possible to provide a way to scaffold the DbContextModelSnapshot file only from the database? That way, it would be possible to recover from a situation where the database is out of sync with the model.

We have the "dotnet ef dbcontext scaffold" command that will generate everything, what I am suggesting is a new command "dotnet ef snapshot scaffold" that does nothing else but create the snapshot file based on the current database structure.

**Comment by smitpatel** [comment]
What if, you used `dotnet ef dbcontext scaffold` then used `dotnet ef migrations add Init` and used the snapshot file from that first migration?

**Comment by GZidar** [comment]
Hi @smitpatel, thanks for your response. What you are suggesting there will work (and is part of the workaround we are using) but once it's run I need to delete the model files and the dbcontext files that were created during that process because I don't actually want EF to make changes to my existing codebase. What I am proposing would, ideally, not touch the existing models or dbcontext nor create any files except the snapshot file.

**Comment by GZidar** [comment]
If anyone is interested, this is how we are achieving this right now via a powershell script:

```
# Call the CLI tools to scaffold a new dbcontext and then perform an initial migration
dotnet ef dbcontext scaffold "data source=<your data source>;" Microsoft.EntityFrameworkCore.SqlServer --output-dir .\devTemp --context TempContext
dotnet ef migrations add devTemp --context TempContext --output-dir .\devTemp\Migrations

# Now do some string replacements to the snapshot file so it matches the proper namespaces 
(get-content .\devTemp\Migrations\TempContextModelSnapshot.cs) | foreach-object {$_ -replace "TempContext", "<your db context>"} | set-content .\devTemp\Migrations\TempContextModelSnapshot.cs
(get-content .\devTemp\Migrations\TempContextModelSnapshot.cs) | foreach-object {$_ -replace "Repository.devTemp;", "Repository;"} | set-content .\devTemp\Migrations\TempContextModelSnapshot.cs
(get-content .\devTemp\Migrations\TempContextModelSnapshot.cs) | foreach-object {$_ -replace "Repository.devTemp.Migrations", "Repository.Migrations"} | set-content .\devTemp\Migrations\TempContextModelSnapshot.cs
(get-content .\devTemp\Migrations\TempContextModelSnapshot.cs) | foreach-object {$_ -replace "Repository.devTemp.", "Repository."} | set-content .\devTemp\Migrations\TempContextModelSnapshot.cs

# delete everything from the local migrations folder and copy the snapshot file into it
Remove-Item .\Migrations\*.* -Force
Copy-Item .\devTemp\Migrations\TempContextModelSnapshot.cs .\Migrations\<your DbContextModelSnapshot>.cs

# delete the generated scaffolding created earlier
Remove-Item .\devTemp -Force -Recurse
```

The specific strings that you find and replace may differ for your project but this script is what is working for us to achieve this outcome.


Who knows, it may be useful for others as well.

**Comment by ajcvickers** [comment]
This is not something we are planning to implement, although we could revisit this decision based on more feedback from other customers. See also #1298
