### ISSUE TITLE
Migrations updates excluded DbContextModelSnapshot file

### ISSUE THREAD

**Issue by GZidar** [dotnet/efcore#12875]
If there is a copy of the DbContextModelSnapshot file in the project's file structure in a folder alphabetically before the migration output (even if it has been excluded from the project) the migrations command will find this file and update it instead of the one in the proper target folder.

This results in problems because the snapshot used by subsequent commands is no longer correct.

### Steps to reproduce

Assuming that the default target migrations folder is ./Migrations take a copy of the files in that folder and place them in a folder called ./AMigrations then open visual studio and exclude that folder from the project.

After having done this the project should build as per normal (if you don't exclude the folder the project will complain about the duplicate files)

Then return to the command line and run:

dotnet ef migrations add <something>

You will see that the migration files are created in the proper target folder but the DbContextModelSnapshot in the ./AMigrations folder has been updated.

The workaround is to place the excluded copies in a folder that is alphabetically after the target migration folder (eg. ./ZMigrations)

Other ef cli commands do not seem to have this problem.

### Further technical details

EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment]
@GZidar This discovery of the location to use is part of the design for Migrations. We discussed what we could do to avoid the situation that you describe, but since we don't have information on excluded files, there doesn't seem much we can do. The workaround you suggest seems reasonable, or alternately the files could be renamed.
