### ISSUE TITLE
System.Data.Entity.Database.SqlQuery<TElement> was really useful. Why is it not available in .NET Core?

### ISSUE THREAD

**Issue by jenergm** [dotnet/efcore#12887]
Dear all,

For .NET Core development and performance is quite important that we can run SQL Native queries and fill ViewModels directly.

We have created a lot of helpers in .NET Framework using that like this:
```C#
public IHttpActionResult FindPaged(MyViewModel dto)
{
    if (dto.sort == null) dto.sort = "NAME";
    if (dto.dir == null) dto.dir = "ASC";

    using (MyContext myContext = new MyContext())
    {
        StringBuilder sqlQuery = new StringBuilder();
        List<DbParameter> parameters = new List<DbParameter>();
        sqlQuery.Append("SELECT");
        sqlQuery.Append("    ID,");
        sqlQuery.Append("    NAME,");
        sqlQuery.Append("    CAPACITY,");
        sqlQuery.Append("    VERSION");
        sqlQuery.Append(" FROM MY_TABLE WHERE DISABLED = 0");
        if (!string.IsNullOrEmpty(dto.name))
        {
            parameters.Add(new OracleParameter("NAME", dto.name));
            sqlQuery.Append(" AND NAME LIKE '%' || #NAME || '%'");
        }
        if (dto.capacity != null)
        {
            parameters.Add(new OracleParameter("CAPACITY", dto.capacity));
            sqlQuery.Append(" AND CAPACITY >= #CAPACITY");
        }

        return Ok(myContext.Database.SqlQueryPage<MyViewModel>(sqlQuery.ToString(), dto, parameters).QueryPage());
    }
}
```

In that example, SqlQueryPage uses SqlQuery internally... I can run any query with any parameters and use any ViewModels matching.

Technical details:
- EF Core version: 2.1.1
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer or Oracle in the next future.
- Operating system: Windows 10 Pro
- IDE: Visual Studio 2017 Enterprise 15.7.5

Best regards,
Jener Garcia Menezes
System Architect at PROSEGUR S/A

**Comment by sdanyliv** [comment]
@jenergm, i suppose it’s just simple sample because i do not see any benefits of dynamic sql building versus linq queries. EF will create parameters and SQL without any problem.
```cs
public IHttpActionResult FindPaged(MyViewModel dto)
{
    using (MyContext myContext = new MyContext())
    {

        var query = myContext.MyTable.AsNoTracking().Where(t => !t.Disabled);
        if (!string.IsNullOrEmpty(dto.name))
             query = query.Where(t => t.Name.Contains(dto.Name));
        if (dto.capacity != null)
             query = query.Where(t => t.Capacity > dto.Capacity);
        if (dto.dir == null)
             query = query.OrderBy(t => t.Name);
        else
             query = query.OrderByDescending(t => t.Name);

        query = query.Skip(pageNumber * pagesSize).Take(pageSize);
        
        var result = query.Select(t => new MyViewModel
             {
                    Id = t.Id,
                    Name = t.Name,
                    Capacity = t.Capacity,
                    Version = t.Version
              });

        return Ok(result.ToList());
    }
}
```
And if you need some dynamic querying like ordering by different columns - there is DynamicLinq.

**Comment by jenergm** [comment]
Hi Svyatoslav Danyliv,

Thanks for answer and participate!
I have this option in my solution too. It was a simple example, sorry to didn't put a complex that we have. I simplificated that to become understandable. But you should know that some advanced queries are impossible to do with dynamic expressions and is so hard to DBAs creating indexes to that...
Most complex systems here use direct SQL Queries and we would like continuing using that.

Thanks in advance!

**Comment by sdanyliv** [comment]
@jenergm, you have several options before EF support this again.

1.  Use Dapper
    `MyContext.Database.GetDbConnection().Query...`
2. And if you want to continue with linq, try our [linq2db integration](
https://github.com/linq2db/linq2db.EntityFrameworkCore) which developed for complex linq queries. It will be easy for guys who know SQL very well.

**Comment by jenergm** [comment]
I understood... but we really would like something in EntityFrameworkCore as there is in EntityFramework of .NET Framework.

**Comment by ajcvickers** [comment]
@jenergm Is there some reason that [FromSql](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) with [QueryTypes](https://docs.microsoft.com/en-us/ef/core/modeling/query-types) doesn't work for you?

**Comment by ajcvickers** [comment]
@jenergm Not having to define query types in the model is tracked by #10753

**Comment by jenergm** [comment]
Hi Arthur,

Thanks for answer me!

I wish it can be possible in a next future version.

Cheers,

**Comment by d668** [comment]
any news?

**Comment by ErikEJ** [comment]
You can use this: https://github.com/aspnet/EntityFrameworkCore/issues/1862#issuecomment-451671168
