### ISSUE TITLE
Recreating child collection fails to update

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#12884]
I'm mapping DTOs to entities with child collections. The problem is mapper I'm using doesn't operate on an existing collection, but creates a new collection and copies values from old collection. How can I solve it? I was looking at `ChangeTracker.TrackGraph` but it doesn't seem to work.

https://stackoverflow.com/questions/45590265/automapper-confuses-changetracker
(I don't use AutoMapper though)

```
Exception message: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23505: duplicate key value violates unique constraint "PK_ProductBarcodes"
```

### Steps to reproduce

```c#
public class Order
{
    public int Id { get; set; }
    public ICollection<Product> Products { get; set; }
}

public class OrderDTO
{
    public int Id { get; set; }
    public ICollection<ProductDTO> Products { get; set; }
}

// Code

var order = DbSet.Find(id);
// assigns new collection to Products, Products are probably untracked now...
orderDto.Map(order);

DbContext.Update(order);
DbContext.SaveChanges();

```

### Further technical details
EF Core version: 2.1.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment]
@Thorgard It's hard to know for sure with just the snippets posted above, but my guess is that the new collection of Products is being put into the Added state and hence EF attempts to insert them all again. There are several different ways of dealing with disconnected entities like this and which is appropriate for you depends on exactly what you are trying to do. The [documentation for working with disconnected entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities) will hopefully point you in the right direction.

**Comment by Thorgard** [comment]
@ajcvickers thanks. I solved it by eager loading all navigation properties. This way changes are tracked. Not sure if this is the best solution for now but it does the trick.
