### ISSUE TITLE
DropColumnOperation should expose the Old Annotations of a column

### ISSUE THREAD

**Issue by AtomicBlom** [dotnet/efcore#12896]
While working on a custom SqlServerMigrationsSqlGenerator, I noticed that I was not able to access the annotations that were on the column before it was dropped in a DropColumnOperation. I had expected the annotations to be available on the operation similarly to how an AlterColumnOperation has the OldColumn property.

Ideally, when dropping a column, a scaffolded migration would expose a .OldAnnotation() method that would allow me to access annotations present on the column before it was removed.

To give a bit more context of what I'm trying to achieve, as part of our project, it was decided to store Enums as strings in our database for clarity, and we added Check constraints on our columns to ensure that only conforming strings could be entered into a database.

As these check constraints were tedious to manage, I've been writing some migration helper code to add annotations for the type of an enum, and the list of values to make up the check constraint, and this is working well for all operations except the DropColumnOperation, where I can't tell from the operation if a column has a constraint or not because the annotations are not exposed.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.4

**Comment by bricelam** [comment]
You should be able to subclass and replace the `SqlServerMigrationsAnnotationProvider` overriding `ForRemove(IProperty)` any annotations returned will be available on the `DropColumnOperation`.

**Comment by bricelam** [comment]
``` csharp
class MyMigrationsAnnotationProvider : SqlServerMigrationsAnnotationProvider
{
    public virtual IEnumerable<IAnnotation> ForRemove(IProperty property)
        => property.GetAnnotations().Where(a => a.Name == "MyEnumAnnotation");
}
```
``` csharp
dbContextOptionsBuilder.ReplaceService<IMigrationsAnnotationProvider, MyMigrationsAnnotationProvider>();
```
``` csharp
var annotation = dropColumnOperation["MyEnumAnnotation"];
```
