### ISSUE TITLE
Lazy loading and Many-to-many relationship exception.

### ISSUE THREAD

**Issue by ZBAGI** [dotnet/efcore#12898]
### Description
EF still doesn't support many-to-many relationship. In order to work around it, **join entity** is needed. But instead of loading / adding / checking join entity every time i using `JointCollectionFacade` instead. That act as a a collection and deals with it on its own. So i don't need to do anything more than just 
```csharp
 //Many to many relationship.
User.Role.Add(new Role())
User.Role.Delete(role);
``` 
Works like a charm with eager loading but it's throws an exception with lazy-loading and i have no idea why.

### Steps to reproduce problem
1. Clone repo from https://github.com/ZBAGI/Bugger
2. Adjust connection string in `Bugger/Database.cs` - to whatever you want to use.
3. Run debug and query `http://localhost:3577/api/values` with GET request
On first run database will initiate - `UserAccount` and `Role` will be created and EF will track it without any problem. Because they are already loaded - lazy loading will not throw an exception and everything works fine. 
4. Stop debug (IIS) and start it again. Now when you will request user for some reason lazy loader will prop an exception that states that  `AccountRoleJoint` is detached. Why ? I have tried to attach it in the constructor but that just lead to more unexplained exceptions.

### Exception
```
System.InvalidOperationException: 'Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'AccountRoleJoints' on detached entity of type 'UserAccountProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'
```

### Further technical details
**EF Core version:** 2.1
**Database Provider:** Pomelo.EntityFrameworkCore.MySql

**Comment by ajcvickers** [comment]
Note for triage: this is happening because lazy-loading is being triggered from the entity's constructor which happens before the entity is tracked.

**Comment by ZBAGI** [comment]
I fought the same. But loading it outside constructor doesn't help either. 
I changed [`Account` model](https://github.com/ZBAGI/Bugger/blob/master/Bugger/Models/Account.cs) to create facade in the getter
```csharp
    public abstract class Account
    {
        public Account(string name, string password) : this()
        {
            Name = name;
            //TODO: Proper password encryption with salt... and hookers. In fact, forget the password encription.
            Password = password;
        }

        protected Account()
        {
        }

        [NotMapped]
        private ICollection<Role> _Roles { get; set; }
        [NotMapped]
        public ICollection<Role> Roles {
            get
            {
                if(_Roles == null)
                    _Roles = new JointCollectionFacade<Role, Account, AccountRoleJoint>(this, AccountRoleJoints);
                return _Roles;
            }
        }
        [JsonIgnore]
        public virtual ICollection<AccountRoleJoint> AccountRoleJoints { get; }

        [Key]
        public int Id { get; set; } = GenerateUID();
        [Required]
        public abstract string Type { get; protected set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Password { get; set; }

        private static int GenerateUID()
        {
            var bigInteger = new BigInteger(Guid.NewGuid().ToByteArray());
            return Math.Abs((int)(bigInteger % int.MaxValue));
        }
    }
```
Ending up with exception
```
System.InvalidOperationException: 'The navigation property 'AccountRoleJoints' on the entity type 'Account' does not have a setter and no writable backing field was found or specified. Read-only collection navigation properties must be initialized before use.'
```
on the line:
```csharp
_Roles = new JointCollectionFacade<Role, Account, AccountRoleJoint>(this, AccountRoleJoints);
```
Please keep in mind that everything that is shown here works without any problem with eager loading.

**Comment by ajcvickers** [comment]
@ZBAGI The exception message in that case says what it means. Adding a `private set` to the property makes it work.

Triage: This is a case for which lazy-loading will never work--we cannot lazy-load another entity while in the constructor for the first entity. Instead, the lazy-loading should be triggered only when needed, for example in this case by not eagerly creating the Roles value in the constructor.
