### ISSUE TITLE
I want ask about when you use -UseDatabaseNames   Parameters  Generating Model navigation properties does not match the database name

### ISSUE THREAD

**Issue by zdlian** [dotnet/efcore#12897]
Describe what is not working as expected.
When I used Scaffold-DbText to generate entities from the database, there was a problem with navigation properties that did not match the database name.
If you are seeing an exception, include the full exceptions details (message and stack trace).
For Example:
```C#
  public partial class SysRoleMenu
    {
        public SysRoleMenu()
        {
            RoleDataUser = new HashSet<RoleDataUser>();
        }

        public int RoleMenuId { get; set; }
        public int MenuId { get; set; }
        public int RoleId { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? Creator { get; set; }
        public int? Modifier { get; set; }
        public DateTime? ModifyTime { get; set; }
        public string Remark { get; set; }
        public int TenementId { get; set; }

        public SysMenu Menu { get; set; }
        public SysRole Role { get; set; }
        public ICollection<RoleDataUser> RoleDataUser { get; set; }
    }
```
The names of Menu, Role, and databases in the above generated entities will still change. In addition to these, there are UserInfo, MasterInfo and so on.
Exception message:
Stack trace:

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

I want to generate the following entities. What should I do?
```c#
public partial class SysRoleMenu
    {
        public SysRoleMenu()
        {
            RoleDataUser = new HashSet<RoleDataUser>();
        }

        public int RoleMenuId { get; set; }
        public int MenuId { get; set; }
        public int RoleId { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? Creator { get; set; }
        public int? Modifier { get; set; }
        public DateTime? ModifyTime { get; set; }
        public string Remark { get; set; }
        public int TenementId { get; set; }

        public SysMenu  SysMenu { get; set; }
        public SysRole SysMenu  { get; set; }
        public ICollection<RoleDataUser> RoleDataUser { get; set; }
    }
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@zdlian Unless I'm missing something, the code you posted at the top looks the same as the code code you say you want to generate.

**Comment by zdlian** [comment]
@ajcvickers Some navigational attribute names do not match database names, for example, the navigational attribute generated by UserInfo is User, and you can see why

**Comment by ajcvickers** [comment]
@zdlian Navigation properties do not exist in the database--they exist only in the entity type classes. Since the navigation properties are effectively a view or facade over the foreign key, we use the foreign key column name as a basis for creating the navigation names. For example, the `MenuId` foreign key column results in the the `Menu` navigation property. I don't believe that there is an easy way to change this at the moment; we will discuss in triage.
