### ISSUE TITLE
Is there an equivalent to EF6's `CreateSourceQuery` in EF Core?

### ISSUE THREAD

**Issue by skbergam** [dotnet/efcore#12893]
After I query an entity like `var blog = ctx.Blogs.Single(b => b.Id == id);` I want to be able to call something like:
```C#
var recentPosts = blog.PostsQ
    .OrderByDescending(p => p.DateCreated)
    .Take(5)
    .ToList();
```

In EF6 I could do this with the following:
```C#
public partial class Blog {
    public ObjectQuery<Post> PostsQ => Posts.CreateSourceQuery();
}
```

How can I do this in EF Core? I'm assuming that the return type would be different, just not sure how to implement:

```C#
public partial class Blog {
    public IQueryable<Post> PostsQ => ???;
}
```

**Comment by ajcvickers** [comment]
@skbergam The equivalent in the DbContext API (in either EF6 or EF Core) is the `Query` method, accessible through the [EntityEntry](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.entityentry-1?view=efcore-2.1). For example:
```C#
using (var context = new BloggingContext())
{
    Blog blog = context.Set<Blog>().Single();

    IQueryable<Post> postsQuery = context.Entry(blog).Collection(e => e.Posts).Query();
}
```
The more modern APIs in EF6 and EF Core are predominantly designed to work with "POCO" entity types that do not directly use EF inside the class, so there isn't an obvious equivalent for putting this in the entity type itself. However, if all you need is to be able to load posts dynamically, then you might consider using [lazy-loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data).
