### ISSUE TITLE
Memory leak using FromSql

### ISSUE THREAD

**Issue by gribkovav** [dotnet/efcore#12902]
Constant grow of allocated process memory when repeatedly executing DbSet<>.FromSql method with dynamic sql (containing some volatile part e.g. temp table name etc). Well, of course it's not about classic unmanaged memory leak, it's some cache (seems ICompiledQueryCache in QueryCompiler and might be something else) used for queries has no obsolescence settings or size restriction, so it constantly grow. For some kind of software it's a serious problem, especially for services intended to operate in long term period, querying something with dynamically generated queries quite often.

We need either some way to correctly(!) clear cache or settings to restrict its size and/or its data lifespan, or (and I personally think it's better)  even a way to disable CompiledQueryCache (just use pass-through realization of ICompiledQueryCache) in cases when I'm sure about what I'm doing.

### Steps to reproduce
I've attached zip file with sample solution to reproduce, it contains just a few files. In order to reproduce and successfully run  it you need an instance of SqlServer (whatever version you have compatible with ef).

Entry point part is 
```c#
static void Main(string[] args)
{
	TestDbContext();
	var cache = ServiceProviderCache.Instance;
	Console.WriteLine("Press Enter...");
	Console.ReadLine();
}
```

After I get to ReadLine the process memory reaches about 600 mbytes and never falling. 

Most interesting code part  in Program.cs is method TestDbContext:
```c#
var rnd = new Random();

for (var i = 0; i < 30000; i++)
{
	var id = rnd.Next(1000000);
	const string connStr = "Server=(local);Initial Catalog=master;Integrated Security=True;";
	using (var db = new EventsExchangeDbContext(connStr))
	{
		var tempName = "@temp" + GetRandomString();
		var sql = $@"SET NOCOUNT ON;
                DECLARE {tempName} TABLE(Id int);
                INSERT {tempName}(Id) VALUES({id});
                SELECT Id FROM {tempName};";
					var rows = db.Ids.AsNoTracking().FromSql(sql).ToList();
	}
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer 2.1.1
Operating system: Windows 10 Enterprise [Version 10.0.17134.165]
IDE:  Visual Studio 2017 15.7.3
[HelloWorld.zip](https://github.com/aspnet/EntityFrameworkCore/files/2263074/HelloWorld.zip)

**Comment by ajcvickers** [comment]
@gribkovav This is because every query generated is different. Is there a reason not to use a parameterized query in this case?

We will implement cache eviction in the query cache to handle this case--see #12905.

**Comment by gribkovav** [comment]
@ajcvickers 
 Hello Arthur 0/ 
I do clearly understand that it's cached by design. But the way cache is used now makes be doubt designers have anticipated all the ways EF is used by us mere developers. =)
Queries vary but usually more complicated then in sample, and of course I use parametrization (injection aware you know :) ), but sometimes queries should be different, dynamically generated - in numbers of parameters, in names of temporary tables. Of course I could use something except EF, Dapper for example or good old SqlDataReader and Automapper, in cases of plain simple data acquisition especially without need to track changes in context. But, why should I if EF is already here? Remember Ockham : 
> It is futile to do with more things that which can be done with fewer

 ;)
