### ISSUE TITLE
ValueGenerator NextValueAsync isn't called at all

### ISSUE THREAD

**Issue by gilmishal** [dotnet/efcore#12900]
Overriding NextAsync/NextValueAsync is expected to be called and populate the value after running an async task.
However it is never called.

#### My Generator
      
```
    public class MyGenerator : ValueGenerator<int>
    {
        public override bool GeneratesTemporaryValues => false;

        public override int Next(EntityEntry entry)
        {
            return 0
        }

        public override async Task<int> NextAsync(EntityEntry entry, CancellationToken token)
        {
            return await SomeAsyncTask();
        }
    }
```
#### Setup

```
  builder.Entity<SomeEntity>()
                .Property(r => r.EntityId)
                .HasValueGenerator<MyGenerator>();
```
### My own research

After cloning the repository I found out that apparently nothing actually calls it. I mean there is a `PropogateValueAsync` That calls it, but nothing calls that.

### Bottom Line

The question is what is the point of the `NextAsync` function, and what are the plans regarding actually making it work? because it does seem like a useful feature, since using non async method is considered a bad practice.

### Further technical details
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Fall Creators Update
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment]
@gilmishal It's called by [`AddAsync`](https://github.com/aspnet/EntityFrameworkCore/blob/a3124077a8f03412471f27f5a046c863cd26f14f/src/EFCore/DbContext.cs#L756). It is only useful in very limited circumstances where generating a value needs to hit the database. Even then, most value generators never need to do this, so in most cases AddAsync just adds extra overhead and Add should be used instead.

**Comment by gilmishal** [comment]
I think I figured it out - [`AddAsync`](https://github.com/aspnet/EntityFrameworkCore/blob/a3124077a8f03412471f27f5a046c863cd26f14f/src/EFCore/ValueGeneration/ValueGenerator%60.cs#L28) isn't called. The base `ValueGenerator` works as expected, however the Generic one doesn't.

Since the line is marked with the `new` keyword, instead of as an override (seems like a mistake, although understandable) it will never be called by using the base class.
