### ISSUE TITLE
The derived type 'Contact' cannot have KeyAttribute on property 'ContactId' since primary key can only be declared on the root type.

### ISSUE THREAD

**Issue by Illeris** [dotnet/efcore#12919]
I have a "contact" entity derived from a "entityobject" (base entity). The mapping class looks like this:

```C#
public class ContactMappingConfig : EntityObjectMappingConfigBase<Contact>
    {
        public ContactMappingConfig(string schema = "dbo") : base(schema)
        {
        }

        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Contact> builder)
        {
            builder.HasKey(x => x.ContactId);
            builder.ToTable("Contact");
            builder.Property(x => x.FirstName).HasColumnName("FirstName").HasMaxLength(255);
            ...
        }
    }
```
When I invoke the context (code below), I get the exception on the ctx.Contacts invocation.
```C#
 Dev1DbContext ctx = new Illeris.Dev1.Repository.Dev1DbContext(cnStr);
foreach (var x in ctx.Contacts)
{
}
```
Wasn't this fixed in 1.0.1? I just upgraded to .NET CORE v2.1 & EF 2.1.2.

Plz advice.

**Comment by ajcvickers** [comment]
@Illeris A key can only be defined on the base type of a mapped hierarchy. There are a variety of related reasons for this, but for a TPH mapping it boils down to one primary key for the table which is shared by all entity types that are mapped to that table.

If you feel like there is a bug here outside of this limitation, then please post a runnable project/solution or complete code listing that reproduces the bug.

**Comment by The-DevOps-Guy** [comment]
Hi, I have created a example project with this issue for you to reproduce. 
To see, all you need to do is run the following command in the Package Manager Window.
>Add-Migration Init -Context ApplicationDbContext

Solution: https://drive.google.com/file/d/1gXqpyamax-SQVU6F006AlCsc-mcZNRJZ/view?usp=sharing
