### ISSUE TITLE
So confused about EF Core's pluralization issues. Cannot commit my changes via DBContext. 

### ISSUE THREAD

**Issue by JDGHHou** [dotnet/efcore#12921]
Setting up an EF Core DB Context, I've created singular-named db classes based on singular-named tables in the database. Following conventions from previous EF versions, I present DBSets of them named plurally. So, my Order class is presented in a DBSet<Order> collection called Orders. But when I try to add an Order object to Orders then call the DBContext's SaveChanges() method, SQL throws an error because there is no object in the database called Orders. The table is called Order. But I can't just change the DBSet name to Order, because I already have a class named Order in the same namespace. This is really confusing. 

Why would EF Core abandon this really effective approach? What is the replacement? I can't get basic CRUD stuff to work because of this.

**Comment by ajcvickers** [comment]
@JDGHHou The behavior in EF Core is the same as it was in EF6. To override the DbSet convention, set the table name explicitly using either the ModelBuilder API or data annotations, as described in the documentation on [Table Mapping](https://docs.microsoft.com/en-us/ef/core/modeling/relational/tables)
