### ISSUE TITLE
Transient DbContext lifetime when using DbContextPool

### ISSUE THREAD

**Issue by arishlabroo** [dotnet/efcore#12946]
Question: Is it required that DbContext leased from a pool be `Scoped` lifetime?

From [here](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore/EntityFrameworkServiceCollectionExtensions.cs#L292),  it is set as scoped with no overload to pass a service lifetime.

When I am configuring services, if I explicitly.
```
serviceCollection.AddTransient(
      sp => (TContextService)sp.GetService<DbContextPool<TContextImplementation>.Lease>().Context);
```
it seems to be working as expected.

I understand the implications of scoped vs transient context, but in case of ContextPool, want to make sure if transient leased context is especially not recommended.

**Comment by ajcvickers** [comment]
@arishlabroo I believe it should be okay. The only issue might be that none of the transient instances will be determined to the pool until transients are disposed, and I believe that happens when the scope is disposed.
