### ISSUE TITLE
Improve usage outside of AspNetCore (Generic Host)

### ISSUE THREAD

**Issue by greenboxal** [dotnet/efcore#12944]
We're building a messaging based application mesh, and even though we don't use AspNetCore, we still use `Microsoft.Extensions.Hosting` and friends as the application base.

Today, in order to use `dotnet ef` commands, we need to implement an `IDesignTimeDbContextFactory'1`. This is cumbersome because I don't wanna have two code paths for instantiating our `DbContext`. Also, we need to have one `IDesignTimeDbContextFactory'1` per application, as they have their own `DbContext`.

When using AspNetCore, EFCore relies on `WebHostBuilderFactory` to find the application services and get the `DbContext`.

What are my options here? My suggestion is to expose `AppServiceProviderFactory` as a design time service that could be overridden by my own design time implementation (if people are okay with this, I can provide a PR).

**Comment by ajcvickers** [comment]
@javiercn I talked to @bricelam and he indicated that hosting now owns/shares this code. Do you have any thoughts?

**Comment by greenboxal** [comment]
@javiercn that actually makes sense. It was weird to me all the references to `WebHost` and the dependency on Microsoft.AspNetCore.Hosting instead of Microsoft.Extensions.Hosting.

Also, is there a reason why you're using reflection instead of the actual interfaces? (both on APC.Hosting and EFCore).

One suggestion that I would make is to rename or add a third method, called `BuildHost`, dropping the Web, as it is confusing.

**Comment by javiercn** [comment]
@greenboxal We don’t want EF to take a strong dependency on Hosting, that’s why we use reflection.

As per adding yet another pattern I want to avoid changing this yet another time without any functional requirement change.

Hope that makes sense.

Closing this issue as there’s no more action to be taken here at the moment.

**Comment by oliverjanik** [comment]
Can we please re-open?

The use case is quite clear:
1) Non asp.net core project
2) DbContext in a class library

The only solution is to implement DbContext factory in the class library which super awkward.

@javiercn

**Comment by ajcvickers** [comment]
@oliverjanik Can you please open a new issue and include a small, runnable project/solution that demonstrates the issue you are having.
