### ISSUE TITLE
EF Core 2.1.1 Full Text Search issue

### ISSUE THREAD

**Issue by apavelm** [dotnet/efcore#12981]
Developing an application that uses Full-Text Search and EF Core 2.1.1

FT Catalog and FT-index on the table have been built. 

The query in MS SQL Server Management Studio, like this
```C#
select * from school
where FREETEXT(Name, 'university')
```
works fine and returns data.

But if I try to do same from the .NET Core application
```C#
var schools =  _db.Schools
                .AsNoTracking()
                .Where(c =>
                        EF.Functions.FreeText(c.Name, searchText)
                )
                .ToList();
```

 I will get an exception:
```
System.Data.SqlClient.SqlException (0x80131904): Cannot use a CONTAINS or FREETEXT predicate on table or indexed view 'School' because it is not full-text indexed.
```

In my debug, I dig into SQL Profiler and found a generated SQL-query

```sql
exec sp_executesql N'SELECT TOP(@__p_3) ...field...
FROM [School] AS [s]
...
WHERE ...conditions.... AND (FREETEXT([s].[Name], @__searchText_2))....;
```
Note. Query is quite big, I truncated it a little.
So, I copy-pasted it into SQL Server Management Studio, and it works! 
But if I tried to execute this query from C# code, even by `ExecuteSQLCommand` I will get an exception.

User is `sa` everywhere

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017 (latest)
![console](https://user-images.githubusercontent.com/6442445/44008901-5810f47e-9eeb-11e8-83ff-74f3986da23a.png)

**Comment by apavelm** [comment]
Please advice how to solve it

**Comment by apavelm** [comment]
Additional info,

If I doing same from the tests
```
// Act
var schools = await controller.Get("university");
```
That code is inside, it return correct result-set (no exceptions)

**Comment by ErikEJ** [comment]
Are you sure you are connecting to the same database?

**Comment by apavelm** [comment]
Absolutely, same Db, same user, same query

**Comment by apavelm** [comment]
@ErikEJ Please tell me if I can give you more details. The issue described looks weird, at least because the same code works fine if it called under Tests, but fail if it called via ApiController

**Comment by smitpatel** [comment]
> Note. Query is quite big, I truncated it a little.
So, I copy-pasted it into SQL Server Management Studio, and it works!
But if I tried to execute this query from C# code, even by ExecuteSQLCommand I will get an exception

Can you try running query from C# with raw ADO.NET without having EF in the picture? If SQL generated by EF works in some cases and fails in other cases then it is highly unlikely that EF Core is causing the issue.

**Comment by apavelm** [comment]
@smitpatel Just tested EF Core generated query from ADO.NET - works
Next after ADO.NET EF Core code
```
var schools =  _db.Schools
                .AsNoTracking()
                .Where(c =>
                        EF.Functions.FreeText(c.Name, searchText)
                )
                .ToList();
```
Fails

**Comment by apavelm** [comment]
I've created a new db-user to test - doesn't matter, same exception

**Comment by smitpatel** [comment]
@apavelm - Based on description above, we will need a full repro code of application, along with database creation scripts to investigate this issue further.

**Comment by apavelm** [comment]
@smitpatel This is a commercial project, unfortunately, I can not share it. Probably if it is possible we can make an appointment for the call (eg, via skype/hangout/etc) and you can investigate what happens at my PC (if it required).

I tried to cut some things off from the solution to prepare the "Demo" project which I'll share with you. But after simplification, the issue has gone (for the demo project), but still persist in the original project.

According to this, I suspect the only 3 things (difference from the original project), what do you think, which of them could be the reason for the issue:
- Multiple table references and navigation properties in the model
- Original DbContext is defined in the library, which installed by NuGet from the private repo.
- Original DBContext uses Enum.NET and NodaTime extension for the models and converters.

These three things is only the difference from the original db-context.

**Comment by apavelm** [comment]
**UPDATE**
Tested that code on 2 different PCs works everywhere, so seems it is a local issue. 
I think this issue-ticket could be closed, but **could you please give me an advice how it could be solved, thanks in advance**
