### ISSUE TITLE
Why FKs (property names) in related table are enforced to certain standard.

### ISSUE THREAD

**Issue by aristosamar** [dotnet/efcore#12993]
Hi,

Loading related data forces me to use specific naming convention regarding FK in database.
Example:

		public class Activity
		{
			[Key]
			public int ID { get; set; }
			[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
			public DateTime Created { get; set; }
			public string Code { get; set; }
			public string Name { get; set; }
			public virtual ICollection<ActivityNote> ActivityNotes { get; set; }
		}
		public class ActivityNote
		{
			[Key]
			public int ID { get; set; }
			public int ActivityID { get; set; }
			public string Note { get; set; }
		}

I use different convention for FKs in my databases:
1. Prefix FKs with ID (i.e. ActivityNote.IDActivity instead of ActivityNote.ActivityID)
2. Place FKs at the top of the table schema

This helps me to recognize FKs easily when browsing through table schema.
I imagine it can span a debate as whether it's good or bad idea but in my opinion it's a matter of a personal taste. I am interested in why this is enforced to be certain way. To be able to use it I would need to change schema of many tables.

Instead FKs could be marked by data annotations or similar.

**Comment by ajcvickers** [comment]
@aristosamar A property with any name can be configured as an FK; see https://docs.microsoft.com/en-us/ef/core/modeling/relationships
Likewise, a property can be mapped to a column with any name; see https://docs.microsoft.com/en-us/ef/core/modeling/relational/columns
