### ISSUE TITLE
Where can I learn how to use advanced APIs like SqlFragmentExpression or IMethodCallTranslator?

### ISSUE THREAD

**Issue by he-dev** [dotnet/efcore#12997]
I'd like to know more about these advanced APIs (and others) and how I can customize EF-Core by implementing my own `IMethodCallTranslator` and generate some custom SQL with the `SqlFragmentExpression`. I'd also like to know which services are replacable and to what extent they can be customized.

Could you share some links to articles about such more advanced techniques?

**Comment by ajcvickers** [comment]
@he-dev I'm not aware of any documentation or articles for these areas. I suspect your best bet is to read the code and look at the tests. Leaving this open for now to discuss with @divega as to whether or not to create a docs issue for this.

**Comment by he-dev** [comment]
@ajcvickers I was afraid you might say that reverse-engineering is the only way. However, I'd be great if EF-Core's docs had the same quality as ASP.NET-Core where virtually every interface and service and customization is described (even with examples) and you can adjust things much more easily.

**Comment by ajcvickers** [comment]
@he-dev Can you post a link to that documentation for ASP.NET Core?

**Comment by he-dev** [comment]
@ajcvickers Here're a couple of them:

https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.iviewlocationexpander?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.languageviewlocationexpander?view=aspnetcore-2.1

or an extensive list of feature-interfaces:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-2.1

ASP.NET-Core seems to be a _customize-anything_ product whereas EF-Core a _use-as-is_ one. As you've said in the first response, there are no such pages about EF-Core that describe various services and interfaces to override, add, replace, implement or extend in order to customize EF-Core or provider behaviour.

**Comment by ajcvickers** [comment]
@he-dev Thanks for the links. Those seem much more like mainline scenarios to me. EF has a lot of application-level configuration, but almost none of it is done through implementation of services. That's only for the most advanced things that we expect only a handful of people to do, or for people writing database providers, for which we are lacking some documentation. When we find something that a lot of people need, we try to make a good configuration experience that does not require replacement of services.
