### ISSUE TITLE
Enhancement: context identifiers

### ISSUE THREAD

**Issue by BalassaMarton** [dotnet/efcore#12996]
When multiple db contexts are backed by the same database (for example in a DDD/Bounded Context implementation), it takes extra effort to name migrations correctly, especially when they are developed separately. This is just the most obvious problem, the below proposal could be extended to solve other, yet unknown problems arising in these scenarios.

#### Annotations
```cs
[ContextId("Sales")]
public class SalesDbContext : DbContext {
}

[ContextId("Inventory")]
public class InventoryDbContext : DbContext {
}
```

#### Fluent API
```cs
public class SalesDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasContextId("Sales");
    }
}
```

#### Expected behavior

1. Migration identifiers should be automatically prefixed, e.g. running this:
````
Add-Migration AddProducts -Project MySolution.SalesService -Context SalesDbContext
````
should add a migration with class name `AddProducts`, and file name `XXXXXXXX_AddProducts`, but the migration id should be `XXXXXXXX_Sales_AddProducts`.

This would eliminate the need to manually prefix the migration name when there's a possibility that other db contexts are also using the same database.

**Comment by ajcvickers** [comment]
@BalassaMarton This is not something we plan to implement, but there is a service `IMigrationsIdGenerator` than can be implemented to change the way migration names are generated. EF can then be instructed to use the new service by calling ReplaceService on the DbContextOptionsBuilder.
