### ISSUE TITLE
Many-to-many relationships without an entity class to represent the join table.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#13009]
In Entity Framework 6.x, we can configure many-to-many relationships without an entity class to represent the join table but in EF Core we cannot do that yet( 2.1).

My question is when this EF 6.x feature will be imported in EF Core?

Thank you.

**Comment by MarcoLoetscher** [comment]
Planned for 3.0: https://github.com/aspnet/EntityFrameworkCore/issues/10508
