### ISSUE TITLE
Calling GetType() on entity selects every property

### ISSUE THREAD

**Issue by csokiskeksz** [dotnet/efcore#13011]
I have a query, where I want to select one property from an entity, and also get the type of the entity. I receive the correct type, but now in the SQL generated by EF every property is selected. Is this a bug, or is it necessary to select all properties in order to get the entity type?

### Steps to reproduce

Let's say I have an entity:
```C#
public class Entity
{
    public Guid Id { get; set; }
    public string Property1 { get; set; }
    public string Property2 { get; set; }
    public string Property3 { get; set; }
}
```
When I select only "Property1", the SQL generated is good:
```C#
var entity = context.Entities
    .Select(e => new
    {
        e.Property1
    })
    .FirstOrDefault(); 
```
```sql
SELECT TOP(1) [e].[Property1]
FROM [Entities] AS [e]
```

But when I also want to select the type of "Entity", I get the following SQL:
```C#
var entity = context.Entities
    .Select(e => new
    {
        e.Property1,
        e.GetType().Name
    })
    .FirstOrDefault();
```
```sql
SELECT TOP(1) [e].[Id], [e].[Property1], [e].[Property2], [e].[Property3]
FROM [Entities] AS [e]
```
It's not a big deal in this example, but I want to use this in an inheritance scenario where it becomes a problem due to the large amount of properties

### Further technical details:

EF Core version: 2.1
Database Provider: EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017 15.7.6

**Comment by smitpatel** [comment]
`GetType` is not something which we can translate to server. Further, there can be differences based on how entity is materialized or even inheritance hierarchy. Hence the only way to get it reliably and accurately is to create the actual instance. Hence you see all properties selected.

If you are using it specifically in TPH scenario then it would be better to use Discriminator property value rather than `GetType().Name`

**Comment by ajcvickers** [comment]
Triage: closing this as by-design.

**Comment by csokiskeksz** [comment]
Thanks for clearing that up. I suspected that it worked like that, but I couldn't find any confirmation for it. 
You are right, using the Discriminator value is the way to go then.
