### ISSUE TITLE
Unused constructor DatabaseProvider(DatabaseProviderDependencies)

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/efcore#13020]
The [following code](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore/Storage/DatabaseProvider.cs#L32-L35) in release/2.2 is only ever called by tests and I don't think it's needed there either.

```csharp
public DatabaseProvider([NotNull] DatabaseProviderDependencies dependencies)code
{
    Check.NotNull(dependencies, nameof(dependencies));
}
```

Can this constructor be removed (probably marked `Obsolete` first)?

**Comment by smitpatel** [comment]
@MisinformedDNA - It is for future proofing.
We use `*Dependencies` objects for inject services through DI. Putting all services in constructor means adding a new service is breaking change for people deriving from it. Hence we introduced Dependencies objects which will hold all the services. And adding a new service would still not break others. Currently, `DatabaseProvider` does not depend on any service hence the  `DatabaseProviderDependencies` object has no members and the constructor is empty.
In future when it needs to depend on the service, it will be used appropriately without breaking apps.
