### ISSUE TITLE
DefaultIfEmpty Does Not NullRef

### ISSUE THREAD

**Issue by avinash-phaniraj-readify** [dotnet/efcore#13039]
When `DefaultIfEmpty()` is used to perform a left outer join, and the if the row is used incorrectly (i.e. by assuming the row is not missing), then no exceptions are raised. We would expect a `NullReferenceException` to be raised.

```c#
                from e in employees
                join d in employeeDevices on e.Id equals d.EmployeeId into x 
                from j in x.DefaultIfEmpty()
                select new 
                {
                    Result = j.Id != 0 ? "Was Not Zero" : "Was Zero"
                }
```
For the case when `j` is `null` (e.g. the left join found no match on the join predicate):
* Using `j.Id` should *normally* raise an exception, but
* In the example above, Result is `null` instead 

> NOTE: We're porting an existing codebase from LINQ to SQL where this pattern appears to be valid. The current behaviour is dangerous in that it's hiding the failure, which makes it more difficult to identify issues.

### Steps to reproduce
https://github.com/avinash-phaniraj-readify/EFCoreTestBed/tree/DefaultIfEmptyDoesNotNullRef

### Further technical details
EF Core version: 2.1.1
Database Provider: EntityFrameworkCore.SqlServerCompact35 2.1.0.1
Operating system: Win 10
IDE: Visual Studio 2017 15.7.2

**Comment by optiks** [comment]
@ajcvickers After further discussion, please feel free to close this as designed. I'll send a separate follow up email. Thanks.
