### ISSUE TITLE
How do I unit test implementations of IEntityTypeConfiguration

### ISSUE THREAD

**Issue by gforceg** [dotnet/efcore#13046]
I hope this is the right place to ask this question. I am working on a class that extends IEntityTypeConfiguration and I want to unit test code that usually runs in DbContext.OnModelCreating.

For example:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  modelBuilder.ApplyConfiguration(new MyCustomConfig("./some-seed-data.json"));
  modelBuilder.ApplyConfiguration(new MyOtherCustomConfig());
}
```

Should I be instantiating a ModelBuilder? I would prefer to not run a migration that creates files but that's an acceptable side-effect.

Thanks

EF Core version: <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0" />
Database Provider: <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" />
Operating system: Win 10
IDE: (e.g. Visual Studio 2017 15.4) VS Code

**Comment by gforceg** [comment]
I think I can achieve my goal if I can some how instantiate EntityTypeBuilder but usually this object is provided by the framework.

**Comment by ajcvickers** [comment]
@gforceg What are you trying to test, specifically?

**Comment by gforceg** [comment]
@ajcvickers, I am working on an abstract class that makes method calls in Configure() to perform configuration and to seed data from the file system (json, yaml, etc...).

```C#
public abstract class EntityConfiguration<TEntity> : IEntityTypeConfiguration<TEntity>
  where TEntity : class
  {
    public string FilePath { get; set; }
    
    public EntityConfiguration(string filePath = "")
    {
      this.FilePath = filePath;
    }

    public void Configure(EntityTypeBuilder<TEntity> builder)
    {
      DoConfiguration(builder);
      DoSeed(builder);
    }
    ...
}
```

I think what I'm currently trying to do is an integration test. I have a class 'MyCustomConfig' that inherits from EntityConfiguration. I want to assert that the following code will throw an exception when the json file doesn't exist.

```C#
modelBuilder.ApplyConfiguration(new MyCustomConfig("./non-existent-file.json"));
```

I must wrap the call in modelBuilder.ApplyConfiguration otherwise, MyCustomConfig.Configure won't be called. The only way I know how to do this is by running a migration from the dotnet cli and I think that would be more of a BDD test.

I would also like to be able to unit test the individual DoConfiguration(builder) and DOSeed(builder) functions but I don't know how to instantiate EntityTypeBuilder.

**Comment by ajcvickers** [comment]
@AndriySvyryd to answer.

**Comment by AndriySvyryd** [comment]
```C#
var serviceProvider = new ServiceCollection()
    // You can also use InMemory or any other provider here to get the provider-specific conventions
    .AddEntityFrameworkSqlServer()
    .AddDbContext<DbContext>(o => o.UseSqlServer("Server=."))
    .BuildServiceProvider();

using (var serviceScope = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
    using (var context = serviceScope.ServiceProvider.GetService<DbContext>())
    {
        var conventionSet = ConventionSet.CreateConventionSet(context);
        return ModelBuilder(conventionSet);
    }
}
```

**Comment by gforceg** [comment]
@AndriySvyryd @ajvickers Thanks so much for your response. I will give this a try very soon!

**Comment by gforceg** [comment]
@AndriySvyryd Your code sample was very helpful and informative.
Now I have unit testing working in my project (And I know more about how DI works outside of .net core MVC!)

I did have to make a small change to get this to work:

I changed this line:
```C#
return ModelBuilder(conventionSet);
```

To this:
```C#
return new ModelBuilder(conventionSet);
```

**Comment by weitzhandler** [comment]
Hello @AndriySvyryd and thanks for your response,

I have a similar question, except in my scenario I am on integration test project.
To setup the models configuration I'm using `builder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());`.

I'm using ASP.NET Core integration test, and I'd like to override the various entity configuration to include seed data. Unfortunately the various db initializers were all removed, and based on my understanding, the only way to 'inject' the seed data is by re-registering the DbContext registrations to their subclasses, having the `OnModelCreating` overridden. Are there any other options to consider.
I'm trying to leave the `Startup` classes untouched to mimic the original app behavior as much as possible.

**Comment by weitzhandler** [comment]
What I ended up doing is added this to my integration test service registration:

```c#
void ConfigureServices(IServiceCollection services)
{
  ReplaceDbContextRegistration<GlobalDbContext, TestGlobalDbContext>(services);
  ReplaceDbContextRegistration<PerTenantDbContext, TestPerTenantDbContext>(services);
}

void ReplaceDbContextRegistration<TContext, TTestContext>(IServiceCollection services)
  where TContext : DbContext
  where TTestContext : TContext
{
  var current = services.Single(descriptor => descriptor.ServiceType == typeof(TContext));
  var clone = new ServiceDescriptor(current.ServiceType, typeof(TTestContext), current.Lifetime);

  services.Replace(clone);
}
```
