### ISSUE TITLE
Question - How to create DbContext with existing DbConnection in a provider-agnostic way

### ISSUE THREAD

**Issue by BalassaMarton** [dotnet/efcore#13041]
I have a set of worker classes that must share the same DbTransaction. Following the instructions on the documentation page
https://docs.microsoft.com/en-us/ef/core/saving/transactions#cross-context-transaction-relational-databases-only
I was able to share the transaction - however this ties my classes to a particular provider (SqlServer) that is not suitable for my unit tests. What I need to accomplish:
- Create `DbContext`s from externally provided `DbContextOptions`
- Start and share a single `DbTransaction` between these contexts
- All without using any provider-specific API.

Is this possible in any way?

**Comment by ajcvickers** [comment]
@BalassaMarton Can you give some more details on how this approach is tied to SqlServer?

**Comment by BalassaMarton** [comment]
Consider something like this:
```cs
    public interface IWorker
    {
        void DoWork(Func<MyDbContext> dbFactory);
    }

    public class WorkerRunner
    {
        private readonly DbContextOptions<MyDbContext> _dbOptions;

        private readonly List<IWorker> _workers;

        public WorkerRunner(DbContextOptions<MyDbContext> dbOptions, List<IWorker> workers)
        {
            _dbOptions = dbOptions;
            _workers = workers;
        }

        public void RunWorkers()
        {
            using (var context = new MyDbContext(_dbOptions))
            {
                using (var tran = context.Database.BeginTransaction())
                {
                    foreach (var worker in _workers)
                        worker.DoWork(() =>
                        {
                            // This won't work
                            var db = new MyDbContext(_dbOptions);
                            // And this one will even throw exception when used with in-memory database (during unit testing)
                            db.Database.UseTransaction(tran.GetDbTransaction());
                            return context;
                        });

                    tran.Commit();
                }
            }
        }
    }
```
The options are provided through DI and already contain a connection string (or in-memory DB options, if running in a unit test). The only way I can share a transaction between two contexts is to also share the `DbConnection` - but I can't do that, because there's no core API that would let me copy the connection from one options object to another. Even if I know the provider, or write conditional code, `UseSqlServer(SqlConnection)` will throw an exception because the options object already has a connection string configured.

**Comment by BalassaMarton** [comment]
I might have found a solution, although I'm not sure this is safe to do:
```cs
var db = new MyDbContext(context.GetInfrastructure().GetRequiredService<IDbContextOptions>() as DbContextOptions<MyDbContext>);
```
If I do this, the options object extracted from the context has a `DbConnection` and no connection string, but I'm wondering, does this generally work with other providers as well?

**Comment by sam-wheat** [comment]
Please see:

[AdaptiveClient](https://github.com/leaderanalytics/AdaptiveClient)

[AdaptiveClient.EntityFrameworkCore](https://github.com/leaderanalytics/AdaptiveClient.EntityFramework)

[AdaptiveClient Demo](https://github.com/leaderanalytics/AdaptiveClient.EntityFramework.Zamagon)

>  The only way I can share a transaction between two contexts is to also share the DbConnection...
 
This is probably related to your DI container.  AdaptiveClient uses Autofac and injects a single (shared) instance of DBContext into all services (workers) that request it.

Also, AdaptiveClient resolves components based on your connection string.  So if your app targets SQL Server and MySQL and SQLite AdaptiveClient will look at your connection string and inject the correct platform-specific implementation for you.

**Comment by BalassaMarton** [comment]
@sam-wheat That's nice, but I specifically do __not__ want to share a single `DbContext`, but create an arbitrary amount of contexts that work in the same transaction, all without any provider-specific code. I actually came up with a solution and writing an article about it, but until then, see my repo
https://github.com/BalassaMarton/EFCore.TransactionExtensions

**Comment by ajcvickers** [comment]
@BalassaMarton I have marked #8494 for re-triage since that would make this scenario a lot easier. I would also be interested in reading your article--I have some ideas for working around this, but I'd like to see what you come up with first.

**Comment by BalassaMarton** [comment]
@ajcvickers I've posted it as a readme, I'd really appreciate if you guys could comment on it. There's great chance I still don't get everything about EF Core & transactions.
https://github.com/BalassaMarton/EFCore.TransactionExtensions

**Comment by BalassaMarton** [comment]
Yes, it's a very similar approach. In both cases, an external service is configuring the DbContext, and in both cases it is a requirement of the service that the same instance has to create contexts for the same connection. I might even like your version better because it retains the ability to control where and how to instantiate the DbContext. Anyway, I'll work on my tool a little more and see where it gets me.
