### ISSUE TITLE
Don't enable foreign keys for read-only operations in SQLite

### ISSUE THREAD

**Issue by j-hudecek** [dotnet/efcore#13054]
Currently EF Core for SQLite opens a new connection for each statement and sends ``PRAGMA FOREIGN_KEYS=ON`` for each statement. ``SELECT`` statements don't really need to be checked for foreign keys. Since a new connection is opened for each statement it should be possible to avoid doing that. It takes 2ms on my machine.

### Steps to reproduce
``var entity = context.Entities.Single(e=>e.ID==1);``

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlLite
Operating system: Windows
IDE: Visual Studio 2017 15.7

**Comment by ajcvickers** [comment]
Note from triage: Issue #12151 is about removing this (since it's not needed) in 3.0. Assuming we do that, then this will no longer be an issue.
