### ISSUE TITLE
Foreign key value propagation could make use of temporary values

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1305]
See #1304. The value generator used must be the same one as used to generate keys for the principal. However, the values generated will always be temporary even if the value generator being used is not generating temporary values. This doesn't matter much except that value generation may be somewhat expensive and values from the non-temporary key space get used up. So instead value generators could be asked to generate temporary values even if they don't normally do so, and this capability could then be used by the FK propagator.

**Comment by rowanmiller** [comment]
We should just do this if we get feedback that we need to
