### ISSUE TITLE
Dynamic Typed Models Support

### ISSUE THREAD

**Issue by lvasiliou** [dotnet/efcore#1306]
Can you add support for dynamic typed models?
For example
I specify my model and table mappings in JSON or XML format, EF gives me dynamic objects with maybe an entityname property. This is extremely useful for large applications containing a huge number of entities

**Comment by rowanmiller** [comment]
This should be largely supported once we [allow full entities to be represented in shadow state](https://github.com/aspnet/EntityFramework/issues/749). You'll be able to create a model without any CLR classes and then query/manipulate/save data.

@Riva81 do you have any particular requirements that you don't think will be met by this?

**Comment by Riva81** [comment]
I will give r7 a go and let you know. I have an application that consists of around 123 or so entities and I am putting my faith in EF6.x. I hate to go in and implement 123 classes with 123 WebAPI controllers. A good balance is 123 classes and one controller that will support CRUD operations for all entity types- maybe an expando with an entry that specifies the entity type. My DB Context will just pick that Expando object up and know what to do with it. Similarly I should be able to return an expando or dynamic object from DB context select queries. It will be interesting to see how annotations will work with shadow state entities.

**Comment by rowanmiller** [comment]
Currently we don't support full entities in shadow state (you still have to have an actual CLR class for each entity). We will enable it in the future though (issue #749). The way shadow state currently works, any shadow properties (or entities when supported) are stored in the ChangeTracker and can be read/written thru that API.

**Comment by rowanmiller** [comment]
Closing out as there hasn't been anymore discussion but feel free to re-open if you have further questions.
