### ISSUE TITLE
Support for using another column from the same table in Value Conversions

### ISSUE THREAD

**Issue by dhtek** [dotnet/efcore#13067]
Does it possible to use another column from the same table when defining the converter ? 
I try to find on the web, but didn't find any answer.

### Steps to reproduce

```c#
builder.OwnsOne(x => x.Type).Property(x => x.Code).HasColumnName("TypeCode");
builder.Property(x => x.Detail).HasConversion(
x => XmlSerializer.SerializeDetail(x),
x => XmlSerializer.DeserializeDetail<IDetail>("Should be the value from the column TypeCode", x));
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017 15.7.3

**Comment by ajcvickers** [comment]
@dhtek This is currently not possible, but is being tracked as part of #9906
