### ISSUE TITLE
Hope EF can be compatible with ADO. NET, including Enterprise Library, and support MyBatis-like framework, support Sql statements in XML file configuration

### ISSUE THREAD

**Issue by ghd258** [dotnet/efcore#13086]
Hope EF can be compatible with ADO.NET, including Enterprise Library, and support similar MyBatis framework, support Sql statements in XML file configuration, mainly considering the performance of large projects with EF or problems, especially more than a dozen table associations, and the amount of data is very large, or ADO.NET square. Good performance, Microsoft has abandoned the update maintenance EnterpriseLibrary

**Comment by ghd258** [comment]
support similar MyBatis framework, support Sql statements in XML file configuration

**Comment by ajcvickers** [comment]
@ghd258 There doesn't seem to be any specific question here, so closing. If you have a specific question or issue, then please file a new issue including full details of what the scenario is, what's not working, and any other details that will help us understand specifically what you are asking.
