### ISSUE TITLE
Enumeration is not supported

### ISSUE THREAD

**Issue by wangpengxpy** [dotnet/efcore#13095]
```
System.InvalidCastException
```

### Steps to reproduce

```c#
    public class Test
    {
        public int Id { get; set; }
        public string PayId { get; set; }
        public Status Status { get; set; }
        public DateTime CreatedTime { get; set; }
    }

    public enum Status : byte
    {
        Create = 0,
        Success = 1
    }
    var context = new EFCoreDbContext();
    var tests = context.Tests.Select(d => new Test()
    {
          Status = (d.Status == Status.Create ? Status.Create : Status.Success),
           CreatedTime = d.CreatedTime,
            Id = d.Id
    }).ToList();
```
![image](https://user-images.githubusercontent.com/12961992/44533344-e9a0e900-a727-11e8-946a-b80782677a05.png)

### Further technical details
Target Framework:  .NET Framework 4.6.1
EF Core version: (2.0.1)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win 8.1
IDE: (Visual Studio 2017 15.8.0)
[](url)

**Comment by maumar** [comment]
this works in current bits. Please update your EFCore version.
