### ISSUE TITLE
Missing Document Summary

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#13116]
When I use the EFTool to generate a model from the code first, the document summary is missing

**Comment by ajcvickers** [comment]
@Varorbc Can you be more specific about what you mean by "the EFTool"?

**Comment by bricelam** [comment]
(and *document summary* 😀)

**Comment by Varorbc** [comment]
@ajcvickers @bricelam https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L249 miss table and column summary from database

**Comment by bricelam** [comment]
Similar to #6149?

**Comment by Varorbc** [comment]
Yes, very similar to this, as Rowanmiller said, I would like to have xml doc comments, and the scalability mentioned by him, I hope you can also provide such a package, but don't use https for t4 templates: //www.nuget.org/packages/EntityFramework.CodeTemplates.CSharp/

**Comment by ajcvickers** [comment]
Triage: this is not something we are going to implement because we believe the value is pretty small, but we would consider a well-written community PR to add this functionality.

**Comment by Varorbc** [comment]
I think it's important for those who take database first and then use reverse engineering.
