### ISSUE TITLE
Test that materialization, etc.handles entities that use C# 6 features

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1311]
In particular read-only auto properties.

**Comment by rowanmiller** [comment]
Please discuss with @ajcvickers 
Also summarize what you tested (and findings) at design meeting

**Comment by smitpatel** [comment]
I tried adding test in EntityMaterializerSourceTest which contains entity with read only auto properties. It throws following exception
````
System.InvalidOperationException : No backing field could be discovered for property 'Microsoft.Data.Entity.Tests.Metadata.EntityMaterializerSourceTest+SomeEntityReadOnly.Foo' and the property does not have a setter. Either use a backing field name that can be matched by convention, annotate the property with a backing field, or define a property setter.
````

**Comment by divega** [comment]
@smitpatel I for that particular case it is expected. We would probably need materialization to support matching constructor parameters to be able to work with those entities. Probably a good idea to file a bug for that and then we can discuss the priority.

**Comment by smitpatel** [comment]
It is possible to find backing field of read-only auto property through reflection.
The backing field is constructed using pattern *\<PropertyName>k__BackingField* 

Following method gives access to backing field.
```C#
private string _getBackingFieldName(string propertyName)
{
    return string.Format("<{0}>k__BackingField", propertyName);
}

private FieldInfo _getBackingField(object obj, string propertyName)
{
    return obj.GetType().GetField(_getBackingFieldName(propertyName), BindingFlags.Instance | BindingFlags.NonPublic);
}
```
Then we can use this code to set the value
```C#
var field = _getBackingField(myObjectToChange, "PropertyName");
field.SetValue(myObjectToChange, NewValue);
```

**Comment by smitpatel** [comment]
Marking for re-triage to decide what to do next for this.

**Comment by bricelam** [comment]
Given that the semantics of read-only auto properties are the same as `readonly` fields, should we even be trying to set these fields in the first place?

**Comment by ilmax** [comment]
+1 for materialization via constructor. This is a good feature and lot of people would like to have this.

**Comment by rowanmiller** [comment]
Discussed in triage and agreed that we should not include a getter-only property in the model by convention. Logged these two issues as a result of the discussion:
- https://github.com/aspnet/EntityFramework/issues/1527
- https://github.com/aspnet/EntityFramework/issues/1526

**Comment by divega** [comment]
Clearing up milestone so that we can review this in triage.
