### ISSUE TITLE
Wrong parameter sent when setting a foreign key

### ISSUE THREAD

**Issue by ThomasWeiss** [dotnet/efcore#13123]
EF Core version: 2.1.2
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL v2.1.1.1

Using the following entity:
```C#
[Table("caps_user_shares")]
internal class CapsUserShareEntity
{
    [Column("caps_id")]
    public Guid CapsId { get; set; }
    [Column("user_id")]
    public Guid UserId { get; set; }
    [Column("location")]
    [Required] public Point Location { get; set; }

    public CapsEntity Caps { get; set; }
    public UserAccountEntity User { get; set; }
}
```
and the following foreign key rule:
```C#
modelBuilder.Entity<CapsUserShareEntity>().HasOne(s => s.User).WithMany().HasForeignKey(s => s.UserId);
```

I tried to add such an entity and set its `UserId` to `Guid.Empty` which corresponds to a (special) user that exists in the DB:
```C#
Context.CapsUserShares.Add(new CapsUserShareEntity
{
    CapsId = @event.EntityId,
    UserId = Guid.Empty,
    Location = PointFromLocationModel(@event.Location)
});
```
This failed with a violation of the foreign key constraint I described above. Tracing the SQL statements with `EnableSensitiveDataLogging`, I saw that the parameter sent for the `user_id` column was not `Guid.Empty` but some other Guid that I couldn't match with anything else in the DB (so presumably the result of a `Guid.NewGuid()`).

The workaround I found was to set the `User` property to that special user I had to retrieve first:
```C#
var publicUser = await Context.UserAccounts.FirstOrDefaultAsync(a => a.Id == Guid.Empty);
...
Context.CapsUserShares.Add(new CapsUserShareEntity
{
    CapsId = @event.EntityId,
    User = publicUser,
    Location = PointFromLocationModel(@event.Location)
});
```
This approach does result in the right parameter being sent.

My intuition is that `Guid.Empty` being `default(Guid)`, it is not considered as a set value by EF?

**Comment by ajcvickers** [comment]
@ThomasWeiss This is because EF will by default generate GUID values for new entities which do not already have a GUID value set. The sentinel for determining if the GUID value is set or not is the CLR default for the types, which in this case is the empty GUID.

If the GUID values are being created by the application, then this can be switched off, in which case the empty GUID will be treated like any other GUID value:
```C#
    [Column("caps_id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid CapsId { get; set; }
```

**Comment by ThomasWeiss** [comment]
@ajcvickers Thanks a lot for that prompt reply!

**Comment by ThomasWeiss** [comment]
@ajcvickers Adding that option (either as an attribute or with the fluent API) doesn't solve the problem as a new GUID is still injected by EF. Could there be a side-effect with that property also being a foreign key?
I can try to prepare a full repro if necessary.

**Comment by roji** [comment]
@ThomasWeiss I just checked and adding the attribute as suggested by @ajcvickers indeed makes a zero GUID appear in the database. Please double-check your code and if there's still an issue, try to submit a (minimal) repro.

**Comment by ThomasWeiss** [comment]
I can't reproduce it in a minimal project, yet I'm positive that the attribute is correctly applied to the property... must be some kind of side-effect that I haven't found yet. I will close the issue as I've no evidence that it comes from EF at this stage.

**Comment by ThomasWeiss** [comment]
@ajcvickers @roji I think I finally got a minimal repro, I put the .cs and .csproj in [this gist](https://gist.github.com/ThomasWeiss/e637284b5453f5ac3bea25f9abfac612).

When I:
- create the migration
- apply the migration
- patch the DB to create the user with `insert into users (id) values('00000000-0000-0000-0000-000000000000')` (would normally be patched directly into the migration)
- debug the project
I got an exception on `SaveChanges()` complaining about the foreign key constraint violation I mentioned earlier in the ticket.

Hope this helps and let me know if you need any further information, thanks!

**Comment by roji** [comment]
@ThomasWeiss, thanks for the repro, I can see something unexpected happening (for me). It does seem that EF Core is generating Guid values for `UserId` even though `DatabaseGeneratedOption.None` is specified. Removing the foreign-keyness of `UserId` removes this behavior (and a zero Guid is properly inserted).

@ajcvickers I don't have time at the moment to dig further but does the foreign-keyness somehow override `DatabaseGeneratedOption.None`?

**Comment by ThomasWeiss** [comment]
If it can help, and from the steps I went through in order to get the repro, it may come from the fact that `UserId` is both a foreign key and part of a composite primary key. Not 100% sure though.

**Comment by ajcvickers** [comment]
@ThomasWeiss Yes, the DatabaseGeneratedOption needs to go on the primary key--sorry I wasn't clear about this. This is because when generating key values it is very unusual that a key value should be generated directly for an FK property, since it would not match any existing PK. Instead, PK values typically get their value via propagation from the primary key value, rather than having a new value generated.

**Comment by ThomasWeiss** [comment]
@ajcvickers Thanks a lot for that clarification.
For those running in the same issue and looking at my repro, the problem got solved by applying the         `[DatabaseGenerated(DatabaseGeneratedOption.None)]` attribute to the `Id` of `UserEntity`.
