### ISSUE TITLE
Generated SQL for `datetime` filter is using `datetime2` format, resulting in SqlException

### ISSUE THREAD

**Issue by johnmwright** [dotnet/efcore#13133]
See also: https://stackoverflow.com/questions/52048935/how-do-i-get-entityframeworkcore-generated-sql-to-use-the-right-format-for-datet

I'm using [Microsoft.EntityFrameworkCore.SqlServer v2.1.2](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/2.1.2) (and have also tried v2.2.0-preview1-35029) and am using LINQ to fetch a collection of entities from an Azure SqlServer database, filtering on a DateTime field.  

However, the SQL generated by the LINQ statement uses a string-based DateTime value that SqlServer rejects with this error:

> Conversion failed when converting date and/or time from character string.

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Conversion failed when converting date and/or time from character string.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
System.Data.SqlClient.SqlDataReader.TryHasMoreRows(out bool moreRows)
System.Data.SqlClient.SqlDataReader.TryReadInternal(bool setTimeout, out bool more)
System.Data.SqlClient.SqlDataReader.Read()
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.BufferlessMoveNext(DbContext _, bool buffer)
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities<TOut, TIn>(IEnumerable<TOut> results, QueryContext queryContext, IList<EntityTrackingInfo> entityTrackingInfos, IList<Func<TIn, object>> entityAccessors)+MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor<T>+EnumeratorExceptionInterceptor.MoveNext()
System.Collections.Generic.List<T>.AddEnumerable(IEnumerable<T> enumerable)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
WrightfullySite.Controllers.API.DeskReadingController.GetReadings(Nullable<DateTime> sinceDate) in DeskReadingController.cs
```

Based on the datetime format strings in [`SqlServerDateTimeTypeMapping.cs`](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs#L18-L20), it appears the [`SqlLiteralFormatString` logic](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs#L69-L74) is falling back to the `DateTime2FormatConst` when the column is actually defined as `datetime`.

**My expectation is that the framework would use the `DateTimeFormatConst` for this query, given that the underlying column type is `datetime`.**

The EntityFramework model I'm using looks like this:

    public class DeskReading
    {
        public int DeskReadingId { get; set; }
        //... some other fields ...
        public DateTime Timestamp { get; set; }
    }

And my LINQ to query the values looks like this:

	IQueryable<DeskReading> readings = 
		_dbContext.DeskReadings
				.OrderBy(gr => gr.Timestamp)
				.Where(gr => gr.Timestamp > new DateTime(2017, 05, 01));

    readings.ToList();

And the SQL that's generated by that looks like this: _(note: I used this [extension method](https://stackoverflow.com/a/51583047/682840) to extract the SQL)_

    SELECT [gr].[DeskReadingId] --...some other fields ...
    FROM [DeskReadings] AS [gr]
    WHERE [gr].[Timestamp] > '2017-05-01T00:00:00.0000000'
    ORDER BY [gr].[Timestamp]

Note that the value for the filter is `'2017-05-01T00:00:00.0000000'`, which matches the `DateTime2FormatConst` format.

If I run that SQL directly on the SqlServer via SSMS, I get the same error:

[![enter image description here][1]][1]

But if I change the filter to use `'2017-05-01 00:00:00.000'` (the `DateTimeFormatConst` format), it works fine:

    SELECT [gr].[DeskReadingId] --...some other fields ...
    FROM [DeskReadings] AS [gr]
    WHERE [gr].[Timestamp] > '2017-05-01 00:00:00.000'
    ORDER BY [gr].[Timestamp]
	

  [1]: https://i.stack.imgur.com/gOZry.png

Here's the create script for the table:

    CREATE TABLE [dbo].[DeskReadings](
    	[DeskReadingId] [int] IDENTITY(1,1) NOT NULL,
    	[SoilMoistureSensor1] [int] NOT NULL,
    	[SoilMoistureSensor2] [int] NOT NULL,
    	[LightLevel] [int] NOT NULL,
    	[TemperatureF] [real] NOT NULL,
    	[HumidityPercent] [real] NOT NULL,
    	[Timestamp] [datetime] NOT NULL,
     CONSTRAINT [PK_dbo.DeskReadings] PRIMARY KEY CLUSTERED 
    (
    	[DeskReadingId] ASC
    )WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]

----

Note: I was able to resolve this issue by attributing the DateTime property in the model class, as follows:
```
        [Column(TypeName="datetime")]
        public DateTime Timestamp { get; set; }       
```

### Further technical details
EF Core version: v2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 
Operating system: Windows 10 Pro 1803 build 17134.228 
IDE: Visual Studio Enterprise 2017 v15.8.1
Database: Azure SqlServer (12.0.2000.8)

**Comment by smitpatel** [comment]
By convention, EF Core maps `DateTime` property to `datetime2` column in database. (for better accuracy of stored values). That is the reason we are generating `datetime2` literal. If your database is using something other than conventional then you need to configure it properly in EF Core. Using ColumnAttribute the way you showed is one way. You can also use Fluent API to do the same. If your EF Core model does not match your database schema then you are likely to run into errors at runtime.
