### ISSUE TITLE
Getting "attempt was made to lazy-load navigation property on detached entity" error when using AsNoTracking despite using Include to eager fetch children

### ISSUE THREAD

**Issue by jonathanmoffatt** [dotnet/efcore#13173]
I'm using Entity Framework Core 2.1.2 and am performing a query using AsNoTracking. I'm using Include to bring in my navigation property (a collection).

If all my entities have at least one child in their collection then it all works fine.

However, if any of my entities have no children then I get an error:

```
System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'Children' on detached entity of type 'ParentProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'
```

### Steps to reproduce

Here's a standalone example that can be run from a console app (use NuGet to bring in Microsoft.EntityFrameworkCore 2.1.2, Microsoft.EntityFrameworkCore.Proxies 2.1.2, Microsoft.EntityFrameworkCore.InMemory 2.1.2):

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace LazyLoadingIssue
{
    public class Parent
    {
        public int Id { get; set; }
        public string ParentName { get; set; }
        public virtual ICollection<Child> Children { get; set; }
    }

    public class Child
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public virtual Parent Parent { get; set; }
        public string ChildName { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            SetupDatabase(setupToFail: true);
            PerformTest();

            Console.WriteLine("Press any key to finish");
            Console.ReadLine();
        }

        private static void PerformTest()
        {
            using (var db = new MyContext())
            {
                try
                {
                    IQueryable<Parent> parents = db.Rounds.Include(r => r.Children).AsNoTracking();
                    foreach (Parent parent in parents)
                    {
                        Console.WriteLine($"Parent (Id={parent.Id}) '{parent.ParentName}'");
                        foreach (Child child in parent.Children)
                        {
                            Console.WriteLine($"  - Child (Id={child.Id}, ParentId={child.ParentId}) '{child.ChildName}'");
                        }
                    }

                    Console.WriteLine("** WORKED **");
                }
                catch (Exception ex)
                {
                    Console.WriteLine("** FAILED **");
                    Console.WriteLine(ex);
                }
            }
        }

        private static void SetupDatabase(bool setupToFail)
        {
            using (var db = new MyContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var parent1 = new Parent
                {
                    ParentName = "First sample parent (has children)",
                    Children = new List<Child>
                    {
                        new Child {ChildName = "child-1"},
                        new Child {ChildName = "child-2"},
                        new Child {ChildName = "child-3"}
                    }
                };
                var parent2 = new Parent
                {
                    ParentName = $"Second sample parent ({(setupToFail ? "with no children" : "has children")})",
                    Children = new List<Child>()
                };
                if (!setupToFail)
                    parent2.Children.Add(new Child {ChildName = "child-4"});
                db.AddRange(parent1, parent2);
                db.SaveChanges();
            }
        }
    }


    public class MyContext : DbContext
    {
        public DbSet<Parent> Rounds { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
//                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                .UseInMemoryDatabase(databaseName: "_modelApp")
                .UseLazyLoadingProxies()
                ;
        }
    }

}
```

**Comment by ajcvickers** [comment]
@jonathanmoffatt This is because lazy-loading isn't supported for NoTracking queries (#10042) but we tried to not make it throw if it looked like lazy-loading wasn't needed. In retrospect it might have been better to always throw. Note that the warning can be configured to not throw using `ConfigureWarnings` in the DbContextOptionsBuilder.

**Comment by kakins** [comment]
I may be confused, but did the response to this issue address the question?  I believe in the original code example he's eagerly loading Children (`.Include(r => r.Children)`).  

The reason I ask is because I'm encountering the same issue, but it only happens with Collection navigation properties.

The following throws an exception only for `d.Amounts`.
```
                await dbContext.CostingAllocationDetails
                    .Include(d => d.Interval)
                    .ThenInclude(i => i.Allocation)
                    .ThenInclude(a => a.Position)
                    .ThenInclude(p => p.Worker)
                    .Include(d => d.Amounts)
                    .AsNoTracking()
                    .Take(50)
                    .ToListAsync())
```

**Comment by huby01** [comment]
> I may be confused, but did the response to this issue address the question? I believe in the original code example he's eagerly loading, not lazy loading, Children (`.Include(r => r.Children)`).
> 
> The reason I ask is because I'm encountering the same issue, but it only happens with Collection navigation properties.
> 
> The following throws an InvalidOperationException only for `d.Amounts`.
> 
> ```
>     var details = await dbContext.CostingAllocationDetails
>         .Include(d => d.Interval)
>         .ThenInclude(i => i.Allocation)
>         .ThenInclude(a => a.Position)
>         .ThenInclude(p => p.Worker)
>         .Include(d => d.Amounts)
>         .AsNoTracking()
>         .Take(50)
>         .ToListAsync())
> 
>     foreach (var detail in details)
>         detail.Amounts // this fails when I try to access 
> ```

Hello @kakins , I am presently facing this situation. Have you solved this issue?

**Comment by danikun** [comment]
Hi I'm facing this same issue with 2.2.4, I don't know why it was closed. 

If you do an include and the collection you are including is empty, instead of setting the property to an empty collection it keeps the navigation proxy. 

Please reopen the issue

**Comment by kramffud** [comment]
In an EF Core Lazy Loading scenario where Navigation properties were filled in a data layer via DbSet<>.Include() clause(s) while the Entity was attached to a DbContext and then that Entity was detached and passed up to a business layer, consider adding this to your DbContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) method:
`optionsBuilder.ConfigureWarnings(warn => warn.Ignore(CoreEventId.LazyLoadOnDisposedContextWarning));`
The error will be ignored and the values that were originally Include()d will be returned.

**Comment by arnileibovits** [comment]
I'm getting the same error on EF Core 3.1.3, but on only when using **inheritance** (table-per-hierarchy).

I'm eagerly loading a collection, which is part of an abstract class. I can see the correct SQL JOIN generated, and in the debugger I can see private fields populated correctly (eagerly). But I'm still getting "An attempt was made to lazy-load navigation property ... on detached entity".

Should I create a code sample to reproduce this?

**Comment by kramffud** [comment]
@arnileibovits - My experience with POCO model inheritance in EF was so miserable, I ditched it for entirely flat POCOs.  EF's heavy-handed mgt/requirements for a Discriminator Column conflicted with my control freak issues.  Have you tried suppressing the error per my previous post?  If so, your issue may be more of one where EF ignores the warning on your parent/base object, but not the inherited child object?  Those are the types of frustrations that drove me away from table-per-hierarchy.

**Comment by ajcvickers** [comment]
@arnileibovits If you think you're hitting an issue that is not covered by #10042, then please file a new issue and please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by arnileibovits** [comment]
> @arnileibovits If you think you're hitting an issue that is not covered by #10042, then please file a new issue and please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

No, my issue is the opposite. While #10042 is about lazy loading, my issue is with eager loading (while tracking is turned off). The entities are actually loaded, but an exception is mistakenly thrown.

NB! This only happens when using inheritance (TPH).

I'll see if I can put a sample together.

**Comment by lucaswalter** [comment]
I am also the same error on EF Core 3.1.4, but on only when using inheritance from a base abstract class. Is there an update or workaround for this?

**Comment by ajcvickers** [comment]
@lucaswalter  If you think you're hitting an issue that is not covered by #10042, then please file a new issue and please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by arnileibovits** [comment]
I've added a repro here: #21593
