### ISSUE TITLE
Computed field can be configured on a derived type

### ISSUE THREAD

**Issue by slubowsky** [dotnet/efcore#13175]
Created some entity types using inheritance. Have one field that needs to be an actual value in base but a computed value in derived.

Not expecting it to work, but trying just in case, I used fluent API to configure computed property on derived type only . Everything compiles, migration gets created, table gets created with computed field - but as coded, intention was for this to be for derived type only, not base.

I didn't expect this to be supported, but might be a good idea if some exception was thrown at build or migration rather then it appearing to work.

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
@slubowsky Yeah, I can't see how this would work given that the column in the database is either computed or it isn't. However, can you post code showing your attempt to configure it differently on the base verses the derived type?

**Comment by slubowsky** [comment]
@ajcvickers All I did was something like:
```
modelBuilder.Entity<Derived>()
                .Property(p => p.Days)
                .HasComputedColumnSql("DATEDIFF(DAY, [StartDate], [EndDate])");
```
where Days is defined in the base class and computed column is NOT set up for base. Table gets computed property (even for base) due to setting it up on derived.

**Comment by ajcvickers** [comment]
@slubowsky Thanks for posting that. We discussed in triage and decided on no action for now, but we may need to revisit what it means to configure for base verses derived types when considering TPC mapping.
