### ISSUE TITLE
Trouble migrating to AspNetCore.App on Linux

### ISSUE THREAD

**Issue by j-hudecek** [dotnet/efcore#13184]
I have a web app created from 2.0 template that uses EF Core with SQLite and references AspNetCore.All.

I've read [that it will be deprecated](https://github.com/aspnet/Announcements/issues/287) so I've decided to move away from it.

I've removed the .All package and added the .App, added System.Data.SQLite (v.1.0.109), added the other necessary packages to get rid of compiler errors and successfully built and ran on Windows. 

When I've tried to deploy to Linux I got these journal entries:

    Aug 31 23:12:47 server dotnet-myapp[14355]: Error:
    Aug 31 23:12:47 server dotnet-myapp[14355]:   An assembly specified in the application dependencies manifest (myappcore.deps.json) was not found:
    Aug 31 23:12:47 server dotnet-myapp[14355]:     package: 'System.Data.SQLite.Core', version: '1.0.109.1'
    Aug 31 23:12:47 server dotnet-myapp[14355]:     path: 'runtimes/linux-x64/lib/netstandard2.0/SQLite.Interop.dll'

I've tried removing reference to Microsoft.EntityFrameworkCore.Sqlite and using Microsoft.EntityFrameworkCore.Sqlite.Core instead according to https://github.com/aspnet/EntityFrameworkCore/issues/9505#issuecomment-324420209

    Aug 31 23:14:29 server dotnet-myapp[14908]:   An assembly specified in the application dependencies manifest (myappcore.deps.json) was not found:
    Aug 31 23:14:29 server dotnet-myapp[14908]:     package: 'SQLitePCLRaw.lib.e_sqlite3.linux', version: '1.1.11'
    Aug 31 23:14:29 server dotnet-myapp[14908]:     path: 'runtimes/linux-x64/native/libe_sqlite3.so'

I've added a reference to SQLitePCLRaw.bundle_e_sqlite3:

     Aug 31 23:30:46 server dotnet-myapp[20825]:   An assembly specified in the application dependencies manifest (myappcore.deps.json) was not found:
     Aug 31 23:30:46 server dotnet-myapp[20825]:     package: 'SQLitePCLRaw.bundle_e_sqlite3', version: '1.1.11'
     Aug 31 23:30:46 server dotnet-myapp[20825]:     path: 'lib/netcoreapp/SQLitePCLRaw.batteries_e_sqlite3.dll'

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlLite
Operating system: Ubuntu 16.05
IDE: Visual Studio 2017 15.7

**Comment by ajcvickers** [comment]
@j-hudecek ASP.NET/EF Core use the `Microsoft.Data.Sqlite` package. `System.Data.SQLite` is the older third-party SQLite provider which was never part of the All package.
