### ISSUE TITLE
Cannot open the database XXX requested by the login

### ISSUE THREAD

**Issue by xenoxsis** [dotnet/efcore#13189]
Hi,

I recently started a new .Net Core Web Application and I started by setting up the identity, everything worked fine, when I called Update-Database on my own local sql instance, it was creating the database no problem and everything worked.

I then started adding some custom models, and added the DbSet property to the context. That's when I ran into a problem. When I deleted the database and ran the "Update-Database" command again, it would create my database, but fail with: "There is already an object named 'AspNetRoles' in the database".

I search a bit around for that and found that in my DbInitializer I had "_context.Database.EnsureCreated()" and that people recommended I removed this, so I commented it out.

Now, it creates the DB (but no tables) and I got a different error: 

Cannot open database "<database>" requested by the login. The login failed.
Login failed for user 'MicrosoftAccounts/<my windows account username>'.

No matter what I do I get either of those two errors with Update-Database.

I tried adding a SQL user and connecting with that
And I tried deleting Migrations Folder and adding a new migration WITH my changes

Let me know if there's more information I can add to this case it help figure out what causes this.

Thank you

**Comment by ajcvickers** [comment]
@xenoxsis The [documentation on customizing the ASP.NET Core Identity model](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1) may help. If you are still running into issues, then please post a runnable project/solution or complete code listing that demonstrates that behavior you are seeing.

**Comment by xenoxsis** [comment]
@ajcvickers Hi Mr. Vickers - I have uploaded the project here: https://github.com/xenoxsis/Auctioneer

**Comment by ajcvickers** [comment]
@xenoxsis The call to `dbInitializer.Initialize();` is attempting to access the database while EF tooling is obtaining the model to use. If you're going to do database initialization on startup, then it needs to happen only when the application starts, and hence cannot go in the Configure method. For a production app, I would strongly recommend not doing database deployment or seeding when the application starts, but if you're going to do this, then one way is to create a scope and an initializer in the Main method:
```C#
public static void Main(string[] args)
{
    var webHost = BuildWebHost(args);

    using (var scope = webHost.Services.CreateScope())
    {
        var dbInitializer = scope.ServiceProvider.GetService<IDbInitializer>();
        dbInitializer.Initialize();
    }

    webHost.Run();
}
```
