### ISSUE TITLE
Migration errors with the located assembly's manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by andrescorrea** [dotnet/efcore#13198]
I'm trying to generate a database from the terminal of VS code using SQL Operations Studio, whenever I try to generate a migration this error occurs.

`dotnet ef migrations add init`

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly '/usr/local/share/dotnet/sdk/2.1.401/DotnetTools/dotnet-ef/2.1.2/tools/netcoreapp2.1/any/tools/netcoreapp2.0/any/ef.dll'. The located assembly's manifestdefinition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

This is how my .csproj looks like now
```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.2" />
  </ItemGroup>
</Project>
```

Any workaround for this?

**Comment by ajcvickers** [comment]
@andrescorrea Can you please post a project/solution that reproduces the issue you are seeing so that we can investigate more.

**Comment by andrescorrea** [comment]
I fixed the error adding:
 ```csproj
<RuntimeIdentifier>osx.10.12-x64</RuntimeIdentifier>

inside the <PropertyGroup> tag group
