### ISSUE TITLE
SQLite+SQLCipher (Android): Connection stays open after EnsureDeleted()

### ISSUE THREAD

**Issue by Follpvosten** [dotnet/efcore#13193]
I am developing an Android app using Xamarin.Forms (with a .NET Standard library containing the code). It is using EntityFramework Core with the Sqlite backend.
When a user successfully authenticates inside the app, a local SQLite database is created (using `DbContext.Database.EnsureCreated();`); when the user logs out again, the database is to be destroyed (using `DbContext.Database.EnsureDeleted();`).
All of that works fine, however, when trying to log in again (e.g. with a different user), the following exception is thrown:

```
Exception message: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Teams" already exists'.
Stack trace:  at easyTeam.BridgeFunctionManager.Call (System.String name, System.String args) [0x000d5] in C:\Source\easyTeamOrganiser-ng\Mobile\Mobile\BridgeFunctionManager.cs:63 
  at easyTeam.GeneralBridgeFunctions.CallFunctionSync (System.String name, System.String args) [0x0006f] in C:\Source\easyTeamOrganiser-ng\Mobile\Mobile\GeneralBridgeFunctions.cs:146
```

A bit of investigation (this is a rooted Android device) shows that on login, the connection is opened (and therefore a file descriptor is created):

```
1|i9300:/ # ls -l /proc/3151/fd/ | grep db3                                    
lr-x------ 1 u0_a97 u0_a97 64 2018-09-01 10:01 144 -> /data/data/com.religiox.easyteam/files/easyTeam.db3
```

After logging out, the output of that command changes to this:

```
lr-x------ 1 u0_a97 u0_a97 64 2018-09-01 10:01 144 -> /data/data/com.religiox.easyteam/files/easyTeam.db3 (deleted)
```

So the file is still being accessed by the process, which probably means the connection is still open. It therefore accesses the deleted database and errors out because every table is still in memory.
EDIT: Manually closing the connection also doesn't change anything.

### Steps to reproduce
I have created [an example project](https://github.com/Follpvosten/SQLiteProblem) which, at least for me, reliably reproduces the issue.

* Press the first button; the database is created.
* Press the second button; the database is filled with 3 test datasets.
* Press the second button again; a correct error is displayed.
* Press the third button; now, the database is deleted, but the file descriptor is still open (`lr-x------ 1 u0_a98 u0_a98 64 2018-09-02 13:32 59 -> /data/data/com.companyname.SQLiteProblem/files/testdb.db3 (deleted)`)
* Press any of the first two buttons and you get an error which does not make sense anymore, as the database doesn't exist.
* Restart the app and now you can start over because the deleted database is no longer in memory.

### Further technical details
EF Core version: 2.1.2
Database Provider: Sqlite/Sqlite.Core
Operating system: Android (EDIT: Version is 7.1)
IDE: Visual Studio 2017 15.7.4 and also Visual Studio 2017 15.8

**Comment by Follpvosten** [comment]
Alright, I'll look into doing that. I had already thought of that beforehand, but since there are 3-5 different projects involved (SQLitePCL, SQLCipher, EF Core and SQLite itself, and maybe also Mono to some extent), I decided to go to the high-level project I actually use.

I will go to the other projects one after another and see what I can do.

**Comment by bricelam** [comment]
Do all your SQLitePCLRaw.* package versions align? We had [similar issues](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/524) reported in the past...

**Comment by Follpvosten** [comment]
@bricelam I have now had time to check that; adding a dependency to SQLitePCLraw.core, Version 1.1.11, doesn't change anything. Which other packages should I try?

I would think that a completely fresh project such as my "SQLiteProblem" example should use all the right package versions by default, but I don't know that, of course.

**Comment by bricelam** [comment]
You're right. 2.1 projects should all be at 1.1.11.
