### ISSUE TITLE
Add-Migration behavior with LogLevel

### ISSUE THREAD

**Issue by daniloak** [dotnet/efcore#13212]
When I am running Add-Migrations I am getting the following error message

`An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: Configuration value 'Info' is not supported.
Unable to create an object of type 'MyContext'. Add an implementation of 'IDesignTimeDbContextFactory<MyContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.`

When I change the appsettings.developments, LogLevel-->Default = Debug everything works well even without having the IDesignTimeDbContextFactory and keeping the method CreateWebHostBuilder as it is.

### Steps to reproduce
- Create a simple API with .net core 2.1
- Add a DbContext and a simple entity
- Try to run add-migration 

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: (e.g. Visual Studio 2017 15.8)

[WebApplication6.zip](https://github.com/aspnet/EntityFrameworkCore/files/2357277/WebApplication6.zip)

[2018-09-04 14.39.zip](https://github.com/aspnet/EntityFrameworkCore/files/2357289/2018-09-04.14.39.zip)

**Comment by ajcvickers** [comment]
@daniloak Can you post a runnable/project solution that demonstrates the behavior you are seeing so that we can investigate further.

**Comment by daniloak** [comment]
I edited the issue, I also added a video showing the issue, please, do not consider the "notepad" part in the video

**Comment by ajcvickers** [comment]
@daniloak I downloaded your project and tried running various migration commands. They all worked fine for me, which suggests something about your machine setup. I would try clearing your NuGet caches, reinstalling the .NET Core SDK, and possibly Visual Studio.

**Comment by daniloak** [comment]
Did you use Debug or Info in the log level?

**Comment by ajcvickers** [comment]
@daniloak I didn't change anything. I expected the project to be setup to reproduce the issue you are seeing.

**Comment by daniloak** [comment]
Again with the parameter changed. 

[WebApplication6.zip](https://github.com/aspnet/EntityFrameworkCore/files/2357932/WebApplication6.zip)

**Comment by ajcvickers** [comment]
@daniloak Thanks, I am able to reproduce this now--we will investigate.

**Comment by smitpatel** [comment]
You cannot use just `Info` you need to use exact string version of the `LogLevel` enum as in this file. https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Abstractions/LogLevel.cs
