### ISSUE TITLE
Where condition missing on Left join grouped sub query

### ISSUE THREAD

**Issue by tai-yi** [dotnet/efcore#13216]
I want left join twice, first is a grouped sub query, second is a table.

The major translation works well.

But the condition has some problem, if LINQ condtion constains the grouped query part, the translation will not translate condition part.

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

#### Tables
**Users**
userid, username
**SupperFCWacher**
id, userid
**FCWacher**
id , userid, dealerid

#### LINQ
```c#
var data = from u in _dbContext.Users
                       join s in _dbContext.SupperFCWachers
                       on u.Id equals s.UserId
                       into su
                       from m in su.DefaultIfEmpty()

                       join wg in (from w in _dbContext.FCWachers group w by w.UserId into g select new { UserId = g.Key, Count = g.Count() }
                       )
                       on u.Id equals wg.UserId
                       into wu
                       from n in wu.DefaultIfEmpty()
                       where m.Id != null || n.Count > 0
                       select new FCWacherSummaryModel()
                       {
                           UserId = u.Id,
                           UserName = u.UserName,
                           Description = m == null ? "" : "All Dealers"
                       };
```
#### Translated SQL
```SQL
SELECT [t].[UserId], [t].[Count], [s].[Id], [u].[UserID] AS [UserId0], [u].[UserName], CASE
    WHEN [s].[Id] IS NULL
    THEN N'' ELSE N'All Dealers'
END AS [Description]
FROM [UserDefinition] AS [u]
LEFT JOIN [SupperFCWacher] AS [s] ON [u].[UserID] = [s].[UserId]
LEFT JOIN (
    SELECT [w].[UserId], COUNT(*) AS [Count]
    FROM [FCWacher] AS [w]
    GROUP BY [w].[UserId]
) AS [t] ON [u].[UserID] = [t].[UserId]
--where s.id is not null or t.Count>0   --!!this condition will not be translated.
```
### Another Issue

If FCWacher inherit SupperFCWacher, the translated sql will be error.

### Further technical details
EF Core version: (2.1.1)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by icesasoftcorp** [comment]
please the solution to this problem
