### ISSUE TITLE
Many to many self reference table - guid Id changes itself

### ISSUE THREAD

**Issue by blowdart** [dotnet/efcore#13225]
_From @john345331 on September 5, 2018 18:51_

https://stackoverflow.com/questions/52191661/many-to-many-self-reference-table-guid-id-changes-itself

_Copied from original issue: aspnet/Home#3500_

**Comment by blowdart** [comment]
_From @john345331 on September 5, 2018 18:52_

Also a better documentation should be added for self referencing one-to-one and many-to-many tables

**Comment by ajcvickers** [comment]
Covered by https://github.com/aspnet/EntityFramework.Docs/issues/815
