### ISSUE TITLE
Feature Request: LINQ to table parameter

### ISSUE THREAD

**Issue by awr** [dotnet/efcore#13239]
Use Case: Ability to use query against a variable number of inputs, for a batching scenario. Ideally I'd like to have the same query plan used whether there are 2 input values or 100 input values, in conjunction with a linq query.

Hypothetical linq:
```c#
public class MyDbContext : DbContext
{
    // ... or however it makes sense to define a udt
    public DbParameter<IdUdt> IdTable { get; set; }
}

public class IdUdt : DbTableParameter<long>
{
    // not sure if this would be necessary, but could enable the With function below
    protected override void Populate(long value)
    {
        this.Id = value;
    }

    public long Id { get; set; }
}

public static class Execution
{
    public static async Task<List<Person>> GetWithTableParameterAsync(IEnumerable<long> ids, CancellationToken cancellationToken) 
    {
        using (var db = new MyDbContext()) {
            var query = from person in db.People
                        join id in db.IdTable.With(ids) on person.PersonId equals id.Id
                        select person;
            return await query.ToListAsync(cancellationToken);
        }
    }
}
```

Ideally this generates t-sql that looks something like:
```t-sql
declare @p0 dbo.udt_Id
insert into @p0 values(1)
insert into @p0 values(2)
insert into @p0 values(3)
insert into @p0 values(4)

exec sp_executesql N'SELECT 
    [Extent1].[PersonID] AS [Id], 
    [Extent1].[Name] AS [Name]
    FROM [dbo].[People] AS [Extent1]
    INNER JOIN @p0 i ON t.[PersonID] = i.[ID]',N'@ids [dbo].[udt_TableBigintId] READONLY',@ids=@p0
```

Note that I realize I can already do something similar with a `Contains` -- something like: 
```c#
    public static async Task<List<Person>> GetWithInClauseAsync(IEnumerable<long> ids, CancellationToken cancellationToken) 
    {
        using (var db = new MyDbContext()) {
            var query = from person in db.People
                        where ids.Contains(person.PersonId)
                        select person;
            return await query.ToListAsync(cancellationToken);
        }
    }
```

The difference is in the sql that gets generated, since it embeds the id values into the query (or if using an expression tree walker, I believe it's possible to change this to have n equality checks with sql parameters). I'd prefer a single query plan to either of these solutions.

I also realize that it's possible to use table parameters with raw sql, but the challenge there is that I can't easily inject it into the middle of a complex query if I want to use LINQ.

**Comment by awr** [comment]
Anything I can do to help this along? I'd be happy to put together a PR if you point me in the general direction of where you'd want to see this (assuming it fits with your direction for the project).

**Comment by divega** [comment]
Note for triage: I think this belongs in the backlog for now, but since @awr is interested in contributing we can discuss the design in general terms.

**Comment by divega** [comment]
Updated my previous comment to reflect that client evaluation isn't an option anymore after 3.0.

**Comment by AndersMalmgren** [comment]
I think the syntax should be more close to that of Set<TEntity>()

something along the lines of  

```
IQueryable<TEntity> TableValueParameterSet<TEntityId>(IEnumerable<TEntityId> ids) where TEntity : struct
```

By conventon EF could use a table value paramater type named `$"ef_core_{nameof(TEntity)}_tvp"` or similar

**Comment by AndersMalmgren** [comment]
If EF core eventually support insert / delete / update directly on IQueryables you could even do

```
ctx.TableValueParameterSet(ids)
  .Join(ctx.Set<MyEntity>(), id => id, e => e.Id, (id, e) => e)
  .Delete();
```

If we extend the table value parameter mechanics to support custom entity types not just simple value types  we could even bulk insert with a crazy high level of performance. Something like.

```
var batch = Enumerable.Range(0, 2000).Select(i => new MyEntity{ Foo = $"Hello World_{i}" }).ToList();
ctx.TableValueParameterSet(batch)
.Insert();
```

Possibilities are endless  :D

**Comment by AndersMalmgren** [comment]
This issue need more love from the ef core team.

**Comment by Alexander-Bartosh** [comment]
Any update on this one ? 
Is there any other approach to build ONE EF LINQ query that is using/filtering on a TVP (e.g. list of Ids) ?

**Comment by hauntingEcho** [comment]
Rather than using a temp table or a TVP, couldn't this translate to joining either a CTE or a VALUES list?  for example:
```
SELECT a.*
FROM People AS a  
INNER JOIN (VALUES (1), (2), (3), (4)) AS vals_0(param_0)
ON a.PersonID = vals_0.param_0
;
```

or:
```
WITH cte_0(param_0) AS (VALUES (1), (2), (3), (4))
SELECT a.*
FROM People AS a  
INNER JOIN cte_0
ON a.PersonID = cte_0.param_0
;
```

This could also be extended to object types, e.g. `WITH cte_0(id, name) AS (VALUES (1, 'alice'), (2, 'bob'))`

**Comment by willnationsdev** [comment]
Just stumbled upon this issue. I would love to have a robust, built-in solution for this problem. However, until then, I also wanted to share an EF Core extension I found that accomplishes a similar task: [EntityFramework.MemoryJoin](https://github.com/neisbut/EntityFramework.MemoryJoin) (for anyone else who needs an immediate solution).

You basically just add a dedicated `DBSet` to your `DbContext` with a generic parameter of whatever DTO you want to use for your TVP so-to-speak. If it's `protected`, then EF Core won't try to generate an entire table for it in the database, but you'll still be able to incorporate instances of it into queries.

By default, they have a [`QueryModelClass` type](https://github.com/neisbut/EntityFramework.MemoryJoin/blob/master/src/EntityFrameworkCore.MemoryJoin/QueryModelClass.cs) with 3 properties each of types `string`, `bool`, `long`, `double`, `Guid`, and `DateTime`. Should accommodate most use cases of joining on a single table's columns. However, if you need, say, 4 strings, you can create and provide your own DTO class to use instead.

I haven't successfully run a query that supplies multiple lists in a single request so not sure if that's supported or if I'm just doing things incorrectly. At least gives a general idea of how something like this could be implemented though.

**Comment by erwan-joly** [comment]
> Just stumbled upon this issue. I would love to have a robust, built-in solution for this problem. However, until then, I also wanted to share an EF Core extension I found that accomplishes a similar task: [EntityFramework.MemoryJoin](https://github.com/neisbut/EntityFramework.MemoryJoin) (for anyone else who needs an immediate solution).
> 
> You basically just add a dedicated `DBSet` to your `DbContext` with a generic parameter of whatever DTO you want to use for your TVP so-to-speak. If it's `protected`, then EF Core won't try to generate an entire table for it in the database, but you'll still be able to incorporate instances of it into queries.
> 
> By default, they have a [`QueryModelClass` type](https://github.com/neisbut/EntityFramework.MemoryJoin/blob/master/src/EntityFrameworkCore.MemoryJoin/QueryModelClass.cs) with 3 properties each of types `string`, `bool`, `long`, `double`, `Guid`, and `DateTime`. Should accommodate most use cases of joining on a single table's columns. However, if you need, say, 4 strings, you can create and provide your own DTO class to use instead.
> 
> I haven't successfully run a query that supplies multiple lists in a single request so not sure if that's supported or if I'm just doing things incorrectly. At least gives a general idea of how something like this could be implemented though.

sadly it does not seems to make it easy to add new type mapping like Nodatime or Postgres Enums. 
Additionally it make all variables use a different name even when the value is unique which result in the query plan being different each times.

Would also love to see a robust solution for this problem

**Comment by roji** [comment]
@erwan-joly how do you see this as relevant for NodaTime or PG enum support? Both these are already natively supported by the PostgreSQL provider etc.

**Comment by erwan-joly** [comment]
> @erwan-joly how do you see this as relevant for NodaTime or PG enum support? Both these are already natively supported by the PostgreSQL provider etc.

I think I was unclear, what I meant was the other way around: it would be nice if the proposed solution was supporting those (and any type supported by the provider) not that the support of those types would change in anyway with such a solution.

The suggested solution EntityFramework.MemoryJoin does not work with those types and also create a new set of parameters at every run so it will always get a new query plan.

It only support a small subset of types: https://github.com/neisbut/EntityFramework.MemoryJoin/blob/master/src/EntityFramework.MemoryJoin/Internal/MappingHelper.cs#L321

it would be nice to be able to join with an in memory list for any supported type in the provider. And I believe having this in EF would result in each provider being able to add the support on their side with things like

‘select * from table t
join values(generatedFromMemoryList) as list(id, name,…)
On t.id = list.id and t.name = list.name’

**Comment by roji** [comment]
Everyone, EF 8.0 is introducing full support for primitive collections, which very much addresses what has been discussed above ([see this blog post](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/)). Rather than using a SQL Server TVP (Table-Valued Parameter), we've gone with JSON arrays as the way to represent arrays.

For example, consider the following simple LINQ query using Contains:

```c#
var names = new[] { "Blog1", "Blog2" };

var blogs = await context.Blogs
    .Where(b => names.Contains(b.Name))
    .ToArrayAsync();
```

EF Core 7.0 translated this as follows:

```sql
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE [b].[Name] IN (N'Blog1', N'Blog2')
```

The new 8.0 translation:

```sql
Executed DbCommand (49ms) [Parameters=[@__names_0='["Blog1","Blog2"]' (Size = 4000)], CommandType='Text', CommandTimeout='30']

SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE EXISTS (
    SELECT 1
    FROM OPENJSON(@__names_0) AS [n]
    WHERE [n].[value] = [b].[Name])
```

This allow the same query plan to be reused regardless of parameters. And in addition, any LINQ operators can now be composed over the array parameter, not just Contains.

* Are widely supported across different databases. TVPs are a SQL Server-only feature.
* Do not require a type to be defined before being used in a query.
* Can also be used as columns and not just as parameters. This allows storing e.g. an array of ints as a column in the database, and then using LINQ Contains() over that exactly as one can use it over a parameter.
* Seem to provide at least better performance compared to TVPs (see https://github.com/dotnet/efcore/issues/13617#issuecomment-1471760575 for the benchmarks).

So unless I'm mistaken, there's no longer a reason for this issue to be open; unless someone can come up with a specific reason why TVPs should be used (as opposed to a JSON array), EF 8.0 seems to already resolve the issues described here.

**Comment by erwan-joly** [comment]
> Everyone, EF 8.0 is introducing full support for primitive collections, which very much addresses what has been discussed above ([see this blog post](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/)). Rather than using a SQL Server TVP (Table-Valued Parameter), we've gone with JSON arrays as the way to represent arrays.
> 
> For example, consider the following simple LINQ query using Contains:
> 
> ```cs
> var names = new[] { "Blog1", "Blog2" };
> 
> var blogs = await context.Blogs
>     .Where(b => names.Contains(b.Name))
>     .ToArrayAsync();
> ```
> 
> EF Core 7.0 translated this as follows:
> 
> ```sql
> SELECT [b].[Id], [b].[Name]
> FROM [Blogs] AS [b]
> WHERE [b].[Name] IN (N'Blog1', N'Blog2')
> ```
> 
> The new 8.0 translation:
> 
> ```sql
> Executed DbCommand (49ms) [Parameters=[@__names_0='["Blog1","Blog2"]' (Size = 4000)], CommandType='Text', CommandTimeout='30']
> 
> SELECT [b].[Id], [b].[Name]
> FROM [Blogs] AS [b]
> WHERE [b].[Name] IN (
>     SELECT [n].[value]
>     FROM OPENJSON(@__names_0) WITH ([value] nvarchar(max) '$') AS [n]
> )
> ```
> 
> This allow the same query plan to be reused regardless of parameters. And in addition, any LINQ operators can now be composed over the array parameter, not just Contains.
> 
> * Are widely supported across different databases. TVPs are a SQL Server-only feature.
> * Do not require a type to be defined before being used in a query.
> * Can also be used as columns and not just as parameters. This allows storing e.g. an array of ints as a column in the database, and then using LINQ Contains() over that exactly as one can use it over a parameter.
> * Seem to provide at least better performance compared to TVPs (see [this comment](https://github.com/dotnet/efcore/issues/13617#issuecomment-1471760575) for the benchmarks).
> 
> So unless I'm mistaken, there's no longer a reason for this issue to be open; unless someone can come up with a specific reason why TVPs should be used (as opposed to a JSON array), EF 8.0 seems to already resolve the issues described here.

Seems perfect 🎉

**Comment by erwan-joly** [comment]
@roji what am I missing ? This fail I was expecting it to join on an OpenJson list 
<img width="656" alt="image" src="https://github.com/dotnet/efcore/assets/35202750/7dd330c1-8697-4a04-913b-f210bc834bd8">

**Comment by roji** [comment]
@erwan-joly can you please open a new issue with a full, runnable repro (not a code screenshot)? This issue isn't the place to discuss that.

**Comment by erwan-joly** [comment]
> @erwan-joly can you please open a new issue with a full, runnable repro (not a code screenshot)? This issue isn't the place to discuss that.

Yeah wasn’t sure if this was a bug or just a misunderstanding on what the issue was about
