### ISSUE TITLE
Have a way to construct a rawsqlstring from a trusted source

### ISSUE THREAD

**Issue by cortex93** [dotnet/efcore#13256]
When executing raw sql script containing curly braces, it is really cumbersome to have to escape those characters in the first place.

We should have a method to be able to bypass the replacement mechanism when we trust the input.

```
string sql = File.ReadAllText("...");
sql = sql.Replace("{", "{{").Replace("}", "}}");
context.Database.ExecuteSqlCommandAsync(sql);
```
With EF1000 compilation warning "The SQL expression passed to 'ExecuteSqlCommandAsync' embeds data that will not be parameterized."

Should be something like
```
string sql = File.ReadAllText("...");
RawSqlString rawSql = RawSqlString.FromTrustedStringWithNoParameter(sql);
context.Database.ExecuteSqlCommandAsync(rawSql);
```
With no warning.

I can't find documentation on it so maybe it already exists or there is a better way to achieve this.

**Comment by smitpatel** [comment]
It is just a warning. Wouldn't disable the warning in the source is same amount of work as calling a method?

**Comment by ajcvickers** [comment]
@cortex93 We discussed this and we're not planning to do anything here, especially since the APIs will be changing slightly in 3.0 and the analyzer will be removed.

**Comment by divega** [comment]
@cortex93 Thanks for the clarification. So, you are talking about a SQL string that happens to include curly braces as part of the SQL (e.g. inside some string literal) and the fact that you now have to escape them to prevent our argument replacement logic from being triggered. This is interesting. As you mentioned, there are probably things we could do about this. Bringing it back to triage.

**Comment by cortex93** [comment]
you rephrase it right; thanks for re-opening it.

**Comment by ajcvickers** [comment]
Triaged with #13270, leaving that issue on the backlog.

**Comment by renemadsen** [comment]
Any change on this issue? Stil facing the same problem in 3.1
