### ISSUE TITLE
EntityQueryModelVisitor does not properly use CreateTransparentIdentifierType

### ISSUE THREAD

**Issue by crhairr** [dotnet/efcore#13265]
As a 3rd-party EF Core provider maintainer, I need to be able to control the transparent identifier type used by EntityQueryModelVisitor. I can override CreatetTransparentIdentifierType, but this has no effect on VisitAdditionalFromClause because it does not properly call that method:

https://github.com/aspnet/EntityFrameworkCore/blob/146863a3bdc25c1ea1cb224ba0611594398c8459/src/EFCore/Query/EntityQueryModelVisitor.cs#L983

Instead, it directly references the internal TransparentIdentifier<,> type.

This causes type mismatches when overriding CreateTransparentIdentifierType and attempting to use that type in other visitor methods. The net effect is having to override more methods that strictly necessary just to ensure that the correct type is used.

### Further technical details
EF Core version: ALL historical versions
Database Provider: Non-specific (problem is in EFCore)

**Comment by ajcvickers** [comment]
Tracking this for 3.0 as part of the the larger query refactoring that is tracked by #12795

**Comment by ajcvickers** [comment]
This should no longer be an issue in 3.0. Innit?

**Comment by smitpatel** [comment]
3.0 query pipeline does not have client evaluation of joins so creation of Transparent identifier would be removed altogether in Core. (Individual providers like InMemory can implement their own client side translation)
