### ISSUE TITLE
The SQL translation of  LINQ's Skip/Take is not compatible with SQL Server 2008.

### ISSUE THREAD

**Issue by RickyLin** [dotnet/efcore#1326]
I have read #299. That's great that EF can take advantage of new feature of new SQL Server. However, **do we have a plan to support SQL Server 2008**? The SQL Server 2008 doesn't support statement like `OFFSET @p3 ROWS FETCH NEXT @p3 ROWS ONLY`. In this case, I'm not able to use Skip/Take when targeting SQL Server 2008, which is a pity since I still have to use SQL Server 2008 in the next few years probably.

**Comment by rowanmiller** [comment]
SQL Server 2008 isn't currently something we are planning to support in our SQL Server provider. It should be fairly easy to override the provider to replace sql generation that is failing for a particular set of scenarios... but it's not something we are planning to explicitly implement/test/support in the official provider.
