### ISSUE TITLE
Async on nested expressions freezes

### ISSUE THREAD

**Issue by genne** [dotnet/efcore#13275]
If you execute `ToArrayAsync` on a nested expression, i.e.

```c#
var data = await context.MyEntities.Select(e => new EntityModel 
{
    Nested = e.NestedObjects.Select(n => new NestedModel{ ... })
}).ToArrayAsync();
```

then `data[0].Nested` will be of type `AsyncLinqOperatorProvider.EnumerableAdapter<NestedModel>`, i.e. it seems like it's evaluated async as well. If you evaluate that in a WebApi (or similar) it will freeze.

### Steps to reproduce

Calling the following WebAPI action will timeout:

```c#
public class EntityController : ApiController
{
        [HttpGet]
        public Task<EntityModel[]> GetAll()
        {
            return new MyContext().Entities.Select(s => new EntityModel
            {
                Nested = e.NestedObjects.Select(n => new NestedModel())
            }).ToArrayAsync();
        }
}
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by ajcvickers** [comment]
@smitpatel to suggest a workaround, and find dupe.

**Comment by smitpatel** [comment]
It is a deadlock issue. Same as #12842 

As a work-around,
1. Use ToList on inner collections like this
```C#
            return new MyContext().Entities.Select(s => new EntityModel
            {
                Nested = e.NestedObjects.Select(n => new NestedModel()).ToList()
            }).ToArrayAsync();
```

2. Disable MARS, which would make sure proper internal buffering happens.
3. Use Sync query.

**Comment by genne** [comment]
Thanks 👍
