### ISSUE TITLE
Spatial Query: Normalize method calls

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#13282]
There are several ways to write the same thing using NTS. It would ease the burden on provider writers if we normalized these to a single member. For example, `ToString` and `ToText` would be rewritten as `AsText`.

**Comment by smitpatel** [comment]
If we do this then #13281 may automagically work.

**Comment by bricelam** [comment]
It's a little different. The sugar methods are usually there because they're more efficient in NTS. We wouldn't want to use the normalized version during client eval.
