### ISSUE TITLE
Build Error: EntityFramework.Relational.FunctionalTests

### ISSUE THREAD

**Issue by tonysneed** [dotnet/efcore#1328]
FTY, I'm receiving the following compilation error when building EntityFramework-2014.sln:

Error CS0433: The type 'AsyncLocal<T>' exists in both 'System.Threading.ExecutionContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' EntityFramework.Relational.FunctionalTests.ASP.NET Core 5.0 TestSqlLoggerFactory.cs 19

However, after running 'build initialize', I was able to build the EntityFramework.sln just fine. :)

**Comment by rowanmiller** [comment]
Closing, feel free to reopen if you have further questions
