### ISSUE TITLE
Can't reference Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by ZapRiver** [dotnet/efcore#13299]
I'm trying to install the package Microsoft.EntityFrameworkCore.SqlServer to my Shared project (.NET Standard 2.0) of a Blazor ASP.NET Core Hosted Application using the command 'Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 2.1.0' but I'm getting an error, regardless of whether I try to install version 2.1.0, 2.1.1 or 2.1.2. This used to work perfectly well until a month ago when I updated Visual Studio.

This is the error I'm getting:

MSB3073	The command "dotnet "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/illink/illink.dll" -l none -c link -u link -b true -t --verbose  -d "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/mono/bcl/" -d "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/mono/bcl/Facades/" -o "C:\Users\Andy\source\repos\WebApplication1\WebApplication1.Client\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\Andy\source\repos\WebApplication1\WebApplication1.Client\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor\0.5.1\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.5.1\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore\2.1.0\lib\netstandard2.0\Microsoft.EntityFrameworkCore.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore.abstractions\2.1.0\lib\netstandard2.0\Microsoft.EntityFrameworkCore.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore.relational\2.1.0\lib\netstandard2.0\Microsoft.EntityFrameworkCore.Relational.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore.sqlserver\2.1.0\lib\netstandard2.0\Microsoft.EntityFrameworkCore.SqlServer.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.caching.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Caching.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.caching.memory\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Caching.Memory.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.configuration\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.configuration.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.configuration.binder\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.dependencyinjection\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.logging\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Logging.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.logging.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.options\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Options.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.primitives\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.jsinterop\0.5.1\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.win32.registry\4.5.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" -a "C:\Users\Andy\.nuget\packages\mono.webassembly.interop\0.5.1\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\remotion.linq\2.2.0\lib\netstandard1.0\Remotion.Linq.dll" -a "C:\Users\Andy\.nuget\packages\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Users\Andy\.nuget\packages\system.collections.immutable\1.5.0\lib\netstandard2.0\System.Collections.Immutable.dll" -a "C:\Users\Andy\.nuget\packages\system.componentmodel.annotations\4.5.0\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\Andy\.nuget\packages\system.data.sqlclient\4.5.0\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\Andy\.nuget\packages\system.diagnostics.diagnosticsource\4.5.0\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.interactive.async\3.1.1\lib\netstandard1.3\System.Interactive.Async.dll" -a "C:\Users\Andy\.nuget\packages\system.linq\4.1.0\lib\netstandard1.6\System.Linq.dll" -a "C:\Users\Andy\.nuget\packages\system.linq.expressions\4.1.0\lib\netstandard1.6\System.Linq.Expressions.dll" -a "C:\Users\Andy\.nuget\packages\system.linq.queryable\4.0.1\lib\netstandard1.3\System.Linq.Queryable.dll" -a "C:\Users\Andy\.nuget\packages\system.memory\4.5.0\lib\netstandard2.0\System.Memory.dll" -a "C:\Users\Andy\.nuget\packages\system.numerics.vectors\4.4.0\lib\netstandard2.0\System.Numerics.Vectors.dll" -a "C:\Users\Andy\.nuget\packages\system.objectmodel\4.0.12\lib\netstandard1.3\System.ObjectModel.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.emit\4.0.1\lib\netstandard1.3\System.Reflection.Emit.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.emit.ilgeneration\4.0.1\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.emit.lightweight\4.0.1\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.typeextensions\4.1.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" -a "C:\Users\Andy\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.0\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll" -a "C:\Users\Andy\.nuget\packages\system.security.accesscontrol\4.5.0\lib\netstandard2.0\System.Security.AccessControl.dll" -a "C:\Users\Andy\.nuget\packages\system.security.principal.windows\4.5.0\lib\netstandard2.0\System.Security.Principal.Windows.dll" -a "C:\Users\Andy\.nuget\packages\system.text.encoding.codepages\4.5.0\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "C:\Users\Andy\.nuget\packages\system.threading\4.0.11\lib\netstandard1.3\System.Threading.dll" -a "C:\Users\Andy\source\repos\WebApplication1\WebApplication1.Shared\bin\Debug\netstandard2.0\WebApplication1.Shared.dll" -a "C:\Users\Andy\source\repos\WebApplication1\WebApplication1.Client\obj\Debug\netstandard2.0\WebApplication1.Client.dll"" exited with code 1.	WebApplication1.Client	C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\Blazor.MonoRuntime.targets	441	

I'm using Visual Studio 2017 15.8.4.

**Comment by ajcvickers** [comment]
@ZapRiver Can you provide some more details on exactly when you hit this? Is it on package install or some other time? Does building the solution work? (Also note that generally using the IL linker is likely to have issues based on similar scenarios for Xamarin and Unity--see #10963 and #13099)

**Comment by ZapRiver** [comment]
Here's how to reproduce the error.
  
  1. Open Visual Studio 2017 15.8.4.
2. Create a new ASP.NET Core Web Application -> Blazor (ASP.NET Core hosted).
3. Go to Nuget Package Manager Console.
4. Select the Shared project and type Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 2.1.0.
5. Type Install-Package Microsoft.EntityFrameworkCore.Tools -Version 2.1.0.
6. Recompile. Error:
Error MSB3073 The command "dotnet "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/illink/illink.dll" -l none -c link -u link -b true -t --verbose  -d "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/mono/bcl/" -d "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/mono/bcl/Facades/" -o "C:\Users\Andy\source\repos\WebApplication2\WebApplication2.Client\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\Andy\source\repos\WebApplication2\WebApplication2.Client\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor\0.5.1\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.5.1\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore\2.1.3\lib\netstandard2.0\Microsoft.EntityFrameworkCore.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore.abstractions\2.1.3\lib\netstandard2.0\Microsoft.EntityFrameworkCore.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore.relational\2.1.3\lib\netstandard2.0\Microsoft.EntityFrameworkCore.Relational.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.entityframeworkcore.sqlserver\2.1.3\lib\netstandard2.0\Microsoft.EntityFrameworkCore.SqlServer.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.caching.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Caching.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.caching.memory\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Caching.Memory.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.configuration\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.configuration.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.configuration.binder\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.dependencyinjection\2.1.1\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.logging\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Logging.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.logging.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.options\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Options.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.extensions.primitives\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.jsinterop\0.5.1\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\Andy\.nuget\packages\microsoft.win32.registry\4.5.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" -a "C:\Users\Andy\.nuget\packages\mono.webassembly.interop\0.5.1\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\remotion.linq\2.2.0\lib\netstandard1.0\Remotion.Linq.dll" -a "C:\Users\Andy\.nuget\packages\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Users\Andy\.nuget\packages\system.collections.immutable\1.5.0\lib\netstandard2.0\System.Collections.Immutable.dll" -a "C:\Users\Andy\.nuget\packages\system.componentmodel.annotations\4.5.0\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\Andy\.nuget\packages\system.data.sqlclient\4.5.1\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\Andy\.nuget\packages\system.diagnostics.diagnosticsource\4.5.0\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.interactive.async\3.1.1\lib\netstandard1.3\System.Interactive.Async.dll" -a "C:\Users\Andy\.nuget\packages\system.linq\4.1.0\lib\netstandard1.6\System.Linq.dll" -a "C:\Users\Andy\.nuget\packages\system.linq.expressions\4.1.0\lib\netstandard1.6\System.Linq.Expressions.dll" -a "C:\Users\Andy\.nuget\packages\system.linq.queryable\4.0.1\lib\netstandard1.3\System.Linq.Queryable.dll" -a "C:\Users\Andy\.nuget\packages\system.memory\4.5.1\lib\netstandard2.0\System.Memory.dll" -a "C:\Users\Andy\.nuget\packages\system.numerics.vectors\4.4.0\lib\netstandard2.0\System.Numerics.Vectors.dll" -a "C:\Users\Andy\.nuget\packages\system.objectmodel\4.0.12\lib\netstandard1.3\System.ObjectModel.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.emit\4.0.1\lib\netstandard1.3\System.Reflection.Emit.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.emit.ilgeneration\4.0.1\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.emit.lightweight\4.0.1\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Users\Andy\.nuget\packages\system.reflection.typeextensions\4.1.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" -a "C:\Users\Andy\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.1\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll" -a "C:\Users\Andy\.nuget\packages\system.security.accesscontrol\4.5.0\lib\netstandard2.0\System.Security.AccessControl.dll" -a "C:\Users\Andy\.nuget\packages\system.security.principal.windows\4.5.0\lib\netstandard2.0\System.Security.Principal.Windows.dll" -a "C:\Users\Andy\.nuget\packages\system.text.encoding.codepages\4.5.0\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "C:\Users\Andy\.nuget\packages\system.threading\4.0.11\lib\netstandard1.3\System.Threading.dll" -a "C:\Users\Andy\source\repos\WebApplication2\WebApplication2.Shared\bin\Debug\netstandard2.0\WebApplication2.Shared.dll" -a "C:\Users\Andy\source\repos\WebApplication2\WebApplication2.Client\obj\Debug\netstandard2.0\WebApplication2.Client.dll"" exited with code 1. WebApplication2.Client C:\Users\Andy\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\Blazor.MonoRuntime.targets 441 
  

  
  
 Andy Richard
  
  

----------------------------------------

**Comment by ajcvickers** [comment]
@ZapRiver Which version of the ,NET Core SDK do you have installed?

**Comment by ZapRiver** [comment]
The latest I installed is 2.1.402 (x64). I have also tried 2.1.400 and 401 with no luck. I have a number of older versions I didn't realize are also installed. Does it matter if they're still installed?
  
  

----------------------------------------

**Comment by Kishorree** [comment]
I having the same issue with 2.1.402. Kindly let me know if there is any work around for this issue

**Comment by ZapRiver** [comment]
There is a workaround.
  
 1. Create a temporary Blazor application solution (the template named 'Blazor', not the ones named 'Hosted' or 'Server-side').
  
 2. Use the Package Manager Console to add EntityFrameworkCore to that project:
     Install-Package Microsoft.EntityFrameworkCore.SqlServer
    Install-Package Microsoft.EntityFrameworkCore.Tools
  
 3. Use the Package Manager Console to generate the scaffolding for your database:
     Scaffold-DbContext "Server=YourServerName;Database=YourDatabaseName;user id=UserID;password=Password;Trusted_Connection=True;MultipleActiveResultSets=true" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
  
 4. Copy the DbContext file generated in step 3 into the Server project of your Blazor hosted solution and replace the namespaces in that file to reflect the namespaces of your Blazor hosted solution.
  
 5. Copy the content of the Models folder from your temporary Blazor application solution (except for the DbContext file) into the Models folder of the Shared project of your Blazor hosted solution and replace the namespaces in those files to reflect the namespaces of your Blazor hosted solution.
  
  
 6. Recompile your Blazor hosted solution and delete the temporary Blazor solution.
  
 Voila.
  
  
  

----------------------------------------

**Comment by coeur85** [comment]
up
