### ISSUE TITLE
is it possible for add `FromSql` support for memoryDatabase

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#13302]
Is it possible for add `FromSql` support for memoryDatabase?

I'm using inMemoryDatabase provider for ef core, but it seems it does not support `FromSql`.
So is it possible to add support?

**Comment by ajcvickers** [comment]
@WeihanLi The in-memory database is not a relational database and does not have any support for running a query language like SQL.

**Comment by WeihanLi** [comment]
Thanks @ajcvickers
