### ISSUE TITLE
Visual Studio 2017 version 15.8.4 update error

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#13307]
From VS Feedback:

After Visual Studio 2017 version 15.8.4 update

Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Because not working web project

before version Microsoft.EntityFrameworkCore, Version=2.1.1

nuget package 2.1.3 update after working

hey! I'm afraid I can not update it.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by Nurgunkalol** [comment]
same error, up

**Comment by davidsonsousa** [comment]
I had the same issue and here is how I fixed:

1. Update Microsoft.EntityFrameworkCore.Proxies to version 2.1.3 and also  Microsoft.VisualStudio.Web.CodeGeneration.Design to version 2.1.4
2. Delete both /bin and /obj folders from the project
3. Rebuild

Perhaps using "Clean Solution" in the step 2 could also work.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
