### ISSUE TITLE
Published to Centos7, memory has been growing until the process is killed

### ISSUE THREAD

**Issue by netnr** [dotnet/efcore#13311]
Asp.net core 2.1 EF

Centos7 1Core 1G

Previously, Windows was running on IIS, using the sqlserver database. In the first two weeks, it was replaced by Centos, using nginx as a proxy, and the database was replaced by sqlite3.

At the beginning, the Centos system swap space is about 200MB, the site runs for one day, the memory accounts for 90%, the swap runs out, the dotnet process is killed; the swap set 2GB later, persists for about a week, the swap runs out, and the dotnet process is killed.

As long as you visit the site, the memory footprint will gradually increase and will not be released; IIS runs completely without these problems on Windows.

The difference between them is that the database is different, one is sqlserver and the other is sqlite3;

![d752317616](https://netnr.gitee.io/gs/2018/09/13/d752317616.png)

![e5e70dc91b](https://netnr.gitee.io/gs/2018/09/13/e5e70dc91b.png)

**Comment by ajcvickers** [comment]
@netnr It's unlikely we will be able to figure out what is happening without a solution/project or code listing that reproduces what you are seeing. Are you able to distill the scenario down into something that we can use to investigate?

**Comment by netnr** [comment]
After testing, using SQL to query memory without EF will not always increase

**Comment by netnr** [comment]
https://github.com/netnr/netnrf/tree/master/src/v2/Netnr.ResponseFramework/Netnr.Data

**Comment by linkinshi** [comment]
@netnr 
optionsBuilder.UseLoggerFactory(new LoggerFactory(new[]
            {
                new ConsoleLoggerProvider((category, level)
                    => category == DbLoggerCategory.Database.Command.Name
                    && level == LogLevel.Error, true)
            }));
don't create new LoggerFactory each time.
you can see this https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging

**Comment by netnr** [comment]
@linkinshi Resolved issue, thanks
