### ISSUE TITLE
EF Logging and Tests

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#13329]
I write tests for my EF data provider and want to check a generated SQL text.

Decision from #6482 does not work correctly, so I began use a log.

```c#
sealed class TestLogger:ILogger
{
 //....
 public void RegIn(DbContext db)
 {
  db.GetService<ILoggerFactory>().AddProvider(new TestLoggerProvider(this));
 }//RegIn
 //....
};//class TestLogger

//......
 [Test]
 public static void Test_01()
 {
  var log=new TestLogger();

  using(var cn=new xdb.OleDbConnection(TestServices.Conf__GetCnStr()))
  {
   cn.Open();

   using(var tr=cn.BeginTransaction())
   {
    using(var db=new MyContext(tr))
    {
     log.RegIn(db);
```
TestLogger works as expected - I receive notifications from EF and can save a SQL of executed command.

One problem - each test creates and registed in own (local) DbContext an own (local) log object.

But seems AddProvider append the log object into global list. As result each test sends notifications to own log and to logs of previous tests.

test1 sends notifications to log1
test2 sends notifications to log2 and log1
test3 sends notifications to log3, log2 and log1
...

It is problem.

I want registry local log object in local dbcontext object only.

Is this possible?

-----
One global log object - I think, is very bad idea. Because I can get the problems with parallel execution of tests.

**Comment by smitpatel** [comment]
You don't need to add logging infra. Just use `Fixture.TestSqlLoggerFactory` it should be available for all test fixtures in functional tests in EF Core Specs tests. If you are writing tests which are not derived from EF Specs tests then you can follow how TestSqlLoggerFactory is wired up in DI to use in own tests.

**Comment by dmitry-lipetsk** [comment]
Hi @smitpatel,

Thanks, I understood.

```c#
class TestBaseDbContext:DbContext
{
 public TestBaseDbContext(xdb.OleDbTransaction tr)
 {
  m_cn=tr.Connection;

  m_log=new TestLogger();

  //---------------------------------------
  this.Database.UseTransaction(tr);
 }//TestBaseDbContext

 //----------------------------------------------------------------------
 public TestLogger log
 {
  get
  {
   Debug.Assert(!Object.ReferenceEquals(m_log,null));

   return m_log;
  }//get
 }//log

 //DbContext interface ---------------------------------------------------
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
 {
  optionsBuilder.UseLcpiOleDb(m_cn);

  optionsBuilder.UseLoggerFactory(new TestLoggerFactory(m_log)); // <--------
 }//OnConfiguring

 //----------------------------------------------------------------------
 private readonly xdb.OleDbConnection m_cn;

 private readonly TestLogger m_log;
};//class TestBaseDbContext
```
Now tests work as expected.
