### ISSUE TITLE
Regular Azure Table Storage

### ISSUE THREAD

**Issue by JoshTango** [dotnet/efcore#13323]
You now offer a Cosmos DB Provider.  Cosmos DB API supports talking to the regular table storage outside of Cosmos so does this mean I can use the Cosmos DB Provider and configure it to talk to regular table storage?  The reason why I ask this is because it is 3 to 4 times cheaper than Cosmos Table Storage.

**Comment by divega** [comment]
@JoshTango Thanks for bringing this up. As explained [in the announcement](https://blogs.msdn.microsoft.com/dotnet/2018/09/12/announcing-entity-framework-core-2-2-preview-2/#new-ef-core-provider-for-cosmos-db) our Cosmos DB provider targets the [SQL API](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-introduction). 

We currently don't have plans to build a provider for the Table API, but it is something we can consider in the future, especially if enough customers want it.

**Comment by JoshTango** [comment]
Oh right it only targets sql api.  I see.  Well it would be easy for you to also provider table storage support since your using a discriminator to map all entities to only one collection.

**Comment by divega** [comment]
@JoshTango writing a provider for a database API that has a completely different paradigm is not that easy :blush:, but as I said it is still something we can consider doing in there is enough demand.

**Comment by JoshTango** [comment]
I'm sorry I was thinking to simply.  When I realized you have pushed all your entities into one collection using a discriminator I thought then that it could simply be used with a table in azure table storage also.  While it would be easy for you offer that part I forgot their is a whole bunch of code associated with the LINQ side of things which can not be reused and would be a lot of work.

**Comment by jcmontx** [comment]
Following on this. Still not on the roadmap? At least partial support?

**Comment by AndriySvyryd** [comment]
@jcmontx We still don't have plans to support this. But it's a great opportunity for a community project,

**Comment by ericsampson** [comment]
@AndriySvyryd @ajcvickers it's a bummer that there is not a provider for Azure Tables. Cosmos is so much more expensive. Have you had any more requests for this? I can't find any community options.

**Comment by ajcvickers** [comment]
@ericsampson Honestly, we really aren't seeing significant demand for this provider. This issue has a few comments and #1142 has a few, but neither issue has any votes (thumbs-up) and we aren't hearing any demand from other channels.

**Comment by ericsampson** [comment]
@ajcvickers thanks I understand. Table Storage kind of seems like it's fading away via slow attrition in favor of cosmos, but that's too bad IMO because the cost model makes Table Storage useful for things that would cost waaay more in cosmos. Cheers.

**Comment by danim-hub** [comment]
I'd also like to be able to use Table Storage.
Cosmos is overkill for simple projects and Table Storage is more cost-effective
