### ISSUE TITLE
Logging elapsed as string

### ISSUE THREAD

**Issue by danjohnso** [dotnet/efcore#13324]
https://github.com/aspnet/EntityFrameworkCore/blob/d59be61006d78d507dea07a9779c3c4103821ca3/src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs#L120

In the RelationalLoggerExtensions, you convert the elapsed time to a string which was frustrating to find when utilizing structured logging.  I was trying to run aggregations over values from our logs but kept getting null errors until I found the value wasn't actually a number.  I can't think of a reason that would make that property useful as a string when neighboring properties which are also numbers are logged as numbers (CommandTimeout). 

There are several other lines in the logger extension which would need updates as well, but before I started a PR, I though I would see if there was reasoning behind storing the value as a string.   Would you take a pull request which drops the string conversion and just logs the property as a number?

**Comment by ajcvickers** [comment]
@danjohnso There at least used to be issues passing non-strings to ASP.NET Core logging, but even without that we want to format the values appropriately for the message. We will discuss this in triage, but I expect the answer is to use DiagnosticSource/DiagnosticLister to get events with structured data. This API is designed to give you full access to the raw data for the event. EF Core generates both types of event.

**Comment by ajcvickers** [comment]
Triage: discussed and there was general agreement that DiagnosticSource is better for this. If we were to do anything for ASP.NET Core logging, then it would require enhancements to the message formatting capabilities there first, which would be something to follow up on at https://github.com/aspnet/Logging/issues

**Comment by danjohnso** [comment]
@ajcvickers sounds good, I was unaware EF Core fully implemented DiagnosticSource.  I know I have seen other parts of the core framework that don't put information in both places so I didn't think to look there for the information, but glad I can use that for ef data
