### ISSUE TITLE
Snapshot location uisng Add-Migration -OutputDir with Release fodler

### ISSUE THREAD

**Issue by generik0** [dotnet/efcore#13342]
HI

Thanks for a cool package.
When i for a migration i like to use:

Add-Migration -OutputDir Migrations\Release2018_x -Context XzyMigrationDbContext -Project Xzy.Migrations -StartupProject Xzy.App -Name Add_Xxy

But this also means that the snapshot is in the Migrations\Release2018_x folder.
What do i do when i make the next release and the migrations shoud be in Migrations\Release2019_y release.
Will there be issues with the multiple shnapshots=?

Thanks again, Br Rik

**Comment by bricelam** [comment]
Feel free to move the file and change the namespace. The tool can usually find it and update it.

Don't add two snapshots. That will cause problems.

**Comment by generik0** [comment]
@bricelam 
Thanks for your answer, i find that if i move, it creates a new one each time under the Migrations\Release2018x.

I have tried to move to root, i.e "Migrations" and then an add-migration just creates a new snapshot.

**Comment by ajcvickers** [comment]
@generik0 Can you please post a runnable project/solution that demonstrates the behavior you are seeing?

**Comment by generik0** [comment]
@ajcvickers 

I think you guys can make this test yourselves. It shold be a part of you CI integration tests
Snaposhot under release folder:
![image](https://user-images.githubusercontent.com/2411563/45813191-38fc1a00-bcd2-11e8-91c4-c0a702f47a71.png)

Snampshot moved and namespace changed:
![image](https://user-images.githubusercontent.com/2411563/45813215-46190900-bcd2-11e8-9b40-d2e454c55a4a.png)

Migrations run, and EF makes 2 snapshots
![image](https://user-images.githubusercontent.com/2411563/45813219-4addbd00-bcd2-11e8-8c62-a881b7599793.png)

**Comment by generik0** [comment]
@ajcvickers I have made an example. You just need to run:
Add-Migration -outputdir Migrations/Release42 -Context TestDbContext -project EfCoreMultipleTransactionsSameDbContext -startupproject EfCoreMultipleTransactionsSameDbContext -Name Add_Test
And you will see there is an extra snapshot created.
[EfCoreNewSnapshotCreated.zip](https://github.com/aspnet/EntityFrameworkCore/files/2449324/EfCoreNewSnapshotCreated.zip)

**Comment by ajcvickers** [comment]
@generik0 Yes, thank you. I was able to reproduce this previously, hence it is assigned as a bug and in a milestone.

**Comment by jasonliaocn** [comment]
Hi, is it possible to create multiple target? previously my database is SQL server and I already have some migration histories, now I may want to deploy it to MySQL but all I can do is to delete the SQL Server migrations folder and start from the beginning again.

if I can specify the output folder for example Migrations-MySQL and there will be a new ModelSnapShot for MySQL generated would be better.

so the structure could be:
Migrations
    MySQL
         20181101042215_Add_Test.cs
         20181101042215_Add_Test.Designer.cs
         TestDbContextModelSnapshot.cs
   SQLServer
         20181101042215_Add_Test.cs
         20181101042215_Add_Test.Designer.cs
         TestDbContextModelSnapshot.cs

then I can specify to UseSqlServer or UseMySql with the target Migrations.
