### ISSUE TITLE
DBContextPool usage: manual creation

### ISSUE THREAD

**Issue by ircheg** [dotnet/efcore#13350]
Hi!

I have a question concerning DbContext Pooling usage. 
I have stateless service and don't want to add dozens of asp net core packages in order to call AddDbContextPool. 
Do I understand it correct that it's not recommended to create DbContextPool manually as in future releases of EF Core the APIs can be changed or even deleted?

`Container container = new Container(); // simple injector container
container.RegisterSingleton<DbContextPool<PlanDbContext>>();`

P.s. sorry if the question is placed in incorrect place. I would be grateful if someone point out where it should be asked

**Comment by ajcvickers** [comment]
@ircheg `AddDbContextPool` does not require any ASP.NET Core packages. EF Core is often used with ASP.NET Core, but there are no dependencies on ASP.NET Core.
