### ISSUE TITLE
After a property is modified, when setting its value back to its original value, isModified remains true (even though CurrentValue is equal to OriginalValue).

### ISSUE THREAD

**Issue by mschnack** [dotnet/efcore#13367]
When tracking the state of an entity, EF Core is correctly changing it to _Modified_ when a property is changed. But if the property value is set back to its original value, the entity is still being marked as _Modified_ and the property is still marked as _IsModified = true_.

Please ignore if this is intended by design, but my expectation is that the state of the property to be computed based on the values of _CurrentValue_ and _OriginalValue_. Something like
`bool IsModified => this.CurrentValue != this.Original;` and the state of the entity to be computed based on the state of its properties.

Currently this happens only when setting a property to its current value. For example:

```c#
var originalName = user.Name;
user.Name = originalValue;
```

In this case, both the entity and the property are not considered as modified. 

But when setting to anything else and then back, both are marked as modified:

```c#
var originalName = user.Name;
user.Name = "Bob";
user.Name = originalValue;
```

In the case above, both the entity and the property are considered as modified. 

### Further technical details
EF Core version: 2.1.2

**Comment by ajcvickers** [comment]
@mschnack This is currently by-design, mostly because we don't always have reliably information about original values and several important scenarios require that a property remain marked as modified even if the original value we have is the same as the current value.

**Comment by mschnack** [comment]
@ajcvickers Thank you for the explanation. That's what I imagined.

Just in case anyone has a similar need, here is the code I've written to verify if the entities (and their properties) are "truly" modified:

```c#
var modifiedEntries = ((DbContext)this.context).ChangeTracker.Entries<T>()
                                                .Where(entry => entry.State == EntityState.Modified)
                                                .ToList();

foreach (var entry in modifiedEntries)
{
    var modifiedProperties = entry.Properties.Where(p => p.IsModified)
                                  .ToList();

    foreach (var property in modifiedProperties)
    {
        property.IsModified = property.OriginalValue != property.CurrentValue;
    }

    if (modifiedProperties.All(p => !p.IsModified))
    {
        entry.State = EntityState.Unchanged;
    }
}
```

**Comment by ajcvickers** [comment]
@mschnack The last check for all properties not modified should not be needed since EF should make this state change automatically once there are no remaining modified properties.
