### ISSUE TITLE
EF 6.2.0 TypeUsage MaxLength, possible? OR EF6 should support String length > Int32

### ISSUE THREAD

**Issue by ZooDoo4U** [dotnet/efcore#13362]
Nothing is broken for me right now, but i'm more concerned that looking at the length restriction for a string is still only an Int32?  However if i might user SQL I could get strings with a max length as Int64.  Working on some code for validating string values for my DB i was doing this to outside of EF via straight SqlCommand calls with a SqlDataReader.  I found i would get back at either an Int32 or Int64 datavalue for some column length using this:

$@"SELECT min(DATALENGTH([{colName}])), max(DATALENGTH([{colName}])) FROM [{tblName}]"

Wanting to override  my DbContext.SaveChanges() and forcibly trim long strings to get around validation errors, was curious what the MaxLength EF recognized as a max column length, this is where the TypeUsage.cs comes in. 

Snooping into the source for the TypeUsage.cs seems MaxLength will always be Int32 max.   

Your convenience a link the file is here, .
https://referencesource.microsoft.com/#System.Data.Entity/System/Data/Metadata/Edm/TypeUsage.cs

Where my concern is coming from if we now get back to the code posted at first,  to get the max column lengths from SQL some columns lengths are reported as Int64.  So it begs the question if EF6 will or wont allow strings > Int32? Given if i run this int will be 4 bytes regardless of the host application being x86 or x64

private static void MyTest()
{
    Console.WriteLine($"Is64BitProcess == {Environment.Is64BitProcess}");
    Console.WriteLine($"sizoef(int) {sizeof(int)}");
    Console.WriteLine($"sizof(int32) {sizeof(Int32)}");
    Console.WriteLine($"sizeof(int64) {sizeof(Int64)}");
    Console.WriteLine($"sizeof(long) {sizeof(long)}");
}

Is64BitProcess == False
sizoef(int) 4
sizof(int32) 4
sizeof(int64) 8
sizeof(long) 8

Is64BitProcess == True
sizoef(int) 4
sizof(int32) 4
sizeof(int64) 8
sizeof(long) 8

So my real concern boils down to Sql.  Can it possibly a string with a length > Int32? Or is the code for the column length returned from SQL as an Int32?  

Vitals:
Version 1803 (OS Build 17134.285)
EF 6.2.0
VS 2017 15.8.1
"Victor"-dadori  direct...

**Comment by ajcvickers** [comment]
EF6 only supports 32-bit max length values. While it is true that theoretically SQL Server (or other databases) could support longer, this is something we had decided not to fix, even while EF6 was in active development on CodePlex.
