### ISSUE TITLE
Is this code safe?

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#13369]
https://softwareengineering.stackexchange.com/questions/378670/should-i-check-if-something-exists-in-the-db-and-fail-fast-or-wait-for-db-except

```csharp
public async Task<ActionResult<Parent>> CreateParent(Parent parent)
{
    if (!await _db.Children.AnyAsync(c => c.Id == parent.ChildId))
       return NotFound($"Child with id {parent.ChildId} could not be found.");

    _db.Parents.Add(parent);
    await _db.SaveChangesAsync();        

    return parent;
}
```

People are saying that there will be a concurrency problem with this code. 
>  it can always happen that the ID is inserted concurrently between checking time and writing time.

What's the general practice to deal with problem like this?

**Comment by leppie** [comment]
Not sure if you trying to troll the classic `File.Delete` issue or misunderstanding the difference between concurrency and transactions. 😕

**Comment by Necronux** [comment]
@leppie fuck you asshole

**Comment by leppie** [comment]
Wow, that escalated fast!

**Comment by ajcvickers** [comment]
@Necronux Yes, that code can have concurrency issues. See https://docs.microsoft.com/en-us/ef/core/saving/concurrency

**Comment by Necronux** [comment]
> Not sure if you trying to troll the classic File.Delete issue or misunderstanding the difference between concurrency and transactions. 

Neither, and your comment is arrogant and pointless
