### ISSUE TITLE
Allow removal of Cascade on Delete Convention

### ISSUE THREAD

**Issue by ac10n** [dotnet/efcore#13366]
In EF, there was a way to configure CascadeOnDelete to None, like:

    builder.Conventions.Remove<OneToManyCascadeDeleteConvention>();

In ef core, the only options is to configure it on each relationship via Fluent api.

I want to argue that:

1. There should be an option to remove this convention, DbContex-wide, not on each relationship
2. The default behavior should be not to cascade on deletes, should be: none, which prevents deletion of an entity if it has dependents. This consistency check in a database relationships prevents users from deleting unwanted data and is the default in many management UIs including SSMS.

I do understand that changing the default behavior (number 2) is a breaking changed and my argument is not sufficient for such a breaking change.

However, I think that number 1 is a truly missing feature.

**Comment by milosloub** [comment]
You can set it globally in OnModelCreating method of your DbContext class:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
            base.OnModelCreating(modelBuilder);

            // Global turn off delete behaviour on foreign keys
            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
}
```

**Comment by ajcvickers** [comment]
The code @milosloub posted is the way to do this now, but removing the convention should be covered by #214
