### ISSUE TITLE
How do I precompile the EntityFrameworkCore Libraries?

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/efcore#13378]
I am trying to precompile the EntityFrameworkCore libraries on my development machine.  Starting up the debugging takes forever.  The DotNetCore library has a bewildering number of locations where it's DLLs could be  saved.  There's \dotnet\sdk\,  \dotnet\shared\, \dotnet\store\ and even more and that's just in the program files\dotnet folder!  If that's not enough confusion and frustration, some of these libraries also exist in nuget packages under "fallback folders" and other cryptic names.   

Perhaps, Microsoft enjoys sadistically punishing it's declining developers and customer base by making things as difficult as possible.  This remind me of many years ago when I helped a friend locate years worth of Outlook emails on his computer.  To my surprise and utter disgust, it was buried deep into his user folder into a cryptic directory.  Get your act together Microsoft!

P.S. Don't you dare try passing the ball to another team by claiming it's the core team's responsibility.  It isn't!   When you're DLL takes forever to load and execute, it's your problem.

**Comment by ajcvickers** [comment]
@Joebeazelman What do you mean by "precompile"?

**Comment by Joebeazelman** [comment]
precompile as in prejitting the assemblies.  Right now, EntityFramework keeps jitting.

**Comment by ajcvickers** [comment]
@Joebeazelman There is a "crossgen" tool, which is the .NET Core equivalent to the old "ngen" tool for .NET Framework--documentation is here: https://github.com/dotnet/coreclr/blob/master/Documentation/building/crossgen.md
