### ISSUE TITLE
How to code OnModelCreating in EF core

### ISSUE THREAD

**Issue by sundong1982** [dotnet/efcore#13383]
EF6：
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Configurations.AddFromAssembly(typeof(MySqlDbContext).Assembly);
            modelBuilder.Properties().Where(o => typeof(IEntityRowVersion).IsAssignableFrom(o.DeclaringType) && o.PropertyType == typeof(byte[]) && o.Name == "RowVersion").Configure(o => o.IsConcurrencyToken().HasDatabaseGeneratedOption(DatabaseGeneratedOption.None));
            Database.SetInitializer(new MySqlDbInitializer());
}
```

**Comment by ajcvickers** [comment]
@sundong1982 
* EF Core doesn't pluralize table names. 
* AddFromAssembly is tracked by #13088, with PR here: #13305. 
* Lightweight conventions are best implemented by iterating over the model--see some examples in #214. 
* There are no database initializers.

**Comment by sundong1982** [comment]
thx:)

**Comment by davidrevoledo** [comment]
@sundong1982  in the meantime you can use this. -> https://github.com/davidrevoledo/EntityFrameworkCore.AutoLoad

**Comment by sundong1982** [comment]
> @sundong1982 in the meantime you can use this. -> https://github.com/davidrevoledo/EntityFrameworkCore.AutoLoad

oh,good. thx!!
