### ISSUE TITLE
Question: How to do local calculation of expression through my code?

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#13395]
Local calculation of expressions uses rules, which different from DBMS rules.

First example:
DBMS: NULL+'text' -> NULL
LOCAL: null+"text" -> "text"

Second example:
DBMS: SUBSTRING('12345' FROM 10) returns empty string
LOCAL: "12345".Substring(9) generates exception

This creates problems.

Question:
How I can replace local calculation of expressions to my code (which will use DBMS rules)?

It is possibled in general?

**Comment by Tarig0** [comment]
So you want the local evaluation to be a 1-1 of the server calculation?

Think you'll just have to spin your own functions to simulate the provider.

**Comment by dmitry-lipetsk** [comment]
> So you want the local evaluation to be a 1-1 of the server calculation?
Yes.

> Think you'll just have to spin your own functions to simulate the provider.

Functions and operators (like "string+string").

How I can replace, for example, implementation of System.String.Replace and "String operator + (String, String)" at level of my data provider for EF.Core?

Any examples would be helpful.

---
Additional info.

My data provider may translate call of System.String.Replace to SQL only when arguments is very simple (it is limitations and problems of DBMS). In other cases I want to make local calculation (with DBMS rules).

**Comment by Tarig0** [comment]
Can you give an example of a call chain that you would need to be evaluated client side?

**Comment by dmitry-lipetsk** [comment]
> Can you give an example of a call chain that you would need to be evaluated client side?

```C#
string vv1="Q";
var recs=db.testTable.Where(r => (r.DATA+vv1).Trim()==null && r.TEST_ID==testID);
```

> The LINQ expression 'where (([r].DATA + __vv1_0).Trim() == null)' could not be translated and will be evaluated locally.

My data provider for Linq rejects translate of TRIM to SQL, when it argument contains the parameter. This allow me avoid some limitations of DBMS.

I want to calculate TRIM at client side. Result should be null if r.DATA has null, or vv has null.

**Comment by Tarig0** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Query/ExpressionVisitors/Internal/SqlServerSqlTranslatingExpressionVisitor.cs#L49

This looks like where you would override the behavior

**Comment by dmitry-lipetsk** [comment]
@Tarig0,

In general - yes.

I found where EFCore stored conditions for local calculation after query execution:

https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs#L1029-L1031

But at current time I do not know - what I should do with this :)

**Comment by Tarig0** [comment]
so basically you would pre-process the fragments so the client eval warning wouldn't be added

| |Left NULL|left NOT NULL|
|---|---|---|
|RIGHT NULL|NULL|NULL|
|RIGHT NOT NULL|NULL|Added value|

And then Trim

Null == null
Value == value.trim()

**Comment by smitpatel** [comment]
@dmitry-lipetsk - The way to do it is in writing a proper method for translation at provider level.
https://github.com/aspnet/EntityFrameworkCore/blob/af68d14219bf8da624f1785d434172c732371400/src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs#L986-L1033

Above is the code which translates `Where` clause in Query. Roughly steps involved:
1. Verify if we are not in client eval mode and we can translate the where to SQL by finding appropriate SelectExpression to add the predicate.
2. Use SqlTranslatingExpressionVisitor to translate the clause to server and add it to SQL if it succeeds.
3. Take whatever is not translated and generate client eval warning.
4. Call base method which is basically linq evaluation of the where clause from `Enumerable.Where`

For your particular scenario, what you want it is if the translating to SQL (step 2) fails then you need to rewrite the where clause to be equivalent function of how server would take care of null parameters and then call base. If you do that then you can mimic the server behavior even when evaluating client code when expression is not translated to server.
Same you have to do for every other thing where this is encountered like order by/join etc.

**Comment by dmitry-lipetsk** [comment]
Ok. I should create new class, which inherites the RelationalQueryModelVisitor. I already think in this direction.

In MyQueryModelVisitor, I override VisitWhereClause.

How I can call from MyQueryModelVisitor.VisitWhereClause the EntityQueryModelVisitor.VisitWhereClause?

I understand that it is C# question, but I not know - how do it? :)

```C#
// EntityQueryModelVisitor
class TA 
{
 public virtual void F() { Console.WriteLine("TA.F"); }
}

// RelationalQueryModelVisitor
class TB:TA 
{
 public override void F() { Console.WriteLine("TB.F"); base.F();}
}

// MyQueryModelVisitor
class TC:TB
{
 public override void F() { Console.WriteLine("TC.F"); base.base.F();} // <--- ???
}

```
It seems I should copy the RelationalQueryModelVisitor to my source and modify it. Yes?

**Comment by smitpatel** [comment]
I am not sure if `base.base.F()` works but you should not call it. You should rather call `base.F()`. While it may still try to translate the where clause through SqlTranslator which will fail but it will give the warning mechanism and client eval from core.
Another alternative is to do rewriting in advance so you don't need to modify each individual clause (like any function call can be re-written in c# to match database semantics during `OptimizerQueryModel` method. But inside your provider specific SqlTranslatingExpressionVisitor, you collapse it back and translate to server.

Ultimately, it is upto you how you want to achieve it. On abstraction level of relational, biggest issue we encountered is what would be the behavior when client evaluating given each database provider can have differences. Hence we erred on the side of keeping LINQ semantics, i.e. just execute code on client side. For most databases, it should translate to server and if it ends up on client side because of some user specified client side function then user should write client safe code.

**Comment by dmitry-lipetsk** [comment]
@smitpatel,

Think, I found the better place, where I can transform the expression for local calculation - ReplaceClauseReferences.

```c#
class FB_Common__QueryModelVisitor:RelationalQueryModelVisitor
{
 public FB_Common__QueryModelVisitor
         (EntityQueryModelVisitorDependencies     dependencies,
          RelationalQueryModelVisitorDependencies relationalDependencies,
          RelationalQueryCompilationContext       queryCompilationContext,
          RelationalQueryModelVisitor             parentQueryModelVisitor)
  :base(dependencies,
        relationalDependencies,
        queryCompilationContext,
        parentQueryModelVisitor)
 {
 }

 //RelationalQueryModelVisitor interface ---------------------------------
 public override Expression ReplaceClauseReferences
                  (Expression   expression,
                   IQuerySource querySource,
                   bool         inProjection)
 {
  Debug.Assert(!Object.ReferenceEquals(expression,null));

  expression
   =ExpressionVisitors.FB_Common__ToServerExpressionTransformatorVisitor.Exec
     (expression);

  Debug.Assert(!Object.ReferenceEquals(expression,null));

  return base.ReplaceClauseReferences
         (expression,
          querySource,
          inProjection);
 }//ReplaceClauseReferences
};//class FB_Common__QueryModelVisitor
```

FB_Common__ToServerExpressionTransformatorVisitor walks the tree and replaces nodes. Current result looks fine.
