### ISSUE TITLE
EF7 + VNext + K projets + mysql: "The type or namespace name 'ModelConfiguration' does not exist in the namespace 'System.Data.Entity'"

### ISSUE THREAD

**Issue by roalcantara** [dotnet/efcore#1340]
Hi, 

I'm not quite sure where I should post my question. If it's not here, where?

Well, I'm trying to set-up the environment for EF7 + aspnetvnext + K projets + mysql on my OSX.

I followed this [excellent article](https://www.jeremymorgan.com/tutorials/vnext/how-to-build-c-sharp-on-mac-osx/), and I've created the app using the Yeoman generator and I'm able to run successfully the following commands:
- kvm update
- kpm restore

But when I run

```
$ k ef
```

I got

**Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: /Users/roalcantara/Documents/vnext/DAL/MyDbContext.cs(3,26): error CS0234: The type or namespace name 'ModelConfiguration' does not exist in the namespace 'System.Data.Entity' (are you missing an assembly reference?)**

And if I run

```
k kestrel
```

I got

**Missing method BuildServiceProvider in assembly /Users/roalcantara/.kpm/packages/Microsoft.AspNet.Hosting/1.0.0-beta1/lib/aspnet50/Microsoft.AspNet.Hosting.dll, type Microsoft.Framework.DependencyInjection.Fallback.ServiceCollectionExtensions System.TypeLoadException: Could not load type 'Microsoft.Framework.DependencyInjection.Fallback.ServiceCollectionExtensions' from assembly 'Microsoft.AspNet.Hosting'. at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0**

Am I missing any dependency?

Here is my /vnext/projects.json:

``` json
{
    "webroot" : "wwwroot",
    "exclude": "wwwroot/**/*.*",
    "dependencies": {
        "Microsoft.AspNet.Server.IIS":"1.0.0-beta1",
        "Microsoft.AspNet.Mvc": "6.0.0-beta1",
        "Microsoft.AspNet.Hosting": "1.0.0-beta1",
        "Microsoft.AspNet.Security.Cookies": "1.0.0-beta1",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta1",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta1",
        "Kestrel": "1.0.0-beta1",
        "EntityFramework": "7.0.0-*",
        "EntityFramework.Migrations": "7.0.0-*",
        "EntityFramework.Commands": "7.0.0-*",
        "System.Data.Entity.Repository": "2.0.0.1",
        "MySql.Data.Entity.EF6": "6.8.3"      
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004",
        "ef": "EntityFramework.Commands"
    },
    "frameworks": {
        "aspnet50" : { }
    }
}
```

/vnext/Model/User.cs

``` cs
using System.ComponentModel.DataAnnotations;

namespace VNext.Models
{
  public class User
  {
    [Key]
    public long id { get; set; }

    [Required]
    [MinLength(4)]
    public string Name { get; set; }

    [Required]
    [MinLength(6)]
    public string Username { get; set; }

    [Required]
    [MinLength(6)]
    public string Password { get; set; }
  }
}
```

/vnext/DAL/MyDbContext.cs

``` cs
using VNext.Models;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace VNext.DAL
{
  public class MyDbContext : DbContext
  {    
    public MyDbContext() : base("VNextConnectionString")
    {
      Database.SetInitializer<MyDbContext>(new MyDbInitializer());
    }

    public DbSet<User> Users { get; set; }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
      modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
    }
  }
}
```

and my /vnext/Web.config

``` xml
<connectionStrings>
  <add name="VNextConnectionString" providerName="MySql.Data.MySqlClient" connectionString="server=localhost;UserId=vnext;Password=vnext..;database=vnext_development;CharSet=utf8;Persist Security Info=True"/>
</connectionStrings>
```

This is my kvm list output:

| Active | Version | Runtime | Location | Alias |
| --- | --- | --- | --- | --- |
| * | 1.0.0-beta1 | Mono | ~/.kre/packages | default |

and my nuget sources are:
1. https://www.nuget.org/api/v2/
2. https://www.myget.org/F/aspnetvnext/api/v2/

Any ideas?

This is my all source code: https://github.com/roalcantara/vnext

Cheers.

**Comment by roalcantara** [comment]
Hi @rowanmiller and @Praburaj thank you so much for your reply.

I was definitely using the wrong code sample. Fallowing the MusicStore source and the [Configuring-a-DbContext Wiki](https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext#config-inline-in-code) did the trick.

Now, when I run 

```
$ k ef 
```

I see the **unicorn**! :)

However, when I run 

```
$ k ef migration Add AddUser
```

I'm getting:

**System.InvalidOperationException: No service for type 'Microsoft.Data.Entity.Infrastructure.DbContextService`1[Microsoft.Data.Entity.Migrations.Infrastructure.Migrator]' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[DbContextService`1] (IServiceProvider provider) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.MigrationTool.CreateMigrator (Microsoft.Data.Entity.DbContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.MigrationTool.CreateScaffolder (Microsoft.Data.Entity.DbContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration (System.String migrationName, System.String contextTypeName, System.String rootNamespace, System.String projectDir) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.Program.AddMigration (System.String name, System.String context) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.Program+<>c__DisplayClass4.<Main>b__17 () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute (System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0**

I might have missed some configuration.

This is the /vnext/config.json
```json
{
  "Data": {
    "DefaultConnection": {
        "ConnectionString":"server=localhost;UserId=vnext;Password=vnext..;database=vnext_development;CharSet=utf8;Persist Security Info=True",
        "ProviderName":"MySql.Data.MySqlClient"
    }
  },
  "EntityFramework": {
    "MyDbContext": {
        "ConnectionStringKey": "Data:DefaultConnection:ConnectionString"
    }
  }
}
```

the /vnext/Models/VNextContext.cs
```cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata;

namespace VNext.Models
{
  public class VNextContext : DbContext
  {
    public DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<User>().Key(a => a.Id);
      base.OnModelCreating(builder);
    }
  }
}
```

and the /vnet/Startup.cs
```cs
using System;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Diagnostics;
using Microsoft.AspNet.Diagnostics.Entity;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Routing;
using Microsoft.Data.Entity;
using Microsoft.Framework.Cache.Memory;
using Microsoft.Framework.ConfigurationModel;
using Microsoft.Framework.DependencyInjection;
using VNext.Models;

namespace KWebStartup
{
  public class Startup
  {
    public Startup()
    {
      Configuration = new Configuration()
                  .AddJsonFile("config.json")
                  .AddEnvironmentVariables(); //All environment variables in the process's context flow in as configuration values.
    }

    public IConfiguration Configuration { get; private set; }

    // This method gets called by the runtime.
    public void ConfigureServices(IServiceCollection services)
    {
        // Add EF services to the services container.
        services.AddEntityFramework(Configuration)
                .AddDbContext<VNextContext>();

        // Add MVC services to the services container.
        services.AddMvc();
    }

    //This method is invoked when ASPNET_ENV is 'Development' or is not defined
    //The allowed values are Development,Staging and Production
    public void ConfigureDevelopment(IApplicationBuilder app)
    {
      //Display custom error page in production when error occurs
      //During development use the ErrorPage middleware to display error information in the browser
      app.UseErrorPage(ErrorPageOptions.ShowAll);  
      app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);

      // Add the runtime information page that can be used by developers
      // to see what packages are used by the application
      // default path is: /runtimeinfo
      app.UseRuntimeInfoPage();

      Configure(app);
    }

    // Configure is called after ConfigureServices is called.
    public void Configure(IApplicationBuilder app)
    {
      app.UseStaticFiles();

      // Add MVC to the request pipeline
      app.UseMvc(routes =>
      {
        routes.MapRoute(
            name: "default",
            template: "{controller}/{action}/{id?}",
            defaults: new { controller = "Home", action = "Index" });

        routes.MapRoute(
            name: "api",
            template: "{controller}/{id?}");
      });
    }
  }
}
```

Any ideas?

By the way, do you happen to know if is there any sample of EF7 + MySQL? I couldn't find any on google.

Thanks a lot.

And happy new year!

**Comment by rowanmiller** [comment]
Hey,

You need to also register the SQL Server services in Startup.cs:

```
        // Add EF services to the services container.
        services.AddEntityFramework(Configuration)
                .AddSqlServer()
                .AddDbContext<VNextContext>();
```

And you need to tell EF to use SQL Server for that particular context. You can do that in your context:

```
        protected override void OnConfiguring(DbContextOptions builder)
        {
            builder.UseSqlServer();
        }


Or in Startup.cs:

```
        services.AddEntityFramework(Configuration)
                .AddSqlServer()
                .AddDbContext<VNextContext>(options => options.UseSqlServer());
```

In the future you will be able to specify the provider in config.json too... but not just yet.

~Rowan

**Comment by roalcantara** [comment]
Hi @rowanmiller,

Thank you so much for your help.

I had taken off that lines cuz I wanted to use MySQL instead of SQL Server and I thought that lines were only for SQL Server. Sorry about that.

Anyway, I've updated my Startup.cs as suggested, have a look:

```cs
using System;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Diagnostics;
using Microsoft.AspNet.Diagnostics.Entity;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Routing;
using Microsoft.Data.Entity;
using Microsoft.Framework.Cache.Memory;
using Microsoft.Framework.ConfigurationModel;
using Microsoft.Framework.DependencyInjection;
using VNext.Models;

namespace KWebStartup
{
  public class Startup
  {
    public Startup()
    {
      Configuration = new Configuration()
                  .AddJsonFile("config.json")
                  .AddEnvironmentVariables(); //All environment variables in the process's context flow in as configuration values.
    }

    public IConfiguration Configuration { get; private set; }

    // This method gets called by the runtime.
    public void ConfigureServices(IServiceCollection services)
    {
        // Add EF services to the services container.
        services.AddEntityFramework(Configuration)
                .AddSqlServer() //register the SQL Server services
                .AddDbContext<VNextContext>(options => options.UseSqlServer()); //telling EF to use SQL Server for that particular context

        // Add MVC services to the services container.
        services.AddMvc();
    }

    //This method is invoked when ASPNET_ENV is 'Development' or is not defined
    //The allowed values are Development,Staging and Production
    public void ConfigureDevelopment(IApplicationBuilder app)
    {
      //Display custom error page in production when error occurs
      //During development use the ErrorPage middleware to display error information in the browser
      app.UseErrorPage(ErrorPageOptions.ShowAll);  
      app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);

      // Add the runtime information page that can be used by developers
      // to see what packages are used by the application
      // default path is: /runtimeinfo
      app.UseRuntimeInfoPage();

      Configure(app);
    }

    // Configure is called after ConfigureServices is called.
    public void Configure(IApplicationBuilder app)
    {
      app.UseStaticFiles();

      // Add MVC to the request pipeline
      app.UseMvc(routes =>
      {
        routes.MapRoute(
            name: "default",
            template: "{controller}/{action}/{id?}",
            defaults: new { controller = "Home", action = "Index" });

        routes.MapRoute(
            name: "api",
            template: "{controller}/{id?}");
      });
    }
  }
}
```

However, when I run:

```
$ k ef migration add AddUser
```

I'm still getting:

**System.InvalidOperationException: No service for type 'Microsoft.Data.Entity.Infrastructure.DbContextService`1[Microsoft.Data.Entity.Migrations.Infrastructure.Migrator]' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[DbContextService`1] (IServiceProvider provider) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.MigrationTool.CreateMigrator (Microsoft.Data.Entity.DbContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.MigrationTool.CreateScaffolder (Microsoft.Data.Entity.DbContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration (System.String migrationName, System.String contextTypeName, System.String rootNamespace, System.String projectDir) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.Program.AddMigration (System.String name, System.String context) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.Program+<>c__DisplayClass4.<Main>b__17 () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute (System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.Commands.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0**

I'm really thinking I might be missing some configuration..

Any thoughts?

**Comment by roalcantara** [comment]
Hi folks,

Can we use MySQL on asp.net vnext?

If not, how do you usually develop asp.net vnext applications on OSX?

Thanks a lot.

**Comment by rowanmiller** [comment]
@roalcantara - Any chance you could share the actual code files so we could debug locally and see what is going wrong? I can't see anything obviously wrong with the code you have posted.

There is no MySQL provider for EF7 just yet. Our team is working to sure up our SQL Server provider, then we'll look at PostgreSQL and get back to finishing other providers we started (SQLite, Azure Table Storage, Redis).

**Comment by roalcantara** [comment]
Hi @rowanmiller, thanks again for your reply.

Yeah, sure. This is the source code: https://github.com/roalcantara/vnext

So, if there is no MySQL provider for EF7 yet, how do you develop asp.net vnext on OSX?

What would you suggest? Can I install SQLServer on OSX? Or, perhaps, having a Windows on dual-boot would be the way to go for now?

Cheers mate.

**Comment by glen-84** [comment]
@roalcantara,

As I understand it, EF7 is in the early stages of development, and a MySQL provider is not yet available.

It seems the current options are: SqlServer, SQLite, AzureTableStorage, and InMemory (according to [this](https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Traditional-.NET-Applications) page).

@rowanmiller,

Are there any issues (either here or on the MySQL website) that we can watch for progress in this regard?

**Comment by divega** [comment]
@roalcantara what @glen-84 @ says is correct. It might also help to look at this blog post on [priorities, and focus for the Initial release of EF7](http://blogs.msdn.com/b/adonet/archive/2014/12/02/ef7-priorities-focus-and-initial-release.aspx) to understand where we are. 

We want to have a good story for server development targeting OSX and Linux and we are planning to work towards that after the initial release, but at this point we haven't really picked a provider that we would build. PostgreSQL and MySQL are the main contenders (although SQLite could be OK for small applications and we would like to have a story for connecting to SQL Server on a Windows box at some point). 

Feedback and any knowledge of potential contributions from the community should help us make the best choice.

**Comment by glen-84** [comment]
@divega Would the MySQL provider not be written by MySQL, like the one for EF6? ([link](http://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html))

If it will be written by the EF team, then I would say that MySQL > SQLite or PostgreSQL.

**Comment by divega** [comment]
@glen-84 I read this as you saying that all things being equal, you would find MySQL the most useful. Is that correct? 

Writing the provider isn't a goal for us on its own, but it would be a means to accelerate getting something out there that works well with EF7. 

Incidentally, we have been working on a SQLite provider, mostly because it is the de facto option local data access.

**Comment by glen-84** [comment]
@divega, apologies for not being clear. What I meant was that MySQL tends to have a greater following and a larger community than PostgreSQL, which means that implementing it would satisfy more developers.

I would position SQLite separately to the above two, because it has a different usage profile (local data access, smaller databases, etc.), and may be important for things like mobile application development.

**Comment by divega** [comment]
@glen-84 Agreed that SQLite is on a different category. Thanks for your feedback. We'll keep it in mind.

**Comment by roalcantara** [comment]
@divega, @glen-84, @rowanmiller thanks for the replies.

Well, I've decided use the Azure as datasource. Then, I don't need to have any database locally, and I can develop tranquilly on my OSX.

My customer, however, requested me to use EF6 instead of EF7, once he reckons that the EF7 is still in their initial stage of development at the moment and is not recommended for production.

What would you say about this? Do you guys agree? If so, can I develop vNext normally using EF6 on my OSX?

Cheers.

**Comment by rowanmiller** [comment]
@roalcantara - Both EF7 and ASP.NET vNext aren't ready for production use (they are both on the same timeline to an initial release). That said, EF7 is probably still seeing a higher rate of major API changes etc. as it was more of a re-write than most areas of ASP.NET vNext.

EF6 should work on Mono (but it's not a scenario that our team has historically verified for EF6 and earlier releases). You wouldn't be able to target the .NET Core though, it would need to be full .NET. You also loose integration with dependency injection etc.

**Comment by rowanmiller** [comment]
@roalcantara There has been a lot of discussion on this thread. I just wanted to see if you had outstanding issues still or if we can close this one now?

**Comment by rowanmiller** [comment]
Closing but please reopen if further discussion is needed
