### ISSUE TITLE
Value Objects / Complex Type not working on collection of entities in Entity Framework Core v2.0

### ISSUE THREAD

**Issue by NickCook-StruMIS** [dotnet/efcore#13418]
Hi, 

I am trying to incorporate a value object on a collection of entities in Core 2.0 and it is not working. I can create a value object on the Aggregate Root (say Purchase Order), with no problem but when I apply a value object to a child entity (say Purchase Order Item), which is a collection of entities under the aggregate root, it does not work. I have set them up exactly the same and the child entity will persist the changes to the database but EF does not populate the value object on requery.  I must be doing something wrong or this not supported?

Any Help. Thanks.

**Comment by SSkovboiSS** [comment]
Hi @NickCook-StruMIS 
Can you provide an example of code that demonstrates the problem?

**Comment by NickCook-StruMIS** [comment]
Hi, thanks for your help, please see below:

Here we have a Value Object called PricePerUnit: 

public class PricePerUnit : ValueObject<PricePerUnit>
    {
        public double UnitPrice { get; private set; }
        public double Value { get; private set; }

        private PricePerUnit() {}    //EF requires a paramterless constructor to populate the object in reflection.

        public PricePerUnit(double unitPrice, double value)
        {
            UnitPrice = unitPrice;
            Value = value;
        }

}

Here is the AggregateRoot entity CostCentre that has a collection of CostCode Entities:

 public class CostCentre : AggregateEntity
    {
        public string Name{ get; private set; }

        public PricePerUnit PricePerUnit { get; set; }

        public IList<CostCode> CostCodes { get; set; }
    }


public class CostCode : Entity
    {
        public string Name { get; set; }

        public int CostCentreId { get; set; }

        public virtual CostCentre CostCentre { get; set; }

        public PricePerUnit PricePerUnit { get; set; }
     
    }


Here is the context that tells EF that CostCentre & CostCode owns the Value object:

modelBuilder.Entity<CostCentre>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.UnitPrice).HasColumnName("UnitPrice");
modelBuilder.Entity<CostCentre>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.Value).HasColumnName("Value");

modelBuilder.Entity<CostCode>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.UnitPrice).HasColumnName("UnitPrice");
modelBuilder.Entity<CostCode>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.Value).HasColumnName("Value");


In the base context EF populates the Entity graph with the values from the database:

 internal T GetById<T>(int id) where T : AggregateEntity
        {
            var aggregate = Set<T>().Where(x => x.Id == id);

            var aggregateName = typeof(T).Name;

            var aggregatePaths = EntityConfiguration.GetAggregatePaths(aggregateName);

            if (aggregatePaths != null)
            {
                foreach (var aggregatePath in aggregatePaths)
                {
                    aggregate = aggregate.Include(aggregatePath);
                }

            }

            return aggregate.FirstOrDefault();
        }

(The EntityConfiguration.GetAggregatePaths part is just constructing the includes path for the CostCode entity because we eager load)

Now: EF persists the value object properties to both tables (CostCentre & CostCode), when it saves the graph through SaveChanges. But when EF requires the database it does not populate any of the child entities CostCode.PricePerUnit properties but it does populate CostCentre.PricePerUnit correctly.

So, as my original question states it looks like core is not populating value objects when it pulls the entity from the database (for entities that are in a collection).

Julie Lerman states "Owned Type Mapping doesn't currently support mapping properties that are collctions of owned types; but that feature is coming". Is this the problem? 
This implies collections of owned types, which is not what i am doing here. My example is just simple collection of entites but one of the properties is a value object.

Any help would be great, i'm sure this worked in EF 6.

Thanks.

**Comment by NickCook-StruMIS** [comment]
As a follow up, I have trapped the SQL generated from EF when it inserts and retrieves the CostCentre & CostCode objects. As you can see the UnitPrice & Value is being inserted on both objects CostCentre & CostCode (proving that my OwnsOne mapping is correct in the context). But the sql generated for the retrieve includs the UnitPrice & Value for the CostCentre but not the CostCode. So EF is not constructing the Select SQL statement correctly but it is constructing the Insert statement correctly.

exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [CostCentre] ([CreatedBy], [CreatedOn], [Description], [Name], [System], [UpdatedBy], [UpdatedOn], [Version], [UnitPrice], [Value])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9);
SELECT [CostCentreID], [RowVersion]
FROM [CostCentre]
WHERE @@ROWCOUNT = 1 AND [CostCentreID] = scope_identity();
',N'@p0 nvarchar(4000),@p1 datetime2(7),@p2 nvarchar(50),@p3 nvarchar(4000),@p4 int,@p5 nvarchar(4000),@p6 datetime2(7),@p7 int,@p8 float,@p9 float',@p0=N'Webuser',@p1='2018-09-26 16:14:05.3820991',@p2=N'Insert Test',@p3=N'41e0a1a2-6310-48de-9f21-be6eacb8b8f4',@p4=0,@p5=N'Webuser',@p6='2018-09-26 16:14:05.3821026',@p7=0,@p8=2,@p9=3

exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [CostCode] ([CostCentreId], [Description], [Name], [System], [UnitPrice], [Value])
VALUES (@p10, @p11, @p12, @p13, @p14, @p15);
SELECT [CostCodeID]
FROM [CostCode]
WHERE @@ROWCOUNT = 1 AND [CostCodeID] = scope_identity();
',N'@p10 int,@p11 nvarchar(50),@p12 nvarchar(50),@p13 int,@p14 float,@p15 float',@p10=1217,@p11=NULL,@p12=N'CostCode1',@p13=0,@p14=5,@p15=6

exec sp_executesql N'SELECT TOP(1) [x].[CostCentreID], [x].[CreatedBy], [x].[CreatedOn], [x].[Description], [x].[Name], [x].[RowVersion], [x].[System], 
[x].[UpdatedBy], [x].[UpdatedOn], [x].[Version], [x].[CostCentreID], [x].[UnitPrice], [x].[Value]
FROM [CostCentre] AS [x]
WHERE [x].[CostCentreID] = @__id_0
ORDER BY [x].[CostCentreID]',N'@__id_0 int',@__id_0=1214

exec sp_executesql N'SELECT [x.CostCodes].[CostCodeID], [x.CostCodes].[CostCentreId], [x.CostCodes].[Description], [x.CostCodes].[Name], [x.CostCodes].[System]
FROM [CostCode] AS [x.CostCodes]
INNER JOIN (
    SELECT DISTINCT [t].*
    FROM (
        SELECT TOP(1) [x0].[CostCentreID]
        FROM [CostCentre] AS [x0]
        LEFT JOIN [CostCentre] AS [x.PricePerUnit0] ON [x0].[CostCentreID] = [x.PricePerUnit0].[CostCentreID]
        WHERE [x0].[CostCentreID] = @__id_0
        ORDER BY [x0].[CostCentreID]
    ) AS [t]
) AS [t0] ON [x.CostCodes].[CostCentreId] = [t0].[CostCentreID]
ORDER BY [t0].[CostCentreID]',N'@__id_0 int',@__id_0=1214

**Comment by ajcvickers** [comment]
@NickCook-StruMIS I haven't been able to reproduce this--my code is below. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

```C#
public class PricePerUnit
{
    public double UnitPrice { get; private set; }
    public double Value { get; private set; }

    private PricePerUnit() { }

    public PricePerUnit(double unitPrice, double value)
    {
        UnitPrice = unitPrice;
        Value = value;
    }
}

public class CostCentre
{
    public int Id { get; set; }

    public string Name { get; private set; }

    public PricePerUnit PricePerUnit { get; set; }

    public IList<CostCode> CostCodes { get; set; }
}

public class CostCode
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int CostCentreId { get; set; }

    public virtual CostCentre CostCentre { get; set; }

    public PricePerUnit PricePerUnit { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CostCentre>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.UnitPrice).HasColumnName("UnitPrice");
        modelBuilder.Entity<CostCentre>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.Value).HasColumnName("Value");

        modelBuilder.Entity<CostCode>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.UnitPrice).HasColumnName("UnitPrice");
        modelBuilder.Entity<CostCode>().OwnsOne(p => p.PricePerUnit).Property(ppu => ppu.Value).HasColumnName("Value");
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new CostCentre
            {
                PricePerUnit = new PricePerUnit(3.3, 4.4),
                CostCodes = new List<CostCode>
                {
                    new CostCode
                    {
                        PricePerUnit = new PricePerUnit(1.1, 2.2)
                    }
                }
            });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var codes = context.Set<CostCentre>().Include(e => e.CostCodes).ToList();
        }
    }
}
```
![image](https://user-images.githubusercontent.com/1430078/46106349-4b23ff80-c18d-11e8-9674-0930d38285a7.png)

**Comment by NickCook-StruMIS** [comment]
Problem solved Thanks @ajcvickers, it turns out our base context was still referencing EntityFrameworkCORE v2.0.1. Taking your sample and creating a new project forced me to get the latest version of EntityFramework which works fine. It must have been a bug that the Entity Framework team fixed between versions. I am amazed that no one else has picked up on this because I did search every where before creating this post. Thanks again, you saved me a lot of time.
