### ISSUE TITLE
SqlServer Spatial: Add provider-specific functions

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#13421]
We should consider adding (based on feedback) some of SQL Server's spatial methods to `EF.Functions`.

SQL Method | Notes
--- | ---
AsBinaryZM | Like `new WKBWriter().Write(geometry)`
AsGml | Like `new GMLWriter().Write(geometry)`
BufferWithCurves | Needs NetTopologySuite/NetTopologySuite#247
BufferWithTolerance | Like `geometry.Buffer(distance, parameters)`
CollectionAggregate | Needs #13278
ConvexHullAggregate | Needs #13278
CurveToLineWithTolerance | Potential workaround for NetTopologySuite/NetTopologySuite#247
EnvelopeAggregate | Needs #13278
EnvelopeAngle
EnvelopeCenter
GeomFromGml | Like `new GMLReader().Read(gml)`
HasM | Like `double.IsNaN(point.M)`
HasZ | Like `double.IsNaN(point.Z)`
InstanceOf | Like `geometry is TGeometry`
IsValidDetailed
MakeValid
MinDbCompatibilityLevel | Mitigates serialization format changes
Parse | Like `new WKTReader().Read(text)`
Point | Optimized version of `STPointFromText`
Reduce | Like simplifiers in NTS
ReorientObject
ShortestLineTo | Like `DistanceOp.NearestPoints(geometry1, gometry2)`
STAsText | Like `new WKTWriter().Write(geometry)`
STCurveN | Needs NetTopologySuite/NetTopologySuite#247
STCurveToLine | Potential workaround for NetTopologySuite/NetTopologySuite#247
STGeomCollFromText | Like `new WKTReader().Read(text)`
STGeomCollFromWKB | Like `new WKBReader().Read(binary)`
STGeomFromText | Like `new WKTReader().Read(text)`
STGeomFromWKB | Like `new WKBReader().Read(binary)`
STLineFromText | Like `new WKTReader().Read(text)`
STLineFromWKB | Like `new WKBReader().Read(binary)`
STMLineFromText | Like `new WKTReader().Read(text)`
STMLineFromWKB | Like `new WKBReader().Read(binary)`
STMPointFromText | Like `new WKTReader().Read(text)`
STMPointFromWKB | Like `new WKBReader().Read(binary)`
STMPolyFromText | Like `new WKTReader().Read(text)`
STMPolyFromWKB | Like `new WKBReader().Read(binary)`
STNumCurves
STPointFromText | Like `new WKTReader().Read(text)`
STPointFromWKB | Like `new WKBReader().Read(binary)`
STPolyFromText | Like `new WKTReader().Read(text)`
STPolyFromWKB | Like `new WKBReader().Read(binary)`
UnionAggregate | Needs #13278

**Comment by ajcvickers** [comment]
Note from triage: let's see whether it makes more sense to make a PR to NTS for the curve ones.

**Comment by ajcvickers** [comment]
Closing this as we don't intend to proactively implement these. However, this does not mean will will not implement some specific functions based on feedback, and we will likely consider well-written PRs for any of these.

**Comment by juliusfriedman** [comment]
Just as a FYI NTS Doesn't offer a comparable function for `MakeValid` and I am not sure if one can use the `Microsoft.SqlSerer.Types` package on Linux to do it manually either.
