### ISSUE TITLE
Feature request: Make it possible to generate DbContext as an asbstract class

### ISSUE THREAD

**Issue by nicoabie** [dotnet/efcore#13439]
The use case of this would be multitenant applications.

With different concrete classes for each tenant (maybe not the best idea) or with just one concrete class that extends the abstract DbContext and receives upon creation what is needed to narrow its results to a single tenant.

Having an abstract DbContext would enforce that there is no way to have results of more that one tenant at a time.

I'll like to see which are the community thoughts about this.

I believe one way to work around this is to use [global filters](https://docs.microsoft.com/en-us/ef/core/querying/filters) but it just not seems the cleanest way.

**Comment by Nachitous** [comment]
That actually sounds like an amazing and quite useful idea

**Comment by ajcvickers** [comment]
@nicoabie Can you be more specific about what you mean by "generate"? You can, of course, already create such a base class, so I assume you are asking for something else than the ability to do it. For example:
```C#
public class Blog
{
    public int Id { get; set; }
    public string TenantId { get; set; }
}

public abstract class BaseContext : DbContext
{
    protected BaseContext(DbContextOptions options, string tenantId) 
        : base(options)
    {
        TenantId = tenantId;
    }

    public string TenantId { get; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().HasQueryFilter(b => b.TenantId == TenantId);
    }
}

public class ContextOne : BaseContext
{
    public ContextOne(DbContextOptions<ContextOne> options)
        : base(options, "One")
    {
    }
}

public class ContextTwo : BaseContext
{
    public ContextTwo(DbContextOptions<ContextTwo> options)
        : base(options, "Two")
    {
    }
}

public class Program
{
    public static void Main()
    {
        var serviceProvider = new ServiceCollection()
            .AddDbContext<ContextOne>(o => o.UseInMemoryDatabase("One"))
            .AddDbContext<ContextTwo>(o => o.UseInMemoryDatabase("Two"))
            .BuildServiceProvider();

        using (var scope = serviceProvider.CreateScope())
        {
            var context = scope.ServiceProvider.GetService<ContextOne>();
            context.Add(new Blog { TenantId = context.TenantId });
            context.SaveChanges();
        }

        using (var scope = serviceProvider.CreateScope())
        {
            var context = scope.ServiceProvider.GetService<ContextTwo>();
            context.Add(new Blog { TenantId = context.TenantId });
            context.SaveChanges();
        }

        using (var scope = serviceProvider.CreateScope())
        {
            var context = scope.ServiceProvider.GetService<ContextOne>();

            Console.WriteLine(context.Set<Blog>().Single().TenantId);
        }

        using (var scope = serviceProvider.CreateScope())
        {
            var context = scope.ServiceProvider.GetService<ContextTwo>();

            Console.WriteLine(context.Set<Blog>().Single().TenantId);
        }
    }
}

```

**Comment by nicoabie** [comment]
@ajcvickers yes sorry, I missed an important part and thanks for the fast reply and example provided. The scenario this use case would be most useful is when using database first and scaffolding the DbContext.

There, it is not the developer who writes the definition of the DbContext but the tool itself.

It is a way of enforcing going through a specific context, in your example it is still possible to access the DbContext and query the posts for all tenants.

**Comment by ajcvickers** [comment]
@nicoabie There are many different ways of implementing multi-tenancy. They involved different trade-offs in terms of complexity, efficiency, and isolation. Use query filters can be easy to implement, but doesn't give very good isolation, so if that's something that is important to you, then this probably isn't the correct approach.

With regard to generating this from reverse engineering, again the problem is that there is no one 'right way' to do multi-tenancy, so it's hard to scaffold something general for this. We would rather continue to focus on the underlying mechanisms for this, and then maybe come back to tooling support in the future.

**Comment by nicoabie** [comment]
@ajcvickers, I was just asking for the autogenerated DbContext to be abstract. With that one would be aware to not call it directly but I understand of it's not a priority...

**Comment by ajcvickers** [comment]
@nicoabie The generated `DbContext` class is partial already, which means you can easily make it abstract in your own partial. For example, in the generated code:
```C#
public partial class BloggingContext
{
    //...
}
```
Then in your code add this:
```C#
public abstract partial class BloggingContext
{
    //...
}
```

**Comment by nicoabie** [comment]
@ajcvickers that works for me, thanks a lot!!!
