### ISSUE TITLE
Make service provider hashing more reliable

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/efcore#13437]
This test [fails](http://aspnetci/viewLog.html?buildId=564444&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
Assert.Equal() Failure
                                 ↓ (pos 201)
Expected: ···n changed for 'Core:EnableRichDataErrorHandling', configurati···
Actual:   ···n changed for 'Core:UseMemoryCache', configuration changed fo···
                                 ↑ (pos 201)
   at Microsoft.EntityFrameworkCore.ServiceProviderCacheTest.Reports_debug_info_for_most_similar_existing_service_provider() in /_/test/EFCore.Tests/ServiceProviderCacheTest.cs:line 154
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @ajcvickers

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by AndriySvyryd** [comment]
Ran 2 million iterations without getting a failure.
If the test continues to be flaky we could consider making the cache key bigger to reduce collisions or to require providers to implement a strict `Equals` as well.

**Comment by Eilon** [comment]
@ajcvickers / @AndriySvyryd - maybe safe to close this now? Hasn't failed in quite a while.

**Comment by ajcvickers** [comment]
@Eilon I would like to keep it open for now, since the failures, while rare, are the result of an underlying limitation in hashing for service providers. I think it makes sense to do something different for 3.0.

**Comment by ajcvickers** [comment]
Discussed and decided we are happy with this for now.
