### ISSUE TITLE
Support for ComplexType 

### ISSUE THREAD

**Issue by 3x0dv5** [dotnet/efcore#1344]
In EF6 we have to possibility to use Complex Types such as shown in EF6' documentation:

"There are two ways to configure scalar properties on a complex type.

You can call Property on ComplexTypeConfiguration.

``` C#
modelBuilder.ComplexType<Details>() 
    .Property(t => t.Location) 
    .HasMaxLength(20);
```

You can also use the dot notation to access a property of a complex type.

``` C#
modelBuilder.Entity<OnsiteCourse>() 
    .Property(t => t.Details.Location) 
    .HasMaxLength(20);
```

" from http://msdn.microsoft.com/en-us/data/jj591617#2.1

**Comment by rowanmiller** [comment]
This just isn't implemented yet, already tracked by https://github.com/aspnet/EntityFramework/issues/246
