### ISSUE TITLE
When using .GroupBy then .Include is ignored

### ISSUE THREAD

**Issue by nazarkryp** [dotnet/efcore#13450]
Code Like this:
```C#
var query = Context.Set<MovieCategory>()
                    .Join(Context.Set<Movie>(), mc => mc.MovieId, m => m.MovieId, (category, movie) => new { category, movie })
                    .GroupBy(cmm => cmm.movie)
                    .Select(cm => cm.Key)
                    .Include(e => e.Studio);

var result = await query.ToListAsync();

```
Generates query like this:
```sql
SELECT [e].[MovieId], [e].[CategoryId], [e.Movie].[MovieId], [e.Movie].[Date], [e.Movie].[Description], [e.Movie].[Duration], [e.Movie].[StudioId], [e.Movie].[Title], [e.Movie].[Uri]
FROM [MovieCategories] AS [e]
INNER JOIN [Movies] AS [e.Movie] ON [e].[MovieId] = [e.Movie].[MovieId]
ORDER BY [e.Movie].[MovieId]

```
As a result navigation property Studio in model Movie is null. I've runned the same query in EF6 and it worker fine. Here I've tried different combinations of placing .Include() (e.g: Context.Set<Movie>().Include(e=>e.Studio) etc.)

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.3 (tried latest prerelease verion as well, but no luck)
Operating system:  Win10
IDE: (e.g. Visual Studio 2017 15.8.5)

**Comment by smitpatel** [comment]
Related to #12737

**Comment by ajcvickers** [comment]
Closing as using `Include` after a projection will not be supported.
