### ISSUE TITLE
There is no implicit reference conversion from ApplicationDbContext to Microsoft.EntityFrameworkCore.DbContext

### ISSUE THREAD

**Issue by arndim01** [dotnet/efcore#13464]
While following the [tutorial](https://www.pmichaels.net/tag/dbcontext-identitydbcontext/)  I am getting an error when `DbContextOptions<ApplicationDbContext>`
 which is ApplicationDbContext inherit to IdentityDbContext but when I tried to inherit DbContext it works fine.

![error](https://user-images.githubusercontent.com/6179080/46336558-bf631500-c65d-11e8-9529-2b654ffe9be7.png)

**Exception message:** 
The type 'WebExtractorPortalCore.Context.ApplicationDbContext' cannot be used as type parameter 'TContext' in the generic type or method 'DbContextOptions<TContext>'. There is no implicit reference conversion from 'WebExtractorPortalCore.Context.ApplicationDbContext' to 'Microsoft.EntityFrameworkCore.DbContext'.

**Comment by ralmsdeveloper** [comment]
This is wrong, the correct would be.
```
public class ApplicationIdentityDbContext : IdentityDbContext
{
    public ApplicationIdentityDbContext(DbContextOptions<ApplicationIdentityDbContext> options)
        : base(options)
    {
    }
}
```
DbContextOptions<**IdentityDbContext**>
to
DbContextOptions<**ApplicationIdentityDbContext**>

**Comment by ajcvickers** [comment]
@ralmsdeveloper  The screenshot already shows use of `ApplicationDbContext`.

@arndim01 There is not enough info here to see what is going on. Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by ralmsdeveloper** [comment]
@ajcvickers  Yes, of course, the image seems to have been edited, I almost certainly looked at it, I even created a repro, but thank you.

This may be missing some package, or incompatibility with the target, because the project structure does not appear to be ASP.NET CORE

**Comment by arndim01** [comment]
Hi guys tnx for the respond. The complete code is the same with the tutorial I mentioned above. I actually Im not getting an error if I inherit DbContext and not the IdentityDbContext. I used IdentityDbContext because it has a built-in user authentication which is I needed in the project.

**Comment by arndim01** [comment]
@ralmsdeveloper hi ram yeah you are correct my mistake that's a web api project structure. Although I created a asp.net core, I'm still getting the same error.

**Comment by arndim01** [comment]
Hi guys. I did able to run the code and now its working fine. Its seems that the mistake is because of the packages I used. 

BTW tnx for your time.
