### ISSUE TITLE
Pass connection string as argument to `dotnet ef database update`

### ISSUE THREAD

**Issue by lomholdt** [dotnet/efcore#13465]
When doing a `dotnet ef database update` it could be an awesome feature to enable passing environment variables in style with the [comand line configuration provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.1#command-line-configuration-provider). That way when I want to use another connection string for migrating the database I can simply pass it to the command. This way I don't have to create a specific context using another connection string. 

### Example
```powershell
dotnet ef database update --ConnectionString=(localdb)\mssqllocaldb;Database=...
```

**Comment by RamunasAdamonis** [comment]
Why this issue was closed, is there any resolution for this?

**Comment by ajcvickers** [comment]
@RamunasAdamonis The reason it is closed is because the person who opened it closed it. That being said, I know we have discussed this in the past, but I don't remember the outcome, so re-opening.

**Comment by ajcvickers** [comment]
@bricelam to look for dupe.

**Comment by bricelam** [comment]
Duplicate of #10750
