### ISSUE TITLE
Scaffolded navigation property name no longer meaningful when using composite foreign keys

### ISSUE THREAD

**Issue by tylercamp** [dotnet/efcore#13475]
### The Problem

**When scaffolding using single-column foreign keys, I would get navigation properties with useful names such as:**
```C#
        // fk_army_at_home_id: current_village.army_at_home_id -> current_army.army_id
        public CurrentArmy ArmyAtHome { get; set; }

        // fk_army_owned_id: current_village.army_owned_id -> current_army.army_id
        public CurrentArmy ArmyOwned { get; set; }

        // Same formatting for the rest
        public CurrentArmy ArmyRecentLosses { get; set; }
        public CurrentArmy ArmyStationed { get; set; }
        public CurrentArmy ArmySupporting { get; set; }
```
_(Where `current_army` table has primary key `army_id`)_

**After changing the primary keys to be composite for these tables and setting the foreign keys as composite accordingly, I get generic, uninterpretable names such as:**
```C#
        // fk_army_at_home: current_village.(world_id,army_at_home_id) -> current_army.(world_id,army_id)
        public CurrentArmy CurrentArmy { get; set; }

        // fk_army_owned: current_village.(world_id,army_owned_id) -> current_army.(world_id,army_id)
        public CurrentArmy CurrentArmy1 { get; set; }

        // Same formatting for the rest
        public CurrentArmy CurrentArmy2 { get; set; }
        public CurrentArmy CurrentArmy3 { get; set; }
        public CurrentArmy CurrentArmyNavigation { get; set; }
```
_(Where `current_army` table has composite primary key `world_id,army_id`)_

Setting the new foreign keys to have the same naming convention as the original sample (suffixed with `_id`) has no effect.

### Desired Behavior

In this case the property names should be the same between the above samples. I expected no change in property names when I updated those foreign keys, as the navigation property names seemed to be pulled from the names of the foreign keys.

### Further technical details
EF Core version: 2.1.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL

**Comment by tylercamp** [comment]
> Name of FK property is assumed to be of type `NavigationName + Id`

Does this imply that keeping the same foreign key naming as in the first case should lead to the expected property names?

Maybe I'm missing something, how does the convention not work for composite key?

**Comment by tylercamp** [comment]
If that naming convention does not apply to composite keys, is there any other way to dictate the property name in this case?

**Comment by ajcvickers** [comment]
@tylercamp Do you have a suggestion on how the navigation names could be generated from the information available in the database schema?

**Comment by tylercamp** [comment]
Via foreign key name, as is the case with single-column foreign keys.

Strip prefixes and suffixes of fk, fkey, and id, separated by underscore, and use the current convention of replacing underscores via camel case.

This works for my case and I’d expect other cases, but I’m unfamiliar with the full range of formats that foreign key names may take.

**Comment by tylercamp** [comment]
Even if not used as a primary approach, using this as a fallback would be much preferred to RelationNavigation, Relation1, Relation2, etc

**Comment by ajcvickers** [comment]
@tylercamp Just to clarify, EF Core uses the foreign key _column name_ as the basis for generating the navigation name. It does not use the foreign key _constraint name_. While in your case you have FK constraint names that might, with some manipulation, make reasonable names, our experience from trying to use constraint names for this in the past has been that they are usually not named in a way that would result in this making sense. There also doesn't seem like a good way to combine the column names to do this. Therefore, we think the best thing to do here is to allow customization of the process, which is being tracked by issue #4038

**Comment by tylercamp** [comment]
> Just to clarify, EF Core uses the foreign key _column name_ as the basis for generating the navigation name. It does not use the foreign key _constraint name_.

Thank you, this clarification was needed.

Before I finish by making a custom `IDesignTimeServices` for my specific types and column names, is there a convention for naming of navigations based on composite key column names?
