### ISSUE TITLE
Look at factoring of base relational components to ensure they provide pit of success to provider writers

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1348]
As part of https://github.com/aspnet/EntityFramework/issues/1065 we decided that having an ANSI provider isn't the correct thing to do. In that issue we also discussed looking at the factoring of the base relational provider to ensure we don't _provide defaults that "mostly work" across providers_. We should look at  this to make sure we agree on the factoring (possibly a design meeting topic).

**Comment by rowanmiller** [comment]
We're happy with query pipeline. @ajcvickers to chat with @AndriySvyryd about update pipeline... leaving issue open in case any action items come up from that.

**Comment by ajcvickers** [comment]
Talked to @AndriySvyryd. We are happy with the update pipeline.
