### ISSUE TITLE
Table/Column annotations are empty in custom SqlServerMigrationsSqlGenerator

### ISSUE THREAD

**Issue by btodts** [dotnet/efcore#13497]
Consider the following `EntityTypeConfiguration` which, among others, adds Annotations to the EntityTypeBuilder:

```c#
public void Configure(EntityTypeBuilder<MunicipalityName> builder)
{
    builder.ToTable(TableName, Schema.Legacy)
        .HasKey(p => p.Id)
        .ForSqlServerIsClustered(false)
        .HasAnnotation("Foo", "Bar");

     builder.Property(p => p.Name)
        .HasDefaultValue("Foo!")
        .HasAnnotation("COLLATE", "Latin1_General_CI_AI");
 }
```

In this particular use case, I want to add a `COLLATE` clause to the column definition when a migration is executed. To do this, I created a custom `SqlServerMigrationsSqlGenerator`. In this Generator, I figured I could get a column's annotations and, if necessary, add additional SQL statements to the builder.

This is the custom SqlGenerator's Generate method:

```c#
protected override void Generate(CreateTableOperation operation, IModel model, 
    MigrationCommandListBuilder builder)
 {
    Debugger.Launch();

    base.Generate(operation, model, builder);

    var tableAnnotations = operation.GetAnnotations();
    var columnAnnotations = operation.Columns.SelectMany(c => c.GetAnnotations()).ToList();

    // Additional logic, left out for brevity
```

Unfortunately, both `tableAnnotations` and `columnAnnotations` are always empty:
![2018-10-04 10_55_13-municipalityregistry debugging - microsoft visual studio](https://user-images.githubusercontent.com/12234350/46463443-2ef31480-c7c4-11e8-9f74-98c865bc7ee4.png)

Note that the DefaultValue of "Foo!" does work:
![2018-10-04 10_56_05- clrtype system string](https://user-images.githubusercontent.com/12234350/46463475-3f0af400-c7c4-11e8-8788-577761797798.png)

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10 Enterprise
IDE: Visual Studio Enterprise 2017 15.7.5

**Comment by smitpatel** [comment]
You also need to override https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs to transport annotation from model to MigrationOperations.
