### ISSUE TITLE
Is there a way to inject semaphore?

### ISSUE THREAD

**Issue by alewmt** [dotnet/efcore#13498]
Hi!
I get different kinds of timeouts due to too many threads accessing the database at peak times.  It is not easy to do IQueryable api facade to intercept database requests. Coordination of threads at the application level does not give good results. I would like to know if it is possible to inject `SemaphoreSlim` in `EF` 
to limit the number of simultaneous accesses to the database? I need it to reduce the processing time of one request and do not interrupt requests by timeout.

**Comment by ajcvickers** [comment]
@alewmt This is not something that is currently possible or that we are planning to do. Throttling is not something that should be handled at the EF layer; it would probably make sense to review your architecture and determine where a more traditional throttling mechanism could be inserted.
