### ISSUE TITLE
Model.DebugView Property - Causing Massive Log Growth

### ISSUE THREAD

**Issue by twurm** [dotnet/efcore#13490]
Describe what is not working as expected.
We are using Nlog to handle all of our logging.  We started seeing massive growth while doing some concurrency testing.  The base exception we see (though not the actual problem) is: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

That leads us to the real problem.  The exception contains DebugView information which in this case is over 700,000 characters.  Is there a way to exclude the DebugView information?

We are using the following setting in Nlog: 

      <parameter name="@exception" layout="{exception:format=toString:maxInnerExceptionLevel=10}" />
	  
If you are seeing an exception, include the full exceptions details (message and stack trace).  

```
Exception message: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Stack trace:
{
	"Entries": [{
			"Entity": {
				"Id": 2,
				...				
				"Deleted": false,
				"CreatedById": 17,
				"CreatedDate": "2018-10-02T19:03:39.2493709Z",
				"UpdatedDate": "2018-10-02T19:03:39.6285994Z",
				"RowVersion": [0, 0, 0, 0, 4, 34, 175, 157]
			},
			"State": "Modified",
			"Context": {},
			"Metadata": {
				"Builder": {
					"ModelBuilder": {
						"Metadata": {
							"ChangeTrackingStrategy": "Snapshot",
							"ConventionDispatcher": {
								"Tracker": "Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.MetadataTracker"
							},
							"DebugView": {
								"View": "Model: \r\n  EntityType: Article\r\n    Properties: \r\n      ArticleId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0\r\n        Annotations: \r\n          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping\r\n          SqlServer:ValueGenerationStrategy: IdentityColumn\r\n      Body (string) Required 1 1 -1 -1 -1\r\n        Annotations: \r\n          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping\r\n      CreatedById (int) Required FK Index 2 2 1 -1 1\r\n ……."}

```
Note this is only a small exceprt of what is in DebugView. I'd be more than happy to privatly share the entire log.  

### Steps to reproduce

Anytime you receive the error above "Database operation expected to affect 1 row(s) but actually affected 0 row(s)" run a tostring on the exception.  The larger the database relational model the larger the DebugView data.

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017 15.8.x
NLog: 4.5.9

**Comment by ajcvickers** [comment]
@twurm ToString on the exception doesn't dump out all that information. Presumably there is something else (maybe NLog) which is attempting to read state from the exception object and serialize it into what you posted above. This is actually a dangerous thing to do without a lot of care because the state of the exception is not intended to be used like this and a) can be large (as you see) as well as b) contain potentially sensitive information that probably shouldn't be stored in logs, at least in production.

**Comment by twurm** [comment]
@ajcvickers thanks for the quick response.  

The issue was related to the @ formatter that was added in [Nlog 4.5](https://github.com/NLog/NLog/wiki/Exception-layout-renderer).  

> @ means serialize all Exception-properties into Json-format. Introduced in NLog 4.5
