### ISSUE TITLE
Dotnet tool ef, showing error when installed in the same version.

### ISSUE THREAD

**Issue by alanrezendee** [dotnet/efcore#13505]
Operating system used:
ArchLinux

Dotnet version that presents the error: 2.1.4.
Dotnet ef version that presents the error: 2.1.4.

When I run the simple "dotnet ef" command, where everything is OK with the tool, I should return for example "Entity Framework Core .NET Command-line Tools 2.1.2-rtm-30932", and command-line options of the tool, is displaying the error below:

Error message: A Fatal Error occurred, the required library libhostfxr.so could not be found
If this is a self-contained application, that library should exist in [some path here.
If this is a framework-dependent application, install the runtime in the default location [default location] or use the DOTNET_ROOT environment variable to specify the runtime location.

Before this error I researched a solution that worked for me, but solving the error message reported above, and presenting a new error as per message below, when again running the "dotnet ef" command. Since then I have researched various solutions and none have satisfied my need. Considering this context I was able to make a solution of my own by installing a smaller version of the tool dotnet ef, and this way it worked.

Error Message: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.5' was not found.
 - Check application dependencies and target a framework version installed at:
     / opt / dotnet
 - Installing .NET Core prerequisites might help solve this problem:
     http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
 - The .NET Framework and SDK can be installed from:
     https://aka.ms/dotnet-download
 - The following versions are installed:
     2.1.4 at [/opt/dotnet/shared/Microsoft.NETCore.App]

My doubts are as follows:
Why does dotnet version 2.1.4 and dotnet ef 2.1.3 work, and does it not work with the same 2.1.4 versions?

**Comment by ajcvickers** [comment]
Moved to https://github.com/dotnet/cli/issues/10112 since all these errors are coming from dotnet rather than EF
