### ISSUE TITLE
Memory leak when using fromSql with dynamic sql

### ISSUE THREAD

**Issue by JanEggers** [dotnet/efcore#13513]
related to https://github.com/borisdj/EFCore.BulkExtensions/issues/73

using context.Set<T>().FromSql("select something from #dynamic") causes a memory leak in the Query cache.  

EFCore.BulkExtensions uses this pattern to read entities from a temporary table with dynamic name.

expected behavior:
the FromSql queries should either not be cached at all or there must be a way to disable caching like the Query extensions .AsNoTracking() there should be an option to express .WithoutQueryCaching().

another option would be to create a precompiled query with a rawsqlstring.

### Further technical details
EF Core version: 2.1.4
IDE: Visual Studio 2017 15.8

**Comment by ajcvickers** [comment]
Duplicate of #12902

**Comment by JanEggers** [comment]
related to #12905
