### ISSUE TITLE
Add-Migration with changing FKs fails in 2.1 (works again in 2.2 preview)

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#13529]
I'm leaving this here as a breadcrumb, should anyone else hit this problem.
I originally brought it up in https://github.com/aspnet/EntityFrameworkCore/issues/329 because I thought it was related to SQLite table rebuilds due to constraint changes.

**Overview**
I have a solution with a number of custom mappings.  Along the way I did two mapping changes that were fine in 2.0.0-2.0.3, failed in 2.1.0-2.1.4 and succeed again with the current 2.2 preview.

This happens with the SQLite provider as well as the SQL Server provider.

When I recreated a much simpler repro there was no problem, so it is specific to something else in my model. I will put a repro with MY model on my github account if you are interested in debugging against the EF Core code. (When I do that I will update this issue).

**Scenario one: Adding a join entity and mapping for a  Many-to-Many**
The first mapping change creates a many to many relationship between two entities: Manager and Team
That means adding 
ManagerTeamHistory class
```
public class ManagerTeamHistory {
    public ManagerTeamHistory (Guid managerId, Guid teamId) {
      ManagerId = managerId;
      TeamId = teamId;
    }
    public Guid ManagerId { get; private set; }
    public Guid TeamId { get; private set; }
  }
```
There's a navigation property in only ONE end, which satisfies my domain logic.

I added the mapping in the context
  ` modelBuilder.Entity<ManagerTeamHistory> ().HasKey (m => new { m.ManagerId, m.TeamId });
 `  
And then tried to add the new migration which failed with this error: 
```
data git:(TEST_E1) ✗ dotnet ef migrations add init -s ../console
System.NullReferenceException: Object reference not set to an instance of an object.
  at Microsoft.EntityFrameworkCore.Update.Internal.SharedTableEntryMap`1.CreateSharedTableEntryMapFactory(IReadOnlyList`1 entityTypes, IStateManager stateManager, String tableName, String schema)
  at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffData(TableMapping source, TableMapping target, DiffContext diffContext)
  at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(TableMapping source, TableMapping target, DiffContext diffContext)+MoveNext()
  at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
  at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
  at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
  at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
  at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
  at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
  at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
  at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

**Scenario Two: Replacing a public property in a one-to-one relationship with a backing field**
I had the same error after encapsulating a property in a one to one relationship.
Changing
`public Manager Manager { get; set; }`
to
```
private Manager _manager;
private Manager Manager =>_manager ;
public string ManagerName=>_manager.Name;
```
Because this is resolved in 2.2 as mysteriously as it appeared in 2.1, I am not very concerned about it but wanted to leave this here in case anyone was interested.

**Comment by ajcvickers** [comment]
@smitpatel to investigate

**Comment by smitpatel** [comment]
@ajcvickers @julielerman - No obvious sign what could be wrong in code. I tried to find out possibilities of null ref in related code, looking for signs of change from 2.1 to 2.2 but no luck.

**Comment by julielerman** [comment]
thanks for looking into it. My model is a little weird. It may be a waste of time to track it down for my particular scenario but if someone hits the same thing, hopefully they'll find this thread. I'm just grateful that it magically fixed itself with 2.2. :) If I ever figure out what particular thing was causing it, I'll leave that info here. Closing .... :)

**Comment by joohan** [comment]
Hi! 

I'm getting a NullReferenceException with the same stacktrace as Julie above. I'm however on 2.2.0 preview 3. The configuration works on 2.1.4. 

It works if I remove all migrations and regenerate.  

Any tips on how to pinpoint which model/relationship is creating the error?

Best regards,
Johan

**Comment by ajcvickers** [comment]
@joohan Can you post a runnable project/solution or complete code listing that demonstrates the issue you are seeing?

**Comment by julielerman** [comment]
@ajcvickers Mine is also on Github. but it means opening up a BEFORE branch and making a specific set of changes  then trying to run migrations in order to see what is changing and the impact on the migrations. But oddly while mine worked in 2.0.* and failed inj 2.1.x, it worked again in 2.2. And also as a reminder, this is only happeningn in my strange model, not a super-straightforward model. Do you want to see or maybe its easier (and more relevent... to 2.2)  to investigate with @joohan 2.2 failure?

**Comment by ajcvickers** [comment]
@julielerman I was asking @joohan for a repro.

**Comment by julielerman** [comment]
yes I understood that. Was just offering my own. :)

**Comment by joohan** [comment]
We have quite a big model and I haven't been able to locate which model/relation is causing the exception, just that it worked until upgrade to preview 3.

**Comment by julielerman** [comment]
@joohan I'm going to try out my crazy model with preview 3. I was on preview 2 when it was working.

**Comment by julielerman** [comment]
FWIW, My model migration (which succeeds in 2.0.1,  fails in 2.1.0 and succeeded with 2.2.0-preview2) continues to succeed with  preview3. Also, notable, that when it fails with 2.1 , it's not even due to a change. If I start with zero migrations, add one, make no changes, then add another it still fails with the above error. So it seems to be more about reading the existing model than working out the diff. Do you see that behavior with your problem, @joohan ?

**Comment by joohan** [comment]
Yes, the same happens for me if i start from zero migrations it works. If I however try to add a second migration without making changes to the model I get the error. I also tested on preview1 and preview2. Same problem there.

**Comment by joohan** [comment]
Sorry for the delay in answering. I unfortunately share my files as it's a project for a client.

**Comment by julielerman** [comment]
@joohan Absolutely understand. I am happy to send mine to you (they are only demos) if you have want and have time.

**Comment by joohan** [comment]
Sorry a little short on time so haven't had a time to look at this.

**Comment by joohan** [comment]
We no longer get this error with 2.2

**Comment by jonathanmoffatt** [comment]
All good in 2.2 for us too :)

**Comment by ctrl-alt-d** [comment]
Same problem here. "Solved" removing foreign key constraint names:

```
                entity.HasOne(d => d.Parent)
                    .WithMany(p => p.Children)
                    .HasForeignKey(d => d.ParentId)
                    .OnDelete(DeleteBehavior.Restrict)
                    ;//.HasConstraintName("FK_child_to_parent_FK");  <- removing  this
```
