### ISSUE TITLE
Release notes for 2.1.4?

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#13532]
I moved from 2.1.3 to 2.1.4 and performance against MySQL dropped by roughly half.  I would like to provide more info but honestly I don't know where to begin looking.  My app is a downloader that reads/ writes  multiple tables simultaneously.  I think if I knew what changed between the releases I would have a better starting point.
I am using Pomelo.EntityFrameworkCore.MySql version 2.1.2.  This dependency did not change.

Thank you.

**Comment by ajcvickers** [comment]
@sam-wheat This is what changed: https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aclosed+milestone%3A2.1.5

**Comment by sam-wheat** [comment]
@ajcvickers Thanks Arthur.  False alarm sorry.  Issue resolved.
