### ISSUE TITLE
Unable to load navigation property when i attach the main entity in another DbContext  

### ISSUE THREAD

**Issue by rajeevsoni** [dotnet/efcore#13543]
Not able to load navigation property.

### Steps to reproduce
having a self referencing entity of the below structure.

Post
{
Comment(list)
}

Comment
{
Comment (list) 
}

I have fetched a Post from 1 method and have included only 1st level of comments.
Now i have passed the Post to separate method for some updation on its childs.
Now in the new method i have a new dbContext n i have attached "Post" i.e. DbContext.Attach(Post);
and using below statement  
await DbContext.Entry(Post).Reference(x => x.Comment).LoadAsync();
//this is already loaded as i have included 1st level of comments already.

but  
await DbContext.Entry(Comment).Reference(x => x.Comment).LoadAsync();
this s not loading further child.

EF Core version: 2
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@rajeevsoni There is not enough information here for us to be able to reproduce what you are seeing. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by rajeevsoni** [comment]
@ajcvickers 
Can't share the actual code base.
Find the dummy code snippet below.


  public class Area
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public Area ParentArea { get; set; }
        public List<Area> Child { get; set; }
    }

    public void DoModification()
    {
        int areaId = GetAreaId();

        Area area = null;

        // private readonly Func<AlterDBContext> _dbContextProvider
        using (var dbContext = _dbContextProvider())
        {
            area = await dbContext.Areas.Include(x => x.ParentArea)
                                             .FirstOrDefaultAsync(x => x.Id == areaId);
        }

        await updateAreaStatus();
    }

    public void updateAreaStatus(Area area)
    {
        using (var dbContext = _dbContextProvider())
        {
            dbContext.Attach(area);

            await UPDTParent(area, dbContext);
           
            await dbContext.SaveChangesAsync();
        }
    }

    private async Task UPDTParent(Area area, AlterDBContext dbContext)
    {
        //suppose i have area hirearchy
        //ParetArea1
        //    --SubArea1
        //        -- SubSubArea1
        //
        //if i am currently at 3rd level and start upadating parent then not able to load
        //
       
        await dbContext.Entry(area).Reference(x => x.ParentArea).LoadAsync();

        area.Status = 1;
       
        if (area.ParentArea != null)
        {
            await UPDTParent(area, dbContext);
        }
    }

**Comment by ajcvickers** [comment]
@rajeevsoni This is an infinite recursion:
```C#
private async Task UPDTParent(Area area, AlterDBContext dbContext)
{
    await dbContext.Entry(area).Reference(x => x.ParentArea).LoadAsync();

    area.Status = 1;
       
    if (area.ParentArea != null)
    {
        await UPDTParent(area, dbContext);
    }
}
```

**Comment by rajeevsoni** [comment]
@ajcvickers 
No, there will always be a root area with ParentAreaId = null

**Comment by ajcvickers** [comment]
```C#
public class Area
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Status { get; set; }
    public Area ParentArea { get; set; }
    public List<Area> Child { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<Area> Areas { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        Area area;

        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            area = new Area { Child = new List<Area> { new Area() }, ParentArea = new Area() };
            context.Add(area);
            context.SaveChanges();
        }

        await new Program().DoModification(area.Id);
    }

    public async Task DoModification(int areaId)
    {
        Area area;

        using (var dbContext = new BloggingContext())
        {
            area = await dbContext.Areas.Include(x => x.ParentArea)
                .FirstOrDefaultAsync(x => x.Id == areaId);
        }

        await UpdateAreaStatus(area);
    }

    public async Task UpdateAreaStatus(Area area)
    {
        using (var dbContext = new BloggingContext())
        {
            dbContext.Attach(area);

            await UPDTParent(area, dbContext);

            await dbContext.SaveChangesAsync();
        }
    }

    private async Task UPDTParent(Area area, BloggingContext dbContext)
    {
        await dbContext.Entry(area).Reference(x => x.ParentArea).LoadAsync();

        area.Status = 1;

        if (area.ParentArea != null)
        {
            await UPDTParent(area, dbContext);
        }
    }
}
```
```
Process is terminating due to StackOverflowException.
Press any key to continue . . .
```

**Comment by rajeevsoni** [comment]
@ajcvickers 
Will make it a runnable and will share that solution with you in a while.

But my concern is, if i am getting entity from another context and then using it in another context using Attach i.e. UpdateAreaStatus method

If i do not attach the entity and instread load it again from dbContect using Id of entity then every thing works fine(means loading ParentArea navigation property).

**Comment by rajeevsoni** [comment]
@ajcvickers 
Hi, minor mistake is there while doing recursion for updating parent and also done a small change by not doing eager loading of parentArea. Please refer below update code.

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp4
{
    public class Area
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public Area ParentArea { get; set; }
        public List<Area> Child { get; set; }
    }

    public class BloggingContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

        public DbSet<Area> Areas { get; set; }
    }

    public class Program
    {
        public static async Task Main()
        {
            Area area;

            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                area = new Area { Child = new List<Area> { new Area() }, ParentArea = new Area() };
                context.Areas.Add(area);
                context.SaveChanges();
            }

            await new Program().DoModification(area.Id);
        }

        public async Task DoModification(int areaId)
        {
            Area area;

            using (var dbContext = new BloggingContext())
            {
                area = await dbContext.Areas.FirstOrDefaultAsync(x => x.Id == areaId);
            }

            await UpdateAreaStatus(area);
        }

        public async Task UpdateAreaStatus(Area area)
        {
            using (var dbContext = new BloggingContext())
            {
                dbContext.Attach(area);

                await UPDTParent(area, dbContext);

                await dbContext.SaveChangesAsync();
            }
        }

        private async Task UPDTParent(Area area, BloggingContext dbContext)
        {
            await dbContext.Entry(area).Reference(x => x.ParentArea).LoadAsync();

            area.Status = 1;

            if (area.ParentArea != null)
            {
                await UPDTParent(area.ParentArea, dbContext);
            }
        }
    }
}

**Comment by ajcvickers** [comment]
@rajeevsoni The reason for this is that the foreign key for the relationship is not mapped to a property of the entity type. Instead, the value is being stored in "[shadow state](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties)"--that is, with the tracking information that the context has about the entity. This is fine for a query/update on the same context instance, but if you need to re-attach [disconnected entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities), then the value is lost unless you explicitly carry it with the entity. The easiest way to fix this is just to map the FK to a property. For example:
```C#
public class Area
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Status { get; set; }
    public int? ParentAreaId { get; set; }
    public Area ParentArea { get; set; }
    public List<Area> Child { get; set; }
}
```
