### ISSUE TITLE
Scaffolding problem with BIT type fields

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/efcore#13545]
_From @lm28 on September 13, 2018 7:56_

## Steps to reproduce:
When creating my tables (in SSMS) the script for one of my tables is as follows.

```
	CREATE TABLE dbo.AdmbuildingType(
		[AdmbuildingTypeID] [INT] IDENTITY(1,1) PRIMARY KEY,
		[BuildingTypeCode] [VARCHAR] (20) NOT NULL,
		[BuildingTypeDescr] [VARCHAR] (150) NOT NULL,
		[ReturnInt] [INT] NULL,
		[ReturnBit] [BIT] NOT NULL Default 0,
		[ReturnStr] [VARCHAR] (100) NULL Default '',
		[LastUpdated] [DATETIME] DEFAULT GetDate(),
		[TStamp] [TimeStamp],
		[UpdatedBy] [CHAR] (30) NULL Default '',
		[Obsolete] [BIT] NOT NULL Default 0)
	GO

	ALTER TABLE AdmbuildingType
	ADD CONSTRAINT UCbuildingType UNIQUE(buildingTypeCode)
	GO

```
Typically, this table will be used to display a Code and Description in a drop down box in my app.
If the record is marked as 'Obsolete' then it will not be available for selection.

Now when I run 'Scaffold-DbContext' to create the model in my solution, the following related code is generated in the CONTEXT.cs file (I have removed references to all my other tables).  
Notice that the Bit type fields (ReturnBit and Obsolete) are not listed here. Im not sure why?

	```
public virtual DbSet<AdmBuildingType> AdmbuildingType { get; set; }

	modelBuilder.Entity<AdmbuildingType>(entity =>
	{
		entity.HasIndex(e => e.BuildingTypeCode)
			.HasName("UCbuildingType")
			.IsUnique();

		entity.Property(e => e.BuildingTypeCode).IsUnicode(false);

		entity.Property(e => e.BuildingTypeDescr).IsUnicode(false);

		entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");

		entity.Property(e => e.ReturnStr)
			.IsUnicode(false)
			.HasDefaultValueSql("('')");

		entity.Property(e => e.Tstamp).IsRowVersion();

		entity.Property(e => e.UpdatedBy)
			.IsUnicode(false)
			.HasDefaultValueSql("('')");
	});
``
`And....This is the MODEL that is created by EF.

```
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	namespace RACEZ.Models
	{
		public partial class AdmbuildingType
		{
			[Column("AdmbuildingTypeID")]
			public int AdmbuildingTypeId { get; set; }
			[Required]
			[StringLength(20)]
			public string BuildingTypeCode { get; set; }
			[Required]
			[StringLength(150)]
			public string BuildingTypeDescr { get; set; }
			public int? ReturnInt { get; set; }
			public bool ReturnBit { get; set; }			//Hide this field to prevent the Create and Edit propblem.
			[StringLength(100)]
			public string ReturnStr { get; set; }
			[Column(TypeName = "datetime")]
			public DateTime? LastUpdated { get; set; }
			[Required]
			[Column("TStamp")]
			public byte[] Tstamp { get; set; }
			[StringLength(30)]
			public string UpdatedBy { get; set; }
			public bool Obsolete { get; set; }			//Hide this field to prevent the Create and Edit propblem.
		}
	}

```
Now I create a 'Pages\Adm\BuildingType' folder and then right-click and choose
\Add\ Razor Page \ Razor Pages using Entity framework (CRUD)
Once the process is complete, I rebuild my solution. Now the issues start appearing.
On both the Create.cshtml.cs and the Edit.cshtml.cs files, I am getting a CS1061 error that is related to each of the Bit fields.

The create.cshtml is generated as
```
	@page
	@model RACEZ.Pages.Adm.BuildingType.CreateModel

	@{
		ViewData["Title"] = "Create";
	}

	<h2>Create</h2>

	<h4>AdmbuildingType</h4>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form method="post">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="AdmbuildingType.BuildingTypeCode" class="control-label"></label>
					<input asp-for="AdmbuildingType.BuildingTypeCode" class="form-control" />
					<span asp-validation-for="AdmbuildingType.BuildingTypeCode" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="AdmbuildingType.BuildingTypeDescr" class="control-label"></label>
					<input asp-for="AdmbuildingType.BuildingTypeDescr" class="form-control" />
					<span asp-validation-for="AdmbuildingType.BuildingTypeDescr" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="AdmbuildingType.ReturnInt" class="control-label"></label>
					<input asp-for="AdmbuildingType.ReturnInt" class="form-control" />
					<span asp-validation-for="AdmbuildingType.ReturnInt" class="text-danger"></span>
				</div>
				<div class="form-group">
					<div class="checkbox">
						<label>
							<input asp-for="AdmbuildingType.ReturnBit" /> @Html.DisplayNameFor(model => model.ReturnBit))
						</label>
					</div>
				</div>
				<div class="form-group">
					<div class="checkbox">
						<label>
							<input asp-for="AdmbuildingType.Obsolete" /> @Html.DisplayNameFor(model => model.Obsolete))
						</label>
					</div>
				</div>
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-default" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-page="Index">Back to List</a>
	</div>

	@section Scripts {
		@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	}

```
and the create.cshtml.cs is generated as :

```
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Mvc.RazorPages;
	using Microsoft.AspNetCore.Mvc.Rendering;
	using RACEZ.Models;

	namespace RACEZ.Pages.Adm.BuildingType
	{
		public class CreateModel : PageModel
		{
			private readonly RACEZ.Models.FACEZContext _context;

			public CreateModel(RACEZ.Models.FACEZContext context)
			{
				_context = context;
			}

			public IActionResult OnGet()
			{
				return Page();
			}

			[BindProperty]
			public AdmbuildingType AdmbuildingType { get; set; }

			public async Task<IActionResult> OnPostAsync()
			{
				if (!ModelState.IsValid)
				{
					return Page();
				}

				_context.AdmbuildingType.Add(AdmbuildingType);
				await _context.SaveChangesAsync();

				return RedirectToPage("./Index");
			}
		}
	}

```
Incidentally, I also have a few other tables which, when I try to add a Razor (CRUD) page, ALL the cshtml.cs files in the 'Pages\Adm\tableName' folder report a 'CS0118 - tableName is a namespace, but is used like a type' error.  
I have no idea yet what is causing that problem??  (The two tables that I have tested this on are name ActType and EnrStage)

## Expected behavior:
Bit type fields should be available.

## Actual behavior:

## Additional information about the project being scaffolded, such as:
### Target framework(s):  ASP.Net Core 2.1 EF Razor Page

### Package version of Microsoft.AspNetCore.App  or Microsoft.AspNetCore.All (if applicable): 2.1.1

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:




_Copied from original issue: aspnet/Scaffolding#876_

**Comment by vijayrkn** [comment]
_From @Rick-Anderson on September 13, 2018 19:4_

@lm28 can you come up with the simplest possible sample to reproduce the problem? It's helpful to put the sample on github. You have alot of complexity in your actual code that not necessary to reproduce the problem.

**Comment by vijayrkn** [comment]
_From @lm28 on September 15, 2018 3:39_

Simplest sample. Create a table where one field type is a BIT, then run the scaffold tool.

**Comment by vijayrkn** [comment]
Since this is an issue with EF scaffolder (Scaffold-DbContext), moving to the EF repo.

**Comment by ajcvickers** [comment]
@vijayrkn What is the EF error here? I don't see anything wrong until "\ Razor Pages using Entity framework (CRUD)" is used, which is not EF code.

**Comment by vijayrkn** [comment]
@ajcvickers - This was the initial reported issue 

```
Now when I run 'Scaffold-DbContext' to create the model in my solution, the following related code is generated in the CONTEXT.cs file (I have removed references to all my other tables).
Notice that the Bit type fields (ReturnBit and Obsolete) are not listed here. Im not sure why?
```

**Comment by ajcvickers** [comment]
@vijayrkn Because they are mapped by convention and so do not need any additional configuration in OnModelCreating. If this is the only issue being reported, then this should be closed by-design, but it looks to me like things are failing later.

**Comment by vijayrkn** [comment]
@lm28 - Does this answer your questions? If not, can you let us know what is failing during scaffolding? A sample project would definitely help.
