### ISSUE TITLE
Detect Changes - Incorrect State

### ISSUE THREAD

**Issue by avinash-phaniraj-readify** [dotnet/efcore#13565]
Scenario - 
1. Attach an entity to the context with a known primary key specified (Id > 0)
2. Extend entity graph by adding/associating another entity with an Id > 0
3. Trigger DetectChanges for ex; invoke context.ChangeTracker.Entries().

You will find the new entity (which was not explicitly attached) being tracked. 
It's state however is incorrectly tracked as "Added" and not "Unchanged".

If the new entity were to be attached via context.Attach, its state is correctly determined.

### Steps to reproduce
Repro : https://github.com/avinash-phaniraj-readify/EFCoreTestBed/tree/DetectChangesStateError

```c#
           var context = new TestDbContext(options);

            var emp = new Employee { Id = 1, Name = "known employee" };
            emp.Devices = new List<EmployeeDevice>();
            context.Attach(emp);

            var device = new EmployeeDevice { Id = 1, EmployeeId = 1, Device = "known device" };

            emp.Devices.Add(device);
            context.ChangeTracker.Entries();

            Debug.Assert(context.Entry(device).State == EntityState.Unchanged);
```

### Further technical details
EF Core version: 2.1.4
Database Provider: EntityFrameworkCore.SqlServerCompact35 2.1.2.1
Operating system: Win 10
IDE: (e.g. Visual Studio 2017 15.8.4)

**Comment by ajcvickers** [comment]
@avinash-phaniraj-readify Please see my response to #13564 and also see #13575 which would change this if we chose to implement it.
