### ISSUE TITLE
Query with null-coalesced entity gets client-evaluated

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#13568]
This query throws a `QueryClientEvaluationWarning`:
```C#
Blog a = ctx.Blogs.First();
Blog b = a;
ctx.Posts.Where(p => p.Blog == (a ?? b)).Count();
```

As a workaround, I can compare the PK instead of the navigation:
```C#
decimal? a = ctx.Blogs.First().Seqnr;
decimal? b = a;
ctx.Posts.Where(p => p.Blog.Seqnr == (a ?? b)).Count();
```

EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.Oracle
Operating system: Windows 10
IDE: Visual Studio Professional 2017 15.8.6

**Comment by smitpatel** [comment]
Related #20164
