### ISSUE TITLE
Unexpected results in query

### ISSUE THREAD

**Issue by gighen76** [dotnet/efcore#13570]
There are some concurrent situations where following query:
```c#
var wrongOrderRows = await dbContext.OrderRows.Where(or =>or.OrderOrderId == orderId && or.DeliveryDate != null).ToListAsync();
```
results in a list of rows where items are not what I expect:
```c#
bool wrongResult = wrongOrderRows.Any(or => or.DeliveryDate == null);
```
wrongResult is true: wrongOrderRows contains rows with a null DeliveryDate in spite of what was expressed in "where condition".

### Steps to reproduce
I've following (simplified) model:

```c#
public class Order
{
	public Order()
	{
		OrderRows = new HashSet<OrderRow>();
	}

	[Key]
	public long OrderId { get; set; }

	[InverseProperty("Order")]
	public ICollection<OrderRow> OrderRows { get; set; }
}

public class OrderRow
{
	[Key]
	public long OrderRowId { get; set; }

	[Column(TypeName = "datetime")]
	public DateTime? DeliveryDate { get; set; }

	[Column("Order_OrderId")]
	public long? OrderOrderId { get; set; }

	[ForeignKey("OrderOrderId")]
	[InverseProperty("OrderRows")]
	public Order Order { get; set; }
}


public class OrderServiceDbContext : DbContext
{
	
	public OrderServiceDbContext(DbContextOptions<OrderServiceDbContext> options) : base(options)
	{

	}
	
	public virtual DbSet<OrderRow> OrderRows { get; set; }
	public virtual DbSet<Order> Orders { get; set; }
	
	
	protected override void OnModelCreating(ModelBuilder modelBuilder) 
	{
		modelBuilder.Entity<OrderRow>(entity =>
		{
			entity.HasIndex(e => e.OrderOrderId)
				.HasName("IX_Order_OrderId");

			entity.Property(e => e.OrderRowId).ValueGeneratedNever();

			entity.HasOne(d => d.Order)
				.WithMany(p => p.OrderRows)
				.HasForeignKey(d => d.OrderOrderId);
		});

		modelBuilder.Entity<Order>(entity =>
		{
			entity.Property(e => e.OrderId).ValueGeneratedNever();
		});
	}
}


```

I've a db populated with orders each one containing 10 rows. Code that follows tries to replicate the problem:

```c#
[TestCase]
public void WrongQueryResults()
{
	long orderId = 1; // orderId where I want to execute this test
	int numTasks = 2;
	Task<bool>[] tasks = new Task<bool>[numTasks];

	for (int i = 0; i < numTasks; i++)
	{
		tasks[i] = Task.Run(async () =>
		{
			// initialize dbContext (foreach thread to exclude possibly shared resources)
			var optionsBuilder = new DbContextOptionsBuilder<OrderServiceDbContext>();
			optionsBuilder.UseSqlServer(Environment.GetEnvironmentVariable("PMS_SQL_CONNECTION_STRING"));
			var dbContextOptions = optionsBuilder.Options;

			// try to generate the problem
			using (var dbContext = new OrderServiceDbContext(dbContextOptions))
			{
				// assign null value to all orderRows
				var resetOrderRows = await dbContext.OrderRows.Where(or => or.OrderOrderId == orderId).ToListAsync();
				foreach (var or in resetOrderRows)
				{
					or.DeliveryDate = null;
				}
				// update random row (min 2 threads with different rows to replicate problem)
				// using again dbContext is necessary to replicate the problem
				var orderRow = await dbContext.OrderRows.Where(or => or.OrderOrderId == orderId).OrderBy(or => Guid.NewGuid()).FirstOrDefaultAsync();
				orderRow.DeliveryDate = DateTime.Now;
				await dbContext.SaveChangesAsync();

				// request DeliveryDate != null but it results rows with DeliveryDate == null
				var wrongOrderRows = await dbContext.OrderRows.Where(or => or.OrderOrderId == orderId && or.DeliveryDate != null).ToListAsync();
				bool wrongResult = wrongOrderRows.Any(or => or.DeliveryDate == null); // ... when condition in query is != and not ==

				return wrongResult;
			}

		});
	}

	Task.WaitAll(tasks);
	Assert.IsFalse(tasks.Any(t => t.Result));

}
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: microsoft/dotnet:2.1.1-runtime container
IDE: (Visual Studio 2017 15.8.6)

**Comment by ajcvickers** [comment]
@gighen76 This line:
```C#
var wrongOrderRows = await dbContext.OrderRows.Where(or => or.OrderOrderId == orderId && or.DeliveryDate != null).ToListAsync();
```
is going to do a database query for any rows where the DeliveryDate is not null. However, since the entity instances for these rows are already being tracked it is these tracked instances that are retuened. Since the database is being updated underneath by another thread, it means that these results being tracked by the context are stale and may not match in terms of which entities have DeliveryDate null or not. This is an almost textbook example of a race condition.

These kind of issues are typically avoided by a) using a short-lived context instance that is only used for a single unit-of-work, and b) using [optimistic concurrency patterns](https://docs.microsoft.com/en-us/ef/core/saving/concurrency) to handle conflicts that happen in concurrent updates from multiple units of work.

**Comment by gighen76** [comment]
... but the problem is that it returns tracked instances with DeliveryDate == null even if my condition is !=null.
If my query is orderRows.Where(or => or.DeliveryDate != null) I don't expect orderRows with DeliveryDate == null in result. At most I expect empty list with stale context.

Same code running in older EF (.net 4.5.2) works perfectly.

**Comment by ajcvickers** [comment]
@gighen76 The behavior is the same in all versions of EF, so maybe, since this is a race condition, it just happens that it is being hit with EF Core and not with your older code.

**Comment by gighen76** [comment]
@ajcvickers tanks for your reply. So for a linq query 
orderRows.where(or=>or.DeliveryDate!=null)
 is ok to have orderRows with DeliveryDate=null as result? I expected at least a result with a satisfied condition.

**Comment by ajcvickers** [comment]
@gighen76 Yes, of the entity instances for those rows are already being tracked by the context, and the values in those instances are stale with regard to the database.

**Comment by gighen76** [comment]
@ajcvickers I Think the misunderstand is on what I intend are "placed" those instances. DeliveryDate=null is for instances in stale context even if they are stale with regard of database. I dont intend instances in database but i expected != null at least for those tracked by datacontext.

**Comment by ajcvickers** [comment]
@gighen76 EF always executes queries against the database, so the query will return entity instances based on the value in the database, not the value in the tracked entity. So if the database has been updated since the entity was tracked, then the predicate is still evaluated against the database, but the results may contain stale data that don't match what the predicate tested for in the database.

Issue #2982 tracks combining local and database queries in a way that might give you the results you are expecting, but that change is big and complex. We won't be implementing it any time soon.

**Comment by gighen76** [comment]
@ajcvickers thank you for your reply. 
So there are some situations in that where conditions are not respected and I can't do orderRow.DeliveryDate.Value after a orderRows.Where(or => or.DeliveryDate != null) 
but I've to check again the list returned in memory as follows:
context.orderRows.Where(or => or.DeliveryDate != null).ToList().Where(or => or.DeliveryDate != null)
:(

**Comment by ajcvickers** [comment]
@gighen76 It might be worthwhile looking at this from a bigger picture. First consider if it is really necessary to query multiple times in a single unit of work. Consider instead running one query to get the data, manipulating it in memory without querying a second time, and then deal with conflicts when writing using optimistic concurrency. Alternately, if the unit of work needs to issue multiple queries without the data changing, then this may warrant using a database transaction.
