### ISSUE TITLE
What is the proper way to run migrations in Azure?

### ISSUE THREAD

**Issue by etairi** [dotnet/efcore#13591]
I'm using a local database for development purposes and a deployed database in Azure for production. My problem is that when I locally I can easily apply the migrations with `dotnet ef database update`, but I was wondering how can I apply the migrations to the production database that is in Azure. I think automatic migrations are not available in EF Core. But, I tried to do something like this (from what I gathered online):

```C#
public void Configure(IApplicationBuilder app, 
                      IHostingEnvironment env,
                      IServiceProvider provider)
{
     // Automatic migrations.
     if (env.IsProduction())
     {
         using (var context = provider.GetService<MyContext>())
         {
             context.Database.Migrate();
         }
     }
}
```
This seems to kind of work, but I was wondering whether this is the recommended approach to run migrations in an app hosted in Azure?

**Comment by ajcvickers** [comment]
@AngelosP Can you point us to documentation on how to handle migrations when publishing to Azure?

**Comment by ilmax** [comment]
@etairi When you publish via VisualStudio you can check if you want to run a migration against an azure db (you can also have multiple context and decide via a checkbox if you want to apply migrations for every one of the listed context) if you are using azure devops (formerly vsts) you can generate the migration script via `dotnet ef migration script -i` , this will generate an idempotent script to migrate your db, you have include this one in your artifacts and then simply run the script against the db in your release pipeline, no need for the `context.Database.Migrate()` call. The db migration is done at deploy time, not in the "first run after the update"

**Comment by ilmax** [comment]
@etairi I'm able to run the migration even if the DbContext is outside the web project (so a similar configuration as yours) with asp.net core projects.

O.T. you should really give a try to azure devops :)

**Comment by etairi** [comment]
@ilmax Interesting. I do not get migrations option in publish dialog for my project. It is also ASP.NET Core project.

**Comment by AngelosP** [comment]
> @AngelosP Can you point us to documentation on how to handle migrations when publishing to Azure?

This is probably the best documentation we have on the subject:
https://blogs.msdn.microsoft.com/webdev/2018/05/18/exploring-azure-app-service-web-apps-and-sql-azure/

Unfortunately it's just a blog post, which comes with the usual challenges of not being localized to different languages and not being easy to search for and find using Google/Bing. I'm going to find a nice place for it under docs.microsoft.com and submit a PR to get this info in there.

If anybody has any feedback on the blog post let me know and I'll make sure the article we put up on docs.microsoft.com addresses it.

Thank you
Angelos

**Comment by ajcvickers** [comment]
Thanks @AngelosP

**Comment by Compufreak345** [comment]
@AngelosP Unfortunately the link leads to a 404 page. Is there a new link available?

**Comment by ghorsey** [comment]
Here's a working link:
https://devblogs.microsoft.com/aspnet/exploring-azure-app-service-azure-diagnostics/
