### ISSUE TITLE
EF ignores ValueGeneratedOnAdd 

### ISSUE THREAD

**Issue by msmolka** [dotnet/efcore#13592]
Describe what is not working as expected.

### Steps to reproduce

I have following model
``` c#
public class Area
{        
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTimeOffset CreatedDate { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
       
        public string Name { get; set; }
}
```

I've even added manually:

``` c#
builder.Entity<Area>().Property(r => r.Id).ValueGeneratedOnAdd();
```

The query generated by EF is:
``` sql
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Job].[Area] ([Id], [Name])
VALUES (@p0, @p1);
SELECT [CreatedDate]
FROM [Job].[Area]
WHERE @@ROWCOUNT = 1 AND [Id] = @p0;

',N'@p0 uniqueidentifier,@p1 nvarchar(4000)',@p0='0E466D42-ED59-4023-6E49-08D62F701EBE',@p1=N'test'
```

I would expect that Id will be generated by server. but it is inserted.

### Further technical details
EF Core version: 2.1.4
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system:  Windows 10 Pro
IDE: (e.g. Visual Studio 2017 15.8.7)

**Comment by ajcvickers** [comment]
@msmolka See my answer here: https://github.com/aspnet/EntityFrameworkCore/issues/10070#issuecomment-336502376
