### ISSUE TITLE
In Memory Database Not Persisted with Injected Data when Testing

### ISSUE THREAD

**Issue by aherrick** [dotnet/efcore#13618]
I believe my issue is surrounding this closed out bug. https://github.com/aspnet/EntityFrameworkCore/issues/9613

In reviewing, I've setup a stripped down sample showing the issue:
https://github.com/aherrick/TestServerAndInMemoryDbDemo

The issue boils down to this.

In my Test Project I am spinning up the basic ASP.NET Core server so I can run API tests against it.

I have a simple `DbContext ` where I'm injecting a new User object.
https://github.com/aherrick/TestServerAndInMemoryDbDemo/blob/master/XUnitTestProject1/ApplicationUsersControllerGetApplicationUser.cs

In my ASP.NET Core `Startup` I'm adding a Policy for Authorization. When I try to pull the DbContext back out so I can validate the User/Role, my injected Test user in Memory doesn't exist.

Please feel free to clone my project above.

Thank you!

```
      // add basic policy auth
            services.AddAuthorization(options =>
            {
                options.AddPolicy("Admin", policy =>
                {
                    policy.RequireAssertion(async httpContext =>
                    {
                        // only way I know to get to try and resolve DbContext
                        var atomsDBContext = services.BuildServiceProvider().GetService<ApplicationDbContext>();

                        var user = await atomsDBContext.User.FirstOrDefaultAsync();

                        // don't have a user at this point even though we added during test

                        // validate db access role
                        return true;
                    });
                });
            });
```

**Comment by ajcvickers** [comment]
@aherrick Given that this seems to be the same issue as #9613, what is it that you are hoping for from posting this issue?

**Comment by aherrick** [comment]
@ajcvickers is there another way I can achieve resolving the DB Context? #9613 seemed it was Closed out so I'm not sure what the resolution is.

**Comment by ajcvickers** [comment]
@aherrick I added [a comment](https://github.com/aspnet/EntityFrameworkCore/issues/9613#issuecomment-430722420) to 9613 that shows how to resolve the issue.
