### ISSUE TITLE
how to use snapshot in team develop in three branch

### ISSUE THREAD

**Issue by RenshuozZ** [dotnet/efcore#13626]
i have three branch with .net core web api that use ef core 2.0 
every branch has it own db
we develop in dev  and use dev db  and add-migration .... update database and the snapshot is good
when i merge the dev to master  i  want to sync the change in dev db  to master db 
but add migration is empty  because snapshot is not match with my db 
is there any solution

**Comment by RenshuozZ** [comment]
@bricelam  I look forward to your reply.

**Comment by ajcvickers** [comment]
@RenshuozZ We looked at this in triage, but there is not enough information here to be able to give any meaninful guidance. Can you create a github repo with simple projects in the layout that you are using and then describe where/when the issue happens?

**Comment by ajcvickers** [comment]
@RenshuozZ We need more detailed information about what you are doing. Ideally,, can you create a github repo with simple projects in the layout that you are using and then describe where/when the issue happens?

**Comment by RenshuozZ** [comment]
https://github.com/RenshuozZ/efcoredemo

**Comment by ajcvickers** [comment]
@RenshuozZ Thanks for the code! Can we also get some detailed steps to reproduce what you are seeing? For example, it's not clear to me what, "delete the migration in dev db" means.

**Comment by RenshuozZ** [comment]
@ajcvickers  thank you for your help , I have already solved my problem. I got it wrong.
