### ISSUE TITLE
ForeignKeyAttribute add cascadeDelete cascadeUpdate param

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#13627]
ForeignKeyAttribute add cascadeDelete cascadeUpdate param

**Comment by ajcvickers** [comment]
This is unlikely to go on `ForeignKeyAttribute`, since those types are pretty locked down, but this is a reasonable suggestion for #10864

**Comment by Varorbc** [comment]
[#9750](https://github.com/dotnet/corefx/issues/9750)

**Comment by ajcvickers** [comment]
Duplicate of #9621
