### ISSUE TITLE
Move DesignTimeServiceCollectionExtensions to Microsoft.Extensions.DependencyInjection namespace

### ISSUE THREAD

**Issue by Berreek** [dotnet/efcore#13621]
Is there any reason to not have `DesignTimeServiceCollectionExtensions` in `Microsoft.Extensions.DependencyInjection` namespace as it is recomended [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2) to have all `ServiceCollection` extensions in one namespace ?

`We recommended that apps follow this convention. Place extension methods in the Microsoft.Extensions.DependencyInjection namespace to encapsulate groups of service registrations.`

**Comment by bricelam** [comment]
It's "hidden behind a namespace" since it's an advanced scenario and won't/shouldn't be used by most apps.

**Comment by bricelam** [comment]
We have other extension methods hidden behind the `Infrastructure` namespace for the same reason.
