### ISSUE TITLE
Can not resolve reference: `System.Buffers`, referenced by `System.Memory`

### ISSUE THREAD

**Issue by dannythomas13** [dotnet/efcore#13631]
I am building a cross platform xamarin forms application using vs2017 version 15.8.7 nad after adding reference to ef core sqllite (2.2.0-preview2-35157) I am getting the following error:

Can not resolve reference: `System.Buffers`, referenced by `System.Memory`. Please add a NuGet package or assembly reference for `System.Buffers`, or remove the reference to `System.Memory`

**Comment by ajcvickers** [comment]
@divega to follow up

**Comment by divega** [comment]
@marek-safar this bug report looks a lot like what happened in 2.1. Any new known issues with System.Memory again?

@dannythomas13 If you could provide a repro project that would help us and the Xamarin team a lot.

**Comment by hartez** [comment]
@divega We've got a reproduction project available at https://github.com/xamarin/Xamarin.Forms/issues/3810

**Comment by horizondave** [comment]
I'm getting this error with the 2.1.4 versions of the nuget's.

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by marek-safar** [comment]
Is there any repro? I should just work out of the box if you add both System.Memory and System.Buffers nugets.

**Comment by divega** [comment]
@marek-safar sorry I did not respond before but the repro was provided by @hartez in https://github.com/xamarin/Xamarin.Forms/issues/3810 as he mentioned above in this thread. It seems that one uses EF Core 2.1.3, while @dannythomas13 reported this happening with 2.2.0-preview2, but the error seems identical. 

I will close this issue as external in the meantime, but please mention me in https://github.com/xamarin/Xamarin.Forms/issues/3810 if I can be of any help.
