### ISSUE TITLE
为什么这里没有生成视图model的命令？

### ISSUE THREAD

**Issue by git102347501** [dotnet/efcore#13632]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
Translation: "Why is there no command to generate the view model here?"

**Comment by git102347501** [comment]
Thank you for your answer.

> ```
> dotnet tool install -g dotnet-aspnet-codegenerator
> dotnet aspnet-codegenerator view --dataContext MyDbContext --model MyEntity
> ```

Thank you for your answer！

> 翻译：“为什么没有命令在这里生成视图模型？”

Thank you for your translation！
