### ISSUE TITLE
Changed "Include" behavior with "ToList"

### ISSUE THREAD

**Issue by schamo** [dotnet/efcore#13630]
With EF Core 1.1.x (linked example project uses 1.1.1), we were able to do something like

```c#
            using (var context = new MyDbContext())
            {
                var canReadCount = context.Parents
                    .Include(p => p.Children)
                    .Where(p => CanRead(p))
                    .ToList()
                    .Count;
            }
```

In the CanRead method, the Children navigation property was loaded, and the filtering worked as planned. What's already strange, though, is that the following code does things differently:

```c#
            using (var context = new MyDbContext())
            {
                var canReadCount = context.Parents
                    .Include(p => p.Children)
                    .Count(p => CanRead(p));
            }
```

Here, the child elements won't be loaded in the CanRead method, hence the code won't do what we expect it to. This obviously means that ToList() and Count() are handling inclusion differently - which we don't necessarily understand, but we got used to it.

However, with EF Core 2.1.x (linked example project uses 2.1.4), both of these options now seem to work the same way - not doing what we expected (i.e. with ToList() we now have the same behavior as with Count()). This is a bit annoying, even though we got a workaround for this; we now have a method that returns an Expression that does the same thing as the CanRead() method before:

```c#
            using (var context = new MyDbContext())
            {
                var canReadCount = context.Parents
                    .Include(p => p.Children)
                    .Where(GetCanReadExpression())
                    .Count();
                Console.WriteLine("Using CanRead expression: " + canReadCount);
            }
```

I don't know whether it's a bug, or desired behavior, and in any case, we found a workaround. However, I'd still like to know whether there's a way to "get back" the behavior which we had with "ToList()" in version 1.1.x.

I created two example projects to demonstrate this difference in behavior, which you can find here:
https://github.com/schamo/testef11 (for EF 1.1)
https://github.com/schamo/testef21 (for EF 2.1)

I'm using all of the three methods mentioned above in these projects, and the big difference is with the "ToList()" method, which returned what we desired before, but no longer does.

**Comment by ajcvickers** [comment]
@schamo Using an opaque method call in a `Where` clause is generally a bad idea since there is no way to ever translate it. This is what causes the original queries to be evaluated on the client; the expression version is much better. Beyond this, we changed some of the ways Include works in 2.0, which lead to these differences; the 1.1 behavior was essentially by accident. We also have some ideas going forward to improve this further in 3.0, but those ideas are not fully fleshed out yet.

**Comment by schamo** [comment]
Thanks for your answer. I am totally aware that using expressions is the way to go; I don't actually know why this one was implemented differently. I was just wondering why it worked before and now doesn't any longer. I'm going to implement it the right way then.
