### ISSUE TITLE
when i use FromSql query join sql ,when the column Id have same value ,then the record is same like image

### ISSUE THREAD

**Issue by cherho0** [dotnet/efcore#13641]
sql like this ,c.Id value may be same 
`
SELECT c.Id,a.Id SkuId ,c.Name FarmName,c.SkuType, ifnull(b.id,0) RoomId ,ifnull(b.roomname,'床位') RoomName,
DATE_FORMAT(a.SkuData, '%Y-%m-%d')  SkuData, a.TotalSkuCount, a.UseCount
FROM tuanzi.tblroomsku  a 
left join tuanzi.tblroom b on a.roomid = b.id and a.farmid = b.farmid
left join tuanzi.tblfarmstaymain  c on a.farmid = c.id
`

in the workbench

  | 18 | 北海 | 1 | 31 | 1 | 测试ny | 2018-09-01 | 3 | 0
  | 18 | 北海 | 1 | 32 | 1 | 测试ny | 2018-09-02 | 3 | 0
  | 18 | 北海 | 1 | 33 | 1 | 测试ny | 2018-09-03 | 3 | 0
  | 18 | 北海 | 1 | 34 | 1 | 测试ny | 2018-09-04 | 3 | 0
  | 18 | 北海 | 1 | 35 | 1 | 测试ny | 2018-09-05 | 3 | 0
  | 18 | 北海 | 1 | 41 | 1 | 测试ny | 2018-10-01 | 12 | 0
  | 18 | 北海 | 1 | 42 | 1 | 测试ny | 2018-10-02 | 12 | 0

but in the ef.core is this:

18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 |31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0
18 | 31 | 北海 | 1 | 测试ny | 2018-09-01 | 1 | 3 | 0

but when i use a.id the record was right

**Comment by ajcvickers** [comment]
@cherho0 Entity type instances must each have a unique key value. Instead, try mapping to a [query type](https://docs.microsoft.com/en-us/ef/core/modeling/query-types).
