### ISSUE TITLE
ID object as entity key not queryable

### ISSUE THREAD

**Issue by bobvandevijver** [dotnet/efcore#13669]
Like in #9194, I want to use a dedicated ID object as entity key, which should work fine when value converters are used (as stated by @ajcvickers). However, I seem to hit limitations in the implementation.

I've created a sample project which can be used to demonstrate the problem: https://github.com/bobvandevijver/EFCore_ObjectAsKey.

What happens? EF Core seems to be incapable of translating the key to the database value during query compile time, as this log part shows:
```
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Compiling query model: 
      '(from Book e in DbSet<Book>
      where Property([e], "id") == __get_Item_0
      select [e]).FirstOrDefault()'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model: 
      '(from Book e in DbSet<Book>
      where Property([e], "id") == __get_Item_0
      select [e]).FirstOrDefault()'
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where (Property([e], "id") == __get_Item_0)' could not be translated and will be evaluated locally.
```

This means it will create a query that retrieves all objects, which it does according to the log:
```
 Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [e].[id], [e].[value]
      FROM [Books] AS [e]
```

Then, it uses the `==` comparator (which you **need** to implement, as otherwise it uses reference compare without any warning or whatsoever, which fails as you would expect). This subtle difference already had me stuck for hours (I previously only implemented the `Equals` method). 

However, this has a massive performance impact: I want to select on a PK, the type has a decent conversion defined, but it will first retrieve the whole dataset to search for my PK in memory. This basically means that when you want to use a value conversion, you really shouldn't care about performance. 

My demo project uses a simple `int` as key, but in my real project I want to use `Guid` as primary key. But without query support, it is a no go... I'm using the latest EF Core (2.1.5).

Am I missing something? Can I tell EF how to convert the object to the query? Why can it convert the object to a normal database value, but can it not use the same transformed value for a query?

**Comment by ajcvickers** [comment]
Note for triage: part of #10434, but we should probably keep this open as a specific case to fix.

**Comment by PopovKS** [comment]
Hello @bobvandevijver , i'm faced to same problem and quick fix for that : 


```
    public class User
    {
        public UserId Id { get; set; }
        public Credentials Credentials { get; set; }
    }

    public class UserId
    {
        private UserId()
        {
            
        }

        private UserId(long id)
        {
            Id = id;
        }

        public long Id { get; private set; }

        public static implicit operator long(UserId beaconId)
        {
            return beaconId.Id;
        }

        public static implicit operator UserId(long id)
        {
            return new UserId(id);
        }
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            var userId = (UserId) obj;
            return this.Id == userId.Id;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }

```
and query now : 
`DbContext.Users.Where(l => Convert.ToInt64(l.Id) == Convert.ToInt64(userId)).ToListAsync() `

it works fine.

**Comment by bobvandevijver** [comment]
@PopovKS That indeed does work, but does require you to use the `Convert` trick in every query you write, and it also creates a convert part in the SQL-query, which shouldn't be required.

I would still like to see a complete solution from the ef core team, so I'll wait for that :)

**Comment by latromi-technology** [comment]
I have the same problem, and decide implement @PopovKS approach temporarily...

**Comment by RouR** [comment]
It does not work in case `public string Id { get; private set; } `
Another problem is define it as primary key

**Comment by sygnowskip** [comment]
@bobvandevijver there is a way to make it queryable, but there are also some restrictions in current EF Core implementations (ID's needs to be generated on server side, so you're not able use database identity), you could find more details here: https://sygnowskip.github.io/domain/natural-identifiers-with-entity-framework-core/

**Comment by bobvandevijver** [comment]
@sygnowskip As explained in the earlier comments it is not about it not being queryable in the easy explanation of the word, but about converting the query to something the database actually uses. Your link exactly describes what I already did, but when you are going to look at the executed queries, you will see that the filter will be done in memory.

I'm not sure whether or not this now works with EF Core 3.0, I haven't had the chance to test that version yet.

**Comment by sygnowskip** [comment]
@bobvandevijver my queries will be correctly translated to SQL (as WHERE clause) and executed on database, check tests in my source code. It's working on both, EF Core 2.2 and 3.0.

**Comment by sygnowskip** [comment]
And after additional research, I was able to configure natural ID's and IDENTITY INSERT on database @bobvandevijver - solution for this is here https://github.com/sygnowskip/sygnowskip.github.io/tree/feature/support-for-numeric-natural-ids/sources/2019-11-03-natural-identifiers-with-entity-framework-core/NaturalIdentifiers

**Comment by smitpatel** [comment]
Generated SQL in 3.1
```SQL
      SELECT TOP(1) [b].[id], [b].[value]
      FROM [Books] AS [b]
      WHERE [b].[id] = @__p_0
```
