### ISSUE TITLE
Embedded IgnoreQueryFilters() propagates to parent queries

### ISSUE THREAD

**Issue by myrup** [dotnet/efcore#13668]
I was a bit surprised to find embedded IgnoreQueryFilters() calls propagates to parent queries.

### Steps to reproduce
```c#
var blogs = db.Blogs.Select(blog => new {
   blog.Id,
   Posts = db.Posts.IgnoreQueryFilters().Where(post => post.BlogId == blog.Id)
}).ToList();
```
In the above code I would expect IgnoreQueryFilters to only apply to posts and not also blogs.

### Further technical details
EF Core version: 2.1.2
Database Provider: PostgreSql
Operating system: Mac OS X Mojave
IDE: VS Mac 7.6.9

**Comment by smitpatel** [comment]
`IgnoreQueryFilters` applies to whole query. Just like `AsTracking/AsNoTracking`

**Comment by ajcvickers** [comment]
See also #10275 and #8576

**Comment by divega** [comment]
@myrup one pattern you may consider using to have finer control of what filters are applied in a specific query execution is to introduce flags to shortcircuit spcific filters. The flags can be properties or fields on the DbContext. Your filters would look something like this:

``` csharp
modelBuilder.Entity<Blog>().HasQueryFilter(b => BlogFilterDisabled || b.Tenant == TenantId);
modelBuilder.Entity<Post>().HasQueryFilter(p => PostFilterDisabled || !p.IsDeleted);
```

Note that the flags will result in an additional Boolean parameters sent to the server for each query execution.

**Comment by myrup** [comment]
@ajcvickers @divega I can absolutely work around it. I am just looking at the example code and think that it is very counterintuitive (not C# like) that the filter is applied globally instead of on the collection the method call is on.
