### ISSUE TITLE
EF Core Sqlite 2.1.4 with trigger throws malformed database schema

### ISSUE THREAD

**Issue by redplane** [dotnet/efcore#13685]
I'm using `EF Core sqlite` and `Sqlite` to connect my app to sqlite database.
In my sqlite database, I have one trigger:

```
CREATE TRIGGER IF NOT EXISTS OnTopicInsert
AFTER INSERT ON Topic 
WHEN Topic.Status == 1
BEGIN

    INSERT INTO CategorySummary(CategoryId, TotalPost, TotalFollower, LastTopicId, LastTopicTitle, LastTopicCreatedTime)
    VALUES(Topic.CategoryId, 1, 0, Topic.Id, Topic.Title, Topic.CreatedTime)
    ON CONFLICT(CategoryId) 
    DO UPDATE
    SET TotalPost = TotalPost + 1,
        LastTopicId = Topic.Id,
        LastTopicTitle = Topic.Title,
        LastTopicCreatedTime = Topic.CreatedTime;
END
```

When I run my app, there is exception thrown back:

**SQLite Error 11: 'malformed database schema (OnTopicInsert) - near "ON": syntax error'.**

By using `EF Core sqlite provider` to check sqlite version, it seems like `EF Core Sqlite 2.1.4` is using Sqlite `3.22.0`  which doesn't support `UPSERT` operation.

Do you have any solutions for this ?

Thank you,

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE:  Visual Studio 2017 15.4

**Comment by bricelam** [comment]
See ericsink/SQLitePCL.raw#224. Until then, you can [bring your own copy of SQLite](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/526#issuecomment-396318826).
