### ISSUE TITLE
SqlServerDbFunctionsExtensions      Will it support it?

### ISSUE THREAD

**Issue by stuyun** [dotnet/efcore#13684]
https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.sqlclient.sqlfunctions?view=netframework-4.7.2

**Comment by pmiddleton** [comment]
Some of those methods are supported already.  The rest can be added using the DbFunctionAttribute.  

See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0
