### ISSUE TITLE
Managed Identity Service Connection with EF Core

### ISSUE THREAD

**Issue by mgolois** [dotnet/efcore#13689]
Hello All,

I have an Azure SQL database which has an Azure Web App as admin (taking advantage of the Azure ADD Managed Service Instance [msi]). In my dotnet core app, that would like to connect to my database using Entity Framework. I could not find any documentation on it. Is it supported? 

Thanks,

Golois

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by divega** [comment]
@mgolois Unfortunately we don't have an end to end example of how to do this. 

Using the feature normally requires obtaining the access token form an [`AuthenticationContext`](https://docs.microsoft.com/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext?view=azure-dotnet), and then setting it on the `AccessToken` property on the `SqlConnection` object before you open the connection. 

Will your application target .NET Core? EF Core connects to SQL Server using the SqlClient ADO.NET provider. Support for authentication using an access token was introduced to SqlClient in the .NET Core 2.2 version, which is still in preview. The issue that was addressed is https://github.com/dotnet/corefx/issues/13660, this [blog post]( https://blogs.msdn.microsoft.com/dotnet/2018/10/17/announcing-net-core-2-2-preview-3/) details how to obtain .NET Core 2.2 preview 3, and this is the preview of SqlClient is [on NuGet](https://www.nuget.org/packages/System.Data.SqlClient/4.6.0-preview3-27014-02). 

I would like to at least point you to an authoritative example of how to do this, at least when working with the ADO.NET layer, but I couldn't find it, so I am going to follow up with the SqlClient team. 

In most common usage of EF Core, we create the `SqlConnection` object under the hood, so you don't get a chance to set the `AccsessToken` property before we open the connection. However if you override the `OnConfiguring` method on your derived `DbContext`, you should be able to call `UseSqlServer()` with a new instance of `SqlConnection`.  At a later point, for example before executing the first query or SaveChanges, you should be able to set the AccessToken property. 

We are using https://github.com/aspnet/EntityFrameworkCore/issues/13261 to track a possible improvement to make this more seamless.

**Comment by mgolois** [comment]
Thank you @divega ! yes my app targets .netcore, so we'll just wait for the release of .net core 2.2. Meanwhile, I'm just going to use keyvault and MSI to secure the connection string. Thanks!

**Comment by svrooij** [comment]
@divega is there an update on the sample? I cannot get this to work.
