### ISSUE TITLE
session in core 1.1 framework

### ISSUE THREAD

**Issue by IsaaasI** [dotnet/efcore#13687]
I am trying to use session in core 1.1 framework but not work. 
Any one please give me the best suitable way to use session in c# Core 1.1 solution .

The below error I face in my solution.
![image](https://user-images.githubusercontent.com/17950923/47214926-1aa83d80-d3a8-11e8-8c32-4d725c492641.png)

Also I tried to install **Install-Package Microsoft.AspNet.WebApi.Owin -Version 5.2.6**
and give me the below error
![image](https://user-images.githubusercontent.com/17950923/47215071-b3d75400-d3a8-11e8-868f-ff24a01f9c5a.png)

Any suggestion please .

### Further technical details
Operating system: 
IDE: (e.g. Visual Studio 2017 15.7.2)

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/AspNetCore/issues/3693
