### ISSUE TITLE
Incorrect transformation to Sql

### ISSUE THREAD

**Issue by TemitaTom** [dotnet/efcore#13682]
### Steps to reproduce
c#
Create linq query with group of two tables

```
from v in _ctx.MyTable
join w ...
join w2..
...
group new { w, w2 } by new { w.id, w2.name } into gw
orderby gw.Key.name 
select { gw.Key.id, gw.Key.name }
```

Throw this exception (Spanish version, sorry)
`Sintaxis incorrecta cerca de la palabra clave 'AS'.  Sintaxis incorrecta cerca de la palabra clave 'GROUP'.`

Query transformed to Sql, add ")" in incorrect position

```
SELECT CONVERT(VARCHAR(11), [w].[id] AS [Id0]), [w2].[name] AS [c]
FROM [MY_TABLE] AS [v]
INNER JOIN W ...
INNER JOIN W2 ...
 ...
GROUP BY [w].[id], [w2].[name]
ORDER BY [c]
```

Fixed version
`SELECT CONVERT(VARCHAR(11), [w].[id]) AS [Id0], [w2].[name] AS [c]`

### Further technical details
EF Core version: 2.1.4
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7 (64 Bits)
IDE:  Visual Studio 2017 15.8.7

**Comment by smitpatel** [comment]
#12826
