### ISSUE TITLE
NullReferenceException when calling AddAsync with spatial data

### ISSUE THREAD

**Issue by corstian** [dotnet/efcore#13699]
### Details
When adding an object which contains a spatial property (`IPoint`) with a `null` value EntityFramework Core throws a `NullReferenceException`.

### Reproduction
See the following repository ([https://github.com/corstian/efcore-nullreferenceexception-on-add](https://github.com/corstian/efcore-nullreferenceexception-on-add)) for a minimalistic reproduction of the issue.

### Further technical details
EF Core version: preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by corstian** [comment]
Disregard this, It seems to work properly when using the 2.2.0-rtm-35526 packages :)

**Comment by ffMathy** [comment]
Where can these packages be found, and why are they not on NuGet? When will the be released there?

**Comment by ajcvickers** [comment]
@ffMathy The issue was fixed after preview 3. It will be available on NuGet when we ship 2.2.0 RTM, or you can get it from the nightly builds on NuGet: https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.EntityFrameworkCore.SqlServer/2.2.0-rtm-35526

**Comment by ffMathy** [comment]
Very cool. Are there any estimates on RTM release date, more specifically than "this year"?

**Comment by ErikEJ** [comment]
https://github.com/aspnet/Announcements/issues/307
