### ISSUE TITLE
Would like to have a check for table exists before an exception is thrown when a table already exists for a call to RelationalDatabaseCreator.CreateTables()

### ISSUE THREAD

**Issue by anewton** [dotnet/efcore#13703]
Would like to have a check for table exists before an exception is thrown when a table already exists for a call to RelationalDatabaseCreator.CreateTables()

When attempting to execute the following code, with the intention of creating database tables if they do not exist at runtime, it would be nicer if an exception is not thrown when a table does already exist.  A suggestion is to add a new method called "CreateNeededTables" or "CreateMissingTables" that fails gracefully without throwing an exception.

The CreateTables method in Entity Framework is useful to ensure that database tables exist in a database when writing code first.  This is a specific use case where code creates a Sqlite database file at runtime, as needed, with all the tables created when a dbContext is used for a repository.  The exception is handled in code when a table already exists, however, it would be better to make an attempt to validate the table exists before attempting to create the table.

```c#
RelationalDatabaseCreator databaseCreator =
    (RelationalDatabaseCreator)_dbContext.Database.GetService<IDatabaseCreator>();
databaseCreator.CreateTables();
```

### Further technical details
EF Core version: 
    Assembly Microsoft.EntityFrameworkCore.Relational, Version=2.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 Microsoft.EntityFrameworkCore.Relational.dll

Visual Studio Code info:
    Version: 1.28.2 (system setup)

**Comment by ajcvickers** [comment]
@anewton We have discussed such ideas in the past, but the problem is that just because a table exists doesn't mean that it is up-to-date. The recommended approach for anything other than very simple drop everything/create everything scenarios is to use Migrations.

**Comment by anewton** [comment]
@ajcvickers Thank you for your response. The assumption being made by throwing an exception in CreateTables is that 1. a table already exists and 2. the existing table absolutely is out of date. I'd be happier if CreateTables would simply avoid the throw and do nothing. Rather than forcing an expensive exception on the developer to either code around or implement migrations in a scenario that migrations is not needed or desired. There is a middle ground.
