### ISSUE TITLE
ValueGeneratedOnAdd works like ValueGeneratedOnUpdate and vice versa

### ISSUE THREAD

**Issue by msarm** [dotnet/efcore#13702]
For a datetime field expecting the SQL datetime as default value while adding a new record. When applying the default SQL datetime value along with ValueGeneratedOnAdd condition, it still allows to update the datetime field but when changed to ValueGeneratedOnUpdate it works as expected. Looks like the functionality got swapped here.

## Apply the below code - it will allow to update datetime field
 ```
builder.Property(u => u.Dated).HasColumnType("datetime")
                               .HasDefaultValueSql("getdate()").ValueGeneratedOnAdd();
```

## Apply the below code - it will not allow to update datetime field
```
 builder.Property(u => u.Dated).HasColumnType("datetime")
                              .HasDefaultValueSql("getdate()").ValueGeneratedOnUpdate();
```

### Library used
Assembly Microsoft.EntityFrameworkCore, Version=2.1.4.0

**Comment by ajcvickers** [comment]
@msarm `ValueGeneratedOnAdd` means that if no value is supplied for new entities, then generate one. It does not imply either that an explicit value cannot be supplied instead, or that the value cannot later be updated. The `AfterSaveBehavior` and `BeforeSaveBehavior` control those things from the EF side.

**Comment by ajcvickers** [comment]
@msarm Also, `ValueGeneratedOnUpdate` also does not imply that an explicit value cannot be supplied instead, except that SQL Server doesn't allow this for computed columns.
