### ISSUE TITLE
[2.2] [SQL CE Provider] TypeMapper test fails

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#13707]
After updating to preview 3, and implementing the new Clone pattern for TypeMappings, the following test fails (in the 2.2-preview branch):

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/2.2-preview/test/EntityFramework.SqlServerCompact.Tests/SqlCeTypeMapperTest.cs#L611

What am I doing wrong?

```
Exception message:
Test 'Microsoft.EntityFrameworkCore.SqlCeTypeMapperTest.Can_map_string_base_type_name_and_size(typeName: "nvarchar")' failed:
	System.ArgumentException : Unqualified data type nvarchar on property StringWithSize
	Storage\Internal\SqlCeTypeMapppingSource.cs(162,0): at EFCore.SqlCe.Storage.Internal.SqlCeTypeMappingSource.ValidateMapping(CoreTypeMapping mapping, IProperty property)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo& mappingInfo, IReadOnlyList`1 principals)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(IProperty property)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMappingSource.FindMapping(IProperty property)
	SqlCeTypeMapperTest.cs(621,0): at Microsoft.EntityFrameworkCore.SqlCeTypeMapperTest.Can_map_string_base_type_name_and_size(String typeName)
```

### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: SQL CE
Operating system: 
IDE: Visual Studio 2017 15.8.4

**Comment by ajcvickers** [comment]
@ErikEJ Could be related to the difference here: https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs#L37

@AndriySvyryd may have ideas since he recently looked at something similar in MySQL.

**Comment by AndriySvyryd** [comment]
@ErikEJ Would need to debug to find the cause, but when using `StoreTypePostfix.Size` make sure that `size` is not null

**Comment by ErikEJ** [comment]
It was indeed that difference! All TypeMapper tests passing now! 😄 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/c7fc123ff2df4824165c001973b7cca61d65a1c9
