### ISSUE TITLE
Have YOU tried EF Core 2.2 preview 3

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#13716]
Download numbers indicate that many of you have not:
![image](https://user-images.githubusercontent.com/1430078/47303837-de5c2380-d5d9-11e8-8abc-043b839f0dbc.png)

### This is the **last preview before RTM**. We need you feedback now!

So update to the preview--it's on NuGet--run your tests and see what happens.

More info can be found in the [announcement post](https://blogs.msdn.microsoft.com/dotnet/2018/10/17/announcing-entity-framework-core-2-2-preview-3/).

Comment here on your experience.

👍 if you tried it and it worked. 
👎 if you tried it and it didn't. Please comment on what went wrong.
😕 if you couldn't try it. Please comment on why not.

Please give us the feedback we need to make this a solid release!

**Comment by ErikEJ** [comment]
Filed a test failure #13707 (may well be unrelated) - otherwise all looks good

**Comment by mattrichnz** [comment]
Working really well for me, apart from #13708.

As a side note, to serialise/deserialise IPoint objects propery needed to write a simple custom JsonConverter, would be nice to see one shipped in EF Core but I guess that’s outside the scope of the project.

**Comment by sam-wheat** [comment]
Number 1,537 here.

**Comment by baoduy** [comment]
it is working fine on my project. Happy to see it release.

![image](https://user-images.githubusercontent.com/166953/47331025-f81a6b00-d6ac-11e8-922d-b0319f4d2526.png)

**Comment by DSilence** [comment]
Tried it on my project, so far #13686 is blocking further testing. HUGE thanks to EF team for implementing spatial support! Really looking forward to cleaning up all the messy workarounds in our code.

**Comment by bricelam** [comment]
@mattrichnz Have you considered serializing to GeoJSON? (via the [NetTopologySuite.IO.GeoJSON](https://www.nuget.org/packages/NetTopologySuite.IO.GeoJSON) package)

``` csharp
var json = new GeoJsonWriter().Write(point);
```

**Comment by Starkie** [comment]
Just did. I confirm that #13531 is fixed. Thanks again!

**Comment by bricelam** [comment]
> SqlException : Cannot find either column "dbo" or the user-defined function or aggregate "dbo.Format", or the name is ambiguous.

**Comment by garvincasimir** [comment]
For more context, I am pulling microsoft/mssql-server-linux:latest to run these tests. Last successful run was 5 months ago on v2.0.0. Is it possible something changed on the sql server end?
https://travis-ci.org/garvincasimir/csharp-datatables-parser/builds/388849731

**Comment by ilmax** [comment]
Everything works for me!

**Comment by ajcvickers** [comment]
@smitpatel @maumar Any thoughts on the comments above from @garvincasimir?

**Comment by garvincasimir** [comment]
Thanks @smitpatel I figured it was something like that. I guess it is too late since the decision seems to have already been made but I am uncomfortable with adding dbo by default. Users with other schemas would still need to specify the schema. I wouldn't have called the original behavior a bug. I feel like empty (no schema) is a much better default. Specifying schema as an empty string seems kind of awkward.

**Comment by smitpatel** [comment]
@garvincasimir - Certainly specifying empty string as schema is bit awkward, but mainline scenario for DbFunction to be user defined functions which are most of times server functions for specific user logic. It is true that DbFunction allows you to map to built-in functions but many of the built-in function on server side are mapped with their appropriate CLR side using MethodCallTranslators in provider code. (like string.Lower/Upper etc). Some of them which does not have specific CLR type mapping has been defined on `EF.Functions`. So the scenario of user defined function mapping to built-in function on server side remains minority hence, we decided to make "dbo" default.

**Comment by pmiddleton** [comment]
@garvincasimir - A small point of clarification.  The original issue was that DbFunctions were not using the model's DefaultSchema.  That is what #9214 fixes.  Should you change the DefaultSchema on the model to something other than dbo then DbFunctions will use that.  

As @smitpatel stated the majority use case is for mapping user defined functions and therefore we use the models DefaultSchema for Sql Server.

**Comment by garvincasimir** [comment]
Thanks for the additional context. Makes sense.

**Comment by garvincasimir** [comment]
Seems that this was changed again? Framework seems to be inserting dbo when it finds an empty schema.

**Comment by pmiddleton** [comment]
@garvincasimir - this did change.  

See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#udf-empty-string

**Comment by garvincasimir** [comment]
Thanks @pmiddleton  for the link. So as of now there is no way to call system functions in SQL Server?

**Comment by smitpatel** [comment]
@garvincasimir - The link also shows example on how to configure DbFunction to call system function.

**Comment by garvincasimir** [comment]
@smitpatel  I saw that but it was listed under "Migrations". Not sure how it would apply to query generation (Linq to Sql).

**Comment by smitpatel** [comment]
@garvincasimir - It is listed under "Mitigations" (if I understand you correctly).

**Comment by garvincasimir** [comment]
@smitpatel woops!! I read it wrong (multiple times). I will take a look.
