### ISSUE TITLE
DB2 does not support correlated subquery in order by clause

### ISSUE THREAD

**Issue by ShamsulAmry** [dotnet/efcore#13710]
I'm writing my own provider for DB2 (one of the reason is because the existing official provider is not up to date), and am using EF Core's release/2.1 branch for development.

There are few test failures, which I found out is because DB2 does not support correlated subquery in order by clause. It can only support correlated subquery in projection or where clause. (source: [Correlated subqueries](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqlt.doc/ids_sqt_181.htm))

Would like to get input on what should be the best way going forward around this issue. Ignore affected test cases? I am looking at `SqlTranslatingExpressionVisitor` but am not so sure how to handle that class.

**Comment by ajcvickers** [comment]
@smitpatel to provide some guidance.

**Comment by smitpatel** [comment]
Duplicate of #8032

**Comment by smitpatel** [comment]
@ShamsulAmry - Can you confirm, if the issue you are facing is same as the #8032

**Comment by ShamsulAmry** [comment]
@smitpatel - Yes, I added the reference link to #8032
