### ISSUE TITLE
Named connection strings are only supported when using 'IConfiguration' and a service provider

### ISSUE THREAD

**Issue by mucciols** [dotnet/efcore#13726]
could you please tel me what i am doing wrong?

SCAFOLD DBCONTEXT
```
Scaffold-DbContext -Connection name=DbAsp Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -f
```

CONFIGURESERVICES
```C#
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            
            services.AddDbContext<aspContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DbAsp")));

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }
```

ASPCONTEXT.CS
```C#
public partial class aspContext : DbContext
    {
        public aspContext()
        {
        }

        public aspContext(DbContextOptions<aspContext> options)
            : base(options)
        {
        }
		
		...
}
```

EXCEPTION

InvalidOperationException: A named connection string was used, but the name 'DbAsp' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.

APPSETTINGS.JSON
```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },

  "AllowedHosts": "*",

  "ConnectionStrings": {
    "DbAsp": "Server=xxx;Database=xyz;integrated security=True;"
  }
}
```

Exception message:
Stack trace:
A named connection string was used, but the name 'DbAsp' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 15.7.2)
.NET CORE 2.2 release 3

**Comment by ajcvickers** [comment]
@mucciols We have not been able to reproduce this. Can you post a runnable project/solution or complete code listing that demonstrates the issue you are seeing.

**Comment by mucciols** [comment]
Hi, thank you for your reply. Now i have  injected the dbcontext in the constructor and Now it work.
Best wishes. 
Simone

**Comment by drua** [comment]
We are still facing these issue in dotnetcore **console** application.

Steps to reproduce: 
Create console app ( core 2.1)
Add Entity frameworks from package-manager console
Use database first approach 
`Scaffold-DbContext -Connection name=DbAsp Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -f`

We are getting this same error as soon as we run this command
.

**Comment by ajcvickers** [comment]
@drua By default, a console application created in Visual Studio or by `dotnet` doesn't have any EF code, so when you say that you did not make any modifications to the default created project, that doesn't seem to align with the exception you are seeing. Given this, I think I am misunderstanding what you mean by "default console app". Can you post the "default console app" that you created so we can take a look, and also be specific about how/where it was created.

**Comment by captmomo** [comment]
Is there a workaround for this if I wish to use EF Core in a separate .NET standard class library?

My current project structure is like this:

EFCore.Library (.NET standard class library)
-Models
-Data

DummyStartUp (console application)

`Scaffold-DbContext -Connection name=DefaultConnection -OutputDir Models -ContextDir Data Microsoft.EntityFrameworkCore.SqlServer -Context UEIOSContext -Project DummyStartup -StartupProject DummyStartup -Force`

ERROR
`A named connection string was used, but the name 'DefaultConnection' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.` 
  
I want to use a named connection string to avoid the connection string being written into the dbcontext file.

**Comment by ajcvickers** [comment]
@captmomo It should be possible to wire up everything to make this work outside of an ASP.NET Core application, but I doubt it would be worth it. Instead just use whatever mechanism works for you to load the connection string from wherever you have it stored, and then pass it to EF.

**Comment by captmomo** [comment]
@ajcvickers thanks. I ended up using a dummy mvc project instead and it worked as expected

**Comment by sibeliuz** [comment]
Still does not work in .net core 3.xx web api projects

**Comment by BlackMush** [comment]
@sibeliuz Same here, I couldn't manage to make this work in my web API 3.0 project. I tried with a brand new Web API solution, created with VS 2019, it still doesn't work.

**Comment by captmomo** [comment]
The main thing is to have your web api project reference the class library and Ensure you have a named connectionstring for your web api project.

**Comment by BlackMush** [comment]
@captmomo I'm not sure to understand what you mean by "to have your web api project reference the class library"
Do you mean this (in Startup.cs) : 
`services.AddDbContext<TradeoDataContext>(x => x.UseSqlServer(Configuration.GetConnectionString("TradeoConnectionString")));`
And this, in appSettings.json :
` "ConnectionStrings": {
    "TradeoConnectionString": "Server=xxx;Database=Tradeo;Trusted_Connection=False; User Id=xxx; Password=xxx"
  },`

**Comment by captmomo** [comment]
No. Right click the web project, select add reference, select the projects
tab, select your class library project

**Comment by BlackMush** [comment]
Okay, thanks for the clarification. I didn't figure out you were talking about your previous comments. I'll try that, but that's only a workaround. Maybe I should re-open an issue, I reproduced the problem very easily on a new solution.

**Comment by captmomo** [comment]
Ok now I’m confused
What exactly is the issue you’re facing ?

**Comment by BlackMush** [comment]
Very precisely the one described in the first comment :)

**Comment by captmomo** [comment]
> Very precisely the one described in the first comment :)

 Can you post the solution that you created so we can take a look, and also be specific about how/where it was created. And the command you used?

**Comment by BlackMush** [comment]
> I could attach my project for your reference if it helps.

I believe you, I cannot reproduce the problem on the new solution anymore ! It's still not working on my real API project though. I'll definitely try your solution.

**Comment by zanyar3** [comment]
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
               // add IConfigurationRoot  to get connection string 
                IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();
                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), x => x.UseNetTopologySuite());
            }
        }
```

**Comment by Yan9080** [comment]
> I had this problem with a new Core 3.1 project and a Scaffold-DbContext. Startup.cs has a IConfiguration.
> Adding the DdContext to startup.cs solved the problem
> 
> ```
>     public void ConfigureServices(IServiceCollection services)
>     {
>         ........
>         services.AddDbContext<StipContext>(options =>
>             options.UseSqlServer(Configuration.GetConnectionString("NameOfYourConnectionStringParameter")));
>     }
> ```

Yes, that's the correct answer. 
When we use connectionstring as a parameter inside "appsettings.json" file, then we need to add that code to specify the connectionstring parameter name

**Comment by Shriyanshmit** [comment]
> Hi, thank you for your reply. Now i have injected the dbcontext in the constructor and Now it work.
> Best wishes.
> Simone

I am also facing the same issue please let me know in which constructor you have defined.

**Comment by mucciols** [comment]
In the constructor of the object you use it

Il mer 25 ago 2021, 10:07 Shriyanshmit ***@***.***> ha
scritto:

**Comment by asante07** [comment]
Please I am also having a similar issue with connection strings are only supported when using 'IConfiguration' and service provider.  What is wrong with my code.

PM> Scaffold-DbContext "Name=ConnectionStrings:DESKTOP-8C6F6G4\\SQLEXPRESS" Microsoft.EntityFrameworkCore.SqlServer
Scaffold-DbContext "Name=ConnectionStrings:DESKTOP-8C6F6G4\\SQLEXPRESS" Microsoft.EntityFrameworkCore.SqlServer
.......
A named connection string was used, but the name 'ConnectionStrings:DESKTOP-8C6F6G4\\SQLEXPRESS' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.

Please what am I doing wrong in this syntax

using VS 2022, Sql Server v18.12.1

![Connections](https://user-images.githubusercontent.com/108937903/180791110-707a2ae6-8903-44de-a12d-7c332493c015.PNG)

**Comment by ErikEJ** [comment]
The name of your connection string is: `DBConnection` !

**Comment by ErikEJ** [comment]
@asante07 that error means you actually connect to the database Server. Suggest you create a issue with proper information about your environment.
