### ISSUE TITLE
Support forum for EF Core

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#13738]
Is there any support forum for EF Core where we can ask questions?

Thanks

**Comment by pantonis** [comment]
@cincuranet stackoverflow they dont accept general questions only questions about stuff that don't work

**Comment by cincuranet** [comment]
Well defined question of such type is accepted on SO. I don't see
problem with that.

**Comment by Eilon** [comment]
"How" and "why" questions can certainly be on-topic on StackOverflow. Here's their help page: https://stackoverflow.com/help/dont-ask

> Some subjective questions are allowed, but “subjective” does not mean “anything goes”. All subjective questions are expected to be constructive. What does that mean? Constructive subjective questions:
>
> * inspire answers that explain “why” and “how”
> * tend to have long, not short, answers
> * have a constructive, fair, and impartial tone
> * invite sharing experiences over opinions
> * insist that opinion be backed up with facts and references
> * are more than just mindless social fun

The issue trackers on GitHub are mostly about filing bugs and logging feature suggestions. For paid support, you can start at https://support.microsoft.com/

**Comment by ajcvickers** [comment]
@pantonis The EF team will often try to answer questions that are posted here. However, if the question is complex and or ambiguous then that may not be feasible. But ask a reasonable question and we'll try to give a reasonable answer.
