### ISSUE TITLE
Issue EF Core and Kestrel

### ISSUE THREAD

**Issue by armanpetrosyan23** [dotnet/efcore#13759]
When I run the app on Kestrel, and in Startup Configure method there is a call to the datebase migration or EnsureCreated(), the app runs but the following exception is being displayed:

![capture](https://user-images.githubusercontent.com/35919382/47496896-51c79480-d869-11e8-90d0-232957eb7b24.PNG)

**Comment by ajcvickers** [comment]
@armanpetrosyan23 Please show your Program and Startup classes.

**Comment by armanpetrosyan23** [comment]
Please see my GitHub link -> [https://github.com/armanpetrosyan23/Test_Seed.git](url)

**Comment by armanpetrosyan23** [comment]
@ajcvickers
Please go a little into detail concerned to your last thought. Why everything goes fine when we run the app on IIS?

**Comment by ajcvickers** [comment]
@armanpetrosyan23 That I don't know; I would suggest you follow up on https://github.com/aspnet/AspNetCore
