### ISSUE TITLE
System assemblies in output folder targeting .NET Framework 4.7.2

### ISSUE THREAD

**Issue by JojoEffect** [dotnet/efcore#13755]
Hi all,

maybe I missunderstood some things or I just did not enough investigation, but according to [this documentation](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/514195-Targeting%20.NET%20Framework%204.7.1%20copies%20extra%20files%20to%20your%20bin%20directory.md) there should be no System.*.dll assemblies in my bin outputfolder when targeting .NET Framework 4.7.2 in combination with .NET Standard 2.0 and/or .NET Core 2.1 projects/assemblies. (That's the way I understand it.)

If I'm wrong on that, skip the sample and please just point me to the according docs.

My case:

`.NET Framework 4.7.2 project -> .NET Core 2.1 EF Core project`

(**EDIT**: the `.NET Core 2.1 EF Core project` is a  multitarget project to netcoreapp2.1 and netstandard2.0)

I need to build an installer and have to deploy all dependencies that are not covered by the .NET Framework.

I made a [small sample ](https://github.com/JojoEffect/SystemDLLinOutputFolder) to reproduce the behavior I'm talking about.

If I add `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` to my .NET Framework 4.7.2 project, then additionally to the expected `Microsoft.EntityFrameworkCore.Sqlite` NuGet package references
these `System.*` assemblies are added to my output folder:

```
System.Buffers.dll
System.Collections.Immutable.dll
System.ComponentModel.Annotations.dll
System.Diagnostics.DiagnosticSource.dll
System.Interactive.Async.dll
System.Memory.dll
System.Numerics.Vectors.dll
System.Runtime.CompilerServices.Unsafe.dll
```

Is this correct and as expected?
If yes, why is this and where can I find docs on that?

EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite)
Operating system: Windows 10 15063.1324 (1703)
IDE: Visual Studio 2017 15.8.7

Thank you in advance for your effort!

**Comment by JojoEffect** [comment]
I did some further investigation and found, that at least

```
System.Buffers.dll
System.Collections.Immutable.dll
System.Diagnostics.DiagnosticSource.dll
System.Memory.dll
```

are **only** available in .NET Framework Core. So it seems like this should be in the output when targeting .NET Framework 4.7.2.

But for 
```
System.ComponentModel.Annotations.dll
System.Interactive.Async.dll
```
I couldn't find any references [here](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel?view=netframework-4.7.2).

**Comment by ajcvickers** [comment]
@JojoEffect I believe that the answer to your question is that some of the dependencies of EF target lower than netstandard 2.0, which causes additional packages to be pulled in. However, I don't fully understand how all this works. I would suggest you follow up with the [NuGet team](https://github.com/NuGet/Home) or [CoreFx team](https://github.com/dotnet/corefx) for further guidance.
