### ISSUE TITLE
Allow plugins to specify themselves while scaffolding

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#13788]
Plugins (e.g. NetTopologySuite) [can already participate in scaffolding](https://github.com/aspnet/EntityFrameworkCore/blob/b8f7715b5903bdef3ff27ba552fd8c55ee387c4b/src/EFCore.Sqlite.NTS/Design/Internal/SqliteNetTopologySuiteDesignTimeServices.cs), generating a model with CLR types based on plugin-provided mappings.

However, the scaffolded `OnConfiguring()` method currently does not contain a `Use*()` method to use the plugin (e.g. `UseNetTopologySuite()`), so the scaffolded model is unusable and the user must add it by hand.

We could extend `IProviderConfigurationCodeGenerator` to generate the appropriate code to include plugins. Unless I'm mistaken this will automatically all plugins which are referenced at scaffold-time regardless of whether they were actually needed during scaffolding (this doesn't seem like a big problem).

**Comment by bricelam** [comment]
Dupe of #13764

**Comment by roji** [comment]
Oops missed that...
