### ISSUE TITLE
Disable automatic creation of FK indices

### ISSUE THREAD

**Issue by artemvalmus** [dotnet/efcore#13793]
Can I disable automatic creation of indices on FKs in migrations? In the following console application I do not explicitly declare an index using HasIndex method, but it's added in the migration anyway.

```c#
namespace Test
{
    public class Foo
    {
        public int Id { get; set; }
    }

    public class Bar
    {
        public int Id { get; set; }

        public int FooId { get; set; }

        public Foo Foo { get; set; }
    }

    public class Context : DbContext
    {
        public Context()
        {
            Database.Migrate();
        }

        public DbSet<Foo> Foos { get; set; }

        public DbSet<Bar> Bars { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "Server=(localdb)\\MSSQLLocalDB;Database=Test;Trusted_Connection=True");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
```

EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment]
@artemvalmus It would be interesting to know why you don't want the indexes.

**Comment by artemvalmus** [comment]
@ajcvickers Just because I wanted to control myself when to create indices according to my schema and data itself. Moreover, could you explain then what the purpose of HasIndex (talking about one-column indices) is if no matter I use it or not, the index is created anyway?

**Comment by ajcvickers** [comment]
@artemvalmus Thanks for the additional information. Issue #7605 is tracking adding an API to remove indexes.
