### ISSUE TITLE
EF does not respect [Required(AllowEmptyStrings = false)] attribute in regard to empty strings

### ISSUE THREAD

**Issue by maxiptah** [dotnet/efcore#13806]
I have a model (Code Fist) where name is marked with `[Required(AllowEmptyStrings = false)]` attribute. 
In model snapshot I see that following is generated: b.Property<string>("Name").IsRequired().

I expect that if I assign an empty string ("") to this proberty that this won't be saved to the database and raise a validation exception. This is however not the case, the field is persisted into the DB.

Does EF respect DataAnnotations and actually validates the model before pushing to DB or it relies purely on DB validation?

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
@maxiptah EF Core does not do this kind of validation. See #3322
