### ISSUE TITLE
Scaffold-Dbcontext ignoring -Tables array

### ISSUE THREAD

**Issue by cnicho** [dotnet/efcore#13821]
Scaffold-Dbcontext is ignoring the -Tables array and processes all tables in the database

### Steps to reproduce
Example command:
Scaffold-DbContext -Connection "Server=(localdb)\LocalDbV14;Database=MYDB;Trusted_Connection=True;" -Provider Microsoft.EntityFrameworkCore.SqlServer -Schemas dbo -Tables "TABLE1" -Context MyDbContext -Verbose -Force

### Further technical details
EF Core version: 2.1.4
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
LocalDb version: 14
LocalDb collation: SQL_Latin1_General_CP1_CI_AS (CP1252) by default
Operating system:  Windows 10 1803 plus updates
IDE: Visual Studio 2017 15.8.8

**Comment by smitpatel** [comment]
>  -Schemas dbo -Tables "TABLE1"

Is interpreted as all the tables in schema `dbo` or `TABLE1` (which can be in any schema)

What is the table which is being scaffolded for you?

**Comment by ajcvickers** [comment]
@cnicho To follow up a bit more, you can scaffold only the table using something like:

```
Scaffold-DbContext -Connection "..." -Provider Microsoft.EntityFrameworkCore.SqlServer -Tables "dbo.TABLE1" -Context MyDbContext -Verbose -Force
```

**Comment by cnicho** [comment]
I have duplicate table names across multiple schemas. I understaood -Schemas to be used to indicate which schema and tables to be those tables I want scaffolded in that schema. I currently get all tables for schema dbo; not just the table named.
I don't understand why you have closed it.
