### ISSUE TITLE
Microsoft.Data.Sqlite: Consider being strict about requiring disposal of DbCommands

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#13836]
This would be a breaking change, but would have the advantage of cleaning up code like that in aspnet/Microsoft.Data.Sqlite#506.

**Comment by ajcvickers** [comment]
Consider guidance for other ADO.NET providers in this area. /cc @roji @divega

**Comment by bricelam** [comment]
The architecture I have in mind for #14044 will remove the need to dispose SqliteCommand objects. It will also allow them to be disposed while their SqliteDataReader is open.
