### ISSUE TITLE
Classes using ModelBuilder and associated classes cannot be properly unit tested without tight coupling

### ISSUE THREAD

**Issue by davija** [dotnet/efcore#13868]
When working with code that deals with ModelBuilder, PropertyBuilder, etc. it would be nice to be able to test that code with proper unit tests.

However, it appears that ModelBuilder and it's associated classes are not built to allow for mocks.  

For example, if you are calling ```ModelBuilder.Entity<MyType>(. . .)``` one might expect that to return an IEntityTypeBuilder.  Conversely on EntityTypeBuilder, one would expect to find calls to ```EntityTypeBuilder.Property("MyPropertyName")``` to return an IPropertyBuilder.  

Alas, this is not the case... These method calls return concrete implementations of those classes instead.

If you look further, you will see that many of these builders have constructors with parameters (usually with a significant number of not-null attributes) that make trying to mock these out become a dizzying operation in traversing the stack of inter-connected classes.

This tight coupling and not using proper interfaces violates SOLID coding principles and makes it difficult to work with .

**Comment by ajcvickers** [comment]
@davija Can you show examples of what kinds of tests you would like to write?

**Comment by davija** [comment]
Here is an example of what I would like to be able to do for a test:
`        public void TestRegisterRowVersionEntities()
        {
            var mockModelBuilder = new Mock<IModelBuilder>();
            var mockEntityTypeBuilder = new Mock<IEntityTypeBuilder>();
            var mockPropertyBuilder = new Mock<IPropertyBuilder>();
            var res = mockEntityTypeBuilder.Object;

            mockEntityTypeBuilder.Setup(etb => etb.Property("RowVersion")).Returns(mockPropertyBuilder.Object);
            mockModelBuilder.Setup(mb => mb.Entity(It.IsAny<Type>())).Returns(mockEntityTypeBuilder.Object);

            ModelBuilderExtensions.RegisterRowVersionEntities(mockModelBuilder.Object);

            mockModelBuilder.Verify(mb => mb.Entity(typeof(TestVersionedModel)), Times.Once);
            mockEntityTypeBuilder.Verify(etb => etb.Property("RowVersion"), Times.AtLeastOnce);
            mockPropertyBuilder.Verify(pb => pb.IsRowVersion(), Times.AtLeastOnce);
        }
`

This would allow me to very easily be able to create mocks of these objects and do a simple test...

However, here is what I had to do to get this working (LOTS of extra work and digging through dotnet code to figure out what is needed), notice the very involved setup required in the Setup method:
`
        private Mock<ModelBuilder> MockModelBuilder { get; set; }

        private Mock<EntityTypeBuilder> MockEntityTypeBuilder { get; set; }

        private Mock<PropertyBuilder> MockPropertyBuilder { get; set; }

        [TestInitialize]
        public void Setup()
        {
            MockModelBuilder = new Mock<ModelBuilder>(new ConventionSet());

            // All this GOOP is here because of ModelBuilder is tightly coupled to concrete classes that
            // need to be instantiated just so it can be mocked....
            var model = new Model();
            var entityType = new EntityType("a", model, ConfigurationSource.Explicit);
            var property = new Mock<Property>("RowVersion", typeof(byte[]), null, null, entityType, ConfigurationSource.Explicit, null);
            var mnternalModelBuilder = new InternalModelBuilder(model);
            var internalEntityTypeBuilder = new InternalEntityTypeBuilder(entityType, mnternalModelBuilder);
            var internalPropertyBuilder = new InternalPropertyBuilder(property.Object, mnternalModelBuilder);

            MockEntityTypeBuilder = new Mock<EntityTypeBuilder>(internalEntityTypeBuilder);
            MockPropertyBuilder = new Mock<PropertyBuilder>(internalPropertyBuilder);
        }

        [TestMethod]
        public void TestRegisterRowVersionEntities()
        {
            var res = MockEntityTypeBuilder.Object;
            MockEntityTypeBuilder.Setup(etb => etb.Property("RowVersion")).Returns(MockPropertyBuilder.Object);
            MockModelBuilder.Setup(mb => mb.Entity(It.IsAny<Type>())).Returns(MockEntityTypeBuilder.Object);

            ModelBuilderExtensions.RegisterRowVersionEntities(MockModelBuilder.Object);

            MockModelBuilder.Verify(mb => mb.Entity(typeof(TestVersionedModel)), Times.Once);
            MockEntityTypeBuilder.Verify(etb => etb.Property("RowVersion"), Times.AtLeastOnce);
            MockPropertyBuilder.Verify(pb => pb.IsRowVersion(), Times.AtLeastOnce);
        }
`

**Comment by ajcvickers** [comment]
@davija Thanks for the additional info. Can you explain a bit more about what tests like that are designed to achieve? What kind of bugs/regression/other things will these tests catch?

**Comment by davija** [comment]
This is just a standard unit test on code that I was writing to test that the behavior matches requirements.  

The purpose of the test is to ensure that the code (for an extension to the ModelBuilder class) under test actually properly registered content with the model builder as required.

**Comment by ajcvickers** [comment]
@davija Thanks for all the clarification. There are many issues associated with changing these builders to return interfaces, not least the breaking changes trying to evolve them going forward. If there is a compelling reason why such a change would be very beneficial, then we would consider what could be done. However, we feel that the kind of testing you are proposing is of very little real value, and hence on balance the patterns we are using are probably appropriate. (We see more and more people not writing tests like this, and indeed we pretty much stopped doing it in our code too.)

You might consider instead testing that the IModel has been configured as appropriate. That is, test that your code actually did what you think it did to the model. This might not strictly be "unit testing" but we have found it to be much better at detecting bugs/regressions since it can catch where a call to the model builder doesn't do what you think it does. Just testing that the method was called will never fail for this.

**Comment by davija** [comment]
@ajcvickers I would have to disagree with stating that this kind of unit testing is not valid.  

Essentially what we are doing is placing attributes on specific classes that need to do row versioning and then use reflection at creation time to scan and register those as such (which is what this extension method does).

This kind of testing is critical to ensuring that this code is written properly and functional.

This is not the only area of the dotnet core framework that fails to follow SOLID design principles and many of them should be addressed.  Proper unit testing in dotnet core is VERY difficult since there are so many concrete classes used instead of interfaces as proper OOP would dictate.  This is only made more difficult in the fact that Fakes is no-longer supported in dotnet core.

If Microsoft really wants to promote good frameworks and ensure they are used to generate quality code, they REALLY need to re-evaluate using SOLID principles in libraries / frameworks they produce.   With the introduction of dotnet core, there were a lot of good improvements in the right direction with much of the framework, however some key areas made the same mistakes all over again.
