### ISSUE TITLE
Owned collections: Attributes-based configuration experience is incomplete and may be hard to understand

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#13874]
According to @AndriySvyryd the following model, OrderItem won't have a composite identifying key. I understand that this is because the use of KeyAttribute will override the key member we would have created in shadow state. 

This is consistent with the effect of KeyAttribute in other places, but it is hard to tell if customers will expect this to happen. 

Also, if I want the composite identifying key, there is no way to do this today just using attributes. 

``` csharp
public class Order
{
    public int OrderId { get; set; }
    public List<OrderItem> Items { get; set; }
}

[Owned]
public class OrderItem
{
    [Key] 
    public int OrderId {get ;set;} 
….
}

**Comment by ajcvickers** [comment]
Triage: discuss this again with @AndriySvyryd. See also comments on #13875
