### ISSUE TITLE
Warning when Synchronous api used?

### ISSUE THREAD

**Issue by clement911** [dotnet/efcore#13877]
Is it possible to issue an exception whenever a sync API is used (e.g. ToArray() instead of ToArrayAsync), similar to QueryClientEvaluationWarning?

Ideally this could be turned off on a per query basis in case there is a good reason to use a sync API (a bit like the c# #pragma warning disable)

**Comment by ajcvickers** [comment]
@clement911 It's possible that we could block synchronous execution of the query, which seems to be the gist of what you are asking for. However, this is the first feedback we have seen for this, and there are many scenarios where using synchronous APIs is desirable--for example, when using SQLite which doesn't have a truly asynchronous implementation at the database level. (In such cases using the async APIs just adds overhead but with no value.)

We're not planning to implement this, but as always we could reconsider given good feedback.

**Comment by clement911** [comment]
This is not what I'm asking.
I just would like to have some sort of events I can hook up to when a sync API is used.
So that we can log it and then remove sync calls that were accidentally introduced in the code base.

**Comment by ajcvickers** [comment]
@clement911 Something like this? https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.relationaleventid.commandexecuting?view=efcore-2.1

**Comment by clement911** [comment]
Yes, that looks promising, I see there is an IsAsync property.
But, how do I hook up to that event? Any sample?

**Comment by ajcvickers** [comment]
@clement911 https://github.com/aspnet/EntityFramework.Docs/issues/583 links to a couple of issues with examples.

**Comment by clement911** [comment]
Interesting API..
I think that will do thanks.
