### ISSUE TITLE
One-To-Many relation unexpected behavior when not defining foreign key

### ISSUE THREAD

**Issue by hebagomaah** [dotnet/efcore#13884]
I am trying to define a one-to-many relationship as follows:

```C#
public class BloggingContext : DbContext
    {
        public BloggingContext(DbContextOptions<BloggingContext> options)
            : base(options)
        { }

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Post>().HasOne(b => b.Blog).WithMany().IsRequired().OnDelete(DeleteBehavior.Cascade);
            base.OnModelCreating(modelBuilder);
        }
    }

    [Table("Blogs")]
    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }

    [Table("Posts")]
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public Blog Blog { get; set; }
    }
```
The EF defined the relation as required by adding a new column **BlogId** as a foreign key

but when trying to create the Post below:

```json
{
  "postId": 0,
  "title": "Post1",
  "content": "First post",
  "blog": {
    "blogId": 1
   }
}
```
and I have previously created a Blog with Id = 1, the exception below is thrown

> SqlException: Cannot insert explicit value for identity column in table 'Blogs' when IDENTITY_INSERT is set to OFF.

which mean that EF tries to create the referenced blog.

**Comment by ajcvickers** [comment]
@hebagomaah Reading between the lines, I'm guessing that you are doing the equivalent of this:
```C#
var blog = new Blog { BlogId = 1};
var post = new Post { Blog = blog };
context.Add(post);
context.SaveChanges();
```
In this case both Blog and Post are treated as new entity instances that need to be inserted. Instead you can use Attach such that the key being set will indicate that the Blog actually already exists:
```C#
var blog = new Blog { BlogId = 1};
var post = new Post { Blog = blog };
context.Attach(post);
context.SaveChanges();
```
See also #13575, https://docs.microsoft.com/en-us/ef/core/saving/related-data, and https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities
