### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.  Parameter name: source   in production Mode

### ISSUE THREAD

**Issue by osmanrahimi** [dotnet/efcore#13882]
I am using EF Core  v 1.2, In my project, I have a method when I debug it or when I run it in local machine It works fine and return data, but when I publish the project in production mode it returns an exception.

Exactly this code without any changes work properly .

Note : the Code executed form an background Service .

My query is  : 
```
 public IEnumerable<OrderItemEntity> GetItemsByCustomerServiceId(int orderId, int customerServiceId)
            {
                var query = _context.OrderItems
                    .Include(ff => ff.ChildrenOrderItems)
                    .Include(ff => ff.ServiceOrderItem).ThenInclude(ff => ff.CustomerService).ThenInclude(ff => ff.Package)
                    .Include(ff => ff.InvoiceItems).ThenInclude(ff => ff.InvoiceItem).ThenInclude(ff => ff.InvoiceItemDiscountLogs)
                    .Include(ff => ff.InvoiceItems).ThenInclude(ff => ff.InvoiceItem).ThenInclude(ff => ff.InvoiceItemTaxLogs)
                    .Include(ff => ff.ProductPackageOrderItem).ThenInclude(ff => ff.ProductPackage).ThenInclude(ff => ff.Product)
                    .Where(dd =>
                        !dd.IsDeleted
                        && dd.Type == OrderItemType.CustomerService
                        && !dd.ServiceOrderItem.IsDeleted
                        && !dd.ServiceOrderItem.CustomerService.IsDeleted
                        && dd.ServiceOrderItem.CustomerService.Id == customerServiceId && dd.OrderId == orderId);

                return query.ToList();
            }
```
Exception is  : 
`
System.ArgumentNullException: Value cannot be null.  Parameter name: source     
at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)    
 at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()     
 at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()  
 at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()    
 at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()     
 at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)   
`

**Comment by ajcvickers** [comment]
@osmanrahimi Can you try updating to a newer version of EF Core? 2.1 is the latest stable, 2.2 will be out by the end of the year and 2.2 preview 3 is available now.

**Comment by osmanrahimi** [comment]
@ajcvickers is it a bug?

**Comment by ajcvickers** [comment]
@osmanrahimi Yes, likely. However, it's extremely unlikely we will patch it in version 1.1.x, so the first course of action is to upgrade to 2.1 or above. If the issue still persists there, then we'll need a runnable project/solution or complete code listing that reproduces the issue so that we can fully investigate.

**Comment by osmanrahimi** [comment]
Unfortunately, I am not unable to upgrade it. 
But what is strange for me, is that when I call that code from swagger it works fine but when it calls from background service it throws an exception.  

To solve the problem, I chnaged the code to this until I upgrade it.
  ```
 var result = DataContext.OrderItems.Include(ff => ff.ChildrenOrderItems)
                .Where(dd => !dd.IsDeleted
                    && dd.Type == OrderItemType.CustomerService
                    && !dd.ServiceOrderItem.IsDeleted
                    && !dd.ServiceOrderItem.CustomerService.IsDeleted
                    && dd.ServiceOrderItem.CustomerService.Id == customerServiceId && dd.OrderId == orderId).ToList();
           
            foreach (var item in result)
            {
                item.ServiceOrderItem = DataContext.ServiceOrderItems.Include(ff => ff.CustomerService).ThenInclude(ff => ff.Package).FirstOrDefault(r => r.OrderItemId == item.Id);
                item.InvoiceItems = DataContext.OrderItemInvoiceItems.Where(r => r.OrderItemId == item.Id).Include(ff => ff.InvoiceItem).ThenInclude(ff => ff.InvoiceItemDiscountLogs).Include(ff => ff.InvoiceItem).ThenInclude(ff => ff.InvoiceItemTaxLogs).ToList();
                item.ProductPackageOrderItem = DataContext.ProductPackageOrderItems.FirstOrDefault(r => r.OrderItemId == item.Id);
            }
```
