### ISSUE TITLE
Adding AddRange to dictionary cause a update on FK

### ISSUE THREAD

**Issue by pgroene** [dotnet/efcore#13886]
When adding child objects to a dictionary collection from the child type the child objects are updated to the first parent that what added to the dictionary key bucket.

### Steps to reproduce

```c#
public class Parent{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Code1 { get; set; }
    public string Code2 { get; set; }
    public List<Child> Childs{ get; private set; } = new List<Child>();
}
public class Child{
    public Guid Id { get; set; } = Guid.NewGuid();
    [ForeignKey("ParentFK")]
    public Guid ParentId { get; set; }
}

//Code to use parent / childs

var dict = new Dictionary<string, List<Child>>();
foreach (var code in new [] {"C0","C1","C2","C3","C4","C5"})
{
         var items = (await dbcontext.Reqests
                //    .AsNoTracking()
                    .Include(r => r.Childs)
                    .Where(r => r.Code1== code)
                    .ToListAsync().ConfigureAwait(false))
                    .ToDictionary<Parent, string>(r => r.Code2);

          foreach (var key in items.Keys)
                {
                    if (dict.ContainsKey(key))
                        dict.[key].AddRange(items[key].Childs); //Here are fks changed 
                    else
                    {
                        dict.Add(key, items[key].Childs);
                    }
                }
}
dbcontext.SaveChanges();
```

When the SaveChanges call is made, the fk is updated in the database. The dict.[key].AddRange(items[key].Childs);  does trigger the changes to be tracked. Child objects are updated to belong to the 'first parent of the dictionary bucked'.

I would have expected no changes are tracked.

The .AsNoTracking() will prevent tracking and the update.

### Further technical details
EF Core version: (found in project.csproj or packages.config)

 <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

Database Provider: 
Microsoft.EntityFrameworkCore.SqlServer

Operating system: 
Windows / Linux / Docker container on linux

**Comment by ajcvickers** [comment]
@pgroene This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by pgroene** [comment]
You can find a sample project here:
https://github.com/pgroene/ef-dictionary/

**Comment by ajcvickers** [comment]
@pgroene I'm still not following what is unexpected executing the code. Many `Child` objects are added to the collection pointed to by the `Parent.Childs` navigation property. These are then persisted to the database when `SaveChanges` is called. What am I missing here?

**Comment by pgroene** [comment]
The following line moves all child object from a parent to the first parent in that range:

dict[key].AddRange(items[key].Childs);

The save changes does persist it idd to the database (in this case the memory database). I would not expect the AddRange on a dictionary to change the parent elements of the added child objects to the first parent added on key.

**Comment by ajcvickers** [comment]
@pgroene It's not doing `AddRange` on a dictionary. It's doing `AddRange` on the list contained in the dictionary, and that list is the same instance that is being tracked as a navigation from `Parent`. The reference to the Parent gets fixed up to be consistent with the parent that now references the children.

**Comment by pgroene** [comment]
Yeah, that idd the case, thanks for sharing that insight! It seems that the code construction was very poor chosen.
