### ISSUE TITLE
EF Core 2.1 SQL syntax error when passing table name as parameter

### ISSUE THREAD

**Issue by aoiste** [dotnet/efcore#13907]
For some reason, I need to excute sql like this:

```c#
context.Database.ExecuteSqlCommand($"UPDATE {tableName} SET COLUMN = {value} WHERE {pk} = {pkValue}");
```
The code caused an SQL syntax error because the table name was single quoted

### Further technical details
EF Core version: 2.1.4
Database Provider: MySql.Data.EntityFrameworkCore
Operating system: Windows 10
IDE: Visual Studio 2017 15.9 Preview 5.0

**Comment by ajcvickers** [comment]
@ztytotoro That code is telling EF to parameterize more than just values. This isn't supported in SQL. Instead use string concatenation for the things that cannot be parameters in SQL, but of course being very careful to avoid potential SQL injection attacks.
