### ISSUE TITLE
HasConversion is ignored

### ISSUE THREAD

**Issue by witua** [dotnet/efcore#13910]
There is a float column in DB which stores date/time in OADate format. It's represented in model as a DateTime property with `HasConversion(d => d.ToOADate(), oa => DateTime.FromOADate(oa))`. When comparing the property value with DateTime.Now in query expression, it's translated to GETDATE() and no conversion is made, which leads to incorrect comparison results with no error received.

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017

**Comment by Tarig0** [comment]
What happens if you assign DateTime.Now to a variable then use that variable inside the query?

**Comment by witua** [comment]
It works as expected in this case.

**Comment by smitpatel** [comment]
Related #10434

**Comment by smitpatel** [comment]
@witua - Can you also post the full query?
