### ISSUE TITLE
Unique constraint only being created for one of two self referencing FKs

### ISSUE THREAD

**Issue by MichaelSearson** [dotnet/efcore#13933]
Originally I encountered an issue with self referencing FK values being replaced with NULLs when calling the `SaveChanges()` method. This was resolved as part of [this StackOverflow answer](https://stackoverflow.com/questions/53240371/entity-framework-core-self-referencing-fk-column-value-being-replaced-with-nul), but it raised a question about whether there was a bug in EF itself as it seemed to be treating the `AddedByAccountId` and `ModifiedByAccountId` properties in my Account entity as a single one-to-one relationship.

### Steps to reproduce
[This repository](https://github.com/MichaelSearson/entity-framework-issue-example) demonstrates the original issue I mentioned above, but at its core all you need to do is have an entity with multiple self referencing keys (`AddedByAccountId` and `ModifiedByAccountId`) like this:

```c#
public class Account
{
    [Key]
    public Guid AccountId { get; set; }

    #region Audit

    public Guid? AddedByAccountId { get; set; }

    public DateTime AddedOnUtc { get; set; }

    public Guid? ModifiedByAccountId { get; set; }

    public DateTime ModifiedOnUtc { get; set; }

    #endregion Audit

    #region Navigation Properties

    [ForeignKey(nameof(AddedByAccountId))]
    public virtual Account AddedByAccount { get; set; }

    [ForeignKey(nameof(ModifiedByAccountId))]
    public virtual Account ModifiedByAccount { get; set; }

    #endregion Navigation Properties
}
```
You can then create a derived DbContext implementation like this:
```c#
public class EntityFrameworkDbContext : DbContext
{
    public EntityFrameworkDbContext(DbContextOptions<EntityFrameworkDbContext> options)
        : base(options)
    {
    }

    public DbSet<Account> Accounts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            // This line is necessary for the AddedByAccountId property - but not 
            // the ModifiedByAccountId property. 
            entity.HasIndex(e => e.AddedByAccountId).IsUnique(false);
        });
    }
}
```
If I don't include the `IsUnique(false)` line shown in the snippet above then the migration generated will try to apply a unique constraint to the `AddedByAccountId` column - but not the `ModifiedByAccountId` column. 

```c#
// Migration created without the line of code shown in the previous snippet:
migrationBuilder.CreateIndex(
    name: "IX_Accounts_AddedByAccountId",
    table: "Accounts",
    column: "AddedByAccountId",
    unique: true,
    filter: "[AddedByAccountId] IS NOT NULL");

migrationBuilder.CreateIndex(
    name: "IX_Accounts_ModifiedByAccountId",
    table: "Accounts",
    column: "ModifiedByAccountId");
```

```c#
// Migration created with the line of code:
migrationBuilder.CreateIndex(
    name: "IX_Accounts_AddedByAccountId",
    table: "Accounts",
    column: "AddedByAccountId");

migrationBuilder.CreateIndex(
    name: "IX_Accounts_ModifiedByAccountId",
    table: "Accounts",
    column: "ModifiedByAccountId");
```

Can someone confirm if this is intended behaviour? Thank you!

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.8

**Comment by ajcvickers** [comment]
@MichaelSearson By convention EF will create a one-to-many relationships for a single reference navigation properties with no inverse. This has been debated a lot, but pragmatically seems to work well. It's simple to force it to create one-to-one relationships instead, in which case both FKs will be unique:

```C#
modelBuilder.Entity<Account>(entity =>
{
    entity.HasOne(e => e.AddedByAccount).WithOne();
    entity.HasOne(e => e.ModifiedByAccount).WithOne();
});
```
See [modeling relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships) for more info.
