### ISSUE TITLE
Inheritance: Convention based discriminator when using IEntityTypeConfiguration

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#13938]
Currently a convention based discriminator is only used on inheriting entity types when they are configured as a DbSet in the DbContext class:
``` c#
    public DbSet<MobileContract> MobileContracts { get; set; }
    public DbSet<BroadbandContract> BroadbandContracts { get; set; }
```

I my code I always use `IEntityTypeConfiguration` so my entity types are discovered dynamically.
AFAIK it's not possible to use the convention based discriminator in this scenario.

What I would like to do is this:
``` c#
public abstract class Contract : IEntityTypeConfiguration<Contract>
{
    public int ContractId { get; set; }
    public DateTime StartDate { get; set; }
    public int Months { get; set;}
    public decimal Charge { get; set; }

    public virtual void Configure(EntityTypeBuilder<Contract> builder)
    {
        builder.HasDiscriminator()
            .HasValue<MobileContract>()
            .HasValue<BroadbandContract>();
    }
}

public class MobileContract : Contract
{
    public string MobileNumber { get; set; }
}

public class BroadbandContract : Contract
{
    public int DownloadSpeed { get; set; }
}
```

This way I don't have to specifiy any details about what discriminator is used. EF simply uses the default (convention based) discriminator.

**Comment by ajcvickers** [comment]
@nphmuller Using `IEntityTypeConfiguration` or not should have no bearing on this. Can you post a runnable project/solution or complete code listing that demonstrates the issue you are seeing?

**Comment by nphmuller** [comment]
@ajcvickers I jumped to conclusions. `builder.HasBaseType<>()` solves my case.
Although I'm basically describing the opposite: `builder.HasInheritedType<>()` on the base class.

Anyway, since `HasBaseType()` works for us, I'm closing this issue.
