### ISSUE TITLE
Suggestion: There needs to be a way to suppress 3rd party tables, like AutoHistory from generated migrations.

### ISSUE THREAD

**Issue by BrianMinister** [dotnet/efcore#13932]
Because I have middleware that consumes from several contexts that are formed by other teams, each context wants to re-create autohistory, and other tables that are common across originating projects.

In the context that I am generating a migration for, it would be awesome if I could put in 
`modelBuilder.Entity<AutoHistory>().MigrationIgnore();`
or
`modelBuilder.Entity<UserPickup>().MigrationIgnore();`

### Steps to reproduce
Build a project with multiple Contexts that are both using AutoHistory.

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, SQLlite, Custom
Operating system: Win 10 Pro. Latest public.
IDE: Visual Studio 2017 15.8.9

**Comment by ajcvickers** [comment]
Duplicate of #2725

**Comment by alexsandro-xpt** [comment]
It is useful for mixed legacy database with migration without break legacy tables making migration genered table working together with fixed tables.
