### ISSUE TITLE
Read Only DbContext to Use In CQRS Architecture

### ISSUE THREAD

**Issue by farhad-taran** [dotnet/efcore#13934]
I am just wondering if there is a default implementation for a readOnly DbContext.

I know that a readOnly connection string can be used or that the following code does that, but I want to make sure that Tracking behavior can not be re-enabled and stays disabled for the life time of the context as I want to have two conetexts concurrently in the web request scope, one for writing and one for reading.

        public BloggingContext()
        {
            this.ChangeTracker.AutoDetectChangesEnabled = false;
            this.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
        }

so I am wondering if there may be a mechanism that allows the change tracker to be replaced or is it possible to make it so that if AsTracking is called on a item then an exception is thrown?

**Comment by ajcvickers** [comment]
@ftaran We discussed this as a team and we don't think there is enough value in explicitly configuring a context as read-only such that it can not be changed. If you only ever want to do no-tracking queries, then that can be configured like you show or in AddDbContext, If you want to be sure that nobody can modify and save entities from the context, then override SaveChanges to throw. (Also note that the setting for AutoDetectChangesEnabled will have no effect if the context only does no-tracking queries.)

**Comment by roji** [comment]
@anreton you can set up a [command interceptor](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#database-interception), and check the [CommandSource](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.commandcorrelatedeventdata.commandsource?view=efcore-9.0#microsoft-entityframeworkcore-diagnostics-commandcorrelatedeventdata-commandsource) property on the arguments to detect ExecuteUpdate and Delete.
