### ISSUE TITLE
Query object with list of objects

### ISSUE THREAD

**Issue by ashelest** [dotnet/efcore#13946]
Hi. Sorry for may be stupid question, but im done.
Im trying to create query for complex object
I have next query model
`
   public class QueryModel
    {
        public Guid ID { get; set; }
        public IEnumerable<string> Keys { get; set; }
    }
`
Next mapping
`
modelBuilder.Query<QueryModel>()
.ToView("ViewName");
`
I get error
InvalidOperationException: The property; CompanyQuery.Keys; could not be mapped, because it is of type; IEnumerable which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the [NotMapped] attribute

I feel like i need to configure manually somehow, but i just dont understand how.

**Comment by ajcvickers** [comment]
@ashelest What's the query you would like to execute that would return this model?
