### ISSUE TITLE
Add function to Init Migration

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#13952]
Hello, I want to create an initializing migration to which functions have already been added. It’s inconvenient to manually add to the migration file because during the development phase it is often necessary to initialize the database again and again. To keep for the sake of this a migration file that also changes very often does not make sense. Tell me what solutions there are to insert the sql code (in particular, the function creation code) into the generated migration file.

**Comment by ajcvickers** [comment]
@bricelam to respond.

**Comment by bricelam** [comment]
@terrainkognito2017 It doesn't sound like you're getting much value from using Migrations at this stage of development. Have you considered using using code like this instead?

``` csharp
context.Database.EnsureCreated();
context.Database.ExecuteSqlCommand("CREATE FUNCTION...");
```

If you really want to use migrations, you could start with an empty migration. Comment out any DbSet properties and the OnModelCreating method, add the initial migration. Add your functions to that migration. Finally, uncomment your DbSets and OnModelCreating. This lets you easily your *second* migration (using Remove-Migration, Add-Migration) while keeping the function code around.

**Comment by bricelam** [comment]
Issue #3053 is also about creating a better schema management workflow for the early stages of a project.

**Comment by ajcvickers** [comment]
@terrainkognito2017 As far as we understand your question, there isn't a way to do exactly what you are trying to do, and it's not something we are planning to implement. Given this, @bricelam Is suggesting some other ideas that might solve your originally stated problem in a different way.
