### ISSUE TITLE
PrimitivePropertyAttributeConfigurationConvention Extension equivalent in EF Core 2

### ISSUE THREAD

**Issue by ben-allamx** [dotnet/efcore#13954]
We are migrating from EF 6 to EF Core 2.2

In our Model we use a custom Attribute Extension:  DecimalPrecisionAttribute
This attribute is used by both the UI for validation as well as configured for use in EF 6 in for database creation in OnModelCreating with the following line: 
```c#
 modelBuilder.Conventions.Add(new DecimalPrecisionAttributeConvention());
```
When the database is created with EF 6, the decimal precision and scale are correctly set with values from the custom attribute.

This method gives us a one liner attribute to add to decimal fields in any model that needs the precision and scale dictated in both the UI and the database.

We are looking for a way to do this with EF Core but have not been able to find documentation on how to do so. EF Core does not appear to have a Convention to apply our custom DecimalPrecisionAttributeConvention to.

The only information we have seen is to either add to each and every property in Fluent API or to add another attribute in every model.
```c#
modelBuilder.Entity<Blog>().Property(x => x.MyDecimal).HasColumnType("decimal(14, 2)").IsOptional();
```
or
```c#
[Column(TypeName = "decimal(14,2)")]
public Decimal? MyDecimal { get; set; }
```

Here is an example structure of our current classes.

```c#
[AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
public sealed class DecimalPrecisionAttribute : Attribute
{
    public Byte Precision { get; set; }
    public Byte Scale { get; set; }

    public DecimalPrecisionAttribute(Byte precision, Byte scale)
    {
        Precision = precision;
        Scale = scale;
    }
}
```
```c#
public class DecimalPrecisionAttributeConvention : PrimitivePropertyAttributeConfigurationConvention<DecimalPrecisionAttribute>
{
    public override void Apply(ConventionPrimitivePropertyConfiguration configuration, DecimalPrecisionAttribute attribute)
    {
        if (attribute.Precision < 1 || attribute.Precision > 38)
            throw new InvalidOperationException("Precision must be between 1 and 38.");

        if (attribute.Scale > attribute.Precision)
            throw new InvalidOperationException("Scale must be between 0 and the Precision value.");

        configuration.HasPrecision(attribute.Precision, attribute.Scale);
    }
}
```
```c#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    ...
    modelBuilder.Conventions.Add(new DecimalPrecisionAttributeConvention());
    ...
}
```
```c#
public class Blog
{
    [DecimalPrecision(14, 2)]
    [Display(Name = "My Decimal")]
    public Decimal? MyDecimal { get; set; }
}
```

**Comment by ajcvickers** [comment]
@ben-allamx You're hitting a couple of missing things here. First, the convention framework is currently internal--see #214. We're planning to change this for 3.0, but there's a lot currently in 3.0 so it may get punted.

Also, we're missing support for setting precision and scale in a database agnostic manner--see #11614.

However, there is a reasonable workaround which is to run some code at the end of OnModelCreating (or wherever you configure the model) to bulk-configure all the decimal properties based on the attribute and set the store type there. For example:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>();

    foreach (var decimalProperty in modelBuilder.Model
        .GetEntityTypes()
        .SelectMany(e => e.GetProperties())
        .Where(p => p.PropertyInfo != null
                    && (p.ClrType == typeof(decimal)
                        || p.ClrType == typeof(decimal?))))
    {
        var attribute = (DecimalPrecisionAttribute)decimalProperty.PropertyInfo
            .GetCustomAttributes(typeof(DecimalPrecisionAttribute), true)
            .FirstOrDefault();

        if (attribute != null)
        {
            decimalProperty.Relational().ColumnType = $"decimal({attribute.Precision},{attribute.Scale})";
        }
    }
}
```
You could instead use internal code and write a convention, but this will likely get broken in 3.0 when conventions become public, but I can provide some guidance if you need it.
