### ISSUE TITLE
Consider removing UseRowNumberForPaging

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#13959]
Because it is generally only needed in SQL Server 2008, which is out of support.

If you're reading this and you use UseRowNumberForPaging, then please comment on this issue and let us know why you are using it.

**Comment by BBGONE** [comment]
Because we payed for the standard version of SQL Server 2008. It works perfectly for us. Why to buy a new version?

**Comment by felipepessoto** [comment]
@ajcvickers, I still see some customers using it. The extended support ends in 2019. 

I had to use the rownumber flag recently.

**Comment by duoanfen** [comment]
because we only buy 2008 licence on production environment which many project is already runing on it and working without problem, if we change to 2012 only for this problem, we must by a new licence for 2012 and only for this netcore project. so i think it is not a good plan

**Comment by duoanfen** [comment]
I find a way to solve this error temporary, use a lock on ToList() function, but if we do like this it can not handle many request in the same time,  so it is only a temporary solution to this problem.
code is:
                List<TMenu> rs = null;
                lock (StaticLock.MenuListLock)
                {
                    rs = query.ToList();
                }

**Comment by duoanfen** [comment]
```C#
123123
```

**Comment by BBGONE** [comment]
Yeah, to replace a working database server is not as easy as to replace a web browser with a newer one. Even after a long time it can work inside a virtual machine with an older OS. I can not count how many SQL Servers 2008 are now used, but i think it is a very substantial number. People don't like to throw away money on what they don't need.

**Comment by lxs3626** [comment]
Big steps, easy to pull eggs.

**Comment by duoanfen** [comment]
哈哈哈 楼上的笑死我了，翻译过来就是：步子大了容易扯着淡

**Comment by ajcvickers** [comment]
Thanks for the feedback all.

**Comment by ajcvickers** [comment]
Based on feedback, we're not planning to remove this functionality in the 3.0 release.

**Comment by prochnowc** [comment]
Same here. SQL Server 2008 is still in use for some databases in the company. Thanks for not removing it in 3.0. In our apps we implemented probing the SQL server version on startup and set the flag accordingly.

**Comment by xrkolovos** [comment]
Same here. Our clients still has SQL server 2008. This would force us to go back to ef6

**Comment by duoanfen** [comment]
We already change SQL Servcer to Mysql for DB service, Because our company leader do not agree to pay for money to update to sqlserver 2012, Change to Mysql that we can deploy .netcore project all on Ubuntu or CentOS.  So I think I will never experience this problem in the future, Thanks.

**Comment by BBGONE** [comment]
> 
> 
> We already change SQL Servcer to Mysql for DB service, Because our company leader do not agree to pay for money to update to sqlserver 2012, Change to Mysql that we can deploy .netcore project all on Ubuntu or CentOS. So I think I will never experience this problem in the future, Thanks.
> From Zhongguancun Beijing China

Congratulation. They fixed it in netcore 2.2. We gave it a thought too. But SQL Server has better backup and restore, we have a lot of reports in Reporting Services, and we also use SQL Server Service Broker. Moving it to a new database server looks very tedious.

**Comment by VarunAkula** [comment]
To make the $skip query option of OData to work fine with Microsoft SQL Server 2008 R2, we are using UseRowNumberForPaging

**Comment by xrkolovos** [comment]
Please provide a way for us to add it in our code, we don't want to stuck in .net core 2.2

**Comment by h0730303779** [comment]
UseRowNumberForPaging  efcore 3.1 不能用了吗 震惊 蛋疼

Row-number paging is no longer supported. See https://ak.ms/AA6h122 for more information.
!!!
Please support because our customer database is 2008

**Comment by duoanfen** [comment]
@h0730303779 我们之前用的是netcore2.1，那个时候不能用，现在3版本升级3.0+了具体能不能用不知道啊，我们没升级，改用mysql了

**Comment by h0730303779** [comment]
> @h0730303779 我们之前用的是netcore2.1，那个时候不能用，现在3版本升级3.0+了具体能不能用不知道啊，我们没升级，改用mysql了

不能我也切 mysql了 看见 隔壁issues 有个大佬要自己重写查询. 支持RowNumber分页 等待吧

**Comment by multinerd** [comment]
> 
> 
> UseRowNumberForPaging efcore 3.1 不能用了吗 震惊 蛋疼
> 
> Row-number paging is no longer supported. See https://ak.ms/AA6h122 for more information.
> !!!
> Please support because our customer database is 2008

Another Microsoft url 404's...

**Comment by mentianyi** [comment]
[EF 3 Break change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#urn)

**Comment by dlmotter** [comment]
We need UseRowNumberForPaging because Azure Synapse Analytics Server (Azure Data Warehouse) doesn't support OFFSET either. In order to use EF Core 3.1 with ASAS you have to to weird stuff to skip records in memory, especially if you're using OData.
