### ISSUE TITLE
Best way to make migrations working on Service Fabric

### ISSUE THREAD

**Issue by Ponant** [dotnet/efcore#13969]
I expect that PM will properly add-migration and update-database for a service fabric template with a stateless asp.net core 2.0 (also tried 2.2 preview 3).

I get instead 
```
Unable to create an object of type 'ApplicationDbContext'.
Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project,
or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```
And the verbose version complains about WebHostBuilder
`No BuildWebHost method was found on type 'WebIdentity.Program'.
`

### Steps to reproduce
File new project service fabric with stateless asp.net core 2.0 with Identity. Add variable DefaultConnection with the value taken from appsetting.json directly in startup to temporarily circumvent  configuring the service fabric app manifest. Set the asp.net core project as startup in VS

https://github.com/Ponant/TestServiceFabric 

### Question
How to make that work properly? I checked out the service fabric repo that has no open or closed issues on EF Core. Thanks

**Comment by Ponant** [comment]
Hi @ajcvickers , thanks for the reply, I checked out your link but I do not understand its conclusion yet. It seems to say it is revolved, but it is isn't and others seem to report a similar issue. I do not yet have a workaround solution (setting the EF web app as startup project doe snot solve the issue). As far as I can see:
1) The template does not properly configure the connection string
2) The migration and update-database commands need some code to execute and somehow the service fabric template does not allow for that

I will update this thread if I have any solution, and welcome any advice on the matter in the meantime.

**Comment by ajcvickers** [comment]
@Ponant In the past there was no way to make this work with just a stateless Service Fabric project; it required a target framework that could actually execute code. This may not be the case anymore, so we are looking at this again for 3.0.

**Comment by Ponant** [comment]
@ajcvickers , for your info, I can make migrations work on service fabric, so I think you should be able to find a clean solution. The code I have is a bit brutal but it works; I will update this thread as soon as I can boil done the code to a cleaner one.

**Comment by Ponant** [comment]
@nmehlei , here is what I can come with. It works but I really think a solution should be found to make it more automatic.
https://github.com/Ponant/ServiceFabricSQLLocalDB

**Comment by ajcvickers** [comment]
Note from triage: We don't plan to do anything special here. The normal ways of making this work (e.g. separate dummy project; class library) should be sufficient.
