### ISSUE TITLE
Clean up in EntityMaterializerSource

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#13961]
https://github.com/aspnet/EntityFrameworkCore/blob/4236dfd7f2789782cbba26bf0af15b04dfaf2a0c/src/EFCore/Metadata/Internal/EntityMaterializerSource.cs#L29-L59

We marked old method obsolete to pass in property for value convertor work but now we don't use the property passed in.

**Comment by smitpatel** [comment]
I actually ended up reverting this in new query pipeline for now. Re-opening this and assigning to me to make sure we have correct change in place for final release.

**Comment by ajcvickers** [comment]
Close; it is needed in the new pipeline, so nothing to do here.
