### ISSUE TITLE
.NET Core 2.1.6 + EF Core in Azure , memory leak issues [Question]

### ISSUE THREAD

**Issue by jos1977** [dotnet/efcore#13978]
Hello,

We are currently running a backend application in Azure, which is running on .NET core 2.1.6 (windows), and uses EF Core with SQL database in Azure. At the moment we are experiencing a slow increase in memory usage which seems related to the number of API calls. After performing a memory dump i noticed that there are a lot of Objects of 'Microsoft.Extensions.Caching.Memory.CacheEntry', i am thinking there must be a memory leak occurring or GC is not working properly.

I made a screenshot of the dump, i am curious if anyone has any ideas about this, is this a problem related to the current .net Core version or do i need to investigate more in the EF queries and general configuration?

![image](https://user-images.githubusercontent.com/43636829/48697067-f6789000-ebe3-11e8-8d98-401923a8baeb.png)

  [1]: https://i.stack.imgur.com/5Blqf.png

**Comment by ajcvickers** [comment]
@jos1977 This looks like EF query caching. Can you provide some more details as to why you're thinking it is a memory leak?

**Comment by jos1977** [comment]
@ajcvickers  Well monitoring the process in Azure we noticed that the private memory keeps increasing on average (GC sometimes kicks in but doesnt make it stable). At a certain point we are experiencing out of memory exceptions and finally the thread is terminated (cgi application encountered an error...) and thus we are forced to restart the app.

I am really curious about that EF query caching, as far i can tell this must be part of standard functionality, since we didn't configure anything related to that (also no internal memory caching). Is this something which needs to be checked out or can we somehow control this in a way?

**Comment by ajcvickers** [comment]
@jos1977 A couple of possibilities:
* The internal service provider is being re-created for each context instance--see #12927 for more info, including what to look for in the logs if this is the case.
* There could be a bug in the query cache which is causing the "same" query to be cached pathologically. Again, checking the logs would be the best way to identify this.

**Comment by JanEggers** [comment]
@jos1977  you can use EF.CompileQuery, that avoids the cache.
