### ISSUE TITLE
Unexpected ignored includes

### ISSUE THREAD

**Issue by Xavier-Mobius** [dotnet/efcore#13979]
`Include` and `ThenInclude` are ignored when the query has a "custom" `Select`. 

### Steps to reproduce
Example :

```c#
var test = context.Invoices
    .Include(i => i.Customer)
    .ThenInclude(c => c.Adresses)
    .Select(i => new { i.Id, i.Customer }) // If this line is deleted, Customer.Adresses is no longer empty
    .ToList();

var shouldNotBeNull0 = test.First().Customer.Name;                      // Is not null
var shouldNotBeNull1 = test.First().Customer.Adresses;                  // Is not null but is always empty
var shouldNotBeNull2 = test.First().Customer.Adresses.First().City;     // Throw an exception because Customer.Adresses is empty
```

(Full solution in attachment)
[EntityCore.IncludeIssue.zip](https://github.com/aspnet/EntityFrameworkCore/files/2595618/EntityCore.IncludeIssue.zip)

### Further technical details
EF Core version: 2.1.4
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 Pro 64 bits
IDE: Microsoft Visual Studio Enterprise 2017 Version 15.9.1

**Comment by ajcvickers** [comment]
@Xavier-Plasma This is by-design since the query does not return `Invoice` entities, which is where the Include is defined. However, see #12737
