### ISSUE TITLE
DBQuery behaviour with Moq and UseInMemoryDatabase

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/efcore#13995]
I am seeing a bug when I try and materialize my view using the in memory database context. With Version 2.1 of MVC Core.

Creating the DB Context:
```C#
            var options = new DbContextOptionsBuilder<ApplicationDbContext>()
                   .UseInMemoryDatabase(databaseName: "Index_Get_AsAuthenticatedUser")
                   .Options;

            // Run the test against one instance of the context
            using (var context = new ApplicationDbContext(options))
            {
...
            }
```

Error message thrown:
```
Expression of type 'System.Object' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Metadata.IKey' of method 'System.Collections.Generic.IEnumerable`1[TagentsBarn.Models.BookingDerivedView] EntityQuery[BookingDerivedView](Microsoft.EntityFrameworkCore.Query.QueryContext, Microsoft.EntityFrameworkCore.Metadata.IEntityType, Microsoft.EntityFrameworkCore.Metadata.IKey, System.Func`3[Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.Storage.MaterializationContext,System.Object], Boolean)'
Parameter name: arg2

```
This is observed in the straight DBQuery<MyView> in the real-time debugging inside Visual Studio before any form of WHERE clause is applied and works fine with a normal DBContext outside the testing suite.

Thanks
Mark

**Comment by ajcvickers** [comment]
@MCFHTAGENTS There is not enough information here for us to be able to reproduce the issue you are seeing. Please post a runnable project/solution or complete code listing that demonstrates the issue.

**Comment by MCFHTAGENTS** [comment]
hi there, I have worked out what is going on. The new DBQuery on the DBContext, obviously doesn't work with the InMemory context as it is not a SQL engine. I refactored my code to provide the output of the view into a function which I can then unit test.

It would be helpful if you could inject view results into a DBQuery like you can a DBSet to facilitate unit testing.
Regards
Mark

**Comment by ajcvickers** [comment]
@MCFHTAGENTS Can you elaborate a bit on, "It would be helpful if you could inject view results into a DBQuery like you can a DBSet to facilitate unit testing."

**Comment by MCFHTAGENTS** [comment]
I have a view in my database that is exposed by way of the DBQuery functionality. All works fine in normal use. My service has an ApplicationDbContext injected into it and uses the view. With a normal table the MemoryContext allows me to mock data and pass it into the controller. However the view cannot be mocked in this way as it is a SQL statement run on the back end. Hence it would be helpful to be able to inject some data into the view results as you can already do with the DBSet such that I can pass the mocked data into the unit tests for my service.

**Comment by ljhca** [comment]
Is there a solution to this out there? 

We also need to be able to work with DbQuery objects within a unit test; specifically, we need to add test data to it in order to run the test.

Has this issue been addressed?

**Comment by MCFHTAGENTS** [comment]
I ended up refactoring my code so that I could pass in the results of a view into a method that used it so I could then mock up a simple set of data and test the method

**Comment by ljhca** [comment]
@MCFHTAGENTS OK cool - thanks.

We ended up using the below NuGet package to Mock the Context as it has helper methods to setup DbQuery result sets:

https://github.com/huysentruitw/entity-framework-core-mock
