### ISSUE TITLE
SqlServerMigrationsAnnotationProvider For methods call base ForRemove

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [dotnet/efcore#14007]
While trying to implement a custom MIgrationsAnnotationProvider I ran into a weird issue saying annotations had already been added. I was originally overriding `For` and returning the base plus an additional annotation then determined I would need annotations on downgrades as well so I overrode `ForRemove` and returned the base annotations plus an additional annotation.

I dug in a little and noticed that `For` on [`SqlServerMigrationsAnnotationProvider`](https://github.com/aspnet/EntityFrameworkCore/blob/7cd2eb79628a2511af8e8d2699c29380909ab004/src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs) chains calls to `base.ForRemove` in a couple places. Specifically [here](https://github.com/aspnet/EntityFrameworkCore/blob/7cd2eb79628a2511af8e8d2699c29380909ab004/src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs#L34) and [here](https://github.com/aspnet/EntityFrameworkCore/blob/7cd2eb79628a2511af8e8d2699c29380909ab004/src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs#L40)

**Comment by ajcvickers** [comment]
@bricelam to follow up.

**Comment by bricelam** [comment]
The assumption is that any attributes you need during a DROP, you’ll also need them during CREATE and ALTER.

It sounds like this holds true in your scenario. Don’t add the duplicate annotations in `For`.

**Comment by ZombieProtectionAgency** [comment]
Alright. The naming didn't make it obvious but that does make sense.
