### ISSUE TITLE
Unnecessary column is added in migration. Why?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#14008]
I tried to create typed ids which are wrappers of `Guid`. There are two entities `DeviceType` and `DeviceModel`. `DeviceModel` has a reference to `DeviceType`:    `DeviceTypeId DeviceTypeId {get; private set;}`

When I call `Add-Migration Init` I get weird result:

```CSharp
columns: table => new
{
    Id = table.Column<Guid>(nullable: false),
    DeviceTypeId = table.Column<Guid>(nullable: false),
    Title = table.Column<string>(nullable: false),
    DeviceTypeId1 = table.Column<Guid>(nullable: true)
},
```
I have no idea where this *DeviceTypeId1* comes from.

### Steps to reproduce
[Repo](https://github.com/voroninp/MigrationsBug-)

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 PRO 10.0.17134
IDE: Visual Studio 2017 15.9.2

And I also get an exception, when query with filter: 
`DeviceTypes.Where(t => t.Id != deviceTypeId && t.Name == name).Count()`

>InvalidOperationException: Error generated for warning Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression where ([t].Id != __deviceType_Id_0) could not be translated and will be evaluated locally.

My expectation is that conversion of `deviceTypeId` should be made and correct expression tree generated for SQL query.

**Comment by ajcvickers** [comment]
@voroninp It's not clear to me from the code what the intention is when defining the relationship between DeviceType and DeviceModel. Which is the principal end and which is the dependent end? Or, in other words, what do you expect the FK constraint to look like in the database?

**Comment by voroninp** [comment]
@ajcvickers  model depend on type.

**Comment by ajcvickers** [comment]
@voroninp Do you expect the FK column to be in the DeviceModel table or the DeviceType table?

**Comment by voroninp** [comment]
@ajcvickers DeviceModel. many models can have same type. One To Many relationship.

**Comment by ajcvickers** [comment]
Note for triage: model building issue. Repros on 2.2 RTM.

@voroninp A workaround is to move the property mapping with the converter so that it happens before the relationship is defined:
```C#
b.Property(m => m.DeviceTypeId)
    .HasConversion(DeviceTypeIdConverter)
    .IsRequired();

b.HasOne<DeviceType>()
    .WithMany()
    .HasForeignKey(m => m.DeviceTypeId)
    .IsRequired()
    .OnDelete(DeleteBehavior.Restrict);
```
Model:
```
  EntityType: DeviceModel
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      DeviceTypeId (DeviceTypeId) Required FK Index 1 1 1 -1 1
      DeviceTypeId1 (no field, DeviceTypeId) Shadow FK Index 2 2 2 0 2
      Title (string) Required AlternateKey AfterSave:Throw 3 3 3 -1 -1
    Keys: 
      Id PK
      Title
    Foreign keys: 
      DeviceModel {'DeviceTypeId'} -> DeviceType {'Id'}
      DeviceModel {'DeviceTypeId1'} -> DeviceType {'Id'}
  EntityType: DeviceType
    Properties: 
      Id (DeviceTypeId) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      Name (string) Required AlternateKey AfterSave:Throw 1 1 1 -1 -1
    Keys: 
      Id PK
      Name
```

**Comment by voroninp** [comment]
Thanks. I would like to mesnion as well that currently from docs is not clear how _value generation_ and _value conversion_ works together. 

When I tried `valuegeneratedonadd` for the property of type `DeviceTypeId` my expectation was, that generation would be done for the destination type, but it appeared that EF requires generator for the type of the property. 

Hence, there is a question/proposal:

If converter for the target type exists (`Guid` in my case) and EF can generate the value, then it probably can do a reverse thing using converter (`new DeviceTypeId(generatedGuid)` in my case).

**Comment by AndriySvyryd** [comment]
@voroninp The referenced repo has been deleted. If you are still experiencing this issue please reupload the repro code.
