### ISSUE TITLE
Translation Cache Memory Leak Debugging

### ISSUE THREAD

**Issue by jceddy** [dotnet/efcore#14004]
I'm not sure this is the best place to ask this question, but I haven't found a better place, so here goes:

I'm trying to debug a memory leak in a (quite large and complex) application that I suspect is due to one or more LINQ queries having different versions cached due to (for example) Constant Expression nodes showing up in the query trees.

Is there any way to look at set of cached query translations that could help me track down which LINQ queries might be causing this? Either while stopped in a debugger or through looking at a memory snapshot in the VS2017 debugger?

If this is the wrong place to ask this, feel free just to tell me so and close it.

**Comment by ajcvickers** [comment]
@jceddy Processing the logs may be a good place to start. EF generates the log entries like the following whenever it compiles a query:
```
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Compiling query model:
      '(from Order x in DbSet<Order>
      select [x])
      .Include("OrderLines")
      .FirstOrDefault()'
```
You could also consider using [query tags](https://docs.microsoft.com/en-us/ef/core/querying/tags) in 2.2 to help trace where queries are coming from.

The cache can also be found in the debugger:
![image](https://user-images.githubusercontent.com/1430078/49046800-2d254c00-f18a-11e8-8ab1-0b380b2a498c.png)
