### ISSUE TITLE
Integration tests use AddDbContext method throw exception

### ISSUE THREAD

**Issue by jingliancui** [dotnet/efcore#14009]
[IntegrateTestWeb.zip](https://github.com/aspnet/AspNetCore/files/2610152/IntegrateTestWeb.zip)

Run XWebTest.MainTest.Test1 is fine .

After modify XWebTest.CustomWebApplicationFactory use 

```
services.AddDbContext<ApplicationDbContext>( options =>
                {
                    options.UseSqlite(conn);
                    options.UseInternalServiceProvider(serviceProvider);
                });
```

TestExplorer throw error:
`Message: System.InvalidOperationException : No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
`

So ,I use these now instead:

```
services.AddTransient<ApplicationDbContext>(provider => 
                {
                    var options = new DbContextOptionsBuilder<ApplicationDbContext>()
                    .UseSqlite(conn)
                    .Options;
                    var db = new ApplicationDbContext(options);
                    return db;
                });
```

**Comment by ajcvickers** [comment]
Note for triage: minimal repro is below. This happens when the database provider being used hasn't been added to the internal service provider. It's a negative case, but the exception message could be better.
```C#
public class BloggingContext : DbContext
{
    private readonly IServiceProvider _serviceProvider
        = new ServiceCollection()
            .AddEntityFrameworkInMemoryDatabase()
            .BuildServiceProvider();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0")
            .UseInternalServiceProvider(_serviceProvider);
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            var model = context.Model;
        }
    }
}
```

**Comment by ajcvickers** [comment]
Triage: closing as wont-fix. While we could spend time trying to make a better message in this case, it's probably not worth it giving that some pretty strange code is needed to get here. If we see a lot of people doing the same thing we can always reconsider.
