### ISSUE TITLE
FirstOrDefault for Guid behaves different after upgrade to EF 2.1

### ISSUE THREAD

**Issue by mvonck** [dotnet/efcore#14029]
### The issue

The behavior of FirstOrDefault for Guid in Entity Framework Core changed since the update of 2.1. 

### Steps to reproduce

When i have the following Entity in my DbContext:

```
public class ContentEntity {

    public Guid Id { get; set; }

    public string Title { get; set; }
}
```
And i execute the following Code:

```
Guid? result = dbContext.Set<ContentEntity>()
                .Where(item => item.Title == "Not existing title") // So no results
                .Select(item => item.Id)
                .FirstOrDefault();
```

result in EF 2.0 is: null
result in EF 2.1 is: 00000000-0000-0000-0000-000000000000

The result in EF 2.1 is unwanted behavior. The result should be null.

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio

**Comment by smitpatel** [comment]
You are calling `FirstOrDefault` on a sequence of `Guid`. With the where predicate the sequence is empty hence returning default value of `Guid` which is **not** null. The 2.1 behavior is accurate.

**Comment by divega** [comment]
Does it help to cast the result type inside the query to `Nullabke<Guid>`? For example:

''' csharp
car result = dbContext.Set<ContentEntity>()
                .Where(item => item.Title == "Not existing title") // So no results
                .Select(item => (Guid?)item.Id)
                .FirstOrDefault();
'''
