### ISSUE TITLE
Localization question

### ISSUE THREAD

**Issue by LucaGabi** [dotnet/efcore#14021]
Hi,

I have the following case: my app has a known set of supported cultures, for each table/model, each varchar field, has a corresponding column for one of the known cultures, in the db - each column has a prefix for the culture e.g. book.title has a book.fr_title and book.ru_title the default culture column has no prefix. How can I use EF Core to query the db in such way that it will get the data in to the model according to current culture ? In the model there is only one property book.title so the value should be mapped to this field. **Is there a way to modify the EF Core generated SQL to select the correct column in the table according to the current culture?**

I would very much appreciate any kind of help.
(I want it to work like this, no extra additions: var books.Where(b=>b.price>23.2).ToList();)
I looked at computed properties but those did not work ..

Thanks.

**Comment by ajcvickers** [comment]
@LucaGabi You should be able to [replace IModelCacheKeyFactory](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model) such that a different model is built for each language and in each of those models the tables are mapped to different names. Something like this:
```C#
public class Blog
{
    public Guid Id { get; set; }
    public string Title { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .ReplaceService<IModelCacheKeyFactory, PerCultureModelCacheKeyFactory>()
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Blog>()
            .Property(e => e.Title)
            .HasColumnName(
                CultureInfo.CurrentCulture.TwoLetterISOLanguageName + "_title");
    }
}

public class PerCultureModelCacheKeyFactory : IModelCacheKeyFactory
{
    public object Create(DbContext context) 
        => (context.GetType(), CultureInfo.CurrentCulture);
}
```
