### ISSUE TITLE
Joins post Group By

### ISSUE THREAD

**Issue by avinash-phaniraj-readify** [dotnet/efcore#14036]
Step1: Setup a query involving a left outer join and projection. for ex:
```c#
var q1 = from employee in context.Set<EFCore.Employee>()
     join device in context.Set<EFCore.EmployeeDevice>() on employee.Id equals device.EmployeeId into emptyDevice
     from theDevice in emptyDevice.DefaultIfEmpty()
     select new { employee.Id, device.Name };
```

Step2: Perform a Group By and prepare a projection
```c#
var q2 = from q1Row in q1
     group q1Row by new
     {
       q1Row.Id
     } into s
     select new
     {
       s.Key.Id,
       DevicesCount = s.Count(a=> a.Name) 
     };
```
Step3: Use the query to join with other entities
```c#
var q3 = from q2Row in q2
     join location in context.Set<EFCore.Location>() on q2Row.Id equals location.EmployeeId 
     select new 
     {
       q2Row.Id,
       location.Name
     };
     var results = q3.ToList();
```
We intend to build a rather complex query in step 1 and 2 involving some grouping. And then use this to join other tables to get at other data elements.

I gather from (https://www.codemag.com/Article/1807071/Entity-Framework-Core-2.1-Heck-Yes-It%E2%80%99s-Production-Ready!) that this not supported by EFCore. 
Trying this alters the query in step 2 with additional columns being added to the select clause and results in an invalid query.

What I'd like guidance with is - 

1. Is there a work around ? Our Transformation project has lots of queries with this pattern. 
2. What are our options 
3. Please note that the example above is a simplified version of the real queries. The group by also involves several aggregate funcs and other key columns that are required for step 3. 

[PS: 
1. Steps 1 and 2 - have been broken down from one single query owing to 
https://github.com/aspnet/EntityFrameworkCore/issues/12826 and also because a query with DefaultIfEmpty() and Group By fails to get translated to SQL as described here 
https://stackoverflow.com/questions/50162978/ef-core-group-by-translation-support-on-conditional-sum
2. I have not tested this on MS SQL, I'd expect to run into the same issue.
]

```
Exception Type: System.Data.SqlServerCe.SqlCeException
Exception message: In aggregate and grouping expressions, the SELECT clause can contain only aggregates and grouping expressions. [ Select clause = location,Name]
```

### Further technical details
EF Core version: 2.1.4
Database Provider: (e.g. SqlServerCompact35 2.1.2.1)
Operating system: Win 10
IDE: (e.g. Visual Studio 2017 15.8.6)

**Comment by ErikEJ** [comment]
Not sure why this was closed - running in memory could be a valid fix (in particular for SQL CE)

**Comment by avinash-phaniraj-readify** [comment]
Sorry about the rather hurried post. I realise I'm not a 100% over some strange things we are seeing. let me get to the bottom of it and comeback with a more articulate question. 
Thanks and sorry for the bother.
