### ISSUE TITLE
Owned objects attached with wrong state

### ISSUE THREAD

**Issue by Rubbiroid** [dotnet/efcore#14031]
If I have a entity with some owned object and I attach this entity to the context, the entity get State "Unchanged", but the owned entity got status "Added", which lead to exception:

The entity of type '**OwnedType**' is sharing the table '**TableName**' with entities of type '**EntityType**', but there is no entity of this type with the same key value '{**PK**: **Value**}' that has been marked as 'Added'.

I would expect, that owned entity gets status "Unchanged".

### Further technical details
EF Core version: 2.1.4

**Comment by Rubbiroid** [comment]
More details:
`public class ParentEntity {
    public int Id {get;set;}
    public Entity Entity {get;set;}
}

public class Entity {
    public int id {get;set;}
    public OwnedObject OwnedObject {get;set;}
}

public class OwnedObject {
    public string Value {get;set;}
}
`

If I add a Parent entity first and then attach an Entity, OwnedObject  get a wrong state and I get the exception. If I Attach the Entity first and then add ParentEntity everything works fine.

**Comment by ajcvickers** [comment]
@Rubbiroid Does this capture what you mean by "add a Parent entity first and then attach an Entity,"

```C#
var parentEntity = new ParentEntity
{
    Entity = new Entity
    {
        id = 1,
        OwnedObject = new OwnedObject()
    }
};

context.Add(parentEntity);
context.Attach(parentEntity.Entity);

context.SaveChanges();
```

**Comment by Rubbiroid** [comment]
@ajcvickers yes.

**Comment by ajcvickers** [comment]
@Rubbiroid The reason this is happening is that calling Add with `parentEntity` causes the entire graph to be tracked in the Added state. The Attach call on the other hand sees that the referenced entity is already tracked and changes its state but does not change the state of the owned entity. This is currently by-design, but we are looking into two changes in this area:
* Changes to handling of store generated keys: #13575
* Improved behaviors for aggregates: #1985

I'm closing this, but referencing the scenario from those two places.
