### ISSUE TITLE
Make Cosmos-required APIs public

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#14033]
Original issue below. These types are going, but new public types may be needed, and Cosmos may need other internal types made public.

The types `IEntityResultFindingExpressionVisitorFactory`, `IEntityResultFindingExpressionVisitor`, `IEntityTrackingInfoFactory`, `EntityTrackingInfo` should be moved out of the Internal namespace as they are needed for Cosmos (and probably other non-relational providers)

**Comment by smitpatel** [comment]
All those classes may go away in new pipeline.

**Comment by AndriySvyryd** [comment]
That's fine, as long as the corresponding functionality is exposed to the provider.
