### ISSUE TITLE
Statement order in down-migration is incorrect

### ISSUE THREAD

**Issue by bobvandevijver** [dotnet/efcore#14030]
See the migration below:
```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateSequence(
        name: "seq_bi_id",
        startValue: 15000000000L);

    migrationBuilder.AlterColumn<long>(
        name: "bi_id",
        table: "animals",
        nullable: false,
        defaultValueSql: "NEXT VALUE FOR seq_bi_id",
        oldClrType: typeof(long));
}

protected override void Down(MigrationBuilder migrationBuilder)
{
    migrationBuilder.DropSequence(
        name: "seq_bi_id");
        
    migrationBuilder.AlterColumn<long>(
        name: "bi_id",
        table: "animals",
        nullable: false,
        oldClrType: typeof(long),
        oldDefaultValueSql: "NEXT VALUE FOR seq_bi_id");
}
```

Generated by this code:
```c#
const string biIds = "seq_bi_id";

modelBuilder.HasSequence<long>(biIds)
            .StartsAt(15000000000)
            .IncrementsBy(1);

 modelBuilder.Entity<AnimalEntity>()
            .Property(a => a.BiId)
            .HasDefaultValueSql($"NEXT VALUE FOR {biIds}");
````

In this scenario, the down migration fails as the execution order is the same as with the `Up` migration. The sequence cannot be removed, as it is still used as default value sql in the animals table.

It would make sense if by default the generated order is flipped. There are probably exceptions with dependencies etc, but in general reversing the order should always be correct (you want to revert statements, which are coincidentally grouped in a migration). It would at least solve the problem here.

What do you think?

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOS
IDE: Rider

**Comment by bricelam** [comment]
Similar to #12726. We need to be smarter about columns with `HasDefaultValueSql` and `HasComputedColumnSql`. Although without actually parsing the SQL, we'll never be perfect.

The workaround is to manually re-order the operations after scaffolding.

**Comment by bricelam** [comment]
Looking closer, I don't think we should fix this. At a high level, the order we use is:

- Drop things
- Rename things
- Create and alter things

This is to enable replacing database objects with new ones. I think that if we try to fix this specific case, it will cause other cases to fail.

Short of parsing the SQL (a complexity we desperately wish to avoid), I don't think we can adequately  fix this.
