### ISSUE TITLE
Consider setting (optionally) by config a limit of entities within the lifecycle of a context

### ISSUE THREAD

**Issue by pacoweb** [dotnet/efcore#1405]
Set ( **optionally** ) a limit on the number of entities charged in context. Something like philosophy followed by RavenDb [ Safe by Default!](http://ravendb.net/docs/article-page/2.5/csharp/intro/safe-by-default).

This would favor the use of best practices in the daily work with Entity.

Thanks!

**Comment by rowanmiller** [comment]
This probably isn't something we would want to enforce with exceptions etc. (at least not by default) but these scenarios could be great to log as warnings (long lived contexts, large number of entities in memory, queries with huge result sets, large numbers of Includes in queries, etc.).

It would be interesting to see if most of these could be handled by additional packages that folks can opt into if they want the behavior (using logging, provider APIs, etc.)

**Comment by pacoweb** [comment]
That sounds ambitious!

I was thinking in something more simple and strict. Some **optional** property in ChangeTracker (MaxTrackedEntriesSize, by instance) to just control the tracked entries. Maybe using the changes in the identitymap dictionary, in the StateManager class to check the max size.

Thanks for answering!

**Comment by rowanmiller** [comment]
Discussed in triage and decided that we don't want to do this. We will have hooks that make it possible to easily implement this though.
