### ISSUE TITLE
Can i have Shared SaveChangesAsync() or SaveChanges() between multiple DbContext?

### ISSUE THREAD

**Issue by masoud-bahrami** [dotnet/efcore#14061]
I have a DbContext(ChildDbContext) which inherited from Another DbContext(ParentDbContext).
ParentDbContext inherited from DbContext.

I want to hide SaveChanges() and SaveChangesAsync() from clients of ChildDbContext, and then by calling SaveChanges from ParentDbContext() all tracked DbEntities from ChildDbContext then will be save.

**Comment by ajcvickers** [comment]
@masoud-bahrami This looks more like a C# question than an EF question, and it sounds like inheritance is not the right pattern here; use composition instead.
