### ISSUE TITLE
Empty collections with one:many include and condition

### ISSUE THREAD

**Issue by FilX** [dotnet/efcore#14062]
I have entity with many 1:N relations. I load entities with condition e.g. DateUpdated <= specificDate.  and with Include collections. Sometime are collections empty because data was changed during load 1:N relations. It seems that problem is in multiple "independent" queries for collections load with parent entity condition.

**Example of one query for collection**

N'SELECT [x.Product.BarCodeZboList].[ID], [x.Product.BarCodeZboList].[BarCode], [x.Product].[IDProduct], [x.Product.BarCodeZboList].[IsDefault]
FROM [TabBarCode] AS [x.Product.BarCodeZboList]
INNER JOIN (
    SELECT DISTINCT [x.Product].[ID]
    FROM [Product_Changes] AS [x0]
    INNER JOIN [Product] AS [x.Product0] ON [x0].[ID] = [x.Product0].[ID]
    LEFT JOIN [Product_EXT] AS [x.Product.Product_EXT0] ON [x.Product0].[ID] = [x.Product.Product_EXT0].[ID]
    **WHERE ([x0].[DateUpdated] <= @__context_ChangeTrackingInfo_ToDate_0) AND ([x0].[DateUpdated] > @__context_ChangeTrackingInfo_FromDate_Value_1**)
) AS [t] ON [x.Product.BarCodeZboList].[IDProduct] = [t].[ID]
ORDER BY [t].[ID]',N'@__context_ChangeTrackingInfo_ToDate_0 datetime,@__context_ChangeTrackingInfo_FromDate_Value_1 datetime',@__context_ChangeTrackingInfo_ToDate_0='2018-12-03 10:36:14.047',@__context_ChangeTrackingInfo_FromDate_Value_1='2018-11-26 15:20:39'

Data in table Product_Changes are frequently changed and condition during load collections can be broken. That's mean that product is loaded but with empty collections

### Steps to reproduce
Change data from condition for Main Entity (Product) during when collections are loading

**Comment by ajcvickers** [comment]
@FilX This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by FilX** [comment]
It's little bit hard to simulate it. Today I got the same behavior.

**Entities** (Just important properties)

`    public class KmenZbozi_Changes
    {

        /// <summary>
        /// KmenZbozi ID
        /// </summary>
        public int ID { get; set; }
        public DateTime DateUpdated { get; set; }
        public KmenZbozi KmenZbozi { get; set; }
    }


    public class KmenZbozi : HeliosEntityBase
    {
        public int ID { get; set; }
        public IList<DokumVazba> DokumVazbaList { get; set; }
    }

    public class DokumVazba
    {
        /// <summary>
        /// Dokument ID
        /// </summary>
        public int IdDok { get; set; }
        /// <summary>
        /// KmenZbozi  ID
        /// </summary>
        public int IdTab { get; set; }
        /// <summary>
        /// KmenZbozi 
        /// </summary>
        public KmenZbozi KmenZbozi { get; set; }
    }

`

**Mappings**

`    public class KmenZbozi_ChangesMapping: TrackingChangesEntityTypeConfigurationBase<KmenZbozi_Changes>
    {
        public override void Configure(EntityTypeBuilder<KmenZbozi_Changes> builder)
        {
            base.Configure(builder);
            builder.HasKey(nameof(IHeliosEntity.ID));
            builder.HasOne(x => x.KmenZbozi).WithMany().HasForeignKey(x => x.ID);
        }
   {
public class KmenZboziMapping: HeliosEntityTypeConfigurationBase<KmenZbozi>
    {
        public override void Configure(EntityTypeBuilder<KmenZbozi> builder)
        {
            builder.HasKey(nameof(IHeliosEntity.ID));
            builder.HasMany(x => x.DokumVazbaList)
                .WithOne(x => x.KmenZbozi)
                .HasForeignKey(x => x.IdTab);
        }
    }

    public class DokumVazbaMapping : HeliosEntityTypeConfigurationBase<DokumVazba>
    {
        public override void Configure(EntityTypeBuilder<DokumVazba> builder)
        {
            ToTable(builder);
            builder.HasKey(x => new { x.IdDok, x.IdTab });
        }
   }

`

**Linq Query**

`            var query = _dataContext.KmenZbozi_Changes
                                .Where(x => x.DateUpdated <= context.ChangeTrackingInfo.ToDate);

            if (context.ChangeTrackingInfo.FromDate.HasValue)
            {
                query = query.Where(x => x.DateUpdated > context.ChangeTrackingInfo.FromDate.Value);
            }

            var kmenZboziListX = query
                .Select(x => x.KmenZbozi)
                .Include(x => x.DokumVazbaList)
                .ThenInclude(x => x.Dokumenty)
                .ThenInclude(x => x.Dokumenty_EXT).ToList();
`

**SQL Queries (Profiler)**

`exec sp_executesql N'SELECT [x.KmenZbozi].[ID], [x.KmenZbozi].[Aktualni_Dodavatel], [x.KmenZbozi].[DodaciLhuta], [x.KmenZbozi].[DruhSkladu], [x.KmenZbozi].[Hloubka], [x.KmenZbozi].[Hmotnost], [x.KmenZbozi].[MJEvidence], [x.KmenZbozi].[MJVstup], [x.KmenZbozi].[MJVystup], [x.KmenZbozi].[Minimum_Baleni_Dodavatel], [x.KmenZbozi].[Minimum_Odberatel], [x.KmenZbozi].[Nazev1], [x.KmenZbozi].[Nazev2], [x.KmenZbozi].[Nazev3], [x.KmenZbozi].[Nazev4], [x.KmenZbozi].[Objem], [x.KmenZbozi].[PrepMnozstvi], [x.KmenZbozi].[RegCis], [x.KmenZbozi].[Sirka], [x.KmenZbozi].[SkupZbo], [x.KmenZbozi].[TypDodaciLhuty], [x.KmenZbozi].[TypZarukaVystup], [x.KmenZbozi].[Vyrobce], [x.KmenZbozi].[Vyska], [x.KmenZbozi].[ZarukaVystup]
FROM [blogic].[TabKmenZbozi_Changes] AS [x]
INNER JOIN [TabKmenZbozi] AS [x.KmenZbozi] ON [x].[ID] = [x.KmenZbozi].[ID]
WHERE [x].[DateUpdated] <= @__context_ChangeTrackingInfo_ToDate_0
ORDER BY [x.KmenZbozi].[ID]',N'@__context_ChangeTrackingInfo_ToDate_0 datetime',@__context_ChangeTrackingInfo_ToDate_0='2018-12-12 08:55:44.670'


exec sp_executesql N'SELECT [x.KmenZbozi.DokumVazbaList].[IdDok], [x.KmenZbozi.DokumVazbaList].[IdTab], [x.KmenZbozi.DokumVazbaList].[IdentVazby], [d.Dokumenty].[ID], [d.Dokumenty].[JmenoACesta], [d.Dokumenty].[Popis], [d.Dokumenty].[UlozenoDB], [d.Dokumenty.Dokumenty_EXT].[ID], [d.Dokumenty.Dokumenty_EXT].[_BLogic_DocumentSubtypeCode], [d.Dokumenty.Dokumenty_EXT].[_BLogic_DocumentType]
FROM [TabDokumVazba] AS [x.KmenZbozi.DokumVazbaList]
INNER JOIN [TabDokumenty] AS [d.Dokumenty] ON [x.KmenZbozi.DokumVazbaList].[IdDok] = [d.Dokumenty].[ID]
LEFT JOIN [TabDokumenty_EXT] AS [d.Dokumenty.Dokumenty_EXT] ON [d.Dokumenty].[ID] = [d.Dokumenty.Dokumenty_EXT].[ID]
INNER JOIN (
    SELECT DISTINCT [x.KmenZbozi0].[ID]
    FROM [blogic].[TabKmenZbozi_Changes] AS [x0]
    INNER JOIN [TabKmenZbozi] AS [x.KmenZbozi0] ON [x0].[ID] = [x.KmenZbozi0].[ID]
    WHERE [x0].[DateUpdated] <= @__context_ChangeTrackingInfo_ToDate_0
) AS [t] ON [x.KmenZbozi.DokumVazbaList].[IdTab] = [t].[ID]
ORDER BY [t].[ID]',N'@__context_ChangeTrackingInfo_ToDate_0 datetime',@__context_ChangeTrackingInfo_ToDate_0='2018-12-12 08:55:44.670'

`

The Linq query generate two separated sql queries. The first query SELECT [x.KmenZbozi].[ID], …. was started at 2018-12-12 09:02:35.690 and second query was started at 2018-12-12 09:02:35.880

During executing Linq Query was some data changed (DateUpdated was changed) and DateUpdated  condition for main entity is not valid for some records.

The problem is that main entity is loaded before child entities are loaded. And result is that some main entities has no child entities because condition was changed during child entities loading.

Is there any solution for this case? E.g. Call linq query with one Sql query? Call every main entity load in transaction?

**Comment by ajcvickers** [comment]
@FilX Thanks. We're already discussing how to approach multiple verses single queries for collection includes in 3.0--see #12098

**Comment by FilX** [comment]
It seems that only way how to fix it is call every load with 1:N include in transaction with IsolationLevel.RepeatableRead or Serializable

`            using (var transaction = _dataContext.Database.BeginTransaction(IsolationLevel.RepeatableRead))
            {
                kmenZboziList = query
                    .Select(x => x.KmenZbozi)
                    .Include(x => x.DokumVazbaList)
                    .ThenInclude(x => x.Dokumenty)
                    .ThenInclude(x => x.Dokumenty_EXT).ToList();
            }`
