### ISSUE TITLE
Reverse Engineer.  'KeyBuilder' does not contain a definition for 'ForSqlServerIsClustered'

### ISSUE THREAD

**Issue by cccuscott** [dotnet/efcore#14077]
Describe what is not working as expected.
I ran a db-scaffold on my database and it created this piece of code.
```
                entity.HasKey(e => new { e.PerkId, e.ProductId })
                    .ForSqlServerIsClustered(false);
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'KeyBuilder' does not contain a definition for 'ForSqlServerIsClustered' and no accessible extension method 'ForSqlServerIsClustered' accepting a first argument of type 'KeyBuilder' could be found (are you missing a using directive or an assembly reference?)	Persistence	C:\Users\scott.bush\Documents\Source\BranchManagerCore\Persistence\LeadManager\LeadManagerDbContext.cs	889	Active

Stack trace: 
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Scaffold-DbContext "Server=tcp:****.database.secure.windows.net,1433;Initial Catalog=****;Persist Security Info=False;User ID=****;Password=****;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Persistence.Identity -force -context LeadManagerDbContext
```

### Further technical details
EF Core version: 2.1.5
Database Provider: azure sql
Operating system: azure web app
IDE: Visual Studio 2017 15.9

**Comment by smitpatel** [comment]
Does your project where scaffolded models are generated contains reference to SqlServer package?

**Comment by cccuscott** [comment]
Nope, I'm an idiot i did not have Microsoft.EntityFrameworkCore.SqlServer referenced. Thanks for your time.
