### ISSUE TITLE
Method IModel.TryGetEntityType probably should be renamed

### ISSUE THREAD

**Issue by ilmax** [dotnet/efcore#1408]
Hi, first of all excuse me if this a dupe, but I've tried searching around with no luck.
I noticed that the method indicated above does not follow the "de facto standard" of the TryXXX methods because it's return type is IEntityType instead of bool, so I'm suggesting to change the method name to something similar to GetEntityTypeOrNull (open for better alternatives) and drop the Try prefix to be consistent with the .Net Framework.

M.

**Comment by divega** [comment]
Thank @ilmax for the feedback. We have different opinions on the team on naming :smile: Certainly the classic TryGet pattern in .NET with out params is not one of my favorites. For something like this my take is that we could use FindEntityType (GetEntityTypeOrNull sounds very complicated), but most likely this rename will have to wait until we do an API review.

**Comment by ilmax** [comment]
@divega Agree, I'm not a fan of out parameters too, but since almost all TryGet in .net world return bool, we should try to be consistent IMHO.
+1 for FindEntityType

**Comment by rowanmiller** [comment]
Added a note to consider this during API review https://github.com/aspnet/EntityFramework/issues/1158
