### ISSUE TITLE
Primary key of new child entity changed to a strange negative value

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#14085]
When I retrieve or attach an entity with a relationship (doesn't matter if it's 1-1 or 1-many) and replace the child entity with a new one, the Id of the child entity is changed to a strange negative value (like `-2147482646`) after calling dbContext.Entry().

Calling dbContext.SaveChanges() does however still work as expected and simply creates a new child entity with a generated primary key.

### Further technical details
EF Core version: 2.1.3 / 2.1.4 / 2.2.0
Database Provider: SqlServer and Sqlite. Does not repro in InMemory.
Operating system: Win 1809
IDE: VS 15.9,3

### Steps to reproduce
``` c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace ConsoleApp12
{
    class Program
    {
        static void Main(string[] args)
        {
            var sqlSrvConnStr = "__replace_me__";
            var sqliteConn = new Microsoft.Data.Sqlite.SqliteConnection("data source=:memory:");
            sqliteConn.Open();

            var opts = new DbContextOptionsBuilder<MyContext>()
                // Replicates with Sqlite
                .UseSqlite(sqliteConn)
                // Also replicates with SqlServer.
                //.UseSqlServer(sqlSrvConnStr)
                // Does not replicate with InMemoryDatabase.
                //.UseInMemoryDatabase()
                .Options;

            Repro_Setup(opts);
            Repro(opts);
            Console.ReadLine();
        }

        static void Repro(DbContextOptions<MyContext> opts)
        {
            var ctx = new MyContext(opts);

            var ent = ctx.Set<MyEntity>().Include(me => me.MySubEntity).First();
            ent.MySubEntity = new MySubEntity();

            Console.WriteLine(ent.MySubEntity.Id); // prints: '0';
            ctx.Entry(ent);
            Console.WriteLine(ent.MySubEntity.Id); // prints: '-2147482646';
        }

        static void Repro_Setup(DbContextOptions<MyContext> opts)
        {
            var ctx = new MyContext(opts);
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            ctx.Add(new MyEntity() { MySubEntity = new MySubEntity() });
            ctx.SaveChanges();
        }
    }

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<MyEntity>();
            modelBuilder.Entity<MySubEntity>();
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public MySubEntity MySubEntity { get; set; }
    }

    public class MySubEntity
    {
        public int Id { get; set; }
    }
}
```

**Comment by nphmuller** [comment]
Looks like it's caused by `ChangeTracker.DetectChanges()` which `dbContext.Entry()` calls internally.

**Comment by smitpatel** [comment]
That is just some temporary value change tracker assigns to newly added entities before it can get the actual database-generated value, which would be generated when you call SaveChanges.
Is there any issue with that -ve number?

**Comment by nphmuller** [comment]
My main problem is that it’s undocumented.
Because it’s undocumented and it’s uncommon behaviour, it looks like something big went wrong.

It also looks like int.MinValue, but it's not exactly the same value. Which also peaked my curiosity.

I ran into it when I was debugging another issue and it steered me into a totally wrong direction which cost me a lot of time.

There's probably a technical reason it's hard, but why not leave it simply as the default value (0)?

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties#value-generated-on-add

**Comment by nphmuller** [comment]
Thanks, that helps a lot.

I still think it's pretty confusing behaviour, but that might be just me. 
Especially since the InMemory provider just keeps the value at 0.

Would it be handy to keep this issue open, to see if other people run into the same issue? Or might I as well close it?

**Comment by ajcvickers** [comment]
See also ##12378
