### ISSUE TITLE
Interpolated string in ExecuteSqlCommand do not work as expected

### ISSUE THREAD

**Issue by bobvandevijver** [dotnet/efcore#14097]
So, I experience this interesting behaviour when using an interpolated string with the `ExecuteRawSql` method, but also when using the parameter classes.

Case: I want to disabled the checks, remove all data and re-enable all checks for a mssql database (used for testing). 

Below is the code that currently works (with only the first of the required three queries per table):
```c#
var tables = dbContext.Model
                      .GetEntityTypes()
                      .Select(r => $"{r.Relational().Schema}.{r.Relational().TableName}")
                      .ToImmutableList();

foreach (var table in tables)
{
    dbContext.Database.ExecuteSqlCommand($"ALTER TABLE {table} NOCHECK CONSTRAINT all", table);
}
```

As you can see, I provide the `entityType` twice to the `ExecuteSqlCommand`. I've tried omitting it, or using any of the other possibilities I've found online, but result vary. See below:

```c#
// Works, double param
dbContext.Database.ExecuteSqlCommand($"ALTER TABLE {table} NOCHECK CONSTRAINT all", table);

// Works, it seems that the parameter is ignored
dbContext.Database.ExecuteSqlCommand($"ALTER TABLE {table} NOCHECK CONSTRAINT all", "RandomValue");

// Does not work 
// System.Data.SqlClient.SqlException : Incorrect syntax near '@p0'.
dbContext.Database.ExecuteSqlCommand($"ALTER TABLE {table} NOCHECK CONSTRAINT all");

// Does not work (no interpolated string) 
// System.Data.SqlClient.SqlException : Incorrect syntax near '@p0'.
dbContext.Database.ExecuteSqlCommand("ALTER TABLE {0} NOCHECK CONSTRAINT all", table);
// System.Data.SqlClient.SqlException : Incorrect syntax near '@table'.
dbContext.Database.ExecuteSqlCommand("ALTER TABLE @table NOCHECK CONSTRAINT all", table);

// Does not work (SqlParameter)
// System.Data.SqlClient.SqlException : Incorrect syntax near '@table'.
dbContext.Database.ExecuteSqlCommand("ALTER TABLE @table NOCHECK CONSTRAINT all", new SqlParameter("table", table));
dbContext.Database.ExecuteSqlCommand("ALTER TABLE @table NOCHECK CONSTRAINT all", new SqlParameter("@table", table));
dbContext.Database.ExecuteSqlCommand("ALTER TABLE @table NOCHECK CONSTRAINT all",
                                                     new SqlParameter("@table", SqlDbType.Char) {Value = table});
// System.FormatException : Input string was not in a correct format.
dbContext.Database.ExecuteSqlCommand("ALTER TABLE {@table} NOCHECK CONSTRAINT all",
                                                     new SqlParameter("@table", SqlDbType.Char) {Value = table});
```

What am I missing?

I see that 2.2 has just been released, so I will check what that does.

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOS
IDE: Rider 2018.2

**Comment by ajcvickers** [comment]
@bobvandevijver It's not 100% clear to me what your expectations are, but two important points are:
* SQL does not allow parameterizing the table name in the query. (At least, not without tricks.)
* String interpolation with this method attempts to create parameterized queries.

The API here is planned to change in 3.0, which might make it easier to understand what is happening. See #10996

**Comment by bobvandevijver** [comment]
Right, I missed this parts:
> SQL does not allow parameterizing the table name in the query. (At least, not without tricks.)

That explains the behavior, thank you!
