### ISSUE TITLE
iOS: Upgrade to 2.2.0 from 2.1.3, ArgumentNullException in SqliteDateTimeAddTranslator

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/efcore#14091]
Upgraded my app from EFCore/SQLite from 2.1.3 to 2.2.0 and started receiving this exception only on iOS. No issue on Android.

```
Exception message:
SIGABRT: Value cannot be null. Parameter name: key

Stack trace:
Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior)
Dictionary`2[TKey,TValue].Add (TKey key, TValue value)
Microsoft.EntityFrameworkCore.Sqlite.Query.ExpressionTranslators.Internal.SqliteDateTimeAddTranslator..ctor () <0x1067d3880 + 0x0027f> in <abab8e3bcaf9438797d0f28bf5240ca8#a9ae3f789dc7e3a91b6b3bd037156472>:0
Microsoft.EntityFrameworkCore.Sqlite.Query.ExpressionTranslators.Internal.SqliteCompositeMethodCallTranslator..cctor () <0x1067d2990 + 0x0007b> in <abab8e3bcaf9438797d0f28bf5240ca8#a9ae3f789dc7e3a91b6b3bd037156472>:0


(wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
<series of generic calls like CallSiteRuntimeResolver.Resolve and CallSiteVisitor`2[TArgument,TResult].VisitCallSite>
DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope)
ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope)
ServiceProviderEngineScope.GetService (System.Type serviceType)
ServiceProviderServiceExtensions.GetRequiredService (System.IServiceProvider provider, System.Type serviceType)
ServiceProviderServiceExtensions.GetRequiredService[T] (System.IServiceProvider provider)
DbContext.get_DbContextDependencies ()
DbContext.get_InternalServiceProvider ()
IServiceProvider>.get_Instance ()
IServiceProvider>.get_Instance ()
RelationalDatabaseFacadeExtensions.GetRelationalService[TService] (Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure`1[T] databaseFacade)
RelationalDatabaseFacadeExtensions.Migrate (Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade databaseFacade)

```

### Steps to reproduce
Unknown

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: iOS 12
IDE: Visual Studio 2017 15.9.3

**Comment by jcmanke** [comment]
I'm getting this as well, probably worth noting it only occurs with linking turned on.

**Comment by jcmanke** [comment]
Looks like the issue is [here](https://github.com/aspnet/EntityFrameworkCore/blob/c2bc344e41c72942312072a8f21bdd7817a119ee/src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteDateTimeAddTranslator.cs#L29), with the `DateTime.AddX()` methods being linked out, thereby resulting in an attempt to add a value to the dictionary with a null `MethodInfo` key. 

I worked around it by adding this line of code in my iOS project: `var preserveDateTimeMethods = DateTime.Now.AddYears(1).AddMonths(1).AddDays(1).AddHours(1).AddMinutes(1).AddSeconds(1);`

**Comment by BioTurboNick** [comment]
I suppose the Linker just isn't aware of nameof() references?

**Comment by tipa** [comment]
I also experience this issue on Android, the given workaround works

**Comment by rajathiraja008** [comment]
I am also getting the same issue in Xamarin forms iOS

@jcmanke @tipa  can anyone explain to me how you workaround..?

**Comment by BioTurboNick** [comment]
@rajathiraja008 - Add the code @jcmanke mentioned somewhere in your project. A good spot is in the main application class. you can specify a function "SqliteDateCrashFix()" or something, stick that inside, and then call this function from the startup code. That way it'll be easy to remove when it is no longer needed and you'll remember why you put it in.
