### ISSUE TITLE
Invalid Assert in a couple tests in RelationalTypeMappingTest

### ISSUE THREAD

**Issue by MaxG117** [dotnet/efcore#14109]
This may be a regression from #13306 / #11591. The lines:
    `Assert.Equal(5, parameter.Size);`
do not make sense in Can_create_required_string_parameter and Can_create_string_parameter (in test\EFCore.Relational.Tests\Storage\RelationalTypeMappingTest.cs).

The tests create a StringTypeMapping, then create a DbParameter, and expect that parameter's Size to equal the length of the string value given to CreateParameter(). As far as I can tell, the StringTypeMapping implementation does not set the parameter Size. EF-provider-specific implementations of string type mappings set the Size in their ConfigurreParameter() overrides. However, our Database Provider does not require the parameter Size to be set for string types, so our EF provider does not set it. Therefore:

1) The aforementioned Assert statement is invalid and should be removed.
2) Both tests should be made virtual, so EF providers can override them.

Thanks.

**Comment by MaxG117** [comment]
When I'm talking about a Database Provider, I'm referring to the ADO.NET provider, not an Entity Framework Data Provider. Please let me know if I'm not using the correct terminology here.

I described two problems above. For the first problem, here's the relevant code in the unit test:

```
var parameter = new StringTypeMapping("nvarchar(23)", DbType.String, unicode: true, size: 23)
    .CreateParameter(command, "Name", "Value", nullable: true);
...
Assert.Equal(5, parameter.Size);
```

Prior to #11591 I would have expected parameter size to be 23. But now RelationalTypeMapping does not set the parameter size, and StringTypeMapping does not set the parameter size, why does the test expect parameter size to equal 5? The RelationalTypeMapping.CreateParameter method invokes the Database Provider's own DbCommand.CreateParameter method, which is not required to set the parameter size based on the length of the string value.

For the second problem (make the aforementioned tests `virtual`):
> Typically providers do not use these tests directly, but rather override the functional specification tests... Is there a reason you're running these tests?

SqliteTypeMappingTest and SqlServerTypeMappingTest beg to differ. I do not see anything in the functional specification tests that perform the same kind of testing for type mappings. Most tests in RelationalTypeMappingTest are virtual, the two tests I mentioned are not.

**Comment by MaxG117** [comment]
Thanks for those pointers. It'll take me some time to review BuiltinDataTypeTestBase in detail. From first glance I don't see that it covers the same scenarios as RelationalTypeMappingTest. For example, I do not see a functional test that generates a byte array literal. There may not even be a way to use a byte array literal, I just know that other providers implemented it, so I did also, and I wanted to be able to test it.

**Comment by ajcvickers** [comment]
We're not going to proactively remove these tests.
