### ISSUE TITLE
Scaffolded db context's OnModelCreating doesn't call base class

### ISSUE THREAD

**Issue by neville-nazerane** [dotnet/efcore#14111]
When scaffolding an existing database into an mvc project, I noticed the `OnModelCreating` function doesn't contain the line `base.OnModelCreating(modelBuilder)` to call the base function. It seems to create confusions such as this: https://stackoverflow.com/q/53657924/991609

**Comment by ajcvickers** [comment]
@neville-nazerane This is by-design. OnModelCreating is a "pure" template method, so there is no need to call the DbContext implementation of it. If you derive from another type that may have code there, then calling it on that type usually makes sense, but that's a different scenario.
