### ISSUE TITLE
System.InvalidCastException: 'Unable to cast object of type 'System.Byte[]' to type 'System.String'.'

### ISSUE THREAD

**Issue by jitendrajadav** [dotnet/efcore#14112]
### Describe the bug
I have a model in my WEB API like below : 
```C#
public class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
    }
```

and table of my SQL server is bellow:
```sql
TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [varbinary](max) NULL,
	[PasswordSalt] [nvarchar](max) NULL,
	[IsActive] [tinyint] NOT NULL
```

Now I am using EFCore in Asp.net core Web API

while fetching data is is throwing me error like :

`System.InvalidCastException: 'Unable to cast object of type 'System.Byte[]' to type 'System.String'.'`

My DataContext is here:

```C#
public class DataContext : DbContext
    {
        public virtual DbSet<User> User { get; set; }

        public DataContext(DbContextOptions<DataContext> options) : base(options) { }

    }
```

please let me know what is going wrong here?

I am able to put data into my SQL server user table but while fetching data I am getting this error

### To Reproduce
1. Using this version of ASP.NET Core '2.1.'
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
It should not throw error 

### Screenshots
<img width="960" alt="untitled1" src="https://user-images.githubusercontent.com/1029026/49633447-5a41ec00-fa1f-11e8-9b5b-02bf84053592.png">

**Comment by ajcvickers** [comment]
@jitendrajadav The `PasswordSalt` column is a string type in the database:
```sql
[PasswordSalt] [nvarchar](max) NULL,
```
But the property in the entity type is not a string type:
```C#
public byte[] PasswordSalt { get; set; }
```

You'll need to either map the column to a string, or use a [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) to convert from a string to whatever bytes you need.
