### ISSUE TITLE
OwnsMany cannot use HasQueryFilter

### ISSUE THREAD

**Issue by jasonycw** [dotnet/efcore#14113]
We are in the progress of trying to upgrading to use EF Core 2.2
And found that OwnsMany have some restriction.

### Steps to reproduce
Example:

Models
``` C#
public class User
{
    public Guid UserId { get; set; }
    public string Email { get; set; }
    public IEnumerable<Profile> Profiles { get; set; }
}
public class Profile
{
    public Guid ProfileId { get; set; }
    public string Email { get; set; }
    public bool IsActive { get; set; }
}
```
DbContext
``` C#
protected override void OnModelCreating(ModelBuilder builder)
{
    #region User
    builder.Entity<User>(m =>
    {
        #region Mappings
        m.ToTable("User", "user");
        m.HasKey(x => x.UserId);

        m.OwnsMany(x => x.Profiles, b =>
        {
            b.HasForeignKey(p => p.Email);
            b.HasPrincipalKey(u => u.Email);
        });
        #endregion
    });

    builder.Entity<Profile>(m =>
    {
        #region Mappings
        m.ToTable("Profile", "user");
        m.HasKey(x => x.ProfileId);
        m.HasQueryFilter(x => x.IsActive);
        #endregion
    });
    #endregion
}
```

In this case, `HasQueryFilter` will work properly and only `IsActive` Profile being queried when I call this:
``` C#
_dbContext.Set<User>().Include(u => u.Profiles)
```

However, when I want to simplify the OwnsMany relationship so no need to define `Entity<Profile>` specificly

This will not work
``` C#
protected override void OnModelCreating(ModelBuilder builder)
{
    #region User
    builder.Entity<User>(m =>
    {
        #region Mappings
        m.ToTable("User", "user");
        m.HasKey(x => x.UserId);

        m.OwnsMany(x => x.Profiles, b =>
        {
            b.ToTable("Profile", "user");
            b.HasKey(x => x.ProfileId);
            b.HasQueryFilter(x => x.IsActive);
            b.HasForeignKey(p => p.Email);
            b.HasPrincipalKey(u => u.Email);
        });
        #endregion
    });
    #endregion
}
```
As `CollectionOwnershipBuilder` do not have `HasQueryFilter`

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017 15.9.3

**Comment by ajcvickers** [comment]
@jasonycw Can you give us some insights on why defining a filter on an owned type makes sense and how it would be used?

**Comment by jasonycw** [comment]
@ajcvickers In our case, we don't need to change an inactive profile, every time we query the User, only Active profiles are needed to be retrieved. Also for update, we don't delete the records, just update it to inactive.

Before we try `OwnsMany`, we were using `.HasMany(u => u.Profile).WithOne()` and Add `HasQueryFilter(x => x.IsActive)` for the Profile entity. 
``` C#
protected override void OnModelCreating(ModelBuilder builder)
{
    #region User
    builder.Entity<User>(m =>
    {
        #region Mappings
        m.ToTable("User", "user");
        m.HasKey(x => x.UserId);

        m.HasMany(x => x.Profiles)
           .WithOne()
           .HasForeignKey(p => p.Email)
           .HasPrincipalKey(u => u.Email);
        #endregion
    });

    builder.Entity<Profile>(m =>
    {
        #region Mappings
        m.ToTable("Profile", "user");
        m.HasKey(x => x.ProfileId);
        m.HasQueryFilter(x => x.IsActive);
        #endregion
    });
    #endregion
}
```

And when change to `OwnsMany`, we tried to move all the config to `OwnsMany` but seems `HasQueryFilter` is missing from `CollectionOwnershipBuilder`

**Comment by ajcvickers** [comment]
@jasonycw Or, perhaps, more simply, what is your conception of what an "owned collection" is and what it is for? (We're really interested in getting this kind of information because it helps us create useful features will well-defined semantics.)

**Comment by jasonycw** [comment]
@ajcvickers We were trying to unify all the one to many relationship with OwnsMany so no need to have some property using `HasMany WithOne` and some `OwnsMany`

e.g. 
User may has multiple one to many relationship, like Roles, Profiles, etc and we try to make use OwnsMany for all of them.
By grouping all these relationships to `Owns___` we can get rid of defining Entity that are only owned by others. So `builder.Entity<User>` can contain all the information of the owned entity in one place.

Some entity is pretty easy to migrate from `HasMany WithOne` to `OwnsMany` as they don't have much filtering or login going on. However, in the Profile case, we need the logic to filter the active status and this is not achievable  without defining `builder.Entity<Profile>` explicitly

**Comment by ajcvickers** [comment]
@jasonycw So is the key part this, "By grouping all these relationships to Owns___ we can get rid of defining Entity that are only owned by others. So builder.Entity<User> can contain all the information of the owned entity in one place?" Which if I understand you correctly means you see the "Owns___" APIs as a way to consolidate model building code for an entity and its dependencies into one place?

**Comment by jasonycw** [comment]
@ajcvickers Yes, and also, we think `Owns___` APIs can allow us to query the data without the need to .Include child entities, and it also handles cascade delete and edit

**Comment by smitpatel** [comment]
> By grouping all these relationships to Owns___ we can get rid of defining Entity that are only owned by others. So builder.Entity<User> can contain all the information of the owned entity in one place.

If that is true, then why would owned entities need query filters? Shouldn't that information be also stored in User entity?

**Comment by divega** [comment]
After discussing this with @AndriySvyryd, and reading a bit online about this kind of scenario in the context of DDD, here are my thoughts:

1. TL;DR: I don't think we *need* to decide anything for 3.0 here, so adding propose-punt label.

2. Aggregates that are too large as to need filtering are a smell. If we want ownership/aggregates to become a pit of success feature, an API that steers customers to design smaller aggregates may help.  

3. On the other hand, it is ok to have useful lower-level features that allow customers to do more advanced things, plus not all our customers want to necessary become DDD practitioners. Both rule-based eager loading and query filters are such low-level features. 

4. Precisely because query filters is one of those low-level feature for which it is ok to not always result on consistent behaviors (a well-know example of inconsistency happens when you load a dependent of a principal that has been filtered out: you get dependent with a dangling FK value, but no apparent principal object), I don't want us to take a dogmatic position and say now that we never want to allow this. I prefer to wait for feedback. 

4. I think if we end up enabling query filters for owned objects and then that doesn't work with document oriented database, that is still all right. It is just a consequence of restrictions in the query capabilities of the database (e.g. one full document at the time).

**Comment by farlop** [comment]
Any update for QueryFilter being implemented in owned entities in near future or in EF Core 5.0?

**Comment by AndriySvyryd** [comment]
@farlop Why do you need this? If it's for soft deletes then #19695 will provide a better experience.

**Comment by farlop** [comment]
@AndriySvyryd yes it's related to soft-deletes, but my issue is about EF retrieving from DB owned entities that have been soft-deleted.

For example, consider having an _Order_ with three _OrderDetails_, one of them soft-deleted. A simple query for obtaining the _Order_ would always retrieve from database all three _OrderDetails_, ignoring the QueryFilter established for _OrderDetails_.

**Comment by Palpie** [comment]
In EF Core 5.0 I get this warning (I changed to entity names to match :

```
Warning: Entity 'Blog' has a global query filter defined and is the required end of a relationship
with the entity 'Post'. This may lead to unexpected results when the required entity is
filtered out. Either configure the navigation as optional, or define matching query filters for both entities
in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
```

If the configuration is like this:

```
modelBuilder.Entity<Blog>().HasMany(b => b.Posts).WithOne(p => p.Blog).IsRequired(false);
modelBuilder.Entity<Blog>().HasQueryFilter(b => b.Url.Contains("fish"));
```

One solution is to add:

```
modelBuilder.Entity<Post>().HasQueryFilter(p => p.Blog.Url.Contains("fish"));
```

But if Blob owns Post I cannot use HasQueryFilter on Post.
