### ISSUE TITLE
null GUID value in EF2.2 gives unexpected null error

### ISSUE THREAD

**Issue by bnemetchek** [dotnet/efcore#14117]
An exception occurred while reading a database value for property 'Portal.ConnectionId'. The expected type was 'System.Nullable`1[System.Guid]' but the actual value was null.

This was working in EF2.1 but failing in EF2.2.  How is it an error that a null value retrieved for a nullable GUID column is null?
```

### Further technical details
EF Core version: (EF2.2)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win10
IDE: (e.g. Visual Studio 2017 15.9.3)

**Comment by ajcvickers** [comment]
@bnemetchek This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by bnemetchek** [comment]
This looks like a WAD.  In the primary entity, a FK id was marked as nullable, but the nav property was described as IsRequired().  This is a conflict and I think the error, while not entirely useful, is correct.

**Comment by ajcvickers** [comment]
@bnemetchek If this is a regression from 2.1 to 2.2, it would be really great if you could provide a simple repro for it.

**Comment by bnemetchek** [comment]
I don't think it's a regression.  It seems to me it's an improvement because EF2.1 did not catch this inconsistency where it is now being detected.
