### ISSUE TITLE
Breaking change for DbQuery<> in 2.2

### ISSUE THREAD

**Issue by searus** [dotnet/efcore#14139]
The way that `.Include()` on `DbQuery<>` is handled has changed from 2.1 to 2.2 and is a breaking change for me.

I have created a demo repository here: https://github.com/reyno/efcore-2.2-issue

### Steps to reproduce

1. Update the .csproj to use the 2.1.4 version of the 2 pacakges
2. Create the database with `dotnet ef database update`
3. Run the app with `dotnet run`

The SQL that is generated is as follows:
```
SELECT [p].[Id], [p].[AddressId], [p].[Name], [p.Address].[Id], [p.Address].[Line1]
FROM (

    SELECT  *
    FROM People
                    
) AS [p]
LEFT JOIN [Addresses] AS [p.Address] ON [p].[AddressId] = [p.Address].[Id]
```
This is correct.

Now update the .csproj to the latest 2.2.0 version and run with `dotnet run`.  The SQL generated is as follows:
```
SELECT [p].[Id], [p].[Name], [p.Address].[Id], [p.Address].[Line1]
FROM (

    SELECT  *
    FROM People
                    
) AS [p]
INNER JOIN [Addresses] AS [p.Address] ON [p].[Id] = [p.Address].[Id]
```

Note that the JOIN is now incorrect as it does not join on `AddressId` from the `People` table.

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: n/a
IDE: n/a

**Comment by smitpatel** [comment]
This could be change in model building

**Comment by searus** [comment]
Is it something I can work around using the Model Builder?

**Comment by searus** [comment]
Thanks @smitpatel, you're a star !  I'm back in action 👍

**Comment by ajcvickers** [comment]
@searus Can I ask Smit's question again? "What is the purpose of `PeopleWithAddressView.Id`?" Did you intend it to be the PK, FK, or neither? (This is useful to know when considering if our conventions are doing the right thing.)
