### ISSUE TITLE
The property 'Entity.Location' is of an interface type ('IPoint'). If it is a navigation property manually configure the relationship for this property by casting it to a mapped entity type, otherwise ignore the property using the NotMappedAttribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

### ISSUE THREAD

**Issue by KyleTraynor** [dotnet/efcore#14135]
Problem: Using `Point `as described here https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-entity-framework-core-2-2/ with EF Core 2.2 causes this error:

> System.InvalidOperationException: The property 'Point.Boundary' is of an interface type ('IGeometry'). If it is a navigation property manually configure the relationship for this property by casting it to a mapped entity type, otherwise ignore the property using the NotMappedAttribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

Reproduction Steps:
Step 1) create a new ASP.NET Core Web Application project

Step 2) Add `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` 2.2.0 through nuget.

Step 3) Change `ApplicationDbContext.cs` to look like this:

```
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using NetTopologySuite.Geometries;
using System.IO;

namespace WebApplication1.Data
{
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
         
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                IConfigurationRoot configuration = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json")
                   .Build();
                var connectionString = configuration.GetConnectionString("DefaultConnection");
                optionsBuilder.UseSqlServer(connectionString, opts => opts.UseNetTopologySuite());
            }
        }
        public DbSet<Test> Tests { get; set; }
    }


    public class Test
    {
        public int Id { get; set; }
        public Point Location { get; set; }
    }
}

```

Step 4: In Package Manager Console, run `add-migration test`

This will produce the following error:
`System.InvalidOperationException: The property 'Point.Boundary' is of an interface type ('IGeometry'). If it is a navigation property manually configure the relationship for this property by casting it to a mapped entity type, otherwise ignore the property using the NotMappedAttribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

This is on EF Core 2.2.0 & .net core 2.2

**Comment by smitpatel** [comment]
Did you add call to `UseNetTopologySuite` when registering connection string?

**Comment by ajcvickers** [comment]
@KyleTraynor To add to @smitpatel's comment, documentation for spatial is here: https://docs.microsoft.com/en-us/ef/core/modeling/spatial

@divega It might help to explicitly mention this in the blog, but I understand we don't want everything in the blog.

**Comment by KyleTraynor** [comment]
@smitpatel  and @ajcvickers  Sorry, I forgot to include that when I was making my smaller sample, but this error happens even with UseNetTopologySuite(). I've updated my original post.

**Comment by KyleTraynor** [comment]
Yikes - Sorry. If I take out the  if (!optionsBuilder.IsConfigured), it seems to work. There goes a couple hours of banging my head.

**Comment by incredible-India** [comment]
The NotMapped attribute is used to specify that an entity or property is not to be mapped to a table or column in the database. In the following example, the AuditLog class will not be mapped to a table in the database:

public class Contact
{
    public int ContactId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; } 
    public AuditLog AuditLog { get; set; }
}
[NotMapped]
public class AuditLog
{
    public int EntityId { get; set; }
    public int UserId { get; set; }
    public DateTime Modified { get; set; }
}
