### ISSUE TITLE
Request for information to Xamarin implementation 122018

### ISSUE THREAD

**Issue by waltergrimmvie** [dotnet/efcore#14137]
HI, 

I AM JUST the avarage grunk looking for information,  the MS Xamarin page lead me to the sqlite pcl, and they sent me here.

I am perusing the chance to implement a sqlite solution in Xamarin Form cross solution with near ado function, where I  build my sql statement and process command, receive select dataset etc, 

I also could not find any solution here, nor a sample, just some messages from 2017

Can anyone help me how to solve xamforms cross platform sqlite with a ado equivalent method,

Thanx

**Comment by ajcvickers** [comment]
@waltergrimmvie Assuming that you are asking about the [Microsoft.Data.Sqlite ADO.NET provider for SQLite](https://www.nuget.org/packages/Microsoft.Data.SQLite/), then yes this will allow you to use native SQLite cross-platform with an ADO.NET programming model.
