### ISSUE TITLE
Porting an EF 6 library to EF Core

### ISSUE THREAD

**Issue by figuerres** [dotnet/efcore#14130]
Question:   what are the guidelines for an EF 6 Model class library project to move to EF Core ?
i found the microsoft doc pages at https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code
and i do not see them listing any kind of details about what to look at before you start, no mentaion of what might be a problem area. no mention of any known issues with switching.
the only thing it says is to chnage the namespace
slightly more is said here:
https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/ensure-requirements

is that it ?  no other issues ?  no other details ?

I am looking at move to core in the near future and looking for information to help *before* i start editing code or installing packages.

**Comment by Vasimovic** [comment]
> s that it ? no other issues ? 

For us the biggest issue so far is #14063, the missing function is hard to replace, perhaps if you do not utilize the SqlQuery function in EF 6 you should be okay, EF Core is much more capable then EF 6 - IMHO

**Comment by ajcvickers** [comment]
@figuerres Agreed that it would be good to have better documentation here--I filed https://github.com/aspnet/EntityFramework.Docs/issues/1180. I can't make any guarantees when it will be worked on since we don't currently have any resources (other than the dev team) to write docs.
