### ISSUE TITLE
Support loading recursive relationships to any depth

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#14144]
I have table like this

ModelA

ID | ParentID
-- | --
1 | NULL
2 | 1
3 | 2
4 | 3
5 | 4

```C#
public partial class Model A
{
    public int ID {get;set;}
    public ParentID? {get;set}
    [ForeignKey("ID")]
    public ModelA Parent {get;set;}
}
```
I can get Parent navigation property populated by doing

var obj = `_context.ModelA.Include(x=>x.Parent).Single(x=>x.ID == 5);`

but the obj.Parent.Parent will be null unless I do

var obj = `_context.ModelA.Include(x=>x.Parent).ThenInclude(x=>x.Parent))Single(x=>x.ID == 5);`

the issue is for any entity, there could be X amount of nested navigation property until the actual ParentID is null. I cannot hard code the ThenInclude for derived type.

var obj = `_context.ModelA.Include(x=>x.Parent).ThenInclude(x=>x.Parent))...(N amount of ThenInclude)...Single(x=>x.ID == N);`

Also I do not wish to use lazy loading to solve this issue.

**Comment by smitpatel** [comment]
Can you write a SQL to load all data in single query?

**Comment by Lfwinster** [comment]
Yes I can, but in my case i need to figure out, when given an ID, all its ancestors and navigate through the nav properties

**Comment by smitpatel** [comment]
@Lfwinster - I am asking you to provide a SQL. If it cannot be expression in SQL then it cannot be done in LINQ either. The issue in linq/SQL both you face is, you don't know how many times you have to do join. If you have a clever way to do it in SQL, we can think about how to support it in linq.

**Comment by sdanyliv** [comment]
@smitpatel, it is easily doeable by recursive common table expression (CTE), which supported by many database engines.
```sql
with hierarchy_up (id, parentd_id)
as
(
    select id, parent_id from model_a
    where id = 5
    union all
    select parent.id, parent.parent_id 
    from hierarchy_up h
    inner join model_a parent on parent.id = h.parent_id
)
select * from hierarchy_up
```

**Comment by Lfwinster** [comment]
does that mean Lazy loading is not translating the LINQ into the recursive CTE that @sdanyliv  mentioned but rather into multiple sql queries based on how the navigation properties are being consumed

**Comment by ajcvickers** [comment]
Putting this on the backlog to consider implementing in the future.

@Lfwinster Two workarounds for now are:
* Load all entities of type `ModelA` into the context; all parent/children navigation properties will be fixed up.
* Decide an acceptable depth to go to and add Include/ThenInclude/ThenInclude/etc. up to that depth.

**Comment by Lfwinster** [comment]
> Putting this on the backlog to consider implementing in the future.
> 
> @Lfwinster Two workarounds for now are:
> 
> * Load all entities of type `ModelA` into the context; all parent/children navigation properties will be fixed up.
> * Decide an acceptable depth to go to and add Include/ThenInclude/ThenInclude/etc. up to that depth.

Thanks @ajcvickers , I have considered taking the first work around until this is implemented.

**Comment by tnlthanzeel** [comment]
@ajcvickers , when will this be available?

**Comment by ajcvickers** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 6.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Please vote (👍) for this issue if it is important to you.

**Comment by tnlthanzeel** [comment]
> This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 6.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Please vote (👍) for this issue if it is important to you.

noted! thanks for the reply

**Comment by ajcvickers** [comment]
Note from triage: we do not plan to add direct support for this.
