### ISSUE TITLE
DbContext pooling breaks resolving other scoped services

### ISSUE THREAD

**Issue by daniel-white** [dotnet/efcore#14169]
When using a `DbContext` pool, the service provider isn't correctly resolving other scoped services. I'm not sure if is a limitation of EF or the .NET Core DI.

My use case is this. I have a user context service that is scoped to a ASP.NET Core request. I'd like to resolve some information from the request into my `DbContext`. Hence, I registered my service as scoped. When I use `AddDbContextPool`, it resolves a new copy of my user context service. This example below illustrates that a new scope is created somewhere.

### Steps to reproduce

```c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;

namespace ScopeTest
{
    class Program
    {
        static void Main(string[] args)
        {
            RunPooled();
            RunUnpooled();
        }

        static void RunUnpooled()
        {
            IServiceCollection serviceCollection = new ServiceCollection();
            serviceCollection.AddScoped<ConsoleService>();
            serviceCollection.AddDbContext<MyDbContext>(o => { o.UseInMemoryDatabase("ScopeTest"); });
            IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();
            Run(serviceProvider, "Unpooled");
        }

        static void RunPooled()
        {
            IServiceCollection serviceCollection = new ServiceCollection();
            serviceCollection.AddScoped<ConsoleService>();
            serviceCollection.AddDbContextPool<MyDbContext>(o => { o.UseInMemoryDatabase("ScopeTest"); });
            IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();
            Run(serviceProvider, "Pooled");
        }

        static void Run(IServiceProvider serviceProvider, string mode)
        {
            using (var scope = serviceProvider.CreateScope())
            {
                ConsoleService consoleService = scope.ServiceProvider.GetRequiredService<ConsoleService>();
                consoleService.Format = mode + ": {0}";
                MyDbContext dbContext = scope.ServiceProvider.GetRequiredService<MyDbContext>();
                dbContext.DoSomething();
            }
        }
    }

    class ConsoleService
    {
        public string Format { get; set; } = "{0}";
        public void WriteLine(string message)
        {
            Console.WriteLine(Format, message);
        }
    }

    class Entity
    {
        public int EntityId { get; set; }
        public string Name { get; set; }
    }

    class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        { }

        public DbSet<Entity> Entities { get; set; }

        public void DoSomething()
        {
            ConsoleService consoleService = this.GetService<ConsoleService>();
            consoleService.WriteLine("Hello from DbContext");
        }
    }
}
```

### Further technical details
EF Core version: 2.2.0 and 2.1
Database Provider: N/A, but Npgsql and InMemory
Operating system: Windows 10
IDE: Visual Studio 2017 15.9

**Comment by ajcvickers** [comment]
@daniel-white This is a known limitation of context pooling. Context pooling works by reusing the same context instance across requests. This means that it is effectively registered as a singleton in terms of the instance itself so that it is able to persist.

Context pooling is intended for scenarios where the context configuration, which includes services resolved, is fixed between requests. For cases where this needs to be changed, just don't use pooling. (Note that the performance gain from pooling is usually negligible accept in super-optimized scenarios. If you find that not to be the case, then we would love to see the code and the numbers.)

**Comment by daniel-white** [comment]
Thanks @ajcvickers. I figured as much when reading the code. Is this known limitation documented somewhere? 
I've looked at 
* https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#dbcontext-pooling
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontextpool?view=efcore-2.1

and there is no mention of this limitation.

**Comment by ajcvickers** [comment]
@daniel-white We should update the docs--could you file a docs bug for this?
