### ISSUE TITLE
Should Migration.Designer.cs and DbContextModelSnapshot.cs be under version control?

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#14167]
Those files are auto-generated. I often see people are pushing them to their repositories, what is your recommendation?

**Comment by ajcvickers** [comment]
@Sigvaard They should be checked in; the way migrations works requires they persist from when the tooling last generated them until some new migration is generated.

**Comment by gianAchei** [comment]
And what about now in 2025? It is still recommending to keep at git?

**Comment by roji** [comment]
@gianAchei what's your reason for asking, what changed in 2025?
