### ISSUE TITLE
Bring back the Oracle sample?

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#14175]
Inverse of #14119

**Comment by bricelam** [comment]
We should update the tests to read the connection string from configuration (like the SQL Server ones do). Then we can use a similar condition to skip running the tests unless a connection string is provided.

``` xml
<SkipTests Condition="'$(Test__Oracle__DefaultConnection)' == ''">True</SkipTests>
```

**Comment by bricelam** [comment]
For anyone following this issue, an [official EF Core provider from Oracle](https://www.oracle.com/technetwork/topics/dotnet/) is now available.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
