### ISSUE TITLE
Should the new evaluatable types be internal?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#14170]
3.0 introduces new non-ReLinq types for dealing with evaluatability: IEvaluatableExpressionFilter, EvaluatableExpressionFilterBase, EvaluatableExpressionFilter, RelationalEvaluatableExpressionFilter. These new types are in internal namespaces, although providers may need to use them to flag expressions as non-evaluatable. Npgsql certainly does this.

I know that the whole question of evaluatability design is being revisited, so these types may be a nothing more than a temporary step, in which case this issue can probably be disregarded and closed. Just making sure...

@smitpatel @ajcvickers @austindrenski

**Comment by smitpatel** [comment]
Everything new in query is inside internal namespace until API review at which point, we will make things non-internal as per provider needs. It's better to put things in internal and move out than the other way round.

**Comment by smitpatel** [comment]
@pmiddleton - #13722 #13862
