### ISSUE TITLE
Add TagWith overload that gets the filename and line number automatically

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#14176]
As suggested/used by Nick Craver.

**Comment by jzabroski** [comment]
> As suggested/used by Nick Craver

Are you referring to this tweet: https://twitter.com/Nick_Craver/status/1069999128082595847 ?

And this gist https://gist.github.com/NickCraver/c6f371bf8df37e05c4f09fd3c02ef6a2 ?

**Comment by ajcvickers** [comment]
@jzabroski Yes.

**Comment by michalczerwinski** [comment]
Is it something I can help with? 

Please confirm the approach:
* adding custom extension method TagWith 
* using [CallerFilePath]string fromFile = null, [CallerLineNumber]int onLine = 0 in the extension

What shall we call it? TagWithCallerInfo?

**Comment by ajcvickers** [comment]
@michalczerwinski Yes, that seems to be a reasonable approach. Naming is hard, but can this just be a new overload of TagWith rather getting a new name?

**Comment by michalczerwinski** [comment]
@ajcvickers: great! Will keep it as overload then.

**Comment by stevendarby** [comment]
Isn’t the usefulness of the caller attributes that they automatically set the optional parameters for you? As such, naming it `TagWith()` when passing no parameters reads slightly strangely to me.

**Comment by michalczerwinski** [comment]
@stevendarby: that's why I called it TagWithCallerInfo previously. But as @ajcvickers pointed out it's hard to call this method succinctly, so if you have better proposals?

**Comment by stevendarby** [comment]
@michalczerwinski I haven’t got a better suggestion than your previous one, which I thought was ok. Sorry to weigh in at this point, I just wondered if perhaps @ajcvickers’ suggestion was made without full realisation of how it reads when using the defaults (which is the main use case for this method). If that’s understood and `TagWith` is still preferred then so be it :)

**Comment by ajcvickers** [comment]
@michalczerwinski @stevendarby It doesn't really matter too much at this point since we have an API review process where we will look at all the names and possibly make changes then. Naming is hard; get the code changes done, and we can see what names works best later.
