### ISSUE TITLE
How does QueryContext.ParameterValues work?

### ISSUE THREAD

**Issue by joshmackey** [dotnet/efcore#14198]
I took the EFCore.Cosmo code and modified it to work with currently non-supported NoSQL db. For the most part, it works, but I'm trying to increase it's performance by handling the *where* queries in the db.

I see that the EFCore.Cosmo code calls `selectExpression.ToSqlQuery(queryContext.ParameterValues));` (DocumentQueryExpression.cs) during the execution and that the *ParameterValues* dictionary is used to populate the SQL parameters that were created during the analysis of the query. However, I cannot find where *ParameterValues* gets populated.

 I'm guessing that somewhere, some expressions are created that eventually are used to populating the *ParameterValues* dictionary at query execution time but I can't seem to find how this process works.

Any tips or docs on the matter?

**Comment by joshmackey** [comment]
Awesome, thanks for answering that.

Is there something similar for the join id?

**Comment by smitpatel** [comment]
What are you referring to with "join id"?

**Comment by joshmackey** [comment]
If my model has a foreign key and I call `.Include(...)` when I query it, it appears to be transformed into a JoinClause. As you said, the WhereClause has it's parameters extracted automatically, but what about the JoinClause?

**Comment by smitpatel** [comment]
Where clause was just an example. Every part of query expression tree goes to such processing to generate parameters out of parts of tree which are closure dependent. Also operators like Skip/Take which does not take lambda may have their args converted to parameters if they are not captured from closure.
