### ISSUE TITLE
Build initialize fails 

### ISSUE THREAD

**Issue by Bogatinov** [dotnet/efcore#1420]
For the first time I try `build initialize` in cmd as Administrator and it fails for these packages 

```
System.Text.RegularExpressions
System.Threading
System.Threading.Tasks
System.Collections.Immutable
System.Reflection.Metadata
```

So I try to manually install it with `Manage Nuget packages`. Now it displays why it can not locate these packages: "You are trying to install it to a project that targets .NETFramework, Version = 4.5.1, but the package does not contain any assembly references or content files that are compatible with that framework"

**Comment by rowanmiller** [comment]
May be related to some package source changes happening at the moment and just be a temporary issue.

**Comment by bricelam** [comment]
@Bogatinov What does your `%APPDATA%\NuGet\NuGet.Config` file look like?

**Comment by Bogatinov** [comment]
@bricelam like this
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources>
    <add key="nuget.org" value="true" />
  </disabledPackageSources>
  <activePackageSource>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
  </activePackageSource>
</configuration>
```

**Comment by bricelam** [comment]
Looks like you're hitting the infamous NuGet [Work Item 4397](https://nuget.codeplex.com/workitem/4397). Most of us work around it by adding a line similar to the following inside `packageSources`.
```XML
<add key="nuget.org.DoNotDisable" value="https://www.nuget.org/api/v2/" />
```

**Comment by Bogatinov** [comment]
@bricelam thanks, that worked. So if anyone has the same problem, it can look it up in this issue.
