### ISSUE TITLE
Simple GroupBy statement still evaluated locally

### ISSUE THREAD

**Issue by piotrkolodziej** [dotnet/efcore#14204]
Hello,

We've just upgraded to EF 2.2 and the only GroupBy statement, which so far had been evaluated locally, is still evaluated locally. Is this something you are aware of or should I create a separate solution for you? Please note that the produced Group By contrains not only integer but entity itself as part of GroupBy parameters.

```c#
return _context.StockOperations
    .Where(so => so.Date >= from.Date && so.Date <= to.Date)
    .GroupBy(so => so.ConsumableId)
    .ToList();

public class StockOperation : IAuditEntity
{
    public int StockOperationId { get; private set; }
    public DateTime Date { get; private set; }
    public decimal Quantity { get; private set; }
    public StockOperationType Type { get; private set; }

    public int ConsumableId { get; private set; }
    public int? OrderId { get; private set; }   
}
```

```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy([o].ConsumableId, [o])' could not be translated and will be evaluated locally.
```

```sql
SELECT so."StockOperationId", so."ConsumableId", so."CreatedAt", so."Date", so."OrderId", so."Quantity", so."Type", so."UpdatedAt"
FROM "StockOperation" AS so
WHERE (so."Date" >= @__from_Date_0) AND (so."Date" <= @__to_Date_1)
ORDER BY so."ConsumableId"
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Npgsql 2.2.0
Operating system: macos
IDE: VS Code / Rider

**Comment by smitpatel** [comment]
In order to generate grouping of `IGrouping<int, StockOperation>`, client eval is must. The SQL Group By only corresponds to when using some aggregate operation on the grouping to get a scalar value out of it. In other words, there is not other way to process above group by other than doing partial client eval like that.
