### ISSUE TITLE
EF Core 2.2 DbContext Properties<string> "missing"

### ISSUE THREAD

**Issue by douglassimaodev** [dotnet/efcore#14201]
I could not find a topic like that in here, if there is, sorry for that.

Here we go, On prev version like EF 6.0 we had the possibility to set a default column type
like:   //General Custom Context Properties
            builder.Properties<string>()
                .Configure(p => p.HasColumnType("nvarchar"));

and this would be applied for all fields of type string, where I can't find a similar way for Ef core

same for those options here:

 modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
            modelBuilder.Conventions.Remove<ManyToManyCascadeDeleteConvention>();
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

for now on what is the recommendation to try to get the same behavior in EF core 2/3.0?

**Comment by ajcvickers** [comment]
@douglassimaodev Basically, you can iterate over the model at the end of OnModelCreating and bulk set facets like this. There are some examples in #6787.
