### ISSUE TITLE
[Helix] SqlServer functional tests unable to connect to SqlServer

### ISSUE THREAD

**Issue by HaoK** [dotnet/efcore#14214]
The following tests require SqlServer to run.

EFCore.SqlServer.FunctionalTests 
EFCore.CrossStore.FunctionalTests

Currently they fail due to being unable to connect to SQLServer, @smitpatel mentioned there might be a related core-eng work issue, maybe this one? (https://github.com/dotnet/core-eng/issues/3659) and that the fix might just involve specifying the connection string as an environment variable

```
Failed   Microsoft.EntityFrameworkCore.ConfigurationPatternsTest.Can_register_multiple_context_types
Error Message:
 System.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 52 - Unable to locate a Local Database Runtime installation. Verify that SQL Server Express is properly installed and that the Local Database Runtime feature is enabled.)
---- System.ComponentModel.Win32Exception : The system cannot find the file specified
Stack Trace:
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)

```

Logs: https://mc.dot.net/#/user/dotnet-github-anon-kaonashi-bot/pr~2Faspnet~2Fefcore/ci/181218.01/workItem/EFCore.CrossStore.FunctionalTests-netcoreapp2.0/wilogs

Can repro via triggering new build of: https://github.com/aspnet/EntityFrameworkCore/pull/14174

**Comment by HaoK** [comment]
Note these tests appear to be skipped on ubuntu/OSX so for the purposes of this issue, Windows10 is the only queue that needs to work

**Comment by HaoK** [comment]
@ajcvickers this is the issue for helix + SqlServer

**Comment by ajcvickers** [comment]
Discussed this yesterday, and for now we're putting Helix on the back burner. Current C.I. and agents are working well; touch wood.
