### ISSUE TITLE
dotnet ef migrations script with SDK not on path failing

### ISSUE THREAD

**Issue by severisv** [dotnet/efcore#14225]
When trying to run `dotnet ef` commands using an SDK that is not on PATH, I get an error:

global.json:
```
{
  "sdk": {
    "version": "2.1.301"
  }
}
```

```
C:\projects\myproject>"C:\Users\sever\AppData\Local\Microsoft\dotnet\dotnet.exe" --list-sdks
2.1.301 [C:\Users\sever\AppData\Local\Microsoft\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.2.100 [C:\Program Files\dotnet\sdk]
```

```
C:\projects\myproject>"C:\Users\sever\AppData\Local\Microsoft\dotnet\dotnet.exe" ef migrations script -i -o "C:/artifacts/migrate-db.sql"

A compatible SDK version for global.json version: [2.1.301] from [C:\projects\thon\atlas.checkin\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
```

I'm running the commands from cmd on Windows 10.

When changing global.json to an SDK version that is on PATH everything works fine.

Running other commands such as build and restore using the SDK that is in my home folder works as expected.

**Comment by smitpatel** [comment]
`dotnet ef` tool itself invokes dotnet.exe file under the hood. Hence the SDK you want to use should be in PATH else command would fail. You can add SDK to path locally in cmd for the session and that would also work.

**Comment by ajcvickers** [comment]
Note from triage: we will not attempt any magic here.
