### ISSUE TITLE
Default initialization of HashSets in constructor is wasting memory

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#14249]
*Copy of issue from EF Core Power Tools* https://github.com/ErikEJ/EFCorePowerTools/issues/151

@tfd1973 wrote:

If you have a collection navigation property Blogs e.g. the tool will create initialization code in the constructor.

For small classes or limited use this poses no problem, but if you have a large database where you have a small number of tables on which data is centralized around, then you will end up with a few classes have a lot of collection navigation properties.

Querying data from these tables will end up in a lot of initialized HashSets which for most part all will end up not being used at all - these HashSets consume a vast amount of memory for no apparent reason.

Entity Framework Core is quite capable of functioning whit out that initialization, and I guess you have included it for convenience, so developer do not need to check for null when accessing these properties.

In our test database we have around 20000 people registered, and these have around 1-2 job entries and so on - what ever these people do or participate in are linked to the person table which result in over 100 collection navigation properties on that class and other classes might of course also have a few such properties.

If I query all persons I will end up with 20000 person entities all with around 100 initialized HashSets which is never used. Practically speaking this is memory wise translated into 500 Mb - without the initialization it’s only a 50 Mb footprint.

_Will it be possible to have an option to generate these as commented out or removed entirely?_

We had the same problem with Linq2Sql and made these properties using this pattern with a backing field (for convenience) which would translate to Entity Framework Core like this:

private HashSet<Blog> _blogs;
public ICollection<Blog> Blogs 
{
    get => _blogs ?? (_blogs = new HashSet<Blog>());
    set => _blogs = value;
}

Great tool and thanks for making it :)

**Comment by smitpatel** [comment]
Related #4038

**Comment by ErikEJ** [comment]
@smitpatel But do you think having this option could be useful?

**Comment by smitpatel** [comment]
Having option could be useful but too many options and users have to make decision on what to choose for the option value. I think in past for quite a few useful things we have deferred to templates. Also if you delete the initialization code then EF Core would still work fine.

**Comment by ErikEJ** [comment]
I will refer the user to the Handlebars templates
