### ISSUE TITLE
Custom extension with debug info out value

### ISSUE THREAD

**Issue by SteffenMangold** [dotnet/efcore#14244]
Is it possible to define a `SequenceTypePreservingResultOperatorBase` query extension, that return debug information, like an out value?

Something like

```c#
myContext
    .Where(d => d.ID == 1)
    .MyExtention("Parameter1", out DebugInfo debugInfo)
    .ToList();

var info = debugInfo.SomeInfo;
```

### Further technical details
EF Core version: 2.2.0
Database Provider: any

**Comment by smitpatel** [comment]
To answer the particular question:
`ResultOperatorBase` is coming from Relinq library. If you can make it work in current code base then you can do it. If you cannot then you have to wait for next version for EF Core to make changes to support it. But in next version we are removing Relinq altogether. So there will not be any ResultOperator.

Broadening the scope of the request - If you are looking for some custom queryable operator, then can you elaborate more on what `MyExtension` method is, what are the args, and what do you want to send out in out parameter.

Queryable extension methods are also few different variety like ones which changes query result and requires translation to server. Or ones which would be certain markers and requires special processing at client side but no changes to server translation. Or just marker ones and no effect to compilation phase. Or getting some info out from compilation phase?

**Comment by SteffenMangold** [comment]
> Or getting some info out from compilation phase?

In details, I'm not looking to returning debug information from server side. I want to return information from the compilation phase. Like a "Was cache hit" boolean.

**Comment by smitpatel** [comment]
You could just subscribe to EF Core logging infra. Loggers are services, you can inject them in custom query compiler and log the info. At present we don't have any way to get info from compilation phase outside of logging. We will discuss as team in next meeting (next year), if we want to allow such functionality.

**Comment by SteffenMangold** [comment]
Perfect, Loggers is what I already use to detect cache hits. So I already found the intended way. Thank you for clarifying. 😊
