### ISSUE TITLE
Column Name not reflecting on Database

### ISSUE THREAD

**Issue by vijayantkatyal** [dotnet/efcore#1424]
Column name not reflecting on database

e.g.

[Column("some_name")]
public string name { get; set; }

expected result:
column name should be "some_name"

actual result:
column name is "name" instead of "some_name".

**Comment by ErikEJ** [comment]
Annotations have not been implemented yet

**Comment by vijayantkatyal** [comment]
@ErikEJ thanks for the feedback.
