### ISSUE TITLE
EF Core Tools sees magical DbContext

### ISSUE THREAD

**Issue by martinpetrovaj** [dotnet/efcore#14255]
EF Core Tools started acting strange. I could not determine the reason yet, no package was installed immediately beore this behaviour started, only commands I've used was the Add-Migration and Update-Database duo. After entering command "Add-Migration", the console claims that there is more than one datacontext (More than one DbContext was found. Specify which one to use.…). However, there is only one class which inherits from DbContext in the solution.

The -Context parameter apparently accepts two values - "ApplicationDbContext" (which is the context I've been using throughout my application) and "DbContext" (I was once somehow able to make Get-DbContext -Context DbContext show me it's assembly - I think it was Microsoft.EntityFrameworkCore).

Using Add-Migration MigrationName -Context ApplicationDbContext exhibits strange behaviour (which I simply fail to comprehend or describe) and subsequent calls to Update-Database fail.

Using any commands with -Context DbContext usually results in "The string argument 'identifier' cannot be empty.", as Database name seems to be an empty string.

Any ideas what caused the problem and how to resolve it? I'm not sure which code could be related to this issue, so I'll post some basic stuff to begin with (plus attach the [full solution](https://github.com/aspnet/EntityFrameworkCore/files/2713584/Eshop.zip)):

If you are seeing an exception, include the full exceptions details (message and stack trace).

```c#
namespace Eshop.Data
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options) { }
    …
}
```

```c#
public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
```

```c#
//Startup.cs
if (connectionString.Contains("%PROJPATH%"))
{
    connectionString = connectionString.Replace("%PROJPATH%", env.ContentRootPath);
}

services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connectionString/*, b => b.MigrationsAssembly("Eshop.Data")*/));
services.AddIdentity<ApplicationUser, IdentityRole>()
    AddEntityFrameworkStores<ApplicationDbContext>();
```

```
//appsettings.json
	"ConnectionStrings": {
		"DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=aspnet-Eshop-2A357EC5-5D85-474C-B5D4-CA57311E87CB;Trusted_Connection=True;MultipleActiveResultSets=true",
		"AttachedConnection": "Server=(localdb)\\mssqllocaldb; AttachDbFileName=%PROJPATH%.Data\\Data\\attached.mdf; Trusted_Connection=True;MultipleActiveResultSets=true"
	},
```

### Further technical details
EF Core version: 2.1.0 (I have to use this one)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Home
IDE: Visual Studio 2017 15.9

**Comment by smitpatel** [comment]
All of your `migration.Designer.cs` files have attribute `[DbContext(typeof(DbContext))]` on the class name. That is where the magical DbContext is coming into picture. When I corrected all of them to `[DbContext(typeof(ApplicationDbContext))]` migration started working as expected. Further the newly added migration has correct `DbContextAttribute`. So I am not able to reproduce having incorrect DbContextAttribute. Most likely it was due to manual editing in some way. (May be a find and replace across whole solution). Feel free to reopen if you can provide repro for incorrect attribute generated.

**Comment by martinpetrovaj** [comment]
Thanks a million for finding the issue. I would never have thought the problem might be in the generated migration files and couldn't find anyone with a similar problem.
