### ISSUE TITLE
How to get label text from table reference on database based on TableName and FieldName

### ISSUE THREAD

**Issue by ahmedbarbary** [dotnet/efcore#14251]
**Problem**

**How to get label text from table reference on database  based on Table Name and Field Name dynamically**

from database and Display them on windows form create Employee.

Meaning i need to get label text dynamically from database not static from model

So that Every Time I  need to change text of label i will change it from database depend on reference table 

AND No need to change from code .

IF You give me function or any thing general because i have more models and view i need to make like that)

Query Get Data from reference Table
```sql
SELECT TableName, FieldName,EnglishtextforLabel FROM ReferenceFile WHERE (FieldName = 'EmployeeId' ) AND TableName = 'Employee'
```
Database Have two tables Employee and Reference File(may be increase models and views so that if any thing general is prefer) 

Models classes Include HRContext

```C#
 public class ReferenceFile(have 3 key as composit keys(Code,TableName,FieldName))
    {
        public int Code { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string EnglishtextforLabel{ get; set; }

    }
 public class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeeAge { get; set; }
    }
 public class HRContext : DbContext
    {
        public HRContext(DbContextOptions<HRContext> options)
: base(options)
        { }

        public DbSet<Employee> Employees { get; set; }
        public DbSet<ReferenceFile> ReferenceFiles { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Employee>()
               .HasKey(t => new { t.EmployeeId });

            modelBuilder.Entity<ReferenceFile>()
                .HasKey(t => new { t.Code,t.TableName,t.FieldName });
        }
    } 
```

Here i need to get label on view create from table reference not static field name

Sample data for ReferenceTable

Code | TableName | FieldName      | EnglishtextforLabel 
--- | --- | --- | ---
1 |     Employee  |   EmployeeId    |          Code
2  |    Employee |    EmployeeName |        Name        
3   |   Employee |    EmployeeAge     |       Age

As reference table above sample labels on windows form  create employee must be Give me the Result below :

Code

Name

Age

### Further technical details
Tools used sql server 2012 and visual studio 2017 windows forms

**Comment by ahmedbarbary** [comment]
can nay one help me if possible

**Comment by ajcvickers** [comment]
@ahmedbarbary Unfortunately, I am not able to follow what you are trying to do. Could you try to explain clearly, maybe by showing your code, what you are trying to do and what goes wrong when you write code to do it?
