### ISSUE TITLE
can't support comlex sql query?

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/efcore#14258]
for exmple to execute sql:
select * from a left join select * from b on
a.id=b.id

**Comment by sdanyliv** [comment]
@bouyeijiang LEFT JOIN can be expressed by LINQ.
```cs
var query = from ai in a
   join bi in b on b.id equals a.id into joined 
   from bj in joined.DefaultIfEmpty()
   select new { ai, bj }
```
Also many linq providers support simplified form
```cs
var query = from ai in a
   from bi in b.Where(bi => bi.id == ai.id).DefaultIfEmpty()
   select new { ai, bi }
```

**Comment by bouyeijiang** [comment]
i mean do not used linq query and than execute sql  return a list entity

**Comment by bouyeijiang** [comment]
keypoint is the model need add to DbContext?
