### ISSUE TITLE
Defining Property as IGeometry or Geometry throws SqliteException

### ISSUE THREAD

**Issue by seitzp** [dotnet/efcore#14266]
When I try to set the Geometry of a model class to  IGeometry or Geometry an Exception is thrown. If I use a concrete class( for e.g. Point) it works. The docs state: 

> Using the base Geometry type allows any type of shape to be specified by the property.

```
Exception message: SqliteException: SQLite Error 19: 'Users.Location violates Geometry constraint [geom-type or SRID not allowed]'.
```

### Steps to reproduce
Using sample code from here [Finding Nearby Users with Entity Framework Core Spatial Data](https://www.markopapic.com/finding-nearby-users-using-ef-core-spatial-data/) and changing the type of User.Location from Point to Geometry or IGeometry

**Is this a bug in Sqlite or is this generally not supported?**

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite 2.2.0
Operating system: Windows 10 1809
IDE: (e.g. Visual Studio 2017 15.9.3)

**Comment by ajcvickers** [comment]
@SeitzDev This looks like a bug. I would be helpful if you could post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by SeitzDev** [comment]
I tried again from a new project and it seems there were multiple errors on my end.
You can close this issue.Thanks for your time.
