### ISSUE TITLE
Lazy loading property can not be updated.

### ISSUE THREAD

**Issue by avalon1610** [dotnet/efcore#14261]
I have model which use lazy loading, something like
```c#
public class Device
{
  public virtual IdentityUser CurrentUser {get; set; }
}
```
when I change CurrentUser to null, and update the model, database remain the origin value
```c#
var device = await _database.Devices.SingleOrDefaultAsync(d => d.addresss == address);
device.CurrentUser = null;   // not working 
_database.Devices.Update(device);
await _database.SaveChangesAsync();
```
but when use Include, it works fine
```c#
var device = await _database.Devices.Include(d => d.CurrentUser).SingleOrDefaultAsync(d => d.addresss == address);
device.CurrentUser = null;   // update successfully
_database.Devices.Update(device);
await _database.SaveChangesAsync();
```

Anything i'm doing wrong?

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 7
IDE: Visual Studio 2017 15.9.4

**Comment by Advitalitum** [comment]
Dup of #14246, #14086
