### ISSUE TITLE
Porting from EF6 to EF Core: Namingconventions

### ISSUE THREAD

**Issue by Verkop** [dotnet/efcore#14272]
When I want to port a poject with an existing database from EF 6 to EF Core will I encounter any problems regarding differences in naming conventions between EF6 and EF Core? As the documentation says EF Core is not pluralizing tablenames or anything. Will EF Core still find the corresponding table in the existing database or do I need to change anything for this to work? And if so are there any other differences in naming conventions between these two that I should take a look at first?

Sadly the existing documentation does not cover these aspects of porting to EF Core.

**Comment by ajcvickers** [comment]
@Nanna11 Most of the naming conventions are the same. If you do run into differences, then it would be useful if you could comment here what they were.
