### ISSUE TITLE
Unusual navigation names in generated models from existing database

### ISSUE THREAD

**Issue by singhniranjan** [dotnet/efcore#14278]
When model classes are generated for existing database, column names are in correct in the case as described below.

I have a sample database, say, **school** database which has two tables **Student_Details** and **Book_Details**
Book is issued to multiple students at different times, so one book to many students relationship is there. Now in Book model class, navigation property name for Student is generated incorrectly. Ideally, it should be **Student_Details** whereas it is generated as **Student_**

Script of sample database:
```sql
CREATE TABLE [dbo].[Book_Details](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Book_Name] [nvarchar](50) NULL,
	[Student_Id] [int] NULL,
 CONSTRAINT [PK_Book_Details] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Student_Details](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Student_Name] [nvarchar](256) NULL,
 CONSTRAINT [PK_Student_Details] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Book_Details]  WITH CHECK ADD  CONSTRAINT [FK_Book_Details_Student_Details] FOREIGN KEY([Student_Id])
REFERENCES [dbo].[Student_Details] ([ID])
GO
ALTER TABLE [dbo].[Book_Details] CHECK CONSTRAINT [FK_Book_Details_Student_Details]
GO
```

## Steps to reproduce
Run command in PM Console:
`Scaffold-DbContext "Server=.\SQLEXPRESS;Database=school;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models  -UseDatabaseNames -Context schoolEntities`

The same behavior is there if run from command line instead of PM Console.

Here are genereated model classes. Please note, property name in Book_Details class should be **Student_Details**, whereas it is **Student_**

```c#
using System;
using System.Collections.Generic;

namespace CoreData.Models
{
    public partial class Book_Details
    {
        public int ID { get; set; }
        public string Book_Name { get; set; }
        public int? Student_Id { get; set; }

        public Student_Details Student_ { get; set; }
    }
}

//--------------

using System;
using System.Collections.Generic;

namespace CoreData.Models
{
    public partial class Student_Details
    {
        public Student_Details()
        {
            Book_Details = new HashSet<Book_Details>();
        }

        public int ID { get; set; }
        public string Student_Name { get; set; }

        public ICollection<Book_Details> Book_Details { get; set; }
    }
}

```

### Further technical details
EF Core version: 2.1.1-rtm-30846
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
Navigation name is derived from `navigationName + PKPropertyName = FKPropertyName`
In your case FK is `Student_Id` and PK on the other side is `ID` so it made judgement that navigation should be named as stripped out PK property name from FK. `Student_` is not a good answer though.

**Comment by sc-vudo** [comment]
I have same issue where I have used the foreign key column names not matching the primary key column name.

e.g.

User table has User_ID as PK
Company table has Company_ID as PK
Manager table has FKs to 
Manager_User_ID which is FK to User
Manager_Company_ID is FK to Company

When querying the DB all is well on one entity but add include to query and we hit a problem. It keeps tryingto add a column name matching the PK column name from the FK table.

**Comment by ajcvickers** [comment]
@sc-vudo This looks different from the issue reported here. Can you please file a new issue, including a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment]
No longer repros with 7.0. Generated code is:

```C#
public partial class Student_Detail
{
    public int ID { get; set; }

    public string? Student_Name { get; set; }

    public virtual ICollection<Book_Detail> Book_Details { get; } = new List<Book_Detail>();
}
```

```C#
public partial class Book_Detail
{
    public int ID { get; set; }

    public string? Book_Name { get; set; }

    public int? Student_Id { get; set; }

    public virtual Student_Detail? Student { get; set; }
}
```
