### ISSUE TITLE
DatabaseErrorPageMiddleware cannot find the correct data context when AddDbContext<TService, TImplementation> is used

### ISSUE THREAD

**Issue by CoskunSunali** [dotnet/efcore#14307]
### Describe the bug
This is related to https://github.com/aspnet/AspNetCore/issues/4285 but not exactly the same issue.

`DatabaseErrorPageMiddleware`  tries to resolve the current data context using its concrete implementation type instead of its service type and fails to resolve the context at https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Middleware/Diagnostics.EntityFrameworkCore/src/DatabaseErrorPageMiddleware.cs#L117

It should either resolve the data context using its service type or the internal service provider should have the concrete type registered automatically with its instance pointing to the actual service like below.

```cs
services.AddScoped((s) => // Scoped or Singleton? Don't know how the service is originally registered in the internal service provider
{
    return (TImplementation)s.GetRequiredService<TService>();
});
```

### To Reproduce
1. Enable database error pages using `UseDatabaseErrorPage`
2. Register data context using `AddDbContext<TService, TImplementation>`
3. Create a migration but don't apply (add a column)
4. Run some code (query?) to make EF throw an exception stating that schema mismatch like `Invalid column name '$ColumnName$'`

### Expected behavior
Having database error page working correctly when `AddDbContext<TService, TImplementation>` is used.

### Logs
```
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware:Debug: Entity Framework recorded that the current exception was due to a failed database operation. Attempting to show database error page.
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware:Error: The context type 'Context' was not found in services. This usually means the context was not registered in services during startup. You probably want to call AddScoped<>() inside the UseServices(...) call in your application startup code. Skipping display of the database error page.
```

### Additional Info
Adding a service with the concrete type to the application service provider doesn't help. EF expects the service to exist within the internal service provider. So the error message suggesting that `AddServices` be used in application startup code is also a misleading message because that won't solve the issue.

### Workaround
Register the data context with its concrete implementation type and add an `alias` for the interface type.

```cs
services.AddDbContext<TImplementation>();
services.AddScoped((s) =>
{
    return (TService)s.GetRequiredService<TImplementation>();
});
```

**Comment by ajcvickers** [comment]
@Eilon Thanks; moved it.

**Comment by CoskunSunali** [comment]
Sorry guys, thought the middleware was part of AspNet Core instead of EF Core so I created it there.

Thanks for moving to the appropriate repository.

**Comment by ajcvickers** [comment]
@CoskunSunali It is--you filed in a sensible place. It's just that it is maintained by the EF team so we track issues here.

**Comment by CoskunSunali** [comment]
Changed the description to point the other reference issue to https://github.com/aspnet/AspNetCore/issues/4285

@ajcvickers Oh, glad I wasn't mistaken. Thanks for the insight.

**Comment by ajcvickers** [comment]
Note from triage: consolidate this with other error page updates post 3.1.
