### ISSUE TITLE
could not load file or assembly Microsoft.EntityFrameworkCore.Hosting.Abstractions

### ISSUE THREAD

**Issue by nhn110112** [dotnet/efcore#14310]
Describe what is not working as expected.
I have a class library project targeting .NET Core 2.1 with Entity Framework Core v2.1.4 installed. It contains all the domain logic. Whenever I use EF Core Power Tools -> Migrations Tool, I'm having this exception:

`Message: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.EntityFrameworkCore.Hosting.Abstractions, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

**Comment by ajcvickers** [comment]
@nhn110112 This should be reported to the EF Core Power Tools--see https://github.com/ErikEJ/EFCorePowerTools
