### ISSUE TITLE
Optional Value Conversions dependent on support from Database Provider

### ISSUE THREAD

**Issue by ntyrrell** [dotnet/efcore#14319]
At present, my application uses Npgsql as the database provider for the main application. However, without wanting to run a blank database for unit testing, I would hope to use an InMemory provider instead.

When a column datatype (e.g. PhysicalAddress) is supported by one provider (Npgsql -> macaddr) but not another, it breaks testing. If a value conversion is entered (e.g.)
```
entity.Property(e => e.MacAddress)
.HasColumnName("mac_address")
.HasConversion(
    property => property.ToString(),
    columnName => System.Net.NetworkInformation.PhysicalAddress.Parse(columnName)
)
```
This works when using the InMemory provider, but not in the actual implementation.

Ideally, the conversion should be optional, used if the provider does not have native support for that type.

**Comment by ajcvickers** [comment]
@ntyrrell The model can be conditionally configured with a type mapping based on provider using something like this in OnModelCreating:
```C#
modelBuilder.Entity<Blog>();

if (Database.IsInMemory())
{
    modelBuilder.Entity<Blog>().Property(
            e => e.MacAddress)
        .HasConversion(
              property => property.ToString(),
              columnName => System.Net.NetworkInformation.PhysicalAddress.Parse(columnName));
}
```

That being said, this made us think that configuring value converters for only one provider or another could be useful, and would be nice to do as part of #10784, which is about global conversions.
