### ISSUE TITLE
Design meeting discussion:January 16, 2015

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1432]
This issue is for discussion of the [EF design meeting on January 16, 2015](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-January-16,-2015).

Items discussed were:
- API Review 1 (DbContext, DbSet, Database)

Please comment on this issue to provide feedback, ask questions, etc.

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
