### ISSUE TITLE
.HasDefaultValueSql("(N'NO')"); doesn't work with sqlite

### ISSUE THREAD

**Issue by jsgoupil** [dotnet/efcore#14344]
The following:

```
entity.Property(e => e.Accepted)
    .HasColumnName("accepted")
    .HasMaxLength(50)
    .HasDefaultValueSql("(N'NO')");
```

Will trigger an exception 

```
Message: Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'near "'NO'": syntax error'.
```

I generated the `OnModelCreating` code from `Scaffold-DbContext`. So I have no control over the value set in `HasDefaultValueSql`.

I use the `"DataSource=:memory:"`:

```
// In-memory database only exists while the connection is open
var connection = new SqliteConnection("DataSource=:memory:");
connection.Open();

var options = new DbContextOptionsBuilder<MyContext>()
        .UseSqlite(connection)
        .Options;

var dbContext = new MyContext(options);
using (var context = new MyContext(options))
{
    context.Database.EnsureCreated();
}
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows
IDE: Visual Studio 2017 Community 15.9.2)

**Comment by bricelam** [comment]
> I generated the OnModelCreating code from Scaffold-DbContext. So I have no control over the value set in HasDefaultValueSql.

Models reverse-engineered from a SQL Server database aren't expected to work on SQLite without some changes.

`N'NO'` isn't a valid constant in SQLite's dialect of SQL. Change your model to use `.HasDefaultValue("NO")` to make it work on both SQL Server and SQLite.
