### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite v2.2.0 has dependecy issues on dotnet

### ISSUE THREAD

**Issue by igormcoelho** [dotnet/efcore#14354]
Describe what is not working as expected.

perhaps I'm reporting to the wrong project... is this responsible for Microsoft.EntityFrameworkCore.Sqlite? 

Version 2.2.0 is causing an issue on dotnet nuget, reporting a downgrade issue:
```
error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
error NU1605: Neo -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.unix.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
error NU1605: Neo -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1) 
```

it looks like an issue with DependencyModel 2.1.0 is causing this.

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by bricelam** [comment]
Similar to #14090

**Comment by ajcvickers** [comment]
@bricelam to follow up.

**Comment by igormcoelho** [comment]
oh! it's indeed very similar! thanks for the connection with the other issue... I hope some solution is found, my current action was to downgrade sqlite package, but that's not a good path.

**Comment by igormcoelho** [comment]
@vncoelho this may help us.

**Comment by igormcoelho** [comment]
Should I close this and continue only on https://github.com/dotnet/corefx/issues/34055 ?
