### ISSUE TITLE
Use Tuples to shorten Eager loading expressions

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#14385]
Suppose we have this expression: 
```
context.Blogs
         .Include(blog => blog.Posts)
                .ThenInclude(post => post.Tags)
                     .ThenInclude(tag => tag.TagInfo)
         .Include(blog => blog.Posts)
                .ThenInclude(post => post.Comments)
         .Include(blog => blog.Contributors);
```

I suggest to allow using tuples (or anonymous types) to rewrite it as this:
```
context.Blogs
         .Include(blog => (blog.Posts, blog.Contributors))
                .ThenInclude( (post, _) => (post.Tags, post.Comments)
                    .ThenInclude( (tag, _) => tag.TagInfo);
```

I don't know if it is easy to implement or not, but it saves half the lines in this simple example.

**Comment by tuespetre** [comment]
That's actually a pretty cool idea.

**Comment by MohammadHamdyGhanem** [comment]
@tuespetre 
Thanks. Can you implement the new Include and ThenInclude overloads , at least by making them call the existing ones?

**Comment by tuespetre** [comment]
Implementation-wise, the extension methods would return new `IQueryable<T>` instances with `MethodCallExpression`s that point back at themselves, and then the query compiler would need to be extended in some way to account for those expressions.

I do not speak for the EF Core team though, I just like your idea.

**Comment by ajcvickers** [comment]
@MohammadHamdyGhanem We discussed this in triage and we don't think it is something we want to introduce to the core API surface. One issue is that It would require multiple overloads for tuples with different cardinality, and beyond that it's pretty hard to decipher the syntax needed when writing it or what it means when reading it.

However, it would certainly be possible to implement this as extension methods that convert the resultant paths into strings and then call into the string overload of Include. So maybe this could be done externally and released as an add-on package by the community?
