### ISSUE TITLE
dotnet ef commands broken in Dev16 2.2 Web app targeting .NET Framework

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#14380]
Steps:
* Use current Dev16 preview
* Create a new "ASP.NET Core Web Application" (Doesn't repro with console app.)
* In the One ASP.NET dialog, select ".NET Framework" "ASP.NET Core 2.2", and create an "Web Application" with HTTPS and "Individual User Accounts" auth.
* Build everything
* Open a developer command prompt for Dev16
* Change to the project dir
* Run `dotnet ef dbcontext list`

Result:

> C:\Stuff\WebApplication5\WebApplication5>dotnet ef dbcontext list
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
WebApplication5.Data.ApplicationDbContext

**Comment by smitpatel** [comment]
>  no "Individual User Accounts" auth.

This is ambiguous for me if user is using identity or not.
With No Auth mode
error is (as expected since no EF packages installed)
```
\WebApplication9>dotnet ef dbcontext list
Your startup project 'WebApplication9' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```

With Individual user accounts,
It works for me.
```
\WebApplication10>dotnet ef dbcontext list
WebApplication10.Data.ApplicationDbContext
```

We would need a repro solution.

**Comment by ajcvickers** [comment]
@smitpatel Typo--I removed the no. This repros for me consistently on the Dev16 preview. I'll add you to an email thread.

**Comment by ajcvickers** [comment]
[WebApplication5.zip](https://github.com/aspnet/EntityFrameworkCore/files/2747643/WebApplication5.zip)

**Comment by smitpatel** [comment]
After updating SDK from 2.2.102 to 2.2.200-preview-009648 I am also seeing the error.
Also in above case, we are still printing out the context list.
With other commands we actually throw error
```
\WebApplication1>dotnet ef database update
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

**Comment by smitpatel** [comment]
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

The version of assembly in bin folder is 4.0.2.0

Most of the binding redirect generated are not matching version of assembly in bin folder.
Also EF Core fails to bind correctly as the tool is trying to find version 2.2 but the assembly available is 2.2.1.0

**Comment by ajcvickers** [comment]
@smitpatel Thanks for the additional investigation.
@bricelam @smitpatel Can we either:
* Actively pass this off to @livarcocc or whomever is appropriate if we think it is root caused down to something external to ASP.NET/EF
* Pull in @natemcmaster or whomever is appropriate if it's an issue with build
* Or make it a priority between the two of you to investigate further.

Thanks!

**Comment by bricelam** [comment]
Not seeing any issues using SDK 2.2.200-preview-009748...

**Comment by ajcvickers** [comment]
@bricelam @livarcocc So is this fixed already for Dev16 preview 2? Do we know how?

**Comment by ajcvickers** [comment]
We have tested with the latest preview 2 build and this no longer repros.
