### ISSUE TITLE
Regression - GroupJoin gives wrong result after upgrade EF Core

### ISSUE THREAD

**Issue by Dixin** [dotnet/efcore#14395]
Recently I upgraded an old project to use the latest EF Core, then a `GroupJoin` query gives the wrong result.

### Reproduce
The following query gives the correct result with EF Core 1.1.6-, and gives wrong result with EF Core 2.0.0+:

```cs
internal static void SelfJoin(AdventureWorks adventureWorks)
{
    IQueryable<Product> outer = adventureWorks.Products;
    IQueryable<Product> inner = adventureWorks.Products;
    // For each product, find other products with the same ListPrice.
    var products = outer.GroupJoin(
        inner,
        product => product.ListPrice,
        product => product.ListPrice,
        (product, samePriceProducts) => new
        {
            Name = product.Name,
            ListPrice = product.ListPrice,
            SamePriceProducts = samePriceProducts
                .Where(samePriceProduct => samePriceProduct.ProductID != product.ProductID)
                .Select(samePriceProduct => samePriceProduct.Name)
        });

    // Print each product, and other products with the same ListPrice.
    products.ForEach(product =>
        Trace.WriteLine($"{product.Name} ({product.ListPrice}): {string.Join(", ", product.SamePriceProducts)}"));
}
```

### Expected
In EF Core 1.1.6-, the `GroupJoin` is translated to:
```sql
SELECT [product].[ProductID], [product].[ListPrice], [product].[Name], [product].[ProductSubcategoryID], [product0].[ProductID], [product0].[ListPrice], [product0].[Name], [product0].[ProductSubcategoryID]
FROM [Production].[Product] AS [product]
LEFT JOIN [Production].[Product] AS [product0] ON [product].[ListPrice] = [product0].[ListPrice]
ORDER BY [product].[ListPrice]
```
And each product is correctly matched with other products with the same price.

> ...
> Mountain-400-W Silver, 38 (769.4900): Mountain-400-W Silver, 40, Mountain-400-W Silver, 42, Mountain-400-W Silver, 46
> Mountain-400-W Silver, 40 (769.4900): Mountain-400-W Silver, 38, Mountain-400-W Silver, 42, Mountain-400-W Silver, 46
> Mountain-400-W Silver, 42 (769.4900): Mountain-400-W Silver, 38, Mountain-400-W Silver, 40, Mountain-400-W Silver, 46
> Mountain-400-W Silver, 46 (769.4900): Mountain-400-W Silver, 38, Mountain-400-W Silver, 40, Mountain-400-W Silver, 42
> ...

### Unexpected
In EF Core 2.0.0+, the `GroupJoin` is translated to:
```sql
SELECT [product].[ProductID], [product].[ListPrice] AS [ListPrice0], [product].[Name] AS [Name0], [product].[ProductSubcategoryID], [product].[RowVersion], [product].[ProductID], [product].[ListPrice], [product].[Name], [product].[ProductSubcategoryID], [product].[RowVersion]
FROM [Production].[Product] AS [product]
ORDER BY [ListPrice0]
```
And each product is matched with 0 other product.

> ...
> Mountain-400-W Silver, 38 (769.4900): 
> Mountain-400-W Silver, 40 (769.4900): 
> Mountain-400-W Silver, 42 (769.4900): 
> Mountain-400-W Silver, 46 (769.4900): 
> ...

This looks like a regression.

### Further technical details
EF Core version: 2.0.0+
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.9.5

**Comment by smitpatel** [comment]
This is not supported query. See #17068
