### ISSUE TITLE
Commands: Allow for DbContexts in other assemblies

### ISSUE THREAD

**Issue by waf** [dotnet/efcore#1440]
Currently, the `--context` command does not allow for DbContexts in other projects. For example, if you run the following command from a `MyProject.Web` project, which depends on a `MyProject.DataAccess` project that contains your DbContext:

``` console
> k ef migration apply -c "MyProject.DataAccess.MyDbContext"
System.InvalidOperationException: No DbContext named 'MyProject.DataAccess.MyDbContext' was found.
   at Microsoft.Data.Entity.Commands.ContextTool.SelectType(IEnumerable`1 types, String name)
   at Microsoft.Data.Entity.Commands.MigrationTool.GetContextType(String name)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass5.<Main>b__18()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
```

You can get around this by running the `k` command from the `MyProject.DataAccess` project, but that requires duplicating the connection string in `MyProject.DataAccess` and `MyProject.Web`.

**Comment by cherrydev** [comment]
I actually can't even get the work-around to operate unless I override OnConfiguring and then hard-code the connection string, since the ef command doesn't seem to properly initialize the DI container, even if you include a Startup.cs in the DataAccess project.  Have you found a workaround to this?

**Comment by waf** [comment]
@cherrydev no, my work-around is just copying the connection string from `MyProject.Web\config.json` to `MyProject.DataAccess\config.json`, and putting the following in `MyProject.DataAccess.MyDbContext`:
```csharp
        protected override void OnConfiguring(DbContextOptions options)
        {
            var configuration = new Configuration().AddJsonFile("config.json");
            options.UseSqlServer(configuration.Get("Data:DefaultConnection:ConnectionString"));
        }
```
Issue 823 is related, as it will make Commands respect the various system components. I don't think that issue being fixed will allow for DbContexts in other projects, though.

**Comment by bricelam** [comment]
I think we'll always require the commands to be run on project containing migrations (or the context if generating the first migration). As part of #823, we'll allow you to specify a start-up project that will be used to look for `Startup.ConfigureServices` and relative-pathed files (including configuration).

**Comment by rowanmiller** [comment]
Required work is already tracked by items that @bricelam linked to
