### ISSUE TITLE
Service lifetimes in ASP.NET Core

### ISSUE THREAD

**Issue by GoFightNguyen** [dotnet/efcore#14414]
This [ASP.NET Core 2.1 documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#entity-framework-contexts) says 

> EF contexts should be added to the service container using the scoped lifetime...Services that use the database context should also use the scoped lifetime.

Does this imply it is "scoped lifetimes" all the way up? Let Service1 use the database context and Service2 use Service 1. Is the implication that both Service1 and Service2 should use a scoped lifetime?

### Further technical details
EF Core version: 2.1
ASP.NET Core version: 2.1

**Comment by ajcvickers** [comment]
@GoFightNguyen Yes, although transient can be used instead, as long as care is taken to ensure the service is disposed.
