### ISSUE TITLE
local evaluation and include

### ISSUE THREAD

**Issue by herme063** [dotnet/efcore#14410]
Does Include() affect the decision to evaluate something locally or remotely?

I have a very simple where query yet it still trigger local evaluation

The LINQ expression 'where {__parameter.TypeIds => Contains([ts].TypeId)}' could not be translated and will be evaluated locally.

I do have several includes on the same query though,

Thank you,

**Comment by smitpatel** [comment]
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by herme063** [comment]
I forgot to mention that I am using this Contains() inside a compiled query.

**Comment by herme063** [comment]
[same issue faced here](https://github.com/aspnet/EntityFrameworkCore/issues/13976)
