### ISSUE TITLE
Default columns of __EFMigrationsHistory

### ISSUE THREAD

**Issue by ichensky** [dotnet/efcore#14422]
Proposal: change default columns of `__EFMigrationsHistory` table to: 

Id, MigrationName, MigrationSource, Created 

Where 
`Id`  - hash (for ex. sha1) from `MigrationSource`
`MigrationName` - name of migration.
`MigrationSource` - sql representation of migration.
`Created` - date, when migration was applied to database. 

With this columns, it would be possible 
* See what migrations were applied, without having source code (so this will be good for admins, that have no access to the source code). 
* Apply same migration several times. 
* By `Id` hash developer will always know what migration was and when applied even if  `MigrationSource` not included into database by security restrictions. 
* Migrations can have the same names, but with different source code, of different names with the same source code.

**Comment by ajcvickers** [comment]
@bricelam to follow up.
