### ISSUE TITLE
[question]performance improve

### ISSUE THREAD

**Issue by ZhiqiangTao** [dotnet/efcore#14438]
why does the series of EF  not implement or integrate [https://entityframework-extensions.net/](url) by default, it seems more perfomance! .........

**Comment by smitpatel** [comment]
Duplicate of #795

**Comment by ajcvickers** [comment]
@ZhiqiangTao Functionality existing in third-party libraries is something we encourage. It helps build a better ecosystem overall. That being said, we also consider well-written, robust PRs to add functionality to EF Core.
