### ISSUE TITLE
Unable to load the specified metadata resource.

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#1443]
Got this exception(_see title_)

Found this on google ... 

http://stackoverflow.com/questions/689355/metadataexception-unable-to-load-the-specified-metadata-resource

Then thought to myself ... hmmmm. What a wonderful place to be ...

**Comment by rowanmiller** [comment]
__EF Team Triage:__ _This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving._

**Comment by rowanmiller** [comment]
Closing as there doesn't seem to be anything actionable here. It is worth noting that this issue would no longer exist in EF7 as we do not load models from embedded xml files.
