### ISSUE TITLE
Couchbase provider discussion

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#14452]
Creating this discussion issue to continue our conversation with people from [Couchbase](https://www.couchbase.com) and the [Couchbase open-source community](https://github.com/couchbase) about an EF Core provider. 

cc @mgroves, @jeffrymorris, @brantburnett.

**Comment by jeffrymorris** [comment]
Hey Folks -

We have has some discussion internally regarding short and long term development goals for Couchbase EF and have decided to:

- Target EF Core 2.0 and porting over the Linq layer from Linq2Couchbase. Assuming this is feasible and is doable within a realistic time frame we would release a v1 Couchbase EF provider based on EF Core 2.0 sometime this year, prefferably in the early summer.
- Once we getting a published v1.0 Couchbase EF provider, switch over to v2 by targeted EF Core 3.0 - this should conincide with end of the dev cycle for EF Core 3.0 before production and should leave us with a more stable platform to base v2 Couchbase EF on.

We feel this would meet our short term goals to offer an EF provider sooner than later (even if its not 100%) and then work torwards supporting the future of EF, 3.0.

-Jeff

**Comment by smitpatel** [comment]
I would suggest using EF Core 2.1 (rather than 2.0)

**Comment by ajcvickers** [comment]
@jeffrymorris Sounds reasonable. A couple of thoughts:
* As @smitpatel said, target 2.1 (or 2.2) rather than 2.0.
  * 2.0 is already out-of-support.
  * 2.1 is LTS, so it will be in-support for a while yet
  * 2.2 has the most features and seems to be the most stable, but will be out of support before 2.1.
* We won't be able to change much in the 2.x codebase if things you need are missing/hard.
* We had discussed following along with the Cosmos provider, which will be harder to do since it is targeting 3.0.

That being said, the plan sounds reasonable.

**Comment by jeffrymorris** [comment]
I probably should have said _"Target EF Core 2.X"_...based upon LTS 2.1 seems best, unless we need to pivot somewhere. Thanks for the feedback!

**Comment by ajcvickers** [comment]
And yes, the versions correspond with the other EF packages. We ship the specification tests every time we ship a major or minor version, including previews.

**Comment by mgroves** [comment]
@ajcvickers Excellent, thank you. Can you recommend any resources on how to get started with Microsoft.EntityFrameworkCore.Specification.Tests (other than Postgres repository)? My current thought is that these tests will help to drive the code that we write (a TDD approach).

**Comment by ajcvickers** [comment]
@mgroves We don't have any good docs on this, but the general idea is that the package contains test classes that you derive from in your project to run with your provider. A TDD approach might be hard at first with these tests they all require some level of basic functionality--they aren't unit tests as such, so you may want some of those of your own as appropriate. That being said, getting to a point where all these tests pass is a great goal and should cover all the most important functionality.

**Comment by mgroves** [comment]
I've taken a crack at getting some of the basic infrastructure created.

I used the "InMemory" provider from the release/2.1 branch as a guideline - https://github.com/aspnet/EntityFrameworkCore/tree/release/2.1

My efforts are in [my own fork right now](https://github.com/mgroves/dotnet-couchbase-ef). It's basically just a bunch of skeleton classes. I can "add" entities, and then a "notimplementedexception" is thrown when I attempt to SaveChanges. If I want to proceed trying to bring in [Linq2Couchbase](https://github.com/couchbaselabs/Linq2Couchbase), can you recommend a good place to start? I'm thinking `CouchbaseQueryModelVisitorFactory` and/or `CouchbaseEntityQueryableExpressionVisitorFactory`?

**Comment by ajcvickers** [comment]
@smitpatel Any thoughts on @mgroves's question?

**Comment by mgroves** [comment]
You all have been great helps so far, thank you!

To override QueryCompiler, I just `TryAdd<IQueryCompiler,CouchbaseQueryCompiler>` in the AddEntityFrameworkCouchbase extension method? `TryAddCoreServices` won't override it?

Kinda related, I'm a little unclear about how/where to accept and store config (like ip address, credentials, bucket name). I'm assuming the `DbContextOptionsBuilder` extensions method (`UseCouchbase`) should accept those settings, but what do I do with them at that point?

**Comment by ajcvickers** [comment]
@mgroves Look at IOptionsExtension. For example, there is one for InMemory that handles the database name.

**Comment by ajcvickers** [comment]
@mgroves Also, yes, TryAddCoreServices won't override it. The infrastructure ensures that provider services are registered first, and then EF will only use the default implementations if the provider has not registered an implementation.

**Comment by brantburnett** [comment]
What's the status of the 3.0 work? Is it ready to start developing a provider yet, or is it still at a high rate of flux?

**Comment by AndriySvyryd** [comment]
@brantburnett Sorry for the late response, but 3.0 is stable now :smile: We do have some breaking changes planned for the next release, but they should mostly only affect the relational providers.

**Comment by vslee** [comment]
You can vote for the issue here: https://issues.couchbase.com/browse/NCBC-1931

**Comment by x-danma** [comment]
This discussion might be more important now that ef core 8 have more support for JSON-columns in relational databases, as well as a cosmosDB provider. https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew. I can't upvote the [couchbase jira issue](https://issues.couchbase.com/browse/NCBC-1931), but would like to

**Comment by mgroves** [comment]
Thanks for leaving a comment @x-danma, I've created an internal feedback item. EF Core support is something I'd like to see too :)

**Comment by vslee** [comment]
Couchbase has now released an official provider:

Announcement blog post: https://www.couchbase.com/blog/ef-core-provider-for-couchbase-general-availability/
NuGet: [Couchbase.EntityFrameworkCore](https://www.nuget.org/packages/Couchbase.EntityFrameworkCore)                       
GitHub repo: https://github.com/couchbaselabs/couchbase-efcore-provider
Docs: https://docs.couchbase.com/efcore-provider/current/start-using-efcore-provider.html
