### ISSUE TITLE
Unable to run a straightforward InMemory sample on Linux

### ISSUE THREAD

**Issue by Mimetis** [dotnet/efcore#1447]
Hi all;
I tried to run a quick sample on a Linux VM.
Installing **Mono** was straightforward and seems to work : 
![Mono Version](http://www.dotmim.com/sitefiles/linuxef/MonoVersion.jpg)

Then installing the **KVM** and the latest **KRE** wasn't so easy, but it's ok :)
![Kvm list](http://www.dotmim.com/sitefiles/linuxef/kvmlist.jpg)

My application folder contains everything required and the **kpm restore** works as expected
![Kvm list](http://www.dotmim.com/sitefiles/linuxef/llapp.jpg)

Here is my **project.json** file :
![Kvm list](http://www.dotmim.com/sitefiles/linuxef/vi.jpg)

And the code is, as you may expect, really simple :

```
    public class FabrikamContext : DbContext
      {
          public DbSet<Customer> Customers { get; set; }
          public DbSet<Image> Images { get; set; }
          public DbSet<ServiceTicket> ServiceTickets { get; set; }

          protected override void OnConfiguring(DbContextOptions builder)
          {
            builder.UseInMemoryStore(false);
          }
     }
```

Here is a result of a **k run** command :

![Kvm list](http://www.dotmim.com/sitefiles/linuxef/krun.jpg)

Is there any problem with **Logging** assembly ?

Thx a lot !

Sebastien Pertus

**Comment by divega** [comment]
@suhasj does this ring any bells for you?

**Comment by suhasj** [comment]
The packages seems to be missing. @Mimetis what happens when you run `kpm restore` and try again ?

**Comment by Mimetis** [comment]
Everything worked fine, when i ve done the kpm restore
I just tried a refresh right now :) 
![](http://www.dotmim.com/sitefiles/linuxef/kpmrestore.jpg)

**Comment by suhasj** [comment]
ok I see your project.json and you should have `aspnet50` instead of `aspnetcore50` since coreclr is not available on Mono. Can you make that change and try again ?

**Comment by davidfowl** [comment]
Yes, @suhasj is right, that is the problem.

**Comment by Mimetis** [comment]
thx guys ! It works pretty fine right now :)
As you said, since coreclr is not available, it make sense to run in within aspnet50

Thx you, my Techdays Demo will works, finally !

Seb
