### ISSUE TITLE
Intermittent System.ExecutionEngineException with DBContext

### ISSUE THREAD

**Issue by camainc** [dotnet/efcore#14487]
Describe what is not working as expected.

Recently started experiencing this error when starting a debug session. It happens just about every other time I start debugging. Very, very frustrating.

```
Exception message:

System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception of type 'System.ExecutionEngineException' was thrown.

Stack trace: Empty
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

I cannot do that - our solution is pretty massive and this error only happens in this solution.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
protected WinsDbContextBase(DbContextOptions options, ICurrentUserContext userContext)
        : base(options) <== error occurs here
        {
            ...
        }```

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.2.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4) VS 2017  15.9.5

**Comment by ajcvickers** [comment]
@camainc I would suggest you file an issue on https://github.com/dotnet/coreclr or on VS feedback (to reach the debugger people) since it's unlikely this is anything that is actionable by the EF team. However, it is likely going to be difficult for those teams to follow up effectively without someway to reproduce what you are seeing, so if you're able to narrow this down to something you can share, then that would be very useful.

**Comment by camainc** [comment]
Ok, but the error only happens in the constructor of DbContext. I'm guessing I'm out of luck getting any help with this one.

**Comment by ajcvickers** [comment]
@camainc We can certainly try to help, but we need something more to work with, and ultimately it will get passed to another team.

**Comment by camainc** [comment]
Thanks, I understand.
