### ISSUE TITLE
ValueBuffer does not release memory as expected.

### ISSUE THREAD

**Issue by beerdog** [dotnet/efcore#14480]
It seems that Microsoft.EntityFrameworkCore.Storage.ValueBuffer does not release references to the queried models after the scope is exited when using .Include() on a referenced entity.

E.g. DbContext with ServiceLifetime.Scoped is loaded after a web api request and reads 2 models from db and each model has 2 referenced models, these 6 models will be read into the ValueBuffer.

When the second identical request occurs, the valuebuffer is still populated with these 6 models and will append 6 new identical models to the buffer.

This is clearly seen in the memory trace afer first request:

![efcore_memory1](https://user-images.githubusercontent.com/3513015/51489415-884d7680-1da8-11e9-863a-3f6754a7fbd2.png)

after second request:

![efcore_memory2](https://user-images.githubusercontent.com/3513015/51489421-8d122a80-1da8-11e9-845d-602235b977c6.png)

The memory will be reclaimed when GC occurs but since the DbContext is scoped per request I believe this buffer should be retained between requests. With this behaviour when running in cloud provider with multiple .net core services with ef core the available memory will easily be consumed.

If this is expected behaviour, it would be nice with some way to disable this cache.

Sourcecode with example provided:

[efcore.memory.zip](https://github.com/aspnet/EntityFrameworkCore/files/2779903/efcore.memory.zip)

### Further technical details
EF Core version: 2.2.1
Database Provider: InMemory / Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2017 15.9.5)

**Comment by ajcvickers** [comment]
@beerdog Everything here in the code and the output looks by-design to me. EF caches metadata for use by multiple requests, but not instance data for your entities.

**Comment by beerdog** [comment]
@ajcvickers I understand that EF caches metadata and that is all good, but if it were only metadata the cache wouldn't grow when requesting the same dataset and there would only be ~1 metadata object for each model. Now there is 4 references to "Value" and 8 references to "LinkedValue" in the ValueBuffer and it is growing for each request. Seems redundant to keep multiple references to the same object.

For us this is a problem when exposing large datasets in an cloud environment with limited memory available.

**Comment by ajcvickers** [comment]
@beerdog Can you explain in detail what this means, "The memory will be reclaimed when GC occurs but since the DbContext is scoped per request I believe this buffer should be retained between requests?"

**Comment by beerdog** [comment]
@ajcvickers Ah I see now that my wording was off.

What I really meant though is that I see that memory is reclaimed when I manually trigger a gc but that I believe that the buffer should NOT be retained between requests. Since the buffer does not seem to be used in subsequent requests, because the buffer will be filled with multiple instances of the same objects.

And from what I've seen, this is only the case when ".Include()" is used, if it's omitted the cache won't continue to grow. Maybe the ".Include()" causes a cache-miss? And the same object will be appended to the cache, just speculation.

**Comment by ajcvickers** [comment]
@beerdog The ValueBuffer instances used for data reader results are not shared across requests. Of course, the memory they use will not be freed until the GC runs.

**Comment by beerdog** [comment]
@ajcvickers Ok, I think I understand now, thank you for your time.

**Comment by vijayls** [comment]
We are facing the same problem. What is the fix?
