### ISSUE TITLE
((Microsoft.EntityFrameworkCore.Internal.InternalDbSet<ModelsEntity.test>)iset).Local = error CS0030: Unable to type“Microsoft.EntityFrameworkCore.DbSet<T>”to“Microsoft.EntityFrameworkCore.Internal.InternalDbSet<ModelsEntity.test>”

### ISSUE THREAD

**Issue by jian007** [dotnet/efcore#14486]
public class BaseDbContex:DbContext
    {
        public BaseDbContex():base()
        {
        }

        public BaseDbContex(DbContextOptions<BaseDbContex> dbContextOptions) : base(dbContextOptions)
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //base.OnConfiguring(optionsBuilder.UseMySql(@"server=127.0.0.1;userid=root;password=root;port=3306;database=autofacdemo;allowPublicKeyRetrieval=true;Character Set=utf8;"));
            base.OnConfiguring(optionsBuilder.UseSqlServer(@"sdata source=DESKTOP-JIAN\MSSQLSERVER_2;initial catalog=Autofacdemo;user id=sa;password=123"));

        }
    }

        BaseDbContex BaseDbContex = new BaseDbContex();

        public DbSet<T> iset { get; set; }
        public BaseDAL()
        {
            iset = BaseDbContex.Set<T>();
        }

**Comment by ajcvickers** [comment]
@jian007 Errors like this usually indicate mismatched package versions. For example, using some EF/ASP.NET packages from 2.1, with others from 2.2. If this is not the case, then please post a small, runnable project/solution or complete code listing that demonstrates the error and we can re-open the issue.

**Comment by jian007** [comment]
https://github.com/jian007/AutoFacNetCoreDemo

**Comment by jian007** [comment]
> @ jian007这样的错误通常表示不匹配的软件包版本。例如，使用2.1中的某些EF / ASP.NET包，以及2.2中的其他包。如果不是这种情况，那么请发布一个小的，可运行的项目/解决方案或完整的代码清单来演示错误，我们可以重新打开该问题。

https://github.com/jian007/AutoFacNetCoreDemo
