### ISSUE TITLE
Intermittent System.ExecutionEngineException with EF Core DBContext

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/efcore#14495]
_From @camainc on Tuesday, 22 January 2019 23:55:52_

After updating the nuget packages in my solution, I started experiencing this error when starting a debug session. It happens almost every other time I start debugging.  The stack trace is empty, there is no inner exception, and the only thing I can do is stop execution and then restart the debugging session.

Exception message:

System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception of type 'System.ExecutionEngineException' was thrown.

Stack trace: Empty
Steps to reproduce

protected WinsDbContextBase(DbContextOptions options, ICurrentUserContext userContext)
        : base(options) <== The error occurs here
        {
            ...
        }```

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.2.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4) VS 2017  15.9.5

_Copied from original issue: dotnet/coreclr#22137_

**Comment by camainc** [comment]
LOL, thanks. When I posted this on the EF Core issues list, I was told to post it on to the Core CLR list.

**Comment by ajcvickers** [comment]
See https://github.com/aspnet/EntityFrameworkCore/issues/14495

**Comment by ErikEJ** [comment]
Endless loop??

**Comment by camainc** [comment]
LOL

**Comment by camainc** [comment]
![image](https://user-images.githubusercontent.com/944606/51627117-03707300-1ef6-11e9-8474-47e1815b9110.png)
