### ISSUE TITLE
Custom IEntityTypeConvention registration

### ISSUE THREAD

**Issue by ilmax** [dotnet/efcore#1450]
Hi, I would like to know if the IEntityTypeConvention is an extension point, since I've assumed it is, I developed a custom extension, but I'm failing registering it.
Currently I've tried to write `modelBuilder.EntityTypeConventions.Add(new MyCustomConvention());` on `OnModelCreating` but it does not work because all entities are already added to the model and entity conventions are not fired. I gave a quick look at the code and found that the only way to add custom conventions is writing a custom `IModelBuilderFactory`. is that right?

**Comment by divega** [comment]
I think the short answer is that a lot of this stuff isn't implemented yet. @AndriySvyryd can probably answer in more detail.

**Comment by ilmax** [comment]
@divega Thanks, feel free to close!

**Comment by AndriySvyryd** [comment]
@ilmax Yes, for now the only way to do it properly is in a custom  IModelBuilderFactory.
