### ISSUE TITLE
Evaluate a LET clause ONCE

### ISSUE THREAD

**Issue by sbreed** [dotnet/efcore#14524]
Hello:

Perhaps this is already implemented, but I'd like to request a feature such as evaluating a let clause once when making a query.

Suppose I have two entities: Employee and Company.  I'm making a query that returns the companies a user manages.

For example...
```
public IQueryable<Company> GetUserCompanies(int userId)
{
  return from c in this.DbContext.Companies
         let user = this.DbContext.Users.FirstOrDefault(u => u.ID == userId && !u.IsDeleted)
         where user != null && c.Managers.Any(m => m.UserID == user.ID)
         select c;
}
```

Because of the let clause, a trip to the database is required for EACH company, which isn't efficient because the user should always be the same.  Also, in this example, I know I could skip the let clause altogether; I'm just using it to show my point.  Additionally, I know I can make two calls to the DB by first getting the user and -- if the user is not null -- then getting the companies, but this requires two trips to the database.  Nonetheless, my code is just an example that illustrates the point.

What would be nice would be to have something like the following...

```
public IQueryable<Company> GetUserCompanies(int userId)
{
  return from c in this.DbContext.Companies
         const user = this.DbContext.Users.FirstOrDefault(u => u.ID == userId && !u.IsDeleted)
         where user != null && c.Managers.Any(m => m.UserID == user.ID)
         select c;
}
```

Granted, it doesn't have to be the const keyword, but I'm envisioning that the const keyword -- instead of let -- would indicate that I want the variable user to be evaluated once and only once, negating the multiple evaluations of let.

Again, it my hope that this is an easy request unless there's some other way that this can be achieved without making two or more trips to the DB.  Thanks again!

**Comment by tuespetre** [comment]
The `let` clause translates to a call to:

`.Select(c => new { c, user = this.DbContext.Users.FirstOrDefault(...) })`

Now theoretically, if the subtree `this.DbContext.Users.FirstOrDefault(...)` does not have any free variables, the query compiler could be made to lift that subtree 'up and out' so that it would in fact only be executed once. But that's still ultimately going to be two calls to the database.

Perhaps you could write your LINQ query as:

```
from c in this.DbContext.Companies
join u in this.DbContext.Users on u.ID equals userId
where !u.IsDeleted && !c.Managers.Any(m => m.UserID == u.ID)
select c
```

which should generate a single SQL query like:

```
SELECT c.*
FROM dbo.Companies AS c
JOIN dbo.Users AS u
    ON u.ID = @userId
WHERE u.IsDeleted = 0 AND NOT EXISTS (
    SELECT 1
    FROM dbo.Managers AS m
    WHERE m.CompanyID = c.ID AND m.UserID = u.ID
)
```

**Comment by ajcvickers** [comment]
@smitpatel to follow up.

**Comment by smitpatel** [comment]
At present above query is N+1 which would change in 3.0 to be one SQL query to fetch all data. Likely to be using cross/outer apply kind of SQL syntax.
Important point is, let is just linq sugar. Expression trees don't have concept of variables. So even if you use let, your subtree will be repeated multiple times in the expression. Hence generated SQL would also have translation of subtree multiple times. According to @divega, SQL query engines can optimize them and only evaluate once and use result again.

Apart from that, we are not planning to do anything to evaluate "let" once. (in strict sense)

**Comment by divega** [comment]
@smitpatel slightly related to this, I think we have talked about a potential optimization that would try to convert CROSS/OUTER APPLY to JOINs when possible, the (untested) idea being that the engine can be better at optimizing JOINs. Do you know if we are tracking this idea somewhere?

**Comment by smitpatel** [comment]
Our query pipeline does not generate apply when join is possible. Hence we don't need such optimization step. (this is true for 2.2 pipeline also)

**Comment by sbreed** [comment]
Thank you, guys.  As usual, your input and feedback is most appreciated.

**Comment by GeoMarkou** [comment]
This is very misleading. I only realised this was happening after upgrading to .Net 6 and I could see the generated SQL. [The documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/let-clause) for this feature states:

> In a query expression, it is sometimes useful to **store the result** of a sub-expression in order to use it in subsequent clauses. You can do this with the let keyword, which creates a new range variable and initializes it with the **result of the expression** you supply.

Reading this isn't even open for interpretation - it directly states that it works by storing a complex query ONCE, so we can then use the result in `WHERE` / Outer `SELECT` / `ORDER BY` / etc... But in actuality, it's being translated to: "copy/paste this complex query so it's run multiple times"??? I thought I was writing good, performant SQL based on the documentation. Along with the fact that the syntax is misleading as it's the same as a normal variable assignment. The only reason you would even use this keyword is a real foot-gun as you end up generating completely jank SQL which selects the same complex queries / joins over and over again, and tanks your database.

Most SQL languages e.g. PostgreSQL allow you to define a temporary variable in a query to improve performance. Why on earth isn't it using that feature when available? At the very least, update your documentation and syntax to make it more obvious what is going on. Example syntax I spent 3 seconds thinking up: Don't allow the normal "returns a value result" functions when using `let` as this implies that the result is being evaluated and stored. Enforce (using errors) that people have to use the queryable syntax, which is actually how it behaves.

```C#
// Before
from c in db.Companies
    let users = db.Users.Where(u => u.ID == userId && !u.IsDeleted).ToList()
    let user = db.Users.FirstOrDefault(u => u.ID == userId && !u.IsDeleted)

// After
from c in db.Companies
    let users = db.Users.Where(u => u.ID == userId && !u.IsDeleted)
    // I don't think there's actually a "first or default" queryable equivalent
    let user = db.Users.FirstOrDefaultQueryable(u => u.ID == userId && !u.IsDeleted)
```

Obviously the ideal situation would be to make it use temporary variables as expected but I understand there may be technical difficulties.

**Comment by roji** [comment]
@GeoMarkou can you post a minimal, runnable code sample? In your first query ("Before") there's a ToList, which gets executed as a separate query (and database roundtrip) - that's very much by design.

If the complaint is about the let expression getting duplicated in the final SQL, then this may be a case of pending selectors (/cc @maumar) - we have work planned on improving this but that will take time. Note that the LINQ documentation you cited above is conceptual documentation about how LINQ works; while it describes how LINQ to Objects evaluates LINQ operators in-memory, it does not guarantee that when translated to SQL (or anything else), your query will be generated in a particular way.

**Comment by GeoMarkou** [comment]
> If the complaint is about the let expression getting duplicated in the final SQL

@roji yes this is exactly what's happening in my case. It's a known issue then I'm guessing, good to know it's not intended to work this way at least. Do you still need a code sample?

**Comment by roji** [comment]
@GeoMarkou no, I think we're fine here without a code sample - the issue known and understand. We definitely do aim to make this better, but it's unfortunately not trivial.
