### ISSUE TITLE
Document how to write code that works both with EF Core IQueryableAsync and local collections

### ISSUE THREAD

**Issue by sandersaares** [dotnet/efcore#14529]
I find myself having code that performs queries against `IQueryable<T>` and uses the `.ToArrayAsync()` method family. This works fine.

But sometimes I also want to use this code on collections that are not backed by EF. Maybe in test code, maybe in code that caches some query results and modifies them locally.

If I just pass a `new List<T>().AsQueryable()` into such code, the `.ToArrayAsync()` call explodes with an exception, stating that it can only be called on a provider that implements `IAsyncQueryable`.

Okay fine but how do I write asynchronous code that can handle both EF backed IQueryable and regular AsQueryable backed IQueryable? I request this be documented at https://docs.microsoft.com/en-us/ef/core/querying/async

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by JanEggers** [comment]
same issue here.

I solved it be wrapping the extension like SafeToListAsync that first checks if the underliing queryable supports async and if not uses the synchronous version within Task.Run.

I dunno if thats the way to do it but it worked for me.

**Comment by ajcvickers** [comment]
@sandersaares  For now, I think the workaround suggested by @JanEggers is the way to go on this. Diego may have more information, but as far as I know there isn't a good way to do this when using the current implementation. I hope that things will change once async enumerable is a first-class part of .NET Core, but I don't know that for sure. Putting this in 3.0 now and assigning to @divega to loop back on the experience later.

**Comment by christiansk** [comment]
Would it be possible to do what's being asked here using the System.Linq.Async package from [Reactive Extensions](https://github.com/dotnet/reactive)?

**Comment by yruson** [comment]
@JanEggers Can you share your implementation, I don't know what method to use to know if IQueryable's Provider supports asynchronous. Thank you very much.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
