### ISSUE TITLE
Lock row Mysql 

### ISSUE THREAD

**Issue by aimprogman** [dotnet/efcore#14538]
Lock row in EF CORE  Database Mysql

I can not implement  following query in EF Core

```
SELECT * FROM person WHERE id=1 FOR UPDATE
```

### Steps to reproduce
I want use it as:

```c#
this._context.Person.FirstOrDefault(a => a.id==1).ForUpdate();
```

**Comment by ajcvickers** [comment]
Duplicate of #6717

**Comment by aimprogman** [comment]
Thanks, I will subscibe  #6717
