### ISSUE TITLE
Why is there no IExpressionFragmentTranslatorPlugin

### ISSUE THREAD

**Issue by Bitsonthefloor** [dotnet/efcore#14557]
I am working more with the latest EF core 2.2.1 and I noticed that for the expression translators there is a plugin interface for adding translators for both members and method calls but none for expression fragment. Was this a design decision or something that was overlooked?

I ask because I have mocked such and interface and implemented an extended  RelationalCompositeExpressionFragmentTranslator that allows me to intercept null checks and call a custom NullHandler (thus allowing for custom isnull type expressions in relation to ValueConverters, i.e. use a value or logic operation instead of sql IS NULL for non nullable fields with a null meaning value) but I would prefer to not have to monkey code such capabilities in.

**Comment by ajcvickers** [comment]
Will investigate for 3.0 whether it makes sense to expose this as a plugin API.

**Comment by mrswain** [comment]
I have a feature branch with the changes necessary to add it if you want to look those over, I can even do a PR if you want.

https://github.com/aspnet/EntityFrameworkCore/compare/master...mrswain:add-missing-eftplugin

**Comment by smitpatel** [comment]
@mrswain - Can you post what kind of ExpressionTree are you trying to process? And why it is a plugin?

**Comment by ajcvickers** [comment]
Closing as we don't plan to add plug-in support specifically for fragments.
