### ISSUE TITLE
Investigate cancellation design for new IAsyncEnumerable<T> in the context of EF Core

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#14552]
This is part of https://github.com/aspnet/EntityFrameworkCore/issues/12047, but I think important enough to track it separately. 

The cancellation story for the new `IAsyncEnumerable<T>` has some peculiarities, e.g. it requires associating a `CancellationToken` with an `IAsyncEnumerable<T>` calling the `WithCancellation` extension method, so that then you can use the `IAsyncEnumerable<T>` with `await foreach`. 

This is a bit strange because now you have associated an instance of an object cannot be reused (the `CancellationToken`) with an instance of an object that by design should be reusable. 

We should look at whether this works well with the fact in the context of EF Core. 

For example, how does the cancellation token flow to IAsyncQueryProvider.ExecuteAsync?

**Comment by ajcvickers** [comment]
@divega to follow up with C# people.

**Comment by ajcvickers** [comment]
Chatted with @smitpatel  and @divega. Not sure we need to do anything more for 3.0.

**Comment by divega** [comment]
I think we should only need to do some smoke testing to check that our operators and things like AsAsyncEnumerable().WithCancellation(ct) flow cancellation correctly.

**Comment by roji** [comment]
I went over our codebase and we seem to be doing everything right:

* Whenever we do await/foreach (e.g. [ToListAsync](https://github.com/dotnet/efcore/blob/0065e1d2680f5fcc6ac20d560d038f3782ce2376/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2324)), we use WithCancellation to flow the cancellation token in.
* Methods returning IAsyncEnumerator accept a cancellation token and flow it in.
* Methods returning IAsyncEnumerable which *aren't* iterator block methods don't accept a cancellation token, which avoids burning it into the returned instance. Thus the instance can be reused multiple times, each time with a new cancellation token.
* We don't have any async iterator block methods (i.e. async + yield), so we don't need to use [EnumeratorCancellation]

Good explanation/guidelines: https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8
