### ISSUE TITLE
Incorrect JSON Serialization on .NET Framework 4.7.2 if Entity has [Serializable] attribute and Lazy Loading enabled

### ISSUE THREAD

**Issue by Xantrul** [dotnet/efcore#14558]
I am not 100% sure that the issue is with EF Core, but this seems like a good place to start. Also, given how specific this issue is - it might be not worth fixing, but it definitely worth at least documenting it here so other can find it (spent whole day yesterday trying to solve this).

### Conditions to get repro
- Database model lives in its own class library with target "netstandard2.0"
- Application using database has target of ".NET Framework 4.7.2"
- Entity Has [Serializable] attribute set
- Lazy Loading is enabled

### Steps to reproduce
Open attached solution and run `EfCoreRepro.ClassicConsoleApp`

### Expected output
`{"Id":1,"Age":25,"Name":"John Smith"}`

### Actual output
`{"__interceptors":[{}],"__interfaces":["Microsoft.EntityFrameworkCore.Proxies.Internal.IProxyLazyLoader, Microsoft.EntityFrameworkCore.Proxies, Version=2.2.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"],"__baseType":"EfCoreRepro2.DB.Models.Person, EfCoreRepro2.DB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","__proxyGenerationOptio
ns":{"hook":{},"selector":null,"mixins":null,"baseTypeForInterfaceProxy.AssemblyQualifiedName":"System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},"__proxyTypeId":"class","__delegateToBase":false,"__data":[25,1,"John Smith"]}`

### Additional info
- Issue does not repro if application is targeting .NET Core (see `CoreConsoleApp` in the repro solution)
- Commenting out [Serializable] attribute produce correct output
- How we ended up with this configuration in the first place: We are working on adding few new services to the existing .NET Framework solution, and we want them to target .NET Core so we can run new ones serverless in the cloud. In order to allow both new and old applications to share database model we upgraded Database project from EF6 to EF Core (and re-targeted the rest of the solution to 4.7.2).

### Further technical details
EF Core version: 2.2.1
Database Provider: SqlLite (in memory). Originally found with Npgsql
Operating system: Windows 10 (dev box) and Windows 2016 (beta server)
IDE: JetBrains Rider 2018.3.1

[EfCoreRepro2.DB.zip](https://github.com/aspnet/EntityFrameworkCore/files/2814164/EfCoreRepro2.DB.zip)

**Comment by ajcvickers** [comment]
@JamesNK Is this something you have seen before? This is serialization of Castle dynamic proxies with JSON.NET. On Core, it nicely ignores the proxy type and serializes to the real class contract. On .NET Framework, it serializes using the proxy type.

**Comment by JamesNK** [comment]
If a type has `[Serializable]` and implements `ISerializable` then the content of `GetObjectData()` is used as JSON.

**Comment by ajcvickers** [comment]
@JamesNK But do you know why the behavior here is different with .NET Framework and .NET Core? (It could be that the proxies are generated differently, but thought you might have seen this before.)

**Comment by ajcvickers** [comment]
@Xantrul This looks like an issue with the way [Castle proxies](https://github.com/castleproject) handles serialization--please report to them. (The behavior for .NET Core is what we would expect.) Closing this as external, but if there is something we're doing wrong here then please comment and we can re-open and fix.
