### ISSUE TITLE
Remove With Condition

### ISSUE THREAD

**Issue by mohamedmahmoudalemam** [dotnet/efcore#14596]
Why not add an overload to Remove and RemoveRange methods that take a predicate:
ex: context.Employees.Remove(x => x.Id ==1);
and context.Employees.RemoveRange(x => x.DepartmentId == 1);

So one sql command and no need to get either object to delete or list to delete.

**Comment by JanEggers** [comment]
https://github.com/zzzprojects/EntityFramework-Plus

**Comment by mohamedmahmoudalemam** [comment]
Official support will be nice.

**Comment by ajcvickers** [comment]
Duplicate of #795
