### ISSUE TITLE
Operations of Entity Framework Core for Views

### ISSUE THREAD

**Issue by kickgod** [dotnet/efcore#14592]
Describe what is not working as expected.

----
**`How does EFCore query complex views? Or how to map views to entity models! Use ADO.NET?`**

**`EF Core does not have context.Database.SqlQuery support?`**

### Further technical details
EF Core version: 2.1.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win10
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ErikEJ** [comment]
You can use Query Types: https://docs.microsoft.com/en-us/ef/core/modeling/query-types

**Comment by kickgod** [comment]
Thank you very much.
