### ISSUE TITLE
RawSql ORDER BY [t].[id]

### ISSUE THREAD

**Issue by CTGControls** [dotnet/efcore#14606]
Describe what is not working as expected.
How can I remove the last order by ID. I need the results from the RAWSQL AS IS (ordered by departments.userfriendlyName). Is there a better way of doing this then RAWSQL with out being evaluated locally?
**I am using raw SQL:**

``` sql
SELECT  tblDepartmentsHeader.id, 
	tblDepartmentsHeader.approvedRejectedByIp, 
	tblDepartmentsHeader.approvedRejectedByUserId, 
	tblDepartmentsHeader.approvedRejectedOnDate, 
	tblDepartmentsHeader.changeKey, 
	tblDepartmentsHeader.deletedByIp, 
	tblDepartmentsHeader.deletedByUserId, 
	tblDepartmentsHeader.deletedOnDate, 
	tblDepartmentsHeader.isActive, 
	tblDepartmentsHeader.isDeleted, 
	tblDepartmentsHeader.lastModifiedByIp, 
	tblDepartmentsHeader.lastModifiedByUserId, 
	tblDepartmentsHeader.lastModifiedOnDate, 
	tblDepartments.userfriendlyName
FROM 	ctgcontr_FfmDBContext.departmentsHeader AS tblDepartmentsHeader INNER JOIN
	ctgcontr_FfmDBContext.departments as tblDepartments ON 
	tblDepartmentsHeader.id = tblDepartments.departmentsHeaderId
WHERE   (tblDepartments.id IN 
		(SELECT TOP (1000) MAX(DISTINCT id) AS id	
		FROM ctgcontr_FfmDBContext.departments AS departments
		GROUP BY departmentsHeaderId
		ORDER BY MAX(DISTINCT createdOnDate), id))
ORDER BY userfriendlyName desc
```

**The SQL is being excited is:**
``` sql
SELECT [tblDepartmentsHeader.departments].[id], [tblDepartmentsHeader.departments].[changeKey], [tblDepartmentsHeader.departments].[createdByIp], [tblDepartmentsHeader.departments].[createdByUserId], [tblDepartmentsHeader.departments].[createdOnDate], [tblDepartmentsHeader.departments].[departmentsHeaderId], [tblDepartmentsHeader.departments].[userfriendlyName]
      FROM [departments] AS [tblDepartmentsHeader.departments]
      INNER JOIN (
          SELECT [tblDepartmentsHeader0].[id], (
              SELECT TOP(1) [d1].[userfriendlyName]
              FROM [departments] AS [d1]
              WHERE [tblDepartmentsHeader0].[id] = [d1].[departmentsHeaderId]
          ) AS [c]
          FROM (
               SELECT TOP(1000) tblDepartmentsHeader.id, tblDepartmentsHeader.approvedRejectedByIp,
                                                  tblDepartmentsHeader.approvedRejectedByUserId, tblDepartmentsHeader.approvedRejectedOnDate,
                                                  tblDepartmentsHeader.changeKey, tblDepartmentsHeader.deletedByIp,
                                                  tblDepartmentsHeader.deletedByUserId, tblDepartmentsHeader.deletedOnDate,
                                                  tblDepartmentsHeader.isActive, tblDepartmentsHeader.isDeleted,
                                                  tblDepartmentsHeader.lastModifiedByIp, tblDepartmentsHeader.lastModifiedByUserId,
                                                  tblDepartmentsHeader.lastModifiedOnDate,
                                                  tblDepartments.userfriendlyName
                                          FROM     ctgcontr_FfmDBContext.departmentsHeader AS tblDepartmentsHeader INNER JOIN
                                                   ctgcontr_FfmDBContext.departments as tblDepartments ON tblDepartmentsHeader.id = tblDepartments.departmentsHeaderId
                                          WHERE   (tblDepartments.id IN
                                                      (SELECT TOP (1000) MAX(DISTINCT id) AS id
                                                          FROM ctgcontr_FfmDBContext.departments AS departments
                                                          GROUP BY departmentsHeaderId
                                                          ORDER BY MAX(DISTINCT createdOnDate), id)) order by userfriendlyName
          ) AS [tblDepartmentsHeader0]
          WHERE ([tblDepartmentsHeader0].[isDeleted] <> 1) OR [tblDepartmentsHeader0].[isDeleted] IS NULL
          ORDER BY (
              SELECT TOP(1) [d0].[userfriendlyName]
              FROM [departments] AS [d0]
              WHERE [tblDepartmentsHeader0].[id] = [d0].[departmentsHeaderId]
          ), [tblDepartmentsHeader0].[id]
          OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
      ) AS [t] ON [tblDepartmentsHeader.departments].[departmentsHeaderId] = [t].[id]
      ORDER BY [t].[id]
```

**My Linq:**
``` csharp
            IEnumerable<departmentsHeader> departmentsHeader =
                        await 
                        (from tblDepartmentsHeader in _FFM_DbContext.departmentsHeader
                            .FromSql(sql, parameterPageSize, parameterSearchString).Include("departments")
                        where tblDepartmentsHeader.isDeleted != true
                        select tblDepartmentsHeader
                        )
                        .Skip((int)((pageNumber * pageSize) - pageSize))
                        .Take((int)pageSize)
                        .ToListAsync();
```

### Further technical details
ASP.NET Core 2.2.1
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1607 LTSB
IDE: Visual Studio 2017 15.9.6

**Comment by divega** [comment]
@CTGControls the call to FromSql replaces the mapping of `_FFM_DbContext.departmentsHeader` in the LINQ query to whatever SQL you provide. In order to implement the Include, the Where, the projection and the paging operations, it needs to compose over the SQL you provided. EF Core has to implement this without changing the SQL you provided. 

I am not 100% sure I understand your question, but perhaps you are looking after something like I have described in https://github.com/aspnet/EntityFrameworkCore/issues/14525. It is about an hypothetical new API that would be used to replace the SQL of the whole query with your own. 

Another option could be to add your own explicit OrderBy on the LINQ query instead of having it in the SQL.

I hope this helps.

**Comment by CTGControls** [comment]
First thank for your fast response!!

Maybe you did answer this question:
My question is how do I remove the "ORDER BY [t].[id]" from the EF _(The SQL is being excited is:)_ query. The ORDER BY [t].[id] seems to me to be over reaching and presumptuous as I can not see why it is needed. 

My problem with a OrderBy in the Linq is I am not sure how to do it. The data I need to order by is in a joined table "tblDepartments.userfriendlyName" that is in the .Include("departments"). I am not sure the correct syntax for the Linq to make this happen on the Database, I don't see the reason to waste CPU Cycles. 

My entities:
**departmentsHeader**
    public class departmentsHeader : tableHeaderParent
    {
        public List<departments> departments { get; set; }
    }

**departments**
    public class departments : tableHeaderChild
    {
        //ID of the Department Header
        [Column(Order = 200)]
        [Display(Name = "ID of the Department Header")]
        public System.Guid departmentsHeaderId { get; set; }
        [ForeignKey("departmentsHeaderId")]
        public virtual departmentsHeader departmentsHeader { get; set; }


        //Name of the Department
        [Column("userfriendlyName", Order = 201)]
        [MaxLength(50)]
        [Display(Name = "user friendly Name")]
        public string userfriendlyName { get; set; }

    }

**tableHeaderParent**
   public abstract class tableHeaderParent
    {
        //The ID of your object with the name of the Contacts
        [Key]
        [Column("id", Order = 0)]
        [Required]
        public Guid id { get; set; }


        //A byte[] with the name of the vBinChangeKey Change Key is used in some tables for recored change history. When the applaction requires advanced tracking.
        [Column("changeKey", Order = 2)]
        [Display(Name = "Change Key")]
        [Timestamp]
        public byte[] changeKey { get; set; }

        // A Bool with the name of the bitRecordActive used to disable a Recipient
        [Column("isActive", Order = 3)]
        [Display(Name = "Is Active")]
        [Required]
        public bool isActive { get; set; } = true;

        //A Bool with the name of the bitRecordDeleted used to delete a record
        [Column("isDeleted", Order = 4)]
        [Display(Name = "Is Deleted")]
        public bool? isDeleted { get; set; } = false;

        //The date the record was Updated
        [Column("lastModifiedOnDate", Order = 8)]
        [Display(Name = "Last Modified On Date")]
        public DateTime? lastModifiedOnDate { get; set; } = DateTime.UtcNow;

        //User ID of the user who Updated the record
        [Column("lastModifiedByUserId", Order = 9)]
        [Display(Name = "Last Modified By User ID")]
        public Guid? lastModifiedByUserId { get; set; }

        //User IP Address of the user who Updated the record
        [Column("lastModifiedByIp", Order = 10)]
        [MaxLength(50)]
        [Display(Name = "Last Modified By IP")]
        public string lastModifiedByIp { get; set; }

        //The date the record was Deleted
        [Column("deletedOnDate", Order = 11)]
        [Display(Name = "Deleted On Date")]
        public DateTime? deletedOnDate { get; set; }

        //User ID of the user who Deleted the record
        [Column("deletedByUserId", Order = 12)]
        [Display(Name = "Deleted By User ID")]
        public Guid? deletedByUserId { get; set; }

        //User IP Address of the user who Deleted the record
        [Column("deletedByIp", Order = 13)]
        [MaxLength(50)]
        [Display(Name = "Deleted By IP")]
        public string deletedByIp { get; set; }

        //The date the record was Approved
        [Column("approvedRejectedOnDate", Order = 14)]
        [Display(Name = "Approved Rejected On Date")]
        public DateTime? approvedRejectedOnDate { get; set; }

        //User ID of the user who Approved the record
        [Column("approvedRejectedByUserId", Order = 15)]
        [Display(Name = "Approved Rejected By User ID")]
        public Guid? approvedRejectedByUserId { get; set; }

        //User IP Address of the user who deleted the record
        [Column("approvedRejectedByIp", Order = 16)]
        [MaxLength(50)]
        [Display(Name = "Approved Rejected By IP")]
        public string approvedRejectedByIp { get; set; }

    }

**tableHeaderChild**
    public abstract class tableHeaderChild
    {
        //The ID of your object with the name of the Contacts
        [Key]
        [Column("id", Order = 0)]
        [Required]
        public Guid id { get; set; }


        //A byte[] with the name of the vBinChangeKey Change Key is used in some tables for recored change history. When the applaction requires advanced tracking.
        [Column("changeKey", Order = 2)]
        [Display(Name = "Change Key")]
        [Timestamp]
        public byte[] changeKey { get; set; }

        //The date the record was created
        [Column("createdOnDate", Order = 5)]
        [Display(Name = "Created On Date")]
        [Required]
        public DateTime createdOnDate { get; set; } = DateTime.UtcNow;

        //User ID of the user who created the record
        [Column("createdByUserId", Order = 6)]
        [Display(Name = "Created By User ID")]
        [Required]
        public Guid createdByUserId { get; set; }

        //User IP Address of the user who created the record
        [Column("createdByIp", Order = 7)]
        [MaxLength(50)]
        [Display(Name = "Created By IP")]
        [Required]
        public string createdByIp { get; set; }

    }

**Comment by divega** [comment]
> The ORDER BY [t].[id] seems to me to be over reaching and presumptuous as I can not see why it is needed.

:smile: This additional ORDER BY is usually introduced because of how `Include()` to collections is implemented in EF Core.We generate two separate SQL queries (one of the root entity and one for the collection). We then need to zip the results from both queries together as they get returned, for which we need some common deterministic ordering criteria that can be applied to both queries. And that is the ORDER BY. 

I took another look at your SQL, and I believe I now understand that you want to order 'departmentsHeader` instances by the `userFriendlyName` on the latest `departments` entity. 

Given all this, you could try removing `.Include("departments")` from your LINQ query. If you still need to load the `departments` instances corresponding to the `departmentsHeader` returned by you query, you can achieve that by executing a second query. Keep in mind that if both queries are tracked, all navigation properties will be automatically fixed up to point to the right entities as soon as each individual entity is materialized. However, if you do any query composition (e.g. Skip, Take, Where), your SQL query will become a subquery in the EF Core query, and the database engine will not guarantee that your ORDER BY is preserved. 

My second recommendation is to revisit your model to include a relationship (FK and reference navigation) from the `departmentsHeader` to its corresponding latest created `departments`. This will require some additional logic in the application to maintain the value of the FK updated, but it should allow you to write everything this query more easily and completely in LINQ. 

Yet another alternative you could consider is to create a database view for the latest created `departements`. You can then map this view to an entity in EF Core and establish a 1:0..1 relationship between `departmentHeader` and this new entity, based on the value of `departmentHeader`'s PK. And you can navigate this relationship to reach `userFriendlyName` and OrderBy it. You need to be very careful to never update entities mapped to this database view, since the database view will not be updatable. I would recommend mapping this to a query type so that we never try to update it, but currently EF Core does not allow returning query types and tracked entities from the same query.

**Comment by ajcvickers** [comment]
@divega to follow up

**Comment by CTGControls** [comment]
This data was just being used on a razor page, I did not need the change tracking and some of the other great things that EF provides. So in the end I used ADO.NET for this. I was also able to combine 2 query's into one. @divega suggestions and help where all helpful and interesting. I may need to use some in the near future. 

`string sql = @"SELECT  [departmentsHeader].[id], [departmentsHeader].[approvedRejectedByIp],
                                    [departmentsHeader].[approvedRejectedByUserId], [departmentsHeader].[approvedRejectedOnDate],
                                    [departmentsHeader].[changeKey], [departmentsHeader].[deletedByIp],
                                    [departmentsHeader].[deletedByUserId], [departmentsHeader].[deletedOnDate],
                                    [departmentsHeader].[isActive], [departmentsHeader].[isDeleted],
                                    [departmentsHeader].[lastModifiedByIp], [departmentsHeader].[lastModifiedByUserId],
                                    [departmentsHeader].[lastModifiedOnDate],
                                    [departments].[id] As departmentsId,
                                    [departments].[createdOnDate],
                                    [departments].[createdByUserId],
                                    [departments].[createdByIp],
                                    [departments].[userfriendlyName],
                                    COUNT(*) OVER( PARTITION BY 1 ) AS paginationTotalCount
                             FROM    departmentsHeader AS departmentsHeader INNER JOIN
                                         departments as departments ON departmentsHeader.id = departments.departmentsHeaderId
                             WHERE   (([departmentsHeader].[isDeleted] != 1 OR [departmentsHeader].[isDeleted] IS NULL )AND departments.id IN
                                         (SELECT id
											From(
												SELECT id, userfriendlyName ,
													RANK() OVER (PARTITION BY departmentsHeaderId ORDER BY createdOnDate DESC) departmentsHeaderId_Rank
												FROM departments AS departments

											) AS tbl1
										Where tbl1.departmentsHeaderId_Rank = 1)";`


Helper method:
`        public async Task<DataTable> GetUsingPaginationWithUserfriendlyName(string sql, string search, int? sort, int? pageNumber = 1, int? pageSize = 10)
        {
            DataTable dataTable = new DataTable();

            SqlParameter parameterPageSize = new SqlParameter("@pageSize", 1000000);

            SqlParameter parameterSkip = new SqlParameter("@Skip", (int)((pageNumber * pageSize) - pageSize));
            SqlParameter parameterTake = new SqlParameter("@Take", (int)pageSize);

            SqlParameter parameterSearchString;
            if (string.IsNullOrEmpty(search) != true)
            {
                //format the search string for multi word search 
                //input of the work order that user wants to search
                search = new FFM.Helpers.SearchString().build(search);

                //Add the search string to the SQL Parameter
                parameterSearchString = new SqlParameter("@SearchString", search);

                //Add the where clause to the SQL query statement
                sql += "AND [userfriendlyName] LIKE @SearchString )";
            }
            else
            {
                //If there is not a search return everying
                parameterSearchString = new SqlParameter("@SearchString", "%");
                sql += ")";
            }

            switch (sort)
            {
                default:
                    sql += @"ORDER BY userfriendlyName";
                    break;
                case 1:
                    sql += @"ORDER BY userfriendlyName desc";
                    break;
                case 2:
                    sql += @"ORDER BY createdOnDate";
                    break;
                case 3:
                    sql += @"ORDER BY createdOnDate desc";
                    break;
            }

            sql += @" OFFSET (@Skip) ROWS FETCH NEXT (@Take) ROWS ONLY";



            var connectionString = _configuration.GetConnectionString("app");

            if (string.IsNullOrEmpty(connectionString))
                throw new ArgumentException("No connection string in config.json");

            using (var connection = new SqlConnection(connectionString))
            {
                using (var command = new SqlCommand(sql, connection))
                {
                    command.Parameters.Add(parameterSearchString);
                    command.Parameters.Add(parameterPageSize);
                    command.Parameters.Add(parameterSkip);
                    command.Parameters.Add(parameterTake);
                    try
                    {
                        await connection.OpenAsync();
                        IDataReader dataReader = await command.ExecuteReaderAsync();

                        dataTable.Load(dataReader);
                        connection.Close();
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "", null);
                    }
                    finally
                    {
                        connection.Close();
                    }
                }
            }

            return dataTable;
        }
`

**Comment by sdanyliv** [comment]
I'm crying how it looks like. You can create this SQL by [linq2db extension for EF Core](https://github.com/linq2db/linq2db.EntityFrameworkCore) which support Window Functions.
Also I have written similar pagination as an sample before, with no RAW SQL
https://github.com/linq2db/linq2db/issues/1402#issuecomment-438961009

**Comment by ajcvickers** [comment]
@divega After having read through all this again it doesn't seem like there is anything actionable here. Moving this to discussions so that you can follow up in your own time. Feel free to push back if there is something else we need to track here.

**Comment by smitpatel** [comment]
Nothing actionable on EF side. We need Order by to combine collection include results on client side so we cannot remove it. If we see user specified order by inside expression tree, we preserve it. If it is opaque to us like in raw SQL then we cannot do anything about it.
