### ISSUE TITLE
Question: Generate migrations from code.

### ISSUE THREAD

**Issue by alexdrl** [dotnet/efcore#14612]
Hello, I'm trying to create a console app that tries to generate the migration code and detects if there are some operations that will be created in the generated code.

Ideally, if the `dotnet ef migrations add <MigrationName> --json` command would output the number of operations generated, that would be enough. A public API which returns a `ReadOnlyList<MigrationOperation>` like is passed to the `CSharpMigrationOperationGenerator` also will work. Is there some public API that I am missing? I am trying to fiddle with `Microsoft.EntityFrameworkCore.Design.OperationExecutor`, but the API seems too hard to use, and I am getting an error which says that the assembly is not found. I am trying to pass the same parameters as `dotnet ef`. 

Any idea?

**Comment by bricelam** [comment]
See [this line](https://github.com/aspnet/AspNetCore/blob/94a4293cce735b3756661ef5a475c4944f57d64d/src/Middleware/Diagnostics.EntityFrameworkCore/src/DatabaseErrorPageMiddleware.cs#L141-L143) in the database error page. It determines if there are any changes between the last migration and the current model.

**Comment by alexdrl** [comment]
Wow, your answer fits our needs perfectly. Thank you for the specific answer! 😄
