### ISSUE TITLE
Contains, Any are evaluated locally

### ISSUE THREAD

**Issue by learningsavvy** [dotnet/efcore#14620]
I've been trying to get the NOT IN/NOT EXISTS (in SQL) work with EF Core/Linq but could not succeed. The query I currently have is: 

```C#
var items = (from i in db.Items
                             join ia in db.ItemAttributes.Where(a=> !db.ItemRepositorys.Any(x=> x.JobID == a.JobID)) on i.JobID equals ia.JobID
                             where IdsList.Contains(i.JobID)
                             select ia).ToList();
```

When I used SQL Profiler to look at the query generated, EF Core generates the following query:

```SQL
SELECT [t].[ID], [t].[CreatedBy], [t].[CreatedOn], [t].[ItemID], [t].[JobID], [t].[KeyValue], [t].[UpdatedBy], [t].[UpdatedOn]
FROM [Data].[Item] AS [i]
INNER JOIN (
    SELECT [a].[ID], [a].[CreatedBy], [a].[CreatedOn], [a].[ItemID], [a].[JobID], [a].[KeyValue], [a].[UpdatedBy], [a].[UpdatedOn]
    FROM [Data].[ItemAttributes] AS [a]
    WHERE NOT EXISTS (
        SELECT 1
        FROM [Data].[ItemRepository] AS [x]
        WHERE [x].[JobID] = [a].[JobID])
) AS [t] ON [i].[JobID] = [t].[JobID]
WHERE [i].[JobID] IN (CAST(1 AS bigint))
```

.NET code throws the following error:

### Data is Null. This method or property cannot be called on Null  values. ### 

What I noticed is ItemRepositorys table does not have any data in it. I am guessing this part (**!db.ItemRepositorys.Any(x=> x.JobID == a.JobID)**) in the query is being evaluated locally. Any help is appreciated.

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.6

**Comment by smitpatel** [comment]
The posted linq query is translated to SQL fully based on code snippets above. Your guess is not true given the SQL.

Please post a full runnable solution which demonstrate the error you are seeing.

**Comment by learningsavvy** [comment]
Thanks for the quick reply. The issue was with schema difference between the model and SQL table. The model had a non nullable property where as the SQL column had NULLs in it. When I changed the property to nullable, everything was working as expected.
