### ISSUE TITLE
The instance of entity type 'StepbackRefModel' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. 

### ISSUE THREAD

**Issue by anirbandebroy** [dotnet/efcore#14634]
**The instance of entity type 'StepbackRefModel' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.**

I am getting this above issue during update but not for the first time.First time during update it is work as charm but when i am reloading(Next time onward) the page i am getting this issue.As i am using AsNoTracking() it should not be the case. As I have to update my data there is any alternate approach which can resolve the issue? Any help is highly appreciated

Version: Microsoft.EntityframeworkCore.Sqllite 2.1.4
Platform: Xamarin

```C#
public async Task<bool> AddStepBackRefItemAsync(StepbackRefModel item)
        {
            try
            {
                var allItems = await _databaseContext.DbRefData.AsNoTracking().LastOrDefaultAsync().ConfigureAwait(false);

                if (allItems == null)
                {
                    await _databaseContext.DbRefData.AddAsync(item).ConfigureAwait(false);
                    await _databaseContext.SaveChangesAsync().ConfigureAwait(false);
                }
                else
                {
                    item.Id = allItems.Id;
                    _databaseContext.DbRefData.Update(item);
                    await _databaseContext.SaveChangesAsync().ConfigureAwait(false);
                }

                return true;
            }
            catch (Exception ex)
            {
                Log.Instance.Error("Error during Add", ex.Message);
                App.Toasts.Notify(ToastNotificationType.Error, "Application Error", ex.Message, Constants.ToastTimeoutLong);
                ex = null;

            }

            return false;
        }
```

**Comment by ajcvickers** [comment]
@anirbandebroy I moved the code above into a console application--see below--but it does not reproduce what you are seeing. Can you please post a small, runnable project/solution or complete code listing (like that below) that demonstrates the behavior you are seeing.

```C#
public class DbRefData
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<DbRefData> DbRefData { get; set; }


public class Program
{
    public static async Task Main()
    {
        int id;

        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var item = context.Add(new DbRefData()).Entity;

            context.SaveChanges();

            id = item.Id;
        }

        using (var context = new BloggingContext())
        {
            var item = new DbRefData { Id = id };

            var allItems = await context.DbRefData.AsNoTracking().LastOrDefaultAsync().ConfigureAwait(false);

            if (allItems == null)
            {
                await context.DbRefData.AddAsync(item).ConfigureAwait(false);
                await context.SaveChangesAsync().ConfigureAwait(false);
            }
            else
            {
                item.Id = allItems.Id;
                context.DbRefData.Update(item);
                await context.SaveChangesAsync().ConfigureAwait(false);
            }
        }
    }
}
```

**Comment by anirbandebroy** [comment]
Yea surely.But as i told you first time the issue doesn't occurred.it will occur if i update my data next time on wards.

**Comment by ajcvickers** [comment]
@anirbandebroy I ran through multiple code paths in your code; nothing unexpected happened. Can you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by anirbandebroy** [comment]
Here is my code

 public class DatabaseContext : DbContext
    {
        public DbSet<LogItem> DbLog { get; set; }
        public DbSet<StepbackRefModel> DbRefData { get; set; }
        public DbSet<StepBackForm> DbStepBackData { get; set; }
        public DbSet<UserList> DbLoginData { get; set; }

        private readonly string _databasePath;

        public DatabaseContext(string databasePath)
        {
            _databasePath = databasePath;

            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite($"Filename ={ _databasePath}");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }

public class StepbackRefModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public IList<EmployeeContractor> EmployeeContractors { get; set; }
        public IList<ProjectContractor> ProjectContractors { get; set; }
        public IList<Hazard> Hazards { get; set; }
        public IList<Risk> Risks { get; set; }
        public IList<RiskLevel> RiskLevels { get; set; }
        public IList<Area> Areas { get; set; }
        public IList<BusinessUnit> BusinessUnits { get; set; }
        //public IList<Period> Periods { get; set; }
        public IList<Project> Projects { get; set; }
    }

    public class EmployeeContractor : DropDownBase
    {
        //public int ParentId { get; set; }
        public int Id
        {
            get => Key;
            set => Key = value;
        }
        public string Name
        {
            get => Value;
            set => Value = value;
        }
    }

    public class ProjectContractor:DropDownBase
    {
        //public int ParentId { get; set; }
        public int Id
        {
            get => Key;
            set => Key = value;
        }
        public string Name
        {
            get => Value;
            set => Value = value;
        }
    }

    public class StepBackAssessmentDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        //public int ParentId { get; set; }
        //public bool Value { get; set; }
        public string DisplayName { get; set; }
    }

    public class Hazard
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        public IList<StepBackAssessmentDetail> StepBackAssessmentDetails { get; set; }
        //public IList<object> OtherHazards { get; set; }
    }

    public class Risk
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        //public int ParentId { get; set; }
        //public object Value { get; set; }
        public string DisplayName { get; set; }
    }

    public class RiskLevel
    {
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
        public int Id { get; set; }
        //public DateTime CreatedDate { get; set; }
        //public string CreatedUserCode { get; set; }
        //public DateTime LastUpdateDate { get; set; }
        //public string LastUpdateUserCode { get; set; }
        //public string LastUpdateControlValue { get; set; }
    }

    public class Area : DropDownBase
    {
        public int ParentId { get; set; }
        public int Id
        {
            get => Key;
            set => Key = value;
        }
        public string Name
        {
            get => Value;
            set => Value = value;
        }
    }

    public class BusinessUnit : DropDownBase
    {
        public int Id
        {
            get => Key;
            set => Key = value;
        }
        public string Name
        {
            get => Value;
            set => Value = value;
        }
    }

    //public class Period
    //{
    //    public DateTime StartDate { get; set; }
    //    public DateTime EndDate { get; set; }
    //    public int Id { get; set; }
    //    public string Name { get; set; }
    //}

    public class Project : DropDownBase
    {
        public int ParentId { get; set; }
        public int Id
        {
            get => Key;
            set => Key = value;
        }
        public string Name
        {
            get => Value;
            set => Value = value;
        }
    }

   #region ReferenceData

        public async Task<bool> AddStepBackRefItemAsync(StepbackRefModel item)
        {
            try
            {
                var allItems = await _databaseContext.DbRefData.AsNoTracking().LastOrDefaultAsync().ConfigureAwait(false);

                if (allItems == null)
                {
                    await _databaseContext.DbRefData.AddAsync(item).ConfigureAwait(false);
                    await _databaseContext.SaveChangesAsync().ConfigureAwait(false);
                }
                else
                {
                    item.Id = allItems.Id;
                    _databaseContext.DbRefData.Update(item);
                    await _databaseContext.SaveChangesAsync().ConfigureAwait(false);
                }

                return true;
            }
            catch (Exception ex)
            {
                Log.Instance.Error("Error during Add", ex.Message);
                App.Toasts.Notify(ToastNotificationType.Error, "Application Error", ex.Message, Constants.ToastTimeoutLong);
                ex = null;

            }

            return false;
        }


        public async Task<StepbackRefModel> GetStepBackRefItemAsync(bool forceRefresh = false)
        {
            StepbackRefModel allItems;
            try
            {
                // Ignore forceRefresh for now.
                allItems = await _databaseContext.DbRefData.LastAsync().ConfigureAwait(false);
                return allItems;
            }
            catch (Exception ex)
            {
                Log.Instance.Error("Error during Add", ex.Message);
                App.Toasts.Notify(ToastNotificationType.Error, "Application Error", ex.Message, Constants.ToastTimeoutLong);
                ex = null;
            }
            return null;
        }


        #endregion

**Comment by ajcvickers** [comment]
@anirbandebroy This still isn't code that I can build and run without making modifications. Please post something that I can build and run.

**Comment by anirbandebroy** [comment]
@ajcvickers  sorry for the delay replied i created the sample from my working app.Please check it and let me know if you have any issue. should i include the soltion for the other issue also which i raised?
[sample.zip](https://github.com/aspnet/EntityFrameworkCore/files/2875178/sample.zip)

**Comment by anirbandebroy** [comment]
steps,

from home page - go to any other page and during return to home page issue will be observed due to updation of data.reload the homepage again will reproduce the same issue.

**Comment by ajcvickers** [comment]
@anirbandebroy The issue is that there is a single context instance that is first used to add and save entities, and then later used again while it is still tracking those entities.

The recommended pattern for EF is to use a new DbContext instance for each unit-of-work.

**Comment by anirbandebroy** [comment]
@ajcvickers Thanks for reply.But your answer is not clear.As per my knowledge the dbcontext which i am using is tied with path of sql lite.so how can i use new DbContext for each unit of work ? it will be helpfull if you provide me suitable example.

 public class DatabaseContext : DbContext
    {
        public DbSet<LogItem> DbLog { get; set; }
        public DbSet<StepbackRefModel> DbRefData { get; set; }
        public DbSet<StepBackForm> DbStepBackData { get; set; }
        public DbSet<UserList> DbLoginData { get; set; }
        public DbSet<PreferenceModel> DbPreference { get; set; }

        private readonly string _databasePath;

        public DatabaseContext(string databasePath)
        {
            _databasePath = databasePath;

            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite($"Filename ={ _databasePath}");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }

     private readonly DatabaseContext _databaseContext;

        public HSERepository()
        {
            string dbpath = DependencyService.Get<ISQLite>().GetConnection();
            _databaseContext = new DatabaseContext(dbpath);
        }

**Comment by ajcvickers** [comment]
@anirbandebroy EF is an OR/M, not just an API directly into the SQLite database. It providers common abstractions and patterns such as change tracking and unit-of-work. I'm not sure exactly what it is that you want an example for, but [the docs](https://docs.microsoft.com/en-us/ef/core/get-started/) cover inserting/updating data.

**Comment by baoduy** [comment]
I suspected the Tracking had a problem. Here is my workaround solution
```csharp
   builder.Property(u => u.Id).HasDefaultValue(0).ValueGeneratedOnAdd();
```

**Comment by ajcvickers** [comment]
@baoduy That's a very unusual configuration for a key. It's hard to see where it would be useful.

**Comment by anirbandebroy** [comment]
@baoduy  Ok I got a workaround related to it by using the using statement.Internally how the enity framework works i did find any details about that but some how the using statement for the DBContext works for me.Sadly there is not enough doc exist what to do and what not to do.

```
using (dbContext = new DatabaseContext(dbConnection))
            {
                item.UpdateDate = DateTime.Now;
                var iRefData = await dbContext.DbRefData.Include(p => p.Hazards).ThenInclude(p => ((Hazard)p).StepBackAssessmentDetails)
                                    .Include(p => p.ProjectContractors)
                                    .Include(p => p.Projects)
                                    .Include(p => p.RiskLevels)
                                    .Include(p => p.Risks)
                                    .Include(p => p.Areas)
                                    .Include(p => p.BusinessUnits)
                                    .Include(p => p.EmployeeContractors)
                                    .Include(p => p.Periods)
                                    .FirstOrDefaultAsync();

                Log.Instance.Verbose("HSERepository.AddStepBackRefItemAsync", string.Format("Old Reference Data found - {0}", iRefData == null ? "No" : "Yes"), "ID-" + iRefData?.Id.ToString());

                if (iRefData != null)
                {
                    dbContext.RemoveRange(iRefData.Areas);
                    dbContext.RemoveRange(iRefData.BusinessUnits);
                    dbContext.RemoveRange(iRefData.Periods);
                    dbContext.RemoveRange(iRefData.ProjectContractors);
                    dbContext.RemoveRange(iRefData.Projects);
                    dbContext.RemoveRange(iRefData.Risks);
                    dbContext.RemoveRange(iRefData.RiskLevels);
                    dbContext.RemoveRange(iRefData.EmployeeContractors);
                    dbContext.RemoveRange(iRefData.Hazards.SelectMany(x=>x.StepBackAssessmentDetails));
                    dbContext.RemoveRange(iRefData.Hazards);

                    dbContext.Remove(iRefData);
                    await dbContext.SaveChangesAsync();

                    Log.Instance.Verbose("HSERepository.AddStepBackRefItemAsync", "Old Reference Data Removed ", iRefData?.Id.ToString());
                }

                item.Id = 1;
                await dbContext.DbRefData.AddAsync(item);
                await dbContext.SaveChangesAsync();

                Log.Instance.Verbose("HSERepository.AddStepBackRefItemAsync", "New Reference Data Added", item?.Areas?.Count.ToString());
            }
```
