### ISSUE TITLE
AsQueryable Causes Execution

### ISSUE THREAD

**Issue by Cooksauce** [dotnet/efcore#14648]
Say you have the following data model:

```c#
class Person
{
    long Id { get; set; }
    virtual ICollection<Letter> Mail { get; set; }
}

class Letter
{
    long Id { get; set; }
    ... other properties ...
}

using (var context = new DbContext)
{
    Person person = context.Persons.Find(personId);

    *var queryable =  person.Mail.AsQueryable();

    var filteredQuery = queryable.Where(...);
}

```
The line with * causes query execution on the database to get ALL mail from person. I've read this is intentional. If so, why?

1. Doesn't this go against the goal of an ORM?

2. Can't EF recognize the intent here, and delay the execution?
 
3. Is my best option to add a virtual "Person" to the Letter class? Then do:
```c#
context.Letters.Where(o => o.Person == person);
```

### Further technical details
EF Core version: (2.2.0)
Database Provider: (npgsql)

**Comment by ajcvickers** [comment]
@Cooksauce If you are using lazy-loading proxies, then accessing the `Mail` navigation property will cause it to query the database and load all related entities.

If you din't have lazy-loading properties, then it is just calling AsQueryable on a normal `ICollection<T>` property, which doesn't involve any EF code and hence won't give you an EF query.

If you want an EF query for the navigation property, then use `var queryable context.Entry(person).Collection(e => e.Mail).Query;`
