### ISSUE TITLE
Could not load System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by chukkalasandeep** [dotnet/efcore#14647]
I am using EntityFrameworkCore in a class library targeting .NetFramework 4.6.1

I am getting the dll not found exception at the line of creating DBContext instance. Below is the image of the exception information. Strange is the assembly version in the exception message and the inner exception message is different. I tried solutions provided at (https://github.com/aspnet/EntityFrameworkCore/issues/7889) but nothing worked.

![image](https://user-images.githubusercontent.com/9654621/52459786-2eb7bb00-2ba2-11e9-984f-624c8d8526da.png)

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@chukkalasandeep Getting assembly conflicts like this is quite common when using .NET Framework and various "core" packages. Please follow up on the corefx repo where there is [an issue discussing the general problem](https://github.com/dotnet/corefx/issues/33643) and where there will hopefully be some guidance on good ways to deal with it.
