### ISSUE TITLE
Migrations: "No project was found" on linux

### ISSUE THREAD

**Issue by DjeeBay** [dotnet/efcore#14655]
Hi,

I have an issue when I'm trying tu run dotnet ef database update on my linux server.
Locally, on my Windows dev machine it works correctly, the command creates my sqlite db and that's it.

On my linux server "dotnet ef" doesn't work at all, I have to run "dotnet exec dotnet-ef.dll database update" and specify --depsfile and --runtimeconfig options, but then I have the "No project was found" message.

I tried with some options found with this post [#13339](https://github.com/aspnet/EntityFrameworkCore/issues/13339) but I still have the error.

```
Exception message: No project was found. Change the current working directory or use the --project option.
Stack trace:
Microsoft.EntityFrameworkCore.Tools.CommandException: No project was found. Change the current working directory or use the --project option.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.FindProjects(String path, String errorWhenNoProject, String errorWhenMultipleProjects)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```
Of course I tried with --project /path and --startup-project /path options but didn't help.
So I really don't know how to make it work.

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Debian 8
IDE: Visual Studio 2017 15.9.5

**Comment by ajcvickers** [comment]
@DjeeBay Can you provide some more detailed steps on how we might be able to reproduce this? For example:
* How was EF installed on the Linux box
* Where is the command being run from?
* What is the exact command being executed?
* What does the csproj file look like? Are there multiple projects?

**Comment by DjeeBay** [comment]
- EF is not installed on Linux, that's why I need to rund dotnet exec dotnet-ef.dll included when I publish.

- The command is run at the root of the publication (/var/www/myProj), where the MyProj.API.dll is.

- The exact command (tried with some variations but always the same result):
 ```
dotnet exec --depsfile MyProj.API.deps.json --runtimeconfig MyProj.API.runtimeconfig.json dotnet-ef.dll database update --assembly MyProj.API.dll --startup-assembly MyProj.API.dll --root-namespace MyProj
```

- Here is the csproj of the aps.net core app (where migrations are)
```<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>secret</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
  </ItemGroup>

  <Import Project="..\MyProj.Shared\MyProj.Shared.projitems" Label="Shared" />

</Project>
```

In fact it is a multiple projects. At the beginning it is a Xamarin Prism project and I added the API which is an asp.net core proj and I have a shared project where I have my models, DbContext class, some custom libraries and services.

**Comment by ajcvickers** [comment]
@DjeeBay One thing that is definately wrong is the reference to the "Microsoft.EntityFrameworkCore.Tools.DotNet" package. This is an obsolete package for any EF Core release newer than 2.0. It should be removed. Let us know if this doesn't help.

**Comment by DjeeBay** [comment]
@ajcvickers The problem is that if I remove this package, I don't have the dotnet-ef.dll anymore.
So I can't run my dotnet exec dotnet-ef.dll command.

This is why I installed this package. But in fact, there is probably another way to have EF on linux but I didn't find how to do.

**Comment by ajcvickers** [comment]
@DjeeBay Since 2.1, the EF tool is installed as part of the dotnet SDK. The correct way to get the tool onto the box is to install SDK.
