### ISSUE TITLE
Scaffolding to Reverse Engineer a SQL Server Database Surreptitiously Renames Columns

### ISSUE THREAD

**Issue by CubeSpark** [dotnet/efcore#14654]
Scaffolding from the NuGet Package Manager Console appears to work effectively but surreptitiously, generating classes in the Model realm for tables in the existing database but "secretly" renaming table and column structures and containers. Sarcastically though I may be, this appears to me to be equivalent to renaming C# or Java namespaces and/or class names for some darker purpose (on a reverse-engineering procedure). These dark purposes appear to be deemed "standardization". 

In this case, the command is `Scaffold-DbContext` with arguments passed as needed. 

In my situation, the database uses Schema Names, Table Names, and Column Names that provide type constraint hints. For example, the Primary Surrogate Key columns in the tables do not use the common epigraph "ID", but rather use the table name, an underscore and the acronym **_PSK** for **P**rimary **S**urrogate **K**ey.  

In SQL Server tables, the concept of ID comes from a proper trait of the column known as an IDENTITY Property, with seed value and an increment. The seed and the increment are defined at the database engine during table design. It is a well-known and well-tested technique for generating integer surrogate (meaningless) values which uniquely identify an entire row in a surrogate, proxy, meaningless way. They are used exclusively for JOIN efficiency, since relations are almost always indexed for the purpose of the fast and efficient JOIN algorithms. 

Foreign Key columns in Foreign (child) Tables that are related to the Primary Key Columns in the Primary (parent) Table are named exactly the same, except they use **_FSK**. The justification for this naming is that it removes the need to specify a table alias. 

In other words, when the columns being joined on two different tables have slightly different but conceptually similar names, a table alias to differentiate them can be dispensed.  For example, two tables named **DB.Table.Parents** and **DB.Table.Children** would have a Primary Surrogate Key column (**PSK**) in the Parent named **Parent_PSK**, and the related Foreign Key Column would be named **Parent_FSK** - that is, one Primary Key Column in the Parent and one Foreign Key Column in the Child.

To JOIN the tables, then, we can write (in valid TSQL)

```
SELECT 
MotherName, ChildName
FROM 
DB.Tables.Parents INNER JOIN DB.Tables.Children
ON Parent_PSK = Parent_FSK;
```
When the `Scaffold-DbContext` operation finished, the column names had their underscores stripped surreptitiously, and the capitalization was changed on the suffix from PSK to Psk, or FSK to Fsk.  I find this type of renaming to be insidious, and I do not see any ANSI / ISO standards that govern this.

The original fully qualified column names in the database are:

1. DB.Table.Parents.**Parent_PSK**
2. DB.Table.Children.**Parent_FSK**

Entity Framework `Scaffold-DbContext`  broke that convention and renamed the columns as follows, removing the Schema Name in the process. If the default schema in the database engine is no longer DBO, a lot of refactoring would need doing, or some attributes set, or various other tweaks to make the EF Model match the existing model. 

```
Parents.Parent_PSK
Children.Parent_FSK
```
I would suggest changing EF Core 2.2.0 rather than changing the inherited interfaces of the database object signatures, such as column names, schema names, default constraint functionality, or key constraint properties such as the IDENTITY property. 

Also, a full scale acceptance of the epigram **ID**, which is commonly used as a false conceptual name for a column flagged as an IDENTIFIER should be restrained, because the concept of ID is not associated with the IDENTITY property, but is only a matter of slick naming convenience, which is a property that assigns a seed and an increment to an integer column.  How many OOPs developers know that ID is actually an ever-increasing, seeded, incremental value controlled by the IDENTITY property on the column definition in TSQL?

EF Core version: 2.2.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 Professional on a Domain
Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment]
@CubeSpark A couple of comments:
* Reverse engineering/scaffolding a database does not modify that database in any way
* Identifiers are, by default, modified to be more idiomatic to C#. This can be disabled with the [use-database-names](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold) option.
* Whatever column you have setup to be an Identity column will be scaffolded as a property that acts this way in the model. The convention of using "Id" for the primary key and making it an Identity column doesn't apply if something else is configured as the key.

If you're seeing behaviors different from these, then please post a small, runnable project/solution or complete code listing that demonstrates what you are seeing.

**Comment by CubeSpark** [comment]
Thanks,

That’s a good answer - use database names …

I am new at this, and I have a lot to learn.

Again, thanks for the response.

Sincerely,
Robert (Bob) Letts
