### ISSUE TITLE
EF7 Class Inheritance 

### ISSUE THREAD

**Issue by WillBaldwin** [dotnet/efcore#1466]
using EntityFramework 7.0.0.-beta1

I have class inheritance setup with the intent to implement Table per Hierarchy (TPH) database schema on SQL Server.  As I understand it EF7 should default to TPH but in my test application it is defaulting to (TPC).  Is there a HINT I can give EF7 to indicate TPH is my intent?

public class Book
{
     public int BookId;
     public string Name;
} 
public class Paperback : Book{}
public class Notebook : Book{}
public class Hardcover: Book{}

**Comment by WillBaldwin** [comment]
I found where TPH support is a still a TODO item in the repo...

**Comment by rowanmiller** [comment]
Here is the work item tracking inheritance support: https://github.com/aspnet/EntityFramework/issues/247
