### ISSUE TITLE
EF7 Fluent API: Self Referencing Tables

### ISSUE THREAD

**Issue by WillBaldwin** [dotnet/efcore#1467]
It appears as if EF7 uses all new Fluent API.  Does anyone know where I might find more info?  I'd like to implement self referencing tables with EF7.

public class Employee  
{
     public int EmployeeId  //minus the gets and sets
     public Employee Manager  //maps to the manager's Employee
     public int ManagerId  //maps to the manager's Employee.EmployeeId
     public string Name
     public <List > Employees
}

//EF7 Fluent API does not seem to support the following..  perhaps there is a translation?
HasOptional(x => x.Manager)          //new Fluent API property maybe??
.WithMany(x => x.Employees)          //new Fluent API .OneToMany
.HasForeignKey(x => x.ManagerId)  //new Fluent API ForeighKey
.WillCascadeOnDelete(false);           //new Fluent API property maybe??

**Comment by AndriySvyryd** [comment]
The EF 7 equivalent is
.Entity<Employee>()
.HasOne(x => x.Manager)
.WithMany(x => x.Employees)
.ForeignKey(x => x.ManagerId)
.Required(false);

Cascade on delete is not supported yet

**Comment by WillBaldwin** [comment]
The following are not resolving for me, I assume they are introduced in later builds of EF7 after "7.0.0-beta1", is that correct?
 
.HasOne(x => x.Manager)
 .WithMany(x => x.Employees)

**Comment by rowanmiller** [comment]
Correct, they are currently in nightly builds. Here is some info on using the latest builds https://github.com/aspnet/EntityFramework/wiki/Getting-Started-with-Nightly-Builds.

**Comment by heathyates** [comment]
@rowanmiller 

I was testing the nightly builds with the link you gave. I applied it to the ASP.NET template application (the one we are given out of the box). I received the following error below:

![error](https://cloud.githubusercontent.com/assets/1896424/5951702/2c1f998a-a730-11e4-914b-f164349685e2.PNG)


Steps to reproduce: 
1. Create ASP.NET 5 Web application 
2. Follow directions found here: https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Traditional-.NET-Applications 
3. Install-Package EntityFramework.SqlServer –Pre

I realize this is the nightly build and it is really living on the edge trying to test it out, but I thought you would like to be aware.

**Comment by weitzhandler** [comment]
@rowanmiller @AndriySvyryd 
Alright, no problems with storing the data, but is there a way to retrieve a hierarchy of depth `n`?
#3241
