### ISSUE TITLE
Self-referencing one-to-one

### ISSUE THREAD

**Issue by space-alien** [dotnet/efcore#14677]
My entity has two self-referencing one-to-one relationships as follows:
```C#
public class Entry
{
    public int Id { get; set; }
    public Entry ReversedByEntry { get; private set; }
    public Entry ReversesEntry { get; private set; }
}
```
E.g.
```
  Entry 42             Entry 42
↓ reverses ↓       ↑ reversed by ↑
  Entry 17             Entry 17
↓ reverses ↓       ↑ reversed by ↑
  Entry 1              Entry 1
```
This configuration:
```C#
public class EntryConfiguration : IEntityTypeConfiguration<Entry>
{
    public void Configure(EntityTypeBuilder<Entry> builder)
    {
        builder.Property(x => x.Id);

        builder.HasKey(x => x.Id);

        builder.HasOne(x => x.ReversedByEntry)
            .WithOne(x => x.ReversesEntry)
            .HasForeignKey<Entry>("ReversedByEntryId")
            .HasPrincipalKey<Entry>(x => x.Id)
            .IsRequired(false);

        builder.HasOne(x => x.ReversesEntry)
            .WithOne(x => x.ReversedByEntry)
            .HasForeignKey<Entry>("ReversesEntryId")  // Different name
            .HasPrincipalKey<Entry>(x => x.Id)
            .IsRequired(false);
    }
}
```

Produces this table:
```C#
migrationBuilder.CreateTable(
    name: "Entries",
    columns: table => new
    {
        Id = table.Column<int>(nullable: false)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
        ReversesEntryId = table.Column<int>(nullable: true),
        ReversedByEntryId = table.Column<int>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Entries", x => x.Id);
        table.ForeignKey(
            name: "FK_Entries_Entries_ReversesEntryId",
            column: x => x.ReversesEntryId,
            principalTable: "Entries",
            principalColumn: "Id",
            onDelete: ReferentialAction.Restrict);
    });
```

The migration is producing two columns, but only one FK constraint, whereas I was expecting both.

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by smitpatel** [comment]
When you define a relationship using `HasOne().WithOne` and use the same pair of navigations in it then from EF Core, perspective you are configuring one relationship only. So in your EntityConfiguration, when you call `HasOne` chain again with different FK name, it is going to configure the same relationship and will change FK property name. Hence you are seeing only one FK constraint in your table. Perhaps, your both navigations are not part of same foreign key constraint.

**Comment by space-alien** [comment]
Thank you for the explanation.

However, these are actually two different relationships:
```
             Reverses       ReversedBy
Entry 42     17             null
Entry 17     1              42
Entry 1      null           17
```

Hence two calls to HasOne, one for each column, and two different shadow foreign key properties.

I can generate both FK constraints by omitting the WithOne() arguments:
```C#
builder.HasOne(x => x.ReversedByEntry)
    .WithOne()
    .HasForeignKey<Entry>("ReversedByEntryId")
    .HasPrincipalKey<Entry>(x => x.Id)
    .IsRequired(false);

builder.HasOne(x => x.ReversesEntry)
    .WithOne()
    .HasForeignKey<Entry>("ReversesEntryId")
    .HasPrincipalKey<Entry>(x => x.Id)
    .IsRequired(false);
```

The problem now is that EF won't automatically fix up the relationships. For example, if I set `entry17.Reverses = entry1` (both entries tracked), `entry1.ReversedBy == null`.

Is this scenario achievable?

**Comment by ajcvickers** [comment]
@space-alien The conceptual connection between the two FKs is something that EF does not know about. In other words, there is no way to tell EF that when this FK value changes, then this other FK value should also change in some way. This sounds like something that should be encapsulated in your business logic, rather than in the OR/M.

**Comment by space-alien** [comment]
Thanks Arthur for your reply,

Still, my instincts tell me that the code in my first message *should* produce two separate relationships. EF has all the information it needs:

 * Two calls to HasOne starting from different properties
 * Each call specifies a different FK property.

I understand from Smit's reply that because the relationships (necessarily) rely on the same pair of navigations (being on the same entity), EF interprets the two calls as the same relationship and consequently the second call effectively "overwrites" the first, but perhaps that is not ideal?

If the relationships were between different entities, the exact same code would produce two relationships. And in my second message, omitting the parameter for WithOne() also produces two relationships.

**Comment by space-alien** [comment]
Thank you for your reply Arthur.

I realise that I have been reasoning about this incorrectly. There is only one relationship, and the single FK constraint is correct.

`b.Reverses = a;` correctly gives `b.ReversedBy == null;   a.ReversedBy == b;   a.Reverses == null`

My original configuration should have been simplified to:

```C#
public class EntryConfiguration : IEntityTypeConfiguration<Entry>
{
    public void Configure(EntityTypeBuilder<Entry> builder)
    {
        builder.Property(x => x.Id);

        builder.HasKey(x => x.Id);

        builder.HasOne(x => x.ReversedByEntry)
            .WithOne(x => x.ReversesEntry)
            .HasForeignKey<Entry>("ReversedByEntryId")
            .HasPrincipalKey<Entry>(x => x.Id)
            .IsRequired(false);
    }
}
```
