### ISSUE TITLE
Migration Information

### ISSUE THREAD

**Issue by WillBaldwin** [dotnet/efcore#1468]
In EF7 there appears to be a hidden location for migration information; perhaps another duplicate hidden snapshot?  I was able to delete all my migration files, the database schema and "k ef migration list" still was listing migrations that I had deleted.  I deleted the migrations folder and that seemed to clean it up but I would love to know where this hidden location is so I can mess with things I am not suppose to; granted I have been editing the migration files by hand to accomplish migration rollbacks.  If only I could figure out how to get EF to roll back migrations for me.

**Comment by bricelam** [comment]
Generating migrations adds (or updates) three files to your project:
* **Migrations/MyMigration.cs** -- You can mess with this file. It contains our best-guess at what operations to perform.
* **Migrations/MyMigration.Designer.cs** -- This is the migration's metadata used by the framework
* **Migrations/MyContextModelSnapshot.cs** -- You can merge conflicts in this file. It contains the last-know model we use to generate new migrations.

I suspect `k ef migration list` also lists migrations that have been applied to the database. These are stored in the `__MigrationHistory` table and will probably show up even if the migrations files for them have been deleted.

**Comment by WillBaldwin** [comment]
Thank you for the great explanation!
