### ISSUE TITLE
Model inheritance: EF returns data from both base and derived one

### ISSUE THREAD

**Issue by piotrek-k** [dotnet/efcore#14681]
### Steps to reproduce

I have two models:

```c#
public class Post {
//some parameters
}
```

```c#
public class PostArchive : Post {
    public DateTimeOffset DateOfArchivizationUTC { get; set; }
}
```

And in DbContext class:
```c#
public DbSet<UserAction> UserActions { get; set; }
public DbSet<PostArchive> PostsArchive { get; set; }
```

Entity Framework generated for me one database table containing the sum of columns from both models plus "Discriminator" column.

Then, I get data from database:

```c#
Posts = await _context.Posts.ToListAsync();
```

### Problem description

I can see, I'm receiving data from both Posts and PostsArchive. Is this OK? I mean, shouldn't it return data from Posts only (and omit PostsArchive)? Is it a bug, or intended behaviour?

I made two different classes/models for a reason. I wanted to clearly separate Posts from PostsArchive. One is based on another but they were meant to be different type of data. If I want to get Posts, I want to get Posts without PostsArchive and vice versa.

### Further technical details
EF Core version: 2.1.1
Database Provider:Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment]
@piotrek-k This is intended behavior. EF is mapping the hierarchy using the "TPH" mapping pattern such that the semantics of the hierarchy is preserved. You can do this:
```C#
modelBuilder.Entity<PostArchive>().HasBaseType((Type)null);
```
but then the semantics of the inheritance is lost, so you might consider in that case whether inheitance is the right form of relationship (in the OO sense) between these two types.
