### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Sebacad** [dotnet/efcore#14689]
Hi, 

I have a project with a query executed regularly (each 10 minutes). And i have increasing memory used.
I tried to create a scope to dispose my context for each request. Instances are disposed to every GC.Collect called, but EF never frees the used memory.

`using (var scope = _serviceProvider.CreateScope())
            {
                var messageQueuing = scope.ServiceProvider.GetRequiredService<IMessageQueuing>();
                messageQueuing.PlanifyQueudMessages();
            }`

![image](https://user-images.githubusercontent.com/42929332/52711687-bcc0e680-2f92-11e9-8024-b7bef9196fa7.png)

![image](https://user-images.githubusercontent.com/42929332/52712070-d44c9f00-2f93-11e9-824f-9efcff0b552a.png)

EF Core keeps objects even after a SaveChange. Except I do not need memory cache in my treatment. Have an idea to optimize memory management?

Microsoft.EntityFrameworkCore.Sqlite Version 2.1.1

**Comment by ajcvickers** [comment]
@Sebacad EF is designed to cache and reuse metadata and queries, among other things, so some continued memory usage is expected. If it continued to grow without bound, then that would indicate a bug, but that's not what I'm seeing here.

Most of this caching is rooted on the `IServiceProvider` that EF uses internally. You can instead manage this yourself by creating a service provider and giving it to EF. Something like:
```C#
var serviceProvider = new ServiceCollection().AddEntityFrameworkSqlite().BuildServiceProvider();
```
Then pass this service provider to `UseInternalServiceProvider` in either `AddDbContext` or `OnConfiguring`.

If you want no caching, then create a new `serviceProvider` for each context instance. However, perf will likely be very bad.

**Comment by adamskrodzki** [comment]
I'm experiencing similar issues 
Is there a way to cleare all caches of EF ? 
I have an app which do some db operations in a loop (think cron like worker process) and I also see continuus potentially unbounded growth in memory (I have 256 MB docker containers and they throw Oout Of Memory after ~1 hour) is there any way in which i can free all EF dependent data (cache) I'm already disposing all contexts periodically but that is not helping

**Comment by ajcvickers** [comment]
@adamskrodzki If you build the EF internal service provider yourself, and then pass it to EF with `UseInternalServiceProvider`, then all EF caching will be rooted in that service provider. Throwing it away and creating a new one should allow it all to be garbage collected.

**Comment by adamskrodzki** [comment]
I do not understand how it can help me ? I review the IServiceProvider interface and see only getService method, how that gives me any control over clearing EF cache ? Can you guide me to any example?
