### ISSUE TITLE
Migrations Fail without Connection String

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#1470]
Given the fact that the model snapshot is in the project, not in the database, I asked Brice about add-migration failing when I hadn't yet made a connection string available. He said it may be a bug and asked that I add it here as an issue.

**Comment by bricelam** [comment]
Migrations *shouldn't* ever (but I haven't checked yet) connect to the database in this case, so it's technically not needed. We do however instantiate the DbContext. I'm not sure if doing that requires it to be present. If so, we should consider relaxing that requirement and only throw when trying to connect to the database.

**Comment by vossad01** [comment]
Is there some other minimal level of configuration required for the migrations to be created?
I find a DbContext that can be instantiated but knows nothing about connecting to a database still exhibits issues trying to create migrations. 

A simple setup like,

```C#
public class BlogDbContext : DbContext
{
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Blog>();
	}
}

public class Blog
{
	public int BlogId { get; set; }
	public string Url { get; set; }
}
```
fails with the following when `Add-Migration` is called:

> Unable to resolve service for type 'Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder' while attempting to activate 'Microsoft.Data.Entity.Relational.Migrations.Infrastructure.MigrationAssembly'.

However, `new BlogDbContext()` does not throw any exceptions so instantiating the DbContext would not seem to the be problem.

As soon as `OnConfiguring` is overridden to specify UseSqlServer with a connection string, migrations create without issue:

```c#
protected override void OnConfiguring(DbContextOptions options)
{
	options.UseSqlServer(@"Server=(localdb)\v11.0;Database=BlogDbContext;Trusted_Connection=True;");
	base.OnConfiguring(options);
}
```

**Comment by julielerman** [comment]
Instantiating a DbContext does not trigger database activity so at that point it won't be looking to resolve the service. If you had code to execute a query, savechanges or otherwise hit the db, then you would get a problem like you did when migrating. In fact, I've seen ef7 need to have the provider specified on something like DbContext.add. So I'm not sure where in the pipeline the provider comes in with ef7 exactly. But not from instantiating the context.

Hth

**Comment by bricelam** [comment]
@vossad01 you do need to be using a data store that supports Migrations. The data stores (aka providers) are responsible for adding the correct services. We should however, make that error message a little clearer. Can you file a new issue?

**Comment by vossad01** [comment]
@bricelam Thanks!  #1652 created.

**Comment by rowanmiller** [comment]
@bricelam @julielerman it doesn't seem like there is anything to do here. You do need to have a `UseSqlServer` to let EF know which provider you are using... but we don't actually use the connection string, so it doesn't matter if it's just a dummy one that you never actually connect to.

OK if I close this out?

**Comment by bricelam** [comment]
Yeah, it's lame you have to specify *something* even though we don't use it. But specifying a dummy one is an acceptable workaround.

**Comment by sturlath** [comment]
For some reason we are getting this and need to add a "dummy" connection string to get it to work.
`  "DefaultConnection": "Data Source;Initial;Integrated Security=True;",`

So the following 
` dotnet ef migrations add Test`

throws

`Value cannot be null. (Parameter 'connectionString') `



This is my project settings using 2022 (doesn´t work either in 2019)

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>some guid</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="5.0.3" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Core" Version="3.1.3" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.1.4" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProcessingJobAPI\ProcessingJobAPI.csproj" />
  </ItemGroup>
</Project>
```

Any ideas what might be causing this?

**Comment by ajcvickers** [comment]
@sturlath Please open a _new_ issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
