### ISSUE TITLE
[question] exclude a relationship from an IQueryable that have include

### ISSUE THREAD

**Issue by mhamri** [dotnet/efcore#14710]
let say i have a function that is returning the IQueryable and inside that function i'm including some relationship. now because of so many similar functionality i want to use the same function but i don't need one or some of the include. is there anyway to remove include from IQueryable before executing it?

function IQueryable<TableName> FuncName(){
    return _db.TableName.Include(x=>MustHaveChild).Include(x=>x.ChildTable);
}

.... later i use the function but remove the

var tableValue= FuncName().Exclude(x=>x.ChildTable).ToList()

I know i can go and mess around with the execution tree, but i was wondering if there is a ready project or built in function to do that

**Comment by smitpatel** [comment]
The general way to solve this is to have conditional includes. `FuncName` can take parameters which includes it should apply and you only apply Includes needed for particular query. If you want to remove Include because results are not bringing in parent entity anymore then it would be ignored automatically.

**Comment by mhamri** [comment]
you mean if i do a projection i can ignore the include right?

**Comment by ajcvickers** [comment]
@mhamri This is not something we plan to implement. You'll need to use conditional code to build the queries you want with or without `Include`. It might help to always add the Includes near the end of the query.

**Comment by ajcvickers** [comment]
@mhamri Also, once implemented, issue #2953 (rule-based eager loading) might help.
