### ISSUE TITLE
Is it possible to cache all entity values in memory？and shared by all DbContext in process.

### ISSUE THREAD

**Issue by mokeyish** [dotnet/efcore#14729]
There is a lot of queries in my app, It caused low performance. 

Because the amount of data is very small.  Is it possible to cache all entity values in memory?and shared by all DbContext in process.

**Comment by Tarig0** [comment]
How many dbcontexts do you have active at a time? Usually you should have one per Web request.

**Comment by mokeyish** [comment]
There is only one `DbContext` per Web Request. Because of complex entity relationships need to query many times, It caused low performance.

**Comment by Tarig0** [comment]
Think you will need to put up a code example to really grasp what may be the issue. Think having a shared data between each dbcontext would exasperate the issue.

**Comment by mokeyish** [comment]
Since the code amount is very large, I can't put the code here,.   A graph data stored in database, I don't know how many nodes there are. I think it is no need to query database again and again(Many web request), cached all data in memory, the 1st request will be slower, but the 2nd and next request will be faster.

**Comment by Tarig0** [comment]
If you can host it in a repo you can share the code that way

**Comment by mokeyish** [comment]
Sharing code seems to be cumbersome，It belongs to a large project. I still want to known how to cache all entity values in memory, and shared by all DbContext in process.

**Comment by Tarig0** [comment]
To answer your specific question I would not rely on EF core to do the caching but instead have an extra layer that would do the caching and then when a cache miss occurs use EF to fill the cache and return the object.

**Comment by ajcvickers** [comment]
@mokeyish The recommended approach is to use a single context instance per unit-of-work. Entities are cached within the unit of work, but each unit of work queries again from the database. A second-level cache is not something we are currently planning on implementing--see #5858. Issue #12206 (reference data) might also be relevant, which we do plan to implement, but is currently on the backlog.

**Comment by mokeyish** [comment]
@ajcvickers I'm trying to rewrite `StateManger`, make it shared in all `DbContext`, then use read and write separation, and track the changes of transaction  `commit` and `rollback` for updating data
