### ISSUE TITLE
 SQLite Error 5: 'database is locked' only on Linux

### ISSUE THREAD

**Issue by xavierlaffargue** [dotnet/efcore#14732]
I have a question, I have a small program that retrieves a CSV file and transforms it into a Sqlite database. On Windows no problem it works very well. On Linux, however, I get an error message:

```

string connectionString = "Data Source=" + PathFile + targetFile;
            using (SqliteConnection m_dbConnection = new SqliteConnection(connectionString))
            {
                m_dbConnection.Open();
                // Requêtes de création des tables
                string sql = String.Empty;
                sql = String.Concat(sql, "CREATE TABLE TARGETS (idTarget NUMERIC, customerId NUMERIC, numberCard TEXT, mail TEXT, mobile TEXT, bat NUMERIC);");
                sql = String.Concat(sql, "CREATE TABLE COLUMNS (idColumn  NUMERIC, name TEXT, isVariable NUMERIC);");
                sql = String.Concat(sql, "CREATE TABLE ROW (idTarget  NUMERIC, idColumn TEXT, value TEXT);");
                // Execution des requêtes de création
                Console.WriteLine("Commande : " + sql);
                using (SqliteCommand command = new SqliteCommand(sql, m_dbConnection))
                {
                    countRow += command.ExecuteNonQuery(); // <===== /!\ Exception here
                }
           }

```
`
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Mailing.Service.ServiceFile.ConvertCSVToSQLite(String sourceFile, String targetFile)
   at Mailing.Service.ServiceFile.UploadFile(Byte[] byteFile, String filename, TypeCanal canal, Int32 idMailing, Boolean async)
   at MailingAutomator.Program.Main(String[] args) in Program.cs:line 64`

Is there something different between Linux and Windows for Microsoft.Data.Sqlite?
A connection with the fact that on Linux I read and write on a mounted NAS ? A problem of access ? The sqlite database is created but empty.

### Further technical details
EF Core version: 2.2.2
Database Provider: Microsoft.Data.Sqlite
Operating system: Linux Ubuntu 16.04 & Windows 10

**Comment by xav-stargate** [comment]
Some news :
When I use a samba share on a other ubuntu server it's works
But on other Windows share I get again this error... a journal file appears and disappears several times.
I don't understand, the sqlite file is created but empty
