### ISSUE TITLE
Detecting script vs execution in MigrationsSqlGenerator

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#14746]
Is there an easy way to detect whether the `XxxMigrationsSqlGenerator` is generating statements for execution or for script to be created? Because for script I have to generate slightly different output for user to be able to execute it without minor tweaks (basically [SET TERM](https://www.firebirdsql.org/pdfmanual/html/isql-terminator.html)).

If not, it's fine. In EF6 this wasn't done either and nobody complained. As one would expect people run the migrations directly.

**Comment by ajcvickers** [comment]
@cincuranet We recommend not creating different output when generating a script as opposed to applying the migrations directly. Can you give some more details on why this is needed?

**Comment by cincuranet** [comment]
Yes I can. When the migrations are generated and directly executed, it is known what's the command. But when I generate the script, then the semicolons are, by default, delimiting commands. But semicolons inside i.e. stored procedure will break the parsing and the script is not going to be valid (and Firebird, at the moment, does not support sending multiple commands inside one "packet"). That's why Firebird has SET TERM "statement" (it's really not a statement, because server does not handle it, it's purely for client side tools to handle parsing. 

That why the stored procedure in script would look like this for Firebird.

```sql
-- changing the separator to ^
set term ^;

-- the end of the procedure is signaled by ^ so the ; can be used inside
create procedure ...
begin
  foo;
  bar;
  baz;
end^

-- changing the separator back to ;
set term ;^
```

Yes, I know there are ways to handle it without explicit separators (like counting "begin-end" etc. levels), but none of this is supported by any - default or commercial - tool known to me supporting Firebird.

If this would be easy to do, I would like to do it. Else, meh, let's see whether somebody asks for it...

**Comment by ajcvickers** [comment]
@bricelam to follow up.

**Comment by bricelam** [comment]
SQL Server has the [GO utility statements](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-2017) for tools to mark the end of a batch/DbCommand. Does Firebird have a similar concept for tools? This is enabled by the [ISqlGenerationHelper.BatchTerminator](https://github.com/aspnet/EntityFrameworkCore/blob/1f019d938f87700c953a15c2b740eefd139e710f/src/EFCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs#L39) property.

If not, we can look into adding a flag to indicate that [Migrator.GenerateScript](https://github.com/aspnet/EntityFrameworkCore/blob/1f019d938f87700c953a15c2b740eefd139e710f/src/EFCore.Relational/Migrations/Internal/Migrator.cs#L261) was called.

**Comment by cincuranet** [comment]
Yeah, the GO is similar concept. But for Firebird it's not hardcoded. At the beginning the `SET TERM xxx` has to be called. And only for scripts and procedural blocks.

So I fail to see how the `BatchTerminator` could be used, but I might be missing something.

**Comment by bricelam** [comment]
I agree, it wouldn't work for `SET TERM`.

**Comment by cincuranet** [comment]
So the state is that ATM I can't detect that the script is being generated, right? 

I'll leave it as it's now and once the flag is present - I suppose somewhere in 3.x timeframe - I'll update the code.

**Comment by bricelam** [comment]
Correct; there's currently no way to detect it.

**Comment by roji** [comment]
Note: this has become more critical for Npgsql - am going to need this for automatic sequence reset after seeding to avoid collision (https://github.com/npgsql/efcore.pg/issues/367).

**Comment by bricelam** [comment]
@roji I can't figure out what Npgsql actually needs to do differently in the script vs at runtime. Can you elaborate?

**Comment by bricelam** [comment]
Oh I see--https://github.com/npgsql/efcore.pg/issues/1157. So yours is idempotent too.

**Comment by bricelam** [comment]
@cincuranet You need to do it for *all* scripts, right? (not just idempotent)

**Comment by cincuranet** [comment]
Correct.
