### ISSUE TITLE
Primary Key Data Annotations are randomly being ommited (Database first)

### ISSUE THREAD

**Issue by yomer** [dotnet/efcore#14755]
I'm using EF Core Power Tools to do a Reverse Engineer for my database model. When the tool used EFCore 2.1.4, everything was working as expected when generating my model in code from my DB. But the tool got updated to EFCore 2.2 and now when reverse engineering, my classes are being randomly generated without the Primary Key Data Annotation

Checking the issue with @ErikEJ who authored EF Core Power Tools, he was able to reproduce the issue and said that the issue is with EFCore's reverse engineering.

[https://github.com/ErikEJ/EFCorePowerTools/issues/180](url)

I would appreciate your help.

### Steps to reproduce
1. Create a project and have the EFCore Power Tools 2.2.12 VSIX installed
2. Create a DB in SQL with the following two tables
```
CREATE TABLE [dbo].[Arr_Cat_MontoGasolina](
	[IdCat_MontoGasolina] [int] IDENTITY(1,1) NOT NULL,
	[MontoGasolina] [int] NOT NULL,
	[Borrado] [bit] NOT NULL,
 CONSTRAINT [PK_Arr_Cat_MontoGasolina] PRIMARY KEY CLUSTERED 
(
	[IdCat_MontoGasolina] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Arr_Cat_MontoGasolina] ADD  DEFAULT ((0)) FOR [Borrado]
GO

CREATE TABLE [dbo].[Arr_Cat_Paso](
	[IdCat_Paso] [int] IDENTITY(1,1) NOT NULL,
	[Paso] [nvarchar](30) NOT NULL,
	[Borrado] [bit] NOT NULL,
 CONSTRAINT [PK_Arr_Cat_Pasos] PRIMARY KEY CLUSTERED 
(
	[IdCat_Paso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Arr_Cat_Paso] ADD  DEFAULT ((0)) FOR [Borrado]
GO
```

3.  Right click the project in the Solution Explorer in Visual Studio, and select **Reverse Engineer->Select Connection->Select Tables ->**

4. Choose the following options on the last screen and run the tool
![capture20190213144202310](https://user-images.githubusercontent.com/1246242/53106219-33606580-34f8-11e9-84a8-d217f24ef220.png)

### Further technical details
EF Core version: 2.2 (Used by EF Core Power Tools 2.2.12), 2.1.4 Used by my project
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10
IDE: Visual Studio 2017 15.8.7

**Comment by smitpatel** [comment]
Answered here https://github.com/ErikEJ/EFCorePowerTools/issues/180#issuecomment-465699609

This is non-issue.

**Comment by yomer** [comment]
Thanks for your support. I understand what happened and made the necessary changes in my database.
