### ISSUE TITLE
Clone entityframework into VS2015 and cannot resolve dependencies

### ISSUE THREAD

**Issue by heathyates** [dotnet/efcore#1475]
![error](https://cloud.githubusercontent.com/assets/1896424/5907543/624d3b6a-a565-11e4-80b0-ae75ea2fd251.PNG)
Please see the image above. I cloned the entire repo and I am unable to resolve dependencies such as Xunit. I was taking a peak at your tests (it's the quickest way to learn a project). Could you please tell us what we could be missing? I'm not understanding why. 

![cannotfindxunit](https://cloud.githubusercontent.com/assets/1896424/5907611/e28694ac-a565-11e4-9267-bd893ebeee5f.PNG)

So I tried to restore the package in nugget and received the error above. 

![error xunit](https://cloud.githubusercontent.com/assets/1896424/5908193/eab51342-a56a-11e4-916e-41f716a639a4.PNG)

My colleague Will Baldwin went an extra step and we both found that we are unable to install the package via package console manager for xunit. See above. Is anyone aware of a workaround?

**Comment by bradwilson** [comment]
I've noticed that recent builds of NuGet require that you add the nuget.org package source if you're using a `NuGet.config` file to permit the use of custom package sources. I'm not sure when this change went in, but I've already updated all the `NuGet.config` files in xUnit.net for this exact reason: https://github.com/xunit/xunit/blob/master/nuget.config#L4

If EF is using a custom `NuGet.config` file, they may also need to make this update.

**Comment by heathyates** [comment]
This solved the issue. Thank you Brad.
