### ISSUE TITLE
EF Core execute SQL on connection

### ISSUE THREAD

**Issue by phatcher** [dotnet/efcore#14769]
I'm using SQL Server's SESSION_CONTEXT capability to enforce per-user security even though the we have pooled connections

With EF 6 this is possible by writing an interceptor which executes each time a connection is opened, see [this article](https://blogs.msdn.microsoft.com/mvpawardprogram/2016/02/09/row-level-security-in-entityframework-6-ef6/l) for example.

Given the lack of lifecycle hooks, is there anyway currently to accomplish the same thing with EF Core?

**Comment by ajcvickers** [comment]
@phatcher The link doesn't work for me, but if you need to do something each time the connection is opened, then consider using the events on `DbConnection`. If you need access to the `DbCommand` each time EF uses it to execute a command, then try using a `DiagnosticListener`--something like this:

```C#
public class DbInterceptor : IObserver<KeyValuePair<string, object>>
{
    public void OnCompleted()
    {
    }

    public void OnError(Exception error)
    {
    }

    public void OnNext(KeyValuePair<string, object> value)
    {
        if (value.Key == RelationalEventId.CommandExecuting.Name)
        {
            var command = ((CommandEventData)value.Value).Command;

            // Do DbCommand manipulation here
        }
    }
}

public class EfGlobalListener : IObserver<DiagnosticListener>
{
    private readonly DbInterceptor _dbInterceptor = new DbInterceptor();

    public void OnCompleted()
    {
    }

    public void OnError(Exception error)
    {
    }

    public void OnNext(DiagnosticListener listener)
    {
        if (listener.Name == DbLoggerCategory.Name)
        {
            listener.Subscribe(_dbInterceptor);
        }
    }
}
```
Registered like this:
```C#
DiagnosticListener.AllListeners.Subscribe(new EfGlobalListener());
```

**Comment by phatcher** [comment]
@ajcvickers I can see the DbConnection.StateChange event handler, but how would I wire that up within a particular DbContext - do I override OnConfiguring.

Doesn't there need to a hook on something like DatabaseFacade so that it can wireup the handler before when EF create the connection instance?

**Comment by ajcvickers** [comment]
@phatcher Should be able to do it in the constructor. For example:
```C#
    public BloggingContext(DbContextOptions<BloggingContext> options)
        : base(options)
    {
        var connection = Database.GetDbConnection();

        connection.StateChange += (_, a) => Console.WriteLine($"Connection {a.CurrentState}");
    }
```

**Comment by c-luu** [comment]
@ajcvickers For Opened/ Opening state interception, is there a best practice between event handling as done here and overriding `DbConnectionIntercepter`?

**Comment by ajcvickers** [comment]
@c-luu Not really; use whichever works best for you.
