### ISSUE TITLE
How to detect .ValueGeneratedNever?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#14761]
The goal is to be able to detect when the fluent API setting "ValueGeneratedNever" is used on a PrimaryKey field. Typically I Scaffold to save time, so the real world properties would be like:

```
     modelBuilder.Entity<MyModel>(entity =>
            {
                entity.HasKey(e => e.MyProp) .ForSqlServerIsClustered(false);
                entity.Property(e => e.MyProp).ValueGeneratedNever();
});

  public partial class MyModel 
{
        [Key]
        public Guid MyProp { get; set; }
}
```

The end usage will be to dynamically detect if an insert will be allowed with the primary key already set on a given entity.

Ideally I'd be able to pull this from something like:
```
IEntityType ietType = ...Model.GetEntityTypes()....;
IKey ikKey =  ietType.FindPrimaryKey();
ikKey.somemetafieldthatletsmecheckforValueGeneratedNever.
```

I've been trying to search documentation, and played around in debug, but I haven't come across a way to do this yet.

I'm hoping there is some obvious meta-data look-up that I've missed.

Thanks for the help!

**Comment by smitpatel** [comment]
`Key` are not generated, properties are. So you need to check for properties inside the given key. `IProperty.ValueGenerated` enum can tell you what is value generation set for each property.

**Comment by OpenSpacesAndPlaces** [comment]
@smitpatel That worked perfectly - thank-you!!!!!!!!!!!!!!!!!!!!!!!!

In-case anyone else comes across this - was as simple as:
```
IEntityType ietType = ...Model.GetEntityTypes()....;
IKey ikKey =  ietType.FindPrimaryKey();
bool bPartOfKeyNotGenerated = ikKey.Properties.Any(p=>p.ValueGenerated == ValueGenerated.Never)
```

This can be closed.
