### ISSUE TITLE
unit test cases to test methods containing EntryFrameworkCore Attach method 

### ISSUE THREAD

**Issue by NidhiNagarro** [dotnet/efcore#14795]
I have an update method which updates an entity. As my controller already fetched the item from DB, I was attaching my entity with DBContext

```cs
 public async Task UpdateUser(User user, string name)
        {
            using (var context = _dbProvider())
            {
                context.Attach(user);
                user.Username = name;
                await context.SaveChangesAsync();
            }
        }
[SampleAttachProblem.zip](https://github.com/aspnet/EntityFrameworkCore/files/2896573/SampleAttachProblem.zip)

```

This works fine with the Sqlserver provider.

In my unit test cases, I tried to test this using InMemory Provider.

1. First my InMemoryDBContext fetches entity
2. Then sends an update for that entity.

But I get error

The instance of entity type 'Message' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

### Steps to reproduce
1. First my InMemoryDBContext fetches entity
2. Then sends an update for that entity.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

### Further technical details
EF Core version: 2.1.4.0
Microsoft.EntityFrameworkCore.InMemory: 2.1.2.0

Attached are files. My earlier issue got closed and couldnt find a way to open that.
[SampleAttachProblem.zip](https://github.com/aspnet/EntityFrameworkCore/files/2898970/SampleAttachProblem.zip)

**Comment by NidhiNagarro** [comment]
[SampleAttachProblem.zip](https://github.com/aspnet/EntityFrameworkCore/files/2896574/SampleAttachProblem.zip)
Files attached

**Comment by NidhiNagarro** [comment]
Problem being faced while writing unittest case was with methods containing Attach method

1.	Case 1: when we use same DBContext then error says

`      Error : The instance of entity type 'Message' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

Even if we detached DBContext with original one

2.	Case 2: in case we do not use same context and remove all item error says

Error: Attempted to update or delete an entity that does not exist in the store.

**Comment by ajcvickers** [comment]
@NidhiNagarro Both `GetDBContext` and `GetDBContextDetached` generate a new name for the in-memory database each time they run. If you want the same database to be used in both cases (so you can insert with one context instance and update with another) then you'll need to use the same database name for both. Also, deleting the data `EnsureDeleted` doesn't seem appropriate if you're trying to get data out of it.
