### ISSUE TITLE
How to ignore Identity column for hasdata(...)

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#14807]
Hi,

We are working to have support for EF Core Code First from IBM EntityFramework core provider.
recently during HasData(...) we noticed that it's generating insert data even for Identity column.
We have gone through EF Doc and could see internally for SQL server 'SET IDENTITY INSERT ON' is being used. whereas DB2 do not have this option. And DB2 generates value for identity column. 
Now our question is how can we avoid generating values for identity column ?
Is there something which we can pass in model level, EF layer will take care ?

Ref Doc: https://www.learnentityframeworkcore.com/configuration/fluent-api/hasdata-method

HasData call:
modelBuilder.Entity<SEEDATATAB>().HasData(
                new SEEDATATAB {id=1, name = "archana" });

Here id is identity column and primary key.

The issue should exist even for computed column sql.. 

Thanks,
Archana

**Comment by ajcvickers** [comment]
@archanasoni Seeding requires explicit key values to work. If there is no way to enable inserts into an Identity column for DB2, then there is no way to use seeding in this scenario. Seeding will instead only work for tables that don't use Identity columns.
