### ISSUE TITLE
Microsoft.Data.Sqlite: Make SqliteFactory.CreateDataAdapter and CreateCommandBuilder throw

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#14819]
After https://github.com/dotnet/corefx/issues/35564 is implemented, we should update these methods to throw instead of return null. (Or just implement them as part of #13838)

**Comment by roji** [comment]
I think I'd just implement, it's really not a huge deal and issues on that part of the provider are very rare. [My implementation is here](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/NpgsqlDataAdapter.cs) (although it's super old and probably not ideal).
