### ISSUE TITLE
"dotnet ef --help" does not display all possible options

### ISSUE THREAD

**Issue by jaworek** [dotnet/efcore#14817]
<img width="597" alt="screenshot 2019-02-25 at 09 14 33" src="https://user-images.githubusercontent.com/22678765/53323210-cb39c700-38dd-11e9-9245-62bafe8a5625.png">

"dotnet ef --help" command does not display all possible options that are listed in the documentation:
https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

Is there any reason these commands are not listed? In my experience it hurts discoverability of possible options. It would be helpful to have them listed or provide a link to documentation.

### Further technical details
EF Core version: 2.2.1-servicing-10028

**Comment by ErikEJ** [comment]
What is missing?

**Comment by jaworek** [comment]
Command flags mentioned in this site: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

For example:
--json
--context 
--startup-project 
--startup-project 
--framework 
--configuration 
--runtime

**Comment by ajcvickers** [comment]
@jaworek Those options are associated with specific commands, not with the top level `ef`. For example, as it says in the output shown above, to get info on `migrations add`:
```console
C:\aspnet\EntityFrameworkCore>dotnet ef migrations add --help


Usage: dotnet ef migrations add [arguments] [options]

Arguments:
  <NAME>  The name of the migration.

Options:
  -o|--output-dir <PATH>                 The directory (and sub-namespace) to use. Paths are relative to the project directory. Defaults to "Migrations".
  --json                                 Show JSON output.
  -c|--context <DBCONTEXT>               The DbContext to use.
  -p|--project <PROJECT>                 The project to use.
  -s|--startup-project <PROJECT>         The startup project to use.
  --framework <FRAMEWORK>                The target framework.
  --configuration <CONFIGURATION>        The configuration to use.
  --runtime <RUNTIME_IDENTIFIER>         The runtime to use.
  --msbuildprojectextensionspath <PATH>  The MSBuild project extensions path. Defaults to "obj".
  --no-build                             Don't build the project. Only use this when the build is up-to-date.
  -h|--help                              Show help information
  -v|--verbose                           Show verbose output.
  --no-color                             Don't colorize output.
  --prefix-output                        Prefix output with level.
```

**Comment by jaworek** [comment]
Thanks for the explanation.
