### ISSUE TITLE
Relational: Lifecycle hook for initializing a connection

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#14822]
Having a hook to initialize the DbConnection would be very useful. On SQLite, this would allow you to register user-defined functions or load extensions.

This hook should apply both the external connections and onces created by EF.

Today, I would use this so simplify the SpatiaLite loading and enable translations for TimeSpan (https://github.com/bricelam/EFCore.SqliteEx/issues/1) and Regexp (https://github.com/bricelam/EFCore.SqliteEx/issues/2).

**Comment by ajcvickers** [comment]
Covered by #16714
