### ISSUE TITLE
EF Core Global Reading / writing separation Caching Extensions.

### ISSUE THREAD

**Issue by mokeyish** [dotnet/efcore#14834]
**I write an extension ([Go to the repository](https://github.com/mokeyish/EFCoreCaching)) for caching EF entity value in memory.**

1. [ReadStateManager](https://github.com/mokeyish/EFCoreCaching/blob/master/EFCaching/EFCore/ReadStateManager.cs) was shared by all DbContext for reading data.
2. [WriteStateManager](https://github.com/mokeyish/EFCoreCaching/blob/master/EFCaching/EFCore/WriteStateManager.cs) is used for updating data, Every `DbContext` has a `WriteStateManager`. If value was changed it will update to `ReadStateManager` for global reading.

**Is there any hidden danger in the production environment?**

**Comment by ajcvickers** [comment]
@mokeyish First, the code makes heavy use of EF Core internal classes. These will change in any EF Core release and will likely break your code. Personally, I wouldn't put in production with this much hacked internal code.

Beyond that, whether or not it is ready is really up to you and the testing you have done; it's not something we can answer.
