### ISSUE TITLE
Microsoft.EntityFrameworkCore.Relational.Specification.Tests should explicitly set CultureInfo

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#14847]
The `Microsoft.EntityFrameworkCore.Relational.Specification.Tests` package should explicitly set `CultureInfo` for the test(s), else comparison is different and some (in my case query) tests fail (in my case on ordering).

### Further technical details
`Microsoft.EntityFrameworkCore.Relational.Specification.Tests`: 2.2.0

**Comment by ajcvickers** [comment]
@cincuranet We would be happy to take a PR to make the test more robust. We haven't had to resort to setting `CultureInfo` in the past (expect when explicitly testing that) since ideally the tests should be culture-agnostic. But if that's the pragmatic/feasible way of fixing it, then so be it.

**Comment by ajcvickers** [comment]
Superseded by #14912
