### ISSUE TITLE
Memory Leak - Where() with dynamic expression

### ISSUE THREAD

**Issue by TimJRodgers** [dotnet/efcore#14859]
I am building dynamic expressions to perform a where query against a DbSet. This seems to leak a lot of memory, eventually leading to an out of memory exception.

I am using EF Core 2.2 with Sqlite, however it also happens with SqlServer. It seems to be the same problem as Issue #10535 which was closed due to not being reproducible.

Here is a simple code sample that quickly reproduces the problem;

```C#
using System;
using System.Linq;
using System.Linq.Expressions;

using SQLitePCL;

using Microsoft.EntityFrameworkCore;

namespace EfLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create the database
            using (RdbContext rdbContext = new RdbContext())
                rdbContext.CreateDb();

            // Leak memory
            while (true)
                using (RdbContext rdbContext = new RdbContext())
                    rdbContext.LeakMemory();
        }
    }

    class RdbContext : DbContext
    {
        public virtual DbSet<MyEntity> Entities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            Batteries.Init();
            optionsBuilder.UseSqlite("Data Source=C:\\MemLeak.db");
        }

        public void CreateDb()
        {
            Database.EnsureCreated();
        }

        public void LeakMemory()
        {
            Expression<Func<MyEntity, Int64>> exField = s => s.Id;
            Expression<Func<MyEntity, Boolean>> ex = Expression.Lambda<Func<MyEntity, Boolean>>(Expression.GreaterThanOrEqual(exField.Body, Expression.Constant(DateTime.Now.Ticks)), exField.Parameters);
            Entities.Where(ex).ToArray();
        }
    }

    class MyEntity
    {
        public Int64 Id { get; set; }
    }
}
```

If I switch from a `DbSet` to `List<MyEntity>`, with `AsQueryable()`, then it does not leak.

If I replace `Expression.Constant(DateTime.Now.Ticks)` with `Expression.Constant(20L)`, then there is no leak. 

I confirmed that the memory cache size is growing each call. I am using dynamically built expressions a lot, all with varying complexity. This is just the simplest example of the issue.

Thanks,

Tim.

**Comment by ajcvickers** [comment]
@TimJRodgers The reason for this is that `Expression.Constant(DateTime.Now.Ticks)` creates a new constant expression with a different value each time it is executed. This means that each time an expression tree like this is created it doesn't match any previous query and hence a new cache entry is created.

To prevent this, the expression tree should be created with a parameter for the `DateTime.Now.Ticks` value such that the query cache contains a parameterized query into which a different value will be inserted each time it is executed.
