### ISSUE TITLE
In Entity Framework Core 2, I can't seem to remove a foreign key from within OnModelCreating using IMutableEntityType's RemoveForeignKey method.

### ISSUE THREAD

**Issue by denmitchell** [dotnet/efcore#14863]
I have a DbContext subclass (call it FkContext) where foreign keys are defined.  I have a subclass of this subclass (call it NoFkContext) pointing to a different database where I wish to not have those foreign keys.  I created a DropForeignKeys() extension method for ModelBuilder, which uses [IMutableEntityType.RemoveForeignKey](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.imutableentitytype.removeforeignkey?view=efcore-2.1#Microsoft_EntityFrameworkCore_Metadata_IMutableEntityType_RemoveForeignKey_System_Collections_Generic_IReadOnlyList_Microsoft_EntityFrameworkCore_Metadata_IProperty__Microsoft_EntityFrameworkCore_Metadata_IKey_Microsoft_EntityFrameworkCore_Metadata_IEntityType_); however, the generated Up() method still contains the foreign key definitions.  

I could manually remove the foreign key definitions in the Up() method, but it would be better to be able to remove them using something like my extension method below.  Note: if even if I call DbContext.Database.Migrate() from code and step through execution lines, the method does not remove the foreign keys from the model.

Here is the extension method (a less compact version for debugging purposes):

```c#
    public static ModelBuilder DropForeignKeys(this ModelBuilder modelBuilder) {
            var entityTypes = modelBuilder.Model.GetEntityTypes().ToList();
            for (int i = 0; i < entityTypes.Count(); i++) {
                var entityType = entityTypes[i];
                var foreignKeys = entityType.GetForeignKeys().ToList();
                for (int j = 0; j < foreignKeys.Count(); j++) {
                    var fk = foreignKeys[j];
                    entityType.RemoveForeignKey(
                        fk.Properties,
                        fk.PrincipalKey,
                        fk.PrincipalEntityType);
                }
            }
            return modelBuilder;
        }
```

### Steps to reproduce

In the attached Visual Studio solution, at the Package Manager Console, call ...
Add-Migration Initial -Context FkContext
Add-Migration Initial -Context NoFkContext
For additional debugging, set a breakpoint in my extension method and run the console project, which includes the following lines in Program.Main:
```c#
using (var context = new NoFkContext()) {
                context.Database.Migrate();
            }
```

Note: I also tried calling RemoveForeignKey on the entity (Address) directly -- both from within an extension method and from within an EntityTypeConfiguration subclass's Configure method.  No errors, but the foreign key remains.

Per my comment below, I think that the conventions are reasserting themselves as I attempt to remove foreign keys.  The conventions appear to be kept at bay when I merely ignore all navigation properties, as per the following extension method.

 ```c#
        public static ModelBuilder IgnoreNavigationProperties(this ModelBuilder modelBuilder) {

            var entityTypes = modelBuilder.Model.GetEntityTypes().ToList();
            for (int i = 0; i < entityTypes.Count(); i++) {
                var entityType = entityTypes[i];
                var navs = entityType.GetNavigations().ToList();
                for (int j = 0; j < navs.Count(); j++) {
                    modelBuilder.Entity(entityType.Name).Ignore(navs[j].Name);
                }
            }
            return modelBuilder;
        }
```

It would be better if the RemoveForeignKey method either removed the foreign keys or returned an exception.

### Further technical details
[ExploringRemoveForeignKeys.zip](https://github.com/aspnet/EntityFrameworkCore/files/2913961/ExploringRemoveForeignKeys.zip)

EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.9.4)

**Comment by denmitchell** [comment]
I am wondering whether, when I remove the foreign keys using RemoveForeignKey(), the conventions are taking over and adding back in the foreign keys.  In another project, I noticed that when I first define the foreign keys via fluent API and then immediately after that remove them, extra columns are generated, and these extra columns are used in the foreign key definitions in Up().

**Comment by ajcvickers** [comment]
@denmitchell It seems unusual to build the model with FKs and then attempt to remove them. Why not conditionally build the model without them in the first place?

**Comment by denmitchell** [comment]
The "non-FK context" supports history tables that back its "FK context" counterpart.  

Originally, I had written a library to generate SQL Server temporal tables during migrations (EDennis.MigrationsExtensions).  This library works fine; however, I found that I could provide greater control (and better testability) by using EF (rather than SQL Server) to manage the writes to the history tables.  Also, I was able to create some nice reusable base repository methods that allow one to add "as-of" date parameters to Linq query expressions.  (This is harder to do in EF Core when you are using SQL Server temporal tables.) 

To support the "EF-temporal" approach, I have been creating (1) an abstract context that defines the DbSets (and DbQueries, if any) and uses the fluent API to configure various columns; (2) a current-records context that extends the abstract class and that specifies the table, schema, and primary key, as well as calls to HasData and HasValueGenerator for in-memory databases; and (3) a history-records context that extends the abstract class and does what the current-records context does except for history tables (there is a different schema, an expanded primary key, and no call to HasValueGenerator).  

_Importantly, the DbSets shared by both the current-records context and the history-records context point to the same model classes_.  When these model classes have navigation properties, by convention, foreign keys are automatically generated.  And so, the foreign key specs propagate to both the current-records context and the history-records context.  I suppose that I could create base model classes that have no navigation properties and use those base model classes for the history-records context, but I thought that if I could just disable foreign-key generation in the history-records context with a one-liner command, it would simplify the code.   So, I am using the IgnoreNavigationProperties extension method to do just that.

Any thoughts on the approach?

For the purposes of this issue, I am not convinced that the RemoveForeignKey method does anything, as the conventions appear to add the foreign key back to the model immediately after I remove it.  Would it be possible to disable the competing convention when RemoveForeignKey is called?  (Again, I now have a work-around for this.)

**Comment by ajcvickers** [comment]
@denmitchell Thanks for the additional info. We will discuss.

**Comment by ajcvickers** [comment]
@AndriySvyryd to follow up.

**Comment by AndriySvyryd** [comment]
This should be made possible by https://github.com/aspnet/EntityFrameworkCore/issues/2725

**Comment by denmitchell** [comment]
@AndriySvyryd  and @ajcvickers  Thank you.

**Comment by BalassaMarton** [comment]
I have the same problem (version EF Core version 2.1.8), probably for the same reasons (building a snapshot or 'as-of' variant for my DbContext automagically). `RemoveForeignKey` does not actually remove the foreign key. Is there a workaround for this?

**Comment by ChiefInnovator** [comment]
I have this exact same problem with the latest entity framework 2.2.6.
