### ISSUE TITLE
Investigate how ConfigureAwait(false) impacts calling back into user code on .NET Core

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#14861]
This issue is about understanding the full consequences of  https://github.com/aspnet/EntityFrameworkCore/issues/10164 on .NET Core and possibly identifying mitigations (either user guidance or changes to the implementation of https://github.com/aspnet/EntityFrameworkCore/issues/10164) for anything that change could break. 

In particular, we know that EF6 running on .NET Framework initially used ConfigureAwait(false) for the async implementation, but then we had a few customers report issues because specific state stored in the ExecutionContext wasn't flown into delegates we execute on the user's behalf. 

Initially we added a workaround that allowed current Culture to be flown in https://github.com/aspnet/EntityFramework6/commit/2ec5bf6c79a389c87a718acba5eb50a79e0c9a32. The change adds our own custom awaitable and the WithCurrentCulture extension method which replaces ConfigureAwait(false) in our internal async implementaiton. But at a later point other customers reported that other state that wasn't being flown was important to them: security principals. 

Recently, there has been some talk about this issues not affecting .NET Core in the same way, but it is hard find evidence of this so we want to really test it and understand it better. 

One simple example @smitpatel suggested to look at is what happens to the locale used in a call to ToString() in the top level projection of a query. We can have similar tests for other "ambient" state. 

Even if we confirm that this "ambient" state is not flown to user code, we should keep in mind that the user code we call is typically materialization, and there may be other ways this code can be written to flow this state explicitly. In other words, if we believe that the benefit of ConfigureAwait(false) (maybe in terms of performance, although we haven't measured that, and diminished chances of deadlocks when Task.Result is used) is greater than the downside, then we may choose to just document the impact as a breaking change and provide workarounds.

**Comment by ajcvickers** [comment]
Closing in favor of #10164
