### ISSUE TITLE
InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext

### ISSUE THREAD

**Issue by pathmanshakir** [dotnet/efcore#14876]
I am working on project with no repository pattern ASP.net core. I am trying to separate my business logic from controllers, kind of setting up a business layer. I do the following to get all of my users.
Deleting de default constructor DatabaseContext is not helping because then I am getting error in the following line.

```C#
 using (var ctx = new DatabaseContext())
        {
            var query = ctx.Users;
            var res = await query.ToListAsync();
            return res;
        }
```
DbContext
```C#
public class DatabaseContext : DbContext
{
    public DatabaseContext() : base() { }
    public DatabaseContext(DbContextOptions <DatabaseContext>  options) : base(options) { }
    public DbSet<User> Users { get; set; }
    public DbSet<OvertimeRequest> OvertimeRequests { get; set; }
    public DbSet<HolidayRequest> HolidayRequests { get; set; }
    public DbSet<PaymentRequest> PaymentRequests { get; set; }
}
```
OvertimeRequestBusiness
```C#
public class OvertimeRequestBusiness
{
    public static OvertimeRequestBusiness Instance { get; } = new 
        OvertimeRequestBusiness();

    public OvertimeRequestBusiness() { }

    public async Task<List<User>> GetAllUsersAsync()
    {
        **using (var ctx = new DatabaseContext())**
        {
            var query = ctx.Users;
            var res = await query.ToListAsync();
            return res;
        }
    }
}
```
Controller
```C#
[Route("users")] 
[HttpGet]
public async Task<List<User>> GetAllUsers()
{
    return await OvertimeRequestBusiness.Instance.GetAllUsersAsync();
}
```
And the error I get is.
**InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext****

**Comment by ajcvickers** [comment]
@pathmanshakir Do you register the DbContext using `AddDbContext`? If so, can you show what that code looks like?

**Comment by pathmanshakir** [comment]
Problem is solved, you can see the solution here. 
https://stackoverflow.com/a/54941651/10587542
Thanks for your time @ajcvickers
