### ISSUE TITLE
Number of automated commits is getting out-of-hand

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#14879]
For example:
![image](https://user-images.githubusercontent.com/1430078/53588790-a42fff00-3b42-11e9-8c8b-eb92123c04d1.png)

**Comment by smitpatel** [comment]
+1000

**Comment by roji** [comment]
+10000 (to more closely approximate the number of automated commits we've had recently)

**Comment by roji** [comment]
(clue: a single github user can add more than one emoji reaction)

**Comment by ajcvickers** [comment]
We're now consolidating to once-per-day-per-repo, which is still quite a lot. We will keep giving feedback as it becomes more apparent how getting to coherency will work going forward and potentially revisit later.

**Comment by CZEMacLeod** [comment]
It would help (for us poor end users) if we could snooze/ignore/avoid/filter notifications for the dotnet-maestro although that would be more of a GitHub thing than an EF / .Net team thing.

**Comment by ErikEJ** [comment]
@CZEMacLeod You could use a mail filter / rule.

**Comment by CZEMacLeod** [comment]
@ErikEJ I was talking about on the GitHub website [https://github.com/notifications](https://github.com/notifications) or [https://github.com/aspnet/EntityFrameworkCore/notifications](https://github.com/aspnet/EntityFrameworkCore/notifications)
I look to see what's new, closed etc. to keep abreast of the changes and work going on, and if there are any issues that affect what I'm working on.
This was fine until the excessive notifications from dotnet-maestro and the merging of all the AspNet repositories which means I now have hundreds/thousands of notifications to try to skim through.

**Comment by ErikEJ** [comment]
Sorry, I assumed you were subscribing to email notifications
