### ISSUE TITLE
In.Ex 4.0 preview NuGet build

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#14906]
In.Ex team has recently released first preview NuGet package for In.Ex 4.0 with great API improovements, supports of new features and new async extentions (related PR - https://github.com/dotnet/reactive/pull/423).
Currently I'm trying to use it in my project with EF Core, but due to type conflicts it causes  TypeLoadException:
`Message: System.TypeLoadException : Could not load type 'System.Collections.Generic.IAsyncEnumerable'1' from assembly 'System.Interactive.Async, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. .....`
It would be great to have EF Core updated with support of new version of System.Interactive.Async. Will it be possible ?

**Comment by ajcvickers** [comment]
Pinging @divega to follow up on this one.

**Comment by ajcvickers** [comment]
@anton-beetroot-23071996 We're still working through the interaction of EF Core and the new async enumerable support in C# 8. We plan to have something to say publicly in the next few weeks, likely as part of a preview blog post.

**Comment by devsko** [comment]
@ajcvickers Please take into account that this bug means that you cannot reference EF and Ix at the same time (direct or transitive). It's not only about support IAsyncEnumerable.

**Comment by ajcvickers** [comment]
@devsko This is a point-in-time situation. We plan to have a coherent solution before 3.0 ships.

**Comment by alan994** [comment]
@ajcvickers  Any update on this?

**Comment by ajcvickers** [comment]
@alan994 We working on it, but it's not quite ready yet. Hopefully it will make preview 6. More realistically, preview 7.

**Comment by anton-beetroot-23071996** [comment]
@ajcvickers Hi) Is there exist any non-closed issue for this (or maybe PR), to track on its status ?

**Comment by ajcvickers** [comment]
@anton-beetroot-23071996 It will happen as part of #15498

**Comment by xaviergxf** [comment]
@ajcvickers i'm still seeing this error on preview 8.

**Comment by ajcvickers** [comment]
@xaviergxf Please open a new issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by shravan2x** [comment]
I'm facing the same issue on preview8.

**Comment by smitpatel** [comment]
@shravan2x - As @ajcvickers said above, please open new issue with requested details so we can investigate.
