### ISSUE TITLE
EnitityCore 2.2.1 database default newid() Guid not being used the Entity Framework

### ISSUE THREAD

**Issue by zp978** [dotnet/efcore#14919]
My sql server database table has Guid as primary key (Id) column and default as newid(), when making an insert to the table using entity core, if i dont supply the Id field i would like the insert done with the newid() default generated from the database. This does not happen as the Id Guid in my Entity class is always assigned {00000000-0000-0000-0000-000000000000} if i dont set it and hence Enity Core uses this for insert, how can i make Entity framework not to use the {00000000-0000-0000-0000-000000000000} and use the newid() guid default from the database. 

I have tried attribute on the Id property as below , but no luck the value {00000000-0000-0000-0000-000000000000} get assigned and Id is not generated from DB default newid()

my entity class example 

       public partial class Building
       {
       
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        public string Description { get; set; }

          }
}

**Comment by wstaelens** [comment]
use the modelbuilder.
See: https://github.com/aspnet/EntityFrameworkCore/issues/14518#issuecomment-457763408

**Comment by ajcvickers** [comment]
@zp978 I have not been able to reproduce this using the code shown--see my attempt below. Can you post a runnable project/solution or complete code listing (like below) that demonstrates the behavior you are seeing.

```C#
public partial class Building
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }
    public string Description { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Building>();
    }
}


public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var building = context.Add(new Building()).Entity;

            context.SaveChanges();

            Console.WriteLine(building.Id);
        }

        using (var context = new BloggingContext())
        {
            Console.WriteLine(context.Set<Building>().Single().Id);
        }
    }
}
```
Output:
```
688a6203-44cf-4dee-0497-08d6a18b65b9
688a6203-44cf-4dee-0497-08d6a18b65b9
```

**Comment by zp978** [comment]
Thanks for the reply. 
Please see code below 

    public partial class APDbContext : DbContext
    {
        public APDbContext()
        {
        }

        public APDbContext(DbContextOptions<APDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assets> Assets { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity<Assets>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50);

            });
        }
    }


   public partial class Assets
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        public string Description { get; set; }
        
    }

// add an asset here I have not set the assets.Id but by default EF core assigns {00000000-0000-0000-0000-000000000000} and this is what is attempted to be added to the database. in the sql server database ID column is UniqueIndentifier not null primary key with default value (newid()) 

       public bool AddAsset()
        {
            bool result=false;
            
            Assets assets = new Assets();
            assets.Description = "Test Description";
            _dbContext.Add(assets);
            return result;

        }
![image](https://user-images.githubusercontent.com/48198898/54168969-ddf8f200-44c0-11e9-95df-d5ca2c261757.png)

**Comment by ajcvickers** [comment]
@zp978 The call to `ValueGeneratedNever` configures the property to never use generated values. If you want to use any kind of generated values, then don't call this method. By default, without this call, EF will generate GUIDs on the client using a sequential generator. If you want to instead use the `newid()` constraint, then configure it like so:
```C#
modelBuilder
    .Entity<Assets>()
    .Property(e => e.Id)
    .HasDefaultValueSql("newid()");

```

**Comment by zp978** [comment]
thank you for the reply. 

One question ValueGeneratedNever was not added by me but done by scaffold command when it is run. So if I change the .HasDefaultValueSql("newid()"); in the model builder I need to make this change every time after I run the scaffold command. Is there a soltion to update modelBuilder as 
    .Entity<Assets>()
    .Property(e => e.Id)
    .HasDefaultValueSql("newid()"); 

Then the Id  column default value is not updated when scaffold command is run in future ?

**Comment by ajcvickers** [comment]
@zp978 Using the same table for `Assets` that you posted in #14910, I am not able to reproduce this. I get the following scaffolded for the ID column:
```C#
entity.Property(e => e.Id)
    .HasColumnName("ID")
    .HasDefaultValueSql("(newid())");
```
This works correctly for me when saving new entities. That is, they end up with the ID generated by the `newid()` constraint.

**Comment by danielmeza** [comment]
@zp978 remember,  for pk guid is recommended use sequential id

**Comment by wgutierrezr** [comment]
Hi, I am having this issue after upgrade Asp.Net core 2.2 to Asp.Net Core 3.1.

**Comment by ajcvickers** [comment]
@wgutierrezr Please file a new issue and include a small, runnable project or complete code listing that demonstrates the behavior you are seeing.

**Comment by wgutierrezr** [comment]
Hi, I solved my issue with the GUID, basically, I need to create it in the controller manually. I base my solution regarding this post: https://stackoverflow.com/questions/53493025/entity-framework-core-auto-generated-guid/53495148#53495148

Thanks.

**Comment by roji** [comment]
@TajievOlimjon that should already be the default behavior: a primary key Guid property should get a random Guid generated for it ([see the Npgsql docs](https://www.npgsql.org/efcore/modeling/generated-properties.html#guiduuid-generation)). If you're seeing a different behavior, please post a new issue on https://github.com/npgsql/efcore.pg with a runnable code sample that shows the problem.

**Comment by TajievOlimjon** [comment]
Sequential value generation cannot be used for the 'Id' property on the 'Book' object type because the property type is 'Guid'. Consecutive columns can only be of type short, int, or long.

**Comment by roji** [comment]
@TajievOlimjon as I wrote above, I need a runnable code sample, and not just an error message. Note that if you're using a version of EF prior to 6.0, that's no longer supported.
