### ISSUE TITLE
Is there a way from EFCore to not resolve the Func<T>?

### ISSUE THREAD

**Issue by mayconbeserra** [dotnet/efcore#14914]
The following code has one function called CompanyQueries.WithJustOneAdmin:

```
            var companiesWithJustOneAdmin = Server.DbContext.Companies
                .Include(c => c.CompanyActivation)
                .Include(c => c.UserCompanies)
                    .ThenInclude(uc => uc.Company)
                        .ThenInclude(c => c.VerifiedBy)
                .Where(CompanyQueries.WithJustOneAdmin(mbUserId))
                .ToList();

```
```
        public static Func<Company, bool> WithJustOneAdmin(Guid userId)
        {
            return company
                => company.UserCompanies.All(uc => uc.UserId == userId);
        }
```

As far as I know, EFCore is going to select all the data and apply the Where with the `WithJustOneAdmin Func` on the client side for each entry.

Is that the right behaviour of that?

What we noticed here, in some cases, Func didn't filter the data.

### Further technical details

EF Core version:  Version="2.1.3"
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Linux container

**Comment by ajcvickers** [comment]
@mayconbeserra The delegate passed to the `Where` clause is opaque to EF and is not something that can be translated. Instead, pass an expression tree in the `Where` clause. This will allow EF to analyse it and generate SQL. For example:
```C#
public static Expression<Func<Company, bool>> WithJustOneAdmin(Guid userId)
{
    return company
        => company.UserCompanies.All(uc => uc.UserId == userId);
}
```
