### ISSUE TITLE
Distributed Transactions support 

### ISSUE THREAD

**Issue by ahamed-ishak** [dotnet/efcore#14939]
Ef core documentation says ef core does not support [Distributed Transactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions#limitations-of-systemtransactions) 

Is there any alternative way to use ef core with Distributed Transaction ? Or when its going to support Distributed Transaction in ef core.

This is a sample code that will throw System.PlatformNotSupportedException with message 

> This platform does not support distributed transactions.

  ```
namespace TransactionScope.PersistenceLayer
{
    public class DatabaseManager:IDisposable
    {
        public DataContextOne DataContextOne { get; }
        public DataContextTwo DataContextTwo { get; }

        public DatabaseManager()
        {
            DataContextOne = new DataContextOne();
            DataContextTwo = new DataContextTwo();
        }


        public void SaveChanges()
        {
            using (var transactionScope=new System.Transactions.TransactionScope())
            {
                DataContextOne.SaveChanges();
                DataContextTwo.SaveChanges();
            }
        }

        public void Dispose()
        {
            DataContextOne?.Dispose();
            DataContextTwo?.Dispose();
        }
    }
}

```
```
class Program
    {
        static void Main(string[] args)
        {
            using (var databaseManager=new DatabaseManager())
            {
                var student = new Student
                {
                    Name = "Sample Name " + Guid.NewGuid().ToString()
                };

                databaseManager.DataContextOne.Add(student);
                databaseManager.DataContextTwo.Add(student);

                databaseManager.SaveChanges();

            }
        }
    }
```

**Comment by ajcvickers** [comment]
@ahamed-ishak As @divega [wrote in a this comment](https://github.com/aspnet/EntityFramework.Docs/issues/1094#issuecomment-435494122):
> This is a limitation of System.Transactions in .NET Core, not a limitation of EF Core. If you use EF Core on .NET Framework, the implementation of System.Transactions there does support distributed transactions. That is what "platform" is referring to in the exception you saw.

> The limitation is tracked at dotnet/corefx#13532. I encourage you to add information on that issue about why you need this and to up-vote it.
