### ISSUE TITLE
Scaffold-DbContext: accept a text file with TableName|CollectionName|EntityName maps

### ISSUE THREAD

**Issue by jwatkin** [dotnet/efcore#14938]
This is a feature request for an additional parameter to be added to the Scaffold-DbContext command. The purpose of this parameter is to allow a user to specify a text file that contains the tables to be reverse engineered as well as their associated collection and entity names. This would allow a user to:

- specify completely different names for a table's collection and entity representations
- provide a precise pluralization map

Here's an example text file for reverse engineering two existing tables named ScheduledCourses and Faculty:
```
TableName | CollectionName | EntityName
ScheduledCourses | CourseOfferings | CourseOffering
Faculty | Instructors | Instructor
```

**Comment by jwatkin** [comment]
The DbSetName column values would also apply to any other entity-based collections that are defined during the reverse engineering. So maybe "DbSetName" should be "CollectionName" instead.

**Comment by ErikEJ** [comment]
EF Core Power Tools allows you to do this

**Comment by jwatkin** [comment]
@ErikEJ Thank you for all of your help with this. EF Core Power Tools is able to handle my use case. For a database table name of "course_sched", I was able to have EF Core Power Tools reverse engineer it to:
`public virtual DbSet<CourseOffering> CourseOfferings { get; set; }`
and
`CourseOffering.cs`

**Comment by ajcvickers** [comment]
@jwatkin This is not something we are planning to add to EF Core at this time; the recommendation for now is to use Power Tools. At some point in the future we hope to implement "update model from database" functionality (#831) at which point this would be covered.

**Comment by fenma** [comment]
It's disappointing that no one here is explaining how to do that. Just saying that you can do it, is not enough.

**Comment by fenma** [comment]
> 
> 
> EF Core Power Tools allows you to do this

You made really nice tool. How can i use a configuration file for "tableName|CollectionName|EntityName maps" in your tool. I see only option "Pluralize, singularize generated object names (english)"

Please check again the post of JWatkin.
I made a text file with mapping. Can i use it with your tool?

**Comment by ErikEJ** [comment]
@fenma You can find the docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-epftrenamingjson
