### ISSUE TITLE
Cleanup story in RelationalTestStore

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#14957]
What's the cleanup story in `RelationalTestStore`? The database creation generally happens in `Initialize` method, but is there some place to do safe database drop? I personally don't think tests should leave stuff behind.

**Comment by smitpatel** [comment]
>  I personally don't think tests should leave stuff behind.

We leave behind databases. This may be SqlServer specific but Database creation is time-expensive step. Especially, SqlServer takes few seconds before database is ready to be used after creation. Hence we don't drop databases in code. Whenever there is issue, you can manually delete all databases and tests will recreate them. What we do instead is clean all objects from database (a fully clean database) and then recreate all objects and seed data as needed. The processing happens here.
https://github.com/aspnet/EntityFrameworkCore/blob/9be0341cfc60a852b7c30da444b460702e0a055d/test/EFCore.Specification.Tests/TestUtilities/TestStore.cs#L53-L60

Providers can override appropriate methods to implement the behaviour.

**Comment by smitpatel** [comment]
If you are too keen on deleting databases after test is done, then here is how Cosmos does it. (Since Emulator supports limited no of collections)

https://github.com/aspnet/EntityFrameworkCore/blob/9be0341cfc60a852b7c30da444b460702e0a055d/test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs#L137-L146

**Comment by cincuranet** [comment]
Yes, that's surely SQL Server specific. In Firebird, for example, database creation is instant.

Dropping in `Dispose` mean the database name needs to be unique per store (aka no sharing), because other tests might be running using the same database.

So, looks like some kind of "reference" counting or unique names is my only option here. :(

**Comment by smitpatel** [comment]
You can write a script outside of testing to run after build has passed to drop all databases.

**Comment by cincuranet** [comment]
No I can't. I would have to know the names of DBs somehow (Firebird does not have a "master" database).

**Comment by ErikEJ** [comment]
Maybe you can reuse what I do for SQL CE?

**Comment by cincuranet** [comment]
@ErikEJ in case of `CreateShared` the database is left behind anyway, if I read your code correctly.

**Comment by roji** [comment]
Note that leaving databases behind (or at least having the option to) can also sometimes be useful for inspecting the data after a problematic test has already executed.

**Comment by cincuranet** [comment]
Agree. I usually stop the test while it's running and inspect the database at that point.
