### ISSUE TITLE
DbContext Includes Every Class. Not Just Those Defined with DBSet<T>

### ISSUE THREAD

**Issue by eopeter** [dotnet/efcore#14951]
After upgrading to v 2.2.2 my DBContext Now includes every class in the Solution (domain and entity objects) and validating their properties OnModelCreating() override.

For Example: I have `Address()` and `AddressModel()` and only defined `DBSet<Address>` but when I run my project, `AddressModel` is included in `builder.Model.GetEntityTypes()`

From the below error message, the Dbcontext should not be looking at `AddressModel` or `ProviderModel` as they are not `DBSet<T>` property of DbContext.

Address, Provider are in namespace Project.Data.Models (class library)
AddressModel, ProviderModel are in namespace Project.Core.Models (class library)

###ERRORS####
An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to determine the relationship represented by navigation property 'AddressModel.ProviderList' of type '`List<ProviderModel>`'. Either manually configure the relationship, or ignore this property using the '`[NotMapped]`' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

### Further technical details
EF Core version: 2.2.2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: (e.g. Visual Studio 2017 15.9.7

**Comment by ajcvickers** [comment]
@eopeter It has always been the case (even in classic EF) that the `DbSet` properties represent the roots of the model, but that [other entity types discovered through navigation properties](https://docs.microsoft.com/en-us/ef/core/modeling/included-types#conventions) are also included.

Given this, if the behavior you are seeing seems like a bug, then please post a small, runnable project/solution that demonstrates the behavior you are seeing.

**Comment by eopeter** [comment]
This seems to be a bug with my specific project that I would need to resolve. Thanks!!
