### ISSUE TITLE
Querying the sub-entities of a table that uses TPH does not return the base entities 

### ISSUE THREAD

**Issue by MSiffert** [dotnet/efcore#14962]
I have two DbContext. A BaseDbContext and one that inherits from the BaseDbContextcalled FemaleDbContext.

```
public class BaseDbContext : DbContext
{
    public BaseDbContext(DbContextOptions options) : base(options) { }

    public virtual DbSet<Person> Person { get; set; }
    public virtual DbSet<House> House { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().ToTable("Person", "dbo");
        modelBuilder.Entity<House>().ToTable("House", "dbo");

        modelBuilder.Entity<Person>().HasOne(e => e.House).WithMany(e => e.Persons);
        modelBuilder.Entity<House>().HasMany(e => e.Persons).WithOne(e => e.House);
    }
}

```
The goal is to extend the Person entity with another property. I do not want to use shadow properties because its too dynamic. So I am trying to make it work using TPH. Here is my other context:

```
public class FemaleDbContext : BaseDbContext
{
    public DbSet<Female> Female { get; set; }

    public FemaleDbContext(DbContextOptions<FemaleDbContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Female>().HasBaseType<Person>();

        base.OnModelCreating(modelBuilder);
    }
}
```

As you can see, my sub-context should use the Female entity instead of the  Person. The problem is that when I run this.Context.Female.ToList() on my SubDbContext, only entities with the value Female inside the Discriminator field inside my database are returned. Entities with the value Person in that table are returned. But I want to get every entity.

Also, here are my entities:

```
public class Person
{
    public int Id { get; set; }
    public string Firstname { get; set; }
    public string Middlename { get; set; }
    public string Lastname { get; set; }
}

public class Female : Person
{
    public bool? IsPregnant { get; set; }
}
```

How can I configure my DbContext that this.Context.Female.ToList() returns both Females and Persons. **Note that this.Context.Person.ToList() already returns everything, not only Persons**

Here is a very simple repository to reproduce the problem:
https://github.com/MSiffert/EFCore-TPH-Example
The GET inside PersonController returns everything while the GET in FemaleController only returns the `Female ` entities

**Comment by MSiffert** [comment]
After some research I realised that this is the expected behavious. I am expecting a list of `Female` object, but the base entities cannot be converted into the Person entities. One solution I have used in my Sub-Context is to simply override every new `Person` entity to be a `Female` entity. That way everything works as expected.

 ```

public override int SaveChanges()
{
    foreach (var entityEntry in this.ChangeTracker.Entries())
    {
        if (entityEntry.Entity is Person)
            entityEntry.Property("Discriminator").CurrentValue = "Female";
    }

    return base.SaveChanges();
}

```

**Comment by ajcvickers** [comment]
@MSiffert TPH mappings are used to preserve the inheritance hierarchy when going to and from the database. Over-writing the discriminator property in that way means that TPH isn't really even being used. In such a case, it's probably better just to map both entity types to the same table without using TPH. Some columns could not be mapped for one type if they are not needed and the column is nullable.
