### ISSUE TITLE
EF Core Cancel edit: Entity Collection member does not returns original values

### ISSUE THREAD

**Issue by azeemil** [dotnet/efcore#14966]
I tried many ways to solve this issue.
```C#
 Context.Entry(user).Collection(a => a.GroupMembers).LoadAsync();
                        //.Query()
                        //.Include(b => b.Group)//.ThenInclude(c => c.GroupMembers)
                        //.Load();
                    Context.Entry(user).Reload();

  public void RejectChanges()
        {
            foreach (var entry in Context.ChangeTracker.Entries())
            {
                switch (entry.State)
                {
                    case EntityState.Modified:
                    case EntityState.Deleted:
                        entry.State = EntityState.Modified; //Revert changes made to deleted entity.
                        entry.State = EntityState.Unchanged;
                        break;
                    case EntityState.Added:
                        entry.State = EntityState.Detached;
                        break;
                }
            }
        }
```
All properties reloaded. But Collection reloading did not work.

**Comment by ajcvickers** [comment]
@azeemil Can you be more specific about exactly what it is you're trying to do? For example, if the goal is to ensure that the context contains fresh data, then usually that is best achieved through a new context instance at the beginning of the unit of work. On the other hand, if the goal is to refresh a graph of entities such that local and database changes are preserved, then that it quite hard to do because various kinds of conflicts will need to be resolved.

**Comment by azeemil** [comment]
i am trying to reload data. I use WinForm bindingSource. When user edit data and click save button it is ok. When click cancel button edited data returns original value. But Collection member does not return.

I use this method to discard changes. 
public void Discard(TEntity entity)
        {
            var entry = Context.Entry(entity);
            switch (entry.State)
            {
                case EntityState.Modified:
                    entry.State = EntityState.Unchanged;
                    break;
                case EntityState.Added:
                    entry.State = EntityState.Detached;
                    break;
                case EntityState.Deleted:
                    entry.Reload();
                    break;
            }
        }
this work for model members except collections.

    public partial class User : IBaseEntity, IAuditableEntity, IActive
    {
        private string _password;
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password
        {
            get => string.IsNullOrEmpty(_password) ? string.Empty : 
                CryptographicHelper.Decrypt(_password);
            set => _password = CryptographicHelper.Encrypt(value);
        }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; } = true;
        public int CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual ICollection<UserPermission> Permissions { get; set; }
        public virtual ICollection<UserBranch> Branches { get; set; }
        public virtual ICollection<UserWarehouse> Warehouses { get; set; }
    }

**Comment by ajcvickers** [comment]
@azeemil If the intent is to discard all changes made and reload from the database, then this would best be achieved by disposing the context instance and creating a new one.

**Comment by azeemil** [comment]
Is there another  way to solve this issue? i don't want to dispose context.

**Comment by ajcvickers** [comment]
@azeemil You could detach all entities to clear the context out. For example:
```C#
foreach (var entityEntry in context.ChangeTracker.Entries().ToList())
{
    entityEntry.State = EntityState.Detached;
}
```
However, this isn't efficient and is not recommended.
