### ISSUE TITLE
Question: Does IMigrator.Migrate apply all migrations up to the given migration or does it apply the given migration directly

### ISSUE THREAD

**Issue by FunkyLambda** [dotnet/efcore#14977]
Further to https://github.com/aspnet/EntityFrameworkCore/issues/9968, which was closed with a resolution to updated Migration docs as part of https://github.com/aspnet/EntityFramework.Docs/issues/518, I'd like to know:

Does `IMigrator.Migrate` apply all migrations *up to* the given migration name or does it apply the given migration directly?

I.e., let's say you have migrations IM, M1, M2, ...., Mn, where IM is the initial migration. If I call `IMigrator.Migrate` and pass in some Mi, will all migrations IM, M1, M2, ..., Mi be applied? Or does it just do IM, Mi?

I'm not sure which part of the Migration docs were updated, but the info I found was extremely limited, to the point where it might as well not exist: 
https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#apply-migrations-at-runtime

**Comment by ajcvickers** [comment]
@FunkyLambda It will apply all migrations _that have not yet been applied_ up-to and including the given migration.
