### ISSUE TITLE
One DbContext instance between different IIS InProcess asp.net core apps ?

### ISSUE THREAD

**Issue by smokeelow** [dotnet/efcore#14978]
I have 2 web applications running on IIS(asp.net core 2.2 InProcess mode)

One of the apps has a big database class, a lot of relations, value conversions etc.:
**Artage.Web.Data.AppDbContext**
 ![Artage Web.Data.AppDbContext](https://user-images.githubusercontent.com/1822237/54094601-d515fc80-43aa-11e9-81c2-29eb157f3728.png)

Another app has a mega simple database class:
**Artage.DIS.Data.AppDbContextCli**
![Artage DIS.Data.AppDbContextCli](https://user-images.githubusercontent.com/1822237/54094626-fb3b9c80-43aa-11e9-8d96-33af23e576e1.png)

So... when i'm trying to execute following code
```
using (AppDbContextCli db = new AppDbContextCli())
{
      int imagesCount = await db.Images.AsNoTracking().CountAsync()
}
```
i'm getting error like this

> The property 'Issue.Tags' could not be mapped, because it is of type 'List<string>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

this looks weird to me, because Issue model is not even declared in AppDbContextCli.

as a workaround i added following configuration for AppDbContextCli
```
modelBuilder.Ignore<BlogPost>();
modelBuilder.Ignore<Category>();
modelBuilder.Ignore<Order>();
modelBuilder.Ignore<FolderItem>();
modelBuilder.Ignore<Issue>();
modelBuilder.Ignore<PaymentMethod>();
modelBuilder.Ignore<User>();
modelBuilder.Ignore<UserImagePurchases>();
modelBuilder.Ignore<CampaignCoupon>();
modelBuilder.Ignore<CampaignPromotion>();
modelBuilder.Ignore<ImageCategory>();
modelBuilder.Ignore<ChatUser>();
modelBuilder.Ignore<OrderCoupon>();
modelBuilder.Ignore<TeamUser>();
modelBuilder.Entity<Product>().Ignore(i => i.Tags);
modelBuilder.Entity<Image>().Ignore(i => i.AverageColor);
modelBuilder.Entity<Image>().Ignore(i => i.ColorPalette);
```

**Comment by ajcvickers** [comment]
@smokeelow Most likely here is a reference from one of the entity types that you are mapping to one of the types that you intend not to map. (EF traverses the graph of entity types to define the model; it doesn't only bring in types for which there is an explicit call to `Entity`.)

If this isn't the case, then we're likely going to need a small, runnable project/solution or complete code listing that demonstrates the problem for us to be able to fully investigate.

**Comment by smokeelow** [comment]
@ajcvickers didn't know that but this is definitely my case. Thanks!
