### ISSUE TITLE
NextValueAsync + CancellationToken

### ISSUE THREAD

**Issue by kolcsara** [dotnet/efcore#14980]
Trying to use a CancellationToken in an AddAsync(xEntinty, ct) and it doesn't cancels the task.
Can call the CancellationTokenSource.Cancel() before the AddAsync or in meanwhile when the task is running, but the same result comes up: The entity is added and shouldn't be..

### Steps to reproduce

```
var cts = new CancellationTokenSource();
var userEntity = _mapper.Map<UserEntity>(user);
cts.Cancel();
await _context.Users                     // _context is an instance of an inherited DbContext class
                .AddAsync(userEntity, cts.Token)
                .ConfigureAwait(false);
```

And somewhere deep, this happens in the EF Core:
```
public new virtual Task<TValue> NextAsync(
            [NotNull] EntityEntry entry,
            CancellationToken cancellationToken = default)
                => Task.FromResult(Next(entry));
```
So the CancellationToken isn't respected.

### Further technical details
EF Core commit hash: (latest on the repository) 1282c16 
EF Core.Sqilte.Core: 2.2.1
EF Core.Tools: 2.2.1

**Comment by ajcvickers** [comment]
@kolcsara The reason for this is that `AddAsync` normally does not actually do any async work. In most cases, `Add` should be used. (Some specialized forms of value generators might do async work in AddAsync, but that's very uncommon.)
