### ISSUE TITLE
how about an example

### ISSUE THREAD

**Issue by jwisener** [dotnet/efcore#14986]
Any examples?

**Comment by ajcvickers** [comment]
@jwisener It's not clear to me exactly what you are commenting on, but the [docs](https://docs.microsoft.com/en-us/ef/core/) have many examples, and there are also some [samples in the repo](https://github.com/aspnet/EntityFrameworkCore/tree/master/samples).

**Comment by jwisener** [comment]
Sorry, I guess the "provide feedback" didn't link this correctly.
