### ISSUE TITLE
"Fully Defined" One-To-Many Relationship Creates Multiple FK's in Migration

### ISSUE THREAD

**Issue by Cooksauce** [dotnet/efcore#15017]
When fully defining a one-to-many relationship, multiple foreign keys are created in the migration.

```c#
public class Author
{
    public Guid Id { get; set; }
    public virtual ICollection<Book> Books { get; set; }
}
public class Book
{
    public long Id { get; set; }

    public Guid AuthorId { get; set; }
    public virtual Author Author { get; set; }
}

protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Entity<Author>()
                .HasMany(a => a.Books)
                .WithOne()
                .HasForeignKey(b => b.AuthorId)
                .OnDelete(DeleteBehavior.Cascade);
}
```

This results in 2 FKs, "**AuthorId**" and "**AuthorId1**" being created. 

* Removing the line: "public virtual Author Author { get; set; }" alleviates the problem. (Due to my use case, this isn't a good solution)

This leads me to believe EF isn't recognizing that the 'virtual Author' should be apart of the relationship defined in the Fluent API. Is there a way to indicate they are one relationship?

### Further technical details
EF Core version: (2.2.2)
Database Provider: (Npgsql)

**Comment by smitpatel** [comment]
Your WithOne call does not pass any argument explicitly stating that there is no back navigation hence they become 2 relationships.

```C#
 builder.Entity<Author>()
                .HasMany(a => a.Books)
                .WithOne(b => b.Author) // <------ this change
                .HasForeignKey(b => b.AuthorId)
                .OnDelete(DeleteBehavior.Cascade);
```
