### ISSUE TITLE
Invalid column name error

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#15021]
EF Core 2.2.2

I am getting an error `Invalid column name 'BarraSyncLogDetailID'.  I have used a utility to search the root directory and every file in every sub folder and the string "BarraSyncLogDetailID" does not appear in ANY file (case insensitive) in my project.  I have also scripted my entire database and searched it for the string "BarraSyncLogDetailID" - it is not found.  I have no idea how or why EF thinks there is a column of such a name on my table.  How can I troubleshoot this further?

Query:

	var query = from h in db.Holdings select h;	
    string sql = query.ToSql();

sql:

	"SELECT [h].[ID], 
	[h].[BarraSyncLogDetailID], // no such column
	[h].[CUSIP], 
	[h].[DimeMainClassDesc], 
	[h].[DimeSecondClassDesc], 
	[h].[EffectiveDate], 
	[h].[EntityID], 
	[h].[ISIN], 
	[h].[LogEntityID], 
	[h].[MainAssetID], 
	[h].[MainAssetIDType], 
	[h].[Quantity], [h].[SEDOL], [h].[SecurityAlias], [h].[SecurityID], [h].[SecurityIDType]\r\n

	FROM [SyncLog].[Holdings] AS [h]"

Error Message:

	Invalid column name 'BarraSyncLogDetailID'.

Stack Trace:
	

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Janus.Equity.BarraOne.DAL.LoggingService.SaveLogHoldings(List`1 entities) in C:\LoggingService.cs:line 163
   at Janus.Equity.BarraOne.Test.LoggingTests.InsertHolding() in C:\LoggingTests.cs:line 50
   
   
   
Holding.cs

	public class Holding
    {
        public long ID { get; set; }
        public long LogEntityID { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string SecurityAlias { get; set; }
        public string SecurityID { get; set; }
        public string SecurityIDType { get; set; }
        public string DimeMainClassDesc { get; set; }
        public string DimeSecondClassDesc { get; set; }
        public string CUSIP { get; set; }
        public string SEDOL { get; set; }
        public string ISIN { get; set; }
        public string EntityID { get; set; }
        public double Quantity { get; set; }
        public string MainAssetID { get; set; }
        public string MainAssetIDType { get; set; }

        public virtual JEntity JEntity { get; set; }
    }

DbContext:

		// Holdings -------------------
		mb.Entity<Holding>().ToTable("Holdings", SchemaName).HasKey(x => x.ID);
		mb.Entity<Holding>().HasOne(x => x.JEntity).WithMany(x => x.Holdings).HasForeignKey(x => x.LogEntityID).OnDelete(DeleteBehavior.Restrict);
	
	
Table:

	USE [RRA]
	GO

	/****** Object:  Table [SyncLog].[Holdings]    Script Date: 3/13/2019 2:43:28 PM ******/
	SET ANSI_NULLS ON
	GO

	SET QUOTED_IDENTIFIER ON
	GO

	CREATE TABLE [SyncLog].[Holdings](
		[ID] [bigint] IDENTITY(1,1) NOT NULL,
		[LogEntityID] [bigint] NOT NULL,
		[EntityID] [varchar](50) NULL,
		[EffectiveDate] [datetime2](0) NULL,
		[SecurityAlias] [varchar](50) NULL,
		[SecurityID] [varchar](50) NULL,
		[SecurityIDType] [varchar](50) NULL,
		[Quantity] [float] NULL,
		[DimeMainClassDesc] [varchar](50) NULL,
		[DimeSecondClassDesc] [varchar](50) NULL,
		[SEDOL] [varchar](50) NULL,
		[CUSIP] [varchar](50) NULL,
		[ISIN] [varchar](50) NULL,
		[MainAssetID] [varchar](50) NULL,
		[MainAssetIDType] [varchar](50) NULL,
	 CONSTRAINT [PK_Holdings] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	GO

	ALTER TABLE [SyncLog].[Holdings]  WITH CHECK ADD  CONSTRAINT [FK_Holdings_Entities] FOREIGN KEY([LogEntityID])
	REFERENCES [SyncLog].[Entities] ([ID])
	GO

	ALTER TABLE [SyncLog].[Holdings] CHECK CONSTRAINT [FK_Holdings_Entities]
	GO

**Comment by smitpatel** [comment]
We need `Holding` class & classes where all its navigations are pointing to.

**Comment by sam-wheat** [comment]
@smitpatel 
Thank you Smit Patel, Holding class is in original post,  Related class attached plus DbContext

	public class JEntity
    {
        public long ID { get; set; }
        public long JobLogID { get; set; }
        public string InvestmentManager { get; set; }
        public string EntityID { get; set; }
        public string AccountType { get; set; }
        public string Dicipline { get; set; }
        public string ManagerName { get; set; }
        public string EntityStatus { get; set; }
        public string EntityName { get; set; }
        public string EntityLegalName { get; set; }
        public int TotalCountPositions { get; set; }
        public string Strategy { get; set; }
        public string Currency { get; set; }
        public string DataSource { get; set; }
        public DateTime EffectiveDate { get; set; }

     
        public virtual JobLog JobLog { get; set; }
        public virtual ICollection<Holding> Holdings { get; set; }
        public virtual ICollection<Entity_LogSummary> Entity_LogSummaries { get; set; }

        public JEntity()
        {
            Holdings = new List<Holding>();
        }
    }
	
	
	
	internal class LoggingDB : DbContext
    {
        public DbSet<JLogAttribute> Attributes { get; set; }
        public DbSet<JEntity> Entities { get; set; }
        public DbSet<Holding> Holdings { get; set; }
        public DbSet<JobLog> JobLogs { get; set; }
        public DbSet<BarraSyncLogDetail> LogDetails { get; set; }
        public DbSet<BarraSyncLogSummary> LogSummaries { get; set; }
        public DbSet<UserAsset> UserAssets { get; set; }

        private const string SchemaName = "SyncLog";

        internal LoggingDB()
        {

        }

        internal LoggingDB(DbContextOptions options) : base(options)
        {
            ChangeTracker.AutoDetectChangesEnabled = false;
            ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            Database.SetCommandTimeout(360);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder mb)
        {
            base.OnModelCreating(mb);

            // Attributes -------------------
            mb.Entity<JLogAttribute>().ToTable("Attributes", SchemaName).HasKey(x => x.ID);
            mb.Entity<JLogAttribute>().HasOne(x => x.LogDetail).WithMany(x => x.Attributes).HasForeignKey(x => x.LogDetailID).OnDelete(DeleteBehavior.Restrict);

            // Entities -------------------
            mb.Entity<JEntity>().ToTable("Entities", SchemaName).HasKey(x => x.ID);
            mb.Entity<JEntity>().HasOne(x => x.JobLog).WithMany(x => x.Entities).HasForeignKey(x => x.JobLogID).OnDelete(DeleteBehavior.Restrict);

            // Entity_LogSummary -------------------
            mb.Entity<Entity_LogSummary>().ToTable("Entity_LogSummaries", SchemaName).HasKey(x => new {x.LogEntityID, x.LogSummaryID });
            mb.Entity<Entity_LogSummary>().HasOne(x => x.Entity).WithMany(x => x.Entity_LogSummaries).HasForeignKey(x => x.LogEntityID).OnDelete(DeleteBehavior.Restrict);
            mb.Entity<Entity_LogSummary>().HasOne(x => x.LogSummary).WithMany(x => x.Entity_LogSummaries).HasForeignKey(x => x.LogSummaryID).OnDelete(DeleteBehavior.Restrict);

            // Holdings -------------------
            mb.Entity<Holding>().ToTable("Holdings", SchemaName).HasKey(x => x.ID);
            mb.Entity<Holding>().HasOne(x => x.JEntity).WithMany(x => x.Holdings).HasForeignKey(x => x.LogEntityID).OnDelete(DeleteBehavior.Restrict);

            // JobLogs
            mb.Entity<JobLog>().ToTable("JobLogs", SchemaName).HasKey(x => x.ID);

            // LogDetail -------------------
            mb.Entity<BarraSyncLogDetail>().ToTable("LogDetails", SchemaName).HasKey(x => x.ID);
            mb.Entity<BarraSyncLogDetail>().HasOne(x => x.LogSummary).WithMany(x => x.LogDetails).HasForeignKey(x => x.LogSummaryID).OnDelete(DeleteBehavior.Restrict);

            // LogSummary -------------------
            mb.Entity<BarraSyncLogSummary>().ToTable("LogSummaries", SchemaName).HasKey(x => x.ID);
            mb.Entity<BarraSyncLogSummary>().HasOne(x => x.JobLog).WithMany(x => x.LogSummaries).HasForeignKey(x => x.JobLogID).OnDelete(DeleteBehavior.Restrict);

            // UserAssets -------------------
            mb.Entity<UserAsset>().ToTable("UserAssets", SchemaName).HasKey(x => x.ID);
            mb.Entity<UserAsset>().HasOne(x => x.LogDetail).WithMany(x => x.UserAssets).HasForeignKey(x => x.LogDetailID).OnDelete(DeleteBehavior.Restrict);
        }
    }

**Comment by smitpatel** [comment]
Can you also share `BarraSyncLogDetail` class? Does it contain any reference to `Holding`?

**Comment by sam-wheat** [comment]
I found the problem.  There was a navigation property left over from a refactor on a class called `BarraSyncLogDetal`.  I do not know why EF is even looking at this table for the simple query I posted and I don't know why it is not putting a dot between table name and ID column.



	public class BarraSyncLogDetail
    {
        public long ID { get; set; }
        public long LogSummaryID { get; set; }
        public string Detail1 { get; set; }
        public string Detail2 { get; set; }
        public string Detail3 { get; set; }
        public string Detail4 { get; set; }
        public string BarraResultCode { get; set; }
        public string BarraResultMsg { get; set; }
        public DateTime BarraEffectiveDate { get; set; }

        public virtual BarraSyncLogSummary LogSummary { get; set; }
        public virtual ICollection<JLogAttribute> Attributes  { get; set; }
        public virtual ICollection<JEntity> Entities { get; set; }
        //public virtual ICollection<Holding> Holdings  { get; set; } // causes error
        public virtual ICollection<UserAsset> UserAssets  { get; set; }

        public BarraSyncLogDetail()
        {
            Attributes = new List<JLogAttribute>();
            Entities = new List<JEntity>();
            //Holdings = new List<Holding>(); // causes error
            UserAssets = new List<UserAsset>();
        }
    }

**Comment by smitpatel** [comment]
>  //public virtual ICollection<Holding> Holdings  { get; set; } // causes error

This navigation property will cause a relationship to be created by convention. And that column is fk property created in `Holding` by convention. Generally if you see some invalid column popping up like that, it is likely some leftover navigation property causing relationship to be created.

**Comment by sam-wheat** [comment]
Does the fact that the tablename and column name are concatenated without a dot raise an alarm?

**Comment by smitpatel** [comment]
@sam-wheat - It is that way because its the FK property. FK property name are generated that way by convention. It is not the case that generated SQL is not delimiting identifiers properly.

**Comment by mauriciogracia** [comment]
I'm having this issue, and have not seen what are my navigation properties that are left over, how can I see more details about this error

https://stackoverflow.com/questions/78257605/entity-framework-core-reports-a-column-that-does-not-exist-in-any-model-nor-the

**Comment by ajcvickers** [comment]
@mauriciogracia Please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by mauriciogracia** [comment]
In the provided link someone has already provided the reason.

I really think that this error could be more precise, and for example mention the name of the navigation property that it was trying to resolve
