### ISSUE TITLE
Unrecognized option '--environment' when using dotnet cli tools

### ISSUE THREAD

**Issue by FunkyLambda** [dotnet/efcore#15026]
As per the following comment by @bricelam:
https://github.com/aspnet/EntityFrameworkCore/issues/7353#issuecomment-270718816

I ran this:
`dotnet ef database update --startup-project ../<my_project> --environment Development`

This gives:
`Unrecognized option '--environment'`

I'm using:
.NET Command Line Tools (2.1.504)

**Comment by bricelam** [comment]
The `--environment` options was removed in version 2.0.0. Use this instead:
``` cmd
set ASPNETCORE_ENVIRONMENT=Development
dotnet ef database update --startup-project ../<my_project>
```

**Comment by MarounMaroun** [comment]
@bricelam Can I read this value from my migration file? Will it be passed as an env variable?

**Comment by bricelam** [comment]
@MarounMaroun Yes, that should work.
