### ISSUE TITLE
Сase insensitivity after adding HasConversion(). Bug or feature?

### ISSUE THREAD

**Issue by ASBrattsev** [dotnet/efcore#15031]
I had to implement the method GetByNames with case-insensitive
```c#
public async Task<List<Model>> GetByNames(CancellationToken cancellationToken, params string[] names)
{
  return await Context.Models.Where(it => names.Contains(it.Name)).ToListAsync(cancellationToken);
}
```
This method didn't work and I changed my configuration class like this:
```c#
public class ModelConfiguration : IEntityTypeConfiguration<Model>
{
  public void Configure(EntityTypeBuilder<Model> builder)
  {
    builder.Property(it =>it.Name).HasConversion(v => v.ToLowerInvariant(), v => v);
    //...
  }
}
```
After that, everything began to work. The data is stored in lower case, but is searched even if the searchText is in upper case.
Is it bug or feature? I'm afraid of behavior changes in the future after upgrading EF Core.

I expected that I would need to change my method as follows:
```c#
public async Task<List<Model>> GetByNames(CancellationToken cancellationToken, params string[] names)
{
  var lowerNames = names.ToLowerInvariant();
  return await Context.Models.Where(it => lowerNames.Contains(it.Name)).ToListAsync(cancellationToken);
}
```

### Further technical details
EF Core version: 2.2.2
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.2.0
Operating system:  Windows 10
IDE: Rider 2018.3

**Comment by ajcvickers** [comment]
@ASBrattsev Essentially, you're using the value converter here to normalize any data going into the database to ensure that it is lower case.  This is a reasonable use of value converters, but it will only work for your case if all the data going into the database either goes through EF (and is hence normalized by the converter) or is inserted by some other mechanism that also ensures that this happens.
