### ISSUE TITLE
The function runtime is unable to start. mscorlib: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified. 

### ISSUE THREAD

**Issue by gabrielbaptista** [dotnet/efcore#15040]
I just upgraded the Entity Framework Core from 2.2.0 to version 2.2.3 in my Azure Functions. After the upgrade, my functions stopped working. I just need to run the function and the problem happens.

Exception message:
The function runtime is unable to start. mscorlib: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified. 

### Further technical details
EF Core version: 2.2.3
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Azure Functions: v1

**Comment by ajcvickers** [comment]
@gabrielbaptista Can you post the csproj file?

**Comment by gabrielbaptista** [comment]
Hello @abpiskunov , you can check it here:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <AzureFunctionsVersion>v1</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
	<Reference Include="System.Data.Linq" />
  </ItemGroup>    
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\models\cloud.prix.mgvnuvem.model\cloud.prix.mgvnuvem.model.csproj" />
    <ProjectReference Include="..\..\sdk\cloud.prix.comuns\cloud.prix.comuns.csproj" />	
	<ProjectReference Include="..\..\models\cloud.prix.iot.model\cloud.prix.iot.model.csproj" />    
    <ProjectReference Include="..\..\models\cloud.prix.model\cloud.prix.model.csproj" />    
    <ProjectReference Include="..\ProcessaInformacoesBalanca\ProcessaInformacoesBalanca.csproj" />	
  </ItemGroup> 
  
  
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by ajcvickers** [comment]
@gabrielbaptista Thanks for the additional info. I don't have much experience with Azure Functions, but my understanding is that they are loaded into a runtime that may already include references to some versions of packages. As such, it is not always possible to use a new version of a package until the runtime has been updated with that version. However, I'm not 100% sure on this and will follow up with some other people here. You might also want to reach out to the Functions team and see what their expectations are in this regard.

**Comment by gabrielbaptista** [comment]
Hi @ajcvickers . That is exactly what I thought. To solve it, I kept using E.F.Core 2.2.0, but I am really concerned about when I will have the opportunity to update, since the dependencies are not in my control.

**Comment by VladislavAntonyuk** [comment]
you have to clean your packages folder  on disk and restore them again

**Comment by gabrielbaptista** [comment]
Yes, we have.

**Comment by paulbatum** [comment]
The ability of Azure Functions V1 to load dependencies without assembly load issues is quite limited. The information shared in this thread is not enough for me to comment on exactly why 2.2.3 is not loading. I made a V1 function app and I was able at least get it to load types from the Microsoft.EntityFrameworkCore.SqlServer 2.2.3 assembly (see below output). You might need to make a simplified, shareable repro in order to determine exactly what is going wrong here.

That said, our ability to update functions V1 to address issues like this is extremely limited, so working on a standalone repro might not be the best use of your time.
 
Very significant changes were made in terms of how dependencies are loaded in Functions V2. These changes addressed many different cases where users were unable to use a certain library in V1. If you want to be able to keep taking EF updates into your function app then I strongly recommend you upgrade to V2. A good starting point is [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#migrating-from-1x-to-2x).

Example output mentioned above - note the line towards the bottom where the assembly name is emitted:
```
[4/2/2019 6:26:39 PM] Starting Host (HostId=pbatumsurfaceb-200862808, Version=1.0.12299.0, InstanceId=a06d7626-4a97-4d96-9104-0346a609a33d, ProcessId=55444, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
Listening on http://localhost:7071/
Hit CTRL-C to exit...
[4/2/2019 6:26:39 PM] Loaded custom extension 'BotFrameworkConfiguration'
[4/2/2019 6:26:39 PM] Loaded custom extension 'SendGridConfiguration'
[4/2/2019 6:26:39 PM] Loaded custom extension 'EventGridExtensionConfig'
[4/2/2019 6:26:40 PM] Host keys are loaded.
[4/2/2019 6:26:40 PM] registered EventGrid Endpoint = http://localhost:7071/admin/extensions/EventGridExtensionConfig
[4/2/2019 6:26:40 PM] Generating 1 job function(s)
[4/2/2019 6:26:40 PM] Found the following functions:
[4/2/2019 6:26:40 PM] FunctionApp6.Function1.Run
[4/2/2019 6:26:40 PM]
[4/2/2019 6:26:40 PM] Host initialized (1609ms)
[4/2/2019 6:26:41 PM] Host started (1665ms)
[4/2/2019 6:26:41 PM] Job host started
[4/2/2019 6:26:41 PM] Host lock lease acquired by instance ID '000000000000000000000000B4288DB1'.


Http Functions:

        Function1: http://localhost:7071/api/Function1

Debugger listening on [::]:5858
[4/2/2019 6:26:46 PM] Function started (Id=33be5202-377f-41d2-975f-a75fad7432fc)
[4/2/2019 6:26:47 PM] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=33be5202-377f-41d2-975f-a75fad7432fc)
[4/2/2019 6:26:47 PM] Microsoft.EntityFrameworkCore.SqlServerRetryingExecutionStrategy, Microsoft.EntityFrameworkCore.SqlServer, Version=2.2.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
[4/2/2019 6:26:47 PM] C# HTTP trigger function processed a request.
[4/2/2019 6:26:47 PM] Function completed (Success, Id=33be5202-377f-41d2-975f-a75fad7432fc, Duration=478ms)
[4/2/2019 6:26:47 PM] Executed 'Function1' (Succeeded, Id=33be5202-377f-41d2-975f-a75fad7432fc)
```

**Comment by ajcvickers** [comment]
Thanks @paulbatum for the detailed explanation.

Since this is an issue specific to Azure Functions V1 which will be improved greatly in V2, closing as external.
