### ISSUE TITLE
Generated SQL with 2012 syntax on 2008R2 database

### ISSUE THREAD

**Issue by ovidiutudorache** [dotnet/efcore#1505]
The edmx is created using a 2012 SQL database.
Then I execute queries on a 2008R2 database, the generated SQL contains OFFSET and FETCH NEXT instructions that are supported on SQL 2012.
Tested on EF 6.1.2
This does not happen on EF 6.1.1.

**Comment by ErikEJ** [comment]
Change the providermanifest token in the EDMX - see my blog post here: http://erikej.blogspot.dk/2014/12/a-breaking-change-in-entity-framework.html

**Comment by ovidiutudorache** [comment]
Thank you.

Ovidiu Tudorache
   CTO
   Zurply
   P: +40 748 128 041
   E: ovidiu.tudorache@zurply.com

2015-01-30 14:07 GMT+02:00 Erik Ejlskov Jensen <notifications@github.com>:
