### ISSUE TITLE
Cosmos: Using Sytem.Configuration.ConfigurationManager, Not compatible with Xamarin.Android

### ISSUE THREAD

**Issue by mbordogna** [dotnet/efcore#15053]
When deploying to the Android emulator...
03-17 20:55:28.057 D/Mono    ( 5436): Assembly Loader probing location: 'System.Configuration.ConfigurationManager'.
03-17 20:55:28.057 F/monodroid-assembly( 5436): Could not load assembly 'System.Configuration.ConfigurationManager' during startup registration.
03-17 20:55:28.057 F/monodroid-assembly( 5436): This might be due to an invalid debug installation.
03-17 20:55:28.057 F/monodroid-assembly( 5436): A common cause is to 'adb install' the app directly instead of doing from the IDE.

The only remaining reference I have is coming from Microsoft.Azure.Comos.Direct's 
Depenency on System.Configuration.ConfigurationManager

### Steps to reproduce
Include EFCore.Cosmos Nuget in NetStandard Xamarin root project.
Start emulator, Try to deploy

### Further technical details
EF Core version: 3.19153.1
Database Provider:   Microsoft.EntityFrameworkCore.Cosmos
Operating system: Win10 
IDE:  Visual Studio 2017 15.9
Android Emulator x86 Oreo

Resolution Options: 
Replace ConfigurationManager with cross platform Supported Configuration implementation, or fix ConfigurationManager to support android.

**Comment by ajcvickers** [comment]
Moved to https://github.com/Azure/azure-cosmos-dotnet-v3/issues/83 since this dependency is brought in by the Cosmos SDK.
