### ISSUE TITLE
Proposal: SqlFragmenExpression accepting a formattable string as a ctor argument

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/efcore#15056]
At this moment `SqlFragmentExpression` accepts only a string which covers most use cases, but the case with string interpolation. This leads to nasty errors when an argument format depends on the current culture. Yep, this can be fixed on the provider size by `FormattableString.Invariant` or via some `SqlFormattableFragmentExpression`, but wouldn't it be better to introduce this on the EF Core side and make life easier for provider maintainers?

```
public SqlFragmentExpression(FormattableString sql)
    : this(FormattableString.Invariant(sql)) { }
```

/cc @roji @austindrenski

**Comment by ajcvickers** [comment]
@YohDeadfall The use of FormattableString in other APIs is to allow parameters to _not_ be in the resulting string at all, but instead to be used as database parameters. This is very different from the use suggested here, and is not an API approach that we want to take. (It would have some of the issues of the other APIs--such as it being hard to determine when the string overload starts being used, but without any of the benefits.)

Provider code must generate string literals such that they are as expected by the database. In practice this means never using the current culture, which in turn usually means that it is more convenient to use string.Format rather than string interpolation. That's why we rarely use interpolation inside EF Core unless it's only for values that are already strings.

**Comment by YohDeadfall** [comment]
@ajcvickers I'm talking about things which happens in providers and which should be used internally, not for parameter substitution. For example take a look at npgsql/Npgsql.EntityFrameworkCore.PostgreSQL#847.

`string.Format` perfectly suits the goal, but not sure about it usability. So I would like to hear other provider developers too since I'm not an expert and only fix some EF related code (:

**Comment by ajcvickers** [comment]
@YohDeadfall I understand that. We don't want to be in the business of doing this.

**Comment by roji** [comment]
One more thing to add - our usage of SqlFragmentExpression here may be a bit questionable, it's meant mainly as a shortcut to avoid creating a new expression type. It could be argued that once a complex fragment needs to be generated (as here), providers should in any case just have a new expression type and render that as usual. Not really sure, just adding some thoughts.

**Comment by smitpatel** [comment]
Can you guys elaborate, how would you like to render this new ctor or new expression type when printing out SQL?

**Comment by YohDeadfall** [comment]
Like in [this PR](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/852), but without explicit call to `FormattableString.Invariant`:

```csharp
interval = new SqlFragmentExpression($"INTERVAL '{amountToAdd} {datePart}'");
// instead of
interval = new SqlFragmentExpression(FormattableString.Invariant($"INTERVAL '{amountToAdd} {datePart}'"));
```

**Comment by smitpatel** [comment]
@YohDeadfall - My question is how would you print it out in SQL. Suppose you added `SqlFormattableFragmentExpression` as custom expression. When you are visiting it in DefaultQuerySqlGenerator, what would it output to SQL?

**Comment by YohDeadfall** [comment]
It should work as `SqlFragmentExpression`. Nothing more than implementation of this proposal on our side.

```csharp 
public class SqlFormattableFragmentExpression : SqlFragmentExpression
{
    public SqlFormattableFragmentExpression(FormattableString sql)
        : base(FormattableString.Invariant(sql)) { }
}
```

**Comment by smitpatel** [comment]
If that's the case then, neither option is good. Custom expression type is too much work for seemingly minor task. And adding new ctor has it's own issue. (see https://github.com/aspnet/EntityFrameworkCore/issues/10996 for more details).

Best practice would be to just avoid interpolated string. But if you are insistent on using it then just define an extension method which would generate SqlFragmentExpression with culture invariant string.
