### ISSUE TITLE
User Secrets with Update-Database command

### ISSUE THREAD

**Issue by JwanKhalaf** [dotnet/efcore#15051]
I have a .NET Core application that is [available on GitHub](https://github.com/JwanKhalaf/Bejebeje.Identity/tree/feature/adding-identity-server-4). It makes use of User Secrets. When I check out the application, define my local User Secret variables and run `Update-Database` in the Package Manager Console, I get the following error:

![image](https://user-images.githubusercontent.com/42877376/54489304-c6e04880-48a2-11e9-9762-fb038672cea7.png)

Do EF Core migrations not work with User Secrets? What am I doing wrong?

### Further technical details
```
<ItemGroup>
  <PackageReference Include="IdentityServer4" Version="2.3.2" />
  <PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.3.0" />
  <PackageReference Include="Microsoft.AspNetCore.App" />
  <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.2.0" />
  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.0" />

  <PackageReference Include="Serilog" Version="2.8.0" />
  <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
  <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
  <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
</ItemGroup>
```
Database Provider: Postgres via Npgsql
Operating system: Windows 10 x64
IDE: Visual Studio 2019 Preview (version 16, Preview 4.2)

**Comment by ajcvickers** [comment]
@JwanKhalaf Please post the output from running with the "verbose" option.

**Comment by JwanKhalaf** [comment]
@ajcvickers it turns out, I had to set the `ASPNETCORE_ENVIRONMENT` variable first.

For anyone reading this in the future, in order to set `ASPNETCORE_ENVIRONMENT` from within Package Manager Console, you run the following command.

```
$env:ASPNETCORE_ENVIRONMENT='Production'
```

Obviously, you would replace `Production` with whatever environment you want to target (e.g. `Develop`).

I'll close the issue.
