### ISSUE TITLE
Request for better parameter infromation in CommandExecuted log output

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#15085]
I wanted to turn EF Core's CommandExecuted log into real SQL, using the parameter information provoded when EnableSensitiveDataLogging is turn on. I have done this (see [this article](https://www.thereformedprogrammer.net/decoding-entity-framework-core-logs-into-runnable-sql/)), but I found I couldn't get enough information to accurately define what type/value some types had. @ErikEJ suggested I talked to you to see if there is any way around this.

My article goes through this in detail, but the limitations were:
- I couldn't detect if a string was set to NULL or an empty string.
- I couldn't detect the type of various parameters, such as GUID, DataTime etc. to wrap them in string.

See code example below:

I am not seeing a exception.

### Steps to reproduce
I have a class with most (all?) types mapped to the database

```c#
public class AllTypesEntity
{
    public int Id { get; private set; }
    public bool MyBool { get; private set; } = true;
    public bool? MyBoolNullable { get; private set; } = null;
    public int MyInt { get; private set; } = 1234;
    public int? MyIntNullable { get; private set; } = null;
    public double MyDouble { get; private set; } = 5678.9012;
    public Decimal MyDecimal { get; private set; } = 3456.789m;
    public Guid MyGuid { get;  set; }
    public Guid? MyGuidNullable { get; private set; } = null;

    public string MyString { get; private set; } = "string with ' in it";
    public string MyStringNull { get; private set; } = null;
    public string MyStringEmptyString { get; private set; } = string.Empty;

    [Required]
    [Column(TypeName = "varchar(123)")]
    public string MyAnsiNonNullString { get; private set; } = "ascii only";

    public DateTime MyDateTime { get; set; }
    public DateTime? MyDateTimeNullable { get; private set; } = null;
    public TimeSpan MyTimeSpan { get;  set; }
    public DateTimeOffset MyDateTimeOffset { get;  set; }
    public byte[] MyByteArray { get;  set; }
}
```

The log output for an add looks like this:

```SQL
Executed DbCommand (46ms) [Parameters=[@p0='ascii only' (Nullable = false) (Size = 123) (DbType = AnsiString), @p1='True', @p2='', @p3='0x010203' (Size = 8000), @p4='2000-01-02T00:00:00', @p5='' (DbType = DateTime2), @p6='2004-05-06T00:00:00.0000000+01:00', @p7='3456.789', @p8='5678.9012', @p9='58f13f04-d466-4cf1-a07f-2843031902b8', @p10='' (DbType = Guid), @p11='1234', @p12='' (DbType = Int32), @p13='string with ' in it' (Size = 4000), @p14='' (Size = 4000), @p15='' (Size = 4000), @p16='04:05:06'], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AllTypesEntities] ([MyAnsiNonNullString], [MyBool], [MyBoolNullable], [MyByteArray], [MyDateTime], [MyDateTimeNullable], [MyDateTimeOffset], [MyDecimal], [MyDouble], [MyGuid], [MyGuidNullable], [MyInt], [MyIntNullable], [MyString], [MyStringEmptyString], [MyStringNull], [MyTimeSpan])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16);
SELECT [Id]
FROM [AllTypesEntities]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
```

My decode method can be found [here](https://github.com/JonPSmith/EfCore.TestSupport/blob/master/TestSupport/EfHelpers/Internal/EfCoreLogDecoder.cs). In that I make some compromise decisions (like wrapping most types in '') that kinda works.

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.9.6)

**Comment by ErikEJ** [comment]
If all DbTypes were specified + NULL Vs Empty string, assume it would solve most of your issues?

**Comment by JonPSmith** [comment]
@ErikEJ, yes that would solve a problem that is a) impossible to detect at the moment and b) likely to happen a lot.

I do worry about numbers being presented as strings, e.g. '123' instead of 123, but it seems to work in SQL Server. Any thoughts on that?

**Comment by ErikEJ** [comment]
But if you know the type you will know if you should remove the '' or not

**Comment by JonPSmith** [comment]
Sorry, didn't read your reply properly - I focused on the NULL bit!

Yep, if the DbType was always provided that would fix the other problems completely.

**Comment by ajcvickers** [comment]
@JonPSmith Wouldn't `DiagnosticSource` be a better option here? It gets all the events that go to logging, but instead of being focused on textural logging it provides all the raw data for the event. This includes all the parameters and their values/facets.

The `ILogger` based logging from ASP.NET has some support for structural logging, but it's not great because getting the output correct often involves not passing raw arguments to logging, but instead converting them to strings first.

**Comment by JonPSmith** [comment]
@ajcvickers, sounds great but there isn't much documentation on how to set it up. How would I create/inject a `IDiagnosticsLogger` or an  `DiagnosticSource` listener when I create a DbContext?

**Comment by ajcvickers** [comment]
@JonPSmith `DiagnosticSource` is part of the wider .NET ecosystem and isn't D.I. enabled. Unfortunately, the usage is quite strange. There is an example in #12024, but you should also be able to find guidance online since its not EF specific.

**Comment by JonPSmith** [comment]
@ajcvickers . I think I'll have to give that a miss as I want to have the capability in my [EfCore.TestSupport](https://github.com/JonPSmith/EfCore.TestSupport) library. I can't think of a way to make the DiagnosticSource localised to each DbContext in a unit test. If you know a way to do that then let me know, otherwise I'll keep the version based on the logging information.

**Comment by ajcvickers** [comment]
@JonPSmith Typically by filtering based on the context instance in the listener, just like would have been the case for EF6 interceptors.

**Comment by ajcvickers** [comment]
@JonPSmith We discussed this as a team and agreed that `DiagnosticSource` is the way to go for this kind of thing. It would be great if you could provide detailed feedback on whether or not you could make this work and if not what the issues were.

**Comment by JonPSmith** [comment]
Hi @ajcvickers,

Thanks for the feedback. I want to try that but I'm deep in a contract at the moment (I'm used EF Core of course!) and I won't get to it for quite a while (months??). But I do plan to have a go and I will let you know.

You can close this issue for now. If I have any issues when I try this I will reopen it later.

**Comment by ajcvickers** [comment]
Thanks @JonPSmith
