### ISSUE TITLE
Renaming operation causes issue due to dependency 

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#15084]
Hi,

We are planning to support Code First in IBM Entity Framework Core Provider. We have use cases around Renaming Table Or Column name where if any dependency is there on reamed table or column it throws error.  for example, column is part of  Composite key and we want to change one of the column name, generated migration class do not generate code to drop primary key first and then rename column followed by creating the primary key.

It's just one example, but we have many use cases in this area. 
Another example is we want to rename table which has foreign key relation and index. Now with EF Core it generates Up method with drop pk, drop fk , rename table, rename index, create pk, create fk etc. In this due to index dependency it's failing.

Please note server allows to rename table or column, but dependency should be handled first.

So if we handle this we need to perform below steps:

Figure out whether table has PK or FK, Index
if it has then gather all the required data like constraint name, parent table, parent table_column name etc. incase of composite key we need to have list of columns.
then drop the keys ,index etc
rename table
then add keys,index back using data collected in step 2.
It's going to be more effort just to rename table
Our question is:

What is the easiest way to achieve it.
Why doesn't MS EF Core generate drop and create keys\indexes operation along with rename operation ? in this way it would have been more easy for providers to handle..

**Comment by ajcvickers** [comment]
@bricelam to follow up.

**Comment by bricelam** [comment]
@archanasoni What I'm hearing is that you can't rename tables and columns in DB2 without rebuilding referencing primary keys and foreign key constraints. Is that correct?

In SQL Server, we have to rebuild indexes when a column type is narrowed. Here is [the code](https://github.com/aspnet/EntityFrameworkCore/blob/v2.2.2/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L272-L326) that does that. The same issue exists for primary keys and foreign key constraints (#13178) but we don't currently rebuild those.

Issue #329 is about creating helper methods that providers can leverage to rebuild parts of the schema when sending a simple ALTER statement isn't enough. Today, users are expected to handle these cases by manually adding the rebuild steps in the `Up` and `Down` methods of their migrations.

**Comment by bricelam** [comment]
> Why doesn't MS EF Core generate drop and create keys\indexes operation along with rename operation?

In our experience, most databases don't require dropping these. The rename operations typically maintain any existing references to the tables and columns.

**Comment by archanasoni** [comment]
okay but DB2 requires to rebuild the dependencies, m not sure about other DBs.  Will fix for #329 be enough or helpful in our scenario ?  I could see it's  opened since 2014.. any idea by when will it get fixed ?

**Comment by ajcvickers** [comment]
@archanasoni That issue is in the Backlog milestone. This means that it is not going to happen for the 3.0 release. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

This should not block your provider. For example, the SQLite provider also needs table rebuilds for a lot of migrations, and SQL Server sometimes needs them. The intention of migrations is not to always be able to scaffold everything. Sometimes migrations will need hand edits and workarounds for things not supported natively bu the provider.
