### ISSUE TITLE
TPH disables Required Attribute

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/efcore#15099]
When using TPH all columns become nullable and the Required attribute becomes completely useless. I'm not sure if everyone is aware of that and if that is "to be expected".

I'm aware that it can't be verified within the DB but one might expect this to be evaluated by the EF instead whenever the DB can't do it.

```csharp
public abstract class A
{
   public Guid Id { get; set; }
}

public class A1 : A
{
   [Required]
   public int? I { get; set; }
}

public class A2 : A { }

/--------------------------------/

public DbSet<A> As { get; set; }
public DbSet<A1> A1s { get; set; }
public DbSet<A2> A2s { get; set; }

/--------------------------------/

context.A1s.Add(new A1 {I = null});
```

| Id |Discriminator|I|
|-|-|-|
|642CB9AA-9BD6-4E75-B6C8-08D6ADEA4347|A1|NULL|

Validation of the `Required` Attribute would work when you remove `public DbSet<A> As { get; set; }` because this removes TBH and each entity gets its own table.

Of course there are more things that would not throw an exception when using TPH even though it should.

edit: _at least_ at the creation of the migration script it should give me a warning that the `Required` attribute is going to be ignored.

BR

**Comment by ajcvickers** [comment]
@matthiaslischka EF Core doesn't do any validation of your entities beyond what is necessary for it to function. This is because experience has shown that validation usually happens first in the U.I., then in the service/application, and most times anything EF would do is redundant and just adds overhead. So the work to support validation is not something we plan to invest in for EF Core.

**Comment by matthiaslischka** [comment]
Like I said. It should AT LEAST add a warning when creating the Migrations that the `Require` attribute is going to be ignored. It's strange to me that the expected behavior changes extremely weather you have TBH or not.

**Comment by ajcvickers** [comment]
@matthiaslischka It's not being ignored. It's still configured as required in the EF model. The column on the other hand must be nullable to support the way TPH works. That doesn't make the property in the model nullable.

**Comment by matthiaslischka** [comment]
It's going to be ignored on the DB (of course) - what is not necessarily what you would expect and why you put it on the property.
It might event change when you had just one class in the table at first but add a second later on.
I still think that at least a warning that the `Required` property will not behave (anymore) like you might expect would be nice.

**Comment by ajcvickers** [comment]
@matthiaslischka I don't think this warrants a warning, but maybe the docs for TPH need to be more explicit about this consequence. I'll reopen to get the opinion of others on the team.

**Comment by ajcvickers** [comment]
Notes from triage: see #2595, and also https://github.com/aspnet/EntityFramework.Docs/pull/1386.
