### ISSUE TITLE
Make PropertyBuilder.IsRowVersion() Relational

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#15094]
Even though the configuration performed by `IsRowVersion` is not relational-specific, the name and the common usage scenario is.

**Comment by ajcvickers** [comment]
@AndriySvyryd Any more data than when we discussed this before? See https://github.com/aspnet/EntityFrameworkCore/pull/6408#issuecomment-242519753 :trollface:

**Comment by AndriySvyryd** [comment]
@ajcvickers No, previous discussions have been GC'ed from my memory.

**Comment by ajcvickers** [comment]
You should have maintained a reference. ;-)

**Comment by ajcvickers** [comment]
Triage: TL;DR no change.

Before the information gets collected again:
* Yes, it's SQL Server specific, but we have the API, and we had it in EF6, so inventing something new has usability cost
* All it really means is, "use this property for automatic optimistic concurrency". That might be offline lock, or something specific to the provider.
  * This is similar to how `ValueGeneratedOnAdd` doesn't specify how this is achieved, just that it should happen.
