### ISSUE TITLE
Query: Server Eval Count of GroupBy 

### ISSUE THREAD

**Issue by MyJimmyZhou** [dotnet/efcore#15097]
**code:**
``` csharp
        public int Count()
        {
            return webUserDao.DbSet().Where(u => u.CreateTime < DateTime.Now).GroupBy(g => g.UserType).Count();
        }
```

**Issues:**
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy([u].UserType, [u])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.

**Comment by MaklaCof** [comment]
Same problem here:
```
var group = this.Set<DbMasterUser>().GroupBy(t => t.LanguageId).ToArray();
```

> The LINQ expression 'GroupBy([t].LanguageId, [t])' could not be translated and will be evaluated locally.

with
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.3" />
```

**Comment by smitpatel** [comment]
@maklaCof - Your groupby query lacks aggregate operator. It can never be translated to SQL GROUP BY clause.

**Comment by smitpatel** [comment]
@MyJimmyZhou - Essentially you are counting number of groups. You can just do Distinct on grouping key column and Count on rather than using GroupBy.

**Comment by smitpatel** [comment]
Generated invalid SQL
```SQL
SELECT COUNT(*)
FROM (
    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
    FROM [Orders] AS [o]
    GROUP BY [o].[CustomerID]
) AS [t]
```

**Comment by smitpatel** [comment]
Work-around
```C#
public int Count()
        {
            return webUserDao.DbSet().Where(u => u.CreateTime < DateTime.Now).GroupBy(g => g.UserType).Select(g => g.Key).Count();
        }
```

**Comment by smitpatel** [comment]
Operators covered here
- Count
- LongCount
- Any
- All

**Comment by smitpatel** [comment]
Pulling this in 5.0
