### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#15109]
From VS Feedback:

sometimes when we add a new migration the migration file is getting generated but with empty class

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by neethupvijayan** [comment]
when we remove a migration from solution explorer without using remove migration command in package manager console and again adding a new migration for the same migration class is getting generated but with empty data.. Here the attachment
[Employee.zip](https://github.com/aspnet/EntityFrameworkCore/files/2995245/Employee.zip)

**Comment by ajcvickers** [comment]
@neethupvijayan This project does not build, so I cannot run the code. It references "..\WebAdmin\EntityFramework.csproj" which is not included.

**Comment by neethupvijayan** [comment]
@ajcvickers Please check with this
[Student.zip](https://github.com/aspnet/EntityFrameworkCore/files/3006652/Student.zip)

**Comment by neethupvijayan** [comment]
@ajcvickers 
[Employee.zip](https://github.com/aspnet/EntityFrameworkCore/files/3006676/Employee.zip)

**Comment by ajcvickers** [comment]
@neethupvijayan Still doesn't build for me, but looking again I am pretty sure this is by-design. When removing a migration it is important to use the command to do so. This is because removing the migration also updates the model snapshot. Without doing this EF tooling will not detect the model differences again.
