### ISSUE TITLE
Need more information in Log Warning

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/efcore#15101]
I get warnings in my log such as 
`The Include operation for navigation '[a].Channel' is unnecessary`
obviously the text in side the single quotes is relevant to my code not yours. 
It would be helpful if the log message also included some information such as the request URL or action method so it is possible to identify where in the code base this include is.

Thanks
Mark

**Comment by ajcvickers** [comment]
Notes from triage: filed #15127 which should enable this.

This doesn't include the request or action method, which is ASP.NET specific, but it should be possibly to instrument such a method so that it also logs, allowing correlation.
