### ISSUE TITLE
Internal API usage and extensibility requirements for third party tooling scenarios 

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#15108]
I am creating this placeholder issue initially for @ErikEJ. I am talking to him at the moment and hearing about the internal APIs his tools use, workarounds for emulating what dotnet ef does to run user code but to do other operations, parsing of the debug model view, etc. 

Hoping that we can identify things that we can expose publicly to prevent tools from having to reinvent the wheel as much as possible.

**Comment by ajcvickers** [comment]
Putting this in discussion for now. @ErikEJ We're not going to be able to do a fully public design surface area yet, although that could happen in the future. However, we can certainly look at making some useful things public on a pragmatic basis. We look forward to hearing from you as to which pieces might make sense to go public here.

**Comment by ErikEJ** [comment]
Thanks Arthur, I am fine with the current state of affairs and have a good path for moving to 3.0
