### ISSUE TITLE
Issue (Invalid column name 'has_filter') while scaffolding from SQL Server 2005

### ISSUE THREAD

**Issue by iamsourabh-in** [dotnet/efcore#15116]
Error Number:207,State:1,Class:16
Invalid column name 'has_filter'.
Invalid column name 'filter_definition'

I am currently using SQL Server 2005, and ASP.NET core 2.2.

I had a look at the scaffolding source code which is trying to fetch the details of the table.

See below-

`SELECT
    SCHEMA_NAME([t].[schema_id]) AS [table_schema],
    [t].[name] AS [table_name],
    [i].[name] AS [index_name],
    [i].[type_desc],
    [i].[is_primary_key],
    [i].[is_unique_constraint],
    [i].[is_unique],
    [i].[has_filter],
    [i].[filter_definition],
    COL_NAME([ic].[object_id], [ic].[column_id]) AS [column_name]
FROM [sys].[indexes] AS [i]
JOIN [sys].[tables] AS [t] ON [i].[object_id] = [t].[object_id]
JOIN [sys].[index_columns] AS [ic] ON [i].[object_id] = [ic].[object_id] AND [i].[index_id] = [ic].[index_id]`

Is this a bug which will be resolved in the future or should I expect this never to come for SqlServer 2005 ?

Thanks

**Comment by ErikEJ** [comment]
SQL Server 2005 is not supported by EF Core

**Comment by ajcvickers** [comment]
@codeRusty As @ErikEJ says, we don't support SQL Server 2005, which means that we will sometimes use features of SQL Server that were only introduced in more recent editions.
