### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#15110]
From VS Feedback

When we change something in more than one domain and try to add migration together for all the domain changes its not taking the changes in database  so we forced to  delete the all added migrations  and  to create the migration as initial

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by neethupvijayan** [comment]
[Student1.zip](https://github.com/aspnet/EntityFrameworkCore/files/2995185/Student1.zip)
[StudentDb.zip](https://github.com/aspnet/EntityFrameworkCore/files/2995191/StudentDb.zip)
when trying to make a property in a domain to be null ,migration is getting generated, but after updating database that field in the table kept unchanged
Above we attaching the project solution zip and database MySQL zip

**Comment by ajcvickers** [comment]
@neethupvijayan This project does not build, so I cannot run the code. It references "..\Student.Domain\Student.Domain.csproj" which is not included.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
