### ISSUE TITLE
Add support for readonly in-memory SQLite databases

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/efcore#15118]
SQLite has support for simultaneous connections to the same in-memory database (see `In-memory Databases And Shared Cache` at https://www.sqlite.org/inmemorydb.html). On the other hand, in-memory databases are always opened [with the readwrite flag](https://github.com/aspnet/EntityFrameworkCore/blob/9afed5819d71ab1751741a591d81aa31d179c60b/src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs#L189)

In my application, there are two connections to the same database, one read/write, one readonly and during development the database is in-memory instead of running against an actual file. By having readonly connections, I would be able to detect earlier when I chose the wrong connection before putting the code in production.

**Comment by ajcvickers** [comment]
Brice to take a look at this, but it may require breaking changes and so could very well not get done for 3.0

**Comment by bricelam** [comment]
As far as I can tell, this isn’t possible in SQLite. The docs lead me to believe that the read/write/create flags only apply to files, and they get ignored on in-memory databases.

Let me experiment a bit with the native APIs to confirm...

**Comment by bricelam** [comment]
Confirmed. The flags don't affect in-memory databases.

``` csharp
using System.Diagnostics;

using static SQLitePCL.raw;

class Program
{
    static void Main()
    {
        SQLitePCL.Batteries_V2.Init();

        var rc = sqlite3_open_v2(
            "file:test",
            out var db1,
            SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE |
            SQLITE_OPEN_URI |
            SQLITE_OPEN_MEMORY |
            SQLITE_OPEN_SHAREDCACHE,
            vfs: null);
        Debug.Assert(rc == SQLITE_OK);

        rc = sqlite3_exec(db1, "CREATE TABLE A(X)");
        Debug.Assert(rc == SQLITE_OK);

        rc = sqlite3_open_v2(
            "file:test",
            out var db2,
            SQLITE_OPEN_READONLY |
            SQLITE_OPEN_URI |
            SQLITE_OPEN_MEMORY |
            SQLITE_OPEN_SHAREDCACHE,
            vfs: null);
        Debug.Assert(rc == SQLITE_OK);

        rc = sqlite3_exec(db2, "INSERT INTO A VALUES (1)");
        Debug.Assert(rc == SQLITE_OK);
    }
}
```

**Comment by Tragetaschen** [comment]
Shame… Well, more work for the PR review then...

Thanks for looking into it, though!
