### ISSUE TITLE
Dynamic Entities with Dynamic Navigation Properties that fit with NoSQL Graph db providers

### ISSUE THREAD

**Issue by jersiovic** [dotnet/efcore#1513]
Do you have evaluated the idea of supporting dynamic types for entities with navigation properties to other entities that fit with Graph dbs or hibrid dbs(Document+Graph). Nodes of those dbs are schema free and each node can be connected to other different nodes.
So it would be great EF will allow us to use dynamic navigation properties instead of use the current ones we define in the class. Those navigation properties will be set per object instead of per type, in that way we could harness the real power of NoSql dbs

This request is related with this other issue in Orchard CMS Github where we discuss about how can fit EF7 with the dynamic schema Orchard uses:  https://github.com/OrchardCMS/Brochard/issues/12

**Comment by jersiovic** [comment]
Hibernate OGM (http://hibernate.org/ogm) does support from time ago schema free data.
https://hibernate.atlassian.net/browse/OGM-470
Will also  EF7 support it?

**Comment by divega** [comment]
Looking at items that have been sitting on my plate for some time I found this one that I think at this stage either belongs in the backlog or possibly closed if we believed it is something we are never going to do, so clearing up milestone. 

The main point is obviously to have truly schema-less models, where each instance can have its own shape, or at least some more limited but still useful version of that, such as enabling "complex type" properties that are schema-less which has been supported by other O/RMs for a long time.

OrchardCMS/Brochard#12 is an interesting read too, although it is clear Orchard does not need EF7 to support this feature.

**Comment by rowanmiller** [comment]
@divega to open a new issue capturing the expand object feature and put on backlog

**Comment by divega** [comment]
We won't be supporting anything like this for now but I have captured some information on dynamic models for our backlog in #2282. I am going to close this item in favor of that one.
