### ISSUE TITLE
Keep DbContext constructor that takes service provider and options

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1514]
We use this extensively in our tests, in particular for decoupling the service provider setup from EF provider configuration. We also don't always use a derived context. It might be possible to create some ugly code with AddDbContext and always using a derived context that would allow us to change our test code. I started to look at this, but @divega and @AndriySvyryd suggested that we should reconsider the decision first.

**Comment by rowanmiller** [comment]
Keep it
