### ISSUE TITLE
Unexpected behavior when loading an entity with an ownership relation directly through navigation properties

### ISSUE THREAD

**Issue by ilyvion** [dotnet/efcore#15150]
I'm having odd and/or unexpected behaviors when loading an entity with an ownership relation through navigation properties or through the `EntityEntry<>.Query()` method, and I need to know if this behavior is on purpose or if I've discovered a bug.

I have an entity `Item`, which has a property `Color` of the type `HexRgbColor`. This property has been configured to be owned by `Item`. (`itemBuilder.OwnsOne(i => i.Color)`)

When loaded directly by a query (e.g. `context.Items.Where(i => i.Id == 1)`), the `Color` property loads just fine, and everybody's happy.

When loaded by an `.Include()` from another entity (e.g. `context.Occurrences.Where(o => o.OrderId == 1).Include(o => o.Item)` or `context.Entry(order).Collection(ord => ord.Occurrences).Query().Include(occ => occ.Item)`), the `Color` property loads just fine, and everybody's happy.

**HOWEVER**, if you try to skip the middle man and go straight for the item (e.g. `context.Occurrences.Where(o => o.OrderId == 1).Select(o => o.Item)` or `context.Entry(order).Collection(ord => ord.Occurrences).Query().Select(occ => occ.Item)`), the `Color` property is not loaded, and will be set to its default value.

What? Why? And more to the point: I have not found any way of loading that owned property without also having to go through either a direct query of the item (which defeats the point, since I don't know the item's ID at the time of the query) or by having to load its "parent" entity as well.

### Steps to reproduce

I created a working example in LINQPad using the InMemoryDatabase provider, although I discovered this issue when using my regular SQL database provider, so it's obviously an EF issue, not a provider issue. I've put the whole file up [in a gist](https://gist.github.com/alexschrod/22b7491fc225a1059df844505160160e).

Should be possible to just open and run directly in LINQPad, although it shouldn't be too hard to put it all in a cs file and run in a true `dotnet` manner, if LINQPad doesn't meet your requirements.

### Further technical details
EF Core version: 2.2.2
Database Provider: Pomelo.EntityFrameworkCore.MySql, but I get same behavior with Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 Pro 64-bit
IDE: Visual Studio Code 1.32.3

**Comment by ajcvickers** [comment]
Note for triage: verified that the cases reported here are duplicates of #13546
