### ISSUE TITLE
DbUpdateConcurrencyException when updating DbSet with child class in 3.0.0-preview3.19153.1

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/efcore#15153]
Describe what is not working as expected.

I am updating an class Link along with it's child property SubLink.  I get an error.  I can perform this operation on classes with simpler relationships.  I have self-references classes, one-to-many relationships, and many-to-many relationships.  I can add new rows without a problem.  It is only when I try to update an existing row, along with it's child class.

If you are seeing an exception, include the full exceptions details (message and stack trace).
`DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.`

```
Exception message:
Stack trace:
[EntityFrameworkCore3.Test.zip](https://github.com/aspnet/EntityFrameworkCore/files/3006530/EntityFrameworkCore3.Test.zip)



```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

I have a sample project that demonstrates the behavior that I attached.  All of my classes are in the directory: ClassesForTestCase.  Program.cs performs the migrations and calls a SeedData method that inserts test data into all of the tables.  Controller Home, action Index queries the database for an existing item and performs an update.  

`await _context.SaveChangesAsync();`

Produces the error specified.  Simply running the program should display the error on the home index page.

### Further technical details
EF Core version: 3.0.0-preview3.19153.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: (e.g. Visual Studio 2019 16 4.3)

**Comment by ajcvickers** [comment]
@dpedrelli You mentioned an attachment, but I don't see it.

**Comment by dpedrelli** [comment]
Oh.  I see the file listed under Stack Trace.  I'll try adding again.
[EntityFrameworkCore3.Test.zip](https://github.com/aspnet/EntityFrameworkCore/files/3009943/EntityFrameworkCore3.Test.zip)

**Comment by dpedrelli** [comment]
@ajcvickers  ^^^

**Comment by dpedrelli** [comment]
@ajcvickers I found another issue and added it to the project.  Entity Framework Core 3 appears to not support one-to-one relationships.

```
                entity.HasOne(d => d.Link)
                    .WithOne(p => p.LinkPeer)
                    .HasForeignKey(d => d.LinkId)
                    .OnDelete(DeleteBehavior.Restrict);
```
Produces an error in the VS IDE, under the line .HasForeignKey(d => d.LinkId).
Cannot convert the Lambda expression to type 'string' because it is not a delegate type
[EntityFrameworkCore3.Test.zip](https://github.com/aspnet/EntityFrameworkCore/files/3010473/EntityFrameworkCore3.Test.zip)
.

**Comment by AndriySvyryd** [comment]
@dpedrelli This is due to a [breaking change in EF Core 3.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dc)
You would need to disable value generation for all key properties that are being set:
```C#
entity.Property(e => e.Id).ValueGeneratedNever();
```
