### ISSUE TITLE
Creating different value in StringTypeMapping for migrations vs query

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#15165]
Is there an easy way to distinguish whether the call to `StringTypeMapping.GenerateNonNullSqlLiteral` is in migrations vs because of query generation? For migrations I need to generate slightly different literal for strings as not everything that's allowed in query is allowed in i.e. `DEFAULT` clause (and yes, query benefits from this extra stuff). 

I suppose the answer is no, I just hope for the best. :)

**Comment by roji** [comment]
@cincuranet AFAIK there's nothing to allow you to make that distinction, but a string literal really only represents a... string literal - it's surprising to think of different literals. Can you provide a bit more detail/examples on what's support in queries and not in migrations?

**Comment by cincuranet** [comment]
When you have a string literal in a query, the type, in Firebird, is `CHAR(x)`. Hence if you have i.e. `cond ? "Yes" : "No"` in C#, the SQL will have `CASE WHEN cond THEN 'Yes' ELSE 'No'` and the resulting type is `CHAR(3)` and reading the _No_ will give you actually `"No "`. This a) makes some tests fail and b) makes it unintuitive for the C# user. Solution is to force `VARCHAR` type by explicitly casting i.e. `CAST('Yes' AS VARCHAR(2))` and `CAST('No' AS VARCHAR(3))`. Then the resulting type is `VARCHAR(x)` and so it does not contain the right spaces as for `CHAR(x)`.

Easiest would be to know where I am in `GenerateNonNullSqlLiteral`, but I thought this information is not accessible.

I'm now playing with `IExpressionFragmentTranslator` and custom expression to handle it later in derived `DefaultQuerySqlGenerator`. Might be an overkill, though. Maybe special case for `ExplicitCastExpression` and wrapping the string `ConstantExpression` into it will do.

**Comment by cincuranet** [comment]
Wait a minute. I'm over-engineering that. I can handle it directly in `VisitConstant`. That's not only simple, but also likely correct place for it. 🙃

**Comment by smitpatel** [comment]
In 3.0 query pipeline,
1. If default type for string is `CHAR(x)` which does padding then probably default for strings should be varchar.
2. If the type mapping can be inferred from one side, you will get that type mapping. So `cond ? column : "no"` will print "no" with whatever type mapping of column is.
3. If `cond ? "Yes" : "No"` is in projection where there is no way to infer type mapping then default will be used. Hence a good default helps.
4. IExpressionFragmentTranslator is dead.

**Comment by cincuranet** [comment]
Ad 1-3> It's not what's default in query pipeline, but rather what type server infers, as it's a literal.
Ad 4> Well, I didn't use it at the end. But sad for backwards compatibility anyway.

**Comment by smitpatel** [comment]
There is nothing in IExpressionFragmentTranslator which cannot be done in SqlTranslatingExpressionVisitor directly. It may have impact if there are plugins out there which are using it but as of now there are none (to my info).

If server infers incorrect type of literal then perhaps putting explicit cast around it is required. See Float/Bool type mapping for SqlServer. Further, if you say type mapping is inferred by server which causes `No` to be padded with space then probably should just return that. Or do some magic when reading. Therefore the default matters. If server is going to do padding like that without info where it should not be, you can always cast such literals to varchar while printing so server does not do weird magic.

**Comment by cincuranet** [comment]
Casting to varchars is exactly what I'm doing.
