### ISSUE TITLE
Update statement using FromSql throws error

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/efcore#15188]
@smitpatel @ajcvickers 
Describe what is not working as expected.

Want to update a table with values using FromSQl and getting below error.

repo.FromSql("update dbo.Invoice set InvoiceStatus= {0},UpdateUser='{1}' where id={2}", 1, User,BatchId).  Please let me know what am i missing here. Can I use FromSQL to do update. 

**Exception**

**Comment by smitpatel** [comment]
`FromSql` is for querying data using custom SQL and not for updates. For updates consider using `context.ExecuteSqlCommand`

**Comment by arunprasathv** [comment]
Thanks Smit, @smitpatel 

I need to tweak to make this change in my API, If inject DBContext  in the API controller do I need to dispose explicitly? I assume the framework take care. 

In the Startup file, I've the following 
services.AddDbContextPool<CBillingContext>(options =>
            {
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
 
                options.UseSqlServer(connectionString);
            }
            );

**Comment by smitpatel** [comment]
If you are getting context through DI, DI will dispose it automatically.

**Comment by arunprasathv** [comment]
Thanks, when we do delete and update at the sametime.. do we need to it in a transaction ? EF Core does create transaction internally if im not wrong. @smitpatel

**Comment by smitpatel** [comment]
SaveChanges are wrapped inside a transaction. ExecuteSqlCommand does not start a transaction. You would need manual transaction.

**Comment by arunprasathv** [comment]
Thanks
