### ISSUE TITLE
SQL Server Connection Resiliency

### ISSUE THREAD

**Issue by Tieantono** [dotnet/efcore#15196]
Hi, I have configured my DbContext to use SQL Server Connection Resiliency feature in EF Core.
When using an UAT server for testing (only using 1 SQL Server 2016 instance), this feature works fine, without throwing any error regarding this feature. But when using production servers (yes, we have 2 SQL Server 2016 instances grouped by SQL Server AlwaysOn feature), there are so many error messages regarding this feature.

### Logs
Here are one of our log (cannot post the exception message below what I have posted since it will tell my project's class name):
```
System.InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.OnFirstExecution()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
```
### Codes
My AddDbContextPool() configurations are like this
```c#
services.AddDbContextPool<MyContext>(options =>
{
    options.UseSqlServer(Configuration.GetConnectionString("MyDb"), strategy =>
    {
        strategy.EnableRetryOnFailure(
            maxRetryCount: 5, 
            maxRetryDelay: TimeSpan.FromSeconds(30), 
            errorNumbersToAdd: null
            );
    });
});
```
Then, my CreateExecutionStrategy() codes are like this
```c#
await MyContext.Database.CreateExecutionStrategy().ExecuteAsync(async () =>
{
    using (var transContext = await this.MyContext.Database.BeginTransactionAsync())
    {
        // Ma codes....
        // First SaveChangesAsync() call.
        await this.MyContext.SaveChangesAsync();

        // Second SaveChangesAsync() call.
        await this.MyContext.SaveChangesAsync();

        // Transaction commit.
        transContext.Commit();
    }
}
```

### Project's frameworks and dependencies
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012 R2
IDE: Visual Studio 2017

I've searched on the internet, but haven't found any similar situations like what I have now.
Thanks in advance.

**Comment by AndriySvyryd** [comment]
@Tieantono Trying just the code you posted does not produce the exception. Could you post a small repro project?
Also is there a particular reason you are not using the latest EF Core version?

**Comment by Tieantono** [comment]
@AndriySvyryd Ok, I'll create a small repro project.

Yes, the problem was not found when using personal computer and UAT server (using Windows Server 2012 R2 too).

We gladly like to use the newest version of EF Core! But sadly, our project is huge, and we don't have time to upgrade our dependencies's version, and we are in production phase right now.

We have problem when we want to save a blob file into our SQL Server database (with VARBINARY(MAX) data type), and we suspect it might be coming from this exception.

**Comment by ajcvickers** [comment]
@Tieantono Just to be sure you are aware, EF Core (and all of .NET Core 2.0) is out of support. It's not getting any updates, even for security issues.

**Comment by Tieantono** [comment]
@AndriySvyryd I'm sorry, but I haven't made the repo yet, but considering the current situation of our project, which is better now after we replaced `AddDbContextPool()` to `AddDbContext()`, we know the what are the reasons:
- When using `AddDbContextPool()`, we still curious about its behaviour. In my codes, there are some DataReader (SELECT query) that are in the `BeginTransaction()` scope. Not only that, some of our transaction codes have a very long processes

Now it's time to refactor all codes to only run `SaveChanges()` once only if it possible. Previously we have to using `BeginTransaction()` since there are some header and detail tables that must be inserted simultaneously, but in order to do that, the header ID must exist first. We just found out recently that we don't need to save the header table first now in EF Core 2.0.

@ajcvickers Oh I didn't know about that, but I've prepared migration branch in order to update our frameworks versions

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
