### ISSUE TITLE
How to reuse expression tree?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#15198]
What I'd like to be able to-do is as follows:
```
Expression exp = Context.MyTable.Include(p => p.AnotherTable).Where(p => p.Id == 1).Expression;
List<MyTable> lstData = Context.MyTable.QueryByMyExpression(exp).ToList();
```
I can't seem to find a method like "QueryByMyExpression".

Is there any way to store a DbSet expression for later use?

I saw "EF.CompileQuery", but that's not exactly what I'm looking for since it's less generic than I'd like (the end result is fairly fixed and requires re-passing values).

**Comment by smitpatel** [comment]
This is more like over-engineering 🚀 

```C#
var query = Context.MyTable.Include(p => p.AnotherTable).Where(p => p.Id == 1);
var lstData = query.ToList();
var someOtherRandomQuery = query.Where(...).OrderBy(...).Skip(0).Take(10).ToList();
```

You can reuse the Queryable directly.

**Comment by OpenSpacesAndPlaces** [comment]
That's tied to a specific context instance and imagine has a  much heavier payload.

The actual use case is not as simple as initial example - that was merely a usage outline.

What I'd actually want to-do is more like:
```
private static ConcurrentDictionary<String, Expression> lstCachedExpressions = new ConcurrentDictionary<String, Expression>()

public void SomeMethod()
{
 using( DbContext Context = new  DbContext) { 
 lstCachedExpressions.TryAdd("someuniquekey", Context.MyTable.Include(p => p.AnotherTable).Where(p => p.Id == 1).Expression)
}
}

public void SomeOtherMethod()
{
 using( DbContext Context = new  DbContext)
 { 
Expression exp;
			 lstCachedExpressions.TryGetValue("someuniquekey", out exp);
List<MyTable> lstData = Context.MyTable.QueryByMyExpression(exp).ToList();
}
}

```

**Comment by smitpatel** [comment]
> That's tied to a specific context instance and I imagine has a much heavier payload.

So is when you do `.Expression` on it. You are never getting out of context unless you replace the context instance in expression tree or you reconstruct expression tree.

**Comment by OpenSpacesAndPlaces** [comment]
Ah, ok - so then "EF.CompileQuery" is currently the only way to get a context free re-usable expression?

**Comment by smitpatel** [comment]
Partially correct. EF.CompileQuery gives you compiled lambda which you can use to re-generate the results. If you are just running same query then it would work. If you are adding more on expression tree then it won't work.

**Comment by OpenSpacesAndPlaces** [comment]
Thanks
