### ISSUE TITLE
Managing SQL Azure Max Connections

### ISSUE THREAD

**Issue by erikrenaud** [dotnet/efcore#15191]
Azure SQL has relatively low maximum connection counts (60 for base database I believe).

In order to protect myself against too many simulataneous connections during a usage peak, I would like to:
1- better understand the behavior of DotNetCore and EFCore when the servers returns a NoMoreConnectionsAvailable type error
2 - a mecanism where i could intercept this so i can fli the health status of my app to degraded, so I can act...

Any ideas, didn't find anything specifc while looking at the code...

**Comment by ajcvickers** [comment]
Moving this to corefx since this is a question about SQL connections, which is something that SQLClient controls, not EF Core.

**Comment by tuath** [comment]
Great ! thx.

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/corefx/issues/36453
