### ISSUE TITLE
HasKey not working with composite of backing field and non-backing field types

### ISSUE THREAD

**Issue by Xaeco** [dotnet/efcore#15207]
In EF Core 3.0 I wan't to create composite primary keys with both a backing field and a non-backing field. Like the following:
`entity.HasKey(e => new { EF.Property<Guid>(e, "TenantId"), e.ContactId });`
or
`entity.HasKey(e => new { Guid = EF.Property<Guid>(e, "TenantId"), e.ContactId });`
or
`.HasForeignKey(d => EF.Property<Guid>(d, "TenantId"))`

Exception:
The properties expression 'e => new <>f__AnonymousType12`2(Guid = Property(e, "TenantId"), ContactId = e.ContactId)' is not valid. The expression should represent a simple property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.

Any help on achieving this would be greatly appreciated.

### Further technical details
EF Core version: 3.0.0-preview3.19153.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.0.0 Preview 4.4)

**Comment by smitpatel** [comment]
You cannot use EF.Property inside model building code. Use string APIs.

**Comment by divega** [comment]
EF Triage: We will use this issue to track the possibility of supporting the EF.Property method inside HasKey. Moving to the backlog. 

Currently the way to do this is as @smitpatel mentioned to use the string version of HasKey.

**Comment by Xaeco** [comment]
> You cannot use EF.Property inside model building code. Use string APIs.

Thanks @smitpatel . That did the trick, I used:
`entity.HasKey("TenantId", "ContactId");`

Long-term though it would be preferable to reference the class properties to reduce errors.

**Comment by Xaeco** [comment]
Hi @divega. Thanks for adding it to the backlog.

**Comment by divega** [comment]
> Long-term though it would be preferable to reference the class properties to reduce errors.

@Xaeco, for cases in which the key members are public properties, you definitively can use the lambda version. The string version is mostly useful in all other cases. You can also take advantage of the `nameof()` operator with the string version when you have composite keys that are mixed.

**Comment by ajcvickers** [comment]
Closing as this is no longer something we intend to implement.
