### ISSUE TITLE
Relationship foreign key was created but reference object is null

### ISSUE THREAD

**Issue by Creta5164** [dotnet/efcore#15210]
I was trying to relationship two classes.
```cs
public class Parent {
  [Key] public string ParentID { get; set; }
  ...
  public Child ChildObject { get; set; }
}

public class Child
{
  [Key] public int ChildIndex { get; set; }
  
  [Required] public string ParentID { get; set; }
  public Parent ParentObject { get; set; }
}

//...in OnModelCreating method, I was trying for ef core will detect child row as object.
modelBuilder.Entity<Parent>()
            .ToTable("Parent")
            .HasOne(i => i.ChildObject)
            .WithOne(c => c.ParentObject)
            .HasForeignKey<MemberContact>(f => f.ParentID);
```

And adding precreated object are fine. (image)
```cs
var ParentObj = new Parent();
ParentObj.ParentID = "cretapark";
var ChildObj = new Child();
ParentObj.ChildObject = ChildObj;

context.Parents.Add(ParentObj);
```

![image](https://user-images.githubusercontent.com/13521406/55277113-f5006680-533f-11e9-9db6-d0db8faffd02.png)  
![image](https://user-images.githubusercontent.com/13521406/55277117-ffbafb80-533f-11e9-9f90-202a7ece8bd3.png)

But after I had try to get parent object, parent object doesn't have child object(null).
```cs
var parent = context.Parents
                    .Where(parent => parent.ParentID == "cretapark")
                    .FirstOrDefault();
if (parent != null) {
    System.Diagnostics.Debug.WriteLine(parent.ChildObject == null);
    //True
}
```

### Further technical details
EF Core version: Npgsql.EntityFrameworkCore.PostgreSQL 2.2.0
Database Provider: PostgreSQL
Operating system: Windows 10, 1809, 17763.379
IDE: vscode 1.32.3

**Comment by ableji** [comment]
@Creta5164 
you mean Parent.Child is null?
if yes, did you enabled lazy loading?
if not, use include() method or any other loading related data methods.

(I assumed Member entity is the parent and  MemberContact is the child)

**Comment by Creta5164** [comment]
@ableji Thanks to response, I have try lazyload just now.
And this is works fine now. thanks!

![image](https://user-images.githubusercontent.com/13521406/55288166-76aecd80-53ee-11e9-820e-f2f5cdabf945.png)

Refer document post : https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading

**Comment by Creta5164** [comment]
I changed lazy load pattern to eager load pattern, this is also works fine.  
![image](https://user-images.githubusercontent.com/13521406/55363817-57f92580-5519-11e9-83d8-273c805aa892.png)

https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/860
