### ISSUE TITLE
Question - Can Struct/Tuples be faster for Non Tracked Queries

### ISSUE THREAD

**Issue by ackava** [dotnet/efcore#15223]
For non tracked query, with small entity for fairly large result requires unnecessary allocating so many small objects in heap.

Most non tracked objects are anyway readonly, so why force use of class?

Wouldn't it be faster to use struct?

**Comment by ajcvickers** [comment]
@ackava Can you post some code showing an example of a struct that you want to map in this way, and what the code looks like to query it from the database?

**Comment by ackava** [comment]
Consider following query, I need to pull ids with some status and send it to some other service. With tuple, I don't need to create class.

Consider, EmailRecipient entity has lot of fields

```c#

     var list = await db.EmailRecipients
                      .Where(x => x.Email.Sent == true && x.Processed = false)
                      // tuple syntax..
                      .Select( x => ( x.RecipientName, x.EmailAddress ))
                      .Take(1000)
                      .ToListAsync();
     foreach(var (name, email) in list) {
              ..... send push notification 
     }

// with struct..

    public struct RecipientInfo {
           public string Name;
           public string Email;
    }

     var list = await db.EmailRecipients
                      .Where(x => x.Email.Sent == true && x.Processed = false)
                      .Select( x => new RecipientInfo { Name = x.RecipientName, Email = x.EmailAddress } )
                      .Take(1000)
                      .ToListAsync();
     foreach(var r in list) {
              ..... send push notification 
     }
```

In above example, I am not using change tracking, even for couple of fields, Tuple will only hold references to string and copying few bytes on stack will be lot faster compared to allocating and releasing these objects.

**Comment by smitpatel** [comment]
Those queries should be working already. Did you try running them? Did you run into any issues?

**Comment by ackava** [comment]
I got error which is already reported at, https://github.com/dotnet/roslyn/issues/12897

Sorry I thought it was related to EF, but now I understand it is roslyn issue.

Struct and Tuple are working fine if I use `ValueTuple.Create`.
