### ISSUE TITLE
Preventing Entity Types From Navigating to Query Types is very limiting

### ISSUE THREAD

**Issue by WarrenFerrell** [dotnet/efcore#15224]
### Business Need
Say I have the need to keep track of all the walks taken by a group of walkers on a team. 
Each team has a recursive Location structure and each walker belongs to a Location when they take a walk but they can switch to another Location inbetween walks.
However, I want to keep track of where each walk was taken so I can present statistical summaries (e.g. how much time they actually spent walking, etc.) based on the Location of a set of walks during a set timespan. 

```c#
public class Team
{
    public int Id { get; set; }
    public Guid HeadLocationTypeId { get; set; }
    public ICollection<Walker> Walkers { get; set; }
}

public class LocationType
{
    public Guid Id { get; set; }
}

public class Location
{
    public Guid Id { get; set; }
    public Guid? ParentId { get; set; }
    public Guid LocationTypeId { get; set; }
}

public class Walker
{
    public string Id { get; set; }
    public int TeamId { get; set; }
    public ICollection<Walk> Walks { get; set; }
}

public class Walk
{
    public string WalkerId { get; set; }
    public DateTime WalkStart { get; set; }
    public DateTime WalkEnd { get; set; }
    public int BirdsSeen { get; set; }
    public int TimeSpentWalking { get; set; }
    public int DistanceTraveled { get; set; }
    public ICollection<LocationSnapshot> Snapshots { get; set; }
}

public class LocationSnapshot
{
    public string WalkerId { get; set; }
    public DateTime WalkStart { get; set; }
    public Guid LocationId { get; set; }
}
```

Now recursive structures are a pain to deal with in SQL and a huge pain in EF so I decide to create this view, LocationDescendants, of the Location structure - that lists all the descendants for each location. 
This view also introduce a mock HeadLocation for each Team that has the key {TeamId, null} so I can get all Locations for the Team without having to filter for distinct DescendantIds.
But because EF doesn't allow entityTypes to point to queryTypes, I have to create the LocationDescendants as an EntityType and just comment out the migration code... 
Except Ef creates the ModelSnapshot and ignores the nullability of AncestorId so any queries that include a the mock HeadLocation fail because the model thinks AncestorId isn't nullable. 

```c#
public class LocationDescendants
{
    public int TeamId { get; set; }
    public Guid? AncestorId { get; set; }
    public Guid DescendantId { get; set; }
	public Location Ancestor { get; set; }
	public Location Descendant { get; set; }
}

public class Location
{
    ...
    public ICollection<LocationDescendants> Ancestors { get; set; }
    public ICollection<LocationDescendants> Descendants { get; set; }
}
```

I could fix this problem by introducing a HeadLocation for every team but each team is taking at least a million walks a week so this would bloat the size of my already large LocationSnapshot table.
I could also use a surrogate Id for the mock HeadLocation (probably just using HeadLocationTypeId) but this makes it hard to differentiate which members are Head Locations, breaks the filters on 
some queries I have that rely on AncestorId being null when the entire team's Location structure is being queried, and breaks the abstraction that the table represents. 
I could also just do all queries that require the LocationDescendants table from the LocationDescendants DbQuery but this is very limiting and requires more invasive rewriting of many methods that could benefit from the simplicity offered by the LocationDescendants view.
The preferred solution would be to just be able to target the LocationDescendants from my Location entity. 

### Further technical details
EF Core version: 2.2.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: 
IDE: Visual Studio 2017 15.9.9

**Comment by ajcvickers** [comment]
@WarrenFerrell It looks to me like `LocationDescendants` have keys. Is that correct? If so, can you explain why you want to map them as query types, which are explicitly for types that don't have anything that can be used as a unique key?

**Comment by WarrenFerrell** [comment]
@ajcvickers The key for `LocationDescendants` contains the nullable column `AncestorId` which the modelBuilder ignores and maps to a non-nullable column, thus throwing an error every time a LocationDescendant with a null AncestorId (i.e. The mock Head Location for each team) is retrieved. 

```c#
modelBuilder.Entity<LocationDescendants>().HasKey(ld => new { ld.TeamId, ld.AncestorId, ld.DescendantId });
```

I find mapping Views to EntityTypes in general to be a poor workaround because every time anything in the View is changed, a migration needs to be created and all the generated code commented out.

**Comment by ajcvickers** [comment]
@divega to read.
