### ISSUE TITLE
HasOne relationship on Owned type not working as expected with Cosmos

### ISSUE THREAD

**Issue by altick** [dotnet/efcore#15245]
I have the **one-to-many** relationship configured between `Membership` (owned by `Activity` entity) and entity `User`. When I select all activities I get back results where only the first activity's membership contains the instance of the user entity. For the rest of the results the users are set to null.

However when I create all entities and query the activities within the same instance of the context I receive the expected results, i.e. all users are set for all memberships.

This is a snippet of how the relationship between `Membership `and `User `is configured:
```c#
builder.OwnsMany(a => a.Members)
           .HasOne(m => m.User)
           .WithMany()
           .HasForeignKey(m => m.UserId);
```
This is a snippet of how the activities are queried:
```c#
var activities = context.Activities
                .Include(a => a.Members)
                .ThenInclude(m => m.User)
                .ToArray();
```
Please, check out the [solution with the repro](https://github.com/altick/ef-cosmos-relationship-repro) for the further details
_(configured for the local emulator)_

### Further technical details
EF Core version: **3.0.0-preview3.19153.1**
Database Provider: **Microsoft.EntityFrameworkCore.Cosmos 3.0.0-preview3.19153.1**
Operating system: **Win 10**
IDE: **Visual Studio 2019 Preview 4.3**

**Comment by smitpatel** [comment]
Blocked on #16920
The query is doing cross collection include.
