### ISSUE TITLE
Need async entrypoint for custom configuration of DbContext

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/efcore#15247]
This is more of a question than issue, though the question spawns from a issue with that Core does not support AAD.

Net Core and EF core does not support AAD tokens out of the box like full framework. There are a workaround were you can set access token on the SqlConnection. Retrieving the token is a async operation. So I need a generic entrypoint that are async. In constructor of my DbContext I can inject and execute stuff, but I cant do it async so it not good enough.

Bascily I need to a good entrypoint to execute my config class

```csharp
internal class DbTokenConfig : IDbContextConfig
{
    private readonly ITokenProvider _tokenProvider;

    public DbTokenConfig(ITokenProvider tokenProvider)
    {
        _tokenProvider = tokenProvider;
    }

    public async Task Config(MyDbContext context)
    {
        var conn = context.Database.GetDbConnection() as SqlConnection;
        conn.AccessToken = await _tokenProvider.GetAsync();
    }
}
```

**Comment by ajcvickers** [comment]
@AndersMalmgren Not sure why you closed this, but we plan to think about this kind of situation holistically as part of #13261.

**Comment by AndersMalmgren** [comment]
@ajcvickers I found another similar question that stated it was not planned that's why. I solved it in a none async way now when the DbContext is being injected
