### ISSUE TITLE
Consider abstracting connection management

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1529]
In EF7 as well as in EF6 we open the connection on demand and close the connection automatically when it isn't needed. We also allow customers to write code that override this automatic behavior by opening the connection automatically.

Given the wider range of stores we would like to support with EF7, I don't think we can assume that this style of connection management will work in all cases. It seems reasonable that for EF7 we could separate the contract of connection management from the actual implementation, e.g. the context could inform the provider when a connection is being used and when it is being released from use, but it could be up to the provider implementation to decide what to do with that information. Similarly, it would be up to the provider to decide when to create transactions.

I am not 100% sure of the current state of this in the code but looking at several places it seemded to me that we are assuming the connection can be managed in a similar way as in EF6.

**Comment by ajcvickers** [comment]
Closing as we haven't seen significant demand for this feature. We could revisit this decision based on feedback and we would also consider a well-written community PR for it.
