### ISSUE TITLE
Consider using System.Transactions.Transaction.Current in relational when running on desktop .NET

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1530]
When running on desktop .NET ADO.NET connections (at least SqlClient and a few more providers) will get auto-enlisted in ambient transactions. In EF6 we integrate with System.Transactions by checking for Transaction.Current not being null before we decide wether we need to initiate our own local DbTransaction. If we don't do the same in EF7 when running on desktop .NET, the behavior of EF7 in presence of ambient transactions will most likely not meet user expectations.

**Comment by rowanmiller** [comment]
We decided not to support TransactionScope. We decided we should detect if someone is trying to though and throw so it is clear it's not supported (#1584).
