### ISSUE TITLE
QueryRewrite: clean up query validation for various negative cases

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15312]
We have a number of tests that verify we validate negative inputs correctly. Those are now different in many places. Disabling tests for now and will clean them up once we have a fuller picture of the entire pipeline.

**Comment by smitpatel** [comment]
I am adding few more.

**Comment by smitpatel** [comment]
@maumar - I think you have fixed most of these (added validations in source code). It would be good to just scrub here if we are missing anything still so we can prioritize properly (or just add them if it is easy).
