### ISSUE TITLE
EF Core2.2 Aggregation functions not working as expected with SQLite Provider

### ISSUE THREAD

**Issue by sagarpdesai** [dotnet/efcore#15324]
I am using ef core 2.2 and LINQ with SQLite provider. I am trying to aggregate multiple columns in a query. The sql query generated by LINQ is incorrect and is yielding incorrect results.

.Net Core Sample Code for Aggregate Query with multiple columns:
```C#
 public async Task<SecondaryInvoiceLProformaTotals> test(int secondaryInvoiceId)
        {
            var query = (_context.SecondaryInvoiceLineItems
                    .Where(i => i.SecondaryInvoiceId == secondaryInvoiceId)
                    .GroupBy(l => new {l.SecondaryInvoiceId})
                    .Select(g => new SecondaryInvoiceLProformaTotals
                    {                
                        SecondaryInvoiceId = g.Key.SecondaryInvoiceId,        
                        SumInvoiceQty = g.Sum(o => o.InvoiceQty),
                        SumMRPAmount = g.Sum(o => o.TotalMRPAmount),
                        SumSecondaryDiscountAmount = g.Sum(o => o.TotalSecondaryDiscountAmount),
                        SumSecondaryPrice = g.Sum(o => o.TotalSecondaryPrice),
                        SumIGSTAmount = g.Sum(o => o.TotalIGSTAmount),
                        SumCGSTAmount = g.Sum(o => o.TotalCGSTAmount),
                        SumSGSTAmount = g.Sum(o => o.TotalSGSTAmount),
                        SumAmount = g.Sum(o => o.TotalAmount),
                        SumBasePoints = g.Sum(o => o.TotalBasePoints)
                    })
                    );
            SecondaryInvoiceLProformaTotals ret = await query.FirstOrDefaultAsync();            
            return ret;
        }
```
SQL query generated by LINQ:

```sql
SELECT SUM("i"."InvoiceQty") AS "SumInvoiceQty", 
"i"."TotalMRPAmount" AS "SumMRPAmount", 
"i"."TotalSecondaryDiscountAmount" AS "SumSecondaryDiscountAmount", 
"i"."TotalSecondaryPrice" AS "SumSecondaryPrice", 
"i"."TotalIGSTAmount" AS "SumIGSTAmount", 
"i"."TotalCGSTAmount" AS "SumCGSTAmount", 
"i"."TotalSGSTAmount" AS "SumSGSTAmount", 
"i"."TotalAmount" AS "SumAmount", 
SUM("i"."TotalBasePoints") AS "SumBasePoints"
      FROM "SecondaryInvoiceLineItems" AS "i"
      WHERE "i"."SecondaryInvoiceId" = 5
      GROUP BY "i"."SecondaryInvoiceId"
      LIMIT 1
```

Expected SQL Query
```sql
SELECT SUM("i"."InvoiceQty") AS "SumInvoiceQty",
SUM("i"."TotalMRPAmount") AS "SumMRPAmount", SUM("i"."TotalSecondaryDiscountAmount") AS "SumSecondaryDiscountAmount", 
SUM("i"."TotalSecondaryPrice") AS "SumSecondaryPrice", 
SUM("i"."TotalIGSTAmount") AS "SumIGSTAmount", 
SUM("i"."TotalCGSTAmount") AS "SumCGSTAmount", 
SUM("i"."TotalSGSTAmount") AS "SumSGSTAmount", 
SUM("i"."TotalAmount") AS "SumAmount", 
SUM("i"."TotalBasePoints") AS "SumBasePoints"
      FROM "SecondaryInvoiceLineItems" AS "i"
      WHERE "i"."SecondaryInvoiceId" = 5
      GROUP BY "i"."SecondaryInvoiceId"
      LIMIT 1
```

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.Sqlite

----

Operating system: 
IDE: Visual Studio Code Version 1.32.3 (1.32.3)

**Comment by smitpatel** [comment]
The issue here is, all the columns which don't have SUM are decimal column. SQLite specifically blocks decimal aggregate translation to server. But group by part in relational is still lifting them.
Regardless given decimal restriction on SQLite, this query cannot be translated to server fully.

**Comment by ajcvickers** [comment]
Notes from triage: there is no way we can reliably translate anything that requires decimal ordering, since since SQLite doesn't have a decimal type and the mapping to strings does not preserve ordering. Actions here:
* Document SQLite limitations here. (https://github.com/aspnet/EntityFramework.Docs/issues/1433) Specifically:
  * Why these expressions are not translated on SQLite
  * How to cast to double if the data loss is acceptable for the comparison
* Document this as a breaking change, even though it is technically covered by the client-eval break (https://github.com/aspnet/EntityFramework.Docs/issues/1432)

Closing this issue since there is nothing to do here given that the `decimal` operations cannot be translated.
