### ISSUE TITLE
Unset<T>    Collectible assemblies (net core 3)

### ISSUE THREAD

**Issue by Diaskhan** [dotnet/efcore#15342]
In nearest Future, when ships net core 3.0 wil be present Collectible Assemblies.

1.It is in theory possible to Unset<T>("Sometype")
If is Seted dynamicaly with reflection  (Set("Sometype")) ??

2.Or better is Reconfigure Dbcontext ?

Its need for Dynamic Plugin Scenario !

**Comment by ajcvickers** [comment]
@Diaskhan Are you asking to un-register an entity type from the model that has previously been registered?

**Comment by Diaskhan** [comment]
Yes !
I have following idea! 

1.Generate entity class and ientitytypeconfiguration ! 
2. Compile with roslyn ! 
3. Apply assembly to new dbcontext like in this article 
https://stackoverflow.com/questions/49946019/how-can-i-use-the-entity-framework-core-capabilities-to-change-my-database

4. Recompile all models and reload current dbcontext with new models ! 

The 4 part searching how it could be done ?

**Comment by ajcvickers** [comment]
@Diaskhan Sorry, but we have no plans to implement this.

**Comment by Diaskhan** [comment]
Maybe imodelkeycahchefactory helps ?
