### ISSUE TITLE
[Design] Interface segregation for DbContext and DbSet

### ISSUE THREAD

**Issue by MorenoGentili** [dotnet/efcore#15358]
Hello everyone. I'm using the dependency injection of ASP.NET Core to receive a `DbContext` instance in my application service.
``` C#
public class ProductService {
    public ProductService(MyDbContext context)
    {
        //...
    }
}
```
As you can see, this service is dealing with _products_ and I'm not too comfortable in making it depend on a `MyDbContext` that contains all sorts of `DbSets`. This violates the interface segregation principle.

Of course, I could write my own abstraction on top of it, but I think the `DbContext` could be a friendlier and easier-to-use object if it let my service depend on what it actually needs.
I'm suggesting Entity Framework Core provided a `IReadOnlyDbSet<T>` interface which would be resolved with the `DbSet<T>` instance. I would use it like this:
``` C#
public class ProductService {
    public ProductService(IReadOnlyDbSet<Product> products)
    {
        //...
    }
}
```
And then, when I needed to also insert, update and remove products, I would depend on `IDbSet<Product>` which would also expose the `Add`, `Update` and `Remove` methods, among the others. My service would also depend on `IDbContext<Product>` which would provide the `SaveChanges` and `SaveChangesAsync` methods.
``` C#
public class ProductService {
    public ProductService(IDbSet<Product> products, IDbContext<Product> context)
    {
        //...
    }
}
```
This would save me the chore of implementing the UoW & Repository patterns and it would not need an abstraction with lots of plumbing code in it.
Of course, this is still an opinionated and half-reasoned suggestion (e.g. how would it work in a project with multiple `DbContext`s mapping the same `Product` entity class?) but I still like to know your opinion about it.

**Comment by ajcvickers** [comment]
@MorenoGentili We discussed this and agreed that this kind of abstraction is best implemented in application code, or possibly in an opinionated data abstraction that sits on top of EF Core. Either way, we don't plan to implement this in the EF Core codebase.  Doing so would likely result in either something so opinionated that it isn't generally useful, or so general that it isn't opinionated.
