### ISSUE TITLE
Unable to add migration in .net core 3.0 project

### ISSUE THREAD

**Issue by alexandermujirishvili** [dotnet/efcore#15378]
I try to add migration in .net core 3.0 project, but for some reason I get the following error:

Unable to create an object of type 'MyDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

![image](https://user-images.githubusercontent.com/46314872/56230924-4faef780-608e-11e9-86ac-708486f9a955.png)

I have tried same in .net core 2.2 project and I have successfully added migration.

Simple projects to see problem:
https://github.com/alexandermujirishvili/EFCoreProblem

**Comment by ajcvickers** [comment]
Note for triage: this is because we are not picking up `CreateHostBuilder` in:
```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

Changing to `CreateWebHostBuilder` makes this work:
```C#
public static IHostBuilder CreateWebHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```
/cc @bricelam

**Comment by bricelam** [comment]
@alexandermujirishvili If you update your EF Core packages to 3.0.0-* does it work? `CreateHostBuilder` isn't detected by EF Core 2.2

**Comment by alexandermujirishvili** [comment]
@bricelam Yes, it works. Thank you.
