### ISSUE TITLE
the sequence of data which is inserted to db is not same the code sequence

### ISSUE THREAD

**Issue by zxs731** [dotnet/efcore#15382]
i find if the child collection have item more than 20 then the insert sequence is not same with code. Not sure why and how to control the insert？

**Comment by ajcvickers** [comment]
@zxs731 This is by-design because preserving order requires overhead, and in the general case EF needs to  be able to order inserts to avoid deadlocks.  Issue #9067 tracks ordered collections, which may be related to what you are trying to do.
