### ISSUE TITLE
Add generic KeyBuilder

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#15380]

**Comment by ajcvickers** [comment]
Only a binary break, so it can come in late.

**Comment by lajones** [comment]
Poaching.

**Comment by ajcvickers** [comment]
@AndriySvyryd Should this still be marked as fixed? Should we file a new issue for HasKey returning the generic key builder?

**Comment by AndriySvyryd** [comment]
The generic builder is in the code so this is still fixed. I don't think it's worth it to keep tracking this.
