### ISSUE TITLE
Run the internal code usage analyzer on the providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#15393]
We have an analyzer that detects usage of internal code, but it doesn't run on the EF Core providers in the solution since analyzers don't work across project references.

Look into running the analyzer from a test instead, for the providers only. This could also be useful in the functional test suite for other providers.

**Comment by ajcvickers** [comment]
We need some way to do this automatically, but does not have to be analyzer.

**Comment by bricelam** [comment]
Project | Violations
--- | ---:
Cosmos | 27
Design | 1,214
InMemory | 17
Proxies | 8
Relational | 275
Sqlite | 2
Sqlite.NTS | 2
SqlServer | 4
SqlServer.NTS | 0

**Comment by bricelam** [comment]
Looks like we can use a project reference:

``` xml
<ProjectReference Include="..\EFCore.Analyzers\EFCore.Analyzers.csproj"
                  ReferenceOutputAssembly="False"
                  OutputItemType="Analyzer" />
```
Some people have reported issues (e.g. having to unload and reload projects) but we can try it and see how annoying it is.

**Comment by ajcvickers** [comment]
Removing from Backlog to remember to discuss on Friday.

**Comment by ajcvickers** [comment]
Notes from discussion:
* @smitpatel to investigate the relational uses.
  * It may be correct to allow relational to use internal references, as long as these internal uses are not blocking things needed by non-relational providers.
  * We should follow up with other non-relational providers to see what they are using
* For 5.0, we need to check/fix the other uses
  * Some of them are intentional
  * We should run the analyzer against providers even if we have to suppress in some cases
  * SqlServer uses PropertyBaseExtensions, ConventionAnnotation & RelationalExpressionExtensions
  * Sqlite uses TypeExtensions
  * Sqlite.NTS uses SqliteOptionsExtension

See also https://github.com/dotnet/efcore/issues/16707 for Cosmos

**Comment by smitpatel** [comment]
Apart from few issues/PR I filed, comprehensive report.
```
ForeignKeyConstraint.cs: ForeignKeyComparer 
TableIndex.cs: IndexComparer 
UniqueConstraint.cs: KeyComparer 
MigrationsSqlGenerator.cs: SemanticVersionComparer 
FromSqlParameterApplyingExpressionVisitor.cs: ReferenceEqualityComparer 
RelationalValueGeneratorSelector.cs: TemporaryNumberValueGeneratorFactory 
RelationalCommandBuilder.cs: IndentedStringBuilder 
TableAliasUniquifyingExpressionVisitor.cs: ReferenceEqualityComparer 
KeyValueIndexFactorySource.cs: IdentityMapFactoryFactoryBase 
RelationalValueGeneratorSelector.cs: TemporaryDateTimeValueGenerator 
RelationalValueGeneratorSelector.cs: TemporaryDateTimeOffsetValueGenerator 
RelationalValueGeneratorSelector.cs: StringValueGenerator 
RelationalValueGeneratorSelector.cs: BinaryValueGenerator 
ModificationCommand.cs: NonCapturingLazyInitializer 
KeyValueIndexFactory.cs: IPrincipalKeyValueFactory<TKey> 
KeyValueIndexFactory.cs: IDependentKeyValueFactory<TKey> 
KeyValueIndexFactory.cs: ForeignKeyExtensions 
KeyValueIndexFactorySource.cs: KeyExtensions 
TableMappingBaseComparer.cs: EntityTypePathComparer 
MigrationsModelDiffer.cs: Multigraph<,> 
ModificationCommand.cs: InternalEntityEntry 
ModificationCommandComparer.cs: PropertyBaseExtensions 
CommandBatchPreparer.cs: Multigraph<,> 
Migrator.cs: IndentedStringBuilder 
CommandBatchPreparer.cs: Graph<,> 
CommandBatchPreparer.cs: IndexExtensions 
CommandBatchPreparer.cs: IDependentKeyValueFactory<object[]> 
CommandBatchPreparer.cs: INullableValueFactory<object[]> 
MigrationsSqlGenerator.cs: CoreAnnotationNames 
MigrationsModelDiffer.cs: EntityTypeExtensions 
ColumnMappingBaseComparer.cs: EntityTypePathComparer 
RelationalTypeMappingSource.cs: PropertyExtensions 
RelationalTypeMappingInfo.cs: PropertyExtensions 
RelationalExecutionStrategyFactory.cs: NoopExecutionStrategy 
RelationalModel.cs: DebugView 
RelationalModel.cs: ForeignKeyComparer 
RelationalModel.cs: EntityTypePathComparer 
```

**Comment by smitpatel** [comment]
Enabled in relational with suppression in place.
