### ISSUE TITLE
[Feature Request] attach entity return query

### ISSUE THREAD

**Issue by mhamri** [dotnet/efcore#15396]
I have this problem with Efcore where I have disconnected entities (mainly in the asp.net core) where I need include some infromation that only are available in some relations.

`_context.Entry(disconnectedEntity).Collection(x=>x.RelationTable).Load();`

this would work but at the same time i'm loosing the option to query only a portion of the `RelationTable` which i need.

compare to above method i am loosing some benefit.

```
_context.DisconnectedEntity.Where(x=>x.Id== disconnectedEntity.Id).Select(x=> new DataINeedOnly {
                Id=x.Id,
                RelationData=x.RelationTable.SomeData,
                Name= x.Name,
                Address= x.Address
            }).FirstOrDefault();
```

in this method i'm only loading `SomeData` from the relationship which I only need. but at the same time i'm loading the data that i already have from the `disconnectedEntity`.

another options is to load only what i need and map the other data manually.
or using `.Query()` on `Collection()` and then map those values back to the result separately.
```
var result= _context.DisconnectedEntity.Where(x=>x.Id== disconnectedEntity.Id).Select(x=> new DataINeedOnly {
                Id=x.Id,
                RelationData=x.RelationTable.SomeData,
            }).FirstOrDefault()

result.Name= disconnectedEntity.Name;
result.Address= disconnectedEntity.Address;
```
all the solutions are ugly and not consistent. involve a lot of redundant and repeating code. 

i wish for something like this

```
_context.DisconnectedEntity.Attach(disconnectedEntry).Query().Select(x=> new DataINeedOnly {
                Id=x.Id,
                RelationData=x.RelationTable.SomeData,
                Name= x.Name,
                Address= x.Address
            });
```
or something like this in case of having a list to attach

```
_context.Attach(listOfDisconnectedEntities).Query().Include(x=>x.what relation).Where(x=>true).First()
```

the whole point is when i'm attaching something it should be the state of the available values and should query those values that isn't there like relation data.

at the moment the `Query()` is supported on `Collection` but i wish for having it on the `EntityEntry` itself

p.s i wrote this from top of my mind just here so please forgive the typo and syntax error

**Comment by ajcvickers** [comment]
@mhamri Can you use something like this?

```C#
context.Attach(disconnectedEntity).Collection(e => e.RelationTable).Load();
```
In my test code below this results in the following SQL:
```sql
SELECT [e].[Id], [e].[BlogId]
FROM [Post] AS [e]
WHERE [e].[BlogId] = @__get_Item_0
```

Full test code:
```C#
public class Blog
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public  Blog Blog { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory Logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog
            {
                Id = 1,
                Posts = new List<Post>
                {
                    new Post(),
                    new Post(),
                    new Post()
                }
            });
            
            context.SaveChanges();
        }
        
        using (var context = new BloggingContext())
        {
            var disconnectedEntity = new Blog { Id = 1 };

            context.Attach(disconnectedEntity).Collection(e => e.Posts).Load();

            Debug.Assert(disconnectedEntity.Posts.Count == 3);
        }
        
        using (var context = new BloggingContext())
        {
            var disconnectedEntity = new Blog { Id = 1 };

            var posts = context.Attach(disconnectedEntity).Collection(e => e.Posts).Query().ToList();

            Debug.Assert(posts.Count == 3);
            Debug.Assert(disconnectedEntity.Posts.Count == 3);
        }
    }
}
```

**Comment by mhamri** [comment]
thanks, @ajcvickers for the example, I am well aware of this. the problem I'm pointing out is how projection would work in this case. let's call it disconnected entity's projection.

what should I do when I want to project the `Blog` to `BlogProjection` when it's a disconnected Entity? if I project a disconnected entity when I want to load some related data into a projection it will query the whole thing. while it's unnecessary. 

I can't attach a disconnected entity and query those portions that are missing and then do a projection on top of that.

as I mentioned in the first post, I have some limited option, like to get the missing parts separately, then put them back together piece by piece or use Automapper or some other solution or query the whole things again based on the entity Id.

**Comment by ajcvickers** [comment]
@mhamri It seems that you are asking for a way to combine some form of query (e.g. projection) against both entities that are being pulled from the database and entities that are already tracked without requesting again the already tracked entities from the database. This is covered by #2982. However, it's a large, involved feature, so it's not something that we plan to take on anytime soon, and my best guess is that it's realistically something we will never do.
