### ISSUE TITLE
Internal API usages detected by analyzer in providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#15416]
While working on syncing EFCore.PG with preview4, the analyzer flagged several internal API usages, where Npgsql is doing the same thing as the SqlServer provider. Some of them may be known, but I'm dumping them all here - we can triage and split off to other issues later (am omitting obvious cases of the query pipeline which will get replcaed). Hopefully #15393 will help detect this kind of thing earlier in the future.

* [SqlServerConventionSetBuilder calls ConventionSet.CreateConventionSet()](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs#L124)
* [SqlServerConventionSetBuilder uses RelationalMaxIdentifierLengthConvention](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs#L65)
* [SqlServerInternalMetadataBuilderExtensions uses RelationalForeignKeyBuilderAnnotations (the rest of the builder annotations are similar))](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Metadata/Internal/SqlServerInternalMetadataBuilderExtensions.cs#L82)
* [SqlServerCompiledQueryCacheKeyGenerator extends RelationalCompiledQueryCacheKeyGenerator ](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs#L26)
* [SqlServerExecutionStrategy calls ICurrentDbContext.Context](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Storage/Internal/SqlServerExecutionStrategy.cs#L55)

Tests:
* [TestRelationalCommandBuilderFactory uses IndentedStringBuilder](https://github.com/aspnet/EntityFrameworkCore/blob/5643bb6dcacaa294197e6649caac6a7a410434f5/test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs#L36)
* [BatchingTests use RelationalResources.{LogBatchReadyForExecution,LogBatchSmallerThanMinBatchSize}](https://github.com/aspnet/EntityFrameworkCore/blob/140f4cf9d01ebdc1c0b621018bc3f0770c4aa50e/test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs#L177)

**Comment by ajcvickers** [comment]
Product code;
* These should be covered by #214 or related issues that @AndriySvyryd is working on:
  * [SqlServerConventionSetBuilder calls ConventionSet.CreateConventionSet()](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs#L124)
  * [SqlServerConventionSetBuilder uses RelationalMaxIdentifierLengthConvention](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs#L65)
  * [SqlServerInternalMetadataBuilderExtensions uses RelationalForeignKeyBuilderAnnotations (the rest of the builder annotations are similar))](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Metadata/Internal/SqlServerInternalMetadataBuilderExtensions.cs#L82)
* Created #15442 for this, but it looks like it just needs docs update:
  * [SqlServerCompiledQueryCacheKeyGenerator extends RelationalCompiledQueryCacheKeyGenerator ](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs#L26)
* Created #15441:
  * [SqlServerExecutionStrategy calls ICurrentDbContext.Context](https://github.com/aspnet/EntityFrameworkCore/blob/71a32cfd5a8c24dde5c8938f7eee4d8a14f29f5d/src/EFCore.SqlServer/Storage/Internal/SqlServerExecutionStrategy.cs#L55)

Tests:
* Created #15443:
  * [TestRelationalCommandBuilderFactory uses IndentedStringBuilder](https://github.com/aspnet/EntityFrameworkCore/blob/5643bb6dcacaa294197e6649caac6a7a410434f5/test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs#L36)
  * [BatchingTests use RelationalResources.{LogBatchReadyForExecution,LogBatchSmallerThanMinBatchSize}](https://github.com/aspnet/EntityFrameworkCore/blob/140f4cf9d01ebdc1c0b621018bc3f0770c4aa50e/test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs#L177)
