### ISSUE TITLE
Namespace and dotnet ef dbcontext scaffold 

### ISSUE THREAD

**Issue by RCRoederHPE** [dotnet/efcore#15421]
I found it annoying that you cannot specify the default Namespace. Any solution? I can clean it up afterwords. But i get a build failed.

dotnet ef dbcontext scaffold "server=DEV07; Database=ProjectsNow.Schedule; Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models\Schedule -c dbScheduleContext -f -d --use-database-names  --context-dir Data

**Comment by ajcvickers** [comment]
Duplicate of #9723
