### ISSUE TITLE
EntityTypeBuilder does not contain a definition for HasData

### ISSUE THREAD

**Issue by manutdkid77** [dotnet/efcore#15459]
I have an entity `Movie`, to which I am trying to seed data. As mentioned in the [docs](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#model-seed-data), we need to use the `HasData()`. However I am receiving an error saying there is no definition for HasData

```
EntityTypeBuilder<Movie>' does not contain a definition for 'HasData' 
and no accessible extension method 'HasData' accepting a first argument of 
type 'EntityTypeBuilder<Movie>' 
could be found (are you missing a using directive or an assembly reference?) (CS1061)
```
However I can find/use other methods from the `Microsoft.EntityFrameworkCore.Metadata.Builders` namespace

I also found a [comment](https://github.com/aspnet/EntityFrameworkCore/issues/11629#issuecomment-384336352) for a similar issue. Please let me know if I need to provide more details.

### Further technical details
EF Core version: Entity Framework Core .NET Command-line Tools
2.2.2-servicing-10034
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Win10
IDE: VS Code 1.33.1

**Comment by ajcvickers** [comment]
@manutdkid77 Please post a small project/solution that demonstrates the behavior you are seeing.

**Comment by manutdkid77** [comment]
@ajcvickers Can you please take a look at this [project](https://github.com/manutdkid77/TheMoviePlace)

**Comment by ajcvickers** [comment]
@manutdkid77 That project targets EF Core 2.0, which is out of support. Please try either 2.1 or 2.2.

**Comment by manutdkid77** [comment]
@ajcvickers I can confirm that by migrating to 2,2, the issue has been resolved. Thank you for the guidance.

**Comment by SammyK08** [comment]
@ajcvickers  Thank You for your suggestion. I updated my EF core to 2.1 and it worked.
