### ISSUE TITLE
Fail: The LINQ expression 'First()' could not be translated and will be evaluated locally

### ISSUE THREAD

**Issue by mhosman** [dotnet/efcore#15476]
Hi! I'm using .NET Core 3.0.0-preview4-19216-03.
I have a query that includes "Lang_Attributes" and a global filter in order to get just one value of that list. Then I just try to order by the name of the filtered lang_attribute:

`await query.Include(c => c.Lang_Attributes).OrderBy(c => c.Lang_Attributes.First().Name).ToListAsync()`

I get a warn and a fail (error) because the First() is evaluated locally. How can I fix this?? This is not supposed to be an error in preview 4. Thank you very much!

```
warn: Microsoft.EntityFrameworkCore.Query[10103]
      Query: '(from Role_Lang <generated>_1 in [c].Lang_Attributes select [<generated>_1].Name).First()' uses First/FirstOrDefault/Last/LastOrDefault operation without OrderBy and filter which may lead to unpredictable results.
```

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLM8DJH1NVPC", Request id "0HLM8DJH1NVPC:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'First()' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg)........................
```

**Comment by sdanyliv** [comment]
As a one of the guys who know how LINQ providers work and what SQL can do, for your sample I suggest to enforce client side evaluation:
```cs
(await query.Include(c => c.Lang_Attributes)
    .ToListAsync())
    .OrderBy(c => c.Lang_Attributes.First().Name)
    .ToList();
```
You have created complicated query for SQL Server, which needs Window Functions usage (not supported in EF) and subquery involving. If you need pagination later - better to write raw sql (not easy task at all).
LINQ gives a lot of ways for data manipulations, but not all of them can be effectively translated to SQL.

**Comment by mhosman** [comment]
Hey @sdanyliv thanks for the response! Yes, in the complete query I have pagination so adding a ToListAsync before OrderBy is not the best scenario for my situation. I really don't know how to achieve this issue.

**Comment by mhosman** [comment]
Just updated: 
`await query.Include(c => c.Lang_Attributes).OrderBy(c => c.Lang_Attributes.First().Name).ToListAsync()`
To:
`await query.Include(c => c.Lang_Attributes).OrderBy(c => c.Lang_Attributes.FirstOrDefault().Name).ToListAsync()`

And worked like a charm....

**Comment by divega** [comment]
Note from triage: @smitpatel to respond.

**Comment by sdanyliv** [comment]
> And worked like a charm....

@mhosman, interesting, can you show here SQL?

**Comment by smitpatel** [comment]
`First` has throwing behavior if sequence contains no elements. We try to preserve that hence cause client eval. `FirstOrDefault` should be able to do server eval. In 3.0 we are blocking client eval other than top level projection but we will treat First & FirstOrDefault the same so it would be translated to server.
