### ISSUE TITLE
Consider an overload of `Update` that specifies which properties should be modified

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#15493]
for example when in MVC edit action want to save changes, usually needs to escape multi properties of the model from saving because is current have null values.

```
db.Entry(model).State = EntityState.Modified;
db.Entry(model).Property(p => p.Name).IsModified = false;
db.Entry(model).Property(p => p.RelatedId).IsModified = false;
db.Entry(model).Property(p => p.Description).IsModified = false;
db.Entry(model).Property(p => p.IsActive).IsModified = false;
```
for each property that want ignore from saving must add line of code for will be escaped.

please add the Ignore method that can ignore multi properties in one line of code.

```
db.Entry(model).State = EntityState.Modified;
db.Entry(model).Ignore(p => new { p.Name, p.RelatedId, p.Description, p.IsActive });
```

**Comment by ajcvickers** [comment]
@mojtabakaviani This pattern of marking all the properties as modified and then re-marking certain properties as not modified is usually not the best approach. Can you provide some details as to why you're doing it this way?

**Comment by mojtabakaviani** [comment]
By default, all the properties are modifiable and usually need the marked some properties not as modified. This pattern helps to marked selected properties as a line of code instead of write multi-lines.
I write this with an extension method and for example in MVC web projects very useful ignore model's properties that not in view when updating model.

**Comment by mojtabakaviani** [comment]
thanks, capability ignore or modify specifies properties very useful, some time need ignore few properties, some time need modify few properties.

**Comment by Matthiee** [comment]
@ajcvickers  I'll implement this one.

**Comment by ajcvickers** [comment]
Note from triage: this is not something we plan to implement. Related functionality in #5536 may help here.
