### ISSUE TITLE
Entity not being ignored by ModelBuilder

### ISSUE THREAD

**Issue by MesquitaEngineer** [dotnet/efcore#15496]
I'm setting my context through the Modelbuilder in OnModelCreating Method. I have two classes. One called 'Pessoa' and the other 'Membro'. 'Membro'.relates to 'Pessoa'. But I do not want to have to map Pessoa'. Only the Membro'. class is mapped. But when I run my project, I get an error saying: "You need to set a Primary Key for 'Pessoa'." If I did it, displays error message "Column Invalid 'PessoaCodigo'".

I need to keep these classes, because other contexts share it. And in these Person is mapped.

My Base Context

```C#
public abstract class BaseDbContext : DbContext
{
    public DbSet Pessoas { get; set; }
    public DbSet Membros { get; set; }
}
```

My derived context

```C#
public class ConmembDbContext : BaseDbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json")
            .Build();

        optionsBuilder.UseSqlServer(config.GetConnectionString("Conmemb"));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Ignore();
        modelBuilder.ApplyConfiguration(new MembroMap());
    }
}
```

my configured to membro Map;

```C#
public class MembroMap : IEntityTypeConfiguration
{
    public void Configure(EntityTypeBuilder builder)
    {
        builder.ToTable("tblMembros");

        builder.HasKey(b => b.codigo);
        builder.Property(b => b.codigo).HasColumnName("iCodigo").HasConversion<System.Int16>();
        builder.Ignore(b => b.codigoPessoa);
        
        //builder.Ignore(p => p.pessoa);

        //builder.HasOne(p => p.pessoa)
        //    .WithMany(p => p.membro)
        //    .HasForeignKey(p => p.codigoPessoa);
    }
}

public class Membro
{
    public int codigo { get; set; }
    public int? codigoPessoa { get; set; }

    public Pessoa pessoa { get; set; }
 }

public class Pessoa
{
    public int codigo { get; set; }
    public ICollection<Membro> membro { get; set; }
}
```

Why?

**Comment by ajcvickers** [comment]
@MesquitaEngineer A few things:
* The `DbSet` property for `Pessoa` will cause it to be mapped.
* The reference from `Membro` to `Pessoa` will cause it to be mapped.
* If you really want only one type to be mapped, then remove the `DbSet` and `Ignore` the reference from `Membro` to `Pessoa`.

All that being said, I'm left wondering why you want to map only one entity type when the two are related like this.

**Comment by MesquitaEngineer** [comment]
I can not do this because I have other contexts that share dbset <Person> ();

But I found the solution to my problem. there was another mapping that was requiring a foreign key. 'Contrato' Class  with 'Pessoa' Class. And in that I mapped the key:

protected override void OnModelCreating (ModelBuilder modelBuilder)
        {

            modelBuilder.ApplyConfiguration (newMap Membro());
            modelBuilder.ApplyConfiguration (new ContratoMap ());
       
            modelBuilder.Ignore <Pessoa> ();

            

        }


public class ContratoMap : IEntityTypeConfiguration<Contrato>
    {
        public void Configure(EntityTypeBuilder<Contrato> builder)
        {
            builder.ToTable("RHCONTRATOS");

            builder.Property(b => b.unidade).HasColumnName("UNIDADE");
            builder.Property(b => b.empresa).HasColumnName("EMPRESA");
            builder.Property(b => b.codigo).HasColumnName("CONTRATO");
            builder.Property(b => b.codigoPessoa).HasColumnName("PESSOA");
            builder.Property(b => b.situacao).HasColumnName("SITUACAO");
            builder.Property(b => b.codigoCargo).HasColumnName("CARGO").HasConversion<string>();


            builder.HasOne(p => p.cargo)
               .WithMany(p => p.contratos)
               .HasForeignKey(p => p.codigoCargo);

            builder.HasOne(p => p.pessoa)
                .WithMany(p => p.contratos)
                .HasForeignKey(p => p.codigoPessoa);

        }
    }


Attention: to be sure, ignore <Pessoa> must be after modelBuilder.ApplyConfiguration (new ContratoMap ());
