### ISSUE TITLE
Sqlite AutoIncrement bug when more than one primary key

### ISSUE THREAD

**Issue by Sina-Soltani** [dotnet/efcore#15497]
I have a problem with Auto Increment when a table has more than one primary key column.

Model:
```c#
public class Product
{
    public int Id { get; set; }
    public int Tr {get; set; }
}
```

Configuration:
```c#
modelBuilder.Entity<Product>()
                .HasKey(model => new { model.Id, model.Tr });

modelBuilder.Entity<Product>()
                .Property(model => model.Id)
                .ValueGeneratedOnAdd();
```

which creates this:
```
CREATE TABLE "Products" (
    "Id" INTEGER NOT NULL,
    "Tr" INTEGER NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id", "Tr")
)
```

As you see, the Id column is not AutoIncrement. But if I change the configuration to have only one primary key, then it works!

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite -Version 2.2.4

**Comment by wdegraaf-travel1** [comment]
Sqlite doesn't support autoincrement on composite primary keys.

https://stackoverflow.com/questions/6793205/auto-increment-on-composite-primary-key-sqlite3-python

**Comment by bricelam** [comment]
@wdegraaf-travel1 Is correct. This isn't possible in SQLite.

**Comment by bricelam** [comment]
Oh wait, you don't want it on two columns--just on Id. This scenario should be covered by #10228

**Comment by bricelam** [comment]
No wait, it's still not possible. You'd have to make the primary key in the database different from the primary key in the model.

**Comment by bricelam** [comment]
You might be able to get the behavior you want using [triggers](https://sqlite.org/lang_createtrigger.html).

**Comment by GeraudFabien** [comment]
My main problems is that i use SQLite as test DB and i want to create an empty schema using migration So it must be the same migration than mysql.

I'm looking for a temporary solution if you know one.

**Comment by kskalski** [comment]
Would something like ``b.Property(e => e.Id).HasDefaultValueSql("select max(rowid) + 1 from table");`` be on the right track to simulate the autoincrement functionality for column being part of complex primary key? I tried this, but EF Core didn't emit any value in ``INSERT`` statement for ``Id`` column (though I suspect it decided to skip it because value in the model was set to 0)

**Comment by kskalski** [comment]
> Would something like `b.Property(e => e.Id).HasDefaultValueSql("select max(rowid) + 1 from table");` be on the right track 

Ok, forget it - ``HasDefaultValueSql`` is for specifing expressions in column's ``DEFAULT`` schema section and sqlite will allow only "constant expressions" there (along with a few exceptions like ``CURRENT_TIMESTAMP``). So the approach of selecting current ``rowid`` for insert is still a viable solution (from sqlite SQL point of view - select subexpression works fine in ``VALUES`` section), but would need to be implemented in the provider by specially crafting value on ``INSERT``.
