### ISSUE TITLE
Fail to save child records by using EF Core 2.2.4 after upgrading .Net Core from 2.1.5 to 2.2.4

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#15507]
Moved from https://github.com/dotnet/core/issues/2641 filed by @Michaelwan777

----

Fail to save child records 

Hi! My project is developed by using .Net Core 2.1.5. Recently, I upgraded my project to 2.2.4. After the upgrading, searching performance becomes faster, which is nice. However, I realized that it failed to save multiple child records completely. It can only save the last record of multiple child records(There is no such serious case in 2.1.5) I'm still investigating the reasons for this bug.  

# General
.NET Core: From 2.1.5 to 2.2.4
OS: Win10
EF Core: 2.2.4

**Comment by ajcvickers** [comment]
@Michaelwan777 Can you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by Michaelwan777** [comment]
@ajcvickers Hi Arthur! Thank you for your response. I'm using dotnet core plus ef core in this project.

In Controller:
`	public IActionResult SaveOrder(Order order, string orderStatus)
		{
			FixUpCustomer(order);
			FixUpTrip(order);
			FixUpBookSupply(order);

private void FixUpBookItem(Order order)
		{
			var bookingItemList = new List<BookingItem>();
			foreach (var bookingItem in order.BookingItems)
			{
				if (bookingItem.SupplierId != 0)
				{
					bookingItem.OrderId = order.Id;
					bookingItem.ConfirmNum = order.ConfirmNum;
					bookingItem.SupplierType = _supplierRepository.Get(bookingItem.SupplierId).Type;
					bookingItem.Duration = (bookingItem.CheckOut - bookingItem.CheckIn).Days + 1;

					bookingItemList.Add(bookingItem);
				}
			}
			order.BookingItems = bookingItemList;
		}

		private void FixUpBookSupply(Order order)
		{
			var supplyBookingList = new List<SupplyBooking>();
			foreach (var supplyBooking in order.SupplyBookings)
			{
				if (supplyBooking.HotelId != 0)
				{
					supplyBooking.OrderId = order.Id;
					supplyBookingList.Add(supplyBooking);
				}
			}
			order.SupplyBookings = supplyBookingList;
		}

		private void FixUpCustomer(Order order)
		{
			var customerList = new List<Customer>();
			foreach (var customer in order.Customers)
			{
				if (!String.IsNullOrEmpty(customer.FirstName))
				{
					customer.OrderId = order.Id;

					string str_l = "";
					if (!String.IsNullOrEmpty(customer.LastName))
					{
						str_l = customer.LastName;
					}
					customer.FirstName = customer.FirstName.Replace(" ", "").ToUpper();
					customer.LastName = str_l.Replace(" ", "").ToUpper();

					if (customer.LastName != "" && customer.FirstName != "")
					{
						customer.FullName = (customer.LastName + "/" + customer.FirstName);
					}

					if (customer.LastName == "" && customer.FirstName != "")
					{
						customer.FullName = (customer.FirstName);
					}

					if (customer.LastName != "" && customer.FirstName == "")
					{
						customer.FullName = (customer.LastName);
					}


					customerList.Add(customer);
				}
			}
			order.Customers = customerList;
		}
`

In Repository:
`
public void Save(Order order)
		{
			if (order.Id == 0)
			{
				AddOrder(order);
			}
			else
			{
				UpdateOrder(order);
			}
		}

		private void AddOrder(Order order)
		{
			order.EntryDate = DateTime.Now;
			order.ConfirmNum = order.ConfirmNum.ToUpper();

			_context.Orders.Add(order);
			UpdateStartEnd(order, order);
			_context.SaveChanges();

		}

		private void UpdateOrder(Order order)
		{
			var existing = _context.Orders.FirstOrDefault(c => c.Id == order.Id);

			if (existing == null)
				throw new ArgumentOutOfRangeException($"order not exits { order.Id}");

			if (existing != null)
			{
				string OrderStatusPast = existing.OrderStatus;
				string OrderStatusNow = order.OrderStatus;
				order.EntryDate = existing.EntryDate;
				order.ConfirmNum = order.ConfirmNum.ToUpper();
				order.CreatorName = existing.CreatorName;

				_context.Entry(existing).CurrentValues.SetValues(order);

				UpdateChild(existing, order.Customers);
				UpdateChild(existing, order.Trips);
				UpdateChild(existing, order.SupplyBookings);
				UpdateChild(existing, order.BookingItems);

				UpdateStartEnd(existing, order);

				_context.SaveChanges();
			}
		}


		private void UpdateChild(Order existingOrder, List<Customer> newCustomers)
		{
			// Delete children
			foreach (var existingChild in existingOrder.Customers.ToList())
			{
				if (!newCustomers.Any(c => c.Id == existingChild.Id))
					_context.Customers.Remove(existingChild);
			}

			// Update and Insert children
			foreach (var childModel in newCustomers)
			{

				var existingChild = existingOrder.Customers
					.Where(c => c.Id == childModel.Id)
					.SingleOrDefault();

				if (existingChild != null)
				{
					// Update child
					_context.Entry(existingChild).CurrentValues.SetValues(childModel);
				}
				else
				{
					// Insert child 
					existingOrder.Customers.Add(childModel);
				}

			}
		}

		private void UpdateChild(Order existingOrder, List<Trip> newTrips)
		{
			// Delete children
			foreach (var existingChild in existingOrder.Trips.ToList())
			{
				if (!newTrips.Any(c => c.Id == existingChild.Id))
					_context.Trips.Remove(existingChild);
			}

			// Update and Insert children
			foreach (var childModel in newTrips)
			{

				var existingChild = existingOrder.Trips
					.Where(c => c.Id == childModel.Id)
					.SingleOrDefault();

				if (existingChild != null)
				{
					// Update child
					_context.Entry(existingChild).CurrentValues.SetValues(childModel);
				}
				else
				{
					// Insert child 
					existingOrder.Trips.Add(childModel);
				}
			}
		}

		private void UpdateChild(Order existingOrder, List<SupplyBooking> newSupplyBookings)
		{
			// Delete children
			foreach (var existingChild in existingOrder.SupplyBookings.ToList())
			{
				if (!newSupplyBookings.Any(c => c.Id == existingChild.Id))
					_context.SupplyBookings.Remove(existingChild);
			}

			// Update and Insert children
			foreach (var childModel in newSupplyBookings)
			{

				var existingChild = existingOrder.SupplyBookings
					.Where(c => c.Id == childModel.Id)
					.SingleOrDefault();

				if (existingChild != null)
				{
					// Update child
					_context.Entry(existingChild).CurrentValues.SetValues(childModel);
				}
				else
				{
					// Insert child 
					existingOrder.SupplyBookings.Add(childModel);
				}

			}
		}
`

In View:
I use 'HtmlHelpers.BeginCollectionItemCore' to add or delete the additional item append to the page by ajax call.

**Comment by ajcvickers** [comment]
@Michaelwan777 Can you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by Michaelwan777** [comment]
> @Michaelwan777 Can you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

Hi! The code aims to create/edit Order then create/edit/remove its child class(Customer, Trip, and SupplyBooking).

It works well if used .NET Core versions which are not newer than 2.2.0. But if .NET Core is updated to 2.2.X in the project, the code fails to work.

**Comment by ajcvickers** [comment]
@Michaelwan777 I can't run that code because there are many missing types that I would have to create myself and guess as to what they contain. In order for us to effectively investigate this issue we need something that we can run _without guessing what other code to add_ and it needs to clearly demonstrate the behavior you are seeing. The process can be further expedited by systematically trimming out all code that is not needed to reproduce the issue. This is how people generally arrive at a "small, runnable" repro.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
