### ISSUE TITLE
Nested or interleaved execution of no tracking query triggers concurrency guard exception

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#15518]
We uncovered this while working on a database sample for ML.NET at https://github.com/dotnet/machinelearning-samples/pull/295/files. 

Repros with EF Core 3.0.0-preview4 and 2.2, and it does not repro in EF6.

I would expect this to be a supported scenario if the underlying database supports MARS:

``` csharp
using (var context = new MyIssueTrackingContext(connectionString))
{
    var repos = context.Repos.AsNoTracking().OrderBy(r => r.Id);
    foreach (var a in repos)
    {
        foreach (var b in repos) // throws
        {
            // do work
        }
    }
}
```

But it throws:

> Unhandled Exception: System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe. This could also be caused by a nested query being evaluated on the client, if this is the case rewrite the query avoiding nested invocations.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_FastQuery\>d__3`1.MoveNext()
   at InterleavedQueries.Program.Main(String[] args) in C:\Users\divega\source\repos\PortEF6ToCore\Program.cs:line xx

Note that there is no rentrancy on any method or more than one thread trying to do work on the same `DbContext` instance, but just a MARS scenario.

Full repro:

``` csharp
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace InterleavedQueries
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyIssueTrackingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.Repos.Add(new Repo { Name = "Blah", CreatedOn = DateTime.Now });
                context.SaveChanges();
                var repos = context.Repos.AsNoTracking().OrderBy(r => r.Id);
                foreach (var a in repos)
                {
                    foreach (var b in repos)
                    {
                    }
                }
            }
        }
    }

    public class MyIssueTrackingContext : DbContext
    {
        public DbSet<Repo> Repos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"server=(localdb)\mssqllocaldb;database=MyIssueTracking;Integrated Security=true;ConnectRetryCount=0;MultipleActiveResultsets=true");
        }
    }
    
    public class Repo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string CreatedByName { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
```

**Comment by ajcvickers** [comment]
Covered by #14534
