### ISSUE TITLE
Inheritance redundancy column

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#1551]
I create 3 entities, for example : 

class A {
public int Id {get; set }
public string Name {get; set; }
}

class B : A {
public string Location {get; set;}
}

class C : A {
public int Number {get; set;}
}

I run the command : k ef migration add initial, and entity framework generate 3 tables :
Table A with the columns Id, Name.
Table B with the columns Id, Name, Location.
Table C with the columns Id, Name, Number.

Don't create 1 table with column discriminator, what is the guideline for the inheritance code first implementation ?

**Comment by rowanmiller** [comment]
Inheritance is one of the features that has not been implemented yet. The work is being tracked by this work item https://github.com/aspnet/EntityFramework/issues/247.
