### ISSUE TITLE
Group By - simple case

### ISSUE THREAD

**Issue by yahorsi** [dotnet/efcore#15523]
Hi Guys, we use 2.2.4 EF and having problem with simplest group by. 
The one below EF wants to evaluate on the client and I have no clue why.
If I select just Id it works ok.

from f in Context.Flights
group f by f.Id into fg
select fg

Is it supposed to work and we do something wrong?
If now, will this be supported in 3.0?

Thanks!

**Comment by smitpatel** [comment]
Your group by query while valid in LINQ cannot be converted to SQL Group By. EF Core does the ordering and generate the appropriate groups on client side. That client translation is working in already in EF Core and will continue to work in 3.0
