### ISSUE TITLE
Suggestion about NuGet Sources

### ISSUE THREAD

**Issue by WillBaldwin** [dotnet/efcore#1552]
I realize that this suggestion is out of context for EntityFramework but I am hoping this suggestion makes it to the right people eventually.  I and my team have been testing and evaluating vNext for awhile now and one issue keeps coming back to bite us over and over again: NuGet Package Sources.

My Visual Studio 2015 environment now has four distinct NuGet package sources and I have to switch what source I need based on the project or solution I have open.  Do I need nightly builds, or do I need beta1, perhaps beta 2 nuget.org or myget.org... Consider I might have two instances of Visual Studio 2015 open at the same time and I need one package source for one and  different one for the other.  

Would there not be an advantage to being able to specify the NuGet source in the project.json?

Example: You might have a theoretical MusicStore solution distribution on GitHub and one project requires the production NuGet source and another project demonstrating new libraries requires a different beta package source.  There is no standard place to specify the required package source for the users of the distribution.

It would seem to be a big time saver for people who will in the future regularly bounce between production release NuGet sources and nightly build NuGet sources.

**Comment by Eilon** [comment]
@WillBaldwin this would be good to discuss in https://github.com/aspnet/Home. Having said that, you can have a NuGet.config file in whatever project you want to specify particular NuGet feeds. This is done in pretty much all the repos here, for example, https://github.com/aspnet/EntityFramework/blob/dev/NuGet.Config .

**Comment by WillBaldwin** [comment]
Here is the thing...  If the packages are incompatible with the selected KRE the IDE does not handle the incompatibility well i.e. the developer has very few (almost none) clues as to why Roselyn is unhappy with references.  Packages are specified in the project.json and the target KRE is specified in the project properties.  There seems to be a disconnect between the two very interdependent configuration settings and if set wrong the behavior is undesirable.

**Comment by rowanmiller** [comment]
@WillBaldwin could you start up this conversation in https://github.com/aspnet/Home so that the appropriate folks see it.

**Comment by WillBaldwin** [comment]
moved to  https://github.com/aspnet/Home
