### ISSUE TITLE
Renaming default aliases for tables/columns

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#15545]
Is there a way the provider can rename (correctly) the aliases for tables/columns EFCore used for the query?

Example:
```sql
Table1 AS "t"
    LEFT JOIN Table2 AS "t.Table2" ON "t"."idTable2" = "t.Table2"."id"
    LEFT JOIN Table3 AS "t.Table2.Table3" ON "t.Table2"."IdTable3" = "t.Table2.Table3"."id" 
```

Can I somehow change i.e. the `t.Table2` or `t.Table2.Table3`?

I know I can change the names while creating the query, but that will make higher parts of EFCore unhappy, because it will not be able to find what it expects in the reader.

Reason:
Firebird has limited length for identifiers and especially while in join, the names of tables are just concatenated together and it's easy to overrun this limit.

**Comment by smitpatel** [comment]
Prior to 3.0, providers need to set this property to limit the length for identifiers.
https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Query/RelationalQueryCompilationContext.cs#L94

In 3.0, alias-ing is going to be much different but it will allow providers to specify max length in similar fashion.

**Comment by cincuranet** [comment]
Thanks, that solves it for me (at least at the moment for 2.2 :)).
