### ISSUE TITLE
[VERY LOW] startvs.cmd opens Visual Studio 2017 even if Visual Studio 2019 available

### ISSUE THREAD

**Issue by jzabroski** [dotnet/efcore#15575]
# Describe what is not working as expected.
Running the directions on the Getting Started wiki page should work, regardless of how many versions of Visual Studio I have installed.

```
d:\source\GitHub\EntityFrameworkCore\ > startvs.cmd EFCore.sln
```

This appears to happen if you have Visual Studio 2019 installed, and then a Visual Studio 2017 Update gets released and you apply the 2017 update.

# Workaround
In the Start Menu, type "default apps".  Scroll down to "Choose default apps by file type".  Scroll down to .sln - select the Visual Studio Version Selector tool.

# Additional Notes
This is a bit strange, since ASSOC and FTYPE commands in cmd seem to return the correct information (as far as I am unaware - not an expert).

```
C:\Users\john.zabroski>assoc .sln
.sln=VisualStudio.Launcher.sln

C:\Users\john.zabroski>ftype VisualStudio.Launcher.sln
VisualStudio.Launcher.sln="C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\VSLauncher.exe" "%1"
```

The following loads the correct version of Visual Studio, but upon opening the project, it doesn't seem to load any of the projects:
```
"C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\VSLauncher.exe" d:\source\GitHub\EntityFrameworkCore\EFCore.sln
```

This is bizarre, since, according to the documentation on CMD `start` command, it should use the FTYPE value.

**Comment by ajcvickers** [comment]
@jzabroski By design, it opens whatever app the default association is for .sln files.

**Comment by jzabroski** [comment]
Figured out the full work-around. - re-run build.cmd, then run startvs.cmd EFCore.sln
It seems the latest Visual Studio 2017 update somehow changed up the dotnet runtime.  Could be a "dotnet rollforward" issue but I'm not smart enough to understand rollforward.
