### ISSUE TITLE
Query :: improve expression tree formatter

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1558]
We currently have ExpressionPrinter and Remotion.Linq.Clauses.ExpressionTreeVisitors.FormattingExpressionTreeVisitor that allows visualizing query trees. Relinq one is great but the formatting on it is bad - we should consider improving on this (maybe contributing to relinq?) so that debugging queries is easier

**Comment by rowanmiller** [comment]
We probably won't do anything in this area unless there is significant value. At this stage there is so much other higher priority work we don't see this as something we'd ever really get to.

**Comment by maumar** [comment]
this was opened per discussion with @divega  here: https://github.com/aspnet/EntityFramework/pull/1438

Will reopen for now - feel free to close again if you guys decide to override the decisions from that discussion.

**Comment by rowanmiller** [comment]
We discussed in triage this morning :smile:
