### ISSUE TITLE
QueryRewrite: clean up "ToOrdered" method calls after nav rewrite is done

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15591]
Nav rewrite introduces ToOrdered methods when the IOrderedEnumerable/Queryable is lost due to pending selector application at the end of nav rewrite.

We should be able to safely remove those - on top level the type doesn't really matter and we don't support order by as the final operation inside a subquery - all collections need to be buffered using ToList etc, which will remove IOrderedQueryable anyway.

**Comment by smitpatel** [comment]
Fixed in 3.0 when I rewrote nav rewrite.
