### ISSUE TITLE
Microsoft.EntityFramework.Sqlite 3.0.0-preview4 on NetStandard 2.1 - compilation of IAsyncEnumerable fails

### ISSUE THREAD

**Issue by manzanotti** [dotnet/efcore#15597]
Describe what is not working as expected.

Upgrading the package from preview3 to preview4, the project no longer compiles. The errors all appear to be around missing methods on IAsyncEnumerable:

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Error	CS0656	Missing compiler required member 'System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync'	IAsyncEnumerableTest
Error	CS0656	Missing compiler required member 'System.IAsyncDisposable.DisposeAsync'	IAsyncEnumerableTest
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.ValueTask`1..ctor'	IAsyncEnumerableTest
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.ValueTask..ctor'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetStatus'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.OnCompleted'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.IValueTaskSource`1.GetResult'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.IValueTaskSource`1.GetStatus'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.IValueTaskSource`1.OnCompleted'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.IValueTaskSource.GetResult'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.IValueTaskSource.GetStatus'	IAsyncEnumerableTest	
Error	CS0656	Missing compiler required member 'System.Threading.Tasks.Sources.IValueTaskSource.OnCompleted'	IAsyncEnumerableTest

```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

Project file:
```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.0.0-preview4.19216.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>

  <Target Name="AddAssemblyAliasToReactiveAsync" AfterTargets="ResolveAssemblyReferences" Condition=" '$(TargetFramework)' != '' AND ( '$(TargetFramework)' == 'netcoreapp3.0' OR '$(TargetFramework)' == 'netstandard2.1' ) ">
    <ItemGroup>
      <ReferencePath Condition=" '%(FileName)' == 'System.Interactive.Async' ">
        <Aliases>reactive</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
</Project>
```

Note that it has the current fix for the clash in Async namespaces caused by the SQLite package. I've tried compiling the project without this in, and it fails due to the clash still.

The class:

```
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace IAsyncEnumerableTest
{
    public class AsyncService
    {
        public async IAsyncEnumerable<JObject> Get()
        {
            yield return await Call();
        }

        private async Task<JObject> Call()
        {
            return await Task.FromResult<JObject>(null);
        }
    }
}
```

If I downgrade the SQLite package to preview3, it compiles.

### Further technical details
EF Core version: (found in project.csproj or packages.config)
3.0.0-preview4.19216.3
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Microsoft.EntityFrameworkCore.Sqlite.Core
Operating system: 
Windows 10 Pro build 17763
IDE: (e.g. Visual Studio 2017 15.4)
Visual Studio 2019 16.1.0 Preview 2.0

**Comment by ajcvickers** [comment]
@manzanotti This is a point-in-time situation with the previews while we work to remove our dependency on the old IX-Async package and start using built-in `IAsyncEnumerable` support. We hope to do this for preview6, but it may land in preview7 instead.

**Comment by manzanotti** [comment]
@ajcvickers Thanks for the reply. I'll stick with preview 3 for now then. May I request that the release notes of whichever preview you get this working in do explicitly mention this is fixed?
