### ISSUE TITLE
Support for custom configuration in DbContextOptions

### ISSUE THREAD

**Issue by mikary** [dotnet/efcore#1560]
The mechanism for loading custom configuration settings from the `DbContextOptions` is not easily discoverable. If we want users to be able to fetch their own settings in a `DbContext` without registering an `IOptions<T>` or manually adding settings into the service provider, we should consider providing a simpler method for accessing these settings.

The `DbContextOptions` provides a dictionary containing the `DbContext` specific settings from `Configuration` but the user would be required to cast the instance to `IDbContextOptions` (in the M.D.E.Infrastructure namespace) or perhaps an `IAccessor<T>` after API review.

``` cs
IReadOnlyDictionary<string, string> RawOptions { get; [param: NotNull] set; }
```

**Comment by ajcvickers** [comment]
Closing since DbContextOptions now no longer has any connection to the configuration or options infrastructure and does not have any concept of raw values or dictionaries.
