### ISSUE TITLE
Lambda versions for Skip(), Take(), etc.

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1561]
In EF6 [we added lambda versions of Skip() and Take()](https://entityframework.codeplex.com/workitem/197) as extensions to IQueryable<T>. These allow for paging queries that are parameterized, query plans that are reusable and a LINQ experience that respects the contract of closures. 

We are making the behavior of EF7's LINQ implementation closer to EF6 in the sense that constants in the query become constants in the SQL so it becomes important that we do this here too.

**Comment by divega** [comment]
As per CodePlex [#1446](http://entityframework.codeplex.com/workitem/1446) the same principle applies to other LINQ operators such as ElementAt(), Contains() and DefaultIfEmpty().

**Comment by smitpatel** [comment]
Skip/Take are already parametrized in EF Core.

**Comment by ajcvickers** [comment]
Already fixed a different way.

**Comment by codymullins** [comment]
@ajcvickers is it safe so assume we no longer need the lambda version for the performance improvements that existed in EF6?

**Comment by ajcvickers** [comment]
@codymullins Correct.
