### ISSUE TITLE
Method not found while Scaffolding in a brand new project

### ISSUE THREAD

**Issue by aleksamagicka** [dotnet/efcore#15625]
I created a brand new project ASP Net Core project with auth and added two model classes, `StudentGroup` and `Student`, which can be found in the [repro project](https://drive.google.com/open?id=1O0Oj7Qjjf_c6veOiGs7rAWFn6I4Sqdup). The `StudentGroup` contains a name and a List of `Student`s, which should work (One to Many).

I ran a scaffold to generate the controller and views, and it failed with the following error message:

`There was an error running the selected code generator: 'Method not found: 'Boolean Microsoft.EntityFrameworkCore.Metadata.IProperty.getIsShadowProperty()'.'`

### Further technical details
EF Core version: 3.0.0-preview4.19216.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (the default one)
Operating system: Windows 7 x86
IDE: Visual Studio 2019. 16.0.3

**Comment by ajcvickers** [comment]
This is an issue with ASP.NET scaffolding. It is tracked here: https://github.com/aspnet/Scaffolding/issues/984
