### ISSUE TITLE
Feature: Plugin Interface for Models

### ISSUE THREAD

**Issue by alfkonee** [dotnet/efcore#1563]
I was just working on project that has to use a plugin architecture ie the application will have a main core with multiple plugins extending the features for the application. Each plugin will have some data models that extend the core's EF Model.
I would like to suggest a feature that will make it simple to append Model and Relationship Definitions to a current DBContext
I know this is a long shot but will really appreciate if you take it into consideration

**Comment by divega** [comment]
@alfkonee Thanks for the suggestion. Could you ellaborate more on how you envision this would work?

**Comment by Jetski5822** [comment]
@alfkonee Are you talking about not knowing what models will exist in the DbContext until runtime?

**Comment by alfkonee** [comment]
Hey there guys sorry about the long silence had a bad cold these past few days. Well the feature I suggested is exactly as shown in  @Jetski5822  comment

**Comment by divega** [comment]
I found this item sitting on my plate for investigation, but I think it either belongs in the backlog or closed, so clearing up milestone for re-triage.

The main point I gather from the conversation is to make it easy to have base models that are extended dynamically/programmatically, which is a valid and important scenario. 

However, some of this is already possible, e.g. applications using ASP.NET Identity do it all the time by deriving from `IdentityDbContext` and overriding `OnModelCreating()`, etc. and customers can invoke reflection code to create an EF model as in Rowan's blog post. Although this is not necessarily as easy as it could be, lacking specifics on how to actually make it easier, I am not sure it makes sense to keep this open.

On the other hand some richer scenarios could be enabled by shadow entities which is already covered in #749.
