### ISSUE TITLE
Remove extra model annotations from snapshot

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#15675]
Put all the annotations that should be removed in one place that `CSharpSnapshotGenerator`, `MigrationsCodeGenerator` and `CSharpDbContextGenerator` use.

And add tests for ignored model annotations

**Comment by ajcvickers** [comment]
Putting this on the backlog to make sure that we have test coverage and that the correct annotations are included in the snapshot.

Note that in triage we were not 100% sure whether MaxIdentifierLength should be in the snapshot or not. There may have been MySQL bugs when it wasn't there.

**Comment by roji** [comment]
Poaching to do as part of the work for #21210
