### ISSUE TITLE
Include lost on DbSet<Entity>

### ISSUE THREAD

**Issue by christophedemey** [dotnet/efcore#15672]
Hi

My include is lost if implemented in the following manner, the related entities are not loading.
```
 using (EventBrokerServiceContext context = db.Invoke())
{
    DbSet<DbRegistrationEntry> dbset = context.Set<DbRegistrationEntry>();
    dbset.Include("Execution");
    returnValue = dbset.Where(queryExpression).ToList();
}
```

In the end product i need to be able to receive a List<string> which contains all the neccessary includes.
So i figured this would be great to just iterate over a list of string and add the includes.
```
requiredIncludes.ForEach(include => entitySet.Include(include));
```

### Steps to reproduce
NOK :
```c#
using (EventBrokerServiceContext context = db.Invoke())
{
    DbSet<DbRegistrationEntry> dbset = context.Set<DbRegistrationEntry>();
    dbset.Include("Execution");
    returnValue = dbset.Where(queryExpression).ToList();
}
```
OK :
```c#
using (EventBrokerServiceContext context = db.Invoke())
{
    DbSet<DbRegistrationEntry> dbset = context.Set<DbRegistrationEntry>();
    returnValue = dbset.Include("Execution").Where(queryExpression).ToList();
}
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.2.4
Operating system: Windows 10
IDE: Visual Studio 2019 16.02

**Comment by ajcvickers** [comment]
@christophedemey In common with the way pretty much everything in LINQ works, the `Include` method does not mutate the query passed to it, but rather returns a new query modified appropriately from the previous query. In other words, this:
```C#
dbset.Include("Execution");
```
is essentially a no-op because the query with `Include` applied to it is never used.

In your example, typically something like this is needed:
```C#
requiredIncludes.ForEach(include => query = query.Include(include));
```

**Comment by christophedemey** [comment]
hi  @ajcvickers 

Yeah i found out 5 minutes ago, sorry for bothering you :)
