### ISSUE TITLE
Allow users to check connection string used by database update operation

### ISSUE THREAD

**Issue by ruimaciel** [dotnet/efcore#15689]
A database update operation fails, quite naturally, if the project isn't configured correctly and ends up passing a wrong connection string (i.e., wrong choice/combination of host/port/username/password/etc).  

This problem might occur due to a myriad of reasons due to the many ways that project/environment settings might determine the connection string, which might pose a challenge to developers to troubleshoot the problem.  As a concrete example, using an invalid connection string with some database providers can trigger connection timeout exceptions.

One way to help developers debug this type of problems is to enable them to check which connection string is being used by EFCore to attempt a connection.  If developers are able to check which connection string is being used (say, by outputting it to the log when dotnet ef database update is called with the --verbose flag) then all they have to do is rerun the database update procedure and check the connection string to get additional clues to what might be wrong with their setup.

**Comment by ajcvickers** [comment]
Triage: Follow up with @bricelam

**Comment by bricelam** [comment]
Using `--verbose` will show a line like the following:

> Migrating using database 'MyDatabase' on server '(localdb)\MSSQLLocalDB'.

We don't show the full connection string because passwords.

**Comment by ajcvickers** [comment]
@ruimaciel Is the database name and server sufficient? Or is there other information in the connection string that would be useful?

**Comment by ruimaciel** [comment]
@ajcvickers having access to the hostname and port number would already be very helpful.  Some database drivers also require connection parameters that would be nice to check (say, npgsql's username, database, [etc](https://www.npgsql.org/doc/connection-string-parameters.html)), but I'm sure this sort of corner case is hard to generalize.

**Comment by ajcvickers** [comment]
Putting this on the backlog to consider adding a specific command that returns the full connection string being used.

**Comment by ruyd** [comment]
hey, can I help with this?

**Comment by AndriySvyryd** [comment]
@ruyd Sure. But just so you know, we'll start locking down on features soon, so this might have to ship in 3.1 instead of 3.0

**Comment by SARAVANA1501** [comment]
Hi Team, 

I just looked the code, In 'RelationalLoggerExtensions.cs', MigrateUsingConnection function is actually writing the log. Can we add new command? or in --verbose command?

Guide me on this.
Thanks.

**Comment by GrizzlyEnglish** [comment]
Hey!

Looks like the previous people before me have decided not to work this ticket; is this still wanted? If so, may I have a crack at it? 

Thanks!

**Comment by GrizzlyEnglish** [comment]
So, went to open PR and noticed I was supposed to mention _how_ I planned on fixing this issue prior to creating a PR.

My plan of attack:

Add `ConnectionString` to `ContextInfo` ; which gets set during the `GetContextInfo` design time operation. I have also added a test to verify the design time operation getting the connection string.

So when a user types `dotnet ef dbcontext info` they will get

```
Provider Name: <provider>
Database Name: <db>
Data Source: <source>
Connection String: <connection>
Options: <options>
```

One problem I am having, however, is running `dotnet-ef` and loading up the newly created design time dll. When I add the dlls to my repository with a premade project to spit out the `dbcontext info` it is failing to load `System.Runtime` and am unable to figure out why it can't load that - or if it's a generic dependency issue. If anyone has any pointers that would be amazing.

Anyway, know you all are busy with the impending 6.0 release.

Thanks!

**Comment by ajcvickers** [comment]
@GrizzlyEnglish I discussed with the team, and we're not 100% sure what to do about the password. @bricelam will take a look, but right now we're heads-down working on the 6.0 release, so we will get back to you after that.

**Comment by GrizzlyEnglish** [comment]
@ajcvickers Understood. Thanks for the reply! I figured you were probably extremely busy. I have it "done" and will hold until later date. Thanks again

**Comment by roji** [comment]
Re the passwords, most database providers remove it from the connection string when a DbConnection is opened, unless `Persist Security Info` is true (it's a sort of weird "security" feature). So it's probably safe to print the connection string as-is as long as we extract it from the DbConnection after having opened it.

**Comment by roji** [comment]
@GrizzlyEnglish my above comment was a possible direction, but we first need to see that it makes sense (e.g. that most known provides actually behave in this way). We're also busy stabilizing EF Core 6.0, and it's too late to get this in (the release is now open for bug fixes only), so it's likely to be a while before we can give this our attention.

**Comment by GrizzlyEnglish** [comment]
@roji My bad, guess I got a bit overzealous there and misinterpreted the response. Thanks!
