### ISSUE TITLE
Support entity fields directly referenced in LINQ 

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#157]

**Comment by ajcvickers** [comment]
Assigning back to triage. I'm not sure what this means so I'm not sure if it is done by the field mapping changes or not.

**Comment by anpete** [comment]
@ajcvickers Can't remember exactly either, but suspect it means that I should be able to reference a field within a LINQ query expression (assuming it is accessible) and have the query compiler resolve it to the correct metadata property. We may choose to say that you have to use EF.Property for now...

**Comment by divega** [comment]
**Triage:** we believe for now it is enough to support `EF.Property<T>(name)`. Closing. We will revisit if we get enough feedback on accessing fields directly. Note that is not just query but it would also involve referencing a field in model building.
