### ISSUE TITLE
Build Initialize problem, possibly related to commands.csproj

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#1570]
I've been trying to do a from-scratch walk through of getting and building the source even though I've successfully done this in the past.
I'm cloning from the current source. I have tried this on a machine with VS2013 (and no VS2015 at all) and on a VM with VS2015 RC5. It downloads all of the packages without problem. When it gets to the point where its trying to run MSBuild, it fails with a file not found. I thought it was because the command is MSBuild\14.0 when I was running on the box with VS2013 only. But it is happening on the VS2015 VM and so my attention returned to another bit of info in the file not found error: 
C:\Users\Julie\Documents\GitHub\EntityFramework\tools\EntityFramework.targets(96,5): error :
 No packages found.
 [C:\Use
rs\Julie\Documents\GitHub\EntityFramework\src\EntityFramework.Commands\EntityFramework.Commands.csproj]

Here is more detail about the error:
warn: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
verbose: Stack trace:
   at View10a2fb6296f041c6b340ea91d546c678.<RenderViewLevel0>b__67() in c:\Users\Julie\AppData\Local\Temp\76dba1a49ea844
3480a24f37ae12c0d0-1.cs:line 9148
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View10a2fb6296f041c6b340ea91d546c678.<RenderViewLevel0>b__44() in c:\Users\Julie\AppData\Local\Temp\76dba1a49ea844
3480a24f37ae12c0d0-1.cs:line 1282
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by julielerman** [comment]
I created a completely new vm and was able to run this. Do you think the fact that I already had various solutions using EF7 in NET and EF7 in K runtime could have to do with the hours and hours of wheel spinning? I'll close the issue but still want to know if down the build process is only recommended on clean KRE free machines.

**Comment by bricelam** [comment]
I wonder if it was caused by the recent renames in ASP.NET 5. They required everyone moving from build to build to manually delete environment variables and various files. I'm not sure if there's any documentation on exactly what needs to be done to get an existing machine back into a usable state...

**Comment by julielerman** [comment]
I do worry that others may hit this but how many people are doing this kind of experimentation? I'd just hate for someone else to waste gobs of time trying to correct this problem thinking, like I did, that I was doing something wrong.
