### ISSUE TITLE
Bad default database for SqlClient

### ISSUE THREAD

**Issue by lukewaters** [dotnet/efcore#1571]
If no database is specified in the connection string for SqlServer, SqlClient defaults to master. It is unlikely that this is what the user intended and EF should either block or provide a more appropriate default in this scenario.  In EF6, the default database was constructed from the DbContext name.

**Comment by rowanmiller** [comment]
If no database is specified then the user's default database is used. This is typically 'master' in the same what that the default schema is 'dbo' but it can be changed.
![image](https://cloud.githubusercontent.com/assets/4741851/6157947/7e6a922e-b1fa-11e4-9740-e76d14443cf8.png)

Given that this is built in functionality of SQL Server we don't want to limit it.
