### ISSUE TITLE
QueryRewrite: remove redundant null semantics terms involving non-null parameters once we know parameter values

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15722]
Currently when performing null semantics rewrite we assume all parameters are nullable. This is because at that point we don't have the parameter values. 

We should run optimizations after the values are known and simplify fragments like `@prm IS NULL`, `@prm IS NOT NULL` once we know if the parameters are actually null or not.

**Comment by roji** [comment]
Here's a requirement from the PostgreSQL side...

Thanks to PostgreSQL's fully support for arrays, we can translate the following:

```c#
var ids = new[] { 1, 2, 3 };
var customers = ctx.Customers.Where(c => ids.Contains(c.Id)).ToList();
```

Into the following:

```sql
SELECT * FROM customers WHERE id = ANY (@ids);
```

This obviates doing expansion of parameters into constants at runtime. The one place where this fails is if there's a null somewhere inside `ids`; to preserve null semantics, we'd need to translate to:

```sql
SELECT * FROM customers WHERE id = ANY (@ids) OR id IS null;
```

In other words, I'd ideally be able to cache to commands based on whether the array parameter's value contains a null anywhere.
