### ISSUE TITLE
Query :: Value cannot be null thrown for multi-include query

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1573]
Repro:

```
    public class Level1
    {
        public int Id1 { get; set; }
        public string Name { get; set; }

        //public Level2 OneToOne_Required_PK { get; set; }
        public Level2 OneToOne_Optional_PK { get; set; }

        //public Level2 OneToOne_Required_FK { get; set; }
        //public Level2 OneToOne_Optional_FK { get; set; }

        public ICollection<Level2> OneToMany_Optional { get; set; }
    }

    public class Level2
    {
        public string Id2 { get; set; }
        public string Name { get; set; }

        public int Level1_Required_Id { get; set; }
        public int? Level1_Optional_Id { get; set; }

        public Level1 OneToOne_Required_PK_Inverse { get; set; }
        public Level1 OneToOne_Optional_PK_Inverse { get; set; }
        //public Level1 OneToOne_Required_FK_Inverse { get; set; }
        //public Level1 OneToOne_Optional_FK_Inverse { get; set; }

        public Level1 OneToMany_Optional_Inverse { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Level1> LevelOne { get; set; }
        public DbSet<Level2> LevelTwo { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Level1>().Key(e => e.Id1);
            modelBuilder.Entity<Level2>().Key(e => e.Id2);

            modelBuilder.Entity<Level1>().Property(e => e.Id1).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id2).GenerateValueOnAdd(false);

            //modelBuilder.Entity<Level1>().HasOne(e => e.OneToOne_Required_PK).WithOne(e => e.OneToOne_Required_PK_Inverse).ReferencedKey<Level1>(e => e.Id1).Required(true);
            //modelBuilder.Entity<Level1>().HasOne(e => e.OneToOne_Optional_PK).WithOne(e => e.OneToOne_Optional_PK_Inverse).ReferencedKey<Level1>(e => e.Id1).Required(false);

            //modelBuilder.Entity<Level1>().HasOne(e => e.OneToOne_Required_FK).WithOne(e => e.OneToOne_Required_FK_Inverse).ForeignKey<Level2>(e => e.Level1_Required_Id).Required(true);
            //modelBuilder.Entity<Level1>().HasOne(e => e.OneToOne_Optional_FK).WithOne(e => e.OneToOne_Optional_FK_Inverse).ForeignKey<Level2>(e => e.Level1_Optional_Id).Required(false);

            modelBuilder.Entity<Level1>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level2>().Property(e => e.Id2).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id2).GenerateValueOnAdd(false);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro1487", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {

            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var l1_01 = new Level1 { Id1 = 1, Name = "L1 01", };
                var l1_02 = new Level1 { Id1 = 2, Name = "L1 02", };
                var l1_03 = new Level1 { Id1 = 3, Name = "L1 03", };
                var l1_04 = new Level1 { Id1 = 4, Name = "L1 04", };

                var l2_01 = new Level2 { Id2 = "1", Name = "L2 01", };
                var l2_02 = new Level2 { Id2 = "2", Name = "L2 02", };
                var l2_03 = new Level2 { Id2 = "3", Name = "L2 03", };
                var l2_04 = new Level2 { Id2 = "4", Name = "L2 04", };

                var l1s = new[] { l1_01, l1_02, l1_03, l1_04, }.ToArray();
                var l2s = new[] { l2_01, l2_02, l2_03, l2_04, }.ToArray();

                ctx.LevelOne.AddRange(l1s);
                ctx.LevelTwo.AddRange(l2s);

                //l1s[0].OneToOne_Required_PK = l2s[0];
                //l1s[1].OneToOne_Required_PK = l2s[1];
                //l1s[2].OneToOne_Required_PK = l2s[2];
                //l1s[3].OneToOne_Required_PK = l2s[3];

                //l1s[0].OneToOne_Required_FK = l2s[3];
                //l1s[1].OneToOne_Required_FK = l2s[2];
                //l1s[2].OneToOne_Required_FK = l2s[1];
                //l1s[3].OneToOne_Required_FK = l2s[0];

                ctx.SaveChanges();

                l1s[0].OneToOne_Optional_PK = l2s[0];
                l1s[2].OneToOne_Optional_PK = l2s[2];

                //l1s[1].OneToOne_Optional_FK = l2s[2];
                //l1s[3].OneToOne_Optional_FK = l2s[0];

                l1s[0].OneToMany_Optional = new List<Level2> { l2s[1], l2s[3], };

                ctx.SaveChanges();
            }


            using (var ctx = new MyContext())
            {
                var results1 = ctx.LevelOne
                    .Include(e => e.OneToMany_Optional)
                    .ThenInclude(e => e.OneToMany_Optional_Inverse.OneToOne_Optional_PK)
                    .ToList();

                System.Console.WriteLine(results1);

                //var results2 = ctx.LevelOne
                //    .Include(e => e.OneToMany_Optional)
                //    .ThenInclude(e => e.OneToMany_Optional_Inverse.OneToOne_Optional_PK)
                //    .ToList();

                //System.Console.WriteLine(results2);
            }
        }
    }
```

exception:

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass30_0.
<IncludeNavigations>b__3(IEnumerable`1 ns, IQuerySource _) in D:\k\EntityFramewo
rk\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 210
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass55_0`
1.<BindNavigationPathMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs) in
 D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:
line 888
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCo
re[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3
memberBinder) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQuery
ModelVisitor.cs:line 950
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindNavigationPathMemb
erExpression[TResult](MemberExpression memberExpression, Func`3 memberBinder) in
 D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:
line 885
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<IncludeNavigations>b_
_30_2(<>f__AnonymousType2`2 <>h__TransparentIdentifier0) in D:\k\EntityFramework
\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 207
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(Que
ryModel queryModel, Type resultType) in D:\k\EntityFramework\src\EntityFramework
.Core\Query\EntityQueryModelVisitor.cs:line 204
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TR
esult](QueryModel queryModel) in D:\k\EntityFramework\src\EntityFramework.Core\Q
uery\EntityQueryModelVisitor.cs:line 100
   at Microsoft.Data.Entity.Relational.RelationalDataStore.<Query>b__12_0[TResul
t](QueryModel qm) in D:\k\EntityFramework\src\EntityFramework.Relational\Relatio
nalDataStore.cs:line 112
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey
key, Func`2 factory) in D:\k\EntityFramework\src\EntityFramework.Core\Utilities\
ThreadSafeDictionaryCache.cs:line 37
   at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd[TResult](QueryMode
l queryModel, Func`2 queryCompiler) in D:\k\EntityFramework\src\EntityFramework.
Core\Query\CompiledQueryCache.cs:line 23
   at Microsoft.Data.Entity.Relational.RelationalDataStore.Query[TResult](QueryM
odel queryModel) in D:\k\EntityFramework\src\EntityFramework.Relational\Relation
alDataStore.cs:line 102
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteCollection[T](Query
Model queryModel) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQ
ueryExecutor.cs:line 92
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQ
ueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(
QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult
](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.QueryableExtensions.IncludableQueryable`2.GetEnumerator() in D
:\k\EntityFramework\src\EntityFramework.Core\Extensions\QueryableExtensions.cs:l
ine 1355
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Repro1487.Program.Main(String[] args) in D:\Projects\Repro1487\Repro1487\P
rogram.cs:line 124

**Comment by maumar** [comment]
model was wrong, closing

**Comment by Mertsch** [comment]
@maumar Can you shortly elaborate what was wrong, I run into the same issue and I am out of ideas why
