### ISSUE TITLE
Cosmos: Translate Skip and Take

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#15734]
Support for OFFSET and LIMIT has been added to the SQL dialect. We should translate Skip and Take.

**Comment by Marusyk** [comment]
Seems it can be closed
![image](https://user-images.githubusercontent.com/9221694/97501732-7552d780-197a-11eb-9dbf-e7ebc88aa97a.png)

**Comment by smitpatel** [comment]
This was already done in first cut of query pipeline in cosmos.
