### ISSUE TITLE
Throw better exception for stale Fluent API builders

### ISSUE THREAD

**Issue by lugospod** [dotnet/efcore#15736]
**Problem:**
When multiple fields of single owned type are added to the class, then there is a problem with migration process - MyEntity containins multiple MyOwnedEntity fields. The seeding process throws an exception:

**Exception:**
System.InvalidOperationException: 'The entity of type 'MyEntity' is sharing the table 'my_entity' with entities of type 'MyEntity.FirstOE#MyOwnedEntity', but there is no entity of this type with the same key value '{Id: 1}' that has been marked as 'Added'.'

**Envirnoment:**
EF Core 2.2.4, EF Core Sqlite 2.2.4, .NET CORE 2.2, VS 2019

**Reproducible example:**
[(https://github.com/lugospod/TestEfCoreBuggy)]

**Debugging:**
When I went to debug the code I came to the following conclusion:

1. If you have multiple owned entities of same type, then the problem is with the one that FIRST called OwnsOne. So all of the other Owned instances will go smoothly through seeding process except the first one
2. Call to the method HasData (for seeding purposes) the owned entity that called the OwnsOne first is getting a different EntityType then the rest that follow after it (I inspected the types inside the HasData seeding method). The one that called the OwnsOne first got the following type ("EntityType:  MyOwnedEntity") but all of the other got a "specific" type such as this one "EntityType: EntityType: MyEntity.SecondOE#MyOwnedEntity" - but this I guess could be due to the fact that EF Core gave all of the other specific names to maintain uniqueness of types?
3. In the file MigrationsModelDiffer.cs there is call to targetEntityType.GetData() method. This method is trying to get the data for "EntityType: EntityType: MyEntity.FirstOE#MyOwnedEntity" and not "EntityType:  MyOwnedEntity"  which was used in the seeding process so it return 0 elements and then he exception is thrown due. 

For now, I suspect that there is an issue with types...but I wasn't able to determine the root cause yet...

Any hints on what can I do to avoid understanding the whole EF Core logic?

Tnx!

P.S. Here is a code sample that was used to reproduce the error:

My entity class that references Owned entities:
```
[Table("my_entity")]
    public class MyEntity
    {
        [Column("id", Order = 1)]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public MyOwnedEntity FirstOE { get; set; }
        public MyOwnedEntity SecondOE { get; set; }
    }
```
Definition of owned entity:
```
 public class MyOwnedEntity
    {
        public int? CodebookId { get; set; }
        [MaxLength(100)]
        public string Name { get; set; }
    }
```
Configuration for owned entities and seeding:
```
 public void Configure(EntityTypeBuilder<MyEntity> builder)
        {
            var ownershipFirst = builder.OwnsOne(p => p.FirstOE); // This one causes the error
            ownershipFirst.Property(c => c.CodebookId).HasColumnName("first_codebook_id"); ;
            ownershipFirst.Property(c => c.Name).HasColumnName("first_codebook_name"); ;

            var ownershipSecond = builder.OwnsOne(p => p.SecondOE);
            ownershipSecond.Property(c => c.CodebookId).HasColumnName("second_codebook_id");
            ownershipSecond.Property(c => c.Name).HasColumnName("second_codebook_name"); 

            builder.HasData(new MyEntity() { Id = 1 });

            ownershipFirst.HasData(new { MyEntityId = 1, CodebookId = 1, Name = "Test" });
            ownershipSecond.HasData(new { MyEntityId = 1, CodebookId = 2, Name = "Test2" });
        }
```

**Comment by ajcvickers** [comment]
Note for triage: the issue here is that the builders are stashed away, then when they are later used for `HasData` they do not have valid state because the model has changed underneath.

@lugospod You can workaround this by using the builders where they are declared. For example:

```C#
public void Configure(EntityTypeBuilder<MyEntity> builder)
{
    var ownershipFirst = builder.OwnsOne(p => p.FirstOE); // This one causes the error
    ownershipFirst.Property(c => c.CodebookId).HasColumnName("first_codebook_id"); ;
    ownershipFirst.Property(c => c.Name).HasColumnName("first_codebook_name"); ;
    ownershipFirst.HasData(new { MyEntityId = 1, CodebookId = 1, Name = "Test" });

    var ownershipSecond = builder.OwnsOne(p => p.SecondOE);
    ownershipSecond.Property(c => c.CodebookId).HasColumnName("second_codebook_id");
    ownershipSecond.Property(c => c.Name).HasColumnName("second_codebook_name"); 
    ownershipSecond.HasData(new { MyEntityId = 1, CodebookId = 2, Name = "Test2" });

    builder.HasData(new MyEntity() { Id = 1 });
}
```
Or more idiomatically:
```C#
public void Configure(EntityTypeBuilder<MyEntity> builder)
{
    builder.OwnsOne(
        p => p.FirstOE,
        b =>
        {
            b.Property(c => c.CodebookId).HasColumnName("first_codebook_id");
            b.Property(c => c.Name).HasColumnName("first_codebook_name");
            b.HasData(new {MyEntityId = 1, CodebookId = 1, Name = "Test"});
        });

    builder.OwnsOne(
        p => p.SecondOE,
        b =>
        {
            b.Property(c => c.CodebookId).HasColumnName("second_codebook_id");
            b.Property(c => c.Name).HasColumnName("second_codebook_name");
            b.HasData(new {MyEntityId = 1, CodebookId = 2, Name = "Test2"});
        });

    builder.HasData(new MyEntity() { Id = 1 });
}
```

**Comment by lugospod** [comment]
Thank you very much for the workaround ... I lost quite a lot of time on this one :(

**Comment by AndriySvyryd** [comment]
Note to implementor: We should throw a better exception when the builder is stale. Related to https://github.com/aspnet/EntityFrameworkCore/issues/11108.

**Comment by smitpatel** [comment]
Same as #13519
