### ISSUE TITLE
Query: improve translation of StartsWith/EndsWith

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15730]
In EF6 we had a specific translation that took advantage of sargability

```sql
SELECT [f].[FirstName]
FROM [FunkyCustomers] AS [f]
WHERE (([f].[FirstName] LIKE [f].[FirstName] + N'%') AND (LEFT([f].[FirstName], LEN(@__prm3_0)) = @__prm3_0)) OR (@__prm3_0 = N'')
```

To achieve that translation we explicitly disabled null semantics processing for the translated sql fragment. In the new pipeline we want to avoid special casing this, so the query we generate *looks* significantly worse:

```sql
SELECT [f].[FirstName]
FROM [FunkyCustomers] AS [f]
WHERE (([f].[FirstName] LIKE [f].[FirstName] + N'%') AND ((((LEFT([f].[FirstName], LEN(@__prm3_0)) = @__prm3_0) AND (LEFT([f].[FirstName], LEN(@__prm3_0)) IS NOT NULL AND @__prm3_0 IS NOT NULL)) OR (LEFT([f].[FirstName], LEN(@__prm3_0)) IS NULL AND @__prm3_0 IS NULL)) AND @__prm3_0 IS NOT NULL)) OR ((@__prm3_0 = N'') AND @__prm3_0 IS NOT NULL)
```

We should simplify some of this, especially once we know the value of parameters, and see if what's left has bad performance

**Comment by ajcvickers** [comment]
@maumar to close as duplicate

**Comment by ajcvickers** [comment]
Pinging @maumar

**Comment by maumar** [comment]
dupe of https://github.com/aspnet/EntityFrameworkCore/issues/15722
