### ISSUE TITLE
Error message is unclear when publish StarterWeb to Azure without a linked database

### ISSUE THREAD

**Issue by balachir** [dotnet/efcore#1574]
1. New Starter Web (CTP 6)
2. Publish the project to Azure, do not create a linked database during Azure Website creation (let's say I forgot)
3.  Publish is successful. After publish successfully, IE will launch site, click 'Register'.

ACTUAL
![image](https://cloud.githubusercontent.com/assets/8246794/6120152/eff4842e-b086-11e4-9654-f6e8defc7afa.png)

EXPECTED
Error message that indicates more clearly what's wrong with Register. Something like "Unable to connect to database"

**Comment by rowanmiller** [comment]
We should look into this and see if this is an exception we could catch and wrap with something more helpful. We should look at failure to connect in general because the typical SQL Server 'failed to login' message when the database doesn't exist isn't very clear either.

**Comment by rowanmiller** [comment]
@balachir are you still seeing this message? Other folks that publish without a database see the "Unable to connect to database" error that you expected.

**Comment by rowanmiller** [comment]
Closing, feel free to re-open if you have a scenario where this error is still displayed
