### ISSUE TITLE
EF Core not saving to CosmosDB

### ISSUE THREAD

**Issue by jbirrenkott** [dotnet/efcore#15741]
Describe what is not working as expected.
When trying to add an entity to CosmosDB using EF Core the changes are not saved to the database. 

```
Exception message: N/A
Stack trace: N/A
```

### Steps to reproduce
Run the following code.

```c#
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace UseCosmosTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var submerchant = new Submerchant
            {
                Id = Guid.NewGuid(),
                TenantSlug = "TestSlug",
                OptionOne = 1,
                OptionTwo = 2
            };

            using var context = new SubmerchantContext();
            var added = await context.Submerchants.AddAsync(submerchant);
            var changes = context.ChangeTracker.HasChanges();
            var saved = await context.SaveChangesAsync();
        }

        public class Submerchant
        {
            public Guid Id { get; set; }
            public string TenantSlug { get; set; }
            public int OptionOne { get; set; }
            public int OptionTwo { get; set; }
        }

        public class SubmerchantContext : DbContext
        {
            public DbSet<Submerchant> Submerchants { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseCosmos("https://localhost:8081", "ReplaceWithKey", "ReplaceWithDatabaseName");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.HasDefaultContainerName("Submerchants");
            }
        }
    }
}

```

### Further technical details
EF Core version: 3.0.0-preview5.19227.1
Database Provider: Microsoft.EntityFrameworkCore.Cosmos
Operating system: Windows 10

IDE: Visual Studio 2019 16.0.3

**Comment by chad-chronotek** [comment]
We are seeing the same issue in EF Core version: 3.0.0-preview6.19304.10, simple model with just a few simple attributes (all native types, int, string guid) our code matches the example in the original post almost exactly, we are also making a call to HasDefaultContainerName to specify a default container name.  We make a call to SaveChanges, logging shows that it does detect changes so change tracking is working, logging also shows that the tracked state is changed from 'Added' to 'Unchanged' as seen below.  After the call to SaveChanges the context appears to still have all of the entities but there is nothing in the cosmos database.  Then any attempts to query results after the save such as _dbContext.Requests.Where(r=>r.RequestId == requestId).ToList();
results in the following exception being thrown.  As a result of this it seems the Cosmos provider is completely unusable until this is fixed?

` Exception thrown: 'System.NotImplementedException' in Microsoft.EntityFrameworkCore.Cosmos.dll
An unhandled exception of type 'System.NotImplementedException' occurred in Microsoft.EntityFrameworkCore.Cosmos.dll
The method or operation is not implemented.  at Microsoft.EntityFrameworkCore.Cosmos.Query.Pipeline.CosmosEntityQueryableTranslatorFactory.Create(QueryCompilationContext2 queryCompilationContext)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CosmosDBEFTester.TimecardService.GetTimecardsByCompany(Int32 companyId) in C:\devroot\LocalProjects\CosmosDBEFTesterSLN\CosmosDBEFTester\TimecardService.cs:line 43
   at CosmosDBEFTester.Program.Main(String[] args) in C:\devroot\LocalProjects\CosmosDBEFTesterSLN\CosmosDBEFTester\Program.cs:line 53`
`dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: a096f6bb-b0b3-4159-859e-8f05eb8581ce}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: b468f049-b875-4463-b816-828771735415}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: 378de079-20de-4920-9685-973841159569}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: 4657a3f6-08a9-4bcb-8ec4-adb2d64d750d}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: 5902988f-e169-40a1-8be9-821fd7d17782}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: fd2926fb-3f93-4331-92cd-de981cff20ed}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: 4032f238-e671-4f8d-8cce-578d88d0bdcd}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: d71f8a2e-0efb-4256-b957-38822124f2f5}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: 4b25cc81-c32d-4ff3-80a1-48a949e53257}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Timecard' entity with key '{TimecardId: 5c52f9c9-fccb-4312-b331-b88db9ae7d67}' tracked by 'TimecardDbContext' changed from 'Added' to 'Unchanged'.`

**Comment by AndriySvyryd** [comment]
@chad-chronotek [The Cosmos provider is non functional in preview6](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/)

**Comment by chad-chronotek** [comment]
Ah well that makes sense, guess I will have to come back again and give it a try after it matures a little more.  Thanks for sharing the link!

**Comment by AndriySvyryd** [comment]
@jbirrenkott You need to call `context.Database.EnsureCreated();` first.

Currently we don't check whether any entities have been actually saved, so no exception are thrown if the collection doesn't exist.
