### ISSUE TITLE
Considering statically restricting Include to be specified in the query root

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#15744]
Today we decided to try restricting `FromSqlRaw` and `FromSqlInterpolated` to only apply to `DbSet<T>`. 

Later @roji, @maumar and @smitpatel and I had a chat  about doing something similar with `Include` (although probably force any `FromSql` to happen before `Include`). The arguments were inconclusive. Creating this issue so that other can weigh in. 

We know that restricting `Include` to modify the query root would not block any scenarios, given that we are going to allow entities projected can match any intermediary node in the Include path. We also have made a previous decision than in 3.0 we are not going to allow `Include` in arbitrary places. 

Possible advantages: 

- Improve user education on what `Include` can and cannot do.

Possible disadvantages:

- Maybe in the long run, we actually want to be more flexible re where you can put `Include` anyway

- Potential proliferation of types to represent query roots returned by these methods. E.g. assuming we don't want to allow `FromSql` to be called after `Include`, we need `Include` to represent a types that isn't a `DbSet<T>`, is an `IQueryable<T>`, allows another `Include` to be called, etc. Also, are we sure `Include` and `FromSql` are the only query operations that we don't want to treat as normal LINQ operators anymore?

**Comment by ajcvickers** [comment]
Discussed in triage and decided not to do this for `Include`. While the benefits of leading people to a better understanding of `Include` are significant, we also think this kind of change would break a lot of existing queries. Also, sometimes the query can be more readable with `Include` not directly on the root, and we may choose in the future to support `Include` in places where it is not currently supported. On balance, the value does not outweigh the risk of breaking and our ability to predict the future isn't good enough.
