### ISSUE TITLE
Improve FK convention warning

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#15759]
Reported by @alexk8 in https://github.com/aspnet/EntityFrameworkCore/issues/10918#issuecomment-493968093:

I've found this issue, because I've run into a bit similar problem.
I've turned on verbose mode and I've got lots of messages:
[DBG] The foreign key properties haven't been configured by convention because the best match {'Id' : int} are incompatible with the current principal key {'Id' : string}. ...'.
The problem is that I do not understand what entities are involved there, I can only guess that they are probably from Identity template. That's not really a problem, but I think there more info may be added (entity-types).

**Comment by StrangeWill** [comment]
Would love to see this improved -- I have a wall of warnings that I have to find a way to figure out what is going on on a fairly decently sized database.

**Comment by aaronhudon** [comment]
Approaching a year on this one.  Are there any suggestions on determining how to track down the source entities of this warning?

**Comment by lajones** [comment]
Poaching.
