### ISSUE TITLE
Migration empty - no code generated

### ISSUE THREAD

**Issue by kidchenko** [dotnet/efcore#1576]
Hi guys, I'm adding new migrations, but the code of migration is not generated

![image](https://cloud.githubusercontent.com/assets/5432753/6132812/713c74fa-b13c-11e4-9508-94755b9de433.png)

**Comment by bricelam** [comment]
What do your `DbContext` and `ModelSnapshot` derived classes look like?

**Comment by kiide** [comment]
Hi, this bug happens because I did not put the entity in dbSet :/
