### ISSUE TITLE
Feature request: Create SQL database within existing Azure SQL Elastic Pool

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/efcore#15776]
If the database doesn't exist for a given connection string, I can use Database.Migrate() to create the database and commit the migrations to it. However, this functionality doesn't yet support creating the database to exist within an existing elastic pool and this will instead result in creating a single S0 database on the SQL server that isn't attached to the pool.

The [documentation](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=azuresqldb-current) indicates that you'd need to include:
SERVICE_OBJECTIVE = 'ELASTIC_POOL(name=<elastic_pool_name>)' within the CREATE DATABASE query. 

The logic to create a database in SQL Server appears to live in [SqlServerMigrationsSqlGenerator.cs](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs) but it's not clear that it supports any real mechanism for passing in options apart from the database name (such as naming an elastic pool, an edition or in this case, an elastic pool name).  While I could presumably add such options to the [SqlServerCreateDatabaseOperation](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Migrations/Operations/SqlServerCreateDatabaseOperation.cs), it appears to just get its values out of the [SqlConnectionStringBuilder](https://github.com/aspnet/EntityFrameworkCore/blob/c72b59d3c293ab80243a7e034745d92b2971e718/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs#L165) which also doesn't have support for the elastic pool name.

It seems the better place to add such specific options would be within the [SqlServerDbContextOptionsBuilder](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs), and the [ISqlServerOptions](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Infrastructure/Internal/ISqlServerOptions.cs) so that I can simply tweak the migrations generator to get visibility to these options so it can incorporate them into the create statement.

Is this a viable approach or should I take a different tack? I'd be happy to put together a pull request on this, but if you've got a preferred starting point, let's instead begin from there. Especially if you've got any documentation on implementation discussions from https://github.com/aspnet/EntityFrameworkCore/issues/2969, I'd be eager to read through it.

**Comment by ajcvickers** [comment]
@WhitWaldo This is a scenario that we think would be covered by #6577, which is about allowing configuration to be passed when creating a database.

For now, I would generate a script for database creation and then edit the script. Database creation/updates should as a best practice happen as part of application deployment, rather than when the application starts.
