### ISSUE TITLE
RevEng: Missing HasColumnType fluent API for NCHAR column

### ISSUE THREAD

**Issue by pfdsilva** [dotnet/efcore#15772]
Hi,

While reverse engineering a database schema to generate the entity type classes and a DbContext class, we are noticing that the HasColumnType fluent API is not getting generated for NCHAR column in the DbContext class.

Please note, no exceptions are noticed.

```
Exception message: N/A
Stack trace: N/A
```

### Steps to reproduce

1. Create a table in SQL Server database that contains NCHAR column:

```sql
CREATE TABLE [dbo].[testnchar]
(
[Id] INT NOT NULL PRIMARY KEY,
    [c02nchar] NCHAR(32) NULL
)
```

2. Scaffold this database schema to generate the C# model:
```
dotnet ef dbcontext scaffold "<connection string>" Microsoft.EntityFrameworkCore.SqlServer -o testnchar_model  -f -c MicrosoftEFContext -d --use-database-names -t testnchar
```

After scaffolding the table created in step 1, we got the below entity. 
Please note, the c02nchar column does NOT have the HasColumnType fluent API specified.

```C#
            modelBuilder.Entity<Testnchar>(entity =>
            {
                entity.ToTable("testnchar");

                entity.Property(e => e.Id).ValueGeneratedNever();

                 entity.Property(e => e.C02nchar)
                    .HasColumnName("c02nchar")
                    .HasMaxLength(32);
            });
```
The generated entity class is:
```C#
    public partial class Testnchar
    {
        public int Id { get; set; }
        public string C02nchar { get; set; }
    }
```
Also please note, if we go ahead and create the migration script, the column type changes for the C02nchar column from nchar to nvarchar2.

3. Create the initial migration model:
```
dotnet ef migrations add MicrosoftEFMigration --context MicrosoftEFContext
``

4. Create the migration sql script:
```
dotnet ef migrations script --context MicrosoftEFContext
```
```sql
CREATE TABLE [testnchar] (
    [Id] int NOT NULL,
    [c02nchar] nvarchar(32) NULL,
    CONSTRAINT [PK_testnchar] PRIMARY KEY ([Id])
);
```
### Further technical details
EF Core version: 2.2.4 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.11

**Comment by bricelam** [comment]
I'm not able to reproduce this on 3.0.0. The column is configured correctly:
```csharp
entity.Property(e => e.C02nchar)
    .HasColumnName("c02nchar")
    .HasMaxLength(32)
    .IsFixedLength();
```

**Comment by bricelam** [comment]
(HasColumnType  is not scaffolded because a string property with IsFixedLength is sufficient to configure `nchar` as the column type)

**Comment by wgutierrezr** [comment]
Hi
How about for columns DateTime? I use reverse engeneering to get my context and in any table that uses date time, the property "HasColumnType" is shown like the following example:

`        public void Configure(EntityTypeBuilder<AppApprovalRequests> entity)
        {
            entity.HasKey(e => e.ApprovalRequestId);
            entity.Property(e => e.ApprovedDate).HasColumnType("datetime");
            entity.Property(e => e.NewValue).HasMaxLength(250);
            entity.Property(e => e.OldValue).HasMaxLength(250);
            entity.Property(e => e.RequestDate).HasColumnType("datetime");
            entity.Property(e => e.Active).HasDefaultValueSql("((0))");
            entity.Property(e => e.CreatedBy).HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime").HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime").HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ComputerName).HasMaxLength(100).IsUnicode(false).HasDefaultValueSql("(host_name())");
            entity.Property(e => e.ComputerIp).HasColumnName("ComputerIP").HasMaxLength(20).IsUnicode(false).HasDefaultValueSql("([dbo].[GetIpAddress]())");

            entity.HasOne(d => d.BusinessRule)
                .WithMany(p => p.AppApprovalRequests)
                .HasForeignKey(d => d.BusinessRuleId)
                .HasConstraintName("FK_AppApprovalRequests_AppBusinessRules");
        }`

I upgraded my project to Asp.Net Core 3.0

Any idea how to fix it?
