### ISSUE TITLE
EF is using inner join instead of left join

### ISSUE THREAD

**Issue by lugospod** [dotnet/efcore#15803]
**Problem:**
var data = context.Templates.Include(x => x.Parts).ToList();

This linq query generates the following SQL query:
_SELECT "x"."Id", "x"."Text" FROM "Templates" AS "x" ORDER BY "x"."Id"_

I except to get a left join to Parts table.

**Environment:**
EF Core 2.2.4, EF Core Sqlite 2.2.4, .NET CORE 2.2, VS 2019

**Reproducible example:**
[(https://github.com/lugospod/TestEfCoreBuggy)]

**Debugging:**
I Tried to set the constraint using the fluent API but I only managed to get EF core to perform an inner join.

Model is: One template can have multiple Parts (or none). Part can have a parent template or it can be an orphan.  I would like to get ALL templates and if the template HAS orphans, get them... (eager loading). That is why the TemplateId is nullable in the Parts entity.

Any idea why is EF CORE choosing a) to ignore the join b) when forcing a relation using fluent API then it chooses an inner join.

thank you!

**Comment by roji** [comment]
The current expected behavior here is for EF Core to generate *two* queries: one to get the blogs, and a second one to get the posts (joined with their blogs). Can you please double-check your SQL logs and confirm that you're seeing both queries?

Note that in Entity Framework Core 3.0 this behavior is changing, and a single join query will be generated instead.

**Comment by lugospod** [comment]
Hi, Thank you for you your explanation. 1) I was expecting one query, because I could find any information in the documentation that would state otherwise... my bad 2) my logging was just displaying the last query but after your comment I switched to detailed logging and now I see the two queries.

thank you for your help!
KR;
Luka
