### ISSUE TITLE
Create DBContext and models like EF POCO Generator (using EF Core)

### ISSUE THREAD

**Issue by AlansButler** [dotnet/efcore#15827]
Hello,

We we're happily using Simon Hughes' EntityFramework Reverse POCO Generator to manipulate models generated from a SQL Server database.  Alas, the POCO Generator is not yet available for EF Core, so I'm trying to override EF internals to get some of the same results. 

The only part I'm having trouble simulating is below:
When building the models this is what I want for example:
```C#
public partial class X837_DTP
{
	public long DTPID  { get; set; }
	public virtual X837_Claim X837_Claim { get; set; }
}
```
The schema here is X837 and Claim is a table. We want the simple types like DTPID property names to not contain the schema, but property types that are classes do.  

By Overridding 
RelationalScaffoldingModelFactory  protected override string GetPropertyName(DatabaseColumn column) 
I am able to get all the properties to contain the schema.  This is close as I can get:

```C#
public partial class X837_DTP
{
	public long X837_DTPID  { get; set; }	//Don't want schema name here in property name.
	public virtual X837_Claim X837_Claim { get; set; }

}
```

If I don't use override GetPropertyName I get below model with no schemas in name.

```C#
public partial class X837_DTP
{
	public long DTPID  { get; set; }
	public virtual X837_Claim Claim { get; set; }
}
```

Now, I can override Overridding CSharpEntityTypeGenerator.WriteCode 
and do a replace, but, this doesn't seem to change the name internally.  
The DBContext still uses the tablename only.  Like Claim.
example:
```C#
 entity.HasOne(d => d.Claim)		//HasOne Still using table not Schama_Table
```
	
	
I also tried to override VisitColumn:	
protected override PropertyBuilder VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
so I could tell the type of the property, but even the properties with class types come back as 
simple types in column.storeType.

Any suggestions would be appreciated.
```c#
public class RelationalScaffoldingModelFactoryGaf : RelationalScaffoldingModelFactory
{
	public static string fSchema = string.Empty;
	public static Dictionary<string, List<string>> rememberColumns = new Dictionary<string, List<string>>();
	public RelationalScaffoldingModelFactoryGaf(

		IOperationReporter reporter,
		ICandidateNamingService candidateNamingService,
		IPluralizer pluralizer,
		ICSharpUtilities cSharpUtilities,
		IScaffoldingTypeMapper scaffoldingTypeMapper)
		: base(
			  reporter,
			  candidateNamingService,
			  pluralizer,
			  cSharpUtilities,
			  scaffoldingTypeMapper)
	{
		rememberColumns.Clear();
	}


	/// <summary>
	/// Changes the property names in the models.
	/// public int x { get; set; }   
	/// This converts too many properties.  For example in X837_DTP.
	/// This we want for example: public virtual X837_Claim X837_Claim { get; set; }
	/// This we do not: public DateTime? X837_DateTo { get; set; }
	/// </summary>
	/// <param name="column"></param>
	/// <returns></returns>
	protected override string GetPropertyName(DatabaseColumn column)
	{
		return column.Table.Schema + "_" + column.Name;  
	}
	
	 protected override PropertyBuilder VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
	{
		PropertyBuilder pb = base.VisitColumn(builder, column);
	
		Console.WriteLine("RelationalScaffoldingModelFactoryGaf-VisitColumn");
		Console.WriteLine("     columnName " + column.Name);
		Console.WriteLine("    pb.MetaDataCLRType: " + pb.Metadata.ClrType);
		Console.WriteLine("    Column.StoreType: " + column.StoreType);

		if (column.StoreType)	//returns bigInt even for class types.
		{
		}

		return pb;
	}
}
		
public class CSharpEntityTypeGeneratorGaf : CSharpEntityTypeGenerator
{
    public CSharpEntityTypeGeneratorGaf(
        ICSharpHelper cSharpHelper)
        : base(cSharpHelper)
	{ }
		
	public override string WriteCode(IEntityType entityType, string @namespace, bool useDataAnnotations)
	{
		
		string code = base.WriteCode(entityType, @namespace, useDataAnnotations);
		
		string[] modelLines = code.Split(Environment.NewLine);
		foreach (string line in modelLines)
		{
			List<string> modifiedModelLines = new List<string>();
			//Some code here to get the schemaName and tableName from the current model line.

			modifLine = line.Replace(schemaName + "_" + tableName + " " + tableName,
																  schemaName + "_" + tableName + " " + schemaName +"_"+ tableName);

		
			modifiedModelLines.Add(modifLine);
		}
		code = string.Join(Environment.NewLine, modifiedModelLines.ToArray());		
		return code;
	}
}
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: Visual Studio 2019 Preview 3

**Comment by ErikEJ** [comment]
EF Core Power Tools has custom renaming, maybe you can use that?

**Comment by ajcvickers** [comment]
@AlansButler We discussed this in triage and we don't think that hacking the code to make this work would be a very easy at this point. In general, we want to support things like this using a templating engine, which is covered by issue #4038. For now, using @ErikEJ's EF Core Power Tools is probably the easiest path to go down.
