### ISSUE TITLE
ExecuteInTransaction strategy: verifySucceeded only called on commit failure

### ISSUE THREAD

**Issue by BladeWise** [dotnet/efcore#15825]
Using the execution strategy [ExecuteInTransaction](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Extensions/ExecutionStrategyExtensions.cs#L684) or [ExecuteInTransactionAsync](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Extensions/ExecutionStrategyExtensions.cs#L735) the `verifySucceeded` callback is only invoked if the exception is raised during the transaction commit (given the check over `s.CommitFailed`).

In my case, the actual error (SQL Number 2627, Violation of PRIMARY KEY constraint) is raised before commit (during The `SaveAsync` call), and is caused by the fact that multiple concurrent actors can try to write for the first time an optional dependant entity whose id is the same as the parent entity (available in a local cache), so one of these actors could not be aware at a given time that such optional entity has been already created.

In such a case I think that `verifySucceeded` should be called anyway (eventually with additional information about the fact that the error occurred while committing the transaction or before that), or this behavior should be configurable, because it was unexpected that callback was not called despite the exact SQL error number was specified at configuration time.

**Comment by ajcvickers** [comment]
@BladeWise `verifySucceeded` is very specific functionality targeted to the commit failure scenario for which it is not, without some other mechanism, possible to distinguish between a failed commit and a successful commit with a failure communicating this back to the client. It is not intended to be used for normal connection resiliency. See https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#transaction-commit-failure-and-the-idempotency-issue for more information.

**Comment by BladeWise** [comment]
As far as I can tell, from an `IExecutionStrategy` point of view the `verifySucceeded` is just
> A delegate that tests whether the operation succeeded even though an exception was thrown.
it is not tied to the commit failure scenario itself, since the execution strategy is not always associated with a transaction.
Considering that it's `ExecuteInTransaction/ExecuteInTransactionAsync` that is defining such a logic, I think that providing an override where 'verifySucceeded' provides the `s.CommitFailed` as a parameter would be more correct, and would not break anything.

**Comment by ajcvickers** [comment]
@AndriySvyryd Thoughts?

**Comment by AndriySvyryd** [comment]
@BladeWise The primary use case for providing `verifySucceeded` is to handle commit failures. In fact you are the first one to try to use it for something else AFAIK. You are free to copy the implementation of `ExecuteInTransaction` and add any logic that's useful for your scenario.
We already provide a lot of overloads and adding more would make choosing the correct one even harder so we would only do that if the use case is popular enough.

**Comment by BladeWise** [comment]
@AndriySvyryd That's exactly what I am doing right now, and it's not a issue. Yet, I suppose that the different behavior between `ExecuteInTransaction` and `Execute` could be mentioned directly in the documentation, because unless you check the actual implementation there is no way to determine it (unless I missed that).
Thanks both for your time.

**Comment by AndriySvyryd** [comment]
@BladeWise Well the XML docs _are_ different for `ExecuteInTransaction`:
> A delegate that tests whether the operation succeeded even though an exception was thrown when the transaction was being committed.

And `Execute`:
> A delegate that tests whether the operation succeeded even though an exception was thrown.
