### ISSUE TITLE
Non-constant property name in EF.Property (and indexer property)

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#15832]
Investigate what is currently happening (and what we want to be happening) if a non-constant expression (e.g. closure parameter) is used for the property name to `EF.Property()` (and the indexer property).

**Comment by ajcvickers** [comment]
For 3.0, we should understand what is happening, and throw for non-constants.

**Comment by smitpatel** [comment]
We are past 3.0 and we should just close this. We did not have any issues with it and indexer also has test to pass propertyname as variable and still get constant in the tree.

**Comment by roji** [comment]
Sounds good to me...

**Comment by ajcvickers** [comment]
@maumar to add a test.
