### ISSUE TITLE
Unable to track an entity of type  because alternate key property 'id' is null. EF 3.0 preview.

### ISSUE THREAD

**Issue by nimion** [dotnet/efcore#15844]
I am attempting to attach a database entity to track changes and I receive the following exception.

_Unable to track an entity of type 'GameSession' because alternate key property 'id' is null. If the alternate key is not used in a relationship, then consider using a unique index instead. Unique indexes may contain nulls, while alternate keys must not._ 

[FullStackTraceException.txt](https://github.com/aspnet/EntityFrameworkCore/files/3233810/FullStackTraceException.txt)

The line in question fails here:
`dbContext.GameSessions.Attach(session);`

I am using CosmosDB as my data-provider. I did put a breakpoint at the attach line to stop execution and check the DB to see if the GameSession was properly filled out. Below is the document entry that was created. As you can see there is an id field and it is non-null. 

```
{
    "GameSessionId": "e8c49f74-c125-4fcf-82c1-6b04836c4e6c",
    "ConnectionId": "y3tD6y1HK-8J2NW4c1kDqg",
    "DisconnectCodeId": null,
    "Discriminator": "GameSession",
    "EndTime": "9999-12-31T23:59:59.9999999",
    "StartTime": "2019-05-29T17:21:20.5722608Z",
    "id": "GameSession|e8c49f74-c125-4fcf-82c1-6b04836c4e6c",
    "__partitionKey": "0",
    "_rid": "YsIUAK8YAXoRAAAAAAAAAA==",
    "_self": "dbs/YsIUAA==/colls/YsIUAK8YAXo=/docs/YsIUAK8YAXoRAAAAAAAAAA==/",
    "_etag": "\"0000f604-0000-1100-0000-5ceebf920000\"",
    "_attachments": "attachments/",
    "_ts": 1559150482
}
```

The GameSession object:
```
public class GameSession
{
    public Guid GameSessionId { get; set; }
    public string ConnectionId { get; set; } = string.Empty;
    public DateTime StartTime { get; set; } = DateTime.MinValue;
    public DateTime EndTime { get; set; } = DateTime.MaxValue;
    public DisconnectCode DisconnectCode { get; set; }
}
```

### Further technical details
EF Core version: 3.0.0-preview5.19227.1
Database Provider: Microsoft.EntityFrameworkCore.Cosmos (3.0.0-preview5.19227.1)
Operating system: Windows 10 Pro Version 10.0.17134 Build 17134
IDE: Visual Studio 2017 15.9.9

**Comment by vinylima** [comment]
this error occurred with me calling Update method of EF Core Cosmos 3.0 oficial release (version 3.0.100).

I think that exception occurred because EF Core Cosmos not load yours internal json properties of cosmos document, for example "id", "_rid", "_self", "_etag", etc.

resolved it getting entity of database with AsTracking method, change values and save.

my implementation

### Repository Base or you specialized repository ###

```
        protected virtual async Task<bool> Update(TModel model)
        {
            bool updated = false;

            try
            {
                var existingModel = await this.FindAsync(model, true);
                // See more details below
                model.CopyTo(existingModel);

                base.Db.Set<TModel>().Update(existingModel);
                updated = true;
            }
            catch (Exception e)
            {
                var msg = string.Format("An error ocurred during update model: " + e.Message);
                await this.ServiceBus.PublishEvent(new SystemError(model, msg));
            }

            return updated;
        }
```

### Find Method - In Repository Base or your specialized repository

`public virtual Task<TModel> FindAsync(TModel entity, bool track = false) => this.SearchByIdAsync(entity.Id, track);`

```
        public virtual async Task<TModel> SearchByIdAsync(Guid id, bool track = false)
        {
            TModel entity;

            try
            {
                if (track)
                    entity = this.Db.Set<TModel>().Find(id);
                else
                    entity = this.Db.Set<TModel>().AsNoTracking().Where(m => m.Id == id).FirstOrDefault();
            }
            catch (Exception e)
            {
                entity = default;
                var msg = string.Format("An error ocurred during search a model: " + e.Message);
                await this.ServiceBus.PublishEvent(new SystemError(new { id, track}, msg));
            }

            return entity;
        }
```

### CopyTo Method - In Model class ###

```
        /// <summary>
        /// Copy property values of the current object to another object.
        /// </summary>
        /// <param name="model">The model of destination changes.</param>
        /// <param name="changeId">Set 'True' to change Id or 'False' to do not change.</param>
        public override void CopyTo(IModel model, bool changeId = false)
        {
            var city = model as CityBaseModel;

            if (city == null) return;

            if (changeId)
                city.Id = this.Id;

            city.Name = this.Name;
            city.SGIndex = this.SGIndex;
            city.IsCapital = this.IsCapital;
            city.State = this.State;
        }
```
