### ISSUE TITLE
Work item for entity lifecycle hooks

### ISSUE THREAD

**Issue by SidShetye** [dotnet/efcore#15858]
This is a work-item issue emerging from the parent [discussion issue](https://github.com/aspnet/EntityFrameworkCore/issues/626) which already captures the community demand/severity. We'd like to regain functionality that existed in EF 6 but has been missing in EF Core. 

EF Core should have the following events

1. `ObjectMaterialized`: An event fired when the raw data read from the database is filled into the entity object. As seen in EF 6 [here](https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EntityFramework/Core/Objects/ObjectContext.cs#L522). 
2. `SavingChanges`: An event fired when the entity object is just about to be written to the database. As seen in EF 6 [here](https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EntityFramework/Core/Objects/ObjectContext.cs#L504). 
3. `SavedChanges`: An event fired after the `SavingChanges` operation has completed (successfully or otherwise)

**Comment by weitzhandler** [comment]
Would it be better to replace the events with virtual methods, such as `OnObjectMaterialized<TEntity>(TEntity entity) where TEntity : class` etc?

**Comment by SidShetye** [comment]
@weitzhandler: Not really. See [this](https://stackoverflow.com/a/6887466) for reasons

**Comment by ajcvickers** [comment]
Split out into separate issues #15910 and #15911 as requested by @divega on #626

**Comment by JValck** [comment]
For those who came here via SEO: because I needed this functionality myself, I created my own package with lifecycle hooks.

You can download it via [NuGet](https://www.nuget.org/packages/Ramses). Full docs are available on [the Github page of the project](https://github.com/JValck/Ramses).
