### ISSUE TITLE
How to: Handling strategies and transactions across separate contexts

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/efcore#15869]
I filed this in [documentation](https://github.com/aspnet/EntityFramework.Docs/issues/1495), after reading the documentation [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency), but it occurred to me that it might be better asked and answered here.

If I'm setting up a transaction across multiple contexts, I can use the following:

```
using (var transA = contextA.Database.BeginTransaction()) {
  using (var transB = contextB.Database.UseTransaction(transA.GetDbTransaction())) {
    //etc
  }
}
```

I don't see any methods available that explain how to combine a strategy that spans transactions across multiple contexts. Is this currently possible or on a roadmap?

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v2.2.4
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2019 Professional 16.1.1

**Comment by ajcvickers** [comment]
@WhitWaldo Can you explain in more detail what you mean by, "I don't see any methods available that explain how to combine a strategy that spans transactions across multiple contexts?"

**Comment by WhitWaldo** [comment]
Sure, @ajcvickers .

Each of the examples [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) show how to enclose a transaction within a strategy so it enables retry scenarios. That strategy is initalized from the Database property on the context of each example.

In my own project, I'd like to make use of the built-in retry functionality as well which suggests that I also need to wrap my transactions within strategies. In the code I originally posted, there's an extension method that I can use to link the transaction from one context to the transaction of another context.

I assume, and may be wrong, that the strategy is reliant on information from the context itself and I don't see a mechanism in place for taking an already-defined strategy from one context and joining another from another context to it. 

Building off my earlier example, I expect I'd put something together like the following:

using (var contextA = new ContextA()) {
```
  var strategyA = contextA.Database.CreateExecutionStrategy();

  strategyA.Execute(() => {
    using (var transA = contextA.Database.BeginTransaction()) {
      //Do something within this first transaction context
      using (var contextB = new ContextB()) {
        //Associate the contextA transaction with another transaction from contextB
        using (var transB = contextB.Database.UseTransaction(transS.GetDbTransaction())) {
            //Do something else within this second transaction context
           transB.Commit();
           transA.Commit();
        }
      }
    }
  }
}
```

Now, that strategy is based on the context details of only contextA and wouldn't know anything about contextB. Given that contextB would have its own retry strategy associated with it from when it connected, it seems like I'd want to add `var strategyB = contextB.Database.CreateExecutionStrategy() in `there somewhere. 

- Is that safe to do within another strategy once I've defined contextB? 
- Or, given that transactions have the extension method for UseTransaction to combine transaction contexts, is there something similar in place intended to be used for strategies?

Thanks!

**Comment by AndriySvyryd** [comment]
@WhitWaldo Execution strategies from one context can be used safely with other contexts and there is no way of combining them. So you just need to decide which context to use for creating the strategy.
