### ISSUE TITLE
Value conversion using TypeConverter

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/efcore#15895]
This is a feature request to be able to do value conversions using the [TypeConverter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter?view=netcore-2.2) class.

ASP.NET Core supports model binding using the TypeConverter class.
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding

**Comment by ajcvickers** [comment]
@vanillajonathan It certainly should be possible to use a `TypeConverter` in the implementation of a value converter. However, EF requires value converters to be able to build typed, generic expression trees that can be compiled into the materializer. Value converters also must also be specified in the model explicitly defining the types it converts. So I don't think it makes sense to try to build a single converter that can convert between any two types supported by any `TypeConverter`.
