### ISSUE TITLE
How to Save Nested Parent Child Table With EF

### ISSUE THREAD

**Issue by akbarbd** [dotnet/efcore#15894]
```C#
Class A {
    int Id,
    string Name
}

Class B {
    Int Id,
    Int A_Id
    string Name
}

class C {
    int Id,
    Int? B_ID
    string Name
}
```
.......
.....
.....

How Can save this type nested relation

**Comment by ajcvickers** [comment]
I'm having trouble connecting your code to your question, but [the EF docs](https://docs.microsoft.com/en-us/ef/core/) have sections on [building a model with relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships) and [saving related data](https://docs.microsoft.com/en-us/ef/core/saving/related-data).
