### ISSUE TITLE
F# design support

### ISSUE THREAD

**Issue by booblikum** [dotnet/efcore#15901]
We [REDACTED] would like F# design time support;
https://github.com/bricelam/EFCore.FSharp

*Note: @bricelam edited this comment to remove content that violated the project’s code of conduct.*

**Comment by ajcvickers** [comment]
@bricelam does intend to publish this to NuGet at some point in the future. We are happy with this remaining as a community open source project. We don't have any plans to pull this into the EF Core repo.
