### ISSUE TITLE
IAsyncEnumerable.ToListAsync method

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#15924]
Should we have it?

**Comment by ajcvickers** [comment]
Triage: No.

More specifically:
* Compiled query pattern is changing so it should need it
* If something else does need it, then we need to bring this up at the BCL level, since it really should not be an EF thing.

**Comment by Tommigun1980** [comment]
Hi,

I'm curious as to why this is not implemented.

I have code where I am querying via EF and return an AsAsyncEnumerable.
Furthermore, I have code where I need to convert it to an IEnumerable (for example when calling DBSet.RemoveRange(IEnumerable)). System.Linq.Async has ToListAsync (and possibly conversion methods to IEnumerable directly, haven't checked), but the EF equivalent does not feature these conversion methods. EF Core is also incompatible with Linq.Async.

Any chance you guys could implement feature parity with Linq.Async in regard to the IAsyncEnumberable?

Thanks.

**Comment by smitpatel** [comment]
> Any chance you guys could implement feature parity with Linq.Async in regard to the IAsyncEnumberable?

We explicitly decided not to do so. EF Core is a library to access database. We utilize expression trees for that which comes from `IQueryable`, we support a range of methods on `IQueryable` including `ToListAsync`. EF Core is _not_ a library for `IAsyncEnumerable` hence it does not support everything LINQ does.

**Comment by Tommigun1980** [comment]
Thanks for the answer. It seems that you can’t use Linq.Async in conjunction with EF either, but that’s fine.

Probably not the right place for this, but would you consider adding ToEnumerableAsync (ie return a regular IEnumerable in an async manner)? ToAsyncEnumerable is not the same thing at all; that’s why I was asking for the addition. Motivations why to add it: all other methods in EF Core have async counterparts, some extension libraries implement variations of it to great effect. Not having a ToAsyncEnumerable frequently puts me in a position where I just can’t do what I want and need to start looking at alternate solutions, hence my original post.

Thanks for considering!

**Comment by smitpatel** [comment]
> it seems that you can’t use Linq.Async in conjunction with EF either, probably due to overlapping extension methods.

File a new issue with details which method is giving the error. EF Core as an ORM is library over IQueryable extension methods. If you are using another such library then it is likely going to cause clashes. If it is something we can provide to users to resolves clashes easily then we can look into it.

> return a regular IEnumerable in an async manner

Sync over async? Again file a new issue why you feel that EF Core should provide such method. We provide methods to enumerable database queries async (AsAsyncEnumerable). We provide methods to generate collections async from database queries. If you need enumerable then it is best to use enumerable methods rather than async methods because it is anyway going to be blocking.

**Comment by Tommigun1980** [comment]
Thank you, I will do that.
Just to close the loop here, an AsAsyncEnumerable synchronously returns an asynchronous enumeration, where the apis differ vastly between the two. ToListAsync is close to the proposed ToEnumerableAsync, but its boxing differs. One can of course convert between all types so it’s by no means a showstopper, but it can become weird when you have to construct a list to get an enumeration, from which a list is reconstructed later. Hence I don’t see the asynchronous API being fully at par with the synchronous (which has both ToEnumerable and ToList).
Thanks again.
