### ISSUE TITLE
EnsureDeleted is no-op for SQLite :memory: database

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#15923]
This is because the only way to reliably "delete" the database is to close the connection. So, there may be nothing we can do here--except maybe warn?

**Comment by ajcvickers** [comment]
@bricelam @divega Do you know if we already have a general issue for improving the experience with SQLite in-memory databases? Things like support for keeping the connection open. I thought we did, but I can't find it.

**Comment by ajcvickers** [comment]
Notes from triage: there is nothing we can really do here, but we could warn--backlogging for this.

See also #16103 for making the experience better in general.

**Comment by bricelam** [comment]
We could try closing and reopening the connection.

**Comment by norcino** [comment]
I am affected by this issue, if there is any update or work around please let me know.
I am experiencing some weird problem using sqlite in memory for testing, even creating the whole TestServer, DBcontext  and db at each test setup I can still see occasionally stale data.

**Comment by Peop1eCanF1y** [comment]
Has work around, you can call low level API like this:

``` CSharp
using Microsoft.Data.Sqlite;

DBContext context = CreateContext(); // get your DbContext here

context.ChangeTracker.Clear();

SqliteConnection connection = (SqliteConnection)context.Database.GetDbConnection();
connection.Open();
int rc;
rc = SQLitePCL.raw.sqlite3_db_config(connection.Handle, SQLitePCL.raw.SQLITE_DBCONFIG_RESET_DATABASE, 1, out _);
SqliteException.ThrowExceptionForRC(rc, connection.Handle);
rc = SQLitePCL.raw.sqlite3_exec(connection.Handle, "VACUUM");
SqliteException.ThrowExceptionForRC(rc, connection.Handle);
rc = SQLitePCL.raw.sqlite3_db_config(connection.Handle, SQLitePCL.raw.SQLITE_DBCONFIG_RESET_DATABASE, 0, out _);
SqliteException.ThrowExceptionForRC(rc, connection.Handle);
context.Database.EnsureCreated();

```
Source:
https://www.sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigresetdatabase
https://github.com/dotnet/efcore/blob/main/src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
