### ISSUE TITLE
Expose DbContext on DbSet<T>

### ISSUE THREAD

**Issue by djanosik** [dotnet/efcore#1592]
Hi there,

can you expose DbContext on the DbSet<T> type? We have several extensions for querying DbSets and it's sometimes neccessary to know which DbContext was used to create the query. An example could be our `ProjectionExpression` which is used to create reusable projections.

``` c#
var results = dbContext.Set<Entity>()
    .Project().To<Result, ReusableProjection>()
    .ToArray();
```

It's kind of a better `Select(x => new...)` method and it also supports automatic projections (aka AutoMapper for queries). The projection itself might look like this:

``` c#
public class ReusableProjection: Projection<Entity, Result>
{
    public override Expression<Func<Entity, Result>> GetExpression()
    {
        return x => new Result
        {
            Id = x.Id,
            Other = Set<Other>().Single(j => j.Id == x.OtherId)
        };
    }
}
```

The interesting part is the `Set<Other>()` which returns other sets used to join entities from other tables. Here we need to call the `Set<Other>` of exactly the same instance of `DbContext` that was used to create the original query. If we do otherwise, an exception si thrown.

```
Error LINQ expression contains references to queries that are associated with different contexts.
```

We solved this by using [reflection](http://stackoverflow.com/a/17712575/3637097), but it would nice to find another solution.

Thanks!

**Comment by rowanmiller** [comment]
Hey,

We expose the `IServiceProvider` from `DbSet<T>` which gives you access to all the services EF is using for the current context (including the ability to get the context).

```
var dbSet = ...
var serviceProvider = ((IAccessor<IServiceProvider>)dbSet).Service;
var context = serviceProvider.GetService<DbContextService<DbContext>>().Service;
```

It's a little complex, but for extension methods etc. we think this is probably ok. If there are particular services that folks commonly want (such as the `DbContext` from a `DbSet<T>`) we will consider exposing them directly (i.e. we could add `IAccessor<DbContext>` to `DbSet<T>`).

~Rowan
