### ISSUE TITLE
EntityQueryable<T>.Take() fails to take all appropriate elements

### ISSUE THREAD

**Issue by chlowell** [dotnet/efcore#1593]
Where `data` is an `EntityQueryable<T>` with 3 elements: `data.Take<T>(10)` contains only 1 element when realized. `data.ToList<T>().AsQueryable<T>().Take<T>(10)` contains all 3.

**Comment by anpete** [comment]
Please can you provide more information, such as:

1) What provider are you using?
2) What does your model look like?
3) What is "data", a DbSet, or something else?

Even better, a small self-contained repro that demonstrates the issue.

Cheers,
Andrew.

**Comment by rowanmiller** [comment]
We haven't heard back with requested details
