### ISSUE TITLE
DBContext is using JetBrains.Annotations.NotNullAttribute

### ISSUE THREAD

**Issue by thomasvanveen** [dotnet/efcore#15932]
### DBContext is using JetBrains.Annotations.NotNullAttribute

If I disassemble the DBContext class with Visual Studio 2019 (Go to definition) the Code File shows me the Usage of JetBrains

```c#
public virtual EntityEntry<TEntity> Add<TEntity>([JetBrains.Annotations.NotNull] TEntity entity) where TEntity : class
```

Is this a Bug in Visual Studio, or is it really a reference to JetVrains Assembly?

**Comment by smitpatel** [comment]
It is referencing JetBrains. Link to source code.
https://github.com/aspnet/EntityFrameworkCore/blob/b9c9b57de1ba41f75427db0a51b2e897d0354656/src/EFCore/DbContext.cs#L773-L774

Is there any issue with that?

**Comment by ajcvickers** [comment]
Note that there isn't an assembly reference here. It's just a by-convention type defined in that namespace so that tooling can pick it up.

**Comment by jhorv-bvb** [comment]
This does pose one problem - when I use Visual Studio's Quick Actions to generate a constructor, it includes a [NotNullAttribute] annotation which is an error.

![image](https://user-images.githubusercontent.com/42846583/59704229-97a2e580-91c9-11e9-9c2d-efed55c87ecf.png)

**Comment by ajcvickers** [comment]
@jhorv-bvb See #462 and https://github.com/dotnet/roslyn/issues/5646
