### ISSUE TITLE
QueryRewrite: convert all enumerable query methods to queryable early during query processing

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15931]
Linq query can have enumerable methods, e.g. when composing on top of collection navigation, or grouping in result selector of a GroupJoin.

We can convert all of them to Queryable early on, so that individual visitors only need to do pattern matching on a subset. Where needed we can inject AsQueryable so that types match.

**Comment by roji** [comment]
Should we also get rid of all those pesky Quote expressions while we're at it?

**Comment by smitpatel** [comment]
Can you really get rid of them? o.O

**Comment by roji** [comment]
You mean the expression tree API verifies that there's always QuoteExpression around LamdaExpressions that return IQueryable<T>? If so maybe we can convert everything to IEnumerable instead of the other way around :smiling_imp: ?

**Comment by smitpatel** [comment]
I don't know if it verifies. We cannot go the other way for sure since there are our own methods defined on IQueryable

**Comment by maumar** [comment]
it doesn't verify, nav expansion already swallows quotes and nothing bad happens :3

**Comment by roji** [comment]
![image](https://user-images.githubusercontent.com/1862641/58906238-c5892400-870b-11e9-8bcf-b53aee2de56c.png)

**Comment by smitpatel** [comment]
I wish I can imagine that but translation needs to deal with quote nodes still.

**Comment by ajcvickers** [comment]
Note from triage: @maumar @roji If you want to pursue this, then please prepare something for the design meeting.

**Comment by roji** [comment]
@ajcvickers we can discuss although this is ultimately an internal query pipeline implementation design question, i.e. is it possible to normalize some aspects early to make things easier in actual visitors... I guess we should check if it's even possible first.

**Comment by ajcvickers** [comment]
@roji In general I think bringing the question to the wider team is useful when there is some question as to the best design on internal query pipeline things. This is perhaps something we haven't been so good at in the past.

**Comment by smitpatel** [comment]
Queryable conversion was done in https://github.com/dotnet/efcore/pull/15721 already, which has improved over the time. We are not remove quotes.
