### ISSUE TITLE
System.Runtime dependency not included with NuGet Package.

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#1594]
This is also possibly related to  #150 

I created a simple unit tests project, created a model, added the EntityFramework NuGet packages (latest beta) - but at runtime it blows up because System.Runtime dependency is not installed with the NuGet package:

![image](https://cloud.githubusercontent.com/assets/3176632/6156513/d22425be-b232-11e4-9657-0bc58d280949.png)

I suspect to resolve this it probably just requires adding the "System.Runtime" nuget package as a dependency within the Nuspec file for the EF package..

**Comment by bricelam** [comment]
What type of project and what version of .NET?

**Comment by dazinator** [comment]
C# Library project, Visual Studio 2013, .NET 4.5.1

**Comment by bricelam** [comment]
The design-time facades for these assemblies should be implicitly referenced by MSBuild... What `<Reference>` items are listed inside your project file? Also, what does your `packages.config` look like?

**Comment by dazinator** [comment]
Interesting - so I just created a brand new project - again VS2013, C# Library Project, targeting .net 4.5.1 - and I couldn't replicate this problem. Therefore I am going to assume something must have gone wrong with my project file at some point. I'll do some further digging, and comparison to see if i can work out what has gone awry. 

.

**Comment by dazinator** [comment]
- Am going to close this for now as I can't replicate this issue when starting with a new project.
