### ISSUE TITLE
Property cannot be mapped because it's not a supported primitive type or a valid entity type

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/efcore#15987]
When attempting to add a new migration, I'm getting the following exception:

> The property 'ManyToMany_A_B.ObjA#ObjA.States' could not be mapped, because it is of type 'List<MyState>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

ManyToManyObjAObjB is a many-to-many class between ObjA and ObjB and is registered in the context as expected. ObjA is an owned type under OwnedA which is itself an owned entity under EntityA, as illustrated in the following:

```C#
public class EntityA {
  [Key]
  public Guid Id {get;set;}
  public OwnedA OwnedObject {get;set;}
}

[Owned]
public class OwnedA {
  [Key]
  public Guid Id {get;set;}
  public List<ObjA> MyObjects {get;set;}
  public Guid EntityAId {get;set;}
  public EntityA EntityA {get;set;}
}

[Owned]
public class ObjA 
  public Guid Id {get;set;}
  public Guid OwnedAId {get;set;}
  public List<ManyToMany_A_B> EntityBs {get;set;}
  public List<MyState> States {get;set;}
}

public class EntityB {
  [Key]
  public Guid Id {get;set;}
  public List<ManyToMany_A_B> ObjAs {get;set;}
}

public class ManyToMany_A_B {
  public Guid EntityBId {get;set;}
  public EntityB EntityB {get;set;}
  
  public Guid ObjAId {get;set;}
  public ObjA ObjA {get;set;}
}

public enum MyState {
  Opened,
  Closed
}
```

Each are mapped to one another in the context:
```C#

//Many-to-many
modelBuilder.Entity<ManyToMany_A_B>()
  .HasKey(pd => new {pd.EntityBId, pd.ObjAId});
modelBuilder.Entity<ManyToMany_A_B>()
  .HasOne(a => a.ObjA)
  .WithMany(a => a.EntityBs)
  .HasForeignKey(a => a.ObjAId)
  .OnDelete(DeleteBehavior.ClientSetNull);
modelBuilder.Entity<ManyToMany_A_B>()
  .HasOne(a => a.EntityB)
  .WithMany(a => a.ObjAs)
  .HasForeignKey(a => a.EntityBId)
  .OnDelete(DeleteBehavior.ClientSetNull);
  

//Owns
modelBuilder.Entity<EntityA>
  .OwnsOne(a => a.OwnedObject)
  .OwnsMany(a => a.MyObjects, a => {
    a.HasForeignKey(b => b.OwnedAId)
	a.Property(b => b.Id)
	  .HasDefaultValueSql("newid()");
	a.HasKey(b => new 
	{
	  b.OwnedAId,
	  b.Id
	});
	a.Property(b => b.States)
	  .HasConversion(c => SerializeEnumList(c), c => ParseEnum<MyState>(c));
  });
```
  
My converters then look like the following - they're intened to convert a list of any given enum to a string and vice-versa:

```C#
private string SerializeEnumList<T>(IEnumerable<T> enums) where T : struct, IConvertible, IFormattable, IComparable //Enum
{
  var sb = new StringBuilder();
  foreach(var e in enums) 
  {
    if (sb.Length > 0)
	  sb.Append(";");
	sb.Append(e);
  }
  return sb.ToString();
}

private List<T> ParseEnum<T>(string s) where T : struct, IConvertible, IFormattable, IComparable //Enum 
{
  var result = new List<T>();
  foreach(var split in s.Split(';')) 
  {
    if (!Enum.TryParse<T>(split, true, out var enumVal)) 
	  continue;
	  
	  result.Add(enumVal);
  }
  return result;
}
```

As you can see in the owns definition for the type, I _have_ defined the conversion to use to convert the enum to an appropriate value and back. Given that it's an owned type, I can't access it directly off the modelBuilder and have to reference it within this OwnsMany definition anyway, so why isn't the converter for this type being properly picked up with the rest of the owned definition?

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:

> The property 'ManyToMany_A_B.ObjA#ObjA.States' could not be mapped, because it is of type 'List<MyState>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

Stack trace:
> System.InvalidOperationException: The property 'ManyToMany_A_B.ObjA#ObjA.States' could not be mapped, because it is of type 'List<MyState>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>    at System.Lazy`1.CreateValue()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
>    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.CanConnect()
>    at xyzContext..ctor(DbContextOptions`1 options) in xyzContext.cs:line 31
>    at abc.ContextFactory.CreateDbContext(String[] args) in zbcContextFactory.cs:line 22
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v2.2.4
Operating system: Windows 10 Pro x64
IDE: (e.g. Visual Studio 2017 15.4) Visual Studio 2019 Pro 16.1.1

**Comment by WhitWaldo** [comment]
After marking the list of enums as NotMapped to see what would happen, I re-ran the migration and got a different error:

> Unable to determine the relationship represented by navigation property 'OwnedA.States#ObjA.EntityBs' of type 'List<ManyToMany_A_B>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

That's exactly the many-to-many mapping I have above, so that doesn't really make much sense. 

I'm starting to get the sense that because ObjA is an Owned type, it cannot maintain a many-to-many relationship with an entity.

As I'm primarily wanting to simply associate the various EntityBs with the ObjAs and don't really care if I'm unable to navigate in the opposite direction, is there some way of defining this to be a one-way relationship between the two that's valid for owned types?

**Comment by ajcvickers** [comment]
@WhitWaldo I'm finding it hard to figure out your intentions here. Are you trying to make `ObjA` both owned and not owned at the same time?

It might help if you could clearly describe you object model, without any EF mappings, in terms of what the different types are, where there is ownership, and where there are relationships.

**Comment by smitpatel** [comment]
> I'm starting to get the sense that because ObjA is an Owned type, it cannot maintain a many-to-many relationship with an entity.

That is true. EntityTypes cannot have navigation of owned type except for owner itself. Since you have made `objA` as owned type, `ManyToMany_A_B.objA` is different owned entity type than `OwnedA.MyObjects`. `Owned` attribute is making objA owned type. Since your fluent API configures value converter for `OwnedA.MyObjects` you get exception that List cannot be mapped since no value converter is defined for `ManyToMany_A_B.objA`.

You run into second exception because owned type cannot have collection navigation of owner type since it is always dependent end for ownership relationship.

On high level, owned type constitute an aggregate. There could be relations inside the aggregate from any entityType which is not part of the aggregate can only point to aggregate root. i.e. EntityType which is not owned and is owner of the whole aggregate.

**Comment by WhitWaldo** [comment]
@ajcvickers 
Ultimately I've got an entity that owns an object that owns another object. I've got another entity that I'd like for my latter owned object to be able to reference in a many-to-many relationship. While I'd like to be able to access the navigational properties off the owned object to the entity, I don't need to be able to access the navigational properties in the opposite direction (though of course, if it's possible to do so, I wouldn't complain).

Per @smitpatel 's (thanks for chiming in!) answer though it seems that this isn't possible to set up using the owned types. I've since dropped the owned approach and convert each to be an entity and the migration created and applied exactly as expected.

After carefully re-reading the documentation at [https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#limitations](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#limitations) I see that this scenario is covered under the third bullet point under Current Shortcomings. Does that mean that there's potentially something on a roadmap to enable this sort of scenario down the road?

**Comment by smitpatel** [comment]
@AndriySvyryd to answer last question.

**Comment by AndriySvyryd** [comment]
>After carefully re-reading the documentation at https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#limitations I see that this scenario is covered under the third bullet point under Current Shortcomings. Does that mean that there's potentially something on a roadmap to enable this sort of scenario down the road?

@WhitWaldo That refers to a slightly different scenario as the owned types referenced from different entity types would be different, but using the same owned entity instance. This usually implies that the owned entity type in question is an immutable value type.
