### ISSUE TITLE
SqliteException: SQLite Error 1: 'table Posts has no column named BlogId1'

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#15990]
## Describe what is not working as expected.
EF Core is generating extra column.

```
Exception message: SqliteException: SQLite Error 1: 'table Posts has no column named BlogId1'
Stack trace:
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table Posts has no column named BlogId1'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
```

[Full debug window](https://github.com/spottedmahn/Experiments/blob/master/EF%20Core%20SomeId1/debug%20window.log.txt)

### Steps to reproduce

```c#
public abstract class Entity
{
	[PrimaryKey, AutoIncrement]
	public int Id { get; set; }
}

public class Post : Entity
{
        ...
	public int BlogId { get; set; }

	public Blog Blog { get; set; }
}
```
```c#
public class BloggingContext : DbContext
{
	//...
	
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Blog>()
			.Property(b => b.Id)
			.HasColumnName("BlogId");

		modelBuilder.Entity<Post>(post =>
		{
			post.Property(b => b.Id)
			.HasColumnName("PostId");
			 
		        //this causes the problem
			post.HasOne(p => p.Blog)
			.WithMany()
			.HasForeignKey(p => p.BlogId);
		});
	}
}
```

![image](https://user-images.githubusercontent.com/14079228/59111015-3c8e0a80-890e-11e9-8cfe-cb7ed4cc8cfe.png)

I shouldn't need to define the FK relationship in my `Post` class but I've inherited some code that is doing this.  EF shouldn't generate an erroneous column of `BlogId1` though, should it?

[csproj with repro of the issue](https://github.com/spottedmahn/Experiments/tree/master/EF%20Core%20SomeId1/EF%20Core%20SomeId1%20-%20Copy
)

[Full SLN with readme.md and other test projects](https://github.com/spottedmahn/Experiments/tree/master/EF%20Core%20SomeId1)

---

I created another project that doesn't manually define the FK relationship and compared the migration files:

![image](https://user-images.githubusercontent.com/14079228/59107487-c0dc8f80-8906-11e9-874b-822d8b072413.png)

### Further technical details
EF Core version: 2.1.11, also tried 1.1.6
Database Provider: Sqlite and SqlServer
Operating system: Win 10
IDE: VS 2019 Preview (16.2.0 Preview 1)

**Comment by smitpatel** [comment]
>  //this causes the problem
			post.HasOne(p => p.Blog)
			.WithMany()
			.HasForeignKey(p => p.BlogId);

Your blog class also contains `blog.Posts` collection navigation. By using `WithMany` without parameter you essentially indicated that `blog.Posts` represent a different navigation. `BlogId1` FK property is created for that relationship. If `post.Blog` & `blog.Posts` are navigations in the same relationship then update fluent API call to include both of them.

**Comment by spottedmahn** [comment]
**Solution:**

```csharp
public class BloggingContext : DbContext
{
	//...
	
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Blog>()
			.Property(b => b.Id)
			.HasColumnName("BlogId");

		modelBuilder.Entity<Post>(post =>
		{
			post.Property(b => b.Id)
			.HasColumnName("PostId");
			 
		        post.HasOne(p => p.Blog)
			//as stated by smitpatel: 'By using WithMany without parameter...'
                        //add the Posts reference and it works! 
                        .WithMany(b => b.Posts)
			.HasForeignKey(p => p.BlogId);
		});
	}
}
```

Thanks @smitpatel 👏😊

**Comment by amane312** [comment]
did u checked your entity file it should same like entity data and columns name are same
