### ISSUE TITLE
SimpleQuerySqlServerTest.Cache_key_contexts_are_detached is flaky

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#16006]
Mostly passes when run with all other tests. Always fails for me when run on it's own. Failure is that the weak reference is at the final `Assert.False(weakRef.IsAlive);` call. A couple of ideas:
* A leak in the query pipeline depending on what is already cached
* A test issue due to variations in GC behavior

Will disable the test for now.

**Comment by bricelam** [comment]
I saw similar behavioral differences around WeakReference in the EF6 tests on .NET Core

https://github.com/aspnet/EntityFramework6/blob/e5dd54dc7d7bd6e8d11e711e67f27ca495d959fa/test/EntityFramework/FunctionalTests/Interception/DatabaseLogFormatterTests.cs#L110-L134

https://github.com/aspnet/EntityFramework6/blob/e5dd54dc7d7bd6e8d11e711e67f27ca495d959fa/test/EntityFramework/FunctionalTests/Interception/CommitFailureTests.cs#L922-L947

**Comment by ajcvickers** [comment]
@bricelam Two me, these look more likely to be GC-related than the EF Core one. For those I wouldn't necessarily expect the local to be GC'ed while it is still in scope. I'm pretty sure that's why we are using the delegate pattern for this in the EF Core tests.

**Comment by smitpatel** [comment]
I looked at the test and this is what is we are trying to test (best of my understanding),
- We create a context and run a query, we retain a weak ref to context.
- We call garbage collector.
- We verify that context is garbage collected.

At this point, I feel confident that we are not leaking context into compiled query delegate (we have exception throwing mechanism for that. Cache key does not store context either. We haven't had any reported memory leak about context leaking from query cache. So at this point the test has less to do with EF and more about garbage collection and I don't think it provides us any value.
If people have other ideas about how to verify that we are not leaking context in query cache we could write test in that scenario. We should delete this particular test.
