### ISSUE TITLE
EF Core Updates incorrect fields

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/efcore#16012]
Hi,

I'm experiencing data corruptions in FK fields. I tracked the problem down to a buggy UPDATE statement.
Indeed EF Core seem to update fields in tables that were not changed, resulting in corruption of certain FK fields.

### Steps to reproduce
I can reproduce this bug with a databse schema containing one-to-one, one-to-zero and one-to-many relationships.
The bug occurs when updating related entities independently : If A owns B then update B independently of A and you have a chance of corrupting some FKs in A.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017 15.4
Also using Microsoft.EntityFrameworkCore.Proxies

**Comment by Yuri6037** [comment]
Adding this line in the code seem to prevent the corruptions :
Context.Entry(<instance of entity A>).State = Microsoft.EntityFrameworkCore.EntityState.Detached;

**Comment by ajcvickers** [comment]
@Yuri6037 Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by Yuri6037** [comment]
The issue seem to happen only with large data sets so you'd need to seed the database first.
It's also kind of random, there is a chance a line of the database that was linked to an upated line in the other entity would not be affected.
I can't seem to reproduce this issue with reduced data sets. It does happen with more than 100 of lines in dbo.Symbols and more than 30 lines in dbo.SymbolRefs.

I can however link you to the repository it's open source, would that be sufficient ?
https://dev.azure.com/WikiLibs/_git/API?version=GBdevelop
I can also tell you were exactly the issue occurs : it occurs when updating the dbo.SymbolRefs table independently of the dbo.Symbols table the entire DB schema can be found in WikiLibs.Data.
The boggus code can be found in WikiLibs.Symbols.SymbolManager.OptimizeAsync.
PS : Don't forget to check you are on develop branch

**Comment by ajcvickers** [comment]
@Yuri6037 How are you managing the lifecycle of the context? (I.e. when and how does a context instance get created and when and how does it get disposed.) Also, how are you ensuring that the context instance is not used by multiple threads concurrently?

**Comment by Yuri6037** [comment]
In Unit Testing (WikiLibs.API.Tests)
The lifecycle is simple a new context is created each time a test is executed.

In Production/Development (WikiLibs.Core)
The entire lifecycle is defined by ASP.NET Core services
`            services.AddDbContext<Data.Context>(o => o.UseLazyLoadingProxies()
                                                      .UseSqlServer(Configuration.GetConnectionString("Default")));
`
