### ISSUE TITLE
Error when running on build

### ISSUE THREAD

**Issue by rmorgan0076** [dotnet/efcore#16048]
Currently, the set up .NET Core 2.2.5 installed using SDK Core 2.2.107. The project has two .NET 4.7.2 and one .NET Core 2.2.5. This runs perfect everywhere else but when on our build server we get this error:

(ResolvePackageAssets target) -> 
     [exec]          C:\Program Files\dotnet\sdk\2.2.107\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1064: Package Microsoft.EntityFrameworkCore.Analyzers, version 2.2.4 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. 

### Steps to reproduce
I am not sure of the steps to reproduce. We have our solution with the three projects and build fails on that line.

```

### Further technical details
EF Core version: found in project.csproj
Operating system: Windows 8.1
IDE: Visual Studio 2017 15.4

**Comment by rmorgan0076** [comment]
Here is a copy of the .csproj
----------------------------------------
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>	
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
	<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>	
	<PlatformTarget>AnyCPU</PlatformTarget>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Cors" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.Internal" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Server.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />		
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.2.0" />
    <PackageReference Include="NuGet.Client" Version="4.2.0" />
    <PackageReference Include="NuGet.Common" Version="5.1.0" />
    <PackageReference Include="NuGet.Core" Version="2.14.0" />
    <PackageReference Include="NuGet.Frameworks" Version="5.1.0" />
    <PackageReference Include="NuGet.Packaging" Version="5.1.0" />
    <PackageReference Include="NuGet.Packaging.Core" Version="5.1.0" />
    <PackageReference Include="NuGet.Versioning" Version="5.1.0" />
    <PackageReference Include="React.AspNet" Version="4.0.0" />
    <PackageReference Include="React.AspNet.Middleware" Version="4.1.1" />
    <PackageReference Include="react.js" Version="0.14.7" />
    <PackageReference Include="React.Router" Version="4.0.0" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.5.0" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.2" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />	
  </ItemGroup>

  <ItemGroup>
    
    <Content Remove="$(SpaRoot)**" />
    <None Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ClientApp\public\images\" />
    <Folder Include="ClientApp\src\components\pages\" />
    <Folder Include="ClientApp\src\components\ui\" />
  </ItemGroup>

  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />

    
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)build\**; $(SpaRoot)build-ssr\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

</Project>

**Comment by ajcvickers** [comment]
@bricelam to take a look.

**Comment by rmorgan0076** [comment]
Fixed!

**Comment by petrenko-sergii** [comment]
Hi @rmorgan0076 ,
Sorry, can you write how did you fix this issue?
Thanks in advance :)

**Comment by rmorgan0076** [comment]
For this issue,  if I remember correctly, I had to create a new project and copy over the contents of the damage project to it.

**Comment by petrenko-sergii** [comment]
Hi again, thanks for answer.
I've solved this issue by putting the param "/t:Restore" for MSBuild step, because during usual Nuget step I had this fail.
