### ISSUE TITLE
Invalid column name in unique constrain causes to generate drop all tables while adding migration

### ISSUE THREAD

**Issue by oNoobMastero** [dotnet/efcore#16043]
this line  => `entityBuilder.Entity<IEntity>().HasIndex(new [] { "Field1" , "Field2" }).IsUnique(true);`

Field 2 is invalid and is not available in the table but added to the above Fluent API line by human mistake !!!!

when adding migration it will generate a migration file that contains Drop All Tables !!!!!!

[screenshot of the generated migration file](https://drive.google.com/open?id=1_CR9NQUKX9B9xtfg6Gmd1J49-erUqefI)

### Further technical details
EntityFrameworkCore version: 2.2.4
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (Visual Studio 2019 community 16.2)

please need help !

**Comment by ajcvickers** [comment]
@oOAhmedKingOo Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by oOAhmedKingOo** [comment]
sorry for late replay, 
here is a runnable project attached
[click here to download the project from google drive](https://drive.google.com/open?id=1fIBiyYavJ28dsMh1ZBMa0c-tJknVf7P7)

**Comment by oOAhmedKingOo** [comment]
just add migration on TestDbContext and see what will happen

**Comment by oOAhmedKingOo** [comment]
BTW im using Reflection to do migrations  !!

**Comment by ajcvickers** [comment]
@oOAhmedKingOo The model building code is throwing this:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The specified type 'WebApplication1.IEntity'must be a non-interface reference type to be used as an entity type .
```
but the exception is being swallowed in your `OnModelCreating` method. This leaves the model in an invalid state.

**Comment by oOAhmedKingOo** [comment]
ohh didn't notice that, thanks for your help, and sorry for late replay  :)
