### ISSUE TITLE
Query: investigate discrepancies in sql baselines between CI and local

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#16057]
Compiler_generated_local_closure_produces_valid_parameter_name_1742
parameter name difference
expected: @__8__locals1_details_LastName_1, CI: @__details_LastName_1

Where_datetimeoffset_date_component
DateTimeOffset constant literal difference
expected: 01T00:00:00.0000000-08:00 actual: 01T00:00:00.0000000+00:00

**Comment by smitpatel** [comment]
Second one is going to be different in different regions.

**Comment by yyjdelete** [comment]
BTW: this also lead to an ArgumentException in timezone +8
since `0001-01-01T00:00:00.0000000+08:00` is something before year 1 in utc.
    System.ArgumentException : Failed to convert parameter value from a DateTime to a DateTimeOffset.
    ---- System.ArgumentOutOfRangeException : The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
