### ISSUE TITLE
[3.0preview6]Special edge case for Enum[].Cast<underlying type of enum>().Contains()

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/efcore#16098]
Describe what is not working as expected.
Wrong SQL is generated.
```sql
      SELECT [t].[PK]
      FROM [Test001] AS [t]
      WHERE [t].[PK] IN (Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday)
```
<del>Maybe related to 
https://github.com/dotnet/roslyn/issues/29680#issuecomment-424549785
and
https://blogs.msdn.microsoft.com/ericlippert/2009/09/24/why-is-covariance-of-value-typed-arrays-inconsistent/
, so it's an special edge case that the dotnet runtime treat enum[] and array of it's underlying type as compatible but not the same type, which lead to something wrong for EFCore.
```cs
new DayOfWeek[0] is int[];//=>false for roslyn
((object)new DayOfWeek[0]) is int[];//=>true
typeof(int[]).IsAssignableFrom(typeof(DayOfWeek[]));//=>true
typeof(DayOfWeek[]).IsAssignableFrom(typeof(int[]));//=>true
```
</del>

Update: I see it also works well when I replace `Cast<int>()` to `Cast<uint>()`(the Type of result is still DayOfWeek[]), and change the type of `Test001.PK` to uint. It just not work if Cast to the underlying type of Enum.

### Steps to reproduce
Hit this when I forget to add an .ToArray() for something like the below code
```c#
var allFlags = Enum.GetValues(typeof(DayOfWeek)).Cast<int>();//.ToArray()
ctx.Test001.Where(d => allFlags.Contains(d.PK)).Select(d => d.PK).ToList();

public class Test001{public int PK { get; set; }}
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10, used to works in 3.0.0-preview5.19227.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer and maybe all other providers except InMemory(Not tested)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment]
Closure variable has type of `DayOfWeek[]` so our parameter gets that type. I am not sure why closure variable got a different type from actual type but it throws off our printing part.

Since it throws with invalid sql and there is easy work-around, marking for punt.

**Comment by smitpatel** [comment]
closure.allFlags is of type `IEnumerable<int>`
Expression is of type `IEnumerable<int>`
but when doing `fieldInfo.GetValue(closure)` it returns `IEnumerable<TEnum>`.
Removing from backlog to see if we want to compensate here or we should file issue in BCL.

**Comment by ajcvickers** [comment]
Note from triage: @smitpatel to follow up with Roslyn team. Workaround for EF Core seems fine, so closing this as external.

**Comment by smitpatel** [comment]
https://github.com/dotnet/runtime/issues/44368
