### ISSUE TITLE
EF Core - Predefined type 'System.Object' is not defined or imported (CS0518)

### ISSUE THREAD

**Issue by LlewellynJones** [dotnet/efcore#16109]
Describe what is not working as expected.

The project looked okay until I installed EFCore by running:
"dotnet add package Microsoft.EntityFrameworkCore.SqlServer"

If you are seeing an exception, include the full exceptions details (message and stack trace).
All the objects in my project are in error with the following or similar message:

Predefined type 'System.Object' is not defined or imported (CS0518)

I want to use the EntityFramework but get rid of the messages.

Commenting out the following line from the .csproj file gets rid of the message:
PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" 

Here are the project details:
OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by ajcvickers** [comment]
@LlewellynJones Can you please post you `csproj` file.

**Comment by LlewellynJones** [comment]
Here you go:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
  </ItemGroup>

</Project>

**Comment by ajcvickers** [comment]
@LlewellynJones Do you have a [`global.json`](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) anywhere that could be pinning to the wrong SDK.

Also, it would probably be a good idea to uninstall the very old 1.0 preview SDK since it could be having some unexpected influence.

**Comment by LlewellynJones** [comment]
I don't have a global.json in the project. I did uninstall Core .Net 1.0 and the Core .Net 1.0 Tools. Now I'm not getting the object errors but I'm getting _launch Program '' does not exist_ when I start the debugger. When I build the project I get:
ERROR: Error: spawn dotnet ENOENT
Done: -4058.

**Comment by LlewellynJones** [comment]
I was able open the above projects in VS 2017 and debug them. Did removing the Core 1.0 convert these projects from VS 2015 to VS 2017...?

**Comment by ajcvickers** [comment]
@LlewellynJones It sounds like you are having a lot of issues getting .NET Core to work that are not related to EF. I would suggest to follow up instead on https://github.com/dotnet/core

**Comment by LlewellynJones** [comment]
Okay, I did that.
