### ISSUE TITLE
Preview 6 "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by kccsf** [dotnet/efcore#16102]
Updated EF core 3.0.0 from preview 5 to preview 6 (was working fine on preview 5)

Query:
   this.dbcontext.SomeEntity
      .Include(x => x.Owner)
      .OrderBy(x => !x.IsUnopened)
      .Skip(offset)
      .Take(limit)
      .ToListAsync();

Removing any one of the following alleviates the issue:
   Skip **and** take
   Include
   OrderBy

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
"Object reference not set to an instance of an object."

Stack trace:
"   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SelectExpression.Update(List`1 projections, List`1 tables, SqlExpression predicate, List`1 orderings, SqlExpression limit, SqlExpression offset, Boolean distinct, String alias)\r\n   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SearchConditionConvertingExpressionVisitor.VisitSelect(SelectExpression selectExpression)\r\n   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SearchConditionConvertingExpressionVisitor.VisitSelect(SelectExpression selectExpression)\r\n   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryExpression.VisitChildren(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SqlServerShapedQueryOptimizer.Visit(Expression query)\r\n   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()\r\n   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\\a\\1\\s\\Ix.NET\\Source\\System.Interactive.Async\\Aggregate.cs:line 118\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at xxxxxxxx.Service.DataService.<FindItemsAsync>d__20.MoveNext() in xxxxxxxx.cs:line 555"
```

### Steps to reproduce
I have a private repo if you need a repro.....

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.0 Preview 2

**Comment by maumar** [comment]
already fixed in current bits - d2b195a2cafabda2bd5ed67310044b2a2cd47545

**Comment by kccsf** [comment]
Thanks - apologies for the dupe

**Comment by ajcvickers** [comment]
@kccsf Many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

**Comment by kccsf** [comment]
@ajcvickers No problem at all, thanks for your (and everyone else involved)s' great work. I had read the post you referenced prior to trying preview 6, so was not shocked when it didn't work. I then tried the nightly build as recommended in that post but got a different error.

Should nightly build issues be logged or not due to the nature of them?

**Comment by ajcvickers** [comment]
@kccsf In general we would prefer you log any issues unless you have confidence that they are already tracked by another issue. External feedback on what is working or not is very valuable because query generation is a very large space which means we are inevitably missing test coverage.

**Comment by kccsf** [comment]
@ajvickers - Must be a tough one to cover with tests. Looking forward to EF Core improving as a result of the rewrite  :-). 

The nightly build issue was not to do with query generation, an exception occurs when the db context gets newed up. I'll log it now. Thanks again
