### ISSUE TITLE
Adding DatabaseGenerated.Identity after table is created.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#1611]
When doing Code First and using DatabaseGenerated.Identity later, a migration will not detect this and would not set the default value.

EF 6.latest
C# 6
Visual Studio 2015

Repo:

```
public class Person {
    public Guid ID {get;set;}
}
DbSet<Person> People {get;set;}

Add-Migration "initial"
Update-Database
```

Then :

```
public class Person {
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid ID {get;set;}
}
Add-Migration "identity key"
Update-Database
```

Expected default value for ID =(newsequentialid)
Resulted default value for ID = Empty

**Comment by rowanmiller** [comment]
Data annotation support isn't implemented yet (tracked by https://github.com/aspnet/EntityFramework/issues/107), so adding `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` does not alter the model.
