### ISSUE TITLE
 .Net Core 2.1 EntityFramework Error - Db tinyint column(C# byte) checked with == 1  converted in SQL as 1 as Flag at runtime.

### ISSUE THREAD

**Issue by rajeevanvgh** [dotnet/efcore#16122]
While trying to upgrade a .net core 2.0 Web API project to 2.1, I am getting an Exception "Type Flag is not a defined system type."
There are two columns  in db,  `Primary` and `Deleted`  which are of  datatype `tinyint` which we are facing problem, Corresponding .Net Core generated data type is byte .
Please find the details:

The following query throws exception at runtime. 

```C#
var query = await (from pl in _azureContext.Product.AsNoTracking()
                             where pl.Primary ==1 &&  pl.Deleted=0
                             select new Product()
                             {
                                 ProductId = pl.ProductId,
                                 ProductName = pl.ProductName
                             }).OrderBy(P => s.ProductName).ToListAsync<Product>();
```
1) The query generated internally as follows.

```sql
SELECT  [pl].[ProductId] , [pl].[ProductName]
      FROM [Products] AS [ps]
      WHERE ([pl].[Primary] = CAST(1 AS Flag)) AND ([pl].[Deleted] = CAST(0 AS Flag))
      ORDER BY [ProductName]
```
```
System.Data.SqlClient.SqlException (0x80131904): Type Flag is not a defined system type.
```

Could any one please help me on this.

### Further technical details
EF Core version: 2.1.11
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system:  Windows 10
IDE: (e.g. Visual Studio 2017 15.9.3)

**Comment by ajcvickers** [comment]
@rajeevanvgh Have you tried this on the 2.2.4 release?

**Comment by rajeevanvgh** [comment]
@ajcvickers  No. I was trying to upgrade to  2.1.11. 
The problem looks like scaffolding creates configuration properties as .HasColumnType("Flag") for tinyint and in the query if you check value like x.Primary == 1, the SQL query generated is changing 1 as  CAST(1 AS Flag)). If I use x.Primary == Convert.ToByte(1) it works.

**Comment by ajcvickers** [comment]
@rajeevanvgh Can you post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can identify the root cause.

**Comment by rajeevanvgh** [comment]
@ajcvickers. I have identified the issue. This will not require any entity framework fixes even though noticed some difference in SQL query construction.
The issue is as follows.
1) The SQL Server DB was earlier on premise,  and looks like the dbcontext was generated using scaffolding pointing to that db earlier.
2) The SQL Server DB was migrated to Azure and the connection string is updated and used from that. I was upgrading to EntityFramework Core 2.1 on this db.
3) After analysis Identified that there were few user defined datatypes like Flag of type tinyint which were not ported to Azure Instance.
4) In EntityFramework Core 2.0 it was working without any issues  and  the query filter x.Primary == 1 was translated as x.Primary = 1 in the generated SQL even though the .HasColumnType("Flag") was there in the configuration.
3)In EntityFramework Core 2.1  the query filter x.Primary == 1 was translated as x.Primary = CAST(1 AS Flag) in the generated SQL which is using the .HasColumnType("Flag") was there in the configuration.
5) I will change  .HasColumnType("Flag") to  .HasColumnType("tinyint") which is working.
Hence closing this ticket.  Thank you for your support.
