### ISSUE TITLE
Spatial query is taking too much time with NetTopology suite

### ISSUE THREAD

**Issue by DnyaneshwarShivbhakta** [dotnet/efcore#16135]
We have delivery & tracking application. We are sending live address point(latitude & longitude) from Mobile devices to the Web API & checking those addresses distance with delivery address point. When multiple carriers are online it's taking too much time. following is the query which is taking too much time. This query is taking more than10 minutes of time when we have multiple delivery boy delivering simultaneously.
``` csharp
 var deliveriesQuery = 
  (from a in db.AddressPointDelivery.Where(w => w.IsDelivered == false
    && activeRouteJobIDList.Contains(w.RouteJobId.Value))
   from b in db.BreadCrumb.Where(w => breadcrumbIDList.Any(bread => bread == w.Id))
   where
     Convert.ToDouble(a.Point.Distance(b.Point)) < 200
   select new
   {
     breadcrumbId = b.Id,
     AddressPointId = a.Id,
     ///jobID = rj.JobId,
     routeJobId = a.RouteJobId,
     isUndelivered = !a.IsDelivered,
     CreatedOn = b.CapturedAt
   });
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

### Further technical details
EF Core version: 2.2(found in project.csproj or packages.config)
Database Provider: Azure sql server 2017
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@DnyaneshwarShivbhakta Do the logs from EF contain a warning indicating that this is being evaluated on the client?

**Comment by DnyaneshwarShivbhakta** [comment]
no... I am not getting such warning

**Comment by DnyaneshwarShivbhakta** [comment]
any reply or comment on this issue from Entity framework core team?

**Comment by JanEggers** [comment]
@DnyaneshwarShivbhakta my guess is that activeRouteJobIDList or breadcrumbIDList is the bottleneck, 
try using joins instead of operations with precomputed lists. also have a look at the generated sql and look for missing indices etc..

**Comment by Prateek943** [comment]
@JanEggers  No, they are not the bottleneck. activeRouteJobIDList,breadcrumbIDList have hardly 10 or 20 records.Nonclustered index is already present on the column. I have 17 millions of data in my table and based on the activeRouteJobIDList I am fetching records in join

**Comment by DnyaneshwarShivbhakta** [comment]
@JanEggers  No, they are not the bottleneck. activeRouteJobIDList,breadcrumbIDList have hardly 10 or 20 records.Nonclustered index is already present on the column. I have 17 millions of data in my table and based on the activeRouteJobIDList I am fetching records in join.

**Comment by smitpatel** [comment]
@DnyaneshwarShivbhakta - Can you share definitions of `activeRouteJobIDList` & `breadcrumbIDList`?
In certain cases such Contains/Any caused client eval.

**Comment by DnyaneshwarShivbhakta** [comment]
```

                var activeRouteJobIDList = (from j in db.Job
                                            join rj in db.RouteJob on j.Id equals rj.JobId
                                            where j.IsActive == true && j.EndDate > DateTime.UtcNow
                                                 && carrierID == rj.CarrierId
                                            select new {RouteJobId=rj.Id });

var newBreadcrumbs = (from b in addressPoints

                                      select new BreadCrumb
                                      {
                                          CarrierId = carrierID,
                                          Point = geometryFactory.CreatePoint(new Coordinate(b.Longitude, b.Latitude)),
                                          Speed = b.Speed.GetValueOrDefault() * (Decimal)2.237,
                                          Direction = b.Direction,
                                          CapturedFrom = b.CapturedFrom,
                                          CapturedAt = b.CapturedAt,
                                          Accuracy = (Decimal)b.Accuracy,
                                          IsDisconnect = b.IsDisconnect,
                                          CreatedOn = DateTime.UtcNow,
                                          IsActive = true,
                                          CreatedBy = 0,
                                          ModifiedBy = 0,
                                          ModifiedOn = null,
                                          IsProcessed=false
                                      }).ToList();
 var breadcrumbIDList = (from b in newBreadcrumbs
                                            select b.Id).ToList();
```

**Comment by smitpatel** [comment]
Can you put `ToList` at the end of `activeRouteJobIDList` and see if the query works faster?

**Comment by DnyaneshwarShivbhakta** [comment]
@smitpatel  I tried with that as well.

**Comment by smitpatel** [comment]
I guess, at this point we would need the generated SQL to verify there is no client eval. That would also give us idea if the generated SQL is slow (bad perf at database level) or something in EF is taking much time.

**Comment by DnyaneshwarShivbhakta** [comment]
The amount of time for this query is very high only if we have multiple delivery boy tracking simultaneously. For single or 3-4 simultaneous delivery It wouldn't have this much issue

**Comment by mburbea** [comment]
I'd also remove this `Convert.ToDouble(a.Point.Distance(b.Point)) < 200`, as this trivial cast might prevent it from using your index.

**Comment by ajcvickers** [comment]
Closing as the reason this query is slow is due to not being sargable due to the conversion.

**Comment by mburbea** [comment]
It's not SARGability, but the fact that geospatial queries only get optimized for very specific queries in SQL server. In my testing, some forms the pointless convert didn't always break the optimization.
