### ISSUE TITLE
Cosmos: Distinct operator in queries

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16144]
Test: Distinct
System.ArgumentException : Distict query requires a matching order by in order to return a continuation token.
    If you would like to serve this query through continuation tokens, then please rewrite the query in the form 'SELECT DISTINCT VALUE c.blah FROM c ORDER BY c.blah' and please make sure that there is a range index on 'c.blah'.

**Comment by ajcvickers** [comment]
To test on Cosmos.

**Comment by ajcvickers** [comment]
@divega to look into order-by lifting.

**Comment by divega** [comment]
Here is the original orderby lifting spec: #16226.

**Comment by maumar** [comment]
Basic Distinct scenarios work now. Many are blocked due to lack of subqueries, meaning we can't do pushdown (e.g. customers.Distinct().OrderBy()) or customers.Distinct().Count()
