### ISSUE TITLE
EFCore Add Entity with childEntity Throw the same key is tracked 

### ISSUE THREAD

**Issue by Gavinluo** [dotnet/efcore#16171]
i`m trying to update my code from ef6 to efcore , in EF 6, give child wrong foregin key value, Context.Set.Add() not Check key . and after Add() , will triggered relationship fix-up(auto modify FK property), then SaveChange , but EF Core when Add() will throw key has already tracked

```c#
var defaultPk = "OneCrud_UnitTest";
var defaultPk2 = "OneCrud_UnitTest2";

var item1 = new item { ItemGID = defaultPk,ItemID = defaultPk,TS=DateTime.Now };
item1.itemDetail = new List<itemDetail>();

var detail1 = new itemDetail() //itemDetail HasKey(t => new { t.ItemGID,t.LineId});
{
    GUID = Guid.NewGuid().ToString(),
    ItemGID = defaultPk,//this is foregin key 
    LineId = 1
};

item1.itemDetail.Add(detail1);
unitOfWork.DataContext.Set<item>().Add((item1));
unitOfWork.Commit();

var item = itemRepository.GetByID(defaultPk);
var item2 = new item { ItemGID = defaultPk2 };


item2.ItemID = item2.ItemGID;
item2.TS = DateTime.Now;
item2.itemDetail = new List<itemDetail>();

item2.itemDetail.Add(new itemDetail {
    ItemGID = defaultPk, //in ef 6 will auto fix up to defaultPk2 after Add(), and not throw exception 
    LineId = 1,
    GUID = Guid.NewGuid().ToString(),
});

unitOfWork.DataContext.Set<item>().Add((item2)); // in ef core this line will throw exception "has tracked same key  ItemGID[OneCrud_UnitTest],LineId[1]"

unitOfWork.Commit();
```
may i disable the key check when add(), or fix up foreign key value by hand before call Add() method

### Further technical details
EF Core version: 
Microsoft.EntityFrameworkCore 2.2.4 
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.2
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.1.3)

**Comment by divega** [comment]
@Gavinluo could you provide the model corresponding to this code? It would be even better if you could provide a runnable code snippet that we can use to repro.

**Comment by Gavinluo** [comment]
@divega  you are so amazing , i have code a full demo and upload here.   https://github.com/Gavinluo/EFCoreSameKeyException . this demo use dbContext to operate data, in actually we use CurdRepository and UnitOfWork ,  i`m trying to update our product from ef6 to efcore,  it is difficult to modify business code  .

**Comment by ajcvickers** [comment]
@Gavinluo EF Core doesn't support using an incorrect value for the FK/PK in this code:
```C#
item2.itemDetail.Add(new itemDetail {
    ItemGID = defaultPk, //in ef 6 will auto fix up to defaultPk2 after Add(), and not throw exception 
    LineId = 1,
    GUID = Guid.NewGuid().ToString(),
});
```
In EF Core, if you want the value to be fixed up from the principal, then don't set it:
```C#
item2.itemDetail.Add(new itemDetail {
    LineId = 1,
    GUID = Guid.NewGuid().ToString(),
});
```
EF will use the value if it has been set, which means that if you do set it, then it needs to be set to the correct value.
