### ISSUE TITLE
Possible regression in EF Core 2.2.x

### ISSUE THREAD

**Issue by glatzert** [dotnet/efcore#16193]
I had an error message, stating that a specific property was no navigaton property after migrating from EF Core 2.0.x to 2.2.x.
The issue could be worked around, by renaming a specific property (see classes below).
Since I'm off-site I cannot provide the full stack trace currently, but I'll happily do so, if necessary.

### Steps to reproduce
Create a Model containing the following:

```c#
public class MyDbContext : DbContext {
  public DbSet<Order> Orders { get; set; }
  public DbSet<OrderDetail> OrderDetails { get; set; }
}

public interface IOrder {
  List<IOrderDetail> OrderDetails { get; }
}

public class Order : IOrder {
  public int Id { get; set; }

  public List<OrderDetail> OrderDetails { get; set; }

  [NotMapped]
  public List<OrderDetail> IOrder.OrderDetails => OrderDetails.OfType<IOrderDetail>().ToList();
}

public class OrderDetail : IOrderDetail {
  public int Id { get; set; }

  public int OrderId { get; set; }
  public Order Order { get; set; }
}
```

After renaming the `IOrder.OrderDetails`, it worked again.

I can provide the full source code, if you point out members of your team, who can/should get access to my private repository.

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win10-x64
IDE: VS 2019 (but independent of this)

**Comment by AndriySvyryd** [comment]
Confirmed fixed in 5.0. You can also remove `[NotMapped]` as a workaround
