### ISSUE TITLE
Allow all logging, diagnostics, and interception to be turned off

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#16197]
Implement a fast early bailout that means we don't do any of these thing and will avoid even initializing anything needed for these things.

**Comment by ajcvickers** [comment]
Or consider having a `Flags` enum to enable just the part you want.

**Comment by ajcvickers** [comment]
Consider not creating correlation IDs or timers when logging is not being used: see https://github.com/aspnet/EntityFrameworkCore/pull/16716#pullrequestreview-266543692

**Comment by roji** [comment]
Probably not needed after #24304.
