### ISSUE TITLE
Missing reference error when inheriting from CSharpMigrationsGenerator

### ISSUE THREAD

**Issue by EricStG** [dotnet/efcore#16216]
When upgrading to EF core 3.0 preview from 2.2, we're getting a missing namespace error for `Microsoft.EntityFrameworkCore.Migrations.Design`, as well as any type in that namespace.

```
The type or namespace name 'Design' does not exist in the namespace 'Microsoft.EntityFrameworkCore.Migrations' (are you missing an assembly reference?)
```

The issue stems from the change on how the package reference gets created for `Microsoft.EntityFrameworkCore.Design`. 

In version 2.2, we'd get this:
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.4" />
```
but in 3.0, we get this:
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0-preview6.19304.10">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

As a workaround, we can manually change the package reference by removing the `PrivateAssets` and `IncludeAssets` nodes.

I also don't see any reference to this change on https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes.

### Steps to reproduce
[EfCoreCustomMigration.zip](https://github.com/aspnet/EntityFrameworkCore/files/3321319/EfCoreCustomMigration.zip)

- Add `Microsoft.EntityFrameworkCore.Design` to project
- Create a class that inherits from `CSharpMigrationsGenerator`

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.0.0-preview5
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.0 Preview 2.0

**Comment by ajcvickers** [comment]
@bricelam to de-dupe.

**Comment by bricelam** [comment]
#11506

Manually changing the dependency is the correct way to handle this.
