### ISSUE TITLE
Contains & FreeText throws InvalidOperationException for dynamic columns

### ISSUE THREAD

**Issue by Enngage** [dotnet/efcore#16219]
I have following query that works perfectly:

```
DbContext.Foods.Where(m => EF.Functions.Contains(m.DisplayName, "apple&raw")).ToList();
```

In my scenario, however, I have only `IQueryable<T>` where I don't know what column is going to be used for searching. Using string as a reference causes `InvalidOperationException` to be thrown. I've been trying something in the sense of:

```
DbContext.Foods.Where(m => EF.Functions.Contains("DisplayName", "apple&raw")).ToList();
DbContext.Foods.Where(m => EF.Functions.Contains(m.GetType().GetProperty("DisplayName").Name, "apple&raw")).ToList();
DbContext.Foods.Where(m => EF.Functions.Contains(new Food().DisplayName, "apple&raw")).ToList();
```

But all of them fail. Is there a way of running the queries above successfully?

```
Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where __Functions_0.Contains([m].GetType().GetProperty("DisplayName").Name, "apple&raw")' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
```

### Steps to reproduce
Create full text search index on any column & try to use `FreeText` or `Contains` with property reference as string.

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2019 16.1.2

**Comment by smitpatel** [comment]
`DbContext.Foods.Where(m => EF.Functions.Contains(EF.Property<string>(m, "DisplayName"), "apple&raw")).ToList();

**Comment by Enngage** [comment]
Works great! Thank you :-)
