### ISSUE TITLE
The property 'ValidationFailure.AttemptedValue' could not be mapped

### ISSUE THREAD

**Issue by marcos-cruz** [dotnet/efcore#16247]
My class has a complex object and an enum safe pattern. I'm trying to add-migrations, the package manager console shows me the error below.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
The property 'ValidationFailure.AttemptedValue' could not be mapped, because it is of type 'object' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```
Detail: I have no field or property called 'ValidationFailure.AttemptedValue'

I'm using Visual Studio 2017 Professional - Version 15.9.13,
dotnet Standard 2.0
EntityFramework 2.2.4

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
    public class Representante : Pessoa
    {
        private IList<RepresentanteEmail> _emails;

        private IList<RepresentanteEndereco> _enderecos;

        private IList<RepresentanteTelefone> _telefones;

        public virtual IReadOnlyCollection<RepresentanteEmail> Emails
        {
            get { return _emails.ToArray(); }
        }

        public virtual IReadOnlyCollection<RepresentanteEndereco> Enderecos
        {
            get { return _enderecos.ToArray(); }
        }

        public virtual IReadOnlyCollection<RepresentanteTelefone> Telefones
        {
            get { return _telefones.ToArray(); }
        }


        protected Representante() : base()
        {
        }

        private Representante(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina, string razaoSocial, string nomeFantasia, Cnpj cnpj, InscricaoEstadual inscricaoEstadual, string inscricaoMunicipal) : base(id, idSistemaAntigo, status, dataCadastro, rotina, razaoSocial, nomeFantasia, cnpj, inscricaoEstadual, inscricaoMunicipal)
        {
        }

        private Representante(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina, string nome, string apelido, Cpf cpf, Rg rg) : base(id, idSistemaAntigo, status, dataCadastro, rotina, nome, apelido, cpf, rg)
        {
        }

        public static Representante CriarRepresentantePessoaFisica(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina, string nome, string apelido, Cpf cpf, Rg rg, ICollection<RepresentanteEmail> emails, ICollection<RepresentanteEndereco> enderecos, ICollection<RepresentanteTelefone> telefones)
        {
            Representante obj = new Representante(id, idSistemaAntigo, status, dataCadastro, rotina, nome, apelido, cpf, rg);

            obj.AtribuirEmails(emails);
            obj.AtribuirEnderecos(enderecos);
            obj.AtribuirTelefones(telefones);

            return obj;
        }

        public static Representante CriarRepresentantePessoaJuridica(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina, string razaoSocial, string nomeFantasia, Cnpj cnpj, InscricaoEstadual inscricaoEstadual, string inscricaoMunicipal, ICollection<RepresentanteEmail> emails, ICollection<RepresentanteEndereco> enderecos, ICollection<RepresentanteTelefone> telefones)
        {
            Representante obj = new Representante(id, idSistemaAntigo, status, dataCadastro, rotina, razaoSocial, nomeFantasia, cnpj, inscricaoEstadual, inscricaoMunicipal);

            obj.AtribuirEnderecos(enderecos);
            obj.AtribuirTelefones(telefones);
            obj.AtribuirEmails(emails);

            return obj;
        }
    }

    public abstract class Pessoa : Entity
    {
        private string _nome;
        private string _nomeFantasia;

        public TipoPessoa TipoPessoa { get; private set; }

        public string Nome
        {
            get => _nome;
            private set => _nome = (value == null ? "" : value.RemoverEspacosDuplos().ToUpper().Trim());
        }

        public string Apelido
        {
            get => _nomeFantasia;
            private set => _nomeFantasia = (value == null ? "" : value.RemoverEspacosDuplos().ToUpper().Trim());
        }

        public Cnpj Cnpj { get; private set; }

        public InscricaoEstadual InscricaoEstadual { get; private set; }

        public string InscricaoMunicipal { get; private set; }

        public Cpf Cpf { get; private set; }

        public Rg Rg { get; private set; }

        protected Pessoa() { }

        protected Pessoa(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina, string nome, string apelido, Cpf cpf, Rg rg) : base(id, idSistemaAntigo, status, dataCadastro, rotina)
        {
            TipoPessoa = TipoPessoa.Fisica;
            Nome = nome;
            Apelido = apelido;
            Cpf = cpf;
            Rg = rg;
        }

        protected Pessoa(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina, string razaoSocial, string nomeFantasia, Cnpj cnpj, InscricaoEstadual inscricaoEstadual, string inscricaoMunicipal) : base(id, idSistemaAntigo, status, dataCadastro, rotina)
        {
            TipoPessoa = TipoPessoa.Juridica;
            Nome = razaoSocial;
            Apelido = nomeFantasia;
            Cnpj = cnpj;
            InscricaoEstadual = inscricaoEstadual;
            InscricaoMunicipal = inscricaoMunicipal;
        }
    }

    public abstract class Entity
    {
        private Guid _id;

        private DateTime _dataCadastro;

        private TipoProcesso _rotina;

        public Guid Id
        {
            get => _id;
            private set
            {
                if (value.Equals(Guid.Empty) || value == null)
                {
                    _id = Guid.NewGuid();
                }
                else
                {
                    _id = value;
                }
            }
        }

        public string IdSistemaAntigo { get; private set; }

        public EntityStatus Status { get; private set; }

        public DateTime? DataCadastro
        {
            get => _dataCadastro;
            private set
            {
                if (!value.HasValue || value == null)
                {
                    AtribuirDataCadastro(DateTime.Now);
                }
                else
                {
                    AtribuirDataCadastro(value.Value);
                }
            }
        }

        public DateTime UltimaMovimentacao { get; private set; }

        public TipoProcesso Rotina
        {
            get => _rotina;
            private set
            {
                _rotina = value;

                if (_rotina == TipoProcesso.Adicionar)
                {
                    if (_id.Equals(Guid.Empty) || _id == null)
                    {
                        _id = Guid.NewGuid();
                    }

                    if (_dataCadastro == DateTime.MinValue)
                    {
                        AtribuirDataCadastro(DateTime.Now);
                    }
                }
            }
        }

        public ValidationResult ValidationResult { get; protected set; }

        protected Entity() { }

        protected Entity(Guid id, string idSistemaAntigo, EntityStatus status, DateTime? dataCadastro, TipoProcesso rotina)
        {
            Rotina = rotina;
            Id = id;
            IdSistemaAntigo = string.IsNullOrEmpty(idSistemaAntigo) ? "" : idSistemaAntigo.Trim();
            Status = status;
            DataCadastro = dataCadastro;
        }
    }




Add-Migration InitialCreate -Context BusinessContext -OutputDir Migrations\SqlServer\Business
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@marcos-cruz Looks like it's because EF is trying to map:
```C#
public ValidationResult ValidationResult { get; protected set; }
```
If this property is not intended to be mapped to a database column, then use `[NotMapped]` or `Ignore` in `OnModelCreating` to prevent EF from mapping it.

**Comment by marcos-cruz** [comment]
Hello Arthur,This property is already being ignored, but it still does not work.I feel the problem is when I join the EntityStatus (Enum pattern safe) class and complex object Cpf, Cnpj.Abraços,Marcos Cruz0 XX 11 94261-9856Skype: socramzurcmarcoscruz@terra.com.brhttps://br.linkedin.com/in/cruzmarcosEm Ter 25/06/19 19:44, Arthur Vickers notifications@github.com escreveu:@marcos-cruz Looks like it's because EF is trying to map:public ValidationResult ValidationResult { get; protected set; }If this property is not intended to be mapped to a database column, then use [NotMapped] or Ignore in OnModelCreating to prevent EF from mapping it.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by marcos-cruz** [comment]
> 

            builder.Property(entity => entity.Id)
                .IsRequired();

            builder.Property(entity => entity.Status)
                .HasColumnType($"varchar({EntityStatus.TamanhoDefaultCodigo})")
                .HasColumnName("Status")
                .HasConversion(
                    s => s.Codigo,
                    s => EntityStatus.ObterPorCodigo(s));

            builder.Property(entity => entity.DataCadastro)
                .IsRequired();

            builder.Property(entity => entity.UltimaMovimentacao)
                .IsRequired();

            builder.Ignore(entity => entity.Rotina);

            builder.Ignore(entity => entity.ValidationResult);
            
builder.OwnsOne(representante => representante.Cnpj, cnpj =>
            {
                cnpj.Property(representante => representante.NumeroCnpj)
                    .HasColumnType($"varchar({Cnpj.TamanhoCnpj})")
                    .HasColumnName("Cnpj")
                    .IsRequired();
            });

> 
This property is already being ignored, but it still does not work.

I feel the problem is when I join the EntityStatus (Enum pattern safe) class and complex object Cnpj.

**Comment by ajcvickers** [comment]
@marcos-cruz Thanks for the additional details. We're going to need to be able to reproduce this to make progress. Please post a small, runnable project/solution or _complete_ code listing that demonstrates the behavior you are seeing.

**Comment by marcos-cruz** [comment]
@ajcvickers Thanks for your answers. In this link you have access to a small project, where you can reproduce the error.

[Aguaria.zip](https://github.com/aspnet/EntityFrameworkCore/files/3331697/Aguaria.zip)

To play, do the following:

1. Change the connectionstring in the appsettings file to a local bank
2. Set as startup the project Bigai.Aguaria.Presentation.Migration
3. In Package manager console select the project Bigai.Aguaria.Infra.Data
4. Type: Add-Migration InitialCreate -Context AguariaContext -OutputDir Migrations \ SqlServer \ Aguaria

**Comment by ajcvickers** [comment]
@marcos-cruz It looks like there are `ValidationResult` properties on multiple entity types. Specifically, all types that inherit from `ValueObject<>` or `Entity`. When I ignore these in all places (for example, by using the `[NotMapped]` attribute, then I can no longer reproduce the issue.

**Comment by marcos-cruz** [comment]
Thanks for you attention.
