### ISSUE TITLE
EF 3 - Migration Error

### ISSUE THREAD

**Issue by borodaenko-clearscale** [dotnet/efcore#16274]
Hello.

I have got the same issue:
https://github.com/aspnet/EntityFrameworkCore/issues/15147

I am developing in Windows, using .net core 2.0, and am having the following error when I do dotnet ef migrations add NewMigration:

"Unable to create an object of type 'OAuthContext'. For the different patterns supported at design time".

I can not show the code, because it is a closed project. But I can say for sure that it used to work. I use git, so I'm sure that my previous commits worked.

Thus, before the command Add-Migration and update-database worked, after a few days, they no longer work.

In the previously closed issue you requested the .csproj file:

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
      <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.16" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyProject.Core\MyProject.Core.csproj" />
    </ItemGroup>

</Project>

**Comment by borodaenko-clearscale** [comment]
I avoided this error.
This error occurs if the "Set as StartUp Project" is specified as a console. 
If you fix the "Set as StartUp Project" on the Asp.net Core Website, the problem does not occur.
In the Nuget console, you can only select the Default Project. 
I think that commmands Add-Migration and Update-database should not be dependent on which project is set as the starting point.

**Comment by borodaenko-clearscale** [comment]
ConsoleProject.csproj:

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyProject.Core\MyProject.Core.csproj" />
    <ProjectReference Include="..\MyProject.Repositories\MyProject.Repositories.csproj" />
  </ItemGroup>
</Project>

**Comment by borodaenko-clearscale** [comment]
Sorry, I cann't attach the console .csproj. Github doesn't show it correctly.
But .csproj is very simply, it just simple console project on netcoreapp2.2

**Comment by ajcvickers** [comment]
@borodaenko-clearscale Migrations needs to run your code in order to create the model from which migrations are generated. This requires it knows the startup project.
