### ISSUE TITLE
Consider moving SequentialGuidValueGenerator to core

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1627]
Currently it lives in the SQL Server provider, but this seems to be generally useful functionality.

**Comment by ajcvickers** [comment]
We're already doing this as part of the API review changes.

**Comment by divega** [comment]
Ah, I didn't see it moving in the PR I was looking at.

**Comment by ajcvickers** [comment]
Moving from one assembly to another seemed to be a bit more than just naming/namespace, so I decided to not include it in that PR. It will be in the one I am working on now.

**Comment by divega** [comment]
Got it.
