### ISSUE TITLE
EF core Include exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16288]
the exeception is as following:

```
The expression should represent a property access: 't => t.MyProperty'. 
To target navigations declared on derived types, specify an explicitly typed lambda parameter of the target type, E.g. '(Derived d) => d.MyProperty'.
```

my code: 

```C#
List<T> scaleList = null;
try
{
    scaleList = this.test(queryTem). ToList(); 
}

public IIncludableQueryable<T,object> test(T instance) 
{
    Type tType = typeof(T);
    PropertyInfo[] propertyInfos = tType.GetProperties(); 
    ArrayList listArray = new ArrayList(); 
    IIncludableQueryable<T, object> a = null; 
    
	foreach (var propertyInfo in propertyInfos)
    {
        {
            if (propertyInfo.PropertyType != typeof(int) && propertyInfo.PropertyType != typeof(string))
            {
                a = DbSets.Include(  s  => propertyInfo.GetValue(s));
            }
        }
    }
	
    return a;
}
```
		
There is just one object type in the T class,so the loop is unused, it broke down when first in the loop,I want to know is the Include Method can just write as 
```C#
DbSets.Include(  s  => s.myList)
```

Thank you for your ansower.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/618805/ef-core-include-exception.html
VSTS ticketId: 936402_
_These are the original issue comments:_

小鸡蛋白 on 6/24/2019, 05:28 PM (45 hours ago): I had done many tests,you just see one line "var list=DbSets.Include(s=>propertyInfo.GetValue(s)).ToList();"it will occur a exception like the first writton

Visual Studio Feedback System on 6/24/2019, 07:53 PM (43 hours ago): <markdown>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
Can you explain in more detail what you are trying to achieve?

**Comment by w391457094** [comment]
I want to write an sql dal class with EF Core by using reflection and genericity.And in this way ,because of the T,I can't get the specific properties so that I can't wirte the Include method with this syntax "s  => s.myProperty".I can only reflect its properties,so I must write as this way "s  => propertyInfo.GetValue(s)"

**Comment by ajcvickers** [comment]
@w391457094 Have you tried calling the overload of `Include` that takes a string? That's significantly easier to deal with in situations where you are calling generic code from Reflection.

**Comment by w391457094** [comment]
> overload

I'm sorry that I can't understand what you said.How can I take a string with Include method?The Official definition of the Include is as following.It's just an Expression.

public static IIncludableQueryable<TEntity, TProperty> Include<TEntity, TProperty>([NotNullAttribute] this IQueryable<TEntity> source, [NotNullAttribute] Expression<Func<TEntity, TProperty>> navigationPropertyPath) where TEntity : class;

**Comment by ajcvickers** [comment]
@w391457094 See the documentation here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.include?view=efcore-2.1

Notice that two methods are listed under "Overloads". One takes an expression to represent the navigation property, which is great for writing normal code, but hard to use dynamically. The other method does the same thing, but it takes a string which is just the name of the navigation property to load. It's much easier to construct this name than to build the expression tree, so I'm suggesting that that's what you do.

**Comment by w391457094** [comment]
@ajcvickers It's worked !Thankyou very much .
