### ISSUE TITLE
Lazy Loading navigation properties returns 'System.InvalidOperationException'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16284]
[Original Post](https://stackoverflow.com/questions/56190607/lazy-loading-navigation-properties-returns-system-invalidoperationexception?noredirect=1#comment99043766_56190607")

I've been migrating a VB.net application using EF6 to a C# .Net Core app using EF-Core 3.0. I've always been using EF as DB-First. 
With EF-Core, I need to specify the way I want to load my values. 
Because I often need to access many navigation properties (links to other table through FKs), I'd rather to a Lazy Load than managing Eager Loads. 
But whenever I wanna do so, i get this error on the naviguation properties 

```
((Castle.Proxies.WillyDemandesProxy)willyDemandes).IdPartNavigation threw an exception of type 'System.InvalidOperationException' 
:  Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.LazyLoadOnDisposedContext
Warning: An attempt was made to lazy-load navigation property 'IdPartNavigation' on entity type 'WillyDemandesProxy' after the associated DbContext was disposed.'. 
This exception can be suppressed or logged by passing event ID 'CoreEventId.LazyLoadOnDisposedContextWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
```

Table <strong>WillyDemandes</strong> is linked by foreign key to table <strong>Parts</strong> using <strong>WillyDemande.Id_Part</strong> and <strong>Parts.ID</strong>.

When you scaffold your DbContext using EF-Core DB-First, it creates virtual properties called "<strong>Navigation Properties</strong>" in order for you to easily get access to the linked info in other tables.

The exception is thrown whenever you try to access IDPartNavigation. Here's [an example](https://developercommunity.visualstudio.com/storage/attachments/74446-navig.png)

It also happens not 100% of the time.

Any ideas?

<strong>Context</strong>

```C#
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
            => optionsBuilder
        .UseLazyLoadingProxies()
        .UseSqlServer("Server=TRBSQL02;Database=Info_Indus;Trusted_Connection=True;");
```

<strong>Function</strong>

```C#
        static public WillyDemandes GetFirst()
        {


            using (Info_IndusContext conn = new Info_IndusContext())
            {
                WillyDemandes willyDemandes;

                    willyDemandes = conn.WillyDemandes
                        .Where(x => x.Statut == Statuts.EnTest.ToString() &amp;&amp; x.Username == Environment.UserName)
                        //.Include(x=>x.IdPartNavigation)
                        .OrderBy(x => x.Priority)
                        .ThenBy(x => x.Id)
                        .FirstOrDefault();

                if (willyDemandes != null)
                {
                    willyDemandes.Statut = Statuts.EnTraitement.ToString();
                    willyDemandes.ServerName = Environment.MachineName;
                    willyDemandes.DateDebut = DateTime.Now;
                    conn.SaveChanges();
                    conn.Entry(willyDemandes).GetDatabaseValues();
                    conn.Entry(willyDemandes).Reload();
                }


                return willyDemandes;
            }
        }
```
		
### 05/21/2019

The error seems to be related to the range of DbContext. 
It happens when you combine <strong>USING</strong> and <strong>PROXIES</strong>.

I've written another definition of my function but this time passing the connection through parameters instead of creating it inside the function with <strong>USING</strong>. The proxies are then available wherever DbContext is alive.

```C#
        static public WillyDemandes GetFirst(Info_IndusContext conn)
        {
            WillyDemandes willyDemandes;

                willyDemandes = conn.WillyDemandes
                    .Where(x => x.Statut == Statuts.EnTest.ToString() &amp;&amp; x.Username == Environment.UserName)
                    //.Include(x=>x.IdPartNavigation)
                    .OrderBy(x => x.Priority)
                    .ThenBy(x => x.Id)
                    .FirstOrDefault();


            if (willyDemandes != null)
            {
                willyDemandes.Statut = Statuts.EnTraitement.ToString();
                willyDemandes.ServerName = Environment.MachineName;
                willyDemandes.DateDebut = DateTime.Now;
                conn.SaveChanges();
                conn.Entry(willyDemandes).GetDatabaseValues();
                conn.Entry(willyDemandes).Reload();
            }


            return willyDemandes;


        }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/576190/lazy-loading-navigation-properties-returns-systemi.html
VSTS ticketId: 896486_
_These are the original issue comments:_

Visual Studio Feedback System on 5/21/2019, 07:45 PM (34 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
Everything here seems by-design. As you say, the exception you get is because you're attempting to use the context after it has been disposed, which is by-design.

Please let us known if there is something here that you think should be changed.
