### ISSUE TITLE
Improve exceptions we throw when something cannot be translated to the server query

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#16286]
We would like to add some helpful wording (TBD) and a fwlink (https://go.microsoft.com/fwlink/?linkid=2097910) when our new LINQ implementation throws because it cannot translate something to the server. This can help customers moving from 2.x to 3.0 given [the client eval breaking change](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client) but it can be generally useful based on our experience with previous LINQ implementations that restricted client eval.

**Comment by smitpatel** [comment]
Related #16133
