### ISSUE TITLE
Tips on how to disable caching of IModel

### ISSUE THREAD

**Issue by kewinbrand** [dotnet/efcore#16296]
I have um app that permits the user to dinamically create custom fields.
Googling a bit found some old answers in EF6 involving IModelCacheKeyFactory that I think does not apply to ef core.
After digging a bit in ef implementation I found that in DbContextOptionsBuilder we can UseModel and pass a ModelBuilder. Is this a good approach to accomplish my needs? If so, ModelBuilder needs ConventionSet that I do not know where to get from.

Could you shed some light?

Thank you so far.

**Comment by ajcvickers** [comment]
@kewinbrand Model caching is very important for performance; if a new model is built for every context instance, then perf will be poor. So disabling it entirely is usually not the way to go.

The recommended way to change when a new model is cached is [with `IModelCacheKeyFactory` as documented](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model). (Note that this has always been part of of EF Core; I don't believe it ever existed in EF6.)
