### ISSUE TITLE
QUESTION: Identity updates with port from EF 6 to EF Core

### ISSUE THREAD

**Issue by saif-momin** [dotnet/efcore#16304]
I have an application with EF6 and Asp.Net Identity, targeting .NET 4.6.1. I am **not** on ASP.NET Core. I am wishing to port to EF Core. Is there an identity library for EF Core running on .NET 4.6.1?

**Comment by ajcvickers** [comment]
@saif-momin I think it should be possible to do this with EF Core 2.2 and ASP.NET Core 2.2. See https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server.

However, EF Core 3.0 does not support running on .NET Framework. You must have .NET Core 3.0. This is also true for most of ASP.NET Core, although some of the Identity components will run on .NET Framework, but not any parts that use EF Core, so it probably doesn't help.)
