### ISSUE TITLE
Query: Naked queryables in projection

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16314]
```C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Select_correlated_filtered_collection_works_with_caching(bool isAsync)
        {
            return AssertQuery<CogTag, Gear>(
                isAsync,
                (ts, gs) => ts.OrderBy(t => t.Note).Select(t => gs.Where(g => g.Nickname == t.GearNickName)),
                assertOrder: true,
                elementAsserter: CollectionAsserter<Gear>(g => g.Nickname, (e, a) => Assert.Equal(e.Nickname, a.Nickname)));
        }
```

Here in projection `gs.Where(…)` being used, so return type of result becomes `IEnumerable<IQueryable<Gear>>`, since there is no navigation info, we create `List<Gear>` which cannot be used to return `IQueryable<Gear>`

We can either put AsQueryable after list or disallow such query and force users to write ToList or some other method to remove IQueryable.

In 2.x, we did N+1 eval for such queries so we had an internal Queryable, which used to run query to server, when enumerating the queryable in projection.

**Comment by ajcvickers** [comment]
Note from triage: throw a better exception message here.

**Comment by smitpatel** [comment]
Also enable tests for #17241

**Comment by smitpatel** [comment]
Also consider scenario in https://github.com/aspnet/EntityFrameworkCore/issues/13745 when DbSet is projected.

**Comment by smitpatel** [comment]
Removing from backlog to re-discuss priority. Many linked issues.

**Comment by smitpatel** [comment]
Plus projecting `IOrderedEnumerable`, since we materialize into a list, that also fails. There is no public collection type which implements that inferface either. Currently it fails when we convert the ordering from enumerable to queryable since types changed.

**Comment by mwwhited** [comment]
Why did you make the detection throw an exception on all subqueries instead of just those that are materialized on the external model projection?  They way you made this "fix" breaks subqueries that are never materialized with type mismatches.  

it is no longer possible to do this...
```
var query = from e1 in db.Table1
                    let subLookup = db.Table2.Where(..some filter...)
                    select new {
                        e1.Id,
                        counts = subLookup.Count(),
                        evenCounts = subLookup.Count(i=>i.PropNumber % 2 == 0),
                        total = subLookup.Sum(i=>i.Price)
                     };
```
yeah... I just have to add `.ToString()` after the `.Where(...)` but this now break hundreds of service operations at runtime and mitigatin will basically require revisting and testing large portions of complex applications.  With no means to detect these changes without manually executing ever query.

**Comment by roji** [comment]
@mwwhited can you please open a new issue with a minimal, runnable code sample that shows the exception being thrown?

**Comment by mwwhited** [comment]
Having sub-queries with district causes similar issues.  Is there a way to globally disable this functionality?  No one requested this feature and it is preventing the ability from upgrading from .Net Core 3.1 without full end to end testing of entire platforms.

**Comment by roji** [comment]
@mwwhited see https://github.com/dotnet/efcore/issues/23302#issuecomment-1403766807
