### ISSUE TITLE
TryValidateObject should use fluent model builder configuration

### ISSUE THREAD

**Issue by HakanL** [dotnet/efcore#16317]
Currently TryValidateObject is only using the data annotation attributes on the models, but since it's perfectly valid to use fluent configuration (the Scaffold-DbContext command is using that for example) I think the TryValidateObject should be able to use the fluent metadata (like HasMaxLength, etc) to validate the model as well.

**Comment by smitpatel** [comment]
Who owns TryValidateObject? It is not part of EF Core.

**Comment by HakanL** [comment]
Oh, my bad, I thought it was. It's in System.ComponentModel.DataAnnotations.Validator. Where's the correct place for this issue then?

**Comment by smitpatel** [comment]
https://github.com/dotnet/corefx/issues
