### ISSUE TITLE
EFCore Use timestamps to control concurrency problems

### ISSUE THREAD

**Issue by grantgonggithub** [dotnet/efcore#16329]
EFCore Use timestamps to control concurrency problems

 follow the link below:
_https://github.com/aspnet/EntityFrameworkCore/issues/16236_

_This looks like a MySQL database provider issue. I'm not sure what the mapping was in EF6 when using MySQL, but it sounds like the EF Core provider will need to support the same things for this to work. I suggest you follow up at: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql_

### **but, it's not "Pomelo.EntityFrameworkCore.MySql" problem, it's the same error when I switch to sqlserver, so it's still EFCore problem**

**Comment by divega** [comment]
Closing in favor of the original issue https://github.com/aspnet/EntityFrameworkCore/issues/16236, since there is more information there.
