### ISSUE TITLE
Disabling Auto Transactions 

### ISSUE THREAD

**Issue by nebojsajsimic** [dotnet/efcore#16332]
Hi,
I am trying to use EF but i have difficulties with transaction wrapper,
 main problem is that my data is on a linked server over a driver and that source does not support transactions.
So is there any possibility to use SaveChanges() without wrapping queries in transaction???
Or 
Is it possible to get list of all queries that will be executed on SaveChanges(), than execute it as parameter in procedure outside any transaction controll.

THANK YOU FOR RESPONSE.

**Comment by ajcvickers** [comment]
@nebojsajsimic `context.Database.AutoTransactionsEnabled = false;`

**Comment by nebojsajsimic** [comment]
Nope database does not contain autotransactionenabled........ :(

**Comment by DubravkaTrampa** [comment]
Moze li hint koji driver je u pitanju?

**Comment by ajcvickers** [comment]
@nebojsajsimic Are you using EF6 or EF Core? If EF Core, then which version?

**Comment by nebojsajsimic** [comment]
@ajcvickers  EF 6.2

**Comment by nebojsajsimic** [comment]
@DubravkaTrampa  Neki koji ne podrzava transakcije :), nije poznato koji je driver.

**Comment by ajcvickers** [comment]
@nebojsajsimic EF6 doesn't support this. I'm not aware of a way to stop EF6 creating transactions.

**Comment by nebojsajsimic** [comment]
@ajcvickers
Is this possible with EF Core?
And also, i did not get any answer on second question or the answer is same ... That not supported ?

**Comment by ajcvickers** [comment]
@nebojsajsimic Yes, my first answer was for EF Core since this is the GitHub repo for EF Core. (The one for EF6 is https://github.com/aspnet/EntityFramework6.)

For the second question, you might be able to use [database interception](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/logging-and-interception) to do this, but it would likely be quite difficult.

**Comment by nbon12** [comment]
I tried this:
`context.Database.AutoTransactionsEnabled = false;`
but I'm still seeing 
```
Unhandled exception. System.InvalidOperationException: The connection is already in a transaction and cannot participate in another transaction.
```
after trying to start my own transaction:

```C#
dbContextEf.Database.AutoTransactionsEnabled = false;
            //Console.WriteLine($"[{dbContextEf.Database.GetDbConnection().Database}] Begin Migrating Tenant {tenantSchema?.Name} transactional business database... (may take awhile)");
            IDbContextTransaction transaction = null;
            try
            {
                using(transaction = await dbContextEf.Database.BeginTransactionAsync())
                {
...
```

any thoughts?

**Comment by AndriySvyryd** [comment]
@nbon12 That behavior doesn't depend on `context.Database.AutoTransactionsEnabled`. You might be starting another transaction elsewhere. Open a new issue with a small repro project.
