### ISSUE TITLE
Consider supporting deleting database snapshot files of old migrations

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#16331]
Since our application is slowly accumulating a lot of database migrations, compiling is starting to take a while (compiling + Roslyn analyzers). 

The biggest part of compilation is spend on database snapshots from old migrations. So it would be great if they could be deleted, if I don't want to support reverting those migrations.

See @bricelam 's answer on StackOverflow: https://stackoverflow.com/a/47060795/5473409
I stumbled upon this answer when trying to: [Find a recommended way to clean old EFCore migrations](https://stackoverflow.com/questions/56803788/recommended-way-to-clean-old-entity-framework-core-migrations)

### Further technical details
EF Core version: 2.0.0-2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 (1903)
IDE: VS 2019 16.1.3

**Comment by ajcvickers** [comment]
@nphmuller This is basically tracked by #2174 which is about squashing migrations. Until that feature is implemented, it should be possible to workaround this by manually deleting or scripting deletions, as Brice says in his post.
