### ISSUE TITLE
Capture QueryBaseline.cs in CI

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#16349]
When SQL assertions fail, we get QueryBaseline.cs that provides the full SQL output. We should capture that in CI runs to help diagnose problematic tests etc.

**Comment by bricelam** [comment]
Just need to add it to the build artifacts like we do the packages:

https://github.com/aspnet/EntityFrameworkCore/blob/8efc3ad233f0f3e59434bbdd0d54fdeb560d0253/azure-pipelines.yml#L85-L92

See [the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops) for more info.

**Comment by smitpatel** [comment]
We have artifacts/logs available in build. Can we also add TestResults? the HTML format of test results is better than .log files.

**Comment by bricelam** [comment]
@smitpatel Is this still relevant after migrating to Helix?

**Comment by smitpatel** [comment]
Not needed anymore. Generally failures are indicative of which test failed and what kind of SQL we had.
