### ISSUE TITLE
ServiceProviderCache adds more and more IServiceProviders when running integration tests

### ISSUE THREAD

**Issue by mlassbo** [dotnet/efcore#16369]
When running .NET Core integration tests using WebApplicationFactory the ServiceProviderCache seems to add more and more IServiceProviders for each test until the limit of twenty is reached. By then a warning is logged or an error is thrown depending on how it's configured.

If the DbContext is configured to throw an error, this is the exception thrown:

```
Exception message:
System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.ManyServiceProvidersCreatedWarning: More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling UseLoggerFactory passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. Consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.ManyServiceProvidersCreatedWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
Stack trace:
at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.ManyServiceProvidersCreatedWarning(IDiagnosticsLogger`1 diagnostics, ICollection`1 serviceProviders)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_EntityFinderFactory()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_Finder()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues)
```

### Steps to reproduce
https://github.com/mlassbo/ServiceProviderCacheProblem

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.3

**Comment by ajcvickers** [comment]
The issue here is that each test is effectively spinning up a completely new web app. This means that services we get from ASP.NET are different every test, which in turn means a new internal service provider for every test.

@mlassbo The current workarounds is to manage the internal service provider manually using `DbContextOptionsBuilder.UseInternalServiceProvider`. However, it's also worth mentioning that building and throwing away so much for each test could end up being very slow. This is both because setting everything up is a lot of work, and also because the caching that is set up is usually very important for good perf.

Notes for triage:

Things should be better in 3.0, since we don't need to build a new service provider for a new `ILoggerFactory`, and we don't depend on `IMemoryCache` anymore. It would be useful to know if there are other services that can cause this--possibly `IConfiguration` for example. 

The workaround for 3.0 is also easier, since we added `options.EnableServiceProviderCaching(false)`.

**Comment by mlassbo** [comment]
Thanks @ajcvickers! Your workaround works fine.

Regarding integration test performance we've not run into problems with that yet. For each service we usually have about 50-100 integration tests that hit the database and they run in a few seconds. Spinning up a new web app for each test feels like a comfy solution to minimize the risk of test ordering issues (apart from the occasional shared-mutable-state-in-third-party-component-problem.. ;-)).

Thanks for your attention on this issue and for superb work on .NET Core and EF Core!

**Comment by guardrex** [comment]
@ajcvickers A couple of quick ❓ ...

> The workaround for 3.0 is also easier, since we added `options.EnableServiceProviderCaching(false)`.

For 3.0, are you saying to **_replace_** `options.UseInternalServiceProvider(serviceProvider);` with `options.EnableServiceProviderCaching(false)` ... **_or add_** `EnableServiceProviderCaching`?

According to IntelliSence: If calling `UseInternalServiceProvider`, then calling `EnableServiceProviderCaching` no-ops.

Next, I'm thrown off by the packages/namespace changes for EF Core vis-a-vis leaving `App` metapackage. Either of these aren't immediately obvious to the app (namespace/package-wise) ... IntelliSence seems to know what they are (i.e., finds and describes them in VS UI), but I can't call either of them ...

> 'IServiceProvider' does not contain a definition for ...

<img width="578" alt="Capture" src="https://user-images.githubusercontent.com/1622880/63186231-889daf80-c021-11e9-875f-e58ab18e68c6.PNG">

**Comment by guardrex** [comment]
No, I'm still having trouble with packages/namespaces. IntelliSense knows what these are, but I can't get them to light up for the app. Any tips?

<img width="578" alt="Capture" src="https://user-images.githubusercontent.com/1622880/63187767-4d9d7b00-c025-11e9-9187-80b6bffc2b6f.PNG">

**Comment by ajcvickers** [comment]
@guardrex Please file a new issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ChristopherHaws** [comment]
I have run into this issue as well when running integration tests with the InMemory database provider. I tried to use `EnableServiceProviderCaching(false)` but found that my tests took over 4 min to run (compared to 40 seconds in EF Core 2.2). I was able to just follow the info in the error to disable to ignore the warning/error and all my tests still work and they run in around 45 seconds like they did in v2.2.

```csharp
.ConfigureWarnings(x =>
{
    x.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning);
})
```

**Comment by ajcvickers** [comment]
@ChristopherHaws It sounds like some tests are sharing an internal service provider, but that still many are being created. A better way forward would be to find out why so many internal service providers are being created and avoid doing that.

**Comment by ChristopherHaws** [comment]
@ajcvickers We have test classes that contain more the 20 unit tests and each test has its own `InMemoryDatabaseRoot` to prevent the tests from conflicting.

**Comment by Cooksauce** [comment]
@ajcvickers I'm hitting the situation @ChristopherHaws is describing as well.
Looking at the [source](https://github.com/dotnet/efcore/blob/master/src/EFCore/Internal/ServiceProviderCache.cs) it looks like the cache is static - and thus shared across different tests.

Using a group of tests like this:
```
[Test]
void TestA()
{
  using var rootProvider = new ServiceCollection()
    .AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase(nameof(MyDbContext)))
    .BuildServiceProvider();

  using (var scope = rootProvider.CreateScope())
  {
    // Test stuff
  }
}

[Test]
void TestB()
{
  using var rootProvider = new ServiceCollection()
    .AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase(nameof(MyDbContext)))
    .BuildServiceProvider();

  using (var scope = rootProvider.CreateScope())
  {
    // Test other stuff
  }
}

```

In this case, it seems the two tests are sharing an EF Core service provider cache. So when you run more 20 than tests, this error gets triggered. Run any of them in isolation and the error is not hit.

@ajcvickers Would you agree this is what is happening?
If so, is this by design?
Is there anyway to scope the cache to a given root `IServiceProvider`? (Or at least the error logic)

_Note: I've never hit this error in production._

**Comment by ajcvickers** [comment]
@Cooksauce The code you posted should not cause multiple service providers to be cached in EF Core 3.1 or later. If you're seeing this, then please file a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Cooksauce** [comment]
@ajcvickers
Apologies. The code above causes `TestA` and `TestB` to share the same backing store. The code I was actually using was this. Is it expected to cache multiple service providers?
```
[Test]
void TestA()
{
  using var rootProvider = new ServiceCollection()
    .AddSingleton<InMemoryDatabaseRoot>()
    .AddDbContext<MyDbContext>((sp, o) => o.UseInMemoryDatabase(nameof(MyDbContext), sp.GetService<InMemoryDatabaseRoot>()))
    .BuildServiceProvider();

  using (var scope = rootProvider.CreateScope())
  {
    // Test stuff
  }
}

[Test]
void TestB()
{
  using var rootProvider = new ServiceCollection()
    .AddSingleton<InMemoryDatabaseRoot>()
    .AddDbContext<MyDbContext>((sp, o) => o.UseInMemoryDatabase(nameof(MyDbContext), sp.GetService<InMemoryDatabaseRoot>()))
    .BuildServiceProvider();

  using (var scope = rootProvider.CreateScope())
  {
    // Test other stuff
  }
}
```


After experimenting a bit more it seems the better way would be to give the database a unique name per test:
```
[Test]
void TestA()
{
  var dbName = Guid.NewGuid().ToString();
  using var rootProvider = new ServiceCollection()
    .AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase(dbName))
    .BuildServiceProvider();

  using (var scope = rootProvider.CreateScope())
  {
    // Test stuff
  }
}

[Test]
void TestB()
{
  var dbName = Guid.NewGuid().ToString();
  using var rootProvider = new ServiceCollection()
    .AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase(dbName))
    .BuildServiceProvider();

  using (var scope = rootProvider.CreateScope())
  {
    // Test other stuff
  }
}
```

If this last snippet is the recommended way, I think these 3 snippets (and their behaviors) would be to good include in documentation somewhere on the InMemory context. _Ignore if there are docs already on this._

**Comment by sharwell** [comment]
> The issue here is that each test is effectively spinning up a completely new web app. This means that services we get from ASP.NET are different every test, which in turn means a new internal service provider for every test.

In general, this is a highly-desirable test characteristic. In Roslyn we go to great lengths to guarantee the tests use this approach. 😄

**Comment by lonix1** [comment]
The workaround: `builder.ConfigureWarnings(x => x.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning))`

Does someone know if that disables it for all contexts (EF does all kinds of static caching), or is it disabled only for that specific context created with that specific builder?

**Comment by mayoatte** [comment]
Just commenting here, in case someone else runs into this (which I just did, head-first). 

Another reason this can happen is specifying a certificate callback (ProvideClientCertificatesCallback) in the OnConfiguring method (Postgres). It's not enough to provide the same certificate every time. The delegate must also be a singleton / static or else the cache key will change and lead to this issue. 

Good luck out there.

**Comment by roji** [comment]
@mayoatte continuing conversation in #2265

**Comment by JohnYoungers** [comment]
Adding another potential trigger if someone else stumbles upon this:

If you're setting up an enum with a name translator, it needs to be static:
```
// wrong
builder => builder.MapEnum<MyEnum>("MyEnum", null, new NpgsqlNullNameTranslator());

// correct
private static readonly NpgsqlNullNameTranslator s_npgsqlNullNameTranslator = new();
...
builder => builder.MapEnum<MyEnum>("MyEnum", null, s_npgsqlNullNameTranslator);
```

If they're different objects, `NpgsqlOptionsExtension.ShouldUseSameServiceProvider` will return false
