### ISSUE TITLE
Latest beta version of EntityFramework.Relational gives compilation error

### ISSUE THREAD

**Issue by d0pare** [dotnet/efcore#1637]
I have updated my project's 'EntityFramework.Relational' dependency from 7.0.0-beta-2 to 7.0.0-*.
I'm getting compilation errors on my migrations - 
Reference to type 'SchemaQualifiedName' claims it is defined in 'EntityFramework.Relational', but it could not be found.

**Comment by Eilon** [comment]
Did you update *all* your dependencies, *and* update the XRE to the latest version? Pre-release builds cannot be mixed & matched.

**Comment by Dopare** [comment]
I have changed all my dependencies to "{version}-*" and upgraded clr and corecle runtimes to 1.0.0-beta4-11090 version.

**Comment by Eilon** [comment]
Can you share your project.json file?

**Comment by rowanmiller** [comment]
We recently removed that API. You could go thru and manually update the migrations code, but my recommendation would be to just delete the migration you have and re-scaffold them.

**Comment by Dopare** [comment]
Thank you very much.
