### ISSUE TITLE
Consider making EF Core 2.x work with ASP.NET Core 3.0

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#16372]
Things to consider:

- [ ] 2.2 packages can load in 3.0 app, including lifting dependencies as needed
- [ ] 2.2 command line tools work with 3.0 
  - ~~The problematic issue here is getting `dotnet-ef` to work with the new ASP.NET generic host builder pattern, since there is no way to update the `dotnet-ef` we shipped in 2.2.~~
- [ ] Ensure ASP.NET Identity works
- [ ] Ensure Database Error Page works
- [ ] Ensure MusicStore works
- [ ] Ensure Health Checks works
- [ ] Ensure Identity templates work
- [ ] Ensure ASP.NET scaffolding works

Another possibility: ship a 2.3 which is not in the shared framework and makes these things work.

**Comment by bricelam** [comment]
> there is no way to update the dotnet-ef we shipped in 2.2

We can update dotnet-ef: We ship a working version of dotnet-ef on NuGet that can be used with the 3.0 SDK.

**Comment by bricelam** [comment]
We'll need to patch EFCore.Design to understand the the generic host pattern. I think there were some issues with patching EFCore.Design, but they shouldn't affect projects using the 3.0 SDK.

**Comment by ajcvickers** [comment]
Note: this is not a finalized plan, but rather something we want to investigate.

**Comment by chris5287** [comment]
@ajcvickers is this no longer potentially going to happen? 

We was really looking forward to using .NET Core 3 features (eg: Blazor) but we need to talk to Oracle databases, which has just been released for EF Core 2.2

**Comment by ajcvickers** [comment]
@chris5287 This was a backup plan in case we were not able to deliver EF Core 3.0 by the ship date for .NET Core/ASP.NET Core 3.0. Following a review yesterday we agreed that EF Core 3.0 does not need to slip, and hence we don't need this backup plan.

That being said, it might still be worth doing this for reasons like you mention. I'll re-open to discuss with the team. However, it certainly won't happen until after 3.0 ships.

/cc @divega

**Comment by ajcvickers** [comment]
We discussed this in triage and while we are not going to do anything to proactively support this, we also don't plan to do anything to block it. If people are trying to do this and things don't work, then please file issues and we will look at them on a case-by-case basis.
