### ISSUE TITLE
NuGet : Dependancies not installed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16383]
Hello everyboy,<br>I just installed EntityFrameworkCore in a project, that took me about half an hour, of which about five minutes of installation.<br>I was invited to install Microsoft.Extensions, but this was impossible as I had to install Microsoft.Extensions.Logging first, and so on.<br>Eventually, I had the message &quot;0 errors&quot;. At that moment, I was wondering what was going on, as this was not the normal situation, I normally get 2 errors, as in reality there were 15 errors, but I do not get the list immediately.<br><br>Some time ago, I was asked to write a data access layer after the enterprise gave up using EntityFramework because of this.<br><br>I am using Visual Studio Community 2017 version 15.9.3, on Windows 10.<br>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/625485/nuget-dependancies-not-installed.html
VSTS ticketId: 938402_
_These are the original issue comments:_

Visual Studio Feedback System on 6/27/2019, 11:57 PM (3 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 6/28/2019, 01:18 AM (3 days ago): <markdown><p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>
</markdown>
canevet on 7/1/2019, 00:53 AM (11 hours ago): <p>Hum, for the second project, I have an error I did not have for the first one :</p><p>____</p><p>Gravité    Code    Description    Projet    Fichier    Ligne    État de la suppression<br>Erreur        Le package 'Microsoft.EntityFrameworkCore.Tools.DotNet 2.1.0-preview1-final' a un type de package 'DotnetCliTool' non pris en charge par le projet 'CoreServices01'.                </p><p>____</p><p>So, I tell you : The Microsoft.EntityFrameworkCore.Tools.DotNet 2.1.0-preview1-final package has a DotnetCliTool type that is not taken care of by the project</p><p>Last time I could install Microsoft.EntityFrameworkCore.Tools.DotNet, this time I am afraid not.</p><p>It does not say install that product, it says "boh, does not run !"</p>

canevet on 7/1/2019, 01:30 AM (11 hours ago): <p>Oh, an element in the warnings :</p><p>***</p><p>Gravité    Code    Description    Projet    Fichier    Ligne    État de la suppression<br>Avertissement    NU1608    Version du package détectée en dehors de la contrainte de dépendance : Microsoft.AspNetCore.App 2.1.1 nécessite Microsoft.Extensions.Caching.Abstractions (&gt;= 2.1.1 && &lt; 2.2.0) alors que la version Microsoft.Extensions.Caching.Abstractions 3.0.0-preview6.19304.6 a été résolue.    CoreServices01    D:\Projets Visual Studio\Web\CoreServices01\CoreServices01\CoreServices01.csproj    1    </p><p>***</p><p>Well, the project needs a version of Microsoft.Extensions.Caching.Abstractions lower than 2.2.0, whereas the only two ones that are available are 4.0.0.1 and 4.0.0.2</p><p>We began with something a little heavy to use, and we end on a serious bug, with currently used modules that depend on versions that are no more online.</p><p>I feel that asking to install Microsoft.EntityFrameworkCore.Tools.DotNet should result in a complete list of dependancies, allowing to know that Tools.DotNet cannot be installed because Caching.Abstractions deleted older versions that are needed, and informing the development team to put older versions online again.</p><p>Instead of spending a whole hour on that, and having nothing at all that is able to run.</p>

canevet on 7/1/2019, 08:28 AM (4 hours ago): <p>It appears we have two problems :</p><ul><li>how Visual Studio manages the dependencies of a requested Nuget package, which is why I opened this thread last Thursday, and it would be understandable that it takes some time to find a solution (I shall upgrade to Visual Studio 2019 probably in a few months, when I have an appropriate connection, maybe this helps ; I hope it does not take more place than version 2017, as some packages already do not have room on my SSD).</li><li>some packages are no more published in a version that some other packages request, and this is blocking.</li></ul><p>Where do you think would be more appropriate to ask the second question ? Perhaps the Github project of the package for which an old version is needed ?</p>

_These are the original issue solutions:_
(no solutions)

**Comment by Gluups** [comment]
Hello, right, this does not concern Entity Framework 6.
In the original thread, was answered "we moved the thread and added a solution".
Well, the thread was moved, I see that, can anybody suggest a solution about any package for which dependencies could miss for installation in a project ?

**Comment by ajcvickers** [comment]
@Gluups Please make sure you're only installing EF packages that have consistent version numbers. The `Microsoft.EntityFrameworkCore.Tools.DotNet` package should not be installed; it is obsolete.

If that doesn't work, then please post your `.csproj` file so we can investigate.

**Comment by Gluups** [comment]
OK.
Well, last week I followed this memo : 
[https://www.codeproject.com/Articles/1259484/CRUD-Operation-in-ASP-NET-Core-Web-API-with-Entity?msg=5639901](url)
and I had no problem with it.
I am afraid I cannot do it again.

**Comment by Gluups** [comment]
Well you are right, that worked without Tools.DotNet
I wonder what that module did.

**Comment by Gluups** [comment]
So, the second question asked in the thread is solved, and I am afraid the first one is out of scope here.

**Comment by ajcvickers** [comment]
@Gluups Can you repeat the first question?

**Comment by Gluups** [comment]
What about improving the automation of the Github interface in Visual Studio ?
If Entity Framework requires Microsoft.Automation, the job of Github is not to say "impossible to install Entity Framework because Microsoft.Automation is not installed".
It is to install Microsoft.Automation and then Entity Framework.
Maybe a user confirmation can be suitable in some cases.
I am giving an example with two modules, but in fact it was a tree with about twelve modules, and in this case it is much more spectacular. The difference is between either playing with Github during an hour and know about the success at the end, or working to do one's job.

Anyway, I opened another ticket about this on Visual Studio support.

**Comment by ajcvickers** [comment]
@Gluups Yes, that is out of scope for here. However, I think you're actually talking about integration with NuGet, rather than GitHub.

**Comment by Gluups** [comment]
> 
> 
> @Gluups Yes, that is out of scope for here. However, I think you're actually talking about integration with NuGet, rather than GitHub.

Oh yes of course, sorry, I am going to edit my answer.
