### ISSUE TITLE
EF core db path

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16384]
Model.cs 

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseSqlite("Data Source=Blogging.db");
}
```

App.xaml.cs

```C#
public App()
{
    this. InitializeComponent(); 
    this. Suspending += OnSuspending;
    using (var db = new BloggingContext())
    {
        db. Database.Migrate(); 
    }
}
```
		
The code is from official demo and its run ok. But if I alterd the path ,e.g "Data Source=D:\\Blogging.db",it will occur an error 
Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 14: 'unable to open database file'.'  

when the program code run to the position "db. Database.Migrate();" 

Can you show me how to change the path and I also wonder how to deploy the project to differenct place whatever in my own pc or other pc(and if I deploied the project to my pc ,then I copied it to the other pc ,whether can I run it directly)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/624624/ef-core-db-path.html
VSTS ticketId: 938162_
_These are the original issue comments:_

Visual Studio Feedback System on 6/26/2019, 08:08 PM (4 days ago): <markdown>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
Please post a small, runnable project/solution that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by w391457094** [comment]
[OneToOneErrorDemo.zip](https://github.com/aspnet/EntityFrameworkCore/files/3347739/OneToOneErrorDemo.zip)

**Comment by ajcvickers** [comment]
Since this is a UWP application there are limitations on which parts of the file system are accessible. See https://github.com/aspnet/Microsoft.Data.Sqlite/issues/287
