### ISSUE TITLE
Make it easy to materialize a non-generic IQueryable

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#16429]
Previous pattern was:
```C#
query.OfType<object>().ToList();
```
This now throws; it was previously client-evaluated.

We have a test extension that allows this:
```C#
query.ToList<object>();
```
we could consider productizing it.

See `LoadTestBase`

**Comment by smitpatel** [comment]
Is OfType is accurate though? Shouldn't it be Cast<object> rather than OfType?

**Comment by ajcvickers** [comment]
@smitpatel Agree that `OfType` is non-obvious and I don't think we need to make this work again. But it would be nice to be able to get the results without iterating over them explicitly.

This is low priority--can be backlogged.

**Comment by ajcvickers** [comment]
Notes from triage: nobody likes `ToList` except me, so we will make `OfType`/`Cast` work, post 3.0.

**Comment by sandrohanea** [comment]
I added a small repro project on how I the cast on IQueryable can be used(imagine that GetQueryable method can return different sets based on some parameters).
 
https://github.com/sandrohanea/EFCore30IssueCast
For EFCore2.2.6 no exception occured.
For EFCore3.0.0 ArgumentException occured:

Expression of type 'System.Linq.IQueryable`1[{Interface}]' cannot be used for parameter of type 'System.Linq.IQueryable`1[{Entity}]'
 
I added the exception here to be easier if someone is searching by the exception in the github issues.
Thanks for fixing it :)

**Comment by smitpatel** [comment]
@sandrohanea - Your issue seems to be unrelated to this issue. Can you file a new issue with full repro, exception message and stacktrace ?

**Comment by sandrohanea** [comment]
> @sandrohanea - Your issue seems to be unrelated to this issue. Can you file a new issue with full repro, exception message and stacktrace ?

Thanks for the quick answer. I added a new issue: https://github.com/aspnet/EntityFrameworkCore/issues/18087

**Comment by ajcvickers** [comment]
Verified that both `query.Cast<object>().ToLIst()` and `query.OfType<object>().ToList()` both work in 5.0.

**Comment by ErikEJ** [comment]
Should this be closed?
