### ISSUE TITLE
Non-compilable ModelSnapshot genereated by ForRelational Column, missing method ColumnName

### ISSUE THREAD

**Issue by adamvoss** [dotnet/efcore#1644]
Running Add-Migration on a model where `ForRelational().Column(...)` has been used, generates non-compilable code.  It expects to be able to call a methods called 'ColumnName' where none is available.

Given the simple model,

``` c#
public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptions options)
    {
        options.UseSqlServer(@"Server=(localdb)\v11.0;Database=BloggingContext;Trusted_Connection=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Property(_ => _.Url).ForRelational().Column("Url");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
}
```

Run `Add-Migration Init` in the Package Manager Console.

Note that the generated `BloggingContextModelSnapshot.cs` file gives a compilation error 

> Error 1   'Microsoft.Data.Entity.Metadata.BasicModelBuilder.EntityBuilder.PropertyBuilder' does not contain a definition for 'ColumnName' and no extension method 'ColumnName' accepting a first argument of type 'Microsoft.Data.Entity.Metadata.BasicModelBuilder.EntityBuilder.PropertyBuilder' could be found (are you missing a using directive or an assembly reference?)   C:\Source\Repos\JunkCode\Junk\EF7IssueRepo\Migrations\BloggingContextModelSnapshot.cs   23  30  EF7IssueRepo

The generated class:

``` c#
[ContextType(typeof(BloggingContext))]
partial class BloggingContextModelSnapshot : ModelSnapshot
{
    public override IModel Model
    {
        get
        {
            var builder = new BasicModelBuilder();

            builder.Entity("EF7IssueRepo.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .GenerateValueOnAdd();
                    b.Property<string>("Url")
                        .ColumnName("Url");
                    b.Key("BlogId");
                });

            return builder.Model;
        }
    }
}
```

EntityFramework 7.0.0-beta4-12290

**Comment by bricelam** [comment]
Per #1484, this whole area will be changing.
