### ISSUE TITLE
DbContextOptionsBuilder<>.UseLoggerFactory() with 3.0.0-preview6.19304.10 produces minimal output

### ISSUE THREAD

**Issue by fredl49** [dotnet/efcore#16442]
Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer updated to 3.0.0-preview6.19304.10 produces significantly less output.

**Comment by fredl49** [comment]
Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer updated to 3.0.0-preview6.19304.10 produces significantly less output.

**Comment by ajcvickers** [comment]
@fredl49 Can you post an example of what you were getting before and how it has changed?

**Comment by fredl49** [comment]
**With preview5:**
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.0.0-preview5.19227.1 initialized 'MainDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: CommandTimeout=60 
[29:03.2781025] (1) Function Initialize [Boroughs.cs @33]
Microsoft.EntityFrameworkCore.Query: Debug: Compiling query model: 
'from Borough <generated>_0 in DbSet<Borough>
select [<generated>_0]'
Microsoft.EntityFrameworkCore.Query: Debug: Optimized query model: 
'from Borough <generated>_0 in DbSet<Borough>
select [<generated>_0]'
Microsoft.EntityFrameworkCore.Query: Debug: (QueryContext queryContext) => IEnumerable<Borough> _InterceptExceptions(
|__ source: IEnumerable<Borough> _TrackEntities(
|   |__ results: IEnumerable<Borough> _ShapedQuery(
|   |   |__ queryContext: queryContext, 
|   |   |__ shaperCommandContext: SelectExpression: 
|   |   |       SELECT [b].[BoroughID], [b].[BoroughName], [b].[CountyName]
|   |   |       FROM [Boroughs] AS [b], 
|   |   |__ shaper: (MaterializationContext materializationContext) => 
|   |       {
|   |           instance = new Borough()
|   |           instance.<BoroughID>k__BackingField = int TryReadValue(ValueBuffer materializationContext.get_ValueBuffer(), 0)
|   |           instance.<BoroughName>k__BackingField = string TryReadValue(ValueBuffer materializationContext.get_ValueBuffer(), 1)
|   |           instance.<CountyName>k__BackingField = string TryReadValue(ValueBuffer materializationContext.get_ValueBuffer(), 2)
|   |           return instance
|   |       }), 
|   |__ queryContext: queryContext, 
|   |__ entityTrackingInfos: { itemType: Borough }, 
|   |__ entityAccessors: List<Func<Borough, object>> 
|       { 
|           Func<Borough, Borough>, 
|       }), 
|__ contextType: Manage.Common.Models.Main.MainDbContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opening connection to database '' on server '(LocalDB)\MSSQLLocalDB'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opened connection to database 'D:\PROJECTS\SAGSOFT\MANAGE\MANAGE.MAIN\BIN\DEBUG\NETCOREAPP3.0\MANAGEMAINDB.MDF' on server '(LocalDB)\MSSQLLocalDB'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
SELECT [b].[BoroughID], [b].[BoroughName], [b].[CountyName]
FROM [Boroughs] AS [b]
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executed DbCommand (69ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
SELECT [b].[BoroughID], [b].[BoroughName], [b].[CountyName]
FROM [Boroughs] AS [b]

**With preview6:**
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.0.0-preview6.19304.10 initialized 'MainDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: CommandTimeout=60 
[42:25.6677060] (1) Function Initialize [Boroughs.cs @33]
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opening connection to database '' on server '(LocalDB)\MSSQLLocalDB'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opened connection to database 'D:\PROJECTS\SAGSOFT\MANAGE\MANAGE.MAIN\BIN\DEBUG\NETCOREAPP3.0\MANAGEMAINDB.MDF' on server '(LocalDB)\MSSQLLocalDB'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
SELECT [b].[BoroughID], [b].[BoroughName], [b].[CountyName]
FROM [Boroughs] AS [b]
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executed DbCommand (107ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
SELECT [b].[BoroughID], [b].[BoroughName], [b].[CountyName]
FROM [Boroughs] AS [b]

**Comment by ajcvickers** [comment]
First, many thanks for trying preview 6. We really appreciate people trying the previews and filing issues on what they find.

If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

In this case, more detailed query execution logs are back for preview 7.
