### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#16456]
Is it worth splitting into 2 files?

https://github.com/aspnet/EntityFrameworkCore/blob/dcb203f0c7c8e59e0bd9eccc813680505d1df1d8/src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs#L186-L191

I'm working on something, and if it's good for you I can do it with the PR that I'm going to send.

**Comment by ajcvickers** [comment]
@ralmsdeveloper We discussed in triage and decided that this isn't something we want to do. Thanks for the suggestion though.
