### ISSUE TITLE
Cosmos DB not working with ToListAsync()

### ISSUE THREAD

**Issue by arivoir** [dotnet/efcore#16468]
I'm very new to Cosmos DB, actually started some hours ago. I'm working with the following package Microsoft.EntityFrameworkCore.Cosmos (3.0.0-preview6.19304.10)

I was able to create the database and add items on it, but when I try to query the database I'm getting NotImplementedException's

I'm executing the following

```
IQueryable<T> query = _dbContext.Set<T>();
var items = await query.ToListAsync(cancellationToken);
```

> System.NotImplementedException: 'The method or operation is not implemented.'

How should I query the database? Will this be implemented soon?

Regards,
Alvaro.

**Comment by ajcvickers** [comment]
First, many thanks for trying preview 6. We really appreciate people trying the previews and filing issues on what they find.

If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

For this specific case, the query should work in the nightly builds and in preview 7 when it releases.

**Comment by arivoir** [comment]
Thanks for pointing that out. I'll look forward to the preview 7.
