### ISSUE TITLE
Detecting if an owned entity was changed

### ISSUE THREAD

**Issue by strpipe** [dotnet/efcore#16513]
### Description
When I have an entity that ownes another entity and access the IsModified-Property on the corresponding MemberEntry for the owned type, after modifying it, it always returns false. 

We wanted to use the IsModified-Property to detect whether a property has changed and create change sets to later revert the entity to it's former state. It is working for all property entries but not with owned ones.

Is there a way to detect if an owned entity was changed using EF Core?

### Steps to reproduce
I've included an ASP.Net MVC Application. The logic to reproduce the scenario is inside of the HomeController inside of the Index-Action
[owned_entity_types_is_modified_asp_net_core_mvc.zip](https://github.com/aspnet/EntityFrameworkCore/files/3368698/owned_entity_types_is_modified_asp_net_core_mvc.zip)

### Further technical details
EF Core version: 2.1.1
Database Provider: In-Memory
Operating system: Windows 10 Pro - Version 1809
IDE: Visual Studio 2017 15.9.7

**Comment by ajcvickers** [comment]
Note for triage: this is interesting because in the code below, the change to the owned property is a delete/add operation, not an update operation. The `IsModified` call is being made on the relationship, and is checking if the FK property is modified, which it is not.

Maybe if the entity state is `Added`, then the relationship should report as `Modified`?

```C#
Post post = new Post();
post.Address = new Address {Street = "At the mall", Zip = "01187"};
context.Posts.Add(post);
context.SaveChanges();

Address newAddress = new Address {Street = "Updated", Zip = "Updated"};
post.Address = newAddress;

MemberEntry memberEntry = context.Entry(post).Member(nameof(Post.Address));
Console.WriteLine(memberEntry.IsModified);
```

**Comment by ajcvickers** [comment]
Notes from triage: putting this on the backlog as a bug. However, note that in this case it will be an update because of the way owned types work. But if the relationship is identifying, then we don't mark the FK as modified. We should investigate this space.

**Comment by strpipe** [comment]
I may have found other points of interest. They are not about owned entity types but may still be related.
I created a new sample project, there is code inside three actions of the home controller. Two fail, one passes. If it's not related I could open another issue, however, feel free to that on your own. Please let me know how to proceed. Thank you. 
[is_modified_asp_net_core_mvc_v2.zip](https://github.com/aspnet/EntityFrameworkCore/files/3385482/is_modified_asp_net_core_mvc_v2.zip)

**Comment by ajcvickers** [comment]
I investigated this some more and I now understand why this was labeled a bug. Collection navigations already have this behavior--that is, Deleted or Added related entities indicate that the navigation property is modified. So this change brings reference navigations inline, which I think is a bug. Nevertheless, I think it makes sense to document this as a breaking change.

**Comment by voroninp** [comment]
@ajcvickers ,

 `VehicleHandoverTimes` is an owned entity. When handover is cancelled property is set to null.
How can I detect the change? How can I access the original value?
![image](https://user-images.githubusercontent.com/9202028/161521476-a2f6dcb2-3c24-4492-96b8-73cc3d145451.png)
