### ISSUE TITLE
Ef core filter records on DateTimeOffset type

### ISSUE THREAD

**Issue by vlapenkov** [dotnet/efcore#16525]
I have to store datetime in different time zones, so i use DateTimeOffset. 
What i need is to :
1. convert them to one time zone in query
2. filter records in this query

```
public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTimeOffset SDate { get; set; }
}
var sTime = new DateTimeOffset(2010, 1, 1, 1, 0, 0, TimeSpan.FromHours(1));            
   var resultOffset = _logic.dbContext.Countries.Select(p => new { SDate = p.SDate.ToOffset(TimeSpan.FromHours(1)) }).Where(p => p.SDate >= sTime ).ToList();
```
Everything is filtered correctly but i don't see 'where' condition in profiler. It seems like query is performed in memory
`exec sp_executesql N'SELECT [p].[SDate], @__FromHours_0
FROM [Countries] AS [p]',N'@__FromHours_0 time(7)',@__FromHours_0='01:00:00'`

Please explain this behavior. Can i filter on database level? Not in memory

**Comment by mburbea** [comment]
The intermediary select is likely causing it to evaluate in client side. 
I've had limited success with such a thing but only with well known functions for EF like the geography type functions. (e.g.
```cs
public class Foo
{
     public int Id {get;set;}
     public Point P{get;set;}
     [NotMapped]
     public double D {get;set;}
}
...
var loc = new Point(1,1){SRID=4326};
_context.Foos.Select(x=>new Foo{Id=x.Id,P=x.P,D=x.P.Distance(loc)}).Where(x=> x.D < 10)

will generate::
```sql
SELECT [x].[id],[x].[P],[x].[P].STDistance(@__loc__0) as [D]
FROM [dbo].[Foo] as [x]
WHERE [x].[P].STDistance(@__loc_0) < 10
```





If this is a common enough requirement, you might want to map your table to a view that does this call intermediary.

**Comment by smitpatel** [comment]
`ToOffset` fuction is not server evaluated hence you don't see where predicate. If you have a proposed SQL translation for that function, you could easily write a UDF to convert it.

**Comment by vlapenkov** [comment]
What function should i write instead of ToOffset to transform it to another time zone? and then filter it on server side

**Comment by ajcvickers** [comment]
@bricelam to look into an appropriate SQL translation.

**Comment by bricelam** [comment]
.NET | T-SQL
--- | ---
x.ToOffset(offset) |  SWITCHOFFSET(x, offset)
x.ToUniversalTime() | SWITCHOFFSET(x, '+00:00')

**Comment by bricelam** [comment]
Note, the second parameter of SWITCHOFFSET needs to be be converted to a string.
``` csharp
timeSpan.ToString(
    timeSpan < TimeSpan.Zero
        ? "'-'hh':'mm"
        : "hh':'mm")
```

**Comment by bricelam** [comment]
@ajcvickers Was this closed-wont-fix? We don't intend to add translations for these ourselves? (but would accept a PR)

**Comment by ajcvickers** [comment]
@bricelam Good point. I was thinking a long the lines of helping people write the translation themselves, but there's no reason (other than priority) that we wouldn't have these in the box.
