### ISSUE TITLE
An entity which was got with AsNoTracking() still tracked by the DbContext

### ISSUE THREAD

**Issue by jokerosky** [dotnet/efcore#16548]
### Describe what is not working as expected:

When i get an object from a DbSet<T> with .AsNoTracking(), i expect to be able call .Update() method with another object with the same Id, using the same DbContext.

```
**Exception message**: 'The instance of entity type 'AuthorProfile' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'


**Stack trace**: 
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)\r\n   at BooksReader.Infrastructure.Repositories.DbRepository`1.Update(T entity) in C:\\dev\\Work\\booksreader\\src\\BooksReader.Infrastructure\\Repositories\\DbRepository.cs:line 30\r\n   at BooksReader.Services.AuthorProfileService.EditAuthorProfile(AuthorProfileRequest profile)\r\n   at BooksReader.Services.Tests.AuthorProfileService.Should_Edit_AuthorProfile_And_Create_Personal_Page_If_it_was_empty() in C:\\dev\\Work\\booksreader\\tests\\BooksReader.Services.Tests\\BooksReader.Services.Tests\\AuthorProfileService.Tests.cs:line 55" | string


```

### Steps to reproduce
_Include a complete code listing (or project/solution) that we can run to reproduce the issue._

Please don't mind the team name :)

Line of code in the repository:

https://github.com/bugnabuggy/booksreader/blob/dev/tests/BooksReader.Services.Tests/AuthorProfileService.Tests.cs#L55

steps in general: 
1) Get an object from DbSet<T> of a DbContext with .AsNoTracking() .FirstOrDefault().
2) Call DbSet<T>.Update() with the object for the same DbContext.
3) An exception is thrown because the record still being tracked.

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer or Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.5)

**Comment by ajcvickers** [comment]
@jokerosky Running that test and breaking _before_ the no-tracking query, it seems that the context is already tracking an instance with that key. I suspect there is something amiss in the lifetime management of the repository/context.

![image](https://user-images.githubusercontent.com/1430078/60997814-8f435380-a30c-11e9-873b-e24d6da78de2.png)

**Comment by syutzy** [comment]
Following up on the comment by @ajcvickers in case @jokerosky or others still has this issue
> I suspect there is something amiss in the lifetime management of the repository/context.

That was the issue was for me when I saw this behavior.  The reason that the entities were already in the change tracker was from seeding the context with test data, not from the AsNoTracking query.  Instantiating a separate context for the test methods vs the test setup resolved it.
