### ISSUE TITLE
EF Core vs EF 6.x and earlier

### ISSUE THREAD

**Issue by ayadiwork** [dotnet/efcore#16551]
Dears,
I am using EF Core since a couple of months after years of EF 6.x and it seems that a lot of great features I used to work with are missing. Plus, when I read the EF Core 3.0 and EF Core Roadmap I cannot see them planned. I can mention quickly those features :
- Create automatically a new entity from Stored procedure result.
- Data Base first approach and managing data base updates (without erasing any custom code)
- A visual tool, which most of time can be helpful 
- Separate the entities generated from the context in different DLLs
- Accessing database properties so I can create command, access connections... (answered)
- ...
Please advise.

**Comment by ErikEJ** [comment]
"EF Core Power Tools" can probably help you with item 2, 3, 4.

re 5: You can get the ADO.NET DbConnection by writing:

     myDbContext.Database.GetDbConnection();

**Comment by ayadiwork** [comment]
> 
> 
> "EF Core Power Tools" can probably help you with item 2, 3, 4.
> 
> re 5: You can get the ADO.NET DbConnection by writing:
> 
> ```
>  myDbContext.Database.GetDbConnection();
> ```

**Comment by ajcvickers** [comment]
@ayadiwork:
> Create automatically a new entity from Stored procedure result.

If you mean executing a stored procedure and getting back an entity instance, then this is already supported in EF Core. If you mean something else, then please provide more details.

> Data Base first approach and managing data base updates (without erasing any custom code)

As @ErikEJ says, the Power Tools are good for this. From our side this is tracked by #831

> A visual tool, which most of time can be helpful

Again, the Power Tools can visualize the model. We are not planning to implement any kind of visual designer for EF Core. The value is questionable, and the amount of work required to create and maintain it is more than our small team can handle.

> Separate the entities generated from the context in different DLLs

Again, the Power Tools can help automate the generation here. From the runtime perspective there shouldn't be any issue doing this with EF Core.

**Comment by ayadiwork** [comment]
Thank you all for your answers. I am quite new with EF Core, so I apologies if those question seems to be obvious.
I tested some tools but never power tool and it seems that this one is responding to my answers as you mentioned. In fact, I was talking about a native tool as I was happy with the old one. 
About the stored procedure result set : What I found in the current documentation is that EF Core can call a SP and the result is populated in existing entity which is good. Most of the time, in complex project we need to display table (dashboards) that the source is a lot of data base joins and unions, not a simple entity. so the result is completely different from existing entities generated by EF Core. 
If I add properties to an existing entity and fill it with the stored procedure, it works fine, but it will raises an error somewhere else in the application as soon as I use the entity with the basic context functionalities. 
What do you advise for that situation?

**Comment by ajcvickers** [comment]
@ayadiwork Create a second entity type which matches the shape returned by the stored procedure, and continue using the original entity type in other places.

**Comment by ayadiwork** [comment]
Shall I populate the foelds manually? like this case : 
![PopulateFields](https://user-images.githubusercontent.com/28810269/61061739-bb3a0400-a3f4-11e9-8bc3-1f51cf3454bd.png)

**Comment by smitpatel** [comment]
All questions are answered in https://github.com/aspnet/EntityFrameworkCore/issues/16551#issuecomment-510194919 

For stored procedure, you have to create a keyless entity yourself for now. Support for scaffolding sproc see #15105
