### ISSUE TITLE
Restrict behaves like ClientSetNull in EF Core 2.2 Npgsql

### ISSUE THREAD

**Issue by ArthDevRepo** [dotnet/efcore#16588]
I'm using EF Core 2.2 and when i set Delete Behaivor in a relationship to Restrict, the foreign key is set to null in tracked entities when they are made orphans. This is not in accordance with the behavior described in this article: do not set foreign key property in the child entity to null.

Article: https://docs.microsoft.com/pt-br/ef/core/saving/cascade-delete#feedback

Source code in:
https://github.com/ArthDevRepo/EfCoreRestrictBehaivorProblem

Expected behaivor: When Restrict, do not set FK Property to NULL
Actual behaivor: When Restrict, set FK Property to NULL.

**Comment by ajcvickers** [comment]
@ArthDevRepo The issue here is that the documentation is incorrect. `Restrict` (in 2.2--see #12661 for 3.0 changes) means EF will not attempt to set the FK to null or delete a dependent entity when a principal entity _is deleted_. However, setting the FK explicitly to null either directly or through a corresponding change to the navigation property (as in your example) is still honored. So in a case like in your example, where the FK is nullable and the relationship is optional, setting the FK to null is fine, and can be persisted to the database without error. No orphans are deleted and there is no FK violation.

**Comment by ArthDevRepo** [comment]
I want to change de navigation property without setting fk to null, any chance to do it?

**Comment by ArthDevRepo** [comment]
From https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-2.1

> Indicates how a delete operation is applied to dependent entities in a relationship when the principal is deleted or the relationship is severed.

Restrict

> For entities being tracked by the DbContext, the values of foreign key properties in dependent entities are not changed. This can result in an inconsistent graph of entities where the values of foreign key properties do not match the relationships in the graph. If a property remains in this state when SaveChanges() is called, then an exception will be thrown.

**Comment by ajcvickers** [comment]
@ArthDevRepo Can you explain why you want to do that?

**Comment by ArthDevRepo** [comment]
Remove the post from blog posts list. Or set post.blog navigation property to NULL. 
Expected result is the FK property not changed.

**Comment by ajcvickers** [comment]
@ArthDevRepo But _why_ do you want to do that? (As I said, the documentation here is wrong.)

**Comment by ArthDevRepo** [comment]
I know that doing this does not make sense since I'm deleting the relationship explicitly. My question was whether I was doing it the right way, since the documentation said that FK was not changed. Testing again, I noticed that when deleting the relationship (remove the post from blogs post list), configured with DeleteBehaivor.Cascade, the FK is not changed as with ClientSetNull, SetNull and Restrict. Is that correct? thank you!

**Comment by ajcvickers** [comment]
@ArthDevRepo Whether or not an FK is set to null depends on whether or not the relationship is required or not, in addition to the delete behavior. A required relationship implies the FK is non-nullable, and hence cannot be set to null.

**Comment by ArthDevRepo** [comment]
When a relationship is severed, the fk is set to null if cascade behaivor is clientsetnull, setnull and restrict. Cascade never touch the fk
