### ISSUE TITLE
DateTimeOffset and SQLITE Performance

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#16595]
Hi All,
I have a few questions about DateTimeOffsets and SQLITE performance.

When we store DateTimeOffsets into SQLITE, we can store them as either a regular DateTimeOffset or we can convert them into a long (using UtcTicks) and store that.

Which is better for performance and searching?  My understanding is that some SQLITE queries require client side evaluation and I'm hoping to do as much in the database as possible.

**Comment by ajcvickers** [comment]
@TonyValenti Storing `DateTimeOffsets` in SQLite is not a great experience since there is no native type in SQLite that can represent this. Converting to UTC and storing as a long will work much better.

**Comment by TonyValenti** [comment]
@ajcvickers Is there an attribute or some other method I can use to make this happen automatically?

In my code, I'd like to be able to leverage DateTimeOffsets when available (SQL Server) and fall back to longs on Sqlite.

**Comment by ajcvickers** [comment]
@TonyValenti Are you using EF Core or  just `Microsoft.Data.Sqlite` on it's own? If EF Core, which version?

**Comment by TonyValenti** [comment]
@ajcvickers I'm using EFCore 2.2.

**Comment by ajcvickers** [comment]
@TonyValenti Actually, reading your last comment, I don't think that is going to work. If you store UTC time in SQLite, then you lose the offset. If you need to use `DateTimeOffset` with SQLite and get back the same thing you saved, then I don't think there is an efficient way to do that on SQLite at all, regardless of EF.

**Comment by TonyValenti** [comment]
@ajcvickers I'm OK with "normalizing" the DateTimeOffsets to UTC values on the backend.  As far as our use-case is concerned, values are equal if their UTC values are equal.

**Comment by ajcvickers** [comment]
@TonyValenti In that case this should work:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>().Property(e => e.Published).HasConversion(
        v => v.ToUnixTimeMilliseconds(),
        v => DateTimeOffset.FromUnixTimeMilliseconds(v));
}
```

**Comment by TonyValenti** [comment]
This is great!  Is there a way to make it so that all DateTimeOffsets get that conversion applied?

**Comment by ajcvickers** [comment]
@TonyValenti Not yet; see #10784
