### ISSUE TITLE
SQLite migrate show PlatformNotSupported when applying lazyloading in Xamarin.iOS project

### ISSUE THREAD

**Issue by SoledadIce** [dotnet/efcore#16614]
Once I use UseLazyLoadingProxies() for my DbContext, I got a PlatformNotSupported error in DB migrate. 
Does that mean EF.Core will not support lazyloading for iOS platform, or I made anything wrong?

**Comment by ajcvickers** [comment]
@SoledadIce iOS doesn't allow dynamic code generation, so it's unlikely that lazy-loading proxies will ever work there. However, [lazy-loading patterns without proxies](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading-without-proxies) should still work.
