### ISSUE TITLE
Query: Generate ordering on PK rather than Select 1

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16610]
We introduce `ORDER BY (SELECT 1)` in certain cases in query when we have to specify ordering. It would be nice if we did order by PK (or identifying projection) rather than Select 1 as it would represent a better stable ordering.

**Comment by roji** [comment]
Is it correct to say that keeping OrderBy for constants is a SqlServer-specific thing? Seems like on most other databases it's OK to simply remove the clause entirely.

Another note is that ordering by the key could possibly have an unnecessary perf impact - it may be better to keep `(SELECT 1)`.
