### ISSUE TITLE
Use correlation IDs or scopes for query logging

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1663]
There are different logging levels at which it make sense to log information about queries at different level of detail, e.g. Information would probably include information about the fact that a query is being executed, Verbose would include the SQL (in case it is relational) and Debug would include parameter values. If we duplicate the information, e.g we also include the SQL in the message for the Debug level, then a logger listening for Debug will get the duplicate information. On the other hand if we don't duplicate the information, chances are that the messages will end up logged out of order and it will become impossible to correlate them.

Rather than duplicating the information in the message sent at different levels we can create a correlation ID (which could be a unique identifier) which would uniquely identify all the messages produced for a particular query execution.

**Comment by divega** [comment]
It appears that we should use scopes (e.g. `ILogger.BeginScope()`) for this purpose. We still need to discuss and investigate.

**Comment by rowanmiller** [comment]
We are already using scopes in 1.0.0
