### ISSUE TITLE
Is it possible to provide custom expression for not mapped property?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#16637]
I would like to use computed POCO-properties in queries without causing client side evaluation.

Consider these properties:

```CSharp
private readonly List<DevicesOrderStatusDetails> _statusHistory = new List<DevicesOrderStatusDetails>();
public IReadOnlyList<DevicesOrderStatusDetails> StatusHistory => _statusHistory;

[NotMapped]
public DevicesOrderStatusDetails CurrentStatus => _statusHistory.OrderByDescending(_ => _.UtcSetAt).FirstOrDefault();
```

I would like to write:

```CSharp
orders.Where(_ => _.CurrentStatus.Status == DevicesOrderStatus.Canceled);
```
but I have to write it as:

```CSharp
orders.Where(_ => 
   _.StatusHistory.OrderByDescending(s => s.UtcSetAt).FirstOrDefault().Status == DevicesOrderStatus.Canceled);
```

So it would be nice, if I could tell EF what expression corresponds to `CurrentStatus` property.
Is it possible with EF Core 2.2?

**Comment by ajcvickers** [comment]
@voroninp In order for any LINQ implementation to translate this there needs to be an expression tree to work with. So this is, essentially, a dupl;icate of #10497. You might want to try playing with the [Expressives](https://www.nuget.org/packages/Microsoft.Linq.Translations/) as a possible approach.
