### ISSUE TITLE
Sqlite Spatial: dotnet crashes when loading Spatial Extension (segmentation fault)

### ISSUE THREAD

**Issue by garfbradaz** [dotnet/efcore#16667]
I'm trying to test out the [Spatial Types](https://docs.microsoft.com/en-us/ef/core/modeling/spatial) functionality in EF Core for *SQLite* In Memory provider. 

Now when I run an _Xunit_ test the *dotnet* executable crashes and I will receive a [crash dump report](https://gist.github.com/garfbradaz/3ea71037bc625eaf30d397c7f016d6e0) (No application exceptions are thrown).

It seems to crash when trying to access the `mod_spatialite` extension. I followed the following advice from this issue https://github.com/aspnet/EntityFrameworkCore/issues/14402, as my original problem  was with receiving a _SQLite Exception_ with a **no such function: InitSpatialMetaData** error  to begin with.

### Steps to reproduce for Mac
1. `git clone` https://github.com/StratumFive/EFCore.SQLite.SpatialCrash.
2. `brew install libspatialit`
3. Change directory to the root solution.
4. `dotnet test xunit`
5. Receive error message:

> The active test run was aborted. Reason: Test host process crashed

There is even a console application there to prove it isn't just a Xunit issue.

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.Sqlite / Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite
Operating system: Mac Mojave 10.14.5
IDE: Visual Studio Code
SQLite version: 3.24.0 2018-06-04 14:10:15
dotnet info:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by garfbradaz** [comment]
Updated above with SQLite version.

**Comment by garfbradaz** [comment]
## Update*

Added a `Dockerfile` to the repository [here](https://github.com/StratumFive/EFCore.SQLite.SpatialCrash) for my repo. It also crashes as well (Debian).

### Steps to reproduce for Dockerfile (assumes docker is setup on machine)

1. `git clone` https://github.com/StratumFive/EFCore.SQLite.SpatialCrash.
2. Change directory to the root solution.
4. Build the image `docker build . -t xunit-crash`
5. Run the container and execute into it `docker run --rm -it -p 5001:5001/tcp xunit-crash:latest`
6. Run tests `dotnet test xunit/EFCore.Spatial.Crash.csproj -c Release -r /TestResults --logger "trx;LogFileName=TestResults.trx"`
7. Receive error:

> The active test run was aborted. Reason:

**Comment by garfbradaz** [comment]
Also, here is my Mac `spatialite` Mac info:

>spatialite
SpatiaLite version ..: 4.3.0a	Supported Extensions:
	- 'VirtualShape'	[direct Shapefile access]
	- 'VirtualDbf'		[direct DBF access]
	- 'VirtualXL'		[direct XLS access]
	- 'VirtualText'		[direct CSV/TXT access]
	- 'VirtualNetwork'	[Dijkstra shortest path]
	- 'RTree'		[Spatial Index - R*Tree]
	- 'MbrCache'		[Spatial Index - MBR cache]
	- 'VirtualSpatialIndex'	[R*Tree metahandler]
	- 'VirtualElementary'	[ElemGeoms metahandler]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualFDO'		[FDO-OGR interoperability]
	- 'VirtualGPKG'	[OGC GeoPackage interoperability]
	- 'VirtualBBox'		[BoundingBox tables]
	- 'SpatiaLite'		[Spatial SQL - OGC]
PROJ.4 version ......: Rel. 6.1.1, July 1st, 2019
GEOS version ........: 3.7.2-CAPI-1.11.2 b55d2125
TARGET CPU ..........: x86_64-apple-darwin18.2.0
the SPATIAL_REF_SYS table already contains some row(s)
SQLite version ......: 3.28.0
Enter ".help" for instructions
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for instructions
Enter SQL statements terminated with a ";"

**Comment by garfbradaz** [comment]
@bricelam  do you need anything else from me?

**Comment by bricelam** [comment]
I don't think so. I just need to repro it locally and dig into the failure.

**Comment by garfbradaz** [comment]
Can I help in anyway to dig into the failure @bricelam ? I know you guys are busy and this issue is blocking me.

**Comment by bricelam** [comment]
Does it repro with something as trivial as this:
``` csharp
using static SQLitePCL.raw;

class Program
{
    static void Main()
    {
        SQLitePCL.Batteries_V2.Init();

        sqlite3_open(":memory:", out var db);
        sqlite3_enable_load_extension(db, 1);
        sqlite3_exec(db, "SELECT load_extension('mod_spatialite')");
    }
}
```

**Comment by bricelam** [comment]
Looks like our CI has been hitting this too. 😁

**Comment by bricelam** [comment]
It appears to be in issue with the latest revision of the Homebrew package.

### Workaround
Use the previous version:
``` sh
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/835ae521c065524abdf66578e68032fa24bce514/Formula/libspatialite.rb
```

**Comment by bricelam** [comment]
@fxcoudert What's the proper channel for reporting this?

**Comment by bricelam** [comment]
It may (or may not) be related to the fact that our native SQLite library is named libe_sqlite3.dylib not libsqlite3.dylib

**Comment by garfbradaz** [comment]
> It may (or may not) be related to the fact that our native SQLite library is named libe_sqlite3.dylib not libsqlite3.dylib

Amazing @bricelam  - looking now :)

**Comment by garfbradaz** [comment]
## Feedback

@bricelam  - sorry for the delay.

I reverted the version back using the [workaround](https://github.com/aspnet/EntityFrameworkCore/issues/16667#issuecomment-517493025), but this has caused a new set of errors explained now.

### New Errors
- This runs fine *without* error.

> 
> ```cs
> using static SQLitePCL.raw;
> 
> class Program
> {
>     static void Main()
>     {
>         SQLitePCL.Batteries_V2.Init();
> 
>         sqlite3_open(":memory:", out var db);
>         sqlite3_enable_load_extension(db, 1);
>         sqlite3_exec(db, "SELECT load_extension('mod_spatialite')");
>     }
> }
> ```

* The following Xunit code found [here](https://github.com/StratumFive/EFCore.SQLite.SpatialCrash/blob/master/xunit/TestCrash.cs) now throws the  following exception:

>EFCore.Spatial.Crash.TestCrash.Test_Crash_for_EF_Team:
    Outcome: Failed
    Error Message:
    Microsoft.Data.Sqlite.SqliteException : **SQLite Error 1: 'dlopen(mod_spatialite.dylib.dylib, 10): image not found'.**
    Stack Trace:
       at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.Load(DbConnection connection)
   at EFCore.Spatial.Crash.TestCrash.Test_Crash_for_EF_Team() in /Users/garethb/code/EFCore.Spatial.Crash/xunit/TestCrash.cs:line 18
--- End of stack trace from previous location where exception was thrown ---

* The following console code found [here](https://github.com/StratumFive/EFCore.SQLite.SpatialCrash/blob/master/console/EFCore.Spatial.Crash.Console/Program.cs) now produces the following stack dump [here](https://gist.github.com/garfbradaz/69f8df9c3cc8e161fab46a48330c3657).

Interestingly now when I run `spatialite` on the commandline I get:

> dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.13.dylib
  Referenced from: /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
  Reason: image not found
[1]    21039 abort      spatialite

Could it be some `$PATH` is missing or is expected? Here is my echo'd `$PATH`:

>/usr/local/opt/sqlite/bin
/Users/garethb/.dotnet/tools
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/share/dotnet
~/.dotnet/tools
/Library/Frameworks/Mono.framework/Versions/Current/Commands
/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin

**Comment by ajcvickers** [comment]
Unfortunately, we are out of ideas here. We are going to put this on the backlog, but we are likely to need expert help to make real progress here.

**Comment by pond** [comment]
This is a critical blocker for us.

As a community effort, even with everyone trying their best, crash bugs thrown into the "too hard" bucket mean it can't be taken seriously as something a company's income depends upon. Hard-crash issues need proper engineering resources from Microsoft dedicating to them so that people who are actually able to diagnose and fix the issue are promptly assigned. Perhaps the bottom line is that although EntityFrameworkCore is cross-platform, a crash on a non-Windows platform isn't where the money is and isn't going to get much traction.

If there's anything that can be done to escalate this I'm sure others would appreciate it.

**Comment by ajcvickers** [comment]
@pond What version of EF Core are you using?

**Comment by bricelam** [comment]
@pond the crash is caused by changes made to the libspatialite Homebrew package. I've filed https://github.com/Homebrew/homebrew-core/issues/43203. See [my comment above](https://github.com/aspnet/EntityFrameworkCore/issues/16667#issuecomment-517493025) for a workaround.

**Comment by pond** [comment]
@bricelam The work-around doesn't help I'm afraid - it was the first thing I tried. It doesn't matter what version of that package I install; the crash happens anyway. It looks likely to be a combination of specific versions of several packages. I have isolated a single machine which works, and will try to replicate that particular configuration on another machine as soon as I have time.

@ajcvickers Unsure how to get a version for that particular component; .Net Framework 2.2.4 ("latest download" at the time of writing) and again "most recent" Nuget packages related to EFC & SQLite... Looks like there are references to Microsoft.EntityFrameworkCore.Sqlite 2.2.6 and Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite 2.2.6 in the `.csproj` file.

**Comment by pond** [comment]
Success. By carefully unpicking all newer versions and installing specific versions of the runtime and related libraries, I have the test suite running on SQLite that used to crash. Notably, the version of `libspatialite` is _not_ in my case responsible. Using the most recent Homebrew build works fine. It's other dependencies that seem to be the issue - at least in my case.

It's quite an ugly process. I imagine that most of these carefully chosen versions are _not_ necessary, so I'll edit and update this answer as I narrow things down, until I run out of time for it anyway.

First:

* Uninstall any DotNetCore versions you don't want: https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos
* Get DotNetCore SDK version 2.2.300: https://dotnet.microsoft.com/download/dotnet-core/2.2
* Important! Clean any relevant builds; `dotnet clean` or equivalent

Next, remove a few Homebrew packages: 

```sh
brew uninstall postgis
brew uninstall gdal
brew uninstall libspatialite 
brew uninstall libgeotiff
brew uninstall proj
brew uninstall sqlite
```

...resolving dependencies (or ignoring them) with further `uninstall` commands if need be, taking note of them all for reinstallation later. Then, we cherry-pick versions that happen to work on my machine.

SQLite 3.28.0

```sh
 brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/4fa421cfc34548eb48bc236460584c9f4fa16b22/Formula/sqlite.rb
```

 Proj 6.1.0

``` sh
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ca19c245aae7d6fa8c0d9d7314a4964a3a3b18c8/Formula/proj.rb
```

Libgeotiff seems unrelated, so we just install the most recent version. For this and further calls, Homebrew doesn't seem to recognise the from-SHA installations of dependencies so halts; you have to install with `--ignore-dependencies`. Rather unhelpfully, Homebrew will then warn you that this is an unsupported flag you're not supposed to use, but it's not as if there's any choice.

```sh
brew install --ignore-dependencies libgeotiff
```

Gdal 2.4.1_1

```sh
 brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/37ce68573be9fe921ef65d421da4657e2f6d0270/Formula/gdal.rb
```

Libspatialite 4.3.0a_7 (the most recent version at the time of writing, but locking to SHA for safety here)

```sh
 brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/1bbba12ca10e05e7194a6233d4bf5bf56677939f/Formula/libspatialite.rb
```

 Postgis 2.5.2_2 (the most recent version at the time of writing, but locking to SHA for safety here)

```sh
 brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/0a2e72798e72e3accead7e793d6cccf4ff89dd70/Formula/postgis.rb
```

**Comment by bricelam** [comment]
I too am starting to think this is a problem with PROJ. It looks like it links directly to libspatialite3-0 which breaks SQLite extensions.

**Comment by pond** [comment]
@bricelam Should be able to go to 5.2.0 via

```
brew uninstall --ignore-dependencies proj
brew uninstall --ignore-dependencies libspatialite
brew install --ignore-dependencies  https://raw.githubusercontent.com/Homebrew/homebrew-core/cc8b37d018e1dd29b9051fff899fa397239c59c4/Formula/proj.rb
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/835ae521c065524abdf66578e68032fa24bce514/Formula/libspatialite.rb
```

I tried this and while my own test suite continued to build, I didn't have much luck with the one in the https://github.com/Homebrew/homebrew-core/issues/43203 example repository. Worth a try on your local machine though as there are many other things that might have caused problems on my old laptop.

**Comment by SMillerDev** [comment]
Just make sure not to file issues with homebrew if you install old versions this way since it isn't supported.

**Comment by bricelam** [comment]
(From @michaeldtaylor on #18068)

If I take the SpatiaLiteLoader out into my own app I can get loading the module by explicitly setting the environment variable:

DYLD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/

and doing:

SELECT load_extension('mod_spatialite.so')

**Comment by bricelam** [comment]
I didn't get a response from SpatiaLite. I'm working on just building it myself without PROJ over in [bricelam/mod_spatialite-NuGet](https://github.com/bricelam/mod_spatialite-NuGet)

**Comment by bricelam** [comment]
Today I learned that our [SpatialiteLoader](https://github.com/dotnet/efcore/blob/master/src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs) won't actually work on Linux. Apparently modifying LD_LIBRARY_PATH after the first call to dlopen() has no affect. This drastically minimizes the usefulness of distributing Linux binaries of SpatiaLite in our NuGet package. This may also be true for macOS. I'm investigating other possible workarounds to the PROJ issue.

**Comment by bricelam** [comment]
I was able to confirm my suspicions. This issue stems from PROJ using its own version of SQLite. Here are the relevant parts of the LD_DEBUG log:

> 633:     calling init: /home/bricelam/Test/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libe_sqlite3.so
> 633:
> 633:     calling init: /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
> 633:
> 633:     calling init: /usr/lib/x86_64-linux-gnu/libproj.so.13
> 633:
> 633:     calling init: /usr/lib/x86_64-linux-gnu/mod_spatialite.so
> 633:
> 633:     /usr/lib/x86_64-linux-gnu/mod_spatialite.so: error: symbol lookup error: undefined symbol: sqlite3_extension_init (fatal)

Calling load_extension('mod_spatialite') from e_sqlite3 causes the system sqlite3 library to be loaded as a dependency. Then it tries to call sqlite3_extension_init() in mod_spatialite, but it can't reconcile the two versions of SQLite and crashes.

If I take e_sqlite3 out of the picture and only use the system sqlite3 version, everything works as expected.

``` xml
<ItemGroup>
  <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="3.1.0" />
  <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.0.2" />
</ItemGroup>
```
``` csharp
static void Main()
{
    SQLite3Provider_dynamic_cdecl
        .Setup("sqlite3", new NativeLibraryAdapter("libsqlite3.so.0"));
    SQLitePCL.raw.SetProvider(new SQLite3Provider_dynamic_cdecl());

    var connection = new SqliteConnection("Data Source=:memory:");
    connection.LoadExtension("mod_spatialite");

    var command = connection.CreateCommand();
    command.CommandText = "SELECT spatialite_version()";

    connection.Open();
    var version = command.ExecuteScalar();

    Console.WriteLine("SpatiaLite Version: " + version);
}

class NativeLibraryAdapter : IGetFunctionPointer
{
    readonly IntPtr _library;

    public NativeLibraryAdapter(string name)
        => _library = NativeLibrary.Load(name);

    public IntPtr GetFunctionPointer(string name)
        => NativeLibrary.TryGetExport(_library, name, out var address)
            ? address
            : IntPtr.Zero;
}
```

**Comment by bricelam** [comment]
Another workaround is to manually build and install SpatiaLite without PROJ support:
```sh
./configure --disable-proj
make
make install
```

**Comment by ajcvickers** [comment]
After discussing this with @bricelam and the team, we have decided to close this as external. Brice has done extensive research into making the experience better, but ultimately this comes down to better documentation of workarounds.

**Comment by RamNow** [comment]
> ```cs
> class NativeLibraryAdapter : IGetFunctionPointer
> {
>     readonly IntPtr _library;
> 
>     public NativeLibraryAdapter(string name)
>         => _library = NativeLibrary.Load(name);
> 
>     public IntPtr GetFunctionPointer(string name)
>         => NativeLibrary.TryGetExport(_library, name, out var address)
>             ? address
>             : IntPtr.Zero;
> }
> ```

@bricelam Thanks for all your research!
Do you have any suggestions on what to do when `NativeLibrary` isn't available because you are on a .Net Core 2.2 environment?

**Comment by bricelam** [comment]
Take heart and have a look at https://github.com/ericsink/SQLitePCL.raw/blob/master/src/SQLitePCLRaw.nativelibrary/for_netstandard2.cs

**Comment by bricelam** [comment]
Oh wait, if you're using 2.2, you can just do this:
```xml
<PackageReference Include="SQLitePCLRaw.provider.sqlite3.netstandard11" Version="1.1.12" />
```
```cs
SQLitePCL.raw.SetProvider(new SQLite3Provider_sqlite3());
```
