### ISSUE TITLE
RevEng: Use EF to load metadata for SqlServer provider

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#1667]
Part of #830. 

As part of this investigate whether it might be better to directly query the sys tables.

**Comment by ErikEJ** [comment]
Highly recommend to use sys views, as can be seen from the improved fk Query, and now is a good time to do this

**Comment by dazinator** [comment]
Would using the 'GetSchema()' method of the 'DbConnection' object (SqlConnection) be a possibility here? This method exposes various schema collections (tables, foreign keys etc) - and would future proof EF should you decide to support wrapped / alternate ADO.net providers that support T-SQL but don't have any concept of sys.views / sys.tables.  https://msdn.microsoft.com/en-us/library/ms254969(v=vs.110).aspx

**Comment by popcatalin81** [comment]
@dazinator sys.views / sys.tables, are regular views in the sys schema (Just like any other view).

**Comment by dazinator** [comment]
@popcatalin81 yup, I realise that haha :)
My point is really that it's already possible to obtain certain schema information via the ADO.NET provider - without hand cranking any t-sql commands at all. This would insulate your code, should the SQL team decide to modify those views, drop them in future, or for example, if those views are different in different SQL versions, you don't have to have different queries for different versions of SQL server (The ADO.NET provider for SQL server will respect the version of SQL server and obtain metadata in the appropriate way for that version when you use the GetSchema method) 
It's just a suggestion, just wondered if you had already looked at that this perhaps and dismissed it for some reason.
For background, should alternate ADO.NET providers #1676 ever be supported by EF in the future, then it also means the ADO.NET provider can implement the GetSchema() method and does not have to support sys.views / sys.tables. It also means that an ADO.NET provider that wrapped the SQL ADO.Net provider could potentially "add in / inject" metadata and expose that to EF - which may or may not have some novel uses!

**Comment by divega** [comment]
FWIW, `GetSchema()` is not a viable "future proof" solution. Besides any gap between the results of `GetSchema()` and the metadata needs of EF7 reverse engineering, there is no `DataTable` in .NET Core.

**Comment by dazinator** [comment]
@divega that's interesting about datatable . I would have thought that system.data.sqlclient would throw runtime errors without it. Rather than pester you I'll give it a go and see what I can learn around that!
Thanks

**Comment by dazinator** [comment]
@divega - well I never. So it turns out there is no GetSchema() method at all on dbconnection anymore, and DataTable is nowhere to be found - which means I was talking nonsense. Goes to show how far I have fallen behind with the pace of .NET! Apologies.

**Comment by natemcmaster** [comment]
A "need to have" for this work:

 - [sys.sequences](https://msdn.microsoft.com/en-us/library/ff877934.aspx) uses `sql_variant` which is not currently supported by EF7.

**Comment by smitpatel** [comment]
> sys.sequences uses sql_variant which is not currently supported by EF7.

At present we don't query using sql_variant and cast to appropriate int/bigint type in projection so we are no longer blocked on that.

This could be done after #1862 is implemented.

**Comment by ajcvickers** [comment]
Removing the blocked label since mapping of SQL variants is now supported in EF Core 2.1. We should revisit this and see if there are still any blocking issues or pain points, but the priority is relatively low.

**Comment by smitpatel** [comment]
@bricelam working on this?

**Comment by bricelam** [comment]
No, I assign myself to random issues on the backlog as part of the planning process. 😉

**Comment by ajcvickers** [comment]
We have no plans to go in this direction.
