### ISSUE TITLE
Move (SELECT 1) ordering from relational to SqlServer provider

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#16672]
We currently generate `ORDER BY (SELECT 1)` when Take is used, since SqlServer requires it. We should move that to the SqlServer provider.

We should probably test whether Sqlite is OK with not having this (like PostgreSQL).

Related: in the general case we can also elide OrderBy on constants as they're meaningless.

**Comment by smitpatel** [comment]
Duplicate of #19332
