### ISSUE TITLE
RevEng: add tests

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#1669]
Part of #830. Need to come up with a testing strategy and implement more tests for Reverse Engineering.

**Comment by lajones** [comment]
Added end-to-end test on release branch (dnx451 only) with commit 1d973a1.

**Comment by bricelam** [comment]
(Copying my comment from an earlier PR:)

I think for functional tests, it would good to hit a database and/or compile code. The two big functional scenarios I see are:
* Create various database objects, verify SqlServerMetadataModelProvider outputs a correct model
* Create various models, generate code, verify code, compile code, verify model

**Comment by lajones** [comment]
Merged the end-to-end test for dnx451 into dev branch with commit 776124e.

**Comment by lajones** [comment]
E2E test is updated to work on dnxcore50 as well. See #2452.

**Comment by lajones** [comment]
Adding compilation test with https://github.com/aspnet/EntityFramework/pull/2575

**Comment by rowanmiller** [comment]
@lajones what is still outstanding here?

**Comment by lajones** [comment]
The standard RevEng capabilities are covered through the end-to-end tests, but would like to add more unit tests.

**Comment by rowanmiller** [comment]
Closing, feel free to incrementally add coverage as you work on things.
