### ISSUE TITLE
Reverse Engineer: Merge code which does similar things in Migrations

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#1671]
Part of #830.

There are a couple of classes which have close equivalents in Migrations (ServiceProvider cf DesignTimeServices; CSharpUtilities cf CSharpHelper; SqlServerTypeMapping cf SqlServerTypeMapper). We should investigate merging the functionality.

**Comment by rowanmiller** [comment]
@bricelam @lajones seems like we have done some of this, anything left to do here?

**Comment by bricelam** [comment]
There's still a lot of duplication in the C# utility classes.

**Comment by bricelam** [comment]
It looks like there is also duplicate code that transforms directory paths into namespaces.

**Comment by smitpatel** [comment]
Also merge code for `GenerateAnnotations` in migration & scaffolding including `GenerateFluentApiForAnnotation`

**Comment by divega** [comment]
Cleared up the milestone to get more clarity on whether this should be punted.

**Comment by smitpatel** [comment]
Also, consider that DbContext writer does not generate namespaces for custom types at present.

**Comment by bricelam** [comment]
Closing since this is tracked by #8853
