### ISSUE TITLE
Should save entity history?

### ISSUE THREAD

**Issue by datphan310** [dotnet/efcore#16718]
Dear team,
i have a confuse for this method 
![image](https://user-images.githubusercontent.com/33355243/61788073-5db5a680-ae3b-11e9-8944-ace845232631.png)

why "return false" if "isOwnedEntity" is false?
if i want to make entity history for User entity, what will i do?
If i change to "return true", what will happen?

**Comment by ajcvickers** [comment]
@datphan310 Please post a small, runnable project/solution or complete code listing that reproduces the issue you are seeing and provide a detailed explanation of what behavior you are expecting instead.

**Comment by datphan310** [comment]
> @datphan310 Please post a small, runnable project/solution or complete code listing that reproduces the issue you are seeing and provide a detailed explanation of what behavior you are expecting instead.

sorry for my mistake, because i don't know how to enable entity history for entities, so i use "Audited" to enable it now
