### ISSUE TITLE
Migration: Apply to MsSQL ignores identity

### ISSUE THREAD

**Issue by BravoSlo** [dotnet/efcore#16739]
Add-Migration creates correct <name>.cs 
id = table.Column<int>(nullable: false).Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

But when update-database is executed on mssql server the generated sql statement is missing identity flag and the resulting table has no identity set on id column.

### Further technical details
Microsoft.EntityFrameworkCore.Design 3.0.0-preview7.19362.6
Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview7.19362.6
Microsoft.EntityFrameworkCore.Tools 3.0.0-preview7.19362.6

Operating system: Windows 10 Build 18941.1001
IDE: Visual Studio 2019 16.2.0 Preview 4.0

**Comment by ajcvickers** [comment]
@BravoSlo Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so we can fully investigate.

**Comment by BravoSlo** [comment]
Found the problem, one of our assemblies, which holds base object for our models, was built using preview6 versions. After upgrading to preview7 the migrations are working as expected. Sorry for false report.
