### ISSUE TITLE
Improvement suggestion: add reference to source code when issuing warnings

### ISSUE THREAD

**Issue by fhurta** [dotnet/efcore#16740]
I see warnings like the one below here and there in the log files. However, as the code base is quite large and there are lot of queries, it is not easy to track down to which query is the warning related. Would it be possible to extend the message with source file name and line number?
Or any glues how to find the query in the code that is causing the warning?

```
The Include operation for navigation '[t].Tenant' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information. <s:Microsoft.EntityFrameworkCore.Query>
```

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10, Azure App Service
IDE: Visual Studio 2019 16.1.2

**Comment by ajcvickers** [comment]
@fhurta There isn't a way to do this automatically (that's actually a hard problem: #14134) but you can [add tags to your queries](https://docs.microsoft.com/en-us/ef/core/querying/tags)
