### ISSUE TITLE
dotnet ef is broken in 3.0 preview 7

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16755]
When updating a project to 3.0 preview 7 from an earlier version, &quot;dotnet ef&quot; breaks.  It does not run at the command-line and external providers like npgsql no longer work

See the attached clip from Twitch.

https://clips.twitch.tv/SingleImpartialParrotFloof

Sample Code can be found in the 3.0p7 tag at:

https://github.com/csharpfritz/ResourceManagement/tree/3.0p7

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/659794/dotnet-ef-is-broken-in-30-preview-7.html
VSTS ticketId: 951796_
_These are the original issue comments:_

Visual Studio Feedback System on 7/25/2019, 03:25 AM (12 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
Because EF Core 3.0 is no longer part of the .NET Core shared framework, the `dotnet-ef` tool is no longer part of of the .NET Core SDK and must be installed manually. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dotnet-ef
