### ISSUE TITLE
Performance issue using `.DefaultIfEmpty()`

### ISSUE THREAD

**Issue by loekd** [dotnet/efcore#16764]
### Description
I am querying the maximum value of a non-nullable datetime column in a large table. Using `MaxAsync` I can get an `OutOfRangeException` if no records are found, so I added `.DefaultIfEmpty()`.

### Steps to reproduce

``` csharp
var max = await _dbSet
    .Where(ev => ev.FkId == id)
    .DefaultIfEmpty()
    .MaxAsync(ev => ev.CreatedAtUtc);
```

This results in the following generated SQL statement:

``` SQL
(@__fkId_0 uniqueidentifier)SELECT MAX([t].[CreatedAtUtc])
FROM (
    SELECT NULL AS [empty]
) AS [empty]
LEFT JOIN (
    SELECT [ev].[CreatedAtUtc]
    FROM [Table] AS [ev]
    WHERE ([ev].[FkId] = @__fkId_0)
) AS [t] ON 1 = 1
```
as you can see, the `MAX()` is not computed on the `SELECT` results, but on the JOIN'ed results, resulting in very poor performance for large record-sets. It would be better if the SQL looked more like this:

``` SQL
(@__fkId_0 uniqueidentifier)SELECT ([t].[CreatedAtUtc])
FROM (
    SELECT NULL AS [empty]
) AS [empty]
LEFT JOIN (
    SELECT MAX([ev].[CreatedAtUtc]) AS [CreatedAtUtc]
    FROM [Table] AS [ev]
    WHERE ([ev].[FkId] = @__fkId_0)
) AS [t] ON 1 = 1
```

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Linux and Windows
IDE: Visual Studio 2017 15.9

### Workaround
When using this code:
``` csharp
var max = await  _dbSet
    .Where(ev => ev.FkId == id)
    .MaxAsync(ev => (DateTimeOffset?)ev.CreatedAtUtc);
```

The produced SQL performs much better.
```
SELECT MAX([ev].[CreatedAtUtc])
FROM [Table] AS [ev]
WHERE ([ev].[FkId] = @__fkId_0) 
```

**Comment by ajcvickers** [comment]
Triage: moving this to the backlog to consider other translations. Note however, that the max of { NULL, -1 } is -1, while the max of { 0, -1 } is 0, so the suggested translation doesn't seem correct.
