### ISSUE TITLE
Entity Framework has inconsistent behaviour with int/tinyint keys

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16772]
In a simple EF C# project, I experience different behaviour when a key value is defined as byte (tinyint) or int.

Repro steps:
Build the attached solution
Debug the project.

On line 76, a System.InvalidOperation exception occurs.

Continue  - deletes the database.

Modify the code to use the int version of the Post class Id.
Delete the Migrations folder/code.
Use Package Manager Console to run the command:
  Add-Migration InitialCreate

Rebuild the project
Debug the project

This time there's no exception, and the DB entries are created as expected.

Although this example uses EFCore, the same occurs with EF6.

Why is there this inconsitency between use of byte (tinyint) and int type for the key?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/630464/entity-framework-has-inconsistent-behaviour-with-i.html
VSTS ticketId: 941222_
_These are the original issue comments:_

Visual Studio Feedback System on 7/2/2019, 08:26 PM (22 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 7/3/2019, 11:52 PM (21 days ago): <markdown><p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
@Dave-Lowndes See the discussion on #7161. By convention, `int` keys get automatically generated key values; on SQL Server, this means using an Identity column. `byte` keys do not get this by convention--key values must be explicitly specified. However, you can configure the key property as `ValueGeneratedOnAdd` to enable value generation in this case if it's appropriate for your scenario.

**Comment by Dave-Lowndes** [comment]
@ajcvickers Hi Arthur, I've now had a look at that item, it's not quite what I'm experiencing. Have you tried the example that I supplied with my initial bug report?

With the key defined as a byte (tinyint), my code compiles, can create the DB (it's successfully created with a tinyint key), but the code then fails when adding a collection of 2 Post objects (the class with the tinyint key) to a Blog object. The error produced says nothing about byte/tinyint being a problem.

Furthermore, now I've seen that article, if I use the annotations it mentions:

		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public byte Id { get; set; }

my example works fine.

If I use just [Key] or no annotation, I get the run-time exception - but the DB can still be created by the code.

**Comment by ajcvickers** [comment]
@Dave-Lowndes If the key values are not generated, then they must be specified explicitly. The code doesn't do that, which results in attempting to add multiple instances with the same key value.

**Comment by Dave-Lowndes** [comment]
@ajcvickers Do you not consider this to be incredibly confusing from my (a naive DB developer's) perspective?
Why don't you do exactly what is done for an int key and eliminate this difference?
Why isn't the run-time error clear about what the root cause of the problem is?

**Comment by ajcvickers** [comment]
@Dave-Lowndes What was the exact exception message you got? (I'd like to understand why it was so confusing.)

**Comment by Dave-Lowndes** [comment]
@ajcvickers Have you tried my example?
The exception message says "The instance of entity type 'Post' cannot be tracked because another instance with the key value '{Id: 0}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached."
This ties in with what you're saying about it using the same key value, but from my perspective, it shouldn't behave differently whether it's an int or byte key value. Consistency is good.

**Comment by ajcvickers** [comment]
@Dave-Lowndes You're making the assumption that `int` and `byte` are similar enough that they should have consistent behavior. On the other hand, the difference in key space for 32 bits is about 16 million times bigger than the key space for 8 bits. That's a significant difference when it comes to key generation, which therefore warrants different behavior.

I think both points of view are valid, and maybe for EF Core we should have made a different choice, but it's certainly not a clear-cut decision and we went with the latter option.

**Comment by Dave-Lowndes** [comment]
@ajcvickers I'm assuming they are identical other than table size. If an int keyed table fills up, is there anything that makes that any different from the tinyint case other than the number range involved?
If you're not entertaining changing the underlying behaviour, how about having the tooling prevent us from falling into the hole - though I imagine that's a more difficult nut to crack?

**Comment by ajcvickers** [comment]
@Dave-Lowndes Thanks for the suggestion.

**Comment by Dave-Lowndes** [comment]
@ajcvickers You're welcome. Have a good weekend.
