### ISSUE TITLE
 Package Microsoft.EntityFrameworkCore 3.0.0-preview7.19362.6 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0)

### ISSUE THREAD

**Issue by samueleresca** [dotnet/efcore#16794]
I'm trying to update the following packages:

```Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.InMemory
Microsoft.EntityFrameworkCore.SqlServer
```
I'm receiving the following error:

```
NUGET| NU1202: Package Microsoft.EntityFrameworkCore 3.0.0-preview7.19362.6 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.EntityFrameworkCore 3.0.0-preview7.19362.6 supports: netstandard2.1 (.NETStandard,Version=v2.1)
RIDER| Package restore failed. Rolling back package changes for 'VinylStore.Catalog.Infrastructure'.
NuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'VinylStore.Catalog.Infrastructure'.
  at 
```

### Steps to reproduce
Clone the following project and try to upgrade to the `3.0.0-preview7.19362.6` version
[EFCore.IssuesSample](https://github.com/samueleresca/EF.Core.IssueSample)

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  MacOS

**Comment by ajcvickers** [comment]
@samueleresca Do you have the preview 7 SDK installed?

**Comment by razfriman** [comment]
I had this same issue when I tried to update the packages using my IDE (Rider).

However, when I updated via the .NET Core CLI it worked fine.

```
dotnet add package Microsoft.EntityFrameworkCore-v 3.0.0-preview7.19362.6
dotnet add package Microsoft.EntityFrameworkCore.Sqlite -v 3.0.0-preview7.19362.6
dotnet add package Microsoft.EntityFrameworkCore.SqlServer -v 3.0.0-preview7.19362.6
```

**Comment by samueleresca** [comment]
The same, I was using Rider, Thanks @razfriman @ajcvickers  for the help 👍

**Comment by rodrigodevelms** [comment]
same error here. 
And I have to type "dotnet restore" every time I open the project in Rider
My sdk version: 3.0.100-preview7-012821

**Comment by belousovbb** [comment]
Update Rider has resovled my problem.
