### ISSUE TITLE
ODBC database provider

### ISSUE THREAD

**Issue by tb-mtg** [dotnet/efcore#16795]
Now that ODBC is included in .Net Core 2.2 are there any plans to support this and an EF Core provider?

If there are no plans what would be the recommendation to implementing one or are there any known working implementations that could be used?

**Comment by ajcvickers** [comment]
@tb-mtg Using the ODBC provider as the basis for EF providers that target a _specific database_ is feasible, but not something we have plans to do. On the other hand, a generic ODBC provider for EF that can work with any database that supports ODBC is really not feasible--see #7432 for more discussion.
