### ISSUE TITLE
SqlServerDbContextOptions  - Is this in the correct namespace?

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#1683]
Is SqlServerDbContextOptions in the wrong namespace? 

https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.SqlServer/Extensions/SqlServerDbContextOptions.cs

**Comment by rowanmiller** [comment]
It will probably move, but it won't be at the root namespace since folks shouldn't be constructing an instance of this type. It's just a helper type that is returned after you call `UseSqlServer` on `DbContextOptions`.
