### ISSUE TITLE
EntityFrameworkCore.Cosmos Transaction

### ISSUE THREAD

**Issue by Weidaicheng** [dotnet/efcore#16836]
Is EF Core for Cosmos going to support transaction?

I was using ABP and EFCore.Cosmos and as I know ABP uses transaction in its inside logic, and I got the below exception.

```
Exception message:
NotSupportedException: Specified method is not supported.
Stack trace:
Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosTransactionManager.BeginTransaction()
```
I checked the code and I know these methods haven't implicated.
Are there any plans to implicate these methods?

### Further technical details
EF Core version: 2.2-preview3
Database Provider: Azure Cosmos Db
Operating system: Windows 10 1903
IDE: JetBrains Rider 2019.1

**Comment by AndriySvyryd** [comment]
Cosmos doesn't support client-initiated transactions: https://docs.microsoft.com/en-us/azure/cosmos-db/database-transactions-optimistic-concurrency
However we could add an option to make this method be no-op instead of throwing if that's useful.

**Comment by Weidaicheng** [comment]
> Cosmos doesn't support client-initiated transactions: https://docs.microsoft.com/en-us/azure/cosmos-db/database-transactions-optimistic-concurrency
> However we could add an option to make this method be no-op instead of throwing if that's useful.

Thanks @AndriySvyryd , I think I can do some changes on ABP framework and remove the client transactions when using DbContext.

**Comment by roji** [comment]
It seems like maybe Cosmos added user-initiated ACID transactions since this was opened, [see docs](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/transactional-batch).

**Comment by AndriySvyryd** [comment]
@roji That's tracked by https://github.com/dotnet/efcore/issues/17308 
Transactional batch doesn't map to the EF abstraction of a transaction as it can't include queries

**Comment by roji** [comment]
OK.

> Transactional batch doesn't map to the EF abstraction of a transaction as it can't include queries

Is there a reason why we can't simply ignore the transaction when executing queries? I guess this means that changes from previous updates wouldn't be seen in the queries, but that might not be a reason to disallow that.

Of course, this does seem to fit best for a single SaveChanges, I agree.
