### ISSUE TITLE
KoreBuild fails due to new packages of ASP.NET vNext

### ISSUE THREAD

**Issue by bartdevriendt** [dotnet/efcore#1684]
KoreBuild fails due to new packages of ASP.NET vNext

Logger facility interfaces have changed

**Comment by bricelam** [comment]
@lukewaters Did you update our tests to react to the changes you made in Logging?

**Comment by lukewaters** [comment]
I addressed the interface change in df23433c

**Comment by bartdevriendt** [comment]
I'll pull the changes in
