### ISSUE TITLE
Update-Database in VS' Package Manager Console is very slow on long scripted migrations

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/efcore#16858]
### Describe what is not working as expected.
Using a long SQL script as part of a migration is taking much longer through the VS Package Manager Console than when compared to running the dotnet ef tool on the command line.  I can't find a way to suppress writing out to the console (`Update-Database | Out-Null` and (`$null = Update-Database` both printed output regardless; there doesn't seem to be a -Quiet flag).

Adding a way to silence the output would be a suitable mitigation.

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
1. Clone https://github.com/jimmylewis/NorthwindMigrationRepro
2. From VS, run Update-Database in the Package Manager Console
(for timing info, I used this:
`$start = [System.DateTime]::Now ; Update-Database ; $end = [System.Datetime]::Now ; Write-Host Elapsed ($end.Subtract($start)).ToString()`
)

**Result:**
Operation takes a couple minutes to run, because of how much is being printed to the console.  With this repro project, it seems to take noticeably more than 150 seconds (2:30) - actual variance has ranged from 2:36 to 3:11 over a few tries.

**Expected:**
Operation should be fast.  Doing it with the dotnet-ef tool in a PowerShell console window takes around 8-11 seconds.
(PowerShell command used: `$start = [System.DateTime]::Now ; dotnet ef database update ; $end = [System.Datetime]::Now ; Write-Host Elapsed ($end.Subtract($start)).ToString()`)

### Further technical details
EF Core version: 3.0.0-preview7.19362.6 (probably orthogonal to this version though)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 16.3 (internal builds)

**Comment by ajcvickers** [comment]
@bricelam Any thoughts on this?

**Comment by bricelam** [comment]
@jimmylewis Are you passing a large script to `migrationBuilder.Sql()`? This could be related to #16175

**Comment by jimmylewis** [comment]
I am (it's around 5800 lines), but the migration succeeds in both cases.  It seems like the difference is the speed of printing to the VS tool window.  There's a noticeable lag watching the text scroll compared to doing it in a separate (native) console window, and it seems to add up in cases like this where the output text is long.

**Comment by ajcvickers** [comment]
Closing as this was reported on old versions of VS and things have moved on.
