### ISSUE TITLE
executesqlcommand then requerying doesnt return updated values

### ISSUE THREAD

**Issue by milsnips** [dotnet/efcore#16861]
I have an issue where i am using ef core to insert a record into a table. Immediately after calling SaveChanges() to save the data, i then execute a stored proc via Context.Database.ExecuteSqlCommand() to calculate and update some additional rows in the same table (where required).

Then, using the same context i try and re-query the entity by id, and it doesn't return me the updated values. I looked in the ChangeTracker.Entities() and can see it is in there as unchanged (after the same completed it went from Add to unchanged).

The only way to get the updated data is to loop through the ChangeTracker.Entities list and detach the entities so i can reload it.

Is this normal behavior or is there a better way to do it? seems a bit hacky at moment as i need to override savechanges to do these extra steps after save changes (in particular detaching the unchanged entities every time) is called.

thanks,
Paul

### Further technical details
EF Core version: 2.2.1
Database Provider: SQL Server 2016
Operating system: Windows 10 
IDE: e.g. Visual Studio 2019 16.2.0

**Comment by ajcvickers** [comment]
@milsnips The general answer is to use a new short-lived context instance for each unit-of-work. 

More specifically, if an entity is already tracked by the context, then that instance is returned when running a query. The `context.Entry(x).Reload()` method to cause an individual entity to be re-loaded from the database, assuming that it's okay to overwrite local changes. But as I said above, it's usually cleaner to create a new context instance and query for the updated entities there.
