### ISSUE TITLE
Issue with IAsyncEnumerable and GetEnumerator

### ISSUE THREAD

**Issue by SebHonorine** [dotnet/efcore#16874]
**Describe what is not working as expected:**
Preparing some documentation on .Net Core 3 I'm trying to update some projects from 2.1 to 3.0 
I've done something similar to this:
https://stackoverflow.com/questions/40476233/how-to-mock-an-async-repository-with-entity-framework-core

**before updating my csproj:**
![image](https://user-images.githubusercontent.com/8523321/62239004-0fa42400-b3a2-11e9-94a6-e075e82ea1a5.png)

**After:** 
![image](https://user-images.githubusercontent.com/8523321/62238962-fdc28100-b3a1-11e9-8777-081bafdb25de.png)

seems like now when going into the metadata I'vesee it went from  System.Interactive.Async to System.Runtime.
no more GetEnumerator in the IAsyncEnumerable but getAsyncEnumerator which make a little sense. I tried to replace in my code with getAsyncEnumerator but i get the error 
"an exception tree may not contain a call or invocation that uses optional arguments"

I came across this issue : https://github.com/aspnet/EntityFrameworkCore/issues/14239
But, not sure if it is related

Don't know where to go from there. been a day since I m stuck. Sorry if its stupid :) and thanks

### Steps to reproduce

- update TargetFramework to 3.0

- look where you where doing a IAsyncEnumerable<T>.getEnumerator

### Further technical details
EF Core version:"Microsoft.EntityFrameworkCore" Version="3.0.0-preview7.19362.6"

**Comment by smitpatel** [comment]
`IAsyncEnumerable` is defined in corefx which introduced the method https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Collections/Generic/IAsyncEnumerable.cs

For questions on
- API design raise issue in corefx repo.
- How to set up the mock, then either your mock framework can answer or stackoverflow could be another place to ask questions.

There is nothing actionable on EF Core here. The same issue would arise if you are trying to mock something which implements IAsyncEnumerable.
