### ISSUE TITLE
FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by KeKl** [dotnet/efcore#16875]
I have following class.

```
public class ApplicationUser : IdentityUser
    {
        public int AddressId { get; set; }

        public Address Address
        {
            get;
            set;
        }
    }
```

If I create a new user, add it to the db (SQLite) and save changes. I get a Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
If I remove the AddressId key, everythings fine. If I also init the Address property everythings
gonna work fine too.
If I remove the AddressId key I still get a column in the db (works).

Adding a foreignkey Attribute with the value _AddressId_ on the address property doesnt work. The address class doesnt have a UserId Key prop nor an User avigation prop.

Is this my fault?

**Comment by smitpatel** [comment]
Your FK property AddressId is not null. If you remove it the there would be one created by convention but it would be nullable.
With non-nullable FK you are essentially implying that each ApplicationUser must have associated address, if you don't have one in database then it fails FK constraints. If that is not intention then make FK nullable and relationalship optional.
