### ISSUE TITLE
Wiki: please document the JetBrains Annotations usage guidelines

### ISSUE THREAD

**Issue by dsaf** [dotnet/efcore#1691]
https://github.com/aspnet/EntityFramework/search?utf8=%E2%9C%93&q=jetbrains

1) Why JetBrains Annotations were chosen over Microsoft Code Contracts?
2) Is it a team-specific decision or a company-wide policy?
3) Will Roslyn affect anything in terms of design-by-contract?

Thank you.

**Comment by davidroth** [comment]
Another question: In the aspnet sources they use roslyn as an AOP weaver to inject the nullchecks. (using the CSharpSyntaxTreeRewriter class).
So they do not hand-write null-checks, they just use their own [NotNullAttribute].

In EF7 you are using NotNull + hand-written nullchecks? Why this?

**Comment by ajcvickers** [comment]
There are notes here that outline why we stopped using Code Contracts: http://entityframework.codeplex.com/wikipage?title=Design%20Meeting%20Notes%20-%20October%2025%2c%202012

We are considering using Roslyn for null checks in the future, but not everything is in place in terms of build infrastructure, development environment, etc. so we are holding off for now.
