### ISSUE TITLE
Cosmos: Translate composition over embedded non-primitive collection

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16926]
```C#
        [ConditionalFact]
        public virtual void Navigation_rewrite_on_owned_collection_with_composition()
        {
            using (var ctx = CreateContext())
            {
                var query = ctx.Set<OwnedPerson>().Select(p => p.Orders.Select(o => o.Id != 42).FirstOrDefault());
                var result = query.ToList();

                Assert.Equal(4, result.Count);
            }
        }
```

**Comment by athinadev** [comment]
Please see this too, it should be the same error
#23704

**Comment by AndriySvyryd** [comment]
Note to implementer: We would need to create an abstraction to be used in the server query that could represent a scalar, an object or a collection. Only scalars and scalars collections would have type mapping. Shaper must also change to allow composition and this might impact include implementation.
