### ISSUE TITLE
Generate fluent API for IDENTITY seed and increment

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#16922]
Some questions that have come up:
- What happens in migrations when you change the seed or increment values?
- Does the model snapshot call the fluent API?
- Should the two model annotations be consolidated into one?

**Comment by ajcvickers** [comment]
@bricelam 

> What happens in migrations when you change the seed or increment values?

What do we do for sequences?

> Does the model snapshot call the fluent API?

We can do this later without it being breaking, right?

> Should the two model annotations be consolidated into one?

Seems like you did this in the PR, or is this something different?

**Comment by bricelam** [comment]
>> What happens in migrations when you change the seed or increment values?

>What do we do for sequences?

There is SQL to alter and reset them.

>> Does the model snapshot call the fluent API?

>We can do this later without it being breaking, right?

Yes, but we’ll have to special case the existing annotations forevermore 

>> Should the two model annotations be consolidated into one?

>Seems like you did this in the PR, or is this something different?

I only did it in Migration operations, we could do the same in the model

**Comment by ajcvickers** [comment]
Split out #16964 and #16965 to backlog; leaving this in 3.0.

**Comment by bricelam** [comment]
Looks like we haven't yet provided a hook for providers to handle annotations in the model snapshot.

**Comment by lajones** [comment]
Poaching
