### ISSUE TITLE
migration.designer.cs should be hidden

### ISSUE THREAD

**Issue by luisrudge** [dotnet/efcore#1693]
before ef7, the .designer.cs file was a child of the actual migration.cs file. Today, every migration adds two files and keeps the folder very dirty.

![image](https://cloud.githubusercontent.com/assets/941075/6357482/8e48fe08-bc43-11e4-909c-be259a12a307.png)

**Comment by bricelam** [comment]
We agree. We have a bug filed with the Tooling team (aspnet/Tooling#96 for those with access). In the meantime, you may want to use [Mads' extension](https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c).
