### ISSUE TITLE
Attach entities perform crash

### ISSUE THREAD

**Issue by Mansu12135** [dotnet/efcore#16947]
Hi, 

I want to loading navigation property after saving changes. But I know that we can load dependent object only on attached objects. From time to time after saving my changed object are detached. For this reason I attach object, like this:

```
await context.SaveChangesAsync();

EntityEntry<TEntity> existingEntity = context.Entry(entities[index]);
				if (existingEntity.State == EntityState.Detached) {
					existingEntity = context.Attach(entities[index]);
				}
if (existingEntity.State == EntityState.Detached) {
					existingEntity = context.Attach(entities[index]); // crash here
				} 
```
Can you help me resolve it? Thank you.

**Comment by Mansu12135** [comment]
I'm write bad code 

```
existingEntity = TryTwice(() => context.Attach(entities[index]));
private static T TryTwice<T>(Func<T> action) {
			T result;
			try {
				result = action();
				return result;
			}
			catch {

			}
			return action();
		}
```

As I correct understand problem is in a ChangeTracker, it doesn't update state of objects on time. I'm forcing update it by attached new object.

**Comment by ajcvickers** [comment]
@Mansu12135  There isn't enough information here for me to be able to reproduce what you are seeing. Please post a small, runnable project/solution or complete code listing.
