### ISSUE TITLE
Owned types are not loaded

### ISSUE THREAD

**Issue by therealhappy** [dotnet/efcore#16979]
Data of Owned Types is not loaded from the database.
The generated SQL does not include the table of the owned type.

### Steps to reproduce
I attached a test project that reproduces the behavior.
[EFCoreOwnedDataNotLoaded.zip](https://github.com/aspnet/EntityFrameworkCore/files/3471215/EFCoreOwnedDataNotLoaded.zip)

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Version 1903
IDE: Visual Studio 2019 16.3.0 Preview 1.0

**Comment by ajcvickers** [comment]
Duplicate of #15285. Confirmed that this works with current nightly build.
