### ISSUE TITLE
(feature idea) Configuring DbContexts

### ISSUE THREAD

**Issue by markolbert** [dotnet/efcore#16971]
This isn't even a feature request, just an idea I had that may or may not be of interest or use.

The basic idea is to use an attribute, a generic interface and an extension method to let fluent-api configuration be done "closer" to a POCO class (i.e., in a class kept in the same source code file as the POCO class).

Full write-up at https://jumpforjoysoftware.com/2019/08/configuring-dbcontexts/.

**Comment by ajcvickers** [comment]
@markolbert This is a fairly well-known pattern--for example, see https://blog.oneunicorn.com/2012/03/26/code-first-data-annotations-on-non-public-properties/

What, specifically, are you suggesting that we add to EF Core for this?

**Comment by markolbert** [comment]
Thanx for the reference, @ajcvickers; I enjoyed reading the article. Among other things, it suggest to me that there are likely a number of alternative, idiosyncratic ways of simplifying fluent model building. With simplification being in the mind of the coder :).

So it's probably not worth while including any one approach in EF Core. How would you decide which ones to include and which ones not to?

I'll close this thread.
