### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by noredgaras** [dotnet/efcore#16978]
[![Gitter](https://badges.gitter.im/EntityFrameworkCore/community.svg)](https://gitter.im/EntityFrameworkCore/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by bricelam** [comment]
https://stackoverflow.com/questions/tagged/entity-framework-core*
https://stackoverflow.com/questions/tagged/ef-core*
