### ISSUE TITLE
Where property on IndexAttribute for Unique constraints

### ISSUE THREAD

**Issue by rockstardev** [dotnet/efcore#1698]
Say that I have Attribute like this on my User object/table:

[Index("UNIQ_Nick", IsUnique = true)]
public string Nick { get; set; }

If I don't make Nick required (say I just want emails to register user) constraint will prevent future registrations because in SQL Server IsUnique constraint prevents rows with multiple <NULLs>

This is well described on:
http://stackoverflow.com/questions/767657/how-do-i-create-a-unique-constraint-that-also-allows-nulls
http://stackoverflow.com/questions/24361518/ef-6-1-unique-nullable-index

Do you have any plans to support something like:
[Index("UNIQ_Nick", IsUnique = true, Where="Nick IS NOT NULL")]

?? 

Would you accept pull request if I implemented this?

**Comment by rowanmiller** [comment]
Hey,

This isn't something we'd want to add to the attribute since it is very specific to relational databases. The best place to do this would be to edit the migration once it is scaffolded. We would consider a pull request to add support for this in the migrations index API.

~Rowan

**Comment by weitzhandler** [comment]
@rowanmiller I can't seem to find the `IndexAttribute` attribute at all.
https://github.com/aspnet/EntityFramework/issues/2675

**Comment by rowanmiller** [comment]
@weitzhandler `IndexAttrbiute` was never part of DataAnnotations, it was something we had defined in our EF assembly. We may or may not have it in EF7 (there are some issues with the design we had in EF6 so we don't want to carry it over as-is). For the moment, you need to use the Fluent API to add indexes.

**Comment by weitzhandler** [comment]
@rowanmiller 
But the option doesn't exist in the fluent API either.
I tried to look at `modelBuilder.Entity<MyEntity>().Property(e => e.prop).*` for something related to `Index` or `Unique`, but found nothing.

**Comment by AndriySvyryd** [comment]
@weitzhandler The `Index` method is toplevel on the `EntityTypeBuilder`: ` modelBuilder.Entity<MyEntity>().Index(e => e.prop).Unique()`

**Comment by weitzhandler** [comment]
@rowanmiller 

I still miss the `IndexAttribute` anyway. I prefer attributes way over fluent. Especially when the model starts to become complex and the `OnModelCreating` becomes messy.
BTW, there should be a way to implement an interface in any entity that provides an `OnModelCreating` called from the context's one, this way, the creation of the entity-specific attributes is kept within the entities.

I understand about the `IndexAttribute` which is pretty technology-centric, but again, an attribute is just a useless thing on any DTO, so there is no real issue with annotating properties with technology specific attributes, given these attributes are part of any supported framework.

Anyway thanks for your help @AndriySvyryd

**Comment by weitzhandler** [comment]
@rowanmiller 

I still miss the `IndexAttribute` anyway. I prefer attributes way over fluent. Especially when the model starts to become complex and the `OnModelCreating` becomes messy.
BTW, there should be a way to implement an interface in any entity that provides an `OnModelCreating` called from the context's one, this way, the creation of the entity-specific attributes is kept within the entities.

I understand about the `IndexAttribute` which is pretty technology-centric, but again, an attribute is just a useless thing on any DTO, so there is no real issue with annotating properties with technology specific attributes, given these attributes are part of any supported framework.

Anyway thanks for your help @AndriySvyryd, anyway I haven't managed to find `Order` on the fluent API, is it around there?

**Comment by weitzhandler** [comment]
How do I define the index **order** via fluent API?

**Comment by rowanmiller** [comment]
@weitzhandler currently not possible. Feel free to open an issue to request it :smile:

**Comment by weitzhandler** [comment]
@rowanmiller
But when creating a multi-key index, does it take care of the order automatically? By what precedence?

**Comment by rowanmiller** [comment]
@weitzhandler oh do you mean the order of the columns rather than ASC/DESC? The order of columns is the order that you specify them in the API call to configure the index.

**Comment by weitzhandler** [comment]
@rowanmiller

Great, then!

On Jul 30, 2015 3:34 AM, "Rowan Miller" <notifications@github.com> wrote:
>
> @weitzhandler oh do you mean the order of the columns rather than
ASC/DESC? The order of columns is the order that you specify them in the
API call to configure the index.

**Comment by Kagamine** [comment]
+1 for IndexAttribute

**Comment by applenele** [comment]
+1 for IndexAttribute

**Comment by weitzhandler** [comment]
Yeah. Still hoping to see it back, I think it's not SQL-specific.
Perhaps the attribute should be changed to `UniqueAttribute`, which applies to ANY type of DB, even NoSql.

**Comment by Kagamine** [comment]
I don't think so. We often make a property as an index like a time field, They are able to be duplicated.

**Comment by weitzhandler** [comment]
So be it
Keep the IndexAttribute then...

**Comment by Kagamine** [comment]
Unique must be related to Index, because UniqueKey must be indexed.

**Comment by weitzhandler** [comment]
Whatever. Anyway I'd love to see it back.
I prefer attributes.
Otherwise there should be something like an `IConfigurationEntity(ModelBuilder builder)` interface, that is called on each entity when implemented.
Anyway I believe this is not achievable since that will require the an instance of each of the entities, which will not the optimal solution, and not always possible at all.

**Comment by jasonwilliams200OK** [comment]
@divega, @rowanmiller, wouldn't it make sense to keep this issue opened and add a label <kbd>up for grabs</kbd>. This looks pretty blunt in a wrong way to close the issue when clearly many consumers are asking for `IndexAttribute` feature. At least keep the discussion open to avoid duplicate issues (currently there are 5 closed issues on which people are +1'ing the same feature.. https://github.com/aspnet/EntityFramework/issues/107#issuecomment-162855173).

**Comment by rowanmiller** [comment]
@jasonwilliams200OK this issue was specifically about adding the ability to specify a 'WHERE' clause on an index via attributes. Agreed we have got a lot of feedback wanting an [Index] attribute, and we may introduce one based on that feedback. Looks like we don't have an issue tracking it yet, feel free to open one.

**Comment by jasonwilliams200OK** [comment]
@rowanmiller, should https://github.com/aspnet/EntityFramework/issues/2675 be reopened?

**Comment by rowanmiller** [comment]
Added https://github.com/aspnet/EntityFramework/issues/4050 to the backlog

**Comment by SimonOrdo** [comment]
Is this still true, as of RC1?

> "The Index method is toplevel on the EntityTypeBuilder: modelBuilder.Entity<MyEntity>().Index(e => e.prop).Unique()"

I can't find the Index method on EntityTypeBuilder.  Is it an extension method in another namespace?

**Comment by rowanmiller** [comment]
HasIndex is the method you are after - http://docs.efproject.net/en/latest/modeling/relational/indexes.html.

**Comment by joshcomley** [comment]
Is there any way in EF7 to add a unique constraint via migrations?

**Comment by joshcomley** [comment]
Figured it out:
            migrationBuilder.CreateIndex(
                name: ...,
                table: ...,
                column: ...,
                unique: true);

**Comment by joshcomley** [comment]
Or even better:

            migrationBuilder.AddUniqueConstraint(
                name: ...,
                table: ...,
                column: ...);

**Comment by mdoaie** [comment]
+1 for IndexAttribute

**Comment by tancevsasa** [comment]
+1 for IndexAttribute

**Comment by Int32Overflow** [comment]
+1 for IndexAttribute

**Comment by zbrad** [comment]
+1 for IndexAttribute

**Comment by JD-Robbs** [comment]
Adding my +1 for IndexAttribute.

**Comment by OronDF343** [comment]
+1 for IndexAttribute

**Comment by AndriySvyryd** [comment]
This issue is closed and will not be considered for planning purposes. Please direct all `IndexAttribute` feedback to https://github.com/aspnet/EntityFrameworkCore/issues/4050

**Comment by davidrevoledo** [comment]
+1 for IndexAttribute

**Comment by kanadaj** [comment]
> This isn't something we'd want to add to the attribute since it is very specific to relational databases. 

![image](https://user-images.githubusercontent.com/3247357/50525746-4eed5800-0ad5-11e9-8424-db34bb3bdb5b.png)

Given that there _is_ a shared package just for relational databases, that seems like a very weak excuse not to do it.

**Comment by tidusjar** [comment]
Is there an update for this?

**Comment by ajcvickers** [comment]
@tidusjar This issue is closed in favor of #4050, which is on the backlog.
