### ISSUE TITLE
[Question] How to .Include if .Find is used?

### ISSUE THREAD

**Issue by IdeaHunter** [dotnet/efcore#16990]
Lets imagine we have following model

```c#
public class PrincipalContext : DbContext
{
    public DbSet<Staff> Staffs { get; set; }
}
interface IWithPrincipal
{
    Principal Principal { get; }
}
public class Staff : IWithPrincipal
{
    public int Id { get; set; }
    public Principal Principal { get; set; } = new Principal();
}
```

And we want to fetch it from database by reflection instead of regular query syntax
```c#
var item = db.Find(typeof(Staff), staffId);
```
**Question:**
How do we .Include(nameof(IPrincipal)) in this case?

### Further technical details
EF Core version: 2.2.6
Operating system: windows
IDE:  Visual Studio 2019 16.1.6

**Comment by ajcvickers** [comment]
Duplicate of #6935
