### ISSUE TITLE
Blob + Async - memory consumption is enormous

### ISSUE THREAD

**Issue by alexk8** [dotnet/efcore#17005]
As an example, we are storing some large json strings in RDBMS (please don't say that's a bad idea, that's not the subject)
Extracting a single string of **500k** chars from db (mssql) in async-manner allocates **150Mb** of memory
```
  context.Blobs.Find(1); // allocates 4Mb for 500k - OK
  await context.Blobs.FindAsync(1); // allocates 150Mb for 500k- not OK
  //same for any Async:  ToListAsync,FirstAsync,SingleAsync,etc
``` 
`GC.GetTotalMemory` doesnt show this, this is trackable by `Process.PagedMemorySize64` and other tools.
CPU usage is also much bigger, but it's been reported long ago. I haven't been able to find issue about memory, sorry.
I can forsee an advice "dont read blobs with async", but I think people use long (some KBs) strings quite often and it can affect them too, but in a bit lesser scale.
Upd: some tests show that 150Mb jump arise when dealing with a single string of around 100k (90k is about normal). Trying to load 20 rows of 500000-char string makes GC heavily struggling for ~10seconds

**Comment by sdanyliv** [comment]
@alexk8, it can be not a EF Core problem, but DataProvider's issue. So it is better to mention which DataProvider is used.

**Comment by alexk8** [comment]
@sdanyliv 
Thanks, You're right. I've conducted a small test and it's been confirmed
I could suspect that at least, sorry :(
I'll create a new issue in System.Data.SqlClient repo.
```c#
            SqlConnection connection = new SqlConnection(msconnString);
            await connection.OpenAsync();
            var cmd = connection.CreateCommand();
            cmd.CommandText = "select * from myblobs where id=1";
            long mem01 = Process.GetCurrentProcess().PagedMemorySize64;
            //foreach (var i in Enumerable.Range(1, 20))
            //{
                var reader = await cmd.ExecuteReaderAsync();
                await reader.ReadAsync();
                var str = await reader.GetFieldValueAsync<string>(1);
                await reader.CloseAsync();
            //}
            long mem02 = Process.GetCurrentProcess().PagedMemorySize64;
            Console.WriteLine(mem02-mem01);
```
