### ISSUE TITLE
Auto increment not created (.net core 3.0)

### ISSUE THREAD

**Issue by ilaurensnl** [dotnet/efcore#17026]
To keep the explanation short; I got a .net core dbset, with a model containing an id with 'key' and 'DatabaseGenerated' attributes. The migration has:
```
Id = table.Column<int>(nullable: false)
.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
```
However when running it's not setting the 'auto increment',
```
Identity specification: No
(Is identity) No
Rest is empty
```

The table itself is generated, it's a primary key; however it does nothing else beside that. it's worth to mention that I've tried **long** and **int** for the 'Id'

```
.net core 3.0
Microsoft.EntityFrameworkCore.SqlServer: 3.0.0-preview7.19362.6
Microsoft.AspNetCore.Identity.EntityFrameworkCore: 3.0.0-preview7.19365.7
```

For those interested:
```     
public DbSet<Product> Product { get; set; }

--
    public class Product
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }

--
            migrationBuilder.CreateTable(
                name: "Product",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    Description = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Product", x => x.Id);
                });
```

**Comment by ajcvickers** [comment]
@ilaurensnl Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by ilaurensnl** [comment]
@ajcvickers decided to follow your advice, that way it seems like the auto increment was created. Afterwards started my project and tried it that worked too! I absolutely got no idea what caused it, but it seems like a restart of visual studio fixed the problem? odd.. Spend a few hours playing with it :(

I will close it for now. Thanks for the speedy response!
