### ISSUE TITLE
Migration fails on changing computed value to non-computed value property

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#17046]
When I create an property as computed value and change it afterwards to an non-computed value, the migration will result in an exception.

### Steps to reproduce
1. Create an entity with computed value property
2. do an migration
3. Change the computed value property to an non-computed value
4. do another migration

The migration will now create an `migrationBuilder.AlterColumn<T>(..)` entry. An execution of such an migration will fail with SQL Server, but an `DropColumn`/`AddColumn` migration behavior would fix this.

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows

**Comment by ajcvickers** [comment]
Duplicate of #14075
