### ISSUE TITLE
Need to setup unique index with a where condition

### ISSUE THREAD

**Issue by SidShetye** [dotnet/efcore#17059]
We have a system where we need to express a unique index for all in-use (not-soft-deleted) resources in a multi-tenant system. The simplified SQL is 

```SQL
CREATE UNIQUE NONCLUSTERED INDEX [IX_Unique_Composite_Name_For_Active]
    ON [dbo].[Resources]([TenantId] ASC, [Name] ASC) 
    WHERE MarkedForDeletionAt IS NULL; -- <== this!
GO
```

How can this be expressed in EF Core 3.x ? The closest is 
```c#
resource
.HasIndex(r => (r.MarkedForDeletionAt == null) ? new { r.TenantId, r.Name } : null ) // 
.IsUnique();
```
but that throws an exception 
```
The properties expression 'r => IIF((r.MarkedForDeletionAt == null), new <>f__AnonymousType8`4(TenantId = r.TenantId, Name  = r.Name), null)' is not valid. The expression should represent a simple property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'. (Parameter 'propertyAccessExpression')
```

### Questions:

1.  How do we express this constraint into the EF Core model itself? 

2. If EF Core doesn't support this at the moment (please do soon), what workflow is suggested for engineers using EF Core? Can we express most of the model EF and then apply the remaining conditions as some raw SQL that's always applied?

### Further technical details

EF Core version: `3.0.0-preview7.19362.6`
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: Windows 10 x64 v1903
IDE: Visual Studio 2019 16.2.1

**Comment by smitpatel** [comment]
Use
`resource.HasIndex(r => new { r.TenantId, r.Name }).IsUnique().HasFilter("[MarkedForDeletionAt] IS NULL")`

**Comment by SidShetye** [comment]
Confirmed that this works. Thank you.
