### ISSUE TITLE
Feature Request: DbMigrator can handle cases where db migrations and code migrations have diverged

### ISSUE THREAD

**Issue by jakingmsft** [dotnet/efcore#17078]
Currently the only supported scenarios for automatically applying migrations from code to db, whether by `dbContext.Database.Migrate()` or by `dbMigrate.Update()`, are when the code is ahead of or equal to the db.

```
code: A -> B -> C
  db: A -> B

code: A -> B
  db: A -> B
```

There is another case where code is behind the db

```
code: A -> B
  db: A -> B -> C

```

which can be handled by specifying the migration to move back to, e.g. `dbMigration.Update("B")` in code or `Update-Database Target-Migration B` in Package Manager Console. As far as I know, there is no way to automatically move back to the migration in the code, so it must be done manually or by writing code to automate.

There is one more, complex case, where the code and db have diverged

```
       C -> D (code)
      /
A -> B 
      \
       X -> Y -> Z (db)
```

This can be fixed by targeting the nearest common ancestor migration, then the latest db migration. Again, no way of doing this as far as I know.

What would be nice would be to have an extension method `dbMigrator.UpdateSmart()` that could handle all the cases. It would be especially useful for a development team using EF because when a developer checks out any version of the code from version control he or she can sync the local db's schema with a single command.

**Comment by ajcvickers** [comment]
@bricelam to take a look.

**Comment by bricelam** [comment]
This would require #1911 and #2532

**Comment by ajcvickers** [comment]
@jakingmsft Thanks for the suggestion, but after discussing this we think that the complexities of making this work reliably and consistently probably outweigh the value, especially when compared to other areas we could spent development time on instead.
