### ISSUE TITLE
Multiple Left Joins Can Cause Client Side Evaluation

### ISSUE THREAD

**Issue by iamwyza** [dotnet/efcore#17095]
Describe what is not working as expected.

If you setup multiple left outer joins using Linq Queries, and put all of the DefaultIfEmpty() calls at the end, it will cause EF to do local joins rather than SQL joins.  This is in a scenario where relationships are not defined on the entities.

### Steps to reproduce

```c#
from parent in context.Set<ParentEntity>().Where(parent => parent.Id == 1)
   join child in context.Set<ChildEntity>()
      on parent.ChildId equals Child.Id into childA
   join child2 in context.Set<ChildSecondEntity>()
      on parent.ChildSecondId equals child2.Id into childB
from subChildA in childA.DefaultIfEmpty() 
from subChildB in childB.DefaultIfEmpty()
select new ParentChildModel { /* assigns all the values */ };
```

This will result in the following messages:

```The LINQ expression 'join ChildSecondEntity child2 in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Temp.ChildSecondEntity]) on [parent].ChildSecondId equals Convert([child2].Id, Nullable`1)' could not be translated and will be evaluated locally.```

If however you do the following, it works fine: (basically just move the "from subChildA" up to right after the join).  This is true if you have 2, 3, or 4 etc left joins.

```c#
from parent in context.Set<ParentEntity>().Where(parent => parent.Id == 1)
   join child in context.Set<ChildEntity>()
      on parent.ChildId equals Child.Id into childA
from subChildA in childA.DefaultIfEmpty() 
   join child2 in context.Set<ChildSecondEntity>()
      on parent.ChildSecondId equals child2.Id into childB
from subChildB in childB.DefaultIfEmpty()
select new ParentChildModel { /* assigns all the values */ };
```

It could be simply that documentation should exist that explicitly states that multiple joins must work this way, however, it'd be nice for it to handle both scenarios the same if possible.

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 - Spring 2019
IDE: VS 2019.2

**Comment by smitpatel** [comment]
Unless you do GroupJoin-SelectMany-DefaultIfEmpty in successive order as in 2nd case, it is not necessarily left join to server. Linq GroupJoin or SelectMany has much more capabilities then what a database can handle. While GJ-SM-DIE is pattern to generate left join on server, proper pattern must be used.

**Comment by iamwyza** [comment]
Can I suggest that the documentation be updated to contain a proper example of this?  Searching the documentation for GroupJoin only has one item in the 2.0 release notes saying that it's better now.  And the other relational examples all assume navigational properties.  Examples on StackOverflow are actually how I arrived at the originally incorrect approach of doing all the DefaultIfEmpty lines at the end rather than in between.

Separately (but related), I would really love a LINQ extension as part of EF Core that cuts down on the code size of GroupJoin/SelectMany/DefaultIfEnty.  Readability of doing those as Lambdas is a nightmare.

**Comment by sdanyliv** [comment]
> I would really love a LINQ extension as part of EF Core that cuts down on the code size of GroupJoin/SelectMany/DefaultIfEnty. Readability of doing those as Lambdas is a nightmare.

It can be sample for implementation: we have did this enhancement in **linq2db** library. So, queries are simpler and easier to change, especially if you need to switch from `Left` to `Inner` join or change join order:
```cs
  from parent in context.Set<ParentEntity>().Where(parent => parent.Id == 1)
  from child1 in context.Set<ChildEntity>().InnerJoin(child1 => child1.Id == parent.ChildId)
  from child2 in context.Set<ChildEntity>().LeftJoin (child2 => child2.Id == parent.ChildSecondId)
  from child3 in context.Set<ChildEntity>().RightJoin(child3 => child3.Id == parent.ChildThirdId)
  from child4 in context.Set<ChildEntity>().FullJoin (child4 => child4.Id == parent.ChildFourthId)
  select new ParentChildModel { /* assigns all the values */ };
```
