### ISSUE TITLE
Interpret System.ComponentModel.DefaultValueAttribute

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#17103]
As suggested in PR: https://github.com/aspnet/EntityFrameworkCore/pull/16986/files

However, note that this isn't even a data annotation attribute--it's just something from ComponentModel--and we would need to be sure that the interpretation we use for EF Core is not in conflict with how other parts of the ecosystem (e.g. WinForms/WPF/UWP/Xamarin visual designers)  use it.

**Comment by ElderJames** [comment]
Another idea I have is to add an property to the `ColumnAttribute`
