### ISSUE TITLE
Cannot apply DbContext to existing database

### ISSUE THREAD

**Issue by zygmuntix** [dotnet/efcore#17127]
**Describe what is not working as expected.**
I called `IMigrator.Migrate()` method on runtime with existing database. I would like to apply existing DbContext to existing database.
So my idea was to call:
`dotnet ef migrations add --IgnoreChanges`
However --IgnoreChanges option is not available in EF Core (it was available in EF).
Is it somehow possible to create initial EF Core migration with existing database?

I have a foreach loop running through all migrations but program runs exception because the model already exists. Here is the code:
```
var pendingMigrations = dbContext.Database.GetPendingMigrations().ToList();
            if (pendingMigrations.Any())
            {
                var migrator = metricContext.Database.GetService<IMigrator>();
                foreach (var targetMigration in pendingMigrations)
                {
                    migrator.Migrate(targetMigration);
                }
            }
```

Program tries to apply Initial migration for database that already exists and has the same structure as described in initial migration but fails with System.Data.SqlClient.SqlException telling that there is already an object named XXX existing in the database (I ommitted the real name of the object).

**Comment by ajcvickers** [comment]
@zygmuntix This is being tracked by #2167, which also has some suggestions on how to proceed for now.
