### ISSUE TITLE
why AddDbContextPool poolSize exceed Max_Pool_Size 

### ISSUE THREAD

**Issue by windsOne** [dotnet/efcore#17167]
https://github.com/aspnet/EntityFrameworkCore/blob/c2a39d700963f71c0035fa297aae6ec430578951/src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs#L146

https://github.com/dotnet/corefx/blob/1bb52e6a3db7f3673a3825f3677b9f27b9af99aa/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionString.cs#L35

**Comment by ajcvickers** [comment]
@windsOne That's a pool size for SQL Server connections. It doesn't have any relevance to `DbContext` pooling--the two things are not connected.
