### ISSUE TITLE
Cosmos DB is not compatible with Xamarin.Forms anymore

### ISSUE THREAD

**Issue by arivoir** [dotnet/efcore#17178]
I tried to update the _Microsoft.EntityFrameworkCore.Cosmos_ package from nuget today, and suddenly realized the library was moved to the NetStandard2.1, which is much more restrictive than 2.0, and breaks compatibility with most platforms, like Xamarin.Forms. Is it intended cosmos db to work only with NetCore?

**Comment by arivoir** [comment]
I'm seeing cosmos is not the only package with this change. The whole EntityFrameworkCore is dropping support for NetStandard 2.0
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/3.0.0-preview8.19405.11

Why? Will all the platforms WPF, UWP, Xamarin updated to support NetStandard2.1?

**Comment by ajcvickers** [comment]
@arivoir This is a strategic decision around .NET as a whole, rather than something specific to EF Core.  Xamarin will target .NET Standard 2.1 (although I don't know the timeframe) and will continue to be a target for EF Core. WPF and UWP I can't comment on.

**Comment by arivoir** [comment]
I see, thanks for the info.

**Comment by arivoir** [comment]
@ajcvickers According to Xamarin guys, Xamarin will eventually have support for NetStandard 2.1, but there are no plans in the short term. Apparently it would be ready for Net 5. On the other hand, EntityFrameworkCore is dropping support for NetStandard 2.0 (According to the released packages in nuget) for .NetCore 3. This would be a really serious breaking change, since all the Xamarin will lose EF support (Or they will have to stick to old packages).
I think the most reasonable would be the EFCore llibraries to continue having support for NetStandrad 2.0 until Net5. What do you think?

**Comment by danielmeza** [comment]
@arivoir  @ajcvickers  I have test it by changin mi share code to .net standard 2.1 and goes well, the Android team has complete implement it so we can now add netstandard2.1 reference to android project, the iOS have some issues but the are almost done.
