### ISSUE TITLE
Adding an -exclude option to db first scaffold

### ISSUE THREAD

**Issue by denious** [dotnet/efcore#17184]
As described [in the docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding#specifying-tables), it is possible to limit generated models by specifying table names. Works great until you have 20 tables and want 18 of them!

So this is a feature request to add an -exclude option. :)
Thanks!

**Comment by smitpatel** [comment]
Duplicate of #6182

**Comment by ErikEJ** [comment]
@denious maybe EF Core Power Tools can help you?
