### ISSUE TITLE
Randomly mi EF context loos a relational propertie making it null. Why can it be?

### ISSUE THREAD

**Issue by ufalak** [dotnet/efcore#17180]
0

I have a rest service made in C# net core 2.2 and EF. My code run a loop trough entities making things with them, using always the same db context.

Randomly a very few times one of my objects loose one of its relational properties making it null after db.savechanges() line.

This bug happen the first time on production environment and i've spend lot of time trying to figure out what happening and trying to reproduce it in my local environment.

After a lot of time i can reproduce it just once randomly. On every post i make to the service i get the error until i restart the execution of the application. After that, again was imposible to reproduce it.

 ```
EliminarJustificacionesAfectadas(db, usuarioId, minutosToleranciaTurnoDefinido, empresaId);
        LimpiarAlReprocesar(db, TipoOperacionFichadaFija);

        if (!ObtieneDatoLaboral(db))
        {
            new FichadaAuditoria(this, (int) TiposOperacionAuditoria.Modificacion, usuarioId).Crear(db);
            db.SaveChanges();
            return this;
        }

        new FichadaAuditoria(this, (int) TiposOperacionAuditoria.Modificacion, usuarioId).Crear(db);
        db.SaveChanges(); //after this line a class propertie call DatoLaboral set to null the attribute Persona (DatoLaboral.Persona is set to null) }
```

**Comment by ajcvickers** [comment]
@ufalak There's not enough here for us to be able to figure out what is going on. One think to check is that you're not using the same context instance concurrently from multiple threads; the context is not thread safe. Other than that, we're likely going to need to reproduce this locally in order to help.

**Comment by ufalak** [comment]
I think that the problem is that im using the same context to process thousands of items.
I ve tried to segregate the items on smaller groups and now its working aparently fine.

But it si very strange that randomly just loose the attribute content
