### ISSUE TITLE
FeatureRequest: IQueryable EnsureHasIndex()

### ISSUE THREAD

**Issue by alexk8** [dotnet/efcore#17192]
When writing a query I want to state that a particular index (declaration) should exist.
Example:
```c#
  context.Set<Events>().Where(x=>x.date>lastDate).EnsureHasIndex(x=>x.date).ToList();
```
This should throw an exception if index does not exist in context configuration.
Goal: Code-reviewer (or anyone who sees the code) could be sure that a query performs more-or-less efficiently, without digging into schema declaration.
Also, a hint might be issued to a db-provider to use a specific index but it's not really needed.
Indexes usage is very important when dealing with data and small omission may lead to significant performance issues

**Comment by ajcvickers** [comment]
Thanks for the suggestion. This doesn't really match with the design philosophy of EF at all, so it's not something we plan to implement.
