### ISSUE TITLE
Add Support for null owned types

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#17201]
### Describe what is not working as expected.

Owned entity types can't be null.

> Reference navigations to owned entity types cannot be null unless they are explicitly mapped to a separate table from the owner

Source: [Current shortcomings](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#current-shortcomings) of Owned Entity Types

### Exception message: 
> System.InvalidOperationException: The entity of type 'MyOwnedType' is sharing the table 'MyOwnerType' with entities of type 'MyOwnedType', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.

### Workarounds

[Temporary Work-Around to Allow Null Value Objects](https://msdn.microsoft.com/en-us/magazine/mt846463.aspx?f=255&MSPPError=-2147217396)

https://stackoverflow.com/questions/48063630/nullable-owned-types-in-ef-core

### Steps to reproduce
https://github.com/spottedmahn/EntityFramework.Docs/blob/10a051c3e5ab0aca0d7c70df52bd833e92503f71/samples/core/Modeling/OwnedEntities/Program.cs#L23

### Further technical details
EF Core version: 2.1.11
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2019 Preview 16.3 Preview 2

Sorry if I'm opening a duplicate request, I couldn't find one...

**Comment by smitpatel** [comment]
#9005
