### ISSUE TITLE
Navigation properties does not survive SaveChangesAsync()

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#1721]
Consider the following example:

```
var entity1 = new Entity1();
var entity2 = new Entity2();

entity1.Entity2 = entity2;

_db.Entity1s.Add(entity1);
_db.Entity2s.Add(entity2);

await _db.SaveChangesAsync();
```

After `SaveChangesAsync()` completes I would expect `entity1.Entity2 == entity2`, but it is instead `null`. Is this a bug, or is it by design that I need to query the database after the save to get the navigation properties re-populated?

**Comment by ajcvickers** [comment]
@rmja Can you post the code for your entity types and DbContext?

**Comment by rmja** [comment]
@ajcvickers (@rowanmiller), I will try and elaborate the problem details. Let me know if you need further details. I use beta3.

	public class ItemPageItem
	{
		public int Id { get; set; }

		public ItemPageItemGridsterViewTile GridsterViewTile { get; set; }
	}

	public class ItemPageItemGridsterViewTile
	{
		public int ItemPageItemId { get; set; }
		public byte Width { get; set; }
		public byte Height { get; set; }
		public byte Row { get; set; }
		public byte Column { get; set; }

		public ItemPageItem ItemPageItem { get; set; }
	}

	public class MasterContext : DbContext
	{
		public DbSet<ItemPageItem> ItemPageItems { get; set; }
		public DbSet<ItemPageItemGridsterViewTile> ItemPageItemsGridsterViewTile { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<ItemPageItemGridsterViewTile>().Key(x => x.ItemPageItemId);
			modelBuilder.Entity<ItemPageItem>().HasOne(x => x.GridsterViewTile).WithOne(x => x.ItemPageItem);
		}
	}


Test code:

	var itemPageItem = new ItemPageItem();
	itemPageItem.GridsterViewTile = new ItemPageItemGridsterViewTile();

	_db.ItemPageItems.Add(itemPageItem);
	_db.ItemPageItemsGridsterViewTile.Add(itemPageItem.GridsterViewTile);

	await _db.SaveChangesAsync();

	// itemPageItem.GridsterViewTile == null here.

I have been trying to get more details by adding the source of the beta3 to my solution, but without any luck. The beta3 tag in cannot build as far as I can tell.

**Comment by ajcvickers** [comment]
@rmja The ItemPageItemGridsterViewTile entity is not being tracked. The Add call in EF7 is not recursive--it only adds the top level entity. You can either Add both entities explicitly, or take a look at context.ChangeTracker,TrackGraph.

**Comment by rmja** [comment]
@ajcvickers , I don't follow you:-/ I am adding both entities as far as I can tell. They are also both persisted in the database, so when I do `itemPageItem = _db.ItemPageItems.Include(x => x.GridsterViewTile).SingleOrDefault(x => x.Id == itemPageItem.Id)`, then I have the `GridsterViewTile` relation re-established.

**Comment by ajcvickers** [comment]
@rmja I'll investigate further

**Comment by ajcvickers** [comment]
@rmja This does not repro for me with the current bits. I'm going to assume that it is fixed since code has changed in this area but please feel free to re-open the bug with a full repro if the issue is still happening for you with the latest bits.
