### ISSUE TITLE
Migrating EF Core Identity 1.0 to 2.2: Invalid column name 'ApplicationUserId'

### ISSUE THREAD

**Issue by Ro3A** [dotnet/efcore#17213]
I've migrated a .net core 1.0 project to 2.2, Everything seemed fine until _userManager.IsInRoleAsync was called, at which point I received "Invalid column name 'ApplicationUserId'."

After digging and reviewing other related issues, and trying various solutions, I'm unable to figure out how to utilize my existing database with the latest EF Core packages. 

The latest version has a property "ApplicationUserId" - this property (and column) did not exist at all in 1.0 and I've not found any migration related documentation mentioning this. 

I'm using net461 TFM, with .net core 2.2 packages and my ApplicationDbContext class implements IdentityDbContext<ApplicationUser>.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.1#entity-types 

The link above does not reference "ApplicationUserId" and so far, the only place I've found this in Github source code is in a few tests. 

I'm sure I'm overlooking something small here, but if anyone can point me the in the right direction, I'd be very grateful.

**Comment by ajcvickers** [comment]
This is due to a schema change in ASP.NET Core Identity between 1.x and 2.x. See the [migration guide]( https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1) and also the discussion here: https://github.com/aspnet/EntityFrameworkCore/issues/11763
