### ISSUE TITLE
DbContextServices.get_DataStoreServices throws NullRef

### ISSUE THREAD

**Issue by egorpavlikhin** [dotnet/efcore#1722]
DbContextServices.get_DataStoreServices throws NullRef when there is a missing service registration.

NullReferenceException: Object reference not set to an instance of an object.
Microsoft.Data.Entity.Infrastructure.DbContextServices.get_DataStoreServices()
Microsoft.Data.Entity.Storage.DataStoreServices.GetStoreServices(IServiceProvider serviceProvider)
Microsoft.Data.Entity.Storage.DataStoreServices.<>c__DisplayClass17_0.<get_DataStoreFactory>b__1()
Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()

**Comment by egorpavlikhin** [comment]
Looks like it's not a missing service registration, but an old auth cookie that was causing the problem. Regardless, EF shouldn't throw NullRef there.

Similar bug here https://github.com/aspnet/EntityFramework/issues/1241

**Comment by ajcvickers** [comment]
Lots of re-design in this area. Original bug no longer repros.
