### ISSUE TITLE
UseInternalServiceProvider and EnableServiceProviderCaching for 3.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/efcore#17224]
@ajcvickers I'm updating our [Integration Testing topic (link to live topic)](https://docs.microsoft.com/aspnet/core/test/integration-tests) sample app for 3.0 (Pre8 bits) for our issue to update the topic+sample for 3.0 at [Integration Testing update to 3.0 (aspnet/AspNetCore.Docs \#13353)](https://github.com/aspnet/AspNetCore.Docs/issues/13353).

There's an unrelated issue in the new 3.0 sample app dealing with ASP.NET Core Identity and the in-memory dB. This issue doesn't affect my questions here, but I just want to mention it in passing. ASP.NET Core engineering will have a look at it soon on [Identity exception when using an InMemory database (aspnet/AspNetCore \#13187)](https://github.com/aspnet/AspNetCore/issues/13187).

### Part 1

On [ServiceProviderCache adds more and more IServiceProviders when running integration tests (aspnet/EntityFrameworkCore \#16369)](https://github.com/aspnet/EntityFrameworkCore/issues/16369) with regard to `UseInternalServiceProvider` and `EnableServiceProviderCaching`, you said ...

> The workaround for 3.0 is also easier, since we added `options.EnableServiceProviderCaching(false)`.

For 3.0, I'm not sure if I'm supposed to **_replace_** `options.UseInternalServiceProvider(serviceProvider);` with `options.EnableServiceProviderCaching(false)` ... **_or add_** `EnableServiceProviderCaching`?

According to IntelliSence/API remarks: If calling `UseInternalServiceProvider`, then calling `EnableServiceProviderCaching` no-ops.

### Part 2

I'm facing a problem with namespaces/packages to get access to these members ...

<img width="578" alt="Capture" src="https://user-images.githubusercontent.com/1622880/63213400-9448af00-c0d1-11e9-8ef9-bac045ca21de.PNG">

I've put the whole app up at https://github.com/guardrex/IntTestSamp, which is two projects: The web app and the test project. I'm stuck getting access to the members here ...

https://github.com/guardrex/IntTestSamp/blob/master/tests/RazorPagesProject.Tests/CustomWebApplicationFactory.cs#L30-L31

### Notes

* In the test app project file, you'll see commented-out package references. I was just getting them sorted out for the app now that EF Core is off of the `App` metapackage. I'll clean that up before all of this goes into the upcoming docs PR.
* The web app runs sans the unrelated issue with the InMemory dB and Identity.
* The test project runs (all of the tests pass) without `UseInternalServiceProvider`.
* The behavior of running the tests without `UseInternalServiceProvider` *seems to be* just that the dB is initialized with extra test data owing to a new internal service provider for every test, which was described on the other issue. That's fine and seems like the expected behavior.

### Questions

I think if you can help me craft `ConfigureWebHost` to call `UseInternalServiceProvider` (perhaps it's just namespaces/packages that I don't have a handle on here) and clarify if/how `EnableServiceProviderCaching` should be used that we'll be good here.

**Comment by guardrex** [comment]
Update: This issue isn't blocking us. We're able to perform integration testing without `UseInternalServiceProvider` and `EnableServiceProviderCaching`. The latest sample project for the [Integration Testing doc](https://docs.microsoft.com/aspnet/core/test/integration-tests) is here ...

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/test/integration-tests/samples/3.x

This specific file (*CustomWebApplicationFactory.cs*) is here ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/CustomWebApplicationFactory.cs

Seems to work fine in this form.

Note that if we do move it back to calling these methods, I'm still not clear on a point: Which one should be called, or should it be both? Remarks seem to indicate that we would only call `options.EnableServiceProviderCaching(false)` in this scenario.

**Comment by ajcvickers** [comment]
@guardrex It depends. If you explicitly want EF  to use a different internal service provider for each test, then, turning off service provider caching is the best option. Otherwise, finding and correcting whatever it is that is causing a new service provider to be built is the best option. If that isn't possible because new dependencies are created for each test and this can't be changed, then again turning off service provider caching would be the way to go. Note, however, every test will be doing a lot of work. Calling `UseInternalServiceProvider` is almost never the right thing to do.

**Comment by guardrex** [comment]
Fair enough ... I'm not really sure if the community will have that scenario. We certainly haven't had any questions about it yet. I think on that basis that we're ok today with the current guidance and sample.

We'll keep an :ear: open for feedback from the community.

Thanks for your help.
