### ISSUE TITLE
Feature proposal - [REVENG] Add a default pluralizer implementation

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#17220]
@bricelam suggests adding Humanizer as a default pluralizer for Reverse eng. See https://github.com/ErikEJ/EFCorePowerTools/issues/243 - willing to do a PR if there is interest in this?

**Comment by bricelam** [comment]
Dupe of #11160

**Comment by ErikEJ** [comment]
Should it be an additional NuGet package, like your EF6 pluralizer, @bricelam ?

**Comment by bricelam** [comment]
No, I think EFCore. Design can reference Humanizer directly
