### ISSUE TITLE
Question - RevEng - Alternate DataSources?

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#1723]
Will RevEng work with an alternate EF /  DataSource Provider - or is RevEng purely for  SqlServer only?

If the latter, would you consider implementing a provider model for it in the future, so for example, it could work with other data sources / EF Providers?

**Comment by divega** [comment]
A lot of details of the design are actually emerging from iterating over the SQL Server implementation at the moment but the intent is indeed that each provider will be able to plug in its own components for reverse engineering. 

Another one of the goals is to be very flexible about how schema discovery is implemented across different providers. That aspect was very rigid in  previous versions of EF (e.g. the contract at the provider model was that each provider needed to respond to a set of varying metadata queries which were expressed as EF queries) and was a big pain point for many provider writers.

**Comment by dazinator** [comment]
Cheers @divega - that's good to know, thank you.
