### ISSUE TITLE
Entity type requires a primary key to be defined -  when not even used/defined in Context.

### ISSUE THREAD

**Issue by iby-dev** [dotnet/efcore#17237]
I am getting the following error:

`The entity type 'ConditionField' requires a primary key to be defined`

Whenever i try to instantiate my context called: `OnlineApplicationsDbContext`  - EfCore throws a strop about the above entity not having a PK.

Now here's where it gets a little strange - i am not even using or referencing that entity in my new context. None of my tables/entities defined in my new context have any business with the `ConditionField` entity.

N,B: my context `OnlineApplicationsDbContext` was copied and pasta'ed from a larger context i wrote a while ago: `ApplicationsDbContext` which did define and reference the entity `ConditionField`.

**Comment by divega** [comment]
@iby-dev you haven't provided some of the information (e.g. repro code, what version of EF Core you are using, etc.) needed to be able to tell you for sure what is going on, but if I had to guess, I would say `ConditionField` is referenced indirectly by some entity in your model, you just haven't found it yet. 

You can try explicitly ignoring the type in OnModelCreating or using NotMappedAttribute as a workaround.

**Comment by iby-dev** [comment]
@divega - how would i ignore the entity in question in the `OnModelCreating` event?

**Comment by divega** [comment]
@iby-dev The documentation describes how to [include and exclude types](https://docs.microsoft.com/ef/core/modeling/included-types) in the model.

> Is there a chance that EF expects all 9 tables to be defined in the context?

That would be very unlikely. The only part of EF Core that reads schema information from the database is the DbContext scaffolding commands.

**Comment by iby-dev** [comment]
TY - this did the trick for me.

I still have no idea why this entity is being picked up but the above link worked for me.

Ty.
