### ISSUE TITLE
Cosmos: Diagnostic events including statistics (query cost, activity id)

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17298]

**Comment by roji** [comment]
@AndriySvyryd assignment?

**Comment by AndriySvyryd** [comment]
@roji It's fixed, why would it need assignment?

**Comment by roji** [comment]
I thought we do assignments for fixed issues - this can be useful e.g. when people comment on the issue later, we know immediately who dealt with it. Looking at our closed issue list, it seems like sometimes we do it, sometimes not...

**Comment by AndriySvyryd** [comment]
I always unassign myself, but remain subscribed

**Comment by roji** [comment]
Will bring up in some upcoming meeting to see what people think...

**Comment by chuckgiddens** [comment]
How do I enable this?  Not mentioned anywhere but here!

**Comment by AndriySvyryd** [comment]
@chuckgiddens Same as with all events in EF Core you can use [Logging](https://learn.microsoft.com/ef/core/logging-events-diagnostics/extensions-logging) or [Diagnostic Listeners](https://learn.microsoft.com/ef/core/logging-events-diagnostics/diagnostic-listeners) with events found in https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.diagnostics.cosmoseventid
