### ISSUE TITLE
EF6 convert to EF7

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#1729]
Hi Guys,

I have an weird issue for the EF7.
My Linq is as below

var query = _product.Table;
query = query.OrderBy(l => l.IsoCode);

int Total = query.Count;
var List = query.ToList();

for the EF 6 it will generate in sql profiler
SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Product] AS [Extent1]
    )  AS [GroupBy1]

for the EF 7 it will generate which make the apps crash.
SELECT COUNT(*)
FROM [Product] AS [p]
ORDER BY [p].[IsoCode]

What is the work around way?

**Comment by maumar** [comment]
This should be fixed in the current build

**Comment by rowanmiller** [comment]
Please reopen if it is not fixed
