### ISSUE TITLE
Cosmos: ETag concurrency control

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17299]
Add support for ETags and if-match conditions

**Comment by sebhaub** [comment]
Do i understand this correctly, that currently there is no support for optimistic locking in EFCore.Cosmos or do i miss some information here? 

We want to migrate from a custom implementation to EFCore but rely on the ETag based optimistic locking.

**Comment by AndriySvyryd** [comment]
@sebhaub Your understanding is correct. Please vote on the first post (👍) to help us prioritize the missing features.

**Comment by jviau** [comment]
So if optimistic concurrency is not performed by default via etags, is it possible to get it to work via adding a property to your model that is mapped to cosmos etag field, and then telling efcore it is a concurrency check? https://docs.microsoft.com/en-us/ef/core/saving/concurrency, https://docs.microsoft.com/en-us/ef/core/modeling/concurrency

``` CSharp
class MyContext : DbContext
{
    public DbSet<Person> People { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>()
            .Property("_etag")
            .IsConcurrencyToken();
    }
}

public class Person
{
    private string _etag;
    public int PersonId { get; set; }
    public string LastName { get; set; }
    public string FirstName { get; set; }
}
```

I haven't tested this myself, so it might need other configuration (like saying value is generated for etag?). Just curious if this is a work around for now.

**Comment by AndriySvyryd** [comment]
@jviau Currently the Cosmos provider ignores the `IsConcurrencyToken` call. Etags are really the only reliable way of implementing optimistic concurrency on Cosmos.

**Comment by jviau** [comment]
@AndriySvyryd thank you for the clarification.

Another question - if the cosmos container is configured to use etag concurrency checks, would the cosmos SDK or cosmos endpoint not enforce the concurrecny itself? As in, ef core cosmos provider would recieving a `409 Conflict` when performing an update with an old etag?

**Comment by AndriySvyryd** [comment]
@jviau There's really no etag configuration at the SDK level. Etags are always generated, but will only be used if supplied in the ItemRequestOptions.IfMatchEtag or ItemRequestOptions.IfNoneMatchEtag properties. This is the work tracked by this issue.

**Comment by jviau** [comment]
Thank you! I understand now.

**Comment by esolCrusador** [comment]
So I see that issue is closed but how to setup optimistic concurrency for EntityFramework + CosmosDb? Or is it switched on by default?
