### ISSUE TITLE
Cosmos: API to configure throughput

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17301]
Add API for configuring container throughput and database throughput (manual or autoscale)

**Comment by pavitrag123** [comment]
When can this be provisioned in efcore?

**Comment by AndriySvyryd** [comment]
@pavitrag123 See https://docs.microsoft.com/en-us/ef/core/what-is-new/index#release-planning-process
Vote (👍 ) for the features that are important to you.

**Comment by jrahulroy** [comment]
👍
