### ISSUE TITLE
Cosmos: Translate SelectMany

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17312]

**Comment by roji** [comment]
For at least most scenarios of SelectMany, `SELECT * FROM c IN X.Y.Z` seems perfect ([see docs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-object-array#Iteration)).

**Comment by gamontal** [comment]
@roji Can you please provide an example of an equivalent query translated to LINQ? I'm trying to filter a list of documents based on values located in nested collections. For example:

```json
{
  "Id": "<id>",
  "collection1": [
    {
       "collection2": [
         "propToFilterOn": "<value>"
       ]
    }
  ]
}
```

I can retrieve the values using LINQ on the client-side:

```csharp
entity.AsEnumerable().Where(e => e.collection1
                    .SelectMany(e => e.collection2).Any(d => d.propToFilterOn == "lookUpValue")))
```
But, if I try to run this directly against EF, I get a query translation exception.

**Comment by roji** [comment]
@gamontal translating SelectMany on Cosmos isn't yet supported - that's why this issue is still open.
