### ISSUE TITLE
Cosmos: Add explicit partition key support for queries

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17320]
The partition key would be specified using `.WithPartitionKey()`, e.g.
```C#
var blogs = context.Blogs.WithPartitionKey("10").ToList();
```

**Comment by AndriySvyryd** [comment]
Fixed by 7e02fdb340f0424786c145c9e0e4e8f293eb8621

**Comment by balukantu** [comment]
@AndriySvyryd , I would like to work on WithPartitionKey method. Could you please provide the EFCore version in which the fix is available.

**Comment by AndriySvyryd** [comment]
@balukantu It's included in 5.0.0-preview3

**Comment by Anu666** [comment]
Hi @AndriySvyryd 

We are currently using Cosmos Client and planning on using EF Core provider for CosmosDB in our application. We had the below few questions regarding this. Hope you can shed some light on these.

1. Will EF Core provider would provide all the functionality which is provided by the Cosmos Client ?
2. If yes, would there be any performance improvement by switching to EF Core provider?
3. As our application is going to be in production soon, will there be regular updates and performance improvements?
4. As lot of the work is ongoing as per the thread above, would you recommend us to use EF Core provider in place of Cosmos Client?

Thanks
