### ISSUE TITLE
EF Core 3 Preview 8 QueryFilter not working

### ISSUE THREAD

**Issue by phillipbritain** [dotnet/efcore#17332]
I am having problems getting this to work. Here is my EF mapping:

```
modelBuilder.Entity<UserProject>(entity =>
 {
      entity.HasQueryFilter(p => !p.IsDeleted);
 });
```
I am using a repository pattern if that makes a difference. Here is my implementation:

`var test = _rw.UserProject.FindAll().ToList();`

_rw is Repository Wrapper which just exposes the DbSets of the DbContext. The FindAll() function only exposes the DbSet.

```
public virtual IQueryable<T> FindAll()
{
     return _db.Set<T>();
}
```
Other than that I can't think of any reason why this wouldn't work but perhaps I'm missing something.

**Comment by smitpatel** [comment]
Duplicate of #15264 

It is available in nightly builds.
