### ISSUE TITLE
Question: How to log Datareader or result value via ef core logger

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#17343]
Hi,

From IBM EF Core provider we are trying to capture result of ExecuteReader().
We could see value of output parameter but unable to see result.
Our context is:
```C#
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            IServiceCollection serviceCollection = new ServiceCollection();
            serviceCollection.AddLogging(builder => builder
               
                .AddConsole()
                .AddFilter(level => level >= LogLevel.Information)

            );

            var loggerFactory = serviceCollection.BuildServiceProvider().GetService<ILoggerFactory>();
  optionsBuilder.UseDb2(connectionString,
                  p => { p.SetServerInfo(IBMDBServerType.OS390); p.UseRowNumberForPaging(); });

            
            optionsBuilder.UseLoggerFactory(loggerFactory).EnableSensitiveDataLogging();

}
```
not sure what extra we need to configure to see the result.
Would you please suggest ?

Thanks,
Archana

**Comment by ajcvickers** [comment]
@archanasoni From just the information above it is not at all clear to me what you are asking. Please post a small, runnable project/solution or complete code listing that demonstrates the issue so that we can investigate.

**Comment by archanasoni** [comment]
@ajcvickers , We are actually running Code First scenario testing via IBM EF COre pkg against DB2 zOS from package manager console.
In our implementation for Code First in IBM EF Core, we had to use ExecuteReader() to call Stored Procedure, and we used below method to log the resulting data for ExecuteReader()

 Logger.CommandExecuted(
                   command,
                   DbCommandMethod.ExecuteReader,
                   commandId,
                   connection.ConnectionId,
                   result,
                   false,
                   startTime,
                   stopwatch.Elapsed);

from our test application we have configured logger :
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            IServiceCollection serviceCollection = new ServiceCollection();
            serviceCollection.AddLogging(builder => builder
               
                .AddConsole()
                .AddFilter(level => level >= LogLevel.Information)

            );

            var loggerFactory = serviceCollection.BuildServiceProvider().GetService<ILoggerFactory>();
  optionsBuilder.UseDb2(connectionString,
                  p => { p.SetServerInfo(IBMDBServerType.OS390); p.UseRowNumberForPaging(); });

            
            optionsBuilder.UseLoggerFactory(loggerFactory).EnableSensitiveDataLogging();

}

But in package manager console we see the output:
Executed DbCommand (1,259ms) [Parameters=[p1='0' (Direction = Output)], CommandType='Text', CommandTimeout='30']
      call DSNUTILU(uniqueID,'NO',command,?);

In above output data, only value for out parameter is getting displayed. But DSNUTILU returns resultset as well which is not getting displayed in log.

We want to know from test application what else we can configure to see the resultset which is being returned via DSNUTILU.

**Comment by ajcvickers** [comment]
@archanasoni What does it mean to "display the resultset" in the log?

**Comment by archanasoni** [comment]
@ajcvickers , code from RelationLoggerExtension:
public static void CommandExecuted(
            [NotNull] this IDiagnosticsLogger<DbLoggerCategory.Database.Command> diagnostics,
            [NotNull] DbCommand command,
            DbCommandMethod executeMethod,
            Guid commandId,
            Guid connectionId,
            [CanBeNull] object methodResult,
            bool async,
            DateTimeOffset startTime,
            TimeSpan duration)
        {
            var definition = RelationalStrings.LogRelationalLoggerExecutedCommand;

            var warningBehavior = definition.GetLogBehavior(diagnostics);
            if (warningBehavior != WarningBehavior.Ignore)
            {
                definition.Log(
                    diagnostics,
                    warningBehavior,
                    string.Format(CultureInfo.InvariantCulture, "{0:N0}", duration.TotalMilliseconds),
                    command.Parameters.FormatParameters(ShouldLogParameterValues(diagnostics, command)),
                    command.CommandType,
                    command.CommandTimeout,
                    Environment.NewLine,
                    command.CommandText.TrimEnd());
            }

            **if (diagnostics.DiagnosticSource.IsEnabled(definition.EventId.Name))**
            {
                diagnostics.DiagnosticSource.Write(
                    definition.EventId.Name,
                    new CommandExecutedEventData(
                        definition,
                        CommandExecuted,
                        command,
                        executeMethod,
                        commandId,
                        connectionId,
                        methodResult,
                        async,
                        ShouldLogParameterValues(diagnostics, command),
                        startTime,
                        duration));
            }
        }
We are calling commandexecuted method and as one of argument passing methodResult (DataReader)..
I suppose that second if block that is: if(diagnostics.DiagnosticSource.IsEnabled(definition.EventId.Name))
......
......

Should print methodResult as well, But in our case it's not even entering inside second if block. For trial purpose I tried disabling it then in write(.. , ..) method of DiagnosticListner :
public override void Write(string name, object value)
        {
            for (DiagnosticSubscription curSubscription = _subscriptions; curSubscription != null; curSubscription = curSubscription.Next)
                curSubscription.Observer.OnNext(new KeyValuePair<string, object>(name, value));
        }

_subscriptions contains null in our case. 
My question is- Do we need to add some configuration to capture methodResult(DataReader)
like we used EnableSensitiveDataLogging() to capture value of OUT parameter ?

What we are missing here..

**Comment by ajcvickers** [comment]
@archanasoni Logging a data reader makes no sense unless you mean to iterate the results and log those, but obviously we can't do that. Can you post an example of the kind of output you would expect if this was logged?

**Comment by archanasoni** [comment]
@ajcvickers , here is basic DataReader value which we have to log, this is output when we run DSNUTIL sp:
soft.EntityFrameworkCore.Database.Command[35029]
      Output of Reorg Command: 1ms
1	1DSNU000I    238 06:42:16.33 DSNUGUTC - OUTPUT START FOR UTILITY, UTILID = UTILITYID 
2	 DSNU1045I   238 06:42:16.34 DSNUGTIS - PROCESSING SYSIN AS UNICODE UTF-8 
3	0DSNU050I    238 06:42:16.34 DSNUGUTC -  TEMPLATE EFCOPY DISP(NEW, DELETE, CATLG) 
4	 DSN=DSNNAME
5	 DSNU1035I   238 06:42:16.34 DSNUJTDR - TEMPLATE STATEMENT PROCESSED SUCCESSFULLY 
6	0DSNU050I    238 06:42:16.34 DSNUGUTC -  TEMPLATE EFSYSREC UNIT(SYSDA) DISP=(MOD, DELETE, CATLG) 
7	 DSN=DSNNAME
8	 DSNU1035I   238 06:42:16.34 DSNUJTDR - TEMPLATE STATEMENT PROCESSED SUCCESSFULLY 
9	0DSNU050I    238 06:42:16.35 DSNUGUTC -  REORG TABLESPACE TSNAME FORCE ALL SHRLEVEL CHANGE COPYDDN(EFCOPY) 
10	 UNLDDN EFSYSREC SCOPE PENDING
11	 DSNU1155I ]Q7C2 238 06:42:16.52 DSNURFIT - AUXILIARY TABLESPACE TSNAME WILL BE REORGANIZED IN PARALLEL WITH
12	 BASE TABLESPACE
............
...........

**Comment by ajcvickers** [comment]
@archanasoni We have discussed this as a team and we're still struggling to understand what it is you are actually asking for. Would it maybe be possible for you to submit a PR showing what changes you would like? It might allow us to get past this communication gap.

**Comment by archanasoni** [comment]
@ajcvickers I really dont get what is not clear here.. But before answering anything now I've another question:
To log executed command we have method which takes methodResult as one of argument :
public static void CommandExecuted(
            [NotNull] this IDiagnosticsLogger<DbLoggerCategory.Database.Command> diagnostics,
            [NotNull] DbCommand command,
            DbCommandMethod executeMethod,
            Guid commandId,
            Guid connectionId,
            **[CanBeNull] object methodResult,**
            bool async,
            DateTimeOffset startTime,
            TimeSpan duration)


what is the purpose of this argument ?

**Comment by ajcvickers** [comment]
@archanasoni It's used for interception.

**Comment by archanasoni** [comment]
@ajcvickers  :) what is the end result of it ? I mean methodResult will contain what kind of data ? will it print that data ?

**Comment by ajcvickers** [comment]
@archanasoni The `CommandReaderExecuted` (in 3.0; concepts are similar in 2.2) method follows a standard pattern in EF Core as an entry point to create a variety of logging/diagnostics events after a call has been made to `DbCommand.ExecuteReader`. The type of "events" are:
* A log message sent to an ASP.NET-style `ILogger`
* A diagnostic message sent to a .NET `DiagnosticListener`
* A database interception hook defined on `IDbCommandInterceptor`

The method accepts various state and uses it differently depending on the type of event being generated:
* Both interception and `DiagnosticListener` get a `CommandCreatedEventData` object which contains references to the actual runtime objects being used for command execution. This event data contains the `methodResult`, so this can be examined and used as needed in either a `DiagnosticListener` or `IDbComandInterceptor` implementation.
* `ILogger` gets instead a formatted log message suitable for directly printing/saving.

In addition, `IDbCommandInterceptor` gets the `methodResult` separately because interception can change it to some other object and EF will then continue with that result instead.

All of this happens before any results have been read--that is, the data reader has not been enumerated. We don't print any value out from this data reader in the log message since most data reader implementations are just vehicles for carrying the results (which have not yet been read) and don't inherently have anything interesting to log, other than the results, which have not yet been read, and typically can't be logged without reading them. We certainly would not read the results to log them here since that would essentially mean double enumerating, which would be very slow, among other issues.

So there shouldn't be any issue using `methodResult` in a `DiagnosticListener` or `IDatabaseInterceptor`, if that's what you want to do. And it's by-design that we don't include it in the string sent to `ILogger`.

**Comment by archanasoni** [comment]
@ajcvickers , thanks for the detailed info, as per our requirement we have to print results. As it takes methodResult as an argument so just had a thought that in some configuration or condition result will be printed. But it does not..
