### ISSUE TITLE
Microsoft.EntityFrameworkCore.Internal.ReferenceEqualityComparer is not marked as serializable

### ISSUE THREAD

**Issue by ganaware** [dotnet/efcore#17369]
When I serialized entities that have one-to-many relationship by BinarySerializer, an SerializationException was raised. It said that "Type 'Microsoft.EntityFrameworkCore.Internal.ReferenceEqualityComparer' in Assembly 'Microsoft.EntityFrameworkCore, Version=2.2.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable."

For example:
```csharp
[Serializable]
public class Book {
    public int Id { get; set; }
    public ICollection<Page> Pages { get; set; }
}

[Serializable]
public class Page {
    public int Id { get; set; }
    public int BookId { get; set; }
    public Book Book { get; set; }
}
```
After loading from DB, the Book.Pages is initialized to a HashSet&lt;Page&gt; instance that has a Microsoft.EntityFrameworkCore.Internal.ReferenceEqualityComparer.Instance as a comparer.

The serialization of Book was legal on EFCode 2.1.
Bow now, it is illigal.
The Microsoft.EntityFrameworkCore.Internal.ReferenceEqualityComparer was introduced from 2.2.0 (cf. #12984)

Can you change ReferenceEqualityComparer to be serializable?
Or should I give up using BinarySerializer and find another way such as JsonConvert.Serialize() ?

### Further technical details
EF Core version: 2.2.6
Database Provider: MySqlConnector 0.49.3
Operating system: Windows 7
IDE: Visual Studio Professional 2017 15.8.7

**Comment by ganaware** [comment]
Initializing the collections explicitly is a good solution.  Thank you.

**Comment by KDone108** [comment]
> Initializing the collections explicitly is a good solution. Thank you.

hello, can  you  serialize with BinarySerializer  after  Initializing the collections explicitly

**Comment by ganaware** [comment]
> @ganaware hello, can you serialize with BinarySerializer after Initializing the collections explicitly

@KDone108 yes I can.
See my test project: https://github.com/ganaware/TestEFCoreBinarySerializer

**Comment by ole1986** [comment]
I am having several nested collection. So how and especially why should I initialize them first?

**Comment by KDone108** [comment]
> > @ganaware hello, can you serialize with BinarySerializer after Initializing the collections explicitly
> 
> @KDone108 yes I can.
> See my test project: https://github.com/ganaware/TestEFCoreBinarySerializer

thanks, I understood the Explicit initialization error to be Explicit loading

**Comment by Aleksej-Shherbak** [comment]
I had approximately the same issue, but with .NET Core 3.1. The same complaint from EF about 'ReferenceEqualityComparer'. I don't know will it useful for somebody, but I have solved it with the help of calling `AsNoTracking()`

**Comment by ajcvickers** [comment]
See #29428.
