### ISSUE TITLE
Wrongly configured inheritance does not generate warning but generates wrong SQL

### ISSUE THREAD

**Issue by Xayton** [dotnet/efcore#17394]
I have a few entities that use inheritance (TPH) and I noticed that, if you make a small mistake when configuring navigation properties, EF Core will generate wrong SQL, instead of throwing an error or warning at runtime.

```c#
class MyContext : DbContext
{
	public DbSet<MedicalRecord> MedicalRecords { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Animal>()
			.HasDiscriminator(e => e.Type)
			.HasValue<Cat>(10)
			.HasValue<Lion>(20);
			
		modelBuilder.Entity<MedicalRecord>()
			.HasOne(mr => mr.Cat).WithMany(e => e.MedicalRecords)
			.HasForeignKey(mr => mr.CatId);
	}
}

public abstract class Animal
{
	public int Id { get; set; }
	public int Type { get; set; }
}

public class Cat : Animal
{
	public ICollection<MedicalRecord> MedicalRecords { get; set; }
}

public class Lion : Animal {}

public class MedicalRecord
{
	public int Id { get; set; }
	
	// Medical records are related to cats (not lions).
	public int CatId { get; set; }
	public Cat Cat { get; set; }
}
```
### Working case
The code above works correctly, and if I try to get all the medical records, including for each one the "Cat", it generates the correct SQL:
```c#
_context.MedicalRecords.Include(mr => mr.Cat).ToList();
```
```sql
SELECT mr."Id", mr."CatId", "mr.Cat"."Id", "mr.Cat"."Type"
FROM "MedicalRecords" AS mr
INNER JOIN "Animal" AS "mr.Cat" ON mr."CatId" = "mr.Cat"."Id"
WHERE "mr.Cat"."Type" = 10
```
### Wrong case
The problem happens if the inverse navigation property `MedicalRecords` is moved from the `Cat` class to the `Animal` base class. This is clearly wrong, but EF Core does not generate any warning or error and instead it generates wrong SQL:
```sql
SELECT mr."Id", mr."CatId", mr."LionId", "mr.Cat"."Id", "mr.Cat"."Type"
FROM "MedicalRecords" AS mr
INNER JOIN "Animal" AS "mr.Cat" ON mr."CatId" = "mr.Cat"."Id"
WHERE "mr.Cat"."Type" = 10
```
The column `LionId` does not exist.

### Expected behaviour
I would expect EF Core to generate a runtime exception and not generate wrong SQL.

While in this example it might be easy to spot the cause of the problem, in real cases it could be way harder, particularly if the inverse navigation property was added at a later time.

### Further technical details
EF Core version: 2.2.4
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL

**Comment by smitpatel** [comment]
The generated SQL is "invalid" since column `LionId` does not exist. But unless running the query EF has no way of knowing that `LionId` does not exist in database. The configuration does not seem necessarily wrong to generate warning.
