### ISSUE TITLE
Pluralization hook for DbContext Scaffolding no longer works in EF Core 3 preview 8

### ISSUE THREAD

**Issue by aquacat123** [dotnet/efcore#17401]
In EF Core 2.2.6  I am able to use the following code to implement pluralization when running the Scaffold-DbContext command.  When I upgraded to EF Core 3 preview 8 the Pluralization hook for DbContext Scaffolding stopped working.  My solution still builds and the scaffold command still runs but pluralization is no longer implemented when using IDesignTimeServices to implement pluralization.  This has really caused a problem for me because the new scaffolded classes break the build (due to lack of pluralization).  Since i cant build i cannot attempt to run Scaffold-DbContext again (cant run unless the solution builds).  I have reverted back to EF Core 2.2.6, awaiting a fix for this.

``` csharp
public class CustomPluralizer : IPluralizer
{
    public string Pluralize(string name)
    {
        string result = Inflector.Inflector.Pluralize(name) ?? name;
 
        if (result.EndsWith("Status"))
        {
            result += "es";
        }
        if (result.EndsWith("Campus"))
        {
            result = result.Replace("Campus", "Campuses");
        }
 
        return result;
    }
    public string Singularize(string name)
    {
        string result = Inflector.Inflector.Singularize(name) ?? name;
 
        if (result.EndsWith("Statu"))
        {
            result += "s";
        }
        if (result.EndsWith("Campu"))
        {
            result = result.Replace("Campu", "Campus");
        }
 
        return result;
    }
}
```
 
``` csharp
public class CustomDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection services)
    {
        services.AddSingleton<IPluralizer, CustomPluralizer>();
    }
}
```

**Comment by bricelam** [comment]
Can you share the output of Scaffold-DbContext with `-Verbose`?

**Comment by aquacat123** [comment]
Sure, do you want me to run Scaffold-DbContext with -Verbose using EF Core 3 preview 8?

**Comment by bricelam** [comment]
Yeah, it might have clues about why your pluralizer isn’t getting picked up.

**Comment by aquacat123** [comment]
I setup a sample project to test with and emailed it to you.  Using the sample project everything works fine with 2.2.6 but when i update it to EF Core 3 preview 8 now it says that IPluralizer is unrecognized.  Reverting back to 2.2.6 resolves the problem.

**Comment by ErikEJ** [comment]
Please share your csproj file, I suspect this could be caused by changes to the EF Core.Design package.

**Comment by ErikEJ** [comment]
@bricelam Is this a good change? I have now seen several being "hit" by this, including myself with EF Core Power Tools

**Comment by ErikEJ** [comment]
Maybe publish 2 packages?

**Comment by ErikEJ** [comment]
MS.EFCore.Design.DoNotRefrerenceFromProductCode :smile:

**Comment by hamedhajiloo** [comment]
how to use of this?
