### ISSUE TITLE
Select(x=>**) translation question

### ISSUE THREAD

**Issue by changhuixu** [dotnet/efcore#17403]
I have a quick question about the execution of EntityFramework Select() method.

I found that the translated sql queries are different for ` _dbContext.MyEntity.Select(x => new DTO(x))` and `_dbContext.MyEntity.Select(x => new DTO{ object property assignments})`.
The first one pulls all columns of the entity, while the second one only selects the fields I want.

Is there any particular reason?

Thank you,

### Steps to reproduce
```c#
public class Author
    {
        public int Id { get; protected set; }
        public string FirstName { get; protected set; }
        public string LastName { get; protected set; }
        public AuthorMembership AuthorMembership { get; protected set; }
        protected Author()
        {
            AuthorMembership = AuthorMembership.Bronze;
        }

        public Author(CreateAuthorCommand cmd) : this()
        {
            FirstName = cmd.FirstName;
            LastName = cmd.LastName;
        }
    }
public class AuthorViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public AuthorViewModel()
        {
        }
        public AuthorViewModel(Author author)
        {
            Id = author.Id;
            FirstName = author.FirstName;
            LastName = author.LastName;
        }
    }

// The below two queries translate into different SQL queries.
return await _dbContext.Authors.Select(x => new AuthorViewModel(x)).ToListAsync();
return await _dbContext.Authors.Select(x => new AuthorViewModel 
{
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName
}).ToListAsync();
```
Translated SQL queries:
```sql
--  _dbContext.Authors.Select(x => new AuthorViewModel(x))
Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [x].[Id], [x].[AuthorMembership], [x].[FirstName], [x].[LastName]
FROM [Authors] AS [x]

--  _dbContext.Authors.Select(x => new AuthorViewModel { Id = x.Id, ...})
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [x].[Id], [x].[FirstName], [x].[LastName]
FROM [Authors] AS [x]
```
### Further technical details
EF Core version: Entity Framework Core 2.2.6-servicing-10079
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win10

**Comment by smitpatel** [comment]
AuthorViewModel constructor is opaque in expression tree. We do not know what exactly that constructor do.
In first one you are asking us for Author so we get all the values from database and create Author object and pass it the ctor you indicated and let it do it's magic.
In second case you doing member initialization syntax, which will call parameter-less ctor and assign properties. In this case we can see what are the member assignments are in the expression tree. Hence we only fetch the columns which we need to do the assignments and generate final object.

**Comment by changhuixu** [comment]
Make sense. Thank you.
