### ISSUE TITLE
Sqlite: Throw on blocked translation of aggregate

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17449]
Currently it returns null.
It should rather throw exception with why aggregate was blocked. Aggregate operations are never going to be evaluated on client even if in projection.

**Comment by ajcvickers** [comment]
From triage: also, we should change the exception message for the cases specific to SQLite to be more specific to the SQLite problem. Also check the `OrderBy` case.

**Comment by smitpatel** [comment]
OrderBy case already shows message
> SQLite cannot order by expressions of type '{type}'. Convert the values to a supported type or use LINQ to Objects to order the results.
