### ISSUE TITLE
Translate `as` in where clause

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/efcore#17475]
I have two class:

```
public abstract class Conversation
{
    public int Id { get; set; }
}

public class PrivateConversation : Conversation
{
    public ICollection<User> Users { get; set; }
}
```

In DbContext, there are DbSets:

```csharp
public DbSet<Conversation> Conversations { get; set; }
public DbSet<PrivateConversation> PrivateConversations { get; set; }
public DbSet<User> Users { get; set; }
```

Which generates two tables: `Conversations` and `Users`.

> PrivateConversations are saved in table `Conversations`

Now an error occurred with query:

```

// For some reason, I can only query `db.Conversations`, can not access `db.PrivateConversations`
var conversations = db.Conversations
  .Include(t => (t as PrivateConversation).Users)
  .Where(t => t is PrivateConversation)
  .Where(t => (t as PrivateConversation).Users.Any())
  .ToList();
```

Told me that in `Users.Any()`, `Users` is null.

I am very confused. How can I query all private conversations with user in it?

### Additional info:

packages I usesd:

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.6" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SQLServer" Version="2.2.6" />
```

runtime: .NET Core 2.2

```
<OutputType>Exe</OutputType>
<TargetFramework>netcoreapp2.2</TargetFramework>
```

**Comment by ajcvickers** [comment]
@Anduin2017 EF translates ` .Where(t => ((PrivateConversation)t)...` but not ` .Where(t => (t as PrivateConversation)...`.

**Comment by Anduin2017** [comment]
Thanks! That really solves!

**Comment by Anduin2017** [comment]
Ok. I gotta be really happy if you can fix this and translate the `as` grammar.

**Comment by SARAVANA1501** [comment]
Can you tell me where I can add this new grammar?

**Comment by ajcvickers** [comment]
@smitpatel Since you added `good-first-issue` here can you point @SARAVANA1501 in the right direction to submit a PR for this?

**Comment by smitpatel** [comment]
While code is similar in various place, we can start with one location and update at all location once the structure is define.

https://github.com/aspnet/EntityFrameworkCore/blob/b7df776b0e1b2d94da48b0471c657fda8dbe8f9b/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs#L90-L102

Above code basically unwrap a convert node and gives the converted type. Similar to above processing it needs to identify TypeAsOperation and then unwrap it to identify converted type and innerExpression. It should be added as extension method so all places can easily utilize it. So it goes this way.

| Expression | Inner | ConvertedType |
| ------------- | ------------- | ---------- |
| `a.Property`  | a  | `null` |
| `((T)a).Property`  | a  | `T` |
| `(a as T).Property`  | a  | `T` |

**Comment by smitpatel** [comment]
This is already fixed in master branch in https://github.com/dotnet/efcore/pull/19377
