### ISSUE TITLE
Add logging to query

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17498]
- Log for ignored include.
- Log for including navigation

**Comment by ajcvickers** [comment]
@smitpatel to point to the places where we need to log.

**Comment by smitpatel** [comment]
Also consider https://github.com/aspnet/EntityFrameworkCore/issues/12662

**Comment by smitpatel** [comment]
- Compiling expression tree
- RowLimitingOperationWithoutOrderByWarning
- FirstWithoutOrderByAndFilterWarning
- Optimized expression tree
- navigation included
- include ignored
- Query execution plan, need to print proper plan

**Comment by ajcvickers** [comment]
Note from team discussion: make sure to add the no-ordering warnings back. They don't need to be provider-specific. See #19331

**Comment by bricelam** [comment]
Note from API Review: Re-use the previous EventIds as much as possible
