### ISSUE TITLE
Link conceptual documentation from API docs

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [dotnet/efcore#17508]
It would be good to get some usage examples here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a68bee-6e78-b2b3-bacc-b3ef6873252b
* Version Independent ID: cd5b3292-61d7-c3f8-09aa-ce974a0b9f32
* Content: [EF.CompileAsyncQuery Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef.compileasyncquery?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by bricelam** [comment]
To put it in the See Also section:
``` csharp
/// <seealso href="https://docs.microsoft.com/ef/core/get-started/">Getting Started</seealso>
```
For inline links:
``` csharp
/// <summary>
///     Enables mapping <see href="https://docs.microsoft.com/ef/core/modeling/spatial">spatial types</see> in your model.
/// </summary>
```

**Comment by ajcvickers** [comment]
From #17512:
* HasFilter
* CreateIndex

**Comment by roji** [comment]
Possibly link to [the TrackGraph conceptual docs](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#trackgraph) from the relevant methods in EntityEntryGraphNode.cs (see https://github.com/dotnet/efcore/pull/22626#discussion_r491741958)
