### ISSUE TITLE
spatial problem with coordinates being backwards

### ISSUE THREAD

**Issue by MolallaComm** [dotnet/efcore#17510]
Using latest 2.2.x SQL Server 2012, I'm seeing a problem where the coordinates I see on the code side are backwards from reality.  My POCO:
``` csharp
using MolallaFM.Data.Common;
using NetTopologySuite.Geometries;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MolallaFM.Data.Geo
{
    public class M4Structure : EquatableObject<M4Structure>
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int StructureID { get; set; }
        public Geometry SHAPE { get; set; }
        [MaxLength(255)]
        public string Address { get; set; }
        [MaxLength(255)]
        public string PairNumber { get; set; }
        [MaxLength(50)]
        public string Splitter { get; set; }
        public int? LineageMDF { get; set; }
        public int? LocationID { get; set; }
    }
}
```
If I run "SELECT StructureID, SHAPE.STAsText() AS Text from M4Structure where StructureID=4" on the SQL server, i get:
```
4	POINT (7659643.34 577186.65)
```
However, in my code, when doing:
``` csharp
var structure = ctx.M4Structure.Find(4)
```
if I look at "structure" in the debugger, the SHAPE property prints out as 
```
POINT (577186.65 7659643.34)
```
This doesn't seem right???

FWIW, I really like EF Core.  We have a large EF6 project we are migrating, and I've been pleasantly surprised at how solid it seems and how much faster it is!

**Comment by bricelam** [comment]
Are you trying to map to `geometry` columns? (the default is `geography`)
``` csharp
modelBuilder.Entity<M4Structure>().Property(s => s.SHAPE)
    .HasColumnType("geometry");
```

**Comment by MolallaComm** [comment]
Thanks - that fixed it - and rereading the documentation, i see that is mentioned, although it might be worth breaking it into its own section "Geography vs Geometry" rather than "SQL Server" since I assume it works similarly in Postgres and others that support both types of columns and highlighting that setting the type in your model is required if you are using Geometry.  It might also be good just to throw an exception saying as much if you are reading from a non geography column in the DB that is mapped by default to a geography column in the model rather than pull incorrect data.  It might also be worth discussing changing the default behavior to Geometry instead of Geography also - particularly since the NTS type is called Geometry (and NTS doesn't have a Geography type) but I guess that depends on the preponderance of customers that use one vs. the other.

Just my two cents - thanks again.

**Comment by MolallaComm** [comment]
FWIW, I also notice that before I added the HasColumnType("geometry") when I run my code on using Npgsql it creates a geometry column by default, not a geography column so that is an inconsistency between providers that might also be mentioned in the docs.

**Comment by ajcvickers** [comment]
Filed: https://github.com/aspnet/EntityFramework.Docs/issues/1683
