### ISSUE TITLE
If Have DbDataReader  Can't Get Return/output value

### ISSUE THREAD

**Issue by Honjoy** [dotnet/efcore#17520]
using var cmd = _act.Database.GetDbConnection().CreateCommand();
      cmd.CommandText = "_Test_StoreProce";
      cmd.CommandType = CommandType.StoredProcedure;

      var err = cmd.CreateParameter();
      err.ParameterName = "error";
      err.DbType = DbType.String;
      err.Size = 127;
      err.Direction = ParameterDirection.Output;
      cmd.Parameters.Add(err);
      var ret = cmd.CreateParameter();
      ret.ParameterName = "RC";
      ret.DbType = DbType.Int32;
      ret.Direction = ParameterDirection.ReturnValue;
      cmd.Parameters.Add(ret);

      await cmd.Connection.OpenAsync();
      using var ddr = await cmd.ExecuteReaderAsync();
      if(cmd.Parameters["RC"].Value is int s && s != 0)
        return new { s,m = cmd.Parameters["error"].Value };

**Comment by ajcvickers** [comment]
@Honjoy This isn't really an EF connections (since EF is only used to obtain a connection) but assuming this is using SQL Server, then the `DataReader` needs to be consumed before out parameters will be set. By "consume", I mean read all rows from it and close the reader.

**Comment by Honjoy** [comment]
sorry, not this mean.
In ADO.NET, I can get DbReader and the output parameter/return parameter, if you close datareader the parameter always can read it. but in ef core connection I can't read parameter if have datareader.
