### ISSUE TITLE
Breaking changes ef core 3.0.0-preview8.19405.11

### ISSUE THREAD

**Issue by Diaskhan** [dotnet/efcore#17522]
Trying to port to new ef core 3.0 preview

And i think there have some breakings changes!

1.
```
var migrationServices = new ServiceCollection()
                    .AddDbContextDesignTimeServices(baseCtx)
```
**there no AddDbContextDesignTimeServices in new version**

2.
```
var test1Model = test1ModelBuilder.GetInfrastructure().Metadata;
                test1Model.Validate();
```
**there no vaildate method**

3.          var entityTypes = CurrentContext.Model.GetEntityTypes().Select(t =>
                new {
                    ClrType = t.ClrType,
                    TableName=t.Name //().TableName
                    }
                ).ToList();
**there no TableName property**

What U suggest to do to port to new verison ?

### Further technical details
[error log.txt](https://github.com/aspnet/EntityFrameworkCore/files/3559732/error.log.txt)
[EntityUtills.txt](https://github.com/aspnet/EntityFrameworkCore/files/3559733/EntityUtills.txt)

EF Core version: Microsoft.EntityFrameworkCore.Design 3.0.0-preview8.19405.11
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 10
IDE: (e.g. Visual Studio 2019)

**Comment by bricelam** [comment]
You need to [explicitly reference EFCore.Design](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#microsoftentityframeworkcoredesign-is-now-a-developmentdependency-package) now.

**Comment by ajcvickers** [comment]
@Diaskhan Is your intention to let us know about breaking changes that aren't [documented](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes)? If not, it might be a good idea to scan the [announcements](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-8-and-entity-framework-6-3-preview-8/)/[status updates](https://github.com/aspnet/EntityFrameworkCore/issues/15403) to understand what is happening in 3.0.

**Comment by ajcvickers** [comment]
Note from triage: nothing here not already covered.

**Comment by Diaskhan** [comment]
I will try to do. If not gonna work give u a feedback !
