### ISSUE TITLE
InMemory: Function argument becoming nullable due to optional navigation

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17540]

**Comment by smitpatel** [comment]
Could likely be working already

**Comment by maumar** [comment]
nope, still broken

**Comment by smitpatel** [comment]
What is the error? Query may not always work if required things come null, we just need to fail with nullable object must have value error.

**Comment by smitpatel** [comment]
`Substring` 2nd parameter length cannot take null values. Query is supposed to throw error at runtime.
