### ISSUE TITLE
[Cosmos] How to update Cosmos DB Authkey at runtime?

### ISSUE THREAD

**Issue by NetGH** [dotnet/efcore#17547]
We know we can setup DbContext in DI, however, we would like to re-generate cosmos db key every x month. and we don't want any downtime.

We tried to re-create ServiceCollection, however, we see the error: 

'Microsoft.EntityFrameworkCore.Infrastructure.ManyServiceProvidersCreatedWarning: More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling UseLoggerFactory passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. Consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.ManyServiceProvidersCreatedWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

============== below is how we DI =============
            var buildServiceProvider = new ServiceCollection()
                .AddDbContextPool<CosmosDbContext>(dbContextOptionsBuilder =>
                {
                    dbContextOptionsBuilder
                        .UseCosmos(_connectionOptions.Value.ServiceEndpoint,
                            authKeyOrResourceToken,
                            _dbCollectionOptions.Value.Database
                        )
                        .UseMemoryCache(entityMemoryCache)
                }).BuildServiceProvider();

**Comment by AndriySvyryd** [comment]
@NetGH If you are getting that after about 20 times you changed authkey then it's expected and you can add configuration to ignore this warning.
Otherwise you need to make sure that a new service collection is created only if the authkey is changed.

**Comment by NetGH** [comment]
so create new service collection to create new DbContexts, there would be no memory leak right? or do we need to do any other operations to clear/dispose sth.

**Comment by AndriySvyryd** [comment]
As long as you don't keep references to the old serviceProvider it should be ok.
