### ISSUE TITLE
Document LINQ extension methods

### ISSUE THREAD

**Issue by Vivelin** [dotnet/efcore#17564]
The summary of `SingleOrDefaultAsync` states that an exception is thrown when there is more than one element in the sequence; however, it does not state the type of exception that is thrown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d5a5fa-c203-fef3-e2b6-a51bd4f2a175
* Version Independent ID: 294bcecd-d216-9e7c-85f2-09d375248627
* Content: [EntityFrameworkQueryableExtensions.SingleOrDefaultAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.singleordefaultasync?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Note from triage: For LINQ methods, copy the docs from corefx. See also #17692

**Comment by roji** [comment]
Or documentation for the async LINQ operators is already identical to the corefx docs: compare [ours](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.singleordefaultasync?view=efcore-2.1#Microsoft_EntityFrameworkCore_EntityFrameworkQueryableExtensions_SingleOrDefaultAsync__1_System_Linq_IQueryable___0__System_Threading_CancellationToken_) to [theirs](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.singleordefault?view=netcore-3.1#System_Linq_Queryable_SingleOrDefault__1_System_Linq_IQueryable___0__). Exceptions are properly documented by type in the documentation exception section, it seems quite sufficient to me.
