### ISSUE TITLE
Add-migration throws System.MissingMethodException

### ISSUE THREAD

**Issue by rgomez90** [dotnet/efcore#17561]
### Problem

When trying to use "add-migration" I get the error "The constructor for type "Microsoft.EntityFrameworkCore.Design.OperationExecutor" was not found".

### Exception & Stack trace
```
Exception message: 
The constructor for type "Microsoft.EntityFrameworkCore.Design.OperationExecutor" was not found.

Stack trace:
System.MissingMethodException: Der Konstruktor für den Typ "Microsoft.EntityFrameworkCore.Design.OperationExecutor" wurde nicht gefunden.
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   bei Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   bei Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
   bei Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   bei Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```

### Steps to reproduce

1. Create WPF Project .NET Framework 4.7.2
2. Install Microsoft.EntityFrameworkCore.Tools 3.0.0-preview6.19304.10
3. Create .Net Standard 2.0 and install  Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview6.19304.10
4. Add following code to .Net Standard project (Code is from Microsoft Docs => [Link](https://docs.microsoft.com/en-us/ef/core/get-started/full-dotnet/new-db))

```csharp
 public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
```
5. Set WPF project as StartUp project
6. Try to run "add-migration Initial" from package manager console using .Net Standard project as Default project.

I also created a repo with the code, in case you want to test it. [https://github.com/rgomez90/TestIssueEfCoreOperationExecutor](https://github.com/rgomez90/TestIssueEfCoreOperationExecutor)

I met this issue in another project I am working at. To be sure it was not a project related issue, I created a project from scratch like explained above, and the issue still appears.

### Further technical details
EF Core version: 3.0.0-preview6.19304.10 (last version supporting .Net Standard 2.0)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer ( 3.0.0-preview6.19304.10)
Operating system: Windows 10 Pro & Windows 10 Education
IDE: Visual Studio 2019 16.3.0 Preview 2.0

**Comment by bricelam** [comment]
Does is work using EF Core 2.2.6?

**Comment by rgomez90** [comment]
As far as I've tested it works, and with all versions until 3.0.0-preview4, it works too. 

With preview4 to preview6 it does not work.

With preview8 and .Net Standard 2.1 it worked. I haven't tested preview7.

**Comment by ajcvickers** [comment]
@rgomez90 EF Core 3.0 doesn't support .NET Standard 2.0.

**Comment by rgomez90** [comment]
But the first preview packages (until preview7) work with it...or I am wrong?

**Comment by ajcvickers** [comment]
@rgomez90 Yes...but that's an out-dated preview. I wouldn't expect it to work with anything else.

**Comment by bricelam** [comment]
In other words, use EF Core 2.2 if you need to support .NET Framework. Preview releases aren't supported, and the next supported version (3.0) isn't compatible with .NET Framework.

**Comment by rgomez90** [comment]
Ok.
Thank you.
