### ISSUE TITLE
.Include works differently

### ISSUE THREAD

**Issue by BertusVanZyl** [dotnet/efcore#17579]
When I am working against a real MS SQL Server instance, I have to use .Include to load navigation properties etc. But when working with the InMemory instance, all navigation properties are loaded, even if the .Include is not there at all.

Is there a setting somewhere where I can force the InMemory database to only load data if the .Include is present? The way it currently behaves could potentially miss certain bugs (especially if the bug is the missing .Include in the first place.)

If there is no such setting, the docs should mention this difference along with the other warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c95e5c7e-882f-76f7-5301-2a5d1ede39d3
* Version Independent ID: 8754aa99-67a7-98ac-a51e-0ba995f96414
* Content: [Testing with InMemory - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#feedback)
* Content Source: [entity-framework/core/miscellaneous/testing/in-memory.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/in-memory.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@FrikkinLazer Symptoms like this usually indicate that the same context instance is being used to both initialize data and then query. Instead, tests should match how the context instance is being used by th application, which in cases like this is usually a different context instance for query than was used to store the data.

**Comment by FrikkinLazer** [comment]
Ok so the in memory database does NOT load data, unless the .Include is there, the same way a normal SQL provider does?

**Comment by ajcvickers** [comment]
@FrikkinLazer Correct.
