### ISSUE TITLE
Execution strategy for migration

### ISSUE THREAD

**Issue by ariellourenco** [dotnet/efcore#17578]
Dear all,

I am wondering if the SQL execution strategy specified when configuring the options for the context also covers the Migrate command when it takes place as part of the chain of events of the IWebHost as in the code sample in this [discussion](https://github.com/aspnet/EntityFrameworkCore/issues/9033#issuecomment-317063370)

**Comment by bricelam** [comment]
But we could retry the ones that are in a transaction and do something fancy with Down operations or idempotent DDL statements (IF NOT EXISTS) to recover from failures outside of a transaction.

**Comment by escalonn** [comment]
I'm just looking for a built-in way to retry the connection itself, not any of the operations within it.

**Comment by AndriySvyryd** [comment]
When retrying without a transaction we can start from the last command that succeeded.

**Comment by roji** [comment]
Reopening to track reviewing my comments on #34206 (accidentally approved with auto-merge on).
