### ISSUE TITLE
Test: Create a TestBase which allows inserting custom model to run queries

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17588]
We need to make QueryBugsTest provider agnostic so we can get better coverage. This is important since most of the model we add here are customer models.

**Comment by smitpatel** [comment]
Adding few more points, which are related and should be considered.
QueryBugsTest creates database only once but populate it with tables and data for each test.
Context different test scenario
- Separate bounderies
- Creates only required tables and seed them
- Easy to see data and test together

Single context for all test
- We can go into normal flow of other test classes by having a model which just add more entityTypes in future
- Database is initialized only once and reused

**Comment by AndriySvyryd** [comment]
Tests the require MARS should be moved out and marked with `SqlServerCondition.SupportsMARS`
