### ISSUE TITLE
Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#17585]
### If you believe you have an issue that affects the security of the platform please do NOT create an issue and instead email your issue details to secure@microsoft.com. Your report may be eligible for our [bug bounty](https://technet.microsoft.com/en-us/mt764065.aspx) but ONLY if it is reported through email.

I am trying to insert 19064 rows into mysql database using INSERT INTO COMMAND string generated. I can insert 1150 but over that number is breaking. with the following error
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Stack trace:
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RawSqlCommandBuilder.Build(String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, Object[] parameters)
   at Test.InfrastructureLayer.EntityFramework.Repositories.OpenTradeRepository.BulkToMySQL(IEnumerable`1 openTrades)
   at Test.ApplicationLayer.ClientService.<ProcessOpenTrade>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Test.ApplicationLayer.ClientService.<Start>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Test.ApplicationLayer.Reports.ExecutionReportService.<GetReport>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.WPF.UserControls.ReportsUserControl.<>c__DisplayClass15_0.<<LoadExecutionReport>b__0>d.MoveNext() 
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
 context.Database.ExecuteSqlCommand(command);
```

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.2.6
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) Pomelo.EntityFrameworkCore.MySql 2.2.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4) VS 2017 15.9.11

**Comment by pantonis** [comment]
I think I have found what the problem is but I dont know how to fix it.
I am creating the Insert query using string interpolation and the generated query is the following

```INSERT INTO Order (Timestamp`, Id, Amount, Comment)
values 
('2019-08-01 02:00:01.448', 1, 46513, {Test comment})
```
where test comment actual value is the above.

**Comment by smitpatel** [comment]
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by zykindmitry** [comment]
I am facing the same error. 

I generated sql command with the following text which I would like to execute:
insert into public.peripheral_type ("peripheral_type_id", "vendor_id", "name", "parameters", "note", "product_number", "external_id", "code", "max_load", "nom_load", "can_color_print", "can_foto_print", "removed", "complementary_id", "product_catalog_type_id", "can_buy", "row_version") values ('c11695fc-bd54-42e0-a2f9-a66d771da451', 2000091, N'Monitor LCD 24" Beng GL2450 black {1920х1080, 250,1000:1, 5ms,170/160,DVI-D}', N'', N'Monitor LCD 24" Beng GL2450 black {1920х1080, 250,1000:1, 5ms,170/160,DVI-D},  КК - 34101', N'<Empty text>', N'803481', N'', NULL, NULL, NULL, NULL, false, NULL, 'c3f62ca0-0836-4d8a-a78f-36e204e4c988', false, current_date);

And a DbContext

public class PostgreDbContext : DbContext, ICommandExecuter
    {
        private readonly IConfiguration configuration;

        public PostgreDbContext(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public void Execute(string command)
        {
            Database.ExecuteSqlRaw(command);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(configuration.GetConnectionString("pg"));
        }

    }

Execute method fails with the sames exception. 
I assume that  {1920х1080, 250,1000:1, 5ms,170/160,DVI-D} is treated as a query parameter which was not supplied.

**Comment by ajcvickers** [comment]
@zykindmitry Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by zykindmitry** [comment]
Assuming you have local ms sql (or other db) with table "mytable (text nvarchar(250)) as an example". Running the following code causes the exception above.

class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (var db = new MyContext())
                {
                    db.Execute("insert into mytable (text) values (\'some text with { brackets } inside\')");
                }
            }   
            catch(Exception error)
            {
                Console.WriteLine(error.Message);
            }

            Console.ReadLine();
        }
    }

    class MyContext : DbContext
    {
        public MyContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder dbContextOptions)
        {
            dbContextOptions.UseSqlServer("Server=localhost\\SQLEXPRESS01;Database=demo;Trusted_Connection=True;");
        }

        public void Execute(string command)
        {
            Database.ExecuteSqlRaw(command);
        }
    }

**Comment by zykindmitry** [comment]
class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (var db = new MyContext())
                {
                    var commandText = "insert into mytable (text) values (\'some text with {0} brackets\')";
                    db.Execute(commandText);
                }
            }   
            catch(Exception error)
            {
                Console.WriteLine(error.Message);
            }

            Console.ReadLine();
        }
    }

    class MyContext : DbContext
    {
        public MyContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder dbContextOptions)
        {
            dbContextOptions.UseSqlServer("Server=localhost\\SQLEXPRESS01;Database=demo;Trusted_Connection=True;");
        }

        public void Execute(string command)
        {
            Database.ExecuteSqlRaw(command);
        }
    }

**Comment by ajcvickers** [comment]
@zykindmitry That issue is tracked by #13270.
