### ISSUE TITLE
Remove dependency on full DependencyInjection package

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/efcore#1761]
An Interfaces package was recently spun off from the main DI package (see https://github.com/aspnet/DependencyInjection/pull/195). EF should drop its dependency on the full package and take the Interfaces dependency instead. This will require a little bit of refactoring in the `EntityFrameworkServiceCollectionExtensions` class, but shouldn't be anything too bad.

**Comment by ajcvickers** [comment]
Sending back to triage. We have code paths (notably the happy path for not web apps) that fully create the service collection and build a service provider from it. It doesn't look like this can be done using just the interfaces.

We also ActivatorUtilities for creating DbContext instances when AddDbContext is used.
