### ISSUE TITLE
Review Test Coverage

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#17618]
We should analyze our test coverage to identify any major uncovered areas.

**Comment by bricelam** [comment]
Areas missing automated coverage:
- Core
  - Conventions APIs (possibly just inlined)
- Relational
  - Connection resiliency
- SQL Server
  - Full text search
  - SqlServerDbFunctionsExtensions (client-side)
  - SqlServerUdtTypeMapping
- SQLite
  - Spatial
    - Custom SRIDs
    - Custom Dimensions #13767
- Design
  - MigrationsScaffolder
  - RevEng
    - Spatial
- Tools

**Comment by ajcvickers** [comment]
Duplicate of #17018
