### ISSUE TITLE
Generated SQL missing comparison with GUID values

### ISSUE THREAD

**Issue by cokert** [dotnet/efcore#17633]
When executing a query like what's below, EF Core doesn't add the where clause to the SQL sent to the server.  (I guess it's attempting to apply the filter locally after results are returned.) 
 Regular EF does translate this as expected.  See [this SO question/answer](https://stackoverflow.com/questions/57778819/dynamic-ef-linq-query-comparing-guid-uniqueidentifier-values) for details.

```c#
context.TestTables.Where(x => guid1.CompareTo(x.OtherColumn2) == 0)
```

results in (no where clause)

```sql
SELECT [x].[KeyColumn1], [x].[OtherColumn2]
FROM [TestTables] AS [x]
```

As noted in the SO question linked above, I verified that standard EF would generate something along these lines (this is from the LINQPad output from my SO question -- it's not the same code as above, but notice the where clause has a greater than):

```sql
-- Region Parameters
DECLARE @p0 UniqueIdentifier = '09e0073a-be0e-405a-9564-d34056c8e42a'
DECLARE @p1 UniqueIdentifier = 'd3aaaf86-d4e5-4d77-897e-1b36c1100448'
-- EndRegion
SELECT [t0].[col1] AS [Col1], [t0].[col2] AS [Col2]
FROM [test] AS [t0]
WHERE ([t0].[col2] > @p0) AND ([t0].[col1] = @p1)
ORDER BY [t0].[col1]
```

### Steps to reproduce

[This project](https://github.com/cokert/efcore-test/) shows the issue.  It prints the generated SQL using a hack I found [here](https://stackoverflow.com/questions/37527783/get-sql-code-from-an-ef-core-query).  FWIW, I also ran this against SQL Server and verified the printed output matches what makes it to the server using Profiler.

### Further technical details
EF Core version: 2.2.6  
Database Provider: Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Sqlite  
Operating system: Windows 10 Pro 1903  
IDE: VS Code 1.37.1

**Comment by smitpatel** [comment]
Can you try with EF Core 3.0 preview9? It should be translating the where predicate.

**Comment by cokert** [comment]
The produced SQL is odd and could probably use some work, but it looks like it will work.  I'm getting this from SQL Profiler now (EFCore 3 breaks the `ToSql()` hack):

```sql
exec sp_executesql N'SELECT [t].[KeyColumn1], [t].[OtherColumn2]
FROM [TestTables] AS [t]
WHERE (CASE
    WHEN (@__guid1_0 = [t].[OtherColumn2]) AND @__guid1_0 IS NOT NULL THEN 0
    WHEN @__guid1_0 > [t].[OtherColumn2] THEN 1
    WHEN @__guid1_0 < [t].[OtherColumn2] THEN -1
END = 0) AND CASE
    WHEN (@__guid1_0 = [t].[OtherColumn2]) AND @__guid1_0 IS NOT NULL THEN 0
    WHEN @__guid1_0 > [t].[OtherColumn2] THEN 1
    WHEN @__guid1_0 < [t].[OtherColumn2] THEN -1
END IS NOT NULL',N'@__guid1_0 uniqueidentifier',@__guid1_0='E9C95AE5-9516-45AD-AA48-FCD32DB65ED4'
```

**Comment by cokert** [comment]
I should add in a thanks for the quick response! I didn’t expect to see anything on this until tomorrow at the earliest.

**Comment by smitpatel** [comment]
We have plan to make the SQL simpler #16092

**Comment by cokert** [comment]
Oh, word.  Good to hear.
