### ISSUE TITLE
Optional Foreign Key EF Check

### ISSUE THREAD

**Issue by alaatm** [dotnet/efcore#17630]
In pre 3.0.0, if we configure an optional relation, for example:

```
b.HasOne(p => p.Related)
    .WithMany()
    .HasForeignKey(p => p.RelatedId)
    .IsRequired(false);
```

and the `RelatedId` field is of type `int` then we get an exception:

```
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'The foreign key {'RelatedId'} on entity type 'Related' cannot be marked as optional because it does not contain any property of a nullable type. Any foreign key can be marked as required, but only foreign keys with at least one property of a nullable type and which is not part of primary key can be marked as optional.'
```

In 3.0.0 Preview 9, there are no exceptions thrown and EF will go ahead and make the relation required, (RelatedId column in database will be `not null`). I might have missed some release notes if this behavior was changed, but in my opinion, the original behavior with Exceptions seems more correct.

**Comment by AndriySvyryd** [comment]
@alaatm This is by design: https://github.com/aspnet/EntityFrameworkCore/issues/14197

__For triage__: Consider documenting this in https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes

**Comment by ajcvickers** [comment]
Filed https://github.com/aspnet/EntityFramework.Docs/issues/1697
