### ISSUE TITLE
How to implement multiple DB-context with inherited shared base-entities without TPT

### ISSUE THREAD

**Issue by chrfin** [dotnet/efcore#17641]
This is coupled out from #2266:

I also would like to use EF Core, but couldn't because of my applications heavy dependency on TPT.
At the moment I am using ASP.NET MVC 5 and EF 6 and I am more and more eager to port it to ASP.NET Core and EF Core. Starting with 3.0 I will first try to move to ASP.NET Core and EF 6.3, but the next step would be EF Core - so far I think I can't without TPT, but maybe can I?
My application is a CMS with a plugin-system and I have the following (simplified) structure:

CMS.Common
 - CmsBaseContext : DbContext
   - ContentItem
     - Id
     - TypeId
     - Position
     - AccessRights
     - .....

PluginA
 - PluginAContext : CmsBaseContext
   - PluginAItem : ContentItem
     - Title
     - Text

PluginB
 - PluginBContext : CmsBaseContext
   - PluginBItem : ContentItem
     - Title
     - FilePath

PluginC
 - PluginCContext : CmsBaseContext
   - PluginCItem : ContentItem
     - Url

I actually already have some kind of discriminator in the base-table (`TypeId`), which is used for sorting, ordering and such.  
But what about dynamically added inheritance like in my plugins vs. TPH?
Each plugin would add their own columns to the "hierarchiy table", but `PluginA` and `PluginB` will both try to add `Title`?
Is there a way to work around this (without composition)?
Prefix each column with the plugin-name (that is what i currently do with the table names in TPT)? 
Only add columns if the do not already exist, but what about different types?

Any other ideas how to solve this with EF Core and TPH?

Note: With EF 6 I remove the creation of the base-tables from the inherited contexts migrations manually.

**Comment by ajcvickers** [comment]
@chrfin This could work, but I think it depends on how the base class `ContentItem` is used in the EF model. If it is a target of navigation properties, then EF will need to include it in the model, but given what you say about what you do with base tables in EF6, it seems this may work. I wish I could be more concrete, but I think the specifics get important fast. If you try it, please let us know how it goes.
