### ISSUE TITLE
[CosmosDb] Child properties in inheritance hierarchy are not saved to CosmosDB

### ISSUE THREAD

**Issue by NickSevens** [dotnet/efcore#17660]
### Steps to reproduce
I'm having a setup like for example:

```c#
public Context : DbContext {
  public DbSet<Animal> Animals { get; set; }
}

public class Animal {
  public string Color { get; set; }
}

public class Cat : Animal {
  public int Lives { get; set; }
}

public class Dog : Animal {
  public int Puppies { get; set; }
}
```

I am then adding a Cat and a Dog to my collection (`_context.Animals.Add(new Dog() {...});` and `_context.Animals.Add(new Cat() {...});`

However, in the CosmosDb, the properties `Color` and `Lives` are not saved in the JSON document. Is there a way to allow this?

Thanks.

### Further technical details
EF Core version: 3.0.0-preview9.19423.6
Database Provider: Microsoft.EntityFrameworkCore.Cosmos
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by AndriySvyryd** [comment]
@NickSevens This is not Cosmos-specific, [owned types do not support inheritance](https://github.com/aspnet/EntityFrameworkCore/issues/9630)
