### ISSUE TITLE
IntegerGeneratorEndToEndInMemoryTest is flaky

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17672]
Can_use_sequence_end_to_end_from_multiple_contexts_concurrently_async()
>Assert.Equal() Failure\nExpected: 50\nActual: 41

**Comment by ajcvickers** [comment]
Marking for re-triage, since comment on #6872 implies that this is a product issue.

**Comment by ajcvickers** [comment]
@AndriySvyryd We've been waiting for you to triage this. Is there good evidence that this is a product issue? If so, should it be in the 3.1 milestone?

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes and yes

**Comment by ajcvickers** [comment]
@AndriySvyryd Can't get this to fail; any tips? Any ideas where the product issue is?

**Comment by AndriySvyryd** [comment]
I've seen it fail locally about 1 in 20 runs when running all tests.
Considering https://github.com/aspnet/EntityFrameworkCore/issues/18457, this is probably not high priority

**Comment by ericstj** [comment]
This was hit here: https://dev.azure.com/dnceng/public/_build/results?buildId=1135554&view=ms.vss-test-web.build-test-results-tab&runId=34454890&resultId=122792&paneView=debug

```
Assert.Equal() Failure
Expected: 50
Actual:   0


Stack trace
   at Microsoft.EntityFrameworkCore.IntegerGeneratorEndToEndInMemoryTest.Can_use_sequence_end_to_end_from_multiple_contexts_concurrently_async() in D:\workspace\_work\1\s\test\EFCore.InMemory.FunctionalTests\IntegerGeneratorEndToEndInMemoryTest.cs:line 113
--- End of stack trace from previous location ---
```

**Comment by ericstj** [comment]
False alarm, turns out it was a DI problem. https://github.com/dotnet/runtime/pull/52691
