### ISSUE TITLE
Simple Projection not working

### ISSUE THREAD

**Issue by bradleylandis** [dotnet/efcore#1768]
I'm try to do the following simple projection in Entity Framework 7 and getting the error: 
 System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=When called from 'VisitMethodCallExpression', expressions of type 'Expression' can only be replaced with other non-null expressions of type 'Expression'.
  Source=Remotion.Linq

Here is the code:
            //try simple projection with linq syntax
            var blogSummaries1 = blogContext.Blogs.Select(blog => new
            {
                Id = blog.Id,
                Name = blog.Name,
                PostCount = blog.Posts.Count()
            }).ToList();
            //That threw

```
        //try simple projection with query syntax
        var blogSummaries2 = (from blog in blogContext.Blogs
                             select new
                             {
                                 Id = blog.Id,
                                 Name = blog.Name,
                                 PostCount = blog.Posts.Count()
                             }).ToList();
        //That threw
```

The same code works on EF 6.

I can do this in EF 7 and get all the data loaded:
var blogs = blogContext.Blogs.Include(b => b.Posts).ToList();

So I don't think it is a general configuration issue.

**Comment by rowanmiller** [comment]
This is because we don't currently support using navigation properties in queries (`PostCount = blog.Posts.Count()`). This work is tracked by https://github.com/aspnet/EntityFramework/issues/325.

Opened https://github.com/aspnet/EntityFramework/issues/1799 to add a better exception until this is supported since it has tripped a lot of folks up.
