### ISSUE TITLE
"dotnet ef" can`t be executed properly(" The application to execute does not exist")

### ISSUE THREAD

**Issue by RainkLH** [dotnet/efcore#17708]
PM> dotnet ef
dotnet : The application to execute does not exist: 'C:\Users\xxx\.dotnet\tools\.store\dotnet-ef\2.2.6-servicing-10079\dotnet-ef\2.2.6-servicing-10079\tools\netcoreapp2.2\any\dotnet-ef.dll'.
-----------------------------------------------------------

Actually, the path of [dotnet-ef.dll] is 
"C:\Users\xxx\.dotnet\tools\.store\dotnet-ef\2.2.6\dotnet-ef\2.2.6\tools\netcoreapp2.2\any\dotnet-ef.dll"

so i copy the dir  "2.2.6\dotnet-ef\2.2.6\……"    
and rename it to "2.2.6-servicing-10079\dotnet-ef\2.2.6-servicing-10079……"

-----------------------------------------finally---
PM> dotnet ef

                     _/\__       
               ---==/    \\      
         ___  ___   |.    \|\    
        | __|| __|  |  )   \\\   
        | _| | _|   \_/ |  //|\\ 
        |___||_|       /   \\\/\\

------------------------------------------------------------------------------
emmmmmmmmmmmm
why????

**Comment by divega** [comment]
@RainkLH `dotnet ef` has been moving around between versions:

- Up to the .NET Core 2.2 SDK, the tool ships with the SDK
- In 3.0, the tool has been removed form the .NET Core SDK and has to be installed as either a global or a project tool

I believe what you are seeing is a combination of two limitations:
1. When you install a global or project tool with `dotnet tool install`, unless you specify a version, you will get the the latest sable version. 
2. The last stable version of the `dotnet ef` tool that is available in NuGet is 2.2, but it is a different binary from what is included in the SDK and isn't functional.

The workaround for this is to install the pre-release version of the tool by specifying the version. You can use wildcards after the version if you just wanted to get the latest build. This has detailed in the announcement blog posts and [in the breaking changes document](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#the-ef-core-command-line-tool-dotnet-ef-is-no-longer-part-of-the-net-core-sdk):

``` console
dotnet tool install --global dotnet-ef --version 3.0.0-*
```
I hope this helps,
Diego

**Comment by divega** [comment]
I am going to go ahead and close the issue assuming I have answered your question. If I haven't please reply mentioning me.

**Comment by pcoombe** [comment]
@divega ive just stumbled apon this issue since the 3.0 final SDK release

was trying to global install 2.2.6 as thats the ef version we are running, 
and getting the same issue that the paths are not what it expects.
dotnet-ef\2.2.6-servicing-10079\ vs dotnet-ef\2.2.6\
(the uninstall thinks it should be a different path yet again)

should we be installing v3 of the tool even though we are still targetting ef 2.2? 
my assumption is no.

i have got it working with a local install using dotnet-tools.json, however we are supposed to also now run dotnet tools restore? why wouldnt dotnet restore work out theres tools that need restoring 
:(

**Comment by rocts** [comment]
> I am going to go ahead and close the issue assuming I have answered your question. If I haven't please reply mentioning me.

Installed the release of v3 for the first time and I get this error, so seems it's not fixed with the release.

**Comment by divega** [comment]
@pcoombe, yes you should be installing the 3.0 version of the tool if you are going to use a 3.0 version of the .NET Core SDK 3.0, independent of what version of EF Core you are using in your projects. 

An if you use a previous version of the SDK you should not install any version of the tool.
