### ISSUE TITLE
AttachDBFileName fails if the value includes |DataDirectory|

### ISSUE THREAD

**Issue by mikeHag** [dotnet/efcore#17723]
I have a WPF Prism application working with Entity Framework Core 2.26.  The OnConfiguring method optionsBuilder.UseSqlServer call includes the following in the connect string:
AttachDBFileName=|DataDirectory|\\dbfiles\\my.mdf; 

I created a new project that uses .Net Core 3.0 Preview 9 and Entity Framework Core 3.0 Preview 9. At runtime the same connection string fails.  I get a System.ArgumentException with the message "Invalid value for key 'attachdbfilename'."

"|DataDirectory|" appears to be the problem.  AttachDBFileName with the full path works fine.  If I build up the full path using the value AppDomain.CurrentDomain.BaseDirectory the attach will also work.

**Comment by ErikEJ** [comment]
.NET Core SqlClient does not expand DataDirectory?

**Comment by mikeHag** [comment]
Yes, if I use "|DataDirectory|" the connection fails.

**Comment by bricelam** [comment]
Duplicate of https://github.com/dotnet/SqlClient/issues/16

**Comment by ErikEJ** [comment]
My PR to fix this has just been merged, and wil be part of the 1.1 release

**Comment by ajcvickers** [comment]
@ErikEJ Awesome! Really appreciate your perseverance!
