### ISSUE TITLE
Ability to set DeleteBehavior via ForeignKey annotation

### ISSUE THREAD

**Issue by dmarlow** [dotnet/efcore#17738]
To set the OnDelete referential action, you must have the ICollection navigation property defined in order to even use the ModelBuilder's WithMany and HasForeignKey fluent methods.

I'd like to be able to easily and quickly set the OnDelete action via the ForeignKey attribute on the one navigation property that's defined.

**Comment by AndriySvyryd** [comment]
Related to https://github.com/aspnet/EntityFrameworkCore/issues/10864

**Comment by smitpatel** [comment]
Also see #9621

Outstanding question. Should we add a separate attribute for DeleteBehavior or try to change ForeignKeyAttribute?

**Comment by ajcvickers** [comment]
@smitpatel We should _not touch anything_ in DataAnnotations unless we absolutely have to. Can of worms.

**Comment by smitpatel** [comment]
We will provide functionality of DeleteBehavior with it's own attribute as being tracked in #9621

Closing as won't fix since we don't plan to change ForeignKeyAttribute.
