### ISSUE TITLE
Allow tab indentation for generated migrations

### ISSUE THREAD

**Issue by jez9999** [dotnet/efcore#17739]
Right now, the `dotnet ef migrations` command generates migrations with the snapshot, migration, and migration designer files space-indented.  As I prefer tab indentation, there should be some way to configure it to generate these files with tab-indentation.

**Comment by roji** [comment]
Probable dup of #4038 - rather than specific support or extension points, we should probably just have templates (T4? Razor?) which people can customize any way they want.

/cc @bricelam

**Comment by divega** [comment]
@cincuranet we would consider a PR that makes IndentedStringBuilder a service. We need to check if we share the same infrastructure between model scaffolding and migrations.

**Comment by ajcvickers** [comment]
Note from triage: we don't plan to implement this; code formatting in modern IDEs should be able to easily handle the conversion.
