### ISSUE TITLE
Visual Studio "Publish" dialogue dotnet-ef error

### ISSUE THREAD

**Issue by mbalgo** [dotnet/efcore#17737]
Using Visual Studio 2019 and have tried the same in the latest Visual Studio 2019 Preview.

I right click on my project and select publish. 

The drop down for "Entity Framework Migrations" displays this error:

![image](https://user-images.githubusercontent.com/54877122/64580271-065a9e00-d3c9-11e9-9f07-44c9da93ac96.png)

It looks like VS is trying to run the dotnet-ef command. 

I have tried many varieties of installing and uninstalling dotnet-ef using the CMD outside of VS and the Nuget PM. Including the preview 3.0.0.* and the "latest stable version".

What I am trying to achieve, in the end, is to get the "update-database" command to run automatically when I publish my ASP .NET CORE 2.2 webapp to Azure.  So if anybody knows how to do that then that would be helpful to know.

So far I have created a webapp and it does display the homepage on the Azure site. 

I have created an SQL database in Azure and can connect to it in VS and see that my tables do not yet exist. 

I have put the connection string for the Azure database into the appsettings.json file, and the connection string for the localdb (which was originally in the appsettings.json file and generated automatically and works, I just copied it) into the appsettings.development.json file.

The "register user" functions fails on the website but works locally.

Probably because "update-database" or "apply-migrations" is not happening on the Azure side. 

Everything works on my local machine.

I do not even know whether I need to get the dotnet-ef command working in VS Publish. 

All I want to do is to run the "update-database" command on the Azure database/webapp so that the tables are created just like they are on my local development machine.

Is there a console window in the Azure portal where I can just type "update-database"? 

It would be nice if it just happened when I click Publish (and I think that the error above is what prevents that from happening), but I will settle for just typing "update-database" inside Azure every time I change the database structure since that will not really be happening all that frequently.

**Comment by bricelam** [comment]
Using that dialog is probably the best way to accomplish what you want.

A few follow up questions:
- What version of Visual Studio 2019 are you using? 16.3?
- What versions of the .NET Core SDK are installed? (use `dotnet --info`)
- Have you ran `dotnet tool install -g dotnet-ef`?
- Does your project have a global.json file?

**Comment by killerangels** [comment]
Have you ran dotnet tool install -g dotnet-ef
solved my problem

**Comment by bricelam** [comment]
Note, the Publish dialog team is looking into automatically installing the tool if it's missing

**Comment by khalidrs1903** [comment]
I am facing issue but error is different can some one help me to solve this issue please. Screen shot of the error and other info is below.
![image](https://user-images.githubusercontent.com/31385089/85017358-fa3a1300-b188-11ea-858a-3f0dbb7dfd1f.png)

**"dotnet --info" results**
![image](https://user-images.githubusercontent.com/31385089/85017508-33728300-b189-11ea-8350-f435d14ab82a.png)

Thank you

**Comment by ajcvickers** [comment]
@khalidrs1903 Issues in Visual Studio tooling are better reported with the "Send Feedback" option in VS. This will get the issue to a place where the VS team will see it.

**Comment by HazemAhmed90** [comment]
Hello,
I have the same problem although I have the required packages 
Can anyone help with this please 
Thanks in advance

**Comment by ajcvickers** [comment]
@HazemAhmed90 As mentioned in the previous comment, it would be better to report this to Visual Studio.

**Comment by HazemAhmed90** [comment]
> @HazemAhmed90 As mentioned in the previous comment, it would be better to report this to Visual Studio.

Many thanks
Will do and post their answer
