### ISSUE TITLE
Cosmos: Make the 'id' property more flexible

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17751]
- [x] Rename the `id` property created by convention to avoid it clashing with an entity property.
- [x] Make sure that the property created by the convention is removed if any other property is mapped to `id` (the new property should get the value generator).
- [x] Validate all properties have distinct database names
- [x] Remove the value generator from the property mapped to `id` if it's part of the PK
- [x] Validate that all entity types have an `id` property and that `id` and the partition key are mapped to string

**Comment by MedAnd** [comment]
Hi @AndriySvyryd - seems it's also not possible to override the PK name when mapping using the fluent api... could this bug be the reason this is not supported:

` modelBuilder.Entity<VerificationResponse>(m =>
{
         m.ToContainer("VerificationResponses");
         m.HasKey(k => k.CorrelationId).HasName("id");
         m.HasPartitionKey(o => o.ShopperId);
});
`
