### ISSUE TITLE
Cosmos: Populate __jObject on SaveChanges

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17778]

**Comment by IGx89** [comment]
Any chance of this hitting v5? It makes the solution described in https://docs.microsoft.com/en-us/ef/core/providers/cosmos/unstructured-data#accessing-the-raw-json for working with JObject fields untenable for added entities, since __jObject remains empty even after SaveChangesAsync.

**Comment by AndriySvyryd** [comment]
This doesn't have enough votes to consider doing in 5. But we are always happy to review well-written external PRs.

**Comment by IGx89** [comment]
I did some digging around in the Cosmos provider's code to see how difficult implementing this would be, and it looks like it might be pretty simple. If I add the following into CosmosClientWrapper.ProcessResponse it achieves the goal and all tests still pass:

```
            var jObjectProperty = entry.EntityType.FindProperty("__jObject");
            if (jObjectProperty != null
                && jObjectProperty.ValueGenerated == ValueGenerated.OnAddOrUpdate
                && response.Content != null)
            {
                using var responseStream = response.Content;
                using var reader = new StreamReader(responseStream);
                using var jsonReader = new JsonTextReader(reader);

                var createdDocument = new JsonSerializer().Deserialize<JObject>(jsonReader);

                entry.SetStoreGeneratedValue(jObjectProperty , createdDocument);
            }
```

Before I submit a PR, would you be able to confirm if that's an acceptable approach or not?

**Comment by AndriySvyryd** [comment]
@IGx89 Looks good, but use `StoreKeyConvention.JObjectPropertyName`

**Comment by IGx89** [comment]
Sweet! Definitely. Expect a PR soon, along with another small improvement to allow populating it on new entities as well. Appreciate you being so receptive to contributions here!
