### ISSUE TITLE
Mapping support for private setters of properties

### ISSUE THREAD

**Issue by Praveen-Rai** [dotnet/efcore#17800]
EFCore supports accessing readonly properties using the private backing field. Defining private backing fields isn't so good for readability ( and code manageability ) for it adds verbosity. Even VS doesn't seems happy about it.
![VS_EFCore](https://user-images.githubusercontent.com/39744031/64795759-3e660a80-d59c-11e9-99f7-2bfad054a94c.png)

EFCore must support configuration ( entity mapping support ) for properties having private setters.

**Comment by Praveen-Rai** [comment]
Seems like there was an issue, which i am unable to reproduce now. I hit it while create Migrations using `dotnet ef` command. I am using _Microsoft.EntityFrameworkCore.Preview9_ & _npgsql.EntityFrameworkCore.Postgres.Preview9_ . I will keep a watch and will try to return with a reproducible scenario.

Moreover i feel the CLI isn't too clear in error reporting. I kept getting for various issues : 

> Your startup project 'xyz' doesn't reference Microsoft.EntityFrameworkCore.Design. 
The above message is displayed even when the startup project isn't specified in the cmd options. Ideally, the error message in that case must be "Please specify the startup project".

> Unable to create an object of type 'xyzContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by smitpatel** [comment]
@Praveen-Rai - You could be hitting https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#microsoftentityframeworkcoredesign-is-now-a-developmentdependency-package

**Comment by Praveen-Rai** [comment]
@smitpatel Now i am completely lost :-( , but i did add _Microsoft.EntityFrameworkCore.Design_ . One thing i could notice even now is that `dotnet ef` command doesn't build the entire solution. And that might have been the problem. Not very sure, will have to try.

**Comment by Praveen-Rai** [comment]
For now the good news is that properties with private setter are supported and works fine. The error i got could be a wrong message reported by `dotnet ef` command.

**Comment by Praveen-Rai** [comment]
@smitpatel I just tried to search for the error message string in the Src, and could locate below messages in _\src\EFCore\Properties\CoreStrings.resx_ . Still couldn't recall which one i got.

- The navigation property '{navigation}' on the entity type '{entityType}' does not have a setter and no writable backing field was found or specified. Read-only collection navigation properties must be initialized before use.
- 
- The property '{property}' of entity type '{entity}' does not have a setter. Either make the property writable or use a different '{pam}'.
- 
- No backing field could be found for property '{property}' of entity type '{entity}' and the property does not have a setter.
