### ISSUE TITLE
Defining Query vs ToView

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17804]
If both of them are defined which one should be applied?

**Comment by bricelam** [comment]
Duplicate of #17270

**Comment by smitpatel** [comment]
It mentions the other way is default then what we have right now. (Currently defining query gets applied). Should we make "bug-fix"?

**Comment by bricelam** [comment]
Current way sounds correct to me

**Comment by divega** [comment]
Triage: We will assume the current behavior is correct for now. May revisit in #17270.
