### ISSUE TITLE
Add a warning for decimal PKs with SqlServer

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17817]
We use strict comparisons for PK values that can fail in some scenarios: https://github.com/aspnet/EntityFrameworkCore/issues/14952, https://github.com/aspnet/EntityFrameworkCore/issues/6835

Same for concurrency tokens https://github.com/aspnet/EntityFrameworkCore/issues/17799

Consider recommending to use [SET NUMERIC_ROUNDABORT ON](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-numeric-roundabort-transact-sql?view=sql-server-2017)

**Comment by divega** [comment]
Triage: We should avoid breaking changes in 3.1, but we are not sure this would be one.
