### ISSUE TITLE
Database.Migrate() raises login failed error with SQL Server Express

### ISSUE THREAD

**Issue by smadurange** [dotnet/efcore#17824]
I'm using EF Core version 2.1.11 with SQL Server Express version 12.0.2000.

I have my entity:

    public class MyEntity
    {
        public string Id { get; set; }
    
        public int Age { get; set; }
    }

and my Db context:

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options)
            : base(options)
        {
        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
    
            modelBuilder.Entity<MyEntity>();
        }
    }

In order to create migrations using `dotnet ef migrations add InitialCreate`, I also have a design-time factory defined like:

    public class MyContextFactory : IDesignTimeDbContextFactory<MyContext>
    {
        public MyContext CreateDbContext(string[] args)
        {
            var options = new DbContextOptionsBuilder<MyContext>()
                .UseSqlServer("server=localhost\\SQLEXPRESS;Initial Catalog=MyTestDB;Integrated Security=true")
                .Options;

            return new MyContext(options);
        }
    }

Note that, in my SQL Express, I have not created a database named `MyTestDB`. I want EF Core to create this database and apply the migrations. So, my main method that attempts this is:

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContextFactory().CreateDbContext(Array.Empty<string>()))
            {
                ctx.Database.Migrate();
            }
        }
    }

Now, the line `ctx.Database.Migrate()` raises the exception:

    System.Data.SqlClient.SqlException: 'Cannot open database "MyTestDB" requested by the login. The login failed.
    Login failed for user 

This exception is being raised because the `MyTestDB` is not in SQL Express server at the time of opening the connection. What is strange is, when I run the main method, it raises this exception like 15 times (which is suppressed unless the exception settings are enabled) but when the program exits, and I check the database, the database is actually created and the migrations are applied.

My question is how can I avoid this exception being raised (I do not want to create the database before running the code)? What is the proper way to use the connection string and the `Database.Migrate()` method?

**Comment by bricelam** [comment]
These exceptions are being handled by EF. If I remember correctly, we are passing the exceptions to the ILogger which makes them look more serious than they are. I think we had an issue to stop doing this but I can't seem to find it. Possible #15269?

**Comment by bricelam** [comment]
Oops, wrong issue

**Comment by smadurange** [comment]
Since, eventually the migrations are applied, I guess it's kind of handled. However, it seems that multiple failed login attempts with the database server creates unexpected delays in applying migrations. For instance, one time, I saw 14 SQL exception being raised before the program could complete applying migrations.

This delay is causing some integration tests (that check if a service is up) is failing I think because of a timing issue. When the database server is far, the delay is quite pronounced. The service too more than 5 seconds to actually start running.

**Comment by divega** [comment]
@smadurange could you please provide a repro, or at least some extract from the logs containing the exception?

**Comment by smadurange** [comment]
@divega If you just run the code sample I posted in my question, you will get that exception. It's a self-contained program. Or are you not getting that exception when you try to apply migrations using `Database.Migrate()` on a database that doesn't exist?

**Comment by smitpatel** [comment]
@smadurange - I put your repro code in a console app and ran it. It only threw exception 2 times and both of them were handled. I am not able to see 14 occurrences.

@bricelam - Is 2 times expected for Migrate? EnsureCreated shows only once in logs.

**Comment by bricelam** [comment]
That vaguely rings a bell, but I should probably look again
