### ISSUE TITLE
Restore ability to explicitly configure field name that differs from property name

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#17853]
We made the decision that during EF Core 3.0 we would re-enable configuration like this, after breaking it in preview 4. From the [breaking change documentation](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#field-only-property-names-should-match-the-field-name):

> #### Mitigations
> Field-only properties must be named the same as the field they are mapped to. In a later preview of EF Core 3.0, we plan to re-enable explicitly configuring a field name that is different from the property name:
> ``` c#
> modelBuilder
>    .Entity<Blog>()
>    .Property("Id")
>    .HasField("_id");
> ```

Unfortunately it seems we missed doing this before GA.

@AndriySvyryd I did a quick search to see if we already had a duplicate for this and I didn't find it, but maybe you know where it is.

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/15307

**Comment by divega** [comment]
Closed as duplicate of #15307.
