### ISSUE TITLE
Missing API net core 3.0 .WithMany (How to define many to many relationships using modelbuilder

### ISSUE THREAD

**Issue by joschemd** [dotnet/efcore#17865]
In EF6 you would define a many to many relationship as per MS documentation at: https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/relationships

There doesn't seem to be a work around or best practice to get the Navigation properties setup for this scenario

``` C#
modelBuilder.Entity<Course>()
    .HasMany(t => t.Instructors)
    .WithMany(t => t.Courses)
```

However in EF Core 3.0 you can only define a one to many as the API only seems to have WithOne() method exposed

### Steps to reproduce
``` C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Course>()
                .HasMany(t => t.Instructors)
                .WithOne(t => t.Courses) // WithMany() missing
}
```

### Further technical details

EF Core version: 3.0 preview 9
Database provider: CosmosDB
Target framework:  .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 preview 3

**Comment by bricelam** [comment]
Join the fun over in #1368 😉
