### ISSUE TITLE
Return a table value parameter as a IQueryable

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/efcore#17885]
Sometimes you have a large number of id's from a UI or from an external system. You want to query against these id's. The classic Where(entity => ids.Contains(entity.Id)) is very slow. 

I would love to see a mechanic for getting data using table value parameters. A syntax like this or similar

```
db.ExecuteTableValueQuery(ids)
``` 

Since it returns a IQueryable it could be used like this with good performance

```
db.ExecuteTableValueQuery(ids)
   .Join(db.Set<MyEntity>(), id => id, e => e.Id, (id, e) => e);
```

The table value parameter type could be fixed by convention, if ids is a `IEnumerable<int>` it will try to use a sql type called `ef__core_int_tvp` or similar convention.

**Comment by smitpatel** [comment]
@divega to dedupe.

**Comment by divega** [comment]
This is similar enough to https://github.com/aspnet/EntityFrameworkCore/issues/13239 to close as duplicate. 

@AndersMalmgren it would be great if you could take a look at that issues and elaborate on any additional aspects you see missing, e.g. the convention for naming of tables types.

**Comment by AndersMalmgren** [comment]
@divega I added some of my own ideas to that issue
