### ISSUE TITLE
Allow owned entities on a keyless entity type

### ISSUE THREAD

**Issue by aherrick** [dotnet/efcore#17890]
I have a simple view in my DB that is exposing some fields joined from multiple tables.

I'm able to map my view to my object similar to below:

```
	public IQueryable<MyDbView> MyDbView => Query<MyDbView>();

        modelBuilder.Query<MyDbView>().ToView(nameof(MyDbView));
```

MyDbView is an object similar to below.

```
		public class MyDbView
		{
			public string Name { get; set; }

			public Address OriginAddress { get; set; }
			public Address DestinationAddress { get; set; }
		}

		public class Address
		{ 
                        public int Id { get; set; }
			public string Name { get; set; }

			public string City { get; set; }
			public string State { get; set; }
		}
```

Since the view has flattened the 2 Address fields into 6 fields (`OriginAddressName`, `OriginAddressCity`, etc.), I'd like to inflate them back to the object so `MyDbView` doesn't have to have a direct mapping to each of the fields and I can reuse my types.

How is the possible?

**Comment by smitpatel** [comment]
@aherrick - Can you elaborate more exactly what are you trying to achieve? What is the view definition and what part is causing issue?

**Comment by aherrick** [comment]
Let's pretend my view looked like the following:

```
		Select  s.Id						'ShipmentId',
				oa.Id                       'OriginAddressId',
				oa.Name                     'OriginAddressName',
				oa.City						'OriginAddressCity',
				oa.State                    'OriginAddressState',
				da.Id                       'DestinationAddressId',
				da.Name                     'DestinationAddressName',
				da.City						'DestinationAddressCity'
				da.State                    'DestinationAddressState',
				
		From   Shipment s
		Join Address oa
			On s.Originaddressid = oa.Id
		Join Address da
			On s.Destinationaddressid = da.Id
```
I'd like to inflate this View into the `MyDbView` object.

**Comment by smitpatel** [comment]
@aherrick - That is not possible. In EF each entityType maps to one database object. Same database object can be used for multiple entityTypes but you cannot specify a database object to materialize a graph of object. 
The closest we have in backlog is #14525 which is about using result of FromSql to materialize whole graph. You can perhaps use it to do basic select from view. 
Another alternative we have tracking is #11296 which allows you to specify raw SQL query for include.

If above was an aggregate root, there could have been more options but keyless entity types cannot act as one.

**Comment by aherrick** [comment]
Hmm Thanks... I was hoping I could do something similar to below so I could just manually map the fields.

```
modelBuilder.Entity<Entity>().OwnsOne(
    o => o.OriginAddress,
    sa =>
    {
        sa.Property(p => p.Street).HasColumnName("ShipsToStreet");
        sa.Property(p => p.City).HasColumnName("ShipsToCity");
     // etc.
    });
```

**Comment by smitpatel** [comment]
@aherrick - I also thought that is probably what you intend. But keyless entities cannot be principal end of relationship hence they cannot have owned entities.

**Comment by kgaska** [comment]
Is there any reason why keyless entity cannot have owned type which origin is from the exactly same table? It would be very useful to be able simplify/reuse entity model for views or tables without primary key.

**Comment by kislovs** [comment]
+1 for ability to use `OwnsOne` on keyless entity, because it fit best when you need use only mappings from EF Core for `Set<T>.FromSql[Raw|Interpolated](...)`.

**Comment by igorgiovannini** [comment]
+1
