### ISSUE TITLE
Foreign Key string constraint failed

### ISSUE THREAD

**Issue by dandandandaann** [dotnet/efcore#17905]
I have an issue like this: https://github.com/aspnet/EntityFrameworkCore/issues/16875
Except that my Key is String which is supposed to be already nullable.

I have these classes:
```C#
public class Transaction : Entity
{
    public string TransactionNumber { get; set; }
    public virtual ICollection<Movement> movements { get; set; }
}
public class Movement : Entity
{
    public int MovementId { get; set; }
    public string TransactionNumber { get; set; }
    public virtual Transaction Transaction { get; set; }
}
```
The configuration is setting the key:
```C#
builder.ToTable("Transaction");
builder.HasKey(d => d.TransactionNumber);
```

If I only create a new `Movement` with a `TransactionNumber` and save it I get a `SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.`. If a create both `Movement` and `Transaction` together it doesn't happen.  
I tried changing the `TransactionNumber` to `int?` and it seems to work fine this way.  
  
This issue is only happening in my test environment with Sqlite in memory creating the database codefirst. It's working fine in my production setup using MySql where the database is created independently.

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore 2.2.6
Database provider: Microsoft.EntityFrameworkCore.Sqlite 2.2.6
Target framework: NET Core 2.2

**Comment by AndriySvyryd** [comment]
@danielfdutra Please create a runnable project that shows this issue

**Comment by danielfdutra** [comment]
https://github.com/danielfdutra/EFCoreFKExceptionPoC

**Comment by smitpatel** [comment]
@danielfdutra - It throws exception because Transaction with `TransactionNumber` = `C` does not exist. A nullable FK property allows you to add `Movement` which does not belong to any `Transaction` but FK constraint will still block you to add `Movement` which references to a `Transaction` which does not exist.

**Comment by smitpatel** [comment]
@bricelam - I could not find the issue for unconstrainted relationships.

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/13146
