### ISSUE TITLE
How IMigrator to deal with migrations in multiple assemblies

### ISSUE THREAD

**Issue by stantoxt** [dotnet/efcore#17904]
I want to apply migrations in different assemblies at app startup.
Can this method `Configure the migrations assembly: options.UseSqlServer(connectionString,x =>x.MigrationsAssembly("MyApp.Migrations"));`  achieve that？

**Comment by bricelam** [comment]
Do you mean migrations in different assemblies for the same DbContext?

**Comment by stantoxt** [comment]
Yes,How can I override IMigrator and IMigrationAssembly Dependency Inject?

**Comment by bricelam** [comment]
Why do you want to spread migrations across multiple assemblies? Would having multiple DbContext types simplify your scenario?

**Comment by stantoxt** [comment]
I am developing multi-tenant modular system, the migrations are produced by DesignTimeDbcontext,they are scattered across multiple assemblies. When a new tenant is initializing , I want to use IMigrator to auto migrate at runtime.

**Comment by bricelam** [comment]
Would it be simpler if each module had its own DbContext and defined all the migrations required for that DbContext? The DbContext types could even share some entity classes so long as only one DbContext was in charge of creating migrations for it--#2725 would make this easier.

**Comment by bricelam** [comment]
But yes, if you want to continue with your current approach, replacing the IMigrationsAssembly is the right way.
``` csharp
class MyMigrationsAssembly : IMigrationsAssembly
{
    Type _contextType;
    public MyMigrationsAssembly(
        ICurrentDbContext currentContext)
    {
        _contextType = currentContext.Context.GetType()
    }

    // TODO: Return all the migrations for _contextType
    public IReadOnlyDictionary<string, TypeInfo> Migrations
        => throw new NotImplementedException();

    // Only used by the tools which probably won't work with your architecture
    public ModelSnapshot ModelSnapshot
        => throw new NotImplementedException();

    // Only used by tools and logging
    public Assembly Assembly
        => typeof(void).Assembly;

    // Only used when specifying source and target migration
    public string FindMigrationId(string nameOrId)
        => throw new NotImplementedException();

    public Migration CreateMigration(TypeInfo migrationClass, string activeProvider)
    {
        var migration = (Migration)Activator.CreateInstance(migrationClass.AsType());
        migration.ActiveProvider = activeProvider;

        return migration;
    }
}
```
``` csharp
protected override void OnConfiguring(DbContextOptionsBuilder options)
    => options
        .ReplaceService<IMigrationsAssembly, MyMigrationsAssembly >()
        .UseSqlServer(...);
```

**Comment by stantoxt** [comment]
Thank you, @bricelam .I will try it.

**Comment by stantoxt** [comment]
I aslo want to Add more column to __EFMigrationsHistory like [Column Created Time in EFMigrationsHistory](https://github.com/aspnet/EntityFrameworkCore/issues/13651) and [EF6-How do I add an additional column to the __MigrationHistory table](https://stackoverflow.com/questions/24025075/how-do-i-add-an-additional-column-to-the-migrationhistory-table). I have read the post [Custom Migrations History Table](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table) ,so What is best practice for now?

**Comment by bricelam** [comment]
Yes, create a custom HistoryRepository. Override ConfigureTable to add a column to the table, and override GetInsertScript to insert values into it.

**Comment by zencqui** [comment]
> Thank you, @bricelam .I will try it.

Hi @stantoxt, Were you able to achieve your goal. I am looking at implementing the same.
