### ISSUE TITLE
Could not load type IDbContextOptionsExtensionWithDebugInfo from EntityFrameworkCore

### ISSUE THREAD

**Issue by TomasHubelbauer** [dotnet/efcore#17917]
I think I am able to reproduce closed #15192 in RC1.

`dotnet --version`: 3.0.100-rc1-014190

What I did:

- Scaffold a new .NET Core MVC app with individual account auth:
  `dotnet new mvc --auth Individual`
- Run the app using `dotnet run` and accept the self-signed certificate in the
  browser at https://localhost:5001
- Register, sign out, sign in and sign out again to test the database
- Remove `app.db` and `ConnectionStrings` in `appSettings.json`
- Install the EF in-memory provider:
  `dotnet add package Microsoft.EntityFrameworkCore.InMemory`
- Replace `AddDbContext` with
  `services.AddDbContext<ApplicationDbContext>(options => options.UseInMemoryDatabase(nameof(aws_elastic_beanstalk)))`
- *Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsExtensionWithDebugInfo' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0*

You can see the problem in this repo:

https://github.com/TomasHubelbauer/aws-elastic-beanstalk

### Further technical details

EF Core version: 3.0.0-rc1.19457.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) in memory
Target framework: (e.g. .NET Core 3.0) .NET Core 3.0.100-rc1-014190
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3) CLI

**Comment by AndriySvyryd** [comment]
@TomasHubelbauer You need to keep all dependencies at the same version, including `Microsoft.EntityFrameworkCore.InMemory`

**Comment by TomasHubelbauer** [comment]
Ah, I didn't realize `dotnet add package` will not install pre-release version. Wish the error message was better though.

**Comment by TomasHubelbauer** [comment]
Another thing which doesn't help is that for my version of EF (`3.0.0-rc1.19457.4`) there is no corresponding version of the in-memory provider. The closes is `3.0.0-rc1.19456.14 `.

**Comment by AndriySvyryd** [comment]
I think you are referring to the ASP .NET Core version. Yes, unfortunately the build portion don't match EF for pre-release packages

**Comment by TomasHubelbauer** [comment]
Indeed, I misread the package name. At least it's documented in this issue now for Google. FWIW I was able to get the above to work with in-memory once I switched that package to the RC1 version as well.
