### ISSUE TITLE
3.0 Query Rearchitecture

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#17911]
@smitpatel @ajcvickers 

I just started digging into the new query architecture to start adding back in support for table valued functions.  

I just have to say this architecture is a lot cleaner than the old Re-Linq based code.  Great job team!

**Comment by smitpatel** [comment]
@pmiddleton - Thank you for kind words. Give us feedback to improve it even further as you encounter things during development.

**Comment by bricelam** [comment]
lol, "by design". Yes, our architecture is cleaner by design...
