### ISSUE TITLE
Query : Contains can not be translated to "in" clause 

### ISSUE THREAD

**Issue by Anas-11** [dotnet/efcore#17939]
Am trying to check if any element of a list exists in the DB using the following code :
var results =await  _dbContext.Brands.AsNoTracking().AnyAsync(a => brandsHashset.Contains(a.Name));
Expecting that EF will translate it to "in" clause and the list will be sent as parameters , instead am getting an exception that it can not be translated .

**Comment by smitpatel** [comment]
Duplicate of #17877
