### ISSUE TITLE
Scaffolding: Provide a way to initialize a model with business code

### ISSUE THREAD

**Issue by dsthode** [dotnet/efcore#17937]
When I create my models database-first with scaffolding, a constructor is created for the classes that have foreign keys which creates the HashSet for the relations, like the snipped below:

```cs
// this is autogenerated code
public partial class incidents() {
        [...]

        public incidents()
        {
            action_maintenance = new HashSet<action_maintenance>();
            inci_history = new HashSet<inci_history>();
            inci_status_x_incidents = new HashSet<inci_status_x_incidents>();
        }
        [...]
}
```

Also, sometimes I need to initialize these models with business related data, like initializing properties to certain values and such.

Linq to SQL gave an OnCreated() hook that was called from the constructor once the model was initialized for the framework that was used to initialize properties to business needs (see below an example), but nothing alike exists in EntityFramework Core, or I have been unable to find it.

```cs
// this is autogenerated code
public partial class incidents {
    [...]
    partial void OnCreated();

    public incidents() {
        [...] // initialization of relations
        OnCreated();
    }

    [...]
}
```
```cs
// this is own code
public partial class incidents {
    partial void OnCreated()
    {
        this.creation_date = DateTime.Now;
        this.id = Guid.NewGuid();
    }
}
```

So, it would be great if EFCore included such hook to allow users to initialize the class once the relations have been set up.

**Comment by smitpatel** [comment]
@bricelam - Thoughts?

**Comment by ErikEJ** [comment]
Great idea!

**Comment by bricelam** [comment]
Not sure we'd add first-class support for this directly in EF Core, but #4038 would enable it.

**Comment by ErikEJ** [comment]
I will consider adding it to EF Core Power Tools

**Comment by dsthode** [comment]
I have had a look at the issue linked, EF Core Power Tools and other issues open in the tracker, and I have the following thoughts about it:

- I think the solution proposed in #4038 seems a bit too much just for the functionality requested. At least in it's current inception for the providers.

- EF Core Power Tools would be ok, but depending on external tools doesn't fancy too much, it would be better if it was provided by the framework, although this is the solution that gives the most flexibility via the templates. Another caveat is that we are using VSCode, not Visual Studio, so this tool is no tan option for us. It would be great if EFCore Power Tools was an independent tool, installable through `dotnet tool install` for example.

- I had a look at #626, and maybe it would be the best suited for what I'm asking. Say the lifecycle hooks gave an OnCreated event/callback/whatever where the entity is instantiated by the constructor and control is given to the user to further initialize the object with business specific code (say the model class implements some interfaces via it's partial and needs further processing)

What are your thoughts?

**Comment by smitpatel** [comment]
Discuss with @ajcvickers
