### ISSUE TITLE
How to explicitly turn off identity

### ISSUE THREAD

**Issue by dyslexicanaboko** [dotnet/efcore#17934]
Upon generating my initial migration, all of my `HasKey(...)` properties will generate a primary key and assume `SqlServerValueGenerationStrategy.IdentityColumn`. I have not found a way to create a primary key without the column being set as an Identity Column.

Putting it very simply. I want to create a Primary Key column that does not have identity set.

**Comment by AndriySvyryd** [comment]
See https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties:
``` C#
modelBuilder.Entity<Blog>()
    .Property(b => b.BlogId)
    .ValueGeneratedNever();
```

**Comment by dyslexicanaboko** [comment]
Thank you so much, I really did search and search - I couldn't find anything regarding identity generation options. That's the last place I would have looked.

I got squirrled looking at the generated code from the migration:
```
TableId = table.Column<int>(nullable: false)
    .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
```

Just curious though, wouldn't an option like that be better suited sitting under `HasKey`?

This makes more sense in my opinion:
```
b.HasKey(x => x.TableId)
    .HasName("PK_dbo.Table_TableId")
    .HasIdentity();  //Just indicates the usual default of IDENTITY(1,1) - include overloads for other options
```
Where `HasIdentity()` could also just simply be turned off?

I just feel like it would be wise to keep how Fluent API works as close to SQL Server or any other database really.
`TableId NOT NULL IDENTITY(1,1)` <-- this is easy to do and it's in one place.

**Comment by ajcvickers** [comment]
@dyslexicanaboko `Identity` is associated with the property/column, not the key. A key may have one Identity property/column together with other non-Identity properties/columns.
