### ISSUE TITLE
Refactor ColumnModification

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17946]
- `UseCurrentValueParameter` , `UseOriginalValueParameter` ->  `UseCurrentValue`, `UseOriginalValue`, `UseParameter` (`Entry != null`)
- Review `Value` implementation
- Review usage in `UpdateSqlGenerator`, `MigrationsModelDiffer` and data operations

**Comment by ajcvickers** [comment]
While working on this also consider #23027

**Comment by AndriySvyryd** [comment]
Notes from PR:
The `ColumnModification` is tightly coupled with `ModificationCommand`, so it would be more appropriate to have an `IModificationCommandSource`. In the future it could also be used to pool `ModificationCommand` instances.

The signature for the factory method should be `ModificationCommand Create(ModificationCommandParameters)` to avoid breaking changes if we need to change the passed in parameters.

`ModificationCommand` would need a `ColumnModification AddColumnModification(ColumnModificationParameters)` method for internal and `MigrationsSqlGenerator` use.
