### ISSUE TITLE
Consider making checked enums optional

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#17949]
https://github.com/aspnet/EntityFrameworkCore/issues/15411 was about adding database check constrains for enum properties. The implementation is now in master. 

However I think that this should only be enabled if the user opts in, because constrained enum values deviates quite a lot from the enum type semantics in .NET. For example, in .NET:

- An enum variable can contain any value of the underlying integer type
- The default value for enum is always 0 of the underlying integer type, even if there is not declared member with value 0

Being able to make enums strict is a desirable feature, and it was considered in the original design for enums in the original [enums spec](https://blogs.msdn.microsoft.com/efdesign/2011/06/29/enumeration-support-in-entity-framework/) we considered this.

**Comment by AndriySvyryd** [comment]
Covered by #214
