### ISSUE TITLE
InMemory database does not map required navigation properties

### ISSUE THREAD

**Issue by pedro-monge** [dotnet/efcore#17954]
I am writing unit test using InMemory database and when I apply the required attribute to a navigation property it allows me to save that entity without the navigation property being filled whereas with the Sql Server provider throws the corresponding exception.

### Steps to reproduce
``` C#
public class Request
{
    public int Id { get; set; }
    public string Data { get; set; }
}
public class Response
{
    public int Id { get; set; }
    public string Data { get; set; }
    [Required]
    public Request Request { get; set; }
}
public class TestDbContext : DbContext
{
    public TestDbContext(DbContextOptions<TestDbContext> options)
        : base(options)
    {
    }
}
public class Repository<T>
            where T : class
{
    public Repository(DbContext newDbContext)
    {
        this.DbContext = newDbContext;
    }
    public virtual async Task AddAsync(T entity)
    {
        await this.DbContext.Set<T>().AddAsync(entity);
    }
    public virtual async Task<int> SaveAsync()
    {
        return await this.DbContext.SaveChangesAsync();
    }
}

```

So, if you do something like this it does not throw an exception:

``` C#
var options = new DbContextOptionsBuilder<TestDbContext>()
                        //.UseSqlServer("Server=.\\SQLExpress;Database=SuppliersProxy;Integrated Security=true;").Options;
                        .UseInMemoryDatabase("test").Options;
var context = new TestDbContext(options);
var entity = new Response ()
{
    Data = "Test",
};

var repo = new Repository(context);
repo.AddAsync(entity).Wait();
repo.SaveAsync().Wait(); //at this point the exception should be thrown
```

You can just change the provider to check it.

Not sure it is already covered in any other bugs.

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 2.2
Operating system: Windows 7
IDE: Visual Studio 2019 16.2.5

**Comment by ivanrodriguezfernandez** [comment]
InMemory will allow you to save data that would violate referential integrity constraints in a relational database.

https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#inmemory-is-not-a-relational-database
