### ISSUE TITLE
An utility method to eliminate casts used by generic methods in builders

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/efcore#17981]
There is a lot of places in EF nd its providers where a generic method calls its non-generic version which implements all logic. This introduces a lot of casts. To reduce code size, improve quality and to make code less error prone there could be added some methods in EF itself which will call a non generic method and cast the result back:

```csharp
public static DbContextOptionsBuilder<TContext> NonGeneric<TContext>(
    Func<DbContextOptionsBuilder, DbContextOptionsBuilder> method,
    DbContextOptionsBuilder<TContext> optionsBuilder)
    where TContext : DbContext
    => (DbContextOptionsBuilder<TContext>)method(optionsBuilder);

public static DbContextOptionsBuilder<TContext> NonGeneric<TContext, T>(
    Func<DbContextOptionsBuilder, T, DbContextOptionsBuilder> method,
    DbContextOptionsBuilder<TContext> optionsBuilder, T arg)
    where TContext : DbContext
    => (DbContextOptionsBuilder<TContext>)method(optionsBuilder, arg);

// and so on... and for other types...
```

Example:

```csharp
// before
public static DbContextOptionsBuilder<TContext> UseSnakeCaseNaming<TContext>([NotNull] this DbContextOptionsBuilder<TContext> optionsBuilder)
    where TContext : DbContext
    => (DbContextOptionsBuilder<TContext>)UseSnakeCaseNaming((DbContextOptionsBuilder)optionsBuilder);
// after
public static DbContextOptionsBuilder<TContext> UseSnakeCaseNaming<TContext>([NotNull] this DbContextOptionsBuilder<TContext> optionsBuilder)
    where TContext : DbContext
    => NonGeneric(UseSnakeCaseNaming, optionsBuilder);
```

The disadvantage is that is allocates delegates, but since EF allocates a lot during the configuration step maybe it's not so important.

**Comment by smitpatel** [comment]
@YohDeadfall - Adding any public surface in EF Core for "providers" means that it has to be in public class & not inside .Internal namespace. Which also exposes them to public. Given these methods live alongside methods which customers are supposed to call, it would confuse customers if we add them. If it helps you in making code DRY then you can put those methods as private in your class as implementation detail. We don't plan to add these methods due to negative value it provides to customers.

**Comment by YohDeadfall** [comment]
Okay, but does it make sense to introduce it in SQL Server and SQLite providers? Some internal code as you know is copy pasted to non-Microsoft providers, so it won't be a public API, but still can be used by all parties.

/cc @roji @brgrainger

**Comment by YohDeadfall** [comment]
Okay, but does it make sense to introduce it in SQL Server and SQLite providers? Some internal code as you know is copy pasted to non-Microsoft providers, so it won't be a public API, but still can be used by all parties.
/cc @roji @bgrainger

**Comment by smitpatel** [comment]
@AndriySvyryd - Do you believe that we should do this in our providers?

**Comment by AndriySvyryd** [comment]
We'll consider it when working in this area, I don't think it's high priority
