### ISSUE TITLE
Could not install package 'Microsoft.EntityFrameworkCore 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8'

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#17999]
Update from 2.1.4 to 3.0.0

Could not install package 'Microsoft.EntityFrameworkCore 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Steps to reproduce
Update to Microsoft.EntityFrameworkCore 3.0.0 via Visual Studio 2019 Nuget 

### Further technical details

EF Core version: 2.1.4 -> 3.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .Net Framework 4.8
IDE: Visual Studio 2019

**Comment by OpenSpacesAndPlaces** [comment]
I found the issue:
https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

"Given many of the API additions in .NET Standard 2.1 require runtime changes in order to be meaningful, .NET Framework 4.8 will remain on .NET Standard 2.0 rather than implement .NET Standard 2.1. .NET Core 3.0 as well as upcoming versions of Xamarin, Mono, and Unity will be updated to implement .NET Standard 2.1."

Closing thread.

**Comment by bricelam** [comment]
@OpenSpacesAndPlaces Are you considering migrating to .NET Core 3.0? What kind of app is it?

**Comment by OpenSpacesAndPlaces** [comment]
Eventually yes - but for now we're stuck on framework.

Mostly I'm just confused because I thought the whole point of .NET Standard was to maintain cross-compatibility.

**Comment by OpenSpacesAndPlaces** [comment]
@bricelam Also to be clear- we've be using EF Core on Framework for over a year in production sites (not some new thing for fun just this week)

**Comment by bricelam** [comment]
I'm sure you already know this, but EF Core 2.1 will continue to be supported on .NET Framework for some time.

Out of curiosity, what parts of .NET Framework are you using that aren't in .NET Core 3.0 or the [Windows Compatibility Pack](https://docs.microsoft.com/dotnet/core/porting/windows-compat-pack)? (or in the upcoming [CoreWCF](https://github.com/CoreWCF/CoreWCF) project)

**Comment by OpenSpacesAndPlaces** [comment]
Primarily it's a boatload of webforms code that's the blocker.

**Comment by bricelam** [comment]
☹ My sympathy. The path forward for webforms is not an easy one

**Comment by bricelam** [comment]
Do you want to submit a new feature request for us target netstandard2.0 again? We discussed the possibility today from a technical standpoint. I'd like to see how much community interest there is.

**Comment by OpenSpacesAndPlaces** [comment]
Where would I do that?

Either flipping EF Core 3.0 back to netstandard2.0 or making something like a .Net Framework 4.8.1 with netstandard2.1 support, or even another Nuget package that would shim netstandard2.1 in, would be great.

**Comment by bricelam** [comment]
Just [submit a new issue](https://github.com/aspnet/EntityFrameworkCore/issues/new?labels=type-enhancement&template=feature_request.md) requesting that you’d like EF Core 3 to target .NET Standard 2.0. I think this is important for .NET Framework and also older versions of Xamarin, UWP, and Unity.
