### ISSUE TITLE
How to go on with ILike PostgreSql issue

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/efcore#17996]
The Like method in PostgreSql doesn't match case-insensitive according to the active locale, instead we must use ILike. It is available by Npgsql.EntityFrameworkCore.PostgreSQL through DbFunctions.ILike from the Npgsql team.

I have a project targeting 3 databases 

```
public abstract class BaseDbContext : DbContext { ... }

public class MssqlDbContext : BaseDbContext { ... }
public class PostgreDbContext : BaseDbContext { ... }
```

I have a code like this
```
var customers = context.Customers.Where(c => EF.Functions.Like(c.Name, "a%"));
```

But the above code does't work as expected in postgre. So, in postgresql the code should be
```
var customers = context.Customers.Where(c => EF.Functions.ILike(c.Name, "a%"));
```

it's not nice to have a code with If that checks the database procider. 

So, is there a way to tell the sql server that when it gets ILike should translate it in Like and in my code use only ILike?

I have posted the issue also here. https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/999

**Comment by roji** [comment]
We discussed this in triage and decided that the current semantics are more correct.

As a general rule, EF Core doesn't attempt to cover over nuances or behavioral differences between databases; doing so has proven to be either impossible or detrimental to performance as hacks have to be used to force a database into a behavior that is unnatural to it.

Specifically for case sensitivity, it is not really possible to reliably achieve the same case-sensitivity behavior across databases:
* SQL Server allows you to configure collation, so it's not possible to know how LIKE will behave without knowing how the database is set up.
* PostgreSQL actually has a similar situation - LIKE over columns of type CITEXT do already have case-insensitive behavior.
* Sqlite apparently has its own non-standard behavior with regards to non-English characters.

All the above make it impossible to guarantee the case-sensitivity behavior in the general case.

An additional argument is that in our experience, the (vast) majority of users target a single database and are familiar with its specific SQL dialect. It would be surprising for a PostgreSQL user to use `EF.Functions.Like` and get case-insensitive behavior, as the expectation would be to naturally map that to PostgreSQL LIKE. This penalizes users targeting multiple databases, but improves the experience for single-database users, which seems like the right trade-off to make.

Note that it should be possible to have a utility which generates a different expression tree, callling EF.Functions.Like or PG EF.Functions.ILike depending on the database used. This could lessen the burden of writing cross-database code.
