### ISSUE TITLE
Support for Explicit keys and Unique 

### ISSUE THREAD

**Issue by joelmandell** [dotnet/efcore#17992]
I am working with a legacy database where keys (unique) are added on your own. 
There is no Primary Key and there is no identity increment.

My proposal on how to implement it is by adding a attribute that could do a query for highest value on Key column.
Then do an insert.
I have developed an ripoff of EF, were I have an attribute that is checked on a SaveChanges call. If it has an autoinc it will query the table for highest key and increment by 1.
But there is still a lot of features missing, so I was thinking maybe better to implement in ef core.

But the question is: would it be possible to implement in ef core?

**Comment by smitpatel** [comment]
@joelmandell - We don't plan to implement such functionality in EF Core. Further, querying database in advance for each inserted record may actually be bad perf.
A better alternative is to define a trigger which runs every time a row is added in the table and assigns the value of autoinc column by querying the table (this is all on server side). And in EF Core config, you can mark the property as ValueGeneratedOnAdd https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties#value-generated-on-add EF will read back the value after inserting records and update client side objects.

This will get you what you want in easier way.

**Comment by joelmandell** [comment]
But one would need the to create the triggers manually?
