### ISSUE TITLE
Use <inheritdoc/>

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#18003]
The time has come

**Comment by roji** [comment]
Notes:

* IIRC VS Intellisense supports omitting `<inheritdoc />` altogether, implicitly inheriting documentation from the superclass/interface. This would be ideal.
* Make sure that StyleCop (or whatever) flags undocumented methods which should specify docs (because they don't inherit) but don't do so.
* Whatever we end up doing, make sure it works everywhere (VS, docfx...).

**Comment by roji** [comment]
Super crazy idea!

We could have the "this is an internal API" message on some single shared internal static class member, and then reference that from everywhere with `<inheritdoc cref="foo" />`.

**Comment by sharwell** [comment]
> Super crazy idea!
>
> We could have the "this is an internal API" message on some single shared internal static class member, and then reference that from everywhere ...

It's not really crazy, just not super common (yet). I've used it before.

Definition:

https://github.com/SciSharp/TensorFlow.NET/blob/14f8adbc3d5644ca29cd95f28f62c39ff8f325a7/src/TensorFlowNET.Core/Util/SafeHandleLease.cs#L26-L35

Reference:

https://github.com/SciSharp/TensorFlow.NET/blob/468cb8e8a649ce246d8e472df3170fb7fcdab95b/src/TensorFlowNET.Core/Buffers/Buffer.cs#L33-L35

**Comment by roji** [comment]
\<inheritdoc /\> is now supported by the doc system.

Note that currently no attributes are supported, though cref is apparently in the plan; separated this out to #24386.

**Comment by ajcvickers** [comment]
Note from triage: we will not make any concerted effort to go through existing docs and do this. It can be used in new code or when making other changes, except not for the pubternal message. If doing so, make sure the docs on the derived type is really the same (and should be the same) as on the base type.
