### ISSUE TITLE
Building IQueryable not from DbSet then attach to DbSet

### ISSUE THREAD

**Issue by moataz1991** [dotnet/efcore#18008]
I wans to build IQueryable<T> from Enumerable<T>.AsQueryable<T>()
then send the IQueryable<T> to some DbContext class for excution

something like this
```
public class Querying<T>
    {
         public T BuildQuery()
         {
            return Enumerable.Empty<T>().AsQueryable().Where(...);
         }
    }

    public class DatabaseContext<T>:DbContext
    {
        DbSet<T> _set;
        public List<T> ExecuteQuery(Querying<T> query)
        {
              return _set.AttachQuery(query.BuildQuery()).ToList();
        }
    }
```

**Comment by smitpatel** [comment]
Can you elaborate why you want to do that? If this is just about refactoring the query generation then you can do this way
```C#
public class Querying<T>
    {
         public IQueryable<T> BuildQuery(IQueryable<T> root)
         {
                return root.Where(...);
         }
    }

    public class DatabaseContext<T>:DbContext
    {
        DbSet<T> _set;
        public List<T> ExecuteQuery(Querying<T> query)
        {
              return query.BuildQuery(_set.AsQueryable()).ToList();
        }
    }
```

**Comment by moataz1991** [comment]
> Can you elaborate why you want to do that? If this is just about refactoring the query generation then you can do this way
> 
> ```cs
> public class Querying<T>
>     {
>          public IQueryable<T> BuildQuery(IQueryable<T> root)
>          {
>                 return root.Where(...);
>          }
>     }
> 
>     public class DatabaseContext<T>:DbContext
>     {
>         DbSet<T> _set;
>         public List<T> ExecuteQuery(Querying<T> query)
>         {
>               return query.BuildQuery(_set.AsQueryable()).ToList();
>         }
>     }
> ```

i don't want any component to have the ability to execute anything
only building up the query and execution handler will handle that and return the results

your code the component can simply call `.ToList()` and it will execute which will break my pattern

**Comment by smitpatel** [comment]
I believe if you do not want any code to be executed while building expression tree but want to execute with EF on demand, you need to re-create expression tree with all query roots replaced.
Can you describe what is the reasoning behind this kind of separation?

**Comment by moataz1991** [comment]
segregate execution from preparing

**Comment by smitpatel** [comment]
Refactoring I posted also segregate execution from preparing. Such segregation does not require having execution blocked. So I am still not able to get why you would need to block execution altogether. But if that is what you want to do then you can rewrite expression tree once you have prepared it.

**Comment by smitpatel** [comment]
@moataz1991 - If you want to block execution then you can write wrapping IQueryable and override Execute method and throw exception unless a specific method is called. That would avoid rewriting whole tree and still allow you to block.

We don't plan to add anything in EF to support this scenario.
