### ISSUE TITLE
Is there a way to get dbSet<T> from tableName list?

### ISSUE THREAD

**Issue by Maci94** [dotnet/efcore#18013]
I have to delete some items and i have a list of {tableName, idToDelete}

how can i get a dbSet<T> (with type, not dbSet without type)

< or IQueryable<T>(there id a method to get IQueryable without type) >
code example 
```    
list = new List<TableInfo>() {  new { TableName="Users", idToDelete=5 }, new { TableName="Orders", idToDelete=4},    } 
foreach (var table in list)
{
    //T = users 1st iteration, Orders 2nd iteration 
     var dbSet(<T>) = magic.GetDbSet(table.TableName);
     var item = dbset.where(x=>x.id == idToDelete);
     dbset.remove(item);
      
    //     IQueryable Alternative
    //T = users 1st iteration, Orders 2nd iteration 
     Iqueryable<T> all = magic.GetAll/GetQueryable(table.TableName);
     var item = all .where(x=>x.id == idToDelete);
     DbContext.remove(item);
}
```
avoid result like dbset or iqueryable without type

### Further technical details (UPDATED)

EF Core version: 3.0.0 (not preview)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.0 (not preview)
Operating system: Windows 7
IDE: Visual Studio 2019 16.4 preview 1

**Comment by smitpatel** [comment]
@Maci94 - There are mainly 2 issues with above.
- Multiple entityTypes can map to same table in database (table splitting scenario). So finding entityType from tableName does not work always.
- Even if the table name & entityType have one to one mapping, creating a dbset requires reflection and you will not be able to dbSet<T> in your method.

You can split out your method in different sub-methods where each one deals with particular entityType and you call into correct method by using switch on table name.

**Comment by Maci94** [comment]
> You can split out your method in different sub-methods 
the problem is that i have a lot of table and i can't create a compiled method for each table 
in my code i have a list of {tableName, idItemToDelete} and i don't know how to delete items with E EF Core
