### ISSUE TITLE
I cannot install EFCore 3.0 in UWP project 

### ISSUE THREAD

**Issue by IstvanKor** [dotnet/efcore#18011]
I have tried to install Microsoft.EntityFrameworkCore 3.0.0  package in a UWP project but I got the following error:

Package Microsoft.EntityFrameworkCore 3.0.0 is not compatible with uap10.0.18362 (UAP,Version=v10.0.18362) / win10-x64. Package Microsoft.EntityFrameworkCore 3.0.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)

UWP application targets 18362 version, minimal version 18362.
VS version: 16.3.0

Thanks for your help!

**Comment by huoyaoyuan** [comment]
EF Core 3 requires .net standard 2.1, which is planned but not yet supported by UWP.
.net standard 2.0 was supported by UWP 2 months after its release.

**Comment by bricelam** [comment]
My favorite slide from dotNETConf:

![dotnet5](https://user-images.githubusercontent.com/1226749/65540821-04acd200-dec1-11e9-85e4-e27cd07fcd72.gif)

I hope UWP will also join the party

**Comment by smitpatel** [comment]
@richlander - Do you have guidance for customers for this scenario?

**Comment by YZahringer** [comment]
🎉 Fixed on 3.1.0-preview2: https://github.com/aspnet/EntityFrameworkCore/issues/18141
