### ISSUE TITLE
System.InvalidCastException : Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#18028]
### Steps to reproduce
``` C#
DbConnection dbConnection = context.Database.GetDbConnection(); // System.Data.Common
SqlConnection sqlConnection= (SqlConnection)dbConnection; // System.Data.SqlClient
```
Second line throws an exception:
> System.InvalidCastException : Unable to cast object of type
'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.

I need this for `bulk.WriteToServer()` since _**SqlConnection**_ is type of the first argument in _SqlBulkCopy_ constructor.

### Further technical details

EF Core version: NET Core 3.0
Database provider:  in library System.Data.SqlClient is used,
---------------------  while TestProject has also  Microsoft.EntityFrameworkCore.SqlServer
Target framework: (.NET Standard 2.1)
Operating system: Windows 10
IDE: (Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
Microsoft.EntityFrameworkCore.SqlServer depends on Microsoft.Data.SqlClient hence the cast is invalid.
@bricelam - Is there a way to use SqlServer package with System.Data.SqlClient?

**Comment by bricelam** [comment]
You need to create a new SqlConnection object. There's no way to convert between the two.

We have https://github.com/aspnet/EntityFrameworkCore/issues/15758 for re-introducing a System.Data.SqlClient.dll based provider.

**Comment by bricelam** [comment]
@borisdj AFAIK, Microsoft.Data.SqlClient also has SqlBulkCopy. Can you just remove System.Data.SqlClient in favor of [the new Microsoft.Data.SqlClient](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/)?

**Comment by borisdj** [comment]
After reading following blog: [introducing-the-new-microsoftdatasqlclient](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/)
I have solved the issue by replacing _System.Data.SqlClient_ nuGet with **_Microsoft.Data.SqlClient_**.

**Comment by borisdj** [comment]
Precisely what I did.
Can be closed.
