### ISSUE TITLE
NewExpression cannot be evaluated if provided to custom db functions

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#18026]
After switching to EF Core 3.0 a `NewExpression` (anonymous type) cannot be evaluated when provided to a custom db function resulting in client side evaluation.

Demo: [MethodTranslatorDemo.cs](https://github.com/PawelGerr/Presentation-EntityFrameworkCore/blob/EF-Core_3.0/src/EntityFramework.Demo/Demos/MethodTranslatorDemo.cs)

### Custom function
``` C#
public static class DbFunctionsExtensions
{
   public static int MyDbFunction(this DbFunctions functions, object args)
   {
      throw new NotSupportedException();
   }
}
```

### Method translator
```C#
public class MyMethodCallTranslator : IMethodCallTranslator
{
   private static readonly MethodInfo _myDbFunction = typeof(DbFunctionsExtensions).GetMethod(nameof(DbFunctionsExtensions.MyDbFunction), BindingFlags.Static | BindingFlags.Public);

   public SqlExpression Translate(SqlExpression instance, MethodInfo method, IReadOnlyList<SqlExpression> arguments)
   {
      if (method == _myDbFunction)
      {
         // dummy implementation
         return new SqlConstantExpression(Expression.Constant(42), RelationalTypeMapping.NullMapping);
      }

      return null;
   }
}
```

### Queries
When passing 1 property then the query is translated correctly
```
// SELECT 42 AS [Foo]
// FROM [Products] AS [p]
var result = _ctx.Products
                 .Select(p => new
                              {
                                 Foo = EF.Functions.MyDbFunction(p.Id)
                              })
                 .ToList();
```

When passing an anonymous class to the function then EF is not able to translate the method (or rather the arguments)
```
var result = _ctx.Products
                 .Select(p => new
                              {
                                 Foo = EF.Functions.MyDbFunction(new
                                                                 {
                                                                    p.Id,
                                                                    p.Name
                                                                 })
                              })
                 .ToList();
```

The method translator is not called because the `RelationalSqlTranslatingExpressionVisitor` kind of trying to translate the `NewExpression` twice. Before a method translator is called all method arguments are translated by the `RelationalSqlTranslatingExpressionVisitor`. During translation of the `NewExpression` the method `RelationalSqlTranslatingExpressionVisitor.CanEvaluate(expr)` is being called. `CanEvaluate` expects 3 types of expressions: `ConstantExpression`, `NewExpression` and `MemberInitExpression`. The problem is the `MemberInitExpression` are translated already to `PropertyExpression`s so none of the types match.

#### `RelationalSqlTranslatingExpressionVisitor.VisitMethodCall()` shortly before `CanEvaluate` is called
![image](https://user-images.githubusercontent.com/7135790/65545134-0dc78e80-df15-11e9-84dd-cec26d48090e.png)

### Further technical details
* Microsoft.EntityFrameworkCore.SqlServer: 3.0.0
* Target framework: netcoreapp3.0

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

**Comment by smitpatel** [comment]
This is by design, a NewExpression cannot be represented in SQL tree.

**Comment by PawelGerr** [comment]
> This is by design, a NewExpression cannot be represented in SQL tree.

Any alternative besides creating dozens of method overloads like

```
public static class DbFunctionsExtensions
{
   public static int MyDbFunction<T1>(this DbFunctions functions, T1 arg1)
   {
      throw new NotSupportedException();
   }

   public static int MyDbFunction<T1, T2>(this DbFunctions functions, T1 arg1, T2 arg2)
   {
      throw new NotSupportedException();
   }
}
```

Usage:
```
var result = _ctx.Products
                 .Select(p => new
                              {
                                 Foo = EF.Functions.MyDbFunction(p.Id, p.Name)
                              })
                 .ToList();
```

**Comment by smitpatel** [comment]
I am not sure how you can map method to same DbFunction on database side unless the function is variadic which is not supported at present. And even if we support it, it would be like params argument rather than arbitrary shape object.
Now, if you are writing custom translation ignoring the arguments then again, arguments does not matter much and shouldn't include. If you are mapping to different functions based on argument count then yes, you need overloads since your server side function is also different.

**Comment by PawelGerr** [comment]
Support of params argument would be a better alternative for some functions having variable number of parameters (similar to `FREETEXT / FULLTEXT` clause).
I'm ignoring the arguments to keep it simple, the real implementation will/should use all of them.

For now the overloads are good enough.
