### ISSUE TITLE
Question: can I enable client query evaluate for ef core 3.0?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#18038]
can I enable client query evaluate?

As the docs said here <https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client>

`LINQ queries are no longer evaluated on the client`

**Comment by smitpatel** [comment]
@WeihanLi - You can enable client evaluation by explicitly calling `AsEnumerable` method. Everything after that method would be evaluated in memory and will be outside of EF. EF does not have a mode to do this implicitly for you.
