### ISSUE TITLE
3.0 Custom function schema set to dbo regardless schema is set to null or ""

### ISSUE THREAD

**Issue by NanFengCheong** [dotnet/efcore#18036]
Custom function doesn't translate correctly when schema is set to null or "".
Generate SQL still contains dbo as schema

### Steps to reproduce

```
[DbFunction("JSON_VALUE", null)]
        public static string JsonValue(string column, [NotParameterized]string path)
        {
            throw new NotImplementedException();
        }
```

```
[DbFunction("JSON_VALUE", null)]
        public static string JsonValue(string column, [NotParameterized]string path)
        {
            throw new NotImplementedException();
        }
```

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: WIndows 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
Breaking change: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#udf-empty-string
