### ISSUE TITLE
New entity added in state "modified" instead of "added"

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#18044]
I just upgraded to EF Core 3.0, and I noticed the following break in code.

There are some lines similar to this:

```
var context = new DbContext();
var entityA = context.EntityA.First(...);
context.Entry(entityA).Collection(a => a.EntityB).Load();
var entityB = new EntityB() {
  EntityAID = entityA.Id,
  EntityBID = new Guid(),
};
entityA.EntityB.Add(entityB);
```

As soon as entityB is added to the collection, I checked the ChangeTracker
`context.ChangeTracker.Entries().ToList()[0]`
And I see that entityB was added to the change tracker. However, it's `State=Modifed`.  This is wrong, as it should be `State=Added`.

The result is that when I run the following:
```context.SaveChanges();```
I get an exception `Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded.`

When I run SQL Profiler, i see this is because an `UPDATE` statement was generated rather than an `INSERT` statement.

As a bonus question, how did EF know to add entityB to the ChangeTracker?  entityA.EntityB is of type `ICollection<EntityB>` and is giving an instance of `HashSet<EntityB>` by the `Load()` call.  `HashSet<>` doesn't have any change events, so I don't see how EF could know something was added.

**Comment by joshmouch** [comment]
If I modify the code slightly then this issue no longer occurs:

```
var context = new DbContext();
var entityA = context.EntityA.First(...);
context.Entry(entityA).Collection(a => a.EntityB).Load();
var entityB = new EntityB() {
  EntityAID = entityA.Id,
  EntityBID = new Guid(),
};
context.Add(entityB); // THIS LINE WAS ADDED
entityA.EntityB.Add(entityB);

```

**Comment by smitpatel** [comment]
Likely hitting this https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#detectchanges-honors-store-generated-key-values

**Comment by joshmouch** [comment]
Thanks!
