### ISSUE TITLE
Sacaffold fails when relationship has two fields. No create navigation properties

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#18040]
I have a N:N table in this way:

```
TableA
{
    bigint ID;
}

TableB
{
    bigint ID
}


TableAB
{
    bigint IDA,
    bigint IDB
}
```

The TablaAB has a unique relationship, with fields IDA and IDB. This relationship is created by Sql Server when I set the primary key.

The problem is that when I scaffold, the POCO entities for TableA and TableB has not the navigation properties, so I can create the relationship between them.

If I separate the relationship in two relationships, one for IDA and another for IDB, then the navigation properties are created as expected.

Thanks.

**Comment by smitpatel** [comment]
@ComptonAlvaro - We are having hard time understanding what is the issue. Can you please explain what is the issue? If it is issue in scaffolding, can you provide the SQL script for database schema, scaffolded output and expected output?

**Comment by bricelam** [comment]
> If I separate the relationship in two relationships...then the navigation properties are created as expected.

N:N relationships require two foreign key constraints. It sounds like this may be by design. Are you using SQLite? Otherwise, I'm not sure how you are able to get it to work at all with only one foreign key...

**Comment by ComptonAlvaro** [comment]
I am using Sql Server. The N to N table is this:

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MytableNtoN](
	[IDA] [bigint] NOT NULL,
	[IDB] [bigint] NOT NULL,
 CONSTRAINT [FK_MyConstraintName] PRIMARY KEY CLUSTERED 
(
	[IDA] ASC,
	[IDB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MytableNtoN]  WITH CHECK ADD  CONSTRAINT [FK_MyConstraintName] FOREIGN KEY([IDA], [IDB])
REFERENCES [dbo].[MytableNtoN] ([IDA], [IDB])
GO

ALTER TABLE [dbo].[MytableNtoN] CHECK CONSTRAINT [FK_MyConstraintName]
GO
```

The are only one constraint with 2 fields.

**Comment by bricelam** [comment]
That foreign key constraint constrains the field values to be themselves (x = x). It is a no-op and gets ignored by Reverse Engineering.

**Comment by ComptonAlvaro** [comment]
Then should I create 2 foreigners relationships in the many to many table, one relationship to IDA and another relationship to IDB?

**Comment by bricelam** [comment]
``` sql
CREATE TABLE TableA (
     ID bigint PRIMARY KEY
);

CREATE TABLE TableB (
    ID bigint PRIMARY KEY
);

CREATE TableAB (
    IDA bigint REFERENCES TableA,
    IDB bigint REFERENCES TableB,
    PRIMARY KEY (IDA, IDB)
);
```
