### ISSUE TITLE
DynamicModelCacheKeyFactory behavior changed since 3.0 release?

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#18052]
My whole dynamic filter mechanism is built on this, using a binary key to develop different models depending a dynamic key that is generated like this:

public (Boolean u, Boolean a, Boolean h) Key => (ActiveUserId != 0, ActiveAccountId != 0, ShowHidden);

Starting with deployments today (builds from yesterday or 2 days ago work fie), the alterantive models are not found anymore.

My dynamic model key factory is:

        public class DynamicModelCacheKeyFactory : IModelCacheKeyFactory
        {
            public Object Create(DbContext context)
            {
                if (context is Repository dynamicContext)
                {
                    return (context.GetType(), dynamicContext.Key);
                }
                return context.GetType();
            }
        }

Not sure this relatres to an EfCore change or a change in the runtime (changing the way those generated structs are compared).

This has totally cut down redeployment (WITHOUT code change) of new compiled versions which now blow, and as such I am stuck from updateing the 2.2 runtimes and deploying anything.

**Comment by AndriySvyryd** [comment]
@NetTecture We didn't change anything in this area and I am not sure how this worked for you before. ValueTuple shouldn't be used as the cache key since it's a value type, use a Tuple instead. See: https://github.com/aspnet/EntityFrameworkCore/blob/release/3.1/test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs#L426

**Comment by ajcvickers** [comment]
@AndriySvyryd We've been waiting for you to triage this. Is there anything actionable on our side?

**Comment by AndriySvyryd** [comment]
@ajcvickers No, we can close this now

**Comment by Diaskhan** [comment]
@Nettecture have u solve ure problem ?

**Comment by NetTecture** [comment]
Yes, sorry. It was basically a call that was made BEFORE setting the parameters that resulted in the memory cache being initialized with always the same key. Changing db timeout actually loads the model ;)

Sorry for not coming back.

**Comment by Diaskhan** [comment]
In 2.2 the code calls only once when Object is changed
```
   public Object Create(DbContext context)
        {
            if (context is Repository dynamicContext)
            {
                return (context.GetType(), dynamicContext.Key);
            }
            return context.GetType();
        }
```

Could U check in 3.0 it calls everytime when dbcontext is created !

**Comment by Diaskhan** [comment]
I've opened nee one 
https://github.com/aspnet/EntityFrameworkCore/issues/18611
