### ISSUE TITLE
.Concat results in Union All

### ISSUE THREAD

**Issue by gufi** [dotnet/efcore#18053]
.Concat should result in UNION vs the expectation that .Union would result in UNION  ALL

### Steps to reproduce
concat any two sets of data using EF Core 3.0
<!--
What steps can we follow to reproduce the issue?

``` C#
(from t1 ctx.Table select new { t1.StringColumn }).Union(from t2 in ctx.Table2 select new { t2.StringColumn})
```

### Further technical details

EF Core version: 3.0 
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.concat?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union?view=netframework-4.8

Union in Linq removes duplicates, Concat does not.
Union in SQL removes duplicates, Union all does not.

Current implementation aligns with expected results.

**Comment by gufi** [comment]
Indeed. it appears i've previously been hit by a very old bug that my old office worked around by switching concats and unions =) apologies!
