### ISSUE TITLE
optionsBuilder.UseSqlServer AttachDBFilename |DataDirectory| fail

### ISSUE THREAD

**Issue by FlippieCoetser** [dotnet/efcore#18067]
When passing a connection string, **with** ```|DataDirectory|``` as part of the ```AttachDBFilename``` field, to the ```optionsBuilder.UserSQL()``` an error is thrown: **Invalid value for key 'attachdbfilename'**

When passing a connection string, with the data folder path (**without** ```|DataDirectory|```)  as part of the ```AttachDBFilename``` field, to the ```optionsBuilder.UserSqlServer()``` no error is thrown.

To reproduce the error use ```EF Core Migrations``` and type ```update-database``` in Package Manager Console in Visual Studio 2019

**Comment by ErikEJ** [comment]
This is a .NET Core SqlClient issue, not an EF Core issue

**Comment by smitpatel** [comment]
Duplicate of dotnet/SqlClient#16
