### ISSUE TITLE
Updating a property that is an owned type throws an exception if the property is null.

### ISSUE THREAD

**Issue by joalcava** [dotnet/efcore#18066]
Updating a property that is an owned type throws an exception if the property is null.

### Steps to reproduce
I've created a repo to reproduce the error
https://github.com/joalcava/efcore_ownedtypes_bug/blob/master/Program.cs

I got this exception:

`System.InvalidOperationException: The entity of type 'DueDate' is sharing the table 'Tasks' with entities of type 'Task', but there is no entity of this type with the same key value that has been marked as 'Added'.`

However, in my main project, where I first expirienced this issue I got other this other exception:

`System.InvalidOperationException: An instance of entity type 'Task' is marked as 'Modified', but an instance of entity type 'DueDate' is marked as 'Added' and both are mapped to the same row.`

I wasn't able to reproduce the exact same exception 

### Further technical details

EF Core version: 3.0.0
Database provider: Tested with SQL Server and SQLite, didn't check with postgres
Target framework: .NET Core 3.0
Operating system: I'm using Ubuntu 19.04, didn't test in other OS
IDE: Any

**Comment by joalcava** [comment]
Seems like duplicate of #17935 but not sure.

**Comment by AndriySvyryd** [comment]
Yes, it's a duplicate. You can try [nightly builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) to make sure your scenario is fixed.

**Comment by joalcava** [comment]
Tested with the nightly builds and can confirm it's solved. Thanks
