### ISSUE TITLE
HasQueryFilter not working from Entity Framework Core 3.0 

### ISSUE THREAD

**Issue by DUWENINK** [dotnet/efcore#18084]
I use `HasQueryFilter` in `IEntityTypeConfiguration` but i still can find my deleted data

### Steps to reproduce

THIS is my baseEntity
```C#
   /// <summary>
    /// 基础实体
    /// </summary>
    public class BaseEntity
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime CreateDateTime { get; set; }

        public string CreateUserId { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public bool IsDeleted { get; set; }
    }
```

i have config this in my project 

``` C#

  public class BaseConfiguration<T> : IEntityTypeConfiguration<T> where T : BaseEntity
    {
        public virtual void Configure(EntityTypeBuilder<T> builder)
        {
            //配置全局过滤器
            //India Assam do this wrong maybe
            builder.HasQueryFilter(x => x.IsDeleted == false);
            builder.Property(e => e.CreateUserId).HasMaxLength(36);
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).HasMaxLength(36);
        }
    } 
```

then i take a select 

![image](https://user-images.githubusercontent.com/16337239/65748333-42fef700-e136-11e9-80e9-93570895cd6e.png)

but in the `SSMS` the data 

![image](https://user-images.githubusercontent.com/16337239/65747184-5d83a100-e133-11e9-9654-c857b8ff5c63.png)

What the fk
![image](https://user-images.githubusercontent.com/16337239/65747213-712f0780-e133-11e9-8330-87a570234a09.png)

### Further technical details

EF Core version: 3.0
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework:NET Core 3.0
Operating system:Windows 10 Pro 19XX
IDE: Visual Studio 2019 16.3.1

**Comment by smitpatel** [comment]
@DUWENINK - can you also share the linq query you are running & generated SQL from profiler?

**Comment by DUWENINK** [comment]
This is my Linq query  
```C#
/// <summary>
        /// 分页搜索
        /// </summary>
        /// <param name="filters">查询过滤参数</param>
        /// <returns></returns>
        public async Task<PagedResult<MenuDto>> SearchAsync(MenuFilters filters)
        {
            if (filters == null)
                return new PagedResult<MenuDto>();

            var query = _context.Menus.AsQueryable();

            if (filters.keywords.IsNotBlank())
                query = query.Where(x => x.Name.Contains(filters.keywords));
            if (filters.ExcludeType.HasValue)
                query = query.Where(x => x.Type != (byte)filters.ExcludeType.Value);

            //query = query.Where(c => c.IsDeleted == false);
            return await query.OrderByDescending(item => item.CreateDateTime)
                .Select(item => new MenuDto
                { 
                    Id = item.Id,
                    ParentId = item.ParentId,
                    Name = item.Name,
                    Url = item.Url,
                    Order = item.Order,
                    Type = (MenuType)item.Type
                }).PagingAsync(filters.page, filters.rows);
        }
```
this is my sql  from sql profile
`` SQL 
exec sp_executesql N'SELECT [m].[Id], [m].[ParentId], [m].[Name], [m].[Url], [m].[Order], CAST([m].[Type] AS tinyint) AS [Type]
FROM [Menus] AS [m]
ORDER BY [m].[CreateDateTime] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=15
```

**Comment by DUWENINK** [comment]
> This is my Linq query
> 
> ```cs
> /// <summary>
>         /// 分页搜索
>         /// </summary>
>         /// <param name="filters">查询过滤参数</param>
>         /// <returns></returns>
>         public async Task<PagedResult<MenuDto>> SearchAsync(MenuFilters filters)
>         {
>             if (filters == null)
>                 return new PagedResult<MenuDto>();
> 
>             var query = _context.Menus.AsQueryable();
> 
>             if (filters.keywords.IsNotBlank())
>                 query = query.Where(x => x.Name.Contains(filters.keywords));
>             if (filters.ExcludeType.HasValue)
>                 query = query.Where(x => x.Type != (byte)filters.ExcludeType.Value);
> 
>             //query = query.Where(c => c.IsDeleted == false);
>             return await query.OrderByDescending(item => item.CreateDateTime)
>                 .Select(item => new MenuDto
>                 { 
>                     Id = item.Id,
>                     ParentId = item.ParentId,
>                     Name = item.Name,
>                     Url = item.Url,
>                     Order = item.Order,
>                     Type = (MenuType)item.Type
>                 }).PagingAsync(filters.page, filters.rows);
>         }
> ```
> 
> this is my sql from sql profile
> `` SQL
> exec sp_executesql N'SELECT [m].[Id], [m].[ParentId], [m].[Name], [m].[Url], [m].[Order], CAST([m].[Type] AS tinyint) AS [Type]
> FROM [Menus] AS [m]
> ORDER BY [m].[CreateDateTime] DESC
> OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=15
> 
> ```
> 
> ```
@smitpatel

**Comment by smitpatel** [comment]
@DUWENINK - I am not able to reproduce this. I am getting where predicate generated correctly. Can you verify that your EntityTypeConfiguration is being called (hence actually configuring the filter)? If yes, then can you share a full repro code which shows the issue you are hitting?

**Comment by DUWENINK** [comment]
@smitpatel  I have upload the project on this repo , The Readme.md show it how to deploy  https://github.com/DUWENINK/NETCORE_3_HELP

**Comment by DUWENINK** [comment]
@smitpatel updating.....

**Comment by smitpatel** [comment]
The code supplied to reproduce this issue is quite complex. It would help greatly to have a simplified project/solution or code listing that isolates the issue in EF.

**Comment by ajcvickers** [comment]
@DUWENINK There is a lot of code in that solution, and at least some of it is referencing earlier and incompatible versions of EF packages, including incompatible providers. We're not going to be able to make progress here without a _small_, runnable solution that references consistent versions of 3.0 packages. This will likely require work on your side to narrow down what conditions are causing the behavior you are seeing.

**Comment by DUWENINK** [comment]
> @DUWENINK There is a lot of code in that solution, and at least some of it is referencing earlier and incompatible versions of EF packages, including incompatible providers. We're not going to be able to make progress here without a _small_, runnable solution that references consistent versions of 3.0 packages. This will likely require work on your side to narrow down what conditions are causing the behavior you are seeing.

OK , I will take a  retry when I am free

**Comment by DUWENINK** [comment]
I try paste this code  in the `OnModelCreating` 
```C#
  //事实证明印度佬并不可靠
            //在原来的 BaseConfiguration中的HasQueryFilter 已经无效了 
            foreach (var entityType in modelBuilder.Model.GetEntityTypes()
               .Where(e => typeof(ISoftDlete).IsAssignableFrom(e.ClrType)))
            {
                modelBuilder.Entity(entityType.ClrType).Property<bool>("IsDeleted");
                var parameter = Expression.Parameter(entityType.ClrType, "e");
                var body = Expression.Equal(
                    Expression.Call(typeof(EF), nameof(EF.Property), new[] { typeof(bool) }, parameter, Expression.Constant("IsDeleted")),
                Expression.Constant(false));
                modelBuilder.Entity(entityType.ClrType).HasQueryFilter(Expression.Lambda(body, parameter));
            }

```
AND
IT
IS 
WORK

**Comment by DUWENINK** [comment]
> I try paste this code in the `OnModelCreating`
> 
> ```cs
>   //事实证明印度佬并不可靠
>             //在原来的 BaseConfiguration中的HasQueryFilter 已经无效了 
>             foreach (var entityType in modelBuilder.Model.GetEntityTypes()
>                .Where(e => typeof(ISoftDlete).IsAssignableFrom(e.ClrType)))
>             {
>                 modelBuilder.Entity(entityType.ClrType).Property<bool>("IsDeleted");
>                 var parameter = Expression.Parameter(entityType.ClrType, "e");
>                 var body = Expression.Equal(
>                     Expression.Call(typeof(EF), nameof(EF.Property), new[] { typeof(bool) }, parameter, Expression.Constant("IsDeleted")),
>                 Expression.Constant(false));
>                 modelBuilder.Entity(entityType.ClrType).HasQueryFilter(Expression.Lambda(body, parameter));
>             }
> ```
> 
> AND
> IT
> IS
> WORK

` ISoftDlete` is my interface with on poperty `bool Deleted`

**Comment by ajcvickers** [comment]
@DUWENINK Are you saying that this is now working for you?

**Comment by DUWENINK** [comment]
> @DUWENINK Are you saying that this is now working for you?

 paste this code in the OnModelCreating is work for you but the code in `BaseConfiguration<T> : IEntityTypeConfiguration<T> where T : BaseEntity` is not ,  `public virtual void Configure(EntityTypeBuilder<T> builder)
        {
       
            builder.HasQueryFilter(x => x.IsDeleted == false);
} ` this is not

**Comment by ajcvickers** [comment]
@DUWENINK There is too much ambiguity in the communication here. Please post a _small_, _runnable_, project that demonstrates clearly when run the issue you are having.

**Comment by DUWENINK** [comment]
> @DUWENINK There is too much ambiguity in the communication here. Please post a _small_, _runnable_, project that demonstrates clearly when run the issue you are having.

OKAY,IF I AM FREE I WILL SHOW YOU VIDEO

**Comment by DUWENINK** [comment]
> > @DUWENINK There is too much ambiguity in the communication here. Please post a _small_, _runnable_, project that demonstrates clearly when run the issue you are having.
> 
> OKAY,IF I AM FREE I WILL SHOW YOU VIDEO

sorry , i am busy recently

**Comment by ajcvickers** [comment]
@DUWENINK We don't need a video; we need code we can run.
