### ISSUE TITLE
Consider wrapping exceptions thrown from reading values of a value reader to provide column information

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1808]
With the introduction of the `DbSet<T>.FromSql()` customers can now supply their own SQL projections to our query pipeline, and so it becomes more likely that customers will make mistakes on those projections. We want the exceptions people get to be helpful if possible. We reviewed the SqlExceptions that you get when columns are missing and those already seem very good. 

If a column is of the wrong type though, it will currently throw an opaque InvalidCastException from the value reader (when we have more "strongly typed" value readers this could change to a different type coercion exception from the data reader). 

Hopefully we can wrap those exceptions with some information about the column that failed such as name and expected type. We should take into account how this affects performance.

**Comment by ajcvickers** [comment]
We did significant work in the materializer to improve bad data messages, which has also been of benefit in FromSql. Closing this since we don't think there is a lot of value in doing more.
