### ISSUE TITLE
error migration

### ISSUE THREAD

**Issue by killerangels** [dotnet/efcore#18107]
### Steps to reproduce

error happing when I will deploy

### Further technical details
![erro do kct](https://user-images.githubusercontent.com/17747049/65797618-10f59100-e146-11e9-8985-f423f36cdf59.png)

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
Duplicate of #17737

@killerangels - Can you share your project so we can reproduce the problem?

**Comment by killerangels** [comment]
dotnet tool install -g dotnet-ef

**Comment by killerangels** [comment]
Solved
