### ISSUE TITLE
Issue Running dotnet-ef database update on linux following 3.0 upgrade

### ISSUE THREAD

**Issue by Joseph-Anthony-King** [dotnet/efcore#18101]
I'm currently running the following version of EF Core 3.0 on Ubuntu 18.04:
```
Entity Framework Core .NET Command-line Tools
2.2.6-servicing-10079
```
I've upgraded dotnet core and dotnet-ef to 3.0 on my PC and my Linuxbox and everything if working fine on my PC but I'm getting an error when running the following on my Linuxbox:

```
$ dotnet-ef database update
The EF Core tools version '2.2.6-servicing-10079' is older than that of the runtime '3.0.0'. Update the tools for the latest features and bug fixes.
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```
I've looked online and can't find instructions on updating the EF Core tools... is this a bug or do the tools need an update?

Thank you

**Comment by smitpatel** [comment]
https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/

**Comment by bricelam** [comment]
@Joseph-Anthony-King Can you share the full `--verbose` output? It looks like something is going wrong during `Startup.ConfigureServices`...

**Comment by Joseph-Anthony-King** [comment]
Hi @bricelam, I just tried it again and it's working.  I'm still getting a message about the version but the database is being created.  Thanks!

**Comment by Joseph-Anthony-King** [comment]
FYI, I wasn't able to install version 3.0.0 until I uninstalled version 2.2.6.  I had to run the following commands:

```
$ dotnet tool uninstall --global dotnet-ef
Tool 'dotnet-ef' (version '2.2.6') was successfully uninstalled.
```
```
$ dotnet tool install --global dotnet-ef --version 3.0.0
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0') was successfully installed.
```
I'm no longer receiving the message!
