### ISSUE TITLE
After Core 3.0 upgrade, impossible to add-migration with EF Core 3.0

### ISSUE THREAD

**Issue by jpmaistrebazin** [dotnet/efcore#18100]
After upgrade core 3.0, it's impossible to add-migration in package manager.

### Steps to reproduce

``` 
Add-Migration AddRendezVousImage -Context OozymCrmContext
```
### Exception
>  PM> Add-Migration UpdateAlertTable -Context OozymContext System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.ProductInfo' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(Object reportHandler, IDictionary args) --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Activator.CreateInstance(Type type, Object[] args) at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language) at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor() at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute() at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.b__0() at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args) at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args) Exception has been thrown by the target of an invocation.

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
@jpmaistrebazin - You have mismatched version of packages. All the packages from EF Core (with relevant providers) should be targeting 3.0. Can you share your csproj?

**Comment by jpmaistrebazin** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Business\**" />
    <EmbeddedResource Remove="Business\**" />
    <None Remove="Business\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DataStore\OozymCrm\Migrations\20190603073631_GenerateAutoValues.cs" />
    <Compile Remove="DataStore\OozymCrm\Migrations\20190603073631_GenerateAutoValues.Designer.cs" />
    <Compile Remove="DataStore\OozymCrm\Migrations\20190603095621_AddConfigurationTable.cs" />
    <Compile Remove="DataStore\OozymCrm\Migrations\20190603095621_AddConfigurationTable.Designer.cs" />
    <Compile Remove="DataStore\OozymCrm\Migrations\20190603121831_UpdateConfigurationTable.cs" />
    <Compile Remove="DataStore\OozymCrm\Migrations\20190603121831_UpdateConfigurationTable.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="Refit" Version="4.7.51" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="3.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore">
      <HintPath>..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.identity.entityframeworkcore\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```

**Comment by roji** [comment]
Seems like you're including Microsoft.AspNetCore.Identity.EntityFrameworkCore twice, once as a package (version 3.0.0) and once via a direct assembly reference (version 2.2.0). Can you please remove the second reference?

**Comment by jpmaistrebazin** [comment]
I remove the reference of Microsoft.AspNetCore.Identity.EntityFrameworkCore but no changes, still same error

**Comment by GertArnold** [comment]
What about [this](https://github.com/aspnet/EntityFrameworkCore/issues/17849)?

**Comment by jpmaistrebazin** [comment]
Oh I find, I have a bad reference of Microsoft.AspNetCore.Identity.EntityFrameworkCore in linked project. Thks

**Comment by uditac** [comment]
Has somebody found the resolution to this? Cannot add the Add the migration to my EF core project
