### ISSUE TITLE
What to do with tracked entities when database is deleted

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#18103]
Repro is in https://github.com/aspnet/EntityFrameworkCore/issues/6872#issue-185523249

We add an entity, save it to database. Now entity is in change tracker.
Then database is recreated with EnsureDeleted/EnsureCreated
Same entity cannot be added again since it is still tracked.

**Comment by ardalis** [comment]
In particular, if in a test scenario you add one entity to an empty database, then delete it, then add another new entity, it blows up (using InMemory). Because both are assigned ID 1, which is being tracked.

**Comment by smitpatel** [comment]
We decided in triage that this is by design. If you delete your database in the middle of processing then your DbContext may not be usable. It would be fine pattern to initialize new DbContext or recreate database at very start of processing.

**Comment by ardalis** [comment]
Fair enough, thanks.
