### ISSUE TITLE
Migrations: Could we migrate ContextKey

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1810]
During app building I moved Identity migrations to a sub folder and changed the namespace of the context... which changes the full name we use as the ContextKey.

In EF6 this didn't happen because we hardcoded the key in configuration when you enabled migrations.

We could store this in the model snapshot and have a ChangeContextKey(oldKey, newKey) operation that we scaffold to update old keys. Then it just gets migrated along with all other stuff in the model.

**Comment by bricelam** [comment]
Closing. We decided to try removing ContextKey.
