### ISSUE TITLE
entry.Metadata.DefiningNavigationName is null in Owned

### ISSUE THREAD

**Issue by borisgr04** [dotnet/efcore#18117]
When entry.Metadata.IsOwned() is true sometimes
the property entry.Metadata.DefiningNavigationName is null. 

            ChangeTracker.DetectChanges();
            var entityEntrys = ChangeTracker.Entries().Where(p => p.State == EntityState.Added || p.State == EntityState.Deleted || p.State == EntityState.Modified);
            foreach (var entry in entityEntrys)
            {
                var auditEntry = new AuditEntry(entry, _userCurrent.DateOperation, _userCurrent.UserName, _userCurrent.Action, _userCurrent.Module, entry.State.ToString())
                {
                    TableName = entry.Metadata.Relational().TableName
                };

                
                if (entry.Metadata.IsOwned())
                {
		    //error 
                    string navigationName = entry.Metadata.DefiningNavigationName;

                    if (!auditEntry.TableName.EndsWith(navigationName))
                    {
                        auditEntry.TableName = auditEntry.TableName + "." + navigationName;
                    }

                }

### Steps to reproduce

When Debug the property xxxx present two escenarios:
**Case Ok 1**
**EntityType: Factura.BuyingAddress#Direccion**
  Properties: 
    FacturaId (no field, int) Shadow Required PK FK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 0 0
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
        SqlServer:ValueGenerationStrategy: IdentityColumn
    City (string) 1 1 -1 -1 -1
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping
    Street (string) 2 2 -1 -1 -1
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping
    Valor (decimal) Required 3 3 -1 -1 -1
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDecimalTypeMapping
  Keys: 
    FacturaId PK
  Foreign keys: 
    **Factura.BuyingAddress#Direccion {'FacturaId'} -> Factura {'Id'} Unique Ownership ToDependent: BuyingAddress**
  Annotations: 
    ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
    Relational:TableName: Facturas

**Case Not Ok:**
**EntityType: RubroEjecucion**
  Properties: 
    RubroId (no field, int) Shadow Required PK FK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 0 0
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
        SqlServer:ValueGenerationStrategy: IdentityColumn
    Certificado (decimal) Required 1 1 -1 -1 -1
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDecimalTypeMapping
    Compromiso (decimal) Required 2 2 -1 -1 -1
      Annotations: 
        Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDecimalTypeMapping
  Keys: 
    RubroId PK
  Foreign keys: 
    **RubroEjecucion {'RubroId'} -> Rubro {'Id'} Unique Ownership ToDependent: Ejecucion**
  Annotations: 
    ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
    Relational:TableName: Rubros

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 2.2)
Operating system:
IDE: (e.g. Visual Studio 2017 15.9.16)

**Comment by AndriySvyryd** [comment]
This is by design. DefiningNavigationName is only populated for entity types that share a CLR type (Direccion)

**Comment by borisgr04** [comment]
should be called address? How I do entity types that share a CLR type (Direccion)?

**Comment by AndriySvyryd** [comment]
@borisgr04 You can get it from `Metadata.FindOwnership().PrincipalToDependent.Name`
