### ISSUE TITLE
Using a Discriminator that is part of a composite key

### ISSUE THREAD

**Issue by sitepodmatt** [dotnet/efcore#18126]
Using EF Core 3.0 release. If we have an abstract base class of Animal and two empty dervied classes of Dog and Cat
```

class Animal
Name : String
TypeOfAnimal : String
Age : int
Parent : Animal?

class Dog : Animal
class Cat : Animal
```

And a defined database context of

            mb.Entity<Animal>().HasKey(x => new {x.Name, x.TypeOfAnimal});
            mb.Entity<Entity>().HasDiscriminator<string>(x => x.TypeOfAnimal);
            mb.Entity<Dog>().HasBaseType<Animal>();
            mb.Entity<Cat>().HasBaseType<Animal>();

With  Primary Key (Name, TypeOfAnimal) attempting to use TypeOfAnimal as a discriminator does not work correctly. 
The discriminator value is not populated automatically and .Parent is not resolved to the derived type but to the base type (lets presume that parent of a cat can be a dog).

Adding a supplementary TypeOfAnimal2 : String, not attached to any key, then discriminating on that works both on the fetched Animal and .Parent reference as expected.

Is this a design limitation or a bug?

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/dotnet/efcore/commit/3b67c3d9198cc540767b4d4eb6f5543b89b4dcb8
