### ISSUE TITLE
Migrations: Easy way to apply migrations for all contexts

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1813]
`> k ef migration apply` fails if you have more than one context, but when working with multiple contexts I'm finding it would be fine just to apply for all contexts (usually only one actually has pending migrations). This would save needing to type out `--context <my context name>` all the time. We could have a `--all` switch or it could just be the default of no context is specified (that would be my vote).

**Comment by rowanmiller** [comment]
__Triage:__ we should use `--all`

**Comment by ajcvickers** [comment]
Closing as we haven't seen significant demand for this feature. We could revisit this decision based on feedback and we would also consider a well-written community PR for it.
