### ISSUE TITLE
Where bool column needs to convert to equality when value converter is applied

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#18147]
```C#
        [ConditionalFact]
        public virtual void Where_bool_gets_converted_to_equality_when_value_conversion_is_used()
        {
            using (var context = CreateContext())
            {
                var query = context.Set<Blog>().Where(b => b.IsVisible).ToList();

                var result = Assert.Single(query);
                Assert.Equal("http://blog.com", result.Url);
            }
        }

b.Property(e => e.IsVisible).HasConversion(new BoolToStringConverter("N", "Y"));
```
Generates SQL
```SQL
SELECT "b"."BlogId", "b"."Discriminator", "b"."IsVisible", "b"."Url", "b"."RssUrl"
FROM "Blog" AS "b"
WHERE "b"."Discriminator" IN ('Blog', 'RssBlog') AND "b"."IsVisible"
```
It works for SqlServer since SqlServer converts everything to search condition explicitly so generates
```SQL
SELECT [b].[BlogId], [b].[Discriminator], [b].[IsVisible], [b].[Url], [b].[RssUrl]
FROM [Blog] AS [b]
WHERE [b].[Discriminator] IN (N'Blog', N'RssBlog') AND ([b].[IsVisible] = N'Y')
```

**Comment by smitpatel** [comment]
Also errors on Cosmos.

**Comment by smitpatel** [comment]
Work-around: Compare to true explicitly.
```C#
 var query = context.Set<Blog>().Where(b => b.IsVisible == true).ToList();
```

**Comment by roji** [comment]
Also errors on PostgreSQL :(

**Comment by lauxjpn** [comment]
> Also errors on PostgreSQL :(

Same goes for Pomelo.EntityFrameworkCore.MySql

**Comment by Xayton** [comment]
Hello, our project makes abundant use of `BoolToStringConverter` (making the suggested workaround unfeasible).
I'm in the process of evaluating the upgrade from EF Core 2.1 to 3.1, but this is a blocker issue for us.

I'd like to know why this is currently scheduled for 5.0 when, it seems, it's already fixed.
Even more if you consider that, if we wanted to wait for a LTS, we'd have to wait 2 years for EF Core 6.0.

Thank you very much
