### ISSUE TITLE
Owned entities cannot be tracked without their owner. exceptions when using inheritance

### ISSUE THREAD

**Issue by codehunter13** [dotnet/efcore#18143]
Since i use ef core 3.0 i get the following error:
 System.InvalidOperationException: A tracking query projects owned entity without corresponding owner in result. Owned entities cannot be tracked without their owner. Either include the owner entity in the result or make query non-tracking using AsNoTracking()

The situation:
abstract Entity1 with has an owned type
entity2 inherits entity1
entity3 inherits entity1

entity4 has a collection of entity2

when i query entity4 as tracking and i include the entity 2 collection  i got the error

The code was working in previous versions.

**Comment by smitpatel** [comment]
Duplicate of #18024
