### ISSUE TITLE
InMemory Compatibility with aspnetcore 2.2?

### ISSUE THREAD

**Issue by stefanhk31** [dotnet/efcore#18166]
Hi,

I'm trying to set up in-memory testing for my EF core database, and I can't install the InMemory package, because it's not compatible with netcoreapp2.2. I'm curious, is this intentional? Will there be a compatible version in the future? In the meantime, are there other options for setting up in-memory testing of an EF core database for a .NET core 2.2 app?

Thanks,

Stefan

**Comment by roji** [comment]
The newly-released version 3.0.0 indeed targets .NET Standard 2.1, and so is incompatible with netcoreapp2.2, [see the breaking change note](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#netstandard21) (this has nothing to do with the InMemory provider). However, you can use EF Core 2.2.6 which targets .NET Standard 2.0.
