### ISSUE TITLE
FreeText_through_navigation is broken

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#18199]
Also `FreeText_through_navigation_with_language_terms` and `Contains_through_navigation`

>  System.InvalidOperationException : The LINQ expression 'LastOrDefault<Employee>(Select<TransparentIdentifier<Employee, Employee>, Employee>(
        source: Where<TransparentIdentifier<Employee, Employee>>(
            source: LeftJoin<Employee, Employee, Nullable<uint>, TransparentIdentifier<Employee, Employee>>(
                outer: DbSet<Employee>, 
                inner: DbSet<Employee>, 
                outerKeySelector: (e) => Property<Nullable<uint>>(e, "ReportsTo"), 
                innerKeySelector: (e0) => Property<Nullable<uint>>(e0, "EmployeeID"), 
                resultSelector: (o, i) => new TransparentIdentifier<Employee, Employee>(
                    Outer = o, 
                    Inner = i
                )), 
            predicate: (e) => FreeText(
                _: (Unhandled parameter: __Functions_0), 
                propertyReference: e.Inner.Title, 
                freeText: "President") && FreeText(
                _: (Unhandled parameter: __Functions_0), 
                propertyReference: e.Outer.Title, 
                freeText: "Inside") && e.Outer.FirstName.Contains("Lau")), 
        selector: (e) => e.Outer))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Stack Trace: 
    QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& ) line 51
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 284
    RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 72
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 68
    Database.CompileQuery[TResult](Expression query, Boolean async) line 71
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 106
    <>c__DisplayClass9_0`1.<Execute>b__0() line 96
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) line 84
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 59
    QueryCompiler.Execute[TResult](Expression query) line 92
    EntityQueryProvider.Execute[TResult](Expression expression) line 79
    Queryable.LastOrDefault[TSource](IQueryable`1 source)
    DbFunctionsSqlServerTest.FreeText_through_navigation() line 175

**Comment by smitpatel** [comment]
Do we know which commit broke it?

**Comment by AndriySvyryd** [comment]
No idea, probably new query pipeline

**Comment by AndriySvyryd** [comment]
@ajcvickers Enabled it in aca49588a691c3b617502dcd8d67e5eb4b284558, but it was probably still broken

**Comment by smitpatel** [comment]
The test is doing LastOrDefault with order by so exception. New query pipeline identified badly written tests. :trollface:
