### ISSUE TITLE
Migrations: NullRef when no migration name supplied when adding a migrations (k cmd)

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1819]
`k ef migration add --context UnicornStoreContext`

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.ShowHelp(String commandName)
>    at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context, String startupProject)
>    at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass8_1.<Main>b__6()
>    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
>    at Microsoft.Data.Entity.Commands.Program.Main(String[] args)

Not sure if this is something we should be doing differently in our code or if it's a bug in the cmd line library we use.

**Comment by bricelam** [comment]
This is a dupe of #980 (Closed as fixed by @lukewaters)

**Comment by lukewaters** [comment]
I'll look into this

**Comment by rowanmiller** [comment]
I have beta4-12528 referenced (3 days old) and am seeing the issue

**Comment by lukewaters** [comment]
fixed in #1834
