### ISSUE TITLE
FromSqlRaw only accept ToList/ToListAsync() instead of First/FirstOrDefaultAsync

### ISSUE THREAD

**Issue by ciacco85** [dotnet/efcore#18205]
If the store procedure returns a single value like integer, FirstOrDefault throw an exception
I've tried all the possibile way described in the docs like raw, interpolated, with SqlParameter (checked the namespace in the last case to be Microsoft.Data.SqlClient instead of System.Data.SqlClient)

### Steps to reproduce
create a store procedure that return a single value like
SELECT Top(1) 1
FROM sys.tables 

create inside dbcontext

public DbSet<ReturnObject > EntityUsedBy { get; set; } 

with ReturnObject defined as follow

public class ReturnObject{
public int Return value {get;set;{
}

var result = await _dbContext.EntityUsedBy.FromSqlRaw("exec TestProcedure").FirstOrDefaultAsync();

actual workaround

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#fromsqlsproc

**Comment by robinwilson16** [comment]
The suggested fix does not work if you are working with stored procedures where a single item is returned.

After some trial and error I found this worked:
```
(await _context.Products.FromSqlInterpolated($"EXEC GetProducts").ToListAsync()).FirstOrDefault();
```
