### ISSUE TITLE
Throw better exception for Last without order by

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#18211]
Currently it throws error as ran into client eval. It would be more useful to say that Last is used without order by.

This line should throw exception rather than returning null. (Returning null throws client eval message.

https://github.com/aspnet/EntityFrameworkCore/blob/d005f540471db0b891efb6fdc1cc0c6fc3b21657/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs#L543-L546

Also cosmos does not verify for ordering before LastOrDefault. Should probably do that too.

**Comment by ajcvickers** [comment]
Moving from the backlog to consider for 5.0. This message is very confusing when the real issue is a lack of ordering.
