### ISSUE TITLE
[question] Expression Rewriting

### ISSUE THREAD

**Issue by sitepodmatt** [dotnet/efcore#18244]
We currently have an expression rewriter (using ExpressionVisitor) that takes the predicate or selector and converts it to something EF can understand using our EAV model... 

e.g. queryable.Where(EFHelpers.Rewrite(e => e.name = "matt")));

We have this working nicely now, its ugly to have to wrap every expression. Is there a way to intercept expressions without this explicit wrapping each time or something like dbContext.ExpressionVisitor = ourVisitor ?

**Comment by ajcvickers** [comment]
Putting this on the backlog to consider adding hooks for this. However, there are different places in the pipeline where visitors can run, and different constraints/requirements for each place, so it is not trivial to create a pit-of-success for such extensibility.

**Comment by ajcvickers** [comment]
Covered by #19748
