### ISSUE TITLE
IDesignTimeDbContextFactory does not work in 3.0

### ISSUE THREAD

**Issue by yunfandev** [dotnet/efcore#18247]
I implement interface IDesignTimeDbContextFactory<TContext> in the startup project, but the dotnet ef tools seems first invoking Program.CreateHostBuilder() if failed then try to use design-time factory. 😂😂😂

### Further technical details

EF Core version: 3.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@bricelam to respond.

**Comment by bricelam** [comment]
There are two phases:
1. Discover all the DbContext types so we can find the one you passed to `--context`
2. Instantiate the DbContext

Phase 1 looks everywhere--assemblies, the service provider, and even contexts referenced in attributes.

Phase 2 will always use the IDesignTimeDbContextFactory if it's available. If not it will try to get an instance from the service provider. If it can't it will use the parameterless constructor.

**Comment by bricelam** [comment]
This did not change in 3.0. Are you having issues with something that used to work on 2.x?

**Comment by yunfandev** [comment]
Thanks for your answer, since I only used one DbContext in 2.2, I didn't pay attention to every time Program.CreateHostBuilder() was called. I added multiple DbContext in 3.0 but did not specify the --context parameter when executing the dotnet ef command.😅😅😅

I added a command-line output in both Program.CreateHostBuilder() and IDesignTimeDbContextFactory.CreateDbContext(), then I found that Program.CreateHostBuilder() is called every time I execute dotnet ef command, this is inconsistent with the behavior I read from the [documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#from-a-design-time-factory), so I thought maybe this was a bug. 😅😅😅

> If a class implementing this interface is found in either the same project as the derived DbContext or in the application's startup project, the tools bypass the other ways of creating the DbContext and use the design-time factory instead.
