### ISSUE TITLE
ExecuteSqlInterpolated and ExecuteSqlInterpolatedAsync do not work with variable schema, table and property name

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#18243]
The following query does not work although interpolated sql string is valid:

`await _dbContext.Database.ExecuteSqlInterpolatedAsync($"Delete From [{schema}].[{tableName}] Where {primaryKeyName} = {primaryKeyValue}"); // This does not work` 

and throws the following exception:

> Invalid object name '@p0.@p1'.

If I execute the above interpolated string with `ExecuteSqlRaw` and `ExecuteSqlRawAsync` as follows it works gracefully:

```
var deleteCommand = $"Delete From [{schema}].[{tableName}] Where {primaryKeyName} = {primaryKeyValue}";
await _dbContext.Database.ExecuteSqlRawAsync(deleteCommand);  // This works
```

Am I missing anything in case of `ExecuteSqlInterpolated` and `ExecuteSqlInterpolatedAsync` and this is a just a critical bug?

**Comment by Shane32** [comment]
ExecuteSqlInterpolatedAsync replaces variables with SQL parameters to prevent SQL injection attacks.  So the executed SQL would look something like the following.

```Delete FROM [@p0].[@p1] Where @p2 = @p3```

Since SQL does not allow variables to contain member names like the schema, tableName, or primaryKeyName, the above SQL is invalid.  You would need to use ExecuteSqlRawAsync for your purpose, embedding the schema, tableName, and primaryKeyName directly into the SQL as shown in your example.  The primaryKeyValue could be a parameter.

**Comment by ajcvickers** [comment]
@TanvirArjel When you say that "`ExecuteSqlRaw` and `ExecuteSqlRawAsync` as follows it works gracefully" are you aware that you're creating non-parameterized queries which are potentially susceptible to SQL injection attacks? Or are you mitigating this in some other way?

**Comment by TanvirArjel** [comment]
@ajcvickers 

> are you aware that you're creating non-parameterized queries which are potentially susceptible to SQL injection attacks?

Yes! I am fully aware of that. In my case it will a problem because only value, primary  key which is a long value taking from the user input.

That's not the issue. Issue is why the following query does not work:

> await _dbContext.Database.ExecuteSqlInterpolatedAsync($"Delete From [{schema}].[{tableName}] Where {primaryKeyName} = {primaryKeyValue}");

**Comment by ajcvickers** [comment]
@TanvirArjel Because, as @Shane32 pointed out, it's not valid  SQL. The schema name and table name cannot be parameterized.

**Comment by TanvirArjel** [comment]
@ajcvickers That means the scope of `ExecuteSqlInterpolated` and `ExecuteSqlInterpolatedAsync` are very limited.

**Comment by ajcvickers** [comment]
@TanvirArjel Not sure exactly what you mean. It's limited by what T-SQL on SQL Server supports.

**Comment by acpt** [comment]
building a big update string, we cant split it on code....

**Comment by LucaZiegler** [comment]
> ExecuteSqlInterpolatedAsync

Npgsql.PostgresException: '42601: syntax error at or near "["
