### ISSUE TITLE
[Question] What is the replacement for this is EF Core 3.0?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#18245]
TIA!

        public override string GetDependentEndCandidateNavigationPropertyName(IForeignKey foreignKey)
        {
            var originalSchema = foreignKey.PrincipalEntityType.Scaffolding().Schema;

**Comment by ajcvickers** [comment]
```C#
var originalSchema = foreignKey.PrincipalEntityType.GetSchema();
```
