### ISSUE TITLE
Question - EF Core 3.0 Async Client Evaluation

### ISSUE THREAD

**Issue by jarrodAwesemo** [dotnet/efcore#18262]
As of now this code will work in EF 3.0 because I'm 'opting in' to client evaluation by calling AsEnumerable().  I'd like to await this call to the database but if I use 'AsAsyncEnumerable' I can't use the GroupBy.  How would I convert this code so that it runs asynchronously?

          var result = (from fo in db.FutureOutcomes
                        .Where(x => x.FutureEvent.League == league).AsEnumerable()
                    group fo by new {fo.OfferId, fo.Site, fo.Name}
                    into g
                    select g.OrderByDescending(t => t.CreatedDate).FirstOrDefault()).ToList();

Thanks.

**Comment by smitpatel** [comment]
BCL provides IAsyncEnumerable but it does not provide any methods (like GroupBy) over that. Probably question for corefx & LINQ team.

**Comment by dasMulli** [comment]
You can add a reference to the NuGet package `System.Linq.Async` which is built from https://github.com/dotnet/reactive to provide async grouping logic for IAsyncEnumerable.
