### ISSUE TITLE
EF Core transition guidance for .Net Framework Applications impacted by new .Net Standard 2.1 requirement

### ISSUE THREAD

**Issue by dazbradbury** [dotnet/efcore#18276]
We were in the process of upgrading our DAL to EF Core, within an existing large .Net Framework (MVC) application. All was going well, and we'd put significant effort into this migration with the view that it was a stepping stone to a potential full .Net Core migration later.

With the latest release of EF Core, it seems we're now stuck with no path to continue:

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#netstandard21

So now we have a .Net Framework application, that uses EF Core 2.2 with a multitude of issues (alongside our legacy DAL):

https://github.com/aspnet/EntityFrameworkCore/issues/11711
https://github.com/aspnet/EntityFrameworkCore/issues/15386
https://github.com/aspnet/EntityFrameworkCore/issues/1824

These issues (and others raised by different teams) are being fixed in EF Core 3+. 

Our assumption is that: 

- EF Core 2.2 is no longer being developed, with all changes happening to current / future versions, and thus requiring .Net Standard 2.1. Thus staying on the EF Core 2.2 path seems a dangerous one.
- EF Core 3+ will never support .Net Standard 2
- .Net Framework won't support .Net Standard 2.1

And as such, there is no sensible way to migrate the DAL separately to a full move to .Net Core - and our attempt to do so was naive to rely on the fact that EF Core supported .Net Standard 2. 

Do you have a recommended upgrade path for us? Or a planned upgrade path we can wait for to continue down the EF Core DAL replacement path? 

Or should we be going to EF 6.3 instead, before we can move to .Net Core fully? 

Apologies to create this a GH issue - however it seems there is no guidance on what existing projects are meant to do when it comes to migration paths (or at least, we failed to find it). Your assistance is appreciated.

**Comment by ajcvickers** [comment]
@dazbradbury I don't have a good answer for you. The decisions to not have .NET Framework implement .NET Standard 2.0, and for EF Core to target .NET Standard 2.1 were made by the .NET leadership team. However, issue #18141 is tracking adding back something in 3.1 that would make this possible; please up-vote that issue. Whether or not #18141 gets implemented will depend on both the results of prototyping and support from .NET leadership.
