### ISSUE TITLE
Ambiguous functions usage in EF Core 3.0

### ISSUE THREAD

**Issue by sdanyliv** [dotnet/efcore#18279]
Hi,

Found this when creating project which uses two different providers and trying to share model and queries.

### Steps to reproduce
Include in one project `Pamelo.EntityFramweorkCore.MySql` (preview) and `Microsoft.EntityFrameworkCore.SqlServer` packages

Then try to use in LINQ Query DateTime functions, for example `EF.Functions.DateDiffYear(...)`
```cs
var query = from p in ctx.Products
    select new
    {
	DiffYear = EF.Functions.DateDiffYear(p.SellStartDate, p.SellEndDate)
    }
```
As result we have ambiguous functions usage. So we can not use DB Functions when they are defined in both providers under same namespace `Microsoft.EntityFrameworkCore`. 

Same collision was found when EF Core deprecated `ForSqlServerUseSequenceHiLo` and replaced with `UseHiLo` - here we have collision with `Npgsql.EntityFrameworkCore.PostgreSQL`

Question: It is by design?

For sure we can use extensions directly `SqlServerDbFunctionsExtensions.DateDiffYear(...)` but it breaks sharing queries between providers. 

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer + Pamelo.EntityFramweorkCore.MySql
Target framework: NET Core 3.0
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2019 16.3.2

**Comment by ajcvickers** [comment]
@sdanyliv This is by-design; it's uncommon for code to use multiple relational providers in the same app. Where this is the case then using the extension class name is the way to go.

I'm not sure what you mean by, "but it breaks sharing queries between providers." Nothing has changed that would impact the ability to "share queries between providers", unless these queries were previously using functionality defined in the wrong provider, which may have worked accidentally, but certainly wasn't by-design or a robust way of doing things.
