### ISSUE TITLE
Upgrade to .Net Core 3.0 - dotnet ef is missing

### ISSUE THREAD

**Issue by Pilchie** [dotnet/efcore#18282]
_From @ckruegerkpmg on Tuesday, October 8, 2019 8:38:52 AM_

# After Upgrades to .Net Core 3.0 dotnet ef is missing

# General

After upgrading Visual Studio 2019 from 16.0/16.1/16.2 to 16.3 .Net Core get's upgraded to 16.3
All Projects that are useing Entitfy Framework are failing.

This helps: dotnet tool install --global dotnet-ef
BUT
global didn't install dotnet-ef for the machine globally, only for the user account.
A build Agent typically doesn't run in the same identity than the user that is installing Visual Studio.

It's very annoing that .Net Core 3 installation prevent building .Net Core 2.x Code in it's default installation.

_Copied from original issue: dotnet/core#3570_

**Comment by Pilchie** [comment]
_From @scalablecory on Tuesday, October 8, 2019 6:09:15 PM_

@Pilchie @livarcocc

**Comment by ChaseKR** [comment]
I'm having this same issue as I'm trying to add this to my ,NET Core 3.0/2.2 apps - see #18276

**Comment by bricelam** [comment]
You can also use a `global.json` file to continue using the 2.2 SDK in the project:
```json
{
  "sdk": {
    "version": "2.2.402"
  }
}
```

**Comment by bricelam** [comment]
(The 2.2 SDK includes `dotnet ef` so it should work as it used to without the need to install it separately)

**Comment by ChaseKR** [comment]
Thank you @bricelam - seems to be working for my builds!
