### ISSUE TITLE
UWP Error in creating DB File in resilient storage / user data storage - mandatory for critical data

### ISSUE THREAD

**Issue by msavazzi** [dotnet/efcore#18288]
There is a critical issue in UWP and SQLite that is not mentioned and I was not able to solve: what if the data in the SQLite is critical and should not be bound to the sandbox but must survive the App?
From all the test I did I was NOT able to create the SQLite database file in the "Documents Folder" of the user.
Reading from MS documentation UWP application should NOT address directly the files/folders but use StorageFolder and Storage FIle
(references: https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder
https://blogs.msdn.microsoft.com/wsdevsol/2012/12/04/skip-the-path-stick-to-the-storagefile/)
Even if I've configured correctly all the File access properties and bindings
(https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-capability)
In fact I'm able to enumerate and read the file in the Library I'm not able to perform the SQLiteConnection
`Using db As SqliteConnection = New SqliteConnection("Filename=" ...))`
No matter what I try to do there.
I've found a document "Using SQLite Databases in Any Folder in WinRT" (https://www.codeproject.com/Articles/879846/Using-SQLite-Databases-in-Any-Folder-in-WinRT) that explains it is not possible from SQLite3 but has to do with custom/not supported code.
If this si true is a critical issue as my application handles very critical data that must not be deleted in the case of an app removal.
So I must be able to have the db file in a statefull storage outside of the sandbox and I would even put it in an OneDrive folder.
A workaround that is not feasible in terms of performance would be perform a file copy from the sandbox app storage location to the documents folder.
On the other side I tried to use SQL Server LocaDB (https://blogs.msdn.microsoft.com/jerrynixon/2012/02/26/sql-express-v-localdb-v-sql-compact-edition/) but I received an error that is NOT supported for UWP. In fact this section only mentions to connect with a SQL Server.
So how I can I solve the critical issue I face?
Am I doing something wrong? is it possible to have a code sample of an UWP app opening the data from a file in the User/Documents folder?
Also note that several articles mention that LocalDB is for single use only and not production and that for real app SQLExpress should be used... but this raises the issue on how to distribute SQLExpress within an UWP app or automatically install it as prerequisite in the distribution via marketplace.
So again is not a feasible solution. The best is to have SQLite with the DB file in a user folder.

As suggested in other forums copying the file after the connection is closed is NOT an acceptable solution for a real application as it opens several critical issues:
1) overhead of read/writes. For relevant data EVERY database modification (insert/update/delete) must result in a file copy. This doubles the I/O (read file / write file) Also it requires to create some "new" close method to perform every time a close is after an update of the db to copy it.
2) the copy function should be async in UWP this opens up to critical paths where while the file is still being copied the app can update the data creating a clash. How you solve that? 
3) it create a failure point because if the app crashes/machine crashes between file update and end of file copy you end up with 2 inconsistent files. 
4) how you manage the "restore" of the file? For any reason you have to uninstall/reinstall the app so the file in local storage is destroyed, how you can recover the existing copy? (copy back?) how you ensure is working and the real latest? 
5) what do you do if the copy fails? a DB must be transactional (SQLite IS transactional) so in the scenario where you do the db update -> copy -> copy fails how you manage the db rollback? is impossible as the transaction is already ended! otherwise you cannot close the db connection and copy the file.

Overall, as is, is not an acceptable solution for a production grade application that must support resilient data.

### To Reproduce

1) create UWP project
2) add SQLite nuget packages 3.0
3) add properties for app to access Documents Library
4) add file picker to create file in Documents Library
5) add connection open to db: Using db As SqliteConnection = New SqliteConnection("Filename=" ...))

It will always fail as the outcome of the FilePicker is a StorageFile not a filename

### Additional context

Microsoft.Data.Sqlite version: tried all possible version and nuget packages both from SQLite team and from Microsoft
Target framework: .NET Core 3.0 - NO EF (wanted to use MVVM and LINQ but I'm not able to open the DB so that is not impacting)
Operating system: Windows 10 1903

**Comment by ajcvickers** [comment]
@bricelam to follow up.

**Comment by bricelam** [comment]
> A workaround that is not feasible in terms of performance would be perform a file copy from the sandbox app storage location to the documents folder.

This is the correct workaround for SQLite. Issue https://github.com/ericsink/SQLitePCL.raw/issues/287 is about trying to improve this.

> I tried to use SQL Server LocaDB but I received an error that is NOT supported for UWP

I believe this should work once you enable connections to localhost: https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx#enable_loopback_for_network_access

I agree the whole situation sucks. You might be able to use the Windows 10 Feedback Hub app to reach out to the UWP team to see if they have any additional recommendations.

**Comment by msavazzi** [comment]
> A workaround that is not feasible in terms of performance would be perform a file copy from the sandbox app storage location to the documents folder.
> 
> This is the correct workaround for SQLite. Issue ericsink/SQLitePCL.raw#287 is about trying to improve this.

In reality is much trickier, as I wrote this path opens to multiple complex situation, critical paths. Example 1: What if the transaction is successful and the copy is not?
Example 2: What happens if the file is being copied and an update query update is started? the query will fail as the file is locked? or what?


> 
> I tried to use SQL Server LocaDB but I received an error that is NOT supported for UWP
> 
> I believe this should work once you enable connections to localhost: https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx#enable_loopback_for_network_access

I will give it a try but it leaves open the question of how to distribute MSQL Server LocalDB files together with the UWP

> I agree the whole situation sucks. You might be able to use the Windows 10 Feedback Hub app to reach out to the UWP team to see if they have any additional recommendations.
I'll try again

**Comment by ajcvickers** [comment]
@msavazzi Can you point us to where "UWP says is not their problem?"

**Comment by msavazzi** [comment]
> @msavazzi Can you point us to where "UWP says is not their problem?"

check here: https://developercommunity.visualstudio.com/content/problem/767598/uwp-and-statefull-critical-data-in-sqlite-or-db.html

am I wrong?

M

**Comment by ErikEJ** [comment]
You could use SQL Server Express! I guess the issue with localdb is that it only supports named pipe connections.

**Comment by msavazzi** [comment]
From Microsoft documentation is not possible
 In any case can you provide a working example?
Also how you distribute sqlexpress with yep app in the store?

**Comment by ErikEJ** [comment]
>> From Microsoft documentation is not possible
Where do you see that - I see this: https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases (with a working example)

>> Also how you distribute sqlexpress with yep app in the store?

You dont, but you document how and advise your users that they must have certain requirements installed.

**Comment by msavazzi** [comment]
> From Microsoft documentation is not possible
> 
> 
> Where do you see that - I see this: https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases (with a working example)
> 
Thank ErikEJ, I've read those pages as they are together with the SQLite ones.
But if you check: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15

you can read 

>  is a feature of SQL Server Express targeted to developers. It is available on SQL Server Express with Advanced Services.

so is NOT a version for deployment

> 
> Also how you distribute sqlexpress with yep app in the store?
> 
> 
> You dont, but you document how and advise your users that they must have certain requirements installed.

I'm not sure the Microsoft Store allows to deploy applications that cannot work if a "desktop" application is not installed.
Also the App store mechanism does not allow to execute MSI... 
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d25f290b-59bd-4d13-86fe-c3f3a9e54aee/official-localdb-redistribution-license?forum=sqlexpress#0d59a6d3-7014-4d8f-b207-b891e8e9230e

**Comment by ErikEJ** [comment]
I think you are confused. LocalDB is not the same as SQL Server Express! SQL Server Express allows TCP connections, as demonstrated in the article

**Comment by ErikEJ** [comment]
So you are wrong, yes!

**Comment by msavazzi** [comment]
I'm not wrong, please read the articles I posted, everything is explained quite precisely. LocalDB is a special version of SQLExpress that works on a file. Is installed as part of SQLExpress. It is not meant for distribution but for development.
In any case I asked you to provide me  (everyone) a working solution with LocalDB even starting from the sample in the page, if you're right it should not be difficult to have ti working. I tried and I was not able to have it working.

If you're able to have it working with localDB it could be a workaround to the issue on SQLite not a solution as LocalDB cannot be distributed within UWP apps while SQLite can.
The issue remains.

**Comment by ErikEJ** [comment]
I give up...

**Comment by msavazzi** [comment]
> So you are wrong, yes!

check here:
https://www.microsoft.com/en-us/sql-server/sql-server-editions-express

SQL Server 2017 Express LocalDB
Embed SQL Server Express into applications with LocalDB—a lightweight version of the Express edition. **Available for free as an option when downloading SQL Server 2017 Express**.

**Comment by msavazzi** [comment]
> I give up...

don't give up :) 
help us with a working solution.

**Comment by ErikEJ** [comment]
As I said earlier: Use SQL Server Express, not SQL Server Express LocalDB. 

And for a sample, look at the link I gave you earlier to Microsoft Docs!

**Comment by ErikEJ** [comment]
In particular, look at this part: https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases#trouble-connecting-to-your-database

**Comment by msavazzi** [comment]
Ok, understood, will try

**Comment by ajcvickers** [comment]
@msavazzi I commented on the UWP issue pointing out that this is a UWP issue rather than a SQLite/EF issue.

**Comment by msavazzi** [comment]
> @msavazzi I commented on the UWP issue pointing out that this is a UWP issue rather than a SQLite/EF issue.

Thank you for that but they closed the issue so I think no one will ever read it :( I'm extremely disappointed from their behavior. Do you have any chance to get in touch with them directly or involve them here? or re open the issue? I tried but with no luck :(

**Comment by ajcvickers** [comment]
@msavazzi I will try.

**Comment by ajcvickers** [comment]
Closing this here. Will re-open if anything actionable comes back from UWP.
