### ISSUE TITLE
I hope EF7 will be able to support DB First or Model First

### ISSUE THREAD

**Issue by xiluo** [dotnet/efcore#1828]
I Love EF very much,  We use it with DB First in my work . From a China developers.

**Comment by vossad01** [comment]
If you have not already, you may be interested in reading the the article, [*EF7 - What Does “Code First Only” Really Mean*](http://blogs.msdn.com/b/adonet/archive/2014/10/21/ef7-what-does-code-first-only-really-mean.aspx), for more information on the plans.

**Comment by rowanmiller** [comment]
The blog post that @vossad01 linked to has details on what we are supporting. Generating from an existing database will be supported (some early code is already checked in for this) but the EDMX file format will not be.
