### ISSUE TITLE
Clarify parameter naming when using raw SQL

### ISSUE THREAD

**Issue by appelon** [dotnet/efcore#18291]
Constructing using parameterization with SqlParameter like this:

```C#
var paramDefinition = new SqlParameter("DefinitionId", System.Data.SqlDbType.UniqueIdentifier).Value = definitionId.ToString();
var query = $"SELECT * FROM [dbo].[{table}]";
var queryResult = await context.Blogs.FromSql($"{query} WHERE DefinitionId = @DefinitionId", paramDefinition).FirstOrDefaultAsync();
```
It will generate an error stating that it hasn't declared @DefinitionId.

It looks like you can disregard the specified parametername in SqlParameter as EF expects you to specify the paramters like @p0, @p1, etc:

```C#
var paramDefinition = new SqlParameter("DefinitionId", System.Data.SqlDbType.UniqueIdentifier).Value = definitionId.ToString();
var query = $"SELECT * FROM [dbo].[{table}]";
var queryResult = await context.Blogs.FromSql($"{query} WHERE DefinitionId = @p0", paramDefinition).FirstOrDefaultAsync();
```

Can you verify - or clarify what I did wrong in the first codesnip?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Muppets** [comment]
I had to test this locally as it looked right to me until I spotted:

`var paramDefinition = new SqlParameter("DefinitionId", System.Data.SqlDbType.UniqueIdentifier).Value = definitionId.ToString();`

You are setting the SqlParameter value on the same line as the paramDefinition declaration. This causes the paramDefinition variable to contain the int value 1, not the SqlParameter.

Changing it to the below fixes the issue:

`var paramDefinition = new SqlParameter("DefinitionId", System.Data.SqlDbType.UniqueIdentifier);
paramDefinition.Value = definitionId.ToString();`

From my testing locally, EF is doing everything right with parameters.
