### ISSUE TITLE
Cannot build the solution and throws "Architecture Debu|MCD is invalid"

### ISSUE THREAD

**Issue by andresff** [dotnet/efcore#18305]
I tried to build the solution using the build.cmd but all the time I was getting the exception "". After a lot of research I found the culprit. My computer is HP and by default sets an environment variable called **Platform** and the build process relies heavily on this variable.

**Solution**
Add the line `SET Platform=` to build.cmd file.

Also there is an issue reported in the Nuget Repo about this issue https://github.com/NuGet/Home/issues/4882

The same changes need to be applied to restore.cmd and test.cmd.

I have the solution in this branch [https://github.com/andresff/EntityFrameworkCore/tree/issue18305](https://github.com/andresff/EntityFrameworkCore/tree/issue18305) and can do a PR if you want it.

### Steps to reproduce

1. Set an environment variable called **Platform** to **build.cmd** file before executing the powershell command.
`SET Platform=MCD`
2. run `build.cmd`

>   Restore completed in 4,75 sec for C:\Users\andres\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj.
> Architecture not supported. If you think this is a bug, report it at https://github.com/dotnet/cli/issues
> System.Management.Automation.RuntimeException: Architecture not supported. If you think this is a bug, report it at https://github.com/dotnet/cli/issues
> at Get-CLIArchitecture-From-Architecture, C:\Andres\EntityFrameworkCore\.dotnet\dotnet-install.ps1: line 169
> at <ScriptBlock>, C:\Andres\EntityFrameworkCore\.dotnet\dotnet-install.ps1: line 536
> at InstallDotNet, C:\Andres\EntityFrameworkCore\eng\common\tools.ps1: line 198
> at <ScriptBlock>, C:\Andres\EntityFrameworkCore\eng\common\dotnet-install.ps1: line 18
> at <ScriptBlock>, <No file>: line 1
> C:\Users\andres\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\InstallDotNetCore.targets(15,5): error : dotnet-install failed [C:\Users\andres\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj]

> C:\Andres\EntityFrameworkCore\All.sln.metaproj : error MSB4126: The specified solution configuration "Debug|MCD" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Andres\EntityFrameworkCore\All.sln]

> Build FAILED.

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
@aspnet/build

**Comment by andresff** [comment]
@smitpatel  that "build"part comes from AspNetCore-Tooling repo?

**Comment by dougbu** [comment]
> that "build"part comes from AspNetCore-Tooling repo?

No. @smitpatel was asking for members of that team to respond. So, here I am 😺 

This seems like an odd corner case but setting the environment variable should be fine and won't interfere with using `-platform {some platform}` on one of the command lines.

I suggest fixing this in https://github.com/dotnet/arcade/blob/master/eng/common/build.ps1 and perhaps https://github.com/aspnet/EntityFrameworkCore/blob/master/startvs.cmd (and similar files in other ASP.NET Core repos) would help building / testing / &hellip; far more repos than what you've done in andresff/EntityFrameworkCore@56934b5a9a5c. If @markwilkie agrees, please open a PR in the dotnet/Arcade repo. @markwilkie❔

Many thanks.

**Comment by andresff** [comment]
@dougbu  thanks for your fast response.

As I've tested it, it doesn't need to be added that to starvs.cmd. I mean, I've ran the `startvs.cmd All.sln` without any change and **build solution** worked just fine.

I'll look at dotnet/arcade repo to provide a fix.

**Comment by andresff** [comment]
After some days, I digged in the problem to seek where it was causing this. I wrote a fix in the  dotnet/arcade repo as @dougbu suggested. You can check it out https://github.com/andresff/arcade/tree/fixPlatformEnvVar and if it's a valid solution I can make a pull request or if you need to create an issue on that repo I'll do it too.

**Comment by ErikEJ** [comment]
Why not do a PR?

**Comment by andresff** [comment]
@ErikEJ as @dougbu wrote ... I was waiting the approval of @markwilkie to submit a PR

**Comment by ErikEJ** [comment]
Approval? Is it not OSS??

**Comment by andresff** [comment]
@ErikEJ done at https://github.com/dotnet/arcade/pull/4154.

Thanks to everyone!

**Comment by dougbu** [comment]
My apologies, my wording was poor earlier and I should not have implied anyone's approval was necessary to open a PR.
