### ISSUE TITLE
Alternative for parallel execution of DbQuery

### ISSUE THREAD

**Issue by Flogex** [dotnet/efcore#18309]
In EF Core 2.2 it was possible to execute read-only queries in parallel on the `DbQuery` property of a single `DbContext`.

```cs
class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
}

class TestContext : DbContext
{
    public DbQuery<Person> People { get; set; }
}

static class Program
{
    private static async Task Main()
    {
        using (var ctx = new TestContext())
        {
            Task<string[]> task1 = Query1(ctx);
            Task<int[]> task2 = Query2(ctx);

            await Task.WhenAll(task1, task2);

            IEnumerable<(string, int)>people = task1.Result.Zip(task2.Result);
        }
    }

    private static Task<string[]> Query1(TestContext ctx) => ctx.People.Select(x => x.Name).ToArrayAsync();
    private static Task<int[]> Query2(TestContext ctx) => ctx.People.Select(x => x.Age).ToArrayAsync();
}
```

This sample works fine using EF Core 2.2.6, but throws an `InvalidOperationException` in version 3.0.0: "A second operation started on this context before a previous operation completed." Besides, `DbQuery<T>` is deprecated now.

Is there any alternative to execute read-only queries in parallel on the same context in EF Core 3.0?

**Comment by ajcvickers** [comment]
@Flogex This was not safe in 2.2.6; you are lucky not to have run into issues. The context is not thread-safe; multiple concurrent calls should not be made in parallel.
