### ISSUE TITLE
SQL error in scaffolding existing database

### ISSUE THREAD

**Issue by jhwelz** [dotnet/efcore#18314]
Receiving an error "Arithmetic overflow error converting expression to data type bigint." while running the scaffolding process. 

(dotnet ef dbcontext scaffold "data source=DBNAME;Initial Catalog=CAT_NAME;User Id=USER;Password=PWD;" Microsoft.EntityFrameworkCore.SqlServer --context NameDBContext --force --json --verbose)

It occurs at the point the "Found table with name:" usually starts to be listed...

Verbose log attached.

This database has been through the ringer in its lifetime (converted multiple times, etc), so I'm sure it's something in that.  How does one debug SQL errors in this process? Is there available documentation where users can figure out what it is doing at certain points in the process?

Thanks.

[Verbose Log.txt](https://github.com/aspnet/EntityFrameworkCore/files/3712882/Verbose.Log.txt)

**Comment by smitpatel** [comment]
Can you share Sql for the Sequences you have in your database?

**Comment by smitpatel** [comment]
We try to read certain values as int/long
https://github.com/aspnet/EntityFrameworkCore/blob/e2ff7d81b2617c6e5326a542c976c9d5356aecf3/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L386-L389

But their data type is sql_variant on server. https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-sequences-transact-sql?view=sql-server-2017

**Comment by jhwelz** [comment]
Thanks for the input. I think that may be the issue. The maximum_value was
set to a higher number than the max size of the BigInt...

Thanks,
Joe Welz

**Comment by andyh1213** [comment]
Is there a workaround to this? I am trying to scaffold just a few tables in the database and don't need sequences for this project, but I can't drop or alter them from the database.

**Comment by jhwelz** [comment]
It's been a while but I believe I altered the sequence to have a max value
less then the largest bigint (999999999)... Then scaffolded again.

**Comment by ErikEJ** [comment]
@bricelam Would the fix for this be to set very high valuesto long.MaxValue ? (Considering a PR)

**Comment by bricelam** [comment]
My first thought was to always cast to bigint in the SQL and then just read long values. But yeah, if it’s bigger than long.maxvalue that seems like a good solution

**Comment by andyh1213** [comment]
Thanks. I ended up dropping those sequences temporarily from the database (actually, my DBA did that) and then putting them back after running the scaffolding. Tried specifying just the few tables that I needed with -Tables, but still got the same error. I don't need those sequences in Entity, so kind of a pain to have to do that each time the scaffolding might need to be regnerated, but it works.
