### ISSUE TITLE
Custom translation with SqlFunctionExpression puts the function name between quotation marks

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#18312]
```C#
public static class DB {
	public static decimal? Nvl(decimal? a, decimal? b) {
		throw new Exception();
	}
}
```
```C#
modelBuilder
.HasDbFunction(typeof(DB).GetMethod(nameof(DB.Nvl)))
.HasTranslation((exps) => new SqlFunctionExpression("nvl", typeof(decimal?), exps));
```
```C#
ctx.TestTable.Select(z => DB.Nvl(1, 2)).First();
```
This gets translated to:
```SQL
SELECT "nvl"(1.0, 2.0)
FROM "TEST_TABLE" "z"
FETCH FIRST 1 ROWS ONLY
```
Which throws an exception:
`Oracle.DataAccess.Client.OracleException : ORA-00904: "nvl": invalid identifier`
The problem is that "nvl" is between quotation marks. Why is this happening and how can I get rid of the quotation marks?

The documentation for HasTranslation points to https://go.microsoft.com/fwlink/?linkid=852477 but this link just redirects to https://docs.microsoft.com/en-us/ef/core/modeling/ instead of anything specific to function translation.

I am able to work around this by creating my own FunctionExpression class instead of using SqlFunctionExpression, but I think this should be unnecessary.

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.Oracle
Target framework: .NET Framework 4.7
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

**Comment by Wain123** [comment]
I just noticed that quotes cause the identifier to be case sensitive. The following works correctly despite quotes:
```SQL
SELECT "NVL"(1.0, 2.0)
FROM "TEST_TABLE" "z"
FETCH FIRST 1 ROWS ONLY
```
So it's not even an Oracle issue, it's just a me issue. Sorry.

**Comment by brunosantosrhsenso** [comment]
It seems that SqlFunctionExpression has be changed in core 3 and it does not have a ctor that takes a string in the first parameter anymore. I can't seem to find anywhere online explaining what's the correct usage now. Any help?
