### ISSUE TITLE
An issue that I found when moving from EF6 to EF Core 3.0

### ISSUE THREAD

**Issue by danielkaczmarek** [dotnet/efcore#18332]
Each entity in my case stores who created it and who modified it (see AbstractAudit below), the person who does these operations is called Operator. Operator was also created and could be modified, an Operator can have a Name, name follows the same rule, it has to created and could be modified later. It does work in EF6, we’re now trying to move this production application to netcore and EF core, however the EF core throws the System.InvalidOperationException. 

### Steps to reproduce
    
    public abstract class AbstractAudit
    {
        public int? CreatedOperatorId { get; set; }

        [ForeignKey(nameof(CreatedOperatorId))]
        public Operator CreatedOperator { get; set; }

        public int? ModifiedOperatorId { get; set; }

        [ForeignKey(nameof(ModifiedOperatorId))]
        public Operator ModifiedOperator { get; set; }
    }

    public class Name : AbstractAudit
    {
        public int NameId { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
    }

    public class Operator : AbstractAudit
    {
        public int OperatorId { get; set; }

        public int? NameId { get; set; }

        [ForeignKey(nameof(NameId))]
        public Name Name { get; set; }
    }

### Further technical details

Unable to determine the relationship represented by navigation property 'Name.CreatedOperator' of type 'Operator'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

EF Core version: 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@AndriySvyryd Can you take a look?

**Comment by administersoftware** [comment]
> 
> 
> @AndriySvyryd Can you take a look?

If you would like an example I can have @danielkaczmarek supply one tomorrow morning as we do have a simple one to test against.

**Comment by AndriySvyryd** [comment]
EF Core tries to find a matching inverse navigation for `Operator.Name` and there are two candidates: `Name.CreatedOperator` and `Name.ModifiedOperator`, since it's not clear which one should be used an exception is thrown. You can see more detailed information in the Debug log.

I assume that in your model `Operator.Name` shouldn't actually have any inverse navigation, you can specify this using Fluent API:

```C#
modelBuilder
    .Entity<Operator>()
    .HasOne(o => o.Name)
    .WithOne();

modelBuilder
    .Entity<Name>()
    .HasOne(n => n.CreatedOperator)
    .WithMany();

modelBuilder
    .Entity<Name>()
    .HasOne(n => n.ModifiedOperator)
    .WithMany();
```
