### ISSUE TITLE
EF Core 3 chooses `(CONVERT([bit],(0)))` as default value for Not Nullable bit field

### ISSUE THREAD

**Issue by mscrivo** [dotnet/efcore#18347]
After upgrading to EF Core 3 from 2.2, we noticed that our DB validation process which compares a freshly created DB to one that was updated started complaining that default constraints didn't match.  

In the DB created with EF Core 3, our migrations that added a non-nullable bit column without specifying a default starting adding default constraints that look like this:

`(CONVERT([bit],(0)))`

Previously with 2.2, they were simply: `((0))`

Seems the extra conversion is wasteful?  Unless there's a reason for it?

### Steps to reproduce
Add a migration for a new non-nullable bit column, similar to:

```C#
migrationBuilder.AddColumn<bool>(
                name: "IsEncrypted",
                schema: "security",
                table: "Table",
                nullable: false,
                defaultValue: false);
```
run it, and observe that the key constraint was set to: `(CONVERT([bit],(0)))`

### Further technical details

EF Core version: 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework:  .NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.4

**Comment by ajcvickers** [comment]
@mscrivo EF Core 3.0 is more consistent about ensuring the correct type when the value supplied does not match the expected type. In this case it isn't required, but we don't want to special case this unless there is a compelling reason to do so. Is this causing any issues other than the difference from 2.2?

Also, the SQL to use for the default value can be explicitly set:
```C#
modelBuilder
    .Entity<Blog>()
    .Property(e => e.IsEncrypted)
    .HasDefaultValueSql("0");
```
In which case the SQL generated is `bit NOT NULL DEFAULT (0)`.

**Comment by mscrivo** [comment]
Nope not causing any issues thus far.

**Comment by ajcvickers** [comment]
@chrisbiles The default value is needed for any existing rows in the table. If you don't have any existing rows, then feel free to edit the migration.
