### ISSUE TITLE
About lazy loading issues in EF Core 3.0

### ISSUE THREAD

**Issue by JohnHe404** [dotnet/efcore#18358]
```csharp
ApplicationDbContext _context;
Cdkeys = this._context.Set<CdKey>();
KeyValues = this._context.Set<KeyValue>();
```

```csharp
var keys = Cdkeys.Where(k => k.BuildType == (int)BuildKeyType.Test);
 foreach(var key in keys)
 {
var values = KeyValues.Where(v => v.KeyId == key.Id).ToList();//InvalidOperationException: 
//There is already an open DataReader associated with this Command which must be closed first.
}
```

```csharp
var keys = Cdkeys.Where(k => k.BuildType == (int)BuildKeyType.Test).ToList();//Because the loading is done
 foreach(var key in keys)
 {
var values = KeyValues.Where(v => v.KeyId == key.Id).ToList();//So,No error
}
```

1. I don't think this lazy loading is bad, instead I think it's very cool.
2. I hope the official can have some documentation about this, or help other through my example.

**Comment by HeMinzhang** [comment]
https://github.com/HeMinzhang/EFCoreBug/blob/master/EFCore3.0/EFCoreBug01/EFCoreBug01/Program.cs

**Comment by ajcvickers** [comment]
@HeMinzhang If your intention here is to suggest documentation changes, then please file an issue or submit a PR at https://github.com/aspnet/EntityFramework.Docs making sure to be clear and complete in anything you post/

If your intention is something else, then please provide more details.

**Comment by smitpatel** [comment]
This is not even related to lazy loading. You are trying to enumerate 2 queries at the same time. If your database provider does not support executing 2 DataReader at the same time, you will hit that error. If you are using SqlServer then enable MARS support. Else you cannot run 2 queries interleaved. You have to finish enumerating one query and then execute the other one.

**Comment by HeMinzhang** [comment]
thank you very much!

**Comment by HeMinzhang** [comment]
https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view=sql-server-ver15

**Comment by HeMinzhang** [comment]
**Use foreach code as follows, still need to call ToList to fix the problem**

```csharp
var keys = Cdkeys.Where(k => k.BuildType == (int)BuildKeyType.Test);
 foreach(var key in keys)
 {
var keyvalue = new KeyValue
{
   Id = ....
  KeyType = keyId,
};
var values = KeyValues.Insert();
//SqlException from Entity Framework - New transaction is not allowed because there are other threads running in the session
}
```

https://stackoverflow.com/questions/2113498/sqlexception-from-entity-framework-new-transaction-is-not-allowed-because-ther

https://github.com/aspnet/EntityFrameworkCore/issues/10282

```csharp
var keys = Cdkeys.Where(k => k.BuildType == (int)BuildKeyType.Test).ToList();
 foreach(var key in keys)
 {
var keyvalue = new KeyValue
{
   Id = ....
  KeyType = keyId,
};
var values = KeyValues.Insert();
}
