### ISSUE TITLE
System.FormatException when using Entity Framework Core cosmos database provider in .Net Core 3.0 (Docker)

### ISSUE THREAD

**Issue by Rishanthakumar** [dotnet/efcore#18363]
I am using EF Core Cosmos database provider in .Net Core to build a simple CRUD application with the support of local cosmos database emulator. 
When I run this application locally with IIS Express it works without any issues. But when I try to run it in a docker container with visual studio 2019. I get a System format exception as below.

![image](https://user-images.githubusercontent.com/13392302/66751257-399eba00-eeac-11e9-932e-b9aaaf939184.png)

### Steps to reproduce

You can find my sample project in the following repository: https://github.com/Rishanthakumar/kubetask-api.git

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET Core 3.0
Operating system: 
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
3.3.0 package of Azure.Cosmos had cross plat issue. We also hit it here https://github.com/aspnet/EntityFrameworkCore/pull/18315#issuecomment-540700980

According to the maintainer of the package hotfix has been released in 3.3.1. Update your package version to get the fix.

**Comment by Rishanthakumar** [comment]
Thank you @smitpatel 👍
