### ISSUE TITLE
about Entities.AddAsync(entity) in ef core 3.0

### ISSUE THREAD

**Issue by JohnHe404** [dotnet/efcore#18375]
```csharp
var key = new CdKey
 {
     //Id = Guid.NewGuid().ToString(), //this  fix solution
     Name = "asp.net",
     BuildType = BuildType.Test
 };
await dbContext.AddAsync(key);
```
If you run the above code, you will encounter problems because of the following code

```csharp
if (entityType.FindPrimaryKey() == null)
{
      throw new InvalidOperationException(CoreStrings.KeylessTypeTracked(entityType.DisplayName()));
 }
```

> https://github.com/aspnet/EntityFrameworkCore/blob/24b9aa1d2e14fe2e737255ede9b2a7a623fcf2af/src/EFCore/ChangeTracking/Internal/StateManager.cs#L214

in ef core 2.0:
https://github.com/aspnet/EntityFrameworkCore/blob/release/2.0/src/EFCore/ChangeTracking/Internal/StateManager.cs#L137

So what is recommended to do?

Previous discussion:
https://github.com/aspnet/EntityFrameworkCore/issues/18263

**Comment by HeMinzhang** [comment]
https://github.com/aspnet/EntityFrameworkCore/commit/01a87665db87786abbf901a41e2afb01b928ab89#diff-16c7cd39358889e6177c94b44fc5e89d

**Comment by HeMinzhang** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Stores/src/IdentityUser.cs#L21

```csharp
public IdentityUser()
{
   Id = Guid.NewGuid().ToString();
   SecurityStamp = Guid.NewGuid().ToString();
 }
```

**Comment by HeMinzhang** [comment]
I think it can be built in to determine whether the primary key of the data table is a string type, and then built-in guid string, but I think, may be a little redundant operation
