### ISSUE TITLE
Rerun relationship discovery if an ambiguity has been resolved on the inverse

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#18388]
```C#
modelBuilder
    .Entity<A>()
    .HasOne(a => a.B)
    .WithOne();
```

Should be enough to configure

```C#
public class A
{
    public int Id { get; set; }
    public B B { get; set; }
}

public class B
{
    public int Id { get; set; }
    public A A1 { get; set; }
    public A A2 { get; set; }
}
```

Also run `KeyDiscoveryConvention` when a property is ignored

And remove from ambiguous inverse navigations when an entity type is removed.

**Comment by smitpatel** [comment]
Consider scenario in #18335
where it is collection navigation on both sides. And the other side uses NotMapped to ignore it and resolves ambiguity but we don't discover relationship.
