### ISSUE TITLE
Files being added to ItemGroup.Compile[Remove]

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#18381]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/734640/files-being-added-to-itemgroupcompileremove-1.html)._

---
ASP .Net Core 2.2.6 adds Migration &amp; Migration.Designer CS files to csproj file while performing remove-migration in Package mnager Console.

```
&lt;ItemGroup&gt;
    &lt;Compile Remove=&quot;Migrations\20190916031349_FirstMig.cs&quot; /&gt;
    &lt;Compile Remove=&quot;Migrations\20190916031349_FirstMig.Designer.cs&quot; /&gt;
    &lt;Compile Remove=&quot;Migrations\20190916033026_FirsMig.cs&quot; /&gt;
    &lt;Compile Remove=&quot;Migrations\20190916033026_FirsMig.Designer.cs&quot; /&gt;
    &lt;Compile Remove=&quot;Migrations\20190916033104_FirstMig.cs&quot; /&gt;
    &lt;Compile Remove=&quot;Migrations\20190916033104_FirstMig.Designer.cs&quot; /&gt;
  &lt;/ItemGroup&gt;
```

why is this happening and how can i stop it?

---
#### Visual Studio Feedback System on 9/15/2019, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/16/2019, 11:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Note for triage: this repros for me! /cc @bricelam

**Comment by AlejandroFlorin** [comment]
I have the exact same issue. Would be nice if this got resolved.

**Comment by mahabubulhasan** [comment]
same issue here also

**Comment by DiegoMartelli** [comment]
Same issue, any news?

**Comment by bricelam** [comment]
It looks like this is a race condition in [dotnet/project-system](https://github.com/dotnet/project-system) (or the underlying CPS).

Adding Thread.Sleep between the time the files are deleted and when we call EnvDTE.ProjectItem.Remove() avoids the ugly csproj file.

Should we submit an issue there or work around it in EF?

**Comment by ajcvickers** [comment]
@bricelam Definitely file the bug on project system. Depending on the response and their plans (or not) to ship a fix we may then consider also working around it in EF.

**Comment by bricelam** [comment]
Filed https://github.com/dotnet/project-system/issues/5895

**Comment by bricelam** [comment]
They said we should work around it on our end.

**Comment by Varorbc** [comment]
Same issue, any news?

**Comment by bricelam** [comment]
No news. We hope to work around it in EF Core 5.0

**Comment by bricelam** [comment]
I've got a PR out to work around this on our side. If it's a CPS project and `$(EnableDefaultItems)` and `$(EnableDefaultCompileItems)` are `true`, we won't call ProjectItem.Remove(). Instead we'll let the project system remove the items when it notices the files have been deleted.

**Comment by TuncayDwellworks** [comment]
Hi is it safe to remove these lines, since the files have already been removed?
<Compile Remove="Migrations\xxxxxxxxxxxxx_xxxxxxxxxxx.cs" />

**Comment by bricelam** [comment]
@TuncayDwellworks Yes
