### ISSUE TITLE
Fluent API

### ISSUE THREAD

**Issue by walmanarias** [dotnet/efcore#18384]
When writing the configuration on fluent api like this:
builder.Property(x=>x.SomeProperty).HasColumnType("char").HasMaxLength(10);

migration for this line:
SomeProperty: table.Column<string>(type: "char", unicode: false, fixedLength: true, maxLength: 10, nullable: true)

the database end result for the column type is char(1) and the maxlength part is not taken in consideration although the migration looks find.

**Comment by ajcvickers** [comment]
Duplicate of #15159
