### ISSUE TITLE
Invalid column name "ColumnID1", should be "ColumnID" when fetching entries from database

### ISSUE THREAD

**Issue by Alecu100** [dotnet/efcore#18380]
### Steps to reproduce

I have a database with 4 linked tables. These are Incident, Object, Subject and ObjectSubject.
An Incident has a one to many relationship with Object and Subject tables. The ObjectSubject table links Subject, Object and Incident together. I know this is a bad decision but that's how I received the database. 

The project was started with different technologies. We just started migrating to Entity Framework Core and we can't change the ObjectSubject table to only link Subject and Object.

So the Incident table has a column IncidentID as the primary key. The Subject table has a SubjectID column as the primary key but also a column IncidentID to link it to a corresponding incident using it with a foreign key. The Object table has a column ObjectID as the primary key and also another column IncidentID to link it to a corresponding incident using it with a foreign key. 

The ObjectSubject table has a composite primary key composed of 3 columns: IncidentID, ObjectID and SubjectID. These columns are also used in foreign keys to link Incident, Object and Subject. So for example there is a foreign key using the IncidentID column in the ObjectSubject table and the IncidentID column from the Incident table. For ObjectID and SubjectID columns it's the same case.

Bellow are the poco classes with the type configurations:

``` C#
 public class Incident 
    {
        public int IncidentID { get; set; }
        public string IncidentNickName { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<ObjectSubject> ObjectsSubjects { get; set;}
        public virtual ICollection<Object> Objects { get; set;}
    }

public class Subject
{
       public int SubjectID { get; set; }
       public string Name { get; set; }
       public virtual Incident Incident { get; set; }
       public virtual ICollection<ObjectSubject> ObjectsSubjects { get; set; }
}

public class Object
{
       public int ObjectID { get; set; }
       public string Name { get; set; }
       public virtual Incident Incident { get; set; }
       public virtual ICollection<ObjectSubject> ObjectsSubjects { get; set; } 
}

public class ObjectSubject 
{
       public int IncidentID { get; set; }
       public int SubjectID { get; set; }
       public int ObjectID { get; set; }

       public virtual Object Object { get; set; }
       public virtual Subject Subject { get; set; }
       public virtual Incident Incident { get; set; }
}

public class IncidentTypeConfiguration : IEntityTypeConfiguration<Incident>
{
        public void Configure(EntityTypeBuilder<Incident> builder)
        {
            builder.ToTable("Incident");

            builder.HasKey(x => x.IncidentID);

            builder.Property(x => x.IncidentID).ValueGeneratedOnAdd();

            builder.Metadata.FindNavigation(nameof(Incident.Subjects)).SetPropertyAccessMode(PropertyAccessMode.Field);
            builder.HasMany(x => x.Subjects).WithOne(x => x.Incident).HasForeignKey(x => x.IncidentID).OnDelete(DeleteBehavior.Cascade);

           builder.Metadata.FindNavigation(nameof(Incident.Objects)).SetPropertyAccessMode(PropertyAccessMode.Field);
            builder.HasMany(x => x.Objects).WithOne(x => x.Incident).HasForeignKey(x => x.IncidentID).OnDelete(DeleteBehavior.Cascade);
        }
}

public class SubjectTypeConfiguration : IEntityTypeConfiguration<Subject>
{
        public void Configure(EntityTypeBuilder<Subject> builder)
        {
            builder.ToTable("Subject");

            builder.HasKey(nameof(Subject.SubjectID));

            builder.Property(nameof(Subject.SubjectID)).ValueGeneratedOnAdd();
        }
}

public class ObjectTypeConfiguration : IEntityTypeConfiguration<Object>
{
        public void Configure(EntityTypeBuilder<Object> builder)
        {
            builder.ToTable("Object");

            builder.HasKey(nameof(Object.ObjectID));
        }
}

public class ObjectSubjectTypeConfiguration : IEntityTypeConfiguration<ObjectSubject>
{
        public void Configure(EntityTypeBuilder<ObjectSubject> builder)
        {
            builder.ToTable("ObjectSubject");

            builder.HasKey(nameof(ObjectSubject.IncidentID), nameof(ObjectSubject.SubjectID), nameof(ObjectSubject.ObjectID));

            builder.Property(nameof(ObjectSubject.IncidentID)).HasColumnName("IncidentID");
            builder.Property(nameof(ObjectSubject.SubjectID)).HasColumnName("SubjectID");
            builder.Property(nameof(ObjectSubject.ObjectID)).HasColumnName("ObjectID");

            builder.HasOne(os => os.Subject).WithMany(s => s.ObjectsSubjects).HasPrincipalKey(subject => subject.SubjectID).HasForeignKey(os => os.SubjectID).OnDelete(DeleteBehavior.Cascade);

            builder.HasOne(os => os.Object).WithMany(o => o.ObjectsSubjects).HasPrincipalKey(o => o.ObjectID).HasForeignKey(os => os.ObjectID).OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(os => os.Incident).WithMany(i => i.ObjectSubjects).HasPrincipalKey(i => i.IncidentID).HasForeignKey(os => os.IncidentID).OnDelete(DeleteBehavior.Restrict);
        }
}

```

And bellow is the query I am executing:

``` C#
var incidentsToDelete = DbContext.Incidents.Where(incident => incidentIds.Any(id => id == incident.IncidentID))
       .Include(i => i.Subjects).ThenInclude(s => s.ObjectsSubjects)
       .Include(i => i.Objects).ThenInclude(s => s.ObjectsSubjects).ToList();
```

I get the following exception when executing the query above:

`System.Data.SqlClient.SqlException: 'Invalid column name 'SubjectID1'.'` 
`  at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)`
-->

### Further technical details

EF Core version: 2.2.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: NET Core 2.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by jonathanantoine** [comment]
Did you find where the issue comes from ? I have the same one.
