### ISSUE TITLE
How can i set partition key from cosmosdb collection through entity framework core code first approach?

### ISSUE THREAD

**Issue by saitejaprattipati** [dotnet/efcore#18397]
Partition key _partitionKey is generated by default which is not expected

My code is as follows:

  public class sampleContext : DbContext
    {
        public sampleContext(DbContextOptions options) : base(options)
        {
            Database.EnsureCreated();
        }

        protected sampleContext()
        {
            Database.EnsureCreated();
        }

        public DbSet<Address> Address { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
                {                    
                    OneCollectionPerDbSet(modelBuilder);
                }

        private void OneCollectionPerDbSet(ModelBuilder modelBuilder)
        {
            var dbSets = typeof(sampleContext).GetProperties(BindingFlags.Public | BindingFlags.Instance)
                .Where(p => p.PropertyType.IsGenericType && typeof(DbSet<>).IsAssignableFrom(p.PropertyType.GetGenericTypeDefinition()));
            foreach (var dbSet in dbSets)
            {
                var metadata = modelBuilder.Entity(dbSet.PropertyType.GetGenericArguments()[0]).Metadata;
                metadata.Cosmos().ContainerName = dbSet.Name;
            }
        }
    }

**Comment by AndriySvyryd** [comment]
You can configure it with a call like this:
```C#
modelBuilder.Entity<Address>().HasPartitionKey(c => c.PartitionKey);
```

However 3.0 has some issues with partition keys, so I recommend using a preview version of 3.1

**Comment by thomaslevesque** [comment]
@AndriySvyryd this doesn't seem to work...

I have the following model and DbContext:

```csharp
public abstract class FileSystemItem
{
    public string Id { get; set; }
    public string Name { get; set; }
    public string ParentId { get; set; }
}

public class FileItem : FileSystemItem
{
    public long Size { get; set; }
}

public class FolderItem : FileSystemItem
{
    public int ChildrenCount { get; set; }
}

class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }

    public DbSet<FileSystemItem> FileSystemItems { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<FileSystemItem>(e =>
        {
            e.ToContainer("FileSystemItems");
            e.HasKey(e => e.Id);
            e.HasPartitionKey(e => e.Id);
            e.HasDiscriminator<string>("$type")
                .HasValue<FileItem>("fileItem")
                .HasValue<FolderItem>("folderItem");
        });

        // Apparently I also need to set the partition key for derived classes... that's a bit unexpected        

        modelBuilder.Entity<FileItem>(e =>
        {
            e.HasPartitionKey(e => e.Id);
        });

        modelBuilder.Entity<FolderItem>(e =>
        {
            e.HasPartitionKey(e => e.Id);
        });
    }
}
```

When I try to insert an entity to `FileSystemItems`, I get the following error:

> Create item failed. Status code: BadRequest. Message: 'Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]}ActivityId: 734784b5-20cf-4f0d-8e4e-eae81058af34, Request URI: /apps/6886d0dc-b134-4645-87f9-7bc678aa469b/services/b2e8d470-676a-4c5b-8d60-a7a9b30162cb/partitions/0119e1b5-5d04-42d9-b9c7-35e16142bede/replicas/132145933440249660p/, RequestStats: RequestStartTime: 2019-10-17T09:12:47.7729793Z, RequestEndTime: 2019-10-17T09:12:47.7917245Z, Number of regions attempted: 1ResponseTime: 2019-10-17T09:12:47.7917245Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd19.documents.azure.com:16776/apps/6886d0dc-b134-4645-87f9-7bc678aa469b/services/b2e8d470-676a-4c5b-8d60-a7a9b30162cb/partitions/0119e1b5-5d04-42d9-b9c7-35e16142bede/replicas/132145933440249660p/, LSN: 45, GlobalCommittedLsn: 45, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#45, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create, SDK: Windows/10.0.18362 cosmos-netstandard-sdk/3.0.0'

How is this supposed to work? I have no control over the partition key specified in the header!

**Comment by thomaslevesque** [comment]
In case it was related, I tried to rename `Id` to `id`, but now I get this error:

> The property list {'id', 'id'} cannot be used, because it contains a duplicate - 'id'.

**Comment by AndriySvyryd** [comment]
@thomaslevesque What version did you try this on?

**Comment by thomaslevesque** [comment]
> @thomaslevesque What version did you try this on?

The latest version on NuGet, 3.1.0-preview1.19506.2

> Did you try using a partition key that's not the primary key?

No, I didn't. But I think it should be supported, since it's common to use the id as the partition key in cases where there's no other partition key that would make sense.

**Comment by AndriySvyryd** [comment]
@thomaslevesque If you don't have a good partition key candidate just don't configure a partition key, there's no benefit of having one item per partition.

**Comment by thomaslevesque** [comment]
> If you don't have a good partition key candidate just don't configure a partition key, there's no benefit of having one item per partition.

That's what I'd do, but it's no longer possible to create a collection with no partition key... In the Azure Portal and the .NET SDK (v3), a partition key is mandatory.

**Comment by AndriySvyryd** [comment]
@thomaslevesque EF Core uses `__partitionKey` as the partition key if you don't specify one

**Comment by thomaslevesque** [comment]
Ah, good to know, thanks!
