### ISSUE TITLE
Query when using InMemoryDatabase behaves differently than in version 2.2.0

### ISSUE THREAD

**Issue by WoMayr** [dotnet/efcore#18394]
Executing a query with a projection of a list inside a projection fails since the update to version 3.0.0 with a NullPointerException.

### Steps to reproduce
I created a repository to demonstrate the issue: https://github.com/WoMayr/EfCoreDbIssue

The repository contains a simple model with 3 entities:
![class-diagram](https://user-images.githubusercontent.com/1965557/66899005-885a6a00-effa-11e9-9685-8240ce80954e.png)

| When running the query using version 3.0.0 it failes with a NullReferenceException: | When running the exact same query but using version 2.2.0 (and .NET Core 2.2) it passes: |
| --- | --- |
| ![2019-10-16_09-39-52-devenv](https://user-images.githubusercontent.com/1965557/66899166-cd7e9c00-effa-11e9-956e-b8cf0f5a0f63.png) | ![2019-10-16_09-40-32-devenv](https://user-images.githubusercontent.com/1965557/66899173-cf485f80-effa-11e9-8770-c8f594ffc922.png) |

This is the problematic query ([Link to sourcecode](https://github.com/WoMayr/EfCoreDbIssue/blob/master/EfCoreMemoryDbIssue.Test/UnitTest1.cs#L45)):
```csharp
var myA = await context.As
    .Where(x => x.Id == 1)
    .Select(x => new ADto
    {
        Id = x.Id,
        PropertyB = (x.PropertyB == null)
            ? null
            : new BDto
            {
                Id = x.PropertyB.Id,
                PropertyCList = x.PropertyB.PropertyCList.Select(
                    y => new CDto {
                        Id = y.Id,
                        SomeText = y.SomeText
                    }).ToList()
            }
    })
    .FirstOrDefaultAsync();
```

_Further note_: This issue does not happen when using the Microsoft.EntityFrameworkCore.SqlServer provider, as our project runs without problems. Only the unit tests fail.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework:  .NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.3

**Comment by chuckconway** [comment]
We are experiencing the same issue. We are still investigating the issue, however, from what we can tell the order of the items, when not ordered by the query, are different than when they are inserted. 

The current evidence points to the results being in the reverse order as they are added to the context.

**Comment by tharidu** [comment]
Similar to @chuckconway we are getting the same exact issue. `AsEnumerable` and `ToList` shows results in reverse order they have been added to the context.

**Comment by chuckconway** [comment]
@tharidu We were unable to find a workaround. Luckily for us, the cases where we encountered this issue were minimal. We had to rework the code to not to depend on the index position. Using index position isn't the best programming practice, but it's still annoying a framework upgrade forced a rework of some existing code. Hopefully, you're able to get around this issue with minimal impact.

**Comment by tharidu** [comment]
@chuckconway Actually we were also lucky to have minimal places to rework not to depend on the index position :)

**Comment by smitpatel** [comment]
Related #17537
