### ISSUE TITLE
SqlFunctionExpression should have a package name

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#18399]
Oracle PLSQL functions are called with the following syntax. Quotes are optional, all of these are valid:
```SQL
"NUM"."MIN"(1, 2)
"NUM".MIN(1, 2)
NUM."MIN"(1, 2)
NUM.MIN(1, 2)
```
The package name is NUM, the function name inside that package is MIN.

I would like to call this function using a SqlFunctionExpression, but I can't, because I can't specify the package name. Setting the function name to "NUM.MIN" doesn't help either, this is not valid:
```SQL
"NUM.MIN"(1, 2)
```

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.Oracle
Target framework: .NET Framework 4.7
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

**Comment by smitpatel** [comment]
Use `NUM` as schema & `MIN` as functionName.

**Comment by Wain123** [comment]
Then I can't use the schema to specify the actual schema.
```SQL
"SCHEMA"."NUM"."MIN"(1, 2)
```

**Comment by smitpatel** [comment]
Duplicate of #4019

**Comment by ajcvickers** [comment]
@Wain123 Have you tried using "SCHEMA.NUM" as the schema? I believe that was the solution the last time this came up, but things may have changed.

**Comment by ajcvickers** [comment]
Note from triage: this is something that the Oracle provider could likely do by parsing the value passed to "schema" for dots and doing the appropriate thing. @Wain123 You might want to file an issue with Oracle. Beyond that, closing as duplicate of #4019

**Comment by Wain123** [comment]
> this is something that the Oracle provider could likely do by parsing the value passed to "schema" for dots

I think that's a bad idea. A package is not some subsection of a schema, it's a completely different kind of object.

> Use NUM as schema & MIN as functionName.

This is a successful SQL injection attack. The parameter is labeled "schema", but its value is interpreted as something completely different.

Sorry for the rant, but from a clean code point of view, this whole thread is appalling, starting with the OP mentioning "NUM.MIN" as a function name.

**Comment by ajcvickers** [comment]
@Wain123 In that case it looks like you'll need to wait for #4019 to be implemented.
