### ISSUE TITLE
Override behavior of Linq methods

### ISSUE THREAD

**Issue by bdebaere** [dotnet/efcore#18410]
_What problem are you trying to solve?_
I'm trying to expand certain functionality so that the Any() LINQ method is implemented for a custom type. The IMethodCallTranslator interface looks to be exactly what I need, however the Translate method does not get triggered for every method called in the expression tree.
I know that it works for methods for which EntityFrameworkCore does not have an implementation.

I've tried registering the MethodCallTranslator with 
services.AddScoped<ICompositeMethodCallTranslator, CustomTranslator>();
services.AddScoped<IMethodCallTranslatorPlugin, CustomTranslatorPlugin>();

It's quite weird because the query that is sent to the database does not apply the filter at all. Which makes me wonder why, when EntityFrameworkCore cannot translate it, it does not fall back on other translators.

_Describe the solution you'd like_
Being able to convert .Any() to custom SQL of my choosing, preferably with IMethodCallTranslator. So that the custom conversion of .Any() to SQL takes precedence over other implementations.

I can add an extension method CustomAny() or even an extension method Any() which would take precedence over the LINQ methods. However, this stops working as soon as I add a predicate i.e. Any(this CustomType instance, Func<CustomType, bool> predicate) no longer triggers the Translate method again.

**Comment by smitpatel** [comment]
@bdebaere - Without any code, it is hard to say anything. If you post some code on what is the actual query you are trying to translate, what is the custom translation you have added & what is the generated SQL (When you say that no filter is applied). Also please specify EF Core version you are using.

**Comment by bdebaere** [comment]
@smitpatel 
EntityFrameworkCore 2.2

The Translate method is not being triggered with the code below.

```csharp
    public class TestEntity
    {
        [Key]
        public Guid Id { get; set; }

        public string[] Strings { get; set; } // Example database value: 1234;test;
    }

    public class TestDbContext : DbContext
    {
        public DbSet<TestEntity> TestEntities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "Server=(LocalDb)\\MSSQLLocalDB;Database=Tests;Integrated Security=True;",
                options =>
                {
                    options
                        .MigrationsAssembly(Assembly.GetExecutingAssembly().FullName);
                });

            optionsBuilder
                .AddFilteringSupport();

            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityBuilder = modelBuilder
                .Entity<TestEntity>();

            entityBuilder.ToTable("TestEntity");

            entityBuilder
                .Property(entity => entity.Strings)
                .HasConversion(
                    toDatabase => string.Join(";", toDatabase),
                    toEntity => toEntity.Split(';'));

            base.OnModelCreating(modelBuilder);
        }
    }

    public static class DbContextOptionsBuilderExtensionMethods
    {
        public static DbContextOptionsBuilder AddFilteringSupport(this DbContextOptionsBuilder builder)
        {
            builder
                .AddOrUpdateExtension(new CustomDbContextOptionsExtension());
            return builder;
        }
    }

    public class CustomDbContextOptionsExtension : IDbContextOptionsExtension
    {
        // Rest of the methods removed for brevity.
        public bool ApplyServices(IServiceCollection services)
        {
            services.TryAddSingleton(this);
            services.AddSingleton<IMethodCallTranslatorPlugin, CustomMethodCallTranslatorPlugin>(GetLifetime<IMethodCallTranslatorPlugin>());

            foreach (var descriptor in this.serviceDescriptors)
            {
                services.Add(descriptor);
            }

            return false;
        }
    }

    public class CustomMethodCallTranslatorPlugin : IMethodCallTranslatorPlugin
    {
        public IEnumerable<IMethodCallTranslator> Translators { get; }

        public CustomMethodCallTranslatorPlugin(RelationalDbContextOptionsExtension extension)
        {
            var translators = new List<IMethodCallTranslator>();
            translators.Add(new CustomTranslator());

            this.Translators = translators;
        }
    }

    public class CustomTranslator : IMethodCallTranslator
    {
        public virtual Expression Translate(MethodCallExpression methodCallExpression)
        {
            // This is not being called when performing the Any method (see test below).
            return null;
        }
    }

    [TestMethod]
    public void CanPerformAny()
    {
        using (var dbContext = new TestDbContext())
        {
            var result = dbContext
                .TestEntities
                .FirstOrDefault(entity => entity.Strings.Any());
        }
    }
```

**Comment by bdebaere** [comment]
@smitpatel Any idea on how I can tackle this?

**Comment by bdebaere** [comment]
@smitpatel @ajcvickers Looks like I will have to return to injecting my own IQueryModelGenerator? I wanted to move away from this design because it changes in EntityFrameworkCore 3.0, but there is still a way to convert the code as mentioned in https://github.com/aspnet/EntityFrameworkCore/issues/18029.

**Comment by ajcvickers** [comment]
@bdebaere Are you asking for how to do this in EF Core 2.2, or how to do this in EF Core 3.0?

**Comment by bdebaere** [comment]
@ajcvickers I'm not asking _how_ to do it, per sé. I'm stating that the `IMethodCallTranslator` does not catch all methods, probably because it runs _after_ other processing done by EntityFrameworkCore which for example translates `MemberExpressions` to `ColumnExpressions`. Not a single LINQ method is caught by `IMethodCallTranslator.Translate`.

Therefore, the implementation I currently have makes use of an injected `IQueryModelGenerator` which performs some preprocessing on the generated expression tree. It replaces LINQ Any with a custom Any which does allow me to use the `IMethodCallTranslator` to translate that custom Any method into custom `Expressions` which I can, in turn, translate into SQL through `SqlFragmentExpressions` in the `Visit` method of those custom `Expressions`.

One thing I did notice again was that when I define a custom Any method like below that this triggers the `IMethodCallTranslator.Translate` method.

```csharp
public static class StringArrayExtensionMethods
{
    public static bool Any(this string[] instance)
    {
        throw new InvalidOperationException();
    }
}
```

However defining a custom Any method like below does _not_ trigger the `IMethodCallTranslator.Translate` method. Presumably because EntityFrameworkCore tries to translate the `Func<string, bool>` to something but fails, and then aborts calling the `IMethodCallTranslators` at all.

```csharp
public static class StringArrayExtensionMethods
{
    public static bool Any(this string[] instance, Func<string, bool> predicate)
    {
        throw new InvalidOperationException();
    }
}
```

Two questions:

1. Do I have any other option besides `IQueryModelGenerator`?
1. Why is public `static bool Any(this string[] instance, Func<string, bool> predicate)` not triggering `IMethodCallTranslator.Translate`?

**Comment by bdebaere** [comment]
@ajcvickers EntityFrameworkCore 2.2

**Comment by ajcvickers** [comment]
@bdebaere This is something we are not going to investigate in detail for 2.2 since the query pipeline has changed completely between 2.x and 3.x releases.
