### ISSUE TITLE
Migrations: Should scaffold defaultValue: [CLR default] for new non-nullable columns

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1843]
In EF6, if you add a non-nullable column we set the defaultValue to the CLR default for the property type. Otherwise the AddColumn operation will always fail since you'll end up with NULL for existing data.

**Comment by bricelam** [comment]
Dupe of #1275?

**Comment by rowanmiller** [comment]
Yep, that's the same one
