### ISSUE TITLE
InMemory: Using a .Select(...) on owned property conflicts with relation in same select

### ISSUE THREAD

**Issue by nachtjasmin** [dotnet/efcore#18435]
(sorry for the bad title, should be clarified)

When creating a custom query using the LINQ `.Select()` method, the queried properties do not have the correct value. This only occurs if there's a reference to another relation (one->one in the sample) inside the lambda.

```csharp
var queryMixed = await _context.TestEntities
                               .Select(x => new
                                            {
                                                x.Value,
                                                A = x.Owned.First,
                                                B = x.Owned.Second,
                                                C = x.Child.Owned.First,
                                                D = x.Child.Owned.Second
                                            })
                                .FirstOrDefaultAsync();
```

Consider the following model:
```csharp
var test = new RootEntity
{
    Value = "test",
    Owned = new TestOwned
    {
        First = 2,
        Second = 4,
        AnotherValueType = "yay"
    },
    Child = new ChildEntity
    {
        Owned = new TestOwned
        {
            First = 1,
            Second = 3,
            AnotherValueType = "nay"
        }
    }
};
```

Querying with the above query should return the following values:

- `string "test"`
- `int A = 2`
- `int B = 4`
- `int C = 1`
- `int D = 3`

Actually, `A` and `B` have the wrong values.

- `int A = 4`
- `int B = 1`

This is a query that worked fine in EF Core 2.2.

### Steps to reproduce
**Unit of work project featuring the above code can be found here: https://github.com/jlnostr/efcore-querying-bug**

### Further technical details

EF Core version: 3.0.0 and 5.0.0-alpha1.19517.11
Database provider: InMemory (sample) and PostgreSQL
Target framework: .NET Core 3
Operating system: Windows 10
IDE: JetBrains Rider

**Comment by ajcvickers** [comment]
Note for triage: works for SQL Server and SQLite, but fails as reported for in-memory.
/cc @roji Can you try against PostgreSQL?

**Comment by smitpatel** [comment]
@ajcvickers - Incorrect values for InMemory or exception thrown?

**Comment by ajcvickers** [comment]
@smitpatel In correct values as reported above.

**Comment by roji** [comment]
Test passes on PostgreSQL with EFCore.PG 3.0.0.
