### ISSUE TITLE
he instance of entity type 'x' with the key value '{Id: 6}' is marked as 'Modified', but the instance of entity type 'y' with the key value ': 6}' is marked as 'Added' and both are mapped to the same row.

### ISSUE THREAD

**Issue by codehunter13** [dotnet/efcore#18448]
When updating a valueobject (owned type) i get the follwing error in ef core 3.0. The valueobject is set by assigning a whole new object (hence value object). 

he instance of entity type 'x' with the key value '{Id: 6}' is marked as 'Modified', but the instance of entity type 'y' with the key value ': 6}' is marked as 'Added' and both are mapped to the same row.

We use nested valueobject and inheritance in the entitities (not the valueobjects). don't know if this matters.

**Comment by ajcvickers** [comment]
@codehunter13 Please post a small, runnable project/solution or complete code listing that demonstrates this behavior so that we can fully investigate.

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17422
