### ISSUE TITLE
DbContext.AddRangeAsync doesn't preserve insert order

### ISSUE THREAD

**Issue by benmccallum** [dotnet/efcore#18443]
I've done an upgrade to 3.0 from 2.2 and a couple of unit tests are now breaking. Essentially the tests are around an `AddRangeAsync`, which adds multiple records at once and then asserts they were added as expected. It seems this method can now add records without preserving the order of the input.

I've confirmed and it affects `AddRange` too.

Forgive me if I've missed an upgrade guide mentioning this as a breaking change. If this is the way it is now, I guess it needs to be documented. Otherwise, can it be fixed?

### Steps to reproduce
My unit tests is basically as follows.

```
var user = _context.Users.Single(u => u.UserID == 2);
var rolesToAdd = new [] { "Role1", "Role2" };
await _userRolesService.AddRoles(user, rolesToAdd);

var userRoles = _context.UserRoles.Where(role => role.UserID == 2).ToList();
userRoles.Count.ShouldBe(2);
userRoles[0].Role.Name.ShouldBe("Role1");
userRoles[1].Role.Name.ShouldBe("Role2");
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Win 10
IDE: Visual Studio 2019 16.3.5

**Comment by ajcvickers** [comment]
@benmccallum If the order happened to be preserved in 2.x, then that was a coincidence. EF Core doesn't attempt to preserve order here for several reasons. See #7894 for more info.

**Comment by benmccallum** [comment]
No worries, I've updated my tests not to assume a specific order. Cheers.
