### ISSUE TITLE
Extension methods are not found while using Interface with DbContext

### ISSUE THREAD

**Issue by sudurrani** [dotnet/efcore#18442]
While using an interface for entities with DbContext class can't use/found _context.Database

##### Interface
```
public interface IMainDbContext
{
    DbSet<User> Users { get; set; }
    DbSet<Client> Clients { get; set; }
    Task<int> SaveChangesAsync(CancellationToken cancellationToken);
}
```
##### DbContext Class
```
public partial class MainDbContext : DbContext, IMainDbContext
{
   public MainDbContext(DbContextOptions<MainDbContext> options)
    : base(options)
   {
   }       
   public DbSet<User> Users { get; set; }
   public DbSet<Client> Clients { get; set; }
}
```

> Created a class(RDFacadeExtensions) mentioned here [1862](https://github.com/aspnet/EntityFrameworkCore/issues/1862)

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE:  Visual Studio 2019 16.3.1

**Comment by ajcvickers** [comment]
@sudurrani In the code above, the interface `IMainDbContext` doesn't have any `Database` property, so I wouldn't expect this to compile.  If I'm missing something, then please post a small project/solution that demonstrates the issue so that we can be sure that we're discussing the same code.

**Comment by sudurrani** [comment]
It's very simple, there is an interface with entities and this interface is implemented by a class also inherited from DbContext.
Now when ever I try to inject interface and want to write query like.

```Public Class Any
{
IMainDbContext _context;
      public Any(IMainDbContext context)
      {
           _context = context;
      }
     public List<User> AnyFunction()
     {
            var result = _context.Database.
                       // Here is the issue I can't find Database
      }       
}

**Comment by ajcvickers** [comment]
@sudurrani That's because the interface doesn't define a `Database` property.

**Comment by sudurrani** [comment]
@ajcvickers exactly when I add Database property then whenever I use _context.Database.ExecuteSqlCommand here I won't be able to access **.ExecuteSqlCommand**.
Actually .Database & .ExecuteSqlCommand are DbContext builtin but here I'm using interface with my context class hence unable to get these methods.
Still Can't In .Database & .ExecuteSqlCommand into the game.

**Comment by ajcvickers** [comment]
@sudurrani Unless I'm missing something, that's just the way C#/.NET  works. Is there something EF should be doing differently here?

**Comment by sudurrani** [comment]
I found the solution.
Therefore closing the issue.
