### ISSUE TITLE
EF.Functions support for Cosmos

### ISSUE THREAD

**Issue by danejur** [dotnet/efcore#18451]
When playing around with EFCore's Cosmos provider last night, I made the unfortunate discovery that Cosmos doesn't currently have support (or an implementation, rather) for `EF.Functions`, the helper class that provides some additional SQL operators and functions (notably, for my use cases, `Contains` and `Like`). Is there any plan to add a Cosmos-specific implementation of these extensions?

**Comment by ajcvickers** [comment]
Likely duplicate of #16143

**Comment by danejur** [comment]
@ajcvickers Saw that thread, and thought the same. The only thing I'd point out is that 'like' isn't included on [the list](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-system-functions) of supported built in functions, which I imagine is because `like` isn't technically a function nor does it seem to be currently supported by Cosmos in general. Feel free to close this issue if you feel that it's a dupe, though!

**Comment by AndriySvyryd** [comment]
@danejur See https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6333414-implement-like-keyword
