### ISSUE TITLE
Inefficient idempotent script generation in Migrator.GenerateScript()

### ISSUE THREAD

**Issue by MaxG117** [dotnet/efcore#18455]
The `HistoryRepository` class contains the `GetBeginIf[Not]ExistsScript` and `GetEndIfScript` methods. I think the purpose of these methods is to allow multiple statements to execute between the BEGIN and END blocks of the script. However, the `Migrator.GenerateScript` method ignores this purpose, and idempotent scripts end up placing each command inside its own BEGIN...END block instead of placing all of the commands from a single migration inside a single BEGIN...END block.

This is because the loop that walks through each command in a migration is in the wrong place. The following code:

```C#
foreach (var command in GenerateUpSql(migration))
{
    if (idempotent)
    {
        builder.AppendLine(_historyRepository.GetBeginIfNotExistsScript(migration.GetId()));
        using (builder.Indent())
        {
            builder.AppendLines(command.CommandText);
        }
        builder.AppendLine(_historyRepository.GetEndIfScript());
    }
    ...
}
```

should have probably been:

```C#
if (idempotent)
{
    builder.AppendLine(_historyRepository.GetBeginIfNotExistsScript(migration.GetId()));
    using (builder.Indent())
    {
        foreach (var command in GenerateUpSql(migration))
        {
            builder.AppendLines(command.CommandText);
        }
    }
    builder.AppendLine(_historyRepository.GetEndIfScript());
}
...
```

Same thing for the loop around `GenerateDownSql`.

Additionally, `GenerateScript` assumes that only a single `Indent` is needed to make the script pretty, but my Begin block requires more than one indent. It would be nice if `GetBeginIf[Not]ExistsScript` and `GetEndIfScript` could access the `IndentedStringBuilder`.

**Comment by bricelam** [comment]
This is by design. BEGIN and END statements can't be separated by GO, so we re-issue the IF..BEGIN..END for each GO block. Issue #3928 would make it a lot prettier.

**Comment by MaxG117** [comment]
I'd think "GO" should be executed after END, not between BEGIN and END. I think you've done that in your prototype by suppressing the transaction. It's not immediately clear to me how your changes affect other providers though.

**Comment by ajcvickers** [comment]
@MaxG117 `GO` is executed after `END`. If this isn't the case for you, can you explain more or provide a repro that demonstrates this.

**Comment by MaxG117** [comment]
@ajcvickers I was just replying to Brice's comment, I did not say that `GO` is executed in the wrong place for me.

Here's what I'm getting at. The `Can_generate_idempotent_up_scripts()` unit test in EFCore.SqlServer.FunctionalTests project expects the following SQL to be generated for the migration whose MigrationId = 00000000000001_Migration1:

```SQL
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000001_Migration1')
BEGIN
    CREATE TABLE [Table1] (
        [Id] int NOT NULL,
        CONSTRAINT [PK_Table1] PRIMARY KEY ([Id])
    );
END;

GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000001_Migration1')
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'00000000000001_Migration1', N'7.0.0-test');
END;

GO
```

My understanding is that multiple statements may be executed between `BEGIN` and `END`, so I don't understand why a single migration is split into two separate "IF NOT EXISTS ... BEGIN ... END; GO" blocks. Could the above SQL not be replaced with something like this instead?

```SQL
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000001_Migration1')
BEGIN
    CREATE TABLE [Table1] (
        [Id] int NOT NULL,
        CONSTRAINT [PK_Table1] PRIMARY KEY ([Id])
    );
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'00000000000001_Migration1', N'7.0.0-test');
END;

GO
```

?

**Comment by bricelam** [comment]
EF6 assumed that every statement could be combined into a single batch (batches are separated by GO), but there are several Transact-SQL statements which are required to be at the beginning of a batch and even some that are required to be the only statement in a batch.

EF Core generates a script that represents exactly how the migrations are executed at runtime (e.g. via `dbContext.Database.Migrate()`). This yields greater confidence that the script will work if `dotnet ef database update` worked. Granted there are still some issue we need to fix. (like #12911 and #7681)

Issue #3928 is about updating Migrations to understand when SQL statements can be batched together. This would put more statements inside the BEGIN..END block and result in fewer IF statements (possibly just one) per migration.

**Comment by MaxG117** [comment]
Ok, this makes sense now.

The documentation for the `IHistoryRepository` `GetBeginIf[Not]ExistsScript` and `GetEndIfScript` does not make it clear that even though these methods are used to BEGIN and END a "block", which to me implies multiple statements, the `Migrator.GenerateScript` method does not treat them as wrappers around a "block" of statements, but rather as wrappers around a single statement. That's why I thought there was a bug in the `Migrator.GenerateScript` method.

I'm closing this, and you can reopen or open another if you think the documentation for those methods should be improved.
