### ISSUE TITLE
Review regex usages

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#18454]
Both for best-practices, and for places where we don't need them and so don't need to depend on this can-of-worms.

**Comment by davidfowl** [comment]
Did you delete all of the regexes?

**Comment by ajcvickers** [comment]
@davidfowl No; the team pushed back strongly against doing that.

**Comment by davidfowl** [comment]
That's the only right answer.

**Comment by ajcvickers** [comment]
@davidfowl Would you like me to set up some time with the team so you can convince them? :trollface: 😄

**Comment by davidfowl** [comment]
I will prepare my first EF PR 🤓
