### ISSUE TITLE
HasCheckConstraint() strips out ( )'s inside the string

### ISSUE THREAD

**Issue by SidShetye** [dotnet/efcore#18459]
A check constraint like 
```
(([Prop1] IS NULL AND [Prop2] IS NOT NULL) OR ([Prop1] IS NOT NULL AND [Prop2] IS NULL))
``` 
is reduced to 
```
([Prop1] IS NULL AND [Prop2] IS NOT NULL OR [Prop1] IS NOT NULL AND [Prop2] IS NULL)
 ^                                      ^  ^                                        ^
```

Notice that the internal `(` and `)` are dropped around `^`. We're concerned this can lead to ambiguity in evaluating the condition. Typically this is added to avoid problematic data, so we want to NOT have any ambiguity in either SQL engine evaluation or user readability.

### Steps to reproduce

Just try the following in your `OnModelCreating(..)`

``` C#
modelBuilder.Entity<FirewallRule>(entity =>  {
    entity.HasCheckConstraint("CK_MyEntity_OnlyOneType", "(([Prop1] IS NULL AND [Prop2] IS NOT NULL) OR ([Prop1] IS NOT NULL AND [Prop2] IS NULL))");
});
```

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 x64 v1903
IDE: Visual Studio 2019 16.3.5

**Comment by SidShetye** [comment]
I also want to add before someone nit-picks ;)

For the specific example above, dropping the `(` actually doesn't impact the logical outcome given the [operator precedence](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/operator-precedence-transact-sql?view=sql-server-ver15) of `AND` before `OR`. 

We don't know if we're just lucky with the `(` stripping "bug" or if you actually have some rules and strip off the `(` based on the target SQL provider's capabilities/precedence.

**Comment by AndriySvyryd** [comment]
@SidShetye Where do you get the reduced constraint from?
You can script the migrations to see what EF sends to the database: `dotnet ef migrations script`

**Comment by SidShetye** [comment]
@AndriySvyryd : The `.sql` file from `dotnet ef migrations script` does show the inner `( )`'s. 

But if using any other tool like SSMS or VS2019 SQL projects (for schema compare) to see what was written inside the database, they all return back that check constraint without the `( )`'s.

**Comment by AndriySvyryd** [comment]
Since the output from EF still has the intact constraint then any further manipulation is done by SQL Server
