### ISSUE TITLE
Cannot query a value of type ulong greater than 2 ^ 63 in SQLite

### ISSUE THREAD

**Issue by sharpwood** [dotnet/efcore#18478]
Cannot query a value of type ulong greater than 2 ^ 63 in SQLite.

But that's what the official document says.

Query limitations
SQLite doesn't natively support the following data types. EF Core can read and write values of these types, and querying for equality (where e.Property == value) is also supported. Other operations, however, like comparison and ordering will require evaluation on the client.

https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations?view=aspnetcore-3.0

### Further technical details

EF Core version:3.0.0
Database provider: (Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (NET Core 3.0)
Operating system:Windows 10
IDE: ( Visual Studio 2019 16.3)

**Comment by bricelam** [comment]
It should work, but there may be a bug. @sharpwood Can you share a simple repro project we that can use to investigate?

**Comment by sharpwood** [comment]
![TIM截图20191022090224](https://user-images.githubusercontent.com/7440304/67253570-cd731600-f4aa-11e9-9eaf-412c0f151ccc.png)
![TIM截图20191022090243](https://user-images.githubusercontent.com/7440304/67253571-ce0bac80-f4aa-11e9-8136-04e449e07d87.png)

**Comment by sharpwood** [comment]
![TIM图片20191022090537](https://user-images.githubusercontent.com/7440304/67253617-293d9f00-f4ab-11e9-9160-ab3284a1d96a.png)

The queried value will also be truncated to 9223372036854775807

**Comment by sharpwood** [comment]
[SqliteUlong.zip](https://github.com/aspnet/EntityFrameworkCore/files/3753479/SqliteUlong.zip)

**Comment by bricelam** [comment]
How was your database created? It contains `double` values, not `long` as EF Core and Microsoft.Data.Sqlite are expecting.
```sql
select vkey, typeof(vkey) from bhobk;
```
vkey | typeof(vkey)
--- | ---
(null) | null
1188504575042808212 | integer
1.13569128068376e+19 | real
1.1667368640341e+19 | real

**Comment by sharpwood** [comment]
This database is created by other software. Is there a way to solve this situation?

**Comment by bricelam** [comment]
Ensure `long` values are inserted. If it's using C#, here is the logic we use:
``` csharp
long GetValueToInsert(ulong value)
    => unchecked((long)value);
```

**Comment by sharpwood** [comment]
Because the database is designed by other software and cannot be interfered with, can we correctly read the integer and real in it as an unlong?

**Comment by bricelam** [comment]
I think it’s too late. The precision is already lost. But if you check against the persisted value (1135691280683760000), it should work.

**Comment by bricelam** [comment]
But you might have to use .HasConversion\<double>() to get it to generate the correct SQL.

**Comment by sharpwood** [comment]
It seems that the accuracy has not been lost. I can't find any data according to 1135691280683760000. Instead, I can find it with 11356912806837568195.

**Comment by sharpwood** [comment]
Confusingly, if I use a double query, I can't find the value of long. If I use long query, I can't find the value of double.

**Comment by bricelam** [comment]
We strongly discourage mixing data types within the same column. This breaks some fundamental assumptions of ADO.NET and Entity Framework. As you’ve found, it may not always work.

Dynamic typing is a quirky feature unique to SQLite.

**Comment by ajcvickers** [comment]
@sharpwood Can you also attach a SQLite database containing the data that is causing issues? Hopefully this will allow us to get to the bottom of what is happening with the different types of values.

**Comment by sharpwood** [comment]
https://github.com/aspnet/EntityFrameworkCore/files/3753479/SqliteUlong.zip Here is a test database in database folder

**Comment by ajcvickers** [comment]
@sharpwood How are you determining that the "precision has not been lost"? I am never able to get the exact value that you are looking for. It certainly appears to me that precision has been lost.

**Comment by sharpwood** [comment]
@abpiskunov   I was mistaken before, precision has indeed been lost. However, it is good if we can query the value after losing the precision.
