### ISSUE TITLE
more exception info for "Include has been used on non entity queryable"

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/efcore#18471]
When this line is hit https://github.com/aspnet/EntityFrameworkCore/blob/b563040a1bb85f0e4a5699a369030d2b9b4e3c15/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs#L735

It would be really helpful to include in the exception the include expression name and the type it is targeting

**Comment by smitpatel** [comment]
This issue requires adding an exception message to EF Core. Before you starting working on this issue, please submit a proposed exception message and get it reviewed by the team.

Implementation notes:
- Figure out exact exception message.
- Add relevant message in CoreStrings.resx file and regerated CoreStrings.cs using T4 template.
- Add a test which executes negative query, verify exception type using Assert.Throws & exception message test using Assert.Equal

**Comment by SimonCropp** [comment]
shouldnt `Include has been used on non entity queryable` already be in CoreStrings?

**Comment by smitpatel** [comment]
If only we had time....

**Comment by SimonCropp** [comment]
> If only we had time....

I feel you. but holding a community contribution to a higher standard than you hold the current codebase is not great. clearly if the current string is not in CoreString, then it should not be a blocking requirement for another code change that fixes an unrelated issue.

**Comment by SimonCropp** [comment]
if i was submitting a PR to "move strings into CoreString" it is a diff proposition. but a PR to fix a specific issue should change the min amount of code that allows it to fix the issue. forcing other incidental cleanup is not ok

**Comment by smitpatel** [comment]
@SimonCropp - We did not ask you to move exception message to string resources in your PR. Exception messages are for customers and whenever we add a proper one it goes through team review process.

**Comment by SimonCropp** [comment]
@smitpatel @ajcvickers sorry for my blunt interactions on this issue. I have had a number of unpleasant interactions with MS products/tools recently, and incorrectly let that bubble over where. Again, I am sorry.

**Comment by smitpatel** [comment]
This has been fixed https://github.com/dotnet/efcore/blob/250f524dc051b25ee475b0b4c0fd33b33e74471a/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs#L896

**Comment by smitpatel** [comment]
Fixed in https://github.com/dotnet/efcore/pull/22511
