### ISSUE TITLE
Command execution randomly hangs when executing within a transaction

### ISSUE THREAD

**Issue by alex-zyl** [dotnet/efcore#18480]
.NET Core 3.0 app running on Linux container.
It performs 4 MERGE operations using [Upsert](https://www.nuget.org/packages/FlexLabs.EntityFrameworkCore.Upsert/) extension (uses 
ExecuteSqlRawAsync internally) inside a transaction and writes the data into Azure SQL db:

Slightly obfuscated production code:
```csharp
public async Task PersistAsync(ProcessStatus processStatus)
{
    var strategy = _dbContext.Database.CreateExecutionStrategy();

    await strategy.ExecuteInTransactionAsync(async () => await PersistData(processStatus), () => Task.FromResult(false));
}

private async Task PersistData(ProcessStatus processStatus)
{
    var entities1 = CreateEntity1(processStatus);
    await _dbContext.Entities1.UpsertRange(entities1)
        .On(v => new { v.Id1, v.Id2 })
        .NoUpdate()
        .RunAsync();

    var entities2 = CreateEntity2(processStatus);
    await _dbContext.Entities2.Upsert(entities2)
        .On(v => new { v.Id1, v.Id2 })
        .RunAsync();

    var entities3 = CreateEntity3(processStatus);
    await _dbContext.Entities3.UpsertRange(entities3)
        .On(v => new { v.Id1, v.Id2 })
        .RunAsync();

    var entities4 = CreateEntity4(processStatus);
    await _dbContext.Entities4.UpsertRange(entities4)
        .On(v => new { v.Id1, v.Id2 })
        .RunAsync();

    await _dbContext.SaveChangesAsync();
}
```

It worked fine while running on Win Server 2016 VM
After moving to AKS we noticed that the app started hanging randomly while persisting one of the entities.

It can successfully process the data 50-150 times before the issue occurs and randomly hangs on one four entities from the code above. 

From EF debug logs before it hangs:

```
[16:34:50 DBG] Creating DbCommand for 'ExecuteNonQuery'.
[16:34:50 DBG] Created DbCommand for 'ExecuteNonQuery' (0ms).
[16:34:50 INF] Executing DbCommand [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 6) (DbType = AnsiString), @p2='?' (Size = 6) (DbType = AnsiString), @p3='?' (DbType = Int32), @p4='?' (Size = 1) (DbType = Byte), @p5='?' (Size = 1) (DbType = Byte), @p6='?' (DbType = Int32), @p7='?' (DbType = Int32), @p8='?' (Size = 8000) (DbType = AnsiString), @p9='?' (Size = 255) (DbType = AnsiString), @p10='?' (DbType = DateTime), @p11='?' (Size = 2) (DbType = AnsiString), @p12='?' (Size = 255) (DbType = AnsiString), @p13='?' (DbType = Int32), @p14='?' (DbType = DateTime)], CommandType='Text', CommandTimeout='30']
MERGE INTO [Entities4] WITH (HOLDLOCK) AS [T] USING ( VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14) ) AS [S] ([xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [Json], [xxxx], [LastUpdated], [xxxx], [xxxx], [xxxx], [xxxx]) ON [T].[xxxx] = [S].[xxxx] AND [T].[xxxx] = [S].[xxxx] AND [T].[xxxx] = [S].[xxxx] AND [T].[xxxx] = [S].[xxxx] WHEN NOT MATCHED BY TARGET THEN INSERT ([xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [Json], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx]) VALUES ([xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [xxxx], [LastUpdated], [xxxx], [xxxx], [xxxx], [xxxx]) WHEN MATCHED THEN UPDATE SET [LastUpdated] = [T].[LastUpdated], [xxxx] = [T].[Json], [xxxx] = [T].[xxxx], [xxxx] = [T].[xxxx], [xxxx] = [T].[xxxx], [xxxx] = [T].[xxxx];
```

From sys.sysprocesses
```
spid	kpid	blocked	waittype	waittime	lastwaittype	open_tran	status	program_name	cmd	stmt_start	stmt_end	request_id
151	0	0	0x0000	0	MISCELLANEOUS                   	1	sleeping                      	Core Microsoft SqlClient Data Provider                                                                                          	AWAITING COMMAND          	-1	-1	0
152	0	0	0x0000	0	MISCELLANEOUS                   	1	sleeping                      	Core Microsoft SqlClient Data Provider                                                                                          	AWAITING COMMAND          	-1	-1	0
```

Observations:
1. Not reproducible when running on Windows
2. Reproducible when running on Docker on Windows using Linux containers
3. Not reproducible when using local database
4. Not reproducible on 2.2
5. Not reproducible if not wrapped with transaction

Technical details:

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: ubuntu 16.04 x64

**Comment by ajcvickers** [comment]
@alex-zyl Can you post code showing what calls are actually being made against EF Core? Also, it doesn't look like multiple queries are beiung run concurrently against the same `DbContext` instance, but could you confirm this?

**Comment by alex-zyl** [comment]
@ajcvickers 
Will try to extract the code into reproducible project tomorrow. 

>  but could you confirm this?

Correct. DbContext is instantiated and disposed per dependency.

**Comment by alex-zyl** [comment]
@ajcvickers 
I extracted the code into a separate project. Please see https://github.com/alex-zyl/EFCore3OnLinuxIssue

One thing that I noticed while testing is that the connection string contained MultipleActiveResultSets=True;.
With MARS turned off, no hanging executions so far, so MARS setting might be the case.

**Comment by alex-zyl** [comment]
Tested in AKS: turning off MARS resolved the issue. 
Wondering what changed in 3.0 comparing to 2.2

**Comment by alex-zyl** [comment]
@ajcvickers 
The issue seem to be unrelated to EF Core. Should I raise it in corefx repo?

**Comment by ajcvickers** [comment]
@alex-zyl Hard to be sure where it should go. Do you still think it is an issue with MARS? If so, [SqlClient](https://github.com/dotnet/SqlClient) is probably the right place.

@smitpatel Do we still have conditional behavior based on MARS in the new query pipeline?

**Comment by smitpatel** [comment]
@ajcvickers - No.

**Comment by alex-zyl** [comment]
@ajcvickers 
Thank you. I went through the open issues and it turned out there are already few of them describing similar behavior.
