### ISSUE TITLE
Null encapsulated collection using PropertyAccessMode.Field and Lazy Loading Proxies

### ISSUE THREAD

**Issue by gusgorman** [dotnet/efcore#18512]
I have an encapsulated one to many collection:

```C#
private readonly ICollection<Proficiency> _proficiencies;
```

which is accessed by some simple logic within the domain object, and has a public accessor property:

```C#
public virtual IEnumerable<Proficiency> Proficiencies { get { return _proficiencies.ToList(); } }}
```

```C#
        public virtual bool HasProficiencyAt(int skillLevel)
        {
            return _proficiencies.Any(p => p.SkillLevel == skillLevel);
```

This is mapped as follows:
```C#
            builder.HasMany(s => s.Proficiencies).WithOne().HasForeignKey(p => p.SkillUid);
            builder.Metadata
                .FindNavigation(nameof(Domain.Ibm.Skill.Proficiencies))
                .SetPropertyAccessMode(PropertyAccessMode.Field);
````

If an entity is loaded from the db and the HasProficiencyAt(int skillLevel) method is called by the client code BEFORE the public accessor propery has been called, then the encapsulated _proficiencies collection is null.

So this does not work:

```C#
                        if(skill.HasProficiencyAt(skillLevel))
                        {
```

But this does:

```C#
                        IEnumerable<Proficiency> ps = skill.Proficiencies;
                        if(skill.HasProficiencyAt(skillLevel))
                        {
````

Note this is with LazyLoadingProxies turned on.
Stepping through in the debugger and viewing the object causes the proxy to initialize properly and the bug is then avoided.

EF Core version: 3.0
Target framework: NET Core 3.0
IDE:  Visual Studio 2019 16.3.1

**Comment by ajcvickers** [comment]
@gusgorman This is by-deisgn. EF will only populate the collection when loading of the relationship is triggered, and that happens with lazy-loading when the mapped `Proficiencies` navigation property is accessed. In the case where the field is null, it is because nothing has accessed the navigation property or otherwise triggered the navigation to load.

This can be fixed in the entity by either eager initialization:
```C#
private readonly ICollection<Proficiency> _proficiencies = new List<Proficiency>();
```
or lazy initialization in `HasProficiencyAt`:
```C#
return (_proficiencies ??= new List<Proficiency>()).Any(p => p.SkillLevel == skillLevel);
```
Or `HasProficiencyAt` could be set up to trigger lazy loading by using the property:
```C#
return Proficiencies.Any(p => p.SkillLevel == skillLevel);
```

**Comment by gusgorman** [comment]
@ajcvickers Thanks for the reply. None of the 3 fixes suggested work in all scenarios. 

The first 2 don't work if the object has just been loaded from the database. 

With regards to the 3rd suggestion, I also have an AddProficiency method:

`        public virtual void AddProficiency(Proficiency proficiency)
        {
            _proficiencies.Add(proficiency);
        }`

I guess you could put a workaround in the call the property first, but this is ugly.

**Comment by gusgorman** [comment]
@ajcvickers in addition to my comment above, I should have said "The first 2 don't work if the object has just been loaded from the database and the collection should contain objects, ie the one-to-many relationship has 1 or more items associated with it.

**Comment by ajcvickers** [comment]
@gusgorman Sorry, but I don't have any other suggestions. If you need lazy-loading to kick in, then the access must go through the property since that the only thing that can be overridden by the proxy.

**Comment by gusgorman** [comment]
Fair enough.

So for this to really work the design needs to be changed to somehow populate the private collection directly, which I'm guessing would be a big change and perhaps involve reflection or some other approach.
