### ISSUE TITLE
dotnet publish broken because dotnet-ef is no longer part of sdk since 3.0

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/efcore#18543]
Entity Framework SQL script generation is part of the publish process of .net core applications. This is now broken since 3.0 because dotnet-ef is no longer part of the sdk.

The sql script generation target is defined in `Microsoft.NET.Sdk.Publish.TransformFiles.targets` file in the SDK. It uses `GenerateEFSQLScripts` msbuild task which underneath executes `dotnet ef`.  

## Steps to reproduce

Create a new project. Add a db context. Modify the project to include:
```xml
<ItemGroup>
  <EFMigrations Include="FullName.Of.DbContext" />
</ItemGroup>
```
Then run `dotnet publish`. It fails with `Entity Framework SQL Script generation failed`.

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@ArturDorochowicz To publish with EF, please [install the global tool first](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dotnet-ef).
