### ISSUE TITLE
Adding a new child to a previously saved parent causes an UPDATE instead of an INSERT

### ISSUE THREAD

**Issue by JackCreativeCrew** [dotnet/efcore#18567]
If an entity is added to a dbset and saved, the operation succeeds.
If an entity is then added to a list inside that, for instance, create and save parent then add child to the parent's Children list, when the dbc.SaveChanges call is made the call fails with a DbConcurrencyException. I've traced this back to the child being added as an UPDATE sql statement not an INSERT.

Is this intended behavior?
Am I doing something wrong here?

[An example which triggers this behavior is available here](https://github.com/JackCreativeCrew/DbIssueTest)

**Comment by ajcvickers** [comment]
@JackCreativeCrew See the [breaking change documentation](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dc) and also the discussion on #18055
