### ISSUE TITLE
Add a performant way to register a context factory in DI

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#18575]
This would make using short-lived contexts easier.
Related: https://github.com/dotnet/efcore/issues/19610

**Comment by AndriySvyryd** [comment]
See https://github.com/vany0114/EF.DbContextFactory

**Comment by jzabroski** [comment]
Hi @AndriySvyryd 

Currently, we ask each `T` in an `IRepository<T>` who their `IDbContext` is - so this should solve two problems with one abstraction.  This context factory sounds like a nice improvement, and it avoids directly exposing `Func<T>` which, based on my recent reading of old 2016 conversations between David Fowler and SImpleInjector team, ASP.NET team does not want to do.
