### ISSUE TITLE
Update API doc links to correctly reference external dependencies

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#18580]
Specifically, use the appropriate syntax when referencing a type in an assembly (e.g. Relational) from another assembly (e.g. Core) that doesn't have a dependency on the referenced type.

**Comment by ajcvickers** [comment]
@bricelam Can you add/point to an example of the syntax.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/release/3.1/src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs#L115

**Comment by bricelam** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/processing-the-xml-file
