### ISSUE TITLE
Search for opportunities to use Dictionary.Remove while enumerating without defensive copy

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#18598]
.NET Core 3.0 added the possibility to safely remove entries from Dictionary while enumerating (https://github.com/dotnet/coreclr/pull/18854). We may have places where we copy defensively because this scenario was not previously supported - we may be able to remove these copies for better perf.

**Comment by michalczerwinski** [comment]
I this something I can help with?

StateManager.cs, line 601:
```csharp
                foreach (var keyValuePair in _referencedUntrackedEntities.ToList())
                {
                    if (keyValuePair.Value.Any(t => t.Item2 == entry))
                    {
                        _referencedUntrackedEntities.Remove(keyValuePair.Key);

                        var newList = keyValuePair.Value.Where(tuple => tuple.Item2 != entry).ToList();

                        if (newList.Count > 0)
                        {
                            _referencedUntrackedEntities.Add(keyValuePair.Key, newList);
                        }
                    }
                }
```
calling ToList() is not needed anymore, right? I think I managed to find all potential places for this change:

![image](https://user-images.githubusercontent.com/1795630/115911441-62731880-a46e-11eb-9e1e-1c5845799480.png)

**Comment by roji** [comment]
@michalczerwinski I think this is in TableSharingConcurrencyTokenConvention.cs, not RemoveDerivedEntityTypes.cs, no?

Yes, this does seem like a candidate for simplification/optimization. Note that it's only possible to reliably do this where we're handling a concrete Dictionary (as opposed to IDictionary).

**Comment by michalczerwinski** [comment]
I thoroughly verified all cases and ended up with https://github.com/dotnet/efcore/pull/24814
Not much, I know. Please let me know if you can see more potential patterns.
