### ISSUE TITLE
No more redundant comments

### ISSUE THREAD

**Issue by symphony2014** [dotnet/efcore#18606]
When go through the EntityFrameworkCode source code, I just want to figure out what's the use case for some class,or function ,and try to dive in and get more details, but frequently encounter like this comment :
"  This API supports the Entity Framework Core infrastructure and is not intended to be used
           directly from your code. This API may change or be removed in future releases."
Why not save the space, fill with more intrinsic details?

**Comment by ajcvickers** [comment]
@symphony2014 API documentation takes time to write and maintain. We do this for public API where many people will benefit from it. For internal APIs where the primary consumption is people reading the source code we prefer instead to let the code do the talking.

That is not too say it wouldn't be useful to document at least some of these APIs, but its a lot lower priority than many other things we could be working on, so in reality it is very unlikely to happen.
