### ISSUE TITLE
Ensure query was fully executed on DB side

### ISSUE THREAD

**Issue by d1mnewz** [dotnet/efcore#18610]
It would be really handy to have some way of saying that all the expressions should be translated to DB and evaluated only there, but not in memory using `IEnumerable` methods. 
Currently, we are using some npgSql provider for EF Core and struggling with the limited functionality we discover day by day, i.e. we create some functionality on ASP.NET Core app side that does complex query to DB, and we need to spin up a local database and run our tests against it, listen to verbose logs to verify that the query was created correctly. Obviously, double-checking each query takes a lot of time. I would rather love having a test that ensures that query was fully executed on DB side, or an extension method for `IQueryable` that throws if stuff was not executed on DB side.  

For me, the best case would be having a method you can apply onto your `IQueryable` which ensures that query was fully executed on DB side. Otherwise, an exception should be thrown and the code should be refactored. 

The semantics like `await db.Blogs.Where(x => x.Id % 2 == 0).ExecuteOnlyOnDb().ToListAsync()` would totally cover our cases.

**Comment by ajcvickers** [comment]
@d1mnewz This is [the behavior for the 3.0 release](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client). For previous releases, use `dbContextOptionsBuilder.ConfigureWarnings(w => w.Ignore(RelationalEventId.QueryClientEvaluationWarning));`.
