### ISSUE TITLE
Optimize analyzer by using Roslyn operations

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#18637]
@mvasani wrote in https://github.com/aspnet/EntityFrameworkCore/issues/18618#issuecomment-547187638:

> I notice that you invoke GetSymbolInfo on every single member access and object creation in the compilation. That is going to be extremely expensive, and certainly not recommended for semantic analysis. @sharwell has done bunch of performance measurements in this space, and can confirm the same. You should certainly move to RegisterOperationAction for these callbacks. You can register for following OperationKinds:
>
>    OperationKind.ObjectCreation - Gives back an IObjectCreationOperation
    OperationKind.Invocation - Gives back an IInvocationOperation
    OperationKind.FieldReference - Gives back an IFieldReferenceOperation
    OperationKind.MethodReference - Gives back an IMethodReferenceOperation
    OperationKind.PropertyReference - Gives back an IPropertyReferenceOperation
    OperationKind.EventReference - Gives back an IEventReferenceOperation
>
> Each of the above operations directly expose the underlying target symbol and would avoid invoking GetSymbolInfo.
>
> I would also avoid registering a syntax node action for ClassDeclarationSyntax and invoking GetDeclaredSymbol. Instead you can invoke RegisterSymbolAction with SymbolKind.NamedType and explicitly check the type kind on the call back to be TypeKind.Class.

**Comment by roji** [comment]
Thanks @sharwell, we'll discuss this.

**Comment by sharwell** [comment]
@roji It sounds like you reviewed the performance of the builds to show that the current builds are not impacted to the degree I described. If this analyzer is limited to running within this repository, it would certainly be reasonable to use that as the primary basis for your triage.

**Comment by roji** [comment]
@sharwell this analyzer isn't used only within this repo - it's flown to all users of EF Core, to prevent accidental usage of pubternal APIs. So making sure it runs efficiently is definitely important.

**Comment by roji** [comment]
In other words, the specific migrations example reported by the user in #3663 is no longer (significantly) affected, but huge user repos could suffer.

**Comment by sharwell** [comment]
@CyrusNajmabadi it sounds like this analyzer could be generalized and migrated to BannedApiAnalyzers to address some of the issues were looking into

**Comment by roji** [comment]
Check out https://github.com/aspnet/AspNetCore/blob/master/src/Components/Analyzers/src/ComponentParameterUsageAnalyzer.cs for a similar analyzer implemented with IOperation.

**Comment by roji** [comment]
Closing in favor of #19648 which contains repro information, etc.

**Comment by roji** [comment]
Duplicate of #19648
