### ISSUE TITLE
DbFunctionBuilder HasTranslation not accepting Expression after upgrade to EF Core v3.0

### ISSUE THREAD

**Issue by antoniopinedo** [dotnet/efcore#18644]
Following code used to work on EF Core v2.2.6:

```
public static class GuidFunctions
{
    public static bool IsGreaterThan(this Guid left, Guid right) => left.CompareTo(right) > 0;
    public static bool IsGreaterThanOrEqual(this Guid left, Guid right) => left.CompareTo(right) >= 0;
    public static bool IsLessThan(this Guid left, Guid right) => left.CompareTo(right) < 0;
    public static bool IsLessThanOrEqual(this Guid left, Guid right) => left.CompareTo(right) <= 0;
    public static void Register(ModelBuilder modelBuilder)
    {
        RegisterFunction(modelBuilder, nameof(IsGreaterThan), ExpressionType.GreaterThan);
        RegisterFunction(modelBuilder, nameof(IsGreaterThanOrEqual), ExpressionType.GreaterThanOrEqual);
        RegisterFunction(modelBuilder, nameof(IsLessThan), ExpressionType.LessThan);
        RegisterFunction(modelBuilder, nameof(IsLessThanOrEqual), ExpressionType.LessThanOrEqual);
    }
    static void RegisterFunction(ModelBuilder modelBuilder, string name, ExpressionType type)
    {
        var method = typeof(GuidFunctions).GetMethod(name, new[] { typeof(Guid), typeof(Guid) });
        modelBuilder.HasDbFunction(method).HasTranslation(parameters =>
        {
            var left = parameters.ElementAt(0);
            var right = parameters.ElementAt(1);
            return Expression.MakeBinary(type, left, right, false, method);
        });
    }
}
```

After upgrade to EF Core v3.0, the block for "modelBuilder.HasDbFunction(method).**HasTranslation**" throws the following error:

> Cannot implicitly convert type 'System.Linq.Expressions.BinaryExpression' to 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression'

While checking the methods signature for EF Core v2.2.6 and EF Core v3.0 I could notice that the HasTranslation function type was changed from Expression to SqlExpression, making the returned type incompatible (BinaryExpression returned by Expression.MakeBinary).

EF Core v2.2.6
[HasTranslation(Func<IReadOnlyCollection<Expression>,Expression>)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.dbfunctionbuilder.hastranslation?view=efcore-2.1)

EF Core v3.0
[HasTranslation(Func<IReadOnlyCollection<SqlExpression>,SqlExpression>)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.dbfunctionbuilder.hastranslation?view=efcore-3.0)

What would be the best way to have this working with EF Core 3.0 since it is not accepting Expression anymore but only SqlExpression?

**Comment by smitpatel** [comment]
Replace 
`return Expression.MakeBinary(type, left, right, false, method);`
With 
`return new SqlBinaryExpression(type, left, right, method.ReturnType,null);`

**Comment by antoniopinedo** [comment]
Hi Smit, that solves the problem with the Binary Expressions, so now there is a different inheritance path like:
Expression -> SqlExpression -> SqlBinaryExpression

Makes sense.  Thanks a lot for your help
