### ISSUE TITLE
Exclude Identity tables when database-first scaffolding

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/efcore#18647]
Please add a flag to Scaffold-DbContext to exclude the Identity tables created starting with dbo.AspNet*

There is no need to have an EF view of these tables as they are reached via the built-in Identity managers (userManager, roleManager, etc.)

Example flag -ExcludeIdentity

ref: https://github.com/aspnet/EntityFrameworkCore/issues/2725

**Comment by ajcvickers** [comment]
Note from triage: given that this isn't always the correct thing to do, and given that the tools already have a more general way to choose the tables, we're not going to implement a specific flag juts for this case.
