### ISSUE TITLE
API Review: Metadata: Review decision to add missing Get/TryGet pairs for indexes etc..

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#1866]
A few reasons to reconsider this:

1) Indexes, Keys and FKs do not have names and so do not fit the general pattern.
2) We don't appear to need these in the runtime.
3) It's hard to imagine needing the throwing versions for elements that can always be optional.

**Comment by rowanmiller** [comment]
We won't do this per Andrew's reasoning
