### ISSUE TITLE
Nested OwnsMany entities 'VistLambda' error

### ISSUE THREAD

**Issue by pavitrag123** [dotnet/efcore#18677]
I've multiple nested owns many relationships in my entity. Able to insert the data into cosmos db but facing below issue while retrieving data 

![image](https://user-images.githubusercontent.com/19691194/67948954-c8ca0280-fc0c-11e9-9676-d4fe33f5a927.png)

### Steps to reproduce
Same as issue https://github.com/aspnet/EntityFrameworkCore/issues/18265 that was marked as closed but still not working for me. 
Entity configuration:
![image](https://user-images.githubusercontent.com/19691194/67948835-8a344800-fc0c-11e9-8d47-29bce4640e9f.png)
This same entity configuration worked on efcore 3.0 previewPlease let me know if I missed anything. 
Thank you,

### Further technical details

EF Core version: 3.0.0.0
Database provider:Microsoft.EntityFrameworkCore.Cosmos
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by AndriySvyryd** [comment]
Issue #18265 was fixed in 3.1.0-preview2. Try that version when it's out or a nightly.
