### ISSUE TITLE
CrossStore tests are flaky

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#18682]
- Can_save_changes_and_query
- Can_register_multiple_context_types_with_default_service_provider
- Can_use_one_context_nested_inside_another_of_a_different_type_with_implicit_services
- Can_use_one_context_nested_inside_another_of_a_different_type

There might be a connection leak:
> System.InvalidOperationException : Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.

**Comment by smitpatel** [comment]
We can get some coverage till this is fixed by using sqlite.

**Comment by AndriySvyryd** [comment]
This failure is probably not specific to these tests, but affects the first test that uses LocalDB. We could try ensuring that LocalDB is running before the tests.

**Comment by smitpatel** [comment]
We also need to do this in helix precommands.
