### ISSUE TITLE
Query: make null semantics optimizations provider-specific

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#18689]
There are some null semantics optimizations we can do on SQL Server but not on other providers. We should consider making NullSemanticsRewritingExpressionVisitor provider specific.

example query:

```cs
ctx.Set<Weapon>().Select(
w => new
{
    w.Id,
    IsCartridge = !w.IsAutomatic && w.SynergyWithId == 1
})
```

null semantics rewriting visitor when initially encounters this expression determines that it cant do optimized translation, since its in the projection,
so we get:

```cs
!w.IsAutomatic && w.SynergyWithId == 1 && w.SynergyWithId != null
```

however, later on those conditions get converted to CASE blocks, in which optimized translation would be allowed. 

If null semantics would be a provider specific, it could always assume it can optimize conditions in projection (and maybe other places?), since search condition visitor will convert them all to CASE blocks.

Another optimization:

```cs
ctx.NullSemanticsEntity1.Where(e => e.NullableBoolA == e.BoolB == (e.IntA == e.NullableIntB)));
```

on sql server we can apply optimized translation to the child comparisons, because they get converted to CASE blocks, on other providers we can't.

**Comment by maumar** [comment]
Another optimization available on sql server:

```
true == NOT(a) -> NOT(a)
```

since NOT(a) on sql server (assuming we dont run relational null semantics) can never be null

**Comment by maumar** [comment]
removing properse-close, there is decent value in doing it in the future, imo

**Comment by smitpatel** [comment]
@maumar to present design of this in next design meeting.

**Comment by smitpatel** [comment]
@maumar - are you saying that fix to this issue is not needed? :trollface:
