### ISSUE TITLE
How to overwrite/set the nested owned types property?

### ISSUE THREAD

**Issue by blakeex** [dotnet/efcore#18697]
I am using EF Core 2.2 & here are my entity classes.

BigBoss class
  ```
  public class BigBoss {
           public Guid Id { get; set; }
           public SmallBoss SmallBoss { get; set; }
           // other stuff...
    }
```
BigBoss class owns SmallBoss,which owns Secretary and so on.

Here is the hierarchy: BigBoss -> SmallBoss -> Secretary.
Secretary has a foreign key which is Intern.
```
public class SmallBoss{
		public Secretary Secretary { get; set; }
	}

public class Secretary {
		public Intern Intern{ get; set; }
		public int? InternId{ get; set; }
		public double Number { get; set; }
	}

public class Intern {
		public int Id { get; set; }
		public string Identifier { get; set; }
		public string Name { get; set; }
	}
```
Here is how I setup the owned entity with data context (simplified for example purpose):
```
	protected override void OnModelCreating(ModelBuilder modelBuilder) {
	modelBuilder.Entity<BigBoss>()
			            .OwnsOne(
				            bigBoss => bigBoss.SmallBoss, smallBoss => {
					            smallBoss.OwnsOne(smallBoss2 => smallBoss2.Secretary);
				            });
}
```
When I am about to overwrite/set the `SmallBoss` property in existing `BigBoss` entity
```
	bigBossFound = myContext.BigBosses.FirstOrDefault(bigB => bigB.Id == bigBossId);

    // it does not work. smallBossInput & bigBossFound.SmallBoss will have all its properties set as null.
    // bigBossFound.SmallBoss = smallBossInput;

    // it works
    bigBossFound.SmallBoss.Secretary = smallBossInput.Secretary;

    // it cannot work // I could not recall the error message :/
    // myContext.BigBosses.Update(bigBoss);

    myContext.SaveChanges();

```
### Steps to reproduce
1) Implement the codes above in a .NET Core 3 project
2) Ensure your project (csproj) references include: 
`    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.*" />`
3) Debug the codes, which overwrite/set the `SmallBoss` property in existing `BigBoss` entity

### Questions:
 1.  Why I could not set the owned owned entity property (`BigBoss.SmallBoss`) directly?
 2.  Why I could not use `myContext.BigBosses.Update(bigBoss);` for owned entity?
 3.  What is the best practice/method to replace/update nested owned type entity? Or can I safely use `myContext.BigBosses.Update(bigBoss);` in EF Core 3.0?

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.InMemory, Microsoft.EntityFrameworkCore.SqlServer.Design, Microsoft.EntityFrameworkCore.Design
Target framework: NET Core 3.0
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by AndriySvyryd** [comment]
This was fixed in 3.1 Try again after updating (or using a nightly build) and post the exception message if is still doesn't work.
