### ISSUE TITLE
Is DbContextPool populated lazily?

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#18702]
This is more of a question than a feature request... Namely, is the `DbContext` pool populated with a full complement of instances on startup (128 by default), or are instances created lazily as they are requested? I assume its the latter, but just want to be sure.

**What problem are you trying to solve?**
I have a background service app that does some work every few minutes, forever. During each iteration, I create a new service scope, so that I can correctly get some short-lived `DbContext`s for that iteration. I know that there will only ever be N instances in use per iteration though, so I don't need the pool size to be greater than N. Obviously the best way to be explicit about this is to set `poolSize` in the call to `AddDbContextPool`, but I don't want to go adding numbers to my configuration (which will surely confuse future me) if I don't have to. 🙂

**Comment by AndriySvyryd** [comment]
@DanVicarel It's the latter. If at most N instances are used concurrently there shouldn't be more than N + 1 instances in the pool.
