### ISSUE TITLE
No support for .Net Frameork

### ISSUE THREAD

**Issue by lorinkundert** [dotnet/efcore#18736]
So move to a modern framework, ok, Linux it is

**Comment by ajcvickers** [comment]
Linux is a good choice for .NET Core.

**Comment by lorinkundert** [comment]
By dropping support for .NET Framework we lose all of our 3rd party controls and that raises the pain point to where we can replace Windows desktops with Linux

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/18141
