### ISSUE TITLE
More superflous null checks in EF Core 3.1 preview

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#18733]
In case you are still trying to hammer these out via something related to https://github.com/aspnet/EntityFrameworkCore/pull/18694 , some simple queries are still adding in IS NOT NULL where I would not expect them.

I have checked these using 3.1.0-preview2.19525.5 as well. (Latest daily build)

Example 1, hard coded predicate

`context.People.Where(p=>p.Name=="Erik").ToList();`

Results in 
the following predicate in the SQL (SQL Server and also SQLite)
`WHERE ([s].[Name] = N'Erik') AND [s].[Name] IS NOT NULL`

When using a variable, the parameterized query has definitely reduced the # of null checks (there were 4!) that we saw in EF Core 3.0 but this still seems extraneous. (I ran it by someone with much stronger DB knowledge than myself and he agreed). Hint as to who that as lies in my sample. :)

`WHERE ([s].[Name] =@__name_0) AND [s].[Name] IS NOT NULL`

### Further technical details

EF Core version:  3.1.0-preview2.19525.5
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3.6)

**Comment by smitpatel** [comment]
Latest daily builds are preview3 but I am not sure if they are being published properly. I am sure the fix is not in preview2 builds.

**Comment by julielerman** [comment]
Hmm. I  used the version shown on Nuget explicitly. I'll see what happens with "3.1.0-*" and the fees in my Nuget.config file.

**Comment by julielerman** [comment]
that and variations aren't giving me preview3 so maybe not published. Anyway...i'll just carry on. You can close this if you know you've already gotten to it.

**Comment by julielerman** [comment]
I now have 3.1.0-preview3.19553.2 and can see both of my examples now have no NULL checks in them.
closing and also making sure @ErikEJ sees this :)
