### ISSUE TITLE
Entity Framework Core with Azure Table Storage

### ISSUE THREAD

**Issue by leroylll** [dotnet/efcore#18737]
Any plans to have Entity Framework Core work with Azure Table Storage?

**Comment by ajcvickers** [comment]
@leroylll We currently have no plans. Duplicate of #18514

**Comment by brandonh-msft** [comment]
@ajcvickers it's not clear to me how this ask is a dupe of 18514 - is that the right source item?

**Comment by ajcvickers** [comment]
@brandonh-msft Thanks, wrong issue. Should be #1142.
