### ISSUE TITLE
Packages include icon twice

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#18749]
![image](https://user-images.githubusercontent.com/1226749/68165562-9a9e3880-ff14-11e9-884e-ea8eb0d0dd71.png)

cc @aspnet/build

**Comment by dougbu** [comment]
@wtgodbe please do the needful. Looks like the automated PRs get the PNG files from _both_ your changes and the latest Arcade SDK. I'm surprised this didn't hit errors in an Arcade dependency update PR.

**Comment by wtgodbe** [comment]
https://github.com/aspnet/EntityFrameworkCore/pull/18805

**Comment by wtgodbe** [comment]
Never mind, https://github.com/aspnet/EntityFrameworkCore/pull/18806
