### ISSUE TITLE
Error `Cannot INSERT NULL` with Default SQL Value set for Boolean Property

### ISSUE THREAD

**Issue by ackava** [dotnet/efcore#18757]
This was working correctly in EF 2.1

# Model
```c#
    [Table("Products")]
    public class Product
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ProductID { get; set; }

        public string Name { get; set; }
        public bool Archived { get; set; }
        public DateTime? LastUpdated { get; set; }
    }
```

# Context
```c#
    public class AppContext: DbContext
    {
        public AppContext(DbContextOptions options): base(options) {}

        public DbSet<Product> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // this was working in EF Core 2.1
            // this fails in EF 3.0
            modelBuilder.Entity<Product>().Property(x => x.Archived).HasDefaultValueSql("0");
        }
    }
```

Test
```c#
            using (var db = new AppContext(options.Options))
            {
                db.Products.Add(new Product { Name = "a" });
                // this fails as well
                db.Products.Add(new Product { Name = "a", Archived = false });

                db.SaveChanges();
            }
```

# Migration

In migration/creating database, default sql value is required at many places where table rows are inserted by some other stored procedures which are out of scope of EF.

### Steps to reproduce

1. Clone this Repo https://github.com/ackava/ef-core-3-insert-bug
2. Run SQL Query to create table against test database
3. Change connection string and run, you will end up with Cannot INSERT NULL

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 Latest Stable Release
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@ackava Configure the property not to use generated values when inserting:
```C#
modelBuilder
    .Entity<Product>()
    .Property(x => x.Archived)
    .HasDefaultValueSql("0")
    .ValueGeneratedNever();
```

**Comment by henrypuspurs** [comment]
I just had this issue. Normal configuration on a bool as I've done many times

```cs
builder.Property(_ => _.IsAvailable)
            .IsRequired()
            .HasDefaultValue(true);
```
would not work until I changed it to
```cs
builder.Property(_ => _.IsAvailable)
            .IsRequired()
            .HasDefaultValueSql("1")
            .ValueGeneratedNever();
```

Still doesnt make any sense. Could it be a bad snapshot from multiple migrations being merged without a rebase and recreated migration?
