### ISSUE TITLE
EF core 3 migration tool ignores Default Database Location property

### ISSUE THREAD

**Issue by zhou-xb** [dotnet/efcore#18779]
I am learning ASP.NET w/ Visual Studio Community 2019, and follow the tutorial to create Razor Pages web app, am just trying the EF core 3 migration tool. I learned that **Update-Database** command always creates database at folder **C:\Users\<current user>**, although I changed the **Default Database Location** property of server (localdb)\MSSQLLocalDB to other folder.

I hope the migration tool can make use of **Default Database Location** property when creating new database.

**Comment by ajcvickers** [comment]
@zhou-xb My understanding is that LocalDb never uses the Default Database Location. You need a normal SQL Server instance for that--SQL Express should work. 

I tried to find documentation for this, but couldn't find anything specific. You might want to try asking at https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/view-or-change-the-default-locations-for-data-and-log-files?view=sql-server-ver15

**Comment by zhou-xb** [comment]
@ajcvickers Thanks a lot for your information.
