### ISSUE TITLE
Request to open PR 5607

### ISSUE THREAD

**Issue by mhamri** [dotnet/efcore#18776]
Requesting to merge PR 
https://github.com/aspnet/EntityFrameworkCore/pull/5607

I am so upset that the PR was there but didn't merged. it was a long-awaited feature to happen.

as a team, we are doing a feature branch. each branch come with its own migration. as a convention, we are putting the task number in front of the migration and if it's something we needed to write custom script (somethign not generated by ef migration) then we add _custom at the end 

atm it looks like this 
![image](https://user-images.githubusercontent.com/8991783/68268555-94819680-0091-11ea-9659-c4cab421406d.png)

as you can see most of the migration is coming with 2 or three files. it could be reduce to 2 files with that PR.

another problem that PR could solve is our development flow. 

it's not always obvious that we need custom migration at the start. we do changes, we create migration. later in PR review or with intuition, it comes out there is a need for custom migration. 

now the hardship starts. we need to remove the migration. create an empty migration (with custom file renaming and timestamp matching) and put back the migration again.

and god forbid if there is an after migration script and we want to do some more changes to the model. we need to copy the content of custom migration to another file. remove the last two migrations. do the changes. create a migration and put back the custom migration there again. and we need to do this again and again until we are happy with the changes. 

with that PR we didn't need to remove the custom migration at all. 

with that PR, we just needed an empty file with the same class name and just made it partial. it could be added either before or after the migration to handle all the scenario. 

that's the whole idea behind the partial class. one portion generated by the machine and one portion is generated by the human. but now the class is partial but only support machine-generated part and there is no hook for human-generated part!

please merge the PR!

**Comment by ajcvickers** [comment]
> we need to remove the migration. create an empty migration (with custom file renaming and timestamp matching) and put back the migration again.

Why do you need to do this? Why not edit the generated migration?

> remove the last two migrations. do the changes. create a migration and put back the custom migration there again. 

Why not just add another migration?

> one portion generated by the machine and one portion is generated by the human

Migrations are not generated with the intention that they will never be changed. Using EF to scaffold a migration is a starting point. It is intended that the migration then be edited as needed.

**Comment by mhamri** [comment]
> Why do you need to do this? Why not edit the generated migration?

because the model is changed. or the PR is merged but there are more to be done and it only can be done before certain migration. let say we need to have a before migration script.
so the flow is like this: 

1. I use ef to generate a migration based on some model change
2. I create an empty migration and add the custom script
3. after PR I understand I need to change the model and have a before migration script. so what other option do I have to regenerate the step 1 migration and also insert a migration before step 1?

correct me if I'm wrong but there are two methods. 
a. remove the migrations one by one up to step 1 (so the DB also update along the way) and recreate everything from scratch
b.  or update the DB to the before step 1 migration. create a custom file, fix the timestamp and everything to be able to inject the custom migration. then copy the snapshot from previous branch or parent branch (because your current snapshot is based on the existing model). then recreate step1

and the problem with migration with big teams is each time we rebase a branch more migration is coming to your branch, so we need to regenerate the migration each time and put them at the bottom of the migration list. 

but there are cases that you understand another branch already removed or changed some data that you needed for your branch. then you want to have a copy of those changed or lost information somewhere and you need to modify their migration or add a before migration. 

regenerating their migration is the most time consuming of the work.

> Why not just add another migration?

because the sequence matters. specially if there is a data loss or data shape change. some action only can happen at that point in time. we don't have any method to inject a migration before another migration. we need to move to the top of the tree and then walk down again. 

> Migrations are not generated with the intention that they will never be changed. Using EF to scaffold a migration is a starting point. It is intended that the migration then be edited as needed.

I understand that. but the real-life development flow isn't like contoso app. we create model, we create a migration, we do the review, we drop migration, we do model change again and again and create migration again and again. and we rebase, we change data shape on a daily basis. but each time we can't go and rewrite the whole custom script that we wrote last time or modify the newly generated migration to amend those changes. that's why we have to keep a backup of what we wrote last time in another file. write the script, copy it to another editor. update the DB, ... 

I hope I could demonstrate our daily frustration when a team try to work together and use migration.

**Comment by ajcvickers** [comment]
@mhamri Can you post an example of what kind of code you put in the "custom script"?

/cc @bricelam to take a look.

**Comment by mhamri** [comment]
sure, I am posting a fairly small one in here for easier read and discussion

![image](https://user-images.githubusercontent.com/8991783/68757280-a8576a80-0646-11ea-82a9-86a784e352e0.png)

### a little brief about business logic 
previously when we were creating our application, we thought that each of the tasks in the app has its own risk calculation. later when our understanding of the application grew, we came to the conclusion that we can have one single place for all the risk calculation with a little different formula. 

so for this task, we need to move some of the columns to another table and at the same time recalculate them. 

first, we need to take a back up of those values. our naming convention to take the backup is the `backup_taskNumber_description`. we need this backup table, especially for the down() method, because after applying the migration we don't know how to recalculate the old values. 


```C#
 public partial class _1734backupactivitytofindingRecommendations_custom : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder) {
           migrationBuilder.Sql(@"SELECT Id,Recommendations, Urgency, DueDate , Action,ActivityId, ActivityOwnerId ,Status,CreatedAt  INTO backup_1734_ActivityModule_ActivityFinding FROM ActivityModule_ActivityFinding ");
        }

        protected override void Down(MigrationBuilder migrationBuilder) {

            migrationBuilder.Sql(@"UPDATE 
                                                        ActivityModule_ActivityFinding
                                                   SET
                                                        Action = r.Action ,
                                                        ActivityOwnerId = r.ActivityOwnerId ,
                                                        DueDate = r.DueDate ,
                                                        Recommendations = r.Recommendations, 
                                                        Status = r.Status ,
                                                        Urgency = r.Urgency                  
                                                   FROM                                                                                                            
                                                        (SELECT fr.Id,  fr.Action ,fr.ActivityOwnerId, fr.DueDate,  fr.Recommendations, 
                                                             fr.Status, fr.Urgency    
                                                             FROM  backup_1734_ActivityModule_ActivityFinding AS fr
                                                         ) r                                   
                                                    WHERE r.Id= ActivityModule_ActivityFinding.Id ");

            migrationBuilder.DropTable("backup_1734_ActivityModule_ActivityFinding");
        }
    }
```
after that, we create a new table. remove the columns from the old tables and refactor whatever we can. 
then we call the `ef migration add` to create a new migration.

```C#
public partial class _1734findingRecommendations : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ActivityModule_ActivityFinding_UserModule_User_ActivityOwnerId",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropForeignKey(
                name: "FK_ActivityModule_ActivityFinding_ActivityModule_Activity_IgrActivityId",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropIndex(
                name: "IX_ActivityModule_ActivityFinding_ActivityOwnerId",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropIndex(
                name: "IX_ActivityModule_ActivityFinding_IgrActivityId",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "Action",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "ActivityOwnerId",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "DueDate",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "IgrActivityId",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "Recommendations",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "Status",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.DropColumn(
                name: "Urgency",
                table: "ActivityModule_ActivityFinding");

            migrationBuilder.CreateTable(
                name: "ActivityModule_FindingRecommendation",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ActivityFindingId = table.Column<long>(nullable: false),
                    Recommendation = table.Column<string>(nullable: true),
                    Urgency = table.Column<int>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    PlannedStartDate = table.Column<DateTimeOffset>(nullable: true),
                    PlannedEndDate = table.Column<DateTimeOffset>(nullable: true),
                    ActualStartDate = table.Column<DateTimeOffset>(nullable: true),
                    ActualEndDate = table.Column<DateTimeOffset>(nullable: true),
                    ActionOwnerId = table.Column<long>(nullable: true),
                    ActionUpdate = table.Column<string>(nullable: true),
                    CreatedAt = table.Column<DateTimeOffset>(nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActivityModule_FindingRecommendation", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ActivityModule_FindingRecommendation_ProjectModule_ProjectUser_ActionOwnerId",
                        column: x => x.ActionOwnerId,
                        principalTable: "ProjectModule_ProjectUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ActivityModule_FindingRecommendation_ActivityModule_ActivityFinding_ActivityFindingId",
                        column: x => x.ActivityFindingId,
                        principalTable: "ActivityModule_ActivityFinding",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ActivityModule_FindingRecommendation_ActionOwnerId",
                table: "ActivityModule_FindingRecommendation",
                column: "ActionOwnerId");

            migrationBuilder.CreateIndex(
                name: "IX_ActivityModule_FindingRecommendation_ActivityFindingId",
                table: "ActivityModule_FindingRecommendation",
                column: "ActivityFindingId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ActivityModule_FindingRecommendation");

            migrationBuilder.AddColumn<string>(
                name: "Action",
                table: "ActivityModule_ActivityFinding",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ActivityOwnerId",
                table: "ActivityModule_ActivityFinding",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "DueDate",
                table: "ActivityModule_ActivityFinding",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "IgrActivityId",
                table: "ActivityModule_ActivityFinding",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Recommendations",
                table: "ActivityModule_ActivityFinding",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Status",
                table: "ActivityModule_ActivityFinding",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "Urgency",
                table: "ActivityModule_ActivityFinding",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_ActivityModule_ActivityFinding_ActivityOwnerId",
                table: "ActivityModule_ActivityFinding",
                column: "ActivityOwnerId");

            migrationBuilder.CreateIndex(
                name: "IX_ActivityModule_ActivityFinding_IgrActivityId",
                table: "ActivityModule_ActivityFinding",
                column: "IgrActivityId");

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityModule_ActivityFinding_UserModule_User_ActivityOwnerId",
                table: "ActivityModule_ActivityFinding",
                column: "ActivityOwnerId",
                principalTable: "UserModule_User",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityModule_ActivityFinding_ActivityModule_Activity_IgrActivityId",
                table: "ActivityModule_ActivityFinding",
                column: "IgrActivityId",
                principalTable: "ActivityModule_Activity",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
```

after that, we need to put back everything back to its place 

```
public partial class _1734copyactivitytofindingRecommendations_custom : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO ActivityModule_FindingRecommendation(ActivityFindingId,Recommendation,
                                                Urgency,ActionOwnerId,Status,PlannedStartDate,PlannedEndDate,ActualStartDate,ActualEndDate,ActionUpdate,CreatedAt)
                       SELECT actFind.Id AS ActivityFindingId, actFind.Recommendations, actFind.Urgency,	pu.Id AS ActionOwnerId,
                        Status = CASE 
                        WHEN Status = 3 and DueDate is not null and ActivityOwnerId is not null THEN 4
                        WHEN Status = 1 and DueDate is not null and ActivityOwnerId is not null THEN 2
                        WHEN Status = 2 and DueDate is not null and ActivityOwnerId is not null THEN 2
					    ELSE 1
					    END,
                        PlannedStartDate = CASE 
                        WHEN Status = 3 and DueDate is not null THEN actFind.DueDate
                        WHEN Status = 1 and DueDate is not null THEN actFind.DueDate
                        WHEN Status = 2 and DueDate is not null THEN actFind.DueDate                        
					    ELSE NULL
					    END,
                        PlannedEndDate = CASE 
                        WHEN Status = 3 and DueDate is not null and ActivityOwnerId is not null THEN actFind.DueDate
                        WHEN Status = 1 and DueDate is not null and ActivityOwnerId is not null THEN actFind.DueDate
                        WHEN Status = 2 and DueDate is not null and ActivityOwnerId is not null THEN actFind.DueDate
					    ELSE NULL
					    END,
                        ActualStartDate = CASE 
                        WHEN Status = 3 and DueDate is not null and ActivityOwnerId is not null THEN actFind.DueDate                        
					    ELSE NULL
					    END,
                        ActualEndDate = CASE 
                        WHEN Status = 3 and DueDate is not null and ActivityOwnerId is not null THEN actFind.DueDate                        
					    ELSE NULL
					    END,actFind.Action as ActionUpdate,
                        actFind.CreatedAt
                        FROM backup_1734_ActivityModule_ActivityFinding actFind
			            INNER JOIN ActivityModule_Activity AS act ON act.Id = actFind.ActivityId
			            INNER JOIN ProjectModule_ProjectUser AS pu ON pu.ProjectId = act.ProjectId and actFind.ActivityOwnerId = pu.UserId");
        }

        protected override void Down(MigrationBuilder migrationBuilder) {
            migrationBuilder.Sql("truncate table ActivityModule_FindingRecommendation");
        }
```

so you maybe ask when do you drop the backup tables? the answer is in the deployment migration, before the deployment, we create an empty migration without down that can drop all the backup tables and add anything else that doesn't fall into the development migration script.

and please note that we are not reaching to this script straight forward. I remember for this case the developer right away jumped to the code and deleted the old columns and created some new columns. then he understood that he need to also move the activity owner to the new table. removed the migration and redo some stuff. then when he tried to write the down() migration, then he understood he forgot the before migration ....

**Comment by ajcvickers** [comment]
@smitpatel To respond.

**Comment by smitpatel** [comment]
Looking at whole description, editing migration files directly is the right thing to do. It easily helps while rebasing with incoming changes. The custom scripts may be needed to be saved and moved around while recreating migration. Scaffolding additional migration to put script is pit of failure. You are causing more pain to yourself now that you need to revert multiple migrations.

I looked at the PR, while it would add something if you add method, it would not scaffold anything for you. You will be still in the same boat that you need to copy over script because when you regenerate the migration, the migration class would be differently named and now you have inconsistency in file name. Further, the code does not update to scaffold those methods in newly generated migration by default.

Now, to solve the issue of custom scripts, all you are doing in custom script file is calling Sql. (In some cases dropping-recreating tables which are not in EF Core model in first place). So rather than trying to use partial class, you should just create associated helper class - `findingRecommendations_Helper.cs` Make it a static class, create static methods in the class with passing MigrationBuilder parameter. Then call those methods from scaffolded migrations up/down method as needed. Not only you don't need to copy any code (which you would have to even with that PR merged), just 4 lines edit at max and you can get whatever you want. You never have to recreate those classes either even if you get more changes from upstream since their naming has nothing to do with migrations at that point.

Closing this issue as not needed. It is all about refactoring code when editing migrations. Helper class with static method is more robust way to do then scaffolding those methods in everyone's migration. (which still suffers from code copy over when regenerating migration).

**Comment by mhamri** [comment]
@smitpatel I think you are wrong! 

>editing migration files directly is the right thing to do. It easily helps while rebasing with incoming changes.

when the team is big, the amount of changes is too much that after each rebase you can't edit the scaffolded code manually. you have to rely on migration and it's a good thing to do. in this way we don't need to look into the whole migration each time that we rebase (that is our daily routine). 


>Scaffolding additional migration to put script is pit of failure

I didn't ask the ef to create any new migration for me. **all I want is 4 virtual methods in the base class (Migration) that I can override them (in a partial class).** these 4 methods should be BeforeUp, AfterUp and BeforeDown and AfterDown. that's all I want. atm you have two PR that doing that. from different ppl. and I'm another guy with the same request. 

>I looked at the PR, while it would add something if you add method, it would not scaffold anything for you. You will be still in the same boat that you need to copy over script because when you regenerate the migration, the migration class would be differently named on regeneration and now you have inconsistency in file name. Further, the code does not update to scaffold those methods in newly generated migration by default.

again you are wrong! if you merge the PR we can have something like this 

![image](https://user-images.githubusercontent.com/8991783/69110145-bda01f00-0ab4-11ea-9ae7-ca2035cd1097.png)

all these custom scripts can be picked by ef automatically and there is no need after each migration we edit the scaffolded code.

in this way, we only need to keep the name of the migration consistent. since the timestamp is not part of the class name, hence we don't need to copy and modify the migration each time. 

as long as we have the same name for the migration (that can be done easily with the name of the branch and some script) we don't need even modify the scaffolded migration. why on each development we have to open the migration and copy-paste some static method there? that's the same thing if we have 4 hooks, isn't it? if I create a static method and put it at the first line of the up method is same as beforeUp()? and if I put it at the end of the up method is like afterUP(). it's same but the development and number of times that we need to do this is less. the files can go next to each other. can be found easily with the IDE, so why not? 

if you fear is that what we do here is something that the other frameworks are not doing, it's because they don't have the partial file! if C# support such thing, so why we don't use it? if someone doesn't want to override those methods and do like the normal flow, so let them do. you don't need to expose the hooks in the migration file, but at the same time, you don't stop others to use these features. 

>just 4 lines edit at max and you can get whatever you want. 

look at this way, please. it's 4 lines of code 10 times a day, 40 line of redundant code obligated by the framework on the developer per day! 

@ajcvickers for comment

**Comment by ajcvickers** [comment]
@mhamri We have discussed this as a team and several people have taken a look at it. On balance we don't believe this is something we want to do for the reasons already stated.

**Comment by mhamri** [comment]
@ajcvickers thanks for the reply, but looking at the @smitpatel response, I believe my request understood incorrectly. he thought that I'm asking for more of the migration file to be generated but as I mentioned before, I am asking for **4 empty virtual methods in the base class (Migration) that I can override them (in a partial class)**. it doesn't affect the current flow nor it changes how the migration is being used or generated. so what is the harm to add something that doesn't affect anything but it helps the dev flow?
as you have multiple PR from different ppl that doing it, it proves that we are not alone with doing this exercise during our development. so may I know what is rational with not adding this?
