### ISSUE TITLE
Change tracking of derived entities are tracked by the base type

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#1878]
Hi,

I have the following TPH setup:

```
public abstract class Base
{
    public int Id { get; set; }
    public string BaseString { get; set; }
}

public class Derived : Base
{
    public string DerivedString { get; set; }
}

public DbSet<Base> Bases { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var model = modelBuilder.Model;
    var baseEntityType = model.GetEntityType(typeof(Base));
    baseEntityType.AddAnnotation("Relational:DiscriminatorProperty", "discriminator");

    var derivedEntityType = model.AddEntityType(typeof(Derived));
    derivedEntityType.BaseType = baseEntityType;
    derivedEntityType.AddAnnotation("Relational:DiscriminatorValue", "derived");
}
```

The quering works, but it seems as if the results from a query arrives in the change tracker as a wrong type, namely the base type, so changes on the properties belonging to `Derived` are not tracked.

To see this, consider the following observations where there is only one record in the database, and it is of type `Derived`.

This does work ("Hello" is written to the database):

```
var entity = _db.Bases.First();
// entity is of type Derived. Perfectly fine.
entity.BaseString = "Hello";
_db.SaveChanges();
```

This does not work ("Hello" is not written to the database):

```
var entity = _db.Bases.First();
// entity is of type Derived. Perfectly fine.
entity.DerivedString = "Hello";
_db.SaveChanges();
```

This does also not work:

```
var entity = _db.Bases.First();
// entity is of type Derived. Perfectly fine.
entity.DerivedString = "Hello";
_db.Entry(entity).State = EntityState.Modified;
_db.SaveChanges();
```

Neither does this:

```
var entity = _db.Bases.OfType<Derived>().First();
entity.DerivedString = "Hello";
_db.SaveChanges();
```

But it turns out that the following does work:

```
var entity = _db.Bases.OfType<Derived>().First();
entity.DerivedString = "Hello";
_db.Entry(entity).State = EntityState.Modified;
_db.SaveChanges();
```

This issue is probably related to the review stuff in #1707.

**Comment by rowanmiller** [comment]
Work is tracked by https://github.com/aspnet/EntityFramework/issues/1707

**Comment by rmja** [comment]
@rowanmiller I am reopening this one as #1707 was closed but the problem still exists, even in the latest RC2 bits.

**Comment by rowanmiller** [comment]
Turns out we have https://github.com/aspnet/EntityFramework/issues/4817 tracking this one now.
