### ISSUE TITLE
Don't share change trackers between DbContext instances

### ISSUE THREAD

**Issue by groege** [dotnet/efcore#18798]
```
using (var db = new MyContext()) {
    var myEntity = db.MyEntities.FirstOrDefault(x => x.Guid == guid);
    ...
}
```
When calling it the second time, with the same guid, it will thrown an Exception telling me another instance with this guid is already being tracked, how is this possible - does it track changes between different instances of DbContext?
How can I disable this -> i do want to track changes within the using block.
But imho two different context objects should never share tracked objects.
Am I missing something?

EF Core version: 3.0 & 3.1 preview 2
Database provider: Microsoft.EntityFrameworkCore.SqLite
Target framework: NetStandard 2.1 (Using Android)
Operating system: Win10
IDE: Visual Studio 2019 16.4.0 Preview 3.0

**Comment by roji** [comment]
@groege it's not clear exactly what you're referring to. The following code sample loads the same entity several times inside the same context and also within different contexts (active at the same time), and there's no issue. Change tracking is something that is done at the DbContext level, not globally. Could you please submit a clear code sample?

```c#
class Program
{
    static void Main(string[] args)
    {
        var guid1 = Guid.NewGuid();

        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            ctx.Blogs.Add(new Blog { Guid = guid1, Name = "Blog1" });
            ctx.SaveChanges();
        }

        using (var ctx1 = new BlogContext())
        {
            var blog1 = ctx1.Blogs.FirstOrDefault(b => b.Guid == guid1);
            var blog1again = ctx1.Blogs.FirstOrDefault(b => b.Guid == guid1);
        }

        using (var ctx2 = new BlogContext())
        {
            var blog1 = ctx2.Blogs.FirstOrDefault(b => b.Guid == guid1);

            using (var ctx3 = new BlogContext())
            {
                var blog1againInside = ctx3.Blogs.FirstOrDefault(b => b.Guid == guid1);
            }
        }
    }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(...);
}

public class Blog
{
    [Key]
    public Guid Guid { get; set; }
    public string Name { get; set; }
}
```

**Comment by groege** [comment]
That is really weird, came back to work today and now it works (without code changes)... Really weird, thank you for your time!
