### ISSUE TITLE
Error after removing SuppressForeignKeyEnforcement() after EF Core 3.0 upgrade

### ISSUE THREAD

**Issue by yonathanseleshi** [dotnet/efcore#18792]
I am working on a Xamarin Forms App and I upgraded to Xamarin iOS 13.8 .  After I upgraded I noticed my dbcontext.savechanges was no longer working so I upgraded my EF Core and EF Core Sqlite to 3.0.

After doing this I got an error stating 

optionsBuilder.UseSqlite($"Filename={DBPath}", x => x.SuppressForeignKeyEnforcement()); 

no longer worked as x.SuppressForeignKeyEnforcement was no longer available.  I saw another person report this issue here:

https://github.com/aspnet/EntityFrameworkCore/issues/17344

and their solution was to simply remove the SuppressForeignKeyEnforcement() part, but that isn't working for me.

When I tried that my dbcontext.savechanges calls are still not saving and I am getting the following error:

"Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'."

Any solutions?

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: (e.g. .NET Core 3.0)
Operating system: iOS
IDE: Visual Studio Mac 8.3.7

**Comment by ajcvickers** [comment]
@bricelam The [breaking change documentation](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#ef-core-no-longer-sends-pragma-for-sqlite-fk-enforcement) says:

> Foreign keys are enabled by default in SQLitePCLRaw.bundle_e_sqlite3, which is used by default for EF Core. For other cases, foreign keys can be enabled by specifying `Foreign Keys=True` in your connection string.

Does that mean that `Foreign Keys=False` will disable FK enforcement? (I remember we had discussion around this, but I don't remember the outcome.)

**Comment by ajcvickers** [comment]
Confirmed with @bricelam that this should work.
