### ISSUE TITLE
SQLite cannot order by expressions of type 'decimal'. Convert the values to a supported type or use LINQ to Objects to order the results.

### ISSUE THREAD

**Issue by jhcfmm** [dotnet/efcore#18799]
I have upgraded a VS2017 project with .NetStandard2.0 and EFCore 2.x to VS21019, .NetStandard2.1 and EFCore 3.0.  Got hit by the issue where a function parameter could not be included in the LINQ command since the server side could not handle it and would throw an exception.  Removed the function part of the query and got hit by the: "SQLite cannot order by expressions of type 'decimal'. Convert the values to a supported type or use LINQ to Objects to order the results." exception.  
Putting the query in a try/catch does not catch the exception so I can't see any inner exception information if there is any.  (Project is a Xamarin project and main target is Android.)  The table definition in SQLITE is as follows:

```sql
CREATE TABLE "Uabts" (
    "Sid" INTEGER NOT NULL CONSTRAINT "PK_Uabts" PRIMARY KEY AUTOINCREMENT,
    "Kdnr" INTEGER NOT NULL,
    "Rev_Nr" INTEGER NOT NULL,
    "UAbtNr" INTEGER NOT NULL,
    "WKB_Geometry" BLOB NOT NULL,
    "XMin" REAL NOT NULL,
    "YMin" REAL NOT NULL,
    "XMax" REAL NOT NULL,
    "YMax" REAL NOT NULL,
    "LabelX" REAL NOT NULL,
    "LabelY" REAL NOT NULL,
    "BestAlter" INTEGER NOT NULL
)
```

The section of code works once in the page to display the query on a map is:

```C#
List<Uabt> listUabtBdrs = null;
using (var db = new ClientDb())
{
	db.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
	List<Uabt> listUabtBdrs = db.Uabts.Where(c=>c.Kdnr == selKdnr && c.Rev_Nr == selRev_Nr && (c.UAbtNr / 100000) == selAbt).ToList();
}
```

The same query later when trying to display information on a single selected point throws the exception.  I have attempted to skip the .Where clause and add a specific sort to see if it would help with no success.:

```C#
List<Uabt> dtUabtSubset = null;
using (var db = new ClientDb())
{
	db.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
	try
	{
		dtUabtSubset = db.Uabts.AsNoTracking().ToList();
	}
	catch (Exception ex)
	{
		// Excption is thrown on query but never gets to here.
		string exMessage = ex.Message;
	}
	// This query also throws an exception.
	dtUabtSubset = db.Uabts.AsNoTracking().OrderBy(c => c.Kdnr).ToList();
}
```

I am at wits end trying to figure out what is causing this as there are NO decimal types in this table and I am not attempting any type of sort.  Not sure if the error is in EFCore, .NetStandard, Xamarin, etc.

**Comment by ajcvickers** [comment]
@jhcfmm Pleas post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by sciocoder** [comment]
@jhcfmm SQLite doesn't natively support decimal data types. 
https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations#query-limitations

**Comment by jhcfmm** [comment]
Look at trying to create a simple project that can reproduce the error.  The existing VisaulStudio 2019 / Xamarin project was throwing an exception and stopping the code with the "executing line pointer" pointing to the query of a table with NO decimal type, but looking at all the sorts in the application, the page that was supposed to open with a pointer to the table did read a table with decimals and a sort on the decimal column.  It is likely that it is happening in the other page, but the exception pointer is not showing the correct location of the exception.

**Comment by jhcfmm** [comment]
The problem was in the page that should have been opened, but while debugging and using the single step process, the exception was appearing when trying to step past the query in the page before the other page should have been built.  This issue is being closed.  (Still don't know why it was stopping while trying to use the step over feature on the query and not the query on the next page.)
