### ISSUE TITLE
Support SOP in Entity Framework

### ISSUE THREAD

**Issue by grecinto** [dotnet/efcore#1879]
I am interested in integrating/supporting EF in this pure managed code, NoSQL engine code library (see https://sop.codeplex.com/ for details). I can see this to be a win-win feature for everybody. SOP provides solution to a lot of data persistence problems from personal repo/small shop to the Enterprise.

In addition, EF itself may benefit from tremendous, high speed virtualized RAM caching SOP provides.

**Comment by grecinto** [comment]
Hi Rowan/et al,

Pls. let me know if you need anything from me.

I am not too much familiar w "engagement protocol" on things like this. But I am open & flexible. I can provide anything within my limits to get some traction on this. :)

Pls. feel free to provide guidance/direction or any feedback when ready.

Thx much, sincerely,
-G.

**Comment by rowanmiller** [comment]
Hey,

Thanks for reaching out to us. At the moment our code base is still very much in-flux so there isn't really any documentation etc. as things change day-to-day. The best way to get started is to take a look at the code for the providers we have and then ask questions as you run into issues. The providers in our code base are mostly relational at the moment, but there is an InMemory provider that may be helpful to you.

The https://github.com/npgsql/npgsql project is also working on EF7 support at the moment, so you may find some useful discussion between the EF and npgsql teams in our issue trackers (that is a relational provider though, so their implementation will be quite different to yours).

Of course, as our code base stabilizes and we get closer to an RTM we will provide documentation etc. for provider writers.

~Rowan

**Comment by grecinto** [comment]
Thx, I'll look into those (sample) provs & d InMemory version.

**Comment by grecinto** [comment]
SOP Synopsis

SOP is a modern, scalable, portable, lightweight & highly adaptive object management system packaged in a code library. What separates SOP from the rest of the pack is its proven adaptability and being written in managed code (c#), it can be adapted quite quickly and easily across diverse use-cases, e.g. - from very thin use as a RAM virtualizer/high performance persisted data cache or on the opposite end, used as a data mgmt platform for providing high performance, enterprise scalable/durable data storage solution that runs on a new env't like the Azure cloud to take advantage of massive distributed processing & geo-redundancy it provides. All these while achieving its primary goal of reducing (and thus, optimizing!) persistence layers involved in application data mgmt to bare minimum.

**Comment by grecinto** [comment]
UPDATE: the just released version of SOP B-Tree .Net (v4.8) now sports LINQ to Objects extensions which fully enables complete LINQ to Objects functionality inter-operability. Somehow, LINQ to Entities support suddenly becomes less of a priority for this code library.

I wonder though whether there is still a need for this feature? 'other than perhaps, for using LINQ to Entities as an abstraction "layer", which anyway may not be necessary for SOP due to it operates in the context of the user code/objects (POCOs), thus, it already puts the user code as 1st class citizens. 

LINQ to Objects seems to be ideal, 'talking about "query language" per se. Pls. advice on your opinion, if/when time permits. 'just wanted to get your point of view.

**Comment by rowanmiller** [comment]
Docs on writing a provider at https://docs.microsoft.com/en-us/ef/core/providers/writing-a-provider

This isn't a provider we would put in the core project, it should be a community maintained provider.
