### ISSUE TITLE
Unable to install EF Core tools 3.0.0 in .net Core 3.0

### ISSUE THREAD

**Issue by geedsen** [dotnet/efcore#18800]
Trying to create the initial migration 
dotnet ef migrations add initial --startup-project ..\CojacDB\CojacDB.csproj

results in the following error:

The EF Core tools version '2.1.4-rtm-31024' is older than that of the runtime '3.0.0'. Update the tools for the latest features and bug fixes.
Unable to create an object of type 'CojacJobContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

running dotnet ef --version shows:

Entity Framework Core .NET Command-line Tools
2.1.4-rtm-31024

doing an install of the 3.0.0 tools:

Installing NuGet package Microsoft.EntityFrameworkCore.Tools 3.0.0.
Committing restore...
Generating MSBuild file D:\Users\Ben\Source\Repos\Gathering\Quadrotech.Core.Data.Agent\obj\Quadrotech.Core.Data.Agent.csproj.nuget.g.props.
Writing assets file to disk. Path: D:\Users\Ben\Source\Repos\Gathering\Quadrotech.Core.Data.Agent\obj\project.assets.json
Restore completed in 183.83 ms for D:\Users\Ben\Source\Repos\Gathering\Quadrotech.Core.Data.Agent\Quadrotech.Core.Data.Agent.csproj.
Successfully installed 'Microsoft.CSharp 4.6.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.EntityFrameworkCore 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.EntityFrameworkCore.Abstractions 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.EntityFrameworkCore.Analyzers 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.EntityFrameworkCore.Design 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.EntityFrameworkCore.Relational 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.EntityFrameworkCore.Tools 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.Extensions.Caching.Abstractions 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'Microsoft.Extensions.Caching.Memory 3.0.0' to Quadrotech.Core.Data.Agent
Successfully installed 'System.Collections.Immutable 1.6.0' to Quadrotech.Core.Data.Agent
Successfully installed 'System.ComponentModel.Annotations 4.6.0' to Quadrotech.Core.Data.Agent
Successfully installed 'System.Diagnostics.DiagnosticSource 4.6.0' to Quadrotech.Core.Data.Agent
Successfully installed 'System.Threading.Tasks.Extensions 4.5.2' to Quadrotech.Core.Data.Agent
Executing nuget actions took 1.3 sec
Time Elapsed: 00:00:02.3615022

But the problem remains, the exact error occurs on the migration. and the dotnet ef --version still shows the 2.1.4-rtm-31024

**Comment by geedsen** [comment]
Tried this: dotnet tool install --global dotnet-ef
But no difference

**Comment by roji** [comment]
Can you please run `dotnet tool list --global` and post the results?

**Comment by geedsen** [comment]
Package Id      Version      Commands
--------------------------------------
dotnet-ef       2.1.4        dotnet-ef

**Comment by geedsen** [comment]
Not sure if this helps (it did not for me :)
![image](https://user-images.githubusercontent.com/1316595/68430673-c50c2200-01b0-11ea-8ac6-44876e8dbcdb.png)

**Comment by geedsen** [comment]
but this did work:
dotnet tool uninstall --global dotnet-ef
dotnet tool install --global dotnet-ef --version 3.0.0 --interactive

Had to do the uninstall first else it would tell me it was already installed.
