### ISSUE TITLE
NuGet package problem wrt dependency already defined

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/efcore#1882]
Hello, I'm trying to install EF 7 on a clean project and I get this type of error for every EF package:

install-package : 'EntityFramework.Commands' already has a dependency defined for 'EntityFramework.Relational'.
...
or
Install-Package : 'EntityFramework.Relational' already has a dependency defined for 'EntityFramework.Core'.
...
Any helps

**Comment by bricelam** [comment]
This is due to the renaming of aspnet50/aspnetcore50 to dnx451/dxcore50. It looks like [the change](https://nuget.codeplex.com/SourceControl/changeset/e84c2d1b1b7f5fa65201dda49ab7b3ac8d4588af) has gone into the 2.8.5 branch of NuGet. Now you just have to wait for them to actually release it. :wink:

**Comment by bricelam** [comment]
If you're using VS 2010, 2012, or 2013 then NuGet 2.8.5 is available [here](https://nuget.codeplex.com/releases/view/612846).
