### ISSUE TITLE
Capability to make scaffold without schema name [useful in MySQL] 

### ISSUE THREAD

**Issue by buster95** [dotnet/efcore#18828]
I have a localhost mysql using mysql.data.entityframeworkcore the database is named kongo when I do db scaffold in the dbcontext tables are maped as this:
`kongo`.`table1`
`kongo`.`table2`
`kongo`.`table3`
etc.
connection is good but when I'm trying connect to a online server some hosting not allow change the database name and by default they put a prefix example `u12312_kongo` in the database name,
when efcore make a query as like
SELECT * FROM `kongo`.`table1` but in the hosting 

`kongo` database not exists just `u12312_kongo` is available
hosting show the database not exists

capability to scaffold without schema name
![image](https://user-images.githubusercontent.com/15637669/68535623-bcc7fa00-030a-11ea-8a7f-fea52dc22666.png)

**Comment by buster95** [comment]
I'm doing scaffold with the next command
dotnet ef dbcontext scaffold "Name=kongo" MySql.Data.EntityFrameworkCore -o Models -f

**Comment by ErikEJ** [comment]
Seems there is a confusion between schema name and database name? @jespersh ?

**Comment by buster95** [comment]
> Seems there is a confusion between schema name and database name? @jespersh ?

In MySQL schema and database are the same concept

**Comment by jespersh** [comment]
You need to define the database in the connection string. I'm trying in development so I use the same database for both debug and release, but I modified it for you:

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
#if DEBUG
        optionsBuilder
            .UseMySql(@"server=localhost;port=3306;user id=root;Pwd=supersecretpassword;persistsecurityinfo=True;database=kongo;AllowZeroDateTime=True;Convert Zero Datetime=true");
#else
        optionsBuilder
            .UseMySql(@"server=mysql.hosting.com;port=3306;user id=u12312;Pwd=supersecretpassword;persistsecurityinfo=True;database=u12312_kongo;AllowZeroDateTime=True;Convert Zero Datetime=true");
#endif
    }
}
```

There are various ways to define these, be it hardcoded or appsettings or a key vault: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0

**Comment by buster95** [comment]
You don't understand me, my connections string are good for every server, but for the app was working I modified all the file kongoContext removing the "schema" mapping in the method ToTable(), in my opinion entity framework core is only optimized for sqlserver, in MySQL, schemas are not exists

**Comment by buster95** [comment]
The problem is that efcore when making queries put the schema name in the query and that schema name that was mapped in the dbcontext not exists remotely just locally
For example:
That query is wrong and was maked by efcore
Select * From kongo.employee
For MySQL the correct query is
Select * From employee
Because kongo justo exists

**Comment by jespersh** [comment]
MySQL treats schema == database. The same holds true in various mysqlconnectors. I'm using https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/ which underneath uses https://github.com/mysql-net/MySqlConnector/ and they also treat schemas as databases.

It isn't strictly wrong, it is just something to be aware of since it the definition comes directly from the MySQL glossary.

Anyway! Is the problem that the scaffolding code generated with 3.0 is including the database name in ToTable? I'm not seeing it when using Pomelo.EntityFrameworkCore.MySql that I normally use.
```
dotnet ef dbcontext scaffold "server=xxxxxx;user id=xxxxxx;password=xxxxxx;persistsecurityinfo=True;database=ourproduct" "Pomelo.EntityFrameworkCore.MySql" -o Models -f
```

I couldn't get the official mysql connector to scaffold. It fails with
```
Method 'Create' in type 'MySql.Data.EntityFrameworkCore.Scaffolding.Internal.MySQLDatabaseModelFactory' from assembly 'MySql.Data.EntityFrameworkCore, Version=8.0.18.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' does not have an implementation.
```

I'd recommend using Pomelo.EntityFrameworkCore.MySql tbh.

https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_schema

**Comment by smitpatel** [comment]
If MySql treats schema == database then it the scaffolding code for MySql (implementation of `IDatabaseModelFactory` should strip out all schema information. For EF Core schema is different concept and it will be used in query hence it is required in MySql provider to not put database name as schema info.

**Comment by ajcvickers** [comment]
@buster95 Many people seem to struggle with the MySQL provider from Oracle. Moving to the Pomelo open-source provider, as suggested by @jespersh, might result in more luck. Beyond that, as @smitpatel says, this is an issue with the way the MySQL provider is reverse engineering--please file an issue with them.

**Comment by jespersh** [comment]
@smitpatel you're dead on the money there and I was staring at MySQL's `IDatabaseModelFactory` official provider wondering if it was the right piece of code I was looking at:
```C#
DatabaseTable table = new DatabaseTable()
{
	Schema = reader.GetValueOrDefault<string>("table_schema"),
	Name = reader.GetValueOrDefault<string>("table_name")
};
```

Where as Pomelo has this set to null:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e00e12e97d1482f27ab25ae024223f8e7eb2e5b6/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L155-L156

@ajcvickers I had written this before you posted and wanted to provide a bit of insights I discovered.

**Comment by buster95** [comment]
> @smitpatel you're dead on the money there and I was staring at MySQL's `IDatabaseModelFactory` official provider wondering if it was the right piece of code I was looking at:
> 
> ```cs
> DatabaseTable table = new DatabaseTable()
> {
> 	Schema = reader.GetValueOrDefault<string>("table_schema"),
> 	Name = reader.GetValueOrDefault<string>("table_name")
> };
> ```
> 
> Where as Pomelo has this set to null:
> https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e00e12e97d1482f27ab25ae024223f8e7eb2e5b6/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L155-L156
> 
> @ajcvickers I had written this before you posted and wanted to provide a bit of insights I discovered.

I was using mysql.data.entityframeworkcore because is the official connector from mysql, but I saw that not work properly still
