### ISSUE TITLE
Move issues from preview milestones after GA

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#18820]
So all issues in `3.0-previewX` would move into `3.0.0`.

The previews become largely irrelevant after release and we (and customers) can then easily see in one place everything included in a given release.

If we don't delete the preview milestones, then the history will still indicate which milestone it was fixed, so we're not losing information here.

**Comment by ajcvickers** [comment]
Done for 5.0.

**Comment by roji** [comment]
So nice to finally see the 6.0.0 milestone populated with all those issues :)
