### ISSUE TITLE
when will support MongoDB Provider

### ISSUE THREAD

**Issue by czs1993** [dotnet/efcore#18835]
MongoDb is a highly popular No-SQL database solution for storing structured, non-relational document data. If EFCore supports MongoDB, it will be of great help to monitoring and application development.

**Comment by ajcvickers** [comment]
@czs1993 This is not something that the EF team is planning to implement. A google search indicates that there is at least one community effort to implement a provider, so you might try following up there.

**Comment by vslee** [comment]
You can vote for the issue here https://jira.mongodb.org/browse/CSHARP-3837
