### ISSUE TITLE
Database Migrate fails to execute for manually created database

### ISSUE THREAD

**Issue by lovelessX** [dotnet/efcore#18839]
When I first run a migrator app against a local SQL Server instance which has a manual database created already and have EF Core execute my InitialCreate migration, it throws a Microsoft.Data.SqlClient.SqlException due to the DB already existing.

It appears the database Migrate() call expects to be able to create the databases on first call. This is not possible in all circumstances because we don't want our migrator app to have DB create permissions (intended to be used in Azure SQL ultimately).

**Microsoft.Data.SqlClient.SqlException**: 'Database 'mydatabasename' already exists. Choose a different database name.'

### Steps to reproduce

Steps:

1. Manually create an empty database in your environment
2. Create a migration project and add an initial migration with the Add-Migration command.
3. Attempt to execute the migration by calling Microsoft.EntityFrameworkCore.DbContext.Database.Migrate().

Note that if I don't create it manually everything works fine. This also worked on EF Core 2.2.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 64-bit
IDE: Visual Studio 2019 16.3.5

**Comment by ajcvickers** [comment]
@lovelessX Can you be more specific about how you are creating the database in step 1?

**Comment by lovelessX** [comment]
To clarify, I am manually creating it in Microsoft SQL Server Management Studio. Literally just right-clicking on the Databases folder under my SQL Server instances and saying "New Database..." and then using all defaults. Nothing else.

I have also tried manually making the __EFMigrationsHistory table by hand, but same problem.

This seems like a common use case so I'm very confused as to why this would happen. It would be the same for developers coming from an existing DB with data in it.

**Comment by ajcvickers** [comment]
@lovelessX I have not been able to reproduce this. I created an empty database in SQL Management Studio, then created a migration and ran the code below. EF correctly created the schema in the empty database, as can be seen in the logs. 

Could you please capture logs from your code so we can try to figure out what is different.

```C#
public class Blog
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly ILoggerFactory Logger = LoggerFactory.Create(x => x.AddConsole().SetMinimumLevel(LogLevel.Debug));
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Property(e => e.Id).UseIdentityColumn(1001, 1);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=FromManagementStudio;ConnectRetryCount=0");
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.Migrate();

            context.Add(new Blog());
            
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            Console.WriteLine(context.Set<Blog>().First().Id);
        }
    }
}
```

```
dbug: Microsoft.EntityFrameworkCore.Infrastructure[10409]
      An additional 'IServiceProvider' was created for internal use by Entity Framework. An existing service provider was not used due to the following configuration changes: configuration added for 'Core:UseMemoryCache', configuration added for 'Core:EnableSensitiveDataLogging', configuration added for 'Core:EnableDetailedErrors', configuration added for 'Core:ConfigureWarnings', configuration added for 'SqlServer:UseRowNumberForPaging'.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'BloggingContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
dbug: Microsoft.EntityFrameworkCore.Migrations[20400]
      Migrating using database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteScalar'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteScalar' (1ms).
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10800]
      DetectChanges starting for 'BloggingContext'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10801]
      DetectChanges completed for 'BloggingContext'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [__EFMigrationsHistory] (
          [MigrationId] nvarchar(150) NOT NULL,
          [ProductVersion] nvarchar(32) NOT NULL,
          CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
      );
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [__EFMigrationsHistory] (
          [MigrationId] nvarchar(150) NOT NULL,
          [ProductVersion] nvarchar(32) NOT NULL,
          CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
      );
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteScalar'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteScalar' (0ms).
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteReader'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
dbug: Microsoft.EntityFrameworkCore.Database.Command[20300]
      A data reader was disposed.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20191114202614_One'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20209]
      Beginning transaction with isolation level 'Unspecified'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20200]
      Began transaction with isolation level 'ReadCommitted'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteNonQuery' (0ms).
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Blog] (
          [Id] int NOT NULL IDENTITY(1001, 1),
          CONSTRAINT [PK_Blog] PRIMARY KEY ([Id])
      );
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Blog] (
          [Id] int NOT NULL IDENTITY(1001, 1),
          CONSTRAINT [PK_Blog] PRIMARY KEY ([Id])
      );
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteNonQuery' (0ms).
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
      VALUES (N'20191114202614_One', N'3.0.0');
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
      VALUES (N'20191114202614_One', N'3.0.0');
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20210]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20202]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20204]
      Disposing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10808]
      'BloggingContext' generated a temporary value for the 'Id' property of new 'Blog' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10806]
      Context 'BloggingContext' started tracking 'Blog' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
dbug: Microsoft.EntityFrameworkCore.Update[10004]
      SaveChanges starting for 'BloggingContext'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10800]
      DetectChanges starting for 'BloggingContext'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10801]
      DetectChanges completed for 'BloggingContext'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20209]
      Beginning transaction with isolation level 'Unspecified'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20200]
      Began transaction with isolation level 'ReadCommitted'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteReader'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteReader' (0ms).
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Blog]
      DEFAULT VALUES;
      SELECT [Id]
      FROM [Blog]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Blog]
      DEFAULT VALUES;
      SELECT [Id]
      FROM [Blog]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10803]
      Foreign key property 'Blog.Id' detected as changed. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see property values.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20300]
      A data reader was disposed.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20210]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20202]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20204]
      Disposing transaction.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      An 'Blog' entity tracked by 'BloggingContext' changed from 'Added' to 'Unchanged'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
dbug: Microsoft.EntityFrameworkCore.Update[10005]
      SaveChanges completed for 'BloggingContext' with 1 entities written to the database.
dbug: Microsoft.EntityFrameworkCore.Infrastructure[10407]
      'BloggingContext' disposed.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'BloggingContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      (queryContext) => Single<Blog>(new QueryingEnumerable<Blog>(
          (RelationalQueryContext)queryContext,
          SqlServerQuerySqlGeneratorFactory,
          SqlExpressionFactory,
          ParameterNameGeneratorFactory,
          Projection Mapping:
              EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: Blog.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], }
          SELECT TOP(1) b.Id
          FROM Blog AS b,
          Func<QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator, Blog>,
          BloggingContext,
          DiagnosticsLogger<Query>
      ))
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteReader'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'FromManagementStudio' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [b].[Id]
      FROM [Blog] AS [b]
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [b].[Id]
      FROM [Blog] AS [b]
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10806]
      Context 'BloggingContext' started tracking 'Blog' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
1001
dbug
```

**Comment by lovelessX** [comment]
Here is my output:

`dbug: Microsoft.EntityFrameworkCore.Migrations[20400]
      Migrating using database 'TestDatabase' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'TestDatabase' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'TestDatabase' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'TestDatabase' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'TestDatabase' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'master' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'master' on server '(local)'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteNonQuery' (5ms).
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [TestDatabase];
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (19ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [TestDatabase];
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Database 'TestDatabase' already exists. Choose a different database name.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at <solutionname>.Program.Main(String[] args) in C:\Development\<solutionpath>\Program.cs:line 24
ClientConnectionId:7c028d45-facb-4872-a71f-6c4337e6034e
Error Number:1801,State:3,Class:16`

**Comment by lovelessX** [comment]
I have run your own code with my instance with a similar result. The same exception is thrown. I'm attaching my project.

[TestDBStuff.zip](https://github.com/aspnet/EntityFrameworkCore/files/3871274/TestDBStuff.zip)

Using:
SQL Server 12.0.5223.6.

Frameworks:
Microsoft.NETCore.App 3.0.0

Packages:
Microsoft.EntityFrameworkCore 3.0.1
Microsoft.EntityFrameworkCore.SqlServer 3.0.1


    dbug: Microsoft.EntityFrameworkCore.Infrastructure[10409]
          An additional 'IServiceProvider' was created for internal use by Entity Framework. An existing service provider was not used due to the following configuration changes: configuration added for 'Core:UseMemoryCache', configuration added for 'Core:EnableSensitiveDataLogging', configuration added for 'Core:EnableDetailedErrors', configuration added for 'Core:ConfigureWarnings', configuration added for 'SqlServer:UseRowNumberForPaging'.
    info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
          Entity Framework Core 3.0.1 initialized 'BloggingContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
    dbug: Microsoft.EntityFrameworkCore.Migrations[20400]
          Migrating using database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
          Opening connection to database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20004]
          An error occurred using the connection to database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
          Opening connection to database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20004]
          An error occurred using the connection to database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
          Opening connection to database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20004]
          An error occurred using the connection to database 'FromSqlManagementStudio' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
          Opening connection to database 'master' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
          Opened connection to database 'master' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
          Creating DbCommand for 'ExecuteNonQuery'.
    dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
          Created DbCommand for 'ExecuteNonQuery' (3ms).
    info: Microsoft.EntityFrameworkCore.Database.Command[20100]
          Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
          CREATE DATABASE [FromSqlManagementStudio];
    fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
          Failed executing DbCommand (16ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
          CREATE DATABASE [FromSqlManagementStudio];
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
          Closing connection to database 'master' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
          Closed connection to database 'master' on server '(local)'.
    dbug: Microsoft.EntityFrameworkCore.Infrastructure[10407]
          'BloggingContext' disposed.
    Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Database 'FromSqlManagementStudio' already exists. Choose a different database name.
       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
       at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
       at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
       at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
       at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
       at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
       at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
       at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
       at TestDBStuff.Program.Main() in C:\Users\<repofolder>\source\repos\TestDBStuff\TestDBStuff\Program.cs:line 15
       at TestDBStuff.Program.<Main>()
    ClientConnectionId:9f535712-99ba-4246-ba94-899a6cb71896
    Error Number:1801,State:3,Class:16

**Comment by ajcvickers** [comment]
@lovelessX It looks very much like the connection string to the database is not correct. What the log above shows is:
* Failure to open a connection to the given database. This is interpreted to mean that the database does not exist.
* Successfully opening of a connection to `master` on the same server
* Attempt to create the database using the connection to master

What happens if you attempt to open a connection to the database manually, before doing anything else? For example:

```C#
public class Program
{
    public static void Main()
    {
        var connection = new SqlConnection("<your connection string>");
        connection.Open();
    }
}
```

**Comment by lovelessX** [comment]
You're right - it was an obfuscated account issue with the DB. Once I cleaned that up it worked. Thanks for the help!
