### ISSUE TITLE
Improve exception messages for client evaluation of ToShortDateString, etc.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#18848]
See https://github.com/aspnet/EntityFrameworkCore/issues/18826

**Comment by smitpatel** [comment]
I ran the scenario against 3.1 release on SqlServer. We actually translate the query. `ToSthortDateString` is not server evaluated but it is in projection (for outer level and inner level both) hence we evaluate on client and generate results.

No exception message to improve.
