### ISSUE TITLE
Don't set GUID PK to be store generated by convention

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#18863]
The common scenario seems to be using explicit values which causes confusion after 3.0 changes. E.g. https://github.com/aspnet/EntityFrameworkCore/issues/18830

**Comment by ajcvickers** [comment]
@AndriySvyryd Do we really know that's the common scenario? Or are we just hearing about that one because it's the one we broke?

**Comment by AndriySvyryd** [comment]
@ajcvickers Based on the filed issues I think it's safe to say that it is more expected that an integer property would be value generated than a GUID one. We can make this change early and gather feedback.

**Comment by bobbydowling** [comment]
Only time I have ever cared to have my GUID's auto-set for me is when someone has decided against my will to make their PKs a GUID, which has only happened a few times in my 20 years doing this.

**Comment by ajcvickers** [comment]
Discussed in triage and decided that while this might be a better default there isn't enough evidence that this will be a significant enough improvement to make a breaking change now.
