### ISSUE TITLE
Inserting a related entity of a related entity not able to populate Foreign Key of Main Parent Entity

### ISSUE THREAD

**Issue by bsheriff** [dotnet/efcore#18878]
I am working with Entity Framework Core 3.0 and am having issues with inserting objects into navigation properties and properly maintaining the Parent Foreign Key.

I have 2 Model Classes

**EntityType.cs**
```C#
public class EntityType
{
   public int TypeId { get; set; }
   public string Name { get; set; }

   public virtual ICollection<Criteria> Criterias { get; set; }
}
```

**Criteria.cs**
```C#
public class Criteria
{
   public int CriteriaId { get; set; }
   public int TypeId { get; set; }
   public int? ParentCriteriaId { get; set; }
   public string Name { get; set; }

   public virtual EntityType Type { get; set; }
   public virtual Criteria ParentCriteria { get; set; }

   public virtual ICollection<Criteria> Criterias { get; set; }
}
```

So as you can see a "Type" can have one or many "Criterias" and each "Criteria" can have one or many child "Criterias".  So "Criteria" has a self-referencing FK.

Here is the FluentApi Configuration Relationship I have for "Criteria"
```C#
builder.HasOne(x => x.Type).WithMany(x => x.Criterias).HasForeignKey(x => x.TypeId).OnDelete(DeleteBehavior.Restrict);
builder.HasOne(x => x.ParentCriteria).WithMany(x => x.Criterias).HasForeignKey(x => x.ParentCriteriaId).OnDelete(DeleteBehavior.Restrict);
```

So I implemented a UnitOfWork/Repository pattern and have a service layer which uses that.
My Service layer for inserting an "EntityType" along with one to many "Criterias" is as follows - 
* Note this is a service layer and the caller is passing in an "EntityTypeDTO" object which contains a  
   List of "Criteria" objects and I also have logic to create a List of "children" which is not shown 
   here.
```C#

// The main parent object to be created
EntityType type = new EntityType
{
    Name = entityTypeDTO.Name
};

foreach (CriteriaDTO criteriaDTO in entityTypeDTO.Criterias)
{
     // Create the top level Criteria object which will be the "Parent"
     // No problem here, EF is able to populate the TypeId FK for the Parent
     Criteria criteria= new Criteria
     {
         Name = criteriaDTO.Name     
     };

     foreach (CriteriaDTO childDTO in children)
     {
        // Loop through the children of the parent and add to the navigation property
        // Here is where the problem is, EF is able to populate the ParentCriteriaId FK but
        // for some reason cannot resolve the TypeId FK
         criteria.Criterias.Add(new ModelCriteria
         {
             Name = childDTO.Name
         });
     }

     type.Criterias.Add(criteria);
}

UnitOfWork.ModelTypeRepository.Add(type);

await UnitOfWork.SaveAsync();
```

So after it tried to Save I get the following exception:
`Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Criteria_EntityTypes_TypeId". The conflict occurred in database`

So I know where the issue is occuring, but do not know why.  EF cannot seem to resolve the TypeId when looping through the children of the Criteria and adding to the criteria.Criterias collection.  For the time being I have been using the following workaround - 

Instead of adding the child criteria object to the list of "Criterias" like so
```C#
foreach (CriteriaDTO childDTO in children)
{
         criteria.Criterias.Add(new ModelCriteria
         {
             Name = childDTO.Name
         });
}
```

I have to manually set the EntityType object like this (but I shouldn't have to do it this way):
```C#
foreach (CriteriaDTO childDTO in children)
{
         criteria.Criterias.Add(new ModelCriteria
         {
             Name = childDTO.Name,
             EntityType = type
         });
}
```

EF Core version: 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@bsheriff In this code:
```C#
criteria.Criterias.Add(new ModelCriteria
         {
             Name = childDTO.Name
         });
```
a new instance of `ModelCriteria` is created. (I'm assuming this is supposed to be the same as (or derived from) the `Model` class shown above.) However, there is no `Type` set on this entity instance. From  what you have written it seems like you're saying that EF should know the relationship here and set a `Type` automatically. Can you explain in a bit more detail how EF would know this is the correct thing to do?

**Comment by bsheriff** [comment]
So when I do this `type.Criterias.Add(criteria);` EF knows how to populate the `TypeId` property for the `criteria` object.  Now when I do this - 
```
criteria.Criterias.Add(new Criteria
{
     Name = childDTO.Name
});
```
My assumption was, based on the configuration that I had created, when I do this `type.Criterias.Add(criteria);` that all the `criteria.Criterias` would get the `TypeId` from its ancestor `type`.  I could be incorrect of course and maybe I am missing something and this is the intended behavior and my "workaround" is the only thing I can do in my scenario.

Thanks

**Comment by ajcvickers** [comment]
@bsheriff In the first case EF is just fixing up the inverse navigation property for _the same relationship_. So adding an entity to `EntityType.Criterias` is equivalent to setting the FK `Criteria.TypeId` is equivalent to setting `Criteria.Type`. They all mean the same thing.

In the second case, adding to `Criteria.Criterias` is equivalent to setting `Criteria.ParentCriteria` is equivalent to setting the FK `Criteria.ParentCriteriaId`. It has no effect on the other relationship.

**Comment by bsheriff** [comment]
Ok so there is no way to set both related entities (EntityType and ParentCriteria) in the same "add" statement.  I would have to manually set the Ancestor Type = type when adding to the `criteria.Criterias` collection?

**Comment by ajcvickers** [comment]
Correct. The relationships are independent.

**Comment by bsheriff** [comment]
Ok,

Thank you for the clarification
