### ISSUE TITLE
EF 3 + Sqlite how to set up a resilient connection

### ISSUE THREAD

**Issue by kofifus** [dotnet/efcore#18875]
I have .NET Core window service desktop app + EF 3.1 connecting to Sqlite like this:
```
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
      string connectionString = $"Data Source=mydb.db;";
      optionsBuilder
        .UseSqlite(connectionString);
    }
```
I need to set up some resilient mechanisms (basically a retry on failures), looking here is seems that for SqlServer there is `sqlServerOptions.sqlOptions.EnableRetryOnFailure` but what are my options for sqlite ?

I can see that `UseSqlite` has `SqliteDbContextOptionsBuilder` which has an `ExecutionStrategy` but I'm not if/how to use it for a resilient connection.

Any help ?

**Comment by ajcvickers** [comment]
@kofifus We haven't put any work into resiliency for SQLite because database access is just in-proc file access. Can you provider some more information on the kinds of failures that need retrying?

**Comment by kofifus** [comment]
I have seen cases of SQLITE_LOCKED and SQLITE_BUSY which as far as understand should be low level implemented by EF

But besides that, I think it should be possible to define a resiliency policy for SQLite, in my case since my code is critical, I simply don't want to care, if any error happen I want to have retry policy etc ...

**Comment by ErikEJ** [comment]
Why not simply use Polly then?

**Comment by kofifus** [comment]
I'm not familiar with Polly, does it work well with EF DB context and Linq ? I want the retry around the server side query before it is materialized, so I can do further inmem client side linq ..

**Comment by ajcvickers** [comment]
@kofifus These events are already re-tried at the ADO.NET layer. You can increase the command timeout to re-try for longer. However, it's not too difficult to get into a deadlock with SQLite, so longer timeouts may not help you.

If you wanted you could implement an `IExecutionStrategy` for SQLite to make EF retry on certain errors, but I don't expect this to be very useful given the nature of the SQLite interaction.
