### ISSUE TITLE
Visual Studio 19 - In Package manager console command "add-migration" is missing

### ISSUE THREAD

**Issue by inabeel** [dotnet/efcore#18906]

**Comment by ajcvickers** [comment]
@inabeel Did you install the Microsoft.EntityFrameworkCore.Tools NuGet package into your project??

**Comment by inabeel** [comment]
No.. I didn't install this one!. 
Do we need to install packages separately?

**Comment by ajcvickers** [comment]
Yes. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#no-longer
