### ISSUE TITLE
Sequence of data displaying- contentious looping no end  

### ISSUE THREAD

**Issue by ChristalVins** [dotnet/efcore#18902]
```C#
 public class NewsPost
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PostId { get; set; }
        [Required]
        [MaxLength(30)]
        public string PostName { get; set; }
        [Required]
        public string PostContent { get; set; }
        public string PostImageUrl { get; set; }
        [MaxLength(150)]
        public string PostDate { get; set; }

        public virtual ICollection<Like> Likes { get; } = new List<Like>();
        public virtual ICollection<Comment> Comment { get; set; }
    }

public class Like
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LikeId { get; set; }
        [Required]
        [MaxLength(30)]
        public string LikeName { get; set; }
        public string LikeDate { get; set; }

        // Foreign key
        [Display(Name = "NewsPost")]
        public int PostId { get; set; }
        [ForeignKey("PostId")]
        public virtual NewsPost NewsPost { get; set; }
    }
```

```C#
var query = _context.NewsPosts.Include(l => l.Likes)
````

### Steps to reproduce

![image](https://user-images.githubusercontent.com/14306827/68870765-69e2ae00-0721-11ea-804f-4a43b10ca609.png)

![image](https://user-images.githubusercontent.com/14306827/68870885-a1515a80-0721-11ea-98db-6db94c02a7c2.png)

![image](https://user-images.githubusercontent.com/14306827/68871028-d067cc00-0721-11ea-9b30-91da05e1aeb8.png)

Please provide the solution...

### Further technical details
Code first approach,
EF Core version: 
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@ChristalVins All you are seeing here are back references from the `Like` to the `NewsPost` with which it is related. In other words, the `Likes` collection on an instance of `NewsPost` contains a `Like` instance, and this instance refers back to the same `NewsPost` instance. This is by-design--it reflects how the objects in the graph are related to each other.
