### ISSUE TITLE
UseMemoryCache API

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#18938]
From @1009058470
some of .net core api's description is not clear. for example ,DbContextOptionsBuilder.UseMemoryCache(IMemoryCache) Method just show it parameters ,but i don not know how to make it parameters.
the url is https://docs.microsoft.com/zh-cn/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder-1.usememorycache?view=efcore-3.0#Microsoft_EntityFrameworkCore_DbContextOptionsBuilder_1_UseMemoryCache_Microsoft_Extensions_Caching_Memory_IMemoryCache_

Filed originally at https://github.com/MicrosoftDocs/feedback/issues/2156

**Comment by AndriySvyryd** [comment]
Also add a link to docs
