### ISSUE TITLE
Cosmos: How to configure DbContext for an infinite/recursive owned entity 

### ISSUE THREAD

**Issue by gdahlin** [dotnet/efcore#18930]
Hi!

Out of the documentation for Owned entities and cosmos, I cannot see if there is, or should be, a way to configure a DbContext so that an owned entity, that is recursive, will serialise the complete structure of the entity to Cosmos.

### Steps to reproduce
1. Create a containing Entity that ownes the recursive entity.
2. Configure the DbContext with Owned for the recursive entity.

Since the recursive entity owns entities of itself, there should be a way to configure the context to just follow the navigation properties as long as there is relevant children populated in the entity graph.

This is what we would have:
``` C# 
//Entities
 public class RootEntity
 {
        public string Id { get; set; }
        public string PartitionKey { get; set; }
        public string Name { get; set; }
        
        public IEnumerable<RecursiveEntity> Children { get; set; }
}

public class RecursiveEntity
{
        public string Name { get; set; }
        public IEnumerable<RecursiveEntity> Children { get; set; }
}
```

``` C# 
//Context
modelBuilder.Owned<RecursiveEntity>();

modelBuilder.Entity<RootEntity>().HasPartitionKey(o => o.PartitionKey);
modelBuilder.Entity<RootEntity>().OwnsMany(p => p.Children);
```

Ideally in a pure Cosmos scenario this could be enough just to serialise the recursive structure(s) indefinitely since all entities in the RecursiveEntity are owned, but as of now we cannot find a way forward. 
We need a way to configure the DbContext to understand to navigate the recursive entity graph.

To set at fixed depth by nesting `.OwnsMany()` in the context is unfortunately not an option in this case for the entities.

### Further technical details

EF Core version: 3.1.0-preview3.19554.8
Database provider: Cosmos DB
Target framework: .NET Core 3.1 Preview 3
Operating system: Mac OS X, Windows 10
IDE: Visual Studio Code

**Comment by AndriySvyryd** [comment]
@gdahlin This is not supported by EF Core, each nested OwnsMany call defines a new entity type

**Comment by gdahlin** [comment]
Would there be any possibility to eventually make it supported, at least for the Cosmos provider (Since Cosmos handles these type of entities in a very good manner with alternative Clients/SDKs)?

Without the possibility to manage recursive hierarchies in EF Cosmos, we would need to rely on either the Cosmos SDK directly or other third party frameworks for these entities at least.

Would be a really good thing to be able to use EF all the way I believe.

**Comment by AndriySvyryd** [comment]
@gdahlin It's possible, but would require changes in Core even if only the Cosmos provider supports it. And it would be fairly expensive to implement, so we would only do it if this is a very popular pattern.

**Comment by gdahlin** [comment]
Thank you for the clarification. Let's see if this would be a popular pattern for implementing all the way.

I was unaware of above documentation for unstructured data. That will probably help us a lot in our use-case. Would there be a way to know in advance if/when there will be changes to the `__jObject` behaviour?

**Comment by AndriySvyryd** [comment]
> Would there be a way to know in advance if/when there will be changes to the __jObject behaviour?

@gdahlin We'll mention it in the [breaking changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes) for the version in which it will change. There are currently no plans to change it.

**Comment by aladd04** [comment]
Little bit of an old open issue, but any chance this will be supported in any upcoming releases?

**Comment by ajcvickers** [comment]
@aladd04 We just discussed this as a team and it is not something we plan to implement.
