### ISSUE TITLE
Query: optimize CASE statement - remove conditions that are never hit

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#18935]
```sql
CASE
        WHEN CAST(0 AS bit) THEN x
        ELSE y
    END
```

we can simply remove the WHEN block since it's condition is never met so the result would be just `y`

If all the WHEN blocks have been removed and there is no ELSE condition we can return NULL

**Comment by smitpatel** [comment]
@maumar - Is this already done?

**Comment by ranma42** [comment]
Yes, this should already be optimized by
https://github.com/dotnet/efcore/blob/ecd6104d7db803a976116a49d5855bce85634051/src/EFCore.Relational/Query/SqlNullabilityProcessor.cs#L525-L532
