### ISSUE TITLE
DB scaffold CLI Removes DBSET<t> (dbquery<t>)

### ISSUE THREAD

**Issue by loganmarshall1** [dotnet/efcore#18944]
Since the Dbscaffold CLI replaces dbcontext c# file each time.  In order to use ef cores new dbSet<t> (the new dbquery) you have to put into this (auto wiped out by the CLI) dbcontext file as a.HasNoKey() item.

In efc2 the dbquery<t> we kept it in a partial class so it wouldn't get over written by the scaffold.  Since we can't put dbSets<t> in a different c# file because we need to add hasnoKey() in onmodelbuilding event (which gets over written by the scaffold), we have to stay on 2.0

Would really like to upgrade to EF core 3.0 but since they deprecated DBquery<t> into something new that breaks db scaffolding for us we can't.

The only nuGet we haven’t updated in our core3.0 build is this efcore3.0 one. 😅

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: win10 x64
IDE: Visual Studio 2019 16.3.8

**Comment by ErikEJ** [comment]
You are a bit unclear, but with EF Core 3, you can override the OnModelCreatingPartial partial method

**Comment by loganmarshall1** [comment]
How? Because the on model creating auto generated by the db scaffold CLI is already an override?  Can you have 2 overrides?  Will it run both overrides?

Logan

On Nov 16, 2019, at 5:08 PM, Erik Ejlskov Jensen <notifications@github.com> wrote:

﻿

You are a bit unclear, but with EF Core 3, you can override the OnModelCreatingPartial partial method

**Comment by ErikEJ** [comment]
Have a close look at the last lines of the generated DbContext

**Comment by loganmarshall1** [comment]
I did look at it, not sure what your subtly inferring?  Can you be more direct?

Logan

On Nov 16, 2019, at 5:50 PM, Erik Ejlskov Jensen <notifications@github.com> wrote:

﻿

Have a close look at the last lines of the generated DbContext

**Comment by ErikEJ** [comment]
Something like this: https://github.com/ErikEJ/EFCorePowerTools/issues/300#issuecomment-551172148
