### ISSUE TITLE
Migrations (Design-time): The Namespace of the model snapshot is incorrect.

### ISSUE THREAD

**Issue by whizkidwwe1217** [dotnet/efcore#18956]
The **namespace** of the generated model snapshot is not updated on the succeeding migrations.
In the screenshot below, I have a single DbContext but the `OnConfiguring` method has been overriden to support different database providers. For example, in SqlServer, it should use the `optionsBuilder.UseSqlServer`, in MySql, it should use the `optionsBuilder.UseMySql`, and soon.

![image](https://user-images.githubusercontent.com/1977391/69008657-04dcc180-0988-11ea-912e-0c48f91118c6.png)

As you can see, the namespaces of both model snapshots are the same. The first one should be `i21Apis.Migrations.MySql`
![image](https://user-images.githubusercontent.com/1977391/69008690-5a18d300-0988-11ea-9425-63e69ffd194f.png)

### Steps to reproduce
I have an override on the `OnConfiguring` method of the DBContext that switches to a different database provider depending on some conditions:

```
public interface IDbContextConfigurationBuilder
{
    void OnConfiguring(DbContextOptionsBuilder optionsBuilder);
}
```

```
public class TenantDbContext : DbContext
{
        private readonly IConfiguration configuration;
        private readonly Tenant tenant;
        private readonly IDbContextConfigurationBuilder builder;

        public TenantDbContext(DbContextOptions<TenantDbContext> options)
            : base(options)
        {

        }

        public TenantDbContext(IConfiguration configuration, Tenant tenant,
            IDbContextConfigurationBuilder builder, DbContextOptions<TenantDbContext> options)
            : this(options)
        {
            this.configuration = configuration;
            this.tenant = tenant;
            this.builder = builder;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            if (builder != null) builder.OnConfiguring(optionsBuilder);
        }

        public DbSet<Customer> Customers { get; set; }
        public DbSet<CompanyLocation> CompanyLocations { get; set; }
    }
}
```
I don't know if DI works on the DesignTimeFactory so I've manually instantiated the interface that returns an appropriate database provider OnConfiguring implementation. The provider switch is set via environment variable:
```
public class TenantDesignTimeDbContextFactory : IDesignTimeDbContextFactory<TenantDbContext>
 {
        public TenantDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<TenantDbContext>();
            var config = GetConfiguration(args);
            var provider = GetEnvironmentVariable("DatabaseProvider");

            Tenant tenant = null;
            IDbContextConfigurationBuilder contextConfigBuilder = null;

            if (provider.Equals("Sqlite"))
            {
                tenant = new Tenant { DatabaseProvider = "Sqlite", ConnectionString = ConnectionStringTemplates.SQLITE };
                contextConfigBuilder = new SqliteDbContextConfigurationBuilder(config, tenant);
            }
            else if (provider.Equals("MySql"))
            {
                tenant = new Tenant { DatabaseProvider = "MySql", ConnectionString = ConnectionStringTemplates.MYSQL };
                contextConfigBuilder = new MySqlDbContextConfigurationBuilder(config, tenant);
            }
            else
            {
                tenant = new Tenant { DatabaseProvider = "SqlServer", ConnectionString = ConnectionStringTemplates.SQLSERVER };
                contextConfigBuilder = new SqlServerDbContextConfigurationBuilder(config, tenant);
            }

            return new TenantDbContext(config, tenant, contextConfigBuilder, optionsBuilder.Options);
        }
}
```

Batch command to generate migrations:

```batch
set DatabaseProvider=SqlServer
dotnet ef migrations add SqlServerMigration -o Migrations/SqlServer -c TenantDbContext

set DatabaseProvider=MySql
dotnet ef migrations add MySqlMigration -o Migrations/MySql -c TenantDbContext

set DatabaseProvider=Sqlite
dotnet ef migrations add SqliteMigration -o Migrations/Sqlite -c TenantDbContext

pause
```

### Further technical details
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100     
 Commit:    04339c3a26  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18363
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@whizkidwwe1217 I believe right now the only way to handle this is to have a different DbContext sub-type for each provider. This is because otherwise the same model snapshot is used for any provider. We want to make this a better experience going forward--see https://github.com/aspnet/EntityFrameworkCore/issues/16406
