### ISSUE TITLE
How to use ToQuery outside the DbContext?

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#18957]
In a `DbContext`'s `OnModelCreating` method, I can use `ToQuery` to map an entity type to a LINQ query as opposed to a table:
```c#
public sealed class Record
{
    public int Id { get; set; }
    public string Value { get; set; }
}

public sealed class RecordData
{
    public string Value { get; set; }
}

public sealed class ApplicationDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<RecordData>().HasNoKey().ToQuery(() => Records.Select(r => new RecordData { Value = r.Value }));
    }

    public DbSet<Record> Records { get; set; }
    public DbSet<RecordData> RecordData { get; set; }
}
```

but in our project, we like to use `IEntityTypeConfiguration` classes to configure each entity type and then call `ApplyConfiguration` from inside the `DbContext` as opposed to having any configuration directly there.

My question is, how to define the query passed to `ToQuery` in such a configuration class outside of the `DbContext`?
```c#
public sealed class RecordDataConfiguration : IEntityTypeConfiguration<RecordData>
{
    public void Configure(EntityTypeBuilder<RecordData> builder)
    {
        builder.HasNoKey().ToQuery(/* what goes here? */);
    }
}
```

I would expect the lambda in `ToQuery` to take a `DbContext` as the parameter so that I could do something like this:
```c#
builder.HasNoKey().ToQuery(context => context.Set<Record>().Select(r => new RecordData { Value = r.Value }));
```
but I don't see that being the case and can't think of any way to get the `DbContext` or `DbSet` for a specific entity type here. Am I missing something? What's the correct way to do this?

**Comment by ajcvickers** [comment]
@Neme12 I just tested this and it works for me, although @smitpatel indicated that it might not work for all usages of the context.
```C#
public sealed class RecordDataConfiguration : IEntityTypeConfiguration<RecordData>
{
    private readonly DbContext _context;

    public RecordDataConfiguration(DbContext context)
    {
        _context = context;
    }

    public void Configure(EntityTypeBuilder<RecordData> builder)
    {
        builder.HasNoKey().ToQuery(() => _context.Set<Record>().Select(r => new RecordData { Value = r.Value }));
    }
}
```
```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        new RecordDataConfiguration(this).Configure(modelBuilder.Entity<RecordData>());
    }
```

It's probably also worth noting that `ToQuery` is not an area we are currently happy with and we plan to make changes in 5.0. See #18903 and #17270

**Comment by smitpatel** [comment]
If it works for you then it works for everyone.

**Comment by snappyfoo** [comment]
@ajcvickers due to model caching is there not a chance that will capture the initial context only?

**Comment by ajcvickers** [comment]
@snappyfoo I don't think so, no.
