### ISSUE TITLE
What happened to IPluralizer, ICandidateNamingService and CandidateNamingService in 3.0?

### ISSUE THREAD

**Issue by patricknolan** [dotnet/efcore#18969]
Hi,

I just updated to Entity Framework Core 3.0 and the following code no longer compiles. It looks like 
IPluralizer, ICandidateNamingService and CandidateNamingService no longer exist.

What is the new recommended approach for customising the generation  of entities via Add-Migration InitialCreate?

    public class CustomDesignTimeServices : IDesignTimeServices
    {
        public void ConfigureDesignTimeServices(IServiceCollection services)
        {
            services.AddSingleton<ICandidateNamingService, CustomCandidateNamingService>();
           services.AddSingleton<IPluralizer, CustomPluralizer>();
        }
    }

    public class CustomPluralizer : IPluralizer
    {
        public string Pluralize(string name)
        {
            return Inflector.Inflector.Pluralize(name) ?? name;
        }
        public string Singularize(string name)
        {
            return Inflector.Inflector.Singularize(name) ?? name;
        }
    }

    public class CustomCandidateNamingService : CandidateNamingService
    {
        public override string GetDependentEndCandidateNavigationPropertyName(IForeignKey foreignKey)
        {
            if (foreignKey.PrincipalKey.IsPrimaryKey())
                return foreignKey.PrincipalEntityType.ShortName();

            return base.GetDependentEndCandidateNavigationPropertyName(foreignKey);
        }
    }

**Comment by smitpatel** [comment]
You may be running into this https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dip
