### ISSUE TITLE
Consecutive OrderBy not working

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#18963]
It seems that when using 2 consecutive `OrderBy` clauses, the first one is ignored. This means that the sorting isn't stable.

The documentation for `Enumerable.OrderBy` says that the sort is stable:
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netcore-3.0
but there's no mention of the stability in `Queryable.OrderBy`:
https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.orderby?view=netcore-3.0
so I guess it's up to the implementation. Should EF Core provide stability as well, or is this not supported?

### Steps to reproduce

``` C#
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ConsoleApp3
{
    public sealed class Record
    {
        public int Id { get; set; }
        public int A { get; set; }
        public int B { get; set; }
    }

    public sealed class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=aspnet-WebApplication-6E483A89-BEE6-4A76-96CC-CEB276E5E112;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }

        public DbSet<Record> Records { get; set; }
    }

    public static class Program
    {
        public static void Main()
        {
            using (var context = new ApplicationDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Records.Add(new Record { A = 2, B = 2 });
                context.Records.Add(new Record { A = 2, B = 1 });
                context.Records.Add(new Record { A = 1, B = 2 });
                context.Records.Add(new Record { A = 1, B = 1 });
                context.SaveChanges();
            }

            using (var context = new ApplicationDbContext())
            {
                var records = context.Records.OrderBy(r => r.B).OrderBy(r => r.A).ToList();
            }
        }
    }
}
```

I would expect the order inside `records` to be the same as when calling `OrderBy(r => r.A).ThenBy(r => r.B)`, so:
```
new Record { A = 1, B = 1 }
new Record { A = 1, B = 2 }
new Record { A = 2, B = 1 }
new Record { A = 2, B = 2 }
```
but that's not the case because the generated SQL only has `ORDER BY [r].[A]` as opposed to `ORDER BY [r].[A], [r].[B]`.

#### Why sort things in such a weird way as opposed to using `ThenBy`?

I implemented a method that sorts an `IQueryable` based on a list of properties along with their sorting direction (ascending/descending). First I only used it on the client but at one point I started to use this with EF Core and later noticed that the sorting is wrong. For this method, `OrderBy` in a foreach loop is the simplest implementation. In order to use `OrderBy/ThenBy`, I had to special case the first item and also deal with the fact that in order to use `ThenBy`, I have to cast to `IOrderedQueryable` that is returned from the first `OrderBy`.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 Version 1903
IDE: Visual Studio 16.4.0 Preview 5.0

**Comment by smitpatel** [comment]
> Should EF Core provide stability as well, or is this not supported?

Given EF Core has to translate Queryable.OrderBy to SQL Order By clause, the cost of implementing it is not as cheap as Enumerable.OrderBy where it just happens to be work. Hence we have no plans to support it.

**Comment by Neme12** [comment]
@smitpatel Yes, I know it has to be translated. I was asking for the translation support.
