### ISSUE TITLE
Detaching an entity results in related entities being deleted

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#18982]
EF Core 3.0.1

I insert an object along with related objects. Then I set the state of the object to "Detached". I then perform another call to `.SaveChangesAsync()`.

Observed behavior: the related objects are deleted.
Expected behavior: the related objects should not be deleted; rather their tracking status should simply be set to "Detached".

(This is a breaking change since upgrading from EF Core 2.2.4)

### Steps to reproduce

```
    public class Thing
    {
        [Key]
        public Guid ThingId { get; set; }
        [MaxLength(200)]
        public string Description { get; set; }
        public List<OwnedByThing> OwnedByThings { get; set; } = new List<OwnedByThing>();
    }

    public class OwnedByThing
    {
        [Key]
        public Guid OwnedByThingId { get; set; }
        public Guid ThingId { get; set; }
        public Thing Thing { get; set; }
        public int Value { get; set; }
    }

            await using var db = new MyDbContext();
            var thing = new Thing
            {
                Description = "Hello world thing",
                OwnedByThings = new List<OwnedByThing>
                {
                    new OwnedByThing {Value = 1},
                    new OwnedByThing {Value = 2}
                }
            };

            db.Things.Add(thing);
            await db.SaveChangesAsync();

            var thingCount = await db.Things.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(1, thingCount, "Thing Count A");
            var ownedCount = await db.OwnedByThings.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(2, ownedCount, "Owned count A");

            db.Entry(thing).State = EntityState.Detached;
            await db.SaveChangesAsync();
            
            thingCount = await db.Things.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(1, thingCount, "Thing Count B");
            ownedCount = await db.OwnedByThings.CountAsync(e => e.ThingId == thing.ThingId);
            Assert.AreEqual(2, ownedCount, "Owned count B");
```
Result:
``` 
  Owned count B
  Expected: 2
  But was:  0
```

### Further technical details

EF Core version: 3.0.1
Database provider: Npgsql
Target framework:.NET Core 3.0
Operating system: Windows 10 Pro
IDE: JetBrains Rider

**Comment by shaulbehr** [comment]
Hello, has anyone noticed this? I'd say this is a pretty serious bug, no?

**Comment by ajcvickers** [comment]
Note for triage: this still repros with 3.1. It looks like detaching the principal is causing cascade delete of the dependents rather than cascade detach.

@shaulbehr We will investigate whether this is something we should patch.

**Comment by ajcvickers** [comment]
@shaulbehr It looks like a workaround might be to revert the [change to the cascade timing](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#cascade) using something like this:
```C#
public BloggingContext()
{
    ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges;
    ChangeTracker.DeleteOrphansTiming = CascadeTiming.OnSaveChanges;
}
```
Can you test if this workaround works for you?

**Comment by shaulbehr** [comment]
@ajcvickers Yep, that workaround works. Thanks!

**Comment by silvajpr** [comment]
Please fix this soon as possible!
I was not aware of this problem and I already lost data because of this problem!
This is a way to work!
I shouldn’t have to came here to know that you already found the problem 3 months ago and simply post an workaround instead of fixing it and relesse the fix in 3.1 or 3.1.1 etc.
I thought you were having short release cycles so you can deliver this kind of fixes fast!
I am very frustated with this.
Nothing in the breaking changes tell us about this side effect of the detach!
Thanks

**Comment by ajcvickers** [comment]
@silvajpr This is approved for the 3.1.3 patch, tentatively scheduled for March.

**Comment by YZahringer** [comment]
@ajcvickers do you have an ETA for 3.1.3 patch release?

**Comment by ajcvickers** [comment]
@YZahringer It's still tentatively scheduled for March.

**Comment by freerider7777** [comment]
Is this fixed?
