### ISSUE TITLE
Scaffold-dbcontext not working correctly while using a VPN

### ISSUE THREAD

**Issue by aldrashan** [dotnet/efcore#18985]
Not sure why yet, but am experiencing problems while using the scaffold-dbcontext command.

I'm working via a VPN (WatchGuard Mobile VPN with SSL) and if I try to scaffold the remote database, the scaffolded code is only partially correct. More specifically, the `.HasDefaultValueSql("...")` calls are missing and are being replaced by `.ValueGeneratedNever()` calls. Perhaps other things are missing as well, but those aren't obvious at first glance. Have only received errors because of default values that have gone missing.

If I recreate the tables in a local database and scaffold those, the scaffolding will be correct.
Would currently have to locally restore the database from a backup every day in order to be able to scaffold our company's tables.

I've posted it on [stackoverflow ](https://stackoverflow.com/questions/58919679/scaffold-dbcontext-not-generating-hasdefaultvaluesql-anymore)first, but haven't received much response there.

**Comment by ErikEJ** [comment]
You are referring to different databases in your SO post - are you 101 % sure that their schemas are indetical?

**Comment by aldrashan** [comment]
> You are referring to different databases in your SO post - are you 101 % sure that their schemas are identical?

Let me clarify the SO post.

I'm currently working for 2 companies.
Company 1 still uses SQL Server 2012 Enterprise, company 2 uses SQL Server Express 2017.
I'm working on-site at company 1. For company 2 I'm working from home via a VPN.
On my pc I have a Sql Server Express 2017 running.

On my first SO update, I tested the scaffold-dbcontext on company 1's database, to make sure that I had all the needed nuget packages installed. That worked so I tried scaffolding company 2's database again when I got home, after installing all the same nuget packages I had used for the test at company 1 earlier that day.
That did not scaffold correctly, so I posted the update, thinking it was the Sql Server versions causing it.

I had another database (that had nothing to do with company 1 or 2) in my local Sql Server instance at home, so I tried scaffolding that with the same project that was used for the first test in the previous paragraph (i.e. SO update 1).
That worked so then I copied company 2's daily database backup, from earlier that day, and installed it locally, via the "Restore Database..." wizard in SSMS. To my surprise the scaffolding was correct, after which I posted SO update 2.

Am going to try to scaffold company 2's database again while I'm at their location on saturday without VPN. If that works, then it's definitely the VPN that's the problem.

**Comment by ajcvickers** [comment]
@aldrashan Can you scaffold using the --verbose option in both cases and post the logs?

**Comment by aldrashan** [comment]
Alright, it's working now and I feel stupid.

Was scaffolding using our application's datareader/writer user and apparently its rights got changed a while back. Apparently the user can see the different columns, but not the column's defaults.
Received a new user that's able to read those default values as well and now it's working perfectly.
