### ISSUE TITLE
Store computed property with Entity Framework Core

### ISSUE THREAD

**Issue by McKabue** [dotnet/efcore#18998]
I have a computed property that is not being updated to the database. This computed property is just a getter that uses other model properties if no explicit value was provided.

### Steps to reproduce
```C#
    public class User
    {
        private string _fullName;

        public string Id { get; set; } = Guid.NewGuid().ToString("D");
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName
        {
            get
            {
                if (_fullName == null)
                {
                    _fullName = this.FirstName + " " + this.LastName;
                }
                return _fullName;
            }

            set => _fullName = value;
        }
    }

    User user = new User { FirstName = "James", LastName = "Joe" };
    databaseContext.Users.Add(user);
    await databaseContext.SaveChangesAsync();
```

**The `FullName` property is not persisted in the database**, unless i explicitely  set it, eg: 
```C#
User user = new User { FirstName = "James", LastName = "Joe", FullName =  "James Joe" };
```
The strange thing is that `Id` property is being generated and saved while its also computed.

Here is a related [StackOverflow Question](https://stackoverflow.com/questions/58116856/store-computed-property-with-entity-framework-core)
### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Linux Ubuntu 16.04
IDE: Visual Studio Code

**Comment by ajcvickers** [comment]
@McKabue This is because, starting with EF Core 3.0, EF [reads and writes directly to the backing field](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#backing-fields-are-used-by-default), where possible. EF can be configured to use the property instead, at which point the computed value will be read from the property and hence written to the database:
```C#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
     modelBuilder
         .Entity<User>()
         .Property(e => e.FullName)
         .UsePropertyAccessMode(PropertyAccessMode.Property);
 }
```

**Comment by McKabue** [comment]
@ajcvickers  Wow, that simple? Am glad it's working now, i must have missed or misunderstood that from the documentation, although there is no explicit example...

Just a quick question, _I suppose the change above doesn't require or affect migrations, **correct**?_

**Comment by ajcvickers** [comment]
@McKabue It should not have any affect on migrations.

**Comment by McKabue** [comment]
Does `modelBuilder.UsePropertyAccessMode(PropertyAccessMode.PreferFieldDuringConstruction);` or `.UsePropertyAccessMode(PropertyAccessMode.Property)` affect default values like ?
```csharp
public DateTime? CreaedOn { get; set; } = DateTime.UtcNow;
```

**Comment by ajcvickers** [comment]
@McKabue I don't believe it will have any affect.
