### ISSUE TITLE
Inserting an entity with a required string field that is marked as a key allows empty and blank strings

### ISSUE THREAD

**Issue by sethjackson** [dotnet/efcore#18996]
Inserting an entity with a required string field that is marked as a key allows empty and blank strings.

### Steps to reproduce

```csharp
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public enum FieldType
{
    Text,
    Numeric,
    Related
}

public class Field
{
    [Required]
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public string Name { get; set; }
    public FieldType Type { get; set; }
    public string Value { get; set; }
    public int? RelatedFieldId { get; set; }
}
```

```csharp
using Microsoft.EntityFrameworkCore;

public class ApplicationContext : DbContext
{
    public ApplicationContext(DbContextOptions<ApplicationContext> options)
            : base(options)
    {
    }

    public DbSet<Field> Fields { get; set; }
}
```

```csharp
_context.Fields.Add(new Field
{
    Name = "",
    Type = FieldType.Text
});
_context.Fields.Add(new Field
{
    Name = " ",
    Type = FieldType.Text
});
_context.SaveChanges();
```

I would expect an exception to be thrown similar to how an exception is thrown when the `Name` property is `null`.

I have tried the `Microsoft.EntityFrameworkCore.InMemory` provider as well as `Microsoft.EntityFrameworkCore.Sqlite` provider (with an on-disk DB and an `:memory:` DB) and they all exhibit the same behavior.

The documentation for [RequiredAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute) states that:

> The RequiredAttribute attribute specifies that when a field on a form is validated, the field must
> contain a value. A validation exception is raised if the property is null, contains an empty string
> (""), or contains only white-space characters.

### Further technical details

EF Core version: 3.0.0.
Database provider: Microsoft.EntityFrameworkCore.Sqllite
Target framework: .NET Core 3.0
Operating system: Windows 10

**Comment by ajcvickers** [comment]
@sethjackson EF Core doesn't do any validation of your entities beyond what is necessary for it to function. This is because experience has shown that validation usually happens first in the U.I., then in the service/application, and most times anything EF would do is redundant and just adds overhead. So the work to support validation is not something we plan to invest in for EF Core.

**Comment by sethjackson** [comment]
Ok. Would it be possible to mention something like this in the EF Core docs? Perhaps I missed it but this was not clear to me from reading the EF Core docs or the `System.ComponentModel.DataAnnotations` docs either.

**Comment by ajcvickers** [comment]
@sethjackson I opened https://github.com/aspnet/EntityFramework.Docs/issues/1942 for this.

**Comment by sethjackson** [comment]
Thanks!
