### ISSUE TITLE
IsRequired not throwing an exception when reading null values.

### ISSUE THREAD

**Issue by TomTimTam** [dotnet/efcore#18994]
IsRequired doesnt apear to do anything. Reading & writing nulls from the database for a string goes against the context contract.

### Steps to reproduce
Add `.IsRequired()` to a string property on any given table.
https://dotnetfiddle.net/k04Haf

### Further technical details

EF Core version: 2.1.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: 2.1.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.5

**Comment by ajcvickers** [comment]
@TomTimTam EF Core doesn't do validation of your data. Doing so for queries would add overhead to the common case where the data is correct. Validation before saving is something that has shown to be done better at a higher level than EF, and hence doing in EF adds overhead without significant value.
