### ISSUE TITLE
IQueryModelGenerator 在3.0中是否有替代的

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [dotnet/efcore#19008]
IQueryModelGenerator 在3.0中是否有替代的

**Comment by zhanghaiboshiwo** [comment]
How does core 3.0 convert IQueryable<TEntity>into SQL

**Comment by zhanghaiboshiwo** [comment]
public static string ToSql<TEntity>(this IQueryable<TEntity> query, Microsoft.EntityFrameworkCore.DbContext dbCtx)
        {

            IQueryModelGenerator modelGenerator = dbCtx.GetService<IQueryModelGenerator>();
            QueryModel queryModel = modelGenerator.ParseQuery(query.Expression);
            DatabaseDependencies databaseDependencies = dbCtx.GetService<DatabaseDependencies>();
            QueryCompilationContext queryCompilationContext = databaseDependencies.QueryCompilationContextFactory.Create(false);
            RelationalQueryModelVisitor modelVisitor = (RelationalQueryModelVisitor)queryCompilationContext.CreateQueryModelVisitor();
            modelVisitor.CreateQueryExecutor<TEntity>(queryModel);
            var sql = modelVisitor.Queries.First().ToString();
            //return sql;
            return default;
        }

The previous method is no longer available

**Comment by smitpatel** [comment]
SEe https://gist.github.com/rionmonster/2c59f449e67edf8cd6164e9fe66c545a#gistcomment-3040767
