### ISSUE TITLE
DateTime.UtcNow.Subtract no longer works in EF Core 3.0?

### ISSUE THREAD

**Issue by patricknolan** [dotnet/efcore#19000]
I Just updated to EF Core 3.0 and am getting a heap of errors.

The following query was working fine before upgrading.

```
var count = await this.Entities.Events.CountAsync(e =>
e.UserId.Value.Equals(user.Id) && e.EventTypeId == Convert.ToInt32(EventTypes.ClientAuthenticated) && e.Created >= DateTime.UtcNow.Subtract(new TimeSpan(1, 0, 0, 0)));
```

It now throws the following error.

`{"The LINQ expression 'Count<Event>(\r\n    source: DbSet<Event>, \r\n    predicate: (e) => e.UserId.Value.Equals((Unhandled parameter: __8__locals1_user_Id_0)) && e.EventTypeId == 81 && e.Created >= DateTime.UtcNow.Subtract((Unhandled parameter: __ts_1)))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."}`

If I modify my code to the following it works again

```
var dt = DateTime.UtcNow.Subtract(new TimeSpan(1, 0, 0, 0));
var count = await this.Entities.Events.CountAsync(e => e.UserId.Value.Equals(user.Id) && e.EventTypeId == Convert.ToInt32(EventTypes.ClientAuthenticated) && e.Created >= dt);
```

Is this a deliberate change or a bug? If it's a deliberate change it's going to make upgrading very painful for people :(

**Comment by smitpatel** [comment]
It is a deliberate breaking change as mentioned here https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client
