### ISSUE TITLE
ClientSetNull behavior changed 

### ISSUE THREAD

**Issue by Detzito** [dotnet/efcore#19009]
I don't see any changes about ClientSetNull behavior in your documentation, but this behavior seems to have changed between Ef Core 2.2 and 3.0.

Now, in a one-to-many relation, the parent removal immediatly unset childs' FK and the null FK is saved in database. In 2.2, the FK was kept.

### Steps to reproduce

1. Create a one-to-many relation
2. Set the DeleteBehavior on ClientSetNull
3. Create a Parent and one or many childs. Save them.
4. Remove the Parent using DbSet.Remove function. The ParentId field is set to null on every child.
5. Call SaveChangesAsync() and the childs become orphans. Precision : in my case, SaveChangesAsync sets Parent state to Modified and SoftDeletes it. 
6. In database, the FK on childs is null.

In 2.2, it worked...

Maybe am I wrong but... for me ClientSetNull means I am responsible to manually unset FK  to the newly deleted entity, isn't it ?

this documentation is not up to date and contains contradictions...
https://docs.microsoft.com/fr-fr/ef/core/saving/cascade-delete

and this one says the documentation applies to 3.0.......2.0 but I think it's not the case : 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-3.0#feedback

### Further technical details

EF Core version: 3.0.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) (e.g. Microsoft.EntityFrameworkCore.SqLite)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@Detzito The default timing for cascades has changed in 3.0. See the [breaking change documentation](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#cascade) for how to configure the previous behavior.
