### ISSUE TITLE
Query :: make sure we generate valid and human-readable parameter names for complex closure scenarios

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1901]
This is related to #1742 
Sometimes compiler creates funky names when generating a closure. Since we based out parameter names on the FieldInfo/PropertyInfo, those names may be affected and we should compensate.

Example of a complex closure scenario could be:

```
    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "ComplexClosure", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    public class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    public class Details
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    public class TestClass
    {
        public void TestMethod(Details details)
        {
            using (var ctx = new MyContext())
            {
                var firstName = details.FirstName;
                var lastName = details.LastName;
                var q = ctx.Customers.Where(c => c.FirstName == firstName && c.LastName == details.LastName).ToList();
            }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var test = new TestClass();
            test.TestMethod(new Details { FirstName = "Foo", LastName = "Bar" });
        }
    }
```

Currently, for the above scenario we would generate a name like:
@__8__locals1_details_LastName_1

While valid, it's not very readable. We should also investigate other complex closure scenarios to see if compiler generates some other name patterns.

**Comment by anpete** [comment]
@__details_LastName_1 would be good here.

We could also look at prefixing/suffixing improvements.

**Comment by ajcvickers** [comment]
Triage: we discussed this and we think parameter names are generally pretty good now, but even if there are cases where we generate the name above, then we're still okay with that. We can revisit this in the future of it becomes an issue with the community or we discover cases where names are very unreadable and/or confusing.

**Comment by smitpatel** [comment]
parameter names
`@__firstName_0`
& `@__details_LastName_1`
