### ISSUE TITLE
Query tags with inheritance table(s) in the query

### ISSUE THREAD

**Issue by sshukurov** [dotnet/efcore#19011]
TagWith does not output the tag when inheritance table(s) are involved in the query.

I created a minimal repro here: https://github.com/sshukurov/EntityFrameworkCoreProblemWithQueryTags

### Further technical details

EF Core version: 3.0.1.
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.0.1.
Target framework: .NET Core 3.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.3.10

**Comment by ajcvickers** [comment]
@sshukurov I was able to reproduce this on SQL Server with 3.0. However, the issue does not reproduce with 3.1:

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      -- This tag must show up!

      SELECT [j].[Id]
      FROM [Jobs] AS [j]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      -- This tag must be missing!

      SELECT [u].[Id], [u].[Name], [u].[ispoweruser], [u].[Level]
      FROM [Users] AS [u]
      WHERE [u].[ispoweruser] IN (CAST(0 AS bit), CAST(1 AS bit))
```
I expect the root cause is the same as #18466

Can you try again with 3.1 preview 3?
