### ISSUE TITLE
Query: Off-By-One errrors

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19028]
https://github.com/aspnet/EntityFrameworkCore/blob/88bd694897b96557c37fdc58ac2116d3ea269736/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L392

https://github.com/aspnet/EntityFrameworkCore/blob/88bd694897b96557c37fdc58ac2116d3ea269736/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L898

**Comment by roji** [comment]
@smitpatel looks like you already fixed this in c2c469d9bd2140ffe43e6dae43b674ce67dead9c?

**Comment by maumar** [comment]
I looked thru all of the instances of Count comparisons inside SelectExpression and they are correct, closing
