### ISSUE TITLE
API to get the underlying entity CLR type from a proxy instance

### ISSUE THREAD

**Issue by davisnw** [dotnet/efcore#19035]
In EF6, we had `ObjectContext.GetObjectType(...)`. That no longer exists in EF Core.

Particular use case - enforcing certain edit restrictions within the db context for specific types.  In this case, the restrictions are looked up in a dictionary based on the entity type.

Now that EFCore supports lazy loading, it is important that the actual entity type be used as the key, not the proxied type.  So `e.Entity.GetType()` is not reliable in the face of lazy loading proxies.

I see a few candidates, e.g.
```
Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry e = this.ChangeTracker.Entries().First();
Type a = e.Metadata.ClrType;
Type b = e.Metadata.DefiningEntityType.ClrType;
Type c = e.Metadata.BaseType.ClrType;
e.Entity.GetType();
```
`EntityEntry.Metadata.ClrType` docs say:
"Gets the CLR class that is used to represent instances of this type. Returns null if the type does not have a corresponding CLR class (known as a shadow type).

Shadow types are not currently supported in a model that is used at runtime with a DbContext. Therefore, shadow types will only exist in migration model snapshots, etc."

It is not clear here whether ClrType could return a proxied type or not when lazy loading is enabled.

`EntityEntry.Metadata.DefiningEntityType` docs say:
"Gets the defining entity type."

Not particularly helpful, as there is no information on what "defining entity type" means.  Not clear how this would be different in practice from just calling `ClrType` directly. One is left to infer that this *probably* doesn't return a proxied type?

`EntityEntry.Metadata.BaseType` docs say:
"Gets the base type of this entity type. Returns null if this is not a derived type in an inheritance hierarchy."

That is not particularly clear on whether or not proxied types would be considered part of the inheritance hierarchy.

See also: https://stackoverflow.com/questions/38296805/how-to-get-the-entity-poco-type-from-the-entity-proxy-type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f53661f7-f873-a82d-1530-02d41be92b6c
* Version Independent ID: 0a8ed446-c260-ca04-b6e0-0ec0672c344f
* Content: [EntityEntry.Metadata Property (Microsoft.EntityFrameworkCore.ChangeTracking)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.entityentry.metadata?view=efcore-3.0#Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntry_Metadata)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.ChangeTracking/EntityEntry.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.ChangeTracking/EntityEntry.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by davisnw** [comment]
If adding a new api, I think it would be good to clarify how it is similar and how it is different from the EntityEntry metadata api.

**Comment by orionstudt** [comment]
AFAIK `IEntityType.ClrType` is a fool proof way to get the POCO type (based on the way the Proxy lib uses that property). Is that not the case? Is a new API necessary? Maybe just update the docs for the `IEntityType.ClrType`?

If any changes or new API need to be done here I could knock it out while proxies are still fresh on my mind.

**Comment by ajcvickers** [comment]
@orionstudt If you have the IEntityType, then yes this will work. However, this issue is about finding the entity CLR type when starting with just an instance. This instance might or might not be a proxy. (I'm honestly not convinced there is really much value here.)

**Comment by davisnw** [comment]
@ajcvickers The original issue was filed as a documentation issue.  In the use case given in the original post, I noted how EF6 provided the information via `ObjectContext.GetObjectType(...)`.  In the rest of the example, I examined how that might be accomplished in EF Core using the `Metatdata` property (`IEntityType`) and noting that the documentation wasn't clear to me.

If EFCore guarantees that e.g. `IEntityType.ClrType` will not be a proxied type, but the actual type from the POCO class then I don't see a reason for a new api, but still think the documentation could be more clear e.g.:
- Make it clear that the type returned by `ClrType` is the actual type defined on the entity POCO class, and are not affected by lazy loading proxies
- Explaining what `DefiningType` means
- Making clear that proxies are not considered as part of the inheritance hierarchy for `BaseType`

**Comment by davisnw** [comment]
Understanding that my original post was mixing somewhat different things (getting the unproxied type from an instance, vs getting the type from the EntityEntry).

So just speaking from my personal experience, if we can say that the correct (unproxied) type is available via `IEntityType.ClrType` (via `EntityEntry.Metadata`), then I haven't found a need to get it directly from the instance (as was done in EF6)

**Comment by ajcvickers** [comment]
@davisnw Fair enough; I'm convinced we don't need this. Thanks @davisnw and @orionstudt for your analysis. I added a link to this thread to a dosc issue for proxies.
