### ISSUE TITLE
Build one model for all data stores

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1904]
We decided to change back to building a single model for all data stores. This has several implications:
- Data store specific conventions should, as a best practice, not change the structure of the model, but should only add annotations. If the structure of the model is changed, then this will result in a different structure for all data stores. For example, if a new column is added by one data store, it will show up in all other data stores as well.
- The way annotations work doesn't need to change and #1542 can be closed. 
- The way model builders and conventions work needs to be changed. This is the major work item being tracked by this bug. By default, only the conventions for the currently selected data store will run. However, it should be possible to change this in OnModelCreating to also run conventions for any other available data store.

**Comment by bricelam** [comment]
The SqlServerModelDiffer will also need to be updated to handle provider-specific overrides.

**Comment by bricelam** [comment]
In fact, the whole `ModelDiffer` architecture may need to change to allow multiple providers to play part in the diffing process. The implementation can be deferred until after RTM, but we should think about it up front to prevent/minimize breaking changes to the Migrations provider model.

**Comment by bricelam** [comment]
We also need to review places in `EntityFramework.Relational` where we call `entityType.Relational()` (or similar) to account for provider-specific overrides.

**Comment by rowanmiller** [comment]
We'll enable this when we work on multi-provider migrations etc.
