### ISSUE TITLE
DbSet query with DateTime.Now parse CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by 491134648** [dotnet/efcore#19043]
### Steps to reproduce
Dbset query with DateTime.Now property with the definition of a DateTime.Now variable, generating sql is not the same, whether there are related configuration items can close the transfer related database function
`
DateTime dateTime = DateTime.Now;
            ActivityCourse activityCourse = _activityCourse.Query(d => d.CourseID == courseID
            && d.StartTime <= dateTime
            && d.EndTime > dateTime
            && d.IsDel == false
            ).FirstOrDefault();
            var data= activityCourse = _activityCourse.Query(d => d.CourseID == courseID
             && d.StartTime <= DateTime.Now
             && d.EndTime > DateTime.Now
             && d.IsDel == false
            ).FirstOrDefault();
`

### Further technical details

EF Core version: 2.2.6
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET Core 2.2
Operating system:windows 10
IDE: (e.g. Visual Studio 2019 16.3)
![image](https://user-images.githubusercontent.com/9816794/69477166-d3e40d00-0e1d-11ea-8c4d-1bb1447d0921.png)

**Comment by hez2010** [comment]
I think it's not bug but by design. If you want to use specific DateTime for query, you should save the value in a variable first and pass it as a parameter.

**Comment by ajcvickers** [comment]
@hez2010 Seems to have it right.

**Comment by 491134648** [comment]
Yes,When I set it to a variable, he was right.Whether this can provide the relevant configuration item switch, or provide the relevant translation function instructions in the EF document, it is easy to write this DateTime.Now, the result of the mysql time zone inconsistent when embarrassed
