### ISSUE TITLE
Forward types

### ISSUE THREAD

**Issue by hikalkan** [dotnet/efcore#19046]
Hi,

Is there any way to forward a pre-configured entity type to another type?

Assume that I have a NuGet package which contains a module for the Identity library that contains an IdentityUser class used as an entity in the IdentityDbContext.

This package is a reusable module. For a particular application, I want to re-use this module but I want to replace the IdentityUser with MyIdentityUser which is derived from the IdentityUser and overloads some virtual methods.
This is a good way to create some reusable modules as NuGet packages, yet allow developers to customize the business logic for the entities inside the module.

I want these:

* Entity framework core allows to simply forward IdentityUser to MyIdentityUser by configuring the DbContext in the OnModelCreating.
* The reusable module (NuGet package) will still continue to use IdentityUser everywhere (like `DbSet<IdentityUser>` and in LINQ expessions), but EF Core will materialize MyIdentityUser instead of the IdentityUser while querying and handle it on save.

What do you think?

**Comment by ajcvickers** [comment]
@hikalkan This would require a lot of magic! We discussed this in triage, but we don't think it is something we are going to implement. The mechanism for [customizing ASP.NET Core Identity](https://docs.microsoft.com/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.0) may give you basically what you need, but it won't be as transparent as you are suggesting.

**Comment by hikalkan** [comment]
I respect you that you don't want to implement it, but...

Identity module was just a sample. Microsoft made it customizable, but the effort was really huge and the result is a bad design (no domain logic in the entities, requires to make many generic classes... etc.). Think that you have tens of modules in a real world scenario. Designing all the modules like Identity module would be terrible.

Thank you for your time to answer.
