### ISSUE TITLE
Missing UseDatabaseNullSemantics configurations 

### ISSUE THREAD

**Issue by stealthzeus** [dotnet/efcore#19054]
In EF core there seems to be no way to set the UseDatabaseNullSemantics value to be true. And it seems by default this value is false and it generates the OR clauses in the where clause when using linq to sql, without leaving any way for users to generate the unsafe query assuming the variables are not null.

Add another method in DbConextOptionsBuilder to allow configuration of UseDatabaseNullSemantics value

**Comment by smitpatel** [comment]
Please use [UseRelationalNulls](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.relationaldbcontextoptionsbuilder-2.userelationalnulls?view=efcore-3.0#Microsoft_EntityFrameworkCore_Infrastructure_RelationalDbContextOptionsBuilder_2_UseRelationalNulls_System_Boolean_) API to configure EF Core to use database null semantics.
