### ISSUE TITLE
Stored Procedures

### ISSUE THREAD

**Issue by matthewwren** [dotnet/efcore#19075]
Previously I was using DbQuery on the DBContext to declare types that were returned from stored procedures.  In EF Core 3 I am told to change from DbQuery to DbSet.  However when I do this and run Add-Migration the migration tries to create tables for these entities.  I have tried various ways of stopping this from happening via the context to no avail.  The only solution I have found that actually allows my queries to work is to simply remove the tables from the migration, but then they still exist in the generated snapshot class as tables, so this is clearly a hack.  What is the correct way of using custom types that are neither tables nor views, but returned from stored procedures?

**Comment by ajcvickers** [comment]
@matthewwren This is tracked by #2725. The easiest workaround for now is to use `ToView` on the entity types. Migrations will then exclude it; it doesn't matter that it's not really a view.
