### ISSUE TITLE
Set provisioned throughput for cosmos db using EFcore

### ISSUE THREAD

**Issue by pavitrag123** [dotnet/efcore#19074]
Is there a way to set provisioned throughput at cosmos database level while using efcore like below. 

using Microsoft.Azure.Documents.Client

![image](https://user-images.githubusercontent.com/19691194/69617262-f5333c00-105d-11ea-9d0f-24e0ef8664ce.png)

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17301
