### ISSUE TITLE
Nullable object must have a value

### ISSUE THREAD

**Issue by MartinZikmund** [dotnet/efcore#19089]
After upgrading from 2.2 to 3.0, I have encountered a problem when using nullable fields. In case of 3.0 I get `InvalidOperationException` with `Nullable object must have a value`.

When a nullable field is used and property getter checks its nullability, the exception is thrown when instance of the entity is added to context:

``` C#
    private DateTime? _created;

    public DateTime Created
    {
        get => _created ?? DateTime.UtcNow;
        set => _created = value;
    }
```

Luckily the **workaround** is simple:

``` C#
public DateTime Created { get; set; } = DateTime.UtcNow;
```

It may not be a bug per se, but I would like to understand, what is the underlying reason why this does not work.

### Steps to reproduce

Can be reproduced with a very simple Core 3.0 Console app.

**Program.cs**
``` C#
static void Main(string[] args)
{
    var dbOptions = new DbContextOptionsBuilder<TestDbContext>()
        .UseInMemoryDatabase("test")
        .Options;
    using (var context = new TestDbContext(dbOptions))
    {
        context.Users.Add(new User()); // The exception occurs here.
        context.SaveChanges();
    }
}
```

**TestDbContext**
``` C#
public class TestDbContext : DbContext
{
    public TestDbContext(DbContextOptions<TestDbContext> options)
        : base(options)
    {
        
    }

    public DbSet<User> Users { get; set; }
}
```

**User.cs**
``` C#
public class User
{
    public int Id { get; set; }

    // This works.
    //public DateTime Created { get; set; } = DateTime.UtcNow;

    // This does not work.
    private DateTime? _created;

    public DateTime Created
    {
        get => _created ?? DateTime.UtcNow;
        set => _created = value;
    }
}
```

### Further technical details

EF Core version: 3.0.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer): In-memory
Target framework: Core 3.0
Operating system: Windows 10
IDE: VS 16.3.8

**Comment by ajcvickers** [comment]
@MartinZikmund The issue here is that starting with EF Core 3.0 EF will [read and write the field directly by default](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#backing-fields-are-used-by-default). This only works when the field always contains valid values for the property, which is not the case here. EF can be told to use the property always with:
```C#
modelBuilder.Entity<User>().Property(e => e.Created).UsePropertyAccessMode(PropertyAccessMode.Property);
```

**Comment by MartinZikmund** [comment]
@ajcvickers Thank you for the explanation, it is really helpful 😊 .
