### ISSUE TITLE
Query: re-visit FunctionPreprocessingExpressionVisitor

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#19082]
During pre-process we add null checks to StartsWith and EndsWith. We should double check if we can do better there, in most cases those checks are not needed, perhaps we can be smarter in detecting the cases when they matter.

**Comment by smitpatel** [comment]
Currently, we don't have any ideas to do anything better. If we ever come up with a solution we can improve it. This is not causing any issue right now so closing it as we don't need to track it.
