### ISSUE TITLE
Feature request: dotnet ef dbcontext scaffold arguments order

### ISSUE THREAD

**Issue by doggy8088** [dotnet/efcore#19106]
I'm writing a `dotnet-ef` command auto-completion tool. Here is the usage of `dotnet ef dbcontext scaffold`:

```sh
dotnet ef dbcontext scaffold -h
```

```txt
Usage: dotnet ef dbcontext scaffold [arguments] [options]

Arguments:
  <CONNECTION>  The connection string to the database.
  <PROVIDER>    The provider to use. (E.g. Microsoft.EntityFrameworkCore.SqlServer)
```

I'd like to recommend change the arguments order to `dotnet ef dbcontext scaffold <PROVIDER> <CONNECTION>`.

It because the `<CONNECTION>` are vary from different `<PROVIDER>`. If I can guess the `<PROVIDER>` first, then I can suggest `<CONNECTION>` after this.

**Comment by ajcvickers** [comment]
@doggy8088 This change is not something we are likely to do because it would break existing usage of the tool. However, we are interested in the approach you are taking here. What mechanism are you using to implement auto completion? What kind of completion are you thinking of for connection strings?

**Comment by doggy8088** [comment]
@ajcvickers I made a `dotnet` CLI auto-completion tool for Command Prompt that based on famous tool [Clink](https://mridgers.github.io/clink/). I already implemented all the built-in .NET Core CLI commands and arguments including `dotnet-ef` global tool. If you are a CMD lover just like me, you will like it. 😄

If you'd like to try out, just following the commands to install. 

```sh
choco install clink -y
mkdir c:\Projects
cd /d c:\Projects
git clone https://github.com/doggy8088/clink-completions.git
cd clink-completions
install.bat
```

**Comment by ajcvickers** [comment]
@doggy8088 Thanks for the additional information. Are the "two different connection strings" hard-coded example connection strings? Or do you attempt to find them in config somewhere?

In terms of this issue, I'm going to close this as we're not going to change the argument order. However, note that we have #5976 open tracking built-in completion support.

**Comment by doggy8088** [comment]
Yes, it's hard-coded. It works as a template.
