### ISSUE TITLE
Migrations: Track Parent Migrations

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#1911]
This would allow us to better detect conflicts, but we would also need some way to merge.

**Comment by rowanmiller** [comment]
@bricelam do you think we still need this now that we have model snapshot?

**Comment by bricelam** [comment]
It would help us detect conflicts. The snapshot in the migration can still get into a bad state. We use that snapshot for column types currently. We'll use it for rebuilds in the future.

**Comment by bricelam** [comment]
So, it *will* help us do better, but maybe what we have is "good enough".

**Comment by bricelam** [comment]
Although doing a rebuild but missing a column because it was added (but not synced) before you generated your migration would be a pain to debug (and maybe even notice).

**Comment by rowanmiller** [comment]
Ah yeah... rebuilds from the snapshot... didn't think of that. Is this trivial to just add now, or do you think it should go on backlog?

**Comment by bricelam** [comment]
It's trivial to add the pointer, but it might end up being YAGNI since we won't actually do anything with it now.

**Comment by bricelam** [comment]
I don't think it's a breaking change to add later either since we can just infer the parent migration from the order

**Comment by rowanmiller** [comment]
We can do this if we find a feature that would use it

**Comment by bricelam** [comment]
My thoughts exactly
