### ISSUE TITLE
Problemas con take y skip Sql 2008 

### ISSUE THREAD

**Issue by ivancr8824** [dotnet/efcore#19114]
tengo un problema pero es por la version que utilizo del SQL SERVER 2008 al momento de querer paginar el sgte error

incorrect syntax near 'offset'. invalid usage of the option next in the fetch statement.'

Esto pasa justo cuando se ejecutan la instrucción take y skip entonces estuve buscando una solucion y me indican que agrege esto al startup del proyecto server

services.AddDbContext<ApplicationDbContext>(option =>

   option.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), b => b.UseRowNumberForPaging()));

pero aun así no me funciona y sigue lanzando el error

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ErikEJ** [comment]
SQL Server 2008 is no longer supported by EF Core

**Comment by ajcvickers** [comment]
Duplicate of #16400
