### ISSUE TITLE
the same object got different hash code in join query, causing group by to failed

### ISSUE THREAD

**Issue by yypyinyipeng** [dotnet/efcore#19117]
good weekend

before，i use efcore v2.2.4 and execute the following query
```sql
var result = await (from caseBase in _unitofwork.DbContext.CaseBases
                    join caseDiagnose in _unitofwork.DbContext.CaseDiagnose 
                        on caseBase.CaseId equals caseDiagnose.CaseId into caseDiagnosis
                    from diagnosis in caseDiagnosis.DefaultIfEmpty()
                    where caseBase.PatientId == 371
                    select new
                    {
                        caseBase,
                        diagnosis
                    })
                .AsNoTracking()
                .ToListAsync();
 var group = result.GroupBy(c => c.caseBase);
```
it works as expected -- i got 10 objects in result and 7 objects in group
when i upgrade efcode to v3.0.0, using the same query, i got 10 objects in result and 10 objects in group!   
after checked, i find in efcore v2.2.4, the same object got the same hashcode, but in efcore v3.0.0 , the "same" object got the different hashcode, so this should be the cause of the issue, could some can explain why it happened? thanks a lot.  

![2 2 4](https://user-images.githubusercontent.com/13032120/69897718-aef61980-138a-11ea-909e-84441a80a525.png)

![3 0 0](https://user-images.githubusercontent.com/13032120/69897733-dd73f480-138a-11ea-8521-0d787b0cb6df.png)

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.PostgreSQL
Target framework: NET Core 3.0
Operating system:
IDE:

**Comment by benaadams** [comment]
Hashcode shouldn't be being used in a query or stored to db?

[Object.GetHashCode Method](https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netcore-3.0#remarks)

> Two consequences follow from this:
> 
> * You should not assume that equal hash codes imply object equality.
> 
> * You should never persist or use a hash code outside the application domain in which it was created, because the same object may hash across application domains, processes, and platforms.
> 
>  Warning
> 
> A hash code is intended for efficient insertion and lookup in collections that are based on a hash table. A hash code is not a permanent value. For this reason:
> 
> * Do not serialize hash code values or store them in databases.
> * Do not use the hash code as the key to retrieve an object from a keyed collection.
> * Do not send hash codes across application domains or processes. In some cases, hash codes may be computed on a per-process or per-application domain basis.
> * Do not use the hash code instead of a value returned by a cryptographic hashing function if you need a cryptographically strong hash. For cryptographic hashes, use a class derived from the System.Security.Cryptography.HashAlgorithm or System.Security.Cryptography.KeyedHashAlgorithm class.
> * Do not test for equality of hash codes to determine whether two objects are equal. (Unequal objects can have identical hash codes.) To test for equality, call the ReferenceEquals or Equals method.

**Comment by yypyinyipeng** [comment]
> Hashcode shouldn't be being used in a query or stored to db?
> 
> [Object.GetHashCode Method](https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netcore-3.0#remarks)
> 
> > Two consequences follow from this:
> > 
> > * You should not assume that equal hash codes imply object equality.
> > * You should never persist or use a hash code outside the application domain in which it was created, because the same object may hash across application domains, processes, and platforms.
> > 
> > Warning
> > A hash code is intended for efficient insertion and lookup in collections that are based on a hash table. A hash code is not a permanent value. For this reason:
> > 
> > * Do not serialize hash code values or store them in databases.
> > * Do not use the hash code as the key to retrieve an object from a keyed collection.
> > * Do not send hash codes across application domains or processes. In some cases, hash codes may be computed on a per-process or per-application domain basis.
> > * Do not use the hash code instead of a value returned by a cryptographic hashing function if you need a cryptographically strong hash. For cryptographic hashes, use a class derived from the System.Security.Cryptography.HashAlgorithm or System.Security.Cryptography.KeyedHashAlgorithm class.
> > * Do not test for equality of hash codes to determine whether two objects are equal. (Unequal objects can have identical hash codes.) To test for equality, call the ReferenceEquals or Equals method.

thanks for your quick reply. 
query results produce different characteristics after upgrade the version of efcode, maybe i used hashcode to verify it was wrong, but this issue still exists -- group by object in client does not working as before

**Comment by smitpatel** [comment]
An intentional breaking change as per https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#notrackingresolution 
Since you are doing client side grouping, you should provide a custom key comparer which matches entities based on their key values rather than reference equality.

**Comment by yypyinyipeng** [comment]
> An intentional breaking change as per https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#notrackingresolution
> Since you are doing client side grouping, you should provide a custom key comparer which matches entities based on their key values rather than reference equality.

got it, thanks
