### ISSUE TITLE
Can Scaffold-DbContext generate entities with comments

### ISSUE THREAD

**Issue by netnr** [dotnet/efcore#19113]
Bring comments and swagger output interface more intuitive

**Comment by ErikEJ** [comment]
Implemented for SQL Server in 3.0

**Comment by ajcvickers** [comment]
@netnr Are you asking for comments from the database to be converted to C# comments on entity types? For example:

```C#
/// <summary>
///    This came from the database...
/// </summary>
public class Blog
{
    ...
}
```

**Comment by netnr** [comment]
@ajcvickers Yes

**Comment by ajcvickers** [comment]
@netnr This is something that we would support as part of #4038. However, external tools such as those from @ErikEJ and @tonysneed may already support this through their templating mechanisms.

**Comment by tonysneed** [comment]
@netnr Here is my scaffolding library: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars. EF Core Power Tools by @ErikEJ also include my scaffolding library.

**Comment by ErikEJ** [comment]
@ajcvickers Any particular reason why this could not simply be in the product?
see https://github.com/ErikEJ/EFCorePowerTools/pull/372/files for needed changes.

**Comment by ajcvickers** [comment]
@ErikEJ Do you really feel people want this behavior by default? /cc @bricelam @JeremyLikness

**Comment by ErikEJ** [comment]
Not 100% sure, I am making it the default for now in the daily build, but fail to see why it would be an issue. 

FWIW, EF Reverse POCO template has it enabled by default, and I cannot find any complaints about it. https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/Database%20NorthwindSqlCe40.tt#L84 - but then again I just found out who made it the default: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/16 😆 

I also saw this: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/41a7eaa248de1afc8d6bd3567df2f774cd47571d

**Comment by ajcvickers** [comment]
@ErikEJ Let's circle back round after it's been the default for a month or two. If there are still no complaints, then we should consider it.

**Comment by ErikEJ** [comment]
@ajcvickers Sounds good, I will do a release to MarketPlace soon then.

**Comment by ErikEJ** [comment]
@ajcvickers Power Tools with comments on by default has been released since May 2020, and I have not had a single complaint - except about bugs in my implementation 😆 

This is what I currently have:

```csharp
        private void WriteComment(string comment)
        {
            if (!string.IsNullOrWhiteSpace(comment))
            {
                _sb.AppendLine("/// <summary>");

                foreach (var line in comment.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None))
                {
                    _sb.AppendLine($"/// {System.Security.SecurityElement.Escape(line)}");
                }

                _sb.AppendLine("/// </summary>");
            }
        }

```

**Comment by ajcvickers** [comment]
Thanks for the update, @ErikEJ.

**Comment by bricelam** [comment]
I do this in [my T4 templates](https://github.com/bricelam/EFCore.TextTemplating/blob/master/EFCore.TextTemplating/MyEntityTypeGenerator.tt#L15-L23) by default too. Looking at Erik's code, I have a few bugs to fix... 😬

**Comment by ErikEJ** [comment]
@bricelam yeah, that was also my initial implementation, until I faced some real life comments

**Comment by ErikEJ** [comment]
Are you planning to enable this in EF Core 6 ?

**Comment by bricelam** [comment]
I think we'd happily accept a PR for 6.0

**Comment by Gambero81** [comment]
Is this feature only for ef6? can be ported in current ef5?

**Comment by roji** [comment]
@Gambero81 EF Core 5.0 has already been released, and so is only receiving important bug fixes. See our [release planning page](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more details.

**Comment by ErikEJ** [comment]
@Gambero81 it is available in EF core power Tools for EF Core 5
