### ISSUE TITLE
Escape provider-specific symbols in user-input when using EF.Functions.Like

### ISSUE THREAD

**Issue by nesterenko-kv** [dotnet/efcore#19118]
`EF.Functions.Like` doesn't make any escaping by default. Is there any in-built method to escape provider-specific symbols in string?

**Comment by roji** [comment]
Have you tried using [this overload of EF.Functions.Like](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctionsextensions.like?view=efcore-2.1#Microsoft_EntityFrameworkCore_DbFunctionsExtensions_Like_Microsoft_EntityFrameworkCore_DbFunctions_System_String_System_String_System_String_) which allows specifying the escape character?

**Comment by nesterenko-kv** [comment]
Yeap, I saw that one, but it means that I need manually escape the pattern, which is not the thing I want to do.
Take a look at this tests of basic string operations: [FunkyDataQueryTestBase](https://github.com/aspnet/EntityFrameworkCore/blob/09809a94e133da72c05f1f651194a58a10e7f260/test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs#L169)
There are in-built escaping functionality  in all provider-specific translators, for example:
[SqliteStringMethodTranslator](https://github.com/aspnet/EntityFrameworkCore/blob/0d76bbf45a42148924b413ef8f37bf49c1ce10d3/src/EFCore.Sqlite.Core/Query/Internal/SqliteStringMethodTranslator.cs#L287)

**Comment by roji** [comment]
Can you provide a bit more info on what you're trying to do? If we automatically escaped the special characters in the LIKE pattern, the LIKE expression wouldn't have any value anymore (i.e. you could just compare for equality...).

Regarding the functionality you linked to... The EscapeLikePattern method you're linking to is used when LIKE expressions are used to execute other .NET method calls, i.e. StartsWith/EndsWith. This is a different case from when a user called EF.Functions.Like: StartsWith/EndsWith need to behave exactly as they do in C#, where LIKE escape characters have no meaning (%, _, [, ]). On the other hand, when a user calls EF.Functions.Like they are directly and manually creating a LIKE expression, and so get the exact database behavior for it, without any escaping or behavior changes from us. It's important to keep it that way to allow people to express anything they want.

**Comment by nesterenko-kv** [comment]
I'm trying to implement `string.Contains` with `EF.Functions.Like`, but if I'll use it directly with user input it will give wrong output if input string contains some of those chars `%, _, [, ]`.
Is it possible to provide overload with FormattableString to EF.Functions.Like which will escape all passed strings?

**Comment by roji** [comment]
EF Core already translates string.Contains for you (with CHARINDEX in SQL Server), any reason you need to do it yourself?

I don't think it makes sense for us to expose such an overload of EF.Functions.Like - it would be useless in almost all cases, save maybe the one you're doing; the point of LIKE in generally to have those special characters unescaped.

Note that it's totally fine for you to copy-paste the EscapeLikePattern function from the appropriate provider if you really wish to implement things yourself.

**Comment by nesterenko-kv** [comment]
Well, ok. makes sense. Thanks!

**Comment by roji** [comment]
Can you confirm whether there was any issue with EF Core's translation of string.Contains that made you think about implementing your own?

**Comment by nesterenko-kv** [comment]
I wasn't sure whether `CHARINDEX` performs same as `LIKE`

**Comment by roji** [comment]
I'd be very interested if you could run a benchmark comparing the two on SQL Server (with raw SQL - no need to go through EF Core). If we see there's any significant difference we could consider changing the default implementation inside EF Core.

At least in theory CHARINDEX could perform better since it doesn't have to do any pattern matching, just look for a substring. But this kind of thing should always be measured.
