### ISSUE TITLE
Error when using migrations InitailCreate

### ISSUE THREAD

**Issue by gerardgiraffe** [dotnet/efcore#19134]
Using the Mac Visual Studio tutorial on MVC and ran dotnet ef migrations add InitialCreate
Using Catalina version 10.15
Visual Studio for Mac 8.4 preview (build 2535)
Error Message in terminal
Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.

Not sure where to go from here

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-au/ef/core/what-is-new/ef-core-3.0/breaking-changes#the-ef-core-command-line-tool-dotnet-ef-is-no-longer-part-of-the-net-core-sdk)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@gerardgiraffe Please post a small project/solution that demonstrates the error you are seeing.

**Comment by gerardgiraffe** [comment]
I will try if not to big I thought someone may have experienced this before and will try again later today thanks 

GerardGiraffe

**Comment by gerardgiraffe** [comment]
Thank you Arthur for responding. I have solved this by deleting the ef package installed with Visual Studio for Mac and replacing it with a later version and now it appears to work. The problem was caused by incompatibility between dotnetccore 3.1 and the version of ef I was using.

**Comment by gerardgiraffe** [comment]
See above
