### ISSUE TITLE
Unabled to generate database - Cannot find primary key

### ISSUE THREAD

**Issue by plouveau** [dotnet/efcore#1913]
I got an issue regarding my entity : 
[Table("EntityLocalized", Schema = "RDP")]
    public class EntityLocalized
    {
        [Key]
        [Column(Order = 0)]
        public virtual Byte EntityId { get; set; }
        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual Int32 CultureId { get; set; }
        [Required, MaxLength(200)]
        public virtual String Name { get; set; }
        [ForeignKey("EntityId")]
        public virtual Entity Entity { get; set; }
        [ForeignKey("CultureId")]
        public virtual Culture Culture { get; set; }
    }

When i'm doing the following command : "k ef migration add ContinentLocalized", I got this issue : 
k : Microsoft.Data.Entity.Metadata.ModelItemNotFoundException: The entity type 'RDP.WebStore.Data.Entities.ContinentLocalized' requires a key to be defined.

Am I doing something wrong ?

**Comment by rowanmiller** [comment]
Hey,

Data annotations are not yet supported so you will need to use the Fluent API for configuration. BTW here is the work item tracking data annotation support https://github.com/aspnet/EntityFramework/issues/107.

~Rowan
