### ISSUE TITLE
Many-to-Many Relationship in EF Core 2.2.2 not working

### ISSUE THREAD

**Issue by jcprata** [dotnet/efcore#19132]
Hi,

I am trying to dynamically creating a many-to-many relationship between two tables and has a support manual to do that i have read the following article: [EF 6 Many-to-Many Relationship](https://www.entityframeworktutorial.net/code-first/configure-many-to-many-relationship-in-code-first.aspx).

My classes are:
```
public partial class Role
{
	public Role()
	{
		PageRoles = new HashSet<PageRole>();
	}

	public int Id { get; set; }
	public string Name { get; set; }

	public virtual ICollection<PageRole> PageRoles { get; set; }
}
```
and
```
public class PageRole
{
	public PageRole() 
	{
		Roles = new HashSet<Role>();
	}

	public int Id { get; set; }
	public string Name { get; set; }
	public virtual ICollection<Role> Roles { get; set; }
}
```
When i try to create a migrate file this will generate the following error:

> Unable to determine the relationship represented by navigation property 'PageRole.Roles' of type 'ICollection<Role>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

I haven't created any code with API Fluent.

Thank you.

EF Core version: 2.2.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 2.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.9

**Comment by ajcvickers** [comment]
@Murplatina EF6 documentation will not be helpful for using EF Core. See https://docs.microsoft.com/en-us/ef/core/modeling/relationships#many-to-many for the EF Core documentation.

**Comment by Murplatina** [comment]
@ajcvickers thank you for your answer.
