### ISSUE TITLE
EF Core 3 Sql Server Version

### ISSUE THREAD

**Issue by ToddThomson** [dotnet/efcore#19149]
With EF Core 3, SQL Server 2008 is no longer supported. I am trying to decide which development SQL Server Express version to upgrade to. My production SQL database hosting provider now provides an upgrade to SQL Server 2016. I currently have SQL Server Express 2017 running locally to support Azure DevOps.

From an EF Core 3 SqlServer perspective does it matter which SQL Server version (2016 v 2017) is used?

**Comment by ErikEJ** [comment]
No, it does not matter.

**Comment by ToddThomson** [comment]
Thanks @ErikEJ
