### ISSUE TITLE
Surely this should work?

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#19143]
So essentially all i'm trying to do is "post" a collection of status update (DTO's) for transactions (Entities) in the db.
Since i don't know how big the status updates collection might be i decided to "batch" the db calls limiting the number of references I lookup to 1,000 per call.

I then go about pulling out of my db a "batch of transactions", expanding in to all the stuff I will need to apply the status update.

I have also added to the dbContext a property called "User" which pulls the current user from the system and expands in to that users roles like this ...

```cs
user = GetAll<B2BUser>(true)
    .Include(u => u.Roles)
        .ThenInclude(r => r.Role)
    .FirstOrDefault(u => u.Id == userName);
```
... this value is stored as a private property inside the context for the life of the context.
(in case that's relevant)

so ... moving on "foreach update" I pass the update and a batch of transactions in to another method which finds the transaction for the updates reference and then does a simple "t.Status = update.Status" and adds new item to the audit trail returning that in the process.

once all the updates are done I return the audit trail items that were created during this process ...
```cs
public async Task<IEnumerable<DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>>> UpdateStatusForBatch(IEnumerable<TransactionStatusUpdate> updates)
{
    if (updates != null && updates.Count() > 0)
    {
        var results = new List<DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>>();

        foreach (var subBatch in updates.BatchesOf(1000))
        {
            var references = subBatch.Select(u => u.Reference).ToArray();
            var transactions = Db.GetAll<T>(true)
                .Where(i => i.References.Any(r => references.Contains(r.Id)))
                .Include(i => i.AuditTrail)
                .Include(i => i.References)
                .Include(i => i.Buckets)
                    .ThenInclude(b => b.Bucket)
                        .ThenInclude(b => b.Roles)
                            .ThenInclude(br => br.Role)
                                .ThenInclude(r => r.Users)
                .ToArray();

            foreach(var bi in subBatch)
            {
                try
                {
                    var result = UpdateStatusFor(bi, transactions);
                    await Db.SaveChangesAsync();
                    results.Add(result);
                }
                catch (Exception ex)
                {
                    var result = new DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>
                    {
                        Item = bi,
                        Success = true,
                        Details = new[] { transactions.First(t => t.References.Any(r => r.Id == bi.Reference)).Audit(Objects.AuditItemLevel.Error, User, ex.Message) }
                    };

                    results.Add(result);
                }
            }
        }

        return results;
    }
    else
        return new List<DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>>();
}
```

**So to my question** 

I get this exception from EF ...
> The instance of entity type 'B2BUserRole' cannot be tracked because another instance with the same key value for {'UserId', 'RoleId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

... but at no point am I editing adding or removing a B2BUserRole instance to or from anything so i'm little confused as to the cause of this other than "there might be some overlap in the batching queries." (these entities are pulled to do security checks before applying the change to the root transaction entity).

As a test for that case I pulled the batching logic out and just sent a couple of status update to the endpoint that receives this call (one referencing a transaction that does not exist).
As per best practice with EF the aspnet stack contructs a new scoped instance of the context and gives it to my controller which runs the logic above.

So that left me thinking "oh ok, it must not like that I have the user query and the transaction queries happening to return the same B2BUserRole instances or something".

so I wrapped the user call in ...

```cs
ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
...
ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.TrackAll;
```

... and got the same result.
So the only conclusion I could draw was "oh ok maybe the user is in 2 roles that happened to be attached to this transaction query", and I was right.
So I can't pull related rows even if I don't edit them and apply a change to something related to them then call save changes.

That left me baffled, how do I solve this?

**Comment by TehWardy** [comment]
So I found the issue just inside the foreach loop where i loop through the batches I was doing this ...

    var references = updates.Select(u => u.Reference).ToArray();

... confusingly though, although this is pulling more out of the DB than intended I don't understand why this would cause the exception shown.


The line of code correction should be ...

    var references = subBatch.Select(u => u.Reference).ToArray()

**Comment by TehWardy** [comment]
Ok now i'm even more confused ...

It's like EF won't allow an entity instance to appear twice from the same query result, I altered the code like this ...

```cs
public async Task<IEnumerable<DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>>> UpdateStatusForBatch(IEnumerable<TransactionStatusUpdate> updates)
{
    if (updates != null && updates.Count() > 0)
    {
        var results = new List<DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>>();

        foreach (var subBatch in updates.BatchesOf(1000))
        {
            foreach(var bi in subBatch)
            {
                using var ctx = Db.NewInstance() as IB2BDataContext;
                var transactions = ctx.GetAll<T>(true)
                    .Include(i => i.AuditTrail)
                    .Include(i => i.References)
                    .Include(i => i.Buckets)
                        .ThenInclude(b => b.Bucket)
                            .ThenInclude(b => b.Roles)
                                .ThenInclude(br => br.Role)
                                    .ThenInclude(r => r.Users)
                    .Where(i => i.References.Any(r => bi.Reference == r.Id))
                    .ToArray();

                try
                {
                    var result = UpdateStatusFor(bi, transactions);
                    await ctx.SaveChangesAsync();
                    results.Add(result);
                            
                    log.Debug($"Status updated for {typeof(T).Name}:\n{result.ToJson(ObjectExtensions.JSONSettings, Newtonsoft.Json.Formatting.Indented)}");
                }
                catch (Exception ex)
                {
                    var result = new DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>
                    {
                        Item = bi,
                        Success = false,
                        Message = ex.Message,
                        Details = new[] { transactions.FirstOrDefault(t => t.References.Any(r => r.Id == bi.Reference))?.Audit(Objects.AuditItemLevel.Error, User, ex.Message) }
                    };

                    await ctx.SaveChangesAsync();
                    results.Add(result);
                    log.Debug($"Failed to update status for {typeof(T).Name}:\n{result.ToJson(ObjectExtensions.JSONSettings, Newtonsoft.Json.Formatting.Indented)}");
                }
            }
        }

        return results;
    }
    else
        return new List<DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>>>();
}
```

I'm doing 1 get call per context instance here, and the user i'm using for permission checks is from the request scoped instance context so that's literally the only data i pull from the db from a single call of ...

```cs
            var transactions = ctx.GetAll<T>(true)
                .Where(i => i.References.Any(r => references.Contains(r.Id)))
                .Include(i => i.AuditTrail)
                .Include(i => i.References)
                .Include(i => i.Buckets)
                    .ThenInclude(b => b.Bucket)
                        .ThenInclude(b => b.Roles)
                            .ThenInclude(br => br.Role)
                                .ThenInclude(r => r.Users)
                .ToArray();
```

The change applied is then in this method on the transaction entity ...

```cs
[PrivilegePerspective(Perspective.Debtor)]
public virtual IEnumerable<TAuditItem> Hold(B2BUser user, string externalState)
{
    var result = new List<TAuditItem>();

    if (user.Can(GetType().Name.ToLower() + "_debtorhold", this as IAmBucketManaged))
    {
        result.Add(ApplyStateChange(TransactionState.Held, Perspective.Debtor, user));
        DebtorExternalState = externalState ?? "Held";
    }

    if (result.Count == 0)
        throw new SecurityException("Access Denied!");

    return result;
}
```

... the code i have left out for berevity is literally just mapping the update info to this call by doing ...

```cs
var transaction = transactions.FirstOrDefault(t => t.References.Any(r => r.Id == update.Reference));
var result = update.NewState switch
                {
                    (int)TransactionState.Hold=> new DetailedResult<TransactionStatusUpdate, IEnumerable<TAuditItem>> { Item = update, Success = true, Details = transaction.Hold(User, update.ExternalStateString) },
                   ...
               }
```

"User" is coming from Db.User (as described above.

**Comment by TehWardy** [comment]
For berevity, to increase visibility of the problem, the extracted "work" now being done on a single DbContext looks something like this for each update ...

```cs
foreach(var update in updates)
{
	using var ctx = Db.NewInstance() as IB2BDataContext;
	var transactions = ctx.GetAll<T>(true)
		.Where(i => i.References.Any(r => references.Contains(r.Id)))
		.Include(i => i.AuditTrail)
		.Include(i => i.References)
		.Include(i => i.Buckets)
			.ThenInclude(b => b.Bucket)
				.ThenInclude(b => b.Roles)
					.ThenInclude(br => br.Role)
						.ThenInclude(r => r.Users)
		.ToArray();
		
	var transaction = transactions.FirstOrDefault(t => t.References.Any(r => r.Id == update.Reference));
	transaction.DebtorState = "New State";
	await ctx.SaveChangesAsync();
}
```
I'm completely lost as to why this should trigger any sort of issue at all with UserRoles, the last "ThenInclude" call is purely included for the permissions check which I now do another context instance (variable named Db in the original code block).

**Comment by ajcvickers** [comment]
@TehWardy Thanks for posting. There is a lot here to read--we will get to it when we can.

**Comment by TehWardy** [comment]
thx @ajcvickers  ... Bit of an update ...

I discussed this problem with the team, and the key things that came out were, pull the query ...

```
// this "false" adds .AsNoTracking() to the Set<T>() that GetAll<>(T) wraps
var user = GetAll<B2BUser>(false) 
                        .Include(u => u.Roles)
                            .ThenInclude(ur => ur.Role)
                        .FirstOrDefault(u => u.Id == userName)
```
So straight up, EF should not care about the results of that query any more.
Then we hit the transaction query ....

So I refactored the logic a bit here allowing me to reduce the query to this:

```
	var transactions = Db.GetAll<T>(true)
		.Where(i => i.References.Any(r => references.Contains(r.Id)))
		.Include(i => i.AuditTrail)
		.Include(i => i.References)
		.Include(i => i.Buckets)
			.ThenInclude(b => b.Bucket)
				.ThenInclude(b => b.Roles)
					.ThenInclude(br => br.Role)
		.ToArray();
```

Having done that I ran the same update logic which is something like ...

```
transactions.ForEach(t => t.Hold(User));
await saveChangesAsync();
```
There's a bit more to "figuring out" the status updates (which I partially touched on above) but that's all DTO work that doesn't touch EF ... the net result is that on each transaction I do a call with an internal priv check which is something like:

```
public virtual IEnumerable<TAuditItem> Hold(B2BUser user, string externalState)
{
   if(t.Buckets.All(b => b.Roles.Any(br =>br.Role.HasPriv("foo") && br.Role.HasUser(User))))
       ApplyChanges(TransactionState.Held);
}
```
... i'm deliberately reducing the code down at this point to further clarify the EF interactions so that if clause is basically what user.Can() does from the previous code samples. I built Methods on each level of the chain so for example Roles have a Method called Allows which checks if a given user has a given priv keeping all the role logic inside the role Entity.

All of this stuff is ultimately just simple "is this joined to that" which is why i pull so many tables for the transactions I need to update.

So I refactored the user.Can() "question" to something like ...

```
t.Buckets.All(b => b.Roles.Any(br => user.Roles.Any(ur => br.RoleId == ur.RoleId) && ur.Role.HasPriv("foo")));
```

This meant that I could reduce the previous query for getting the transactions down to the one at the start of this comment (not requiring me to pull the rows from the table "B2BUserRoles" that were linked through the chain to the individual transactions) which was ultimately the cause of my initial headache.

The transaction status changing method would ask the security question and if the result was true change a string property value on the transaction and add an AuditTrail Item, so Hold() would ultimately just do something like this after the priv check ...

```
this.DebtorState = "Held";
this.AuditTrail.Add(new AuditTrailItem() { ... });
```

... then save changes would be called (initially for a whole batch, but as I hit issues I tried refactoring for each item).

I'm now getting the exception - 

> Violation of PRIMARY KEY constraint 'PK_Roles'. Cannot insert duplicate key in object 'Security.Roles'. The duplicate key value is (b22055fe-67db-41e7-2310-08d7740618e4).
> The statement has been terminated.

Which seems odd since I did get the Role and I did read some information on it, but I didn't update it nor have I added anyhting to any role collections that would trigger an insert.

I'm now convinced that there's something about either how the ChangeTracker works / my usage of it that's causing it / me confusion.

Hopefully i'll hear from you guys soon, sorry about the information overload in this post but I often get tickets shut down for not providing enough information so i'm trying to be as thorough as possible this time.

**Comment by TehWardy** [comment]
Ok I figured out where the Role add is coming from, finally!!!
I think this is all down to a complex set of conditions in my code that resulted in an untracked entity being attached to a new one thus it did exactly what it was designed to do and tried to insert the entire entity tree in to the db again.

I'm still doing cleanup and confirming that this is the cause but for now at least I'm confident that it's not in fact a bug in EF Core.

I will confirm then close soon hopefully.

**Comment by TehWardy** [comment]
Yup that's the culprit ... one line of code out of place ... typical huh!
