### ISSUE TITLE
Document behavior when cancellation is signaled

### ISSUE THREAD

**Issue by sbrockway** [dotnet/efcore#19151]
My assumption, when passing a cancellation token to .ToListAsync() or other similar APIs, is that the method will throw OperationCanceledException() if cancellation is signalled during the operation. If this is accurate, could the documentation be updated to describe this?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.tolistasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync%60%601);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-3.0

**Comment by ajcvickers** [comment]
@roji Can you find an example of the boilerplate from the BCL that you were mentioning?

**Comment by roji** [comment]
I did a quick test and ToListAsync throws [TaskCanceledException](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception?view=netframework-4.8), which extends OperationCanceledException and is the right behavior (IIRC).

For the exception message, found several in the BCL, I guess we can take our pick:

* [System.Collections.Concurrent/BlockingCollection`1.xml](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.add?view=netframework-4.8#System_Collections_Concurrent_BlockingCollection_1_Add__0_System_Threading_CancellationToken_): If the CancellationToken is canceled.
* [System.Linq.ParallelEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.linq.parallelenumerable.aggregate?view=netframework-4.8#System_Linq_ParallelEnumerable_Aggregate__3_System_Linq_ParallelQuery___0__System_Func___1__System_Func___1___0___1__System_Func___1___1___1__System_Func___1___2__): The query was canceled with the token passed in through WithCancellation.

There are others. The first one seems sufficient to me...
