### ISSUE TITLE
Question: How to implement CreateValueBufferFactory in QuerySqlGenerator in Core 3.0

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#19169]
Hi,

We are working to support Core 3.0 for IBM Entityframework Core provider.
For DB2 database we need to get hold of datareader and some property in case of boolean.

Version 2.2 prior releases we had overridden method CreateValueBufferFactory(..) in Db2QuerySqlGenerator class. But we do see as part of Core 3.0 this doesn't exist anymore.

My Question is - how do we inject CreateValueBufferFactory code in Core 3.0 for select query ? What is the replacement of it ?

**Comment by ajcvickers** [comment]
@archanasoni The query code was extensively re-written for EF Core 3.0. Many of the lower-level classes have changed. Updating a provider for 3.0 is unfortunately a significant amount of work. Consider looking at the work done for [Npgsql](https://github.com/npgsql/efcore.pg) and [Pomelo MySQL](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) as well as the changes made here to the SQLite and SQL Server providers as guidance on how to update. Also, the list of [breaking changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes) will likely be useful.

**Comment by archanasoni** [comment]
@ajcvickers , I had looked SQLServer design and breaking changes. DB2 provider quires Datareader, Parameter value and RowNumberPaging..
Without these many scenario will fail.

Now my simple question is how can we get DataReader object in select flow. Earlier using CreateValueBufferFactory(..) we were able to achieve it.

Similarly for ParameterValues ?

And Please don't be in so much hurry to Close this case!!!!
