### ISSUE TITLE
hierarchyid sql server type not supported with ef core

### ISSUE THREAD

**Issue by nfgodfather** [dotnet/efcore#19163]
I've seen a couple of microsoft blog posts that mention hierarchyid is not supported in ef core, but I have yet to find a way to make it work. EF Core doesn't seem to be able to convert to CLR type mapping. Here is the article that mentions it being supported: https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/

**Comment by smitpatel** [comment]
The article mention it is being supported in EF 6.3. This is EF Core and hierarchyid is still not supported. See #365
