### ISSUE TITLE
Change default localdb mdf file

### ISSUE THREAD

**Issue by lucasNewSharp** [dotnet/efcore#19165]
I can't change localdb default mdf file location. I want put mdf file inside App_Data folder, but it's created on C:\user folder it's a bug?

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by lucasNewhsarp** [comment]
My bad
