### ISSUE TITLE
Columns with default values in seed data are always different

### ISSUE THREAD

**Issue by lakeman** [dotnet/efcore#19167]
I'm using ```DateTimeOffset``` values as concurrency columns in practically all tables. Rather than using a trigger, values are updated by the ```DbContext``` before saving, so that I can supply the end users actual timezone. So that the column can be ignored when inserting via sql, a default value has been specified.

A few tables have some seed data, where I've supplied a constant value based on the date the data was authored.

This was working fine in ef core 3.0. Upgrading to 3.1, this seed data is always updated pointlessly in every migration.

```c#
    entity.HasData(
        new LookupType { Type = nameof(Comment), Description = "Comment Types", Modified = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc), ModifiedBy = "Upgrade"},
    );
    //....
    migrationBuilder.UpdateData(
        table: "lookup_type",
        keyColumn: "type",
        keyValue: "Comment",
        columns: new[] { "modified", "modified_by" },
        values: new object[] { new DateTimeOffset(new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "Upgrade" });
```

The ModifiedBy column also has a default value, which seems to be the cause of the problem.

**Comment by ajcvickers** [comment]
@lakeman I am not able to reproduce this--see my code below. Can post a small project/solution or update my code listing to reproduce the behavior you are seeing.

```C#
public class LookupType
{
    public string Type { get; set; }
    public string Description { get; set; }
    public DateTimeOffset Modified { get; set; }
    public string ModifiedBy { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LookupType>().HasKey(e => e.Type);
        modelBuilder.Entity<LookupType>().HasData(
            new LookupType 
                { 
                    Type = "Comment", 
                    Description = "Comment Types",
                    Modified = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc), 
                    ModifiedBy = "Upgrade"
                }
        );
    }
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}
```

**Comment by lakeman** [comment]
Hmmm, my original suspicion about the cause seems to be wrong. Attempting to step through ```MigrationsModelDiffer.DiffData()```, the original values of these two properties are never set because ```targetProperty.ValueGenerated == ValueGenerated.OnAdd``` [line 1800](https://github.com/aspnet/EntityFrameworkCore/blob/4b42c7aee3eb90ec929acf72af94f358bfb065dd/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L1800)

**Comment by lakeman** [comment]
I'm guessing that line should read ```targetProperty.GetBeforeSaveBehavior() != PropertySaveBehavior.Save```?

**Comment by ajcvickers** [comment]
@lakeman Looks like you may be hitting #18943. If not, we will need repro code.

**Comment by lakeman** [comment]
Looks like they have the same cause.
