### ISSUE TITLE
Query: null semantics not applied in a negated comparison.

### ISSUE THREAD

**Issue by ixtreon** [dotnet/efcore#19179]
A negated comparison between a nullable DateTime and a (non-null) DateTime behaves differently when executed in-memory vs. against SQL Server or Sqlite. With relational null semantics set to off, my expectation would be for these to behave in the same way, as suggested by the documentation.

### Steps to reproduce
Given the following model:

```C#
public class Conversation
{
    public int Id { get; set; }
    public DateTime? DateLastSeen { get; set; }
}
```

the following query:
```C#
var someDate = new DateTime(2000, 1, 1);
var ans = db.Set<Conversation>()
        .Where(x => !(x.DateLastSeen > someDate))
        .ToList();
```

produces the following SQL output:
```SQL
-- SQL Server
SELECT [m].[Id], [m].[DateLastSeen]
FROM [Conversations] AS [m]
WHERE [m].[DateLastSeen] <= @__someDate_0

-- SQLite
SELECT "m"."Id", "m"."DateLastSeen"
FROM "Conversations" AS "m"
WHERE "m"."DateLastSeen" <= @__someDate_0
```

This is consistent with SQL semantics where, for any X, both `NULL > X` and `NOT (NULL > X)`evaluate to null/false, but differs from C# semantics where `null < X` is false and `!(null < X)` is true:

```C#
> !(null > DateTime.Now)
true
> var list = new DateTime?[] { null, DateTime.Now };
> var someDate = DateTime.Now.AddMinutes(5);  // larger than any element of `list`
> list.Where(x => !(x > someDate)).ToList()
List<Nullable<DateTime>>(2) { null, [05/12/2019 16:21:23] }
```

Seems to occur both with the default options and when explicitly specifying `SqliteDbContextOptionsBuilder.UseRelationalNulls(false)`. 

### Further technical details

EF Core version: 3.1.0-preview3.19554.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.Data.Sqlite
Target framework: net461
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by maumar** [comment]
related to #9544

**Comment by maumar** [comment]
another issue here is that we were applying optimization:

!op(a, b) -> negated_op(a, b) (e.g. !(a >b) -> (a <= b), where a and/or b are nullable. We should only be applying this for non-nullable arguments

**Comment by maumar** [comment]
incorrectly optimizing negated non-nullable binary expressions has been fixed in https://github.com/dotnet/efcore/commit/a5f3e26d3bac6ddf16bf87d1010fb27ed681d071

The other part is tracked by #9544 - closing
