### ISSUE TITLE
IDbQueryCache for ef core 3.1

### ISSUE THREAD

**Issue by AdamWorley** [dotnet/efcore#19173]
I'm trying to upgrade to ef core 3.1 in one of my projects but as a result I am getting an error as IDbQueryCache is missing.

Has this been moved into an extension package or is there an alternative that can be used?

**Comment by ajcvickers** [comment]
@AdamWorley DbQuery has been removed in EF Core 3. Query types are now just entity types that have no key defined. So the "replacement" for IDbQueryCache is IDbSetCache. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#qt

**Comment by AdamWorley** [comment]
@ajcvickers Great, thanks for the update
