### ISSUE TITLE
Composable unit of work

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#1918]
In the scenario where multiple context instances are used with potentially different transactions that should be committed only if all the individual SaveChanges succeed.
While it is possible to do this manually (see #744) we could provide a nicer experience with an abstraction that would track all the contexts and do the appropriate calls when the underlying transactions succeed or fail.

**Comment by ajcvickers** [comment]
After further thought, the complexity of doing this, especially in a database agnostic way, is very high. Therefore, for now, we are closing this as something we don't intend to work on. However, we would of course reconsider this based on sufficient and compelling feedback.
