### ISSUE TITLE
how to add dependent entity when in ef core 3.0?

### ISSUE THREAD

**Issue by Grart** [dotnet/efcore#19199]
get a principal entity , clear old dependent entity then add new dependent entity,
in ef 2.0 Run SQL is Delete and Insert
but same code in ef 3.0 Run SQL is  Update

``` C#

	public class Blog
	{
		[Key]
		public Guid? Id { get; set; }
		public virtual List<Post> Posts { get; set; }
	}

	public class Post
	{
		[Key]
		public Guid Id { get; set; }
		public Guid? BlogId { get; set; }

		public Blog Blog { get; set; }
	}
	public class MSSQLContext : DbContext
	{
		public MSSQLContext(
				DbContextOptions<MSSQLContext> options
			)
			: base(options)
		{ }


		public DbSet<Blog> Blogs { get; set; }

	}


	{
		var dbCtx = context.RequestServices.GetService<MSSQLContext>();


		var _cust = dbCtx.Blogs.Include(m => m.Posts).First();
		_cust.Posts.Clear();
		for (int _i = 0; _i < 3; _i++)
		{
			_cust.Posts.Add(
				new Post()
				{
					Id = Guid.NewGuid()
				});
		}

		dbCtx.SaveChanges();
	}
```

``` C#

exec sp_executesql N'SET NOCOUNT ON;
UPDATE [Post] SET [BlogId] = @p0
WHERE [Id] = @p1;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p2
WHERE [Id] = @p3;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p4
WHERE [Id] = @p5;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p6
WHERE [Id] = @p7;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p8
WHERE [Id] = @p9;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p10
WHERE [Id] = @p11;
SELECT @@ROWCOUNT;

',N'@p1 uniqueidentifier,@p0 uniqueidentifier,@p3 uniqueidentifier,@p2 uniqueidentifier,@p5 uniqueidentifier,@p4 uniqueidentifier,@p7 uniqueidentifier,@p6 uniqueidentifier,@p9 uniqueidentifier,@p8 uniqueidentifier,@p11 uniqueidentifier,@p10 uniqueidentifier',@p1='36FFD837-23E4-4806-965B-105C4BF28EB9',@p0='EC575871-7E53-466D-8C71-187707FFC0C6',@p3='3FFA7777-13AE-4BD0-9BFC-726E0277431D',@p2='EC575871-7E53-466D-8C71-187707FFC0C6',@p5='808E863C-4E4B-4A76-A843-A2F95D3F6318',@p4=NULL,@p7='8A725DAF-C0FB-48BD-B54C-F7474DD16245',@p6=NULL,@p9='9B660C74-88FA-44A0-97D5-90C55B053CF8',@p8='EC575871-7E53-466D-8C71-187707FFC0C6',@p11='B37E64F7-5E12-42B2-9C48-E82AA40E8D4A',@p10=NULL

```

EF Core version:3.1.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:win10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@Grart We made a [change in 3.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dc) such that when detecting changes to graphs where the entities use generated keys we use the primary key value to determine whether or not the entity is new or already existing. GUID PKs are generated by default, but in this case the values are being explicitly set.

To get back to the 2.2 behavior configure the property as not generated. For example:
```
[DatabaseGenerated(DatabaseGeneratedOption.None)]
public Guid Id { get; set; }
```

**Comment by Grart** [comment]
configure the property as not generated
Run SQL is Update and Insert

`
exec sp_executesql N'SET NOCOUNT ON;
UPDATE [Post] SET [BlogId] = @p0
WHERE [Id] = @p1;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p2
WHERE [Id] = @p3;
SELECT @@ROWCOUNT;

UPDATE [Post] SET [BlogId] = @p4
WHERE [Id] = @p5;
SELECT @@ROWCOUNT;

INSERT INTO [Post] ([Id], [BlogId])
VALUES (@p6, @p7),
(@p8, @p9),
(@p10, @p11);
',N'@p1 uniqueidentifier,@p0 uniqueidentifier,@p3 uniqueidentifier,@p2 uniqueidentifier,@p5 uniqueidentifier,@p4 uniqueidentifier,@p6 uniqueidentifier,@p7 uniqueidentifier,@p8 uniqueidentifier,@p9 uniqueidentifier,@p10 uniqueidentifier,@p11 uniqueidentifier',@p1='716D7F8B-76D6-438E-942B-30AB2AD10059',@p0=NULL,@p3='B933ECAF-6385-4083-9036-D489D2E87DDF',@p2=NULL,@p5='EF589D52-9DB3-4800-973C-A9CE6F358044',@p4=NULL,@p6='46872576-3DCB-4335-8A4C-6BD75BB73030',@p7='4ACDE59E-3707-492A-AA15-785F213A4581',@p8='E0D7E71E-4771-4C7D-BBFC-B24A12189E0A',@p9='4ACDE59E-3707-492A-AA15-785F213A4581',@p10='7E4B153B-45EB-446D-AA53-78A0EC40D937',@p11='4ACDE59E-3707-492A-AA15-785F213A4581'
`

how to configure 
SQL to run  Delete and Insert  ?

**Comment by Grart** [comment]
I  find,thank you

https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api#required-and-optional-relationships

https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api#required-and-optional-relationships
