### ISSUE TITLE
X and Y Switched in WKT/ToString (and everywhere I suspect)

### ISSUE THREAD

**Issue by endintiers** [dotnet/efcore#19200]
X and Y switched when reading Geometry from SQL DB.
POINT (1 2) becomes POINT (2 1).

### Steps to reproduce
1) In local SQL Server create a table:
CREATE TABLE [dbo].[TestGeometry](
[Id] [int] NOT NULL,
[Geo] [geometry] NULL,
CONSTRAINT [PK_TestGeometry] PRIMARY KEY CLUSTERED
( [Id] ASC )ON [PRIMARY] ) ON [PRIMARY]
GO
INSERT INTO [dbo].[TestGeometry] (Id, Geo)
Values (1, geometry::STGeomFromText('POINT (1 2)', 0));
GO
SELECT [Geo].ToString() as Geo FROM [dbo].[TestGeometry]

The result is POINT (1 2) - correct.

2) Run the attached code.

The result is POINT (2 1) - incorrect.

[WildMouse.Unearth.GeoBugConsole.zip](https://github.com/aspnet/EntityFrameworkCore/files/3930428/WildMouse.Unearth.GeoBugConsole.zip)

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Additional help from: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.9

**Comment by ajcvickers** [comment]
Note for triage: there appears to be a difference in SQL Server here when using `geometry` as opposed to `geography`. The code above results in `POINT (2 1)` but if I change the column type to `geography` and use `geography::STGeomFromText`, then the result is `POINT(1 2)`.

/cc @bricelam

**Comment by bricelam** [comment]
By design. You need to configure the column type to use `geometry`.
```csharp
[Column(TypeName = "geometry")]
public Geometry Geo { get; set; }
```
or
```csharp
modelBuilder.Entity<TestGeometry>()
    .Property(g => g.Geo)
        .HasColumnType("geometry");
```
The flipping is caused by differences in how SQL Server interprets the binary format between geometry and geography.

**Comment by endintiers** [comment]
Thanks, I can see now how to get the correct interpretation of any SQL Server field.
One confusing thing is that it shows that a NetTopologySuite Geometry (Point etc.) is by default interpreted as representing a SQL Server geography (it defaults that way if you don't specify the typename).
But the moral is: always specify the TypeName, which is good documentation anyway...
