### ISSUE TITLE
Overriding CustomerQueries in tests

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19208]
What would be the best/easiest way to override [this string](https://github.com/aspnet/EntityFrameworkCore/blob/master/test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs#L32) in my tests?

**Comment by ajcvickers** [comment]
@cincuranet Like this: https://github.com/npgsql/efcore.pg/blob/b11080d5d4276612d1c19a84405b4280cb2ce1ba/test/EFCore.PG.FunctionalTests/TestModels/Northwind/NorthwindNpgsqlContext.cs
