### ISSUE TITLE
Null semantics and custom function expression

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19219]
When I create custom expression for some function and _not_ derive it from `SqlFunctionExpression`, the `NullSemanticsRewritingExpressionVisitor` then does not handle the null semantics properly.

I can derive from `SqlFunctionExpression` and completely ignore the structure provided (because the function I'm doing has different "formatting") and live with that. But seems wrong. What also seems weird is creating custom `NullSemanticsRewritingExpressionVisitor`. Is there any expected path provider writers should take?

**Comment by ajcvickers** [comment]
@smitpatel or @roji to follow up.

**Comment by roji** [comment]
@cincuranet can you give us some background on why you need to create a custom expression for a function instead of using `SqlFunctionExpression`? This is to make us understand any shortcomings it has etc.

Regardless, there's work underway to allow providers to extend `NullSemanticsRewritingExpressionVisitor` to handle custom expressions, so that should help.

**Comment by cincuranet** [comment]
The `SqlFunctionExpression` has a of properties that my expression does not need, so as I said, I can completely ignore these and derive from it just for the sake of `NullSemanticsRewritingExpressionVisitor`. Or I can try to (ab)use some of the properties. Neither is particularly nice.

Extending `NullSemanticsRewritingExpressionVisitor` would do, yet just for the null semantics simple marker interface would do (instead of relying on `SqlFunctionExpression`) and no overrides etc. would be needed.

**Comment by roji** [comment]
I'm trying to ask why derive at all - what exactly is preventing you from using SqlFunctionExpression and driving you to want to create your own custom expression type? Which properties don't you need? Can you provide some details on your concrete scenario?

**Comment by cincuranet** [comment]
Because not everything in SQL is plain `FUNCTION(param, param, param)`. Take a look at [EXTRACT](https://firebirdsql.org/refdocs/langrefupd20-extract.html). I have to handle the SQL generation to accommodate for - in this case - `FROM` piece.

**Comment by ajcvickers** [comment]
@smitpatel to take a look.

**Comment by smitpatel** [comment]
Custom expression and deriving NullSemantics is right thing.

@cincuranet - There is no way to define an interface for null semantics since we need to pass nullability information for each component and get modified tree and nullability information of result node back. So overriding the visitor is the way to go.

**Comment by cincuranet** [comment]
OK, thanks. For now I'll keep abusing `SqlFunctionExpression`, but I'll keep this in my head for the future improvements.

**Comment by cincuranet** [comment]
Just checking, did anything changed for custom expressions for functions in 6.0? Before I go into rabbit hole of handling this (at the moment facing problems with the mentioned EXTRACT function). Thanks.

**Comment by roji** [comment]
@cincuranet I don't think anything important change for custom expressions for functions but @smitpatel can probably confirm.

However, it may be helpful to look at what I've done in the PostgreSQL provider - see [PostgresFunctionExpression](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Query/Expressions/Internal/PostgresFunctionExpression.cs). This is used to support both named parameter syntax (`my_func(a => b, c => d)`) and non-comma separators (`position(x IN y)`, which may be very similar to your EXTRACT example).

**Comment by cincuranet** [comment]
Thanks. I was just checking.

Also the `PostgresFunctionExpression` handling was helpful to quickly finish what I needed, thanks.
