### ISSUE TITLE
RelationalConnection.DbTransaction should be an extension method

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#1922]
Filing this in case I miss the API review

**Comment by rowanmiller** [comment]
@AndriySvyryd why do you want this to be an extension method rather than instance method on the return type?

**Comment by AndriySvyryd** [comment]
RelationalConnection shouldn't be coupled to implementation details of RelationalTransaction.

Sent from my Windows Phone
________________________________

**Comment by rowanmiller** [comment]
We'll go over all this in API review
