### ISSUE TITLE
Stop preventing composition over common table expressions

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19224]
#17558 introduced a composability check in order to throw better exceptions when attempting to compose over non-select expressions. The problem is, PostgreSQL fully supports composing over common table expressions (WITH ...), even if SQL Server doesn't (see https://github.com/npgsql/efcore.pg/issues/1153).

We should probably either stop parsing SQL once and for all, or at least provide a hook for provider's to say what's composable and what isn't (if we feel the exception is valuable enough). Note also that the PostgreSQL syntax for invoking stored procedures is CALL as opposed to SQL Server's EXEC, so filtering specifically for stored procedures isn't trivial either.

We should also try to improve on cross-database awareness and testing.

**Comment by ajcvickers** [comment]
Expose a hook for providers.

**Comment by shaulbehr** [comment]
Hey there, I'm upgrading to EF Core 3.1. I've got a pretty central query that's breaking on account of this, which is written thusly to prevent race conditions on a unique index:
```
var newThing = await DbContext.Things.FromSqlInterpolated($@"
    insert into thing(thingValue, ...) 
    values ({value}, ...)
    on conflict do nothing
    returning *") .FirstOrDefaultAsync() 
?? await GetExistingThingAsync(...);
```
This used to work fine using `.FromSql()`, but now it is throwing:
```
System.InvalidOperationException : FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling `AsEnumerable` after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.
```
I'd *really* appreciate if you folks could see your way either to patching this soon, or suggesting a workaround.

**Comment by shaulbehr** [comment]
Oh, it looks like the suggested workaround in the error message actually is a workaround:
```
var newThing = DbContext.Things.FromSqlInterpolated($@"
    insert into thing(thingValue, ...) 
    values ({value}, ...)
    on conflict do nothing
    returning *").AsEnumerable().FirstOrDefault() 
?? await GetExistingThingAsync(...);
```
The bummer is that it's no longer an async call, but at least it works.

**Comment by roji** [comment]
@shaulbehr there's also [AsEnumerableAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.asasyncenumerable?view=efcore-3.1#Microsoft_EntityFrameworkCore_EntityFrameworkQueryableExtensions_AsAsyncEnumerable__1_System_Linq_IQueryable___0__) which can allow you to do this asynchronously.

**Comment by roji** [comment]
For anyone currently blocked by this, you can make this work on 3.1 by replacing your provider's implementation of QuerySqlGenerator, and overriding the implementation of VisitFromSql to omit the check. This is essentially what #21127 will permit providers to do for 5.0 in a well-factored way.
