### ISSUE TITLE
Choose where to generate database file in SQLite migration

### ISSUE THREAD

**Issue by diegosasw** [dotnet/efcore#19228]
I want to have a class library (e.g: Sasw.SimpleBlog.Storage.SQLite) targeting the netstandard2.1 with a DbContext (with `"Data Source=blog.db"`), Migrations and the SQLite database file.
This csproj has:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasw.SimpleBlog\Sasw.SimpleBlog.csproj" />
  </ItemGroup>
</Project>
```

Since this is a class library I cannot use the dotnet tools to create migrations and update database with them. So I create a netcore console application (e.g: Sasw.SimpleBlog.Storage.SQLite.Migrator) just for the purpose of creating and applying migrations
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasw.SimpleBlog.Storage.SQLite\Sasw.SimpleBlog.Storage.SQLite.csproj" />
  </ItemGroup>
</Project>
```

I can create migrations and place them under the class library as desired running the `dotnet ef` command from either project and playing with the --startup-project or --project. 
Example (e.g: from Sasw.SimpleBlog.Storage.SQLite):
```
dotnet ef migrations add InitialCreate --startup-project ../Sasw.SimpleBlog.Storage.SQLite.Migrator
``` 
would properly create the Migrations folder in the class library project.

However when I update the database the `blog.db` is generated inside the netcoreapp3.1 project, and I don't seem to be able to specify where the target database is.

```
dotnet ef database update --startup-project ../Sasw.SimpleBlog.Storage.SQLite.Migrator/
```
The blog.db is under `Sasw.SimpleBlog.Storage.SQLite.Migrator` even if I also specify a `--project` pointing to `./`

A parameter where I can choose where the SQLite database to update is located or a workaround and documentation about it.

**Comment by ErikEJ** [comment]
Use a full path in your development connection string?

**Comment by sunnyatticsoftware** [comment]
ouch! Well, I feel ashamed. It's must be Sunday. Thanks a lot, it works as expected like that.
