### ISSUE TITLE
Query: SqlServer: Functions to create datetime variations from components

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19237]
Consider DATEFROMPARTS
DATETIME2FROMPARTS
DATETIMEOFFSETFROMPARTS
SMALLDATETIMEFROMPARTS
TIMEFROMPARTS

**Comment by Marusyk** [comment]
I will try to prepare PR for this. Could you please assign it to me?

**Comment by Marusyk** [comment]
Done. The issue can be closed

**Comment by smitpatel** [comment]
Fixed in #19400
