### ISSUE TITLE
Question: How to implement CreateValueBufferFactory in QuerySqlGenerator in Core 3.0

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#19243]
**Already had opened case #19169  Please don't be in so much hurry to close it it's painful to open issue for each reply **

I had looked SQLServer design and breaking changes. DB2 provider requires Datareader, Parameter value and RowNumberPaging..
Without these many scenario will fail.

Now my simple question is how can we get DataReader object in select flow. Earlier using CreateValueBufferFactory(..) we were able to achieve it.

Similarly for ParameterValues ?

**Comment by smitpatel** [comment]
You don't create ValueBuffers from database values in EF Core 3.0

**Comment by smitpatel** [comment]
I would totally blame this on one of the customer to present it to me recently. Please refer to [XY problem](https://en.wikipedia.org/wiki/XY_problem).

EF Core 3.x query pipeline stopped using ValueBuffers altogether. Hence there is no way to implement CreateValueBufferFactory. In order for us to help you out, you need to describe what actual issue you are trying to solve. A lot of functionality in previous query pipeline has been reworked to implement it differently. So for many cases, you cannot solve the problem using same solution.

For row number paging, the SqlServer version which required it went out of support hence we dropped support for it and we are not planning to add it either. You would have to implement it by yourself. I am not sure what would be the complexity of it.

**Comment by archanasoni** [comment]
Actually for boolean type we have to edit one of property in DB2DataReader class.. Earlier via ValueBuffer we were able to get hold of DataReader and editing overrideReturnTypes=True
Now since ValueBuffer is removed, somehow we need to get hold of DataReader object otherwise our many scenario will fail..

for example: context.TestTabs.All(i => i.ID > 1)

sample Code which we may need to be injected:
 if (colTypes.Contains<Type>(Type.GetType("System.Boolean")) || colTypes.Contains<Type>(Type.GetType("System.Nullable`1[System.Boolean]")))
             {
                int colNum = 0;

                foreach (Type colType in colTypes)
                {

                    if (colType.FullName.Contains("System.Boolean"))
                    //if (colType.FullName.ToString() == "System.Boolean")
                    {

                        if (_overrideColumnReturnTypes == null)
                        {
                            _overrideColumnReturnTypes = new Dictionary<int, TypeCode>();
                        }
                        _overrideColumnReturnTypes.Add(colNum, TypeCode.Boolean);

                    }                  
                    colNum++;
                }

                ((DB2DataReader)dataReader).OverrideColumnReturnTypes= _overrideColumnReturnTypes;               

            }

**Comment by ajcvickers** [comment]
@archanasoni This should be handled by type mappings. That is, the properties should get different type mappings depending on whether they are conceptually boolean or not. The type mapping then has a mechanism to use a custom data reader expression as needed.

I suspect attempting to pre-modify the data reader in the way you show won't be successful without making extensive hacks to the internals, which is something providers should avoid.

**Comment by archanasoni** [comment]
@ajcvickers  DB2 handles boolean in different way, and is not that straight forward. 
for example, when valuebuffer can have boolean type we need to update OverrideColumnReturnTypes property of Db2Datareader. Basically for query using All method(context.TestTabs.All(i => i.ID > 1)),  EF expects result as boolean but DB2 doesn't support it fully so to make it work we have to update property.

Type mapper wouldn't help here...

**Comment by ajcvickers** [comment]
@archanasoni Maybe it's just the case that DB2 is too different from other relational providers to make it a candidate to use the relational provider infrastructure. In this case, I suggest you abandon using the relational provider infrastructure and use your own implementation. This will free you from the constraints in the way EF using ADO.NET.

**Comment by archanasoni** [comment]
Thanks @ajcvickers , will close the issue as Vacation time :)
Once I'm back will open it if needed..
