### ISSUE TITLE
Want PrimaryKey be TKey rather than Int in  IdentityUserClaim class.

### ISSUE THREAD

**Issue by ogswr** [dotnet/efcore#19240]
I want to handle more than 32bit records in AspNetUserClaims table.

Hiding doesn't work acording to #12565
` public class CustomIdentityUserClaim : IdentityUserClaim<string>
  {
    public new string Id { get; set; }
  }`

so, I want you to change base class (IdentityUserClaim<TKey>) property type
public virtual int Id { get; set; } =>     public virtual Tkey Id { get; set; }

**Comment by ajcvickers** [comment]
@ogswr This is [documented](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1). If you need more than what is covered by that documentation, then please file an issue on the [ASP.NET repo](https://github.com/aspnet/AspNetCore) which is where Identity is maintained.

**Comment by ogswr** [comment]
got it. thanks.

**Comment by kolpav** [comment]
@ajcvickers Even after reading all the issues and linked documentation I am still unable to change `Id` type of `IdentityUserClaim` can you point me in right direction?

By looking at the `IdentityUserClaim` implementation I see the you can provide type for `UserId` but not for `Id`.
```c#
  public class IdentityUserClaim<TKey> where TKey : IEquatable<TKey>
  {
    public IdentityUserClaim();

    //
    // Summary:
    //     Gets or sets the identifier for this user claim.
    public virtual int Id { get; set; }
    //
    // Summary:
    //     Gets or sets the primary key of the user associated with this claim.
    public virtual TKey UserId { get; set; }
```

but in `IdentityUser` you can provide type for `Id`

```c#
  public class IdentityUser<TKey> where TKey : IEquatable<TKey>
  {
    ...
    public virtual TKey Id { get; set; }
    ...
}
```

I expect you to advise me to open new issue but please consider that most people googling this problem will end up here after clicking through multiple issues as I did.

**Comment by ajcvickers** [comment]
@kolpav The identity model does not allow this key type to be changed. You could request this be changed by filing an issue at [ASP.NET Core](https://github.com/dotnet/aspnetcore), but it's been like this for a long time and I don't think there are plans to change it.

**Comment by kolpav** [comment]
@ajcvickers Interesting do you know why is that? I can imagine that at first the keys were written as hardcoded types then later were all replaced with generics except IdentityUser PK isn't it weird?
