### ISSUE TITLE
Query with Where (Enum = 1) Could not be Translated?

### ISSUE THREAD

**Issue by abbotware** [dotnet/efcore#19272]
I understand some changes happened in EF core 2 -> 3
(https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client)

have a trival simple where expression that used to work:

`Where(x => x.EntityType == EntityTypeId.Basic)`

    System.InvalidOperationException : The LINQ expression 'DbSet<Entity>
        .Where(e => (int)e.EntityTypeId == 1)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Should the above query continue to work?  Or is all server side functionality (ie like paging) been dropped for client side evaluation only?

### Steps to reproduce

I am doing expression mapping (automapper) to convert expression from one a viewmodel into a datamodel.. so there is a bit of magic happening... from the expression exception though, I can see the the expression was translated correctly as `ViewModel.EntityType` is correctly being mapped to `EntityModel.EntityTypeId`

it seems its related to the enum being marked abstract:

```C#
    public class ModelIntKey : BaseIntKey
    {
        public override SomeEnum Enum => SomeEnum.Basic;
    }

    public abstract class BaseIntKey
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public abstract SomeEnum Enum { get; }
    }
```

I am using it as a type discriminator for a class heirarchy

if I change the above to this:

```C#
   public class ModelIntKey : BaseIntKey
    {
        public override SomeEnum Enum { get; set; } = SomeEnum.Basic;
    }

    public abstract class BaseIntKey
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public abstract SomeEnum Enum { get; set; }
    }
```

It works... so perhaps it is the 'get only property' that is the cause?

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (NET Core 3.1)
Operating system: Windows 10 
IDE: (e.g. Visual Studio 2019 16.4)

**Comment by ajcvickers** [comment]
@abbotware This:
```C#
 public virtual SomeEnum Enum { get; }
```
is a read-only property which means that EF won't map it to a database column by default. This was also true in EF Core 2.2. This is what causes client-side evaluation.

```C#
public virtual SomeEnum Enum { get; set; }
```
will be mapped and the value will be obtained from the database.

**Comment by abbotware** [comment]
ah - make sense - so It was client side all along (whoops!)
