### ISSUE TITLE
EF Core 3.1.0 Nuget contains duplicated entries case Nuget.Server fail to indexing

### ISSUE THREAD

**Issue by RayMMond** [dotnet/efcore#19288]
EF Core 3.1.0 nuget package from [nuget.org](https://www.nuget.org/api/v2/package/Microsoft.EntityFrameworkCore/3.1.0) contain two **packageIcon.png** file. Nuget.Server will throw key-exists-expcetion when indexing package.

### Steps to reproduce

1. Put Microsoft.EntityFrameworkCore.3.1.0.nupkg to Nuget.Server Package folder and index packages.

### Further technical details

EF Core version: 3.1.0
Database provider: None
Target framework: None
Operating system: Windows
IDE: None

**Comment by ajcvickers** [comment]
@Pilchie Is there a place where we are globally tracking the double packageIcon issue?

**Comment by Pilchie** [comment]
Generally aspnet/Extensions#2744.

**Comment by ajcvickers** [comment]
Closing as this is tracked across ASP.NET and EF by the referenced issue.

**Comment by forki** [comment]
That issue that you linked was closed.

**Comment by ajcvickers** [comment]
@forki That's because issues are generally closed once the required change has been merged, which has already happened here.

**Comment by forki** [comment]
Yeah but the problem exists and it will be spreading. It's not solved

**Comment by Pilchie** [comment]
@forki Yes, we understand that, but that doesn't mean we need to change our issue management strategy.  As @ajcvickers notes, we close issues when a fix is checked in, and put them into a milestone that represents the release they will be part of.  This is just following that policy.

**Comment by doboczyakos** [comment]
All these packages have the same error:

Microsoft.Extensions.Configuration.Abstractions 3.1.0
Microsoft.Extensions.Primitives 3.1.0
Microsoft.Extensions.Configuration 3.1.0
Microsoft.EntityFrameworkCore 3.1.0
Microsoft.EntityFrameworkCore.Abstractions 3.1.0
Microsoft.Extensions.Configuration.Binder 3.1.0
Microsoft.Extensions.Caching.Abstractions 3.1.0
Microsoft.Extensions.DependencyInjection 3.1.0
Microsoft.Extensions.Logging.Abstractions 3.1.0
Microsoft.Extensions.Caching.Memory 3.1.0
Microsoft.Extensions.DependencyInjection.Abstractions 3.1.0
Microsoft.Extensions.Logging 3.1.0

**Comment by forki** [comment]
Just FYI: https://github.com/aspnet/Extensions/issues/2744#issuecomment-564945991 all those packages can't be used with local nuget server.
