### ISSUE TITLE
EF Core Default Value Always FALSE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19286]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/850881/ef-core-default-value-always-false.html)._

---
EF Core migration WILL NOT recognize the default value of bool property, its value is ALWAYS  set to "false" in DB.

```C#
public class AlwaysFalse
{
 public bool MyTest {get; set;} = true;  
}

public partial class addBoolColumn: Migration
{
     protected override void Up(MigrationBuilder migrationBuilder)
     {
         migrationBuilder.AddColumn<bool>(
             name: "MyTest",
             table: "AlwaysFalse
             nullable: false,
             defaultValue: false);  //  expect defaultValue: true
                                              //  necessary to manually type over "false" value with "true" into proposed Migrations partial class 
     }
}
```

---
#### Visual Studio Feedback System on 12/11/2019, 02:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
EF Core does not use the default value set in the language and I don't immediately see any reasonable way of making this work. Default values documentation is here: https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-values

**Comment by br3nt** [comment]
I can see the fluent API supports `HasDefaultValue(true)`, but why no support for `[DefaultValue(true)]`??
