### ISSUE TITLE
EF Core 3.1 in UWP on ARM

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#19294]
I have a UWP app that used EF Core 2.2.6 successfully on x86, x64 and ARM.

After upgrading to EF Core 3.1, the app still runs successfully on x86 and x64 but on ARM fails with several exceptions:

The first is
Exception thrown: 'System.DllNotFoundException' in Microsoft.Data.SqlClient.dll
followed by
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in LoadingDockDisplay.exe

Is there an issue with EF Core 3.1 on ARM?

Any ideas on the cause and how to fix this?

**Comment by ajcvickers** [comment]
@GRS-Leedo From the stack trace this looks like an issue in SqlClient. You're probably want to report it to https://github.com/dotnet/SqlClient, but I expect they will need a lot more information than is provided here to be able to reproduce this.

**Comment by GRS-Leedo** [comment]
Thanks Artur.  Sometimes it is difficult to know who things like this go to.
