### ISSUE TITLE
Replacement for RelationalMetadataExtensions?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#19298]
I used to be able to-do like:

```
IEntityType entityType = ...;
foreach (IProperty propertyType in entityType.GetProperties())
{
     var relational = propertyType.Relational()
}
```
To get "IRelationalPropertyAnnotations".

This seems to have come from "RelationalMetadataExtensions" - those no longer seem to be present.

What's the replacement?

Specifically I was using it to get:
```
relational.ColumnName
relational.ColumnType

```

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Framework 4.8

**Comment by AndriySvyryd** [comment]
```C#
propertyType.SetColumnName();
propertyType.SetColumnType();
```
