### ISSUE TITLE
UseNetTopologySuite extension for InMemory database

### ISSUE THREAD

**Issue by Hameds** [dotnet/efcore#19306]
I used 'InMemory' in my unit tests and I have some spatial data. According to [docs](https://docs.microsoft.com/en-us/ef/core/modeling/spatial) there is builtin support for `UseNetTopologySuite()` extension method in `SQL Server` and `Sqlite`. There is also support for this extension method in `PostgreSQL` using [https://github.com/npgsql/efcore.pg](https://github.com/npgsql/efcore.pg) but no support for `InMemory`.

If you look at EF source code you can see `EFCore.Sqlite.NTS` and `EFCore.SqlServer.NTS` projects. It's nice to have `EFCore.InMemory.NTS` project.

**Comment by smitpatel** [comment]
Since InMemory is "in-memory" there is no need to provide translation or mapping to store type. It just works because NTS is loaded in memory already. You don't need to call anything specific. NTS works for in-memory out of the box.

**Comment by Hameds** [comment]
@smitpatel thanks for the comment. I tried to seed `InMemory` in my unit tests with a `Point` (from `NetTopologySuite.Geometries` namespace) but it didn't work. I assumed it's related to `UseNetTopologySuite()` extension method. I will check again.
