### ISSUE TITLE
Force in what sequence data seeding should occor

### ISSUE THREAD

**Issue by RCTycooner** [dotnet/efcore#19300]
### What problem are you trying to solve?
(We're doing a code first approach here) 

I have two tables A and B.
A contains a foreign key to B.

Both A and B are seeded with data using "HasData"
In the migration scripts, the table B is created first, then table A. But the seeded data is inserted the other way around (first A, then B). This causes issues when trying to run Database-Update, as the foreign key's condition is not met!

### Describe the solution you'd like
I want to be able to assign an order in which HasData-methods are executed.

### Current work around
We can manipulate the migration script and adjust the order directly there.
But since we're in an early development state, and the database isn't stable yet, we're often throwing away migrations and recreating our dev-database.

**Comment by AndriySvyryd** [comment]
Seeding should detect the foreign keys and issue the inserts in the correct order. Can you provide a small repro project that shows the issue you are experiencing?

**Comment by RCTycooner** [comment]
When creating the repro, I stumbled on an underlying issue, something was off in the data I was seeding. Which caused the aformentioned issue...

Closing this.
