### ISSUE TITLE
Possible regression from EF6 to EF Core TPH

### ISSUE THREAD

**Issue by patrickklaeren** [dotnet/efcore#19307]
Given a model where several classes derive from an abstract `Shape` class, and not all derived types are present in the context class, the discriminator is not set for the missing derived types, i.e.:

```cs
public class EntityContext : DbContext
{
    public virtual DbSet<Shape> Shapes { get; set; }
    public virtual DbSet<Circle> Cirlces { get; set; }
    public virtual DbSet<Rectangle> Rectangles { get; set; }
    public virtual DbSet<Pentagon> Pentagons { get; set; }
    // Square is not present as a DbSet
}

public abstract class Shape
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Circle : Shape { }
public class Rectangle : Shape { ]
public class Square : Shape { }
public class Pentagon : Shape { }
```

EF6 would discover the `Square` type when used as such:

```cs
db.Shapes.Add(new Square
{
     Name = Guid.NewGuid().ToString("n"),
});
```

The discriminator column in the database would be correctly populated with `Square` even when there is no `DbSet<Square>`

![image](https://user-images.githubusercontent.com/1341180/70792190-97f2f680-1d90-11ea-9616-f27854b0edf6.png)

EF Core does not discover `Square` and instead inserts `Shape` as the discriminator - leading to the record never being retrieved by EF Core again.

![image](https://user-images.githubusercontent.com/1341180/70792236-b1943e00-1d90-11ea-83f7-55d19639974c.png)

Please find below the repository to reproduce this possible regression. It is possible this is intentional, however this can lead to a hidden bug that causes EF Core to _not_ query data that seems like it is inserted with no validation issues.

### Steps to reproduce

https://github.com/Inzanit/eftphregression

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0 & .NET Core 3.1
Operating system: WIndows 10 Pro
IDE: Visual Studio 2019 16.4.1

**Comment by AndriySvyryd** [comment]
@Inzanit This is by design. In order to improve model building performance EF Core only discovers entity typed that have a corresponding DbSet, are configured in OnModelBuilding or are referenced from another discovered entity type.
