### ISSUE TITLE
Entities are not tracked after being loaded by a query involving DbQuery in a subquery

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#19308]
My Context contains this:
```C#
private DbQuery<RangeResult> RangeQuery { get; set; }
public IQueryable<RangeResult> Range(decimal? from, decimal? to) {
	return RangeQuery.FromSql($"SELECT * FROM table(num.getRange({from}, {to}))");
}
```
My mapping contains this:
```C#
modelBuilder.Query<RangeResult>().Property(t => t.ColumnValue).HasColumnName("COLUMN_VALUE");
```
I'm trying to use it in a subquery:
```C#
ctx.TestTable.Where(z => ctx.Range(1, 10).Select(r => r.ColumnValue).Sum() == z.NumVal).ToList();
```
Gets translated to:
```SQL
SELECT [Column list omitted]
FROM "TEST_TABLE" "z"
WHERE (
    SELECT SUM("r"."COLUMN_VALUE")
    FROM (
        SELECT * FROM table(num.getRange(1.0, 10.0))
    ) "r"
) = "z"."NUM_VAL"
```
The problem is that the returned entities are not tracked by the context. They don't appear in ChangeTracker.Entries and don't raise DbSet.Local.CollectionChanged.

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.Oracle
Target framework: .NET Framework 4.7
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

**Comment by ajcvickers** [comment]
@Wain123 We believe this is fixed in the 3.1 release. I realize that you will not be able to use 3.1 with an Oracle database until Oracle release a new provider. However, it is not feasible to patch 2.x for this change.
