### ISSUE TITLE
Support for useRowNumberForPaging() in Core 3.0

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#19305]
Hi,

We are working to support Core 3.0 via IBM EntityFramework Core provider.
We are aware that since SQL server EF doesn't need useRowNumberForPaging, it's removed from Core 3.0

But our issue is- DB2 needs to have support for useRowNumberForPaging.
Now my question is how can we implement support for it ? Where can we intercept it ?
With 2.2 or prior version, createDefault(...) of QuerySqlGeneratorFactory had selectExpression as argument, now how can we get hold of that with new infra ?

**Comment by smitpatel** [comment]
Add custom query post processor in your provider by deriving from https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs

Override `Process` method. The expression argument you get here is the expression tree which will be compiled to delegate. In your visitor, capture `ShapedQueryExpression`. The QueryExpression property would be a SelectExpression. Modify your SelectExpression as needed (in-place modification of SelectExpression). Don't change the value of `shapedQueryExpression.QueryExpression`.

**Comment by archanasoni** [comment]
Thanks @smitpatel , One more question is earlier we had AliasExpression and ColumnReferenceExpression, do we have replacement for them ?

Basically I'm adding new column as ROW_NUMBER() OVER() AS c here alias name I want to have control and give our own reference is it possible with Core 3.0 ?

To add predicate we had used  ColumnReferenceExpression, do we have replacement for this ?

**Comment by smitpatel** [comment]
ColumnReferenceExpression has been merged into ColumnExpression itself. Though you should never need to use it. It would be available via binding mechanism.

AliasExpression has been removed. Alias has been made part of ProjectionExpression, which is dedicated expression to store projection.

As for adding predicate, current API's are not public to make it possible. Essentially you want to do this where sqlExpression is your constructed rownumberexpression.
https://github.com/aspnet/EntityFrameworkCore/blob/f8ac8b1e88f0b608dc6f5efdf9232b78cc5dd1a3/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L686-L690

But ColumnExpression ctor is internal. So you would need to use reflection to call this ctor. https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs#L24

**Comment by archanasoni** [comment]
Thanks very much @smitpatel 
Hope fully last query :)
Similar to SearchConditionConvertingExpressionVisitor we created Db2RowNumber* visitor but in this way we have to implement lot of abstract method though those are not needed. Would you suggest which is best base class or interface to derive Db2RowNumber*

**Comment by smitpatel** [comment]
@archanasoni - `SqlExpressionVisitor` should be used as base class only when visitor is supposed to do processing for each custom node in the tree. The intent is to enforce implementation so no custom node gets missed. If you only need to deal with few certain custom expression then derive from `ExpressionVisitor`

**Comment by archanasoni** [comment]
Thanks @smitpatel  it helped a lot :) 
we can close the issue..
