### ISSUE TITLE
Still Struggling with Include with a Where on Child Include

### ISSUE THREAD

**Issue by cgountanis** [dotnet/efcore#19312]
Still not sure how to include a parent table then a one-to-many child table with a specific Where clause. What am I missing? Global filters can do this in the Context but sometimes you just need to filter down the data a bit on the fly in a single SQL call, smaller data return vs getting all the data and using LINQ to filter the SQL results.

```
return _context.ParentTable
                .Include(p => p.ChildTable.Where(c => c.Status == "Open"));
```

**Comment by smitpatel** [comment]
Duplicate of #1833

**Comment by cgountanis** [comment]
Thanks for the reference, based on what I am reading it is not possible yet?
