### ISSUE TITLE
MutableEntityTypeExtensions.GetOrAddProperty

### ISSUE THREAD

**Issue by TrevorFradsham** [dotnet/efcore#19310]
Attempted to upgrade project from net core 2.2 to 3.1 but [MutableEntityTypeExtensions GetOrAddProperty](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.mutableentitytypeextensions.getoraddproperty?view=efcore-2.2) method does not exist in net core 3.1. I cannot find any documentation on depreciation or reason for removal.

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore
Target framework: Net core 3.1

**Comment by AndriySvyryd** [comment]
It was part of Metadata cleanup. You can use
```C#
var property = entityType.FindProperty("") ?? entityType.AddProperty("");
```

**Comment by TrevorFradsham** [comment]
Thank for the quick response.
