### ISSUE TITLE
Two different packages?

### ISSUE THREAD

**Issue by seankanderson** [dotnet/efcore#19325]
I'm seeing two packages on NuGet that look identical except for the dependencies.  

Microsoft.EntityFrameworkCore.Sqlite
Microsoft.EntityFrameworkCore.Sqlite.Core

I'm guessing I should use the .Core library since it doesn't have any other dependencies except for core?  

I'm going through absolute hell with my builds trying to keep EntityFrameworkCore working for UWP/Android etc... 

I installed it (.Core version) but I keep getting duplicate e_sqlite3.dll errors when I build.  I've spent days just trying to get my shit to build.  Users are twiddling their thumbs.  Mind you, I had this working until I started using AppCenter to distribute wherein I started seeing build errors. As I tried to resolve the issues for the AppCenter build I've managed to get into a state where my local builds are hosed.  At least now I get the same error when building in AppCenter and locally. :)

Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload contains two or more files with the same destination path 'e_sqlite3.dll'. Source files: 
C:\Users\SeanAnderson\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.2\runtimes\win10-x86\nativeassets\uap10.0\e_sqlite3.dll
C:\Users\SeanAnderson\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.2\runtimes\win10-x86\native\e_sqlite3.dll	Nevitium.UWP

**Comment by ajcvickers** [comment]
@seankanderson `Microsoft.EntityFrameworkCore.Sqlite` brings the native binary with it and is intended as the default experience. `Microsoft.EntityFrameworkCore.Sqlite.Core` allows for other binaries to be used.

The AppCenter issue is discussed in #19156
