### ISSUE TITLE
Query: Make Order By (Select 1) provider specific

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19332]

**Comment by mburbea** [comment]
You can also use the much more comical `over(order by 1/0)` which is short and does the same thing.

**Comment by maxiptah** [comment]
What is this bug about? Can it be related to my issue here: https://stackoverflow.com/questions/59372650/ef-core-3-1-generates-order-by-select-1-which-breaks-old-code ?

**Comment by ajcvickers** [comment]
Notes from team discussion:
* We are requiring an order, with a warning--see #17498 and #19331
* It seems low value to do this for cases where the warning is suppressed or not generated
* We can revisit this if we get more feedback

For now, closing as not needed.
