### ISSUE TITLE
EF-Proxies <-> Fody.PropertyChanged <-> Reload entry

### ISSUE THREAD

**Issue by michaelmairegger** [dotnet/efcore#19340]
I use Fody.PropertyChanged to inject INotifyPropertyChanged into my model classes. With Microsoft.EntityFrameworkCore.Proxies v2.2.6 the following code called correctly the INotifyPropertyChanged.PropertyChanged event.

    await DbContext.Entry(entity).ReloadAsync();

But with Microsoft.EntityFrameworkCore.Proxies v3.1.0 version the event is not raised. This is strange because the `entity` is correctly updated. The issue happens if I have the following property declaration:

    public string Name { get; set; }

if I use the following declaration then everything works:

    private string Name1;
    public string Name
    {
        get => Name1;
        set => Name1 = value;
    }

First I thought that this is a Fody.PropertyChanged error but leaving Fody.PropertyChanged at the newest version and rolling back to Microsoft.EntityFrameworkCore.Proxies v2.2.6 resolves the issue.
So i think that the issue was introduced with Microsoft.EntityFrameworkCore.Proxies >= 3.0.

Was there introduced a new behavior with the EF-Proxy library that breaks the use with Fody.PropertyChanged? I have tried different Castle.Core versions too but with no success.

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net451

**Comment by ajcvickers** [comment]
@michaelmairegger We made a change in EF Core 3 to make reading and writing properties by their backing fields the default behavior. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#backing-fields-are-used-by-default for more information.

**Comment by michaelmairegger** [comment]
@ajcvickers Thanks, this fixes the issue.
