### ISSUE TITLE
Cosmos: Cannot model properties of the same type in entity

### ISSUE THREAD

**Issue by Dragon160** [dotnet/efcore#19348]
### Description

Assume the following code setup.
There is one "Entity" BmwCar - which is using the EngineInfo as a property.  
As soon as you have the very same property inside the BmwCar (or even another Entity) again - EFC+Comos is not able to model it.

    public class EngineInfo
    {
        public bool IsDiesel { get; set; }
        public string Id { get; set; }
    }

    public class BmwCar
    {
        public string Owner { get; set; }
        public int Age { get; set; }

        public EngineInfo EngineInfo {get; set; }

        public EngineInfo EngineInfo2 { get; set; }
    }

    public class BmwCarConfig : IEntityTypeConfiguration<BmwCar>
    {
        public void Configure(EntityTypeBuilder<BmwCar> builder)
        {
            builder.OwnsOne(p => p.EngineInfo);
            builder.OwnsOne(p => p.EngineInfo2);

        }
    }

### Expected behaviour

Should be able to model it and store it within the database like this:

    {
        "Id": "9a519621-b765-462c-8a86-1d5bf39ba596",
        "Discriminator": "BmwCar",
        "Age": "19",
        "Owner": "Schorsch",
        "id": "BmwCar|9a519621-b765-462c-8a86-1d5bf39ba596",
        "EngineInfo": {
            "Discriminator": "EngineInfo",
            "Id": "xyz",
            "IsDiesel": false,
        },
        "EngineInfo2": {
            "Discriminator": "EngineInfo",
            "Id": "xyz2",
            "IsDiesel": false,
        },
    }

### Actual behaviour

System.InvalidOperationException: The instance of entity type 'EngineInfo' cannot be tracked as the entity type 'BmwCar.EngineInfo#EngineInfo' because they are not in the same hierarchy.   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity, IEntityType entityType)

### Further technical details

EF Core version:    3.1.0 / 3.0.0  
Database provider:  Cosmos DB  
Target framework:   Core 3.1 / netStandard2.1  
Operating system:   Windows 10

**Comment by ajcvickers** [comment]
@Dragon160 Please post a small, runnable project or complete code listing that demonstrates the behavior you are seeing.

**Comment by Dragon160** [comment]
@ajcvickers It turns out that the problem is a different one than reported. I will create another issue with the correct title and attach a small sample project to it! 

I think this one can be closed ;-)
