### ISSUE TITLE
Vulnerability in reference as reported by Snyk

### ISSUE THREAD

**Issue by badamsdev** [dotnet/efcore#19347]
A new Asp.Net Core 3.1 project with Authentication enabled adds the Microsoft.EntityFrameworkCore.SqlServer 3.1.0 packages which has a known vulnerability in a reference as reported by Snyk.

> **High severity vulnerability found in System.Text.RegularExpressions**
> **Description:** Regular Expression Denial of Service (ReDoS)
> **Info:** [Snyk Report](https://snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTREGULAREXPRESSIONS-174708)
> 
> **Introduced through:** Microsoft.EntityFrameworkCore.SqlServer@3.1.0
> 
> **From:** Microsoft.EntityFrameworkCore.SqlServer@3.1.0 > Microsoft.Data.SqlClient@1.0.19269.1 > Microsoft.Identity.Client@3.0.8 > System.Xml.XDocument@4.3.0 > System.Xml.ReaderWriter@4.3.0 > System.Text.RegularExpressions@4.3.0
> 
> **From:** Microsoft.EntityFrameworkCore.SqlServer@3.1.0 > Microsoft.Data.SqlClient@1.0.19269.1 > Microsoft.Identity.Client@3.0.8 > System.Runtime.Serialization.Json@4.3.0 > System.Private.DataContractSerialization@4.3.0 > System.Text.RegularExpressions@4.3.0
>   From: Microsoft.EntityFrameworkCore.SqlServer@3.1.0 > Microsoft.Data.SqlClient@1.0.19269.1 > Microsoft.Identity.Client@3.0.8 > System.Runtime.Serialization.Json@4.3.0 > System.Private.DataContractSerialization@4.3.0 > System.Xml.ReaderWriter@4.3.0 > System.Text.RegularExpressions@4.3.0
>   and 5 more...
> 
> **Fixed in:** 4.3.1
> **Tested 99 dependencies for known issues, found 1 issue, 8 vulnerable paths.**

This was fixed in May 2019 with System.Text.RegularExpressions@4.3.1.
[GitHub Announcement](https://github.com/dotnet/announcements/issues/111)

**I'm wondering why EntityFrameworkCore has not updated it's packages?**

**Comment by ErikEJ** [comment]
I looks like a case of https://www.nuget.org/packages/Microsoft.Identity.Client/ not updating its dependencies - you can reference the newer version explicitly, if you want

**Comment by ajcvickers** [comment]
@badamsdev I am following up internally with the owners of the EF dependency.
