### ISSUE TITLE
Query: Add more tests for Queryable.Reverse

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19356]
Add tests for 
- Reverse inside a subquery, i.e. the main query is being pushed down
- Reverse is used in either side of join/leftjoin/selectmany
- Reverse is used in a subquery in projection
   - Single result
   - Collection projection
- Reverse is used in scalar subquery

**Comment by smitpatel** [comment]
- OrderBy -> OrderBy -> reverse
- OrderBy -> ThenBy -> reverse

**Comment by Pankraty** [comment]
I'll do it if no one minds.

**Comment by Pankraty** [comment]
@smitpatel I am new to CosmosDB and have some issues so I am asking for a bit of advice. 
```
ss.Set<Employee>()
    .OrderBy(e => e.City)
    .ThenBy(e => e.EmployeeID)
    .Reverse()
    .Select(e => $"{e.EmployeeID}")
```
this query fails with `{"code":400,"body":{"code":"BadRequest","message":"Message: {\"Errors\":[\"The order by query does not have a corresponding composite index that it can be served from.\"]}`.

I believe it has to work on CosmosDB too; maybe I have to add a composite index, or choose another pair of columns? Or should I disable that particular test on Cosmos?

**Comment by smitpatel** [comment]
Disable test on cosmos for now. Issue number in skip message would be #17246
