### ISSUE TITLE
Where to fix double @ in FromSqlInterpolated_with_inlined_db_parameter

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19364]
What would be the correct place to handle the double `@` generated as part of `FromSqlInterpolated_with_inlined_db_parameter` test? The `QuerySqlGenerator.VisitFromSql` does not seem to be hit in this scenario.

**Comment by smitpatel** [comment]
Update
https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/blob/db3591f034089d7c283c48b40c40eaae246994c5/Provider/src/FirebirdSql.EntityFrameworkCore.Firebird/Storage/Internal/FbSqlGenerationHelper.cs#L33-L34
to align with
https://github.com/aspnet/EntityFrameworkCore/blob/2aefa91e1e823eec9648be38998ffdbb71016410/src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs#L60-L63

**Comment by cincuranet** [comment]
Thanks. No idea how I could forget about this.
