### ISSUE TITLE
OrderBy Anonymous Type Not Working (SQL Server)

### ISSUE THREAD

**Issue by mmeyer-civic** [dotnet/efcore#19367]
We have a Asp.Net Core 3.1 project with OData integrated that isn't working when you provide more than one order by filter.  Entity Framework isn't able to translate the query.

I've created a very simple console application to reproduce the issue.
[https://github.com/mmeyer-civic/efcoreorderby](https://github.com/mmeyer-civic/efcoreorderby)

### Steps to reproduce

1. Run the application

The query with an anonymous type doesn't work.  This is the way that Odata is producing the order by ($orderby: Name,Color,Family).

```C#
 var query2 = db.SimpleObjects.OrderBy(t => new { t.Name, t.Color, t.Family }).ToList();
```

But this does

```C#
var query = db.SimpleObjects.OrderBy(t =>t.Name).ThenBy(t=>t.Color).ThenBy(t=>t.Family).ToList();
```

### Got Exceptions? Include both the message and the stack trace

```
The LINQ expression 'DbSet<SimpleObject>
    .OrderBy(s => new { 
        Name = s.Name, 
        Color = s.Color, 
        Family = s.Family
     })' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system:
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment]
@mmeyer-civic `.OrderBy(t => new { t.Name, t.Color, t.Family })` is an interesting pattern for OData to generate. We will follow up with the OData team to understand why they are doing this.
