### ISSUE TITLE
Include_duplicate_collection_result_operator missing order

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19363]
The `Include_duplicate_collection_result_operator` in both `Include...` and `IncludeAsync...` is missing the order before the final `Take(1)`.

**Comment by ajcvickers** [comment]
@cincuranet Consider sending a PR?

**Comment by ajcvickers** [comment]
Closing this for now as there hasn't been any response. @cincuranet We're more than happy to take a PR for this.
