### ISSUE TITLE
Insert failure in Can_insert_update_delete test

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19362]
I'm having failure in the `Can_insert_update_delete` test on the first action (the insert path) and I fail to understand why EF Core is doing the observed behavior.

Before the call to `nz.Animals.Add(kiwi);` the `kiwi` is in `Detached` state (`DetectChanges` called). After the `nz.Animals.Add(kiwi);` it's in `Modified` state (again `DetectChanges` called). How? Why?

Obviously then in my provider I generate `UPDATE` statement and everything is wrong. But I have no idea how the object got into this state, let alone whether something in provider could cause that.

Any ideas?

BTW the `nz` is in `Unchanged` state.

**Comment by ajcvickers** [comment]
@cincuranet This may be due to keys being configured as generated when they should not be, or vice-versa. Specifically, consider that if an entity has a generated key, and that key value is set, then it will get the Modified/Unchanged state instead of the Added state.

**Comment by cincuranet** [comment]
Yes, that was it. Thanks.
