### ISSUE TITLE
Foreign key is not inserted for new child records when an entity has two OwnsMany of the same type

### ISSUE THREAD

**Issue by edkwchan** [dotnet/efcore#19374]
Here is my object
``` C#
public class Invoice
{
public Guid ID {get; set;}
public string InvoiceNum {get; set;}
public List<PhoneNumber> DeliveryPhoneNumbers { get; set; } = new List<PhoneNumber>();
public List<PhoneNumber> BillPhoneNumbers { get; set; } = new List<PhoneNumber>();
}

public class PhoneNumber
{
public string NationalDestinationCode {get;set;}
public string SubscriberNumber {get;set;}
}

public class InvoiceConfiguration : EntityConfiguration<Invoice>
{
            modelBuilder.Entity<Invoice>()
                .OwnsMany(r => r.DeliveryPhoneNumbers, p =>
                {
                    p.WithOwner().HasForeignKey("InvoiceID");
                    p.Property<Guid>("ID");
                    p.HasKey("ID");
                });
            modelBuilder.Entity<Invoice>()
                .OwnsMany(r => r.BillPhoneNumbers, p =>
                {
                    p.WithOwner().HasForeignKey("InvoiceID");
                    p.Property<Guid>("ID");
                    p.HasKey("ID");
                });
}
```

The migration script is generated correctly

            migrationBuilder.CreateTable(
                name: "Invoices_BillPhoneNumbers",
                columns: table => new
                {
                    ID = table.Column<Guid>(nullable: false),
                    NationalDestinationCode = table.Column<string>(maxLength: 5, nullable: true),
                    SubscriberNumber = table.Column<string>(maxLength: 14, nullable: true),
                    InvoiceID = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Invoices_BillPhoneNumbers", x => x.ID);
                    table.ForeignKey(
                        name: "FK_Invoices_BillPhoneNumbers_Invoices_InvoiceID",
                        column: x => x.InvoiceID,
                        principalTable: "Invoices",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });
            migrationBuilder.CreateTable(
                name: "Invoices_DeliveryPhoneNumbers",
                columns: table => new
                {
                    ID = table.Column<Guid>(nullable: false),
                    NationalDestinationCode = table.Column<string>(maxLength: 5, nullable: true),
                    SubscriberNumber = table.Column<string>(maxLength: 14, nullable: true),
                    InvoiceID = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Invoices_DeliveryPhoneNumbers", x => x.ID);
                    table.ForeignKey(
                        name: "FK_Invoices_DeliveryPhoneNumbers_Invoices_InvoiceID",
                        column: x => x.InvoiceID,
                        principalTable: "Invoices",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

When I insert an Invoice entity in SQL database, I got 
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Invoices_DeliveryPhoneNumbers_Invoices_InvoiceID". The conflict occurred in database "ORG_ad2a3c6b-1fd2-4594-b12c-a3e17d601481", table "dbo.Invoices", column 'ID'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at Microsoft.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.<>c__DisplayClass192_0.<NextResultAsync>b__1(Task t)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

If I removed the constraint FK_Invoices_DeliveryPhoneNumbers_Invoices_InvoiceID deliberately in database, then I can add the invoice record but the records in Invoices_DeliveryPhoneNumbers has empty Guid in the InvoiceID field.  So it is clear that why records cannot be added at the first place.

If there is only one set of "PhoneNumbers", then things can work smoothly.

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.0
Target framework: .NET Core 3.1
Operating system:  Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment]
@AndriySvyryd to take a look.

**Comment by AndriySvyryd** [comment]
@edkwchan I am not able to repro this on master, can you provide a small runnable project?

This is the code I tried:
```C#

[ConditionalFact]
public void Can_insert_owned_collections()
{
    using var testDatabase = SqlServerTestStore.CreateInitialized(DatabaseName);
    var options = Fixture.CreateOptions(testDatabase);

    using (var context = new InvoiceContext(options))
    {
        context.Database.EnsureCreated();
        context.Add(new Invoice()
        {
            DeliveryPhoneNumbers = new List<PhoneNumber> { new PhoneNumber() },
            BillPhoneNumbers = new List<PhoneNumber> { new PhoneNumber() }
        });

        context.SaveChanges();
    }
}

public class InvoiceContext : DbContext
{
    public InvoiceContext(DbContextOptions options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Invoice>()
            .OwnsMany(r => r.DeliveryPhoneNumbers, p =>
            {
                p.WithOwner().HasForeignKey("InvoiceID");
                p.Property<Guid>("ID");
                p.HasKey("ID");
            });
        modelBuilder.Entity<Invoice>()
            .OwnsMany(r => r.BillPhoneNumbers, p =>
            {
                p.WithOwner().HasForeignKey("InvoiceID");
                p.Property<Guid>("ID");
                p.HasKey("ID");
            });
    }
}

public class Invoice
{
    public Guid ID { get; set; }
    public string InvoiceNum { get; set; }
    public List<PhoneNumber> DeliveryPhoneNumbers { get; set; } = new List<PhoneNumber>();
    public List<PhoneNumber> BillPhoneNumbers { get; set; } = new List<PhoneNumber>();
}

public class PhoneNumber
{
    public string NationalDestinationCode { get; set; }
    public string SubscriberNumber { get; set; }
}
```

**Comment by edkwchan** [comment]
Sorry, I'm unable to reproduce the problem.  Probably it was my fault in code.
