### ISSUE TITLE
How to get all strings that contains any of a given words? 

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#19388]
I opened this issue: [](https://github.com/aspnet/EntityFrameworkCore/issues/19273)

In that case I was using EF Core 3.0 but now I am using EF Core 3.1, as it was suggested me, but the problem is the same.

I am trying a query like this:

```
string[] miArrPalabrasABuscar = paramCriterios.Description.Split(" ").Where(x => string.IsNullOrWhiteSpace(x) == false).ToArray();
                        miIqPersons = miIqPersons.Where(x => miArrPalabrasABuscar.Any(y => x.Description.Contains(y)));
```
So it seems that with the new version the problem still happens.

Thanks.

**Comment by ajcvickers** [comment]
@smitpatel to find duplicate.

**Comment by smitpatel** [comment]
Duplicate of #19070
