### ISSUE TITLE
Interpret [DataType(DataType.Date)] attribute for entity properties

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#19382]
When I use the `System.DateTime` type for an propery with the attribute `[DataType(DataType.Date)]`, the framework automatically creates an `datetime2` type when using SQL Server.

But actually, this is not necessary, because the `date` type in SQL Server would be enough, since we defined already with the [DateTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatypeattribute?view=netframework-4.8) that we only are interested in the date part of DateTime.

Currently I always have to use the attribute `[Column(TypeName = "date")]` to tell the framework that I don't want to use the full date-time type, but just the simple date type.

Suggestion:
----------
When I use the [DateTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatypeattribute?view=netframework-4.8) with the option `DateType.Date`, the framework should automatically choose the SQL data type `date` (when using SQL Server) so I don't need to use the `ColumnAttribute`.

**Comment by ajcvickers** [comment]
@ice1e0 This attribute is designed primarily for validation of string-based members that have different formatting restrictions in the UI. Coercing this into something that is also used to determine a database column type involves a significant mismatch. These types of mismatch are a common source of confusion (consider empty strings and the Required attribute) so this isn't something we plan to support.
