### ISSUE TITLE
Query: Key comparison for collection nav throws when PK is struct

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19407]
See https://github.com/aspnet/EntityFrameworkCore/issues/13507#issuecomment-569130301

We use Expression.Equal always, which does not work for value type which does not define Equal operator.

Few options
- We can always use Equals operator which translate to the same thing. (need to verify this)
- We can make it conditional that use Expression.Equal only when possible.

**Comment by smitpatel** [comment]
Wait for #13507 to add test classes.

**Comment by smitpatel** [comment]
@ajcvickers - Were there tests added for this in source?

**Comment by ajcvickers** [comment]
Change the structs in this file: https://github.com/dotnet/efcore/blob/c2c469d9bd2140ffe43e6dae43b674ce67dead9c/test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs#L1807
