### ISSUE TITLE
Set [JsonIgnore] on LazyLoader in IProxyLazyLoader

### ISSUE THREAD

**Issue by jamalabo1** [dotnet/efcore#19403]
The attribute [IgnoreDataMember] should ignore the field `LazyLoader` when `.UseLazyLoadingProxies()` is used, 
but still, it returns the model with 
```
{
   "LazyLoader": {}
}
```

### Steps to reproduce

What steps can we follow to reproduce the issue?
Include `.UseLazyLoadingProxies()` and use any model and return it, 

#### Controller
``` C#
[HttpGet]
[Authorize(AuthorizationPolicies.ClientAndAdmins)]
[Route("{id}")]
[EnableQuery]
public async Task<IActionResult> GetClient(Guid id)
{
      var response = await _clientsService.ReadClient(id);
      if (response.Response == null) return StatusCode(response.StatusCode);
      return StatusCode(response.StatusCode, response.Response);
}
```
#### Configuration
```C#
services.AddDbContext<AppContext>(options =>
{
     options
       .UseNpgsql(Configuration.GetConnectionString("DefaultConnection"))
       .UseSnakeCaseNamingConvention()
       .UseLazyLoadingProxies();
});
```

### Further technical details

EF Core version: `3.1.0`
Database provider: `Npgsql`
Target framework: `.NET Core 3.1`
Operating system: `Windows 10`
IDE: `Rider 2019.3.1`
 
This may be `Npgsql.EntityFrameworkCore` problem, but `IProxyLazyLoader` Is under the namespace `Microsoft.EntityFrameworkCore.Proxies`

**Comment by ajcvickers** [comment]
@jamalabo1 Reading between the lines here, I assume you mean that `"LazyLoader"` is included in the serialized JSON of the result. If so, then this seems like a JSON serialization issue, not an EF issue.

**Comment by roji** [comment]
This seems to be by-design, see https://github.com/dotnet/corefx/issues/40062. Try to use the [JsonIgnore] attribute instead of [IgnoreDataMember].

**Comment by jamalabo1** [comment]
@ajcvickers can you add both attributes?
(`[JsonIgnore]` & `[IgnoreDataMember]`)

**Comment by roji** [comment]
@jamalabo1 unless I'm mistaken, I don't think anything needs to be added to EF Core - if you have a LazyLoader property on your entity, you will need to add [JsonIgnore] on it yourself ([see the lazy loading documentation](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading)). If I'm misunderstanding or missing something let me know.

**Comment by jamalabo1** [comment]
@roji you are correct nothing have to be added to EF core because I can fix it my self by adding the field `LazyLoader` to my model and make it private or add the attribute, but this can be fixed if `[JsonIgnore]` was added to EF core (`IProxyLoader`),
it's not an issue so fixed is not the best word to fix, but ...,
any way this what I did
```C#
private ILazyLoader LazyLoader { get; set; }
```
and this approach worked because it was designed for those who do not use the proxy loader (i do)
(manual lazy loading).

**Comment by ajcvickers** [comment]
@roji We should include this attribute on the generated property in the proxy.

**Comment by roji** [comment]
Oh I see, was not aware this is how things worked. We can use this issue to track that.
