### ISSUE TITLE
LINQ/SQLITE: Unnecessary IS NULL term generated for linq clause !string.isnullorempty()

### ISSUE THREAD

**Issue by fmaeseele** [dotnet/efcore#19410]
Hi,
Using AspnetCore 3.1 with Linq/SQLite, I have a SQL strangely generated for a simple clause.
I have a simple table containing 2 text fields : COUNTRY and ISOCOUNTRY.
I want to get all rows where COUNTRY is not null and not empty:

```c#
VisitorsByCountry = _dataDbContext.Visitors
    .AsNoTracking()
    // Fix for NULL values on ordinal 11
    .Select(v => new { v.Country, v.IsoCountry })
    .Where(v => !string.IsNullOrEmpty(v.Country))
    .AsEnumerable(); // Fix for EF 3.0 not supporting ClientSide GroupBy
```

When I look into the SQL generated for the Where(v => !string.IsNullOrEmpty(v.Country)) :

```sql
SELECT "v"."Country", "v"."IsoCountry"
FROM "Visitors" AS "v"
WHERE "v"."Country" IS NOT NULL AND (("v"."Country" <> '') OR "v"."Country" IS NULL)
```

The Where clause should be like: `WHERE "v"."Country" IS NOT NULL AND "v"."Country" <> ''`

Regards

**Comment by maumar** [comment]
IsNullOrEmpty can never be null, so we shouldn't ally "full" expansion even for the negated case. Related to https://github.com/aspnet/EntityFrameworkCore/issues/18555

**Comment by maumar** [comment]
Problem here is that at the time we compute null semantics we have the expression in the following form:

```sql
NOT ( v.Country IS NULL OR (  v.Country = N'' ))
```

however we only recognize pattern is form: column IS NOT NULL && (...)

We should recognize the pattern in the negated form as well, i.e. 

column IS NULL OR (...)

**Comment by maumar** [comment]
note: on sqlserver we translate IsNullOrEmpty to like and don't produce the redundant null check:

```sql
NOT ([c].[Country] IS NULL OR ([c].[Country] LIKE N''))
```
