### ISSUE TITLE
Lazy loading proxies are not thread safe

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#19414]
Hi,

In my unit tests, I run 20 parallel calls to my app to check that everything works as expected when there are concurrent requests.

Lately I have used LazyLoading ( Microsoft.EntityFrameworkCore.Proxies ), and I started having this exception :

```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    Dictionary`2.set_Item(TKey key, TValue value)
    InternalEntityEntry.SetIsLoaded(INavigation navigation, Boolean loaded)
    EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
    ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
    ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
    ChangeDetector.DetectChanges(IStateManager stateManager)
    DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

```

It's due to this assignation which is not thread-safe : https://github.com/aspnet/EntityFrameworkCore/blob/6ff8377477d6240f16c58c86e7d9eaf4b4f73ebf/src/EFCore/Internal/LazyLoader.cs#L69 

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0

**Comment by YeskaNova** [comment]
Sometimes I have this exception too :

```
  Message: 
    System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Stack Trace: 
    Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    Dictionary`2.set_Item(TKey key, TValue value)
    LazyLoader.SetLoaded(Object entity, String navigationName, Boolean loaded)
    InternalEntityEntry.SetIsLoaded(INavigation navigation, Boolean loaded)
    EntityGraphAttacher.SetReferenceLoaded(EntityEntryGraphNode`1 node)
    EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
    EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
    NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
    InternalEntityEntryNotifier.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
    ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
    ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
    ChangeDetector.DetectChanges(IStateManager stateManager)
    ChangeTracker.DetectChanges()
    DbContext.TryDetectChanges()
    DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by roji** [comment]
@YeskaNova can you confirm that you're performing multiple concurrent operations on the same DbContext instance? If so, that is not supported - see [this note in the docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#avoiding-dbcontext-threading-issues) and [this discussion if you're interested in the reasoning why](https://github.com/aspnet/EntityFrameworkCore/issues/18148).

Otherwise, if you're sure you're not performing concurrent operations on the same instance, can you please post a runnable code sample?

**Comment by YeskaNova** [comment]
@Roji I'm not performing concurrent operations on the same DbContext, it's used as a UnitOfWork so one DbContext = one single threaded request. Let me check that service scopes aren't misleading me to use the same DbContext.

**Comment by YeskaNova** [comment]
I had a cache lazy-using a dbcontext and that was the problem, sorry for that.

**Comment by roji** [comment]
Thanks for confirming.

**Comment by ajcvickers** [comment]
Re-opening to discuss thread-safety of proxies.

**Comment by ajcvickers** [comment]
Note from team discussion:
* If context has been disposed, then access to the navigation property should be thread-safe. This allows entity instances to be passed and to and used freely in other parts of the application after loading has finished.
* If the context has not been disposed, then using the lazy-loader is using the context instance, hand hence will not be thread safe.

**Comment by ajcvickers** [comment]
Reviewed the code here and I think all is well. The `_loadedStates` dictionary can only be created or mutated while the entity is being loaded, which means that this is happening while the context is being used and hence does not need to be thread safe. (See above.) Later multiple threads might be accessing `_loadedStates` but since no thread can modify it there should be no thread-safety issues.

**Comment by Xriuk** [comment]
Lazy loading with or without proxies not being thread-safe is a bit problematic, how am I supposed to know when my entity will be accessed and my property will be loaded? How we should handle this?

**Comment by ajcvickers** [comment]
@Xriuk You won't be able to use lazy-loading if you have multiple threads that could trigger lazy-loading using the same context instance.

This is one of the reasons many people consider lazy-loading to be an anti-pattern.

**Comment by roji** [comment]
@ajcvickers didn't actually think of that specific problem with lazy-loading...

**Comment by roji** [comment]
Indeed, that all makes sense... One possible way to make this sane would be to use a new DbContext instance when lazy-loading, with the logic that the lazy property access isn't actually part of the unit-of-work, but that's all very murky (there are probably cases where it should be, cases where it shouldn't?).
