### ISSUE TITLE
3.1, Regression, InMemoryProvider

### ISSUE THREAD

**Issue by yahorsi** [dotnet/efcore#19424]
### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
This issue is lacking any information, am closing as a likely dup/attempt of #19425

**Comment by yahorsi** [comment]
Sorry/thank you
