### ISSUE TITLE
To change the IDENTITY property of a column, the column needs to be dropped and recreated

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#19427]
I am getting the following error when I attempt to update my database from the Package Manager Console.

> To change the IDENTITY property of a column, the column needs to be dropped and recreated.

I realize there are existing issues about this same error, but they seem to involve primary keys where the remark about IDENTITY makes sense. I can't see how IDENTITY applies in my case as the column I'm changing is not a primary key and is not indexed.

### Steps to Reproduce

My table definition was as follows:

    CREATE TABLE [dbo].[Areas] (
        [Id]          INT            IDENTITY (1, 1) NOT NULL,
        [UserId]      NVARCHAR (450) NOT NULL,
        [Title]       NVARCHAR (150) NOT NULL,
        [Description] NVARCHAR (MAX) NULL,
        [CssClass]    NVARCHAR (32) NOT NULL, 
        [Sequence]    INT            NOT NULL,
        [OnHold]      BIT            NOT NULL,
        [Created]     DATE           NOT NULL,
        CONSTRAINT [PK_Areas] PRIMARY KEY CLUSTERED ([Id] ASC),
        CONSTRAINT [FK_Areas_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo]. [AspNetUsers] ([Id]) ON DELETE CASCADE
    );
    GO
    CREATE NONCLUSTERED INDEX [IX_Areas_UserId]
        ON [dbo].[Areas]([UserId] ASC);

I changed the model so that `string CssClass` is removed, and added `int StyleId` instead. But when I update the database, I get the error described above.

So I manually edited the table definition as follows.

    CREATE TABLE [dbo].[Areas] (
        [Id]          INT            IDENTITY (1, 1) NOT NULL,
        [UserId]      NVARCHAR (450) NOT NULL,
        [Title]       NVARCHAR (150) NOT NULL,
        [Description] NVARCHAR (MAX) NULL,
        [StyleId]     INT NOT NULL, 
        [Sequence]    INT            NOT NULL,
        [OnHold]      BIT            NOT NULL,
        [Created]     DATE           NOT NULL,
        CONSTRAINT [PK_Areas] PRIMARY KEY CLUSTERED ([Id] ASC),
        CONSTRAINT [FK_Areas_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo]. [AspNetUsers] ([Id]) ON DELETE CASCADE
    );
    GO
    CREATE NONCLUSTERED INDEX [IX_Areas_UserId]
        ON [dbo].[Areas]([UserId] ASC);

But when I try to update the database again (to ensure everything is in sync), I get the same error.

### Update Output

Here's the output from the update process.

    PM> update-database
    Microsoft.EntityFrameworkCore.Infrastructure[10403]
          Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
    Microsoft.EntityFrameworkCore.Database.Command[20100]
          Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
          SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
    Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
    Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
    Microsoft.EntityFrameworkCore.Database.Command[20100]
          Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
          SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
    Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
    SELECT [MigrationId], [ProductVersion]
    FROM [__EFMigrationsHistory]
    ORDER BY [MigrationId];
    Microsoft.EntityFrameworkCore.Database.Command[20100]
          Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
          SELECT [MigrationId], [ProductVersion]
          FROM [__EFMigrationsHistory]
          ORDER BY [MigrationId];
    Microsoft.EntityFrameworkCore.Migrations[20402]
          Applying migration '20191230173411_StyleIdNowInt'.
    Applying migration '20191230173411_StyleIdNowInt'.
    System.InvalidOperationException: To change the IDENTITY property of a column, the column needs to be dropped and recreated.
       at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
       at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_4(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
       at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
       at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
       at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
       at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
       at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
       at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
       at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
       at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
    To change the IDENTITY property of a column, the column needs to be dropped and recreated.

### Migration File

Here is my migration file. (Note that the name is different because I regenerated it. But it's getting the same error.)

    public partial class CssClassToStyleId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Discriminator",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "CssClass",
                table: "Areas");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Areas",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .OldAnnotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddColumn<int>(
                name: "StyleId",
                table: "Areas",
                nullable: false,
                defaultValue: 0);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "StyleId",
                table: "Areas");

            migrationBuilder.AddColumn<string>(
                name: "Discriminator",
                table: "AspNetUsers",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Areas",
                type: "int",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddColumn<string>(
                name: "CssClass",
                table: "Areas",
                type: "nvarchar(32)",
                maxLength: 32,
                nullable: false,
                defaultValue: "");
        }
    }

### Further Technical Details

Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by SoftCircuits** [comment]
Is it because my new column ends in *Id*? Was it automatically interpreted as a primary or other key? If so, how the heck do I stop that?

**Comment by SoftCircuits** [comment]
### UPDATE

Looking at the migration file, I see the blocks that call `AlterColumn` appear to be changing my primary key (to the same name and type). If I comment out these blocks, I can `update-database` without error.

But I'm still not clear why these blocks were added. They don't appear to be necessary. This question is a few days old now. I'm hoping someone can take a look at this issue. There appears there might be a problem.

**Comment by ajcvickers** [comment]
@SoftCircuits Please post a small, runnable project that reproduces the behavior you are seeing so that we can investigate.

**Comment by SoftCircuits** [comment]
> @SoftCircuits Please post a small, runnable project that reproduces the behavior you are seeing so that we can investigate.

Well, if the code wouldn't compile it's hard to see how it would be runnable. At any rate, since there's a database involved, that's more easily said than done. Moreover, if not everyone is reporting this, I have no reason to think that creating a new project would include this error.  So I'll probably just let it go if no one else is worried about it.
