### ISSUE TITLE
Amazing, what happened to EFCore 3x

### ISSUE THREAD

**Issue by EzrealJ** [dotnet/efcore#19441]
Sorry, my English is not very good, the following text is translated by Google, I hope to express my meaning accurately

Before the 3.1 version was released, I used version 2.2.6. My application is a multi-tenant application. About 2000+ tenants use my application, so I replaced IModelCacheKeyFactory to achieve the purpose
![image](https://user-images.githubusercontent.com/28976837/71613989-4fd33100-2be4-11ea-953e-1b0c59bd04bb.png)

But this also brings some costs. When using the 2.2.6 version, it needs to consume about 1.2GB+ of memory during the peak application period; but when I upgraded the NETCore to 3.1 version, I also upgraded the EFCore version to 3.1. I did not change my business code, I just used extensions to complete the version switch
![image](https://user-images.githubusercontent.com/28976837/71614004-68434b80-2be4-11ea-8eb1-650ba1ab2117.png)

But it is very amazing that after the upgrade, the application only needs 200MB + of memory overhead during the peak period. What brings so much memory savings?Can you answer my doubts?

**Comment by ajcvickers** [comment]
@EzrealJ Glad the upgrade helped. It's hard to know what changed to cause this impact, but if I had to guess it was likely to do with the way `LoggerFactory` is handled when set differently for each context instance.
