### ISSUE TITLE
 The query extracts all the fields in a LEFT JOIN.

### ISSUE THREAD

**Issue by herreraluisr** [dotnet/efcore#19452]
Good afternoon.

In the following query:

            var Qmerma = (from a in Db.PP_Merma.Where(x => x.Indicador == "E")
                          from a1 in a.PP_MermaDet
                          join a2 in Db.PP_Equipo on a.PlantaId equals a2.EquipoId
                          join a3 in Db.PP_Turno on a.TurnoId equals a3.TurnoId
                          join a4 in Db.PP_Equipo on a.EquipoId equals a4.EquipoId
                          join a5 in Db.PP_Producto on a.ProductoId equals a5.ProductoId
                          join a6 in Db.WH_Item on a5.Item equals a6.Item
                          join a7 in Db.PP_TipoMerma on a1.TipoMermaId equals a7.TipoMermaId
                          join a8 in Db.SY_Person on a.Person equals a8.Person into Operario
                          from a8 in Operario.DefaultIfEmpty()
                          join b in Db.PP_ParteProduccion on new { a.PlantaId, a.Fecha.Date, a.TurnoId } equals new { b.PlantaId, b.FechaProduccion.Date, b.TurnoId } into Parte
                          from b in Parte.DefaultIfEmpty()
                          join b1 in Db.PP_ParteProduccionDetalle on new { b.ParteProduccionId, a.EquipoId, a.ProductoId } equals new { b1.ParteProduccionId, EquipoId = (int)b1.MaquinaId, b1.ProductoId } into ParteDet
                          from b1 in ParteDet.DefaultIfEmpty()
                          select new
                          {
                              MermaId = (int?)a1.MermaId,
                              PlantaId = (int?)a.PlantaId,
                              Fecha = (DateTime?)a.Fecha.Date,
                              TurnoId = (int?)a.TurnoId,
                              ProductoId = (int?)a.ProductoId,
                              Operario = a8.Name,
                              a7.Indicador,
                              a7.TipoMerma,
                              Cantidad = (decimal?)a1.Cantidad,
                              a7.Orden
                          });
            var TQuery = (from a in Db.PP_ParteProduccion
                          from b in a.PP_ParteProduccionDetalle
                          join b1 in Db.PP_Producto on new { b.ProductoId, EsFormato = "N" } equals new { b1.ProductoId, b1.EsFormato }
                          join b2 in Db.WH_Item on b1.Item equals b2.Item
                          join b3 in Db.SY_Person on a.Person equals b3.Person into Supervisor
                          from b3 in Supervisor.DefaultIfEmpty()
                          join m in Db.PP_Equipo on new { a.PlantaId, IndicadorTipo = "F" } equals new { PlantaId = m.EquipoId, m.IndicadorTipo }
                          join m2 in Db.PP_Equipo on b.MaquinaId equals m2.EquipoId into Linea
                          from m2 in Linea.DefaultIfEmpty()
                          join t in Db.PP_Turno on a.TurnoId equals t.TurnoId
                          join c in Qmerma on new { PlantaId = (int?)a.PlantaId, Fecha = (DateTime?)a.FechaProduccion.Date, TurnoId = (int?)a.TurnoId, ProductoId = (int?)b.ProductoId } equals new { c.PlantaId, c.Fecha, c.TurnoId, c.ProductoId } into Merma
                          from c in Merma.DefaultIfEmpty()
                          select new
                          {
                              Periodo = SqlDb.Periodo(a.FechaProduccion),
                              Planta = m.Descripcion,
                              Fecha = a.FechaProduccion.Date,
                              Turno = t.Descripcion,
                              Linea = m2.Descripcion,
                              Codigo = b2.ItemCode,
                              CodigoExterno = b2.ExternalCode,
                              Producto = b2.Name,
                              Unidad = b2.Unit,
                              CantidadProduccion = (decimal?)b.Cantidad,
                              CantidadKilos = (b.Cantidad * b2.Weight),
                              Lote = b.NumeroLote,
                              c.MermaId,
                              c.Operario,
                              c.Indicador,
                              c.TipoMerma,
                              c.Cantidad,
                              c.Orden
                          }).Where(vbWhere).OrderBy(x => x.Planta).ThenBy(x => x.Linea).ThenBy(x => x.Fecha).ThenBy(x => x.Turno).ThenBy(x => x.MermaId).ThenBy(x => x.Orden);

The result generated is:

SELECT Convert(VARCHAR(6), [p].[FechaProduccion], 112) AS [Periodo], [p2].[Descripcion] AS [Planta], CONVERT(date, [p].[FechaProduccion]) AS [Fecha], [p4].[Descripcion] AS [Turno], [p3].[Descripcion] AS [Linea], [w].[ItemCode] AS [Codigo], [w].[ExternalCode] AS [CodigoExterno], [w].[Name] AS [Producto], [w].[Unit] AS [Unidad], [p0].[Cantidad] AS [CantidadProduccion], [p0].[Cantidad] * [w].[Weight] AS [CantidadKilos], [p0].[NumeroLote] AS [Lote], [t].[MermaId0] AS [MermaId], [t].[Name1] AS [Operario], [t].[Indicador0] AS [Indicador], [t].[TipoMerma], [t].[Cantidad], [t].[Orden]
FROM [PP_ParteProduccion] AS [p]
INNER JOIN [PP_ParteProduccionDetalle] AS [p0] ON [p].[ParteProduccionId] = [p0].[ParteProduccionId]
INNER JOIN [PP_Producto] AS [p1] ON ([p0].[ProductoId] = [p1].[ProductoId]) AND ('N' = [p1].[EsFormato])
INNER JOIN [WH_Item] AS [w] ON [p1].[Item] = [w].[Item]
LEFT JOIN [SY_Person] AS [s] ON [p].[Person] = [s].[Person]
INNER JOIN [PP_Equipo] AS [p2] ON ([p].[PlantaId] = [p2].[EquipoId]) AND ('F' = [p2].[IndicadorTipo])
LEFT JOIN [PP_Equipo] AS [p3] ON [p0].[MaquinaId] = [p3].[EquipoId]
INNER JOIN [PP_Turno] AS [p4] ON [p].[TurnoId] = [p4].[TurnoId]
LEFT JOIN (
    SELECT [p5].[MermaId], [p5].[Company], [p5].[EquipoId], [p5].[Fecha], [p5].[Indicador], [p5].[Lote], [p5].[Observacion], [p5].[ParteProduccionDetalleId], [p5].[Person], [p5].[PlantaId], [p5].[ProductoId], [p5].[ReplicationUnit], [p5].[Reproceso], [p5].[TurnoId], [p5].[XLastDate], [p5].[XLastUser], [p6].[MermaDetId], [p6].[Cantidad], [p6].[Company] AS [Company0], [p6].[MermaId] AS [MermaId0], [p6].[ReplicationUnit] AS [ReplicationUnit0], [p6].[TipoMermaId], [p6].[XLastDate] AS [XLastDate0], [p6].[XLastUser] AS [XLastUser0], [p6].[ZonaLineaId], [p7].[EquipoId] AS [EquipoId0], [p7].[Cabezales], [p7].[Capacidad], [p7].[Caudal], [p7].[Company] AS [Company1], [p7].[Descripcion], [p7].[EquipoPadreId], [p7].[IndicadorEnvasado], [p7].[IndicadorEquipo], [p7].[IndicadorLote], [p7].[IndicadorProducto], [p7].[IndicadorTipo], [p7].[Moldes], [p7].[NombreCorto], [p7].[ReplicationUnit] AS [ReplicationUnit1], [p7].[Status], [p7].[TipoEnvasado], [p7].[TipoEquipo], [p7].[WareHouse], [p7].[XLastDate] AS [XLastDate1], [p7].[XLastUser] AS [XLastUser1], [p8].[TurnoId] AS [TurnoId0], [p8].[Company] AS [Company2], [p8].[Descripcion] AS [Descripcion0], [p8].[EquipoId] AS [EquipoId1], [p8].[HoraFin], [p8].[HoraFin1], [p8].[HoraInicio], [p8].[HoraInicio1], [p8].[IndicadorLote] AS [IndicadorLote0], [p8].[NombreCorto] AS [NombreCorto0], [p8].[ReplicationUnit] AS [ReplicationUnit2], [p8].[XLastDate] AS [XLastDate2], [p8].[XLastUser] AS [XLastUser2], [p9].[EquipoId] AS [EquipoId2], [p9].[Cabezales] AS [Cabezales0], [p9].[Capacidad] AS [Capacidad0], [p9].[Caudal] AS [Caudal0], [p9].[Company] AS [Company3], [p9].[Descripcion] AS [Descripcion1], [p9].[EquipoPadreId] AS [EquipoPadreId0], [p9].[IndicadorEnvasado] AS [IndicadorEnvasado0], [p9].[IndicadorEquipo] AS [IndicadorEquipo0], [p9].[IndicadorLote] AS [IndicadorLote1], [p9].[IndicadorProducto] AS [IndicadorProducto0], [p9].[IndicadorTipo] AS [IndicadorTipo0], [p9].[Moldes] AS [Moldes0], [p9].[NombreCorto] AS [NombreCorto1], [p9].[ReplicationUnit] AS [ReplicationUnit3], [p9].[Status] AS [Status0], [p9].[TipoEnvasado] AS [TipoEnvasado0], [p9].[TipoEquipo] AS [TipoEquipo0], [p9].[WareHouse] AS 
[WareHouse0], [p9].[XLastDate] AS [XLastDate3], [p9].[XLastUser] AS [XLastUser3], [p10].[ProductoId] AS [ProductoId0], [p10].[CalculaCosto], [p10].[CantidadProducto], [p10].[Company] AS [Company4], [p10].[Contenido], 
[p10].[DestinoProducto], [p10].[EquipoId] AS [EquipoId3], [p10].[EsAditivo], [p10].[EsFormato], [p10].[EsSubProducto], [p10].[FactorCosto], [p10].[FactorProducto], [p10].[FormatoId], [p10].[FormulaId], 
[p10].[IndicadorProducto] AS [IndicadorProducto1], [p10].[InsertoId], [p10].[Item], [p10].[MaquinaId], [p10].[MoldeId], [p10].[Name], [p10].[Observacion] AS [Observacion0], [p10].[OrigenProduccion], [p10].[PesoBatch], 
[p10].[PorExtraccion], [p10].[ReplicationUnit] AS [ReplicationUnit4], [p10].[TipoCertificado], [p10].[TipoProducto], [p10].[WareHouse] AS [WareHouse1], [p10].[XLastDate] AS [XLastDate4], [p10].[XLastUser] AS [XLastUser4], 
[w0].[Item] AS [Item0], [w0].[ClasificacionCostos], [w0].[ClasificacionExtraId], [w0].[ClasificacionPreciosPromoId], [w0].[Company] AS [Company5], [w0].[Contenido] AS [Contenido0], [w0].[DefaultQuantity], 
[w0].[DescProperties], [w0].[DescripcionVenta], [w0].[Description], [w0].[ExternalCode], [w0].[Factor], [w0].[FactorFinalProduct], [w0].[FactorProdItem], [w0].[FactorProduction], [w0].[FactorPurchase], 
[w0].[FactorPurchaseItem], [w0].[FactorSale], [w0].[FactorSaleItem], [w0].[FlagAvailableForSale], [w0].[FlagDueDate], [w0].[FlagGeneric], [w0].[FlagItemClass], [w0].[FlagLote], [w0].[FlagMaxMin], [w0].[FlagProduction], 
[w0].[FlagQA], [w0].[FlagQualityCertificate], [w0].[FlagSerie], [w0].[GenericUse], [w0].[GraphicsProcess], [w0].[INTERIOR], [w0].[ItemCareMax], [w0].[ItemClassification], [w0].[ItemCode], [w0].[ItemFamily], [w0].[ItemLine], 
[w0].[ItemMax], [w0].[ItemMin], [w0].[ItemSubFamily], [w0].[ItemType], [w0].[Mark], [w0].[MaterialType], [w0].[Measure], [w0].[Model], [w0].[Name] AS [Name0], [w0].[NextelCode], [w0].[NombreCorto] AS [NombreCorto2], 
[w0].[PACKAGEQUANTITY], [w0].[PACKAGEUNIT], [w0].[PACKAGEUNIT1], [w0].[PriceComplete], [w0].[PriceCompleteDate], [w0].[PriceCurrency], [w0].[ProductoId] AS [ProductoId1], [w0].[RealWeight], [w0].[Registerdate], [w0].[ReplicationUnit] AS [ReplicationUnit5], [w0].[Tariffpercentage], [w0].[TimeVcto], [w0].[TipoEnvase], [w0].[TipoPasta], [w0].[Unit], [w0].[UnitClassification], [w0].[UnitFinalProduct], [w0].[UnitProduction], [w0].[UnitPurchase], [w0].[UnitSale], [w0].[Volume], [w0].[Weight], [w0].[WeightReal], [w0].[XLastDate] AS [XLastDate5], [w0].[XLastUser] AS [XLastUser5], [w0].[tariff], [p11].[TipoMermaId] AS [TipoMermaId0], [p11].[Company] AS [Company6], [p11].[Indicador] AS [Indicador0], [p11].[NombreCorto] AS [NombreCorto3], [p11].[Orden], [p11].[ReplicationUnit] AS [ReplicationUnit6], [p11].[TipoMerma], [p11].[XLastDate] AS [XLastDate6], [p11].[XLastUser] AS [XLastUser6], [s0].[Person] AS [Person0], [s0].[ActivityType], [s0].[Address], [s0].[AddressNumber], [s0].[BirthCountry], [s0].[BirthDate], [s0].[BirthDepartment], [s0].[BirthLocalite], [s0].[BirthProvince], [s0].[BirthReference], [s0].[Block], [s0].[Block2], [s0].[BloodType], [s0].[BusinessUnit], [s0].[CIIU], [s0].[Childrens], [s0].[Civilstate], [s0].[ClassPerson], [s0].[Company] AS [Company7], [s0].[CompanyType], [s0].[CostCenter], [s0].[CostCenter1], [s0].[CostCenter2], [s0].[CostCenter3], [s0].[CostCenterCode], [s0].[Country], [s0].[CountryIssuing], [s0].[DefaultVendor], [s0].[Department], [s0].[Discapacity], [s0].[DocumentNumber], [s0].[DocumentType], [s0].[DriverLicenseAntiquity], [s0].[DriverLicenseNumber], [s0].[DriverLicenseType], [s0].[EMail], [s0].[EmployeeDocumentType], [s0].[Fax], [s0].[FlagContributor], [s0].[FlagKeep], [s0].[FlagLockCA], [s0].[FlagName], [s0].[FlagOutSourcingIn], [s0].[FlagOutSourcingOut], [s0].[FlagPerceptionAgent], [s0].[FlagPersonImport], [s0].[FlagPersonType], [s0].[FlagResponsibleMother], [s0].[FlagRetentionAgent], [s0].[FlagRucPersonType], [s0].[FlagSUNAT5], [s0].[FlagUserID], [s0].[FlagViewRequisition], [s0].[ForeignerCard], [s0].[FormularioRetencion], [s0].[Inside], [s0].[InstructionLevel], [s0].[IsCustomer], [s0].[IsDomiciled], 
[s0].[IsEmployee], [s0].[IsVendor], [s0].[LastDocumentNumber], [s0].[LastEmployeeDocumentType], [s0].[LastName1], [s0].[LastName2], [s0].[LicenseCondition], [s0].[LicenseExpirationDate], [s0].[LicenseLow], [s0].[Localite], 
[s0].[MarriedName], [s0].[MilitarDocument], [s0].[Name] AS [Name1], [s0].[Name1] AS [Name10], [s0].[Name2], [s0].[Nationality], [s0].[Ocupation], [s0].[Passport], [s0].[PercentPerceptionAgent], [s0].[PersonType], 
[s0].[ProfesionalStudiesCenterType], [s0].[Province], [s0].[Reference], [s0].[Region], [s0].[ReplicationUnit] AS [ReplicationUnit7], [s0].[Ruc], [s0].[Ruc1], [s0].[Ruc2], [s0].[Ruc3], [s0].[SecTelephone], [s0].[SectorId], 
[s0].[Sex], [s0].[Specialty], [s0].[Status] AS [Status1], [s0].[StreetName], [s0].[StreetType], [s0].[Telephone], [s0].[UserID], [s0].[VendorComission], [s0].[XLastDate] AS [XLastDate7], [s0].[XLastUser] AS [XLastUser7], 
[s0].[ZipCode], [s0].[ZonasId], [s0].[Zone], [s0].[ZoneName], [s0].[addressnumber2], [s0].[apple], [s0].[apple2], [s0].[codeLDN], [s0].[country2], [s0].[createDate], [s0].[creditline], [s0].[creditlinecurrency], 
[s0].[creditlineex], [s0].[creditlinelo], [s0].[department2], [s0].[indicator], [s0].[inside2], [s0].[isrecruiter], [s0].[issupervisor], [s0].[istrainer], [s0].[kilometer], [s0].[kilometer2], [s0].[localite2], [s0].[lot], 
[s0].[lot2], [s0].[observations], [s0].[province2], [s0].[reference2], [s0].[room], [s0].[room2], [s0].[shirtsize], [s0].[shoessize], [s0].[stage], [s0].[stage2], [s0].[streetname2], [s0].[streettype2], [s0].[trouserssize], 
[s0].[zone2], [s0].[zonename2], [p12].[ParteProduccionId], [p12].[Company] AS [Company8], [p12].[Currency], [p12].[FechaProduccion], [p12].[Numero], [p12].[NumeroLote], [p12].[Observacion] AS [Observacion1], [p12].[Person] 
AS [Person1], [p12].[PesoMateriaPrima1], [p12].[PesoMateriaPrima2], [p12].[PlantaId] AS [PlantaId0], [p12].[ReplicationUnit] AS [ReplicationUnit8], [p12].[Status] AS [Status2], [p12].[Total], [p12].[TotalEx], [p12].[TotalHoraEx], [p12].[TotalHoraLo], [p12].[TotalIndiEx], [p12].[TotalIndiLo], [p12].[TotalLo], [p12].[TotalProdEx], [p12].[TotalProdLo], [p12].[TurnoId] AS [TurnoId1], [p12].[XLastDate] AS [XLastDate8], [p12].[XLastUser] AS [XLastUser8], [p13].[ParteProduccionDetalleId] AS [ParteProduccionDetalleId0], [p13].[Cantidad] AS [Cantidad0], [p13].[Company] AS [Company9], [p13].[ControlAlmacen], [p13].[Currency] AS [Currency0], [p13].[EnvasadoraId], [p13].[FactorProducto] AS [FactorProducto0], [p13].[FechaVencimiento], [p13].[FormulaId] AS [FormulaId0], [p13].[FormulaVersionId], [p13].[MaquinaId] AS [MaquinaId0], [p13].[Merma], [p13].[NumeroBatch], [p13].[NumeroLote] AS [NumeroLote0], [p13].[Observacion] AS [Observacion2], [p13].[Omitir], [p13].[OrdenProduccionId], [p13].[Origen], [p13].[ParteProduccionId] AS [ParteProduccionId0], [p13].[PesoMateriaPrima], [p13].[PorDistribuye], [p13].[PorHumedad], [p13].[PorHumedadH], [p13].[PriceEx], [p13].[PriceKgEx], [p13].[PriceKgLo], [p13].[PriceLo], [p13].[ProductoId] AS [ProductoId2], [p13].[ProductoOrigenId], [p13].[ReplicationUnit] AS [ReplicationUnit9], [p13].[Total] AS [Total0], [p13].[TotalAdiEx], [p13].[TotalAdiLo], [p13].[TotalEnvEx], [p13].[TotalEnvLo], [p13].[TotalEx] AS [TotalEx0], [p13].[TotalHoraEx] AS [TotalHoraEx0], [p13].[TotalHoraLo] AS [TotalHoraLo0], [p13].[TotalIndiEx] AS [TotalIndiEx0], [p13].[TotalIndiLo] AS [TotalIndiLo0], [p13].[TotalLo] AS [TotalLo0], [p13].[TotalMpEx], [p13].[TotalMpLo], [p13].[TotalProdEx] AS [TotalProdEx0], [p13].[TotalProdLo] AS [TotalProdLo0], [p13].[TotalProdPEx], [p13].[TotalProdPLo], [p13].[TotalSubEx], [p13].[TotalSubLo], [p13].[TransactionId], [p13].[WareHouse] AS [WareHouse2], [p13].[WhareHouse], [p13].[XLastDate] AS [XLastDate9], [p13].[XLastUser] AS [XLastUser9]
    FROM [PP_Merma] AS [p5]
    INNER JOIN [PP_MermaDet] AS [p6] ON [p5].[MermaId] = [p6].[MermaId]
    INNER JOIN [PP_Equipo] AS [p7] ON [p5].[PlantaId] = [p7].[EquipoId]
    INNER JOIN [PP_Turno] AS [p8] ON [p5].[TurnoId] = [p8].[TurnoId]
    INNER JOIN [PP_Equipo] AS [p9] ON [p5].[EquipoId] = [p9].[EquipoId]
    INNER JOIN [PP_Producto] AS [p10] ON [p5].[ProductoId] = [p10].[ProductoId]
    INNER JOIN [WH_Item] AS [w0] ON [p10].[Item] = [w0].[Item]
    INNER JOIN [PP_TipoMerma] AS [p11] ON [p6].[TipoMermaId] = [p11].[TipoMermaId]
    LEFT JOIN [SY_Person] AS [s0] ON [p5].[Person] = [s0].[Person]
    LEFT JOIN [PP_ParteProduccion] AS [p12] ON (([p5].[PlantaId] = [p12].[PlantaId]) AND ((CONVERT(date, [p5].[Fecha]) = CONVERT(date, [p12].[FechaProduccion])) OR (CONVERT(date, [p5].[Fecha]) IS NULL AND CONVERT(date, [p12].[FechaProduccion]) IS NULL))) AND ([p5].[TurnoId] = [p12].[TurnoId])
    LEFT JOIN [PP_ParteProduccionDetalle] AS [p13] ON (([p12].[ParteProduccionId] = [p13].[ParteProduccionId]) AND ([p5].[EquipoId] = [p13].[MaquinaId])) AND ([p5].[ProductoId] = [p13].[ProductoId])
    WHERE [p5].[Indicador] = N'E'
) AS [t] ON ((([p].[PlantaId] = [t].[PlantaId]) AND ((CONVERT(date, [p].[FechaProduccion]) = CONVERT(date, [t].[Fecha])) OR (CONVERT(date, [p].[FechaProduccion]) IS NULL AND CONVERT(date, [t].[Fecha]) IS NULL))) AND ([p].[TurnoId] = [t].[TurnoId])) AND ([p0].[ProductoId] = [t].[ProductoId])
WHERE Convert(VARCHAR(6), [p].[FechaProduccion], 112) = 201911
ORDER BY [p2].[Descripcion], [p3].[Descripcion], CONVERT(date, [p].[FechaProduccion]), [p4].[Descripcion], [t].[MermaId0], [t].[Orden]

All fields are being used instead of those selected, in version 2.2.6 it did not happen.
in:
INNER JOIN [PP_Turno] AS [p4] ON [p].[TurnoId] = [p4].[TurnoId]
LEFT JOIN (
    SELECT [p5].[MermaId]

### Further technical details

EF Core version: 3.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Standard 2.0
Operating system: Windows 10x64
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment]
@smitpatel to respond.

**Comment by smitpatel** [comment]
Only particular selection which happened in 2.2 has some corner case bugs in certain case.
In 3.0+ we select all columns in the subquery but in final projection we only get columns which are required to generate result. So while the SQL is larger, it does not fetch any additional data.

**Comment by jonathanantoine** [comment]
Hello,

Does this not create some side effects like the one described on https://github.com/dotnet/efcore/issues/19826 ?
