### ISSUE TITLE
Seeding data in existing project

### ISSUE THREAD

**Issue by Christophe06410** [dotnet/efcore#19451]
Hello,

I have a project that is already running at different customer locations.
Basically, I have the following tables:
 - a Product table
 - a MenuEntry table
 - a Translation table

So I have a list of products and for each of them, a couple of translated strings in the Translation table (for english, french, german etc). 
Same thing for the menus displayed in the application (with translated texts in Translation table).
This means the Translation Table has a primary key and two foreign keys (one towards Product.ID and another one toward MenuEntry.ID).

So I have seed data, so far so good.
Now, customers have defined new products which created new rows in both Product and Translation tables. Fine.

Then, I need to update the application and add new Menu entries with corresponding translations.
The number of defined products is different at each customer site, so I don't know exactly what are the current Max(Translation.ID) there.
How do you use the seed HasData method to avoid the Duplicate Key exception in table Translation ?
My problem seems similar to this issue: https://github.com/aspnet/EntityFrameworkCore/issues/12324

Thank you for your help.

### Steps to reproduce

My stack trace is: 

> [SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Translation'. Cannot insert duplicate key in object 'dbo.Translation'. The duplicate key value is (1024).
The statement has been terminated.]
>    System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +212
>    System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +81
>    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +631
>    System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject > stateObj, Boolean& dataReady) +4222
>    System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) +953
>    System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) +304
>    System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +283
   > Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues) +870
   > Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) +40
   > Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) +40
   > Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection) +233
>    Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration) +191
>    Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade) +41
>    BeerService.Startup.Configuration(IAppBuilder app) +1587

### Further technical details

EF Core version: 2.2.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .Net Framework 4.6.2
Operating system: Windows 10 pro and Windows server 2012 R2
IDE: Visual Studio 2017 15.9.4

Thank you

**Comment by ajcvickers** [comment]
@AndriySvyryd to respond.

**Comment by AndriySvyryd** [comment]
@Christophe06410 If the PK is `int` then you can use negative values. Otherwise `HasData` is not a good way to do this.

**Comment by Christophe06410** [comment]
Thank you!
