### ISSUE TITLE
Join with DefaultIfEmpty on non-nullable (struct) property generates INNER JOIN

### ISSUE THREAD

**Issue by mqudsi** [dotnet/efcore#19456]
Similar to https://github.com/aspnet/EntityFrameworkCore/issues/13511 but with a `Join` rather than a `SelectMany`, using a join against a table with `DefaultIfEmpty` and a non-nullable struct as the the inner/outer key creates an `INNER JOIN` query rather than an `OUTER JOIN` query.

The non-nullable property that is used as the inner/outer join key has a converter to-and-from string.

```csharp
Ulid? graderId = null;
var response = await _db.Responses
    .AsNoTracking(!track)
    .Where(response => response.Id == responseId)
    .Join(_db.GradedSurveys.DefaultIfEmpty(),
        response => response.Id,
        gradedSurvey => gradedSurvey.ResponseId,
        (response, gradedSurvey) => new {
            Response = response,
            GraderId = gradedSurvey.GraderId
        })
    .Where(join => join.GraderId != graderId)
    .Select(join => join.Response)
    .OrderBy(r => r.Id)
    .FirstOrDefaultAsync(cancel)
    .ConfigureAwait(false);
```

The intention is to select records from `Responses` where there is no corresponding record in `GradedSurveys`. 

This expands to the following query:

```sql
SELECT "t0"."id", "t0"."date", "t0"."gradeId", "t0"."hash", "t0"."path", "t0"."subjectId", "t0"."surveyId", "t0"."teacherId", "t0"."id0", "t0"."date0", "t0"."jpegPath", "t0"."name", "t0"."pdfPath", "t0"."id00", "t1"."id", "t1"."index", "t1"."name", "t1"."surveyId", "t1"."text", "t1"."id0", "t1"."index0", "t1"."name0", "t1"."questionId", "t1"."text0"
FROM (
    SELECT "r"."id", "r"."date", "r"."gradeId", "r"."hash", "r"."path", "r"."subjectId", "r"."surveyId", "r"."teacherId", "s"."id" AS "id0", "s"."date" AS "date0", "s"."jpegPath", "s"."name", "s"."pdfPath", "t"."id0" AS "id00"
    FROM "responses" AS "r"
    INNER JOIN (
        SELECT "g"."id", "g"."flags", "g"."graderId", "g"."gradingTime", "g"."responseId", "g"."timestamp", "g"."id" AS "id0"
        FROM (
            SELECT NULL AS "empty"
        ) AS "empty"
        LEFT JOIN "gradedSurveys" AS "g" ON 1 = 1
    ) AS "t" ON "r"."id" = "t"."responseId"
    INNER JOIN "surveys" AS "s" ON "r"."surveyId" = "s"."id"
    WHERE ("r"."id" = @__responseId_0) AND "t"."graderId" IS NOT NULL
    ORDER BY "r"."id"
    LIMIT 1
) AS "t0"
LEFT JOIN (
    SELECT "q"."id", "q"."index", "q"."name", "q"."surveyId", "q"."text", "a"."id" AS "id0", "a"."index" AS "index0", "a"."name" AS "name0", "a"."questionId", "a"."text" AS "text0"
    FROM "questions" AS "q"
    LEFT JOIN "answers" AS "a" ON "q"."id" = "a"."questionId"
) AS "t1" ON "t0"."id0" = "t1"."surveyId"
ORDER BY "t0"."id", "t0"."id00", "t0"."id0", "t1"."id", "t1"."id0"
```

I believe this assumes that the intent is to *find* a matching record rather than exclude matching records and optimizes accordingly; I would have thought `DefaultIfEmpty` would have skipped that but it does not seem to.

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.Data.Sqlite
Target framework: 3.1
Operating system: Windows 10 x64
IDE: N/A

**Comment by smitpatel** [comment]
@mqudsi - Does this give incorrect results? Since you asked for Join with DefaultIfEmpty collection, we generate LeftJoin with Null to generate a DefaultIfEmpty and then inner join it with outer. The SQL is expected and correct.

**Comment by mqudsi** [comment]
Yes, the result is an empty set because records with an empty collection do not match at all.

**Comment by mqudsi** [comment]
The left join is fine, the first “inner join” is the issue.

**Comment by mqudsi** [comment]
Perhaps I am misunderstanding the intent of `DefaultIfEmpty()` here, or its virality? The missed records occur when there is a `Response` that has no `GradedSurvey` entries in its navigation property `GradedSurveys`.

In particular, for the data in question, the innermost query

```sql
SELECT "g"."id", "g"."flags", "g"."graderId", "g"."gradingTime", "g"."responseId", "g"."timestamp", "g"."id" AS "id0"
FROM (
    SELECT NULL AS "empty"
) AS "empty"
LEFT JOIN "gradedSurveys" AS "g" ON 1 = 1
```

produces the same results as a naive select:

```sql
SELECT "g"."id", "g"."flags", "g"."graderId", "g"."gradingTime", "g"."responseId", "g"."timestamp", "g"."id" AS "id0"
FROM gradedSurveys "g"
```

therefore the subsequent outer `LEFT JOIN` is effectively no different than if it were an `INNER JOIN` as the null values have already been excluded from propagating to this level.

**Comment by smitpatel** [comment]
>produces the same results as a naive select:

No, it does not. It produces the same result only when gradedSurveys table is not empty. When that table is empty then the result of first query is a row with all null values rather than 0 rows returned. Which is exactly same behavior as DefaultIfEmpty in LINQ.

- Your LINQ query does not match exactly with the SQL you have posted.
- If you want a left join then use actual left join. See https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#left-join

> The intention is to select records from Responses where there is no corresponding record in GradedSurveys.

Your LINQ query does not do that. Specifically, you need to write an actual Left Join as posted in doc above and then use a where predicate to filter out non-null matches.

**Comment by mqudsi** [comment]
That's fair enough. I ran into issues with SelectMany, but that's in the other issue. I'll close this one out.
