### ISSUE TITLE
Include not loading collections on queries containing sub-queries

### ISSUE THREAD

**Issue by seankanderson** [dotnet/efcore#19457]
Code first. All convention based entity relations. Everything works as expected except for this situation:

_context.Set<Invoice>().AsNoTracking()
.Where(i => i.InvoiceItems.Sum(x => x.ExtendedPriceWithTax) > i.InvoicePayments.Sum(z => z.Credit))
.Include(i => i.BillToCustomer)
.Include(i => i.InvoiceItems)
.Include(i => i.InvoicePayments).ToListAsync();

BillToCustomer is loaded.
InvoiceItems and InvoicePayments do not load.

If I drop the subquery (Where condition) this all works fine.  All includes load. I have also tried LinqKit Includes on the IQueryable--same effect. If I explicitly project and populate the Invoice with a Select then everything is loaded.

### Further technical details
![Annotation 2020-01-02 002547](https://user-images.githubusercontent.com/1112636/71652820-75e8f600-2cf6-11ea-9aaa-38a47eb16c25.png)

EF Core version: See attached image...
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.1.0
Operating system: Windows 10 18363
IDE: Visual Studio 2019 16.4.2

**Comment by smitpatel** [comment]
You are using mix of EF Core 3.0 & EF Core 2.2. Upgrade all EF Core related packages to 3.1.

**Comment by seankanderson** [comment]
> 
> 
> You are using mix of EF Core 3.0 & EF Core 2.2. Upgrade all EF Core related packages to 3.1.

Tried that. Throws me into a broken build hell and exposes me to other nastier known bugs.  Not something I want to revisit.  Does the provider (Sqlite 2.2.6) handle this implementation detail?

**Comment by seankanderson** [comment]
I enabled change tracking and it still failed to load the Includes.

**Comment by smitpatel** [comment]
> Does the provider (Sqlite 2.2.6) handle this implementation detail?

All the EF Core packages must be same version. So if you are using 2.2.6 then make sure all of them are 2.2.6, in your screenshot you are using EF Core 3.0. Mixing different package version is not supported.

It may or may not work in 2.2.6. At this point 2.2.6 is out of support. See https://dotnet.microsoft.com/platform/support/policy/dotnet-core
So even if it does not work in 2.2.6 we don't intend to fix it.

**Comment by seankanderson** [comment]
The SQLite 3.0 provider does not work with .NET Core 3.0.  I am on EntityFrameworkCore 3.0 except for the SQLite provider.  Can we get someone else to weigh in who knows the exact details of the implementation? If I upgrade the provider (which I cannot without breaking everything, or rolling back .NET Core to 2.X) is it really going to solve this issue?

**Comment by ajcvickers** [comment]
@seankanderson 

> The SQLite 3.0 provider does not work with .NET Core 3.0

`Microsoft.Data.Sqlite` and its associated ED provider are maintained by the EF team in this repo. If something isn't working here with 3.0/3.1, then please file a new issue so we can investigate.

If you're using some other SQLite provider, then it would be useful to know which one and why.

**Comment by seankanderson** [comment]
Seems this was resolved in 3.1.  In any case the advice is to separately query for Includes for performance reasons.  This appears to be a regression stemming from the query consolidation feature introduced in 3.0.  

https://github.com/aspnet/EntityFrameworkCore/issues/18098
