### ISSUE TITLE
Validation attributes of subclass affect base class

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#1946]
Hi.

I have the following entities in my model:

```
public class Person
{
  public int Id { get; set; }
  public virtual string Phone { get; set; }
}

public class Patient : Person
{
  [Required]
  public override string Phone { get; set; }
}
```

My model is configured to be TPT, I've added the following to my `DbContext`:

```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
  modelBuilder.Types().Configure(t => t.ToTable(GetTableName(t.ClrType)));
}
private string GetTableName(Type type)
{
  var pluralizationService = 
    DbConfiguration.DependencyResolver.GetService<IPluralizationService>();
  return pluralizationService.Pluralize(type.Name);
}
```

But when I add entities of type `Person` and call `context.GetValidationErrors()`, I see validation errors for those two properties, but I want them to be required only when the entity type is a `Patient`, why is it failing validation for a `Person` entity?

Any workarounds will be very appreciated as well.

Here's a screenshot of my debugger watch, please ignore the `BirthDate` property.

![Watch](https://camo.githubusercontent.com/c0609e6b9a511376b84c89df82e85d7f28a4fbab/687474703a2f2f692e696d6775722e636f6d2f6d676d333449582e706e673f32)

**Comment by ErikEJ** [comment]
Not sure that attributes are working (yet)

**Comment by weitzhandler** [comment]
I ended up leaving the property without the `RequiredAttribute`, and implementing the `IValidatableObject` on the `Patient` entity only. Not the nicest workaround, but it now works good.

**Comment by divega** [comment]
@weitzhandler Looks like you are actually describing an issue you found in EF6. If that is the case, this is a limitation of the way validation is implemented. In summary, the underlying EDM model used by EF6 to reason about the properties in the model does not have a way to represent property overrides. We are basically looking at the same property with the same validation attributes at all levels in the inheritance hierarchy. 

For what it is worth, in EF7 we don't plan to run data validation as part of `SaveChanges()` so validation will only happen at other layers, e.g. MVC, and that should follow with higher fidelity the attributes that you put in your types and their properties.

**Comment by weitzhandler** [comment]
@divega Thanks for your response, Diego.
Will the `GetValidationErrors` still exist? Or EF will stop using ANY involvement of validation?

**Comment by divega** [comment]
Currently we don't have plans to build data validation capabilities into DbContext. It is not as much a matter of priority as it is a matter of not being sure that DbContext is the right place for it. Your feedback on this would be very much appreciated.

**Comment by weitzhandler** [comment]
Truth is I'm not really sure. I think it IS effective the EF performs the validation, since it then avoids redundant round-trips to server when null, over length etc. etc.

I'd say the opposite, maybe MVC should be the one reading the errors from EF, but that's also too much of a hassle. So really I can't vote firmly for either side, I do like that the validation exists in EF as well, maybe just make the validation in EF optional.

**Comment by danda1man** [comment]
Was surprised to not see the validation on DbContext as I am investigating migrating a current project to EF7, but I think what @divega said makes send.  The MVC models already have input validations and if youare manually constructing your objects you should know the database limits so running extra validations in EF just slows things down.  99% of the time, the only time I would see a validation error was in development because I forget a field or misconfigured a relationship, but those errors never make it to prod.  I would vote leaving validation off EF
