### ISSUE TITLE
Scaffold-DbContext violates CA2227 rule

### ISSUE THREAD

**Issue by shadinamrouti** [dotnet/efcore#19482]
The generated code from `Scaffold-DbContext` for ICollection violates CA2227 rule.
See: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227?view=vs-2019

The solution is to remove the setter from the generated ICollection property.
E.g. 
`public virtual ICollection<SomeType> Something {get;set;}`
should become:
`public virtual ICollection<SomeType> Something {get;}`
because, according to Microsoft:

> A writable collection property allows a user to replace the collection with a completely different collection. A read-only property stops the collection from being replaced, but still allows the individual members to be set. If replacing the collection is a goal, the preferred design pattern is to include a method to remove all the elements from the collection, and a method to repopulate the collection. See the Clear and AddRange methods of the System.Collections.ArrayList class for an example of this pattern.

**Comment by ajcvickers** [comment]
@shadinamrouti It is very common to use collection properties with setters in .NET, and the code generated is such that it will be useful to many people. You are free to remove the setter if you don't want it; EF doesn't need it.
