### ISSUE TITLE
Method not found error when trying to make Groupby

### ISSUE THREAD

**Issue by rdstettler** [dotnet/efcore#19488]
I try to group a query like this

`var test = context.db.GroupBy(eq => eq.Name).Select(s => new { name = s.Key, number = s.Max(t => t.Value)});`

I get the error
'Method not found: 'System.Linq.Expressions.LambdaExpression Microsoft.EntityFrameworkCore.Internal.ExpressionExtensions.UnwrapLambdaFromQuote(System.Linq.Expressions.Expression)'

this however works fine
`var test = context.db.ToList().GroupBy(eq => eq.Name).Select(s => new { name = s.Key, number = s.Max(t => t.Value)});`

I have not found any other link to a same error with the UnwrapLambdaFromQuote.

bei Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.GetSelector(MethodCallExpression methodCallExpression, GroupByShaperExpression groupByShaperExpression)
   bei Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   bei System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   bei System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   bei Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   bei Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   bei System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   bei Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   bei Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   bei Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   bei Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
...
   bei Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   bei Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   bei Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   bei Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   bei Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

### Further technical details

EF Core version: 3.1.0
Database provider: Sql Server
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: VS Code

**Comment by ajcvickers** [comment]
@rdstettler This usually indicates a mix of packages from different EF Core releases. Make sure all packages are updated to the 3.1. release. If you still see errors, then please post your `.csproj` file so that we can look at the dependencies.

**Comment by rdstettler** [comment]
That was it! Thank you
