### ISSUE TITLE
Collection navigation property in owned type

### ISSUE THREAD

**Issue by GlumacP** [dotnet/efcore#19487]
I have an owned type that has navigation properties to other entities. When the navigation property is one-to-one everything works fine, but if the navigation property is one-to-many (without referencing the collection navigation property) or many-to-one, I get an error 'Unable to determine the relationship represented by navigation property ...' when trying to create an migration.

### Steps to reproduce

This a rough model.

``` C#
public class Parent
	{
		public long Id { get; set; }

		public OwnedType Owned { get; set; }
	}
	public class OwnedType
	{
		public long Id { get; set; }

		public ICollection<RelatedEntity> RelatedEntities { get; set; }
	}

	public class RelatedEntity
	{
		public long Id { get; set; }

		public OwnedType OwnedType { get; set; }

		public long OwnedTypeId { get; set; }
	}

	public class ParentConfig : IEntityTypeConfiguration<Parent>
	{
		public void Configure(EntityTypeBuilder<Parent> builder)
		{
			builder.HasKey(e => e.Id);

			builder.OwnsOne(e => e.Owned)
				.HasKey(o => o.Id);
		}
	}

	public class OwnedTypeConfig : IEntityTypeConfiguration<OwnedType>
	{
		public void Configure(EntityTypeBuilder<OwnedType> builder)
		{
			builder.HasKey(e => e.Id);

			builder.HasMany(e => e.RelatedEntities)
				.WithOne(r => r.OwnedType)
				.HasForeignKey(r => r.OwnedTypeId);
		}
	}

	public class RelatedEntityConfig : IEntityTypeConfiguration<RelatedEntity>
	{
		public void Configure(EntityTypeBuilder<RelatedEntity> builder)
		{
			builder.HasKey(e => e.Id);

			builder.HasOne(e => e.OwnedType)
				.WithMany(o => o.RelatedEntities)
				.HasPrincipalKey(o => o.Id);
		}
	}
```

PMC Output:
Unable to determine the relationship represented by navigation property 'AddressAbbreviation.Address' of type 'UserAddress'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'

### Further technical details

EF Core version: 2.2.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 2.2
Operating system: Windows 10 64-bit
IDE: Visual Studio 2017 15.9.18

**Comment by ajcvickers** [comment]
@GlumacP This is because using `IEntityTypeConfiguration` can only be used for non-owned types. See #15681. EF Core 3.1 generates a clearer exception message.
