### ISSUE TITLE
Delete unacceptable symbols from query parameter

### ISSUE THREAD

**Issue by AR1ES** [dotnet/efcore#19481]
I use obfuscator for my projects.
After obfuscation it replaces the property names with new ones, such as `#=zttCWVaE=`.

For statement `var properties = db.UsersPropertiesStore.FirstOrDefault(m => m.FormId == FormId);`
EF produces query like this `'SELECT ... ([u].[FormId] = @__#=zttCWVaE=_0)',@__#=zttCWVaE=_0 nvarchar(450)',@__#=zttCWVaE=_0=N'FormViewModel'`

This request is invalid because parameter contains unacceptable symbol `=`.

I think EF should delete all unacceptable symbols from query parameter names.

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by smitpatel** [comment]
@dotnet/efteam - What did we plan to do here?

**Comment by roji** [comment]
Who is doing the obfuscation here, i.e. rewriting the parameter names? Shouldn't it be the responsibility of that component to produce workable names?

**Comment by ajcvickers** [comment]
We discussed this again, and we don't think the value here is high enough to fix. This should only happen when the obfuscator (either intentionally or not) creates non-valid C# identifiers in the IL. The obfuscator should be configured to not do that.
