### ISSUE TITLE
ExecuteSqlInterpolatedAsync is not properly translating user-defined table types to SQL sproc

### ISSUE THREAD

**Issue by jwagstaff** [dotnet/efcore#19493]
Consider there is a simple user-defined table type that has one column of type `[int]` called `IdList`.

Now I have the following code to call a stored procedure that takes in 2 parameters: one of type `varchar(10)` and the other of type `IdList`. 

```
private static SqlParameter BuildIdListParam(string paramName, DataTable table)
        {
            return new SqlParameter(paramName, table)
            {
                TypeName = "IdList",
                SqlDbType = SqlDbType.Structured
            };
        }

public async Task<bool> UpdateTradesAsync(string vendorCode, IEnumerable<int> trades)
{

    var tvp = new DataTable();
    tvp.Columns.Add(new DataColumn("ID", typeof(int)));

    foreach (var tradeId in trades)
    {
        tvp.Rows.Add(tradeId);
    }

    var tradesParam = BuildIdListParam("trades", tvp);
                
    await _context.Database
        .ExecuteSqlInterpolatedAsync($@"EXECUTE dbo.Custom_UpdateVendorTrades 
            @vendorCode={vendorCode}, 
            @trades={tradesParam}");
}
```

When run with test inputs of a string vendor code and an enumerable containing {1, 2, 3), this throws a SqlException:
`Microsoft.Data.SqlClient.SqlException : Operand type clash: nvarchar is incompatible with IdList`

When I take a look at SQL profiler it looks like:
![profiler annotation](https://user-images.githubusercontent.com/43182979/71839713-6adcef80-3081-11ea-8732-baec970fd9b0.png)

Shouldn't the highlighted section above read: `@trades=@trades` ?

Is this a bug, or am I missing something here?

**Comment by ajcvickers** [comment]
@smitpatel @roji @maumar Thoughts here?

**Comment by smitpatel** [comment]
Possible that we just used whatever parameter name passed to us in SQL. (This is not entirely query pipeline so processing may ended up differing from FromSql).

We could fix it. We should also verify behavior of FromSql/Non-tvp parameters in ExecuteSql.

**Comment by smitpatel** [comment]
We pass in parameter name as is passed from customer (in fromsql too)
