### ISSUE TITLE
Seeding: Enable indexer properties to be seeded using concrete type

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19495]
Current code for concrete type does not deal with indexer properties.

**Comment by smitpatel** [comment]
cc: @AndriySvyryd

**Comment by AndriySvyryd** [comment]
Related: https://github.com/aspnet/EntityFrameworkCore/issues/9999

**Comment by smitpatel** [comment]
That would be further improvement. I ran into issue that we match based on memberInfo for concrete type which is violated for indexers. I think I have managed to fix it.
