### ISSUE TITLE
Enable-migrations error

### ISSUE THREAD

**Issue by 613038475** [dotnet/efcore#1950]
When executing migrations commands such as `Enable-Migrations`, `Add-Migration`, etc. the following error is encountered.

> Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully qualified file name must be les
> s than 260 characters, and the directory name must be less than 248 characters."

The issue is due to a NuGet bug which is tracked by https://github.com/NuGet/Home/issues/528. 
## :star2: Workarounds :star2:
- :star: **Install an updated NuGet client that resolves this issue** https://nuget.codeplex.com/releases/view/615507
- As a workaround, you can download [this patched version of EntityFramework.psm1](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=entityframework&WorkItemId=2743&FileAttachmentId=1454797), copy it into the `packages\EntityFramework.6.1.3\tools` directory, restart Visual Studio, and try again. 
- An alternate workaround is to unload other projects that reference Entity Framework (so that the only loaded project that references Entity Framework is the one that contains your EF model).
## Details

Full details of the error are...

```
Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully qualified file name must be les
s than 260 characters, and the directory name must be less than 248 characters."
At D:\helloworld\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-Path $ToolsP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException

You cannot call a method on a null-valued expression.
At D:\helloworld\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "CreateInstanceFrom" with "8" argument(s): "The specified path, file name, or both are too long. The fully qualified file name m
ust be less than 260 characters, and the directory name must be less than 248 characters."
At D:\helloworld\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
```

No path is longer than 200 on my harddisk, so I can't understand why this problem will happen.

**Comment by mrchief** [comment]
This also happens when I tried to upgrade from 6.1.1 -> 6.1.3. I even moved my git repo to c: to gain few extra chars but to no avail.

**Comment by mrchief** [comment]
This seems to happen only in VS 2015 (RC) which makes me believe its more of a new NuGet issue. VS 2013 (Update 4) doesn't have this. Installation went fine. And Enable-Migrations also seem to be working fine.

**Comment by NooNameR** [comment]
if create new project, all are fine, with my which worked in VS2013, in VS2015RC same error.

**Comment by unt1tled** [comment]
Same issue here.

**Comment by divega** [comment]
Everyone, thanks for reporting this. 

It seems we'll need more details to be able to repro and forward the information to the NuGet folks, E.g. was yours a clean setup of Visual Studio 2015 RC or an upgrade form a previous preview? 

cc @yishaigalatzer

**Comment by unt1tled** [comment]
I had uninstalled CTP 6 to install the 2015 RC. 

Also tried to no avail:
- Repairing 2015 RC install
- Deleting packages dir
- Uninstalling nuget extension and reinstalling from https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d
- Deleting nuget dirs from AppData  (http://stackoverflow.com/questions/27377094/cannot-be-installed-nuget-package-in-vs2015)
- Downgrading to earlier entity framework versions (http://stackoverflow.com/questions/30020239/ef6-migrations-stopped-working-on-vs-2015-rc)

Works from VS 2013.

**Comment by brendangreen** [comment]
@divega 

Having same issue, in multiple environments.

  1. Windows 10 Preview, Build 10074, where VS 2015 was initially the CTP and upgraded all the way to the RC.
  2. Windows 8.1, where VS 2015 RC was installed clean, with VS 2013 also present on the machine.

Solution was targeting .net 4.5.1, and I also changed it to 4.6, did not resolve the issue.

The project was using Entity Framework 6.1.3, but I have also tried downgrading to 6.1.2, 6.1.1 and 6.1.0 (to at least add a migration to the project) but I continue to get the same error.

Error from running **Add-Migration**:

> New-Object : The value supplied is not valid, or the property is read-only. Change the value, and then try again.
At C:\Users\bgreen\Source\Paygle\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:757 char:13
+     $info = New-Object System.AppDomainSetup -Property @{
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Object], Exception
    + FullyQualifiedErrorId : SetValueException,Microsoft.PowerShell.Commands.NewObjectCommand
 
> The property 'PrivateBinPathProbe' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\bgreen\Source\Paygle\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:772 char:9
+         $info.PrivateBinPathProbe += ';lib\net45'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
> Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 
248 characters."
At C:\Users\bgreen\Source\Paygle\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-Path $ToolsP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 
> You cannot call a method on a null-valued expression.
At C:\Users\bgreen\Source\Paygle\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
> Exception calling "CreateInstanceFrom" with "8" argument(s): "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be 
less than 248 characters."
At C:\Users\bgreen\Source\Paygle\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException

**Comment by hcavazin** [comment]
Same issue here.

**Comment by yishaigalatzer** [comment]
What are the project types you are using? Can someone share a repro project?

**Comment by hcavazin** [comment]
https://github.com/hcavazin/vs2015err
Very simple. Just run "Enable-Migrations" to see errors.
I noticed that the error message is not always the same.

**Comment by ryan-codingintrigue** [comment]
Same issue here when running `Add-Migration`. Simple class library which was on EF6.1.2, upgraded to 6.1.3 and received lots of these errors.

I upgraded to VS2015 RC from CTP6. Windows 7 Enterprise SP1 (x64) machine.

Should be noted that I tried uninstalling & re-installing EF6.1.3 and I get these errors during the installation process too:

> Exception calling "CreateInstanceFrom" with "8" argument(s): "The specified path, file name, or > both are too long. The 
> fully qualified file name must be less than 260 characters, and the directory name must be less > than 248 characters."
> At X:\MyProjectName\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 > char:5
> +     $domain.CreateInstanceFrom(
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : PathTooLongException

**Comment by ilmax** [comment]
Same issue here

**Comment by divega** [comment]
Thanks everyone. @bricelam and @emgarten investigated and found the root cause. More details in https://github.com/NuGet/Home/issues/528.

**Comment by NooNameR** [comment]
@divega can u make an example how to fix it?

**Comment by divega** [comment]
Ultimately the fix will have to go in NuGet bits. 

Since the scenario that is broken is when the solution contains multiple projects with references to the same EF package, I suspect if you temporarily unload projects until only one loaded project in the solution references the EF package, that might help as a workaround. I haven't had a chance to verify this myself yet though.

**Comment by NooNameR** [comment]
for a now i fixed that error in this way: i go to Manager Nuget, delete from all projects inside my solution EF, and where is a main project with Code First i Install nuget 6.1.3, inside all others i add a Reference: System.Data.Entity, and pick with "quick fix" reference: "EntityFramework", and now all are worked, i can add an migration and all other.

**Comment by rgripper** [comment]
@divega I confirm, unloading other projects using EF makes (at least) migrations commands work again.

**Comment by bricelam** [comment]
As a workaround, you can download 
[this patched version of EntityFramework.psm1](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=entityframework&WorkItemId=2743&FileAttachmentId=1454797), copy it into the `packages\EntityFramework.6.1.3\tools` directory, restart Visual Studio, and try again.

**Comment by hcavazin** [comment]
If comment line  `<package id =" EntityFramework "version =" 6.1.3 "targetFramework =" net46 "userInstalled =" true "/>` in "packages.config" of other projects already solved.

**Comment by imarrero** [comment]
You ALL are TERRIFIC!!  - Thank you very much for your effort
Yes @bricelam 's workaround works like a charm.

Thanks.

**Comment by yishaigalatzer** [comment]
@bricelam  :heart:

**Comment by brendangreen** [comment]
@bricelam worked a treat.  Really appreciate it!

**Comment by rgripper** [comment]
bricelam's script is not signed, don't forget to unblock it and probably even do
(admin cmd)> powershell Set-ExecutionPolicy Unrestricted
while its not completely fixed, to allow execution in Package manager console

**Comment by ilmax** [comment]
:thumbsup: for @bricelam, your workaround works like a charm, thank you!

**Comment by divega** [comment]
NuGet/Home#528 has been fixed (thanks @yishaigalatzer and @AndriySvyryd) so the workaround should become unnecessary the next time NuGet clients is refreshed.

**Comment by mrchief** [comment]
:+1: For such quick turnaround!

**Comment by sebrojas14** [comment]
When is gonna be refreshed the NuGet client? I have this problme today

**Comment by sebrojas14** [comment]
Going back to Visual Studio Community 2013...

**Comment by brendangreen** [comment]
@sebrojas14 or....you could use the workaround that was posted by @bricelam.

**Comment by yishaigalatzer** [comment]
We just dropped a new nuget client on codeplex https://nuget.codeplex.com/releases/view/615507 give it at try

**Comment by Casimodo72** [comment]
@yishaigalatzer, great! Using NuGet 3.0 RC2 heals the issue. Actually this problem held me away from moving from VS 2013 to VS 2015 RC.

**Comment by rowanmiller** [comment]
@Casimodo72 thanks for confirming!

I've added the updated client to the list of workarounds

**Comment by sebrojas14** [comment]
Nice to know, but I already dongrade my company PCs to VS 2013. Maybe I will wait until stable release came, vecause uninstall, download and install its a long process

**Comment by divega** [comment]
@sebrojas14 for sure waiting for the stable release of VS 2015 is reasonable, but if you want to continue trying the pre-release version, it should actually work side-by-side with VS 2013 on the same PC.

**Comment by yishaigalatzer** [comment]
And of course if you find more bugs there is still some time to fix them

**Comment by mafshin** [comment]
@bricelam solution worked in VS 2015 RC - Need to Unblock the file if it's replaced.

**Comment by jkmuka** [comment]
I am getting this error on VS2015 RC and the workarounds have not worked. I have found that the error occurs when you have multiple projects referencing EF. So I have a DataContext project with EF 6.1.3, then I have a client project(console, unit test, web, etc.) that references the DataContext project and EF 6.1.3. If I remove the client project from the solution the error goes away. Someone correct me if I am wrong, but I don't think this is a viable workaround. When you have a project that references your DataContext project it also needs the EF reference. Also when I try the workaround to use the patched psm file I get this "Import-Module : File ..\EntityFramework.6.1.3\tools\EntityFramework.psm1 cannot be loaded. The file 
...\EntityFramework.6.1.3\tools\EntityFramework.psm1 is not digitally signed. You cannot run this script on the current system. For 
more information about running scripts and setting execution policy, see about_Execution_Policies "

**Comment by Arser** [comment]
Having the same issue with Visual Studio 2013 Update 5. Any fix avl. for that?

**Comment by maartenba** [comment]
Similar issue: https://github.com/NuGet/NuGetGallery/issues/2592

**Comment by weitzhandler** [comment]
Still having the same issue. VS2015 on a new project of ASP.NET 4 MVC 5.2, trying to call *Enable-Migrations*. This is unbelievable. It's like the ASP.NET dropped the support for the released version focusing on the unreleased beta.
I tried the workaround of the [first post](https://github.com/aspnet/EntityFramework/issues/1950#issue-65169768) - none worked. I have a solution that contains a single project.

**Comment by brendangreen** [comment]
@weitzhandler - which workaround?  The new nuget, or the patches psm1?

**Comment by weitzhandler** [comment]
Both. I have the latest NuGet (3.2), and tried replacing the psm1 file. Neither worked.

**Comment by brendangreen** [comment]
Post your error message.  It's possible that there may be a different issue?
On 25/09/2015 11:17:53 AM, Shimmy <notifications@github.com> wrote:
Still having the same issue. VS2015 on a new project of ASP.NET 4 MVC 5.2, trying to call Enable-Migrations. This is unbelievable. It's like the ASP.NET dropped the support for the released version focusing on the unreleased beta.
I tried the workaround of the first post [https://github.com/aspnet/EntityFramework/issues/1950#issue-65169768] - none worked. I have a solution that contains a single project.

**Comment by weitzhandler** [comment]
@brendangreen 
This was all brought above but to make you happy here you go:

    enable-migration : The term 'enable-migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
    was included, verify that the path is correct and try again.
    At line:1 char:1
    + enable-migration
    + ~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (enable-migration:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException

BTW, all the related EF commands (i.e. get-help entityframework) don't work either.

**Comment by brendangreen** [comment]
When I was using the work around, I had to Import-Module the psm1 file.  You did that?

**Comment by weitzhandler** [comment]
@brendangreen 
Well after explicitly uninstalled EntityFramework (`Uninstall-Package EntityFramework`) and reinstalled it it works now.

**Comment by Gillardo** [comment]
Anyone else still getting this problem?  I have created a new ASP.NET 5 solution with 5 different projects, one is using EntityFramework 6.1.3 and is being referenced by the other projects.  If i try to do ```enable-migrations``` i just get this error

```
enable-migrations : The term 'enable-migrations' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ enable-migrations
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (enable-migrations:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I have tried uninstalling and reinstalling EntityFramework, but still doesnt work?

**Comment by rowanmiller** [comment]
@Gillardo If you are using ASP.NET 5 then the PowerShell commands do not work (due to limitation in the ASP.NET 5 project system). You need to drop out to the command line, see here for more details http://ef.readthedocs.org/en/latest/getting-started/aspnet5.html#create-your-database.

**Comment by Gillardo** [comment]
This is referencing EF7, not EF6.  I managed to get round this, by creating a .csproj for my EF6 project, and then added all the files from my .xproj, by using the "Add By Link" option.  This way i havent got 2 copies of the files.  Now using my .csproj i can run all my commands for EF6, and when i build my .xproj i have the latest versions etc.

But support for EF6 natively in .xproj would be great

**Comment by rowanmiller** [comment]
Ah, sorry I missed that. The same limitation holds true (as you discovered). Sounds like you have the right work around for the moment.

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by amirhaghajani** [comment]
in package manager console
Import-Module (your project path)\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1
