### ISSUE TITLE
Different Configuration For InMemory Provider

### ISSUE THREAD

**Issue by Cooksauce** [dotnet/efcore#19501]
Say I want to use a provider specific configuration for a property. Is there any way to provide an alternative configuration so I can test the `DbContext` with the InMemory provider.

Example:
```
class Post
{
     public long Id { get; set; }
     public MetaData Metadata { get; set; }
}

class MetaData
{
     public string Name { get; set; }
     public string SomethingElse { get; set;}
}

class PostConfig : IEntityTypeConfiguration<Post>
{
     public void Configure(EntityTypeBuilder<Post> builder)
     {
          builder
               .Property(x => x.Metadata)
               .HasColumnType(nameof(NpgsqlDbType.Jsonb).ToLowerInvariant());
     }
}
```

Leads to this exception when creating an InMemory db context:
`System.InvalidOperationException : The property 'Post.Metadata' is of type 'MetaData' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

Is there anyway to get around this? Is there some way to have only EF In Memory ignore it?

**Comment by ajcvickers** [comment]
@Cooksauce You can use `context.Database.IsInMemory()` while building the model. You'll have to flow it into your `IEntityTypeConfiguration` instances.

**Comment by Cooksauce** [comment]
@ajcvickers I see. Follow up question:

On this method in the `ModelBuilder` class:
`public virtual ModelBuilder ApplyConfigurationsFromAssembly([NotNullAttribute] Assembly assembly, [CanBeNullAttribute] Func<Type, bool> predicate = null);`

Is the `Type` passed to the predicate the configuration or the entity? In other words, if I wanted to filter out the configuration above, should my predicate be:
`Func<Type, bool> = type => type != typeof(PostConfig)`
OR:
`Func<Type, bool> = type => type != typeof(Post)`

Thanks in advance

**Comment by ajcvickers** [comment]
@Cooksauce I don't remember. Give it a try and see what you find out.
