### ISSUE TITLE
Query: Deal with same querycontext parameter having multiple inferred type mapping

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19503]
```C#
var city = "Settle";
cs.Where(c => c.City == city || c.Address.Contains(city)).ToList();
```
In above query we have only 1 query context parameter for city but in SQL, city could take different inferred type mapping. We need to determine what should we do with such cases especially if one mapping is unicode and other is not.
It also intersect with the fact that currently we have 1 to 1 mapping between query context parameters and relational parameters which we can relax and use for https://github.com/aspnet/EntityFrameworkCore/issues/17948

**Comment by smitpatel** [comment]
Proposal: Break `IRelationalParameter` interface and expose TypeMapping.
- Each relational parameter needs to have type mapping assigned to it for us to generate the DbParameter.
- Each relational parameter is different from other if it is taking value of a different client side parameter or it has different typemapping then other relational parameter taking same client side value.

**Comment by ajcvickers** [comment]
@smitpatel Design meeting?

**Comment by smitpatel** [comment]
Didn't need breaking changes like above if we cleaned up the parameters we have atm. The design is in PR.
