### ISSUE TITLE
[Discussion] Moving EntityFrameworkCore repo to dotnet org 2020-01-07

### ISSUE THREAD

**Issue by Pilchie** [dotnet/efcore#19512]
As a first step towards the work describe [here](https://github.com/dotnet/announcements/issues/127), we're planning on migrating the EntityFrameworkCore repo to the dotnet org and renaming it to "efcore". We'd like to get this done ASAP.

We don't expect any significant issues for contributors, GitHub is great about adding redirects. However, it may impact our ability to produce nightly builds and flow dependencies for a few days.

Please let us know if you run into any other issues.

**Comment by Pilchie** [comment]
The move and rename are complete - still need to get builds and dependency flow working.

**Comment by roji** [comment]
dotnet/efcore is *so* much better than aspnet/EntityFrameworkCore! Any plans on doing the same for aspnet/EntityFramework.Docs?

**Comment by Pilchie** [comment]
At some point we'd like to migrate the docs repos as well, but I'll leave timing/planning to @Rick-Anderson and @scottaddie for that one.  We happened to have a good time to do it for the source repos yesterday so we jumped on it.

**Comment by Pilchie** [comment]
This is done now.
