### ISSUE TITLE
Query: Nested InvocationExpression may not work

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19511]
Looking at https://github.com/aspnet/EntityFrameworkCore/issues/17791#issuecomment-571645107
and source code, we may not be expanding nested invocation expression. We should add a regression test for it. (And fix it in the process if not working, should be easy one liner).

**Comment by GiannisParaskevopoulos** [comment]
Hi, is it possible to see this fix on ef 3.1.0?

**Comment by ajcvickers** [comment]
@GiannisParaskevopoulos See the [release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for general information on how we determine which issues to patch for. Please post details on how this bug specifically is impacting your application.

**Comment by GiannisParaskevopoulos** [comment]
@ajcvickers Hi and thanks for your response. I guess, I'll have to wait until November.... After all, i do have a workaround.

**Comment by merrycoder** [comment]
@GiannisParaskevopoulos may I ask what workaround you have for this issue?

**Comment by merrycoder** [comment]
@ajcvickers this bug blocks us from migrating from 2.2 to 3.1 as we extensively use the [PredicateBuilder ](http://www.albahari.com/nutshell/predicatebuilder.aspx) in our search algo. We don't plan to migrate to 5.0 as it's not going to be a LTS version, so our next upgrade will be 6.0. I would immensely appreciate a fix in 3.1, if there is no workaround available for this issue.

**Comment by MTrachsel** [comment]
@GiannisParaskevopoulos any chance you could share the workaround with us?

**Comment by smitpatel** [comment]
Updated milestone to 3.1.9. The fix for this will be available in EF Core 3.1.9 or higher & EF Core 5.0 preview1 or higher release.
