### ISSUE TITLE
Skip/Take silently removes joins from generated query

### ISSUE THREAD

**Issue by Atee134** [dotnet/efcore#19523]
I'm experiencing a strange bug(?) where if I call skip/take on a query before evaluation, the result will have the navigation properties as null, despite being included.
I've checked the generated SQL query, the join statements are indeed excluded in case of a skip take.

### Steps to reproduce

I've made a simplified project demoing the issue that I've attached, but I will try to describe it here as well.

First, the entities:
``` C#
    public class Dog
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ParentName { get; set; }

        public OwnerId OwnerId { get; set; }

        public List<Toy> Toys { get; set; }
    }

    public enum OwnerId
    {
        Bob,
        Joe
    }

    public class Toy
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int DogId { get; set; }
        [ForeignKey("DogId")]
        public Dog Dog { get; set; }
    }
```

Dogs are related to each other in a tree structure, but there are separate tree structures per owner. (In the example I didn't bother to make trees, just random graphs, as it's not important)

I want to get a list of dogs, with their navigation properties and parents filled, also I want to apply filtering for both the dogs and/or the parent (filtering is not included in the example).

The problematic query:
``` C#
..
        class DogTuple
        {
            public Dog Dog { get; set; }
            public Dog Parent { get; set; }
        }
..

            IQueryable<Dog> dogQuery = context.Dogs
                .Include(d => d.Toys);

            IQueryable<DogTuple> query = from dog in dogQuery
                                         join parent in context.Dogs on new { name = dog.ParentName, ownerId = dog.OwnerId } equals new { name = parent.Name, ownerId = parent.OwnerId }
                                            into queryResult
                                            from parent in queryResult.DefaultIfEmpty()
                                            select new DogTuple { Dog = dog, Parent = parent };

            if (evaluateBeforeSkipTake)
            {
                var whatever = await query.ToListAsync();
            }

            query = query.Skip(10).Take(10);

            var result = await query.ToListAsync();
```

if we evaluateBeforeSkipTake then the result will have the Toys navigation properties filled, but if we 
execute skip/take first, then evaluate, then all Toys navigation properties will be null.
In 2.2 the navigation properties are filled in both cases.

I agree that this is a bit twisted query, but we have a lot of navigation properties included, and couldn't think of any other way to query all these data in one query, though I'm open for suggestions on better alternatives.

Working example:
https://github.com/Atee134/efcore_skiptakebug_demo
Just start the application and open:
https://localhost:44380/test?evaluateBeforeSkipTake=false
https://localhost:44380/test?evaluateBeforeSkipTake=true

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.4.2

**Comment by maumar** [comment]
works on current master, probably fixed by one of the recent include improvements
