### ISSUE TITLE
Unable to form nuget packages when referencing latest EntityFrameworkCore 3.1.0 libraries

### ISSUE THREAD

**Issue by AlexEngblom** [dotnet/efcore#19542]
Not sure if this is the correct platform for this issue as it's more about the release package than the solution itself, but here we go:

### Problem
NuGet pack does not work if we include files with too old or no LastWriteTime as discussed in the linked issue below.

Latest 3.1.0 entity framework core libraries have assemblies where LastWriteTime falls into this category, which blocks us from creating nuget packages if we reference latest efcore.

### Root cause
There's an open issue in NuGet https://github.com/NuGet/Home/issues/7001 , but since it's been open for so long with no actions taken I suppose it's not going anywhere anytime soon.
This is why I hope it can be resolved in this end, because currently we need to reference older 3.0.0 packages or make a hack in the CI-pipeline to bump the file write timestamps...

### Steps to reproduce
Add references to the latest 3.1.0 Microsoft.EntityFrameworkCore libraries in your net core project and try to run NuGet pack. You will get error from NuGet stating 'The DateTimeOffset specified cannot be converted into a Zip file timestamp.'

At least these 3.1.0 assemblies cause issues for NuGet packaging:

Microsoft.EntityFrameworkCore.Abstractions.dll
Microsoft.EntityFrameworkCore.dll
Microsoft.EntityFrameworkCore.Relational.dll
Microsoft.EntityFrameworkCore.SqlServer.dll

**Comment by ajcvickers** [comment]
@dotnet/aspnet-build Is "files with too old or no LastWriteTime" a known issue with the assemblies we build?

**Comment by dougbu** [comment]
This does sound like NuGet/Home#7001 but I thought we caught that in our builds prior to the 3.1.0 release. @rrelyea am I misremembering the timing?

May overlap dotnet/aspnetcore#18273 though that's a repo build issue.

**Comment by Pilchie** [comment]
I don't remember exactly for efcore, but for aspnetcore, we thought we fixed it but IIRC it turned out that the SDK we used to build 3.1 was too old. I believe this is fixed in the next servicing build to be released.

**Comment by ajcvickers** [comment]
@AlexEngblom EF Core 3.1.1 is now on NuGet. Can you check to see if it still has this issue?

**Comment by tthiery** [comment]
@ajcvickers I can report in that version 3.1.1 resolved my referenced issue #19576

**Comment by AlexEngblom** [comment]
@ajcvickers I can confirm the new release fixed the issues in our case as well, thank you!
