### ISSUE TITLE
EF InMemory database is shared between tests on Linux but not Windows or Mac

### ISSUE THREAD

**Issue by wizofaus** [dotnet/efcore#19544]
I have a class with a number of integration tests (Xunit) all using TestServer, and overriding the DbContextOptions dependency injections to do UseInMemoryDatabase instead of the regular UseSqlDatabase. All the tests use the same *name* for the in-memory database. On Windows and Mac this is fine - because each test has its own TestServer and ServiceProvider context, each in-memory database is totally unique and is empty at the beginning of the test.
But under linux, this is NOT true - the database still contains records from previous tests!
I have to remove all existing database records first for my test to work (it's actually 100% reliable - the test runs fine on its own, but fails when run as part of the full suite, if I don't add the code to remove the existing records).
I tried upgrading to .NET 3.1, but this made no difference. The .NET runtime version is 2.1, using Xunit 2.4.1.

**Comment by vasont** [comment]
Is that true? I thought we had to use a Guid.NewGuid().ToString() for a name (aka a globally unique name) in order to ensure our InMemory EF context was unique on our Windows runs. We want our tests to have a unique instance of the "database" for the test.

**Comment by wizofaus** [comment]
> Is that true? I thought we had to use a Guid.NewGuid().ToString() for a name

Yes, if all the tests use the same (default) service provider. But not if they each have their own TestServer instance and you use the service provider from that.

**Comment by ajcvickers** [comment]
@wizofaus 

> because each test has its own TestServer and ServiceProvider context, each in-memory database is totally unique and is empty at the beginning of the test

Whether or not this is true depends on which "ServiceProvider" you are talking about. The default experience should be a shared in-memory database, on both Windows and Linux. See #9613 for more details. If you're seeing different instances, then that usually means that each test is getting a new EF internal service provider.

**Comment by wizofaus** [comment]
I just confirmed with this bit of code that it works as expected on Windows. I'm trying to get access to linux instance to test on:

```using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Xunit;
using Microsoft.AspNetCore.TestHost;

public class Widget
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class MyContext : DbContext
{
    public MyContext(DbContextOptions<MyContext> options) : base(options) { }
    public DbSet<Widget> Widgets { get; set; }
}

public class FooTests
{
    public FooTests()
    {
        var builder = new WebHostBuilder().Configure(_ => { })
            .ConfigureServices(sc =>
            {
                sc.AddDbContext<MyContext>(o => o.UseInMemoryDatabase("Test"));
                sc.AddScoped<MyContext>();
            });
        server = new TestServer(builder);
    }
    [Fact]
    public void Test1_ShouldSucceed()
    {
        using (var scope = server.Host.Services.CreateScope())
            using (var context = scope.ServiceProvider.GetRequiredService<MyContext>())
            {
                Assert.Empty(context.Widgets);
                context.Add(new Widget { });
            }
    }
    [Fact]
    public void Test2_ShouldSucceed()
    {
        Test1_ShouldSucceed();
    }
    readonly TestServer server;
}
```

**Comment by wizofaus** [comment]
>  See #9613 for more details. 

I just read that issue - so is ensuring each test has its own InMemoryDatabaseRoot the best solution?

**Comment by ajcvickers** [comment]
@wizofaus If your intention is to isolate each test from the others, then yes.

**Comment by wizofaus** [comment]
Cool thanks - but why the difference between Windows and Linux I wonder?

**Comment by ajcvickers** [comment]
@wizofaus There should be no difference. If you can provide a repro, then I would like to understand the root cause.

**Comment by wizofaus** [comment]
@ajcvickers  I provided a class above you can add to a standard dotnet xunit project if you have access to a linux node to run on (I do but it's a bit tricky from home, might have to wait till I'm next in the office).

**Comment by wizofaus** [comment]
Ok so I finally discovered the key difference, which is that where it's failing I'm actually using:
```
                sc.AddTransient(provider => new DbContextOptionsBuilder<MyContext>().UseInMemoryDatabase("Test").Options);
```
in `ConfigureServices()` instead of `AddDbContext( )`.

Once I do that I definitely observe that the in-memory database is shared between tests - but it happens on Windows too, even though that didn't seem to be what I was observing previously.
However I think I have an explanation for that - which is that my Asserts that should have been failing were inside an async lambda that had been assigned to an Action - and this definitely behaves differently between Linux and Windows (on the former the xUnit test runner seems to hang, on the latter, the tests simply pass as though the asserts had never occurred).

**Comment by wizofaus** [comment]
@ajcvickers - I'm happy to close this now that I've better understood what's happening, I understand that `AddDbContext` is the preferred mechanism for configuring a DbContext-derived class for DI but in my case I'm developing an independent module that is supposed to be able to do its own DI independent configuration and I couldn't make AddDbContext work quite the way I wanted to, as it only accepts an DbContextOptionsBuilder, and I can't see any straightforward way of overriding its behaviour in a test yet.
