### ISSUE TITLE
 No suitable constructor found for entity type 'Func<ConstructorInfo, bool>' for inheritance entity

### ISSUE THREAD

**Issue by baoduy** [dotnet/efcore#19557]
I got an issue as below when added inheritance entity to EfCore. However, the migration is fine if remove the inheritance classes.

`No suitable constructor found for entity type 'Func<ConstructorInfo, bool>'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'object', 'method' in 'Func<ConstructorInfo, bool>(object object, IntPtr method)'.`

Thanks
Duy

**Comment by ajcvickers** [comment]
@baoduy Please post a small, runnable project that reproduces the behavior you are seeing so that we can investigate.

**Comment by baoduy** [comment]
Sorry, I found an issue with my entity which causing this exception. However, it really helps to investigate faster if the exception message provides more details on the entity name or construction name.

**Comment by ajcvickers** [comment]
@baoduy See #17010 and #19383
