### ISSUE TITLE
Log total number of SQL queries for asp.net request

### ISSUE THREAD

**Issue by benmccallum** [dotnet/efcore#19558]
I'm wondering if it's possible (built-in or with some suggestions from the team) to write out a log of the total count of queries fired to the DB when handling an asp.net request. 

Reason being, I'm currently debugging performance issues in a graph scenario, and I suspect the resolvers are suffering an N+1 problem and firing tonnes of DB queries to the server. Something I can fix easily enough with the dataloader concept, but I'd love it if I could just plug-n-play a logger that goes, "Hey, that request just fired 100 queries to the DB, here's a warning/error that you've done something wrong". 

If there's nothing out-of-the-box, I'm thinking I could inject a per-HTTP-request dependency that is thread-safe, which is my tallier, and then if I can hook in to the DbDontext execution somewhere I could call into that tallier and +1 onto the tally. 

Any suggestions welcome! I'll open-source it as a NuGet package if I come up with something decently pluggable.

**Comment by benmccallum** [comment]
Or maybe I can provide a loggerfactory that spawns a logger that has an overloaded log method that finds the logs related to a Query (`DbLoggerCategory.Query`?) and can do the tallying.

I know I can just setup standard logging and then do a count in the text for that category, but was looking for something a little easier and quicker to monitor regularly.

**Comment by ErikEJ** [comment]
Run a profiler on the database server???

**Comment by benmccallum** [comment]
Yea I think that's the way to go for debugging my current perf issues; I'll definitely do that.

I guess the logging technique is nice because it can yell at me in logs if we accidentally get ourselves in the same way again. 

I've just realised though that in our case (GraphQL service fronting microservices, fun!) that I could be better off counting the number of requests going out to those microservices.

That being said, the initial idea (for those who aren't doing microservices) is sound. But perhaps if they just look at the logs and see tonnes of queries being logged in there per api call, that's enough to see an issue. 

Happy to close.

**Comment by ilmax** [comment]
Actually miniprofiler can also display you the query that the context run for every single request, may this fits your needs?

**Comment by ajcvickers** [comment]
@benmccallum If you're using the default context-per-request, then something like this, maybe?

```C#
public class CountingCommandInterceptor : DbCommandInterceptor
{
    public int QueryCount { get; set; }
    
    public override DbDataReader ReaderExecuted(DbCommand command, CommandExecutedEventData eventData, DbDataReader result)
    {
        QueryCount++;
        
        return result;
    }

    public override Task<DbDataReader> ReaderExecutedAsync(DbCommand command, CommandExecutedEventData eventData, DbDataReader result,
        CancellationToken cancellationToken = new CancellationToken())
    {
        QueryCount++;
        
        return Task.FromResult(result);
    }
}

public class BloggingContext : DbContext
{
    private readonly CountingCommandInterceptor _interceptor = new CountingCommandInterceptor();

    public int QueryCount => _interceptor.QueryCount;
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
             .AddInterceptors(_interceptor)
             .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}
```

It will count SaveChanges calls too, but I expect it would be possible to filter those if necessary.

**Comment by ajcvickers** [comment]
@roji EF performance counters?

**Comment by roji** [comment]
@ajcvickers yep, makes sense - I think that's already covered in #18016 ("General/basic execution statistics").

**Comment by ajcvickers** [comment]
Closing this as covered by #18016 but happy to continue the discussion on ways to do this now if people want to.

**Comment by benmccallum** [comment]
Thanks all! Sorry I haven't had a chance to comment back, bit under the pump. Will dig in to the above suggestions when I have time. Thanks again.

**Comment by KiwiDevelopment** [comment]
For anyone landing here — I built a NuGet package that solves exactly this, specifically for integration tests:
 
```
await using var guard = factory.TrackQueries<Program, AppDbContext>();
var client = guard.CreateClient();

await client.GetAsync("/api/orders");

guard.AssertCount(exact: 1); // fails if N+1 sneaks in
```

It wraps DbCommandInterceptor so you don't have to write the boilerplate yourself. Useful as a regression guard — if someone breaks eager loading later, the test catches it immediately.
  
Package: KiwiQuery.EFCore on NuGet. Repo: https://github.com/KiwiDevelopment/KiwiQuery. MIT, one dependency.
