### ISSUE TITLE
Sqlite on Ubuntu: SQLite Error 1: 'no such table: Book'

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/efcore#19556]
I have a very simple website using a Sqlite database. It was working in .NET Core 2.2

Since upgrading to .NET Core 3.0, and the problem persists with .NET Core 3.1, it works locally, but once deployed on Ubuntu 18.04.3 LTS, I get this error

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Book'.

Nothing has changed in regards to the database nor anything around it.

It works on Windows 10 but fails in Ubuntu, so this looks like a bug in Sqlite. If it was failing to connect to the database, the error would be different, I suppose?

**Comment by ajcvickers** [comment]
@mysteryx93 Please post a small, runnable project that reproduces the error so that we can investigate.

**Comment by mysteryx93** [comment]
My project is already simple enough so I just trimmed it down. It works locally but fails on Ubuntu server.
[Satrimono.zip](https://github.com/dotnet/efcore/files/4050212/Satrimono.zip)

**Comment by AlexanderTaeschner** [comment]
I have no access to a Linux server, so that I cannot test it, but my guess would be that the database file is not found. In this case sqlite creates a new empty database file and opens it.

**Comment by bricelam** [comment]
> .Replace("~", _env.ContentRootPath)

Is that the right directory? Like Alexander said, if it's not, an empty database file will be created. Use `Mode=ReadWrite` in your connection string to get it to throw if the database doesn't exist.

**Comment by mysteryx93** [comment]
aaahhh

I've added this and it works now, thanks

`.Replace("~", _env.ContentRootPath).Replace('\\', System.IO.Path.DirectorySeparatorChar)`
