### ISSUE TITLE
Network errors when connecting to a SQLServer

### ISSUE THREAD

**Issue by Dolphinsimon** [dotnet/efcore#19566]
We have a SQLServer Instance in the cloud. When the ASP.NETCore with EFCore project starting, the error occurred:  Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections.(provider: TCP Provider, error: 0 - Host not found.)
       ---> System.ComponentModel.Win32Exception (11001): Host not found.

We do know this is a network error, but we can get ping response to the server in the same machine, also we can open the web pages in the same host.

EF Core version:3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Ent LTSC2019
IDE:  Visual Studio 2019 16.4.2

**Comment by Dolphinsimon** [comment]
Update: We have tested the SQL Server Instance host and port with tcpclient in the same application.
TCPClient works fine with connecting to the server. The efcore keeps prompting the same errors.

**Comment by Dolphinsimon** [comment]
UPDATE: Today the error changed:
Microsoft.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when sending the request to the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
But we have not changed anything.

**Comment by ajcvickers** [comment]
@Dolphinsimon Can you connect to the server from .NET without using EF Core?

**Comment by Dolphinsimon** [comment]
> @Dolphinsimon Can you connect to the server from .NET without using EF Core?

I have tested with pure SqlConnection, it can connect to our db.
This is my testing code:

```C# using var client=new TcpClient();
                logger.LogInformation("Connecting...");
                await client.ConnectAsync("www", 1433);
                logger.LogInformation("TCP Client Connected!");
                await using var sqlConnection=new SqlConnection(" ");
                sqlConnection.Open();
                logger.LogInformation("SQL Connected!");
                logger.LogInformation("Closing...");
                sqlConnection.Close();
                logger.LogInformation("Closed!");```

**Comment by Dolphinsimon** [comment]
We've tested the connection issue by azure sqldb. EFCore works well with Azure SQLDB. This might be an issue related by our SQL instance.
