### ISSUE TITLE
EFCore.Specification.Tests/EFCore.Relational.Specification.Tests release cadency

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19573]
Does the `EFCore.Specification.Tests`/`EFCore.Relational.Specification.Tests` package need to be aligned with the main EFCore package? I mean is there a possibility to release the `EFCore.Specification.Tests`/`EFCore.Relational.Specification.Tests` maybe more often, as bugs in tests are fixed, so provider writers can get the fixes faster? I suppose given the package is consumed only by provider writers and only for tests, this could be possible.

**Comment by ajcvickers** [comment]
@cincuranet We have discussed in the past ways to tighten the loop to external providers updating to EF changes. We're still interested in any ideas you have in this area. 

The packages are pushed everywhere we normally push packages: releases, previews, and daily builds. Typically, most providers follow the previews--we expect to get the first 5.0 preview out in the next couple of months. However, I don't think there is anything preventing a provider using the packages from the daily builds instead.
