### ISSUE TITLE
k ef migration add "name with space" result in bad c# code

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#1957]
I didn't found this issue anywhere, pretty sure you already know it but just in case,

if you `k ef migration add "name with space"` that will create a method with spaces which obviously doesn't compile.

**Comment by bricelam** [comment]
I'm pretty sure this has been fixed. @Bartmax, what version of EF are you using?

**Comment by Bartmax** [comment]
7.0.0-beta3, is the only one shown in intellisense on CTP 6. Should I use another one ?

**Comment by bricelam** [comment]
That's the latest released version. You can use the nightly builds if you really want to live on the bleeding edge.

**Comment by vncastanheira** [comment]
@Bartmax Did you upgraded the K runtime to the new DNVM? 
I found this issue after making this update and also unsure what command to run a migration now.

**Comment by Bartmax** [comment]
No. Using ctp6 beta-3 packages with kvm/kpm and friends

**Comment by bricelam** [comment]
@vncastanheira The command should be `dnx . ef migration add blah`.

**Comment by rowanmiller** [comment]
This is fixed in Beta 4 and later releases
