### ISSUE TITLE
Query to match by Guid works in 2.2.6, fails in 3.1

### ISSUE THREAD

**Issue by jmoleary** [dotnet/efcore#19586]
My EF Core Database has a very simple query that tries to match a "Scan" record by a required Guid field.    It succeeds under 2.2.6  but fails under 3.1.0

(Note: I've found similar issues to this e.g. #11002 but I don't think they apply in my case.  My database Guid field is definitely Guid, not a string.  I've verified this looking at the database explorer)

Here is the query that fails:

    bool DoesScanExist(Guid guid)
    {
        // Finds the record under 2.2.6,fails under 3.1.0
        using var ctx = new GsContext();
            return ctx.Scans.AsNoTracking().SingleOrDefault(s => s.Guid == guid) != null;       
    }

This is the database model class

    public class Scan
    {
        [Key]
        public int              Id              { get; set; }

        [Required]
        public Guid             Guid            { get; set; }
        public bool             IsDeleted       { get; set; }   // soft delete

        [Required]
        [MaxLength(512)]
        public string           CreatedBy       { get; set; }
        public DateTime         CreatedOn       { get; set; }

        [Required]
        [MaxLength(512)]
        public string           UpdatedBy       { get; set; }
        public DateTime         UpdatedOn       { get; set; }

        [Required]
        [MaxLength(256)]
        public string           Name            { get; set; }

        [Required]
        public string           Folder          { get; set; }
        public Part             Part            { get; set; }
        public string           Note            { get; set; }
        public int?             CartridgeId     { get; set; }   
        public Cartridge        Cartridge       { get; set; }
        public int?             DeviceId        { get; set; }
        public Device           Device          { get; set; }
        public List<Routine>    Routines        { get; set; }
    }`

I can downgrade my EF Core NuGet packages back to version 2.2.6 to make the query work again.  Then go back up to 3.1.0 and watch it fail

Note that if I change the query to expensively retrieve all scans and *then* match on the client, it works fine

`      var sc = ctx.Scans.AsNoTracking().ToList().SingleOrDefault(s => s.Guid == guid);
`

But again, my database GUID field is not a text type. I can see that in SQL Server Compact Toolbox.  

I created the initial  migration some time ago, probably around the time of EF Core 2.0-ish.   I've been using it ever since and upgrading EF Core Versions along the way. There have been no other migrations since the initial one.

If I compare the SQL issued in both cases, I think I can see the difference but I don't know what it means.  

This is the 2.2.6 version of the query, which works.  **Note that it appears to execute TWO commands.**

```
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 2.2.6-servicing-10079 initialized 'GsContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: SensitiveDataLoggingEnabled 
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
PRAGMA foreign_keys=ON;
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[@__guid_0='c8fa66ef-08a4-4276-bd2d-a9f02ec221be' (DbType = String)], CommandType='Text', CommandTimeout='30']
SELECT "p"."Id", "p"."CartridgeId", "p"."CreatedBy", "p"."CreatedOn", "p"."DeviceId", "p"."Folder", "p"."Guid", "p"."IsDeleted", "p"."Name", "p"."Note", "p"."PartId", "p"."UpdatedBy", "p"."UpdatedOn"
FROM "Scans" AS "p"
WHERE ("p"."IsDeleted" = 0) AND ("p"."Guid" = @__guid_0)
LIMIT 2
```

Here is the 3.1.0 version which fails and **only appears to execute ONE command.**

```
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.1.0 initialized 'GsContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: SensitiveDataLoggingEnabled 
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[@__guid_0='c8fa66ef-08a4-4276-bd2d-a9f02ec221be' (DbType = String)], CommandType='Text', CommandTimeout='30']
SELECT "s"."Id", "s"."CartridgeId", "s"."CreatedBy", "s"."CreatedOn", "s"."DeviceId", "s"."Folder", "s"."Guid", "s"."IsDeleted", "s"."Name", "s"."Note", "s"."PartId", "s"."UpdatedBy", "s"."UpdatedOn"
FROM "Scans" AS "s"
WHERE NOT ("s"."IsDeleted") AND ("s"."Guid" = @__guid_0)
LIMIT 2
```

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite 3.1.0
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by ErikEJ** [comment]
Breaking change? https://docs.microsoft.com/da-dk/ef/core/what-is-new/ef-core-3.0/breaking-changes#guid-values-are-now-stored-as-text-on-sqlite

**Comment by jmoleary** [comment]
Oh thank you.  I don't know why my googling didn't have me hitting that.
