### ISSUE TITLE
[Migrations] Add GeneratedCodeAttribute to generated code

### ISSUE THREAD

**Issue by m4cx** [dotnet/efcore#19596]
We are currently inspecting our code base with SonarQube/SonarLint to improve our code quality. Without touching those files, the analysis throws error, warning or information messages. This is also the case for other code analysis tools like mentioned in issue #18277. 

It also reports code clones which is indeed pretty normal. I don't want to refactor those files just for the purpose of passing the quality gates.

It would be nice to have an default disabling of code analysis in place:
```csharp
[GeneratedCode("Tool", "Version")] // Remove if file is edited
public partial class Init : Migration 
{
}
```
With this information in place, code analysis can skip all those files. If you manually edit this file or you want to check EF Core quality score for fun, you can just remove this attribute.

**Comment by roji** [comment]
Note that the partial part of the migration that resides in the `XXX.Designer.cs` files has a `// <auto-generated />` at its beginning, which is a signal to Roslyn analyzers to consider this generated code (the extension .Designer.cs does the same, btw).

For the main file which doesn't have this, we actually consider it to be "regular code"; although it's initially generated by code, it is then considered entirely fine for users to edit this file for customization/tweaks.

Do you have a specific usage scenario causing you problems?

**Comment by ajcvickers** [comment]
See #10203 for a related discussion on `<auto-generated />`.

@bricelam Is there any reason to treat `[GeneratedCode]` differently to `<auto-generated />`?

**Comment by ajcvickers** [comment]
The team discussed this and decided:
* We're going to keep the same rules we have now for when we put `// <auto-generated />` on a file. That is, when it should not be edited. Files that are scaffolded to then be edited will not get it.
* `GeneratedCodeAttribute` does not seem to be widely used. Also, since it applies to a class it doesn't allow one part of the partial class to be generated while the other is not. For these reasons we are not going to emit `GeneratedCodeAttribute`.

**Comment by StingyJack** [comment]
If the goal is to have Sonar* (and other CA tools) skip code generated files, then consider using the file naming convention of `.g.cs` (or vb, etc). This can be configured in Sonar to skip these files for analysis, but you can still have their non generated partial classes (with the regular extensions) analyzed. 

[GeneratedCode] was on every service client (wsdl/svcutil) I can recall, and its present on their spiritual successor Nswag. As someone whose work regularly involves writing or consuming services over the network, that seems "widely used" to me.
