### ISSUE TITLE
Index-included properties are treated as columns, not properties

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19602]
First raised in https://github.com/npgsql/efcore.pg/issues/1201 for Npgsql, but looks to be the same bug for the SQL Server provider: the included properties annotation contains properties names, but SqlServerMigrationsSqlGenerator renders them as column names directly. This fails if the column name differs from the property name.

When fixing this, add a migration test in #19039, and add one to Npgsql too.

**Comment by roji** [comment]
@bricelam any idea if we have this bug elsewhere in migrations?

**Comment by ajcvickers** [comment]
@roji to check if this is fixed on master.

**Comment by bricelam** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/14087

**Comment by roji** [comment]
Confirmed, this has already been fixed in SQL Server but Npgsql wasn't updated.
