### ISSUE TITLE
Update comment on UseLoggerFactory

### ISSUE THREAD

**Issue by benmccallum** [dotnet/efcore#19611]
**Problem**
Recently had someone in our team add `UseLoggerFactory` when we swapped from `AddDbContext` to `AddDbContextPool`. Was trying to find if it was necessary, as I didn't think it was.

[Docs ](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3) site says no. 
> EF Core integrates automatically with the logging mechanisms of ASP.NET Core whenever AddDbContext or AddDbContextPool is used. Therefore, when using ASP.NET Core, logging should be configured as described in the ASP.NET Core documentation.

Bit of a nitpick I know, but it'd be worth quickly updating the UseLoggerFactory method descriptions [here](https://github.com/dotnet/efcore/blob/402938aec53f2004a2cb551d932edae38bffafb6/src/EFCore/DbContextOptionsBuilder.cs#L95) which explicitly call out `AddDbContext` but not the Pool version.
> There is no need to call this method when using one of the 'AddDbContext' methods. 'AddDbContext' will ensure that the <see cref="ILoggerFactory" /> used by EF is obtained from the application service provider.

**Solution**
I can quickly update the comments in a PR. Let me know if you're happy with either of these:

1. There is no need to call this method when using one of the 'AddDbContext' methods (including 'AddDbContextPool'), which ensure that the <see cref="ILoggerFactory" /> used by EF is obtained from the application service provider.
2.  There is no need to call this method when using one of the 'AddDbContext*' methods, which ensure that the <see cref="ILoggerFactory" /> used by EF is obtained from the application service provider.

**Comment by ajcvickers** [comment]
@benmccallum Short sentences are easier for non-native English speakers and machine translation. How about:

`There is no need to call this method when using one of the 'AddDbContext' methods, including 'AddDbContextPool'. These methods ensure that the <see cref="ILoggerFactory" /> used by EF is obtained from the application service provider.`

**Comment by benmccallum** [comment]
I like it. PR up. There was another method I found in there that I think needs the comment updated too. Please check though. Cheers!
