### ISSUE TITLE
DefaultIfEmpty() + Max() broken again?

### ISSUE THREAD

**Issue by romanov** [dotnet/efcore#19612]
### Steps to reproduce

Simple Model:

```
public class Person
{
[Key]
public int Id { get; set; }

public string Name { get; set; }
}
```

SQL table is with 0 rows.

try: 

    var id = _context.Persons.AsNoTracking().DefaultIfEmpty().Max(x => x.Id) + 1;

exception **InvalidOperationException: Sequence contains no elements.**

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by maumar** [comment]
query plan:

```
ShapedQueryExpression: 
    QueryExpression: 
        (Projection Mapping:
            EmptyProjectionMember -> 0
        SELECT MAX(p.Id)
        FROM 
        (
            SELECT (NULL AS empty)
        ) AS empty
        LEFT JOIN Persons AS p ON 1 == 1)
    ShaperExpression: 
        {
            Nullable<int> result;
            result = (ProjectionBindingExpression: EmptyProjectionMember);
            return result == default(Nullable<int>) ? throw new InvalidOperationException("Sequence contains no elements.") : (int)result;
        }
```

**Comment by romanov** [comment]
Closing https://github.com/dotnet/efcore/issues/17988

**Comment by ajcvickers** [comment]
@maumar to verify dupe.
