### ISSUE TITLE
Add a lightweight version of DbContext

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#19610]
One without `OnConfiguring` and `OnModelCreating` methods. These can be optionally specified in `AddDbContext`.

Optimized for use with compiled model and context pooling. It will allow using EF without loading any model building types.
`OnModelBuilding` can be moved to options: `DbContextOptionsBuilder.OnModelBuilding(Action<ModelBuilder> buildModel)`

Consider doing something similar for `DatabaseFacade` if migration code is not trimmed out even when `EnsureCreated`/`EnsureDeleted` is not used.

Limitations:

- It won't have events or other features that need to be cleaned when returning to pool

Alternatively, we can define [a feature switch](https://github.com/dotnet/runtime/blob/65f04b9f299bc0f57788dd4124b3748fbc92ef84/docs/workflow/trimming/feature-switches.md#adding-new-feature-switch) for model building to allow the code to be [trimmed](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/ILLink-files.md).

**Comment by roji** [comment]
Would this be a user-facing thing, or more of an internal building block for compiled models?

**Comment by AndriySvyryd** [comment]
This is user-facing, they will need to place the model building code in a different assembly than this runtime context (along with migrations) to be able to avoid loading model building code in production.

**Comment by roji** [comment]
OK, thanks for the explanation. It would be nice to do a design session once where you give an overview of what you're planning :)

**Comment by AndriySvyryd** [comment]
Sure, but I don't think that the benefits of doing this will ever be enough to justify the cost of implementation.

**Comment by ajcvickers** [comment]
@AndriySvyryd Do you mean you created an issue that you think we will close? :trollface: 

The question of how to create the compiled model and consume it at runtime has been bothering me for five years! This does seem like it could be a way forward.

**Comment by AndriySvyryd** [comment]
Yes, as a pragmatic optimist while I don't think we'll do this I hope we will.

**Comment by ilmax** [comment]
@ajcvickers I'm sure you guys already thought about it, but what about starting with a serializable implementation of the IModel and generate that one via a command line at CI time, and configure the context to load this serialized model in the startup.cs.
I was thinking about generating a read-only model at compile time but without running ef this is tricky, this approach instead looks a bit easier to me.

**Comment by AndriySvyryd** [comment]
@ilmax Yes, we've thought about it 😄 : https://github.com/dotnet/efcore/issues/1906#issuecomment-401565817, https://github.com/dotnet/efcore/issues/8258, https://github.com/dotnet/efcore/issues/12511

**Comment by AndriySvyryd** [comment]
This is no longer necessary due to how trimming works.
