### ISSUE TITLE
HasNoKey() cause migration to generate table 

### ISSUE THREAD

**Issue by domdeger** [dotnet/efcore#19621]
We use e.g. `modelBuilder.Entity<QueryResult>().HasNoKey();` to register custom query result types for usage with "FromRawSql". We migrated from DbQuery<> as we moved along from ef core 2.2 .

Since ef core 3.1 new migrations include code to create table for the entity types marked with .HasNoKey(). The only way I was able to work around this behaviour was to call "ToView" on those types.

### Steps to reproduce

<!--
What steps can we follow to reproduce the issue?
1. Add register non entity class with modelBuilder.Entity<>().HasNoKey();
2. Let ef generate a migration
We ❤ code! Include a complete code listing or attach a simplified project

### Further technical details

EF Core version: 3.1.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer): Pomelo.Mysql
Target framework: (e.g. .NET Core 3.0) 3.1
Operating system: Windows 10 1909
IDE: (e.g. Visual Studio 2019 16.3) VS19

**Comment by ajcvickers** [comment]
@domdeger Yes, this is correct. Improving the experience here is tracked by #17270
