### ISSUE TITLE
Allow a namespace to be provided to all scaffolding operations

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#19626]
I'd love to be able to provide a namespace for the generated files. My project has an `src/` directory at the root where my C# source files begin from.

😊

**Comment by ErikEJ** [comment]
EF Core Power Tools gives you full control of namespaces (for Reverse Engineering)

**Comment by atrauzzi** [comment]
Does that require Visual Studio to run?

**Comment by ErikEJ** [comment]
Yes, IT is a Visual Studio extension. Please create an issue if you would like a .NET Core command line version.

**Comment by atrauzzi** [comment]
Is that not what this is?

**Comment by ErikEJ** [comment]
Yes, bit it does not allow you full control of namespaces at the moment

**Comment by atrauzzi** [comment]
Can we simply track it through this issue?

**Comment by ajcvickers** [comment]
@bricelam to take a look.

**Comment by bricelam** [comment]
Duplicate of #9723
