### ISSUE TITLE
EF Core Updating ALL columns when only 3 have changed.

### ISSUE THREAD

**Issue by adrianwright109** [dotnet/efcore#19634]
I read @ajcvickers blog post: [https://blog.oneunicorn.com/2020/01/17/dontcallupdate/](https://blog.oneunicorn.com/2020/01/17/dontcallupdate/)

So I thought I would check my code...

**N.B.** In my base repository class for update I have this:
```
        public virtual void Update(T entity)
        {
            _dbContext.Entry(entity).State = EntityState.Modified;
            entity.IdString = entity.GetId().ToString();
            _dbContext.Add(CreateAuditEntity("U", entity));
            _dbContext.SaveChanges();
        }
```
**Step 1:**
I retrieve an entity from the dbContext using this query:
```
        public RvImport GetOldestPendingRvImport()
        {
            const int pendingStatus = (int)RvImportStatusEnums.Pending;

            return _dbContext.RvImports
                .Where(x => x.RvImportStatusId == pendingStatus)
                .OrderBy(x => x.Id)
                .Take(1)
                .FirstOrDefault();
        }
```
**Step 2:**
I update 3 properties on the entity:
```
            rvImport.RvImportStatusId = (int)RvImportStatusEnums.Processing;
            rvImport.ImportStartDateTime = DateTime.UtcNow;
            rvImport.ModifiedBy = $"WebJob {typeof(Functions).Assembly.GetName().Version}";
```
**Step 3:**
Call `Update()` on the base repository passing in the modified entity

**Step 4:**
I profile the SQL to find that its updating ALL columns regardless of whether they have changed or not.  See full SQL update below:
```
exec sp_executesql
N'
	SET NOCOUNT ON;
UPDATE
	[RvImports]
SET
	[Body] = @p0, 
	[ConcurrencyStamp] = @p1, 
	[ImportEndDateTime] = @p2, 
	[ImportFileTypeId] = @p3, 
	[ImportFilename] = @p4, 
	[ImportStartDateTime] = @p5, 
	[ProjectId] = @p6, 
	[RecordCount] = @p7, 
	[RequestedImportFileTypeId] = @p8, 
	[RvImportStatusId] = @p9, 
	[UserId] = @p10
WHERE
	[Id] = @p11;
SELECT @@ROWCOUNT;',
N'
	@p11 int,
	@p0 nvarchar(4000),
	@p1 nvarchar(4000),
	@p2 datetime2(7),
	@p3 int,
	@p4 nvarchar(4000),
	@p5 datetime2(7),
	@p6 int,
	@p7 int,
	@p8 int,
	@p9 int,
	@p10 nvarchar(4000)',
	@p11=39,
	@p0=NULL,
	@p1=N'03153F3B-5EC0-4004-B290-96F97E0AA023',
	@p2=NULL,
	@p3=3,
	@p4=N'Import (2).csv',
	@p5='2020-01-18 19:30:19.9648002',
	@p6=9,
	@p7=NULL,
	@p8=2,
	@p9=2,
	@p10=N'3f7b6467-90b3-40e0-bc86-116840900a81'
```
I guess I was expecting that to happen as I'm explicitly calling and marking the entire entity as Modified:
```
            _dbContext.Entry(entity).State = EntityState.Modified;
```

Then I thought I would try the update again but would skip over the line that is marking the state of the entire entity as Modified, expecting that this time the SQL profile would only show those 3 modified columns in the UPDATE statement. 

But to my shock nothing was updated and the SQL profile was empty (except for it adding a new Audit entry which is part of the `Update()` method)

It seems that even though I have an entity from the dbContext which the dbContext "_should_" be tracking the 3 modified properties on the entity are not being updated when calling `_dbContext.SaveChanges();` without explicitly calling `_dbContext.Entry(entity).State = EntityState.Modified;` but then it updates ALL columns.

I just want the update statement to ONLY update the columns that have actually changed.

What am I doing wrong?  

### Further technical details

EF Core version: 2.2.6
Database provider: Azure - Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 2.2.8
Operating system: Windows 7
IDE: Visual Studio 2019 16.4

**Comment by ilmax** [comment]
if you read the entity, update 3 properties and call SaveChanges  (without marking the entity as modified) from the same context instance, it will behave the way you want.

**Comment by ajcvickers** [comment]
@adrianwright109 Hard to be sure with just snippets of code, but my guess would be that the `RvImport` instance is not being tracked by the context using in your `Update` method. This could be either that it is queried as no-tracking, or because a new context instance is created between the two places, or maybe it has been explicitly detached.

**Comment by adrianwright109** [comment]
My bad! Its turns out that I was explicitly setting all EF queries to NoTracking in `ConfigureServices`
```
.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
```
