### ISSUE TITLE
Rewrite analyzer using Roslyn Operations for speed and cross-language support

### ISSUE THREAD

**Issue by toshke994** [dotnet/efcore#19648]
I am upgrading our project from .netcore 2.1 to 3.1.1. (and EF core with it). One of the projects that doesn't use EF at all references another project that does reference it, and as a result building the first project takes around 30 minutes.

I have isolated the problem in the sample app.
Build time while referencing Microsoft.EntityFrameworkCore.Analyzers (3.1.1) ~10000ms
Build time without referencing Microsoft.EntityFrameworkCore.Analyzers (3.1.1) ~200ms

### Steps to reproduce

[BuildSpeedTest.zip](https://github.com/dotnet/efcore/files/4086598/BuildSpeedTest.zip)

Build a provided solution while referencing Microsoft.EntityFrameworkCore.Analyzers (3.1.1) and it should take ~10000ms (±1s)
Build without referencing Microsoft.EntityFrameworkCore.Analyzers (3.1.1), or disable running analyzers during the build and it should take ~200ms

Reducing the size of StaticArray will reduce the build time and vice versa.

### Further technical details

EF Core version: 3.1.1
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro (Version 1909)
IDE: Visual Studio 2019 16.4.3

**Comment by ajcvickers** [comment]
Related to #18618 and possibly #19597

/cc @roji

**Comment by ajcvickers** [comment]
@roji I see a difference in build times on my machine, although it's not nearly as pronounced as reported above. I have again captured and attached diagnostic build logs. It doesn't look to me that this is specific to the EF analyzers, but more related to how the build operates with/without analyzers turned on. However, I could be totally wrong!

Could you take a look at the logs and then follow up with your analyzer contacts?

[with_analyzers.txt](https://github.com/dotnet/efcore/files/4130650/with_analyzers.txt)
[without_analyzers.txt](https://github.com/dotnet/efcore/files/4130651/without_analyzers.txt)

**Comment by ajcvickers** [comment]
Attaching binlogs here too.

[binlogs.zip](https://github.com/dotnet/efcore/files/4130715/binlogs.zip)

**Comment by roji** [comment]
@ajcvickers thanks for the work... I'll follow up on this.

**Comment by roji** [comment]
Note: will continue investigation in #19597 assuming this is a dup until we see otherwise.

**Comment by roji** [comment]
This is not a dup of #19597, and I repro a x10 degradation in build time (with --no-incremental --no-restore). I'll investigate further.

**Comment by roji** [comment]
As suggested by @mvasani and @sharwell, rewriting the analyzer using Operations brought the build time from around 10 seconds to 2, roughly the same as without the analyzer. Thanks!
