### ISSUE TITLE
Is there any way to apply global query filter to a unique index or all unique indexes of an entity?

### ISSUE THREAD

**Issue by doboczyakos** [dotnet/efcore#19656]
There's an IsDeleted property on the entity, and we configure global query filter on it.
If there's a unique index, we expect checking uniqueness is made only on entities with IsDeleted=false.

There should be an option to add the already defined global query filter to a unique index, or define that it should be added to all unique indexes of the entity.

**Comment by ajcvickers** [comment]
@doboczyakos This sounds like a filtered index--see https://docs.microsoft.com/en-us/ef/core/modeling/indexes#index-filter

**Comment by doboczyakos** [comment]
No. This is not simply a filtered index.
We have a field for logical deletion.
We are writing a global query filter and we'd like to apply this filter on the unique indexes writing the expression down only once.
It was not a question but a feature suggestion ;)

**Comment by ajcvickers** [comment]
@doboczyakos Can you elaborate more on what you mean by, "apply this filter on the unique indexes?"

**Comment by doboczyakos** [comment]
@ajcvickers I mean .IsUnique().WithQueryFilter() or
if (index.IsUnique)
   index.ApplyQueryFilter();

But I've found out that by the time we'll have fluent api for HasFilter/SetFilter these can be easily implemented as custom extension methods.

**Comment by ajcvickers** [comment]
@doboczyakos So the only connection to the index is that you want to configure it on the entity type _via the Index API_, as opposed to via the entity type API, as is normally the case.

**Comment by doboczyakos** [comment]
@ajcvickers I mean when implementing logical deletion it makes sense to have the same expression as global query filter and filter on all unique indexes of the same entity... or there should be an option to configure logical deletion similar to concurrency token.
https://github.com/dotnet/efcore/issues/19653 would add more value to the product than this one so I'd not like to waste your time with it ;)
