### ISSUE TITLE
Client side GroupBy is not supported in EF 3.0

### ISSUE THREAD

**Issue by simpleway2016** [dotnet/efcore#19663]
``` C#
 var ret = db.UserInfo.GroupBy(m => m.phone).ToArray();
```
throw exception:
System.InvalidOperationException:“Client side GroupBy is not supported.”

EF Core version: 3.0
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: windows 10
IDE:Visual Studio 2019

**Comment by maumar** [comment]
dupe of https://github.com/dotnet/efcore/issues/17068

**Comment by NetMage** [comment]
@simpleway2016 This doesn't have a SQL translation benefit since no server side aggregation is performed; you can just put `AsEnumerable()` before the `GroupBy`.
