### ISSUE TITLE
Is EF Core 2 supported with ASP.NET Core 3.1

### ISSUE THREAD

**Issue by ManuelHaas** [dotnet/efcore#19678]
Hi,

does EF Core 2.1.14 or 2.2.6 work with ASP.NET Core 3.1 and is this supported?
I ask because due to several breaking changes it is not possible for us to upgrade EF Core at this point in time.

**Comment by ajcvickers** [comment]
@ManuelHaas In general, no. However, depending on what you are doing you may be able to make it work.
