### ISSUE TITLE
Register does not work on the remote site after I publish StarterWeb template to Azure

### ISSUE THREAD

**Issue by balachir** [dotnet/efcore#1967]
REPRO STEPS
1. New project from StarterWeb template
2. Ctrl-F5, Register a user - works fine
3. Publish to Azure
4. Click Register on the published remote site.

ACTUAL
![image](https://cloud.githubusercontent.com/assets/8246794/6948772/cdc8ec18-d864-11e4-9eda-f42fbd5fa0c1.png)

**Comment by bricelam** [comment]
Dupe of #1960

**Comment by rowanmiller** [comment]
Also a dupe of https://github.com/aspnet/Templates/issues/41
