### ISSUE TITLE
EntityEntry.OriginalValues does return current values of newly created object

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/efcore#19671]
[According to the docu](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.entityentry.originalvalues) EntityEntry.OriginalValues should

> Gets the original property values for this entity. The original values are the property values as they were when the entity was retrieved from the database.

So I would expect the original values collection for a new entity, that was never added to the DB, to be empty. However it returns the full set of current properties.

```csharp
[Fact]
public void OriginalValues_OfNewEntity_ShouldBeEmpty()
{
	var context = new MyDbContext();
	context.Database.EnsureCreated();
	var entity = new Entity {SomeString = "foobar"};
	context.Entities.Add(entity);

	var originalEntity = (Entity) context.Entry(entity).OriginalValues.ToObject();

	originalEntity.SomeString.Should().BeEmpty().And.NotBeEquivalentTo(entity.SomeString); 
	//Fails: Expected originalEntity.SomeString to be empty, but found "foobar".
}
```

BR Matthias

**Comment by ajcvickers** [comment]
@matthiaslischka This is currently by-design. Real original values may not be available for a number of reasons, so they default to current values if not set. This often removes the need to write different code to handle different object states.

That being said, we'll discuss if it makes sense to change this behavior.

**Comment by matthiaslischka** [comment]
I wanted to send a PR for the docu but could not find the correct source on Github. I think this behaviour might be worth mentioning. We stumbled across this because we use it for some of our validation.

**Comment by ajcvickers** [comment]
@matthiaslischka A docs PR would be great! API docs like the one you linked are in this repo. For example: https://github.com/dotnet/efcore/blob/master/src/EFCore/ChangeTracking/EntityEntry.cs#L295

Other higher-level docs are here: https://github.com/aspnet/EntityFramework.Docs
