### ISSUE TITLE
Query: inconsistent behavior between relational and InMemory/L2O for queries grouping by a constant

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#19683]
In relational we ignore groupby constant or parameter, so we just generate simple select. However, on InMemory and Linq2Objects we generate a single grouping with the key.

**Comment by ajcvickers** [comment]
Talk with @smitpatel on this. Related to client-grouping.

**Comment by smitpatel** [comment]
Duplicate of #19027

**Comment by smitpatel** [comment]
`StartsWith(null)` is exception in client-side. If we consider the result as false then the translation on relational is incorrect. It should group by false and just generate 1 grouping.

**Comment by smitpatel** [comment]
Poached
