### ISSUE TITLE
FromSqlInterpolated + Cache

### ISSUE THREAD

**Issue by lixaotec** [dotnet/efcore#19692]
Dear folks,

How would I accomplish query caching with fromsqlinterpolated ?

I tried zzzproject query cache FromCache() it does not work when calling CoUnt() and fromsqlinterpolated it calls but seem not to get from cache.
Unfortunately i need sqlinterpolate to use full text search with containstable.

Any path?

Thanks

**Comment by ajcvickers** [comment]
@lixaotec Can you provide more details on what indicates that query caching is not being used?
