### ISSUE TITLE
EF Core does not report types it failed to load from migration assemblies

### ISSUE THREAD

**Issue by Trojaner** [dotnet/efcore#19691]
EntityFramework Core should report failed types from SharedTypeExtensions.GetLoadableDefinedTypes.

I just spent 6 hours figuring out why EntityFramework Core suddenly does not apply any pending migrations with context.Database.Migrate(). After exploring more I noticed that context.Database.GetMigrations() and context.Database.GetPendingMigrations() were empty. I checked IMigrationAssemlby which also had an empty Migrations property.

Finally, after testing and debugging more I noticed that GetLoadableDefinedTypes catches a TypeLoadException without reporting it [here](https://github.com/dotnet/efcore/blob/ee31f22ecdce1e4bd4b558436467b8e7f9626a52/src/Shared/SharedTypeExtensions.cs#L333). This exception should be reported at least in the debug logs.  

It seems like Microsoft.EntityFrameworkCore.Relational was missing for my migrations project for some reason, after adding it my migrations started to work again.

**Comment by ajcvickers** [comment]
@Trojaner It's by design that type loading errors are ignored when scanning assemblies. That being said, logging a warning seems like a good idea.

**Comment by Trojaner** [comment]
I agree they should be ignored but reporting such exception would be really helpful

**Comment by MWallenberg** [comment]
Thank you @Trojaner , I had the same issue, and spent more than a day trying to debug it. I agree it should be reported or logged somehow.
