### ISSUE TITLE
Backing field configuration reports weird errors

### ISSUE THREAD

**Issue by ImoutoChan** [dotnet/efcore#19711]
I have entity class with field like this:

```C#
private string _supportedExtensions;
```

then I have configuration like this:

```C#
modelBuilder.Entity<MyEntity>()
    .Property<string>("SupportedExtensions")
    .HasField("_supportedExtensions");
```

My intention was to have in model only field and to have "SupportedExtensions" columns in database. It seems like I do all correctly and according to this documentation:
https://docs.microsoft.com/en-us/ef/core/modeling/backing-field

But, when I try to add migration, I receive an error:
`InvalidOperationException: The specified field '_supportedExtensions' cannot be used for the property 'MyEntity.SupportedExtensions' because it does not match the property name.`

Is this a bug or am I doing something wrong?

stacktrace:
```
at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.SetField(FieldInfo fieldInfo, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.SetField(String fieldName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.HasField(String fieldName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder.HasField(String fieldName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder`1.HasField(String fieldName)
```

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.PgSql
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.0 Preview 2.0

**Comment by ajcvickers** [comment]
@ImoutoChan That documentation shows this pattern for mapping a field:

```C#
modelBuilder.Entity<MyEntity>()
    .Property<string>("_supportedExtensions");
```
I'm curious to know why you are instead using the pattern above?

Changing the column to which a property is mapped is documented here: https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=fluent-api%2Cwithout-nrt#column-names

For example:

```C#
modelBuilder.Entity<MyEntity>()
    .Property<string>("_supportedExtensions")
    .HasColumnName("SupportedExtensions");
```

**Comment by ImoutoChan** [comment]
Thank you, it helped. I probably was confused because I thought Property can only define property (real or shadow), and backing field can be configured only through HasField method.
