### ISSUE TITLE
Decimal column with a scale greater than 2 does not translate to SQL properly.  In this case, .0025 converts to 25

### ISSUE THREAD

**Issue by foobarred1** [dotnet/efcore#19728]
I have a model that contains a .HasColumnType(6, 4) and when I save a value, such as .0025m, EF Core translates it to 25 in SQL.

### Steps to reproduce

Model:

```
namespace TestEFCore.Models
{
    public partial class TestDecimal
    {
        public int Id { get; set; }
        public decimal? Decimal4 { get; set; }
    }
}
```

Context code:

```
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TestDecimal>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Decimal4).HasColumnType("decimal(6, 4)");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedOnAdd();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


```
Program.cs:

```
namespace TestEFCore
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            using (FleetFusionContext db = new FleetFusionContext())
            {
                db.Add(new TestDecimal
                {
                    Decimal4 = .0025m
                });
                db.SaveChanges();
            }
        }
    }
}
```

Result in SQL Profiler:

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [TestDecimal] ([Decimal4])
VALUES (@p0);
SELECT [ID]
FROM [TestDecimal]
WHERE @@ROWCOUNT = 1 AND [ID] = scope_identity();

',N'@p0 decimal(4,4)',@p0=25


```

NOTE that the generated SQL statement will error out because p0 is set to 25 though it is of decimal(4,4) type.  Interestingly, if I set the value to .25m, it works properly.

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3.8)

[TestEFCore.zip](https://github.com/dotnet/efcore/files/4122924/TestEFCore.zip)

**Comment by ajcvickers** [comment]
@foobarred1 I added logging to your sample app, and this is the output I see:

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (37ms) [Parameters=[@p0='0.0025' (Nullable = true)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [TestDecimal] ([Decimal4])
      VALUES (@p0);
      SELECT [ID]
      FROM [TestDecimal]
      WHERE @@ROWCOUNT = 1 AND [ID] = scope_identity();
```
Logging code:
```C#
private readonly ILoggerFactory Logger 
    = LoggerFactory.Create(c => c.AddConsole());//.SetMinimumLevel(LogLevel.Debug));
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
        optionsBuilder
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }
}
```

Can you double-check that the application you posted reproduces the issue in your environment. If it does, then we can figure out what's different between my setup and yours.

**Comment by foobarred1** [comment]
Yes.  It does exactly as I described:
![image](https://user-images.githubusercontent.com/24896875/73291341-973de480-41c5-11ea-9b95-0def6aac8f7a.png)

**Comment by foobarred1** [comment]
Also, FYI (in case it's relevant):

![image](https://user-images.githubusercontent.com/24896875/73291712-58f4f500-41c6-11ea-80e7-2bc065d26145.png)

**Comment by ajcvickers** [comment]
@foobarred1 Can you insert the logging code I posted above and then post the output of the log here?

**Comment by foobarred1** [comment]
Fascinating...  Log says .0025, profiler says 25.

![image](https://user-images.githubusercontent.com/24896875/73296934-42539b80-41d0-11ea-87d2-099517542473.png)

**Comment by ajcvickers** [comment]
@foobarred1 What value is actually stored in the database?

**Comment by ErikEJ** [comment]
SQL Profiler bug? https://stackoverflow.com/questions/11845012/decimal-passed-incorrectly-from-c-sharp-to-sql-server-with-tableadapters

**Comment by foobarred1** [comment]
Wha???  Okay, it worked.  Sorry for wasting your time.  I fell into this problem trying to troubleshoot something else.  This is a red herring.
