### ISSUE TITLE
Bug fixing policy: Which bugs are going to be fixed in EF Core 3.1

### ISSUE THREAD

**Issue by cello99d** [dotnet/efcore#19736]
I wonder which bugs are going to be fixed under LTS in EF Core 3.1?
I see already 69 bugs fixed for release 5.0, many of them do also exists in 3.1.
Which fixes do you plan to backport to 3.1?
I am also wondering whether it would be a better approach to fix bugs in 3.1 fitrst and then port the fixes forward to 5.0?

**Comment by ajcvickers** [comment]
@cello99d I started writing some documentation on this yesterday. I'll link to it when done.

**Comment by ajcvickers** [comment]
@cello99d See https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning
