### ISSUE TITLE
Discuss default null propagation strategy for functions

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19731]
We now have the ability to specify detailed null behavior on functions (i.e. whether the function itself is nullable, and whether its propagates nulls from its parameters and instance). The current default for this - SqlExpressionFactory.Function() overloads which don't accept these settings - is for the function to be nullable, and for the parameters/instance *not* to be propagated; in other words, we have no idea about the function and when it returns null, we assume the worst, so we add null checks on the function:

```sql
WHERE (FOO(p) = x) OR ((FOO(p) IS NULL) AND (x IS NULL))")
```
(assuming x is nullable)

While this is the most conservative option, it's also problematic for perf (especially since we evaluate the function twice) and very verbose, and we think that the vast majority of functions *do* propagate nulls. We could decide to change the default to always propagate, producing:

```sql
WHERE (FOO(p) = x) OR (p IS NULL) AND (x IS NULL))")  -- When p is nullable, or:
WHERE FOO(p) = x  -- When p is non-nullable
```

Note: this will affect both UDFs and not just provider writer.

**Comment by pmiddleton** [comment]
What if we add the ability for provider and UDF to specify how a function works in regards to nullability.  That way regardless of what you set as a default approach the user/provdier has a way to reverse it in a per function basis if needed?

**Comment by maumar** [comment]
@pmiddleton https://github.com/dotnet/efcore/issues/19609

**Comment by smitpatel** [comment]
Current default is set to nullability propagates to true. @maumar is working on making the default false.

**Comment by roji** [comment]
Design discussion: both defaults here have their pitfalls:

1. Assuming parameters propagate nullability can cause wrong results in cases where they don't in the actual function
2. Assuming the opposite causes the function to be evaluated twice (see sample above), which can cause both a perf degradation and data corruption in case the function has side-effects.

Since there is no sensible default, it seems we should lean towards forcing users mapping functions to make an informed decision, probably by obsoleting overloads which don't allow nullability propagation to be specified.

**Comment by smitpatel** [comment]
- Current default remains as is
- Obsolete overloads in SqlExpressionFactory which does not take null propagation info.

**Comment by maumar** [comment]
poaching this as I have some clean-up to do in this area anyway

**Comment by roji** [comment]
Shouldn't the bad overloads be obsoleted on ISqlExpressionFactory as well? Places where the service is injected via an interface don't get obsolete warnings although the implementations are obsoleted.
