### ISSUE TITLE
async queries interface/API

### ISSUE THREAD

**Issue by carlin-q-scott** [dotnet/efcore#19743]
I would like to restrict my team to using async queries, but currently we can only access async queries through [extension methods on IQueryable](https://docs.microsoft.com/en-us/ef/core/querying/async).

Could we get an IQueryableAsync that only exposes the async queries? It should also include the IQueryable methods that are query builders.

**Comment by ajcvickers** [comment]
@carlin-q-scott This is outside of the scope of the EF. You could request changes to the base class libraries for .NET, but it seems extremely unlikely to me that a big change to the way LINQ is structured will be made.
