### ISSUE TITLE
Generate copy-paste queries for logging

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#19756]
ToQueryString creates queries that define parameters and can therefore be copy-pasted into SSMS or similar for debugging and analysis. A few people have since suggested we should do the same for logging.

The downside might be that the log now contains SQL statements that aren't actually used by the runtime--that is, the parameter declarations. We could consider commenting these if we think it's otherwise confusing. (I'm not convinced this is necessary.)

**Comment by jwyza-pi** [comment]
ToQueryString is great for queries you control.  But for things like `DbContext.SaveChangesAsync()` it doesn't appear there is any alternative other than the current method of "copy from log, manually reconstruct the parameter declarations/assignments".
