### ISSUE TITLE
EF 2.2 varchar to numeric cannot be cast automatically on update

### ISSUE THREAD

**Issue by Stan0v** [dotnet/efcore#19762]
Reproduced on PostgreSql

### **Steps to reproduce:**
Create some DB with table with column of varchar type based on model with string type
Then alter the model field that corresponds to this column to decimal type and create migration. That's will produce next code:
migrationBuilder.AlterColumn<decimal>(
                name: "SomeColumn",
                table: "SomeTable",
                type: "decimal(24, 8)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "varchar");

Next if you try to generate script using dotnet ef migrations script, then the scipt will be fine and contains: 
ALTER TABLE "SomeTable" ALTER COLUMN "SomeColumn" TYPE decimal(24, 8) USING "InitialSideAmount"::numeric(24, 8);
ALTER TABLE "SomeTable" ALTER COLUMN "SomeColumn" SET NOT NULL;
ALTER TABLE "SomeTable" ALTER COLUMN "SomeColumn" DROP DEFAULT;

But if you'll try to run dotnet ef database update it will result: 42804: column "SomeColumn" cannot be cast automatically to type numeric

**Comment by roji** [comment]
Can you please reopen this Npgsql-specific issue in https://github.com/npgsql/efcore.pg?
