### ISSUE TITLE
Generate models for Views and Stored Procedures

### ISSUE THREAD

**Issue by camerontbelt** [dotnet/efcore#19768]
I inherited a legacy application that has hundreds of stored procedures and views across dozens of databases. It's quite time consuming to comb through and manually build models for any given view or stored procedure. 

I would like to be able to generate models based on these views and stored procedures to make development easier for migrating to EF Core.

**Comment by ErikEJ** [comment]
3.x allows you to scaffold views

**Comment by ajcvickers** [comment]
Stored proc scaffolding is tracked by #15105
