### ISSUE TITLE
SqliteParameter cannot bind a null value

### ISSUE THREAD

**Issue by DevinCarr** [dotnet/efcore#19775]
I noticed that when I have a null string set in a scenario like this:
```C#
var command = _db.CreateCommand();
command.CommandText = @"
INSERT INTO users (key, user)
VALUES ($key, $user);
";
command.Parameters.AddWithValue("$key", user.Key) // user.Key == "123"
command.Parameters.AddWithValue("$user", user.Name) // user.Name == (string)null
command.ExecuteNonQuery();
```
When executed, the parameter cannot be bound since the value is null. In this case though, it is okay that the name is sometimes null (via user input, etc.).

In [SqliteParameter.cs](https://github.com/dotnet/efcore/blob/8f7dda7f173012563477e90afb2b249084b10788/src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs#L206) there is a check to make sure that the `_value` is not null and throws the `InvalidOperationException` exception. (I could be misinterpreting the method by which a null should be bound to a parameter.) I also notice that in [SqliteValueParameter.cs](https://github.com/dotnet/efcore/blob/8f7dda7f173012563477e90afb2b249084b10788/src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs#L50) that the `_value` is also checked for null, but would correctly bind null via `BindNull()` if the exception is not thrown from SqliteParameter.cs.

Exceptions returned:
```
System.InvalidOperationException: Value must be set.
  Stack Trace:
      at Microsoft.Data.Sqlite.SqliteParameter.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
```

### Additional context

Microsoft.Data.Sqlite version: 3.1.1
Target framework: netcoreapp3.0 (3.0.100)
Operating system: 
```
OS Name:     Windows
OS Version:  10.0.18362
OS Platform: Windows
RID:         win10-x64
```

**Comment by ajcvickers** [comment]
@DevinCarr ADO.NET DbParameter types require the use of `System.DBNull` here. A C# null is treated as unknown by these APIs.
