### ISSUE TITLE
Entity Framework core 3.1.1 Multilevel Inheritance

### ISSUE THREAD

**Issue by mnoursi** [dotnet/efcore#19787]
An exception is thrown while running add-migration (EF core 3.1.1):

 **CLR property 'DiscriminatorLevel2Id' cannot be added to entity type 'CustomerBase' because it is declared on the CLR type 'InternalCustomer'** 

### Steps to reproduce

The following shows the needed hierarchy (briefly):
``` C#

public class CustomerBase
	{
		public int Id { get; protected set; }
                public int CustomerTypeId { get; protected set; }
	}

public class InternalCustomer: CustomerBase
	{
		public decimal points { get; protected set; }
                public int DiscriminatorLevel2Id { get; protected set; }
	}

public class ExternalCustomer: CustomerBase
	{
                public string Name { get; protected set; }
	}

public class VIPCustomer: InternalCustomer
	{
                public string CardNumber { get; protected set; }
	}

public class RegularCustomer: InternalCustomer
	{
                public int ParentId { get; protected set; }
	}

```
Mapping looks like:

``` C#

// Discriminator (Level 1)
modelBuilder.Entity<CustomerBase>()              
            .HasDiscriminator(b => b.CustomerTypeId)
            .HasValue<InternalCustomer>((int)CustomerType.Internal)
            .HasValue<ExternalCustomer>((int)CustomerType.External);

// Discriminator (Level 2) 
modelBuilder.Entity<InternalCustomer>()
         .HasDiscriminator(b => b.DiscriminatorLevel2Id)
         .HasValue<VIPCustomer>((int)DiscriminatorLevel2.VIP)
         .HasValue<RegularCustomer>((int)DiscriminatorLevel2.Regular);
```

- Is "Multilevel Inheritance TPH" supported using "Discriminator"  by Entity Framework Core 3.1.1?
- If not, then How will "Multilevel inheritance " be implemented, what are changes needed to be done in the above example?

### Further technical details

EF Core version: 3.1.1

**Comment by mnoursi** [comment]
It seems  Multilevel inheritance is not supported by EF core 3.1,
the following link may have a useful workaround:

https://stackoverflow.com/questions/60042465/entity-framework-core-3-1-1-multilevel-inheritance

**Comment by ajcvickers** [comment]
@mnoursi We see requests for multilevel inheritance occasionally. However, the complexity cost of supporting it is quite high in what is already a complex area. Therefore based on current levels of interest we are not going to implement this. As always, we could revisit this if demand becomes high.
