### ISSUE TITLE
Why is HasColumnType included for every property in migrations

### ISSUE THREAD

**Issue by tidyui** [dotnet/efcore#19797]
We have a pretty normal use-case in our products. In test environments and in integration-tests we run everything on `SQLite` for portability, but in production we run `SQL Server` or `SQL Azure`. Up to version `2.2.4` migrations created using either `SQLite` or `SQLServer` would produce the same output and be database agnostic, however after upgrading to `3.1` this is not the case. 

For example, let's say we have a column which is a `string` with a max length of 128. In previous version this would produce the following code in the `Designer` file.

~~~ csharp
b.Property<string>("MyColumn")
    .IsRequired()
    .HasMaxLength(256);
~~~

However, after upgrading to `3.1` it produces the following result:

~~~ csharp
b.Property<string>("MyColumn")
    .IsRequired()
    .HasColumnType("TEXT")
    .HasMaxLength(256);
~~~

This of course causes the migration to crash on `SQL Server` as text can't have a max length. As a test I have gone through the migrations we've done with `3.1` and removed **every** occurrence of `HasColumnType` and as suspected the migration works just the same on `SQLite` as it did with the statements there.

What is the reason behind this, because it sure makes life complicated. Either we have to manually process every migration created **or** we have to split the repository project into three projects, one with the data entities and logic and two projects containing migrations for each respective database provider. None of these options sounds appealing.

Best regards from Sweden

Håkan

**Comment by AndriySvyryd** [comment]
@tidyui The technical reason is that the CLR type is not always enough to determine the column type for some providers (e.g. `string` could be TEXT, VARCHAR, ENUM or GUID). We can't rely on the model snapshot, as it's only available for the last migrations and we can't predict whether the column type will be ambiguous.

In general we moved away from the idea of generating migrations that can be used for different providers as that quickly breaks down for complex real-life models. There are two [recommended ways of dealing with this ](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli):

- Generating a migration set for every provider
- Manually merging the migrations using conditions
