### ISSUE TITLE
If an entity MyEntity has a property called MyProp, I cannot create an entity called MyEntity_MyProp. How do I fix that?

### ISSUE THREAD

**Issue by andrerpena** [dotnet/efcore#1979]
I'm using Entity Framework 6, with POCO and fluent-API and I've noticed an annoying bug.

If I have an entity called `MyEntity` and this entity has a property called `MyProp`, that makes it impossible to create an entity called `MyEntity_MyProp`.

Exception:

```
The item with identity 'MyEntity_MyProp' already exists in the metadata collection.\r\nParameter name: item
```

The error immediately goes away if I rename any of the entities, or rename the properties.

The "bug" is obvious: the key [EntityName]_[PropertyName] must be unique in the metadata collection.

Screenshot:

![Image](http://i.imgur.com/vE8EOPj.png)

I'm migrating a huge Entity Framework model with 390+ classes from EF 4, database first, to EF 6, code first, with fluent-API. It's out of question to rename the entities or the tables.

How do I solve that?

**Comment by maumar** [comment]
filed bug in codeplex instead - that's where EF6 issues should be reported:
https://entityframework.codeplex.com/workitem/2727
