### ISSUE TITLE
RevEng: Let IDatabaseModelFactory override the scaffolded connection string

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#19799]
ErikEJ.EntityFrameworkCore.SqlServer.Dacpac currently scaffolds something like this:

``` csharp
.UseSqlServer("Chinook.dacpac")
```
Because that's the "connection string" you pass to `dotnet ef dbcontext scaffold`. We should add a hook for IDatabaseModelFactory implementations to override the connection string that gets scaffolded. We'd probably do this using an annotation on DatabaseModel.

cc @ErikEJ

**Comment by lajones** [comment]
@ErikEJ - FYI - the fix for this was just checked in. Just add `databaseModel[ScaffoldingAnnotationNames.ConnectionString] = yourOverridingConnectionString` in your implementation of `IDatabaseModelFactory.Create()`.

**Comment by ErikEJ** [comment]
Fantastic - is 5.0 preview1 out?

**Comment by ajcvickers** [comment]
@ErikEJ Currently tentatively scheduled for sometime in March.

**Comment by ErikEJ** [comment]
@lajones This has now been implemented! Thanks!
