### ISSUE TITLE
SaveChangesAsync on DbContext throws out without exceptions or errors

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [dotnet/efcore#19804]
I have a set of handler with async methods that I axecute one by one in foreach cycle, in one of them I then call SaveChangesAsync and it throws my code back to initial foreach cycle without any exceptions at all and skipping all code execution.

Changing SaveChangesAsync to SaveChanges works, but that's not a solution

That's where method are executed - https://gist.github.com/CaCTuCaTu4ECKuu/8c5c8b4717e27ce4fe6b054cff839dcc#file-domaineventmanager-cs-L114
Handler on **line 114** is where error happens and it throws me to next iteration in cycle without any errors or exceptions

Error happens here - https://gist.github.com/CaCTuCaTu4ECKuu/5a6dc2e76ced8d594648a7df163d10fc#file-efrepository-L16

TargetFramework: netcoreapp2.2
Packages:
- Microsoft.AspNetCore.All
- Microsoft.EntityFrameworkCore 2.2.6
Operating system: W10 1909
IDE: Visual Studio 2019 16.4.3

**Comment by ajcvickers** [comment]
@CaCTuCaTu4ECKuu If you debug into the code and step over the SaveChangesAsync all, what happens in the debugger?

**Comment by CaCTuCaTu4ECKuu** [comment]
@ajcvickers Nothing. It just jump all the way back to part where next iteration begin.
I enabled Common Language Runtime Exceptions as someone suggested but no errors. I can show it on video, but people dont believe me when I say that it throws without any errors. Code doesn't execute after line of code where savechanges is and it does not run in background (I tried with cancellation token with 1s delay - same behavior).

**Comment by ajcvickers** [comment]
@CaCTuCaTu4ECKuu I certainly believe you, but unfortunately that doesn't help me reproduce the problem. :-) Probably the best way forward here is for you to attempt to create a small, runnable project that reproduces the issue. If you attach that here I'll see if I can reproduce what you're seeing.

**Comment by CaCTuCaTu4ECKuu** [comment]
Not sure if I can reproduce it myself in project other than this, there is a lot of code, but I'll try to make new project

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
