### ISSUE TITLE
EF Core doesn't auto-renew AAD token?

### ISSUE THREAD

**Issue by chandimar001** [dotnet/efcore#19808]
I am integrating Azure Active Directory with my .Net Core 2.2 service that uses entity framework. I followed the steps in the following threads:
https://github.com/dotnet/efcore/issues/11928
https://github.com/dotnet/efcore/issues/13261

My code looks like this:

```
public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options) : base(options)
        {
            var conn =  (SqlConnection) this.Database.GetDbConnection();
            conn.AccessToken = (newAzureServiceTokenProvider()).GetAccessTokenAsync("https://database.windows.net/").Result;
        }
        public DbSet<Item> Items { get; set; }
    }

//Startup.cs
services.AddDbContext<ToDoDbContext>(options =>
{
    var connStr = Configuration["ConnectionString"];
    options.UseSqlServer(connStr);
});
```
Everything works great at the start. The service gets the token from AAD and successfully connects to the database. However, the token expires after an hour and the code fails with a "Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON' exception.

How do I make EF Core create a new connection with a fresh token?

**Comment by ajcvickers** [comment]
@chandimar001 At the moment that isn't any built-in support for this; we will consider it as part of #13261. Please vote for that issue.

As a workaround, you could use an [`IDbCommandInterceptor`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.idbcommandinterceptor?view=efcore-3.1) to renew the token if needed before each time the database is accessed.

**Comment by OskarKlintrot** [comment]
Won't `AzureServiceTokenProvider` retrieve a new token if needed? Or does your DbContext live long enough for the token to expire?

**Comment by ajcvickers** [comment]
@OskarKlintrot I was assuming based on the context (no pun intended) that this was a long lived...err context. As always, a short lifetime (single unit-of-work) is preferred.

**Comment by chandimar001** [comment]
AzureServiceTokenProvider retrieves the new token automatically (5 minutes before it expires), but I need Entity Framework to establish/update the current connection with the new token token.

I'm fairly new to Entity Framework. The DBContext is indeed long lived because I thought you shouldn't create connections frequently for perf reasons. Searching the web on the topic implies I should be using a scoped DB connection instead of singleton. If I do that, then this becomes a non-issue. Is that what you are referring to?

**Comment by ajcvickers** [comment]
@chandimar001 Correct.
