### ISSUE TITLE
Query: add validation to warn about required navigations pointing to entity with query filter

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#19801]
When model has required navigation which points to the entity, which has query filter we could run into a problematic situation. If the entity is filtered out by query filter we run into referential integrity issue (required entity is not there), so currently we remove the parent entity also. This might be unexpected - we should detect this case during model validation. 

Ideally this case would be handled by having a query filter also on the other side of the navigation, effectively filtering out entities whose other side of the navigation has been pruned by it's query filter (soft cascade delete of sorts)

**Comment by smitpatel** [comment]
Design meeting decision:
- We will add a warning in model validation to warn about potential danger of having a query filter defined on principal end without query filter on dependent side when dependent side has non-nullable FK. If FK is non-nullable and principal is filtered out then dependents become orphan which is not something a true non-nullable FK would allow.
