### ISSUE TITLE
Allow specifying different column names per table in TPT, TPC or entity splitting

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#19811]
E.g. `int Id` could be mapped to `int Id` in `People` and to `string CustomerId` in `Customers`

## TPC:
```C#
    modelBuilder.Entity<Person>().ToTable("People")
        .InheritPropertyMapping(false);  
    modelBuilder.Entity<Customer>().ToTable("Customers", t =>
        {
            t.Property(c => c.Id).HasColumnName("CustomerId");
        });
```

## Entity splitting:
```C#
    modelBuilder.Entity<Customer>(cb =>
    {
        cb.ToTable("Customers");
        cb.SplitToTable("CustomerDetails", t =>
        {
            t.Property(c => c.Id).HasColumnName("CustomerId");
        })
    };
```

Also allow to map a base property to the derived table in TPT

## TPT:
```C#
    modelBuilder.Entity<Person>().ToTable("People");  
    modelBuilder.Entity<Customer>().ToTable("Customers", t =>
        {
            t.Property(c => c.Id).HasColumnName("CustomerId");
        });
```

Related: https://github.com/dotnet/efcore/issues/17270#issuecomment-588037768

**Comment by smitpatel** [comment]
A possible side-effect in query, that if you are writing query like `context.People.Where(e => e.Id == 5)` then translating that could be complicated, since now you have to apply the predicate to both the tables separately before generating Union. Which could easily go downhill when the Id start being used in complex query operators like join conditions etc.

**Comment by smitpatel** [comment]
Just different column names or just different but database implicit convertible column types should be ok.

**Comment by ajcvickers** [comment]
Not to implementer: see scenario in #22753.

**Comment by Racerboymatt** [comment]
Ok, so my apologies if this is a stupid question but I'm trying to follow the chain of responses here.  My question is that it appears that EF Core 5.0 does NOT currently support a TPT mapping where the Base Type PK name and the Derived Type (Sub Type) PK name do not have the same name.  Meaning, for now, the base type PK name and all derived type PK names must be the same column name in all tables.  Is that correct.  I have tried lots of different ways to do this and I can find no way to do it in the current 5.0 release.  Is the EF Team is planning on releasing this in the 6.0 release?

Sorry for my stupid question for clarification.

**Comment by AndriySvyryd** [comment]
@Racerboymatt You are correct. Currently there is no supported way of having different column or PK names for tables mapped to derived types in TPT

**Comment by overdunne** [comment]
We ended up creating a view for one of the tables in TPT, that renames the PK column to match the other, then mapping to the view as if it were the table.

**Comment by AndriySvyryd** [comment]
> which forces me to adjust my code generator for this particular scenario (and generate clumsy code for compound PKs too). While that's of course doable, it begs the question why it wasn't solved behind the scenes: the target table is different, Manager inherits from Employee in the model, the field name is different in the pk field mapping for Manager, it maps the inherited field EmployeeId to a field that's named differently in the mapping than in Employee... gee, could it be it might be it remaps the pk field!?

In general, we err on the side of having simpler rules instead of trying to guess user's intent. This wouldn't help you in particular, but the users can now write their own conventions to handle situations like this.

**Comment by Ygilany** [comment]
@AndriySvyryd does this fix cover indexes and primary keys? looks like in my TPT implementation all the subtypes end up with the same primary key index, which is an issue on Postgres?
