### ISSUE TITLE
Play nice with environment variables

### ISSUE THREAD

**Issue by Rast1234** [dotnet/efcore#19816]
Our projects get "environment" name from a variable different from `ASPNETCORE_ENVIRONMENT`. More, our environments have different names, eg `dev, stage, pre, prod`. We also did not like the default environment being `Production`. In general, our `BuildHostConfiguration` looks like this:

```c#
new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string>{{WebHostDefaults.EnvironmentKey, "dev"}})
	.AddEnvironmentVariables()
	.AddEnvironmentVariables("ASPNETCORE_")
```
Last line exists for compatibility with other options like `ASPNETCORE_URLS`.

Applications work fine. **EF CLI does not**, because it inserts ASPNETCORE_ENVIRONMENT right into env vars, so there is no way to know if it was there in the first place (or absent). Relevant code:

https://github.com/dotnet/efcore/blob/0d76bbf45a42148924b413ef8f37bf49c1ce10d3/src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs#L63

When we implement `IDesignTimeDbContextFactory` and build our HostConfiguration there, env vars are already poisoned by this code.

My suggestion is to provide ConfigurationBuilder pre-seeded with `WebHostDefaults.EnvironmentKey` and let users override (or ignore it) without messing with OS env vars.

### Steps to reproduce
1. build host configuration for asp.net core application yourself
2. read environment name from any source other than environment variables or read it from a variable other than `ASPNETCORE_ENVIRONMENT`
3. after that read `ASPNETCORE_*` variables for compatibility
4. application works as expected
5. EF CLI like `dotnet ef migrations list` sets wrong environment because it writes to ASPNETCORE_ENVIRONMENT env variable.
6. *Asp.net core treats default environment as "Production", so there is incinsistency between framework and tools.*

### Further technical details

EF Core version: 2.2.1-servicing-10028
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: netcoreapp2.2
Operating system: Windows 10 1607, CentOS, Debian (different versions)
IDE: Visual Studio 2017 Professional 15.9.6

**Comment by Rast1234** [comment]
Current workaround is to detect if CreateWebHostBuilder is called by EF CLI and undo setting env var:

```c#
if (Assembly.GetEntryAssembly()?.GetName().Name?.ToLowerInvariant() == "ef")
{
	if (System.Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
	{
		System.Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", null);
	}
}
```

**Comment by bricelam** [comment]
I wonder if we can remove that code as part of #8695

**Comment by ajcvickers** [comment]
Following discussions, closing this as a duplicate of #8695 since that issue covers the underlying problem of handling platform-specific environment variables in a platform-agnostic package/tool.
