### ISSUE TITLE
Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19818]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/889199/microsoftaspnetcoreidentityentityframeworkcore-311.html)._

---
If you use NuGet to update version 3.1.0 of this package to 3.1.1, the following exception occurs in ConfigureServices, where AddEntityFrameworkStores is called:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

Reverting back to 3.1.0 is the current solution for me.

---
#### fatimah hamid on 1/18/2020, 01:23 PM: 

<p>I have the same issue , any solution?</p>

#### paul marangoni on 1/18/2020, 02:05 PM: 

<p>I reverted back to 3.1.0 for a bunch of NuGet packages. These errors/bugs are occurring much more frequently lately.  I'm realizing that I can't trust Microsoft to properly test their software releases anymore.  It's very frustrating and I end up wasting a lot of time.</p>

#### Visual Studio Feedback System on 1/18/2020, 09:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### sumit.bohra on 1/19/2020, 11:44 AM: 

<p>Please help to resolve this issue</p><p>System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
  Source=&lt;Cannot evaluate the exception source&gt;
  StackTrace:
&lt;Cannot evaluate the exception stack trace&gt;</p>

#### Visual Studio Feedback System on 1/19/2020, 09:51 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Wayne Thompson on 1/20/2020, 04:04 PM: 

<p>I have this issue on some machines only.</p>

#### Cyrus Sullivan on 1/22/2020, 06:38 PM: 

<p>same problem, just updates all Nuget packages and now this</p>

#### Julius LIMSON on 1/22/2020, 10:07 PM: 

<p>same. every solve issue introduces another problem. </p>

#### Patrick Daniel on 1/27/2020, 01:25 PM: 

<p>I also have this issue. Updating the EF packages to 3.1.1 caused my app to crash on heroku. I had to rollback all of them to 3.1. I hope a fix is found soon.</p>

---
#### sumit.bohra solved on 1/19/2020, 11:43 AM, -2 votes: 

<p>System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
  Source=&lt;Cannot evaluate the exception source&gt;
  StackTrace:
&lt;Cannot evaluate the exception stack trace&gt;</p>

**Comment by ajcvickers** [comment]
@Pilchie @mkArtakMSFT Do these look like manifestations of https://github.com/dotnet/aspnetcore/issues/18334 or is this something different?

**Comment by Pilchie** [comment]
Yes, it's an instance of that when people update the NuGet package but haven't installed the 3.1.1 runtime yet.

**Comment by ajcvickers** [comment]
Thanks @Pilchie. Closing as external. See https://github.com/dotnet/aspnetcore/issues/18334 for more info.
