### ISSUE TITLE
Map Null date in efcore relational DB

### ISSUE THREAD

**Issue by nexawo** [dotnet/efcore#19810]
I want to map null date with entity but when I send  null date it assign default date after mapping.
In Db date is required. 

I Wrote a test where I check if date is null from frontend then it should throw an error on insertion but when I do that then after the mapping line it assign default value {[01/01/0001 12:00:00 AM]} to my date variable.
As you can see in below fig where in first image start date is null and after it maps the start date gets a default value.

![11](https://user-images.githubusercontent.com/55268813/73914500-3a37e200-48db-11ea-8c45-458aef7f2f55.PNG)
![12](https://user-images.githubusercontent.com/55268813/73914504-3c01a580-48db-11ea-8cd3-2ac169a8aaa9.PNG)

**Comment by smitpatel** [comment]
StartDate in second image after mapping via AutoMapper is `DateTime`. `DateTime` is a struct which is not nullable. If you don't assign it a value then it initializes to default value which is what you are seeing.

If the date is required in Db then you cannot send null to Db. There is mismatch between your domain model and database model. If StartDate can be null then database model should also accept null.
