### ISSUE TITLE
请问？

### ISSUE THREAD

**Issue by CN317910** [dotnet/efcore#19812]
厂商:HUAWEI 
 型号： VCE-AL00 
 Android sdk 版本： 28
 Rom : Unknown
 DeviceId : 57937d9a8f84800e
 网络类型 : Wifi
 屏幕宽度 : 1080
 屏幕高度 : 2090
 AvailableMemory ： 0.95 GB
 时间 : 2020-02-06 17:50:48
 运营商 ：中国移动
 本机IP : 192.168.1.4
 本地DNS : 未知
 Device UID : 57937d9a8f84800e
 
 
 Nickname : 青年公益
 UserId : 19293354
 Haruki : 4.19.0
 VersionCode : 2019004190
 TinkerId : null
 NewTinkerId : null
 BuildTime : 2020-01-15 10:50:54

===== curl -I https://s0.jianshuapi.com/ping =====
s0.jianshuapi.comapi.jianshu.io

===== ping : s0.jianshuapi.com=====
PING s0.jianshuapi.com (106.75.9.11) 56(84) bytes of data.
64 bytes from 106.75.9.11: icmp_seq=1 ttl=49 time=34.4 ms
64 bytes from 106.75.9.11: icmp_seq=2 ttl=49 time=42.5 ms
64 bytes from 106.75.9.11: icmp_seq=3 ttl=49 time=44.0 ms
64 bytes from 106.75.9.11: icmp_seq=4 ttl=49 time=51.1 ms
64 bytes from 106.75.9.11: icmp_seq=5 ttl=49 time=71.3 ms
64 bytes from 106.75.9.11: icmp_seq=6 ttl=49 time=42.3 ms
64 bytes from 106.75.9.11: icmp_seq=7 ttl=49 time=43.9 ms
64 bytes from 106.75.9.11: icmp_seq=8 ttl=49 time=40.8 ms
64 bytes from 106.75.9.11: icmp_seq=9 ttl=49 time=36.7 ms
64 bytes from 106.75.9.11: icmp_seq=10 ttl=49 time=42.8 ms

--- s0.jianshuapi.com ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9013ms
rtt min/avg/max/mdev = 34.443/45.020/71.366/9.744 ms

===== ping : api.jianshu.io=====
PING api.jianshu.io (106.75.9.11) 56(84) bytes of data.
64 bytes from 106.75.9.11: icmp_seq=1 ttl=49 time=34.7 ms
64 bytes from 106.75.9.11: icmp_seq=2 ttl=49 time=44.5 ms
64 bytes from 106.75.9.11: icmp_seq=3 ttl=49 time=46.4 ms
64 bytes from 106.75.9.11: icmp_seq=4 ttl=49 time=44.7 ms
64 bytes from 106.75.9.11: icmp_seq=5 ttl=49 time=43.7 ms
64 bytes from 106.75.9.11: icmp_seq=6 ttl=49 time=42.3 ms
64 bytes from 106.75.9.11: icmp_seq=7 ttl=49 time=35.3 ms
64 bytes from 106.75.9.11: icmp_seq=8 ttl=49 time=34.2 ms
64 bytes from 106.75.9.11: icmp_seq=9 ttl=49 time=34.1 ms
64 bytes from 106.75.9.11: icmp_seq=10 ttl=49 time=35.0 ms

--- api.jianshu.io ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9012ms
rtt min/avg/max/mdev = 34.123/39.539/46.423/4.933 ms

===== ping : www.jianshu.com=====
PING www.jianshu.com.w.cdngslb.com (58.49.248.248) 56(84) bytes of data.
64 bytes from 58.49.248.248: icmp_seq=1 ttl=57 time=15.2 ms
64 bytes from 58.49.248.248: icmp_seq=2 ttl=57 time=17.7 ms
64 bytes from 58.49.248.248: icmp_seq=3 ttl=57 time=18.3 ms
64 bytes from 58.49.248.248: icmp_seq=4 ttl=57 time=37.7 ms
64 bytes from 58.49.248.248: icmp_seq=5 ttl=57 time=15.9 ms
64 bytes from 58.49.248.248: icmp_seq=6 ttl=57 time=14.6 ms
64 bytes from 58.49.248.248: icmp_seq=7 ttl=57 time=21.7 ms
64 bytes from 58.49.248.248: icmp_seq=8 ttl=57 time=43.2 ms
64 bytes from 58.49.248.248: icmp_seq=9 ttl=57 time=18.9 ms
64 bytes from 58.49.248.248: icmp_seq=10 ttl=57 time=17.7 ms

--- www.jianshu.com.w.cdngslb.com ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9012ms
rtt min/avg/max/mdev = 14.643/22.124/43.233/9.448 ms

===== ping : s0.jianshuapi.com=====
PING s0.jianshuapi.com (106.75.9.11) 56(84) bytes of data.
64 bytes from 106.75.9.11: icmp_seq=1 ttl=49 time=35.9 ms
64 bytes from 106.75.9.11: icmp_seq=2 ttl=49 time=42.6 ms
64 bytes from 106.75.9.11: icmp_seq=3 ttl=49 time=43.9 ms
64 bytes from 106.75.9.11: icmp_seq=4 ttl=49 time=45.0 ms

**Comment by ajcvickers** [comment]
Machine translation:

## Excuse me?

Manufacturer: HUAWEI
Model: VCE-AL00
Android sdk version: 28
Rom : Unknow
DeviceId : 57937d9a8f84800e
Network Type: Wifi
Screen width: 1080
Screen height: 2090
AvailableMemory: 0.95 GB
Time: 2020-02-06 17:50:48
Operator: China Mobile
Native IP: 192.168.1.4
Local DNS: Unknown
Device UID : 57937d9a8f84800e

Nickname : Youth
UserId : 19293354
Haruki : 4.19.0
VersionCode : 2019004190
TinkerId : null
NewTinker Id : null
BuildTime : 2020-01-15 10:50:54

curl -I https://s0.jianshuapi.com/ping
s0.jianshuapi.comapi.jianshu.io

Ping : s0.jianshuapi.com
PING s0.jianshuapi.com (106.75.9.11) 56 (84) bytes of data.
64 bytes from 106.75.9.11: icmp_seq s 1 ttl-49-time-34.4 ms
64 bytes from 106.75.9.11: icmp_seq s 2 ttl s 49 time s 42.5 ms
64 bytes from 106.75.9.11: icmp_seq s 3 ttl-49-time-44.0 ms
64 bytes from 106.75.9.11: icmp_seq s 4 ttl-49-time-51.1 ms
64 bytes from 106.75.9.11: icmp_seq s 5 ttl s 49 time s 71.3 ms
64 bytes from 106.75.9.11: icmp_seq s 6 ttl-49-time-42.3 ms
64 bytes from 106.75.9.11: icmp_seq s 7 ttl-49-time-43.9 ms
64 bytes from 106.75.9.11: icmp_seq s 8 ttl-49-time-40.8 ms
64 bytes from 106.75.9.11: icmp_seq s 9 ttl-49-time-36.7 ms
64 bytes from 106.75.9.11: icmp_seq s 10 ttl s 49 time s 42.8 ms

--- s0.jianshuapi.com ping sstatistics ---
10 packets, 10 received, 0% packet loss, time 9013ms
rtt min/avg/max/mdev s 34.443/45.020/71.366/9.744 ms

Ping : api.jianshu.io
PING api.jianshu.io (106.75.9.11) 56 (84) bytes of data.
64 bytes from 106.75.9.11: icmp_seq s 1 ttl-49-time-34.7 ms
64 bytes from 106.75.9.11: icmp_seq s 2 ttl s 49 time s 44.5 ms
64 bytes from 106.75.9.11: icmp_seq 3 ttl-49-time-46.4 ms
64 bytes from 106.75.9.11: icmp_seq s 4 ttl s 49 time s 44.7 ms
64 bytes from 106.75.9.11: icmp_seq s 5 ttl s 49 time s 43.7 ms
64 bytes from 106.75.9.11: icmp_seq s 6 ttl-49-time-42.3 ms
64 bytes from 106.75.9.11: icmp_seq s 7 ttl-49-time-35.3 ms
64 bytes from 106.75.9.11: icmp_seq s 8 ttl-49-time-34.2 ms
64 bytes from 106.75.9.11: icmp_seq s 9 ttl-49-time-34.1 ms
64 bytes from 106.75.9.11: icmp_seq s 10 ttl-49-time-35.0 ms

--- api.jianshu.io ping sstatistics ---
10 packets, 10 received, 0% packet loss, time 9012ms
rtt min/avg/max/mdev s 34.123/39.539/46.423/4.933 ms

Ping : www.jianshu.com
PING www.jianshu.com.w.cdngslb.com (58.49.248.248) 56 (84) bytes of data.
64 bytes from 58.49.248.248: icmp_seq s 1 ttl-57 time-15.2 ms
64 bytes from 58.49.248.248: icmp_seq s 2 ttl-57 time-17.7 ms
64 bytes from 58.49.248.248: icmp_seq s 3 ttl-57 time-18.3 ms
64 bytes from 58.49.248.248: icmp_seq s 4 ttl-57 time-37.7 ms
64 bytes from 58.49.248.248: icmp_seq s 5 ttl-57 time-15.9 ms
64 bytes from 58.49.248.248: icmp_seq s 6 ttl-57 time-14.6 ms
64 bytes from 58.49.248.248: icmp_seq s 7 ttl-57 time-21.7 ms
64 bytes from 58.49.248.248: icmp_seq s 8 ttl-57 time-43.2 ms
64 bytes from 58.49.248.248: icmp_seq s 9 ttl-57 time-18.9 ms
64 bytes from 58.49.248.248: icmp_seq s 10 ttl-57 time-17.7 ms

--- www.jianshu.com.w.cdngslb.com ping sstatistics ---
10 packets, 10 received, 0% packet loss, time 9012ms
rtt min/avg/max/mdev s 14.643/22.124/43.233/9.448 ms

Ping : s0.jianshuapi.com
PING s0.jianshuapi.com (106.75.9.11) 56 (84) bytes of data.
64 bytes from 106.75.9.11: icmp_seq s 1 ttl-49-time-35.9 ms
64 bytes from 106.75.9.11: icmp_seq s 2 ttl s 49 time s 42.6 ms
64 bytes from 106.75.9.11: icmp_seq 3 ttl-49-time-43.9 ms
64 bytes from 106.75.9.11: icmp_seq s 4 ttl-49-time-45.0 ms

**Comment by ajcvickers** [comment]
@CN317910 This site is for Entity Framework Core issues. I am closing your issue because it is not about Entity Framework Core.

**Comment by CN317910** [comment]
156962
