### ISSUE TITLE
Foreign Key Constraint Exception on Add() when key = 0

### ISSUE THREAD

**Issue by sdpollack** [dotnet/efcore#19829]
I am creating a row in a many-to-many linking table.  The foreign key value is 0.  I am getting Microsoft.Data.SqlClient.SqlException: 'The INSERT statement conflicted with the FOREIGN KEY constraint ..."  Digging into the call stack I see that the value has been changed from 0 to -2147482647.  It works fine with other rows.  It only fails with the row whose key value is 0.  I used the 0 key value for a row that the application requires and it prevents the user from deleting that row.

Also writing the same data using direct SQL works (no FK exception) because I'm correctly specifying the '0' value.

I don't understand why my '0' key is being changed to '-2147482647' by EF Core.

### Steps to reproduce

What steps can we follow to reproduce the issue?

1) Create three tables: A, B, AB with primary keys and AB with foreign keys to A & B.  Tablke AB is the many-to-many linking table.
2) Manually add row to A with primary key of 0.  Add a row to B.
3) In EF Core Add() row to AB with the key values from the A and B rows created above.
4. On context.SaveChanges() the exception is produced.

Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=The INSERT statement conflicted with the FOREIGN KEY constraint "FK_NotificationGroupUnit_Units_UnitId". The conflict occurred in database "OperationDatabase", table "dbo.Units", column 'UnitId'.
The statement has been terminated.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

[Foreign Key issue.txt](https://github.com/dotnet/efcore/files/4172069/Foreign.Key.issue.txt)

### Further technical details

EF Core version: 3.1.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system:  Windows Enterprise
IDE:  Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment]
@sdpollack 

> It only fails with the row whose key value is 0

From your code, it looks like the key values are configured to use generated values. This means that the CLR default for key type acts as a sentinel value meaning, "no key value has yet been generated". This often means that it will get a temporary value (which is a large negative number like you are seeing) before saving changes. So basically, zero is not a valid key value if the application is using Identity columns to generate key values.

That being said, I am not able to reproduce exactly what you are seeing. It may be related to #19137 which we're planning to fix in a patch release. If not, then please attach a small, runnable project that reproduces what you are seeing.

**Comment by sdpollack** [comment]
I will create a small runnable project for you shortly.

But if the answer is that when using identity keys, manually inserted values such as zero are disallowed, that makes sense.  I would appreciate some indication of this limitation be documented.  I’ve found the documentation of setting an Explicit values into SQL Server IDENTITY columns<https://docs.microsoft.com/en-us/ef/core/saving/explicit-values-generated-properties#explicit-values-into-sql-server-identity-columns>, but I didn’t think this applied to my case since the row with the key of 0 is already in the database.   I have found no documentation of EF Core’s use of sentinel values.

**Comment by sdpollack** [comment]
Here is a small demo project that illustrates the issue I found.

[KeyOfZeroDemo.zip](https://github.com/dotnet/efcore/files/4181845/KeyOfZeroDemo.zip)

**Comment by ajcvickers** [comment]
@sdpollack Thanks for the code. I verified that this is indeed what is happening and filed https://github.com/aspnet/EntityFramework.Docs/issues/2105 to improve the documentation.
