### ISSUE TITLE
context is not updated after ExecuteSqlInterpolated unless context.dispose() is called

### ISSUE THREAD

**Issue by sadiqkhoja** [dotnet/efcore#19834]
I am unit testing my repository using ":memory:" sqlite connection. Every method is working correctly except the one which is using ExecuteSqlInterpolated. 
To setup tests, I am adding records to DbSet. If I dispose the context after adding records then ExecuteSqlInterpolated works correctly. Not sure if this is a bug or I'm missing something in my understanding.

### Steps to reproduce
Here's the code to reproduce the problem:

``` C#
var connection = new SqliteConnection("DataSource=:memory:");
connection.Open();
var options = new DbContextOptionsBuilder<MYContext>()
		.UseSqlite(connection)
		.Options;

var context = new MYContext(options);
context.Database.EnsureCreated();
context.Images.Add(new DAL.DataModels.Images()
{
	Id = 1,
	Thumbnail = null,
	Url = "https://www.example.com"
});
context.SaveChanges();
// context.Dispose(); // works if uncomment these two lines
// context = new MYContext(options); // works if uncomment these two lines
var result = context.Database.ExecuteSqlInterpolated($"UPDATE images SET Thumbnail = 'new value' WHERE id = 1");
Assert.Equal(1, result);
Assert.Equal("new value", context.Images.Find(1).Thumbnail);
```

### Further technical details

EF Core version: 3.0.0
Database provider: InMemory
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.2

**Comment by smitpatel** [comment]
According to documentation of Find
> Finds an entity with the given primary key values. If an entity with the given primary key values is being tracked by the context, then it is returned immediately without making a request to the database.

Since you are using same context which saved the entity, image is still being tracked so while values are saved in database, the way you are reading value, the object would not contain updated values still.

**Comment by sadiqkhoja** [comment]
thanks, in that case I'll close this issue.
