### ISSUE TITLE
Removal of ReferenceOwnershipBuilder

### ISSUE THREAD

**Issue by cxc256** [dotnet/efcore#19840]
Removing ReferenceOwnershipBuilder and replacing it with ReferenceNavigationBuilder has blown up a library that I use in all my projects and has caused a real headache.

Why would you change the name and not have any backwards compatability?!?!!?

**Comment by ajcvickers** [comment]
@cxc256 The reason for the change is documented here: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#configuration-api-for-owned-type-relationships-has-changed
