### ISSUE TITLE
Reusing Connectionstring variable for multiple DataContext causes Entityframework to point to wrong Db

### ISSUE THREAD

**Issue by prashantchoudhary** [dotnet/efcore#19849]
I am trying to use two DataContexts in my code. But if reuse the connection string variable with different values, EF Core fails to resolve and probably binds to the wrong schema.

### Steps to reproduce

What steps can we follow to reproduce the issue?
This doesn't work and throws ` Invalid object name *modelName*`

``` C#
string connectionString = GetConfigurationConnectionStringThatPointsToOtherSchema();
_serviceDescriptors.AddDbContext<ConfigDbContext>(options => options.UseSqlServer(connectionString));
connectionString = Configuration["ConnectionStrings:OnaymatikDbConnection"];
_serviceDescriptors.AddDbContext<CompanyDbContext>(options => options.UseSqlServer(connectionString));
         
```
This works, and I am using as work around,
``` C#
string connectionString = GetConfigurationConnectionStringThatPointsToOtherSchema();
_serviceDescriptors.AddDbContext<ConfigDbContext>(options => options.UseSqlServer(connectionString));
string connectionString2 = Configuration["ConnectionStrings:OnaymatikDbConnection"];
_serviceDescriptors.AddDbContext<CompanyDbContext>(options => options.UseSqlServer(connectionString2));
         
```

### Further technical details
SDK: WindowsDesktop
EF Core version:3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:NET Core 3.1
Operating system: Win10x64
IDE:Visual Studio 2019 16.4.4

**Comment by ajcvickers** [comment]
@prashantchoudhary I have not been able to reproduce this. Please attach a small, runnable project or a complete code listing that reproduces the behavior so that we can investigate.

**Comment by prashantchoudhary** [comment]
After some struggle I was able to create one sample application. Apparently Ef and DI are not well documented for WPF/WinForm/Console.
Anyways,In the attached code, I have added a macro `#define FAILURE_SCENARIO` in Program.cs file. It can be commented to see the working behaviour. 

Please modify the appsettings.json and OnConfiguring to point to the right Db Password and Apply Migrations. 
[TestForBug.zip](https://github.com/dotnet/efcore/files/4200977/TestForBug.zip)

**Comment by AndriySvyryd** [comment]
@prashantchoudhary This is just how closures work in C#. Try:
```C#
var stringToWrite = "Hello ";
Action writeFirstPart = () => Console.Write(stringToWrite);

stringToWrite = "World!";
Action writeSecondPart = () => Console.Write(stringToWrite);

writeFirstPart();
writeSecondPart();
```

**Comment by prashantchoudhary** [comment]
Oh thank you, I was being silly, ServiceDescriptor code was not as obvious as this one.
