### ISSUE TITLE
Inheritance DataAnnotation

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#1984]
Rowan,

Can you please consider add DataAnnotation to configure Inheritance.
1. [TablePerHierarchy]
2. [TablePerType]
3. [TablePerConcrete]
So that we dont have play around with fluent api with AddProperty. Its would make things looks cleaner.

Thank you mate

**Comment by divega** [comment]
@wangkanai We discussed this in triage and it is hard for us to see how this would be used and how it would make inheritance mapping look cleaner. I would expect inheritance mapping to be the result of how derived types are mapped, e.g. they could be mapped to different tables using the fluent API or attributes as soon as we have support. We could even think of allowing using an attribute to specify discriminator values for each derived type if all types are mapped to a single table.

Can you please elaborate on the idea a bit more?

**Comment by divega** [comment]
Closing as we don't have plans to do this.
