### ISSUE TITLE
InMemory - bad key management for derived entity types

### ISSUE THREAD

**Issue by saliksaly** [dotnet/efcore#19854]
Using in-memory database, ef core 3.1.
Having abstract class _Animal_ and two derived classes: _Cat_ and _Dog_.
All are registered as entities in DbContext.
Seeding 2 Cat entities in DbContext.OnModelCreating.

1st problem:
When inserting a new Cat entity to DbSet, receiving error: "ArgumentException: An item with the same key has already been added. Key: 1".
The Id for the new entity shuld be 3 because there are already two.

2nd problem:
When inserting a new Dog entity to DbSet, it behaves inappropriately: replaces Cat entity with id 1 with the new Dog entity and adds new Dog entity with id 1!

### Steps to reproduce

Here is asp net core demo app to demonstarte the problem described:
https://github.com/saliksaly/aspnetcoreapp-efcore-inherited-entity-id-problem

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1
Operating system: Win10 v. 1809
IDE: Visual Studio Community 2019 16.4.4

**Comment by ajcvickers** [comment]
@saliksaly I was able to reproduce this and it does look like a bug. 

Note for team: it looks like the code that peeks into the in-memory database to decide what key value to use is not working correctly when there is inheritance mapping.

**Comment by saliksaly** [comment]
Hi, would not be there any workaround until 5.0.0 version?

**Comment by ajcvickers** [comment]
@saliksaly Just wanted to let you know that I have started investigating a workaround, but it may take me a while.

**Comment by ajcvickers** [comment]
@saliksaly I have a PR out to fix this for EF Core 5.0. Here's a workaround for 3.1:

```C#
private static void BumpGenerator(
    DbContext context, Type entityClrType, string propertyName, int newLowBound)
{
    var entityType = context.Model.FindEntityType(entityClrType);
    var property = entityType.FindProperty(propertyName);
    var options = context.GetService<IDbContextOptions>().FindExtension<InMemoryOptionsExtension>();
    var inMemoryStore = context.GetService<IInMemoryStoreCache>().GetStore(options.StoreName);
    var generator = inMemoryStore.GetIntegerValueGenerator<int>(property);
    
    var values = new object[entityType.GetDeclaredProperties().Count()];
    values[property.GetIndex()] = newLowBound;
    generator.Bump(values);
}
```

Use it like this:
```C#
BumpGenerator(context, typeof(AnimalBase), nameof(AnimalBase.Id), 2);
context.Add(
    new Cat
    {
        Name = "Tom",
    });
```

Passing `2` here means that the next value generated will be 3. 

Note: this workaround uses EF internal code. This code will change in new releases of EF Core and the workaround will likely break. Use only with EF Core 3.1.

**Comment by ShoSashko** [comment]
I just wanted to clarify. I have the same issue but with string as a key. 
EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1

> {"An item with the same key has already been added. Key: TestEmail1@gmail.com"}

Please let me know if there is any workaround?

**Comment by ajcvickers** [comment]
@ShoSashko There is a workaround posted above.

**Comment by ShoSashko** [comment]
@ajcvickers Thanks for the quick response. 

Not sure how I can apply this workaround for my specific case, having a `string `as a PK.
I've tried to change the workaround posted above from `int` to `string`

```
private static void BumpGenerator(
    DbContext context, Type entityClrType, string propertyName, string newLowBound)
        {
            var entityType = context.Model.FindEntityType(entityClrType);
            var property = entityType.FindProperty(propertyName);
            var options = context.GetService<IDbContextOptions>().FindExtension<InMemoryOptionsExtension>();
            var inMemoryStore = context.GetService<IInMemoryStoreCache>().GetStore(options.StoreName);
            var generator = inMemoryStore.GetIntegerValueGenerator<string>(property);

            var values = new object[entityType.GetDeclaredProperties().Count()];
            values[property.GetIndex()] = newLowBound;
            generator.Bump(values);
        }
```
But it throwing exception of the `generator.Bump`. 

I have doubts that it will work anyway, there is no equal method for `GetIntegerValueGenerator` for the string. 

Please let me know if I am even on the right track.

**Comment by ajcvickers** [comment]
@ShoSashko No, this code doesn't make sense for strings, but then usually automatically generating string key values also doesn't make sense. You may be running into [this breaking change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#string-and-byte-array-keys-are-not-client-generated-by-default).

**Comment by saliksaly** [comment]
I have applied the fix to the demo app:
https://github.com/saliksaly/aspnetcoreapp-efcore-inherited-entity-id-problem
