### ISSUE TITLE
dotnet ef Could not execute because the specified command or file was not found

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19861]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/903195/dotnet-ef-could-not-execute-because-the-specified.html)._

---
<p>In angular + asp.net core 3.1 project, I am getting this error, whenever I try to access anything related to EF.</p> <p>dotnet ef Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-ef does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH</p><p>Everything was working fine before. Due to some error I downloaded my old package of the project from GitHub and pasted, and now getting this error.</p> <p>I have already set environment variables too</p><p><a href="https://i.stack.imgur.com/wgoMB.jpg" target=_blank>Error in dotnet CLI + .csproj file setup</a></p><p><a href="https://i.stack.imgur.com/UymO4.jpg" target=_blank>My environmental variable set up</a></p><p><a href="https://i.stack.imgur.com/xRbVN.jpg" target=_blank>Working in System cmd but not in asp.netcoreCLI</a></p><p><p><a> Image:https: i.stack.imgur.com=</a></p>

---
#### Visual Studio Feedback System on 2/2/2020, 07:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
The `dotnet ef` command is now shipped separately as a global tool. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dotnet-ef

**Comment by SidV7** [comment]
> 
> 
> _This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/903195/dotnet-ef-could-not-execute-because-the-specified.html)._
> 
> In angular + asp.net core 3.1 project, I am getting this error, whenever I try to access anything related to EF.
> 
> dotnet ef Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-ef does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH
> 
> Everything was working fine before. Due to some error I downloaded my old package of the project from GitHub and pasted, and now getting this error.
> 
> I have already set environment variables too
> 
> [Error in dotnet CLI + .csproj file setup](https://i.stack.imgur.com/wgoMB.jpg)
> 
> [My environmental variable set up](https://i.stack.imgur.com/UymO4.jpg)
> 
> [Working in System cmd but not in asp.netcoreCLI](https://i.stack.imgur.com/xRbVN.jpg)
> 
> Image:https: i.stack.imgur.com=
> ### Original Comments
> #### Visual Studio Feedback System on 2/2/2020, 07:31 PM:
> 
> We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.
> ### Original Solutions
> 
> (no solutions)

Facing the same issue. I'm working on .net core 3.1.0
After installing dotnet-ef globally, when i try to look up for the features by running
dotnet ef -h
i get these errors
![1](https://user-images.githubusercontent.com/40420811/82828943-ca705600-9ecf-11ea-9e66-c77441be0a28.PNG)
![2](https://user-images.githubusercontent.com/40420811/82828969-d5c38180-9ecf-11ea-859e-63b66fb8ad4b.PNG)

**Comment by SidV7** [comment]
The problem went away after starting VS code in admin mode

**Comment by Darkace01** [comment]
Delete your debug folder and try `dotnet tool install --global dotnet-ef` again

**Comment by bellaj** [comment]
The dotnet ef tool is no longer part of the .NET Core SDK
This change allows us to ship dotnet ef as a regular .NET CLI tool that can be installed as either a global or local tool. For example, to be able to manage migrations or scaffold a DbContext, install dotnet ef as a global tool typing the following command:

`dotnet tool install --global dotnet-ef`

**Comment by shanilkv** [comment]
> Delete your debug folder and try `dotnet tool install --global dotnet-ef` again

It's worked for me

**Comment by AmaniToamaWebDevelp1** [comment]
dotnet tool install --global dotnet-ef
Tool 'dotnet-ef' is already installed.
[****]$ dotnet ef migrations add MigrationName
dotnet ef database update
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[*****]$

**Comment by rekardev1** [comment]
I did the following:

- dotnet tool install --global dotnet-ef
- uninstalling and re-installing
- run terminal as administrator 

The fix for me was adding `C:\Users\rekar\.dotnet\tools` manwally to the PATH

**Comment by RiversJohn** [comment]
> 

Just hit this issue, except for me even editing the path manually does absolutely nothing.
One would imagine installing a global tool via commandline would actually configure itself into a functional state no? o.0
