### ISSUE TITLE
Compatibility issue with SQLite SEE 

### ISSUE THREAD

**Issue by vichuviswan** [dotnet/efcore#19869]
I have a C# UWP application which uses SQLite database, where I copy the database from install path to localappdata during first launch, encrypt the database using [SQLite SEE](https://www.sqlite.org/see/doc/release/www/index.wiki) to save some application specific details, decrypt and use it for future runs. Please find below the relevant sections of the code for reference:

**Encryption Logic:**
![image](https://user-images.githubusercontent.com/21960131/74196791-a1c79780-4c23-11ea-9a1b-230ef73923f0.png)

**Run-time usage:**
![image](https://user-images.githubusercontent.com/21960131/74196850-c28fed00-4c23-11ea-85b1-8aef543d4a7c.png)

The logic is working without any issues when I had SQLite SEE v3.30.1 with Microsoft.EntityFrameworkCore.Sqlite v2.2.0 and SQLitePCLRaw.lib.e_sqlite3.v140 v1.1.14 (replaced the existing e_sqlite3.dll with the one I created based off of SEE)

For upgrading to EFCore (3.1.1), I removed the SQLitePCLRaw.lib.e_sqlite3.v140 package I was using and based on the SQLitePCLRaw documentation, I did the following additional changes to my code setup:

- Installed the SQLitePCLRaw.bundle_e_sqlite3 package
- Replaced the e_sqlite3.dll in the SQlitePCLRaw.lib.e_sqlite3 with the one I have with SEE
- Updated the logic to provide the complete absolute path for my database
- Invoked the SQLitePCL.Batteries_V2.Init() as part of startup

Now, I see that the encryption methods are getting executed without any issues/exception, but in the section where it tries to read data from the database, it throws an exception:

> "SQLite 26: File is not a database"

Please find below the error message and associated stack trace:
![image](https://user-images.githubusercontent.com/21960131/74196981-113d8700-4c24-11ea-9c51-463618b75f71.png)

![image](https://user-images.githubusercontent.com/21960131/74196993-1569a480-4c24-11ea-8845-a2e4d9c7f575.png)

I get the exact same error when I tried to open the database from SQLite CLI or any other database browsing software's like, SQLiteManager.

Since I noticed that the SQLitePCLRaw is supporting only up to v3.28.0 of SQLite, I tried downgrading the e_sqlite3 SEE binary that I'm using to the same version, but the issue remains the same.

I did verify that the encryption and decryption is working fine with SEE command line, but fails only when integrated in my application using EFCore. Additionally, the logic is working fine until EFCore 2.2.6 and from 3.0 onward I get the issue. As you see, only thing that I directly refer from my code logic is Microsoft.Data.Sqlite and I know under the hood it uses the SQLitePCL packages, so not sure now the issue is with EFCore, any of its dependencies or did I miss something.

Any assistance is really appreciated.

### To Reproduce

Create a simple UWP application which writes some data to a SQLite database in %localappdata% path using EFCore 3.1.1, encrypts it using SEE and use the stored data for future launches.

### Additional context

Microsoft.Data.Sqlite version: 3.1.1.0
Target framework: (e.g. .NET Core 3.0): .NetStandard 2.0 library used in the UWP application with UAP version 17134
Operating system: Windows 10 RS4

**Comment by bricelam** [comment]
Have a read through [Encryption](https://docs.microsoft.com/dotnet/standard/data/sqlite/encryption) and [Custom SQLite versions](https://docs.microsoft.com/dotnet/standard/data/sqlite/custom-versions) in the Microsoft.Data.Sqlite docs. If it's still giving you trouble, let us know. We don't have a license to SEE, so debugging might be ...problematic.
