### ISSUE TITLE
Benchmarks: remove EF6 benchmarks

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19878]
Isn't relevant anymore and requires maintenance.

/cc @bricelam @ajcvickers

**Comment by ajcvickers** [comment]
@roji Do one more run...

**Comment by roji** [comment]
Run results:

* [EF6.SqlServer.Benchmarks.Artifacts.zip](https://github.com/dotnet/efcore/files/4954056/EF6.SqlServer.Benchmarks.Artifacts.zip)
* [EFCore.SqlServer.Benchmarks.Artifacts.zip](https://github.com/dotnet/efcore/files/4954057/EFCore.SqlServer.Benchmarks.Artifacts.zip)

After 5.0 I'll sit down and do a nice comparison :)
