### ISSUE TITLE
Can't debug ef project

### ISSUE THREAD

**Issue by jonantoine** [dotnet/efcore#19880]
I cloned the release/3.1 branch. Figured out what comand args were needed. But the program keeps bombing with:
```
Could not load file or assembly Microsoft.EntityFrameworkCore.Design
```

My args look like this 
```
dbcontext scaffold "Data Source=vm\\sql2017;Initial Catalog=Test; Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer --assembly C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.dll --startup-assembly C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.dll --project-dir C:\A\ConsoleApp1\ConsoleApp1\ --language C# --root-namespace ConsoleApp1 -v 
```
Also setting the working directory to this: C:\A\ConsoleApp1\ConsoleApp1\ 

This project has reference to Microsoft.EntityFrameworkCore.Design and scaffold works fine when using the official released ef version.

I also tried to debug the dotnet-ef project which is where I got the args above. 
This is what it produced:
```
dotnet exec --depsfile C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.deps.json --additionalprobingpath C:\Users\xxxx\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.runtimeconfig.json C:\Users\xxxx\.dotnet\tools\.store\dotnet-ef\3.1.1\dotnet-ef\3.1.1\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "Data Source=vm\sql2017;Initial Catalog=Test; Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer --assembly C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.dll --startup-assembly C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.dll --project-dir C:\A\ConsoleApp1\ConsoleApp1\ --language C# --working-dir C:\A\ConsoleApp1\ConsoleApp1 --verbose --root-namespace ConsoleApp1
```

The ef program doesn't like whenI pass it the --depsfile or --additionalprobingpath  args but the ref to the Microsoft.EntityFrameworkCore.Design dll is in there.

How do you debug this program? Any help would be appreciative.

**Comment by jzabroski** [comment]
Hi @jonantoine , I have[ some tips](https://github.com/jzabroski/Home#net-core-new) on debugging .net core assembly loading:

```
setx CORE_HOSTTRACE 1
```
if debugging an ASP.NET Core app, consider also adding:
```
setx ASPNETCORE_ENVIRONMENT "Development"
```

My other piece of advice is to look carefully at your .deps.json file and see what version it is loading, and verify the version of the dll you're referring to matches exactly.  To do this, use a tool like DotPeek to look at the assembly manifest.  I used this trick to debug a similar annoying issue with System.ComponentModel.DataAnnotations, but it took me 2-3 days to "perform this trick" the first time without any guidance.  Hoping this saves you some effort.

**Comment by jzabroski** [comment]
@jonantoine Was that helpful?  LMK how you make out.

**Comment by ajcvickers** [comment]
@jonantoine It looks like you are trying to build the EF code. Are you doing this so that you can debug into EF?

**Comment by jonantoine** [comment]
Yes, I can successful build the EF core project. But when the program tries to resolve some nuget packages, such as Microsoft.EntityFrameworkCore.Design can't be found. And I know my test project is setup right because the ef scaffolding cmd work and classes get created if I use the official release binaries. It seems the command coming out of the dotnet-ef project:
```
dotnet exec --depsfile C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.deps.json --additionalprobingpath C:\Users\xxxx\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.runtimeconfig.json C:\Users\xxxx\.dotnet\tools\.store\dotnet-ef\3.1.1\dotnet-ef\3.1.1\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "Data Source=vm\sql2017;Initial Catalog=Test; Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer --assembly C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.dll --startup-assembly C:\A\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp2.2\ConsoleApp1.dll --project-dir C:\A\ConsoleApp1\ConsoleApp1\ --language C# --working-dir C:\A\ConsoleApp1\ConsoleApp1 --verbose --root-namespace ConsoleApp1
```
Holds information to resolve these dependencies, but I can't debug that cmd in the dotnet cli project because that project seems to have similar issues trying to debug. 
I would like to know how everyone else is debugging the ef project because it seems I have been jumping through hoops to get this far. Isn't the ability to simply debug a project for troubleshooting/learning purposes important?

**Comment by jzabroski** [comment]
For .NET CLI Tools, the experience is indeed somewhat silly - I've argued to a few people at Microsoft that CLI Tools should be recursively defined, and I should be able to enter a debug stack by having a special dotnet CLI tool called AttachTo whose argument is "another CLI tool + parameters".  This would let you inspect `System.AppContext.GetData(“APP_CONTEXT_DEPS_FILES”)` and so on.

In other words, I don't think this is a concern you should raise in EFCore, per say.  It's a more general problem.  

However, to @ajcvickers point, if you're trying to debug EF Core, it might be helpful if you stated what you're trying to debug.

> I would like to know how everyone else is debugging the ef project because it seems I have been jumping through hoops to get this far.

I followed the advice given to me by @AndriySvyryd and @smitpatel - and created a shell project to test theories regarding various EF Bugs.  You can see my playground here: https://github.com/jzabroski/EntityFrameworkMappingTablePerHierarchy

To debug EF Core model building, it's sufficient to just call EnsureDeleted.  You can also call any of the ToDebugString extension methods: https://github.com/dotnet/efcore/search?q=todebugstring&unscoped_q=todebugstring To use ToDebugString _well_, it may be helpful to read this thread between @smitpatel and I: https://github.com/dotnet/efcore/issues/15640#issuecomment-490221820 as well as this tip from @AndriySvyryd 👍 

> Column name uniquification happens in the `Finalize` step, so if you use `modelBuilder.Model.ToDebugString()` in `OnModelCreating` you will see the default names.

**Comment by ajcvickers** [comment]
@jonantoine As @jzabroski alluded to, you should not need to build EF Core to debug into it. That being said, it can be difficult when working with tools, since you need to attach the debugger to the tools process.

If you do end up building the code to work with the dotnet-ef tool, then consider passing the `-pack` option to the build script. This will spit out local copies of the EF NuGet packages (including `dotnet-ef`) which you can then use for a local NuGet package feed.
