### ISSUE TITLE
Make JsonSerializer and EF Core compatible out of the box

### ISSUE THREAD

**Issue by libertizer** [dotnet/efcore#19910]
_Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance. So even if you don't explicitly include the data for a navigation property, the property may still be populated if some or all of the related entities were previously loaded._

This causes huge problems with System.Text.Json. More precisely:

Exception:   System.Text.Json.JsonException
Message:     A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.
Stacktrace:

Make JsonSerializer and EF Core related Data loading compatible with each other out of the boy

**Comment by ajcvickers** [comment]
@libertizer We appreciate that the experience here could be better, and I'm sorry you are running into issues. However, there isn't anything that EF can do out-of-the-box to fix this without it being a massive breaking change. It's also far from clear that any such change is wanted by the majority of EF users. Issue #11564 is tracking a behavior that could be turned on EF to not connect back references for loaded data, which would usually result in no cycles and so make this easier, but the only real solution is to use a JSON serializer that handles cycles. You can currently use [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) for this, and in 5.0 it will also be supported by the built-in serializer.
