### ISSUE TITLE
Add fluent API for read-only flags

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1991]
Currently these are only available in core metadata. We should decide on naming/flags/enum before doing the fluent API work.

**Comment by divega** [comment]
There are several aspects we still need to decide on. Figuring out what we want to do and whether this APIs will be needed is high priority.

**Comment by ajcvickers** [comment]
I think we are, for the moment, agreed on the general shape of the core metadata. Bringing this back to triage to decide if we need fluent API for the following:
- IsReadOnlyBeforeSave (Throw on SaveChanges if a value other than null/sentinel is set on a new entity)
- IsReadOnlyAfterSave (Throw on SaveChanges if the property is marked as modified)
- StoreGeneratedAlways (Always get the value from the database regardless of whether the property is set/modified on the client)
- SentinelValue (Set something other than default(T) as the sentinel.)

**Comment by rowanmiller** [comment]
99%+ of apps should not need to use these APIs (the higher level APIs should give you the control you need)
