### ISSUE TITLE
The  Query's  Include with  Skip and Take

### ISSUE THREAD

**Issue by maikebing** [dotnet/efcore#19924]
like this :

```C#
 _context.HealthChecks
    .Include(p => p.entries.OrderBy(e=>e.name))
    .Include(p => p.history.OrderBy(h=>h.on).Take(100)).ToList();
```

EF Core version:
Database provider: npgsql)
Target framework:.NET Core 3.1)
Operating system:Win10 1909 
IDE:  Visual Studio 2019 16.4.5

**Comment by ajcvickers** [comment]
@maikebing Include doesn't work like that; the lambda expression is used to identify navigation properties, but it cannot then be further composed on. See [Loading related data](https://docs.microsoft.com/en-us/ef/core/querying/related-data) in the docs for more information.
