### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension'

### ISSUE THREAD

**Issue by remy90** [dotnet/efcore#19939]
I'm trying to apply a migration

> dotnet ef migrations add MyMigration --verbose --startup-project ../MyProject.Api/MyProject.Api.csproj

results in the following. I've highlighted what I believe to be the root cause. I've used Microsoft.EntityFrameworkCore.SqlServer 2.0.0 in the target project, so I'm not sure why it's using 2.2.1.0

> dotnet exec --depsfile /src/MyProject.Api.csproj/bin/Debug/netcoreapp2.0/MyProject.Api.deps.json --additionalprobingpath /.nuget/packages --additionalprobingpath /usr/local/share/dotnet/sdk/NuGetFallbackFolder --runtimeconfig /src/MyProject.Api/bin/Debug/netcoreapp2.0/MyProject.Api.runtimeconfig.json /.dotnet/tools/.store/dotnet-ef/3.1.1/dotnet-ef/3.1.1/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll migrations add SqlKeyValueReplacementForCosmosDB --assembly /src/MyProject.Api/bin/Debug/netcoreapp2.0/MyProject.Infrastructure.dll --startup-assembly /src/MyProject.Api/bin/Debug/netcoreapp2.0/MyProject.Api.dll --project-dir /src/MyProject.Infrastructure/ --language C# --working-dir /src/MyProject.Infrastructure --verbose --root-namespace MyProject.Infrastructure
> Using assembly 'MyProject.Infrastructure'.
> Using startup assembly 'MyProject.Api'.
> Using application base '/src/MyProject.Api/bin/Debug/netcoreapp2.0'.
> Using working directory '/src/MyProject.Api'.
> Using root namespace 'MyProject.Infrastructure'.
> Using project directory '/src/MyProject.Infrastructure/'.
> Finding DbContext classes...
> Finding IDesignTimeDbContextFactory implementations...
> Finding application service provider...
> Finding BuildWebHost method...
> Using environment 'Development'.
> Using application service provider from BuildWebHost method on 'Program'.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at MyProject.Api.Program.ConfigureLogger(WebHostBuilderContext context, LoggerConfiguration config) in /src/MyProject.Api/Program.cs:line 91
>    at Serilog.SerilogWebHostBuilderExtensions.<>c__DisplayClass1_0.<UseSerilog>b__0(WebHostBuilderContext context, IServiceCollection collection)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at MyProject.Api.Program.BuildWebHost(String[] args) in /src/MyProject.Api/Program.cs:line 55
> An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Object reference not set to an instance of an object.
> No application service provider was found.
> Finding DbContext classes in the project...
> Found DbContext 'MyDbContext'.
> Using DbContext factory 'MyDbContextFactory'.
> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension' from assembly '**Microsoft.EntityFrameworkCore.SqlServer, Version=2.2.1.0**, Culture=neutral, PublicKeyToken=abdb45897'.
>    at MyProject.Infrastructure.Persistence.MyDbContextFactory.<>c__DisplayClass1_0.<CreateDbContext>b__0(SqlServerDbContextOptionsBuilder sql)
>    at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
>    at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer[TContext](DbContextOptionsBuilder`1 optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
>    at MyProject.Infrastructure.Persistence.MyDbContextFactory.CreateDbContext(String[] args) in /src/MyProject.Infrastructure/Persistence/MyDbContextFactory.cs:line 84
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass14_0.<FindContextFactory>b__1()
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> 

### Steps to reproduce
From the Startup Project:
TargetFramework: netcoreapp2.0
PackageReference Include: "Microsoft.AspNetCore.All" Version="2.0"
PrivateAssets Condition="'%(PackageReference.Version)' == ''">>all PrivateAssets>
Publish Condition="'%(PackageReference.Version)' == ''">true /Publish>

From the target Project: 
    

>     TargetFramework>netstandard2.0 /TargetFramework>
>     PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0" />
>     PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.0.0" />
>     PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />

### Further technical details

EF Core version: 2.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 2.0.0
Target framework: netcoreapp2.0
Operating system: macOS Catalina Version 10.15.2
IDE: Visual Studio Code Version: 1.42.1

**Comment by ajcvickers** [comment]
@remy90 EF Core and .NET Core 2.0 are [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/) Please try updating to 3.1 of both. If you're still running into problems, then please attach a small, runnable project that reproduces what you are seeing so that we can investigate.

**Comment by remy90** [comment]
Upgrading did help
