### ISSUE TITLE
Query: Avoid generating join to owner for owned navigations in some cases

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19932]
Split from #18299 

We generate a join to owner and apply filter conditions on owner to make sure that we are selecting owned entity for correct entity type. This is required when querying for base type and getting owned navigation from derived type as different derived type can be using same columns for different owned entities.

When owned navigation is defined on base type then we don't need to filter records in this way since there will not be any clash. Moreover owner table filter from outer will be more restrictive than inner in such cases.

**Comment by AndriySvyryd** [comment]
Fixed in 5cf965838bff0afe57faa31cf50fcbe3a2b85a79
