### ISSUE TITLE
EF creates ForeignKey when using a function to point to a local object in a many-to-many relationship

### ISSUE THREAD

**Issue by johnmackerras** [dotnet/efcore#19945]
When setting up a Many-to-Many relationship, and also setting up a shortcut function to access the opposte-side data set, EF will create a one-to-one Foreign Key between the two detail tables. (Confused? yep!)

### Steps to reproduce
1. Open the attached "DDDTrial" solution in VS2019.

2. Build the project, inspect the underlying MS-SQL database. The three tables are created as you would expect for a stock standard many-to-many.

3. In the Contacts module, remove the "[NotMapped]" attribute from the 'public IEnumerable<Project> Projects' function.

4. Delete database and re-exectue to build a new one.

5. Inspect dbo.Project fields. You will se a new field ContactID has been added in with a ForeignKey linking back to dbo.Contacts.

6. Replace the [NotMapped] attribute and rebuild to remove the underlying  FK.

Note: It make no difference whether you point Projects to  ContactProjects or to the backing field _contactProjects. The FK is still created.

So, the behaviour here is the although the 'Project' function simply points to another field inside it's own class, EF thinks that it should create link to the 'Project' table and the result is that the programmer who does not take care to look at whats created underneath may end up with one-to-one links spanning over the top of his many-to-many relationship.

[DDDTrial.zip](https://github.com/dotnet/efcore/files/4209786/DDDTrial.zip)

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win10
IDE: Visual Studio 2019 16.4.4

**Comment by johnmackerras** [comment]
Further information. This is an unbalanced structure. If you remove the NotMapped attribute and balance the many-to-many strture by adding the opposite number function.

i.e. add to the Project class:
public IEnumerable<Contact> Contacts => _contactProjects.Select(p => p.Contact).ToList();

then the tables build as expected for a m-m relationship

**Comment by ajcvickers** [comment]
@johnmackerras I've looked at your code and read what you wrote above and it sounds like you want a property that is not mapped to anything in the model. But then, that's what `[NotMapped]` is for, so I'm left wondering why it is you want to remove this attribute. What am I missing here?

**Comment by johnmackerras** [comment]
Hi AJ,
EFCore doesn't really distinguish between properties and methods any more, which might be the real cause of this. I would consider that, in the Project class:

"public IEnumerable<ContactProject> ContactProjects" is a property as it stores data.
"private ICollection<ContactProject> _contactProjects" is a backing field of the above property

However "public IEnumerable<Contact> Contacts" is a method because it does not store data itself, it is an action which extracts a subset of data from the 'ContactProjects' property.

There is also another thing to point out, here. Whether or not Contacts is considered property or not, it is a List which contains multiple items, yet the field created by EFCore in the opposing table is a single-value storage field, so that only one value of the many values in the list can be recorded at any one time. This in itself, seems wrong.

**Comment by ajcvickers** [comment]
@johnmackerras If `public IEnumerable Contacts` is a method, why is it declared as a property?

**Comment by johnmackerras** [comment]
Hi Arthur,

You are quite right in a passive-agressive way. I wrote:
public IEnumerable<Contact> Contacts => _contactProjects.Select(p => p.Contact).ToList();

but should have writtten:
public IEnumerable<Contact> Contacts() => _contactProjects.Select(p => p.Contact).ToList();

It's very easy to forget parentheses when in many cases it works just as well without them. You could have just explained that in your response.

**Comment by ajcvickers** [comment]
@johnmackerras I apologize if I came across that way. It was a genuine question, but I should perhaps have phrased it as, "I can see from your description that you are conceptually considering this a method, and yet in the C# code I see it defined as a property. Is there some reason that you're using property syntax for something that is conceptually a method?" In other words, I really was asking if you are doing this on purpose--I see lots of interesting code patterns some of which are new to me, and so I was wondering if this was one of them.
