### ISSUE TITLE
Updating to MDS 1.1.1

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#19962]
Is there a 3.1.2 release?

Or must we add an explicit reference to MDS 1.1.1 to get the async fix?

https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.1.1

**Comment by ajcvickers** [comment]
@ErikEJ An explicit reference is needed. We will consider updating the patch dependency for a future patch release.

**Comment by ajcvickers** [comment]
@Pilchie Do we have any general guidance on whether we should update our dependencies in a patch when one of them has itself been patched?

**Comment by Pilchie** [comment]
Adding @ericstj for his thoughts.

**Comment by ericstj** [comment]
It doesn't scale for every package in the ecosystem to update when one of its dependencies updates.  In dotnet/runtime we don't do this in servicing, but we do in minor releases.  We still occasionally make case-by-case decisions to update in servicing.  For example: when a dependency has a security update that we want to make sure people have, or the dependency has a significant bugfix and we don't want to support the bug.

**Comment by ajcvickers** [comment]
Thanks all. Based on the feedback and discussion in the team we're not going to proactively do this. However, as always, we could revisit this with more feedback.
