### ISSUE TITLE
Table is generated for Keyless Entity Type, despite no model declaration

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/efcore#19972]
Not sure if this issue is related to EF Core, or just Npgsql...

When defining a keyless entity type for use by raw SQL queries, the designer generates a `ModelSnapshot` that defines a table for this entity, despite the fact that I don't specify a table through `ModelBuilder` API, or through Attribute decorations. I don't see any obvious `EntityTypeBuilder` calls I can make to specify that no table should be generated, and I can't call `.ToQuery()` because the query that backs this entity needs to be raw. It includes a lot of function calls that EF doesn't translate.

[Here](https://github.com/JakenVeina/efcore-issue-19972) is a minimal codebase that reproduces the issue, with the important bits shown below.

A sample entity definition...
```cs
public class MyTestKeylessEntity
{
    public MyTestKeylessEntity(
        long userId,
        int recordCount,
        long valueTotal)
    {
        UserId = userId;
        RecordCount = recordCount;
        ValueTotal = valueTotal;
    }

    public long UserId { get; }
    public int RecordCount { get; }
    public long ValueTotal { get; }
}

public class MyTestKeylessEntityConfigurator
    : IEntityTypeConfiguration<MyTestKeylessEntity>
{
    public void Configure(
            EntityTypeBuilder<MyTestKeylessEntity> entityTypeBuilder)
    {
        entityTypeBuilder
            .HasNoKey();
        entityTypeBuilder
            .Property(x => x.UserId);
        entityTypeBuilder
            .Property(x => x.RecordCount);
        entityTypeBuilder
            .Property(x => x.ValueTotal);
    }
}
```

The generated `ModelSnapshot`...
```cs
modelBuilder.Entity("EFCoreTest.MyTestKeylessEntity", b =>
    {
        b.Property<int>("RecordCount")
            .HasColumnType("integer");

        b.Property<long>("UserId")
            .HasColumnType("bigint");

        b.Property<long>("ValueTotal")
            .HasColumnType("bigint");

        b.ToTable("MyTestKeylessEntity");
    });
```

EF Core version: v3.1.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL v3.1.1.2
Target framework: .NET Core 3.1
Operating system: Windows 8.1 Pro x64
IDE: Visual Studio 2019 v16.4.5

**Comment by AdamDotNet** [comment]
Hi @JakenVeina. I was looking through this repository for the same reason as you, tables were being made for my Query types when I didn't want them to be.

#18116 has the workaround:
> For now, you can just use something like .ToView("You forgot to use FromSql with ModQueueEntry")

But it is on the radar for EF Core 5.0:
> Note from triage: closing this as duplicate since the work here is covered by #17270 and #2725.

Hope this helps!

**Comment by JakenVeina** [comment]
Roger, thanks for the tip.
