### ISSUE TITLE
Missing function DataLength 

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/efcore#19988]
how would i get access to DataLength which is in ms sql. its available on Ef6 but not sure how to get access to it with core,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c516f9eb-928c-2f34-63e1-2285f2c524e5
* Version Independent ID: 27061b6e-0ab1-de5a-d03d-d7cbd2a2618e
* Content: [DbFunctions Class (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctions?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbFunctions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbFunctions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by Marusyk** [comment]
Please assign it to me
