### ISSUE TITLE
Don't see any entity framework 7.0-* packages in nuget.org

### ISSUE THREAD

**Issue by PradeepKadubandi** [dotnet/efcore#1998]
Was there never been an upload of EF packages in nuget.org? Or the default feed api.nuget.org? 

I don't see any version of 7.0.0-\* packages (I included prerelease versions) in the manage nuget packages dialog (and I verified nuget.org and the packages are there)

**Comment by paul-daly** [comment]
You can find the latest EF7 nuget packages on myget: https://www.myget.org/F/aspnetvnext/.  You'll need to add this url to the list of package sources in Visual Studio:
Tools --> Options --> Nuget Package Manager --> Package Sources

I assume that the EF team will post the nuget packages to nuget.org once EF7 is released.

**Comment by divega** [comment]
@PradeepKadubandi 7.0.0-* prerelease "EntityFramework" packages exist but are unlisted in nuget.org to prevent unintended upgrades from EF6 until we get a better solution for that in place. You should be able to see 7.0.0-* prerelease packages for "EntityFramework.Core" and "EntityFramework.SqlServer".
