### ISSUE TITLE
preview2.20120.1: Complex query graph fails to translate requiring cliend evaluation in error.

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#19999]
Neither repro nor more information - I sadly have no line numbers and the exception thrown does not contain any more information. I can try to cut down the code to a repro, but this is out of a migration project.

Note: it is possible this is a duplicate of https://github.com/dotnet/efcore/issues/19997 - I simply do not know because there is not enough information provided to debug this properly.

Note: The quality of the error message is a separate error under https://github.com/dotnet/efcore/issues/20001 - right now this wall of text is not helpfull at all.

In the nightly I am getting again the following error:

 could not be translated. Either rewrite the query in a form that can be translated,

for a graph that contains nothing that should require translation.

The query graph in question is:

> 'DbSet<OBTIncident>
>     .Join(
>         inner: DbSet<OBTBuilding>
>             .Where(o0 => DbSet<OBVBuildingRights>
>                 .Where(o1 => EF.Property<Nullable<int>>(o0, "PkBID") != null && EF.Property<Nullable<int>>(o0, "PkBID") == EF.Property<Nullable<int>>(o1, "FkBuildingID"))
>                 .Where(o1 => o1.FkLoginID == __ef_filter__ActiveUserId_1)
>                 .Any()), 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o, "FkBID"), 
>         innerKeySelector: o0 => EF.Property<Nullable<int>>(o0, "PkBID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<OBTIncident, OBTBuilding>(
>             Outer = o, 
>             Inner = i
>         ))
>     .Where(o => DbSet<OBVBuildingRights>
>         .Where(o2 => EF.Property<Nullable<int>>(o.Inner, "PkBID") != null && EF.Property<Nullable<int>>(o.Inner, "PkBID") == EF.Property<Nullable<int>>(o2, "FkBuildingID"))
>         .Where(o2 => o2.FkLoginID == __ef_filter__ActiveUserId_0)
>         .Any())
>     .LeftJoin(
>         inner: DbSet<OBTServiceContact>
>             .Join(
>                 inner: DbSet<GTMandator>
>                     .Where(g => DbSet<GVMandatorRights>
>                         .Where(g0 => EF.Property<Nullable<int>>(g, "PkMandatorID") != null && EF.Property<Nullable<int>>(g, "PkMandatorID") == EF.Property<Nullable<int>>(g0, "FkMandatorID"))
>                         .Where(g0 => g0.FkLoginID == __ef_filter__ActiveUserId_3)
>                         .Any()), 
>                 outerKeySelector: o3 => EF.Property<Nullable<int>>(o3, "FkMandatorID"), 
>                 innerKeySelector: g => EF.Property<Nullable<int>>(g, "PkMandatorID"), 
>                 resultSelector: (o, i) => new TransparentIdentifier<OBTServiceContact, GTMandator>(
>                     Outer = o, 
>                     Inner = i
>                 ))
>             .Where(o3 => DbSet<GVMandatorRights>
>                 .Where(g1 => EF.Property<Nullable<int>>(o3.Inner, "PkMandatorID") != null && EF.Property<Nullable<int>>(o3.Inner, "PkMandatorID") == EF.Property<Nullable<int>>(g1, "FkMandatorID"))
>                 .Where(g1 => g1.FkLoginID == __ef_filter__ActiveUserId_2)
>                 .Any()), 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Outer, "FkServiceContactID"), 
>         innerKeySelector: o3 => EF.Property<Nullable<int>>(o3.Outer, "PkServiceContactID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>(
>             Outer = o, 
>             Inner = i
>         ))
>     .LeftJoin(
>         inner: DbSet<OBTAddress>, 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Inner.Outer, "FkAddressID"), 
>         innerKeySelector: o4 => EF.Property<Nullable<int>>(o4, "PkAddressID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>, OBTAddress>(
>             Outer = o, 
>             Inner = i
>         ))
>     .LeftJoin(
>         inner: DbSet<OBTTextCountry>, 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Inner, "FkCountryID"), 
>         innerKeySelector: o5 => EF.Property<Nullable<int>>(o5, "PkCountryID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>, OBTAddress>, OBTTextCountry>(
>             Outer = o, 
>             Inner = i
>         ))
>     .LeftJoin(
>         inner: DbSet<OBTTextRegion>, 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Outer.Inner, "FkRegionID"), 
>         innerKeySelector: o6 => EF.Property<Nullable<int>>(o6, "PkRegionID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>, OBTAddress>, OBTTextCountry>, OBTTextRegion>(
>             Outer = o, 
>             Inner = i
>         ))
>     .Where(o => EF.Property<Nullable<int>>(o.Outer.Outer.Outer.Inner.Outer, "PkServiceContactID") == null ? null : new ServiceProvider{ 
>         Address = EF.Property<Nullable<int>>(o.Outer.Outer.Inner, "PkAddressID") == null ? null : new Address{ 
>             City = o.Outer.Outer.Inner.SCity, 
>             Country = o.Outer.Inner.SIso2, 
>             CountryInfo = EF.Property<Nullable<int>>(o.Outer.Inner, "PkCountryID") == null ? null : new CountryInfo{ 
>                 Id = o.Outer.Inner.PkCountryID, 
>                 Name = o.Outer.Inner.SName 
>             }
>             , 
>             No = o.Outer.Outer.Inner.SNumber, 
>             PostCode = o.Outer.Outer.Inner.SZip, 
>             Region = o.Inner.SIso, 
>             RegionInfo = EF.Property<Nullable<int>>(o.Inner, "PkRegionID") == null ? null : new RegionInfo{ 
>                 Id = o.Inner.PkRegionID, 
>                 Name = o.Inner.SName 
>             }
>             , 
>             Street = o.Outer.Outer.Inner.SStreet 
>         }
>         , 
>         Code = o.Outer.Outer.Outer.Inner.Outer.SShortName, 
>         ContactEmailAdd = o.Outer.Outer.Outer.Inner.Outer.SContactEmailAdd, 
>         ContactPerson = o.Outer.Outer.Outer.Inner.Outer.SContactPerson, 
>         ContactPhone1 = o.Outer.Outer.Outer.Inner.Outer.SContactPhone1, 
>         ContactPhone2 = o.Outer.Outer.Outer.Inner.Outer.SContactPhone2, 
>         ContractContactEmailAdd = o.Outer.Outer.Outer.Inner.Outer.SContractContactEmailAdd, 
>         ContractContactPerson = o.Outer.Outer.Outer.Inner.Outer.SContractContactPerson, 
>         ContractContactPhone = o.Outer.Outer.Outer.Inner.Outer.SContractContactPhone, 
>         Created = o.Outer.Outer.Outer.Inner.Outer.DCreateDate, 
>         Department = o.Outer.Outer.Outer.Inner.Outer.SDepartment, 
>         Id = o.Outer.Outer.Outer.Inner.Outer.PkServiceContactID, 
>         Identity = o.Outer.Outer.Outer.Inner.Outer.GIdentity, 
>         IsInspection = o.Outer.Outer.Outer.Inner.Outer.BIsInspection, 
>         IsMaintenance = o.Outer.Outer.Outer.Inner.Outer.BIsMaintenance, 
>         Name = o.Outer.Outer.Outer.Inner.Outer.SLongName, 
>         Type = o.Outer.Outer.Outer.Inner.Outer.IType 
>     }
>      == null)'
 
The stack trace is:

>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
  
I will gladly investogagte further, but as it stands the debugging information is not particularly helpfull. The message does contain the whole query graph - but no information WHICH PART acutally blows. At minimum it should contain the exact part of the graph that is responsible for this exception. As it stands now, there is no way to debug real world queries (and yes, this is one of the easier ones) because the graphs are big and there is NO indication whichpart is relevant for the exception. I open a

**Comment by smitpatel** [comment]
```C#
.Where(o => EF.Property<Nullable>(o.Outer.Outer.Outer.Inner.Outer, "PkServiceContactID") == null ? null : new ServiceProvider{
Address = EF.Property<Nullable>(o.Outer.Outer.Inner, "PkAddressID") == null ? null : new Address{
City = o.Outer.Outer.Inner.SCity,
Country = o.Outer.Inner.SIso2,
CountryInfo = EF.Property<Nullable>(o.Outer.Inner, "PkCountryID") == null ? null : new CountryInfo{
Id = o.Outer.Inner.PkCountryID,
Name = o.Outer.Inner.SName
}
,
No = o.Outer.Outer.Inner.SNumber,
PostCode = o.Outer.Outer.Inner.SZip,
Region = o.Inner.SIso,
RegionInfo = EF.Property<Nullable>(o.Inner, "PkRegionID") == null ? null : new RegionInfo{
Id = o.Inner.PkRegionID,
Name = o.Inner.SName
}
,
Street = o.Outer.Outer.Inner.SStreet
}
,
Code = o.Outer.Outer.Outer.Inner.Outer.SShortName,
ContactEmailAdd = o.Outer.Outer.Outer.Inner.Outer.SContactEmailAdd,
ContactPerson = o.Outer.Outer.Outer.Inner.Outer.SContactPerson,
ContactPhone1 = o.Outer.Outer.Outer.Inner.Outer.SContactPhone1,
ContactPhone2 = o.Outer.Outer.Outer.Inner.Outer.SContactPhone2,
ContractContactEmailAdd = o.Outer.Outer.Outer.Inner.Outer.SContractContactEmailAdd,
ContractContactPerson = o.Outer.Outer.Outer.Inner.Outer.SContractContactPerson,
ContractContactPhone = o.Outer.Outer.Outer.Inner.Outer.SContractContactPhone,
Created = o.Outer.Outer.Outer.Inner.Outer.DCreateDate,
Department = o.Outer.Outer.Outer.Inner.Outer.SDepartment,
Id = o.Outer.Outer.Outer.Inner.Outer.PkServiceContactID,
Identity = o.Outer.Outer.Outer.Inner.Outer.GIdentity,
IsInspection = o.Outer.Outer.Outer.Inner.Outer.BIsInspection,
IsMaintenance = o.Outer.Outer.Outer.Inner.Outer.BIsMaintenance,
Name = o.Outer.Outer.Outer.Inner.Outer.SLongName,
Type = o.Outer.Outer.Outer.Inner.Outer.IType
}
== null)
```
This part blows up. Hope it helps!

**Comment by NetTecture** [comment]
@smitpatel 

A repro is up. I have made a general repro repository using a simple database. It does not "work" as this issue is pre-execution, but it demonstrates the issue. I will use this repro in the future to show all differences.

The object hierarchy in case is

Event -> Organizer (replacing the ServiceProvider).

Repro location:

https://github.com/NetTecture/EntityFrameworkCoreIssues

It is a ltttle complex because it is ready to demonstrate issues in 3 environments: Ef classic, 2.2 and nightly, though using only 2 environments for this demonstration.

* Data: future database
* DataClasses: The classes used by all Ef instances.
* EntityClasses: the classes actually requested.
* EntityMappings: Automapper projections used to generate the sql. I run around 90% of my sql through projection because the normal use case are exposed entity classes via Odata with query conditions dynamically projected into the database.

Then:

* 3 repositories (RepositoryEfClassic, RepositoryEfCore22 and RepositoryEfNightly. Those are the repositories with the DbContext instance (DbRepository) and all the configurations.
* 3 test projects (Tests.EfClassic, Tests.EfCore22, Tests.EfCoreNightly).

Repro, assuming visual studio:

* Filter by Issue19999 (or use the test explorer;). The actualy test is named "Repro" in test classes named "Issue19999".

** Tests.EfCoreNightly:

In Visual Studio, I get

System.InvalidOperationException: 'The LINQ expression 'DbSet<DbEvent>
    .LeftJoin(
        inner: DbSet<DbOrganizer>, 
        outerKeySelector: d => EF.Property<Nullable<int>>(d, "OrganizerFk"), 
        innerKeySelector: d0 => EF.Property<Nullable<int>>(d0, "PkOrganizer"), 
        resultSelector: (o, i) => new TransparentIdentifier<DbEvent, DbOrganizer>(
            Outer = o, 
            Inner = i
        ))
    .Where(d => EF.Property<Nullable<int>>(d.Inner, "PkOrganizer") == null ? null : new Organizer{ Name = d.Inner.Name }
     == null)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

This is the bug documented here, albeit significantly smaller as those repro classes contain less properties.

** Tests.EfCore22

Executes and results in "System.Data.SqlClient.SqlException: 'Invalid object name 'Event'.'" because the db is not properly initialized (yet) as this is not relevant for the execution. Copy/paste of the Output window shows the logging in which you find the generates SQL statement:

SELECT [dtoDbEvent].[OrganizerFk], [dtoDbEvent.Organizer].[Name], CASE
|   |   |   |           WHEN [dtoDbEvent].[OrganizerFk] IS NULL
|   |   |   |           THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
|   |   |   |       END, [dtoDbEvent].[Title]
|   |   |   |       FROM [Event] AS [dtoDbEvent]
|   |   |   |       LEFT JOIN [Organizer] AS [dtoDbEvent.Organizer] ON [dtoDbEvent].[OrganizerFk] = [dtoDbEvent.Organizer].[PkOrganizer], 

As can clearly be seen it absolutely manages to generate a SQL statement that offloads the null test to the database.

NOTE: This SQL is defective as are a LOT of EfCore2.2 statements that do not take global queries into account. To be correct, it must integrate the test into the join into dtoDBOrganizer join (which may have additional filter clauses attached) and test for the pk field being filled THERE (returning false when the row there is filtered out). Just because there is a foreign key does NOT mean the object is visible to the user.

**Comment by smitpatel** [comment]
```C#
            repository.DbEventDbSet
                .AsNoTracking()
                .ProjectTo<EntityClasses.Event>(
                    TestSetup.MapperConfiguration, TestSetup.EmptyParams, nameof(DataClasses.DbEvent.Organizer)
                )
                .Where(x => x.Organizer == null)
                .ToList();
```
The where is client eval. Since it is a CLR side object (non-scalar) which is created using Automapper.  
Options you have are
- Move Where clause before ProjectTo
- Convert Where clause to something which does comparison on scalar property rather than a non-scalar object which cannot be represented in SQL. (If this non-scalar was an EntityType registered in model, we would convert it to key equality but it is a Dto type generated through AM)
- Put AsEnumerable before Where. (Bad perf but if you don't want to rewrite your query in better way).

Now going through your long post,
The last queryable operator in the exception message clearly indicates what is being client evaluated.
```C#
.Where(d => EF.Property<Nullable>(d.Inner, "PkOrganizer") == null ? null : new Organizer{ Name = d.Inner.Name }
== null)
```
Any improvement to exception message is being tracked by #20001 

> As can clearly be seen it absolutely manages to generate a SQL statement that offloads the null test to the database.

Please notice that there is no WHERE clause in the SQL you have posted. EF Core 2.2 evaluated where on client side. Which EF Core 3.x made breaking change not to do that anymore.

It is client eval as error message says. I have written how to rewrite query different to make it work. We are not going to change decision we have made on client eval at this point.

Nothing actionable in this issue. Closing.

**Comment by NetTecture** [comment]
Is there any way to get the query graph out of the system before sql translation?

This is what ef classic is generating. Automapper ProjectTo is NOT loading all items, it is generating a query graph - that gets ignored.

Ef 6.4 ggets this SQL (and I will update the repro tomorrow):

SELECT 
    1 AS [C1], 
    CASE WHEN ([Extent2].[PkOrganizer] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C2], 
    [Extent2].[Name] AS [Name], 
    [Extent1].[Title] AS [Title]
    FROM  [dbo].[Event] AS [Extent1]
    LEFT OUTER JOIN [dbo].[Organizer] AS [Extent2] ON [Extent1].[Organizer_PkOrganizer] = [Extent2].[PkOrganizer]
    WHERE [Extent2].[PkOrganizer] IS NULL

I have updated the repro, Tests.EfClassic, same setup. There the automapper generated query graph is getting the proper SQL including a where clause. I start thinking that there is some type of "we do not recognize the linq that automapper generates and thus do not propagate the where clause" scenario. Sadly there is easy way to visualize the query graph?

Given ef 6.4 offload: this is totally actionable.

**Comment by smitpatel** [comment]
> Sadly there is easy way to visualize the query graph?

Stop spending time in throwing insults and write your own tool. Hope that helps!

**Comment by NetTecture** [comment]
@smitpatel Yeah, way to go. After all, @Pilchie is not doing his job and you are not doing yours. And Ef 6.4 works. And obviously people upset by your tool not working are no something bothering you.

**Comment by NetTecture** [comment]
@smitpatel @Pilchie  It acutally Is a translation error, likely because lack of foresight to valid LINQ and focus on LINQ generated by (only) standard queries has removed some ability.

The following valid and quite basic LINQ still throws an error:

            using var repository = TestSetup.GetRepository();
            repository.DbEventDbSet
                .Select(x=> new EntityClasses.Event ()
                {
                    Id = x.PkEvent,
                    Title = x.Title,
                    Organizer = x.Organizer 
                        != null
                        ? new EntityClasses.Organizer()
                        {
                            Id = x.Organizer.PkOrganizer,
                            Name = x.Organizer.Name,
                        } 
                        : null,
                })
                .Where(x => x.Organizer == null)
                .ToList();

There is no need at this point to actually resort to client side logic. There IS a need to translate basic LINQ expressions into SQL, though.

I understand, @smitpatel , that you start being emparassed and loose the overview of knowing your product. Because at another place to another person you managed in the last 2 days to post that - oh, wait: 

"is a pattern we don't recognize to removal null."

and close it as duplicate.

So, this is a duplicate of #19997 (ups) which points down to #17020  opened last August. Which was removed from the backlog milestone yesterday.

I hate to say, but "not actionable" sounds like a lie (and yes, I come from a culture where we cal lthings what they are) that @Pilchie should have a look into this statement of yours. Yes, you guys get flooded with error reports - but if they do not get fixed... And btw., "not actionable" was and is flagged as "easy win" by you.

But you are right, chance that you actually fix this for all the people that rely on - btw., quite likely automapper on #17020, because this is about the most used tool for this. And this block makes usage of OData, btw., quite unusable outside of trivial cases because you pretty much MUST project to separate data and api objects.

**Comment by Pilchie** [comment]
@NetTecture I've hidden your comment as abusive.

This repository will not accept behavior that is not respectful and inclusive of all members of the community per it's code of conduct.  We'd like you to be a member of the community, but your current comments are offensive and will not be tolerated, regardless of whether they have technical merit.
