### ISSUE TITLE
Scaffold-DbContext generated code conflicts with 'System' namespace classes

### ISSUE THREAD

**Issue by simeyla** [dotnet/efcore#19995]
I have a table called `Environment` in my database.

My generated code does not compile because the generated table clashes with `System.Environment` - due to `using System`.

    Environment' is an ambiguous reference between 'RR.EF.ShipperDB.Models.Environment' 
    and 'System.Environment'	

### Steps to reproduce
Name a table `Environment` (or probably anything in `System` namespace)

Run `Scaffold-DbContext` command to generate context into a **different namespace.** eg.

    -o ShipperDB.Models --context-dir ShipperDB.Contexts --context ShipperDBContext

### How to fix
1) At least in my generated code the `System` namespace isn't actually consumed.

   //using System;

OR 

2) Rename the class 

OR

3) Use same namespace for context as for models. 

### Further technical details

It should be ok to just remove `using System` in the template, and fully qualify any system classes that may be used (none is in my code).

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ErikEJ** [comment]
@simeyla EF Core Power Tools offers you full control of all namespaces used.

**Comment by simeyla** [comment]
@ErikEJ This is not a showstopper by any means. I can just comment out the line and it works. The issue is there's a bug in here that should be trivial to fix,

**Comment by simeyla** [comment]
@ErikEJ This is not a showstopper by any means. I can just comment out the line and it works. The issue is there's a bug in here that should be trivial to fix,

**Comment by ajcvickers** [comment]
@simeyla We will discuss, but I think we will cover cases like this as part of #4038

**Comment by ajcvickers** [comment]
Team notes: we will continue to generate simple names by default. #4038 will allow this to be changed for those who want more qualified (e.g. namespace, assembly) names.
