### ISSUE TITLE
Databinding with WPF

### ISSUE THREAD

**Issue by juszkiem** [dotnet/efcore#19993]
I have simple issue. I cannot bind ObservableCollection in EF Core. I have tried to replicate the code that is an example for the EF6 from the following page [https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf](url) in EF core 3.1.1 code first.
I can only get as far as Bind Object to Controls section. When I open Data Source Configuration Wizard no data objects are shown in the tree. When I replicate the same steps in EF6 it works. Am I missing something or Core does not support this feature?
I know .NET Core may not support dragging the data object onto the design area, however, if data object does not show in the wizards it means there is no bindable objects in the application.

### Steps to reproduce
Follow the steps on [https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf](url)

### Further technical details

EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.4.4)

**Comment by ajcvickers** [comment]
@juszkiem I just tried and ran into the same thing. We will follow up with the WPF team.

[SimpleWpfApp.zip](https://github.com/dotnet/efcore/files/4241937/SimpleWpfApp.zip)

**Comment by ajcvickers** [comment]
@Pilchie Who's a good contact for UWP issues in Visual Studio?

**Comment by Pilchie** [comment]
@diverdan92?

**Comment by ajcvickers** [comment]
@diverdan92 Where would be a good place to follow up on WPF data binding issues?

**Comment by diverdan92** [comment]
If this is just an issue with the Visual Studio tooling, can you please file this issue in Visual Studio [directly](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)?

**Comment by ajcvickers** [comment]
@diverdan92 Can you please file the issue against Visual Studio as requested. (There is a pretty good chance it will get automatically routed back to EF and I know that will be frustrating so I apologize in advance, but it will give us a hook to drive investigation on the WPF side.)
