### ISSUE TITLE
Problem with Migration in multiple DbContext on Same DataBase at runtime

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/efcore#19996]
Hi,
I have multiple DbContext on the same database. I want to migrate all my dbcontext at runtime but only one dbcontext changes affected on database. 
this is my code:

 ```C#
public static class MigrationManager
    {
        public static IWebHost MigrateDatabase(this IWebHost webHost)
        {
            using (var scope = webHost.Services.CreateScope())
            {
                try
                {
                    MigrateShopping(scope);
                    MigrateIdentity(scope);
                }
                catch (Exception)
                {
                    //Log errors or do anything you think it's needed
                    throw;
                }
            }

            return webHost;
        }
        private static void MigrateIdentity(IServiceScope scope)
        {
            var identityDbContext = scope.ServiceProvider.GetRequiredService<ApplicationIdentityDbContext>();
            identityDbContext.Database.EnsureCreated();
            identityDbContext.Database.Migrate();
        }

        private static void MigrateShopping(IServiceScope scope)
        {
            var shoppingDbContext = scope.ServiceProvider.GetRequiredService<ShoppingDbContext>();
            shoppingDbContext.Database.EnsureCreated();
            shoppingDbContext.Database.Migrate();
        }
    }
```

**Comment by ajcvickers** [comment]
@mehdihadeli It's hard to tell from your code what is going on, but some things look suspcious--for example, calling `EnsureCreated` immediately followed by `Migrate` is unlikely to do what you expect, but it also shouldn't cause the issue you are reporting.

Please attach a small, runnable project, or post a complete code listing that reproduces what you are seeing so that we can investigate.

**Comment by mehdihadeli** [comment]
Hi @ajcvickers ,
my problem resolved. the reason was I didn't create migration files with `dotnet ef migrations add Initial_ShoppingContext` after creation migration files also removing EnsureCreated from my migration in code it worked.
my project repo: https://github.com/mehdihadeli/.Net-Core-CQRS-Shopping

**Comment by ajcvickers** [comment]
> can I do migration completely in code without using dotnet ef migrations add Initial_ShoppingContext command?

We don't have built-in support for this because we recommend that you review migrations before applying them to the database. See #6214
