### ISSUE TITLE
Query: Table alias problem with collation Finnish_Swedish_CI_AI

### ISSUE THREAD

**Issue by OrjanJa** [dotnet/efcore#19998]
When joining 2 tables whose names begin with W and V, the generated SQL contains table alias [w] and [v].
This is not working with collation Finnish_Swedish_CI_AI, where w = v.

**Comment by OrjanJa** [comment]
Update: This is only a problem with SQL Server pre-2016 (version <120).

**Comment by ajcvickers** [comment]
@OrjanJa This looks like it was a SQL Server bug that has been fixed in later releases. We don't currently plan to change what EF Core generates.
