### ISSUE TITLE
Query/Sqlite: incorrect sql generated for int + string concat queries

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#19990]
SqliteQuerySqlGenerator -> GenerateOperator is supposed to generate string concat operator `||` for Add operator and when type is string. However for case when int is concatenated with string, the type is object

**Comment by smitpatel** [comment]
Why the type is object in SqlBinaryOperator?

**Comment by smitpatel** [comment]
Notes:
- SqlExpression.Type object should not be present in the tree for most cases except un-configured SqlConvert.
- To infer type of Binary, don't use just left.Type
- To infer type of Unary, be smart.
