### ISSUE TITLE
Question: Is there any command already or planned for binding an object to an entity ?

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#1999]
Is there any command already or planned for 'merge/bind' an object to an entity ? Something along the lines with the controllers model binders.

```
var personDto = new PersonDto {Name = "Bart"};
var person = db.People.First();
db.People.Update(person, personDto);
```

**Comment by divega** [comment]
@Bartmax we do not have anything like this planned for EF7 RTM but it sounds like something we would consider adding in the future. In fact in EF6 you could do `context.Entry(person).CurrentValues.SetValues(personDto)` with similar effects. In the meanwhile, for Web applications you should be able to use the model binding functionality in MVC. I took a quick look and I think `TryUpdateModelAsync()` is what you would use in MVC6. (cc @rynowak in case there is something better)

**Comment by Bartmax** [comment]
ah right `context.Entry(person).CurrentValues.SetValues(personDto)` that was in EF6, (couldn't find it).

I like how EF7 is shaping, lot of things still needs to be done so I clearly understand that this is not something to think about right now.

Thanks @divega closing.
