### ISSUE TITLE
One property of Entity is not saved when copying from one context to another

### ISSUE THREAD

**Issue by oerpli** [dotnet/efcore#20004]
Sorry for the very general title but I couldn't figure out what is actually breaking and why.

### What am I trying to accomplish:

- I collect raw data stored in one DB (`SourceDb[Context]`)
- This should then be copied/transformed (for consumption by applications) into another DB (`TargetDb[Context]`)
- A few tables that define the basic entities would be kept in sync between the two DbContexts (though some meta data is ignored in `TargetDbContext`). Sync in this case means: If it's added/updated in `SourceDb`, do the same in `TargetDb`. 
- Loading from `Source` and adding to `Target` doesn't work because some entities already exist
- Loading from `Source` and updating `Target` doesn't work because some entities don't exist already
- My workaround is as follows:
    - Disable Key-generation in `TagertDbContext` for entities that are copied
    - Remove the whole tables in `Target`, load the whole table from `Source` and insert into `Target` (keeping IDs from `Source` in target and hoping (!) that referential integrity in `Source` ensures the same in `Target`). 

### The actual bug
I have the following types
- Person:
   - Id
   - Name

- Location
   - Id
   - Name

- TimedRelation<Person,Location>
    - Id
    - A (Person)
    - B (Location)
    - Timestamp

```csharp
public static async Task CopyStuff() {
    await using var SourceContext = new SourceDbContext();
    await using var TargetContext = new TargetDbContext();
    await using var transaction = await dtContext.Database.BeginTransactionAsync();
    // Delete existing elements
    TargetContext.RemoveRange(TargetContext.Persons);
    TargetContext.RemoveRange(TargetContext.Locations);
    TargetContext.RemoveRange(TargetContext.LocationHistory);

    var history = await SourceContext.LocationHistory
        .Include(l => l.A) // Person
        .Include(l => l.B) // Location
        .ToListAsync()
        .ConfigureAwait(false);
    // Fix Part 1 goes here
    var persons = SourceContext.Persons
        .ToDictionary(x => x.Id);
    var locations = SourceContext.Locations
        .ToDictionary(x => x.Id);
    foreach (var h in history) {
        h.A = persons[h.A.Id];
        h.B = locations[h.B.Id];
    }
    TargetContext.AddRange(history);
    await TargetContext.SaveChangesAsync();
    // Fix Part 2 goes here
    await dtContext.SaveChangesAsync();
}
```

The dictionaries and foreach loop are used to map all entities with the same Id to the same object before adding the whole thing to the DbContext (else there would be an exception due to multiple objects having the same id. 

What happens now is the following:
- If the database is empty when I run the above code, everything is inserted as it should be 
- If I run the same piece of code a second time, first everything is deleted and then reinserted, but upon reinsertion the `.B` property of the `TimedRelation` entities is missed (i.e. null). 

I found the following workaround (insert in code above at the marked positions)

```csharp
// Part 1:  Dictionary that maps `TimedRelation.Id` to `TimedRelation.B.LocationId`
var historyMap = allHistory 
       .ToDictionary(a => a.Id, a => a.B.LocationId);
...
// Part 2: Fixing each object
foreach (var hist in TargetContext.LocationHistory) {
    hist.B = await TargetContext.Locations.FindAsync(historyMap[hist.Id]);
}
await TargetContext.SaveChangesAsync();
```

While I understand that what I am doing is somewhat weird (if anyone can recommend resources that show me a better way to achieve what I am trying to achieve I would be thankful) I still think that it shouldn't happen that EF just forgets to insert one property of an entity. 

### Further technical details

EF Core version: 3.1.1 (also tried 3.1.2 - didn't change anything)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win 10 Pro
IDE: Most recent Visual Studio 2019 (16.4.5)

**Comment by AndriySvyryd** [comment]
@oerpli I think the context is getting mixed messages when you are deleting existing elements and then inserting them again in the same unit of work. Try calling `TargetContext.SaveChangesAsync()` after `RemoveRange`.

**Comment by oerpli** [comment]
I will try on Monday. Initially I didn't do so because I thought each `SaveChange` approx. corresponds to a transaction. I have since learned that these things are not related.

**Comment by oerpli** [comment]
I tried to add the  `SaveChangesAsync` after `RemoveRange` but ran into a conflict as the DB is in an invalid state after the (due to foreign key references) - the whole thing must be done in a single commit  (I omitted it from the example above as I thought it was not related to my problem).
I've amended it now with the following: 
```csharp
await using var dcContext = new DcReadOnlyContext();
await using var dtContext = new DataTransformerDbContext();
await using var transaction = await dtContext.Database.BeginTransactionAsync().ConfigureAwait(false);
// [ ... everything from above ... ] 
await transaction.CommitAsync().ConfigureAwait(false);
```

**Comment by AndriySvyryd** [comment]
I believe your issue is now resolved. Feel free to comment if you are still experiencing it.
