### ISSUE TITLE
Linq exception could not be translated has very bad error message.

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#20001]
nightly preview2.20120.1

I challenge you to find the concrete exception that requires client evaluation in this statement. For any real world usage this text dump is not helpful - the error message fails to identify the exact statement that can not be translated.

> System.InvalidOperationException: 'The LINQ expression 'DbSet<OBTIncident>
>     .Join(
>         inner: DbSet<OBTBuilding>
>             .Where(o0 => DbSet<OBVBuildingRights>
>                 .Where(o1 => EF.Property<Nullable<int>>(o0, "PkBID") != null && EF.Property<Nullable<int>>(o0, "PkBID") == EF.Property<Nullable<int>>(o1, "FkBuildingID"))
>                 .Where(o1 => o1.FkLoginID == __ef_filter__ActiveUserId_1)
>                 .Any()), 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o, "FkBID"), 
>         innerKeySelector: o0 => EF.Property<Nullable<int>>(o0, "PkBID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<OBTIncident, OBTBuilding>(
>             Outer = o, 
>             Inner = i
>         ))
>     .Where(o => DbSet<OBVBuildingRights>
>         .Where(o2 => EF.Property<Nullable<int>>(o.Inner, "PkBID") != null && EF.Property<Nullable<int>>(o.Inner, "PkBID") == EF.Property<Nullable<int>>(o2, "FkBuildingID"))
>         .Where(o2 => o2.FkLoginID == __ef_filter__ActiveUserId_0)
>         .Any())
>     .LeftJoin(
>         inner: DbSet<OBTServiceContact>
>             .Join(
>                 inner: DbSet<GTMandator>
>                     .Where(g => DbSet<GVMandatorRights>
>                         .Where(g0 => EF.Property<Nullable<int>>(g, "PkMandatorID") != null && EF.Property<Nullable<int>>(g, "PkMandatorID") == EF.Property<Nullable<int>>(g0, "FkMandatorID"))
>                         .Where(g0 => g0.FkLoginID == __ef_filter__ActiveUserId_3)
>                         .Any()), 
>                 outerKeySelector: o3 => EF.Property<Nullable<int>>(o3, "FkMandatorID"), 
>                 innerKeySelector: g => EF.Property<Nullable<int>>(g, "PkMandatorID"), 
>                 resultSelector: (o, i) => new TransparentIdentifier<OBTServiceContact, GTMandator>(
>                     Outer = o, 
>                     Inner = i
>                 ))
>             .Where(o3 => DbSet<GVMandatorRights>
>                 .Where(g1 => EF.Property<Nullable<int>>(o3.Inner, "PkMandatorID") != null && EF.Property<Nullable<int>>(o3.Inner, "PkMandatorID") == EF.Property<Nullable<int>>(g1, "FkMandatorID"))
>                 .Where(g1 => g1.FkLoginID == __ef_filter__ActiveUserId_2)
>                 .Any()), 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Outer, "FkServiceContactID"), 
>         innerKeySelector: o3 => EF.Property<Nullable<int>>(o3.Outer, "PkServiceContactID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>(
>             Outer = o, 
>             Inner = i
>         ))
>     .LeftJoin(
>         inner: DbSet<OBTAddress>, 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Inner.Outer, "FkAddressID"), 
>         innerKeySelector: o4 => EF.Property<Nullable<int>>(o4, "PkAddressID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>, OBTAddress>(
>             Outer = o, 
>             Inner = i
>         ))
>     .LeftJoin(
>         inner: DbSet<OBTTextCountry>, 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Inner, "FkCountryID"), 
>         innerKeySelector: o5 => EF.Property<Nullable<int>>(o5, "PkCountryID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>, OBTAddress>, OBTTextCountry>(
>             Outer = o, 
>             Inner = i
>         ))
>     .LeftJoin(
>         inner: DbSet<OBTTextRegion>, 
>         outerKeySelector: o => EF.Property<Nullable<int>>(o.Outer.Inner, "FkRegionID"), 
>         innerKeySelector: o6 => EF.Property<Nullable<int>>(o6, "PkRegionID"), 
>         resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<OBTIncident, OBTBuilding>, TransparentIdentifier<OBTServiceContact, GTMandator>>, OBTAddress>, OBTTextCountry>, OBTTextRegion>(
>             Outer = o, 
>             Inner = i
>         ))
>     .Where(o => EF.Property<Nullable<int>>(o.Outer.Outer.Outer.Inner.Outer, "PkServiceContactID") == null ? null : new ServiceProvider{ 
>         Address = EF.Property<Nullable<int>>(o.Outer.Outer.Inner, "PkAddressID") == null ? null : new Address{ 
>             City = o.Outer.Outer.Inner.SCity, 
>             Country = o.Outer.Inner.SIso2, 
>             CountryInfo = EF.Property<Nullable<int>>(o.Outer.Inner, "PkCountryID") == null ? null : new CountryInfo{ 
>                 Id = o.Outer.Inner.PkCountryID, 
>                 Name = o.Outer.Inner.SName 
>             }
>             , 
>             No = o.Outer.Outer.Inner.SNumber, 
>             PostCode = o.Outer.Outer.Inner.SZip, 
>             Region = o.Inner.SIso, 
>             RegionInfo = EF.Property<Nullable<int>>(o.Inner, "PkRegionID") == null ? null : new RegionInfo{ 
>                 Id = o.Inner.PkRegionID, 
>                 Name = o.Inner.SName 
>             }
>             , 
>             Street = o.Outer.Outer.Inner.SStreet 
>         }
>         , 
>         Code = o.Outer.Outer.Outer.Inner.Outer.SShortName, 
>         ContactEmailAdd = o.Outer.Outer.Outer.Inner.Outer.SContactEmailAdd, 
>         ContactPerson = o.Outer.Outer.Outer.Inner.Outer.SContactPerson, 
>         ContactPhone1 = o.Outer.Outer.Outer.Inner.Outer.SContactPhone1, 
>         ContactPhone2 = o.Outer.Outer.Outer.Inner.Outer.SContactPhone2, 
>         ContractContactEmailAdd = o.Outer.Outer.Outer.Inner.Outer.SContractContactEmailAdd, 
>         ContractContactPerson = o.Outer.Outer.Outer.Inner.Outer.SContractContactPerson, 
>         ContractContactPhone = o.Outer.Outer.Outer.Inner.Outer.SContractContactPhone, 
>         Created = o.Outer.Outer.Outer.Inner.Outer.DCreateDate, 
>         Department = o.Outer.Outer.Outer.Inner.Outer.SDepartment, 
>         Id = o.Outer.Outer.Outer.Inner.Outer.PkServiceContactID, 
>         Identity = o.Outer.Outer.Outer.Inner.Outer.GIdentity, 
>         IsInspection = o.Outer.Outer.Outer.Inner.Outer.BIsInspection, 
>         IsMaintenance = o.Outer.Outer.Outer.Inner.Outer.BIsMaintenance, 
>         Name = o.Outer.Outer.Outer.Inner.Outer.SLongName, 
>         Type = o.Outer.Outer.Outer.Inner.Outer.IType 
>     }
>      == null)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

This is WAY too much code and WAY to little information. Besides being in error (this is another bug), if I would ahve to debug a complex statement like this I would consider the tool to be primitive. I generally do know the statement at the point of this exception (or I can easily get it). What I need is the EXACT statement that produces this exception.

This is one of the smaller sql statements I have. It is the result of a get top 1 of a OBTIncident - with most joins coming from global query filters and / or being used for optional data (and SHOULD be removed at a second stage because I acutally do not ask for the data). Finding where a (possibly unrelated to my code) error has added a non translatable query filter would require me to find the excression in error. I have queries about 5 to 10 times as long.

Please:
* Remove the current text dump and provide ONLY the relevant part OR
* Add the relevant part at the beginning (the following excpression XXXX in the query graph YYYY can not be translated. There is a context where this exception is thrown anyone trying to find out where the issue is in a 10 page query graph really wants to know where it is.

**Comment by smitpatel** [comment]
You are creating `new ServiceProvider` in your code and comparing it with a null in a where predicate. That is client evaluation. For the error message that is what we can do best. We don't have original expression tree after expanding all the navigations.

**Comment by NetTecture** [comment]
@smitpatel It is not in 2.2. And I am NOT saying that I am getting this client evaluated in 2.2 - in 2.2 as well as EF 6.4 this gets properly translated in SQL. There is NO reason for this to be client evaluated outside of the translation being crappy. NOTHING in this requires client side code.

**Comment by smitpatel** [comment]
- Please tell me the SQL equivalent of `new ServiceProvider { ... } = null` since you are claiming that nothing in this requires client side code.
- You did not indicate what was behavior of EF6 or EF Core 2.2 was for this query. Please include such details in your bug report.
- If you believe that this can be translated then provide as full repro so we can actually look into it and trying to add translation.

In the absence of any information other than just the exception it threw, we do not have anything we can do here.

**Comment by NetTecture** [comment]
@smitpatel If you are sure this is the part blowing (the error message is not clear) I will easily make a repro for it ;) It will be here latest monday.

**Comment by ajcvickers** [comment]
We talked about the length of the expression in the error message and agree that it is very hard to figure out which part is failing. We have some ideas on how to improve this, but it is non-trivial to identify the problematic interaction and present it clearly. We will discuss as a team how to best move forward here.
