### ISSUE TITLE
Code first migrations do not set custom column type correctly while using RelationalTypeMapping

### ISSUE THREAD

**Issue by ConfiDev** [dotnet/efcore#20019]
I'm trying to create an custom RelationalTypeMapping to convert objects to json and vice versa. So I do not have to use the HasConversion in the EntityTypeBuilder for every property but just define it once globally.

It looks something like that
``` C#
public class JsonTypeMapping<T> : RelationalTypeMapping
        where T : class
{
    private readonly IJsonSerializer _jsonSerializer;

    public JsonTypeMapping(IJsonSerializer jsonSerializer)
        : base(new RelationalTypeMappingParameters(new CoreTypeMappingParameters(typeof(T), new JsonValueConverter<T>(jsonSerializer)), "json1"))
    {
        _jsonSerializer = jsonSerializer;
    }

    protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)
    {
            return new JsonTypeMapping<T>(_jsonSerializer);
    }
}
```
There I set the "storeType", which I assume is the column type, to "json1" (the SQLite DB Type).
I inject this JsonTypeMapping<T> into the IServiceCollection of the DbContext which works just fine and use the following Model with the Property "Metaddata" which I want to store in a "json1" db column

``` C#
[Table("environment")]
public class EnvironmentEntity
{
    [Column("id")]
    public string Id { get; set; }
        
    [Column("name")]
    public string Name { get; set; }
        
    [Column("meta")]
    public JObject Metadata { get; set; }
}
```

After running the "dotnet ef migrations add <name>" command I get the following lines of code.
In the ModelSnapshot
``` C#
...
modelBuilder.Entity("InfrastructureMonitor.Repository.Database.Models.EnvironmentEntity", b =>
{
    b.Property<string>("Id")
        .HasColumnName("id")
        .HasColumnType("TEXT");

    b.Property<string>("Metadata")
        .HasColumnName("meta")
        .HasColumnType("json1");

    b.Property<string>("Name")
        .HasColumnName("name")
         .HasColumnType("TEXT");

    b.HasKey("Id");

    b.HasIndex("Name")
        .IsUnique();

    b.ToTable("environment");
});
...
```
There I see the ".HasColumnType("json1");" which I expect.
In the Migration file on the other hand it looks like that
``` C#
...
migrationBuilder.CreateTable(
    name: "environment",
    columns: table => new
    {
        id = table.Column<string>(nullable: false),
        name = table.Column<string>(nullable: true),
        meta = table.Column<string>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_environment", x => x.id);
    });
...
```
I would expect "meta = table.Column<string>(type: "json1", nullable: true)" instead of "meta = table.Column<string>(nullable: true)".
Running this migration leads to a column with the type "TEXT" instead of "json1".

Designing the Model like that:
``` C#
[Table("environment")]
public class EnvironmentEntity
{
    [Column("id")]
    public string Id { get; set; }
        
    [Column("name")]
    public string Name { get; set; }
        
    [Column("meta", TypeName = "json1")]
    public JObject Metadata { get; set; }
}
```
"fixes" the issue, but it's not really what I'm looking for, since the idea behind using a RelationalTypeMapping is to only have the type information at one place.

Is this the expected behavior or do I do something wrong here?

Thanks in advance!

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET Core 3.1

**Comment by ajcvickers** [comment]
@ConfiDev It looks like you're losing type mapping parameters when the mapping is cloned. The Clone method should look something like:

```C#
protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)
            => new SqlServerStringTypeMapping(parameters, _sqlDbType);
```
Take a look at `SqlServerStringTypeMapping` as an example.

**Comment by ConfiDev** [comment]
I took a closer look at the `SqlServerStringTypeMapping` but it didn't really help me to get closer to a solution. I tried it with the suggested modifications. But by that I found the `SqliteGeometryTypeMapping<TGeometry>` which was very helpful, since it is closer to what I'm trying to do.

So I tried the following model, to see the resulting migration files
``` C#
[Table("environment")]
public class EnvironmentEntity
{
    [Column("id")]
    public string Id { get; set; }
        
    [Column("name")]
    public string Name { get; set; }
        
    [Column("meta")]
    public Point Metadata { get; set; }
}
```

This resulted in the following ModelSnapshot
``` C#
modelBuilder.Entity("InfrastructureMonitor.Repository.Database.Models.EnvironmentEntity", b =>
{
    b.Property<string>("Id")
         .HasColumnName("id")
         .HasColumnType("TEXT");

    b.Property<Point>("Metadata")
        .HasColumnName("data")
        .HasColumnType("POINT");

    b.Property<string>("Name")
        .HasColumnName("name")
        .HasColumnType("TEXT");

    b.HasKey("Id");

    b.HasIndex("Name")
        .IsUnique();

    b.ToTable("environment");
});
```
And here I do not only see the `.HasColumnType("POINT");` but also `b.Property<Point>("Metadata")`

And the Migration file is as following
``` C#
migrationBuilder.CreateTable(
    name: "environment",
    columns: table => new
    {
        id = table.Column<string>(nullable: false),
        name = table.Column<string>(nullable: true),
        data = table.Column<Point>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_environment", x => x.id);
    });
```
And here the generated code also does not set the `columnType` but uses the `Point` class directly, which is working perfectly fine, while creating the DB, reading and writing from/to it.

So I tried to understand why this is working and it seems like, that the `RelationalGeometryTypeMapping<TGeometry, TProvider>` is not setting the `ValueConverter<TGeometry, TProvider>` directly in the `CoreTypeMappingParameters` like I did.
[RelationalGeometryTypeMapping.cs#L61](https://github.com/dotnet/efcore/blob/7ae89d6adb7433b6ae9c37091e57a1226092ef46/src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs#L61)

But is using the converter in the overwritten `CreateParameter` and `CustomizeDataReaderExpression` methods
[RelationalGeometryTypeMapping.cs#L88](https://github.com/dotnet/efcore/blob/7ae89d6adb7433b6ae9c37091e57a1226092ef46/src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs#L88)
[RelationalGeometryTypeMapping.cs#L113](https://github.com/dotnet/efcore/blob/7ae89d6adb7433b6ae9c37091e57a1226092ef46/src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs#L113)

So I dig a little bit depper and I think I found the code responsible for creating the migration file.
[MigrationsModelDiffer.cs#L1043](https://github.com/dotnet/efcore/blob/7ae89d6adb7433b6ae9c37091e57a1226092ef46/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L1043)
And there I can see, that the `storeType` set in the `RelationalTypeMappingParameters` is not used at all. But the `storeType` parameter is also not available there anymore since there is only the `CoreTypeMappingParameters` object.
And since the `ClrType` of my column is `string` in my initial case, while generating the migration SQL the `storeType` `TEXT` is taken.
I debugged a little and saw it in the following method call
[SqliteTypeMappingSource.cs#L112](https://github.com/dotnet/efcore/blob/9abd61d3fb4cdd1041f25fe2e10c70ee3dc4055e/src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs#L112)
The `RelationalTypeMappingInfo` `StoreTypeName` is actually `json1` but since there is a type mapper for the `ClrType` `string`, that one is taken first.

So my conclusion would be, that it is only possible to get my code working, by either setting the `columnType` with the property-attribute or implementing a similar approach like in the `RelationalGeometryTypeMapping<TGeometry, TProvider>`. But overwriting the `CustomizeDataReaderExpression` method seems not trivial at all.

**Comment by ajcvickers** [comment]
@ConfiDev Taking a step back here, I think it's important to understand that by creating a type mapping like this you're essentially adding handling for a new database-native type to the database provider. This is a lot more than just using a value converter with an existing mapping. It's also complicated by the fact that the database doesn't really support this native type, which means this isn't really the way to do what you want.

I spent some digging into the your code, but I didn't make much progress. Instead it made me realize that creating a RelationalTypeMapping is a pretty difficult way to workaround for #10784. The bulk configuration in OnModelCreating shown in the issue seems much more practical.

**Comment by ConfiDev** [comment]
Thanks for your time and the explanation!

> @ConfiDev Taking a step back here, I think it's important to understand that by creating a type mapping like this you're essentially adding handling for a new database-native type to the database provider. This is a lot more than just using a value converter with an existing mapping. It's also complicated by the fact that the database doesn't really support this native type, which means this isn't really the way to do what you want.

I see your point here. With that explanation I totally agree with you.

> I spent some digging into the your code, but I didn't make much progress. Instead it made me realize that creating a RelationalTypeMapping is a pretty difficult way to workaround for #10784. The bulk configuration in OnModelCreating shown in the issue seems much more practical.

I'll take a look at #10784 and the workaround there. Thanks for the hint!

Fingers crossed you guys find the time to implement this in 5.0.
