### ISSUE TITLE
Scaffolding Tables with COmposite FK keys mix the order of relationship

### ISSUE THREAD

**Issue by jeffersoil** [dotnet/efcore#20018]
Hi!

I'm using Oracle.EmtityFrameworkCore to scaffold a database with almost 100 tables and many tables having Composite Pks and FKs.

When Scaffold is processing, it maps the tables and mix the order of foreign keys, do not allowing the process to complete:

    The types of the properties specified for the foreign key {'SicIdCco', 'SicNrAno', 'SicNrNumOsm', 
    'SicNrSsm'} on entity type 'SicModulo' do not match the types of the properties in the principal 
    key {'NrNumOsm', 'SicIdCco', 'SicNrAno', 'SicNrSsm'} on entity type 'SicOsm'.

I think that the script is not respecting the order of declared columns in the PK and FK parameters of the tables and it's getting the order of the phisical position of columns in tables, that could be very harmfull in compelx contexts

The erros vanish if i change the PK order of the column to the exacly order of the table

**Comment by ajcvickers** [comment]
@jeffersoil I have been unable to reproduce this with a similar database structure when using a SQL Server database. This leads me to believe that an issue with the Oracle provider for EF Code, in which case you need to contact Oracle. If this isn't the case, then please post a small, runnable project that reproduces the behavior you are seeing so we can investigate.

**Comment by jeffersoil** [comment]
@ajcvickers I found that the order of issuing the FK relationships is the same order that is used when issuing the lambda command Find(). Its semms really a bug in the ODP provider,or at least a undocumented role for creating the PKs on the Oracle side. Thanks 4 the help.
