### ISSUE TITLE
Log a warning when KeyAttribute overrides KeylessAttribute

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20014]

**Comment by ajcvickers** [comment]
Note that `[Key]` goes on properties, while `[Keyless]` goes on types. For example:

```C#
[Keyless]
public class Product
{
    [Key]
    public int Id { get; set; }
}
```

In this case the entity should become keyless because that's the EF-specific configuration. Key _may_ be required by something else outside of EF.

This should still warn.

**Comment by smitpatel** [comment]
Put placeholder on where to add warning. Un-assigning myself.

**Comment by lajones** [comment]
I'm on the message.
