### ISSUE TITLE
EF Core tools migrations list function returns extra output

### ISSUE THREAD

**Issue by Krystian-D** [dotnet/efcore#20039]
Entity Framework Core .NET Command-line Tools 3.1.2

When using `dotnet ef migrations list --project` command following extra output is included :
Build started...
Build succeeded.

This is causing a slight issue with our build step which is listing all migrations and then generates individual script for each migration because 
_Build started..._ and _Build succeeded._ aren't valid migrations

This wasn't an issue in Entity Framework Core .NET Command-line Tools 3.0.0
or in .Net Core SDK 2 when ef tools were part of SDK.
### Steps to reproduce

- Create EF project
- Add multiple migrations
- Run `dotnet ef migrations list --project`  command

### Further technical details

Tool: Entity Framework Core .NET Command-line Tools 3.1.2
EF Core version: 2.2.6
Database provider:
Target framework: .NET Core 3.1.2
Operating system: Windows 10
IDE:

**Comment by smitpatel** [comment]
Also consider `--json` option. A structured JSON would be more appropriate then parsing command line output. https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#common-options

We will look into more what we can improve here. May be a `--quiet` flag.

**Comment by smitpatel** [comment]
After discussing with @bricelam,
using `--prefix-output` flag would help more in this case. Just look for lines which starts with `data` prefix. Other output lines would be prefixed with different tags to separate them out.

**Comment by bricelam** [comment]
Example:
```ps1
$migrations = dotnet ef migrations list --prefix-output --json |
    where { $_.StartsWith('data:') } |
    foreach { $_.Substring(5) } |
    ConvertFrom-Json
```

**Comment by Krystian-D** [comment]
@bricelam Thank you very much that's very helpful.

**Comment by AlexandreBossard** [comment]
```dotnet ef migrations --no-build list --json```

does not build, and so, does not output the thing.

Now the question is how can we just build the migrations.
