### ISSUE TITLE
High ram during compile of EF.Core Project

### ISSUE THREAD

**Issue by yakeer** [dotnet/efcore#20032]
Hello,
I have an EF core version 3.0.0 project,
With quite a large relational db context (around 200 entities).
The Migrations assembly is in the same project, with around 200 migrations (this is an ongoing project).

My issue is, that during build, the RAM of dotnet process (MacOS, but also happens in Windows Machine) is going up to 7GB.

Is this normal? am I doing something not according to Best Practice?

**Comment by ajcvickers** [comment]
@yakeer There are of course many factors involved, but this does not seem abnormally high to me, especially when the build is automatically handled by multiple underlying processes.

With regard to the number of migrations, we do recognize this as an issue. We have ideas in this area such as being able to [automatically squash migrations](https://github.com/dotnet/efcore/issues/2174), and making it easy for migrations to be [more separated from main application code](https://github.com/dotnet/efcore/issues/19587).

Try the [Roslyn repo](https://github.com/dotnet/roslyn) if we want to follow up further on compiler memory use.
