### ISSUE TITLE
code first ColumnType Date and HasDefaultSqlValue

### ISSUE THREAD

**Issue by DavidStania** [dotnet/efcore#20045]
Hey guys,
i've got the following issues working with code first.

 `  [Column(TypeName = "Date")]
    public DateTime Datum { get; set; }
`

with this builderconfiguration

`builder.Property(r => r.Datum).HasDefaultValueSql("GETUTCDATE()").IsRequired();`

generates this migration code:

`            migrationBuilder.AddColumn<DateTime>(
                name: "Datum",
                table: "Stoerung",
                type: "Date",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));`

ColumnType is still right, but I expected that defaultSqlValue is set to "GETUTCDATE()"

another issue I get is if I'm using fluent api for specify ColumnType instead DataAnnotation like:

`builder.Property(r => r.Datum).HasColumnType("Date").HasDefaultValueSql("GETUTCDATE()").IsRequired();`

folowing migration code is generated:

`migrationBuilder.AddColumn<DateTime>(
                name: "Datum",
                table: "Stoerung",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));`

ColumnType "Date" is missing and also defaultSqlValue is wrong.
### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.5

**Comment by DavidStania** [comment]
> Hey guys,
> i've got the following issues working with code first.
> 
> ` [Column(TypeName = "Date")] public DateTime Datum { get; set; }`
> 
> with this builderconfiguration
> 
> `builder.Property(r => r.Datum).HasDefaultValueSql("GETUTCDATE()").IsRequired();`
> 
> generates this migration code:
> 
> ` migrationBuilder.AddColumn<DateTime>( name: "Datum", table: "Stoerung", type: "Date", nullable: false, defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));`
> 
> ColumnType is still right, but I expected that defaultSqlValue is set to "GETUTCDATE()"
> 
> another issue I get is if I'm using fluent api for specify ColumnType instead DataAnnotation like:
> 
> `builder.Property(r => r.Datum).HasColumnType("Date").HasDefaultValueSql("GETUTCDATE()").IsRequired();`
> 
> folowing migration code is generated:
> 
> `migrationBuilder.AddColumn<DateTime>( name: "Datum", table: "Stoerung", nullable: false, defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));`
> 
> ColumnType "Date" is missing and also defaultSqlValue is wrong.
> 
> ### Further technical details
> EF Core version: 3.1.2
> Database provider: Microsoft.EntityFrameworkCore.SqlServer
> Target framework: .NET Core 3.1.2
> Operating system: Windows 10
> IDE: Visual Studio 2019 16.4.5

### Further information
I'm using **IEntityTypeConfiguration** like below:

`public abstract class AuditierbarConfiguration<T> : IEntityTypeConfiguration<T>
    where T : Auditierbar<T>
    {
        public virtual void Configure(EntityTypeBuilder<T> builder)
        {
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Id).ValueGeneratedOnAdd();
            builder.HasIndex(r => r.ErstelltDurch);
            builder.HasIndex(r => r.AktualisiertDurch);
            builder.HasIndex(r => r.GelöschtDurch); 
            builder.Property(r => r.Erstellt).IsRequired();
            builder.Property(r => r.Aktualisiert).IsRequired();
            builder.Property(r => r.Deaktiviert);
        }
    }`

at this point, `*.HasColumnType("Date").HasDefaultValueSql("GETUTCDATE()")` is ignored.

**Comment by ajcvickers** [comment]
@DavidStania Is your configuration code being called? Are you creating an `AuditierbarConfiguration` instance in `OnModelCreating` and calling `Configure` on it?

**Comment by DavidStania** [comment]
@ajcvickers Thank you for reply.

I'm calling
`protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
        }`

in my DbContext-Class.

**Comment by ajcvickers** [comment]
@DavidStania Try using the concrete configurations explicitly instead of calling `ApplyConfigurationsFromAssembly`. If that works, then the issue is that `ApplyConfigurationsFromAssembly` is not finding them for some reason, which we can look into.

**Comment by DavidStania** [comment]
@ajcvickers i can confirm that.
My workaround was to call the concrete configuration in my Model like:

```c#    public class StörungsmeldungConfiguration : IEntityTypeConfiguration<Störungsmeldung>
    {
        public void Configure(EntityTypeBuilder<Störungsmeldung> builder)
        {
            builder.ToTable("Stoerung");
            builder.HasIndex(r => new { r.UnternehmenId, r.FertigungsauftragId, r.ArbeitssystemId, r.Datum });
            builder.HasIndex(r => new { r.UnternehmenId, r.ArbeitssystemId, r.Datum });
            builder.HasIndex(r => new { r.UnternehmenId, r.Datum });
            builder.Property(r => r.Start).IsRequired();
            builder.Property(r => r.Reparateur).HasMaxLength(255);
            builder.Property(r => r.Bemerkung).HasMaxLength(255);
            builder.Property(r => r.Datum).IsRequired().HasColumnType("Date").HasDefaultValueSql("GetUtcDate()");
        }
    }
```

This is working as expected. Migration code:
```c#
migrationBuilder.AddColumn<DateTime>(
                name: "Datum",
                table: "Stoerung",
                type: "Date",
                nullable: false,
                defaultValueSql: "GetUtcDate()");
```

**Comment by ajcvickers** [comment]
@DavidStania Make sure you have concrete classes for each `IEntityTypeBuilder` in your assembly. For example:

```C#
public class StörungsmeldungConfiguration : AuditierbarConfiguration<Störungsmeldung>
{
    ...
}
```

The abstract base type won't itself be discovered.

**Comment by DavidStania** [comment]
@ajcvickers I created a model with less complexity based on my implementation
```C#
    public abstract class Auditierbar<T>
    {
        public T Id { get; set; }
        public DateTime Changed { get; set; }
        public DateTime Created { get; set; }
        public DateTime Date { get; set; }
    }
    public class AuditierbarConfiguration<T> : IEntityTypeConfiguration<T> where T : Auditierbar<T>
    {
        public void Configure(EntityTypeBuilder<T> builder)
        {
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Date).HasColumnType("Date").HasDefaultValueSql("GetUtcDate()");
            builder.Property(r => r.Changed).HasDefaultValueSql("GetUtcDate()");
            builder.Property(r => r.Created).HasDefaultValueSql("GetUtcDate()");
        }
    }
    public class Stoerung : Auditierbar<Guid>
    {
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }
    public class StoerungsmeldungConfiguration : AuditierbarConfiguration<Stoerung>
    {
        public void Configure(EntityTypeBuilder<Stoerung> builder)
        { 
            builder.ToTable("Stoerung"); 
```
If I'm right with your proposal, that should work. But it doesn't. Getting that error Message

> **Compiler Error CS0311** Der Typ "WebApplication1.Data.Stoerung" kann nicht als Typparameter "T" im generischen Typ oder in der generischen Methode "AuditierbarConfiguration<T>" verwendet werden. Es ist keine implizite Verweiskonvertierung von "WebApplication1.Data.Stoerung" in "WebApplication1.Data.Auditierbar<WebApplication1.Data.Stoerung>" vorhanden.

Where is my mistake?

**Comment by DavidStania** [comment]
Allright! Found the problem by myself. I had a wrong implementation of  the BaseClass

```C#
    public class BaseEntity<TEntity, T>
    {
        public T Id { get; set; }
        public DateTime Changed { get; set; }
        public DateTime Created { get; set; }
        public DateTime Date { get; set; }
    }
    public class BaseEntityConfigurations<TEntity, T> : IEntityTypeConfiguration<TEntity> where TEntity : BaseEntity<TEntity, T>
    {
        public virtual void Configure(EntityTypeBuilder<TEntity> builder)
        {
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Id).ValueGeneratedOnAdd();
            builder.HasIndex(r => r.Date);
            builder.Property(r => r.Date).HasColumnType("Date").HasDefaultValueSql("GetUtcDate()");
            builder.Property(r => r.Changed).HasDefaultValueSql("GetUtcDate()");
            builder.Property(r => r.Created).HasDefaultValueSql("GetUtcDate()");
        }
    }
    public class Stoerung : BaseEntity<Stoerung, Guid>
    {
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }
    public class StoerungConfiguration : BaseEntityConfigurations<Stoerung, Guid>
    {
        public override void Configure(EntityTypeBuilder<Stoerung> builder)
        {
            base.Configure(builder);
            builder.ToTable("Stoerung");
        }
    }
```
My migration code looks like
```C#
migrationBuilder.CreateTable(
                name: "Stoerung",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Changed = table.Column<DateTime>(nullable: false, defaultValueSql: "GetUtcDate()"),
                    Created = table.Column<DateTime>(nullable: false, defaultValueSql: "GetUtcDate()"),
                    Date = table.Column<DateTime>(type: "Date", nullable: false, defaultValueSql: "GetUtcDate()"),
                    StartTime = table.Column<DateTime>(nullable: false),
                    EndTime = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Stoerung", x => x.Id);
                });
migrationBuilder.CreateIndex(
                name: "IX_Stoerung_Date",
                table: "Stoerung",
                column: "Date");
```

Everythink is working like expected!

Thank you @ajcvickers for support.
