### ISSUE TITLE
linq left join .ToString() not work

### ISSUE THREAD

**Issue by staneee** [dotnet/efcore#20069]
I have two tables, the Id field in table A is of type long, and the Id field in the associated table A in table B is of type string.
Table A.ID.ToString() cannot be translated into SQL when linq is used for left join queries.

### Steps to reproduce

```C#
    public class Table1
    {
        public long Id { get; set; }

        public string Value { get; set; }

    }

    public class Table2
    {
        public long Id { get; set; }

        public string Value { get; set; }

        public string Table1Id { get; set; }
    }
```

```C#
var dbContext = new AppDbContext();

var query = from table2 in dbContext.Set<Table2>().AsQueryable()
            join table1 in dbContext.Set<Table1>().AsQueryable()  on table2.Table1Id equals table1.Id.ToString() into table1Joind
            from table1 in table1Joind.DefaultIfEmpty()
			select new
            {
                Table1Value=table1.Value,
                Table2Value=table2.Value,
            };
			
var result = await query.ToListAsync();
```

### Further technical details

EF Core version: 3.1.1
Database provider: Devart.Data.Oracle.EFCore 9.11.951
Target framework: .NET Core 3.1
Operating system: windows 10 professional X64
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by qinhuan456** [comment]
Me too.What Shall I do？I don't want to change entities

**Comment by smitpatel** [comment]
Translation of `ToString` to SQL is provider specific translation. This should be reported to the provider you are using.

**Comment by ajcvickers** [comment]
Closing this as external. Please follow up with Devart.
