### ISSUE TITLE
Update to security template

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20068]
So behind the scene something added a new commit https://github.com/dotnet/efcore/commit/659ecfd2842cb6710d40ecf39f671c28b437fc4f

(tell me more about automation taking over the world!)

Anyway, looking at aspnetcore repo the details have changed a little https://github.com/dotnet/aspnetcore/pull/19236
Our repo does not have security.MD in repo root, rather it is inside .github folder.
- Which one do we keep?
- Make sure the one we keep is up-to-date.

**Comment by ajcvickers** [comment]
@Pilchie We would like to understand:
* What happened here that resulted in a bot adding a file to the repo without any PR or sign-off
* What the guidance is for `security.md` especially given that we now have two files in two locations with conflicting information.

**Comment by Pilchie** [comment]
I'm not sure what this is.  @mmitche do you know?

**Comment by mmitche** [comment]
@terrajobst did this as a project for Barry

**Comment by ajcvickers** [comment]
@terrajobst Ping.

**Comment by ajcvickers** [comment]
@terrajobst Ping.

**Comment by terrajobst** [comment]
> * What happened here that resulted in a bot adding a file to the repo without any PR or sign-off

I've sent you an email with the details

> * What the guidance is for `security.md` especially given that we now have two files in two locations with conflicting information.

That I don't know. @blowdart needs to answer how he sees [SECURTY.md](https://github.com/dotnet/efcore/blob/master/SECURITY.md) vs. [docs/security.md](https://github.com/dotnet/efcore/blob/master/docs/security.md).

**Comment by blowdart** [comment]
Its your choice really, as long as all the info is there, including the bug bounty link then I'm good.

**Comment by ajcvickers** [comment]
@smitpatel Do you want to clean this up?

**Comment by smitpatel** [comment]
Yes, I do.
