### ISSUE TITLE
Unable to migrate database if using UDF in HasComputedColumnSql

### ISSUE THREAD

**Issue by MarkLFT** [dotnet/efcore#20119]
I have a table that includes 4 computed columns.  These columns are defined in EF as 
```C#
builder.Property(x => x.IsSupervisor)
       .HasComputedColumnSql("([dbo].[IsSupervisor]([OperatorGroupId]))");
```
In VS the project builds ok, and I can use the add-migration command.  But update-database fails as the UDFs do not exist yet.

I tried to create the UDFs manually first, but cannot as they refer to tables and fields being created in the update-database.

So I created placeholder UDFs with the correct structure, but no content. This allowed the update-database to work, but now I am unable to give the UDFs their content as it reports they are being used by table xyz. 

I am at a loss on how to get out of this loop. I have searched the internet, but I am unable to find a solution.  Is this a bug, or am I missing something?

I am using the latest EFCore for SQL, version 3.1.2.

**Comment by ajcvickers** [comment]
@bricelam to take a look.

**Comment by bricelam** [comment]
You need to create the UDF as part of your migration:
```cs
protected override void Up(MigrationBuilder migrationBuilder)
{
    // Create tables the function depends on

    migrationBuilder.Sql(@"
        CREATE FUNCTION IsSupervisor ...
    ");

    // Create columns that depend on the funciton
}
```
