### ISSUE TITLE
dynamic switch table

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [dotnet/efcore#20112]
I would like to ask how to implement dynamic switch data table in efcore？

**Comment by AndriySvyryd** [comment]
What's a dynamic switch data table? And how would you use it?

**Comment by zhanghaiboshiwo** [comment]
@AndriySvyryd I want to use EFCore for sub-library sub-tables

**Comment by zhanghaiboshiwo** [comment]
I found a way to do it but it tells me that the null pointer  wrong
![微信图片_1](https://user-images.githubusercontent.com/43592384/75638693-25dfce80-5c68-11ea-8105-140007d394d2.png)
![微信图片_2](https://user-images.githubusercontent.com/43592384/75638698-28dabf00-5c68-11ea-9e09-9fa820d9f3b8.png)

**Comment by AndriySvyryd** [comment]
That usually indicates that you are trying to modify a model after it has been validated.
Please provide a small runnable project that shows what you are trying to do.

**Comment by zhanghaiboshiwo** [comment]
@AndriySvyryd 
[ConsoleApp2.zip](https://github.com/dotnet/efcore/files/4273164/ConsoleApp2.zip)

**Comment by AndriySvyryd** [comment]
@zhanghaiboshiwo You should update the model by overriding [OnModelCreating](https://docs.microsoft.com/en-us/ef/core/modeling/)

**Comment by zhanghaiboshiwo** [comment]
But what I want to say is that I have multiple tables with the same structure but different table names. I want to switch tables dynamically through this method

**Comment by zhanghaiboshiwo** [comment]
Because my tables are automatically generated according to the rules

**Comment by zhanghaiboshiwo** [comment]
@AndriySvyryd

**Comment by AndriySvyryd** [comment]
You can use different contexts or [build the model dynamically](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model)
