### ISSUE TITLE
NRE thrown when running migrations with incorrect store type

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20115]
While working on a user repro, MigrationsSqlGenerator threw an NRE [from here](https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs#L1206) because migrations meant for SQL Server were executed on PostgreSQL. The store type in the migrations was incorrect (did not correspond to CLR type for Npgsql), and so a type mapping wasn't found. We should throw a better exception here.

/cc @bricelam

**Comment by ajcvickers** [comment]
@roji This is probably covered by #15174
