### ISSUE TITLE
lowercase table and column settings

### ISSUE THREAD

**Issue by AucT** [dotnet/efcore#20123]
Some people use mysql, postgresql.
Would be nice to have switcher so ef will use lower_case style for table and column names.

**Comment by AndriySvyryd** [comment]
Something like https://github.com/efcore/EFCore.NamingConventions?

**Comment by AucT** [comment]
Yes, would be nice if ef core has this included.

**Comment by ajcvickers** [comment]
@AucT It's included with the Npgsql provider.
