### ISSUE TITLE
Mocking IDBContextTransaction for unit tests

### ISSUE THREAD

**Issue by MikeRavenelle** [dotnet/efcore#20129]
I am attempting to write unit tests for a controller in my project. I am running into an issue where `using (var dbContextTransaction = _database.BeginTransaction())` is not handled correctly when using` InMemoryAliasDbContext `to mock my` DbContext`. It will immediately dispose and none of my method code is tested/executed.

### Steps to reproduce

1. Have a controller method that uses 
2. `using (var dbContextTransaction = _database.BeginTransaction())`
3. Write a unit test that calls this method and uses ~~InMemoryAliasDbContext~~ `UseInMemoryDatabase` to mock the database.
(https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)
4. Run the unit test
5. Method disposes immediately when `using (var dbContextTransaction = _database.BeginTransaction())` is hit and exits method.

### Further technical details

EF Core version: 3.0.0
Database provider: Sqllite
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.4.5)

**Comment by ajcvickers** [comment]
@MikeRavenelle I'm not sure where `InMemoryAliasDbContext` comes from, but I would strongly recommend not trying to create a test double for `DbContext`. Instead, if you want to write tests at this level, then I would consider creating your own interface or even a repository that defines the behaviors you want to be able to mock and use that.

**Comment by MikeRavenelle** [comment]
I apologize as I made my previous post in a rush.

I am using a class called `InMemoryAliasDbContext `that uses:

```
 var options = new DbContextOptionsBuilder<AliasContext>()
                   .UseInMemoryDatabase(Guid.NewGuid().ToString())
                   .Options;

var context = new AliasContext(options)
```
to create contexts for my unit tests. It is based off this microsoft documentation.

[(https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)]

**Comment by ajcvickers** [comment]
@MikeRavenelle The in-memory provider doesn't support transactions. I suspect `using (var dbContextTransaction = _database.BeginTransaction())` is throwing an exception saying that and that's why your method is ending.

> System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Database.Transaction.TransactionIgnoredWarning': Transactions are not supported by the in-memory store. See http://go.microsoft.com/fwlink/?LinkId=800142 This exception can be suppressed or logged by passing event ID 'InMemoryEventId.TransactionIgnoredWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

As it says in the message, you can make transactions a no-op if you don't actually need transaction functionality in your tests.

If this doesn't help, then please attach a small, runnable project that reproduces the behavior you are seeing so that we can investigate.

**Comment by MikeRavenelle** [comment]
That seems to have fixed the issue! Thanks
