### ISSUE TITLE
Update BenchmarkDotNet version

### ISSUE THREAD

**Issue by JamesNK** [dotnet/efcore#20127]
I have created PRs to update BenchmarkDotNet in aspnetcore and extensions. Should probably update the version used here as well. The version used is two years old.

Example of resolving breaking changes and obsolete APIs in BenchmarkDotNet - https://github.com/dotnet/extensions/pull/3043

**Comment by roji** [comment]
Thanks @JamesNK, am planning a general cleanup round and will do this as part of it.
