### ISSUE TITLE
Question: How to delete and migrate multiple times with a single DbContext?

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/efcore#20120]
For a certain scenario, I need a way to let me delete and migrate databases multiple times.
The following code is the minimal example simulating what I want to do.  However, it generates an error as follows.

> The instance of entity type 'Todo' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using System;
using System.IO;

namespace Experiment
{
    class Todo
    {
        public int Id { get; private set; }
        public string Description { get; set; }
    }

    class AppDbContext : DbContext
    {
        public DbSet<Todo> Todos { get; private set; }
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlite("Data Source = Database.db");
        }
    }

    class MigrationBait : IDesignTimeDbContextFactory<AppDbContext>
    {
        public AppDbContext CreateDbContext(string[] args) => new AppDbContext();
    }

    class Program
    {
        static void Main(string[] args)
        {
             // Assume that context is given as a singleton.
            AppDbContext context = new AppDbContext(); 

            try
            {
                // Here is the simplest example only for simulating the recreation.
                for (int i = 0; i < 2; i++)
                {
                    context.Database.EnsureDeleted();
                    context.Database.Migrate();
                    context.Todos.Add(new Todo { Description = $"i={i}" });
                    context.SaveChanges();
                }
            }
            catch (Exception error)
            {
                Console.WriteLine("Errors!");
                File.WriteAllText("log.txt", error.InnerException.Message);
            }
        }
    }
}
```

How to fix this issue?

**Comment by ajcvickers** [comment]
@pstricks-fans Don't reuse the context instance. Deleting a database while it is still tracking entities in that database is generally not a good idea. In your case I don't think you're trying to do this, but because re-use a context instance that is already tracking entities then that's in effect what you are doing.

**Comment by pstricks-fans** [comment]
@ajcvickers : Thank you for replying. 

Is it possible to remove the tracking first, followed by deleting the database and then migrating plus creating a new database? I am a newbie.

**Comment by ajcvickers** [comment]
@pstricks-fans General guidance is to use a new context instance for each unit of work. These are definitely different units of work, so a new context instance for each is much more appropriate than attempting to reuse.

**Comment by pstricks-fans** [comment]
@ajcvickers : OK. Thank  you. I understood now. However, for this scenario, how to remove the tracking in the context? It is fine if it is not possible.

**Comment by ajcvickers** [comment]
@pstricks-fans If you mean how can you not use tracking at all, then you can't.  SaveChanges _requires_ tracking.

**Comment by pstricks-fans** [comment]
@ajcvickers Thank you very much!
