### ISSUE TITLE
Performance regression on Fortunes

### ISSUE THREAD

**Issue by sebastienros** [dotnet/efcore#20131]
c.f. PowerBI dashboard

![image](https://user-images.githubusercontent.com/1165805/75730395-a40c9700-5ca1-11ea-98c4-645d3953e1b6.png)

It doesn't show up on scenarios without EF.
There hasn't been a change in the EF version around this regression, so we might consider moving it to the runtime repos once it has been confirmed this is due to a change in the runtime.

TODO: verify by running the benchmark on the two runtime versions that show the delta.

**Comment by roji** [comment]
Thanks @sebastienros. I now try to do regular weekly syncs for the Npgsql EF Core provider, so it's possible this represents a real regression. Is it possible to get the versions of the Npgsql EF Core provider before and after this regression?

**Comment by sebastienros** [comment]
@roji I don't record that, but I don't think you changed the version during this time. I looked at the change log. We can change the csproj (in a branch) to accept a version as an argument, and change it to see if there something.
