### ISSUE TITLE
beta5 command does not contain a static Main

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#2013]
i'm getting the follow error when trying to target ef 7.0.0-beta5

```
PM> k ef migration add initial
'EntityFramework.Commands' does not contain a static 'Main' method suitable for an entry point
```

if i target ef 7.0.0-beta3 it working fine.

**Comment by ErikEJ** [comment]
Is it not dnxvm or something like that instead of k?

**Comment by davidfowl** [comment]
`dnx`

**Comment by wangkanai** [comment]
Have it change? 
I still see here http://stephenwalther.com/archive/2015/01/17/asp-net-5-and-angularjs-part-4-using-entity-framework-7

**Comment by divega** [comment]
Yes, names of command line tools and APIs have changed recently. Some of the command line tools changes are mentioned at https://github.com/aspnet/Home#getting-started.
