### ISSUE TITLE
Unable to suppress filter on unique index with `.HasFilter(null)` since EF Core 3

### ISSUE THREAD

**Issue by miniyou** [dotnet/efcore#20136]
A unique index where at least one column is nullable will by default get a filter like `[SomeColumn] IS NOT NULL`. With EF Core 2, this filter could be suppressed with `.HasFilter(null)` in the fluent definition, like so:

``` CSharp
x.Entity<CompanyExternalAuthToken>()
    .HasIndex(d => new { d.ServiceKey, d.ExternalId })
    .HasName("IX_ServiceKey_ExternalId")
    .IsUnique(true)
    .HasFilter(null);
```

However, with EF Core 3.1, the `HasFilter` call has no effect, the result is the same as if it had not been called at all. In other words, when creating a migration, EF Core will try to recreate all of those indexes to include the filter we're trying to suppress.

I found a workaround and verified that it works as expected:

``` CSharp
x.Entity<CompanyExternalAuthToken>()
    .HasIndex(d => new { d.ServiceKey, d.ExternalId })
    .HasName("IX_ServiceKey_ExternalId")
    .IsUnique(true)
    .Metadata.SetAnnotation(RelationalAnnotationNames.Filter, null);
```

It appears to me that this is caused by [this snippet](https://github.com/dotnet/efcore/blob/725adf77d3a08d99ce59787354d391176c3844b7/src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs#L89) – note the call to `SetOrRemoveAnnotation` rather than `SetAnnotation`:
``` CSharp
public static void SetFilter([NotNull] this IMutableIndex index, [CanBeNull] string value)
    => index.SetOrRemoveAnnotation(
        RelationalAnnotationNames.Filter,
        Check.NullButNotEmpty(value, nameof(value)));
```

I don't see any reason for this change, and it seems unintentional to me.

### Steps to reproduce

Create an entity with at least one nullable column, like

``` CSharp
public class MyEntity
{
    public string MyProperty { get; set; }
    // ...others omitted for brevity
}
```

In `OnModelCreating(…)`, define this index:

``` CSharp
x.Entity<MyEntity>()
    .HasIndex(d => new { d.MyProperty })
    .HasName("IX_MyProperty")
    .IsUnique(true)
    .HasFilter(null);
```

Result: the index gets a filter.

### Further technical details

EF Core version: `3.1.2` (upgrading from `2.2.4-servicing-10062`)
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `.NET Framework 4.7.2`
Operating system: `Windows 10`
IDE: `Visual Studio Enterprise 2019 16.4.3`

**Comment by shuegelm** [comment]
Got the same problem on MariaDB. I am using
```c#
            builder
                .HasIndex(email => new { email.GroupersonId, email.IsPrimary })
                .IsUnique()
                .HasFilter($"[{nameof(EmailEntity.IsPrimary)}] = 1");
```
Sadly the filter has no effect at all. Its just an normal index. So i am not able to insert multiple non primary email addresses.

**Comment by AndriySvyryd** [comment]
@shuegelm That's more likely to be an issue in the Pomelo provider

@lauxjpn cc

**Comment by shuegelm** [comment]
> @shuegelm That's more likely to be an issue in the Pomelo provider
> 
> @lauxjpn cc

U right. Already found the reported issue.

**Comment by lauxjpn** [comment]
> That's more likely to be an issue in the Pomelo provider

@AndriySvyryd @shuegelm I can't figure out where the start of this conversation is (maybe I am missing something).

> U right. Already found the reported issue.

@shuegelm Please drop a link, so I know which issue you are referring to. Thanks!

**Comment by shuegelm** [comment]
> > That's more likely to be an issue in the Pomelo provider
> 
> @AndriySvyryd @shuegelm I can't figure out where the start of this conversation is (maybe I am missing something).
> 
> > U right. Already found the reported issue.
> 
> @shuegelm Please drop a link, so I know which issue you are referring to. Thanks!

I deleted my original post because it was not the right place.

https://jira.mariadb.org/browse/MDEV-15140

**Comment by agrawalsaurabh21** [comment]
@miniyou : Thanks for the soln , it worked for me . I have dotnet core 3.1 , Oracle.EntityFramework.core and oracle 12.2 version .

But i have made some changes into your soln and that is 

.SetAnnotation(RelationalAnnotationNames.CheckConstraints, "TableName IN ('DerivedTableName')");

This soln is working with oracle as well as sql server.

**Comment by jinek** [comment]
This automatic filter thing is the story of how to miss an index in database and to get performance troubles.
