### ISSUE TITLE
Build models with conventions in MigrationsTestBase

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20157]

**Comment by ajcvickers** [comment]
@roji Check for issue for/coverage of round-tripping snapshot.

**Comment by roji** [comment]
Duplicate of  #11193?

**Comment by ajcvickers** [comment]
See also:
* Migrations: Test using snapshot #11193
* Remaining clean up for migration tests #19668

**Comment by roji** [comment]
MQ?

**Comment by roji** [comment]
This would add good coverage, but doesn't seem like a bug.
