### ISSUE TITLE
Query: improve logic around Contains(byte array) 

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#20155]
Currently we special case how he handle contains on byte arrays. This should be cleaned up - AllAnyContainsRewritingExpressionVisitor should be able to run after nav expansion, but currently some cases of entity equality require it to run before it.

**Comment by smitpatel** [comment]
Depends on #20164

**Comment by roji** [comment]
Just to keep in mind... In PostgreSQL `byte[]` can be mapped in two ways: either as a binary type (called `bytea`, this is the default mapping), or as an array of bytes (just like you can have arrays of ints, arrays of strings). Being able to map to array of bytes is actually important to some users - sometimes used for enums with underlying byte type. Tell me if you need/want more details.
