### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20166]
release/1.0 -> Tag 1.0.6 corresponds to last release we made. There are additional commits on the branch from infra team which we never released and should not be necessary.
release/1.1 -> Tag 1.1.6 aligns with last release, rest same as above.
release/2.0 -> Tag 2.0.3 aligns perfectly no additional commits.
release/2.2 -> Tag 2.2.6 aligns with release, Additional commits are merging release/2.1 to 2.2 to flow further. Last build did not pass.
release/3.0 -> Tag 3.0.3 aligns.

All above releases are EOL, please delete those branches. If we ever end up needing anything we have tags to recreate the branch anyway.

**Comment by ajcvickers** [comment]
@smitpatel to discuss with @Pilchie

**Comment by Pilchie** [comment]
I support @smitpatel's proposal.

**Comment by ajcvickers** [comment]
@bricelam Apparently, you have the permissions to do this.

**Comment by bricelam** [comment]
Deleted 1.0, 1.1 & 2.0.
We'll continue to merge from 2.1 to 2.2 to 3.0 to 3.1 to master.
Anything left to do?

**Comment by Pilchie** [comment]
2.2 and 3.0 are out of support - you could delete them and merge straight from 2.1-3.1.  I believe that is what `aspnetcore` is doing.

**Comment by ajcvickers** [comment]
@Pilchie Are you absolutely, 100% sure that we will never build 2.2 again? For any reason?

**Comment by Pilchie** [comment]
If there is a tag, a branch can be easily recreated on demand if that need arises.  However, if you wanted to defer doing this for a while, that would be fine too.

**Comment by ajcvickers** [comment]
@Pilchie The question is actually not about keeping the branch, but whether when we make a 2.1 fix it should flow through 2.2 in the normal way. If we stop doing that, then 2.2 gets out of sync and falls behind, which we generally try hard to avoid.

**Comment by bricelam** [comment]
Deleted 2.2 & 3.0.
