### ISSUE TITLE
Query: Rewrite Entity Equality

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20164]
The pattern of wrapping and unwrapping is just too leaky. Way too many expressions I encountered where it leaves behind internal states causing translation failures.
Either merge into nav rewrite since it has entity info or convert to a proper reducingEV pattern.

**Comment by maumar** [comment]
+1 for merge with nav rewrite

**Comment by roji** [comment]
I think there's value in leaving this as a separate visitor, just to keep nav rewrite from becoming a super huge single visitor that does everything... (that doesn't mean there isn't room for cleanup/improvement in EE, possibly even a rewrite). Just something to consider.

**Comment by AndriySvyryd** [comment]
We can keep the visitors separate in source code and combine them using a composite visitor.

**Comment by smitpatel** [comment]
Historically, we did order by entity to order by entity PK in translation phase. It is in EE right now, which can be moved again. The reason for EE happening before nav expansion was 2 fold
- entity.Principal == null can be replaced with entity.ForeignKey == null saving additional join. We currently don't do this as it had issues with query filter where we would give wrong results.
- et1.Owned == et2.owned should become et1 == et2, (same for collections), they would match only if principal is same entity instance. We do it for collection at present but not for owned entities.

In entity equality rewrite issue, we had various opinions about merging EE into navigation expansion. One more issue was about EE on a subquery with composite PK which has a contains based different translation.

Overall design I am proposing is	
- Nav expansion which already deals with navigations does task of pruning navigations which does not need to be expanded
- entity equality goes away from preprocessing.
- Translation pipeline based on whatever mapping converts entity equality best it can do on server side.
