### ISSUE TITLE
Upgrade from 2.2 to 3.1 EF - multiple select doesn't work anymore

### ISSUE THREAD

**Issue by moisoiu** [dotnet/efcore#20169]
Hello,

We face a strange issue after upgrade to 3.1. We can't do anymore multiple async call to get data from SQL.  Any idea what would be the cause ? Or a workaround (except to do await for each method) ?

### Steps to reproduce

Get data from 2 tables via Task and then do a Task.WhenAll (as below), in 2.2 everything works fine, in 3.1 

We are using AutoFac, as **InstancePerLifetimeScope** (Scoped), I've tried also as **InstancePerRequest** (Transient) but no success unfortunately 

Autofac Configuration

```
// EF context
builder
.Register(x =>
{
var contextOptionsBuilder = new DbContextOptionsBuilder<EfContext>()
	.UseSqlServer(_sqlConnectionString);

	return new EfContext(contextOptionsBuilder.Options);
})
.AsSelf()
.InstancePerLifetimeScope();
```

Repository methods

```
    public async Task Test()
        {

            var task1 = _context
               .Set<User.Domain.Entities.User>()
               .AsNoTracking()
               .Where(x => x.ActiveYN)
               .Where(x => x.UserId == 1)
               .SingleOrDefaultAsync();

            var task2 = _context
              .Set<WorkSpace>()
              .AsNoTracking()
              .Where(x => x.ActiveYN)
              .Where(x => new long[] { 1 }.Contains(x.WorkSpaceId))
              .ToListAsync();


            await Task.WhenAll(task1, task2);

            
        }

```

Exception:

``` 
A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913."
```

### Further technical details

EF Core version: 3.1.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by F0b0s** [comment]
As far as i know, it doesn't relate with ef core. Databases doesn't suport parallel requests(at least sql server doesn't support this). You can read it here https://github.com/dotnet/efcore/issues/12952

**Comment by moisoiu** [comment]
And I'm for to not support parallel requests, but for normal cases like Create Update Delete and Read in some cases (2 threads / tasks calls same Table) but if I'm doing a separate call, I don't understand why this shouldn't be allowed.

**Comment by F0b0s** [comment]
As far as I remember it's about database session(connection). You can issue only one command and has to wait until it's finished. You can't issue two select commands at the same time. It's a way this thing works.
So, i suppose your Task.WhenAll didn't works at 2.2 as well.

**Comment by SayusiAndo** [comment]
If I recall correctly I met this issue here in the last a few months, and the contenxt was something similar:

 - there is a Blazor components and when it is instantiated (drawed) it makes a call to the DB
 - this component is called from multiple times as it is a nested component
 - database calls start to throw exceptions you got

If I remember correctly, the root cause was that EF can't manage parallel calls or the same calls parallely. In the morning I tried to search for it, but I haven't found in a few minutes so I gave it up.

Hopefully, it helps. If not, sorry for the noise.

**Comment by moisoiu** [comment]
When I hear command I think of an operation as Create / Update / Delete ,and yes I agree that I have to wait until is finished. But when I'm discussing about queries, only Read comes through my mind, and if there isn't the same Read / Query on same Table (Which let's say it might occur some locks) it should work just fine. 

I've attached 2 archives, one with EF 3.1 (I even let it in Transient but no success) and one in 2.2, and in 2.2 it's **working fine**, but on the other hand on 3.1 it's **not**

[entityframework3-1.zip](https://github.com/dotnet/efcore/files/4287854/entityframework3-1.zip)

[entityframework2-2.zip](https://github.com/dotnet/efcore/files/4287873/entityframework2-2.zip)

Hope you have an idea on this or something. Cause it's quite strange with this upgrade of losing the async (I'm happy that I had Integration Tests huehuehue and was able to track this issue)

**Comment by smitpatel** [comment]
> in 2.2 it's working fine

Just to clarify, in 2.2, EF Core was serializing queries under the hood and running them one by one. In 3.1, you would have to await them individually yourself. So behaviorally nothing has changed.

**Comment by moisoiu** [comment]
So there isn't away to increase the performance of running multiple queries in "async" way with the same dbcontext? But if I would use multiple dbcontext it would work ?

**Comment by ajcvickers** [comment]
@moisoiu Correct. A single DbContext instance can only be used for one async operation at a time.
