### ISSUE TITLE
Consider wrapping SqlException with a custom exception providing more details

### ISSUE THREAD

**Issue by alexangas** [dotnet/efcore#2017]
Suggestion based on experiences using `ExecuteSqlCommand()` in EF6 where the actual SQL statement and its parameters would be extremely useful in troubleshooting production errors. Example of troubleshooting scenario under EF6:

> `System.Data.SqlClient.SqlException (0x80131904): The parameterized query '(@userId int,@securableEntityId nvarchar(4000),@roleId tinyint,@' expects the parameter '@securableEntityId', which was not supplied.`

This extra information could be provided through a custom exception with appropriate properties.

Going further this could apply to any SqlException throwing call that EF makes to SQL that would assist in troubleshooting.

I'd be interested to work on this if that helps. I examined the code to try and work out if something was happening in this space but wasn't clear.

Related to #1808.

**Comment by ajcvickers** [comment]
This would be both a breaking change and we don't think it would add significant value, so closing this for now, although we could reconsider with compelling feedback.
