### ISSUE TITLE
Why ReadItemAsync is not used to search an item by id and partition key?

### ISSUE THREAD

**Issue by alexeymarkov** [dotnet/efcore#20170]
When I use context.DbSet.Find(x => x.Id == id) EF Core Provider executes container.GetItemQueryStreamIterator which is slower and costs significant more RUs in comparison with container.ReadItemAsync with providing an id and a partition key.

There could be an optimization which analyses a query (CosmosSqlQuery)

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/17310
