### ISSUE TITLE
Improve correlated collection key matching

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20184]
In some cases we can look at outer to determine if inner should start a new group.

**Comment by smitpatel** [comment]
Now I need to remember what I was thinking.

**Comment by smitpatel** [comment]
@maumar - I assume you have some ideas about this?

**Comment by maumar** [comment]
blocking those scenarios, at least for tests marked with this bug

**Comment by ajcvickers** [comment]
@maumar @smitpatel This issue is marked closed_fixed in rc1, but the PR is still open. Is this planned for RC1?

**Comment by smitpatel** [comment]
I approved PR yesterday, @maumar will rebase and get it through approval for merge (hopefully by tomorrow morning)
