### ISSUE TITLE
Metadata: Bring back SqlServerDbFunctionConvention

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20182]
To set schema as dbo conventionally.

It was there in 2.2 release. It got removed at some point. Currently query injects dbo when printing.

**Comment by AndriySvyryd** [comment]
Depends on https://github.com/dotnet/efcore/issues/19806

**Comment by smitpatel** [comment]
Little more details? 😅

**Comment by AndriySvyryd** [comment]
@smitpatel Why do you need more details? Are you planning to poach this?

**Comment by smitpatel** [comment]
May be. I was thinking just a model finalized convention can populate this on SqlServer, without any side-effects or triggering other conventions.

**Comment by AndriySvyryd** [comment]
Ok, you could do it that way for now. But with #19806 or #9329 the value would be available during `OnModelBuilding`, which is preferable

**Comment by smitpatel** [comment]
Poached. (hopefully ok).

I went the route to bringing the convention back because this was in 5.0 but the other issues which would make further improvements are in backlog so I thought we want to go this route meanwhile.
