### ISSUE TITLE
SqlHierarchyId is not working with Sqlite in memory provider

### ISSUE THREAD

**Issue by darthkurak** [dotnet/efcore#20199]
Hi. I am not sure if this is a bug, or maybe something that is made by design.
However, in the end, outcome is that we have a problem of testing functionality around SqlHierarchyId with in memory provider.

Whenever we use Sqlite in memory provider with Entities which use SqlHierarchyId,  EnsureCreated method fails with following:

`The property 'UserGroup.Node' could not be mapped, because it is of type 'SqlHierarchyId' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

On the other hand, Ef in memory provider partially works. But with EF in memory we can't use, computed columns for example.

So, only option left, which I see, is testing on real database behind. 

Or maybe there are another options? Can't sqlite in memory provider support SqlHierarchyId? It supports so many things like transactions or computed columns, maybe it is possible to implement?
Why actually, there is no memory provider who support full sql server?

**Comment by ajcvickers** [comment]
@darthkurak [SqlHierarchyId](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.types.sqlhierarchyid?view=sql-smo-140.17283.0) is a type defined by SQL Server for use with SQL Server. It's not supported by any other database provider. (The in-memory provider will take an instance, store it, and give you it back, but is completely ignorant of what it means or is used for.)
