### ISSUE TITLE
Improve shadow FK cardinality mismatch exception message

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20194]
```C#
    e.OwnsMany(p => p.Articles, a =>
    {
        a.OwnsMany(p => p.Comments, c=>
        {
            c.WithOwner().HasForeignKey("RelatedArticlesId");
        });
    });
```

Currently throws:
> The property 'RelatedArticlesId' cannot be added to the type 'Blog.Articles.Comments#Comment' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.

Should throw something like:
> The foreign key {'RelatedArticlesId'} on the entity type 'Blog.Articles.Comments#Comment' has a different number of properties than the principal key {'ArticlesId', 'Id'}. Specify the same number of properties or call 'HasPrincipalKey' first to target an alternate key.

**Comment by ajcvickers** [comment]
@AndriySvyryd Poachable by @lajones?

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes

**Comment by ajcvickers** [comment]
In latest daily, this now throws:

> System.InvalidOperationException: The relationship from 'Comment' to 'Article.Comments' with foreign key properties {'RelatedArticlesId' : int} cannot target the primary key {'BlogId' : Guid, 'Id' : int} because it is not compatible. Configure a principal key or a set of foreign key properties with compatible types for this relationship.
