### ISSUE TITLE
Determine default for complete discriminator mapping

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20192]
Till now, in terms of default, we always assumed that mapping is not complete (i.e. there can be rows in database with discriminator values we don't know). 
This issue tracks if we want to change that default.

**Comment by ajcvickers** [comment]
@AndriySvyryd to bring to the design meeting.

**Comment by AndriySvyryd** [comment]
**Design decision:** We'll change the default and document this as a minor breaking change.
And make the exception that is thrown for an unknown discriminator value include a link to a doc page.
