### ISSUE TITLE
Internal code usage scenarios missed by the analyzer

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20206]
Identified scenarios:

- [x] Generic type parameter (e.g. `context.GetService<IInMemoryStoreCache>()`)
- [x] Type usage without instantiation (`IStateManager state = null`)
- [x] Typeof (`typeof(IInMemoryStoreCache)`)
- [x] private readonly field in private nested class
- [x] Implemented interface

**Comment by AndriySvyryd** [comment]
We shouldn't be using `GetService`

**Comment by smitpatel** [comment]
May be because generic type check is missed?

**Comment by ajcvickers** [comment]
Also doesn't seem to detect:
```C#
IStateManager state = null;
```
But does detect:
```C#
IStateManager state = new StateManager(null);
```

**Comment by ajcvickers** [comment]
Finding more cases like this. It seems that the analyzer doesn't detect any uses of internal types/members that don't actually involve invoking anything.

**Comment by roji** [comment]
@ajcvickers have converted this issue to a shopping list of currently undetected cases in the analyzer. Let's add more to it as we find them.

**Comment by smitpatel** [comment]
private readonly field in private nested class.

**Comment by roji** [comment]
@smitpatel can you provide a bit more detail on "private readonly field in private nested class", possibly a code fragment?

**Comment by smitpatel** [comment]
```
public class A
{
    private class B
    {
        private readonly InternalEntityEntry Entry;
    }
}
```
