### ISSUE TITLE
Unit testing with a generic repository

### ISSUE THREAD

**Issue by mmillican** [dotnet/efcore#20209]
I understand the general guidance is to not mock Entity Framework for unit testing, and instead use a repository or in-memory database. I've been trying to use a generic repository pattern and still running into a lot of issues around `IQueryable<T>` and `async`. I'm hoping someone can point me in the right direction.

Here's my generic repository interface:

```c#
public interface IRepository<TContext, TEntity> where TContext : IDbContext where TEntity : class, new()
{
    IQueryable<TEntity> Table { get; }
    IQueryable<TEntity> TableNoTracking { get; }

    Task<TEntity> GetByIdAsync(object id);

    Task CreateAsync(TEntity entity);
    Task UpdateAsync(TEntity entity);
    Task DeleteAsync(TEntity entity);
}
```

And a sample usage of that:

```c#
public class EntityAclService : IEntityAclService
{
    private readonly IRepository<IDbContext, EntityAclRecord> _permissionRepository;
    private readonly IUserRoleService _userRoleService;

    public EntityAclService(IRepository<IDbContext, EntityAclRecord> permissionRepository,
        IUserRoleService userRoleService)
    {
        _permissionRepository = permissionRepository;
        _userRoleService = userRoleService;
    }

    // redacted for brevity

    public async Task<bool> AuthorizeAsync<TEntity>(int siteId, TEntity entity, string permissionKey, Role role) where TEntity : ISupportsAcl
    {
        var entityPermissions = await GetPermissionsForEntityAsync(siteId, entity);
        var hasPermission = entityPermissions
            .Where(x => x.PermissionKey == permissionKey
                && x.RoleId == role.Id)
            .Any();

        return hasPermission;
    }
}

```

And finally a sample test using these:

```c#
[Test]
public async Task Authorize_ReturnsTrue_GivenValidRoleForEntity()
{
    // Arrange
    var testPermissions = new List<EntityAclRecord>
    {
        new EntityAclRecord
        {
            Id = 1,
            SiteId = 1,
            EntityType = "MyApp.Core.Entities.Pages",
            EntityId = 1,
            RoleId = 1,
            PermissionKey = "Page.Edit"
        }
    };

    var testRole = new Role
    {
        Id = 1,
        SiteId = 1,
        Name = "Admin",
        NormalizedName = "ADMIN"
    };

    var testPage = new Page
    {
        Id = 1,
        Title = "TestPage"
    };

    var mockPermissionRepo = new Mock<IRepository<IDbContext, EntityAclRecord>>();
    mockPermissionRepo.SetupGet(x => x.TableNoTracking)
        .Returns(testPermissions.AsQueryable());

    var mockUserRoleService = new Mock<IUserRoleService>();

    var permissionService = new EntityAclService(mockPermissionRepo.Object, mockUserRoleService.Object);

    // Act
    var result = await permissionService.AuthorizeAsync<Page>(1, testPage, "Page.Edit", testRole);
}
```

The error I get when running the tests are:

```
System.InvalidOperationException : The source IQueryable doesn't implement IAsyncEnumerable<MojoCms.Core.Entities.Security.EntityAclRecord>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.

```

**Specific questions**

1. Is it possible to use `IQueryable<T>` as properties and async methods against them while having them be testable? Everything I've found on the subject is using internal APIs and those have since changed (understandable since they are internal).
2. If I can't do this, do you have any suggestions how I can unit test my services which will likely all take a `IRepository` as a dependency? Ideally I'd like to not rely on changing internal implementations.

**Comment by SayusiAndo** [comment]
What I would investigate first is how much value (execution time, stability, easy to write tests, headache with mocks, team progress enablement, etc.) between this test using mocks and this test using either in memory db or SQLite. In one hand, if you have a lot of tests then sqlite can be a bottlenect in execution time, and will bring some problems to be solved with parallel execution. On the other hand, you don't have to struggle with mocks.

**Comment by smitpatel** [comment]
You cannot use Mock library to mock IQueryables being passed to EF Core. It would be a very elaborate process to write your custom query provider to mock IQueryable. If you want to mock things and not use any EF Core provider then make sure that you are mocking results of queries rather than just query roots being passed to EF queries. Else use an actual EF Core provider for testing.

**Comment by mmillican** [comment]
@smitpatel I think that's effectively what I'm trying to do here (mocking results from my Repository that my Services can use). Could you provide any samples of how you would do this?

**Comment by smitpatel** [comment]
@mmillican - There is a lot of missing code to effectively tell anything for me. But based on snippets, while you are mocking part of repository by giving list as queryable, other parts are still working on EF Core especially calling EF Core's async methods. You need to mock all the results which would come out of EF core to effectively test it without EF Core provider.

So `GetPermissionsForEntityAsync` also need to be mocked to give some results rather than calling into EF Core code.
