### ISSUE TITLE
Scaffold-DbContext - numeric columns in VIEW objects not created in DB Context

### ISSUE THREAD

**Issue by peterhamilton-cpx** [dotnet/efcore#20219]
When using Scaffold-DbContext to reverse-engineer VIEW objects from SQL Server, any columns in the selected VIEW objects of type "int" are not being created in the DB Context classes, while columns of other types (e.g. "string") are being generated.  

I have created a simple example of this below, and I can confirm that this behaviour occurs in "real" VIEW objects.  For example, we have reverse-engineered a view with +114 columns, and all columns of type "int" (67 in total) are missing from the generated DB Context class.

### Steps to reproduce
**Step 1- Create a view with some numeric and non-numeric columns, I tried both CAST with a numeric column in addition to an uncasted column:**
```
CREATE VIEW [dbo].[VIEW_With_Some_Numeric_Columns]
AS
SELECT 
  1 AS Item_ID
 ,1 AS SomeNumber
 ,CAST(1 AS int) AS SomeCastedNumber
 ,'Item' AS Item
```
**Step 2 - Reverse engineer the VIEW using Scaffold-DbContext**
`Scaffold-DbContext 'Data Source=(localdb)\ProjectsV13;Initial Catalog=MyTestDB' Microsoft.EntityFrameworkCore.SqlServer -Table VIEW_With_Some_Numeric_Columns -DataAnnotations -OutputDir Models -Force`

**Step 3 - Review the generated Model and DB Context classes**
All columns in the generated Model class for the reverse-engineered VIEW are present:
 
![image](https://user-images.githubusercontent.com/58074761/76162217-ef93ca80-6111-11ea-94ec-684c2cd5a14b.png)

However, only one column "Item" is generated in the Context.cs class:
![image](https://user-images.githubusercontent.com/58074761/76162243-2c5fc180-6112-11ea-9a35-ed7a303c8937.png)

All columns of type "int" are missing in the DB Context class.

### Further technical details
EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.5

**Comment by ErikEJ** [comment]
The DbContext class only refers to columns if the deviate from the built-in conventions, and none of the other int columns deviate.

**Comment by ErikEJ** [comment]
@ajcvickers Maybe there is a lack of documentation of conventions ? - it completely tripped up @peterhamilton-cpx  - I could only find something substantial on this third party site: https://www.entityframeworktutorial.net/efcore/conventions-in-ef-core.aspx

**Comment by peterhamilton-cpx** [comment]
@ErikEJ, @ajcvickers  - Thanks for your input Erik, and yes, I agree that I am completely tripped up, even after reviewing the article you mentioned.  :(

The example VIEW which I provided above doesn't reference any existing tables or relationships.  All the properties get generated in the Model class, and _some_ properties are generated in the Context class.  However, any "int" properties in the Model are not generated in the Context class.  If I change the data type within the VIEW for  "SomeNumber" and "SomeCastedNumber" to "varchar(50)", recreate the view, and reverse engineer again, these two columns are generated in the Model and Context classes.

**Comment by ErikEJ** [comment]
@peterhamilton-cpx Yes, that is how the conventions works, varchar(50) is no the standard mapping for string, it is nvarchar(MAX) (as described in the linked article!)

**Comment by ErikEJ** [comment]
Do you have any runtime errors or test failures caused by this, or do you juts not understand the concept of mapping conventions?

**Comment by peterhamilton-cpx** [comment]
No test failures.  I tested and it is working.  I think the issue is that all properties _were_ created in the Context.cs file in a previous version of EF Core such as:

`entity.Property(e => e.Status).HasColumnName("Status");`

This is **not** created when reverse engineering in EF Core 3.1.  I was contacted by a developer as this was creating issues in a front-end app (but that's a different issue altogether).  

As you previously indicated, I had a fundamental misunderstanding of what _needs_ to be in the *Context.cs class. The "int" columns in the source VIEW do not need to be generated in the *Context.cs class because they are just integer columns (nothing special).  

I thought that all properties would need to be there as they were previously.

My apologies for wasting your time, and I thank you so much for helping out.
