### ISSUE TITLE
Should test lowest supported OS versions

### ISSUE THREAD

**Issue by dougbu** [dotnet/efcore#20218]
Helix testing is currently limited to
- Windows.10.Amd64
- Ubuntu.1804.Amd64
- OSX.1014.Amd64

But, Ubuntu 16.04 and macOS 10.13 are both supported OS releases. Main concern is likely macOS 10.13 because we can no longer build on that OS and will instead build on macOS 10.14.

**Comment by ajcvickers** [comment]
Notes from team triage: we will leave our coverage as-is for now.
