### ISSUE TITLE
Microsoft.EntityFrameworkCore.Proxies is not compatible with Dotnet Core 3.1

### ISSUE THREAD

**Issue by CKKwan** [dotnet/efcore#20224]
**Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.EntityFrameworkCore.Proxies 3.1.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore.Proxies 3.1.2 does not support any target frameworks.**

It was working for the past few days, suddenly stopped working today.

After uninstall the nuget package, I can't get it to reinstall again. It will give the above error when I am trying to install

EF Core version: **3.1.2**
Database provider: **SqlServer Express**
Target framework: **.NET Core 3.1**
Operating system: **Win 10 x64**
IDE: **Visual Studio 2019 16.4.5**

**Comment by ajcvickers** [comment]
@CKKwan Please post your `csproj` file so we can take a look.

**Comment by CKKwan** [comment]
[csproj.zip](https://github.com/dotnet/efcore/files/4309603/csproj.zip)

@ajcvickers the csproj files are attached

**Comment by ajcvickers** [comment]
Use `Microsoft.Data.SqlClient` instead of `System.Data.SqlClient`. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#SqlClient

**Comment by CKKwan** [comment]
@ajcvickers Thanks for the suggestion, but I am still getting the same error.

Actually I only showed one error in the original post, but in actual fact I received 3 errors. I am not sure if the other two lines of error will help.

**Error	NU1202	Package Castle.Core 4.4.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Castle.Core 4.4.0 does not support any target frameworks.	CoreDB	c:\CoreDB\CoreDB.csproj	1**	

**Error	NU1202	Package Microsoft.EntityFrameworkCore.Proxies 3.1.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore.Proxies 3.1.2 does not support any target frameworks.	CoreDB	c:\CoreDB\CoreDB.csproj	1**	

**Error		Package restore failed. Rolling back package changes for 'CoreDB'.**

**Comment by CKKwan** [comment]
I can't find where is **Package Castle.Core 4.4.0** included.

The problem persist even after I reinstall or repair VS2019.

Strange enough, I have tested my code in another Desktop, and all are working fine. I have no problem including the proxies package.

**Comment by CKKwan** [comment]
I went to the extend to repair / uninstall / reinstall VS2019. And it doesn't help at all.

Finally solved my issued by:
1. Clear all the nuget packages cache.
2. delete all the bin / obj folders
3. restore all client side / nuget packages
