### ISSUE TITLE
Sqlite: add transaction savepoint API

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20228]
Sqlite supports the SQL Standard for savepoints: https://www.sqlite.org/lang_savepoint.html. SqlClient and Npgsql expose APIs for this their DbTransaction implementation, and https://github.com/dotnet/runtime/issues/33397 tracks adding the relevant APIs in System.Data.

**Comment by bricelam** [comment]
System.Data.SQLite leveraged savepoints to implement nested transactions at the ADO.NET layer. I like the proposed design better.

**Comment by ajcvickers** [comment]
@roji @bricelam What is this blocked on? Should it be in 5.0 if it is blocked?

**Comment by bricelam** [comment]
I think it was blocked on getting it into ADO.NET. I don't think it needs to be in 5.0.

**Comment by roji** [comment]
@ajcvickers this is simply waiting for the new methods to appear in a new version of the SDK (I think preview8). I know it's technically an enhancement, but I think we should just do it. It's trivial to do, there's virtually no risk (new APIs) and it would make sense to implement the new 5.0 API in 5.0...

**Comment by ajcvickers** [comment]
If it can go in this week, okay. Otherwise we'll discuss on Friday.

**Comment by smitpatel** [comment]
@roji - Can you verify milestone/labels?
