### ISSUE TITLE
SQLite provider does not validate connection string on Add-Migration but does on Remove-Migration

### ISSUE THREAD

**Issue by mqudsi** [dotnet/efcore#20223]
(This is half-bug half-feature-request territory.)

### Steps to reproduce

* Create a new ASP.NET Core project, install the EF core nuget package, the EF Core tools package, and the EF Core SQLite provider.
* Create a DbContext (details do not matter)
* Add the DbContext to the program, but with an invalid connection string:

```csharp
            services.AddDbContext<Database>(options =>
            {
                options.UseSqlite("test.db");
            });
```

At this point, you may run `Add-Migration InitialCreate` to create a migration. The creation will succeed, and a `Migrations` folder will be added to the project. 

If it is necessary to undo this migration - perhaps the developer realized their model was incorrect before even applying the migration itself - an attempt to call `Remove-Migration` at this point will fail, because `Remove-Migration` tests the DB to check if the migration being removed was applied to the database, and the connection to the database will necessarily fail because the connection string as written in the `Startup.cs` is incorrect:

> Format of the initialization string does not conform to specification starting at index 0.

At this point, the physical changes to the codebase (e.g. the presence of the `Migrations` folder and its newly generated contents) cannot be reverted without first setting a valid connection string. (Actually, I just realized `Remove-Migration -force` will also work)

I believe it's acceptable for `Add-Migration` to succeed even with an invalid connection string (as a developer may design the database model without having a database to apply it against, theoretically at any rate), but this particular combination of `Add-Migration` succeeding with an invalid connection string but `Remove-Migration` failing without a valid connection string is (while only somewhat pedantically in technical terms, in UX terms it I think it probably qualifies as) a bug.

Some possibilities/food-for-thought:

* Have `Add-Migration` validate the connection string and bail if it does not have the correct format (or take it further and require that the connection also be valid, if `Remove-Migration` stipulates the same)
* In `Remove-Migration`, handle the error caused by an invalid connection string by including a hint to the user that `-force` may be used to ignore this and continue,
* Record the connection string at the time of `Add-Migration` and if it has not changed upon calling `Remove-Migration` but is invalid (e.g. the case above), ignore the error and continue as if `-force` were applied.

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: N/A (but Windows 10 1909)
IDE: Visual Studio 2019 16.5.0 Preview 2.0

**Comment by ajcvickers** [comment]
@mqudsi Thanks for bringing this up. The current behavior is by-design. In particular, one of the reasons that `-force` exists is for this case. We discussed again, but we don't think there's enough value to justify making other changes here.

**Comment by FarazOnline** [comment]
Excellent!!!
Thanks for being the only one source I found to be helpful enough to revert me back to my project on WPF Core!!!
:-)
