### ISSUE TITLE
DI enhancement for multiple-provider apps

### ISSUE THREAD

**Issue by sei-jmattson** [dotnet/efcore#20239]
Does it make sense to register `DbContextOptions<TContextService>` in `AddDbContext<TContextService, TContextImplementation>()` when the types differ? ([source](https://github.com/dotnet/efcore/blob/c69926a8cdd05f4427e89ac8bac734e490b3d23a/src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs#L495))

One approach to supporting multiple database providers with EFCore is to have multiple DbContext's inherit from a base DbContext.

When using `.AddDbContext<TContextService, TContextImplemenation>()` only `DbContextOptions<TContextImplementation>` gets added to DI, so injecting the  TContextService anywhere fails because it can't find `DbContextOptions<TContextService>`.

My [minimal example](https://github.com/sei-jmattson/EfCoreMultipleProvidersExample) shows this works when manually registering `DbContextOptions<TContextService>`; can this be default behavior? Or should I be doing something differently?

Thanks!

**Comment by ajcvickers** [comment]
@sei-jmattson Use the provider-specific DbContext type for the generic of `DbContextOptions<>` and then use the non-generic constructor in the base class. For example:

```C#
public class ProjectDbContext : DbContext
{
    public ProjectDbContext(DbContextOptions options): base(options) {}
    public DbSet<Datum> Data { get; set; }

}

public class ProjectDbContextSqlServer: ProjectDbContext
{
    public ProjectDbContextSqlServer(DbContextOptions<ProjectDbContextSqlServer> options): base(options){}
}

public class ProjectDbContextPostgreSQL: ProjectDbContext
{
    public ProjectDbContextPostgreSQL(DbContextOptions<ProjectDbContextPostgreSQL> options): base(options){}
}
```

**Comment by sei-jmattson** [comment]
Sweet, thanks!  That fixes me up.
