### ISSUE TITLE
Reset operation does not supply the items removed.

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#20235]
Instead of using ObservableHashSet, I created my own collection type for a navigation. I raised the INotifyCollectionChanged Reset operation and got an InvalidOperationException:  ''ObservableCollection<T>.Clear()' is not supported because it uses the 'INotifyCollectionChanged' 'Reset' operation, which does not supply the items removed. Either use multiple calls to 'Remove' or use a notifying collection that supports 'Clear', such as 'Microsoft.EntityFrameworkCore.ChangeTracking.ObservableHashSet<T>'.'

Any idea what collection it is referring to? My collection is not based on ObservableCollection. Note, I am using notification change tracking. 

The debugger says it occurred in InternalEntityEntry.HandleINotifyCollectionChanged.

The principal entity is in the Unchanged state, as is the dependent entity.

**Comment by sjb-sjb** [comment]
Looked at the code and it seems this is a simple case of just having a misleading message. The message should be more generic, like, "NotifyCollectionChangedAction.Reset is not supported on navigation collections, because it does not contain sufficient information about the change."

Would be nice if this were supported but not at all critical to me. I should be able to find a way around it.

**Comment by ajcvickers** [comment]
Notes from team triage: the value of updating the exception message doesn't seem high here.
