### ISSUE TITLE
Navigation property combined with backing field leads to errors OnModelCreating

### ISSUE THREAD

**Issue by APIWT** [dotnet/efcore#20238]
Take the following entities:
```C#
public sealed class Employee
{
    private Supervisor supervisor;

    public long Id { get; set; }

    public long? SupervisorId { get; set; }

    public Supervisor Supervisor
    {
        get => this.Department?.Supervisor ?? this.supervisor;
        set => this.supervisor = value;
    }

    public long? DepartmentId { get; set; }

    public Department Department { get; set; }
}

public sealed class Department
{
	public long Id { get; set; }
	
    public long? SupervisorId { get; set; }

    public Supervisor Supervisor { get; set;}
}
```

And the following DB context:
```C#
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions options)
        : base(options)
    {
    }

    public DbSet<Employee> Employee { get; set; }
    public DbSet<Supervisor> Supervisor { get; set; }
    public DbSet<Department> Department { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Employee>()
            .Property(e => e.Supervisor)
            .HasField("supervisor")
            .UsePropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

When running the update database command:
```
dotnet tool run dotnet-ef database update
```

The following error is generated:
```
The property 'Employee.Supervisor' is of type 'Supervisor' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

How do I combine both the backing field concept and the navigation property concept?

### Further technical details

EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)

**Comment by APIWT** [comment]
Just in-case this is not a bug, and I am doing something wrong, I have created a Stackoverflow post for additional feedback: https://stackoverflow.com/questions/60619040/in-entityframework-core-is-it-possible-to-use-a-navigation-property-combined-wi

**Comment by ajcvickers** [comment]
@APIWT The answer to this depends on whether or not `Supervisor` is intended to be an entity type or not. If it is, then the references to it are "navigation properties" which are not configured using the `Property` API. See #6674 for how to configure the backing field.

If it's not an entity type, then use a [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) to map it to the database.

**Comment by APIWT** [comment]
Hey @ajcvickers. `Supervisor` is intended to be an entity type. I'll check out your link. Thanks!

**Comment by APIWT** [comment]
I'm going to close this issue, but I would recommend pointing out this information formally in the documentation. Thank you!
