### ISSUE TITLE
Why is string query translated into instr() in SQLite

### ISSUE THREAD

**Issue by simpleway2016** [dotnet/efcore#20248]
I found that :
db.MyTable.Where(m=> m.Name.Contains("abc")).ToArray()  will translate to:
select * from MyTable where instr( Name , 'abc' ) > 0
and this sql string can not ignore case
so if i try:
 db.MyTable.Where(m=> m.Name.Contains("ABC")).ToArray() , i will get nothing

I suggest that this query  should be translated ：
select * from MyTable where Name like '%abc%' , so if my database allow , i can ignore case

**Comment by smitpatel** [comment]
In C# `Console.WriteLine("ABCD".Contains("abc"));` returns false. So Contains match is case sensitive in C#. If you use C# Contains method then EF Core will translate it to something which will bring back results which matches result.

If you want to use Like in your SQL then considering using [EF.Functions.Like](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctionsextensions.like?view=efcore-3.1#Microsoft_EntityFrameworkCore_DbFunctionsExtensions_Like_Microsoft_EntityFrameworkCore_DbFunctions_System_String_System_String_) in the query to generate desired SQL.
