### ISSUE TITLE
SQL Server Native Client 11.0 connected ODBC using Entity framework core problem happens

### ISSUE THREAD

**Issue by ChristalVins** [dotnet/efcore#20259]
Hi Team,

I am working ASP.Net core 3.1 and connected with  "SQL Server Native Client 11.0" using ODBC connection. Using this connection some error displaying. can you please help on this.

**Connection string:**

"Connection": "Driver={SQL Server Native Client 11.0};server=1.1.1.1;trusted_connection=Yes;app=Microsoft® Visual Studio®;wsid=PPKID;database=master"

var connectionString = Configuration.GetConnectionString("Connection");
            var connection = new OdbcConnection(connectionString);
            services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connection));

![image](https://user-images.githubusercontent.com/14306827/76493588-f8a9d200-6458-11ea-9665-2b130fa8e29b.png)

![image](https://user-images.githubusercontent.com/14306827/76493646-1e36db80-6459-11ea-8031-aa2d5a5c45a0.png)

Please help this issues.

**Comment by ajcvickers** [comment]
@ChristalVins The EF Core SQL Server provider only supports use of [Microsoft.Data,SqlClient](https://github.com/dotnet/SqlClient) at the ADO.NET level. It would be interesting to understand your motivation for using something different.
