### ISSUE TITLE
DCProj File presence breaks Entity Framework

### ISSUE THREAD

**Issue by computamike** [dotnet/efcore#20256]
Adding Orchestration to a project in Visual Studio Community 2019 prevents Entity Framework CLI from executing.

### Steps to reproduce
1. Create an ASP.NET MVC Project (with Docker Linux container support)
1. Access Package Manager Console
1. Execute ```dotnet ef```
1. Entity Framework "unicorn" screen is presented.
![image](https://user-images.githubusercontent.com/464876/76424169-cab48700-639f-11ea-9cfa-711acc5ac391.png)
1. Right click project, Add, Container Orchestrator Support
1. Select `Docker Compose`
1. Select `Linux` for  Docker Support Options, Target OS
1. VS has now added a dcproj file to the project.
1. Access Package Manager Console
1. Execute ```dotnet ef```
1. Entity Framework error screen is presented.
![image](https://user-images.githubusercontent.com/464876/76424483-37c81c80-63a0-11ea-8c7b-9e4fdddf256d.png)

Here is a simplified project with 2 commits.
https://github.com/computamike/EntityFrameworkOrchestration

### Further technical details

EF Core version: Entity Framework Core .NET Command-line Tools 3.1.2
Database provider: N/A
Target framework: .NET Core 3.1
Operating system: Windows 10 v 1809 (OS Build 17763.1039)
IDE: Visual Studio 2019 Community

**Comment by computamike** [comment]
I believe the issue is related to this line : 
https://github.com/dotnet/efcore/blob/2c341ee6cb9721fdaedbe3cb3b302c8b7a3fe008/src/dotnet-ef/RootCommand.cs#L271

The method ResolveProjects scans the directory for `*.*proj` files, excluding `.xproj` files.  

I believe we should also be excluding dcproj files.  Alternatively it might be better to whitelist a set of project files that can be used

**Comment by computamike** [comment]
I've tried passing Project file in, and it fails to work.  I've forked the project and I have written a fix for this, but was unable to test it.

As a test, I ran the unit tests - threw an exception from `ResolveProjects` - my thoughts were that this would reveal if the code is covered by a unit test - which it doesn't seem to be,

Can someone suggest how this code can be tested?

**Comment by bricelam** [comment]
Something very strange is going on here. `dotnet ef` without a sub-command shouldn't ever look for a project... I think that error is coming from dotnet.exe, not dotnet-ef.dll.

**Comment by bricelam** [comment]
Also, EF's message for this situation would read as follows:

> More than one project was found in the current working directory. Use the --project option.

**Comment by bricelam** [comment]
Does `--verbose` give any additional information?

**Comment by computamike** [comment]
i'll check that out for you

**Comment by computamike** [comment]
Running ```dotnet ef --verbose``` returns the same error as reported.

**Comment by computamike** [comment]
I had a quick look at the DotNet cli repo and found this in the localizable strings section - which looks suspiciously like the error message presented.

https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf#L74

So - this might be the same bug in the CLI app, rather than EF ??? But if that's the case and the CLI is used for other stuff besides EF, wouldn't we be seeing this error in other applications?

**Comment by computamike** [comment]
yeah - I had a quick look and it's there in the Dotnet CLI - exactly the issue that I thought was being checked in EF - 

https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L265

So DotNet cli is checking a directory for any *.*proj files - and picks up DCProj and csproj, and throws an error based on that.

**Comment by computamike** [comment]
Just going to see if I can move this issue to the DotNet CLI repository

**Comment by computamike** [comment]
I don't have permission to move this to the DotNetCli repo.  I'll create an issue there.  Sorry for the inconvenience.

**Comment by computamike** [comment]
Going to suggest that this issue be closed - it seems that this is an issue with DotNetCli - but based on what I can see historically I'm not confident that this would be fixed - there was an existing bug that had been closed, and I believe the upshot was that it was expected behavior.
