### ISSUE TITLE
Restore Methods for Dynamic Table / DBSet Collections

### ISSUE THREAD

**Issue by GaryFurash** [dotnet/efcore#20255]
Any case where the code target might work for different entities in the framework (e.g., a Validation that needs to work generically with fields other than the passed field and interact with the context).

Something like db.GetSet([setname])

**Comment by ajcvickers** [comment]
@GaryFurash It's not clear exactly what you are asking for. Are you looking to use dynamic types that are not part of the EF model? Or are you looking to access mapped types through a non-generic API?

**Comment by GaryFurash** [comment]
sorry I meant being able to do something like
context.DbSet(variable with entity name).more linq statments

**Comment by ajcvickers** [comment]
@GaryFurash The problem with this is that LINQ is an inherently generic API. Even if you could get a non-generic `IQueryable`, there's very little that can be done with it without using generic methods.
