### ISSUE TITLE
Group by with aggrigates fails even though documentation claims it should work

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/efcore#20266]
The documentation on EF Core 3.1 says that all group bys that are not based on agrigates will fail but aggregates will succeed.

Here's an example where that's false:

```
from e in Context.Entitlements
						  join iie in Context.InvoiceInventoryEntitlements on e.Id equals iie.EntitlementId
						  join ii in Context.InvoiceInventory on iie.InvoiceInventoryId equals ii.Id
						  join i in Context.Inventory on ii.InventoryId equals i.Id
						  join iItem in Context.InventoryItems on i.Id equals iItem.InventoryId

						  group new { ii.Units, ii.Price, e.CancelledOn, e.EndsOn, e.StartsOn, e.Active } by new { iItem.RecurringPeriod, iItem.Type, i.SKU, i.Name } into g

						  select new ChurnRateDto
						  {
							  RecurringPeriod = g.Key.RecurringPeriod,
							  InventoryType = g.Key.Type,
							  SKU = g.Key.SKU,
							  Inventory = g.Key.Name,
							  CurrentValue = g.Where(e => e.StartsOn <= dtAsOf &&
											(e.EndsOn == null || e.EndsOn >= dtAsOf) &&
											(e.CancelledOn == null || e.CancelledOn >= dtAsOf) &&
											e.Active).Sum(r => (decimal?)r.Price * r.Units) ?? 0M,
							  CurrentCount = g.Where(e => e.StartsOn <= dtAsOf &&
											(e.EndsOn == null || e.EndsOn >= dtAsOf) &&
											(e.CancelledOn == null || e.CancelledOn >= dtAsOf) &&
											e.Active).Count(),
							  PreviousValue = g.Where(e => e.StartsOn <= dtPreviousAsOf &&
											(e.EndsOn == null || e.EndsOn >= dtPreviousAsOf) &&
											(e.CancelledOn == null || e.CancelledOn >= dtPreviousAsOf) &&
											e.Active).Sum(r => (decimal?)r.Price * r.Units) ?? 0M,
							  PreviousCount = g.Where(e => e.StartsOn <= dtPreviousAsOf &&
											(e.EndsOn == null || e.EndsOn >= dtPreviousAsOf) &&
											(e.CancelledOn == null || e.CancelledOn >= dtPreviousAsOf) &&
											e.Active).Count(),
						  }
```

This query is trivially converted to T-SQL as a simple group by of sums yet fails. (the precise schema is irrelevant. It's a few group fields, and then 2 sums based on where clauses and 2 counts based on the same where clauses.)

**Comment by ajcvickers** [comment]
@JohnGalt1717 As with previous issues (for example, #19753, #20189) there isn't enough information here for us to be able to reproduce the issue without guessing too many things around model configuration, etc. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by JohnGalt1717** [comment]
As with everyone else on the planet, I'm busy keeping the lights on. Where's the small sample project template from the EF Core group that allows this to be done quickly and easily that should have obviously been created by now since you require this from everyone?

**Comment by ajcvickers** [comment]
@JohnGalt1717 Here you go:

```C#
public static class ThreeOneApp
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            // Create and save entities to reproduce the issue here. 

            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            // Execute the problematic query here.
        }
    }
}

public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole()); //.SetMinimumLevel(LogLevel.Debug));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Configure your model here.
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(Your.SqlServerConnectionString);
}
```
(We also have https://github.com/dotnet/EntityFramework.Docs/issues/2137 for doing this in a more uniform way.)

**Comment by JohnGalt1717** [comment]
The link doesn't seem to have a download other than to a 3rd party....

**Comment by ajcvickers** [comment]
@JohnGalt1717 Copy and paste the code above into a console application. That's all you need.

**Comment by JohnGalt1717** [comment]
What I would expect is a complete project, with a complete data model that exemplifies all of the supported use cases of EF Core and instructions in said project on where to find each for test purposes and then a test project or instructions in program.cs of a console app that allows adding whatever queries you need to show a failure.

**Comment by ajcvickers** [comment]
@JohnGalt1717 We're not going to do that. Does that mean you won't be able to provide us with a repro?

**Comment by JohnGalt1717** [comment]
@ajcvickers I'll translate "We have no intention of providing the tools to respect our customers and save them time reporting the endless bugs in our code because we're only interested in fixing things that are spoon fed to us and are more than happy to put our fingers in our ears and claim that our product is great."

If you were actually an open source project that wasn't actively funded by one of the world's largest companies who makes 6 figures off of me, I would expect that I might have to do this. But ironically those projects don't treat people using their code like you guys do so I have almost never had to put the kind of effort into reporting bugs that you demand.

No, I'm not going to waste my time helping you when you are doing absolutely NOTHING to help me with your product that I pay $200,000 a year directly and indirectly for.

Really hope your new boss sets this team straight soon. In the mean time, feel free to ignore reality and close my tickets instead of following basic instructions.
