### ISSUE TITLE
OnModelCreating instead of OnConfiguring

### ISSUE THREAD

**Issue by GeroIwan** [dotnet/efcore#20269]
In the first paragraph: The method relevant for the model is DbContext.OnModelCreating(ModelBuilder) instead of DbContext.OnConfiguring(DbContextOptionsBuilder), isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0b7495a-7d8b-7f77-9ac2-1d491e866274
* Version Independent ID: f32cf4d0-18ae-4b24-2c12-c17762593af0
* Content: [IModel Interface (Microsoft.EntityFrameworkCore.Metadata)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.imodel?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata/IModel.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata/IModel.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Also check for other usages--see #20270

**Comment by GeroIwan** [comment]
@AndriySvyryd I cannot see any changes within the first paragraph of the IMutableModel and IModel _documentation_. Are they really fixed?

**Comment by AndriySvyryd** [comment]
Yes, it takes a while for the docs to be generated and published
