### ISSUE TITLE
Question:  Does the ChangeTracker use WeekReference ?

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#20260]
I working on project that has  feature : import data from excel file .
when I update / add the  entity I have question in follow situation

```C#
foreach(var row in excelrows)
{
    List<Data> queriedData = Db.Set<Data>().AsTracked().Where(..... )  .ToList();  
    if(queriedData.Count > 0)
    {
        // changed

        queriedData.Foreach(x=>{   ....  update the entity   });
    }
    else
    {
         Db.Add(new Data());
    }
}

Db.SaveChanges() //  outside loop
```

I wonder that will the  data in `queriedData`  be GCed  because it is in the loop ?

**Comment by ajcvickers** [comment]
@John0King `ToList` returns a normal `List<T>` which holds references to every item. None of the items will be GC'ed before the list itself is, even assuming no other references.
