### ISSUE TITLE
OnModelCreating instead of OnConfiguring

### ISSUE THREAD

**Issue by GeroIwan** [dotnet/efcore#20270]
In the first paragraph: The method relevant for the model is DbContext.OnModelCreating(ModelBuilder) instead of DbContext.OnConfiguring(DbContextOptionsBuilder), isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c026ebcb-2f29-3905-b4cf-251c8c8102f4
* Version Independent ID: 3e310dba-00fd-bca8-ee0d-bb35d4bf01eb
* Content: [IMutableModel Interface (Microsoft.EntityFrameworkCore.Metadata)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.imutablemodel?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata/IMutableModel.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata/IMutableModel.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Tracked by #20269
