### ISSUE TITLE
Question/Feature: Adding google.protobuf.Timestamp to an EF Core DB.

### ISSUE THREAD

**Issue by JeepNL** [dotnet/efcore#20283]
I opened an issue (https://github.com/grpc/grpc-dotnet/issues/817) about adding a `google.protobuf.Timestamp` field (from a .proto file) to an EF Core DB. (Blazor WebAssembly Project, pls see issue [grpc-dotnet#817 ](https://github.com/grpc/grpc-dotnet/issues/817) for more info )

When I tried to do that I got this error:  

"_The entity type 'Timestamp' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'_"

The answer I got from James Newton-King is: 

> Timestamp is designed to be serialized to and deserialized from Protobuf. It isn't intended to be saved to a database with EF.

Is there a way to add a record with a `google.protobuf.Timestamp` field directly to an EF DB?

**Comment by AndriySvyryd** [comment]
You'd need to use a [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)

**Comment by JeepNL** [comment]
@AndriySvyryd Yes, thank you!
