### ISSUE TITLE
EF Core 3.1 migrationBuilder.RenameColumn generate a wrong sql for mysql5.7

### ISSUE THREAD

**Issue by byebyebt** [dotnet/efcore#20287]
migrationBuilder.RenameColumn generate a sql “alter table XXX rename column YYY to ZZZ” that can't work in mysql 5.7

### Steps to reproduce

I'm working on mysql5.7.  
When I rename a column in model , and add migration to context, efcore will create two operation：DropColumn and AddColumn. that's not my expectation. 
So I delete those two operations and add a RenameColumn Operation, but that will generate a sql like “alter table XXX rename column YYY to ZZZ” that can't pass in mysql 5.7("1064 - You have an error in your SQL syntax").
So I have to use migrationBuilder.Sql to exec "alter table XXX change YYY ZZZ  datatype" myself.

### Further technical details

EF Core version: 3.1.0
Database provider: Pomelo.EntityFrameworkCore.MySql 3.1.0
Target framework: .NET Core 3.1
Operating system: win10
IDE: Visual Studio 2019 16.4.6

**Comment by ErikEJ** [comment]
Sound like you are creating SQL Server migrations against MySQL, or there is a bug in the MySQL provider.

**Comment by byebyebt** [comment]
> Sound like you are creating SQL Server migrations against MySQL, or there is a bug in the MySQL provider.

Thanks for your help.  since I have add many Migrations on mysql5.7, such as create table, including create autoincrement id, so it sames could not be a db type error, and if it's a bug of provider, how can I test and cofirm that? maybe switch to an other provider to compare it?

**Comment by ajcvickers** [comment]
@byebyebt https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql is the correct place to follow up on the provider issue.

**Comment by byebyebt** [comment]
@ErikEJ @ajcvickers Thanks a lot for your help!

**Comment by byebyebt** [comment]
This problem is couse by version missing in UsMySql method call,  that will result in wrong version infering in the provider.
