### ISSUE TITLE
OnModelCreating is always called when app is starting

### ISSUE THREAD

**Issue by ibasin** [dotnet/efcore#20295]
According to this tutorial https://www.learnentityframeworkcore.com/migrations/seeding we are supposed to seed data at the end of OnModelCreating method override. I do that and it works well.

However, I noticed that OnModelCreating is called every time I start the application and my SeedData method is always called. When the database schema did not change, the data also does not change but the SeedData method at the end of the OnModelCreating method is still called nonetheless. My SeedData is an expensive method that loads a bunch of data from CSV files and takes 5-7 seconds. Running it every time I start the app is expensive especially during debugging.

Is OnModelCreating supposed to run every time? Is there a way to differentiate times when seeding data is actually needed?

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.1.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.6

**Comment by AndriySvyryd** [comment]
See [Data Seeding docs](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
> In EF Core, seeding data can be associated with an entity type as part of the model configuration. Then EF Core migrations can automatically compute what insert, update or delete operations need to be applied when upgrading the database to a new version of the model.

You should only use `HasData` if you want migrations to manage applying changes to it, otherwise just add it to the database using `SaveChanges` when needed.

**Comment by AndriySvyryd** [comment]
In the future this could be mitigated by https://github.com/dotnet/efcore/issues/1906, compiling the data into the model, but that might increase the compile time instead.
