### ISSUE TITLE
CommandExecuted and CommandError diagnostics source events can be raised for single query in EF starting with 3.0

### ISSUE THREAD

**Issue by stukselbax** [dotnet/efcore#20296]
After upgrade from efcore 2.2.8 to 3.1.2 we started observe strange behavior in opentracing system we used ([jaeger](https://github.com/jaegertracing/jaeger-client-csharp) with [opentracing-contrib\csharp-netcore](https://github.com/opentracing-contrib/csharp-netcore)). 

```log
Span has already been finished; will not be reported again. Operation: Action MyController/MyAction Trace Id: dfaebcab772352af2ff88bbad09b5646 Span Id: 2a25748f4de61b06
```

It arises when efcore executes query and http request is aborted by the client (cancellationToken passed in triggers `TaskCancelledException` inside `RelationalCommand` **after** `CommandExecuted` event was broadcasted).

This problem states that someone has tried to finish "Tracer Span" twice. This was the [opentracing-contrib\csharp-netcore](https://github.com/opentracing-contrib/csharp-netcore) library code that did that, but it did that because it [expect behavior](https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/EntityFrameworkCore/EntityFrameworkCoreDiagnostics.cs#L61-L63) like in [efcore 2.x.x](https://github.com/dotnet/efcore/blob/v2.2.8/src/EFCore.Relational/Storage/Internal/RelationalCommand.cs#L305-L328):

```c#
                case "Microsoft.EntityFrameworkCore.Database.Command.CommandError":
                    {
                        CommandErrorEventData args = (CommandErrorEventData)untypedArg;

                        // The "CommandExecuted" event is NOT called in case of an exception,
                        // so we have to dispose the scope here as well!
                        DisposeActiveScope(isScopeRequired: true, exception: args.Exception);
                    }
```

It appears that in [efcore 3.1.2](https://github.com/dotnet/efcore/blob/v3.1.2/src/EFCore.Relational/Storage/RelationalCommand.cs#L506-L548) we can get both  `CommandExecuted` and `CommandError` events for single query, and this causes incorrect behavior in opentracing system we use. This behavior looks strange because from one point of view we have `CommandExecuted`, which states [A database command has been executed.](https://github.com/dotnet/efcore/blob/e1572b5fbc6d4083cc356b0052b0749e06cc97ca/src/EFCore.Relational/Diagnostics/RelationalEventId.cs#L196), but after that, we have `CommandError`, which state: [An error occurred while a database command *was executing.*](https://github.com/dotnet/efcore/blob/e1572b5fbc6d4083cc356b0052b0749e06cc97ca/src/EFCore.Relational/Diagnostics/RelationalEventId.cs#L209)

<details><summary>RelationalCommand.cs - problematic place</summary>
<p>

```c#
                if (logger != null)
                {
                    reader = await logger.CommandReaderExecutedAsync(
                        connection,
                        command,
                        context,
                        commandId,
                        connection.ConnectionId,
                        reader,
                        startTime,
                        stopwatch.Elapsed,
                        cancellationToken);
                }

                if (readerColumns != null)
                {
                    // We have got TaskCancelledException here, because of cancellationToken was passed.
                    reader = await new BufferedDataReader(reader).InitializeAsync(readerColumns, cancellationToken); 
                }

                var result = new RelationalDataReader(
                    connection,
                    command,
                    reader,
                    commandId,
                    logger);

                readerOpen = true;

                return result;
            }
            catch (Exception exception)
            {
                if (logger != null)
                {
                    await logger.CommandErrorAsync(
                        connection,
                        command,
                        context,
                        DbCommandMethod.ExecuteReader,
                        commandId,
                        connection.ConnectionId,
                        exception,
                        startTime,
                        stopwatch.Elapsed,
                        cancellationToken);
                }
```

</p>
</details>

Is it possible to change the place where `CommandExecuted` event is raised in order to preserve behavior like in [efcore 2.x.x](https://github.com/dotnet/efcore/blob/v2.2.8/src/EFCore.Relational/Storage/Internal/RelationalCommand.cs#L305-L328)? For example:

```c#
                if (readerColumns != null)
                {
                    reader = await new BufferedDataReader(reader).InitializeAsync(readerColumns, cancellationToken); 
                }

                var result = new RelationalDataReader(
                    connection,
                    command,
                    reader,
                    commandId,
                    logger);

                if (logger != null)
                {
                    reader = await logger.CommandReaderExecutedAsync(
                        connection,
                        command,
                        context,
                        commandId,
                        connection.ConnectionId,
                        reader,
                        startTime,
                        stopwatch.Elapsed,
                        cancellationToken);
                }

                readerOpen = true;

                return result;
            }
            catch (Exception exception)
            {
                if (logger != null)
                {
                    await logger.CommandErrorAsync(
                        connection,
                        command,
                        context,
                        DbCommandMethod.ExecuteReader,
                        commandId,
                        connection.ConnectionId,
                        exception,
                        startTime,
                        stopwatch.Elapsed,
                        cancellationToken);
                }
```

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.5

**Comment by stukselbax** [comment]
@ajcvickers can you please consider this for patch in 3.1?

**Comment by ajcvickers** [comment]
@stukselbax I'm not sure this [meets the bar for a patch release](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning). I agree that EF Core sure not generate both events, but that in of itself doesn't seem too serious.
