### ISSUE TITLE
Query: Remove EF.Functions.Like from InMemory provider

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20293]
InMemory does not support it. The implementation differs on database provider used. There is no correct InMemory behavior. We should remove it and move the method to relational layer with client eval throw.

**Comment by ajcvickers** [comment]
@smitpatel Does it currently work when used with the in-memory provider?

**Comment by ajcvickers** [comment]
Specific case of #20294 where we need to preserve the in-memory behavior.
