### ISSUE TITLE
PartitionKey support with Cosmos EFCore

### ISSUE THREAD

**Issue by balukantu** [dotnet/efcore#20307]
Hi Team,

I am working on an Azure Cosmos Db and planning to integrate EFCore. I have gone through the documentation and identified the point **Entity types with partition keys don't work correctly in some scenarios**.

So Can't we work efficiently with partition keys in EFCore? or As it is mentioned, can you list out the scenarios where it will not work?

Below are a few scenarios, where we use the partition key.

1.  Pass partition key when creating, updating, deleting or retrieving a record. [Link](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#partition-keys)
2. Pass partition key when executing a LINQ based on the partition key. #17320

**Comment by AndriySvyryd** [comment]
I've addressed your questions in https://github.com/dotnet/EntityFramework.Docs/issues/2184
