### ISSUE TITLE
k ef remove to current migration (and squash migrations)

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#2031]
right now if I have 25 migrations and I do a 

```
k ef migration apply 0
```

then I have to execute

```
k ef migration remove
```

25 times to get the migrations clean. 
I know this is not a very real scenario, but I was thinking if a remove to current would be a good idea

```
k ef migration remove notapplied
```

sorry if there is something to do this already.

**Comment by Bartmax** [comment]
I use this because while development I go and create as many migrations I need as soon as I need them (domain driven database design :D hehe) and when I feel like I'm done, I go back all the migrations and add a fresh one (aka merge all migrations into one).

**Comment by bricelam** [comment]
We often talk about this as the *Squash Migrations* command, I don't think we have an issue for it. If you're removing *all* migrations, you can just delete the *.cs files for the migrations and model snapshot after running `Apply-Migration 0`.

**Comment by bricelam** [comment]
If we implement #1298, you would be able to delete the migration files and the snapshot for the ones you want to remove. The snapshot would then be re-generated on the next add.

**Comment by Bartmax** [comment]
sounds good. thank you @bricelam

**Comment by rowanmiller** [comment]
**Triage** Added an issue to track the squash scenario https://github.com/aspnet/EntityFramework/issues/2174. Think we have everything covered now.
