### ISSUE TITLE
Detect SqlServer features automagically rather than using env vars

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20318]
@bricelam wrote 
Can we detect sequences, memory-optimized, hidden columns, and online index creation?

**Comment by ErikEJ** [comment]
Assuming you only support SQL Server 2012 or later, sequences are always supported.

Memory optimized: https://github.com/dotnet/efcore/blob/master/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L1111 

Hidden columns: https://github.com/dotnet/efcore/blob/master/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L1106

Online index creation: EngineEdition IN (3,5,8)

**Comment by AndriySvyryd** [comment]
@ErikEJ That only indicates whether the server support the syntax, the in-memory feature also needs to be installed among [other requirements](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/requirements-for-using-memory-optimized-tables?view=sql-server-ver15) to be able to succesfully create an in-memory table.

**Comment by ajcvickers** [comment]
@ErikEJ Consider making a PR?

**Comment by ErikEJ** [comment]
Yes, happy to. Should I remove the Supports sequences attribute or just leave it?

**Comment by ErikEJ** [comment]
Yes! PR submitted.
