### ISSUE TITLE
Multiple Connections in one DbContext

### ISSUE THREAD

**Issue by biqas** [dotnet/efcore#2032]
Hi,

would be great if a DbContext could handle multiple database connections.
Example could be, one/multiple connection(s) to one/multiple SQL-Database(s) for relational data and one/multiple connection to no-SQL-Database(s).

**Comment by rowanmiller** [comment]
**Team Triage:** We discussed this when we were originally designing EF7 and decided that a single context would always target a single database. If we want to support polyglot patterns in the future we would offer guidance (and possibly some components) to coordinate multiple contexts into a single unit of work.
