### ISSUE TITLE
Query: Casting to derived type to access member should cause client eval

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20335]
From #15807

If an entity is being cast to derived type then we need to client eval it to throw correct exception. (Casting to same type or base type should pass through). This is applicable to member access/ EF.Property both. Also for property/navigation/skipnavigation.

The only place where casting to derived type will be swallowed is when used inside include. Since include are applied only in final projection, we can add condition on client side without affecting server evaluability of whole query.

**Comment by AndriySvyryd** [comment]
If practical we should maintain the correct behavior, as making this client-eval would be a breaking change. We might need to add discriminator filters to the translation to fix incorrect results being returned in some cases.

**Comment by ajcvickers** [comment]
@smitpatel to add some examples that will break.

**Comment by maumar** [comment]
We decided to leave this behavior as is. In case of shared columns customers can filter entities using OfType, and in case they want to access values in the columns for all properties mapped to that column - retrieve them separately and use Union
