### ISSUE TITLE
How to replace the db on the fly?

### ISSUE THREAD

**Issue by raffaeler** [dotnet/efcore#20330]
I have a scenario where I need to archive the database file (sqlite) after a given amount of time.
I was thinking to create a dbcontext factory monitor the dbcontext instances:
- when the counter goes to zero, I should be able to archive the db and create the new empty file

Is there something in the infrastructure that can make this easier?

Thanks

**Comment by ajcvickers** [comment]
@raffaeler EF doesn't track the contexts created or disposed. This seems like something the application should handle if it is needed.

**Comment by raffaeler** [comment]
Thanks @ajcvickers.
Unfortunately the application can be shutdown but not restarted (when hosted in a pure Kestrel scenario). For this reason I was trying to solve the problem on the EF side.
I already have a background service running the migration during startup so that the db is created. But I still need to move the file in the archive folder after a given amount of time, and have no idea how.

If there is no solution or you don't have any suggestions, feel free to close this issue.

**Comment by ErikEJ** [comment]
Take a backup using the built in sqlite API for that?

**Comment by raffaeler** [comment]
@ErikEJ Interesting. Is there already a C# library for doing a backup?

**Comment by ErikEJ** [comment]
I think the @ericsink library exposes backup method, yes.

>> Moving out the file was even better because avoids possible problems in writing/clearing multiple times the db file

Yes, but impossible to do if the file is in use! backup or "VACUUM INTO" should do the trick.

**Comment by raffaeler** [comment]
I am trying to re-run automatically the app but it's pretty complex and not sure if asp.net core maintain some static stuff that may cause the errors i am seeing

**Comment by raffaeler** [comment]
For the sake of curiosity I resolved with two strategies:
1. app re-launching itself
2. On Linux, systemd supports "restart=" policy by checking the process exit status

At the application startup, if the db is old enough, it gets archived and then I let the migrations to their work (recreate the db, schema and seed the basic data).

Thanks all
