### ISSUE TITLE
Test: Make sure all owned types are having at least one column other than PK

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20336]
We see data in the column and we end up calling materializer even when entity type is base.
Happens in our tests since owned type did not have any additional column than PK to identify it's existence.

**Comment by smitpatel** [comment]
A general case would be resolved by #20334 
Re-purposed this issue to discuss about owned entity when there are no columns other than PK.
Not sure much value to support them but if we do then they would be required dependents anyway.

**Comment by AndriySvyryd** [comment]
Yes, we'll ensure they are required dependents in model validation once we support them. It doesn't matter what the behavior is until then.

**Comment by smitpatel** [comment]
So we can just update our tests and close this issue?

**Comment by AndriySvyryd** [comment]
Yes, but add a note on https://github.com/dotnet/efcore/issues/12100

**Comment by smitpatel** [comment]
I am adding at least one additional property in each owned type in tests other than PK.
