### ISSUE TITLE
Entity Equality rewrites owned == null check to PK check

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20342]
Even if owned entity is null, the PK may have value in case of table splitting scenario.

**Comment by smitpatel** [comment]
Related #20164 

@AndriySvyryd - Any thoughts what should be the behavior?

**Comment by AndriySvyryd** [comment]
We would need to use left joins to get the "correct" PK values (i.e. null if any required column is null, etc.) and compare against that. Same for OrderBy

**Comment by smitpatel** [comment]
Can we just write whole condition inline? Since it will always be scalar returning, we can put that in SQL without join.

**Comment by AndriySvyryd** [comment]
Yes, but then you'd need to write new logic to generate that
