### ISSUE TITLE
Cosmos: Detect partition key filters in more queries

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20350]
Currently one needs to write the query like this to use a partition key:
```C#
var blogs = context.Blogs.WithPartitionKey("1337").ToList();
```

Instead we could automatically detect the partition key filter if used:
```C#
var blogs = context.Blogs.Where(b => b.PartitionKey == "1337").ToList();
```

**Comment by alexeymarkov** [comment]
Is it already included into EF Core 5.0 release?
I am going to use querying by partition key in HasQueryFilter and would like to know whether it will be properly translated into a single partition query by specifying the detected partition key value in QueryRequestOptions.

**Comment by braidenstiller** [comment]
> Is it already included into EF Core 5.0 release?
> I am going to use querying by partition key in HasQueryFilter and would like to know whether it will be properly translated into a single partition query by specifying the detected partition key value in QueryRequestOptions.

I am also interested in this outcome.

**Comment by AndriySvyryd** [comment]
> Is it already included into EF Core 5.0 release?

This issue is still open therefore it hasn't been implemented.
Use `WithPartitionKey` to get the expected query.

**Comment by 1iveowl** [comment]
> > Is it already included into EF Core 5.0 release?
> 
> This issue is still open therefore it hasn't been implemented.
> Use `WithPartitionKey` to get the expected query.

Are you certain? The PR was merged, as I recall.

**Comment by AndriySvyryd** [comment]
Nevermind, it is in fact in 5.0 🥳

**Comment by AndriySvyryd** [comment]
You can enable Debug logging to make sure your query is getting picked up correctly

**Comment by smitpatel** [comment]
This is not fixed. The only place where PR identified this is for case of Find or query similar to `dbset.Where(keypredicate).FirstOrDefault()`
