### ISSUE TITLE
LINQ projection gives inconsistent results using in memory database

### ISSUE THREAD

**Issue by mateusz-szymanski** [dotnet/efcore#20359]
Given certain configuration with relationships and owned types, linq on dbset gives inconsistent results using in memory database. Changing the order of selecting values in the projection makes a difference.

### Steps to reproduce
I've created a simple solution with necessary setup and test: [EFCoreIssuePlayground.zip](https://github.com/dotnet/efcore/files/4361429/EFCoreIssuePlayground.zip) ([github](https://github.com/mateusz-szymanski/EFCoreIssuePlayground)).

``` C#
...
            var result1 = (from r in dbContext.Root
                           select new
                           {
                               r.B.BValue,
                               r.A.Sub.AValue
                           }).FirstOrDefault();

            var result2 = (from r in dbContext.Root
                           select new
                           {
                               r.A.Sub.AValue,
                               r.B.BValue,
                           }).FirstOrDefault();

            Assert.Null(result1.BValue);
            Assert.NotNull(result2.BValue);
```

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.InMemory, version: 3.1.2
Target framework: netstandard2.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.3

**Comment by davidfon** [comment]
This issue is preventing us from upgrading from EF Core 2.2. I've attached another example using the latest 5.0 preview that demonstrates the issue with a slightly different setup. In the attached example, the selected properties become juxtaposed incorrectly depending on which projection is used (e.g. `PersonFullName` receives the value of `entity.Person.PersonName.LastName`).
[EFCoreIssuePlayground.zip](https://github.com/dotnet/efcore/files/4610135/EFCoreIssuePlayground.zip)

**Comment by ajcvickers** [comment]
@davidfon Presumably this is impacting test code only, since it's an in-memory database issue. To give us a rough idea of the impact, how many tests do you have, and how many of them are failing?

**Comment by davidfon** [comment]
@ajcvickers Sorry, retract the bit about not being able to upgrade. We can work around it by simply pulling the data with `ToList()` and then projecting after the fact. Still, it's a little scary seeing data being randomly assigned across the properties.

**Comment by mateusz-szymanski** [comment]
@davidfon For the time being you could use another sql provider for tests, like sqLite. Then you can migrate to EF Core 3.0 and there is no need to artificially call `ToList`. It takes a bit longer to run the tests but aside from that it should work fine in most of the cases.
