### ISSUE TITLE
OrderBy converting to constant expression which errors

### ISSUE THREAD

**Issue by Lukazoid** [dotnet/efcore#20357]
When using EF Core 3.1.2, given the following:

```C#
int? idFromSearchText= ...;
    
var results = myQuery.OrderBy(x => x.Id == idFromSearchText? 1 : 2).ThenBy(x => x.Description);
```

When `idFromSearchText` is `null` this is getting converted to an OrderBy with a constant case:

```TSQL
ORDER BY CASE
    WHEN CAST(0 AS bit) = CAST(1 AS bit) THEN 1
    ELSE 2
END, [s0].[Description]
```

Which SQL server errors with: `A constant expression was encountered in the ORDER BY list, position 1.`

I assume this is because EF sees that `Id` (type `int`) can never be `null` so does some constant optimization, however it breaks the SQL order by.

I am currently migrating a project from Linq2Sql where this previously worked.

Is there any way to force this condition to be evaluated by SQL server?

I would expect something like:

```TSQL
ORDER BY CASE
    WHEN [s0].[Id] = @__idFromSearchText_0 THEN 1
    ELSE 2
END, [s0].[Description]
```

Or the omission of any order by clauses which are constant.

**Comment by maumar** [comment]
This has been fixed in master, case statement gets optimized to a constant which then gets removed.
