### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task`1<!!0> Microsoft.EntityFrameworkCore.DbContext.FindAsync(System.Object[])

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#20358]
I write some extensions for EF Core, and recently I found it works normal with ef core 2.x, but exception with ef core3.x, seemed it was because `FindAsync` return `Task` in efcore2.x, but `ValueTask` in efcore3.x and now efcore5.0, so I'm wondering if there's a variable to distinguish what returned by `FindAsync` or  is there other solution?

```
Method not found: 'System.Threading.Tasks.Task`1<!!0> Microsoft.EntityFrameworkCore.DbContext.FindAsync(System.Object[])
```

the code I'm using:

``` csharp
public async Task<TEntity> FindAsync(params object[] keyValues)
{
    var entity = await DbContext.FindAsync<TEntity>(keyValues);
    return entity;
}
```
source repo here <https://github.com/WeihanLi/WeihanLi.EntityFramework/blob/dev/src/WeihanLi.EntityFramework/EFRepository.cs#L37>

### Steps to reproduce

there're two sample projects here 

- efcore 2.x sample <https://github.com/WeihanLi/WeihanLi.EntityFramework/blob/dev/samples/WeihanLi.EntityFramework.Samples/Program.cs>
- efcore 3.1 sample <https://github.com/WeihanLi/WeihanLi.EntityFramework/blob/dev/samples/WeihanLi.EntityFramework.Core3_0Sample/Program.cs>

just run `dotnet run` under sample project dir, works normal with efcore 2.x sample, exception with efcore 3.x, exception details below:

> Method not found: 'System.Threading.Tasks.Task`1<!!0> Microsoft.EntityFrameworkCore.DbContext.FindAsync(System.Object[])'.
>
>    at WeihanLi.EntityFramework.EFRepository`2.<FindAsync>d__6.MoveNext() in C:\projects\sources\WeihanLi.EntityFramework\src\WeihanLi.EntityFramework\EFRepository.cs:line 39
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at WeihanLi.EntityFramework.EFRepository`2.FindAsync(Object[] keyValues)
   at WeihanLi.EntityFramework.Core3_0Sample.Program.<>c.<Main>b__1_3(IEFRepository`2 repo) in C:\projects\sources\WeihanLi.EntityFramework\samples\WeihanLi.EntityFramework.Core3_0Sample\Program.cs:line 87
   at WeihanLi.Common.DependencyResolver.ServiceCollectionDependencyResolver.TryInvokeService[TService](Action`1 action) in D:\a\1\s\src\WeihanLi.Common\DependencyResolver.cs:line 191
   at WeihanLi.EntityFramework.Core3_0Sample.Program.Main(String[] args) in C:\projects\sources\WeihanLi.EntityFramework\samples\WeihanLi.EntityFramework.Core3_0Sample\Program.cs:line 74

### Further technical details

EF Core version: ef core 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1
Operating system: windows 10
IDE:  Visual Studio 2019 16.5

**Comment by smitpatel** [comment]
Package version mixing across major versions. WeihanLi.EntityFramework depends on EF Core 2.1. If it is used to test with EF Core 3.1 it is likely going to fail.

**Comment by WeihanLi** [comment]
yeah, exactly that case, so is there a variable or some else method that I can know if ef core 3.x or 2.x is used?

**Comment by ajcvickers** [comment]
@WeihanLi You need to look at the packages you are using and the dependencies that they have.

**Comment by WeihanLi** [comment]
> @WeihanLi You need to look at the packages you are using and the dependencies that they have.

is there some variables like `DEBUG`/`NETCOREAPP3.1` to write some conditional compile code, just
 like code like belows:

``` csharp

#if EFCORE3_1
            // ...
#else
            // ...
#endif
```

**Comment by ajcvickers** [comment]
@WeihanLi No.

**Comment by smitpatel** [comment]
@WeihanLi - From what I know, you would need multiple projects to support multiple versions of same dependency. You can certainly share the source files. The code snippet you shared with variable EFCORE3_1 can be defined in csproj which references EF Core 3.1 using XML tag `DefineConstants`.
Beyond that I feel that this is more of a question for [project system](https://github.com/dotnet/project-system)  rather than EF Core.

**Comment by WeihanLi** [comment]
Thanks
