### ISSUE TITLE
BufferedDataReader needs to be accommodating to incorrect values

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20364]
While working on #20278, we enabled tests which has wrong data to verify we throw better exceptions. All the tests are working correctly for Sqlite. But for SqlServer where we use BufferedDataReader, the reader throws early exception while trying to read values. Hence the code not reach the place where we intercept exception to throw better message (that code is part of shaper), BufferedDataReader buffers before calling into shaper.

**Comment by smitpatel** [comment]
This requires passing enabledDetailedErrors to Execute method via RelationalCommandParameterObject which is public.

**Comment by AndriySvyryd** [comment]
Adding a property to RelationalCommandParameterObject is not a breaking change.
@dotnet/efteam Does anyone think we shouldn't do this in 5.0?

**Comment by smitpatel** [comment]
No new ctor to take value for that parameter?

**Comment by AndriySvyryd** [comment]
> No new ctor to take value for that parameter?

Yes, a new overload

**Comment by ajcvickers** [comment]
I'm good with it.
