### ISSUE TITLE
Give example of what userSuppliedSearchTerm can be.

### ISSUE THREAD

**Issue by gorgi** [dotnet/efcore#20361]
Currently, it is very confusing how to use this new method. More thorough exemples will help us understand the right usage of this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8243b953-5de7-3123-0737-9be4ca3c08fd
* Version Independent ID: 1d1c0196-70ac-a45e-d1b7-48c55963f612
* Content: [RelationalDatabaseFacadeExtensions.ExecuteSqlInterpolatedAsync(DatabaseFacade, FormattableString, CancellationToken) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolatedasync?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
In the example here it could be made clearer that `userSuppliedSearchTerm` is a variable representing a parameter for the query.

**Comment by F0b0s** [comment]
@ajcvickers I'm new to this repository, can you explain more preciselly where the example should be created? I would like to implement this.

**Comment by Marusyk** [comment]
It should be added to [this page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolatedasync?view=efcore-3.1#feedback). So, you need to fork [EntityFramework.ApiDocs](https://github.com/dotnet/EntityFramework.ApiDocs) repository and add the example to https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml

**Comment by smitpatel** [comment]
@F0b0s - It should be updated in https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs file where the API is defined. ApiDocs are auto-generated from XML comments over the source code.

**Comment by manvydasu** [comment]
@smitpatel Could you elaborate what the improved example is supposed to look like? At first I didn't realize that 'dbo.SearchBlogs' is actually Table Valued Function..

I was thinking of few options:
1. Add another example which is simpler, like:
`"SELECT * FROM [dbo].[Blogs] WHERE Name LIKE '{userSuppliedSearchTerm}%'"`

2. Replace the example?

3. Mention that `[dbo].[SearchBlogs]` is actually Table Valued Function.. `

**Comment by smitpatel** [comment]
The example needs to mention in some way that `userSuppliedSearchTerm` is a variable. Possibly defining variable in C# before the query in the example would work.
