### ISSUE TITLE
Regression in PostgreSQL Contains on array

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20369]
Since syncing EFCore.PG from commit 725adf77d3a08d99ce59787354d391176c3844b7 to ac4633559b117b92156d75f07b7ef81dc920b4fd, Contains on arrays is broken. AllAnyContainsRewritingExpressionVisitor seems rewrites the Contains to Any, which then produces a translation failure. This rewriting seems problematic to me (shouldn't we leave alone calls on arrays or other stuff?), but let me know if this is intentional and I should change the provider to recognize Any on arrays instead of Contains.

**Comment by smitpatel** [comment]
Suspected PR which adding offending code https://github.com/dotnet/efcore/pull/19744

Related issue to improve https://github.com/dotnet/efcore/issues/20155 (not sure if that would fix this too. Blocked on #20164 

Can you also post expression tree which fails?

**Comment by roji** [comment]
Sure, here you go:

```
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression].Single(e => e.SomeArray.Contains(3))
```

After NormalizeQueryableMethodCall:

```
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression].Single(e => e.SomeArray.AsQueryable().Contains(3))
```

After AllAnyContainsRewritingExpressionVisitor:

```
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression].Single(e => e.SomeArray.AsQueryable().Any(p => (p == 3)))
```

**Comment by ajcvickers** [comment]
I'm assuming, because we have tests for it, that Contains on byte arrays is still working. Do we special case byte arrays somewhere?

**Comment by roji** [comment]
I thought about this some more... The Npgsql provider should actually be able to translate a simple Any on arrays - as long as the tree above doesn't produce any exceptions in preprocessing and makes it to translation, I should just handle this structure. So this is probably not an issue (though let me confirm).

**Comment by roji** [comment]
FYI just unskipped the tests and they're green, thanks!
