### ISSUE TITLE
SQLite provider and JsonDocument property

### ISSUE THREAD

**Issue by Lobosque** [dotnet/efcore#20379]
## What problem are you trying to solve? 
I have a codebase that I use both the SQLite provider (tests) and the Postgres Provider (production). I am trying to use `JsonDocument` Properties as described here: [https://www.npgsql.org/efcore/mapping/json.html](https://www.npgsql.org/efcore/mapping/json.html)
But apparently there is no equivalent mapping for SQLite.

Is support for such mapping in the roadmap?

Is there anything I can do to make the SQLite Understand this type of property? Even if it is something very simple as storing the content as string.

**Comment by ajcvickers** [comment]
@Lobosque #4021 is tracking JSON support in general.

For now, you can use a [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) to map JSON to a string column, serializing on save, and deserializing when reading the value back.

If you want to do this only for SQLIte, then wrap the code in OnModelCreating with `if (Database.IsSqlite())`.

**Comment by Lobosque** [comment]
@ajcvickers this will work just fine for my use case.
Closing the issue, thanks.

**Comment by douglasg14b** [comment]
Is there a new ticket tracking this? It seems that the feature implemented for #4021 addresses owned entities, but not necessarily `JsonDocument` conversion & JSONB queries 🤔

**Comment by roji** [comment]
Yes, see #28871.
