### ISSUE TITLE
Update EF Core 3.1 SqlClient dependency to 1.1.1

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20378]
See #20316 and #20377

**Comment by cheenamalhotra** [comment]
Hi @ajcvickers 

We released [v1.1.2](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.1.2) today and would recommend using the new one with more improvements!
[Release Notes](https://github.com/dotnet/SqlClient/blob/master/release-notes/1.1/1.1.2.md)

Thanks, Cheena
