### ISSUE TITLE
Cascade delete in EfCore 3.1.2

### ISSUE THREAD

**Issue by dennis-8** [dotnet/efcore#20372]
Hello,

something is not working as expected with Cascade delete.

Parent models (`WorkflowVersion` and `StepVersion` ) have cascade delete  and there is many to many relationship between children (`Step `and `Workflow`):

```C#
modelBuilder.Entity<WorkflowVersion>()
                .HasMany(x => x.Workflows)
                .WithOne(x => x.WorkflowVersion)
                .OnDelete(DeleteBehavior.Cascade);

modelBuilder.Entity<Workflow>()
                .HasMany(x => x.StepWorkflows)
                .WithOne(x => x.Workflow)
                .OnDelete(DeleteBehavior.Cascade);

modelBuilder.Entity<StepVersion>()
                .HasMany(x => x.Steps)
                .WithOne(x => x.StepVersion)
                .OnDelete(DeleteBehavior.Cascade);

// many to many
modelBuilder.Entity<StepWorkflow>()
                        .HasKey(x => new { x.StepId, x.WorkflowId });

modelBuilder.Entity<StepWorkflow>()
                        .HasOne(x => x.Step)
                        .WithMany(x => x.StepWorkflows)
                        .HasForeignKey(x => x.StepId);

modelBuilder.Entity<StepWorkflow>()
                        .HasOne(x => x.Workflow)
                        .WithMany(x => x.StepWorkflows)
                        .HasForeignKey(x => x.WorkflowId);
```
The order in which models are deleted matters, `WorkflowVersion `and `Workflow `and `StepWorkflow `first, then `StepVersion`.

I was expecting that next code will first delete `workflowVersion `and `stepVersions `after that, but it always starts to delete step versions first.

Why is it starting to delete `stepVersion `first?

```C#
_context.WorkflowVersions.Remove(workflowVersion);

_context.StepVersions.RemoveRange(stepVersions);

await _context.SaveChangesAsync();
```
How to make the code work without calling `SaveChangesAsync ` after each `Remove`?

**Comment by ajcvickers** [comment]
@denis-n I'm having trouble understanding how all four entity types interact in the model. Can you also post the code for the entity types?

**Comment by denis-n** [comment]
```
public class WorkflowVersion
    {
        public Guid Id { get; set; }

        public int LastPublishedVersion { get; set; }

        public bool IsPublished { get; set; }        

        public ICollection<Workflow> Workflows { get; set; }
    }

public class Workflow
    {
        public Guid Id { get; set; }        

        public Guid WorkflowVersionId { get; set; }

        public WorkflowVersion WorkflowVersion { get; set; }

        public ICollection<StepWorkflow> StepWorkflows { get; set; }
    }

public class StepVersion 
    {
        public Guid Id { get; set; }

        public int LastPublishedVersion { get; set; }

        public bool IsPublished { get; set; }

        public ICollection<Step> Steps { get; set; }
    }

public class Step
    {
        public Guid Id { get; set; }                

        public Guid StepVersionId { get; set; }

        public StepVersion StepVersion { get; set; }

        public ICollection<StepWorkflow> StepWorkflows { get; set; }        
    }

public class StepWorkflow 
    {
        public Guid StepId { get; set; }

        public Step Step { get; set; }

        public Guid WorkflowId { get; set; }

        public Workflow Workflow { get; set; }        
    }
```

There are separate pages for Steps and for Workflows. And when a step is deleted, I want to delete all versions of that step, that's why StepVersion has cascade delete.

Same for workflows, but I don't want to use cascade delete for StepWorkflow (delete a step when a stepWorkflow is deleted), user can just 'disconnect' steps and workflows..

**Comment by ajcvickers** [comment]
@denis-n Can you explain again _why_ you expect to see `workflowVersions` deleted before `stepVersions`?

**Comment by denis-n** [comment]
I first call delete `workflowVersion `and after that I call delete `stepVersion`.

In EfCore **2.1** it was working, the order was important there.

Did **3.1** changed that? Where can I read about it?

**Comment by ajcvickers** [comment]
@denis-n EF Core creates an ordering for updates based on constraints in the model. This is incompatible in the general case with deleting in the order that items are marked deleted in the context, which in general won't work because of constraint violations. If it was deleting in that order in 2.1, then this was purely by chance.

If you need to force some deletes to happen before the other, then you'll need to call SaveChanges twice--once for each set of deletes.

**Comment by denis-n** [comment]
Here is an example how to use transactions.

Does it look correct?

```
                using (var transaction = await _context.Database.BeginTransactionAsync())
                {
                    _context.WorkflowVersions.Remove(new WorkflowVersion
                    {
                        Id = workflowVersionId
                    });

                    await _context.SaveChangesAsync();


                    _context.StepVersions.RemoveRange(stepVersions);

                    await _context.SaveChangesAsync();


                    await transaction.CommitAsync();
                }
```
