### ISSUE TITLE
Comparers are internal

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20387]
- [x] ForeignKeyComparer
- [x] EntityTypePathComparer
- [x] IndexComparer
- [x] KeyComparer
- [x] ReferenceEqualityComparer

**Comment by ajcvickers** [comment]
@AndriySvyryd I've been looking through these and think we could make them all public. If anyone needs to compare metadata items, then I'd rather they use ours than roll their own. Okay with that?

**Comment by AndriySvyryd** [comment]
Perhaps if we name/document them properly. My concern is that without looking the implementation one may assume that they check for equality, however they only compare identity.
