### ISSUE TITLE
false DecimalTypeDefaultWarning[30000] because converter is ignored

### ISSUE THREAD

**Issue by springy76** [dotnet/efcore#20406]
I'm using a **converter** on a `decimal` property which converts the value to `Int64` (BigInt on SqlServer) but I still get a warning logged (to Seq) on each app start (first context creation) for every single decimal property being part of the model (all have the converter assigned):

> No type was specified for the decimal column 'Balance' on entity type 'Customer'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values using 'HasColumnType()'.

(does not happen when using SQLite provider)

### Steps to reproduce

A property somewhere in the model:
``` C#
public decimal Balance { get; set; }
```
The converter applied to `ModelBuilder`
``` C#
modelBuilder.Entity<Customer>()
    .Property(c => c.Balance).ConvertToIntegerMoneyCents();
```
The converter itself:
``` C#
private static readonly ValueConverter decimalMoneyToLongCentsConverter = new DecimalMoneyToLongCentsConverter();

public static PropertyBuilder<decimal> ConvertToIntegerMoneyCents(this PropertyBuilder<decimal> propertyBuilder, string suffix = "Cents")
=> propertyBuilder
	.HasConversion(decimalMoneyToLongCentsConverter)
	.HasColumnName(propertyBuilder.Metadata.Name + suffix);

private sealed class DecimalMoneyToLongCentsConverter : ValueConverter<decimal, long>
{
	private static readonly Expression<Func<decimal, long>> convertToProviderExpression = d => TryConvertToProvider(d);
	private static readonly Expression<Func<long, decimal>> convertFromProviderExpression = l => l / 100m;

	internal DecimalMoneyToLongCentsConverter()
		: base(convertToProviderExpression, convertFromProviderExpression)
	{
	}

	private static long TryConvertToProvider(decimal value)
	{
		var cents = value * 100;
		if ( decimal.Truncate(cents) != cents )
			throw new ArgumentException("Using money with more than 2 digits after comma would loose information!", nameof(value));
		return (long)cents;
	}
}
```

I could add `.HasColumnType("BigInt")` but that would break the currently provider-agnostic definition of the model. (While this might work for SQLite, for other providers this will throw an error.)

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.2
Operating system: W10
IDE: VS 16.5.1

**Comment by ajcvickers** [comment]
@springy76 This doesn't look correct:

```C#
.HasConversion<DecimalMoneyToLongCentsConverter>()
```

The generic parameter for HasConversion is not the converter, it's the provider-side type. I'm surprised you were able to get able to get even the model built using this code. Are you sure it is being called?

**Comment by springy76** [comment]
Sorry for that. The real code uses a static readonly property:

``` c#
		private static readonly ValueConverter decimalMoneyToLongCentsConverter = new DecimalMoneyToLongCentsConverter();
[..]
			.HasConversion(decimalMoneyToLongCentsConverter)

```

**Comment by ajcvickers** [comment]
@springy76 Thanks, I am able to reproduce this now. Since the warning is erroneous in this case, you could configure it to be ignored:

```C#
optionsBuilder.ConfigureWarnings(w => w.Ignore(SqlServerEventId.DecimalTypeDefaultWarning))
```
