### ISSUE TITLE
Support store-specific non-composable query detection

### ISSUE THREAD

**Issue by mikary** [dotnet/efcore#2040]
The `EntityQueryableExpressionTreevisitor` currently checks for `FromSql` strings starting with "EXEC" to determine if composition is possible. This logic should be factored out to allow providers to determine when composition is supported.

**Comment by divega** [comment]
@mikary Should this be closed now? It seems to be referenced by a PR that isn't the last one.

**Comment by mikary** [comment]
Possibly, right now we are checking the SQL to see if it's a stored procedure in the ```RelationalEntityQueryableExpressionTreeVisitor``` and not allowing a provider-specific override. If we're okay with going by the logic of "Anything that doesn't start with ```SELECT``` is non-composable" on all providers, we could go ahead and close this out.

**Comment by divega** [comment]
Closing for now since the new logic seems to be applicable to all relational providers. If we find exceptions in the future we can revisit.
