### ISSUE TITLE
DbCommandInterceptor not triggered when using CosmosDb

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#20436]
DbCommandInterceptor methods are not executed when using a CosmosDb context.

Please see sample output and code below.  I used the same interceptor and it gets triggered using a SqlLite context but not a CosmosDB.

![image](https://user-images.githubusercontent.com/22228405/77781510-b3260100-7023-11ea-89da-687ceeef3ca2.png)

### Further technical details
        static void Main(string[] args)
        {

            var connectionStringBuilder = new SqliteConnectionStringBuilder 
                {
                    DataSource = "UsersDb",
                    Cache = SqliteCacheMode.Shared,
                    Mode = SqliteOpenMode.Memory
                };  
            var connectionString = connectionStringBuilder.ToString(); 

            var _connection = new SqliteConnection(connectionString);
            _connection.Open();

            var cosmosEndPoint = "https://localhost:8081";
            var cosmosKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";

            var sqlOptionsBuilder = new DbContextOptionsBuilder<SqlDbContext>().UseSqlite(_connection);
            sqlOptionsBuilder.AddInterceptors(new MyIntereceptor());
            var cosmosOptionsBuilder = new DbContextOptionsBuilder<CosmosDbContext>().UseCosmos(cosmosEndPoint, cosmosKey, "Users");
            cosmosOptionsBuilder.AddInterceptors(new MyIntereceptor());

            var userId = Guid.NewGuid();

            var sqlContext = new SqlDbContext(sqlOptionsBuilder.Options);
            sqlContext.Database.EnsureCreated();
            var sqlUser = sqlContext.Users.Find(userId);
            if (sqlUser == null)
            {
                sqlContext.Users.Add(new User { UserId = userId, FirstName = "First", LastName = "Last" });
                sqlContext.SaveChanges();
            }

            var cosmosContext = new CosmosDbContext(cosmosOptionsBuilder.Options);
            cosmosContext.Database.EnsureCreated();
            var cosmosUser = cosmosContext.Users.Find(userId);
            if (cosmosUser == null)
            {
                cosmosContext.Users.Add(new User { UserId = userId, FirstName = "First", LastName = "Last" });
                cosmosContext.SaveChanges();
            }           
        }

       public class MyIntereceptor : DbCommandInterceptor
           {
               public override InterceptionResult<DbDataReader> ReaderExecuting(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
               {
                   Console.WriteLine($"Provider: {eventData.Context.Database.ProviderName}");
                   Console.WriteLine($"Command: {command.CommandText}");
                   Console.WriteLine();
                   return base.ReaderExecuting(command, eventData, result);
               }

           }

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: NET Core 3.1
Operating system:
IDE: VS 2019 16.5.1

**Comment by ErikEJ** [comment]
Is Cosmos a relational provider?

**Comment by rbt-eugene** [comment]
@ErikEJ cool, looks like no dice then.
