### ISSUE TITLE
Warn when uniquifying an FK column name

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20435]
Consider the case where there is a candidate FK property by name in the dependent CLR type, but it doesn't work for the FK for some other reason--commonly, that the type of the property is not compatible with the type of the PK property. In this case we currently create a shadow property with a uniquified name--e.g. `BlogId1`. I assert that this is almost always not what is wanted. We should consider making this a warning, or perhaps even an error by default.

**Comment by AnthonyGiretti** [comment]
Thank you I really appreciate!

**Comment by wenz** [comment]
I agree, would be really useful, since I was hit by "SomeId1" a few times, as well.

**Comment by ajcvickers** [comment]
Discussed with the team:
* We currently have debug-level logging for this. We could promote this to warning, but sometimes the property will be removed later in the model build process as more information is gathered and conventions are re-run.
* We could therefore instead keep track of when we're doing this, but then only warn if the synthesized properties remain in the final model.

**Comment by AnthonyGiretti** [comment]
Ok thank you!
*Anthony Giretti*
*Blogger, Speaker | MVP, MCSD*
*m:*  +1 514 557 1380 <+1+514+557+1380>
*s:  *anthonygiretti.com
*e:  *anthony.giretti@gmail.com


Le ven. 27 mars 2020 à 15:07, Arthur Vickers <notifications@github.com> a
écrit :
