### ISSUE TITLE
Is disposing required?

### ISSUE THREAD

**Issue by ryno1234** [dotnet/efcore#20434]
EF Core has a .Dispose() method. Is it required to call this (or use a Using statement)  or is this handled automatically? If it is not, why is not not called via a Finalizer?

**Comment by ajcvickers** [comment]
@ryno1234 You should dispose it. If you don't, then any native resources will eventually be freed by the finalizer, but this will result in very inefficient management of resources, including potentially running out of resources like connections. Also, EF cleans up various registrations when the context is disposed. Not doing this could result in memory leeks depending on how those registrations interact with the lifetime of objects in the heap.

**Comment by ryno1234** [comment]
Thanks @ajcvickers ! Have a good day.
