### ISSUE TITLE
EF Core doesn't seem to properly remove foreign keys when using IMutableEntityType's RemoveForeignKey method

### ISSUE THREAD

**Issue by JerrettDavis** [dotnet/efcore#20440]
Another issue (#14863), seemed to hit on this, but I could not find any resolution listed. 

Our application features a multitenant DbContext that allows for automatic data segregation and provisioning by leveraging shadow properties and global query filters. This works great, but we recently found the need to setup composite primary keys for tables that don't have an identity column. 

In an effort to do this as painlessly as possible, I built some extension methods for `ModelBuilder` to leverage in `OnModelCreating`. I initially call `ApplyConfigurationsFromAssembly`, followed by my model mutation methods. 

The basic flow of the mutation method works like so. First, I fetch all entities that implement `IOrganizationEntity`. I then iterate over the collection adding a hidden guid field called `OrganizationIdentifier` to each one. While updating the model, I check if the entity contains a non-identity primary key. If it does, I remove the existing primary key, combine it with my `OrganizationIdentifier` field, and re-add the pair as the primary key. 

After this is done, I need to remove the existing foreign key relationships that relied on the previous primary key. I've attempted to this using the `RemoveForeignKey` method on `IMutableEntityType`, but after stepping through EF Core's code, it appears at some point the foreign key (and its associated navigation) get recreated. 

I try to remedy this by calling `IMutableEntityType`'s `IsIgnored` on every property that is referenced on the primary key (as well as the navigation properties). Regardless, it appears that the foreign keys always regenerate in some fashion, making it impossible for me to rebind the navigation properties. 

Is there any sort of work-around for this?

### Steps to reproduce

The following is a simplified version of my extension methods. I have been debugging them by inserting a `Debugger.Launch()`, and running `>dotnet ef migrations add InitialCreate` from my DbContext root directory in a terminal.

``` C#
public static ModelBuilder MutateOrganizationEntities(this ModelBuilder modelBuilder)
{
    var entities = modelBuilder.Model.GetEntityTypes()
        .Where(x => typeof(IOrganizationEntity).IsAssignableFrom(x.ClrType));

    foreach (var entity in entities)
    {
        entity.AddProperty("OrganizationIdentifier", typeof(Guid));
        
        var orgId = entity.FindProperty("OrganizationIdentifier");
        var keys = entity.GetProperties().Where(e => e.IsKey())
            .ToHashSet();
        
        if (keys.Any(k => k.ValueGenerated == ValueGenerated.OnAddOrUpdate))
            continue;

        keys.Add(orgId);
        entity.SetPrimaryKey(keys.ToList());
        
        FixRelationships(entity);
    }

    return modelBuilder;
}

private static void FixRelationships(IMutableEntityType entity)
{
    var references = entity.GetDeclaredReferencingForeignKeys()
        .ToList();

    foreach (var reference in references)
    {
        var element = reference.DeclaringEntityType;
        foreach (var prop in reference.Properties)
            element.IsIgnored(prop.Name);

        if (reference.DependentToPrincipal != null)
            element.IsIgnored(reference.DependentToPrincipal.Name);

        if (reference.PrincipalToDependent != null)
            entity.IsIgnored(reference.PrincipalToDependent.Name);

        element.RemoveForeignKey(reference);

        // excluded the foreign key recreation code for brevity.
    }
}
```

I've also attached a small sample application that demonstrates the behavior. 
[EFCoreMultiTenantDemo.zip](https://github.com/dotnet/efcore/files/4395967/EFCoreMultiTenantDemo.zip)

### Further technical details

EF Core version: 3.1.2
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET Core 3.1
Operating system: Windows 10 Build 1909
IDE: Jetbrains Rider 2019.3.4

**Comment by smitpatel** [comment]
Based on scenario, instead of Removing FK you should just set new FK. That would automatically remove previous FK and not add one by convention.

**Comment by JerrettDavis** [comment]
@smitpatel Can you recommend a method? Simply using [IMutableEntityType.AddForeignKey](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.imutableentitytype.addforeignkey?view=efcore-3.1) results in a new foreign key being created, but it preserves the previous foreign key. Attempting to set `DependentToPrincipal` or `PrincipalToDependent` results in an error as the previous foreign key still references the, now-defunct, navigation properties.

**Comment by smitpatel** [comment]
Looks like `IMutableEntityType` does not have function to replace FK. So best case would be to suspend conventions while you make change. Probably it goes into a lot more internal code.
@AndriySvyryd  may know a better way else it may not be possible to make this change.

**Comment by AndriySvyryd** [comment]
You can call `IMutableForeignKey.SetProperties` to change the properties on the foreign key.

You can call ((Model)Model).ModelBuilder.Metadata.ConventionDispatcher.DelayConventions() to delay the convention, see https://github.com/dotnet/efcore/blob/68a3fbc62d8cfb45e77728ddf774838b5ffe5439/src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs#L89

Or you can avoid all that and instead call `((IConventionEntityType)entityType).Builder.PrimaryKey()` that does all of this for you.

**Comment by JerrettDavis** [comment]
@AndriySvyryd Using `IMutableForeignKey.SetProperties` gets me nearly there, but during model generation, it applies a `UniqueConstraint` on the original primary key. 

Using `DelayConventions` while calling `SetProperties` does not affect this. Using `DelayConvetions` while removing the foreign and readding it using `IMutableEntityType.RemoveForeignKey` and `IMutableEntityType.AddForeignKey` like in the method below, results in 2 foreign keys being created, one from convention and one from the method.

```C#
private static void Fix(IMutableEntityType entity)
{
    var references = entity.GetDeclaredReferencingForeignKeys()
        .ToList();

    using (((Model) entity.Model).Builder.Metadata.ConventionDispatcher.DelayConventions())
    {
        foreach (var reference in references)
        {
            var currentProps = reference.Properties.ToList();
            var identity = reference.DeclaringEntityType.FindProperty("TenantIdentifier");
            var pk = entity.FindPrimaryKey();
        
            currentProps.Add(identity);
            // var casted = currentProps.Cast<Property>().ToList().AsReadOnly();
            // reference.SetProperties(casted, pk);

            reference.DeclaringEntityType.RemoveForeignKey(reference);
            reference.DeclaringEntityType.AddForeignKey(currentProps, pk, entity);
        }
    }   
}
```

I attempted replacing my initial call to `IMutableEntityType.SetPrimaryKey` with `((IConventionEntityType) entity).Builder.PrimaryKey(keys.Cast<IConventionProperty>().ToList());` and nothing appeared to change in the migrations, leaving the original primary keys in tact. Using it in tandem with `IMutableEntityType.SetPrimaryKey` results in identical behavior as not using it at all.

**Comment by JerrettDavis** [comment]
I believe I have come up with a potential workaround. It appears that I can store a reference to the original primary key, and use `IMutableEntityType.RemoveKey` after I have fixed the relationship using `IMutableForeignKey.SetProperties`. This does not result in an extraneous `UniqueConstrant`, and it appears that all the various mappings are now correct. 

I will have to continue doing some more testing before closing.

**Comment by JerrettDavis** [comment]
After fairly extensive testing, everything appears to be working properly. Thanks for the pointers. Cheers 🍺.
