### ISSUE TITLE
More specific exceptions to abstract database backend

### ISSUE THREAD

**Issue by glen-84** [dotnet/efcore#2044]
See: https://entityframework.codeplex.com/workitem/1270

Doctrine's DBAL has this: https://github.com/doctrine/dbal/pull/458/files

**Comment by arangas** [comment]
Yes - this seems related to #2017 (my issue) and #1808.

**Comment by rowanmiller** [comment]
Duplicate of https://github.com/aspnet/EntityFramework/issues/2017
