### ISSUE TITLE
Seralizing a List<EnumType> doesn't work - but a List<int> does (Postgresql)

### ISSUE THREAD

**Issue by Tylertron1998** [dotnet/efcore#20449]
EntityFramework does not seem to know to cast an List<SomeEnum> to a List<int> - at runtime an exception is thrown:
```
 Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> System.NotSupportedException: The CLR array type System.Collections.Generic.List`1[EfCoreRepo.Models.Colours] isn't supported by Npgsql or your PostgreSQL. If you wish to map it to an  PostgreSQL composite type array you need to register it before usage, please refer to the documentation.
```

### Further technical details

EF Core version: 3.1.3
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL 3.1.3)
Target framework: NET Core 3.0
Operating system: Windows 10
IDE: Jetbrains Rider

**Comment by ajcvickers** [comment]
@roji Is mapping lists of enums something the Npgsql EF provider is intended to support already?

**Comment by roji** [comment]
This does work for me on 3.1.3, but you do need to do some setup to make it work - see the code sample below ([and also the docs](http://www.npgsql.org/efcore/mapping/enum.html?tabs=tabid-1).

Note that List support in version 3.1 of the Npgsql EF provider is limited - many operations aren't translated, and you're better off using an array instead. However, for 5.0 List support should be on par with array support (https://github.com/npgsql/efcore.pg/issues/395), so consider giving 5.0.0-preview1 a try. 

PS Npgsql/PostgreSQL EF issues are better filed on github.com/npgsql/efcore.pg.

```c#
class Program
{
    static void Main()
    {
        using var ctx = new BlogContext();
        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();

        var result = ctx.Blogs.Where(b => b.Moods.Contains(Mood.Sad)).ToList();
    }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql(...)
            .UseSnakeCaseNamingConvention()
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    static BlogContext()
    {
        NpgsqlConnection.GlobalTypeMapper.MapEnum<Mood>();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresEnum<Mood>();
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Mood> Moods { get; set; }
}

public enum Mood
{
    Happy,
    Sad
}
```

On 5.0.0-preview1 the query generates the following SQL:

```sql
SELECT b.id, b.moods, b.name
FROM blogs AS b
WHERE 'sad'::mood = ANY (b.moods)
```
