### ISSUE TITLE
Foreign key violation when adding child node into context

### ISSUE THREAD

**Issue by htuomola** [dotnet/efcore#2045]
I have a model which contains one-to-many relationship between parent and child nodes (many children for one parent). When creating a new child and parent and only adding Child to the context.Children I get an exception:

Microsoft.Data.Entity.Update.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Child_Parent_ParentId". The conflict occurred in database "EF7Test", table "dbo.Parent", column 'Id'.

The code which fails is:

``` csharp
using (var ctx = new SimpleContext())
{
    var parent = new Parent
    {
        Id = Guid.NewGuid(),
        Name = "John"
    };
    var child = new Child {Name = "Dave", Id = Guid.NewGuid(), Parent = parent};
    ctx.Children.Add(child);
    ctx.SaveChanges();
}
```

Model in question is

``` csharp
public class Parent
{
    public Guid Id { get; set; }
    public string Name { get; set; }

    public List<Child> Children { get; set; }
}

public class Child
{
    public Guid Id { get; set; }
    public string Name { get; set; }

    public Guid ParentId { get; set; }
    public Parent Parent { get; set; }
}
```

Context is defined as

``` csharp
public class SimpleContext : DbContext
{
    public DbSet<Parent> Parents { get; set; }
    public DbSet<Child> Children { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\v11.0;Database=EF7Test;Trusted_Connection=True;MultipleActiveResultSets=true");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Child>()
            .ForRelational(r =>
            {
                r.Table("Child");
            });

        modelBuilder.Entity<Child>()
            .Key(r => r.Id);

        modelBuilder.Entity<Child>()
            .Property(r => r.Id)
            .GenerateValueOnAdd(true);


        modelBuilder.Entity<Child>()
            .Reference<Parent>(rs => rs.Parent)
            .InverseCollection(r => r.Children)
            .ForeignKey(rs => rs.ParentId);

        // parent model

        modelBuilder.Entity<Parent>()
            .ForRelational(r =>
            {
                r.Table("Parent");
            });

        modelBuilder.Entity<Parent>()
            .Key(r => r.Id);

        modelBuilder.Entity<Parent>()
            .Property(r => r.Id)
            .GenerateValueOnAdd(true);
    }
}
```

This happens both with 7.0.0-beta5-12939 and 7.0.0-beta5-12983. I have a complete project I can share if that helps.

**Comment by divega** [comment]
@mikary Please investigate.

**Comment by mikary** [comment]
This is actually working as designed. In EF7 calling ```ctx.Children.Add(child);``` only adds the child instance and does not traverse the navigation properties to find other instances to track. There are two ways you can go about solving this in your application:
* Add the parent instance explicitly: ```ctx.Parents.Add(parent);```
* Use the TrackGraph method to traverse the navigation properties ```ctx.ChangeTracker.TrackGraph(child, entry => { entry.State = EntityState.Added; });```

The ```TrackGraph``` option uses the ```Action<EntityEntry>``` to support more advanced scenarios, but if you are just looking to track a completely new graph, as in this scenario, the above action should be sufficient.

**Comment by htuomola** [comment]
Thanks for the response. Is it intentional that the same code which fails for SQL provider works fine with in-memory provider? Sample code below (context constructor just calls base class (DBContext) constructor with the options).

```csharp
[TestMethod]
public void AddTree_ViaChild_InMemory()
{
	var optionsBuilder = new DbContextOptionsBuilder();
	optionsBuilder.UseInMemoryStore();
	using (var ctx = new SimpleContext(optionsBuilder.Options))
	{
		var parent = new Parent
		{
			Id = Guid.NewGuid(),
			Name = "John"
		};
		var child = new Child { Name = "Dave", Id = Guid.NewGuid(), Parent = parent };
		ctx.Children.Add(child);
		ctx.SaveChanges();
	}
}
```

**Comment by mikary** [comment]
With the in memory store, the issue is that the FK relationships are not enforced, as described in #2166. If you follow the ```using``` with a query on ```Parents``` in the context, the resulting list will be empty because it is not traversing the navigations.

```cs
using (var ctx = new SimpleContext(optionsBuilder.Options))
{
    var parents = ctx.Parents.ToList();
    Console.WriteLine("Parents: {0}", parents.Count());
}
```
