### ISSUE TITLE
Include depth, influencing circular references

### ISSUE THREAD

**Issue by rockstardev** [dotnet/efcore#2046]
This problem is probably mentioned a lot - I am just wondering if anything is lately done to handle this. Here is good example of problem:

http://stackoverflow.com/questions/13691563/entity-framework-always-includes-data-that-is-in-context-even-if-i-dont-ask-for

I have similar issue, only in my case I have one to one reference like this:

```
public class TopObject
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int TopObjectId { get; set; }

    public virtual ChildObject ChildObject { get; set; }
}

public class ChildObject
{
    [Key]
    [ForeignKey("TopObject")]
    public int TopObjectId { get; set; }
    public TopObject TopObject { get; set; }
}
```

And what happens when I run db.TopObject.Include(a=>a.ChildObject) is that I get circular reference... like this:

```
var x = db.TopObjects.Include(a=>a.ChildObject).Single(a=>a.TopObjectId == 1);
// now I have: x.ChildObject.TopObject.ChildObject.TopObject...
```

Obviously this problem can be solved in numerous ways (and sometimes doesn't need solving at all), but I really believe it would be beneficial if this is solved on EntityFramework level, along the lines of having something like:

```
db.TopObjects.Include(a => a.ChildObject, 0)
// depth of 0 should result in x.ChildObject.TopObject == null
```

Any chance of making something like this happen?

**Comment by rowanmiller** [comment]
The classes you used in your example aren't a hierarchical relationship, they are a simple one-to-many relationship. In your example you have a single instance of a TopObject with a single instance of a ChildObject. Therefore when you query for them using Include you get both objects in memory.

The top object (x) points to the child which in turn points back to the parent. Therefore when you run `x.ChildObject.TopObject.ChildObject.TopObject` you are just navigating backwards and forwards between the same two objects.

Inclusion levels for a self referencing relationship such as Employee.Manager are interesting, but that isn't this scenario.

```
public class Employee
{
  public int EmployeeId { get; set; }

  public int ManagerId { get; set; }
  public Employee Manager { get; set; }
  public List<Employee> Reports { get; set; }
}
```
