### ISSUE TITLE
Null error when optional property is null

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#20469]
Followup to #20106

The following runtime error occurs when certain properties are null.

> SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

Since this involves hitting a database to see the error, I'm unsure what code to provide to illustrate the issue. Here are the parameters of the situation, though.

The model has no foreign keys and is hitting a view (by calling `ToView()` for the `DbSet` in `OnModelCreating()`. If I remove the fields from the model that can have null data from the database and from `OnModelCreating()` for this `DbSet`, the execution of the query by calling `ToListAsync()` runs fine. Otherwise, the error/exception occurs.

I don't have nullable reference types enabled, so I'm not sure why it would find an exception when an optional model property would have a null value (since all model properties are optional by default with nullable reference types disabled by default).

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: macOS 10.15.4
IDE: Visual Studio 2019 for Mac version 8.6 Preview 1 (8.6.0.3437)

**Comment by mrlife** [comment]
Hi, I'm really stuck on this. Are there situations where an optional property is not allowed to be null?

**Comment by ajcvickers** [comment]
@mrlife 

> since all model properties are optional by default with nullable reference types disabled by default

Value types (such as int, bool, decimal, etc.) are all required by default since they are not nullable. Make the property type `Nullable<T>` (e.g. int?, bool?, etc. in C#) if you need them to be optional.

**Comment by mrlife** [comment]
@ajcvickers Ah, it was the `DateTime` properties that needed to be made nullable. Thank you!

Since `DateTime` is in `System` I thought it would have been listed on this page in the Value Types listing: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#value-types. Would it make sense to include it on that page?

**Comment by ajcvickers** [comment]
@mrlife Adding it to that page makes sense to me, but I don't maintain those docs. I suggest you use the Feedback section of that page to make the suggestion.
