### ISSUE TITLE
Proposal: Linq studio for running Linq queries

### ISSUE THREAD

**Issue by ansarizafar** [dotnet/efcore#20486]
I propose Linq studio a Prisma studio https://github.com/prisma/studio like database IDE https://prisma.studio/preview?project=northwind for running Linq queries. This GUI will greatly help developers to view and edit data in  database without using sql queries. 

We can have a cli command for launching Linq studio

````
dotnet ef studio
````

**Comment by ajcvickers** [comment]
@ansarizafar It's unlikely that we will build this functionality into EF Core. However, we have a [documentation page for tools and extensions](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md) to which you could submit a PR to let others know about this.

**Comment by ansarizafar** [comment]
In my opinion Linq studio is a much needed missing piece and should be an official product. EF Developers will love it.
