### ISSUE TITLE
ParameterExpression.Name can be null but EF doesn't handle that

### ISSUE THREAD

**Issue by lukemurray** [dotnet/efcore#20485]
If you build an expression on a DbContext and execute it like so `lambdaExpression.Compile().DynamicInvoke(myArgs);` you will get an error if you create `ParameterExpression`s with no name. Which the API lets you do - `Expression.Parameter(typeof(MyType))`. But code in EF 3.1 (note 2.x worked) expects there is a name e.g.

```
if (target is ParameterExpression baseParameterExpression
                && baseParameterExpression.Name.StartsWith(CompiledQueryCache.CompiledQueryParameterPrefix, StringComparison.Ordinal))
```

in `EntityEqualityRewritingExpressionVisitor.cs` line 941.

This is EF 3.1.3.

Obviously I'm not building expression, but a library is, this one - https://github.com/lukemurray/EntityGraphQL

Yes I'll update to add names for all parameters, but if someone can create a `ParameterExpression` with a null name should EF handle that?

This is 1 place I found, but I guess it could be in many places?

### Steps to reproduce

Use the above library on 3.1. Or, not tested but should be something like 
``` C#
var p = Expression.Parameter(typeof(MyDbContext));
var prop = Expression.Property(p, "SomeRelation");
var lambda = Expression.Lambda(prop, new [] { p });
var result = lambda.Compile().DynamicInvoke(instanceOfDbContext);
```

### Further technical details

EF Core version: 3.1.3
Database provider: Npgsql
Target framework: .net core 3.1
Operating system: Mac OS
IDE: VS Code

**Comment by ajcvickers** [comment]
@lukemurray In general, we prioritize expression trees created by the C# compiler. This is because the problem space for expression trees is extremely large, so we necessarily need to restrict it where we can. That being said, since multiple expression tree generators are doing this, and it's something I think we can easily fix, we will look into doing so.

**Comment by lukemurray** [comment]
Thanks. That sounds good.

Note that the example above is written by hand in C# and therefore the compiler is generating the expression tree. I just based it on what was generated.

Is there a guide to getting this library compiling locally?

________________________________

**Comment by ajcvickers** [comment]
> therefore the compiler is generating the expression tree.

That's not what I meant. The C# compiler generates expression trees as it compiles code. This is the primary source for expression trees in queries, and theseare the compiler-generated expression trees I am referring to. In the code above, the C# compiler is compiling your code that then it is your code that manually builds the expression tree.

**Comment by xuzhg** [comment]
And a link: 
Many OData customers face the same issue at: http://github.com/odata/webapi/issues/2080

**Comment by smitpatel** [comment]
@ajcvickers - Do you want me to create PR against release/3.1 too?

**Comment by lukemurray** [comment]
@ajcvickers Sorry! I replied late at night via email. I thought I was replying to another issue else where. Ignore my message!

Still nice that it will be looked at. Thanks,
