### ISSUE TITLE
log the parameter value and data result and transaction begin/commit/rollback

### ISSUE THREAD

**Issue by athinboy** [dotnet/efcore#20484]
if there is solution,please let my know ,microsofo doc is so simply!

In a parallel system, It is possible that many threads  update/select/del some same  rows in a mysql table  parallelly. 

so ,sometimes the data changed weird, we need log to find problem .

so it is necessary to log the parameter value、data result and transaction begin/commit/rollback。

and ,thread number,transaction identifier(create by EF) is also import!
 
A option to switch it is best!

and log4net is good ,we can customize the style.

style like:

==> Preparing: select t1.id, t1.service_network_id from aaaa where record_id=? order by t1.create_time desc
==> Parameters: 4862918404433920(Long)
<== Columns: id, service_network_id
<== Row: 4862918404483072, 2981510004500480
<== Row: 4862918404597760, 2981510004500480
<== Total: 2

and log4net is perfered. people can customer the log style\output,and good performance!

thanks!

**Comment by athinboy** [comment]
and ,thread number,transaction identity is also import!
style like:

==>  Preparing: select t1.id, t1.service_network_id from aaaa where record_id=? order by t1.create_time desc 
==> Parameters: 4862918404433920(Long)
<==    Columns: id, service_network_id 
<==        Row: 4862918404483072, 2981510004500480
<==        Row: 4862918404597760, 2981510004500480
<==      Total: 2

**Comment by ajcvickers** [comment]
@athinboy See the [documentation on logging](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3). See the [Microsoft.Extensions.Logging.Log4Net.AspNetCore NuGet package](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Log4Net.AspNetCore/) for using this with log4net.

**Comment by athinboy** [comment]
sorry,My request is clutter . the key points are follow:
1、send results of select  command to ILogger.Log , and EnableSensitiveDataLogging to switch it.
we don't need worry about performance, the program tester perfer result  than saving time.
2、If EF create the transaction identifier ,send it to ILogger.Log when transaction begin/commit/rollback .

thanks,

**Comment by athinboy** [comment]
OK,maybe I should implement this with IDbCommandInterceptor/IDbTransactionInterceptor  .
