### ISSUE TITLE
EFCoreColumnOrder not working as expected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#20490]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/973562/efcorecolumnorder-not-working-as-expected.html)._

---
Hi Team,

I have crated Entity framework core - code first model application using core 3.1, but the column order annotaion is not taking entity fromwork core. can you plese invisticate and provide the solution.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by lajones** [comment]
Possible dupe of #10059
