### ISSUE TITLE
Optimistic concurrency for junction table

### ISSUE THREAD

**Issue by masaeedu** [dotnet/efcore#2049]
The documentation on concurrency states that optimistic concurrency can be enabled for an entity by creating and configuring an extra property in the model, which will correspond to a ROWVERSION column in the database. How can this be done for the junction table in a many to many relationship where the mapping entity is not explicitly managed?

If this is not possible, how can concurrent deletes of associations between entities that bear a many-to-many relationship to each other be carried out?

**Comment by divega** [comment]
The question doesn't seem relevant to EF7: Currently EF7 does not support many-to-many and when/if does there will be a "shadow entity" for the junction table. I have moved the issue to codeplex for EF6:

https://entityframework.codeplex.com/workitem/2738
