### ISSUE TITLE
Initializing type in constructor invalidates EF Core's Include() function

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/efcore#20500]
I have a states class:
``` C#
[DataContract(IsReference = true)]
public class State
{
	[DataMember]
	public string Name { get; set; }

	[DataMember]
	public List<Region> Regions { get; }

	public State()
	{
		Name = string.Empty;
		Regions = new List<Region>();
	}

	public State(string name)
	{
		Name = name;
		Regions = new List<Region>();
	}
}
```

And a regions class:
``` C#
[DataContract(IsReference = true)]
public class Region
{
	[DataMember]
	public string Name { get; set; }

	[DataMember]
	public List<County> Counties { get; }

	[DataMember]
	public List<Report>? Reports { get; }

	[DataMember]
	public State State { get; set; }
	public string StateId { get; set; }

	public Region()
	{
		Name = string.Empty;
		StateId = string.Empty;
		Counties = new List<County>();
	}

	public Region(string name)
	{
		Name = name;
		StateId = string.Empty;
		Counties = new List<County>();
	}
}
```

Every region should have a state and therefore `Region.State` cannot be null. I am using C#8 with the new nullable feature and I get a nice warning letting me know that my `State` property wasn't initialized. However, if I do initialize it as `State = new State();` in the class constructor, EF Core's `Include()` doesn't work on my GET request.
Is there a workaround to this? Can I have both or am I doing something wrong?

### Further technical details

EF Core version: 5.0.0-preview.2.20120.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4 Preview 2

**Comment by smitpatel** [comment]
Please see https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#non-nullable-properties-and-initialization

**Comment by BrunoBlanes** [comment]
Nice. So just to make sure I understand, a good way to go about this is to use a backing field and point that to EF Core while having my property initialized to that field, right?

**Comment by BrunoBlanes** [comment]
Yeah, got it. Thanks, you're the best.
