### ISSUE TITLE
Dbcontext OnConfiguring method generated by scaffold command.

### ISSUE THREAD

**Issue by ansarizafar** [dotnet/efcore#20526]
I am using following ef command to scaffold postgres db

````
dotnet ef dbcontext scaffold "connectionString" Npgsql.EntityFrameworkCore.PostgreSQL --schema tribe -o Data -f -c "ApplicationDbContext"

````
The scaffold command is generating ApplicationDbContext class with OnConfiguring mehod

````
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseNpgsql("connectionString");
            }
        }
````
Is it possible to tell scaffold command to stop generating OnConfiguring method. I don't need this method as I am  using 
````
    services.AddDbContext<ApplicationDbContext>(options =>
            options.UseNpgsql(Configuration.GetConnectionString("Postgres")));
````
in startup,cs file, Is it also possible to avoid following warnings in generated code? 

````
ApplicationDbContext.ApplicationDbContext()
Non-nullable property 'Tribes' is uninitialized. Consider declaring the property as nullable. [tribeserver]csharp(CS8618)
Non-nullable property 'Users' is uninitialized. Consider declaring the property as nullable. [tribeserver]csharp(

```

**Comment by ansarizafar** [comment]
I have found a solution for the warning issue but its inconvenient to edit all DbContext and entity classes properties to avoid warnings, every time we scaffold. It would be great If generated code fixed this issue automatically.
```
        public DbSet<Tribe> Tribes { get; set; } = default!;

````

**Comment by ErikEJ** [comment]
Latest daily build of EF Core Power Tools removes OnConfiguring completely (if you choose to not generate a connection string)

**Comment by ansarizafar** [comment]
@ErikEJ What about Non-nullable property warnings. Is this issue also fixed in Latest daily build? How can I install Latest daily build of EF Core Power Tools?

**Comment by ErikEJ** [comment]
I have no idea, you should probably share your project file. For the daily build, look at the readme in the Power Tools repo ( not an official Microsoft project)

**Comment by ajcvickers** [comment]
@ansarizafar Are you aware of the [name= ](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding#configuration-and-user-secrets) syntax for connection strings? Is this something you considered?

**Comment by ansarizafar** [comment]
@ajcvickers I have used name= syntax but still OnConfiguring method is generated by scaffold command. 

Is it there a way to avoid Non-nullable property is uninitialized warnings in generated code?

**Comment by ajcvickers** [comment]
@bricelam Is it required that OnConfiguring be used with the name= syntax?

**Comment by bricelam** [comment]
Well, we need to get the `Name=` connection string from somewhere. If you're manually handling it somewhere like Startup.ConfigureServices then we don't need to scaffold OnConfiguring

**Comment by ansarizafar** [comment]
@ajcvickers Scaffold is also generating an empty constructor which is causing an error.
````
   public ApplicationDbContext()
        {
        }

````
![image](https://user-images.githubusercontent.com/5788284/78755310-5961f700-7992-11ea-9b58-54876f26d8a5.png)

**Comment by ajcvickers** [comment]
@ansarizafar Scaffolding for nullable reference types is tracked by #15520.

**Comment by ajcvickers** [comment]
Notes from team discussion:
* We will provide an option to not generate OnConfiguring at all
* This should be coupled with clear guidance on using the name= syntax

**Comment by ajcvickers** [comment]
Linking to #19899, which is about the name= part.
