### ISSUE TITLE
Microsoft.EntityFrameworkCore.Cosmos as MongoDb Provider

### ISSUE THREAD

**Issue by aammfe** [dotnet/efcore#20536]
Cosmos Db Uses Same Wire protocol as  MongoDb then Why not Microsoft.EntityFrameworkCore.Cosmos can be use as just Mongodb Provider?

If there are some specifications just for CosmosDb other than Mongo Theoretically There should a MongoDb provider and Microsoft.EntityFrameworkCore.Cosmos should be on top of it. 

Please Care to Explain.

**Comment by JeremyLikness** [comment]
Hi @aammfe. Cosmos DB actually supports several APIs. The API that EF Core is built on is the SQL API. Mongo DB requires an entirely different provider. There are a few 3rd party providers available for EF Core over Mongo DB but it's an entirely different approach.

**Comment by damieng** [comment]
The official MongoDB EF provider is now available in preview https://github.com/mongodb/mongo-efcore-provider/
