### ISSUE TITLE
Entity Framework Core 3.1 Enum Conversion failed when converting the nvarchar value 'EnumValue' to data type int

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#20534]
I'm using Entity Framework Core 3.1 and trying to do a simple query on an enum property in my entity in my localdb and I keep getting this error:

> Enum conversion failed when converting the nvarchar value 'Accountant' to data type int

Entity:

```c#
public class DemoEntity
{
    [Key]
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public Position Position { get; set; }
}
```

Enum - Position:

```c#
public enum Position
{
    [Display(Name = "Accountant")]
    Accountant,
    [Display(Name = "Chief Executive Officer (CEO)")]
    ChiefExecutiveOfficer,
    [Display(Name = "Integration Specialist")]
    IntegrationSpecialist,
    [Display(Name = "Junior Technical Author")]
    JuniorTechnicalAuthor,
    [Display(Name = "Pre Sales Support")]
    PreSalesSupport,
    [Display(Name = "Sales Assistant")]
    SalesAssistant,
    [Display(Name = "Senior Javascript Developer")]
    SeniorJavascriptDeveloper,
    [Display(Name = "Software Engineer")]
    SoftwareEngineer
}
```

DbContext:
```C#
public class DemoDbContext : DbContext
{
    public DemoDbContext(DbContextOptions options)
        : base(options) { }

    public DbSet<DemoEntity> Demos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //var converter = new ValueConverter<Position, string>(
        //                    v => v.ToString(),
        //                    v => (Position)Enum.Parse(typeof(Position), v));

        //var converter = new EnumToStringConverter<Position>();

        modelBuilder
            .Entity<DemoEntity>()
            .Property(e => e.Position);
            //.HasColumnType("nvarchar(max)")
            //.HasConversion<string>();
            //.HasConversion(converter);
    }
}
```

I tried adding value conversions:

1. `.HasConversion<string>()` - didn't work
2. `.HasConversion(converter)` - didn't work

When I query the table as follows I'm getting the conversion error

```c#
try
{
    var test = await query.Where(x => x.Position.Equals(Position.Accountant)).ToListAsync();
}
catch (System.Exception e)
{
    //throw;
}
```

The `Position` is of type `NVARCHAR(MAX)` in my database. 

[![enter image description here][1]][1]

[![enter image description here][2]][2]

I modified the query to `query.Where(x => x.Position.Equals(Position.Accountant.ToString())).ToListAsync()`. Now the query executes but I get zero results.

Expected Result:

I should get one record from the database.

  [1]: https://i.stack.imgur.com/y9eSd.png
  [2]: https://i.stack.imgur.com/0jPdz.png

**Comment by fingers10** [comment]
After some analysis it looks like there is a bug in expression formation. I can see my coding breaking in EF Core 3.1.3 where as it was working in EF Core 2.2.6. 

I'm forming the expression dynamically in the run time and that works with EF Core 2.2.6 but breaks in EF Core 3.1.3. I'll share the expression formed in both version here in a day or two

**Comment by fingers10** [comment]
Here is what I have got.

`x.Position.Equals(Position.Accountant)` builds expression like `WHERE [d].[Position] = 0` instead of `WHERE [d].[Position] = N'Accountant'`.

But using `==` like `x.Position == Position.Accountant` builds correct expression.

Is this is the expected behavior? I need to use `==` instead of `Equals`?

**Comment by ajcvickers** [comment]
@fingers10 I'm not really following your comments about the expression building--are you referring to expressions EF is building, the compiler is building, or that you are building manually?

Looking at your original code, mapping the enum to a string is working for me. Note that you should still use the enum value in the query--EF will convert it to a string via the value converter.

```C#
public class DemoEntity
{
    [Key]
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public Position Position { get; set; }
}

public enum Position
{
    [Display(Name = "Accountant")]
    Accountant,
    [Display(Name = "Chief Executive Officer (CEO)")]
    ChiefExecutiveOfficer,
    [Display(Name = "Integration Specialist")]
    IntegrationSpecialist,
    [Display(Name = "Junior Technical Author")]
    JuniorTechnicalAuthor,
    [Display(Name = "Pre Sales Support")]
    PreSalesSupport,
    [Display(Name = "Sales Assistant")]
    SalesAssistant,
    [Display(Name = "Senior Javascript Developer")]
    SeniorJavascriptDeveloper,
    [Display(Name = "Software Engineer")]
    SoftwareEngineer
}

public static class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(
                new DemoEntity { Position = Position.IntegrationSpecialist },
                new DemoEntity { Position = Position.Accountant }
            );
            
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            var test = context
                .Set<DemoEntity>()
                .Where(x => x.Position == Position.Accountant)
                .ToList();

            Console.WriteLine(test[0].Position);
        }
    }
}

public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole()); //.SetMinimumLevel(LogLevel.Debug));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DemoEntity>().Property(e => e.Position).HasConversion<string>();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(Your.SqlServerConnectionString);
}

```

**Comment by fingers10** [comment]
@ajcvickers I'm referring to the expression formed by EF Core. In your above code, you're using `==` operator in your `.Where()` condition but if you use `.Equals()` then the result will be empty. We need to use `==` always instead of `.Equals()`?

**Comment by fingers10** [comment]
@ajcvickers You're welcome. I'm happy that I'm able to contribute by finding issues.
