### ISSUE TITLE
Query: Skip navigations and owned entities

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20551]
Currently we don't expand navigations to owned type in nav expansion since each provider could map owned type differently. This works fine for normal navigations since no navigation no expansion needed. Further, if owned entity has navigation to other type, there is still a navigation path from owner (which is the query root), which we can use to generate the FK properties.

When it comes to skip navigations, the navigations could be absent and gives us just set of FK. So underlying problems
- Do we expand skip navigation to owned type in it's component FKs? If we do how do we represent this in LINQ to transport to translation pipeline.
- How do we expand skip navigation defined on owned entity but pointing to regular entity?
  - If the association entity is regular entity then we can expand an FK to regular entity and cause chained expansion.
  - If the association entity is also an owned entity then we may not have a navigation to it always, that means we cannot expand the first FK in chain but we have to expand second FK in the chain since target type is regular entity.

**Comment by ajcvickers** [comment]
Note from team discussion: this doesn't seem very useful. If you're reading this and think it's something you need, then please up-vote and comment on why it is needed.
