### ISSUE TITLE
Can we use Attribute to define column comment?

### ISSUE THREAD

**Issue by zlzforever** [dotnet/efcore#20569]
We can config comment of Column/Table in the Configure method:

    public override void Configure(EntityTypeBuilder<Agreement> builder)
    {
        base.Configure(builder);
        builder.HasIndex("UserId", "Version").IsUnique();
        builder.HasComment("用户协议");
        builder.Property(x => x.Version).HasComment("协议版本");
    }

Is there an Attribute to config the comment like bellow?

    [Description("用户协议")]
    public class Agreement
    {
        [Description("版本号")]
        public string Version { get; private set; }
    }

**Comment by yuanxiongwei** [comment]
yes! when will it be available?
