### ISSUE TITLE
Creating a SelectExpression

### ISSUE THREAD

**Issue by bdebaere** [dotnet/efcore#20564]
I'm trying to port my custom code from EntityFrameworkCore 2.2 to EntityFrameworkCore 3.1. The code in question creates an ExistsExpression with a subquery. The result I am after is `EXISTS(SELECT 1 FROM [TableValuedFunction])`, which I was able to achieve with version 2.2.

The code I'm porting is below.
```csharp
                    var subquery = this.selectExpressionFactory.Create(this.queryModelVisitor.QueryCompilationContext);
                    subquery.AddTable(new CustomTableExpression());
                    var existsExpression = new ExistsExpression(subquery);
```

What I've come up with is below.
```csharp
                    var entityType = this.model.FindEntityType(typeName);
                    var subQuery = this.sqlExpressionFactory.Select(entityType);
                    subQuery.AddTable(new CustomTableExpression());
                    var existsExpression = this.sqlExpressionFactory.Exists(subQuery, false);
```

However, there is no AddTable on the new SelectExpression. And the constructor I really want to access is private. The constructor in question is below.

```csharp
        private SelectExpression(
            string alias,
            List<ProjectionExpression> projections,
            List<TableExpressionBase> tables,
            List<SqlExpression> groupBy,
            List<OrderingExpression> orderings)
```

I've successfully managed to port all other custom code I had. Of course I can adjust stuff here and there to make it work, but I'd prefer to keep this approach I currently have as it is rather clean in my opinion.
Any suggestions are welcome!

**Comment by smitpatel** [comment]
Does `TableValuedFunction` return an entityType?

**Comment by bdebaere** [comment]
@smitpatel I'm not 100% sure what you mean by that, but TableValuedFunction (https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/how-to-use-table-valued-user-defined-functions) behaves like a table.

**Comment by smitpatel** [comment]
Whatever data `TableValuedFunction` returns from server, does it constitute a shape of an EntityType?
For example, when you have a `Blog` entity in your model, the data in table `Blogs` would represent the shape of Blog entity (not the literal blogs).

**Comment by bdebaere** [comment]
@smitpatel No, it would be untyped, like the result of https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver15.

**Comment by smitpatel** [comment]
Using this method by passing `(SqlExpression)null`
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.isqlexpressionfactory.select?view=efcore-3.1#Microsoft_EntityFrameworkCore_Query_ISqlExpressionFactory_Select_Microsoft_EntityFrameworkCore_Query_SqlExpressions_SqlExpression_

It will create `Select 1`
Then you can add your custom TableExpression and wrap the subquery into ExistExpression.

**Comment by bdebaere** [comment]
@smitpatel Okay thank you, but sir, that takes me halfway there. How can I add the custom TableExpressionBase to the SelectExpression? SelectExpression.AddTable is unavailable.

**Comment by smitpatel** [comment]
In that case, just use `SqlFragmentExpression` we don't support Select over a tableExpression which does not represent EntityType yet.
