### ISSUE TITLE
Consider making AnonymousObject public

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20565]
In-memory provider uses it.

**Comment by smitpatel** [comment]
Even relational does. typeof(AnonymousOjbect) is not caught in analyzers.

**Comment by smitpatel** [comment]
Though I would recommend on the side of not making it public. It has potential of being misused.

**Comment by ajcvickers** [comment]
@roji `typeof()` seems to be another case of #20206.

**Comment by roji** [comment]
@ajcvickers added this to #20206, thanks.
