### ISSUE TITLE
I have an InvalidCastException despite using EF Core HasConversion

### ISSUE THREAD

**Issue by FrancoisM** [dotnet/efcore#20586]
While I use a conversion for a property, basic queries that use that property as a parameter fail.
There already is a [StackOverflow](https://stackoverflow.com/questions/61127859/i-have-an-invalidcastexception-despite-using-ef-core-hasconversion) issue open.

### Steps to reproduce

Here is a [repro ](https://github.com/FrancoisM/EfCoreIssue) with a test that passes in memory but fails with a local db.

### Further technical details

EF Core version: 2.1.3 and 2.2.6 (it works ok with 3.1.3 but I cannot migrate to version 3)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp 2.1
Operating system:
IDE: Visual Studio 2019 16.4.1

**Comment by FrancoisM** [comment]
I personally managed to migrate to net core 3 and I'm not impacted by the issue anymore.
I don't know if it needs to be closed though as I don't know if you maintain version 2.

**Comment by ajcvickers** [comment]
Closing since 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/) and the bar for fixing anything in 2.1 is very high.
