### ISSUE TITLE
System.InvalidOperationException: The property 'SomethingID' on entity type 'SomeEntity' has a temporary value while attempting to change the entity's state to 'Modified'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/efcore#20581]
I have an Entity which is defined as so:

```
public class MyEntity
{
   [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
   public int EntityId {get; set;}
   public bool IsActive {get; set;}
}

```

I have some code which either adds or modifies instance of `MyEntity` depending on the logic required in the program. But on ANOTHER INSTANCE of the same `DbContext`

e.g. I use one instance of the context to load the entity and another to update it later on only if necessary.

i.e.

```
//cachedEntities is a list previously loaded from a different context than `db` below
var someEntity = cachedEntities.Where(e=>e.EntityId == 1);

if(null == someEntity)
{
   //Logic to insert
  db.MyEntities.Add(new MyEntity{...});
}else{
  //Logic to update
  someEntity.IsActive = false;
 db.MyEntities.Update(someEntity);
}
```
Exception is in the Title and the Stack Trace is as follows:

> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Update(TEntity entity)

### Further technical details

EF Core version: 3.1.3
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET Core 3.1.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 Version 16.4.6)

**Comment by lajones** [comment]
@juliusfriedman There are a couple of problems:

1) The error message is complaining about a property called `SomethingID` on `SomeEntity` - but your code above doesn't include either of these?

2) But from what you wrote I think you just don't need to call `Update()` there. Please see these blog posts explaining when to call and when not to call `Update()` and what the consequences are of doing so.

https://blog.oneunicorn.com/2020/01/17/dontcallupdate/
https://blog.oneunicorn.com/2020/01/18/docallupdate/

**Comment by juliusfriedman** [comment]
I used those examples because I can't really share the code which I am using in my project because it is work related and not owned solely by myself.

Thank you for the Blog posts, I have just finished reading them....

Long story short, I first use the context to load the entities at the beginning of the program. I then use a different context to update them because the original context is no longer in scope.

From the examples you posted it seems that perhaps I need to use `Attach` and then `SaveChanges` for such cases?

I will give that a try and see if helps but the funny thing is that this does not always occur, there are certain cases where multiple entities are being updated when this does occur reliably and is the source of reason I created this issue.

I will give a try with some different logic e.g. using `Attach` and calling save changes and see how that goes but I won't be able to post an immediate update as the dataset which causes the exception takes about 5 hours to run (maybe a little less)

Any other advice you could provide in interim would be helpful or if you need additional information please let me know the best way to share such without having to provide the same exact code I use in the program.

If I find a work around I will update this thread and close the issue.

Thank you for your time.

**Comment by juliusfriedman** [comment]
What I can say immediately is that on smaller datasets which I have tried it seems that just performing a select from the new context, modifying the property and then calling `SaveChanges` seems to work so this might be something related to using one context to select the entity and another to update it.

If that makes more sense please let me know.

**Comment by lajones** [comment]
@juliusfriedman Well, there is a trade-off, as mentioned in the blogs.

If you're going to use `Attach()` then the framework will only update the properties that it knows have been updated after the `Attach()` call (see especially the discussion in the blogs about setting a property to `null`) - so your code will need to make sure that all the other properties are as you expect them. `Update()` means update _all_ of the properties of a given entity.

The error you're getting seems to indicate that you're trying to update an entity, but a primary (or maybe some other) key is not set when it should be. Remember you must have a primary key set to identify which entity you are updating. 

A small project exemplifying the problem is the best way for us to repro the situation and help you out.

**Comment by juliusfriedman** [comment]
The thing is my entities key property is defined with the correct attributes:

> [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]

And if it exists would already imply that it has a primary key. 

I am not updating the primary key as it would have already been assigned for me to select it out of the database in the first place....

For me to take the time and see if I can repo this outside of my work code I would need you to provide me a quick example of what your looking for...

i.e. can I just take the simple `BloggingContext` examples and modify them to attempt to manifest the issue as I describe above by using 1 instance of the `BloggingContext` to select a few `Blogs` and then another instance later on to perform the update logic?

Hopefully that would be sufficient.

**Comment by lajones** [comment]
Sure. That sounds good.

**Comment by juliusfriedman** [comment]
Here is the simplest program I can come up with:

```
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleAppEfCoreRepo
{
    public class User
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public DateTime ModifiedDate { get; set; }
    }

    public class UserContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=IX2086;Initial Catalog=UserRepoTest;Connect Timeout=60;Integrated Security=true;");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {

            //We are going to store users are they are created
            List<User> createdUsers = new List<User>();

            //Use the context
            using (var db = new UserContext())
            {
                //Ensure we can create the database
                if(false == db.Database.EnsureCreated())
                {
                    throw new InvalidOperationException("Cannot create the database!");
                }

                //Loop to make some users
                for(int i = 0; i < 1_000; ++i)
                {
                    //Allocate the User
                    var newUser = new User
                    {
                        Email = string.Join('@', i, Environment.MachineName),
                        IsActive = true,
                        ModifiedDate = DateTime.UtcNow
                    };

                    //Not sure what the use of the EntityEntry is but that's not a core issue here
                    var addedUser = db.Users.Add(newUser);

                    //I store the newUser
                    createdUsers.Add(newUser);
                }

                //Determine how many rows were effected
                int effectedRows = db.SaveChanges();

                //Ensure all users created were inserted
                if(effectedRows != createdUsers.Count)
                {
                    throw new InvalidOperationException("Not all users were added!");
                }
            }

            //Make a new context to do processing
            using (var db = new UserContext())
            {
                //For keeping track of what was modified or inserted
                int modifiedUsers = 0, insertedUsers = 0;

                //Loop each created user and determine if modification is necessary
                foreach (var user in createdUsers.ToArray())
                {
                    //If the UserId is odd
                    if ((user.UserId & 1) == 1)
                    {
                        //Disable the user
                        user.IsActive = false;

                        //Set ModifiedDate
                        user.ModifiedDate = DateTime.UtcNow;

                        //Not sure of the use of...
                        var updatedUser = db.Users.Update(user);

                        //keep track of the users modified
                        ++modifiedUsers;
                    }
                    else //We will add a new user  
                    {
                        //Allocate the User
                        var newUser = new User 
                        {
                            Email = string.Join('@', createdUsers.Count + 1, Environment.MachineName),
                            IsActive = true,
                            ModifiedDate = DateTime.UtcNow
                        };

                        //Not sure of how this is useful...
                        var addedUser = db.Users.Add(newUser);

                        //Add to the cache
                        createdUsers.Add(newUser);

                        //Keep track of inserted users
                        ++insertedUsers;
                    }
                }

                //Save changes to the database (inserting 5 and updating 5)
                int effectedRows = db.SaveChanges();

                //If the number of effectedRows is not as expected throw
                if(effectedRows != modifiedUsers + insertedUsers)
                {
                    throw new InvalidOperationException("Not all users were inserted or modified");
                }
            }

            System.Console.WriteLine("Test passed!");

            using(var db = new UserContext())
            {
                if(false == db.Database.EnsureDeleted())
                {
                    throw new InvalidOperationException("Cannot delete the database");
                }
            }
        }
    }
}

```

However after running this program for quite a few times I cannot replicate the behavior I am seeing in my real program.

The only major difference is that my entities have relations to other entities so I can attempt to add something like that to the example and try again but the flow of the program would be the same as I am not updating the related entities only a few properties local to the entity itself.

Please let me know if I can make this any clearer.

**Comment by juliusfriedman** [comment]
The large dataset completed so I am going to close this issue for now.

I worked around my issue by selecting for the cached entity from the db and performing the update without using `Update` so perhaps the issue was with update... 

Thank you anyway for your time.
