### ISSUE TITLE
Support for Cosmos provider camelcase JsonSerializer settings 

### ISSUE THREAD

**Issue by xxeasterxx** [dotnet/efcore#20588]
There is currently no option to indicate camelcase json serializer settings in options builder for Cosmos. Understand there's a .ToJsonProeperty() but it's tedious to do for every properties and it seems like we can't use Tojsonproperty for List object.

**Comment by ajcvickers** [comment]
This is similar to changing the column mapping convention for relational database providers. Public conventions, tracked by #214, would make this possible. It could also be done in an extension similar to https://github.com/efcore/EFCore.NamingConventions. As with the relational version, it's not something we are planning to pull into the main codebase.
