### ISSUE TITLE
FromSqlInterpolated Pasing Parameters

### ISSUE THREAD

**Issue by rajansoft2** [dotnet/efcore#20594]
IT throw Exception {"Must declare the scalar variable \"@p0@p1\"."
```C#
public async Task<List<T>> FromSqlInterpolated(string commandText, DbParameter[] parameters)
        {
                string commandParam = string.Join(",",parameters.Select(a => a.Value ).ToList());
                List<T> result = await dbContext.Set<T>().FromSqlInterpolated($"{commandText}{commandParam}")
                    .AsNoTracking()
                    .ToListAsync();
                return result;
        }
```
### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@rajansoft2 `FromSqlInterpolated` is intended to allow _SQL parameters_ to be declared inline. It can't be used for items that will not form SQL parameters. See documentation here: https://docs.microsoft.com/en-us/ef/core/querying/raw-sql
