### ISSUE TITLE
System.InvalidOperationException: 'There is already an open DataReader associated with this Command which must be closed first.'

### ISSUE THREAD

**Issue by HashemGo** [dotnet/efcore#20598]
System.InvalidOperationException: 'There is already an open DataReader associated with this Command which must be closed first.'

### Steps to reproduce
One To Many Relationship

int Count = db.Table.Count(x => x.IdFK == anyId); 

there is no data in the Table yet it should return Count = 0;

Microsoft.EntityFrameworkCore.SqlServer 3.1.3

**Comment by HashemGo** [comment]
I just found the previous line
var List = db.ParentTable.OrderByDescending(x => x.Id);

after add to .ToList() the error is gone 
var List = db.ParentTable.OrderByDescending(x => x.Id).ToList();

I don't know if this a bug or note I don't know about it
anyway thanks

**Comment by ajcvickers** [comment]
@HashemGo SQL Server can only consume one result set at a time by default. You can enable [Multiple Active Result Sets (MARS)](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/enabling-multiple-active-result-sets) support in the connection string if needed.
