### ISSUE TITLE
Strongly typed ids with database generated values / or High-Low sequence generated values

### ISSUE THREAD

**Issue by davidroth** [dotnet/efcore#20591]
Hi,

I am prototyping with using strongly typed ids for primary keys for a ddd model. It works with client side generated Guids but I would like to make it work by using integer ids, generated by DB using Identity insert or High Low sequence:

```csharp
public readonly struct OrderId : IComparable<OrderId>, IEquatable<OrderId>
{
    public int Value { get; }
    public OrderId(int value) => Value = value;
    // ... Equals, GetHashCode, Operators, etc.
}

public class Order
{
    public OrderId Id { get; private set;}
    public Order() {}
}

public class OrdersContext : DbContext
{
    public DbSet<Order> Orders => Set<Order>();
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.Entity<Order>(b =>
            {
                b.HasKey(x => x.Id);
                b.Property(e => e.Id)
                  .HasConversion(number => number.Value, s => new OrderId(s))
                  .UseIdentityColumn() // Exception: Identity value generation cannot be used for the property 'Id' on entity type 'Order' because the property type is 'OrderId'. Identity value generation can only be used with signed integer properties.
                  .UseHighLow() // Exception:SQL Server sequences cannot be used to generate values for the property 'Id' on entity type 'Order' because the property type is 'OrderId'. Sequences can only be used with integer properties.
                  .ValueGeneratedOnAdd(); // Exception:Value generation is not supported for property 'Order.Id' because it has a 'ValueConverter<OrderId, int>' converter configured. Configure the property to not use value generation using 'ValueGenerated.Never' or 'DatabaseGeneratedOption.None' and specify explicit values instead.
            });
    }
}

```

I would like to use identity insert or high low value generation for the `Order.Id` property. Basically the default behavior as if `Order.Id` would be a typical `int` property:

```csharp
public class Order
{
    public int Id { get; private set;}
    public Order() {}
}
```

Is there a possibility to make this work at the moment via a workaround?
If not, then this may be the first feature request to support such a scenario.

**Comment by ilmax** [comment]
Hey @davidroth I've also looked into this in the past, have a look at [here](https://github.com/dotnet/efcore/pull/18123)

**Comment by davidroth** [comment]
Thanks for the info @ilmax! Are you still working on new MR supporting this scenario?

For EF-Team:
So it looks my issue here is a duplicate of https://github.com/dotnet/efcore/issues/11597 and https://github.com/dotnet/efcore/issues/20125.

Feel free to close if you think so ;-)

**Comment by ilmax** [comment]
@davidroth I would love to get the this feature in, but I'm not doing anything atm and also is not clear if the team would accept such a contribution as per [this](https://github.com/dotnet/efcore/pull/18123#issuecomment-536358802) comment. 
It would be great to have this clarified so we can implement this one

**Comment by ajcvickers** [comment]
@davidroth @ilmax There is a design proposal here: https://github.com/dotnet/efcore/issues/11597#issuecomment-542832484. We would certainly love to have a good community PR that implements and test this. That being said, it's not a simple 1-hour PR. In particular, there is a considerable amount of testing needed since there are many dimensions in play here.
