### ISSUE TITLE
EF.CompileQuery parameters

### ISSUE THREAD

**Issue by shivakumarb1989** [dotnet/efcore#20606]
Currrently EF.CompileQuery supports 5 parameters for querying. 

Having said this the EF does not support client evaluation, passing a class as a parameter to EF.CompileQuery throws (limitation / client evaluation) a bug. 
I would like to understand if i can achieve atleast 12 parameters(by overloading/extending) the EF.CompileQuery for querying. 
Is there any way that we can support more parameters. Or are their any work arounds to acheive this feature.

In future releases are you guys planning to support more parameters? Please let me know your thoughts.

Thanks a lot.

**Comment by ajcvickers** [comment]
@smitpatel Why do we only have API for up to five parameters?

**Comment by ajcvickers** [comment]
Notes from team discussion:
* Add more TParam overloads--up to at least 15
* Add params object array support for more parameters

**Comment by shivakumarb1989** [comment]
Hi @ajcvickers @smitpatel , Could you please provide any documentation of EF.CompileQuery examples if any? Many Thanks.

**Comment by smitpatel** [comment]
> Add params object array support for more parameters

**Comment by AndriySvyryd** [comment]
> @dotnet/efcore - Can someone explain? An example of API?

```C#
        public static Func<TContext, <#= paramsList #>object[], IEnumerable<TResult>> CompileQuery<TContext, <#= paramsList #>TResult, TProperty>(
[NotNull] Expression<Func<TContext, <#= paramsList #>object[], IIncludableQueryable<TResult, TProperty>>> queryExpression)
            where TContext : DbContext
```

**Comment by smitpatel** [comment]
Without true funcletizer it does not work in current implementation.
Using 3.1 packages, below fail because we cannot translate ArrayAccess over a parameter.
```C#
                var query = EF.CompileQuery((MyContext context, object[] parameters)
                    => context.Blogs.Where(b => b.Id == (int)parameters[0]));

                query(db, new object[] { 1 }).ToList();
```

**Comment by shivakumarb1989** [comment]
Woah! I can see there is a pull request for 15 parameters. When can we expect this to be published @smitpatel , thanks. :)

**Comment by shivakumarb1989** [comment]
Hi @ajcvickers , @smitpatel . is this feature going to be released in any of the EF core 3.1.x versions? This is something we are looking for in our project. Many thanks.

**Comment by AndriySvyryd** [comment]
@shivakumarb1989 3.1.x only contain critical bug fixes. All implemented featured will be released in 5.0.0

**Comment by shivakumarb1989** [comment]
Ok cool. Thanks for the update @AndriySvyryd

**Comment by shivakumarb1989** [comment]
Hi All, One last question. Could we combine multiple EF.CompileQueries? to achieve more parameters. Or is there a work around for this in 3.1.x? many thanks.

**Comment by smitpatel** [comment]
Work-around would involve adding additional method in the own code.
Add a static method in your own code like one of this. Difference between all 3 method is ending. If your lambda ends with result of type IQueryable or scalar/single result or ends with include. You only need to add the method you are using.
https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore/EF.CompileQuery.cs#L268-L321

The implementation of method uses https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore/Query/Internal/CompiledQuery.cs class, just derive from it, add Execute method with number of parameters you need and use that in implementation. CompiledQuery.cs is in Internal namespace so it can break between releases. But it should work for release/3.1. From 5.0 you wouldn't need a work-around.

**Comment by shivakumarb1989** [comment]
Great. Many thanks @smitpatel . Will try that.
