### ISSUE TITLE
Includes() with string throws not finding navigation path exception when type T is derived

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#20609]
Is it possible to have Includes() using strings not throw an exception when a derived type is passed in that doesn't have a specific navigation property? My use case is a generic method that will eager-load all navigation properties for one hierarchy. I'm using OfType<T>() and having to set the DbSet to the base type as a workaround but it seems redundant since DbSet<T> already defines the type and OfType should be unnecessary. Using `Include` with public navigation properties (e.g., `Include(p=> ((ClassA)p).SubA)`) works but these navigations are configured as private fields/private properties. This will likely go away when https://github.com/dotnet/efcore/issues/2953 is resolved.

For example, 

```c#

public class BaseClass
{
public string Id {get; set;}
}

public class ClassA : BaseClass
{
public SubA SubA {get;set;}
}

public class ClassB : BaseClass
{
public SubB SubB {get;set;}
}

public class ClassC : BaseClass
{
public SubA SubA {get;set;}
public SubC SubC {get;set;}
}

context.Set<T>().Include("SubA").Include("SubB").Include("SubC").ToList(); //exception thrown navigation not found when T is derived/concrete. Works if T is 'BaseClass'

context.Set<BaseClass>().Include("SubA").Include("SubB").Include("SubC").OfType<T>().ToList(); //works but the oftype call appears to be redundant and having to set the baseclass on Set<T>() weakens the use of generics
```

### Further technical details

EF Core version: 5 preview 3 daily
Database provider: Mssqlocaldb
Target framework: .NET 5
Operating system: Win 10
IDE: Visual Studio 2019 Preview

**Comment by maumar** [comment]
converted the error to use logging infra instead of just throwing. The behavior can be configured so that the exception is not thrown when the error occurs (although by default it is still thrown).
event id: CoreEventId.InvalidIncludePathError
