### ISSUE TITLE
Migration trying to drop the 'Discriminator' column even if it doesn't exist

### ISSUE THREAD

**Issue by developerMCSI** [dotnet/efcore#20601]
Similar to issue #20410 
I use efCore 3.1.3

I'd like an "AllSeller" class to read all the records in the table and a class for each entity subtype (NotDefinedSeller,AreaManager,Seller).
So I have defined a class "AllSeller" with table name "CrmSellers".
I derived the "NotDefiniedSeller","AreaManager", "Seller" classes from it.
I have defined the field "SellerType" as discriminator.
The first migration is correct, but with each subsequent migration I always get the "drop column of field Discriminator" that doesn't exist.

I'll try to use ".HasBaseType((Type)null)" to remove an entity type from the hierarchy,but without success.
I'll try to use ".HasNoDiscriminator()" to force not to use the discriminator, but this command appears to be only for CosmosDB.

I see in DbContextModelSnapshota.cs
 modelBuilder.Entity("efcoretest.AllSeller", b =>
                { …
                    b.HasDiscriminator();   // <- THIS WRONG
                });

If I comment this row and I add a new migrations the migration is empty, without the wrong command of "drop column of field Discriminator"

At this point I think my code is correct and there is a bug in efCore migration.

Can you check it and add **3.1.4** as **milestone**?
Thanks

### Steps to reproduce
1) Clone the attached solution with my code.
[efcoreDiscriminator.zip](https://github.com/dotnet/efcore/files/4464177/efcoreDiscriminator.zip)
2) dotnet ef migrations add NewMigration
3) View the .\Migrations*_NewMigration.cs migration file.

### Further technical details
EF Core version: efcore 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win10 64x
IDE: Visual Studio 2019 16.5.3

**Comment by ajcvickers** [comment]
@developerMCSI I'm not sure I'm following what you are trying to do. Why would a type in the middle of a mapped inheritance hierarchy not have a discriminator? Each type in a mapped hierarchy will use the same discriminator column.

**Comment by developerMCSI** [comment]
This table is populated by an external application.
I need both to read all the data in the table (AllSeller) and at the application domain level I must be able to see the data as two different entities (AreaManager, Seller).

If I use TPH when I want all the sellers I should do AreaManager union Seller.

To avoid this I created the AllSeller class and then with an intermediate BaseSeller class block the hierarchy and resume it for AreaManager and Seller. By doing this I saw that efcore add-migration creates a "Discriminator" field for the AllSeller class too.
My current workaround is to have defined a "FakeDiscriminator" field used as a discriminator by AllSeller and a "SellertType" field used as a discriminator by AreaManager and Seller.
So all records have the field FakeDiscriminator = "AllSeller" and the field SellerType with "AreaManager" or "Seller" according to the type of entity.

I wish I could have a class for direct access to the table (as RAW read), but keep the two domain entities. How do I do it?

In any case, returning to the reported bug, the "Add-migration" command generates an incorrect migration as it creates a "Drop-Column" command at each migration that should not be present.

**Comment by ajcvickers** [comment]
> This table is populated by an external application.

Does the table have a discriminator column?

**Comment by developerMCSI** [comment]
> This table is populated by an external application.
> 
> Does the table have a discriminator column?

The table does not have a discriminator column.

Have you seen the attached code? Have you tried doing a new migration?

**Comment by ajcvickers** [comment]
@developerMCSI If you are using TPH mapping with a table, then that table must have a discriminator column. Otherwise EF has no way of determining the type represented by each row. Without a discriminator column, you can't map a hierarchy to that table.

**Comment by developerMCSI** [comment]
@ajcvickers Yes, of course, but why does EFCore add a drop column in the migration?
Have you tested my sample code?

**Comment by ajcvickers** [comment]
@developerMCSI Yes, I have. However, I'm trying to access the priority of fixing this bug, and given that it only seems to happen in a scenario that won't work anyway, then the priority is looking very low at the moment.

**Comment by developerMCSI** [comment]
I applied a workaround to no longer have the drop column in the migration, but in my opinion the bug is the same as # 20410

**Comment by ajcvickers** [comment]
@developerMCSI If you think this is a duplicate, then I will just close this as a duplicate and we don't need to investigate anymore. I was assuming that you thought it was similar but not a duplicate, otherwise there is no point in having a new issue for it.
