### ISSUE TITLE
Multiple level eager loading with lazy loading model

### ISSUE THREAD

**Issue by iuridosanjos** [dotnet/efcore#20626]
I've already saw many issues created about querying multiple levels no EF Core 3.x and someone posted this [possible solution](https://gist.github.com/smitpatel/d4cb3619e5b33e8d9ea24d3f2a88333a), but it's not working when you use LazyLoadingProxies.

### Context
I have a model that supports lazy loading on some properties and I want to load all the properties usnig an eager load, so (in this case) nothing gets loaded on demand.

### Problem
All the data that are eager loaded after the first query are not being considered as already loaded when the properties that supports lazy loading gets accessed, making them to be loaded again by LazyLoader.

I've used SQL Server Profiler to check all the queries running on the database. It shows the eager loads queries are correct, but when the properties that are supposed to be loaded on the second+ queries are accessed, it shows additional queries loading specific properties/values on demand.

### What I expect
All eager load done on multiple queries got tracked on the DBContext and got reused on the LazyLoader.
Whenever I access the data that are already loaded (eager loaded) on the DBContext gets reused and not (re)loaded on demand.

### Example/Reproduce
I'll consider the example of the [possible solution](https://gist.github.com/smitpatel/d4cb3619e5b33e8d9ea24d3f2a88333a) as the same example here, specifically talking about the "Tracking & Buffering" part of it.

```
var query = db.Customers.Include(c => c.Address);
var result = query.ToList();
query.Include(c => c.Orders).ThenInclude(o => o.OrderDiscount).SelectMany(c => c.Orders).Load();
query.SelectMany(c => c.Orders).SelectMany(o => o.OrderDetails).Load();
```

If Customer.Address, Orders.OrdersDiscount and Orders.OrdersDetails are all lazy loading (simply add _virtual_ to all properties and configure EF Core to _UseLazyLoadingProxies_), we get the following result, line by line:

```var query = db.Customers.Include(c => c.Address);```
```var result = query.ToList();```
Loads normally in a single select, Address will be eager loaded and NOT lazy loaded

```query.Include(c => c.Orders).ThenInclude(o => o.OrderDiscount).SelectMany(c => c.Orders).Load();```
Orders and OrdersDiscount will be loaded on this line, but whenever it's acessed in the result (eg: _result[0].Orders[0]_) it gets loaded AGAIN (lazy loaded), but it was already eager loaded before. Seems like Tracking was lost or something like it.

```query.SelectMany(c => c.Orders).SelectMany(o => o.OrderDetails).Load();```
Same happens here when OrderDetails try to be eager loaded, but whenever we access it via result (eg: _result[0].Orders[0].OrderDetails[0]_) it gets loaded AGAIN (lazy loaded).

It seems that all the eager loading that's done after the first query are not being tracked so the lazy loader can reuse and not load them again.

Any advices? Am I doing something wrong?

### Additional Information
EF Core Version tested here: 3.1.3
SQL Server Version: SQL Server 2019
Using .NET Core 3.1

### UDPATE
After digging into the problem and with the help of @smitpatel , I did achieve to use a work-around setting the _CollectionEntry_ of the property to _IsLoaded=true_, so it's lazy-loading don't get triggered. However I think that EF Core itself should work on this case, understanding that the property is fully loaded as it was eager-loaded before.

Maybe further updates from EF Core that will possibily resolve the "queries data explosion" on includes with 1:n and n:n relationships update from version 2.x to 3.x will also resolve this problem. Maybe when EF Core successfully manages to properly handle all the loading it can update the metadata properly and eager-loads can be used with lazy-loads without the needs of a workaround.

**Comment by ajcvickers** [comment]
`Load` cannot mark collections as loaded by default because there is no guarantee the query didn't do filtering, or some other way return results that don't match the fully loaded question. The correct thing to do is mark the collections as loaded--as in the workaround above--if you know that all entities have been loaded or otherwise want to treat the collection as fully loaded.
