### ISSUE TITLE
Trigger for Timestamp automaticaly generated by SQLite provider

### ISSUE THREAD

**Issue by HovorkaJan** [dotnet/efcore#20625]
I am writing application tests using SQLite database and I would like the same "_[Timestamp]_ annotation" behavior like on SQL server. 

There is a trigger _SetStatusTimestamp_ created in https://github.com/dotnet/efcore/issues/12260 which provides the same functionality. I want to ask if it would be possible to generate such a trigger automaticali by _Add-Migration_ script for SQLite provider if Entity field has _[Timestamp]_ annotation (or _IsRowVersion()_ is used in Fluent API).

**Comment by bricelam** [comment]
Implementing #2195 would be a lot simpler

**Comment by ajcvickers** [comment]
Notes from team discussion: With regard to this specific scenario, we believe that it is best covered by #2195. Also, #10770 is an issue on the backlog for trigger management in the model/migrations.
