### ISSUE TITLE
Query: We should throw when accessing non-nullable property over a null-value entity in the projection

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#20633]
query:

```cs
ctx.Gears.Select(g => g.AssignedCity.Name.Length);
```

assuming assigned city can be null, we should throw "nullable object must have a value" (or ideally something more meaningful).

Currently we return default(int) - it might not be what user expected.
Casting result to nullable will yield correct result (and would get rid of the exception in the future)

```cs
ctx.Gears.Select(g => (int?)g.AssignedCity.Name.Length);
```

**Comment by maumar** [comment]
Note: in 2.1 we had this behavior, which we changed in 3.1

**Comment by ajcvickers** [comment]
Notes from team discussion: we should do this alongside the other related change such that `Sum` queries still return correct values. Then I don't think this is a breaking change because it is only changing the result in places where it was previously wrong.
