### ISSUE TITLE
Regression in model building perf

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20672]
![image](https://user-images.githubusercontent.com/1430078/79614482-7e9ee580-80b5-11ea-8853-d246b30b7933.png)

**Comment by AndriySvyryd** [comment]
Fixed in d788e06ee73b83674099325d1988469f4f6ac720

![Untitled picture](https://user-images.githubusercontent.com/6539701/129991391-a428acc8-1230-4c29-bbff-d1b6bee1dfed.png)
