### ISSUE TITLE
Add Support for CosmosSerializationOptions in the Cosmos Provider

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/efcore#20670]
Enabling features like indented JSON documents and ignoring a property when null. By setting "IgnoreNullValues" to true, for example, properties will not be serialized when null (as opposed to serializing the property with a value of null).

When configuring the DbContext, allow configuration options based on CosmosSerializationOptions. Currently these are:

IgnoreNullValues
Indented
PropertyNamingPolicy

https://docs.microsoft.com/dotnet/api/microsoft.azure.cosmos.cosmosserializationoptions

**Comment by ajcvickers** [comment]
Note from triage: this needs to be done in conjunction with or after #17306. It may not be needed if configuring the serializer and is options is sufficiently easy.

**Comment by ajcvickers** [comment]
Covered by configuration of the serializer after #17306 is implemented.
