### ISSUE TITLE
Class with one owned property generates extra table instead of appending to TPH table

### ISSUE THREAD

**Issue by michielpeeters** [dotnet/efcore#20688]
Hello, 

**Observed behaviour:**
I'm working in a project which uses TPH and Owned classes. Now I'm adding a new class to the TPH hierarchy and I have created a new Owned class. This owned class is one-time used in the new TPH class. When I generate a migration somehow it detects to add an additional table instead of appending it to the existing TPH table. When I add an additional property (as type: the owned class) in the TPH class it starts suddenly appending the properties (as expected) to the TPH table. So the main question is how can I add a single owned property which also generates a correct migration (which appends the owned class to the base table instead of creating a new table)?

**Expected behaviour:**
When adding one owned property to a class that it generates the correct migration (appending to the TPH) instead of suggesting to create a complete new table.

**Steps to reproduce:**
1. Clone the repository located here: https://github.com/michielpeeters/efcore_ownedproperty_issue
2. In the package manager console: Add-Migration Test (if correct, it displays the TPH table + additional table)
3. In the package manager console: Remove-Migration
4. Add additional property to the TestClass called TestProperty2 with the same Owned class.
5. Execute in package manager console: Add-Migration Test (if correct, it displays now only the TPH table where the columns are correctly appended (desired situation).

**Further technical details:**
EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target Framework: .net core 3.1.3
Operating System: Windows 10 x64
IDE: VS2019 Preview 16.6.0 Preview 3

**Comment by ajcvickers** [comment]
Related to #19543 #19279

**Comment by AndriySvyryd** [comment]
Fixed in fb33fe4
