### ISSUE TITLE
iOS Build after upgrade to EF core 3.1.3

### ISSUE THREAD

**Issue by simader** [dotnet/efcore#20689]
After upgrading to EF Core 3.1.3 we can't build anymore our iOS app, because of this error:
MTOUCH : error MT2002: Failed to resolve "System.Diagnostics.PerformanceCounter" reference from "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [/Users/runner/runners/2.165.2/work/1/s/09_Mobile/*.iOS.csproj]

Before using EF Core 2.2.6 it was working.
#20055: here it was meantioned, but it is closed and nobody is responding. 

We are using newest VS and Mono...

### Further technical details

EF Core version: 3.1.3
IDE: newest

**Comment by ajcvickers** [comment]
@alexkblount Looks like this is a Xamarin/iOS issue. Does it look familiar to you?

**Comment by alexkblount** [comment]
System.Diagnostics.PerformanceCounter does not exist in Xamarin.iOS Mono.

**Comment by ajcvickers** [comment]
@simader Please post your csproj file so we can see what packages you are pulling in.

**Comment by simader** [comment]
Hi All,
I found the solution: Somehow a reference of EntityFramworkCore.SqlServer ended up in my App. 
When i removed all references to this package, the build startet to work again.
Thanks for you help.
