### ISSUE TITLE
"auto-generated" doc-tag in migrations

### ISSUE THREAD

**Issue by amosonn** [dotnet/efcore#20691]
Currently, when generating migrations using the EF tool (`dotnet-ef migrations add <name> ...`), two files are automatically generated: `<timestamp>_<name>.cs` and `<timestamp>_<name>.Designer.cs`. Whereas the second has a leading line `// <auto-generated />`, which tells tooling such as stylecop to skip this file, the first one doesn't, which requires adding it manually to avoid warnings/errors. It would be nice if the first one had it as well.

Version 3.1.3, archlinux.

**Comment by ajcvickers** [comment]
Duplicate of #10203
