### ISSUE TITLE
Expose missing async APIs for transaction commit/rollback

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20694]
Continuing on #9015, #15917

**Comment by roji** [comment]
@ajcvickers shouldn't this be in a 5.0 milestone? It seemed to have gone in for preview5...

**Comment by AndriySvyryd** [comment]
@roji Usually the person that commits the fix is responsible of ensuring that the issue is in the correct milestone and has the "closed-fixed" label

**Comment by roji** [comment]
Sure, am just wondering why this didn't pop up for triage up to now...

**Comment by AndriySvyryd** [comment]
We don't triage closed issues

**Comment by roji** [comment]
We had a few issues with closed-fixed without a milestone - fixed two of mine, pinged @ajcvickers for others. Unfortunately Github doesn't seem to support searching for issues *without* a certain label (closed-duplicate and all the others), so it's difficult to find everything that doesn't have a closed label but no milestone...

**Comment by smitpatel** [comment]
GH does not properly filter things but here is the query you are looking for
https://github.com/dotnet/efcore/issues?q=is%3Aissue+no%3Amilestone+is%3Aclosed+-label%3Aclosed-duplicate+-label%3Aclosed-question+-label%3Aclosed-external+-label%3Aclosed-by-design+-label%3Aclosed-could-not-reproduce+-label%3Aclosed-not-needed+-label%3Aclosed-wont-fix

Plus, don't think there is any need to go further than first page as we did not assign closed-* labels before. First page end itself is reaching 2018.

**Comment by roji** [comment]
Thanks @smitpatel!
