### ISSUE TITLE
Regex in MigrationsIdGenerator doesn't work for longer strings

### ISSUE THREAD

**Issue by stefanluchian** [dotnet/efcore#20706]
If you have a prefix longer than "yyyyMMddHHmmss".Length, then the Regex doesn't work as expected.

### Steps to reproduce

Call this:
`MigrationsIdGenerator.GetName("12345678901234567_InitialCreate");`

One gets `67_InitialCreate` instead of `InitialCreate`.

Call this:
`MigrationsIdGenerator.IsValidId("12345678901234567_InitialCreate");`

The Regex should pay attention to the start of the string.
If not, it will incorrectly validate the longer number instead of rejecting it.

### Further technical details

EF Core version: 3.1.3
Database provider: not relevant
Target framework: .NET Core 3.1
Operating system: not relevant
IDE: not relevant

**Comment by stefanluchian** [comment]
Thanks for solving this for version 5.
Does this mean, that the problem can also be solved for 3.1.x ?

**Comment by ajcvickers** [comment]
@stefanluchian The [release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) describes how we determine which issues to patch. This issue doesn't seem like it meets the criteria.
