### ISSUE TITLE
Add support for Cosmos DB Connection strings

### ISSUE THREAD

**Issue by bradygaster** [dotnet/efcore#20712]
**Current State**
Currently, the `DbContextOptionsBuilder.UseCosmos` method has one overload that takes the Cosmos DB URI and key. 

**Potential Issue**
We're about to ship some updates in the tooling that will dial in the Cosmos DB connection string more elegantly. Customers who use that tooling would get a connection string handed to them in config, but they'd have a paper cut here - they can't use that pre-wired-up connection string with the `UseCosmos` method. 

**Proposed Solution**
Add an overload that takes a single string rather than the URI and the key, and take in the Connection String the tooling team will be pulling down from the Cosmos DB RP. 

Adding @timheuer and @AngelosP and @vijayrkn FYI for visibility. If you'd like support on the feature let us know.

**Comment by Marusyk** [comment]
I need this overload. I'll prepare PR for this

**Comment by Marusyk** [comment]
> Add an overload that takes a single string rather than the URI and the key
It seems we cannot use a single string parameter because we also need to specify the database name.

The connection string to CosmosDB doesn't contains Database name

> AccountEndpoint=https://schindler-eos.documents.azure.com:443/;AccountKey=SIUFFZa48DZsbCSghWcULcU2vZHr8d8mtCBFGf9MtWd9aL71eYg4KUbSoefachZnJQQUcFtIBmXi345F4tsbDw==;

@AndriySvyryd
