### ISSUE TITLE
System.NullReferenceException on Add DBContext Model Diagram

### ISSUE THREAD

**Issue by clouddust0246** [dotnet/efcore#20714]
Hello, 

i already followed the steps from the plural sight training by julie lerman but i ran into this error when try to run the model diagram.

I have 3 projects under the solution:
ConsoleApp1
SamuraiApp.Data -> Contains the Context (this is where i tried running the ef core tool)
SamuraiApp.Domain -> Contains the classes

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samurai.Domain\SamuraiApp.Domain.csproj" />
  </ItemGroup>

</Project>

1>------ Build started: Project: SamuraiApp.Data, Configuration: Debug Any CPU ------
1>CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from C:\Users\clouddust-dell\.nuget\packages\microsoft.entityframeworkcore.analyzers\3.1.3\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from C:\Users\clouddust-dell\.nuget\packages\microsoft.entityframeworkcore.analyzers\3.1.3\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
1>SamuraiApp.Data -> C:\Users\clouddust-dell\source\repos\SamuraiApp\Samurai.Data\bin\Debug\netcoreapp2.0\SamuraiApp.Data.dll
1>SamuraiApp.Data -> C:\Users\clouddust-dell\source\repos\SamuraiApp\Samurai.Data\bin\Debug\netstandard2.0\SamuraiApp.Data.dll
1>Done building project "SamuraiApp.Data.csproj".
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCorePowerTools.Extensions.ProjectExtensions.GetCspProperty(Project project, String propertyName) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\ProjectExtensions.cs:line 52
   at EFCorePowerTools.Extensions.ProjectExtensions.ContainsEfCoreDesignReference(Project project) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Extensions\ProjectExtensions.cs:line 102
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 45

### Further technical details

EF Core version: 2.4.38
Database provider: Pomelo.EntityFrameworkCore.Mysql also tried MySql.Data.EntityFrameworkCore
Target framework: netcoreapp2.0;netstandard2.0
Operating system: Window 10 Home
IDE: Visual Studio 2017 15.9.22

**Comment by ErikEJ** [comment]
This is a EF Core Power Tools issue, I have created: https://github.com/ErikEJ/EFCorePowerTools/issues/377
