### ISSUE TITLE
Misinterpreted expression with owned entities

### ISSUE THREAD

**Issue by verdie-g** [dotnet/efcore#20729]
I have one entity (`Owner`) containing two owned entities (`Owned1` and `Owned2`). When selecting a row and projecting it using `AutoMapper` I expected both owned entities to be different than null but one of them always gets null. If I remove one owned entity the other becomes different than null. Also, if I replace the navigation property of `Owned2` and replace it with an int, both entities aren't null anymore.

I've [reported the issue to AutoMapper](https://github.com/AutoMapper/AutoMapper/issues/3390) but apparently the issue would be on EF's side.

Feel free to rename the title as I haven't understand the issue.

### Steps to reproduce

```csharp
class Program
{
    static async Task Main()
    {
        await using var db = new MyDbContext();

        db.Owners.Add(new Owner
        {
            Owned1 = new Owned1(),
            O = new Owned2(),
        });
        await db.SaveChangesAsync();

        var config = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Owner, OwnerViewModel>();
            cfg.CreateMap<Other, OtherViewModel>();
            cfg.CreateMap<Owned1, Owned1ViewModel>();
            cfg.CreateMap<Owned2, Owned2ViewModel>();
        });

        var c = await db.Owners
            .ProjectTo<OwnerViewModel>(config)
            .ToListAsync();

        // c.O == null
    }
}


public class Owned1ViewModel { public int A { get; set; } }
public class Owned2ViewModel { public OtherViewModel Other { get; set; } }
public class OtherViewModel { public int Id { get; set; } }

public class OwnerViewModel
{
    public int Id { get; set; }
    public Owned1ViewModel Owned1 { get; set; }
    public Owned2ViewModel O { get; set; }
}

class MyDbContext : DbContext
{
    public DbSet<Owner> Owners { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder options) =>
        options.UseInMemoryDatabase("test");
}

public class Owner
{
    public int Id { get; set; }
    public Owned1 Owned1 { get; set; }
    public Owned2 O { get; set; }
}

[Owned] public class Owned1 { public int A { get; set; } }
[Owned] public class Owned2 { public Other Other { get; set; } }
public class Other { public int Id { get; set; } }
```
### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1
Operating system: 5.6.3-arch1-1 x86_64 GNU/Linux
IDE: Rider 2020.1

**Comment by ajcvickers** [comment]
@verdie-g This is working for me with [EF Core 5.0 preview 3](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0-preview.3.20181.2). Can you try again with preview 3 and check that it resolves your issue?

Note for team: this was not an in-memory issue; it also reproed on SQL Server.

**Comment by verdie-g** [comment]
The issue is still present on my side using `Microsoft.EntityFrameworkCore 5.0.0-preview.3.20181.2` and `Microsoft.EntityFrameworkCore.InMemory 5.0.0-preview.3.20181.2`. Making my project target `netcoreapp5.0` didn't help.

**Comment by ajcvickers** [comment]
@verdie-g Can you extract the IQueryable into a variable:

```C#
var queryable = db.Owners.ProjectTo<OwnerViewModel>(config);
        
var c = await queryable.ToListAsync();
``` 

And then drill down into it in the debugger, expand the DebugView, and post here both the Expression and Query.

![image](https://user-images.githubusercontent.com/1430078/80386302-10e47d80-885c-11ea-92a1-9e089d809c39.png)

On my machine I see this:
```
DbSet<Owner>()
    .Select(dtoOwner => new OwnerViewModel{ 
        Id = dtoOwner.Id, 
        O = dtoOwner.O == null ? null : new Owned2ViewModel{ Other = dtoOwner.O.Other == null ? null : new OtherViewModel{ Id = dtoOwner.O.Other.Id }
             }
        , 
        Owned1 = dtoOwner.Owned1 == null ? null : new Owned1ViewModel{ A = dtoOwner.Owned1.A }
         
    }
    )
```
```sql
SELECT [o].[Id], CAST(0 AS bit), CASE
    WHEN [o0].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [o0].[Id], [o].[Owned1_A]
FROM [Owners] AS [o]
LEFT JOIN [Other] AS [o0] ON [o].[O_OtherId] = [o0].[Id]
```

**Comment by verdie-g** [comment]
Looks pretty similar
```csharp
DbSet<Owner>()
    .Select(dtoOwner => new OwnerViewModel{ 
        Id = dtoOwner.Id, 
        O = dtoOwner.O == null ? null : new Owned2ViewModel{ Other = dtoOwner.O.Other == null ? null : new OtherViewModel{ Id = dtoOwner.O.Other.Id }
             }
        , 
        Owned1 = dtoOwner.Owned1 == null ? null : new Owned1ViewModel{ A = dtoOwner.Owned1.A }
         
    }
    )
```

And no query for InMemory provider.

**Comment by ajcvickers** [comment]
@verdie-g Thanks--it was my error. I didn't check again with the in-memory provider. I can now repro this on the latest daily build.
