### ISSUE TITLE
Cannot Extend EF Core 3.1 use have a global WITH (NOLOCK) Setup

### ISSUE THREAD

**Issue by cristureansamuel** [dotnet/efcore#20720]
I've migrated over to .netcore 3.1 and EF Core 3.1. from 2.2

In 2.2 I've managed to have a WITH (NOLOCK) mechanism with the below code.
![image](https://user-images.githubusercontent.com/25790148/80011407-7fc87c00-84d4-11ea-8720-82fa5fd2d1cb.png)

However, I cannot re-use this code on EF 3.1, I've tried with an interceptor (print screen) below.
The challenge with the below code is that it does not place the WITH (NOLOCK) where it supposed to and always places it at the end of the query.

![image](https://user-images.githubusercontent.com/25790148/80011616-c74f0800-84d4-11ea-829d-1787b26b226b.png)

### Further technical details

EF Core version:
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019)

**Comment by ralmsdeveloper** [comment]
@cristureansamuel Try
```csharp
public class WithNoLockMechanism : DbCommandInterceptor
{
    private static readonly Regex _tableAliasRegex =
        new Regex(@"(?<tableAlias>FROM +(\[.*\]\.)?(\[.*\]) AS (\[.*\])(?! WITH \(NOLOCK\)))",
            RegexOptions.Multiline | 
            RegexOptions.IgnoreCase | 
            RegexOptions.Compiled);

    public override InterceptionResult<DbDataReader> ReaderExecuting(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<DbDataReader> result)
    {
        if (!command.CommandText.Contains("WITH (NOLOCK)"))
        {
            command.CommandText =
                _tableAliasRegex.Replace(
                     command.CommandText,
                     "${tableAlias} WITH (NOLOCK)");
        }

        return result;
    }
}
```

This is just an example, you may need to do more around.

**Comment by cristureansamuel** [comment]
@ralmsdeveloper thank you so much for your answer.
It seems to look ok I just need to test it over all my app scenarios.

BTW isn't this a bit risky? using REGEX?

**Comment by ralmsdeveloper** [comment]
This is just a workaround, while this is the easiest and easiest way to use hints, I'm sure the team or community will soon be doing something official.

And regarding the regex I don't see any problems until then.

The only problem is that you will apply hint to all tables in your query, what you can do is do a pre-validation.

**Comment by bdebaere** [comment]
@cristureansamuel The pipeline was changed from 2.x to 3.x. The following code at https://gist.github.com/bdebaere/d8e8fadb116efd717563bd72adacd3f2 should work for you. Let me know if you have any issues.

**Comment by cristureansamuel** [comment]
Thanks @ralmsdeveloper  & @bdebaere .

I've managed to figure it out, please see below how I did it.

public static class CustomDbContextOptionsBuilderExtensions
    {
        public static DbContextOptionsBuilder UseCustomSqlServerQuerySqlGenerator(this DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.ReplaceService<IQuerySqlGeneratorFactory, CustomSqlServerQuerySqlGeneratorFactory>();
            return optionsBuilder;
        }
    }

    class CustomSqlServerQuerySqlGeneratorFactory : IQuerySqlGeneratorFactory
    {
        public CustomSqlServerQuerySqlGeneratorFactory(QuerySqlGeneratorDependencies dependencies)
            => Dependencies = dependencies;
        public QuerySqlGeneratorDependencies Dependencies { get; }
        public QuerySqlGenerator Create() => new CustomSqlServerQuerySqlGenerator(Dependencies);
    }

    public class CustomSqlServerQuerySqlGenerator : SqlServerQuerySqlGenerator
    {
        public CustomSqlServerQuerySqlGenerator(QuerySqlGeneratorDependencies dependencies)
            : base(dependencies) { }
        protected override Expression VisitTable(TableExpression tableExpression)
        {
            // base will append schema, table and alias
            var result = base.VisitTable(tableExpression);
            Sql.Append(" WITH (NOLOCK)");
            return result;
        }
    }

then on DBContext.cs file I've called the above class like this:

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseCustomSqlServerQuerySqlGenerator();

        }

**Comment by ajcvickers** [comment]
Better support for NOLOCK is tracked by #6717. Closing this since workarounds have been provided--thanks @ralmsdeveloper and @bdebaere!
