### ISSUE TITLE
EF Core Same TABLE TWO ACTIONS (Remove item + update remaining ones)

### ISSUE THREAD

**Issue by cristureansamuel** [dotnet/efcore#20737]
I have a weird situation.

I have a list from where I need to remove an item from the DB, then all remaining ones I need to just increment and update them.

I use.AsNoTracking() on the list filtering but I cannot perform the above actions thought.
Keeps telling me that "
"The property 'ListNumber' on entity type 'LIST' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal."
I've tried also to build 1 method for remove and 1 for update the remaining items and call them from the controller (the first one is the remove then the second one is the update) but the same result.

Anyone can help me out because I'm stuck I would highly appreciate a clear example or approach on how I can deal with the above situation.

Thank you in advance.

Below is the code I'm using

Controller

```C#
await _repo.RemoveFromList("1234", "1");
await _repo.ResetList("1234");
```

Methods
```C#
public async Task RemoveFromList(string listNumber, string listItem)
        {
            try
            {
                var entity = await _context.LIST.Where(x => x.ListNumber == listNumber && x.ListItem == listItem).FirstOrDefaultAsync();
                _context.LIST.Remove(entity);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                throw;
            }
        }

public async Task ResetList(string listNumber)
        {
            try
            {
                var entities = await _context.LIST.AsQueryable().Where(x => ListNumber== listNumber).ToListAsync();
                var startFrom = 1;
                foreach (var en in entities)
                {
                    en.NewListNumber = startFrom.ToString().PadLeft(3, '0');
                    startFrom++;
                    _context.LIST.Update(en);
                }

                await _context.SaveChangesAsync();
                
            }
            catch (Exception ex)
            {
                throw;
            }
        }
```

Remove Method works but the second one does not work, gives me the below exception

Got Exceptions? Include both the message and the stack trace

Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
-->

### Further technical details

EF Core version:
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@cristureansamuel It's hard to diagnose what is happening without understanding what the model is and how these methods are being called. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by cristureansamuel** [comment]
@ajcvickers I will prepare a sample project and link it here. I would do it today.

Thank you for your interest.

**Comment by cristureansamuel** [comment]
I managed to do it like below 

 ```
var updateList = await _context.UpdateLists.FindAsync(id);
                _context.UpdateLists.Remove(updateList);
                await _context.SaveChangesAsync();
                var resetAllRows = await _context.UpdateLists.ToListAsync();
                var row = 1;
                foreach (var item in resetAllRows)
                {
                    item.ListRow = row.ToString();
                    row++;
                    _context.Update(item);
                    await _context.SaveChangesAsync();
```

**Comment by ajcvickers** [comment]
@cristureansamuel Are you saying that the code you posted works for you and this issue can be closed?

**Comment by cristureansamuel** [comment]
Hi @ajafry yes
