### ISSUE TITLE
using context.EntityType.Find(1) when primary key is a long instead of an int generates ArgumentException

### ISSUE THREAD

**Issue by JohnnyErnest** [dotnet/efcore#20738]
Title says it all, should be an easy fix.

<img width="960" alt="EFCoreTest" src="https://user-images.githubusercontent.com/25945156/80174323-ea9eb380-85b7-11ea-94ea-aecfc108537c.png">

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 Community)

**Comment by ErikEJ** [comment]
Have you tried:

    .Find(1L);
