### ISSUE TITLE
EF Core Scaffold Doesn't Respect Output Directory

### ISSUE THREAD

**Issue by Chris-Dickerson** [dotnet/efcore#20752]
Issuing the scaffold command when the output directory is anything other than standard (_bin/Debug_) -- the command fails with:

**The specified deps.json [D:\Projects\TestProject\bin\Debug\netcoreapp3.1\TestProject.deps.json] does not exist**

The TestProject has the output directory set to "_..\bin\x64\Debug_"

### Steps to reproduce

Change the dotnet Core project's output folder to a non-standard path (such as ..\bin\Debug) and run the scaffold command:

`
dotnet ef dbcontext scaffold "Server=(localdb)\MSSQLLocalDB;Database=TESTDB;Integrated Security=True;MultipleActiveResultSets=true" Microsoft.EntityFrameworkCore.SqlServer --output-dir TestDb --context TestDbModel --startup-project TestProject --force --verbose --no-build --use-database-names`

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro Version 10.0.18363.778
IDE: Visual Studio 2019 16.5.4

[dotnetcore-sdk-runtimes.txt](https://github.com/dotnet/efcore/files/4534494/dotnetcore-sdk-runtimes.txt)

**Comment by bricelam** [comment]
@Chris-Dickerson Could you share your csproj? We use the `OutputPath` MSBuild property to determine the output directory.

**Comment by Chris-Dickerson** [comment]
The top level directory is where the primary or common bin directory is, the other directories are all projects in the solution, including the data access project (csproj attached).

[DataAccessLayer.csproj.txt](https://github.com/dotnet/efcore/files/4561793/DataAccessLayer.csproj.txt)

**Comment by bricelam** [comment]
I think the issue is that you're setting it in a condition:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
  <OutputPath>..\bin\x64\Debug\</OutputPath>
</PropertyGroup>
```

Platform isn't specified when we read the property, so we get the default value.

It might work if you specify `--runtime`:

```sh
dotnet ef dbcontext scaffold --runtime win10-x64 ...
```

But personally, I'd just specify BaseOutputPath instead:

```xml
<PropertyGroup>
  <BaseOutputPath>..\bin\</BaseOutputPath>
</PropertyGroup>
```

**Comment by Chris-Dickerson** [comment]
I didn't set anything in the csproj by hand, it's all from Visual Studio. If you start a .NET Core project, add a platform in the configuration manager, then set the output path, you get:

`<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\bin\x64\Debug</OutputPath>
  </PropertyGroup>

</Project>`

**Comment by Chris-Dickerson** [comment]
```
<BaseOutputPath>..\bin</BaseOutputPath>
```

Using the switch "--runtime x64" just appends the label to the end of the path beyond the netcoreapp:

```
The specified deps.json [D:\Projects\TestProject\bin\Debug\netcoreapp3.1\x64\TestProject.deps.json] does not exist
```

The way that you set Debug and Release for the build, and the way the scaffolding works are different. The problem is you cannot affect the path beyond the "netcoreapp3.1" part of the path, that gets appended all the time. The runtime switch only affects things when scaffolding.

**Comment by bricelam** [comment]
We mimic `dotnet run` which only has `--runtime`. This sets `RuntimeIdentifier` which influences `PlatformTarget`.

`Platforms` and `Platform` appear to be VS-specific properties that [don't integrate well](https://github.com/dotnet/sdk/blob/3058e86e67b30696e5eacc00c9234e9cc0033985/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L49-L60) with the .NET Core SDK.

In other words, `dotnet run` has the same problem as `dotnet ef`. We should follow up with [dotnet/sdk](https://github.com/dotnet/sdk) and [dotnet/project-system](https://github.com/dotnet/project-system) to see what their guidance is here.

**Comment by ajcvickers** [comment]
@davkean What's the best way to follow up on this? Who would be an appropriate person to ping?

**Comment by ajcvickers** [comment]
Also pinging @drewnoakes as a top contributor to project-system.

**Comment by marcpopMSFT** [comment]
@dsplaisted any suggestions here?

**Comment by dsplaisted** [comment]
Setting up platforms in the configuration manager doesn't always work well for .NET Core projects.  In this project, there is only a single Platform defined (`x64`).  However, if you build the project from the command line the Platform won't be set, and the customizations won't apply.  I believe if you were to build the solution file, it would apply the Platform.

I would recommend not using the Platform like this.  For `dotnet build` or other commands you could work around the issue by specifying the platform by adding `-p:Platform=x64` to the command line.  I'm not sure if `dotnet ef` supports this though.

**Comment by bricelam** [comment]
We don’t flow extra args to dotnet/MSBuild. We just made a change to flow them to the app.

We’d probably need to add first-class support for Platform to fix this.

Or invent some novel way of determining which arguments flow to MSBuild, which flow to the app, and (eventually) which flow to the provider.

**Comment by dsplaisted** [comment]
Another workaround would be to put the following in a `PropertyGroup` in the file before the groups that have the conditions on them:

```xml
<Platform Condition="'$(Platform)' == ''">x64</Platform>
```

IE, if the `Platform` isn't set, then set it to `x64`.

**Comment by bricelam** [comment]
So it feels like our guidance is:

1. Don't use the Platforms drop-down list on SDK-style projects (ones with `<Project SDK="...">`)
2. If you do, specify a default value in the project file for SDK tools to use

It may be worth filing an issue on [dotnet/project-system](https://github.com/dotnet/project-system) to see if there's anything they can do to improve this experience.

**Comment by davkean** [comment]
> Setting up platforms in the configuration manager doesn't always work well for .NET Core projects

Confused why this is better in legacy?

**Comment by dsplaisted** [comment]
> > Setting up platforms in the configuration manager doesn't always work well for .NET Core projects
> 
> Confused why this is better in legacy?

I think it's just less likely that you're going to build the project file directly without the Platform specified, or to run a tool which processes the project file and doesn't know about the default Platform set up in the .sln file.

**Comment by davkean** [comment]
> I think it's just less likely that you're going to build the project file directly without the Platform specified

ie This is nothing to do with SDK-projects, just that a project has been built without specifying the platform.

**Comment by bricelam** [comment]
So should EF be parsing the sln file and passing `/p:Platform=xxx`?

**Comment by bricelam** [comment]
Or (similar to how we handle TFM) just pick the first value in `Platforms`?

**Comment by dsplaisted** [comment]
I don't think EF should be doing anything special here.  I can understand why EF would pick an arbitrary TargetFramework, because if you build the project without TargetFramework specified, then it will build for both of them.  However, the same is not the case for the Platform, so I would say that the project file should be updated with a default for the `Platform`.

**Comment by ajcvickers** [comment]
Closing as we agree that EF should no do anything special here.
