### ISSUE TITLE
EFCore Provider for New Database

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#20778]
Not sure if this is correct forum, if not, please suggest what would be correct forum to ask this question.
I am looking for EFCore support for new RDBMS(database). This database already support .NET Core 3.1 Provider. What would be best place to start with possible skeleton code to support new database? Could we take https://github.com/dotnet/efcore code and modify https://github.com/dotnet/efcore/tree/master/src/EFCore.SqlServer/Storage/Internal source files to support new Database?

Could we take https://github.com/dotnet/efcore code and modify https://github.com/dotnet/efcore/tree/master/src/EFCore.SqlServer/Storage/Internal source files to support new Database?

**Comment by roji** [comment]
We unfortunately don't currently have a skeleton provider template you can start from, but you can indeed duplicate an existing provider and start from there. The SQL Server provider is one possibility; you can also look at a provider that's completely outside the repo, like [Npgsql.EntityFrameworkCore.PostgreSQL](https://github.com/npgsql/EFCore.PG).

We also have [a doc page on writing a provider](https://docs.microsoft.com/en-us/ef/core/providers/writing-a-provider), although it's unfortunately very rudimentary and not up to date. We do plan on providing more docs on this for 5.0. As you run into problems, feel free to open new issues here to ask questions and we'll assist in any way we can.

Out of curiosity, can you let us know which RDBMS you're developing a provider for?

**Comment by deokershesh** [comment]
Thanks @roji,
Basically one of the links from "doc page on writing a provider" takes me to https://github.com/dotnet/efcore only. Also it has Npgsql.EntityFrameworkCore.PostgreSQL as you mentioned. However, didn't find how to start building Npgsql.EntityFrameworkCore.PostgreSQL code form github link.

I was looking for EFCore Provider for Informix database and didn't find one, hence thought to make an attempt to create one!

**Comment by roji** [comment]
See the links on that page to Npgsql, Pomelo MySQL and SQL Server Compact. You should be able to clone these and build them; at the very least for the Npgsql provider, a standard `dotnet build` should work.

**Comment by roji** [comment]
Am going to close this as there's nothing actionable here - https://github.com/dotnet/EntityFramework.Docs/issues/681 already tracks improving our docs for provider writers. But don't hesitate to post back here if you have more questions.
