### ISSUE TITLE
Allow SQL Server aliases to be mapped

### ISSUE THREAD

**Issue by DanielSSilva** [dotnet/efcore#20773]
This issue comes in the sequence of #12633 , as per @ajcvickers request

When using a property that has a `User Defined Type` on SQL, C# throws an exception (see the sample readme for more information):

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Type fid is not a defined system type.
```

### Steps to reproduce
[Here's a sample and instructions on Readme](https://github.com/DanielSSilva/EF_UDT_Issue)

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Ubuntu 18.04 and Ubuntu 20.04
IDE: vscode

**Comment by ajcvickers** [comment]
@DanielSSilva Thanks for filing this. However, #12633 was about how EF scaffolds a DbContext from a database that contains a user defined type. In your case, you are explicitly using the user-defined type in the model:
```C#
builder.Property(p => p.UserId).HasColumnType("fid");
builder.Property(p => p.ProfileId).HasColumnType("fid");
```
I'm not sure whether this is supported or not--we will discuss.

**Comment by DanielSSilva** [comment]
@ajcvickers my bad. I've understood it wrongly then. I saw this part
```
the resulting context is

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserDefinedDataTypeBug>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Status).HasColumnType("Enumeration");
            });
        }
```
and assumed that it was correct (I now understand that it is not). This used to work on 2.0.

**Comment by ajcvickers** [comment]
@DanielSSilva We discussed this and because of limitations in how SQL Server supports aliases we don't think we can make this work. The correct thing to do for EF is to "erase" the aliases--that is, when using an alias for "bigint" you should tell EF that the column type is "bigint".

**Comment by DanielSSilva** [comment]
Thanks for the reply @ajcvickers . But Why is that this worked on 2.0 but now it does not work on 3.1? What changed so that it now throws such exception?

**Comment by ajcvickers** [comment]
@DanielSSilva That I'm not sure of, but _a lot_ has changed since 2.0.

**Comment by DanielSSilva** [comment]
@ajcvickers but if this used to work on 2.0, I don't think that this should be considered to be a limitation in SQL Server. In fact, I expected the issue #12633 not to be an issue but actually the expected behavior based on my experience with 2.0. There might have been some change on EF side on how it deals with translation between User Defined Data Type and C# types, but it used to work just fine.
If a database has multiple User Defined Data Types spread across many tables, "erasing" them all in EF will not only be painful but also error prone because one has to ensure the same restrictions that user defined type used to do (like `NOT NULL` , `NVARCHAR(50)`, etc)

**Comment by ajcvickers** [comment]
@DanielSSilva In 2.0, the type mapping was weak, which cased numerous issues. The type mapping now is much more correct, which has solved many issues, but is probably what is now blocking this.

I'll re-open this to consider adding support for correctly mapping aliases in a future release.
