### ISSUE TITLE
Add the command to update the tools to the latest version to the version mismatch error message.

### ISSUE THREAD

**Issue by riscie** [dotnet/efcore#20791]
**Problem**
Trying to use the ef core tools when the current project version does not match the local installed tools version tells us correctly that we should update the local tools. However, it does not show how we can achieve that. I (and [others](https://stackoverflow.com/a/59231565/1595320)) think, the message could show us how to do so.

**Solution**
Add the command to update the tools to the latest version to the version mismatch error message.

**Comment by ajcvickers** [comment]
Link was added in #20792.
