### ISSUE TITLE
Build query in All.sln file

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#20793]
There is below line in All.sln file. What are the encoded values at the prefix and suffix? If I need to support new database, how do I get these values?

Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "EFCore.SqlServer", "src\EFCore.Informix\EFCore.Informix.csproj", "{99595B81-D47C-40BA-8C61-5328A5A0E4AB}"

**Comment by ErikEJ** [comment]
That's not how you should build a provider, simply consume the published packages, and adopt the Test packages.

**Comment by deokershesh** [comment]
@ErikEJ, May be my approach is not right to pick up "https://github.com/dotnet/efcore" source code and make appropriate changes in the code which is supported for SqlServer to support other databases. Infact, I did open another issue https://github.com/dotnet/efcore/issues/20778 and it was suggested to duplicate the code and make appropriate changes.

Request you to suggest best way to support Entity Framework Core for new database. Thanks

**Comment by ErikEJ** [comment]
@deokershesh You can look at the chain of commits in the repo for an approach that worked well for me: https://github.com/GibraltarSoftware/VistaDB.EFCore/commits/develop

**Comment by ajcvickers** [comment]
@deokershesh As @roji said in #20778, look at how the [PostgreSQL provider](https://github.com/npgsql/efcore.pg) and the [Pomelo MySQL provider](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) organize their code and pull in the EF packages. You should structure the repo for your provider in the same way.

**Comment by ErikEJ** [comment]
@ajcvickers  It would lower the barrier to have a "template/null" provider to use as a starting point. But of course it can quickly become stale.
