### ISSUE TITLE
SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.

### ISSUE THREAD

**Issue by donhuvy** [dotnet/efcore#20817]
I am using `Microsoft.EntityFrameworkCore.SqlServer`, Version=`5.0.0-preview.3.20181.2`

Exception log: https://gist.github.com/donhuvy/71d1773effecd39c561c2e8ccb4396ec

![exception](https://user-images.githubusercontent.com/1328316/80867486-80c09100-8cbe-11ea-90ab-7ea3477aea04.png)

![razor](https://user-images.githubusercontent.com/1328316/80867681-a69a6580-8cbf-11ea-9591-4ee308f1b10d.png)

Blazor razor file https://gist.github.com/donhuvy/ecb28b20764cf57bffb914baa01c8fbe#file-salevoucher-razor-L333

database: https://gist.github.com/donhuvy/98268691b37a02cf74d273cb74dc37dc#file-applicationdbcontext-cs-L6148

My model: https://gist.github.com/donhuvy/61810e01a8c1c400314a95687cb0e5e7

My form: https://gist.github.com/donhuvy/339cd6d48c147aa7e8180f373fb0c7ca

`dot net ef` https://gist.github.com/donhuvy/e3e0a22949fdbba9de7a65ba10089033

Visual Studio: https://gist.github.com/donhuvy/f8e5a3ffa5888f04569b6f26a1f8650b

```
select @@VERSION;
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Enterprise Evaluation Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 18363: ) 
```

### Steps to reproduce

My Visual Studio project file: https://gist.github.com/donhuvy/4ceb946c35e132c40271929ac480aebe#file-acc133balzor-proj-L25

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 5.0 preview
Operating system: Windows 10 x64 pro
IDE: Microsoft Visual Studio Community 2019 Preview
Version 16.6.0 Preview 5.0

**Comment by ErikEJ** [comment]
If the SQL Server data type is "datetime", the lowest possible value is what the error message clearly states.

**Comment by ralmsdeveloper** [comment]
@donhuvy 
You are not passing data to **PostedDate**, which is a non-null field, SQL Server expects a minimum value of **1/1/1753**, and .NET the minimum value is **1/1/0001**, so it passes the value in **PostedDate** that solved your problem!

**Comment by donhuvy** [comment]
> @donhuvy
> You are not passing data to **PostedDate**, which is a non-null field, SQL Server expects a minimum value of **1/1/1753**, and .NET the minimum value is **1/1/0001**, so it passes the value in **PostedDate** that solved your problem!

Thanks @ralmsdeveloper , It works. I am sorry, it is not a bug.

**Comment by Dra-123** [comment]
Hi donhuvy. I want to learn something. I have low vision and so I need big fonts as you did. Therefore, I want to make the Visual Studio appearance that I use look exactly like yours. How did you do this big fonts. Do you use any customized theme. Can you share your font configuration. Thanks.
