### ISSUE TITLE
Missing benchmarks in dashboard

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20822]
NavigationsQuerySqliteTests, QueryCompilationSqliteTests

/cc @sebastienros

**Comment by roji** [comment]
@sebastienros am still not seeing those two benchmark suites, although it's been 17 hours - do we need to wait more?

**Comment by sebastienros** [comment]
My little hands need to add the charts to PBI now. Since we moved to dedicated charts this is not dynamic anymore.

**Comment by smitpatel** [comment]
I am still not seeing QueryCompilationSqliteTests in benchmarks. Mr. tiny hands need to do more work? :trollface:

**Comment by sebastienros** [comment]
QueryCompilationSqliteTests doesn't work right now

https://dev.azure.com/dnceng/internal/_build/results?buildId=631390&view=logs&j=624e7fb7-5c98-5486-5327-c11d2337f7d0&t=c4144b72-12c9-5209-97f7-6afef65adbfd

FilterOrderProject returns NA values

**Comment by roji** [comment]
Thanks - that benchmark indeed fails on Sqlite because ordering by decimals isn't supported. Submitted #20876 to replace by double - should be fine for benchmarking.

**Comment by smitpatel** [comment]
Please close the issue once we verify it in benchmark dashboard.

**Comment by roji** [comment]
@sebastienros since the fix above, I can see QueryCompilationSqliteTests running without failures locally now, but it's still not appearing on the dashboard. Does something else need to be done on your side?

**Comment by sebastienros** [comment]
Remember the little hands

**Comment by sebastienros** [comment]
done

**Comment by smitpatel** [comment]
Wrong title of the benchmark Mr. Tiny hands!

**Comment by sebastienros** [comment]
For me it looks fine 😊
