### ISSUE TITLE
Certain queries fail to return correct results when compiled with UWP .NET Native

### ISSUE THREAD

**Issue by mfeingol** [dotnet/efcore#20829]
The following query fails to return a result when compiled with UWP .NET Native. It returns the correct result without .NET Native:

```c#
var result = db.Entities.FirstOrDefaultAsync(e => e.StringColumn == this.nullableStruct.Value.StringValue);
```

The following query, which should be equivalent, returns the expected result:

```c#
string stringValue = this.nullableStruct.Value.StringValue;
var result = db.Entities.FirstOrDefaultAsync(e => e.StringColumn == stringValue);
```

I'm not sure if this is a .NET Native bug or an EF Core bug.

### Steps to reproduce

I'll include a simple repro project as soon as I have one.

### Further technical details

EF Core version: 2.2.6 and 3.1.3
Database provider: SQLite
Target framework: UWP
Operating system: Windows 10 19041.208
IDE: VS 2019 16.5.4

**Comment by roji** [comment]
Thanks @mfeingol, a minimal, runnable repro project would indeed be helpful here.

**Comment by mfeingol** [comment]
Thanks, @roji.

You can find a repro at https://github.com/mfeingol/repros/tree/master/EFCoreRepro_20829.

Just build and F5 on the UWP app. Note that the queries are successful without .NET Native, and unsuccessful with.

**Comment by mfeingol** [comment]
@roji: were you able to reproduce the issue?

Thanks.

**Comment by roji** [comment]
@mfeingol not yet, there are many other high-priority items I'm looking into, especially since this has a workaround (copy the value out from the nullable struct to a simple variable).

**Comment by mfeingol** [comment]
That's fair.

One thing I'll note, though, is that it's not entirely obvious to developers that there's a problem. The offending queries don't throw an exception, they just return no results. Further, this only happens with .NET Native compilation, so the queries will work fine with normal build/debug cycles.

So I think there being a workaround isn't _that much_ of a mitigating factor in this context, since the issue is so subtle.

**Comment by roji** [comment]
Thanks for the additional info... Unfortunately I still can't promise anything in the near future...

**Comment by mfeingol** [comment]
I just thought I'd check in on this. Do you anticipate this will ever be fixed, perhaps with .NET 5? Or does .NET 5 render the issue moot since .NET Native presumably changes a lot?

**Comment by roji** [comment]
@mfeingol I'm sorry that this couldn't receive any attention up to now - there have just been too many other things in the pipeline. Unfortunately .NET 5.0 is pretty much complete now, and so this won't be fixed for that version. I'm not sure exactly how .NET 5 would change .NET Native (but that's because I haven't been following UWP very closely).

**Comment by mfeingol** [comment]
@ajcvickers: anything in particular that's blocking you with this issue?

**Comment by ajcvickers** [comment]
Note from triage: UWP is not supported in .NET 6.

**Comment by mfeingol** [comment]
Given that EF Core 3.x is still receiving periodic updates, I'd request this be reconsidered.

**Comment by ajcvickers** [comment]
@mfeingol This does not [meet the bar](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for patching 3.1.

**Comment by mfeingol** [comment]
That's unfortunate, but I understand your position.
