### ISSUE TITLE
Unable to find options to change ColumnEncryptionKeyCacheTtl 

### ISSUE THREAD

**Issue by chintan3100** [dotnet/efcore#20842]
Unable to find options to change ColumnEncryptionKeyCacheTtl 

https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.columnencryptionkeycachettl?redirectedfrom=MSDN&view=netframework-4.8&viewFallbackFrom=netcore-3.1#System_Data_SqlClient_SqlConnection_ColumnEncryptionKeyCacheTtl

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
@chintan3100 I'm not very familiar with it, but that is a static property. That means you should be able to set it yourself on SqlConnection, and there's no real need or value in EF Core doing anything with it.

**Comment by chintan3100** [comment]
Looks like not supported in net core. It's supported in .net framework :(

**Comment by roji** [comment]
[Microsoft.Data.SqlClient does have this property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.columnencryptionkeycachettl?view=sqlclient-dotnet-core-1.1#Microsoft_Data_SqlClient_SqlConnection_ColumnEncryptionKeyCacheTtl) - consider switching from System.Data.SqlClient to that ([see this blog post for more details](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/)).

Am going to close this issue as nothing seems to be needed from the EF Core side, but if you encounter further difficulties feel free to post back.

**Comment by type4ranjan** [comment]
Is there any way to change this setting in SQL Server Management Studio (SSMS) ? It has default timeout to 2 hours or we have to close and start SSMS again to clear cache.
