### ISSUE TITLE
EF Filtered include is creating fields that don't exist in table

### ISSUE THREAD

**Issue by garrapatita** [dotnet/efcore#20841]
I am using .net core 3.1
Microsoft.EntityFrameworkCore.Tools v5.0.0-preview.3.20207.1
Microsoft.EntityFrameworkCore.SqlServer v5.0.0-preview.3.20181.2

My simplified entities are as follows:
```
public class Channel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string YTChannelId { get; set; } ///<value>Id YouTube gives to the channel and it is used here as a primary key.</value>
        //From snipped
        [Required]
        public string ChannelTitle { get; set; } 
        public string Description { get; set; } 
        public ICollection<ChannelStat> ChannelStat { get; set; } 
        public DateTime? LastUpdate { get; set; }    //The last time the channel published a video
        public DateTime RegisteredTime { get; set; } //At what date and time was the channel was registered in our system, always UTC time
    }
```

```
public class ChannelStat
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; } //primary key identity column
        [ForeignKey("channel")]
        public string YTChannelId { get; set; }
        public virtual Channel Channel { get; set; } //Reference property to the channel to which this stats belong.
        public ulong? VideoCount { get; set; } //Nr of videos the channel has
        public DateTime RegisteredTime { get; set; } //At what date and time was the stat captured, always UTC time
    }
```
Here is the how I'm querying in the repository
```
var results = _context.Channel
                    .Include(channel => channel.ChannelStat
                    .OrderByDescending(stat => stat.RegisteredTime)
                    .Take(1))
                    .ToList();
```
The idea is to get all the channels and for each channel to get only the latest stat for it.
I followed this doc (the **filtered include** section) https://docs.microsoft.com/en-us/ef/core/querying/related-data

In any event, here is the sql translated as a shown by the profiler
```
SELECT [c].[YTChannelId], [c].[ChannelTitle], [c].[Description], [c].[LastUpdate], [c].[RegisteredTime], [t].[Id], [t].[ChannelYTChannelId], [t].[RegisteredTime], [t].[VideoCount], [t].[YTChannelId]
FROM [Channel] AS [c]
OUTER APPLY (
    SELECT TOP(1) [c0].[Id], [c0].[ChannelYTChannelId], [c0].[RegisteredTime], [c0].[VideoCount], [c0].[YTChannelId]
    FROM [ChannelStat] AS [c0]
    WHERE [c].[YTChannelId] = [c0].[ChannelYTChannelId]
    ORDER BY [c0].[RegisteredTime] DESC
) AS [t]
ORDER BY [c].[YTChannelId], [t].[RegisteredTime] DESC, [t].[Id]
```

And here it is what the sql should look like in order to work
```
SELECT [c].[YTChannelId], [c].[ChannelTitle], [c].[Description], [c].[LastUpdate], [c].[RegisteredTime], [t].[Id], [t].[RegisteredTime], [t].[VideoCount], [t].[YTChannelId]
FROM [Channel] AS [c]
OUTER APPLY (
    SELECT TOP(1) [c0].[Id], [c0].[RegisteredTime], [c0].[VideoCount], [c0].[YTChannelId]
    FROM [ChannelStat] AS [c0]
    WHERE [c].[YTChannelId] = [c0].[YTChannelId]
    ORDER BY [c0].[RegisteredTime] DESC
) AS [t]
ORDER BY [c].[YTChannelId], [t].[RegisteredTime] DESC, [t].[Id]
```
As you can see EF is translating it funny adding a non existent ```ChannelYTChannelId``` column, however please notice that at the end of the sql it also contains ```YTChannelId```. So I have no idea where this extra column is coming from. I asume it is a bug.

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#fkp

**Comment by garrapatita** [comment]
Hi smitpatel, I am already explicitly configuring my foreign key as such with the annotations in the entity class 
```
[ForeignKey("channel")]
public string YTChannelId { get; set; }
public virtual Channel Channel { get; set; }
```

Or is there something else that I should be doing and I'm not?
Thanks!

**Comment by smitpatel** [comment]
Your navigation name in attribute and class have different casing. They are not matching.

**Comment by garrapatita** [comment]
@smitpatel thanks, it works now. But I don't get it. I have the same syntax with the mismatch casing since EF core 2.2.6 and it was never a problem. I feel so silly now. But thanks for the help!

**Comment by smitpatel** [comment]
@garrapatita - The FK attribute was being ignored in 2.2 same way it was in 3.1 when the casing was different. In 2.2 since we matched exact PK name too, the FK attribute error was getting masked. Since 3.1 had that breaking change, it exposed the error in FK attribute too.

**Comment by garrapatita** [comment]
@smitpatel thanks again for the clarification and for the speedy reply!
