### ISSUE TITLE
Review our usage of <code> in XML docs

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20849]
It seems like in many cases we expect &lt;code&gt; doc fragments to render inline, but in the docs they're rendered as a block, [leading to ugly/mangled docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.update.iupdateadapter.cascadechanges?view=efcore-3.1#Microsoft_EntityFrameworkCore_Update_IUpdateAdapter_CascadeChanges
).

[In some cases](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.fromsql?view=efcore-3.1), a separate code block may make sense, but this needs to be cleaned up...

**Comment by ajcvickers** [comment]
@roji Further evidence that we should get rid of them.

**Comment by roji** [comment]
Not sure it would solve what you think it would - the supporters of &lt;code&gt; would switch to wanting italics instead or something :laughing: 

More seriously, in cases like FromSqlInterpolated a separate code block makes sense to me, but that's not how it's being used at the moment (e.g. there's a dot afterwards...).

**Comment by roji** [comment]
Reopening to verify that the output looks good (especially with regards to https://github.com/dotnet/efcore/pull/20893#pullrequestreview-408556637).

**Comment by roji** [comment]
Closing since we've decided not to push the API docs live for now. We'll revisit this later.

**Comment by sharwell** [comment]
This is easy to review if you use [DotNetAnalyzers/DocumentationAnalyzers](https://github.com/DotNetAnalyzers/DocumentationAnalyzers). I believe [DOC203](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/DOC203.md) is the rule that flags misuse of `<code>` elements, and a code fix is provided to convert them to `<c>`. Here's the [unit test](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/99e70d0bbc4d9fe006bc453f47be616cbc2248f5/DocumentationAnalyzers/DocumentationAnalyzers.Test/PortabilityRules/DOC203UnitTests.cs#L32-L59) for this specific case.

**Comment by roji** [comment]
Thanks @sharwell, opened https://github.com/dotnet/efcore/issues/21094 to track.

**Comment by roji** [comment]
@sharwell, I'm seeing that the [DotNetAnalyzers.DocumentationAnalyzers](https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers) was last released in 2018, and the latest version is still a beta. Is this the right package, and if so, is it being updated?
