### ISSUE TITLE
"Committing transaction" is logged twice

### ISSUE THREAD

**Issue by m00ndark** [dotnet/efcore#20859]
When a transaction is committed, "Committing transaction" is logged twice for category "Microsoft.EntityFrameworkCore.Database.Transaction". Likely due to incorrect resource string in https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Properties/RelationalStrings.resx#L200. "LogCommittedTransaction" and "LogCommittingTransaction" have the same value.

### Steps to reproduce

1. Setup a logger factory in `OnConfiguring` that logs all levels of "Microsoft.EntityFrameworkCore.Database.Transaction" category
2. Modify your entities and save changes
3. Note that your logger logs "Committing transaction." twice for category "Microsoft.EntityFrameworkCore.Database.Transaction"

### Further technical details

EF Core version: 3.1.3
Database provider: FirebirdSql.EntityFrameworkCore.Firebird
Target framework: .NET 4.8
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.1

**Comment by roji** [comment]
Thanks for flagging this, submitted a fix.
