### ISSUE TITLE
Owned Type inside an owned type

### ISSUE THREAD

**Issue by fabianus76** [dotnet/efcore#20850]
Could it be, that ef does not permit to have a property of a type that is owned in an owned type?
If so, this should be changed. Why wouldn't it be desiderable to be able to use a portion of something reusable inside of something else that is reusable? 

If not the case, please make owned types possible inside of owned types.

**Comment by ajcvickers** [comment]
@fabianus76 This is supported. If you're having an issue with this, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by fabianus76** [comment]
@ajcvickers - thanks a lot for your feedback. An error message made me think this but thanks to your feedback I could discovered the problem that led to the misleading error message.
