### ISSUE TITLE
Random data corruption and UseLazyLoadingProxies

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/efcore#20857]
Hello, I'm back with data corruption using EF Core. However this time I can reliably re-create at will the data corruption and moreover it seem to be linked to UseLazyLoadingProxies.

### Steps to reproduce

1- Setup a database context with related entities and have the following relationship defined in OnModelCreating override method:
``` C#
            modelBuilder.Entity<User>(builder =>
            {
                builder.HasOne(e => e.Group)
                    .WithOne()
                    .HasForeignKey<User>(e => e.GroupId)
                    .IsRequired(false)
                    .OnDelete(DeleteBehavior.SetNull);
                builder.HasIndex(e => e.GroupId).IsUnique(false);
            });
            modelBuilder.Entity<Permission>(builder =>
            {
                builder.HasOne(e => e.Group)
                    .WithMany(e => e.Permissions)
                    .HasForeignKey(e => e.GroupId)
                    .IsRequired(true)
                    .OnDelete(DeleteBehavior.Cascade);
            });
```
2- In the Startup service add UseLazyLoadingProxies to the AddDbContext options and use a SQL server (Azure for example).
3- Have at least 10 entries in the User database table. Make sure ALL these entries have a valid GroupId.
4- Have a controller using newtonsoft JSON that stores a reference to an entry in this User table.
5- In the same controller create a function that updates an entry in this User table to change the variable Group to another Group that is already in use by the current user stored in the controller.
6- Call SaveChangesAsync on the Database context after change of the Group variable.
7- Enjoy permanently corrupted/broken table User: the User that was stored in the controller got it's group set to null and groupid as well.
8- Repair database by issuing raw SQL commands in order to get back a valid GroupId.
9- In the same controller update the Group of a user with a Group that is already in use by another user.
10- Call SaveChangesAsync on the Database context after change of the Group variable.
11- Try to load again those two users entries with identical Group.
12- Enjoy the Group variable set to null on one of them while it clearly should not.
Note: This second bug does not permanently corrupt the database...
Note 2: The bugs only occurs when an update is performed and not when new entries are added...

These bugs of course may cause random null reference exceptions everywhere in the application.

### Further technical details

EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: 3.1
Operating system: Windows 10 x64 (SB2 15 inch/local development system) and Azure Web API App Service
IDE: Visual Studio 2019 Community 16.3.5

**Comment by roji** [comment]
@Yuri6037 can you please submit a simple runnable program that does the steps above? You seem to already have a clear scenario which you describe in text, it would be better to have it in code.

**Comment by Yuri6037** [comment]
Yeah! Great I just made it! I made a small ASP.Net Core project with EF Core 3.1.2 and as predicted it sees GroupId destroyed when it should absolutely not.

**Comment by Yuri6037** [comment]
[TestAppEFCoreCorruption.zip](https://github.com/dotnet/efcore/files/4587910/TestAppEFCoreCorruption.zip)

All the controller logic can be found in BotController in the Controllers folder

**Comment by roji** [comment]
Doesn't really matter - you can attach a file here on github, or link to a repo. Anything will do, but please keep the project minimal - clean out anything unrelated to the repro.

**Comment by Yuri6037** [comment]
Done just a raw zip with the entire solution

**Comment by roji** [comment]
@Yuri6037 your model seems to be badly configured. Here you are configuring EF Core for a one-to-one relationship between users and groups:

```c#
builder.HasOne(e => e.Group)
    .WithOne()
    .HasForeignKey<User>(e => e.GroupId)
    .IsRequired(false)
    .OnDelete(DeleteBehavior.SetNull);
```

However, in your Startup.cs you're adding many users to the same group. You probably want to do the following instead:

```c#
modelBuilder.Entity<Group>(b => b
    .HasMany<User>()
    .WithOne(u => u.Group)
    .HasForeignKey(u => u.GroupId));
```

Take a look at [our doc page on configuring relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships). In your model, a Group is like a Blog in our examples, and a User is like a Post.

**Comment by Yuri6037** [comment]
Strangely enough applying this change in local advertises an empty migration. I'll check if it changes anything however I will need at least 30 minutes to have Azure services update with the new code

**Comment by Yuri6037** [comment]
Thank you a lot that fixed the problem. The syntax seem a bit backward logic to me as instead of going from the user which has a group you go backward from group to user...
Anyways, maybe this should be given as warning when generating a database migration or when compiling to help the user know that the relations he designed might cause corruptions.
Do you think this would be a good idea?

**Comment by roji** [comment]
The way you configured your model isn't wrong in any absolute way, it just doesn't correspond to your needs or to how your application works. It's perfectly legitimate to set up a one-to-one relationship, but then you can't have multiple users in the same group... This is also why we can't really have a warning on it.
