### ISSUE TITLE
 请问如何在其他类使用ApiAuthorizationDbContext(非Controller)? How to use apiauthorizationdbcontext (non controller) in other classes?

### ISSUE THREAD

**Issue by laolaolulu** [dotnet/efcore#20851]
![xx](https://user-images.githubusercontent.com/33310261/81132355-b5636f80-8f80-11ea-9fdb-00705c1272b8.png)

**Comment by roji** [comment]
@laolaolulu I don't read Chinese, but you're missing a `base()` constructor all on your constructor. The two required parameters for the base constructor (DbContextOptions, IOptions<OperationalStoreOptions>) are typically managed by dependency injection, which injects them when instantiating your class. If you're not using dependency injection, you must provide these yourself in your application whenever you instantiate the context.

**Comment by laolaolulu** [comment]
Sorry, maybe the translation software I use is not very good;

My custom class does not use dependency injection apiauthorizationdbcontext. How should I connect to the database?

**Comment by laolaolulu** [comment]
> @laolaolulu I don't read Chinese, but you're missing a `base()` constructor all on your constructor. The two required parameters for the base constructor (DbContextOptions, IOptions) are typically managed by dependency injection, which injects them when instantiating your class. If you're not using dependency injection, you must provide these yourself in your application whenever you instantiate the context.

Sorry, maybe the translation software I use is not very good;

My custom class does not use dependency injection apiauthorizationdbcontext. How should I connect to the database?

**Comment by roji** [comment]
If you're not using dependency injection, you'll need to construct instances of DbContextOptions and IOptions&lt;OperationalStoreOptions&gt; yourself, and pass them to the constructor every time you want to instantiate the class.

For constructing DbContextOptions, [see this doc page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#constructor-argument). Here's a quick sample for constructing these two objects:

```c#
var optionsBuilder = new DbContextOptionsBuilder<MyContext>();
optionsBuilder.UseSqlServer("...");
var dbContextOptions = optionsBuilder.Options;

var operationalStoreOptions = Options.Create(new OperationalStoreOptions
{
    // Put options here
});
```

These would typically be constructed once when your application initialized, and then reused every time a new DbContext needs to be instantiated. However, note that ApiAuthorizationDbContext was designed to work with dependency injection - consider doing that instead.

I'm going to close this issue as nothing is needed from the EF Core side, hope this helped.
