### ISSUE TITLE
Assembly issue Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#20856]
While trying to simple EF Core SQL Server program to connect to database (using .UseSqlServer() call), I am getting below error at runtime. Compilation is fine. There seem to be many related issues opened but none of them seems to help!! Please let me know, what mistake I might be making to compile the program.

: 'Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'

My project has following line for Microsoft.Extensions.DependencyInjection.Abstractions.dll. Since the Microsoft.Extensions.DependencyInjection.Abstractions.dll has version 3.1.2, I added Version values, but even if I don't add the Version also, it reports the same error.

	<Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.2">
    <HintPath>C:\Users\user1\.nuget\packages\microsoft.aspnetcore.app.ref\3.1.2\ref\netcoreapp3.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>

Sample Program: Connection string proper value is provided in actual program

```c#
using Microsoft.EntityFrameworkCore;
using System;

namespace EFCoreSql
{
    class SchoolContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@@"Data Source=(machine_name)\<db instance name>;Initial Catalog=<db name>; Integrated Security=True;");
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var schoolContext = new SchoolContext();
        }
    }
}
```

**Comment by ajcvickers** [comment]
@deokershesh Pleas post your csproj file.

**Comment by deokershesh** [comment]
@ajcvickers, Kindly find csproj file contents below.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Win32.Registry">
      <HintPath>D:\corefx-release-3.1\artifacts\bin\Microsoft.Win32.Registry\netcoreapp-Windows_NT-Debug\Microsoft.Win32.Registry.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SqlClient">
      <HintPath>D:\corefx-release-3.1\artifacts\bin\System.Data.SqlClient\netcoreapp-Windows_NT-Debug\System.Data.SqlClient.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Permissions">
      <HintPath>D:\corefx-release-3.1\artifacts\bin\System.Security.Permissions\netcoreapp-Debug\System.Security.Permissions.dll</HintPath>
    </Reference>
	<Reference Include="Microsoft.Data.SqlClient">
      <HintPath>C:\Users\user1\.nuget\packages\microsoft.data.sqlclient\2.0.0-preview2.20084.1\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll</HintPath>
    </Reference>
	<Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>D:\EntityFrameworkCore\efcore-master\artifacts\bin\EFCore.SqlServer\x64\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
	<Reference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <HintPath>D:\EntityFrameworkCore\efcore-master\artifacts\bin\EFCore.SqlServer\x64\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.SqlServer.dll</HintPath>
    </Reference>
	<Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.2">
      <HintPath>C:\Users\user1\.nuget\packages\microsoft.aspnetcore.app.ref\3.1.2\ref\netcoreapp3.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <AssemblyInfoLines Include="[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute(System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior)]" />
  </ItemGroup>

</Project>

**Comment by deokershesh** [comment]
[MyApp.csproj.txt](https://github.com/dotnet/efcore/files/4588488/MyApp.csproj.txt)

**Comment by deokershesh** [comment]
Any help please?

**Comment by roji** [comment]
@deokershesh please try using regular <PackageReference> for nuget packages instead of <Reference>, which is for assemblies on your local filesystem - this way of consuming nuget packages is pretty much deprecated. Use the Visual Studio interface to add Nuget packages instead of editing the csproj yourself - the correct references should be added for you.

For example, to reference Microsoft.EntityFrameworkCore.SqlServer you should be having:

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version=3.1.2" />
```

Note that <PackageReference> and <Reference> need to live inside separate <ItemGroup> nodes. You also don't need to reference all the dependencies - simply referencing Microsoft.EntityFrameworkCore.SqlServer in this way will automatically bring everything else it needs (like Microsoft.Extensions.DependencyInjection.Abstractions).

**Comment by smitpatel** [comment]
```
 </Reference>
	<Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>D:\EntityFrameworkCore\efcore-master\artifacts\bin\EFCore.SqlServer\x64\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
	<Reference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <HintPath>D:\EntityFrameworkCore\efcore-master\artifacts\bin\EFCore.SqlServer\x64\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.SqlServer.dll</HintPath>
    </Reference>
````
EF Core master branch depends on 5.0 preview version of Microsoft.Extensions.DependencyInjection.Abstractions package.
Your csproj contains EF Core dependencies of version 3.1.2, It is not going to work. You need to upgrade all the dependencies to compatible version too.

**Comment by deokershesh** [comment]
Thanks smitpatel, I am relatively new to this whole space of EF Core/.NET Core to figure out the right dependencies. I have observed, as part of build process itself it downloads required .NET Core SDK versions.

Please could you provide hints about how to upgrade to compatible version in this case? By the way I already have below SDK version.. may be I need different runtime version?

c:\>dotnet --version
5.0.100-preview.2.20176.6

**Comment by roji** [comment]
@deokershesh dotnet --version shows the version of the dotnet SDK - this is what you use to compile your applications, and is not related to the EF Core version. EF Core is just another nuget package which your project depends on.

I suggest taking a look at some [nuget tutorials](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio) to better understand .NET package management. In the end you supposed to use your IDE (e.g. Visual Studio) to depend on packages like EF Core, and that will produce &lt;PackageDependency&gt; nodes in your csproj.
