### ISSUE TITLE
Allow migrations configuration to be automatically be picked up from a cloned repo

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20862]
I often want to use migrations after cloning a GitHub repo or downloading a VS solution in some other way. To do this I have to figure out which project is the startup, which project contains migrations, and possibly other settings. Instead I want that information to be carried with the VS solution. This would allow me to run, for example, `dotnet ef migrations add One` at the solution level and have it use the appropriate projects and other settings.

This could be done in one of several ways:
* A config file at the solution level that EF reads
* Support for generating and using "response files" automatically
* Support for generating and using a well-known script automatically

This will also require documentation to promote this as a well-known pattern that becomes commonly used.

**Comment by Saibamen** [comment]
Related: https://github.com/dotnet/efcore/issues/21106?

**Comment by bricelam** [comment]
A possible implementation: #22203

**Comment by bricelam** [comment]
Just to publicly state my stance on this, I don't think we'll ever be able to provide something that's more discoverable or simple than a script file can provide.

For example, by creating a file named `ef.cmd` (or an equivalent .sh file on macOS and Linux) in the root of your project with contents like the following:

```cmd
@dotnet ef --project MyApp.Data --startup-project MyApp %*
```

And using commands like the following:

```cmd
ef migration add MyMigration
ef database update
```

Or if you have multiple contexts or projects, use response files. For example create a file named `identity.rsp` with the following contents.

```
--context=IdentityContext
--project=MyApp.Data
--startup-project=MyApp
```

And use it like this:

```cmd
dotnet ef database update @identity.rsp
```

**Comment by ajcvickers** [comment]
@bricelam Maybe its just a matter of good docs/guidance on how to do this.

**Comment by ntziolis** [comment]
I agree that scripts provide an easy way to figure out what should be done.

That said a couple of downsides are:
- Its project specific instead of stack specific
- It requires project owners to take care of multiple platforms. Looking at node this has not worked well as many projects still do not provide ability to build on windows without manually converting shell scripts (thanks to wsl this has become a non issue). 

So there is a case to be made for the dotnet cli as a whole (not just ef cli) to allow specifying default profiles for commands. Similar to the response files but platform independent.

**Comment by ajcvickers** [comment]
Note from triage: scenarios better handled in other ways.

**Comment by KoshelevS** [comment]
The approach with RSP file did not worked for me. dotnet command refused to recognize arguments from the RSP file I created. But the approach with a CMD file in the root folder works as expected (but with a minor change):
```cmd
@dotnet ef %* --startup-project ./src/App --project ./src/App.DataAccess --context App.DataAccess.AppDbContext
```

**Comment by durmazoguzhan** [comment]
> Just to publicly state my stance on this, I don't think we'll ever be able to provide something that's more discoverable or simple than a script file can provide.
> 
> For example, by creating a file named `ef.cmd` (or an equivalent .sh file on macOS and Linux) in the root of your project with contents like the following:
> 
> @dotnet ef --project MyApp.Data --startup-project MyApp %*
> And using commands like the following:
> 
> ef migration add MyMigration
> ef database update
> Or if you have multiple contexts or projects, use response files. For example create a file named `identity.rsp` with the following contents.
> 
> ```
> --context=IdentityContext
> --project=MyApp.Data
> --startup-project=MyApp
> ```
> 
> And use it like this:
> 
> dotnet ef database update @identity.rsp

@bricelam  really? are u kidding??
we cannot make progress with this perspective.
sometimes something is not about us, we're working on teams. will i recommend this solution for all of my team members and saying it is the best-practice? please look a little bit engineering mindset and perspective.

**Comment by bricelam** [comment]
Not kidding. Check in your scripts and show your team how to use them.

GitHub Copilot is my only engineering mindset now.
