### ISSUE TITLE
Creating table dynamically in database during runtime from .netcore 2.2 boilerplate

### ISSUE THREAD

**Issue by vinodhboston** [dotnet/efcore#20865]
I need sample solution or reference for creating table dynamically in database during runtime using .netcore 2.2 with angular 8 and  entity framework.

could you please suggest.

**Comment by ajcvickers** [comment]
@vinodhboston Likely EF doesn't have built-in support for dynamically creating tables at runtime.

Also, note that .NET Core 2.2 is now [out-of-support](https://dotnet.microsoft.com/download/dotnet-core). You should move to 3.1.
