### ISSUE TITLE
Shouldn't EF Core use BETWEEN for integer like enum constraints and not IN?

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#20868]
Referring to this feature: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#generation-of-check-constraints-for-enum-mappings.

I suppose that many as I use an integer for storing enums and not strings as in the example. If an integer type is used and it's an unbroken interval of integers, shouldn't BETWEEN be used instead of IN because if the enum may have many values, you will get a long enumeration of values for IN?

**Comment by roji** [comment]
@henrikdahl8240 in C# you can define arbitrary integer values for enums, so there's no guarantee that enum values are contiguous. Using BETWEEN would potentially allow invalid values to slip in because of gaps in the enum integer values.

**Comment by henrikdahl8240** [comment]
@roji, Yes, it's clear, but an enum cannot change without bringing the need for a new migration. Therefore the optimal choice can just be done when adding a new migration. When adding a new migration, it can easily be checked, if the values of the enum constitute a contigous range of integers. If that is the case, you can use BETWEEN and otherwise fallback on IN.

I would like to add, that the reason I suggest it at all is, that I assume, that BETWEEN is O(1) and IN is O(n). If I am right in this assumption, I suppose it's obvious, that use of BETWEEN is to be preferred when the enum constitutes a contigous range of integers.

You don't generally agree in these considerations?

**Comment by roji** [comment]
I agree - it's a valid optimization for cases of numeric-backed enums with a large number of values. Note that there's a bit of complexity, as the check for numeric contiguity has to happen after any value converters have already been applied, and not on the CLR enum values themselves.

Are you interested in contributing this?

**Comment by henrikdahl8240** [comment]
Somewhere there must be some code, which produces the IN statement and the BETWEEN statement is a perfect substitute if the values for IN constitute a contigous range of integers.

I have for example cases like this in the code produced by Add-Migration:
`b.HasCheckConstraint(..., "[ValueFormat] IN(0, 1, 2, 3, 4, 5, 6, 7, 8)");`

Isn't the case, that somewhere there is some code, which produces the condition for the constraint and today it unconditionally produces an IN statement. It's clear from the example, that at this location, there is already knowledge, that the problem is concerned with integers and not strings because there are no quotes around the arguments for IN.

Could it be done by simply just producing the condition using a bit context, like this:
Today:
1. Produce IN with the enumerated values.

Tomorrow:

1. Check if the arguments in question denote a contigous range of integers.
2. Yes: Produce: BETWEEN "min-value" AND "max-value", i.e. of the values otherwise used for IN.
3. No: Fallback situation, Produce IN as today.

If you don't have a better idea for determining if the set of integers constitute a contigous range, you can probably do it like this:

1. Put all the values normally used for IN to a set of integers.
2. Determine "min-value" and "max-value" of the set, e.g. using LINQ.
3. If "max-value" - "min-value" + 1 == size of set, the set of integers denotes a contigous range of integers.

I don't have specific knowledge how Entity Framework Core works internally. Is you find my approach reasonable and you think it's just a matter of enhancing the algorithm as I write, I can easily spend a few minutes doing that. Perhaps you could send me a link for the file and I can just mail the result to you, because I have never worked with github, because I have just had other interests.

Do you find my considerations reasonable?

**Comment by ErikEJ** [comment]
Do you have any evidence of any performance benefits of this proposed change?

**Comment by henrikdahl8240** [comment]
@ErikEJ, The best would obviously be if there would be no performance benefit because SQL Server would just realize, that the arguments for IN constitute a range and therefore execute it as it would do with BETWEEN.
I have not found such information, but I have found this https://blog.sqlauthority.com/2018/06/13/sql-server-performance-comparison-in-vs-or/ and if it's the case for any kind of IN argument list, i.e. that there is just produced an expression where the comparisons against arguments are all OR'ed together it's clear that BETWEEN is superior.
Can you refer to information, that SQL Server is doing this kind of contextual optimization?

**Comment by henrikdahl8240** [comment]
@ErikEJ Basically it's obviously this kind of nature we talk about: https://stackoverflow.com/questions/3308280/is-there-a-performance-difference-between-between-and-in-with-mysql-or-in-sql-in, however it does not address potential specifics of Microsoft's SQL Server.
The case probably rather is, that BETWEEN always results in the best performance possible and IN can be as quick if it's executed in a clever way, which is the reason I asked you, if you have such knowledge concerning SQL Server.

**Comment by roji** [comment]
Simplest thing would be to write a benchmark and measure...

FYI here's the code doing the constraint generation: https://github.com/dotnet/efcore/pull/17798/files

**Comment by henrikdahl8240** [comment]
Referring to https://github.com/dotnet/efcore/issues/20880 I do not intend to spend the small amount of time for this enhancement, despite I can see, that it can easily be done as I imagined because I will not opt-in for the check constraint.

@roji Thank you for the reference.

**Comment by roji** [comment]
@henrikdahl8240 that's very understandable. FWIW there may still be a bit of value in doing this change in the plugin - for big enums with contiguous values it's possible this would provide a perf benefit (or at the very least make for terser SQL). If you like, open this issue on https://github.com/efcore/EFCore.CheckConstraints, and even if it's in backlog someone may do it at some point.

In any case I'll go ahead and close this on the EF Core side. Thanks again for your suggestion!

**Comment by henrikdahl8240** [comment]
@roji Please allow me to add one more comment. The code you referred to has this fragment:
```
foreach (var item in enumValues)
{
    var value = ((RelationalTypeMapping)typeMapping).GenerateSqlLiteral(item);
    sql.Append($"{value}, ");
}

sql.Remove(sql.Length - 2, 2);

```
So the idea is to imperatively build something you don't want and then you remove, what you didn't want.

All this code is just a matter of doing String.Join(", ", ...).

Therefore it ought to be programmed like that instead, i.e. using String.Join(). This will result in one concise line of code instead of the current approach which is vulnerable to small adjustments like e.g. removing the semantically irrelevant space.

**Comment by roji** [comment]
@henrikdahl8240 I completely agree - I merely moved all this code out to the plugin at https://github.com/efcore/EFCore.CheckConstraints. Are you interested in submitting a PR to that repo to fix this?

**Comment by roji** [comment]
Note: opened https://github.com/efcore/EFCore.CheckConstraints/issues/3 to track this.
