### ISSUE TITLE
Move enum check constraints convention to relational?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20878]
We now generate check constraints for enums (#15411), but that code is in the SQL Server provider. Since our check constraint support is in relational and there's nothing really SQL Server-specific about this, why not have the convention in relational for use by other providers?

Sqlite does not support altering/dropping check constraints so it should not have it - but we could remove that convention there (or possibly not add it to the relational convention set by default, but still allow providers to add the convention from relational).

(small note: PG would need a modified version anyway because of native enums, for which we don't want this - so ideally the convention would be refactored slightly to be reusable)

**Comment by ajcvickers** [comment]
@roji We talked about this at the time and decided that the form of this particular convention was pretty SQL Server specific, even though check constrains in general is a relational concept. From what you said above, this still seems like the right choice.

**Comment by roji** [comment]
I agree that this convention wouldn't be on by default, but I'm not sure why we wouldn't include the class itself in relational... This way any provider that wishes to use it can simply reference it from their own convention set (all providers except Sqlite could). The PG issue is a minor issue of refactoring it to allow overriding the decision making on when the constraint should be generated vs. the actual logic for generating the constraint.

**Comment by roji** [comment]
As per design discussion, closing in favor of #20897.
