### ISSUE TITLE
New EF Core Provider

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#20871]
I believe this is not the right category/place to possibly ask this question, but I believe I could get some hint to move forward...

I am trying to create EF Core provider for one relational database. There seem to be many issues, with respect to incompatibilities of dependent assemblies, even only little info available as to how to get started writing one and also build issues I observed.

Is there anyway, I could reach out to some specific team/person and can have call/chat with them?

**Comment by ajcvickers** [comment]
@deokershesh [This issue](https://github.com/dotnet/EntityFramework.Docs/issues/681) is tracking improving the documentation for writing a provider. Beyond that, the best way forward is to copy what the successful community providers are doing--most notably [efcore.pg for PostgreSQL](https://github.com/npgsql/efcore.pg) and [the Pomelo MySQL provider](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql). You should structure the layout, build, and testing of your provider in a similar way.

Note that creating an EF Core provider can be complicated and difficult. It should really only be attempted by somebody with a relatively deep knowledge of EF Core _and_ a deep knowledge of the target database system.
