### ISSUE TITLE
EFCORE 3.1 - Logger property missing in QuerySqlGeneratorDependencies"

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#20873]
I am developing a EFCore 3.x provider for Oracle. I want to put some custom traces in one of my classes which inherits from `QuerySqlGenerator`.
In EFCORE 2.x, one of the constructor parameter `QuerySqlGeneratorDependencies` has the 'Logger' property which can be utilized for generating custom traces.
But in EFCORE 3.x, it seems to be missing.
I see some other classes (Ex:- `ModificationCommandBatchFactoryDependencies`) still have this Logger property which can be used to generate custom traces. So I am not sure why the Logger property has been removed from `QuerySqlGeneratorDependencies` class.
I tried passing some optional arguments in the constructor of `OracleQuerySqlGeneratorFactory `which inherits from `QuerySqlGeneratorFactory`
(For Ex:- `IDiagnosticsLogger<DbLoggerCategory.Query> query_logger = null`) but it didn't help.
 I always get "`query_logger.Logger.IsEnabled(LogLevel.Trace)`" condition as false.
So I am not able to generate traces related to QuerySqlGenerator. Is there any alternative/workaround in EFCore 3.1 to achieve the same.

Here is the Context class used by the sample application-

```C#
public class BloggingContextWithFiltering : DbContext
  {
    public static readonly ILoggerFactory MyLoggerFactory
        = LoggerFactory.Create(builder =>
        {
          builder
                  .AddFilter((category, level) => level == LogLevel.Trace)
                  .AddDebug();
        });
    public DbSet<Blog> Blogs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseOracle("<connection string>").UseLoggerFactory(MyLoggerFactory);
    }
}
```
### Further technical details

EF Core version: Microsoft.EntityFrameworkCore 3.1.3
Database provider: 
Target framework:  .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by smitpatel** [comment]
Dependencies objects contains dependencies used in the type. If you need additional services in your type then inject them directly.

**Comment by shvmgpt116** [comment]
@smitpatel Thanks for the update. I am not very familiar on how to inject services in a type. Is there anything similar present in Sql Server provider which I can use as a reference?

**Comment by ajcvickers** [comment]
@shvmgpt116 EF Core uses common concepts from [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/5.0.0-preview.3.20215.2), most notably dependency injection. You'll probably want to have a pretty good understanding of how this works before attempting an EF Core provider. It's worth noting that creating an EF Core provider can be complicated and difficult. It should really only be attempted by somebody with a relatively deep knowledge of EF Core _and_ a deep knowledge of the target database system.

**Comment by shvmgpt116** [comment]
As hinted out in my original post, I have already tried constructor dependency injection. But it did not work.
I tried passing some optional arguments in the constructor of OracleQuerySqlGeneratorFactory which inherits from QuerySqlGeneratorFactory
(For Ex:- IDiagnosticsLogger<DbLoggerCategory.Query> query_logger = null) but it didn't help.
I always get "query_logger.Logger.IsEnabled(LogLevel.Trace)" condition as false.
This code works perfectly fine with EFCORE 2.x, but does not work with EFCORE 3.x.

**Comment by ajcvickers** [comment]
@shvmgpt116 You're running into this breaking change: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#ilf

Since loggers are now scoped they cannot be depended on directly by singleton services.

@smitpatel Do we ever do our own logging during SQL generation? If so, can you point me to the code?

**Comment by smitpatel** [comment]
We don't log during SqlGeneration.

**Comment by ajcvickers** [comment]
@shvmgpt116 We discussed this and we will consider adding back a way to log in SQL generation in a future release. Could you explain some more about what you are logging and why is makes sense to log here rather than in query translation?

**Comment by shvmgpt116** [comment]
In general, we use tracing to track the flow of the app within our provider.
We generate query's so that they are compatible with the version of the Oracle DB that the customer is using. Hence we log any useful information in relation to this.
We also log any other information that will help us diagnose issues reported by customers especially when reproducible test cases are not available.
**Please could you also consider adding the log capability to these classes mentioned below.**
1)  AnnotationCodeGenerator
2)  RelationalModelValidator
3)  MigrationsAnnotationProvider
4)  RelationalCompiledQueryCacheKeyGenerator
5)  RelationalSqlGenerationHelper
6)  ValueGeneratorCache
7)  RelationalValueGeneratorSelector
8)  RelationalMemberTranslatorProvider
9)  RelationalMethodCallTranslatorProvider
10) IQuerySqlGeneratorFactory
11)  RelationalCommandBuilderFactory
12)  RelationalTypeMappingSource
	**This class can use logger to trace various types properties like:- IsUnicode, IsKeyOrIndex, IsFixedLength, Scale, Precision, Size, ClrType, StoreTypeNameBase, StoreTypeName, IsRowVersion, StoreTypeNameBase**
13)  UpdateSqlGenerator, IOracleUpdateSqlGenerator
	**This class can use logger to trace schema name, table name and modification commands operation**

**Comment by ajcvickers** [comment]
The scoping of many services has changed since this issue was opened, allowing the logger to be injected into more places. Requests to add the logger for specific cases should be made by filing new issues, indicating exactly where the logging it needed.
