### ISSUE TITLE
Could not load file or assembly 'System.ValueTuple , Version=4.0.3.0

### ISSUE THREAD

**Issue by pas059** [dotnet/efcore#20874]
Hello,
I'm trying to upgrade a project which targets .net 4.7.2 and which used EFcore 2.26, to EFcore 3.1.3.

The buid is now ok, but durig execution, and as soon as i try to create a DBcontext i get an exception

"Une exception a été levée par l'initialiseur de type pour 'Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache'."
the inner exception message is:
Impossible de charger le fichier ou l'assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ou une de ses dépendances. Le fichier spécifié est introuvable.

the stacktrace:
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache..cctor()

As suggested in other posts, i added the following lines in the app.config file:

`			<dependentAssembly>
				<assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
		  </dependentAssembly>
`
but this change nothing for me.

Someone can help?
thanks in advance,
Pascal

### Further technical details

EF Core version: 3.1.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 4.7.2)
Operating system: W10
IDE: (e.g. Visual Studio 2019CE 16.5.4)

**Comment by roji** [comment]
Can you please post your full csproj file?

**Comment by pas059** [comment]
Hi roji,
As the csproj is big file (>3000lines), i prepared one from the original  from which i removed the parts that concern my own addition files and let only the configuration on which i work (x64 debug); nevertheless, it remains near than 300 lines.
I remarked that at the end, it is indicated that some nuget packages are missing (SQLite3xxxxxxx) and some of them are strange (linux, OsX ??)
[MyEFc3App.zip](https://github.com/dotnet/efcore/files/4593077/MyEFc3App.zip)

regards
Pascal

**Comment by bricelam** [comment]
Does it work if you [migrate to PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)? There are several known limitations with using packages.config

**Comment by pas059** [comment]
Hi,
after migrating from packages.config to PackageReference, this exception no longer appears. Thanks for your suggestion Brice!

But now, i have a 'System.NullReferenceException ' on a line
`modelBuilder.Owned<global::EFc3AppSp.DB.RealData4>();`
 in my OnModelCreating() method which is generated by 'Entity Framework visual editor'.
But this is probably another issue, perhaps due to a problem of modeling migration from EFc 226 to EFc 313;
any idea?

thanks again,
regards
Pascal

**Comment by roji** [comment]
@pas059 if you can see this error when running your program, please open a new issue with a short sample showing what you're doing - an exception isn't enough to go on.

If this is only an issue you get when using the Entity Framework Visual Editor, please contact the maintainer of that tool.
