### ISSUE TITLE
Mocking Entry method of DbContext is hard

### ISSUE THREAD

**Issue by alisabzevari** [dotnet/efcore#2088]
Many of methods in DbContext are virtual. So they can be mocked using Moq or similar frameworks. But Entry is not virtual. [Searching the net](http://www.asp.net/web-api/overview/testing-and-debugging/mocking-entity-framework-when-unit-testing-aspnet-web-api-2#dependency) made me accept that the better way to mock this method is to write a `MarkAsModified` method in our DbContext. I think this is not a clean way. Is it possible to make Entry method as virtual or create IDbContext interface?

**Comment by divega** [comment]
@alisabzevari

**Comment by divega** [comment]
@alisabzevari It seems `Entry()` is already virtual in EF7. I will assume that you are asking about making in virtual in EF6 as well, correct?

**Comment by alisabzevari** [comment]
Yes I was talking about EF6. I thought they migrated EF6 to github. Seems like it is in codeplex yet.

**Comment by divega** [comment]
Yeah, we haven't moved EF6 tracking to GitHub, at least not yet. In the meanwhile I copied this issue to https://entityframework.codeplex.com/workitem/2741.

**Comment by rowanmiller** [comment]
@alisabzevari can you see https://entityframework.codeplex.com/workitem/2741 as we have a question on the request
