### ISSUE TITLE
Move enum constraints convention out of EF Core to a plugin

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20897]
#15411 added a convention to create database check constraints for enums. We've decided this would be more appropriate for an external plugin for the following reasons:

* Check constraints have a perf impact, and if the database is only accessed by EF they aren't needed. A plugin would provide an explicit opt-in for this.
* The current convention is SQL Server-specific, but could be used on other databases as well (#20878).

**Comment by roji** [comment]
PR: https://github.com/efcore/EFCore.CheckConstraints/pull/1

**Comment by smitpatel** [comment]
@roji - I think you already completed this work item.

**Comment by roji** [comment]
Thanks @smitpatel.
