### ISSUE TITLE
Review usage of <c></c> for keywords in XML docs

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20891]

**Comment by AndriySvyryd** [comment]
@wadepickett @scottaddie @mairaw @JasonCard Is there guidance for whether we should enclose keywords like `false`, `true` and `null` in <c></c> tags in XML docs to improve localization?

**Comment by mairaw** [comment]
You should be use see langword for those instead: `<see langword="true" />`

Here's an example:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web/HttpBrowserCapabilitiesBase.xml#L94

`<c>` for other elements that are not language keywords.

**Comment by AndriySvyryd** [comment]
@mairaw Thanks!
