### ISSUE TITLE
RevEng: Move Templating Code to Commands package

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#2091]
Move the code under https://github.com/aspnet/EntityFramework/tree/dev/src/EntityFramework.Relational.Design/Templating to be in the Commands package instead. So that it is more reusable.

**Comment by bricelam** [comment]
We should generally put all design-time code in the Commands package. The *.Design packages are intended to only contain the contracts/common implementations that providers derive from to participate in design-time scenarios.

**Comment by lajones** [comment]
@bricelam We might want to talk about package naming. I'm not sure that would be obvious to other developers.

**Comment by bricelam** [comment]
We discussed previously: (See [Design Meeting Notes - September 11, 2014])(https://github.com/aspnet/EntityFramework/wiki/Entity-Framework-Design-Meeting-Notes---September-11,-2014#migrations-commands-high-level-experience)

> The package name in git is currently EntityFramework.Design. However, we discussed other names and settled on EntityFramework.Commands since this code is used for the PowerShell, Project K, and executable commands. The .Design posfix makes it seem like System.Data.Entity.Design or similar packages/assemblies ... We also considered EntityFramework.Tools, but this would likely cause confusion with Visual Studio tooling. Note that while we are discussing Migrations here the actual package will likely also include non-Migrations commands.

**Comment by lajones** [comment]
@bricelam I meant we should discuss renaming the *.Design packages.

**Comment by lajones** [comment]
Discussed with @bricelam. Just moving the Templating code to Commands causes a circular dependency between Relational.Design and Commands. So leaving it where it is and closing this issue for now. But we agree there ought to be an API review where we decide what lives where.
