### ISSUE TITLE
Owned entity troubles

### ISSUE THREAD

**Issue by pas059** [dotnet/efcore#20913]
Hi,
After updating an application from EFcore 226 to EFcore 313, during the execution of my OnModelCreating() method i get a 'System.NullReferenceException ' exceptionS on the line

`modelBuilder.Owned<global::EFc3AppSp.DB.RealData4>();`

The RealData4 is a dependant entity used in 2 others entities: 11 times in the first and 23 in the second. In fact, i got 23  'System.NullReferenceException ' exceptions at this line (?). As, this code works fine with EFcore 226, i wonder what's happen ; can always an owned entity be used in several entities?

Any idea?
Thanks, 
Pascal

### Further technical details

EF Core version:3.1.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlLite)
Target framework: (e.g. .NET Core 4.7.2)
Operating system:W10pro
IDE: (e.g. Visual Studio 2019CE 16.5.4)

**Comment by ajcvickers** [comment]
@pas059 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by pas059** [comment]
Hi,
this will be defecult to extract such code from my (large) project. But in addition, i noted that for another owned entity, for which there is a call to modelBuilder.Owned<...>(), that apparently creates no problem. This other owned entity is defined and used in the same way, but there are differences in the definition of my RealData4 entity which contains some nullable properties, for instance:
`      public double? Average { get; set; }
`
and not the other owned entity. Perhaps it's a direction to investigate?

regards

**Comment by pas059** [comment]
Hi again,
I modified the model of my RealData4 entity by changing all the nullable properties to [Required], but this changes nothing. 
Other differences compared to my other owned entity, is that RealData4 entity is used in 2 other entities (1 for my other owned entity), and that it is used much many more times.

regards

**Comment by pas059** [comment]
Hi,
Finally, i think that this problem was a consequence of another problem.
These entities were owned by another entity which is itself owned by .... another entity which is inherited from a pure abstract class that has no DBset; this works with EFc226 but apparently creates some troubles with EFc313. So i changed that.

I also take this "oppertunity" to change the use my RealData4 by using OwnsMany rather than n times OwnsOne; this creates another table containing all RealData4 instances (one by line) but no matter (i hope).

regards
Pascal
