### ISSUE TITLE
ToDictionary pulling entire table instead of selected columns

### ISSUE THREAD

**Issue by meyerovb** [dotnet/efcore#20928]
I'm pretty sure ToDictionary in a former EF version selected just the relevant columns.  Now when I do:

context.Set<Table1>().ToDictionary(a => a.PKCol, a => a.Col1);

The select pulls in all of Table1 instead of just PKCol and Col1

**Comment by roji** [comment]
@meyerovb this used to pull back the entire table in previous versions too. ToDictionary is method over IEnumerable - EF Core cannot translate it to SQL and cannot be aware of the lambdas you are using to project the keys and values.

You can use a Select to tell EF Core to project out only the two columns:

```c#
var result = ctx.Blogs
    .Select(b => new { b.PKCol, b.Col1})
    .ToDictionary(a => a.PKCol, a => a.Col1);
```

**Comment by roji** [comment]
@ajcvickers @smitpatel aside from proposing an IQueryable ToDictionary, there isn't anything to be done here. Suggest closing as closed-external.
