### ISSUE TITLE
Incorrect StoreGenerationIndex is set when more than two entity types share the same owned collection

### ISSUE THREAD

**Issue by jangezelius** [dotnet/efcore#20932]
Given 3 or more parent entity types that all have an owned collection of the same child entity type, when EF Core creates the UniqueProperty to use in the key for this owned collection, the StoreGenerationIndex is correctly set to 1 for the first 2 parent entity types, but for every parent entity type thereafter, StoreGenerationIndex is -1. 

This causes EF Cosmos to fail to set the ordinal key value, since the property is not considered having a TemporalValue, leading to the error 
```System.InvalidOperationException: The instance of entity type 'Parent3Entity.Children#ChildEntity' cannot be tracked because another instance with the key value '{Parent3EntityId: <guid>, Id: 0}' is already being tracked.```

### Steps to reproduce

Define at least 3 entity types like this:
``` C#
    public class Parent1Entity
    {
        [Key]
        public Guid Id { get; set; }
        public ICollection<ChildEntity> Children { get; set; }
    }
    public class Parent2Entity
    {
        [Key]
        public Guid Id { get; set; }
        public ICollection<ChildEntity> Children { get; set; }
    }
    public class Parent3Entity
    {
        [Key]
        public Guid Id { get; set; }
        public ICollection<ChildEntity> Children { get; set; }
    }
    public class ChildEntity
    {
        public string Name { get; set; }
    }
```
And a DbContext with an OnModelCreating like this:
``` C#
   protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Parent1Entity>().OwnsMany(p => p.Children);
        modelBuilder.Entity<Parent2Entity>().OwnsMany(p => p.Children);
        modelBuilder.Entity<Parent3Entity>().OwnsMany(p => p.Children);
    }
```
Then this code:
``` C#
    foreach(var entityType in _context.Model.GetEntityTypes())
    {
        if (entityType.DefiningEntityType == null)
            continue;
        sb.AppendLine($"EntityType: {entityType.DisplayName()}");
        var idProperty = entityType.FindProperty("Id");
        sb.AppendLine($"\tProperty: {idProperty.Name}");
        sb.AppendLine($"\t\tStoreGenerationIndex: {idProperty.GetStoreGeneratedIndex()}");
        sb.AppendLine();
    }
```
Will give this output:
```
EntityType: Parent1Entity.Children#ChildEntity
	Property: Id
		StoreGenerationIndex: 1

EntityType: Parent2Entity.Children#ChildEntity
	Property: Id
		StoreGenerationIndex: 1

EntityType: Parent3Entity.Children#ChildEntity
	Property: Id
		StoreGenerationIndex: -1
```
Any additional entity types will have the same property values as for Parent3Entity.

Since `DocumentSource.CreateDocument()` in `Microsoft.EntityFrameworkCore.Cosmos.Update.Internal` only assigns the ordinal key to an Id property if it is considered a TemporalValue, the assignment will break. 

#### Workaround
Add the id property and create the composite key manually for the owned collections, like this:
```
    modelBuilder.Entity<Parent3Entity>().OwnsMany(p => p.Children, c => 
        {
            c.Property<int>("OrdinalId");
            c.HasKey("Parent3EntityId", "OrdinalId");
        });
```

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.1

**Comment by ajcvickers** [comment]
Poaching
