### ISSUE TITLE
While using condition - A relational store has been configured without specifying either the DbConnection or connection string to use

### ISSUE THREAD

**Issue by jkyadav** [dotnet/efcore#2093]
Hi,
I am trying to work with EF7 I have configured all the setting in config.json and Startup.cs,

Able to add and apply migration.
1- while changing the field length it does not apply on database, code looks like 

``` C#
[StringLength(100)]
public string Text { get; set; }
```

2- When I am writing where condition over entity getting this error "A relational store has been configured without specifying either the DbConnection or connection string to use"
My code looks like 

``` C#
TestContext db = new TestContext();
var cust = db.Customers.Where(x => x.id == text).FirstOrDefault();
```

What am doing wrong here?

Any help..

**Comment by ErikEJ** [comment]
Re 1: Attributes are not yet implemented, you can use the Fluent API

**Comment by jkyadav** [comment]
Ok

**Comment by bricelam** [comment]
What does your `DbContext` look like? What does your `Startup.cs` look like? Do you have any config files? What do they look like?

**Comment by jkyadav** [comment]
I am using EF 7..
My context looks like ;

public class TestContext : DbContext
	{
		public DbSet<Contact> Contacts { get; set; }
		public DbSet<Customer> Customers { get; set; }

		public TestContext ()
		{
		}
		protected override void OnConfiguring(DbContextOptions options)
		{
			options.UseSqlServer();
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
		}
	}

My startup.cs looks like 

public class Startup
	{
		public Startup(IHostingEnvironment env)
		{
			Configuration = new Configuration()
				.AddJsonFile("config.json")
				.AddEnvironmentVariables();
		}

		public IConfiguration Configuration { get; set; }

		public void ConfigureServices(IServiceCollection services)
		{
			services.AddEntityFramework(Configuration)
				.AddSqlServer()
				.AddDbContext<TestContext>();
			services.AddMvc();
		}
}

And this is my config.json
{
	"Data": {
		"DefaultConnection": {
			"ConnectionString": "Server=.sqlexpress;Database=testdb; user id= test; password=test;MultipleActiveResultSets=true"
		}
	},
	"EntityFramework": {
		"TestContext": {
			"ConnectionString": "Data:DefaultConnection:ConnectionString"
		}
	}
}

**Comment by TravisMeyers** [comment]
You need to update your services.AddEntityFramework.* line in ConfigureServices() method to this:

services.AddEntityFramework(Configuration)
            .AddSqlServer()
            .AddDbContext<TestContext>(options =>  options.UseSqlServer(Configuration.Get("Data:Defaultconnection:ConnectionString")));

This is for beta3, there was a change in beta4 that removes the need of passing Configration to AddEntityFramework.

**Comment by jkyadav** [comment]
@TravisMeyers  have tried above solution, unfortunately it does not work, if we need to specify connection string manually in Startup.cs file then why we need to write these lines "EntityFramework": {"TestContext": {"ConnectionString": "Data:DefaultConnection:ConnectionString"} in config.json? What is the use of these lines?

**Comment by TravisMeyers** [comment]
Sorry my earlier suggestion didn't help, that had worked for me when I received that error message before. As for your question of what is the use of those lines in the `config.json`... In beta4 the `"EntityFramework"` section is no longer inserted during scaffolding. And `.AddEntityFramework()` is now parameter-less, so you can't pass in `Configuration`. Welcome to beta software... :construction:

I would suggest you upgrade to beta4 and try again from a fresh project.

**Comment by jkyadav** [comment]
Ok, great..

**Comment by rowanmiller** [comment]
As discussed by others this is all changed in Beta 4. Feel free to reactivate if you still have issues.

**Comment by jkyadav** [comment]
Thanks @rowanmiller  I will reactivate ..

**Comment by jkyadav** [comment]
@rowanmiller  I have reactivated EF beta4 still seems Data Annotation not working..
If I try to write below code

[StringLength(100)]
public int Text { get; set; }

Still it sets Text size as MAX.

Can you please let me know what all I need to change to make this working using EF beta4.

**Comment by ErikEJ** [comment]
@jkyadav  Do you really mean "public int" ? Data annotation attributes are not implemented in beta 4, you need to use the Fluent modelBuilder API

**Comment by rowanmiller** [comment]
@jkyadav easiest way is just to set the data type you want to use http://ef.readthedocs.org/en/latest/modeling/configuring.html#relational-data-type.

Data Annotation support is tracked by https://github.com/aspnet/EntityFramework/issues/107

**Comment by jkyadav** [comment]
In my table there are 80 column, so I have to write 80 lines in the context file, I don't think provided solution will easy in this case, and also I have already defiled model property length.
