### ISSUE TITLE
Encapsulated collection unexpected behaviour when inserting and deleting childs with lazy loading enabled

### ISSUE THREAD

**Issue by salvobellino95** [dotnet/efcore#20945]
### Describe the bug 
I tipically like to encapsulate collections that represents one-to-many relationships exposing a IReadOnlyList\<T\>. When I remove and add some entities in these collections using the private List\<T\> backing field during the same unit of work, entities that were to be deleted are not deleted.

### To Reproduce
```cs
 public class Blog
    {
        public int Id { get; set; }

        private readonly List<Post> _posts = new List<Post>();
        public virtual IReadOnlyList<Post> Posts => _posts.ToList();

        public void SetPosts(List<Post> posts)
        {
            //some business logic
            _posts.Clear();
            _posts.AddRange(posts); 
            //here I see only the added posts, the previous ones have been removed as expected
        }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Content { get; set; }
    }

___

    static void Main()
    {
        using (var db = new BloggingContext())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            var blog = new Blog();
            blog.SetPosts(new List<Post>() { new Post() { Content = "post1" }, new Post() { Content = "post2" } });
            db.Blogs.Add(blog);
            db.SaveChanges();
        }

        using (var db = new BloggingContext())
        {
            var blog = db.Blogs.First();
            blog.SetPosts(new List<Post>() { new Post() { Content = "post3" }, new Post() { Content = "post4" } });
            db.SaveChanges();

            Debug.Assert(blog.Posts.Count == 2); //fails, it contains also the removed posts post1,post2
        }
    }
```

The relation is mapped as usual
```cs
            modelBuilder.Entity<Blog>().HasMany(b => b.Posts).WithOne()
                .Metadata.PrincipalToDependent.SetPropertyAccessMode(PropertyAccessMode.Field);
```
If the relation is configured using Owned Types, it works.
```cs
            modelBuilder.Entity<Blog>().OwnsMany(b => b.Posts).WithOwner(); //this works 
```

Here there is a runnable example:
https://github.com/salvobellino95/efcoreissue1

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.4
Target framework: NET Core 3.1
Operating system: Win10 Home 1806
IDE: VS Community 16.5.2

**Comment by ajcvickers** [comment]
@salvobellino95 In this code:

```C#
using (var db = new BloggingContext())
{
    var blog = db.Blogs.First();
    blog.SetPosts(new List<Post>() { new Post() { Content = "post3" }, new Post() { Content = "post4" } });
    db.SaveChanges();

    Debug.Assert(blog.Posts.Count == 2); //fails, it contains also the removed posts post1,post2
}
```
the existing posts are never loaded. This is because the code modifies the field directly, and so never calls the property that is overridden to do lazy loading.

**Comment by salvobellino95** [comment]
Thank you for your time. Now I understand. It makes sense. Maybe this is not the best pattern to do that. A simple workaround can be load the collection in the setter, for example:

`            var existingPosts= Posts.ToList();`

Maybe a good solution can be mapping directly to a protected virtual fields 

`            //builder.HasMany("_intervals").WithOne();
            //builder.Ignore(p => p.Intervals);
`
But now i have magic strings in my mapping code. There are other solutions?
Thank you

**Comment by ajcvickers** [comment]
@salvobellino95 Lazy-loading proxies require a property that can be overridden, and that EF access the the field directly to avoid issues with recursion.

**Comment by salvobellino95** [comment]
So what is in your opinion the best way to encapsulate a collection using lazy loading? I think that this is a geneal question and perhaps there are many developers that try to use this feature, maybe not in the best way

**Comment by ajcvickers** [comment]
@salvobellino95 Personally, I would use something like this:

```C#
public class Blog
{
    private readonly List<Post> _posts = new List<Post>();
    
    public virtual IReadOnlyList<Post> Posts => _posts;
}
```
But your way is fine too if you feel a defensive copy is needed.

If you want to trigger lazy-loading inside your code, then you'll need to use the navigation property to do that. I don't think there is a problem with this.
