### ISSUE TITLE
OS X: No data stores are configured

### ISSUE THREAD

**Issue by jbehrens94** [dotnet/efcore#2094]
When running `dnx . ef migration apply`, I receive this error

`Using context 'ApplicationDbContext'.
System.InvalidOperationException: No data stores are configured. Configure a data store by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services.`

When I open Visual Studio Code and add the mentioned `OnConfiguring` method in `IdentityModels.cs` I receive an error telling me `no suitable method found to override`.
Are there any known ways of setting up EF on OS X?

**Comment by luisrudge** [comment]
I'm having this too on Windows

**Comment by jbehrens94** [comment]
Is there a way to solve that?

**Comment by luisrudge** [comment]
I'm solving the same way the `file > new project` experience is solving: automatic migrations.

```csharp
public class MyAppDb : DbContext
{   
    private static bool _created;

    public MyAppDb()
    {
        if (!_created)
        {
            Database.AsRelational().ApplyMigrations();
            _created = true;
        }
    }
}
```

**Comment by jbehrens94** [comment]
I have that same code in `ApplicationDbContext`, but that doesn't work for me, resulting in the error described above.

**Comment by divega** [comment]
@bricelam will sure have better insights on this one, but I believe on an ASP.NET 5 app the migrations command will need access to the service wire up that happens in the `ConfigureServices()` method in Startup.cs. Alternatively EF can boostrap its own service container, but for that case you will need to override the OnConfiguring() method on the context. @jbehrens94 the error about no suitable method to override is not expected. The method [is defined in the DbContext as virtual](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/DbContext.cs#L260). Are you using the right signature?

**Comment by jbehrens94** [comment]
Ah, you are correct about the signature, @divega. What should I specify in `UseSqlServer()` on OS X?

**Comment by divega** [comment]
Unfortunately at this stage there aren't yet many good options available for developing on OS X. Some people, including @rowanmiller from out team have played with connecting with a SQL Server instance in a Windows box. For that, you just need to keep calling `UseSqlServer()`. This will leverage the implementation of SqlClient included in Mono, which has limitations (apparently it is mostly outdated) but will work for some scenarios. @roji and other folks are working on the [Postgresql provider for EF7](https://github.com/npgsql/npgsql/issues/249) but not sure how much of it currently works on Mono. We also have a [SQLite provider](https://github.com/aspnet/EntityFramework/tree/dev/src/EntityFramework.Sqlite) in the works. @bricelam can probably comment on how much of it works on Mono currently.

**Comment by luisrudge** [comment]
@divega I agree with you. Running the migration should have some kind of way to wire up services.

**Comment by roji** [comment]
@divega, the Npgsql EF7 provider does work on mono (although there are some build issues). @rowanmiller demoed it in //build running on OS X.

However, we don't currently have nugets (I intend to work on this very soon, will post back here). Also, the EF7 provider itself is still in early stages (more complicated operations don't work yet).

**Comment by jbehrens94** [comment]
Is there an estimate on when this functionality will be working 100%?
Also, is Azure possibly usable with EF on OS X? I received some SSL errors when trying to register?

    _____________________________

**Comment by roji** [comment]
@jbehrens94 not really... EF7 itself isn't out yet... All I can say is that it's really high-priority for us.

**Comment by divega** [comment]
That is one of the known limitations of the SqlClient implementation in Mono. It has never been updated to support the protocol extensions used in Azure SQL DB. See http://stackoverflow.com/questions/28016789/is-it-possible-to-connect-the-azure-sql-database-on-mono-project-consisting-of-c.
cc @rowanmiller in case he found a better workaround for that.

**Comment by divega** [comment]
> All I can say is that it's really high-priority for us.

Same here. Having a compelling story for Mac OSX and Linux development is a high priority for the teams involved at Microsoft.

**Comment by jbehrens94** [comment]
I'm really happy about the great work you're doing, guys!
Indeed, I am really looking forward to developing on OS X in C#. Do you also know if sometime we'll be able to develop native C#, instead of via Mono?

And to keep on-topic, I should use npgsql, is the conclusion?
How to set that up?

**Comment by ErikEJ** [comment]
@Roji Hi, where do you plan to host your alpha NuGet packages?

**Comment by roji** [comment]
@ErikEJ, I plan to start publishing continuous build nugets on myget.org in the coming days, am working on putting everything together at the moment...

**Comment by roji** [comment]
@jbehrens94 regarding EF7, then we're still far from ready for any sort of serious use. For now you can use Npgsql on mono (OS X or Linux) to access PostgreSQL, either with EF6 or without it (direct ADO.NET).

**Comment by luisrudge** [comment]
@davidfowl  is there a way to wire up services without running the app?

**Comment by divega** [comment]
@jbehrens94 I knew I had heard about a workaround to connect Mono's SqlClient to Azure SQL DB. It is mentioned in #2018, but it requires disabling connection encryption.

**Comment by rowanmiller** [comment]
**Triage** Seems like everything is resolved here, but feel free to reactivate if there are outstanding things we need to address.

**Comment by rowanmiller** [comment]
@luisrudge I don't think there is such a thing planned. The logic to configure services etc. is contained in Startup.cs so we run that code to configure your services. @bricelam may have other insights, but I don't see any way around needing to run your service setup code.

**Comment by luisrudge** [comment]
So how will we run migrations in a sane way?

**Comment by divega** [comment]
@luisrudge I am curious, what is exactly the part that bothers you about migrations setting up the services?

**Comment by luisrudge** [comment]
Having to setup connection strings in two places is what botters me

**Comment by divega** [comment]
Is it that `ConfigureServices()` isn't getting called automatically for you and migrations are broken like apparently is happening in issue #2213?

**Comment by divega** [comment]
> Having to setup connection strings in two places is what bothers me

I see, but after re-reading the whole thread I still don't understand why you have to put it in two places. It should be sufficient to have it in the `ConfigureServices()` method in Startup.cs.

**Comment by luisrudge** [comment]
@divega yes! that's the exact problem. ConfigureServices is not called for migrations.

**Comment by divega** [comment]
Got it. Then let's continue the discussion on #2213. 

cc @bricelam in case he wants your repro.

**Comment by atrauzzi** [comment]
Just a note before moving over to my ticket: I definitely think you shouldn't have to configure twice if that's the case.

**Comment by divega** [comment]
@atrauzzi We 100% agree you shouldn't need to configure it twice and it is designed to work without it, but there appears to be a bug.

**Comment by atrauzzi** [comment]
Sounds good, sorry - I wasn't clear on the conclusion here as the issue was closed by the time it was linked to mine :)

**Comment by luisrudge** [comment]
:+1: Thanks guys!

**Comment by rhires** [comment]
@jbehrens94 - hi...I see that you got far enough with getting EF installed that you can try to use it. I've looked around a bit but don't see anything resembling instructions on how to do what you did. In other words, how did you get EF even on your Mac to determine it wasn't completely workable? There are steps I'm missing but you've either found them or you figured it out...please help?

**Comment by rowanmiller** [comment]
@rhires EF7 is a NuGet package that you install, the exact instructions for installing a NuGet package will depend on the tooling you are using (Visual Studio Code, Mono Develop, etc.).
