### ISSUE TITLE
Microsoft.AspNet.Hosting.Abstractions was reverted back to Interfaces naming, EF build broken

### ISSUE THREAD

**Issue by swaggerloaf** [dotnet/efcore#2095]
Errors in c:\projects\2015\EntityFramework\src\EntityFramework.Commands\project.json
    Unable to locate Microsoft.AspNet.Hosting.Abstractions >= 1.0.0-*
Errors in c:\projects\2015\EntityFramework\test\EntityFramework.Commands.Tests\project.json
    Unable to locate Microsoft.AspNet.Hosting.Abstractions >= 1.0.0-*
Errors in c:\projects\2015\EntityFramework\test\EntityFramework.Commands.FunctionalTests\project.json
    Unable to locate Microsoft.AspNet.Hosting.Abstractions >= 1.0.0-*

**Comment by bricelam** [comment]
This should be fixed once things propagate through our CI and out to the MyGet feed.

**Comment by bricelam** [comment]
In the meantime, `git checkout 50def64` should make things build.

**Comment by swaggerloaf** [comment]
EF build no longer broken
The "Abstractions" packages are now in MyGet
