### ISSUE TITLE
Update database is not creating database

### ISSUE THREAD

**Issue by ilijevicdenis** [dotnet/efcore#20956]
Hi guys, 

I have created new class project which targets .NET Standard 2.1.  
Project contains Entity classes and entity configurations. I can add migrations but I can't figure out why update database command can't connect to my local Sql Server command. 

Project startup: .NET Core 3.1 Blazor
Sql server: Sql server 2019 express
Visual studio: Visual studio 2019 

Detailed informations and code examples are below: 

```
PM> dotnet ef migrations list --startup-project ./Backoffice
Build started...
Build succeeded.
20200513220704_Initial_delta_core
PM> 
```

Update database

```
PM> dotnet ef database update 20200513220704_Initial_delta_core --startup-project .\Backoffice --context Delta.Core.CoreContext -v
Using project '.\Backoffice\Backoffice.csproj'.
Using startup project '.\Backoffice\Backoffice.csproj'.
Writing '.\Backoffice\obj\Backoffice.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\ilije\AppData\Local\Temp\tmpC4B.tmp /verbosity:quiet /nologo .\Backoffice\Backoffice.csproj
Writing '.\Backoffice\obj\Backoffice.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\ilije\AppData\Local\Temp\tmpE60.tmp /verbosity:quiet /nologo .\Backoffice\Backoffice.csproj
Build started...
dotnet build .\Backoffice\Backoffice.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.81
Build succeeded.
dotnet exec --depsfile C:\repos\Delta\Backoffice\Backoffice\bin\Debug\netcoreapp3.1\Backoffice.deps.json --additionalprobingpath C:\Users\ilije\.nuget\packages --runtimeconfig C:\repos\Delta\Backoffice\Backoffice\bin\Debug\netcoreapp3.1\Backoffice.runtimeconfig.json C:\Users\ilije\.dotnet\tools\.store\dotnet-ef\3.1.4\dotnet-ef\3.1.4\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll database update 20200513220704_Initial_delta_core --context Delta.Core.CoreContext --assembly C:\repos\Delta\Backoffice\Backoffice\bin\Debug\netcoreapp3.1\Backoffice.dll --startup-assembly C:\repos\Delta\Backoffice\Backoffice\bin\Debug\netcoreapp3.1\Backoffice.dll --project-dir C:\repos\Delta\Backoffice\Backoffice\ --language C# --working-dir C:\repos\Delta\Backoffice --verbose --root-namespace Backoffice
Using assembly 'Backoffice'.
Using startup assembly 'Backoffice'.
Using application base 'C:\repos\Delta\Backoffice\Backoffice\bin\Debug\netcoreapp3.1'.
Using working directory 'C:\repos\Delta\Backoffice\Backoffice'.
Using root namespace 'Backoffice'.
Using project directory 'C:\repos\Delta\Backoffice\Backoffice\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'CoreContext'.
Finding DbContext classes in the project...
Using context 'CoreContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'Backoffice'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'Backoffice'...
No design-time services were found.
Done.
PM> 

```
For example class one entity is:

```
    public sealed class Company
    {
        public Guid CompanyId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public bool CooperationExpressed { get; set; }
        public string VatNumber { get; set; }
        public bool EuBased { get; set; }
        public bool IsClient { get; set; }
        public string WebSite { get; set; }
    }

```
Configuration for company table
```
    public sealed class CompanyTableConfiguration : IEntityTypeConfiguration<Company>
    {
        public void Configure(EntityTypeBuilder<Company> builder)
        {
            builder.ToTable("Company");
            builder.Property(c => c.Address).HasMaxLength(200);
            builder.Property(c => c.Name).HasMaxLength(200).IsRequired();
            builder.Property(c => c.VatNumber).HasMaxLength(30);
            builder.Property(c => c.WebSite).IsUnicode().HasMaxLength(150);
        }
    }

```
DbContext class

    public sealed class CoreContext : DbContext
    {
        public DbSet<Company> Companies { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        { 
            modelBuilder.HasDefaultSchema("DeltaCore");
            modelBuilder.ApplyConfiguration(new CompanyTableConfiguration());
        }

        public CoreContext(DbContextOptions<CoreContext> options) : base(options)
        {
        }
    }

DI registration

`            services.AddDbContextPool<CoreContext>(options => options.UseSqlServer(connectionString, o => o.MigrationsAssembly("Delta.Core")));`

And finally connection string

>   "ConnectionString": "Data Source=DESKTOP-LG0SJ8I\\SQLEXPRESS;Integrated Security=True;MultipleActiveResultSets=true"

Thanks for reading,
Denis

**Comment by ajcvickers** [comment]
@ilijevicdenis I don't see any errors in the output you posted. What specifically is not working?

**Comment by ilijevicdenis** [comment]
Database and tables are not created

**Comment by ajcvickers** [comment]
@ilijevicdenis Nothing looks obviously wrong here. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by xgrois** [comment]
I have a similar issue. For creating a new DB, (1) "add-migration InitialCreate" succeeded, (2) "update-database" succeeded. However, no DB has been created in SQL server. I am following a YouTube tutorial (https://www.youtube.com/watch?v=J7Ho7HS7i_Y&list=PL6n9fhu94yhVowClAs8-6nYnfsOTma14P&index=12).

I have done other simple projects with EF and this is the first time this weird thing happens.

**Comment by oddikaro** [comment]
I think the issue is the connection string. Check if you have the "...;**database=<name-you-want>**;..."

**Comment by XGillerX** [comment]
This seems old by i will post any way, i had a similar issue, and what i found is that the DB engine used was localDb, ehich you can view if you use (localdb)\MSSQLLocalDB as server name.

**Comment by lenuga** [comment]
change your Database. May be it is working

**Comment by fasteddys** [comment]
I have the same problem in EF 6.01

**Comment by munzzz5** [comment]
> 

did you find a solution to this have been at it for a few days, i dont understand whats wrong in my connection string 
connectionString=Server=localhost;Database=LESSONLEARNT;Trusted_Connection=True;MultipleActiveResultSets=true;User ID=SA;Password=password;

**Comment by itunuelijah** [comment]
I am having the same issue with connecting asp net core boilerplate template with  mysql . Please help

**Comment by itunuelijah** [comment]
My startup.
namespace Vale.fintech.Web.Startup
{
    public class Startup
    {
    
        private readonly IWebHostEnvironment _hostingEnvironment;

        public Startup(IWebHostEnvironment env)
        {
            _hostingEnvironment = env;
        }

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            //Configure DbContext
            services.AddAbpDbContext<FintechDbContext>(options =>
            {
                DbContextOptionsConfigurer.Configure(options.DbContextOptions, options.ConnectionString);
            });

            services.AddScoped<IAccountService, AccountService>();
            services.AddScoped<ICustomerService, CustomerService>();
            services.AddScoped<ITransactionService, TransactionService>();
            services.AddScoped<IAccountManager, AccountManager>();
            services.AddScoped<ICustomerManager, CustomerManager>();
            services.AddScoped<ITransactionManager, TransactionManager>();


            services.AddMvc();


            services.AddControllersWithViews(options =>
            {
                
            }).AddNewtonsoftJson();


            services.AddControllers();
            services.AddTransient<CustomersController>();
            services.AddTransient<AccountsController>();
            services.AddTransient<TransactionsController>();

            services.AddAutoMapper(typeof(Startup));

            MapperConfiguration config = new MapperConfiguration(configuration =>
            {
                configuration.CreateMap<Customer, CustomerDto>();
                configuration.CreateMap<CustomerDto, Customer>();
                configuration.CreateMap<Customer, CustomersDTO>();
                configuration.CreateMap<CustomersDTO, Customer>();
                configuration.CreateMap<Account, AccountDto>();
                configuration.CreateMap<AccountDto, Account>();
                configuration.CreateMap<Account, CreateAccountDTO>();
                configuration.CreateMap<CreateAccountDTO, Account>();
                configuration.CreateMap<Transaction, TransactionDTO>();
                configuration.CreateMap<TransactionDTO, Transaction>();
            });
            IMapper mapper = config.CreateMapper();
            services.AddSingleton(mapper);

            //Configure Abp and Dependency Injection
            return services.AddAbp<FintechWebModule>(options =>
            {
                //Configure Log4Net logging
                options.IocManager.IocContainer.AddFacility<LoggingFacility>(
                    f => f.UseAbpLog4Net().WithConfig(
                        _hostingEnvironment.IsDevelopment()
                            ? "log4net.config"
                            : "log4net.Production.config"
                        )
                );
            });
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseAbp(); //Initializes ABP framework.

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
Appsetting.json
{
  "ConnectionStrings": {
    "Default": "Server=127.0.0.1;Database=valefintechdb;Uid=root;Pwd=ipassword;"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
dbcontext
public class FintechDbContext : AbpDbContext <FintechDbContext>
    {
        //Add DbSet properties for your entities...
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public FintechDbContext(DbContextOptions<FintechDbContext> options) 
            : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            /* Configure the model here */
            modelBuilder.Entity<Customer>().ToTable("Customers");
            modelBuilder.Entity<Account>().ToTable("Accounts");
            modelBuilder.Entity<Transaction>().ToTable("Transactions");

        }
    }
} 
configurer
public static class DbContextOptionsConfigurer
    {
       

        public static void Configure(DbContextOptionsBuilder<FintechDbContext> builder, string connectionString)
        {
            var serverVersion = ServerVersion.AutoDetect(connectionString);
            builder.UseMySql(connectionString, serverVersion);
        }

        public static void Configure(DbContextOptionsBuilder<FintechDbContext> builder, DbConnection connection)
        {
            var serverVersion = ServerVersion.AutoDetect(connection.ConnectionString);
            builder.UseMySql(connection, serverVersion);
        }
    }
  public static class DbContextOptionsConfigurer
    {
       

        public static void Configure(DbContextOptionsBuilder<FintechDbContext> builder, string connectionString)
        {
            var serverVersion = ServerVersion.AutoDetect(connectionString);
            builder.UseMySql(connectionString, serverVersion);
        }

        public static void Configure(DbContextOptionsBuilder<FintechDbContext> builder, DbConnection connection)
        {
            var serverVersion = ServerVersion.AutoDetect(connection.ConnectionString);
            builder.UseMySql(connection, serverVersion);
        }
    }
