### ISSUE TITLE
change in usage of DbSet<xx>.Update()

### ISSUE THREAD

**Issue by pas059** [dotnet/efcore#20955]
Hi,

During the upgrade of my App from EFc226 to EFc313, i remarked a change in the usage of DbSet<>.Update().

For instance, the following code containing in an event handler

```C#
Test test = e.Test;
using ( DbContext dbContext = GetDbContext() )
{
	dbContext.Tests.Update( test );

	//  playing with test

	dbContext.SaveChanges();
}
```

works with EFc226, but gives the exception with EFc3.1.3

> Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded.

when calling 'dbContext.SaveChanges()'. But the following code 

```C#
Test test = e.Test;
using ( DbContext dbContext = GetDbContext() )
{
	//  playing with test
		
	dbContext.Tests.Update( test );

	dbContext.SaveChanges();
}
```

works with EFc3.1.3.

Someone can confirm or explain?

Regards
Pascal

### Further technical details

EF Core version:3.1.3
Database provider: SQLite
Target framework: (e.g. .NET 4.7.2)
Operating system:W10pro
IDE: (e.g. Visual Studio 2019 16.5.4)

**Comment by ajcvickers** [comment]
@pas059 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by pas059** [comment]
Hi Arthur,

this will be difficult to attach a small runable code as the code shown above is extracted from a large project, and this is not really an issue (as i have a solution). But i wonder what is the normal way, the 1st or the Scnd solution.
Nevertheless, at the end of my "playing" of the "test', i use this
`Entry( patient ).State = EntityState.Unchanged;`

where 'patient' is an instance of entity that has the navigation property:
`      public virtual ICollection<Test> Tests { get; protected set; }
`
and the entity 'Test' has the navigation property
`      public virtual Patient Patient { get; set; }
`
all the rest of playing is just data manipulation. I hope this helps you

regards
Pascal

**Comment by ajcvickers** [comment]
@pas059 I can make the code you posted exhibit both behaviors quite easily. Without knowing what is specifically happening in your case it's impossible to further debug. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by pas059** [comment]
Hi Arthur,
As explained above, this will be difficult to attach a small runable code, but i confirm what's described above.
I don't say that this is a bug, probably that i badly interpret the role of the Update() method.
I thought that Update() has to be used before modifying the entity as the doc says that Update "begins tracking..." (and i used it in this way with EFc226), but, finally, the behavior with EFc313 seems more logic to me; as i understand, now, Update() méthod marks an entity as Modified, and so the call to 'dbContext.SaveChanges()' do the update, as expected.
I'm right?

best regards

**Comment by ajcvickers** [comment]
These blog posts describe how Update should and should not be used:
https://blog.oneunicorn.com/2020/01/17/dontcallupdate/
https://blog.oneunicorn.com/2020/01/18/docallupdate/
