### ISSUE TITLE
Issue Installing Or Upgrading EF Core Tools

### ISSUE THREAD

**Issue by BroMarduk** [dotnet/efcore#20954]
When I or anyone in my organization try and update or install EF Core Tools the following error occurs:

PM> dotnet tool update --global dotnet-ef
C:\Program Files\dotnet\sdk\3.1.202\NuGet.targets(124,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/xxxxxxxxxxxx/xxxxxxxxxxx/xxxxxxxxxx/nuget/v3/index.json. [C:\Users\DanBegallie\AppData\Local\Temp\ppzsvdmr.ebq\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.202\NuGet.targets(124,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\DanBegallie\AppData\Local\Temp\ppzsvdmr.ebq\restore.csproj]
dotnet : Tool 'dotnet-ef' failed to update due to the following:
At line:1 char:1
 dotnet tool update --global dotnet-ef

CategoryInfo          : NotSpecified: (Tool 'dotnet-ef... the following::String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError
 
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

 You are attempting to install a preview release and did not use the --version option to specify the version.
 A package by this name was found, but it was not a .NET Core tool.
 The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
 You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

The only way to fix the issue is to remove our Azure DevOps NuGet Package source (password protected) and run the install or upgrade again.   I've tried moving the order of the NuGet package sources - putting the password protected source at the top, bottom, middle but location does not seems to matter, as long as it's in the list the error occurs.

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:  Windows 10
IDE: (e.g. Visual Studio 2019 16.5.5)

**Comment by smitpatel** [comment]
> error : Response status code does not indicate success: 401 (Unauthorized).

If you want to have own package source in the list then you also need to provide authorization. I think this error would happen with any package restore when you don't authorize.

**Comment by BroMarduk** [comment]
It just seems that if it could be downloaded from a public repository higher in the priority list of NuGet sources that it would do so without even trying to access the private repository.
