### ISSUE TITLE
Provide built-in support for a token provider in Cosmos DB

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/efcore#20969]
The Cosmos DB provider can use resource tokens for access. In some environments this must be asynchronously fetched after service initialization. Tokens also expire. Right now all token management must be done external to the provider.

Provide a configuration option for an asynchronous delegate that returns an endpoint and key. This would be fetched on creating the client the first time. Allow configuration that if there is an authorization issue, the delegate is called again in case the issue is the token expiration. 

For server side solutions the delegate can be implemented to fetch the resource token from Cosmos directly. For client solutions it can be configured to make an API call to fetch the token.

For example:

```csharp
ICosmosResourceAccess 
{
     string Endpoint;
     string Key;
}

Func<Task<ICosmosResourceAccess>> fetchToken;

UseCosmos(null, null, opt => opt.UseTokenProvider(
   async ()=> await MyProvider.FetchTokenAsync());
```

**Comment by AndriySvyryd** [comment]
Related to https://github.com/dotnet/efcore/issues/20221

**Comment by JeremyLikness** [comment]
Closing via #26491
