### ISSUE TITLE
stringlength does not have effect on DB 

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/efcore#20974]
im having a sql db in azure. i have a string column where the string length displays "max", but in the code i have set the string length to 5000.please help. im using code first migration.

![image](https://user-images.githubusercontent.com/18216790/82140895-c305d880-984f-11ea-96d5-fe6170010dc6.png)

![image](https://user-images.githubusercontent.com/18216790/82140922-edf02c80-984f-11ea-899b-f8f229a2990b.png)

context model snapshot

![image](https://user-images.githubusercontent.com/18216790/82140938-10824580-9850-11ea-8c00-c888f63bdcb1.png)

**Comment by lajones** [comment]
The maximum number of byte-pairs for an `nvarchar` column is 4000. See [these docs](https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver15).  Anything above that is treated as `max`.

**Comment by ErikEJ** [comment]
If you make your column non-unicode, the max size is 8000.
