### ISSUE TITLE
Support for multiple enums (flags) in EnumToStringConverter

### ISSUE THREAD

**Issue by risogolo** [dotnet/efcore#20994]
Seems like EnumToStringConverter / StringEnumConverter does not support enums with multiple combined options
InProgress = 1,
NotCancelled = 7,
**State = InProgress | NotCancelled**

any plans to support that?

**Comment by roji** [comment]
@risogolo this would require something like concatenating the different values in a comma-separated string, after discovering which exact values are set, which isn't trivial to do. I'm not sure it's a good idea for EF Core to do this out of the box.

@ajcvickers we may want to detect [Flags] enums and emit an informative error, at least unless we decide to properly handle them.

**Comment by ajcvickers** [comment]
@roji Duplicate of #20094. My understanding is that the string will be a numeric value if it represents multiple states, but will still round-trip correctly.

**Comment by roji** [comment]
Duplicate of #20094

**Comment by roji** [comment]
Thanks...

> My understanding is that the string will be a numeric value if it represents multiple states, but will still round-trip correctly.

I'm not sure what value there is in storing a number in a string column (why not just store it in an int column), but yeah, it would work.

**Comment by risogolo** [comment]
Guys we are talking about EnumToStringConverter, I need to see string representation of enum in DB, so I guess numeric value does not make sence.

**Comment by roji** [comment]
@risogolo so what exact string representation are you looking for for `InProgress | NotCancelled`?

**Comment by risogolo** [comment]
something visible, for example "InProgress; NotCancelled"
