### ISSUE TITLE
Migration commands sending data inline instead of using parameters.

### ISSUE THREAD

**Issue by rkaushik15** [dotnet/efcore#20996]
I am working on an EFCORE provider and I notice the following behavior:

When seeding some data in the DB using Migration commands from Package Manager Console, the SQL queries created are having the data INLINE, and not using any bind parameters.

Not using bind parameters can cause the following issues:

1. We cannot control the bind type, if required.
2. SQL Injection Issues.
3. If the string contains sensitive information, then tracing out the SQL will also end up tracing out the string containing sensitive information.

I request you to change this behavior so bind parameters are used instead of data being sent inline.
### Steps to reproduce

An overview of the general steps followed to reproduce this:

1. Create a new project and add the necessary references and NuGet packages including Microsoft.EntityFrameworkCore. 

2. Create the class corresponding to the table we wish to create in the DB.

3. Seed the data for entity during model creation. I used the following code:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

      modelBuilder.Entity<TAB2>(eb =>
      {
            eb.Property(b => b.id);
            eb.Property(b => b.COL2).HasMaxLength(250).IsUnicode().HasColumnType("NVARCHAR2(60)");
      });

      modelBuilder.Entity<TAB2>().HasData(
          new TAB2
          {
            id = 1,
            COL2 = "dummy_string"
          }
          );
    }
```

4. run `add-migration <name>` from PMC
5. run `update-database` from PMC

The following SQLs are generated:

```
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"TAB2" (
    "id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "COL2" NVARCHAR2(60),
    CONSTRAINT "PK_TAB2" PRIMARY KEY ("id")
)';
END;


BEGIN
INSERT INTO "TAB2" ("id", "COL2")
VALUES (1, N'dummy_string');
END;
```

As we can see the data values are present inline in the SQL query. 

### Further technical details

EF Core version: 3.1
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.4

**Comment by roji** [comment]
@rkaushik15 thanks for filing this (@bricelam @AndriySvyryd if you have any recollection on why it was done this way...).

> We cannot control the bind type, if required.

How do you mean? EF Core is aware of the type of the column, and formats the literal value based on that. Do you have a concrete case in mind?

> SQL Injection Issues.

This isn't susceptible to SQL injection issues, as EF Core properly escapes all values - just like it does with literal values in queries. Try defining seed data with apostrophes, and you should see them escaped.

> If the string contains sensitive information, then tracing out the SQL will also end up tracing out the string containing sensitive information.

That is a valid concern, although data that you put inside your context definition (in source code) shouldn't be considered secret/sensitive as a general rule.

**Comment by bricelam** [comment]
@rkaushik15 Keeping in mind that most Migrations workflows involve generating a self-contained SQL script to use during deployment, what SQL would you like to see generated? In other words, how would you expect the parameter values to be specified in the script?

**Comment by rkaushik15** [comment]
Hi @roji and @bricelam, thanks for your prompt response

@roji 

>How do you mean? EF Core is aware of the type of the column and formats the literal value based on that. Do you have a concrete case in mind?

I've come across issues in the way DB_CHARSET and NLS_CHARACTERSET are handled. With inline data, the conversion is sometimes improper causing the data to not be inserted properly and garbage values being inserted in the DB. Specifically when encoding of the data to be entered is different than the DB_CHARSET. 
The issue is mitigated when we enter the data using parameters where we can explicitly handle the BIND type and change it to NVARCHAR2.

>This isn't susceptible to SQL injection issues, as EF Core properly escapes all values - just like it does with literal values in queries. Try defining seed data with apostrophes, and you should see them escaped.

I tried this out and it works as you've mentioned. Thanks for letting me know. You are right, SQL Injection would not be an issue.

@bricelam 

>Keeping in mind that most Migrations workflows involve generating a self-contained SQL script to use during deployment, what SQL would you like to see generated? In other words, how would you expect the parameter values to be specified in the script? And would doing it that way actually address your concerns?

This is absolutely correct in case the user wants to generate a migration script. In that case using a parameter would not be possible. However, that is not my use case. I am simply using 'update-database', which generates a Relational Command which is executed to apply the changes to the DB. 
What I would expect would simply be a command object with the CommandText:

`
BEGIN
INSERT INTO "TAB2" ("id", "COL2")
VALUES (:1, :2);
END;
`

The Command object would have a list of DbParameters which would have the corresponding values. 

We can then handle the parameters and make any changes necessary and that should address my concerns.

**Comment by ajcvickers** [comment]
@rkaushik15 We discussed this and decided that we're not going to implement a different pattern when the migrations are run from code as opposed to when they are run from a generated script. This is because we want both type of executions to be as close as they can be in functionality so that they can be easily used interchangeably. Also, even if there is a small advantage of using parameters here, the cost of implementation and the increase in code complexity doesn't seem worth the value delivered.

> I've come across issues in the way DB_CHARSET and NLS_CHARACTERSET are handled. With inline data, the conversion is sometimes improper causing the data to not be inserted properly and garbage values being inserted in the DB. Specifically when encoding of the data to be entered is different than the DB_CHARSET.

This sounds like an issue with the Oracle provider and should be reported to them as a bug.
