### ISSUE TITLE
Add-Migration InitialCreate

### ISSUE THREAD

**Issue by Raviniki** [dotnet/efcore#21000]
Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Add-Migration InitialCreate
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Environment
---------------------
 <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\jquery\**" />
    <Content Remove="wwwroot\lib\jquery\**" />
    <EmbeddedResource Remove="wwwroot\lib\jquery\**" />
    <None Remove="wwwroot\lib\jquery\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.4.20220.10" />
  </ItemGroup>

**Comment by ajcvickers** [comment]
@Raviniki Please post your csproj file.

**Comment by Raviniki** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\jquery\**" />
    <Content Remove="wwwroot\lib\jquery\**" />
    <EmbeddedResource Remove="wwwroot\lib\jquery\**" />
    <None Remove="wwwroot\lib\jquery\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.4.20220.10" />
  </ItemGroup>

</Project>

**Comment by Raviniki** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\jquery\**" />
    <Content Remove="wwwroot\lib\jquery\**" />
    <EmbeddedResource Remove="wwwroot\lib\jquery\**" />
    <None Remove="wwwroot\lib\jquery\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"
Version="5.0.0-preview.4.20220.10" />
  </ItemGroup>

</Project>

**Comment by ajcvickers** [comment]
@Raviniki You'll need to install the required NuGet packages. See the documentation here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell

**Comment by Raviniki** [comment]
i see i have different version for tool and different version for
sqlserver  thanks man

**Comment by Raviniki** [comment]
solved
