### ISSUE TITLE
cannot use EntityFramework.InMemoryStore

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#2101]
![error](https://cloud.githubusercontent.com/assets/127777/7429043/e61f3922-effa-11e4-93c8-d6674cbfc694.png)

I just created a new asp.net 5 app using 2015 rc, and I would like sql server store to in memory, but If I add the InMemory package to the project,json the restore fails.

Am I missing something?

**Comment by sayedihashimi** [comment]
@lucamorelli I just added ```"EntityFramework.InMemory": "7.0.0-beta4"``` to my project.json and everything restored file. What are you seeing? Is your nuget feed pointing to nuget.org or something else?

**Comment by lucamorelli** [comment]
I'm using the main feed the version of dnx is 1.0.0-beta4-11566. Inside visual studio I tried to configuring bot v2 and v3 feed. I also tried from command line from the same result. the strange thing is that this morning I tried to install it in vpn application, using nuget 2.8.* and it worked.

**Comment by rowanmiller** [comment]
Any error details from the restore output?

**Comment by rowanmiller** [comment]
Closing as we have not been able to reproduce this issue. Feel free to reactivate if you can provide error details etc.
