### ISSUE TITLE
EF core and .NET Standard 2. issue on Update-Database command 

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#21030]
**Environment**: `EF Core`, `.NET Standard 2.0`, `VS2019 ver. 16.5.5`, `Windows 10 Pro 1903`.

**Issue**: My `VS2019` project solution has a startup project, say, `MyStartupProj` and a .NET Standard 2.0 project, say, `MyDotStandardProj` that is referenced by startup project. Using EF Core on `MyDotStandardProj` , I've been able to do all scaffolding (model classes, MyDbContext class, running Add-Migration etc.). But when I run the `PM> Update-Database -Project MyDotStandardProj ` command in `VS2019`, the following `MyDbContext.cs` file in .NET Standard project creates the database inside my user directory `C:\Users\MyIUserName\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\3.1.4\tools\net461\any\MySQLite.db`. And when I run the LINQ queries (such as the [following](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli#create-read-update--delete), I get the error `no such table exists` etc. Obviously the error is because of compiler not being able to find the `MySQLite.db` file in `bin\Debub` subfolder.

**Question**: Why the following code is creating the `MySQLite.db` db in my user directory instead of Standard Library project's directory (i.e., `bin\Debub` subfolder). And how can I resolve the issue?

**Remark**: I think what's happening is that the line `AppDomain.CurrentDomain.BaseDirectory…….` of the following code is looking for `bin\Debub` subfolder in startup project but since the scaffolding is all done in .NET Standard project, the compiler is not finding `MyDbContext.cs` file in startup project and hence the `PM> Update-Database -Project MyDotStandardProj` is creating the `MySQLite.db` in the user subfolder shown above. So, how can we resolve this issue?

**MyDbContext.cs file inside `MyDotStandardProj`**:
```
…......…………...
using Microsoft.EntityFrameworkCore; //added from here
……….
namespace MyDotStandardProj{
    public class MyDbContext: DbContext
    {
        string sSQLiteDbPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory + "MySQLite.db");
        public DbSet<MyObject> MyObjects { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseSqlite($"Data Source = {sSQLiteDbPath}");
    }
}
```

**Comment by bricelam** [comment]
Don't use `AppDomain.CurrentDomain.BaseDirectory`. At design time, that will be the location of the tool executing your code (e.g. `C:\Users\MyIUserName\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\3.1.4\tools\net461\any\`) which is not what you want.

Can you just use a relative path?

```cs
options.UseSqlite("Data Source = MySQLite.db")
```

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
