### ISSUE TITLE
Migration creates constraint before altering table. 5.0.0-preview.4.20220.10

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#21037]
The constraint is added before the column is added in the migration..

    public partial class AlterTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateCheckConstraint(
                name: "Check",
                table: "People",
                sql: "LEN(TRIM([Name])) > 0");

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "People",
                type: "nvarchar(max)",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "Check",
                table: "People");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "People");
        }
    }

### Steps to reproduce

Alter the a table by adding a property in this case Name and add a constraint on the configuration.

5.0.0-preview.4.20220.10

[PreviewEFIssues.zip](https://github.com/dotnet/efcore/files/4677201/PreviewEFIssues.zip)

### Further technical details

EF Core version: 5.0.0-preview.4.20220.10
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)

**Comment by roji** [comment]
Thanks for reporting this and for using the previews! I've submitted a fix (which should appear in preview6). In the meantime, as a workaround simply create the column and add the check constraint in two different migrations.
