### ISSUE TITLE
How can I set Auto update migration after each model class change?

### ISSUE THREAD

**Issue by masoodafar-web** [dotnet/efcore#21034]
hi, i want do not **Add-migration** after each change in **model class** entities and add to migration automatically ,What should I do?
in **entityFramwork 6** It was done by `automaticmigrationsenabled=true`.of course, if I understood correctly :-))
please guide me

**Comment by ajcvickers** [comment]
@masoodafar-web Automatic migrations are not supported in EF Core. See #6214.
