### ISSUE TITLE
when remove migration, do not add ItemGroup

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#21047]
### 2.*.csproj auto add ItemGroup
```
  <ItemGroup>
    <Compile Remove="Migrations\20200526055139_InitCreate.cs" />
    <Compile Remove="Migrations\20200526055139_InitCreate.Designer.cs" />
  </ItemGroup>
```

### Further technical details

EF Core version:3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system:Win10
IDE: Visual Studio 2019 16.6

**Comment by ajcvickers** [comment]
Duplicate of #18381
