### ISSUE TITLE
System.Data.SqlServerCe library reference not found

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21050]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1025925/systemdatasqlserverce-library-reference-not-found.html)._

---
I've installed the following NuGet libraries in a Core 3.1 project and when I try to use the "Add SQL CE 4.0 Connection", the systems responds with a dialog box that indicates I need to load the "SQL Server Compact 4.0 runtime."

<PackageReference Include="EntityFramework.SqlServerCompact" Version="6.4.0" />
    <PackageReference Include="EntityFrameworkCore.SqlServerCompact40.Core" Version="2.2.0.7" />
    <PackageReference Include="EntityFrameworkCore.SqlServerCompact40.Design" Version="1.1.0.1" />
    <PackageReference Include="EntityFrameworkCore.SqlServerCompact40" Version="2.2.0.7" />
    <PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="3.1.0" />
    <PackageReference Include="ErikEJ.EntityFrameworkCore.SqlServer.Dacpac" Version="3.1.2" />
    <PackageReference Include="ErikEJ.SqlCeBulkCopy" Version="2.1.6.15" />
    <PackageReference Include="ErikEJ.SqlCeMembership" Version="2.1.0.2" />
    <PackageReference Include="ErikEJ.SqlCeScripting" Version="3.5.2.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.3">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.3">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.SqlServer.Compact" Version="4.0.8876.1" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="14.0.1016.290" />
    <PackageReference Include="runtime.native.System.Data.SqlClient.sni" Version="4.7.0" />
    <PackageReference Include="runtime.win7-x64.runtime.native.System.Data.SqlClient.sni" Version="4.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.1" />
    <PackageReference Include="System.Data.SqlServerCe_unofficial" Version="4.0.8482.1" />

I've searched for, but have not found, a Sql Server Compact 4.0 runtime nor an official System.Data.SqlServerCe reference file that I could load to satisfy the system and, therefore, I am unable to use the SQL CE database op;tion.

What is the reference library called that will allow me to use this feature?

---
#### Visual Studio Feedback System on 5/11/2020, 08:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ErikEJ** [comment]
1: You cannot use the SQL Server Compact EF Core provider with EF Core 3. It only works with EF Core 2.2.

2: Download locations for the SQL CE runtime is available here: https://github.com/erikEJ/sqlcetoolbox/wiki
