### ISSUE TITLE
Entity Framework Core and .NET Standard 2.0 - an inconsistent behavior

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#21054]
**Environment**: `VS2019 - ver16.6`, `Windows 10 pro 1903`

I followed [this][1] link from Microsoft team to create a `VS2019` solution with `.NET Standard 2.0` library project and a dummy `.NET Core Console` app as a startup project. In that solution, I also followed this [EF Core official tutorial][2] to create a `SQLite` db (called `MySQLiteDb.db`) that gets created in the root directory of dummy `.NET Core Console`.

Afterwards, I referenced that `.NET Standard` library in one of my `WPF Full Framework` project to perform some db operations. For that I copied `MySQLiteDb.db` from the above project into this `WPF` project and set its `Copy to output directory` action to `Copy if newer` with `Build Action` as `None`. Now, this `WPF Full Framework` app works fine and performs multiple db operation on `MySQLiteDb.db`.

But when I do the same as above on a [Microsoft VSTO Add-in][3] project by referencing the same `.NET Standard` library, I get an inconsistent behavior: For example, half of the time the app successfully  performs a data insert but about half of the time the app throws the following error on the data insert. And there is no data validation because this test db has three simple text columns with no unique keys/index etc. Question: Why this inconsistent behavior on `VSTO` project but not on `WPF` project while both are `.NET 4.8` projects. And how can the issue be resolved?

**Error**:
>Inner Exception 1: SqliteException: SQLite Error 1: 'no such table: MyDocs'.

  [1]: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#other-target-frameworks
  [2]: https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=visual-studio
  [3]: https://docs.microsoft.com/en-us/visualstudio/vsto/create-vsto-add-ins-for-office-by-using-visual-studio?view=vs-2019

**Comment by ajcvickers** [comment]
\cc @bricelam

**Comment by bricelam** [comment]
What is the value of `dbContext.Database.GetDbConnection().DataSource` when it succeeds and when it fails? Make sure the connection is open when reading the property value.

**Comment by saf-itpro** [comment]
@bricelam How do I find out the value of `dbContext.Database.GetDbConnection().DataSource` at the time of success and failure. Just a click on a VSTO Ribbon button inserts the data using following code. A button click would insert data one or two times but not the third time (or vice versa).

I'm not sure why data connection would be an issue, but would like to find out the value of `dbContext.Database.GetDbConnection().DataSource`  at the time of insertion. Please tell me how to check that. Same code inserts the data in `WPF` app always successfully with every button click. 
Button click is inserting the data as follows:

```
using (MathDocsContext db = new MathDocsContext())
{
    MyDoc rec = db.MyDocs.Where(t => t.Author == author && t.Title == title).FirstOrDefault();

    db.Add(new MyDoc { DateModified = DateTime.Today.ToString("MM-dd-yyyy"), Author = author, Title = title, DocContent = sDocContent });
    await db.SaveChangesAsync();
}
```

**Comment by ajcvickers** [comment]
See also https://github.com/dotnet/efcore/issues/21118, which is another case where VSTO is not working.

**Comment by ajcvickers** [comment]
@saf-itpro For VSTO issues please use the Help->Send Feedback menu in Visual Studio. This will direct the issue to the VSTO team.
