### ISSUE TITLE
Unable to translate string.Compare after Upgrade from 2.2.6 to 3.1.4

### ISSUE THREAD

**Issue by ssteiner** [dotnet/efcore#21060]
In my DBContext, I have a property 

```csharp
internal AspNetUser MyUser
        {
            get
            {
                string realUserId = "hello";
                return AspNetUsers.Include(x => x.AspNetRoles).FirstOrDefault(x => string.Compare(x.UserName, realUserId, true) == 0);
            }
        }
```

When I access this property in a DbContext using EFCore 2.2.6, no problems, everthing works as expected. with EFCore 3.1.4, accessing MyUser throws this

> The LINQ expression 'DbSet<AspNetUser>
    .Where(a => string.Compare(
        strA: a.UserName, 
        strB: __realUserId_0, 
        ignoreCase: True) == 0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
 at    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )

Is this supposed to happen? I have quite a few case insensitive string comparisons in my code..

### Steps to reproduce

As you may have guessed from the naming, this is based on a standard ASP.NET Core web application with Individual User Accounts (storing user accounts in-app). That gets you the database schema. Then just add that property to to ApplicationDBContext.cs, and try accessing it.

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.4
Operating system: Windows 10 1909
IDE:  Visual Studio 2019 16.6

**Comment by ajcvickers** [comment]
@ssteiner In 2.2, EF was pulling all the data back from the database and doing the string comparison in memory. If you want to get back that behavior, then change your query to this:

```C#
AspNetUsers.Include(x => x.AspNetRoles)
    .AsEnumerable()
    .FirstOrDefault(x => string.Compare(x.UserName, realUserId, true) == 0);
```

For more information on translating string comparisons to SQL, see the discussion on #1222.  In this case, since SQL Server is case insensitive by default, you can probably just do this:

```C#
AspNetUsers.Include(x => x.AspNetRoles)
    .FirstOrDefault(x => x.UserName == realUserId));
```
