### ISSUE TITLE
camelCase property names for CosmosDB

### ISSUE THREAD

**Issue by Marusyk** [dotnet/efcore#21073]
Is there any way to serialize property names in camelCase using CosmosDB provider instead of

```
builder.Property(o => o.Id).ToJsonProperty("id")
```
to avoid this

![image](https://user-images.githubusercontent.com/9221694/83199276-8ee0c080-a149-11ea-8bb3-0e6d1b475490.png)

**Comment by ajcvickers** [comment]
Duplicate of #20588. However, see the external package https://github.com/efcore/EFCore.NamingConventions which does something similar for relational names. It should be possible to either update or fork this package to do the same for Cosmos.
/cc @roji

**Comment by mtnvencenzo** [comment]
See here > https://github.com/dotnet/efcore/issues/28270#issuecomment-2764309401
