### ISSUE TITLE
Rename GetName(table, schema) to GetDatabaseName(table, schema) for Indexes

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#21072]
See [this comment in PR 21012](https://github.com/dotnet/efcore/pull/21012#discussion_r431991512).

**Comment by lajones** [comment]
@AndriySvyryd Do you also want to change the extension methods `GetDefaultName` to be `GetDefaultDatabaseName`? And obsolete the `GetDefaultName` that existed before your TPT PR?

**Comment by AndriySvyryd** [comment]
@lajones Yes
