### ISSUE TITLE
Option to not create references for classes generated to the project when using Scaffold-DbContext

### ISSUE THREAD

**Issue by birtej** [dotnet/efcore#21080]
The way we are using the scaffolding, we have a helper project that updates the DataContext and entities in two separate projects.  Due to version conflicts and the work required to update to ef core 3.x we cannot put the scaffolding within the projects for the foreseeable future.

Currently, we have to delete references that have been added to the helper project.

We would like the option to not execute _dteProject.ProjectItems.AddFromFile_ when scaffolding the dbcontext in the PMC

**Comment by ajcvickers** [comment]
@birtej This isn't something we are likely to change, but using the [dotnet ef tool](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet) instead of the PMC command should work for you, since it has no integration with Visual Studio and so doesn't call AddFromFile.
