### ISSUE TITLE
Entity Framework Core Table Name not Pluralized

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21083]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1050926/entity-framework-core-table-name-not-pluralized.html)._

---
My model includes the following table definition.

```C#
public class RailInterchangeLocation
    {
        public int RailInterchangeId { get; set; }
        public RailInterchange RailInterchange { get; set; }

public int LocationId { get; set; }
        public Location Location { get; set; }
    }
```
And here is a snippet I put in `OnModelCreating()`.

```C#
builder. Entity<RailInterchangeLocation>()
        . HasKey(ri => new { ri. RailInterchangeId, ri. LocationId });
```

Seems to work okay except that the generated table name is not pluralized. All my other tables are.

```C#
CREATE TABLE [dbo]. [RailInterchangeLocation] (
        [RailInterchangeId] INT NOT NULL,
        [LocationId]        INT NOT NULL,
        CONSTRAINT [PK_RailInterchangeLocation] PRIMARY KEY CLUSTERED ([RailInterchangeId] ASC, [LocationId] ASC),
        CONSTRAINT [FK_RailInterchangeLocation_Locations_LocationId] FOREIGN KEY ([LocationId]) REFERENCES [dbo]. [Locations] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_RailInterchangeLocation_RailInterchanges_RailInterchangeId] FOREIGN KEY ([RailInterchangeId]) REFERENCES [dbo]. [RailInterchanges] ([Id]) ON DELETE CASCADE
    );
    GO

CREATE NONCLUSTERED INDEX [IX_RailInterchangeLocation_LocationId]
        ON [dbo]. [RailInterchangeLocation] ([LocationId] ASC);
```
---
#### Visual Studio Feedback System on 5/27/2020, 00:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
EF Core does not pluralize entity type names when generating table names. However, it will use the DbSet property name if there is one, or the table name can be specified explicitly in the model configuration.

**Comment by EngNunoFigueira** [comment]
I speficif on C# Model/DbContext  :
public DbSet<Municipio> Municipios { get; set; }
But on SQL Server Database the Tables is created as Municipio ! Is it correct ?
