### ISSUE TITLE
Build2015 - Beta 5 with support for Universal apps

### ISSUE THREAD

**Issue by igrali** [dotnet/efcore#2110]
Hi EF team

I'm not sure where to ask this so I'm opening as an "issue".
I'd like to know when is the planned release of Beta 5? It was used for the demos in Universal app during Build 2015 session by @rowanmiller.

Thanks!

-Igor

**Comment by ErikEJ** [comment]
You can get if from the  myget daily builds nuget feed

**Comment by rowanmiller** [comment]
What's in the nightly builds won't quite work out of the box with UAP. I'm going to post up some instructions next week to work around the current issues and we will get them resolved soon.

**Comment by igrali** [comment]
Great, thanks Rowan!

**Comment by Nebelkraehe** [comment]
I´m having the same issue that I can´t use EF7 (particularly ```EntityFramework.SqLite```) in Univeral Apps / PCL projects.
A work around instruction would be great. Thanks.

**Comment by jureg85** [comment]
Hi,

Any update on this? 
I'm waiting to start using EF7 (SqlLite) on my Win 10 UAP.

Many thanks for all efforts.

Jure

**Comment by bricelam** [comment]
I've created a starter app in [bricelam/EF7OnUWP](https://github.com/bricelam/EF7OnUWP). Look at the commit history for the steps involved to work around the issues.

**Comment by jureg85** [comment]
Any rough dates when major issues with  Win UAP 10 (EF7) will be fixed and officall ready?

Many Thanks,

**Comment by rowanmiller** [comment]
Not at this stage. We're working to have the ironed out for our next preview (Beta 5), but there are changes needed outside of just EF, so it depends on when things fall into place for all the involved teams.

**Comment by jureg85** [comment]
Rowan,

I'm developing the app that should be released very close to Windows 10 release. I really want to use Entity Framework (SqLite) and avoid to use other alternatives

I will stay tuned. Thank you for information and keep the good work.

Cheers

**Comment by natemcmaster** [comment]
Since #2322 , have we made any progress towards UAP support?

**Comment by bricelam** [comment]
@natemcmaster It resolved #2183 and some issues with the System.Data.Common package. We're now waiting for the Tools for Windows 10 catch up so we can continue testing.

**Comment by rowanmiller** [comment]
Just a quick update, EF7 Beta 6 works with the initial RTM release of UWP.
EF7 Beta 7 will work, but it needs an updated version of NuGet which is not yet publically available - https://github.com/aspnet/EntityFramework/issues/3019
