### ISSUE TITLE
Switch to returning ValueTask in loggers and interceptors

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21109]
Many of our loggers currently return generic Tasks in order to support interception, incurring lots of needless heap allocations. For example, [RelationalCommand.ExecuteReaderAsync](https://github.com/dotnet/efcore/blob/a1931d9e0f7f327a0431b494b1af29f8299a1dfe/src/EFCore.Relational/Storage/RelationalCommand.cs#L469) calls [CommandReaderExecutingAsync](https://github.com/dotnet/efcore/blob/016256850c227897b2c2b4a3125210483d0318f8/src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs#L410) and [CommandReaderExecutedAsync](https://github.com/dotnet/efcore/blob/016256850c227897b2c2b4a3125210483d0318f8/src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs#L803), both of which actually return synchronously in almost all cases but allocate Task instances.

In addition, our interceptor API surface also returns generic Tasks from all methods. This means that the moment an interceptor is set up, the user starts paying additional allocations for all of its methods, regardless of whether those are intercepted or if they complete synchronously.

As this is a (minor) breaking change in a relatively new API, it may be good to do this early.

**Comment by roji** [comment]
@ajcvickers milestone-deprived issue

**Comment by ajcvickers** [comment]
@roji @smitpatel What I meant to do was remove the milestone _and_ reopen the issue so we can discuss again in triage since it was already reported as a break.
