### ISSUE TITLE
Entity is being deleted istead of update when mapped via AutoMapper and navigation properties are not changed

### ISSUE THREAD

**Issue by szszoke** [dotnet/efcore#21102]
Updating an entity via AutoMapper results in a `DELETE` SQL statement instead of an `UPDATE`.

### Steps to reproduce

The problem appears under the following circumstances:
1. Entity type has a navigation property `[Nav]`
2. Entity type has a separate ID field for the navigation property `[NavId]`
3. DTO type has a field that maps to the navigation property `[NavDTO -> Nav]`
4. DTO type has a field that maps to the ID of the navigation property `[NavDTOId -> NavId]`
5. DTO instance [Nav] not set to anything and [NavId] set to a valid ID is mapped to Entity instance via AutoMapper
6. Calling SaveChanges on the DbContext generates a `DELETE` statement.

Minimal reproduction of the issue with unit tests: https://github.com/szszoke/EFAutomapperBug

Failing unit tests that illustrate the problem:
- `AutoMapper_ShouldNotDelete`
- `ManualMapping_ShouldNotDelete`

In the example I am setting the primary key fields to be manually generated but having them auto-generated still results in the same problem.

### Further technical details

EF Core version: 3.1.201
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.0
Operating system: Windows 10 1903 Build 18362.836
IDE: dotnet cli

This does not seem to be a new issue:
#9156
https://stackoverflow.com/questions/47665106/entity-framework-deleting-object-upon-update
https://stackoverflow.com/questions/47334441/entity-framework-core-2-0-deleting-record-instead-of-updating-it

**Comment by szszoke** [comment]
In the meantime I noticed that AutoMapper is not needed at all.

Simply setting the navigation property to `null` and the navigation property ID field to something valid causes the problem to appear.

```diff
- mapper.Map(
-     new TestItemDTO
-     {
-         TestItemChildId = 1,
-     },
-     item);
+ item.TestItemChildId = 1;
+ item.TestItemChild = null;
```

My problem seems to be related to #13913.

**Comment by szszoke** [comment]
I found some more weirdness going on. If I leave the navigation property alone and set the ID field only then EF happily generates an `UPDATE` statement.

So to sum it up:

Attempting to change a foreign key value updating the ID field and setting the navigation property to `null` will cause EF to delete the record.
```cs
item.TestItemChildId = 1;
item.TestItemChild = null;
```

Attempting to change a foreign key value by updating the ID field only will cause EF to update the record.
```cs
item.TestItemChildId = 1;
```

**Comment by szszoke** [comment]
For people who might need a workaround with AutoMapper, I had to configure the mapping to ignore the navigation property. Please see `AutoMapper_IgnoreNavProp_ShouldNotDelete` here: https://github.com/szszoke/EFAutomapperBug/blob/master/UnitTest.cs

**Comment by ajcvickers** [comment]
@szszoke When a navigation property changes from non-null to null, then that is considered severing the relationship between the two entities. If the relationship is set to delete orphans (the default for required relationships) then this means the dependent entity will be deleted. For optional relationships, the FK is instead set to null. When both the navigation property and the FK are changed, then the current behavior is that the navigation property change wins--see #21105. We will discuss if we want to change this behavior, but I suspect it would be unlikely since it would be a significant breaking change.
