### ISSUE TITLE
PropertyChanged not fired anymore in EF Core 3.1 using CurrentValue

### ISSUE THREAD

**Issue by Quietscheente** [dotnet/efcore#21119]
I upgraded from EF Core 2.2.6 to EF Core 3.1 and the following line does not fire PropertyChanged anymore, the UI is not updated. EF Core 2.2.6 did.

``` C#
myContext.Entry(SheetToEdit).Property(prop.Name).CurrentValue = valuesSheet[prop.Name];
```

The SheetToEdit class is partial. 
The first one is original from scaffold, the second one is
``` C#
public partial class SheetToEditClass : INotifyPropertyChanged, IDataErrorInfo
```

The Nuget Package PropertyChanged.Fody is used.

If I set the values directly in the object it works as expected.

```C#
SheetToEdit.GetType().GetProperty(prop.Name).SetValue(SheetToEdit, valuesSheet[prop.Name]);
```

Is there a breaking change I did not get?

EF Core version: 3.1
Database provider: Oracle.EntityFrameworkCore
Target framework: .NET Core 3.1
Operating system: Win 10 (1809)
IDE: Visual Studio 2019 16.6.1

**Comment by ajcvickers** [comment]
@Quietscheente Starting with 3.0, EF Core now always writes directly to fields by default. See:https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#backing-fields-are-used-by-default

**Comment by Quietscheente** [comment]
Thanks, because of PropertyChanged.Fody the backing field did not occur to me.
