### ISSUE TITLE
MS Office Add-in error when inheriting a class from DbContext

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#21118]
I’m trying to create a Word [VSTO Add-in][1] project in Visual Studio 16.6.1 targeting `.NET Framework 4.8`. I want to use [Microsoft.EntityFrameworkCore.Sqlite][2] to access information in a database. However, as soon as I add a class that inherits from `DbContext`, I can no longer build the project. I get an error reporting:

    The "FindRibbons" task failed unexpectedly. 
    System.IO.FileNotFoundException: Could not load file or assembly 'WordAddInTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

WordAddinTest is the name of my project.

I can reproduce this using these minimal steps:

 1. Create a new Visual Basic project of type Word VSTO Add-in.
 2. Set the name to WordAddinTest, and the Framework to Framework .NET Framework 4.8.
 3. Using the Nuget Package Manager, install `Microsoft.EntityFrameworkCore.Sqlite`.
 4. Replace the default code in ThisAddIn.vb with the following:

Code:

    Imports Microsoft.EntityFrameworkCore
    
    Public Class ThisAddIn
        Private Sub ThisAddIn_Startup() Handles Me.Startup
        End Sub
    
        Private Sub ThisAddIn_Shutdown() Handles Me.Shutdown
        End Sub
    End Class
    
    Public Class TestClass
        Public Property Id As Integer
        Public Property Title As String
    End Class
    
    Public Class TestContext
        'Inherits DbContext
        'NOTE: If the line above is excluded, it will compile (but obviously without EntityFramework support)
    
        Public Property TestProperty As DbSet(Of TestClass)
    End Class

This will compile, run and debug without problems.

However, uncommenting the line indicated so that TestContext inherits from DbContext, it no longer compiles, and the Error List displays the following error:

    The "FindRibbons" task failed unexpectedly.
    System.IO.FileNotFoundException: Could not load file or assembly 'WordAddInTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
    File name: 'WordAddInTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
    
    Server stack trace: 
       at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
       at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
       at System.Reflection.Assembly.Load(String assemblyString)
       at System.UnitySerializationHolder.GetRealObject(StreamingContext context)
       at System.Runtime.Serialization.ObjectManager.ResolveObjectReference(ObjectHolder holder)
       at System.Runtime.Serialization.ObjectManager.DoFixups()
       at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
       at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
       at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
       at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.FixupForNewAppDomain()
       at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
    
    Exception rethrown at [0]: 
       at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
       at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
       at Microsoft.Build.Framework.ITask.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
    
    WRN: Assembly binding logging is turned OFF.
    To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
    Note: There is some performance penalty associated with assembly bind failure logging.
    To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].	WordAddInTest

Noting the advice at the end about Fusion Logging, if I set that registry value it adds the following information:

    === Pre-bind state information ===
    LOG: DisplayName = WordAddInTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
     (Fully-specified)
    LOG: Appbase = file:///C:/applications/programming/Visual Studio 2019 Community/MSBuild/Current/Bin/
    LOG: Initial PrivatePath = NULL
    Calling assembly : (Unknown).
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\applications\programming\Visual Studio 2019 Community\MSBuild\Current\Bin\MSBuild.exe.Config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
    LOG: Attempting download of new URL file:///C:/applications/programming/Visual Studio 2019 Community/MSBuild/Current/Bin/WordAddInTest.DLL.
    LOG: Attempting download of new URL file:///C:/applications/programming/Visual Studio 2019 Community/MSBuild/Current/Bin/WordAddInTest/WordAddInTest.DLL.
    LOG: Attempting download of new URL file:///C:/applications/programming/Visual Studio 2019 Community/MSBuild/Current/Bin/WordAddInTest.EXE.
    LOG: Attempting download of new URL file:///C:/applications/programming/Visual Studio 2019 Community/MSBuild/Current/Bin/WordAddInTest/WordAddInTest.EXE.	WordAddInTest

Visual Studio is looking for my Add-in DLL in the MSBuild directory.

Is it just not possible to use Entity Framework in a VSTO Add-in project?
Is there another logical explanation for why it can’t compile?
I haven’t been able to find any other reports of the same problem, and I can’t imagine I’m the first person to try it.

I realize there is more required to actually use the EntityFramework to access a database, but this is a compilation error, so it isn’t even getting that far.

Thank you for any help that can be provided.

**UPDATE**:

Following is `.vbproj` (equivalent of .csproj) file in case it can shed some light on identifying/solving the issue:

    <Project ToolsVersion="16.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
      
      <PropertyGroup>
        <ProjectTypeGuids>{BAA0C2D2-18E2-41B9-852F-F413020CAA33};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <ProjectGuid>{A4902970-1F65-45A0-AED0-5B3398DFE0CD}</ProjectGuid>
        <OutputType>Library</OutputType>
        <NoStandardLibraries>false</NoStandardLibraries>
        <RootNamespace>WordAddinTest</RootNamespace>
        <AssemblyName>WordAddinTest</AssemblyName>
        <LoadBehavior>3</LoadBehavior>
        <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
        <DefineConstants>VSTO40</DefineConstants>
        <BootstrapperEnabled>true</BootstrapperEnabled>
        <BootstrapperComponentsLocation>HomeSite</BootstrapperComponentsLocation>
      </PropertyGroup>
      <ItemGroup>
        <BootstrapperPackage Include="Microsoft.VSTORuntime.4.0">
          <Visible>False</Visible>
          <ProductName>Microsoft Visual Studio 2010 Tools for Office Runtime %28x86 and x64%29</ProductName>
          <Install>true</Install>
        </BootstrapperPackage>
      </ItemGroup>
      <PropertyGroup>
        
        <OfficeApplication>Word</OfficeApplication>
      </PropertyGroup>
      
      <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
        <WarningLevel>4</WarningLevel>
      </PropertyGroup>
      
      <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
        <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
        <WarningLevel>4</WarningLevel>
      </PropertyGroup>
      
      <ItemGroup>
        <Reference Include="Accessibility" />
        <Reference Include="System" />
        <Reference Include="System.Data" />
        <Reference Include="System.Drawing" />
        <Reference Include="System.Windows.Forms" />
        <Reference Include="System.Xml" />
        <Reference Include="System.Core" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="Microsoft.CSharp" />
      </ItemGroup>
      <ItemGroup>
        <Reference Include="Microsoft.Office.Tools.v4.0.Framework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.Tools.Applications.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.Office.Tools, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.Office.Tools.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.Office.Tools.Word, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
      </ItemGroup>
      <ItemGroup>
        <Reference Include="Microsoft.Office.Tools.Common.v4.0.Utilities, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>True</Private>
        </Reference>
      </ItemGroup>
      <ItemGroup>
        <Reference Include="Office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
          <Private>False</Private>
          <EmbedInteropTypes>true</EmbedInteropTypes>
        </Reference>
        <Reference Include="Microsoft.Office.Interop.Word, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
          <Private>False</Private>
          <EmbedInteropTypes>true</EmbedInteropTypes>
        </Reference>
        <Reference Include="stdole, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
          <Private>False</Private>
        </Reference>
      </ItemGroup>
      
      <ItemGroup>
        <Compile Include="Model.cs" />
        <Compile Include="Properties\AssemblyInfo.cs">
          <SubType>Code</SubType>
        </Compile>
        <EmbeddedResource Include="Properties\Resources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>Resources.Designer.cs</LastGenOutput>
          <SubType>Designer</SubType>
        </EmbeddedResource>
        <Compile Include="Properties\Resources.Designer.cs">
          <AutoGen>True</AutoGen>
          <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <None Include="WordAddinTest_TemporaryKey.pfx" />
        <None Include="Properties\Settings.settings">
          <Generator>SettingsSingleFileGenerator</Generator>
          <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <Compile Include="Properties\Settings.Designer.cs">
          <AutoGen>True</AutoGen>
          <DependentUpon>Settings.settings</DependentUpon>
        </Compile>
        <Compile Include="Ribbon1.cs" />
        <Compile Include="ThisAddIn.cs">
          <SubType>Code</SubType>
        </Compile>
        <None Include="ThisAddIn.Designer.xml">
          <DependentUpon>ThisAddIn.cs</DependentUpon>
        </None>
        <Compile Include="ThisAddIn.Designer.cs">
          <DependentUpon>ThisAddIn.Designer.xml</DependentUpon>
        </Compile>
        <AppDesigner Include="Properties\" />
      </ItemGroup>
      <ItemGroup>
        <EmbeddedResource Include="Ribbon1.xml" />
      </ItemGroup>
      <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite">
          <Version>3.1.4</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
          <Version>3.1.4</Version>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
      </ItemGroup>
      <PropertyGroup>
        <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
        <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
      </PropertyGroup>
      <PropertyGroup>
        <SignManifests>true</SignManifests>
      </PropertyGroup>
      <PropertyGroup>
        <ManifestKeyFile>WordAddinTest_TemporaryKey.pfx</ManifestKeyFile>
      </PropertyGroup>
      <PropertyGroup>
        <ManifestCertificateThumbprint>002EE54C6C297029AF8A7691A5DAC8F51DACA96A</ManifestCertificateThumbprint>
      </PropertyGroup>
      
      <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
      
      <Import Project="$(VSToolsPath)\OfficeTools\Microsoft.VisualStudio.Tools.Office.targets" Condition="'$(VSToolsPath)' != ''" />
      
      <ProjectExtensions>
        <VisualStudio>
          <FlavorProperties GUID="{BAA0C2D2-18E2-41B9-852F-F413020CAA33}">
            <ProjectProperties HostName="Word" HostPackage="{29A7B9D7-A7F1-4328-8EF0-6B2D1A56B2C1}" OfficeVersion="15.0" VstxVersion="4.0" ApplicationType="Word" Language="cs" TemplatesPath="" DebugInfoExeName="#Software\Microsoft\Office\16.0\Word\InstallRoot\Path#WINWORD.EXE" DebugInfoCommandLine="/x" AddItemTemplatesGuid="{51063C3A-E220-4D12-8922-BDA915ACD783}" />
            <Host Name="Word" GeneratedCodeNamespace="WordAddinTest" IconIndex="0">
              <HostItem Name="ThisAddIn" Code="ThisAddIn.cs" CanonicalName="AddIn" CanActivate="false" IconIndex="1" Blueprint="ThisAddIn.Designer.xml" GeneratedCode="ThisAddIn.Designer.cs" />
            </Host>
          </FlavorProperties>
        </VisualStudio>
      </ProjectExtensions>
    </Project>

  [1]: https://docs.microsoft.com/en-us/visualstudio/vsto/create-vsto-add-ins-for-office-by-using-visual-studio?view=vs-2019
  [2]: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite/

**Comment by ajcvickers** [comment]
@Pilchie We have seen several issues recently which indicate that "Visual Studio Tools for Office" do not work correctly with .NET Standard dependencies. Do you know who would be an appropriate contact to follow up on this?

**Comment by John-Hart** [comment]
Thanks @saf-itpro we've opened a VSTO bug for this.  In the future, if you run into VSTO issues please use the Help->Send Feedback menu in Visual Studio

**Comment by John-Hart** [comment]
@saf-itpro  you can use this bug to track this issue: https://developercommunity.visualstudio.com/content/problem/1031063/compilation-error-findribbons-task-failed-unexpect.html

**Comment by saf-itpro** [comment]
@John-Hart Thank you for re-opening the issue [here](https://developercommunity.visualstudio.com/content/problem/1031063/compilation-error-findribbons-task-failed-unexpect.html). I'll track it.
