### ISSUE TITLE
EntityStateChangedEventArgs with wrong OldState and in the NewState property values

### ISSUE THREAD

**Issue by daniel3303** [dotnet/efcore#21117]
When you directly add an entity that is not being tracked to the DbContext using DbContext.Update(entity) and you listen to the ChangeTracker.StateChanged event, the event NewState and OldState properties are not correct.
The expected true values are OldState = Unchanged and NewState = Modified. However, the values that you get are OldState = Modified and NewState = Unchanged.

### Steps to reproduce

Write a controller action to update your entity without loading it from the database, for instance:

``` C#
public async Task<IActionResult> Edit([Bind("Id", "Name")]Entity entity) {
             _dbContext.Update(entity);
            await _dbContext.SaveChangesAsync();
            return Ok();
}
```

Then listen to the ChangeTracker StateChanged event, for instance:
``` C#
private void OnEntityStateChanged(object sender, EntityStateChangedEventArgs e) {
            Console.WriteLine(e.NewState); // Unchanged
            Console.WriteLine(e.OldState); // Modified
}
```

However, after the event is triggered the final entity state is Modified what does not make sense since the final state should be the same has the NewState property in the StateChanged event.

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.4
Operating system: macOS Catalina
IDE: Intellij Rider

**Comment by ajcvickers** [comment]
@daniel3303 That event is being fired when SaveChanges is being called, and as such the old and new state are correct. Listen to the `ChangeTracker.Tracked` to get notified when EF starts tracking the query. In my testing, `args.Entry.State` then correctly indicates that the entity is being tracked in the `Modified` state.
