### ISSUE TITLE
IPluralizer is missing in EntityFrameworkCore.Design 5.0

### ISSUE THREAD

**Issue by mannok** [dotnet/efcore#21122]
I used to implement `IDesignTimeServices` with `IPluralizer` in order to make `scaffold-dbcontext works so that I can switch pluralized table names into signalized entity name. e.g. Clients -> Client `

After I upgraded to EF Core 5.0, IPluralizer gone... I can no longer change my entity name. Did I miss something?

### Steps to reproduce
```
using Inflector;
using System;
using System.Collections.Generic;
using System.Text;

namespace IB.Stock.TestConsole.EFConfig
{
    class EFPluralizer : IPluralizer
    {
        public string Pluralize(string identifier)
        {
            return Inflector.Pluralize(identifier) ?? identifier;
        }

        public string Singularize(string identifier)
        {
            return Inflector.Singularize(identifier) ?? identifier;
        }
    }
}

```

The above is some of my code. I cannot find any reference for `IPluralizer`.

### Further technical details

EF Core version: 5.0.0-preview.4.20220.10
EntityFrameworkCore.Design version: 5.0.0-preview.4.20220.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by ErikEJ** [comment]
It is still there: https://github.com/dotnet/efcore/blob/0d76bbf45a42148924b413ef8f37bf49c1ce10d3/src/EFCore.Design/Design/IPluralizer.cs 

Maybe you are hit by this breaking change: https://docs.microsoft.com/da-dk/ef/core/what-is-new/ef-core-3.0/breaking-changes#dip

**Comment by kevin-a-naude** [comment]
@mannok It may be that the assets included by the package reference to Microsoft.EntityFrameworkCore.Design excludes necessary assets to use IPluralize.

When I installed Microsoft.EntityFrameworkCore.Design into a Net5.0 library project, it was installed as follows.
```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets> <!-- this line -->
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

Note that the default for `IncludeAssets` is `all` when it is omitted. If you have a line like the above in your project, you can correct the problem by either deleting the `IncludeAssets` line, or by adding `compile` to the list of included assets. I'm not sure if this fix will be required in the future, but it seems necessary at present.

You can read about the available options for `IncludeAssets` at [https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files).
