### ISSUE TITLE
Feature: Add "-Views" in Scaffold-DbContext

### ISSUE THREAD

**Issue by TomaszGrzmilas** [dotnet/efcore#21123]
Hi,

I want to Scaffold one view from database. When using "-Tables <name>" i get error: no table found.

I suggest to add a "-Views" switch to a Scaffold-DbContext command.

Br
Tom Thunderforest

**Comment by ErikEJ** [comment]
Which EF Core version?

**Comment by TomaszGrzmilas** [comment]
EF Core 3.1.4

**Comment by ErikEJ** [comment]
Suggest you provide a sample SQL schema script, that can reproduce the issue.

**Comment by TomaszGrzmilas** [comment]
Hi,

Ok I checked and with MySQL database it ok - I can pass view name as parameter for "-Tables ".
I get the error when using Oracle Database (-Provider "Oracle.EntityFrameworkCore")

Sorry for bothering.

**Comment by ErikEJ** [comment]
Yes, the Oracle (preview) provider has some issues: https://github.com/oracle/dotnet-db-samples/issues/73
