### ISSUE TITLE
Update RelationalModelValidator validation for non-store-generated shared concurrency columns

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#21136]
`RelationalModelValidator.ValidateSharedColumnsCompatibility` ensures (among other things) that EntityTypes are not missing a concurrency token property when properties share the same column. However the definition of "concurrency token property" only includes ones where it is also store-generated.

`TableSharingConcurrencyTokenConvention` was recently updated see (PR #21128 and associated issue #21041) to create such properties for all concurrency token properties, not just ones which are store-generated.

We should look into changing `RelationalModelValidator` in the same way.

### Further technical details
EF Core version: 5.0.0-preview5

**Comment by AndriySvyryd** [comment]
We only validate the store generated concurrency tokens because those are the ones that can change value when a table-sharing entity is updated without updating the other entities in the row.
