### ISSUE TITLE
Exception when saving value to a shared column

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#21139]
This scenario was broken by https://github.com/dotnet/efcore/pull/21128

See test in https://github.com/dotnet/efcore/commit/347e9cf5017c90a888f8aec5609ba7c92d1cfc4e

**Comment by AndriySvyryd** [comment]
Consider adding another value to ValueGenerated: `OnUpdateSometimes`

**Comment by ajcvickers** [comment]
@AndriySvyryd @smitpatel Happy for this to be poached.
