### ISSUE TITLE
Group by LINQ queries too complex for Entity Framework Core?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21150]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1065318/group-by-linq-queries-too-complex-for-entity-frame.html)._

---
I have the following code/query.

    public async Task<IEnumerable<FinancialsLocation>> DoSomething(ApplicationDbContext dbContext, DateRange dateRange)
    {
        return await (from detail in QueryFinancialDetails(dbContext, dateRange)
                        group detail by detail.LocationId
                        into locations
                        select new FinancialsLocation
                        {
                            Id = locations.Key,
                            StorageCost = locations.Sum(l => l.StorageCost),
                            SwitchInCost = locations.Sum(l => l.SwitchInCost),
                            SwitchOutCost = locations.Sum(l => l.SwitchOutCost),
                            CherryPickCost = locations.Sum(l => l.CherryPickCost),
                            StorageRevenue = locations.Sum(l => l.StorageFee),
                            SwitchInRevenue = locations.Sum(l => l.SwitchInFee),
                            SwitchOutRevenue = locations.Sum(l => l.SwitchOutFee),
                            CherryPickRevenue = locations.Sum(l => l.CherryPickFee),
                            StorageProfit = locations.Sum(l => l.StorageProfit),
                            SwitchInProfit = locations.Sum(l => l.SwitchInProfit),
                            SwitchOutProfit = locations.Sum(l => l.SwitchOutProfit),
                            CherryPickProfit = locations.Sum(l => l.CherryPickProfit),
                            FinancialDetails = null,
                        })
                        .ToListAsync();
    }

    private IQueryable<FinancialItem> QueryFinancialDetails(ApplicationDbContext dbContext, DateRange dateRange)
    {
        return from detail in QueryHelper.QueryStorageDetails(dbContext, dateRange)
                let startDate = (detail.TakeOrPayStartDate < detail.ArrivalDate) ?
                    (DateTime)detail.TakeOrPayStartDate :
                    detail.ArrivalDate.Value
                let endDate = (detail.TakeOrPayEndDate > detail.DepartureDate) ?
                    detail.TakeOrPayEndDate.Value :
                    detail.DepartureDate ?? dateRange.EndDate
                let rangeStartDate = (startDate >= dateRange.StartDate) ? startDate : dateRange.StartDate
                let rangeEndDate = (endDate <= dateRange.EndDate) ? endDate : dateRange.EndDate
                let daysInStorage = EF.Functions.DateDiffDay(rangeStartDate, rangeEndDate) + 1
                select new FinancialItem
                {
                    LocationId = detail.LocationId,
                    Name = detail.Location.Name,
                    City = detail.Location.City,
                    State = detail.Location.State,
                    Customer = detail.Customer.Name,
                    RailcarNumber = detail.RailcarNumber,
                    TakeOrPayId = detail.TakeOrPayId,
                    DaysInStorage = daysInStorage,
                    DailyStorageRate = detail.DailyStorageRate ?? 0,
                    SwitchInRate = detail.SwitchInRate ?? 0,
                    SwitchOutRate = detail.SwitchOutRate ?? 0,
                    CherryPickRate = detail.CherryPickRate ?? 0,
                    StorageCost = detail.DailyStorageCost * daysInStorage,
                    SwitchInCost = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                        detail.SwitchInCost : 0,
                    SwitchOutCost = (detail.DepartureDate >= dateRange.StartDate && detail.DepartureDate <= dateRange.EndDate) ?
                        detail.SwitchOutCost : 0,
                    CherryPickCost = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                        detail.CherryPickCost : 0,
                    StorageFee = (detail.DailyStorageRate ?? 0) * daysInStorage,
                    SwitchInFee = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                        detail.SwitchInRate ?? 0 : 0,
                    SwitchOutFee = (detail.DepartureDate >= dateRange.StartDate && detail.DepartureDate <= dateRange.EndDate) ?
                        detail.SwitchOutRate ?? 0 : 0,
                    CherryPickFee = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                        detail.CherryPickRate ?? 0 : 0,
                };
    }

    public static IQueryable<StorageDetail> QueryStorageDetails(ApplicationDbContext dbContext, DateRange dateRange)
    {
        return from detail in dbContext.StorageDetails
                where (detail.ArrivalDate != null && detail.ArrivalDate <= dateRange.EndDate &&
                    (detail.DepartureDate == null || detail.DepartureDate >= dateRange.StartDate)) ||
                    (detail.TakeOrPayStartDate != null && detail.TakeOrPayStartDate <= dateRange.EndDate &&
                    (detail.TakeOrPayEndDate == null || detail.TakeOrPayEndDate >= dateRange.StartDate))
                select detail;
    }

This query generates the following exception:

>System.InvalidOperationException: The LINQ expression 'new FinancialItem{ 
    LocationId = (ProjectionBindingExpression: LocationId), 
    Name = (ProjectionBindingExpression: Name), 
    City = (ProjectionBindingExpression: City), 
    State = (ProjectionBindingExpression: State), 
    Customer = (ProjectionBindingExpression: Customer), 
    RailcarNumber = (ProjectionBindingExpression: RailcarNumber), 
    TakeOrPayId = (ProjectionBindingExpression: TakeOrPayId), 
    DaysInStorage = (ProjectionBindingExpression: DaysInStorage), 
    DailyStorageRate = (ProjectionBindingExpression: DailyStorageRate), 
    SwitchInRate = (ProjectionBindingExpression: SwitchInRate), 
    SwitchOutRate = (ProjectionBindingExpression: SwitchOutRate), 
    CherryPickRate = (ProjectionBindingExpression: CherryPickRate), 
    StorageCost = (ProjectionBindingExpression: StorageCost), 
    SwitchInCost = (ProjectionBindingExpression: SwitchInCost), 
    SwitchOutCost = (ProjectionBindingExpression: SwitchOutCost), 
    CherryPickCost = (ProjectionBindingExpression: CherryPickCost), 
    StorageFee = (ProjectionBindingExpression: StorageFee), 
    SwitchInFee = (ProjectionBindingExpression: SwitchInFee), 
    SwitchOutFee = (ProjectionBindingExpression: SwitchOutFee), 
    CherryPickFee = (ProjectionBindingExpression: CherryPickFee) 
}
.StorageProfit' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

I could easily get this to work by calling `ToList()` before grouping the data. But that would download a massive number of rows when all I want are the totals.

Can anyone explain what part of this query is too complex? And is there anything that could be done to support a query like this without downloading all the data?

---
#### Jonathan Wood on 6/4/2020, 10:12 AM: 

<p>In the code above, the following is in error:</p><p>StorageProfit = locations.Sum(l =&gt; l.StorageProfit),<br>SwitchInProfit = locations.Sum(l =&gt; l.SwitchInProfit),<br>SwitchOutProfit = locations.Sum(l =&gt; l.SwitchOutProfit),<br>CherryPickProfit = locations.Sum(l =&gt; l.CherryPickProfit),</p><p>These profit properties are actually calculated on the client side and so they could never work here. However, I've removed these lines and an error still persists.</p><p>I think the problem has to do with the calculations in `QueryFinancialDetails` not being able to be used in the `Sum()` calls in `DoSomething()`.</p>

#### Visual Studio Feedback System on 6/5/2020, 01:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jonathan Wood on 6/5/2020, 08:03 AM: 

<p>Working with this further, I haven't found a single real-World `group by` query that Entity Framework Core seems able to handle. Would like to hear on if this is improving or if there's a workaround.</p>

---
### Original Solutions
(no solutions)

**Comment by smitpatel** [comment]
```C#
 select new FinancialItem
            {
                LocationId = detail.LocationId,
                Name = detail.Location.Name,
                City = detail.Location.City,
                State = detail.Location.State,
                Customer = detail.Customer.Name,
                RailcarNumber = detail.RailcarNumber,
                TakeOrPayId = detail.TakeOrPayId,
                DaysInStorage = daysInStorage,
                DailyStorageRate = detail.DailyStorageRate ?? 0,
                SwitchInRate = detail.SwitchInRate ?? 0,
                SwitchOutRate = detail.SwitchOutRate ?? 0,
                CherryPickRate = detail.CherryPickRate ?? 0,
                StorageCost = detail.DailyStorageCost * daysInStorage,
                SwitchInCost = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                    detail.SwitchInCost : 0,
                SwitchOutCost = (detail.DepartureDate >= dateRange.StartDate && detail.DepartureDate <= dateRange.EndDate) ?
                    detail.SwitchOutCost : 0,
                CherryPickCost = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                    detail.CherryPickCost : 0,
                StorageFee = (detail.DailyStorageRate ?? 0) * daysInStorage,
                SwitchInFee = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                    detail.SwitchInRate ?? 0 : 0,
                SwitchOutFee = (detail.DepartureDate >= dateRange.StartDate && detail.DepartureDate <= dateRange.EndDate) ?
                    detail.SwitchOutRate ?? 0 : 0,
                CherryPickFee = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                    detail.CherryPickRate ?? 0 : 0,
            };
```
does not contain definition for `StorageProfit` but you are using that in `StorageProfit = locations.Sum(l => l.StorageProfit)`, EF Core has no way to compute that value.

**Comment by SoftCircuits** [comment]
@smitpatel : I addressed that in my comment. Guess I should edit the original question.

**Comment by smitpatel** [comment]
Error message mentions the `StorageProfit` property explicitly.

**Comment by SoftCircuits** [comment]
> Error message mentions the `StorageProfit` property explicitly.

Please read my reply about how that part was a mistake and I've removed those and the error persists. In fact, all my attempts to do GROUP BY in a LINQ query and Entity Framework have failed with a similar error.

**Comment by smitpatel** [comment]
@SoftCircuits - You need to provide more details on what parts you removed, what is the current query you are running and what is the error you are getting.

**Comment by SoftCircuits** [comment]
Despite my correction in a comment, it appears this was not a great example. So here's another, perhaps better, example.

>The LINQ expression 'DbSet<StorageDetail>
    .Where(s => s.ArrivalDate != null && s.ArrivalDate <= __dateRange_EndDate_0 && s.ReleaseDate == null || s.ReleaseDate >= __dateRange_StartDate_1 || s.TakeOrPayStartDate != null && s.TakeOrPayStartDate <= __dateRange_EndDate_0 && s.TakeOrPayEndDate == null || s.TakeOrPayEndDate >= __dateRange_StartDate_1)
    .Join(
        outer: DbSet<Location>, 
        inner: s => EF.Property<Nullable<int>>(s, "LocationId"), 
        outerKeySelector: l => EF.Property<Nullable<int>>(l, "Id"), 
        innerKeySelector: (o, i) => new TransparentIdentifier<StorageDetail, Location>(
            Outer = o, 
            Inner = i
        ))
    .Join(
        outer: DbSet<Customer>, 
        inner: s => EF.Property<Nullable<int>>(s.Outer, "CustomerId"), 
        outerKeySelector: c => EF.Property<Nullable<int>>(c, "Id"), 
        innerKeySelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<StorageDetail, Location>, Customer>(
            Outer = o, 
            Inner = i
        ))
    .GroupBy(
        source: s => new { 
            Id = s.Outer.Outer.LocationId, 
            Name = s.Outer.Inner.Name, 
            City = s.Outer.Inner.City, 
            State = s.Outer.Inner.State, 
            CustomerId = new FinancialItem{ 
                LocationId = s.Outer.Outer.LocationId, 
                Name = s.Outer.Inner.Name, 
                City = s.Outer.Inner.City, 
                State = s.Outer.Inner.State, 
                Customer = s.Inner.Name, 
                RailcarNumber = s.Outer.Outer.RailcarNumber, 
                TakeOrPayId = s.Outer.Outer.TakeOrPayId, 
                DaysInStorage = __Functions_4
                    .DateDiffDay(
                        _: s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value >= __dateRange_StartDate_3 ? s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value : __dateRange_StartDate_3, 
                        startDate: s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 <= __dateRange_EndDate_2 ? s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 : __dateRange_EndDate_2) + 1, 
                DailyStorageRate = s.Outer.Outer.DailyStorageRate ?? 0, 
                SwitchInRate = s.Outer.Outer.SwitchInRate ?? 0, 
                SwitchOutRate = s.Outer.Outer.SwitchOutRate ?? 0, 
                CherryPickRate = s.Outer.Outer.CherryPickRate ?? 0, 
                StorageCost = s.Outer.Outer.DailyStorageCost * (decimal)(__Functions_4
                    .DateDiffDay(
                        _: s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value >= __dateRange_StartDate_3 ? s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value : __dateRange_StartDate_3, 
                        startDate: s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 <= __dateRange_EndDate_2 ? s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 : __dateRange_EndDate_2) + 1), 
                SwitchInCost = s.Outer.Outer.ArrivalDate >= __dateRange_StartDate_5 && s.Outer.Outer.ArrivalDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchInCost : 0, 
                SwitchOutCost = s.Outer.Outer.ReleaseDate >= __dateRange_StartDate_5 && s.Outer.Outer.ReleaseDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchOutCost : 0, 
                CherryPickCost = s.Outer.Outer.CherryPickDate >= __dateRange_StartDate_5 && s.Outer.Outer.CherryPickDate <= __dateRange_EndDate_6 ? s.Outer.Outer.CherryPickCost : 0, 
                StorageRevenue = s.Outer.Outer.DailyStorageRate ?? 0 * (decimal)(__Functions_4
                    .DateDiffDay(
                        _: s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value >= __dateRange_StartDate_3 ? s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value : __dateRange_StartDate_3, 
                        startDate: s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 <= __dateRange_EndDate_2 ? s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 : __dateRange_EndDate_2) + 1), 
                SwitchInRevenue = s.Outer.Outer.ArrivalDate >= __dateRange_StartDate_5 && s.Outer.Outer.ArrivalDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchInRate ?? 0 : 0, 
                SwitchOutRevenue = s.Outer.Outer.ReleaseDate >= __dateRange_StartDate_5 && s.Outer.Outer.ReleaseDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchOutRate ?? 0 : 0, 
                CherryPickRevenue = s.Outer.Outer.CherryPickDate >= __dateRange_StartDate_5 && s.Outer.Outer.CherryPickDate <= __dateRange_EndDate_6 ? s.Outer.Outer.CherryPickRate ?? 0 : 0 
            }
            .CustomerId, 
            Customer = s.Inner.Name
         }, 
        keySelector: s => new FinancialItem{ 
            LocationId = s.Outer.Outer.LocationId, 
            Name = s.Outer.Inner.Name, 
            City = s.Outer.Inner.City, 
            State = s.Outer.Inner.State, 
            Customer = s.Inner.Name, 
            RailcarNumber = s.Outer.Outer.RailcarNumber, 
            TakeOrPayId = s.Outer.Outer.TakeOrPayId, 
            DaysInStorage = __Functions_4
                .DateDiffDay(
                    _: s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value >= __dateRange_StartDate_3 ? s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value : __dateRange_StartDate_3, 
                    startDate: s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 <= __dateRange_EndDate_2 ? s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 : __dateRange_EndDate_2) + 1, 
            DailyStorageRate = s.Outer.Outer.DailyStorageRate ?? 0, 
            SwitchInRate = s.Outer.Outer.SwitchInRate ?? 0, 
            SwitchOutRate = s.Outer.Outer.SwitchOutRate ?? 0, 
            CherryPickRate = s.Outer.Outer.CherryPickRate ?? 0, 
            StorageCost = s.Outer.Outer.DailyStorageCost * (decimal)(__Functions_4
                .DateDiffDay(
                    _: s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value >= __dateRange_StartDate_3 ? s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value : __dateRange_StartDate_3, 
                    startDate: s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 <= __dateRange_EndDate_2 ? s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 : __dateRange_EndDate_2) + 1), 
            SwitchInCost = s.Outer.Outer.ArrivalDate >= __dateRange_StartDate_5 && s.Outer.Outer.ArrivalDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchInCost : 0, 
            SwitchOutCost = s.Outer.Outer.ReleaseDate >= __dateRange_StartDate_5 && s.Outer.Outer.ReleaseDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchOutCost : 0, 
            CherryPickCost = s.Outer.Outer.CherryPickDate >= __dateRange_StartDate_5 && s.Outer.Outer.CherryPickDate <= __dateRange_EndDate_6 ? s.Outer.Outer.CherryPickCost : 0, 
            StorageRevenue = s.Outer.Outer.DailyStorageRate ?? 0 * (decimal)(__Functions_4
                .DateDiffDay(
                    _: s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value >= __dateRange_StartDate_3 ? s.Outer.Outer.TakeOrPayStartDate < s.Outer.Outer.ArrivalDate ? (DateTime)s.Outer.Outer.TakeOrPayStartDate : s.Outer.Outer.ArrivalDate.Value : __dateRange_StartDate_3, 
                    startDate: s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 <= __dateRange_EndDate_2 ? s.Outer.Outer.TakeOrPayEndDate > s.Outer.Outer.ReleaseDate ? s.Outer.Outer.TakeOrPayEndDate.Value : s.Outer.Outer.ReleaseDate ?? __dateRange_EndDate_2 : __dateRange_EndDate_2) + 1), 
            SwitchInRevenue = s.Outer.Outer.ArrivalDate >= __dateRange_StartDate_5 && s.Outer.Outer.ArrivalDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchInRate ?? 0 : 0, 
            SwitchOutRevenue = s.Outer.Outer.ReleaseDate >= __dateRange_StartDate_5 && s.Outer.Outer.ReleaseDate <= __dateRange_EndDate_6 ? s.Outer.Outer.SwitchOutRate ?? 0 : 0, 
            CherryPickRevenue = s.Outer.Outer.CherryPickDate >= __dateRange_StartDate_5 && s.Outer.Outer.CherryPickDate <= __dateRange_EndDate_6 ? s.Outer.Outer.CherryPickRate ?? 0 : 0 
        }
    )' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

And here's the code:

```cs
public async Task<IEnumerable<FinancialsLocation>> GetFinancialsByLocation(ApplicationDbContext dbContext, DateRange dateRange)
{
    return await (from detail in QueryFinancialDetails(dbContext, dateRange)
                    group detail by new
                    {
                        Id = detail.LocationId,
                        detail.Name,
                        detail.City,
                        detail.State,
                        detail.CustomerId,
                        detail.Customer,
                    }
                    into locations
                    select new FinancialsLocation
                    {
                        Id = locations.Key.Id,
                        Name = locations.Key.Name,
                        City = locations.Key.City,
                        State = locations.Key.State,
                        CustomerId = locations.Key.CustomerId,
                        Customer = locations.Key.Customer,
                        TotalStorageCost = locations.Sum(l => l.StorageCost),
                        TotalSwitchInCost = locations.Sum(l => l.SwitchInCost),
                        TotalSwitchOutCost = locations.Sum(l => l.SwitchOutCost),
                        TotalCherryPickCost = locations.Sum(l => l.CherryPickCost),
                        TotalStorageRevenue = locations.Sum(l => l.StorageRevenue),
                        TotalSwitchInRevenue = locations.Sum(l => l.SwitchInRevenue),
                        TotalSwitchOutRevenue = locations.Sum(l => l.SwitchOutRevenue),
                        TotalCherryPickRevenue = locations.Sum(l => l.CherryPickRevenue),
                        FinancialDetails = null,
                    })
                    .ToListAsync();
}

private IQueryable<FinancialItem> QueryFinancialDetails(ApplicationDbContext dbContext, DateRange dateRange)
{
    return from detail in QueryHelper.QueryStorageDetails(dbContext, dateRange)
            let startDate = (detail.TakeOrPayStartDate < detail.ArrivalDate) ?
                (DateTime)detail.TakeOrPayStartDate :
                detail.ArrivalDate.Value
            let endDate = (detail.TakeOrPayEndDate > detail.ReleaseDate) ?
                detail.TakeOrPayEndDate.Value :
                detail.ReleaseDate ?? dateRange.EndDate
            let rangeStartDate = (startDate >= dateRange.StartDate) ? startDate : dateRange.StartDate
            let rangeEndDate = (endDate <= dateRange.EndDate) ? endDate : dateRange.EndDate
            let daysInStorage = EF.Functions.DateDiffDay(rangeStartDate, rangeEndDate) + 1
            select new FinancialItem
            {
                LocationId = detail.LocationId,
                Name = detail.Location.Name,
                City = detail.Location.City,
                State = detail.Location.State,
                Customer = detail.Customer.Name,
                RailcarNumber = detail.RailcarNumber,
                TakeOrPayId = detail.TakeOrPayId,
                DaysInStorage = daysInStorage,
                DailyStorageRate = detail.DailyStorageRate ?? 0,
                SwitchInRate = detail.SwitchInRate ?? 0,
                SwitchOutRate = detail.SwitchOutRate ?? 0,
                CherryPickRate = detail.CherryPickRate ?? 0,
                StorageCost = detail.DailyStorageCost * daysInStorage,
                SwitchInCost = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                    detail.SwitchInCost : 0,
                SwitchOutCost = (detail.ReleaseDate >= dateRange.StartDate && detail.ReleaseDate <= dateRange.EndDate) ?
                    detail.SwitchOutCost : 0,
                CherryPickCost = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                    detail.CherryPickCost : 0,
                StorageRevenue = (detail.DailyStorageRate ?? 0) * daysInStorage,
                SwitchInRevenue = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                    detail.SwitchInRate ?? 0 : 0,
                SwitchOutRevenue = (detail.ReleaseDate >= dateRange.StartDate && detail.ReleaseDate <= dateRange.EndDate) ?
                    detail.SwitchOutRate ?? 0 : 0,
                CherryPickRevenue = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                    detail.CherryPickRate ?? 0 : 0,
            };
}

public static IQueryable<StorageDetail> QueryStorageDetails(ApplicationDbContext dbContext, DateRange dateRange)
{
    return from detail in dbContext.StorageDetails
            where (detail.ArrivalDate != null && detail.ArrivalDate <= dateRange.EndDate &&
                (detail.ReleaseDate == null || detail.ReleaseDate >= dateRange.StartDate)) ||
                (detail.TakeOrPayStartDate != null && detail.TakeOrPayStartDate <= dateRange.EndDate &&
                (detail.TakeOrPayEndDate == null || detail.TakeOrPayEndDate >= dateRange.StartDate))
            select detail;
}
```

**Comment by smitpatel** [comment]
```C#
select new FinancialItem
            {
                LocationId = detail.LocationId,
                Name = detail.Location.Name,
                City = detail.Location.City,
                State = detail.Location.State,
                Customer = detail.Customer.Name,
                RailcarNumber = detail.RailcarNumber,
                TakeOrPayId = detail.TakeOrPayId,
                DaysInStorage = daysInStorage,
                DailyStorageRate = detail.DailyStorageRate ?? 0,
                SwitchInRate = detail.SwitchInRate ?? 0,
                SwitchOutRate = detail.SwitchOutRate ?? 0,
                CherryPickRate = detail.CherryPickRate ?? 0,
                StorageCost = detail.DailyStorageCost * daysInStorage,
                SwitchInCost = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                    detail.SwitchInCost : 0,
                SwitchOutCost = (detail.ReleaseDate >= dateRange.StartDate && detail.ReleaseDate <= dateRange.EndDate) ?
                    detail.SwitchOutCost : 0,
                CherryPickCost = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                    detail.CherryPickCost : 0,
                StorageRevenue = (detail.DailyStorageRate ?? 0) * daysInStorage,
                SwitchInRevenue = (detail.ArrivalDate >= dateRange.StartDate && detail.ArrivalDate <= dateRange.EndDate) ?
                    detail.SwitchInRate ?? 0 : 0,
                SwitchOutRevenue = (detail.ReleaseDate >= dateRange.StartDate && detail.ReleaseDate <= dateRange.EndDate) ?
                    detail.SwitchOutRate ?? 0 : 0,
                CherryPickRevenue = (detail.CherryPickDate >= dateRange.StartDate && detail.CherryPickDate <= dateRange.EndDate) ?
                    detail.CherryPickRate ?? 0 : 0,
            };
```
Does not project `CustomerId` which you are using in your key selector.

**Comment by SoftCircuits** [comment]
@smitpatel : OMG, you're absolutely right. Now it works! I guess the error message threw me as it seemed to be suggesting the query was too complex somehow. Next time I see this error, I will know to more carefully check I'm providing every column I need. The error message could definitely be a little more helpful here.

I certainly appreciate you looking at this. You helped me a great deal. Thanks.
