### ISSUE TITLE
Discriminator should be read-only

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#21154]

**Comment by ajcvickers** [comment]
Make discriminator read-only by default, but allow explicit configuration back to read-write.

**Comment by lajones** [comment]
Note: after discussion with @ajcvickers the comment above does _not_ mean "add an API on DiscriminatorBuilder which would call down and make the property read-write"; it means "rely on existing APIs to do that, whether that's Metadata API or some sugar we add later to allow any property to be set read-write if it is currently read-only, just don't implement this issue in such a way that it makes the discriminator's property _never_ be settable to read-write".
