### ISSUE TITLE
After generating a migration in EF Core, the project reports NuGet issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21151]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1062090/after-generating-a-migration-in-ef-core-the-projec.html)._

---
I have a relatively simple ASP.NET Core MVC app, that I run inside a Docker container using the Docker mechanism built into VS for Mac, with minor changes to install the dotnet SDK and dotnet-ef tool in the running container to make it possible to generate migrations.

Any time I run `dotnet ef migrations add` inside the container, the process succeeds (provided I haven’t got the app running inside Visual Studio; if I do, the migrations process fails because the app fails to build first), but when I then build and run the app I get the same warning every single time :

&gt; The “ResolvePackageAssets” task failed unexpectedly

This is relatively trivial to fix (by performing a NuGet restore), although *that* process often seems to fail when run. Whether or not the process fails, though, the ResolvePackageAssets error goes away and the app builds and runs just fine.

This is, so far, my biggest single frustration with VS for Mac.

---
#### Visual Studio Feedback System on 6/3/2020, 00:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Please report this issue to NuGet: https://github.com/NuGet
