### ISSUE TITLE
[Question] Inheritance Entity unable to Insert

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2115]
Hi,

Let said if I have entity Customer : Account.

When I want to insert account it work perfectly.
but when I insert Customer it error encounter since I never create an entity of customer.
I expect the data of customer is store into Account table.

An unhandled exception occurred while processing the request.

ModelItemNotFoundException: The entity type 'Customer' was not found. Ensure that the entity type has been added to the model.
Microsoft.Data.Entity.Metadata.Model.GetEntityType(Type type)

Do I need to map the customer value to account then perform add?
Why the above operation unable to perform Insert?

EF Version: v7.0.0-beta4-12943

**Comment by rowanmiller** [comment]
Inheritance isn't fully implemented yet so the types don't get included in the model. You won't be able to use inheritance properly until we have basic implementation finished.
