### ISSUE TITLE
HasConversion EnumToStringConverter unsupported for SubType (Enum) of  owned  Entity

### ISSUE THREAD

**Issue by duhowise** [dotnet/efcore#21156]
EF Core does not allow adding migrations for owned entities with enum sub-types that have value converters. The Enum sub-types work just fine for the owned types, the problem however occurs when say an EnumToStringConverter is applied to the Enum. The error returned is:
`System.InvalidOperationException: The property 'Driver.Vehicle#Vehicle.Type' is of type 'VehicleType' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

### Steps to reproduce
```C#
public class Driver : Entity
{
 public string Name { get; set; }
 public Vehicle Vehicle { get; set; }
}

public class Vehicle
{
 public string Model { get; set; }
 public string LicensePlate { get; set; }
 public DateTime ModelYear { get; set; }
 public string ModelName { get; set; }
 public VehicleType Type { get; set; }
}

public enum VehicleType
{
 Car,
 PickupTruck,
 Taxi,
 Tricycle,
 Truck,
 Motorcycle
}
public class DriverDbContext : DbContext
{
  public DbSet<Driver> Drivers { get; set; }
  public DriverDbContext(DbContextOptions<DriverDbContext> options): base(options)
  {
  }


  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    modelBuilder.Entity<Driver>().OwnsOne(x => x.Vehicle).Property(x => x.Type).HasConversion<EnumToStringConverter<VehicleType>>();
    base.OnModelCreating(modelBuilder);
  }      
}
```

### Further technical details

EF Core version:3.1.3
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.1

**Comment by smitpatel** [comment]
`modelBuilder.Entity<Driver>().OwnsOne(x => x.Vehicle).Property(x => x.Type).HasConversion<string>();`
does this work?

**Comment by ralmsdeveloper** [comment]
@duhowise 
That way you will be able to perform!

```csharp
modelBuilder
    .Entity<Driver>()
    .OwnsOne(x => x.Vehicle)
    .Property(x => x.Type)
    .HasConversion<string>();

// Or

modelBuilder
    .Entity<Driver>()
    .OwnsOne(x => x.Vehicle)
    .Property(x => x.Type)
    .HasConversion(new EnumToStringConverter<VehicleType>());
```

**Comment by ralmsdeveloper** [comment]
@smitpatel you were faster, i was replying and i didn't see your answer!

**Comment by duhowise** [comment]
```
modelBuilder
    .Entity<Driver>()
    .OwnsOne(x => x.Vehicle)
    .Property(x => x.Type)
    .HasConversion(new EnumToStringConverter<VehicleType>());
```
this right here worked perfectly. 
thank you @smitpatel  and @ralmsdeveloper
