### ISSUE TITLE
API for assigning sequence for a property

### ISSUE THREAD

**Issue by borgdylan** [dotnet/efcore#2116]
~~Currently EF is asking for DefaultSequence in order to generate a new value for Id properties. On databases such as Npgsql it is a convention to have a sequence associated to Id properties. Could there be a way such that such a sequence could be assigned per property in OnModelCreating?~~

Also could there be a standard way to turn off automatic value generation from EF's side to let the database make a new value on its own if T-SQL's identity or PostgreSQL's serial are used in the Table ? This was the default in EF6

**Comment by borgdylan** [comment]
Forget the first paragraph since this is configurable per property in OnModelCreating.

**Comment by cwoolum** [comment]
I'm running into the same problem. I'm deploying to azure which doesn't support sequences and I just want to use an identity column instead. I've tried the combo of `GenerateValueOnAdd(true).StoreComputed(true)`  doesn't seem to make a difference. I'm on Beta4

**Comment by ajcvickers** [comment]
@cwoolum `modelBuilder.ForSqlServer().UseIdentity();`

**Comment by cwoolum** [comment]
Aah, that works. Thanks!
