### ISSUE TITLE
Helpful exception message for method translation failure

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21177]
This would help pinpoint the problematic method (within a potentially large exception), and point users towards our future DbFunction docs. @JeremyLikness, can we get a new fwlink pointing to https://github.com/dotnet/EntityFramework.Docs/issues/500 for now?

Continues work started in #20612

**Comment by JeremyLikness** [comment]
@roji https://go.microsoft.com/fwlink/?linkid=2132413
