### ISSUE TITLE
Filtered includes not working with In Memory DB provider 

### ISSUE THREAD

**Issue by a-keen** [dotnet/efcore#21179]
Using `Microsoft.EntityFrameworkCore.InMemory v5.0.0-preview.4.20220.10`, I am having an issue with the [Filtered Include](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#preview-3) and the In Memory DB provider. 

The following screenshot works when I use a **SQL Server provider** (`Microsoft.EntityFrameworkCore.SqlServer v5.0.0-preview.4.20220.10`), as in the extra WorkOrderDocuments are filtered out properly in line 2.  

However, when using  an **In Memory DB provider**, it does not filter out the extra WorkOrderDocuments and therefore throws a `System.InvalidOperationException : Sequence contains more than one element` because there is not a "Single" WorkOrderDocument in the list of WorkOrderDocuments on the workOrder entity.  The exception is thrown in the last line when trying to call `SingleOrDefault()`  

![image (4)](https://user-images.githubusercontent.com/42074885/84072858-dc58fb00-a99d-11ea-9a02-ea03bbde3146.png)

**Comment by smitpatel** [comment]
@a-keen - Please share a small runnable code which demonstrate the issue you are seeing. My suspicion is that entities are already tracked when running the query for InMemory hence the result does not correspond to the filtered include. That is always going to be case for filtered include.

**Comment by smitpatel** [comment]
Use different context instances for seeding the database and querying the database, like how it would be in actual business code.
