### ISSUE TITLE
Combining ToView and ToTable

### ISSUE THREAD

**Issue by bdebaere** [dotnet/efcore#21172]
Would it be possible to consider the following feature: I'm trying to use a view for SELECT operations and a table for DELETE, INSERT, and UPDATE operations.

I used to have a custom EntityFrameworkCore version for this, but with 3.x came the return of the ToView method, and the solution to my problem I thought. I'd like to configure both ToView and ToTable for a given model, and have EntityFrameworkCore automatically pick the view for SELECT operations and the table for DELETE, INSERT, and UPDATE operations.

I'd be willing to write this extension myself, but before I begin work I'd like to know if this would be accepted.

**Comment by ajcvickers** [comment]
@bdebaere This should already work in the EF Core 5.0 preview. Can you try it and let us know if you run into issues.

**Comment by bdebaere** [comment]
@ajcvickers I can confirm that this works for 5.0.0-preview.4.20220.10, but does not work for 3.1.4.
