### ISSUE TITLE
Outdated dependency on SqlClient package

### ISSUE THREAD

**Issue by arjanvanbekkum** [dotnet/efcore#21184]
There is a bug in the Mircosoft.Data.SqlClient package version 1.0.19x, if you use async queries in a container on .NET Core 3.1, it random creates locks on the database. This bug is fixed in version 1.1.1 of the Mircosoft.Data.SqlClient package.

Please update the minimum version of this dependency to 1.1.1. instead of 1.0.19x

for more information please read: 
  https://arjanvanbekkum.github.io/blog/2020/06/08/Process-End-NET-Core-EF-Core

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win10, Linux Containers
IDE: Visual Studio 2019 16.5.4

**Comment by roji** [comment]
@arjanvanbekkum we don't update dependency versions to new minor/major versions in EF Core patch versions - in the 5.0 the SqlClient version has already been updated.

However, there's nothing preventing you from taking a dependency on a newer version of SqlClient yourself, in your own project.

**Comment by arjanvanbekkum** [comment]
We already updated our project to use a newer version of the SqlClient. This bug has the potential to completely stop your software from working correctly , it took us a few days to figure out what was wrong. 

If you could update the dependency on the EF package to use 1.1.1 you can prevent this bug appearing in other projects as well. 

When using Visual Studio you are not actively triggered for updates on dependency packages so you manually figure out which package needs an update.
I know Visual Studio is not your problem, but in this case you can prevent this bug and save a lot of time and money for teams running in to this issue.

**Comment by ajcvickers** [comment]
See #20377. We have been holding off on this, but the plan is still to update once we're confidence that the package we update to is fully stable.

**Comment by arjanvanbekkum** [comment]
Thanks @ajcvickers. We are already running with version 1.1.1 of the sql client, no problems so far.

**Comment by ajcvickers** [comment]
PR: https://github.com/dotnet/efcore/pull/20377
