### ISSUE TITLE
NullPointerException when using cached model

### ISSUE THREAD

**Issue by KaNarlist** [dotnet/efcore#21191]
I'm currently in the process of upgrading my project form EF Core Version 2.2.6 to 3.1.4 because of the new Oracle Provider suporting this version and I'm getting a NullPointerException when using a cached model.
The project is used from an WCF Service application which had some performance issues when the model had to be created with every service call.

To cache the model I added the following line at the end of OnModelCreating after every configuration was applied:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.ApplyConfiguration(...);
	modelBuilder.ApplyConfiguration(...);
	...
	ModelCache.Instance.Model = modelBuilder.FinalizeModel();
}
```

ModelCache is a simple singleton that holds an IModel instance. In OnConfiguring I apply the model if it is set:
```
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
 {
     if (ModelCache.Instance.Model != null)
           optionsBuilder.UseModel(ModelCache.Instance.Model);
       base.OnConfiguring(optionsBuilder);
 }
```

This way I saved several hundred milliseconds on each WCF service call.

After upgrading to EF Core 3.1.4 I get a NullPointerException in the first method that tries to access the database. For example context.Database.ExecuteSqlRaw(...) in a test method.

Through debugging the EF code I found out that the NPE occurs here:
```

        public virtual IModel FinalizeModel()
        {
            var finalModel = (Model)ConventionDispatcher.OnModelFinalized(Builder)?.Metadata;
            return finalModel?.MakeReadonly() ?? this;
        }

```
because ConventionDispatcher is null.

If I remove the caching everything seems to work, but I guess I will have the performance issues again. Unfortunately it looks like the creation of the model is no longer traced out, so I can't see how long it takes in the logs anymore.

### Steps to reproduce
Save the model in OnModelCreating and load it in OnConfiguring.

Got Exceptions? Include both the message and the stack trace

Exception thrown: 'System.NullReferenceException' in Microsoft.EntityFrameworkCore.dll
Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel() in C:\Users\xxx\Downloads\efcore-3.1.4\efcore-3.1.4\src\EFCore\Metadata\Internal\Model.cs:line 829

### Further technical details

EF Core version: 3.1.4
Database provider: Oracle.EntityFrameworkCore 3.19.0-beta1
Target framework: .Net Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.5

**Comment by roji** [comment]
@KaNarlist EF Core already caches the model internally - you definitely should not be needing to do this. If this saves you hundreds of milliseconds for each call, chances are that you may be doing something wrong... Can you please post a minimal code sample which produces these long delays?

**Comment by KaNarlist** [comment]
Hmm did it also cache the model in Version 2.2.6 or is this a new feature?

I can definately see performance improvements with the new version but I assumed them coming mainly from EF using joins now to load related entities instead of multiple queries. I fear a minimal code sample would be quite large, because of the WCF Client/Server architecture and multiple tiers.

I probably could provide a trace log with the older version where you can see the context and model creation, if that helps you.

Is there a way to configure EF Core 3.1 to log out the same information when the log level is set to Trace to compare them? Because so far I get far less information than before.

**Comment by roji** [comment]
> Hmm did it also cache the model in Version 2.2.6 or is this a new feature?

EF Core has always cached the model. There have been lots of changes since 2.2.6 which could affect perf, but nothing related to model caching AFAIK.

> I fear a minimal code sample would be quite large, because of the WCF Client/Server architecture and multiple tiers.

Try isolating your model and EF Core operation from your actual WCF architecture. Logic executing the same EF Core query should exhibit the same behavior (slowdown/speedup) regardless of whether it's executed from within a WCF application or a simple console program. I suggest trying this because it's likely that any perf issue you're seeing isn't necessarily related to model caching etc.

> I probably could provide a trace log with the older version where you can see the context and model creation, if that helps you.

I'm afraid an old trace log wouldn't really provide much information - even a new one is hard to analyze without a code sample which produces it.

> Is there a way to configure EF Core 3.1 to log out the same information when the log level is set to Trace to compare them? Because so far I get far less information than before.

Although things have indeed changed between EF Core 2.2 and 3.1, both output trace information that should be relatively comparable - I'm not aware of anything specific that has been removed.

**Comment by ajcvickers** [comment]
@KaNarlist It should be pretty easy to determine if EF model caching is working since OnModelCreating is called once per model. A typical application should only run OnModelCreating once. (There are reasons it can be called more than once, but they are atypical.)

**Comment by KaNarlist** [comment]
> 
> 
> @KaNarlist It should be pretty easy to determine if EF model caching is working since OnModelCreating is called once per model. A typical application should only run OnModelCreating once. (There are reasons it can be called more than once, but they are atypical.)

Good idea, I just checked it with both versions. Without my caching mechanism from above OnModelCreating is called every time the context is created with the older version. Now with the new version it is only called once. So I don't know why the caching wasn't working before but it looks like it is working now.
