### ISSUE TITLE
DbContext.Add() and DbContext.SaveChanges() methods

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#21205]
I have simple database table which has "serial" (auto increment) and "string" columns. I want to insert 1 record into this table. Out of the two columns I want to give value to only "string" column, since "serial" column will generate auto value (starting from value 1 or increment by 1). However when I try to use the below sample code, it reports error, "System.InvalidOperationException: 'The property 'StudentId' on entity type 'Student' has a temporary value while attempting to change the entity's state to 'Unchanged'."

Question: How do I tell the EF Core that only insert the single column i.e. "string" from the table and database will take care of first column (i.e. "serial", which is treated as implicit PK)?

Any help is very much appreciated.

```c#
public class Student
        {
            public int StudentId { get; set; }
            public string Name { get; set; }
        }

 public DbSet<Student> Students { get; set; }

                var std = new Student()
                {
                    //StudentId = 10, // This works though.
                    Name = "Bill"
                };

                schoolContext.Students.Add(std);
                schoolContext.SaveChanges();
```

I referred https://github.com/dotnet/efcore/issues/3619 ticket, which doesn't really solve my problem!

**Comment by roji** [comment]
@deokershesh can you please post your DbContext class, and preferably a runnable code sample?

**Comment by deokershesh** [comment]
@roji, Kindly find the running code below. Here I am using Informix database "UseInformix()" and table created is "create table students(studentid SERIAL, name CHAR(30))". When I provide values for both StudentID and Name fields then it works (I had to change code internally for Informix to generate the appropriate SQL query for INSERT). 

using Microsoft.EntityFrameworkCore;
using System;
using static EFCoreSql.SchoolContext;

namespace EFCoreSql
{
    class SchoolContext : DbContext
    {
        public SchoolContext() : base()
        {
            Console.WriteLine("In SchoolContext");
        }

        public class Student
        {
            public int StudentId { get; set; }
            public string Name { get; set; }
        }

        public class Course
        {
            public int CourseId { get; set; }
            public string CourseName { get; set; }
        }

        public DbSet<Student> Students { get; set; }
        public DbSet<Course> Courses { get; set; }
		
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInformix("Database=sheshdb; server=lo_informix1410;UID=informix; PWD=xxxx");
        }

    }
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("In Main");
            using (var schoolContext = new SchoolContext())
            {
                // Don't use lazy loading here.
                schoolContext.ChangeTracker.LazyLoadingEnabled = false;

                bool _canCo = schoolContext.Database.CanConnect(); if (_canCo == true)
                    Console.WriteLine("Informix database is good");
                else
                    Console.WriteLine("Not able to connect to Informix database!!");

                bool _Created = schoolContext.Database.EnsureCreated();
                if (_Created == false)
                    Console.WriteLine("Database exist in the Informix");
                else
                    Console.WriteLine("Database not exist in the Informix!!");

                var std = new Student()
                {
                    //StudentId = 10, // If I provide this value also, then it works.
                    Name = "Bill"
                };

                schoolContext.Students.Add(std);
                schoolContext.SaveChanges();
                Console.WriteLine("SaveChanges method inserted record successfully");
            }
        }
    }
}

**Comment by roji** [comment]
That code is indeed standard EF Core code and works across all the provider I know - see the code sample below. Which Informix provider are you using? It's likely that the problem is there.

<details>
<summary>Working code sample</summary>

```c#
class Program
{
    static async Task Main(string[] args)
    {
        await using var ctx = new SchoolContext();
        await ctx.Database.EnsureDeletedAsync();
        await ctx.Database.EnsureCreatedAsync();

        var std = new Student()
        {
            //StudentId = 10, // If I provide this value also, then it works.
            Name = "Bill"
        };

        ctx.Students.Add(std);
        await ctx.SaveChangesAsync();
        Console.WriteLine("SaveChanges method inserted record successfully");
    }
}

public class SchoolContext : DbContext
{
    public DbSet<Student> Students { get; set; }
    public DbSet<Course> Courses { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            // .UseSqlite("Filename=/tmp/foo.sqlite")
            // .UseNpgsql(@"Host=localhost;Username=test;Password=test")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}

public class Student
{
    public int StudentId { get; set; }
    public string Name { get; set; }
}

public class Course
{
    public int CourseId { get; set; }
    public string CourseName { get; set; }
}
```

**Comment by deokershesh** [comment]
Yes, I could see the same working with other databases. However, I can't figure out way to only insert column data except PK column where value is auto generated. I was debugging the code and found following code seems to be causing the issue. By changing from "EntityState.Unchanged" to variable "currentState" seems to resolve my problem. Looking at the IF() condition the changed code seems to be correct but not sure exactly what its trying to do by sending "Unchanged" state while data is actually inserted (before the execution comes this code, the row is already inserted successfully).

The below code is in, ..\efcore-master\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs file.

        public virtual void AcceptChanges()
        {
            if (!_storeGeneratedValues.IsEmpty)
            {
                foreach (var property in EntityType.GetProperties())
                {
                    var storeGeneratedIndex = property.GetStoreGeneratedIndex();
                    if (storeGeneratedIndex != -1
                        && _storeGeneratedValues.TryGetValue(storeGeneratedIndex, out var value))
                    {
                        this[property] = value;
                    }
                }

                _storeGeneratedValues = new SidecarValues();
                _temporaryValues = new SidecarValues();
            }

            var currentState = EntityState;
            if ((currentState == EntityState.Unchanged)
                || (currentState == EntityState.Detached))
            {
                return;
            }

            if ((currentState == EntityState.Added)
                || (currentState == EntityState.Modified))
            {
                _originalValues.AcceptChanges(this);
                SharedIdentityEntry?.AcceptChanges();

                //SetEntityState(EntityState.Unchanged, true); // Shesh, Commented this line and added below line
                SetEntityState(currentState, true);
            }
            else if (currentState == EntityState.Deleted)
            {
                SetEntityState(EntityState.Detached);
            }
        }

**Comment by roji** [comment]
@deokershesh InternalEntityEntry.cs is a core, internal EF Core file and is not connected to any specific provider. As you can see, everything is working well for other providers - just not the Informix one you are using. If you are using a self-developed provider, concentrate on understanding what is missing in your provider compared to the others.

**Comment by MaxG117** [comment]
EF is supposed to treat any *Id column as identity "by convention," but database providers must support the convention. Failing that, there are "built-in" PropertyBuilder extensions and property annotations which allow the application to configure columns as auto-generated or auto-incremented, but the database provider must also support such features: https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties

A database provider could also provide its own PropertyBuilder extensions or property annotations to accomplish the same thing if the built-in ones are insufficient.

**Comment by deokershesh** [comment]
Thanks a lot @MaxG117 , That's the exact info I was looking for. For my database [DatabaseGenerated(DatabaseGeneratedOption.Identity)] is suitable. If I use this property, EF Core doesn't generate its own values.

Thanks once again. This is indeed good piece of info.
