### ISSUE TITLE
ef core created an instance for each element in a one to many relationship with the same foreign key

### ISSUE THREAD

**Issue by dpr-dev** [dotnet/efcore#21208]
Hi. I have a two classes 
```
class Road 
{
    // only for ef
    private Road() { Debug.WriteLine("Road entity created"); }
    public Road(...) {}

    public IReadOnlyList<Statement> Statements {get; private set;}
}

class Statement 
{ 
    // only for ef 
    private Statement() {}
    public Statement(...) {}

    public Road Road {get; private set;}
}
```
This query created many instances for the parent entity (Road) with the same foreign key. as a result, I got a million identical roads (instead of one)

```
List<Statement> items = await _context.Statements
      .AsNoTracking().Include(e => e.Road)
      .Where(e => statements.Contains(e.Id)).ToListAsync(); /
``` 

### Further technical details

Operating system: Windows

Packages:  
```
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.5" /> 
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.2"/> 
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.4" /> 
```

**Comment by smitpatel** [comment]
@dpr-dev - Please provide a runnable repro code.

**Comment by tiesont** [comment]
So, it seems like our two choices are:

1) Leave change tracking enabled --> get expected values in navigation properties
2) Disable change tracking --> get duplicate values in navigation properties.

Is there a way to enforce/approximate the weak references mentioned at the end of the linked doc above? Everything I read says to disable change tracking on read-only queries to help return results faster, but nothing mentions this behavior (granted, most of those articles were for EF Core 2.x).

**Comment by smitpatel** [comment]
@tiesont - Starting with EF Core preview5 new API is added. It is called `PerformIdentityResolution` (beware this will be renamed in preview7 to AsNoTrackingWithIdentityResolution`.
That will use a stand alone state manager to de-dupe results but not track them.

**Comment by tiesont** [comment]
@smitpatel I assume that means that there is no way to mimic that behavior, now?

**Comment by smitpatel** [comment]
The only way to do that now is to initialize new DbContext to run the query and then throw away the context.
