### ISSUE TITLE
The process has no package identity

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#21215]
Using EFCore with SQLITE now causes the error:
System.InvalidOperationException: 'The process has no package identity. (Exception from HRESULT: 0x80073D54)'

From the following module:
Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.LoadAppData

It looks like it is using reflection to do some calls.  Can this be updated to not throw?

**Comment by ajcvickers** [comment]
@TonyValenti Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by NatPerat** [comment]
I have the same problem. Just updated Microsoft.EntityFrameworkCore.Sqlite to 3.1.5
Here's a little reproduction 
[ConsoleApp1.zip](https://github.com/dotnet/efcore/files/4771213/ConsoleApp1.zip)

**Comment by ajcvickers** [comment]
@TonyValenti @NatPerat I ran the project on two machines (Ubuntu Linux and Windows 10) and it worked fine in both places. Which operating system/version are you on where this is failing?

**Comment by TonyValenti** [comment]
@ajcvickers - The exception is an internal one that is swallowed by the code.  In VS, tell it to break on every exception and you'll see it happen.

**Comment by ajcvickers** [comment]
@TonyValenti I still don't see an exception. However, a handled exception in this case is by-design. Why is this causing issues for you?

**Comment by NatPerat** [comment]
The project seems to be running fine regardless of the exception. But I was worried it might have other implications. The System.InvalidOperationException was not there in the previous versions. So when I searched and found this issue I thought I should dig a little.

I run windows 10 with the latest dotnet core sdk and the .net framework 4.8 alongside.

**Comment by jeroenwalter** [comment]
I have this exact same issue, even disabling all C# exceptions in the exception settings won't help. The program consistently breaks when trying to open a sqlite connection. 
The console app provided earlier as an example also reproduces this problem for me.
I'm running vs2019 16.6.2. 
So as a consequence, each time I run my program in the debugger, I get this exception thrown in my face, then have to press F5 to continue debugging.

**Comment by MaivKhanhPr0** [comment]
[](https://aex.dev.azure.com/me?mkt=en-US&tab=edit)

**Comment by knilecrack** [comment]
I have same issue as @jeroenwalter, it runs fine .net core, but for .net 4.8, same exception.

**Comment by jeroenwalter** [comment]
I got rid of this exception after enabling the "Enable Just my code" option in the debugging options....

![image](https://user-images.githubusercontent.com/1812838/92640115-17d8cd80-f2dd-11ea-8604-a44042d3c082.png)

**Comment by jmevel** [comment]
Why had this issue been closed? Is this really by design to throw an exception?
I don't even know what is wrong in my code and why I get this exception...

@jeroenwalter's answer isn't a solution, it's a workaround.
By enabling `Just my code` we can't use SourceLink anymore!

**Comment by kg** [comment]
This exception being InvalidOperationException is also especially bad because it means if you filter IOEs from the SQLite assembly, any ones of actual significance will be silenced. That's undesirable, it should at least be a more specific exception type.

**Comment by Bosch-Eli-Black** [comment]
Linking to the relevant code, in case it's helpful for someone: https://github.com/dotnet/efcore/blob/8144d50ec0d15b87c35a9a3a425b1faadafb87f1/src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs#L30
