### ISSUE TITLE
Throw a better exception message when Reverse cannot be translated

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#21217]

**Comment by KaloyanIT** [comment]
I'm interested in contributing. Is the issue still available and if it is, could you provide more description? Thank you!

**Comment by smitpatel** [comment]
https://github.com/dotnet/efcore/blob/2a3ff067749f80de9d3054883a8deec6acfe782d/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs#L902
https://github.com/dotnet/efcore/blob/e9fae4a1328e64fb76cd01c1a186c93d525d748d/src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs#L753

Above lines while returning null value should call AddTranslationErrorDetails with appropriate error message which indicates that reverse could not be translated to server because there is no ordering on server side.
Exception messages should be added in RelationalStrings.resx & CosmosStrings.resx file and generated using TT4 templates.

There would be few tests which would be verify exception. Update them to verify the error message. One way to find those tests would be to throw `InvalidFilterCriteriaException` rather than returning null and those test would show up as fail.
