### ISSUE TITLE
A host error has occurred during startup operation  (5.0.0-preview.4.20220.10 and 5.0.0-preview.5.20278.2)

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#21216]
Entity framework throws the following errors when used in Azure Functions after upgrading from 5.0.0-preview.3.20181.2.

Running locally with Azure Functions Core Tools, but the same issues exist on Azure.
(https://github.com/Azure/azure-functions-core-tools)

A host error has occurred during startup operation '28db500b-7bbd-4b51-8b06-0c9c4e6adaf2'.
System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

And afer adding  builder.Services.AddLogging(); 

A host error has occurred during startup operation '569550f2-9eea-49af-9a74-4204925bbd69'.
FunctionApp1: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

### Steps to reproduce

I've a include a minimal setup in which this reproduces when switching between preview 3 4 and 5.

[FunctionApp1.zip](https://github.com/dotnet/efcore/files/4760844/FunctionApp1.zip)

Upgrade EF to preview 5.

### Further technical details

EF Core version: 5.0.0-preview.5.20278.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10 - 1909
IDE: (e.g. Visual Studio 2019 16.6.2)

**Comment by ajcvickers** [comment]
@qsdfplkj Have you reported this to Azure Functions? It's been my experience that using new versions of EF Core in Azure Functions requires support on their side, and I expect this hasn't yet been done for 5.0.

**Comment by qsdfplkj** [comment]
https://github.com/Azure/azure-webjobs-sdk/issues/2515

**Comment by dengere** [comment]
@ajcvickers its not related with EF, i tested any other version EF Cor 3.1.3 , 3.1.2 3.1 and 3.1.0, 3.0.0 same error has occurred.
I think that issued by Azure Functions dependency injection could not find ILogger implementation.  
https://github.com/Azure/azure-functions-host/issues/4577#issuecomment-618499724 issue wait more than ıne year...

**Comment by dengere** [comment]
May be it can help to fix issue; EF Core 2.0.1 working properly.

**Comment by qsdfplkj** [comment]
@dengere  I double checked your claim. But on all the version you mentioned it only reproduces on preview 4 and 5 using the solution I added in the report. I also think the the root cause seems to be outside EF Core in one of it's direct or indirect dependencies on Logging or DependencyInjection since EF Core started using a 5.0.0-preview releases internally on preview 4.
