### ISSUE TITLE
Remove allocation from ConcurrencyDetector critical section management 

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21229]
For every entity we read [in QueryingEnumerable](https://github.com/dotnet/efcore/blob/6242987ed5c66e25dcac78281059b54dae3e33f1/src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs#L136), we incur a heap allocation because EnterCriticalSection returns an IDisposable. Returning the struct directly would avoid that.

This would probably mean making ConcurrencyDetector an internal implementation detail of QueryingEnumerable, and not a replaceable service.

**Comment by smitpatel** [comment]
ConcurrencyDetector is also used in SaveChanges and ExecuteSqlRaw* methods. It is not an internal implementation detail of QueryingEnumerable.

**Comment by roji** [comment]
I've looked again, and it's probably possible to fix this even without big changes. If IConcurrencyDetector exposed ExitCriticalSection publicly, and EnterCriticalSection returns a public disposer type, that type could just reference its IConcurrencyDetector and call ExitCriticalSection on it when disposed.

Basically an allocation per row doesn't seem like a good idea, especially if there's no good reason for it...

**Comment by smitpatel** [comment]
Unless I am missing something, what are we exactly allocating?

**Comment by roji** [comment]
ConcurrencyDetector.Disposer is a readonly struct, which is great - but it gets boxed when it's returned by EnterCriticalSection as an IDisposable. It's enough to change the return value to the concrete struct type to avoid that boxing. The using statement doesn't box structs if they're passed to it directly, but if they're cast to IDisposable first they get boxed.
