### ISSUE TITLE
DbFunctions invoked without DbContext references are always executed on the client

### ISSUE THREAD

**Issue by MaxG117** [dotnet/efcore#21228]
The DbFunctions that do not have any references to DbContext are now always executing on the client for some reason. No attempt is made to translate them with `IMethodCallTranslator`.

### Steps to reproduce

Consider the following `DbFunctions` extension:

``` C#
        public static Double Degrees(
            [CanBeNull] this DbFunctions _,
            [NotNull] Object value)
            => throw new InvalidOperationException(MyStrings.DBFunctionOnClient)
```

If the application does the following:

``` C#
            var rows = myContext.myTables
                .Where (e => e.Id == 3)
                .Select(r => new
                {
                    deg = EF.Functions.Degrees(r.Id),
```

then `EF.Functions.Degrees` is translated by my `IMethodCallTranslator` into the desired server-side function call. But if the application does this:

``` C#
            var rows = myContext.myTables
                .Where (e => e.Id == 3)
                .Select(r => new
                {
                    deg = EF.Functions.Degrees(2),
```

then no translation is performed and EF tries to execute it locally, resulting in exception. Niladic functions meant to execute on the server also do not work (since they don't have any references to DbContext).

This worked correctly in 2.2, but it's not working in 3.1. Is this a bug in EF or do I need to do something on my end to make it work again?

I do not see this mentioned in [3.0 breaking changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes) as it does not appear to be related to #12757. I also don't think it's related to #9022.

### Further technical details

EF Core version: 3.1.4
Database provider: the one I'm writing

**Comment by smitpatel** [comment]
`EF.Functions.Degrees(2)` is not correlated with server in anyway and it will always be evaluated on client and converted to parameter. That is how parameter extraction works on a query to aid query caching. See https://github.com/dotnet/efcore/issues/13524 & https://github.com/dotnet/efcore/issues/13549

If you want the function to evaluate on client side then you can body for the method.

**Comment by MaxG117** [comment]
> If you want the function to evaluate on client side then you can body for the method.

@smitpatel could you clarify please? I want certain DbFunctions to always evaluate on the server.

**Comment by smitpatel** [comment]
I suggest reading this thread, it capture everything. https://github.com/dotnet/efcore/issues/12527
You can register your function to be not evaluatable on client side by using IExpressionEvaluatbleFilter service.
In our providers, we don't do it. If `EF.Functions.Degrees(2)` is not server correlated then there is very little value in sending it to server rather than using direct value.

**Comment by MaxG117** [comment]
I'm sorry, I introduced a bug while upgrading our `IEvaluatableExpressionFilter` implementation to 3.x and forgot that it was involved in this. Thanks very much!
