### ISSUE TITLE
Sample for SQLite usage on Linux or Mac

### ISSUE THREAD

**Issue by Schr3da** [dotnet/efcore#2122]
Hey,

is there any working example available with ASP.NET vNext and EF7 on Linux or Mac?
I have checked already many resources and even tried to setup it by myself but Im unable to get it to work. An example would be really nice. Im currently writing my bachelor thesis about ASP.NET vNext and its cross platform capabilities. To proof the current state I need to integrate an simple web service with some REST API's. Instead of SQL Server I wanted to use SQLite because it should be available as well.
Any feedback about this topic would be really nice!
Thanks a lot in advice
regards
Schreda

**Comment by bricelam** [comment]
Have you installed the x86 version of libsqlite3? On Ubuntu, the command is:
```bash
apt-get install libsqlite3-0:i386
```

**Comment by Schr3da** [comment]
Hey thanks for you reply. Yes the package is already installed. Today I tried to setup everything on OSX 10.10 to improve my workflow... except the database and the "dun build" bug is working. I used yo to generate a new project (Web Application), dnu restore, dnx . kestrel to run it... but as soon as I'm trying to Register a new User I get an exception: 
```
SocketException: Could not resolve host '(localdb)'
```
So I tried to add SQLite support and tried to adding the 
```
option.UseSQLite('Filename=sample.sqlite;')
``` 
instead of  
```
options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]).
```
but Im even unable to get the intenseness method signature. So Im somehow worry about my project configuration. By the way here is my project.json file:

```json
{
    "webroot": "wwwroot",
    "userSecretsId": "aspnet5-test-aac12b4d-cbe2-4f2d-912a-eaad4f484b99",
    "version": "1.0.0-*",

    "dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta4",
        "EntityFramework.SQLite": "7.0.0-*",
        "EntityFramework.Commands": "7.0.0-beta4",
        "Microsoft.AspNet.Mvc": "6.0.0-beta4",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.UserSecrets": "1.0.0-beta4",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4",
        "Microsoft.Framework.Logging": "1.0.0-beta4",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta4",
        "Kestrel": "1.0.0-beta4",
    },

    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5001",
        "gen": "Microsoft.Framework.CodeGeneration",
        "ef": "EntityFramework.Commands"
    },

    "frameworks": {
        "dnx451": {},
        "dnxcore50": {}
    },

    "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
    "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
    "scripts": {
        "postrestore": ["npm install", "bower install"],
        "prepare": ["grunt default"]
    }
}
```

By the way i tried to follow this tutorial as well but with all the latest libraries.
http://www.dotnetthoughts.net/how-to-use-sqlite-in-asp-net-5/.
Am I missing some additional dependencies? I really don't know why I get not the UseSQLite method.
I already tried to just write the method but server is than not starting anymore ...

Thanks a lot 
regards
Schreda

**Comment by bricelam** [comment]
The first error you're getting is from ASP.NET Identity ([aspnet/Identity](https://github.com/aspnet/Identity)) trying to still use SQL Server. You may want to file an issue on their repo to see what their recommendation is for running on OSX.

For the second error, you'll need to add the `EntityFramework.Sqlite` package to your `project.json` file before the `UseSqlite` method will be available.

**Comment by divega** [comment]
FWIW, ASP.NET Identity product code does not call UseSqlServer(). It will pick up whatever the DbContext is configured with in either Startup.cs or the IdentityDbContext's OnConfiguring() method. 

cc @bricelam

**Comment by Schr3da** [comment]
Thanks a lot for the answers. Im currently using the InMemory Db after I finish all the other tasks I will return to the configuration of the sqlite version.

**Comment by bricelam** [comment]
@natemcmaster was able to get SQLite working on OSX. Closing this issue for now, but please file any new issues you run into when trying to make it work.

**Comment by Schr3da** [comment]
Hey,

Thank you for your help, I made an Sample application based on the Microsofts Mvc Example. 
It contains an SQLite Database and its fully working with beta-6.0.0 bellow is the repository link maybe someone else is searching for it :dancer: 

https://github.com/Schr3da/ASP.net-vnext-samples

**Comment by bricelam** [comment]
:metal: Rock on.

**Comment by natemcmaster** [comment]
Also, we recently added an article to our documentation that uses SQLite on OSX:  http://ef.readthedocs.org/en/latest/getting-started/osx.html
