### ISSUE TITLE
ConnectionString - slash & back-slash support on Linux

### ISSUE THREAD

**Issue by k0st1x** [dotnet/efcore#21222]
new SqliteConnection("Data Source=Data\\\data.db") //  <-- does not work under Linux
vs
new SqliteConnection("Data Source=Data/data.db") // work on both Linux&Windows

plz make '\\' work under the Linux

**Comment by roji** [comment]
Path handling is a detail of the operating system, I don't think it would be appropriate to make backslash work as a separator on Linux. Any reason you can't just use forward-slash which works on both?

**Comment by k0st1x** [comment]
@roji, your question is very complex.
initially for me the dotnet core is very powerful cross-platform runtime.
the System.IO.Path and System.IO.File APIs works well with "\\" under the linux and this feature helps me to port console tools.
even under the development on the .csproj files i'm not thinking about modifying slashes - and this is great.
with that experience i'm getting to port own tool with sqlite db to linux, but get such bad surprise.

**Comment by roji** [comment]
>  the System.IO.Path and System.IO.File APIs works well with "\" under the linux and this feature helps me to port console tools.

That doesn't sound right to me - I'd double-check your tests on this. Backslash is actually a valid character in a filename on Linux, so you can have a file called "a\b" in a directory, right next to a directory "a" containing a file "b".

**Comment by ajcvickers** [comment]
Closing as by-design. Manipulating the connection string passed by the application is not something that EF or the provider should do.
