### ISSUE TITLE
CollectionNavigationProperty by HashSet causes unexpected behaviour

### ISSUE THREAD

**Issue by RamType0** [dotnet/efcore#21221]
When we want to create many-to-many relation ships,We usually create entity to represent it by two separated one-to-many relation ships.
This kind of entity is really value-like,so we need to determine these equality by two navigation properties.
When we map this kind of entities to HashSet,sometimes it added to HashSet before it navigation property has been set.
Because HashSet caches elements hashcode while it added,this causes undefined behaviour.

I think collection navigation property should be mapped at last.

### Further technical details

EF Core version:3.1.5
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET Core 3.1

**Comment by ajcvickers** [comment]
@RamType-0 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by RamType-0** [comment]
> @RamType-0 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Here's runnable project.
https://github.com/RamType-0/RamType0.EntityFrameworkCore.Issues

**Comment by smitpatel** [comment]
Defining a hash set without using referential equality comparer and then using navigation properties in Equals method of an entity type is hardly going to work in EF Core. Navigations may not be loaded always. Consider using properties in Equals implementation.

```C#
  public class A
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; private set; }


        public HashSet<A2B> A2Bs { get; } = new HashSet<A2B>();

    }


        public bool Equals(A2B? other)
        {
            return other != null &&
                   EqualityComparer<A>.Default.Equals(A, other.A) &&
                   EqualityComparer<B>.Default.Equals(B, other.B);
        }
```

**Comment by RamType-0** [comment]
> Consider using properties in Equals implementation.

Because `A2B` is just a reference container,I could n't find out any other Equals implementation.

Note:`A2B.AId` and `A2B.BId` is not always available.

**Comment by smitpatel** [comment]
> Note:A2B.AId and A2B.BId is not always available.

If AId is not available then how come A is available?

**Comment by RamType-0** [comment]
> > Note:A2B.AId and A2B.BId is not always available.
> 
> If AId is not available then how come A is available?

The instance of A or B which has not been added to Database doesn't have Id.

**Comment by ajcvickers** [comment]
@RamType-0 Defining equality and hashing that way makes your types incompatible with .NET collections in general. See my comment here for more details and related guidance: https://github.com/dotnet/efcore/issues/12984#issuecomment-412651778

**Comment by RamType-0** [comment]
> @RamType-0 Defining equality and hashing that way makes your types incompatible with .NET collections in general. See my comment here for more details and related guidance: [#12984 (comment)](https://github.com/dotnet/efcore/issues/12984#issuecomment-412651778)

I never intended to mutate hashcode.

But only EFCore internal does it.

I just want to make many-to-many relation ships like this.
https://docs.microsoft.com/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key
With this case ,we will get exception on `SaveChanges` while we added `PostTag` with same `Post` and `Tag`.
I want to avoid it by disallowing add `PostTag` with same `Post` and `Tag` to `Post.PostTags`.
