### ISSUE TITLE
SQLite segfaults in Alpine 3.12 Docker container 

### ISSUE THREAD

**Issue by bgrainger** [dotnet/efcore#21232]
This bug is similar to https://github.com/dotnet/efcore/issues/14504.

When using the Alpine-3.12-based image (e.g., `mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.12`), SQLite segfaults when it's used.

### To Reproduce

Create a Docker container based on `mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.12`.

Run a `netcoreapp3.1` project (that uses `Microsoft.Data.Sqlite`) with code similar to the following:

```csharp
using var connection = new SqliteConnection("Data Source=local.db");
Console.WriteLine("Opening connection...");
connection.Open();
Console.WriteLine("Opened connection.");
using var command = new SqliteCommand("create table test(data integer);", connection);
command.ExecuteNonQuery();
Console.WriteLine("Created table.");
```

It segfaults when executing the `create table` command. This doesn't happen when using `mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.11`.

A GitHub repo with a Dockerfile that reproduces the problem is: https://github.com/bgrainger/SqliteAlpine

### Additional context

Microsoft.Data.Sqlite version: 3.1.5
Target framework: netcoreapp3.1
Operating system: Alpine 3.12

**Comment by bgrainger** [comment]
Related to Alpine 3.12: https://github.com/dotnet/core/issues/4750

**Comment by ajcvickers** [comment]
@ericsink This looks like an incompatibility between the Alpine docker image and the native SQLite image. Is this something you have seen before?

@rbhanda @richlander Any ideas on this?

**Comment by ericsink** [comment]
I haven't seen anything related to sqlite/alpine in quite a while.

There was an issue with sqlite/alpine quite some time ago, probably over a year, but IIRC, it got resolved without my involvement.

**Comment by bgrainger** [comment]
The previous Alpine/SQLite issue (if it helps with diagnosing this) was https://github.com/dotnet/efcore/issues/14504.

**Comment by ajcvickers** [comment]
Ping @rbhanda @richlander again. Any ideas on how to help here or where to direct this issue?

**Comment by rbhanda** [comment]
@MichaelSimons

**Comment by MichaelSimons** [comment]
@rbhanda - running the scenario it does show `shared/Microsoft.NETCore.App/3.1.5/Microsoft.NETCore.App.deps.json` has not been updated to include the Alpine 3.12 rid.  This looks to have been corrected in https://github.com/dotnet/corefx/pull/42928 and will be part of 3.1.6.  

The open question I have is where the breakdown in process occurred that signed off on Alpine 3.12 support being in place.

cc @dleeapho, @richlander

**Comment by ajcvickers** [comment]
Thanks @MichaelSimons. Closing this as external.
