### ISSUE TITLE
Include siblings syntactic sugar

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2124]
Instead of writing this...

``` C#
db.Posts
    .Include(p => p.Author)
    .Include(p => p.Sponsor);
```

...it might be interesting to enable writing this instead.

``` C#
db.Posts.Include(p => new { p.Author, p.Sponsor });
```

It could also extend to `ThenInclude`.

``` C#
db.Blogs.Include(b => Posts).ThenInclude(p => new { p.Author, p.Sponsor });
```

Note, it would prevent chaining additional `ThenInclude` calls, but I think that's an acceptable limitation of the sugar.

**Comment by rowanmiller** [comment]
Give you can't chain we aren't going to do this.

**Comment by Bluejanis** [comment]
As a suggestion to load other siblings, maybe you could create another method like `.AlsoInclude()` to include on the same level as the last `.ThenInclude()`.
