### ISSUE TITLE
one to many relationship not created 

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/efcore#21250]
hi, hope all are keeping well. im developing a web application using ef core 3.1 and came across a problem

i create a database table as Profile. then did the migration and updated the database. sometimes later the client said the user must have addresses. so i added a table as addresses. since im not directly querying from the addresses table i did not add it as a Dbset. i added the ICollection of address in the profile table and a profile proeperty in the Address table
then i did the migration. i did not see any foreign key relationships, the up and down methods were empty.

i coudnlt figure it out for a long time. then i deleted the db and the migrations folder and added migration fresh. then i got the foreign key to the the Addresses table. can you please shed some light on why it did not create the foreign  key in the address when i added the Address table later?

**Comment by roji** [comment]
@tnlthanzeel it's quite hard to know exactly what's happening from a textual description - if you could post a quick code sample (including the context and entity), where you're adding a property and the migration generated comes out empty, we can investigate that.

**Comment by tnlthanzeel** [comment]
i aaded ICcollection<Address> property to the Profile entity class 
![image](https://user-images.githubusercontent.com/18216790/84613219-6ba36880-aee0-11ea-86cc-dea1f6816a76.png)


theeni added the Profile's Primary key as foreign key in the Address entity
![image](https://user-images.githubusercontent.com/18216790/84613347-adccaa00-aee0-11ea-9136-2e28affd4f0c.png)

since im not will not query from the Address table directly i did not add the Address as a DbSet in the dbcontext class.

i did the migration but the migration did not give e the foreign key in the Address entity. then i deleted the entire migration folder and did a fresh migration, this time i got the foreign key in the Address table.

**Comment by tnlthanzeel** [comment]
sorry, closed by mistake

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by tnlthanzeel** [comment]
i cannot recreate the issue. but im sure I  did not make any mistake first time. since cannot recreate im closing this. thanks for the time spared ion this: :)
