### ISSUE TITLE
EF Core SQL Max Pool issue when using (Hosted) Background Service

### ISSUE THREAD

**Issue by azampagl** [dotnet/efcore#21270]
My team and I have been experiencing some EF Core / SQL pooling issues on a high utilization .NET Core Web App.

```Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.```

The issue started occurring when EF Core / ApplicationDbContext was being referenced in a Background task on a hosted service (QueuedHostedService). Following the guide at:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio

I've followed the recommended dependency injection and hosted service guides.

### Steps to reproduce

I wasn't planning on attaching an entire project, but if you need it just let me know. The relevant lines:

#### Startup.cs
```C#

...
services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

...

services.AddScoped<IScopedWorker, ScopedWorker>();
services.AddSingleton<MySingletonThatAddsToBackground>();
// Follow the host service guide from microsoft.
services.AddHostedService<QueuedHostedService>();
services.AddSingleton<IBackgroundTaskQueue, BackgroundTaskQueue>();

```

#### MySingletonThatAddsToBackground.cs
```C#
public class MySingletonThatAddsToBackground
{
    private readonly IBackgroundTaskQueue _taskQueue;
    private readonly ILogger _logger;
    private readonly CancellationToken _cancellationToken;
    public IServiceProvider _services { get; }

    public MySingletonThatAddsToBackground(IServiceProvider services, IBackgroundTaskQueue taskQueue,
        ILogger<MonitorLoop> logger,
        IHostApplicationLifetime applicationLifetime)
    {
        _services = services;
        _taskQueue = taskQueue;
        _logger = logger;
        _cancellationToken = applicationLifetime.ApplicationStopping;
    }

    public void DoWorkBackground()
    {
        // Enqueue a background work item
        _taskQueue.QueueBackgroundWorkItem(async token =>
        {
            try
            {
                using (var scope = _services.CreateScope())
                {
                    var scopedWorker = scope.ServiceProvider.GetRequiredService<IScopedWorker>();

                    await scopedWorker.DoWork();
                }
            }
            catch (OperationCanceledException)
            {
                // Prevent throwing if the Delay is cancelled
            }
        });
    }
}
```

#### ScopedWorker.cs
```C#
public class ScopedWorker : IScopedWorker
{
    private readonly ApplicationDbContext _db;

    public ScopedWorker(ApplicationDbContext db)
    {
        _db = db;
    }

    public void DoWork()
    {
        var customers = _db.MyCustomers.ToListAsync();
        
        // Do stuff to customers.

        await _db.SaveChangesAsync();
    }
}
```

### Discussion

Inside MySingletonThatAddsToBackground, after the ```using (var scope)``` is completed, shouldn't the scope be disposed, which then disposes ```ScopedWorker``` (scoped), which then disposes the ```ApplicationDbConext``` (scoped), and then closes the connection / pool connection?

Is there something I'm not implementing properly to cause the connection pool leak?

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.4
Operating system: Windows Server 2016, SQL Server 2016
IDE: 16.6

**Comment by ajcvickers** [comment]
@azampagl How are you coming to the conclusion that this is a connection pool leak as opposed to exhaustion of the connection pool?

**Comment by azampagl** [comment]
@ajcvickers Thanks for the prompt response! I apologize if my inquiry made it sound like it's conclusively a connection pool leak - I can't rule out the pool exhaustion scenario yet. We've only noticed this starting to occur when using the queued background processes.

Unfortunately testing with the background process has been non-trivial on our production environment (Max Pool Size = 1000). I've been using a combo of sp_who to monitor open SQL connections / compare it to incoming requests. From the logs, we haven't seen a burst anywhere near making it have 1000 open SQL connections at one time, so we've started to wonder if we implemented something wrong in EF core that isn't releasing the connections properly after each request (scoped ApplicationDbContext).

Do you notice anything that stands out with the code that would not properly dispose of the ApplicationDbContext and hold on to the connection? Would it be better to force close instead of letting the GC dispose and then release the connection?

E.g.
```
using (var scope = _services.CreateScope())
{
   var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
   var scopedWorker = scope.ServiceProvider.GetRequiredService<IScopedWorker>();
   await scopedWorker.DoWork();
   await db.Database.CloseConnectionAsync();
}
```

**Comment by ajcvickers** [comment]
@azampagl 

> Would it be better to force close instead of letting the GC dispose and then release the connection?

Yes, you should always make sure things are disposed ASAP. However, in your original code:

```C#
using (var scope = _services.CreateScope())
{
    var scopedWorker = scope.ServiceProvider.GetRequiredService<IScopedWorker>();

   await scopedWorker.DoWork();
}
```
the service scope is explicitly disposed and hence all the scoped services will also be disposed. On the other hand, the code in your last comment is wrong because it never disposes the scope and hence none of the scoped services will be disposed.

More generally, I don't see anything obvious in your original post that would cause a leak. However, it's hard to know without knowing the architecture of the application and specifically how all the services interact.

**Comment by azampagl** [comment]
@ajcvickers Thanks!

In regards to "the code in your last comment is wrong because it never disposes the scope and hence none of the scoped services will be disposed."

How so? It's inside the ```using``` from the same scope. The only additional code was to get the db (which is in the same scope) and to force close the connection before the scope is disposed.

**Comment by ajcvickers** [comment]
@azampagl Yes, you are correct. I some how missed the `using`. Doh! 🤷

**Comment by JakeLokkesmoe** [comment]
@azampagl Did you ever figure out what was causing the pool exhaustion? I'm experiencing what seems to be a very similar issue.

**Comment by xrkolovos** [comment]
I'm also experiencing a similar issue. Any directions will be appreciated.

**Comment by azampagl** [comment]
We ended up upgrading to .NET Core 5 and the issues were no longer there.

**Comment by yeganehaym** [comment]
i have the same problem
i have some calculations and i need sql data inside it
so i use Parallel way
```
Parallel.ForEach(personIds,new ParallelOptions()
                        {
                            MaxDegreeOfParallelism = 8
                        },async personId =>
                            {
                                using (var scope = _serviceScopeFactory.CreateScope())
                                {
                                              var uow = scope.ServiceProvider.GetRequiredService<IUnitOfWork>();
                                             //do job here
                                }
                             }

```

i get connections list from sql server query and takes 100 connectons immediately and if i set max pool size connection to 200
takes them too and decrease the speed of doing job

**Comment by yeganehaym** [comment]
im using .net 6

**Comment by ajcvickers** [comment]
@yeganehaym It seems very likely that the connection pool is being exhausted. Creating multiple threads like this is almost always going to be very inefficient and resource intensive and so is not recommended. Beyond this, connection pooling is handed by [SqlClient](https://github.com/dotnet/SqlClient), not EF Core. Nevertheless, if you believe there is a bug in EF Core, then open a _new_ issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by yeganehaym** [comment]
it was my fault
i run async methods on Foreach so i changed it to ForeachAsync and now i have my connections under control

**Comment by Fasih-Khan-320** [comment]
I'm encountering the same exceptions when updating a record.
The system is multi-tenant, and I'm configuring the database connection at runtime using DbContext.OnConfiguring().
These SQL connection pool exceptions typically occur when around 1000 or more concurrent requests hit the system.
I've implemented caching for GET queries, but the issue arises during updates where the process gets stuck.

I've also go through `PoolDbContext` which won't help me out as i'm generating connection on runtime when request landing to my system.

**ServiceCollection.cs**
```
services.AddScoped<TenantDbContext>();
services.AddScoped<DbContextOptions<TenantDbContext>>((serviceProvider) =>
{
    return new DbContextOptionsBuilder<TenantDbContext>()
        .UseSqlServer("xyz", x => x.MigrationsAssembly("xyz"))
        .Options;
});
services.AddUnitOfWork<TenantDbContext>();
```

**TenantDbContext.cs**
```
public class TenantDbContext: DbContextBase<TenantDbContext>
{
    public TenantDbContext(DbContextOptions<TenantDbContext> options,
        ConnectionInformation dbConn)
        : base(options, dbConn)
    {
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
    }
}
```
