### ISSUE TITLE
Generating rollbackscript between test & prod db

### ISSUE THREAD

**Issue by killjoy2013** [dotnet/efcore#21288]
In our Jenkins pipeline, we genarate an idempotent sql script file and let the pipeline apply it on prod db very easily.
However, we need to create a rollback script file in order to be able to rollback to pevious release. 
We can of course create a rollback file with below cli command;

`dotnet ef migrations script 20190725054716_Newer_migration 20190829031257_Older_migration `

Since Jenkins don't know anything about the migration names, things get complicated. 

My suggestion is to add optional **source_db_conn_sting** and **target_db_conn_sting** parameters. So, we can use our cli command as follows;

  `dotnet ef migrations script  test_db_conn_sting prod_db_conn_sting`

Here **test_db** is the source and **prod_db** is the target. We can decide a rollback or migration script file.  So, it's obvious that we need to generate a rollback script file.  If we change the order of the databases, we can just generate a relevant sql script.

If this is to be accepted, love to work on it :)

**Comment by bricelam** [comment]
It should be possible to do this after #577 (PR #14122):

``` ps1
$testMigration = Get-Migration -ConnectionString $testConnectionString |
    where applied |
    select -Last 1 -ExpandProperty id
$prodMigration = Get-Migration -ConnectionString $prodConnectionString |
    where applied |
    select -Last 1 -ExpandProperty id
Script-Migration $testMigration $prodMigration
```

**Comment by ajcvickers** [comment]
Closing as we believe the use of Get-Migration shown above is a reasonable way to do this.
