### ISSUE TITLE
IsConcurrencyToken() with TPH generating incorrect migration statements?

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#21316]
When properties of concrete classes in a hierarchy are set as a concurrency token with `IsConcurrencyToken()`, the migrations alter the column to be not nullable. This should be relaxed so that we can have TPH with nullable columns while also using `IsConcurrencyToken()`

Models:
```c#
 public abstract class BaseClass
    {
        public string Id { get; private set; }
    }

    public class ConcreteA : BaseClass
    {
        public ConcreteATypes ATypes { get; private set; }
    }

    public enum ConcreteATypes
    {
        A1, A2, A3,

    }

    public enum ConcreteBTypes
    {
        B1, B2

    }


    public class ConcreteB : BaseClass
    {
        public ConcreteBTypes BTypes { get; private set; }
    }
```
ApplicationDbContext.cs
```c#
  static ApplicationDbContext()
        {
            NpgsqlConnection.GlobalTypeMapper.MapEnum<ConcreteATypes>();
            NpgsqlConnection.GlobalTypeMapper.MapEnum<ConcreteBTypes>();

        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.HasPostgresEnum<ConcreteATypes>();
            builder.HasPostgresEnum<ConcreteBTypes>();
            builder.Entity<ConcreteA>().HasBaseType<BaseClass>();
            builder.Entity<ConcreteB>().HasBaseType<BaseClass>();
            builder.Entity<ConcreteB>().Property(p => p.BTypes).IsConcurrencyToken();
            builder.Entity<ConcreteA>().Property(p => p.ATypes).IsConcurrencyToken();
            base.OnModelCreating(builder);
}
```

Generates:

```c#
public partial class base1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:Enum:concrete_a_types", "a1,a2,a3")
                .Annotation("Npgsql:Enum:concrete_b_types", "b1,b2");

            migrationBuilder.CreateTable(
                name: "BaseClass",
                columns: table => new
                {
                    Id = table.Column<string>(type: "text", nullable: false),
                    Discriminator = table.Column<string>(type: "text", nullable: false),
                    ATypes = table.Column<ConcreteATypes>(type: "concrete_a_types", nullable: false), //should be nullable for TPH
                    BTypes = table.Column<ConcreteBTypes>(type: "concrete_b_types", nullable: false) //should be nullable for TPH
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BaseClass", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BaseClass");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:Enum:concrete_a_types", "a1,a2,a3")
                .OldAnnotation("Npgsql:Enum:concrete_b_types", "b1,b2");
        }
    }
```
### Further technical details

EF Core version: 5.0.0-preview.7.20317.4
Database provider: npgsql 5.0.0-preview6-ci.20200617T130728
Target framework: .NET 5 nightly (preview 7)
Operating system: Win 10
IDE: VS 2019 16 preview 2

**Comment by AndriySvyryd** [comment]
@vflame  For the columns to be nullable you need to declare the properties as nullable:
```
    public class ConcreteA : BaseClass
    {
        public ConcreteATypes? ATypes { get; private set; }
    }
    public class ConcreteB : BaseClass
    {
        public ConcreteBTypes? BTypes { get; private set; }
    }
```

**Comment by vflame** [comment]
> @vflame For the columns to be nullable you need to declare the properties as nullable:
> 
> ```cs
>     public class ConcreteA : BaseClass
>     {
>         public ConcreteATypes? ATypes { get; private set; }
>     }
>     public class ConcreteB : BaseClass
>     {
>         public ConcreteBTypes? BTypes { get; private set; }
>     }
> ```

Is there a reason why this is only enforced when `IsConcurrencyToken()` is configured? This seems like a regression/change in behavior. It doesn't make sense in our domain to have the enum's as nullables.

**Comment by AndriySvyryd** [comment]
@vflame Yes, this is a regression

@lajones We shouldn't create concurrency token properties on the base type if there's no table sharing

**Comment by lajones** [comment]
@AndriySvyryd Can we be more precise on "no table sharing"? Though `BaseClass` is abstract it looks to me like both `ConcreteA` and `ConcreteB` do share the table "BaseClass"?

Do you mean "We shouldn't create a concurrency token property on the base type if the concurrency tokens are not shared, i.e. will be stored in separate columns?"

**Comment by AndriySvyryd** [comment]
@lajones Table sharing means that a single row is mapped to more than one entity type. Just using TPH doesn't cause this.

**Comment by lajones** [comment]
OK. So really it's the row that they're sharing in a "table sharing" scenario. Your comment makes sense to me now.

**Comment by AndriySvyryd** [comment]
Yes, "row-sharing" is more accurate, but we decided to use EF6 terminology
