### ISSUE TITLE
Foreign Key error when inserting value 0

### ISSUE THREAD

**Issue by jose-cousino** [dotnet/efcore#21310]
I have two related entities between them (master - detail). The primary key of the master entity is of the smallint type. The primary key of the detail entity is of the integer type. The detail table has a smallint field which is the foreign key with the master table,

Generally it works correctly when I add a detail entity, but when the value of the primary key of the master entity has a value of 0, when I execute the EF query it tries to insert the value -32670 and Foreign key error is produce because this value does not exist in the master table. In the master table there is a record whose identifier is 0.

Entities
```C#
public class Location
{
      public int Id { get; set; } 
      public short StorageLicationId { get; set; }
      public string Caption { get; set; }
      public string Description { get; set; }

       public StorageLocation StorageLocation { get; set; }
}

public class StorageLocation
{
    public short Id { get; set; }
    public string Caption { get; set; }
    public string Desctiption { get; set; }

    public HashSet<Location> Locations { get; set; }
}
```
Code to insert in database
```C#
using (var ctx = new MyContext())
{
var loc = new Location { **StorageLicationId = 0**, Caption = "Loc1", Description = "Description location1" };

  await ctx.Set<Location>().AddAsync(loc);
  await ctx.SaveChangesAsync();
}
```
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (53ms) [Parameters=[ **@p1='-32667'**, @p2='Loc1',@p3='Description location 1'], CommandType='Text', CommandTimeout='30']

*****************************************************
*****************************************************

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows Server 2019 Standard 
IDE: Visual Studio 2019 16.6.0

Thanks

**Comment by ajcvickers** [comment]
@jose-cousino By default, integer primary keys of any size are made store-generated. This uses the CLR default (zero) as a sentinel value that indicates that the entity is new and needs to have a key value generated. If you're not actually using store generated keys, then this can be disabled using a data annotation or the model builder API. For example:

```C#
[DatabaseGenerated(DatabaseGeneratedOption.None)]
public short Id { get; set; }
```

**Comment by jose-cousino** [comment]
Thank you for the clarification

Bye

**Comment by jose-cousino** [comment]
Yesterday I was thinking and I wanted to ask if it´s not the state of the entity that determines what action has to be done on it (insert, update or delete) and not to check the value 0 of the primary key field of the master table?

Thanks
