### ISSUE TITLE
Consider adding template methods for DbConnection calls

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#21327]
For #7283 I need to call a different overload of DbConnection.Open in the SQL Server provider. I'm adding a template method to allow this, but similar template methods could be useful in other providers. Tentative list of relevant methods based on what RelationalCommand calls:

* BeginTransaction
* Close
* EnlistTransaction
* State
* Dispose

We could also consider doing this for other Db types where they are wrapped by EF.

**Comment by KaloyanIT** [comment]
Hi, I'm interested in contributing. In which providers should be added more template methods?

**Comment by ajcvickers** [comment]
These should be added to RelationalConnection as was done for OpenDbConnection in https://github.com/dotnet/efcore/pull/21328/files

**Comment by KaloyanIT** [comment]
I am not sure that I understand completely what should be done? Should these template methods be implemented in child classes of RelationalConnection?

**Comment by ajcvickers** [comment]
@KaloyanIT The PR above added a new method `OpenDbConnection` like this:

```
protected virtual void OpenDbConnection(bool errorsExpected)
            => DbConnection.Open();
```

It simply calls `DbConnection.Open()`. This is the kind of template method we're talking about here. These methods do not need to be overridden in any providers as part of this change. However, it makes it _possible_ for providers to override these methods. That's what the objective is here.

**Comment by joaopgrassi** [comment]
@KaloyanIT are you still working on this? If not I could take it. (looking to plant a tree this October 😊). @ajcvickers , I took at look at `RelationalConnection` where you added the `OpenDbConnection` but most methods in the list above are already virtual, like `BeginTransaction` so what is actually needed to change?

**Comment by ajcvickers** [comment]
@joaopgrassi Taking BeginTransaction as an example, notice that `RelationalConnection.BeginTransaction` does a bunch of things and then calls `DbConnection.BeginTransaction`. This means if I want to tweak what happens in `DbConnection.BeginTransaction`, I have to override `RelationalConnection.BeginTransaction` and replicate all the code in that method.

The change here is to "extract method" on the call to `DbConnection.BeginTransaction` so it looks like this:

```C#
            var dbTransaction = interceptionResult.HasResult
                ? interceptionResult.Result
                : ConnectionBeginTransaction(isolationLevel);
```
```C#
        protected virtual DbTransaction ConnectionBeginTransaction(IsolationLevel isolationLevel)
            => DbConnection.BeginTransaction(isolationLevel);
```

Now I only need to override `RelationalConnection.ConnectionBeginTransaction`, which means I don't have to duplicate all the code from `RelationalConnection.BeginTransaction`.

(Don't worry too much about the method names; we'll look at them in API review.)

**Comment by joaopgrassi** [comment]
Got it, thanks @ajcvickers that cleared things a lot. If no one is working on it, I'll start and send a PR soon ;)
