### ISSUE TITLE
Visual Studio 2019 "Publish" dialogue "Run 'dotnet tool restore' to make 'dotnet-ef' command available error error

### ISSUE THREAD

**Issue by khalidrs1903** [dotnet/efcore#21325]
I am facing issue while publishing my web application. Entity Framework Migrations area in publish screen displaying error instead of options to Please help me to solve this issue. Screen shot of the error and other info is below.
![image](https://user-images.githubusercontent.com/31385089/85017358-fa3a1300-b188-11ea-858a-3f0dbb7dfd1f.png)

**csproj file**
![image](https://user-images.githubusercontent.com/31385089/85017704-906e3900-b189-11ea-9d24-b75857e20b6f.png)

**"dotnet --info" results**
![image](https://user-images.githubusercontent.com/31385089/85017508-33728300-b189-11ea-8350-f435d14ab82a.png)

Thank you

**Comment by ajcvickers** [comment]
@khalidrs1903 Issues in Visual Studio tooling are better reported with the "Send Feedback" option in VS. This will get the issue to a place where the VS team will see it.

**Comment by khalidrs1903** [comment]
@ajcvickers  thnak you for the input, but i am trying here to understand if i am doing something wrong or is it really issue and if it is a issue then is it EF Core or Visual Studio. Expecting a guidance.
Thanks Again.

**Comment by ajcvickers** [comment]
@khalidrs1903 This looks to me like a bug in the tooling.

**Comment by UserMuc123** [comment]
Hello, I am having the same issue. Is there any solution for this? Any help is apreciated
