### ISSUE TITLE
Clarification - foreign Key error when inserting value 0

### ISSUE THREAD

**Issue by jose-cousino** [dotnet/efcore#21323]
Yesterday I made a question about a possible error I have when when I enter the value 0 in the Foreign Key field.   #21310 

And the answer made me more doubtful, so I wanted to ask:

I thought that the context of EF to know what operation it has to do (insert, update or delete) depending on the state of the entity and not on the evaluate of the primary key field, and in this case on the value 0 of the Foreign key field.

Please, confirm me if the context evaluates the state of the entity to know which operations is the one that has to be done or is the verification of the value of the Foreign Key field.

And if it is the sate of the entity, you could tell me, when I insert in the Foreign Key field a 0, the context of EF tries to insert the value -32760 causing a Violation Foreign Key error.

Thanks

**Comment by ajcvickers** [comment]
@jose-cousino EF needs to know the initial state of new entities. These can be explicitly specified, but when using generated keys it is useful to use whether or not the key value is set to distinguish new from existing entities. See these docs for more information: https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities
