### ISSUE TITLE
Setting IsConcurrencyToken on an Owned Entity Property and updating that property generates incorrect SQL

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#21322]
Setting `IsConcurrencyToken()` on the property of an owned entity causes wrong SQL to be generated despite the changes being tracked. This started occurring just recently. Can't identify which version of nightly/preview.

```c#
 builder.OwnsOne(y => y.CurrentBalance, p =>
            {
                p.Property(p => p.Amount).IsConcurrencyToken(); //removing IsConcurrencyToken generates SQL UPDATE when the property is updated. Leaving IsConcurrencyToken causes the property to be ignored despite being updated and tracked for change.
                p.OwnsOne(x => x.Currency);
            });
```

related to https://github.com/dotnet/efcore/issues/21316?

EF Core version: 5.0.0-preview.7.20317.4
Database provider: npgsql 5.0.0-preview6-ci.20200617T130728
Target framework: .NET 5 nightly (preview 7)
Operating system: Win 10
IDE: VS 2019 16 preview 2

**Comment by AndriySvyryd** [comment]
@vflame I'm not able to repro this. Could you create a small runnable project using [daily build](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md)?

**Comment by vflame** [comment]
I currently can't use the latest daily build since I'm held back by npgsql (which only supports preview 7) at the moment.
