### ISSUE TITLE
IProperty.IsReadOnlyBeforeSave with value generators

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#2132]
It would be nice if I could set IsReadOnlyBeforeSave when the value is set on add with a value generator.

**Comment by ajcvickers** [comment]
Discussed this in triage and we decided that this could be done if we add another flag to the state entry similar to the IsTemporary flag, but instead for IsSystemGenerated. If this flag is set and IsReadOnlyBeforeSave is set, then user code would not be able to change the value. However, note that we would have to have a way of knowing that it was user code setting the value, which would introduce some additional coupling between components.

This isn't a super important feature so leaving it as Pri1 for now.
