### ISSUE TITLE
Query: The curious case of merge

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#21332]
For query like following
```C#
ss.Set<EntityOne>().Include(e => e.ThreeSkipPayloadFull).ThenInclude(e => e.CollectionInverse)
                    .Include(e => e.JoinThreePayloadFull).ThenInclude(e => e.Three).ThenInclude(e => e.ReferenceInverse)
```
Where `ThreeSkipPayloadFull` is just skipping over `JoinThreePayloadFull.Three`, how should we deal with these includes?

Couple of issues around this
- Major issue is how should query materialize and initialize things. From query perspective, first chain is just there is a collection include, so it will create the collection and get data to fill into it disregarding anything in the middle. For that chain query does not generate the join entity at all since collection include for query is initialize the collection using INavigationBase and put entities into it. That means the second chain in above example becomes a different subquery (they are subquery since collection includes). So query fetches the data twice for same columns and entities and fills both chain separately with different entity instances.

- Minor issue is difference with tracking query. Since Statemanager will generate the join entities, i.e. putting anything in skip collection navigation will also add join entity fixup, they will be merged into one consistent graph. But same is not possible in no tracking query. So behavior would be with just one chain above, second chain will be populated in tracking query but not in non-tracking query.

**Comment by ajcvickers** [comment]
Discussed and agreed that the current behavior is accecptable.
