### ISSUE TITLE
Consider making annotation names public

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21331]
The names of our annotations are currently pubternal (e.g. CoreAnnotationNames, RelationalAnnotationNames). In theory it shouldn't be necessary to use them - the metadata APIs should be enough. However, there are various scenarios where the annotations themselves need to be manipulated directly:

* External conventions may need to intercept a specific annotation being set/modified. I hit this case in EFCore.NamingConventions, where [special logic needs to happen](https://github.com/efcore/EFCore.NamingConventions/blob/master/EFCore.NamingConventions/NamingConventions/Internal/NameRewriterBase.cs#L84) when the table name is set.
* In PR #21329,  AnnotationCodeGenerator [needs to process annotations directly](https://github.com/dotnet/efcore/pull/21329/files#diff-b77f40ee1be01b6fa38d5740613950e5R16) - and not even on the IAnnotatable.

**Comment by AndriySvyryd** [comment]
`RelationalAnnotationNames` is public

`CoreAnnotationNames` are an implementation detail and shouldn't be treated as other annotations. In the future they won't be returned together with other annotations - #19806. Other implementations, like the compiled model might not store those facets as annotations.

**Comment by roji** [comment]
Thanks for the explanation @AndriySvyryd, makes sense.
