### ISSUE TITLE
Question: Is it possible to use IgnoreQueryFilters in an explicit load?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#21349]
This isn't a feature request, but a question. Wasn't sure where I should post questions.

I'm looking at creating a soft delete method that mimics the cascade delete. For instance if I had relationships `GrandFather -> Father -> Son` I soft delete `GrandFather` it would also soft delete the `Father` and `Son` too. This could be useful in *some* situations.

To do this I use explicit loading to load any relationships, e.g. for collections `_context.Entry(principalInstance).Collection(navigation.PropertyInfo.Name).Load();`

The soft delete works, but the un-soft delete doesn't because I need to load the relationships with `IgnoreQueryFilters` method in it, and I can't find a way to do that. 

Can you suggest a way around this? Building a real query is doable, but quite hard to get right for all situations. The other option is to cast the `_context.Entry(principalInstance).Collection(navigation.PropertyInfo.Name).Query()` to the right form to apply the `IgnoreQueryFilters()` method.

Any wisdom greatly received.

PS. If you are interested the current version of the CascadeSoftDelService can be found [here](https://github.com/JonPSmith/EfCoreinAction-SecondEdition/blob/Part2/ServiceLayer/SoftDeleteServices/Concrete/CascadeSoftDelService.cs).

**Comment by ajcvickers** [comment]
@maumar @smitpatel Do we have an overall issue tracking improvements to the usability of query filters?

**Comment by JonPSmith** [comment]
Though you might like to know that I have found a way to apply a `IgnoreQueryFilters()` method to a explicit load. This small snippet shows how I do it - the class `GenericCollectionLoader<TEntity>` at the end is where the clever part lives. 

I consider this issue closed, but you might like to provide a version of `IgnoreQueryFilters()` method for explicit loading. I doubt it will be needed much but it might help someone else.

```c#
private void LoadNavigationCollection(object principalInstance, INavigation navigation)
{
    if (_set)
        //For setting we can simple load it, as we don't want to set anything that is already set
        _context.Entry(principalInstance).Collection(navigation.PropertyInfo.Name).Load();
    else
    {
        //for undoing a soft delete we need to load the collection with a IgnoreQueryFilters method
        var navValueType = navigation.PropertyInfo.PropertyType;
        var innerType = navValueType.GetGenericArguments().Single();
        var genericHelperType =
            typeof(GenericCollectionLoader<>).MakeGenericType(innerType);

        Activator.CreateInstance(genericHelperType, _context, principalInstance, navigation.PropertyInfo);
    }
}

private  class GenericCollectionLoader<TEntity> where TEntity : class
{
    public GenericCollectionLoader(DbContext context, object principalInstance, PropertyInfo propertyInfo)
    {
        var query = context.Entry(principalInstance).Collection(propertyInfo.Name).Query();
        var collection = query.Provider.CreateQuery<TEntity>(query.Expression).IgnoreQueryFilters().ToList();
        propertyInfo.SetValue(principalInstance, collection);
    }
}
```

**Comment by ajcvickers** [comment]
@JonPSmith We're tracking making this easier in #17347. Also, I have created an [overall issue for improving the query filter experience](#21459).

**Comment by JonPSmith** [comment]
Your link is broken - see #21459 for link to Improve usability of global query filters issue.

**Comment by smitpatel** [comment]
Updated broken link.
