### ISSUE TITLE
Single_non_scalar_projection_after_skip_uses_join failing because of missing ORDER BY

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21341]
When syncing EFCore.PG, the new Single_non_scalar_projection_after_skip_uses_join is failing, probably because of non-deterministic ordering.

```c#
ss.Set<Customer>().Select(c => c.Orders.OrderBy(o => o.OrderDate).Skip(2).FirstOrDefault()
```

Translates to:

```sql
SELECT t0."OrderID", t0."CustomerID", t0."EmployeeID", t0."OrderDate"
        FROM "Customers" AS c
        LEFT JOIN (
            SELECT t."OrderID", t."CustomerID", t."EmployeeID", t."OrderDate"
            FROM (
                SELECT o."OrderID", o."CustomerID", o."EmployeeID", o."OrderDate", ROW_NUMBER() OVER(PARTITION BY o."CustomerID" ORDER BY o."OrderDate" NULLS FIRST) AS row
                FROM "Orders" AS o
            ) AS t
            WHERE (2 < t.row) AND (t.row <= 3)
        ) AS t0 ON c."CustomerID" = t0."CustomerID";
```

And ordering isn't preserved coming out of the innermost subquery.

/cc @smitpatel @maumar

**Comment by smitpatel** [comment]
It is not supposed to be preserved. The outer does not specify any ordering. AssertQuery will sort them.

**Comment by roji** [comment]
Ah, misread the LINQ (and the window query), that makes sense. I dug deeper into this test failure and something very strange is going on, will update.

**Comment by roji** [comment]
This did turn out to be a non-deterministic ordering issue: customer LACOR has two orders with the same date...
