### ISSUE TITLE
`EntityEntry.CurrentValues`

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/efcore#21343]
`EntityEntry.CurrentValues` throws an 'System.InvalidOperationException' when accessing a property which does not exist.

Just like `EntityEntry.CurrentValues.GetValue<T>`, I believe we should have:

- `+ public bool EntityEntry.CurrentValues.TryGetValue<T>(string propertyName, out T value)` which will indicate if the property existed or not without having to deal with the stack preservation overhead.

Perhaps the out should be a `PropertyValue` or there should also be a corresponding overload.

**Scenario:**
Consider implementing Soft Delete on some objects but not all or having `Created/ModifiedDate` or some combination therein on some objects but not all.

**Work around:**
Write trivial extension method, which unfortunately still have the overhead of the exception.

Using EntityFrameworkCore 3.1.5

**Comment by ajcvickers** [comment]
@juliusfriedman The entity type metadata can be checked if needed before calling the method. There are several options for doing this; one example is:

```C#
var property = entry.Metadata.FindProperty(propertyName);
if (property != null)
{
    Console.WriteLine(entry.CurrentValues.GetValue<string>(property));
}
```

**Comment by juliusfriedman** [comment]
Good to know thank you! Please close this issue if you see fit.

**Comment by KaloyanIT** [comment]
Is this issue still in To Do or the comment from @ajcvickers resolves it?
