### ISSUE TITLE
Query: Factories used during query compilation takes QueryCompilationContext in Create method

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#21345]
As QueryCompilationContext is an object holding various states and flags used during a query compilation, based on usage various visitors which are run during compilation may need access to some states from it. In order to avoid future breaks,
we have aligned following Visitors & their associated factory methods to take QueryCompilationContext as parameter.
Following factories were already accepting QCC as argument.
- IQueryTranslationPreprocessorFactory
- IQueryTranslationPostprocessorFactory
- IShapedQueryCompilingExpressionVisitorFactory

Following factories have been changed to accept QCC as argument.
- IQueryableMethodTranslatingExpressionVisitorFactory
- IRelationalSqlTranslatingExpressionVisitorFactory

If you are having a custom visitor for above, then please update factory method and ctor of the visitor accordingly.

Changes were made in #20422

**Comment by smitpatel** [comment]
@AndriySvyryd - Should close this issue in 5.0?

**Comment by AndriySvyryd** [comment]
Yes, it's "fixed"
