### ISSUE TITLE
Left Topic/Index pane in documentation

### ISSUE THREAD

**Issue by MuraliManickam** [dotnet/efcore#21354]
I just have a thought that the left pane of microsoft documentation that shows subtopics/index of particular topic seems kind of blocking to read the content of the documentation

Presentation of the content is good, but if you provide toggle option for show/hide on the left subtopic/index pane that would be great.
![Capture](https://user-images.githubusercontent.com/12298856/85213112-1922db80-b328-11ea-8b6d-a112f89ba838.JPG)

**Comment by roji** [comment]
@MuraliManickam feedback on the doc site itself (as opposed to EF Core content in it) should be reported in https://github.com/MicrosoftDocs/feedback/issues.
