### ISSUE TITLE
StackOverflowException when accessing a LazyLoaded navigation property in a 'getter'

### ISSUE THREAD

**Issue by slovely** [dotnet/efcore#21356]
If an entity property has a `get` that accesses a Navigational Property on the entity, you get a StackOverflowException.
The attached example is of course made-up, but this pattern was found when looking at updating an existing EF6 application to EFCore.  The pattern works as expected in EF6.

I'm not sure if this is a bug, or whether this behaviour would be expected in EFCore due to changes to the change tracker, but it did work in EF6 so if it is not a bug would there be someway to workaround it but still get the same behaviour in EFCore?  Uncommenting line 20 to disable the change tracker will allow the program to run, but of course in the real application we do need changes to be tracked.

Thank you.

### Steps to reproduce
This gist contains a simple program that reproduces the problem (NOTE update the connection string on line 11): https://gist.github.com/slovely/17fda7d7f6524d3c40eb6fafcc44da6c

### Stack Trace
(shortening to just show the recursion)
```
Recursive.get_Name() at C:\Projects\Git\EFCoreTesting\StackOverflowTest\Program.cs:line 80 [2]
[Lightweight Method Call]
ClrPropertyGetter<Recursive, string>.GetClrValue() [1]
InternalEntityEntry.ReadPropertyValue() [1]
InternalEntityEntry.get_Item() [1]
ChangeDetector.LocalDetectChanges() [1]
ChangeDetector.DetectChanges() [1]
ChangeDetector.DetectChanges() [1]
EntityEntry.DetectChanges() [1]
DbContext.TryDetectChanges() [1]
DbContext.Entry() [1]
LazyLoader.ShouldLoad() [1]
LazyLoader.Load() [1]
LazyLoadingInterceptor.Intercept() [1]
AbstractInvocation.Proceed() [1]
RecursiveProxy.get_Children() [1]
Recursive.get_Name() at C:\Projects\Git\EFCoreTesting\StackOverflowTest\Program.cs:line 80 [1]
[Lightweight Method Call]
new InternalEntityEntry.OriginalValues()
InternalEntityEntry.EnsureOriginalValues()
InternalEntityEntrySubscriber.SnapshotAndSubscribe()
StateManager.StartTrackingFromQuery()
QueryContext.StartTracking()
[Lightweight Method Call]
QueryingEnumerable<Recursive>.Enumerator.MoveNext()
Enumerable.Single<StackOverflowTest.Recursive>()
[Lightweight Method Call]
QueryCompiler.Execute<StackOverflowTest.Recursive>()
EntityQueryProvider.Execute<StackOverflowTest.Recursive>()
Queryable.First<StackOverflowTest.Recursive>()
Program.Main() at C:\Projects\Git\EFCoreTesting\StackOverflowTest\Program.cs:line 21
```

### Further technical details

EF Core version: 3.1.200
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Rider, but same in VS or cmd line.

**Comment by slovely** [comment]
To add some context that is probably missing on the `why` in this example...
In the real add the property in question needs the value stored in the database, but it is calculated from values in the navigation entity (which in this particular case happens to be a reference to the same entity, but it doesn't need to be).

If there is a better way to store a calculated value like that then any suggestions gratefully received 🤟

**Comment by ajcvickers** [comment]
Note for team: the main issue here is that EF Core using wring to backing fields as a means to ensure non-re-entrance. This is enforced for navigation properties, but in this case a mapped regular property without a backing field is calling into the lazy-loaded property, which means that EF triggers lazy loading when it accesses that property. See also #7946.

@slovely This can be made to work by using a backing field:

```C#
private string _name;
public string Name
{
    get => _name = Children
    set{}
}
```

**Comment by slovely** [comment]
Thank you for the ridiculously quick response.  Using a backing field does indeed solve the StackOverflowException.  One small issue though, is that when the initial entities are created, the 'Name' column will be NULL (in the database only, the model is correct).  If they are reloaded and then saved again, the value will be set correctly.  I tried various `PropertyAccessMode` settings, but they either didn't save the `Name` column or caused the StackOverflowException again.

I worked around it with a fairly simple override of SaveChanges:

```
        public override int SaveChanges()
        {
            foreach (var e in ChangeTracker.Entries())
            {
                if (e.State == EntityState.Added && e.Entity is Recursive recursive)
                {
                    // Force the name field to be updated.
                    recursive.Name = recursive.Name;
                }
            }
            return base.SaveChanges();
        }
```

Feel free to close this issue if you want, otherwise I'm happy to re-test the original error if EF is updated to avoid the StackOverflow.

Thanks again! 👍

**Comment by ajcvickers** [comment]
@slovely I thought about it a bit, but I can't come up with a better workaround than what you're doing in SaveChanges. However, we discussed and I have re-opened a previous request for first-class support for client computed but persisted properties.

**Comment by slovely** [comment]
👍 Thank you very much!
