### ISSUE TITLE
Helper extension for creating Sequential GUIDs (COMB)

### ISSUE THREAD

**Issue by mrtaikandi** [dotnet/efcore#2135]
Hi folks,

Considering that there are many options to generate sequential GUIDs by using UuidCreateSequential or DateTime which each has their pros and cons, wouldn't be helpful to have an extension method or something for generating these values that is compatible with both full framework and .NET Core.

**Comment by rowanmiller** [comment]
We have a [SequentialGuidValueGenerator](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/ValueGeneration/SequentialGuidValueGenerator.cs) already baked into EF7 for just this purpose.

**Comment by mrtaikandi** [comment]
Thank you for the clarification. It is very useful.
