### ISSUE TITLE
Split repo to minimize dependency on Hosting

### ISSUE THREAD

**Issue by Tratcher** [dotnet/efcore#2136]
EntityFramework.Commands is the only project that depends on the Hosting repo. This dependency causes EF to rebuild on the CI much more frequently, and it 20 minutes every time.

Proposal: Move this project to another repo and remove EF's dependency on the Hosting repo.

**Comment by bricelam** [comment]
:grinning: My proposal (in #2020) was to split Hosting to decouple it from service discovery and building.

**Comment by rowanmiller** [comment]
**Triage** Agreed with Brice's comments, it makes more sense to split out the piece of functionality we use in Hosting.
