### ISSUE TITLE
VS 2017 shows red squiggly on UseSqlSever when method is resolved

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/efcore#21361]
To reproduce:
1. Create new ASP.NET Core web app with all defaults.
2. Add Movie class

```
public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }  
```

3.Scaffold
4. Build/run - it works fine.
5. Open _Startup.cs_ and UseSqlSever is underlined with red squiggly.  It shows the error:
'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer' and no extension method 'UseSqlServer' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by kmkrish007** [comment]
After installing **Microsoft.EntityFrameworkCore.SqlServer** Nuget package my issue resolved.

**Comment by SarahAbelWhab** [comment]
Install-Package Microsoft.EntityFrameworkCore.SqlServer "the same version of your .net core you chose when created the project"

**Comment by Jacob273** [comment]
I got updated **Microsoft.EntityFrameworkCore.SqlServer** to the version **5.03,** and installed Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 5.0.3 IDE still did not recognized UseNetTopologySuite() extension after installation

I had to rebuild the .csproj and then the error dissapeared.

**Comment by Nicky0230** [comment]
> funcionó instalando el paquete Microsoft.EntityFrameworkCore.Sqlite.Core

**Comment by Nicky0230** [comment]
me funciono instalando Microsoft.EntityFrameworkCore.SqlServer
