### ISSUE TITLE
HasComment is too strict and does not work with any column that is somehow depended on

### ISSUE THREAD

**Issue by aminsrz** [dotnet/efcore#21364]
Adding a comment to a column that another column is dependent on gives the following error when updating database:

The column 'FullName' is dependent on column 'FirstName'.
ALTER TABLE ALTER COLUMN FirstName failed because one or more objects access this column.

### Steps to reproduce

If you have a computed colums like this:
``` C#
            migrationBuilder.AddColumn<string>(
                name: "FullName",
                table: "Person",
                maxLength: 200,
                nullable: true,
                computedColumnSql: "[FirstName] + ' ' + [LastName]");
```
Then another migration that is adding a comment to the [FirstName] and [LastName] columns cannot be applied and gives the mentioned error message when updating the database:
```
            builder.Property(x => x.FirstName)
                .HasComment("نام");
            builder.Property(x => x.LastName)
                .HasComment("نام خانوادگی");
            builder.Property(x => x.FullName)
                .HasComment("نام کامل");
```

### Further technical details

EF Core version: EF Core 3.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)

**Comment by aminsrz** [comment]
The same error happens with foreign keys:

> The index 'IX_Decision_LatePaymentLetterId' is dependent on column 'LatePaymentLetterId'.
> ALTER TABLE ALTER COLUMN LatePaymentLetterId failed because one or more objects access this column.

I think the problem is that for such a simple thing as adding a description it uses the AlterTable/AlterColumn migration method, which has a lot of unwanted consequences.
``` C#
            migrationBuilder.AlterColumn<int>(
                name: "LatePaymentLetterId",
                schema: "DecisionAndOpinion",
                table: "LatePaymentLetterReceiver",
                nullable: false,
                comment: "شناسه نامه عدم پرداخت", //the only change
                oldClrType: typeof(int),
                oldType: "int");
```

**Comment by aminsrz** [comment]
And this is the error message for adding comment to the computed column itself:

> Cannot alter column 'SequenceNumber' because it is 'COMPUTED'

**Comment by bricelam** [comment]
Agreed--we should be smarter. We don't actually need the ALTER TABLE..ALTER COLUMN statement if only these things change:
- Identity (when we let the database throw)
- DefaultValue
- DefaultValueSql
- Comment

**Comment by bricelam** [comment]
On a related note, it looks like we don't handle altering comments on computed columns at all. We don't copy it to the add operation:
https://github.com/dotnet/efcore/blob/7f3e01aa6b00f0e3d61639a069d62033c8cf4bf5/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L233-L250
