### ISSUE TITLE
Cannot create a DbSet for 'DocumentChecklistItem' because this type is not included in the model for the context

### ISSUE THREAD

**Issue by charliex3** [dotnet/efcore#21375]
Hi!

I'm getting the above mentioned error in my code.
Just to be clear from the very beginning, the code works, I have everything initialzed in DbContext correctly, running .NET Core 2.1.
How I know that it works? Well because it's running correctly on the production server, 3 test servers, my 2 laptops and even my colleagues didn't encounter this bug.

I just can't seem to figure out where the hell is a difference between my desktop and two laptops where it works, as I've already tried even to reinstall windows on my desktop and even that didn't help.

![image](https://user-images.githubusercontent.com/67288343/85323194-e1529a00-b4c7-11ea-8d0e-e4b3d3a1d519.png)

![image](https://user-images.githubusercontent.com/67288343/85323202-e6174e00-b4c7-11ea-81fa-733fb8d5f837.png)

![image](https://user-images.githubusercontent.com/67288343/85323455-532ae380-b4c8-11ea-843e-2176c128a7bb.png)

I'm getting the same result on a few other models and don't know why... there's not correlation between them.

It's super weird bug... I've been analyzing code for past 2-3 days what the differences are but I did not find any. It's like it doesn't initialize something but what? that's the question...

I'm running .NET Core 2.1 with EF 2.1.8.

Any ideas what can be wrong on my PC?
Has anyone encounter a similar problem?

Thanks! Much appreciated for all tips on how to fix this.

PS: Like the only difference between my two laptops and desktop is that desktop is using AMD Ryzen and laptops are Intel... It's kind of a stupid thinking but I've literally tried almost everything else I found on the internet and just can't seem to get rid of it, it's super annoying that It happens only on one machine without a proper explanation why.

**Comment by ajcvickers** [comment]
@charliex3 I don't think that there is any realistic way for us to help you here since there is no way for us to reproduce what you are seeing.

**Comment by charliex3** [comment]
I'm more or less just curious if this was not encountered by someone already and would be willing to guide me how to fix it. It's really funny that even after windows reinstallation it still happens.
