### ISSUE TITLE
Expose model building conventions to applications

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#214]
- [x] Create public interfaces for metadata API to be used by conventions.
- [x] Change `QueryFilter`, `DefiningQuery`, `IsEagerLoaded`, `IsShadowProperty` , `IsIndexedProperty`, `BeforeSaveBehavior` `AfterSaveBehavior` to extension methods.
- [x] Throw when calling `SetField` would change the shadowness of a property or the name of the identifying `MemberInfo`.
- [x] Rename `GetContainingPrimaryKey` to `FindContainingPrimaryKey`.
- [x] Throw when calling `SetField` on a shadow or a field-only property.
- [x] Create public interfaces that the internal model builders implement, e.g. `IConventionModelBuilder`. This will allow cleaner API, without the explicit `ConfigurationSource` parameter.
- [x] Throw instead of silently failing when a non-explicit configuration call is invalid. This would require adding quiz API ('CanSet').
- [x] Make model element references consistent (e.g. `Property` vs `IProperty` vs `string` vs `PropertyInfo`)
- [x] Add provider-specific extension methods for convention metadata interfaces.
- [x] Rename and move `RelationalAnnotations` and `RelationalAnnotationsBuilder` to Core.
- [x] Remove unused methods on provider classes like  `SqlServerPropertyBuilderAnnotations.ColumnName`.
- [x] Rename the `Apply` methods to be more descriptive and make the return types consistent, still allowing to stop the execution of the following conventions.
- [x] Pass `CoreConventionSetBuilderDependencies` to the constructor of all conventions.
- [x] Add convention type for configuring a type as owned and use it to remove ambiguous ownerships.
- [x] Track the model elements as they are modified by conventions, so a call to a convention never returns an element that is no longer in the model.
- [x] Add a way to delay the convention execution.
- [x] Move logic from `ModelCustomizer` to a convention.
- [x] Add `SqlServerValueGenerationStrategy.None` value that can be used to override the model default.
- [x] Filter out the core annotations changes from conventions.
- [x] Remove `PropertyMetadataChanged()` calls and don't cache indexes while the model is mutable.
- [x] Expose conventions as `List` on `ConventionSet`
- [x] Add methods to add/remove a convention to/from all appropriate convention lists.
- [x] Add a `Conventions` property of `ConventionSetBuilder` type to `ModelConfigurationBuilder` with methods to add/remove a convention

**Comment by sthiakos** [comment]
This was useful for me in the following Scenarios:
* Undo default conventions applied by EF using DbModelBuilder
** Creating an IStoreModelConvention for AssociationType to remove underscore from FK names,
** Creating an IStoreModelConvention for EntitySet to remove underscore from m-2-m join tables/dbsets.

* Dictate Entity Identity Behaviors - using the modelBuilder.Types() method:
** Auto-generation based on whether it's a Data-Dictionary/Lookup item (e.g. BlogType - static) vs an Entity (Blog - autogen).  They are distinguished based on interface implementations.

* Decouple code naming standards and DB naming standards - using the modelBuilder.Properties() method:
** Give a common Class property (e.g. "StateId") but an explicit db column name (e.g. "BlogStateId").  Same goes for "Id" in code but "{Type}Id" in database.

Doing this once I was able to govern the entity definitions without requiring explicit entity declaration.  I'm not advocating the same implementation, but do feel custom/override conventions are valuable.

Cheers,

Steve

**Comment by rowanmiller** [comment]
Some of these types of things can be achieved by iterating over the model that is created by convention. This was not possible in EF6 because we collected a set of configuration during OnModelCreating and then used that plus conventions to build the model. But in EF7 we build an initial model from conventions and then pass that to OnModelCreating.

Of course, this means you need to be mindful of ordering. For example, if a type wasn't included in the model by convention, then you need to make sure you add it before you iterate over the model and assign table names.

Here is an example of appending an `s` to the table name.

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  foreach (var entity in modelBuilder.Model.GetEntityTypes())
  {
    modelBuilder.Entity(entity.Name).ToTable(entity.Name + "s");
  }
}
```

**Comment by sthiakos** [comment]
Thanks for the info Rowan,

I'll just need to explicitly load my entities in this method for my domain assembly:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var entityTypes = myDomainAssembly.DefinedTypes
        .Where(ti => ti.IsClass && ti.IsPublic && !ti.IsAbstract && !ti.IsNested)

    foreach (var entityType in entityTypes)
    {
        modelBuilder.Entity(entityType).DoStuff(...);
    }
}
```
This makes me think that perhaps an `OnEntityModelCreating(ModelBuilder entityModelBuilder)` may help with conventions and keep things dynamic.

Steve

**Comment by totht91** [comment]
I see that this issue is not a priority issue, but will the custom conventions be implemented before RC2, or just before RTM? (I hope it will be at least in RTM)

**Comment by ErikEJ** [comment]
According to the current roadmap it will be in 7.0.2 (?) https://github.com/aspnet/EntityFramework/wiki/Roadmap

**Comment by totht91** [comment]
Ohh I missed this. Thank you.

**Comment by simonlampen** [comment]
Is this the correct issue to follow for being able to register custom EdmFunctions.
i.e: in EF 6.1 I can register a mapping from a custom SUM implementation to a SQL custom aggregate function using code like this:

````
modelBuilder.Conventions.Add(new AddAggregateFunctionRegistration())
...
public class AddAggregateFunctionRegistration ...

  public void Apply(EntityContainer item, DbModel dbModel)
    var edmFunction = EdmFunction.Create("MySum", "dbo", ...
    ...
    dbModel.StoreModel.AddItem(edmFunction);
    dbModel.Compile();

````

Can this be done in EF7 or are we waiting for further Convention features to be implemented?

Simon

**Comment by rowanmiller** [comment]
@simonlampen you would need more than this item to support Model Defined Functions. I don't think we have an issue tracking that feature (cc @divega in case he knows of one that covers that scenario).

**Comment by simonlampen** [comment]
Thanks @rowanmiller. @divega FYI the scenario we are looking to handle is the one outlined here: http://stackoverflow.com/questions/33437455/code-first-entity-framework-6-1-custom-aggregate-function
Simon

**Comment by divega** [comment]
@rowanmiller Although we don't have any issue specifically covering user defined aggregate functions we have a few issues covering user defined functions in #621, #622 and #2538. In fact there is some overlap among them. 

It might be a good idea to consolidate user defined function support in one issue with a list of scenarios and description of ideas we could implement (e.g. allow specifying the mapping to CLR function in the model for use in LINQ, annotating the function with an attribute, `FromSql()` style ad-hoc support, etc). Thoughts?

**Comment by rowanmiller** [comment]
@divega yep I agree (I'm always in support of less granular items to track on the backlog :smile:). Opened #4319 and closed out the others. Feel free to add any details to the new issue.

**Comment by divega** [comment]
@rowanmiller Looks great. I only added user-defined aggregate functions to the description and some details about the possible usage patterns we could enable.

**Comment by ajcvickers** [comment]
Consider a way to get from IMutableEntityType (or similar) to the InternalEntityTypeBuilder (or similar) so that changes can be flagged as "by convention" when making changes to an IMutableEntityType. See comments on PR #4688.

**Comment by AndriySvyryd** [comment]
Add conventions that run when an index is added/removed

**Comment by divega** [comment]
Regarding 

> When executing delayed conventions prune redundant ones.

We believe that this could help improve the performance of building the model quite a bit. Currently our benchmarks show that build the model is marginally slower than EF6:

### InitializationTests.BuildModel_AdventureWorks

![image](https://cloud.githubusercontent.com/assets/1253414/25501839/f8a25b3e-2b48-11e7-8886-17dfeb7d48bc.png)

cc @AndriySvyryd

**Comment by ajcvickers** [comment]
See #11404 for details of internal conventions related API that are used by providers.

**Comment by ajcvickers** [comment]
Also consider https://github.com/aspnet/EntityFrameworkCore/issues/11738 when working on this issue.

**Comment by ajcvickers** [comment]
Closed #11404 and #11405 as duplicates of this since providers will need to update to the new public APIs for 3.0,

**Comment by MeikelLP** [comment]
In case someone comes across this and requires a workaround for snake case table & property names... Here is my workaround (may help the implementation or extensions):

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    foreach (var entity in modelBuilder.Model.GetEntityTypes())
    {
        // table names
        modelBuilder.Entity(entity.Name).ToTable(ToSnakeCase(entity.ShortName() + 's'));
        
        // properties
        var props = GetType().Assembly
            .GetType(entity.Name)
            .GetProperties()
            .Where(x => 
                x.GetCustomAttribute<NotMappedAttribute>() == null &&
                (
                    x.PropertyType.IsPrimitive ||
                    (
                        typeof(Nullable<>).IsAssignableFrom(x.PropertyType) && x.PropertyType.GenericTypeArguments[0].IsPrimitive
                    )
                )
            );
        foreach (var prop in props)
        {
            modelBuilder.Entity(entity.Name).Property(prop.Name).HasColumnName(ToSnakeCase(prop.Name));
        }
    
    }
}

private string ToSnakeCase(string input)
{
     var returnString = "";
     foreach (var chr in input)
     {
         if (chr.ToString().ToUpper() == chr.ToString())
         {
              // is uppercase character
             returnString += '_' + chr.ToString().ToLower();
         }
         else
         {
             returnString += chr;
         }
    }

    returnString = returnString.TrimStart('_');
    return returnString;
}
```

**Comment by ajcvickers** [comment]
Planning: we will do here what we can fit into 3.0

**Comment by smitpatel** [comment]
Make the opt-in for Enums for 5.0

**Comment by Saibamen** [comment]
Any plans to have it in EF Core 5.0 (or even faster, in some preview)?

**Comment by AndriySvyryd** [comment]
@Saibamen No, we don't plan to ship this in EF Core 5.0

**Comment by Martin-Andersen** [comment]
It's such a common feature I work with oracle and my company insist on using all uppercase for everything

**Comment by AraHaan** [comment]
Any ETA to allow applications to register custom ``EntityTypeAddedConventions``, ``EntityTypeBaseTypeChangedConventions``, ``ModelFinalizingConventions`` for their application and relational databases?

**Comment by roji** [comment]
@AraHaan providers can already add conventions by creating their own IProviderConventionSetBuilder (typically extending RelationalConventionSetBuilder to get the default relational conventions), and then adding whatever conventions they want. See [NpgsqlConventionSetBuilder](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Metadata/Conventions/NpgsqlConventionSetBuilder.cs) for an example.

**Comment by Neme12** [comment]
> Any ETA to allow applications to register custom `EntityTypeAddedConventions`, `EntityTypeBaseTypeChangedConventions`, `ModelFinalizingConventions` for their application and relational databases (or at least a way to extend the database providers themselves to add them)?

Yes, it's already possible, I've done it for a while now.

**Comment by AraHaan** [comment]
Alright, I have added my own conventions, but currently only on top of the one used by the default SqlServer provider and named it as an extension to it (it registers the SqlServer provider then immediately replaces it's ConvensionSetBuilder registered in the DI container with it's own).

It feels like an hack but it works for now.

**Comment by vupham1111** [comment]
hello, I come from this https://github.com/dotnet/efcore/issues/27400
does the ef core support this feature yet, if it does, I hope you can feed me some guidance, thank you so muchhhh

**Comment by ajcvickers** [comment]
@vupham1111 See https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#model-building-conventions
