### ISSUE TITLE
Update error message CoreStrings.ConflictingRelationshipNavigation to say what to Ignore

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#21416]
Suppose you are trying to override an existing 1:1 relationship with a new 1:N relationship i.e.
```
    modelBuilder.Entity<Nob>().HasOne(e => e.Hob).WithOne(e => e.Nob);
    // and some time later...
    modelBuilder.Entity<Nob>().HasMany(e => e.Hobs).WithOne(e => e.Nob);
```

(The test `OneToManyTestBase.Removes_existing_unidirectional_one_to_one_relationship()` exemplifies this if you remove [line 1881](https://github.com/dotnet/efcore/blob/ad93e5cc7cd1276dee48b31532a0dc8816daa7ba/test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs#L1881)).

If you set up the situation above you get the following error message :
```
Cannot create a relationship between 'Nob.Hobs' and 'Hob.Nob', because there already is a relationship between 'Hob.Nob' and 'Nob.Hob'. Navigation properties can only participate in a single relationship. If you want to override an existing relationship call Ignore on the navigation first.
```

The 1:N relationship creation will succeed whichever of the two existing navigations, `Hob.Nob` or `Nob.Hob` you Ignore. However if you Ignore `Nob.Hob` then automatic discovery of other relationships in which that navigation can participate will fail. E.g. if you replace [line 1881](https://github.com/dotnet/efcore/blob/ad93e5cc7cd1276dee48b31532a0dc8816daa7ba/test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs#L1881) with:

```
    modelBuilder.Entity<Nob>().Ignore(e => e.Hob);
```
then the later asserts of that test will fail (since they depend upon `Nob.Hob`).

@AndriySvyryd and I discussed and we think the error message would be more useful if it specified which navigation to Ignore. I suggest the error message should end with:
```
...If you want to override the existing relationship call Ignore on the navigation 'Hob.Nob' first.
```

**Comment by KaloyanIT** [comment]
I'm interested in contributing. Could you provide a little more detail on exactly what should be accomplished to resolve this issue?

**Comment by AndriySvyryd** [comment]
@KaloyanIT You need to:

1. Modify `ConflictingRelationshipNavigation` in `CoreStrings.resx`.
1. Run custom tool on `CoreStrings.Designer.tt`
1. Fix calling code
