### ISSUE TITLE
DebugView.LongView has odd ProductVersion (perhaps)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#21411]
A "Long" debugview from EF Core 5 preview 5 conatins:

```
Annotations: 
  ProductVersion: 2.2.0-rtm-35687

```
Is that by design?

EF Core version: 5.0 preview5
Database provider: N/A 
Target framework: .NET Core 3.1

**Comment by AndriySvyryd** [comment]
Are you looking at a model built from a migrations snapshot?

**Comment by ErikEJ** [comment]
@AndriySvyryd I dont think so: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efpt/EFCoreModelBuilder.cs#L44

**Comment by ajcvickers** [comment]
@ErikEJ I have not been able to reproduce this. Is the context or model being created in some unusual way?

**Comment by ErikEJ** [comment]
I am using the Design helpers, as you can see in the linked code...

**Comment by ErikEJ** [comment]
Maybe @bricelam  can help?

**Comment by ErikEJ** [comment]
Ah, the model is reverse engineered, and the product version annotation is scaffolded (old bug, fixed now)
