### ISSUE TITLE
EF Core 5 Preview: Not Handling Unique Keys when Reverse Engineering DB

### ISSUE THREAD

**Issue by jryutzy** [dotnet/efcore#21425]
In the EF Core Preview 5 release, a column that has a Unique Key is not getting generated correctly when reverse engineering by using Scaffold-DbContext
![image](https://user-images.githubusercontent.com/67274124/85882329-19e6c200-b7ad-11ea-8a7c-07dfdf07a8b8.png)

![image](https://user-images.githubusercontent.com/67274124/85882586-8661c100-b7ad-11ea-99a4-c25ad7fc5236.png)

EF Core 5 Preview 6.20312 is on left and EF Core 3.1.5 is on right

Notice EF Core 5 is not generating this in model builder
                entity.HasIndex(e => e.Value)
                    .HasName("Country_UK")
                    .IsUnique();

**Comment by ajcvickers** [comment]
@jryutzy Please post the schema of the table that is being reverse engineered.

**Comment by jryutzy** [comment]
/****** Object:  Table [App].[Country]    Script Date: 6/30/2020 8:07:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [App].[Country](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Value] [varchar](50) NOT NULL,
	[Description] [varchar](250) NOT NULL,
	[CreateUser] [varchar](163) NOT NULL,
	[CreateDate] [datetime2](7) NOT NULL,
	[CreateProcess] [varchar](100) NOT NULL,
	[ModifyUser] [varchar](163) NOT NULL,
	[ModifyDate] [datetime2](7) NOT NULL,
	[ModifyProcess] [varchar](100) NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [Country_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [Country_UK] UNIQUE NONCLUSTERED 
(
	[Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [App].[Country] ADD  DEFAULT (getdate()) FOR [CreateDate]
GO

ALTER TABLE [App].[Country] ADD  DEFAULT (getdate()) FOR [ModifyDate]
GO

ALTER TABLE [App].[Country] ADD  DEFAULT ((1)) FOR [Active]
GO

**Comment by ajcvickers** [comment]
@jryutzy I am not able to reproduce this. I get the following scaffolded. What edition and version of SQL Server are you reverse engineering from?

```C#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>(entity =>
            {
                entity.ToTable("Country", "App");

                entity.HasIndex(x => x.Value)
                    .HasName("Country_UK")
                    .IsUnique();

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasViewColumnName("ID");

                entity.Property(e => e.Active)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateProcess)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.ModifyDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyProcess)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Value)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }
```

**Comment by jryutzy** [comment]
Are you using EF Core 5 Preview? If so, what build?

**Comment by ajcvickers** [comment]
@jryutzy Also using 15.0. I tried it with the daily build and it worked. Then I rolled back to preview 6 to check it there and it still worked. Output above is from preview 6. Output on #21470 is from the daily build.

**Comment by ErikEJ** [comment]
Triple check that you are scaffolding from the correct database..

**Comment by jryutzy** [comment]
I run below from PMC
Scaffold-DbContext "Server=localhost;Database=Demo;Persist Security Info=False;User ID=sa;Password=removed" Microsoft.EntityFrameworkCore.SqlServer -Schemas App -DataAnnotations -UseDatabaseNames -OutputDir zGenerated_Code -Context DemoContext -Namespace Lab.Model

or below from PS
dotnet ef dbcontext scaffold "Server=localhost;Database=Demo;Persist Security Info=False;User ID=sa;Password=removed" Microsoft.EntityFrameworkCore.SqlServer --data-annotations --use-database-names --output-dir zGenerated_Code --context DemoContext_dncli --namespace Lab.Model --no-onconfiguring --table Country

Then it does not generate below
   entity.HasIndex(x => x.Value)
                    .HasName("Country_UK")
                    .IsUnique();

Because it is putting the index on the class since I'm using DataAnnotations
![image](https://user-images.githubusercontent.com/67274124/86263048-a9fe8000-bb8e-11ea-960d-c453c37abc61.png)

**Comment by ErikEJ** [comment]
So there is no issue, the configuration appears as Data Annotation !?

**Comment by jryutzy** [comment]
Correct Erik
