### ISSUE TITLE
Making a sub-query inside a projection from a filtered Queryable results in all the results being added to a single object.

### ISSUE THREAD

**Issue by JulioPablo** [dotnet/efcore#21434]
Say you've got a `Customer` entity which has a one to many relation to a `CustomerTransacion` entity.

`CustomerTransaction` has a Date column, in this case I´d like to get all the customer and their transactions for a given month, so for example I´d like a list with all the customer who had a transaction made in the month of June and I also want all their transactions from June. This the approach I initially took;

``` C#
//Get All Customers and their transactions within the current month.
            var today = DateTime.UtcNow;
            var fromDate = new DateTime(today.Year, today.Month, 1);
            var toDate = fromDate.AddMonths(1).AddDays(-1);

            var transactionsQuery = _context.CustomerTransactions
                    .Where(ct => ct.Date >= fromDate && ct.Date <= toDate);

            var customersQuery = transactionsQuery.Select(ct=> ct.Customer).Distinct();
            var filteredTransacionIds = transactionsQuery.Select(t => t.Id);

            var buggyResult = customersQuery.Select(c => new MonthlyCustomersTransactionsListVM()
            {
                CustomerId = c.Id,
                Transactions = c.Transactions.Where(t => filteredTransacionIds.Contains(t.Id)).Select(t => new MonthlyCustomersTransactionsVM()
                {
                    CustomerId = c.Id,
                    TransactionId = t.Id,
                    Amount = t.Amount,
                    Date = t.Date
                })
            }).ToList();
```

The issue here is that instead of getting a list of customer VMs with their corresponding transactions, I get a single customerVM  with all the transactions from all other customers.

I found the following query worked instead

``` C#
            var customersIds = customersQuery.Select(c => c.Id);
            var correctResult = _context.Customers.Where(c => customersIds.Contains(c.Id)).Select(c => new MonthlyCustomersTransactionsListVM()
            {
                CustomerId = c.Id,
                Transactions = c.Transactions.Where(t => filteredTransacionIds.Contains(t.Id)).Select(t => new MonthlyCustomersTransactionsVM()
                {
                    CustomerId = c.Id,
                    TransactionId = t.Id,
                    Amount = t.Amount,
                    Date = t.Date
                })
            }).ToList();
```

I´ve created a repo with a project where this behavious can be reproduced, [https://github.com/JulioPablo/EFCore-PgSql-Projection-Bug-Demo](https://github.com/JulioPablo/EFCore-PgSql-Projection-Bug-Demo)

The queries are in `HomeController.cs` in case anyone wants to run it and check it out for themselves, you can set a breakpoint and check the results that come back from the database.

### Further technical details

EF Core version: 3.1.5
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 
Target framework: NET Core 3.1
Operating system: Windows 8/10
IDE: Visual Studio 2019

**Comment by sdanyliv** [comment]
I think, `Distinct` on whole entity is problem here. It is not trivial task to support in projection `c.Transactions` navigation after this method.
Think about that and maybe you do not need `Distinct` on ALL columns.

And If you really cares about performance, you should rewrite your query using client side grouping.
```cs
            var today = DateTime.UtcNow;
            var fromDate = new DateTime(today.Year, today.Month, 1);
            var toDate = fromDate.AddMonths(1).AddDays(-1);

            var transactionsQuery = _context.CustomerTransactions
                    .Where(ct => ct.Date >= fromDate && ct.Date <= toDate);

            var transactions = transactionsQuery.Select(t => new MonthlyCustomersTransactionsVM()
                {
                    CustomerId = c.Id,
                    TransactionId = t.Id,
                    Amount = t.Amount,
                    Date = t.Date
                }).ToList();

            var correctResult = transactions
               .GroupBy(t => t.CustomerId)
               .Select(g => new MonthlyCustomersTransactionsListVM()
               {
                   CustomerId = g.Key,
                   Transactions = g.ToArray()
               })ToList();
```
No joins, single optimal query.

**Comment by JulioPablo** [comment]
Well, I think you´re taking the example literally, I´m the actual use case there are more properties on both sides, for example the customer is not just a entity with an Id and there is some sorting done on on the projected entities, so doing a client side `GroupBy` does not make sense as that'd be loading the entire table into memory before doing the sort.

Not sure about `Distinct` being the issue, as that is still being used on the work around. 

What I'm really trying to report here is that there is some really odd behavior with the first showcased query, something that at least I consider a bug.

**Comment by sdanyliv** [comment]
About `Distinct`, not sure how EF guys handles that but it can be a problem. I'm also developing LINQ parser, so I know what is hard to translate optimally.

I have free time so, there is "better" solution:
```cs
            var today = DateTime.UtcNow;
            var fromDate = new DateTime(today.Year, today.Month, 1);
            var toDate = fromDate.AddMonths(1).AddDays(-1);

            Expression<Func<CustomerTransaction, bool>> transactionFilter = 
                 ct => ct.Date >= fromDate && ct.Date <= toDate;

            var customersQuery = _context.Customers.Where(c => c.Transactions.Any(transactionFilter));
            var buggyResult = customersQuery.Select(c => new MonthlyCustomersTransactionsListVM()
            {
                CustomerId = c.Id,
                Transactions = c.Transactions.Where(transactionFilter).Select(t => new MonthlyCustomersTransactionsVM()
                {
                    CustomerId = c.Id,
                    TransactionId = t.Id,
                    Amount = t.Amount,
                    Date = t.Date
                })
            }).ToList();
```
As result you have non optimal working SQL.

**Comment by JulioPablo** [comment]
Again, you seem to be focusing on the query versus what the issue is really about, the unexpected behavior of all the relationships being dumped on a single entry.

I´m also not sure about branding SQL as non-optimal without looking at the actual SQL that EF has compiled.
Maybe this will make the issue clearer.

![image](https://user-images.githubusercontent.com/33587721/85961926-139e4480-b96b-11ea-99e0-899bcd3565a7.png)
![image](https://user-images.githubusercontent.com/33587721/85961982-59f3a380-b96b-11ea-9aec-12afa5e1ae59.png)

**Comment by maumar** [comment]
I was able to repro this in 3.1 and also verified that it works correctly in current bits.
