### ISSUE TITLE
EnsureCreated throws 'Index was outside the bounds of the array.' EF Core 5

### ISSUE THREAD

**Issue by Shumigaj** [dotnet/efcore#21430]
I got 'Index was outside the bounds of the array.' issue after update application to use EF Core 5 Preview 6.

One entity from my context inherits a base class with string property. EnsureCreated fails because of it.

Code sample: [GitHub](https://github.com/Shumigaj/Samples/tree/1701d077036e17e40a170abc87ed7dbd3a7bcb14) App.cs line 46

[Stackoverflow issue](https://stackoverflow.com/questions/62612161/ensurecreated-throws-index-was-outside-the-bounds-of-the-array-ef-core-5)

### Further technical details

EF Core version: 5.0.0-preview.6.20312.4
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5
Operating system: Android

**Comment by ajcvickers** [comment]
Duplicate of #18793

**Comment by r-work** [comment]
Same issue here, using **5.0.0-rc.1.20451.13**, works on Windows but breaking on Android in OnModelCreating when calling **modelBuilder.Entity(type, entity =>** ...

**Comment by ajcvickers** [comment]
@roji @JeremyLikness We closed this as a duplicate of #18793, which itself was closed as external. Can we check where we actually ended up with this in 5.0?
