### ISSUE TITLE
Support grouping by an entity type

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#21447]
Group by supports grouping on scalars and anonymous types. It should also support grouping on an entity type. This should behave the same way as grouping on an anonymous type. The translation to SQL appears to be unproblematic.

This is a LINQ to SQL migration hurdle.

Query code:

    _ = (from c in ctx.TestChildren
         group c by c.TestParent into g
         select new { g.Key, Count = g.Count() }).ToList();

Exception:

```
System.InvalidOperationException: 'The LINQ expression 'DbSet<TestChild>()
    .LeftJoin(
        inner: DbSet<TestParent>(), 
        outerKeySelector: t => EF.Property<Nullable<int>>(t, "TestParentID"), 
        innerKeySelector: t0 => EF.Property<Nullable<int>>(t0, "ID"), 
        resultSelector: (o, i) => new TransparentIdentifier<TestChild, TestParent>(
            Outer = o, 
            Inner = i
        ))
    .GroupBy(
        keySelector: t => t.Inner, 
        elementSelector: t => t.Outer)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

Rewriting the query to an anonymous type allows it to execute, but it does not return a trackable entity:

    _ = (from c in ctx.TestChildren
         group c by new { c.TestParent.ID, c.TestParent.Name } into g
         select new { g.Key, Count = g.Count() }).ToList();

I believe this issue is *not* a duplicate: https://github.com/dotnet/efcore/issues/17653

**Comment by ajcvickers** [comment]
@GSPP Why is this not a duplicate?

**Comment by GSPP** [comment]
Hm, funnily, it is an exact duplicate. When I looked at it the first time I understood the issue differently. Closing.
