### ISSUE TITLE
InMemoryDb Improvement: distinguish between same entity types on different dbcontexts

### ISSUE THREAD

**Issue by pburdynski** [dotnet/efcore#21453]
Problem:
In modular monolyth architecture it is good practice to use one dbcontext per module (with its own db schema). It helps to decouple modules on infrastructure layer. However, there are cases when it is useful to use all of these dbcontexts at once - integration tests.
When testing integration between modules it makes sense to use in memory database. There is one problem though. If you are using the same Entity type across all of these contexts (i.e. InboxOutbox pattern is implemented and every module has its own Inbox/Outbox tables), In-memory database will treat all of this entities as one. It is because EFCore stores entity definitions in dictionary where the type of the entity is the key.

Possible solution:
I think it is good idea to define key of entity as some kind of concatenation of schema name and entity type, so that In-memory db will be able to properly interpret what is separate entity and what isn't.

**Comment by ajcvickers** [comment]
@pburdynski The in-memory database is not a relational database and the tables do not have schemas, since this is a relational concept. We recommend [using a relational database for testing](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/).
