### ISSUE TITLE
Generating a model from an existing database

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#21478]
Trying to generate code/model from existing database objects. I run the below command to achieve the purpose. However it fails with "Build Started... Build failed." message. I don't see any error log files to get some more insight. What am I be missing? I am using newly built EF Core Provider for Informix. This is not yet available on Nuget (as I am still developing). The MyApp.csproj contains all the details about the Provide name and location. It creates bin and obj folders, obj folder has few metadata files but doesn't help to provide any info about error!

D:\scaffold>dotnet ef dbcontext scaffold "Database=ifmxefcoredb1; server=lo_informix1410; UID=informix; PWD=xxxx" Informix.EntityFramework.Core -o Models --project MyApp.csproj

Build started...
Build failed.

D:\scaffold>

Output of "dotnet ef -h" below

D:\scaffold>dotnet ef -h
Entity Framework Core .NET Command-line Tools 3.1.5

Usage: dotnet ef [options] [command]

Options:
  --version        Show version information
  -h|--help        Show help information
  -v|--verbose     Show verbose output.
  --no-color       Don't colorize output.
  --prefix-output  Prefix output with level.

Commands:
  database    Commands to manage the database.
  dbcontext   Commands to manage DbContext types.
  migrations  Commands to manage migrations.

Use "dotnet ef [command] --help" for more information about a command.

**Comment by smitpatel** [comment]
`-v` switch can help seeing more output. Make sure you can build your project using `dotnet build`

**Comment by deokershesh** [comment]
Thanks smitpatel, that helped a bit to get more info. It seems I also have to provide skelton .cs file. Now I created program1.cs as follows and then it proceeds but reports below errors!

Program1.cs:
----------
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace EFCoreSql
{
    class Program
    {
        static void Main(string[] args)
        {
  
        }
    }
}

Errors : When "dotnet ef dbcontext scaffold "Database=sheshefcoredb1; server=lo_informix1410;UID=informix; PWD=xxxx" Informix.EntityFramework.Core -o Models --project MyApp.csproj -v" command is run from CLI.

[System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.](url)

**Comment by smitpatel** [comment]
SemanticVersionComparer is in EFCore.Relational in 5.0 & EFCore in 3.1
Make sure you are not mixing different versions.

**Comment by deokershesh** [comment]
@smitpatel, could you provide little more info please? What do I need to look across my projects/files to confirm its being mixed and any suggestions you may have to address it.

**Comment by deokershesh** [comment]
I think the same issue is reported as part of ticket https://github.com/dotnet/efcore/issues/20517, I couldn't quite get about  solution though!

**Comment by deokershesh** [comment]
Still looking for solution... providing some more info, if this helps to provide any more pointers for resolution! I also changed, all my project files target framework to "netcoreapp3.1" (earlier some of them were netstandard2.1) but still problem continues! Any help to resolve the issue is greatly appreciated.

1. Attaching the MyApp.csproj.txt file which I am using.
2. Command used is, "dotnet ef dbcontext scaffold "Database=sheshefcoredb1; server=lo_informix1410;UID=informix; PWD=xxxx" Informix.EntityFramework.Core -o Models --project MyApp.csproj -v"
3. In this project file, following rules seems to make difference!, as it changes the error messages!
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

If above detail is used it reports error, " System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore' "

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-preview.5.20227.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

If above detail is used it reports error, " The EF Core tools version '3.1.5' is older than that of the runtime '5.0.0-preview.5.20227.5'. Update the tools for the latest features and bug fixes. "

If I remove the above details from MyApp.csproj file, then it report error, "Microsoft.EntityFrameworkCore.Tools.CommandException: Your startup project 'MyApp' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again. "

[MyApp.csproj.txt](https://github.com/dotnet/efcore/files/4863389/MyApp.csproj.txt)

**Comment by ajcvickers** [comment]
@deokershesh You're using 3.1.5 of the design package and, for some reason, 5.0 preview 3 for the other packages.

**Comment by deokershesh** [comment]
Unfortunately, problem still continues, I would be more than happy to provide all information, regarding how I am building ".NET Core", ".NET EF Core" and any other artifacts needed, if that would help to point the issues that I am facing. Somehow assembly version incompatibilities seems to be a bit of issue in general.

**Comment by deokershesh** [comment]
Never mind, seems to have resolved the assembly version issues by making certain changes in global.json and using the correct version of "dotnet". However I am facing another problem related to scaffolding, which I will mention in new ticket.
