### ISSUE TITLE
RelationalEventId.QueryClientEvaluationWarning is missing

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#21479]
The documentation points to a way to make client evaluations throw:

    optionsBuilder
        .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFQuerying;Trusted_Connection=True;")
        .ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning));

The `RelationalEventId.QueryClientEvaluationWarning` member is missing, though. The private enum does contain a `QueryClientEvaluationWarning` member, though.

https://github.com/dotnet/efcore/blob/3e5ee6c5deb9ad147058c5f9fa4c21a638306840/src/EFCore.Relational/Diagnostics/RelationalEventId.cs#L76

This is as of EF Core 5.0 preview 6.

**Comment by smitpatel** [comment]
The documentation clearly says that
> The following section applies to EF Core versions before 3.0.
