### ISSUE TITLE
Roadmap EF 7.0.0

### ISSUE THREAD

**Issue by Nebelkraehe** [dotnet/efcore#2147]
Hi there,

I just wanted to ask if there´s any roadmap or time schedule for the 7.0.0 release?
Thanks.

**Comment by Eilon** [comment]
There's some good info and further links on the wiki: https://github.com/aspnet/EntityFramework/wiki/What-is-EF7-all-about

As far as schedule, the schedule is the same as for the rest of ASP.NET 5, but we have not yet announced any dates publicly.

**Comment by Nebelkraehe** [comment]
Thank you very much.
