### ISSUE TITLE
Support --output-file arg for "dotnet ef dbcontext scaffold"

### ISSUE THREAD

**Issue by schnerring** [dotnet/efcore#21492]
I use  `dotnet ef dbcontext scaffold` for `DbContext` generation and make use of the `--output-dir` and `--no-onconfiguring` parameters. In my data project I have the following files:

* `MyDbContext.cs` (generated by `dotnet-ef`)
* `MyDbContext.Customizations.cs` (manual changes like overriding `OnConfiguring`)

I would rather have something like an `--out-file` parameter:

* `MyDbContext.Generated.cs` (generated by `dotnet-ef`)
* `MyDbContext.cs` (manual changes)

I feel like this is a convention used by many e.g. code cleanup tooling ignoring `*.Generated.cs` files by default.

I'm sure there's reasons but I must say it also feels weird that `--context-dir` and `--output-dir` are relative to `--project` and not relative to the execution context.

**Comment by ErikEJ** [comment]
>> code cleanup tooling ignoring *.Generated.cs files by default.

Can you provide an example of that? It is more likely something like "auto-generated" inside the file that causes this.

**Comment by schnerring** [comment]
> Can you provide an example of that? It is more likely something like "auto-generated" inside the file that causes this.

You're right, things inside files also affect tooling but so do file names.

[JetBrains Rider - Partly disable code inspection for generated code](https://www.jetbrains.com/help/rider/Code_Analysis__Configuring_Warnings.html#exclude_generated)

> You can also configure the list of files, folders, file masks, and regions that contain generated code. For these items, JetBrains Rider runs only those code inspections that check code for compiler errors and warnings. Some file masks and regions, which are typically used for generated code, for example *.designer.cs **are included in this list by default**, but you can change the default settings if necessary.

By default `*.Generated.cs` and `Reference.cs` files are also included.

ReSharper has the same defaults.

**Comment by ErikEJ** [comment]
I don't use R# or Rider, I use Visual Studio.

**Comment by bricelam** [comment]
It's possible to override this behavior.

First, enable compiling against the EF Core Design assembly:

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.5">
  <PrivateAssets>all</PrivateAssets>
  <!-- UNDONE: We want to include compile assets -->
  <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
</PackageReference>
```

Next, override the code generator to update the filenames:

``` cs
class MyModelGenerator : CSharpModelGenerator
{
    public MyModelGenerator(
        ModelCodeGeneratorDependencies dependencies,
        ICSharpDbContextGenerator cSharpDbContextGenerator,
        ICSharpEntityTypeGenerator cSharpEntityTypeGenerator)
        : base(dependencies, cSharpDbContextGenerator, cSharpEntityTypeGenerator)
    {
    }
            
    public override ScaffoldedModel GenerateModel(
        IModel model,
        ModelCodeGenerationOptions options)
    {
        var result = base.GenerateModel(model, options);
        
        foreach (var file in result.AdditionalFiles
            .Append(result.ContextFile))
        {
            file.Path = file.Path.Insert(
                file.Path.LastIndexOf('.'),
                ".Generated");
        }
        
        return result;
    }
}
```

Finally, override the design-time service with your implementation:

``` cs
class DesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection services)
        => services.AddSingleton<IModelCodeGenerator, MyModelGenerator>();
}
```
