### ISSUE TITLE
Keyless entity relationships to non keyless entities

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#21506]
I kicked off the discussion here: https://github.com/dotnet/efcore/discussions/21494

... Long story short, I just just want to know if this is even possible and if so what is the recommended approach for this type of thing?

It's not specifically required that this be the approach taken, I could just work from Query defined in the context itself that pulls from multiple sets but i'm not clear on how this "should" work.

Any advice, much appreciated.

**Comment by ajcvickers** [comment]
Discussion issue seems appropriate for this.
