### ISSUE TITLE
Query: Disallow FromSql on TPT/TPC

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#21508]
Currently it is likely to just fail abruptly. We can either make it work or throw when used on TPT hierarchy.

**Comment by smitpatel** [comment]
@AndriySvyryd - Throw or allow? Same would be applicable to TVFs

**Comment by AndriySvyryd** [comment]
Throw. FromSql support tracked by https://github.com/dotnet/efcore/issues/21627. TVF tracked by https://github.com/dotnet/efcore/issues/19970
