### ISSUE TITLE
Add overloads of UsingEntity() that could take a shared-type entity type

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#21505]

**Comment by smitpatel** [comment]
Part of #9914

**Comment by smitpatel** [comment]
- Remove exception throwing for STET when used during UsingEntity with clrType only.

**Comment by AndriySvyryd** [comment]
To clarify, the  only required overloads are:
```C#
EntityTypeBuilder UsingEntity(
    [NotNull] name,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureRight,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureLeft);

EntityTypeBuilder<TLeftEntity> UsingEntity(
    [NotNull] name,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureRight,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureLeft,
    [NotNull] Action<EntityTypeBuilder> configureAssociation);
```

If the specified `name` doesn't match any existing entity type then we'll assume the CLR type to be `Dictionary<string, object>` and create a new entity type

Other overloads will be implemented in https://github.com/dotnet/efcore/issues/21535

**Comment by smitpatel** [comment]
@AndriySvyryd - #21552 adds overloads of UsingEntity which takes only name when generic and takes name & type when non-generic, just like any other place configuring relationship with STET.

Above overloads are non-generic and does not take type either (which you mentioned that we will assume Dictionary<string, object>. Do you want to add them too?

**Comment by AndriySvyryd** [comment]
The reason I chose these is that I don't expect other types to be used for STETs frequently. But these can be added later, along with  #21535

**Comment by smitpatel** [comment]
#21552 fixed this
