### ISSUE TITLE
Reverse engineering with EF Core 5 preview 6 has unneeded changes (from 3.1)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#21520]
- but maybe it is a deliberate decision?

Before:

                entity.HasKey(e => new { e.OrganizationId, e.AspectType, e.AspectId });

After:

                entity.HasKey(x => new { x.OrganizationId, x.AspectType, x.AspectId });

Before:

                entity.HasIndex(e => e.AspectId);
                entity.HasIndex(e => new { e.OrganizationId, e.AssetId, e.AspectType })
                    .HasName("IX_AspectAsset_OrgId_AssetId_AspectType");

After:

                entity.HasIndex(x => x.AspectId);
                entity.HasIndex(x => new { x.OrganizationId, x.AssetId, x.AspectType })
                    .HasName("IX_AspectAsset_OrgId_AssetId_AspectType");

Before:

                entity.HasOne(d => d.Aspect)
                    .WithMany(p => p.AspectAssets)
                    .HasPrincipalKey(p => p.AspectId)
                    .HasForeignKey(d => d.AspectId)
                    .HasConstraintName("FK_AspectAsset_Aspect");

After:

               entity.HasOne(d => d.Aspect)
                    .WithMany(p => p.AspectAssets)
                    .HasPrincipalKey(x => x.AspectId)
                    .HasForeignKey(x => x.AspectId)
                    .HasConstraintName("FK_AspectAsset_Aspect");

### Further technical details

EF Core version: 5 preview 6
Database provider: SqlServer 
Target framework: .NET Core 3.1

**Comment by ajcvickers** [comment]
Note from triage: Ensure the reverse-engineered code stays consistent. It's okay for the migrations code to use "x" although ideally we should also preserve what we were doing in migrations before.
