### ISSUE TITLE
Add overloads of UsingEntity() that take advantage of conventions

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#21535]
We don't need this for 5.0, but it would be nice to add some sugar.

Each overload will have a version that takes a `Type`, a version that takes a name and a version that take neither (we'll assume the type is `Dictionary<string, object>` and generate the type name based on the related entity types). Also there'll be a version of each that returns the builder for the association entity type and one that takes it as a nested lambda as well as the non-generic flavor (~9 variations of each in total). I'll only show the `Type` with nested lambda overloads here for brevity.

```C#
EntityTypeBuilder<TLeftEntity> UsingEntity<TAssociationEntity>(
    [NotNull] Action<EntityTypeBuilder<TAssociationEntity>> configureAssociation);
```

We'll use the FKs found by convention if there's exactly one compatible FK to each of the entity types in the M2M. The PK will be configured as composite over those FKs, so in the simple case `configureAssociation` could be `null`

```C#
EntityTypeBuilder<TLeftEntity> UsingEntity<TAssociationEntity>(
    [NotNull] Action<ReferenceCollectionBuilder<TLeftEntity, TAssociationEntity>> configureRight,
    [NotNull] Action<ReferenceCollectionBuilder<TRightEntity, TAssociationEntity>> configureLeft,
    [NotNull] Action<EntityTypeBuilder<TAssociationEntity>> configureAssociation)
```

This one additionally allows to configure the FKs that we found. This version will throw immediately if the FKs are not found or are ambiguous.

**Comment by smitpatel** [comment]
Also consider overloads in https://github.com/dotnet/efcore/issues/21505#issuecomment-654449840

@AndriySvyryd wrote
To clarify, the only required overloads are:
```C#
EntityTypeBuilder UsingEntity(
    [NotNull] name,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureRight,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureLeft);

EntityTypeBuilder<TLeftEntity> UsingEntity(
    [NotNull] name,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureRight,
    [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureLeft,
    [NotNull] Action<EntityTypeBuilder> configureAssociation);
```
If the specified name doesn't match any existing entity type then we'll assume the CLR type to be `Dictionary<string, object>` and create a new entity type

**Comment by softlion** [comment]
Can we have a sample plz ?
