### ISSUE TITLE
SqlBatchBuilder - force batch size of 1

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2154]
Hi, is there any way to force the SqlBatchBuilder to always have a batch size of 1?
In my migrationssqlgenerator I currently have to override each operation and add 

```
builder.EndBatch();
```

Basically it seems like migrations ignores the MaxbatchSize setting, but I could easily be doing something wrong

**Comment by bricelam** [comment]
I don't think the batch builder implementation ever got "finished". Suppressing transactions also does not work as far as I know.

**Comment by ErikEJ** [comment]
@bricelam Thanks, I will cope for now, and wiat for it to be "finished" :calendar:

**Comment by bricelam** [comment]
Re-assigning to me since this relates to #2739

**Comment by bricelam** [comment]
Closing this as superseded by #2739. Migrations is the only thing using `SqlBatchBuilder`, so it will most likely go away when we switch to single-statement commands by default.
