### ISSUE TITLE
Ef core generates a query for each row after AddRange() then SaveChanges()

### ISSUE THREAD

**Issue by amro93** [dotnet/efcore#21544]
workflowStateRepository.CreateMany(wfStates);
await workflowStateRepository.SaveAsync();

public virtual void CreateMany(IEnumerable<T> entities)
        {
            if (entities is null)
            {
                throw new ArgumentNullException(nameof(entities));
            }
            SetCreateEntityDetails(ref entities);
            Set.AddRange(entities);
        }

result query:
   
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (78ms) [Parameters=[@p0='string' (Size = 4000), @p1='user.test' (Size = 100), @p2='2020-07-07T10:42:55' (Nullable = true), @p3=NULL (DbType = DateTime2), @p4='1st' (Size = 4000), @p5='41c2c594-0609-49fc-aa01-3f574803f3b1' (Nullable = false) (Size = 100), @p6='False', @p7='1st Step' (Nullable = false) (Size = 100), @p8='Automatic' (Nullable = false) (Size = 50), @p9='Start' (Nullable = false) (Size = 50), @p10=NULL (Size = 100), @p11=NULL (DbType = DateTime2), @p12=NULL (Size = 4000), @p13='Normal' (Nullable = false) (Size = 50), @p14='19'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [WorkflowState] ([BusinessComments], [CreatedBy], [CreatedDate], [DeletedDate], [Description], [Guid], [IsDeleted], [Name], [PickUserMode], [Status], [UpdatedBy], [UpdatedDate], [WorkflowDiagram], [WorkflowStateType], [WorkflowVersionId])
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14);
      SELECT [Id]
      FROM [WorkflowState]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[@p0='string' (Size = 4000), @p1='user.test' (Size = 100), @p2='2020-07-07T10:42:55' (Nullable = true), @p3=NULL (DbType = DateTime2), @p4='2nd' (Size = 4000), @p5='a29d8d49-84d3-4514-a41a-da78e980714f' (Nullable = false) (Size = 100), @p6='False', @p7='2nd Step' (Nullable = false) (Size = 100), @p8='Automatic' (Nullable = false) (Size = 50), @p9='Intermediate' (Nullable = false) (Size = 50), @p10=NULL (Size = 100), @p11=NULL (DbType = DateTime2), @p12=NULL (Size = 4000), @p13='Normal' (Nullable = false) (Size = 50), @p14='19'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [WorkflowState] ([BusinessComments], [CreatedBy], [CreatedDate], [DeletedDate], [Description], [Guid], [IsDeleted], [Name], [PickUserMode], [Status], [UpdatedBy], [UpdatedDate], [WorkflowDiagram], [WorkflowStateType], [WorkflowVersionId])
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14);
      SELECT [Id]
      FROM [WorkflowState]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[@p0='string' (Size = 4000), @p1='user.test' (Size = 100), @p2='2020-07-07T10:42:55' (Nullable = true), @p3=NULL (DbType = DateTime2), @p4='3rd' (Size = 4000), @p5='8530b3d5-4d0e-467d-ad1c-bbead04102ff' (Nullable = false) (Size = 100), @p6='False', @p7='3rd Step' (Nullable = false) (Size = 100), @p8='Automatic' (Nullable = false) (Size = 50), @p9='End' (Nullable = false) (Size = 50), @p10=NULL (Size = 100), @p11=NULL (DbType = DateTime2), @p12=NULL (Size = 4000), @p13='Normal' (Nullable = false) (Size = 50), @p14='19'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [WorkflowState] ([BusinessComments], [CreatedBy], [CreatedDate], [DeletedDate], [Description], [Guid], [IsDeleted], [Name], [PickUserMode], [Status], [UpdatedBy], [UpdatedDate], [WorkflowDiagram], [WorkflowStateType], [WorkflowVersionId])
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14);
      SELECT [Id]
      FROM [WorkflowState]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();


```### Steps to reproduce

<!--
What steps can we follow to reproduce the issue?

We ❤ code! Include a complete code listing or attach a simplified project

``` C#
public async Task<WorkflowVersionDto> CreateAsync(CreateWorkflowVersionDto dto)
        {
            var entity = workflowVersionDtoMap.DtoToEntity(dto);
            // TODO: entity mapping validation
            // TODO: enhance query below
            var wfStates = entity.WorkflowStates?.ToList();
            entity.WorkflowStates = null;

            await workflowVersionRepository.CreateAsync(entity);
            await workflowVersionRepository.SaveAsync();

            if (wfStates != null)
            {
                List<WorkflowDueActionType> actions = new List<WorkflowDueActionType>();
                List<WorkflowDueTime> dueTimes = new List<WorkflowDueTime>();
                List<WorkflowTransition> workflowTransitions = new List<WorkflowTransition>();
                List<WorkflowStateGroup> workflowStateGroups = new List<WorkflowStateGroup>();
                List<WorkflowStateUser> workflowStateUsers = new List<WorkflowStateUser>();

                // separate nested object to be saved on another object
                foreach (var state in wfStates)
                {
                    if (state.WorkflowDueActionTypes != null)
                    {
                        state.WorkflowDueActionTypes.ToList().ForEach(d => d.WorkflowState = state);
                        actions.AddRange(state.WorkflowDueActionTypes);
                        state.WorkflowDueActionTypes = null;
                    }
                    if (state.WorkflowDueTime != null)
                    {
                        state.WorkflowDueTime.WorkflowState = state;
                        dueTimes.Add(state.WorkflowDueTime);
                        state.WorkflowDueTime = null;
                    }

                    if (state.BeginWorkflowTransitions != null)
                    {
                        state.BeginWorkflowTransitions.ToList().ForEach(t => t.BeginWorkflowState = state);
                        workflowTransitions.AddRange(state.BeginWorkflowTransitions);
                        state.BeginWorkflowTransitions = null;
                    }

                    if (state.WorkflowStateGroups != null)
                    {
                        state.WorkflowStateGroups.ToList().ForEach(g => g.WorkflowState = state);
                        workflowStateGroups.AddRange(state.WorkflowStateGroups);
                        state.WorkflowStateGroups = null;
                    }

                    if (state.WorkflowStateUsers != null)
                    {
                        state.WorkflowStateUsers.ToList().ForEach(u => u.WorkflowState = state);
                        workflowStateUsers.AddRange(state.WorkflowStateUsers);
                        state.WorkflowStateUsers = null;
                    }
                }
               
               // Here =>>> expecting 100s of WfState objects
                workflowStateRepository.CreateMany(wfStates);
                await workflowStateRepository.SaveAsync(); // save each row in a single query

                // then
                workflowDueActionTypeRepository.CreateMany(actions); // save all rows in a single query

                workflowDueTimeRepository.CreateMany(dueTimes); // save all rows in a single query

                workflowTransitionRepository.CreateMany(workflowTransitions); // save all rows in a single query

                workflowStateGroupRepository.CreateMany(workflowStateGroups); // save all rows in a single query

                workflowStateUserRepository.CreateMany(workflowStateUsers); // save all rows in a single query

                await workflowStateRepository.SaveAsync(); // save all rows in a single query
            }
            return await GetWithStatesAsync(entity.Id);
        }
```

Got Exceptions? Include both the message and the stack trace

For `dotnet ef` and PMC, share the --verbose output
-->

### Further technical details

EF Core version: 3.1.5
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
@amro93 although a separate INSERT is sent for each added row, these INSERTs are batched in a single round-trip, providing good performance. It's also necessary to have separate INSERTs in order to get any database-generated values (e.g. identity) back from the database, and populate them in the inserted entities. Do you have a particular problem or alternative implementation in mind here?

**Comment by amro93** [comment]
> @amro93 although a separate INSERT is sent for each added row, these INSERTs are batched in a single round-trip, providing good performance. It's also necessary to have separate INSERTs in order to get any database-generated values (e.g. identity) back from the database, and populate them in the inserted entities. Do you have a particular problem or alternative implementation in mind here?

@roji thank you for the fast response,

its OK if the query is sent on a single round trip with multiple inserts, but I'd expect the logger to log this row "info: Microsoft.EntityFrameworkCore.Database.Command[20101]" once, which indicates that the transaction has been started.
but if you have a deep look on the included query you will notice that the transaction initialized multiple times for each single row, which I believe its not a single round trip

how ever the next lines of the code will be translated into the query below which make sense for a single round trip

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (46ms) [Parameters=[@p0='SendMailDueActionType' (Nullable = false) (Size = 100), @p1='54', @p2='this is over due test mail body' (Nullable = false) (Size = 4000), @p3='False', @p4='AssignedUser' (Nullable = false) (Size = 100), @p5='over due Task ' (Nullable = false) (Size = 4000), @p6='MoveToStateDueActionType' (Nullable = false) (Size = 100), @p7='54', @p8='41c2c594-0609-49fc-aa01-3f574803f3b1' (Size = 4000), @p9='53', @p10='54', @p11='Hours' (Nullable = false) (Size = 20), @p12='2', @p13='user.test' (Size = 100), @p14='2020-07-07T11:08:21' (Nullable = true), @p15='1', @p16='53', @p17='user.test' (Size = 100), @p18='2020-07-07T11:08:21' (Nullable = true), @p19='2', @p20='54', @p21='53', @p22='user.test' (Size = 100), @p23='2020-07-07T11:08:20' (Nullable = true), @p24='54', @p25='54', @p26='user.test' (Size = 100), @p27='2020-07-07T11:08:20' (Nullable = true), @p28='55'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [WorkflowDueActionType] ([Discriminator], [WorkflowStateId], [Body], [IsBodyHtml], [MailReceiverType], [Subject])
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5);
      SELECT [Id]
      FROM [WorkflowDueActionType]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
      
      INSERT INTO [WorkflowDueActionType] ([Discriminator], [WorkflowStateId], [NextWorkflowStateGuid], [NextWorkflowStateId])
      VALUES (@p6, @p7, @p8, @p9);
      SELECT [Id]
      FROM [WorkflowDueActionType]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
      
      INSERT INTO [WorkflowDueTime] ([WorkflowStateId], [DueTimeType], [DueTimeValue])
      VALUES (@p10, @p11, @p12);
      DECLARE @inserted3 TABLE ([Id] bigint, [_Position] [int]);
      MERGE [WorkflowStateGroup] USING (
      VALUES (@p13, @p14, @p15, @p16, 0),
      (@p17, @p18, @p19, @p20, 1)) AS i ([CreatedBy], [CreatedDate], [GroupId], [WorkflowStateId], _Position) ON 1=0
      WHEN NOT MATCHED THEN
      INSERT ([CreatedBy], [CreatedDate], [GroupId], [WorkflowStateId])
      VALUES (i.[CreatedBy], i.[CreatedDate], i.[GroupId], i.[WorkflowStateId])
      OUTPUT INSERTED.[Id], i._Position
      INTO @inserted3;
      
      SELECT [t].[Id] FROM [WorkflowStateGroup] t
      INNER JOIN @inserted3 i ON ([t].[Id] = [i].[Id])
      ORDER BY [i].[_Position];
      
      DECLARE @inserted5 TABLE ([Id] bigint, [_Position] [int]);
      MERGE [WorkflowTransition] USING (
      VALUES (@p21, @p22, @p23, @p24, 0),
      (@p25, @p26, @p27, @p28, 1)) AS i ([BeginWorkflowStateId], [CreatedBy], [CreatedDate], [EndWorkflowStateId], _Position) ON 1=0
      WHEN NOT MATCHED THEN
      INSERT ([BeginWorkflowStateId], [CreatedBy], [CreatedDate], [EndWorkflowStateId])
      VALUES (i.[BeginWorkflowStateId], i.[CreatedBy], i.[CreatedDate], i.[EndWorkflowStateId])
      OUTPUT INSERTED.[Id], i._Position
      INTO @inserted5;
      
      SELECT [t].[Id] FROM [WorkflowTransition] t
      INNER JOIN @inserted5 i ON ([t].[Id] = [i].[Id])
      ORDER BY [i].[_Position];

**Comment by amro93** [comment]
When I added large number of rows 1000+ ef core generated a huge query for a single round trip.
it seems that ef core will decide when to generate a single query for each row if the number of rows is less than a specific value which intended to improve the performance after all.

**Comment by roji** [comment]
@amro93 yeah, the SQL Server provider has a minimum below which it doesn't batch, because that has been shown to be less efficient - see #9270 for some more info on this. FWIW the PostgreSQL providers starting from two commands, so this is a provider-specific thing.
