### ISSUE TITLE
SQLite RevEng: Generated columns are missing

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#21557]
It looks like the metadata for generated (aka computed) columns is a little wonky and we miss them when scaffolding. I suspect the ADO.NET metadata APIs also need some updates.

**Comment by bricelam** [comment]
AFAICT, the only APIs that show them are:

* sqlite_master.sql (would have to parse the entire CREATE TABLE statement)
* pragma_table_xinfo where hidden = 2 (only shows name and type; computed sql and stored aren't exposed)

**Comment by roji** [comment]
FWIW I remember spending 5 minutes on this and giving up - cool that it's possible to do...

**Comment by bricelam** [comment]
Looks like STORED columns have a value of 3.
