### ISSUE TITLE
Produce Self Many-to-Many Relationship by default if have exactly 2 collection navigations to self

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#21568]
Currently if you have an entity type:

```C#
    public class A
    {
        public int Id { get; set; }

        public List<A> Bs { get; set; }
        public List<A> Cs { get; set; }
    }
```

We will not recognize Bs <-> Cs as a many-to-many. (You are free to configure it as that or as 2 1:N relationships as you wish, we just don't recognize it by default).

At the Design Meeting on July 8 2020 we decided to create this as an implicit many-to-many between Bs and Cs with a separate join entity.

**Comment by AndriySvyryd** [comment]
Poaching
