### ISSUE TITLE
Support for closed generic types?

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#21561]
I am having problems using closed generic types in a model like this:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClosedGenericSample
{
    public abstract class Vehicle
    {
    }

    public class Bike : Vehicle
    {
    }

    public class Car : Vehicle
    {
    }

    public abstract class Employee
    {
        Guid ID { get; set; }
    }

    public abstract class Employee<TCorporateVehicle>
        where TCorporateVehicle : Vehicle
    {
        public virtual TCorporateVehicle Vehicle { get; set; }
    }

    public class Manager : Employee<Car>
    {
    }

    public class Staff : Employee<Bike>
    {
    }
}

```
Should it be possible to use closed generic types in this way?

Can you refer to somewhere in the documentation, where it reads what you can and should do when using closed generic types?

Should I for instance map `Employee<Car>` and `Employee<Bike>` separately?

Does it matter, if Vehicle is an entity or an owned type?

If using closed generic types is not currently supported, are there some plans in this regard because it's really valuable when making non-trivial models?

I am using the newest EF Core, i.e. .net 5.0 Preview 6.

**Comment by ajcvickers** [comment]
@henrikdahl8240 Closed generics work the same way as any other type. There should be no issue mapping them, but we don't do anything special with them either.

**Comment by henrikdahl8240** [comment]
OK. But it's correct, that it didn't work with EF 6.4 isn't it, because here e.g. the above case may not work because the classes Manager and Staff cannot have its super classes?

**Comment by ajcvickers** [comment]
@henrikdahl8240 `Employee<TCorporateVehicle>` is not a closed generic type, so you won't be able to map it.

**Comment by henrikdahl8240** [comment]
No, I mean `Manager`, `Employee<Car>`, `Staff`, `Employee<Bike>` and `Employee`.

With EF 6.4 it doesn't work for me as the super class of `Manager` is `Employee<Car>` and of `Staff` is `Employee<Bike>`.

These two `Employee` generics are both closed, i.e. `Employee<Car>` and `Employee<Bike>`.

It doesn't work with EF 6.4.

It should work with EF Core.

Is that correctly understood, because actually I have only tried this specific case with EF 6.4, where it didn't work.

**Comment by ajcvickers** [comment]
@henrikdahl8240 Yes, it should work. (EF6 and EF Core are totally different code bases, so something not working in EF6 isn't usually a very useful piece of information when determining whether or not something will work with EF Core.)
