### ISSUE TITLE
Update Default Join Entity Type Property Names

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#21567]
At the moment, when we create properties to hold the FKs involved in an implicit many-to-many join entity, we define the names of those properties from "{ETSN}_{propName}" where {ETSN} = declaringEntityType.ShortName(), {propName} = the property's name on declaringEntityType, where declaringEntityType is in turn both of the two outer entities in the join and the properties are from that entity type's PK.

At the Design Meeting on July 8 we decided to update this to name the foreign properties whatever we use elsewhere in the code when creating FKs "behind the scenes".

**Comment by smitpatel** [comment]
If you just create the FK, then it will create appropriate FK properties automatically. So there is no need for M2M to even worry about property names. I think the convention to set PK for association entity for create FK values is tracked elsewhere.

**Comment by lajones** [comment]
@smitpatel Yes. But it doesn't do that at present - so I need to update the code. This is to keep track of that.

**Comment by AndriySvyryd** [comment]
Poaching
