### ISSUE TITLE
Different objects when I include entities with no tracking

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#21573]
I have a quiery like this:

```
Quaeryable<MyEntity> myIq = myDbContext.MyType;

myIq = myIq.Include(x => x.MyOtherTypeNavigation);

return myIq.AsNoTracking().ToListAsync().ConfigureAwait(false);
```

I have realize that if there are various rows as result, each object of navigation property, for a given ID, is different object. I mean:

MyType 1 with ID = 1; Navigation property ID = 1;
MyType 2 with ID = 2; Navigation property ID = 1;

In this case, the navigation properties are different objetcts, I would expected to be the same objects.

In fact, if I don't use AsNoTracking(), the objects are the same.

I don't know if this the desire behaviour, but if I have a repository and a client that uses this repsotory, the client expects to get the same object for a given entity and same ID. If the repository use AsNoTracking() to improve the performance, the client will get different objects.

In practice, this makes to the client, if wants to update an entity, he has to iterate all the list of entities of type MyType to update all the objects. If I would have the same object, with one update, it would be enough.

I wonder if it wouldn't be better to get always the same behaviour, to have the same object for a given type and the same ID.

I am using the version 3.1.5 of entity core.

Thanks.

**Comment by smitpatel** [comment]
No tracking queries don't perform identity resolution. See https://docs.microsoft.com/en-us/ef/core/querying/tracking#identity-resolution

In 5.0 we have add `AsNoTrackingWithIdentityResolution()` operator to perform identity resolution but not add entities to current change tracker to act like no tracking query. See #19877
