### ISSUE TITLE
Queryable methods of (element, index) lambda cannot be translated

### ISSUE THREAD

**Issue by kinosang** [dotnet/efcore#21583]
Failed when process LINQ expression for extension with type constraint

```
Processing of the LINQ expression 'DbSet<Posts>
    .Where(a => (Nullable<long>)((IDataEntity)a).Id < __request_Before_0)
    .OrderByDescending(a => ((IDataEntity)a).Id)
    .Take(__p_0)
    .Select((p, i) => new PostViewModel{ 
        Id = p.Id,
        ... 
    }
    )' by 'NavigationExpandingExpressionVisitor' failed.
```

It seems C# do casting for the generic types with constraint.

### Steps to reproduce

``` C#
public static IQueryable<T> ToPaginationResult<T, TEntity>(
    this IQueryable<TEntity> query,
    PaginationRequest request,
    Expression<Func<TEntity, int, T>> expression)
    where T : IDataEntity
    where TEntity : IDataEntity
{
    if (request.Before.HasValue)
    {
        query = query.Where(a => a.Id < request.Before);
    }

    query = query.OrderByDescending(a => a.Id);

    return query
        .Take(request.Size)
        .Select(expression);
}

db.Posts.ToPaginationResult(request, (p, i) => new PostViewModel{ 
    Id = p.Id,
    ... 
});
```

### Further technical details

EF Core version: 3.1.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1 3.1.301
Operating system: macOS 10.15
IDE: None

**Comment by ajcvickers** [comment]
@kinosang Several issues in this area have been fixed for the 5.0 previews. Please try with [preview 6](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0-preview.6.20312.4) and report back if you are still seeing this error.

**Comment by kinosang** [comment]
@ajcvickers nope, the same error occured on .NET Core `5.0.100-preview.6.20318.15` with efcore `5.0.0-preview.6.20312.4`

**Comment by kinosang** [comment]
Without the `.Select(expression)` transformation, it can work well.

So it is not bug about type constraint...

**Comment by smitpatel** [comment]
EF Core cannot translate `Select` with `(p. i)` lambdas. since there is no equivalent of `i` (the index) in databases.

**Comment by ajcvickers** [comment]
@smitpatel Candidate for better exception message?

**Comment by smitpatel** [comment]
We already throw better exception message indicating that translation of method has failed.
This is the list of methods which are not supported and we throw translation failure.
We can probably add in the docs pointed by fwlink why they are not translated.
https://github.com/dotnet/efcore/blob/26c8e1c9b80f2bccfd28537a6e7e0af68d5d928f/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs#L530-L544

**Comment by maumar** [comment]
Nothing to do here, closing
