### ISSUE TITLE
GROUP BY Date on DateTimeOffset doesn't seem to work

### ISSUE THREAD

**Issue by alexszym** [dotnet/efcore#21597]
I've been trying group and count records by date on a DateTimeOffset column. When I try it on a string column everything works as expected when I try to group by date, I get exceptions.

Is calling .Date not supported in .Net Core? Is there an equivalent somewhere for the TruncateTime db functions?

### Steps to reproduce

When I try to run the following code (using SQL Lite)

``` C#
                var records = await db.Records
                 .Select(x => x.CreatedUtc.Date)
                 .GroupBy(x => x)
                  .Select(x => new
                  {
                      Date = x.Key,
                      Count = x.Count(),
                  })
                 .ToListAsync();
```

I get
```
System.InvalidOperationException: 'The LINQ expression 'DbSet<Record>
    .GroupBy(
        source: a => a.CreatedUtc.Date, 
        keySelector: a => a.CreatedUtc.Date)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

```
-->

### Further technical details

EF Core version: 3.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlLite)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.5)

**Comment by smitpatel** [comment]
Sqlite cannot translate `DateTimeOffset.Date` to server. See https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations#query-limitations

**Comment by alexszym** [comment]
I've swapped to a DateTime field and everything is working 👍 

I was using a workaround from https://github.com/dotnet/efcore/issues/10784

```foreach (var entityType in builder.Model.GetEntityTypes())
                    {
                        var properties = entityType.ClrType.GetProperties().Where(p => p.PropertyType == typeof(DateTimeOffset)
                                                                                    || p.PropertyType == typeof(DateTimeOffset?));
                        foreach (var property in properties)
                        {
                            builder
                                .Entity(entityType.Name)
                                .Property(property.Name)
                                .HasConversion(new DateTimeOffsetToBinaryConverter());
                        }
                    }
```
Unfortunately looks like I hit its limitations. There is no intention to add support for it in 3.1 is there?

**Comment by ajcvickers** [comment]
@alexszym This isn't something that is going to change in any 3.1 release.
