### ISSUE TITLE
Implement SqliteException.IsTransient

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21598]
https://github.com/dotnet/runtime/issues/34817 introduces DbException.IsTransient for .NET 5.0, database-agnostic transient error detection. Not sure which transient errors Sqlite surfaces (e.g. locking/transactions?), these could be surfaced via this property.

/cc @bricelam

**Comment by ajcvickers** [comment]
Note from triage: SQLite does not have any transient errors of this type, other than waiting on locks which is already handled internally.
