### ISSUE TITLE
No behaviour documented for if property not found

### ISSUE THREAD

**Issue by TheRealDuckboy** [dotnet/efcore#21610]
If the requested property doesn't exist in the given entry, does this method return null or throw an exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 692c6c02-2677-6386-f57c-6fc06b8c7c57
* Version Independent ID: 317b8fb1-8fcc-4b3a-e493-c8df2f49eb63
* Content: [EntityEntry.Property(String) Method (Microsoft.EntityFrameworkCore.ChangeTracking)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.entityentry.property?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.Property);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.ChangeTracking/EntityEntry.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.ChangeTracking/EntityEntry.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Note from triage: we have updated exception documentation in various places. We also document when anything can return null. Nothing practical left to do here.
