### ISSUE TITLE
Slowness in windows tests

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#21630]
After https://github.com/dotnet/efcore/pull/21605 PR was merged, our windows build in azure devops which was finishing around 45-50 mins mark started crossing 60 mins. And since 60 mins was timeout, all subsequent runs for master branch and any PR targeting master started timing out for "Build windows" configuration.
I updated the timeout to 90 mins in #21628 and it passed around 65 mins mark.
The repro is consistent. Not even single run with that commit passed under 60 mins.
Other release branches were passed without any issue using same infra.
Hence, I believe this is not intermittent infra issue. Something happened in our dependencies which made our test runs much slower.
From about 45 mins to run all tests, now it takes 60 mins, which is 33% rise. Filing this issue to investigate.

**Comment by ajcvickers** [comment]
Closing this as investigations have not been fruitful and our EF perf tests are not showing regressions.
