### ISSUE TITLE
EF ignores [NotMapped] attribute for a specific property

### ISSUE THREAD

**Issue by vargasol** [dotnet/efcore#21632]
Hi,

I have the following EF model class:

`[Table("Accounts")]
public class Account : ModelBase
{
[Key]
public Guid ID { get; set; } = Guid.NewGuid();

[Required]
public string Email { get; set; }

[Required]
public string Name { get; set; }

public string Address { get; set; }

public AccountType Type { get; set; }

public string? Phone { get; set; }

public DateTime RegisteredAt { get; set; } = DateTime.Now;

public Guid LoginType { get; set; }

public string City { get; set; }

[Required]
public string CountryCode { get; set; }

[Required]
public AccountSex Sex { get; set; }

[Required]
public Guid AvatarID { get; set; }

public bool Active { get; set; } = true;

public string ZIP { get; set; }

public DateTime? LastLogon { get; set; }

[NotMapped]
[NotDump]
[NotTracked]
public string A { get; set; }

[NotMapped]
public IList<int> RoleIDs { get; set; }
}`

During an update command, EF always throwing error that **RoleIDs** does not have column in SQL table for this model. This is strange, because I am using [NotMapped] attribute to avoid mapping. However, the attribute **is working for property "A".**
I have the same behavior if I remove the setter function from the property and keep only the getter. I can solve the issue if I remove this property from the class.

On stackoverflow I read an article this is because of a bug in EF: https://stackoverflow.com/questions/34164285/entity-framework-is-ignoring-notmapped-attribute

Can you please check and give some hint this issue can be solved?

Thanks!
Gabor

### Further technical details

EF Core version: 3.1.6 (latest)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by roji** [comment]
Is a relationship defined in your model between Account and Role in some way? Can you please post a minimal model/code sample (not just the Account class), and also include the full exception information?

**Comment by vargasol** [comment]
I have the following error message from exception text:
**The property 'RoleIDs' on entity type 'Account' could not be found. Ensure that the property exists and has been included in the model.**

This is happening only if I run the following code and throws the exception on the **await sql.SaveChangeAsync()** line.:
`public async Task<Account> SaveProfile(AccountChange account)
		{
			Account acc;
			using (SQL sql = new SQL())
			{
				acc = sql.Accounts.Single(a => a.ID == account.ID);
				acc.Name = account.Name;
				acc.ZIP = account.ZIP;
				acc.Address = account.Address;
				acc.City = account.City;
				acc.CountryCode = account.CountryCode;
				await sql.SaveChangesAsync();
				acc = sql.Accounts.Single(a => a.ID == account.ID);
				Log.WriteAPILog($"Changing personal details of user {account.ID}");
			}
			return acc;
		}`

If I want to create a new account, the exception is not coming.
It is also not coming if remove the property RoleIDs from the Account model.

**Comment by roji** [comment]
Can you please post a minimal model/code sample (not just the Account class)?

**Comment by vargasol** [comment]
This is in my EF DbContext class:
`protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<AccountRole>()
				.HasKey(c => new { c.UserID, c.RoleID });
			modelBuilder.Entity<Account>().Ignore("RoleIDs");
		}`

Just to ensure, the exception is still fails. The RoleIDs contains the ID values of the Roles assigned to the user. There is a middle table in SQL which maps the Users ID with Roles ID. There is no direct relationship between Accounts and Roles table.

**Comment by roji** [comment]
It would be really helpful to get a minimal model/code sample rather than fragments... Please try to narrow down your code to a small console program, including the model, entities and query code, this way we can see exactly what you're doing.

**Comment by vargasol** [comment]
Ahh. So. The problem was on my side, not on EF side. Sorry for this. However, if I already found the root cause, I would like to share with you.
I created a full tracker solution for the SQL DbContext to could log all writing transactions for debug purposes:
`private void _TrackTransactions()
		{
			IEnumerable<EntityEntry> trackedData = this.ChangeTracker.Entries();
			foreach (var item in trackedData)
			{
				if (!this._TrackRequired(item))
				{
					continue;
				}

				Log newEntry = new Log();
				StringBuilder description = new StringBuilder();
				description.AppendLine("Object type:" + item.Entity.GetType().ToString());

				if (item.State == EntityState.Added)
				{
					description.AppendLine("Change type: Add");
				}
				else if (item.State == EntityState.Deleted)
				{
					description.AppendLine("Change type: Delete");
				}
				else if (item.State == EntityState.Modified)
				{
					description.AppendLine("Change type: Modify");
					description.AppendLine(this._GetEntityValues(item, ModelValueType.OriginalValues));
					description.AppendLine();
				}
				description.AppendLine("Properties:");
				description.AppendLine(this._GetEntityValues(item));
				newEntry.Message = description.ToString();
				Log.WriteLog(newEntry);
			}
		}

		private string _GetEntityValues(EntityEntry entry, ModelValueType type = ModelValueType.CurrentValues)
		{
			string result = "";
			if (type == ModelValueType.CurrentValues)
			{
				result += "Current values:\r\n";
			}
			else if (type == ModelValueType.OriginalValues)
			{
				result += "Original values:\r\n";
			}
			object obj = entry.Entity;
			PropertyInfo[] props = obj.GetType().GetProperties();
			foreach (var item in props)
			{
				if (Attribute.IsDefined(item, typeof(NotTrackedAttribute)))
				{
					result += "\t" + item.Name + " (" + item.PropertyType.ToString() + ") => Not tracked value!\r\n";
					continue;
				}

				if (type == ModelValueType.CurrentValues)
				{
					try
					{
						result += "\t" + item.Name + " (" + item.PropertyType.ToString() + ") => " + entry.Property(item.Name).CurrentValue.ToString() + "\r\n";
					}
					catch (NullReferenceException)
					{
						result += "\t" + item.Name + " (" + item.PropertyType.ToString() + ") => NULL value\r\n";
					}
					catch (Exception)
					{
						result += "\t" + item.Name + " cannot be retrieved due to exception!";
					}
				}
				else if (type == ModelValueType.OriginalValues)
				{
					try
					{
						result += "\t" + item.Name + " (" + item.PropertyType.ToString() + ") => " + entry.Property(item.Name).OriginalValue.ToString() + "\r\n";
					}
					catch (NullReferenceException)
					{
						result += "\t" + item.Name + " (" + item.PropertyType.ToString() + ") => NULL value\r\n";
					}
					catch
					{
						result += "\t" + item.Name + " cannot be retrieved due to exception!";
					}
				}

			}
			return result;
		}

		private bool _TrackRequired(EntityEntry entry)
		{
			if (Attribute.IsDefined(entry.Entity.GetType(), typeof(NotTrackedAttribute)))
			{
				return false;
			}
			return true;
		}
`
This solution is tracking all changes related to attributes not marked with [NotTracked] attribute. Because in my class, this attribute was missing for property RoleIDs, this tracker solution wanted to read its value from EF, but because of [NotMapped] attribute, this item was missing from EF.

Sorry for this confusing. That was fully my mistake.
