### ISSUE TITLE
Navigation Class in Multiple Objects Not Displayed

### ISSUE THREAD

**Issue by cxc256** [dotnet/efcore#21631]
I have a Check class. The Check class contains a navigation property to a Company class for the recipient of the check. Please see the following code:

```C#
public class Check
{
	public int CheckId {get;set;}
	public int AccountId {get;set;}
	public int RecipientId {get;set;}
	...
	public Company Recipient {get;set;}
}

public class Company
{
	public int CompanyId {get;set;}
	public string CompanyName {get;set;}
}

public class CompanyConfig:IEntityTypeConfiguration<Company>
{
	public void Configure(EntityTypeBuilder<Company> builder)
	{
		builder.ToTable("Companies").HasKey(c => c.CompanyId);
	}
}

public class CheckConfig : IEntityTypeConfiguration<Check>
{
	public void Configure( EntityTypeBuilder<Check> builder )
	{
		builder.ToTable( "Checks" ).HasKey( e => e.CheckId );
		builder
			.HasOne( e => e.Recipient )
			.WithOne( )
			.HasForeignKey<ClipCheck>( e => e.RecipientId );            
	}
}
```

The problem is that when you bring back multiple Check instances (say from 1 Account), if the different checks have the same RecipientId, only the first check with that RecipientId displays Recipient. The subsequent checks have null for Recipient even though there is a recipientId. For example:

```json
[
    {
        "ClipCheckId": 16352,
        "ClipAccountId": 17008,        
        "RecipientId": 1135,
        "Recipient": {
            "CompanyId": 1135,
            "CompanyName": "The XXX Company"
        }
    },
    {
        "ClipCheckId": 16353,
        "ClipAccountId": 17008,
        "RecipientId": 1135,
        "Recipient": null
    },
    {
        "ClipCheckId": 16354,
        "ClipAccountId": 17008,        
        "RecipientId": 1135,
        "Recipient": null
    },
    {
        "ClipCheckId": 16355,
        "ClipAccountId": 17008,
        "RecipientId": 1135,
        "Recipient": null
    }
]
```

There are no exceptions thrown. I've verified it comes out of EF this way.

### Further technical details

EF Core version: 3.1.6 & 3.1.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.6 & 3.15
Target framework: .NET Core 3.1
Operating system: Windows 10 & Windows Server 2016
IDE: Visual Studio 2019 16.6.3 & 16.6.4

**Comment by ajcvickers** [comment]
@cxc256 Given, "the different checks have the same RecipientId," this means that the relationship is not one-to-one but rather one-to-many. For example:

```C#
builder.HasOne( e => e.Recipient ).WithMany( )
```

See https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key for more info.

**Comment by cxc256** [comment]
@ajcvickers That solved the problem.

It is probably just me, but this does not seem intuitive. The relationship between the check and recipient is one to one, especially in the database. True, when you get a bunch of checks, there will be many recipients, but they only belong to an individual check.
