### ISSUE TITLE
Value cannot be null in Utilities.Check 3.1.6 

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/efcore#21654]
Consider this code which worked properly in 3.1.5:

```c#
/// <summary>
        /// Gets the table name from a Entity type.
        /// </summary>
        /// <typeparam name="TEntity"></typeparam>
        /// <returns></returns>
        public string GetTableName<TEntity>() where TEntity : class
        {
            var entityType = Model.FindEntityType(typeof(TEntity));
            string schema = entityType.GetSchema();
            return string.Join('.', schema, entityType.GetTableName());
        }
```

Now in 3.1.6 I find that:

```entityType.GetSchema();``` returns `null` instead of the empty string.

I am only able to resolve this like so:

```entityType.GetSchema(); ?? string.Empty```

OR 

Worse perhaps even after adding this check I get the same exception for entity types which specifically indicated have no table with code like so:

```modelBuilder.Entity<SomeEntity>().HasNoKey().ToView(null);```

Yet I still need to apply the Schema attribute to these entities otherwise I get the same error and 

### Steps to reproduce

`FromSqlRaw` on any entity type. Also happens if I change form DbSet to DbQuery.

The sql is valid but the table it's looking for it should not be, this is `FromSqlRaw` and configured as as indicated above in `OnModelsCreating`

### Further technical details

EF Core version: 3.1.6

Does not occur in 3.1.5

**Comment by ajcvickers** [comment]
@juliusfriedman I am not able to reproduce this--the code below does the same thing on 3.1.5 and 3.1.6. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public static class Program
{
    public static void  Main()
    {
        using (var context = new SomeDbContext())
        {
            Console.WriteLine(context.GetTableName<Blog>());
            Console.WriteLine(context.GetTableName<Post>());
        }
    }
}

public class Blog
{
    public int Id { get; set; }
}

public class Post
{
    public int Id { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
        modelBuilder.Entity<Post>().ToTable("Post", "MySchema");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
         => optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=ConTest;ConnectRetryCount=0");

    public string GetTableName<TEntity>() where TEntity : class
    {
        var entityType = Model.FindEntityType(typeof(TEntity));
        string schema = entityType.GetSchema();
        return string.Join('.', schema, entityType.GetTableName());
    }
}
```

**Comment by juliusfriedman** [comment]
Yea looking into it now, it seems after a revert to 3.1.5 we are still hitting this error but was not until we upgraded to 3.1.6 not 100% sure what's going on right now...

**Comment by juliusfriedman** [comment]
All I 

> Yea looking into it now, it seems after a revert to 3.1.5 we are still hitting this error but was not until we upgraded to 3.1.6 not 100% sure what's going on right now...
> 
> ```cs
> class Number { long Value {get;} {set;} }
> Numbers.FromSqlRaw($@"SELECT 1 as Value").AsNoTracking();//SQL is valid but Utilites.Check throws now.
> ```
> 
> OnModelsCreating:
> 
> ```cs
> modelBuilder.Entity<Number>().HasNoKey().ToView(null);
> ```
> 
> Property
> 
> ```
> internal DbSet<Number> Numbers { get; }
> ```

I found it to the removal of the {set;} on the property which was spurred by an analyzer... SOrry
