### ISSUE TITLE
Make everything virtual with Scaffold (for using UseChangeTrackingProxies())

### ISSUE THREAD

**Issue by janschreier** [dotnet/efcore#21653]
We're DB-first and from time to time run 
`dotnet ef dbcontext scaffold`
to update our model from the database. 
As we're using WPF I currently extend most classes created during scaffolding with a partial class that implements `INotifyPropertyChanged` and let Fody do the rest to get ChangeTracking without much manual work. 

Now I would like to make use of EF Core 5.0 and it's proxy creation with UseChangeTrackingProxies(). But here I get a lot of errors like 

> Property 'PropertyName' on entity type 'EntityName' is not virtual. UseChangeTrackingProxies requires all entity types to be public, unsealed, have virtual properties, and have a public or protected constructor. UseLazyLoadingProxies requires only the navigation properties be virtual.

So my dream would be to have a flag for DbScaffold  which makes every property virtual and not just some.

(I hope this is the right place to make such request, sorry if not!)

**Comment by ErikEJ** [comment]
I think the Handlebars extension and/or EF Core Power Tools with Handlebars could help you.

**Comment by janschreier** [comment]
Handlebars seems to be a true gem. Thanks for pointing me to this :)

**Comment by ajcvickers** [comment]
See also #4038
