### ISSUE TITLE
All DbContext classes are forced to have generic DbContextOptions in DI as long as one DbContext is added to DI with generic DbContextOptions

### ISSUE THREAD

**Issue by RickyLin** [dotnet/efcore#2165]
I read #1401.
My scenario is that I don't want to add my DbContext classes to DI because there are too many of them and I want to generate them by myself (I will add the classes that instantiate those DbContext to DI). On the other hand, I need to use Identity which need to add IdentityDbContext to DI.
In Startup.cs, I add IdentityDbContext as this:

```
services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<DbPortalIdentityDbContext>(options => options.UseSqlServer(Configuration.Get("ConnectionString")));
```

When I need my DbContext class instantiated, I use `DbContextActivator.CreateInstance<T>`.
However, calling `DbContextActivator.CreateInstance<T>` by myself will result in `InvalidOperationException`, the error message is:

The DbContextOptions object registered in the service provider must be a DbContextOptions<TContext> where TContext is the type of the DbContext being used.

The reason is that `AddDbContext` method will [add](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Infrastructure/EntityFrameworkServicesBuilder.cs#L72) DbContextOptions to DI, `GetOptions` method of DbContext class will get DbContextOptions from DI and [if it gets an option but doesn't match the type of DbContext, it throws that exception](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/DbContext.cs#L166).

Because I don't add my DbContext classes to DI, so the `GetOptions` method always get the last DbContextOptions added by the last `AddDbContext` method in Startup.cs then throw the InvalidOperationException.

I wonder whether we can ignore the mismatch instead of throwing an exception?

```
private DbContextOptions GetOptions(IServiceProvider serviceProvider)
{
    if (serviceProvider == null)
    {
        return new DbContextOptions<DbContext>();
    }

    var genericOptions = _optionsTypes.GetOrAdd(GetType(), t => typeof(DbContextOptions<>).MakeGenericType(t));

    var options = (DbContextOptions)serviceProvider.GetService(genericOptions)
                    ?? serviceProvider.GetService<DbContextOptions>();

    if (options == null
        || options.GetType() != genericOptions)
    {
        return new DbContextOptions<DbContext>();
    }

    return options;
}
```

by the way, in this method:

```
public virtual EntityFrameworkServicesBuilder AddDbContext<TContext>([CanBeNull] Action<DbContextOptionsBuilder> optionsAction = null)
    where TContext : DbContext
{
    _serviceCollection.AddSingleton(_ => DbContextOptionsFactory<TContext>(optionsAction));

    _serviceCollection.AddSingleton<DbContextOptions>(p => p.GetRequiredService<DbContextOptions<TContext>>());

    _serviceCollection.AddScoped(typeof(TContext), DbContextActivator.CreateInstance<TContext>);

    return this;
}
```

`p.GetRequiredService<DbContextOptions<TContext>>()` in
  `_serviceCollection.AddSingleton<DbContextOptions>(p => p.GetRequiredService<DbContextOptions<TContext>>());` seems not to work as it's supposed to. In my case, TContext is supposed to be my DbContext type but it's DbPortalIdentityDbContext type because it's the same TContext as AddDbContext<**TContext**>

**Comment by rowanmiller** [comment]
**Triage** This is by design. We always require that the generic version be registered in DI. That is also what our helper methods do. As a convenience we do allow you to expose a constructor that takes the non-generic version... but at runtime it will be an instance of the generic version.
