### ISSUE TITLE
Error -  Could not load file or assembly 'EFCore.BulkExtensions

### ISSUE THREAD

**Issue by edspicer** [dotnet/efcore#21667]
Hi people,

I installed this extensions in my project (my projet have CQRS with EFCore - 2.2, I installed in my Domain Project), when I publish (deploy) in release, in execution I recieve this message : "Could not load file or assembly 'EFCore.BulkExtensions, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null'. O sistema não pode encontrar o arquivo especificado." Have ayone ideia how I can resolve this issue? Thanks.

**Comment by ajcvickers** [comment]
@edspicer Your best bet is to contact the people who create the `EFCore.BulkExtensions` package.

**Comment by edspicer** [comment]
> @edspicer Your best bet is to contact the people who create the `EFCore.BulkExtensions` package.

Ok, thank you! :)

**Comment by edspicer** [comment]
question moved to EFCore.BulkExtensions package
