### ISSUE TITLE
Change-tracking perf: Child and Parent variations

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21674]
![image](https://user-images.githubusercontent.com/1862641/87829606-adc51e80-c87f-11ea-8e9c-3fdcc8c132be.png)

**Comment by roji** [comment]
... and the winner is .... :drum: 

@ajcvickers with commit 6638762de17e6dc1a62448cad667bd52a2df1b78

**Comment by ajcvickers** [comment]
More to do...

![image](https://user-images.githubusercontent.com/1430078/88589109-7daf1580-d00d-11ea-8ec7-a3b9575a073c.png)

**Comment by ajcvickers** [comment]
Thanks @smitpatel!

![image](https://user-images.githubusercontent.com/1430078/91642612-a5fdab80-e9e1-11ea-93e9-4a3072a64ce3.png)
