### ISSUE TITLE
Create Index `WITH INCLUDE`

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/efcore#21682]
https://stackoverflow.com/questions/22033866/entity-framework-6-1-create-index-with-include-statement
https://thinkrethink.net/2017/12/04/add-index-with-include-entity-framework-core-2-0/

```sql
CREATE NONCLUSTERED INDEX IX_IsDeleted_Date_ID ON SomeTable(IsDeleted, [Date]) INCLUDE (ID)
```

```c#
modelBuilder.Entity<SomeTable>().HasIndex(e => new { e.IsDeleted, e.Date }).Includes(e => e.ID);
```

```diff
public class IndexBuilder {
+public static IndexBuilder Includes<TIndexColumn>(this IndexBuilder builder, Expression<TIndexColumn> expression);
}
```

**Comment by roji** [comment]
Are you looking for the [included columns](https://docs.microsoft.com/en-us/ef/core/modeling/indexes#included-columns) syntax?

**Comment by juliusfriedman** [comment]
yes I am sorry for the confusion
