### ISSUE TITLE
Allow DbContext.Update() on entities with temporary key values

### ISSUE THREAD

**Issue by DragoonAethis** [dotnet/efcore#21693]
When trying to run Update on an entity with generated temporary (to be replaced by the database) key, EF fails with: `The property 'Id' on entity type 'SomeEntity' has a temporary value while attempting to change the entity's state to 'Modified'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.`. This behavior is quite counterintuitive, since running Update on an unattached entity will correctly set its state to Added or Modified and leave it as Modified if it has a persistent/generated but not temporary key. One would assume that trying to run it again on attached, Added entities simply leaves it in the Added state, but an exception is thrown instead.

DbContext.Update(entity) should most likely keep the Added entity state, without throwing or changing anything.

**Comment by ajcvickers** [comment]
@DragoonAethis When called on a tracked entity, Update changes its state to `Modified` and marks all properties as modified. A reasonable case can be made that it should instead no-op, but this deviates a lot from EF6 behavior, and regardless changing this now would be a massive breaking change.
