### ISSUE TITLE
IHistory interface issues

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2169]
I am trying to write a provider, and the engine in that provider has some limitations. It does not support any T-SQL programmability (Like BEGIN END IF etc).
The IHistoryRepository interface seems to expect that all providers do that:

```
    string BeginIfNotExists([NotNull] string migrationId);
    string BeginIfExists([NotNull] string migrationId);
    string EndIf();
```

How can I make this work in my provider?

**Comment by ErikEJ** [comment]
OK; looking through the code, if I just do not expect to create idempotent scripts, my HistoryRepo implementation will work. Closing, I guess.

**Comment by bricelam** [comment]
Good feedback. That area still needs a bit of work.

**Comment by ErikEJ** [comment]
@bricelam It does not appear to be an issue anyway, as there is no way I can make the scripts idempotent anyway

**Comment by ErikEJ** [comment]
@bricelam HistoryRepo implemented and tests are passing!
