### ISSUE TITLE
problem with getting keyless Entity from procedure with two parameters

### ISSUE THREAD

**Issue by kyon12345** [dotnet/efcore#21692]
my procedure is like
```sql
CREATE PROCEDURE [dbo].[TestProc_NEW]
    -- Add the parameters for the stored procedure here
    @StartTime DATETIME,
    @EndTime DATETIME
AS
....
##finalResult
 SELECT ... From Table1 left join Table2.....
....
```
and my model is
```C#
public class YieldRateView
    {
        public string FactoryCode { get; set; }
        public string ProductName { get; set; }
        public string CustomerPN { get; set; }
        public string ShiftName { get; set; }
        public string WorkcenterDescription { get; set; }
        public string StationType { get; set; }
        public string DefectGroup { get; set; }
        public string DefectCode { get; set; }
        public int DefectCount { get; set; }
        public int INPUT { get; set; }
    }
```
i checked carefully these property is matched with the output of procedure
while i try to get result from that,i use
```C#
var yieldRateViews = await _context.YieldRateViews.FromSqlInterpolated($"EXEC procName @StartTime ={startTime}, @EndTime = {endTime}").AsNoTracking().ToListAsync();
```
it gots me this Exception
```
引发的异常:“System.ArgumentNullException”(位于 Microsoft.EntityFrameworkCore.Relational.dll 中)
引发的异常:“System.ArgumentNullException”(位于 System.Private.CoreLib.dll 中)
```
so i create a test procedure which is
```sql
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Test_ProcEFCore]
    -- Add the parameters for the stored procedure here
    @StartTime DATETIME,
    @EndTime DATETIME
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT '123' AS ProductName,'456' AS ProductOU
END
```
and this is model
```C#
public class ProductView
    {
        public string ProductName { get; set; }
        public string ProductOU { get; set; }
    }
```
my datacontext configuraiton
```C#
            modelBuilder.Entity<YieldRateView>().HasNoKey();
            modelBuilder.Entity<YieldRateView>().ToView(null);

            modelBuilder.Entity<ProductView>().HasNoKey();
            modelBuilder.Entity<ProductView>().ToView(null);
```
but this one works perfectly!
i'm very confuse,can someone give me a hint,please

**Comment by ErikEJ** [comment]
Sure you sproc only returns the single result set?

**Comment by kyon12345** [comment]
> Sure you sproc only returns the single result set?

yes i am sure,i use temp table in the procedure,but i only return one result

**Comment by ajcvickers** [comment]
@kyon12345 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by kyon12345** [comment]
i finally find the problem,this is because in my datacontext, i use
```
//the problem entity
public DbSet<YieldRateView> YieldRateViews;
//the normal one
public DbSet<ProductView> ProductViews { get; set; }
```
i forget to add {get; set;} behind it,after add it ,everything goes fine,i am a beginner to ef core,can someone tell me why,
is this because ef core Identify YieldRateViews as an Entity in database when we forget accessor property?

**Comment by smitpatel** [comment]
Please refer to [our documentation](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#including-types-in-the-model). Since `YieldRateViews` without accessors is a field not a property, it is not included in the model by convention.
