### ISSUE TITLE
TargetInvocationException when PK property of child entity has no setter

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#2172]
For the most part our stack works when a property doesn't have a setter. In the sample code Test.TestId is fine with no setter but removing the setter from Child.ChildId results in a TargetInvocationException during DetectChanges.

> System.Reflection.TargetInvocationException was unhandled by user code
>   HResult=-2146232828
>   Message=Exception has been thrown by the target of an invocation.
>   Source=mscorlib
>   StackTrace:
>        at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>        at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>        at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>        at Microsoft.Data.Entity.Metadata.Internal.ClrAccessorSource`1.Create(PropertyInfo property)
>        at Microsoft.Data.Entity.Metadata.Internal.ClrAccessorSource`1.<GetAccessor>b__3_0(Tuple`2 k)
>        at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey key, Func`2 factory)
>        at Microsoft.Data.Entity.Metadata.Internal.ClrAccessorSource`1.GetAccessor(Type declaringType, String propertyName)
>        at Microsoft.Data.Entity.Metadata.Internal.ClrAccessorSource`1.GetAccessor(IPropertyBase property)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.EntityEntryMetadataServices.WriteValue(Object entity, IPropertyBase propertyBase, Object value)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.WritePropertyValue(IPropertyBase propertyBase, Object value)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase property, Object value)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.ValueGenerationManager.Generate(InternalEntityEntry entry)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation, Sidecar snapshot)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectNavigationChanges(InternalEntityEntry entry, Sidecar snapshot)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectRelationshipChanges(InternalEntityEntry entry)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
>        at Microsoft.Data.Entity.DbContext.TryDetectChanges(IStateManager stateManager)
>        at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
>        at Microsoft.Data.Entity.DbContext.SaveChanges()
>        at ConsoleApp1.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 14\Projects\ConsoleApp1\src\ConsoleApp1\Program.cs:line 22
>   InnerException: System.NullReferenceException
>        HResult=-2147467261
>        Message=Object reference not set to an instance of an object.
>        Source=EntityFramework.Core
>        StackTrace:
>             at Microsoft.Data.Entity.Metadata.Internal.ClrPropertySetterSource.CreateGeneric[TEntity,TValue,TNonNullableEnumValue](PropertyInfo property)
>        InnerException: 

``` csharp
using System;
using System.Collections.Generic;
using Microsoft.Data.Entity;

namespace ConsoleApp1
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var test = new Test { Name = "Bob" };
                db.Tests.Add(test);

                var child = new Child { Name = "Ted", Test = test };
                test.Children.Add(child);

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                foreach (var item in db.Tests.Include(t => t.Children))
                {
                    Console.WriteLine(item.Name);
                    foreach (var child in item.Children)
                    {
                        Console.WriteLine(" - " + child.Name);
                    }
                }
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Test> Tests { get; set; }
        public DbSet<Child> Children { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            builder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;MultipleActiveResultSets=True;");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Test>().Key(t => t.TestId);
        }
    }

    public class Test
    {
        public Test()
        {
            Children = new List<Child>();
        }

        public int TestId { get; }
        public string Name { get; set; }

        public List<Child> Children { get; set; }
    }

    public class Child
    {
        public int ChildId { get; }
        public string Name { get; set; }

        public int TestId { get; set; }
        public Test Test { get; set; }
    }
}
```

**Comment by divega** [comment]
@rowanmiller I am clearing up the milestone to bring this back to triage to decide the priority. I actually can't recall why it is assigned to me :smile: but discussing with @ajcvickers we both agreed that ultimately if both the `Child` and `Test` types were configured to include their key properties (we shouldn't be bringing properties without setters into the model by convention anymore but the user should be able to configure it explicitly) then fixup code should fall back to using the field just like materialization does.

**Comment by rowanmiller** [comment]
Closing in favor of the more general https://github.com/aspnet/EntityFramework/issues/4461
