### ISSUE TITLE
Question: Is it possible to access the `SqlGenerationHelper` and `TypeMappingSource` services?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#21731]
I would like to build SQL commands using the `SqlGenerationHelper` and `TypeMappingSource` services shown in the [Using a MigrationOperation](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#using-a-migrationoperation). 

Specifically I want to:
* Create SQL constants from NET types to fix a hole in my [EfCore.EFSchemaCompare tool](https://github.com/JonPSmith/EfCore.TestSupport/wiki/9.-EfSchemaCompare) tool. At the moment comparing default values on columns doesn't always work
* I *might* improve my cascade soft delete service to use SQL to set the soft delete column via SQL rather than via EF Core. If I do that I would like to make it database agonistic. 

The code shown in the  [Using a MigrationOperation](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#using-a-migrationoperation) document shows that I could build database agonistic SQL. To do that I need to link into methods in the database provider that allows me to format SQL commands based on the specific provider.

**Comment by ajcvickers** [comment]
@JonPSmith We discussed this and we believe it should be possible to do this. Are you running into specific issues?

**Comment by JonPSmith** [comment]
I want to access these features outside of the `SqlServerMigrationsSqlGenerator` because it would be very clumsy. Is there a way to get to this say via a EF Core service?

**Comment by ErikEJ** [comment]
dbContext.GetService<> ?

**Comment by JonPSmith** [comment]
Yes Erik I would like to use dbContext.GetService<???> and get a service that can format SQL commands in the correct way for the database provider linked to the dbContext. I just don't know what that service interface is called.

**Comment by roji** [comment]
@JonPSmith rather than getting MigrationsSqlGeneratorDependencies - which happens to reference IRelationalTypeMappingSource - you can just get IRelationalTypeMappingSource directly:

```c#
var typeMappingSource = context.GetService<IRelationalTypeMappingSource>();
var constantString = typeMappingSource.FindMapping(typeof(string)).GenerateSqlLiteral("hello");
```

**Comment by JonPSmith** [comment]
Thanks @roji, that would work for most of my usages.
