### ISSUE TITLE
Renamed 'master' to 'main' (broken git pull)

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/efcore#21752]
For all those who can't pull `master`, it has renamed to `main`.

To preserve refspec to patches and branches, just changing the `heads/master` to `heads/main` should work.

```diff
[remote "origin"]
	url = https://github.com/dotnet/efcore
-	fetch = +refs/heads/master:refs/remotes/origin/master
+	fetch = +refs/heads/main:refs/remotes/origin/master
	tagopt = --no-tags
[branch "master"]
	remote = origin
-	merge = refs/heads/master
+	merge = refs/heads/main
```

> Putting this out there, if anyone else facing similar issue with git. Also **Please do announce when you rename branches especially when it could break the forks**.

**Comment by terrajobst** [comment]
Hmm, I'm surprised this broke `git pull`.

@jeffwilcox, isn't GitHub supposed to forward deleted refs to the default branch?

**Comment by jeffwilcox** [comment]
@terrajobst I believe only for retrieving blobs via HTTPS right now... 

Per https://github.com/github/renaming, under "Later this year", 

> And, we’re also looking into redirecting users who git fetch or git clone the old branch name to the new branch name (with a warning and instructions to update their local clone), so it’s easy for your contributors to move.

**Comment by terrajobst** [comment]
Ouch. I see 🙁

**Comment by ajcvickers** [comment]
Closing this as there is nothing to track for EF.
