### ISSUE TITLE
Perf regression in update pipeline

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#21772]
![image](https://user-images.githubusercontent.com/1430078/88427107-2871ca80-cda7-11ea-9be0-befea0ce2cd4.png)

**Comment by roji** [comment]
@AndriySvyryd the offending commit seems to be 13e69caf025bd40324a4eebd7b88af998d5e0da1:

13e69caf025bd40324a4eebd7b88af998d5e0da1

|         Method | Async | Batching |     Mean |   Error |  StdDev |     Gen 0 |     Gen 1 | Gen 2 | Allocated |
|--------------- |------ |--------- |---------:|--------:|--------:|----------:|----------:|------:|----------:|
| UpdatePipeline | False |    False | 137.2 ms | 1.80 ms | 1.68 ms | 4000.0000 | 1000.0000 |     - |  26.74 MB |
| UpdatePipeline | False |     True | 136.0 ms | 0.73 ms | 0.65 ms | 4000.0000 | 1000.0000 |     - |  26.74 MB |
| UpdatePipeline |  True |    False | 140.3 ms | 0.70 ms | 0.65 ms | 4000.0000 | 1000.0000 |     - |  26.94 MB |
| UpdatePipeline |  True |     True | 140.6 ms | 0.89 ms | 0.84 ms | 4000.0000 | 1000.0000 |     - |  26.94 MB |

ffcb62d0e547dea75be85ff398d940173c99b28f

|         Method | Async | Batching |     Mean |   Error |  StdDev |     Gen 0 |     Gen 1 | Gen 2 | Allocated |
|--------------- |------ |--------- |---------:|--------:|--------:|----------:|----------:|------:|----------:|
| UpdatePipeline | False |    False | 128.6 ms | 2.43 ms | 2.27 ms | 4000.0000 | 1000.0000 |     - |  26.74 MB |
| UpdatePipeline | False |     True | 129.2 ms | 0.52 ms | 0.46 ms | 4000.0000 | 1000.0000 |     - |  26.74 MB |
| UpdatePipeline |  True |    False | 132.3 ms | 0.64 ms | 0.60 ms | 4000.0000 | 1000.0000 |     - |  26.94 MB |
| UpdatePipeline |  True |     True | 133.7 ms | 0.83 ms | 0.78 ms | 4000.0000 | 1000.0000 |     - |  26.94 MB |
