### ISSUE TITLE
SqliteDbContextOptionsBuilder.UseNetTopologySuite triggers Loader lock exception after several database reads

### ISSUE THREAD

**Issue by btmorris** [dotnet/efcore#21806]
When using entity framework core to access data in a spatialite database and it fails to execute a query around the 500th attempt with a LoaderLock exception. It does not appear to be related to any specific query. The issue does not occur if the UseNetTopologySuite option is not used. 

### To Reproduce

Attached is a sample project that creates a small database attempts to query the database several times.
[EntityFrameworkBug.zip](https://github.com/dotnet/efcore/files/4983381/EntityFrameworkBug.zip)

Managed Debugging Assistant 'LoaderLock' 
  Message=Managed Debugging Assistant 'LoaderLock' : 'Attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.'

[Managed to Native Transition]
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(System.Data.CommandBehavior behavior)
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(Microsoft.Data.Sqlite.SqliteConnection connection, string commandText, Microsoft.Data.Sqlite.SqliteParameter[] parameters)
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteConnection.Open()
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(bool errorsExpected)
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(bool errorsExpected)
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject parameterObject)
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<EntityFrameworkBug.SimpleModel>.Enumerator.InitializeReader(Microsoft.EntityFrameworkCore.DbContext _, bool result)
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<EntityFrameworkBug.SimpleModel>.Enumerator.MoveNext()
System.Core.dll!System.Linq.Enumerable.SingleOrDefault<EntityFrameworkBug.SimpleModel>(System.Collections.Generic.IEnumerable<EntityFrameworkBug.SimpleModel> source)

### Additional context

Microsoft.Data.Sqlite version: 3.100.620.31702
Target framework: (e.g. .NET Core 3.0) .net 4.8
Operating system: Windows OS Name	Microsoft Windows 10 Pro Version	10.0.18362 Build 18362
Microsoft.EntityFrameworkCore 3.1.6
Microsoft.EntityFrameworkCore.Sqlite 3.1.6
Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite 3.1.6

**Comment by ajcvickers** [comment]
@btmorris Unfortunately, we have seen repeated reports where using Spatialite is causing issues. We will look into this more in the future, but the result may be that we recommend people stop using it. For the moment, I'm putting this on the backlog.

**Comment by ajcvickers** [comment]
Verified that this no longer fails on 8.0.

```
...
149993 f0699163-7f9d-4f21-92a3-81f8653318d0
149994 f0699163-7f9d-4f21-92a3-81f8653318d0
149995 f0699163-7f9d-4f21-92a3-81f8653318d0
149996 f0699163-7f9d-4f21-92a3-81f8653318d0
149997 f0699163-7f9d-4f21-92a3-81f8653318d0
149998 f0699163-7f9d-4f21-92a3-81f8653318d0
149999 f0699163-7f9d-4f21-92a3-81f8653318d0
Done

Process finished with exit code 0.
```
