### ISSUE TITLE
Ability to set navigation property using one of the possible Ids

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#21812]
### What problem are you trying to solve?
Here is a simplified version of what I am trying to solve.

I am working on a razor component that uses a `<select>` to choose the value of a property on a tracked entity.

I have a base `Dropdown` class and multiple classes that derive from it, e.g. `Color`, which is a property on the tracked entity.

To make the razor component generic enough, I pass in a `List<Dropdown>` created from a `List<Color>`.

After the `<select>` is changed, I want to assign the new choice to the `Color` on the tracked entity.

There is no way I can find to set the `Color` property directly - razor component doesn't know it's a `Color` and no way to create a `Color` object using its type and the values from the `List<Dropdown>` corresponding to `<select>` value.

 It would be great if all I had to do was set its `Id` from the value of the `<select>`.

Right now, setting the `Id` and calling `context.SaveChanges()` doesn't update anything in the database.

### Describe the solution you'd like
```
// I'm using reflection in my code, but for this example, I'm leaving it out for simplicity
trackedEntityColorProperty.Id = valudFromSelect;
```

**Comment by ajcvickers** [comment]
@mrlife We're having trouble following what you are trying to do. If possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by mrlife** [comment]
Suppose there is a `Color` entity with these properties:
```
public int Id;
public string Name;
```

A `Bicycle` entity with these properties:
```
public int Id;
public Color Color;
```

The `Color` entity is populated in the database with 10 rows with `Id`s 1-10.

Since EF Core has is tracking the `Color`s, there are situations where it would be nice if, instead of setting `Bicycle.Color`, setting`Bicycle.Color.Id` was enough, if the value is between 1-10.

**Comment by mrlife** [comment]
Suppose there is a `Color` entity with these properties:
```
public int Id;
public string Name;
```

A `Bicycle` entity with these properties:
```
public int Id;
public Color Color;
```

The `Color` entity is populated in the database with 10 rows with `Id`s 1-10.

Since EF Core is tracking the `Color`s, there are situations where it would be nice if, instead of setting `Bicycle.Color`, setting`Bicycle.Color.Id` was enough, if the value is between 1-10.

**Comment by mrlife** [comment]
Suppose there is a `Color` entity with these properties:
```
public int Id;
public string Name;
```

A `Bicycle` entity with these properties:
```
public int Id;
public Color Color;
```

The `Color` entity is populated in the database with 10 rows with `Id`s 1-10.

Since EF Core is tracking the `Color`s, there are situations where it would be nice if, instead of setting `Bicycle.Color`, setting`Bicycle.Color.Id` was enough, if the value is between 1-10. As it is now, only the `Id` is written to the database when `SaveChanges()` is called.

**Comment by ajcvickers** [comment]
@mrlife Mapping these entity types in the normal way will use a ColorId foreign key, which can be added to the Bicycle class:

```C#
public class Bicycle
{
    public int Id { get; set; }
    public Color Color { get; set; }
    public int ColorId { get; set; }
}
```
You can then change the color by setting the `ColorId` property with the appropriate ID.
