### ISSUE TITLE
Add method doesn't trigger a ChangeTracker.StateChanged event because it triggers a ChangeTracker.Tracked event

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#21852]
I noticed that I call `context.Add(entity)` no `ChangeTracker.StateChanged` event is triggered, but if a call `context.Remove(entity)` an event is triggered. I asked why this works this way.
## UPDATE

@ajcvickers pointed out that adding a new entity is tracked by the `ChangeTracker.Tracked` event and it doesn't raise a `ChangeTracker.StateChanged` event. That explains why it works that way.

### Steps to reproduce

Here is an updated unit test showing the `ChangeTracker.Tracked` event, but no `ChangeTracker.StateChanged` event.

``` C#
[Fact]
public void TestStateChangedEventNoSaveChangesOk()
{
    //SETUP
    var options = SqliteInMemory.CreateOptions<Chapter11DbContext>();
    using (var context = new Chapter11DbContext(options))
    {
        context.Database.EnsureCreated();

        var trackedLogs = new List<EntityTrackedEventArgs>();
        context.ChangeTracker.Tracked += delegate (object sender, EntityTrackedEventArgs args)
        {
            trackedLogs.Add(args);
        };

        var statesLog = new List<StateChangedEventLog>();
        context.ChangeTracker.StateChanged += delegate (object sender, EntityStateChangedEventArgs args)
        {
            statesLog.Add(new StateChangedEventLog(sender, args));
        };

        //ATTEMPT
        var entity = new MyEntity { MyString = "Test" };
        context.Add(entity);

        //VERIFY
        statesLog.Count.ShouldEqual(0);
        trackedLogs.Count.ShouldEqual(1);
        trackedLogs.Single().Entry.State.ShouldEqual(EntityState.Added);
    }
}
```

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: EF Core 5 preview 7
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@JonPSmith Listen to the ChangeTracker.Tracked to get notified when EF starts tracking an entity.

**Comment by JonPSmith** [comment]
Ah. My mistake. I assumed I would get a StateChanged event on an add but obviously not. 

Thanks for explaining to me. I will change my issue in case someone else needs to know.
