### ISSUE TITLE
DbCommandInterceptor to set entity properties 

### ISSUE THREAD

**Issue by R4ZuL** [dotnet/efcore#21877]
Hi,

i have a customer entity that includes CreatedBy, CreatedAt, ModifiedBy and ModifiedAt properties.
```C#
public class CustomerEntity : IIdEntity<int>, IAuditableEntity
{
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string CreatedBy { get; set; }

        public string ModifiedBy { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime ModifiedAt { get; set; }
}
```

What i try to achieve is to set the values for the above mentioned properties at runtime by using one of the provided DbCommandInterceptor functions. I already tried to implement something like this:

```C#
public override InterceptionResult<DbCommand> CommandCreating(
            CommandCorrelatedEventData eventData, InterceptionResult<DbCommand> result)
{
            var dbContext = eventData.Context;
            var entries = dbContext.ChangeTracker.Entries().Where(x =>
                x.Entity is IAuditableEntity && (x.State == EntityState.Added || x.State == EntityState.Modified));

            foreach (var entry in entries)
            {
                var now = DateTime.Now;
                var entity = (IAuditableEntity)entry.Entity;

                if (entry.State == EntityState.Added)
                {
                    entity.CreatedAt = now;
                    entity.CreatedBy = "testUser";
                }

                entity.ModifiedAt = now;
                entity.ModifiedBy = "testUser";
            }

            return result;
}
```

As you can imagine this didn't work. Can you provide me any solution ?

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore 3.1.4, Microsoft.EntityFrameworkCore.Relational 3.1.4
Database provider:  Microsoft.EntityFrameworkCore.SqlServer (Productive), Microsoft.EntityFrameworkCore.Sqlite (Testing) 
Target framework: : .NETCore 3.1
Operating system: Microsoft Windows 10
IDE: Visual Studio 2019 16.6.3

**Comment by ajcvickers** [comment]
@R4ZuL A command interceptor is likely not the right approach for this, since you're not to be able to change which properties to save at this point. Typically this is done by overriding SaveChanges. In EF Core 5.0, the [SaveChanges interceptor or event](https://github.com/dotnet/efcore/issues/15910) could be used instead.
