### ISSUE TITLE
Referencing desktop clr only projects in both frameworks in test project

### ISSUE THREAD

**Issue by suhasj** [dotnet/efcore#2187]
In the master branch the `EntityFramework.Relational.FunctionalTests` project references `EntityFramework.Core.Tests` and `EntityFramework.Core.FunctionalTests` in both frameworks while they are built only for desktop clr. Due to this we cannot open EF solution in VS 2015 RC and build the it. Anyway this can be fixed in the master branch ?

**Comment by ErikEJ** [comment]
Did you run:

   build initialize

**Comment by rowanmiller** [comment]
This is fixed in current code base so will soon be in master as part of the Beta 5 release
