### ISSUE TITLE
Regression when having indexer properties on a generic entity

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#21892]
I have generic entities in my app and everything worked as expected before the regression. Adding < T > to User here and having indexer properties ( Data ) triggers the regression.

The last version it worked on is : 5.0.0-rc.1.20380.1

Exception:
```
The entity type 'System.Collections.Generic.Dictionary<string, object>' cannot be added to the model because a shared entity type with the same clr type already exists.
```

``` C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;

public class User<T>
{
    public int Id { get; set; }
    public Dictionary<string, object> Data { get; set; }
}

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User<int>>().OwnsOne(x => x.Data, x =>
        {
            x.IndexerProperty(typeof(string), "a").IsRequired(false);
            x.IndexerProperty(typeof(string), "b").IsRequired(false);
        });
    }
}

class Program
{
    static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        var guid = Guid.NewGuid();
        sc.AddDbContext<AppDbContext>(op => op.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true;DataBase=" + guid));
        using (var provider = sc.BuildServiceProvider())
        {
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
                dbcontext.Database.EnsureCreated();
            }
        }

    }
}
```

EF Core version: 5.0.0-rc.1.20381.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 5.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
Note from triage: we will [re]introduce the APIs on owned types that will allow shared-type entity types to be used.

**Comment by AndriySvyryd** [comment]
@YeskaNova Now you need to call the new overload that has an additional string parameter for the name. Each owned type of type `Dictionary<string, object>` must have a different name.

**Comment by YeskaNova** [comment]
@AndriySvyryd Ok. Thanks all.

**Comment by YeskaNova** [comment]
@AndriySvyryd I have only added the ownedTypeName as you suggested, but it raises another exception, is it linked to this issue or should I create another one? 
![image](https://user-images.githubusercontent.com/4983925/89584944-3dd20480-d83d-11ea-9587-0a35c90e7e48.png)
