### ISSUE TITLE
Migration seed data does not respect "ValueGeneratedOnAddOrUpdate"

### ISSUE THREAD

**Issue by thehe** [dotnet/efcore#21904]
If you're using Seed-Data with EF.Migrations with Value-Generators, initial values are not created with "ValueGeneratedOnAddOrUpdate()" but only with "ValueGeneratedOnAdd()".

see my PR: https://github.com/dotnet/efcore/pull/21865
Problem seems to be the equality-comparison of a flag enum!

#### TimedEntity.cs (abstract)
``` C#
    public abstract class TimedEntity
    {
        [Column("created_at")]
        public DateTimeOffset CreatedAt { get; }

        [Column("updated_at")]
        public DateTimeOffset UpdatedAt { get; } // notice: not nullable here!
    }
```

#### Voucher.cs
``` C#
    [Table("vouchers")]
    public class Voucher : TimedEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("id")]
        [Key]
        public long Id { get; set; }

        [Column("code"), StringLength(100)]
        public string Code { get; set; }
   }
```

#### Migrations seed data - OnConfiguring:
``` C#
            var voucher = modelBuilder.Entity<Voucher>();
            voucher.Property(x => x.CreatedAt).ValueGeneratedOnAdd().HasValueGenerator<NowValueGenerator>();
            voucher.Property(x => x.UpdatedAt).ValueGeneratedOnAddOrUpdate().HasValueGenerator<NowValueGenerator>(); // notice: generate value on ADD *OR* UPDATE!

            voucher.HasData(new Voucher()
            {
                Code = "ABC1234",
                Id = 1
            });
           // no definition of createdAt or updatedAt here - should be filled out automatically
```

#### Results in:
``` C#
            migrationBuilder.InsertData(
                table: "vouchers",
                columns: new[] { "id", "created_at", "code" },  // notice: "updated_at" missing here!
                values: new object[,]
                {
                    { 1L, new DateTimeOffset(new DateTime(2020, 8, 2, 22, 42, 6, 105, DateTimeKind.Unspecified).AddTicks(4450), "ABC1234" },
                });
```

### Further technical details

EF Core version: 3.1.6
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (but irrelevant)
Target framework:  .NET Core 3.1
Operating system: RHEL7, RHEL8, Win10 Enterprise 20H2
IDE: VSCode, Visual Studio 2019 pro

**Comment by AndriySvyryd** [comment]
@thehe ValueGenerated configuration only affects values generated by the database, you don't need to specify them when using a client value generator. Also a value generator isn't currently used when updating, see https://github.com/dotnet/efcore/issues/6999

**Comment by thehe** [comment]
I'm quite confused now:

Why there is "created_at" then in the seed data and not "updated_at"?
When it shouldn't do anything regarding the client-side ValueGenerator, then there shouldn't be any difference between resulting "createdAt" and "updatedAt"?
But "updatedAt" is just missing in seed data.

Can you please describe what's preventing "updated_at" to get popoluted by the same exact value-generator (which just pushes out "DateTimeOffset.UtcNow" as value)

**Comment by AndriySvyryd** [comment]
When you configure a property as `ValueGeneratedOnAddOrUpdate` EF assumes that the value will always be provided by the database, therefore one supplied in the insert operation would either be  ignored or cause an error. However for `ValueGeneratedOnAdd` many databases do provide a way of provided a value that would override what would be generated by the database.

Usually the table auditing pattern is implemented purely on the database side, as that provides the most consistent values.
