### ISSUE TITLE
Microsoft.AspNETCore.Identity.EntityFrameworkCore

### ISSUE THREAD

**Issue by rajaansuggs** [dotnet/efcore#21903]
Hi! I'm having an issue to install 3 Nuget packages for working with databases on a Mac. These (among others) are having issues
1) Microsoft.AspNETCore.Identity.EntityFrameworkCore 
2) Microsoft.EntityFrameworkCore.SQLite
3) Microsoft.EntityFrameworkCore.Design

For instance, I'll get an error message that says "Could not add Microsoft.AspNETCore.Identity.EntityFrameworkCore" in the pop up at the top.

Here's what the Package Console outputs for an attempt at installing number 1 above or Microsoft.AspNETCore.Identity.EntityFrameworkCore in Nuget.

"Attempting to gather dependency information for package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5' with respect to project 'movie', targeting '.NETFramework,Version=v4.5'
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.aspnetcore.identity.entityframeworkcore/index.json
Total number of results gathered : 42
Gathering dependency information took 160 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	19 ms
Attempting to resolve dependencies for package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5'
Resolved actions to install package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5'
Retrieving package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.5' from 'nuget.org'.
For adding package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5' to project 'movie' that targets 'net45'.
Install failed. Rolling back...
Package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5' does not exist in project 'movie'
Package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.3.1.5' does not exist in folder '/Users/rajaansuggs/Projects/movie/packages'
Executing nuget actions took 23 ms
Could not install package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

How can I be able to install these packages so I could do database work?

I would like an Error Free solution for my Mac.

**Comment by smitpatel** [comment]
> Could not install package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

`Microsoft.AspNetCore.Identity.EntityFrameworkCore` does not support .NET Framework 4.5. It supports netcoreapp3.1 or any runtime which implements netstandard2.1 You can refer to [this chart](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) to see supported platforms for netstandard2.1
