### ISSUE TITLE
No data stores are configured

### ISSUE THREAD

**Issue by lovemory** [dotnet/efcore#2191]
Startup.cs  File:
// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add Application settings to the services container.
            services.Configure<AppSettings>(Configuration.GetSubKey("AppSettings"));

```
        // Add EF services to the services container.
        services.AddEntityFramework()
            .AddSqlServer()
            .AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

        // Add Identity services to the services container.
        //services.AddIdentity<ApplicationUser, IdentityRole>()
        //    .AddEntityFrameworkStores<ApplicationDbContext>()
        //    .AddDefaultTokenProviders();
        services.AddIdentity<ApplicationUser, ApplicationRole>()          //modify by hyq 2015-05-07
         .AddEntityFrameworkStores<ApplicationDbContext>()
         .AddDefaultTokenProviders();
        // Configure the options for the authentication middleware.
        // You can add options for Google, Twitter and other middleware as shown below.
        // For more information see http://go.microsoft.com/fwlink/?LinkID=532715
        services.Configure<FacebookAuthenticationOptions>(options =>
        {
            options.AppId = Configuration["Authentication:Facebook:AppId"];
            options.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
        });

        services.Configure<MicrosoftAccountAuthenticationOptions>(options =>
        {
            options.ClientId = Configuration["Authentication:MicrosoftAccount:ClientId"];
            options.ClientSecret = Configuration["Authentication:MicrosoftAccount:ClientSecret"];
        });

        // Add MVC services to the services container.
        services.AddMvc();

        // Uncomment the following line to add Web API services which makes it easier to port Web API 2 controllers.
        // You will also need to add the Microsoft.AspNet.Mvc.WebApiCompatShim package to the 'dependencies' section of project.json.
        // services.AddWebApiConventions();
    }
```

IdentityModels.cs File:

```
public class ApplicationUser : IdentityUser
{
    IdentityDbContext dbContext = new IdentityDbContext();
    public override ICollection<IdentityUserRole<string>> Roles
    {
        get
        {
            var user = dbContext.Users.Include(p => p.Roles).FirstOrDefault(q=>q.Id == this.Id);
            return user.Roles;
        }
    }

}
```

The Issue is:
when run at :var user = dbContext.Users.Include(p => p.Roles).FirstOrDefault(q=>q.Id == this.Id);

it  return a exception
  HResult=-2146233079
  Message=No data stores are configured. Configure a data store by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services.

**Comment by divega** [comment]
The way the services are wired up in an ASP.NET application, e.g. the call to 'AddDbContext<T>()' in 'ConfigureServices()' requires creating the instance of the DbContext through the mechanisms provided by dependency injection in order to work correctly.

The line in which you create the new instance of the ApplicationDbContext using the new operator  won't work as you expect because the context won't get access to the services and DbContextOptions configured at application startup.

The best way to create the context is to add it as a parameter in the constructor or as an injected property in a controller class.

Besides, I am not sure what you are trying to achieve, but it is generally not a great pattern to have the entity types depend on the context. 

My guess is now that other issues opened recently that referred to this same exception may have been caused by similar problems, so thanks for the repro.

**Comment by lovemory** [comment]
I am trying to get  Roles of the user，  but the "   Navigation property for users in the role" return empty.
See the following code


public IActionResult AddUser(string RoleID)  //get the users which not in the role
        {

            ViewBag.RoleID = RoleID;

            List<ApplicationUser> list_user = UserManager.Users.ToList();
            List<UserViewModel> list_user2 = new List<UserViewModel>();
            List<ApplicationRole>list_role =  RoleManager.Roles.ToList();
            foreach(ApplicationRole role in list_role)
            {
                
                foreach (ApplicationUser user in list_user)
                {
                    bool isIn = false;

                    foreach (ApplicationUserRole userrole in user.Roles) //I am trying to Roles of the user.
                    {
                        if (userrole.RoleId == RoleID)
                        {
                            isIn = true;
                        }
                    }
                    if (isIn == false)
                    {
                        if (!list_user2.Exists(p => p.UserID == user.Id))
                            list_user2.Add(new UserViewModel() { RoleID = RoleID, UserID = user.Id, UserName = user.UserName });
                    }
                }

            }


            return View(list_user2);

        }
