### ISSUE TITLE
EF Core errors when trying to make a scaffolded ASP.NET Controller

### ISSUE THREAD

**Issue by dominik246** [dotnet/efcore#21925]
ASP.NET Core MVC is throwing an error while trying to make a scaffolded MVC controller with EF core views.

### Steps to reproduce
1) Download the project from the attached link.
2) Right-click on the Controllers folder in the project, press Add -> New Scaffolded item
3) Select MVC Controller with views, using EF.
4) For "model class" select "StudentModel" from the dropdown list and for "data context" select "ServiceDbContext" and press Add.

Link to Github: [Github link](https://github.com/dominik246/EFCoreTestApp)
Link to error image: [Error link](https://i.imgur.com/R0iiiTN.png)

Error message:
```
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'StudentModel'
Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.Metadata.INavigation.get_DeclaringEntityType()'.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

### Further technical details

EF Core version: 5.0.0-preview.7.20365.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro 1909
IDE: Visual Studio Community 2019 16.6.5

**Comment by ajcvickers** [comment]
@dotnet/efcore Looks like this is due to a binary break when using EF Core 5.0 with ASP.NET Core 3.1. Updating the app to .NET 5 and updating the scaffolding package fixes the error. However, the updated scaffolding package won't run on .NET 3.1. We need to discuss whether this scenario (EF Core 5.0 on ASP.NET Core 3.1) will be something we support and/or recommend.
