### ISSUE TITLE
Why don't I have easy access to the model in migrations?

### ISSUE THREAD

**Issue by rykr** [dotnet/efcore#2193]
Forgive me if this is the wrong way to go about this but the wiki is out of date and there doesn't appear to be a forum for this.

I'm developing a provider and am wondering why in the ColumnDefinition method that is called from a create db op I don't have ready access to the property in the model that defines the column?  I have set StoreGeneratedPattern on the column in the model and simply want to check that value in the migration sql generator to generate the SQL.  However I am simply passed some values from the model (name, table, etc) along with the model and the AddColumnOperation object.

Yes, I could write a method to iterate through the model looking for my property but that seems needlessley inefficient as the EF framework has already mapped the column in the model to the AddColumnOperation.  Why should I have to go find it  again?

**Comment by bricelam** [comment]
I'm starting to work on some significant changes to the migrations pipeline for #1825, #1904 & #1975. When I'm finished, any provider-specific annotations on the model should flow into the migration operations.

Direct access to the model in a Migrations SQL generator is generally discouraged. Our intention is that you should only have to use it for truly exceptional operations like rebuilding a table.

**Comment by rykr** [comment]
Since a big part of EF is generating SQL from a model it seems counter-intuitive to say that you cannot access the model from the sql generator.  Why is it discouraged?

**Comment by rykr** [comment]
It seems quite simple to set the StoreGeneratedPattern on a property to Identity (for autoinc columns) and then in the ColumnDefinition method of the migrationsqlgeneator to simply check for that StoreGeneratedPattern and generate the appropriate SQL.  However the model property is not there.

**Comment by bricelam** [comment]
Generating DML from a model goes through the Migrations pipeline. This allows users to create database artifacts that don't directly map to items in their model. For example, a customer may want to create an auditing table with an autoincrementing column. In this case, there is no property in the model to look at the StoreGeneratedPattern.

Instead, you're provider should create a convention so whenever the StoreGeneratedPattern is set to Identity, an annotation like `MyProvider:Autoincrement=True` gets added. This would then flow into the migration operation.

Alternatively, a user could do something like this inside of their migration code:

```C#
migrationBuilder.AddColumn(
        name: "Id",
        type: "int")
    .ForMyProvider(x =>
    {
        x.AutoIncrement();
    });
```

The call to `AutoIncrement` would also add the `MyProvider:Autoincrement=True` annotation to the operation. In this case, there is no property object backing the `Id` column.

I hope this illustrate why we try to decouple DDL generation from the metadata model.

**Comment by rykr** [comment]
yes, thanks for the explanation.  That makes it more clear.
