### ISSUE TITLE
Restore.csproj failed to build while running dotnet tool install dotnet-ef

### ISSUE THREAD

**Issue by nullableobj** [dotnet/efcore#21930]
I had ef 3.0.0 and advised to update to 3.1.0. Direct update failed so I uninstalled ef from dotnet tool and tried to reinstall it again. I got error while building a restore project in path like this: [/var/folders/gt/9l4q1djd12d__wt0cxkqyrc80000gn/T/gkjf01jk.whw/restore.csproj]
I passed verbosity option for detailed (--v d) with install command and it seems there is exception at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
I am not sure this is an actual bug or this is a problem with my environment. I am running on macos 10.15.6 and dotnet 3.1.302. This is happened also if I downgrade to dotnet 3.1.100.
<img width="987" alt="Screen Shot 2020-08-04 at 14 36 02" src="https://user-images.githubusercontent.com/20289652/89300923-df502f00-d660-11ea-9185-802f753ab76f.png">
<img width="1421" alt="Screen Shot 2020-08-04 at 14 41 24" src="https://user-images.githubusercontent.com/20289652/89300937-e414e300-d660-11ea-90c5-4d8471e0855d.png">

**Comment by nullableobj** [comment]
I am really struggling with this situation. I uninstalled vs4mac and all .net sdk and runtime from uninstaller tool and installed everything. Same problem.  I would appreciate if this can get your attention @ajcvickers 🙏
<img width="1421" alt="Screen Shot 2020-08-05 at 13 46 52" src="https://user-images.githubusercontent.com/20289652/89414634-a7112500-d722-11ea-95c3-54e79916e48b.png">

**Comment by ajcvickers** [comment]
@nullableobj The stack traces indicate a failure in NuGet. Please file a new issue at https://github.com/NuGet/Home so that the NuGet team can take a look.

**Comment by nullableobj** [comment]
I moved issue here https://github.com/NuGet/Home/issues/9876
