### ISSUE TITLE
Consider adding EF regression tests to NuGet's PMC test suite

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#2196]
NuGet has a suite of test for the Package Manager Console that they run on VS. We can add a test that downloads a stable version of the EntityFramework package and exercise our PowerShell commands. 

@yishaigalatzer and I talked about this as a way to prevent regressions like #1950 from happening in the future.

**Comment by ErikEJ** [comment]
+1 - and maybe also https://github.com/aspnet/EntityFramework/issues/2152 ?

**Comment by ajcvickers** [comment]
This hasn't been causing the problems that it used to cause, so closing.
