### ISSUE TITLE
Code First Migrations: Add Parameter to verify connection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21981]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/378574/code-first-migrations-add-parameter-to-verify-conn.html)._

---
<p>When working on a team with multiple developers, and those developers have connection strings that allow schema changes to non-local db servers (test, stage, pre-production, etc), we sometimes run into issues where we are connected to a non-local dev db when running a migrations check, thanks to long hours and arguments out of range exceptions in our own personal mental-multi-tasking.</p><p>I've considered creating a custom migration script to enforce verification of the connection string, but this would require maintenance on over a dozen dev machines in the event that the .NET migrations scripts are overwritten, new installs, or reinstalls.</p><p>I'd like to request a parameter, perhaps &quot;-V&quot; or &quot;-Verify&quot; that prompts the user with the current connection Server and Database names and a required Y/N input to continue.</p><p>This parameter should be optional for &quot;Add-Migration&quot; and &quot;Update-Database.&quot;</p><p>It would be even better if this parameter was REQUIRED if you have a node in your config's appSettings section to trigger the requirement...something like:</p><p>&lt;add key=&quot;migration:validation&quot; value =&quot;required&quot; /&gt;</p>

---
#### Fiona Niu[MSFT] on 11/9/2018, 01:24 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by ajcvickers** [comment]
This is not something we plan to implement in the PMC tools. However, see https://github.com/dotnet/efcore/discussions/21971 for some customization ideas.
