### ISSUE TITLE
Suppress warning to fully qualify EntityFramework version in Package Manager Console when EntityFramework version is fully qualified

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21980]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/392139/suppress-warning-to-fully-qualify-entityframework.html)._

---
<p>When I use Add-MIgration or Update-Database I get this helpful message:</p><p>Both Entity Framework 6.x and Entity Framework Core commands are installed. The Entity Framework 6 version is executing. You can fully qualify the command to select which one to execute, 'EntityFramework\Add-Migration' for EF6.x and 'EntityFrameworkCore\Add-Migration' for EF Core.</p><p>The annoying thing is that I get it even when I do fully qualify the command I'm using. Might be nice to check if the command was qualified already before displaying the warning</p>

---
#### Jane Wu [MSFT] on 11/27/2018, 00:31 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by ajcvickers** [comment]
This isn't something we plan to fix; it's uncommon to need the EF6 and EF Core tools both loaded at the same time.
