### ISSUE TITLE
Column.TypeName should not be case-sensitive

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21982]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1128285/columntypename-should-not-be-case-sensitive.html)._

---
I changed my entity property from:

[Column(TypeName = "NVARCHAR(MAX)")]
    public string Notes { get; set; }

To:

[Column(TypeName = "nvarchar(max)")]
    public string Notes { get; set; }

And it produced this code in the migration:

migrationBuilder.AlterColumn<string>(
                name: "Notes",
                table: "Vendors",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "NVARCHAR(MAX)",
                oldNullable: true);

I don't think the `TypeName` property should be case-sensitive this way.

---
#### Feedback Bot on 7/29/2020, 02:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by roji** [comment]
Note that while `nvarchar(max)` may be the same as `NVARCHAR(MAX)` may be the same on SQL Server, in other database case-sensitive types may exist.

Regardless, have you encountered any negative consequence of the AlterColumn operation above?

**Comment by ajcvickers** [comment]
Closing as by-design.
