### ISSUE TITLE
When I Adding a related entity, the entity state is modified not Added ,the entity Key Type is Guid, it work if the Key Type is string.

### ISSUE THREAD

**Issue by wushizhan** [dotnet/efcore#21997]
When I Adding a related entity, the entity state is Modified not Added ,the entity Key Type is Guid. it work if the Key Type is string.

### Steps to reproduce

            using var dbContext = new TestDbContext();
            var userId = new Guid("332DA567-1CF8-48DD-9424-1AD49FD6CF39");
            //init root entity
            //var user = new AppUser(
            //    userId,
            //    "testUserName");
            //dbContext.Add(user);
            //dbContext.SaveChanges();

            var user = dbContext.AppUsers
                .Include(x => x.AppUserConfigs)
                .Where(x => x.Id.Equals(userId))
                .FirstOrDefault();

            var userConfig = new AppUserConfig(
                Guid.NewGuid(),
                userId,
                "6666");

            user.AppUserConfigs.Add(userConfig);
            // there userConfig state is Modified, why not Added
            var entries = dbContext.ChangeTracker.Entries();
            // error on Save, bacause no data in database
            dbContext.SaveChanges();

    public class TestDbContext : DbContext
    {
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<AppUserConfig> AppUserConfigs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source =.;Initial Catalog=TestCode; User ID=sa;Password=*******;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AppUser>().ToTable("TB_AppUser");
            modelBuilder.Entity<AppUser>().HasKey(x => x.Id);
            modelBuilder.Entity<AppUser>().HasMany(x => x.AppUserConfigs).WithOne().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<AppUserConfig>().ToTable("TB_AppUserConfig");
            modelBuilder.Entity<AppUser>().HasKey(x => x.Id);
        }
    }

    public class AppUser
    {
        public Guid Id { get; protected set; }
        public string UserName { get; protected set; }

        public List<AppUserConfig> AppUserConfigs { get; protected set; }

        protected AppUser()
        { 
        }

        public AppUser(
            Guid id,
            string userName)
        {
            Id = id;
            UserName = userName;
            AppUserConfigs = new List<AppUserConfig>();
        }
    }

    public class AppUserConfig
    {
        public Guid Id { get; protected set; }
        public Guid UserId { get; protected set; }
        public string CorporationId { get; protected set; }

        protected AppUserConfig()
        { 
        }

        public AppUserConfig(
            Guid id,
            Guid userId,
            string corporationId)
        {
            Id = id;
            UserId = userId;
            CorporationId = corporationId;
        }
    }

### Further technical details

EF Core version: 3.1.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.5

**Comment by MaivKhanhPr0** [comment]
[]()

**Comment by wushizhan** [comment]
oh! I find the error. if UserSqlserver then EFCore Default Create Id, So Set Property to No value generation
