### ISSUE TITLE
Add runtime annotation support to model

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#22031]
1. These annotations provide caching capabilities to the model.
2. Can only be added after a model is built
3. Aren't returned with normal annotations

Can be used to store the relational model, `TypeMappingSource`, relational overrides (that don't affect configuration), property indexes/accessors, generating/propagating properties in `ValueGenerationManager`

Related to #9329, #19213, #19806 and #21901

Also review the nullability of some methods: `GetKeyValueComparer`, `CreateDependentsMapFactory`, etc...

**Comment by lauxjpn** [comment]
Are those the same as regular annotations, with the key difference of not leaking into any output files, and are therefore intended (from a provider point of view) to keep track of stuff internally, without the need to carefully clean-up those annotations later on?

**Comment by AndriySvyryd** [comment]
@lauxjpn The key difference is that non-runtime annotations cannot be mutated after the model is built. Runtime annotations can appear in files, like the compiled model in some cases to improve perf.

The providers are free to use both as they see fit. Any that shouldn't be output can be removed in classes derived from `RuntimeModelConvention` and `CSharpRuntimeAnnotationCodeGenerator`
