### ISSUE TITLE
Interceptors registering

### ISSUE THREAD

**Issue by MursalovAltun** [dotnet/efcore#22043]
Setting CreatedAt, ModifiedAt, CreatedBy not using the SaveChanges() method override.
I would like to implement this the way that doesn't break Open-Closed SOLID principle.

To implement these events [#15910](https://github.com/dotnet/efcore/issues/15910) also as interceptors.
Allow registering interceptor for specific DbContext using DI separated from the AddDbContext<T>(DbContextOptionsBuilder).

**Comment by ajcvickers** [comment]
Duplicate of #21578
