### ISSUE TITLE
Microsoft.Data.Sqlite version 3.1.7 creates SQLite database of version 3.28.0 that has security vulnerabilities

### ISSUE THREAD

**Issue by jacobkochekkan** [dotnet/efcore#22042]
I have created a .Net core application (.net core version 3.1.*) that uses Microsoft.EntityFrameworkCore.Sqlite(3.1.7) that internally uses Microsoft.Data.Sqlite. When I create a database and check its version using the code below, I get the created databases version  as 3.28.0.

`SqliteConnection connection = new SqliteConnection(this.connectionString);`
            `string stm = "SELECT SQLITE_VERSION()";`
            `connection.Open();`
            `using var cmd = new SqliteCommand(stm, connection);`
            `string version = cmd.ExecuteScalar().ToString();`

Since SQLite version 3.28.0 has some security vulnerabilities as mentioned in [this](https://www.cvedetails.com/version/334686/Sqlite-Sqlite-3.28.0.html) article, I would like to know if there is a version of Microsoft.EntityFrameworkCore.Sqlite that I could use that would create a SQLite database with the latest version 3.32.3

**Comment by ajcvickers** [comment]
@ericsink @bricelam Thoughts on getting 3.32.3 into a build?

**Comment by ericsink** [comment]
Yes, I need to make this happen.

**Comment by ericsink** [comment]
ericsink/SQLitePCL.raw#356

**Comment by ajcvickers** [comment]
Closing this as external. Once a new SQLitePCL.raw is available the dependency bot will update M.D.Sqlite accordingly.

**Comment by jacobkochekkan** [comment]
I updated to Microsoft.EntityFrameworkCore.Sqlite(3.1.10) and Microsoft.EntityFrameworkCore.Sqlite(5.0.0), for both, the below code still gives me database version of **3.28:**

SqliteConnection connection = new SqliteConnection(this.connectionString);
string stm = "SELECT SQLITE_VERSION()";
connection.Open();
using var cmd = new SqliteCommand(stm, connection);
string version = cmd.ExecuteScalar().ToString();
