### ISSUE TITLE
Consider disabling GitHub discussions

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22047]
We've been using them for a while now, but I don't think they are adding value. People file discussions as issues, and issues as discussions, and I don't see this changing. So we now have a parallel channel for tracking issues and questions which is harder to label/manage. I don't think this is adding value.

**Comment by ralmsdeveloper** [comment]
I believe that the Github discussions is extremely important if the community know how to use it, the Github discussions should be the channel for the community to propose new features, improvements and talk about performance.

**Comment by ErikEJ** [comment]
Agree with Arthur, not adding any value, just confusion

**Comment by SayusiAndo** [comment]
`<TwoCents>`
The question whether EF Core team members plus the active community members, have enough energy to train the community how to use it? My gut feeling is no. Not to mention some rights should be distributed to move items from Discussions to Issues and vica versa. 

Questions put in issues were always welcomed and answered before Discussions. I also feel it adds unnecessary complexity to an already working process. If I were Atrur's shoes, I would make the same suggestion.
`</TwoCents>`

**Comment by ajcvickers** [comment]
For the time being, we are closing down the GitHub discussions tab on the EF repo. Instead, we will go back to using [issues](https://github.com/dotnet/efcore/issues) to answer questions and hold discussions. Issues are currently much easier to track, label, and manage.

We will likely reevaluate the GitHub discussions feature again in the future once it has become more mature.
