### ISSUE TITLE
Query: consider updating select expression identifiers when projecting a subset of column and adding distinct

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#22049]
Currently we use keys of all entities in chain as identifiers for the select expression. This becomes a problem when applying distinct - if the keys are not part of the projection we can no longer identify it. However in case of distinct we could change identifiers to become all of the projected (at least in some cases). need to investigate whether its correct thing to do for complex scenarios (nav chains?) and what is perf impact

**Comment by ajcvickers** [comment]
See also scenario in #23897

**Comment by maumar** [comment]
lots of people are hitting this, we should re-triage and fix it sooner if possible
