### ISSUE TITLE
foreach Loop Query not Disposing

### ISSUE THREAD

**Issue by 0b01** [dotnet/efcore#22065]
Hi team,

I am investigating a bug in Visual Studio DiagnosticsHub(Debug > Performance Profiler > Database).

The minimal reproducible example is:

```C#

foreach (var blog in db.Blogs)
    db.Posts.Where(p => p.Blog.BlogId == blog.BlogId).Count()
```

* DiagnosticsHub uses [DataReaderDisposing](https://github.com/dotnet/efcore/blob/35a6aaf1abdef511943d189f064de979bb39a344/src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs#L3775) diagnostic event which contains recordsAffected and readCount

* In the example above, the DataReader for the first SELECT query(`SELECT "b"."BlogId" FROM "Blogs" AS "b"`) is not disposed, as a result DataReaderDisposing event is never fired

### Steps to reproduce

1. Create an empty console app
2. Copy attached Program.cs into ConsoleApp1/Program.cs
3. Download and place [sqlite database](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1128861/) to solution root
4. Debug>Performance Profiler>Database
5. Save diagsession to Desktop/1.diagsession
6. Open PerfView > diagsession file > Events
![image](https://user-images.githubusercontent.com/1768528/90286039-dbbf6380-de29-11ea-967a-d9f204bb3d80.png)
7. Under Activity2Stop:
![image](https://user-images.githubusercontent.com/1768528/90286055-e4b03500-de29-11ea-85da-795b3ca82747.png)

```C#
// Program.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;

namespace EFTestApp
{
    public class Program
    {
        public static void Main()
        {
            using (var db = new BloggingContext())
            {
                foreach (var blog in db.Blogs)
                {
                    Console.WriteLine(blog.Url);
                    var blogPosts = db.Posts.Where(p => p.Blog.BlogId == blog.BlogId);
                    Console.WriteLine("Number of posts: {0}", blogPosts.Count());
                }
                System.Threading.Thread.Sleep(1000);
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string path = "";
            string localPath = "../../DatabaseSQLiteDb.db";
            string containerPath = "./DatabaseSQLiteDb.db";

            if (File.Exists(localPath))
            {
                path = localPath;
            }
            else if (File.Exists(containerPath))
            {
                path = containerPath;
            }
            else
            {
                throw new Exception("Unable to find database file");
            }

            optionsBuilder.UseSqlite($"Data Source={Path.GetFullPath(path)}");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Blog Blog { get; set; }
    }
}
```

FYI my alias is liha and you can reach me on Teams if you need further clarification.

**Comment by ajcvickers** [comment]
@0b01 I am not able to reproduce this. However, the code here is executing additional queries while still consuming the results of the first query. Some points about this:
* A data reader will be created and disposed for each of these queries.
* If no results are returned from the first query (i.e. no blogs in the database), then the foreach will be a no-op and no additional queries will be run. In this case I see one data reader created and disposed.
* If there are results, then I see this sequence of events:
  * Top-level data reader is created
  * A data reader is created and disposed for each of the inner queries
  * The top-level data reader is disposed
* This "multiple active result sets" capability is not supported by all database providers. It works with SQLite and SQL Server (with MultipleActiveResultSets=true in the connection string) but not in most other databases.
  * For other databases buffering will occur in EF, which means the first data reader will always be disposed before new ones are created.
  * EF Core also does this if buffering is turned on for some other reason--notably Azure connection resiliency.

**Comment by ajcvickers** [comment]
My code for playing with this:

```C#
public class Program
{
    public static void Main()
    {
        // using (var db = new BloggingContext())
        // {
        //     db.Database.EnsureDeleted();
        //     db.Database.EnsureCreated();
        //
        //     var blog1 = new Blog();
        //     var blog2 = new Blog();
        //
        //     db.AddRange(
        //         new Post {Blog = blog1},
        //         new Post {Blog = blog2},
        //         new Post {Blog = blog1},
        //         new Post {Blog = blog2});
        //
        //     db.SaveChanges();
        // }
        
        using (var db = new BloggingContext())
        {
            foreach (var blog in db.Blogs)
            {
                Console.WriteLine(blog.Url);
                var blogPosts = db.Posts.Where(p => p.Blog.BlogId == blog.BlogId);
                Console.WriteLine("Number of posts: {0}", blogPosts.Count());
            }
            System.Threading.Thread.Sleep(1000);
        }
    }
}

public class BloggingContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole().SetMinimumLevel(LogLevel.Debug));
        
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlite($"Data Source=test.db");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public Blog Blog { get; set; }
}
```

**Comment by 0b01** [comment]
@ajcvickers Hi Arthur, thanks for investigating and the info on how it works. I noticed it is actually disposing correctly but the ActivityID is missing as you can see in the screenshot:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/1768528/90439319-38b95480-e08a-11ea-85b2-b27d57c7dc4b.png)

Is there a reason ActivityId is missing? Also, is CommandId suitable for tracking start stop events?

**Comment by ajcvickers** [comment]
@0b01 My understanding from the original design of ActivityID several years ago is that it doesn't support interleaved start/stop in a given async context. This is when the inner data reader completes it resets the ActivityID, which then means that when the outer data reader completes the ActivityID is already null. This was considered an acceptable limitation, with the understanding that it would not work for interleaved events such as are possible from most objects that don't have a single ambient instance.

Yes, CommandId is designed for correlating commands.

**Comment by 0b01** [comment]
@ajcvickers, It turns out the rationale behind using ActivityId instead of CommandId is because CommandId is missing from DiagnosticSource. CommandEventData(which contains DbCommand and is only used by *Executing) inherits from another class so it is not accessible in DiagnosticSource. I have submitted another issue to dotnet runtime: https://github.com/dotnet/runtime/issues/41300

There is nothing to be done in efcore repo. Thank you for the clarification.
