### ISSUE TITLE
Migration will add all subclasses to the join table if the join table property is in a parent class

### ISSUE THREAD

**Issue by iWangJiaxiang** [dotnet/efcore#22112]
I have a many to many relation for my models, which was implemented by [join table](https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration). 

In my case, one of the model in m2m join table model is **inherited** from an abstract class `ClaseBase` that has m2m table model property.

The issue is the generated migration file will create all models inheriting  `ClaseBase`  as fields in the join table.

These unexpected fields are primary keys, which will cause  migration failure for further modification of join table.

### Steps to reproduce

Please go to my reproducing repo and watch the readme

[iWangJiaxiang/EfCoreMany2ManyBugReproduction](https://github.com/iWangJiaxiang/EfCoreMany2ManyBugReproduction/tree/master)

### Further technical details

EF Core version: 3.1
Database provider: any
Target framework:  .NET Core 3.1
Operating system: Windows
IDE: Visual Studio 2019 16.7

**Comment by ajcvickers** [comment]
@iWangJiaxiang Given that `Tags` is on `BookBase`, what is your expectation for the contents of `Tags` when the instance is a `BookB`? Is it invalid to access? Should it always be empty? Should it also represent a many-to-many to Tags, like it would if the instance is a `BookA`?

**Comment by iWangJiaxiang** [comment]
@ajcvickers Thanks for your reply!

It turns out the issue of my design.

Right now the m2m relationship is limited to `BookA` and `Tag`, but in the future the `BookB` will have this m2m relationship as well. I am considering whether to share same `BookTag` model with a **discriminator** or something like `BookATag`/`BookBTag`.

Since the `BookB` model is not present in `BookTag` . the `BookBId` field will be empty and impossible to access.

I am curious about why the `BookBId` field has been created implicitly? There is only one-way access for `BookB`/`BookTag` m2m right (From `BookB` to `Tag`).

**Comment by ajcvickers** [comment]
@iWangJiaxiang EF doesn't need navigation properties on both sides of the relationship. Since BookB.Tags (from BookBase) relates BookB  to BookTag, the relationship exists and EF creates an FK for it.

**Comment by iWangJiaxiang** [comment]
@ajcvickers Thank you
