### ISSUE TITLE
Setting DbContextOptionsBuilder.UseXXXX before instantiating context - no DbContext ctor overload takes builder

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#2211]
In earlier bits, you could create a DbContextOptions object and set options such as UseInMemoryStore on it, then pass it in to an overloaded constructor of your context and then pass it on to DbContext ctor ala:

```
public MyContext(DbContextOptions options) :base(options)
        { } 
```

But now we use DbContextOptionsBuilder for those settings, yet the DbContext ctor overload still takes a  DbContextOptions type. 

I'm guessing there is a new coding pattern but I'm not finding it when looking through various tests.

So can you point me to a test that shows how to pass it, unless the you just need to add a new overload to the dbcontext.ctor.

thanks

**Comment by julielerman** [comment]
cc @bricelam

**Comment by ajcvickers** [comment]
@julielerman Most of the time you would just use the DbContextOptionsBuilder in the AddDbContext method (usually for an ASP.NET app) or override the OnConfiguring method which gives you the builder.

If you want to create your DbContextOptions explicitly, then use DbContextOptionsBuilder to build it, and then use the Options property on the builder to get the finished options. You can then pass this into your context constructor. However, this is rarely necessary--in fact we were very close to removing this constructor entirely.

**Comment by julielerman** [comment]
AddDbContext in asp.net makes sense. 

And yah...  "don't use EF7 right now unless you are in ASP.NET5" but you know, I'm building demos and trying to keep them simple so people can see EF7 without the confusion of ASP.NET 5.

I was trying this was to find a way to build demos that could easily flip from sqlserver to inmemory.

anyway...I had missed the Options property on DbContextOptionsBuilder. (this is another one of those, I wish I could ask a question without raising an issue...)

Thanks. Nothing to see here.

Also, added an issue to modify the wiki topic about this pattern so that it shows using the builder instead of options https://github.com/aspnet/EntityFramework/issues/2216

thanks!
