### ISSUE TITLE
Unable to generate migrations

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#2213]
When running `dnx . ef migration script`, I get the following:

```
System.InvalidOperationException: No service for type Microsoft.Data.Entity.Relational.Migrations.Migrator' has been registered.
```

I've been using UnicornStore as an example, but haven't been able to pinpoint where I might be missing something.

**Comment by bricelam** [comment]
Which data store provider are you using?

**Comment by atrauzzi** [comment]
SQL Server

**Comment by bricelam** [comment]
Is you DbContext in a separate project than your Startup.cs? Could you share you DbContext and Startup classes?

**Comment by atrauzzi** [comment]
For sure, hang on, I'll make a gist.

**Comment by atrauzzi** [comment]
Here ya go: https://gist.github.com/atrauzzi/56fa19e938cf4d71b0ca

Very basic stuff, I'm studying my way into ASP.NET 5 and EF7, so if it's a sloppy mistake, I apologize.

**Comment by bricelam** [comment]
It looks like `ConfigureServices` isn't getting called. Is it in the same project as your DbContext?

**Comment by atrauzzi** [comment]
Everything is in one project. I'm just trying to get basic bootstrap going here.

**Comment by bricelam** [comment]
@atrauzzi Were you ever able to get this working? If not, I'll try and dig into reproducing the issue locally.

**Comment by atrauzzi** [comment]
Sorry, I haven't had time to look into this any more.  Although obviously we can keep this ticket as an archive of things if it comes up again.

**Comment by bricelam** [comment]
Yes, please feel free to reopen! (I was just pruning my personal backlog of issues.)

**Comment by dazinator** [comment]
I hit this error today (using RC1) - and it was because I forgot the `UseSqlServer()` call!

This makes me wonder - @atrauzzi - perhaps try changing the order of those calls so that `UseSqlServer()` is _after_ `AddDbContext` - that's just a hunch as I haven't actually tried replicating..
