### ISSUE TITLE
EF keeps internal reference to entity types after query

### ISSUE THREAD

**Issue by rayao** [dotnet/efcore#2214]
It seems a regression, in Beta3 or Beta4 my UT worked as expected.

The scenario:
- We generate (IL.Emit) some dynamic types as entity types.
- We generate a subclass of DbContext.
- We build a ServiceCollection and hence IServiceProvider.
- We build DbContextOptions with DbContextOptionsBuilder.
- We create an instance of the DbContext (subclass) with IServiceProvider and DbContextOptions as parameters.
- We query some data with the DbContext instance.
- We dispose the DbContext instance.
- We call GC.Collect, GC.WaitForFullGCComplete, GC.WaitForPendingFinalizers several times then verify that those dynamically generated types are all collected.

Results:
- The UT passes on earlier EF beta build, but now fails on beta5.
- On beta5, if we comment out the query call, dynamic types could be collected. So I suspect there's some internal reference (cache maybe) to entity types (or their members) not cleared after a query run.

**Comment by ajcvickers** [comment]
@rayao Can you confirm that the IServiceProvider is being collected? If it is, then everything else should be free to be collected and there may be a bug here. If not, then this is by design because the query cache persists at the IServiceProvider level.

**Comment by rayao** [comment]
@ajcvickers Thank you Arthur, I verified that the IServiceProvider is NOT collected. But I think that's just a result of a hidden reference chain, not the root cause.
Or maybe I made something wrong writing this code? I assume not since the only call that makes different result is the query, and as I said with EF earlier beta build this UT passed.

        [TestMethod]
        public void TestAccessGenWithExternalType()
        {
            var weak = Task.Run(() => GenAccessContextAndModelWithExternalType()).Result;
            // Makes no difference without Task.
            //var weak = GenAccessContextAndModelWithExternalType();

            for (int i = 0; i < 3; i++)
            {
                GC.Collect();
                GC.WaitForFullGCComplete();
                GC.WaitForPendingFinalizers();
            }
            Assert.IsFalse(this.serviceProvider.IsAlive);
            Assert.AreEqual(null, weak.Target);
        }

        WeakReference serviceProvider;

        DbContext CreateDbContext(Type dbContextType, string connectionString, IEdmModel model)
        {
            var collection = new ServiceCollection();
            collection.AddEntityFramework().AddSqlServer();

            var provider = collection.BuildServiceProvider();
            var optBuilder = new DbContextOptionsBuilder();
            optBuilder.UseModel(ModelBuilderOnEdm.BuildModel(model)).
                UseSqlServer(connectionString);

            serviceProvider = new WeakReference(provider);
            return (DbContext)Activator.CreateInstance(dbContextType, provider, optBuilder.Options);
        }

        IQueryable DbSet(DbContext context, Type entityType)
        {
            var method = context.GetType().GetMethod("Set").MakeGenericMethod(entityType);
            return (IQueryable)method.Invoke(context, null);
        }

        WeakReference GenAccessContextAndModelWithExternalType()
        {
            // The app.config file contains connections strings that are in reference to the DataDirectory, therefore the
            // data directory needs to be initialized since the tests are not running within ASP.NET
            // (http://msdn.microsoft.com/en-us/library/vstudio/cc716756(v=vs.100).aspx).  The use of 
            // DataDirectory avoids the need of an absolute path within the config file.
            AppDomain.CurrentDomain.SetData("DataDirectory", System.IO.Directory.GetCurrentDirectory());
            using (var connection = new System.Data.SqlClient.SqlConnection("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\AccTest.mdf;Integrated Security=True;Connect Timeout=30"))
            {
                connection.Open();
                using (var ctx = new AccessSystemDbContext(connection.ConnectionString))
                {
                    var svcLocator = new AccessSvcLocator();
                    var model = EntityParser.ParseObjects(ctx, svcLocator);
                    Assert.AreNotEqual(null, model);

		    // This generate dynamic CLR types including a subclass of DbContext, returned as tup.Item1
                    var tup = EntityContextBuilder.CreateContextType(svcLocator, typeof(DbContext), model);

                    Assert.AreNotEqual(null, tup.Item1);
                    Assert.AreNotEqual(null, tup.Item2);
                    Assert.IsTrue(svcLocator.ExternalHub.AddHandlerCalled);

                    using (var dbContext = CreateDbContext(tup.Item1, connection.ConnectionString, tup.Item2))
                    {
                        var contactType = tup.Item1.Assembly.GetTypes().First(e => e.Name == "Contacts");
                        var dbSet = DbSet(dbContext, contactType);

			// This single line makes a difference, comment out it the UT passes.
                        var list = dbSet.Cast<object>().Take(2).ToList();

                        return new WeakReference(tup.Item1);
                    }
                }
            }
        }

**Comment by rayao** [comment]
Hey guys perhaps I found the root cause, if I change the test method this way it'll pass.
So I believe the root cause is EF makes a heavy use of ConcurrentDictionary (and hence ConcurrentBag) which uses thread local storage (TLS) as its backing storage, and that storage will only perish when the thread exits.
If you browse bugs opened by me there's a similar one I believe caused by same reason, and that one has a GCRoot dump.

So I think it may still be a problem here:
* EF should eagerly clean up caches in ConcurentDictionary (in Dispose() method at least), not relying on GC to clean it up, the very reason is that ConcurrentDictionary stores everything in TLS, and TLS only gets collected when the owning thread exists.
* async calls make use of thread pool threads, we can't control lifetime of those threads, hence can't control lifetime of those references, hence the lifetime of a generated dynamic type.
* There has been a lot of discussion on ConcurrentDictionary, its very nature sometimes results in real bug. There's a thread in our internal ASP.NET discussion group talking about a static ConcurrentDictionary references lots of very old threads (by storing values in their TLS) and hence preventing those threads from being collected, thus consumes too much resources of the process and corrupts it. If you want I can try searching it for you.
So, please consider if there's possibility to clean up those caches in an eager way.

        [TestMethod]
        public void TestAccessGenWithExternalType()
        {
           WeakReference weak = null;
            var thread = new System.Threading.Thread(param =>
            {
                weak = GenAccessContextAndModelWithExternalType();
            });
            thread.Start();
            thread.Join();
            Assert.AreEqual(System.Threading.ThreadState.Stopped, thread.ThreadState);

            for (int i = 0; i < 3; i++)
            {
                //System.Data.SqlClient.SqlConnection.ClearAllPools();
                GC.Collect();
                GC.WaitForFullGCComplete();
                GC.WaitForPendingFinalizers();
                //await System.Threading.Tasks.Task.Delay(2000);
            }
            Assert.IsFalse(this.serviceProvider.IsAlive);
            Assert.AreEqual(null, weak.Target);
        }

**Comment by rayao** [comment]
Sorry guys, this is false alarm.
I've just realized that the IServiceProvider is also IDisposable, and as long as it's disposed, everything is GAC'd, which is awesome!

**Comment by divega** [comment]
@rayao Thanks for following up. I am glad to hear that it is now working as intended for you.
