### ISSUE TITLE
Crash on UWP when configuring entities with interfaces

### ISSUE THREAD

**Issue by rick-palmsens** [dotnet/efcore#22159]
I recently added some interfaces for our entities to enforce certain properties, but this results in a `PlatformNotSupportedException` from the call to `GetRuntimeInterfaceMap` on UWP:

![image](https://user-images.githubusercontent.com/57390463/90869134-17ad7800-e398-11ea-9aab-903489fe7efd.png)

### Steps to reproduce
Have a few `IEntityTypeConfiguration` for entities with an interface, and configure them with `ApplyConfigurationsFromAssembly`

Some deeper stack trace:
![image](https://user-images.githubusercontent.com/57390463/90869597-bcc85080-e398-11ea-8774-93f5c3c65286.png)

### Further technical details

EF Core version: 3.1.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: UWP 1903
Operating system: Windows
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment]
Note from triage: UWP is not supported in .NET 6.
