### ISSUE TITLE
Test runner failing on release/5.0 because of new VB analyzer dependency

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22177]
Main branch is working fine.

Error:
```
CSC : error AD0001: Analyzer 'Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer' threw an exception of type
'System.IO.FileNotFoundException' with message 
'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
[/home/ajcvickers/efcore/src/EFCore.Proxies/EFCore.Proxies.csproj]
```
for all the tests.

**Comment by ajcvickers** [comment]
I'm running into this again and cleaning doesn't always work.

**Comment by ajcvickers** [comment]
This is hitting me a lot when switching branches. It may be related to dotnet processes running in the background.

**Comment by roji** [comment]
Yeah, unless I'm mistaken, the compiler (probably including analyzers?) is kept running in the background, so if you're switching from an old analyzer version to a new one, something like this may happen. `dotnet build-server shutdown` may help on the cmdline.

I'll play around with it a bit to try to understand.

**Comment by roji** [comment]
Also flagged by @sebastienros for the benchmarks: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D779625%26view%3Dlogs%26j%3D624e7fb7-5c98-5486-5327-c11d2337f7d0%26t%3D2359c25d-30a0-55a2-ec7b-07ef5e18701f&data=02%7C01%7CShay.Rojansky%40microsoft.com%7C4f48560ae7064fc1e14108d845338f6e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637335435052072154&sdata=Op2xdZoIJVREuCThtAlkT%2Bx93PfdpSc027OsMdgkAUw%3D&reserved=0

**Comment by roji** [comment]
Yeah, what I wrote above checks out. To repro on the cmdline:

* Check out out any commit before bc6832998694a8848a189310d36d92ddb3b4c507 (which is where I rewrote the analyzer and added the VB dependency)
* Do `dotnet build-server shutdown` to start from a clean slate
* Run any tests (e.g. EFCore.Tests)
* Check out bc6832998694a8848a189310d36d92ddb3b4c507 with the new dependency
* Run the tests again, you should get the failure (Could not load file or
 assembly 'Microsoft.CodeAnalysis.VisualBasic)
* Do `dotnet build-server shutdown` again
* Run the tests again, everything works fine

@sebastienros are benchmark builds still failing because of this? If so, is there any chance we're mixing two versions of EF here?

**Comment by ajcvickers** [comment]
@roji The thing I don't understand about this is that there should be no commits in the main branch that are not also in the release/5.0 branch, so I should not be building different versions of the analyzer code.

**Comment by sharwell** [comment]
I'm very familiar with this particular error. Where can I find the implementation of the analyzer in question?

**Comment by ajcvickers** [comment]
@sharwell https://github.com/dotnet/efcore/tree/release/5.0/src/EFCore.Analyzers

**Comment by sebastienros** [comment]
Benchmarks are still failing because if this. I will investigate today.

**Comment by roji** [comment]
@sharwell thanks for chiming in, [note this conversation](https://github.com/dotnet/efcore/pull/21996#discussion_r469897747) with @mavasani.

The analyzer only uses Visual Basic to produce more narrow diagnostic spans, so strictly-speaking it's possible to just remove it, if this is complicated. The analyzer would still work and do its job, just emit lesser quality diagnostics.

Let me know what you think.

**Comment by sharwell** [comment]
@roji There are three options:

1. Remove support for Visual Basic (i.e. you remove the references to Microsoft.CodeAnalysis.VisualBasic _and_ you modify the `DiagnosticAnalyzer` attribute to not export for VB usage)
2. Keep the Visual Basic support, but remove the usage of _both_ the C# and VB syntax types (i.e. you only reference Microsoft.CodeAnalysis.Common)
3. We keep Visual Basic support and keep the syntax-specific diagnostic location reporting, but split up the current Microsoft.EntityFrameworkCore.Analyzers assembly into C#- and VB-specific derived analyzer classes.

**Comment by roji** [comment]
@sharwell thanks for the info. How complicated is it to do option 3? #21966 tracks this, is there any clear guidance on how to do it? It may be a bit late in the release to do this if it's a lot.

Barring this, if I'm understanding you correctly, we can either be a C#-only analyzer (in which case we can reference syntax-specific stuff), or do both C# and VB, at the price of not having any syntax-specific references? If that's our choice, I suspect we're go with being C#-only for now, and possibly improve for VB in 6.0 (but we'll have to discuss).

**Comment by roji** [comment]
@sharwell out of curiosity, how is it that I haven't been able to reproduce the issue without caching the old analyzer in the build server (as in https://github.com/dotnet/efcore/issues/22177#issuecomment-679087431)?

**Comment by sharwell** [comment]
The build uses VBCSCompiler.exe when available, but if that fails for any reason (which it is allowed to do at any time including for transient reasons) it falls back to csc.exe. The former provides both the C# and VB compiler assemblies, while the latter only provides the C# assemblies.

**Comment by roji** [comment]
Discussed this with the team in triage. Since we're very late in the 5.0 cycle, the decision is to remove the VB capabilities for now, and keep this as a C#-only analyzer (option 1 [above](https://github.com/dotnet/efcore/issues/22177#issuecomment-679228132)).

We'll keep PR https://github.com/dotnet/efcore/pull/22195 - which does option 3 - open for now, and merge it later for 6.0.

Thanks again for the input and the PR @sharwell - we'll definitely get this in.

**Comment by sharwell** [comment]
@roji Would you like me to submit a parallel pull request with just the changes for option (1) or is it something that you're already familiar with?

**Comment by roji** [comment]
@sharwell thanks for offering! I think I can take care of it. Basically remove the attribute from the analyzer, remove the reference to Microsoft.CodeAnalysis.VisualBasic and all the code that does VB syntax, right?

**Comment by sharwell** [comment]
Yes that should cover it. Feel free to mention me in the code review.
