### ISSUE TITLE
Scaffold-DbContext Error: Could not load assembly ''. Ensure it is referenced by the startup project ''.

### ISSUE THREAD

**Issue by Spryter** [dotnet/efcore#22174]
Hi! 

I created .Net Core 2.1 app, added Telegram.Bot Nuget package and some code. Also created SqlServer database.
Then I installed to app Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.SqlServer.Design, Microsoft.EntityFrameworkCore.Tools packages to scaffold tables from my database.

Then I ran `Scaffold-DbContext "Server=Localhost;Database=dbName;Trusted_Connection=True" Microsoft.EntityFrameworkCore.SqlServer` 
and got error `Could not load assembly ''. Ensure it is referenced by the startup project ''.`
Didn't use any migrations, just wanted to create model classes automatically.
 
I have one project in solution (so it is startup project), use Debug x64 project build configuration .

Googled a lot, but didn't get answer, help, please. Why is this empty assembly name? What could I do?

### Further technical details
EF Core version:  3.1.7 - Tools
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 2.1
Operating system: Win 7
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
Don't install `Microsoft.EntityFrameworkCore.SqlServer.Design`--that package isn't compatible with EF Core 2.0+
