### ISSUE TITLE
Adding a 'profile' parameter to `ef migrations add` and `ef migrations update`

### ISSUE THREAD

**Issue by pdevito3** [dotnet/efcore#22190]
Currently, when working on a project with multiple `appsettings.{environment}.json` files, there is no way to add a migration or update the database while pointing to a particular profile. 

So say I have a project with two the appsetting files below. When I try to add a migration or update the database after the fact, there is no way for me to tell the CLI where to look at.

So let's say I have appsettings.Production.json:
```json
{
  "UseInMemoryDatabase": false,
  "ConnectionStrings": {
    "HelloDb": "Data Source=localhost\\SqlExpress;Initial Catalog=MyDbName;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

and I have appsettings.Development.json:
```json
{
  "UseInMemoryDatabase": true,
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

Similar to how `dotnet run` has a [launch profile option](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run#options), it would be really useful to have that option on the `ef migrations add` and `ef migrations update` commands

**Comment by bricelam** [comment]
Needs https://github.com/dotnet/efcore/issues/8695

**Comment by bricelam** [comment]
Note, you can currently set `ASPNETCORE_ENVIRONMENT` before running `dotnet ef` to let the host builder locate the appropriate settings file.

**Comment by pdevito3** [comment]
Thanks @bricelam found that work around this morning. Not really an ideal workflow, but will work for now. Seems like an update is on the horizon though in EF5? Is there any kind of estimated timeline for that?

**Comment by bricelam** [comment]
No significant updates around this issue specifically in 5.0.0, but that version will be released at www.dotnetconf.net in November.

**Comment by ajcvickers** [comment]
Closing in favor of #8695

**Comment by saliksaly** [comment]
It is possible to implement IDesignTimeDbContextFactory which can then read connection string from appsettings.Development.json.
Here is how: 

- https://blog.danielpadua.dev/posts/efcore-implementing-a-multi-environment-designtimedbcontextfactory/
- https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#args
