### ISSUE TITLE
Consider supporting .netconfig for hierarchical and standard configuration

### ISSUE THREAD

**Issue by kzu** [dotnet/efcore#22203]
It's not uncommon to need to run the `dotnet ef` tool several times. Passing all those arguments each time can be error prone and tiresome. The experience would be substantially better if the tool would adopt the [dotnetconfig](https://dotnetconfig.org) format for persisting arguments that are repeated or reused a lot, so that only the changing ones across executions need to be provided.

In addition to the increased consistency across .NET Core global tools, adopting `.netconfig` would also bring the very useful feature of automatically supporting hierarchical configurations. Developers consuming various tools can also simply rely on a single format for all their tools. The proposed format (heavily based on [git-config](https://git-scm.com/docs/git-config)) has served the GIT community incredibly well over the years, with sufficient flexibility for all the various tools that make up the `git` experience.

Users could also use the provided `dotnet-config` [CLI tool](https://dotnetconfig.org/#cli) to configure values programmatically, without EF tools having to provide their own mechanism to do the same (if it were to be supported down the road in some other format).

An example of what the configuration could look like for `ef` and various [settings listed in the docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#common-options):

```
[ef]
    connection = "Server=(localdb)\\mssqllocaldb;Database=Blogging;Trusted_Connection=True;"
    provider = Microsoft.EntityFrameworkCore.SqlServer
    configuration = Release
    json
    verbose
    
[ef "dbcontext"]
    data-annotations
    output-dir = Models
    force
    table = Blog
    table = Post
    context-dir = Context
    context-namespace = New.Namespace
```

With that configuration, the common arguments (including connection and provider) could be shared by all supported commands without needing to enter them on every run. The `dbcontext` section configures the same scenario to the one in the [docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold):

```
dotnet ef dbcontext scaffold "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -t Blog -t Post --context-dir Context -c BlogContext --context-namespace New.Namespace
```

With the `.netconfig` support, you could run the scaffold repeatedly by just running

```
dotnet ef dbcontext scaffold
```

since all the arguments can be resolved from `.netconfig`. Notice, also, that the shared settings (`ef` section) could also be moved a few folders up the hierarchy (i.e. the alongside the solution) so that those values are automatically used whenever any `dotnet ef` command is run anywhere from any descendent directory.

The productivity benefits would be enormous.

## Solution

The CLI tool would take a dependency on the [dotnet-config-lib](https://www.nuget.org/packages/dotnet-config-lib) package, and for any command like option that wasn't specified, it would use the `Config` API to read values from (hierarchical) `.netconfig`, like so:

```csharp
Config config = Microsoft.DotNet.Config.Build();

string? connection = config.GetBoolean("ef", "connection");
```

Alternatively:

```
if (config.TryGetBoolean("ef", "connection", out string connection)) {
  ...
}
```

The `dotnet-config` API is simple and straightforward for reading single and multiple values alike. In the example above, there are multiple `table` variable/values specified. They can be read like so:

Here are some concrete examples of using the API:
* [dotnet-serve](https://github.com/natemcmaster/dotnet-serve/pull/64/files#diff-148eb09c4d64f71298fee3ed73931b31R105) to read custom headers from config
* [dotnet-file](https://github.com/kzu/dotnet-file/blob/master/src/File/Command.cs#L22-L36) reads file url/etag entries to download/update files from remote locations
* [dotnet-vs](https://github.com/kzu/dotnet-vs/blob/master/VisualStudio/Commands/SaveCommand.cs#L20) allows saving aliases to config, which are [later read](https://github.com/kzu/dotnet-vs/blob/master/VisualStudio/CommandFactory.cs#L78) when running aliased commands

**Comment by smitpatel** [comment]
Can you specify how it would be better than https://github.com/dotnet/efcore/issues/8695 ?

**Comment by kzu** [comment]
1. Hierarchical configuration: you can have a solution-level `.netconfig` with common settings across all projects, then a project-level one that overrides values for that project. 
2. Looks like that `launchSettings.json` API didn't go anywhere, so you'll need your own parsing. Not needed with `dotnet-config`
3. Users can directly use the `dotnet config` tool to edit the config settings file, no need to provide any tooling for that in EF (say, for the launchSettings.json).
4. Format is general purpose for any .NET global tool, meaning devs familiar with it can leverage that knowledge
5. Not all projects have launchsettings.json, in fact most won't. It won't make much sense to have a *launch* settings for class libraries that just contain shared entities and DB contexts and nothing launch-able. Weird uex to force a *launch* settings in that scenario.

**Comment by kzu** [comment]
For the scenario mentioned in https://github.com/dotnet/efcore/issues/22190, `.netconfig` makes even more sense, since you can have a global section: 

```
[ef]
  UseInMemoryDatabase = true
```

and then override per environment only the settings you care to override (in the same file or another one, doesn't matter:


```
[ef "Production"]
  UseInMemoryDatabase = false

```

As for connection strings per environment, one way to model them could be:

```
[ef.connectionstrings "Production"]
  HelloDb = "Data Source=localhost\\SqlExpress;Initial Catalog=MyDbName;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
  ByDb = "Data Source=localhost\\SqlExpress;Initial Catalog=MyDbName2;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
```

NOTE: you can model the sections, subsections and variables any way you like, this is just an example, of course.

**Comment by smitpatel** [comment]
launchSettings.json is .NET core concept, even though it is not being honored in EF Core yet, there is widespread usage of that across the board.
Main thing is, it is something which is project specific and can be put in version control.

configs are good for tools which are purely user experiences and preferences, e.g. git. You want git command line to work in certain way or add your personal metadata but you cannot put things in there which are not personal. You cannot configure your remote in git config. 
Same way, why would a user of EF Core want to say globally that use in memory database by default. What if the context is not configured using in memory database? what if in memory database package is not installed. What if they are running actual migration but there are no migrations for in memory database. Further, not only `dotnet ef` needs to care about this, also the actual dotnet run would need to consider this. e.g. if you are using a local database for development and run a migration which gets applied but app does not work properly. Then you are debugging it by running the app. If the app running (which happens  via dotnet run, invoked altogether outside of EF), then `dotnet run` is supposed to understand that same thing `dotnet ef` does? Also introduction of this adds additional dependency which not all user may want to use.

We should _not_ do this unless there actual feedback about multiple customers wanting to use.

@kzu - You can create your own CLI tool like `dotnet ef` where .netconfig works. There is low chance it would be made part of this product without customer feedback.

**Comment by kzu** [comment]
Launchsettings.json can trivially override team-wide settings, so, it doesn't look like a strong argument against. 

Just like aspnet.core supports multiple configuration providers... (A .netconfig one is coming, btw).

**Comment by smitpatel** [comment]
> Just like aspnet.core supports multiple configuration providers... (A .netconfig one is coming, btw).

That is the crux of the issue. If there is a configuration provider which .NET itself supports then we can light up. Anything beyond that and `dotnet ef` may respect but `dotnet run` won't so it would create a major confusion. If ASP.NET Core adds .netconfig one then we can also light up there here. Is there a tracking issue or PR for ASP.NET Core one?

**Comment by kzu** [comment]
I don't understand the fast-tracked `propose-close`. How is the community going to provide feedback if things are closed in a matter of days? 

You didn't seem to answer any of the benefits I cited either, and you're still assuming that people will have launch settings.json files copied (since it's not hierarchical) over *library* projects that are never launched... Seems like a weird uex, honestly.

**Comment by kzu** [comment]
I am going to create a MS.Extensions.Configuration provider:https://github.com/dotnetconfig/dotnet-config/issues/3 

But I see your point WRT dotnet run and built-in settings...

**Comment by smitpatel** [comment]
> How is the community going to provide feedback if things are closed in a matter of days?

Community are going to provide feedback what they **need**? What is their use case? How hierarchical they want it to be?

It based on feedback and scenarios, we can determine **iff** .netconfig is right way to express it or we need something different. Regardless those discussions are supposed to happen in .NET Core runtime repo (or CLI repo). If it has to work across `dotnet run`, `dotnet ef` and ASP.NET Core then underlying runtime has to add support for it. We cannot act before that. So yes, this issue is propose-close since there is nothing actionable on EF Core side till design is presented to .NET Core, they accept and implement it and be available in SDK.

**Comment by kzu** [comment]
Well, maybe I'm not familiar enough with what dotnet ef does, but codegen at build/design time hardly needs runtime support. It never had on any project that did that that I ever used...

**Comment by smitpatel** [comment]
> You didn't seem to answer any of the benefits I cited either,

1. Fair usage, if hierarchical settings wanted. I haven't seen much usage for launch settings or any other config used in running the app to be globally stored.
2. The issue is open because we are not writing our own parsing. We are waiting for .NET to provide us a hook to get all that data. It is not dead yet.
3. launchSettings.json is just a JSON file. You can edit it in anything. And .NET can add editing tool if needed. (all other jsons are edited in Visual studio directly, so not sure if anything needed)
4. Is there Microsoft tool which utilizes this?
5. dotnet ef cannot be invoked on class library. It needs to have a startup project which can be invoked. Launch settings stays there. Your claim is incorrect.

**Comment by smitpatel** [comment]
You should familiarize yourself with how dotnet ef works first then. It partially invokes the startup project to build service provider and get services and utilizes those services to generate code. `dotnet ef` is code generation at design time it is _not_ code generation at build time.

**Comment by kzu** [comment]
Design time vs build time is largely a semantics issue. I.e. with a Roslyn source generator, are you doing design time or build time? ;-). The only difference that really matters is run-time vs non-run-time. If you're not doing run-time codegen, I wonder what you need dotnet runtime support for in anything relating to codegen...

**Comment by smitpatel** [comment]
design time vs build time is not just semantics. Build time allows you to hook into compilation process, you cannot run your app during build time. Design time is when your app is not running exactly for what it should be but it can still be run. `dotnet ef` requires to start the app partially to get all the services. This has been way with HostBuilder API in .NET Core.

At this point, I don't think this discussion is going anywhere. I pointed you to right direction where you should be filing proposal for this. It's upto you if you want to. There is still nothing actionable on EF Core.

**Comment by kzu** [comment]
Oh boy: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#other-target-frameworks

> Apps that have the EF Core model in a .NET Standard class library might not have a .NET Core or .NET Framework project. For example, this is true of Xamarin and Universal Windows Platform apps. In such cases, you can create a .NET Core console app project whose only purpose is to act as startup project for the tools. The project can be a dummy project with no real code — it is only needed to provide a target for the tooling.

Like I said, regardless of what (good or otherwise) reasons you have for your current design, it must definitely sounds like far from a delightful user experience. No wonder some users [consider that a bug](https://github.com/dotnet/efcore/issues/12608).

Anyway, for comparison, Roslyn also runs your code (analyzers, source generators) and they don't impose artificial constraints like having a startup project for that. So, sure, you can rationalize why you think that's necessary or unavoidable given your current tooling implementation, but using that (design bug, IMO) as the justification for why you must have runtime support for configuration, and for using launchSettings.json, which people may have solely because of the artificial restriction in the first place, is disingenuous IMO.

But I guess the entanglement goes so deep as to make it practically imposible, regardless of how little sense it makes that a library project can't scaffold an ORM from a connection string...

**Comment by ajcvickers** [comment]
@kzu Thanks for the proposal. I think if this becomes something that is widely adopted, then we would consider support in EF Core. However, it seems likely that even then it would be done as an external package so that the core package doesn't contain a dependency on a particular configuration system. (This is the general approach we have taken to EF configuration from the beginning--all config is by code, which can be bound to config files externally if people so choose.) For now, I don't think there is anything actionable on the EF side, but if this becomes a thing then we can always revisit.

**Comment by kzu** [comment]
Fair enough. `dotnet-serve` is already on board (shipped support for it already), `reportgenerator` is coming up next, it's been an easy sell so far :). 

I think it's most useful at the entry point dotnet tool, rather than in lower layers where being config-agnostic is most valuable.
