### ISSUE TITLE
Perf regression in existing data variations

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22215]
Likely due to local detect changes for cascade delete

![image](https://user-images.githubusercontent.com/1430078/91200441-07590e00-e6b4-11ea-98cd-8706bcb39070.png)

**Comment by ajcvickers** [comment]
@dotnet/efteam Made this poachable.

**Comment by smitpatel** [comment]
Do we know commit which caused this?

**Comment by ajcvickers** [comment]
We think it's adding the call to local DetectChanges here: https://github.com/dotnet/efcore/pull/22079

**Comment by smitpatel** [comment]
Found the root cause. PR coming in.
