### ISSUE TITLE
how to set navigation properties in in linq 

### ISSUE THREAD

**Issue by karnik1110** [dotnet/efcore#22237]
i am trying to perform include() command in linq on northwind db how do i set navigation properties

### Steps to reproduce

``` C#
using (var context = new NorthwindContext())
{
    var product = (from s in context.Products.Include("Categories")
                   where s.ProductName == "chai"
                   select s).FirstOrDefault<Products>();
    Console.WriteLine(product);
}
```

System.InvalidOperationException: 'Invalid include path: 'Categories' - couldn't find navigation for: 'Categories''

EF Core version:
Database provider: (e.g. Microsoft.SqlServer.Express)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
