### ISSUE TITLE
Perf regression in Attach

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#22263]
![image](https://user-images.githubusercontent.com/1528107/91372396-66a84280-e7c8-11ea-82c8-92cdcf3e0812.png)

Also AttachChildren/AttachParents scenarios.

@dotnet/efteam - Does anyone know the faulty commit. I will start bisecting on git tomorrow morning if no one knows.

**Comment by AndriySvyryd** [comment]
My guess would be 04575b007d79ed9514833abcfe37997880c498be
