### ISSUE TITLE
Many-To-Many skip navigations are not working properly with lazy loading (Preview 8)

### ISSUE THREAD

**Issue by daniel3303** [dotnet/efcore#22271]
Many-To-Many skip navigations are not working properly.

### Steps to reproduce

``` C#
public class Request {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreationTime { get; set; } = DateTime.Now;

        public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}

public class Employee{
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Request> Requests { get; set; } = new List<Request>();
}

public IActionResult Test() {
         _dbContext.Add(new Employee{Name = "Employee test", Requests = new List<Request>(){new Request{Title = "Request test"}}});
         _dbContext.SaveChanges();
         Console.WriteLine(_dbContext.Requests.First().Employees.Count));
         return Ok();
}

```

After running migrations the intermediate table RequestEmployee is properly created and the foreign keys properly set. When we try to access the property Employees on Request or Requests on Employee and following exception is thrown.

 System.InvalidOperationException: The property 'Employees' on entity type 'Request' could not be found. Ensure that the property exists and has been included in the model.
         at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.Navigation(String propertyName)
         at Microsoft.EntityFrameworkCore.Internal.LazyLoader.ShouldLoad(Object entity, String navigationName, NavigationEntry& navigationEntry)
         at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
         at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
         at Castle.DynamicProxy.AbstractInvocation.Proceed()
         at Castle.Proxies.RequestProxy.get_Employees()
...

However it does not break if used as follows:

``` C#
Console.WriteLine(_dbContext.Requests.Include(r => r.Employees).First().Employees.Count);
```

Note that I am using at the StartUp UseLazyLoadingProxies()

### Further technical details

EF Core version: v5.0.0-preview.8.20407.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: macOS Catalina and Windows 10 (happens in both)
IDE: Visual Studio 2019 16.7 and Rider 2020.01 (tested in both)

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/dotnet/efcore/commit/ca57b8e21b7473ad5cce434e8c0f79519bcce17f
