### ISSUE TITLE
replace internal api `EntityQueryProvider` with something public

### ISSUE THREAD

**Issue by nikita-starostin** [dotnet/efcore#22280]
There is a library linqkit I am using for reusable expressions. I have an issue described here https://stackoverflow.com/questions/48661790/includes-doesnt-work-with-linqkit-asexpandable (see the answer). 

Is it possible to replace check `source.Provider is EntityQueryProvider` with `source.Provider is IQueryProvider`?
![image](https://user-images.githubusercontent.com/57386894/91498384-55465f80-e8c8-11ea-8a05-e0bde8870505.png)

**Comment by ajcvickers** [comment]
@nikita-starostin Currently EF Core, by-design, ignores Include when used with a non-EF LINQ provider. This allows, for example, queries with Include to be used with LINQ-to-Objects where the data is already loaded and Include is a no-op. If this is something that doesn't work for linqkit, then we would be happy to discuss alternatives. However, we don't have enough context on what linqkit needs to do to make any changes here, especially given we want Include to continue to be ignored by non-EF query providers. I would suggest you contact linqkit and ask them to make a concrete proposal if they need something to change in EF.
