### ISSUE TITLE
Temporal Table Support (new in SQL Server 2016)

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#2229]
Do you have any plan to integrate Temporal table to align the feature from Sql 2016?

**Comment by rowanmiller** [comment]
**Triage** For the most part basic query etc. should just work. We do want to look at ability to query particular points in time etc., but we will look at this once we ship the initial RTM.

**Comment by adamjstone** [comment]
I'm glad to see that this is in queue. This is an important feature for large enterprises. We want to ease the pain of delivering reports for sox audits. This is a painful bureaucratic hoop that every publicly traded enterprise in the United States has to jump through. Over and over.

**Comment by pkothare** [comment]
+1 on SOX compliance. I'd like to contribute to this. There is a huge community of enterprise developers that will see value in this feature.

**Comment by rohitshrivastava04** [comment]
Now when SQL 2016 is released, is there any update on this issue?

**Comment by rowanmiller** [comment]
This is on our backlog to look at, but there are higher priority features that we will be tackling first. You can absolutely use temporal tables with EF Core, there just isn't a first class way to reason about points in time. To do this, you would use a raw SQL query https://docs.efproject.net/en/latest/querying/raw-sql.html.

**Comment by qanuj** [comment]
+1 on SOX compliance

**Comment by smoelker** [comment]
+1 Temporal support would be incredibly useful!

**Comment by amirazizian** [comment]
+1

**Comment by GalayM** [comment]
+1

**Comment by lovezhuliang** [comment]
+1

**Comment by johnavery** [comment]
+1 for creating Temporal Tables from Fluent API and also issuing temporal queries!

**Comment by cSteusloff** [comment]
+1

**Comment by SamNasr** [comment]
Rowan, any updates on using EF Code First to build/maintain Temporal Tables?  Where can we monitor this issue?

**Comment by rowanmiller** [comment]
@SamNasr this is the right place to monitor the issue. No updates as yet, this isn't planned for our next release (2.0)

**Comment by jessanmen1** [comment]
Any news on this?

**Comment by ajcvickers** [comment]
We seem to have two issues tracking this. Closing this one in favor of #4693, since that issue contains a bit more information.

**Comment by rezdm** [comment]
One more vote for this one.

**Comment by angularDevd** [comment]
and another one +1

**Comment by hadi-jabbari** [comment]
+1

**Comment by toper** [comment]
+1

**Comment by pfaisant** [comment]
+1. any update ?

**Comment by AliaksandrBortnik** [comment]
> +1. any update ?

This ticker is closed. Go to the following ticker: [#4693](https://github.com/aspnet/EntityFrameworkCore/issues/4693)
