### ISSUE TITLE
Code fix: propose adding AsQueryable when async LINQ operator is used on a DbSet

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#22315]
Assuming #18124 can't be properly fixed (in System.Linq), we can at least have a code fix provider that proposes adding AsQueryable, which is our recommended workaround for now. This would also allow users to immediately fix all occurrences in the solution etc.

**Comment by Youssef1313** [comment]
@roji Is there an existing analyzer that lacks a codefix? Or this issue is to implement both an analyzer and a codefix?

**Comment by roji** [comment]
@Youssef1313 this is for both an analyzer and a codefix. However, see #24041 for a possibly different direction on fixing this. We'll be discussing this soon.

**Comment by Youssef1313** [comment]
@roji Great! I'll keep an eye on the other issue as well as on this one, and will open a PR it was decided to implement the analyzer.

**Comment by roji** [comment]
As per #24041, we're going to remove IAsyncEnumerable from DbSet, so an analyzer/codefix is no longer needed.
