### ISSUE TITLE
Async operation takes 130x longer to finish on a nvarchar(MAX) field comparing to a sync operation 

### ISSUE THREAD

**Issue by daniel3303** [dotnet/efcore#22331]
When a modal from the database where a column has a long string (I tested with a 9MB string) it takes around 130x more if you use an async operation.

### Steps to reproduce

``` C#
public class File {
        public int Id { get; set; }
        public string Base64{ get; set; }
}

public IActionResult Index() {
      var file = _dbContext.Files.Find(1); // The property Base64 has a 9MB random Base64 string
      return Ok(file.Base64); // Takes 0.2s
}

public async Task<IActionResult> Index() {
      var file = await _dbContext.Files.FindAsync(1);
      return Ok(file.Base64); // Takes 25.9s
}
```

### Further technical details

EF Core version: v5.0.0-preview.8.20407.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: macOS Catalina and Windows 10 (happens in both)
IDE: Visual Studio 2019 16.7 and Rider 2020.01 (tested in both)

**Comment by smitpatel** [comment]
@roji to find dupe.

**Comment by roji** [comment]
Dupicate of https://github.com/dotnet/SqlClient/issues/593

**Comment by roji** [comment]
See also https://github.com/dotnet/SqlClient/issues/689 which is a dup of the above specifically for text data.

Unfortunately you'll have to use sync for now, or drop down to ADO.NET and use the streaming API, which does work efficiently in async.
