### ISSUE TITLE
PMC commands detailed in the wiki page won't work

### ISSUE THREAD

**Issue by lnaie** [dotnet/efcore#2233]
Hi,

This is the help page that I've used trying to apply the pre-generated migration of a default vnext MVC project:
https://github.com/aspnet/EntityFramework/wiki/Using-EF7-in-Traditional-.NET-Applications

There's no Add-Migration or Apply-Migration PMC command.
I had to run the following command to get the migration applied:
PM> dnx ./ProjectPath ef migration apply

Wasting time on simple stuff when starting with vnext is not fun. :)
Thanks

**Comment by rowanmiller** [comment]
Hey,

That page is about traditional .NET applications (WPF, WinForms, ASP.NET vCurrent, etc.). For ASP.NET 5 the commands don't work in PMC (at least not yet). You can use `dnx . ef` at a command prompt for ASP.NET 5 (or you can do it via PMC as you discovered).

~Rowan

**Comment by bricelam** [comment]
(See also aspnet/dnx#952)
