### ISSUE TITLE
Duplicate DBContextOptions registered in DI

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/efcore#22341]
While debugging a failure in our blazorwasm templates with individual auth using local databases, I encountered an issue that broke `DatabaseDeveloperPageExceptionFilter`. Specifically it seems like two instances of `DBContextOptions<ApplicationDBContext>` were registered in DI. This eventually caused an issue where `FinalizeModel` was called twice and it threw on the second call. While we can workaround the issue by deduping the context options in the exception filter, it seems like a bug that two context options were registered in the first place.

I'm assigning @smitpatel since he helped me debug this issue and has some context so he can help fill in the blanks in case I missed some details.

### Steps to reproduce

Repro: https://github.com/JunTaoLuo/DuplicateContext
Run the project and set a breakpoint in DatabaseDeveloperPageExceptionFilter to observe the duplicated dbcontexts.

### Further technical details

EF Core version: 5.0.0-rc.1.20430.4
Database provider: e.g. Microsoft.EntityFrameworkCore.SqlServer
Target framework: net5.0
Operating system:
IDE:

**Comment by JeremyLikness** [comment]
@smitpatel please check 3.1 for regression.

**Comment by ajcvickers** [comment]
@JunTaoLuo I am not able to reproduce this. I do see the same `DbContextOptions` registered twice, but once as a the generic type and once as the non-generic type:

![image](https://user-images.githubusercontent.com/1430078/100286567-df35b100-2f27-11eb-91a5-23f8b0e44949.png)

This is expected. I also verified that `errorContext.HttpContext.RequestServices.GetServices<DbContextOptions>()` only returns the non-generic registration, which is again as expected. I have not been able to get int a state where `errorContext.HttpContext.RequestServices.GetServices<DbContextOptions>()` returns more than one, except when more than one context type is registered, where it is again expected.

**Comment by ajcvickers** [comment]
@JunTaoLuo Ping

**Comment by JunTaoLuo** [comment]
Hmm I'll need to see why the repro isn't working for you then. Since I definitely ran into the described issue, which is why we have the code https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/Diagnostics.EntityFrameworkCore/src/DatabaseDeveloperPageExceptionFilter.cs#L56-L58. I'll update this issue if I have more details.

**Comment by slavanap** [comment]
I've just noticed this and wanted to say that such behavior trigger dump of info for contexts that haven't been used within processing of HttpRequest, thus initiating their creation and triggering unnecessary connection to DB for DbContexts that haven't been used. https://source.dot.net/#Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore/DatabaseDeveloperPageExceptionFilter.cs,59

**Comment by ajcvickers** [comment]
@slavanap Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by slavanap** [comment]
@ajcvickers 

Unfortunately, it can't be made very small, but I've tried. Files are listed below. When HomeController.Index method is hit and exception is propagated, please notice the message in the logs:
```
fail: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseDeveloperPageExceptionFilter[7]
      An exception occurred while calculating the database error page content. Skipping display of the database error page.
      System.Exception: ContextBad is never used, although registered in DI. So this code should never hit
```


Project.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.7" />
  </ItemGroup>

</Project>
```

Program.cs
```c#
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication1 {

    public class ContextGood : DbContext {
        public DbSet<Post> Posts { get; set; }
        public ContextGood(DbContextOptions<ContextGood> options) : base(options) { }
    }

    public class ContextBad : DbContext {
        public DbSet<Post> Posts { get; set; }

        public ContextBad(DbContextOptions<ContextBad> options) : base(options) { }
        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            throw new Exception("ContextBad is never used, although registered in DI. So this code should never hit");
        }
    }

    public class Post {
        public int Id { get; set; }
        public string Title { get; set; }
    }


    class Startup {
        
        static void Main(string[] args) =>
            CreateHostBuilder(args).Build().Run();

        static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => {
                    webBuilder.UseStartup<Startup>();
                });


        public void ConfigureServices(IServiceCollection services) {
            services.AddDatabaseDeveloperPageExceptionFilter();
            services.AddControllers();
            services.AddDbContext<ContextBad>(opts => opts.UseInMemoryDatabase("test1"));
            services.AddDbContext<ContextGood>(opts => opts.UseNpgsql("server=0.0.0.0"));
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
            if (env.IsDevelopment())
                app.UseDeveloperExceptionPage();

            app.UseRouting();
            app.UseEndpoints(endpoints => {
                endpoints.MapDefaultControllerRoute();
            });
        }
    }

    public class HomeController: Controller {
        readonly ContextGood _good;

        public HomeController(ContextGood good) {
            _good = good;
        }

        public IActionResult Index() {
            _good.Posts.Find(1);
            return Ok("test");
        }
    }

}
```

launchSettings.json
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:51923",
      "sslPort": 44378
    }
  },
  "profiles": {
    "WebApplication1": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by ajcvickers** [comment]
@slavanap Thanks; I understand what's going on. I will discuss with @bricelam.

**Comment by ajcvickers** [comment]
@slavanap Move to https://github.com/dotnet/aspnetcore/issues/36877
