### ISSUE TITLE
Using Microsoft.Data.SqlClient didn't work for The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects

### ISSUE THREAD

**Issue by Angus221** [dotnet/efcore#22349]
when I excute sql like:

   ```
  public int ExcuteSql(string sql)
        {
            return context.Database.ExecuteSqlRaw(sql);
        }
```

`
    
                SqlParameter[] fparams = new SqlParameter[2];
                fparams[0] = new SqlParameter("@BatchNo", batchNumber);
                fparams[1] = new SqlParameter("@Result", SqlDbType.Int);
                fparams[1].Direction = ParameterDirection.Output;

                int i = _unitOfWork.ExcuteSql("EXEC [UP_BUD_CHECKFORCAST] @BatchNo,@Result OUTPUT", fparams);
`
Throw the exception： 
The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects

Sameone said  changing using System.Data.SqlClient to using Microsoft.Data.SqlClient will fix，

But I only used  Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer,
I can't find "System.Data.SqlClient" anywhere，

How could I Fix it

EF Core version:EF core 5.0-preview8
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: Core 3.1
Operating system:
IDE: Visual Studio 2019)

**Comment by roji** [comment]
You are likely still referencing System.Data.SqlClient - can you please double-check your csproj file? Also, check the usings at the top of the file to see which provider you're using.

**Comment by Angus221** [comment]
> You are likely still referencing System.Data.SqlClient - can you please double-check your csproj file? Also, check the usings at the top of the file to see which provider you're using.

I've searched all of them（like top of the file、csproj file and all of the referencing）, and I haven't found ‘System.Data.SqlClient’。

![image](https://user-images.githubusercontent.com/21039420/91921404-0bada880-ecfe-11ea-843b-77aab8a58605.png)

![image](https://user-images.githubusercontent.com/21039420/91921441-22ec9600-ecfe-11ea-8dd1-3b5a50698fad.png)

**Comment by Angus221** [comment]
> You are likely still referencing System.Data.SqlClient - can you please double-check your csproj file? Also, check the usings at the top of the file to see which provider you're using.

Thanks，I found the reference and replaced it，it fixed。
