### ISSUE TITLE
Nullable exception after updating to Preview-8 (Nullable object must have a value)

### ISSUE THREAD

**Issue by damikun** [dotnet/efcore#22348]
In case of move to **last version** of ef core (5.0.0-preview.8.20407.4), app throws exceptions: **"nullable object must have value"** for all objects that contains some nullable defined member..

**All older versions works only prev-8 not..**  ( tested on prev 5,6,7 as OK )

- Tested with different DBs  (SQL/SQLite/Postgres)  (So i think it is not provider related..)
- Tested that this is not migration or tools related..

This happens when any object has some Nullable member which is null... Im adding example for UserRole Null...

**Example DB model:**
```
 public class User {

        public long ID { get; set; }

        public string UserName {
            get {
                return String.Format("{0}.{1}", FirstName, LastName);
            }
        }

#nullable enable
        public string? AvatarFileName { get; set; }
#nullable disable

        public string FirstName { get; set; }

        public string LastName { get; set; }

#nullable enable
        public string? Email { get; set; }
#nullable disable

        public User() {
            this.Tokens = new HashSet<RefreshToken>();
            this.Groups = new HashSet<GroupUser>();
            this.Claims = new HashSet<UserPermission>();
            this.Email = "";
            this.AvatarFileName = "";
        }

#nullable enable
        public DateTime? ActivTimestamp { get; set; }
#nullable disable

        public bool Deactivated { get; set; }

        virtual public IEnumerable<RefreshToken> Tokens { get; set; }

#nullable enable
        virtual public Role? Role { get; set; }
#nullable disable

        virtual public IEnumerable<GroupUser> Groups { get; set; }
....
   ....
     etc.
    }
```

**From SELECT:**
```
SELECT "t"."ID", "t"."Email", "t"."FirstName", "t"."LastName", "r"."ID", "r"."Name", "r"."Description", "r"."Code", "t"."ActivTimestamp", "t"."AvatarFileName" AS "AvatarImageName", "t"."Deactivated"
FROM (
    SELECT "u"."ID", "u"."ActivTimestamp", "u"."AvatarFileName", "u"."Deactivated", "u"."Email", "u"."FirstName", "u"."LastName", "u"."RoleID"
    FROM "Users" AS "u"
    WHERE ("u"."FirstName" IS NOT NULL AND NOT ("u"."Deactivated")) OR ("u"."LastName" IS NOT NULL AND NOT ("u"."Deactivated"))
    LIMIT @__p_0
) AS "t"
LEFT JOIN "Roles" AS "r" ON "t"."RoleID" = "r"."ID"
```

**Throw:**
```
 An exception occurred while iterating over the results of a query for context type 'Presistence.AppDbContext'.
System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
...
  ...
   etc.
```

**Versions:**
EF Core version: 5.0.0-preview.8.20407.4
Database provider: SqlServer or SQL or PosgreSQL (tested with all so i think it is not provider related..)

**Comment by roji** [comment]
The LINQ query is missing from the above, can you please post it? Or even better, a simple, fully runnable code sample (with both a model and the LINQ query) would be ideal. As we're starting to approach the 5.0 release, it's important to move fast, and having a full repro is the best way to do that.

**Comment by smitpatel** [comment]
Due to this https://github.com/dotnet/efcore/issues/20633
The queries are trying to read nullable values into non-null field.

**Comment by damikun** [comment]
> The LINQ query is missing from the above, can you please post it? Or even better, a simple, fully runnable code sample (with both a model and the LINQ query) would be ideal. As we're starting to approach the 5.0 release, it's important to move fast, and having a full repro is the best way to do that.

@roji  I prepared this for you under link as test repo..

You must run app and call API controller where is Linq... under: `https://github.com/dotnet/efcore/issues/22348`

https://github.com/damikun/EfCore-Prev.8-null-object-bug-report

**Comment by smitpatel** [comment]
```C#

List<User_DTO> db_enity = await _context.Users.AsNoTracking()
            .Include(e=>e.Role)
            .Select(e=> new User_DTO(){
                ID = e.ID,
                Role =  new Role_DTO {
                ID = e.Role.ID,
                Name = e.Role.Name,
            },
            }).ToListAsync();
```
`user.Role` is nullable so `e.Role.ID` can return null (EF Core makes it null safe). But `User_DTO.Role` is nullable but not the `Role_DTO.ID` so as the exception says, you cannot put null value in ID, Name columns.

**Comment by damikun** [comment]
@smitpatel thx for info... Oh yes i see.. So whats the workaround for this? or better say how to do this select with new prev8 ? i saw the merge is new and something going back to .net core 2.2 behavior...

**Comment by smitpatel** [comment]
```C#
List<User_DTO> db_enity = await _context.Users.AsNoTracking()
            .Include(e=>e.Role)
            .Select(e=> new User_DTO(){
                ID = e.ID,
                Role =  e.Role == null ? null : new Role_DTO {
                ID = e.Role.ID,
                Name = e.Role.Name,
            },
            }).ToListAsync();
```
You need to check for `e.Role` being null then returning null rather than create the Role_DTO.
