### ISSUE TITLE
Need base test packages on MyGet 

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2235]
Or maybe I should not be running them?
Or maybe they are in the wrong dll?

I currently need (and use):
 From EntityFramework.Core.Tests:
 EntityFrameworkServiceCollectionExtensionsTest
 ApiConsistencyTestBase

From EntityFramework.Relational.Tests:
 MigrationSqlGeneratorTestBase

**Comment by rowanmiller** [comment]
@ErikEJ we discussed in triage today and the thoughts are that you should just copy this code, at least for the moment. We may split things up a little more in the future, but publishing these whole test suites doesn't seem like the right thing to do.
