### ISSUE TITLE
Myget feed

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2236]
Not really an issue, but anyway:
What is the status on the "daily " build, seems to have been stuck for some days now (and I am falling more and more behind)

**Comment by rowanmiller** [comment]
Hey Erik,
There was some wide-reaching dependency upgrades going on that affect EF7 and ASP.NET 5... should be resolved today.
~Rowan

**Comment by ErikEJ** [comment]
Aaah - love "beta" land!
