### ISSUE TITLE
Improve CreateProxy exception message for weak and shared types

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#22366]
Currently `context.CreateProxy<Dictionary<string, object>>()` throws "The entity type '{entityType}' was not found. Ensure that the entity type has been added to the model.". If the type is shared or weak we should instead suggest calling context.Set<T>("TypeName").CreateProxy()

**Comment by ajcvickers** [comment]
Fixed by #22338

**Comment by AndriySvyryd** [comment]
#22338 doesn't handle weak types
