### ISSUE TITLE
How to use Lazy loading without Include？

### ISSUE THREAD

**Issue by Angus221** [dotnet/efcore#22381]
Our team update the project from EF6 to EF Core 5.0，

In the past，we use the navigation properties without “include”
Like：
`
var deptName=_db.Users
.Select(m=>new {
m.userName,
**DeptName=m.Department.Name**
})`

Now,I must add 'include',

`
var deptName=_db.Users
.Include(u=>u.Department)
.Select(m=>new {
m.userName,
**DeptName=m.Department.Name**
})`

If I didn't add include,the department was null,and throw exception.

**I hope use Lazy loading without Include,because so many code without include.**

We use Microsoft.EntityFrameworkCore.Proxies
`       optionsBuilder.**UseLazyLoadingProxies()**
                    .ConfigureWarnings(warnings => warnings.Ignore(CoreEventId.DetachedLazyLoadingWarning))
                    .UseSqlServer(connection, op => {
                        op.CommandTimeout((int)TimeSpan.FromMinutes(5).TotalSeconds);
                    })`

EF Core version: 5.0-Preview8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: WIndows Server 08 R2
IDE:  Visual Studio 2019

**Comment by smitpatel** [comment]
You don't need include for that. Can you share a small runnable repro code which shows exception?

**Comment by Angus221** [comment]
> You don't need include for that. Can you share a small runnable repro code which shows exception?

![image](https://user-images.githubusercontent.com/21039420/92078418-cc13b900-edf0-11ea-8fb7-c069dce6b790.png)

When I used firstordefault() or  AsEnumrable() , It will throw exception

**Comment by smitpatel** [comment]
That is different from query you posted in first post. In first post you are using custom projection, there is no entity type being projected out so include is not needed. If you are projecting out entity then you would need include or lazy loading

Refer to [our documentation on lazy loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading).

**Comment by Angus221** [comment]
> That is different from query you posted in first post. In first post you are using custom projection, there is no entity type being projected out so include is not needed. If you are projecting out entity then you would need include or lazy loading
> 
> Refer to [our documentation on lazy loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading).

Thanks，I will check my code
