### ISSUE TITLE
LICENSE.txt missed something?

### ISSUE THREAD

**Issue by Flithor** [dotnet/efcore#22384]
https://github.com/dotnet/efcore/blob/eb9975bffe2dc17dc9e6ee4111285b9d81f770d1/LICENSE.txt#L189

LOL

**Comment by smitpatel** [comment]
The build scripts fills in details. It is not an error.

**Comment by smitpatel** [comment]
@dougbu - Since you reviewed the PRs which updated this file. Feel free to close this if everything is by design and working as expected.

**Comment by sharwell** [comment]
This is the same way that the Apache Foundation includes this license notice for its own projects.
https://github.com/apache/netbeans/blob/ace8c87a32d85bcd9c7b389629834425c27a1128/LICENSE#L190

**Comment by smitpatel** [comment]
Thanks for verifying @sharwell
