### ISSUE TITLE
Update-Database --connection not working: A positional parameter cannot be found

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#22390]
I updated from preview 6 to preview 8.
`Update-Database --connection "Your=Connection;String"` not working not in Package Manager Console. It gives error:
```
Update-Database : A positional parameter cannot be found that accepts argument 'Your=Connection;String'.
At line:1 char:1
+ Update-Database --connection "Your=Connection;String"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Database], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Update-Database
```

It was working in preview 6.

### Steps to reproduce

1. Open Package Manager Console
2. Set startup project to your project with your `IEntityTypeConfiguration` implementations
3. Set `Default project` in Package Manager Console as in point 2.
4. Type `Update-Database --connection "Your=Connection;String"`

### Further technical details

EF Core version: 5.0.0-preview.8.20407.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by bricelam** [comment]
Just one dash: `-Connection`

**Comment by Saibamen** [comment]
Thanks - working :)
