### ISSUE TITLE
Owned Types does not map back when also using custom types for entity identity.

### ISSUE THREAD

**Issue by DerAlbertCom** [dotnet/efcore#22397]
When Reading back Owned Types from the Database this does not worked with Typed Identities (e.g. Custom Type per Id for ensuring correct Id Assingment). If I read to complete type every Owned Type Properties is empty.

But the data is store in the database, if i make specific select on these properties then the data is read.

### Steps to reproduce

Go to

https://github.com/DerAlbertLive/MyInvoices (not a big project, just starting to experiment, and you can ignore the webapp part)

Checkout Branch `feature/entity-id-types` run the unit tests. Two test are failing `Customer_can_be_stored_and_loaded` and `User_can_be_stored_and_loaded`. Both work in the `develop` branch which is using normal `long` as Id fields

the test `Customer_can_be_stored_and_loaded` queries the data like this, and the test fails on checking the property values
![image](https://user-images.githubusercontent.com/136992/92186091-ee8bed80-ee55-11ea-8891-3c231808ccdd.png)

the test `Customer_can_be_stored_and_sub_queried` makes a projection and the test works

![image](https://user-images.githubusercontent.com/136992/92186145-1da25f00-ee56-11ea-885b-5c4aee600bc9.png)

Now switch to the `develop` branch (with no Typed Identities), and every test is working.

JFI: Had to switch to Guid for Ids in the entity-id-types branch, because with long as Ids and Typed Identities EF Core was not willing to allow ValueGeneratedOnAdd, and always thinks the Key is already Set even when not stored in the db.

For your convenience i made a dummy pull request to develop https://github.com/DerAlbertLive/MyInvoices/pull/1 so that you can see the changes, and that there is no difference how i mapped the owned types.

### Further technical details

EF Core version: 5.0 Preview 8 and 3.1.7
Database provider: Microsoft.EntityFrameworkCore.SqlLite
Target framework: .NET Core 3.1.7
Operating system: Mac OS
IDE: Rider, but does not matter ;)

**Comment by smitpatel** [comment]
Your key properties are value type and that will be used for correlation to find out if there is associated owned entity or not to materialize. So you also need to set value comparer along with value conversion so that EF can correctly match keys. See [documentation](https://docs.microsoft.com/ef/core/modeling/value-comparers) for more details.

It does not happen when you are not materializing the owner and owned entity both (the custom projection case) since we will just get data from server to create anonymous type and we don't have to do any key checks.

**Comment by smitpatel** [comment]
Adding ValueComparer like below
```C#
            builder.Property(e => e.Id)
                .HasConversion(p => p.Id, p => new UserId(p))
                .Metadata.SetValueComparer(new ValueComparer<UserId>((l,r) => l.Id.Equals(r.Id), l => l.Id.GetHashCode()));
```
makes both tests pass.

**Comment by DerAlbertCom** [comment]
Yes, wished i had this information 30 Minutes ago, then i found the ValueComparer stuff , i came here to close as this as fast as possible  and saw your comments. yes, indeed with this it works. Thank you for checking this out and for your help.
