### ISSUE TITLE
New Code First Fluent Configuration API

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/efcore#2244]
I am attempting to get a head start on re-writing our website using ASPNET 5 and EF7.  I recognize that it is still in Beta, but I am finding some serious (reported) issues with EF7, or at least my use of it.
**Is there any documentation on how to use the new API?**

I'm finding that some of the allowed methods are dependent on the order previous methods in the chain to work correctly.  I would have expected that a Fluid API would only allow methods to be called that should be.  An example is the .Column("Name") method which works after a .Property(...) but not after a .Property(...).ForSqlServer(). (this has been reported).

**Comment by rowanmiller** [comment]
No documentation at the moment as the API is still changing rapidly. We will start on documentation once we have completed our initial round of API reviews (currently in progress). For example, today we decided to remove the `ForSqlServer()` pattern and just have top level `SqlServerColumnName(...)` APIs.

**Comment by rowanmiller** [comment]
BTW unless you want different column names for different providers, `Column(...)` is the API you want. Though using the SQL Server specific API will also work just fine once it's fully implemented.
