### ISSUE TITLE
RawSqlCommandBuilder class Build() method

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#22441]
I have following update SQL query to run against my EF Core provider. More info in  https://github.com/npgsql/efcore.pg/issues/1489 , in this issue, I was asked to open issue in this forum.

var name1 = "Deoker";
int id2 = 10;
var updOut = schoolContext.Database.ExecuteSqlRaw("update Students set Name = '{0}' where StudentID = '{1}'", name1, id2);

The above code eventually calls RawSqlCommandBuilder::Build(string sql, IEnumerable parameters) method. Which converts above query to "update Students set Name = '@p0' where StudentID = '@p1' ". Now our database doesn't understand "parameter name" i.e. p0 and p1. Our database understands "parameter marker" i.e. the above query needs to be changed to "update Students set Name = ? where StudentID = ?", whereas p0 and p1 continues to the name for the "binding" purpose internally.

I could see if I make appropriate changes in ...\EFCore.Relational\Storage\Internal\RawSqlCommandBuilder.cs then it works for my database. However I am not supposed to change any of these files. Hence would like to know how do I extend/override this method/class/interface in my EF Core provider code. I have picked reference code from Npgsql Postgres i.e. https://github.com/npgsql/efcore.pg

**Comment by roji** [comment]
Parameter placeholder generation is taken care of by your provider's RelationalSqlGenerationHelper, override that rather than RawSqlCommandBuilder (see GenerateParameterNamePlaceholder as well as the other methods).

**Comment by deokershesh** [comment]
GenerateParameterNamePlaceholder() I have already override to return "?", which is making the below query/method ( FromSqlRaw() ) works without any issue. 

var students = schoolContext.Students.FromSqlRaw("Select * from Students where Name = '{0}' and StudentID = '{1}'", name, id1).ToList();

The above line eventually gets called to InitializeReader()->GetRelationalCommand()->GetCommand() [This method is override which calls GenerateFromSql() private method and calls GenerateParameterNamePlaceholder() which takes care of parameter marker i.e. "?".

Now, in the below problematic method call ExecuteSqlRaw(). The call stack is ExecuteSqlRaw()->RawSqlCommand::Build(). Now Build() method calls GenerateParameterName() and not "GenerateParameterNamePlaceholder()", hence even though I have override GenerateParameterNamePlaceholder() there is no impact of the same, since its not calling this method. We do need "GenerateParameterName()" as well. The "parameter placeholder" i.e. "?" in our case doesn't get replaced against "@p0", "@p1" etc. Hence I thought may be I need to override "RawSqlCommand::Build()" method, but there is no such infra/interface/class in Npgsql Postgres EF core code. Please let me know if any other way I need to address this.

var updOut = schoolContext.Database.ExecuteSqlRaw("update Students set Name = '{0}' where StudentID = '{1}'", name1, id2);

**Comment by roji** [comment]
@deokershesh have you overridden GenerateParameterName as well, to make it return `?`? In fact, the [default implementation of GenerateParameterNamePlaceholder](https://github.com/dotnet/efcore/blob/18f47ea879d975bc24ea389391d3e191a46d1d6a/src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs#L91) simply calls GenerateParameterName, so if you override GenerateParameterName to return `?` things should work.

However, I do think RawSqlCommandBuilder may need to be fixed to use GenerateParameterNamePlaceholder, opened #22458 to track.

**Comment by deokershesh** [comment]
GenerateParameterName() can't return unique value each time i.e. "?", because the output of GenerateParameterName() gets added into the list "substitutions.Add(substitutedName);" which doesn't like duplicate values in the list!

Thanks for opening ticket to fix the issue.

**Comment by roji** [comment]
Why is it a problem for `substitutions` to contain duplicate values? It's just a List...

**Comment by deokershesh** [comment]
May be not the list but one of following calls certainly didn't like duplicate values...

relationalCommandBuilder.AddParameter(parameterName, substitutedName);
parameterValues.Add(parameterName, parameter);

**Comment by roji** [comment]
Can you post a full exception stack for that?

**Comment by deokershesh** [comment]
@roji, Tried to make GenerateParameterName() return "?" and this particular test case seem to work, as it uses "parameterName" from the "parameterNameGenerator.GenerateNext()" method eventually.

I don't recall exactly the test case which failed and reported "duplicate" issue (may be in dictionary usage!), but I 100% remember that making GenerateParameterName() to return "same value" all the time didn't work in few cases. I believe, originally the purpose of this method is to return different value each time, however GenerateParameterNamePlaceholder() could always be same, since its just place holder for the parameter marker.

**Comment by roji** [comment]
@deokershesh I don't see any particular reason to suppose that GenerateParameterName needs to return anything unique; I'd expect that for providers where DbParameter.ParameterName doesn't matter at all (i.e. any provider using positional parameters), it would just be null everywhere, for example.

Beyond #22458 which is already open, I'm going to need to see an actual failure with all the details in order to investigate this further.

**Comment by deokershesh** [comment]
ok, are you suggesting the below 3 methods to return "?" (or particular marker supported) where "parameter name" is not supported by underlying database?

        public override string GenerateParameterName(string name)
           => "?";

        public override void GenerateParameterName(StringBuilder builder, string name)
            => "?";

        public override string GenerateParameterNamePlaceholder(string name)
            => "?";

**Comment by roji** [comment]
Yes, but as I wrote above, you don't need to override GenerateParameterNamePlaceholder since it already calls GenerateParameterName by default.

**Comment by deokershesh** [comment]
Thanks for confirmation. If all 3 of methods returns the same value, then making another stack call could be avoided.

**Comment by deokershesh** [comment]
Another challenge is that below methods returns '?' (with single quote around) and eventually my query becomes "update Students set Name = '?' where StudentID = '?' ", which is not accepted by database. It expects "parameter marker" just as ? (question mark) and not with single quote around. In case of GenerateFromSql() private method in my earlier post, since its my private method, I had replaced '?' with just ? (without single quote) and it works, once "GenerateParameterNamePlaceholder()" returns '?'. I can't do the same in "RawSqlCommand::Build()" method as its not override! Please suggest.

public override string GenerateParameterName(string name)
       => "?";

public override string GenerateParameterNamePlaceholder(string name)
       => "?";

**Comment by roji** [comment]
I don't understand... All of these methods should return a simple question mark, without any single ticks. What is the exact issue you're facing with that?

**Comment by deokershesh** [comment]
public override string GenerateParameterNamePlaceholder(string name)
=> "?";

The above returns '?' (single quotes around), I would need a method which returns "char" (without single quotes) instead of "string". May be something below, but there is no virtual method GenerateParameterNamePlaceholder()/GenerateParameterName() which returns "char".

public override **char** GenerateParameterNamePlaceholder()
=> '?';

public override **char** GenerateParameterName()
=> '?';

The above methods would suffice for me. Also above methods should be called from its respective callers i.e. "RawSqlCommand::Build()".

The above methods would help me to get below SQL query, no single quote around ?(question mark which is parameter marker) :

update Students set Name = ? where StudentID = ? <== This is **valid** syntax for my database

Instead of currently ?(question mark which is parameter marker) is surrounded by single quotes.  

update Students set Name = '?' where StudentID = '?' <== This is **invalid** syntax for my database

**Comment by roji** [comment]
Where are the single quotes coming from? AFAICT EF doesn't add them... Why do you think that these methods need to return char? Whatever string is returned from them should end up embedded, as is, in the final SQL, without any surrounding quotes of any kind.

**Comment by deokershesh** [comment]
>>Where are the single quotes coming from? AFAICT EF doesn't add them...
I am also looking for the answer, I thought this forum will provide the answer. However I believe, Its coming because it returns "string", you can try to quickly debug above methods and see from where its coming, it will return something like '@p0' (with single quote around), I believe this is the property (of C# compiler?) of any "string" value being returned from method.

>>Why do you think that these methods need to return char?
I already answered in my previous post, my SQL query expects only question mark (?) not with quotes. Hence if method is returning with single quote, I have to make my own changes to convert to "only single quote" which I am doing where I have control, but in case of "RawSqlCommand::Build()" I have no control since its not overridden! by the Npgsql Postgres current code.

**Comment by roji** [comment]
@deokershesh there's nothing in C# (compiler or otherwise) which surrounds values with single quotes - both string and char are printed as-is. The single quotes are most likely coming from somewhere in your code.

FWIW in any other provider, the named parameter placeholders (e.g. `@p`) are also outputted without any quotes around them (that would be an error).

**Comment by deokershesh** [comment]
Thanks @roji , It was test case problem, it was written with '{0}' and so on...
Please update once we have fix for https://github.com/dotnet/efcore/issues/22458

**Comment by roji** [comment]
@deokershesh you can subscribe to #22458 to be updated of progress there. Note that it will not be done for 5.0, which is already almost closed for changes. However, as written above, unless I'm mistaken this should not be blocking for you.

**Comment by deokershesh** [comment]
Thanks @roji for update.
