### ISSUE TITLE
Mapping identity columns to enum properties not working in 3.1.5 / 3.1.8 / 5.0.0-preview.8.20407.4

### ISSUE THREAD

**Issue by cceuroform** [dotnet/efcore#22446]
I use proper enumerations to prevent mixing int from different tables.
Based on:
[https://github.com/dotnet/efcore/issues/11970](https://github.com/dotnet/efcore/issues/11970)
[https://github.com/dotnet/efcore/issues/13814](https://github.com/dotnet/efcore/issues/13814)
I wrote the provided code.

When running the code I got the following error:

**Identity value generation cannot be used for the property 'DeviceID' on entity type 'Device' because the property type is 'Device_Values'. Identity value generation can only be used with signed integer properties.**

I have tried the code with the following versions of EF Core

- 3.1.5
- 3.1.8
- 5.0.0-preview.8.20407.4

Can you provide any guidance/workaround for how to fix this?

### Steps to reproduce
``` C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.ValueGeneration.Internal;
using System;

namespace EFCoreTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using var ctx = new MyContext();
            ctx.Devices.Add(new Device());
            ctx.SaveChanges();
        }
    }
    public enum Device_Values { }
    public partial class Device
    {
        public Device_Values DeviceID { get; set; }
    }
    public class MyContext : DbContext
    {
        public virtual DbSet<Device> Devices { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var converter = new ValueConverter<Device_Values, int>(v => (int)v, v => (Device_Values)v, new ConverterMappingHints(valueGeneratorFactory: (p, t) => new TemporaryIntValueGenerator()));
            modelBuilder.Entity<Device>(entity => entity.Property(e => e.DeviceID).ValueGeneratedOnAdd().UseIdentityColumn().HasConversion(converter));
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("test");
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```
### Further technical details

EF Core version: 3.1.5 & 3.1.8 & 5.0.0-preview.8.20407.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: Visual Studio 2019 16.8 Preview

**Comment by ajcvickers** [comment]
@cceuroform This is currently not supported--issue #11970, which you reference above, is tracking adding support for this.
