### ISSUE TITLE
Allow specifying online option on ALTER TABLE ... ALTER COLUMN

### ISSUE THREAD

**Issue by ivansemenovv** [dotnet/efcore#22451]
For a highly available zero-downtime deployment, we would need the ability to perform online index operations on Azure SQL Database:

ALTER TABLE ... ALTER COLUMN  ... WITH (ONLINE = ON)

Is there anything in EF Core that supports this and if not, is this something on the teams roadmap?

**Comment by AndriySvyryd** [comment]
Duplicate of #22351
