### ISSUE TITLE
How to detect changed properties?

### ISSUE THREAD

**Issue by Nebelkraehe** [dotnet/efcore#2245]
Hello.

At the moment I´m looking for a method/property delivering the changed properties inside an entity.
I detect the changes by `EntityState` but I can´t find any access to receive only the changed properties without iterating the whole properties for changes. 

In earlier versions this information was accessible by `ObjectStateEntry.GetModifiedProperties()`. Is there any equivalent way in EF7?

Thanks in advance.

Nebelkraehe

**Comment by rowanmiller** [comment]
Here is the code you need to write at the moment.

```
            var entry = context.Entry(myEntity);
            var propertyNames = entry.Metadata.GetProperties().Select(p => p.Name);
            var modifiedProperties = propertyNames.Select(p => entry.Property(p)).Where(e => e.IsModified);
```

Leaving open as this code is worse than I was expecting and we may want to bump up priority of implementing the missing APIs here.

**Comment by Nebelkraehe** [comment]
Thank you very much. 
A direct access would be great.

**Comment by Nebelkraehe** [comment]
How about inserting this two methods into [EntityEntry](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/ChangeTracking/EntityEntry.cs)-Class?
```
public virtual IEnumerable<string> GetModifiedPropertyNames()
{
	return Metadata.GetProperties().Where(e => Property(e.Name).IsModified).Select(s => s.Name);
}

public virtual IEnumerable<IProperty> GetModifiedProperties()
{
	return Metadata.GetProperties().Where(e => Property(e.Name).IsModified);
}
```

**Comment by rowanmiller** [comment]
Opened up a high level item to track this and other APIs that we want to implement on ChangeTracker/Entry https://github.com/aspnet/EntityFramework/issues/2295
