### ISSUE TITLE
entity framework 3.1 appears to retain a copy of the dbcontextmodelsnapshot despite being deleted

### ISSUE THREAD

**Issue by eric10k93** [dotnet/efcore#22466]
I wanted to reset my migrations from scratch, as I have had a handful of issues in the project related to EF Core.  I deleted my Migrations folder as well as removed all migrations from the __efmigrationshistory table.  Now, when I attempt to add a new migration it generates a migration with a single changed model (as if it is still making comparisons against a DbContextModelSnapshot file... but the file no longer exists, so I don't understand what it is comparing against.

### Steps to reproduce

I have a startup project with a DbContextFactory and a target project where I actually manage the migrations.  I am attempting to run everything from the package manager console in visual studio.

I am attempting to follow the steps listed here under "Resetting all migrations":
https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations

I delete my migrations folder and clear all migrations in the __efmigrationshistory table.

Then I run "Add-Migration Test123 -Project TestTools.Eatl"

This successfully creates a new migrations folder with just this migration and a new model snapshot file.

BUT, I was expecting the new migration to recreate the entire database since no previous migrations exist (or the file should be empty?)... what actually happens is the migration contains code for one table change that I don't want applied to the database... then, if I run "Script-Migration -Project TestTools.Eatl", it DOES create the SQL code for the entire database (BUT it doesn't include the latest migration I just added "Test123").

I'm not sure if this bug is related to using a different target project than the startup project, but EF Core appears to be finding data where there shouldn't be any since I have deleted it.  Are there other places in code that tell EF Core where to look for a model snapshot?

Lastly, to add to the issue... if I attempt at this point to run "Remove-Migration -Project TestTools.Eatl", I get an error stating that one of the previously deleted migration files can't be removed because it wasn't found... Where is it even finding the name of that file since I deleted my entire migrations folder and cleared the __efmigrationshistory table?  It doesn't even attempt to remove the currently unapplied migration "Test123"... it is trying to remove a previously applied migration (that technically should no longer exist).

![image](https://user-images.githubusercontent.com/3928446/92631166-382d6b80-f28e-11ea-8cee-ed2e15ae07d4.png)
![image](https://user-images.githubusercontent.com/3928446/92631198-45e2f100-f28e-11ea-8b2e-ead67db7634c.png)
![image](https://user-images.githubusercontent.com/3928446/92631215-4aa7a500-f28e-11ea-8501-904bcb5db9f5.png)

### Further technical details

EF Core version: 3.1.7
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET Standard 2.0 Class Library
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by eric10k93** [comment]
Seems to be that this was an issue with getting the project to look at the correct referenced project... despite having deleted the referenced NuGet package and adding the project as a direct reference in the solution, it was still pointing to an older version of the migrations project... so this is more of an assembly reference issue it appears...  I think I've finally got it resolved by removing and re-adding all references.

**Comment by lauxjpn** [comment]
This is a continuation of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1155.

**Comment by lauxjpn** [comment]
@eric10k93 Glad you were able to resolve it!
