### ISSUE TITLE
Detect simple join tables in reverse engineering and create many-to-many relationships

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22475]

**Comment by ajcvickers** [comment]
Notes from triage:
* The pri-zero here is that a database created by EF6 with many-to-many relationships should reverse-engineer to EF Core with many-to-many relationships. Specifically, the join table must contain only columns for the two FKs and these columns must also form the primary key. If the table has a separate PK or any payload columns, then it should not be considered many-to-many.
* Meeting the EF6 scenario should also mean that simple, fully by-convention many-to-many relationships created by EF Core will round-trip.
* It's too late to do this for EF Core 5.0.

@ErikEJ Might you consider doing this in the EF Core Power Tools? That would make something available for 5.0. Also, in the future, if you want to do the PR for here, that would be awesome! 😁

**Comment by ErikEJ** [comment]
@ajcvickers I assume that would require changes to code generation, then?

**Comment by ajcvickers** [comment]
@ErikEJ Yes, it probably would. @bricelam?

**Comment by ErikEJ** [comment]
Ok - I have already reluctantly pulled in some Internal code anyway. Happy to take a PR for this!!

**Comment by smitpatel** [comment]
It would probably require some changes to code gen. Currently there is no processing of SkipNavigations in code gen at all. I think best place to identify and add skip navigation would be RelationalScaffoldingModelFactory (now we are deep in internal territory lol) to add skip navs to model and code gen will handle it as such.

**Comment by ErikEJ** [comment]
Hmmm.. where would I specify the table name (since it most likely will not match convention) 

Assume in fluent config, but how, since there is no EntityType to refer to??

**Comment by smitpatel** [comment]
```C#
modelBuilder.Entity<One>().HasMany(e => e.TwoSkip).WithMany(e => e.OneSkip).UsingEntity(e => e.ToTable("tableName"));
```
EF will fill in actual entity type appropriately, whatever that type would be by convention. (Likely Dictionary<string, object>)
(Untested code)

**Comment by bmoteria** [comment]
@smitpatel The provided solution doesn't seem to work in my scenario as the table "FeatureVehicle" contains two columns which has underscore ("Feature_ID" and "Vehicle_VehicleID"). (cc @ajcvickers)

When query is executed it throws following exception:
```
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type '<PRODUCT>.Data.Context.<PRODUCT>DbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'FeaturesID'.
Invalid column name 'VehiclesID'.
Invalid column name 'VehiclesID'.
Invalid column name 'VehiclesID'.
Invalid column name 'FeaturesID'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:76b39b9f-06db-43a9-ae78-d7820dd60584
```

Here are my entities:
```
public partial class Vehicle
{
     ....
     public ICollection<Feature> Features { get; set; }
}

public partial class Feature
{
     ....
     public ICollection<Vehicle> Vehicles { get; set; }
}
```

**Comment by smitpatel** [comment]
@bmoteria - Your issue is not related to the issue you are posting on. Please avoid off-topic discussions. Your column names in the join entity does not match what is generated conventionally, so you will need to configure them manually using HasColumnName.

**Comment by cgountanis** [comment]
I am ready for this change, we use database first and it would be great if it automatically did the Many to Many so something like `context.Posts.Include(e => e.Tags)` would work automatically.

```
CREATE TABLE [Posts] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(max) NULL,
    CONSTRAINT [PK_Posts] PRIMARY KEY ([Id])
);

CREATE TABLE [Tag] (
    [Id] int NOT NULL IDENTITY,
    [Text] nvarchar(max) NULL,
    CONSTRAINT [PK_Tag] PRIMARY KEY ([Id])
);

CREATE TABLE [PostTag] (
    [PostsId] int NOT NULL,
    [TagsId] int NOT NULL,
    CONSTRAINT [PK_PostTag] PRIMARY KEY ([PostsId], [TagsId]),
    CONSTRAINT [FK_PostTag_Posts_PostsId] FOREIGN KEY ([PostsId]) REFERENCES [Posts] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_PostTag_Tag_TagsId] FOREIGN KEY ([TagsId]) REFERENCES [Tag] ([Id]) ON DELETE CASCADE
);

CREATE INDEX [IX_PostTag_TagsId] ON [PostTag] ([TagsId]);
```

**Comment by strich** [comment]
I'm quite confused here. The EF Core documentation goes to some length to tell me how to setup many to many relationships but according to the pictured note (At the bottom of the page!) and this issue, it isn't actually available yet?
![image](https://user-images.githubusercontent.com/987896/110777327-ea9fb480-8258-11eb-87f2-7226d891137f.png)

Is there a work around documented?

**Comment by smitpatel** [comment]
Detection is "easy"
@dotnet/efteam  - What do we want to print out in code files?

**Comment by AndriySvyryd** [comment]
Calls to the methods that will be added by https://github.com/dotnet/efcore/issues/21535

**Comment by ErikEJ** [comment]
@ajcvickers is it still the intention to do this in 6.0 - when is "feature freeze" ?

**Comment by ajcvickers** [comment]
We are going to have to cut some things, but this is currently still in the plan. Lower in the stack is freezing now. EF/ASP, etc. have about a month more.

**Comment by ErikEJ** [comment]
Fingers crossed!

**Comment by smitpatel** [comment]
I have code for detection ready in a branch. Just waiting for APIs to be added which would be scaffolded eventually.

**Comment by ErikEJ** [comment]
Will this be in RC1 then?

**Comment by ajcvickers** [comment]
Filed https://github.com/dotnet/EntityFramework.Docs/issues/3411

**Comment by GSPP** [comment]
Can this be disabled? That would be good for two reasons:

- Existing code (either from an older EF version or from another ORM) might depend on the join table to be an explicit class.
- Making it a class is more future-proof because you can now easily add additional columns without a big refactoring.

**Comment by ajcvickers** [comment]
@GSPP We discussed this, but the feeling on the team was that it should be covered by #4038. Also, keep in mind you can later add a join entity with additional columns without changing existing code that uses the relationship as many-to-many. It's not one or the other, like it was in EF6.

**Comment by ErikEJ** [comment]
@ajcvickers Would it be possible to somehow tweak the generated DatabaseModel so an join entity would be generated?

**Comment by ajcvickers** [comment]
@ErikEJ Note sure. Maybe @smitpatel knows. (Thinking of allowing this in the Power Tools?)

**Comment by ErikEJ** [comment]
Exactly!

**Comment by ajcvickers** [comment]
@ErikEJ I think this would be worthwhile. If need be, we'll consider making minor changes to EF 6.0 to allow you to do this.

**Comment by ErikEJ** [comment]
Maybe an annotation to disable a table from participating in many-to-many without join table?

**Comment by smitpatel** [comment]
Current determination is done by https://github.com/dotnet/efcore/blob/a69c2ca667ffdad57845b2a2e578648f9247ff0b/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs#L1136-L1160

which is purely based on IEntityType rather than IDatabaseTable.
We can introduce annotation for providers to put on IDatabaseTable to tell us it is many to many join table though it could also become pit of failure especially to scaffold a join table we need to know both skip navigations (hence the current check is on IEntityType). Annotation put on arbitrary table would fail very abruptly when writing code. Perhaps a different extension point would serve better.

@ErikEJ - How does power tools work that it need something on database model or cannot utilize current code?

**Comment by ErikEJ** [comment]
Power Tools simply uses the default CSharpDbContextGenerator.cs, but it hooks into the DatabaseModel generation, and manipulates that in flight.

I was looking for a simple way to exclude a table from many-to-many, not include, to allow users to opt out on a per table basis.

**Comment by smitpatel** [comment]
Looking at power tools code, I see that you already have one derived class for `RelationalScaffoldingModelFactory`, if you are fine overriding it and copying some code then overriding `VisitForeignKeys` would get you that in 6.0. Basically you use the code without skip navs (how it was in 5.0) to skip M2M join table. Once we don't add skip navigations there, rest of the code should generate code for it like a normal entity.

**Comment by ErikEJ** [comment]
@smitpatel  Perfect! I will consider that if customers ask for it!

**Comment by ajcvickers** [comment]
@ErikEJ So it looks like right now you don't need us to add/change things for you?

**Comment by ErikEJ** [comment]
@ajcvickers Correct!

**Comment by hgsenger** [comment]
Hi, although this is a nice feature we have the following scenario, where we have some trouble with it:
- Table 'A'
- Table 'B'
- MappingTable1 A <-> B (m:n)
- MappingTable2 A <-> B (m:n)

Scaffolding the database context fails in this case with the error message that the navigation property Table 'B' cannot be added twice to Table 'A'.

It would be nice if the navigation property names could be based on the intersection table name(s) to circumvent this issue.

**Comment by AndriySvyryd** [comment]
@hgsenger This will be fixed in 6.0.1

**Comment by glucklichman** [comment]
Hi, I take a simple many-to-many relationship. After scaffolding I will take one entity with two Reference navigation and two entities  **without** collection navigation. As I read the documentation, the two entities mave to include the collection navigation.

```
public partial class PersonTrainingCourse
{
        public int PersonId { get; set; }
        public int CourseId { get; set; }

        public virtual TrainingCourse Course { get; set; }
        public virtual Person Person { get; set; }
}
```
And dbContext includes only one-to-many relationships
```
modelBuilder.Entity<PersonTrainingCourse>(entity =>
            {
                ...

                entity.HasOne(d => d.Course)
                    .WithMany()
                    .HasForeignKey(d => d.CourseId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Person<>TrainingCourse_TrainingCourse");

                entity.HasOne(d => d.Person)
                    .WithMany()
                    .HasForeignKey(d => d.PersonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Person<>TrainingCourse_Person");
            });
```

**Comment by moritzinio** [comment]
> Hi, I take a simple many-to-many relationship. After scaffolding I will take one entity with two Reference navigation and two entities **without** collection navigation. As I read the documentation, the two entities mave to include the collection navigation.
> 
> ```
> public partial class PersonTrainingCourse
> {
>         public int PersonId { get; set; }
>         public int CourseId { get; set; }
> 
>         public virtual TrainingCourse Course { get; set; }
>         public virtual Person Person { get; set; }
> }
> ```
> 
> And dbContext includes only one-to-many relationships
> 
> ```
> modelBuilder.Entity<PersonTrainingCourse>(entity =>
>             {
>                 ...
> 
>                 entity.HasOne(d => d.Course)
>                     .WithMany()
>                     .HasForeignKey(d => d.CourseId)
>                     .OnDelete(DeleteBehavior.ClientSetNull)
>                     .HasConstraintName("FK_Person<>TrainingCourse_TrainingCourse");
> 
>                 entity.HasOne(d => d.Person)
>                     .WithMany()
>                     .HasForeignKey(d => d.PersonId)
>                     .OnDelete(DeleteBehavior.ClientSetNull)
>                     .HasConstraintName("FK_Person<>TrainingCourse_Person");
>             });
> ```


I have the same Problem. DBContext only hast one-to-many relationships even thought the database has many-to-many relations.

**Comment by ErikEJ** [comment]
@moritzinio please open a new issue, and share your database schema.

**Comment by moritzinio** [comment]
@ErikEJ I will tomorrow thank you.

**Comment by sommmen** [comment]
@ajcvickers hiya this docs page https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many

Points to this workitem which seems to be closed. Is this now fixed or not? perhaps the docs should be updated?

**Comment by Scionn** [comment]
> @ajcvickers hiya this docs page https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many
> 
> Points to this workitem which seems to be closed. Is this now fixed or not? perhaps the docs should be updated?

I don't think its SOLVED, we have the same problem today with the latest version of EF core 6.0.6 (at the moment) scaffolding a Postgresql database with two m-2-m tables...

**Comment by ajcvickers** [comment]
@Scionn Please open a _new_ issue and post the schema and command that results in the issue so that we can investigate.

**Comment by RicardOlivo** [comment]
Maybe missing something here, but I'm baffled at how or why would Microsoft arbitrarily force a set of rules and decide which and when a table will be reverse engineered and when to skip it, without even a flag to supress it. Is there a way to full scaffold using net 6 without this nonsense, other than doing it by hand? thanks

**Comment by ErikEJ** [comment]
@RicardOlivo Yes, just use EF Core Power Tools!

**Comment by tuyendam00** [comment]
I still want ef core gen class mapping many-many in net 6.0, how to do it
I want:
modelBuilder.Entity<GenerateProjectProgrammingLanguageMapping>(
entity =>
            {
                entity.HasKey(e => new { e.GenerateProjectId, e.ProgrammingLanguageId });

                entity.ToTable("GenerateProjectProgrammingLanguageMapping", "MDM");

                entity.HasOne(d => d.GenerateProject)
                    .WithMany(p => p.GenerateProjectProgrammingLanguageMapping)
                    .HasForeignKey(d => d.GenerateProjectId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_GenerateProjectProgrammingLanguageMapping_GenerateProject");

                entity.HasOne(d => d.ProgrammingLanguage)
                    .WithMany(p => p.GenerateProjectProgrammingLanguageMapping)
                    .HasForeignKey(d => d.ProgrammingLanguageId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_GenerateProjectProgrammingLanguageMapping_ProgrammingLanguage");
            });

Ef gen:
 entity.HasMany(d => d.ProgrammingLanguages)
                    .WithMany(p => p.GenerateProjects)
                    .UsingEntity<Dictionary<string, object>>(
                        "GenerateProjectProgrammingLanguageMapping",
                        l => l.HasOne<ProgrammingLanguageDAO>().WithMany().HasForeignKey("ProgrammingLanguageId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_GenerateProjectProgrammingLanguageMapping_ProgrammingLanguage"),
                        r => r.HasOne<GenerateProjectDAO>().WithMany().HasForeignKey("GenerateProjectId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_GenerateProjectProgrammingLanguageMapping_GenerateProject"),
                        j =>
                        {
                            j.HasKey("GenerateProjectId", "ProgrammingLanguageId");

                            j.ToTable("GenerateProjectProgrammingLanguageMapping");
                        });

**Comment by RicardOlivo** [comment]
@tuyendam00 I did it using net core 3.1, then copy/pasted into 6. Sad I know.

**Comment by ErikEJ** [comment]
@tuyendam00 @RicardOlivo Just use EF Core Power Tools, it has an option to generate the actual entities
