### ISSUE TITLE
Incorrect query generated when using Skip and Enum Where condition when Skip value is same as enum value

### ISSUE THREAD

**Issue by etamm** [dotnet/efcore#22524]
Sorry if this problem has been posted before, I couldn't find any issues with similar problem.

Ef core generates invalid SQL when the Skip value is the same as Enum value in a Where condition, when Skip statement is before the Where clause.

I added an example query that generates the expected result (at least considering how it handles the Enum value), but in my current project it is not possible to use that variant (at least not very easily). 
I don't think that it should matter in what order the Skip statement is applied, it shouldn't use the same parameter for the `offset` and `where` predicate. 
Note also that if the Skip value of the original query would be changed to anything else than 0 (the enum value) it would also generate good SQL.

In my current project the issue manifests in the final select projection. Pagination/filters are applied on the inner query and the final query uses a sub query that selects a child entity by applying a similar Enum filter. In Postgresql (database used in the project), because of type mismatch the following error is thrown: `42883: operator does not exist: text = integer` (It tries to compare enum that is stored as `text` with the integer offset parameter).

### Steps to reproduce
Query that generates incorrect SQL
``` C#
 await context.Foos.Skip(0).Where(x => x.Type == FooEnum.A).ToListAsync();
```
Sql generated (notice `@__p_0` parameter usage)
``` SQL
SELECT [t].[Id], [t].[Type]
   FROM (
     SELECT [f].[Id], [f].[Type]
     FROM [Foos] AS [f]
     ORDER BY (SELECT 1)
     OFFSET @__p_0 ROWS
 ) AS [t]
 WHERE [t].[Type] = @__p_0
```

Query that doesn't have the problem (returns expected result). Note Skip was moved after the Where condition
``` C#
 await context.Foos.Where(x => x.Type == FooEnum.A).Skip(0).ToListAsync();
```
Sql generated: 
``` SQL
SELECT [f].[Id], [f].[Type]
FROM [Foos] AS [f]
WHERE [f].[Type] = N'A'
ORDER BY (SELECT 1)
OFFSET 0 ROWS
```
I would expect even the first example to generate the same Where condition: `WHERE [f].[Type] = N'A'`.
Especially because changing the Enum (or Skip) value also generates the expected SQL:
``` C#
 await context.Foos.Skip(0).Where(x => x.Type == FooEnum.B).ToListAsync();
```
Sql generated
``` SQL
SELECT [t].[Id], [t].[Type]
  FROM (
      SELECT [f].[Id], [f].[Type]
      FROM [Foos] AS [f]
      ORDER BY (SELECT 1)
      OFFSET @__p_0 ROWS
  ) AS [t]
  WHERE [t].[Type] = N'B'
```
Or original query with Skip(1):
``` C#
 await context.Foos.Skip(1).Where(x => x.Type == FooEnum.A).ToListAsync();
```
Sql generated
``` SQL
SELECT [t].[Id], [t].[Type]
  FROM (
      SELECT [f].[Id], [f].[Type]
      FROM [Foos] AS [f]
      ORDER BY (SELECT 1)
      OFFSET @__p_0 ROWS
  ) AS [t]
  WHERE [t].[Type] = N'A'
```

Full code example project (has more variations and working examples), uses Sql server local db:
[EfCoreSkipEnumBug.zip](https://github.com/dotnet/efcore/files/5217876/EfCoreSkipEnumBug.zip)

### Further technical details

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer & Npgsql.EntityFrameworkCore.PostgreSQL (maybe also others)
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.2

Thank you.

**Comment by ajcvickers** [comment]
@maumar to look for dupe.

**Comment by etamm** [comment]
Because I didn't think that this problem is a result of seemingly some kind of a parameter usage optimization (at least it looks like this) I didn't explicitly mention that we are storing the enums as text in the database (using EnumToStringConverter).

Probably if we would store the enum integer values in the database this wouldn't be a problem.

**Comment by maumar** [comment]
related issue: https://github.com/dotnet/efcore/issues/19128

**Comment by smitpatel** [comment]
This is in funcletization and arises from quite different issue. See #19503
