### ISSUE TITLE
Soft deletable Entity (with required relationship) marked for deletion throws InvalidOperationException before calling SaveChanges()

### ISSUE THREAD

**Issue by alexaka1** [dotnet/efcore#22561]
My model has 3 classes, `Foo`, `Bar` and `FooBar`. `FooBar` was created to make many-to-many relationship between `Foo` and `Bar`.
`Foo` contains a List of `FooBar`s. `FooBar` contains one `Foo` and one `Bar`, with both (non-nullable) foreign keys and navigation properties. `Foo` is soft deletable, `FooBar` is not, and `Bar` isn't soft deletable either, but only because it's non-changing data, basically just exists to store Enums (but that's besides the point).

I want to delete a `Foo` object, I call:
```C#
Foo foo = /* gets passed down as argument */
_db.Attach(foo).State = EntityState.Deleted; // this line throws an exception when .Net Core 3.1 or above is used
await _db.SaveChangesAsync(cancellationToken);
```
Now note the `State` modification. I intentionally don't use `_db.Remove()`, because I want the `FooBar` children to be left alone (since nothing would happen to them anyway, because only one property would change on `Foo` for all EF Core cares). (But I have tried this with `Remove()` and the same exception is thrown.)
The `SaveChanges()` method is an override to handle `EntityState.Deleted` entities, and just set them as soft-deleted.
```C#
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
{
// other preprocessing ... (this code is never reached though, because of the exception thrown above)
foreach (var entry in ChangeTracker.Entries<ISoftDeletable>().Where(e => e.State == EntityState.Deleted))
            {
                entry.State = EntityState.Unchanged;
                entry.Entity.Deleted = true;
             }
// other processing
await base.SaveChangesAsync(cancellationToken);
}
```

The above code worked perfectly well in ASP.Net Core 2.2. `Foo` had `foo.Deleted` set to `true`, and the child entities remained unchanged.

However both on the latest ASP.Net Core 3.1 and on ASP.Net 5 rc.1 (EF Core 5.0.0-rc.1.20451.13) the following exception is thrown, when I change the State to Deleted:

> System.InvalidOperationException: The association between entity types 'Foo' and 'FooBar' has been severed but the relationship is either marked as 'Required' or is implicitly required because the foreign key is not nullable. If the dependent/child entity should be deleted when a required relationship is severed, then setup the relationship to use cascade deletes.

Did I miss a breaking change? Why would setting the EntityState trigger an exception? If I didn't handle the soft deletion, and I just called `base.SaveChanges()`, then 100% I am at fault, because a required relationship is not configured to cascade. The following is my delete behaviour for relationships:
```C#
foreach (IMutableForeignKey relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
```
But this exception is thrown before I even get to handling the deletion. And I believe EF Core shouldn't start to freak out before I even call `SaveChanges()`. And this now breaks my code completely, because I'm not even sure how to fix it. If I changed the foreign key to be nullable or changed the relationship to be NOT required, then I would change intented behavior, and I could create `FooBar`s that don't include a `Foo`, which makes no sense.

**Comment by ajcvickers** [comment]
@alexaka1 You are probably hitting this: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#cascade

It's easy to switch back to the pre-3.1 behavior, as shown in the "mitigations" section.

If this doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by alexaka1** [comment]
@ajcvickers I did miss that change. Putting in 
```C#
base.ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges;
base.ChangeTracker.DeleteOrphansTiming = CascadeTiming.OnSaveChanges;
```
 in my own context constructor solved it. My bad :)
Although I'm still confused about this behavior for `...State = EntityState.Deleted;`. My understanding was that this only affects the specific entity, and calling `Remove()` is the one that rounds up all the potential relationships for deletion as well.

**Comment by ajcvickers** [comment]
@alexaka1 Usually calling `Remove` or setting the state to Deleted do the same thing. If I am remembering correctly, the only difference is if the entity is not being tracked before Remove is called.
