### ISSUE TITLE
Generic Query from Set fails with Interface 

### ISSUE THREAD

**Issue by BC89** [dotnet/efcore#22567]
After upgrading to EF Core 5 RC1 this breaks 

```C#
var vals = _context.Set<IAuditableEntity>(element.FullName).ToList();
````

With error - Cannot create DbSet for entity type 'LuAnalysis' since it is of type 'LuAnalysis' but the generic type provided is of type 'IAuditableEntity'.

Code leading up to the error is as follows. 

```C#
List<Type> domainlist;

            var domains = new List<Domain>();

            var alllist = _context.Model.GetEntityTypes().Select(t => t.ClrType).ToList();

            if (targetDomain is null)
            {
                domainlist = alllist.Where(n => n.Name.StartsWith("Lu")).ToList();
            }
            else
            {
                domainlist = alllist.Where(n => n.Name.StartsWith(targetDomain)).ToList();
            }

            if (domainlist.Count > 0)
            {
                foreach (var element in domainlist)
                {

                    var vals = _context.Set<IAuditableEntity>(element.FullName).ToList();
```

All domain classes inherit from  IAuditableEntity which is essential a placeholder for soft deletes.

```C#
public partial class LuAppQueueType : IAuditableEntity { 
[Key]
        public Guid AppQueueTypeId { get; set; }
        public string Description { get; set; }
}
```

```C#
public interface IAuditableEntity    {    }
```

EF Core version: 5.0.0-rc.1.20451.13
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 v 16.7.3)

**Comment by BC89** [comment]
Should add that it was working with for all preview builds of EF Core 5

**Comment by ajcvickers** [comment]
@BC89 The generic type for a `DbSet<TEntity>` must be the actual concrete type of the entity. I'm surprised that `var vals = _context.Set<IAuditableEntity>(element.FullName).ToList();` was not throwing in the previews, but this seems to have been fixed for RC1 since it is now throwing the correct exception.
