### ISSUE TITLE
.NET 5.0 RC1 p.SetColumnType("[money]") results in wrong type in migration

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#22569]
If you have a property of type `decimal` and do `p.SetColumnType("[money]")` using .NET 5.0 RC1 the migration will specify another type, because it will specify `[money](18,2)`.

Money however neither has precision nor scale, so it fails when updating the database.

If you manually substitute "`[money](18,2)`" => "`[money]`" as you actually specified using `p.SetColumnType("[money]")`, it works fine.

**Comment by ajcvickers** [comment]
@henrikdahl8240 Using square brackets around type names is not something that EF Core expects, and hence EF doesn't recognize `[money]` as a type it knows and falls back to the default behavior for a decimal property with an unknown store type. It shouldn't add (18, 2) to this, so that's a bug. However, when using the SQL Server type in a form that EF understands (`p.SetColumnType("money")`) I see the correct behavior.

Is there a reason you're specifying type names in this way?

**Comment by henrikdahl8240** [comment]
@ajcvickers OK, so I will remove the brackets. I thought that the argument is forwarded as is to SQL Server and if you try to use the context menu in SQL Server Management Studio for a database and select Tasks => Generate Scripts ..., types appear with brackets around in line with the usual reasons for using brackets when using SQL Server. Therefore I put the brackets around, like e.g. [money].
In the previews it has worked fine. In my opinion it was quite reasonable to expect, that the argument for SetColumnType should be specified in terms of the software dealing with columns, i.e. in terms of SQL Server. The summary for SetColumnType is "Sets the database type of the column to which the property is mapped." and I suppose that what is given in a script produced by SQL Server Management Studio should be the canonical representation, which I therefore used.

**Comment by ajcvickers** [comment]
@henrikdahl8240 We'll discuss.

**Comment by henrikdahl8240** [comment]
I think there should be made a clear decision on the nature/syntax of the actual argument and the documentation should be clear, so you have no doubt as you use the feature.

**Comment by ajcvickers** [comment]
@henrikdahl8240 That's reasonable, although in my 12+ years on EF I think this is the first time I have ever seen anyone use square brackets in this API.

**Comment by henrikdahl8240** [comment]
I also have this construction in my code:
`modelBuilder.Model.GetEntityTypes().SelectMany(entityType => entityType.GetDeclaredProperties()).Where(p => p.ClrType == typeof(DateTimeOffset)).ToList().ForEach(p => p.SetColumnType("[datetimeoffset](0)"));`

As far as I remember, it does not work withoug brackets, but only with brackets, at least in some of the .NET 5.0 previews and therefore I have consistently put brackets around the type lexemes.
