### ISSUE TITLE
"The framework 'Microsoft.NETCore.App', version '2.0.0' was not found" error while adding migration for .NET 5.0-preview7 project with dotnet ef 5.0-rc1

### ISSUE THREAD

**Issue by bairog** [dotnet/efcore#22593]
Hello.
I have simple class library project with a EF Core 5.0-rc1 DbContext that targets .NET 5.0-preview7 (I'm using **.NET 5-preview7** because according to [info on download page](https://dotnet.microsoft.com/download/dotnet/5.0) it is the latest one that supports Visual Studio 2019 v**16.7 Release**. I use only stable IDE builds in my project and cannot use preview IDE versions).
I've installed latest Entity Framework Core .NET Command-line Tools 5.0.0-rc.1.20451.13
When I'm trying to add migration via **dotnet ef migrations add InitialCreate --verbose** command I get an error:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.0-preview.7.20364.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
In my Visual Studio 2019 16.7.3 Professional I have .NET Core 3.1 SDK (LTS) option checked and .NET Core 2.1 SDK (LTS) **unchecked**.
I also have .NET 5.0-preview7 SDK installed.

### Steps to reproduce

1. Download test project - https://yadi.sk/d/T6MXHQEFScnKbQ
2. Uninstall all .NET Core 2.x SDKs
3. Install latest Entity Framework Core .NET Command-line Tools 5.0.0-rc.1.20451.13
4. Run **dotnet ef migrations add InitialCreate --verbose** command in test project folder

### dotnet ef migrations add InitialCreate --verbose output:

```
dotnet ef migrations add InitialCreate --verbose
Using project 'D:\Test\Test\Test.csproj'.
Using startup project 'D:\Test\Test\Test.csproj'.
Writing 'D:\Test\Test\obj\Test.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Leo.TOPAZ1\AppData\Local\Temp\tmp10F2.tmp
 /verbosity:quiet /nologo D:\Test\Test\Test.csproj
Writing 'D:\Test\Test\obj\Test.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Leo.TOPAZ1\AppData\Local\Temp\tmp12C8.tmp
 /verbosity:quiet /nologo D:\Test\Test\Test.csproj
Build started...
dotnet build D:\Test\Test\Test.csproj /verbosity:quiet /nologo

Сборка успешно завершена.
    Предупреждений: 0
    Ошибок: 0

Прошло времени 00:00:01.38
Build succeeded.
dotnet exec --depsfile D:\Test\Test\bin\Debug\net5.0\Test.deps.json --additionalprobingpath C:\Users\Leo.TOPAZ1\.nuget\packages
 --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder"
 C:\Users\Leo.TOPAZ1\.dotnet\tools\.store\dotnet-ef\5.0.0-rc.1.20451.13\dotnet-ef\5.0.0-rc.1.20451.13\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll
 migrations add InitialCreate --assembly D:\Test\Test\bin\Debug\net5.0\Test.dll --startup-assembly
 D:\Test\Test\bin\Debug\net5.0\Test.dll --project-dir D:\Test\Test\ --language C# --working-dir D:\Test\Test --verbose --root-namespace Test
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.0-preview.7.20364.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=win10-x64
```

### Further technical details

EF Core version: **5.0-rc1**
Database provider: **Microsoft.EntityFrameworkCore.Sqlite 5.0-rc1**
Target framework: **.NET 5.0-preview7**
Operating system: **Windows 10 2004 x64**
IDE: **Visual Studio 2019 16.7.3 Professional**

**Comment by ajcvickers** [comment]
@bairog Why are you using preview 7 of .NET 5? Your project builds for me correctly with the RC1 SDK installed.

**Comment by bairog** [comment]
@ajcvickers I'm using **.NET 5-preview7** because according to [info on download page](https://dotnet.microsoft.com/download/dotnet/5.0) it is the latest one that supports Visual Studio 2019 v**16.7 Release**. I use only stable IDE builds in my project and cannot use preview IDEversions.

**Comment by ajcvickers** [comment]
@bairog While technically there is no specific reason I know of that using an old ASP.NET Core preview should fail, it's not a configuration that we test. There is an expectation that people move to the latest available preview. For ASP.NET Core 5.0, this requires a preview version of Visual Studio, assuming you need Visual Studio. If that's not something you can use, then you might want to try testing EF Core 5.0 RC1 using ASP.NET Core/.NET Core 3.1. If that's doesn't work for you, then unfortunately you'll probably have to wait until GA releases of ASP.NET Core and Visual Studio.

In this case, what version of the `dotnet-ef` tool are you using? Make sure it is updated to the RC1 release.

**Comment by bairog** [comment]
@ajcvickers I'm using latest dotnet-ef **5.0.0-rc.1.20451.13**. Ok, I've got it that **.NET 5.0-preview7** + **EF Core 5.0-rc1** is not expected to be used togethet. I will wait until .NET and У Core 5 GA. Thank you.
