### ISSUE TITLE
Aggregation extensions in OData ASP.NET Core fail when using SQL Server

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#22601]
Please read the post https://github.com/OData/WebApi/issues/2293

Is it due to errors in EF Core 5.0 RC1?

If yes, is it fixed in the daily builds?

**Comment by smitpatel** [comment]
EF Core does not expand navigations used after GroupBy operator. Filed #22069 It is not fixed in daily build. We will consider it in next release. As mentioned in tracking issue on OData, they are adding a solution for OData to work.
