### ISSUE TITLE
Add ef migration for a conext without namespace, we get ArgumentNullException 

### ISSUE THREAD

**Issue by balachir** [dotnet/efcore#2261]
Using Dev14 RC (beta4)
1. New Empty Web API app : AspNet5BookService
2. Add class Author.cs to Models folder

```
namespace AspNet5BookService.Models
{
    public class Author
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}
```

3, Add BookServiceContext.cs class to Models folder - but forgot to set the namespace

```
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata;

    public class BookServiceContext : DbContext
    {
        private static bool _created = false;

        public DbSet<Author> Authors { get; set; }

        public DbSet<Book> Books { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=BookServiceContext;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
        }
    }
```

4, Add EF migration

**ACTUAL**
Exception below. It took a little while to figure out that missing namespace was the issue

![image](https://cloud.githubusercontent.com/assets/8246794/7781118/71e29186-009d-11e5-83fa-7d48dac33b01.png)

**Comment by rowanmiller** [comment]
This is no longer an issue as of RC1. You do still get an invalid `using` (tracked by https://github.com/aspnet/EntityFramework/issues/2467), but the migration is scaffolded.
