### ISSUE TITLE
5.0 RC1 Many-to-many optional navigation properties

### ISSUE THREAD

**Issue by Atulin** [dotnet/efcore#22627]
Right now, it seems that the necessary code to create many-to-many is

```cs
class Post
{
  public int Id { get; set; }
  public ICollection<Tag> Tags { get; set; }
}

class Tag
{
  public int Id { get; set; }
  public ICollection<Post> Posts { get; set; }
}
```
```cs
builder.Entity<Post>()
  .HasMany(p => p.Tags)
  .WithMany(t => t.Posts);
```

but what about optional navigation properties, when I want only `Post` to have a list of `Tag`s, but not necessarily the `Tag` to have a list of `Post`s?

```cs
class Post
{
  public int Id { get; set; }
  public ICollection<Tag> Tags { get; set; }
}

class Tag
{
  public int Id { get; set; }
}
```
```cs
builder.Entity<Post>()
  .HasMany(p => p.Tags)
  .WithMany();
```

That would also be in line with other relationships, where

```cs
builder.Entity<Post>()
  .HasOne(p => p.Category)
  .WithMany();
```

is perfectly valid and doesn't require a `Category` to contain a collection of `Post`s.

**Comment by ajcvickers** [comment]
Related/dupe: #3864

**Comment by ajcvickers** [comment]
@Atulin This isn't supported for 5.0. I've updated #3864 to indicate that this is the issue tracking unidirectional many-to-many relationships. Please vote for that issue.
