### ISSUE TITLE
5.0 RC1 UseIdentityColumn arguments unstable in snapshot?

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/efcore#22632]
When I upgraded from 3.1 to 5.0 RC1, all my old `SqlServerValueGenerationStrategy.IdentityColumn` annotations was upgraded to `UseIdentityColumn()`.

Now whenever I remove a migration with "_dotnet ef migrations remove_" all `UseIdentityColumn()` will be changed to `UseIdentityColumn(1,1)` in the model snapshot file..

.. but if I afterwards add another migration with "_dotnet ef migrations add_" they will revert back to `UseIdentityColumn()`. 

Doesn't seem to do any harm, but it generates a lot of diff in git. Is this expected behaviour?

**Comment by ajcvickers** [comment]
@smitpatel to investigate

**Comment by smitpatel** [comment]
@ajcvickers - 5 or 6?
