### ISSUE TITLE
Mark join entities as Added when one or both ends are Added

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22647]
See discussion in #22621

The fundamental problem with attaching entities at either end of a many-to-many is that these entities do not contain any information that would indicate whether the join entities are new or existing. We assume that they are existing, but if either end of the many-to-many is Added, then I think we should assume they are new and put them in the Added state. This won't make attaching many-to-many without additional state work in general since we still have no way of knowing if two existing entities were previously related or not, but it will make the default better for the case where one or both is Added.

**Comment by ajcvickers** [comment]
Note that we already do this when using `context.Update` rather than `context.Attach`.

**Comment by atiyar** [comment]
@ajcvickers Could you please notify if/when its available in the daily builds?
