### ISSUE TITLE
The EF Core tools version '3.1.8' is older than that of the runtime '5.0.0-rc.1.20451.13'

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#22660]
I have updated EF Core Tools to latest 5.0.0-rc.1.20451.13 and when I run ```Add-Migration MyMigration``` in VS2019 Package Manager Console I get the following warning ```The EF Core tools version '3.1.8' is older than that of the runtime '5.0.0-rc.1.20451.13'. Update the tools for the latest features and bug fixes.```

### Further technical details

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1
Operating system: Windows 10
IDE: VS2019 Pro 16.7.4

**Comment by ajcvickers** [comment]
@pantonis Please post your csproj file and the output from `dotnet ef --info`.

**Comment by bricelam** [comment]
...and the output of `dotnet tool list` and `dotnet tool list --global`

**Comment by pantonis** [comment]
I found the issue. I was not referencing  ```Microsoft.EntityFrameworkCore.Tools``` to my startup project. I have three projects. One for Api, one for migrations and one for the actual app. I am using Package manager console and I have set default project the one for migrations.  Once I referenced ```Microsoft.EntityFrameworkCore.Tools``` in startup project (Api) warning went away
