### ISSUE TITLE
Toolchain for detecting expressions that cannot be translated

### ISSUE THREAD

**Issue by Danielku15** [dotnet/efcore#22663]
I think everyone potentially ran into this already when migrating from EF6 to EFCore: client-side evaluated queries (EFCore 2.x) and runtime InvalidOperationExceptions for expressions that cannot be translated (EFCore 3.x). Currently there is no obvious way for developers to know while coding if an expression might not be translatable. 😞

In a happy world you have full test coverage of your codebase and you would catch any InvalidOperationException in your unit or integration tests. But being realistic: 

a) Migrating projects from .net Framework to .net core (and related libraries) is still not complete. Tons of companies have products with a classical stack and are aiming for a migration. It would be luxury to have full coverage in such enterprise environments.
b) With every new query you write, you might make multiple rounds on rephrasing and re-testing them until EF Core can actually translate them. 

I think many developers face this pain of not being able to clearly see during development/design time whether the code, which is syntactically and semantically right, might also work during runtime. 😖

The first thing that came into my mind as a potential solution is: Roslyn Analyzers. Neglecting the cost behind such a feature to be developed it would give developers an amazing development experience if the IDE would instantly highlight that a query cannot be translated by EF Core. Again being realistic this is likely to costly to have as analyzer which constantly verifies the corresponding expressions. 

That's why I thought it might be rather realistic to have an extension of the CLI tools for EF Core. Using Roslyn APIs we could crawl all potential EF core expressions and do a verification whether the corresponding queries can be translated. 

Thinking simplistic, a tool could work like this: 

* Setup the base EF design time infrastructure for inspecting the DbContext related metadata. 
* Scan a given source tree of your projects for any Linq expressions which might result in a EF Core query. 
* Use a similar logic like the QueryCompiler to translate the expressions to a query and check for potential errors. 
* Report the results which are then reviewed by a developer. 

Obviously there is quite an effort behind this as during runtime you have really all information available about your DB, Models, custom query translators etc. But I assume such a system anyhow needs to grow over time with new checks and scenarios that people will report not to be working correctly. 

**Disclaimer:** We just migrated from EF6 to EFCore 3.1 and are constantly facing runtime exceptions which we try to cover step by steps with unit tests and catch all application paths. I was thinking whether I could develop such a tool on my own using EF internals, but I fear I might be lacking currently of some essential EFCore details to really to this properly. I thought of opening such a dicussion and try to get feedback if others also wish for such a thing. If not, we can of course close then the discussion here 😉

**Comment by ErikEJ** [comment]
Why not invest in a tool that can run all your queries against a live database - not for correctness, but simply to prevent errors?

I did that once, using reflection to enumerate all repository methods, and then calling with mocked parameters.

**Comment by Danielku15** [comment]
This might only work if your repositories are rather simple and mapped directly down to queries. In our case repositories also ensure certain business rules. Especially when it comes to operations which create/update records: Depending on the input values we might load related data for foreign keys and/or insert multiple items into multiple tables. In many cases randomized parameters will rather result in errors than a proper query execution. Also certain queries might require corresponding data preparation on the server to trigger the related query paths. 

To give some metrics: The product we're working on is older than 10yrs and and provides a lot of functionality with many edge cases and special scenarios. That might also be one of the main reasons why not full coverage exist. We have more than 30 repositories and more than 400 repository methods mapping down to one or more queries. 

We are already actively working on increasing the coverage to have all queries at least executed without checking too many details. But as you can imagine this results also in quite some development costs. It already resulted in quite some costs to do the migration and product management is obviously not happy to hear that we need to invest more time to sort out all the potentially hidden things that were broken due to this upgrade. Also Quality Assurance has a tough time with these hidden broken things, which again results in costs for testing and issue management. 

Considering that many teams/projects likely suffer from this, the costs multiply accordingly in the market.

**Comment by roji** [comment]
As you've written, a static analysis is a pretty huge investment. One big hurdle is that the EF query pipeline processes LINQ expression trees, but a Roslyn analyzer - or any other sort of static analysis - provides Roslyn syntax/semantic models, which are very different. The translation between the two is anything but trivial. Moreover, it's not even clear whether it can reliably identify all EF query scenarios and determine whether they can be translated. One notable example is dynamic queries, where users construct LINQ expression trees based on some input - there's really no way we'd ever be able to handle that kind of thing. I personally thing it's an interesting problem to explore and maybe prototype at some point, but it's definitely a very complicated and tenuous proposal.

For the purpose of knowing whether your program will run, static analysis is also quite limited. Yes, it may be able to tell you if you're using an unsupported LINQ construct or method call, but that's a very narrow of "working". In practice, data operations frequently involve multiple queries/updates with interdependence, or rely on data in the database being in a certain way - a theoretically translatable query may easily fail in the context of a real program. I'm trying to say that in a real application, there's simply no way to be confident that code runs except by providing proper test coverage for it.

One last note... Such a static analysis tool was requested especially during the transition from 2.2 to 3.0, where queries that were client-evaluating previously stopped working as we disabled that feature; this kind of high-impact breaking change is really unlikely to occur again - queries that are currently working (i.e. 3.1) will, as a general rule, continue working. So while I understand the desire for such a tool in a significant migration (from EF6, from EF Core 2.2), it makes much less sense to me going forward for a product that's already on EF Core 3.1 and above.

**Comment by AndriySvyryd** [comment]
We have a limited amount of available resources and this feature would provide less value for the investment than most of the other features we currently have in the backlog, so it's very unlikely that it will ever make it over the cut. So we'll close it preemptively to avoid having it in limbo for the next X years.
Since it would be a design tool it can be shipped separately from EF. So we do encourage anyone who decides to tackle it on their own and will consider reasonable changes to EF code to make it work.

**Comment by ErikEJ** [comment]
@Danielku15 Just enable logging of client evaluation, that should get you quite far. https://twitter.com/JonnySchnittger/status/1315762561657253888
