### ISSUE TITLE
Unexpected side-effects when checking ChangeTracker.HasChanges

### ISSUE THREAD

**Issue by ChristophHornung** [dotnet/efcore#22671]
When temporarily setting an entity property to `null` before setting a new value there are side effects from calling `ChangeTracker.HasChanges()` on the context.

E.g.
```csharp
blog.Author = null;
db.ChangeTracker.HasChanges();
blog.Author = new Author() {Name = "NonMVPAuthor"};
```

This code will mark the `blog` entity as deleted, while removing the `HasChanges` call does not.

### Steps to reproduce

Run the code from this project [EFCoreDetectChangesSideEffects.zip](https://github.com/dotnet/efcore/files/5263355/EFCoreDetectChangesSideEffects.zip)

Notice how for the test with `HasChanges` the blog entity gets deleted on save, while without it the blog entity only updates.

This behaviour makes debugging certain scenarios quite difficult when checking for changes unexpectedly alters the behaviour. The method should ideally be side effect free or at least document it's side effects.

### Further technical details

EF Core version: both 5 RC 1 and 3.1.8
Database provider: seems to be independent from the provider
Target framework: .net core 3.1

**Comment by ajcvickers** [comment]
@ChristophHornung This is because `HasChanges` automatically calls `DetectChanges` so that the answer returned reflects any changes of state that happen from changes to the entity's property values. In this case, EF detects that the relationship was severed and reacts accordingly.

**Comment by ChristophHornung** [comment]
@ajcvickers So it is intentional that calling `HasChanges` has side-effects that can alter the outcome of the next `SaveChanges`? Why doesn't the change detection recognize that after setting the `Author` to a new value that this was a simple replacement and not a deletion (as it correctly decides when not calling `HasChanges`)?

Is there any documentation regarding when it is 'safe' to call `HasChanges` without any accidental side-effects? Or is the recommendation to only call it before `SaveChanges`?

**Comment by ajcvickers** [comment]
@ChristophHornung By default, EF Core performs cascading actions, including deleting orphans, immediately that the change is detected. If you wish to defer this, which seems appropriate in this case, then try setting:

```C#
context.ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges;
context.ChangeTracker.DeleteOrphansTiming = CascadeTiming.OnSaveChanges;
```

These changes will then only be made when SaveChanges is called, which in your case means the delete will not happen at all since you change it into a re-parent before saving.
