### ISSUE TITLE
Inherited Classes Mapping 

### ISSUE THREAD

**Issue by alfkonee** [dotnet/efcore#2267]
Inherited Classes in EF models need to be related in the database with the Generalization rule in database normalization.
Eg: I have four classes Person Guardian Student and Teacher. The last three inherit from the first but when I run the CreateTables function for database I get four different Tables each with all the fields inherited from the Person table. Instead of the related tables I would have gotten in EF 6

**Comment by Boglen** [comment]
try 
public class SomeContext : DbContext
{
public DbSet<Person> Persons {get;set;}
}

not public DbSet<Guardian > Guardians {get;set;} and etc

**Comment by alfkonee** [comment]
I'm using IdentityDbContext will it still work if I remove the Inherited classed DbSet

**Comment by rowanmiller** [comment]
Inheritance isn't fully implemented yet in EF7. Pieces of it are implemented but there is no end-to-end support enabled yet. The work is being tracked by https://github.com/aspnet/EntityFramework/issues/247.

**Comment by weitzhandler** [comment]
This issue is a breaker.
