### ISSUE TITLE
Fetching unnecessary data for nested objects when the IQueryable is converted.

### ISSUE THREAD

**Issue by aradalvand** [dotnet/efcore#22685]
Sorry about the title if it's a little confusing, I couldn't think of a better one!
I have 2 domain classes: `Book` and `Author`, and 2 DTOs: `BookDto` and `AuthorDto`, which are a subselection of their respective entities. Nothing complicated so far.
I want to convert an `IQueryable<Book>` (which is the `DbSet<Book>` on my `AppDbContext`) into an `IQueryable<BookDto>` and then expose that to enable the client code to the query the `BookDto`, as opposed to the `Book` domain class, if you will.

## Steps to Reproduce:
First convert the `IQueryable<Book>` into an `IQueryable<BookDto>`:

```
IQueryable<BookDto> queryableDto = dbContext.Books.Select(book => new BookDto
    {
        Name = book.Name,
        ...
        Author = new AuthorDto
        {
            Id = book.Author.Id,
            Name = book.Author.Name,
            ...
        }
    });
```
Now, if I you this (get the name of the book):

```
queryableDto.Select(bookDto => bookDto.Name).FirstOrDefault();
```
Inspecting the EF Core's generated SQL, it's only fetching the `Name` of the book and nothing else, which is great.

But then if you do something like this (get the name of the author of the book):
```
queryableDto.Select(bookDto => bookDto.Author.Name).FirstOrDefault();
```
I get the name of the author successfully, but looking at the EF Core's generated SQL, I realized that this time it's actually retrieving all the data of the author from the database, which is not what I asked for, as you can see I requested only the Name of the Author. Doesn't it make sense for EF Core to do just as it did when I requested the name of the book? Which is to only retrieve the name of the author and not the whole object?

I know there's definitely a reason behind this, but I would say it's not the ideal behavior.

## Details:
EF Core Version: I've tried this with both 3.1.8 (latest stable) and 5.0.0 RC
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7

**Comment by smitpatel** [comment]
Which version of EF Core are you using? Share a runnable repro code which shows the issue you are seeing and what is the generated SQL for that scenario?

**Comment by AradAral** [comment]
Sorry, this wasn't a problem with EF Core.
