### ISSUE TITLE
Filtered include not respected when using select

### ISSUE THREAD

**Issue by leonardder** [dotnet/efcore#22680]
I'm working with a group of db tables that's following the pattern as outlined in classes below. Note that I pretty much simplified the example here.

```
	public class Relation {
		public Int32 StoreId { get; set; }
		public virtual Store Store { get; set; }
		public String RelationNumber { get; set; }
		public String RelationName { get; set; }
	}
	
	public class User { 
		public Int32 StoreId { get; set; }
		public virtual Store Store { get; set; }
		public String UserName { get; set; }
	}

	public class Store {
		public Int32 Id { get; set; }
		public virtual List<Relation> Relations { get; set; }
		public virtual List<User> Users { get; set; }
	}
```

The relation number consists of the first six characters of the user name. There is no direct relation to user mapping in the database, which is of course pretty weird.

### Steps to reproduce
Use the following query:

```
            context.Users
                .Include(l => l.Store.Relations.Where(r => r.RelationNumber == l.UserName.Substring(0, 6)))
                .Select(l => new UserRelationInfo
                {
                                        UserName = l.UserName,
                                        RelationName = l.Store.Relations.Single().RelationName
                })
                ...
```

It looks like that, when using select this way, the filtered include is not yet applied to the Relations navigation property. Therefore, the resulting query simply gets the first entry from the Relations table where the store id is matches. The where clause doesn't contain a check for relation number.

I'd have to use something like this:

```
            context.Users
                .Include(l => l.Store.Relations)
                .Select(l => new UserRelationInfo
                {
                                        UserName = l.UserName,
                                        RelationName = l.Store.Relations.Where(r => r.RelationNumber == l.UserName.Substring(0, 6)).Single().RelationName
                })
                ...
```

### Further technical details

EF Core version: 5.0RC1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7

**Comment by smitpatel** [comment]
Filtered include applies filter only when loading the navigation property if the root object is in the final result. If you are having the data from navigation property in the result in some way then you need to write filter on the navigation directly. 2nd way you have showed is actually right way to query it.

**Comment by leonardder** [comment]
Thanks for pointing this out. Would it be helpful to document this in the [Filtered include](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include) section?
