### ISSUE TITLE
Execution strategy retries and lingering DbContext state 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22704]
Moved from discussions

### Question

@Timovzl

The EF6 documentation states something that seems to make sense, which the EF Core documentation omits, as far as I'm aware:

> Note that any contexts should be constructed within the code block to be retried. This ensures that we are starting with a clean state for each retry.

https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/retry-logic#solution-manually-call-execution-strategy

```C#
executionStrategy.Execute(
    () =>
    {
        using (var db = new BloggingContext())
        {
            // Snip
        }
    });
```

What is the intended way to achieve this behavior with EF Core?

* If we take roughly the same approach with EF Core, will it have the intended effect?
* Does EF Core have a cleaner, built-in way that has the intended effect? (I'm making this assumption because the EF Core documentation does not have such instructions as described above.)

There are a few reasons why the resulting behavior is desirable:

1. If we have a rich domain model with a method that moves it from state A to B, such a method tends to throw an InvalidOperationException if it was already in state B. After all, such use tends to indicate developer error. However, if the DbContext remembers the modifications from the previous retry attempt, we will run into such exceptions. Instead, our retry should start with a clean slate, just like the initial attempt naturally did. The retry should not be affected by circumstance.

2. We would like to be sure that the DbContext is not holding any reference to a previous, abandoned transaction. (Maybe it doesn't, but it's hard to be certain without acquiring a new DbContext.)

### Replies

From @ajcvickers

@Timovzl Are you asking only about the case where you manually call the execution strategy?

---

From @Timovzl

@ajcvickers That is correct! Because that seems to be the most ubiquitously reliable way to achieve transactionality - especially for special cases such as serverless database plans, where retries are essential.

--- 

From @AndriySvyryd

> If we take roughly the same approach with EF Core, will it have the intended effect?

Yes

> Does EF Core have a cleaner, built-in way that has the intended effect? (I'm making this assumption because the EF Core documentation does not have such instructions as described above.)

If you don't recreate the context then when the action is retried it will be in the same state as before the exception was thrown, so as long as you only change state outside of the action that's retried then it should work fine.

> We would like to be sure that the DbContext is not holding any reference to a previous, abandoned transaction. (Maybe it doesn't, but it's hard to be certain without acquiring a new DbContext.)

It doesn't, but it's recommended that you start and commit the transaction manually when using the execution strategy manually.

---

From @Timovzl

Thanks @AndriySvyryd!

So what concerns me is that we need an additional, practically-unused DbContext instance to do things the way I described above: the one that merely creates the execution strategy. It seems a bit smelly and wasteful, and I'm trying to see if it can be avoided.

> It doesn't [hold any reference to a previous, abandoned transaction], but it's recommended that you start and commit the transaction manually when using the execution strategy manually.

Yes, I was assuming manual transaction control. If I manually start a transaction, and then there is a connection issue during SaveChangesAsync, and the retry kicks in... will the DbContext still hold a reference to the broken transaction on the next attempt? (Clearly, when using a new DbContext instance inside the execute block, it does not, since there is a brand new DbContext, but I mean when we forego that approach.)

> If you don't recreate the context then when the action is retried it will be in the same state as before the exception was thrown, so as long as you only change state outside of the action that's retried then it should work fine.

Then does that mean that the following undesirable scenario is possible, when not using separate instances?

* Attempt 1 loads an entity and invokes some logic on it that changes its state from A to B.
* A retry occurs, for whatever reason.
* Attempt 2 loads the entity, but sees it present in its change tracker, and uses the existing (already modified) instance.
* The logic to change the entity's state to B throws an exception, since changing from state B to state B is considered an invalid operation.
* We can no longer recover, because we had expected to start fresh, but the DbContext reuse and the change tracker prevented that.

That is the sort of thing I'm really trying to avoid. I suppose my question really boils down to this: To truly start fresh, is there an equally reliable way that does not need the practically-unused DbContext instance just to create the execution strategy?

If not, could we dispose the strategy-creating DbContext once it has created the strategy, and then use that strategy? After all, if we were to take the above approach everywhere, with pooling, we would be wasting half of our DbContext pool.

---

From @AndriySvyryd

> So what concerns me is that we need an additional, practically-unused DbContext instance to do things the way I described above: the one that merely creates the execution strategy. It seems a bit smelly and wasteful, and I'm trying to see if it can be avoided.

As long as you don't use .Model, .SaveChanges or any DbSet just creating a new context instance won't noticeably impact perf.

> If I manually start a transaction, and then there is a connection issue during SaveChangesAsync, and the retry kicks in... will the DbContext still hold a reference to the broken transaction on the next attempt?

No

> Then does that mean that the following undesirable scenario is possible, when not using separate instances?

Yes, that's why I'd recommend moving any state-affecting logic outside of the action being retried.

> To truly start fresh, is there an equally reliable way that does not need the practically-unused DbContext instance just to create the execution strategy?

Yes. If you are using DI you can inject the ExecutionStrategyDependencies service and use that to create the execution strategy (SqlServerRetryingExecutionStrategy if you are using SQL Server for example).

> If not, could we dispose the strategy-creating DbContext once it has created the strategy, and then use that strategy? After all, if we were to take the above approach everywhere, with pooling, we would be wasting half of our DbContext pool.

No, services from a disposed context shouldn't be used in any way, especially if you are using context pooling. Also if you are using pooling you can just increase the pool size to accommodate this. Context instances don't consume a large amount of memory as they use a common cache for many services.

When comparing these options from a perf standpoint please use a benchmark as the effects in a real application are hard to predict.

---

From @Timovzl

> No, services from a disposed context shouldn't be used in any way, especially if you are using context pooling.

Don't dispose the one used to create a strategy. Got it.

> Yes, that's why I'd recommend moving any state-affecting logic outside of the action being retried.

It can actually be very important for application developers to have state-affecting logic inside the action being retried. If the data happens to be changed by another process in between our attempts, then the business operation being performed may actually have become an invalid operation. If we reload, we realize this and act accordingly. If we do not, we may store the entity in an invalid state - a state not expected by the rest of the system, potentially introducing subtle bugs in other parts of the application. (With change tracking, we risk an invalid state because we overwrite only some properties. Without change tracking, we overwrite everything and potentially undo the other process' operation, which is probably undesirable as well.)

That is what makes the EF6 documentation on manually calling the execution strategy such good advice, in my opinion.

> As long as you don't use .Model, .SaveChanges or any DbSet just creating a new context instance won't noticeably impact perf.
Also if you are using pooling you can just increase the pool size to accommodate this.

Ok, so doubling the pool size could work. Still, I'd prefer not to touch it: Deviating from the default practically opts out of changes to the default made by the EF team (which is very nice to have), and from a library I can make no assumptions about the application's pool size.

> If you are using DI you can inject the ExecutionStrategyDependencies service and use that to create the execution strategy (SqlServerRetryingExecutionStrategy if you are using SQL Server for example).

Interesting alternative. I suppose with ActivatorUtilities we could even protect ourselves against constructor changes. Unfortunately, I really cannot hard-code the use of any particular execution strategy from a class library.

One workaround might be to get an execution strategy from the DbContext once, and from then on use ActivatorUtilities to create instances of its type.

As another alternative, could I permanently claim just a single DbContext instance from the pool, and use that only for creating execution strategies? (I suppose that would mean counting on thread-safety of the CreateExecutionStrategy operation.)

---

From @AndriySvyryd

> As another alternative, could I permanently claim just a single DbContext instance from the pool, and use that only for creating execution strategies? (I suppose that would mean counting on thread-safety of the CreateExecutionStrategy operation.)

Sure. CreateExecutionStrategy just calls a constructor.

---

From @Timovzl
> If you are using DI you can inject the ExecutionStrategyDependencies service and use that to create the execution strategy (SqlServerRetryingExecutionStrategy if you are using SQL Server for example).

> Interesting alternative. I suppose with ActivatorUtilities we could even protect ourselves against constructor changes. Unfortunately, I really cannot hard-code the use of any particular execution strategy from a class library.
One workaround might be to get an execution strategy from the DbContext once, and from then on use ActivatorUtilities to create instances of its type.

I like this approach for not claiming to be related to any particular DbContext. Unfortunately, it did not work, since ExecutionStrategyDependencies is not in the application's container. I expect it is in EF's internal container. @AndriySvyryd How did you have this in mind?

Also, is ExecutionStrategyDependencies a singleton in EF's internal container? Otherwise, DbContext.GetService<T>() will only come from the correct scope if we use a new DbContext whenever we try to create a strategy - which is what I'm trying to avoid.

> As another alternative, could I permanently claim just a single DbContext instance from the pool, and use that only for creating execution strategies? (I suppose that would mean counting on thread-safety of the CreateExecutionStrategy operation.)

> Sure. CreateExecutionStrategy just calls a constructor.

This approach seems to be working!

I have run into some challenges with setting a DbContext aside with this. It would save a lot of trouble if I could do this instead:

```
// Create DbContext for attempt #1
// Create execution strategy from the DbContext
// ExecutionStrategy.ExecuteAsync:
  // If not attempt #1, dispose DbContext and create new one
  // Start transaction from DbContext
  // Perform work against DbContext: load, modify, save
  // Commit transaction
```
This combines two advantages:

* Have a fresh DbContext per attempt, preventing any state leakage between attempts.
* Not need an externally stored DbContext to create the strategy.
I realize that you said not to use anything (the IExecutionStrategy) from a disposed DbContext. But what do you think about this:

Since we rely on the fact that CreateExecutionStrategy just calls a constructor, doesn't that mean that we also rely on the fact that the resulting IExecutionStrategy is completely detached from the DbContext that created it? And doesn't that invariably lead to the conclusion that disposal of the DbContext has nothing to do with the created strategy?

If we agree that these assumptions boil down to the same thing, then I can take this easier approach. If I'm missing something and they are not the same, then I'll have to juggle a single DbContext for execution strategy creation.

Your support is greatly appreciated.

---

From @AndriySvyryd

> Unfortunately, it did not work, since ExecutionStrategyDependencies is not in the application's container. I expect it is in EF's internal container. @AndriySvyryd How did you have this in mind?

Yes, I am so used to the internal service provider that I forgot you couldn't access it.

> Since we rely on the fact that CreateExecutionStrategy just calls a constructor, doesn't that mean that we also rely on the fact that the resulting IExecutionStrategy is completely detached from the DbContext that created it? And doesn't that invariably lead to the conclusion that disposal of the DbContext has nothing to do with the created strategy?

No, the constructor that is called takes the current context, options and logger and they are actively used when the strategy is executing something. The IExecutionStrategy cannot be used after disposing the context used to create it.

In 5.0 you can use context.ChangeTracker.Clear() to reset the currently tracked entities.

**Comment by Timovzl** [comment]
I am happy to report that reusing the DbContext and using `DbContext.ChangeTracker.Clear()` in between attempts works perfectly. I use a catch block that clears the change tracker and rethrows the exception, after which the potential retry attempt kicks in.

For the documentation, I would recommend that a section like [this](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/retry-logic#solution-manually-call-execution-strategy) be added, but for EF Core. After all, the technology has changed, but the underlying expectations have not: the scenario is still relevant. Such a section could address the difference between performing the loading and making the changes _inside_ vs. _outside_ the retryable action.

**Comment by Timovzl** [comment]
@AndriySvyryd It just hit me that clearing the change tracker might be insufficient.

Imagine the following scenario:

- A unit of work made a change to the SQL session near the end of its work. For example, it set the isolation level to `READ UNCOMMITTED` and was about to read something that way. (You can probably come up with a better example.)
- The `IExecutionStrategy` (or some custom code that caught a `DbUpdateConcurrencyException`) caused the unit of work to be retried. The connection itself was not interrupted.
- Now _all_ operations in the unit of work are inadvertently run against a SQL session that is set to `READ UNCOMMITTED`.

After we had modified the session state, the only expected path was for the connection to be reset (on the provider level) due to the `DbContext` being disposed, but the retry actually reused the `DbContext` without resetting the connection.

This seems to warrant resetting more thoroughly than just clearing the change tracker.

What operation would you recommend for this? Does `DbContext.Database.CloseConnectionAsync()` suffice to match the disposal behavior? (And is that one safe to call even if the connection happens to not be open?)

**Comment by AndriySvyryd** [comment]
@Timovzl Yes, closing the connection in that way should be ok, as long as nothing else was using it. However, in most cases the connection is closed when a transient error occurs.
