### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2270]
For my EF/ SQLCE provider, I cannot "hijack" EntityFramework.SqlServerCompact - any recommendations/suggestions for package names? (As I plan to release a package on NuGet.org that matches beta5) ? EntityFramework.SqlServerCompact.ErikEJ  ? Or EntityFramework.SqlServerCompact.7 or EntityFramework7.SqlServerCompact  ?

**Comment by bricelam** [comment]
Oh lame; *EntityFramework.SqlServerCompact* would have been ideal. We actually hit a related (but less severe) issue because the EF6 provider assembly was named EntityFramework.SqlServer.

**Comment by rowanmiller** [comment]
EntityFramework.SqlCE or SqlServerCE?

**Comment by rowanmiller** [comment]
BTW we have also had some discussion around including the major version in our package name EntityFramework7.XYZ. There are obviously some serious downsides to doing this... but also some big benefits (especially around not automatically upgrading between major versions with breaking changes). We haven't decided either way... but we are discussing.

**Comment by ErikEJ** [comment]
Thanks, will change to EntityFramework.SqlCe for now (goes well in hand with the names of the top level extension methods)
