### ISSUE TITLE
Using Storedproc in EF Core

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22703]
This issue was moved from discussions.

### Question

@AsifAliBhat

Hi,

Can I invoke a stored proc (which return relational data) in EF core using DbContext.Database.ExecuteSqlCommand() or any other way? I have read somewhere that DbContext.Database.ExecuteSqlCommand() does not support relational data.

Thanks,
Asif

### Replies

@ErikEJ

Yes, you can https://erikej.github.io/efcore/2020/04/06/query-non-table-classes-raw-sql.html

**Comment by AsifAliBhat** [comment]
Thanks, Arthur! You blog gave me a hope. Now, one quick question, can I use sql stored proc instead of raw query on my context?

**Comment by ErikEJ** [comment]
Please provide a code sample of what you are after

**Comment by AsifAliBhat** [comment]
Hi Erik,

I am trying to achieve something like below

var users = context
            .InvoiceData  //->My DTO to store relational data from Invoices, InvoiceDetails and payment table
            .FromSqlRaw("exec prGetInvoiceData @InvoiceID", invID)
            .ToList();

I think this should work for me. Right!

Thanks,
Asif

**Comment by ErikEJ** [comment]
Yes - you can do that, or you could use EF Core Power Tools to create the mappings for you 

https://erikej.github.io/efcore/2020/08/10/ef-core-power-tools-stored-procedures.html

**Comment by AsifAliBhat** [comment]
That was really helpful, Erik!

Thanks much!

**Comment by AsifAliBhat** [comment]
I was able to call the stores proc without parameter, but getting below issue with param:

System.InvalidCastException:The SqlParameterCollection only accepts non null SqlParameter type objects, not SqlParameter object.s.

**Comment by ErikEJ** [comment]
You must be using "Microsoft.Data.SqlClient" and not "System.Data.SqlClient"

**Comment by AsifAliBhat** [comment]
You are simply awesome, Erik! That worked smoothly. I was just able to find you on twitter, will always keep eagle's eye open on your tweets 😊.

Thanks a lot,
Asif
