### ISSUE TITLE
Procedure for skipping navigation property discovery on specific properties in conventions 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22725]
Moved from discussions.

### Question

From @lauxjpn

> We currently implemented JSON support in Pomelo for both, `System.Text.Json` and `Newtonsoft.Json`, based on the work done by @roji for Npgsql. The support is implemented in individual packages (one for each supported JSON library) and based on the underlying plugin infrastructure (like for the NTS implementation).
> 
> `Newtonsoft.Json` uses a couple of DOM classes with properties that would normally be discovered as navigation properties by EF Core. We don't want that, because those classes and properties are being explicitly handled and translated by the query pipeline.

This is a follow-up to https://github.com/dotnet/efcore/issues/9330#issuecomment-687737675.

Lets say we have an entity type called `MyEntity` and a special JSON DOM type called `JToken`:

```c#
// In our code:
public class MyEntity
{
    public int Id {get; set;}
    public JToken JsonProperty {get; set;} // <-- we want a non-navigation property here
}

// In an external JSON library:
public abstract class JToken // <-- we don't want this as an entity of the model
{
    // ...
    public JToken Parent {get; set;}
}
```

What is the recommended procedure to make sure, that the default conventions discover `MyEntity.JsonProperty` and make it part of the model, but will not use it as a navigation property and will not make `JToken` an entity of the model?

Should we just ignore the `JToken` type with `IModelInitiliazedConvention` and then manually add the properties with `IEntityTypeAddedConvention` (and possibly `IEntityTypeBaseTypeChangedConvention`, basically doing what `PropertyDiscoveryConvention` does)?

This is still for `3.1`.

/cc @AndriySvyryd

### Replies

From @lauxjpn

Looks like I just messed up the type mapping resolution. Seems to be working without any additional conventions now.

From @smitpatel

If the type mapping says that it is mappable primitive type then it will be added as property rather than navigation.

From @Timovzl

Out of curiosity, can you demonstrate the code you used to do this?

From @lauxjpn

> If the type mapping says that it is mappable primitive type then it will be added as property rather than navigation.

@smitpatel Yes, that is exactly how it is. I was wondering before, why it was working for Microsoft's `JsonDocument` and `JsonElement` and not Newtonsoft's `JToken`, and just assumed that it was because they are `struct`s and not `class`es. But all that is needed is for the type mapping source to resolve a valid type mapping for a target type and that type is not considered navigable or being a model entity anymore. However, due to some debugging I did before, I was only resolving `JObject` and not `JToken` anymore by accident.

@Timovzl This is how the convention looked like, at the moment I realized that we don't need it at all:

```c#
using System;
using System.Collections.Generic;
using System.Reflection;
using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Utilities;
using Newtonsoft.Json.Linq;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;

namespace Pomelo.EntityFrameworkCore.MySql.Json.Newtonsoft.Metadata.Conventions
{
    public class MySqlJsonNewtonsoftDomEntitiesConvention : IModelInitializedConvention, IEntityTypeAddedConvention
    {
        private static readonly HashSet<Type> _domTypes = new HashSet<Type>
        {
            typeof(JArray),
            typeof(JContainer),
            typeof(JObject),
            typeof(JProperty),
            typeof(JRaw),
            typeof(JToken),
            typeof(JValue),
        };

        public MySqlJsonNewtonsoftDomEntitiesConvention(
            [NotNull] ProviderConventionSetBuilderDependencies dependencies,
            [NotNull] RelationalConventionSetBuilderDependencies relationalDependencies)
        {
            Dependencies = dependencies;
        }

        protected virtual ProviderConventionSetBuilderDependencies Dependencies { get; }

        public virtual void ProcessModelInitialized(
            IConventionModelBuilder modelBuilder,
            IConventionContext<IConventionModelBuilder> context)
        {
            foreach (var domType in _domTypes)
            {
                modelBuilder.Ignore(domType);
            }
        }

        public void ProcessEntityTypeAdded(IConventionEntityTypeBuilder entityTypeBuilder, IConventionContext<IConventionEntityTypeBuilder> context)
        {
            Check.NotNull(entityTypeBuilder, nameof(entityTypeBuilder));

            var entityType = entityTypeBuilder.Metadata;
            if (!entityType.HasClrType())
            {
                return;
            }

            foreach (var property in entityType.GetRuntimeProperties().Values)
            {
                if (IsCandidateProperty(property))
                {
                    entityTypeBuilder.Property(property);
                }
            }
        }

        private bool IsCandidateProperty([NotNull] PropertyInfo propertyInfo)
            => _domTypes.Contains(propertyInfo.PropertyType) &&
               Dependencies.TypeMappingSource.FindMapping(propertyInfo) is MySqlJsonTypeMapping;
    }
}
```

It worked except for the last line `Dependencies.TypeMappingSource.FindMapping(propertyInfo) is MySqlJsonTypeMapping`, which made me realize what the actual issue was.

---

From @Timovzl

Thanks @lauxjpn. I'm actually trying to understand the solution you ended up using. If I'm not mistaken, the essence is in this line (emphasis mine):

But all that is needed is for the type mapping source to resolve a valid type mapping for a target type and that type is not considered navigable or being a model entity anymore.

I don't follow entirely, though, and I'm interested to know how this is done! Do you have a code sample of how you achieved that?

---

From @lauxjpn 

You can take a look at the following files:

* [MySqlJsonTypeMappingSourcePlugin.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/dee2b75d42a24ad21d4b644a92e338cdc97471de/src/EFCore.MySql/Storage/Internal/MySqlJsonTypeMappingSourcePlugin.cs)
* [MySqlJsonMicrosoftTypeMappingSourcePlugin.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/dee2b75d42a24ad21d4b644a92e338cdc97471de/src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMappingSourcePlugin.cs)

They are for the Microsoft JSON handling but do the same. The important part is this one:

From [MySqlJsonMicrosoftTypeMappingSourcePlugin.cs#L33-L41](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/dee2b75d42a24ad21d4b644a92e338cdc97471de/src/EFCore.MySql.Json.Microsoft/Storage/Internal/MySqlJsonMicrosoftTypeMappingSourcePlugin.cs#L33-L41):

```c#
if (clrType == typeof(JsonDocument) ||
    clrType == typeof(JsonElement))
{
    return (RelationalTypeMapping)Activator.CreateInstance(
        MySqlJsonTypeMappingType.MakeGenericType(clrType),
        "json",
        GetValueConverter(clrType),
        Options);
}
```

This is pretty normal stuff for an EF Core provider. I basically just used the "wrong" type in the `clrType == typeof(JsonDocument)` line for the Newtonsoft implementation. That let EF Core believe, that the type I was missing in that line was just a normal user entity and handled it accordingly.

What is the background for you following up on this? Any concrete issues you are trying to solve?

---

From @Timovzl

@lauxjpn None but curiosity! It seemed like a good feature to know how to use, and I did not know enough about it to manage to find examp

**Comment by lauxjpn** [comment]
> Looks like I just messed up the type mapping resolution. Seems to be working without any additional conventions now.

This one has already been resolved and can just be closed.
