### ISSUE TITLE
PrincipalKey without UniqueConstraint? 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22720]
Moved from discussions.

### Question

From @mathiasi

Consider the following:

```csharp
public class A
{
    public string Foo { get; set; }
    public long Id { get; set; }

    public IEnumerable<B> B { get; set; }
}

public class B
{
    [Key]
    public int Id { get; set; }

    public string Bar { get; set; }
}

...
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<A>(b =>
    {
        b.HasKey(x => new {x.Id, x.Foo});

        b.HasMany(x => x.B)
            .WithOne()
            .HasPrincipalKey(x => x.Id);
    });
}
```

Which creates the following migration:

```csharp
migrationBuilder.CreateTable(
    name: "A",
    columns: table => new
    {
        Foo = table.Column<string>(nullable: false),
        Id = table.Column<long>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_A", x => new { x.Id, x.Foo });
        table.UniqueConstraint("AK_A_Id", x => x.Id);
    });

migrationBuilder.CreateTable(
    name: "B",
    columns: table => new
    {
        Id = table.Column<int>(nullable: false)
            .Annotation("Sqlite:Autoincrement", true),
        Bar = table.Column<string>(nullable: true),
        AId = table.Column<long>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_B", x => x.Id);
        table.ForeignKey(
            name: "FK_B_A_AId",
            column: x => x.AId,
            principalTable: "A",
            principalColumn: "Id",
            onDelete: ReferentialAction.Restrict);
    });

migrationBuilder.CreateIndex(
    name: "IX_B_AId",
    table: "B",
    column: "AId");
```

Which is almost what I want, except for the UniqueConstraint on table A! Is there a way around this?

### Replies

From @ajcvickers

@mathiasi The principal key of a relationship is required to be unique, otherwise its ambiguous which row the foreign key is referencing.

**Comment by mathiasi** [comment]
@ajcvickers Right! I get that from a database perspective and maybe my question wasn't super clear but essentially what I wanted to do is to create an aggregation relationship between A and B. I was hoping there was a way to configure it so EF Core would handle the joining for me so I don't have to worry about that.

**Comment by ajcvickers** [comment]
@mathiasi Can you explain what an "aggregation relationship" would look like in this example? In what way will the entities be related in the database?

**Comment by mathiasi** [comment]
Just clarify: when I'm talking about an "aggregation relationship", I'm thinking about this: https://softwareengineering.stackexchange.com/questions/61376/aggregation-vs-composition . It is my general understanding that EF Core likes to do composition relationships as it what databases are good at with foreign keys etc.
But in my case I would like a more loosely relationship, hence the _"B exists independently (conceptually) from A"_ (I guess it is the other way around in my example). 
I'm currently on a project which imports a data-source that has a structure like this, where one entity is referencing part of a composite key and I've had to create a lot of MTM tables to make it work without a lot of manual joins.
I guess from at database perspective it would just be two tables with no constraints between them but EF Core would be configured to automatically do the joining necessary.
Maybe my understanding is wrong and this isn't what EF Core is intended to do so I'm just thinking out loud here :)

**Comment by ajcvickers** [comment]
@mathiasi Thanks, we will discuss.

**Comment by ajcvickers** [comment]
@mathiasi We discussed this, but it's not something we are planning to support. Thanks for the suggestion.
