### ISSUE TITLE
efcore when to support sharding sub-table sub-database

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22731]
Moved from discussions.

### Question

From @apchenjun

efcore when to support sharding sub-table sub-database,If you need to process particularly big data, you need to sub-table and sub-database to operate the database. Currently, there is no suitable component to achieve this function. Is there any official plan to add this feature?

### Replies

From @ajcvickers

@apchenjun We're following up with the SQL team on sharding and looking at creating a simple example. See https://github.com/dotnet/EntityFramework.Docs/issues/2450.

**Comment by xuejmnet** [comment]
[sharding-core](https://github.com/xuejmnet/sharding-core) it's my lib for sharding table and sharding database for efcore 2+ like sharding-jdbc
