### ISSUE TITLE
Null reference exception on DataTable.Load(IDataReader)

### ISSUE THREAD

**Issue by m0glan** [dotnet/efcore#22756]
I get a null reference exception occasionally when executing the following code:

```csharp
private IEnumerable<T> ReadDomainObjects(IDataReader dataReader)
{
    lock (lockObject_)
    {
        var domainObjects = new List<T>();

        var dataTable = new DataTable();
        dataTable.Load(dataReader);    // exception occurs here

        foreach (var row in dataTable.Rows.Cast<DataRow>())
        {
            T domainObject = mapper_.Map(row);
            domainObjects.Add(domainObject);
        }

        return domainObjects;
    }
}
```

This code is maybe called by multiple threads. I tried to add a lock but not sure how effective is (not very it seems, if it's a multi-threading issue). Most info I could find about this is in [#20651](https://github.com/dotnet/efcore/issues/20651), but still I'm not sure what I'm doing wrong. 

Here's the stack trace:

```
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
```

System info:
- Microsoft.Data.Sqlite.Core 3.1.6
- SQLitePCLRaw.lib.e_sqlcipher 2.0.2
- .NET Framework 4.6.2
- Windows 10 x86_64

**Comment by bricelam** [comment]
@vmoglan Could you provide a project that reproduces the exception so we can investigate?

**Comment by vmoglan** [comment]
@bricelam I couldn't reproduce this exception in a smaller project; even in the real project this does not occur every time, so there is no way to know. I'll investigate this further and let you know if I find out anything. 

[SqliteParallelDataTableLoad.zip](https://github.com/dotnet/efcore/files/5297361/SqliteParallelDataTableLoad.zip)

**Comment by bricelam** [comment]
I suspect this is the same multi-threaded issue you mentioned. Ensure there is one connection per thread.
