### ISSUE TITLE
Can "Shared columns" be used for properties which are modelled as foreign keys?

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#22757]
Can "Shared columns" be used for properties which are modelled as foreign keys?

Regarding "Shared columns" I mean what is described here: https://docs.microsoft.com/en-us/ef/core/modeling/inheritance

Example:

- Concrete class `Person`
- Abstract class `Mammal`, concrete sub-classes `Dog` and `Cat`.
- Person has two `ICollection` properties: `Dogs` and `Cats`, obviously of type `Dog` and `Cat`.
- Both `Dog` and `Cat` have a property `PersonID` which is mapped as a foreign key to `Person` and property `Person` of type `Person`.

Let's not discuss, that the relationship should be between `Mammal` and `Person`, because in my real case this is not feasible.

My question is, can the `Dog`'s `PersonID` as well as the `Cat`'s `PersonID` both specify `.HasColumnName("PersonID")` and hereby benefit from Shared Columns or it's not feasible as they are foreign keys and instead I must have separate Dog_PersonID and Cat_PersonID columns?

In my opinion, the documentation at https://docs.microsoft.com/en-us/ef/core/modeling/inheritance should make it explicit, whether the feature "Shared Columns" can also be used for foreign keys.

EF Core version: .NET 5.0 RC1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 5.0 RC1
Operating system: Windows 10 Professional
IDE: Visual Studio 2019 16.8.0 Preview 3.1

**Comment by ajcvickers** [comment]
@henrikdahl8240 Yes, this should work. Have you tried it?

**Comment by henrikdahl8240** [comment]
@ajcvickers No, but this I will do now. I thought it could be, that Person's Dogs and Cats would not give the right result as this requires usage of the Discriminator column of Mammal, which is obviously not necessary if Cat and Dog had their own separate foreign keys.
I thought you would respond, that it doesn't work with foreign keys du to this detail.
