### ISSUE TITLE
Dependency tracking in App Insights not working above version 3.1.3 on Azure Functions

### ISSUE THREAD

**Issue by pcsikos** [dotnet/efcore#22759]
After upgrading Microsoft.EntityFrameworkCore dependency to 3.1.4 or higher on an Azure Function application, the SqlDependency tracking in Application Insights stopped working.

You can reproduce the issue in [repo](https://github.com/pcsikos/AzureFunctionsBrokenSqlDependency/tree/master)

After deploying the application to Azure(without EF), SQL dependencies in Application Insights are tracked as expected. (master branch from my repo)

However, after adding a Microsoft.EntityFrameworkCore reference to the project and nothing else is changed, the tracking stops working (efcore3-1-8 branch). After removing the reference tracking is working again. Any version above 3.1.3 used, does not have working sql dependency tracking. You can check the other scenarios in my repo as well.

I hope I provided enough information to reproduce the issue.

**Comment by ajcvickers** [comment]
@pcsikos See https://github.com/dotnet/SqlClient/issues/678
