### ISSUE TITLE
Is migrations on Azure with managed identity (AccessToken) not supported?

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22772]
Moved from discussion #21879

### Question

From @andrejohansson

My app is running on an Azure app service. It´s using managed identity.

I retrieve my context and set the accesstoken on the sql connection like this in my DI configuration for AddDbContext:

```C#
               var tokenProvider = new AzureServiceTokenProvider();
                var accessToken = tokenProvider
                    .GetAccessTokenAsync("https://database.windows.net/", this.dbTenantId)
                    .Result;
               sqlConnection.AccessToken = accessToken;
```

This works fine for running the app and connecting to the db. It gets an access token and retrieves data from the db.

But when I added migrations to my project, and want´s to run them on startup like this:

```C#
        private void MigrateDatabase()
        {
            using (AsyncScopedLifestyle.BeginScope(this.container))
            {
                var logger = this.container.GetInstance<ILogger<Startup>>();
                logger.LogInformation("Database: Starting database migration...");
                var db = this.container.GetInstance<BokaMeraContext>();
                db.Database.Migrate();
                logger.LogInformation("Database: Migrations, done.");
            }
        }
```

I get an exception that

```
Microsoft.Data.SqlClient.SqlException | Login failed for user ''.
```

So, I'm wondering. Is the migration process creating it´s own sql connections (which then wont get the token)?

Can I somehow make migrations work on Azure using Managed Identity?

---

### Replies

From @ErikEJ

Maybe initialize the migration context with a SqlConnection with the AccessToken?

---

From @andrejohansson

It´s already doing that. When `GetInstance<BokaMeraContext>()` is run in MigrateDatabse then the factory code I posted above is run. So it should have a token.

---

From @ajcvickers

@andreasbotsikas Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by andreasbotsikas** [comment]
I am not sure how my name appeared on this one (probably wrong reference). I had a similar experience when we were running highly optimized code in Container Instances, where our code was running before the [IMDS service](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#managed-identity) being fully loaded, something that was changed in 2021.
