### ISSUE TITLE
Microsoft.EntityFrameworkCore.EntityTypeExtensions.GetDeclaredNavigations() not return many to many navigations

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#22795]
`// EntityFrameworkCore 5.0.0-rc1.20451.13

namespace CoreTests
{
    public class Person
    {
        public Guid ID { get; set; }
        public string Surname { get; set; }

        public virtual ICollection<House> Houses { get; set; }

        public virtual ICollection<Addres> Addreses { get; set; }

        public bool Is { get; set; }
    }

    public class House
    {
        public Guid ID { get; set; }
        public virtual ICollection<Person> Owners { get; set; }
        public string Address { get; set; }
    }

    public class Addres
    {
        public virtual Person PersonProperty { get; set; }
        public Guid ID { get; set; }
        public string Street { get; set; }
    }

    public class TestContext : Microsoft.EntityFrameworkCore.DbContext
    {

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseInMemoryDatabase("Test");
            
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Person>().HasKey(itm => itm.ID);
            modelBuilder.Entity<Person>().HasMany(itm => itm.Addreses).WithOne(itm => itm.PersonProperty);
            modelBuilder.Entity<Person>().Ignore(itm=>itm.Is);
            modelBuilder.Entity<Person>().HasMany(itm => itm.Houses).WithMany(itm=>itm.Owners);
            modelBuilder.Entity<House>().HasKey(itm => itm.ID);
        }
    }

}``

Microsoft.EntityFrameworkCore.EntityTypeExtensions.GetDeclaredNavigations(NotNullAttribute] this IEntityType entityType) 
on PersonEntityType not return the may to many navigation(Houses). All many to many navigations for any IEntityType in the model are not returned.

**Comment by ErikEJ** [comment]
Maybe use GetSkipNavigations?

**Comment by GLuca74** [comment]
@ErikEJ Many thanks i get the many to many navigations with this. Can u kind tell me where i can read more in deep wath a skip navigation is in the EF Core view? Many thanks

**Comment by ErikEJ** [comment]
I think the docs for EF Core 5 are not completely ready yet, given that EF Core 5 will not release until November 10.

**Comment by GLuca74** [comment]
OK, Many thanks
