### ISSUE TITLE
[Question] Mixed TPT+TPH (a.k.a. hybrid inheritance mapping)

### ISSUE THREAD

**Issue by MaximS** [dotnet/efcore#22796]
Is it possible to mix TPT and TPH mappings in EF Core .NET 5.0 (RC1)?

Suppose I have the following model (eg. for ecommerce):
```C#
Product  // Id, Name
    PhysicalProduct // Weight
    DownloadableProduct // Size in bytes
        EBook // Page count
        Movie // Genre
```
Now I would like to map this hierarchy to 3 tables: 
- PRODUCT - for Id and Name properties, 
- PRODUCT_PHYSICAL - for its Weight and inventory data
- PRODUCT_DOWNLOADABLE - for the entire DownloadableProduct branch differentiated by a discriminator

Is it planned for FE Core .NET 5.0? Or may be there is a way to configure this mapping in the current or daily EF Core version?

Now I get an error trying to implement it.

Entities (toy model):
```C#
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class PhysicalProduct : Product
    {
        public int Weight { get; set; }
        public int InStock { get; set; }
    }

    public class DownloadableProduct : Product
    {
        public int LengthInBytes { get; set; }
        public string MimeFormat { get; set; }
    }

    public class EBook : DownloadableProduct
    {
        public int PageCount { get; set; }
    }

    public class Movie : DownloadableProduct
    {
        public string Genre { get; set; }
    }
```
Mapping:
```C#
    {
            modelBuilder.Entity<Product>()
                .ToTable("PRODUCT")
                .HasKey(p => p.Id);

            modelBuilder.Entity<PhysicalProduct>()
                .ToTable("PRODUCT_PHYSICAL");

            modelBuilder.Entity<DownloadableProduct>()
                .ToTable("PRODUCT_DOWNLOADABLE");

            modelBuilder.Entity<DownloadableProduct>()
                .HasDiscriminator<string>("DL_PROD_TYPE")
                .HasValue<EBook>("ebook")
                .HasValue<Movie>("movie");
    }
```
Error message on `dotnet ef migrations add Init`
```
'DownloadableProduct' is mapped to the table 'PRODUCT_DOWNLOADABLE' while 'Product' is mapped to the table 'PRODUCT'. Map all the entity types in the hierarchy to the same table or remove the discriminator and map all of them to different tables. See https://go.microsoft.com/fwlink/?linkid=2130430 for more information.
```

EF6 seems to [support such mappings](https://stackoverflow.com/questions/27146490/how-can-i-mix-tph-and-tpt-in-entity-framework-6) as well as (N)Hibernate.

EF Core version: 5.0.100-rc.1.20452.10
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: (e.g. .NET 5.0)
Operating system: Linux Mint 20
IDE: VSCode 1.49.1

**Comment by ajcvickers** [comment]
@MaximS We don't currently have any plans to support hybrid inheritance mapping in EF Core.

**Comment by momt99** [comment]
Any update on plans to support this feature?
Also is there any workaround?
