### ISSUE TITLE
DBContext with ServiceLifetime.Transient and NavigationProperty.Load()

### ISSUE THREAD

**Issue by NormanGiHu** [dotnet/efcore#22790]
Hello,
I'm testing a ViewModel (which gets the DBContext via Constructor Injection) for a WPF Application with xUnit.
The DataContext is for testing configured as follows

```C#
services.AddDbContext<MyDataContext>(options => options
        .EnableSensitiveDataLogging()
        .UseLazyLoadingProxies()
        .UseSqlServer(configuration.GetConnectionString("SqlConnection")), `ServiceLifetime.Transient);
```

The xUnit TestClass has several Testmethodes.
Every TestMethod uses an Instance of the ViewModel.
When executing Tests only the ViewModel in the first executed TestMethod has a fully populated DBContext Instance.

The DBContexts of the ViewModels in the following TestMethods have their NavigationProperties not tracked anymore.
Why is it so? And how can i solve the Problem?

For this Code:

```C#
MyDataContext .Entry(MyModel) .Collection(bi => bi.MyModelNavigationProperty) .Load();
```

I get in later TestMethods

> System.InvalidOperationException : Navigation property 'MyModelNavigationProperty' on entity of type 'MyModel' cannot be loaded because the entity is not being tracked. Navigation properties can only be loaded for tracked entities.

BR,
Norman

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 Preview

**Comment by ajcvickers** [comment]
@NormanGiHu There isn't enough here to be able to understand how EF is being used in these tests. Please attach a small project that runs tests in the way you are attempting so that we can investigate.

**Comment by NormanGiHu** [comment]
Hello,
problem solved. When creating a small example project it became clear that the problem was not within ef core.

It were the child-viewmodels in the following tests, which sent their "dbset"- model to the "wrong" parent viewmodel instance (which had another dbcontext instance).

So all childviewmodels from different test methodes sent their data to the parent viewmodel in the first test method and not to the parent view model of their testmethod.

thank you for your patience ;)
