### ISSUE TITLE
Timing of EF Core 5 for UWP ???

### ISSUE THREAD

**Issue by dan-meier** [dotnet/efcore#22799]
Looking for more information on the timing of EF Core 5 support for UWP.

The "[Supported .NET implementations](https://docs.microsoft.com/en-us/ef/core/platforms/)" page simply lists "TBD".  Other resources suggest it might be over a year out, in late 2021 before UWP is compatible with .NET Standard 2.1 (a pre-requisite for EF Core 5).  Some resources suggest even later -- after .NET 6 is released -- since there's apparently some concern over [UWP's compatibility with .NET 5](https://github.com/dotnet/standard/issues/1567#issuecomment-600513715).

The question of [UWP compatibility with .NET Standard 2.1](https://github.com/dotnet/standard/issues/1567) was raised over a year ago, with some handwaiving in the ensuing months, but nothing resembling a plan, despite a [December 2019 comment](https://github.com/dotnet/standard/issues/1567#issuecomment-566862284), "_We'll have more to share when we get through our planning process_".

Needless to say, the mixed messages are confusing, and the lack of "official" information makes planning difficult.

Can someone provide an update on the timing of EF Core 5 support for UWP?  Even if it's a "spit-ball" estimate...even if it's "disappointing news", it'll be helpful information for your customer developer community.  It'd be terrific, too, if an estimate could be followed up with periodic updates to let the customer developer community know if anything has changed from the original estimate.  Thanks!

**Comment by emiliano84** [comment]
+1 for this

**Comment by ajcvickers** [comment]
@dan-meier We're holding off on UWP work while we see where things evolve with [Project Reunion](https://github.com/microsoft/ProjectReunion). In general the experience with EF Core and UWP is not very good. We hope that in the future we'll be able to create and document a great experience as the U.I. platform evolves.

**Comment by dan-meier** [comment]
@ajcvickers  Thanks for your reply.  Any chance that "see where things evolve" might mean "not going to work on it"?  And what kind of time-frame would you guesstimate for "in the future"?  Months?  Quarters?  Years?

In the mean time, can you suggest alternatives for accessing EF Core 5 capabilities "indirectly" from UWP?

I created a library using the EF Core 5 RC and, safely encapsulating all the new EF Core 5 goodies outside the UWP project, naively assumed I could plug the library into my UWP project since the library was only returning POCOs.  But UWP's lack of compatibility with .NET Standard 2.1 blew things up right away.  (I should've read the fine print first!)

After experiencing the simplicity of how EF Core 5 handles many-to-many relationships, it's REALLY hard to go back!

**Comment by ajcvickers** [comment]
@dan-meier We're committed to making EF Core work well with all popular .NET U.I. frameworks in the long term. However, EF Core 5.0 is done; we're not planning any additional work for UWP or anything else in 5.0. We will continue to follow developments as we work on EF Core 6.0. I can't predict what will happen elsewhere, but it seems to me from current information that we should be able to get this working for .NET 6.

That doesn't mean that it won't work with EF Core 5.0 before then since EF Core targets .NET Standard 2.1, so If UWP is made to work correctly against this, then EF Core will likely work.

Unfortunately, I don't know enough about UWP to suggest alternatives.

**Comment by dan-meier** [comment]
@ajcvickers  I appreciate your candid comments.  Many moving parts!  Though not the ideal situation, your feedback will help those of us in the customer developer community plan better.   Thanks!

**Comment by pubtom** [comment]
If you need .NET>5 in UWP please give a vote on this: https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483
