### ISSUE TITLE
example of Many-to-many is incomplete

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#22807]
## Ask a question
The example of the many-to-many [here ](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew) which shows the customization of the join table is not showing the actual .net POCO models (Community, Person, and especially PersonCommunity). 
Can you please share them?

Thanks

EF Core version: EF Core 5 RC1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win10
IDE: Visual Studio 2019 16.7.4

**Comment by ajcvickers** [comment]
This will be covered by https://github.com/dotnet/EntityFramework.Docs/issues/1978
