### ISSUE TITLE
Missing Reload() for Entry or complete Context.DbSet

### ISSUE THREAD

**Issue by Nebelkraehe** [dotnet/efcore#2280]
Hello.

After building an SQLite example for multiuser environment I ran into a problem regarding reloading changed rows.

I started two instances of my example program and added a new row in one instance. Refreshing inside the other instance worked well. Same behavior for deleting a row.

**Problem:**
Editing and saving a row did work inside one instance. Refreshing inside the second instance did not change anything.
The only way to get it to work is to dispose the current context and reinstanciate it.

Is there any way to reload the context (to fetch all changes from the database - not only the deleted and added rows) without instanciating it new?

Thanks.

Nebelkraehe

**Comment by makcakaya** [comment]
I have experienced the same behaviour with the earlier versions too. I think this is not something to be changed/fixed as DbContext is designed to be used as a Unit of Work.

I solved the issue by creating short-lived contexts. Create a context, do your operations, and get rid of it.

**Comment by Nebelkraehe** [comment]
> Create a context, do your operations, and get rid of it.

That´s also the way I design it. 
In my case it´s a screen including a few data rows to check. After loading and visualizing it - the user checks it - finds something to edit (perhaps something another user already did) and saves it - but before the final change saving, I´d like to query - through the current context - if something in the related database table changed. 
This would be the timespan/operation scope where I´d keep the context alive.

Otherwise it would be:
- Create context
- load needed data and visualize it
- dispose context
- edit data
- recreate context
- load needed data to compare it for changes
- save changes to the database
- dispose context

If I take the time for the first, its a bit faster than the second with additional context creation.

**Comment by rowanmiller** [comment]
There are a couple of requests here:
* Agreed that we need Reload etc. on EntityEntry. Opening an all up issue to track this (and other) missing APIs https://github.com/aspnet/EntityFramework/issues/2295.
* Also opening an issue to track the ability to refresh based on a query https://github.com/aspnet/EntityFramework/issues/2296.

You are correct that at the moment there is no easy way to do this. A new context instance is the best option.
