### ISSUE TITLE
Automatic by convention mapping coupled with Owned entities

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22814]
Moved from discussion #22015.

### Question

From @AndersMalmgren

We are on ef core 3.1.6. We have two special interfaces for our Entities.

_ICreated_ and _IUpdated_

From the DB context we automatically add the config for these using
```csharp
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.ApplyConfigurationsFromAssembly(typeof(ICreated).Assembly);

    builder
        .Model
        .GetEntityTypes()
        .Where(et => typeof(IUpdated).IsAssignableFrom(et.ClrType))
        .ForEach(et => builder.Entity(et.ClrType).Property(nameof(IUpdated.UpdatedUTC)).IsConcurrencyToken());

    builder
        .Model
        .GetEntityTypes()
        .Where(et => typeof(ICreated).IsAssignableFrom(et.ClrType))
        .ForEach(et =>
        {
            var entity = builder
                .Entity(et.ClrType);

            entity
                .Property(nameof(ICreated.CreatedUTC))
                .IsRequired();

            entity.Property(nameof(ICreated.CreatedBy))
                .IsRequired();
        })
}
```

This have worked very well up to this point. But now we wanted to add a _ICreated_ entity as a owned entity doing

```csharp
builder.OwnsOne(p => p.PayerInfo, b =>
{
    b.WithOwner().HasForeignKey(p => p.PaymentTransactionId);
    b.ToTable("PaymentTransactionPayerInfo", "dbo");
});
```

This works if we do not add the _ICreated_ interface. If we add the interface to the entity it will crash on this line _builder.Entity(et.ClrType)_ With the exception

> The type 'PaymentTransactionPayerInfo' cannot be configured as non-owned because an owned entity type with the same name already exists

So for these i instead need to use the _OwnedNavigationBuildersomehow_. Ideas? Thanks

---

### Replies

From @AndersMalmgren This is using Internal API, so it won't work in 5.0, but should get you unblocked:

```C#
var ownership = et.FindOwnership();
if (ownership != null)
{
    var ownershipBuilder = new OwnedNavigationBuilder(
        (EntityType)ownership.PrincipalEntityType,
        (EntityType)ownership.DeclaringEntityType,
        (InternalRelationshipBuilder)((IConventionForeignKey)ownership).Builder);

    ownershipBuilder
        .Property(nameof(ICreated.CreatedUTC))
        .IsRequired();

    ownershipBuilder
        .Property(nameof(ICreated.CreatedBy))
        .IsRequired();
}
```

**Comment by AndersMalmgren** [comment]
I went with the none fluent version that does not use internal stuff. Though why not use internal keyword on internal stuff? :P
