### ISSUE TITLE
How check if an IEntityType is an EntityType created for a many to many relation

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22818]
Moved from discussion #22797.

From @GLuca74

//EntityFrameworkCore 5.0.0-rc1.20451.13

How is te best way to check if and IEntityType, got from DbContext.Model.GetEntityTypes(), is an EntityType internally created for a many to many relation?

I found EntityType.IsImplicitlyCreatedJoinEntityType, is there a best way instead of cast the interface type to this concrete type?

Many thanks

**Comment by ajcvickers** [comment]
@GLuca74 There isn't inherently anything about these entity types that could not also be applied to other entity types. What are you planning to do with this info?

**Comment by GLuca74** [comment]
Hello @ajcvickers , I have an utility that accepts an external DbContext that say the queryable entities.
Theese autogenerate entity types seems not queryable so i have two choices :

1. Exclude this entity types, then i need a way to recognize them
2. There is a way to query theese entity types with somethig similary how the shadow propertyes are queryable.

If possibile, I would prefer the second option

**Comment by smitpatel** [comment]
They are shared type entity type. You need to use `Set<T>` method on DbContext which also takes the string argument and pass the name of the entity type there. You can check shared type entity type by using `IEntityType.HasSharedClrType`

**Comment by GLuca74** [comment]
Thanks @smitpatel and sorry for the delay, many thanks, you pointed me to study shared types also.
I hope my problem will not became distinguish a shared type from an autogenerate shared type :), I will see in the near future

Thanks for all
