### ISSUE TITLE
Get custom values from sql query

### ISSUE THREAD

**Issue by makemefeelgr8** [dotnet/efcore#22811]
Lets say there is a super complicated sql query. It may include views, triggers, stored procedures and whatnot.
I'll use this one as an example:
`select A from B`
It turns out there is absolutely no way to read the data it returns with entity framework core! If you want to select a custom value from the db, your best bet would be to remove ef core and install something that actually works.
This is as close as it gets:
`context.MANDATORY_MODEL_NAME.FromSqlRaw("select A from B")`
But in case your model is a custom one (not a table), you're doomed.
So, this is a problem I'm trying to solve.

Any other db management solution had this feature available since version 1.
EF6:
`ctx.Database.SqlQuery<model>("select A from B")`
Dapper, linq2sql, the list goes on and on.
Even php:
`$result = mysqli_query($db, 'select A from B');`

I'm so frustrated. It's just ridiculous! I can't believe entity framework core got to version 3 and it still lacks the very most basic features like the one I've mentioned! 
Don't you guys have stored procedures?

Anyway, I am removing ef core right now. I'll install another db management solution that can actually get data from raw queries.

Best wishes, I hope you'll make ef core actually usable one day.

**Comment by ErikEJ** [comment]
Hope you left this message to get a positive response?

In any case, EF Core Power Tools can map stored procedures for you:
https://erikej.github.io/efcore/2020/08/10/ef-core-power-tools-stored-procedures.html

and you can use this to query into arbitrary classes:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/DbContextExtensions

**Comment by makemefeelgr8** [comment]
> Hope you left this message to get a positive response?

Yeah, I'm sorry if I sounded rude. I've just wanted to check if there is actually a way to do that.

> and you can use this to query into arbitrary classes:
That one looks promissing. It creates a new context per each query, though, so this is a no-go for me. I really wish guys who work on EF Core to listen to me and to actually add this feature. How hard can it be to execute a raw query (already implemented) and get some results (already implemented as well)?

**Comment by ajcvickers** [comment]
Tracked by #10753 and #11624

**Comment by makemefeelgr8** [comment]
These issues have been open for 2 years(!!) already. Countless duplicates were created since then and still noone have even started coding!
_I wonder what's more important- implementing webassembly support noone needs, or improving the default db management solution everyone use. Can I talk to a manager?_
