### ISSUE TITLE
Why EF Core doesn't honor ToTable() when creating database?

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22819]
Moved from discussion #22798.

### Question

From @SayusiAndo

In my project I have a few tables and all of them has the name I setup with builder.ToTable("some_table_name"). There is one entity where EF Core uses the class name. I can't figure out why. I double checked everything multiple times, the configuration doesn't differ from other entities' configuration.

Under what circumstances EF Core uses classname instead of the provided table name?
The database is SQLite, and the string I'd like to use is dimensionstructure_node. I have way longer table name than this.

Thank you!

---

### Replies

From @ErikEJ

Have you checked your migrations?

---

From @SayusiAndo

No migrations.

The funny thing is that if the class name is changed then the table name follows it. I'm just scratching my head here.

**Comment by ajcvickers** [comment]
@SayusiAndo Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by SayusiAndo** [comment]
@ajcvickers thanks for your reply. I need a few days.

**Comment by SayusiAndo** [comment]
I found the issue. I forgot to apply entity configuration. User error, that what we had here.
