### ISSUE TITLE
Examples use wrong overload.

### ISSUE THREAD

**Issue by GeroIwan** [dotnet/efcore#22840]
All examples for the `AddDbContext<TContextService,TContextImplementation>` overloads show code using an `AddDbContext<TContext>` overload but no `AddDbContext<TContextService,TContextImplementation>` overload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e7cd4d-906b-7749-ef0d-9792569e4b90
* Version Independent ID: 29db4d36-3ab7-3eb9-ddb2-e5799f1f239a
* Content: [EntityFrameworkServiceCollectionExtensions.AddDbContext Method (Microsoft.Extensions.DependencyInjection)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext?view=efcore-3.1&source=docs)
* Content Source: [dotnet/xml/Microsoft.Extensions.DependencyInjection/EntityFrameworkServiceCollectionExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.Extensions.DependencyInjection/EntityFrameworkServiceCollectionExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
All code examples for this class has been removed in https://github.com/dotnet/efcore/pull/21031

**Comment by ajcvickers** [comment]
Covered by #17508
