### ISSUE TITLE
Cannot create a non generated integer primary key

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/efcore#2284]
The code below will fail with an exception "System.InvalidOperationException: The property 'Id' on entity type 'Parent' does not have value generation on add enabled and it is principal by at least one foreign key. Properties 
referenced by foreign keys should have value generation on add enabled."

Replacing `int` with `string` will effectively achieve the result so why is there such a limitation for ints?

```
public class Parent
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ParentId { get; set; }

    public Parent Parent { get; set; }
}

public class Context: DbContext
{
    public Context()
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<Parent>(b =>
        {
            b.Key(x => x.Id);
            b.Property(x => x.Id).GenerateValueOnAdd(false);
        });
    }

    public DbSet<Parent> Parents { get; set; }
    public DbSet<Child> Children { get; set; }
}
```

**Comment by rowanmiller** [comment]
Hey,

You don't really want to ever turn off `GenerateValueOnAdd` (it's how EF generates placeholder keys if you don't have one assigned), we are revisiting the whole design/API for value generation because it is not very friendly/intuitive at the moment.

In the meantime... this is probably the code you are after...

```csharp
b.Property(x => x.Id).ForSqlServer().UseNoValueGeneration();
```

~Rowan

**Comment by MaximBalaganskiy** [comment]
The suggested code results in the same exception

**Comment by rowanmiller** [comment]
@MaximBalaganskiy can you share the complete code for us to reproduce the issue? That way we can work out what is going on.

**Comment by MaximBalaganskiy** [comment]
Put the source code archive to my dropbox
https://www.dropbox.com/s/r7uugi06mmstfx7/Issue2284.zip?dl=0

**Comment by c1rus** [comment]
i ran into same issue.
