### ISSUE TITLE
SavingChanges in EF Core 5.0 thrown System.NotSupportedException:

### ISSUE THREAD

**Issue by alraseen** [dotnet/efcore#22841]
After I upgraded form ef core 3.1 to ef core 5.0.0-rc , I got a **System.NotSupportedException:** 'This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.'. it happened when I save changes after removing an entity

**Comment by ajcvickers** [comment]
@loveprogrammin Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by loveprogrammin** [comment]
this is the classes

    public class Level : BindableBase
    {

        public Account()
        {
            LevelOne = new ObservableCollection<LevelOne>();
        }
        
        public Guid Guid { get; set; }

        private int code;
        public int Code
        {
            get { return code; }
            set { SetProperty(ref code, value); }
        }
        private string name;
        public string Name
        {
            get { return name; }
            set { SetProperty(ref name, value); }
        }

        private ObservableCollection<LevelOne> levelOne;
        public ObservableCollection<LevelOne> LevelOne
        { 
            get { return levelOne; }
            set { SetProperty(ref levelOne, value); }
        }
    }

and the second class 

     public class LevelOne :BindableBase
     {

        public LevelOne()
        {
            LevelTwo = new ObservableCollection<LevelTwo>();
        }
        public Guid Guid { get; set; }
        public Guid LevelId { get; set;}
        private int code;
        public int Code
        {
            get { return code; }
            set { SetProperty(ref code, value); }
        }
        private string name;
        public string Name
        {
            get { return name; }
            set { SetProperty(ref name, value); }
        }

        public Level Level { get; set; }

        private ObservableCollection<LevelTwo> levelTwo;
        public ObservableCollection<LevelTwo> LevelTwo
        {
            get { return levelTwo; }
            set { SetProperty(ref levelTwo, value); }
        }
    }

and the DbContext

    public class AppsContext : DbContext
    {
        public DbSet<Level> Levels { get; set; }

        public DbSet<LevelOne> LevelOnes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Initial Catalog=TestDB;Trusted_Connection=true;Server=(localDB)\\MSSQLLocalDB");
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
           modelBuilder.ApplyConfiguration(new LevelConfiguration());
            modelBuilder.ApplyConfiguration(new LevelOneConfiguration());
        }
    }

and the LevelConfiguration is 

    public class LevelConfiguration : IEntityTypeConfiguration<Level>
    {

        public void Configure(EntityTypeBuilder<Level> builder)
        {
            builder.ToTable("Level");
            builder.HasKey(s => s.Guid);
            builder.HasIndex(s => s.Code).IsUnique();
            builder.HasIndex(e => e.Name).IsUnique();
            builder.Property(e => e.Name).IsRequired();
        }
    }

and the LevelOneConfiguration is 

    public class LevelOneConfiguration : IEntityTypeConfiguration<LevelOne>
    {
        public void Configure(EntityTypeBuilder<LevelOne> builder)
        {
            builder.ToTable("LevelOne");
            builder.HasKey(e => e.Guid);

            builder.HasIndex(e => e.Code).IsUnique();

            builder.HasIndex(e => e.Name).IsUnique();

            builder.Property(e => e.Name).IsRequired();

            builder.HasOne(d => d.Level)
                .WithMany(p => p.LevelOne)
                .HasForeignKey(d => d.LevelId)
                .OnDelete(DeleteBehavior.Restrict)
                ; 
        }
    }
  
I hope that will help

**Comment by ajcvickers** [comment]
@loveprogrammin I don't think the issue is related to your EF configuration or model. I don't think there will be much we can do without the executable code that sets up the the appropriate situation to generates the exception.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is still lacking enough information for us to be able to effectively triage it. Once you provide a small, runnable project or post a small, runnable code listing that reproduces what you are seeing we can investigate and reopen this issue.

**Comment by loveprogrammin** [comment]
this is a runnable project [https://1drv.ms/u/s!ApQ9UD_gEQ2qgbEjko4z-HIvUkWaiQ?e=ulXh0y](url)

Make sure before you run the application uncomment the line in LoadAsync() method in MainWindowViewModel to add the data to  the Database. After that run the app and try to remove last subchild in the treeview using the contextMenu

**Comment by ajcvickers** [comment]
@dotnet/efteam This requires Windows to repro. Can somebody try?

**Comment by AndriySvyryd** [comment]
This is a consequence of https://github.com/dotnet/efcore/issues/10164

@loveprogrammin Change the `SaveChangesAsync()` method to this:

```C#
public async Task SaveChangesAsync()
{            
    await context.SaveChangesAsync(acceptAllChangesOnSuccess: false);
    context.ChangeTracker.AcceptAllChanges();
}
```

This will make EF modify the model collections on the current (Dispatcher) thread.

**Comment by loveprogrammin** [comment]
> This is a consequence of #10164
> 
> @loveprogrammin Change the `SaveChangesAsync()` method to this:
> 
> ```cs
> public async Task SaveChangesAsync()
> {            
>     await context.SaveChangesAsync(acceptAllChangesOnSuccess: false);
>     context.ChangeTracker.AcceptAllChanges();
> }
> ```
> 
> This will make EF modify the model collections on the current (Dispatcher) thread.

Thanks it's work 😀

**Comment by ajcvickers** [comment]
@AndriySvyryd reopened to discuss if we should add additional documentation here.

**Comment by AndriySvyryd** [comment]
Yes, we should add a note to the WPF tutorial

**Comment by loveprogrammin** [comment]
I think removing entity is another problem 
In same project when I try to remove parent item, it throws exception and that's ok because the required relationship. Thus,  removing the last-Child item of tree will remove it with the parent even if parent has other children.

**Comment by roji** [comment]
We should also add some documentation to our [async programming page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/async) (I can do that).

**Comment by loveprogrammin** [comment]
I not sure if this going to produce other problems but I reset the context before removing item and it works
`public void ResetContext()
        {
             context = new AppsContextFactory().CreateDbContext(null);
        }`

**Comment by AndriySvyryd** [comment]
Filed dotnet/EntityFramework.Docs#2801
