### ISSUE TITLE
Unable to compile 3.1 application in Azure Pipeline due to dotnet-ef migrations

### ISSUE THREAD

**Issue by TranSystemsGitHub** [dotnet/efcore#22859]
**Version Used**:  core 3.1, Azure Pipeline for Web App Service

**Steps to Reproduce**:

I created a pipeline with my codebase that was upgraded from core 2.2 to 3.1. (with ASPNETCORE_ENVIRONMENT=Staging, build configuration= release, BuildPlatform = x64) The pipeline has:
1. Use NuGet 5.x
2. Use .Net Core sdk 3.x
3. NuGet Restore
4. Then this command line script:

**dotnet build $(build.sourcesDirectory)\MyProject\MyProject.csproj -c:release**

**Expected Behavior**:   The project builds within ten minutes. I can run this exact command on my local machine and it takes four minutes.

**Actual Behavior**: The command hangs and the Pipeline forces the cancellation of the process after 1 hour.

**Comment by ajcvickers** [comment]
@TranSystemsGitHub By default, the `dotnet ef` tool builds the project before running the EF command. This should not be needed in a non-interactive environment where the build has just happened. You can used the `--no-build` option to prevent EF doing this build.  See https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#common-options for more info.

**Comment by TranSystemsGitHub** [comment]
Thank you , I did use --no-build to generate migrations and it works about 50% of the time. However, the pipeline still times out during the build (that we fixed by /p:WebPublishMethod=Package) every third or fourth time I run the pipeline. I do not change the code at all and then the fifth time it works. I think it might be a pipeline agent connectivity error. 

Do you know anything I can do besides making a private agent to make sure my agent returns after the build?

**Comment by ajcvickers** [comment]
@TranSystemsGitHub Sounds like you need to follow up with the Azure Pipelines team. @Pilchie Do you know where Azure Pipelines issues should be reported?

**Comment by Pilchie** [comment]
I would use the feedback reporting built into the "help" menu of the Azure Pipelines pages:

![image](https://user-images.githubusercontent.com/312835/94966262-d25d8980-04b1-11eb-8dc3-1982d4a3c56c.png)
