### ISSUE TITLE
EF navigational properties always present with includes? Even with lots and lots of .includes? 

### ISSUE THREAD

**Issue by dev-freeman** [dotnet/efcore#22856]
**Background**
We are using eager loading (lots of .includes) for our db queries. 
With this, we found from our error handling that at times **one of these db queries with many many .includes properties fails to populate an expected navigational property (performance of this query was good)**. This was occurring very rarely for a query that is run often, but we were seeing this happen at least once a day. 

We thought this might have been a race condition. However after doing work to ensure it could never be a race condition we were still seeing the issue. 

🎉 **We did fix it** 🎉  **By breaking the large query with many .includes into a few smaller queries and managing these navigational properties ourselves, we seemed to have stopped this issue from occurring again.**

**Question:**
Are y'all aware of any limitations with EF eager loading? 
Is it okay to eager load lots of data with a single EF query (lots and lots of .includes), or is it best practice to only use eager loading with small amounts of data and instead manage relational data ourselves (like we have done)?

I just want to make sure what we have done is the right approach and we should encourage this approach going forward? 

### provider and version information

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows

**Comment by ajcvickers** [comment]
@dev-freeman 

> Are y'all aware of any limitations with EF eager loading?

No functional limitations that would explain this behavior.

> Is it okay to eager load lots of data with a single EF query (lots and lots of .includes),

Best practice is usually to only eagerly load the related entities that are needed for the current unit-of-work. Pulling a large part of the database onto the client for every operation is not recommended. Using selected explicit loading can also be useful when loading a relationship has a lot of overhead and it is not usually used for the unit-of-work.

Note also that EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/).

**Comment by AndriySvyryd** [comment]
@dev-freeman In EF Core 3.0 some include issues were fixed by consolidating the queries, see https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#eager-loading-single-query
