### ISSUE TITLE
Select which entity constructor is used

### ISSUE THREAD

**Issue by plapinski-caplugs** [dotnet/efcore#22860]
I have an entity class with two constructors; one public for the application to use when creating a new one and one private for EF to use when fetching from the database.

The ID is a read-only GUID property that is generated in the public constructor and passed through the second constructor.

```cs
public class Customer
    {
        // Application Constructor
        public Customer(string firstName, string lastName)
        {
            Id = Guid.NewGuid();
            FirstName = firstName;
            LastName = lastName;
        }

        // EF Constructor
        private Customer(Guid id, string firstName, string lastName)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
        }

        public Guid Id { get; }
        public string FirstName { get; }
        public string LastName { get; }
    }
```

Entity Framework errors complaining that the ID's backing field is read-only. 

If I change the public constructor's parameter names so that they don't match the property name, EF will happily call the private constructor and not complain about the ID being read-only: `public Customer(string firstName1, string lastName)`

It seems that if EF thinks it can map all the non-ID properties its needs through the public constructor (either because they are not read-only or because they have matching parameters in the public constructor) and the public constructor doesn't take in any parameters EF doesn't know what to do with, it will insist on calling the public one and won't even try to call the private one.

Solutions: 

1. If there are multiple "valid" constructors but only one of them accepts the ID as a parameter (and the ID is read-only), EF should use that one

or

2. Provide some means of telling EF which constructor to use in the DbContext

**Comment by ajcvickers** [comment]
@plapinski-caplugs What version of EF Core are you using?

**Comment by plapinski-caplugs** [comment]
2.2.6

And it dawns on me now that I probably should have spun up a test project with 3.1 before posting this...

**Comment by plapinski-caplugs** [comment]
Seems like this behaves as expected in 3.1, so now there's egg on my face.

Please disregard.
