### ISSUE TITLE
The default value comparer should use IEquatable if the type implements it

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#22885]
Our logic for creating default value comparers [uses the IStructuralEquatable interface](https://github.com/dotnet/efcore/blob/main/src/EFCore/ChangeTracking/ValueComparer%60.cs#L98) if the type implements it. We should do the same for [IEquatable](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netcore-3.1), which is a standard way to implement equality.

It also has the advantage of being generic, and so doesn't box for value types.

**Comment by ajcvickers** [comment]
@roji This should be happening already through pattern matching. Did you find a non corner-case where it's not working?

**Comment by roji** [comment]
Indeed, I missed that reading the code. Thanks.
