### ISSUE TITLE
Many-to-Many collection is not listed by EntityEntry.Navigations or EntityEntry.Collections

### ISSUE THREAD

**Issue by atiyar** [dotnet/efcore#22882]
```c#
public class Movie 
{
    public int Id { get; set; }
    public string Title { get; set; }

    public IList<Genre> Genres { get; set; }
}

public class Genre 
{
    public int Id { get; set; }
    public string Name { get; set; }

    public IList<Movie> Movies { get; set; }
}
```
With the above models and the following code -
```c#
var movie = new Movie
{
    Id = 1,
    Title = "Alien"
    Genres = new List<Genre>
    {
	new Genre { Id = 7, Name = "Sci-Fi" },
	new Genre { Id = 12, Name = "Horror" }
    }
};

var entry = dbCtx.Entry(movie);
```
I can get `Genres` as a `CollectionEntry` if I try -
```c#
var navigation = entry.Navigation("Genres");
var collection = entry.Collection("Genres");
```
but I cannot find it in either of the following list -
```c# 
var navigationList = entry.Navigations.ToList();
var collectionList = entry.Collections.ToList();
```
I don't think it is expected/consistent behavior. 

### Include provider and version information

EF Core version: 5.0.0-rc.2.20475.6 (daily build)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0, .NET Core 3.1
IDE: Visual Studio 2019 16.7, Visual Studio 2019 16.8 Preview 3.2

**Comment by ajcvickers** [comment]
@atiyar This is fixed and should be in the [GA daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) later today. It would be great if you could verify it is fixed on your end.

**Comment by atiyar** [comment]
@ajcvickers Nope. Not working.

**Comment by atiyar** [comment]
@ajcvickers Sorry, my bad, didn't change the wildcard to "rtm" in package references. It  is fixed on my end  :)
