### ISSUE TITLE
Parameterize the single item case of Contains in 5.0?

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/efcore#22880]
I noticed that in 5.0 rc1, a single item Contains will use equals (=) instead of IN like in 3.1.x. 

`var offerIds = new[] {1};`

**3.1.x**

_IN_: `context.Offers.Where(o => offerIds.Contains(o.Id))`
_OUT_: `WHERE [o].[Id] IN (1)`

**5.0 rc1**

_IN_: `context.Offers.Where(o => offerIds.Contains(o.Id))`
_OUT_: `WHERE [o].[Id] = 1`

This is a really nice optimization in itself, I have some queries where 80-90% of the executions will have a single item in the list.

However, the parameter is still hardcoded in the query. 

Related to https://github.com/dotnet/efcore/issues/13617, **could we perhaps have EF Core automatically parameterize the value for this single-item optimization shown above**? (like it's done in this [extension](https://gist.githubusercontent.com/ErikEJ/6ab62e8b9c226ecacf02a5e5713ff7bd/raw/7b2689608b5769376bbc97981d89db1deea83a38/IQueryableExtensions.cs))

It would minimize the number of cached SQL plans, and also react to the `EnableSensitiveDataLogging()` setting - currently the value is visible in log files even if set to `false`.

**Comment by smitpatel** [comment]
This optimization happens in command generation. So regardless of number of items in the list, it will use same compiled query, just generate different command. If it is parameterized in advance then it would be a different compiled query. #13617 would fix this too directly.

**Comment by joakimriedel** [comment]
Aha, OK I see. I hoped it would be an easy fix for the single-item case. 

In the meantime, I'll try exploring the extension mentioned above since it will parameterize also the single item case. Thanks.
