### ISSUE TITLE
EF Core generating incorrect SQL WHERE clause when using user defined bool variables!

### ISSUE THREAD

**Issue by legendof-selda** [dotnet/efcore#22895]
## File a bug

EF Core is not translating LINQ statement to SQL statement properly!

### Include your code

1. This is my View Model:
```csharp
namespace ReservationBookingSystem.Model
{
    public partial class ViewCovidBooking
    {
        [Column("CB_ID")]
        public int CbId { get; set; }
        [Column("MEMBER_ID")]
        public int MemberId { get; set; }
        [Column("event_id")]
        public int EventId { get; set; }
        [Column(TypeName = "date")]
        public DateTime ServiceDate { get; set; }
        [StringLength(50)]
        public string RegiNo { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [Column("MemberFamilyLineID")]
        public int? MemberFamilyLineId { get; set; }
        [Required]
        [StringLength(150)]
        public string MemberName { get; set; }
        [Required]
        [StringLength(1)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BookedOn { get; set; }
    }
}
```

2. In DB Context:
```csharp
namespace ReservationBookingSystem.Data
{
    public partial class ChurchDataDbContext : DbContext
    {
        public ChurchDataDbContext()
        {
        }

        public ChurchDataDbContext(DbContextOptions<ChurchDataDbContext> options)
            : base(options)
        {
        }
        public virtual DbSet<ViewCovidBooking> ViewCovidBookings { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ViewCovidBooking>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("View_CovidBookings");

                entity.Property(e => e.MemberName).IsUnicode(false);

                entity.Property(e => e.RegiNo).IsUnicode(false);

                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.Status)
                    .IsUnicode(false)
                    .IsFixedLength();
            });
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

3. In my code, I am trying to find if there exists a record with the following conditions in my Where statement:
```csharp
            string b = booking.Mobile.Substring(booking.Mobile.Length - 9);
            var timeoutMins = DateTime.Now.AddMinutes(-15);
            bool auto = !int.TryParse(Configuration["ApplicationSettings:MinGapFromLastBooking"], out int MinGapFromLastBooking);
            if(auto)
                MinGapFromLastBooking = serviceSlots[selectedServiceSlot.Value].WaitPeriod;
            bool notMember = string.IsNullOrEmpty(booking.RegiNo);

            var exists = ChurchDataDbContext.ViewCovidBookings.Where(s => ((s.EventId == booking.EventId && auto) && (s.RegiNo == booking.RegiNo && !notMember) && ((s.Email == booking.Email || s.Mobile.EndsWith(b)) && notMember)) && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins)));
            var debug = await exists.CountAsync();
```

In my database rows does exist for the condition I have given, but the problem is that, when it converts it into an SQL statement this is what I get:
```
SELECT COUNT(*)
FROM [View_CovidBookings] AS [v]
WHERE CAST(0 AS bit) = CAST(1 AS bit)
```

i tried with different methods like `FirstOrDefault()`, `MAX()` and they all are generating the incorrect WHERE clause! 

I tried it this way as well `var exists = await ChurchDataDbContext.ViewCovidBookings.AsNoTracking().Where(s => ((s.EventId == booking.EventId && auto) && (s.RegiNo == booking.RegiNo && !notMember) && ((s.Email == booking.Email || s.Mobile.EndsWith(b)) && notMember)) && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins))).CountAsync();`, continuous, but it gives out the same output!

But, when I removed my bool variables from the LINQ query, the generated SQL statement was correct!
`var exists= await ChurchDataDbContext.ViewCovidBookings.AsNoTracking().Where(s => ((s.EventId == booking.EventId) && (s.RegiNo == booking.RegiNo) && ((s.Email == booking.Email || s.Mobile.EndsWith(b)))) && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins))).CountAsync();
`. This generated the correct SQL where clause!
```
SELECT COUNT(*)
FROM [View_CovidBookings] AS [v]
WHERE ((([v].[event_id] = @__booking_EventId_0) AND ([v].[RegiNo] = @__booking_RegiNo_1)) AND (([v].[Email] = @__booking_Email_2) OR ((@__b_3 = N'') OR ([v].[Mobile] IS NOT NULL AND (RIGHT([v].[Mobile], LEN(@__b_3)) = @__b_3))))) AND (([v].[Status] = 'B') OR (([v].[Status] = 'I') AND ([v].[BookedOn] >= @__timeoutMins_4)))
```
I think EF Core is not able to handle proper conversion when it comes to entering bool values! I even tried putting the bool variables, `auto`, `notMember` inside brackets `( )` but that didn't work either! Yes, I could just keep them inside `if` clauses, if I wanted to, but i wanted a single statement rather than doing that and theoretically shouldn't it work or am I missing something in how EF Core generates SQL statements? Let me know if you need more information!

### Include provider and version information

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 19041.508
IDE: Visual Studio 2019 16.7.5

**Comment by smitpatel** [comment]
The where clause is 
```
Where(s => ((s.EventId == booking.EventId && auto) && (s.RegiNo == booking.RegiNo && !notMember) && ((s.Email == booking.Email || s.Mobile.EndsWith(b)) && notMember)) && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins)));
```
If we remove parenthesis which are giving same priority to &&
```
s => s.EventId == booking.EventId
&& auto
&& s.RegiNo == booking.RegiNo
&& !notMember
&& (s.Email == booking.Email || s.Mobile.EndsWith(b))
&& notMember
&& (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins))
```
`!notMember && notMember` is always false, no matter value of notMember.
Seems like your predicate is always false hence generate SQL contains where clause which is always false.

**Comment by legendof-selda** [comment]
> The where clause is
> 
> ```
> Where(s => ((s.EventId == booking.EventId && auto) && (s.RegiNo == booking.RegiNo && !notMember) && ((s.Email == booking.Email || s.Mobile.EndsWith(b)) && notMember)) && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins)));
> ```
> 
> If we remove parenthesis which are giving same priority to &&
> 
> ```
> s => s.EventId == booking.EventId
> && auto
> && s.RegiNo == booking.RegiNo
> && !notMember
> && (s.Email == booking.Email || s.Mobile.EndsWith(b))
> && notMember
> && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins))
> ```
> 
> `!notMember && notMember` is always false, no matter value of notMember.
> Seems like your predicate is always false hence generate SQL contains where clause which is always false.

the use of `notMember`, `auto` is basically used to avoid if statements!
So the idea is instead of using
```
if(auto)
    exists = exists.Where(s=>s.EventId==booking.EventId);
if(notMember)
    exists = exists.Where(s=>s.Email == booking.Email || s.Mobile.EndsWith(b));
else
    exists = exists.Where(s=>s.RegiNo==booking.RegiNo);
```
the bool values inside the parenthesis allows us the same functionality given above! This allows me to create a single query rather than generating using if statements. Although I have no issues with this, I believe that both methods must be welcome!

**Comment by legendof-selda** [comment]
on thinking about this I am going to try using `notMember==false/true` instead of just keeping `notMember` inside the query. i think it might work then!

**Comment by legendof-selda** [comment]
> on thinking about this I am going to try using `notMember==false/true` instead of just keeping `notMember` inside the query. i think it might work then!

Nope! I tried with:
`var debug = await  ChurchDataDbContext.ViewCovidBookings.Where(s => ((s.EventId == booking.EventId && auto==true) && (s.RegiNo == booking.RegiNo && notMember==false) && ((s.Email == booking.Email || s.Mobile.EndsWith(b)) && notMember==true)) && (s.Status == "B" || (s.Status == "I" && s.BookedOn >= timeoutMins))).ToListAsync();
`
and still got the same result
```
SELECT [v].[BookedOn], [v].[CB_ID], [v].[Email], [v].[event_id], [v].[event_title], [v].[MemberFamilyLineID], [v].[MEMBER_ID], [v].[MemberName], [v].[Mobile], [v].[RegiNo], [v].[ServiceDate], [v].[Status]
FROM [View_CovidBookings] AS [v]
WHERE CAST(0 AS bit) = CAST(1 AS bit)
```

**Comment by smitpatel** [comment]
Your predicate is always false. You are combining them incorrectly. Both condition with flipped notMember should have `||` between them. Or rather write it the way you want to write outside.
```C#
exists = exists.Where(s=>auto ? s.EventId==booking.EventId : true);
exists = exists.Where(s=>notMember ? s.Email == booking.Email || s.Mobile.EndsWith(b) :s.RegiNo==booking.RegiNo );
```
