### ISSUE TITLE
Interception: raw query vs. LINQ

### ISSUE THREAD

**Issue by Timovzl** [dotnet/efcore#22899]
When detecting the execution of queries using interceptors or diagnostics listeners, is it possible to distinguish between a raw query (`ExecuteSqlRawAsync()`) vs. a regular LINQ one?

I'm thinking somewhat analog to `ChangeTracker.Tracked`, whose `EntityTrackedEventArgs` contains a `FromQuery` boolean indicating whether it was a query that caused the tracking.

I have looked at the events coming through the diagnostics listener. Initially it seemed I could distinguish LINQ queries by the presence of `Microsoft.EntityFrameworkCore.Query.QueryCompilationStarting` or `Microsoft.EntityFrameworkCore.Query.QueryExecutionPlanned`. Alas, these only seem to happen the first time a query is performed.

Why is it relevant to detect raw queries? Well, besides variants of `SaveChanges` (which can be easily intercepted), raw queries seem to be all that can have Entity Framework perform write operations (but correct me if I'm wrong). For example, if we want to begin an explicit transaction before any write operations take place, then to be safe we would need to do so before executing a raw query as well.

**Comment by ajcvickers** [comment]
@Timovzl I don't believe there is currently any way to determine this. We will consider adding it.

**Comment by Timovzl** [comment]
As a workaround, I have intercepted `NonQueryExecuting` and `NonQueryExecutingAsync`.

It's a bit fragile, though. Who knows if a scalar-returning raw SQL method will be added in the future.

And although I haven't observed other scenarios that lead to `NonQueryExecuting[Async]` (except initialization maybe), I'm not 100% certain.

**Comment by ajcvickers** [comment]
I think this is now possible using `CommandEventData.CommandSource`. See #23719, implemented by #24421.
