### ISSUE TITLE
dnx migrations do not scaffold properly

### ISSUE THREAD

**Issue by SergeyBarskiy** [dotnet/efcore#2289]
I created a context class with a collection based on a simple class.  I used fluent API to configure max length for some string properties of my class.  Running dnx add migration scaffolds properties, but maximum length configuration is ignored as well as required flag.  Happens for both fluent API and attribute based configuration.  This is in VS 2015 RC.  Anything I am missing?  Thanks.

**Comment by rowanmiller** [comment]
Hey,

MaxLength issue is tracked by https://github.com/aspnet/EntityFramework/issues/882

Attribute based configuration is not implemented yet and is tracked by https://github.com/aspnet/EntityFramework/issues/107

~Rowan
