### ISSUE TITLE
Stop using <inheritdoc />

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22894]
Docs team has confirmed that it is not supported.

**Comment by roji** [comment]
See note in https://github.com/dotnet/efcore/pull/22765#issuecomment-704372254

**Comment by ajcvickers** [comment]
Loop back in a few months just in case support gets added by the docs team.

**Comment by AndriySvyryd** [comment]
Anti-dupe of: https://github.com/dotnet/efcore/issues/18003

**Comment by roji** [comment]
Anti-dupe!

**Comment by roji** [comment]
<inheritdoc /> is now supported, so we should close this.
