### ISSUE TITLE
EntityFramework.Commands on Windows 8.1

### ISSUE THREAD

**Issue by anetegithub** [dotnet/efcore#2290]
Setup:
Windows 8.1 Professional x64
Visual Studio 2015 RC (also have VS 2013 Community)

``` powershell
{project folder with project.json}>dnx . ef migration add Init
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   EntityFramework.Commands 7.0.0-beta4
   EntityFramework.SqlServer 7.0.0-beta4
   Microsoft.AspNet.Mvc 6.0.0-beta4
   Microsoft.AspNet.Server.IIS 1.0.0-beta4
   Microsoft.AspNet.Server.WebListener 1.0.0-beta4

Searched Locations:
~

Try running 'dnu restore'.
~
```
##### After `dnu restore` project can't build

Worked on:
Windows 7 SP1 x64
VS 2015 RC (also have VS 2013 Community)

``` Powershell
{project folder with project.json}>dnx . ef migration add Init
Using context 'TemplateContext'.

{project folder with project.json}>dnx . ef migration apply
Using context 'TemplateContext'.

{project folder with project.json}>cd ..
```

**Comment by rowanmiller** [comment]
> After  dnu restore  project can't build

Can you provide details of the build failure? If it's failing to build then it's probably not an EF issue.

**Comment by anetegithub** [comment]
if i using `cmd> dnu restore` i have:
```powershell
System.ArgumentNullException : Value can't be null
  parameter name: appEnv
```
if i using `VS->Right click on References->Restore Packages` project can build but `System.InvalidOperationException: ...`

Exacly the same code running on Win7 without errors.

**Comment by rowanmiller** [comment]
@glennc have you seen the error listed above before? Just thinking you might know the issue off the top of your head :smile:. If not, should this go to the DNX repo (obviously with a full repro)?

**Comment by rowanmiller** [comment]
@anetegithub can you run `dnvm list` and see which version of DNX is active (it will have a * in the Active column). Can you then check in your `global.json` file and see what DNX version is specified there. If there is a mismatch can you run `dnvm use <version from global.json>` and then try restoring again.

**Comment by anetegithub** [comment]
You are was right!
```powershell
Active Version           Runtime Architecture Location                     Alias
------ -------           ------- ------------ --------                     -----
       1.0.0-beta4       clr     x64          C:\Users\Anton\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\Anton\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\Anton\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\Anton\.dnx\runtimes
  *    1.0.0-beta5-11911 clr     x86          C:\Users\Anton\.dnx\runtimes default
```
project.json
```json
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta4"
    }
}
```
`dnvm use 1.0.0-beta4` solved the problem!
##### Sorry for report in not right place
