### ISSUE TITLE
Microsoft.Data.Sqlite and Flash wear

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/efcore#22903]
Native SQLite has options to control how data is written to the file system in order to get control of aspects such as Flash wear. 
http://sqlite.1065341.n5.nabble.com/Sqlite-on-NAND-flash-devices-td44873.html is one thread discussing these aspects. 

What is the default policy employed by Microsoft.Data.Sqlite regarding flash wear and how can it be controlled ?

**Comment by bricelam** [comment]
When EF Core creates databases, it configures WAL.

Microsoft.Data.Sqlite leverages SQLitePCLRaw which includes a version of SQLite build from the amalgamation and defines SQLITE_TEMP_STORE=2.

SQLitePCLRaw also lets you use a [custom version of SQLite](https://docs.microsoft.com/dotnet/standard/data/sqlite/custom-versions) that you can tune to your heart's content.

Beyond that, feel free to send PRAGMAs and manage transactions and checkpoints in your app as you see fit.

**Comment by JensNordenbro** [comment]
Thanks for all the info!
