### ISSUE TITLE
SqlServer: string.IsNullOrWhiteSpace translation is overly complex

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#22916]
Today, we translate this as `@value IS NULL OR LTRIM(RTRIM(@value)) = N''`. But I have a few questions:

1. Why do we trim both the start and the end? Just one would produce the same result with less processing.
2. More importantly, why do we trim at all? As we know from our StartsWith research, `N' ' = N''` returns true in SQL Server.

IMHO, the translation should be `@value IS NULL OR @value = N''`

**Comment by bricelam** [comment]
In a similar vein, IsNullOrEmpty should use LIKE.

**Comment by bradmarder** [comment]
@bricelam Possible to save a few bytes with `COALESCE(@value, N'')= N''`?

**Comment by roji** [comment]
@bradmarder IIRC COALESCE prevents index use, so `@value IS NULL OR @value = N''` should be preferred. I don't know anything about `IS NULL` vs. `ISNULL` through.

**Comment by bradmarder** [comment]
@roji You are totally right about `COALESCE` not using an index, I missed that aspect. I did test `ISNULL([@value], N'') = N''` on SQL Server 2017 and it did use an index seek (same exact execution plan as the `@value IS NULL OR @value = N''`.

**Comment by roji** [comment]
Split out changing IsNullOrEmpty to #23037.

**Comment by manfredwippel** [comment]
> @bradmarder IIRC COALESCE prevents index use, so `@value IS NULL OR @value = N''` should be preferred. I don't know anything about `IS NULL` vs. `ISNULL` through.

https://github.com/dotnet/efcore/issues/22916#issuecomment-707151020

To provide equal funtionality the statement must be `@value IS NULL OR @value = N'' or nullif(@value, '') is null`
I know the statement is not sargable but then Devs have to use string.IsNullOrEmpty(..)
