### ISSUE TITLE
Making DbContext Proxyable

### ISSUE THREAD

**Issue by mnver1** [dotnet/efcore#22919]
Sorry if this is the wrong place to post this.

I proxy DbContext for several purposes but I recently tried v5.0 and noticed that it introduces 3 non-virtual members which make DbContext less proxyable.

```
public event EventHandler<SavingChangesEventArgs> SavingChanges;
public event EventHandler<SavedChangesEventArgs> SavedChanges;
public event EventHandler<SaveChangesFailedEventArgs> SaveChangesFailed;
```

I hope you consider making them virtual.

**Comment by AndriySvyryd** [comment]
@mnver1 Event overriding behavior is undefined in C#, see https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1070?view=vs-2019. Consider [hiding them](https://netexperiments.blogspot.com/2008/02/event-override-in-c-with-taste-of.html) instead.
