### ISSUE TITLE
Boolean model resulting in nullable database column

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#22913]
### Issue

When I attempt to add a `bool` property to my `ApplicationUser` class, I get a warning, and the property is made nullable in the database.

### Code

I just added the `NoFollowLinks` property to my `ApplicationUser` class and gave it a default value of `true`.

    public class ApplicationUser : IdentityUser
    {
        [StringLength(120)]
        public string Name { get; set; }

        [Column(TypeName = "NVARCHAR(MAX)")]
        public string ProfileMarkDown { get; set; }

        [Column(TypeName = "NVARCHAR(MAX)")]
        public string ProfileHtml { get; set; }

        [Column(TypeName = "NVARCHAR(MAX)")]
        public string Remarks { get; set; }

        public bool NoFollowLinks { get; set; }

        public ICollection<Article> Articles { get; set; }
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<ApplicationUser>()
            .Property(u => u.NoFollowLinks)
            .HasDefaultValue(true);

        base.OnModelCreating(builder);
    }

When I add the migration or update the database, I get a warning.

> The 'bool' property 'NoFollowLinks' on entity type 'ApplicationUser' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'.

I think I understand the warning and can live with it, but then I see the generated database column is nullable.

    [NoFollowLinks]        BIT                DEFAULT (CONVERT([bit],(1))) NULL,

My goal is to add a bit column with a default value of 1. The column should not be nullable. Is this possible?

*NOTE: I tried adding the `[Required]` attribute but that produced an empty migration. My understanding is that Entity Framework generates non-nullable columns from value type properties, by default, which is what I expected here.*

### Include provider and version information

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.4

**Comment by SoftCircuits** [comment]
NOTE: I tried adding the `[Required]` attribute but that produced an empty migration. My understanding is that Entity Framework generates non-nullable columns from value type properties, by default.

**Comment by AndriySvyryd** [comment]
`ApplicationUser` is derived from `IdentityUser`, so all additional columns [need to be nullable when using TPH](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#entity-type-hierarchy-mapping).
