### ISSUE TITLE
Sqlite: Should string.Contains use LIKE?

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#22917]
We sometimes use LIKE on SQL Server. Should SQLite do the same?

https://github.com/dotnet/efcore/blob/692be06c06f12fadf7e33c56b3a518c4e1d5bdb1/src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs#L291-L311

**Comment by roji** [comment]
I thought I looked through all this, maybe I missed this in Sqlite...

Yeah, for constants LIKE seems to be the best way - can use indexes in some cases and generally what you'd write yourself...

**Comment by Marusyk** [comment]
I will try to prepare a PR for this

**Comment by AndriySvyryd** [comment]
**EF Triage**: There doesn't seem to be enough value to warrant a breaking change
