### ISSUE TITLE
Unable to Connect to SQL Azure

### ISSUE THREAD

**Issue by paranoid-android** [dotnet/efcore#2292]
I am using ASP.NET 5 on Mac OS X. I am trying to connect to my SQL Azure Database using the following code:

```
var serverName = "[protected]";
var dbName = "[protected]";
var userId = "[protected]";
var password = "[protected]";
var sql = "SELECT * FROM Customer";

using (var database = new SqlConnection("Server=tcp." + serverName + ".database.windows.net,1433;Database=" + dbName + ";User Id=" + userId + ";Password=" + password + ";Trusted_Connection=False;Encrypt=True;Max Pool Size=25"))
{
  database.Open();
  return await database.QueryAsync<T>(sql);                     
}
```

When this code gets executed, an exception is thrown. The exception details looks like this:

```
Type:
System.NotImplementedException

Message:
SSL encryption for data sent between client and server is not implemented.
```

It seems like developers cannot interact with SQL Azure databases from ASP.NET 5 running on Mac OS X. This is a HUGE issue.

**Comment by rowanmiller** [comment]
This is a limitation of the SQL Client implementation in Mono - here is the issue tracking it on their side https://bugzilla.xamarin.com/show_bug.cgi?id=25491.

BTW you should be able to set `Encrypt=False` and be able to connect without SSL.

Once cross-platform .NET Core is available this will give you the same SQL Client implementation on OSX/Linux that you get on Windows. But in the meantime you need to use Mono which does have some limitations.

**Comment by npnelson** [comment]
SQL Azure **requires** SSL connections per: https://msdn.microsoft.com/en-us/library/azure/ff394108.aspx, so I'm afraid you are stuck for now.

**Comment by paranoid-android** [comment]
Ouch. It doesn't seem right to say the Entity Framework is cross-platform when connecting to a SQL Azure database isn't an option.

**Comment by ErikEJ** [comment]
@paranoid-android Did you read: Once cross-platform .NET Core is available this will give you the same SQL Client implementation on OSX/Linux that you get on Windows.

**Comment by NickBehrends** [comment]
@ErikEJ Yet here we are, with the error still persisting.

**Comment by ErikEJ** [comment]
@paranoid-android There must be an existing issue in the .NET Core repo for this?

**Comment by NickBehrends** [comment]
@ErikEJ Nothing open that the query for 'ssl' returns. Though, looking deeper into the issue, it appears to be Mono at fault here, not .NET Standard or EF. [Here's the exact line of code returning the not implemented exception](https://github.com/mono/mono/blob/master/mcs/class/System.Data/System.Data.SqlClient/SqlConnection.cs#L819-L823), I dug through the bugtracker and [it looks like theres actually been an issue open for this since 2014](https://bugzilla.xamarin.com/show_bug.cgi?id=25491).

**Comment by ErikEJ** [comment]
@paranoid-android So let us assume this works with .NET Core as stated above, then?
