### ISSUE TITLE
Disable ModelCaching, call OnModelCreating() for each instance of dbContext

### ISSUE THREAD

**Issue by kAvItHa-cL** [dotnet/efcore#22928]
Documentation Says : The model for that context is cached and is for all further instances of the context in the app domain. This caching can be disabled by setting the ModelCaching property on the given ModelBuidler

But i can't find way to do it. I have to disable caching because I am adding Model at runtime and loading all the models from assembly and creating database.

I found this link which says one way of achieving this is using DBModelBuilding - adding model mannually to context but it is for Entity Framework, Not helped for EF Core.

Entity Framework 6. Disable ModelCaching

I hope some one has solution for this.

**Comment by AndriySvyryd** [comment]
You can [change the cache key](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model) to properly represent the model that you are building.

You can also [build the model outside](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.conventions.sqlserverconventionsetbuilder.build) of the `DbContext` and then [provide it in the options](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder-1.usemodel).
