### ISSUE TITLE
Any interest in an Entity Framework to EF Core porting reference document?

### ISSUE THREAD

**Issue by jonlouie** [dotnet/efcore#22941]
## Would the EF Core team be interested in adding a reference guide for porting from Entity Framework to EF Core? 

A couple of weeks ago I heard there might be interest in collaborating on such a document so I wanted to raise the question in a public forum. It would include things like:
* Syntactical differences
* Behavioral changes
* Feature disparity
* Etc.

This list could be expanded to include other topics such as Porting Guidance (when to upgrade to EF6 vs migrating to EF Core) or anything else that the community might find useful. The main goal would be to bring all of this information to a central, community-built knowledge base.

Here is what I have so far: https://github.com/jonlouie/docs-sandbox/blob/master/README.md

If there any interest in adding this type of content, I'm all ears for any suggestions and would be happy to collaborate.

**Comment by AndriySvyryd** [comment]
Yes, this is something that we are interested in as there is still a significant number of users who haven't ported to EF Core. The content should loosely follow the existing structure on [feature comparison](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/) and [porting tips](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/).

The main issue tracking this is https://github.com/dotnet/EntityFramework.Docs/issues/1180, so I'll close this one as duplicate. That issue contains a link to a [video that could be useful](https://channel9.msdn.com/Shows/On-NET/Migrating-from-Entity-Framework-6-to-Core).
Also consider these related issues: https://github.com/dotnet/EntityFramework.Docs/issues/684, https://github.com/dotnet/EntityFramework.Docs/issues/1971, https://github.com/dotnet/EntityFramework.Docs/issues/1989

**Comment by jonlouie** [comment]
@AndriySvyryd Thank you for the information and feedback. I'll take a look at the materials you've outlined to see where I can contribute.
