### ISSUE TITLE
Is this a breaking change, and should it be documented?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#22956]
You get the following warning after upgrading a project with a scaffolded DbContext to EF Core 5:  

`Warning CS0618  'RelationalIndexBuilderExtensions.HasName(IndexBuilder, string)' is obsolete: 'Use HasDatabaseName() instead.`

Workaround: Re-scaffold with the EF Core 5 tooling

**Comment by AndriySvyryd** [comment]
Generally we don't consider obsoleted methods a breaking change and we don't specifically call them out in documentation unless the obsoletion message isn't enough to describe what needs to be changed.
