### ISSUE TITLE
Full support for custom provider aggregate functions

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#22957]
Following discussion in #13278, I've done some exploratory work in https://github.com/npgsql/efcore.pg/pull/1531 on PostgreSQL aggregate functions. Here are some issues I ran into:

* It seems impossible to add support for aggregate functions in GroupBy - [GroupingElementExpression is private, etc.](https://github.com/dotnet/efcore/blob/170625d82b78e270046ba16ab30f8ae942c19e88/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L471)
* For top-level (IQueryable) invocations, lots of code needs to be duplicated from relational (see https://github.com/npgsql/efcore.pg/pull/1531/files#r502918288).
    * Weak entities in particular seem impossible to support (https://github.com/npgsql/efcore.pg/pull/1531/files#r502918905)

/cc @smitpatel

Interesting candidate translations:

* [GROUP_CONCAT](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html) for MySQL (see [#26838](https://github.com/dotnet/efcore/issues/26838)), also see other MySQL functions on that page. In PostgreSQL this is called [string_agg](https://www.postgresql.org/docs/current/functions-aggregate.html).
* [json_agg/jsonb_agg](https://www.postgresql.org/docs/current/functions-aggregate.html) on PostgreSQL, [JSON_OBJECTAGG](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html) on MySQL.
* [array_agg](https://www.postgresql.org/docs/current/functions-aggregate.html) on PostgreSQL.

**Comment by smitpatel** [comment]
GroupBy aggregate issue is not related to custom provider function. Not all GroupBy patterns work right now and no one can extend them either that is one of the part in #18923 

For second point, just need to make TranslateExpression protected. But that issue is not related to aggregate either. Any custom queryable method will suffer that.

**Comment by roji** [comment]
OK, thanks - it would be nice if we could make all this work in 6.0. It seems useful to me to track here everything what's needed for custom provider aggregate functions, but up to you if you feel everything's covered elsewhere.

**Comment by roji** [comment]
Note #2981 which tracks string.Join (translatable with e.g. STRING_AGG).

**Comment by smitpatel** [comment]
Base infra added in #27931 
For supporting custom functions, we need to add method call translator like hierarchy.

**Comment by roji** [comment]
@smitpatel keeping open just in order to verify top-level custom aggregate support (as in https://github.com/dotnet/efcore/pull/28092#discussion_r881346480), which may require some extra work.

**Comment by smitpatel** [comment]
Filed #28097 for additional work.
