### ISSUE TITLE
Performance issues with encryption of Sqlite database 

### ISSUE THREAD

**Issue by jacobkochekkan** [dotnet/efcore#22969]
I wrote an application on .NET Core that uses entity framework and SQLite(attached the same). When I use a connection string without a password, the CPU consumption on MacOs is below 10%. But when the connection string has a password included, the CPU performance spikes up to over 100%.

For your convenience, below are the nuget packages used.
`<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.8" />`
`<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.8">`
`<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.8">`
`<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.4" />`

Below is the dotnet--info from my Mac machine:

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.15
OS Platform: Darwin
RID: osx.10.15-x64
Base Path: /usr/local/share/dotnet/sdk/3.1.402/
Host (useful for support):
Version: 3.1.8
Commit: 9c1330dedd
.NET Core SDKs installed:
2.1.202 [/usr/local/share/dotnet/sdk]
3.1.300 [/usr/local/share/dotnet/sdk]
3.1.301 [/usr/local/share/dotnet/sdk]
3.1.402 [/usr/local/share/dotnet/sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

[SqliteDebug.zip](https://github.com/dotnet/efcore/files/5364496/SqliteDebug.zip)

**Comment by AndriySvyryd** [comment]
@bricelam

**Comment by bricelam** [comment]
Deriving encryption keys is expensive. You're looking for feature #13837

**Comment by bricelam** [comment]
Note, you can mitigate this by keeping the connection open across multiple database operations.

**Comment by hesham101** [comment]
When connect to multi database u will see true big problem
