### ISSUE TITLE
Issue with Unicode fields matching when they should not

### ISSUE THREAD

**Issue by matthew-j-clark** [dotnet/efcore#22967]
Hello EFCore team,
I am having what I suspect is an encoding issue for Unicode fields in EFCore.
I have the following rows in my table "RoleAssignmentReaction":
Table layout:
![image](https://user-images.githubusercontent.com/10472072/95711218-2afdf680-0c17-11eb-922b-1b9d5e618ab2.png)

Rows:
![image](https://user-images.githubusercontent.com/10472072/95711147-086bdd80-0c17-11eb-935c-2d4c78d08df0.png)

The query for 🧪 returning no results from ssms:
![image](https://user-images.githubusercontent.com/10472072/95711546-d313bf80-0c17-11eb-8cb1-ba8c5878f327.png)

When I try to use the 🧪 unicode character instead for "adding" a row in entity framework, I get a primary key violation. The clue something is wrong that when I run the below with messageId matching the current row, but emote as 🧪 instead of what is stored (a unicode '🇦') I get one result returned
 var existingEntity = await ctx.RoleAssignmentReaction.FirstOrDefaultAsync(
                    x => x.MessageId == messageId && x.EmoteReference == emote);
Ex:
![image](https://user-images.githubusercontent.com/10472072/95711429-9942b900-0c17-11eb-9a03-b1e72aee57f6.png)

Is there something I am missing here?
Thanks,
Matt

**Comment by SealSlicer** [comment]
By changing the type from nvarchar to varbinary, I am able to handle the string conversion manually in code, and now it works.

**Comment by AndriySvyryd** [comment]
@SealSlicer Make sure to call [`IsUnicode`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.propertybuilder.isunicode?view=efcore-3.1#Microsoft_EntityFrameworkCore_Metadata_Builders_PropertyBuilder_IsUnicode_System_Boolean_) on `RoleId` and `EmoteReference`. If this doesn't help please provide a small runnable project so we can invetigate.

**Comment by SealSlicer** [comment]
Hey @AndriySvyryd how would you like the project? I converted the table to use varbinary instead of nvarchar and that 'solved' the problem.  The code as of me filing the bug is here:
https://github.com/SealSlicer/OmgSpidersGuild/blob/a0f7971ed788221f2589cab90ead457074e1e981/SpiderSalesDatabase/
Before filing the bug I did try explicitly calling "IsUnicode" but that did not work for me.

**Comment by AndriySvyryd** [comment]
@SealSlicer I get the same behavior just by using SSMS. Another workaround is to use `Latin1_General_BIN2` collation on these columns (EF 5.0.0 has `UseCollation()`)

**Comment by SealSlicer** [comment]
Which behavior did you see in ssms @AndriySvyryd ?  I didn't have the described issue when querying in ssms.

**Comment by AndriySvyryd** [comment]
Querying or adding a new row with 🧪 produced the same results as with EF

**Comment by AndriySvyryd** [comment]
The difference from your image is that I used a unicode literal `N'🧪'`
