### ISSUE TITLE
Ability to refresh set of entities with store values

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#2296]
We have an item to track adding `EntityEntry.Reload` (#1203) but in EF6 you could also use `MergeOption` to refresh a set of entities using a query.

**Comment by rmccabe24** [comment]
Has this enhancement been implemented?  We are currently using EF7 and seeing an issue where I update the database but the change is not being reflected in the DB Context.  Therefore need to refresh.

**Comment by rowanmiller** [comment]
@rmccabe24 no, not yet. It will most likely be post v1.0.0

**Comment by rmccabe24** [comment]
Thats really unfortunate.  When is the expected release of v1.0.0?

**Comment by rowanmiller** [comment]
We will release at the same time as ASP.NET Core, and there are no definite dates around that just yet. They will be public as soon as we have them.

**Comment by Steve887** [comment]
@rowanmiller is there any progress or a workaround for this? Currently, the only way I can reset the cached values is restarting my entire application which is obviously not appropriate.

**Comment by rowanmiller** [comment]
@Steve887 this feature has not been implemented yet. 

> Currently, the only way I can reset the cached values is restarting my entire application which is obviously not appropriate.

How about just creating a new instance of you context? We generally advise against having a global instance of your context that is shared throughout the application. In general you tend to get better performance with smaller scoped contexts that are used for an operation and then thrown away.

**Comment by ajcvickers** [comment]
Closing as we haven't seen significant demand for this feature. We could revisit this decision based on feedback and we would also consider a well-written community PR for it.
