### ISSUE TITLE
method ModelBuilder.HasDefaultSchema is not working (No database selected)

### ISSUE THREAD

**Issue by alex-dubatov** [dotnet/efcore#22971]
Approach described below was working with net core 2.2, but fails on net core 3.1.8.

### ConsoleApp4_NetCore3.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.2" />
  </ItemGroup>

</Project>
```

### SQL
```sql
CREATE DATABASE `db`;
use `db`;
CREATE TABLE `t` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
### C#
```c#
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp4_NetCore3
{
    class Program
    {
        static void Main()
        {
 // don't specify Database in connection string. Specify it in OnModelCreating
            var options = new DbContextOptionsBuilder<MyContext>().UseMySql("Server=localhost;User=root;Password=1111;").Options;
            using var db = new MyContext(options);
 // exceptions throws here on line below
            db.T.ToArray();
        }
    }


    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options) : base(options) { }

        public DbSet<T> T { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
// specify db name
            modelBuilder.HasDefaultSchema("db");
        }
    }

    public class T
    {
        [Key]
        public int Id { get; set; }
    }
}

```

### Exception Details
```
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=No database selected
  Source=MySqlConnector
  StackTrace:
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__95.MoveNext() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 210
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ConsoleApp4_NetCore3.Program.Main() in C:\Users\alex\source\repos\ConsoleApp1\ConsoleApp4_NetCore3\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
MySqlException: No database selected
```
### Technical details
EF Core version:
net core 3.1.8 (sdk 3.1.402)
Visual Studio Community 2019 16.7.5

**Comment by ErikEJ** [comment]
which provider version?

**Comment by smitpatel** [comment]
cc: @lauxjpn

**Comment by lauxjpn** [comment]
@alex-dubatov See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1181#issuecomment-702371298 for references, PRs and suggestions about schema use in MySQL and Pomelo.

Basically, the EF Core concept of schemas is the same one that SQL Server uses, which are basically just categories (organization units) you can use to group multiple tables together _within the same database_.

This is fundamentally different from the MySQL terminology, that uses the word "schema" just as a synonym for "database". EF Core currently supports only a single database for a given `DbContext`, so when using Pomelo, you can only use one database as well and because MySQL does not support the EF Core concept of schemas, you cannot really use schemas within databases at all.

However, we later implemented https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/982, with which you can specify how to translate a specified schema name to a table name (but still inside of the single current database).

---

So, since `modelBuilder.HasDefaultSchema("db");` is not the same as executing `` USE `db`. ``, MySQL correctly returns an error, because you haven't specified the database to be used.
If you want to change/set the database that should be used at a later point, you can do so as long as the connection has not been opened yet (e.g. in `DbContext.OnConfiguring()` using a `MySqlConnectionStringBuilder`).

**Comment by alex-dubatov** [comment]
@lauxjpn So, now I can't use two contexts for two different databases with one DbConnection?
Will be implemented feature to support it in a future?
It's important for me, because of big legacy code.
So, I can't migrate to net core 3.1 from 2.2.

**Comment by lauxjpn** [comment]
> So, now I can't use two contexts for two different databases with one DbConnection?

I believe that is correct. This is a scenario that will not work out-of-the-box.

The supported way to implement such a scenario would be to merge the two databases into one. If you want to keep the table names distinct from each other, you could prefix them (`db1_table1`, `db2_table1`) and use `MySqlSchemaBehavior.Translate` as shown in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/982 to translate a specified schema name and table name to a final table name (e.g. schema `db1` and table `table1` could be translated to `db1_table1`).

However, there should also be a couple of (not officially supported) ways to accomplish directly what you want (using two actual databases together).

What is the reason for using a single `DbConnection` with two different databases?

**Comment by alex-dubatov** [comment]
@lauxjpn The reason is to use one transaction for two and more databases. (in our project much more than two databases).
And it's not possible to alocate all db's in one DbContext.
Because DbContext's corresponds to logically separated databases.
Also I don't want to have one large DbContext.

**Comment by lauxjpn** [comment]
> The reason is to use one transaction for two and more databases. (in our project much more than two databases).

If you want to use a single transaction across multiple databases, take a look at [TransactionScope](https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions) (EF Core docs) and as a general overview at [C# controlling a transaction across multiple databases](https://stackoverflow.com/a/22512547/2618319) on StackOverflow.

> Because DbContext's corresponds to logically separated databases.
> Also I don't want to have one large DbContext.

That is not necessarily the case. You can use multiple `DbContext` derived classes over the same database. This is not unusual with larger databases, where each `DbContext` derived class may just represent a specific subset of the database.

---

> That being said, there should also be a couple of (not officially supported) ways to accomplish directly what you want (accessing two actual databases from one `DbConnection`).

Anyway, if you don't want/can refactor your databases and code to either use a single underlying database or to use the suggested `TransactionScope`, I can also provide you with some code to use a single `DbConnection` with multiple databases and Pomelo.

**Comment by alex-dubatov** [comment]
@lauxjpn Thanks for the information.
> I can also provide you with some code to use a single DbConnection with multiple databases and Pomelo.
Please provide it.

**Comment by lauxjpn** [comment]
I specifically made sure when we closed the door on the schema support, that there are multiple back doors so that users can custom implement the behavior anyway.

A simple way is demonstrated in the following fully working code sample:

<details>
<summary>Sample code to translate schemas to databases</summary>

```c#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
    }

    public class Cookie
    {
        public int CookieId { get; set; }
        public string Name { get; set; }
    }

    public class CustomMySqlSqlGenerationHelper : MySqlSqlGenerationHelper
    {
        public CustomMySqlSqlGenerationHelper(
            RelationalSqlGenerationHelperDependencies dependencies,
            IMySqlOptions options)
            : base(dependencies, options)
        {
        }

        protected override string GetSchemaName(string name, string schema)
            => schema; // <-- this is the first part that is needed to map schemas to databases 
    }
    
    public class Context : DbContext
    {
        public virtual DbSet<IceCream> IceCreams { get; set; }
        public virtual DbSet<Cookie> Cookies { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Register our custom class here.
            // Since this is a console program, we need to create our own ServiceCollection for this.
            // In an ASP.NET Core application, the AddSingleton call can just be added to the general service
            // configuration method.
            var serviceProvider = new ServiceCollection()
                .AddEntityFrameworkMySql()
                .AddSingleton<ISqlGenerationHelper, CustomMySqlSqlGenerationHelper>()
                .AddScoped(
                    s => LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .BuildServiceProvider();
            
            optionsBuilder
                .UseInternalServiceProvider(serviceProvider) // use our ServiceProvider
                .UseMySql(
                    "server=127.0.0.1;port=3306;user=root;password=;database=EFCoreIssue22971_01_IceCreamParlor",
                    b => b.ServerVersion("8.0.21-mysql")
                        .SchemaBehavior(
                            MySqlSchemaBehavior.Translate,
                            (schemaName, objectName) => objectName) // <-- this is the second part that is needed to map
                                                                    //     schemas to databases
                        .CharSetBehavior(CharSetBehavior.NeverAppend))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("EFCoreIssue22971_01_IceCreamParlor");
            
            modelBuilder.Entity<Cookie>(
                entity =>
                {
                    entity.ToTable("Cookies", "EFCoreIssue22971_01_Bakery");
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.ExecuteSqlInterpolated($"CREATE DATABASE IF NOT EXISTS `EFCoreIssue22971_01_IceCreamParlor`;");
            context.Database.ExecuteSqlInterpolated($"CREATE DATABASE IF NOT EXISTS `EFCoreIssue22971_01_Bakery`;");
            context.Database.EnsureCreated();

            var iceCreams = context.IceCreams.ToList();
            var cookies = context.Cookies.ToList();
        }
    }
}
```
</details>

This generates the following output:

<details>
<summary>Logged SQL queries etc.</summary>

```sql
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.

info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.8 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.21 MySql

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (82ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      CREATE DATABASE IF NOT EXISTS `EFCoreIssue22971_01_IceCreamParlor`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      
      CREATE DATABASE IF NOT EXISTS `EFCoreIssue22971_01_Bakery`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (19ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
      FROM information_schema.tables
      WHERE table_type = 'BASE TABLE' AND table_schema = 'EFCoreIssue22971_01_IceCreamParlor'

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (141ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      
      CREATE TABLE `EFCoreIssue22971_01_Bakery`.`Cookies` (
          `CookieId` int NOT NULL AUTO_INCREMENT,
          `Name` longtext NULL,
          CONSTRAINT `PK_Cookies` PRIMARY KEY (`CookieId`)
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (129ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      
      CREATE TABLE `EFCoreIssue22971_01_IceCreamParlor`.`IceCreams` (
          `IceCreamId` int NOT NULL AUTO_INCREMENT,
          `Name` longtext NULL,
          CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      
      SELECT `i`.`IceCreamId`, `i`.`Name`
      FROM `EFCoreIssue22971_01_IceCreamParlor`.`IceCreams` AS `i`

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      
      SELECT `c`.`CookieId`, `c`.`Name`
      FROM `EFCoreIssue22971_01_Bakery`.`Cookies` AS `c`
```
</details>

**Comment by lauxjpn** [comment]
> Will be supported this approach in net core 5?

Some details will change (i.e. the `.SchemaBehavior(MySqlSchemaBehavior.Translate, (schemaName, objectName) => objectName)` call can be replaced with a `ConfigureWarnings()` call; for further information on this, follow https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1192), but the general idea will continue to work in Pomelo 5.x.

**Comment by Trevortni** [comment]
Based on your comment about ASP.NET Core, I added to `ConfigureServices(IServiceCollection services)`: 

```
services.AddSingleton<ISqlGenerationHelper, CustomMySqlSqlGenerationHelper>();
```

But I get the error:

```
"Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.Storage.ISqlGenerationHelper Lifetime: Singleton ImplementationType: DSD_Web_API.CustomMySqlSqlGenerationHelper': Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.RelationalSqlGenerationHelperDependencies' while attempting to activate 'DSD_Web_API.CustomMySqlSqlGenerationHelper'.)"
```

I tried adding `AddEntityFrameworkMySql()` before `AddSingleton`, but then it uses the `GetSchemaName` in the library instead of my derived class.

Is there something else I'm not seeing here?

> I specifically made sure when we closed the door on the schema support, that there are multiple back doors so that users can custom implement the behavior anyway with as little effort as possible.
> 
> A simple way is demonstrated in the following fully working code sample:
> 
> Sample code to translate schemas to databases
> ```cs
> using System;
> using System.Linq;
> using Microsoft.EntityFrameworkCore;
> using Microsoft.EntityFrameworkCore.Storage;
> using Microsoft.Extensions.DependencyInjection;
> using Microsoft.Extensions.Logging;
> using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
> using Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal;
> using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;
> 
> namespace IssueConsoleTemplate
> {
>     public class IceCream
>     {
>         public int IceCreamId { get; set; }
>         public string Name { get; set; }
>     }
> 
>     public class Cookie
>     {
>         public int CookieId { get; set; }
>         public string Name { get; set; }
>     }
> 
>     public class CustomMySqlSqlGenerationHelper : MySqlSqlGenerationHelper
>     {
>         public CustomMySqlSqlGenerationHelper(
>             RelationalSqlGenerationHelperDependencies dependencies,
>             IMySqlOptions options)
>             : base(dependencies, options)
>         {
>         }
> 
>         protected override string GetSchemaName(string name, string schema)
>             => schema; // <-- this is the first part that is needed to map schemas to databases 
>     }
>     
>     public class Context : DbContext
>     {
>         public virtual DbSet<IceCream> IceCreams { get; set; }
>         public virtual DbSet<Cookie> Cookies { get; set; }
> 
>         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>         {
>             // Register our custom class here.
>             // Since this is a console program, we need to create our own ServiceCollection for this.
>             // In an ASP.NET Core application, the AddSingleton call can just be added to the general service
>             // configuration method.
>             var serviceProvider = new ServiceCollection()
>                 .AddEntityFrameworkMySql()
>                 .AddSingleton<ISqlGenerationHelper, CustomMySqlSqlGenerationHelper>()
>                 .AddScoped(
>                     s => LoggerFactory.Create(
>                         b => b
>                             .AddConsole()
>                             .AddFilter(level => level >= LogLevel.Information)))
>                 .BuildServiceProvider();
>             
>             optionsBuilder
>                 .UseInternalServiceProvider(serviceProvider) // use our ServiceProvider
>                 .UseMySql(
>                     "server=127.0.0.1;port=3306;user=root;password=;database=EFCoreIssue22971_01_IceCreamParlor",
>                     b => b.ServerVersion("8.0.21-mysql")
>                         .SchemaBehavior(
>                             MySqlSchemaBehavior.Translate,
>                             (schemaName, objectName) => objectName) // <-- this is the second part that is needed to map
>                                                                     //     schemas to databases
>                         .CharSetBehavior(CharSetBehavior.NeverAppend))
>                 .EnableSensitiveDataLogging()
>                 .EnableDetailedErrors();
>         }
> 
>         protected override void OnModelCreating(ModelBuilder modelBuilder)
>         {
>             modelBuilder.HasDefaultSchema("EFCoreIssue22971_01_IceCreamParlor");
>             
>             modelBuilder.Entity<Cookie>(
>                 entity =>
>                 {
>                     entity.ToTable("Cookies", "EFCoreIssue22971_01_Bakery");
>                 });
>         }
>     }
> 
>     internal static class Program
>     {
>         private static void Main()
>         {
>             using var context = new Context();
> 
>             context.Database.ExecuteSqlInterpolated($"CREATE DATABASE IF NOT EXISTS `EFCoreIssue22971_01_IceCreamParlor`;");
>             context.Database.ExecuteSqlInterpolated($"CREATE DATABASE IF NOT EXISTS `EFCoreIssue22971_01_Bakery`;");
>             context.Database.EnsureCreated();
> 
>             var iceCreams = context.IceCreams.ToList();
>             var cookies = context.Cookies.ToList();
>         }
>     }
> }
> ```
> 
> This generates the following output:
> 
> Logged SQL queries etc.
> In essence, there are two steps:
> 
> 1. You need to derive from `MySqlSqlGenerationHelper` and override `GetSchemaName`:
> 
> ```cs
> public class CustomMySqlSqlGenerationHelper : MySqlSqlGenerationHelper
> {
>     public CustomMySqlSqlGenerationHelper(
>         RelationalSqlGenerationHelperDependencies dependencies,
>         IMySqlOptions options)
>         : base(dependencies, options)
>     {
>     }
> 
>     protected override string GetSchemaName(string name, string schema)
>         => schema; // <-- this is the first part that is needed to map schemas to databases 
> }
> ```
> 
> 2. You need to provide a schema name translator:
> 
> ```cs
> optionsBuilder
>     .UseInternalServiceProvider(serviceProvider) // use our ServiceProvider
>     .UseMySql(
>         "server=127.0.0.1;port=3308;user=root;password=;database=EFCoreIssue22971_01_IceCreamParlor",
>         b => b.ServerVersion("8.0.21-mysql")
>             .SchemaBehavior(
>                 MySqlSchemaBehavior.Translate,
>                 (schemaName, objectName) => objectName) // <-- this is the second part that is needed to map
>                                                         //     schemas to databases
>             .CharSetBehavior(CharSetBehavior.NeverAppend))
>     .EnableSensitiveDataLogging()
>     .EnableDetailedErrors();
> ```

Based on your comment about ASP.NET Core, I added to `ConfigureServices(IServiceCollection services)`: 

```
services.AddSingleton<ISqlGenerationHelper, CustomMySqlSqlGenerationHelper>();
```

But I get the error:

```
"Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.Storage.ISqlGenerationHelper Lifetime: Singleton ImplementationType: DSD_Web_API.CustomMySqlSqlGenerationHelper': Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.RelationalSqlGenerationHelperDependencies' while attempting to activate 'DSD_Web_API.CustomMySqlSqlGenerationHelper'.)"
```

I tried adding `AddEntityFrameworkMySql()` before `AddSingleton`, but then it uses the `GetSchemaName` in the library instead of my derived class.
