### ISSUE TITLE
Change Track a Dictionary Property

### ISSUE THREAD

**Issue by paul-charlton** [dotnet/efcore#23013]
Hi,
I have a property on an entity which is storing a dictionary of options.  However, when one of these options are update the change tracker doesn't log it as a change and therefore is missed on the save changes.  I was wondering if there was soemthing I was missing here or whether this should be a feature request?

Property (with backing fields):
```C#
        private readonly Dictionary<string, string> _options = new Dictionary<string, string>();

        private ReadOnlyDictionary<string, string> _readonlyOptions;

        public IReadOnlyDictionary<string, string> Options
        {
            get { return _readonlyOptions ??= new ReadOnlyDictionary<string, string>(_options); }
        }
```

Mapping:
```C#
builder
    .Property(x => x.Options)
    .HasConversion(
        v => JsonConvert.SerializeObject(v, new StringEnumConverter()),
        v => JsonConvert.DeserializeObject<Dictionary<string, string>>(v));
```

EF Core version: 3.1.8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1
Operating system:
IDE: Visual Studio 2019 16.7.6

Thanks in advance,
Paul.

**Comment by roji** [comment]
If you want EF Core to automatically detect changes to the *contents* of your property, you're going to have to set up a [value comparer](https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers) on it. This means that EF Core will snapshot (copy) your property contents when the entity is loaded from the database, and when SaveChanges is called, that snapshot will be compared against the updated version to see if anything changed.

Depending on how much data your dictionaries contain, this may be problematic perf-wise (think about snapshotting and comparing big dictionaries all the time). If that's the case, consider informing EF manually when the property changes:

```c#
context.Entry(entity).Property(e => e.Options).IsModified = true;
```
