### ISSUE TITLE
It is impossible to call inline TVFs in SQL Server that pass their arguments to full text search operators

### ISSUE THREAD

**Issue by slepmog** [dotnet/efcore#23018]
#### Please note:
The problem described below applies not only to EF Core, but also to:
- All versions of EF 6
- All versions of EF 5
- Linq2Sql when running on .NET 4.0 and above

The problem does NOT happen in Linq2Sql on .NET 3.5 and below.

---
#### The problem:

It is not possible to call a stored **inline** table-valued function in SQL Server that passes any of its arguments to a full text operator (e.g. [`contains`][2]).

That is, if you have this in SQL Server:

```sql
create function testing.FullTextInlineTvf(@order_number varchar(20))
returns table
as
return (
  select some_field
  from dbo.table1
  where contains (full_text_enabled_field, @order_number)
);
```

and you try to call it from EF, *in any way*, e.g.:

```cs
dx.Database.ExecuteSqlRaw("select * from testing.FullTextInlineTvf({0});", "334562");
```

you will get an exception:

> **Microsoft.Data.SqlClient.SqlException:** 'The full-text query parameter for Fulltext Query String is not valid.'

---

#### Why it happens

In SQL Server, inline table-valued functions are often unwound and integrated into the parent query, and their parameters are not materialized into actual variables, rather, the piece of the parent query that was used for the argument is substituted into the body of the TVF.

One manifestation of that behaviour is that if you have a parent query in the form of `select * from testing.FullTextInlineTvf('asd' + @something + 'sdf');`, then the argument expression will be substituted into the `FullTextInlineTvf` body, resulting in `where contains (full_text_enabled_field, 'asd' + @something + 'sdf')`, which is an invalid full text search term - it has to be either a literal or a variable, but not an expression.

Another manifestation of the same principle is that the call fails when the argument size is bigger than what is declared in the function. E.g. the function above has `@order_number varchar(20)`, and if you pass a simple variable that is `varchar(21)`, you will get the same error.

These principles apply regardless of the way the database is accessed. If you are working in SQL Server Management Studio, without any C# code or entity frameworks, and trying to execute:
```sql
declare @param varchar(21) = '334562';
select * from testing.FullTextInlineTvf(@param);
```
you will get the exact same error message from SSMS.

When EF generates SQL for the provided command, it goes:

```sql
exec sp_executesql N'select * from testing.FullTextInlineTvf(@p0);',N'@p0 nvarchar(4000)',@p0=N'334562'
```

Because of the `nvarchar(4000)`, the parameter cannot be passed to this inline TVF. It would only be possible to pass such parameter if its size was 20 *or below*.

In Entity Framework 6 and 5 the behaviour is slightly different. The scaffolding there is able to gather information about stored procedures, so it knows the parameter type is `varchar`, not `nvarchar`, so it passes `varchar(8000)` instead of `nvarchar(4000)`. The result is the same.

In Linq2Sql, the issue happens only if the project is using .NET 4.0 or above, which is weird because Linq2Sql correctly scaffolds and stores not only the types of the parameters (`varchar`), but also their sizes (`20`), but then [proceeds to ignore them][1].
It got away with this ignoring in .NET 3.5 because in that version the parameter size for the generated `sp_executesql` call was taken from the actual data passed:

```sql
exec sp_executesql N'select * from testing.FullTextInlineTvf(@p0);',N'@p0 varchar(6)',@p0='334562'
```
Here it passes `varchar(6)` because the actual parameter has 6 characters.

In .NET 4.0 this behaviour was changed, starting from that FW version Linq2Sql also generates `varchar(8000)` and causes the error.

---

In a perfect world,
- the breaking change between FW 3.5 and 4.0 would be reverted, which would automatically fix Linq2Sql, EF5 and EF6, and
- the same behaviour would also be accepted as the way to go for EF Core too (i.e., generate `varchar(6)` if the parameter size is 6 - or, if you are able to scaffold the size, then do that).

I guess that realistically it is not going to happen, and that ultimately this repo may not even the best place to post this issue.
With EF Core not being too concerned with stored procedures, this issue would arguably be a better fit for a general .NET 4.8 repo, but as far as I can tell, there isn't one, and so I am posting it here because the problem does technically apply to EF Core too.

I am aware of workarounds:

- In EF Core:
   ```cs
   dx.Database.ExecuteSqlRaw("declare @f varchar(20) = {0}; select * from testing.FullTextInlineTvf(@f);", "334562")
   ```
- In Linq2Sql:
   ```cs
   dx.ExecuteQuery<FullTextInlineTvfResult>("declare @f varchar(20) = {0}; select * from testing.FullTextInlineTvf(@f);", "334562");
   ```

Unfortunately, it does not mix very well with proper `IQueryable`s from all the other places.

---

[1]: https://stackoverflow.com/q/28981842/11683
[2]: https://docs.microsoft.com/en-us/sql/t-sql/queries/contains-transact-sql?view=sql-server-ver15

EF Core version: 3.1.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.6

**Comment by ErikEJ** [comment]
How about calling in EF Core with a proper defined SqlParameter ?

**Comment by slepmog** [comment]
@ErikEJ Yep, that works! And, contrary to my expectations, returns a proper honest `IQueryable` that can be further filtered, and it all goes out as a single query:

```cs
var result = dx.Set<TvfResult>()
    .FromSqlRaw("select * from testing.FullTextInlineTvf(@param)", new SqlParameter("@param", System.Data.SqlDbType.VarChar, 20) { Value = "334562" })
    .Where(t => t.SomeProperty > 0)
    .ToList();
```
```sql
exec sp_executesql N'SELECT [i].[SomeProperty]
FROM (
    select * from testing.FullTextInlineTvf(@param)
) AS [i]
WHERE [i].[SomeProperty] > 0.0E0',N'@param varchar(20)',@param='334562'
```

I still kind of hate it, because it involves raw SQL commands as opposed to lambdas, but given the current state of things in EF Core regarding stored procedures, I guess that's the absolute best there can be.

It's much worse in EF 6, where the raw sql portion is executed as is and returned as `IEnumerable` for further filtering on client side.
And it is (apparently) unfixable in Linq2Sql where the only option also appears to be `dx.ExecuteQuery<>` which is also an `IEnumerable`.

---

So in the end, I am an idiot, and EF Core does not even have this issue, because the inability to use lambdas comes from the lack of support of stored procedures rather than parameter size peculiarities.

The issue does apply fully to EF 6 and Linq2Sql, but I guess we won't see them fixed.

Then again, when/if stored procedures are better supported in EF Core at the lambda level, this issue may arise again, and there might be no workaround as it would have been lambdas! I hope not.

Thank you!
