### ISSUE TITLE
Confusing information

### ISSUE THREAD

**Issue by GCascaes** [dotnet/efcore#23024]
This page says that its information applies to EF Core from 2.0 to 3.1, but actually not everything applies to all those versions. I needed to check EFCore Github to find out that the overload of the Log method that accepts tuples to configure the log level is actually only available on EF Core 3.0 and later releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 372eced4-f13f-db5d-9e7e-e9591aefc32a
* Version Independent ID: c68149db-fa8a-9e48-5014-c8989bbaf092
* Content: [WarningsConfigurationBuilder.Log Method (Microsoft.EntityFrameworkCore.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.warningsconfigurationbuilder.log?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/WarningsConfigurationBuilder.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Diagnostics/WarningsConfigurationBuilder.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
Filed a customer suggestion in internal issue tracker.
@ajcvickers - How should we track it going forward? We don't exactly control anything on the page to improve it.

**Comment by ajcvickers** [comment]
I don't think we need to track this here. As you say, if it gets fixed, then we will get that fix when we pubish.
