### ISSUE TITLE
Composition over Inheritance

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#2303]
Composition over inheritance is considered good.

Support for implementing composition over inheritance in EF7.
This can be done now with concrete classes.

But when it comes to implement it using interfaces, it does not go well. The migration does not create tables and foreign key mappings when an interface is used for composition and the concrete classes are created later using those interfaces.

**Comment by rowanmiller** [comment]
@satyajit-behera could you share some code that shows the pattern you would like to be able to achieve in your entities? This will help us derive what features would be required in EF to enable the scenario.

**Comment by satyajit-behera** [comment]
@rowanmiller Thanks. Sure, I will create an example for the same and upload it here.

**Comment by Zero3** [comment]
@sayedihashimi Ping.

**Comment by divega** [comment]
@Zero3 did you mean to ping someone else? :smile:

**Comment by Zero3** [comment]
@divega Oh, right you are. My tab completion skills are clearly not in their final form yet! Sorry. @satyajit-behera was the one!

**Comment by Zero3** [comment]
@rowanmiller Was this issue resolved, since you closed this? Or was it because of the lack of an example?

**Comment by divega** [comment]
@Zero3 it was closed because of lack of information.
