### ISSUE TITLE
Can Someone Please Tell Me the Proper Way to Do a View in EFCore Since DbQuery<T> is Being Deprecated - Migrations?

### ISSUE THREAD

**Issue by maxmin88** [dotnet/efcore#23040]
I understand DbQuery<T> is being deprecated and we are supposed to use DbSet<T> going forward.  I have tried doing this and have run into issues creating a View out of a tables Join.    I am using SQLite and UWP with Migrations and Model projects. 

With DbQuery I would define a class JoinData in my model including the fields from the two tables that I want to view.  I would then use DBQuery<JoinData> Joins { get;  set; } in my MyContext definition.
I am currently using MyContext.Joins.FromSqlRaw() to define my query because my query is somewhat complicated with Grouping and Sum.

Using DBQuery<T> would keep the Migration from creating a table in my database.  However DbSet creates a Migration table for my JoinData Class.  I tried to use the [NotMapped] attribute on the JoinData class but then I got an error:
Cannot create a DbSet for 'JoinData' because this type is not included in the model for the context.

Can someone point me to an example in EFCore of how to do a View of Joins using SQLite and Migrations please?

I have included a fairly basic SQLite project with data showing the issue.  If you change the DbQuery to DBSet in EFDBContext the errors start.

[EFAdvancedDB.zip](https://github.com/dotnet/efcore/files/5397613/EFAdvancedDB.zip)

**Comment by ErikEJ** [comment]
Have you tried with .ToTable(null) ?

**Comment by ajcvickers** [comment]
@maxmin88 While @ErikEJ's suggestion should work, it would be more normal to map a view using `ToView`:

```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LinkAndContact>().ToView("LinksAndContacts");
    }
```
