### ISSUE TITLE
Identification of commits in daily dev builds on MyGet

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2305]
As a provider writer, that feeds on the daily dev builds from MyGet, it would be very helpful to have a way of identifying what commit was included in which daily build - mabe tags? Is this currently possible, or can it be made available?

**Comment by bricelam** [comment]
Dupe of aspnet/Universe#64?

**Comment by ErikEJ** [comment]
@bricelam  Yes, so I wont brace myself for it to happen, then!
