### ISSUE TITLE
Backing Fields Not Working Correctly

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/efcore#23064]
### Summary
I want to store in my database string values rather than enumeration values so that it is easier for DBAs and other folks working with stored data to understand what is stored in each column. 

In order to do this, I am using a backing field, as described [here](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations).

However, the resultant column generated by Entity Framework Core was of the type of the exposed property, _not_ the private backing field like I expected.

This causes EF to not be able to save records to this table, since the private backing field is a `string` but the column in the Azure SQL table is an `int`.
### My Code

```C#
/// <summary>
/// Read more about Backing Fields and EntityFramework Core here:
/// https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations
/// </summary>
private string _committeeType;

public RepresentativeType CommitteeType { 
	get 
	{
		return OurGovService.GetRepresentativeType(_committeeType);
	}
	set 
	{
		_committeeType = OurGovService.GetRepresentativeType(value);
	} 
}
```

### Resulting Migration
```C#
using Microsoft.EntityFrameworkCore.Migrations;

namespace OurGov.Server.Migrations
{
    public partial class UpdateNameOfCommitteeType : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "CommitteeType",
                table: "Organizations",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CommitteeType",
                table: "Organizations");
        }
    }
}

```

### Include provider and version information

EF Core version: 3.1.7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1
Operating system:
IDE: Visual Studio Community 2019 Version 16.7.3

**Comment by roji** [comment]
Backing fields are for use when the property and field are of the same type (or at least assignable).

What you're looking for is likely to have a [field-only property](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=fluent-api#field-only-properties), so that EF knows only about your string field, and totally ignores your public property which exposes the enum:

<details>
<summary>Code sample</summary>

```c#

await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Organization> Organizations { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Organization>(builder =>
        {
            builder.Property("_committeeType").HasColumnName("CommitteeType");
            builder.Ignore(e => e.CommitteeType);
        });
    }
}

public class Organization
{
    public int Id { get; set; }

    private string _committeeType;

    public RepresentativeType CommitteeType
    {
        get => Enum.Parse<RepresentativeType>(_committeeType);
        set => _committeeType = value.ToString();
    }
}

public enum RepresentativeType
{
    Foo,
    Bar
}
```

</details>

**Comment by taylorchasewhite** [comment]
Ah thanks, good to know. 

Any chance we can change this issue to an enhancement request? Where possible I _prefer_ to avoid Fluent API, and in this situation it seems like interpreting the private field-only property as a backing field regardless of the return type is a safe interpretation--i.e. using that naming convention described in the backing field documents (`_committeeType` and `CommitteeType`) can be safely assumed that the desired behavior is identical to what you've coded above?

**Comment by roji** [comment]
An alternative way to address this would be for EF to discover private fields which have [Column] on them - this would allow you to have the field with [Column] and the property with [NotMapped]. On the other hand that would require EF to reflect over all private fields as well, which could be a model building perf issue.

**Comment by taylorchasewhite** [comment]
Yeah that would work as well, but I agree that could be performance intensive if you have to do that additional work. 

Would the proposal relating to just looking for the field name that follows the naming convention but _not_ also looking at the _type_ solve for both the performance concerns _and_ arrive at the same outcome?

**Comment by roji** [comment]
Let's see what @ajcvickers thinks.

**Comment by ajcvickers** [comment]
@taylorchasewhite

> I want to store in my database string values rather than enumeration values so that it is easier for DBAs and other folks working with stored data to understand what is stored in each column.

The way to do this is using a [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions), rather than changing the backing field type. For example:

```C#
public enum RepresentativeType
{
    One,
    Two
}

public class Foo
{
    public RepresentativeType CommitteeType { get; set; }
}
```
```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>().Property(e => e.CommitteeType).HasConversion<string>();
    }
```

This causes the enum values to be stored as strings in the database, while still allowing the property itself to be exposed as an enum in the EF model. This means that the property can still be used in queries. For example:

```C#
context.Foos.Where(e => e.CommitteeType == RepresentativeType.One).ToList();
```

If instead the backing field is mapped directly in EF as @roji suggested, then, from an EF perspective, the _property itself_ would no longer be mapped, only the field. This means the property could not used in a query, and using the field in a query is cumbersome and unintuitive.

> In order to do this, I am using a backing field, as described here.

I'm curious as to what part of this documentation led you to the conclusion that this was the way to change the database type? Knowing this will help us improve the documentation so that others don't also get this impression.

**Comment by taylorchasewhite** [comment]
Sorry for the delay in responding--I was out of town visiting my brother and then forgot to respond!

> I'm curious as to what part of this documentation led you to the conclusion that this was the way to change the database type? Knowing this will help us improve the documentation so that others don't also get this impression.

In regards to how/where I interpreted I could use a backing field for this, I got this information from the [EF Core Backing Fields](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations) page. To be clear, it doesn't state that you can use a backing field that is of a different type from your property, but I read through the backing field, which does exactly what I want, and assumed EF Core would pick up the backing field type rather than the "pass through" property type.

Would this value converter still store the enum "values" as a string value though? I.e. instead of RepresentativeType.Congressman as "Congressman" in the database column, it would store "1" (rather than `1`)?

FWIW, the solution to just `NotMapped` the one property works for me, but it still requires the other to be a public property which I don't love. I stand by this would be a nice enhancement to allow backing fields to be a different type than the mapped property--is there any chance we could keep this as an open enhancement or no?

**Comment by ajcvickers** [comment]
> Would this value converter still store the enum "values" as a string value though? I.e. instead of RepresentativeType.Congressman as "Congressman" in the database column, it would store "1" (rather than 1)?

The default for conversion from enum to string will store "Congressman" in the database. However, it's easy to use your own converter to store whatever representation you want.

> I stand by this would be a nice enhancement to allow backing fields to be a different type than the mapped property--is there any chance we could keep this as an open enhancement or no?

I think to keep this open we would need to understand the advantages of this over using a value converter. Can you explain again what those advantages are?

**Comment by taylorchasewhite** [comment]
> The default for conversion from enum to string will store "Congressman" in the database. However, it's easy to use your own converter to store whatever representation you want.

Cool--thanks--good to know.

> I think to keep this open we would need to understand the advantages of this over using a value converter. Can you explain again what those advantages are?

From an advantage standpoint--the philosophy we try to operate by is to avoid fluent notation where possible and keep the documentation (like ForeignKey, NotMapped, etc.) in the class definition. The rationale is that looking at the class definition it's more clear to a developer what happens on the database side (and that way ApplicationDbContext doesn't get too bloated with a bunch of definitions).
