### ISSUE TITLE
'ModelBuilder' does not contain a definition for 'UseIdentityColumns' 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23069]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ModelBuilder-does-not-contain-a-defini/1201835)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.8.0 preview 3.1]
 modelBuilder
                . UseIdentityColumns() // THIS IS PROPLEM
                . HasAnnotation("Relational:MaxIdentifierLength", 128)
                . HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

When i use add-migration and  the problem is show up

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ModelBuilder' does not contain a definition for 'UseIdentityColumns' and no accessible extension method 'UseIdentityColumns' accepting a first argument of type 'ModelBuilder' could be found (are you missing a using directive or an assembly reference?)	 

.net 5 and visual studio 2019 versiyon16.8.0 preview 3.1

---
#### Feedback Bot on 9/27/2020, 06:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Arthur Vickers [MSFT] solved on 10/2/2020, 11:40 AM, 0 votes: 

<p><code>UseIdentityColumns</code> is contained in the SQL Server package at: <a target='_blank' href="https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/">https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/</a></p>

#### Dylan Zhu [MSFT] solved on 9/28/2020, 09:48 PM, 0 votes: 

<p>Dear customer, thank you for your feedback and I am sorry to hear that you are running into this issue.</p><p>According to your description, you need to install this package: <a target='_blank' href="https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/5.0.0-rc.1.20451.13" target="_blank">Microsoft.EntityFrameworkCore.SqlServer</a> into your project. Then, it will work as normal.</p>

**Comment by gongdao** [comment]
If I am using MySQL, Which package Should I install?

**Comment by ajcvickers** [comment]
@gongdao https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql
