### ISSUE TITLE
Mac QueryContextFactory

### ISSUE THREAD

**Issue by dustinsharp** [dotnet/efcore#2306]
I'm currently working on a Macbook Pro and our web project is having errors when trying to call our API. To my knowledge, this same web project will execute as expected when running on Windows, but I'm getting the following error: 

error   : [Microsoft.Data.Entity.Query.QueryContextFactory] An exception occurred in the data store while iterating the results of a query.
System.InvalidCastException: Cannot cast from source type to destination type.
at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReader.ReadValue<System.DateTime> (int) <0x00051>

If an example is needed, we can work to get a generic program running.

**Comment by natemcmaster** [comment]
Can you provide more detail? 
Which build of EF are you using? 
Which version of Mono are you running?
What are you calling in EF that is producing this error?

**Comment by dustinsharp** [comment]
EF build: 3.0.0-beta4
Mono version: 1.0.0-beta4

I've uploaded a repository that demonstrates this issue: https://github.com/dustinsharp/EFBugRepro

Here are the steps for reproducing the error:
1. Restore EFBugRepro.bak to a SQL Server.
2. Modify EfBugRepro/config.json to have a valid Data connection that points to the newly restored EFBugRepro database. The Data Source, Initial Catalog, User, and ID values have been removed for security purposes.
3. In Terminal, run the following commands:
    cd <path to dowloaded solution>\EfBugRepro\src\EfBugRepro
    source dnvm.sh
    sudo dnu restore
    dnx . kestrel
4. Open browser window to: http://localhost:5000/Home/Test.
5. Following error occurs: "DbUpdateException: An error occurred while updating the entries. See the inner exception for details. 
NotSupportedException: Unknown Type : datetime2"

**Comment by natemcmaster** [comment]
This appears to be a bug in Mono's implementation of SqlClient.  https://bugzilla.xamarin.com/show_bug.cgi?id=24719

What version of Mono are you using? Run ``` mono --version``` to find out.

**Comment by dustinsharp** [comment]
Mono JIT compiler version 4.0.1

**Comment by natemcmaster** [comment]
This is an issue in Mono. We can't fix this. The DateTime2 bug *appears* to be fixed with https://github.com/mono/mono/pull/1773.
