### ISSUE TITLE
Does EntityFrameworkCore SQLite require sqlite.dll to work

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#23065]
Does EntityFrameworkCore SQLite require sqlite.dll to work? Right now our provider requires
the sqlite.dll and the x86 abd x64 are not included with nuget package, so it is harder to
upgrade. If EntityFrameworkCore SQLite nuget package either has the sqlite.dll or does not require then we 
could switch providers.

**Comment by bricelam** [comment]
We build on top of [SQLitePCLRaw](https://github.com/ericsink/SQLitePCL.raw) which distributes SQLite for multiple platforms and architectures as NuGet packages.

**Comment by dgxhubbard** [comment]
Does that mean there is a sqite3.dll. I am not familiar with SQLitePCLRaw.

**Comment by dgxhubbard** [comment]
Is everything needed in the nuget package so there is no need to get a dll from anywhere else?

**Comment by dgxhubbard** [comment]
When I look at a nuget package lib directory I can see the dll(s) in the package. However, when I look at microsoft.entityframeworkcore.sqlite there is one file with the name "_._".

**Comment by dgxhubbard** [comment]
Is this just a placeholder to reference microsoft.entityframeworkcore.sqlite.core?

**Comment by dgxhubbard** [comment]
From nuget the descriptions of the two packages are:

Microsoft.EntityFrameworkCore.Sqlite: SQLite database provider for Entity Framework Core.
Microsoft.EntityFrameworkCore.Sqlite.Core: SQLite database provider for Entity Framework Core. This package does not include a copy of the native SQLite library.

So we would want to use Microsoft.EntityFrameworkCore.Sqlite to get everything included, but we cannot see what is in the package because the file is "_._"

**Comment by ajcvickers** [comment]
@dgxhubbard As is normal for NuGet packages, the EF package depends on other packages which include some of the functionality. In this case, the EF package depends on [SQLitePCLRaw.bundle_e_sqlite3](https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3/):

![image](https://user-images.githubusercontent.com/1430078/97057118-6c5ba380-153f-11eb-982b-12878bb23a41.png)

It is this dependency that brings in the native DLL.
