### ISSUE TITLE
Cannot insert explicit value for identity column in table when IDENTITY_INSERT is set to OFF

### ISSUE THREAD

**Issue by emaborsa** [dotnet/efcore#23073]
Working with EF Core 5.0.0-rc2.20475.6, migrated an old EF 6 .NET project.
I used the scaffolding command to generate the models, it worked and a part of the models are like the following example:

    public class Betrieb {
        public virtual ICollection<Tagesinkassos> Tagesinkassi { get; set; }
        // many other properties and collections
    }

    public class Tagesinkassos {
        public long Id { get; set; }
        // other properties
        public virtual TagesinkassosTagesinkasso TagesinkassosTagesinkasso { get; set; }
        public virtual TagesinkassosPostagesinkasso TagesinkassosPostagesinkasso { get; set; }
        public virtual Betrieb Betrieb { get; set; }
    }
    public class TagesinkassosPostagesinkasso {
        public long Id { get; set; }
        // other properties
        public virtual Tagesinkassos IdNavigation { get; set; }
    }
    public class TagesinkassosTagesinkasso {
        public long Id { get; set; }
        // other properties
        public virtual Tagesinkassos IdNavigation { get; set; }
    }

I moved to EF Core 5 because of the TPT, I edited the models followings

    public abstract class Tagesinkassos {
        public long Id { get; set; }
        // other properties
        public virtual Betrieb Betrieb { get; set; }
    }
    public class TagesinkassosPostagesinkasso : Tagesinkassos {
        // other properties
    }
    public class TagesinkassosTagesinkasso : Tagesinkassos {
        // other properties
    }

Loading data always works.
Update items already present in the Betrieb.Tagesinkassi collection also always works. 
If I try to insert a new one, I get the error in the title `Cannot insert explicit value for identity column in table 'Tagesinkassos' when IDENTITY_INSERT is set to OFF`

I checked the database. The column Tagesinkassos.Id has the Identity Specifcation set to YES. The ids of TagesinkassosPostagesinkasso and TagesinkassosTagesinkasso have the Identity Specifcation set to NO.

Tryied to change from ON to OFF or viceversa, but it tells me that the tables have to de dropped and recreated, I can't do it.
Is there a way to use the TPT model or do I have to keep the generated one?

**Comment by ajcvickers** [comment]
@emaborsa 

> Cannot insert explicit value for identity column in table 'Tagesinkassos' when IDENTITY_INSERT is set to OFF

This typically means that the application is setting the key value (to something other than the CLR default). EF6 would just ignore this key value and throw it away. EF Core assumes that if you set the key value, then that's the key value you want. However, SQL Server (unlike a lot for other databases) does not allow an explicit value to be set for the Identity column, hence this error.

The fix is to either non specify key values explicitly, or to use a column not configured for Identity.

If this doesn't seem to be what you are seeing, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by fruitbatinshades** [comment]
I've been struggling with this error today and had to turn identity off the column in Sql Server. I tried 

`modelBuilder.Entity<AnimalActionsResolvedDBO>().Property(p => p.Id).ValueGeneratedNever();`

but error still throws even though I'd expect that to work.

My use case is that I am moving a record from one table to another and want to keep it's id. In practice I guess that the target tables id column is not a generated identity so EF Core is correct :| Just not an obvious issue on the db side.

**Comment by emaborsa** [comment]
@ajcvickers
 > The fix is to either non specify key values explicitly, or to use a column not configured for Identity.

I am just loading the entity and changing a value, and since I cannot change the Identity configuratin of the column, I fear that I cannot switch to TPT.

**Comment by ajcvickers** [comment]
@emaborsa You can send commands to temporarily switch on IDENTITY_INSERT in the database while you move data, and then re-enable it again afterwards. See https://github.com/dotnet/efcore/issues/2803#issuecomment-159375915 for an example. This is fine to do when you're moving data like this while migrating to a new schema.

**Comment by emaborsa** [comment]
@ajcvickers Do you mean move the data, drop and recreate the tables (actaully 13) and move the data back?

**Comment by ajcvickers** [comment]
@emaborsa I was going off your comment, "My use case is that I am moving a record from one table to another and want to keep it's id." I assumed you were doing this as part of changing your database structure. If instead this is a normal part of application execution, then I don't think it will be possible to do in a robust way when using SQL Server.
