### ISSUE TITLE
Support System.Data.SqlClient library in LINQ to SQL queries

### ISSUE THREAD

**Issue by evannah** [dotnet/efcore#23077]
Hello,

Could you please implement support for System.Data.SqlClient library in LINQ queries that are transformed to SQL?

E.g: SqlFunctions.IsNumeric(String) method
https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.sqlclient.sqlfunctions.isnumeric

Thank you in advance.
Best regards.

**Comment by roji** [comment]
Duplicate of #23078
