### ISSUE TITLE
Part of combined key gets overwritten

### ISSUE THREAD

**Issue by ruwentos** [dotnet/efcore#23071]
EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.5

Perhaps this is even a bug, so let me describe it first.
We have two entities:

```C#
public class Asset
  {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        
        // Relationships
        public ICollection<AssetMixRecord> AssetMixRecords { get; set; }
   }

public class AssetMixRecord
    {
        [Column(TypeName = "decimal(8,7)")]
        public decimal Percentage { get; set; }
        public Guid ChildAssetId { get; set; }

        // Relationships
        public Guid ParentAssetId { get; set; }
    }
```
Where both, **AssetMixRecord.ChildAssetId** and **AssetMixRecord.ParentAssetId** are foreign keys of **Asset.Id**.
The context looks like this.
```C#
modelBuilder.Entity<Asset>()
                .HasMany(a => a.AssetMixRecords)
                .WithOne()                
                .HasForeignKey(r => r.ChildAssetId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);

modelBuilder.Entity<AssetMixRecord>()
                .HasKey(c => new { c.ParentAssetId, c.ChildAssetId })
                .IsClustered();
```
It would be interesting to know how to get both foreign keys in here, but this is not part of the issue right now.
The migration for the AssetMixRecord table then looks like this, as expected.
```C#
migrationBuilder.CreateTable(
                name: "AssetMixRecords",
                columns: table => new
                {
                    ChildAssetId = table.Column<Guid>(nullable: false),
                    ParentAssetId = table.Column<Guid>(nullable: false),
                    Percentage = table.Column<decimal>(type: "decimal(8,7)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AssetMixRecords", x => new { x.ParentAssetId, x.ChildAssetId })
                        .Annotation("SqlServer:Clustered", true);
                    table.ForeignKey(
                        name: "FK_AssetMixRecords_Assets_ChildAssetId",
                        column: x => x.ChildAssetId,
                        principalTable: "Assets",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```
Then I create one Assets (A1) without any **AssetMixRecords** and writes it to the database. This works fine.
Then I create a new Asset object (A2) with one **AssetMixRecord**, where **AssetMixRecord.ChildAssetId** = **A1.Id** and **AssetMixRecord.ParentAssetId** = **A2.Id**.
After Insert the Asset (A2) and AssetMixRecord are created in the database, but the key of the AssetMixRecord is altered now.

ChildAssetId                                                     | ParentAssetId                                                   | Percentage
5D7649D3-41D2-4A73-BF50-F304AD5F46B6 | 5D7649D3-41D2-4A73-BF50-F304AD5F46B6 | 0.2

**ChildAssetId** also got the Id of Asset 2.

I dove into the code and discovered that function **Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetForeignKeyProperties** overwrites the property **ChildAssetId** because it's defined as foreign key.
This is unwanted behavior in this case. In fact, we will strictly avoid that **ChildAssetId** ever holds the Id of any of it's parents.

My questions is thus:

How can we prevent EF from changing the key while still it is a foreign key?
Or did we discover a bug here?

Thanks and regards

S.

**Comment by ajcvickers** [comment]
@ruwentos The EF model for those entity types is this:

```
Model: 
  EntityType: Asset
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Description (string)
      Name (string)
    Navigations: 
      AssetMixRecords (ICollection<AssetMixRecord>) Collection ToDependent AssetMixRecord
    Keys: 
      Id PK
  EntityType: AssetMixRecord
    Properties: 
      ParentAssetId (Guid) Required PK AfterSave:Throw
      ChildAssetId (Guid) Required PK FK Index AfterSave:Throw
      Percentage (decimal) Required
    Keys: 
      ParentAssetId, ChildAssetId PK
    Foreign keys: 
      AssetMixRecord {'ChildAssetId'} -> Asset {'Id'} ToDependent: AssetMixRecords
```

See that `AssetMixRecords` navigation is defined by the FK `ChildAssetId`. This means that if an `AssetMixRecord` is in the `AssetMixRecords` collection, then it's FK must point to the entity that has that collection. So what you are seeing seems like the correct behavior given the model definition.
