### ISSUE TITLE
Add support for System.Data.SqlClient library in LINQ to SQL queries

### ISSUE THREAD

**Issue by evannah** [dotnet/efcore#23078]
Hello,

Could you please implement support for System.Data.SqlClient library in LINQ queries that are transformed to SQL?

E.g: SqlFunctions.IsNumeric(String) method
https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.sqlclient.sqlfunctions.isnumeric

Thank you in advance.
Best regards.

**Comment by roji** [comment]
@evannah unless I'm mistaken, SqlFunctions is part of the old Entity Framework 6 (or even earlier?), and is not supported in Entity Framework Core. EF Core has its own function translations, either from standard .NET methods (e.g. String.StartsWith), or from special methods under `EF.Functions` (this is the EF Core analog to the older SqlFunctions). Take a look at the [SQL Server function mappings doc page](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/functions).

You can request any missing translations by opening issues. Are you asking specifically for a translation to SQL Server's ISNUMERIC? If so, we can use this issue to track that.

**Comment by evannah** [comment]
Hello @roji,
Thank you for your answer, and sorry about my late answer.
Yes, I'd like a translation to SQL Server's ISNUMERIC under EF.Functions, please.
Thank you.
Best regards.
