### ISSUE TITLE
Please consider adding two methods to the DbConnectionInterceptor Creating/Created

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/efcore#23087]
I would like to make use and custom key value pairs on the ConnectionString to configure the mode of operation for the interceptors.

Adding the ConnectionCreating/ConnectionCreated would align with Command Interceptor and allow the developer to override the validation of the ConnectionString etc. internal to the provider to config the interceptors operations/mode

**Comment by roji** [comment]
@3GDXC any reason why you can't just use ConnectionOpening for that?

**Comment by 3GDXC** [comment]
@roji using opening connection looks to happen after the call where the connection string is evaluated/validated and therefore any extra key/value pairs added for configuration of interceptor are causing exceptions; allowing a creating before actually creating the connection object would prevent this and allow interceptors to remove additional key/value pairs from the connection string.

**Comment by roji** [comment]
Is this a duplicate of #23085? See my code sample there.

**Comment by frandazzo** [comment]
Hi, i just tried to nuget the DbConnectionInterceptor (version 7) and tried to override the ConnectionCreating method that was not found. 
It's a very important feature because in this way i can override the way a connection is created (with a custom conneciton factory for example). Any idea?

**Comment by ajcvickers** [comment]
@frandazzo Please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
