### ISSUE TITLE
Error with dotnet ef dbcontext scaffold when the password has a semicolon

### ISSUE THREAD

**Issue by zwloveu** [dotnet/efcore#23082]
Steps to reproduce
I ran:
dotnet ef dbcontext scaffold "server=xx;port=xx;database=xx;uid=xx;pwd=123;1234;" Pomelo.EntityFrameworkCore.MySql -o Models --context-dir . -c xxDbContext -p xx/xx.csproj -s xx/xxcsproj -f

The issue
when I change the password in db without a semicolon and use the pwd=123134, the command work.
when the password has a semicolon, the command did not work.
I use " or  ' around the connectionstring, the command did not work.
I use \ to escape the semicolon in the pwd:  pwd=123\;1234, the command did not work
I use ` before the semicolon in the pwd: pwd=123`;1234, the command did not work

Error message
Format of the initialization string does not conform to specification starting at index xx

**Comment by shbys** [comment]
Resolved.
dotnet ef dbcontext scaffold "server=xx;port=xx;database=xx;uid=xx;pwd='123;1234';"
Please close the issue.
