### ISSUE TITLE
Left Join Null Reference Exception

### ISSUE THREAD

**Issue by prasannapattam** [dotnet/efcore#2310]
I am getting a Null Reference Exception when selecting a column in the left join table. Here is my linq

```
var query1 = from vehicles in dbContext.Vehicles
                      join driver in dbContext.VehicleDrivers on vehicles.VehicleDriverId equals driver.VehicleDriverId into driverJoin
                      from vehicledriver in driverJoin.DefaultIfEmpty()
                      select new VehicleListModel
                      {
                          VehicleId = vehicles.VehicleId,
                          Driver = vehicledriver.DriverName   (getting error as vehicledriver is null)
                      };
            var results = query1.ToList();
```

> stack trace:
>    at lambda_method(Closure , QuerySourceScope )
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at eMine.Lib.Repositories.Fleet.VehicleRepository.VehicleListGet() in D:\Prasanna\Mind\Repos\eMine\eMine\src\eMine\Lib\Repositories\Fleet\VehicleRepository.cs:line 666

As a work around I am using this

`Driver = (vehicledriver == null ? null : vehicledriver.DriverName)`

I am currently using 7.0.0-beta4

P.S. - I looked at issue #1232, but this error is different from that. Hence I posted it as a new issue.

**Comment by rowanmiller** [comment]
This seems correct. `DefaultIfEmpty()` will return `null` when no data is present. Therefore `vehicles` is null and trying to access `vehicles.VehicleId` will throw a NullReferenceException.

The code you have to defensively check if `vehicledriver

**Comment by prasannapattam** [comment]
Sorry. I missed the documentation on null checking
https://msdn.microsoft.com/en-us/library/bb397895.aspx
