### ISSUE TITLE
How can i get unique constraint failed exception while using entiity framework core with mysql 

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/efcore#23105]
I am implementing some Db insertion/updation with entity framework core with mysql using code first apporach
I have a some tables with unique cosntraints and i got error when there is duplicate records. I wanted to implement error handling for duplicate unique cosntraint failure in elegant way but didn't find anything when using mysql
can someone guide me in it.

**Comment by KamranShahid** [comment]
I have a .net core 3.1 application using entity framework core with mysql with model first approach. for some table i have unique constraint. when i save such duplicate value i got exception. i wanted to know any way that i will get exception type or error code on which i can do some handled way of error handling

**Comment by ajcvickers** [comment]
@KamranShahid These kind of exceptions are database-specific and have database-specific error codes. When EF Core throws a `DbUpdateException`, the the database-specific exception is included as the inner exception, so look there for specific error codes.

See also https://github.com/dotnet/runtime/pull/38881, which introduces SqlState as a cross-database way to get more specific information about a failure.

**Comment by KamranShahid** [comment]
there should be some generic thing to identify the duplication exception and handled in pretty way. will check it
