### ISSUE TITLE
FORCEEK hint

### ISSUE THREAD

**Issue by IgorMenshikov** [dotnet/efcore#23101]
## Ask a question

I have a table to keep some operation messages. It has a column to reference to a parent table and index for that column. But sometimes SQL Server gets crazy and uses full index scan by a primary key. I know hint FORCESEEK can help but I do not see a way to specify it. Is there a way to do that?

### Include your code

Entity class is

```C#
[Table("Operation_Message")]
    public class OperationMessage
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("OperationMessageID")]
        public int ID { get; set; }

        [Column]
        public int OperationID { get; set; } // database has index
...
    }
```

with query code like:

```C#
var query = (from i in context.OperationMessage
             where i.OperationID == parameters.OperationID
             select i);
```

It generates a corrent SQL code like:

```SQL
SELECT [o].[OperationMessageID], [o].[OperationID]
FROM [Operation_Message] AS [o]
WHERE ([o].[OperationID] = @__parameters_OperationID_0)
ORDER BY [o].[OperationMessageID]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 3.1
Operating system: Windows Server 2016
IDE: Visual Studio 2019 16.7

**Comment by roji** [comment]
To add a query hint, you can use an interceptor as documented [here](https://github.com/dotnet/EntityFramework.Docs/blob/777e0c0e2b1f8f6f417b3a40c059a92979b4fc6f/entity-framework/core/miscellaneous/events/interception.md#example-command-interception-to-add-query-hints).

However, it's of course better to fully understand the root of the issue instead, i.e. why SQL Server performs the unwanted full index scan.
