### ISSUE TITLE
Events aren't reset when pooled context is reset asynchronously

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#23108]
DbContext.ResetState [sets](https://github.com/dotnet/efcore/blob/main/src/EFCore/DbContext.cs#L759) the context events to null, but ResetStateAsync doesn't. Good motivation for doing #10902, assuming it's OK perf-wise.

/cc @ajcvickers (I can fix this as part of some other work in the area)

**Comment by ajcvickers** [comment]
Poaching...
