### ISSUE TITLE
Interpreting Guid.Empty as null in optional foreign key

### ISSUE THREAD

**Issue by rick-palmsens** [dotnet/efcore#23132]
## Ask a question

I have a `Guid` foreign key that is configured as `.IsRequired(false)`. I want to be able to set this foreign key to `Guid.Empty` to say that it is null.

But when I do try to use it like that, the following query is generated:
```SQL
Microsoft.EntityFrameworkCore.Database.Command:Error: Failed executing DbCommand (1ms) [Parameters=[@p0='d644704c-7735-47a6-cea5-08d87bf854bb' (DbType = String), @p1='2017-07-12T14:33:10' (DbType = String), @p2='00000000-0000-0000-0000-000000000000' (DbType = String), @p3='2020-10-29T10:50:01' (DbType = String), @p4='scan1' (Nullable = false) (Size = 5), @p5='0' (DbType = String), @p6='V;Potential;E' (Nullable = false) (Size = 13)], CommandType='Text', CommandTimeout='30']
INSERT INTO "DataArrays" ("Id", "CreatedOn", "DataSetId", "LastModifiedOn", "Name", "Order", "Unit")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
```

It tries to set `@p2` to `00000000-0000-0000-0000-000000000000`, which results in the database returning a foreign key constraint error because it is not a valid key.

How do I configure EF in such a way that `Guid.Empty` is interpreted as null?

## Version Info
EF Core version: 3.1.9
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Standard 2.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.6

**Comment by rick-de-water** [comment]
I've seem to have gotten a bit further by creating a `ValueConverter` that turns it into a `Guid?`, but this now results in a `NOT NULL constraint failed`, even though I've explicitly set `.IsRequired(false)`.

**Comment by rick-palmsens** [comment]
I've seem to have gotten a bit further by creating a `ValueConverter` that turns it into a `Guid?`, but this now results in a `NOT NULL constraint failed`, even though I've explicitly set `.IsRequired(false)`.

**Comment by ajcvickers** [comment]
@rick-palmsens I think you are asking for `Guid.Empty` to be converted to null in the database, and null in the database to converted to `Guid.Empty` in code. If so, this is tracked by #13850. If this isn't what you want, then can you explain more clearly when the conversions should happen.

**Comment by rick-palmsens** [comment]
Yes that is what I want. I used the hacky setting of "_isNullable" to get around it for now.

**Comment by LemmyK6** [comment]
> Yes that is what I want. I used the hacky setting of "_isNullable" to get around it for now.

Can you send me the modification you did please ? I'm facing the same issue.. :/
