### ISSUE TITLE
EF Core 3.1 - Wrong encoding when using migrations with HasData and Oracle 12c

### ISSUE THREAD

**Issue by BigKid1973** [dotnet/efcore#23131]
The (stripped) enitity class does look like this:
```
    public class AlertTemplate
    {
        public int AlertTemplateId { get; set; }
        public short AlertTemplateVersion { get; set; }
        public string Description { get; set; }
    }
```
In OnModelCreating of my DBContext I have:
```
           modelBuilder.Entity<AlertTemplate>().HasData(
                new AlertTemplate { AlertTemplateId = 0, AlertTemplateVersion = 1, Description = "This generic alert was raised because something wen´t wrong while raising a specific alert. Most probably some kind of misconfiguration.\nThe following additional Information is available for the alert that should have been raised:\n\nAlertId:{0} in Version:{1}\nServer:{2}\nError/Exception:{3}"} );
 ```
After building the migration with ef core tools and using it on my db I see a false character in the description:
```
This generic alert was raised because something wen¿t wrong while raising a specific alert. Most probably some kind of misconfiguration.
The following additional Information is available for the alert that should have been raised:

AlertId:{0} in Version:{1}
Server:{2}
Error/Exception:{3}
```

The issue is with the "´" of "wen´t" wrong...  Besides that I spelled it wrong it get´s translated to wen¿t.
When I read that entry from the db into a string it´s still "... wen¿t... ".

I checked the .cs file the migration creates and the modelBuilder.Insert that is there - it seems fine and the cs file is encoded in UTF-8 (with BOM).
(Please be aware that this is the non stripped InsertData to be sure I do not miss something)
```
            migrationBuilder.InsertData(
                table: "AlertTemplates",
                columns: new[] { "AlertTemplateId", "AlertTemplateVersion", "Description", "Name", "NumberOfValues", "ShortDescription", "StartingAlertLevel" },
                values: new object[] { 0, (short)1, @"This generic alert was raised because something wen´t wrong while raising a specific alert. Most probably some kind of misconfiguration.
The following additional Information is available for the alert that should have been raised:

AlertId:{0} in Version:{1}
Server:{2}
Error/Exception:{3}", "Unspecified Alert Alert", (short)4, "An alert was raised but there was a misconfiguration. So instead this generic alert was raised.", 20 });

```
I do not set encodings or collations anywhere - up to now I relied on EF defaults...

So I tried what happens when I use my entity class to create those entries outside of a migration.
```
dbcontext.AlertTemplates.Add (new AlertTemplate() { ...
dbcontext.SaveChanges();
```
Et voila. Everything fine.
So to me it seems an issue with the InsertData that EF core migration generates...

But I really would like to populate my templates using migration.

**Comment by ajcvickers** [comment]
@BigKid1973 This seems like an issue with the Oracle database provider; please follow up with Oracle on this.
