### ISSUE TITLE
[Q] Cast to integer in expression with DayOfWeek

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#23136]
EF Core version: 3.1.8 and master
Database provider: my own and provider for Firebird

**Context**
```c#
 private sealed class MyContext:TestBaseDbContext
 {
  [Table("TEST_MODIFY_ROW")]
  public sealed class TEST_RECORD
  {
   [Key]
   [Column("TEST_ID")]
   public Int64? TEST_ID { get; set; }

   [Column("COL_TIMESTAMP")]
   public System.DateTime DATA { get; set; }
  };//class TEST_RECORD

  //----------------------------------------------------------------------
  public DbSet<TEST_RECORD> testTable { get; set; }
 };//class MyContext
```

**Test1**

`     var recs=db.testTable.Where(r => r.DATA.DayOfWeek-1==System.DayOfWeek.Tuesday && r.TEST_ID==testID);
`

LOG [2]: Compiling query expression: 
'DbSet<TEST_RECORD>()
    .Where(r => (int)(DayOfWeek)((int)r.DATA.DayOfWeek - 1) == 2 && r.TEST_ID == __testID_0)'

SQL:
```
SELECT "t"."TEST_ID", "t"."COL_TIMESTAMP"
FROM "TEST_MODIFY_ROW" AS "t"
WHERE (CAST((EXTRACT(WEEKDAY FROM "t"."COL_TIMESTAMP") - 1) AS INTEGER) = 2) AND ("t"."TEST_ID" = :__testID_0)
```

**Test2**

`var recs=db.testTable.Where(r => r.DATA.DayOfWeek==System.DayOfWeek.Friday && r.TEST_ID==testID);
`

LOG [1]: Compiling query expression: 
'DbSet<TEST_RECORD>()
    .Where(r => (int)r.DATA.DayOfWeek == 5 && r.TEST_ID == __testID_0)'

SQL:
```
SELECT "t"."TEST_ID", "t"."COL_TIMESTAMP"
FROM "TEST_MODIFY_ROW" AS "t"
WHERE (EXTRACT(WEEKDAY FROM "t"."COL_TIMESTAMP") = 5) AND ("t"."TEST_ID" = :__testID_0)
```

**Question**
How to configure EFCore to avoid generation of CAST( ... AS INTEGER) in TEST1?

It is possible?

My translator of DATA.DayOfWeek creates SqlExpression object with TypeMapping.ClrType=System.Int32.

Thanks.

**Comment by ajcvickers** [comment]
@smitpatel to reference issues.

**Comment by smitpatel** [comment]
#15586

**Comment by ajcvickers** [comment]
@maumar to decide whether to keep this open as a backlog enhancement or not.

**Comment by ajcvickers** [comment]
Closing as duplicate of #15586
