### ISSUE TITLE
Usage of FromSqlRaw/FromSqlInterpolated with param inside HasQueryFilter

### ISSUE THREAD

**Issue by tinquen12** [dotnet/efcore#23146]
Hello,

I have some trouble using the `FromSqlRaw` and `FromSqlInterpolated` method inside `HasQueryFilter`.

Here is a snippet of my `HasQueryFilter`. The `GetPermission` is a TVF returning a list of `AccessRight` objects.

```C#
modelBuilder.Entity<SecurableObject>()
               .HasQueryFilter(e => AccessRights
                   .FromSqlInterpolated($"SELECT * FROM dbo.GetPermission(17, 19, {e.Id})")
                   .Any(el => el.Value == PermissionValue.Allow));
```

For information the _SecurableObject_ method looks like this 

```C#
public class SecurableObject
    {
        [Key]
        public int Id { get; set; }
    }
```

The error message is the following one
"System.InvalidOperationException: variable 'e' of type 'DriverConfigurationApp.Models.Authorization.SecurableObject' referenced from scope '', but it is not defined"

I also tried to use the following method 

```C#
modelBuilder.Entity<SecurableObject>()
               .HasQueryFilter(e => AccessRights
                   .FromSqlRaw("SELECT * FROM dbo.GetPermission(17, 19, {0})", e.Id)
                   .Any(el => el.Value == PermissionValue.Allow));
```

and now the problem is that the generated request have an empty FROM see EXISTS part of the query(Should be the call to the TVF)

```SQL
SELECT [s].[Id], [s].[Discriminator], [s].[Name], [a].[Id], [a].[LinkedObjectId], [a].[Permission], [a].[TargetId], [a].[Value]
FROM [SecurableObject] AS [s]
LEFT JOIN [AccessRights] AS [a] ON [s].[Id] = [a].[LinkedObjectId]
WHERE ([s].[Discriminator] = N'SpecificSecurableObject') AND EXISTS (
    SELECT 1
    FROM 
    WHERE [a0].[Value] = 0)
ORDER BY [s].[Id], [a].[Id]
````

I hope my explanation are clear.

Thank you very much for your help. :)

**Comment by smitpatel** [comment]
`FromSql*` methods are not designed to be used with parameters which are server correlated. The purpose was only bind with client side closure variables. Both above filters violates that so it breaks a lot of process in our code (even when used in normal query directly rather than through query filter)
