### ISSUE TITLE
How to configure a many-many relationship without two navigational properties?

### ISSUE THREAD

**Issue by GurGaller** [dotnet/efcore#23155]
Is there a way to configure a many-many relationship where the second entity has no navigation property?
Looking at the overloads of `CollectionNavigationBuilder<TEntity, TRelatedEntity>.WithMany`, all of them require a property to be passed.
I expected a similar API to `WithOne`, that has an overload with an optional parameter.

Another thing I noticed is that the documenation of the overload that takes a lambda expression states that:

> If no property is specified, the relationship will be configured without a navigation property on the other end of the relationship.

But how can we call that method without a property?
### Example
Let's say we have these two classes:

```C#
public class Product
{
    public int Id { get; set }
    public IEnumerable<Category> Categories { get; set; }
}
public class Category
{
    public int Id { get; set; }
}
```
I expected the following configuration to work, but it doesn't compile:
```C#
public class ProductTypeConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.HasMany(p => p.Categories).WithMany();
    }
}
```

### Provider and version information

EF Core version: 5.0.0-rc.2.20475.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.0 Preview 6.0

**Comment by ajcvickers** [comment]
@GurGaller This is tracked by #3864
