### ISSUE TITLE
[QUESTION] - extensibility to scaffold SQL Server stored procedures via EF CLI ?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#23164]
I wonder if it is at all possible to expose the functionality below as a Nuget package, similar to the .Dacpac scaffolder? (I am of course willing to refactor to make this possible)

 https://github.com/ErikEJ/EFCorePowerTools/tree/master/src/GUI/RevEng.Core/Procedures
(registration for my console app here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/Procedures/SqlServerStoredProcedureServiceCollectionExtensions.cs )

**Comment by ajcvickers** [comment]
@ErikEJ Sounds reasonable. We look forward to the PR. :-)

**Comment by ErikEJ** [comment]
Thanks, Arthur, I was not planning a PR, but asking some extensibility advice.

**Comment by ajcvickers** [comment]
@ErikEJ We were probably a bit hasty; we will look again tomorrow. (I read, "I am of course willing to refactor to make this possible" as volunteering to do a PR, which I now see was me reading it wrong. :-))

**Comment by bricelam** [comment]
You should be able to use the usual design-time MSBuild target that adds `[assembly: DesignTimeServicesReference()]`.

Then you could override the `IDatabaseModelFactory`, `IScaffoldingModelFactory`, and `IMigrationsCodeGenerator` services.

Your IDatabaseModelFactory would derive from `SqlServerDatabaseModelFactory` and add the procedures to the DatabaseModel (either via annotations or by returning a subtype of DatabaseModel).

The IScaffoldingModelFactory would add the procedures (and possibly their entity types) to the EF model.

Finally, the `IMigrationsCodeGenerator` would generate C# code for the EF model.

**Comment by ErikEJ** [comment]
Thanks, @bricelam

**Comment by ErikEJ** [comment]
Assume you mean `IModelCodeGenerator` ?
