### ISSUE TITLE
EntityTypeConfiguration annotation

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23163]
``` C#
[EntityTypeConfiguration(typeof (BlogConfiguration))]
public class Blog
{
    ...
}
```

**Comment by antonAce** [comment]
I would like to take this one if there're no objections.

**Comment by AndriySvyryd** [comment]
@antonAce Go ahead.

**Comment by KaloyanIT** [comment]
Hi there, 
I've been trying to implement this, but I am stuck at applying the Configuration. Where should I do that?
I tried to create a convention, but I can not get EntityTypeBuilder<T>.

**Comment by AndriySvyryd** [comment]
@KaloyanIT You can call `new EntityTypeBuilder((IMutableEntityType)builder.Metadata)` from the convention.

**Comment by markolbert** [comment]
Gee. and think I suggested the exact same thing over a year earlier -- with a write-up on implementing it! -- and didn't get any recognition for doing so :(. 

Next time I'll push a little harder. And who knows? Maybe those reviewing feature requests will be a little more supportive.
