### ISSUE TITLE
Unable to create migrations without Microsoft.EntityFrameworkCore.Design in ASP.NET Core Web layer.

### ISSUE THREAD

**Issue by vbakc** [dotnet/efcore#23168]
### Describe the bug

Unable to run EF Core CLI commands without Microsoft.EntityFrameworkCore.Design package in startup project.

### To Reproduce

Create clean architecture app.
Create solution with 3 projects:

- Core
- Data Access Layer
- Web (ASP.NET project)

Data Access Layer has `Microsoft.EntityFrameworkCore` and `Microsoft.EntityFrameworkCore.Design` packages.
In CLI command specified startup and target projects

```dotnet ef migrations add InitialCreate -s WebApi/WebApi.csproj -p Infrastructure/Infrastructure.csproj```

Web project has reference to both Core and Data Access projects.

Expected to get `ASP.NET Core 3.1`-like behavior (to generate migration), but got:
```
Your startup project 'WebApi' doesn't reference Microsoft.EntityFrameworkCore.Design.
This package is required for the Entity Framework Core Tools to work.
Ensure your startup project is correct, install the package, and try again.
```

### Further technical details
- ASP.NET Core version
`Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]`
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100-rc.2.20479.15/

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]
  5.0.100-rc.2.20479.15 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS Code 1.50.1
- dotnet-ef version
```
Entity Framework Core .NET Command-line Tools
5.0.0-rc.2.20475.6
```

**Comment by ChillerShock** [comment]
@Pilchie @mkArtakMSFT thank you for response.
@ajcvickers @Pilchie @mkArtakMSFT tag me if additional info or other help needed, will try my best.

**Comment by ajcvickers** [comment]
@bricelam I know this was discussed again recently, but I'm not sure where the docs or tracking issue ended up.

**Comment by bricelam** [comment]
I wonder why it worked in 3.1. Did NuGet make changes around development dependencies in 5.0?

**Comment by bricelam** [comment]
Also, last time we discussed, we decided the guidance was pretty clear. All our docs say to install it into the startup project, and the error you get if you don't says it too:

> Your startup project 'WebApi' doesn't reference Microsoft.EntityFrameworkCore.Design.
> This package is required for the Entity Framework Core Tools to work.
> Ensure your startup project is correct, install the package, and try again.

**Comment by ajcvickers** [comment]
@ChillerShock Can you post your csproj files where this is behaving differently in 3.1 and 5.0?

**Comment by ChillerShock** [comment]
@ajcvickers 

`WebApi.csproj`

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
```

`Infrastructure.csproj`

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-rc.2.20475.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.2.20475.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.0-rc2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
```

**Comment by ajcvickers** [comment]
@ChillerShock Your startup project does not reference `Microsoft.EntityFrameworkCore.Design`. This fails for me, as expected, on both 3.1 and 5.0. Can you post the actual projects (with the correct TFM, etc.) where the reference isn't required on 3.1?

**Comment by ChillerShock** [comment]
@ajcvickers
Can [this](https://github.com/ChillerShock/MessageBoardServer) be used as an example?

**Comment by ajcvickers** [comment]
@ChillerShock In that example, the Design package is referenced in Infrastructure like this:

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.1.20451.13" />
``` 

This brings in the design assembly as a full reference, meaning that it can be accessed as a transitive reference from your startup project. However, it also means that the assembly is deployed with your application, which is not needed for the design code.

In your code above, the reference is:

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.2.20475.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

This brings in the design assembly in a way that it will not be shipped with your application. However, it also means that the assembly is not available as a transitive reference. This is why the directions indicate that this package should be installed in the startup project.

**Comment by ChillerShock** [comment]
@ajcvickers thank you very much! Sorry for incorrect/irrelevant issue

**Comment by CorneliusDaniell** [comment]
I had also the same problem when i used separation of concerns (onion architecture in my case). For a straightforward answer of your problem i just drop some screenshots of my approach:
![1](https://github.com/dotnet/efcore/assets/17708662/e778958d-7ca2-40d4-b092-58082446624b)
![2](https://github.com/dotnet/efcore/assets/17708662/17dbef29-f1d8-4de1-9398-e12b16e05bcf)
![3](https://github.com/dotnet/efcore/assets/17708662/3604bf33-1264-4eb4-acab-63c649c2bcea)
ps: i hope it works for the older versions of .net core as well
