### ISSUE TITLE
SqlServer: InvalidOperationException when performing aggregation on empty results after 3.1 -> 5.0 migration

### ISSUE THREAD

**Issue by Berreek** [dotnet/efcore#23174]
After migration from 3.1 to 5.0 following ling query throws exception if **there are no records** that match WHERE statement. In 3.1 it returns result with default values - so in this case MaxLat,MaxLng,MinLng,MinLat would all be 0. I can't find anything about it in breaking changes so consider it as a bug.

#### Generated sql
```sql
SELECT TOP(1) MAX([p].[Lat]) AS [MaxLat], MIN([p].[Lat]) AS [MinLat], MAX([p].[Lng]) AS [MaxLng], MIN([p].[Lng]) AS [MinLng]
FROM [Pins] AS [p] 
WHERE [p].[CompanyId] = @__companyId_0
```

#### Model:
```C#
 public class Pin
{
        public int Id { get; set; } 
        public string CompanyId { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
}
```

#### Linq:
```C#
 var viewPort = await DbContext.Set<Pin>()
                .Where(pin=> pin.CompanyId == companyId)
                .GroupBy(e => 1)
                .Select(g => new {
                    MaxLat = g.Max(t => t.Lat), 
                    MinLat = g.Min(t => t.Lat),
                    MaxLng = g.Max(t => t.Lng), 
                    MinLng = g.Min(t => t.Lng),
                }).FirstOrDefaultAsync(cancellationToken);
```

As a work arround I have to either map in that select to some dedicated class with nullable double like this:
```C#
public class ViewPort
{
   public double? MaxLat { get; set; }
   public double? MinLat { get; set; }
   public double? MaxLng { get; set; }
   public double? MinLng { get; set; }
}
```
Or cast to double? in select:
```C#
 .Select(g => new {
                    MaxLat = (double?)g.Max(t => t.Lat), 
                    MinLat = (double?)g.Min(t => t.Lat),
                    MaxLng = (double?)g.Max(t => t.Lng), 
                    MinLng = (double?)g.Min(t => t.Lng),
                }).
```

### Exception
```
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at lambda_method310(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

### Runtime info
EF Core version: 5.0-rc2
Database provider: SqlServer
Target framework: .net 5.0-rc2
Operating system:
Windows/Linux

**Comment by smitpatel** [comment]
Min/Max throws exception when applied over non-nullable type and sequence contains no element (since the result is not defined). This was a bug in 3.1 which was fixed in 5.0.
What is the expected result without using nullable?

**Comment by Berreek** [comment]
> What is the expected result without using nullable?

Not sure. As API consumer I found it a little bit tricky that I have to explicit convert it to nullable to make it work. 
Is it possible in such case to return a default value from `FirstOrDefault` if sequence is empty instead of getting the exception?

**Comment by ajcvickers** [comment]
@Berreek We don't believe returning the default value is appropriate, since this would imply that the max is zero, which could be a valid actual result from the query if rows are present, and so cannot be used as a sentinel in the general case.
