### ISSUE TITLE
Entities in Many-To-Many relationship missing

### ISSUE THREAD

**Issue by hauke-w** [dotnet/efcore#23175]
The attached project contains a unit test that demonstrates a bug where a collection does not contain all entities of the many-to-many relationship. The assertion in line 100 of UnitTest1.cs fails.
[EFCore5ManyToManyBug.zip](https://github.com/dotnet/efcore/files/5477646/EFCore5ManyToManyBug.zip)

The following class diagram illustrates the entity classes:
![model](https://user-images.githubusercontent.com/9463839/97913685-f5988480-1d4e-11eb-8d43-afd37ecde990.png)
Class _Module_ has a composite key.

The following object diagram illustrates the Module entities used in the unit test.
![objects](https://user-images.githubusercontent.com/9463839/97915738-4198f880-1d52-11eb-8bf7-aec0a6165fe6.png)
The already mentioned assertion in line 100 fails because the dependency Module1->Module2 in Realm2 is lost. I.e. Module1.Dependencies does not contain Module2. The similar dependencies in Realm1 are correcly loaded.
The data in the database is correct:
![db](https://user-images.githubusercontent.com/9463839/97915945-976da080-1d52-11eb-9bc3-582ca36ef847.PNG)

### Include provider and version information

EF Core version: 5.0.0-rc.2.20475.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.0 Preview 6.0

**Comment by ajcvickers** [comment]
Note for triage: I haven't got to the bottom of this yet, but it appears to be an issue with explicit/lazy loading of collections. Using eager-loading with Include does not generate the error.

**Comment by ajcvickers** [comment]
@hauke-w After further investigation I don't think there is an EF bug here. Instead, I think there is an issue with how the test is doing verification. Specifically, this code:

```C#
static void VerifyDependencies(Realm realm, int[][] allDependencies)
{
    var modules = realm.InstalledModules.OrderBy(it => it.Id).ToList();

    for (int i = 0; i < modules.Count; i++)
    {
        var module = modules[i];
        var actualDependencies = module.Dependencies.ToList();
        var expectedDependencies = GetDependencies(i, modules, allDependencies);

        // When another db context is used than the one that was used for creating the entities,
        // for Realm2/Module1 the next assertion fails with following message:
        // CollectionAssert.AreEquivalent failed. The number of elements in the collections do not match. Expected:<2>. Actual:<1>.
        CollectionAssert.AreEquivalent(expectedDependencies, actualDependencies);

        var actualDependent = module.DependentModules.ToList();
        var expectedDependent = GetDependent(i, modules, allDependencies);
        CollectionAssert.AreEquivalent(expectedDependent, actualDependent);
    }
}
```

Before the first pass through the loop, EF is tracking the following entities:

```
Module {RealmId: 1, Id: Module0} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module1} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module2} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module3} Unchanged FK {RealmId: 1}
Realm {Id: 1} Unchanged
```
That is, the modules associated with the first realm are but none of the many-to-many relationships have been loaded.

On the first iteration through the loop, the relationships are loaded for fist Module. That is, any case where the first Module is on either side of the relationship This results in the following, since only one relationship matches:

```
Module {RealmId: 1, Id: Module0} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module1} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module2} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module3} Unchanged FK {RealmId: 1}
Realm {Id: 1} Unchanged
ModuleModule (Dictionary<string, object>) {DependenciesRealmId: 1, DependenciesId: Module1, DependentModulesRealmId: 1, DependentModulesId: Module0} Unchanged FK {DependenciesRealmId: 1, DependenciesId: Module1} FK {DependentModulesRealmId: 1, DependentModulesId: Module0}
```
At this point the method attempts to do verification that all expected relationships have been loaded, when only the relationships for the first module have been loaded. This verification fails.

Letting the loop run so that all relationships between modules are loaded results in:

```
Module {RealmId: 1, Id: Module0} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module1} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module2} Unchanged FK {RealmId: 1}
Module {RealmId: 1, Id: Module3} Unchanged FK {RealmId: 1}
Realm {Id: 1} Unchanged
ModuleModule (Dictionary<string, object>) {DependenciesRealmId: 1, DependenciesId: Module1, DependentModulesRealmId: 1, DependentModulesId: Module0} Unchanged FK {DependenciesRealmId: 1, DependenciesId: Module1} FK {DependentModulesRealmId: 1, DependentModulesId: Module0}
ModuleModule (Dictionary<string, object>) {DependenciesRealmId: 1, DependenciesId: Module2, DependentModulesRealmId: 1, DependentModulesId: Module1} Unchanged FK {DependenciesRealmId: 1, DependenciesId: Module2} FK {DependentModulesRealmId: 1, DependentModulesId: Module1}
ModuleModule (Dictionary<string, object>) {DependenciesRealmId: 1, DependenciesId: Module3, DependentModulesRealmId: 1, DependentModulesId: Module1} Unchanged FK {DependenciesRealmId: 1, DependenciesId: Module3} FK {DependentModulesRealmId: 1, DependentModulesId: Module1}
ModuleModule (Dictionary<string, object>) {DependenciesRealmId: 1, DependenciesId: Module3, DependentModulesRealmId: 1, DependentModulesId: Module2} Unchanged FK {DependenciesRealmId: 1, DependenciesId: Module3} FK {DependentModulesRealmId: 1, DependentModulesId: Module2}
```
If verification is instead done after loading all these relationships, then it passes. (This is also why the issue appeared to disappear yesterday when I switched to eager loading with Include.)
