### ISSUE TITLE
reference nulled after SaveChanges

### ISSUE THREAD

**Issue by dagid4** [dotnet/efcore#23180]
I use following version of EF Core:

    Microsoft.EntityFrameworkCore.Sqlite 5.0.0-rc.2.20475.6

I have following classes:

    public class Garage
    {
        public int Id { get; set; }

        public List<Car> Cars { get; set; } = new List<Car>();
    }

    public class Car
    {
        public int Id { get; set; }
    }

    public class Ferrari : Car
    {
        public Special Special { get; set; }
    }

    public class Special
    {
        public int Id { get; set; }
    }

    public class MyContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite($"Filename=my.db");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Garage>().ToTable("Garage");

            modelBuilder.Entity<Car>().ToTable("Car");

            modelBuilder.Entity<Ferrari>().ToTable("Ferrari");

            modelBuilder.Entity<Special>().ToTable("Special");
        }
    }

I have following code:

    await using var context = new MyContext();
    
    await context.Database.EnsureCreatedAsync();
    
    var garage = new Garage();
    
    context.Add(garage);
    
    await context.SaveChangesAsync();
    
    var ferrari = new Ferrari();
    
    garage.Cars.Add(ferrari);
    
    ferrari.Special = new Special();
    
    Console.WriteLine($"Special reference is null: {(ferrari.Special == null ? "YES" : "NO")}");
    
    await context.SaveChangesAsync();
    
    Console.WriteLine($"Special reference is null: {(ferrari.Special == null ? "YES" : "NO")}");

Reference to Special is getting nulled. The output is following:

    Special is null: NO
    Special is null: YES

You can try yourself: https://github.com/dagid4/EfCoreBug

In database everything is ok. Do you have please any idea how to solve this problem? Or is it just a bug?

It can be related to derived classes. If you move the Special property from Ferrari into Car, it is working.

**Comment by ajcvickers** [comment]
I can reproduce this on the 5.0 daily build; it does not repro when switched to TPH. Could be an update pipeline or change tracking bug.
/cc @AndriySvyryd

**Comment by AndriySvyryd** [comment]
@ajcvickers When propagating the store-generated value to the FK we set the FK store-generated value to `null`, due to https://github.com/dotnet/efcore/issues/22603. When accepting the values we overwrite the propagated value with the "store-generated" `null`

**Comment by ajcvickers** [comment]
@AndriySvyryd So, does TPT make this common enough that we should patch for #22603?

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes. In TPH there are no store-generated values in the Ferrari entry at that point so we don't have to reset them to `null`, however in TPT the Car part is inserted first and that triggers the creation of the store-generated Sidecar, leading to the situation above.

I haven't tried it, but inserting a dependent with 2 principals would likely hit this without TPT.

**Comment by dagid4** [comment]
Thank you guys, this was driving me crazy. I've tried to build branch Issue23180 and it is now working! Hope it will get into daily builds soon.

**Comment by tdeeb** [comment]
This looks like the issue I'm having on https://github.com/dotnet/efcore/issues/23158. Looking forward to the daily build!

**Comment by tivtag** [comment]
@AndriySvyryd Will your fix be available in some nightly Alpha/Beta channel?
I believe that I am also hitting this problem.

**Comment by AndriySvyryd** [comment]
@tivtag We don't publish nightly packages for patch releases to avoid overloading the NuGet source. You can try building the package yourself from the `release/5.0` branch after https://github.com/dotnet/efcore/pull/23186 is pushed or wait until December when we'll release 5.0.1
