### ISSUE TITLE
How to fix the group by linq query, currently failing - Client side GroupBy is not supported

### ISSUE THREAD

**Issue by peterkapena** [dotnet/efcore#23190]
```
  var rtn =
                from fav in _context.AdvertFavorite
                join advert in _context.Adverts on fav.AdvertID equals advert.AdvertID
                join blob in _context.Blobs on advert.AdvertID equals blob.AdvertID
                join user in _userManager.Users on advert.UserID equals user.Id
                where fav.UserID == usrid
                group new { blob, user, advert } by new { advert.AdvertID } into grp
                select grp;

            var rtn1 = rtn.ToList();

**Comment by MarcoLoetscher** [comment]
[LINQ queries are no longer evaluated on the client](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client)
If a query can't be fully translated, then either rewrite the query in a form that can be translated, or use AsEnumerable(), ToList(), or similar to explicitly bring data back to the client where it can then be further processed using LINQ-to-Objects.

**Comment by peterkapena** [comment]
I could not find a LINQ query solution. but this is what I came up with. This is a bad memory performance but seems I have no choice.

 `var list = new List<dynamic>();
            var rtn =
                (from fav in _context.AdvertFavorite
                 join advert in _context.Adverts on fav.AdvertID equals advert.AdvertID
                 join user in _userManager.Users on advert.UserID equals user.Id
                 where fav.UserID == usrid
                 select new { user, advert }).ToList();`

`
            rtn.ForEach((r) =>
            {
                var blob = _context.Blobs.Where(b => b.AdvertID == r.advert.AdvertID).FirstOrDefault();
                list.Add(new { blob, r.user, r.advert, });
            });
return rtn`
