### ISSUE TITLE
ArgumentOutOfRangeException for split query with owned types

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23211]
Query:
```C#
context.Set<Root>()
    .AsSplitQuery()
    .Include(e => e.OptionalChildren)
    .OrderBy(e => e.Id)
    .Single(r => r.AlternateId == Fixture.RootAK);
```

`Root.RequiredSingle` and `Root.RequiredSingleAk` are owned.

>    System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the 
    List`1.get_Item(Int32 index)
    SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery) line 1480
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 76
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 74
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 73
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 73
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 73
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    RelationalQueryTranslationPostprocessor.Process(Expression query) line 45
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 177
    Database.CompileQuery[TResult](Expression query, Boolean async) line 72
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 114
    <>c__DisplayClass9_0`1.<Execute>b__0() line 98
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 78
    QueryCompiler.Execute[TResult](Expression query) line 94
    EntityQueryProvider.Execute[TResult](Expression expression) line 81
    GraphUpdatesTestBase`1.LoadOptionalGraph(DbContext context) line 649

**Comment by smitpatel** [comment]
Are owned objects mapped to different tables?

**Comment by AndriySvyryd** [comment]
`Root.RequiredSingle` is table-splitting
`Root.RequiredSingleAk` is mapped to a different table

**Comment by ajcvickers** [comment]
@smitpatel What's the `servicing-consider` status of this?
