### ISSUE TITLE
Migration name filter

### ISSUE THREAD

**Issue by lugospod** [dotnet/efcore#23222]
EF Core uses a class Migration, and if you add a new migration with name "Migration" it will  break the build.

dotnet ef migrations add Migration

results with Circular base class dependency involving 'Migration' and 'Migration' 

I recommend that "migrations add" adds a validation for this... 

### Include stack traces

Migrations/20201106105308_Migration.cs(6,26): error CS0146: Circular base class dependency involving 'Migration' and 'Migration' [/opt/app/src/src/NM.DAL/NM.DAL.csproj]
Migrations/20201106105308_Migration.cs(8,33): error CS0115: 'Migration.Up(MigrationBuilder)': no suitable method found to override [/opt/app/src/src/NM.DAL/NM.DAL.csproj]
Migrations/20201106105308_Migration.cs(167,33): error CS0115: 'Migration.Down(MigrationBuilder)': no suitable method found to override [/opt/app/src/src/NM.DAL/NM.DAL.csproj]
Migrations/20201106105308_Migration.Designer.cs(16,33): error CS0115: 'Migration.BuildTargetModel(ModelBuilder)': no suitable method found to override [/opt/app/src/src/NM.DAL/NM.DAL.csproj]

### Include provider and version information

EF Core version: 3.1.9
Database provider: Postgresql
Target framework: NET 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.7

**Comment by ajcvickers** [comment]
Note from triage: we should add this and other similar conflicts to the check we already have. But low priority.

**Comment by wreuel** [comment]
How could I help with that?

**Comment by ZephArvanitis** [comment]
Would this line/file be the right place to add this check?

https://github.com/dotnet/efcore/blob/a1216b1de00f7443a38f8efe3387adfc5d7c21d0/src/ef/Commands/MigrationsAddCommand.cs#L12-L20

**Comment by ajcvickers** [comment]
@KevRitchie Yes.
