### ISSUE TITLE
Entity attached as Added when identifying FK has default value

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23226]
See https://github.com/dotnet/efcore/blob/main/src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs#L1560

Note the the principal property might not be store-generated.

**Comment by umitkavala** [comment]
When there is assignee; it means @ajcvickers working on it? 
I'd like take my next PR :) which labeled issues should take first?

**Comment by ajcvickers** [comment]
@umitkavala No, it just means that it's in my bucket of things to fix. Feel free to work on this; remember to include tests in any PR that you send.

**Comment by umitkavala** [comment]
Ok. Sure I'll add tests as well. I did my first practice with @AndriySvyryd for #23322

**Comment by umitkavala** [comment]
If key is set which means record is exist otherwise its **Added** 
To decide IsKeySet we look default :
```
public virtual (bool IsGenerated, bool IsSet) IsKeySet
        {
            get
            {
                var isGenerated = false;
                var keyProperties = ((EntityType)EntityType).FindPrimaryKey().Properties;

                // ReSharper disable once ForCanBeConvertedToForeach
                // ReSharper disable once LoopCanBeConvertedToQuery
                for (var i = 0; i < keyProperties.Count; i++)
                {
                    var keyProperty = keyProperties[i];
                    var keyGenerated = keyProperty.ValueGenerated == ValueGenerated.OnAdd;

                    if ((HasTemporaryValue(keyProperty)
                            || HasDefaultValue(keyProperty))
                        && (keyGenerated || keyProperty.IsForeignKey()))
                    {
                        return (true, false);
                    }

                    if (keyGenerated)
                    {
                        isGenerated = true;
                    }
                }

                return (isGenerated, true);
            }
        }
```


could you elaborate the problem?
FK default value = CLR default value or user-defined default value (like default value on principal record)

I think I should start writing test to see problem. what do you think?

**Comment by ajcvickers** [comment]
@umitkavala I haven't investigated this in depth yet, so I'm not sure at this point what the exact root cause or solution is.
