### ISSUE TITLE
Query: consider support for include on derived types in form of entities.Include(e => e.Reference as Derived).ThenBy(d => d.NavigationOnDerived)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#23237]
Currently, for include on derived we support the following pattern:

```cs
entities.Include(e => e.Reference).ThenInclude(r => (r as Derived).NavigationOnDerived)
```

we could consider support for the following:

```cs
entities.Include(e => e.Reference as Derived).ThenInclude(d => d.NavigationOnDerived)
```

The second form would presumably only work for reference navs (whereas pattern we support works for both reference and collection).

Also the second form could be interpreted as having a different semantics, i.e. only include the navigation which is of type Derived (and leaving the other types as null?).

Issue has been reported here: https://github.com/dotnet/efcore/issues/18248

**Comment by ajcvickers** [comment]
Note from triage: we don't currently plan to support this pattern. If you need it, then please comment as to why the supported pattern doesn't work for you and we may consider re-opening.
