### ISSUE TITLE
Can't build for netcoreapp3.1 - Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0'

### ISSUE THREAD

**Issue by kimimaru4000** [dotnet/efcore#23234]
## File a bug

I have a .NET Core 3.1 application using C# 7.3 that I'm trying to include a custom EF Core build for, specifically the [Issue23180 branch](https://github.com/dotnet/efcore/tree/Issue23180). I have included my cloned repo into the .csproj like so:

```
<ItemGroup>
    <ProjectReference Include="\efcore\src\EFCore\EFCore.csproj" />
    <ProjectReference Include="\efcore\src\EFCore.Design\EFCore.Design.csproj" />
    <ProjectReference Include="\efcore\src\EFCore.Proxies\EFCore.Proxies.csproj" />
</ItemGroup>
```
Whenever I build my project, I keep getting an error about it not being able to find **Microsoft.CodeAnalysis** in the **EFCore.Proxies** and **EFCore.Relational** projects. The EF Core branch I checked out builds just fine with the build.sh script, so I'm not sure what's going on here. I have tried including private assets for **EFCore.Design** and manually specifying the version of **Microsoft.CodeAnalysis** with no luck.

```
CSC : error CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /efcore/artifacts/bin/EFCore.Analyzers/Release/netstandard2.0/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/efcore/src/EFCore.Proxies/EFCore.Proxies.csproj]
CSC : error CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /efcore/artifacts/bin/EFCore.Analyzers/Release/netstandard2.0/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/efcore/src/EFCore.Relational/EFCore.Relational.csproj]
```

### Include provider and version information

EF Core version: [Issue23180](https://github.com/dotnet/efcore/tree/Issue23180) - sometime after 5.0.0-rc.2.20475.6
Database provider: System.Data.SQLite
Target framework: .NET Core 3.1
Operating system: Linux Mint 20 Ulyana
IDE: CLI

**Comment by ajcvickers** [comment]
@tdeeb The build script installs a .NET SDK local to the repo. We typically try to keep this SDK to something publicly available--I believe we are currently using .NET 5.0 RC2. You'll likely need to use this same SDK for your build.

**Comment by tdeeb** [comment]
Is there a way to use a different version of .NET to build with? If I specify `-useDefaultDotnetInstall` it still doesn't work.

If not, how does the NuGet package work with my .NET Core 3.1 project, but not my custom build?

**Comment by ajcvickers** [comment]
@tdeeb You might be able to get things to build with another SDK if you hack things, but generally the build system is setup to use a given SDK. The resulting NuGet packages target .NET Standard 2.1 regardless of the SDK used to build them.

**Comment by tdeeb** [comment]
Installing the .NET 5 preview SDK made the builds work; thank you!

However, now my application cannot load SQLite when applying migrations with `DbContext.Migrate()`, while the NuGet package release has no issues. **None of my own code has changed at all.**

I'm including the following projects into my own code:
```
- EFCore.Sqlite.Core
- EFCore.Design.csproj
- EFCore.Proxies.csproj
```
Exception:
```
System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.raw.get_Provider()
   at SQLitePCL.raw.sqlite3_open_v2(utf8z filename, sqlite3& db, Int32 flags, utf8z vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open() in Microsoft.Data.Sqlite.Core/SqliteConnection.cs:line 240
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected) in EFCore.Relational/Storage/RelationalConnection.cs:line 662
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected) in EFCore.Relational/Storage/RelationalConnection.cs:line 641
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected) in EFCore.Relational/Storage/RelationalConnection.cs:line 557
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists() in EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs:line 92
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists() in EFCore.Relational/Migrations/HistoryRepository.cs:line 134
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration) in EFCore.Relational/Migrations/Internal/Migrator.cs:line 112
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade) in EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs:line 40
```

And here is how I'm configuring it:
```
protected override void OnConfiguring(DbContextOptionsBuilder options)
{
    options.UseLazyLoadingProxies().UseSqlite($"Filename={Datasource}", ContextBuilder);
    base.OnConfiguring(options);
}

private void ContextBuilder(SqliteDbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.MigrationsAssembly(System.Reflection.Assembly.GetExecutingAssembly().FullName);
}
```

**Comment by ajcvickers** [comment]
@tdeeb You need `EFCore.Sqlite` if you're not going to supply your own binary.

**Comment by tdeeb** [comment]
Building EFCore.Sqlite does not produce a DLL and it complains about this when I include the project. The output is only a "EFCore.Sqlite.deps.json" file, and I don't see any code in the EFCore.Sqlite project after cloning.

Worth noting that when I build, I get `dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.` I have several zlib packages installed (zlib1g, zlib1g-dev, zlib1g:i386, and zlibc) so I'm not sure what it's looking for here.

**Comment by tdeeb** [comment]
Closing because the original issue was resolved.
