### ISSUE TITLE
Failed to download package inside docker

### ISSUE THREAD

**Issue by Judhianto** [dotnet/efcore#23249]
I have problem when build and publish docker.
It always tried to download nuget packages and failed.
I already tried to download all the packages required  in a local folder and set nuget package source to that folders, but when in build process, it always tried to get the packages form internet -- and fails.

 There're some output result:

`
#11 [build 3/7] COPY [Duren.csproj, ]
#11 CACHED

#12 [build 4/7] RUN dotnet restore "./Duren.csproj"
#12 2.152   Determining projects to restore...
#12 61.02   Failed to download package 'Microsoft.Data.SqlClient.1.1.3' from 'https://api.nuget.org/v3-flatcontainer/microsoft.data.sqlclient/1.1.3/microsoft.data.sqlclient.1.1.3.nupkg'.
#12 61.02    Received an unexpected EOF or 0 bytes from the transport stream.
#12 70.21   Failed to download package 'System.Globalization.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.globalization/4.3.0/system.globalization.4.3.0.nupkg'.
#12 70.21    Received an unexpected EOF or 0 bytes from the transport stream.
#12 71.48   Failed to download package 'System.Text.Encoding.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.text.encoding/4.3.0/system.text.encoding.4.3.0.nupkg'.
#12 71.48    Received an unexpected EOF or 0 bytes from the transport stream.
#12 72.15   Failed to download package 'System.Text.Encodings.Web.4.5.0' from 'https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/4.5.0/system.text.encodings.web.4.5.0.nupkg'.
#12 72.15    Received an unexpected EOF or 0 bytes from the transport stream.
`
there is dockerfile content:

`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Duren.csproj", ""]
RUN dotnet restore "./Duren.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Duren.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Duren.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Duren.dll"]`

**Comment by ajcvickers** [comment]
@Judhianto This doesn't look like it is directly related to EF. I suggest you follow up with the [NuGet team](https://github.com/NuGet).
