### ISSUE TITLE
What limitations for shared entity types

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#23243]
Hello all

EF Core 5.0.0-rc.2.20475.6

Having this model :

```
  public class Nation
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Person> Persons { get; set; }
    }

    public class Person
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public virtual Nation Nation {get;set;}
    }

```

Is there a way to achive something like this?

```
public class MyDBContext : DbContext
    {
        public MyDBContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer(@"XXX");
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.SharedTypeEntity<Person>("BadPerson").HasKey(itm => itm.ID);
            modelBuilder.SharedTypeEntity<Person>("GoodPerson").HasKey(itm => itm.ID);
            modelBuilder.SharedTypeEntity<Nation>("BadNation").HasKey(itm => itm.ID);
            modelBuilder.SharedTypeEntity<Nation>("BadNation").HasMany(itm => itm.Persons).WithOne(itm=>itm.Nation); // i'd like to refer to BadPerson Table 
            modelBuilder.SharedTypeEntity<Nation>("GoodNation").HasKey(itm => itm.ID);
            modelBuilder.SharedTypeEntity<Nation>("GoodNation").HasMany(itm => itm.Persons).WithOne(itm=>itm.Nation); // i'd like to refer to GoodPerson Table
        }
    }

```
Besides this case, is there a way I can found some documentation that explain more What are the limitations of shered Types?

Thanks

**Comment by smitpatel** [comment]
`Nation.Persons` navigation is used in both relationships so later configuration will remove it from first one causing the first relationship to be recreated.

**Comment by GLuca74** [comment]
In this test, i get an exception here :


`modelBuilder.SharedTypeEntity<Nation>("BadNation").HasMany(itm => itm.Persons).WithOne(itm => itm.Nation); // i'd like to refer to BadPerson Table 
`

that is the first relation configuration
The exception is:

`System.InvalidOperationException: 'The entity type 'Person' cannot be added to the model because its CLR type has been configured as a shared type.'`


then, this means that i can not have a relation to a Shared Type Entity?

**Comment by ajcvickers** [comment]
@AndriySvyryd to follow up.

**Comment by AndriySvyryd** [comment]
There is currently no API to configure a navigation to a shared type entity type, this is tracked by https://github.com/dotnet/efcore/issues/23255
