### ISSUE TITLE
EF Core 5.0 Many-to-Many generating singular table names and plural column names

### ISSUE THREAD

**Issue by mhosman** [dotnet/efcore#23258]
Example:

```
public class Customer
{
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Color> Colors { get; set; }
}

public class Color
{
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Customer> Customers { get; set; }
}
```

This is generating a table CustomerColor (singular) with column names in plural: ColorsId, CustomersId

**Comment by ajcvickers** [comment]
@mhosman EF isn't actually pluralizing or singularizing anything here. The table names come from your entity type names. (If you had DbSet properties for these types, then the names would come from those.) The FK names are based on the navigation properties on each end of the relationship.

**Comment by mhosman** [comment]
Thanks for the response. There's a way to change this manually?

**Comment by ajcvickers** [comment]
Yes: https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many

**Comment by mhosman** [comment]
Sorry, not able to find how to change column names without specifying the CLR class (only was able to find a way to change the table name in the docs, no the column names).

Anyway... this behaviour is kind of weird... Since this are always collections, if resulting values are based on the navigation properties, you'll always get pluralized values (unless you name a collection as singular).

**Comment by mhosman** [comment]
Sorry @ajcvickers, not able to find how to change column names without specifying the CLR class (only was able to find a way to change the table name in the docs, no the column names).

Anyway... this behaviour is kind of weird... Since this are always collections, if resulting values are based on the navigation properties, you'll always get pluralized values (unless you name a collection as singular).

**Comment by AndriySvyryd** [comment]
@mhosman You need to use this overload of `UsingEntity`:
```C#
        modelBuilder.Entity<Customer>()
            .HasMany(p => p.Colors)
            .WithMany(p => p.Customers)
            .UsingEntity<Dictionary<string, object>>(
                "CustomerColor",
                j => j
                    .HasOne()
                    .WithMany()
                    .HasForeignKey(pt => pt.ColorId),
                j => j
                    .HasOne()
                    .WithMany()
                    .HasForeignKey(pt => pt.CustomerId));
```

We use the navigation names in the generated names to make it easier to distinguish them for self-referencing relationships and have a simple naming rule.

**Comment by mhosman** [comment]
Great @AndriySvyryd thank you very much!! Worked like a charm. Closing!!

**Comment by ajcvickers** [comment]
@AndriySvyryd Do we have anything tracking making this easier? I don't (yet) think we made the wrong choice on FK property names, but I do think that many people will want to change them.

**Comment by AndriySvyryd** [comment]
@ajcvickers https://github.com/dotnet/efcore/issues/21535
