### ISSUE TITLE
GET LIST IN SESSION OnModelCreatingPartial

### ISSUE THREAD

**Issue by Galandre99** [dotnet/efcore#23251]
Hi, I need to use method 'HasQueryFilter' based on user permission. I actually done this 

```
IEnumerable<int?> _establishmentIdList = _httpContext.Session.Get<IEnumerable<int?>>("establishmentId");


            if (_establishmentIdList != null && _establishmentIdList.Count() > 0 && _establishmentIdList.FirstOrDefault().HasValue)
            {
                modelBuilder.Entity<RegEmployee>().HasQueryFilter(f => _establishmentIdList.Contains(f.EstablishmentId));

                modelBuilder.Entity<RegProduct>().HasQueryFilter(f => f.RelProductEstalishments.Any(a => _establishmentIdList.Contains(a.EstablishmentId)));

                modelBuilder.Entity<RegEstablishment>().HasQueryFilter(f => _establishmentIdList.Contains(f.Id));
            }
```
but session is always empty. Any idea how to get session after login?

Thanks all.

EF Core version: 3.0

**Comment by ajcvickers** [comment]
@Galandre99 EF Core typically builds the model once and then caches it. This is required for performance. This means that your model building code is only being called for the first DbContext instance, and then never again.

Instead you should make `establishmentId` a field on your DbContext. This allows _the same query filter_ to be used with different DbContext instances, taking the `establishmentId` from that instance.

See https://review.docs.microsoft.com/en-us/ef/core/querying/filters
Also, we have an issue open to make this clearer: https://github.com/dotnet/EntityFramework.Docs/issues/773
And an issue open to improve the experience with query filters: https://github.com/dotnet/efcore/issues/21459

Finally, just an FYI that EF Core 3.0 is [out-of-support](https://review.docs.microsoft.com/en-us/ef/core/what-is-new/).

**Comment by Galandre99** [comment]
@ajcvickers thank you so much. I resolved it.
