### ISSUE TITLE
decimal is rounded instead of truncated in 5.0

### ISSUE THREAD

**Issue by DouglasRiddle** [dotnet/efcore#23259]
### Include your code

With EF Core 5.0 decimal values are being rounded instead of truncated. A sample value for ```decimal``` of ```3.7475``` is saved into a T-SQL ```decimal(18,2)``` field as ```3.74``` in EF Core 3.1.10 and ```3.75``` in EF Core 5.0

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Server 2012 R2
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
@DouglasRiddle See https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.0.md#enable-decimal-truncation-behavior-conditionally

**Comment by DouglasRiddle** [comment]
@ajcvickers Thanks for the quick reply! Just for my own confirmation, is the old 3.1 behavior (truncating) considered a bug and the 5.0 behavior (rounding) the correct way going forward?

**Comment by ajcvickers** [comment]
@DouglasRiddle Yes. Actually, when using any version of EF Core (or indeed EF6) you would in most cases see the rounding behavior. With EF Core 5.0 and SqlClient 2.0 the behavior should be rounding by default across the board. This also matches what SQL Server does when precision and scale are not specified on the parameter.
