### ISSUE TITLE
get wrong sql when i use two times group by in ef core 5.0

### ISSUE THREAD

**Issue by chensiel** [dotnet/efcore#23265]
The sql generated by ef 5.0 is wrong and is different to which generated by ef 3.1 when I use two times group by.
Someone can test it?

**Comment by smitpatel** [comment]
Can you share a repro code? Your query and model configuration?

**Comment by chensiel** [comment]
@smitpatel hello, code is below

**Comment by chensiel** [comment]
[using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using EFCore.BulkExtensions;

namespace Tests
{
    public class Test1
    {
        public class Trade
        {
            [Key]
            public string TradeId { get; set; }
            public ICollection<Order> OrderList { get; set; }
        }
        public class Order
        {
            [Key]
            public string OrderId { get; set; }
            public string WayCom { get; set; }
            public string WayBill { get; set; }
            public Trade Trade { get; set; }
        }
        public class Shipping
        {
            [Key]
            public string ShippingId { get; set; }
            public string WayCom { get; set; }
            public string WayBill { get; set; }
            public string ShippingLotNo { get; set; }
            public string ShippingDate { get; set; }
        }

        public class AppDbContext : DbContext
        {
            private LoggerFactory loggerFactory;
            public DbSet<Trade> Trade { get; set; }
            public DbSet<Order> Order { get; set; }
            public DbSet<Shipping> Shipping { get; set; }

            public AppDbContext()
            {
                loggerFactory = new LoggerFactory();
            }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                if (!optionsBuilder.IsConfigured)
                {
                    optionsBuilder.UseSqlite("Data Source=:memory:;");
                }
                base.OnConfiguring(optionsBuilder);
                optionsBuilder.UseLoggerFactory(loggerFactory);
            }
        }

        public void Test()
        {
            var db = new AppDbContext();
            var query = from q1 in db.Order
                        join j1 in db.Shipping on new { q1.WayCom, q1.WayBill } equals new { j1.WayCom, j1.WayBill }
                        select new
                        {
                            j1.ShippingLotNo,
                            q1.Trade.TradeId
                        } into q2
                        group q2 by new { q2.ShippingLotNo, q2.TradeId } into g1
                        select new { g1.Key.ShippingLotNo, g1.Key.TradeId } into q3
                        group q3 by new { q3.ShippingLotNo } into g2
                        select new { g2.Key.ShippingLotNo, Count = g2.Count() };
            var sql = query.ToParametrizedSql().Item1;
        }
    }
}
](url)

**Comment by chensiel** [comment]
sql from ef core 5.0


SELECT "s"."ShippingLotNo", COUNT(*) AS "Count"
FROM "Order" AS "o"
INNER JOIN "Shipping" AS "s" ON (("o"."WayCom" = "s"."WayCom") OR ("o"."WayCom" IS NULL AND "s"."WayCom" IS NULL)) AND (("o"."WayBill" = "s"."WayBill") OR ("o"."WayBill" IS NULL AND "s"."WayBill" IS NULL))
LEFT JOIN "Trade" AS "t" ON "o"."TradeId" = "t"."TradeId"
GROUP BY "s"."ShippingLotNo", "t"."TradeId", "s"."ShippingLotNo"

**Comment by chensiel** [comment]
sql from ef core 3.1

SELECT "t0"."ShippingLotNo", COUNT(*) AS "Count"
FROM (
    SELECT "s"."ShippingLotNo", "t"."TradeId"
    FROM "Order" AS "o"
    INNER JOIN "Shipping" AS "s" ON (("o"."WayCom" = "s"."WayCom") OR ("o"."WayCom" IS NULL AND "s"."WayCom" IS NULL)) AND (("o"."WayBill" = "s"."WayBill") OR ("o"."WayBill" IS NULL AND "s"."WayBill" IS NULL))
    LEFT JOIN "Trade" AS "t" ON "o"."TradeId" = "t"."TradeId"
    GROUP BY "s"."ShippingLotNo", "t"."TradeId"
) AS "t0"
GROUP BY "t0"."ShippingLotNo"

**Comment by chensiel** [comment]
@smitpatel here is a repro [https://github.com/chensiel/Tests](url)

results in ef 3.1 is correct

![ef 3 1](https://user-images.githubusercontent.com/29729100/98969214-9ec44500-24dc-11eb-9af6-32af622577d7.png)

results in ef 5.0 is incorrect

![ef 5 0](https://user-images.githubusercontent.com/29729100/98969217-9ec44500-24dc-11eb-945a-75a41ea9e2cb.png)
