### ISSUE TITLE
API xref errors

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#23260]
**Microsoft.EntityFrameworkCore.Design/OperationExecutor+GetMigrations**
 Cross reference not found: 'Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext'.
**Microsoft.EntityFrameworkCore.Design/OperationExecutor+UpdateDatabase**
 Cross reference not found: 'Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext'.
**Microsoft.EntityFrameworkCore.Diagnostics/DbTransactionInterceptor**
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
**Microsoft.EntityFrameworkCore.Diagnostics/IDbTransactionInterceptor**
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
**Microsoft.EntityFrameworkCore.Diagnostics/ISaveChangesInterceptor**
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
**Microsoft.EntityFrameworkCore.Diagnostics/SaveChangesInterceptor**
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
**Microsoft.EntityFrameworkCore.Infrastructure/CosmosDbContextOptionsBuilder**
 Cross reference not found: 'CosmosDbContextOptionsExtensions.UseCosmos{TContext}'.
**Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder**
 Cross reference not found: 'HasIndex'.
**Microsoft.EntityFrameworkCore.Metadata.Builders/OwnedNavigationBuilder2**
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
**Microsoft.EntityFrameworkCore.Metadata/LazyLoaderParameterBindingFactory**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Metadata.LazyLoaderParameterBindingFactory.IsLazyLoader(System.Type)'.
**Microsoft.EntityFrameworkCore.Metadata/SqlQueryExtensions**
 Cross reference not found: 'RelationalEntityTypeBuilderExtensions.ToSqlQuery'.
**Microsoft.EntityFrameworkCore.Metadata/StoreObjectIdentifier**
 Cross reference not found: 'RelationalEntityTypeBuilderExtensions.ToSqlQuery'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/CrossApplyExpression**
 Cross reference not found: 'Table'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/CrossJoinExpression**
 Cross reference not found: 'Table'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/ExceptExpression**
 Cross reference not found: 'Source1'.
 Cross reference not found: 'Source2'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/InnerJoinExpression**
 Cross reference not found: 'Table'.
 Cross reference not found: 'JoinPredicate'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/IntersectExpression**
 Cross reference not found: 'Source1'.
 Cross reference not found: 'Source2'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/LeftJoinExpression**
 Cross reference not found: 'Table'.
 Cross reference not found: 'JoinPredicate'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/OuterApplyExpression**
 Cross reference not found: 'Table'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/SelectExpression**
 Cross reference not found: 'Alias'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/UnionExpression**
 Cross reference not found: 'Source1'.
 Cross reference not found: 'Source2'.
**Microsoft.EntityFrameworkCore.Query/IMemberTranslator**
 Cross reference not found: 'MemberExpression.Type'.
**Microsoft.EntityFrameworkCore.Query/IMemberTranslatorProvider**
 Cross reference not found: 'MemberExpression.Type'.
**Microsoft.EntityFrameworkCore.Query/QueryableMethods**
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Sum'.
 Cross reference not found: 'Queryable.Sum'.
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Sum'.
 Cross reference not found: 'Queryable.Sum'.
**Microsoft.EntityFrameworkCore.Storage/ReaderColumn**
 Cross reference not found: 'System.Func{DbDataReader, Int32[], T}'.
 Cross reference not found: 'System.Func{DbDataReader, Int32[], T}'.
**Microsoft.EntityFrameworkCore.Storage/RelationalTypeMappingSource**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo@)'.
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo@)'.
**Microsoft.EntityFrameworkCore.Storage/TypeMappingSource**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.TypeMappingSourceBase.FindMapping(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo@)'.
**Microsoft.EntityFrameworkCore.Storage/TypeMappingSourceBase**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.TypeMappingSourceBase.FindMapping(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo@)'.
**Microsoft.EntityFrameworkCore/DbContext**
 Cross reference not found: 'SaveChanges'.
 Cross reference not found: 'SaveChangesAsync'.
 Cross reference not found: 'SaveChanges'.
 Cross reference not found: 'SaveChangesAsync'.
 Cross reference not found: 'SaveChanges'.
 Cross reference not found: 'SaveChangesAsync'.
**Microsoft.EntityFrameworkCore/IDbContextFactory`1**
 Cross reference not found: 'EntityFrameworkServiceCollectionExtensions.AddDbContextPool'.
**Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions**
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
**Microsoft.EntityFrameworkCore/RelationalEntityTypeExtensions**
 Cross reference not found: 'RelationalEntityTypeBuilderExtensions.ToSqlQuery'.
**Microsoft.EntityFrameworkCore/SaveChangesEventArgs**
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
**Microsoft.EntityFrameworkCore/SaveChangesFailedEventArgs**
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
**Microsoft.EntityFrameworkCore/SavingChangesEventArgs**
 Cross reference not found: 'DbContext.SavingChanges'.

**Comment by smitpatel** [comment]
More details https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C9404999c-ee71-fa20-1125-146463fb4d5a%5CPullRequest%5C202011102153444580-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tEA3IWf011y82mCHlL8eOI7Y79pgcH3Z79Iwkt4f1RY%3D&st=2020-11-10T21%3A52%3A41Z&se=2020-12-11T21%3A57%3A41Z&sp=r

**Comment by AndriySvyryd** [comment]
@smitpatel Update link pls

**Comment by smitpatel** [comment]
https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C9404999c-ee71-fa20-1125-146463fb4d5a%5CCommit%5C202109150938270221-main%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T17%3A51%3A33Z&sr=b&sp=r&sig=OSkoeq5vZ6N0QxKR37hwSXKN9xFMTxiQDNar4hwpEdc%3D

**Comment by smitpatel** [comment]
"poaching"

**Comment by roji** [comment]
Enjoy yourself :rofl:

**Comment by smitpatel** [comment]
- Currently "O:" doesn't work on docs site, only "Overload:" works but putting that in source creates compile time error. Raised issue with docs to support "O:" prefix for cref.
- Docs don't generate page for members which are implicitly coming from base class so referencing them will require using the base class type.
- We should avoid to use T:/M:/P: prefix as much as we can so that we know at source code level if things are not working correctly. The place where it is fine to use would be place where the type is not available - referencing relational method in docs in core assembly.
- We should cref to types which are not part of .NET Core. Docs will try to create a link for it but since it is not .NET core (e.g. NTS types), it will cause error because the doc page for it doesn't exist in our system. If we want to reference their type then we should use URLs rather than cref with type.

Only pending one for now is
```
Cross reference not found: 'System.Func{DbDataReader, Int32[], T}'.
 Cross reference not found: 'System.Func{DbDataReader, Int32[], T}'.
```
I couldn't figure out right away to generate the array type. See attempts here https://github.com/dotnet/EntityFramework.ApiDocs/pull/102
Array like above works for method parameters but not inside generic type parameters. Feel free to experiment in above PR.

**Comment by roji** [comment]
@smitpatel is it feasible to somehow integrate a docs gen pass in our pipeline so as to fail builds which create issues?
