### ISSUE TITLE
Unexpected behaviour with OrderBy

### ISSUE THREAD

**Issue by vladtreny** [dotnet/efcore#23267]
Hello,
I am currently migrating app based on MariaDB database. I found a potential issue.

For example, this query
```
var query = await _db.Production
                .OrderByDescending(q => q.Id)
                .Where(q => q.Industry > 0)
                .Select(m => m.FromCompany)
                .Distinct()
                .Take(10)
                .ToListAsync()
```

EF generates:
```
  SELECT DISTINCT `j`.`from_company`
  FROM `production` AS `j`
  WHERE (`j`.`Industry` > 0)
  LIMIT @__p_0
```

I expected to see

`ORDER BY production.id DESC`

Which I did at the begging

`.OrderByDescending(q => q.Id)`

However, it was ignored silently. I think, in that case, there are should be at least a warning or even an exception. 
ORMs in other languages allow that order. May lead to unexpected behaviour.

**Comment by ErikEJ** [comment]
Which provider and EF Core versions?

**Comment by jobriver** [comment]
EF core 3.1+ (I think, it is the same for all version)
Pomelo.entityframeworkcore

**Comment by smitpatel** [comment]
The contract of Distinct, does not guarantee the ordering hence once Distinct is applied the inner order by is gone. If ordering is important after applying Distinct then please add OrderBy operation after Distinct.

**Comment by jobriver** [comment]
> The contract of Distinct, does not guarantee the ordering hence once Distinct is applied the inner order by is gone. If ordering is important after applying Distinct then please add OrderBy operation after Distinct.

If you add OrderBy after Distinct, you will get a nested query that is not desirable, since it is possible to create one query.
Nested query, in that case, is by 15-20x slower than the first one.

Yes, I understand, the correct order is not guaranteed in that query, but it works correctly in mysql/mariadb and not that critical (in my case). ORMs in other languages allow such order.

I would expect a warning in console or exception in such case, instead of silence. Also, in similar cases.

**Comment by smitpatel** [comment]
It may work for in SQL databases but that is not what LINQ query is representing and we are translating LINQ query here. Further, while it works on database now, it can change at any point too since the order is not guaranteed.

**Comment by ajcvickers** [comment]
@smitpatel Could we warn for this?

**Comment by ajcvickers** [comment]
Decision from triage: warn when an OrderBy is discarded because it is superseded by a Distinct.

**Comment by smitpatel** [comment]
Bringing this to design meeting. While the ordering is removed after distinct, it is not fully "discarded" in all cases. We need to discuss when do we show the warning (and if it indeed provides a value).

**Comment by smitpatel** [comment]
Design meeting notes:
- We will not warning in all occurrences where `Distinct` erases ordering.
- We will warn specifically in `Distinct` is being applied to `SelectExpression` which has ordering but not Limit/Offset.
- We will update the message for `LogRowLimitingOperationWithoutOrderBy` to indicate that ordering must come after `Distinct` and it may have been erased if specified before.
