### ISSUE TITLE
Can Scaffold-DbContext generate entities with comments for all DBProvider?

### ISSUE THREAD

**Issue by Flithor** [dotnet/efcore#23279]
copy from:
https://github.com/dotnet/efcore/issues/19113

I'm use [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql).

but it cannot generate xml comments for entity property by Scaffold-DbContext in current release version.
and the contributor said this feature is in EF Core 6.0 https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1219

Uh... really?

**Comment by ErikEJ** [comment]
This is available with EF Core Power Tools today.

**Comment by Flithor** [comment]
Not works, I cannot add a MySql ODBC connection

**Comment by ErikEJ** [comment]
@Flithor I think it will work if you follow the instrictions here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#reverse-engineer---workflow (use the MySQL Visual Studio tools, not ODBC)
