### ISSUE TITLE
Entity Framework Migrations: Constructor of Configuration always called

### ISSUE THREAD

**Issue by altmann** [dotnet/efcore#2327]
I run command Enable-Migrations, but I don't change the database initializer neither in code nor in the config file. If I run the application the constructor of the class Configuration is called. Is this a bug? Details see stackoverflow article http://stackoverflow.com/questions/30627146/entity-framework-migrations-constructor-of-configuration-called-always

**Comment by rowanmiller** [comment]
This is by-design, if you have migrations enabled then the initializer will use them to create the database.

**Comment by altmann** [comment]
Ok, but I DON'T use the MigrateDatabaseToLatestVersion database initializer. I use the default database initializer (CreateDatabaseIfNotExists). So why the constructor of class Configuration is called?

**Comment by rowanmiller** [comment]
CreateDatabaseIfNotExists uses migrations if it is enabled (to check compatibility and to create the database if it doesn't exist). If you don't have migrations then it will use an internal mechanism to create the database and check compatibility.

**Comment by rowanmiller** [comment]
CreateDatabaseIfNotExists won't apply pending migrations though... it will only use migrations (to create the database) if the database doesn't exist.

**Comment by altmann** [comment]
Ahh okay. And if I have multiple Configuration classes in my assembly (for example TestConfiguration and ProductionConfiguration), which configuration is used or is the internal mechanism used?

**Comment by rowanmiller** [comment]
> If I have multiple Configuration classes in my assembly (for example TestConfiguration and ProductionConfiguration), which configuration is used or is the internal mechanism used?

Good question... @ajcvickers do you know off the top of your head

**Comment by ajcvickers** [comment]
You should not have two DbConfiguration classes in your assembly; there must be no more than one so that EF tooling can find and use it. Note that this is not directly related to database initializers--EF will attempt to find and use your DbConfiguration class when EF initializes regardless of whether or not that initialization includes kicking off a database initializer.

**Comment by altmann** [comment]
Ok, currently I have two Configuration classes in my assembly. One configuration for production (AutomaticMigration disabled, no data seeded) and one configuration for testing (AutomaticMigration enabled, testdata seeded). Is this a bad idea? What is the alternative?

**Comment by divega** [comment]
Just to confirm, you are refering to Migrations.Configuration classes as opposed to DB configuration classes, correct?

**Comment by altmann** [comment]
To be correct, its the Configuration which is inherited from System.Data.Entity.Migrations.DbMigrationsConfiguration. 

In my code for example: 

     internal sealed class ProductionConfiguration : DbMigrationsConfiguration<EfMigrationTest2.AppDbContext>

**Comment by divega** [comment]
Thanks for clarifying that. The constraint described by @ajcvickers applies to DbConfiguration which is a different class. I am not sure which DbMigrationsConfiguration would be picked. @rowanmiller might be able to answer from the top of his mind.

**Comment by rowanmiller** [comment]
Looking at the code I think you should get an exception if there are multiple migration configurations. It's probably best not to use the CreateIfNotExists initializer in this case. MigrateToLatestVersion initializer allows you to specify which configuration to use. Or you could just switch off initializers if you don't want anything done with the database.

**Comment by altmann** [comment]
Ok, thanks to all people who help to clarify that.
