### ISSUE TITLE
The ability to easily turn off the Huminizer/Pluralizer functionality in EFCore 5.0

### ISSUE THREAD

**Issue by JYasgarYTGI** [dotnet/efcore#23280]
Scaffold-DbContext

The functionality of automatically creating table models that are de-pluralized is counter-intuitive for applications that are detached from the database. All of my applications are powered by Micro Services and use custom DTOs in the Process/Service Layer. In our apps, database tables are always plural, DTO's are always singular. Now that the DB entities are singular, they conflict with most of the business object names and we have to spend many hours setting up aliased usings and modifying code that has been working for years to add the alias to every business object name.

What is the easiest way to use the database names for objects and have absolutely no changes to naming conventions? -UseDatabaseName seems to only work for the collection names in the Context, not the individual table/object names. I would have hoped that an idea like this would have been opt in, not opt out.

**Comment by smitpatel** [comment]
This could help mitigating the behavior. https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#pluralizer

**Comment by JYasgarYTGI** [comment]
> This could help mitigating the behavior. ...

Thanks for the quick reply.

Just tried it and it seems to disable that singularization of object names!
