### ISSUE TITLE
try to find IsDependentToPrincipal in Navigations  Metadata but it's not there

### ISSUE THREAD

**Issue by umar-daraz-codedistrict** [dotnet/efcore#23283]
unable to find the IsDependentToPrincipal()  in navigation enry 
foreach (var entry in context.ChangeTracker.Entries())
			{
			
						foreach (var navigationEntry in entry.Navigations.Where(n => !n.Metadata.))//.IsDependentToPrincipal()))
						{
						}
}

**Comment by umar-daraz-codedistrict** [comment]
current version is 5.0.0

**Comment by ajcvickers** [comment]
@umar-daraz-codedistrict See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#inavigationbase-replaces-inavigation-in-some-apis-to-support-skip-navigations

You will likely need to just add a cast to INavigation.

**Comment by ashokgovindaraj** [comment]
Hi,  I'm upgrading to .Net 6. I got error.
'INavigationBase' does not contain a definition for 'IsDependentToPrincipal' and the best extension method overload 'NavigationExtensions.IsDependentToPrincipal(INavigation)' requires a receiver of type 'INavigation'

How to cast to INavigation. 

foreach (var navEntry in entry.Navigations.Where(n => !n.Metadata.IsDependentToPrincipal())) {
}

**Comment by ertanhasani** [comment]
@ashokgovindaraj By looking at the documentation its saying to use use `IReadOnlyNavigation.IsOnDependent` instead.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.navigationextensions.isdependenttoprincipal?view=efcore-6.0

Try this:
```
entry.Navigations.Where(x => !((IReadOnlyNavigation)x.Metadata).IsOnDependent);
```

**Comment by ashokgovindaraj** [comment]
@ertanhasani Thank you so much for your reply. Now its working
