### ISSUE TITLE
Porting EF Core to the Modern C++ x20

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/efcore#23287]
Dear EF Team, Do you considering porting EF Core 5 to the Modern C++ ? Nowadays C++ 20 has all (Reflection, Safer Pointers, Metaclasses) to be it possible.

Benefits:
C++ has zero-overhead abstraction.
Modern C++ needs a good ORM.
 .NET has 3 year support lifecycle, C++ library has much more.

**Comment by ajcvickers** [comment]
@IrakliLomidze It would certainly be interesting to see how the patterns in EF Core could be adapted to other programming languages. That being said, this is not something we plan to invest in. However, EF Core is open-source, so feel free to experiment and see how things turn out. I can't say that we will be able to help much, but if you make any progress, then do let us know.
