### ISSUE TITLE
Many to Many: Insert/Edit associations without CLR class.

### ISSUE THREAD

**Issue by mhosman** [dotnet/efcore#23293]
Now that we don't need the CLR classes anymore to use Many-To-Many I have a new issue:

- Let's say we have an entity with **Users** and another one with **Categories**. Many Users can have multiple Categories, and multiple Categories can be associated to multiple Users.
- Based on this new functionality, EF Core automatically will create a users_categories table.
- Now I want to update the user with id 1 and instead of categories 1 and 2, I want that user to have categories 1, 2, 3 and 4.
- Using PATCH, this will update the whole "Categories" row, but I just wanted to assign the id to the customer, not to modify the data inside Categories.
- I tested with Attach. It seems to be working fine when I try to add data, not the same luck when trying to edit data. I get an error saying that is already being tracked.

The big question here is, how can I update the associated data (CLR class) now we don't have direct access to that? Thanks!

**Comment by ajcvickers** [comment]
@mhosman Can you elaborate more on, "but I just wanted to assign the id to the customer, not to modify the data inside Categories."

**Comment by mhosman** [comment]
Sorry, I already found the information here: https://www.youtube.com/watch?v=W1sxepfIMRM&list=PLdo4fOcmZ0oX-DBuRG4u58ZTAJgBAeQ-t&index=32

Thanks

**Comment by mhosman** [comment]
Sorry, I reopened this... I'm still not able to add data to the associated table using just ID's (without retrieving the data first). I left a project with some notes to understand what's happening. The idea is just to insert associations without retrieving data.
With EF 3.1 I was able to do this with the CLR class. Right now I don't know how to do it without the CLR class.

[WebApplication2.zip](https://github.com/dotnet/efcore/files/5538208/WebApplication2.zip)

**Comment by albrtogomez** [comment]
I have this exact question also. When I was using net core 3.1 I could insert associations just with the ID because there was an explicit join table. How can we accomplish this with the new many to many functionality?

**Comment by ajcvickers** [comment]
@mhosman @albrtogomez In the code from the attached project, after the first call to SaveChanges, the context is tracking the following entities:

```
Community {Id: 1} Unchanged
  Id: 1 PK
  Name: 'Community 1'
  Persons: <null>
Community {Id: 2} Unchanged
  Id: 2 PK
  Name: 'Community 2'
  Persons: <null>
Person {Id: 1} Unchanged
  Id: 1 PK
  Name: 'Albert'
  Communities: <null>
Person {Id: 2} Unchanged
  Id: 2 PK
  Name: 'John'
  Communities: <null>
Person {Id: 3} Unchanged
  Id: 3 PK
  Name: 'Kristin'
  Communities: <null>
```

(You can see this in the debugger or with `Console.WriteLine(context.ChangeTracker.DebugView.LongView);`)

Executing the query does change the state of anything here.

However, now this code:

```C#
var community = new Community {Id = 1};
context.Communities.Attach(community);
```

is now attempting to track another instance of `Community {Id = 1}`, and hence you get the exception.

Now to answer your question, it depends again on what trying to do. If the intention is to do an update after query as a separate unit-of-work, then create a new context instance after the first SaveChanges and the attached code will work as expected. If the intention is to do all of this in a single unit-of-work, then since the `Community` are already tracked there is no reason to attach dummy instances like this.

I have tried to help here, but I have a suspicion your attached code did not really demonstrate the issue you're having. If so, I'll be happy to take a look at a modified example. Please do consider making use of the `ChangeTracker.DebugView` to understand what's going on inside the change tracking--I think it will help.

**Comment by mhosman** [comment]
Hey @ajcvickers thank you very much for your response!! That was helpfull but... I don't know how to do that for a PATCH (when you are already tracking an instance of an entity (also tryed with Attach but is not working).
I'll attach the same project with a new example so you can understand what's my issue... 

Thanks again!!
[WebApplication2.zip](https://github.com/dotnet/efcore/files/5543983/WebApplication2.zip)

**Comment by tinchoel10** [comment]
Same question. I think you should improve documentation to explain how to do this with many-to-many.

**Comment by mhosman** [comment]
Yes I agree that maybe the docs should be more specific about this. Don't know if we are able to Patch with the second example I posted.

**Comment by albrtogomez** [comment]
`public class Community
{
    public int Id { get; set; }
    public string Name { get; set; }

	// Before in EF Core 3.1
	public ICollection<CommunityPerson> Members { get; } = new List<CommunityPerson>();
	
	// Now in EF Core 5
    public ICollection<Person> Members { get; } = new List<Person>();
}

public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }

    public ICollection<Community> Memberships { get; } = new List<Community>();
}

public class CommunityPerson
{
    public int CommunityId { get; set; }
    public int PersonId { get; set; }
}

public class CommunitiesContext : DbContext
...
   
public static class Program
{
    public static void Main()
    {
        using (var context = new CommunitiesContext())
        {
            var arthur = new Person { Name = "Arthur" };
            var wendy = new Person { Name = "Wendy" };

            context.AddRange(arthur, wendy);

            context.SaveChanges();
        }

		// EF Core 3.1
        using (var context = new CommunitiesContext())
        {
			//  I was used to join existing entities only by receiving its ID
			int arthurId = 1;
			int wendyId = 2;
			
			// So I fill the new community entity just with thouse IDs using the explicit join table (CommunityPerson)
            var efCommunity = new Community { Name = "EF Community"	};
			efCommunity.Members.AddRange(
				new CommunityPerson { PersonId = arthurId },
				new CommunityPerson { PersonId = arthurId });
				
			// The CommunityId was automatically filled by EF when I call savechanges
			
            context.Add(efCommunity);

            context.SaveChanges();
        }
		
		// EF Core 5
		using (var context = new CommunitiesContext())
        {
			// Same situation, I receive IDs but now I have to retrieve Persons entities before adding them to the new Community
			int arthurId = 1;
			int wendyId = 2;
			
			var people = context.Person.Where(p => p.Id == arthurId || p.Id == wendyId).ToList();
			
            var efCommunity = new Community {Name = "EF Community"};
			efCommunity.Members.AddRange(people);
			
            context.Add(efCommunity);

            context.SaveChanges();
        }	
    }
}
`
The difference now is that as far as I know I must have to query the database before create the new community, in EF 3.1 this was not necesary. Is this the expected way to do this in EF 5? Any recommendations in this cases?

**Comment by albrtogomez** [comment]
I will try to illustrate my problem, hope it is clear enough:

```csharp
public class Community
{
    public int Id { get; set; }
    public string Name { get; set; }

    // Before in EF Core 3.1
    public ICollection<CommunityPerson> Members { get; } = new List<CommunityPerson>();
	
    // Now in EF Core 5
    public ICollection<Person> Members { get; } = new List<Person>();
}

public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }

    public ICollection<Community> Memberships { get; } = new List<Community>();
}

public class CommunityPerson
{
    public int CommunityId { get; set; }
    public int PersonId { get; set; }
}

public class CommunitiesContext : DbContext
...
   
public static class Program
{
    public static void Main()
    {
        using (var context = new CommunitiesContext())
        {
            var arthur = new Person { Name = "Arthur" };
            var wendy = new Person { Name = "Wendy" };

            context.AddRange(arthur, wendy);

            context.SaveChanges();
        }

	// EF Core 3.1
        using (var context = new CommunitiesContext())
        {
	    //  I was used to join existing entities only by receiving its ID
	    int arthurId = 1;
	    int wendyId = 2;
			
	    // So I fill the new community entity just with thouse IDs using the explicit join table (CommunityPerson)
            var efCommunity = new Community { Name = "EF Community"	};
	    efCommunity.Members.AddRange(
	        new CommunityPerson { PersonId = arthurId },
	        new CommunityPerson { PersonId = arthurId });
				
	    // The CommunityId was automatically filled by EF when I call savechanges
			
            context.Add(efCommunity);

            context.SaveChanges();
        }
		
	// EF Core 5
	using (var context = new CommunitiesContext())
        {
	    // Same situation, I receive IDs but now I have to retrieve Persons entities before adding them to the new Community
            int arthurId = 1;
	    int wendyId = 2;
			
	    var people = context.Person.Where(p => p.Id == arthurId || p.Id == wendyId).ToList();
			
            var efCommunity = new Community {Name = "EF Community"};
	    efCommunity.Members.AddRange(people);
			
            context.Add(efCommunity);

            context.SaveChanges();
        }	
    }
}
```

The difference now is that as far as I know I must have to query the database before create the new community, in EF 3.1 this was not necessary. 

Is this the expected way to do this in EF 5? Any recommendations in this cases?

**Comment by mhosman** [comment]
@albrtogomez please take a look at the first example I uploaded. You can attach the entities without retrieving from database. The only problem I have is with the second example: not able to PATCH even using attach.

**Comment by mhosman** [comment]
@ajcvickers I know you are with a lot of work and sorry for the insistence, but there is any way to do this? Thanks!!!

**Comment by ajcvickers** [comment]
@mhosman The key is to make sure not to create new instances of entities that are already tracked. For example:

```C#
using (var context = new DataContext())
{
    // Let's get Person with ID 1
    var person = context.Persons.Include(c => c.Communities).Where(p => p.Id == 1).FirstOrDefault();

    // Create a JSONPatch document to replace communities
    JsonPatchDocument<Person> patchDocument = new JsonPatchDocument<Person>();

    var community1 = context.Communities.Local.FirstOrDefault(e => e.Id == 1)
                     ?? new Community {Id = 1};
    
    var community2 = context.Communities.Local.FirstOrDefault(e => e.Id == 2)
                     ?? new Community {Id = 2};

    patchDocument.Operations.Add(new Operation<Person>
    {
        op = "replace",
        path = "/Communities",
        value = new List<Community> {community1, community2}
    });

    // Apply changes to object
    patchDocument.ApplyTo(person);

    context.SaveChanges();
}
```

**Comment by mhosman** [comment]
Hey @ajcvickers thanks for your response. The thing about this is that I need to ask inside the patchDocument for those Community id's... it's like the simplicity of the patch operation itself is broken... I think is kind of tricky to do this. The same for inserts, y nedd a loop to Attach. Maybe this should be improved somehow in the future. Closing for now. Thank you very much!
