### ISSUE TITLE
Please append QuerySqlGenerator.VisitAndWrapIntoBrackets

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#23315]
Hello,

Could you append to QuerySqlGenerator a **protected** method with follow code:

```c#
                    var requiresBrackets = RequiresBrackets(sqlExpression);

                    if (requiresBrackets)
                    {
                        _relationalCommandBuilder.Append("(");
                    }

                    Visit(sqlExpression);

                    if (requiresBrackets)
                    {
                        _relationalCommandBuilder.Append(")");
                    }
```
?

This method will be useful in your own code (QuerySqlGenerator) and derived classes.

Thanks.

**Comment by ajcvickers** [comment]
@roji @maumar @smitpatel to follow up.

**Comment by roji** [comment]
@dmitry-lipetsk the problem with your suggestion, is that inside the brackets we typically visit some *part* of the SQL expression, and not the expression itself. For example, [in VisitSqlBinary](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L522) we visit the left side, and then the right side:

```c#
var requiresBrackets = RequiresBrackets(sqlBinaryExpression.Left);

if (requiresBrackets)
{
    _relationalCommandBuilder.Append("(");
}

Visit(sqlBinaryExpression.Left);

if (requiresBrackets)
{
    _relationalCommandBuilder.Append(")");
}
```

So I don't see how this would be useful. That being said, if it helps your own QuerySqlGenerator, feel free to add that there.

**Comment by dmitry-lipetsk** [comment]
Hello @roji :)

Sorry I didn't describe the use of this VisitAndWrapIntoBrackets.

I tried to avoid generation of unnecessary "CAST(... AS ...) at last stage - #23136

```c#
sealed class FB_Common__QuerySqlGenerator:QuerySqlGenerator
{
//...
 protected override Expression VisitSqlUnary(SqlUnaryExpression sqlUnaryExpression)
 {
  Check.Arg_NotNull
   (c_ErrSrcID,
    nameof(VisitSqlUnary),
    nameof(sqlUnaryExpression),
    sqlUnaryExpression);

  switch(sqlUnaryExpression.OperatorType)
  {
   case ExpressionType.Convert:
   {
    //....

    if(Helper__CanIgnoreConvert(sqlUnaryExpression))
    {
     this.VisitAndWrapIntoBrackets(sqlUnaryExpression.Operand); //<------------- HERE
    }
    else
    {
     this.Sql.Append("CAST(");

     this.VisitAndWrapIntoBrackets(sqlUnaryExpression.Operand);

     this.Sql.Append(" AS ");

     this.Sql.Append(sqlUnaryExpression.TypeMapping.StoreType);

     this.Sql.Append(")");
    }//else

    break;
   }//Convert

   default:
   {
    base.VisitSqlUnary(sqlUnaryExpression);

    break;
   }
  }//switch

  return sqlUnaryExpression;
 }//VisitSqlUnary
//...
```
This way has the problem - it may generate SQL like "ROUND((  ))".

Perhaps this is not the correct approach.

Further research is needed on this topic.

I'll do it later  :)
