### ISSUE TITLE
How get the Setter from a IProperty

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#23327]
Hello all,

I am adatting my framework to support the new features of version 5.
I am trying to support the property Bag and i found a very confortable IPropertyBase.GetGetter() Extetension method that allow me to get a property value not worring if is an "entity" property or a property of a dictionary(thanks for tha warning about a ShadowProperty).

I did not find a similar extension for the Setter despite i can found it in the PropertyBase class as property.

Is there a safety way to get the Setter like you allow about the getter?

Many thanks

**Comment by ajcvickers** [comment]
@GLuca74 The typical way to get and set a property with EF Core is to use the `PropertyEntry`. For example:

```C#
var propertyEntry = context.Entry(entity).Property(e => e.Name);

propertyEntry.CurrentValue = "Arthur";
Console.WriteLine(propertyEntry.CurrentValue);
```

The CurrentValue property can read and write the property value. It uses the same cached delegates as EF uses to do these things, which means perf is reasonable. CurrentValue is also strongly typed when the type of the property is known to avoid boxing the value when reading.
