### ISSUE TITLE
AddDbContext doesn't provide a LoggerFactory on the CoreOptionsExtension.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#23329]
I want to use the LoggerFactory from the CoreOptionsExtension .

    public class MyContext : DbContext
    {
        private readonly ILogger<MyContext> logger;

        public MyContext(DbContextOptions options) : base(options)
        {
            logger = options.FindExtension<CoreOptionsExtension>()?.LoggerFactory?.CreateLogger<MyContext>();
            if (logger == null)
            {
                throw new Exception("Logger required.");
            }
        }
    }

This will throw the exception:

    services.AddDbContext<MyContext>();

This does work but then the documentation states:

    //     There is no need to call this method when using one of the 'AddDbContext' methods,
    //     including 'AddDbContextPool'. These methods ensure that the Microsoft.Extensions.Logging.ILoggerFactory
    //     used by EF is obtained from the application service provider.

    services.AddDbContext<MyContext>((serviceProvider, optionsBuilder) =>
    {
        optionsBuilder.UseLoggerFactory(serviceProvider.GetService<ILoggerFactory>());
    });

**Comment by ajcvickers** [comment]
@qsdfplkj The integration with ASP.NET logging doesn't set `LoggerFactory` on the context options. This will only be set if an application has explicitly configured a LoggerFactory. However, ASP.NET Core automatically registers the ILoggerFactory in the application service provider, so you should be able to resolve it directly in the DbContext constructor. For example:

```C#
public MyContext(DbContextOptions options, ILoggerFactory loggerFactory) : base(options)
{
    logger = loggerFactory.CreateLogger<MyContext>();
}
```

**Comment by qsdfplkj** [comment]
Ah, now I see it, it can either injected but the EF can resolve it via: options.FindExtension<CoreOptionsExtension>().ApplicationServiceProvider.GetService<ILoggerFactory>();. Use UseLoggerFactory to explicitly configure a LoggerFactory. (I was used to call UseLoggerFactory always).
