### ISSUE TITLE
SQLite functional test project build break

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2333]
In SqliteTestStore.cs:

```
 CacheMode = sharedCache ? CacheMode.Shared : CacheMode.Private
```

Cachemode does not appear to be included in the package published on MyGet v1.0.0-beta6-10770 

@natemcmaster

**Comment by natemcmaster** [comment]
Our CI is several days behind. SqliteTestStore will work when you have the changes merged earlier this week from https://github.com/aspnet/Microsoft.Data.Sqlite/pull/84. Until our nightly builds catch up, you can get around this error by using a locally-built nupkg with the latest changes to Microsoft.Data.Sqlite
