### ISSUE TITLE
Migration to change the type of a identity primary key does not work in EF Core 5.0

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#23333]
I am trying to change the type of identity primary key with EF Core migration as follows but it does not work.

Before Change:

    public class Post
    {
        public int Id { get; set; } // Here it is int type
        public string Title { get; set; }
        public string Content { get; set; }
    }

After Change:

    public class Post
    {
        public long Id { get; set; } // I have changed it to long type.
        public string Title { get; set; }
        public string Content { get; set; }
    }

Genereared Migration:

    migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "Posts",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("SqlServer:Identity", "1, 1")
                .OldAnnotation("SqlServer:Identity", "1, 1");

The error message:

> **The object 'PK_Tags' is dependent on column 'Id'.
> ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.**

The error message suggests that you are almost close to the solution. You need to drop and recreate the primary key constraint as follows:

     migrationBuilder.DropPrimaryKey(
                name: "PK_Posts",
                table: "Posts"); //  I have added this manually

    migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "Posts",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("SqlServer:Identity", "1, 1")
                .OldAnnotation("SqlServer:Identity", "1, 1");

     migrationBuilder.AddPrimaryKey(
                           name: "PK_Posts",
                           table: "Posts",
                           column: "Id"); //  I have added this manually

After adding the custom lines in the migrations, the migration works.

**This can be a very good candidate for EF Core 6.0.0**

### Include provider and version information

EF Core version: 5.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) : 5.0.0
Target framework: 5.0.0
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2019 16.8.1

**Comment by ajcvickers** [comment]
Rebuilding primary key constraints is tracked by #16758
