### ISSUE TITLE
DateTimeOffset based query throws 'The LINQ expression could not be translated.' error

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#23334]
## Description

I'm trying to query records based on year using the `DateTimeOffset` field. But this throws "**The LINQ expression could not be translated.**" But the same works for `DateTime` field. Please assist on what I'm missing.

## Repro Sample

```c#
class Program
{
    static async Task Main()
    {
        using var ctx = new BlogContext();

        var currentYear = DateTimeOffset.Now.Year;
        var dateTimeOffsetFails = await ctx.Book.Where(x => x.PublishedDate.Year > currentYear).ToListAsync();
    }
}

public class BlogContext : DbContext
{
    public DbSet<Book> Book { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite(new SqliteConnection(new SqliteConnectionStringBuilder { DataSource = ":memory:" }.ToString()));
   
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => new { e.Id });

            entity.Property(p => p.PublishedDate)
                .IsRequired(true);
        });
    }
}

public class Book
{
    protected Book()
    {
    }

    public int Id { get; set; }
    public DateTimeOffset PublishedDate { get; private set; }
}
```

### Message

> The LINQ expression 'DbSet<Book>()
>     .Where(b => b.PublishedDate.Year > __currentYear_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

### StackTrace
   

> at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
>    at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
>    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at EFCoreIssuesSample.Program.<Main>d__0.MoveNext() in C:\Users\xxxxxxxxxxxx\source\repos\EFCoreIssuesSample\EFCoreIssuesSample\Program.cs:line 23

### Include provider and version information

EF Core version: 5.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.8.1)

**Comment by maumar** [comment]
Note: works fine on sql server

**Comment by smitpatel** [comment]
DateTimeOffset has limitations on Sqlite provider. Please see https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations#query-limitations
