### ISSUE TITLE
Allow TPT when primary key columns in the tables do not exactly match

### ISSUE THREAD

**Issue by overdunne** [dotnet/efcore#23345]
Trying to apply TPT inheritance in EF Core 5, using an existing schema. How can I specify the primary and foreign key column name in the child table, if the column name does not exactly match the parent table? In the documentation example, we would not have Pets.Id, but Pets.PetId:

CREATE TABLE [Animals] (
    **[Id]** int NOT NULL IDENTITY,
    [Species] nvarchar(max) NULL,
    CONSTRAINT [PK_Animals] PRIMARY KEY ([Id])
);

CREATE TABLE [Pets] (
    **[PetId]** int NOT NULL,
    [Name] nvarchar(max) NULL,
    CONSTRAINT [PK_Pets] PRIMARY KEY ([PetId]),
    CONSTRAINT [FK_Pets_Animals_Id] FOREIGN KEY ([PetId]) REFERENCES [Animals] ([Id]) ON DELETE NO ACTION
);

**Comment by ajcvickers** [comment]
@overdunne This is tracked by #19811
