### ISSUE TITLE
System.InvalidOperationException in GroupBy with empty query

### ISSUE THREAD

**Issue by copyliu** [dotnet/efcore#23347]
###  code

```C#
    public class TestContext : DbContext
    {
        public DbSet<Tbl> Tbl { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=blogging.db");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tbl>(p =>
            {
                p.HasKey("id");
            });
        }
    }
    public class Tbl
    {
        public long id { get; set; }
        public float value { get; set; }
    }

    public class Cls
    {
        public float value { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            using TestContext db=new TestContext();
            var val=db.Tbl.Where(p => false).GroupBy(p => 1).Select(p=>new Cls()
            {
                value = p.Max(i=>i.value)
            }).First();
            Console.WriteLine(val.value);
        }
    }
```

###  stack traces

```
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at ConsoleApp3.Program.Main(String[] args) in L:\MyDocuments\Visual Studio 2019\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 43
```

EF Core version: 5.0.0

for EF Core version 3.x, it don't thrown exception and return zero.

**Comment by smitpatel** [comment]
You are using `Where(p => false)` as predicate before grouping which means the sequence is going to be empty. Further the max is applied on an empty sequence of float. This is an exception in IEnumerable also. 3.x results were incorrect. 5.0 fixed the bug hence you are getting exception since we cannot determine a float value to put in "value".

You can use `p.Max(i => (flaot?)i.value)` to cast to nullable type in advance which will return null if sequence is empty. If you are wanting a non-null result and 0 if sequence is empty then use `p.Max(i => (float?)i.value) ?? 0`

**Comment by copyliu** [comment]
`Max()` in this scenario is returning `null` in 5.0, you can also get 0 result with ` (float?) p.Max(i=>i.value) ?? 0` in 5.0.
is `p.Max(i => i.value)` returning `null` is desired results here?

**Comment by smitpatel** [comment]
`p.Max(i => i.value)` actually does not return `null`. The `Max("value")` in SQL returns null. Which does not match expectation of result of Max on client side (float which is non-null).

**Comment by copyliu** [comment]
```C#
 var val=db.Tbl.Where(p => false).GroupBy(p => 1).Select(p=>new 
            {
                v = p.Max(i=>i.value)
            }).First();
```
in this scenario (anonymous type), it will throw `Nullable object must have a value.`  too because `v` will compiled as a not-null float type but `Max()` return `null`.

Although throwing exception is a correct result, it's confusing to receive  `Nullable object must have a value.` instead of `Sequence contains no elements`. What's more, it doesn't throw exceptions with `.Select(p=>new { value = (float?) p.Max(i=>i.value)})`

**Comment by ajcvickers** [comment]
Discussed in triage and agreed that the current behavior is by-design.
