### ISSUE TITLE
Add-Migration removes previous one-to-one Relationship when used between two models (FluentAPI)

### ISSUE THREAD

**Issue by jelizaga3-gatech** [dotnet/efcore#23356]
### Description
When trying to create 1-1 (zero-or-one to zero-or-one, [0..1] to [0..1] in this case) references, I came across a bug that occurs when trying to create a one-to-one relationship twice between two entities. The bug occurs in the `FluentAPI` and the correct functionality is shown using `DataAnnotations`. At first I thought I was just using the `FluentAPI` incorrectly, but this comment led me to believe that the proper functionality works using `DataAnnotations`: https://github.com/dotnet/efcore/issues/16520#issuecomment-509718125. The `FooHappyPath` and `BarHappyPath` follow the `Document` and `Change` relationship in the link provided.

I would guess that the issue relates to taking the last relationship defined (in this example `FooBug`) so `Add-Migrations` properly processes the relationship but "forgets" (maybe a stray .FirstOrDefault() or .Last()?) the other relationship that was defined.

### Include your code

Entire code file that reproduces issue. 

`FooHappyPath` and `BarHappyPath` shows the correct states and outputs of the migration. 

`FooBug` and `BarBug` shows the states and bugged outputs of the migration. 

```C#
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleApp1
{
    public class FooBug
    {
        public int FooBugId { get; set; }
        public string FooBugName { get; set; }
        public BarBug BarBug { get; set; }
        public int? BarBugId { get; set; }
    }

    public class BarBug
    {
        public int BarBugId { get; set; }
        public string BarBugName { get; set; }

        public FooBug FooBug { get; set; }
        public int? FooBugId { get; set; }

    }
    public class FooHappyPath
    {
        public int FooHappyPathId { get; set; }
        public string FooHappyPathName { get; set; }

        [ForeignKey(nameof(BarHappyPathId))]
        public BarHappyPath BarHappyPath { get; set; }
        public int? BarHappyPathId { get; set; }
    }

    public class BarHappyPath
    {
        public int BarHappyPathId { get; set; }
        public string BarHappyPathName { get; set; }

        [ForeignKey(nameof(FooHappyPathId))]
        public FooHappyPath FooHappyPath { get; set; }

        public int? FooHappyPathId { get; set; }

    }

    public class DataAnnotationsContext : DbContext
    {
        public DbSet<FooHappyPath> FooHappyPathSet { get; set; }
        public DbSet<BarHappyPath> BarHappyPathSet { get; set; }
        public DbSet<FooBug> FooBugSet { get; set; }
        public DbSet<BarBug> BarBugSet { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "Data Source=(localdb)\\ProjectsV13;Initial Catalog=TestDataAnnotations";

            optionsBuilder.UseSqlServer(connectionString);

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<BarBug>()
                .HasOne(b => b.FooBug)
                .WithOne(u => u.BarBug)
                .HasForeignKey<BarBug>(su => su.FooBugId)
                .IsRequired(false);

            modelBuilder.Entity<FooBug>()
                .HasOne(u => u.BarBug)
                .WithOne(su => su.FooBug)
                .HasForeignKey<FooBug>(u => u.BarBugId)
                .IsRequired(false);
        }
    }
}


```

### Include stack traces

No error/stack trace.

### Include verbose output

Running `Add-Migration Initial` in the `Package Manager Console`:

```
PM> Add-Migration Initial
Build started...
Build succeeded.
To undo this action, use Remove-Migration.
```

Creates the migration file: (Comments were added and not auto-generated)

`20201117050417_Initial.Designer.cs`
```csharp
            /* Correct "Happy Path Output" */
            modelBuilder.Entity("ConsoleApp1.BarHappyPath", b =>
                {
                    b.HasOne("ConsoleApp1.FooHappyPath", "FooHappyPath")
                        .WithMany()
                        .HasForeignKey("FooHappyPathId");

                    b.Navigation("FooHappyPath");
                });

            /* Correct  (but part of bug) */
            modelBuilder.Entity("ConsoleApp1.FooBug", b =>
                {
                    b.HasOne("ConsoleApp1.BarBug", "BarBug")
                        .WithOne("FooBug")
                        .HasForeignKey("ConsoleApp1.FooBug", "BarBugId");

                    b.Navigation("BarBug");
                });

            /* Correct "Happy Path Output */
            modelBuilder.Entity("ConsoleApp1.FooHappyPath", b =>
                {
                    b.HasOne("ConsoleApp1.BarHappyPath", "BarHappyPath")
                        .WithMany()
                        .HasForeignKey("BarHappyPathId");

                    b.Navigation("BarHappyPath");
                });

            /* Missing zero-or-one relationship! */
            modelBuilder.Entity("ConsoleApp1.BarBug", b =>
                {
                    b.Navigation("FooBug");
                });
```

### Notes 
I did a quick tests and it also affects `.IsRequired(true)` calls. 

### Include provider and version information

EF Core version: Microsoft.EntityFrameworkCore.Design 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.0
Target framework: .NET 5.0
Operating system: Windows 10 Pro Version	10.0.18363 Build 18363
IDE: Visual Studio 2019 Version 16.8.1

**Comment by jelizaga3-gatech** [comment]
Follow up question: 

I just realized the HappyPath's use "WithMany()" rather than "WithOne()".  I would prefer that the "WithOne()" syntax would persist with the Bug exampls. Is this a SQL/db limitation?

**Comment by AndriySvyryd** [comment]
@jelizaga3-gatech A navigation can only participate in a single relationship, so when you are using `BarBug` again in the configuration you are replacing the previous relationship.
When you don't configure a relationship explicitly EF default to one-to-many.
