### ISSUE TITLE
StackOverflowException when using same collection navigation twice

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23354]
Originally from https://github.com/dotnet/efcore/issues/23348#issuecomment-727298251:

> Yes, my scenario simplified is basically:

```C#
class Product {
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Product> RelatedProducts { get; set; }
}
```

> My OnModelCreating override throws a stackoverflow exception at this statement:

```C#
 modelBuilder.Entity<Product>()
                .HasMany(p => p.RelatedProducts)
                .WithMany(p => p.RelatedProducts)
```

**Comment by AndriySvyryd** [comment]
@Tiberriver256 I don't get a StackOverflow with the above code. Could you share a small repro project?

**Comment by Tiberriver256** [comment]
Hey @AndriySvyryd looks like your comment may have been deleted but it looks like the StackOverflow only shows up when using the DbContext as a .NET Standard 2.1 class library from a .Net Core 3.1 project.

Here's a repo with a simple solution that produces the error:
https://github.com/Tiberriver256/EFCoreSelfRefrerencingStackOverflowIssueRepro

Thanks for looking into this.

**Comment by AndriySvyryd** [comment]
@Tiberriver256 Thanks, I was able to repro it
