### ISSUE TITLE
Can't run csproj tests using Built-in VS test runner

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2335]
Why has this been removed? My understanding is that this tells the VS Test Explorer that this is a test project:

``` XML
 <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
```

**Comment by bricelam** [comment]
Sorry, got a little trigger happy... Red is my favorite color when it comes to diffs.

**Comment by bricelam** [comment]
We typically use [TestDriven.NET](http://testdriven.net/) to run tests, so I didn't notice a difference.

**Comment by ErikEJ** [comment]
@bricelam no worries, but some of us actually use the Microsoft supplied tes runner ;-)

**Comment by bricelam** [comment]
I think we'll have to depend on `xunit.runner.visualstudio` to light it up. It may not work either since we're not using NuGet to install packages...

**Comment by ErikEJ** [comment]
Ok, then, for "your" test Projects it will be Testdriven.net then

**Comment by bricelam** [comment]
`xunit.runner.visualstudio` does depend on MSBuild to copy `xunit.runner.visualstudio.testadapter.dll` to the output directory. Closing as "Won't Fix" for now.
