### ISSUE TITLE
Scaffold-DBContext Generate  Partial Initialize Method to support initialization additions in partial entities.

### ISSUE THREAD

**Issue by ryios** [dotnet/efcore#23355]
When you generate Models for your database using Scaffold-DBContext it makes partial classes which is great.  However there is often initialization logic in the constructor that can't be added to via a constructor in the partial class, for example:

```   public partial class TblThing
    {
        public TblThing()
        {
            TblSubThing= new HashSet<TblSubThing>();
        }
```
So if I want to extend TbLThing with some non generated code, I can create a new file via a partial class to do so.  But If I add a property I want to initialize, there's no way for me to initialize it.  The constructor is already defined in the other partial class that was generated, and theres nothing you can do to make your initialization logic be called by the other partial class.

For a solution,

I think there should be more configurations options for Scaffold-DBContext.  We use a power shell script to run Scaffold-DBContext and we have a custom list of tables we want to scaffold etc.  Our database is old, so we have a few issues where somethings aren't generated all the way, so we manually add them to entities etc.  We want to be able to keep doing that, fixing the database isn't really an option.

So I think we should be able to supply a new parameter to Scaffold-DbContext which is a list of table names to add Initialize calls to.

i.e.

```Scaffold-DbContext -Connection name=ourdb -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir GeneratedEF\EFModels -ContextDir GeneratedEF\DBContext -Context OurContext -ContextNameSpace  OurNamespace -Tables $tableNames -Force -NoPluralize -NoOnConfiguring -TablesWithPartialInitialze "tblCar, tblTruck, tblVehicle"```

So the parameter -TablesWithPartialInitialize

Would cause the constructor above to be generated like this:

```   public partial class TblCar
    {
        public TblThing()
        {
            TblSubThing= new HashSet<TblSubThing>();
            Initialize();
        }
```

The initialize method could then be defined in the extension of the partial class in a separate file.  This would allow us to auto generate our Models without over writing our customizations.

As an added feature I think -TablesWithPartialInitialize should automatically create the new file for the partial class extension for the model with some kind of standard file name, i.e. "TblCar_PartialExtension.cs".  That way the build doesn't fail from Initialize() not being defined.

I'm open to other suggestions.

**Comment by ajcvickers** [comment]
@ryios Thanks for the suggestion. Rather than implement more partial methods by default, we believe this is better supported by integrating templates into the code generation process, since this would allow you do define any partial method that was useful to you. This is tracked by #4038.

**Comment by ryios** [comment]
Ah, sweet, I see you can use EF6 in T4.  So we should be able to customize the generated code via a T4 template.  Thanks.

https://www.bricelam.net/2020/02/03/t4-and-efcore.html
