### ISSUE TITLE
EF5 Including related entities using .Join() throws exception

### ISSUE THREAD

**Issue by ctrlaltdan** [dotnet/efcore#23366]
Good evening, 

I'm trying to run the below query but I'm receiving an exception as follows when trying to generate the SQL query.

> Unable to translate collection subquery in projection since the parent query doesn't project key columns of all of it's tables which are required to generate results on client side. This can happen when trying to correlate on keyless entity or when using 'Distinct' or 'GroupBy' operations without projecting all of the key columns.

I've tried everything I can think of and searching on the web has drawn a blank. Is it possible to include related entities in a `.Join()`?

I appreciate the error message states `the parent query doesn't project key columns of all of it's tables which are required`, and this is true. The Included navigation property `SomeCollection` has a Primary Key of `string TenantId, Guid ClientId, int sequence` (foreign key to Client `string TenantId, Guid ClientId`). As this is a one-to-many collection I don't see how I can feasibly include the `sequence` (given this is what denotes the record's uniqueness).

Many thanks

---

Version: EF 5.0.0
.NET SDK 5.0.100
Persistence: SqlServer

```C#
database
    .ClientStates
    .AsNoTracking()
    .Where(state => state.TenantId == tenantId && state.Timestamp <= atTimestamp)
    .GroupBy(state => new {
        state.TenantId,
        state.ClientId
    })
    .Select(grouping => new
    {
        grouping.Key.TenantId,
        grouping.Key.ClientId,
        Sequence = grouping.Max(state => state.Sequence)
    })
    .Join(
        database.ClientStates,
        subQuery => subQuery,
        state => new { state.TenantId, state.ClientId, state.Sequence },
        (_, client) => client)
    .Join(
        database
            .Clients
            .Include(client => client.SomeCollection), // with this include commented out, the query works.
        state => new { state.TenantId, Id = state.ClientId },
        client => new { client.TenantId, Id = client.Id },
        (state, client) => new
        {
            Client = client,
            ClientState = state
        });
```

SQL Server query produced (when `.Include(client => client.SomeCollection)` is omitted)

```SQL
declare @__tenantId nvarchar(32) = '9e519be65d224c24a752104ad8c2899e'
declare @__atTimestamp datetime2 = '2020-11-17 17:24:41.4852414'

SELECT 
    [c1].[TenantId], [c1].[Id], -- ...omitted for brevity
    [c0].[TenantId], [c0].[ClientId], [c0].[Sequence], [c0].[Timestamp] -- ...omitted for brevity
FROM (
    SELECT [c].[TenantId], [c].[ClientId], MAX([c].[Sequence]) AS [c]
    FROM [ClientStates] AS [c]
    WHERE ([c].[TenantId] = @__tenantId) AND ([c].[Timestamp] <= @__atTimestamp)
    GROUP BY [c].[TenantId], [c].[ClientId]
) AS [t]
INNER JOIN [ClientStates] AS [c0] ON (([t].[TenantId] = [c0].[TenantId]) AND ([t].[ClientId] = [c0].[ClientId])) AND ([t].[c] = [c0].[Sequence])
INNER JOIN [Clients] AS [c1] ON ([c0].[TenantId] = [c1].[TenantId]) AND ([c0].[ClientId] = [c1].[Id])
```

**Comment by ctrlaltdan** [comment]
I should add that an `.Include()` inside of a `.Join()` does seem to work when there's a 1:1 relationship.

**Comment by maumar** [comment]
@ctrlaltdan this is the breaking change you are hitting: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#collection-distinct-groupby

**Comment by ctrlaltdan** [comment]
Ah that's such a bummer! I was inches away from creating a slick all-in-one query using filtered includes. 

I can achieve the same by performing two queries and stitching together the results, I just feel this has greater scope for accidental bugs creeping in later down the line.

Some feedback for the EF team; perhaps the API could have made this an explicit override at the query level to highlight the potential for inconsistencies in results? `.OverrideWarning(Warnings.DistinctOrGroupByCollectionSubqueryCanProduceInaccurateResults)`. It feels as though a valuable part of EF was removed here because of a higher degree of user error.

Thank you for your response @maumar, you've saved me a few hours of frustration!
