### ISSUE TITLE
EF Core 5 / Table-per-type inheritance: if subtype has a pk field with a different name as the parent, the SQL is wrong

### ISSUE THREAD

**Issue by FransBouma** [dotnet/efcore#23379]
EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

See attached repro. 

I get: 
```
fail: 18/11/2020 12:32:00.889 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [e].[ManagerID], [e].[Name], [e].[StartDate], [e].[WorksForDepartmentID], [m].[ManagesDepartmentID], [b].[CompanyCarID], CASE
          WHEN [b].[ManagerID] IS NOT NULL THEN N'BoardMember'
      END AS [Discriminator]
      FROM [dbo].[Employee] AS [e]
      INNER JOIN [dbo].[Manager] AS [m] ON [e].[ManagerID] = [m].[ManagerID]
      LEFT JOIN [dbo].[BoardMember] AS [b] ON [e].[ManagerID] = [b].[ManagerID]
```
-> ` Invalid column name 'ManagerID'.`

Tables: (See attached for full ddl sql)
```sql

CREATE TABLE [dbo].[Manager] 
(
	[ManagerID] [int] NOT NULL, 
	[ManagesDepartmentID] [int] NULL 
)

CREATE TABLE [dbo].[Employee] 
(
	[EmployeeID] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StartDate] [datetime] NOT NULL, 
	[WorksForDepartmentID] [int] NULL 
)

ALTER TABLE [dbo].[Employee] WITH NOCHECK 
	ADD CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
	( 
		[EmployeeID] 
	)

ALTER TABLE [dbo].[Manager] WITH NOCHECK 
	ADD CONSTRAINT [PK_Manager] PRIMARY KEY CLUSTERED 
	( 
		[ManagerID] 
	)

ALTER TABLE [dbo].[Manager] 
	ADD CONSTRAINT [FK_Manager_Employee] FOREIGN KEY
	(
		[ManagerID] 
	)
	REFERENCES [dbo].[Employee]
	(
		[EmployeeID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

ALTER TABLE [dbo].[Employee] 
	ADD CONSTRAINT [FK_Employee_Department] FOREIGN KEY
	(
		[WorksForDepartmentID] 
	)
	REFERENCES [dbo].[Department]
	(
		[DepartmentID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
etc...
```
The difference in PK names is deliberate here for my tests. Here you see the subtype 'Manager' has a different PK field name as its supertype 'Employee'. The generated SQL query tries to obtain the 'ManagerID' from the employee table, but it's EmployeeID in that table. See the attached repro for the full mapping code. It might be I have to do some extra mapping, but I don't know what. I also tried .HasKey() on the Manager type mapping but that didn't solve it (as it already has a key). If I have to map the 1:1 relationship between Employee and Manager, it's not in the docs I have to do that so no idea how. 

As the names differ I map the PK field in the subtypes explicitly:
```cs
protected virtual void MapEmployee(EntityTypeBuilder<Employee> config)
{
	config.ToTable("Employee");
	config.HasKey(t => t.EmployeeId);
	config.Property(t => t.EmployeeId).HasColumnName("EmployeeID").ValueGeneratedOnAdd();
	config.Property(t => t.Name).HasMaxLength(50).IsRequired();
	config.Property(t => t.StartDate);
	config.Property(t => t.WorksForDepartmentId).HasColumnName("WorksForDepartmentID");
	config.HasOne(t => t.WorksForDepartment).WithMany(t => t.Employees).HasForeignKey(t => t.WorksForDepartmentId);
}

protected virtual void MapManager(EntityTypeBuilder<Manager> config)
{
	config.ToTable("Manager");
	config.Property(t => t.EmployeeId).HasColumnName("ManagerID");
	config.Property(t => t.ManagesDepartmentId).HasColumnName("ManagesDepartmentID");
	config.HasOne(t => t.Department).WithMany(t => t.Managers).HasForeignKey(t => t.ManagesDepartmentId);
}
```

Hierarchy:
![image](https://user-images.githubusercontent.com/3628530/99526482-97e57880-299b-11eb-82c9-c38c1a023e59.png)

Repro:
[TPEPkNamesDifferentErrorEFCore5.zip](https://github.com/dotnet/efcore/files/5559751/TPEPkNamesDifferentErrorEFCore5.zip)

**Comment by ajcvickers** [comment]
@FransBouma This looks like the limitation tracked by #19811. /cc @AndriySvyryd

**Comment by FransBouma** [comment]
Looks like it indeed. The fix for this limitation is scheduled for EFCore 6 or for the first patch out? If it's for EF Core 6, I have to add a validation to my system to flag this as an error.

**Comment by ajcvickers** [comment]
The change needed to make this work is significant and hence we cannot address it in a patch. It is scheduled for 6.0.

**Comment by FransBouma** [comment]
Ok, thanks. I'll add a validation rule in my validator so a hierarchy like my test setup will be flagged as an error as it's currently not supported.
