### ISSUE TITLE
Update Microsoft.EntityFramework5.0 error 

### ISSUE THREAD

**Issue by luoyuctl** [dotnet/efcore#23373]
![image](https://user-images.githubusercontent.com/51604064/99488835-0974f500-29a3-11eb-89f2-30d01145489c.png)

roleback Microsoft.EntityFrameworkCore 3.1.9 is worked,i use mysql ,here is my packages
![image](https://user-images.githubusercontent.com/51604064/99489713-4e992700-29a3-11eb-8aed-9db10fdcb006.png)

EF Core version:
Database provider: Microsoft.EntityFrameworkCore5.0
Target framework: NET 5.0
Operating system:Winodows10
IDE: (e.g. Visual Studio 2019 16.8.1)

**Comment by smitpatel** [comment]
Are you using Pomelo.EntityFrameworkCore.MySql version 5.0.0-alpha*?
cc: @lauxjpn

**Comment by Sparklix** [comment]
> Are you using Pomelo.EntityFrameworkCore.MySql version 5.0.0-alpha*?
> cc: @lauxjpn

no，should i use this?

**Comment by smitpatel** [comment]
Can you share the csproj file of the project which is giving error? 3.2.4 of MySql provider does not work with EF Core 5.0

**Comment by smitpatel** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088 for more details.

**Comment by Sparklix** [comment]
> See [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1088](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088) for more details.

how should i use this ?it's something wrong ,options is null
![image](https://user-images.githubusercontent.com/51604064/99492024-cc5f3180-29a7-11eb-8db0-53f569c7b254.png)
![image](https://user-images.githubusercontent.com/51604064/99492071-e0a32e80-29a7-11eb-9746-cc1a8d360ec4.png)

**Comment by Sparklix** [comment]
> Can you share the csproj file of the project which is giving error? 3.2.4 of MySql provider does not work with EF Core 5.0

now i use the Pomelo.EntityFramework.mysql 5.0.0-alpha.2,but something error,i don't know how to 
initialize, just need connecttionString before

**Comment by lauxjpn** [comment]
See our main page under [Getting Started: 3. Services Configuration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/#3-services-configuration).

You can also take a look at any or all of the following:
* https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088#issuecomment-726054388
* https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1233

**Comment by Sparklix** [comment]
> See our main page under [Getting Started: 3. Services Configuration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/#3-services-configuration).
> 
> In short, your call should look like this:
> 
> ```cs
> options.UseMySql(
>     yourConnectionString,
>     new MySqlServerVersion(new Version(8, 0, 18))
> ```
> 
> You can also take a look at any or all of the following:
> 
> * [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1088 (comment)](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088#issuecomment-726054388)
> * [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1233](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1233)

thanks,it getting worked
