### ISSUE TITLE
Collations aren't scaffolded correctly

### ISSUE THREAD

**Issue by yori-s** [dotnet/efcore#23386]
Scaffolding a fluent db context (using `Npgsql.EntityFrameworkCore.PostgreSQL`), column collations appear as `HasComment` rather than `UseCollation`.

Indexes appear to be generated with the expected collation.

`RelationalScaffoldingModelFactory.VisitColumns` [line 500](https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L500) looks a bit suspicious:

Shouldn't
```c#
            if (column.Collation != null)
            {
                property.HasComment(column.Collation);
            }
```
be
```c#
            if (column.Collation != null)
            {
                property.UseCollation(column.Collation);
            }
```

### Include provider and version information

EF Core version: 5.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 5.0
Operating system: windows 10 (docker from wsl2)
IDE: command line

**Comment by smitpatel** [comment]
cc: @roji

**Comment by roji** [comment]
Collations are actually a form of comment on the column on how to do text processing.

(JK, submitted #23388. Database collation scaffolding also doesn't work.)

**Comment by yori-s** [comment]
wow - y'all are **fast** :joy:

**Comment by roji** [comment]
![Uploading image.png…]()

**Comment by roji** [comment]
![image](https://user-images.githubusercontent.com/1862641/99604998-70c88e80-2a0f-11eb-9468-56d08a34453b.png)

**Comment by ajcvickers** [comment]
@roji Please prepare a 5.0.1 patch PR for this.

**Comment by yori-s** [comment]
Looks good using the dotnet6 feed - thanks again for the quick turnaround!

**Comment by roji** [comment]
5.0.1 patch: 23414
