### ISSUE TITLE
Is EntityFrameworkCore.Sqlite embeddable in a self contained single file application?

### ISSUE THREAD

**Issue by MattInternet** [dotnet/efcore#23385]
I'm working on a cli tool that I would like to be fully self contained so the user can simply run the binary directly. It is currently using dotnet 5 as well as Microsoft.EntityFrameworkCore.Sqlite version 5.0.0

Replicating the behaviour is very easy:
1. create a new project with `dotnet new`
2. add EF Core sqlite with: `dotnet add package Microsoft.EntityFrameworkCore.Sqlite`
3. publish the app self-contained with: `dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -c Release -o publish`

Now you will see the output directory will have 3 files:
- libe_sqlite3.so
- <project_name>.pdb
- <project_name>

The 2 containing <project_name> are fine but the libe_sqlite3.so one, which the application cannot run without, makes it not fully self-contained.

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5.0
Operating system: Ubuntu 20.04
IDE: VSCode

**Comment by bricelam** [comment]
Two options I can think of:

1. Include the native libraries inside the executable so they can be automatically extracted at runtime. Add `/p:IncludeNativeLibrariesForSelfExtract=true` to do this.

2. Use the system version of SQLite.
    ```xml
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.0" />-->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="5.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_sqlite3" Version="2.0.4" />
    ```
