### ISSUE TITLE
broadFileSystemAccess for Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by myokeeh** [dotnet/efcore#23393]
I'm trying to use an SQlite database that's located in `D:\test.db3`. My app already has `broadFileSystemAccess`. It's a kiosk (assigned access) UWP app. Why doesn't this work?

```
using (var connection = new SqliteConnection("Filename=D:\\test.db3"))
{
        connection.Open();
}
```

Exception:
> Microsoft.Data.Sqlite.SqliteException SQLite Error 14: 'unable to open database file'.

**Comment by bricelam** [comment]
See https://github.com/aspnet/Microsoft.Data.Sqlite/issues/287#issuecomment-243504475 and https://github.com/ericsink/SQLitePCL.raw/issues/287
