### ISSUE TITLE
Scaffolding of synonyms in SqlServer

### ISSUE THREAD

**Issue by Trapov** [dotnet/efcore#23395]
I'm trying to reverse-engineer an already existing database and the created synonyms are not being mapped. I want to have them mapped to.

So my solution is pretty simple. Basicly include that in the SqlServerDatabaseModelFactory. I think everything should just work.

https://github.com/dotnet/efcore/blob/92f9a2fe8faa6cffdd9d1646060a8cf6dba8c50e/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L650

```sql
    UNION ALL
	SELECT
		name,
		OBJECT_ID([base_object_name]) as object_id,
		SCHEMA_ID() AS schema_id
	FROM sys.synonyms s
```

**Comment by ajcvickers** [comment]
@Trapov Thank you for suggesting this and your efforts on creating a PR. We discussed this in the team and while we think this is something we can certainly do, we need to understand more about how and what the consequences will be. In particular:
- Many [different database objects can be synonyms](https://docs.microsoft.com/en-us/sql/relational-databases/synonyms/synonyms-database-engine?view=sql-server-ver15). We should understand what it means to reverse engineer each of these.
- We need to be sure that there are then no issues using the reverse engineered code at runtime. This applies to both when the synonyms reference objects in the same or a different database.

This work needs to be done before we can accept a PR for this. If you're willing to invest your time in this, then let us know. It would be appreciated, but we understand you may not want to go into this amount depth, in which case this can stay on the backlog for now.

**Comment by ajcvickers** [comment]
Note from triage: we do not plan to support synonyms.
