### ISSUE TITLE
Column order inconsistency between schema, collection and swagger

### ISSUE THREAD

**Issue by akorkiatupa** [dotnet/efcore#23394]
First of all I am super excited about all of the new features and finally some features I have been hoping for years are finally here. One of those features was custom column ordering when extending baseEntity class with sub business entity. 

Eg. 

```
    public class BaseEntity
    {
        [Column(Order = 0)]
        public int? Id { get; set; }

        [Column(Order = 997)]
        public DateTime? CreatedAt { get; protected set; } = DateTime.Now;

        [Column(Order = 998)]
        public DateTime? UpdatedAt { get; protected set; } = DateTime.Now;

        [Column(Order = 999)]
        public int? UpsertUserId { get; protected set; }
    }

    public class User : BaseEntity
    {
        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }

        [Required]
        [MaxLength(200)]
        public string Email { get; set; }
    }
```
Now this combination results into a table where ->

```
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](200) NOT NULL,
	[CreatedAt] [datetime2](7) NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[UpsertUserId] [int] NULL
) ON [PRIMARY] ...
```
Which is exactly what is wanted all good so far. 

However when fetching data from collection you get entities with column order ->

```
[
   {
      "firstName":"Default",
      "lastName":"Admin",
      "email":"test@gg.com",
      "id":1,
      "createdAt":"2020-11-18T13:26:08.4978624",
      "updatedAt":"2020-11-18T13:26:08.4978629",
      "upsertUserId":null
   }
]
```

And in swagger -> 

![image](https://user-images.githubusercontent.com/45167282/99639729-a346ab80-2a50-11eb-8a08-4eddf25866cc.png)

As a developer I would like to keep the column ordering defined in the entity property data annotations when fetching data from the database through dbContext. I would also like to keep same format on swagger. The desired end result would be in this scenario ->

```
[
   {
      "id":1,
      "firstName":"Default",
      "lastName":"Admin",
      "email":"test@gg.com",
      "createdAt":"2020-11-18T13:26:08.4978624",
      "updatedAt":"2020-11-18T13:26:08.4978629",
      "upsertUserId":null
   }
]
```

Thanks, keep up the good work.

**Comment by ajcvickers** [comment]
@akorkiatupa The JSON you show is outside the control of EF Core. EF Core queries result in CLR types, which are then serialized to JSON by your JSON serializer of choice. It is the JSON serializer that determines the order of properties in the resulting JSON. You'll need to follow up with authors of the JSON serializer you're using. However, I believe JSON is unordered by design, so I suspect you might find this is not supported. Also, you may want to follow up with Swagger to understand where the order used comes from there.

**Comment by akorkiatupa** [comment]
@ajcvickers Thanks for pointing me into right direction, JSON supports ordering however it seems System.Text.Json defaults into alphabetical order. Found out that Newtonsoft.Json supports it while the new System.Text.Json has not yet implemented it. 

https://github.com/dotnet/runtime/issues/728
