### ISSUE TITLE
Don't remove table mapping for entity types used in TVFs

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23407]
Originally reported by @maumar 

Line to remove: https://github.com/dotnet/efcore/blob/b970bf29a46521f40862a01db9e276e6448d3cb0/src/EFCore.Relational/Metadata/Conventions/TableValuedDbFunctionConvention.cs#L97

**Comment by ajcvickers** [comment]
Note from triage: consider when to map to table automatically, or not, based on how the TVF and return type is used elsewhere.

**Comment by ajcvickers** [comment]
Duplicate of #23408
