### ISSUE TITLE
RevEng generates multiple FKs on same components with different names which model throws

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#23405]
See repro https://github.com/ErikEJ/EFCorePowerTools/issues/594

**Comment by ajcvickers** [comment]
@dotnet/efteam It was indicated in triage that this is a dupe, but I can't find one. Any ideas?

**Comment by ErikEJ** [comment]
Another repro: https://github.com/ErikEJ/EFCorePowerTools/issues/459

**Comment by smitpatel** [comment]
@dotnet/efteam - Should we skip this in database model (so each provider needs to make sure that duplicated FKs are not added). or in scaffolding model where design will figure out that FK is redundant and will skip it.

**Comment by AndriySvyryd** [comment]
@smitpatel If possible do it in the scaffolding model, so we are able to fix it if we support named FKs at some point
