### ISSUE TITLE
Migration to .NET 5 - CommitTransactionAsync does not have an implementation

### ISSUE THREAD

**Issue by mskuratowski** [dotnet/efcore#23413]
Hi, I migrated my project to .NET 5.0, so I updated the target version and NuGet packages.

I updated NuGet packages from:
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.8" />
<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="3.1.8" />
```
to:

```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="5.0.0" />
```

After that, I get the following error when I start my project:

![image](https://user-images.githubusercontent.com/9077441/99805873-6a383500-2b3d-11eb-9428-352af2a08e32.png)

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.2

**Comment by roji** [comment]
Which dotnet SDK are you using? If possible, can you please post a runnable code sample which reproduces the issue?

**Comment by mskuratowski** [comment]
@roji It's 5.0.100

**Comment by roji** [comment]
I just noticed that the error screenshot shows that version 3.1.3 of Microsoft.EntityFrameworkCore.InMemory is still being used - you are most probably mixing versions between 5.0.0 and 3.1.3. Check your csproj carefully and make sure everything is using 5.0.0.

**Comment by mskuratowski** [comment]
@roji  Thanks for the hit. It wasn't a problem with EF Core at all. The problem was with AspNetCore.HealthChecks.UI.InMemory.Storage. It seems like they haven't migrated to .NET 5 :).

Thaks again for your help.
