### ISSUE TITLE
Code-First : One to Many with 3 fields that make up the primary key

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [dotnet/efcore#23415]
.Net Core 3.1
EntityFrameworkCore 3.1.10

The table "Profile" creates the primary key that is made up of ActionId, EndpointId, RoleId; also create foreign keys, but only create two indexes always omitting the first one in the list that make up the primary key

![image](https://user-images.githubusercontent.com/4327356/99833688-0b1bf580-2b28-11eb-8d7d-5dd2c0e5461b.png)
![image](https://user-images.githubusercontent.com/4327356/99833705-13743080-2b28-11eb-81a1-3444de10b61c.png)
![image](https://user-images.githubusercontent.com/4327356/99833728-1a02a800-2b28-11eb-8257-0133b3f9e85c.png)
![image](https://user-images.githubusercontent.com/4327356/99833749-2129b600-2b28-11eb-8e16-9bf85ee53c2c.png)
![image](https://user-images.githubusercontent.com/4327356/99833855-4a4a4680-2b28-11eb-99bb-e00b14e8ab3c.png)
![image](https://user-images.githubusercontent.com/4327356/99833876-559d7200-2b28-11eb-8a03-d3291a683f3c.png)

The table:
![image](https://user-images.githubusercontent.com/4327356/99833893-5fbf7080-2b28-11eb-8fbd-9d49a9d43651.png)
![image](https://user-images.githubusercontent.com/4327356/99833935-71087d00-2b28-11eb-8bf6-c5f4ba448e08.png)
![image](https://user-images.githubusercontent.com/4327356/99833954-782f8b00-2b28-11eb-9542-33db68a51250.png)

**Comment by smitpatel** [comment]
The additional index on `ActionId` is not needed since it is already included by the implicit index on PK.
