### ISSUE TITLE
EFCore.InMemory: "System.InvalidOperationException : Nullable object must have a value." when doing second left join via object

### ISSUE THREAD

**Issue by vanashimko** [dotnet/efcore#23425]
`System.InvalidOperationException: Nullable object must have a value.` exception is thrown when doing second left join via object.

**Steps to reproduce**:
```C#
public class Account
{
    public int Id { get; set; }
}

public class AccountUser
{
    public int Id { get; set; }
    public int AccountId { get; set; }
}

public class AccountUserDevice
{
    public int Id { get; set; }
    public int AccountUserId { get; set; }
}

public class TestContext : DbContext
{
    public DbSet<Account> Accounts { get; set; }
    public DbSet<AccountUser> AccountUsers { get; set; }
    public DbSet<AccountUserDevice> AccountUserDevices { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("database");
    }
}

public class Tests
{
    [Test]
    public void LeftJoinViaObject()
    {
        using var testContext = new TestContext();
        testContext.Add(new Account());
        testContext.SaveChanges();
        var query = from account in testContext.Accounts
            join accountUser in testContext.AccountUsers
                on account.Id equals accountUser.AccountId into accountUsers
            from accountUser in accountUsers.DefaultIfEmpty()
            join accountUserDevice in testContext.AccountUserDevices
                //  Changing to single property
                //  `on accountUser.Id equals accountUserDevice.AccountUserId into accountUserDevices`
                //  makes it work.
                on new {AccountUserId = accountUser.Id} equals new {accountUserDevice.AccountUserId} into
                accountUserDevices
            from accountUserDevice in accountUserDevices.DefaultIfEmpty()
            select new
            {
                account.Id,
            };

        var queryResult = query.ToArray(); // System.InvalidOperationException : Nullable object must have a value.

        Assert.AreEqual(1, queryResult.Length);
    }
}
```

**Actual**:
```
System.InvalidOperationException : Nullable object must have a value.
   at lambda_method49(Closure , ValueBuffer )
   at System.Linq.Enumerable.GroupJoinIterator[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tests.LeftJoinViaObject()
```

As mentioned in the code comments, changing join predicate to `on accountUser.Id equals accountUserDevice.AccountUserId into accountUserDevices` makes the query work. However that is not the case when doing a join on multiple columns, so can not be a workaround in a real scenario.

Reproduced on `Microsoft.EntityFrameworkCore.InMemory` 3.1.4, 5.0 daily build, 6.0 daily build.

**Comment by smitpatel** [comment]
Note: Try `new {AccountUserId = (int?) accountUser.Id} equals new {accountUserDevice.AccountUserId}` as join condition. The error is in server side execution and not in shaping.

**Comment by vanashimko** [comment]
@smitpatel This does not compile. It says `Tests.cs(46, 13): [CS1941] The type of one of the expressions in the join clause is incorrect.  Type inference failed in the call to 'GroupJoin'.` and I can not figure out types, `accountUserDevice.AccountUserId` is `int`, not `int?`. Should these two be compatible? And when I added `(int?)` to `accountUserDevice.AccountUserId` too (to both sides) it worked out. However the original code works fine with SQL Server provider and it generates valid left join x2 query, it fails only when running with in-memory provider.

> The error is in server side execution and not in shaping.

Sorry I did not get it. That is in `Microsoft.EntityFrameworkCore.InMemory`, what do you mean by server side execution?

**Comment by vanashimko** [comment]
```sql
SELECT [a].[Id]
      FROM [Accounts] AS [a]
      LEFT JOIN [AccountUsers] AS [a0] ON [a].[Id] = [a0].[AccountId]
      LEFT JOIN [AccountUserDevices] AS [a1] ON [a0].[Id] = [a1].[AccountUserId]
```
Here is the query `Microsoft.EntityFrameworkCore.SqlServer` generates for the LINQ above (without casting to `int?`). And it works fine. 

The same query is generated when doing `int?`: `on new {AccountUserId = (int?) accountUser.Id} equals new { AccountUserId = (int?) accountUserDevice.AccountUserId}` as suggested.

**Comment by smitpatel** [comment]
SqlServer uses different null semantics than InMemory. They can generate different queries. I need to investigate this little more but this could be by design only. Since your key value is nullable but you are trying to set into a non-null property of anonymous type is going to throw in InMemory.

**Comment by vanashimko** [comment]
Is the anonymous type used directly as is? When I do direct equals on two non nullable keys it is handled special way by converting to nullable types under the hood I guess (since it works fine). The issue appears only when changing to object join, which in case of a single property should be a safe change and produce equivalent results (that is my assumption which may be incorrect though...). It does not look like DB implementation detail, which is irrelevant for InMemory provider.

**Comment by ajcvickers** [comment]
@vanashimko We discussed this in triage and we're going to leave the current behavior based on:
* This is the behavior when using LINQ-to-Objects outside of EF Core
* The query can be changed in a couple of ways, as suggested above, that make it work for both relational translations and the in-memory provider/LINQ-to-Objects
