### ISSUE TITLE
Migrations build issue after .NET 5 installed

### ISSUE THREAD

**Issue by Mizuwokiru** [dotnet/efcore#23426]
Continuing to **#23291**, I still have slow building process with many migrations.
I created "empty" ASP.NET Core project using, added EF Core 5.0 **SqlServer** and **Design** packages, scaffolded some database, created Initial migration and duplicated it ~250 times by script leaving Up and Down methods' bodies are empty.

Build time in VS 16.8.2 is about 20-40 seconds, but if I use .NET CLI it increases to 5+ minutes (I cancelled build).

**[Sample project repository](https://github.com/Mizuwokiru/MigrationIssueSample)**

**[.NET CLI build log with -v diagnostic](https://gist.github.com/Mizuwokiru/b9fd0b27f1ee26d7663a91d6f14b8e61)**

EF Core version: **5.0.0**
Database provider: **Microsoft.EntityFrameworkCore.SqlServer**
Target framework: .**NET 5.0**
Operating system: **Windows 10 Pro 20H2 (OS Build 19042.630)**
IDE: **JetBrains Rider 2020.3 EAP 8**

**Comment by roji** [comment]
Probably related to #23291, but reports the opposite (VS is fast, .NET CLI is slow). I'll investigate.

**Comment by roji** [comment]
@Mizuwokiru one question though - did you experience the same slowness with Visual Studio 16.8.0 or 16.8.1, with the slowness disappearing when you upgraded to 16.8.2? If so, then it's likely the compiler fix not being in release in dotnet SDK yet - that will likely happen with 5.0.1. It's possible to verify this by trying out a daily build of the dotnet SDK, which should contain the fix.

**Comment by roji** [comment]
Repro notes:

With dotnet SDK 3.1.403 (MSBuild Engine 16.7.0+7fb82e5b2), done after 1:42 minutes.
With dotnet SDK 5.0.100 (MSBuild Engine 16.8.0+126527ff1), not done after over 11:00 minutes.
With dotnet SDK 5.0.200-preview.20570.33 (MSBuild Engine 16.8.0+126527ff1), not done after over 11:00 minutes.

**Comment by Mizuwokiru** [comment]
@roji Yeah! I think problem reason is SDK's MSBuild. Visual Studio's MSBuild 16.8.2+25e4d540b works fine. If I build solution using MSBuild.exe from Current/Bin directory of Visual Studio 16.8.2 it's built in 36 seconds.

**Comment by ajcvickers** [comment]
@roji Anything left to do on this one?

**Comment by roji** [comment]
@ajcvickers nope, thanks. This should be resolved with dotnet SDK 5.0.101 which comes out next week.
