### ISSUE TITLE
Using scaffold to generate model got a "s" at the end of property name

### ISSUE THREAD

**Issue by ooo2003003v2** [dotnet/efcore#23436]
Hello there. 
I am using Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Design both version 5.0 for my new project. 
I generated db model by typing dotnet ef dbcontext scaffold ... as usual but this time I got a "s" at the end of my properties in the context file. Is it possible to remove that "s" without removin it manually?

**Comment by ErikEJ** [comment]
Yes is is: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#pluralizer
