### ISSUE TITLE
How to open Sqlite db in full mutex mode

### ISSUE THREAD

**Issue by VarunSaiTeja** [dotnet/efcore#23445]
Library-Version: 5.0.0
I want to use an open database in Full_Mutex mode, because my application executes multiple insert statements parallelly in a transaction.

I found below demo code from [here](https://csharp.hotexamples.com/examples/Microsoft.Data.SQLite/SQLiteConnectionStringBuilder/GetFlags/php-sqliteconnectionstringbuilder-getflags-method-examples.html) and [here](https://github.com/baron-zhang-avepoint/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/Interop/Constants.cs)

```
            builder.Mutex = "None";
            Assert.Equal(Constants.SQLITE_OPEN_NOMUTEX, filter(builder.GetFlags()));

            builder.Mutex = "Full";
            Assert.Equal(Constants.SQLITE_OPEN_FULLMUTEX, filter(builder.GetFlags()));
```

This was present in past(Year: 2015), but not in the latest version.

How to open DB in full mutex in the latest version of Microsoft.Data.SQLite?
@bricelam , @NTaylorMullen , @natemcmaster

**Comment by bricelam** [comment]
Full mutex mode is the default, but I don't think transactions can span multiple threads in ADO.NET. @roji?

**Comment by bricelam** [comment]
P.S. We're thinking about changing it to NOMUTEX in #22330 since ADO.NET's DbConnection generally isn't thread safe.

**Comment by roji** [comment]
> I don't think transactions can span multiple threads in ADO.NET

If we're talking about performing operation concurrently from multiple threads on the same transaction (or anything else on the connection), then yeah, that's generally not supported.

But I don't think there's any problem with multiple threads performing operations inside the same transaction, as long as they're synchronizing properly and not doing it concurrently...

**Comment by VarunSaiTeja** [comment]
@roji , @bricelam  You are correct I am able to perform operations from various threads in a single transaction in a sequence.
But I am trying to insert them concurrently. I mean each thread will insert into DB at the same time using single connection and transaction.

**Comment by roji** [comment]
@VarunSaiTeja this is definitely something that is not typically supported by database drivers - though I have no idea whether Sqlite specifically is capable of supporting this.

**Comment by roji** [comment]
Looking at the [Sqlite docs](https://sqlite.org/threadsafe.html), it seems that "SQLITE_OPEN_FULLMUTEX flag causes the connection to be in serialized mode". From reading up on serialized mode, this basically means that Sqlite itself performs locking to make sure that the different "concurrent" attempts to execute are serialized.

In other words, unless I'm mistaken, Sqlite doesn't actually support true concurrent execution, and there would be no perf advantage in doing full mutex mode over just serializing your operations in .NET (like you have to do with every other database out there). So I'd recommend against going down this path, and coding against ADO.NET as usual, avoiding concurrent execution on a connection.

**Comment by ajcvickers** [comment]
@roji 

> this is definitely something that is not typically supported by database driver

When we're talking DbConnection, I don't think it matters if the driver supports it or not, right? Because `DbConnection` itself and all the other ADO.NET classes are not thread safe.
