### ISSUE TITLE
.Net 5 using EntityFrameworkCore.SqlServer 5.0.0 errors out for property with 'decimal' type.

### ISSUE THREAD

**Issue by code-noober** [dotnet/efcore#23447]
Hi,

Am getting error whenever I try to query with entity that has the property type as "decimal" using the .net core project with the target framework as .NET 5.0 and the entity framework sqlserver version as 5.0.0. 
When I loop each row I see error as **"Error processing 'variables' request. Unknown Error: 0x8000211d"**. 
If i comment out this property with "decimal" type , everything works fine and the object gets mapped correctly.

Note: No exceptions are thrown but when I look each object it comes with the error message as above. I have attached the screenshot for the reference.

The same works fine with .net core project with the target framework as .Net Core 3.1 and the entity framework sqlserver version as 5.0.0.

it took me a quite a while to identify the problem.
Below is the sample code which am using:

```Entity class:
public class Location
{
    [Key]
    public Guid Id {get; set;}
    public string name {get; set;}
    public decimal LocationLat { get; set; }
    public decimal LocationLong { get; set; }
}
DbContect call e.g.:
var result = await _dbContext.Set<Location>().ToListAsync();
```

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
IDE: (e.g. Visual Studio 2019 for Mac 8.8.1)

<img width="789" alt="Screenshot 2020-11-23 at 17 05 44" src="https://user-images.githubusercontent.com/66176626/99992546-62cb9280-2dae-11eb-927b-55890004f4fe.png">

**Comment by ralmsdeveloper** [comment]
In your example, you are making an asynchronous call without waiting!
```
DbContect call e.g.:
var result = _dbContext.Set<Location>().ToListAsync();
```
try
DbContect call e.g.:
`var result = await _dbContext.Set<Location>().ToListAsync();`

**Comment by code-noober** [comment]
> In your example, you are making an asynchronous call without waiting!
> 
> ```
> DbContect call e.g.:
> var result = _dbContext.Set<Location>().ToListAsync();
> ```
> 
> try
> ~DbContect call e.g.:~
> `var result = await _dbContext.Set<Location>().ToListAsync();`

await keyword is already there forgot to add in the question. have updated it. also, i did explained very clearly the issue is with the decimal data type. The .NET 5 with EF Core SqlServer 5.0.0 is not working. try it out. It's definitely a bug. Moreover deciimal data type works fine with the .Net core 3.1 with EF Core Sql Server 5.0.0. Hope its clear now

**Comment by ajcvickers** [comment]
@code-noober I am not able to reproduce this issue--see my runnable code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Location
{
    [Key]
    public Guid Id {get; set;}
    public string name {get; set;}
    public decimal LocationLat { get; set; }
    public decimal LocationLong { get; set; }
}

public class SomeDbContext : DbContext
{
    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

    public DbSet<Location> Locations { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            //.UseSqlite("Data Source=test.db")
            .UseSqlServer(Your.ConnectionString)
            .UseLoggerFactory(ContextLoggerFactory)
            .EnableSensitiveDataLogging();
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
            await context.Database.EnsureDeletedAsync();
            await context.Database.EnsureCreatedAsync();

            context.Add(new Location {LocationLat = 3.3m, LocationLong = 4.4m, name = "Chucky Cheeses"});

            await context.SaveChangesAsync();
        }

        using (var context = new SomeDbContext())
        {
            var result = await context.Set<Location>().ToListAsync();
            Console.WriteLine($"Lat: {result[0].LocationLat} Lon: {result[0].LocationLong}");
        }
    }
}
```

**Comment by code-noober** [comment]
> @code-noober I am not able to reproduce this issue--see my runnable code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
> 
> ```cs
> public class Location
> {
>     [Key]
>     public Guid Id {get; set;}
>     public string name {get; set;}
>     public decimal LocationLat { get; set; }
>     public decimal LocationLong { get; set; }
> }
> 
> public class SomeDbContext : DbContext
> {
>     private static ILoggerFactory ContextLoggerFactory
>         => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));
> 
>     public DbSet<Location> Locations { get; set; }
> 
>     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>         => optionsBuilder
>             //.UseSqlite("Data Source=test.db")
>             .UseSqlServer(Your.ConnectionString)
>             .UseLoggerFactory(ContextLoggerFactory)
>             .EnableSensitiveDataLogging();
> }
> 
> public class Program
> {
>     public static async Task Main()
>     {
>         using (var context = new SomeDbContext())
>         {
>             await context.Database.EnsureDeletedAsync();
>             await context.Database.EnsureCreatedAsync();
> 
>             context.Add(new Location {LocationLat = 3.3m, LocationLong = 4.4m, name = "Chucky Cheeses"});
> 
>             await context.SaveChangesAsync();
>         }
> 
>         using (var context = new SomeDbContext())
>         {
>             var result = await context.Set<Location>().ToListAsync();
>             Console.WriteLine($"Lat: {result[0].LocationLat} Lon: {result[0].LocationLong}");
>         }
>     }
> }
> ```

c

**Comment by code-noober** [comment]
After digging the more forums on github, Seems like others having similar issue for an e.g. this link
[Error processing 'variables' request. Unknown Error: 0x8000211d](https://github.com/OmniSharp/omnisharp-vscode/issues/3926)

**Comment by ErikEJ** [comment]
@code-noober External VS Code issue?? Not related to EF Core.

**Comment by code-noober** [comment]
> @code-noober External VS Code issue?? Not related to EF Core.

You are right its Visual Studio 2019 Debug issue with decimal datatype using .NET 5.0 version.
I am using VS2019 Pro on my macbook pro. Same issue is not reproducible using .Net Core 3.1. 
Looks like VS2019 debugging issue.
Am closing this issue as this is not related to .NET 5 or EF code Sql Server.

Thanks @ajcvickers  and @ErikEJ for helping.

**Comment by code-noober** [comment]
Just to add to the issue that this error does not affect the data and you can see the data populated if you qrite it to console or bind to UI element even though the error message still exist.
