### ISSUE TITLE
I suggest a new dotnet command 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23449]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1187556/i-suggest-a-new-dotnet-command.html)._

---
I suggest a new dotnet command to add a migration and on the same line already update the database:

"dotnet ef migrations add [name] updating database"

---
#### Feedback Bot on 9/17/2020, 02:35 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by smitpatel** [comment]
Suggestion 
`dotnet ef migrations add [name] && dotnet ef database update`
