### ISSUE TITLE
Upgrade to Microsoft.Data.SqlClient v2.1.0

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/efcore#23453]
Currently EF Core 5.0 references **v2.0.1 of Microsoft.Data.SqlClient** that can cause some issues we recently addressed in v2.1.0:
[Release Notes](https://github.com/dotnet/SqlClient/blob/master/release-notes/2.1/2.1.0.md#summary-of-changes-in-21)

Most important issues for EF users that were solved with v2.1.0:
- Microsoft.Data.SqlClient.SNI.pdb files present in Native SNI runtime NuGet packages, that are now removed.
https://github.com/dotnet/SqlClient/issues/652#issuecomment-731615294 - fixed by https://github.com/dotnet/SqlClient/pull/764
- `InvalidOperationException` and `NotSupportedException` errors due to `WriteAsync` collisions (important fix as impact was high) https://github.com/dotnet/SqlClient/issues/786#issuecomment-732278328 - fixed by https://github.com/dotnet/SqlClient/pull/796

and many more bug fixes :)

Please update dependency on Microsoft.Data.SqlCLient to [v2.1.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.0) when appropriate.

**Comment by jjxtra** [comment]
The short summary is:

- Ef core 5.0.0 package for sql server is referencing the microsoft sql client nuget version 2.0.1, it needs to reference 2.1.0.
- The issue can be avoided by manually adding microsoft sql client package 2.1.0 into the project, forcing the ef core sql server package to reference the newer version.
- But it took me several days to figure this out, hopefully a 5.0.1 hotfix can come out to reference the newer package and save other people lost time.

**Comment by ajcvickers** [comment]
@cheenamalhotra Done automatically already for 6.0: https://github.com/dotnet/efcore/pull/23434

We generally don't update to a new point release in a patch, but we will consider it if the issues fixed are significant.

**Comment by olljanat** [comment]
@cheenamalhotra @ajcvickers How about EF Core 3.1? Will it switch to SqlClient 2.x on some point or will those fixes to be ported to SqlClient 1.x?

**Comment by ErikEJ** [comment]
@olljanat You can just update to use 2.1.0 with EF Core 3.x: https://erikej.github.io/efcore/sqlclient/2020/03/22/update_mds.html

**Comment by olljanat** [comment]
@ErikEJ but are those versions compatible? I assume that there is some breaking change which why version number was raised from 1.x to 2.x?

**Comment by ErikEJ** [comment]
Yes, no breaking changes for EF Core

**Comment by ajcvickers** [comment]
Discussed in triage. We will hold off on updating the dependency in 5.0.x for now to allow further feedback on the SqlClient 2.1, since it is newly released. We will then make a call as to whether or not to take this to Tactics.

**Comment by ajcvickers** [comment]
We discussed this again and decided not to bump to a new point release in out patch release. This is not in the spirit of semantic versioning. The correct thing to do is for people to explicitly specify the higher package version. EF Core 6.0 will depend on the latest released M.D.SqlClient package.

**Comment by drdamour** [comment]
> Yes, no breaking changes for EF Core

is there a support matrix of SQL Data Client for EF Core SQL Provider somewhere?

**Comment by ErikEJ** [comment]
There is some general advice here: https://docs.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli (there is some known issues with 3.0.0 )

**Comment by RyanThomas73** [comment]
> There is some general advice here: https://docs.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli (there is some known issues with 3.0.0 )

@ErikEJ Do you have links for any of the known issues using EF Core with the `Microsoft.Data.SqlClient v3.0.0` package? 
Our immediate case of concern is compatibility between EFCore3.1 with the Microsoft.Data.SqlClient 3.0 package.

**Comment by ErikEJ** [comment]
The only issue I know of is the row version null fix, where the AppContext switch is not working as expected, a PR is currently under review. If that gets released with 3.0.1, then you probably still need the AppContext switch with EF Core, but not sure.

**Comment by drdamour** [comment]
looks like he fix to this make it to 3.0.1 via https://github.com/dotnet/SqlClient/pull/1246
