### ISSUE TITLE
Change table name via ModelBuilder and ForSqlServer does not work for dnx451

### ISSUE THREAD

**Issue by Rinsen** [dotnet/efcore#2345]
Hi!

I am trying to change the default name in a table mapping to a new name via ModelBuilder because i have pluralized names in database but i cant get this to work for dnx451, it only works for dnxcore50

`modelBuilder.Entity<MyEntity>(e =>
            {
                e.ForSqlServer().Table("MyEntitys");
                e.Key(m => m.UserId);
            });`

The extension method ForSqlServer() does not exist in dnx451 is the message I get and i cant find where to add this manually in the EntityType or where this name really is located.

Any ideas?

And i have the same problem with .Relational() extension method.

**Comment by bricelam** [comment]
Can you share your `project.json` file?

**Comment by Rinsen** [comment]
Sure :)

{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "Rinsen.Common": "1.0.0-*", // My own code
        "EntityFramework.Core": "7.0.0-beta4",
        "Rinsen.DatabaseInstaller": "1.0.0-*" // My own code
    },

    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Collections": "4.0.10-beta-22816",
                "System.Linq": "4.0.0-beta-22816",
                "System.Threading": "4.0.10-beta-22816",
                "Microsoft.CSharp": "4.0.0-beta-22816",
                "EntityFramework.SqlServer": "7.0.0-beta4",
                "EntityFramework.Commands": "7.0.0-beta4"
            }
        }
    }
}

**Comment by bricelam** [comment]
Add `EntityFramework.SqlServer` and `EntityFramework.Commands` to the general `dependencies` property, not the dnxcore50-specific one.

**Comment by Rinsen** [comment]
Thanks!

That solved the problem, what difference does it make and when should I put dependencies under general dependencies and when to put them under version specific dependencies?

**Comment by bricelam** [comment]
Put it in a framework-specific dependency list if you only want it for that framework. This is primarily used for dependencies that aren't available on some frameworks. In general, put it under the general one. :wink:

**Comment by Rinsen** [comment]
That´s simple enough :) 

I probably will find out when i need it!

Thanks again! :)
