### ISSUE TITLE
.HasFilter(null) on nullable type removes null-check filter

### ISSUE THREAD

**Issue by ShadowJonathan** [dotnet/efcore#23458]
### Model

```cs
    public class Identity {
        [Key] public string Id { get; set; }

        public bool IsGroup { get; set; }

        public virtual Person? BackingPerson { get; set; }
        public virtual Group? BackingGroup { get; set; }

        public bool Check() => IsGroup ? BackingPerson == null && BackingGroup != null : BackingGroup == null && BackingPerson != null;
    }

    public class Person {
        [Key, Required] public int Id { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AvatarHash { get; set; }
    }

    public class Group {
        [Key] public int Id { get; set; }

        public string Name { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime CreatedOn { get; set; }
    }
```

### `OnModelCreating`

```cs
        protected override void OnModelCreating(ModelBuilder builder) {
            builder.Entity<Identity>(entity => {
                                                  entity.Property<int?>("Group").IsRequired(false);
                                                  entity.Property<int?>("Person").IsRequired(false);

                                                  entity.HasIndex("Group").IsUnique().HasFilter(null);
                                                  entity.HasIndex("Person").IsUnique().HasFilter(null);
                                              });

            builder.Entity<Identity>(entity => {
                                         entity.HasOne(i => i.BackingGroup)
                                               .WithOne().IsRequired(false).HasForeignKey(typeof(Identity), "Group");

                                         entity.HasOne(i => i.BackingPerson)
                                               .WithOne().IsRequired(false).HasForeignKey(typeof(Identity), "Person");
                                     });
        }
```

### Migration

```cs
...
            migrationBuilder.CreateIndex(
                name: "IX_Identities_Group",
                table: "Identities",
                column: "Group",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Identities_Person",
                table: "Identities",
                column: "Person",
                unique: true);
```

### SQL (`script`)

```SQL
...

CREATE UNIQUE INDEX [IX_Identities_Group] ON [Identities] ([Group]);
GO


CREATE UNIQUE INDEX [IX_Identities_Person] ON [Identities] ([Person]);
GO
```

## Description

My goal with this code is to explicitly create a nullable foreign key on a "switch" table (`Identities`) that refers to either a person, or a group.

A small quirk here is that the unique index (to make sure no more than 1 identity refers to a person) has its null-check nullified with `.HasFilter(null)` on the end.

Removing this restores the `filter: "[Group] IS NOT NULL"` on migration `CreateIndex` entries, and `WHERE [Person] IS NOT NULL` on SQL `script` output.

### Include provider and version information

EF Core version: 5.0.0
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `.NET Core 3.1`
Operating system: PopOS!_20 (effectively Ubuntu 20)
IDE: `JetBrains Rider 2020.2.4`

### Notes

Possible regression from #20136

**Comment by ajcvickers** [comment]
@ShadowJonathan When you call, `HasFilter(null)`, then you are telling EF not to create a filter. You can pass your own filter to `HasFilter` including whatever you need in that filter. I'm struggling to understand what is not working here.

**Comment by ShadowJonathan** [comment]
@ajcvickers documentation and supplemental reading all point towards the fact this should unilaterally create a "If <insert name here> is not null" filter, only autogenerated for every sql database type.

**Comment by ajcvickers** [comment]
@ShadowJonathan Sorry, but I'm really not following what you are asking at all. Could you point to the relevant parts of the documentation and supplemental reading that you are referring to?

**Comment by ShadowJonathan** [comment]
Oh, pardon, I was referring to a clause [here](https://docs.microsoft.com/en-us/ef/core/modeling/indexes#index-filter), which I must've misremembered.
