### ISSUE TITLE
ChangeTracker Update EntityState to Modified even when All properties Value Are The Same 

### ISSUE THREAD

**Issue by tlejmi** [dotnet/efcore#23465]
When Update an Entity and All the values are the same. ChangeTracke detected all properties  I assigned to them the same value as Modified and Send an Update Request with all value to the database. 

```
                var options = new JsonSerializerOptions
                {
                    IgnoreNullValues = true
                };
                var log = new TrackableLog
                {
                    User = user,
                    EntityKey = entry.Properties.FirstOrDefault(x => x.Metadata.IsPrimaryKey())?.CurrentValue.ToString(),
                    Action = operation,
                    Entity = entry.Metadata.GetTableName(),
                    Time = now,
                };
                   var objectidenitifier = StoreObjectIdentifier.Create(entry.Metadata, StoreObjectType.Table); 
                    var modificationDictionary = new Dictionary<string, string>();
                    var modifiedProperty = entry
                        .Properties.Where(
                            x => x.IsModified 
                                 && x.Metadata.Name != nameof(ITrackable.LastModifiedBy)
                                 && x.Metadata.Name != nameof(ITrackable.CreatedAt)
                                 && x.Metadata.Name != nameof(ITrackable.LastModifiedAt)
                                 );
                        

                    foreach (var property in modifiedProperty)
                    {
                        var name = property.Metadata.GetColumnName(objectidenitifier!.Value);
                    
                        var current = property.CurrentValue.ToString();
                        var original = property.OriginalValue.ToString();

                        if (!string.Equals(current?.Trim(), original?.Trim()))
                        {
                            modificationDictionary.Add(name, current);
                        }
                    }
                     log.Changes = JsonSerializer.Serialize(modificationDictionary, options); 
```

In This Example, I try to detect the changes in my Entries where entry.State == EntityState.Modified in  SaveChanges override. 
When I try to update my Entry with the same Value I get an empty Dictionary. 

 

I think it can be Optimised, and Compare between CurrentValue and OrginalValue before modifying the Entry.Status to Modified and Send an Update Request to the database.

**Comment by ajcvickers** [comment]
@tlejmi The purpose of the DbContext and DbSet Update methods is to start tracking a disconnected entity and mark all properties as modified. Update is typically used because you don't know which properties may have been modified while the entity was not being tracked. If this information is known, then it would be better to use Attach and then individually mark properties as modified. Also, if you're not using disconnected entities, then you shouldn't use Update or Attach at all; EF will automatically mark individual properties as modified.
