### ISSUE TITLE
Cosmos: Allow mapping custom partition key in generated Many-to-Many join table

### ISSUE THREAD

**Issue by braidenstiller** [dotnet/efcore#23467]
Currently when configuring a many-to-many relationship with the fluent API there isn't a way to configure (and provide a value to) a custom partition key on the auto-generated join table.

For example, there are two objects, _Post_ and _Tag_ with a many-to-many relationship.

```
public class Post
{
    public string PostId { get; set; }
    public string PartitionId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public ICollection<Tag> Tags { get; set; }
}

public class Tag
{
    public string TagId { get; set; }
    public string PartitionId { get; set; }

    public ICollection<Post> Posts { get; set; }
}
```

Using the fluent API we could map this to the same container that has our Post and Tags objects, however if the container has an already established partition key that is not present on the join, this will fail.

With the following configuration:
```
entityTypeBuilder
    .Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
    .UsingEntity(join => 
    {
        join.HasPartitionKey("PartitionId");
        join.ToContainer("SomeExistingDataContainer);
    });
```

As of v5, entity keys now include their Id **and** partition Id together. This means on the autogenerated join the partition id's for both already come through, e.g:

```
PostTag Join Table
{
    "PostId": "",
    "PostPartitionId": "",        <------------
    "TagsId": "",
    "TagsPartitionId": "",        <------------
    "Discriminator": "",
    "id": "",
    .. etc
}
```

Mapping either of these fields to the container partition scheme would solve this issue. 
For example in the fluent API:

```
entityTypeBuilder
    .Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
    .UsingEntity(join => 
    {
        join.Property("PostPartitionId").ToJsonProperty("PartitionId");
        join.HasPartitionKey("PartitionId");
        join.ToContainer("SomeExistingDataContainer);
    });
```

However currently this would fail with the following:
_System.InvalidOperationException: 'The partition key for entity type 'PostTag (Dictionary<string, object>)' is set to 'PartitionId', but there is no property with that name.'_

This limitation restricts the usefulness of the new many-to-many mapping when using the Cosmos provider.

**Comment by smitpatel** [comment]
May be a typo in `join.HasPartitionKey("PartitionId");` It should be `join.HasPartitionKey("PostPartitionId");` which is the name of the property in EF model.

**Comment by braidenstiller** [comment]
> May be a typo in `join.HasPartitionKey("PartitionId");` It should be `join.HasPartitionKey("PostPartitionId");` which is the name of the property in EF model.

This normally would be the case, but because we're putting the Join entity into the already existing container "SomeExistingDataContainer" with it's **own** partition key scheme (in this case "PartitionId" - as you can see is present on both the Tag and Post models) we get an error saying that you can't add an entity with partition key "PostPartitionId" when the container is already setup with "PartitionId" as the partition key.

**Comment by smitpatel** [comment]
That is still the case. The value you provide in `HasPartitionKey` API is the name of the property in the EF Model. Your partition key in database being called "PartitionId" is not related to it. So you would need to call it with "PostPartitionId" only.

The following code listing will achieve same container and same column for partition key for all
```C#
modelBuilder.Entity<Post>().HasPartitionKey(e => e.PartitionId).ToContainer("Container");
modelBuilder.Entity<Tag>().HasPartitionKey(e => e.PartitionId).ToContainer("Container");
modelBuilder.SharedTypeEntity<Dictionary<string, object>>(
    "PostTag",
    e =>
    {
        e.IndexerProperty<string>("TagId");
        e.IndexerProperty<string>("PostId");
        e.IndexerProperty<string>("PartitionId");
        e.HasKey("TagId", "PostId", "PartitionId");
        e.ToContainer("Container");
        e.HasPartitionKey("PartitionId");
    });
modelBuilder.Entity<Post>().HasMany(e => e.Tags).WithMany(e => e.Posts)
    .UsingEntity<Dictionary<string, object>>(
        "PostTag",
        e => e.HasOne<Tag>().WithMany().HasForeignKey("TagId", "PartitionId"),
        e => e.HasOne<Post>().WithMany().HasForeignKey("PostId", "PartitionId"));
```
(This assumes that partition key for posts and tags which are related to each other would be same. If that is not the case then additional user input is required in terms of what should be the partition key for the join entity if post and tags are in different partition)

The configuration of join entity is done before configuring many to many because of bug #23476

**Comment by braidenstiller** [comment]
> That is still the case. The value you provide in `HasPartitionKey` API is the name of the property in the EF Model. Your partition key in database being called "PartitionId" is not related to it. So you would need to call it with "PostPartitionId" only.
> 
> The following code listing will achieve same container and same column for partition key for all
> 
> ```cs
> modelBuilder.Entity<Post>().HasPartitionKey(e => e.PartitionId).ToContainer("Container");
> modelBuilder.Entity<Tag>().HasPartitionKey(e => e.PartitionId).ToContainer("Container");
> modelBuilder.SharedTypeEntity<Dictionary<string, object>>(
>     "PostTag",
>     e =>
>     {
>         e.IndexerProperty<string>("TagId");
>         e.IndexerProperty<string>("PostId");
>         e.IndexerProperty<string>("PartitionId");
>         e.HasKey("TagId", "PostId", "PartitionId");
>         e.ToContainer("Container");
>         e.HasPartitionKey("PartitionId");
>     });
> modelBuilder.Entity<Post>().HasMany(e => e.Tags).WithMany(e => e.Posts)
>     .UsingEntity<Dictionary<string, object>>(
>         "PostTag",
>         e => e.HasOne<Tag>().WithMany().HasForeignKey("TagId", "PartitionId"),
>         e => e.HasOne<Post>().WithMany().HasForeignKey("PostId", "PartitionId"));
> ```
> 
> (This assumes that partition key for posts and tags which are related to each other would be same. If that is not the case then additional user input is required in terms of what should be the partition key for the join entity if post and tags are in different partition)
> 
> The configuration of join entity is done before configuring many to many because of bug #23476

Works perfect!
