### ISSUE TITLE
I am facing issue With Removing User From Role  As well as 

### ISSUE THREAD

**Issue by Raviniki** [dotnet/efcore#23474]
```
 var roles = await userManager.GetRolesAsync(user);            
  var result = await userManager.RemoveFromRolesAsync(user, roles);
```
this Throws Exception Like An exception occurred while iterating over the results of a query for context type 'LogicLevel.AppDbContext'.

Also At 
```
 userManager.AddToRoleAsync(user, role. Name)
``
same kind exception also happen over here An exception occurred while iterating over the results of a query for context type 'LogicLevel.AppDbContext
Microsoft.EntityFrameworkCore.Query: Error: 
EF Core version:6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 5.0)
Operating system: windows
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by Raviniki** [comment]
http://justonlybusiness.com/ 
is the URL  https://github.com/Raviniki/businesspoint.git where you can find all code for sample project register one user as admin and then try to go to admin activity and then after under admin activity manage role --> Add or Remove User -->then Select User -->Update Not Work 
As Well As All User-->Edit User -->Manage Role Also Not Work What is fix for that

**Comment by Raviniki** [comment]
i have provided the full code and every thing please clone the code and run
locally

**Comment by Raviniki** [comment]
i think i am good i found error like my identity user which i am saving using Sp don't have security stamp and concurrancystamp that why i am getting that error now i am closing that issue sorry for bothering Patel

**Comment by Raviniki** [comment]
solved
