### ISSUE TITLE
Reverse Engineering generates not needed code

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#23473]
.NET CLI Tools: 5.0.0

Generated code:
```
entity.Property(e => e.ChangedDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("('2014-07-22T10:34:48.440Z')")
                    .HasAnnotation("Relational:ColumnType", "datetime");
```

Should be:
```
entity.Property(e => e.ChangedDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("('2014-07-22T10:34:48.440Z')"));
```

Generated code:
```
entity.Property(e => e.OperationArt)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsFixedLength(true);
```

Should be (default parameter value for `IsFixedLength()` is true):
```
entity.Property(e => e.OperationArt)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsFixedLength();
```

**Comment by ErikEJ** [comment]
Which provider?

**Comment by smitpatel** [comment]
ColumnType annotation is already removed from scaffolded code in 5.0 release. See https://github.com/dotnet/efcore/issues/22564
Have you upgraded all your packages and tooling to 5.0 RTM?

**Comment by Saibamen** [comment]
@ErikEJ: `Microsoft.EntityFrameworkCore.SqlServer`

@smitpatel: Ahhh sorry, I was on wrong branch (RC1). You are right.

Still in TODO: `.IsFixedLength(true)`

**Comment by ajcvickers** [comment]
@Saibamen Please post the database schema that results in reverse engineering to `.IsFixedLength(true)` where it is not needed so that we can investigate.

**Comment by Saibamen** [comment]
@ajcvickers This method is needed.

What is not needed is `true` parameter, because `true` is the default value for `IsFixedLength()` ;)

**Comment by ramanathanv** [comment]
Hi @ajcvickers . I would like to fix this issue as a first contribution to this library.

**Comment by ramanathanv** [comment]
Hi @ajcvickers . Can you please provide some pointers on the class/method that needs to be fixed?

**Comment by ajcvickers** [comment]
@ramanathanv [CSharpDbContextGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs) is the class the controls code generation of the DbContext. It looks like `IsFixedLength` comes from [AnnotationCodeGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Design/AnnotationCodeGenerator.cs).
