### ISSUE TITLE
Migration on Helm pre-install and pre-update hook

### ISSUE THREAD

**Issue by peirens-bart** [dotnet/efcore#23489]
I'm new to Kubernetes and Helm deployment.
I want to update my microservice using Helm deployment on a Kubernetes cluster. The problem I'm having is how to handle database scheme changes when having more than 1 pod on my service. and not breaking the other pods during the update.
I also don't want that my new version is kicked out during booting because of the migration and therefore missing the health check.
But I'm not sure if what I want to do is a good idea and how to do it the right way.

in my Helm script, I want to use the pre-install en pre-update hook for executing the migration script or command.
But I also need to have a rollback in case the new version of the container has an issue.

Do I need to make a special container where I run a PowerShell script that executes the generated scripts. if so how do I generate a rollback script using the dotnet cli.

Or can I create a container and use the dotnet cli directly from the entry point like starting my application. I think do the only thing that I need then is the dotnet ef tool cli inside the container and the assembly with my context.

Or any other options where I can be sure that the migration is done properly.

**Comment by roji** [comment]
@peirens-bart we highly recommend to *not* apply migrations when your application (or container/pod) starts up, specifically when multiple instances of your application may be running (and therefore conflicting with one another). 

You can generate a migration SQL script (e.g. as part of your CI process) and execute that directly against the database - generating a rollback script is simply a matter of specifying a source migration that's newer than the target migration. Or you can use the `dotnet ef database update` command-line tool to bring your database to a specific migration point - it should be easy to get this running inside a container.

Some more information is available in the docs on [applying migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli).

**Comment by peirens-bart** [comment]
@roji thanks for the fast reply.

so the steps needed when having a database schema change is
* stop service + pod
* execute SQL script
* redeploy services

do you have an example of running dotnet ef cli from inside a container, or is this as easy as

`
ENTRYPOINT ["dotnet","ef database update"]
`

**Comment by roji** [comment]
Assuming you're container is set up correctly, yeah, it should be that simple... Whether you need to stop all your apps depends on various things, but as a general rule yeah, it's definitely recommended and the simpler way to go.

FYI We're also looking into "migration bundles" which should provide an even more streamlined experience for applying migrations.
