### ISSUE TITLE
How to do a query that uses "CROSS APPLY" that multiplies number of records

### ISSUE THREAD

**Issue by seerek** [dotnet/efcore#23492]
Let say I have following SQL Server table

```sql
create table VATReport
(
	Field varchar(10) not null
	, Base decimal(38,20) not null
	, Amount decimal(38, 20) not null
);
```
with following data:
```sql
insert into VATReport (Field, Base, Amount)
values ('P_48', 1, 1);
```
How can I setup my DBContext and write LINQ query that will produce following sql?:
```sql
select f.*
from VATReport as v
cross apply
(
	select * from (values (v.Field, v.Base, v.Amount)) as x(Field, Base, Amount)
	union all
	select * from (values ('P_53', null, v.Amount), ('P_54', null, v.Amount)) as x(Field, Base, Amount)
	where v.Field = 'P_48'
) as f
```
and produces following results
|Field|Base|Amount|
|---|---|---|
|P_48|1|1|
|P_53|NULL|1|
|P_54|NULL|1|

LINQ Query should probably look more or less like:
```csharp
from v in ctx.VATReport
from f in ??? //what to type here?
select f
```
I had some hopes that [FromExpression() method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.fromexpression?view=efcore-5.0) can be used for such cases, but unfortunately seems that it handles only TVF.
Main problem seems to be that I want to generate records out of thin air.
In my case I want to create 3 records from one.

Another way to ask this question is:
How to do in Entity Framework LINQ following sql query:
```sql
select 1, 'abc'
```
Is it possible?

**Comment by ajcvickers** [comment]
@maumar to de-dupe.

**Comment by maumar** [comment]
EF Core currently doesn't allow for creating rows explicitly. The improvement is tracked by: https://github.com/dotnet/efcore/issues/6660
