### ISSUE TITLE
RC2 fixed issues have empty elements

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#23499]
ULRs:

https://github.com/dotnet/efcore/issues?q=is%3Aissue+milestone%3A5.0.0-rc2+is%3Aclosed+label%3Atype-bug+is%3Aclosed
https://github.com/dotnet/efcore/issues?q=is%3Aissue+milestone%3A5.0.0-rc2+is%3Aclosed+label%3Atype-enhancement+is%3Aclosed

These URLs is from Release Notes: https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2.md

Also there is missing documentation for new changes in RC2: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew
![image](https://user-images.githubusercontent.com/905878/100376014-103ce100-300f-11eb-9666-a2fb81d28cc6.png)

### The problem

Users need to read long posts in this issue https://github.com/dotnet/efcore/issues/19549 to check what was changed between RC1 and RC2 and between RC2 and RTM...

**Comment by roji** [comment]
@Saibamen I've just submitted a PR reworking the 5.0 "what's new page", removing all preview-related information. Since 5.0 is now generally available, we don't think that per-preview information is valuable any more.

**Comment by Saibamen** [comment]
@roji: IMHO this is useful for developers who are still in Preview X/RC X

**Comment by ajcvickers** [comment]
@Saibamen The What's New document is intended to provide a brief overview of new features. EF Core 5.0 was feature complete in RC1, which means there are no new features to document for RC2 and RTM. This document is not intended to list all issues fixed-GitHub has that info. That being said, I agree that since we consolidate issues for RTM it does become hard to find what changed from the last preview you were on. I'll think about if we can do something better there.

**Comment by Saibamen** [comment]
>This document is not intended to list all issues fixed

OK, I understand, but

>GitHub has that info

No, it doesn't. Please see my first two URLs in my first post here.
For example: https://github.com/dotnet/efcore/issues?q=is%3Aissue+milestone%3A5.0.0-rc2+is%3Aclosed+label%3Atype-bug+is%3Aclosed
This URL is copy-pasted from RC2 Release Notes in GitHub.

But IMO it is too late to fix these labelling (or maybe it is just typo in URLs - if yes - just quick fix it in https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2.md)

**Comment by ajcvickers** [comment]
@Saibamen That's what I meant by, "That being said, I agree that since we consolidate issues for RTM it does become hard to find what changed from the last preview you were on. I'll think about if we can do something better there."
