### ISSUE TITLE
[5.0.0] NullReferenceException while trying to get EntityTypeBuilder. Was working in RC1

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#23497]
I'm upgrading EF Core 5 RC1 directly to RTM, but this bug also occurs in RC2 (I checked it few minutes ago).

BTW: There is missing documentation for RC2 changes: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew

### Include your code

```C#
public class MyContext : DbContext
{
	public ModelBuilder EntityModelBuilder { get; private set; }
	public EntityValidator EntityValidator => new EntityValidator();

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
	    EntityModelBuilder = modelBuilder;
	    new MyModelBuilder(modelBuilder).ApplyConfigurations();
	}
}
```

```C#
public class DbContextRepository<T, U> : IDisposable, IRepository<T> where T : class where U : DbContext
{
    protected readonly U _context;
    protected readonly DbSet<T> _set;

    public DbContextRepository(U context)
    {
        _context = context;
        _set = _context.Set<T>();
    }

    public virtual bool Save()
    {
        var entities = _context.ChangeTracker.Entries();
        var myContext = _context as MyContext;

        // validator
        myContext.EntityValidator.EnsureContextValidationOrThrowException(entities, myContext.EntityModelBuilder);

        return _context.SaveChanges() > 0;
    }
}
```

```C#
public class EntityValidator
{
    public void EnsureContextValidationOrThrowException(IEnumerable<EntityEntry> entities, ModelBuilder modelBuilder)
    {
        if (modelBuilder == null)
        {
            // modelBuilder can be null if DB operations & SaveChanges() happen in filters when context.OnModelCreating() was not called yet
            return;
        }

        var addedModifiedEntities = (from entry in entities
            where entry.State == EntityState.Modified || entry.State == EntityState.Added
            select entry.Entity);

        foreach (var entity in addedModifiedEntities)
        {
            // Get the EF EntityTypeBuilder<T> for our entity
            var entityTypeBuilder = modelBuilder.Entity(entity.GetType());
        }
    }
}
```

### Include stack traces

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Terefere.Kuku.Data.TTT.Context.Infrastructure.EntityValidator.EnsureContextValidationOrThrowException(IEnumerable`1 entities, ModelBuilder modelBuilder) in C:\Terefere\Kuku\Source\Libs\Terefere.Kuku.Data.TTT.Context\Infrastructure\Validation\EntityValidator.cs:line 44
```

### More info

From debugger:
![image](https://user-images.githubusercontent.com/905878/100368701-31e49b00-3004-11eb-92ba-592ab80c563b.png)

**Important note:**

This code was working without this NRE exception in RC1!

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows
IDE: Visual Studio 2019 16.8.2

**Comment by smitpatel** [comment]
ModelBuilder is not supposed to be used after model is built. Use `IModel` instead.

**Comment by Saibamen** [comment]
@smitpatel: Thanks. I rewrited my code to use `MyContext.Model` (which is `IModel`) and it worked without any problems now.

But I am wondering why there is no info about this breaking change in RC2 docs?

**Comment by ajcvickers** [comment]
> But I am wondering why there is no info about this breaking change in RC2 docs?

Basically because it never occurred, at least to me, that someone would keep a reference to the ModelBuilder taken from OnModelCreating and then try to use the builder in the future long after the model is built. We maybe should have defensive code that checks for this, but since it is something we never even thought about, we don't.

I'm curious, when you were writing the code, did you not think that storing the ModelBuilder away and using later was a strange thing to do?

**Comment by Saibamen** [comment]
@ajcvickers This code was written by my colleague from my team about 6 months ago.
This is what he says:
>I would have to come back to this topic, but I did it because it turned out to be needed when rewriting from the previous version of the code for filters / model validation.
I saved the variable "for later" because I didn't know how to get to it in `EntityValidator` (but maybe I didn't look long enough and there was a "whatever, but it works" solution).
