### ISSUE TITLE
MigrationBuilder.InsertData not considering column types passed in

### ISSUE THREAD

**Issue by fearhq** [dotnet/efcore#23503]
EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1
Operating system: Windows 10
IDE: N/A

When using MigrationBuilder.InsertData to work on a table that has no EF mappings, MigrationBuilder.InsertData does not take into account the columnTypes that are passed in

**Comment by fearhq** [comment]
I mentionned in the PR that added the columnType overloads that for InsertData the value was simply ignored
https://github.com/dotnet/efcore/pull/22346

**Comment by AndriySvyryd** [comment]
Vote 👍 on the first comment if you are also experiencing this issue.
