### ISSUE TITLE
Proposal: add <auto-generated> comment in files generated with dotnet ef dbcontext scaffold

### ISSUE THREAD

**Issue by 0xced** [dotnet/efcore#23514]
Files generated with the `dotnet ef dbcontext scaffold` command may generate warnings for tools such as ReSharper, for example:
* Using directive is not required by the code and can be safely removed
* Partial class with single part
* Partial method without implementing declaration

A solution to make these warnings disappear would be to add an *auto-generated* comment header:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated with the dotnet-ef tool.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```

**Comment by ErikEJ** [comment]
EF Core Power Tools does that!

**Comment by 0xced** [comment]
Good to know, thanks! I'll try it next time.

But I think it's still important to have this feature in the dotnet-ef tool which is cross-platform.

**Comment by ErikEJ** [comment]
Sure!

**Comment by ajcvickers** [comment]
This is not unreasonable given a workflow that regenerates these files. However, rather than add a specific option to the command line tool for this, it will covered by templates: #4038. See also #831.

**Comment by hades200082** [comment]
These days you can add the following to your .editorconfig file (adjust the file path in the square brackets as needed)

```ini
# Do not apply code styles to generated migration files
[**/Migrations/*.cs]
generated_code = true
```

**Comment by JDAVF** [comment]
@roji  The two tickets #28180 and this were closed as duplicate of each other. Please reopen one of them

**Comment by ErikEJ** [comment]
Easy to do in the EF Core team provided t4 templates these days

**Comment by JDAVF** [comment]
> Easy to do in the EF Core team provided t4 templates these days

Yes, but T4 are only needed if you need to customize. T4 is not the default option and the code should always be marked as auto-generated.

**Comment by roji** [comment]
@JDAVF it should not; code generated with `dotnet ef dbcontext scaffold` is meant to be editable by users for whatever customizations they need to do. This is very different from truly generated code which should never be touched by users.

**Comment by ErikEJ** [comment]
@roji Exactly, unlike code generated by EF Core Power Tools, which also always includes the header
