### ISSUE TITLE
Proposal: prevent generating a default DbContext constructor when using dotnet ef dbcontext scaffold --no-onconfiguring

### ISSUE THREAD

**Issue by 0xced** [dotnet/efcore#23515]
Version 5.0.0 of the dotnet-ef tool introduced the `--no-onconfiguring` option which is great if you plan to configure your DbContext outside of the context itself (which you probably should).

When using this option, the DbContext class is still generated with a default constructor. This default constructor becomes problematic without the `OnConfiguring` method since the context is unusable when created through the default constructor. As soon as you try to use a DbContext created by the default constructor, you get a `System.InvalidOperationException`:
> No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

The scaffolded DbContext classes should be fool proof. So I strongly encourage you to consider not generating the default constructor when the `--no-onconfiguring`  option is enabled.

**Comment by ajcvickers** [comment]
The default constructor can still be used if OnConfiguring is in a partial class. However, if there is already a partial class for OnConfiguring, then adding a parameterless constructor to that partial seems reasonable, so we will consider this as a future enhancement.
