### ISSUE TITLE
Is HasQueryFilter applicable when using Load method?

### ISSUE THREAD

**Issue by sserbula** [dotnet/efcore#23510]
I have class `Cycle` that contains list of `employees`. `Employee` has `User` property that is reference to `User` and `User` has property `IsDeleted` because we use soft delete. We use `HasQueryFilter(e => !e.IsDeleted)` to prevent getting deleted user. With `Include` this works perfectly, but because of performance issues in EF 3.1 we started using `Load`. Everything is much faster but `HasQueryFilter` is not applied and I get `Employee` with `User` that is null. Is `HasQueryFilter` not applicable with load?

When using include: List of employees is empty(because User inside Employee is soft deleted) - expected result
When using load: List of employees is not empty(I get Employee entities where User is null but UserId is not null) - problem

```
public class Employee
{
     ...
     public ICollection<CycleEmployee> Employees { get; protected set; } = new List<CycleEmployee>();
}

public class CycleEmployee
{
    public User User { get; protected set; }
    public Guid UserId { get; protected set; }
}
```

Fetching data with load:

```
public Cycle GetCycle(Guid cycleId, params string[] includeProperties)
        {
            var query = DbContext
                .Cycles
                .Where(e => e.OrganizationId == CurrentUser.OrganizationId);
            var cycle = query.SingleOrDefault(e => e.Id == cycleId);
            query.LoadMultipleProperties(includeProperties);

            return cycle;
        }

public static void LoadMultipleProperties<T>(this IQueryable<T> query, params string[] includeProperties)
            where T : class
        {
            foreach (var prop in includeProperties)
            {
                query.Include(prop).Load();
            }
        }
```

### Include provider and version information

EF Core version: 3.1.10
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET core 3.1)
Operating system: Windows
IDE: (e.g. Visual Studio 2019 16.8.2)

**Comment by ajcvickers** [comment]
@sserbula I have not been able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sserbula** [comment]
@ajcvickers I am trying to reproduce this error in my mini project as well, but I can't, hopefully I will manage to do it.

**Comment by sserbula** [comment]
@ajcvickers I did it, here is repo - https://github.com/SerlokPK/ef-core-load-method-bug/tree/master

Everything is set, you only need to start app and hit endpoints from swagger (there is simple guide in read me)

**Comment by smitpatel** [comment]
Query filter is being applied to Load successfully too. The issue is badly defined query filters.
You have required navigation from dependent to principal which has query filter defined which causes orphans in database even though you mark as required which generates incorrect results. We also show warning for it.

See https://docs.microsoft.com/en-us/ef/core/querying/filters#accessing-entity-with-query-filter-using-required-navigation for more details.
