### ISSUE TITLE
Cloud Firestore support in EFCore.

### ISSUE THREAD

**Issue by sps014** [dotnet/efcore#23520]
[Cloud Firestore](https://firebase.google.com/docs/firestore) is a flexible, scalable database for mobile, web, and server development from Firebase and Google Cloud Platform. Like Firebase Realtime Database, it keeps your data in sync across client apps through real-time listeners and offers offline support for mobile and web so you can build responsive apps that work regardless of network latency or Internet connectivity. 

Currently [Google.Cloud.Firestore](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/) provides API to interact with Database from C#. It also support Simple and compound Queries.
```cs
CollectionReference citiesRef = db.Collection("cities");

Query chainedQuery = citiesRef
    .WhereEqualTo("State", "CA")
    .WhereLessThan("Population", 1000000);

```
model is defined as 
```cs
[FirestoreData]
public class Post
{
     [FirebaseProperty]
     public string Message {get;set;}
}
```
Firestore is widely used database, The goal is to have API similar to EFCore.
Support for it in EFCore will be highly useful to many people including me.<br>
Thank you

**Comment by ajcvickers** [comment]
@sps014 It's unlikely that we will implement this provider on the EF team. However, we would be supportive of a community effort to create such a provider, such as has been done for [MySQL](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql), [PostgreSQL](https://github.com/npgsql/efcore.pg), and others. However, keep in mind that a full EF Core database provider is a big undertaking.

**Comment by sps014** [comment]
Community plugins will be better options..
I Will explore that.
Thanks

**Comment by saviour123** [comment]
Firebase Datastore provider would be great considering there is a support for Mongo, this means its possible for FB to be supported, I would like to reopen this in 2025, whats the plan?

**Comment by roji** [comment]
@saviour123 as written above, it's very unlikely the EF team will be developing a provider for Firebase - it's not feasible for us to write the providers for all the databases in the world (note that the Mongo provider is also not written by us). This is something that would be better for someone from the community to pick up.
