### ISSUE TITLE
Savepoints not supported with SQL Server memory-optimized tables

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#23526]
Originally raised by @phonglevishn in https://github.com/dotnet/EntityFramework.Docs/pull/2698#issuecomment-735734472.

<details>
<summary>Workaround that completely disables savepoints which can be used with 5.0, reverting to the 3.1 behavior</summary>

```c#
public class MyDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(....)
            .ReplaceService<IRelationalTransactionFactory, NoSavepointsTransactionFactory>();
}

public class NoSavepointsTransactionFactory : IRelationalTransactionFactory
{
    public virtual RelationalTransaction Create(
        IRelationalConnection connection,
        DbTransaction transaction,
        Guid transactionId,
        IDiagnosticsLogger<DbLoggerCategory.Database.Transaction> logger,
        bool transactionOwned)
        => new NoSavepointsTransaction(connection, transaction, transactionId, logger, transactionOwned);

    class NoSavepointsTransaction : RelationalTransaction
    {
        public NoSavepointsTransaction(
            IRelationalConnection connection,
            DbTransaction transaction,
            Guid transactionId,
            IDiagnosticsLogger<DbLoggerCategory.Database.Transaction> logger,
            bool transactionOwned)
            : base(connection, transaction, transactionId, logger, transactionOwned)
        {
        }

        public override bool SupportsSavepoints => false;
    }
}
```

</details>

**Comment by phonglevishn** [comment]
> Originally raised by @phonglevishn in [dotnet/EntityFramework.Docs#2698 (comment)](https://github.com/dotnet/EntityFramework.Docs/pull/2698#issuecomment-735734472).
> 
> Workaround that completely disables savepoints which can be used with 5.0, reverting to the 3.1 behavior

Thanks for answering. I will try this. I tried changing the SupportsSavepoints but it only allows get. I still like the option of using savepoint on a case-by-case basis. Hope this property can be set manual

**Comment by roji** [comment]
@phonglevishn yeah, the limitation around memory-optimized tables definitely points towards a user-configured flag on a particular transaction, which would opt out of it. You can probably achieve that by providing your own subclass of SqlServerTransaction, where you'd have a setter to control SupportsSavepoints.
