### ISSUE TITLE
EFCore v5.0.0, VS2019, .NET Core 3.1 - An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created

### ISSUE THREAD

**Issue by fenton-nick** [dotnet/efcore#23534]
## EFCore v5.0.0, VS2019, .NET Core 3.1 - An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created.

I am getting the following warning when building a project with EFCore 5 in VS2019. 

This is happening on brand new .NET Core 3.1 project with a fresh install of EFCore v5. I ran `dotnet ef dbcontext scaffold` which worked fine. After that, these build + intellisense warnings showed up. 

Note: the build succeeds and the project functions as is it should.

```
Warning	CS8032	An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from 
C:\Users\<redacted>\.nuget\packages\microsoft.entityframeworkcore.analyzers\5.0.0\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll: 
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	

```

Here's my csproj

```xml

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    ...
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
  </ItemGroup>

  ...
```

**Comment by roji** [comment]
@fenton-nick can you please try the following on the command-line:

* git clean -xfd (at the root)
* dotnet build-server shutdown
* dotnet build

And confirm whether you still see the error? If the error persists, it would be great if you can just share the project as a github repo, or emailed as a ZIP (see the email on my profile)

**Comment by fenton-nick** [comment]
Just finished update VS2019 from v16.4.3 to v16.8.2.

The build warning appears to be gone. We can close this for now. I'll follow up if the issue comes back.

**Comment by rubens-lopes** [comment]
Having the same issue on JetBrains Rider 2021.2.1, running on Windows 10

```
An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from .nuget\packages\microsoft.entityframeworkcore.analyzers\5.0.10\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
```

I've tried @roji suggestion, but it did not solve the error. :(

I can not share the repo since it is a corporate one.

**Comment by roji** [comment]
@rubens-lopes this kind of thing is almost always some sort of build or dependency issue - review your csproj, try to clean your project and rebuild from scratch on the command-line (to isolate whether this is a VS-related issue). If you're still seeing an issue, try to create a repro for this based on your actual corporate code; we don't need to see your actual project, just something that reproduces the problem. In the majority of cases, as part of working on a minimal repro, users come across the actual problem they had in their project and the problem is resolved that way.

**Comment by rubens-lopes** [comment]
Thank you for your time @roji, we solved the mystery.

Turns out the one of the .csproj has the tag `<WarningsAsErrors />` it was breaking the build on Rider and on Azure, but not on Visual Studio.

For now the time has decided to not update this package, beyond 3.1.*, util the next LTS.
