### ISSUE TITLE
Best practice for deleting a lot of data (bulk/nested delete)

### ISSUE THREAD

**Issue by andrejohansson** [dotnet/efcore#23533]
## Ask a question

Variants of this question have been asked a lot of times but I cannot seem to find a real and "official" answer of how to do this correctly.

We have a lot of entity types in our model (around 200). Most of these entities have a "owned by" relationship to one of the entities. This is our security model. To simplify from your example we could say that the entity ``User`` is the owner of entity ``Blog`` and entity ``Post``.

Since the ownership and security model is central in our system, it eventually leads to that our ``User`` entity have relationships to pretty much all other entities. I don´t see anything wrong with that (do you?), it makes sense that if a user owns a specific kind of entity then there is a relation.

The problem arises when I wan´t to delete and entity. 

- I can´t use cascade delete since it would require me to load all the entities that are owned before deleting. This would be to load an insane amount of data just to tell the db that is should be deleted. Loading hundreds of relations in a nested manner is just not viable.
- I know about third party solutions such as [Entity Framework Extensions](https://entityframework-extensions.net/bulk-delete) and others mentioned in #795. But for me, It´s not really viable since the extensions tie harder into the specific providers and become hard to test.

Now, I am wondering what is preventing ef from working in this manner?

1. I setup my relations and configure cascade delete (User owns blog, user owns posts, cascade delete is on)
1. I call something like ``ctx.Users.Delete(user, cascade: true);`` on an entity where I have **only loaded the top level** user.
1. Ef follows the parameter "cascade" and the configured relationships and for each it would generate:

```sql
DELETE FROM Posts WHERE Owner = userId;
DELETE FROM Blogs WHERE Owner = userId;
DELETE FROM Users WHERE Id = userId;
```
Why is there a need to load the entities first for ef?

Is there a best practice way for deleteing a large complex tree structure of data without having to resort to native sql (keeping my models and code provider-agnostic)?

### Include provider and version information

EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@andrejohansson Set-based deletes is tracked by #795. Currently, you can:
* Ensure that database-level cascades are set up (if your database supports the cascades you want) so that EF doesn't need to have all child entities loaded.
* Execute raw SQL commands to perform the deletes

**Comment by yangzhongke** [comment]
You can use this library [https://github.com/yangzhongke/Zack.EFCore.Batch](https://github.com/yangzhongke/Zack.EFCore.Batch)

**Comment by andrejohansson** [comment]
@ajcvickers and @yangzhongke, thanks for your replies. I will experiment a bit further and see whcih solution fits us the best!
