### ISSUE TITLE
sqlite-net-sqlcipher (1.7.335) does not work any more with actual version (5.0)

### ISSUE THREAD

**Issue by hsoehne** [dotnet/efcore#23546]
## File a bug

Microsoft.Data.Sqlite (3.1.10) works fine
Microsoft.Data.Sqlite (5.0.0) crashes

sqlite-net-sqlcipher (1.7.335) has to be installed
```C#

using Microsoft.Data.Sqlite;
namespace LocalDB
{
    public class LocalDb
    {
        public LocalDB()
        {
            var basePath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            var _dbcon = new SqliteConnection(@"Data Source =" + basePath + @"; Mode=ReadWriteCreate; Password = password"); 
            _dbcon.Open();
        }
    }
}
```

**Comment by ajcvickers** [comment]
@hsoehne Please post the exception message and full stack trace.

**Comment by hsoehne** [comment]
{System.InvalidOperationException: You specified a password in the connection string, but the native SQLite library 'e_sqlite3' doesn't support encryption.
  at Microsoft.Data.Sqlite.SqliteConnection.Open () [0x004aa] in <3f40aa4e535147a4a1d60be9d48aa8ed>:0 
  at LocalDB.LocalDb.Konstruktor () [0x0004a] in C:\source\AZ\LocalDB\LocalDB.cs:40 }

it happens at  _dbcon.Open();

**Comment by bricelam** [comment]
Since `sqlite-net-sqlcipher` references SQLitePCLRaw.bundle_e_sqlcipher, you should be referencing `Microsoft.Data.Sqlite.Core`. Otherwise you'll end up also referencing bundle_e_sqlite3 and the behavior is non-deterministic.

**Comment by hsoehne** [comment]
I tried it and nothing changed.

**Comment by bricelam** [comment]
Look through the .deps.json file (under bin) to make sure nothing else is bringing in `SQLitePCLRaw.bundle_e_sqlite3`

**Comment by hsoehne** [comment]
I looked there, but I could not recognize anything. (Perhaps because it is the first time I looked there). So I decided to delete all bin and object folders in the solution and to test it again, but no success.

**Comment by bricelam** [comment]
Can you provide a simplified repo project so we can investigate further?

**Comment by hsoehne** [comment]
I created a branch with title Issue23546. There you find a project, which throws the error with Android. I can not compile IOS. UWP works fine.

**Comment by ajcvickers** [comment]
@hsoehne Where is the branch?

**Comment by hsoehne** [comment]
It has been private. Now I turned it to public.

**Comment by ajcvickers** [comment]
@hsoehne That's great...but where is the branch? Can you post a link, please?

**Comment by hsoehne** [comment]
Sorry, it is my first time here.

https://github.com/hsoehne/Issue23546

I hope it helps

**Comment by bricelam** [comment]
@hsoehne It looks like you still need to uninstall the `Microsoft.Data.Sqlite` package from the projects (but keep Microsoft.Data.Sqlite**.Core**)

**Comment by hsoehne** [comment]
O.K. I did so. I removed Microsoft.Data.Sqlite and added Microsoft.Data.Sqlite.Core. Then I noticed my software takes a log time during startup and does not finish starting. So I debugged it once more. One connection was established, but not a second. Is it possible, that .Core only supports one connection at a time? If yes, it would not be a real saticefying solution.

**Comment by ajcvickers** [comment]
@hsoehne Connection pooling should help with that: https://github.com/dotnet/efcore/issues/13837
