### ISSUE TITLE
Discussion on using EF Core in an interactive C#  Jupyter notebook

### ISSUE THREAD

**Issue by AhmedKhalil777** [dotnet/efcore#23540]
In my Case,  I need to work on Efcore  example with data annotations but it can't mapped when migrations happened in the interactive environment 
![image](https://user-images.githubusercontent.com/38745087/100666508-cb43e200-3361-11eb-90d1-c87d49b018f9.png)

 the result is the `[Key]` annotation or any schema annotation not mapped in current migrations
![image](https://user-images.githubusercontent.com/38745087/100666720-1fe75d00-3362-11eb-9989-ded4fe579398.png)

**Comment by AhmedKhalil777** [comment]
## Are these features not working in the interactive c# ?
I think the fluent API can work good in this environment

**Comment by jonsequitur** [comment]
We are working on support for auto-scaffolding in .NET Interactive but haven't tried actually creating the model in a notebook yet. 

https://github.com/dotnet/interactive/pull/870

**Comment by smitpatel** [comment]
In very basic app without any package installation requiring, the app can detect the annotations so annotations are working.
Though I run into issue when trying to install EFCore.SqlServer package

![image](https://user-images.githubusercontent.com/1528107/101539766-e6ab8000-3953-11eb-982c-9c107dad4f00.png)

This issue should probably investigated by team which owns C# support in jupyter notebooks as it seems like there are multiple hoops to jump through even before reaching EF Core phase here.

**Comment by jonsequitur** [comment]
@smitpatel, the stack trace indicates you're using an early preview of Jupyter support in the `dotnet-try` tool. Please run the following to update:

```console
> dotnet tool install -g Microsoft.dotnet-interactive
> dotnet interactive jupyter install
```

One potential reason for the error you're seeing is that the version you're running targets .NET Core 3.0, but `#r nuget` without a version specification will grab EF 5. 

That said, I don't expect the issue that @AhmedKhalil777 raised to work in any version, nor do I think it can be fixed within C# scripting. C# scripting's assembly model is quite different from what EF expects, which I'm guessing is the problem. In effect, @AhmedKhalil777's two different code cells are compiled into two different assemblies.

One thing to try is to put all of the code into a single cell and see if that works.

**Comment by ajcvickers** [comment]
@jonsequitur Thanks for jumping in here. I love this integration of EF Core into notebooks! Let's work together with @JeremyLikness to track potential improvements/extensions to the experience.

**Comment by ajcvickers** [comment]
Putting this in the discussion milestone for other discussion on the experience with interactive notebooks.

**Comment by AhmedKhalil777** [comment]
Thanks much @ajcvickers , @jonsequitur , @smitpatel  for this discussion, returning to my notebook , my notebook worked perfectly , I don't know why, but reinstalling the assemblies again make it work, so I think there are some changes happened  on these packages.

The integration between jupyter notebook and .Net world is something so beauty, and this make students and university teachers and scientists bring .Net with their environment, thanks much .Net team and enjoy coding.

**Comment by JeremyLikness** [comment]
@ajcvickers I propose we include this as a consideration for EF Core 7. It sounds like it's working, but I think making the experience well-known and visible, perhaps documenting examples and polishing edge cases makes sense. Your thoughts? I'm happy moving this issue or consideration or filing a new one.

@AhmedKhalil777 can you share some of the experiences this enabled for you and ways you are working with it?

Jeremy

**Comment by jonsequitur** [comment]
For reference here's the blog post @LadyNaggaga wrote about the experience earlier this year: https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/

It describes both EF support and direct SQL query support. We're working on improvements in this area now.

**Comment by JeremyLikness** [comment]
I just went through the experience using our "getting started" example in a Jupyter notebook using .NET Interactive in Visual Studio Code, and it worked flawlessly. I am going to [add documentation](https://github.com/dotnet/EntityFramework.Docs/issues/4018) and close this issue.
