### ISSUE TITLE
Handling of Denormalized Data in Cosmos

### ISSUE THREAD

**Issue by wowfood** [dotnet/efcore#23541]
Example, I have the following models

    public class ItemModel
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    }

    public class StockModel
    {
        public string Id { get; set; }
        public ItemModel Item { get; set; }
        public int Stock { get; set; }
    }

    public class User
    {
        public IEnumerable<ItemModel> OwnedItems {get; set;)
    }

Based on the cosmosDB documentation, I'd want to handle this as denormalized data, which would embed the contents of ItemModel into User and into Stock.  To accomplish this, in the OnModelCreating method I have the following.

    builder.Entity<StockModel>().ToContainer("Stock");
    builder.Entity<StockModel>().OwnsOne(p => p.Item);

    builder.Entity<User>().ToContainer("Users");
    builder.Entity<User>().OwnsMany(p => p.OwnedItems);

On its own, this operates fine.  However I also need to be able to manipulate ItemModel separately.  Based on the Azure documentation, I should be able to have ItemModel embedded in my other entities, and update those using the ChangeFeed function.  However if I add

    builder.Entity<ItemModel>().ToContainer("Items");

I get an error 'The type 'Item' cannot be marked as owned because a non-owned entity type with the same name already exists.'

Is there any way to accomplish what I'm trying to do using EntityFramework.Core.Cosmos?  Or is denormalization in this sense not really possible.

**Comment by smitpatel** [comment]
I would suggest reading up https://docs.microsoft.com/en-us/azure/cosmos-db/modeling-data for detailed information about modelling in cosmos db.
In the example you have posted above, you are trying to embedded  `ItemModel` and also put it in separate container. Both at the same time is not possible and it is not efficient either. You should choose either of the mapping or come up with a hybrid model where embedded data is subset of actual data based on use.

**Comment by wowfood** [comment]
I have looked through that document, that's how I came to my above conclusion.

When to embed
In general, use embedded data models when:

There are contained relationships between entities.
There are one-to-few relationships between entities.
There is embedded data that changes infrequently.
There is embedded data that will not grow without bound.
There is embedded data that is queried frequently together.

The model I gave as an example matches those criteria.

https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-model-partition-example#v2-introducing-denormalization-to-optimize-read-queries

The document here also appears to include representing an entity as both its own, and embedded in other entitites.

**Comment by smitpatel** [comment]
From EF Core side an entity can either be owned/embedded or it can be separate regular entity and mapped to a container directly.  It cannot be both. 

If your model matches the criteria you highlighted then it should not be mapped to a separate container. They are not changed frequently and does not warrant any duplication to own container.
