### ISSUE TITLE
Analog of jpa repository in EF Core

### ISSUE THREAD

**Issue by ZhdanDeveloper** [dotnet/efcore#23544]
it would be very useful if EF Core had features similar to JPA repository(i mean base CRUD operations for entities), It would make development a lot easier.

**Comment by roji** [comment]
The EF Core DbContext can fulfil at least some of the neds of a JPA repository - it has methods for adding, loading and removing entities, and change tracking allows for easy updating (load, change, save). What exactly are you missing?

**Comment by ZhdanDeveloper** [comment]
there isn't one important thing for web development, for instance, in JPA you can create an interface UserRepository and inherit it from JPA interface, generalized by user entity, after that your interface have all base CRUD methods you need.
![image](https://user-images.githubusercontent.com/68823930/100756049-e2d0a880-33fd-11eb-8698-d70fbca154b8.png)

Without this feature developers have to manually create basic methods in each interface for every single entity(like on the picture below).
![image](https://user-images.githubusercontent.com/68823930/100757220-2677e200-33ff-11eb-9f98-2477ea5ae84a.png)

However, with feature from JPA it could be done like this : 
![image](https://user-images.githubusercontent.com/68823930/100757574-94240e00-33ff-11eb-8282-5f72f5627b96.png)

**Comment by roji** [comment]
All the methods you list above - possibly with the exception of RemoveCategoryByIdAsync - are already primitive operations on EF Core's DbSet (which can be viewed as a repository of sorts):

Your listed methods | EF Core equivalent
---- | ----
GetAll | context.Categories
GetById | context.Categories.Find(id)
AddCategoryAsync | context.Categories.Add(category)
SaveAsync | context.SaveChangesAsync
RemoveCategoryByIdAsync | context.Categories.Remove(context.Categories.Find(id))

Do you really feel like an additional wrapping layer is required here?
