### ISSUE TITLE
Minor typo in source file

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#23545]
Just stumbled across this very minor issue. The following contains `façade` with a `ç` instead of a `c` three times:
 https://github.com/dotnet/efcore/blob/eb180fe94d8efb1a68f9e12021ebc09aea854427/test/EFCore.Specification.Tests/TestUtilities/DatabaseFacadeExtensions.cs#L15-L16

**Comment by ajcvickers** [comment]
@lauxjpn Is this a problem? https://dictionary.cambridge.org/us/dictionary/english/facade

**Comment by lauxjpn** [comment]
@ajcvickers Oops, wasn't aware that his is actually correct English. I guess this can be ignored then :)

**Comment by ErikEJ** [comment]
@ajcvickers So line 12 is misspelled, then 😂 https://github.com/dotnet/efcore/blob/eb180fe94d8efb1a68f9e12021ebc09aea854427/test/EFCore.Specification.Tests/TestUtilities/DatabaseFacadeExtensions.cs#L12 ??

**Comment by lauxjpn** [comment]
@ErikEJ Well, I guess some are more posh then others on the team :)

**Comment by roji** [comment]
We should write "focussed" instead of "focus" and in general have more British spelling to give the project a more elitist scent.

**Comment by roji** [comment]
(plus, as I agreed I will start using Hebrew in identifiers)

**Comment by lauxjpn** [comment]
> (plus, as I agreed I will start using Hebrew in identifiers)

@roji I absolutely agree. This is 2020 after all!

Though I have successfully avoided pushing any useful commits to EF Core so far, I would really like to write some Japanese source code at some point in time, so I get quicker at typing with the Microsoft IME. (No worries, I wouldn't dare to use the honorific language level, as this might get a bit tricky to get right.)

**Comment by smitpatel** [comment]
You guys really want me to start using "ou" rather than "o"?

**Comment by roji** [comment]
No honorific - no contribution...
