### ISSUE TITLE
EntityTypeBuilder: .IsRequired() is ignored if used after .OnDelete() 

### ISSUE THREAD

**Issue by gukoff** [dotnet/efcore#23555]
## Problem

When configuring a non-nullable foreign key with FluentAPI, `.isRequired()` is ignored when called after `.OnDelete()`.

## Code

There are 2 models, connected by a 1-to-many relationship:
```C#
class Country {
   public long Id { get; set; }
}

class City {
   public long Id { get; set; }
   public Country Country { get; set; }
}
```

I'd like every city to belong to some country. This means, make the foreign key `City.CountryId` non-nullable.

Now, this doesn't work:

```C#
EntityTypeBuilder<City> builder;  // initialized

builder
.HasOne(city => city.Country)
.WithMany(country => country.Cities)
.OnDelete(DeleteBehavior.Restrict)
.IsRequired();   // after OnDelete
```

But this does:
```C#
EntityTypeBuilder<City> builder;  // initialized

builder
.HasOne(city => city.Country)
.WithMany(country => country.Cities)
.IsRequired()  // before OnDelete
.OnDelete(DeleteBehavior.Restrict);
```

__The only difference is the order of `IsRequired()` and `OnDelete()`.__

The first (buggy) snippet generates a database migration with a nullable foreign key:
```C#
CountryId = table.Column<long>(type: "bigint", nullable: true)
```
And the second doesn't:
```C#
CountryId = table.Column<long>(type: "bigint", nullable: false)
```

## Diagnostics

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: MacOS (reproducible on Windows too)
IDE: command line

**Comment by migellars** [comment]
Hi, @gukoff but _**I'd like every city to belong to some country.** __  a country should have many cities

**Comment by ajcvickers** [comment]
@AndriySvyryd This repros for me and is a regression from 3.1.
