### ISSUE TITLE
SqliteDataReader.GetStream is not working correctly in presence of composite primary keys

### ISSUE THREAD

**Issue by filipnavara** [dotnet/efcore#23554]
## File a bug

For a table definition `CREATE TABLE "a" ("id" INTEGER NOT NULL, "name" TEXT, "value" TEXT, PRIMARY KEY ("id", "name"));` the code in SqliteDataReader.GetStream would incorrectly interpret the "id" column as being the row ID. This happens because `sqlite3_table_column_metadata` identifies the `id` column as primary key and it has the `INTEGER` type. However, this is not satisfactory condition in presence of the composite primary keys and it will incorrectly identify the column as equivalent to `rowid` which it is not.

It's not trivial to fix the optimization since not all of the columns from the composite key have to be present as part of the result set so essentially all of the columns in the table would have to be examined to rule out the presence of the composite primary key.

### Include version information

Microsoft.Data.Sqlite version: 3bd012b6dc645f6d4e14ddb473c42f3fa4e0b98b
Target framework: .NET 5.0

**Comment by bricelam** [comment]
Regressed in 2.2.0

**Comment by bricelam** [comment]
@filipnavara As a workaround, you can add `rowid` (before id) to your SELECT clause:

```sql
SELECT rowid, id, name, value
FROM a
```

**Comment by filipnavara** [comment]
Thanks, I am aware of the workaround. We are using a fork anyway so this is not blocking us. We just started to upstream our changes or report the issues if we don't have a proper fix.

**Comment by bricelam** [comment]
Good bug. A fix is out for review.

To satisfy my own curiosity, I'd love to hear more about how you're using Microsoft.Data.Sqlite. If you're willing, you can send all the gory details to me at bricelam [at] (the notorious name of the company for which I work) [dot] com. Otherwise, thank you for reporting!
