### ISSUE TITLE
Throw DbUpdateException or DbUpdateConcurrencyException for in-memory database errors

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#23569]
See

Adding_the_same_entity_twice_results_in_DbUpdateException
Deleting_the_same_entity_twice_results_in_DbUpdateConcurrencyException
Deleting_then_updating_the_same_entity_results_in_DbUpdateConcurrencyException

**Comment by AnushreeDixit** [comment]
Hi, can I work on this issue ? @ajcvickers

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
