### ISSUE TITLE
Why does my non-nullable navigation property have a nullable backing field?

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/efcore#23588]
I created the following class:

```c#
class Post
{
    public Blog Blog { get; set; }
}
```

but the backing field in the database is `BlogId (FK, int, null)` instead of `not null`. I have enabled nullable reference type in my project. Is there anything else I should configure?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c3721a-da23-d9ea-a054-9d786d2ff4d2
* Version Independent ID: 6d3b0f96-6642-75e5-93c8-02c23f142ac4
* Content: [Working with nullable reference types - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
* Content Source: [entity-framework/core/miscellaneous/nullable-reference-types.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/nullable-reference-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Notes for triage:
* Putting `[Required]` on the navigation doesn't help
* Adding an inverse navigation does
