### ISSUE TITLE
Transaction isolation level remains after transaction on the connection in a pool

### ISSUE THREAD

**Issue by DimitryNechaev** [dotnet/efcore#23580]
I register DB context with AddDbContextPool option

I query some dirty data in high performing API to avoid table locks created by other processes.
For that purpose I create TransactionScope
```
            using (var tran = new TransactionScope(TransactionScopeOption.Required, 
                new TransactionOptions { IsolationLevel = IsolationLevel.ReadUncommitted },
                TransactionScopeAsyncFlowOption.Enabled))
            {
                var branchStock = await ObjectContext.tblBranchProduct
                   .Where(so => so.BranchId == branchId && so.ProductId == productId)
                   .AsNoTracking()
                   .FirstOrDefaultAsync();

                tran.Complete(); // does not make any difference

                return branchStock;
            }
```
I verify in SQL Profiler
![image](https://user-images.githubusercontent.com/12892631/101127432-a7c6b300-3651-11eb-9a63-045c13fdabb7.png)

**After the execution of the above code the connection #89 still having uncommitted isolation level after the tran disposal.**

I trigger some different method on the API, which does not define any transaction (straight LINQ query)
I see that the previously used connection #89 when reused is reading uncommited data.
I have disposed the transaction, it is expected to reset.

![image](https://user-images.githubusercontent.com/12892631/101127036-c7111080-3650-11eb-9dd0-2fbe7490c3f2.png)

I believe this is a bug, as transaction isolation level should return to default after the tran disposal.
I can dictate the level for a query, but not for connection.
Once query is done, I can't do anything to the pool connection which was used to run the query.

**Comment by DimitryNechaev** [comment]
It appears to be the same issue as described 5 years ago in https://stackoverflow.com/questions/28442558/entity-framework-and-transactionscope-doesnt-revert-the-isolation-level-after-d

And offloaded to Sql Client
https://github.com/dotnet/SqlClient/issues/96

From that perspecrtive it is not relevant to EF Core.

**Comment by ajcvickers** [comment]
@DimitryNechaev Yes, this is a well-known issue with SqlClient tracked by https://github.com/dotnet/SqlClient/issues/96

**Comment by suzunkopru** [comment]
I am using EF Core 7.0 and the error still persists.

**Comment by roji** [comment]
@suzunkopru this has nothing to do with EF Core, but rather with the underlying SqlClient database drive. See https://github.com/dotnet/SqlClient/issues/96, as indicated above.
