### ISSUE TITLE
Ca we now use the beta4 release in Production

### ISSUE THREAD

**Issue by ikourfaln** [dotnet/efcore#2359]
Hi,

We are working on a big project, and we need to build it with ASP.NET 5. But we can't wait anymore for the RTM, so is it safe to start the project with Visual Studio 2015 RC (EF beta4) ?

Thanx for all your hard work

**Comment by rowanmiller** [comment]
We're not going to try and stop you using Beta 4 in a production app, but I would recommend against it. If you do decide to then just realize that it is not a supported release and there are a lot of issues with it, some know, many unknown. In particular we have not done a lot of performance or stress testing so there may very well be issues you hit when the framework is put under load.

**Comment by rowanmiller** [comment]
Closing but feel free to reopen if you have further follow up.

**Comment by ikourfaln** [comment]
Hmmmm, thanx a lot for reply, I think we will just start with EF6.
and thanx for your hard work :+1:

**Comment by rowanmiller** [comment]
EF6 is definitely what we would recommend for the moment.

**Comment by ikourfaln** [comment]
Thanx @rowanmiller
