### ISSUE TITLE
Scaffolding Migrations programmatically in Asp.Net Core 5 and EF Core 5

### ISSUE THREAD

**Issue by oNoobMastero** [dotnet/efcore#23595]
I'm trying to scaffold migration files by Internal EF Core APIs programmatically. But I get:

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

from `ScaffoldMigration` method and nothing is NULL as u can see below.

![image](https://user-images.githubusercontent.com/30547976/101289228-3a12b680-380c-11eb-9557-b6365731fd3e.png)

and what's alternative for this
`new Microsoft.EntityFrameworkCore.SqlServer.Design.Internal.SqlServerDesignTimeServices().ConfigureDesignTimeServices(designTimeServiceCollection);`

because in below screenshot shows a green underline and says

`It may be changed or removed without notice in any release`

![image](https://user-images.githubusercontent.com/30547976/101289262-69292800-380c-11eb-9cfd-9b42abdd2064.png)

thanx for helping :)

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: ASP.NET Core 5.0
Operating system: Windows 10
IDE:  Visual Studio 2019 Preview _latest_

**Comment by bricelam** [comment]
Remove the calls AddSingleton calls for MigraitonsScaffolder and its dependencies.

Here's the non-Internal way to access SqlServerDesignTimeServices:
```cs
var providerAssembly = Assembly.Load("Microsoft.EntityFrameworkCore.SqlServer");
var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
var providerServicesType = providerAssembly.GetType(providerServicesAttribute.TypeName);
var providerServices = (IDesignTimeServices)Activator.CreateInstance(providerServicesType);
providerServices.ConfigureDesignTimeServices(services);
```

If you still encounter errors after that, can you attach a runnable repro so we can debug further?

**Comment by oNoobMastero** [comment]
here is my modified code : 
```var designTimeServiceCollection = new ServiceCollection(); var providerAssembly = Assembly.Load("Microsoft.EntityFrameworkCore.SqlServer");
var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
var providerServicesType = providerAssembly.GetType(providerServicesAttribute.TypeName);
var providerServices = (IDesignTimeServices)Activator.CreateInstance(providerServicesType);
providerServices.ConfigureDesignTimeServices(designTimeServiceCollection);
var designTimeServices = designTimeServiceCollection.BuildServiceProvider();
var scaffolder = designTimeServices.GetRequiredService<MigrationsScaffolder>();
```
but last line when getting MigrationsScaffolder from the services gives error and says there  is no `MigrationsScaffolder` registered because I removed the AddSingleton  calls for `MigrationsScaffolder` .

can u show me the complete code of getting `MigrationsScaffolder` from DesignTimeServices or anywhere ?

Thanx :)

**Comment by bricelam** [comment]
Services are registered under their interface. Use `IMigrationsScaffolder`

**Comment by oNoobMastero** [comment]
how can I use `IMigrationsScaffolder` ? I mean how to get it or initiate this interface ?
I Searched everywhere but could not find a documentation on that.

Thanx :)

**Comment by bricelam** [comment]
Here's the code listing [from our docs](https://docs.microsoft.com/en-us/ef/core/cli/services#using-services): (Note, you don't need SqlServerDesignTimeServices for Migrations)

```cs
var db = new MyDbContext();

// Create design-time services
var serviceCollection = new ServiceCollection();
serviceCollection.AddEntityFrameworkDesignTimeServices();
serviceCollection.AddDbContextDesignTimeServices(db);
var serviceProvider = serviceCollection.BuildServiceProvider();

// Add a migration
var migrationsScaffolder = serviceProvider.GetService<IMigrationsScaffolder>();
var migration = migrationsScaffolder.ScaffoldMigration(migrationName, rootNamespace);
migrationsScaffolder.Save(projectDir, migration, outputDir);
```

**Comment by oNoobMastero** [comment]
Thank you very much.
That was what I need 

Regards ;)

**Comment by oNoobMastero** [comment]
@bricelam  hey man .

now i have the same Error ( `System.NullReferenceException: 'Object reference not set to an instance of an object.'` ) when i try to to do migration when already some migration files and the snapshot is available at migration folder..

when the Migration Folder is empty all works fine but otherwise gives me the same above error..

here is my migration code:
`
var serviceCollection = new ServiceCollection();
serviceCollection.AddEntityFrameworkDesignTimeServices();
serviceCollection.AddDbContextDesignTimeServices(_applicationDbContext);
var serviceProvider = serviceCollection.BuildServiceProvider();

var scaffolder = serviceProvider.GetService<IMigrationsScaffolder>();
var migration = scaffolder.ScaffoldMigration("Migration_" + DateTime.Now.ToString("ddMMyy_hhmmss"), $"SoftMax.DatabaseModels.Migrations.ApplicationDb");
var projectDir = $@"..\SoftMax.DatabaseModels\Migrations\ApplicationDb\";


this line => `var migration = scaffolder.ScaffoldMigration("Migration_" + DateTime.Now.ToString("ddMMyy_hhmmss"), $"SoftMax.DatabaseModels.Migrations.ApplicationDb");` gives the error.


Regards :)
`

**Comment by vrassouli** [comment]
> Here's the code listing [from our docs](https://docs.microsoft.com/en-us/ef/core/cli/services#using-services): (Note, you don't need SqlServerDesignTimeServices for Migrations)
> 
> ```cs
> var db = new MyDbContext();
> 
> // Create design-time services
> var serviceCollection = new ServiceCollection();
> serviceCollection.AddEntityFrameworkDesignTimeServices();
> serviceCollection.AddDbContextDesignTimeServices(db);
> var serviceProvider = serviceCollection.BuildServiceProvider();
> 
> // Add a migration
> var migrationsScaffolder = serviceProvider.GetService<IMigrationsScaffolder>();
> var migration = migrationsScaffolder.ScaffoldMigration(migrationName, rootNamespace);
> migrationsScaffolder.Save(projectDir, migration, outputDir);
> ```

After updating to ef core 6, serviceProvider.GetService<IMigrationsScaffolder>() is throwing exception.
`System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator' while attempting to activate 'Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsCodeGeneratorDependencies'.'`

I couldn't figure out how to register IAnnotationCodeGenerator!

Thanx for helping

EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: ASP.NET Core 6.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by roji** [comment]
Here's a code sample that scaffolds a migration with EF Core 6.0:

```c#
var services = new ServiceCollection()
    .AddEntityFrameworkDesignTimeServices()
    .AddDbContextDesignTimeServices(ctx);

var designTimeServices = new SqlServerDesignTimeServices();
designTimeServices.ConfigureDesignTimeServices(services);

var serviceProvider = services.BuildServiceProvider();
var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();
var migration = scaffolder.ScaffoldMigration("MyMigration", "MyApp.Data");

Console.WriteLine(migration.MigrationCode);
```

**Comment by ASalihov** [comment]
Can you please explain when such approach might be useful?

**Comment by roji** [comment]
@ASalihov in normal applications, you're not expected to scaffold migrations programmatically - migrations are scaffolded by the developer via the EF tools, whenever a model changes.

**Comment by georg-jung** [comment]
I think this approach can be useful to create a unit test that checks for accidentally introduced model changes:

```csharp
[Fact]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "EF1001:Internal EF Core API usage.", Justification = "Thats okay for this test case.")]
public async Task EnsureNoPendingModelChanges()
{
    // See https://learn.microsoft.com/en-us/ef/core/cli/services#using-services
    // and https://github.com/dotnet/efcore/issues/23595#issuecomment-966185003
    await using var db = testDatabaseFixture.CreateDbContext();

    var services = new ServiceCollection();
    services.AddEntityFrameworkDesignTimeServices();
    services.AddDbContextDesignTimeServices(db);

    var designTimeServices = new Npgsql.EntityFrameworkCore.PostgreSQL.Design.Internal.NpgsqlDesignTimeServices();
    designTimeServices.ConfigureDesignTimeServices(services);

    var serviceProvider = services.BuildServiceProvider();

    var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();
    var migration = scaffolder.ScaffoldMigration("TestMigration", $"{typeof(Data.AppDbContext).Assembly.FullName}.Migrations");
    migration.MigrationCode.ShouldMatch(@"override\s+void\s+Up\(MigrationBuilder\s+migrationBuilder\)\s*\{\s*\}", "Model state is not in sync with the state snapshotted in the latest migration. 'Add-Migration' would result in changes.");
}
```

Note that the test makes assumptions about EF Core/EF Core provider behaviour that is not guaranteed to be stable (uses internal APIs, even assumes specific structure of scaffolded migration code). This is acceptable in my scenario though as a) these internals don't seem to change too often in practice, b) the test would probably be easy to fix if they did (or easy to remove/disable if required) and c) provides an imho valuable guarantee until it might potentially break.
