### ISSUE TITLE
Still can't run ef core in package manager console .deps.json does not exist

### ISSUE THREAD

**Issue by nbelley** [dotnet/efcore#23607]
I created another issue since the other one is closed but still is a problem:

Here is what I do, using visual studio 2019 16.8.2:

1. Created a new solution
2. .net Core 5 library 
3. added a class called Blog (like in the tutorial: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs)
4. installed the tools from the nuget packager console: Install-Package Microsoft.EntityFrameworkCore.Tools
5. then ran the initial command: Add-Migration InitialCreate

And bam: 

![Clipboard01](https://user-images.githubusercontent.com/4919080/101393834-b3a2b700-3895-11eb-9eb0-48dcdcee7bd2.jpg)

Please don't tell me this is normal, that my solution file is corrupted or that my build configuration is broken. It does that with a clean new project.

_Originally posted by @nbelley in https://github.com/dotnet/efcore/issues/16386#issuecomment-740119889_

**Comment by smitpatel** [comment]
@dotnet/efteam  - Do we have anywhere in our docs that migrations/tools cannot be used from a class library?

**Comment by ajcvickers** [comment]
@smitpatel I thought they could be used with a class library, as long as it targets a real platform and not just .NET Standard.

**Comment by nbelley** [comment]
I'm targeting .net 5:

![dsafafsdfsda](https://user-images.githubusercontent.com/4919080/101399389-675b7500-389d-11eb-8955-36db11bf35f5.jpg)

**Comment by smitpatel** [comment]
@ajcvickers - My understanding is that we need to be able to run the app some way to get services. netstandard wasn't executable ever. But a class library is executable even if it is targeting some tfm which can be both. 
I guess @bricelam can clarify everything. 😄

**Comment by bricelam** [comment]
Class libraries should work fine.

@nbelley Can you share the contents of your .csproj file?

**Comment by nbelley** [comment]
[TestEFMigration.zip](https://github.com/dotnet/efcore/files/5661286/TestEFMigration.zip)

I joined my whole test project, which is not much...

**Comment by bricelam** [comment]
What is the output of running `Get-Module EntityFrameworkCore`?

What is the output of running `(Get-Project).ConfigurationManager.ActiveConfiguration.Properties | ft Name, Value`?

**Comment by nbelley** [comment]
@bricelam here it is:

![image](https://user-images.githubusercontent.com/4919080/101626254-b19e3c80-39ea-11eb-8d60-16ec8ce9da17.png)

**Comment by bricelam** [comment]
I’m surprised EF Core isn’t giving the better error message that we added in 5.0...

Can you show the output of Add-Migration with -Verbose?

This is the same issue with [dotnet/project-system](https://github.com/dotnet/project-system) that many others have reported. Can you file there and work with them to diagnose it? It’s been a couple years, and they still say they haven’t been able to repro it to properly diagnose it...

**Comment by nbelley** [comment]
here is the result! 

![image](https://user-images.githubusercontent.com/4919080/101673218-e333f980-3a24-11eb-8ca8-5ba2a4b71fd9.png)

So, the problem is related to the fact that it doesn't seem I have an active config even if I do?

**Comment by bricelam** [comment]
Yeah, for some unknown reason the project system doesn’t give us the values we need (bin/Debug/net5.0 in this case)
