### ISSUE TITLE
EF Core 5 - add ability to identify Table name for Many-to-Many where UsingEntity() 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23606]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/EF-Core-5---add-ability-to-identify-Tabl/1268920)._

---
When converting the EntityFramework model from EF Core 3.1, to adopt the new style Many-to-Many format in EF Core 5, and where the Table name for the linking has already been defined it is possible to construct the model using the following:

Given the linking table defined as:

```C#
public class ContactTag
    {
        public long ContactID { get; set; }
        public Contact Contact { get; set; }

public long TagID { get; set; }
        public Tag Tag { get; set; }
    }
```

To recreate this linking table I need to employ UsingEntity(), as below, but I also need to define the table name as a separate line (line 1 below):

```C#
modelBuilder.Entity<ContactTag>(). ToTable("ContactTagLink");
            modelBuilder.Entity<Tag>()
                . HasMany(w => w.Contacts)
                . WithMany(m => m.Tags)
                . UsingEntity<ContactTag>
                (
                    j => j.HasOne(x => x.Contact). WithMany(). HasForeignKey(x => x.ContactID),
                    j => j.HasOne(x => x.Tag). WithMany(). HasForeignKey(x => x.TagID),
                    j => j.HasKey(x => new { x.ContactID, x.TagID })
                );
```
Instead of having to make a separate line to define the Table Name, it would be easier to be able to define all parameters, including the table name within Using Entity(), so that model definition includes the `. ToTable()` as well, like so

```C#
modelBuilder.Entity<Tag>()
                . HasMany(w => w.Contacts)
                . WithMany(m => m.Tags)
                . UsingEntity<ContactTag>
                (
                    j => j.HasOne(x => x.Contact). WithMany(). HasForeignKey(x => x.ContactID),
                    j => j.HasOne(x => x.Tag). WithMany(). HasForeignKey(x => x.TagID),
                    j => j.HasKey(x => new { x.ContactID, x.TagID }),
                    j => j.ToTable("ContactTagLink"),

);
```

At the moment, Intellisense does offer the `. ToTable()` option, but the compiler rejects the line when entered.

---
#### Feedback Bot on 11/25/2020, 09:47 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by ajcvickers** [comment]
The third lambda is the configuration for the join entity. You can add the call to `ToTable` there. For example:

```C#
modelBuilder.Entity<Tag>()
    . HasMany(w => w.Contacts)
    . WithMany(m => m.Tags)
    . UsingEntity<ContactTag>
    (
        j => j.HasOne(x => x.Contact). WithMany(). HasForeignKey(x => x.ContactID),
        j => j.HasOne(x => x.Tag). WithMany(). HasForeignKey(x => x.TagID),
        j =>
        {
            j.HasKey(x => new {x.ContactID, x.TagID});
            j.ToTable("ContactTagLink");
        });
```
