### ISSUE TITLE
Improve EF Core performance on TechEmpower Fortunes

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#23611]
We have been running the industry standard [TechEmpower benchmarks](https://www.techempower.com/benchmarks/) on .NET against a PostgreSQL database for several years. In particular, the [Fortunes benchmark](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=fortune) is particularly relevant to EF scenarios. We have multiple variations of this benchmark, including:
- An implementation that uses ADO.NET directly. This is the fastest implementation of the three listed here.
- An implementation that uses [Dapper](https://www.nuget.org/packages/Dapper/). This is slower than using ADO.NET directly, but still fast.
- An implementation that uses EF Core. This is currently the slowest implementation of the three.

The goal for EF Core 6.0 is to get the EF Core performance to match that of Dapper on the TechEmpower Fortunes benchmark. This is a significant challenge which may not be fully achieved in EF Core 6.0. Nevertheless, we will get as close as we can.

**Comment by roji** [comment]
Starting EF Core Fortunes perf: 69,653 RPS
Dapper perf: 93,453 RPS

Description                                                                                                   | RPS    | Improvement
------------------------------------------------------------------------------------------------------------- | ------ | -----------
Starting point                                                                                                | 69,653 |
[Set EF DbContext pool size to 1024 (instead of default 128)](https://github.com/aspnet/Benchmarks/pull/1630) | 73,718 | 5.8%

**Comment by Saibamen** [comment]
@roji: Please update URLs for tickets in your comment

For example:
`[Cache ResettableServices for DbContext pooling](https://github.com/dotnet/efcore/issues/23611#24138)`
Should be:
`[Cache ResettableServices for DbContext pooling](https://github.com/dotnet/efcore/issues/24138)`

GitHub will do redirect automatically if number of issue is pull request

**Comment by roji** [comment]
Here's the memory reduction info. The following includes only improvements done between EF Core 5 and 6: no benchmark code changes or .NET-related changes, but including some minor Npgsql improvements.

Scenario  | MB allocated | # objects allocated
--------- | ------------ | -------------------    
EF Core 5 | 54.84        | 910,000
EF Core 6 | 31.14        | 379,700
Reduction | 43.2%        | 58.3%

**Comment by roji** [comment]
Here's a comparison with and without EF's compiled query feature:

Scenario         | RPS
---------------- | ---
With compiled    | 257,285
Without compiled | 247,480

So disabling compiled queries reduces perf by **3.8%**. Not a lot, but it's worth mentioning the that the Fortunes query itself is as minimal as can be (just enumerate the DbSet - no operators, no parameters); as the query becomes more complex, the gap will increase.

<details>
<summary>Crank cmdlines</summary>

With compiled:

```
dotnet run -- --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes_ef --profile aspnet-citrine-lin --application.framework net6.0 --application.options.outputFiles Z:\projects\test\bin\Release\net5.0\publish\*.dll -i 5
```

Without compiled:

```
dotnet run -- --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes_ef --profile aspnet-citrine-lin --application.framework net6.0 --application.options.outputFiles Z:\projects\test\bin\Release\net5.0\publish\*.dll --application.source.repository http://github.com/roji/AspNetBenchmarks --application.source.branchOrCommit NonCompiledQuery -i 5
```

</details>

/cc @ajcvickers

**Comment by AndriySvyryd** [comment]
@roji Whenever you work on this again I think it could be beneficial to determine where Dapper is benefitting from the move to .NET 6 in case a similar optimization can be applied to EF Core.

**Comment by roji** [comment]
Am closing this for now, as we've achieved good results for 6.0 and don't have immediate plans for further work.
