### ISSUE TITLE
EF Core 3.0 not able to get data from Oracle view

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23627]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/EF-Core-30-not-able-to-get-data-from-Or/1208863)._

---
<p>Hi, </p><p>I am not able retrieve data from Oracle View in using ORacle Entity Framework Core and .Net EF core 3.0, but tables are returning data.</p> <p><strong>The Context.&lt;ViewName&gt;. ToList() is always showing 0 result with no errors.</strong></p> <p>the Model is generated using Scaffold-DbContext with Oracle DB connection</p><p>Code Sample: </p><p><u>Model Context</u></p><p>public virtual DbSet&lt;XxegcXerpSalesmanMasterV&gt; XxegcXerpSalesmanMasterV { get; set; }</p> <p>modelBuilder.Entity&lt;XxegcXerpSalesmanMasterV&gt;(entity =&gt;
            {
                entity. HasNoKey();
                entity. ToView(&quot;XXEGC_XERP_SALESMAN_MASTER_V&quot;, &quot;APPS&quot;);
                entity. Property(e =&gt; e.CreationDate)
                    . HasColumnName(&quot;CREATION_DATE&quot;)
                    . HasColumnType(&quot;DATE&quot;);
                entity. Property(e =&gt; e.Division)
                    . HasColumnName(&quot;DIVISION&quot;)
                    . HasMaxLength(150)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.EndDateActive)
                    . HasColumnName(&quot;END_DATE_ACTIVE&quot;)
                    . HasColumnType(&quot;DATE&quot;);
                entity. Property(e =&gt; e.LastUpdateDate)
                    . HasColumnName(&quot;LAST_UPDATE_DATE&quot;)
                    . HasColumnType(&quot;DATE&quot;);
                entity. Property(e =&gt; e.MainWhCode)
                    . HasColumnName(&quot;MAIN_WH_CODE&quot;)
                    . HasMaxLength(3)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.MainWhName)
                    . HasColumnName(&quot;MAIN_WH_NAME&quot;)
                    . HasMaxLength(240)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.OrgId)
                    . HasColumnName(&quot;ORG_ID&quot;)
                    . HasColumnType(&quot;NUMBER&quot;);
                entity. Property(e =&gt; e.ResourceId)
                    . HasColumnName(&quot;RESOURCE_ID&quot;)
                    . HasColumnType(&quot;NUMBER&quot;);
                entity. Property(e =&gt; e.ResourceStatus)
                    . HasColumnName(&quot;RESOURCE_STATUS&quot;)
                    . HasColumnType(&quot;CHAR(1)&quot;);
                entity. Property(e =&gt; e.RouteCode)
                    . HasColumnName(&quot;ROUTE_CODE&quot;)
                    . HasMaxLength(16)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.RouteType)
                    . HasColumnName(&quot;ROUTE_TYPE&quot;)
                    . HasMaxLength(150)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.SalesmanName)
                    . HasColumnName(&quot;SALESMAN_NAME&quot;)
                    . HasMaxLength(1412)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.SalesmanNumber)
                    . HasColumnName(&quot;SALESMAN_NUMBER&quot;)
                    . HasMaxLength(30)
                    . IsUnicode(false);
                entity. Property(e =&gt; e.SalesrepId)
                    . HasColumnName(&quot;SALESREP_ID&quot;)
                    . HasColumnType(&quot;NUMBER&quot;);
                entity. Property(e =&gt; e.StartDateActive)
                    . HasColumnName(&quot;START_DATE_ACTIVE&quot;)
                    . HasColumnType(&quot;DATE&quot;);
                entity. Property(e =&gt; e.VanSubinv)
                    . HasColumnName(&quot;VAN_SUBINV&quot;)
                    . HasMaxLength(30)
                    . IsUnicode(false);
            });</p> <p class=""></p><p class=""><u>Class Defination</u></p><p class="">namespace MVC_oracle. Models
{
    public partial class XxegcXerpSalesmanMasterV
    {
        public decimal ResourceId { get; set; }
        public string SalesmanName { get; set; }
        public string SalesmanNumber { get; set; }
        public string RouteCode { get; set; }
        public string RouteType { get; set; }
        public string VanSubinv { get; set; }
        public string MainWhCode { get; set; }
        public decimal? OrgId { get; set; }
        public string Division { get; set; }
        public decimal SalesrepId { get; set; }
        public string ResourceStatus { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public DateTime StartDateActive { get; set; }
        public DateTime? EndDateActive { get; set; }
        public string MainWhName { get; set; }
    }
}</p><p></p><p>Controller Class:</p><p> private readonly ModelContext _context;          <strong>var SalesMans = _context. XxegcXerpSalesmanMasterV.ToList(); // Not getting data here</strong></p>

---
#### Feedback Bot on 10/5/2020, 03:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This is an issue with Oracle's EF Core provider. Please report the issue with Oracle.
