### ISSUE TITLE
dotnet ef migrations script -i checks for wrong error code

### ISSUE THREAD

**Issue by Quietscheente** [dotnet/efcore#23638]
## File a bug

When I use the `dotnet ef migrations script -i` cli command to generate an idempotent script it creates a script starting with

		Begin
		BEGIN 
		EXECUTE IMMEDIATE 'CREATE TABLE 
		"__EFMigrationsHistory" (
			"MigrationId" NVARCHAR2(150) NOT NULL,
			"ProductVersion" NVARCHAR2(32) NOT NULL,
			CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
		)';
		END;

		End;

		EXCEPTION
		WHEN OTHERS THEN
			IF(SQLCODE != -942)THEN
				RAISE;
			END IF;
		END;        

### Error

When I copy this script into my oracle client and execute it I get the error message:

![image](https://user-images.githubusercontent.com/57129685/101645682-f059e400-3a36-11eb-9e3c-e0a8d704b0f1.png)

_(an object with this name already exists)_

Line 17 is the RAISE

Does the script check for the wrong error code? If I replace 942 with 955 the script works as expected.

"ORA-00942: table or view does not exist"
"ORA-00955: name is already used by an existing object"

### Include provider and version information

EF Core version: Entity Framework Core .NET Command-line Tools 5.0.1
Database provider: Oracle.EntityFrameworkCore
Target framework: NET Core 3.1
Operating system: Win 10 64 bit

**Comment by roji** [comment]
@Quietscheente your should probably submit this to the folks maintaining Oracle.EntityFrameworkCore - this is the general EF Core repo.
