### ISSUE TITLE
SqliteException.ThrowExceptionForRC	0x000000000000011F

### ISSUE THREAD

**Issue by wjvii** [dotnet/efcore#23633]
## Ask a question

Getting a random crash in our application and wanted to know for sure if SqliteException.ThrowExceptionForRC	0x000000000000011F means a SQLite Error 17 as defined here: https://sqlite.org/rescode.html#schema 

Not 100% sure where the error is occurring in code yet but including part of the stack trace below.

### Include stack traces

```
27	mrt100_app.dll	RhpThrowEx	0x0000000000000084	
28	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteException.ThrowExceptionForRC	0x000000000000011F	
29	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteCommand::_PrepareAndEnumerateStatements_d__64.MoveNext	0x00000000000000F6	
30	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteCommand::_GetStatements_d__54.MoveNext	0x000000000000007A	
31	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteDataReader.NextResult	0x0000000000000088	
32	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteCommand.ExecuteReader	0x00000000000000E4	
33	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteCommand.ExecuteNonQuery	0x0000000000000031	
34	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteConnectionExtensions.ExecuteNonQuery	0x0000000000000202	
35	microsoft.data.sqlite.dll	Microsoft::Data::Sqlite::SqliteConnection.Open	0x000000000000055B	
```
### Include provider and version information

EF Core version: 3.1.9
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET 3.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.8.3)

**Comment by ajcvickers** [comment]
@wjvii We're not sure why you think this would mean it is error 17. Can you explain more?

**Comment by wjvii** [comment]
@ajcvickers thank you for responding.

I was going based on this specific line:

Microsoft::Data::Sqlite::SqliteException.ThrowExceptionForRC	0x000000000000011F

At first I thought 11F was the error but reading https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite.sqliteexception.throwexceptionforrc?view=msdata-sqlite-3.1.0 it seems this is an Int32 error for SQLite and I could not find an result 287 (if my math is right) for SQLite here https://sqlite.org/rescode.html so my mind, and being a really poor reader of hexadecimal, I took the F as a delimiter/indicator sort of like the 0x and said 11 hex (decimal 17) is an error here https://sqlite.org/rescode.html and it makes sense in the area of code the error appears to be in because we were doing database schema modification (GUID blob to string) and 17 was a schema error.

So maybe the better questions should be: Should I be using https://sqlite.org/rescode.html as a lookup for the decimal value this represents and does that 0x000000000000011F represent the decimal error value for SQLite? If not, can you get the value from this trace? BTW, this stack trace comes from the Health area of the Microsoft Store dashboard.

Thank you.

**Comment by ajcvickers** [comment]
@wjvii I don't know where "0x000000000000011F" comes from; the stack trace is not in the form usually generated by .NET. However, it seems unlikely that this is any kind of error code given that every line in the trace has some number in this form.

I would follow up with Microsoft Store and see if they understand the trace.
