### ISSUE TITLE
Default value in MSSQL ignored without entity.Property

### ISSUE THREAD

**Issue by romanov** [dotnet/efcore#23647]
Question: why default values in MSSQL will fail in EFcore?

For example:

simple table in MSSQL
![изображение](https://user-images.githubusercontent.com/644179/101799307-1063d300-3b1d-11eb-922e-a7c9ce551a3e.png)

Then add simple model

```
public string ClientEmail {get;set;}
public string ClientName {get;set;}
public string ClientAdress {get;set;}
```

If you pass just
```
var client = new Client {
  ClientEmail = "test@microsoft.com",
  ClientName = "test"
};
context.Clients.Add(client)
```
the app will throw an exception about the missing "ClientAdress" even when the default value in **MSSQL** exists!

but if u will add 

` entity.Property(e => e.DeliveryAdress).HasDefaultValueSql("(N'-')");` 

to model builder it will work.

### Include provider and version information

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10 Pro  10.0.19042.630
IDE: (e.g. Visual Studio 2019 16.8.2)

**Comment by ajcvickers** [comment]
@romanov Because you need to tell EF that the property can have a generated value, either with `HasDefaultValue` or `HasDefaultValueSql`, or with `ValueGeneratedOnAdd` or similar.
