### ISSUE TITLE
Helix tests in SqlServer.FunctionalTests failing consistently

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/efcore#23642]
EFCore's internal builds are failing 85% of the time this week because of this issue. Tests in `SqlServer.FunctionalTests` are failing with:

> System.InvalidOperationException : Sequence contains more than one element

Details from Teams chat:

> Error - Microsoft.Data.SqlClient.SqlException : A timeout occurred while waiting for memory resources to execute the query in resource pool 'internal' (1). Rerun the query.\r\nThe statement has been terminated.

> Based on some investigation I did on this error, it happens when there is not enough memory available for localdb the error is thrown.

> The root cause is likely going to be that helix VMs just don't have enough memory to keep SqlServer happy for EF Core testing scenario.

CC @bricelam

**Comment by wtgodbe** [comment]
Builds where this is happening:

https://dev.azure.com/dnceng/internal/_build/results?buildId=912849&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=909309&view=results

And many more

**Comment by ajcvickers** [comment]
@smitpatel is following up on this; closing the issue here is there is nothing specific to the tests to change.
