### ISSUE TITLE
How to tell EF Core that a given type is *not* an entity

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/efcore#23640]
I'm using C# 9 records as strongly-typed ids in my project, i.e. something like this:

```csharp
public record ProductId(Guid Value) : IStronglyTypedId<Guid>;

public class Product
{
    public ProductId Id { get; set; }
    public string Name { get; set; }
    public decimal UnitPrice { get; set; }
}
```

I set up the necessary EF Core ValueConverters, and it mostly works, but every now and then I run into a weird behavior where EF Core treats my strongly-typed id as an entity type.

How do I tell it EF Core that a given type should not be considered an entity?

(I suspect this might have been asked before, but I couldn't find a relevant issue)

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
@thomaslevesque 

> I set up the necessary EF Core ValueConverters, and it mostly works, but every now and then I run into a weird behavior where EF Core treats my strongly-typed id as an entity type.

Value converters is the way to do this, since EF needs to know how to map the property somehow. If you're seeing issues with this and can reproduce the problem, then we would certainly like to know.

**Comment by thomaslevesque** [comment]
I'm doing that already, but I'm still seeing strange things:
- my custom types still appear in modelBuilder.Model.GetEntityTypes()
- they sometimes have an additional `TempId` property

**Comment by ajcvickers** [comment]
@thomaslevesque If you're calling `modelBuilder.Model.GetEntityTypes()` while building the model, then this is expected. These are consequences of how the model is incrementally constructed by the conventions. They will ultimately be removed when the model is finalized. Implementation and use of #10784 would also likely mean that these types never get introduced into the model.

**Comment by thomaslevesque** [comment]
@ajcvickers I see, thanks!

**Comment by thomaslevesque** [comment]
@ajcvickers one more question about this...

If I do this:

```csharp
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    foreach (var property in entityType.GetProperties())
    {
        if (some condition) property.SetValueConverter(...);
    }
}
```
I never see the `Id` property in the inner loop. I understand that it's because `ProductId` is treated as an entity, so `Id` is mapped as a navigation property. But it means I can't add the converter to `Id`... I also tried to manually add the `Id` property, but it doesn't work because there's already a navigation property with the same name. And I can't find a way to remove that navigation property...

I know that it works if I explicitly configure `Id` as a key before that loop, but I'm trying to do this for *all* entities, so I'd rather not have to manually configure the key for every entity.

Is this possible?
