### ISSUE TITLE
Add an attribute to not save null values when updating

### ISSUE THREAD

**Issue by omid-ahmadpour** [dotnet/efcore#23656]
To not save null values during the update

Sometimes we just want to update the values that the user changes, in this case the values that have not changed are null, we want them not to track and save these values

**Comment by ajcvickers** [comment]
@omidah Doing this in general would often result in bugs since applications need to be able to set columns to null. However, if you really want this behavior, then there are several ways to achieve this in EF Core. One simple way to to override SaveChanges:

```C#
public override int SaveChanges()
{
    ChangeTracker.DetectChanges();

    foreach (var entry in ChangeTracker.Entries().Where(e => e.State == EntityState.Modified))
    {
        foreach (var propertyEntry in entry.Properties)
        {
            if (propertyEntry.CurrentValue == null)
            {
                propertyEntry.IsModified = false;
            }
        }
    }
    
    return base.SaveChanges();
}
```

**Comment by omidah** [comment]
@ajcvickers 
Yes, you right
But my suggestion is to create an attribute for such occasions that we put on top of the class

**Comment by ajcvickers** [comment]
@omidah Feel free to do that in your own code. This is not something we plan to put in EF Core itself.
