### ISSUE TITLE
Allow navigation properties that are collections of keys, e.g. ICollection<long> for foreign entities with matching long key

### ISSUE THREAD

**Issue by kskalski** [dotnet/efcore#23655]
I'm often working with models that do not reference the other entities directly by their object instance, but simply by their key. 
Such approach is more serialization and wire-transfer friendly, so I guess it's a reasonable use-case to expect.

for example
```
class Group {
   int Id { get; set; }
   string Name { get; set; }
   ICollection<long> UserIds { get; set; }
}
class User {
  long Id { get; set; }
  string Name { get; set; }
  int GroupId {get; set; }
}
```

Currently only property of type ``ICollection<User>`` can be specified in ``HasMany()`` call and any other way trying to use ``UserIds`` is not accepted. This is in contrast with singular properties like ``User.GroupId`` which can be used to specify a dependent one-to-many or one-to-one relationship.

I would like to use the ``Group.UserIds`` property as navigation for specifying one-to-many relationship to User entities.
I imagine this could be supported when I call 
```
groupModelBuilder.HasMany<User>("UserIds").WithOne("GroupId")
```

The same applies to many-to-many relationship, e.g. 
```
class Topic {
  int Id;
  ICollection<int> GroupIds { get; set; }
}
class Group {
  int Id;
  ICollection<int> TopicIds { get; set; }
}
...
topicModelBuilder.HasMany<Group>("GroupIds").WithMany("TopicIds").UsingEntity(...)
```

Lambda expression variants would be cool too, but I guess this would require elaborate type / aux builders extension.

**Comment by ajcvickers** [comment]
@kskalski Can you provide some more details on how database inserts, updates, and deletes using this pattern would work?

**Comment by kskalski** [comment]
I think it could follow the very same semantics of navigational property containing related entities, with a simple difference - the provided keys relate to existing entities in the database (I suppose checked / enforced based on configured cascade policy).

For example one-to-many relationship Group <- User seems to work like this:
- when I fetch a group as  ``var group = Db.Groups.Include(g => g.Users).First();`` so ``Users`` navigational property is populated, it also "tracks" the modifications to it, such that
  * ``group.Users.RemoveAt(0)`` --> will cause removal of association between user at idx 0 from group
  * ``group.Users.Add(Db.Users.Find(123L))``  --> will cause adding association between user with Id==123 and group
  * those operations are realized by means of defined relationship, e.g. for one-to-many in above model they will modify ``GroupId`` property value on related ``User`` rows (setting to ``null`` for removal, setting to ``group.Id`` for addition)
  * in a hypothetical ``UserIds`` navigational property this use-case would be realized accordingly when ``group.UserIds.RemoveAt(0)`` or ``group.UserIds.Add(123L)`` are  done, for this purpose ``UserIds`` would be treated as a set of keys end more or less be equivalent to ``group.Users.Clear(); group.Users.AddRange(group.UserIds.Select(id => Db.Users.Find(id)))``
- when I fetch a group as  ``var group = Db.Groups.First();`` so ``Users`` navigational property is not populated, it does not "track" removals, but it still "tracks" additions, such that
  * ``group.Users.Add(Db.Users.Find(123L))``  --> will cause adding association between user with Id==123 and group
  * adding user element that is already associated with a group doesn't cause error nor any change in db
  * saving changes while such users collection contains new elements, but doesn't contain (all) existing entities will not touch those existing entities, just add new ones
  * the ``UserIds`` would behave in a very similar way

I suppose some of the above use-cases, especially for many-to-many version, would require EF to do some additional fetches to check existing state (which maybe are avoided if the objects put into collection are already tracked due to earlier operations) before deciding on exact operation. For example I guess the 'not tracked many-to-many collection to which we add existing key' would need to consult the backing many-to-many entity collection to verify whether it needs to insert new entry or not touch anything.

**Comment by kskalski** [comment]
As you might guess this is a bit related to an earlier proposals that I created (https://github.com/dotnet/efcore/issues/21262). Here the plain collection of ids use-case and allowed operations (e.g. always operating on existing keys) are simpler, but more limited.
Ideally it would be nice to find a pattern that could handle both of them and more - a flexible API for navigation/collections conversion. 

Maybe navigational properties should allow specifying translation mechanism where elements would be translated:
- model property ``ICollection<T>`` + ``Func<T, Pair<K, E>>`` custom converter = navigational property ``ICollection<E>`` where ``E`` uses ``K`` as key
- converter would return ``(key, entity)``
  * when ``entity`` is not null then it's used and ``key`` is ignored - used for adding new entities to navigation or manipulating populated / tracked one
  * otherwise ``key`` is used for operating on entities that are assumed to be existing in general - used for the simplified ``T`` cases, which do not contain full/enough information to deconstruct whole ``E`` instance
- analogous conversion ``Func<Pair<K, E>, T>`` (or ``Func<EF.Entry<E>, T>``) would be provided to convert back
- EF would keep the collection synchronized with its internal ``ICollection<E>`` - by forwarding additions, editions (overwriting element at index) and removals both ways

This feature would allow to easily implement https://github.com/dotnet/efcore/issues/23655 and https://github.com/dotnet/efcore/issues/21262 on the user side. It would also enable other use-cases, e.g. when ``IDictionary`` or any other user-defined collection doesn't use ``K`` in direct way, etc. :-)

**Comment by andleer** [comment]
How does this work for inserts? You don't have key values before your various entities are connected to a context and the SaveChanges() method on the context is invoked.

You can maintain an object graph with key values once they are assigned but how are relationships established without those?

**Comment by kskalski** [comment]
Yeah, that's true, for such models I need to do insert+save in "layers" and this staging needs to be done manually.  The collection fields like this are not often used in such scenarios though - if they use keys instead of entities directly, it is a sign that they are "referential" to some other part of the graph, not "defining". This could for example be a place where graph cycles arise, or a place in system where "layers" are implicitly natural (e.g. User and Document, by the time you create Document, your user usually already exists).

I could imagine some ways of dealing with this problem, like ``DbSet<E>.Add()`` returning Entity that has "some kind of key" defined that could be used to reference in ``IColleciton<K>``. I use this approach in my APIs, but I suppose it's a bit messy solution to add into library like EF, since it requires defining separate domain for keys and heck, generating those fake keys in some way.

On the other hand, using proposal from https://github.com/dotnet/efcore/issues/23655#issuecomment-743725712 this could be done by the user-provided custom converter. E.g. it could create a simple mapping of added entities to "fake" keys, maybe not really storing them, but making sure they do not collide. The non-obvious think here would be that as part of Save the keys would be replaced to real values by EF also inside the collection.

**Comment by andleer** [comment]
It seems like you can get pretty close to what you want with existing functionality. Add an IEnumerable<T> property for your keys collection and have it simply project the values based on the existing navigation collection. You can't insert into the enumeration but you don't have the ids to do that anyway. If you are creating new child entities, you can always set the parent id directly, attach it to the context and then save it.

```
parent class
{
    ...
    public IEnumerable<int> ChildIds => ChildNavigationCollection.Select(i => i.ChildId);
}
```

**Comment by kskalski** [comment]
It's the other way around, I already have an  ``IEnumerable<int>`` on my model, but don't have a entity enumeration navigation. So I would like EF to understand it when some ids are put into my ids enumeration when I insert the entity in context.
