### ISSUE TITLE
InMemory: Missing the equivalent of IRelationalDbContextOptionsBuilderInfrastructure

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#23669]
Currently, there is no way to get from an InMemoryDbContextOptionsBuilder to the DbContextOptionsBuilder.

Our current workaround in EntityFrameworkCore.InMemrory.HierarchyId is to use reflection:

```cs
var coreOptionsBuilder = (DbContextOptionsBuilder)typeof(InMemoryDbContextOptionsBuilder)
    .GetProperty("OptionsBuilder", BindingFlags.Instance | BindingFlags.NonPublic)
    .GetValue(optionsBuilder);
```

**Comment by AndriySvyryd** [comment]
I understand now. We should make the `OptionsBuilder` public, but hidden from IntelliSense in `InMemoryDbContextOptionsBuilder `, `RelationalDbContextOptionsBuilder` and `CosmosDbContextOptionsBuilder`
