### ISSUE TITLE
Missing documentation for parameter "name" in DbContext.Set<TEntity>(string)

### ISSUE THREAD

**Issue by cesarsouza** [dotnet/efcore#23683]
I've upgraded to EF Core 5.0 and noticed there is now a new overload for the Set<TEntity>() method which accepts a string parameter called "name". However, there is no documentation for the intended purpose of this overload or what the "name" parameter is supposed to control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1996d904-53ee-b5b5-a7ec-fbeee1a39a56
* Version Independent ID: 71d9633e-ec6e-93e1-8785-96cc4179eee8
* Content: [DbContext.Set Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.set?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Need to update in source https://github.com/dotnet/efcore/blob/main/src/EFCore/DbContext.cs#L300

I will also hand-edit the xml in docs if someone can write a doc line for param.
