### ISSUE TITLE
"dotnet ef dbcontext scaffold" is no longer pluralizing DbSet properties

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#23689]
I'm not sure if I can really provide a sample project for this issue.

Just recently, running `dotnet ef dbcontext scaffold` generates singular DbSet properties instead of plural.  This may have started happening after upgrading from .NET Core 3.x to 5, but I'm not certain.   It did not used to happen.

I am **not** using `--no-pluralize`, and I have tried installing `Bricelam.EntityFrameworkCore.Pluralizer`.

All of my database tables are plural, yet the DbSet properties are generated as singular.  This of course causes my entire project to break and I need to manually fix all of them one by one.

The command I am running:
```
dotnet ef dbcontext scaffold 'Server=tcp:abcxyz.database.windows.net,1433;Initial Catalog=abcxyz;Persist Security Info=False;User ID=user;Password="hunter2";' Microsoft.EntityFrameworkCore.SqlServer --force --data-annotations --output-dir Models --context DbContext
```

![image](https://user-images.githubusercontent.com/6278400/102237092-e3674580-3eb9-11eb-9a62-061119fbbaf6.png)

Did some scaffolding behavior change here between 3.x and 5.x?

Please let me know if there's any other useful details I can provide.

Thank you

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Arch Linux
IDE: Visual Studio Code 1.52.0

**Comment by ErikEJ** [comment]
Pluralization was enabled by default in 5.0. do you have DesignTimServices configured??

**Comment by LuckySandwich** [comment]
> Pluralization was enabled by default in 5.0. do you have DesignTimServices configured??

No, I don't have that configured anywhere.  I shouldn't need it if it's enabled by default, should I?  

Thanks

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#pluralizer

**Comment by ErikEJ** [comment]
What happens if you use --no- pluralize ?

**Comment by LuckySandwich** [comment]
> What happens if you use --no- pluralize ?

What the heck....  adding `--no-pluralize` fixed my problem. It pluralized my DbSets correctly

**Comment by ajcvickers** [comment]
@LuckySandwich While the switch is called `--no-pluralize`, it really means don't use the pluralizer, which means do not do pluralization or singularization. To get the previous behavior back you need to switch off the pluralizer with `--no-pluralize`.

**Comment by LuckySandwich** [comment]
Thanks for the explanation @ajcvickers.  It seems to me that `--no-pluralizer` would make more sense than `--no-pluralize`, it's a little confusing how that's set up.

So then, when @ErikEJ said "pluralization is enabled by default in 5.0" .. does that then means "the pluralizer is enabled by default even though it's singular by default"?

**Comment by ErikEJ** [comment]
It pluralizes and singuralizes yes, and it is a breaking change as documented

**Comment by LuckySandwich** [comment]
Okay, thank you for the help!  Everything seems to be fixed now.

**Comment by ajcvickers** [comment]
@LuckySandwich Agreed that we could have named this better.
