### ISSUE TITLE
dotnet ef migrations fails with Directory.Build.props

### ISSUE THREAD

**Issue by eddieparker** [dotnet/efcore#23691]
Using the attached zip file, I can't get `dotnet ef migrations add InitialCreate` to work with the given Directory.Build.props.  I've tried various incantations of --msbuildprojectextensionspath and they all yield the following error:

```
D:\dev\personal\csharpsandbox\csharpsandbox.csproj : error MSB4057: The target "GetEFProjectMetadata" does not exist in the project.
Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
```
If you delete the Directory.Build.props file the sample builds fine however.

### Include provider and version information

EF Core version: 5.0.1
Database provider: Sqlite
Target framework: .netcore 3.1
Operating system: Windows
IDE: VS2019 16.8.3

[EFMigrateTest.zip](https://github.com/dotnet/efcore/files/5698429/EFMigrateTest.zip)

**Comment by ajcvickers** [comment]
@eddieparker Thanks for reporting this; we will investigate in the new year.

**Comment by huoyaoyuan** [comment]
If the `obj` path was changed by `Directory.Build.props`:
For 5.0.0, it required --msbuildprojectextensionspath option for me. For 5.0.1, it ignores the path and gemerates the targets file in `obj` (works silently).

**Comment by eddieparker** [comment]
> If the `obj` path was changed by `Directory.Build.props`:
> For 5.0.0, it required --msbuildprojectextensionspath option for me. For 5.0.1, it ignores the path and gemerates the targets file in `obj` (works silently).

Can I ask what you set the --msbuildprojectextensionpath to?  Using the above zip file I've tried:

`dotnet ef migrations add InitialCreate --msbuildprojectextensionspath _intermediate_/Debug/csharpsandbox` and I still end up with:

`D:\dev\personal\csharpsandbox\csharpsandbox.csproj : error MSB4057: The target "GetEFProjectMetadata" does not exist in the project.
Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
`

**Comment by huoyaoyuan** [comment]
I haven't downloaded your zip, but seems that you didn't set the base of relative path. For me it was `..\..\Artifact\obj\ProjectName\Debug\`. Here`..\..` navigates from the project path to the root path.

**Comment by bricelam** [comment]
Here is the correct way to configure MSBuildProjectExtensionsPath in your project:
```xml
<Project> <!-- NB: No Sdk="" here. -->

  <PropertyGroup>
    <MSBuildProjectExtensionsPath>$(MSBuildProjectDirectory)\_intermediate_\</MSBuildProjectExtensionsPath>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <!-- (Project content goes here) -->

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

</Project>
```
Then you can use the option on the command line:
```sh
dotnet ef migrations add InitialCreate --msbuildprojectextensionspath _intermediate_
```
Trying to set it anywhere else will result in very unexpected behavior that you'll probably need to use a tool like [MSBuild Log Viewer](https://msbuildlog.com/) to understand why it's not working.

**Comment by bricelam** [comment]
As @huoyaoyuan found, the easiest thing to do is to not touch `MSBuildProjectExtensionsPath` and just use the defaults.
