### ISSUE TITLE
Microsoft.EntityFramework.Core 3.1.10 and Microsoft.OData.Core 7.7.3

### ISSUE THREAD

**Issue by athinadev** [dotnet/efcore#23704]
Hello,

we've recently moved our projects from EntityFramework 6.4.4 to Microsoft.EntityFramework.Core 3.1.10 and there is an issue regarding the use of oData. When we send a query with group by we are getting the Exception.
System.InvalidOperationException: EF.Property called with wrong property name. at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) 

I have posted the issue to oData community and they said, that this is an EntityFramework.Core issue.
Other oData Clients say that the same problem has EntityFramework.Core 5.

Please see the last comments in oData Community here and provide a solution.
https://github.com/OData/WebApi/issues/2015 

We wait longer than 6 months for this issue to get fixed.

Thanks in advance

**Comment by iozcelik** [comment]
This issue also continiue at EF Core 5. We move project to EF Core 5 from EF 6 and stuck here. Group by and aggregation is not working. Even simple one.

**Comment by keatkeat87** [comment]
We are facing the same problem, EF Core 5, does anyone have a workaround/direction for this ?

**Comment by iozcelik** [comment]
I don't understand why anyone from ef core team give a date? Lots of people move their project to .net core. Also mean to ef core. This issue priority have to high.

**Comment by skarpovru** [comment]
This is a known issue since at least 2018: https://github.com/dotnet/efcore/issues/12088

**Comment by ajcvickers** [comment]
@athinadev @iozcelik @keatkeat87 We are tracking several issues that will improve GroupBy support--see https://github.com/dotnet/efcore/labels/area-groupby. These are scheduled for the next release of EF Core, which is EF Core 6.0 in November 2021.
