### ISSUE TITLE
Unclear example query

### ISSUE THREAD

**Issue by git-hub-user** [dotnet/efcore#23708]
The document show an example:

`context.Database.ExecuteSqlInterpolated($"SELECT * FROM [dbo].[SearchBlogs]({userSuppliedSearchTerm})")`

I have two issues with this:

1. `SearchBlogs` looks like a user defined function, which is not explained and overly complex for this case.
1. What use would it be to know how many records are effect by this statement, rather than obtaining the actual results? I can think of some, but not anything very common and it does not make this a clear example.

An update query would be much more straight-forward.

What I was actually looking for was `FromSqlInterpolated()`, which is the more applicable method for selecting data. You might want to reference it as a _see also_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de6f794-3c75-d76b-2f0f-ad567b85bf5b
* Version Independent ID: b1f0b083-db4f-a453-8390-b58c6102d4ce
* Content: [RelationalDatabaseFacadeExtensions.ExecuteSqlInterpolated(DatabaseFacade, FormattableString) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolated?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Note for triage: example is no longer in the code in main.
