### ISSUE TITLE
Multiple providers - Created migrations are not database agnostic

### ISSUE THREAD

**Issue by didster** [dotnet/efcore#23714]
Using EFC with multiple providers.

In v3.1.1 of EFC, migrations created against (say) MSSQL were created as something like as follows

```
migrationBuilder.CreateTable(
            name: "Users",
            columns: table => new
            {
                FirstName = table.Column<string>(nullable: true),
                LastName = table.Column<string>(nullable: true),
                Email = table.Column<string>(nullable: true),
            }
```

For the most part, these migrations could then be run against other databases such as say SQLite with no problem.  Where DB specific behaviour was required, the migrations could be manually modified to include conditional statements subject to the database being used.  This behaviour was described in the docs [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers)

In 5.0.1 however, migrations are now created as follows when the active provider is MSSQL:

```
migrationBuilder.CreateTable(
            name: "Users",
            columns: table => new
            {
                FirstName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                LastName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                Email = table.Column<string>(type: "nvarchar(max)", nullable: true),
            }
```  

The inclusion of the type: argument prevents the migration running on anything but MSSQL so the only option for multiple providers is now multiple derived context's or multiple migration assembles, both of which are somewhat involved to setup when you have a very simple model with just simple types.

Was there a reason this was changed? Is is possible to restore the old behaviour?  I'm unsure if its a bug or intended behaviour given the discussion about the use of conditional statements in the migrations has been removed from the docs.

Related SO question [here](https://stackoverflow.com/questions/65319430)

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer & Microsoft.Data.Sqlite
Target framework: .net core 3.1
Operating system: Win10
IDE: Visual Studio 2019 16.7.7

**Comment by ajcvickers** [comment]
@didster We made a conscious decision in 5.0 to move in this direction--see #16406 for details. You can still use conditional code like you were doing before, so you're not forced to move to multiple contexts or assemblies. However, there will be much more conditional code than before.

**Comment by didster** [comment]
@ajcvickers Aha ok thanks, good to know it was a conscious decision.

> You can still use conditional code like you were doing before

Yeah I guess kind of my point was more that I **wasn't** using it before, although was aware I could if needed, it just worked.  This was ideal for simple projects

Although I can see both sides of the argument as it always felt a bit fragile like I always forget to explicitly add `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` to identity columns which was needed to avoid manually updating the migrations to include conditional code.

I have now got the multi migration assembles setup and working which is a world easier than the last time I tried now you can pass args to the app from the tooling to further pass into the generic host to pick the active provider, so I'm all good.  

My only comment for something that needs more thought is the circular dependency issue you get when having multiple migration assembles.  The work around in the docs of modding the `BaseOutputPath` of the migration assembles to output to the main project works fine if you just have one project + migrations.  But it doesn't work if you have an explicate "model" project used by a main project and possibly others as if you output to the model project the migration assembles dont automatically get copied on to any dependent projects output folder as they are not explicate dependencies of the model project.  This sort of defeats part of the point of having an explicate model project you can share as anyone using it has to explicate references to both the model project and any migration project to ensure everything ends in the main projects output folder.

Anyway thats another issue - thanks again for the clarification.
