### ISSUE TITLE
How to use two DbContext Pool at the same time（AddDbContextPool）

### ISSUE THREAD

**Issue by vagile-cn** [dotnet/efcore#23715]
EF Core version: 3.1.0
Database provider: Mysql
Target framework: dotnet core 3.1
Operating system: win or centos 7
IDE: Visual Studio 2019 16.8.3

How to use two DbContext Pool at the same time（AddDbContextPool）
I'd try new two ServiceCollection by myself, and AddDbContextPool in  each ServiceCollection and build it，
then it will throw a exception...
![image](https://user-images.githubusercontent.com/22270643/102466749-6808be00-408a-11eb-9720-c17c22f3ec41.png)
the exception only will throw on the ServiceCollection that new by myself,
if use the default ServiceCollection to AddDbContextPool , it will not throw the exception .

I want use the Context pool that read from read-only db node and write to read-write db node
so  I need two Context pool..

who can tell me how to do this?

**Comment by vagile-cn** [comment]
Maybe because my English is so bad that no one can understand what I say?

**Comment by ajcvickers** [comment]
@vagile-cn There should not be any issue with calling AddDbContextPool multiple times--I tested this quickly--see below.

The exception posted above generally means what it says--multiple threads using the same context instance. However, there isn't enough information here to understand why it is being thrown. If you think there is a bug here, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Blog
{
    public int Id { get; set; }
}

public class Post
{
    public int Id { get; set; }
}

public class SomeOtherDbContext : DbContext
{
    public SomeOtherDbContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Post> Posts { get; set; }
}

public class SomeDbContext : DbContext
{
    public SomeDbContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Blog> Blogs { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        var serviceProvider = new ServiceCollection()
            .AddDbContextPool<SomeDbContext>(
                b => b.UseSqlServer(Your.ConnectionString)
                    .LogTo(m => Console.WriteLine($"1: {m}")))
            .AddDbContextPool<SomeOtherDbContext>(
                b => b.UseSqlServer(Your.OtherConnectionString)
                    .LogTo(m => Console.WriteLine($"2: {m}")))
            .BuildServiceProvider();

        using (var scope = serviceProvider.CreateScope())
        {
            var context1 = scope.ServiceProvider.GetService<SomeDbContext>();
            context1.Database.EnsureDeleted();
            context1.Database.EnsureCreated();

            var context2 = scope.ServiceProvider.GetService<SomeOtherDbContext>();
            context2.Database.EnsureDeleted();
            context2.Database.EnsureCreated();

            context1.Add(new Blog());
            context1.SaveChanges();

            context2.Add(new Post());
            context2.SaveChanges();
        }
    }
}

```

**Comment by vagile-cn** [comment]
thank you so much for your idea
I already Add two ContextPool by two DbContext class that classB is a subclass of classA
I do this by AddDbContextPool<classA> and AddDbContextPool<classB>
thank you so much!!!
