### ISSUE TITLE
Is there any way to get record from FromSqlRaw with insert xxx on CONFLICT xxx returning *?

### ISSUE THREAD

**Issue by xiaoxin01** [dotnet/efcore#23710]
## Ask a question

I want to generate an identity by id. So I has an class like:

```c#
public class Identifier
{
    public string Id { get; set; }
    public int Identify { get; set; }
}
```
I use FromSqlRaw to create or update identity by Id:

```c#
            var sql = @"
                INSERT INTO ##Identifiers## (##Id##, ##Identify##)
                    VALUES('aaa',1)
                ON CONFLICT (##Id##)
                DO 
                    update  SET ##Identify## = ##Identifiers##.##Identify##+1
                    RETURNING  *;".Replace("##", "\"");

            var identity = await _context.Identifiers.FromSqlRaw(sql).SingleAsync();
```

But I got an err, after check the log, I found that the sql generated by framework is:

```sql
              SELECT i.Id, i.Identify
              FROM
                INSERT INTO "Identifiers" ("Id", "Identify")
                    VALUES('aaa',1)
                ON CONFLICT ("Id")
                DO
                    update  SET "Identify" = "Identifiers"."Identify"+1
                    RETURNING  *;),
```
The added sql command 'SELECT xxx from xxx' will cause an err.

Is there any way to tell entity framework not to add the 'SELECT xxx from xxx' command?

### Include provider and version information

EF Core version: 5.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework:  .NET 5.0
Operating system: Ubuntu 18

**Comment by roji** [comment]
I've moved this to EFCore.PG as https://github.com/npgsql/efcore.pg/issues/1614, as it's specific to the PostgreSQL provider.

**Comment by roji** [comment]
Looking at this again, there actually doesn't seem to be anything to do here. If the raw SQL isn't composed over (in this case with SingleAsync), EF Core should simply execute the given raw SQL as a top-level query, which should work just fine. PG itself doesn't support nesting `INSERT INTO ... RETURNING ...` as a subquery, so there's nothing else to be done.

More concretely, try adding AsAsyncEnumerable before your Single (which should become SingleAsync, see [async LINQ operators](https://docs.microsoft.com/en-us/ef/core/miscellaneous/async#async-linq-operators). This would removing the composition in the query, making the INSERT top-level and executing the Single operator client-side.
