### ISSUE TITLE
Two List<> properties assigned the same instance when entity instance is materialized 

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#23726]
An entity type with two `List<int>` properties gets materialized with the properties pointing to the same instance when the lists are empty.

The example below configures the properties to use value converters, but this also occurs without value converters on PG where `List<int>` is natively supported. The same occurs with arrays instead of lists.

Originally raised by @jrhodnik in https://github.com/npgsql/efcore.pg/issues/1608.

<details>
<summary>Repro</summary>

```c#
await using (var ctx = new BlogContext())
{
    await ctx.Database.EnsureDeletedAsync();
    await ctx.Database.EnsureCreatedAsync();
}

await using (var ctx = new BlogContext())
{
    var blog = ctx.Blogs.Single();

    Console.WriteLine(ReferenceEquals(blog.One, blog.Two)); // true
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"...")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(e =>
        {
            e.Property(b => b.One).HasConversion(
                l => string.Join(",", l),
                s => s.Split(",", StringSplitOptions.None).Select(int.Parse).ToList());

            e.Property(b => b.Two).HasConversion(
                l => string.Join(",", l),
                s => s.Split(",", StringSplitOptions.None).Select(int.Parse).ToList());

            e.HasData(new Blog { Id = 1 });
        });
    }
}

public class Blog
{
    public int Id { get; set; }
    public List<int> One { get; set; }
    public List<int> Two { get; set; }
}
```

</details>

**Comment by smitpatel** [comment]
@dotnet/efteam - This behavior is expected. Both lists are null when saving, when it goes through converters and when it returns. So they are going to be reference equals since they are null.

**Comment by roji** [comment]
Sorry, I messed up the repro. The problem is actually not reproducible with value converters - below is an updated repro with PostgreSQL native mapping to `List<int>` (note the initialization of the properties to an empty list). I can investigate this as well, but wanted to report first in case it rings any bells.

<details>
<summary>Repro</summary>

```c#
await using (var ctx = new BlogContext())
{
    await ctx.Database.EnsureDeletedAsync();
    await ctx.Database.EnsureCreatedAsync();
}

await using (var ctx = new BlogContext())
{
    var blog = ctx.Blogs.Single();

    Console.WriteLine("Is null: " + (blog.One is null)); // False
    Console.WriteLine("ReferenceEquals: " + ReferenceEquals(blog.One, blog.Two)); // True
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql("Host=localhost;Username=test;Password=test")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(e => e.HasData(new Blog { Id = 1 }));
    }
}

public class Blog
{
    public int Id { get; set; }
    public List<int> One { get; set; } = new();
    public List<int> Two { get; set; } = new();
}
```

</details>

**Comment by smitpatel** [comment]
Since there is no value saved in database, it is probably whatever the type mapping does here. We just utilize the GetX methods to read the values. It doesn't look like anything wrong in the core part here and this could be npgsql specific issue.
Few things to check would be.
- Are values in the database after seeding as expected. 
- Is the type mapping able to read back correct value when passed whatever is database given value?
- Should also remove the new() initialization to see if that is causing some issue.

**Comment by roji** [comment]
Thanks, I'll investigate this further. Am leaving this open for now until I understand what's going on.

**Comment by roji** [comment]
This turned out to be an Npgsql ADO.NET bug (https://github.com/npgsql/npgsql/issues/3417).
