### ISSUE TITLE
Investigate why the .NET Portability Analyzer reports issues for EF Core

### ISSUE THREAD

**Issue by pas059** [dotnet/efcore#23722]
Hello,

I am in the process of migrating an application designed with Windows Forms/.Net 4.7.2/EF core 3.13 to Windows Forms/.Net 5/EF core 5.

using the [https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer](url), i already prepared the project for this. Now it remains only the EF core parts :smile: .
What is the recommended procedure: upgrade the EF core packages and then upgrade the project, or proceed in the reverse order? personaly, i intended to proceed with the first way.

Of course any other advice will be enjoyed

regards

### Include provider and version information

EF Core version: 3.13 then 5.0
Database provider: PostgreSQL, SQLite and SqlServer
Target framework: .Net Framework 4.7.2 then NET 5.0
Operating system:W10
IDE:  Visual Studio 2019CE 16.8.3

**Comment by ErikEJ** [comment]
You cannot do that, as EF Core 5 does not support .NET Framework.

**Comment by pas059** [comment]
thanks for your reply Eric.
i know that, i thought do this way just for updating the '.csproj' file, without trying to generate the project.
So, the 2scnd way, but as EF core 3.13 is not compatible with Net 5 (from the portability analyser), i will have hundreds (perhaps thousands) of errors.
regards

**Comment by pas059** [comment]
Exact Eric, not possible to proceed by he first way, so the second
Regards

**Comment by roji** [comment]
> EF core 3.13 is not compatible with Net 5 (from the portability analyser), i will have hundreds (perhaps thousands) of errors.

I'm not sure exactly what you mean there - you should be able to use EF Core 3.1 just fine in an application targeting .NET 5. .NET itself is backwards compatible, so whatever runs on earlier versions should run on later ones (modulu some very rare and targeted breaking changes).

**Comment by pas059** [comment]
Hi Roji,
I said that "EF core 3.13 is not compatible with Net 5" because after using the [,](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) on my project, the generated report shows many uncompatibilities for EntityFrameworkCore.
But no matter, what i wanted was to migrate to EF core 5, which implies to migrate the whole application to .net 5. It's done now, and, to my surprise, the app can access to databases created with previous version (EFc 3.13 + .Net 4.7.2) apparently without problem. Even if after reading thi [paper](https://docs.microsoft.com/fr-fr/ef/core/what-is-new/ef-core-5.0/breaking-changes), i was not really worried and if i have to check more, is this really surprising?

regards

**Comment by roji** [comment]
> what i wanted was to migrate to EF core 5, which implies to migrate the whole application to .net 5.

Just for accuracy, EF Core 5 targets .NET Standard 2.1, which means it can be used from .NET Core 3.1.

> is this really surprising?

That depends on exactly what you're doing :) In any case, it's good to hear the migration went smoothly.

**Comment by ajcvickers** [comment]
Re-opening this to discuss with the team. This is the second time recently that the [The .NET Portability Analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) has been reported to show issues for EF Core. I would like to understand this better.

**Comment by pas059** [comment]
Hi,
if this can help, i can send you the report.

**Comment by ajcvickers** [comment]
@pas059 Yes, that would be very helpful. Thanks!

**Comment by pas059** [comment]
Hi,
Here a [link](https://mega.nz/file/sp0WQL5C#iCYmwEjITNu-uku96WFLeDHbQyywD3xzVbV3wHTxEww)

regards

**Comment by ajcvickers** [comment]
[EFcApp_ApiPortAnalysis.html.txt](https://github.com/dotnet/efcore/files/5726366/EFcApp_ApiPortAnalysis.html.txt)

**Comment by JeremyLikness** [comment]
I was able to reproduce this with a very simple project and am following up with the team now.

**Comment by JeremyLikness** [comment]
File [Issue #993](https://github.com/microsoft/dotnet-apiport/issues/993) on the [dotnet-apiport](https://github.com/microsoft/dotnet-apiport/) repo.

**Comment by ajcvickers** [comment]
Closing as the external issue has been closed--the technology is deprecated.
