### ISSUE TITLE
OData functional tests use transitive references from IdentityServer

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#23739]
While working on #20547, I removed the reference to IdentityServer from the SQL Server functional projects.

```
<PackageReference Include="IdentityServer4.EntityFramework" Version="4.1.1" />
```

This caused the OData tests to fail due to some transitive dependencies on ASP.NET Core being used. I failed to figure out specifically which dependencies were being used, so I added the reference directly in the OData tests and filed this bug to follow up.

**Comment by smitpatel** [comment]
IdentityServer depended on an older version of shared framework which brought in certain MVC types like `HttpGetAttribute`/`ControllerBase`/`ModelBinderAttribute`. Using shared framework directly in the project using Web SDK gets those missing references.
