### ISSUE TITLE
EF 6 Multiple IDbContextFactory

### ISSUE THREAD

**Issue by ilmax** [dotnet/efcore#2374]
I hope this is the right place to fill EF6 issues, if not please redirect me to the correct place.

I found that EF does not throw when there are multiple IDbContextFactory implementations for the same context, IMHO an exception should be thrown to make the error crystal clear. Type names will be welcome in the exception message.

Regards, Max

**Comment by natemcmaster** [comment]
Thanks for sharing, Max. This repo is for EF 7. You can file issues for EF 6 on our Codeplex project at https://entityframework.codeplex.com.
