### ISSUE TITLE
Referencing multiple efcore libraries using different ef core versions

### ISSUE THREAD

**Issue by divinebovine** [dotnet/efcore#23749]
## Ask a question

Is there any way to support add multiple dbcontexts from libraries that may be using different versions of ef core? Currently we have one library that is ef core 3.1 for a sql server database and another that has upgraded to ef core 5 for a postgresql database. If we try to use them in the same project then we run into the following:
```sh
Unhandled exception: System.TypeLoadException: Method 'Create' in type 'Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitorFactory' from assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```
I understand that it may be an issue with dependency injection, but if there's a way to support this behavior, it would be helpful.

**Comment by anranruye** [comment]
just upgrade to Microsoft. EntityframeworkCore. SqlServer 5.0 in your main project which refer to other two projects.

**Comment by ajcvickers** [comment]
@divinebovine You may be able to get this to work by forcing everything to use the 5.0 version. However, this is not something I would recommend doing; you may run into incompatibilities at unexpected times. If at all possible update everything in a given assembly to reference the same EF Core version.

**Comment by divinebovine** [comment]
@anranruye thanks for the feedback, I will do some testing to make sure I don't run into issues.

@ajcvickers thank you too. I agree that's what needs to happen, but there's a challenge with getting multiple microservices (some owned by other teams) all updated in sync.
