### ISSUE TITLE
FromSqlInterpolated throws System.InvalidOperationException when calling to a stored procedure which returns an Entity containing an [Owned] property 

### ISSUE THREAD

**Issue by msschl** [dotnet/efcore#23754]
Same as #20743.

Are there any intentions to implement this feature soon?

**Comment by ajcvickers** [comment]
@msschl As indicated on #20743, this functionality is covered by #14525. That issue is on the backlog with one vote, and so is not something we plan to implement any time soon. Please add your vote (:+1:) to the issue.
