### ISSUE TITLE
Trying to obtain Model metadata about Owned Types and the nullability of properties

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#23758]
I am updating my [EfSchemaCompare](https://www.thereformedprogrammer.net/ef-core-taking-full-control-of-the-database-schema/) library which compares the current `Model` of an EF Core context with an actual database captured via the `IDatabaseModelFactory` service (scaffolding). This allows people who like to migrate their databases via hand-coded SQL scripts to ensure that their database changes matches what the EF Core context thinks the database schema is.

The current issue is around Owned Types, which can now be defined as `Required`. Currently I detect a nested Owned Type (and table splitting) by detecting that the primary key and foreign key are a) in the same table and b) are the same name as recommended by @smitpatel (see #10345). But with the new feature introduced in EF Core 5 you can now define a Owned Types as `Required`, which changes the nullability of the properties in an Owned Type.

Please advise if it is possible to detect the addition of the `Required` using the currently available `Model` or `EntityEntry<T>` features.

### Include provider and version information

EF Core version: 5.0
Database provider: any
Target framework:  .NET 3.1
Operating system:
IDE: Visual Studio 2019 16.8

**Comment by AndriySvyryd** [comment]
@JonPSmith The most robust way to get this information is to use the new `model.GetRelationalModel()` method to get the relational representation that handles all the mapping complexity and is resistant to future changes.

**Comment by JonPSmith** [comment]
Hi @AndriySvyryd,

Thanks for that. I have had a initial look but I need to do a lot more digging into this. I will be back with any questions (later).

**Comment by ajcvickers** [comment]
@JonPSmith Closing for now. We can re-open if you have further questions.

**Comment by JonPSmith** [comment]
No problem. I'm currently updating all my libraries to EF Core 5 + writing documentation. I plan to come back to this some time later.

**Comment by JonPSmith** [comment]
Hi @AndriySvyryd,

I have some time to look at the limitations in my [EfCore.SchemaCompare](https://github.com/JonPSmith/EfCore.SchemaCompare). At the moment I'm looking at detecting if a nested Owned Type has the `.IsRequired()` setting. It seems the `IRelationalModel` data on the table has a property `IsRequiredDependent` is true. e.g. `RelationalTable.PrimaryKey.MappedKeys[0].ReferencingForeignKeys[0].IsRequiredDependent` is true, if the  `.IsRequired()` method is applied to the Owned Type, e.g.

```c#
//inside the OnModelCreating method
modelBuilder.Entity<User>().ToTable("Users");
modelBuilder.Entity<User>().OwnsOne(e => e.HomeAddress);
modelBuilder.Entity<User>().Navigation(p => p.HomeAddress).IsRequired();
```

From this information I use the following code to detect that the `IsRequired` method was applied to the navigational link of an Owned Type. The two inputs are:

* `_model` is the `IModel`
* `table` is the `DatabaseTable` that the `IEntityType` is mapped to 

```c#
//This gets the relational table information for the correct table 
var thisTableRelational = _model.GetRelationalModel().Tables.Single(x =>
    x.FormSchemaTableFromITable(_defaultSchema) == table.FormSchemaTableFromDatabase(_defaultSchema));
// if this is true, then the nested Owned Type properties aren't forced to be nullable
var isRequired = thisTableRelational.PrimaryKey.MappedKeys.FirstOrDefault()?
    .GetReferencingForeignKeys().FirstOrDefault()?.IsRequiredDependent ?? false;
```

**My question is: My code assumes the first `MappedKeys` will contain the `IsRequiredDependent` I am looking for, is this correct?** It looks that way but there are so many options I can't test them all. 

*PS. I only found this difference by building code to traverse the metadata and and comparing the differences! I have seen you output text of Model - is there some code that I can use to output the `IModel` and `IRelationalModel` in an easy to read format?*

**Comment by AndriySvyryd** [comment]
@JonPSmith First let me ask whether you really need to now whether the owned type is required or would it be enough to know whether the columns it is mapped to are nullable?

**Comment by AndriySvyryd** [comment]
> My question is: My code assumes the first MappedKeys will contain the IsRequiredDependent I am looking for, is this correct?

No, the first mapped key will be for the principal entity type.

You can find out whether an owned entity type is optional or is required but declared on an optional owned type by calling:
```
myOwnedType.GetTableMappings().Single().Table.IsOptional(myOwnedType)
```

Of course a type might be mapped to more than one table, so it's best to start with an `ITable`.

> PS. I only found this difference by building code to traverse the metadata and and comparing the differences! I have seen you output text of Model - is there some code that I can use to output the IModel and IRelationalModel in an easy to read format?

```C#
var modelString = model.ToDebugString(MetadataDebugStringOptions.LongDefault);
var relationalModelString = model.GetRelationalModel().ToDebugString(MetadataDebugStringOptions.LongDefault);
```

**Comment by JonPSmith** [comment]
Thanks @AndriySvyryd - that worked great and is much more secure. I used the `ITable` version.

> @JonPSmith First let me ask whether you really need to now whether the owned type is required or would it be enough to know whether the columns it is mapped to are nullable?

Yes, I just need to know if the properly is nullable but I found the `IProperty.IsNullable` isn't correct for OwnedTypes and TPH and table splitting. Therefore I needed a method that corrected that, which that code goes in. If there is a better way to do this then let me know.

*PS. Thanks for the `ToDebugString` - that will be much easier to read than hovering over debug data.*

**Comment by JonPSmith** [comment]
I'm now looking TPT and getting some conflicting results (IModel PK constraint name, FK constraint name, and delete behaviour don't match the database - should I raise a separate issue for that?)

**Comment by AndriySvyryd** [comment]
> Yes, I just need to know if the properly is nullable but I found the IProperty.IsNullable from the Model isn't correct for OwnedTypes and TPH and table splitting. Therefore I needed a method that corrected that, which that code goes in. If there is a better way to do this then let me know.

If you are comparing database schemas `IColumnBase.IsNullable` will give you more accurate results.

> I'm now looking TPT and getting some conflicting results (IModel PK constraint name, FK constraint name, PK value generated, and delete behaviour don't match the database). Should I raise a separate issue for that or add it on this issue?

Use `IUniqueConstraint.Name` and `IForeignKeyConstraint.Name`. We'll add better support for this in https://github.com/dotnet/efcore/issues/19811

**Comment by JonPSmith** [comment]
> If you are comparing database schemas IColumnBase.IsNullable will give you more accurate results.

That worked, which removed a load of complex code I was using. Much better.

> Use IUniqueConstraint.Name and IForeignKeyConstraint.Name. We'll add better support for this in #19811

I tried that, but it wasn't correct. I have left that as a limitation, with a link to #19811

That is it for now. Thanks for the introduction to the `IRelationalModel`. That has a lot of useful stuff I didn't know about.
