### ISSUE TITLE
Error running acceptance tests in .net core in CI/CD pipeline

### ISSUE THREAD

**Issue by jlechem** [dotnet/efcore#23756]
I'm getting the following error from our CI/CD pipeline in GitLab. The test runs fine locally..

CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /home/nonroot/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/builds/credit-technology/core-platform/applications/ccks/CCKSApi.Domain/CCKSApi.Domain.csproj]
CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /home/nonroot/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/builds/credit-technology/core-platform/applications/ccks/CCKSApi.Repositories/CCKSApi.Repositories.csproj]
CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /home/nonroot/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/builds/credit-technology/core-platform/applications/ccks/CCKSApi.Services/CCKSApi.Services.csproj]
CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /home/nonroot/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/builds/credit-technology/core-platform/applications/ccks/CCKSApi.Managers/CCKSApi.Managers.csproj]
CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /home/nonroot/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/builds/credit-technology/core-platform/applications/ccks/CCKSApi/CCKSApi.csproj]
CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer cannot be created from /home/nonroot/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/builds/credit-technology/core-platform/applications/ccks/CCKSApi.AcceptanceTests/CCKSApi.AcceptanceTests.csproj]

**Comment by roji** [comment]
@jlechem can you please provide more information - ideally a repro - which would allow us to reproduce this? I'd specifically look into which .NET SDK you're using to build on your CI/CD, compared to your local environment, etc.

**Comment by roji** [comment]
Note #23234 which is similar and was resolved by using the correct .NET SDK.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
