### ISSUE TITLE
EF Core 5 AsSplitQuery() can not work with OData WebApi

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#23752]
Original Issue: https://github.com/OData/WebApi/issues/2380

Is there anything can help with ef core?

EF Core 5 split query is not exactly same as the behavior of EF Core 2.x. Is it possible to regress the behavior of version 2.x?

**Comment by smitpatel** [comment]
Duplicate of #21234 
5.0 does not support AsSplitQuery non-include scnearios.

**Comment by anranruye** [comment]
#21234 is marked as fixed.

However, we still can not use AsSplitQuery() OData WebApi.
