### ISSUE TITLE
Cant use Include query in SqlAzure!

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#2375]
for example: use ASP.Net Identity data schema, and code:

 var user2 = (from u in identityRepository.Table.Include(u=>u.Roles)
                            where u.Id == 1
                            select u).FirstOrDefault()

in SqlAzure throw an InvalidOperationException, but in localDB it works fine!

**Comment by divega** [comment]
@endink thanks for reporting this. Can you please provide the full details of the exception you are seeing?

**Comment by endink** [comment]
@divega Of cause, but there is a problem, I use the VS2015 RC with English language version, but i get the exception message is Chinese, because of my PC is Chinese ? the exception message like this, sorry for my bad English :

A database operation failed while processing the request.

AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
AggregateException: 发生一个或多个错误。 
InvalidOperationException: 已有打开的与此 Command 相关联的 DataReader，必须首先将它关闭。

BTW: InvalidOperationException also in the StackTrace  .


--------------------------------------------------------------------------------


There are pending model changes for ApplicationDbContext

Scaffold a new migration for these changes and apply them to the database from the command line:
> dnx . ef migration add [migration name] 
> dnx . ef migration apply

**Comment by rowanmiller** [comment]
> InvalidOperationException: associated with this Command's DataReader already open, you must first shut it down

Looks like MARS (multiple active result sets) is not enabled. You probably have `MultipleActiveResultSets=True` included in your localdb connection string but not in your SQL Azure connection string.

Can you enable MARS on your SQL Azure connection string and see if it resolves the issue?

**Comment by rowanmiller** [comment]
Can you also confirm which version you are using. We have removed the need for MARS in recent nightly builds.

**Comment by endink** [comment]
@rowanmiller Thanks Thank! It really because the MultipleActiveResultSets miss in the Azure connection string , when i add MARS, it works great ! I use EntityFramework 7.0.0-beta4 in VS2015 RC, SqlAzure version is 11. Thanks again!
