### ISSUE TITLE
Dotnet Core + Entity framework Core using Store Procedure - With multiple subsets of results.

### ISSUE THREAD

**Issue by allanisaikumar** [dotnet/efcore#23762]
My current store Procedure return result columns based on my conditions.
i.e in one set of my params it gives a b c columns.
in other set of params it gives a b d columns.

But the entity is of a b c d column properties...

this gives error for that d is not in query result in first case and c is not in query result in second case

Need us the way to have map the properties if result have that value otherwise take the default values of the properties...

Can we expect the feature of supporting in future ? or Can some one suggest the alternate to this.

**Comment by ajcvickers** [comment]
@allanisaikumar This is tracked by #21627; make sure to add your vote to that issue.
