### ISSUE TITLE
DbContext.ChangeTracker does not register information about objects deleted in cascade

### ISSUE THREAD

**Issue by AlexanderZhyrkov** [dotnet/efcore#23765]
## File a bug
I have the Blog object and the Post object with one-to-many relationship as described in [here](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key) 
When I delete Blog objects, related Post objects are deleted too. But if the post objects were not loaded into memory, then the information about their deletion will not be in the dbContext.ChangeTracker. I have attached a project that reproduces this behavior. Notice the changedEntityEntryCollection collection.
I use EF Core version 5.0.0
[ConsoleApp1.zip](https://github.com/dotnet/efcore/files/5741740/ConsoleApp1.zip)

**Comment by anranruye** [comment]
This is correct behavior.  These entities which are not loaded will be eventually deleted by the database.  In fact,  it's better to not load related entities if you don't need them,  which can improve performance.

**Comment by AlexanderZhyrkov** [comment]
Yes, but if I want to know which objects will be deleted? The ChangeTrackerdoes not allow it in this configuration.

**Comment by anranruye** [comment]
@AlexanderZhyrkov  Imposible!

**Comment by ajcvickers** [comment]
@AlexanderZhyrkov EF Core needs to have entities tracked in order to know what to delete. This won't be true once  #795 is implemented. However, even then if you need to know what is going to be deleted you will need to query the database in some way.
