### ISSUE TITLE
TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#23779]
I not sure, but seems this code has mistake:

https://github.com/dotnet/efcore/blob/03c1ba5275b11963ee1d05ad388ded2fda861c1b/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L1397-L1409

In case of obj1.CompositePK != obj2.CompositePK need generate SQL with **OR**:

NOT(obj1.CompositePK.part1==obj2.CompositePK.part1) OR NOT(obj1.CompositePK.part2==obj2.CompositePK.part2)

Your code generates SQL with **AND**:

NOT(obj1.CompositePK.part1==obj2.CompositePK.part1) AND NOT(obj1.CompositePK.part2==obj2.CompositePK.part2)

?

**Comment by maumar** [comment]
it indeed is a bug which results in data corruption
