### ISSUE TITLE
EF Core Owned types don't work for loading data but they do for saving

### ISSUE THREAD

**Issue by sergio222-dev** [dotnet/efcore#23788]
Hi!, I'm working in my project with entity that use value objects, I have read in the doc that if you want work with value objects you must use owned types.
When I save my entity with its repository this work perfectly, but when I try to load data this doesn't work, it only load my ID value object but not the others

this is my context
```c#
public class WikiContext : DbContext
    {
        private string _sConnection;
        
        #region Constructs

        public WikiContext()
        {
        }
        public WikiContext(string sConnection)
        {
            _sConnection = sConnection;
        }

        #endregion

        #region Entities

        public DbSet<Customer> Customers{ get; set; }

        #endregion

        #region Mapping

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(_sConnection);
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new CustomerConfiguration());
           
            base.OnModelCreating(modelBuilder);
        }

        #endregion
    }
```

this is my CustomerConfiguration:
```C#
public class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> builder)
        {
            // https://stackoverflow.com/questions/49607375/ef-core-dbcontext-map-custom-type-as-primary-key
            // http://thedatafarm.com/data-access/entity-framework-private-constructors-and-private-setters/
            builder.ToTable("Customers");
            builder.HasKey(customer=> new { customer.Id });
            builder
                .Property<CustomerId>("Id")
                .HasConversion(id => id.Value, guid => new CustomerId(guid));



            // https://www.edgesidesolutions.com/ddd-value-objects-with-entity-framework-core/
            builder.OwnsOne(c => c.Name, a =>
            {
                a.Property(p => p.Value).HasColumnName("Name");
                a.WithOwner();
            });

            builder.OwnsOne(c => c.StudioId, a =>
            {
                a.Property(p => p.Value).HasColumnName("StudioId").HasColumnType("uniqueidentifier");
                a.WithOwner();
            });

            
        }
    }
```

and this is my customer repository method
```c#
        public Customer[] Search()
        {
            var customers = Context.Customers.Select(customer=> customer);
            
            return customers.ToArray();
        }
```

I can do a workaround with the next model configuration, but I still have doubt about this way

```c#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Customer>(builder =>
            {
                builder.ToTable("Customers");
                builder.HasKey(customer => new { customer.Id });
                builder
                    .Property<CustomerId>("Id")
                    .HasConversion(id => id.Value, guid => new CustomerId(guid));
            
                builder
                    .Property<CustomerName>("Name")
                    .HasColumnName("Name")
                    .HasConversion(name => name.Value, value => new CustomerName(value));
            
                builder
                    .Property<StudioId>("StudioId")
                    .HasColumnName("StudioId")
                    .HasConversion(p => p.Value, value => new StudioId(value));
            });
            
            base.OnModelCreating(modelBuilder);
        }

        #endregion
```

this is the Customer Entity 
```C#
    public class Customer: IAggregateRoot
    {
        #region Constructors

        private Customer()
        {
        }
        
        public Customer(CustomerId oId, CustomerName oCustomerName, StudioId oStudioId)
        {
            Id = oId;
            Name = oCustomerName;
            StudioId = oStudioId;
        }

        #endregion

        #region Public Methods

        public static Customer Create(CustomerId oId, CustomerName  oName, StudioId oStudioId)
        {
            var oCustomer = new Customer(oId, oName, oStudioId);

            //TODO: implement event sourcing here

            return oCustomer;
        }

        #endregion

        #region Property

        public CustomerId Id { get; set; }

        public CustomerName Name { get; set; }

        public StudioId StudioId { get; set; }

        #endregion
    }

    public class CustomerName : StringValueObject
    {
        
        public string Value { get; set; }
        
        #region Constructors

        private CustomerName()
        {
        }

        public CustomerName(string sName)
        {
            Value = sName;
        }

        #endregion
    }
```

I can't figure out where the problem is, I tryed several model configuration but still I can understand why this doesn't works.

Also I made a quick repository where the same problem ocurrs [repository](https://github.com/sergio222-dev/EFCore-with-ownedtypes)

example
![image](https://user-images.githubusercontent.com/7524061/103431566-c49ec980-4bb0-11eb-8a88-b8678ab9cc4e.png)

what happens when I try to recover data
![image](https://user-images.githubusercontent.com/7524061/103431585-15162700-4bb1-11eb-9d7c-5363ea197be7.png)

EF Core version: 6 (also try it with 5.0.1)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5
Operating system: Windows 10
IDE: Rider 2020.3

**Comment by anranruye** [comment]
@sergio222-dev 
This moment I haven't opened the repository. But I can not find any problem from the code. 

Do you check the values in database?  I guess the saving process doesn't write these values into database. If not so,  I think this is a bug. Probably caused by combination of converter for the key column and owned entities. Try change the key property to a typical primitive type and see what happens.

**Comment by ajcvickers** [comment]
@sergio222-dev Your `CustomerId` class is used with a value converter. Since it is a reference type, it needs a value comparer, as documented here:https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers

I added this to your code and it worked for me:

```C#
            builder.Property(c => c.Id)
                .HasConversion(
                    id => id.Value, 
                    value => new CustomerId(value),
                    new ValueComparer<CustomerId>(
                        (l, r) => l.Value == r.Value,
                        v => v.Value.GetHashCode(),
                        v => new CustomerId(v.Value)));
```

Unfortunately, owned types don't work well as value objects. Using value converters is a better way to go, but currently requires serialization of multiple values into a single column until #13947 is fixed. See also #9906 and the issues and conversations linked from there.

**Comment by sergio222-dev** [comment]
> @sergio222-dev Your `CustomerId` class is used with a value converter. Since it is a reference type, it needs a value comparer, as documented here:https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers
> 
> I added this to your code and it worked for me:
> 
> ```cs
>             builder.Property(c => c.Id)
>                 .HasConversion(
>                     id => id.Value, 
>                     value => new CustomerId(value),
>                     new ValueComparer<CustomerId>(
>                         (l, r) => l.Value == r.Value,
>                         v => v.Value.GetHashCode(),
>                         v => new CustomerId(v.Value)));
> ```
> 
> Unfortunately, owned types don't work well as value objects. Using value converters is a better way to go, but currently requires serialization of multiple values into a single column until #13947 is fixed. See also #9906 and the issues and conversations linked from there.

Thanks, it works perfectly
