### ISSUE TITLE
left join best practice

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/efcore#23782]
Hi.
Left out join is used very often
Please suggest a better example of an extension.
Thank.

**Comment by ajcvickers** [comment]
@EvgenyPrikhodko Are use asking for better documentation or an extension method?

**Comment by EvgenyPrikhodko** [comment]
> @EvgenyPrikhodko Are use asking for better documentation or an extension method?

There is no (LEFT OUTER JOIN) method in EF.Core, we decided to make it as an extension in our project. Would like to know what is the best option offered by the community.

**Comment by ajcvickers** [comment]
@EvgenyPrikhodko Okay; hopefully somebody from the community will express an opinion.

**Comment by EvgenyPrikhodko** [comment]
@ajcvickers 
Hi.
Can you share your experience?

**Comment by roji** [comment]
@EvgenyPrikhodko just to make that you're aware of the [standard documented way](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#left-join) to express a left join, without a specific method:

```c#
var query = from b in context.Set<Blog>()
            join p in context.Set<Post>()
                on b.BlogId equals p.BlogId into grouping
            from p in grouping.DefaultIfEmpty()
            select new { b, p };
```

This is what we recommend doing.

**Comment by ajcvickers** [comment]
@EvgenyPrikhodko I would go further than @roji and say that I would hardly ever write a join directly. Instead I would create a model with appropriate required/optional relationships, then query against that model and using navigations for relationships. EF Core will then figure out what kind of join to perform based on the shape of the model.
