### ISSUE TITLE
InvalidOperationException: No database provider has been configured for this DbContext - Blazor Server Application

### ISSUE THREAD

**Issue by kmuthukumar23** [dotnet/efcore#23783]
Thanks in advance.

In Blazor server application with EF core, facing Runtime exception when using **-NoOnConfiguring** arg in the 'Scaffold-DbContext “connectionstring” Microsoft.EntityFrameworkCore.SqlServer -NoOnConfiguring -OutputDir Models'.

```
InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

I have followed this documentation for generating DbContext without on configuring.

https://docs.microsoft.com/en-us/ef/core/cli/powershell#scaffold-dbcontext

And this is my Startup code.

```
services.AddDbContext<TestBookContext>(opt => {
                string connectionString = @"Connectionstring";
                opt.UseSqlServer(connectionString);
            });
```
Note: I have created the DB by using VS 2019's SQL Server Object Explorer.

If we add the 'on configuring' method in DB context, then it works.

This is my Context.

```
namespace BlazorAppDBContext.Models
{
    public partial class TestBookContext : DbContext
    {
        public TestBookContext()
        {
        }

        public TestBookContext(DbContextOptions<TestBookContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Book> Books { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("Book");

                entity.Property(e => e.Author)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

Sample: 
[BlazorAppDBContext.zip](https://github.com/dotnet/efcore/files/5755541/BlazorAppDBContext.zip)

### Include provider and version information

EF Core version: 5.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:Window 10 version 1909
IDE: (e.g. Visual Studio 2019 16.9.0 Preview 1.0)
Server: Visual studio 2019 preview SQL Sever Object Explorer

**Comment by ajcvickers** [comment]
@kmuthukumar23 I'm not able to run your code, but it could be related to having both a parameterless and a parameterized constructor for your context:

```
        public TestBookContext()
        {
        }

        public TestBookContext(DbContextOptions<TestBookContext> options)
            : base(options)
        {
        }
```

Try removing the parameterless constructor, or possibly moving it after the parameterized constructor.

#23306 may be related.

**Comment by kmuthukumar23** [comment]
@ajcvickers Thanks for your try.

I have made the changes in the order of constructors but still not working. The same mentioned error is thrown. :(

**Comment by ajcvickers** [comment]
@kmuthukumar23 Did you try removing the parameterless constructor entirely?

**Comment by kmuthukumar23** [comment]
@ajcvickers No, I have placed the parameterless constructor after the parameterized one since facing the error when removing the parameterless constructor from here.

```
@code{
   //Facing Error at below line when remove the parameterless constructor
    TestBookContext tb = new TestBookContext();

    private List<Book> books;

    protected override void OnInitialized()
    {
        books = tb.Books.ToList();
    }
}
```

**Comment by ajcvickers** [comment]
@kmuthukumar23 If you create the context instance without passing any configuration to it, then this is likely the problem. See [DbContext Lifetime, Configuration, and Initialization](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/) for more information.

**Comment by WeihanLi** [comment]
Additional to @ajcvickers , you should get the `TestBookContex` by use `@inject TestBookContext tb` on top of page instead of `new TestBookContex`

- <https://docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-5.0>
- <https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0>
