### ISSUE TITLE
Mangled migration generated when altering database collation

### ISSUE THREAD

**Issue by donhuvy** [dotnet/efcore#23794]
Environment: Microsoft Visual Studio Community 2019 Version 16.8.3 ; .NET 5 version 5.0.101 ; ASP.NET Core Blazor WebAssembly 5, Microsoft SQL Server 2019, Windows 10 x64 version 2004.

Entity Framework Core 5.0.1 , Entity Framework Core Package Mange Console tool 5.0.1

run command

```
PM> Add-Migration
```

enter a name

```
SecondDay
```

I see error syntax at

```
migrationBuilder.AlterDatabase(,
                oldCollation: "SQL_Latin1_General_CP1_CI_AS");
```

![image](https://user-images.githubusercontent.com/1328316/103448334-d8d6e980-4cca-11eb-9f5c-93dce572f2a0.png)

**Comment by donhuvy** [comment]
Solution

Add these text

```
collation: default
```

```
migrationBuilder.AlterDatabase(collation: default,
                oldCollation: "SQL_Latin1_General_CP1_CI_AS");
```

but need fix it in source code of the tool.

**Comment by donhuvy** [comment]
I send a pull request at here https://github.com/dotnet/efcore/pull/23795

**Comment by roji** [comment]
@donhuvy I'm reopening this as the patch for 5.0.3 hasn't yet gone in.
