### ISSUE TITLE
Enhance the Change Tracking Proxy to notify changes of non-entity objects

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#23796]
I'm happy to notice that _Change Tracking Proxy_ is now a part of EF Core 5.
Is it possible to enhance it to notify changes of non-entity objects like what I did in https://github.com/dotnet/efcore/issues/23789#issuecomment-753292039?

Related issues and comments:
#23789 
#23790 
https://github.com/dotnet/efcore/issues/23790#issuecomment-753373251

**Comment by ajcvickers** [comment]
@anranruye We don't believe this is a good fit for the proxies for the same reasons the original issue is not a good fit for EF Core.

**Comment by anranruye** [comment]
@ajcvickers 
I agree,  there must be better ideas.
