### ISSUE TITLE
BuiltInDataTypes test base issue

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2379]
I am unable to implement these tests:
public override void Can_insert_and_read_back_all_non_nullable_data_types()
        {
            //base.Can_insert_and_read_back_all_non_nullable_data_types();
        }
        public override void Can_insert_and_read_back_all_nullable_data_types_with_values_set_to_non_null()
        {
            //base.Can_insert_and_read_back_all_nullable_data_types_with_values_set_to_non_null();
        }

As I am unable to ignore TimeSpan and DateTimeOffset, both of which are not supported by SQL CE.

**Comment by ajcvickers** [comment]
@ErikEJ Can you send a pull request that changes the tests so that any of the properties can be ignored using the same pattern for the ones that SQL Server currently ignores?

**Comment by ErikEJ** [comment]
@ajcvickers Yes, I plan to do that, just never got round to it yet. Should I make all properties "ignorable" or only Timespan and DateTimeOffset?

**Comment by lajones** [comment]
Actually would it be possible to test that the remaining properties do what they do in the base test. And that TimeSpan and DateTimeOffset throw or do whatever you expect them to do for SQL CE?

**Comment by ErikEJ** [comment]
@lajones Well, currently that is not possible, as the test method tests all properties. Or maybe I misunderstand your statement?

**Comment by ajcvickers** [comment]
@ErikEJ I would make all properties ignorable. @lajones I think that's a different test or a bigger refactoring. At the moment property types that are not supported are excluded from the model. Testing the negative case of a property type that is in the model but not supported would be useful, but that's probably best done in a separate test.

**Comment by ErikEJ** [comment]
@ajcvickers Yes, some test that throw "NotSupported" for unsupported datatypes would be great! I will make them all ignorable, then.

**Comment by lajones** [comment]
@ErikEJ @ajcvickers I agree it would be harder to do - more refactoring etc - but it would make for a better test I think. Still - if we can't do it right now @ErikEJ would you mind creating an issue so that we don't forget to do it later? Thanks.

**Comment by ErikEJ** [comment]
@lajones unsure what you are aiming for, so maybe better if you create it! 😉

**Comment by lajones** [comment]
@ErikEJ - if you create a model with e.g. a TimeSpan in it and point it at a SQL CE DB, what would you expect to happen when the user tries to use that model? How and under what circumstances should it fail? The test would just test that you get the expected failure(s).

**Comment by ErikEJ** [comment]
@lajones yes, that seems like a good test, and it is possibly missing from the current test suite. I would expect a NotSupported exception to be thrown in the typemapper

**Comment by lajones** [comment]
Added #2385
