### ISSUE TITLE
How to add an entity with auto-increment PK when there is a conversion for the PK property?

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#23793]
## Ask a question

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

When I try to solve #23741, I met this issue. See https://github.com/dotnet/efcore/issues/23741#issue-771743333
https://github.com/dotnet/efcore/issues/23741#issuecomment-748874873
https://github.com/dotnet/efcore/issues/23741#issuecomment-749048495

**Comment by ajcvickers** [comment]
@anranruye This is currently not supported. Support is tracked by #11597. If you're looking for how to prevent EF Core from treating a property as a navigation, then https://github.com/dotnet/efcore/issues/23741#issuecomment-749662975 covers that.

**Comment by anranruye** [comment]
Closing this because it is already tracked
