### ISSUE TITLE
Extraneous CLR property / CLR type Exception in Hierarchy of Related Objects

### ISSUE THREAD

**Issue by abbotware** [dotnet/efcore#23791]
When adding a new entity to my context I get a CLR Property error message that did not appear before complaining about a discriminator that worked without it.  If I remove the entity, the code works as before.  

Many of my objects all derive from an abstract base class called 'Entity'
There is another abstract base class 'Contact' which is then used for Business and Individual

**Entity** <- **Contact** <-  (**Individual** / **Business**)

Contact has a discriminator column ContactType which is an enum.

I am attempting to add a new entity that does not derive from Entity called **Association** that has a **To** and **From** property - both of which are Entity.

I can only assume that there is a bug due to the fact that I have a lot of inheritance and inter-related objects and the fact that I only get the error when I add:

`public virtual DbSet<Association> Associations { get; set; }`
 to the context

### Include your code

I would be more than happy to share the codebase (its small, but there are at least 20 entities) to any Microsoft Developer via a private github repo

### Include stack traces

"The CLR property 'ContactType' cannot be added to entity type 'Entity' because it is declared on the CLR type 'Contact'"

```
Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(string name, Type propertyType, MemberInfo memberInfo, Nullable<ConfigurationSource> typeConfigurationSource, ConfigurationSource configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, string propertyName, MemberInfo memberInfo, Nullable<ConfigurationSource> typeConfigurationSource, Nullable<ConfigurationSource> configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(MemberInfo memberInfo, Nullable<ConfigurationSource> configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasDiscriminator(MemberInfo memberInfo, ConfigurationSource configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>.HasDiscriminator<TDiscriminator>(Expression<Func<TEntity, TDiscriminator>> propertyExpression)
```

### Include verbose output

dotnet ef did not seem to work

### Include provider and version information

EF Core version: 5.0.1
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 5.0 / SDK 5.0.1)
Operating system: Windows 10
IDE: (Visual Studio 2019 16.8.3)

**Comment by ajcvickers** [comment]
@abbotware It sounds like Entity was previously not mapped in the model (an "unmapped base class") but adding references to it from the new entity type is now causing it to be mapped. Do you need navigations that reference the base type? What is the FK mapping in the database between the new type and the existing types?

**Comment by abbotware** [comment]
You are correct in the fact that Entity is not on my context object directly

By just adding (not the new **Association** class)
` public virtual DbSet<Entity> Entities { get; set; }`

I do indeed get the same exact exception!

**Comment by abbotware** [comment]
@ajcvickers - OK - i think I understand what is going on here - By using abstract base classes, and so far not referring to the base class **Entity** directly - I am in a sense getting a form of  'Table Per Hierarchy' since I see many different tables in the sql server even though they all derive from Entity

When creating the above **Assocation**, I am crossing hierarchies and using the base **Entity** in a FK, EF Core wants to collapse the hierarchies - and the Discriminator column 'breaks'?

if i change my association class to the following:

   public class Association
    {
        public int Id { get; set; }
        public Contact From { get; set; }
        public Contact To { get; set; }
    }

I get no problems at all...  I was attempting to make a generalized association class/entity between all entities... however looking at the DB schema that seems impossible anyway given that there is not 'Entity' table

**Comment by ajcvickers** [comment]
@abbotware That seems like a correct analysis to me.

**Comment by abbotware** [comment]
@ajcvickers - Is it then possible to split the Entity base into its own table so that is common among all other hierarchies?

**Class Hierarchy**
Entity <- Contact <- (Individual / Business)
Entity <- Document

**Schema**
Table 1: Entity [Abstract]
Table 2: Contact [Abstract] (Business [Concrete]/ Individual [Concrete])  
Table 3: Document [Concrete]
Table 4 : Association [Concrete]  (Entity to/from Entity)

Such that one can create an Association with referential integrity across different Hierarchies?

Or is this scenario unsupported? :-/

**Comment by anranruye** [comment]
@abbotware see at https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-type-configuration

**Comment by abbotware** [comment]
@anranruye - ive seen that before - but I was hoping to be able to have more fine grain control over the which types are merged into their own table (Contact - Individual + Business) ... I suppose just going 100% TPT effectively gets what I want :-)
