### ISSUE TITLE
Possible bug in SqlServerTypeMapper

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2381]
I think maybe the DbTypes have been swapped here:

```
               ?? TryMapSized(typeName, typeNamePrefix, new[] { "nchar", "national char", "national character" }, firstQualifier, 
               DbType.AnsiStringFixedLength)
               ?? TryMapSized(typeName, typeNamePrefix, new[] { "char", "character" }, firstQualifier, 
               DbType.StringFixedLength)
```

(Just testing "BuiltInDataTypes" for the SQLCE provider)

If this is the case, I think test coverage may be missing

**Comment by ajcvickers** [comment]
@ErikEJ This code has gone from the SQL Server mapping in my latest changes (which are waiting on review). We no longer use the sized type mappings in SQL Server because we want to keep the Size property on the DbParameter constrained regardless of actual column width in the database.
