### ISSUE TITLE
Optionally enable server-evaluation for non-correlated query fragments

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#23819]
See #23764. We typically evaluate expressions on the client when they are not correlated to any database object. This greatly helps creation of efficient parameters. However, this can be problematic when the database evaluation returns different results than the database translation. This can be opted into in the place handling the translation--for example the NTS plugin in this case. However, it could also be useful to allow this be be opted into by the application.

**Comment by roji** [comment]
@ajcvickers the NTS plugin can already opt specific methods out of client evaluation via evaluatable filters (I think this is what @smitpatel referred to in the meeting), so if we decide we want to *always* exclude certain methods, we can already do that.

This issue still makes sense as an application opt-out (i.e. via EF.ServerEval() or similar)

**Comment by smitpatel** [comment]
We can add this to design meeting if people want to discuss in detail.
- We can do this if we come across an absolute scenario where this makes sense. (So this propose-close is not _never_ but rather wait for feedback where other mechanism does not work)

The flipside of "forcing" server eval of some expression in the query is that, there needs to be server equivalent translation for it else it will be translation failure. Currently translation comes from core provider, plugins and UDFs.
- UDFs are already excluded from evaluating on client.
- DbFunctionExtensions we provide are also excluded (thanks to @roji)
- Currently plugin/provider don't exclude expression from client eval if possible, but if they are aware of methods which can generate different result, they can add that too. Our evaluatable expression filter also takes plugins so plugin can exclude any expression too.

Only case right now where the opt-out would actually work where the code did not opt-out when adding translation by error. So we should wait for a case where this actually helps.

**Comment by AndriySvyryd** [comment]
We discussed this in triage and the value proposition of having a general way of forcing server evaluation is low value and high cost. We'll handle specific cases like NTS when needed.
