### ISSUE TITLE
Regression issue where command line migrations with -o updates the snapshot in the project 

### ISSUE THREAD

**Issue by theo-albers** [dotnet/efcore#23828]
## File a bug
Up to EF Core 3.x the behavior was like this:
- in your C# project folder where you have EF Core migrations
- dotnet ef migrations add SecondVersion -o c:\temp
- in the folder c:\temp we now have:
  - <date prefix>SecondVersion.cs
  - <date prefix>SecondVersion.designer.cs
  - MyDbContextModelSnapshot.cs
- in the project folder nothing is changed

With EF Core 3.x I can rerun "dotnet ef migrations add SecondVersion" without the -o option and it will add the exact same migration to my project.

In EF Core 5.x the behavior is like this:
- in your C# project folder where you have EF Core migrations
- dotnet ef migrations add SecondVersion -o c:\temp
- in the folder c:\temp we now have:
  - <date prefix>SecondVersion.cs
  - <date prefix>SecondVersion.designer.cs
- in the project folder the model snapshot is changed
  - MyDbContextModelSnapshot.cs

With EF Core 5.x I can rerun "dotnet ef migrations add SecondVersion" without the -o option and it will add an empty migration to my project, because the model snapshot is already changed.

I expect the -o option to respect the output path and not to touch my local model snapshot file. This allows me to easily check my migration, change the code, redo, etc. until I'm satisfied with the outcome.

Run run-testcase.cmd in the sample project to see the behavior.
[EfCoreSample.zip](https://github.com/dotnet/efcore/files/5781294/EfCoreSample.zip)

**Comment by AndriySvyryd** [comment]
@bricelam

**Comment by bricelam** [comment]
This is the result of fixing #13342. The migration generated by `dotnet ef migrations add` must be added to the project.

Here are some options for previewing a migration:

1. Use `dotnet ef migrations remove` to remove it and generate a new, corrected one
2. Use version control to revert the changes and generate a new one
3. Use the underlying APIs to build your own tool:
   ```cs
    var db = new MyDbContext();

    var serviceCollection = new ServiceCollection();
    serviceCollection.AddEntityFrameworkDesignTimeServices();
    serviceCollection.AddDbContextDesignTimeServices(db);
    var serviceProvider = serviceCollection.BuildServiceProvider();

    // Scaffold a migration
    var migrationsScaffolder = serviceProvider.GetService<IMigrationsScaffolder>();
    var migration = migrationsScaffolder.ScaffoldMigration(migrationName, rootNamespace);

    File.WriteAllText(migrationFile, migration.MigrationCode, Encoding.UTF8);
    File.WriteAllText(migrationMetadataFile, migration.MetadataCode, Encoding.UTF8);
    File.WriteAllText(modelSnapshotFile, migration.SnapshotCode, Encoding.UTF8);
    ```

**Comment by theo-albers** [comment]
Thanks for listing the alternatives. I guess I have to learn a new habit and undo the snapshot file when using the -o option.
