### ISSUE TITLE
Make multi-targeting of .NET 5 and .NET Core 3.1 for Azure Functions

### ISSUE THREAD

**Issue by shibayan** [dotnet/efcore#23838]
I would like to take advantage of the great features of Entity Framework Core 5.0 right away, but unfortunately Azure Functions, which I use a lot, cannot run Entity Framework Core 5.0.

https://github.com/Azure/azure-functions-host/issues/6949
https://github.com/Azure/azure-functions-vs-build-sdk/issues/472

The reason for this is simple, Entity Framework Core refers to `Microsoft.Extensions.*` and `System.*` version 5.0.x. However, it will probably take a very long time for Azure Functions to support this, so It would be great if multi-targeting could be added on the EF Core side.

**Comment by roji** [comment]
Note that EF Core targets .NET Standard 2.1, which is compatible with .NET Core 3.1 - and so do all of the Microsoft.Extensions dependencies etc. Are you saying you have an issue with using .NET Core 3.1 on Azure Functions?

**Comment by shibayan** [comment]
I am aware that .NET Standard 2.1 is compatible with .NET Core 3.1, and I understand that the same is true for EF Core 5.0 dependencies.

In other words, it's a compatibility issue on the Azure Functions side, but I expect it will take a long time to resolve.

We want to use new features such as Many-to-Many, but the compatibility issue with 5.0 has completely stopped our plans. (Alternatively, features such as Many-to-Many can be backported to solve my problem...)

**Comment by roji** [comment]
@shibayan unfortunately there's not much we can do - both making EF Core 5.0 target .NET Standard2.0, and backporting many-to-many to EF Core 3.1 are not something we'll be doing.

However, at least according to the docs, [Azure Functions do seem to support .NET Core 3.1](https://docs.microsoft.com/en-us/dotnet/architecture/serverless/azure-functions). Are you sure you're not hitting some other issue?

**Comment by shibayan** [comment]
@roji Thank you. I knew it would be difficult, and I will give strong feedback to the Azure Functions team.

I am very grateful for the Many-to-Many support in Entity Framework Core. Thanks to the development team.
