### ISSUE TITLE
EF Core tools set default context

### ISSUE THREAD

**Issue by Luk164** [dotnet/efcore#23840]
## Ask a question

When using `Add-migration` or `Update-database` with multiple contexts these tools require me to specify which one I want to use every time by setting `-Context`. In my app I have a set of contexts, each targeting a different database provider, and one that is used as a proxy, to switch to one of them depending on settings, so it is essentially the only one ever used. Is there any way to set a default context so that we do not have to specify it manually every time using the `-Context`?

### Include provider and version information

EF Core version: 5.0.1
Target framework: .NET 5.0
Operating system: Win10
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
@Luk164 I think in the past we have recommended that people use the capabilities of the shell to do things like this. See the discussion on #20862.

**Comment by bricelam** [comment]
Here's a bit of PowerShell magic to set a default for the session:
```ps1
$PSDefaultParameterValues=@{ "*:Context"="My.Default.DbContext" }
```

**Comment by JeremyMahieu** [comment]
As you said it's only until the session ends. You'd have to do this every time you restart Visual Studio. If you persist it in your profile, then you have the same context for all projects.

Unless there is a profile per project this is not a good solution imo.

It'd be much better that this is defaulted in code somewhere.

**Comment by durmazoguzhan** [comment]
> Here's a bit of [PowerShell magic](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_parameters_default_values) to set a default for the session:
> 
> $PSDefaultParameterValues=@{ '*:Context'='My.Default.DbContext' }

not a real solution. any design time recommendations?
