### ISSUE TITLE
`dotnet ef` tool backwards compatibility

### ISSUE THREAD

**Issue by m4ss1m0g** [dotnet/efcore#23843]
I don't find any clues about backwards compatibility about `dotnet ef` tool.
I have some projects with EF Core 2.2, others with EFCore 3 each of them with specific `dotnet ef` tool version installed.
I would to know if I can install (globally) `dotnet ef` tool version 5.

There are any drawbacks ?
There are potentially issues ?

What are the rules when updating the tool ?

**Comment by ajcvickers** [comment]
@m4ss1m0g Yes, the tool is backwards compatible; it's a thin wrapper. I would always update to the latest version. Note, however, that 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/).
