### ISSUE TITLE
Timestamp/rowversion columns in SqlServer

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#23842]
I am using Microsoft.EntityFrameworkCore.SqlServer 5.0.1. I have read from the documentation that SqlServer usually uses byte[] property for a rowversion column. Is byte[] the only type that can be marked as rowversion?
I am just wondering if there is any way for the application to make .net type 'DateTime' a Timestamp/rowversion column as well.
If this not supported yet, are there any future plans to support this?

In the following test, using LastUpdated column as byte[] works fine, but using it as DateTime type does not work and throws "**Cannot insert the value NULL into column 'LastUpdated'** "

### Code-
Here is the class I am using-
```C#
public class Blog
{
public Guid Id { get; set; }
public DateTime LastUpdated { get; set; }
public string Name { get; set; } = "";
}
```
Here is the OnModelCreating()-
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Blog>(e =>
	{ e.Property(p => p.LastUpdated).IsRowVersion(); });
}
```
Here is the main function-
```C#
static void Main(string[] args)
{
	Console.WriteLine("Hello World!");
	var blog = new Blog
	{
		Name = "Test"
	};

	using (var context = new TestDbContext())
	{
		try
		{
			context.Database.EnsureDeleted();
			context.Database.EnsureCreated();

			context.Blogs.Add(blog);
			context.SaveChanges();
			var lastUpdated = blog.LastUpdated;

			blog.Name = "Test2";
			context.SaveChanges();
			var lastUpdated2 = blog.LastUpdated;
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
		}
	}
}
```

EF Core version: 5.0.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
In SQL Server, [the `rowversion` type](https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver15) (of which `timestamp` is a deprecated synonym) is a binary type; the values it contains do not in any way represent an actual date/time, but rather an opaque version which is only guaranteed to change as the row changes. Therefore, mapping CLR DateTime to SQL Server `rowversion` isn't supported; even if it were done (e.g. via value converters), the actual DateTime values you'd see would be arbitrary, and wouldn't represent that actual date/time of the row change.

If you're looking to create a date/time column which changes every time the row is modified, you can use a database trigger to do that. [Our docs contains example of doing that](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#value-generated-on-add-or-update).

**Comment by ajcvickers** [comment]
@shvmgpt116 You can also mark and use properties as concurrency tokens and update them manually without using the automatic rowversion mechanism at all.
