### ISSUE TITLE
Shouldn't be this exception of type DbUpdateException?

### ISSUE THREAD

**Issue by Enderlook** [dotnet/efcore#23841]
Hi, I'm quite new using EF, so maybe this is foolish, but I got this error:

> System.InvalidOperationException: The property 'SomeEntity.PrimaryKey' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal.

I perfectly know what the error means and how to fix it (I accidentally modified a primary key field, and PK fields can't be edited), but I got confused about `InvalidOperationException`, shouldn't be `DbUpdateException`?

[Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.dbupdateexception?view=entity-framework-5.0.0) says about `DbUpdateException`:
> Exception thrown by `DbContext` **when the saving of changes to the database fails**. Note that state entries referenced by this exception are not serialized due to security and accesses to the state entries after serialization will return null.
(Emphasis mine)

Since the exception was produced when excuting `dbContext.SaveChangesAsync()`, shouldn't it be of type `DbUpdateException`?.

### Include provider and version information

Target framework: .NET 5
Packages:
- Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore 5.0.1
- Microsoft.AspNetCore.Identity.EntityFrameworkCore 5.0.1
- Microsoft.EntityFrameworkCore.SqlServer 5.0.1
- Microsoft.EntityFrameworkCore.Tools 5.0.1

Operating system: Windows 10 
IDE: Visual Studio Community 2019 16.8.3

**Comment by anranruye** [comment]
This exception is actullay throwed by `ChangeTracker.DetectChanges()` which is called inner `DbContext.SaveChanges()`. You can see this from the exception stack trace. The call to `ChangeTracker.DetectChanges()` is before creating any sql command and database connection. Thus there is no database access. If you call `DbContext.ChangeTracker.DetectChanges()` manually, you can also see this exception.

**Comment by Enderlook** [comment]
Oh, I see, so `DbUpdateException` is only for errors produced on the database, not prior to the SQL command generation. Thanks for the clarification.
