### ISSUE TITLE
HasValueGenerationStrategy doesn't set identity seed and increment

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#23844]
HasValueGenerationStrategy on the convention builders sets SqlServerValueGenerationStrategy.IdentityColumn, but doesn't set the seed and increment to their default of 1 (although it does reset them to null if another strategy is configured). This is contrast to the user-facing UseIdentityColumn, which always sets the seed and increment.

There probably isn't an actual bug here, but we may want to make the behavior consistent.

/cc @AndriySvyryd

**Comment by ajcvickers** [comment]
Discussed in triage. The application API explicitly sets all these things, while the convention only sets the values it needs to set.
