### ISSUE TITLE
DbContextTransaction should also rollback dbcontext

### ISSUE THREAD

**Issue by hemantrhtk** [dotnet/efcore#23850]
//PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.1" 
   // PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.1" 

```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace TestWithSQLite
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var context = new MyContext();
            context.Database.OpenConnection();
            context.Database.EnsureCreated();

            var xyz = new MyEntity { ID = 1, Name = "Hemant1" };

            context.Targets.Add(xyz);
            context.SaveChanges();
            xyz.Name = "Hemant2";
            using var transaction = context.Database.BeginTransaction();
            try
            {
                var currentEntity = context.Targets.Find(xyz.ID);
                currentEntity.ID = xyz.ID;
                currentEntity.Name = xyz.Name;
                context.Targets.Attach(currentEntity);
                context.Entry(currentEntity).State = EntityState.Modified;
                context.SaveChanges();//context.SaveChanges(false); also gives same behaviour
                throw new Exception("dummy");
                transaction.Commit();
            }
            catch
            {
                transaction.Rollback(); //underlying db is rolling back but context is not
            }


            var finalStateOfEntity = context.Targets.Where(a => a.ID == xyz.ID).FirstOrDefault();
          //  context.Entry(finalStateOfEntity).Reload();//if this is uncommented, Hemant1 is printed, I shouldn't have to reload.
            Console.WriteLine(finalStateOfEntity.Name); //should be Hemant1, but it comes Hemant2
            Console.ReadLine();


        }
    }

    public class MyEntity
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {

        public virtual DbSet<MyEntity> Targets { get; set; }



        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("DataSource=:memory:", x => { });
         
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```

**Comment by ajcvickers** [comment]
@hemantrhtk This is by-design. When calling `SaveChanges(false)`, EF Core does not update the states of entities to indicate that database update succeeded until `AcceptAllChanges` is called. This leaves the context in a state where the database update can be re-tried by calling SaveChanges again. EF Core does not discard your changes; if you want this behavior, then consider it starting a new unit of work and create a corresponding new context instance.

**Comment by hemantrhtk** [comment]
Thanks @ajcvickers  correct me if I am wrong, by design , 
"transaction.Rollback(); //underlying db is rolling back but context is not"
is supposed to only rollback db, but not the context irrespective of SaveChanges(false) or SaveChanges(true)

If developer wants to resuse "context" after the transaction is over its bad a bad code/design. Against EFCore guidlines.

**Comment by ajcvickers** [comment]
> By design of EF Core, every transaction block must have its own "context"

No. It's by-design that you have a new context for each unit-of-work. If something goes wrong and the transaction isn't committed, then changes can be made to the current context, representing the current unit-of-work, and SaveChanges can be called again to replay the same unit-of-work to the database.

If you want to start over will a clean DbContext after a transaction failed, then this would be a new unit-of-work, and should have a new context.

**Comment by hemantrhtk** [comment]
@ajcvickers
What I understood, ( I talk by example)

Say I have three entities which don't have relationships defined in models for some misterious reasons,

But in DB  E1 Id is reffred in E2. And E3 refers to E2.

Use the same instance of context to create update delete E1, E2 and E3 in a single unit of work.

After E1 is created call savechanges because E2 needs db generated id of E1
Call save changes after creation of E2
Since E3 needs db generated Id of E2

at the end commit transaction. Happy path all good.


if say E3 creation fails, And I want to fail the whole request to the api in this request block  in my unit of work.

So dispose context which  was added as a scoped instance using DI..
(db rollback was already honored by transaction.Rollback(), )

And on the next request create another scoped context instance and inject that.
(new context picks current state from db so all good - happy happy even in case of failure)

This part I understand.


Now I give similar example (over similified) in the original post but this time I act on delete operation in the transaction

]In case of Edit failure, transaction.Rollback() kept new value of Name in the context (Not OK) and old value in DB (OK)] - original post above.
In case of Delete failure ,  transaction.Rollback() didn't delete in db (Ok) and context (OK) both. - see below.
So transaction.Rollback() attitude towards context is not consistent in case of edit and delete operations.





// Include="Microsoft.EntityFrameworkCore" Version="5.0.1" 
//Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.1" 


using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace TestWithSQLite
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var context = new MyContext();
            context.Database.OpenConnection();
            context.Database.EnsureCreated();

            var xyz = new MyEntity { ID = 1, Name = "Hemant1ToBeDeletedlater" };

            context.Targets.Add(xyz);
            context.SaveChanges();
            using var transaction = context.Database.BeginTransaction();
            try
            {
                var currentEntity = context.Targets.Find(xyz.ID);
                context.Targets.Remove(currentEntity);
                context.SaveChanges();
                throw new Exception("dummy");
                transaction.Commit();
            }
            catch
            {
                transaction.Rollback(); //underlying db is rolling back but context is not
            }


            var finalStateOfEntity = context.Targets.Where(a => a.ID == xyz.ID).FirstOrDefault();
            Console.WriteLine(finalStateOfEntity == null);// prints false
            Console.ReadLine();


        }
    }

    public class MyEntity
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {

        public virtual DbSet<MyEntity> Targets { get; set; }



        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("DataSource=:memory:", x => { });
         
            base.OnConfiguring(optionsBuilder);
        }
    }
}

**Comment by ajcvickers** [comment]
@hemantrhtk You need to suppress accepting the changes by calling `SaveChanges(false)`. Otherwise EF Core updates the state of the context immediately the SaveChanges succeeds.

**Comment by hemantrhtk** [comment]
> You need to suppress accepting the changes by calling `SaveChanges(false)`. Otherwise EF Core updates the state of the context immediately the SaveChanges succeeds.

In both the samples above ( delete and edit), `SaveChanges(false)` and `SaveChanges()` exhibit similar behaviour both on the db side and on the context final state after rollback.

**Comment by ajcvickers** [comment]
@hemantrhtk In that case I will need to investigate this as a bug.

**Comment by ajcvickers** [comment]
@hemantrhtk 

> In both the samples above ( delete and edit), SaveChanges(false) and SaveChanges() exhibit similar behaviour both on the db side and on the context final state after rollback.

I am not able to replicate this. Can you post a runnable code example where switching `SaveChanges()` to `SaveChanges(false)` results in the same behavior?

**Comment by hemantrhtk** [comment]
@ajcvickers 

[ConsoleApp4.zip](https://github.com/dotnet/efcore/files/6214821/ConsoleApp4.zip)

**Comment by ajcvickers** [comment]
@hemantrhtk In either case, the following entities are being tracked before SaveChanges:

```
MyEntity {ID: 1} Modified
  ID: 1 PK
  Name: 'Hemant2' Modified Originally 'Hemant1'
```

With `SaveChanges(false)`, the changes are written to the database, but the change tracker is not updated:

```
MyEntity {ID: 1} Modified
  ID: 1 PK
  Name: 'Hemant2' Modified Originally 'Hemant1'
```

With `SaveChanges()`, the changes are written to the database and the change tracker is updated to reflect this:

```
MyEntity {ID: 1} Unchanged
  ID: 1 PK
  Name: 'Hemant2'
```

**Comment by hemantrhtk** [comment]
@ajcvickers 

kindly post a sample code. where "context" is restored to original state upon error is encountered in using var transaction = context.Database.BeginTransaction();

either with save changes or without it.

Upon error db is honouring rollback, but not the context

you may suggest savechanges true or false or any other means to achive this.

issue is "DbContextTransaction should also rollback dbcontext #23850"

you suggested try savechanges with false.

We tried it here in the sample code but did not work.

**Comment by ajcvickers** [comment]
> kindly post a sample code. where "context" is restored to original state upon error is encountered in using var transaction = context.Database.BeginTransaction();

EF does not do this. There is nothing in the EF Core code that restores the state of the DbContext. If you want to start again with no changes applied to the context, then you need to create a new context instance, or use `context.ChangeTracker.Clear()`.

**Comment by hemantrhtk** [comment]
Kindly correct me if I am wrong here:

Purpose of DbContextTransaction is to create a transaction on the database side. 
DbContextTransaction  must not be held responsible to rollback dbcontext.

in case of failures in try catch developer is responsible to either use a new instance of DbContext
OR do something like
context.ChangeTracker.Clear()

Above part is now clear to all the audiences ( I hope ) including me.


**Next unsolved mystery may be 
"If in case of edit operations developer was reposnible to either use a new context or call clear()
, then why attached code rolled back context for delete operations.
 It is not a consistent behaviour across all CRUD operations."**


[ConsoleApp5.zip](https://github.com/dotnet/efcore/files/6224911/ConsoleApp5.zip)

**Comment by ajcvickers** [comment]
@ajcvickers Nothing in the context is rolled back. In your code, SaveChanges _succeeds_, and hence the DbContext is updated to reflect the state of the succeeded call to modify the database. Nothing then happens to the context later if you choose to not commit the transaction, or explicitly roll it back.

**Comment by hemantrhtk** [comment]
> @ajcvickers Nothing in the context is rolled back. In your code, SaveChanges _succeeds_, and hence the DbContext is updated to reflect the state of the succeeded call to modify the database. Nothing then happens to the context later if you choose to not commit the transaction, or explicitly roll it back.

Console.WriteLine(finalStateOfEntity == null);// prints false in consoleapp5. means as per context rollback happened.

Console.WriteLine(finalStateOfEntity.Name); //prints Hemant2 in consoleapp4, means as per context rollback did not happen.


under similar test for delete and edit behaviour is different for delete and edit operations.

**Comment by ajcvickers** [comment]
@hemantrhtk There is nothing there indicating that the context has been rolled back. The transaction on the database has been rolled back, so a query against the database for that entity returns the entity as expected.

**Comment by hemantrhtk** [comment]
> @hemantrhtk There is nothing there indicating that the context has been rolled back. The transaction on the database has been rolled back, so a query against the database for that entity returns the entity as expected.

@ajcvickers what I conclude from above:
1. context.Database.BeginTransaction() returns IDbContextTransaction which guarantees rollback on db side but doesn't promise rollback of DbContext itself.
2. It is advisable to discard current dbcontext and use a new instance  in senerios where developer had to call DbContextTransaction.rollback()
3. if point two above(discard) is not followed and developer is under situation where he had to called rollback, 

a) for edit operations actions taken by .savechanges persist in dbcontext, but in database they roleback duely. [ risky, dbcontext is out of sync ] proof ConsoleApp4
b) for delete operations actions taken by .savechanges do not persist in dbcontext and in database also they rollback. [OK] proof ConsoleApp5

So, to make a general rule ( which definitely will work in both edit and delete) here developer should follow point two above(discard dbcontext) whenever a situation arrives which deems to call .rollback()

Kindly comment on this.

**Comment by ajcvickers** [comment]
@hemantrhtk

> a) for edit operations actions taken by .savechanges persist in dbcontext, but in database they roleback duely. [ risky, dbcontext is out of sync ] proof ConsoleApp4
b) for delete operations actions taken by .savechanges do not persist in dbcontext and in database also they rollback. [OK] proof ConsoleApp5

I'm not sure how you are coming to these conclusions, but they are not connect. It might be a good idea to have another read of the [change tracking documentation](https://docs.microsoft.com/en-us/ef/core/change-tracking/) to understand how calling SaveChanges affects the state of tracked entities.

**Comment by ajcvickers** [comment]
@hemantrhtk I have run your code. The conclusions you are drawing from your code are not correct.

**Comment by keatkeat87** [comment]
@hemantrhtk, @ajcvickers 

I understand it this way, I don't know if it's right.

DbContext != transaction.
dbcontext as a unit of work scope. the responsibility is to manage entity state (added, modified, unchanged, deleted).

it tracks entity and set state for each.
when calling save changes, it check the state and generate SQL query string.
if save changes success the state will be clear (it has done the job, they don't care whether the transaction will be commit or rollback later.)
if fail the state will just stay there, you decide how to handle it.
it can't be "rollback", but you can context.ChangeTracker.Clear() to clear the state.

Transaction is another thing. It takes over after "save changes" job.
You can create 1 transaction and use it on multiple dbcontext (unit of work). every dbcontext allow call multiple times save changes and all will be collected in transaction to decide commit or rollback/rollback save point.

although most of the cases, we love dbcontext = transaction, they can rollback together. but EF Core won't make the limitation. you have to use your strategy to manage yourself.
