### ISSUE TITLE
Entity Framework Core 5.0 does not support string.Concat with more than 2 args

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23859]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Entity-Framework-Core-50-does-not-suppo/1285537)._

---
<p>A Query similar to:</p><pre>From t In Me.DataStore.qryAbo
Where t.AboAdrKey = 1035
Order By t.AboActive Descending, t.PrdName, t.TypName
Select New With {t.AboKey, t.AboAdrKey, t.AboActive, . PrdName = String.Concat(t.PrdName, &quot; &quot;, t.TypName, If(t.AboTrial, &quot; (Trial)&quot;, &quot;&quot;))}
</pre><p>gets translated to</p><pre>DECLARE @__DataRow_AdrKey_0 int = 1035;
SELECT [q]. [AboKey], [q]. [AboAdrKey], [q]. [AboActive], [q]. [PrdName], [q]. [TypName], CASE WHEN COALESCE([q].[ AboTrial], CAST(0 AS bit)) = CAST(1 AS bit) THEN N' (Trial)'
    ELSE N''
END
FROM [qryAbo] AS [q]
WHERE COALESCE(CASE
    WHEN ([q].[ AboAdrKey] = @__DataRow_AdrKey_0) AND [q]. [AboAdrKey] IS NOT NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, CAST(0 AS bit)) = CAST(1 AS bit)
ORDER BY [q]. [AboActive] DESC, [q]. [PrdName], [q]. [TypName]
</pre><p>which brings back 6 columns instead of 4.</p> <p>Is this by design or should System.Concat be supported?</p> <p>Thank you for feedback.</p>

---
#### May Lei [MSFT] on 12/13/2020, 11:39 PM: 

<p>Not sure the area path, please help to reassign if the area path is not correct. Thanks.</p>

#### Travico Support on 12/15/2020, 05:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by smitpatel** [comment]
We are not capturing overloads which takes 3 & 4 strings as args. Easy to add in RelationalStringMethodTranslator.

**Comment by wmeints** [comment]
I'd like to try and fix this one as a first issue. One question though: What do you mean with the string.Concat overloads for cosmos? Do you have the link to the source file for me where these overloads are located?

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.string.concat?view=net-5.0

**Comment by wmeints** [comment]
Sorry, I think I wasn't very clear with my question. I'm looking for the class that translates the `String.Concat` for the CosmosDB provider. In the mean time I was able to locate the one for the relational provider. 

https://github.com/dotnet/efcore/blob/0b3165096d6b55443fc06ae48404c2b037dd73e7/src/EFCore.Relational/Query/Internal/StringMethodTranslator.cs#L72

**Comment by ajcvickers** [comment]
Looks like this didn't make it into the preview 1 branch. It was merged after preview 1 branched, but before branding was updated to preview 2.
