### ISSUE TITLE
Nuget error: Package Microsoft.EntityFrameworkCore 5.0.1 is not compatible with netcoreapp3.1 

### ISSUE THREAD

**Issue by habakuk007** [dotnet/efcore#23867]
Hello,

if I try to update to Package Microsoft.EntityFrameworkCore 5 via nuget in a .Net Core 3.1 application I get on some developer machines this error messages (and on some it works):

    NU1202: Package Microsoft.EntityFrameworkCore 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore 5.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
    NU1202: Package Microsoft.EntityFrameworkCore.Abstractions 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore.Abstractions 5.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
    NU1202: Package Microsoft.EntityFrameworkCore.InMemory 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore.InMemory 5.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
    NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore.Sqlite 5.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
`

If I got it right EntityFrameworkCore 5 requires .Net Standard 2.1 - but this is available from [.Net Core 3.0 ](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

Any idea what is wrong here?

Regards
   Stefan

**Comment by roji** [comment]
I'd start by checking which .NET SDK is installed on the machines where this failure occurs. Try cleaning/removing all SDKs and installing the latest 5.0 one from scratch.

**Comment by habakuk007** [comment]
Hello @roji, thanks for your answer!

I tried to reinstall .Net SDK and also to update the "Visual Studio Build Tools 2019", but still get the same error.

Now I have this environment:

* Windows Server 2012 R2
* .Net v5.0.2 - SDK 5.0.102
* Visual Studio Build Tools 2019 16.8.4

Any other ideas, i still get:

`NU1202: Package Microsoft.EntityFrameworkCore 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore 5.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)`

**Comment by habakuk007** [comment]
I updated to Microsoft.EntityFrameworkCore 5.0.2, now the error looks like this:

`NU1202: Package Microsoft.EntityFrameworkCore.Sqlite 5.0.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.EntityFrameworkCore.Sqlite 5.0.2 supports: netstandard2.1 (.NETStandard,Version=v2.1)

**Comment by ErikEJ** [comment]
You need the .NET Core 3.1 SDK then!

**Comment by roji** [comment]
I think using the 5.0.102 .NET SDK should work as well - but I'm guessing that you have some sort of installation issue that's still picking up the old SDK. I'd suggest cleaning your machine and removing all .NET SDKs, and/or trying on another blank machine to confirm.

**Comment by habakuk007** [comment]
We could finally fix the problem by updating Nuget... We used 4.9.1, after the update to 5.8.1 it worked.

**Comment by farman-Ameer** [comment]
Open .csproj file in notepad and change the target version from 3.1 to 2.1
From
`<TargetFramework>netstandard3.1</TargetFramework>`
To
`<TargetFramework>netstandard2.1</TargetFramework>`
Save notepad. Clean Solution then rebuild the solution and install package.
