### ISSUE TITLE
Creating a database asynchronously at runtime - race conditions

### ISSUE THREAD

**Issue by Perustaja** [dotnet/efcore#23876]
I am trying to handle the creation of databases using existing migrations at runtime using injected connection strings. The only way I can think of doing this is via a factory for my specific ```DbContext```. I found a very similar example in [this sample repository](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Data/FactoryExtensions.cs). 

Here is my code currently, which works. It creates a database if the tenant currently doesn't have one, and doesn't if they already do. 

```TenantedDbContext.cs``` - the main context
```
    public class TenantedDbContext : DbContext, ITenantedDbContext
    {
        // DbSets and other properties omitted for brevity
        public string TenantId => _tenant.Id;
        private readonly string _connectionString;
        private readonly Tenant _tenant;

        public TenantedDbContext(DbContextOptions<TenantedDbContext> options,
            IConfiguration config,
            ITenantProvider tenantProvider) // Note that ITenantProvider has Scoped lifetime
            : base(options)
        {
            _tenant = tenantProvider.GetCurrentRequestTenant();
            _connectionString = config.GetTenantedConnectionString(_tenant.Id);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Bypass tenant configuration if this context was created at design time
            if (!optionsBuilder.IsConfigured)
            {
                // The tenant string is valid because by this point it has been vouched via authorization/factory
                optionsBuilder.UseMySql(_connectionString)
                    .ReplaceService<IModelCacheKeyFactory, TenantedModelCacheKeyFactory>();
            }
        }
    }
```

```RuntimeDbContextFactory``` - The factory creating databases for tenants if they aren't created yet
```
    public class RuntimeDbContextFactory<TContext> :  IRuntimeDbContextFactory<TContext> 
        where TContext : DbContext, ITenantedDbContext
    {
        private readonly IServiceProvider _svcProvider;

        public RuntimeDbContextFactory(IServiceProvider svcProvider)
        {
            _svcProvider = svcProvider ?? throw new ArgumentNullException(nameof(svcProvider));
        }

        public TContext CreateContext()
        {
            var db = ActivatorUtilities.CreateInstance<TContext>(_svcProvider);
            if (!db.Database.GetService<IRelationalDatabaseCreator>().Exists())
                db.Database.Migrate();
            return db;
        }
    }
```

```RuntimeFactoryExtensions``` - Extension methods to register the factory in ```Startup.cs``` The only difference from the sample project is that I changed the default lifetime to be ```ServiceLifetime.Scoped```, because this is not for a Blazor project, and because the default ```DbContext``` scope is normally ```Scoped```.
```
    public static class RuntimeFactoryExtensions
    {
        public static IServiceCollection AddRuntimeDbContextFactory<TContext>(
            this IServiceCollection collection,
            Action<DbContextOptionsBuilder> optionsAction = null,
            ServiceLifetime lifetime = ServiceLifetime.Scoped) // NOTE: Scoped because this is not for Blazor
            where TContext : DbContext, ITenantedDbContext
        {
            // Instantiate with scoped provider
            collection.Add(new ServiceDescriptor(
                typeof(IRuntimeDbContextFactory<TContext>),
                sp => new RuntimeDbContextFactory<TContext>(sp),
                lifetime));

            // Run per request
            collection.Add(new ServiceDescriptor(
                typeof(DbContextOptions<TContext>),
                sp => GetOptions<TContext>(optionsAction, sp),
                lifetime));
            
            return collection;
        }

        private static DbContextOptions<TContext> GetOptions<TContext>(
            Action<DbContextOptionsBuilder> action,
            IServiceProvider sp = null) where TContext : DbContext
        {
            var ob = new DbContextOptionsBuilder<TContext>();
            if (sp != null)
                ob.UseApplicationServiceProvider(sp);
            action?.Invoke(ob);
            return ob.Options;
        }
    }
```

Is it okay to change the lifetime here to ```Scoped``` if the project is not going to be based around Blazor? Also, I noticed in the sample repository that the way the database is created/seeded has a note regarding race conditions. I am not using this code directly, but my creation code in the factory is basically the same thing without seeding, and using ```Migrate()``` instead of ```EnsureCreated()```.

[Sample code for runtime creation](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Data/FactoryExtensions.cs)
```
        /// <summary>
        /// This is NOT for production use. This extension method creates
        /// and populates the database for the first time to make the sample
        /// easiser to run. In production scenarios it could cause a race
        /// condition.
        /// </summary>
        /// <param name="factory">The <see cref="DbContextFactory{ContactContext}"/> to use.</param>
        /// <param name="count">The number of contacts to generate.</param>
        /// <returns>A <see cref="Task"/>.</returns>
        public static async Task EnsureDbCreatedAndSeedWithCountOfAsync(this DbContextOptions<ContactContext> options, int count)
        {
            var builder = new DbContextOptionsBuilder<ContactContext>(options);
            builder.UseLoggerFactory(new LoggerFactory());
            using var context = new ContactContext(builder.Options);
            // result is true if the database had to be created
            if (await context.Database.EnsureCreatedAsync())
            {
                var seed = new SeedContacts();
                await seed.SeedDatabaseWithContactCountOfAsync(context, count);
            }
        }
```

Sorry, so this is where the main question is. Is this due to the seeding or the singleton lifetime? Or is what I am doing also cause for potential race conditions, I am not seeding the database nor will I have to. Also, if the factory creates the context asynchronously, how should it be instantiated in repositories, controllers, etc? I suppose the last question may be more suited to StackOverflow (or maybe this whole question).

Is runtime creation of a database just inherently an operation that will have race conditions?

**Comment by ajcvickers** [comment]
@Perustaja Migrating databases at runtime can have race conditions when:

* Multiple users hitting the same server try to migrate the database concurrently
* Multiple servers using the same database try to migrate the database concurrently

So, to do this safely, you need to ensure that the migration of the database happens once and once-only.

However, even if it is safe, it's still not recommended in most cases because database migration is a deployment concern and not a runtime concern. It is best done with permissions appropriate to deployment, and at a single, well-known time. See 

See https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli for more information.

**Comment by Perustaja** [comment]
> @Perustaja Migrating databases at runtime can have race conditions when:
> 
> * Multiple users hitting the same server try to migrate the database concurrently
> * Multiple servers using the same database try to migrate the database concurrently
> 
> So, to do this safely, you need to ensure that the migration of the database happens once and once-only.
> 
> However, even if it is safe, it's still not recommended in most cases because database migration is a deployment concern and not a runtime concern. It is best done with permissions appropriate to deployment, and at a single, well-known time. See
> 
> See https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli for more information.

I see, thank you for the reply. After thinking about it more and making an SO post I think the approach is just poor on my part. I think a better approach would be to have the identity provider send a gRPC message telling the main web api to create a new tenant's database, but making sure that it is transactional and any requests to the tenant during instantiation are rejected, and the database is deleted if somehow the entire process doesn't finish properly.

It would be once and only once this way, and would allow for migrations with the CLI tool later. So, I am not trying to migrate at runtime per se, just trying to create a new database with the current migrations applied. I have migrations from a design time context with dummy tenant data so that everything should be migrations-friendly.


I think you answered the main question. Thank you
