### ISSUE TITLE
Target .NET Standard 2.0 again

### ISSUE THREAD

**Issue by YZahringer** [dotnet/efcore#23894]
EF Core 5.0 require .NET Standard 2.1. This is a problem for platforms that do not [support it](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support):
- [UWP](https://github.com/dotnet/standard/issues/1567)
- [Unity](https://docs.unity3d.com/2020.2/Documentation/Manual/dotnetProfileSupport.html)
- .NET Framework

Related to:
- https://github.com/dotnet/efcore/issues/18141#issuecomment-542798580
- https://github.com/dotnet/efcore/issues/19535
- https://github.com/dotnet/efcore/pull/23713
- https://github.com/dotnet/efcore/issues/19588

Multitarget `netstandard2.0;netstandard2.1` until `net6.0` release could be considered?

**Comment by ajcvickers** [comment]
@YZahringer This is not something we are going to do. We don't make the final call on what we target, and .NET Standard 2.1 was chosen after much discussion internally on the options available. EF Core 6.0 will likely drop .NET Standard entirely and target .NET 6. 3.1 is an LTS release and is the recommended version to use for those who must target .NET Standard 2.0.
