### ISSUE TITLE
Create api for setting custom names for constraints(primary key, foreignkey, default, unique)

### ISSUE THREAD

**Issue by oxffaa** [dotnet/efcore#2389]
By default constraint for foreignkey - FK_dbo.Table1_dbo.Table2_Id .  Need posibility for set name as  FK_Table1_Table2_SomethingElse_Id or another.

**Comment by rowanmiller** [comment]
Here is the code for Beta 4

```c#
            modelBuilder.Entity<Blog>()
                .Collection(b => b.Posts)
                .InverseReference(p => p.Blog)
                .ForeignKey(p => p.BlogId)
                .ForRelational().Name("FK_Blog");
```

We're simplifying the API in future releases though (removing the need for the `ForRelational()` call and renaming `Name` to `ConstraintName`)
