### ISSUE TITLE
Odata ovewrites OrderBy typed in the code even if no $orderby  query option is given

### ISSUE THREAD

**Issue by cap7ainjack** [dotnet/efcore#23891]
I`m using .NET 5 and I have problem using orderby to IQueriable in a way it was working before.

here are the models I use
```
// The DTO models
public class OfficeDto
{
		public Guid Id { get; set; }
		public string ZipCode{ get; set; }
		public IEnumerable<IdAndName> Employess { get; set; }
}

public class IdAndName 
{
		public Guid Value { get; set; }
		public string Text{ get; set; }
}


// The DB model
public class OfficeEntity {
			public Guid Id { get; set; }
		public string ZipCode{ get; set; }
		public virtual ICollection<XrefOfficesEmployees> XrefOfficesEmployees{ get; set; }
}
```

I want to order my entire Odata result to nested object property. In this case I want to order by Employess.Text
As far as I know this is not supported by Odata. This is ok. So I have additional logic which order by the IQueriable before the Controller return the result:

// The SELECT:
```
var list = query.Select(x =>
	new AddressDto()
	{
		Id = x.Id,
		ZipCode = x.ZipCode,
		
		Employees = x.XrefOfficesEmployees
			.OrderBy(y => y.Order)
			.Select(y => new IdAndName()
			{
				Value = y.EmployeeId,
				Text = y.Employee.FirstName + " " + y.Employee.LastName,
				Order = y.Order
			})
	});
```

And the custom order by

`list = list .OrderByDescending(b => b.Employees .Select(a => a.Text).FirstOrDefault( ));`

So this thing was wokring just fine in the previous versions of .NET Framework (4.7.2) and now it seems Odata just ovewrites it to nothing.

Here is the example URL:

> api/OfficeList?$count=true&$top=20&$skip=0&$select=id,zipcode ,employees
	
No  $orderby.

Maybe some configuration of he Odata which i cannot find...

**Comment by anranruye** [comment]
what version of libraries do you use?

**Comment by cap7ainjack** [comment]
Basicaly everything is the latest.
Microsoft.AspNetCore.OData => 7.5.4
Microsoft.Data.OData => 5.8.4
Microsoft.OData.Core => 7.8.1

**Comment by ajcvickers** [comment]
@cap7ainjack What version of EF Core are you using?

**Comment by cap7ainjack** [comment]
[EnableQuery(EnsureStableOrdering = false)] fixed my problem.

**Comment by cap7ainjack** [comment]
Actually [EnableQuery(EnsureStableOrdering = false)] solves that problem, but with this option when I have a lot queries on same endpoint, more than 100 i get this exception:

"System.InvalidOperationException","Message":"A second operation was started on this context before a previous operation completed."

I spend a lot of time to figure it out, but when i remove the mentioned option above this does not happen. But I have problem again with the OrderBy....

I Use Microsoft.EntityFrameworkCore 5.0.2

**Comment by cap7ainjack** [comment]
I have tried with Microsoft.AspNetCore.OData 8.0.0-preview3 and the issue is still here.  Still getting the 

"System.InvalidOperationException","Message":"A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext."

exception. 

Should this be moved to new Issue or is OK to be here as the original problem is related to this?
