### ISSUE TITLE
Updating a part of list in list

### ISSUE THREAD

**Issue by mortezarezaei68** [dotnet/efcore#23909]
I had problems updating a part of a list which I could solve, using the method below. This problem occurs  when we want to send a  list to backend after we have updated it in the presentation layer. When validating the list. we often struggle with figuring out which items   have been added or removed from the list. 

The extension method I wrote would help solve the issue by updating the old list items with new ones in the presentation layer or could removing items that have been deleted. This could be very useful in creating object values. 
  ```
public static void Update<T>(this IList<T> currentList, IList<T> list) where T : class 
{ 
    var added = list.Except(currentList).ToList(); 
    var removed = currentList.Except(list).ToList(); 
 
    added.ForEach(currentList.Add); 
    removed.ForEach(a => currentList.Remove(a)); 
} 

```

**Comment by roji** [comment]
@mortezarezaei68 your method doesn't seem to have anything to do with EF Core - just generic code for manipulating .NET IList... As such, it doesn't seem very appropriate for inclusion into EF Core.

**Comment by anranruye** [comment]
see at https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities to learn how to handle related entities of a disconnected entity with navigation property.

if your list is not used for navigation property, you can simply tell the backend the states of your entities with your dto model.
```C#
var dto = dataFromFrontend;
var db = new YourDbContext();
db.AddRange(dto.New);
db.RemoveRange(dto.Deleted);
db.UpdateRange(dto.Updated);
db.SaveChanges();
```
