### ISSUE TITLE
Navigation Property with Foreign Key Constraint

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#23907]
## Ask a question
I am replicating Data from a remote database. When data is replicated, it may appear in arbitrary order so I may have a parent object that references child objects which have not yet been replicated locally.

Today, my related properties are stored as integer Fields with no navigation property.

How can I add a navigation property that will not create a foreign key constraint?

**Comment by ajcvickers** [comment]
@TonyValenti That depends what you mean by, "create a foreign key constraint." EF Core always uses FK values to manage relationships. However, it understands that the principal side may not be loaded and hence can be more forgiving of FK values that don't have a corresponding FK value. However, EF Core will assume that such entities do exist in the database.

So if you mean prevent EF Core from treating the value as an FK, then that isn't possible. However, see #13146.

On the other hand, EF Core doesn't care whether or not the foreign key constraint itself exists in the database or not. If you're using EF Core migrations to create the database, then just delete the constraint from the generated migration.
