### ISSUE TITLE
Update debug views to be resilient to exceptions

### ISSUE THREAD

**Issue by FireEmerald** [dotnet/efcore#23903]
The `EntityFrameworkQueryableExtensions.ToQueryString(IQueryable)` Method throws a `InvalidOperationException` if the queryable object contains for example a `Func<T>`. This should be noted in the documentation.

  | Name | Value | Type
-- | -- | -- | --
◢ | e | {"The LINQ expression 'DbSet<LoadcontrolEntry>()\r\n    .Count(l0 => Invoke(__selectorFunc_0, [RelationalEntityShaperExpression], l0)\r\n    )' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."} | System.Exception {System.InvalidOperationException}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba1d5d38-85ff-3d18-beec-a319668d7c01
* Version Independent ID: 1f4e07b6-b928-b2c0-0499-be2c854ec541
* Content: [EntityFrameworkQueryableExtensions.ToQueryString(IQueryable) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.toquerystring?view=efcore-5.0#Microsoft_EntityFrameworkCore_EntityFrameworkQueryableExtensions_ToQueryString_System_Linq_IQueryable_)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by FireEmerald** [comment]
@ajcvickers Could you explain why the to query string method does not work when the `IQueryable` contains a delegate function call? The reason must be in the process of how a `IQueryable` is analyzed. I thought it's because the efcore framework doesn't know what the delegate does until it is executed?

**Comment by ilmax** [comment]
@FireEmerald EF core doesn't work with delegates, it works with expressions that may look very similar but they are a completely different thing. A delegate is a pointer to a function while an expression is a data structure and ef works with the latter. Long story short change the type from `Func<T, bool>` to `Expression<Func<T, bool>>`
