### ISSUE TITLE
Simple Logging to StreamWriter does not log if any filters are applied

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#23908]
## File a bug

Following the guidance in the docs:

DbContext has a StreamWriter declared 

`private StreamWriter _writer = new StreamWriter("D:\\EFCoreLog.txt", append: true);`

In OnConfiguring, LogTo points to the streamwriters writeline delegate

```
   optionsBuilder.UseSqlServer(conn)
             .LogTo(_writer.WriteLine);
```

_writer is getting disposed:

```
    public override void Dispose()
        {
            base.Dispose();
            _writer.Dispose();
        }
```

With the simple logging this simple (no filtering) the log file gets created and the logs are added and appeneded to as needed.

However when adding any type of filtering (just loglevel, just EF Core log category, or a combination) nothing gets added to the file. This will create a file if it doesn't exist but no logs are sent in.

I fear I'm missing a key element in the set up but I believe I followed the docs correctly.

What am I missing?

Thanks (with a nod to Clementine who reported this to me in Pluralsight course discussion)

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
Hi @julielerman. I'm not able to reproduce this--see my code below. Can you look to see what might be different in my code than in the code where you are seeing this?

```C#
public class Blog
{
    public int Id { get; set; }
}

public class SomeDbContext : DbContext
{
    private StreamWriter _writer = new StreamWriter("/home/ajcvickers/EFCoreLog.txt", append: true);
    
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(_writer.WriteLine, LogLevel.Information);

    public override void Dispose()
    {
        base.Dispose();
        _writer.Dispose();
    }
}    

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog());
            
            context.SaveChanges();
        }
    }
}
```

**Comment by julielerman** [comment]
gah ...will check. Can't imagine how my project could be messing with this functionality. Thanks @ajcvickers

**Comment by julielerman** [comment]
tried it again with a simpler project. Only difference is I'm on windows. I am using 5.0.2.  Now I'll create a completely new project and copy paste YOUR code.
'

**Comment by julielerman** [comment]
[Sob] of course new console app (.NET 5) with only your code is working. Now I have to figure out WAT!?!?!?!!! Will report back and close when solved.

**Comment by julielerman** [comment]
Hey I finally found the setup that is causing the problem! It's related to teh scope of the context.
When it's a class wide variable is when it fails to write into the log file when I append a filter or log level.
I moved things around a lot before I came to this and that's how my program file is set up because it's a demo.

```
 public class Program
    {
        private static SomeDbContext context = new SomeDbContext();
        public static async Task Main()
        {
            //using (var context = new SomeDbContext())
            //{
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Add(new Blog());

                context.SaveChanges();
            //}

        }
```

Hoping you can duplicate that and also comprehend why that would be happening! I understand taht this set up is not really a great practice but it's just the setup for my demos and that's what folks are following in my EF Core 5 course.

**Comment by ajcvickers** [comment]
@julielerman How does the context get disposed? (And if it doesn't, then how does the stream get flushed and disposed?)

**Comment by julielerman** [comment]
Ahh I see. The app instance ending isn't enough to trigger DbContext dispose (watched in debug) and the streamwriter isn't getting closed.  So much for demo ware. LOL. Sorry for the time waste. I can at least now explain it to the person who asked me.
