### ISSUE TITLE
Where is CSharpMigrationsGenerator?

### ISSUE THREAD

**Issue by 0-gravity** [dotnet/efcore#23906]
According to documentation CSharpMigrationsGenerator should be in Microsoft.EntityFrameworkCore.Migrations.Design namespace in Microsoft.EntityFrameworkCore.Design package. Decompiling Microsoft.EntityFrameworkCore.Design.dll shows that there is such a namespace and CSharpMigrationsGenerator public class inside of it.
So why I cannot access this class, the code can't even see a namespace?

![image](https://user-images.githubusercontent.com/17303168/104819064-daa8bd00-5833-11eb-99f9-ec84b2c4471b.png)

**Comment by ErikEJ** [comment]
Fix the package reference in your csproj file.
