### ISSUE TITLE
Lifecycle of RelationalTestStore in FunctionalTests

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#23925]
I have found interesting behavior and I don't know whether this was taken into account or if there's a way to get out this problem.

The implementation(s) of `RelationalTestStore` use the `Connection` property to get the connection into the `DbContext`. [Here](https://github.com/dotnet/efcore/blob/v3.1.10/test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestStore.cs#L52) is an example from SQLite. And given the lifecycle of `RelationalTestStore` is longer than one test the same connection will be used for multiple tests. And that might create issues when the connection is left in undefined state. Like for example _Query.AsyncSimpleQueryFbTest.ToListAsync_can_be_canceled_. In my case the cancellation happens as the data is being written/flushed into `NetworkStream` for _fetch_ operation. At that point any further usage of the connection and socket is anybody's guess in what state it is. In my case the tests running after the above mentioned test simply fail, because now there's basically a garbage being sent.

I was trying to get fresh connection for each test, but failed so far. But maybe there's a way I don't see.

Any ideas?

EF Core: 3.1.10

**Comment by ajcvickers** [comment]
@cincuranet I believe it should be possible to cancel an operation on a DbConnection but then continue using that DbConnection. @roji?

**Comment by roji** [comment]
What exactly happens on cancel is provider-dependent, but the reasonable behavior is for cancellation to generate an exception on the reading operation (e.g. ExecuteReader), after which the connection should be in a usable state as @ajcvickers wrote. Of course, there may be various scenarios where the connection could be broken (e.g. network partition), but that shouldn't be the normal case.

In other words, does it make sense to look into making cancellation more robust in your driver, so that users can cancel and then reliably continue using the connection? If not, you may simply want to skip the tests exercising cancellation in EF Core.

**Comment by cincuranet** [comment]
> In other words, does it make sense to look into making cancellation more robust in your driver, so that users can cancel and then reliably continue using the connection? 

This is something that I would like to maybe discuss, because the cancellation can be done on logical level or "physical"/socket level. It's similar dichotomy as with command vs reader cancellation which you've [written about](http://www.roji.org/db-commands-and-cancellation). What repo would be a good place to discuss this?

> If not, you may simply want to skip the tests exercising cancellation in EF Core.

That's what I'm doing right now. But I don't like skipping tests. :)

**Comment by roji** [comment]
I'd be very happy to discuss cancellation with you - as you probably gathered we did a lot of work on that in Npgsql recently.

I don't think it matters much where we discuss this... As this is an ADO.NET issue and possibly specific to your provider, maybe it's best to open an issue on your repro and ping me there - we can bring other people in as necessary.
