### ISSUE TITLE
SqlServer: Allow FreeText and Contains function to take non-string parameters

### ISSUE THREAD

**Issue by alikleitcr7** [dotnet/efcore#23921]
I have the following entity with a property `Content` of type `byte[]`:

```cs
public class Post
{
  [Column(TypeName = "varbinary(max)")]
  [Required]
  public byte[] Content { get; set; }
  
  public string ContentType { get; set; }
}
```

and the content type in model builder:
```
modelBuilder.Entity<Post>()
    .Property(p => p.ContentType)
    .HasComputedColumnSql("'.html'");
```

The Migration:

```cs
migrationBuilder.Sql("CREATE FULLTEXT CATALOG ft_catalog AS DEFAULT", true);
migrationBuilder.Sql(@"CREATE FULLTEXT INDEX ON dbo.Posts([Content] TYPE COLUMN ContentType) KEY INDEX PK_Posts", true);
```

`EF.Functions.FreeText` takes a string `propertyReference` and a string `freeText`.

Here, I passed the Column "Content" as a string I got `The expression passed to the 'propertyReference' parameter of the 'FreeText' method is not a valid reference to a property. The expression should represent a reference to a full-text indexed property on the object referenced in the from clause`.

```cs
IQueryable<DataSets.Post> query = db.Posts;

query = query.Where(k => EF.Functions.FreeText("Content", model.keyword)); 
```

Then, I looked around and found `EF.Property` and used it on `propertyReference` param, Then I got `Failed to convert parameter value from a String to a Byte[]`.
```cs
query = query.Where(k => EF.Functions.FreeText(EF.Property<string>(k, "Content"), model.keyword));
```

The following SQL query works perfectly against the database:

```sql
select ID,Title,Description from Posts where FREETEXT(Content,'wolf')
```
Is there something special for byte[] to be done without having that error?

**Comment by alikleitcr7** [comment]
using (ef core 5.0.1)

**Comment by smitpatel** [comment]
`Content` property is of `byte[]` type. Correct query would be following
`query = query.Where(k => EF.Functions.FreeText(EF.Property<byte[]>(k, "Content"), model.keyword));`

**Comment by alikleitcr7** [comment]
@smitpatel that gives an error `cannot convert byte[] to sting` . FreeText's fist param should be a string

**Comment by smitpatel** [comment]
Seems our function definition is bit too restrictive.

**Comment by smitpatel** [comment]
Acceptable types -  char, varchar, nchar, nvarchar, text, ntext, image, xml, varbinary, or varbinary(max)

**Comment by alikleitcr7** [comment]
Yeah, Is there some kind of workaround for this for the meantime?

**Comment by roji** [comment]
> Acceptable types - char, varchar, nchar, nvarchar, text, ntext, image, xml, varbinary, or varbinary(max)

Also theoretically anything with value converters (I remember we had this discussion at some point).

@alikleitcr7 you should be able to work around this by defining your own method signature and mapping it to FREETEXT as a [user-defined function](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping).

**Comment by alikleitcr7** [comment]
Did the following extension for now:

```
// extension
public static class DbFullTextExtensions
{
    public static bool CustomFreeText(
            byte[] column,
            string keyword)
            => throw new InvalidOperationException($"{nameof(CustomFreeText)} cannot be called client side");
}

// on model creating
modelBuilder
            .HasDbFunction(typeof(DbFullTextExtensions).GetMethod(nameof(DbFullTextExtensions.CustomFreeText)))
            .HasTranslation(args =>
            {
              return new SqlFunctionExpression("FREETEXT", args, nullable: true,
                argumentsPropagateNullability: new[] { false, false }, typeof(bool), null);
            });
```
