### ISSUE TITLE
potentially take ownership of GraphQL.EntityFramework?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/efcore#23922]
regarding this

https://docs.microsoft.com/en-gb/ef/core/what-is-new/ef-core-6.0/plan#graphql

> GraphQL has been gaining traction over the last few years across a variety of platforms. We plan to investigate the space and find ways to improve the experience with .NET. This will involve working with the community on understanding and supporting the existing ecosystem. It may also involve specific investment from Microsoft, either in the form of contributions to existing work or in developing complimentary pieces in the Microsoft stack.

I am the maintainer of https://github.com/SimonCropp/GraphQL.EntityFramework

I would happily transfer the ownership of this project, or parts of it, too the EF core team.

Thoughts?

**Comment by ajcvickers** [comment]
@SimonCropp We will consider it as we work through what we plan to do in the space. I'm closing this for now as there is nothing actionable at this time.

/cc @JeremyLikness
