### ISSUE TITLE
Set discriminator value on child type builder definition

### ISSUE THREAD

**Issue by mythjuha** [dotnet/efcore#23936]
I'm trying to migrate our database layer from Telerik DataAccess to EF Core 5. One of the things i'm struggling with is defining inheritance and especially discriminator values.

The examples found online have this code:
```
modelBuilder.Entity<Blog>()
       .HasDiscriminator<string>("blog_type")
       .HasValue<Blog>("blog_base")
       .HasValue<RssBlog>("blog_rss");
```
What i would like to be able to do is define the discriminator values on the subclass entities, for example:

```
modelBuilder.Entity<Blog>()
        .HasDiscriminator<string>("blog_type")
        .HasDiscriminatorValue("blog_base");

modelBuilder.Entity<RssBlog>()
        .HasDiscriminatorValue("blog_rss");
```

The reason for this is our project is modular and modules are loaded in at runtime. The base project does not yet know about possible subtypes.

Is this possible? Am I missing something?

**Comment by ajcvickers** [comment]
@mythjuha This works for me:

```C#
        modelBuilder.Entity<Blog>()
            .HasDiscriminator<string>("blog_type")
            .HasValue<Blog>("blog_base");
        
        modelBuilder.Entity<RssBlog>()
            .HasDiscriminator<string>("blog_type")
            .HasValue("blog_rss");    }
```

/cc @AndriySvyryd

**Comment by mythjuha** [comment]
Great. A bit 'odd' to need to define the discriminator column twice though, but if it works it works :).
