### ISSUE TITLE
Delete is not cascading in SQLite

### ISSUE THREAD

**Issue by ChristianKern97** [dotnet/efcore#23935]
I have set up Entity Framework in my WPF application and try to use a local SQLite Database. Everything works fine, but after i remove an element from the DbSet and call `SaveChanges()` the associated foreign key entries are not deleted, which creates a lot of oprhand entries in the database.

I made sure, the migration file is using cascade delete for foreign keys and also added `PRAGMA foreign_keys = ON` before each call to the database.

### Include your code

I have already created a stackoverflow question regarding this where i included all the code:
https://stackoverflow.com/questions/65777314/ef-core-sqlite-delete-is-not-cascading

### Include version information

Microsoft.EntityFrameworkCore version: 5.0.2
Microsoft.EntityFrameworkCore.Sqlite version: 5.0.2
Microsoft.EntityFrameworkCore.Proxies version: 5.0.2
Target framework: .NET 5.0
Operating system: Windows 10 Pro, Build 2004

**Comment by ChristianKern97** [comment]
Just to add more code and the complete project:

Migration files: https://github.com/ForkGG/Fork/tree/73eb368/Migrations
DbContext: https://github.com/ForkGG/Fork/blob/73eb368/logic/persistence/PersistenceContext.cs
Class using context: https://github.com/ForkGG/Fork/blob/73eb368/logic/persistence/Persistence.cs

**Comment by ajcvickers** [comment]
@ChristianKern97 As far as I can tell, the code is deleting a dependent/child entity--i.e. the one with the foreign keys. This will not cause the principal/parent entity to be deleted since cascade deletes don't do that. Instead, they delete dependent/child entities when the principal/parent is deleted.

**Comment by ChristianKern97** [comment]
Ok i see, so i got the way this works wrong. 
But if i want to store a list of objects in the database, i create a DbSet<> and that does the trick. If an element of this list now stores the reference to other objects (i.e. Customer stores CustomerInfo in a different object) this is added to the database as a new table and a foreign key in the Customer table.
Now how do i delete the CustomerInfo table entry in EF, if the Customer is deleted (removed from the DbSet)?

**Comment by roji** [comment]
If a CustomerInfo row shouldn't exist without a Customer, then Customer is the principal and CustomerInfo is the dependent. If you configure your model this way, cascade deletes should work properly and deleting a Customer should also cascade-delete its CustomerInfo.

[This page](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key) contains the necessary concepts, [this one specifically on cascade deletes](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete) is also very useful.

**Comment by ChristianKern97** [comment]
Thanks a lot for helping 👍
