### ISSUE TITLE
Migration loop in m:n relation with custom schema

### ISSUE THREAD

**Issue by tomaschabada** [dotnet/efcore#23937]
I have a simple many to many relation defined between the `Course` and `Student` entities

    public class Student
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public List<Course> Courses { get; set; }
    }

    public class Course
    {
        public int CourseId { get; set; }
        public string Name { get; set; }
        public List<Student> Students { get; set; }
    }

I configured both entities to use `my_schema` database schema

     modelBuilder.Entity<Student>()
         .ToTable(nameof(Student), schema: "my_schema");
    
     modelBuilder.Entity<Course>()
         .ToTable(nameof(Course), schema: "my_schema");
After running the generated migration, database tables are generated as expected
[![database diagram][1]][1]

  [1]: https://i.stack.imgur.com/AOUqj.png
Autogenerated join table has the same schema as tables it is related to. And this is causing the poblems.<br/><br/> Each new migration will now include strange (and useless) `RenameTable` operation:

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameTable(
            name: "CourseStudent",
            newName: "CourseStudent",
            newSchema: "my_schema");
    }
    
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameTable(
            name: "CourseStudent",
            schema: "my_schema",
            newName: "CourseStudent");
    }

I am using EntityFramework Core version 5.0.2.<br/><br/>
I see in generated Snapshot migration file that `CourseStudent` entity maps to table without specifying the schema

    modelBuilder.Entity("CourseStudent", b =>
        {
            b.Property<int>("CoursesCourseId")
                .HasColumnType("int");
    
            b.Property<int>("StudentsStudentId")
                .HasColumnType("int");
    
            b.HasKey("CoursesCourseId", "StudentsStudentId");
    
            b.HasIndex("StudentsStudentId");
    
            b.ToTable("CourseStudent");
        });
With this information missing, I suppose, the tool generating new migrations is stuck in a loop where it is changing the schema for join table, but forgetting to note this somewhere (snapshot).

**Comment by tomaschabada** [comment]
> /cc @AndriySvyryd @bricelam We fixed a bug where the join table was not in the same schema as the two other tables, but it looks like the snapshot might not have picked this up.

But the problem occurs when the join table is in the same schema as tables that it joins

**Comment by AndriySvyryd** [comment]
@tomaschabada The workaround is to specify the schema explicitly:
```C#
modelBuilder
    .Entity<Student>()
    .HasMany(l => l.Courses)
    .WithMany(r => r.Students)
    .UsingEntity(a => a.ToTable("CourseStudent", "my_schema"));
```

**Comment by tomaschabada** [comment]
> @tomaschabada The workaround is to specify the schema explicitly:
> 
> ```cs
> modelBuilder
>     .Entity<Student>()
>     .HasMany(l => l.Courses)
>     .WithMany(r => r.Students)
>     .UsingEntity(a => a.ToTable("CourseStudent", "my_schema"));
> ```

I know there are workarounds. We will use one of them till the issue will be fixed
