### ISSUE TITLE
Map model to 2 tables

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#23930]
### What problem are you trying to solve?
We have an entity type, let's call it `ContentTag`. Some are maintained at the system level by staff, and some are maintained at the user level by the users themselves. In order to make it easier to add new system-level `ContentTag`s without taking the app offline, we want to keep the system-level and user-level records separate (so we know what the next `Id` will be for the system-level records).

### Describe the solution you'd like
We want to be able to show the `ContentTag`s in one `<select>`, listed under different `optgroup`s, and it would be practical if they are of the same entity type.

### Possible Workaround
Perhaps a sequence could be used to force the user-level `ContentTag`s to start at say `Id` 200. It could work, but it's not necessarily a good idea.

I'm open to a workaround, but saving the same entity type to multiple tables would be ideal.

**Comment by anranruye** [comment]
what about using a raw sql query?

**Comment by roji** [comment]
One solution that comes to mind, is to use [table-per-type inheritance](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-type-configuration) (TPT): you'd have an abstract ContentTag class with all the properties, and UserContentTag/SystemContentTag, each mapped to its own table (but not adding any properties). When you want to get all the tags, you simply query the abstract ContentTag DbSet, and EF will generate the proper SQL to get rows from both tables.

A simpler solution would be to simply mix system and user tags in the same table, and implement some sort of security scheme to prevent users from manipulating system tags (e.g. by having an IsSystemTag bool property). That's likely to be both simpler and more efficient (no need to query multiple tables). I'm not quite sure what you would need to take the app offline, or why you'd need to know the next Id for system tags.

**Comment by mrlife** [comment]
@anranruye Thanks for the suggestion. I want to keep raw SQL out if possible, but it's a possible solution.

@roji The TPT suggestion sounds like it could work like I had in mind, so thanks for pointing out the key "not adding any properties" part.

For the simpler solution, I'm getting tripped up because I seed the initial system-level `ContentTag`s and worry that a future migration could overwrite the user-level tags if they're in the same table. I haven't been able to test/investigate this yet, but do you know if this is a valid concern?

**Comment by roji** [comment]
If you're concerned about keeping ID spaces distinct between user and system tags, you could simply seed system tags with negative values, and allow user tags to increment as usual on the positive side. This would allow you to distinguish between system and user tags very easily.

**Comment by mrlife** [comment]
@roji I had no idea that negative `Id` values were possible/advisable. Thank you for telling me that. I think that could work out well as long as new system-level tags can be given an explicit Id when created. A couple questions:

1. If a table has auto generated Ids for user-level `ContentTag`s, is it possible to set the Id manually when creating new system-level `ContentTag`s?
2. Migrations to the table would not delete records not in the initial seed data if that seed data changes?

**Comment by roji** [comment]
> I think that could work out well as long as new system-level tags can be given an explicit Id when created

If you're using EF Core's seeding feature, then you must always specify an explicit Id.

> If a table has auto generated Ids for user-level ContentTags, is it possible to set the Id manually when creating new system-level ContentTags?

That depends on your database and how you're generating your IDs. If you're on SQL Server with IDENTITY columns, [see these docs](https://github.com/dotnet/EntityFramework.Docs/pull/2998/files#diff-e1ece2322f12d7192f0c8c9301161da6216316d2494b8bf7f88ba85317725eaeR25).

Migrations generally don't delete anything that isn't tracked by migrations. So if you're using EF Core's seeding feature, as you add and/or remove tags, migrations will add and remove the appropriate rows (this is why IDs must be explicitly given). Otherwise if you've inserted rows via some other means, EF Core won't delete them unless you explicitly tell it to.

**Comment by mrlife** [comment]
@roji Thanks for pointing me to the upcoming docs update. The `IDENTITY_INSERT` is perfect for this. At the same time, if another insert comes along at the same time that uses an auto incremented `Id` field, it seems like there could be an error? I guess the SQL to turn `IDENTITY_INSERT` on/off happens really quickly, so it shouldn't really be an issue.

While I saving an entity to more than one table would be nice, I think you've helped me with a workaround that is at least as good as that.

Thank you!

**Comment by mrlife** [comment]
@roji Thanks for pointing me to the upcoming docs update. The `IDENTITY_INSERT` is perfect for this. At the same time, if another insert comes along at the same time that uses an auto incremented `Id` field, it seems like there could be an error? I guess the SQL to turn `IDENTITY_INSERT` on/off happens really quickly, so it shouldn't really be an issue.

While saving an entity to more than one table would be nice, I think you've helped me with a workaround that is at least as good as that.

Thank you!

**Comment by roji** [comment]
> @roji Thanks for pointing me to the upcoming docs update. The IDENTITY_INSERT is perfect for this. At the same time, if another insert comes along at the same time that uses an auto incremented Id field, it seems like there could be an error? I guess the SQL to turn IDENTITY_INSERT on/off happens really quickly, so it shouldn't really be an issue.

AFAIK there's no issue with using IDENTITY_INSERT while other regular, non-explicit insertions are happening at the same time - all IDENTITY_INSERT does is to allow explicit insertions (which you'd use e.g. for inserting negative values).
