### ISSUE TITLE
Keyless Entity without table

### ISSUE THREAD

**Issue by AR1ES** [dotnet/efcore#23944]
When migrating to ef core 5, I ran into a problem.

I have a lot of query types (keyless entities), which I find through reflection and add to the context:

```C#
foreach(var queryType in LocalQueryTypesCache) {
	var mb = modelBuilder.Entity(queryType);
	mb.HasBaseType((Type)null);
	mb.HasNoKey();
}
```

After startup I this error, while setting context parameter `ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges`.

Error:
```
System.InvalidOperationException: 'Cannot use table 'DepartureLadenProjection' for entity type 'DepartureLadenProjection' since it is being used for entity type 'DepartureLadenProjection' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'DepartureLadenProjection' on the primary key properties and pointing to the primary key on another entity typed mapped to 'DepartureLadenProjection'.'
```

I does not define `ToTable` at modelbuilder.  And I can not (and does not want to) use ToQuerySql() at modelbuilder (it is not awaylable for non-generic `.Entity` method)

EF Core version: 5.0.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Version	10.0.19042 Build 19042
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@AndriySvyryd What is the recommended way to have an entity type not map to any store object?

**Comment by AndriySvyryd** [comment]
`mb.ToTable(null)`

**Comment by AR1ES** [comment]
> `mb.ToTable(null)`

It works.
Why it isn't default?

**Comment by RichardD2** [comment]
`.ToTable(null)` no longer seems to work in EF Core 7.0: attempting to add a migration results in:

> System.ArgumentNullException: Value cannot be null. (Parameter 'name')
>   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
>   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToTable[TEntity](EntityTypeBuilder`1 entityTypeBuilder, String name, String schema, Action`1 buildAction)
>   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToTable[TEntity](EntityTypeBuilder`1 entityTypeBuilder, String name, Action`1 buildAction)

This is for code which works perfectly in EF Core 6.0:

```csharp
modelBuilder.Entity<StringSplitResult>().HasNoKey().ToTable(null, t => t.ExcludeFromMigrations());
```

**Comment by DaveCousineau** [comment]
In EF Core 7 I think you need to cast the null value to disambiguate which overload you're calling.

```
mb.Entity<MyEntity>().HasNoKey().ToTable((string?)null);
```
