### ISSUE TITLE
Run package manager commands on chosen startup project instead of command line chosen project

### ISSUE THREAD

**Issue by mirza-developer** [dotnet/efcore#23957]
I have 4 projects in a solution and one of them is a .net core class library in .net 5 that we want to add models and data working classes there.
A .net 5 web api is our startup project but because of adding our database to the class library, we must run commands like add-migration on this project.
When we run commands, package manager console raises an error that there is no context in your project.
If the class library be chosen as startup project, command runs correctly.
This issue #23853 is similar to mine

**Comment by ajcvickers** [comment]
@mirza-developer Are you choosing the target project in the Package Manager Console?

![image](https://user-images.githubusercontent.com/1430078/106530187-b211fb80-64a0-11eb-8cc2-a95811f8a47e.png)

**Comment by mirza-developer** [comment]
@ajcvickers Target package of console is selected truly

**Comment by mirza-developer** [comment]
Also my repository is available on https://github.com/mirza-developer/SurZor

**Comment by ErikEJ** [comment]
What commands do you run? Give an example.

**Comment by mirza-developer** [comment]
@ErikEJ add-migration AddSurveyFields

**Comment by ajcvickers** [comment]
@mirza-developer With your solution if I set the Api as the startup project and your data library as the Package Manager project, then add-migration works for me:

![image](https://user-images.githubusercontent.com/1430078/106664613-278dd280-655a-11eb-8296-d9e188c62ab8.png)
