### ISSUE TITLE
Inefficient updating of related data

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#23958]
I have Team and User classes

```
    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options)
            : base(options)
        {
        }

        public virtual DbSet<Team> Teams { get; set; }

        public virtual DbSet<User> Users { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Team>(entity =>
            {
                entity.HasMany(x => x.Users).WithOne();
            });
        }
    }

    public class Team 
    {
        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<User> Users { get; set; } = new List<User>();

    }

    public class User
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public double Age { get; set; }
    }
```
I successfully add/remove users to a team using the following code:
```
        public void GetTeams(List<long> updatedUsersList)
        {
            Team dbTeam = (from team in context.Teams.Include(x => x.Users)
                           where team.Id == 2
                           select team).FirstOrDefault();

            User existingUser = (from user in context.Users
                                 where updatedUsersList.Contains(user.Id)
                                 select user).FirstOrDefault();


            dbTeam.Users.Clear();
            dbTeam.Users.Add(existingUser);

            context.SaveChanges();
        }
```
Now I am trying to update users of a team with the following code:

```
 public void GetTeams(List<long> updatedUsersList)
        {
            Team dbTeam = (from team in context.Teams.Include(x => x.Users)
                           where team.Id == 2
                           select team).FirstOrDefault();

            User existingUser = (from user in context.Users
                                 where updatedUsersList.Contains(user.Id)
                                 select new User
                                 {
                                     Id = 1
                                 }).FirstOrDefault();

            dbTeam.Users.Clear();
            dbTeam.Users.Add(existingUser);

            context.SaveChanges();
        }
```
Where I explicitly create a new object using only the Id to increase performance (no need to load all other properties of the User as the relationship between the User and Team is on User Id property). Problem is that EF complains that another instance with the same id is already being tracked ```'The instance of entity type 'User' cannot be tracked because another instance with the key value '{Id: 1}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.'``` 
I want to know why it works that way? I mean I understand that is being tracked because of the Include(x=> x.Users) and when I retrieve the User again it compares the two objects and find it equal and it does not complain (first case) whereas in the second case I only load Id (the two objects are not equal but in terms of relationship equality they are equal -same Id-. Should't the check here being done only by the relationship key and not the entire object?

### Include provider and version information

EF Core version: 5
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019 16.8.2

**Comment by ajcvickers** [comment]
@pantonis See https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution

Improved support for allowing applications to influence identity resolution is something we are looking into.

**Comment by pantonis** [comment]
@ajcvickers Usually when you update related data like the ones I posted above you don't update any of the actual related data (Name, Address etc...) but only the relationship (adding/removing existing users to the team and not adding new users or deleting existing ones into the database).  
The way it works now is that when a disconnected web SPA client (which 90% of new apps are using now) sends the the list of related entity Ids it does not know which are added/removed from the parent entity (in my example existing users that were not removed and newly added users) . When the .net core app receive the updated list it has to check which of the entries are added, which are removed and which remain the intact. Imagine a large enterprise app that has dozens of scenarios like the one posted here that it needs to do this on every entity that has one-to-many or many-to-many relationship(s). And especially when you are using Domain Driven Design where your model is polluted by this infra code.
I mean things could be much simpler if while designing some things, the EF team considers real use cases.
