### ISSUE TITLE
ConventionSet: how to remove ForeignKeyIndexConvention from convention set

### ISSUE THREAD

**Issue by laljikanjareeya** [dotnet/efcore#23961]
My goal is to stop generating indexes while creating foreign key because my database itself is creating index while foreign key has been created.

Here is my Custom Convention SetBuilder
```C#
    public class CustomConventionSetBuilder : RelationalConventionSetBuilder
    {

        public CustomConventionSetBuilder(
            [NotNull] ProviderConventionSetBuilderDependencies dependencies,
            [NotNull] RelationalConventionSetBuilderDependencies relationalDependencies)
            : base(dependencies, relationalDependencies)
        {
        }

        public override ConventionSet CreateConventionSet()
        {
            var conventionSet = base.CreateConventionSet();

            var foreignKeyAddedConvention = conventionSet.ForeignKeyAddedConventions.FirstOrDefault(f => f is ForeignKeyIndexConvention);
            if (foreignKeyAddedConvention != null)
            {
                conventionSet.ForeignKeyAddedConventions.Remove(foreignKeyAddedConvention);
            }

            return conventionSet;
        }
    }
```

Register Builder as below:
```C#
TryAdd<IProviderConventionSetBuilder, CustomConventionSetBuilder>()
```

I have tried Above code but still it's creating indexes. Let me know if any better way available.

Package Version: `Microsoft.EntityFrameworkCore.Relational : 3.1.0`
Thanks!

**Comment by ajcvickers** [comment]
@laljikanjareeya I'm curious which database system you are using where it automatically creates these indexes. Also, does explicitly specifying the indexes cause an error?

**Comment by AndriySvyryd** [comment]
@laljikanjareeya Until #214 is implemented you need to remove `ForeignKeyIndexConvention` from every convention type collection it is registered in: `ForeignKeyAddedConventions, ForeignKeyRemovedConventions, EntityTypeBaseTypeChangedConventions, KeyAddedConventions, KeyRemovedConventions, ForeignKeyPropertiesChangedConventions, ForeignKeyUniquenessChangedConventions, IndexAddedConventions, IndexRemovedConventions, IndexUniquenessChangedConventions, ModelFinalizingConventions`

**Comment by laljikanjareeya** [comment]
> @laljikanjareeya I'm curious which database system you are using where it automatically creates these indexes. Also, does explicitly specifying the indexes cause an error?

@ajcvickers Thanks for quick Respond. It's [Google Cloud Spanner](https://cloud.google.com/spanner) Database. while specify explicitly index it's creating two index one is from Generated script and other one is from Spanner.

**Comment by laljikanjareeya** [comment]
> @laljikanjareeya Until #214 is implemented you need to remove `ForeignKeyIndexConvention` from every convention type collection it is registered in: `ForeignKeyAddedConventions, ForeignKeyRemovedConventions, EntityTypeBaseTypeChangedConventions, KeyAddedConventions, KeyRemovedConventions, ForeignKeyPropertiesChangedConventions, ForeignKeyUniquenessChangedConventions, IndexAddedConventions, IndexRemovedConventions, IndexUniquenessChangedConventions, ModelFinalizingConventions`

I will try this one Thanks 👍

**Comment by roji** [comment]
@laljikanjareeya are you using [this provider](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.EntityFrameworkCore.Spanner/index.html)? If you're a maintainer, this change should probably be done inside the provider itself.

**Comment by laljikanjareeya** [comment]
Thanks @ajcvickers @roji and @AndriySvyryd for the support it's been working as expected after removing `ForeignKeyIndexConvention` from above mention Conventions.
