### ISSUE TITLE
An exception of type 'The skip navigation is not a collection' is thrown for a property implementing ICollection

### ISSUE THREAD

**Issue by mouaddjedidi** [dotnet/efcore#23960]
I have a many-to-many relationship:

```C#
public class User : Entity<User>
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public ICollection<Role> Roles { get; set; }
}

public class Role : Entity<Role>
{
    public string Code { get; set; }
    public string Label { get; set; }

    public ICollection<User> Users { get; set; }
}
```
The many-to-many relationnship is configured as followed (on User):

```C#
builder.HasMany(u => u.Roles)
   .WithMany(r => r.Users)
   .UsingEntity<UserRole>(
       c => c.HasOne(c => c.Role).WithMany().HasForeignKey(c => c.RoleId),
       c => c.HasOne(c => c.User).WithMany().HasForeignKey(c => c.UserId))
   .HasKey(c => new { c.UserId, c.RoleId });
```

This configuration works. However, ```Entity<T>``` implements ```IList<T> ```. In other words, Un object of type User can behave like a collection of type User. If I remove the explicit implementation of ICollection on both skip navigation properties:

```C#
public class User : Entity<User>
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public Role Roles { get; set; }
}

public class Role : Entity<Role>
{
    public string Code { get; set; }
    public string Label { get; set; }

    public User Users { get; set; }
}
```

The solution builds with the same many-to-many configuration which recognizes both navigation properties being enumerable. However, when I try to access the database, I get a runtime exception: ```System.InvalidOperationException : The skip navigation 'User.Roles' is not a collection. Only collection skip navigation properties are currently supported```.

### Provider and version information

EF Core version: 5.0.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@mouaddjedidi How do you make use of those navigation properties? For example, If a user is related to many roles, then which of those roles is sued for the navigation property? Is it the same as one of the entities contained in the navigation property? Is it a different entity instance that is not being used as an entity in the model? Or is it something different?

For triage; full repro code:

```C#
public class Entity<TEntity> : List<TEntity>
{
    public int Id { get; set; }
}

public class User : Entity<User>
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public Role Roles { get; set; }
}

public class Role : Entity<Role>
{
    public string Code { get; set; }
    public string Label { get; set; }

    public User Users { get; set; }
}

public class UserRole
{
    public int UserId { get; set; }
    public int RoleId { get; set; }
    public User User { get; set; }
    public Role Role { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Role {Users = new User {new User()}});
            context.SaveChanges();
        }
    }
}

public class SomeDbContext : DbContext
{
    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .UseLoggerFactory(ContextLoggerFactory)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>().HasMany(u => u.Roles)
            .WithMany(r => r.Users)
            .UsingEntity<UserRole>(
                c => c.HasOne(c => c.Role).WithMany().HasForeignKey(c => c.RoleId),
                c => c.HasOne(c => c.User).WithMany().HasForeignKey(c => c.UserId))
            .HasKey(c => new {c.UserId, c.RoleId});
    }
}
```

**Comment by mouaddjedidi** [comment]
@ajcvickers Each entity is an object that can behave like a collection. For instance, `User user1 = new User()` is an object that behaves like an empty collection. If i do the following `User user2 = new User(); user1.Add(user2);` then user1 is an object that behave like a collection of 1 element (`user1.Count()` is equal to 1 and `user1[0]` return user2 ).

Now if my user record on the database is related to two roles, say role1 and role2. I expect the Roles property of the corresponding `User` entity (lets call it user1) to be an object behaving like a collection of two elements (the 2 related roles) with `user1.Roles.Count()` equal to 2 and `user1.Roles[0]` returning the first role and so on. Now each role of these two roles is itself an object of type `Role` that behaves like a collection of 0 elements as it has no child roles.  If the user has no roles, its `Roles` property may be null or an instance of Role with no elements (the equivalent of `user.Roles = new Role()`). Personnally I would love the second option in order to avoid null reference exceptions.

**Comment by ajcvickers** [comment]
@mouaddjedidi This isn't a pattern supported by EF Core. It may be possible once #752 is implemented.
