### ISSUE TITLE
Tables created using OwnsMany are not pluralised

### ISSUE THREAD

**Issue by richardthombs** [dotnet/efcore#23964]
Using EF Core 5.0.2:

I would expect the following code-first design to produce a table called `Tags` instead the table is named `Tag`. I am aware I can override table name manually, but think that the default name should be pluralised, or that it should come from the property name.

```c#
public class User
{
  public Guid UserID { get; set; }
  public string Username { get; set; }
  public List<Tag> Tags { get; set; }
}

public class Tag
{
  public string Value { get; set; }
}

public class Context : DbContext
{
  public DbSet<User> Users { get; set; }
  
  public Context(DbContextOptions<Context> options) : base(options)
  {
  }

  protected override void OnModelCreating(ModelBuilder builder)
  {
    builder.Entity<User>().OwnsMany(x => x.Tags);
  }
}
```

**Comment by ajcvickers** [comment]
@richardthombs EF Core never pluralizes at runtime, since doing so means that any bug fix in the pluralizer can be a breaking change for existing applications. Using the navigation name is an interesting idea, but I don't think we can change this now since it would be a big breaking change.

**Comment by richardthombs** [comment]
Those are very good reasons not to change it. Thanks for the quick response!
