### ISSUE TITLE
Unexpected extra colum generated when mapping multiple entities to same column for a table per hierarchy

### ISSUE THREAD

**Issue by triplebeta** [dotnet/efcore#23977]
In my sample I defined a parent entity and 3 subclasses. They should all be mapped to the same table in TPH fashion.
All 3 subclasses have an identical required string property AdoProjectName are all mapped to the same table column.
In the future there will be additional subclasses that will not have that same column.

Each EntityTypeConfiguration defines:
```C#
builder.Property(x => x.AdoProjectName).HasMaxLength(200).HasColumnName("AdoProjectName");
```

This generates the following code:
```C#
            migrationBuilder.CreateTable(
                name: "ComponentParts",
                columns: table => new
                {
                    PartId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PartType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    AdoProjectName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    AdoReleasePipeline_AdoProjectName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ...
                    ...
                },
```

This contains the expected column (AdoProjectName) but also an unexpected additional column: AdoReleasePipeline_AdoProjectName 
This columnname is a concatenation of the name of one of the entities and the expected columnname.

### Snapshot is different
The snapshot of the model is similar for 2 of the subtypes but different for the 3rd, while the subclasses and their configuration are identical except for 1 fieldname. They differ for the AdoProjectName field.

For 2 of the entities, the model is like this:
```C#
            modelBuilder.Entity("Infra.Data.AzureDevops.AdoReleasePipeline", b =>
                {
                    b.HasBaseType("Infra.Data.ComponentPart");

                    b.Property<string>("AdoProjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdoReleasePipeline_AdoProjectName");

                    b.Property<string>("AdoReleaseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("adorelease");
                });
```
For the 3rd subclass, the model looks like this:
```C#
            modelBuilder.Entity("Infra.Data.AzureDevops.AdoRepository", b =>
                {
                    b.HasBaseType("Infra.Data.ComponentPart");

                    b.Property<string>("AdoProjectName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AdoProjectName");

                    b.Property<string>("AdoRepositoryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("adorepository");
                });
```

My hypothesis is that for some reason the model does not detect the HasMaxLength for that specific subclass and therefore cannot map it to the same column - and even though I asked EF to map it to that column, it silently just generates a different column without telling.

### Tiny sample solution that reproduces the problem
[TPH-EFCoreIssue.zip](https://github.com/dotnet/efcore/files/5872880/TPH-EFCoreIssue.zip)

### Include provider and version information

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET 5.0
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@triplebeta In the repro code the configuration for `AdoReleasePipeline` is not being used:

```C#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {            
            // Add table-per-hierarchy for ComponentParts
            modelBuilder.ApplyConfiguration(new ComponentPartsConfiguration());
            modelBuilder.ApplyConfiguration(new AdoBuildPipelineConfiguration());
            modelBuilder.ApplyConfiguration(new AdoRepositoryConfiguration());
        }
```

If I add it, then the additional column is not created as expected.
