### ISSUE TITLE
Preserve synchronization context in SaveChangesAsync for accepting changes

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#23971]
Since #10164, we have `ConfigureAwait(false)` everywhere; this can cause issues in certain data binding scenarios, when accepting changes triggers a UI change, which is no longer executed on the UI thread (e.g. #22841).

We could specifically use `ConfigureAwait(true)` in the code path leading to AcceptAllChanges (specifically in two places: DbContext.SaveChangesAsync, StateManager.SaveChangesAsync).

**Comment by ajcvickers** [comment]
Looks like this didn't make it into the preview 1 branch. It was merged after preview 1 branched, but before branding was updated to preview 2.
