### ISSUE TITLE
MigrationBuilder generates wrong foreign key target

### ISSUE THREAD

**Issue by FutureMUD** [dotnet/efcore#23989]
I'm using Entity Framework Core 5.0.1 in a project and I'm having an issue with a generated migration. The project targets a MySQL database and I'm using the Pomelo connector, in case that's relevant.

The core issue is that I had to change the primary key of a joining table which mistakenly only used one of its foreign key properties as the primary key (legacy databases...). 

When generating the SQL to recreate this primary key the migration builder is emitting statements to drop and recreate the foreign keys, but the recreation statement for the foreign key uses the origin table's column name instead of the target table's column name.

Here's the relevant portion of the emitted SQL:

```
ALTER TABLE `EnforcementAuthorities_ArrestableClasses` DROP FOREIGN KEY `FK_EnforcementAuthorities_ArrestableClasses_Enforce`;

ALTER TABLE `EnforcementAuthorities_ArrestableClasses` DROP FOREIGN KEY `FK_EnforcementAuthorities_ArrestableClasses_LegalClasses`;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'EnforcementAuthorities_ArrestableClasses');
ALTER TABLE `EnforcementAuthorities_ArrestableClasses` DROP PRIMARY KEY;

ALTER TABLE `EnforcementAuthorities_ArrestableClasses` ADD CONSTRAINT `FK_EnforcementAuthorities_ArrestableClasses_Enforce` FOREIGN KEY (`EnforcementAuthorityId`) REFERENCES `EnforcementAuthorities` (`EnforcementAuthorityId`) ON DELETE CASCADE;

ALTER TABLE `EnforcementAuthorities_ArrestableClasses` ADD CONSTRAINT `FK_EnforcementAuthorities_ArrestableClasses_LegalClasses` FOREIGN KEY (`LegalClassId`) REFERENCES `LegalClasses` (`LegalClassId`) ON DELETE CASCADE;

ALTER TABLE `EnforcementAuthorities_ArrestableClasses` ADD CONSTRAINT PRIMARY KEY (`EnforcementAuthorityId`, `LegalClassId`);
```

In the case of those two foreign keys the referenced property should be simply `Id` on those entities.

Here's the migration's "up" statement:

```
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PRIMARY",
                table: "EnforcementAuthorities_ArrestableClasses");
            
            migrationBuilder.AddPrimaryKey(
                name: "PRIMARY",
                table: "EnforcementAuthorities_ArrestableClasses",
                columns: new[] { "EnforcementAuthorityId", "LegalClassId" });
        }
```

**Comment by FutureMUD** [comment]
I made a mini-program to demonstrate the problem and was able to reproduce it. Notice the output in the text file, which is what is produced when I run the following Package Manager Console command:

Script-Migration InitialDatabase UpdateDatabase

[EFBugDemo.zip](https://github.com/dotnet/efcore/files/5877542/EFBugDemo.zip)

**Comment by lauxjpn** [comment]
@FutureMUD If this is still an issue for you, please cross-post this issue on our [Pomelo repository](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql), so we will take a look at it.

Thanks!
