### ISSUE TITLE
Help: EF Update Many-to-Many in Detached Scenario

### ISSUE THREAD

**Issue by oswaldofreitas** [dotnet/efcore#2398]
Please guys, I need your help.

In all my devs using EF, I get lost when working with related entities in a detached scenario. Could you help me write a method to update parent and children? See http://stackoverflow.com/questions/30872850/ef-update-many-to-many-in-detached-scenario

Are there any tutorials to help me with a little EF advanced scenarios?

Thank you very much

**Comment by rowanmiller** [comment]
Following up on the StackOverflow thread.

**Comment by oswaldomilet** [comment]
Thanks
