### ISSUE TITLE
Strange DB-First Scaffold Naming

### ISSUE THREAD

**Issue by cgountanis** [dotnet/efcore#23982]
It is really bothering me that it is renaming the Form to Task when you can clearly see the type is ofType "Form", which is a table name. I know the DB is a bit complicated but it is a simple join really.

![csproj](https://user-images.githubusercontent.com/14899817/105887577-86d76a00-5fd1-11eb-9689-31f4903fb57e.png)

![a](https://user-images.githubusercontent.com/14899817/105888003-05340c00-5fd2-11eb-8d03-7580e64d4909.png)

```
Scaffold-DbContext "Server=localhost;Database=XXXX;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Context Context -ContextDir Models -Force
```

**The scaffold improperly names the property.**
public partial class FormPercent
![b](https://user-images.githubusercontent.com/14899817/105888135-36144100-5fd2-11eb-9acb-3a553566916f.png)

Results?
Results would be FormPercent.Task.Task.[FIELDNAME], when it obviously should be FormPercent.Form.Task.[FIELDNAME].

**Comment by ErikEJ** [comment]
What is the Actual table name?
Is it "Form (task)" ??

**Comment by cgountanis** [comment]
> What is the Actual table name?
> Is it "Form (task)" ??

Form, the (XXXX) is the schema. Just how SSMS diagrams displays that. I know, adds to the confusion but even if everything was under the DBO schema it would react the same.

**Comment by ErikEJ** [comment]
Please share the CREATE TABLE statements for the three tables involved, and I will have a look.

**Comment by cgountanis** [comment]
@ErikEJ 

Ok, I dumbed it down so the creation was simple. Same results on public partial class FormPercent: `public virtual Form Task { get; set; }`.

Strange Right?
![2021-01-26 13_16_02-SAEF - Microsoft Visual Studio](https://user-images.githubusercontent.com/14899817/105893431-b0e05a80-5fd8-11eb-8abc-9139c0a7957d.png)

![2021-01-26 13_12_23-SAEF - Microsoft Visual Studio](https://user-images.githubusercontent.com/14899817/105893012-2b5caa80-5fd8-11eb-9b0c-e1df063d6354.png)

![simple](https://user-images.githubusercontent.com/14899817/105892610-b4bfad00-5fd7-11eb-9e28-c4a2a03639d2.png)

```
USE [TEST1]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- [Task]
CREATE TABLE [dbo].[Task](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FilingId] [int] NOT NULL,
	[TaskTypeId] [int] NOT NULL,
	[TaskStatusId] [tinyint] NOT NULL,
	[DateDue] [date] NULL,
	[SubmittedBy] [varchar](50) NULL,
	[SubmittedDate] [datetime2](7) NULL,
	[ReviewedBy] [varchar](50) NULL,
	[ReviewedDate] [datetime2](7) NULL,
	[CreatedBy] [varchar](50) NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedBy] [varchar](50) NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[DeletedBy] [varchar](50) NULL,
	[DeletedDate] [datetime2](7) NULL,
	[TaskComment] [varchar](255) NULL,
 CONSTRAINT [PK_Task] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- [Form]
CREATE TABLE [dbo].[Form](
	[TaskId] [int] NOT NULL,
	[PropertyValue] [int] NOT NULL,
	[CreatedBy] [varchar](50) NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedBy] [varchar](50) NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[DeletedBy] [varchar](50) NULL,
	[DeletedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Form] PRIMARY KEY CLUSTERED 
(
	[TaskId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Form]  WITH CHECK ADD  CONSTRAINT [FK_Form_Task] FOREIGN KEY([TaskId])
REFERENCES [dbo].[Task] ([Id])
GO

ALTER TABLE [dbo].[Form] CHECK CONSTRAINT [FK_Form_Task]
GO

-- [FormPercent]
CREATE TABLE [dbo].[FormPercent](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TaskId] [int] NOT NULL,
	[JurisdictionFIPS] [varchar](5) NOT NULL,
	[TaxDistrictId] [smallint] NOT NULL,
	[FormStatusId] [tinyint] NOT NULL,
	[GradeId] [tinyint] NOT NULL,
	[TaxYear] [smallint] NOT NULL,
	[GrossSellingPrice] [int] NULL,
	[Expenditure] [int] NULL,
	[CreatedBy] [varchar](50) NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedBy] [varchar](50) NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[DeletedBy] [varchar](50) NULL,
	[DeletedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_FormPercent] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FormPercent]  WITH CHECK ADD  CONSTRAINT [FK_FormPercent_Form] FOREIGN KEY([TaskId])
REFERENCES [dbo].[Form] ([TaskId])
GO

ALTER TABLE [dbo].[FormPercent] CHECK CONSTRAINT [FK_FormPercent_Form]
GO
```

```
Scaffold-DbContext "Server=localhost;Database=TEST1;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Context Context -ContextDir Models -Force
```

**Comment by smitpatel** [comment]
Since FK property is `TaskId` that is giving name to navigation as `Task`

**Comment by cgountanis** [comment]
I mean it's just a 1 to 1, should it not still call the object "Form" So you can go X.Y.Z not X.Z.Z as far as names go? Kinda wrenches the situation a bit. We can add a IDENTITY = Yes, ID on Form and just normally FK on the sub columns but that would add to some indexing overhead as far as our DB is concerned.

**Comment by smitpatel** [comment]
EF Core by convention try to match up certain name for foreign key based on navigation name and principal entity type name. See https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#fully-defined-relationships when inferring name from code model. Scaffolding tries to do the similar in reverse. Hence looking at your fk or `TaskId` name, it makes the name of navigation as `Task`. The type of navigation everything is correct since it will point to entity type of principal/dependent table.
At the end of day scaffolding uses heuristic to arrive at most suitable code model from your database model. It may not always be upto user liking or intention. As you asserted already, db is bit complicated so the what scaffolding generated is also confusing to look at it. Feel free to edit the generated code and change it to whatever you like.

**Comment by cgountanis** [comment]
So I can tweak the FK name and fix all this pretty easy?

**Comment by ErikEJ** [comment]
If you tweak with the standard tooling, you must tweak every time. Latest daily release of EF Core Power Tools allows you to configure renaming of navigations.

**Comment by cgountanis** [comment]
I will take a look. Thanks guys!

**Comment by cgountanis** [comment]
I was just hoping this was not something new caused by the associated data table logics put in place around NET5.

What would be the easiest way to handle this with OnModelCreating modelBuilder. Not able to brute force the right combination here.

**Comment by cgountanis** [comment]
@ErikEJ Can you lead me to some direct docs on what would be used to fix this team wide? Otherwise we are just going to ignore for now. Not seeing an easy solution without dropping the 1 to 1 which works nicely actually.

**Comment by cgountanis** [comment]
@smitpatel Anything can be done using OnModelCreatingPartial, not getting the jist, do not think I can since the models have to be created and it already sees the bad name. Recommendations other than keeping a list of re-codes per scaffold?

**Comment by ErikEJ** [comment]
What does "team wide" mean? And are you asking about Power Tools??

**Comment by cgountanis** [comment]
Yes

**Comment by ErikEJ** [comment]
@cgountanis The Power Tools configuration is stored in an file, that you can have under source control, and share between team members, yes.

**Comment by ErikEJ** [comment]
@cgountanis The navigation renaming feature is currently in preview, more information here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Comment by ajcvickers** [comment]
Note from triage: this kind of customization is covered by #4038.
