### ISSUE TITLE
Cannot apply transformations to scaffolded annotations

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#23980]
EFCore.PG supports index-included properties in scaffolding (which SQL Server doesn't). Unfortunately, the scaffolded annotation coming from the DatabaseModelFactory is for column names rather than model properties, and since we apply name transformations to properties the annotations must be transformed as well.

This could mean making RelationalScaffoldingModelFactory public and letting providers do what they want. Or some other sort of hook for applying transformations to annotations as they're brought over from the database model to the model (though here we'd need to know how the specific column's name was previously rewritten into the property name...).

Originally raised by @yyjdelete in https://github.com/npgsql/efcore.pg/issues/1605

/cc @bricelam

**Comment by smitpatel** [comment]
Related #22150

**Comment by roji** [comment]
Thanks @smitpatel, I don't think there's anything here beyond what's already in #22150, closing as a dup.

**Comment by roji** [comment]
Duplicate of #22150

**Comment by roji** [comment]
Note: I may still fix this on the Npgsql side by extending RelationalScaffoldingModelFactory (which is internal) until a more proper solution is done in #22150.
