### ISSUE TITLE
Question: Can reusing lambda expression help to improve performance?

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#23992]
Entity:
```C#
    public class Book
    {
        public int Id { get; set; }

        public string BookName { get; set; }

        public string Type { get; set; }
    }
```
Query1:
```C#
    var db = new MyDbContext();
    var books1 = db.Set<Book>().Where(x => x.Type == "science").Select(x => new
    {
        x.Id,
        x.BookName
    }).ToList();
    var books2 = db.Set<Book>().Where(x => x.Type == "fiction").Select(x => new
    {
        x.Id,
        x.BookName
    }).ToList();
```
Query2:
```C#
    var projectionExpression = ExpressionBuilder.Build((Book x) => new
    {
        x.Id,
        x.BookName
    });
    var db = new MyDbContext();
    var books1 = db.Set<Book>().Where(x => x.Type == "science").Select(projectionExpression).ToList();
    var books2 = db.Set<Book>().Where(x => x.Type == "fiction").Select(projectionExpression).ToList();
```
ExpressionBuilder helper class:
```C#
    public static class ExpressionBuilder
    {
        public static Expression<Func<TSource, TResult>> Build<TSource, TResult>(Expression<Func<TSource, TResult>> expression) => expression;
    }
```
Does Query2 has better performance than Query1, or the two queries are same?

**Comment by roji** [comment]
The two queries should be roughly the same. In both cases EF Core receives a full expression tree (as always), and must process it in the same way. The fact that two nodes in the two different expression trees (the selectors) happen to point to the same instance shouldn't matter.

However, it's best to simply code up a quick BenchmarkDotNet benchmark to actually see how the two variants run.

**Comment by roji** [comment]
BTW: you probably want to read [this section of the perf docs](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#query-caching-and-parameterization), it's provides some clarity on this.
