### ISSUE TITLE
The type cannot be configured as non-owned because an owned entity type with the same name already exists.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#23995]
Tested up until 5.0.2 this causes an exception when creating a migration:

    public class Parent
    {
        public long Id { get; set; }

        public ICollection<Child> Children { get; set; }
    }

    [Owned]
    public class Child
    {
        public Parent Parent { get; set; }
    }

In my DbContext:

    public DbSet<Parent> Parents { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Parent>().OwnsMany(x => x.Children).WithOwner(x => x.Parent);

        modelBuilder.Entity(typeof(Child).Name).Metadata.GetSchema(); // <--- this works because of the .Name
        modelBuilder.Entity(typeof(Child)).Metadata.GetSchema(); // <--- this causes the exception???
    }

Then commenting out the line that causes the exception and generating the migration causes the exception: _The entity type 'Child' is in shadow state. A valid model requires all entity types to have corresponding CLR type._
Commenting out both GetSchema lines creates a correct migration.

This reproduction seems kind of pointless because the only thing I try is reading the schema name. Not changing it otherwise using it but the issues I have in larger setup has the same errors and I think I this is a minimalistic repro of it.

**Comment by anranruye** [comment]
> By-design restrictions
> You cannot create a DbSet<T> for an owned type.
> You cannot call Entity<T>() with an owned type on ModelBuilder.
> Instances of owned entity types cannot be shared by multiple owners (this is a well-known scenario for value objects that cannot be implemented using owned entity types).

see https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities, this is a by design limitations.
