### ISSUE TITLE
Solution with main project with no dependency to migrations project

### ISSUE THREAD

**Issue by CesarD** [dotnet/efcore#24008]
I have a solution with, let's say, 4 projects:

- `Solution1.API`
  - My main app
  - Dependent from all others
- `Solution1.Domain`
  - Where the domain POCO classes are defined with their domain logic
  - Totally independent.
- `Solution1.Infrastructure`
  - Where the entity type configurations are placed, `DbContext` is extended, etc.
  - Dependent from `Solution1.Domain`.
- `Solution1.Infrastructure.Migrations`
  - Only for the generated migrations, to keep them separated from all the rest.
  - Dependent from `Solution1.Infrastructure`

Right now, I have to create a dependency from `API` to `Migrations` in order to build and create new migrations. When I add new migrations, I have to indicate which is the startup project: `dotnet ef migrations add NewMigration -s ..\Solution1.API` in order for the dotnet-ef tool can acquire the connection string and do its stuff.
What I would like to do, is to completely separate `API` from `Migrations`, in the way that `API` wouldn't be dependent from `Migrations` anymore. I think it doesn't make sense to carry such extra assembly to a Production environment where we are not running migrations at any time at all. 
What I can't figure out yet, is how to make it. Any hint as to what would be the best way to achieve this? Should I need to setup all the `DbContext` dependency configuration in `Solution1.Infrastructure.Migrations` as well? 

I'm running the solution on .NET 5 with EF Core 5.0.2.

Thanks!

**Comment by AndriySvyryd** [comment]
@bricelam

**Comment by bricelam** [comment]
It's [poorly written](https://github.com/dotnet/EntityFramework.Docs/issues/933), but have you seen [Using a Separate Migrations Project](https://docs.microsoft.com/ef/core/managing-schemas/migrations/projects) in the docs?

I suggest continuing to use `API` as the startup project. You should be able to avoid publishing EFCore.Design and `Migrations` with your app using the steps shown in the article.

Let me know you you need any specific guidance.
