### ISSUE TITLE
Updated boilerplate for EntityFramework 7+Identity

### ISSUE THREAD

**Issue by emisaacson** [dotnet/efcore#2400]
Visual Studio 2015 RC has a template for a vNext website (beta4) with a lot of Entity Framework and AspNet Identity functionality built in. I've been staying up to date with the nightly builds and my project still compiles but the EF+Identity portion no longer executes, there are various runtime errors. Is the boilerplate for migration and EF/Identity context updated somewhere? I cannot find a repository that has an updated template.

**Comment by divega** [comment]
We are planning to make the code for the VS templates publically available on GitHub, but it isn't there yet. 

In the meanwhile are there specific parts that don't compile and you haven't been able to figure out how to change?

cc @rustd

**Comment by emisaacson** [comment]
I think with the beta6 equivalent of the few lines below I'd be off and running. I can make changes to get them to compile but I'm definitely not configuring the relationships properly and it results in runtime errors. Thank you!

From Migrations\00000000000000_CreateIdentitySchema.cs:
```c#
            builder.Entity("Microsoft.AspNet.Identity.EntityFramework.IdentityRoleClaim`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", b =>
            {
                b.ForeignKey("Microsoft.AspNet.Identity.EntityFramework.IdentityRole", "RoleId");
            });

            builder.Entity("Microsoft.AspNet.Identity.EntityFramework.IdentityUserClaim`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", b =>
            {
                b.ForeignKey("WebApplication2.Models.ApplicationUser", "UserId");
            });

            builder.Entity("Microsoft.AspNet.Identity.EntityFramework.IdentityUserLogin`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", b =>
            {
                b.ForeignKey("WebApplication2.Models.ApplicationUser", "UserId");
            });

            builder.Entity("Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", b =>
            {
                b.ForeignKey("Microsoft.AspNet.Identity.EntityFramework.IdentityRole", "RoleId");
                b.ForeignKey("WebApplication2.Models.ApplicationUser", "UserId");
            });
```

**Comment by bricelam** [comment]
@emisaacson You could delete that file and run `dnx . ef migration add CreateIdentitySchema` to re-scaffold it.

**Comment by emisaacson** [comment]
@bricelam works great. thank you for setting me straight i clearly did not understand this part of the workflow.
