### ISSUE TITLE
Pass DbContextOptions to DbContextFactory

### ISSUE THREAD

**Issue by jfraschilla** [dotnet/efcore#24010]
Is it possible to make DbContextFactory have a method that takes a DbContextOptions parameter?  I am using efcore sqlite and would like to inject a factory into my ViewModel such that I can change the sqlite file that is being used.

```
// In DbContextFactory have a method
public virtual TContext CreateDbContext(DbContextOptions<TContext> options)
         => _factory(_serviceProvider, options);
```

In MyController I would like to do something like the following:
```
public class MyController
{
    private readonly EfCoreContextFactory.IDbContextFactory<BloggingContext> _contextFactory;
    private int _count = 0;

    public MyController(IDbContextFactory<BloggingContext> contextFactory)
    {
        _contextFactory = contextFactory;
    }

    public void DoSomething()
    {
        _count++;
        string filename = $"blog{_count}.db";
        var options = new DbContextOptionsBuilder<BloggingContext>().UseSqlite(@"Data Source={filename}").Options;

        using (var context = _contextFactory.CreateDbContext(options));
        {

        }
    }
}
```

Is there another way to achieve this that I should be looking at?

### Include provider and version information

EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: (e.g. .NET 5.0)
Operating system: Windows
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
@jfraschilla What value is the factory providing here?

**Comment by jfraschilla** [comment]
Are you asking the purpose of using a factory in this simple example?  This example was only to test the use of generating a DbContext using the DbContextFactory.  I am trying to figure out how to use efcore sqlite provider in a WPF document style application similar to Microsoft PowerPoint where each shell (i.e. Window) is associated with a different file.  The application does not use a single sqlite database file for its entire scope.  The user can switch files when they want by using the File menu.  I do not know if this answers you question.

**Comment by ajcvickers** [comment]
@jfraschilla The purpose of the IDbContextFactory implementations shipped with EF Core are to allow the DbContextOptions to be injected from the D.I. container. Feel free to create any other kind of factory that you feel is helpful for your application.

**Comment by jfraschilla** [comment]
@ajcvickers, I have seen some individual recommend the use of IDesignTimeDbContextFactory which has a CreateDbContext(string [] args) method.  I would have to register this with the container instead for the built in DbContextFactory.  This will serve two purposes since I would also need it for migrations.  What are you thoughts on using this?

It would be nice if during a EF Community Standup you would discuss sqlite and dbcontext factories and their use in WPF applications as well as ASP Core.  Including examples of using the db.Database.Migrate() command with the IDesignTimeDbContextFactory.  The docs on the use of CreateDbContext(string [] args) and how one would make use of the args is still unclear to me.  However, I got it to work for my case.

Thanks
John

**Comment by ajcvickers** [comment]
@jfraschilla `IDesignTimeDbContextFactory` is designed specifically for discovery by tools at design-time. It should not be used for other purposes. However, as I said, feel free to create your own factory interface if you need it.

I would not use a factory in a WPF application. I would just create an instance of my context with `new`. I would only use the built-in `IDbContextFactory` if I were using D.I., which I likely wouldn't use in WPF. If I were going to use it in WPF, then I would resolve the options from the D.I. container, since that's what it would be there for.
