### ISSUE TITLE
Move EnableNullabilityCheck from DbContextOptionsBuilder to InMemoryDbContextOptionsBuilder

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#24013]
See #10613

Currently `EnableNullabilityCheck` is called on the top-level options builder:

```C#
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseInMemoryDatabase(Your.ConnectionString)
            .EnableNullabilityCheck(false);
```

It should instead be on the nested lambda for in-memory configuration:

```C#
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseInMemoryDatabase(Your.ConnectionString, b => b.EnableNullabilityCheck(false));
```

**Comment by fagnercarvalho** [comment]
Since I did this I can work on this one if that is okay.

**Comment by ajcvickers** [comment]
@fagnercarvalho Thanks, that would be great!

**Comment by fagnercarvalho** [comment]
Sorry @ajcvickers, I didn't have the bandwidth to work on this, I will communicate this next time to avoid this kind of delay, thank you!

**Comment by ajcvickers** [comment]
@fagnercarvalho No problem; it was a trivial change to make.
