### ISSUE TITLE
Wrong advice when Save points for Multiple Active Result Sets (MARS) 

### ISSUE THREAD

**Issue by vincent1405** [dotnet/efcore#24019]
Hi,

I am using Entity Framework Core in a console app written with .Net Core 3.1.
When I run my program with logging enabled on my context, I have the following message:

> Microsoft.EntityFrameworkCore.Database.Transaction[30004]
      Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled. If 'SaveChanges' fails, then the transaction cannot be automatically rolled back to a known clean state. Instead, the transaction should be rolled back by the application before retrying 'SaveChanges'. See https://go.microsoft.com/fwlink/?linkid=2149338 for more information. To identify the code which triggers this warning, call 'ConfigureWarnings(w => w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS))'

But when I try to modify my OnConfiguring method to configure the warning as adviced, I cannot find the SavepointsDisabledBecauseOfMARS member of the RelationalEventId class:
`            
optionsBuilder
                .UseLoggerFactory(loggerFactory)
                .EnableSensitiveDataLogging()
                .ConfigureWarnings(w => w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS));
`

I think the SavepointsDisabledBecauseOfMARS is a member of the SqlServerEventId class.

**Comment by Jonesie** [comment]
Also in .net 5.
