### ISSUE TITLE
IServiceProvider instantiated more than once?

### ISSUE THREAD

**Issue by rcollina** [dotnet/efcore#24025]
I've been debugging something puzzling for the past few hours, and I could really use some help.

We are setting up Value Converters to serialize to and from JSON fields in a MySQL 8 database in the `DbContext.OnModelCreating` method.

The DbContext itself is registered as scoped.

One of these Value Converters is using `System.Text.Json`.

We are embedding custom de/serialization logic via the `Converters` section of a `JsonSerializeOptions` instance. One of said converters in turn depends on a Singleton dependency in our composition root.

Long story short, we are able to wire a DI dependency down to the EFCore Value Converter - basically mimicking what's described in [this post](https://www.tabsoverspaces.com/233774-using-data-protection-in-entity-framework-core-with-value-converters).

However, it seems that the Singleton dependency we rely upon is instantiated more than once (thus losing the information that is stored in the main instance, so to speak), as if two or more `IServiceProvider`s have been created.

We've been associating a GUID to the Singleton instance and we are in fact getting different GUIDs; there goes our Singleton.

Never had this happen in a non-EFCore ASP.NET Core 2 to 3.1 application.

Is it EFCore, could it be Pomelo - what we use to access MySQL, or are we missing something in our codebase (hopefully and more likely)?

Any help is truly appreciated.

**Comment by ajcvickers** [comment]
@rcollina Can you provide some more details on how you use the singleton dependency? In particular, is it a single dependency in the application's service provider, or in EF Core's internal service provider?

**Comment by ajcvickers** [comment]
@rcollina `OnModelCreating` is only called once when building the model. So if you are using the pattern from the blog, then it will capture the current service instance present when `OnModelCreating` is called and then use it forever. This doesn't quite align with what you are seeing and I am unable to connect the dots from the snippets posted. Please attach a small, _runnable_ project or post a small, _runnable_ code listing that reproduces what you are seeing so that we can investigate.

**Comment by rcollina** [comment]
@ajcvickers sorry for the late reply.

I'll try and create a repro asap but it's not going to happen soon I'm afraid - we removed EF+Pomelo and switched back to DbCommands since it was blocking us + deadline.

I'm not sure if the etiquette would dictate me closing the issue in the meantime.
