### ISSUE TITLE
Index invalidation caused by Oracle query condition N

### ISSUE THREAD

**Issue by kisshexuxia** [dotnet/efcore#24028]
Environmental Science:
ORACLE 11.2.0.4.0
.netcore2.2 EFCORE

The field type of sqbh is VARCHAR2

Create index statement
CREATE INDEX SQBHINDEX2021 ON TABLE (SQBH)

The index of the SQL query automatically generated by efcore is invalid when it has N
SELECT * FROM "TABLE" WHERE "d"."SQBH" IN (N'330000102001', N'330000102200')

The index is valid when the SQL query statement does not have N
SELECT * FROM "TABLE" WHERE "d"."SQBH" IN ('330000102001', '33000010220')

**Comment by roji** [comment]
@kisshexuxia this error seems to be specific to the [Oracle provider](https://www.oracle.com/database/technologies/appdev/dotnet.html), so you're going to have to raise this issue with them.

**Comment by ajcvickers** [comment]
@kisshexuxia Note that if the Oracle provider is working correctly, then this should not happen if the property is [explicitly configured](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-data-types) with a non-Unicode column type like "VARCHAR2".
