### ISSUE TITLE
ModelBuilder: Allow sequence store type to be specified

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2402]
We currently have...

``` C#
modelBuilder.Sequence("MySequence").Type<short>();
```

...but we should also allow you directly specify the store type (similar to properties).

```
modelBuilder.Sequence("MySequence").StoreType("smallint");
```

**Comment by divega** [comment]
A bit off topic, but why don't we also allow this syntax?

``` C#
modelBuilder.Sequence<short>("MySequence");
``` 

The `Type<T>()` method seems a bit strange. This would also make Sequence more similar to properties.

**Comment by bricelam** [comment]
I suspect because it's optional, and chaining is more consistent in that case. But there's no technical reason why we couldn't.

**Comment by divega** [comment]
Optionality can be handled with a non-generic overload. Just saying.

**Comment by bricelam** [comment]
Yeah, I think we should do it. I'll bring it up in API Review.

**Comment by bricelam** [comment]
*Triage:* YAGNI. The default mappings for `short`, `int`, `long`, etc. should always be sufficient.
