### ISSUE TITLE
Use Nullable value in EF Core Expression is a good idea?

### ISSUE THREAD

**Issue by Flithor** [dotnet/efcore#24022]
I means the code like:
```
var nextId = (dbContext.Set<MyEntity>().Max(entity => (int?)entity.keyId) ?? 0) + 1;
```
When the table is empty will still return a value safely.  
If not use the former code, the code will be:
```
var nextId = 1;
if (dbContext.Set<MyEntity>().Any())
    nextId = dbContext.Set<MyEntity>().Max(entity => entity.keyId);
```
## BUT
Is the former code a right and a good ieda?  
May it have any potential risks or problems? Or anti-pattern?

**Comment by anranruye** [comment]
I think it is right and I am doing the same thing in my project.

**Comment by ajcvickers** [comment]
@Flithor Seems fine.
