### ISSUE TITLE
IMutableForeignKey.SetProperties equivalent in .NET Core 2.1?

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/efcore#24030]
Hello,

I maintain a library that targets all supported releases of .NET Core, e.g. 2.1, 3.1, and 5.0

In 3.1 and 5.0 I use `IMutableForeignKey.SetProperties` in my model setup but it isn't available in 2.1. Is there a recommended way to accomplish the same in 2.1?

Thanks!

**Comment by AndriySvyryd** [comment]
@AndrewTriesToCode You'd have to rely on some internal code. Either using `IMutableForeignKey`:
```C#
using (((Model)foreignKey.DeclaringEntityType.Model).ConventionDispatcher.DelayConventions())
{
    foreignKey.DeclaringEntityType.RemoveForeignKey(foreignKey);
    foreignKey.DeclaringEntityType.AddForeignKey(newProps, foreignKey.PrincipalKey, foreignKey.PrincipalEntityType);
}
```

Or `InternalForeignKeyBuilder`:
```C#
((ForeignKey)foreignKey).Builder.HasForeignKey(newProps, ConfigurationSource.Explicit);
```

**Comment by AndrewTriesToCode** [comment]
Thanks @AndriySvyryd 

With EFCore 2.1 this still doesn't seem to work. The former approach doesn't work because `DelayConverntions()` doesn't seem to be in EFCore 2.1 and the latter does add he new FK but it leaves the old one. I'm thinking that this might not be worth the trouble in 2.1.
