### ISSUE TITLE
Is .Net Framework supported as target framework(TF) for Web Jobs migrated to .Net Core 3.1

### ISSUE THREAD

**Issue by amitshukla25** [dotnet/efcore#24038]
As per this https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#target-framework-net-framework-support-dropped,  starting with ASP.NET Core 3.0, .NET Framework is an unsupported target framework while the support for Asp.Net Core 2.1 packages on  .Net Framework will continue.

We are planning to migrate our web jobs from .Net Core 2.1 (targeting .Net Framework) to .Net Core 3.1 (including EF Core 3.1 and using version 3.x of Azure web jobs SDK) . Will .Net Framework 48 be a supported target Framework for this ?

I am assuming so since we are not using any Asp.Net Core packages directly per se but there could be indirect dependencies. Also we use the package Microsoft.ApplicationInsights.AspNetCore

Looking forward to some guidance on this

**Comment by huoyaoyuan** [comment]
> But my question was if my web job solution ( not based on ASP.NET Core MVC or using any ASP.NET Core packages but based on Ef Core 3.1) which I am migrating (updating Nuget packages from 2.1 to 3.1) will support targetting Net Framework 4.8

Their won't be an answer for this, because they are different components and have different versioning. The only answer is, for EF Core, Yes, but it's up to 3.1.

**Comment by roji** [comment]
@amitshukla25 as you can see in our [Supported .NET implementations page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms), EF Core 3.1 (and all it's dependencies) target .NET Standard 2.0, so they support .NET Framework 4.8 and will continue to do so. As a long-time support release (LTS), EF Core 3.1 goes out of support on December 3, 2022 ([see our releases page](https://docs.microsoft.com/en-us/ef/core/what-is-new/)), following which there will be no supported version of EF Core that works on .NET Framework.

Hope that answers your question.
