### ISSUE TITLE
Different behavior between 3.1 and 5 - Multi-2-Multi Unique Index detection

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#24032]
We are migrating from dotnet 3.1 to 5 and we think we see a difference in how ef 5 now looks at muti-2-multi relationship tables that carry Unique Indexs. Our scenario is as follows:

Order Table
Eval Table
OrderEval Table to specify possible multi-2-multi relations between orders and evals

In the future we could have a true many-2-many between Order and Eval but for now an Order can only have 1 Eval, for example. So to enforce that, for now, we put a unique index on the OrderId in the OrderEval table. However, we wrote our code based on the future requirement and not the short-term temporary requirement (of limiting Orders to 1 Eval) knowing that it would potentially happen. And 3.1 seems to have given us an ICollection<OrderEval> on the Order model. But it looks like ef 5 is now smart enough to see the unique index on the multi-2-multi table and "correctly" set up the model that way so that the Order model now has a singular OrderEval instead of an ICollection<OrderEval> that was present in ef 3.1.

Assuming this is the case we just want to know if there is a way to setup the scaffold to go back to the 3.1 behavior until we can get this addressed one way or another.

Hope this makes sense. Any help is much appreciated!

**Comment by ErikEJ** [comment]
Is this database first scaffolding?

In that case, please share a sample schema for the tables involved, and I can investigate.

**Comment by chassq** [comment]
Yes database first. The tables are fairly large so I have abbreviated to get to the point. Also I added our scaffold command example. Hope this helps.

`dotnet ef dbcontext scaffold "Data Source=<server>; Initial Catalog=<db>; user id=<uid>;password=<pwd>;MultipleActiveResultSets=True;Connection Timeout=30" Microsoft.EntityFrameworkCore.SqlServer -o Model -c AppContext -f --context-dir Context  --no-pluralize`

```
CREATE TABLE [dbo].[Order]
(
	[OrderId]		BIGINT NOT NULL,														
	CONSTRAINT [PK_dbo_Order] PRIMARY KEY CLUSTERED ([OrderId] ASC),
);

CREATE TABLE [dbo].[Eval]
(
	[EvalId]		BIGINT NOT NULL,														
	CONSTRAINT [PK_dbo_Eval] PRIMARY KEY CLUSTERED ([EvalId] ASC),
);

CREATE TABLE [dbo].[OrderEval] (
    [OrderEvalId]			    BIGINT       NOT NULL
    [OrderId]			        BIGINT                      NOT NULL,
    [EvalId]			        BIGINT                      NOT NULL,
    CONSTRAINT [PK_dbo_OrderEval] PRIMARY KEY CLUSTERED ([OrderEvalId] ASC)
)

CREATE UNIQUE NONCLUSTERED INDEX [UIX_dbo_OrderEval_OrderId] --This index specifies that orders can only have 1 active eval but evals can be shared across orders
    ON [dbo].[OrderEval]([OrderId] ASC)
    INCLUDE([EvalId]);
```

**Comment by ErikEJ** [comment]
I don't think the unique index does anything different from the primary key! 

But it looks like some foreign key constraints are missing.

**Comment by chassq** [comment]
Sry, I updated my post above to include the FKs on OrderEval.

**Comment by ErikEJ** [comment]
I see the same behavior, only option would be to DROP the index, change your code, or manually change the scaffolded code for now.

**Comment by chassq** [comment]
@ErikEJ thanks for confirming and advising! Might be nice in future to have a switch for something like this if ever possible or feasible.
