### ISSUE TITLE
CSharpMigrationsGenerator doesn't exists in Microsoft.EntityFrameworkCore.Design 5.0.2

### ISSUE THREAD

**Issue by 3ldar** [dotnet/efcore#24048]
## File a bug

EF Core version: 5.0.2
Database provider:  Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: .NET 5.0
Operating system: Windows 10
IDE:  Visual Studio 2019 16.8.4

I was trying to override ```CSharpMigrationsGenerator``` class to create my custom migrations generator. But couldn't find the class in the package. I tried to clean the solution, rebuild, uninstall and reinstall the package but nothing worked. So I had to downgrade to 5.0.1 and it came back. I think there is a packaging issue with the Microsoft.EntityFrameworkCore.Design 5.0.2 nuget package.

**Comment by ErikEJ** [comment]
See https://docs.microsoft.com/da-dk/ef/core/what-is-new/ef-core-3.x/breaking-changes#microsoftentityframeworkcoredesign-is-now-a-developmentdependency-package
