### ISSUE TITLE
using directive inside namespace = errors

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2404]
Hallo guys,

i just got an weird issue while using EF. I have a project which is named **MyCompany.System.MyTool**. if i'm not wrong, this should be a legit assembly and namespace name. i have an existing database and i want to access it via EF _Database First_ approach. so i add a _ADO.NET Entity Data Model_, adding the tables and let VS (and friends) do it's job. it ends in a lot of errors like that
- The type or namespace name 'Collections' does not exist in the namespace 'MyCompany.System' (are you missing an assembly reference?)
- The type or namespace name 'Guid' does not exist in the namespace 'MyCompany.System' (are you missing an assembly reference?)

and so on. it seems that the compiler is confused with the generated code, because of my namespace contains **System**.

if i change the generated code and place the _using System;_ and _using System.Collections.Generic;_ outside the namespace declaration and also changing _System.Guid_ to _Guid_ of the property definitions, all is fine. but that is not a solution, just a temporary workaround until the next code generation. i researched a little bit on the web found a lot of informations and discussions about placing the _using_ inside and outsite the namespace declaration, but no solution to fix that. i know that stylecop is enforcing to place the usings inside the namespace (http://stylecop.soyuz5.com/SA1200.html). but EF should generate working code, regardless how my project/namespace is named. i dont know how to do it well yet. maybe one of you guys have an idea, fix, suggestion or whatever.

thanks & regards
Kai

**Comment by rowanmiller** [comment]
**EF Team Triage:** Using `System` within your own namespaces isn't really recommended, but for cases like this you can just modify the T4 template to generate code that works in your application (i.e. you can move the using statements to outside the namespace).
