### ISSUE TITLE
Foreign key field of one side of an one-to-one relationship is not updated in the database

### ISSUE THREAD

**Issue by AndresLuga** [dotnet/efcore#24046]
## Foreign key field of one side of an one-to-one relationship is not updated in the database

**Project:** https://github.com/AndresLuga/2021.02.02

Model:
```
public class WagonVisit : BaseEntity
{
	public int? Form6WagonId { get; set; }
	public Form6Wagon Form6Wagon { get; set; }
}

public override void Configure(EntityTypeBuilder<WagonVisit> builder)
{
	base.Configure(builder);
	builder.HasOne(wv => wv.Form6Wagon)
		   .WithOne(f6 => f6.WagonVisit)
		   .HasForeignKey<Form6Wagon>(f6 => f6.WagonVisitId)
		   .IsRequired(false);
}

public class Form6Wagon : BaseEntity
{
	public int? WagonVisitId { get; set; }
	public WagonVisit WagonVisit { get; set; }
}

public override void Configure(EntityTypeBuilder<Form6Wagon> builder)
{
	base.Configure(builder);
	builder.HasOne(f => f.WagonVisit)
		   .WithOne(wv => wv.Form6Wagon)
		   .HasForeignKey<WagonVisit>(wv => wv.Form6WagonId)
		   .IsRequired(false);
}
```

Setup:
```
using var dbContext = new RailwayDBContext(RailwayDBContext.Options);
var f6 = new Form6Wagon();
dbContext.Form6Wagons.Add(f6);
var wagonVisit = new WagonVisit();
dbContext.WagonVisits.Add(wagonVisit);
wagonVisit.Form6Wagon = f6;
f6.WagonVisit = wagonVisit;
dbContext.SaveChanges();
```

**Problem 1:** database table `Form6Wagons` column `wagon_visit_id` is null, although the C# code assigned a value (`f6.WagonVisit = wagonVisit`).

**Problem 2:** the following code leaves `form6==null`, which is incorrect.
```
using var dbContext = new RailwayDBContext(RailwayDBContext.Options);
var visit = dbContext.WagonVisits.First();
var form6 = dbContext.Form6Wagons.SingleOrDefault(f => f.WagonVisitId == visit.Id);
```

**Problem 3:** both following statements produce the same query that uses join between the tables instead of actually looking at column `Form6Wagons.wagon_visit_id`. This produces invalid results, if `Form6Wagons` side of the relation contains a reference, but `WagonVisits` side does not.
```
dbContext.Form6Wagons.Where(f => f.WagonVisit == null);
dbContext.Form6Wagons.Where(f => f.WagonVisitId == null);
```

### Include provider and version information
EF Core version: 5.0.2.
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 5.0.2, Microsoft.EntityFrameworkCore.Sqlite 5.0.2.
Target framework: 5.0.200-preview.20614.14.
Operating system: Windows 10 Pro, 20H2.
IDE: Visual Studio 2019 16.9 Preview 3.

**Comment by ajcvickers** [comment]
@maumar to investigate

**Comment by ajcvickers** [comment]
@AndresLuga The navigation properties `Form6Wagon` and `WagonVisit` are used to map a relationship with the foreign key on one side of the relationship:

```C#
	builder.HasOne(wv => wv.Form6Wagon)
		   .WithOne(f6 => f6.WagonVisit)
		   .HasForeignKey<Form6Wagon>(f6 => f6.WagonVisitId)
		   .IsRequired(false);
```

And then again for a different relationship with a different foreign key:

```C#
builder.HasOne(f => f.WagonVisit)
		   .WithOne(wv => wv.Form6Wagon)
		   .HasForeignKey<WagonVisit>(wv => wv.Form6WagonId)
		   .IsRequired(false);
```

This causes the second configuration replaces the first configuration model.

Navigation properties cannot be used for multiple different relationships. See https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key for more details on modelling relationships.
