### ISSUE TITLE
.NET5 Scaffold-DbContext - Lower case naming issue.

### ISSUE THREAD

**Issue by cgountanis** [dotnet/efcore#24040]
Table [ref].[Training] get converted to object name lower case training, really strange one here, checked the PK/FK everything is upper case T. Why would it pick just this table out of 100 tables to lower case the name "training"?

Scaffold-DbContext "Server=localhost;Database=XXX;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Context Context -ContextDir Models -Force

Tried with and without "-UseDatabaseName". Same results.

Soooooo strange!

![image](https://user-images.githubusercontent.com/14899817/106521310-abd14e80-64a3-11eb-9098-2b31122854e1.png)

**Comment by ErikEJ** [comment]
Feel free to share schema privately, and I will investigate.

**Comment by cgountanis** [comment]
Here is the code that will give you the same exact results. There is really nothing to it... Appreciate the help @ErikEJ @smitpatel 

Create Table
`CREATE TABLE [dbo].[Training]( [ID] [int] NOT NULL PRIMARY KEY)`

Then in VS > Package Manager Console run:
`Scaffold-DbContext "Server=localhost;Database=TEST1;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Context Context -ContextDir Models -Force`

Strange only the Training table gets lower cased.
![image](https://user-images.githubusercontent.com/14899817/106618518-272f1080-6535-11eb-898a-51c17800d5e9.png)

**Comment by ErikEJ** [comment]
I would be surprised if that is enough to repro. What is "Training2" ?

**Comment by cgountanis** [comment]
All you need is one table name Training and the uppercase T disappears. Training2 was just a test proving that it works fine unless the word is just Training. Like I said this is very simple to reproduce and very strange result. With all due respect I put the time into giving you an example. What kind of response is you don't think this is enough to reproduce if you didn't try it?

**Comment by cgountanis** [comment]
Just to be clear, this is the new .NET5 EF5 new release version. Worked fine in CORE 3.

**Comment by ErikEJ** [comment]
Thanks, I will give it a try. What locale is your OS?

**Comment by ErikEJ** [comment]
It looks like a bug in the default Humanizer pluralizer, you can add `-NoPluralize` to work around it.

**Comment by cgountanis** [comment]
> It looks like a bug in the default Humanizer pluralizer, you can add `-NoPluralize` to work around it.

You know that was going to be my first guess since it worked in 3.0 and the plural seem to come out with five. I was going to mention something but I didn't want to just guess. Really appreciate the time and I had no clue about that flag so that will come in very handy. Since it's a bug is there anything I can do to get it on the to-do list for fixing?

**Comment by roji** [comment]
I think we'd need to file a bug https://github.com/Humanizr/Humanizer, @ErikEJ do you want to do the honors? :)

**Comment by ErikEJ** [comment]
Sure, I will file a bug!

**Comment by cgountanis** [comment]
Thanks guys I really appreciate the help and time on this one.

**Comment by roji** [comment]
Thanks @ErikEJ - please post the link to it here in case people land here.

**Comment by ErikEJ** [comment]
Bug report created here: https://github.com/Humanizr/Humanizer/issues/1030
