### ISSUE TITLE
why dotnet ef migrations add throw Win32Exception?

### ISSUE THREAD

**Issue by navid-dada** [dotnet/efcore#24053]
I have a dotnet core v3.1 project with an entity framework DbContext. when I try to run:

**dotnet ef migrations add someMigrationName**

this Exception will be thrown:

```
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.EntityFrameworkCore.Tools.Exe.Run(String executable, IReadOnlyList`1 args, String workingDirectory, Boolean interceptOutput)
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
No such file or directory

```
My development environment is a Linux elementary os (Ubuntu 18.04.4 LTS) and rider IDE.

It may be irrelevant but when I try to debug my xunit tests it returns this warning and cannot start execution.

All of these commands work properly and show all options:

-     dotnet
-     dotnet ef
-     dotnet ef migrations

but when I use these options Exception raised:

  

1.   dotnet ef migrations add
2.     dotnet ef migrations list

**Comment by AndriySvyryd** [comment]
@navid-dada Can you provide a small repro project and information on where it's located on your machine?

Do you experience the same issue with EF Core 5? (you'd need to reinstall the ef global tool)

**Comment by navid-dada** [comment]
[ConsoleApp1.zip](https://github.com/dotnet/efcore/files/5938702/ConsoleApp1.zip)
Hi dear @AndriySvyryd 
I attached my sample code to this message. I am currently using ef core 5 and my ef tools are installed globally.
It would be great favor If you direct me to the solution.

**Comment by roji** [comment]
@navid-dada your code sample doesn't work for the following reasons, which are unrelated to the Win32Exception:
* The sample uses the InMemory database, which isn't a relational (SQL) database and therefore does not support migrations. Switch to Sqlite, SQL Server or similar to test.
* Your TestDbContext doesn't have a parameterless constructor, so the design-time tools (e.g. `dotnet ef migrations add`) cannot use it. [See these docs](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli) on the various options for design-time DbContext creation.

Once I corrected the above two issues, everything works fine here, on Ubuntu 20.10. I suspect you may be working on a network drive or some similar storage that may be causing the issue. I recommend trying to have the application sources on a normal, local directory and trying again.

**Comment by navid-dada** [comment]
@raj your point about the InMemory database is right but my CLI did not work at the first stage to run the ef command and It can not go further step to validate my project structure, so I think we must concentrate on the ef command execution stage.
I have another production-ready project which using SqlServer database but it throws that Wn32Exception.
Also, about my hard drive and storage, this sample project is o my primary SSD Storage and that other production-ready is on my HDD Secondary Storage, and both of them throw the same Exception,

**Comment by roji** [comment]
@navid-dada we still need a minimal code sample that produces the exception. Even if the exception happens at a very early stage, that would be sufficient as a repro for us to investigate, assuming we can see the same thing happening here.

Since the vast majority of users are successfully using these tools, I suspect there's some sort of environmental issue specific to your machine (or similar). Have you tried running on another machine, for example?

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
