### ISSUE TITLE
Migrationbuilder check if table, columns, schemas exists

### ISSUE THREAD

**Issue by KhoaND290391** [dotnet/efcore#24052]
Currently we don't have any method to check if table, columns, schemas exists before run migration version.
We should have it, to ensure on manual migration will work, without delete table/colums/schema (lost data).

Provide new API or make MigrationBuilder.SQL with option that returned value then developer can check 
if table, columns, schemas exists by themselves.

**Comment by roji** [comment]
@KhoaND290391 migrations work by storing the current migration version inside your database; when you then apply migrations, EF Core automatically checks the database and applies the correct migrations - either via the tooling, or via checks in the idempotent migrations). So you should not need to check whether database objects exist or not.

If you think the above doesn't work for you, can you please share more details on what you're trying to do and why the general migrations mechanism is insufficient?

Make sure to read [our docs on migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/) for more information on this.

**Comment by KhoaND290391** [comment]
Thanks @roji for fast replying.
Root cause:
Database have serveral version. 1.1, 1.2, 1.3, 2.1, 2.2, 3.1, 3.2.
1.1 does not has table UserProfile, 
1.2 generate table UserProfile with only UserId, Name then has migration id = "1111_addUserProfile"
1.3 update UserProfile with UserId, Name, Email. then has migration id = "1112_updateUserProfile"
----
2.1 base on 1.1 does not generate table UserProfile
2.2 generate table UserProfile with UserId, Name, Email, Phone, Address, then has migration id = "123_addUserProfile"
----
Now 3.1 and 3.2 want to merge all changes of 1.1, 1.2, 1.3, 2.1, 2.2 (due to database now if big, we cannot delete any column)
__
There is only way to resolve this problem is we need to ensure table already exists, columns is exists....
But I did not find any methods can help me in Migrationbuilder class.
Migrationbuilder.Sql seem an approach but it doesn't return any result.
Could you guide me how to due with it? 
----
I hope my answer is make sense. 
Thank you so much.

**Comment by KhoaND290391** [comment]
Thanks @roji for fast replying.
Root cause:
Database have serveral version. 1.1, 1.2, 1.3, 2.1, 2.2, 3.1, 3.2.
1.1 does not has table UserProfile, 
1.2 generate table UserProfile with only UserId, Name then has migration id = "1111_addUserProfile"
1.3 update UserProfile with UserId, Name, Email. then has migration id = "1112_updateUserProfile"

----

2.1 base on 1.1 does not generate table UserProfile
2.2 generate table UserProfile with UserId, Name, Email, Phone, Address, then has migration id = "123_addUserProfile"

----

Now version 3.1 and 3.2 want to merge all changes of 1.1, 1.2, 1.3, 2.1, 2.2 (due to database now if big, we cannot delete any column)

----

There is only way to resolve this problem is we need to ensure table already exists, columns is exists....
But I did not find any methods can help me in Migrationbuilder class.
Migrationbuilder.Sql seem an approach but it doesn't return any result.
Could you pls guide me how to due with it? 

----
I hope my answer is make sense. 
Thank you so much.

**Comment by roji** [comment]
It sounds like you have completely divergent database schemas which you're trying to unify back into one - AFAICT that's not a scenario that's currently supported by EF Core's migrations. The basic working principle of migrations is that you have a single, linear history.

What you can do, is do your checks on table/column existence inside the raw SQL you provider to MigrationBuilder.Sql; instead of trying to get back a value from the database and checking in C# (this isn't supported), simply check in SQL. Something like the following:

```sql
IF NOT EXISTS (SELECT 1 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_TYPE='BASE TABLE' 
           AND TABLE_NAME='mytablename') 
BEGIN
    CREATE TABLE mytablename (...);
END
```

I'd highly recommend bringing converging your databases back to a single schema, which you can then manage normally via migrations without these manual checks.

Maybe @bricelam or @ajcvickers have other ideas to suggest.

**Comment by KhoaND290391** [comment]
Thank you so much for your time,
I think If cannot use MigrationBuilder, I will come up with manual create table , column by raw SQL instead.
Really appreciate your help.
