### ISSUE TITLE
EFCore retrives all columns of a table when a not mapped property is included in select query.

### ISSUE THREAD

**Issue by zeeshanzahoor** [dotnet/efcore#24055]
### Linq query
```C#
var query = ServiceDefinition.Select(m => new
{
  Id = m.Id,
  NotMappedDiscriptionModel = m.DescriptionMl // this property has NotMapped attribute
}).ToList();
```

### Generated SQL

```SQL
SELECT [s].[ID], [s].[ACTION_TYPE_PL], [s].[ASSEMBLY_METHOD_DEFINITION_ID], [s].[CACHE_MAX_AGE], [s].
[CACHE_SIDE_TYPE_PL], [s].[CACHEABLE_TYPE_PL], [s].[CONTENT_TYPE_PL], [s].[EXTERNAL_PATH]
FROM [dbo].[SERVICE_DEFINITION] AS [s]
GO
```

### Expected Behaviour

```SQL
SELECT [s].[ID] FROM [dbo].[SERVICE_DEFINITION] AS [s]
GO
```

EF Core version: 2.21,3.1,5.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by anranruye** [comment]
EF core can't get the value of `m.DescriptionMl` by database query becasue this property is not mapped to a database column. To get the value of `m.DescriptionMl`, ef core must materialize the whole entity object. So the behavior of your linq query is like:
```C#
var query = ServiceDefinition.ToList()
.Select(m => new
{
  Id = m.Id,
  NotMappedDiscriptionModel = m.DescriptionMl // this property has NotMapped attribute
}).ToList();
```
If the value of `m.DescriptionMl` is not related with other properties, you can use const value instead:
```C#
var query = ServiceDefinition.Select(m => new
{
  Id = m.Id,
  NotMappedDiscriptionModel = "defaultValueForDescriptionMl"
}).ToList();
``` 
If the value of `m.DescriptionMl` is computed by other property values, you can map `DescriptionMl` as a computed column, see https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns
