### ISSUE TITLE
Owned Entity Configuration not detecting all changes

### ISSUE THREAD

**Issue by KelownaSoftware** [dotnet/efcore#24068]
If you create an EntityTypeConfiguration class that is used to define the configuration of an owned entity, any changes made to owned entity is recognized by the migration change detector and the migration contains empty Up/Down methods. 
New and removed fields are correctly detected.

```
public class BaseEntity
{
    public string Id { get; set; }
    public ActionRecord CreatedBy { get; set; }
}
```

```
public class MyEntity : BaseEntity
{
     //some other irrelevant properties
}
```

```
public class MyEntityConfiguration : IEntityTypeConfiguration<MyEntity>
{
    public override void Configure(EntityTypeBuilder<MyEntity> builder)
    {
        base.Configure(builder);
         builder.OwnsOne(x => x.CreatedBy, e => new ActionRecordConfiguration());
    }
}
```

```
public class ActionRecordConfiguration: IValueObjectConfiguration<ActionRecord> 
//IValueObjectConfiguration derives from IEntityTypeConfiguration
{
    public void Configure(EntityTypeBuilder<ActionRecord> builder)
    {
        builder.Property(x => x.Id).HasMaxLength(36); //change to 999
        builder.Property(x => x.Name).HasMaxLength(50);
    }
}
```

```
public class AppDbContext : DbContext
{
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // apply configurations only on entities and not value objects
            modelBuilder.ApplyConfigurationsFromAssembly(
            typeof(AppDbContext).Assembly,
            t => t.GetInterfaces().Any(i =>
                i.IsGenericType &&
                i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>) &&
                typeof(BaseEntity).IsAssignableFrom(i.GenericTypeArguments[0]))
            );
        }
}
```

I can successfully create this migration no problem, however if I change  the ActionRecordConfiguration from
``` 
builder.Property(x => x.Id).HasMaxLength(36); //change to 999 
```
to 
```
 builder.Property(x => x.Id).HasMaxLength(999); 
```
and run the migration, no changes are detected.

If I add, or remove a new property and add configuration for those, the migration detects those.

If I replace MyEntityConfiguration from this
```
builder.OwnsOne(x => x.CreatedBy, e => new ActionRecordConfiguration());
```
to
```
builder.OwnsOne(x => x.CreatedBy, e => {
    e.Property(x => x.Id).HasMaxLength(999);
    e.Property(x => x.Name).HasMaxLength(50);
});
```
the change detection works just fine.

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 3.1.6)
Operating system:
IDE: (e.g. Visual Studio 2019 16.8.3)

**Comment by AndriySvyryd** [comment]
@KelownaSoftware Can you put a breakpoint on
```C#
 builder.Property(x => x.Id).HasMaxLength(36); //change to 999
```
to verify it actually gets called at all?

**Comment by KelownaSoftware** [comment]
How do you debug add-migration?

We know that if I add or remove anything within this file, the migration picks it up successfully, so I think we know it's being run.

**Comment by AndriySvyryd** [comment]
> How do you debug add-migration?

You can debug the application instead as this code should be called in the normal workflow.

**Comment by AndriySvyryd** [comment]
This line doesn't apply the configuration:
```C#
builder.OwnsOne(x => x.CreatedBy, e => new ActionRecordConfiguration());
```
I guess it should be
```C#
builder.OwnsOne(x => x.CreatedBy, e => new ActionRecordConfiguration().Configure(e));
```

**Comment by KelownaSoftware** [comment]
You beat me to it! I was just thinking that. However there is a compilation error 
```
builder.OwnsOne(x => x.CreatedBy, e => new ActionRecordConfiguration().Configure(e));
```
 cannot convert from 'Microsoft.EntityFrameworkCore.Metadata.Builders.OwnedNavigationBuilder<MyEntity ,ActionRecord>' to 'Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<ActionRecord>'

Which means my definition for the owned entity configuration could be incorrect?

**Comment by AndriySvyryd** [comment]
> Which means my definition for the owned entity configuration could be incorrect?

Yes, you need to call configuration methods on `OwnedNavigationBuilder<MyEntity, ActionRecord>`
