### ISSUE TITLE
Creating a one-to-many relationship EF Core - update-database fail

### ISSUE THREAD

**Issue by KamilGadawski** [dotnet/efcore#24063]
I encountered this problem when doing update-database. Where is the error being made?

[Creating a one-to-many relationship EF Core - update-database fail](https://stackoverflow.com/questions/66041955/creating-a-one-to-many-relationship-ef-core-update-database-fail)

**Comment by AndriySvyryd** [comment]
Feel free to comment if you are still having this issue.
