### ISSUE TITLE
Replacing One-To-One Entity does not delete old entity and throws unique constraint

### ISSUE THREAD

**Issue by Dresel** [dotnet/efcore#24064]
Apologize if this is working as expected, I couldn't find any clarification about this use case.

When replacing the dependent entity of a one-to-one relationship, `SaveChanges` throws a unique constraint exception. It works though if the dependent entity is eager loaded:

```C#
public static void Main(string[] args)
{
    ServiceCollection services = new ServiceCollection();
    services.AddDbContext<MyContext>(options => options.UseSqlite("DataSource=local.db"));

    var buildServiceProvider = services.BuildServiceProvider();

    using (var scope = buildServiceProvider.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<MyContext>();
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();
    }

    using (var scope = buildServiceProvider.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<MyContext>();
        context.Add(new EntityA() { EntityB = new EntityB() });
        context.SaveChanges();
    }

    using (var scope = buildServiceProvider.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<MyContext>();
        var entityA = context
            .EntitiesA
            // .Include(x => x.EntityB) // works if eager loaded
            .First();
        entityA.EntityB = new EntityB();

        // Throws unique constraint exception
        context.SaveChanges();
    }
}

public class MyContext : DbContext
{
    public DbSet<EntityA> EntitiesA { get; set; }

    public DbSet<EntityB> EntitiesB { get; set; }

    public MyContext(DbContextOptions<MyContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder
            .Entity<EntityB>()
            .Property<int>("EntityAId");

        modelBuilder.Entity<EntityA>()
            .HasOne(x => x.EntityB)
            .WithOne()
            .HasForeignKey<EntityB>("EntityAId");
    }
}

public class EntityA
{
    public int Id { get; set; }

    public EntityB EntityB { get; set; }
}

public class EntityB
{
    public int Id { get; set; }
}
```

**Comment by anranruye** [comment]
I believe this is working as expected.

**Comment by AndriySvyryd** [comment]
@Dresel If you don't load the old entity then EF doesn't know that it needs to be deleted and even if it guessed it doesn't know the PK value for it to be able to delete it.

**Comment by Dresel** [comment]
Theoretically it knows the PK of the Principal Entity which (in case of one-to-one) is a unique FK for the dependent entity?

@AndriySvyryd Sorry to bother you again, but is this correct:

_For replace and delete (setting null or empty collection) operations on navigation properties the navigation entity has to be tracked by EF. It does not matter if one-to-one, one-to-many or many-to-many._

_If the navigation entity is not tracked by EF the operation will fail for one-to-one (unique constraint) and lead to (additional) inserts for one-to-many and many-to-many?_


Are there best practice examples how to handle this within an entity without putting too much infrastructure logic into it:

```csharp
public class EntityA
{
    public virtual EntityB { get; private set; }

    public void UpdateEntityB(EntityB entity)
    {
        // Current workaround with lazy loading enabled but not really satisfying
        _ = this.EntityB;

        this.EntityB = entity;
    }
}
```

Is this topic covered somewhere by the docs? Could this be something added or linked to [relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)?

**Comment by Dresel** [comment]
What about modifying LazyLoadingInterceptor to also load on set? I wouldn't care about additional unnecessary database roundtrips if I do not have to think of entity states? Or would this lead to additional complications I didn't think of?

**Comment by AndriySvyryd** [comment]
> Theoretically it knows the PK of the Principal Entity which (in case of one-to-one) is a unique FK for the dependent entity?

EF can only delete by using PK values at this point.

> For replace and delete (setting null or empty collection) operations on navigation properties the navigation entity has to be tracked by EF. It does not matter if one-to-one, one-to-many or many-to-many.

> If the navigation entity is not tracked by EF the operation will fail for one-to-one (unique constraint) and lead to (additional) inserts for one-to-many and many-to-many?

Yes.

> What about modifying LazyLoadingInterceptor to also load on set? I wouldn't care about additional unnecessary database roundtrips if I do not have to think of entity states? Or would this lead to additional complications I didn't think of?

You can customize the lazy loading behavior by not using proxies: https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies

**Comment by Dresel** [comment]
Thanks for clarification. Very much appreciated.

We ended up by copying the implementation of `IProxyFactory` and replacing the used `IInterceptor` by a custom one that also checks for the setter. In that way we can avoid adding LazyLoader to every navigation property.
