### ISSUE TITLE
Behaviour change in FirstOrDefault or Entity creation from EF2.1 to EF3.x or 5.0 ?

### ISSUE THREAD

**Issue by nehio** [dotnet/efcore#24071]
Hello,

I am currently migrating our whole project from NetCore2.1 with EF2.1 to 5.0. And have come across an issue with the following code 

A controller is tryingto save a BOOKING entity , first we create one 

```
            booking = _context.Add(new Web.Data.Entities.Booking.Booking
            {
                Status = BookingStatus.Creating,
            }).Entity;

            return booking;
```

In  EF2.1 the booking.Id after creation was equal to Int32.Min value (-2147...) now it is 0, wich if i understand it correctly still means it's an ongoing creation. 

Now further along the code,  we have this 

`var bookingPriceExisting = _context
                    .BookingPrices
                    .FirstOrDefault<BookingPrices>(b => b.BookingId == booking.Id);`

BookingPrices beeing a table linked to Booking with a virtual navigation property.

In EF2.1 the FirstOrDefault would return with the creation of a new linked BookingPrices Entity attached to the booking entity, in both EF3.1 and 5.0 the FirstOrDefault returns null.

Downgrading the EF back to 2.1 makes everything work again so it is not a question of code change but what the code behind does, or maybe some configuration that needs to be added ?

Thank you in advance for any help on this issue.

**Comment by AndriySvyryd** [comment]
This is an intentional breaking change https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#tkv
