### ISSUE TITLE
Calling FromSqlRaw with UNION query returns duplicate results

### ISSUE THREAD

**Issue by jonathan-bender** [dotnet/efcore#24078]
**EF Core version:** 5.0.2
**Database providers:** Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.Sqlite
**Target framework:** .NET Core 3.1
**Operating system:** Windows 10
**IDE:** VS 2019 16.4.5

I need to use UNION ALL to normalize some fields on a table but using the FromSqlRaw returns duplicate results.

#### Example in Sqlite

Sql query
```SQL
SELECT CustomerId, FirstName AS CustomerName
FROM Customers
UNION ALL
SELECT CustomerId, LastName AS CustomerName
FROM Customers
```

Model
```C#
    public class UnpivotedCustomer
    {
        [Key]
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
    }

```
Execution results on the server:
| CustomerId | CustomerName |
| -- | -- |
| 1 | John |
| 1 | Doe |

Execution results using FromSqlRaw:
| CustomerId | CustomerName |
| -- | -- |
| 1 | John |
| 1 | John |

As you can see the first name is returned twice and the last name is not returned at all. I had the same problem when using the UNPIVOT statement in sql server but it's a bit more complex..

[Link to a working repo
](https://github.com/jonathan-bender/raw-sql-bug)

**NOTE:** the problem is resolved when using AsNoTracking. It can also be resolved by removing the Key attribute from the CustomerId property, but this trick doesn't work with the UNPIVOT statement.

Thanks and have a good weekend :)

**Comment by ajcvickers** [comment]
@jonathan-bender Tracking queries require each entity to have a unique primary key value, since the primary key is the identity under which the entity is tracked. You can use [keyless entity types](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations) for this if you don't need to track the results.

**Comment by sophisma** [comment]
> **NOTE:** the problem is resolved when using AsNoTracking. It can also be resolved by removing the Key attribute from the CustomerId property, but this trick doesn't work with the UNPIVOT statement.

Thank you for this, I was having the same issue.
