### ISSUE TITLE
Null error when ID property is null

### ISSUE THREAD

**Issue by kekoke** [dotnet/efcore#24072]
## The following runtime error occurs when certain properties are null.

```
 SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
```
When I define the entity as follows,  ID is not a primary key and can be null. I will get above error.

```C#
public class PICKLIST
    {
        public System.DateTime? CreateDate { get; set; }  
        public int? DEFAULTINDEX { get; set; }  
        public int? ID { get; set; }  // ID is not a primary key and can be null
        public int? ITEM_STATUS { get; set; }                
    }
```

When I modify the entity as follows,  it is work. 

```C#
public class PICKLIST
    {
        public System.DateTime? CreateDate { get; set; }  
        public int? DEFAULTINDEX { get; set; }  
        [Column("ID")]
        public int? SID { get; set; }  // ID is not a primary key and can be null
        public int? ITEM_STATUS { get; set; }                
    }
```
This is a strange question -^-^.

### version information
EF Core version: 3.1.6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE:  Visual Studio 2019 16.3

**Comment by anranruye** [comment]
If `ID` property is not primary key, then which one is the primary key property? Is the pk property a shadow property?

**Comment by kekoke** [comment]
> If `ID` property is not primary key, then which one is the primary key property? Is the pk property a shadow property?
> 
> When did you see the error message?

This entity has no primary key, this is an issue left over from history. I got the error when I execute the query commond. 
Maybe adding a primary key will solve this problem?  I am not sure. Thank you for your reply. -^-^

**Comment by anranruye** [comment]
You can use `[Keyless]` attribute(ef core 5.0 only) or `.HasNoKey()` fluent api to tell ef core the entity has no primary key.
See https://docs.microsoft.com/zh-cn/ef/core/modeling/keyless-entity-types?tabs=data-annotations
```C#
[Keyless]
public class BlogPostsCount
{
    public string BlogName { get; set; }
    public int PostCount { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<BlogPostsCount>()
        .HasNoKey();
}
```

**Comment by kekoke** [comment]
> You can use `[Keyless]` attribute(ef core 5.0 only) or `.HasNoKey()` fluent api to tell ef core the entity has no primary key.
> See https://docs.microsoft.com/zh-cn/ef/core/modeling/keyless-entity-types?tabs=data-annotations
> 
> ```cs
> [Keyless]
> public class BlogPostsCount
> {
>     public string BlogName { get; set; }
>     public int PostCount { get; set; }
> }
> 
> protected override void OnModelCreating(ModelBuilder modelBuilder)
> {
>     modelBuilder.Entity<BlogPostsCount>()
>         .HasNoKey();
> }
> ```

Thank you so much, this problem has been solved.
