### ISSUE TITLE
RevEng: Generate [Comment] attribute

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#24073]
The new comment attribute is not supported by reverse engineeering code generation, but it should be.

I propose that [Comment] attributes are generated in EF Core 6.

Happy to do a PR!

**Comment by ErikEJ** [comment]
Will also fix https://github.com/dotnet/efcore/issues/24070

**Comment by ajcvickers** [comment]
@ErikEJ Do you think that people want both doc comments and CommentAttributes by default?

**Comment by ErikEJ** [comment]
Not sure, actually. Did Comment attribute exist before your implementation? OData reference seems to indicate this, but I am unable to find evidence.

**Comment by ajcvickers** [comment]
Note from triage: we will consider this once there is a concrete case of the comment attribute being consumed by something other than EF Core.

**Comment by ErikEJ** [comment]
I re-read the OData comment now, and based on that, I will remove it from being generated with Power Tools, as you can always use the XML comments for documentation.
