### ISSUE TITLE
Can I add a typeconvertor attribute to the property of the model, instead of add HasConversion in OnModelCreating

### ISSUE THREAD

**Issue by william19941994** [dotnet/efcore#24080]
Can I add a typeconvertor attribute to the property of the model, instead of add HasConversion in OnModelCreating?

I  have an ERP interface which has 4000 tables to crate models.
Lots of the conversions are same. fixed length string trim, Yes/No conversion, integer and enum.

 
```C#
public class Rider2
{
    public int Id { get; set; }

    [EnumToNumberConverter(xxx)]
    public EquineBeast Mount { get; set; }
}
```

having an attribte [EnumToNumberConverter] on Mount  property is looks pretty than 

```C#
public class DriverDbContext : DbContext
{
  public DbSet<Rider2> Rider2s{ get; set; }
  public DriverDbContext(DbContextOptions<DriverDbContext> options): base(options)
  {
  }


  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    modelBuilder.Entity<Rider2>().Property(x => x.Mount ).HasConversion<EnumToStringConverter<EquineBeast >();
    base.OnModelCreating(modelBuilder);
  }      
}
```

**Comment by roji** [comment]
@william19941994 you may be looking for #10784, which would allow specifying once that all properties with a given type should have a value converter.

In the meantime, you can loop over your model's properties in OnModelCreating and configure a value converter yourself:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    foreach (var entityType in modelBuilder.Model.GetEntityTypes())
    {
        foreach (var property in entityType.GetProperties())
        {
            property.SetValueConverter(...);
        }
    }
}
```

You can even check if the property is annotated with an arbitrary attribute, and configure the property accordingly.

In general, not everything that can be done via the Fluent API (in OnModelCreating) can be done via Data Annotation attributes, especially since attributes are very limited in what they can accept as parameters.

**Comment by william19941994** [comment]
> @william19941994 you may be looking for #10784, which would allow specifying once that all properties with a given type should have a value converter.
> 
> In the meantime, you can loop over your model's properties in OnModelCreating and configure a value converter yourself:
> 
> ```cs
> protected override void OnModelCreating(ModelBuilder modelBuilder)
> {
>     foreach (var entityType in modelBuilder.Model.GetEntityTypes())
>     {
>         foreach (var property in entityType.GetProperties())
>         {
>             property.SetValueConverter(...);
>         }
>     }
> }
> ```
> 
> You can even check if the property is annotated with an arbitrary attribute, and configure the property accordingly.
> 
> In general, not everything that can be done via the Fluent API (in OnModelCreating) can be done via Data Annotation attributes, especially since attributes are very limited in what they can accept as parameters.

Thank you very much.
The code is just what I needed.
