### ISSUE TITLE
Unknown database enum values are read as the default enum value when using .HasConversion<string>

### ISSUE THREAD

**Issue by Zero3** [dotnet/efcore#24084]
When querying an entity with an enum field that has been mapped with `.HasConversion<string>()` (or manually with an `EnumToStringConverter<>`), Entity Framework reads unknown values in the database as the default value of the enum. This fallback behaviour is undesirable, as it can cause silent data corruption in memory.

### Enum in code

````
public enum State
{
	MyFirstState,
	MySecondState,
	MyThirdState
}
````

### Data in database

````
Id	State
1	MyThirdState
2	MyThirdState
3	MyFourthState
````

## Expected behaviour

Entity Framework throws an exception, either at model time or query time, as `MyFourthState` is not a recognized `State` value.

## Actual behaviour

Entity Framework silently reads `MyFourthState` as `MyFirstState`, leading to data corruption in memory.

Entity Framework seems to assume that it is valid to translate the unknown string value to the default value of enums (i.e. whatever string represents 0 internally, in this case the first state).

## Offending code

Seems to be the `default` fallback in this method in `StringEnumConverter.cs`, but I did not test:

````
        private static TEnum ConvertToEnum(string value)
            => Enum.TryParse<TEnum>(value, out var result)
                ? result
                : Enum.TryParse(value, true, out result)
                    ? result
                    : ulong.TryParse(value, out var ulongValue)
                        ? (TEnum)(object)ulongValue
                        : long.TryParse(value, out var longValue)
                            ? (TEnum)(object)longValue
                            : default;
````

## Notes

I am unaware of whether the current behaviour is by design for some reason unbeknownst to me. Maybe there are other use cases that depend on the current behaviour.

## Provider and version information

EF Core version: 5.0.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite (i did not test with other providers, but this issue should not be provider dependent)
Target framework: netcoreapp3.1

**Comment by lbargery** [comment]
This seems like quite a breaking change...

We tended to have a None = 0 value for all our enums which dealt with this well.

Does this mean that if 3 components reference the same database and we add a new enum value (which is mapped to a string), that ALL 3 components need releasing before we could add any rows in the database containing this new value?

If so, that is quite a change in our release process and would much prefer previous behaviour.

**Comment by ajcvickers** [comment]
@lbargery It should be very easy to [implement your own value converters](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations) with the old behavior for your enums.

**Comment by ajcvickers** [comment]
@timg83 Please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
