### ISSUE TITLE
Officially release the source code for the ReportViewer (RDLC)

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#24088]
There are many projects out there, that contain locally (client-side) rendered RDLC reports. Many of these projects contain such a number of reports, that it is unfeasible to migrate them just to be able to switch from .NET Framework to .NET 5.

This is especially an issue for Entity Framework based applications, that naturally use reporting on their client-side object model, instead of directly on the database tables.

There have been many issues filed over the years in regards to the missing RDLC functionality in .NET (Core), in the hopes to make Microsoft see that this is a major issue.
To this day, the issue remains one of the most requested features of the SQL Server team and has been for years (see ~~[develop a SSRS ReportViewer for ASP.NET Core](https://feedback.azure.com/forums/908035-sql-server/suggestions/33241936-develop-a-ssrs-reportviewer-for-asp-net-core)~~ [develop a SSRS ReportViewer for ASP.NET Core](https://feedback.azure.com/d365community/idea/ec1af842-4d25-ec11-b6e6-000d3a4f0da0)). *Edit: Currently (2022-01-14) it's in 4th place.*

Since Microsoft has apparently abandoned this part of the community and has moved on to other reporting products, that do not adequately fill the client-side gap (like Power BI), the community has build and maintained their own .NET (Core) compatible versions of the ReportViewer in multiple independent projects. AFAIK, all of these projects are based on decompiled versions of Microsoft's ReportViewer for .NET Framework.

_I have heard_, that at least one of those projects is not just compatible with .NET (Core) on Windows, but also compatible with Linux and SQL Server for Linux and is of high quality with a dedicated and active community.
However, because Microsoft's ReportViewer source code has not been published under an open source license to this date, the community has not made this project available to the public.

The community has asked before to make the ReportViewer open source. In response to a [comment of the "Announcing .NET 5.0 Preview 6" post](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-6/#comment-6660), 

> Any news on the SSRS ReportViewer control for WinForms? Reporting is super critical for many business applications out there, and currently a blocker for moving to .NET Core.
> If MS is short on resources to migrate it, I’m sure the community would be willing to help out if you put the source code up on GitHub

@jeremylikness had replied with:

> [...] I will take up the source code suggestion with the team.

Now, half a year later, I would like to follow up on the progress of making ReportViewer open source.
It would give the community the necessary legal framework to make their solutions publicly available and close this issue once and for all.

/cc @ajcvickers

**Comment by ajcvickers** [comment]
@lauxjpn Just wanted to let you know that @JeremyLikness is following up with this.

**Comment by lauxjpn** [comment]
@ajcvickers Awsome, thanks!

**Comment by JeremyLikness** [comment]
This is the plan for reporting moving forward:

[How to integrate PowerBI reporting into .NET apps](https://powerbi.microsoft.com/en-us/blog/how-to-integrate-power-bi-reporting-into-net-apps/)

**Comment by lauxjpn** [comment]
@JeremyLikness Thanks for the update! Looks like there will be no replacement for the locally running ReportViewer then, since PowerBI depends on cloud services.

Big bummer for EF Core developers and everyone else who is depending on it.

---

Since the .NET open source community is vast, it is of course possible that .NET 5/6 compatible source code for the ReportViewer might just publicly appear online. After all, there are many countries out there, where decompiling and changing not owned source code for maintenance purposes is legal.

An official agreement about the community usage, e.g. to just fix bugs and keep it compatible with the current .NET version, without changing any formats or adding new features, and maybe only using the local part, would of course have been a much cleverer and open source targeted approach, and probably a great opportunity for the PowerBI team to get in touch with the .NET community, that is nowadays widely open source centered.

I think the minimum would have been to at least talk about it, because businesses will/cannot recreate their large local legacy apps with hundreds of reports to suddenly work with a remote service, or are not allowed to due to privacy constraints. I am confident that a reasonable agreement could have been reached and an appropriate license found, for the PowerBI management not to feel threatened in regards to future cloud service revenue and with the .NET community being able to update their locally running legacy apps to .NET 6+ instead of being damned to stay on .NET Framework 4.8 until the end of time.

This might just be one of those cases, where the old and new Microsoft approach are colliding with each other.

**Comment by RichardD2** [comment]
> As you prepare to migrate your reports to Power BI, first verify that your organization has a Power BI Premium subscription.

So this is a money-grabbing exercise by Microsoft. Because paying for a Windows Server license and a SQL Server license isn't enough.

No thanks. We'll stick with .NET Framework 4.8 for as long as we can, and then move to a framework that actually embraces open source rather than merely paying lip-service to the idea. 🤬

**Comment by ajcvickers** [comment]
@lauxjpn @RichardD2 I would suggest you comment on the blog post where your comments can reach the decision makers here. This is not something that the EF team has any influence over.

**Comment by lauxjpn** [comment]
@ajcvickers Thanks, I [commented](http://disq.us/p/2m3sn2r) as suggested.

**Comment by RichardD2** [comment]
@ajcvickers That's a big part of the problem - NOBODY at Microsoft seems to want responsibility for SSRS support in .NET!

The .NET team said it's up to the SQL Server team. The SQL team sent us back to the .NET team. The .NET team passed it off to the EF team. And now we're being sent to the PowerBI team, who aren't going to give their product away for free, or provide a component that's not related to their product.

Meanwhile, having waited almost six years for .NET Core/5/6/7/... to support SSRS, we're now expected to tell our managers / customers that they have to pay Microsoft even more money before paying us to migrate our code to the new .NET, just so we can continue to do what .NET Framework can do for free. Nobody's going to sign off on that!

If Microsoft truly embraced open source, they could have released the existing ReportViewer source years ago, and we'd have multiple open source .NET Core versions available by now. Instead, any .NET Core version where the author has even looked at the decompiled source of the existing control risks legal action and licensing charges for anyone who uses it.

**Comment by RichardD2** [comment]
Also, there is no option to comment on the blog post. I've tried Firefox, Chrome, and Edge, and there is no "comment" form shown.

I guess they've removed that facility in anticipation of the angry comments they would otherwise receive.

**Comment by ajcvickers** [comment]
@RichardD2 
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1430078/149490708-18a69ee3-b075-4b24-83f6-909c3c8aced2.png">

**Comment by RichardD2** [comment]
@ajcvickers 

![image](https://user-images.githubusercontent.com/2158265/149490880-0c61c60d-4bc4-4824-86ea-c7e8a5adfda1.png)

![image](https://user-images.githubusercontent.com/2158265/149490958-46575457-9666-4039-8bf1-db3f3e5c49b4.png)

All "enhanced tracking protection" and ad-blockers disabled. No comment form in Firefox, Chrome, or Edge.

**Comment by ajcvickers** [comment]
@RichardD2 I will forward your issue with the blog to the blog owners.

**Comment by lauxjpn** [comment]
> Also, there is no option to comment on the blog post. I've tried Firefox, Chrome, and Edge, and there is no "comment" form shown.
>
> I guess they've removed that facility in anticipation of the angry comments they would otherwise receive.

@RichardD2 In that case, you might want to retry with a private/incognito window of your browser. 

I don't think anyone is trying to restrict you from posting you opinion. They use a normal Disqus comment system.

---

Also generally, it is a good idea too stay level-headed in situations like that. Especially accusations or finger-pointing usually turns out to be counter productive when trying to get others to the table to discuss an issue.

That being said, I understand of course the built-up frustration in regards to this issue over the long time this is going on. Might be best to wait 24 hours before posting in cases like this.

---

I cross referenced this issue thread in my post.
This is what I posted on the blog:

> **lauxjpn:**
>
> Hey Jeroen, what is the plan for RDLC reports?
> 
> I inquired to get the source code for the ReportViewer officially released to the open source community, since as far as I can see, Power BI is not targeting the RDLC area and there are many legacy apps out there that cannot/will not be rewritten to use a cloud service instead and are now stuck on .NET Framework 4.8.
> 
> Did Jeremy get in touch with you about it?
> 
> See [Officially release the source code for the ReportViewer (RDLC) #24088](https://github.com/dotnet/efcore/issues/24088) for the issue I posted on the EF Core repo and feel free to comment here or over there.
> 
> Thanks!

Christopher Finlan answered promptly:

> **Christopher Finlan:**
>
> I left this role in November, but I probably should answer this since this was discussed and decided during my time there. We looked a number of options here, including open sourcing the code, but that was ruled out for a myriad of reasons I can't get into. We aligned with the VS team on this and the decision was made to move ahead with Power BI embedded as the solution for these apps. Understand that not everyone will agree with this decision, but open sourcing the code officially isn't planned.

So as expected, it appears that it was a business decision.

**Comment by lauxjpn** [comment]
I now replied with the following:

> **lauxjpn**:
>
> Hi Christopher, thanks for responding!
> 
> I think it would have been a good idea to get some input from the community in that regard, since as far as I understand it, Power BI embedded is just a thin client to the Power BI cloud service, and therefore not a replacement for existing apps that locally run ReportViewer (which, e.g. could be connected to thousands of local in-memory objects) or even for future apps, where privacy or data protection restrictions prohibit the usage of cloud services.
> 
> I can imagine many of the reasons that came up in the internal discussion that let to the current business decision and I am sure that for most of them, a solution in form of an appropriate license, selective code publication (e.g. only the local code components) and restrictions to not step on the Power BI teams toes (e.g. no future feature development, strictly bug fixing and compatibility PRs, no XML format changes, only development on local components) could have been found.
> 
> As can be seen for other legacy .NET technologies, it is not unusual for Microsoft to let the community take over the maintenance part, once a technology is not officially supported anymore.
>
> From a business point of view, this seems like a missed opportunity to get in contact with a community, that you otherwise might not get connected to Power BI easily.
