### ISSUE TITLE
Auto increment for non-key properties 

### ISSUE THREAD

**Issue by EmirhanAksoy** [dotnet/efcore#24104]
## Migration Error : Only one column per table can be configured as 'Identity'. 

I have _Id_ and _No_ properties in my entity. _Id_ is primary key but _No_ isn't. I need auto-increment for _No_ too.

I check this [document](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#explicitly-configuring-value-generation) . It says two way of doing this Data Annotations  and Fluent API
I tried both of them. But ı am still getting this error while trying  to add migration :
*Only one column per table can be configured as 'Identity'. Call 'ValueGeneratedNever' for properties that should not use 'Identity'*

 **Data Annotation**
```C#
[Key]
public int Id {get; set;}

[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public int No {get; set;} 
```
 **Fluent API**
```C#
builder.Property(t => t.No).ValueGeneratedOnAdd();
```

EF Core version: 5.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
@EmirhanAksoy EF Core is still configuring your Id column as an identity column by convention, since you've done nothing to change that. You need to tell EF Core not to do that, [see these docs](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#no-value-generation). At that point it's up to you to always explicitly provide a unique Id value, or use some other generation mechanism (e.g. a sequence).

**Comment by HakamFostok** [comment]
So adding `[DatabaseGenerated(DatabaseGeneratedOption.None)]` on the top of the `No` property will solve the exception, and we still get the AutoIncrement for the `No` property, I am correct Sir?

**Comment by roji** [comment]
@HakamFostok no. I'm assuming that you want `No` to be your identity column, and `Id` to *not* be an identity column. If that's the case, you need to specify `[DatabaseGenerated(DatabaseGeneratedOption.None)]` on your `Id` property, which is being set up as identity by convention. In other words, something like the following:

```c#
[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
public int Id { get; set; }

[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public int No { get; set; }
```

Note that it then becomes your responsibility to specify the Id each time you insert a new row.

**Comment by EmirhanAksoy** [comment]
I want to make _No_ column auto-increasing without making it an identity column. That's my problem.

**Comment by HakamFostok** [comment]
@roji No Sir it is not the case, we want both `Id` and `No` to be auto-incremented, but we need to have only `Id` fields as our PK.
in other words, how can we add some auto-increment column without including it in the PK, without touching the PK

**Comment by roji** [comment]
Since SQL Server allows only one IDENTITY column per table, you can set up your `No` column to be sequence-driven - [see these docs](https://docs.microsoft.com/en-us/ef/core/modeling/sequences).

**Comment by SaraHal** [comment]
> I want to make _No_ column auto-increasing without making it an identity column. That's my problem.

Hi, Do you have any solution for this?

**Comment by ajcvickers** [comment]
@SaraHal See https://github.com/dotnet/efcore/issues/24104#issuecomment-776716640
