### ISSUE TITLE
EF Core Power tools / Reverse Engineer crashed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#24114]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/EF-Core-Power-tools--Reverse-Engineer-c/1327962)._

---
[severity:Other]
I tried to Reverse Engineer using EF Core Power Tools when my project was all Checked in in TFS then I did a Checked out and tried again with success.

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler. <ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 108

---
#### Mila Zhou[MSFT] on 2/2/2021, 09:57 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? What is the actual result and which result do you expect to happen?</p>
<p>We look forward to hearing from you!</p>

#### Marc Roussel on 2/3/2021, 06:32 AM: 

(private comment, text removed)
#### Feedback Bot on 2/3/2021, 09:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
@ErikEJ Any ideas on this?

**Comment by ErikEJ** [comment]
Hard to tell without version info, but potentially fixed in latest daily.

Best approach is to try latest daily, and maybe provide efpt.config.json file.

**Comment by ErikEJ** [comment]
Should be moved to Power Tools repo, but how do I contact the user?

**Comment by GearTheWorld** [comment]
Hi Erik,

Here are some details

My Email : geardoom3@live.com
I'm actually using version 2.5.454

Here's the efpt.config.json

`{
   "ContextClassName": "ApplicationDbContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": null,
   "ProjectRootNamespace": "CubiDataStore",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 0,
   "SelectedToBeGenerated": 2,
   "Tables": [
      {
         "Name": "[dbo].[Addresses]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Divisions]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Logs]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Products]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Rights]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Shipments]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Tokens]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[Users]",
         "ObjectType": 0
      },
      {
         "Name": "[dbo].[UsersRights]",
         "ObjectType": 0
      }
   ],
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": true,
   "UseDbContextSplitting": false,
   "UseFluentApiOnly": false,
   "UseHandleBars": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseNodaTime": false,
   "UseSpatial": false
}`

As mentionned in the previous ticket, crashes occur only if the project is checked in (TFS) otherwise everything is fine.

**Comment by ErikEJ** [comment]
Thanks, I will have a look. Assume the files are read only in this case?

**Comment by GearTheWorld** [comment]
Exactly

**Comment by ErikEJ** [comment]
@GearTheWorld I am not sure I understand the connection between this issue and TFS source control.
I have made some change to a faulty implementation in the latest daily build, lets see how far that gets you.

https://github.com/ErikEJ/EFCorePowerTools/commit/731497e47f9d6a60237ae42c230a6f03e63bf4ca

**Comment by ErikEJ** [comment]
@GearTheWorld did you try out the latest daily build?

**Comment by GearTheWorld** [comment]
@ErikEJ Monday ;)

**Comment by GearTheWorld** [comment]
System.Exception: Reverse engineer error: 
Microsoft.EntityFrameworkCore.Design.OperationException: No files were generated in directory 'C:\Dev\Cubi-Agile-New\Cubi-Agile\GlobexProjects\CubiShippingDashboardAPI\CubiDataStore\'. The following file(s) already exist(s) and must be made writeable to continue: Addresses.cs,Divisions.cs,Logs.cs,Products.cs,Rights.cs,Shipments.cs,Tokens.cs,Users.cs,UsersRights.cs.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.CheckOutputFiles(ScaffoldedModel scaffoldedModel, String outputDir, Boolean overwriteFiles)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.Save(ScaffoldedModel scaffoldedModel, String outputDir, Boolean overwriteFiles)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 121
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 55

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 115
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 52
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirstAsync>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 277

**Comment by ErikEJ** [comment]
That looks expected, or??

**Comment by GearTheWorld** [comment]
I would not expect a crash in the Output window like this but rather an intelligent behavior like anything in VS when something must be done on files they are automatically checked out.  Right now to use the tool we need to check out all the project involved for Reverse Engineer option in order to have the job done.

**Comment by ErikEJ** [comment]
Thanks! Too long ago since I used TFVC, I think 😁

**Comment by ErikEJ** [comment]
Is your project a classic project or the new style SDK project?

**Comment by GearTheWorld** [comment]
Sorry,  I'm not familiar with your terms
I simply have a Asp. Net core 5 web api with latest VS version and sdk of course

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GearTheWorld** [comment]
;) Don't worry, I face new things almost every day!

**Comment by ErikEJ** [comment]
I have made some changes to integrate added files better in the latest daily: https://github.com/ErikEJ/EFCorePowerTools/commit/32522f459092a5c05f9a610fe7dcba93fd21984b

**Comment by ajcvickers** [comment]
Closing as external.
