### ISSUE TITLE
Cannot update untracked entity if row version property is configured as shadow property

### ISSUE THREAD

**Issue by mnissl** [dotnet/efcore#24126]
My scenario is as follows:

My entity features a row version property. I load an entity with `AsNoTracking()`, attach it later to the context, modify a property and then save the changes. This works fine.

If I configure the row version property as a shadow property, the scenario described above no longer works:

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: 'Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.'
```

This is because the generated SQL code features "row_version is null":

```sql
UPDATE [dbo].[MyTable] SET [my_property] = @p0
WHERE [id] = @p1 AND [row_version] is NULL;
```

I could reproduce this behaviour both with EF Core 3.1.11 and EF Core 5.0.3.

**Comment by anranruye** [comment]
This is the expected behaviour.

You should set the row version shadow property manually after attach the disconnected entity by:
```C#
    dbContext.Entry(entityObject).Property("row_version").OriginalValue = rowVersion;
    dbContext.Entry(entityObject).Property("row_version").CurrentValue = rowVersion;
```
However, you may need an additional query to get the rowVersion value:
```C#
    var rowVersion = dbContext.Set<Entity>().Where(x => x.Id == entityObject.Id).Select(x => EF.Property<byte[]>(x, "row_version")).FirstOrDefault();
```
An recommended workaround is to use field-only property rather than shadow property.
