### ISSUE TITLE
Custom IdGenerator is not being used

### ISSUE THREAD

**Issue by nwendel** [dotnet/efcore#24120]
When using a custom MigrationsIdGenerator it works just fine when doing add-migration but the custom id generator is not used when doing update-database.

The id generator is registered like this:
```C#
public class CustomDesignTimeServices : IDesignTimeServices
{
  serviceCollection.AddSingleton<IMigrationsIdGenerator, CustomMigrationsIdGenerator>();
}
```

The id generator looks like this:
```C#
public class CustomMigrationsIdGenerator : MigrationsIdGenerator
{
  public override string GenerateId(string name)
  {
    return "Prefix_"+base.GenerateId(name);
  }

  public override bool IsValidId(string value)
  {
    /*throw new InvalidOperationException("IsValidId()");*/
    return true;
  }
}
```

When running add-migration the migration gets added with the proper id.  However when running
update-database it isn't used.  I can see that the custom migrations id generator is never created
in update-database if I put a default constructor which throws an exception, then the exception is
never thrown.

EF Core version: 5.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system:
IDE: Visual Studio 2019 16.8.4

**Comment by ajcvickers** [comment]
@bricelam I am able to reproduce this but I can't figure out what is going wrong. Even though `IsValidId` is called from `FindMigrationId`, which is called in several tooling paths, the overridden method never seems to be called.

**Comment by bricelam** [comment]
Ah, looks like IMigrationsIdGenerator is a runtime service, not a design-time service. Use ReplaceService instead.

**Comment by ajcvickers** [comment]
@bricelam But then why is the overload of `GenerateId` being called when a customer generator is added to design-time services? (By the way, while investigating this, I lost faith that I understand how computers work. The behavior I was seeing made no sense to me at all.)

**Comment by bricelam** [comment]
There are two service providers, the design-time services and the runtime services. Any components that resolve services from the design-time service provider would get the instance registered in IDesignTimeServices, but any components that use the runtime service provider would get the instance registered by the provider.

**Comment by ajcvickers** [comment]
@bricelam I'm still confused by what is going on here. Replacing the runtime service seems to have the same effect as replacing the design-time service, but it still doesn't seem like the implementation of `IsValidId` is being used by `FindMigrationId`, or maybe `FindMigrationId` isn't being called when I think it is? Either way, I'm unable to explain this behavior with my current understanding.

**Comment by ajcvickers** [comment]
Verified that `IsValidId` on the service is never called as part of `database update`, which is why the custom service implementation is not called in this case.
