### ISSUE TITLE
modelBuilder.HasDefaultSchema() not working for [__EFMigrationsHistory] table

### ISSUE THREAD

**Issue by changhuixu** [dotnet/efcore#24127]
```C#
public class MyDbContextA : DbContext
    {
        public DbSet<ModelA> ModelAs { get; set; }

        public MyDbContextA(DbContextOptions<MyDbContextA> options) : base(options)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("CA");
        }
    }

// in Startup.cs
var connString = Configuration.GetValue<string>("ConnectionStrings:MyApp");
services.AddDbContext<MyDbContextA>(options => options.UseSqlServer(connString));
```

The expected behavior is that the database migration will create a migration history table [CA].[__EFMigrationsHistory]
However, the migration uses the default schema of the current session/user, for example, [dbo] in my case.
This happens in EF Core 3.1, 5.0 at least.

I suspect that the extension method `services.AddDbContext<MyDbContextA>(options => options.UseSqlServer())` uses a default `SqlServerDbContextOptionsBuilder`. With that, the `o=>o.MigrationsHistoryTable("migration table name", "schema")` sets a NULL schema, which overrides the schema set by the `modelBuilder` for MigrationsHistoryTable.

By the way, all the model entities have correct default schema [CA].

Could you investigate? Thank you.

### Include provider and version information

EF Core version: 5.0.3
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
Default schema of model doesn't affect the schema for migration history table (migration history table is not part of the model). You need to use the method `MigrationsHistoryTable` to configure schema for history table.

**Comment by changhuixu** [comment]
@smitpatel Thanks for answering this issue.
Do you know if there's a constant string for the default EF MigrationsHistoryTable table name? So that we don't need to type in a magic string for the table name.

**Comment by smitpatel** [comment]
The string is publicly available here https://github.com/dotnet/efcore/blob/19847d7c6fdbdcacc9cd2c84129126f8cb57b19b/src/EFCore.Relational/Migrations/HistoryRepository.cs#L43

Not sure how you can reference in code directly.

**Comment by changhuixu** [comment]
perfect, it works.

```csharp
public class MyDbContextA : DbContext
    {
        public const string DefaultSchema = @"CA";
        public DbSet<ModelA> ModelAs { get; set; }

        public MyDbContextA(DbContextOptions<MyDbContextA> options) : base(options)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema(DefaultSchema);
        }
    }
```
```csharp
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

services.AddDbContext<MyDbContextA>(options => options.UseSqlServer(connString,
                        o => o.MigrationsHistoryTable(HistoryRepository.DefaultTableName, MyDbContextA.DefaultSchema)));
```

I hope we can have an extension method so that the code in the options can be shorter. For example,
In additional to,
```csharp
public virtual TBuilder MigrationsHistoryTable([NotNull] string tableName, [CanBeNull] string schema = null)
```
We can have a method,

```csharp
public virtual TBuilder MigrationsHistoryTableSchema([CanBeNull] string schema = null)
```

This should be easy. Thank you.

You can close this issue because my main question is answered.
