### ISSUE TITLE
Using zero in an integer field of a compound key results in bad insert query

### ISSUE THREAD

**Issue by jlddodger** [dotnet/efcore#2414]
When I run the program below, I receive an SqlException: "The number of columns for each row in a table value constructor must be the same."

Using the SQL profiler I discovered that the underlying query was this invalid query:

``` tsql
exec sp_executesql N'SET NOCOUNT OFF;
INSERT INTO [DayOfWeek] ([EventId])
OUTPUT INSERTED.[DOW]
VALUES (@p0),
(@p1, @p2),
(@p3, @p4);
',N'@p0 int,@p1 int,@p2 int,@p3 int,@p4 int',@p0=111,@p1=1,@p2=111,@p3=3,@p4=111
```

Test program:

``` c#
using Microsoft.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EF7InsertReport
{
   public class DayOfWeek
   {
      public virtual int DOW { get; set; }

      public virtual int EventId { get; set; }
   }

   public class MyContext : DbContext
   {
      public DbSet<DayOfWeek> DaysOfWeek { get; set; }

      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         modelBuilder.Entity<DayOfWeek>().Key(dow => new { dow.DOW, dow.EventId });
      }

      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseSqlServer(...);
      }
   }

   class Program
   {
      static void Main(string[] args)
      {
         MyContext db = new MyContext();
         db.Database.EnsureDeleted();
         db.Database.EnsureCreated();

         //db.DaysOfWeek.Add(new DayOfWeek() { DOW = -1, EventId = 111 });
         db.DaysOfWeek.Add(new DayOfWeek() { DOW = 0, EventId = 111 });
         db.DaysOfWeek.Add(new DayOfWeek() { DOW = 1, EventId = 111 });
         db.DaysOfWeek.Add(new DayOfWeek() { DOW = 3, EventId = 111 });
         db.SaveChanges();
      }
   }
}
```

**Comment by rowanmiller** [comment]
Hey,

This is because by default key properties will have values generated by the database if they are left set to the CLR default for the data type. Because int defaults to zero, it just looks like you never set a value for the first row, so EF has the database generate a value (presumably `1` since it's the first row being inserted) which then conflicts with the entity that you gave a value to.

We're still thinking about how to improve this scenario, since it seems to be tripping a few folks up. But given that it looks like you want to explicitly provide values rather than having the database generate them, you can just switch value generation off.

```c#
            modelBuilder.Entity<DayOfWeek>()
                .Property(d => d.DOW)
                .ForSqlServer()
                .UseNoValueGeneration();
```

**Comment by maumar** [comment]
related to https://github.com/aspnet/EntityFramework/issues/1653

**Comment by jlddodger** [comment]
Hey, thanks for the fast reply.  I have added the ```UseNoValueGeneration``` statement above and that definitely helps, but now I get an exception stating:

> The instance of entity type 'EF7InsertReport.DayOfWeek' cannot be tracked because it has an invalid (e.g. null or CLR default) primary key. Either set the key explicitly or consider using an IValueGenerator to generate unique key values.

I assume it is because the field is also part of the primary key.  Is that expected?

**Comment by maumar** [comment]
@jlddodger yes, this is a known issue, check out the #1653 for a bit more context on this

**Comment by rowanmiller** [comment]
@jlddodger in EF7 we introduced the idea of a sentinel value that represents `null` for properties that can not contain `null`. For integer values this is set to zero, but if you want zero the be a valid key value you can change it:

```
modelBuilder.Entity<DayOfWeek>()
                .Property(d => d.DOW)
                .Metadata.SentinelValue = -1;
```

**Comment by rowanmiller** [comment]
BTW we just had a design meeting on this to simplify the API and provide better exception messages to help folks understand how things work https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-July-2,-2015#sql-server-value-generation-scenarios
