### ISSUE TITLE
MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer.HasDifferences(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Metadata.IModel)'.

### ISSUE THREAD

**Issue by Buyani** [dotnet/efcore#24156]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by roji** [comment]
It is very likely that you are mixing versions of EF Core in your csproj - make sure all version are aligned. If you're still having issues, please post the entire csproj so we can investigate.

**Comment by Buyani** [comment]
By aligning all versions you mean using 3.1 version only fot he following
pacjkages :


Install-Package Microsoft.EntityFrameworkCore -Version 5.0.1
Install-Package Microsoft.EntityFrameworkCore.Tools -Version 5.0.1
Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 5.0.1



For Identity Account
Install-Package Microsoft.AspNetCore.Identity.UI -Version 5.0.1
Install-Package Microsoft.AspNetCore.Identity.EntityFrameworkCore -Version
5.0.1
Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
-Version 5.0.1

**Comment by roji** [comment]
Either everything needs to be 3.1, or everything needs to be 5.0 - but don't mix 3.1 and 5.0 packages. If you need further help, please post your csproj.

**Comment by Buyani** [comment]
My File looks like this

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

<UserSecretsId>aspnet-Template.Web-F408BCE4-9AC7-4F19-A779-0DA09EFD5A5C</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
Include="AutoMapper.Extensions.Microsoft.DependencyInjection"
Version="8.1.1" />
    <PackageReference
Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"
Version="2.2.0" />
    <PackageReference
Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.2"
/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI"
Version="3.1.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore"
Version="5.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"
Version="5.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"
Version="5.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers;
buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference
Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4"
/>
  </ItemGroup>


  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools"
Version="2.0.0" />
    <DotNetCliToolReference
Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference
Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
Include="..\Template.Business\Template.Business.csproj" />
    <ProjectReference Include="..\Template.Core\Template.Core.csproj" />
    <ProjectReference Include="..\Template.Data\Template.Data.csproj" />
    <ProjectReference Include="..\Template.Service\Template.Service.csproj"
/>
  </ItemGroup>

</Project>

**Comment by roji** [comment]
* Your Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore and Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore are at 2.2.0
* It's generally recommended to remove the <DotNetCliToolReference> nodes and install the EF Core tooling globally, [as in the documentation](https://review.docs.microsoft.com/en-us/ef/core/get-started/overview/install?branch=pr-en-us-3079#get-the-entity-framework-core-tools).
* You should probably also update Microsoft.AspNetCore.Identity.UI to 5.0 as well.
