### ISSUE TITLE
Implement relational expressions

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/efcore#24153]
While working on a project, exposing an API through ODATA, where the API maps on top of a bunch of SQL Tables/Views/Functions. I got limited by what EF/OData could expose for me. In my example, the following was difficult to expose without some significant performance overhead:

```csharp
class Station {
    ...
    DateTime? LastStartDate { get; set; }

    ICollection<StationMetric> Metrics { get; set; }
    ICollection<StationMetric> MetricsSinceLastStartDate { get; set; }
}
```

In my example, MetricSinceLastStartDate now maps to a View that joins Stations with Metrics and filters based on the obvious requirements. However since Stations itself is not a table but rather an expensive View, the consumer would effectively compute that view twice. Furthermore, There is no indication in this model that Metrics is read/write and MetricsSinceLastStartDate is essentially readonly. Finally, I'm now tied in with the database as I'm relying on Views though these could have been simple EFCore queries.

Instead, if we could have Relational Expressions in EFCore then that would take care of both problems, Here an example of what that could look like:

```csharp

class Cub {
   Guid Id;
   String Name;
 
   public ICollection<CubParticipation> Participations;
   public IReadOnlyCollection<Participants> WinningParticipants;
   public CubParticipation LastWinningParticipant;
}

public class Participant {
   Guid Id;
   string Name; 

   ICollection<CubParticipation> Participations;
   IReadOnlyCollection<Cub> CubsParticipated;
   Cub MostLegendaryParticipation;
}

class CubParticipation {
    Guid CubId;
    Guid ParticipantId;
    DateTime RecordDate;
    int Rank;
     
    Cub Cub; 
    Participant Participant;

}

ConfigureModel(ModelBuilder modelBuilder) {  
   var cubEntity = modelBuilder.Entity<Cub>();
   var participantEntity= modelBuilder.Entity<Participants>();
   var cubParticipation = modelBuilder.Entity<CubParticipation>();

   cubEntity.HasMany(x => x.WinningParticipations).FromExpression(cub => cub.Participations.Where(x => x.Rank == 1));
   cubEntity.HasOptional(x => x.LastWinningParticipant).FromExpression(cub => cub.WinningParticipations.OrderByDescending(x => x.RecordDate).FirstOrDefault());
   
   participantEntity.HasMany(x => x.CubsParticipated).FromExpression(participant => participant.SelectMany(x => x.Participations).Select(x => x.Cub).Distinct());
   participantEntity.HasOptional(x => x.MostLegendaryParticipation).FromSql(participant => $"SELECT * FROM [MyFunction](${participant.Id})");
   // Alternatively:
   participantEntity.HasOptional(x => x.MostLegendaryParticipation).FromExpression((participant, context) => context.Set<CubParticipation>().FromSql($"SELECT * FROM [MyFunction](${participant.Id})"));
}

```

This would allow me to query over my data in a clean form. Relationship expressions are essentially unidirectional. Instead of being two-way. If you want two-way relational expressions then you can set them up on both ends. EF does not need to know the relationship between the 2 expressions. 

Furthermore, entities pulled in through relational expressions can be perfectly tracker by the ChangeTracker, however you can't set any new values to relational expressions.

Instead of having the property type as a IReadOnlyCollection<T>, we could also allow IEnumerable<T> as well as IQueryable<T>. The last one enabling Lazy Loading (and further manipulation) over expressions.

https://github.com/dotnet/csharplang/discussions/161 would offer another solution for the same problem, if ever implemented.

**Comment by ajcvickers** [comment]
@koenbeuk This is closely related to #20339, so we are going to track there with a reference back to this issue for additional context.
