### ISSUE TITLE
Marshalling code generator warning when building net native UWP app referencing Microsoft.EntityFrameworkCore.Sqlite

### ISSUE THREAD

**Issue by lukenuttall** [dotnet/efcore#24163]
I'm getting marshalling code generator warnings when I include the Microsoft.EntityFrameworkCore.Sqlite nuget package version 3.1.12 (or 3.1.6) and build using net native for windows store deployment.

The binaries pass the WACK tool and can be deployed to the store, but I'm unsure whether we are doing something wrong or the package needs extra things in it's dllimports.

Is this likely to actually cause me any grief? Minimal repro attached.

[NugetTestApp.zip](https://github.com/dotnet/efcore/files/5986594/NugetTestApp.zip)

```
Running 'Mcg' transform, heap at 448 MB. (TaskId:361)
1>  Computing application closure and generating interop code (TaskId:361)
1>    Loading 120 modules... (TaskId:361)
1>C:\Users\luke_\.nuget\packages\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'libc!sysctl' for method 'System.Int32 Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Darwin.sysctl(System.Int32*, System.UInt32, System.Byte*, System.UInt32*, System.IntPtr, System.UInt32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
1>C:\Users\luke_\.nuget\packages\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'ntdll!RtlGetVersion' for method 'System.Int32 Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Windows.RtlGetVersion(Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Windows.RTL_OSVERSIONINFOEX)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
```

### Include provider and version information

EF Core version: 3.1.12
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: Microsoft.NETCore.UniversalWindowsPlatform 6.2.12
Operating system: 
IDE: VS 16.8.5

**Comment by ajcvickers** [comment]
@lukenuttall In general EF Core doesn't work with .NET Native. We are watching with interest how the various U.I. platforms develop. Given all the issues we have had trying to create a good experience for UWP together with internal usage data, we have currently put UWP work on the backburner.

**Comment by ajcvickers** [comment]
Note from triage: UWP is not supported in .NET 6.
