### ISSUE TITLE
HasDefaultValue sets value even when it is provided

### ISSUE THREAD

**Issue by jdbriaris** [dotnet/efcore#24167]
## File a bug

Believe this may have been hinted at before [here](https://github.com/dotnet/efcore/issues/23093). I'm using

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.3" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.3" />
```

I have defined an entity containing a column `PathHeadingDefinitionPoint` which is an enumeration, i.e.,

```
    public class OriginNode
    {
        public int Id { get; set; }
        public Guid GlobalId { get; set; }
        public double OffsetX { get; set; }
        public double OffsetY { get; set; }
        public double Heading { get; set; }
        public int PathId { get; set; }
        public PathHeadingDefinitionPoint PathHeadingDefinitionPoint { get; set; }
    }
```
where

```
public enum PathHeadingDefinitionPoint
    {
        PathStart,
        OriginNode
    }
```

I have setup the configuration for this as follows

```
public class OriginNodeConfiguration : IEntityTypeConfiguration<OriginNode>
    {
        public void Configure(EntityTypeBuilder<OriginNode> builder)
        {
            builder.ToTable("RC_OriginNodes");

            builder.Property(x => x.GlobalId)
                .ValueGeneratedOnAdd()
                .HasValueGenerator<GlobalIdGenerator>();

            builder.Property(x => x.PathHeadingDefinitionPoint)
                .HasDefaultValue(PathHeadingDefinitionPoint.OriginNode)
                .HasConversion<string>();
        }
    }
```
The SQLite table is constructed as follows

![image](https://user-images.githubusercontent.com/9742752/108069314-23ce7580-705b-11eb-960e-da1fff35022d.png)

However when I then attempt to add a new entry into the `RC_OriginNodes` table with the `PathHeadingDefinitionPoint` set to a value other than the default value, i.e., 

```
var originNode = new OriginNode
            {
                OffsetX = input.OffsetX,
                OffsetY = input.OffsetY,
                Heading = input.Heading,
                PathId = input.PathId,
                PathHeadingDefinitionPoint = PathHeadingDefinitionPoint.PathStart
            };

            await context.OriginNodes
                .AddAsync(originNode)
                .ConfigureAwait(false);
```
the desired `PathHeadingDefinitionPoint.PathStart` is ignored and replaced with the default `PathHeadingDefinitionPoint.OriginNode`. This is observed in the generated SQL

```
info: 16/02/2021 13:17:40.687 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (2ms) [Parameters=[@p0='61f121c4-569d-48ae-b4df-ea5d6f7dae46' (DbType = String), @p1='0' (DbType = String), @p2='0' (DbType = String), @p3='0' (DbType = String), @p4='1' (DbType = String)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "RC_OriginNodes" ("GlobalId", "Heading", "OffsetX", "OffsetY", "PathId")
      VALUES (@p0, @p1, @p2, @p3, @p4);
      SELECT "Id", "PathHeadingDefinitionPoint"
      FROM "RC_OriginNodes"
      WHERE changes() = 1 AND "rowid" = last_insert_rowid();
```
### Include provider and version information

EF Core version: 5.0.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.4

**Comment by jdbriaris** [comment]
removing the `HasDefaultValue()` from the configuration, i.e., 

```
builder.Property(x => x.PathHeadingDefinitionPoint)
                .HasConversion<string>();
```

and applying the default direct in the migration

```
 migrationBuilder.AddColumn<string>(
                name: "PathHeadingDefinitionPoint",
                table: "RC_OriginNodes",
                type: "TEXT",
                nullable: false,
                defaultValue: "OriginNode");
```
(Note: the migration looks identical to that created with `HasDefaultValue()` other than I typed in `"OriginNode"` for `defaultValue`) gives the desired behaviour. It appears the use of `HasDefaultValue()` is having unintended consequences within database context use?

**Comment by ajcvickers** [comment]
@jdbriaris This is covered in the documentation here: https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#working-with-default-values

**Comment by jdbriaris** [comment]
@ajcvickers Thanks. I'm just slightly confused then as it states in the link _"EF Core will only use a default from the database if no value has been explicitly set."_ However, as far as I can tell I'm explicitly setting the value in code when adding the entry to the database, but it continues to use the value generated from the database., i.e., when doing 

```
var originNode = new OriginNode
            {
               PathHeadingDefinitionPoint = PathHeadingDefinitionPoint.PathStart
            };

            await context.OriginNodes
                .Add(originNode);
```

it ignores that fact that I've set `PathHeadingDefinitionPoint" preferring to set it to the default as specified in the configuration. Is that the expected behaviour?

**Comment by ajcvickers** [comment]
@jdbriaris `PathStart` is the CLR default for the enum type. The docs I link show patterns for dealing with this.
