### ISSUE TITLE
Loading entity from DB does not properly load owned entity if one of it's properties is null

### ISSUE THREAD

**Issue by MalgorzataG26** [dotnet/efcore#24168]
## Description
When loading an entity from the DB, some owned entities are not loaded correctly if nullable property is null. We have class First, which has property of type Second. If id in Second is not null, the Third property is loaded, but if id is null, Third is also returned as null. 
When we run generated query in database, everything is returned correctly. 
```C#
    public class First
    {
        public Second Second { get; set; }
    }
    public class Second
    {
        public int? Id { get; set; }
        public Third Third { get; set; }
    }
    public class Third
    {
        public string Xyz { get; set; }
    }
```
Configuration:
```C#
builder.OwnsOne(e => e.Second, second => { second.OwnsOne(s => s.Third); });
```

EF Core version: 5.0.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.4

**Comment by ajcvickers** [comment]
@smitpatel to de-dupe.

**Comment by smitpatel** [comment]
Duplicate for #23564
