### ISSUE TITLE
Relation virtual properties are getting saved as NULL in Ef Core v 3.1.2, It used to work in 2.2.6

### ISSUE THREAD

**Issue by Qvijaypatil** [dotnet/efcore#24162]
## File a bug
DB Context object has values see the following screen shot
![image](https://user-images.githubusercontent.com/48548660/108026286-0fd04700-704e-11eb-877b-7c17a9618af4.png)

after db.Savechanges() values of virtual properties are getting saved as NULL

Find the database entries as below 

![image](https://user-images.githubusercontent.com/48548660/108026500-73f30b00-704e-11eb-9a53-4d16eda28764.png)

DB Context as follows 

![image](https://user-images.githubusercontent.com/48548660/108027124-a81afb80-704f-11eb-890d-9b9f4c27174f.png)

```c#
 public class HIPAA_5010_835_Context : DbContext, IDbContextSchema
    {
        public string Schema { get; }
        public string erain { get; }
        protected HIPAA_5010_835_Context() { }
        public HIPAA_5010_835_Context(string schema)
        {
            erain = schema;
            this.Database.EnsureCreated();
            this.ChangeTracker.AutoDetectChangesEnabled = false;
        }
        public HIPAA_5010_835_Context(DbContextOptions<HIPAA_5010_835_Context> options, IDbContextSchema schema = null) : base(options)
        {
            Schema = schema?.Schema;
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(ConnectionString);

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema(this.erain);
        }
    }
```

Also Please  note that above issues is encountered after updating ef core version from 2.2.6 to 3.1.2
Code is same 

Any help on this issue will be apreciated 

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.pgsql)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019)

**Comment by ajcvickers** [comment]
@Qvijaypatil There isn't enough information above for us to be able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Qvijaypatil** [comment]
@ajcvickers Thank you for looking into it.  please find the attached project below

[EfCoreRelational.zip](https://github.com/dotnet/efcore/files/6000772/EfCoreRelational.zip)

You can find save changes logic in main function as below

![image](https://user-images.githubusercontent.com/48548660/108317634-94ed6480-71e4-11eb-8c38-9261d44a402d.png)

Relational data is not getting save for following ef core version
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.2" />
  </ItemGroup>

</Project>

and if we degrade it to ef core 2.2.6 it works 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.4" />
  </ItemGroup>

</Project>
Can you please look into this again as it has became high priority issue for us.

 Your help is highly appreciated. Thank you so much !!

**Comment by ajcvickers** [comment]
Note for triage: this is a similar issue to #24006. In this case the entity types override properties like this:

```C#
public class BPR
{
    [DataMember]
    public virtual string TransactionHandlingCode_01 { get; set; }
}

public class BPR_FinancialInformation_2 : BPR, I_BPR
{
        [DataMember]
        [Required]        
        public override string TransactionHandlingCode_01 { get; set; }
}
```

This means that an instance of the derived type duplicates all the backing fields from the base type. EF Core is then reading and writing from a backing field that is never used.

@Qvijaypatil This is an unusual way to override properties and results in objects that use almost twice as much memory as they need since all the properties have duplicate backing fields. A more normal way to override properties like this is to use the backing field from the base class by calling down into the base class property getter and setter. For example:

```C#
        [DataMember]
        [Required]
        public override string TransactionHandlingCode_01
        {
            get => base.TransactionHandlingCode_01;
            set => base.TransactionHandlingCode_01 = value;
        }
```

**Comment by Qvijaypatil** [comment]
@ajcvickers  Thank you so much for quick responses and resolution to above issue. We have corrected derived class getters and setters properties and its working as expected!!
