### ISSUE TITLE
Intercept model initialization

### ISSUE THREAD

**Issue by r-work** [dotnet/efcore#24173]
Is it possible to do some model initialization when:

1. Model is instantiated but before data is written to it.
2.  After data is being written to it.

A small example would be something like the following:

```C#
public class MyModel
{
   public ObservableCollection<Item> Items { get; set; }

   public void OnModelCreating()
   {
       this.Items.IsLoading = true;
   }

   public void OnModelCreated()
   {
       this.Items.IsLoading = false;
   }
}
```

**Comment by ajcvickers** [comment]
@r-work Can you provide some more details on how this would be useful?

**Comment by r-work** [comment]
@ajcvickers this would be similar to **EntityLoading** and **EntityLoaded** which is mentioned [here](https://github.com/dotnet/efcore/issues/626), however that issue is about 7 years old, so I presume that's not going to be implemented.

My use case is pretty much the same as what has been described in that issue (copy & paste):

**EntityLoading**: 
After object instance is created but before its properties are initialized. Can be used to reset a flag that will be set in newly created instances but shouldn’t be set during initialization, i.e. for validation.

**EntityLoaded**:
Can be used to setup anything after an object has been materialized, i.e. event handlers, flags, etc.

**Comment by ajcvickers** [comment]
@r-work These are covered by #15911 and #10789.
