### ISSUE TITLE
FK shadow properties in iOS/Android AOT release version in Xamarin have wrong values

### ISSUE THREAD

**Issue by MaximMikhisor** [dotnet/efcore#24172]
### Model

```
    public class Blog
    {
        public Guid Id { get; set; }
        public string? Url { get; set; }

        public Post? Post1 { get; set; }
        public Post? Post2 { get; set; }
        public Post? Post3 { get; set; }
        public Post? Post4 { get; set; }
        public Post? Post5 { get; set; }
        public Post? Post6 { get; set; }
        public Post? Post7 { get; set; }
        public Post? Post8 { get; set; }
        public Post? Post9 { get; set; }
        public Post? Post10 { get; set; }
        public Post? Post11 { get; set; }
        public Post? Post12 { get; set; }
    }

    public class Post
    {
        public Guid Id { get; set; }
        public string? Title { get; set; }
        public string? Content { get; set; }
    }
```

### Code to get ChangeTracker.DebugView.LongView

```
    public static class BugFactory
    {
        public static String GetLongDebugView(bool isItConsole)
        {
            SeedData(isItConsole);

            using var db = new BloggingContext(isItConsole);

            var blog = db.Set<Blog>().First();

            return db.ChangeTracker.DebugView.LongView;
        }

        private static void SeedData(bool isItConsole)
        {
            using var db = new BloggingContext(isItConsole);

            db.Database.Migrate();

            if (db.Set<Blog>().Any())
                return;
            
            var blog = new Blog
            {
                Url = "http://blogs.msdn.com/adonet",
                Post1 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post2 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post3 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post4 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post5 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post6 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post7 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post8 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post9 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post10 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post11 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" },
                Post12 = new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" }
            };

            db.Add(blog);

            db.SaveChanges();
        }
    }
```

### Console application debug/release versions

Console application on Windows work as expected without any bugs. It works both in release and in debug version.

Result of `ChangeTracker.DebugView.LongView`:

<img width="400" alt="Console" src="https://user-images.githubusercontent.com/40904997/108180177-55cefd00-716b-11eb-8164-8cc7a108aa41.png">

### Xamarin.iOS application debug version

Xamarin.iOS application in debug mode works as expected without any bugs.

Result of `ChangeTracker.DebugView.LongView` in debug version:

<img width="400" alt="Debug_iOS" src="https://user-images.githubusercontent.com/40904997/108180403-99296b80-716b-11eb-9bdc-975f18d0eb20.PNG">

### Xamarin.iOS application release version

Xamarin.iOS application in release mode has a bug.
FK shadow properties have odd values.
Some of them are right. But some of them have strange wrong values and also have `Originally` values.

Result of `ChangeTracker.DebugView.LongView` in release version:

<img width="400" alt="Release_iOS" src="https://user-images.githubusercontent.com/40904997/108181098-5fa53000-716c-11eb-844e-38e32d50956f.PNG">

### Xamarin.Android application debug version

Xamarin.Android application in debug mode works as expected without any bugs.

Result of `ChangeTracker.DebugView.LongView` in debug version:

<img width="400" alt="Debug_Android" src="https://user-images.githubusercontent.com/40904997/108636923-244c8d80-74ed-11eb-8a78-56180903ba96.jpg">

### Xamarin.Android Hybrid AOT application release version

Xamarin.Android application in release mode has a bug, if it was compiled in AOT Hybrid mode. 
Bug was reproduced on `arm64-v8a` Android device (there is no bug on `x86` simulator).

FK shadow properties have odd values.
Some of them are right. But some of them have strange wrong values and also have `Originally` values.

Result of `ChangeTracker.DebugView.LongView` in release version:

<img width="400" alt="Release_Android" src="https://user-images.githubusercontent.com/40904997/108636948-6544a200-74ed-11eb-9497-49f737852108.jpg">

## Sample project

You can find sample project here: https://github.com/LineSmarts/EfCoreBug

## How to reproduce bug
Unfortunately to reproduce this error on iPhone you need to have Mac to be able to compile and run Xamarin.iOS application.

But it is possible to reproduce it on `arm64-v8a` Android device:
1. Get source code from sample project above.
2. Compile release Android project.
3. Run this project on  `arm64-v8a` Android device

Note:
Android release project set up to be compiled in AOT Hybrid mode. I.e. with these settings:
```
 <AndroidAotMode>hybrid</AndroidAotMode>
 <AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
 <EnableLLVM>false</EnableLLVM>
 <AndroidSupportedAbis>x86;x86_64;arm64-v8a</AndroidSupportedAbis>
```

## Provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Standard 2.1
Operating system: iOS/Android
IDE: Visual Studio 2019 16.8

## Question

Do you know what is possible reason of this bug?

**Comment by MaximMikhisor** [comment]
Updated bug description about Android AOT

**Comment by ajcvickers** [comment]
@Pilchie Who would be a good person to follow up with on Xamarin AOT issues?

**Comment by Pilchie** [comment]
@marek-safar - have you got a good contact?

**Comment by marek-safar** [comment]
This indeed looks like AOT codegen bug. Please report the issue at https://github.com/mono/mono with steps on how to reproduce it
