### ISSUE TITLE
Wrong path used with dots in -output parameter

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/efcore#24179]
Using the output parameter in `dotnet ef migrations add ...` of `CocApi.Cache.Migrations` produces the following:

![image](https://user-images.githubusercontent.com/29644329/108287165-6033cb80-7158-11eb-8fb4-ddb367a22034.png)

I had already manually created the single folder. The nested folders were created by ef.

EF Core version: 5.0.3
Database provider: Npgsql
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.4

**Comment by bricelam** [comment]
Do you mean the `--output-dir` parameter? If you really passed `-output` it would be forwarded to the application and (probably) ignored.

**Comment by bricelam** [comment]
Also, you can just move the model snapshot file where you want it, and it should be re-generated in the same place on subsequent commands.

**Comment by devhl-labs** [comment]
I'll try `--output-dir`, thanks.
