### ISSUE TITLE
Index on RAW(16) in Oracle database does not trigger when comparing to GUID from .NET 

### ISSUE THREAD

**Issue by Exasis** [dotnet/efcore#24187]
**Background info**
We have an Oracle Database running v. 18c, with a table containing a column with Datatype RAW(16).
![image](https://user-images.githubusercontent.com/13125021/108371246-db02f200-71fd-11eb-9547-cfd438c293c0.png)

The Datatype was chosen by Entity Framework using Code-first implementation of the GUID datatype in .NET

We have set up an index on the column
![image](https://user-images.githubusercontent.com/13125021/108371344-f53cd000-71fd-11eb-9b00-2ac0366d1e0c.png)

The equivalent field in .NET is setup like this
![image](https://user-images.githubusercontent.com/13125021/108371467-11407180-71fe-11eb-919c-acb8b247e994.png)

**Issue**
When running a query, looking for specific EJERSKIFTE_ID based on the GUID value, the query will not use the index. If instead we surround each representation of the GUID value with "HEXTORAW()" It will correctly use the index.

Original query (Not triggering index):
`SELECT "e"."OBJECTID"
FROM "GSTEJF"."EJERSKABSSKIFTE" "e"
WHERE (((((("e"."EJERSKIFTE_ID" IN ('AB6AF396EB644B17B517D698489B16D9', 'B7E9D9A8526541C7BA65DD3E314FB6C0')) AND ("e"."REGISTRERINGFRA" <= :transactionTime_1))) AND ((("e"."REGISTRERINGTIL" > :transactionTime_2) OR ("e"."REGISTRERINGTIL" IS NULL))))) AND ((("e"."VIRKNINGFRA" <= :validTime_3) AND ((("e"."VIRKNINGTIL" > :validTime_4) OR ("e"."VIRKNINGTIL" IS NULL))))))`
And corresponding Execution-plan
![image](https://user-images.githubusercontent.com/13125021/108374324-223eb200-7201-11eb-8286-5ec7c4278a33.png)

Modified query (Correctly triggering index):
`SELECT "e"."OBJECTID"
FROM "GSTEJF"."EJERSKABSSKIFTE" "e"
WHERE (((((("e"."EJERSKIFTE_ID" IN (HEXTORAW('AB6AF396EB644B17B517D698489B16D9'), HEXTORAW('B7E9D9A8526541C7BA65DD3E314FB6C0'))) AND ("e"."REGISTRERINGFRA" <= :transactionTime_1))) AND ((("e"."REGISTRERINGTIL" > :transactionTime_2) OR ("e"."REGISTRERINGTIL" IS NULL))))) AND ((("e"."VIRKNINGFRA" <= :validTime_3) AND ((("e"."VIRKNINGTIL" > :validTime_4) OR ("e"."VIRKNINGTIL" IS NULL))))))`
And corresponding Execution-plan
![image](https://user-images.githubusercontent.com/13125021/108374227-076c3d80-7201-11eb-80b1-d18b7c836f89.png)

**Comment by Exasis** [comment]
EF Core version: 3.1.10
Database provider: Oracle.Manageddataaccess
Target framework: 3.1.10
Operating system: Windows 10
IDE: Visual studio 2019

**Comment by roji** [comment]
@Exasis this repo contains EF Core itself and the Microsoft-provided providers, but the Oracle provider is not part of that. You will likely have to raise this issue with Oracle support.
