### ISSUE TITLE
Allow to query from a List<T> instead of having to convert it to a array

### ISSUE THREAD

**Issue by appec-bv** [dotnet/efcore#24186]
First of all I'd like to say that my technical terms are not always on point and I'll try to improve that. But I'll try to be as clear as possible.

Whenever I want to get a list of entities based on a list of entities I always need to convert the list to a array of the primary key type. 

Example

```c#

class Foo {

public int Id { get; set; }

}

class Bar {

public int Id { get; set; }

public Foo Foo { get; set; }

public int FooId { get; set; }

}

```

Example code

```c#
var foos = await context.Foo.ToListAsync(); // do whatever to get a List<Foo>
var fooIds = foos.Select(i => i.Id).ToArray();
var bars = await context.Bar.Where(i => fooIds.Contains(i.FooId));
```

If I do not do this and say for example

```c#
var bars = await context.Bar.Where(i => foos.Any(j => i.FooId == j.Id)).ToListAsync();
```

Then I get a error saying that LINQ couldn't be translated to SQL. So I am forced to first convert a `List<Foo>` to a `int[]` to be able to parse this to SQL?

I'd like for EF Core to take away a bit of this boilerplate. Please note that I am not the one to know all the technical possibilities, and if I am even posting this on the right place.

What I'd like is that this (from my example) simply works by taking the primary keys and comparing that. Or by using a deconstructor?  Or any other way so that I do not need to convert my `List<Foo>` to a `int[]`. But can just use the existing list. 

Hope I was clear enough on a issue I'm facing daily.

**Comment by roji** [comment]
There are several things here... First of all, you can use ToArrayAsync instead of ToListAsync and then ToArray, so the above can be rewritten as:

```c#
// Get all the IDs out of the database into an in-memory List
var fooIds = await context.Foo.Select(f => f.Id).ToListAsync();
// Get all the bars where 
var bars = await context.Bar.Where(b => fooIds.Contains(b.FooId)).ToListAsync();
```

However, if your goal is to query all Bars which have a valid FooId, i.e. for which a Foo exists, then you can simply write that as a single query:

```c#
var bars = await context.Bar.Where(b => context.Foo.Any(f => f.Id == b.FooId)).ToListAsync();
```

This will efficiently do the operation in one query, using a SQL subquery.

Finally, looking at this attempted query:

```c#
var bars = await context.Bar.Where(i => foos.Any(j => i.FooId == j.Id)).ToListAsync();
```

This indeed cannot be translated; `foos` is a client-side List of Foo, and SQL doesn't support this kind of query. Instead, you need to project out the IDs and use Contains on that (as you've done above).

Hope that clarifies everything.

**Comment by appec-bv** [comment]
@roji I don't think it was completely clear on what I was trying to archive. Let me explain again.

I am inserting a piece of code used to delete all chats that are bound to a user. Model doesn't seem relevant, so I'm not adding that right now.

```c#
            var chatMembers = await _context.ChatMembers.Where(i => i.ProfileId == profile.Id).ToListAsync();
            var chatMemberChatIds = chatMembers.Select(i => i.ChatId).ToArray();
            var chats = await _context.Chats.Where(i => chatMemberChatIds.Contains(i.Id)).ToListAsync();
            var chatIds = chats.Select(i => i.Id).ToArray();
            var linkedChatMember = await _context.ChatMembers.Where(i => chatIds.Contains(i.ChatId) && i.ProfileId != profile.Id).ToListAsync();
            var chatMessages = await _context.ChatMessages.Where(i => chatIds.Contains(i.ChatId)).ToListAsync();
            var chatMessageIds = chatMessages.Select(i => i.Id).ToArray();
            var chatMessageReads = await _context.ChatMessageReads.Where(i => chatIds.Contains(i.ChatId)).ToListAsync();
            var chatMessageReadsProfile = await _context.ChatMessageReads.Where(i => i.ProfileId == profileId).ToListAsync();

            _context.ChatMessageReads.RemoveRange(chatMessageReads);
            _context.ChatMessageReads.RemoveRange(chatMessageReadsProfile);
            _context.ChatMessages.RemoveRange(chatMessages);
            _context.ChatMembers.RemoveRange(linkedChatMember);
            _context.ChatMembers.RemoveRange(chatMembers);
            _context.Chats.RemoveRange(chats);
```

So like you can see from the above code it's referencing a lot of entities. In more complex scenario's it becomes way more useful to not have to convert to a array.

In your example you mentioned convert it to a `int[]` before actually getting the result. But in EF I need to provide a `List` in `RemoveRange`.

I understand that not all spaghetti code is convertible but this is just simply getting some lists that have some correlation to each other and then deleting the queries entities.

------

When working with entity framework I'd like to interact with the entities directly in my code, without having to wrap it in some sort of secondary layer. The goal of EF would be to remove the need to type difficult SQL queries. But just write simple C#. 

My request is for it to be simpler, removing an "issue" that a lot of people are facing. Rewriting the C# for it to fit SQL is not something I would except. And honestly it's one of the only issues I've had with EF.

**Comment by roji** [comment]
It seems like you're trying to implement cascade delete, where upon removal of the principal (the profile?) all the dependents are automatically deleted as well. Assuming your model is set up properly with all the relationships, EF - or the database - can take care of that for you; it would likely be much less code, and possibly also considerably faster. Take a look at the [cascade delete documentation](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete) for more details. Depending on which database you're using and how exactly the relationships are set up, the cascade delete may be doable purely in the database, in which case deleting only the principal would be enough to get rid of the whole dependent graph.
