### ISSUE TITLE
Add source of command execution to CommandEventData

### ISSUE THREAD

**Issue by Giorgi** [dotnet/efcore#24193]
EF Core interceptors fire in response to every command/query no matter whether it was a Linq query or one of the raw query methods (`FromSqlRaw`, `FromSqlInterpolated`, `ExecuteSqlRaw`, etc) The event argument passed to the interceptor method doesn't indicate the type of the query or source of the command

Proposed solution:

Add an (enum) property to `CommandEventData` indicating the source of the query/command.

Thoughts?

**Comment by ajcvickers** [comment]
Duplicate of #23719. The solution you propose seems like a good place to start if you're thinking of doing a PR.
