### ISSUE TITLE
How to tell EF to include a default-valued column in the insert query

### ISSUE THREAD

**Issue by atiyar** [dotnet/efcore#24200]
I have configured an `int` property with `.HasDefaultValue(100)`. It works as expected. Now I need to insert a value of `0` (zero) in that column - 
```
var employee = new Employee { Name = "Alice", Salary = 0 };
dbCtx.Employees.Add(employee);
dbCtx.SaveChanges();
```
But the column value remains the default one (100). I checked the generated and found that EF doesn't include the `Salary` column in the `INSERT INTO` statement.

I can understand that it makes sense in a way - from EF's perspective, setting `0` to `Salary` is equivalent to not setting any value at all, and may be what it sees is - the user didn't set a value and this column has a default value defined. Hence, it doesn't bother to include the column in the generated SQL.

So,  how can I tell EF that I'm intentionally trying to insert `0` in that column?

EF Core version: 5.0.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by anranruye** [comment]
You should change `Salary` property to nullable type.

**Comment by atiyar** [comment]
@anranruye Yes, that works. Thanks a lot.

**Comment by aureole82** [comment]
It should at least be possible to override the behavior, e.g.:
```c#
// Currently has no effect!!!
dbCtx.Entry(employee)
    .Property(item=> item.Salary)
    .IsModified = true;
```
