### ISSUE TITLE
How to limit related records EF Core 3.1 or 5 (globally or not)

### ISSUE THREAD

**Issue by LucaGabi** [dotnet/efcore#24210]
## Ask a question
How to limit related records EF Core (3.1 or 5) when using Include or ThenInclude ?

Is there a global setting on the DBContext ?

In a context like: Posts & Comments entities one post can have more then 10000 comments .. how should one handle this when loading posts and related comments ?

### Include provider and version information

EF Core version: 5.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework:  .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 latest

**Comment by roji** [comment]
You can use the filtered include feature. [The docs](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include) include an example of just that.

**Comment by LucaGabi** [comment]
Thank you .. Is there a way to do this at a global level ???

**Comment by Der-Kraken** [comment]
Global filters exists: "https://docs.microsoft.com/en-us/ef/core/querying/filters" (they should be used for something like "IsDeleted"-Flags)

What you want to filter is not clear to me. Have you an example? 
Maybe you are looking for "Coment"-Filters based on your "Post"-Instance. Then you are looking for Navigation Properties (see: https://docs.microsoft.com/en-us/ef/core/modeling/relationships#single-navigation-property)?

**Comment by ajcvickers** [comment]
@LucaGabi It's not clear to us how such a global setting would be useful. If it's about displaying only limited data, then that is typically done using Skip/Take paging in the query.

Can you provide some more details on how you would use such functionality?

**Comment by LucaGabi** [comment]
Hi @ajcvickers, having an entity with many relations and including them using include or thenInclude the data would be loaded fully from related tables right - what if I have way many rows in the realted tables .. ? 
For initial query that populates initial UI only a limited amount of data needs to be returned then specific api calls would get the next pages. I think there is something like this in OData .. maybe

**Comment by ajcvickers** [comment]
@LucaGabi Thanks for the additional info, however this is not something we are planning to implement as a global option.
