### ISSUE TITLE
Conflict with MiniProfiler

### ISSUE THREAD

**Issue by iamr8** [dotnet/efcore#24217]
## File a bug
It was more than  two months i deal with an confliction of EF Core v5 with MiniProfiler on asp core 3.1. Until yesterday i accidentally commented out a code as `services.AddEntityFrameworkCore()` and MiniProfiler started to work. Full description of following bug can be found in another issue in MiniProfiler repo. [in this link](https://github.com/MiniProfiler/dotnet/issues/543#issue-797738506)

### Include provider and version information

EF Core version: v5.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 3.1
Operating system: Windows 10 20H2
IDE: Visual Studio 16.8.5

**Comment by ErikEJ** [comment]
What is ` AddEntityFrameworkCore` - dont see that anywhere?

**Comment by iamr8** [comment]
As you at the end of line of issue that i've already written, there is a reference to [another issue](https://github.com/MiniProfiler/dotnet/issues/543#issue-797738506) i've opened in miniprofiler repo.

When i using MiniProfiler for asp core 3, i've got an IMemoryCache issue that being cleared when i have `services.AddEntityFrameworkSqlServer();` in startup.cs. I don't know what is the relation between IMemoryCache and `services.AddEntityFrameworkSqlServer();` , but after i commented out this line, MiniProfiler backs to work. And should be noticed that this issue occured i update EF Core 3.1 to EF Core v5. [Please take a look at the issue](https://github.com/MiniProfiler/dotnet/issues/543#issue-797738506)

**Comment by iamr8** [comment]
> What is ` AddEntityFrameworkCore` - dont see that anywhere?

Sorry, my bad. It is a typo. my mean is `services.AddEntityFrameworkSqlServer();`

**Comment by ajcvickers** [comment]
@iamr8 `services.AddEntityFrameworkSqlServer()` should almost never be used by application code. It's only useful if you are building the EF Core internal service provider yourself, which you should not do unless you fully understand the consequences of doing so.
