### ISSUE TITLE
Issues adding new items to owned collections

### ISSUE THREAD

**Issue by andyamacdonald** [dotnet/efcore#24223]
## Introduction

I'm probably doing something daft or unsupported here but I'm having real issues with adding items to owned collections in EF Core 5.

A typical request flow in our application is for a new appointment to be added to a booking. To do this we first load the booking from the database, add new the appointment into a collection on the booking and then save the booking. The problem seems to be that when we call `SaveChanges` on the context the newly added appointment is issuing an `UPDATE` to the database rather than an `INSERT`.

Obviously that fails because the appointment doesn't yet exist and get the following error message:

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

We know an `UPDATE` is being issued because we can see it in SQL Profiler and looking at the EF tracking data for the new appointment it's state is `Modified`.

We can get around the issue by taking the newly created appointment and manually adding it to the context e.g. `await _context.AddAsync(appointment);`. Something with that approach feels wrong, it feels like we should be able to add the new object to the collection and have it automatically saved.

### Include your code

I've included a really simplified repo below using two domain classes, `Owner` and `Owned`. The full code is also available at: [https://github.com/Medusa-Software-GitHub/ef-core-repo](https://github.com/Medusa-Software-GitHub/ef-core-repo).

```
public class Owner
{
    public Owner()
    {
        Id = Guid.NewGuid();
    }
    
    public Guid Id { get; set; }
    public string Name { get; set; }

    public List<Owned> OwnedObjects = new ();
}
```

```
public class Owned
{
    public Owned()
    {
        Id = Guid.NewGuid();
    }
    
    public Guid Id { get; set; }
    public string Description { get; set; }
}
```

My DB Context configuration:

```
public class TestContext : DbContext
{
    public TestContext(DbContextOptions<TestContext> options) : base(options)
    {
    }
    
    public DbSet<Owner> Owner { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Owner>(ConfigureOwner);
    }

    void ConfigureOwner(EntityTypeBuilder<Owner> builder)
    {
        builder.HasKey(b => b.Id);
        
        builder.Property(b => b.Name);

        builder.OwnsMany(b => b.OwnedObjects, ownedObject =>
        {
            ownedObject.HasKey(b => b.Id);
            
            ownedObject.Property(b => b.Description);
        });
    }
}
```

And finally an API controller:

```
[Route("api/[controller]")]
public class TestController : Controller
{
    private readonly TestContext _context;

    public TestController(TestContext context)
    {
        _context = context;
    }

    [HttpPost]
    public async Task<IActionResult> CreateOwner()
    {
        var owner = new Owner();
        owner.OwnedObjects.Add(new Owned());

        await _context.AddAsync(owner);
        await _context.SaveChangesAsync();

        return Ok();
    }

    [HttpPut]
    public async Task<IActionResult> UpdateOwner()
    {
        var owner = await _context.Owner.FirstOrDefaultAsync();
        owner.OwnedObjects.Add(new Owned());

        await _context.SaveChangesAsync();

        return Ok();
    }
}
```

To repo in the controller first perform a `POST` and then a `PUT`. The `await _context.SaveChangesAsync();` in the `UpdateOwner`/`PUT` operation is the one which throws the exception.

### Include provider and version information

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@andyamacdonald The issue here is that Guid keys get automatically generated values by default. With this configuration an entity with a key value already set is assumed to be an existing entity. This happens in the code above because the key is always eagerly initialized in the entity type constructor.

The fix is either to tell EF Core not to use generated keys:

```C#
ownedObject.Property(b => b.Id).ValueGeneratedNever();
```

Or to stop setting key values explicitly:

```C#
public Owned()
{
    // Id = Guid.NewGuid();
}
```

See https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#generated-versus-explicit-key-values for more information.

**Comment by andyamacdonald** [comment]
Can't believe I missed that, many thanks @ajcvickers
