### ISSUE TITLE
.UseIdentityColumn<T>(int seed , ....

### ISSUE THREAD

**Issue by reginald81** [dotnet/efcore#24222]
SQL Server admits Int64 (BIGINT)  as maximum integer numeric value for identity COLUMNS.

To use Int64 and get the maximum number of values I have to set Int64,MinValue in  seed param.

UseIdentityColumn([NotNullAttribute] this PropertyBuilder propertyBuilder, int seed = 1, int increment = 1);
The value type for the seed parameter should be set to Int64  ?!?!?!?

**Comment by ajcvickers** [comment]
Duplicate of #24840
