### ISSUE TITLE
Customizing RowNumberExpression's orderings

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#24236]
What would be the smoothest way to customize the hardcoded (why?) `(SELECT 1)` from [here](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L2206)? It sucks it's a `SqlFragmentExpression` directly. Probably only way at the moment is in `QuerySqlGenerator.VisitOrdering` and check for that hardcoded string, isn't it?

Version: 5.0.3

**Comment by smitpatel** [comment]
What do you want to insert there rather than `Select 1`?

**Comment by cincuranet** [comment]
`select 1 from rdb$databaase`. Same as why the `GeneratePseudoFromClause` exists.

**Comment by smitpatel** [comment]
Write an QueryTranslationPostProcessor visitor which visits RowNumberExpression and replaces Orderings.

**Comment by cincuranet** [comment]
But even in `QueryTranslationPostProcessor` I need to check the type (`SqlFragmentExpression`) and the string, right? It wouldn't be safe to assume all `SqlFragmentExpression` in `RowNumberExpression`'s orderings are match for replacement...

**Comment by smitpatel** [comment]
Of course you need to match the tree you are looking to replace always and anywhere in visitor.

**Comment by cincuranet** [comment]
Yeah, in that case I can do it in `QuerySqlGenerator` directly, because it's raw and simple enough. Should I file another issue to have the `(SELECT 1)` customizable?

**Comment by smitpatel** [comment]
That `SELECT 1` cannot be customizable due to design complexity. And there exist an easy way to providers to change it later so we are not looking to change current design.

**Comment by cincuranet** [comment]
OK.

BTW you have different idea of what "easy" means compared to mine. :)

**Comment by smitpatel** [comment]
Change the fragment inside SelectExpression will require deriving SelectExpression, update SqlExpressionFactory to generate the derived SelectExpression and register updated, derived services in DI. That is not easy compared to traversing an expression tree to change it the way you want.

**Comment by cincuranet** [comment]
Or the piece of string there can be a single method on a dependency, that will be injected.

**Comment by smitpatel** [comment]
Since SelectExpression is cached, it cannot take/store any dependency object. One method does take SqlExpressionFactory for generation. Since this happens inside join, effectively it will force every AddJoin and family to pass in SqlExpressionFactory which may not always be available to all users.

**Comment by cincuranet** [comment]
> Since SelectExpression is cached, it cannot take/store any dependency object.

Still solvable.


But the discussion really doesn't matter, it's not gonna be changed. I'll work around that, no problem. Over the years I learned to fit a square peg into round hole. :)

**Comment by smitpatel** [comment]
In programming, things are always solvable. There is always a crazy hack you can put into make things work. The question is never about solvability. It is about the cost of doing it that way provides enough value and is that the most appropriate way to solve wrt cost. As I mentioned above, there is other way to do the same thing which is a lot less expensive hence we went with it. In your personal opinion you can like/dislike it, your choice.
