### ISSUE TITLE
Question: Is it safe to run migrations in parallel?

### ISSUE THREAD

**Issue by richardhristov** [dotnet/efcore#24233]
Hello, I'm running a .Net App on AWS ECS and I'd like to run migrations on app startup. I'm using this method to apply the migrations on startup:

```
        private static void UpdateDatabase(IApplicationBuilder app)
        {
            using var serviceScope = app.ApplicationServices
                .GetRequiredService<IServiceScopeFactory>()
                .CreateScope();
            using var context = serviceScope.ServiceProvider.GetService<ApplicationDbContext>();
            context.Database.Migrate();
        }
```

The problem is, I'd also like to have multi A-Z availability on AWS, so I'm running multiple instances of the app at the same time, this means that when updating the app (which creates new containers) they would run the update code at the same time. Is it safe to do this or would I be risking data corruption/data loss? Is there a way to "lock" the database so that only one instance can run the migrations at the same time?

EF Core version: 5.0
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .Net 5.0
Operating system: Linux
IDE: Visual Studio

**Comment by roji** [comment]
No, it is not safe to execute migrations concurrently - as you've noted, race conditions here could cause data corruption etc. (this subject is discussed in our [migration docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli)).

Our recommendation - especially for multi-instance applications - is to not apply migrations at application startup. We recommend generating SQL scripts from your migrations, and applying them as part of your application deployment process (i.e. when a new version of your application is pushed to production).

If you choose to continue running migrations programmatically at startup, then you have to implement some sort of global database locking mechanism. This is not trivial; note that there may be other application instances running which *aren't* applying migrations, but just running normally.
