### ISSUE TITLE
What has to be handled for CompiledQueryFbTest.MakeBinary_does_not_throw_for_unsupported_operator

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#24230]
What has to be handled in provider for `CompiledQueryFbTest.MakeBinary_does_not_throw_for_unsupported_operator` to pass?

Version: 5.0.3

**Comment by roji** [comment]
@cincuranet what failure/exception are you seeing?

**Comment by cincuranet** [comment]
[Here's](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/runs/1959951795?check_suite_focus=true#step:4:989) a full error.

**Comment by roji** [comment]
What does your test implementation look like? [Here's the SQL Server one](https://github.com/dotnet/efcore/blob/main/test/EFCore.SqlServer.FunctionalTests/Query/NorthwindCompiledQuerySqlServerTest.cs#L337), you should probably have the same.

**Comment by cincuranet** [comment]
I was using whatever was in `base`. I wasn't expecting to have such failing test. Thanks.

**Comment by roji** [comment]
Always good to look at SQL Server (and/or Npgsql) when you get a failing test. Though I agree that it's not ideal. @maumar @smitpatel any specific reason all those translation failure assertions can't be implemented in the base?

**Comment by smitpatel** [comment]
Support of ArrayIndex operation is provider dependent and provider should verify error if it is not supported.

**Comment by roji** [comment]
[Even I have to override that test :rofl:](https://github.com/npgsql/efcore.pg/blob/main/test/EFCore.PG.FunctionalTests/Query/NorthwindCompiledQueryNpgsqlTest.cs#L23)...
