### ISSUE TITLE
InvalidOperationException is missing from exceptions list.

### ISSUE THREAD

**Issue by krt-** [dotnet/efcore#24242]
InvalidOperationException is missing from the docs when sequence contains no elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae58e80-e159-5636-3e7a-c5b4d902f0ff
* Version Independent ID: 82ae1327-81c5-92c7-6be8-4f50bc03c6d0
* Content: [EntityFrameworkQueryableExtensions.MaxAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.MaxAsync?view=efcore-5.0&viewFallbackFrom=netstandard-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Note: submitted https://github.com/dotnet/dotnet-api-docs/pull/5380 to fix the .NET docs for Queryable.Max (Enumerable.Max is fine).
