### ISSUE TITLE
Migration wants to drop a table for a stored procedure.

### ISSUE THREAD

**Issue by wjones-BradfordWhite** [dotnet/efcore#24243]
I have tried Core 3 and 5, but migration wants to drop and create for models only used for stored procedures. I fell like I have tried everything, but migration still want to drop the table.

Model:
```C#
[Keyless]
[NotMapped]
public class Warranty_Calculation
{
        public string I_SERIAL_NUMBER { get; set; }
}
```
Context:
```C#
public virtual DbSet<Warranty_Calculation> Warranty_Calculations { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
            modelBuilder.Entity<Warranty_Calculation>(entity =>
            {
                entity.HasNoKey().ToView(null);
            });
}
```

I have also tried:
```C#
modelBuilder.Ignore<Warranty_Calculation>();
```

When I add-migration it shows:
```C#
protected override void Up(MigrationBuilder migrationBuilder)
{
        migrationBuilder.DropTable(name: "Warranty_Calculation");
}

protected override void Down(MigrationBuilder migrationBuilder)
{
         migrationBuilder.CreateTable(name: "Warranty_Calculation",
columns: table => new
                {
                    I_SERIAL_NUMBER  = table.Column<string>(type: "nvarchar(max)", nullable: true),
                },
                constraints: table =>
                {
                });
}
```

I have even created the table in the database and update-database. It run and drops the tables, but the next time I add-migration it wants to drop the table again. I am really at a lose here.

EF Core version: 5.0.3
Database provider: (Microsoft.EntityFrameworkCore.SqlServer) 5.0.3
Target framework: (.NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.8.5)

**Comment by ajcvickers** [comment]
@wjones-BradfordWhite You are likely looking for `ToTable(null)`. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#toview-is-treated-differently-by-migrations and https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#totablenull-marks-the-entity-type-as-not-mapped-to-a-table

**Comment by wjones-BradfordWhite** [comment]
I tested adding:
```C#
modelBuilder.Entity<Warranty_Calculation>(entity =>
            {
                entity.HasNoKey().ToTable(null);
                entity.HasNoKey().ToView(null);
            });
```

And the same issue persist. Migration still wants to drop tables for models used in Stored Procedures.

**Comment by AndriySvyryd** [comment]
@wjones-BradfordWhite Try
```C#
modelBuilder.Entity<Warranty_Calculation>(entity =>
            {
                entity.HasNoKey().ToTable("NonExistingTable", t => t.ExcludeFromMigrations());
            });
```

**Comment by wjones-BradfordWhite** [comment]
AndriySvyryd,
      Bingo! That did it. 
```C#
modelBuilder.Entity<Warranty_Calculation>(entity =>
            {
                entity.HasNoKey().ToTable("Warranty_Calculation", t => t.ExcludeFromMigrations());
            });
```

Thank you for the help!
