### ISSUE TITLE
Incorrect many to many tablename with entity.DisplayName

### ISSUE THREAD

**Issue by DominicSachs** [dotnet/efcore#24253]
It seems there is bug for generating many to many table names with the usage of entity.SetTableName(entity.DisplayName()). I have two many to many relationships. One has the correct table name and one has a table name like this "ClientUser (Dictionary<string, object>)"

```C#
builder.HasMany(b => b.Users).WithMany(b => b.Clients)
                .UsingEntity<Dictionary<string, object>>("ClientUser",
                                                         x => x.HasOne<User>().WithMany().HasForeignKey("UserId"),
                                                         x => x.HasOne<Client>().WithMany().HasForeignKey("ClientId"));

builder.HasMany(b => b.CustomerServiceGroupings).WithMany(b => b.Clients)
                .UsingEntity<Dictionary<string, object>>("CustomerServiceClientGrouping",
                                                         x => x.HasOne<CustomerServiceGrouping>().WithMany().HasForeignKey("GroupingId"),
                                                         x => x.HasOne<Client>().WithMany().HasForeignKey("ClientId"));


```

Generated:
```C#
modelBuilder.Entity("ClientUser", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ClientUser (Dictionary<string, object>)");
                });

            modelBuilder.Entity("CustomerServiceClientGrouping", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("GroupingId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "GroupingId");

                    b.HasIndex("GroupingId");

                    b.ToTable("CustomerServiceClientGrouping");
                });
```

Code for reproduction: https://github.com/DominicSachs/ef-many-many/blob/master/src/MigrationTableNames/Migrations/TestDbContextModelSnapshot.cs#L33

### provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows

**Comment by ajcvickers** [comment]
@DominicSachs Using the display name of the [property bag entity types](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties#property-bag-entity-types) used for [many-to-many join entities](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many) to set the table name is not appropriate. The display name is intended to be a human-readable representation of the entity type, not something that should be used to identify it code or the database.

**Comment by DominicSachs** [comment]
@ajcvickers  I don't get it. I tried to use

`builder.HasMany(b => b.Users).WithMany(b => b.Clients).UsingEntity(e => e.ToTable("ClientUser");`

Now I see the correct (singular) table names but column names are ClientsId and UsersId. I also want singular colum names like ClientId and UserId. 

What ist the correct way to generate a m:n relation with singular table and singular colmun names (without a separate CLR join entity)? Maybe something like the EF 6 MapLeftKey and MapRightKey methods?

I also tried this

```
builder.HasMany(b => b.Users).WithMany(b => b.Clients).UsingEntity(e =>
{
    e.ToTable("ClientUser");
    e.HasOne(typeof(User)).WithMany().HasForeignKey("UserId");
    e.HasOne(typeof(Client)).WithMany().HasForeignKey("ClientId");
});

```
But this generates 4 columns (UsersId, ClientsId, UserId and ClientId).

**Comment by AndriySvyryd** [comment]
You need to configure the underlying FKs in separate parameters:

```C#
builder.HasMany(b => b.Users).WithMany(b => b.Clients)
                .UsingEntity<Dictionary<string, object>>("ClientUser",
                                                         x => x.HasOne<User>().WithMany().HasForeignKey("UserId"),
                                                         x => x.HasOne<Client>().WithMany().HasForeignKey("ClientId"),
                                                         e => e.ToTable("ClientUser"));
```
