### ISSUE TITLE
Question about customizing the migration code in designer and model snapshot files.

### ISSUE THREAD

**Issue by Chakrygin** [dotnet/efcore#24257]
Hi!

The documentation (https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli) says that the migration files generated through `dotnet ef migration add <name>` can be customized.
However, it's not entirely clear, I need to change only `*.cs` files or `*.cs` files, `*.Designer.cs` files and ModelSnapshot file?

For example, I have the following data model:

```
public sealed class MyContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder model)
    {
        model.Entity<Item>();
        model.Entity<Cart>(cart =>
        {
            cart.OwnsMany(x => x.Items, item =>
            {
                item.HasKey(x => new {x.CartId, x.ItemId});
                item.HasOne<Item>()
                    .WithMany()
                    .HasForeignKey(x => x.ItemId)
                    .HasPrincipalKey(x => x.Id);
            });
        });
    }
}

public sealed class Item
{
    public Guid Id { get; set; }
}
public sealed class Cart
{
    public Guid Id { get; set; }
    public List<CartItem> Items { get; set; }
}
public sealed class CartItem
{
    public Guid CartId { get; set; }
    public Guid ItemId { get; set; }
    public int Quantity { get; set; }
}
```

When I create a migration for this model, I get the following code:

```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
        name: "Cart",
        /* ... */);

    migrationBuilder.CreateTable(
        name: "Item",
        /* ... */);

    migrationBuilder.CreateTable(
        name: "CartItem",
        /* ... */);

    migrationBuilder.CreateIndex(
        name: "IX_CartItem_ItemId",
        table: "CartItem",
        column: "ItemId");
}
```

This code creates `IX_CartItem_ItemId` index that I do not need and I want to delete it. How to do it right?
1. Remove `CreateIndex` call from `Up` method only.
2. Remove `CreateIndex` call from `Up` method and `HasIndex("ItemId")` calls from Designer and ModelSnapshot files.

In the second case, since one change is actually being made in multiple places, what potential problems could arise if a developer forgets to do it or does it wrong?

Overall, is editing Designer and ModelSnapshot files normal practice?

**Comment by roji** [comment]
Your model snapshot (and migration designer file) are basically snapshots of your model at the current state, and are used by EF Core to know which changes have occurred *in your model*. That means that if you remove a CreateIndex directive from your model snapshot, the next time you create a new migration, EF Core will include that CreateIndex again. In general, both your model snapshot and Designer file are considered generated code that users aren't expected to touch under normal circumstances.

So the normal practice is to only remove something from your migration file (which it's perfectly fine to edit once it's scaffolded). If you remove CreateIndex from there but leave it in the model snapshot, EF Core won't attempt to introduce it again the next time you create a migration.
