### ISSUE TITLE
Terminate flag ignored when scripting a create table in SqlServerMigrationsSqlGenerator

### ISSUE THREAD

**Issue by nl-za** [dotnet/efcore#24254]
I am trying to add custom SQL to the create table section in the script generated when executing Script-Migration. When overriding the `Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder, bool terminate = true)` method in SqlServerMigrationsSqlGenerator, the `terminate` boolean flag is ignored and the `EndCommand` method is called. This results in the command being flushed from the command builder and added to the commands list.

https://github.com/dotnet/efcore/blob/6e45ea2e967e0e7fe575f61e91fe83d1dbef30ba/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L583

No check whether the command should be terminated or not:

```C#
builder.EndCommand(suppressTransaction: memoryOptimized);
```
Other Generate methods for different types of operations perform a check similar to this:

```C#
  if (terminate)
  {
      builder
          .AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator)
          .EndCommand(suppressTransaction: memoryOptimized);
  }
```

### Include provider and version information

EF Core version: 3.1.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 
IDE: Visual Studio 2019 16.3.8

**Comment by roji** [comment]
Poaching
