### ISSUE TITLE
dbcontext scaffold falsely states: "Missing required argument '<PROVIDER>'."

### ISSUE THREAD

**Issue by rbenjes** [dotnet/efcore#24251]
Entity Framework Core .NET Command-line Tools 6.0.0-preview.1.21102.2

Calling

`dotnet ef dbcontext scaffold "context" provider`

results in error message

`Missing required argument '<PROVIDER>'.`

Obviously that is not the case.

This behavior did not occur in the previous version (5.0.?).

Output with option --verbose:
`dotnet exec --depsfile D:\Source\Workspaces\Test\DbNQCore\DbNQCore\bin\Debug\net5.0\DbNQCore.deps.json --additionalprobingpath C:\Users\rbenjes\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" C:\Users\rbenjes\.dotnet\tools\.store\dotnet-ef\6.0.0-preview.1.21102.2\dotnet-ef\6.0.0-preview.1.21102.2\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold connection Microsoft.EntityFrameworkCore.SqlServer --assembly D:\Source\Workspaces\Test\DbNQCore\DbNQCore\bin\Debug\net5.0\DbNQCore.dll --startup-assembly D:\Source\Workspaces\Test\DbNQCore\DbNQCore\bin\Debug\net5.0\DbNQCore.dll --project-dir D:\Source\Workspaces\Test\DbNQCore\DbNQCore\ --language C# --working-dir D:\Source\Workspaces\Test\DbNQCore\DbNQCore --verbose --root-namespace DbNQCore
Microsoft.EntityFrameworkCore.Tools.CommandException: Missing required argument '<PROVIDER>'.
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Validate()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Missing required argument '<PROVIDER>'.`

**Comment by ajcvickers** [comment]
@bricelam I am able to reproduce this. Looks like .NET 6 is breaking the dotnet-ef tool.

**Comment by bricelam** [comment]
```sh
dotnet exec ...\ef.dll dbcontext scaffold connection Microsoft.EntityFrameworkCore.SqlServer
```
Weird stuff. The first three arguments are definitely getting parsed... I'll need to debug to fully understand what's going on.

**Comment by dsplaisted** [comment]
We switched to a new command line parser for .NET 6 so that's likely related.

@sfoslund Can you look at this?

**Comment by sfoslund** [comment]
I'm not able to repro this issue with 6.0.100-preview.2.21120.3 and dotnet-ef version 5.0.3, it's possible that it was fixed by one of the changes that didn't make it into preview 1. @ajcvickers were you also reproducing with preview 1?

**Comment by ajcvickers** [comment]
@sfoslund Yes, I also used preview 1.

**Comment by sfoslund** [comment]
Great, unless anyone can repro this with preview 2 it can probably be closed as fixed.

**Comment by ajcvickers** [comment]
@sfoslund Thanks. We will verifiy with preview 2.

**Comment by bricelam** [comment]
It's not related to the recent SDK changes. This was caused by some bad code cleanup in PR #22625.

**Comment by IvanFarkas** [comment]
Yeah. Preview 2 still does this. We'll wait for the next one patently ;-)

**Comment by ajcvickers** [comment]
@IvanFarkas I suspect going back to the 5.0 tool will work. The tool itself is a thin wrapper and is designed to be as forward compatible as possible.

**Comment by ooples** [comment]
I'm getting this error with preview 2 so I can confirm that the error is still happening

**Comment by ooples** [comment]
I tried going back to 5.0 and for some reason it still gave me the same error for the package manager console but it worked for the command line interface

**Comment by vijaylaxmi13** [comment]
> I tried going back to 5.0 and for some reason it still gave me the same error for the package manager console but it worked for the command line interface

Please install the 5.0.0 version and close the visual studio and re-open
then run the command from package manager console. 
This worked for me.

**Comment by sanjusjk** [comment]
I too faced the same issue with .Net 5.0, Please make sure below are done.

1) Make Sure the Project which has EF core reference is set as Start up project. In my case, I have a .Net core class library with EF core installed.
2) try the scaffolding in below format. remove User ID and Password if using Windows auth mode.

scaffold-dbcontext -provider Microsoft.EntityFrameworkCore.SqlServer -connection "Server=(localdb)\MSSQLLocalDB;Database=EFCoreMigration;Trusted_Connection=True;user id=test;password=test;” -OutputDir Models
 
This worked for me, pleased let me know the feedback
