### ISSUE TITLE
Split Queries and (Nested) Owned Entities

### ISSUE THREAD

**Issue by CzechsMix** [dotnet/efcore#24266]
I see that the documentation for split queries specifies that `Include` must be used, but that doesn't explain how it works with owned entities.

Do owned entities behave _as thought_ Include was used, or do they actually apply it under the hood?

Would setting default split queries globally apply to owned entity collections?

Is there anyway to combine both these features?

**Comment by smitpatel** [comment]
As described in [documentation](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#querying-owned-types) owned types are included by default without specifying `Include`. So in that respect, the final effect is same as a manual `Include` was specified. So if you are using split query then owned collections will be loaded in a separate query automatically.
