### ISSUE TITLE
CollectionWithoutComparer error message has class and property backwards

### ISSUE THREAD

**Issue by mqudsi** [dotnet/efcore#24264]
The error message 10620 generated for `Microsoft.EntityFrameworkCore.Model.Validation.CollectionWithoutComparer` has the parameters for class name and property name switched around, generating log messages (warnings) like

>  The property 'Tags.RegistrationDocument' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.

Where `RegistrationDocument` is the class and `Tags` is the collection with a DbValueConverter but not DbValueComparer.

### Include provider and version information

EF Core version: 5.0.1
Database provider: Npgsql 5.0.0
Target framework: .Net 5
Operating system: Server 2019
IDE: N/A

**Comment by AndriySvyryd** [comment]
All warning messages with explicit parameter order (e.g. '1_entityType') don't respect it.
