### ISSUE TITLE
Allow nullable column for none-nullable property, backed by nullable field

### ISSUE THREAD

**Issue by mythjuha** [dotnet/efcore#24270]
In my model I have a nullable field, where as the corresponding property is none-nullable. When calling the getter and the getter sees the field is null, it returns a value from a parent navigational property. This means the database column should be nullable.

EF core however doesn't allow me to make the column optional. Any suggestions?

```
private Int? _value;

public Int Value
{
      get
      {
            if (_value== null)
                   return Parent.Value;
            else
                   return _value;
      }
      set
      {
            _value= value;
      }
}



mapping.Property(o => o.Value).IsRequired(false).HasField("_value");
```

---> System.InvalidOperationException: The property 'Value' cannot be marked as nullable/optional because the type of the property is 'integer' which is not a nullable type. Any property can be marked as non-nullable/required, but only properties of nullable types can be marked as nullable/optional.

**Comment by sjb-sjb** [comment]
Maybe you can mark the Value property as [NotMapped]. Given that the backing field _value is stored in the database, it seems to me that you do not also have to store the property.

**Comment by mythjuha** [comment]
> 
> 
> Maybe you can mark the Value property as [NotMapped]. Given that the backing field _value is stored in the database, it seems to me that you do not also have to store the property.

Doesn't EF Core store 'properties' and just allow you to set a field to prevent it from using getters/setters? If I add a NotMapped attribute to the property then field won't be stored either.

**Comment by anranruye** [comment]
try
```C#
private Int? _value;

[NotMapped]
public Int Value
{
      get
      {
            if (_value== null)
                   return Parent.Value;
            else
                   return _value;
      }
      set
      {
            _value= value;
      }
}


mapping.Property("_value");
```

**Comment by ajcvickers** [comment]
@mythjuha This mapping should work on EF Core 5.0. (My code where I tested this is below.) It will not work on EF Core 3.1 since support was added in #15182.

That being said, I would recommend against creating a property where the database entity can return a different value than the database column to which it is mapped. When you use this property in a query it will just use the value in the database column. Also, it will confuse EF Core change tracking if the value changes while the entity is being tracked. EF Core will detect this change and attempt to update the database column on SaveChanges, which at best could be unecessary.

```C#
public class Blog
{
    public int Id { get; set; }
    
    public ICollection<Post> Posts { get; set; }
    
    public int Value { get; set; }
}

public class Post
{
    public int Id { get; set; }
    
    public Blog Parent { get; set; } 
    
    private int? _value;

    public int Value
    {
        get
        {
            if (_value== null)
                return Parent.Value;
            else
                return (int)_value;
        }
        set
        {
            _value= value;
        }
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog {Posts = new List<Post> {new Post()}});
            context.SaveChanges();
        }
    }
}

public class SomeDbContext : DbContext
{
    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .UseLoggerFactory(ContextLoggerFactory)
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }
}
```

**Comment by mythjuha** [comment]
Just giving a sign of life here:
I'll get to testing the suggested solutions ASAP and report back here. Been a hell of a ride porting my .net 4.6 project to .net 5.0. Been needing to replace and update many other libraries other than my ORM, resulting in a lot of breaking changes.

@ajcvickers I'm using .net 5.0. But in my project it tries to create the 'Post' value column as not-nullable. Maybe because i'm using fluentmapping with OnModelCreation. I'll look into this asap and try out your sample first and then look for the differences.

**Comment by sjb-sjb** [comment]
Combining the responses above, what you might do is create a separate data property, say LocalValue, and then mark Value as NotMapped.

**Comment by mythjuha** [comment]
@ajcvickers If i start an empty solution, using the 'Getting started' guide, targeting .net 5.0, I'm not getting the correct results. The 'Value' column of the 'Posts' table is not nullable while it should be.

```migrationBuilder.CreateTable(
                name: "Posts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ParentId = table.Column<int>(type: "INTEGER", nullable: true),
                    Value = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Posts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Posts_Blogs_ParentId",
                        column: x => x.ParentId,
                        principalTable: "Blogs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });
```

Trying to force it using OnModelCreating and setting IsRequired(false) throws the error during the creation of the migration.

Using a local value as proposed by @sjb-sjb for now seems to be the best solution. But I believe its kind of odd to allow passing a 'false' value to 'IsRequired' if it fails anyway.

**Comment by sjb-sjb** [comment]
You didn’t show your entity declaration, did you have

    public int? LocalValue { get; private set; }
    [NotMapped] public int Value {
        get => (this.LocalValue ?? this.Parent?.Value) ?? throw new InvalidOperationException(); 
        set => this.LocalValue = value;
    }

Notice the ? on the declaration of LocalValue should result in it being nullable.

**Comment by mythjuha** [comment]
@sjb-sjb Your proposal works. My code was to show the migration output created by Ajvickers' proposal.
