### ISSUE TITLE
Alternative to Telerik FetchStrategy for eager loading?

### ISSUE THREAD

**Issue by mythjuha** [dotnet/efcore#24273]
I'm currently migrating from Telerik Data Access.

Is there an EF core alternative to the following method used by 'Telerik Data Access' to define eager loading? I find this implementation to be quicker/simpler then the 'Include/ThenInclude' method. Especially when wanting to load multiple properties of an already navigational property.

```
            var fetchStrategy = new Telerik.OpenAccess.FetchOptimization.FetchStrategy();
            fetchStrategy.LoadWith<Course>(c => c.CourseEvents);
            fetchStrategy.LoadWith<Course>(c => c.PersonRegistrations);
            fetchStrategy.LoadWith<PersonCourseRegistration>(r => r.Person);
            fetchStrategy.LoadWith<PersonCourseRegistration>(r => r.Attendances);
            fetchStrategy.LoadWith<PersonCourseRegistration>(r => r.EmployerRegistration);
            fetchStrategy.LoadWith<Person>(p => p.Employers);
            fetchStrategy.LoadWith<EmployerService>(m => m.Role);
            fetchStrategy.LoadWith<EmployerCourseRegistration>(r => r.Employer);

            var courses = this.Database.GetAll<Course>()
                                  .LoadWith(fetchStrategy)
                                  .ToList();
````

**Comment by roji** [comment]
It seems like you're looking for [explicit loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data/explicit), though I'm not familiar with Telerik Data Access so I could be wrong. Though be aware of adding extra unneeded database roundtrips with this kind of technique - this makes especially little sense with one-to-one (reference) navigations, where eagerly loading with Include is more efficient.

If this doesn't correspond to what you're looking for, please post a more complete description of what you need.

**Comment by ajcvickers** [comment]
@mythjuha This feature is tracked by #2953.
