### ISSUE TITLE
Is EF7 not support Full Framework?

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#2427]
Hi !
I want to write a nuget package use asp.net 5 class library projectTemplate, for let it compatible with both Full Framework and DNX. I add "net45" to project.json file like this:

``` JSON
"frameworks": {
    "net45": { },
    "dnx451": {
      "dependencies": {
      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-22816",
        "System.Linq": "4.0.0-beta-22816",
        "System.Threading": "4.0.10-beta-22816",
        "Microsoft.CSharp": "4.0.0-beta-22816",
      }
    }
```

After this, most refrenced package are work fine, such as "Microsoft.Framework.XXX", "System.Reflection", except EntityFramework7, too many codes has problems, like "AsSqlServer()", "AsRelational()". I saw the description of EF package on NUGET website says it is  support NET 4.5.1, did not finish it?

BTW: Forgive my bad English!

**Comment by rowanmiller** [comment]
Hi,

The relational parts of EF7 require .NET 4.5.1 as a minimum. To use them you will need to target net451 rather than net45.

~Rowan

**Comment by endink** [comment]
Hi,
thanks, problem solved!
