### ISSUE TITLE
Include Filter not working as expected

### ISSUE THREAD

**Issue by MauricioArroyo** [dotnet/efcore#24285]
Hi,
Thanks in advance for the help. 

I am facing an issue with the new Include filter on EF Core 5. 

Using a context instance to add a child entity X (a post in this case), but later filtering the childs (where X will be excluded) still returns X.

If I use a different context instance it works as expected. If I get the entities as NoTracking, it works as expected.

I created a small console (.net 5.0) with the blog/posts example to reproduce it. 

Am I missing something?

```C#
public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public List<Post> Posts { get; set; }
}

static void Main(string[] args)
{
    using var context = new Context();
    context.Blogs.Add(new Blog()
    {
        Url = "http://test.com/url",
        Posts = new List<Post>
        {
            new Post
            {
                Content = "content",
                Title = "title",
            }
         }
    });
    context.SaveChanges();
    var blogs = context.Blogs
        .Include(e => e.Posts.Where(p => p.Title.Contains("Cheese"))).ToList();
    //At this point the blog HAS the post even not matching the where clause
    blogs = context.Blogs.AsNoTracking()
       .Include(e => e.Posts.Where(p => p.Title.Contains("Cheese"))).ToList();
    //At this point the blog DO NOT have the post because I am using AsNoTracking
    //Another context instance will filter correctly
}
```
 
EF Core version:
Database provider: I tried InMemory and SqlServer, same result
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.8.3

**Comment by anranruye** [comment]
This is because the `Blog` instance you add to the context and the instance you query from db is the same instance:
```C#
    using var context = new Context();
    var blog = new Blog()
    {
        Url = "http://test.com/url",
        Posts = new List<Post>
        {
            new Post
            {
                Content = "content",
                Title = "title",
            }
         }
    };
    context.Blogs.Add(blog);
    context.SaveChanges();
    var blogs = context.Blogs
        .Include(e => e.Posts.Where(p => p.Title.Contains("Cheese"))).ToList();
    Console.WriteLine(blog == blogs[0]); //output: true
    blogs = context.Blogs.AsNoTracking()
       .Include(e => e.Posts.Where(p => p.Title.Contains("Cheese"))).ToList();
    Console.WriteLine(blog == blogs[0]); //output: false
    //Another context instance will filter correctly
```

**Comment by kourosko** [comment]
> This is because the `Blog` instance you add to the context and the instance you query from db is the same instance:
> 
> ```cs
>     using var context = new Context();
>     var blog = new Blog()
>     {
>         Url = "http://test.com/url",
>         Posts = new List<Post>
>         {
>             new Post
>             {
>                 Content = "content",
>                 Title = "title",
>             }
>          }
>     };
>     context.Blogs.Add(blog);
>     context.SaveChanges();
>     var blogs = context.Blogs
>         .Include(e => e.Posts.Where(p => p.Title.Contains("Cheese"))).ToList();
>     Console.WriteLine(blog == blogs[0]); //output: true
>     blogs = context.Blogs.AsNoTracking()
>        .Include(e => e.Posts.Where(p => p.Title.Contains("Cheese"))).ToList();
>     Console.WriteLine(blog == blogs[0]); //output: false
>     //Another context instance will filter correctly
> ```
Tested your answer and still not working. The issue is still valid.

**Comment by ajcvickers** [comment]
@MauricioArroyo I believe @anranruye was correct with their answer. If this still isn't working when you have changed the code to not query from the same context to which you added the entity, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

See also the change-tracking docs: https://docs.microsoft.com/en-us/ef/core/change-tracking/

**Comment by MauricioArroyo** [comment]
Thank y'all. I think the fact that I had the filtering on the Include made me overlook the fact that they are the same instance. I should have noticed than once I tried with the second context.
Thanks for the clarification!
