### ISSUE TITLE
Decide what to do about Exists

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#2428]
We decided to remove all the fine-grained relational methods, including Exists, from the top-level API, but both Diagnostics and Templates are using Exists in conjunction with ApplyMigrations as a heuristic as to whether or not to call ApplyMigrations. We should decide:
- Is this an appropriate use of Exists?
- If so, should it be exposed at the top level?
- If so, should it be a relational or core concept and what should the method be called if it is relational only?

**Comment by rowanmiller** [comment]
Couple of data points:
We are removing the use of Exists from the templates.
I think it's ok for Diagnostics to drop down to a lower level API.

**Comment by ajcvickers** [comment]
@rowanmiller Do you think that in a store app it will be common for people to want to use the Exists/ApplyMigrations pattern? Did you do this in your app?

**Comment by rowanmiller** [comment]
I just applied migrations without checking for existence... I think that is what folks will want to do since migrations takes care of creating if needed (and no-ops if everything is up to date).

**Comment by ajcvickers** [comment]
@rowanmiller That's what I thought but wanted to check I wasn't missing something. Thanks!
