### ISSUE TITLE
auto add comment

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#24289]
When generating the migration script, can comments be automatically added to the database field through the "summary" content in the XML document?

**Comment by bricelam** [comment]
Unfortunately, getting access to the XML comments at runtime isn't always possible...

I can imagine someone creating an extension containing a source generator that turns them into `[Comment]` attributes which EF could then use, but given the current limitations of source generators, they'd probably also need to implement #14544 first.

**Comment by Varorbc** [comment]
this is my current implementation

```
        private void SetComment(ModelBuilder modelBuilder)
        {
            var entityTypes = modelBuilder.Model.GetEntityTypes();
            foreach (var item in entityTypes)
            {
                var type = item.ClrType;
                var summary = type.GetXmlDocsSummary();
                if (!string.IsNullOrEmpty(summary))
                {
                    item.SetComment(summary);
                }

                var typeProperties = type.GetProperties();

                var properties = item.GetProperties();
                foreach (var property in properties)
                {
                    summary = typeProperties.FirstOrDefault(a => a.Name == property.Name)
                                            ?.GetXmlDocsSummary();
                    if (!string.IsNullOrEmpty(summary))
                    {
                        property.SetComment(summary);
                    }
                }
            }
        }
```

**Comment by ajcvickers** [comment]
@Varorbc We discussed this again, but we don't think this is something we want to build in to EF Core. It might make a good extension for people who have XML comments available and want to use them in this way.

**Comment by Varorbc** [comment]
@ajcvickers Is it possible to add comments by SourceGenerator?
