### ISSUE TITLE
Deleting a parent entity yields to error: Cannot insert explicit value for identity column in table 'XXXXX' when IDENTITY_INSERT is set to OFF."

### ISSUE THREAD

**Issue by brbmimapl2** [dotnet/efcore#24296]
I think I ran across an interesting problem with Entity Framework Core 5 while doing a unit test on SQL Server. My tables are set to cascade deletions.

I have a parent table that I inserted a row into. Everything went fine.

Now I specifically inserted an entity in the child table with a value for the column Id and the parent ID as foreign key. The insert failed as expected with error **_"Cannot insert explicit value for identity column in table 'XXXXX' when IDENTITY_INSERT is set to OFF."._** Then things took a turn for the worse at that point.

I tried to delete the parent row. SQL Server yells at me that I still cannot insert into the child table while INDENTITY_INSERT is off. The same error I got with the invalid insert. I am surmising that the cascade deletion is kicking in but since I was not successful at inserting a row in the child table with the parent PK there should have been no issue. 

_Anybody has run into such problem before?_

**Comment by anranruye** [comment]
Do you use the same dbcontext instance all the time?

**Comment by brbmimapl2** [comment]
I don't but sometimes the same context is reused and that was the root of the problem. I will close this issue.

**Comment by brbmimapl2** [comment]
Closing this. It was a dbcontext reuse isssue. Refactored my code to use a brand `new context and the problem went away.,
