### ISSUE TITLE
Instrumentation - Query count per context instance

### ISSUE THREAD

**Issue by cjbhaines** [dotnet/efcore#24299]
Hi EF Team!

I have a feature request around diagnostics / instrumentation please.

I am trying to instrument EF by inspecting how many queries are made per context instance. We generally don't expect more than 10-20 or so queries on a given context instance. I want to use this to check to see if a context has been misused, such as making query calls inside a loop, which leads to obvious performance issues (we recently had this sneak through to Production).

The closest thing I can find is using is using Diagnostic Listeners for the event id: RelationalEventId.CommandExecuted.Name, however there is no reference to the context in the event data to be able to track this on a per context basis. Event Counters are not really a viable solution either because they are global counters.

I basically want an interception point / diagnostics hook to be able to say that if the number of queries against any given context instance is > X, then log an error or even throw an exception. This would allow us to catch any misuse scenarios that have slipped through PRs in units tests or in test environments.

Let me know what you think / if this is already possible. Thanks!

**Comment by ajcvickers** [comment]
@cjbhaines [CommandExecutedEventData](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.commandexecutedeventdata?view=efcore-5.0) exposes the DbContext being used as the `Context` property.

**Comment by cjbhaines** [comment]
@ajcvickers ah I hadn't seen that, thank you very much! That gives me everything I need. 

We are currently still on 2.2 and it doesn't exist there so I missed it, we are currently upgrading to 5 so that solves it. 

Appreciate your quick response!
