### ISSUE TITLE
[FYI] ef tools on WLS remote in VSCode terminal are not working

### ISSUE THREAD

**Issue by pnmcosta** [dotnet/efcore#24298]
I'm actually not sure if this is a bug with ef core tools or VSCode's WSL remote terminal integration or whatnot.

Just posting here more as an FYI, if you try to run `dotnet ef` from within a remote WSL 2 terminal (Ubuntu in this case) with all the dependencies properly installed it will fail (bottom terminal):

![image](https://user-images.githubusercontent.com/550684/109416805-4e53f300-79b8-11eb-8c78-959066b628d9.png)

However, that is not the case if you connect to the WSL directly (upper terminal). It's not location/project based either, as there's nothing on my `~/` directory.

If this should instead be posted elsewhere let me know.

Thanks,
P.

**Comment by AndriySvyryd** [comment]
@bricelam to follow up

**Comment by bricelam** [comment]
I'm not able to repro this. My Versions:

* Windows 10 20H2
* Ubuntu 20.04
* VS Code 1.53.2
* Remote - WSL 0.53.4
* .NET SDK 5.0.103
* EF Core 5.0.3

**Comment by pnmcosta** [comment]
Sorry, might have been a red herring! Just tested it today and it is working fine too now, must have needed a full system shutdown, I did try `wsl --shutdown` yesterday before posting! 😬 😂

**Comment by bricelam** [comment]
I suspect it was a PATH issue. Glad you were able to get it working.
