### ISSUE TITLE
EF Core memory usage is high 

### ISSUE THREAD

**Issue by NZE** [dotnet/efcore#24301]
We noticed that Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache, which retains 51.33 MB in 884.2 K objects
~70% of the ram of our app using.
![image](https://user-images.githubusercontent.com/8453597/109436600-6b4dfc00-7a74-11eb-9c52-f2e45d0160cd.png)

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: ( .NET 5.0)
Operating system: (Win server 2016 datacenter)
IDE: (Version 16.9.0 Preview 5.0)
EF Core: 5.0
Memory dump can be provided if needed.

**Comment by roji** [comment]
@NZE can you please post a minimal code sample for how you're configuring your context? This is likely a result of a mis-configuration, causing a service provider to get allocated for each context instance.

**Comment by ajcvickers** [comment]
@roji You don't say which version of EF Core you are using. We made it harder to get into this state in 3.1, so if you are not using EF Core 3.1 or 5.0, then please update. If that doesn't work, then as @roji says, we will need to see code. This is likely to be something in OnConfiguring and/or AddDbContext.

**Comment by NZE** [comment]
@ajcvickers @roji thanks guys will post a code sample. Cheers

**Comment by AndriySvyryd** [comment]
Closing this until a small repro project is provided.
