### ISSUE TITLE
InvalidOperationException is missing from exceptions list for a lot of Queryable extensions

### ISSUE THREAD

**Issue by Marusyk** [dotnet/efcore#24307]
The issue is the same as #24242 but related to other extension methods:

- AnyAsync
- CountAsync
- LongCountAsync
- FirstOrDefaultAsync
- LastOrDefaultAsync
- SingleAsync
- MinAsync
- SumAsync
- AverageAsync

We need to add something like:

`/// <exception cref="InvalidOperationException"> <paramref name="source" /> contains no elements. </exception>`

and submit changes to https://github.com/dotnet/dotnet-api-docs

**Comment by roji** [comment]
@Marusyk you're right that MinAsync seems to be missing the exception doc. But the other methods you mention seem to already have the doc, or aren't supposed to throw InvalidOperationException when the source contains no elements - can you please confirm?

For MinAsync, would you like to submit PRs both here and to dotnet-api-docs?

**Comment by Marusyk** [comment]
Let me check again.

Also, I found this code
https://github.com/dotnet/efcore/blob/01adefda72edc4d91ed3931e5b603f02331d0a33/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2853-L2880
each of that methods calls this. should it also be added to docs?

**Comment by roji** [comment]
> should it also be added to docs?

I don't think so - this gets thrown if the user erroneously uses these EF Core operators non a non-EF queryable. That would be a bit like documenting NullReferenceException everywhere where a user might pass a null although the method is documented not to accept it.

/cc @smitpatel

**Comment by Marusyk** [comment]
> @Marusyk you're right that MinAsync seems to be missing the exception doc. But the other methods you mention seem to already have the doc, or aren't supposed to throw InvalidOperationException when the source contains no elements - can you please confirm?

@roji Rechecked every method. The following methods can throw `InvalidOperationException`.

- LastOrDefaultAsync
- SingleAsync
- AverageAsync
- MinAsync

**Comment by roji** [comment]
See #24323, I don't think lastOrDefaultAsync is correct.

**Comment by Marusyk** [comment]
I'll share the code to reproduce

**Comment by Marusyk** [comment]
It is not about "sequence contains no elements", but should be also documented. What do you think?
![image](https://user-images.githubusercontent.com/9221694/110188481-7ca45900-7e24-11eb-8f13-95d2da7f9534.png)

**Comment by roji** [comment]
That could make sense - although EF Core may throw InvalidOperationException for any number of "bad/untranslatable query" scenarios. So this again seems like the "developer error" kind of exception (similar to NullReferenceException [as above](https://github.com/dotnet/efcore/issues/24307#issuecomment-789273318)), and not something developers should actually anticipate, catch and handle. And as such, we probably shouldn't document this either.

@dotnet/efteam thoughts?

**Comment by Marusyk** [comment]
Totally agree, removed changes for `LastOrDefaultAsync `

**Comment by roji** [comment]
@Marusyk [the docs for Queryable.Average](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.average?view=net-5.0#System_Linq_Queryable_Average_System_Linq_IQueryable_System_Int32__) seem to already contain the exception docs. AverageAsync is only part of EF Core (as opposed to Average).

**Comment by ajcvickers** [comment]
@roji Agree we should not include the InvalidOperationException.

**Comment by Marusyk** [comment]
Agree, removed. Thanks
