### ISSUE TITLE
Required parentheses for TOP clause

### ISSUE THREAD

**Issue by jnyrup** [dotnet/efcore#24310]
I was debugging why a query was throwing `incorrect syntax near '@p0'`, even though the query returned from `ToQueryString()` was valid when manually executing it in SSMS against the same database.

I found the culprit to be missing parentheses when using a parameter as expression in a TOP clause.

From https://docs.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql?view=sql-server-ver15#compatibility-support
> For backward compatibility, the parentheses are optional in SELECT statements if the expression is an integer constant. 

Is that intended behavior for EF Core to not have this backward compatibility for integer limits?

### Code

```cs
// works
var result = await context.MyDbSet
    .FromSqlRaw("SELECT TOP 1 * FROM MyTable")
    .ToListAsync();

// works
var result2 = await context.MyDbSet
    .FromSqlInterpolated($"SELECT TOP ({1}) * FROM MyTable")
    .ToListAsync();

// throws a SqlException with "'Incorrect syntax near '@p0'"
var result3 = await context.MyDbSet
    .FromSqlInterpolated($"SELECT TOP {1} * FROM MyTable")
    .ToListAsync();
```

### Stack traces

```
Microsoft.Data.SqlClient.SqlException: 'Incorrect syntax near '@p0'.'

This exception was originally thrown at this call stack:
    [External Code]
    ConsoleApp32.Program.Main(string[]) in Program.cs
```

### Provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Version 20H2
IDE: Visual Studio 2019 16.8.6

**Comment by roji** [comment]
@jnyrup can you please post the full LINQ query which generated the parameterized TOP clause, preferably in a runnable code sample?

**Comment by jnyrup** [comment]
To give more context:
I'm migrating our solution from EF 6.4.0 to EF Core 2.2 (will migrate to a newer EF Core once were on .net core) so I'm constrained by the limitations of translation from linq to sql in that version.
Therefore I use `FromSql` a few places and that's where I hit the problem.

The code posted here is a snippet of the smallest example I could reduce it to running .net5 and ef core 5.0.3, to see if the problem had already been resolved/improved.

The full code I used to reproduce the case (with the connection string removed, and the actual table name changed to `MyTable`)
```cs
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ConsoleApp32
{
    static class Program
    {
        static async Task Main()
        {
            string connection = null;
            var builder = new DbContextOptionsBuilder()
                .EnableDetailedErrors()
                .UseSqlServer(connection);

            using (var context = new MyContext(builder.Options))
            {
                // works
                var result = await context.MyDbSet
                    .FromSqlRaw("SELECT TOP 1 * FROM MyTable")
                    .ToListAsync();

                // works
                var result2 = await context.MyDbSet
                    .FromSqlInterpolated($"SELECT TOP ({1}) * FROM MyTable")
                    .ToListAsync();

                // removing the parentheses around {1} makes it throw
                var result3 = await context.MyDbSet
                    .FromSqlInterpolated($"SELECT TOP {1} * FROM MyTable")
                    .ToListAsync();

                // throws, this is closer to my actual code.
                var limit = 1;
                var result4 = await context.MyDbSet
                    .FromSqlRaw("SELECT TOP {0} * FROM MyTable", limit)
                    .ToListAsync();
            }
        }
    }

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<MyEntity> MyDbSet { get; set; }
    }

    public class MyEntity
    {
        public int Id { get; set; }
    }
}
```

**Comment by roji** [comment]
@jnyrup if you're using raw SQL, it's your responsibility to place parentheses where needed, since you're the one writing the SQL - or am I missing something? If parentheses were missing in SQL which EF generated for a LINQ query, then that could indeed be an EF  bug, but otherwise I'm not seeing the problem here.

**Comment by jnyrup** [comment]
We might be talking across each other.
`SELECT TOP 1 * FROM MyTable` is valid (or at least executable from SSMS) syntax against our SQL Server.
I guess that is due to the backward compatibility with integer limits I link to in the OP.

I wasn't aware that omitting parentheses is only possible due to that backward compatibility.
Without that knowledge, I imagined that `FromSqlRaw("SELECT TOP {0} * FROM MyTable", limit)` would then be a proper way to write a parameterized query equivalent to `SELECT TOP 1 * FROM MyTable`.

I don't know if EF Core would want to add similar backward compatibility to be more consistent with SqlServer.

**Comment by roji** [comment]
@jnyrup it does seem like we're talking across each other. What exactly are you proposing that EF do - what would it add to be more consistent with SQL Server? EF Core doesn't rework the SQL you give it in FromSqlRaw, it merely performs the parameterization (so `{0}` is replaced with `@limit`) and sends the resulting SQL to the database. Whether parentheses are needed in a certain context (TOP or otherwise), with constants or parameters, is purely a SQL question for the database being used (SQL Server in this case); and as I wrote above, when using the FromSql API it's the user's responsibility to provide correct SQL that works on their database.

**Comment by jnyrup** [comment]
Thanks for the patience with me Shay, the problem was on my side.
Omitting the parentheses is not valid for parameterized queries, as the db engine cannot know if the parameter later bound is an integer.

This was valid
```sql
SELECT TOP 1 FROM MyTable
```

This is not
```sql
SELECT TOP @p0 * FROM MyTable
```
