### ISSUE TITLE
How to get value of shadow property after query database

### ISSUE THREAD

**Issue by sang-sakarin** [dotnet/efcore#24315]
## For example

var records = _context.Record

foreach (var record in records)
{
   var nameEn = _context.Entry(record).Property("NameEn").CurrentValue;
}

The nameEn is allways blank, Please suggest me how can i get the value in database without using  _context.Records.Select(e => new {Name = EF.Property<string>(e, "NameEn")});

**Comment by roji** [comment]
The code above should work, as indicated in [the docs](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties#accessing-shadow-properties); see below for a full code sample that does this and works for me.

If you're still having issues, please post a runnable code sample which reproduces the problem (similar to the below).

<details>
<summary>Working code sample</summary>

```c#
await using (var ctx = new BlogContext())
{
    await ctx.Database.EnsureDeletedAsync();
    await ctx.Database.EnsureCreatedAsync();

    var blog = new Blog
    {
        Name = "foo"
    };
    ctx.Entry(blog).Property("MyShadowProperty").CurrentValue = 8;
    ctx.Blogs.Add(blog);

    await ctx.SaveChangesAsync();
}

await using (var ctx = new BlogContext())
{
    var blog = await ctx.Blogs.SingleAsync();
    Console.WriteLine(ctx.Entry(blog).Property("MyShadowProperty").CurrentValue);
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Property<int>("MyShadowProperty");
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

**Comment by sang-sakarin** [comment]
Sorry Sir, Thank for help me solved

My Issue is i set the options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)

**Comment by roji** [comment]
Yeah, we have a note warning against that in those docs, good that's it working for you now.
