### ISSUE TITLE
Supported strategy to reload tracked collections from database

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24319]
## Ask a question

The following extension method works well to ensure collection data is fetched from the database (not from ChangeTracker).

Is it an acceptable/supported way to accomplish this or inherently problematic?

### Include your code

Extension method:

```
public static void Reload(this CollectionEntry source)
{
    if (source.CurrentValue != null)
    {
        foreach (var item in source.CurrentValue)
            source.EntityEntry.Context.Entry(item).State = EntityState.Detached;
        source.CurrentValue = null;
    }
    source.IsLoaded = false;
    source.Load();
}
```

Usage:
```
_dbContext.Entry(blog).Collection(b => b.Posts).Reload();
```

[Source](https://stackoverflow.com/a/57062852/3071284)

### Include provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: macOS
IDE: Visual Studio for Mac 8.10 Preview

**Comment by ajcvickers** [comment]
@mrlife That should work assuming that you wish to discard any changes made and assuming the detached entities don't themselves have any dependents.

**Comment by mrlife** [comment]
@ajcvickers Thanks! For dependent collections, I call this for those as well. For non-collection dependents, I just call the standard `Reload()` available on those. I think that covers everything, but if not, please let me know.
