### ISSUE TITLE
EF Core - Cannot be tracked ERROR but I need to update the child entity

### ISSUE THREAD

**Issue by hikhyper** [dotnet/efcore#24314]
Good day,

I'm trying to update my child entity. But I get an exception 

> The instance of entity type 'SubDetails' cannot be tracked because another instance with the same key value for {'SubDetailId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values

Here's my sample code:
```
var storedDetail = await context.Details
                                .Where(x => x.DetailId == d.DetailId)
                                .Include(i => i.SubDetails)
                                .FirstOrDefaultAsync();

storedDetail.SubDetails = d.SubDetails;
await context.SaveChanges();
```
When I hit update, then I get that exception. 

I'm aware of using `AsNotTracking()` but this removes the tracking of the child entity which is the `SubDetails` that I want to update. Using `AsNotTracking()` ends up updating only the parent entity only, not its child entity.

Here's my sample models:

**Product.cs**
```
public class Detail {
    public int Id {get;set;}
    public string Name {get;set;}
    public ICollection<SubDetail> SubDetails {get;set;}
}

```
**SubDetail.cs**
```
public class SubDetail {
    public int Id {get;set;}
    public string Location {get;set;}
    public Detail Detail {get;set;}
    public int DetailId {get;set;}
}

```
Any help regarding this?

EF Core version: 2.2.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp2.2
Operating system:
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@hikhyper First, EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please update to 3.1 or 5.0. Second, the exception is happening because you load one instance in the query, and then attempt to replace it with a new instance. See https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution for more info.
