### ISSUE TITLE
Cannot sort by NotMapped model property when upgrading from EF 2.2 to 5.0

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/efcore#24322]
Upgrading EF 2.2, a grid was bound to this object, and when the user clicked on the FullName property (see below = FirstName + ' ' + LastName), which wasn't mapped, EF could generate the correct Order By.

In 5.0 I get this error

  .OrderBy(a => a.Inner.FullName)' could not be translated. Additional information: Translation of member 'FullName' on entity type 'User' failed. This commonly occurs when the specified member is unmapped. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

What pattern should I use instead (and no, in this case I can't do order by FirstName, LastName) - the code stack basically allows the user to sort by any column returned, and I don't want to have special logic to decompose this into constituent fields. I want it to generate either SELECT FirstName +" "+ LastName as FullName Order By 'FirstName' + " " + LastName' or something equivalent.

```c#
  public class User : ITenantEntity, ISoftDelete, IAudited
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public DateTime? EmailValidated { get; set; }
        public DateTime? ConsentGranted { get; set; }
        public List<UserRole> Roles { get; set; }
        public ICollection<Device> Devices { get; set; }
        public int? ProfilePhotoId { get; set; }
        public Document ProfilePhoto { get; set; }
        public Vehicle Vehicle { get; set; }
        public int? DefaultRegionId { get; set; }
        public Region DefaultRegion { get; set; }
        public bool EmailMySurveys { get; set; }

        [NotMapped]
        public string FullName => $"{FirstName} {LastName}";
    }
```

**Comment by roji** [comment]
Prior to EF Core 3.0, client evaluation was used for anything that couldn't be translated to SQL for server evaluation - including operations on unmapped properties ([here's the breaking change note](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client)).

You're probably looking for [computed columns](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns): you can map your FullName property to a computed database column, which will allow ordering by it. You can even have an index on it, speeding up the ordering operation in the database.
