### ISSUE TITLE
generate CreateTableOperation instance

### ISSUE THREAD

**Issue by DanielZhang-MSFT** [dotnet/efcore#24326]
Description:
I want to create new instance of CreateTableOperation class from my model via reflection or enything else. I have my model's name and I want to access CreateTableOperation instance with all ef standard attribute, to use it can anyone help me?
I have my custom sql generator class and I want to edit AddColumnOperation method to create a new table based on a model. and I want to have something like CreateTableOperation instance that give me all columns with all annotations that related to sql columns
my models are different and I have only the name of it. but it is one of my domain classes.

My domain classes:
 ```
public class A
     {
         [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
         public int Id { get; set; }
         public int Value { get; set; }
     }
     public class A_1
     {
         [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
         public int Id { get; set; }
         public int Value { get; set; }
     }
     public class A_2
     {
         [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
         public int Id { get; set; }
         public int Value { get; set; }
     }

```
my sqlGenerator class:

```
 public class MyMigrationSqLGenerator : MigrationSqlGenerator
     {
         private string GenerateSqlStatement(AddColumnOperation migrationOperation)
         {
          //Now, I have name of table from migrationOperation.Table. like A,
          //and I want to create table A_1 or A_2 and generate create command,
          //I need something like CreateTableOperation to give me A_1 or A_2 columns and annotations
     }
     }
```

**Comment by AndriySvyryd** [comment]
@DanielZhang-MSFT Could you provide more details on your scenario? `CreateTableOperation` and the like are usually only created by EF and `MigrationSqlGenerator` is usually only implemented by a provider.

**Comment by usapop** [comment]
Hi @AndriySvyryd
I need something like CreateTableOperation class, I need only list of columns and annotions.
Is any way that give me that list? reflection or something similar?

**Comment by roji** [comment]
@usapop you'll need to explain a bit more on why you think you need something like the CreateTableOperation class. Are you implementing your own MigrationSqlGeneration class? If so, why? What exactly are you trying to accomplish, which database provider are you using and why is it insufficient?

**Comment by bricelam** [comment]
@DanielZhang-MSFT You can get a CreateTableOperation for any entity type in your model in your migrations sql generator using code like this:

```csharp
var table = model.GetRelationalModel().FindTable(tableName, schema);

var createTableOperation = new CreateTableOperation
{
    Name = table.Name,
    Schema = table.Schema,
    Comment = table.Comment,
    PrimaryKey = AddPrimaryKeyOperation.CreateFrom(primaryKey)
};
createTableOperation.AddAnnotations(table.GetAnnotations());

foreach (var column in table.Columns)
{
    var addColumnOperation = new AddColumnOperation
    {
        Name = column.Name,
        ColumnType = column.StoreType,
        IsNullable = column.IsNullable,
        DefaultValue = column.DefaultValue,
        DefaultValueSql = column.DefaultValueSql,
        ComputedColumnSql = column.ComputedColumnSql,
        IsStored = column.IsStored,
        Comment = column.Comment,
        Collation = column.Collation
    };
    addColumnOperation.AddAnnotations(column.GetAnnotations());
    
    createTableOperation.Columns.Add(addColumnOperation);
}

foreach (var foreignKey in table.ForeignKeyConstraints)
{
    createTableOperation.ForeignKeys.Add(AddForeignKeyOperation.CreateFrom(foreignKey));
}

foreach (var uniqueConstraint in table.UniqueConstraints.Where(c => !c.GetIsPrimaryKey()))
{
    createTableOperation.UniqueConstraints.Add(AddUniqueConstraintOperation.CreateFrom(uniqueConstraint));
}

foreach (var checkConstraint in table.CheckConstraints)
{
    createTableOperation.CheckConstraints.Add(AddCheckConstraintOperation.CreateFrom(checkConstraint));
}
```

@usapop You can use the DbContext.Model property to inspect the model...

**Comment by usapop** [comment]
Hi @bricelam 
Can you explain more information about you sample code?
in first line, what is the model?
I cannot access DbContext.Model, I'm use .net EntityFramework in system.Data.Entity namespace

**Comment by roji** [comment]
@usapop the System.Data.Entity namespace is for EF6. EF Core uses Microsoft.EntityFrameworkCore.

**Comment by usapop** [comment]
yes @roji , in this scenario I'm use EF6.
Is this sample for EF6 or entity framework core?

**Comment by roji** [comment]
@usapop the sample above is for EF Core (this repo is only for EF Core).
