### ISSUE TITLE
Many to Many skip navigations even when there is a CLR join type?

### ISSUE THREAD

**Issue by cedwards-telis** [dotnet/efcore#24333]
If I have an existing many to many relationship and I decide to add a join table (say because I need to accommodate an extra property) then all the existing code will refer to the skip navigation property.  Is there any way to preserve the skip navigation using the model builder?  I cannot get it to work.

So I start of with

```
public class person
{
public int PersonId { get; set; }
public string Name { get; set; }
public ICollection<Group> Groups { get; set; }
}

public class Group
{
public int GroupId { get; set; }
public string Name { get; set; }
public ICollection<Person> People { get; set; }
}
```

But then I decide I want to have MembershipDescription field in the join.  So I move to using a CLR type, but I don't want to lose the the slip navigations that are littered throughout my code.  So I try.

```
    public class Person
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public ICollection<Group> Groups { get; set; }
        public ICollection<Membership> Memberships { get; set; }
    }

    public class Group
    {
        public int GroupId { get; set; }
        public string Name { get; set; }
        public ICollection<Person> People { get; set; }
        public ICollection<Membership> GroupMemberships { get; set; }
    }

    public class Membership
    {
        public Person Person { get; set; }
        public Group Group { get; set; }
        public string MembershipDescription { get; set; }
    }
```

And in my OnModelCreating I have

```
            modelBuilder.Entity<Person>()
                .HasMany(e => e.Groups)
                .WithMany(e => e.People)
                .UsingEntity<Membership>(
                    b => b.HasOne<Group>().WithMany().HasForeignKey("GroupId"),
                    b => b.HasOne<Person>().WithMany().HasForeignKey("PersonId")
                    );
```

But then I get this in my initial migration and nothing works as I expect

```
            migrationBuilder.CreateTable(
                name: "Membership",
                columns: table => new
                {
                    GroupId = table.Column<int>(type: "int", nullable: false),
                    PersonId = table.Column<int>(type: "int", nullable: false),
                    PersonId1 = table.Column<int>(type: "int", nullable: true),
                    GroupId1 = table.Column<int>(type: "int", nullable: true),
                    MembershipDescription = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
```

**Comment by anranruye** [comment]
You should use b.HasOne(x=>x.Group) and b. HasOne(x=>x.Person)

**Comment by cedwards-telis** [comment]
> You should use b.HasOne(x=>x.Group) and b. HasOne(x=>x.Person)

I am using that

```
            modelBuilder.Entity<Person>()
                .HasMany(e => e.Groups)
                .WithMany(e => e.People)
                .UsingEntity<Membership>(
                    b => b.HasOne<Group>().WithMany().HasForeignKey("GroupId"),
                    b => b.HasOne<Person>().WithMany().HasForeignKey("PersonId")
                    );
```

**Comment by cedwards-telis** [comment]
> You should use b.HasOne(x=>x.Group) and b. HasOne(x=>x.Person)

Like this?  Doesn't compile.

            modelBuilder.Entity<Person>()
                .HasMany(e => e.Groups)
                .WithMany(e => e.People)
                .UsingEntity<Membership>(
                    b => b.HasOne(x => x.Group),
                    b => b.HasOne(x => x.Person)
                    );

Cannot implicitly convert type 'Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceNavigationBuilder<Many_To_Many_With_CLR_Join_Type.Membership, Many_To_Many_With_CLR_Join_Type.Group>' to 'Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder<Many_To_Many_With_CLR_Join_Type.Group, Many_To_Many_With_CLR_Join_Type.Membership>'

**Comment by anranruye** [comment]
```C#
            modelBuilder.Entity<Person>()
                .HasMany(e => e.Groups)
                .WithMany(e => e.People)
                .UsingEntity<Membership>(
                    b => b.HasOne<Group>(x=>x.Group).WithMany().HasForeignKey("GroupId"),
                    b => b.HasOne<Person>(x=>x.Person).WithMany().HasForeignKey("PersonId")
                    );
```

**Comment by cedwards-telis** [comment]
> ```cs
>             modelBuilder.Entity<Person>()
>                 .HasMany(e => e.Groups)
>                 .WithMany(e => e.People)
>                 .UsingEntity<Membership>(
>                     b => b.HasOne<Group>(x=>x.Group).WithMany().HasForeignKey("GroupId"),
>                     b => b.HasOne<Person>(x=>x.Person).WithMany().HasForeignKey("PersonId")
>                     );
> ```

This builds but you still get the duplicate keys as in my original post.

Here is a repo with the code (for VS) - https://github.com/cedwards-telis/Many-To-Many-With-CLR-Join-Type

**Comment by anranruye** [comment]
```C#
            modelBuilder.Entity<Person>()
                .HasMany(e => e.Groups)
                .WithMany(e => e.People)
                .UsingEntity<Membership>(
                    b => b.HasOne<Group>(x=>x.Group).WithMany(x=>x.GroupMemberships).HasForeignKey("GroupId"),
                    b => b.HasOne<Person>(x=>x.Person).WithMany(x=>x.Memberships).HasForeignKey("PersonId")
                    );
```

**Comment by cedwards-telis** [comment]
@anranruye 

Thanks very much, this builds now and I can use the skip navigations.  And I even understand it!
