### ISSUE TITLE
SQL Server 2012 support in version 6 of the connector?

### ISSUE THREAD

**Issue by ravn** [dotnet/efcore#24347]
(Asked the question to the team by mail, was asked to ask it here instead for visibility)

Hi.

We are currently migrating and adding new functionality to a legacy application running on SQL Server 2012.  For our planning I would like to know if the upcoming version 6 of the SQL Server connector(?) in EF still supports 2012 as well?

Thanks /Thorbjørn

**Comment by ajcvickers** [comment]
@ravn Can you be more specific in what you are referring to as the "upcoming version 6 of the SQL Server connector?"

If you're referring to what the EF team ship, then we have no plans to drop support for SQL Server 2012. However, EF depends on [SqlClient](https://github.com/dotnet/SqlClient), and while I don't believe that they are dropping support you should get confirmation from them. If you're using a third-party SQL Server connector then you'll need to check with them.

**Comment by ravn** [comment]
@ajcvickers I am learning on the job with C# (coming from the Java world) so I might not understand the components correctly.  I wish to do some simple "read from a legacy database I control into corresponding objects and have a framework handle the changes to the database schema in something I can commit".  It is my understanding that this is what the EF project provides.

I have then poked around, seen that SQL Server 2012 which we currently run, needs to be upgraded.   I therefore look at how hard the newest versions of the new components push this.  It was my understanding that https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/6.0.0-preview.1.21102.2 will be the newest version soon so I would like to know if we can use version 6 when it comes out or if we must stay on 5 until we are in a position to upgrade in production.  So, logistics.

**Comment by roji** [comment]
@ravn 6.0.0 is indeed in preview at the moment and will be released in late 2021 - 5.0.x is the current latest release and should be generally the preferred version. As @ajcvickers said, we don't plan to drop support for SQL Server 2012 for EF Core 6.0, so you can use 5.0 now and upgrade to 6.0 when that comes out without much risk (though major version upgrades always require extensive testing).

**Comment by ravn** [comment]
Thanks to all.  I am no longer on the project so the decision what to do is not mine any longer. 

I am very impressed with what EF can do. We lack something like EF in the Java world.
