### ISSUE TITLE
Navigation properties of same type on abstract base class

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24344]
## Ask a question

As far as I can tell, models inheriting from an abstract base class that contains navigation properties of the same kind (e.g. `User` below) requires that Fluent API needs to be set up for each inheriting model.

Is it possible to include the Fluent API code once for the abstract base class and not have to add it for every inheriting class?

### Include your code

```C#
// model
public abstract class ItemBase
{
    public int Id { get; set; }
    public DateTime CreateDate { get; set; }
    public DateTime UpdateDate { get; set; }
    public User CreateUser { get; set; }
    public User UpdateUser { get; set; }
}

public class RegularItem : ItemBase
{
    ...
}

public class AdvancedItem : ItemBase
{
    ...
}

// Fluent API in `OnModelCreating()`
modelBuilder.Entity<RegularItem>()
    .HasOne(p => p.CreateUser)
    .WithMany();

modelBuilder.Entity<RegularItem>()
    .HasOne(p => p.UpdateUser)
    .WithMany();

modelBuilder.Entity<AdvancedItem>()
    .HasOne(p => p.CreateUser)
    .WithMany();

modelBuilder.Entity<AdvancedItem>()
    .HasOne(p => p.UpdateUser)
    .WithMany();
```

### Include provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by ajcvickers** [comment]
@mrlife For the case you present above you'll need to explicitly declare the relationship for each entity type. However, you could certainly do a loop in OnModelCreating to reduce the lines of code needed.

**Comment by qsdfplkj** [comment]
You could use IEntityTypeConfiguration<T> and create a ItemBaseConfiguration<T> where T: ItemBase; then apply this configuration to all derived classes: modelBuilder.ApplyConfiguration(new  GenericConfigurationClass<RegularItem>());
 modelBuilder.ApplyConfiguration(new  GenericConfigurationClass<AdvancedItem>());

**Comment by mrlife** [comment]
@ajcvickers This is very helpful to know, thanks. How does one loop through a list of actual types (not variables containing types)?

**Comment by ajcvickers** [comment]
@mrlife Here's one way to use a loop:

```C#
foreach (var type in new[] {typeof(RegularItem), typeof(AdvancedItem)})
{
    modelBuilder.Entity(type).HasOne(nameof(ItemBase.CreateUser)).WithMany();
    modelBuilder.Entity(type).HasOne(nameof(ItemBase.UpdateUser)).WithMany();
}
```
