### ISSUE TITLE
Cosmos DB: is CosmosExecutionStrategy applied for queries?

### ISSUE THREAD

**Issue by alexeymarkov** [dotnet/efcore#24343]
Hello,

currently I have to use EF 5.0.0-preview.3.20181.2 because EF Core 5 release is not working in Azure Functions.
And it seems CosmosExecutionStrategy is not applied when doing queries.
It is correct?
If yes, is it fixed in EF Core 5 release?

Regards,
Alexey Markov

**Comment by AndriySvyryd** [comment]
There haven't been any specific changes for this since EF 5.0.0-preview.3, but note that the strategy will only retry 6 times by default and then fail. Enable logging to see whether this was the case.

**Comment by alexeymarkov** [comment]
Logging is enabled. Default CosmosExecutionStrategy works well for SaveChangesAsync but not for DbSet.FindAsync and not for IQueryable.ToArrayAsync.
Is this by design?

I see Enumerator implementations in EFCore.Relational\Query\Internal respect Execution Strategy but I see nothing in EFCore.Cosmos\Query\Internal that would use Execution Strategy.

For me it looks like a bug.

**Comment by AndriySvyryd** [comment]
@alexeymarkov You are right, `CosmosExecutionStrategy` doesn't handle queries, they are handled by the SDK built-in retry policy as it allows to handle retries without pre-buffering the whole result set, we will expose more options in https://github.com/dotnet/efcore/issues/23203

**Comment by alexeymarkov** [comment]
So do you suggest disabling CosmosExecutingStrategy for SaveChangesAsync as it does not really make sense as there is a built-in retry in CosmosClient?

**Comment by alexeymarkov** [comment]
OK, thanks.
Currently I see the built-in policy fails in 3-5 seconds at my tests when querying data. But with CosmosExecutingStrategy write operations fail in 30-40 seconds. I am thinking about using CosmosExecutingStrategy for querying also...
