### ISSUE TITLE
When call FromSqlRaw in expression tree throws NotImplementedException

### ISSUE THREAD

**Issue by RZProf** [dotnet/efcore#24349]
When call FromSqlRaw on dbset in regular way it works very well.
but if call FromSqlRaw in a expression tree throws not implemented exception
database is not in memory 
 i tried to override OnModelCreating method and gave my model an id. still not woking and throws exception
with same provider when call linq methods over db set works very well

.net core 3.1
ef core 3

**Comment by RZProf** [comment]
I solved the problem by calling create query before calling to array
like down below:

```
var takeMethodCall = Expression.Call(
                typeof(Queryable),
                nameof(Queryable.Take),
                new []{typeof(Person) },
                dbContext.Persons.FromSqlRaw(Query).Expression, 
                Expression.Constant(2));
var methodInfo = dataSource.Source.Provider.GetType().GetMethods()
                .Single(i => i.Name == "CreateQuery" && i.IsGenericMethod)
                .MakeGenericMethod(typeof(string));
var expression = Expression.Call(
                Expression.Constant(QueryProvider),
                methodInfo,
                Expression.Constant(takeMethodCall ));
var toArrayMethodCall = Expression.Call(
                typeof(Enumerable), 
                nameof(Enumerable.ToArray), 
                new []{typeof(Person) },
                expression);

var results = (IEnumerable)Expression.Lambda(toArrayMethodCall).Compile().DynamicInvoke();
```

**Comment by smitpatel** [comment]
In first scenario, you took expression from FromSqlRaw method and added Take(2) on it and followed by ToArray. That expression tree got disconnected from a QueryProvider. The expression tree is valid but invoking it will require a QueryProvider.
In second scenario, when you are calling CreateQuery method, you are giving this new expression tree with Take to EF Core's query provider which would enumerate it when calling ToArray. Second way is right away to do it.
