### ISSUE TITLE
Test Issue: CommandInterceptionTestBase: Error while executing fact- Intercept_non_query_one_app_and_one_injected_interceptor

### ISSUE THREAD

**Issue by iampratishtha** [dotnet/efcore#24348]
Hi Team,

**Problem:** Test case failing with Informix Server while executing the delete row query - DELETE FROM [Singularity] WHERE [Id] = 78
**Test Class:** CommandInterceptionTestBase
**Fact:** Intercept_non_query_one_app_and_one_injected_interceptor
**Reason:** Test failing because there is no row with "78" ID in the "Singularity" table, and in the test fact we are deleting a row having "78" ID. 

While creating a Model in InterceptionTestBase.cs (Line:48-61) class, we are inserting two rows in the Id column 77 and 88.
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder
                    .Entity<Singularity>()
                    .HasData(
                        new Singularity { Id = 77, Type = "Black Hole" },
                        new Singularity { Id = 88, Type = "Bing Bang" });

                modelBuilder
                    .Entity<Brane>()
                    .HasData(
                        new Brane { Id = 77, Type = "Black Hole?" },
                        new Brane { Id = 88, Type = "Bing Bang?" });
            }
```

But in CommandInterceptionTestBase.cs (Line:1355-1368) class we are giving a query **DELETE FROM [Singularity] WHERE [Id] = 78**
```
private async Task TestCompositeNonQueryInterceptors(UniverseContext context, bool async)
        {
            using (context.Database.BeginTransaction())
            {
                string nonQuery =
                    NormalizeDelimitersInRawString(**"DELETE FROM [Singularity] WHERE [Id] = 78"**);

                Assert.Equal(
                    7,
                    async
                        ? await context.Database.ExecuteSqlRawAsync(nonQuery)
                        : context.Database.ExecuteSqlRaw(nonQuery));
            }
        }
```

Can you please help me to understand if there is any issue in this delete query? and if not please help me to understand the objective of these test facts.

**Other facts with the same issue:**
MutatingNonQueryCommandInterceptor (Line:558)
Intercept_non_query_to_replace_execution (Line:733)
Intercept_non_query_to_replace_result (Line:1019)
Intercept_non_query_one_app_and_one_injected_interceptor (Line:1347)

**Comment by ajcvickers** [comment]
@iampratishtha The delete ends up being a no-op, since there is no record with ID 78. However, this should not fail the test, which is not about performing a delete, but rather about testing that the interceptors work.
