### ISSUE TITLE
DbConnectionInterceptor is ignored for migrations (both command line and context.Database operations)

### ISSUE THREAD

**Issue by felinepc** [dotnet/efcore#24346]
I had to use the `DbConnectionInterceptor` to implement Azure Ad Manage Identity token authentication for EF Core + Azure SQL/Postgrel SQL, because the documented constructor-based pattern is not async and cannot handle `DbContext` pooling or `DbContextFactory` (latter is required for use with Blazor server).

The code looks like this:

**Interceptor:** 

```
public class AadMiDbConnectionInterceptor : DbConnectionInterceptor
{
    private readonly AzureServiceTokenProvider _azureTp;

    public AadMiDbConnectionInterceptor(AzureServiceTokenProvider azureTp)
    {
        _azureTp = azureTp;
    }

    public async override ValueTask<InterceptionResult> ConnectionOpeningAsync(
         DbConnection connection,
         ConnectionEventData eventData,
         InterceptionResult result,
         CancellationToken cancellationToken = default)
    {
        //... Handle token retrieval/replacement,  omitted for brevity
     }
}
```
**ASP.NET Core DI:**
```
services.AddSingleton<AzureServiceTokenProvider>
services.AddSingleton<AadMiDbConnectionInterceptor>();

services.AddDbContext<MyDbContext>((sp, options) =>
{
     var config = sp.GetRequiredService<IConfiguration>();
     var interceptor = sp.GetRequiredService<AadMiDbConnectionInterceptor>();

     options.UseNpgsql(config.GetConnectionString("MyDbConnection"))
         .AddInterceptors(interceptor);
});
```
This setup works perfectly fine in project, but when I attempted to perform DB migrations, I got the "no password provided but password required..." error, indicating that the `DbConnectionInterceptor` is not being used.

At first I thought it's the command line tools not being able to correctly obtain the context with the interceptor from ASP.NET Core's DI container, so I implemented `IDesignTimeDbContextFactory` and explicitly created and added the interceptor + context  inside it. The interceptor is still ignored.

Then I assumed it's just the command line tool limitation, so I created some migration logic via code, using `context.Database` related operations such as `.Migrate`. To my surprise, the interceptor also does not work.

So the only way to make migration work, is to explicitly run the `AzureServiceTokenProvider` inside `IDesignTimeDbContextFactory` or inside my migration codes to obtain a token first, and set the connection string. This will do for now, but I wonder if it's possible to make `DbConnectionInterceptor` work for migration related tasks so that no extra code is needed.

**Comment by ajcvickers** [comment]
@felinepc You mention `.Migrate`, rather than `.MigrateAsync`. Are you sure that this isn't working because the connection is not being used asynchronously, and hence `ConnectionOpening` is called instead of `ConnectionOpeningAsync` on your interceptor?

**Comment by felinepc** [comment]
@ajcvickers Oops I forgot the async methods on those even existed (never had to use them before haha). But unfortunately I tried the async versions and still got the "No password has been provided" error. Here's my simple migration method:

```
public static void MigrateDb (IServiceProvider serviceProvider)
{
    using (var scope = serviceProvider.CreateScope())
    {
        // MyDbContext has been registered in Startup.cs with .AddInterceptors()
        var context = scope.ServiceProvider.GetRequiredService<MyDbContext>();
        
        //Calling this synchronously for now to avoid messing with Program.cs Main()
        context.Database.MigrateAsync().Wait();
    }
}
```

I'm using the npgsql provider. Didn't get to test with SQL Server yet.

**Comment by ajcvickers** [comment]
@felinepc I have not been able to reproduce this. Can you post the exact text of the migrations command that fails?

**Comment by felinepc** [comment]
@ajcvickers Sure, please see complete test console app below (no DI, everything constructed manually)

```
namespace TestDbInterceptor
{
    class Program
    {
        static async Task Main(string[] args)
        {
             var connStrWithoutPw = 
                "Server=myserver.postgres.database.azure.com; Port=5432; User Id=myaaduser@myserver; Database=mydb;";

            var interceptor = new TestAadMiDbConnectionInterceptor();

            var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();

            optionsBuilder
                .UseNpgsql(connStrWithoutPw).AddInterceptors(interceptor);

            var context = new MyDbContext(optionsBuilder.Options);

            Console.WriteLine("Performing EF Migration...");

            await context.Database.MigrateAsync();

            Console.WriteLine("Migration completed");
        }
    }

    public class TestAadMiDbConnectionInterceptor : DbConnectionInterceptor
    {
        
        public async override ValueTask<InterceptionResult> ConnectionOpeningAsync(
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result,
            CancellationToken cancellationToken = default)
        {
            var azureTp = new AzureServiceTokenProvider(connectionString: "RunAs=Developer; DeveloperTool=AzureCli");
            
            var token = await azureTp
               .GetAccessTokenAsync("https://ossrdbms-aad.database.windows.net", "my-aad-tenant-id", cancellationToken);

            connection.ConnectionString += $"; Password={token}";

            return result;
        }

    }
}
```

Result: `Npgsql.NpgsqlException: 'No password has been provided but the backend requires one (in cleartext)'`

**Comment by ajcvickers** [comment]
@roji I am not able to reproduce this with the SQL Server provider. I don't think this should be provider specific, but can you try with Npgsql to check if that's the difference?

@felinepc Are you 100% that the interceptor is not being called, as opposed to it being called but failing to get a valid token?

**Comment by felinepc** [comment]
@ajcvickers Correct, it's not called at all, per debugger (and I just added a writeline entry in the interceptor method to confirm this).

I will set up an Azure SQL instance to test the SQL Server provider this weekend.

**Comment by roji** [comment]
This repros for me with Npgsql, am investigating.

**Comment by roji** [comment]
Yeah, I see now - NpgsqlDatabaseCreator bypasses RelationalConnection entirely because of some tricks.

Tracking this as https://github.com/npgsql/efcore.pg/issues/1756.
