### ISSUE TITLE
EF Core Not Respecting 0-seed Identity Column as Valid FK

### ISSUE THREAD

**Issue by mschmidt73** [dotnet/efcore#24352]
## Summary

Exception message: "The value of 'UserSecurityProfile.UserId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known."

The exception is thrown attempting to insert into a many-to-many join table where the parent entity has a 0-value PK, even though the model has specified that the PK is a zero-seeded, auto-incrementing identity column, with navigation properties defined on both entities.

There is a workaround (in addition to using raw SQL) which is to load the parent entity from the context and assign the navigation property. However, for large numbers of inserts, this would be quite inefficient, particularly when all the Id's being submitted via API are valid FK values.

### Code (omissions for brevity)

```C#
// (Entity Definitions)
public class User
{
    [Column("USER_KEY", TypeName = "int"), DatabaseGenerated(DatabaseGeneratedOption.Identity), Key]
    public int UserId { get; set; }

    public virtual List<UserSecurityProfile> UserSecurityProfiles { get; set; } = new List<UserSecurityProfile>();
}

public class UserSecurityProfile
{
    [Column("PROFILE_ID", TypeName = "varchar(30)"), MaxLength(30), Required]
    public string ProfileId { get; set; }

    [ForeignKey("ProfileId")]
    public virtual SecurityProfile SecurityProfile { get; set; }

    [ForeignKey("UserId")]
    public virtual User User { get; set; }

    [Column("USER_KEY", TypeName = "int"), Required]
    public int UserId { get; set; }
}

public class AdminContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).IsClustered();
            entity.Property(e => e.UserId)
                .HasColumnName("USER_KEY")
                .HasColumnType("int")
                .UseIdentityColumn(seed: 0, increment: 1)
                .ValueGeneratedOnAdd();
        }
    }
}

// Service Class
public class AuthorizationService : IAuthorizationService
{
    public async Task<Role> CreateRole(CreateRole model)
    {
        var securityProfile = new Entity.SecurityProfile
        {
            Description = model.Description,
            Core = Entity.Defaults.CurrentVersion.Core,
            ProfileId = model.Name,
            SecurityProfileWindows = model.OperationNames.Select(operationName => new Entity.SecurityProfileWindow
            {
                Core = Entity.Defaults.CurrentVersion.Core,
                ProfileId = model.Name,
                WindowId = operationName
            }).ToList(),
            UserSecurityProfiles = model.UserIds.Select(userId => new Entity.UserSecurityProfile
            {
                ProfileId = model.Name,
                UserId = userId
            }).ToList()
        };

        context.SecurityProfiles.Add(securityProfile);
        context.UserSecurityProfileHistory.AddRange(securityProfile.UserSecurityProfiles.Select(usp => new Entity.UserSecurityProfileHistory
        {
            ProfileId = usp.ProfileId,
            UserId = usp.UserId
        }));

        await context.SaveChangesAsync();

        return await GetRole(securityProfile.ProfileId);
    }
}
```

Originally, the model was mainly specified with annotation, including over User.UserId. While debugging, I commented out the column annotation on the entity and moved the definition into OnModelCreating.

### Work-around

In order to get this to work when the "SYSTEM" user (i.e. UserId == 0) is involved, I had inject the following code prior the original creation of the securityProfile entity:

```C#
            if (model.UserIds.Contains(Entity.Defaults.User.SystemUserId))
            {
                var systemUser = await context.Users.SingleAsync(user => user.UserId == Entity.Defaults.User.SystemUserId);
                var userSecurityProfile = new Entity.UserSecurityProfile
                {
                    ProfileId = model.Name,
                    User = systemUser
                };
                var userSecurityProfileHistory = new Entity.UserSecurityProfileHistory
                {
                    ProfileId = model.Name,
                    User = systemUser
                };

                context.UserSecurityProfiles.Add(userSecurityProfile);
                context.UserSecurityProfileHistory.Add(userSecurityProfileHistory);

                model.UserIds.Remove(Entity.Defaults.User.SystemUserId);
            }
```

This is, for lack of a better term, suboptimal. I would rather not have to preload all the User entities.

### Provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.9.0

**Comment by anranruye** [comment]
try nullable keys
```C#
public class User
{
    [Column("USER_KEY", TypeName = "int"), DatabaseGenerated(DatabaseGeneratedOption.Identity), Key]
    public int? UserId { get; set; }

    public virtual List<UserSecurityProfile> UserSecurityProfiles { get; set; } = new List<UserSecurityProfile>();
}

public class UserSecurityProfile
{
    [Column("PROFILE_ID", TypeName = "varchar(30)"), MaxLength(30), Required]
    public string ProfileId { get; set; }

    [ForeignKey("ProfileId")]
    public virtual SecurityProfile SecurityProfile { get; set; }

    [ForeignKey("UserId")]
    public virtual User User { get; set; }

    [Column("USER_KEY", TypeName = "int"), Required]
    public int? UserId { get; set; }
}
```

**Comment by mschmidt73** [comment]
@anranruye I thought of that, though I haven't tested it. It would seem odd to model the entity in a way that is inconsistent with the underlying data store. I could be missing something here, but it seems like EF could validate that 0 is a valid value for UserId based on the model. That said, it could be a preferable work-around to unnecessarily loading an entity and/or employing conditional logic.

**Comment by ajcvickers** [comment]
@mschmidt73 When using generated keys, EF Core reserves the CLR default as a sentinel value indicating that the key is not set. See https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#generated-versus-explicit-key-values. EF Core does not use this sentinel when the key is not configured as generated. If you need both generation and zero to be a value that should not result in key generation, then you can use one of the patterns described here: https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#working-with-default-values, of which making the property nullable (as suggested by @anranruye) is the simplest, but using a nullable backing field has less impact on your domain model.
