### ISSUE TITLE
Nested self referencing objects not correctly assigned to objects

### ISSUE THREAD

**Issue by dominicshaw** [dotnet/efcore#24368]
### Include your code

As per code here https://github.com/dominicshaw/EntityFrameworkNestingQuirk - the following snip does not behave as expected:

```cs
private async Task<(bool Found, Appraisal Appraisal)> Get(int id)
{
    var staff = await _context.Staff.FindAsync(3);

    _logger.LogInformation("Got Staff Object   : Staff {id} has manager set to {managerId} - running query for appraisal", staff.Id, staff.ManagerId);

    var appraisal =
        await _context.Appraisals
            .Include(ap => ap.Staff).ThenInclude(s => s.Manager)
            .Include(ap => ap.Staff).ThenInclude(s => s.SecondaryManager)
            .Where(ap => ap.Id == id)
            .SingleOrDefaultAsync();

    _logger.LogInformation("Appraisal Query Run: Staff {id} has manager set to {managerId} - run completed", staff.Id, staff.ManagerId);

    if (appraisal != null)
    {
        _logger.LogInformation("Appraisal->Staff->2ndManager->Manager={id} (We should NOT have this)", appraisal.Staff.SecondaryManager?.ManagerId);
        return (true, appraisal);
    }

    return (false, null);
}
```
first log event, manager id is set
second log event, manager id is missing
it shows correctly in the db, the query run by ef looks good, but the object model is wrong
See sample project for more.

### Include verbose output
The console output should be:
```
Got Staff Object   : Staff 3 has manager set to 1 - running query for appraisal
info: EntityFrameworkNestingQuirk.Controllers.AppraisalsController[0]
Appraisal Query Run: Staff 3 has manager set to 1 - run completed
```
but is
```
Got Staff Object   : Staff 3 has manager set to 1 - running query for appraisal
info: EntityFrameworkNestingQuirk.Controllers.AppraisalsController[0]
Appraisal Query Run: Staff 3 has manager set to (null) - run completed
```
See sample project for more.

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win10 x64
IDE: 
Microsoft Visual Studio Professional 2019
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.03752

[EntityFrameworkNestingQuirk.zip](https://github.com/dotnet/efcore/files/6116775/EntityFrameworkNestingQuirk.zip)
[vs system info.txt](https://github.com/dotnet/efcore/files/6116780/vs.system.info.txt)

**Comment by ajcvickers** [comment]
Note for triage: I am able to reproduce this. Query generated:

```sql
SELECT TOP(2) [a].[Id], [a].[Complete], [a].[Deleted], [a].[PeriodEnd], [a].[PeriodStart], [a].[StaffId], [s].[Id], [s].[Email], [s].[Logon], [s].[ManagerId], [s].[Name], [s].[SecondaryManagerId], [s0].[Id], [s0].[Email], [s0].[Logon], [s0].[ManagerId], [s0].[Name], [s0].[SecondaryManagerId], [s1].
[Id], [s1].[Email], [s1].[Logon], [s1].[ManagerId], [s1].[Name], [s1].[SecondaryManagerId]
      FROM [Appraisals] AS [a]
      INNER JOIN [Staff] AS [s] ON [a].[StaffId] = [s].[Id]
      LEFT JOIN [Staff] AS [s0] ON [s].[ManagerId] = [s0].[Id]
      LEFT JOIN [Staff] AS [s1] ON [s].[SecondaryManagerId] = [s1].[Id]
      WHERE [a].[Id] = @__id_0
```

Note that this works if only one of the second-level Includes is used, but if both are used, then one is left null.

**Comment by AndriySvyryd** [comment]
The issue here is that the relationship `Staff.Manager -> Staff` is configured as 1:1, but the seed data is for a 1:* relationship. The data seeding now inserts the inconsistent data as specified thus the repro is failing again.
