### ISSUE TITLE
Usage of Column type will create a messed up migration

### ISSUE THREAD

**Issue by ANM86** [dotnet/efcore#24365]
In my migration always the default scale and precision (18,2) is applied to a use defined type. In my case the UDT has does not match 18,2. So the migration cannot be applied to the database, until I remove it manually from the migration.cs file

DBContext.cs:

```
foreach (var property in _modelBuilder.Model.GetEntityTypes()
                                            .SelectMany(t => t.GetProperties())
                                            .Where(p => p.ClrType == typeof(decimal)))
{
    property.SetColumnType("DefNumeric");
}
```

Migration.cs:

```
PerIC = table.Column<decimal>(type: "DefNumeric(18,2)", nullable: false)  //Wrong
PerIC = table.Column<decimal>(type: "DefNumeric", nullable: false)        //Correct
```

Is there a way to stopp appliying the default scale & precision  autmatically to an UDT?

**Comment by ajcvickers** [comment]
Related: #20773 #12796
