### ISSUE TITLE
[Question] In memory database persistence

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/efcore#2436]
How does in memory persistence work? Is a database persisted per thread?

**Comment by davidroth** [comment]
No, its not per thread, it's per appdomain and uses thread safe collections under the hood.
You can clear persisted values by calling ```context.Database.EnsureDeleted()```

**Comment by ajcvickers** [comment]
@MaximBalaganskiy @davidroth Technically it is per IServiceProvider root. Usually this will mean per app-domain, but it does mean that by using different IServiceProvider instances when constructing your context you can control the lifetime or even use multiple in-memory databases at the same time. However, most apps will have one IServiceProvider root per app domain. Also, you can call UseInMemoryStore(persist: false) in which case the in memory database will be freed when the context is disposed.
