### ISSUE TITLE
How to find which property is not mapped correctly

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#24378]
Hi,

sometimes I have an error in mapping for various reasons and I get exceptions like this:

> **System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'**.
>    at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void* toTypeHnd, Object obj)
>    at System.Runtime.CompilerServices.CastHelpers.ChkCastClassSpecial(Void* toTypeHnd, Object obj)
>    at System.Runtime.CompilerServices.CastHelpers.ChkCastClass(Void* toTypeHnd, Object obj)
>    at Microsoft.Data.SqlClient.SqlBuffer.get_String()
>    at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
>    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
>    at 

or
>  System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

How do I find out, which property/column is causing the exception?

**Comment by ajcvickers** [comment]
@Liero Use `EnableDetailedErrors` as shown here: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#getting-detailed-messages

**Comment by Liero** [comment]
Oops, shame on me for not reading the docs properly. Thanks!
