### ISSUE TITLE
Could not find type mapping for column 'xxxx' with data type 'timestamp'. Skipping column.

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/efcore#24374]
Hi.
How to solve a problem?

`Scaffold-DbContext "server=127.0.0.1;database=db2;user=root;password=pasword;Allow Zero Datetime=true;Convert Zero Datetime=true" MySql.EntityFrameworkCore -Context "AppDBContext"
`
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.12" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.12">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
<PackageReference Include="MySql.EntityFrameworkCore" Version="3.1.10" />
```

**Comment by roji** [comment]
@EvgenyPrikhodko you probably need to raise this with Oracle support, who are the ones responsible for MySql.EntityFrameworkCore.

**Comment by EvgenyPrikhodko** [comment]
https://forums.mysql.com/read.php?38,695331

**Comment by EvgenyPrikhodko** [comment]
https://bugs.mysql.com/bug.php?id=102934
