### ISSUE TITLE
Is it okay to use EF Core 5.0's DbContextFactory in traditionally scoped, non Blazor Server applications?

### ISSUE THREAD

**Issue by felinepc** [dotnet/efcore#24380]
EF Core 5.0 added `AddDbContextFactory` and `AddPooledDbContextFactory` to register a factory for creating `DbContext` instances in DI that benefits Blazor server applications, where traditionally scoped `DbContext` via DI does not work well.

But we still have a problem: many of us use the common "layered" architecture with EF Core, where a "service layer" library has access to injected `DbContext`. It can be a repository, but doesn't have to be.

Now if this service layer is shared by both Blazor Server app and some other traditional ASP.NET Core applications, such as a web API, we have a complication for `DbContext` injection, because they're done differently with `DbContextFactory`.

We can have something like this:
```
public class CarService : ICarService
{
    private readonly IDbContextFactory<CarDbContext> _dbContextFactory;
    private readonly CarDbContext _context;

    public CarService(IDbContextFactory<CarDbContext> dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public CarService(CarDbContext context)
    {
        _context = context;
    }
}
```
Now Blazor Server or a traditional API can of course choose the appropriate constructor and inject what's available, but the problem is that `DbContext` instances created by `DbContextFactory` requires manual disposal via `using` statements. 

So we cannot simply initialize this class and assign the same private `_context` instance like `_context = dbContextFactory.CreateDbContext()` in constructor and leave the rest of the code intact. Instead, the methods in the code always have to add a check for whether the `DbContext` is directly injected via scoped DI (managed, no need for disposal) or the factory (must do `using var context = _dbContextFactory.CreateDbContext()`).

So I wonder if it'd be appropriate to simply use `DbContextFactory` in non-Blazor server apps as well? I'd assume there's a performance penalty for doing so compared to the scoped approach, but would it be considered significant for the average app? 

If for some reason this is not a good approach, what's the best way to handle such scenarios?

**Comment by ajcvickers** [comment]
> So I wonder if it'd be appropriate to simply use DbContextFactory in non-Blazor server apps as well? I'd assume there's a performance penalty for doing so compared to the scoped approach, but would it be considered significant for the average app?

Yes, it's fine to use the factory for any kind of app. As you point out, you will need to dispose the context manually when doing this, but otherwise everything else should work the same. I'd be very surprised if there is a measurable perf difference between the approaches, but if you do find one it would be great if you let us know.
