### ISSUE TITLE
add-migration not recognising changes.

### ISSUE THREAD

**Issue by oliverslade** [dotnet/efcore#2438]
When attempting to use the command add-migration in the Package Manager Console an empty DbMigration file is produced containing nothing but the two empty methods:
  public override void Up()
        {
        }

  public override void Down()
        {
        }

These methods should contain a number of changes that have occurred including new tables however nothing shows up.

**Comment by bricelam** [comment]
Weird. Could you share more of your project? (e.g. your DbContext class, `Startup.cs`, `config.json`...)

**Comment by bricelam** [comment]
Closing for now. Feel free to re-open with the information requested.
