### ISSUE TITLE
Orphan data support.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#24381]
I want to create 2 entities that are related but I would like it to support orphan records. Of course this sounds strange on first sight. But sometimes the orphan data is just registered earlier and usually the data gets resolved later.

    public class Parent
    {
        public int Id { get; set; }
 
        public string Code { get; set;}

        public ICollection<Child> Children { get; set;} 
    }

    public class Child
    {
        public int Id { get; set; }

        public string ParentCode { get; set; }

        [NotMapped] // Because otherwise it will create a FK.
        public Parent Parent { get; set; }
    }

When mapped the child would get a ParentId and all works out. But now I have children with an optional "parentCode" but the parent doesn't have to exist. So AlternateKeys wouldn work right? 

I would still like to query the child and include it's parent (if it does exists) and the other way around get all the children for a parent.

    dbcontext.Parents.Include(p => p.Children);

    dbcontext.Children.Include(c => c.Parent);

**Comment by ajcvickers** [comment]
@qsdfplkj Looks like you are looking for #13146. If so, please vote (👍) for that issue.

**Comment by qsdfplkj** [comment]
I guess it's about the same thing. Though I could think of a different approach where the ParentId is resolved during inserting the parent or updating the child's parentCode).
