### ISSUE TITLE
Intercept backing field calls to kick in lazy loading

### ISSUE THREAD

**Issue by alexmurari** [dotnet/efcore#24390]
As you already know, accessing backing fields of navigation properties doesn't load them.

```csharp
public class Blog
{
  private readonly List<Post> _posts = new List<Post>();

  public virtual IReadOnlyList<Post> Posts => _posts;

  public void AddPost(Post post)
  {
      if(_posts.Count > 10) // This call should be intercepted and lazy load should kick in...
         // some validations...

     _posts.Add(post);
  }
}
```

One solution is to access the navigation property directly, so the related data is loaded, but it hurts the code style, I would prefer to work directly with the backing fields.

The method referencing the backing field would need to be marked as `virtual` so it can be intercepted to load the backing field data.

I assume this was already discussed, and is this way by design, but I couldn't find anything about it.

So, is this possible? Do you consider someday enabling lazy loading for backing fields?

If so, leave this issue open on the backlog for voting.

**Comment by ajcvickers** [comment]
@alexmurari Backing field access cannot be directly intercepted. Can you explain more what you mean by, "The method referencing the backing field would need to be marked as virtual?" Which method are you referring to? Can you show it in code?

**Comment by alexmurari** [comment]
@ajcvickers

Let's follow my initial example.

The method `AddPost` in the `Blog` entity references the `_posts` backing  field.

Original code:

```csharp
public void AddPost(Post post)
{
    if(_posts.Count > 10) // This call should be intercepted and lazy load should kick in...
       // some validations...

   _posts.Add(post);
}
```

We then make this method `virtual`:

```csharp
public virtual void AddPost(Post post)
```

When EF creates the proxy for this entity, it analyzes the method body to see if it references any backing field, like our `_posts` field.

Then, in the proxy, it overrides that method, introducing a call to load the backing field data before the method is executed.

```csharp
public class BlogProxy
{
  public override void AddPost(Post post)
  {
      // Call a EF method here to load the backing field data..
     EF.Load(_posts); // Just a wild guess of how it would work, I don't know the implementation details...
     // load other backing fields if necessary....

     base,AddPost(post); // Invokes the original method now that the backing fields are loaded.
  }
}
```

**Comment by ajcvickers** [comment]
Thanks for the additional info.

> When EF creates the proxy for this entity, it analyzes the method body to see if it references any backing field, like our _posts field.

This would be fragile and/or complex and is not something we plan to do.

**Comment by alexmurari** [comment]
To achieve this I can only think of overriding the calling method to inject the loading code there, before the backing field usage.

I was hoping that the way lazy loading works for properties could be reused for this, but I agree that this would be tricky.

**Comment by ajcvickers** [comment]
@alexmurari You can achieve what you want by [using the lazy-loading infrastructure directly](https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies), instead of using proxies. This allows lazy-loading to be triggered from anywhere. For example:

```C#
public class Blog
{
    public Blog()
    {
    }
    
    private Action<object, string> LazyLoader { get; set; }
    private Blog(Action<object, string> lazyLoader)
    {
        LazyLoader = lazyLoader;
    }
    
    public int Id { get; set; }
    
    private List<Post> _posts = new();
    public IReadOnlyList<Post> Posts => LazyLoader.Load(this, ref _posts);

    public void AddPost(Post post)
    {
        LazyLoader.Load(this, ref _posts);

        if (_posts.Count < 10)
        {
            _posts.Add(post);
        }
    }
}
```

**Comment by alexmurari** [comment]
@ajcvickers Thanks for the example. Altough It works I can't mix infrastructure and domain code together. The domain code is supposed to be pure. Do tou think that it's possible to implement a feature to achieve the same  behavior with proxies by injecting the loading code dynamically?

**Comment by ajcvickers** [comment]
@alexmurari Yes, you could create your own proxies to do this. However, I would strongly argue that any domain code that depends on _any_ lazy-loading functionality is a long way from pure. This is one reason why many people (including myself) consider lazy-loading to be an anti-pattern.
