### ISSUE TITLE
String Primary Key - Use nvarchar(MAX) instead of nvarchar(450)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#24392]
## Ask a question
How do I make a table with a string primary key use NVarChar(MAX) instead of NVarChar(450)?

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system:  Windows 10
IDE: Visual Studio 2019 16.9

**Comment by ErikEJ** [comment]
Not possible, as a primary key is enforced by a unique index, and the key can only be about 900 chars wide.
