### ISSUE TITLE
InvalidOperationException & InvalidCastException

### ISSUE THREAD

**Issue by CodeGlitcher** [dotnet/efcore#24411]
## Ask a question
Hello,

On our production system we are seeing two strange exception during 2 select statements:

The first is: Unable to cast object of type 'System.32' to type 'System.Boolean'

The code we execute is: 
`return _context.PingPongs.Any(e => e.SequenceNumber == sequenceNumber);`

Generates the following query:
```
SELECT CASE
   WHEN EXISTS (
      SELECT 1
	  FROM [PingPongs] as [p]
	  WHERE [p].[SequenceNumber] = __sequenceNumber_0) THEN cast(1 AS bit)
	  ELSE CAST (0 AS bit)
 END
```

The query is correct and 99% of the time this works, but somethings we get this invalid cast exception.

The second exception we see is: The underlying reader doesn't have as many fields as expected.
During a other select:
```
 var entity = _context.RtuProvisioningModels
                .Where(e => includeRemovedBoxes || e.State != Entities.ProvisioningProcessState.BoxRemoved)
                .Include(e => e.ConfigurationMutations)
                    .ThenInclude(cm => cm.CauseOfMutationMessage)
                .Include(e => e.OldConfigurationMutations)
                .SingleOrDefault(x => x.BoxId == boxId);
```
The query
```
SELECT [t].[Id], [t].[BoxFirstOperationalUtc], [t].[BoxId], [t].[BoxLatitude], [t].[BoxLongitude], [t].[BoxOperationalUtc], [t].[BoxType], [t].[Build], [t].[CreatedAtUtc], [t].[DesiredStreetlightScheduleSlotA], [t].[DesiredStreetlightScheduleSlotB], [t].[DesiredTariffScheduleSlotA], [t].[DesiredTariffScheduleSlotB], [t].[DeviceConnectionEstablishedUtc], [t].[DeviceStartedUtc], [t].[FortinetLocalUserId], [t].[IPAddress], [t].[InitialAssetConfigurationJson], [t].[InitialStreetlightScheduleUploadHistoryCorrelationId], [t].[InitialTariffScheduleUploadHistoryCorrelationId], [t].[IsSensorBox], [t].[Manufacturer], [t].[Municipality], [t].[ProcessCorrelationId], [t].[Province], [t].[SLConnected], [t].[SalvadorDeviceId], [t].[SerialNumber], [t].[State], [t].[StationId], [t].[StreetlightScheduleCode], [t].[YearOfManufacture], [c].[Id], [c].[CauseOfMutation], [c].[CreatedAtUtc], [c].[Engineer], [c].[JsonPatch], [c].[MutationDate], [c].[MutationId], [c].[OriginatedFrom], [c].[ReviewComment], [c].[Reviewer], [c].[RtuProvisioningModelId], [c].[State]\nFROM (\n    SELECT TOP(2) [r].[Id], [r].[BoxFirstOperationalUtc], [r].[BoxId], [r].[BoxLatitude], [r].[BoxLongitude], [r].[BoxOperationalUtc], [r].[BoxType], [r].[Build], [r].[CreatedAtUtc], [r].[DesiredStreetlightScheduleSlotA], [r].[DesiredStreetlightScheduleSlotB], [r].[DesiredTariffScheduleSlotA], [r].[DesiredTariffScheduleSlotB], [r].[DeviceConnectionEstablishedUtc], [r].[DeviceStartedUtc], [r].[FortinetLocalUserId], [r].[IPAddress], [r].[InitialAssetConfigurationJson], [r].[InitialStreetlightScheduleUploadHistoryCorrelationId], [r].[InitialTariffScheduleUploadHistoryCorrelationId], [r].[IsSensorBox], [r].[Manufacturer], [r].[Municipality], [r].[ProcessCorrelationId], [r].[Province], [r].[SLConnected], [r].[SalvadorDeviceId], [r].[SerialNumber], [r].[State], [r].[StationId], [r].[StreetlightScheduleCode], [r].[YearOfManufacture]   
FROM [RtuProvisioningModels] AS [r] 
WHERE ([r].[State] <> 40) AND ([r].[BoxId] = @__boxId_0)\n) AS [t]
LEFT JOIN [ConfigurationMutations] AS [c] ON [t].[Id] = [c].[RtuProvisioningModelId]
ORDER BY [t].[Id], [c].[Id]",    
```
Aggain, the query works fine 99% of the time. But sometimes it results in a exception.
If we retry the same action 30 mins later it works fine.
The exception:
```
        "error": {
          "Type": "System.InvalidOperationException",
          "Message": "The underlying reader doesn't have as many fields as expected.",
          "TargetSite": "Void InitializeFields()",
          "Data": {},
          "HResult": -2146233079,
          "Source": "Microsoft.EntityFrameworkCore.Relational",
          "StackTrace": "   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeFields()
           at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList`1 columns)
         at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(IReadOnlyList`1 columns)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)  
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()"
        },
```
This only happens on our production system and we have not found a way to trigger this.
This makes it difficult to find the excact problem. 
Currently we suspect it has something todo with the EnableRetryOnFailure we have set on the DbContext or when a other database is hit with a lot querys. 
```
  services.AddDbContext<ConfigDispatcherContext>(
                (s, options) => options.UseSqlServer(
                    s.GetRequiredService<DbConnection>(),
                    providerOptions => providerOptions.EnableRetryOnFailure()),
                ServiceLifetime.Scoped,
                ServiceLifetime.Scoped)
```

We are experimenting with lowering the load on sql server. 
But so far no results.  Next week we are going to try disabling the EnableRetryOnFailure, but we are not very hopefull this will make a differnce.
Does anyone know what could cause these exceptions and what we could do to prevent this? 
(We have validated that the database is up to date with the lastest migrations and the db context is not used in parallel. )

### Include provider and version information

EF Core version:  v3.1.12
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET core 3.1)
Application Operating system:
centos 7 with docker
base image: dotnet/core/aspnet:3.1 
Sql server:
Window server 
Sql server 2019 standard edition
4 core 16 gb ram. 
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by henrikdahl8240** [comment]
If it's easy for you to try using .NET 5.0, perhaps you should do that. It might be, that some error has been corrected. I have read, that the problem is on your production server only, so perhaps it's not so easy.

**Comment by ajcvickers** [comment]
@CodeGlitcher These look like they could be multi-threading issues. Are you sure that a single DbContext instance is not being used by multiple threads concurrently? Are you awaiting all async operations before starting another?

**Comment by CodeGlitcher** [comment]
I have check our code aggain and every call is awaited.
We are proccing messages from rabbitmq and for each message a new scope is created

``` 
           using (var scope = _serviceProvider.CreateScope())
            {
                var messageHandler = scope.ServiceProvider.GetRequiredService<TMessageHandler>();

                await messageHandler.HandleAsync(message.Body, cancellationToken);
            }
```
The DbContext is marked scoped and the DbConnection as Transient. So a new connection is created (using connection string) for each time a new DbContext  is created. 
There are also no singleton objects that use a database connection. 
And I do assume that ` var connection = new SqlConnection(connectionString);` is threadsafe and will create a new connection or use 1 from the  connection pool. But not give back the same connection to 2 dbcontexts.

**Comment by idobosman** [comment]
> If it's easy for you to try using .NET 5.0, perhaps you should do that. It might be, that some error has been corrected. I have read, that the problem is on your production server only, so perhaps it's not so easy.

Is there anything specific that makes you think an upgrade might be the solution to this problem? I am curious as it might give valuable insights to work with.

**Comment by henrikdahl8240** [comment]
In my case I am dealing with a huge enterprise solution. Here I only refer to the backend. I completely gave up to use version 3 of .NET Core because there were just so many things which didn't work at all. I was very active during the period of preliminary versions of .NET 5. I had many dialogues with staff at the EF Core team. All the issues I addressed were being fixed and I am very satisfied with version 5. I guess, that most likely you will find many benefits from changing to version 5. I have not found any relevant problems with .NET 5.

**Comment by henrikdahl8240** [comment]
Concerning your code, where you write "I have check(ed) our code again and every call is (being) awaited.": And you do not have any method being async void instead of async Task by mistake, so the awaiting will not be honoured?

**Comment by ajcvickers** [comment]
@CodeGlitcher I don't think there is going to be much we are able to do here unless we can reproduce what you are seeing. I understand that it may be difficult to create a small repro for this, but I think that's what we will need. You could try maybe running the problematic queries in a tight loop?

**Comment by CodeGlitcher** [comment]
I understand, fixing a problem without a repro is not easy. 
I have ran our code in a loop and tried to run it parrallel (with and without using the same db context, but i was not able to reproduce the error.

Since last week we have lowered the load on our application and the problem has not reappeard. 
Before we where receiving a few thousend messages every 5 mins and now only every 15,
because of this we are no longer building a backlog of work that needs processing so after 5 or 6 mins our cpu usage drops back to a few %.  
Given this information i think you are right and we do have some sort of a multi threading issue in our application, but 1 that does not appear easy. Perhaps 1 day we will find the source of our problem, but for now we have decided to move on until the issue reappears.

Thank you all for your input.

**Comment by intb9** [comment]
@ajcvickers I'm having a similar issue if my SQL query doesn't return a property that should be returned (i.e. a property that appears in the C# model):
If I use EnableRetryOnFailure I get this error: "The underlying reader doesn't have as many fields as expected" which is not indicative. 
However if I don't use EnableRetryOnFailure I get an indicative error which says the name of the missing field, so I can understand exactly what is the problem
