### ISSUE TITLE
Guid.ToString() in EF Core is not returning lowercase like EF 6 and C# itself

### ISSUE THREAD

**Issue by langdonx** [dotnet/efcore#24419]
Basic query (`Uuid` is of type `Guid`):

```C#
from u in Users select u.Uuid.ToString()
```

EF 6

```SQL
SELECT 
LOWER( CAST( [Extent1].[uuid] AS nvarchar(max))) AS [C1]
FROM [dbo].[Users] AS [Extent1]
```

> c3efd4b8-f1ab-4719-ac02-18ee0569b530

EF Core 3.x

```SQL
SELECT CONVERT(VARCHAR(36), [u].[uuid])
FROM [Users] AS [u]
```

> C3EFD4B8-F1AB-4719-AC02-18EE0569B530

C# (https://dotnetfiddle.net/SRTdiF)

```C#
Console.WriteLine(Guid.NewGuid().ToString());
```

> e3743d33-47e3-4dc1-a141-95e3637ea0a8

#### Provider and version information

EF Core version: 3.1.12
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netstandard2.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.1

**Comment by ajcvickers** [comment]
We discussed this, but decided to not change the behavior here because:

- ToString translations are provider-specific and return whatever the representation the database creates
- We try to generate simple SQL, and the lower casing is not needed here unless you really need the string to be in lower case, in which case this can be done explicitly
- It would break existing apps depending on the current casing

**Comment by inforithmics** [comment]
This can be achieved by an DbCommandInterceptor replacing CONVERT(VARCHAR(36) ...) with LOWER(CONVERT(VARCHAR(36) ...))
```
public class ToLowerGuidStringInterceptor : DbCommandInterceptor
{
    public const string RegexReplace = "LOWER(CONVERT(VARCHAR(36), $1))";
 
    private static readonly Regex Regex = new Regex(
        "CONVERT\\(VARCHAR\\(36\\), ([^\\)]*)\\)",
        RegexOptions.CultureInvariant
        | RegexOptions.Compiled);

    public override InterceptionResult<DbDataReader> ReaderExecuting(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
    {
        command.CommandText = Regex.Replace(command.CommandText, RegexReplace);
    }
}
```

Registering with

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{            
    optionsBuilder.AddInterceptors(new ToLowerGuidStringInterceptor());
}
```

**Comment by HanMoeHtet** [comment]
> * It would break existing apps depending on the current casing

Then you should provide that in ef 6 to ef core migration guide.

**Comment by HanMoeHtet** [comment]
I have modifed @inforithmics 's code to check if the column we are converting is `uniqueidentifer` or not. But this should be a temporary fix.


```cs
public class ToLowerGuidStringInterceptor : DbCommandInterceptor
{
    public const string RegexReplace = " (CASE WHEN TRY_CONVERT(uniqueidentifier, $1) IS NOT NULL THEN LOWER(CONVERT(varchar(36), $1)) ELSE CONVERT(varchar(36), $1) END) ";
 
    private static readonly Regex Regex = new Regex(
        "CONVERT\\(VARCHAR\\(36\\), ([^\\)]*)\\)",
        RegexOptions.CultureInvariant
        | RegexOptions.Compiled | RegexOptions.IgnoreCase);

    public override InterceptionResult<DbDataReader> ReaderExecuting(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
    {
        command.CommandText = Regex.Replace(command.CommandText, RegexReplace);

        return base.ReaderExecuting(command, eventData, result);
    }
}
```

**Comment by HanMoeHtet** [comment]
There is a better answer for that [here](https://stackoverflow.com/questions/76981612/ef-6-to-ef-core-generate-different-cases-for-guid-tostring/76983398#76983398) .
