### ISSUE TITLE
Calls to OnModelCreating

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24413]
## Ask a question

In which situations is `OnModelCreating()` called more than once? I have code that should only be run once and needs access to DI and to query a DbSet.

Can [`OnModelCreating()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.onmodelcreating?view=efcore-5.0) be used for this purpose? If not, is there an alternative to a static constructor so that DI objects are available and DbSets can be queried?

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by roji** [comment]
@mrlife can you please provide more context on why you think you need to query a DbSet from OnModelCreating? OnModelCreating is what configures the model, so it's necessary to complete that before any DbSet is ever queried. In almost all normal applications, OnModelCreating is called exactly once at program startup, and never again after that.

If you provide more details, we can perhaps suggest an alternative approach.

**Comment by mrlife** [comment]
@roji Yes, thanks for your quick reply. I am starting to use the [Audit.EntityFramework.Core](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#entity-framework-data-provider) package, and its configuration should be run once. Since I need access to DI and to query a DbSet, sounds like `OnModelCreating` is not the best place. Is there another option?

**Comment by roji** [comment]
[The docs](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#usage) for that package provide various ways to configure it - by inheriting from a special DbContext base class, or by calling SetConfig on a static DbContextHelper. Is that not sufficient?

**Comment by mrlife** [comment]
@roji The part I linked to has the configuration I'm talking about (example below), which is in addition to what you're asking about.

```
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .Map<Order, Audit_Order>()
            .Map<OrderItem, Audit_OrderItem>()
            .AuditEntityAction<IAudit>((evt, entry, auditEntity) =>
            {
                // access to DI and to query a DbSet here
            })
        )
    );
```

**Comment by roji** [comment]
You may want to turn to that library's author for support, but this code may simply belong in your Main method, or Startup, or anywhere else on program startup.

**Comment by mrlife** [comment]
The solution here was to call `Audit.Core.Configuration.Setup()` in `App.razor`'s `OnInitialized()`.
