### ISSUE TITLE
Ef 5.0.4 bug with hierarchy self refrence navigation property 

### ISSUE THREAD

**Issue by FakeOwner** [dotnet/efcore#24425]
Information : 
.Net 5.0.4
WPF
C# 9
Windows 10
SQL server 2019

```c#
public class OCode
    {
        public long Id { get; set; }

        public long ProjectId { get; set; }

        public string Guid { get; set; }

        public string Title { get; set; }

        public virtual Project Project { get; set; }

        public virtual ICollection<OCValue> OCValues { get; set; }
    }
}

public class OCValue 
    {
        public long Id { get; set; }

        public long ParentId { get; set; }

        public long OCodeId { get; set; }

        public long OCValueTypeId { get; set; }

        public string Value { get; set; }

        public string Description { get; set; }

        public bool? IsCollapsed { get; set; }

        public virtual OCValue Parent { get; set; }
        public virtual ICollection<OCValue> Children { get; set; }
        public virtual OCode OCode { get; set; }
        public virtual OCValueType OCValueType { get; set; }
    }
}
```

When I fill navigation property for table OCode without hierarchy( all OCode.OCValues.Children is null)  all data successfully inserted but when one of the records in table OCValues has a child (navigation property Children )OCode not set Id in OCValue (OCodeId  = 0) by navigation property and throw error Id not set.

See Code example

```c#
OCode oCode = new OCode()
OCode.OCValues = flatData; // all children property in null. it successfully inserted

var heirarchyData = flatData[0].Children = new OCValue()
OCode.OCValues = heirarchyData; // one of record children has data and show error OCValue.OCodeId is 0
```

navigation property insert data not work well in hierarchy self-reference tables.

**Comment by smitpatel** [comment]
`OCodeId` in the nested `OCValue` (inside the children) is non-nullable (long) but the navigation `OCode` for is not set. Hence it shows error.
The way your model is that `OCode` contains multiple `OCValue` and each `OCValue` is connected to an `OCode` but when you are assigning new `OCValue` in the nested collection (`Children`) you also need to assoacite that new `OCValue` to an `OCode`.

**Comment by FakeOwner** [comment]
hello, thank you for your response.

`OCodeId ` in `OCValue `  must be requred.

Is it possiable Ef put `OCodeId ` in `OCValue`  Children  like all `OCValue`  parent?

When I insert nested model, Fk set successfully by EF.
But when `OCValue` need to save if Children is set (children need OCodeId) `OCodeId` not set by EF

**Comment by smitpatel** [comment]
> Is it possiable Ef put OCodeId in OCValue Children like all OCValue parent?

When you set `OCode.OCValues` EF Core has `OCodeId` to put into associated `OCValues`. But in the code above you are adding to `OCValues.Children` a new `OCValues` without specifying associated `OCode`. Essentially it is incomplete graph where EF Core cannot complete the graph through fixup. Whenever you initialize new `OCValues` either you need to add it `OCode.OCValues` directly or assign `OCode` navigation property otherwise it won't work.

**Comment by FakeOwner** [comment]
smitpatel thank you for your description.

I want to insert data relational by navigation property like :

OCValue ocValue = new();
OCValue.Children = new();
OCValue.Children.Add(new(P1=p1, P2=p2,Children = new(P1=p1, P2=p2,Children = new(etc))));
context.Db.Add(ocValue);
context.SaveChanges();

Is it possible in ef 5?
