### ISSUE TITLE
EDMX support

### ISSUE THREAD

**Issue by SmartDev210** [dotnet/efcore#24424]
## Asking about EDMX support on EF Core

Hi EF Core developer team.
I appreciate your effort and I am happy to use EF Core in .NET/.NET Core web apps.

Just what I want to ask is about the EDMX support in EF Core.
I have complex database and it contains many stored procedures. I use them using EDMX with EF in ASP.NET MVC.
I want to migrate it to .NET/.NET Core app.
but really migrate the EF is huge work and I want to ask if EF Core will support EDMX in the future.

And also I want to know if EF Core will support full Database first approach (not the Scaffold).

Thanks.

**Comment by ErikEJ** [comment]
- There are no plans to support EDMX with EF Core.
- You can use EF6 with .NET Core
- EF Core Power Tools can map stored procedures (and your tables/views) for you. 
- It also allows you to evolve the model if you play be the rules.

**Comment by SmartDev210** [comment]
Thanks Erik,
One more question.
Can I use create edmx file in separate project and reference it in .NET Core project?

**Comment by ErikEJ** [comment]
Yes: https://erikej.github.io/ef/dotnetcore/2020/06/15/ef6-use-edmx-dotnetcore.html

**Comment by SmartDev210** [comment]
Great, Thanks
