### ISSUE TITLE
EntityFramework with .NetFramework 4.5.1 complie error.

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#2442]
When i build a asp.net class library that refrenced ef7 package, an error occurred:

error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

my project.json file like this:

``` JSON
"dependencies": {
    "EntityFramework.Relational": "7.0.0-beta4",
    "EntityFramework.SqlServer": "7.0.0-beta4"
  },
  "frameworks": {
    "net451": {
      "dependencies": { }
    },
    "dnx451": {
      "dependencies": { }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-22816",
        "System.Linq": "4.0.0-beta-22816",
        "System.Threading": "4.0.10-beta-22816",
        "Microsoft.CSharp": "4.0.0-beta-22816"
      }
    }
```

I tried to change the "net451" section, but still can not solve the problem:

``` JSON
"net451": {
      "frameworkAssemblies": {
        "Microsoft.CSharp": "4.0.0.0",
        "System": "4.0.0.0",
        "System.Core": "4.0.0.0",
      }
}
```

Another project No EF7 referenced can complie with "net451". Is it a vs2015RC compile BUG?

BTW: Forgive my bad English!

**Comment by bricelam** [comment]
Add the following.
```JSON
"net451": {
    "frameworkAssemblies": {
        "System.Collections": "4.0.0.0",
        "System.Diagnostics.Debug": "4.0.0.0",
        "System.Diagnostics.Tools": "4.0.0.0",
        "System.Globalization": "4.0.0.0",
        "System.Linq": "4.0.0.0",
        "System.Linq.Expressions": "4.0.0.0",
        "System.Linq.Queryable": "4.0.0.0",
        "System.ObjectModel": "4.0.0.0",
        "System.Reflection": "4.0.0.0",
        "System.Reflection.Extensions": "4.0.0.0",
        "System.Resources.ResourceManager": "4.0.0.0",
        "System.Runtime": "4.0.10.0",
        "System.Runtime.Extensions": "4.0.0.0",
        "System.Threading": "4.0.0.0"
    }
}
```
It is caused by tension between DNX and MSBuild/NuGet (See aspnet/dnx#2031)

**Comment by radenkozec** [comment]
Hi @bricelam @rowanmiller 
I have a similar issue on beta5 but without EntityFramework.
Have a error:
>The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	
My project.json:

    "dependencies": {
    "Hue.Model": "1.0.0-*",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
    "System.Net.Http": "4.0.0-beta-23019",
    "System.Data.Common": "4.0.0-beta-23019",
    "System.Data.SqlClient": "4.0.0-beta-23019",
    "Newtonsoft.Json": "7.0.1-beta3"
     },

    "frameworks": {
    "dotnet": {

    },
    "dnx451": {

    },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23019",
        "System.Runtime": "4.0.20-beta-23019",
        "System.Runtime.Extensions": "4.0.10-beta-23019"
       }
      }
     }
     }

I also reference another .NET Core Class Library Hue.Model like you can see in project.json.
Any tips?
