### ISSUE TITLE
Lazy loading without proxies

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#24429]
I am referring to https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies.

If I new Blog(), set Posts to something, then I cannot get Posts because LazyLoader is null.

Should I instantiate a Blog in some other way than using new or I should not be able to get collections until they have been persisted?

**Comment by ajcvickers** [comment]
@henrikdahl8240 The lazy-loader is set when the entity is attached to the context. Can you explain a bit more about what you are trying to do? Does the entity instance represent an instance already in the database? Do you intend to Add/Attach/Update it?
