### ISSUE TITLE
Consider retrying strategy and connection-breaking exceptions

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#24432]
https://github.com/dotnet/SqlClient/issues/971 describes a situation where a SQL Server exception breaks ("dooms") the connection; our retrying strategy mechanism causes the DbConnection to be closed and re-opened, which should get a new physical connection and all should be well (the problem there is an SqlClient issue).

However, what happens if the (relational) connection has already been explicitly opened by the user, and so the retrying strategy would *not* close/re-open the DbConnection? The retries would definitely fail in that case. In other words, some exceptions are transient in the sense that we can retry immediately, and other allow us to retry but only after opening a new connection.

Some things we could do... The retrying strategy can detect if the connection is broken (by checking DbConnection.State). If it's broken and there was no transaction, it can close/re-open and retry then. If there was a transaction, we cannot retry, but we can at least avoid useless retries which are bound to fail.

**Comment by AndriySvyryd** [comment]
We call `RelationalConnection.Open` whenever we (re)try an operation and that takes care of this.
https://github.com/dotnet/efcore/blob/809fe7a219c99fbe4f3576ef42bd084d4a6ce056/src/EFCore.Relational/Storage/RelationalConnection.cs#L610-L622

**Comment by roji** [comment]
You're right, and we also don't allow (retrying) execution within a transaction, which would have been problematic here.

However... this made me realize that we could support retrying within a transaction, thanks to savepoints - create a savepoint before each attempt, and roll back to it if we need to retry. If we implement this, we'd need to again take special care with broken connections - if the connection's state is Broken after an attempt, and we're within a transaction, we absolutely shouldn't retry.

Does the above sound right?

**Comment by AndriySvyryd** [comment]
I'd prefer that the execution strategy fails fast. If a user needs to wait until the connection is broken to learn that an operation within a transaction can't always be retried they will not have a good day.

**Comment by roji** [comment]
But there are some pretty significant scenarios where the operation can be retried (e.g. optimistic concurrency) - is it a good idea to block retries on those just for this?

Put another way, retries are a best effort thing only - they don't guarantee success in any case. So does it matter to users whether an operation can or cannot be retried in specific scenarios?

**Comment by AndriySvyryd** [comment]
The main purpose of the retrying execution strategy is to handle transient errors and most of them result in the connection being broken or closed. Optimistic concurrency errors are not retried by default as they require some user resolution code. The users are free to use a strategy based on our `ExecutionStrategy` implementation for their retry logic and in that case they can override `OnFirstExecution` and `OnRetry` to take advantage of save points.

**Comment by roji** [comment]
Design discussion: it's possible to have a retrying strategy that retries optimistic concurrency assuming the querying is part of the retry block as well (and not just SaveChanges):

```c#
await using (var ctx1 = new BlogContext())
{
    var firstAttempt = true;

    var strategy = ctx1.Database.CreateExecutionStrategy();
    await strategy.ExecuteAsync(async () =>
    {
        var blog1 = await ctx1.Blogs.SingleAsync();
        // Concurrent update occurs
        blog1.Name = "Changed name2";
        await ctx1.SaveChangesAsync();
    });
}
```

This is pretty close to first-one-wins (where optimistic concurrency isn't needed), except it does reload the database row in case of a concurrency update, providing better data coherency in some scenarios. The above can even work within a transaction, it a savepoint is created before each retry.

However, we don't think such *automated* retrying of optimistic concurrency failures is something that's needed in common scenarios.
