### ISSUE TITLE
How does EF core know which class to be considered as model.

### ISSUE THREAD

**Issue by vijaykumarkolli** [dotnet/efcore#24431]
in the given link 

https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs

there is example given 

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}

when i run migration command "Add-Migration InitialCreate"  How does EF core tools identify which class to consider as model.

**Comment by roji** [comment]
That information is detailed in the [modeling docs](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations).

**Comment by vijaykumarkolli** [comment]
Thanks.
