### ISSUE TITLE
Get DebugView in code with EF Core 6 

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#24434]
I used this with EF core 5 to get the DebugView, but it no longer works with EF Core 6 - what is the replacement?

`dbContext.Model.AsModel().DebugView.LongView;`

EF Core version: 6.0 preview2
Target framework: .NET 5.0
Operating system:
IDE: Visual Studio 2019 16.9

**Comment by roji** [comment]
This should work: `((Model)ctx.Model).DebugView.LongView`.

@AndriySvyryd should we make it easier to access DebugView in the debugger (e.g. add an accessor to IModel and other metadata interfaces?)

**Comment by ajcvickers** [comment]
@ErikEJ @roji The way to get the debug view from code is using the `ToDebugString()` extension methods, which are defined on the interface.

@roji There is no problem in the debugger because it knows that the actual runtime time has a DebugView property and shows it.

**Comment by ErikEJ** [comment]
What @roji wrote will work with both 5 & 6, right?

**Comment by ajcvickers** [comment]
Casting IModel to Model is likely to break soon with different IModel implementations that go with the compiled model feature.

**Comment by ErikEJ** [comment]
I have switched to ToDebugString - which works both with 5 and 6, thanks @ajcvickers @roji

**Comment by roji** [comment]
> @roji There is no problem in the debugger because it knows that the actual runtime type has a DebugView property and shows it.

I don't know about VS, but this does not work in Rider... Adding a watch for `ctx.Model.DebugView.LongView` errors (`'IModel' does not contain a definition for 'DebugView'...`), while `((Microsoft.EntityFrameworkCore.Metadata.Internal.Model)ctx.Model).DebugView.LongView` works. Maybe this could be considered a limitation/bug of Rider, I'm not sure.

Buit ToDebugString indeed seems the right option here regardless.

**Comment by ajcvickers** [comment]
@roji I wouldn't expect a watch like that to work. But I was referring to just looking at the context in the debugger:

![image](https://user-images.githubusercontent.com/1430078/111923130-d464d600-8a5a-11eb-9db6-7fd27273267d.png)
