### ISSUE TITLE
.NET 4.5 or 4.5.1 ??

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2443]
Currently, the full .NET only SQLCE provider is configured for .NET 4.5, and nothing breaks afaik. (I am using .NET 4.6 on my PC). Will I need to update to 4.5.1, and if so, why?

**Comment by bricelam** [comment]
`net45` is good for now. We currently target it to support Mono which doesn't have the 4.5.1 System.Data APIs. I talked [a bit about our targets here](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-June-18,-2015#target-frameworks).

**Comment by ErikEJ** [comment]
Fine. I just thought I saw somwhere that EF.Relational required 4.5.1 !?

**Comment by bricelam** [comment]
It did, but we changed it for Mono.

**Comment by ErikEJ** [comment]
Ah!
