### ISSUE TITLE
Add warning when multiple HasQueryFilter()'s are present for the same entity

### ISSUE THREAD

**Issue by ilohnesimmediac** [dotnet/efcore#24438]
Per [HasQueryFilter()](https://docs.microsoft.com/en-us/ef/core/querying/filters)'s documentation:

> It is currently not possible to define multiple query filters on the same entity - only the last one will be applied. However, you can define a single filter with multiple conditions using the logical AND operator (&& in C#).

This is reasonable. However, in some cases, a fairly difficult conclusion to arrive at. I recently spent a considerable amount of time trying to debug why my filters weren't applying, as I had one written for my soft delete flag, and one for my Stripe Id field. 

It'd be really nice if there was a warning thrown for this, I'm sure it would save future developers a ton of pain.

Thanks.

**Comment by ajcvickers** [comment]
@ilohnesimmediac Thanks for the suggestion. This could be useful, although its questionable that these should be warnings, but rather than spend time doing this we want to improve global query filters as tracked by #21459
