### ISSUE TITLE
User Defined Function in HasDefaultValueSql

### ISSUE THREAD

**Issue by XiSigma** [dotnet/efcore#24443]
Consider the following where I create a sequence and set the default value of some property to an SQL User Defined Function call

```C#
protected override void OnModelCreating(ModelBuilder builder)
{
      base.OnModelCreating(builder);

      builder.HasSequence<long>("HumanIdSeq");

      builder.Entity<Order>()
             .Property(o => o.Reference)
             .ValueGeneratedOnAdd()
             .HasDefaultValueSql("dbo.GenerateHumanId(NEXT VALUE FOR HumanIdSeq)");
}
```

Given that I don't need to call my function from c# how can I create it as raw SQL using the ModelBuilder? 

the only way I found is to modify the migration file and define my function as raw SQL there using the MigrationBuilder, is there a way to avoid this step and define it as raw SQL in the ModelBuilder?

**Comment by roji** [comment]
Assuming you're using migrations, then yeah, the way to do this is to specify the raw SQL in your migration file ([as in the docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql)). It currently isn't possible to define raw SQL to be run in model building without migrations - your only option is to include it in your migration file (or to run it outside of EF Core).

BTW I briefly mentioned specifying raw SQL without migrations back in the day in https://github.com/dotnet/efcore/issues/6524#issuecomment-256082609, but I don't think we have a proper tracking issue). This wouldn't be trivial - it's easy enough to run the raw SQL on EnsureCreated, but if migrations are being used it's not clear what to do when the SQL changes...

**Comment by roji** [comment]
Opening to discuss in triage
