### ISSUE TITLE
FromSqlInterpolated: How do you specify precision and scale for automatically created decimal parameters?

### ISSUE THREAD

**Issue by brendonwm** [dotnet/efcore#24442]
I'm not 100% sure but I think this has happened since the move to EF Core 5 and believe this wasn't a problem before. I've put it as a question rather than bug as I don't have the opportunity to try on the previous version at present.

 Essentially our decimal stored procedure parameters are being truncated to 2 decimal places when they're meant to be 4 decimal places.

We have some code like this:
```
            return (await context.IntResult.FromSqlInterpolated(@$"
EXEC dbo.InsertCompanyNta @Date = {date}, -- date
                          @Company = {company},       -- nvarchar(5)
                          @PreTaxNta = {preTaxNta},    -- decimal(18, 4)
                          @PostTaxNta = {postTaxNta}    -- decimal(18, 4)

").ToArrayAsync()).First().Result;
```
This is what appears in the log - as you can see it's defaulted to scale 2:
_info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (16ms) [Parameters=[p0='?' (DbType = DateTime2), p1='?' (Size = 4000), p2='?' (Precision = 18) (Scale = 2) (DbType = Decimal), p3='?' (Precision = 18) (Scale = 2) (DbType = Decimal)], CommandType='Text', CommandTimeout='30']

      EXEC dbo.InsertCompanyNta @Date = @p0, -- date
                                @Company = @p1,       -- nvarchar(5)
                                @PreTaxNta = @p2,    -- decimal(18, 4)
                                @PostTaxNta = @p3    -- decimal(18, 4)_

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 
IDE: Visual Studio 2019 16.9.2

**Comment by roji** [comment]
If you need to specify parameter facets such as precision/scale/size, pass a DbParameter rather than a raw value to FromSqlRaw - [the docs discuss this](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters).

**Comment by ajcvickers** [comment]
@brendonwm Make sure that you have configured the correct precision/scale in your model. For example, by [configuring the column type](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-data-types):

```C#
[Column(TypeName = "decimal(5, 2)")]
public decimal Rating { get; set; }
```

EF Core 5.0 uses this configuration in places where it was ignored by previous versions. See the breaking change here: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#decimals

I don't believe you need to pass create `DbParameter` objects to make this scenario work.
