### ISSUE TITLE
Can I force EF Core to generate a query containing a where-in clause on multiple values?

### ISSUE THREAD

**Issue by PatrikBak** [dotnet/efcore#24449]
This is a correct SQL (Postgresql)

```sql
create table numbers(a int, b int, something varchar(5));

insert into numbers values (42, 1, 'a'), (21, 2, 'b'), (14, 3, 'c'), (7, 6, 'd');

select something from numbers where (a,b) in ((42, 1), (21, 2));
```

I've been wondering if I can force EF core to generate a select like this.

I've tried something like

```csharp
public class Number
{
    public int A { get; set; }

    public int B { get; set; }

    public string Something { get; set; }
}

IQueryable<Number> numbers = ...

var pairs = new[]
{
    new { A = 42, B = 1 },
    new { A = 21, B = 2 }
};

numbers.Where(number => pairs.Contains(new { number.A, number.B }));
```

This doesn't work.

Using Expression trees (via a helper class `PredicateBuilder`), I am able to do something like this

```csharp
numbers.Aggregate(PredicateBuilder.False<Number>(), (result, pair) => result.Or(number => number.A == pair.A && number.B == pair.B))
```

This translates to a slightly different SQL, something like 

```sql
select something from numbers where (a=42 and b=1) or (a=21 and b=2)
```

This solution is good enough for my use-case, but it is not ideal, as it results in a slightly unnecessarily verbose SQL. That's why I'm wondering if EF Core is capable of generating the first version somehow.

**Comment by roji** [comment]
No, AFAIK it isn't currently possible to make EF generate the tighter SQL. We should be able to add the translation for Contains for tuple arrays, though I'm not sure there's an advantage beyond the terser SQL.

**Comment by ajcvickers** [comment]
Ping @roji to check if tuples are part of the SQL standard and if other databases support them.

**Comment by roji** [comment]
Supported in by PostgreSQL and MySQL, not supported by SQL Server or Sqlite:

```sql
CREATE TABLE foo (a INT, b INT);
INSERT INTO foo (a, b) VALUES (1, 2), (3, 4);
SELECT * FROM foo WHERE (a, b) IN ((1, 10), (3, 4));
```

I guess we could provide an optional translator in relational which could be used by providers, though this seems simple enough that each provider could just have its own...

**Comment by ajcvickers** [comment]
Discussed again in triage and agreed not to do anything here at the relational level, but providers could implement something if they choose.
