### ISSUE TITLE
SQLCE 3.5 support - handle Skip not supported

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2445]
SQL CE 4.0 supports the OFFSET/FETCH syntax. SQLCE 3.5 does not. My question is - how to handle this in the 3.5 version of the provider - tried throwing "NotSupportedException", but GenerateLimitOffset is always called, causing any queries to fail.

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/a52ae1cbd31d00e2808fecc2af576455875e5bdd

Would the solution with EF7 simply be to do nothing?

**Comment by anpete** [comment]
@ErikEJ Is it expressible at all in 3.5? If not, the correct thing to do is to subclass RelationalResultOperatorHandler and force client eval of the Skip operator in HandleResultOperator.

A few points on this:

1) RelationalResultOperatorHandler is not currently coming from DI, should be trivial to fix.
2) How are you differentiating between versions in your provider? Or, do you have two providers?
3) We may need to do some work in query cache key construction to ensure that we get separate cache entries between 3.5 and 4.

**Comment by ErikEJ** [comment]
@anpete :
>> Is it expressible at all in 3.5? Nope!
re 1) Sounds likea solution, I will await the DI changes.
re 2) I have two providers https://www.myget.org/gallery/ef7-sqlce (same namespace, however)
re 3) Most unlikely that 3.5 and 4.0 will be used in the same project, but not sure how you construct the "cache key" now

**Comment by divega** [comment]
How did the EF6 provider translate paging operators for SQL CE 3.5?

**Comment by ErikEJ** [comment]
@divega  It did not, it threw at "NotSupportedException"

**Comment by ErikEJ** [comment]
@anpete Just to understand correctly: To tell EF7 to evaulate Skip client side for SQLCE 3.5, I must await changes from your side before that can be implemented?

**Comment by anpete** [comment]
@ErikEJ Yes, unless you send a PR to DI enable RelationalResultOperatorHandler (currently new'd up directly in RelationalDataStore). :-)

**Comment by ErikEJ** [comment]
@anpete Thanks, but no thanks. Will just await changes, and let the provider error for now :smile:

**Comment by ErikEJ** [comment]
Lets just stick to a "NotSupportedException"
