### ISSUE TITLE
Ability to call Set<T> using an interface type constraint

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24451]
The following code requires a class:
https://github.com/dotnet/efcore/blob/95e779b5b623c71f74bad7bcd7b98723d4892cf6/src/EFCore/DbContext.cs#L283-L284

Possible to call `Set<T>()` with an interface?

```c#
public string GetValue<T>(int id) where T : IMyInterface
{
    return context.Set<T>().Where(t => t.Id == id).FirstOrDefault(v => v.Value);
}
```

**Comment by ajcvickers** [comment]
@mrlife No. Entity types must be concrete; see #757 which is about mapping interfaces to entity types.
