### ISSUE TITLE
AddPooledDbContextFactory

### ISSUE THREAD

**Issue by savamas** [dotnet/efcore#24467]
What is the difference in behaviour between AddDbContextFactory and AddPooledDbContextFactory

As I understand when we use "AddDbContextFactory" we should dispose contexts by ourselfs, otherwise they will keep growing.

![image](https://user-images.githubusercontent.com/37020194/111973827-f40a0600-8b0f-11eb-94bc-22f1feb33a92.png)

I register factory of pooled contexts with pool size = 5

![image](https://user-images.githubusercontent.com/37020194/111974474-7db9d380-8b10-11eb-8c43-d92d64a51090.png)

Then I inject factory in my controller and create a db context

![image](https://user-images.githubusercontent.com/37020194/111974642-acd04500-8b10-11eb-99d3-93821a918ae7.png)

But when I make 9 requests to my controller and look at dotnet counters I see that DbContexts are not pooled and they keep growing within each request

Should I dispose those contexts when I use "AddPooledDbContextFactory" ? If yes, hense what is the difference between AddDbContextFactory and AddPooledDbContextFactory?

EF Core version: 5.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10

/Regards

**Comment by ajcvickers** [comment]
@savamas You need to dispose the context instance. Disposing the instance will put it back into the pool.
