### ISSUE TITLE
Using base entity with child entity causes missing Discriminator exception

### ISSUE THREAD

**Issue by kobruleht** [dotnet/efcore#24487]
To reproduce, create database with products table

```
create table Product (
  Product char(20) primary key;
  Description char(50);
  )
```
Map it to Product class using EF Core Scaffold

```C#
public class Product {
  public string Product1 { get; set; }
  public string Description { get; set; }
  }

public DbSet<Product> Products { get; set; }
```

Create product view with special shadow properties which do not exist in database and in Product class:

```C#
public class ShopToode: Product {
  public decimal CartPrice { get; set; }
  }

public DbSet<ShopToode> ShopToodes { get; set; }
```

Verify that it works:

```C#
var tooteinfo = await ctx.ShopToodes.FromSqlRaw(@"select *, 
  1.2 as CartPrice 
  from Product").AsNoTracking().ToListAsync();
```

Try to use Product class

```C#
 var t = ctx.Products.First();
```

Observed:

```
Npgsql.PostgresException (0x80004005): 42703: column t.Discriminator does not exist
```

How to use Product entity if view also exists ?

EF Core version: latest
Database provider: NpgSql
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 latest

**Comment by ajcvickers** [comment]
@kobruleht EF is mapping these two types using the TPH inheritance mapping pattern. Try keeping them independent by setting the base type in the EF model to null:

```C#
modelBuilder.Entity<ShopToode>().HasBaseType((Type)null);
```

**Comment by kobruleht** [comment]
Adding this causes exception

`InvalidOperationException: The entity type 'ShopToode' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
`
I changed it to

`            modelBuilder.Entity<ShopToode>().HasBaseType((Type)null).HasNoKey();
`
but this causes exception  in FromSql command described

```
InvalidOperationException: The required column 'AnaloogNavigationToode1' was not present in the results of a 'FromSql' operation.
(Analoog is Product tabel property referencing to Product table itself)

```
Tried also

`modelBuilder.Entity<ShopToode>().HasBaseType((Type)null).HasKey(e => e.Product1);
`
But this causes exception

> Npgsql.PostgresException (0x80004005): 42703: column k.ShopToodeProduct1 does not exist 

when other entity which is referenced by Product entity is queried.

In reality Product entity has references to other entities and is referenced by other entities. How to fix this so that those references do not cause exception when ShopToode is queried by FromSqlRaw ?

**Comment by ajcvickers** [comment]
> In reality Product entity has references to other entities and is referenced by other entities. How to fix this so that those references do not cause exception when ShopToode is queried by FromSqlRaw?

It's much cleaner if you define a separate type for your view. But if you want it to inherit, and don't want these things mapped then you can use `Ignore` in the model builder to ignore them on the view type.
