### ISSUE TITLE
Question: How to prevent conversion in Sql when building dynamic Linq queries?

### ISSUE THREAD

**Issue by DefinitelyADev** [dotnet/efcore#24485]
Hello,
I'm trying to build a where expression from data passed to an api method, using the following method.

```C#
private static Expression GetWhereExpression<T>(SearchOperator searchOperator, ParameterExpression param, string columnName, string value)
        {
            Expression member = Expression.Property(param, columnName);

            if (member.Type == typeof(int) || member.Type.BaseType == typeof(Enum))
            {
                member = Expression.Convert(Expression.Convert(member, typeof(object)), typeof(string));
            }

            return searchOperator switch
            {
                SearchOperator.Equal => Expression.Equal(member, Expression.Constant(value)),
                SearchOperator.NotEqual => Expression.NotEqual(member, Expression.Constant(value)),
                SearchOperator.Contains => Expression.Call(member, "Contains", Type.EmptyTypes, Expression.Constant(value)),
                _ => null
            };
        }
```

The api accepts string as parameter value and I'm trying to convert the type of the column using `Expression.Convert` to string in in order to get the correct equals otherwise I get the following error:

```
The binary operator Equal is not defined for the types 'System.Int32' and 'System.String'
```

or

```
The binary operator Equal is not defined for the types 'MyEnum' and 'System.String'
```

But I don't want the Convert expression to translate to the following Sql:

```sql
SELECT `q`.`Field1`, `q`.`Field2`, `q`.`Field3`
FROM `Schema`.`TableName` AS `q`
WHERE (CAST(`q`.`Field3` AS char) COLLATE utf8mb4_bin = '1'))
LIMIT @__p_1 OFFSET @__p_0
```

This would have been enough

```sql
SELECT `q`.`Field1`, `q`.`Field2`, `q`.`Field3`
FROM `Schema`.`TableName` AS `q`
WHERE `q`.`Field3` = '1'
LIMIT @__p_1 OFFSET @__p_0
```

EF Core version: 3.1.9
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET 5.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.9.2

**Comment by ajcvickers** [comment]
@TsakiDev Likely the best that you can do here is use a double cast, first to object, and then to the desired type. It looks like you are already doing this in your code. When I do this on SQL Server, I get the following SQL:

```sql
      SELECT TOP(2) [b].[Id], [b].[SomeString]
      FROM [Blog] AS [b]
      WHERE [b].[SomeString] = CAST(1 AS nvarchar(max))
```

@smitpatel @lauxjpn Is there any reason that the SQL Server provider would cast the constant to a string, while the MySQL provider attempts to cast the column to a single character type?

**Comment by smitpatel** [comment]
SqlServer would copy over type mapping of `[b].[SomeString]`

**Comment by lauxjpn** [comment]
This is the same question as https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1358. I posted some code over there, that should accomplish what @TsakiDev is looking for.

---

> Is there any reason that the SQL Server provider would cast the constant to a string, while the MySQL provider attempts to cast the column to a single character type?

@ajcvickers MySQL has very limited casting support that is based on a few very primitive internal types that are pretty much independent of the externally exposed types like `varchar` etc. So `CAST(x as char)` in MySQL is equivalent to `CAST(x as nvarchar(max))` in SQL Server (see [12.11 Cast Functions and Operators: CONVERT()](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_convert)).
So the Pomelo implementation should be correct.
