### ISSUE TITLE
Disable attributes for model

### ISSUE THREAD

**Issue by ColonelBundy** [dotnet/efcore#24508]
As a team, sometimes you agree upon conventions for a codebase and sometimes you go in a direction where you choose to support a subset of features of a particular library and in this case we as a team agreed upon not using attributes for our model. And we try to enforce only using the fluent interface to configure our model. 
This is harder to do in practice and getting new developers on the team and being a very large team does not help either so it gets harder to enforce.

**Proposed solution**
A way to disable attributes and only accept fluent configuration of a model, and perhaps the other way around?
I don't think an exception should occur if this setting is on, rather the model remains unchanged if an attribute is applied to an entity.

**Comment by AndriySvyryd** [comment]
https://github.com/dotnet/efcore/issues/214 will allow you to do exactly what you propose.
