### ISSUE TITLE
Cosmos: add support for pagination

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#24513]
See https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.queryrequestoptions.maxitemcount?view=azure-dotnet

**Comment by AndriySvyryd** [comment]
Also consider exposing the continuation token

> The RU charge of a query with OFFSET LIMIT will increase as the number of terms being offset increases. For queries that have multiple pages of results, we typically recommend using continuation tokens. Continuation tokens are a "bookmark" for the place where the query can later resume. If you use OFFSET LIMIT, there is no "bookmark". If you wanted to return the query's next page, you would have to start from the beginning.

**Comment by vyarymovych** [comment]
Very interested in this as well. We are using EF Core Cosmos provider at the moment and the only way to query a page is to use the 'skip and take' approach. But as it has been mentioned, it's going to use more RUs for the next pages.

So we started thinking about using .NET SDK and replacing EF queries with Cosmos continuation tokens

**Comment by brandonsmith86** [comment]
Any updates?  I am also having to shelve EF w/ Cosmos because of this limitation.

**Comment by AndriySvyryd** [comment]
This feature hasn't been assigned to a particular release yet. The best way to indicate the importance of an issue is to vote (👍) for it. This data will then feed into the [planning process](https://docs.microsoft.com/ef/core/what-is-new/release-planning) for the next release.

**Comment by AndriySvyryd** [comment]
Current design proposal:

```C#
    public static async Task<Page<TSource>> ToPageAsync<TSource>(
        this IQueryable<TSource> source,
        int? maxItemCount = null,
        int? continuationTokenLimitInKb = null,
        CancellationToken cancellationToken = default)
 
    public static async Task<Page<TSource>> ToPageAsync<TSource>(
        this DbSet<TSource> source,
        string continuationToken,
        int? maxItemCount = null,
        int? continuationTokenLimitInKb = null,
        CancellationToken cancellationToken = default)
```
See [Page\<T>](https://learn.microsoft.com/en-us/dotnet/api/azure.page-1?view=azure-dotnet)

Open questions:
- Should `maxItemCount` and `continuationTokenLimitInKb` be specified using separate extension methods? See [Pagination with the Azure SDK](https://learn.microsoft.com/en-us/dotnet/azure/sdk/pagination)
- Should this align with [AsyncPageable\<T>.AsPages()](https://learn.microsoft.com/en-us/dotnet/api/azure.asyncpageable-1.aspages) and return `IEnumerable<Page<T>>` instead?

**Comment by AndriySvyryd** [comment]
Updated the proposal based on the discussion. Even if we implement pagination on other providers the API will be separate, even if the general shape is the same to allow exposing provider-specific options.

**Comment by roji** [comment]
BTW I think it does make sense to accept the maxItemCount directly in ToPageAsync, just to not force the user to use two different operators (it could override any previous-specified one). But we can figure all that out later.

**Comment by KrzysztofCwalina** [comment]
It would be good if you used the same patter, or even the same pagination API as in the Azure SDK (or System.ClientModel).

**Comment by roji** [comment]
@KrzysztofCwalina yeah, we haven't yet started designing for this, but these are on my radar. Are you refering specifically to [these recently-merged paging abstractions](https://github.com/Azure/azure-sdk-for-net/pull/44026), or anything else?

**Comment by roji** [comment]
Sounds good! I'll try to prioritize working on the pagination bits sooner rather than later, and will be in touch with the results. Who are the relevant people to ping on both System.ClientModel and the Azure SDKs, apart from you two?
