### ISSUE TITLE
Owned type w/ HasMany

### ISSUE THREAD

**Issue by cjblomqvist** [dotnet/efcore#24535]
First, I'm assuming Owned Types are basically trying to target https://www.martinfowler.com/bliki/DDD_Aggregate.html

I fully understand why an owned entity cannot be owned by multiple other entities (as is specified in the docs). It simply doesn't make sense from a conceptual perspective, and very unclear technically. However, I see no reason why there can't be relationships to the owned entity? Basically, I don't understand why the following error message exists: ```The type 'Owned' cannot be configured as non-owned because an owned entity type with the same name already exists.```

Below I have two scenarios. One using a DDD Aggregate approach, one without. I assume you can infer the relationships from the types, so no need for the configuration. 

The one without works fine, but the one using the aggregate approach doesn't. I don't see any technical (or conceptual) reasons (whether one splits up Owner/Owned into two entities or keeps them in one, e.g. FlattenedOwner) shouldn't make any difference? It's the same amount of tables, just mapped to either 1 or 2 entities? Or am I just missing how to properly configure such scenario?

Doesn't work:
```C#
public class Owner
{
    public int OwnerId { get; set; }
    public Owned Owned { get; set; }
}

public class Owned
{
    public string SomeProperty { get; set; }
    public List<Related> Relateds { get; set; }
}

public class Related
{
    public int RelatedId { get; set; }
    public Owned Owned { get; set; }
}
```

Works:
```C#
public class FlattenedOwner
{
    public int OwnerId { get; set; }
    public string SomeProperty { get; set; }
    public List<Related> Relateds { get; set; }
}

public class RelatedToFlattened
{
    public int RelatedId { get; set; }
    public FlattenedOwner FlattenedOwner { get; set; }
}
```

EF Core version: 5.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.8.5)

**Comment by cjblomqvist** [comment]
Thanks @ajcvickers! I'll take a stab at it tomorrow and see if I can get it working!

**Comment by cjblomqvist** [comment]
Just a quick question - it looks like you're a assuming that Related should be owned by Owned - that's not the case. They should just have one-to-many relationship (but Related should be a standalone entity). Or am I still missing something? @ajcvickers

**Comment by ajcvickers** [comment]
@cjblomqvist What is the expected semantics of an entity that is part of an aggregate but which acts as the principal end for a relationship with an entity type that is not part of the aggregate?

/cc @AndriySvyryd

**Comment by cjblomqvist** [comment]
@ajcvickers assuming I understand your question correctly. Basically the same as FlattenedOwner, but with a "sub-entity" for a clearer structure. For example, let's assume that Owner (Aggregate in Martin Fowler termology) is huge, then it makes sense (for better structure) to split it up into an Owner/Aggregate and several sub-entities (Owned "entities"). At the moment it seems this limits the possibilities, since there cannot(?) be many-to-one relationship fields on the Owned sub-entities (and it seems, without being an expert, that this is an artifical limitation). It would be nice, since it otherwise significantly limits the possibility to break out the "sub-entities", since none can contain those relationships.

I can send you an actual example tomorrow (in bed on my cell atm) that might help understand an example of a use case.

**Comment by cjblomqvist** [comment]
An example/more realistic scenario of above case:
We have a software system that we sell to fashion brands, specifically footwear/shoe brands. In this system we have Styles - e.g. 'Nike Air' - which have many Colorways - e.g. 'Black', 'White'. Each Style have certain Sizes - e.g. US 10, US 11. A certain Size of a certain Colorway equals a specific Sku (Stock Keeping Unit).

One way to model this:
```C#
public class Style
{
    public int StyleId { get; set; }
    public string Name { get; set; } // E.g. "Nike Air"
    // ... lots of other properties
    public GenderAndSize GenderAndSize { get; set; }
    public List<Colorway> Colorways { get; set; }
}

public class GenderAndSize
{
    // ... lots of other properties
    public List<Size> Sizes { get; set; }
}

public class Size
{
    public int SizeId { get; set; }
    public List<Sku> Skus { get; set; }
}

public class Colorway
{
    public int ColorwayId { get; set; }
    public List<Sku> Skus { get; set; }
}

public class Sku
{
    public int SkuId { get; set; }
    public Colorway Colorway { get; set; }
    public Size Size { get; set; }
}
```

Comments:
* Style owns GenderAndSize
* The reason why GenderAndSize is split up from Style is because Style is very huge, keeping things along the thought lines https://www.martinfowler.com/bliki/DDD_Aggregate.html (the inspiration for owned entities if official MS communication is correct :-) )
* Assuming above two points, there are two ways to model this. 
* A) Either, we have HasXXX-relationships between the rest of the entitites. This obviously doesn't work, since GenderAndSize (an owned entity) contains a List/Collection (HasMany/"one"-end of a one-to-many relationship) of Size, and it seems (correct or not?) that it's not possible to have a one-to-many relationship between an owned entity and another entity.
* B) Or, we can also make Sizes and owned list/collection of GenderAndSize. Regardless if we keep SizeId or not (pragmatically it might make sense to keep it to distinguish specific Sizes within a Style as a compound key with StyleId - or possibly as a standalone PK), we end up with a scenario that an owned entity (in this case Size instead of GenderAndSize), needs to have a one-to-many -relationship with an entity (in this case Sku instead of Size).
* Both A) and B) ends up with the same dilemma. For A) it's more clear that there are no technical difficulties of mapping the relationship (StyleId can act as PK for GenderAndSize since there's a one-to-one strict relationship between Style<->GenderAndSize), which is clear if we do not use owned entities/mapping/relationships at all. It's a little bit more tricky in B) due to StyleId not being able to act as PK since a Style then owns many Sizes.

**Comment by ajcvickers** [comment]
@cjblomqvist I've added a note to #1985, which is where we are tracking full support for aggregate patterns.

**Comment by AndriySvyryd** [comment]
The reason we don't allow owned types to be on the principal end is this line from https://www.martinfowler.com/bliki/DDD_Aggregate.html
> Any references from outside the aggregate should only go to the aggregate root.

Another alternative for your case is to not use owned types and instead configure `Style.GenderAndSize` to be auto-included:

```C#
modelBuilder.Entity<Style>().Navigation(e => e.GenderAndSize).AutoInclude();
```

**Comment by cjblomqvist** [comment]
@ajcvickers - thanks!

@AndriySvyryd - I see! The reasoning behind this seems to be (from the same source):

> The root can thus ensure the integrity of the aggregate as a whole.

I'm no DDD expert and unfortunately I don't have access to the book (atm anyway), so please forgive any ignorance on my part :-) Do you know the reasoning behind this? I'm not sure I understand the integrity argument fully. In a scenario where owned entities are considered a part of the parent (in other words; everything can be considered as one) why does it matter if there are references to the owned entity? If the parent is not complete without it's owned entity (or if not set, then one can safely assume that any links within that owned entity shouldn't exist either), then why does it matter?

If A1 is the parent and A2 is the owned "part" of the parent, model wise one should still consider it as one A? Then why does it matter if any link/reference to B is on A1 or A2?

(I realize there are many other alternatives to solve it in a similar fashion, the simplest is probably to just include the owned properties on the parent directly. I'm just trying to understand Aggregates/Owned entities better, in order to be able to evaluate whether the company I work at should use that pattern more liberally for a better code structure - which seems to be the whole/only point of Aggregates?).

Thanks for taking the time and developing EF!

**Comment by AndriySvyryd** [comment]
@cjblomqvist This reduces coupling, so you can refactor the way the aggregate is broken down without affecting outside code.

> If A1 is the parent and A2 is the owned "part" of the parent, model wise one should still consider it as one A? Then why does it matter if any link/reference to B is on A1 or A2?

Now this is a technical limitation of EF, the model currently doesn't allow a foreign key on one type but the corresponding navigation on a different type.

**Comment by cjblomqvist** [comment]
@AndriySvyryd thanks for putting it so clearly, now I understand (although I'm not sure I agree with that trade-off, since then you're forced to couple everything with the parent - thus limiting the benefit of splitting it up in the first place).

Technical limitations can usually be fixed. I'm more interested in what the EF Core team thinks about this - do you stand with Martin Fowler that owned types should not contain references to other entities due to reasons you've already explained, or do you consider it worthy to support? In other words, can I assume this will never be changed or is there a significant chance it'll be changed in the future?

Again, thanks for your work! 😊

**Comment by AndriySvyryd** [comment]
> Technical limitations can usually be fixed. I'm more interested in what the EF Core team thinks about this - do you stand with Martin Fowler that owned types should not contain references to other entities due to reasons you've already explained, or do you consider it worthy to support? In other words, can I assume this will never be changed or is there a significant chance it'll be changed in the future?

We defined owned types essentially as being an internal part of the aggregate, so this isn't going to change. But this allows us to add the features in #1985. And we are planning to add value object support in #13947, so there will be more alternatives in the future.

**Comment by cjblomqvist** [comment]
Ok! Assuming my interpretation of your comment is correct (basically, no, we won't change how it works), then I'm going to close this issue since this is basically a "won't fix" scenario.

I think it's clear that I would've preferred another outcome (I'm no expert though, maybe thet consequences are too dire), but I must say I really really appreciate the discussion and getting proper reasons for it, so consider my overall a happy EF Core user anyway! :-)

**Comment by smitpatel** [comment]
@pastushenkoy - There is no reason for possible answers to be owned type or part of aggregate. You are looking for ordered collections. See #9067

**Comment by pastushenkoy** [comment]
Order number was just an example. There could be a lot of possible constraints not connected to sort order.

**Comment by smitpatel** [comment]
> Questions could have possible answers which are natively owned type as they have an OrderNumber field.

There could be constraints but if an entity needs to be references by 2 different types which are not in same aggregate then that entity doesn't need to be owned. Constraints could be modeled in various way. The constraint of ownership is already violated and cannot be applied.

**Comment by pastushenkoy** [comment]
I suddenly understood that if we define navigation property than we must allow saving PossibleAnswer separately and this is really violation of ownership constraint. Thank you. This was really helpful.

**Comment by cjblomqvist** [comment]
FYI: By mistake I actually managed to create an owned property which has a relationship - with the expected (originally anyway) behaviour. As clear from the generated migration code (below), the proper foreign key, etc. was created for the relationship.

The structure is as follows:
BomComponentColor
  OwnedType DefaultColor

OwnedType
  int? ColorPaletteColorId
  ColorPaletteColor ColorPaletteColor
  OtherOwnedType CustomColor

The only thing I can think of that differs is that OwnedType is not an entity. I do not remember if I previously by mistake set owned types as entities. I agree that Value Objects might be a better long-term solution, since this obviously breaks Martin Fowler's rules of Aggregates. Considering that, this might actually be a "bug" (if that's not supposed to be allowed).

Haven't mentioned this before but I'm using 5.0 (both .NET, ASP.NET and EF Core).

```csharp
migrationBuilder.DropTable(
                name: "BomComponentColor");

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_ColorPaletteColorId",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_B",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_C",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DefaultColor_CustomColor_Code",
                table: "BomComponent",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "DefaultColor_CustomColor_CreatedAt",
                table: "BomComponent",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DefaultColor_CustomColor_FullName",
                table: "BomComponent",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_G",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_H",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_K",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_L",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_M",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DefaultColor_CustomColor_Name",
                table: "BomComponent",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_R",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_S",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "DefaultColor_CustomColor_UpdatedAt",
                table: "BomComponent",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DefaultColor_CustomColor_Y",
                table: "BomComponent",
                type: "int",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_BomComponent_DefaultColor_ColorPaletteColorId",
                table: "BomComponent",
                column: "DefaultColor_ColorPaletteColorId");

            migrationBuilder.AddForeignKey(
                name: "FK_BomComponent_ColorPaletteColor_DefaultColor_ColorPaletteColorId",
                table: "BomComponent",
                column: "DefaultColor_ColorPaletteColorId",
                principalTable: "ColorPaletteColor",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
```
