### ISSUE TITLE
PropertyBuilder.HasConversion changes the DeleteBehavior property to Cascade

### ISSUE THREAD

**Issue by sdunst** [dotnet/efcore#24534]
**Problem**

I have a foreign key property on an entity, that needs to be converted to a nullable Guid first.
For this I am using a ValueConverter<PropertyType, Guid?>

My issue is, that after the call to HasConversion(...) with my Converter the DeleteBehaviour of the relation changes from ClientSetNull to Cascade. Even tough the output type of the specified ValueConverter is nullable

```C#
// entityTypeBuilder.Property("PropertyName").ForeignKeys.Single().DeleteBehavior == DeleteBehavior.ClientSetNull
entityTypeBuilder.Property("PropertyName").HasConversion(new ToNullableGuidConverter()); // Implementation of ValueConverter<PropertyType, Guid?>
// entityTypeBuilder.Property("PropertyName").ForeignKeys.Single().DeleteBehavior == DeleteBehavior.Cascade
```

EF Core version: 5.0.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.2

**Comment by ajcvickers** [comment]
@sdunst In general, value converters cannot be used to convert nulls, and hence cannot change the nullability of a property. See #13850.
