### ISSUE TITLE
Docs are unclear about List vs ICollection on navigation properties, which to use?

### ISSUE THREAD

**Issue by trustieee** [dotnet/efcore#24544]
The docs [here](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key) show `List<T>` for one-to-many relationships and `ICollection<T>` for Many-to-many, but it doesn't state _why_?

There is this blurb:
> Many to many relationships require a collection navigation property on both sides. They will be discovered by convention like other types of relationships.

Am I understanding this correctly by thinking `ICollection<T>` is required only because the underlying EF code is looking for it by convention? Is there no other reason?

**Comment by ajcvickers** [comment]
@trustieee You can use any collection that implements `IEnumerable<T>` and can be modified.

**Comment by marcusjwhelan** [comment]
@ajcvickers I agree with @mikernet  that this is unclear and anywhere online doesn't really answer this question.

**Comment by robinTsl** [comment]
Got here trying to find an answer to the question. Agree the docs could be clearer.

**Comment by marklagendijk** [comment]
The question remains: what should one use and why?
What things should one consider? Is there a performance impact? Can choosing List over ICollection be a footgun for certain cases? Etc. etc.
These are things that are unknown to a user of the library. Therefore the library documentation should preferably contain some guidance on this.

@ajcvickers do you agree with this assessment? Are you maybe in the position to answer these questions?

**Comment by AndriySvyryd** [comment]
There is almost no difference between the two for EF, you should choose the one that best fits your application.

**Comment by marklagendijk** [comment]
@AndriySvyryd thanks for your reply!
It's good to know that there is almost no difference from the EF perspective.
I prefer `List`, because with `ICollection` I often need to add a `.ToList()`, to use some of the specific `List` methods / properties.
I know that `ICollection` is an extra abstraction that can be useful, but for EF usage I don't see the value.
