### ISSUE TITLE
EnsureCreated doesn't seem to create views

### ISSUE THREAD

**Issue by aaronasmith** [dotnet/efcore#24546]
In my tests I run EnsureCreated to generate my schema in a sql localdb instance.  It doesn't appear that any of the views are created even though there are mappings for them.

**Comment by ajcvickers** [comment]
@aaronasmith EF Core currently doesn't support defining view definitions in the model or applying them to the database via Migrations or EnsureCreated. This is tracked by #14537 and #465.
