### ISSUE TITLE
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding ‘EnableRetryOnFailure()’ to the ‘UseMySqlServer’ call. 

### ISSUE THREAD

**Issue by mkhairnar** [dotnet/efcore#24551]
We are facing above mentioned issue on my sql servers, not sure what could be the reason.
The project is in .net core 3.1 and we are using Pomelo.EntityFrameworkCore.MySql (v-3.1.1) for connecting to MySQL DB.

The dependencies of Pomelo.EntityFrameworkCore.MySql are as follows:
- Microsoft.EntityFrameworkCore.Relational (3.1.1)
- MySqlConnector (0.61.0)
- Pomelo.JsonObject (2.2.1) &
- Pomelo.EntityFrameworkCore.MySql.dll

We often get the above error and would like to know the reason for its occurrence, also what could be the best fix for this?

Thanks,
Makarand Khairnar

**Comment by roji** [comment]
@mkhairnar this exception is supposed to wrap an inner exception which contains the full details on what happened - that should provide the info you're looking for. If you're seeing a MySQL-specific issue, you'll probably need to ask about that on the Pomelo or MySqlConnector repos.
