### ISSUE TITLE
Warn when saving an optional dependent with all null properties when table splitting

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#24558]

**Comment by umitkavala** [comment]
Hi @AndriySvyryd,
I'd like to take this issue.

**Comment by AndriySvyryd** [comment]
@umitkavala Ok

**Comment by umitkavala** [comment]
```c#
public class Order
{
    public int Id { get; set; }
    public OrderStatus? Status { get; set; }
    public DetailedOrder DetailedOrder { get; set; }
}

public class DetailedOrder
{
    public int Id { get; set; }
    public OrderStatus? Status { get; set; }
    public string? BillingAddress { get; set; }
    public string? ShippingAddress { get; set; }
}
```

```c#
modelBuilder.Entity<DetailedOrder>(
    dob =>
    {
        dob.ToTable("Orders");
        dob.Property(o => o.Status).HasColumnName("Status");
    });

modelBuilder.Entity<Order>(
    ob =>
    {
        ob.ToTable("Orders");
        ob.Property(o => o.Status).HasColumnName("Status");
        ob.HasOne(o => o.DetailedOrder).WithOne()
            .HasForeignKey<DetailedOrder>(o => o.Id);
    });


using (var context = new TableSplittingContext())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    context.Add(
        new Order
        {
            Status = OrderStatus.Pending,
        });

    context.SaveChanges();
}
```
Is this the use case? (From https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting#optional-dependent-entity)
I'm trying to save principal entity without setting optional dependent entity?

**Comment by AndriySvyryd** [comment]
@umitkavala Not quite.

The use case is more like
```C#
using (var context = new TableSplittingContext())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    context.Add(
        new Order
        {
            DetailedOrder = new DetailedOrder()
        });

    context.SaveChanges();
}
```

Then if you do

```C#
using (var context = new TableSplittingContext())
{
    var order = context.Set<Order>().Include(o => o.DetailedOrder).OrderBy(o => o.Id).First();

    // order.DetailedOrder is null even though it wasn't null when saved
}
```

**Comment by umitkavala** [comment]
@AndriySvyryd I'm just not sure where to check properties values? First I thought it will be at **RelationalModelValidator** but we need to check during save not model validation. 

https://github.com/dotnet/efcore/blob/3b38e3c9c29ac788ffa2df9492c86a6003bbf5d8/src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs#L1316

Is this the correct place to check null properties? Are we going to throw InvalidOperationException?

**Comment by AndriySvyryd** [comment]
@umitkavala No, you'd need to do it in https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs#L161-L164

That's where we have enough information. Perhaps a helper method in `SharedTableEntryMap` would be needed to determine whether a given entry is an optional dependent.

Note that this isn't straightforward, so don't feel pressured to submit a PR.

**Comment by umitkavala** [comment]
When I try to save optional dependent with null properties; below warning thrown before code reach CreateModificationCommands
https://github.com/dotnet/efcore/blob/6d4b03f4f2820adbc0890c2e632e2ecae91692c5/src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs#L330-L358

**Comment by AndriySvyryd** [comment]
@umitkavala Yes, that's a warning logged at model validation. We need another warning logged when the user actually tries to insert an optional dependent with all null properties when table splitting. We don't want to throw an exception in this case as there might be working applications doing this.

**Comment by umitkavala** [comment]
@AndriySvyryd problem is **WarningBehavior**  set to Throw for this message. So it throws an exception and execution stop there. I'll commit my test code as draft for this PR.
![image](https://user-images.githubusercontent.com/3861934/117537336-7dae5e00-b000-11eb-83fa-c7d8e46c798b.png)
