### ISSUE TITLE
EF Core 5 many-to-many avoid link table by using strings

### ISSUE THREAD

**Issue by sjh37** [dotnet/efcore#24576]
_Using Northwind as an example_

In EF6 you could avoid a link table by declaring something like this:
```c#
HasMany(t => t.Territories).WithMany(t => t.Employees).Map(m =>
{
    m.ToTable("EmployeeTerritories", "dbo");
    m.MapLeftKey("EmployeeID");
    m.MapRightKey("TerritoryID");
});
```

With EF Core 5 if we want to name the link table we are forced to declare the link table, and make use of `UsingEntity`
```c#
builder.HasMany(t => t.Territories).WithMany(t => t.Employees).UsingEntity<EmployeeTerritories>(
    j => j
        .HasOne(m => m.EmployeeTerritories)
        .WithMany()
        .HasForeignKey(m => m.TerritoryID),
    j => j
        .HasOne(m => m.EmployeeTerritories)
        .WithMany()
        .HasForeignKey(m => m.EmployeeID),
    j =>
    {
        j.HasKey(t => new { t.EmployeeID, t.TerritoryID });
    });
```
Which is a bit pointless as I end up declaring all 3 tables anyway, and therefore can avoid using `UsingEntity` by configuring each of the 3 tables as 1-to-many.

I want to be able to declare the name of the link table, and its left and right keys, but without creating the link table class.

What I would like to see is for the developer to pass this information in as strings in a similar fashion to EF 6. I don't want EF Core 5 to guess the name of the link table, it has to be specified as the database already exists.

**Comment by ArminShoeibi** [comment]
You don't need to create a join table just for naming.
```
modelBuilder.Entity<YourEntity>()
    .HasMany(left => left.Entity)
    .WithMany(right => right.Entity)
    .UsingEntity(join => join.ToTable("TheDesiredName"));
```

**Comment by sjh37** [comment]
Thanks @ArminShoeibi
