### ISSUE TITLE
auto migration in ef core

### ISSUE THREAD

**Issue by usapop** [dotnet/efcore#24575]
Hi,
I work on wpf project and ef core 2 with sqlite db
I create my class models and use context.Database.EnsureCreated() method, so my database created on runtime.
If I add new column to my model and write context.Database.Migrate() and run my app, I get error no such column 'newColumn'.

**Comment by roji** [comment]
@usapop you cannot use both EnsureCreated and migrations in the same application. EnsureCreated is generally meant only for prototyping purposes, production applications should use Migrations; after adding a new column, you need to generate a new migration, and then apply that change to your database.

More information is available in the documentation on [EnsureCreated](https://docs.microsoft.com/en-us/ef/core/managing-schemas/ensure-created) and on [Migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli).

**Comment by roji** [comment]
Note: you may be looking for "automatic migrations", which existed in EF6. This is not supported in EF Core, see #6214 for more information.

**Comment by usapop** [comment]
thanks @roji for your answer
