### ISSUE TITLE
Including entity via OnModelCreating creates table but is not available in context

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24587]
## File a bug

The [docs page for Entity Types](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#including-types-in-the-model) indicates that entities can be included in a few ways, including using it in `OnModelCreating()`.

The table is created, however the entity cannot be accessed via the context.

### Include your code

**Include entity type**
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<AuditEntry>();
}
```

**Cannot access entity type**
```C#
    var auditEntries = context.AuditEntry.ToList(); // compile time error
```

Here is the error:
> 'Context' does not contain a definition for 'AuditEntry' and no accessible extension method 'AuditEntry' accepting a first argument of type 'Context' could be found

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: macOS 10.15.7
IDE: Visual Studio for Mac 8.10 Preview 1

**Comment by ErikEJ** [comment]
context.Set<AuditEntry> ?

**Comment by mrlife** [comment]
@ErikEJ Thank you, I can't find this in the [official docs](https://docs.microsoft.com/en-us/ef/core). Is this covered somewhere?

**Comment by ErikEJ** [comment]
No idea, I thought it was common knowledge 😅

**Comment by roji** [comment]
Having a DbSet property on your context is optional - you can always refer to DbSets via the Set() method:

```c#
var auditEntries = context.Set<AuditEntry>().ToList();
```

However, it is common practice to include DbSet properties for easier use. This seems to be well-covered both in the [getting started](https://docs.microsoft.com/en-us/ef/core/#the-model) sample and in the docs on [including types in the model](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#including-types-in-the-model).

**Comment by ErikEJ** [comment]
I think the issue is poor documentation of using DbConext.Set!

**Comment by mrlife** [comment]
@roji Thank you, I sent this to a new docs issue.
