### ISSUE TITLE
Using .Skip() and .Take() with a projection places LIMIT on the wrong query.

### ISSUE THREAD

**Issue by DigiBanks99** [dotnet/efcore#24585]
## Description

I'm attempting to set up paging operations with SQLite and EF Core 5.0 on a projected data set. After writing a unit test, I wasn't getting back the expected results and I added in query logging so I could identify the cause. It seems that when a DbSet is projected to a different set, the LIMIT is placed on the inner query and a -1 LIMIT is applied to the projected query with the desired offset. The problem is that the inner query already limits the result set making the offset for the projected query useless.

### Code

The following code produces the below query. I've added a comment with the line I have a problem with. Also, see the 
[minimum reproducible code](https://github.com/dotnet/efcore/files/6258323/ef-sqlite-pagination.zip).

```cs
return await _context.Posts
                     .MapToBlogPost()
                     .Where(p => p.Content.Length > 0)
                     .ToPagedDataAsync(new PagingOptions
                     {
                         PageNumber = pageNumber,
                         PageSize = pageSize
                     });
```

Results in:

```log
Executed DbCommand (2ms) [Parameters=[@__p_0='5' (DbType = String), @__p_1='10' (DbType = String)], CommandType='Text', CommandTimeout='30']
```

```sql
SELECT "t0"."BlogId", "t0"."Content", "t0"."Id", "t0"."Title", "b"."Url"
FROM (
    SELECT "t"."Id", "t"."BlogId", "t"."Content", "t"."Title"
    FROM (
        SELECT "p"."Id", "p"."BlogId", "p"."Content", "p"."Title"
        FROM "Posts" AS "p"
        WHERE length("p"."Content") > 0
        LIMIT @__p_0 -- This is the problem as it limits the result set
    ) AS "t"
    LIMIT -1 OFFSET @__p_1
) AS "t0"
INNER JOIN "Blogs" AS "b" ON "t0"."BlogId" = "b"."Id"
```

I'd expect the generated SQL to place the `LIMIT` and `OFFSET` keywords on the final query.

```sql
SELECT "t0"."BlogId", "t0"."Content", "t0"."Id", "t0"."Title", "b"."Url"
FROM (
    SELECT "t"."Id", "t"."BlogId", "t"."Content", "t"."Title"
    FROM (
        SELECT "p"."Id", "p"."BlogId", "p"."Content", "p"."Title"
        FROM "Posts" AS "p"
        WHERE length("p"."Content") > 0
    ) AS "t"
) AS "t0"
INNER JOIN "Blogs" AS "b" ON "t0"."BlogId" = "b"."Id"
LIMIT @__p_1 OFFSET @__p_1
```
### Version information

Microsoft.Data.Sqlite version: 5.0.4
Target framework: .NET 5.0
Operating system: Windows 10 Home

**Comment by smitpatel** [comment]
The generated query corresponds to the LINQ written. For pagination you need to apply `Skip` and then `Take` in that order only but the code applies `Take` operation first. For example, you are loading 3rd page where page size is 10 then `Skip(20).Take(10)` will pick 10 records after first 20 which is essentially what 3rd page is supposed to have but `Take(10).Skip(20)` will give empty set because you have already narrowed your result set to first 10 records before `Skip` is applied.

**Comment by DigiBanks99** [comment]
Thanks so much. I didn't realise that was how it works. You learn something new every day.
