### ISSUE TITLE
Nested transaction with multiple db context

### ISSUE THREAD

**Issue by santosh-kh** [dotnet/efcore#24586]
## Clarification on Database transaction with multiple contexts.

* Is the below code is safe to use when both the contexts refer to different databases in the same server ?

### Include your code

```C#
// This raises DbUpdateException since it tries to add the same user. 
        private static async Task NestedDbTransactionWithMultipleDbAsync(User user)
        {
            try
            {            
                using var context = new UserContext();
                using var context2 = new User2Context();

                using (var t1 = context.Database.BeginTransaction())
                {
		       // succeds as its new user to context.
                    context.Users.Add(user);
                    context.SaveChanges();

                    using (var t2 = context2.Database.BeginTransaction())
                    {
                        var user2 = context2.Users.Single(t => t.UserName == user.UserName);
                        context2.Users.Add(user2);
                        await context2.SaveChangesAsync().ConfigureAwait(false);
                        t2.Commit();
                    }
                    t1.Commit();
                }
                
            }
            catch (Exception)
            {
                // throw user friendly exeption
            }
        }
```

### Include provider and version information

EF Core version: Ef Core 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.8.4

**Comment by roji** [comment]
@santosh-kh you seem to be adding the same user to two different databases. This is perfectly fine, but it's important to realize that there's no distributed transaction ensuring that both operations succeed or fail; that is, an exception could be thrown from `t1.Commit()`, leading to the user being inserted into one database but not the other.

**Comment by santosh-kh** [comment]
@roji I was not sure of this is a distributed transaction or not. My understanding was DT is only with multiple servers. This sample with nested database transaction didn't raise any exception but the one with Ambient transaction raised `System.PlatformNotSupportedException Message=This platform does not support distributed transactions.` 
Your statement **I wouldn't infer from the lack of an exception that an actual distribution transaction is going on;** makes sense here.
Thanks for the update.

**Comment by roji** [comment]
> Is the below code is safe to use when both the contexts refer to different databases in the same server ?

I'm assuming that by this you meant that the two connection strings differ only by the database name. I'm not enough of a SQL Server expert to be sure, but I think this should be identical to the case where you're connecting to totally different servers from a transaction/distributed transaction perspective.

**Comment by santosh-kh** [comment]
Yes, connection strings differ only by database name. 
OK. I was confused bcz wiki statement about Distributed Transaction was not that clear to me. 
That's where the confusion with respect to same server with multiple Databases. And since I received that `PlatformNotSupportedException` exception in case of Ambient transaction I raised for clarification.

**Comment by roji** [comment]
So yeah, a transaction over different databases imply a distributed transaction even if they're on the same server, as the exception message shows.

Am closing this issue as things seem clear, but if you have further questions don't hesitate to write back.
