### ISSUE TITLE
Updating many-to-many relation

### ISSUE THREAD

**Issue by julian-dimitroff** [dotnet/efcore#24582]
Hello,
I have a question about updating many-to-many relationships. So I have the following scenario:
```C#
//First Model
public class RoomModel
{
    public long Id { get; set; }
    public string Name { get; set; }
    public long ZoneId { get; set; }

    public ICollection<ZoneRoomModel> Zones { get; set; }
}

//Second model
public class ZoneModel
{
    public long Id { get; set; }
    public string Name { get; set; }
	
    public ICollection<ZoneRoomModel> Rooms { get; set; }
}

//Many-to-many relation
public class ZoneRoomModel
{
    public long ZoneId { get; set; }
    public long RoomId { get; set; }

    public ZoneModel Zone { get; set; }
    public RoomModel Room { get; set; }
	
}
```
I use this code to handle the update:
```C#
var roomModels = new List<RoomModel>
{
    new RoomModel
    {
        Id = 1,
        Name = "Forrest Restaurant",
        Zones = new List<ZoneRoomModel>
		{
			new ZoneRoomModel {RoomId = 1, ZoneId = 7}
		}
    },
    new RoomModel
    {
		Id = 0,
        Name = "Forrest Restaurant 1",
        Zones = new List<ZoneRoomModel>
		{
			new ZoneRoomModel {RoomId = 0, ZoneId = 1},
			new ZoneRoomModel {RoomId = 0, ZoneId = 5},
			new ZoneRoomModel {RoomId = 0, ZoneId = 7},
		}
    }
};

using(var dbContext = new DBIContext())
{
    dbContext.UpdateRange(roomModels);
    dbContext.SaveChanges();
}
```
In the database I have a `Room` with `Id=1`, and in the `many-to-many` table called `ZonesRooms` I have an entrries `RoomId = 1 , ZoneId = 3` and `RoomId=1, ZoneId=4`.

When I execute the query I expect to have one new entry with `RoomId=2` in `Rooms` table, and 3 new entries in the `ZonesRooms` table, and one modified entry for `RoomId=1` in `Rooms` table, and 1 row in `ZonesRooms` table.

What actually happens is that the new room is added in `Rooms` and `ZonesRooms` tables, the modified room is only modified in `Rooms` table and not in the `ZonesRooms` table.

How can I achieve for new entries to add them in the two tables, but for the modified ones, to modify the entity and to erase all from the `many-to-many` table, and add the newly entered?

If there is something that I've missed in the question, please let me know and I'll provide it.

EF Core version: 5.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreDQL
Target framework: 5.0.4
Operating system: Windows 10
IDE: Microsoft Visual Studio Community 2019
Version 16.9.3

Regards,
Julian

**Comment by ArminShoeibi** [comment]
Hello, If you have Implicit Many to Many relationships with EF Core it is really easy to do update operations.
for example.
```
public class Room
{
    public long Id { get; set; }
    public string Name { get; set; }
    public long ZoneId { get; set; }
    public ICollection<Zone> Zones { get; set; }
}
public class Zone
{
    public long Id { get; set; }
    public string Name { get; set; }
    public ICollection<Rooms> Rooms { get; set; }
}
```
```
public async Task UpdateRoom(long roomId,int[] zoneIds)
{
  using(var dbContext = new DBIContext())
  { 
       Room roomToUpdate =  dbContext.Rooms.Include(r=> r.Zones).SingleOrDefaultAsync(r=> r.Id == roomId);        
       List<Zone> zonesToUpdate =  dbContext.Zones.Where(r=> zoneIds.Contains(r.Id)).ToListAsync();         
       roomToUpdate.Zones = zonesToUpdate;
       dbContext.SaveChangesAsync();
       /* Check the query and enjoy, you can perform something like this code for Explicit many to many*/
  }
}
```

**Comment by julian-dimitroff** [comment]
@ArminShoeibi  thanks for your answer!
It is working like this, but this way I'm not able to update the rest of the `RoomModel` properties, unless you do it manually one by one. This way I'm missing the `.Update()` functionality.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi thanks for your answer!
> It is working like this, but this way I'm not able to update the rest of the `RoomModel` properties unless you do it manually one by one. This way I'm missing the `.Update()` functionality.

No, you can update other properties.
just assign them to the value that UI Sents, and after all, you don't need to Call the Update Method because this way you are using Change Detection Update (Change Tracker Feature), and the generated query is better than the update method.

**Comment by julian-dimitroff** [comment]
@ArminShoeibi Thanks again. This is the way I've done it! 
Thank you for your time!
