### ISSUE TITLE
Running seeds from package manager console

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2459]
In addition to migration seeds in EF7 #629

It would be very useful to be able to write seeds that aren't automatic run when `Update-Database` is run.

Something like `Seed-Database "TestData"` would be nice.

Being able to run specific seeds from code would also go a long way when doing integration testing that includes the database - especially with the new "in memory context" :)

**Comment by Bartmax** [comment]
:+1:

**Comment by ajcvickers** [comment]
EF Core 2.1 contains a new mechanism for data seeding that is different from either the database initializer or Migrations seeding from EF6. With this mechanism it is possible to change seed data and scaffold a migration that will make those changes in the database regardless of whether or not the schema has changed. We are also planning to make this work with the in-memory database, although it does not currently do so. Beyond this we are not planning to add anything further around seed data (other than enhancements and bug fixes to that mechanism) but will compelling feedback we may reconsider this decision.
