### ISSUE TITLE
Will opening a StreamWriter for logging and leaving it open, possibly result in Action at a Distance anti-pattern?

### ISSUE THREAD

**Issue by rfalanga** [dotnet/efcore#24593]
I'm going through Julie Lerman's EF Core: Getting Started course on Pluralsight. In that course she demonstrated how you can use a StreamWriter to write to a log file. Awesome functionality!

However, I do have one major concern. Over my years of writing code, I've learned that it is easy to write a code that uses the [Action at a Distance anti-pattern](https://en.wikipedia.org/wiki/Action_at_a_distance_(computer_programming)). I've did it enough and had such bazaar behavior that I have made it a point of avoiding it. Recently one of my colleagues violated the Action at a Distance anti-pattern, which resulted in one instance of a program killing off any other instances when the user tried to bring up another instance.

So, I'd like to ask if EF Core, working with a StreamWriter to a log file is "smart" enough to only open the log file when it's about to write to it? Or will it violate Action at a Distance and leave the log file open for as long as the app is running?

Remember:

* Please make your question as clear and specific as possible.
* Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include verbose output when asking questions about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
@rfalanga it's not immediately obvious what exactly you're asking about - a code sample of what you're thinking of could help.

> So, I'd like to ask if EF Core, working with a StreamWriter to a log file is "smart" enough to only open the log file when it's about to write to it? Or will it violate Action at a Distance and leave the log file open for as long as the app is running?

This doesn't seem related to EF Core in any way - [StreamWriter](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter?view=net-5.0) is just part of basic .NET.

By default, StreamWriter does open the file when its instantiated (with the string-based constructor overloads), and closes it when disposed (though see the docs for more info). I do not believe this is bizarre behavior or an example of "action at a distance".

**Comment by rfalanga** [comment]
Thank you @roji, the link you pointed to does confirm what I was asking about. I know that StreamWriter when used with EF 6 would open and hold onto the file until it was closed and disposed of.  I now see This behavior is the same under .NET 5. I'll illustrate by explaining what's happened where I work.

At work we're writing a WPF app using .NET 4.5.2 and EF 6. One of my colleagues wanted to write to a log file, but what he did was opened the log file with a StreamWriter in the App.xaml.cs file, then leave it open throughout the lifetime of the app, by specifying a global variable for the StreamWriter object. That way, anyone could write to the log file from any class in the app using that global variable. However, what my colleague didn't realize was that having that global variable to the StreamWriter object resulted in an Action at a Distance anti-pattern. Users would complain, because when they try to launch a second instance of the application while the first version was still running, the second version never showed up. "That's weird" they'd tell us. They can launch multiple instances of Word or Excel, why can't they launch multiple instances of our app? The reason is simple, the first instance opens the log file and no other instance could then open the log file. The first instance blocks all subsequent versions from opening the log file, so the first instance crashes all subsequent attempts to run the app again while the first instance is still up. From the viewer's point of view, it was bizarre behavior.  And I now see that EF Core ability to work with a StreamWriter to write to a log file will be the same as it was with EF 6. BTW, I changed the code to get rid of the global variable. Now people have to call a public method of the App object to write to the log file with the StreamWriter, but now it opens the log file, writes to it, and the StreamWriter is immediately disposed of afterwards.

**Comment by roji** [comment]
@rfalanga you seem to be confusing things - EF Core has nothing to do with StreamWriter. Your application may be using EF Core and also logging with StreamWriter, but the two aren't related in any way.

As for your specific issues with StreamWriter, I'd advise looking at one of the serious .NET logging packages (e.g. [Serilog](https://serilog.net/), [NLog](https://nlog-project.org/)), rather than rolling your own logging. It sounds like with your solution, you may get a corrupt log file if both instances of your application attempt to write at the very same time (or you may lose logging messages).

**Comment by rfalanga** [comment]
I agree with you and normally do so. However, I'm talking about my colleagues who'd rather role their own and never use some .NET logging package.
