### ISSUE TITLE
Find/Single issue inefficient SQL

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#2460]
Find issues SQL like this:

```
exec sp_executesql N'SELECT TOP (2) 
    [Extent1].[ID] AS [ID], 
    [Extent1].[Name] AS [Name]
    FROM [dbo].[Customers] AS [Extent1]
    WHERE [Extent1].[ID] = @p0',N'@p0 int',@p0=7
```

The TOP 2 is unnecessary.

Entity Framework should either recognize that there is a filter on a unique key or it should special-case for Find.

This really is a minor problem. But the TOP 2 shows up in the execution plan for SQL Server so that this is not exactly zero runtime cost.

The same issue applies to code like `db.Orders.Single(o => o.CustomerID == customerID)`.

Just wanted to create an issue for this so that you can track it as a work item. Certainly not top priority.

**Comment by vossad01** [comment]
If I understand this correctly, you are saying that when you are using `Single` (or `Find`) to retrieve an entity via its Primary Key, you are expect that EF to trust there is only one entry and not include a **TOP** clause in the query?

**Comment by GSPP** [comment]
Yes, EF requires this invariant anyway. There cannot be multiple entities with the same primary key. When there is a unique index, which is 99.999% common for the key of an entity, there really can't be duplicates under any circumstances.

**Comment by bricelam** [comment]
There is no guarantee that the database enforces (or even has) a primary key constraint. If you don't want to check that there is exactly one result of the query, use `.First()` instead.

**Comment by GSPP** [comment]
It is important to document the fact that only a single result is expected. `First` would explicitly document that multiple results are expected.

What about my other point that EF requires unique entities anyway? This is a fundamental assumption.

**Comment by bricelam** [comment]
I can imagine a poorly designed database that has no actual primary key constraints and is used by various other applications/technologies that might insert duplicate keys. EF requires entity keys to be unique. Thus, when you access the database using EF, you have to manually ensure that the keys are unique using things like `.Single()`.

**Comment by GSPP** [comment]
OK, makes sense. Feel free to close this.

**Comment by divega** [comment]
If there is a significant perf/scslability advantage in the simplerquery I would err on not doing anything special about poorly designed databases.

**Comment by divega** [comment]
Moreover, we can still throw if the query returns more than one row since only one is expected, i.e. we can `.Single()` in memory on the results.

**Comment by vossad01** [comment]
This may be a silly question, but, why would **TOP** be a performance problem in the case we are talking about?

If the complete results set has zero, one, or two items, is the cost of counting them and checking they are less than three significant?
If there are many, is it really *more* expensive to only return two rather than returning all of them?

**Comment by divega** [comment]
@vossad01 Nothing in my mental model of how databases work tells me that there should be a significant difference. However ad-hoc testing shows that without the TOP 2 is 6 times faster :smile:

**Comment by divega** [comment]
@GSPP BTW, we don't have `Find()` in the EF7 API (this is something we currently have in the backlog #797) so I assume you are focusing on EF6. If you would like this to be improved I would like to encourage you to send a PR for the EF6 project which lives at http://entityframework.codeplex.com.

**Comment by divega** [comment]
My original ad hoc test was executing long scripts with thousands of queries (with and without the TOP (2) part) inside SQL Server Management Studio. I prepared a new test which executed the queries programmatically using SqlClient APIs, which should be more representative of what EF would need to do, and I couldn't observe any significant difference. Therefore I am going with the assumption that there isn't a strong enough reason to change this, at least from the perf perspective when using SQL Server.
