### ISSUE TITLE
dbcontext disponse doesn't close connection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#24608]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/dbcontext-disponse-doesnt-close-connect/1376526)._

---
[severity:Other]
I query data based on a value set at user level, so every time a user logs on, it must be populated to filter data, I'm using OnModelCreating to add the filter but it only runs the first time even after dispose the context at logout.

---
#### Mila Zhou[MSFT] on 3/21/2021, 07:54 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? What is the actual result and which result do you expect to happen?</p>
<p>We look forward to hearing from you!</p>

#### Carlos Miranda on 3/22/2021, 08:45 AM: 

(private comment, text removed)
#### Feedback Bot on 3/26/2021, 02:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Carlos Miranda on 3/26/2021, 08:33 AM: 

<p>Thanks,</p>
<p>Do you have any plan on how long does it could take? beacuse I need a workaround if it takes to long.</p>
<p>Regards.</p>

---
### Original Solutions
(no solutions)

**Comment by roji** [comment]
It looks like we're going to need more details, including a code sample that shows exactly what's being done.

**Comment by caml1mx** [comment]
Hi,

I upload the issue and attached you'll find the entire communication I had with the VS team including the code. If you need more info please let me know.

Thanks
[dbcontext disponse doesn't close connection - Visual Studio Feedback.pdf](https://github.com/dotnet/efcore/files/6279600/dbcontext.disponse.doesn.t.close.connection.-.Visual.Studio.Feedback.pdf)

**Comment by caml1mx** [comment]
It looks like the PDF doesn't get the entire info, I upload a new one.
[dbcontext disponse doesn't close connection - Visual Studio Feedback.pdf](https://github.com/dotnet/efcore/files/6279666/dbcontext.disponse.doesn.t.close.connection.-.Visual.Studio.Feedback.pdf)

**Comment by roji** [comment]
Reposting the user repro here in an easier format as the details have been posted publicly above as a PDF:

> When I create a new user a client value is requested to specify the user data environment, so when the user logsin, this client value is used to filter the data using the code:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);
    string cliente = this.HttpContextAccessor.HttpContext.Session.GetString("Cliente");
    if (cliente.Trim() != "*")
    {
        List<PropertyInfo> dbsetProps = new List<PropertyInfo>();
        var props = this.GetType().GetProperties();
        foreach (var item in props)
        {
            var settype = item.PropertyType;
            if (settype.Name.Contains("DbSet"))
            {
                string stype = settype.ToString().Split("[")[1].Split("]")[0];
                Type ttype = Type.GetType(stype);
                var campos = ttype.GetProperties().Select(f => f.Name).ToArray();
                if (campos.Contains("Cliente"))
                {
                    var parametro = Expression.Parameter(ttype, "SocioNegocio");
                    var bar = MemberExpression.Property(parametro, "Cliente");
                    PropertyInfo inPro = ttype.GetProperty("Cliente");

                    var valor = Expression.Constant(cliente);
                    var condicion = Expression.MakeBinary(ExpressionType.Equal, bar, valor);
                    modelBuilder.Entity(ttype).HasQueryFilter(Expression.Lambda(condicion, parametro));
                }
            }
        }
    }
}
```

> This filter remains at the entire session. When the users logsout I close everything with:

```c#
public ActionResult Logout()
{
    HttpContext.Session.Clear();
    _context.Database.CloseConnection();            
    _context.Dispose();

    return RedirectToAction("Logout", "Login");
}
```

**Comment by roji** [comment]
@caml1mx it seems that you're configuring a global query filter dynamically inside your DbContext's OnModelCreating, and expect it to be recalculated every time a DbContext is instantiated (i.e. with each HTTP request). This is not how EF Core works - OnModelCreating is only executed once, the first time a DbContext is used; model creation is typically quite a heavy process, and should not be executed for every DbContext instantiation.

It looks like you're trying to implement a multi-tenant application, where global filters are automatically applied to queries based on values in the HTTP request. Our documentation includes [an example of how to use global filters in this way](https://docs.microsoft.com/en-us/ef/core/querying/filters#example); in a nutshell, your DbContext will need to hold the tenant ID ("Cliente"), which you would have to supply when instantiating the DbContext (from the HTTP request); your global query filter would then reference this field.
