### ISSUE TITLE
Migrations: Scaffold comments

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2461]
Migrations should be able to scaffold comments for operations like.

``` C#
// This operation may result in data loss.
migrationBuilder.DropTable("Customers");
```

Providers should also be able to participate, for example, SQLite may want to write something like.

``` C#
// On SQLite, this operation results in a table rebuild.
migrationBuilder.DropColumn(name: "Birthday", table: "Customers");
```

**Comment by bricelam** [comment]
Here are some thoughts I had on implementing this:

The model differ could pass the operations to the provider giving them a chance to add annotations like `CodeGen:Comment = "This will rebuild the table."`. The scaffolder would then use these special CodeGen annotations when serializing the operations.

**Comment by natemcmaster** [comment]
Although a comment is helpful, I think casual users may not read the comments. When data loss is possible, could we do more assertive , such as requiring a command-line flag "--AllowDrops" or prompting y/n on migration execution?

**Comment by bricelam** [comment]
We already log a yellow warning when operations that could result data loss are scaffolded. But there currently isn't a way for providers to influence whether an operation could result in data loss.

**Comment by divega** [comment]
Here is another scenario we may want to generate comments for: *Add a migrations warning for ValueGeneratedOnAdd for a non-key property for SqlServer #7295*

**Comment by ajcvickers** [comment]
We have already improved logging/feedback in this area, and we hope to improve it further once simple logging is implemented in EF Core. Closing this issue as there is nothing actionable here that isn't tracked elsewhere.
