### ISSUE TITLE
Bug in Getting Started with EF Core docs

### ISSUE THREAD

**Issue by QuantumHive** [dotnet/efcore#24613]
See: https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli#create-read-update--delete

When adding a post to a blog with
`blog.Posts.Add(new Post { Title = "Hello World", Content = "I wrote an app using EF Core!" });`
a null reference exception gets thrown because the `Posts` property on the `Blog` object is null.

**Comment by ajcvickers** [comment]
@QuantumHive Looks like you missed the initializer:

```C#
public List<Post> Posts { get; } = new List<Post>();
```
