### ISSUE TITLE
Cascade delete in table per type(TPT) 

### ISSUE THREAD

**Issue by dimitkos** [dotnet/efcore#24622]
EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 5.0
Operating system: Windows10
IDE:  Visual Studio 2019 16.8.6

I have two entities employee, manager, which class manager inherit from the employee

```
public class Employee
{
        public long Id{ get; private set; }
        public string FirstName { get; private set; }
        public string LastName { get; private set; }
}
```

```
public class Manager: Employee
{
        public long StoreId{ get; private set; }
}
```

I am using type per table due to parent-child relationship, with fluent API configuration

```
class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {

        public void Configure(EntityTypeBuilder<Employee> builder)
        {
            builder.ToTable("Employee");
            builder.HasKey(x => x.Id);    

        }
    }

class ManagerConfiguration : IEntityTypeConfiguration<Manager>
    {

        public void Configure(EntityTypeBuilder<Manager> builder)
        {
            builder.ToTable("Manager");
        }
    }
```
As a result, I have two tables in the SQL server.
The problem is, I want a cascade on delete behavior, when I remove the employee, I want to remove and the record of the manager table. But the default behavior is not this. When I try to delete the parent record I have an FK violation.

I try this method and get the error
```
public async Task DeleteManagers(long[ ] managerIds)
{
      var sqlCommand = $"DELETE FROM dbo.Manager WHERE Id IN ({string.Join(',', managerIds)})";
      await _context.Database.ExecuteSqlRawAsync(sqlCommand);
}
```
Also in the migrations file, the autogenerated code from migration is 
```
b.HasOne(".......Employee", null)
                        .WithOne()
                        .HasForeignKey("....Manager", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
```
How I can configure the OnDelete to cascade in a table per type case?

**Comment by ajcvickers** [comment]
Note for triage: confirmed we don't configure cascade delete here.

**Comment by AndriySvyryd** [comment]
This is by design, using CASCADE by default will very likely result in an error:

> Introducing FOREIGN KEY constraint 'FK_Derived_Base_Id' on table 'Derived' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

However you can configure it manually:

```C#
modelBuilder.Entity<Derived>().HasOne<Base>().WithOne()
    .HasForeignKey<Derived>(d => d.Id).OnDelete(DeleteBehavior.Cascade);
```
