### ISSUE TITLE
Value conversion and query parameters

### ISSUE THREAD

**Issue by andriysavin** [dotnet/efcore#24625]
I'm trying to understand whether the following is a bug or a limitation of value converters, so will describe my problem without much concrete code. 

I'm using EF Core 5.0 on .Net 5.0 runtime.

I have a column in a table (let's name it _Inactive_) which is of `smallint` (nullable) type but with logical meaning of boolean. However it's not a two-values boolean, but instead 0 and NULL means `false` and all other values mean `true`. I wanted this column to look `bool` in my model, so I added value conversion like this:

```csharp
 b.Property(e => e.Inactive).HasConversion<short?>(
   modelValue => (short)(modelValue ? 1 : 0),
   providerValue => providerValue == null || providerValue == 0 ? false : true);
```

Now, when I want to filter entities by `Inactive == true`  the SQL query generated looks like:

`WHERE [e].[Inactive] = @__filterCriteria_Inactive_1`

where

` @__filterCriteria_Inactive_1='1'`

But based on the column definition I provided at the beginning I would expect something equivalent to:

`WHERE [e].[Inactive] <> 0 and [e].[Inactive] IS NOT NULL`

which would allow not only `1` value, but any others except for 0 and NULL.

I can guess that query parameters go through the same model-to-provider conversion as entity property does, so `true` parameter becomes `1` after conversion. But it takes into account only one direction of conversion (model-to-provider) and ignores another. Of course, there could be opposite design, where DB column would be `bit` and entity property would be `short`, and then this query would probably be generated correctly for similar conversion.

So the questions: 
1. Is this behavior a bug or a limitation? 
2. Are there any plans to provide ability to swith which conversion expression is analyzed for WHERE clause generation?
3. Is there a workaround for the described scenario?

Thanks.

**Comment by smitpatel** [comment]
Query does not analyze any expression, you passed `true` value on client side, we just run it through value converter to get server side value and put that in the query. So whatever your value converter gives (here `1`) is what we sent.
The issue here is that your value converter is not round-trip compatible. In one part of your converter you are saying that if value is true then it will be 1 in database but other side you are saying that 2 can also be true. Since both of them are contradicting you are seeing error.

**Comment by andriysavin** [comment]
@smitpatel thanks for you answer.
The convertors are not contradicting in the whole sense of the word, though I agree they are not round-trip compatible. This is because model and provider have different ranges of values they can store, so they just can't be symmetric in that sense. So it looks like this scenario is not supported.

**Comment by smitpatel** [comment]
They are contradicting in the sense that `true` value in LINQ equality when send to server after conversion as `1` not giving all results. So your clause is not matching the data.
I explained above how query works, so yes this is not supported scenario.

**Comment by andriysavin** [comment]
@smitpatel thanks again. I'm closing this issue then.
