### ISSUE TITLE
Automatic client evaluation outside top-level projection still works in some cases

### ISSUE THREAD

**Issue by MarkFl12** [dotnet/efcore#24632]
In Entity Framework Core 5.0.5 the automatic query client evaluation that was disabled with #14935 is still working in some cases.

```C#
void Main()
{
	// First Query
	dbContext.Things.Where(GetBool).ToList();

	// Second Query
	dbContext.Things.Where(a => GetBool(a)).ToList();
}

public Boolean GetBool(Assessment a)
{
	return a.Id % 2 == 1;
}
```

While the second query throws `InvalidOperationException` as expected due to the use of a method that cannot be translated, the first query loads the entire table in to memory still and filters it there.

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: LINQPad 6 / Visual Studio

**Comment by smitpatel** [comment]
When you are writing first way you are not using Queryable.Where, you are using Enumerable.Where method so EF Core only sees query as dbContext.Things.AsEnumerable(). There is nothing EF Core can do about it.
