### ISSUE TITLE
Correlation beetween IsKeySet and EntityState.Added

### ISSUE THREAD

**Issue by NetDefender** [dotnet/efcore#24633]
Hi, I have a custom base model class that has a custom/user state field that is not saved:

```C#
public abstract class EFModel
    {
        #region properties        
        /// <summary>
        /// Gets or sets the state.
        /// </summary>
        /// <value>
        /// The state.
        /// </value>
        public EFEntityState State
        {
            get;
            set;
        }
        #endregion
    }
```
I use consecutive negative values for the key in client only.
I use
```C#
.ValueGeneratedOnAdd().UseIdentityColumn()
```
In database keys are represented by Identity columns.
Then i have created an alternate SaveChanges method:

```C#
public Task<int> SaveChangesWithChangeTracker<T>(T rootEntity)
    where T : class, new()
{
    ChangeTracker.Clear();
    ChangeTracker.TrackGraph(rootEntity, graphNode =>
    {
        EFModel currentEntity = ((EFModel)graphNode.Entry.Entity);
        currentEntry.State = EFStateToEntityState[currentEntity.State]; //Dictionary that maps userstate to entity state
    });

    return SaveChangesAsync();
}
```

When the model is in Added state and the value of the key field is negative, an exception is thrown because it tries to explicitly insert the value on identity column. This error does not occur if the value of the key field is 0 (which is the default behavior of IsKeySet)
If the entity is in the Added state, shouldn't the value in the Id field be ignored?

¿How can i maintain multiple entities from a client side perspective if all must have a 0 in the key?

### Provider and version information

EF Core version: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 3.1)
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2019 16.9.3

**Comment by ajcvickers** [comment]
@NetDefender [Explicit manipulation of temporary values](https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#temporary-values) is currently more difficult that in should be due to #24245. This is fixed for the 6.0 release.
