### ISSUE TITLE
Updating/inserting into a Sql Server table with Always Encrypted columns using EF Core 5

### ISSUE THREAD

**Issue by jwakeen** [dotnet/efcore#24644]
Is EF Core 5 capable of using the normal SaveChanges() pattern to make updates to data in a SQL Server with Always Encrypted columns? I'm having trouble using Entity Framework Core 5 with the "Always Encrypted" feature in a ASP.NET Core 5 API. I've configured an Azure Key Vault and updated the connection string as necessary. I can read encrypted column data successfully, with code like this:

await using var context = new RcContext();
Company c = await context.Companies.FindAsync(id);

where the Companies table has an encrypted column. The encrypted column is defined in the database as datatype varchar(16) and is returned as plain text in a string member of the entity.

However, trying to update a company or insert new companies using context.SaveChanges() is failing. I get the error

SqlException: Operand type clash: nvarchar(4000) encrypted with ... is incompatible with varchar(16) encrypted with ...

Some suggestions for solving this point to using SqlCommand from SqlClient or stored procedures, or increasing the column's size in the database to nvarchar(max). Just as a test, I changed the encrypted column in the database to be type nvarchar(max) and context.SaveChanges() worked. I don't think this is a long term solution.

How do I make SaveChanges() work with EF Core 5?

**Comment by ajcvickers** [comment]
@jwakeen You need to make sure that the EF model contains the correct mapping for the specific database type needed. The easiest way to do this is to [configure the type explicitly](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-data-types). For example:

```C#
[Column(TypeName = "varchar(16)")]
public string Foo { get; set; }
```

**Comment by jwakeen** [comment]
Well, I still get the same type class exception, even after adding:

		[Column(TypeName = "varchar(16)")]
		public string PaymentAccountNumber { get; set; }

To the entity model.

**Comment by ajcvickers** [comment]
@jwakeen In that case, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jwakeen** [comment]
Creating a runnable sample helped me see that  _all_ columns that are encrypted must be attributed with `[Column(TypeName)]`, not just the ones being changed in the update or insert statement. `SaveChanges()` now works as expected.
