### ISSUE TITLE
Entity Framework store previous savechange with error

### ISSUE THREAD

**Issue by Balirezaei** [dotnet/efcore#24642]
I am using EF Core 3.1.11 with SQL Server. When a SaveChanges call results in an error, the next call to SaveChanges will again cause this error.

This is the error I get:

> The DELETE statement conflicted with the REFERENCE constraint ...:

from running this code:
`var Label = await _repository.Find(cmd.Id);`
`_repository.Delete(Label);`
`await _unitOfWork.CommitAsync();`

And this is the next code snippet:

`var label = new Label( cmd.Title, cmd.ParentId);`
`await _repository.Add(label);`
`await _unitOfWork.CommitAsync();`

The insert query on SQL Server profiler not run EF run previous delete query?

The context config is :

`services.AddDbContext<CoreDomainContext>(options =>
        {
            options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
            options.UseSqlServer(this.Configuration.GetConnectionString("CoreDomainContext"));
        });`

Git Url: https://github.com/Balirezaei/mozaeekFramework

**Comment by roji** [comment]
@Balirezaei can you please post a full, runnable code sample which reproduces the error?

**Comment by Balirezaei** [comment]
> @Balirezaei can you please post a full, runnable code sample which reproduces the error?
yes https://github.com/Balirezaei/mozaeekFramework
Thanks a lot 🙏

**Comment by roji** [comment]
@Balirezaei when your delete fails, the DbContext continues tracking the deletion - since it didn't actually take place. This is important, since the assumption is that the unit-of-work can't proceed if this step failed. For example, in your case, you're not going to be able to insert a label if the delete for an existing label with the same ID failed.

Your client (the integration test in this case) should stop at the point where the delete fails and not attempt to insert. Otherwise, you can instantiate a new DbContext which won't have the delete still pending (or use the new [ChangeTracker.Clear](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker.clear?view=efcore-5.0) in EF Core 5.0).

**Comment by Balirezaei** [comment]
> e able to insert a label if the delete for an existing label with the same ID failed.
In Test case  I show in one Unit test but in our real application React Js Client send separate HttpRequest.
The Error still remind.
I have used NoTracking config in initialize Context.

options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)

**Comment by Balirezaei** [comment]
> @Balirezaei when your delete fails, the DbContext continues tracking the deletion - since it didn't actually take place. This is important, since the assumption is that the unit-of-work can't proceed if this step failed. For example, in your case, you're not going to be able to insert a label if the delete for an existing label with the same ID failed.
> 
> Your client (the integration test in this case) should stop at the point where the delete fails and not attempt to insert. Otherwise, you can instantiate a new DbContext which won't have the delete still pending (or use the new [ChangeTracker.Clear](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker.clear?view=efcore-5.0) in EF Core 5.0).

In Test case  I show in one Unit test but in our real application React Js Client send separate HttpRequest.
The Error still remind.
I have used NoTracking config in initialize Context.

options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)

**Comment by roji** [comment]
NoTracking only affects what queries do when you load entities from the database. The moment you call Delete, you're asking the context to track the deletion of the entity - to be executed in the next call to SaveChanges.

**Comment by Balirezaei** [comment]
I change my save change in UnitOfwork and manually Clear ChangeTracker.
And My problem is solved.

> public async Task CommitAsync()
        {
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                foreach (var item in _context.ChangeTracker.Entries())
                {
                    _context.Entry(item.Entity).State = EntityState.Detached;
                }
                throw e;
            }
        }

**Comment by Balirezaei** [comment]
Our problem was about registration of Command Bus in our Framework. It was 

>  services.AddSingleton<ICommandBus, CommandBus>();

That would make Context Lifecyle work inappropriate.
It should be as following.

 `services.AddScope<ICommandBus, CommandBus>();`
