### ISSUE TITLE
Are EF.Functions with string interpolation protect against sql injection

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#24656]
## Ask a question

I m using EF. Functions and I wanted to ask if using EF.Functions with string interpolation if we are protected against Sql injection attacks. 
Example of my code below

```
EF.Functions.Contains(user.FirstName, $"%{input.SearchText}%"
```

EF Core version: 5
Database provider: e.g. Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: WIn 10
IDE: Visual Studio 2019 16.8.5

**Comment by roji** [comment]
Yes, EF Core escapes all string literals so that a single quote (`'`) would be transformed to two single quotes (`''`).

Note that in the above, the interpolation itself is done by C#, and EF isn't aware of it in any way - it just receives a simple string literal for translation.

**Comment by pantonis** [comment]
Thanks!
