### ISSUE TITLE
Should EntityEntry's Expression-based parameters be nullable-friendly?

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/efcore#24659]
Hi guys,

With EF Core 6.0 adopting nullable annotations pretty much everywhere, we now have a great coverage (thanks for that!).
I'm currently testing my OpenIddict framework on the latest .NET 6.0 preview and I'm now seeing a few warnings caused by things like `Context.Entry(authorization).Reference(entry => entry.Application)` when the referenced navigation property is nullable, which requires using a null-forgiving operator to fix them (e.g `Context.Entry(authorization).Reference(entry => entry.Application!)`).

My question/demand is simple: is it the expected behavior or will the methods taking an expression accessor be updated at some point to allow referencing nullable navigation properties without triggering warnings?

/cc @roji as I believe you've taken care of most of the "add nullable annotations everywhere" tasks 😃

**Comment by roji** [comment]
@kevinchalet thanks for raising this - it seems to be a case of incorrect annotation.

Null-annotating the entire EF Core codebase is a massive task, and we're bound to have made some mistakes - so I wouldn't assume that any weirdness you're seeing is by-design. Please don't hesitate to flag such issues to us as you've done here.

@smitpatel I think you did most of change tracking, are you interested in taking a look? If not let me know.

**Comment by kevinchalet** [comment]
Makes total sense, thanks! 👍🏻

**Comment by smitpatel** [comment]
https://github.com/dotnet/efcore/blob/b39308175a2902f0015c959e0637d0b62414362d/src/EFCore/ChangeTracking/EntityEntry%60.cs#L76-L83
How do want to annotate this exactly?

**Comment by kevinchalet** [comment]
`Expression<Func<TEntity, TProperty?>> propertyExpression`?

**Comment by roji** [comment]
There's also the possibility of constraining TProperty to `class?` instead of `class`, but that would flow through to the ReferenceEntry's generic type as well, so we'd need to look a bit wider at how it all works together...

**Comment by roji** [comment]
See discussion of different annotation possibilities in https://github.com/dotnet/efcore/pull/25591#issue-716051040
