### ISSUE TITLE
Query with Negative multiple AND's generating query with OR (SqlServer)

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#24665]
If I have an query `.Where(x => !(x.Name == "Adam" && x.Type == "Person"))` I expect the query generated as `NOT (Name = 'Adam' AND Type = 'Person')` but during test this query is generated as `Name <> 'Adam' OR Type <> 'Person'` that make the query to exclude wrong result.

If I write the query as `.Where(x => x.Name != "Adam" && x.Type != "Person")` or `.Where(x => !(x.Name == "Adam") && !(x.Type == "Person"))` the query is translated correctly.

```C#
public class TestRunner
    {
        private readonly Db _db;

        public TestRunner(Db db)
        {
            _db = db;
        }

        public void Run()
        {
            _db.TableA.Where(x => !(x.Name == "Adam" && x.Type == "Person")).ToList();
        }
    }

    public class TableA
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }

    public class Db : DbContext
    {
        public Db()
        {
        }

        public Db(DbContextOptions options) : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Data Source=(local); Integrated Security=True; Initial Catalog=BugTest;MultipleActiveResultSets=True");
        }

        public DbSet<TableA> TableA { get; set; }
    }
```
Full example of running application exists here https://github.com/Tasteful/bugs/tree/efcore-where-not-problem

### Include verbose output

From console log where we can see that the select expression is build correctly and the generated SQL is with `OR` instead of `AND`.
```
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<TableA>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: TableA.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: TableA.Name (string), 1], [Property: TableA.Type (string), 2], }
              SELECT t.Id, t.Name, t.Type
              FROM TableA AS t
              WHERE Not((t.Name == N'Adam') && (t.Type == N'Person'))),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, TableA>,
          BugTest.Db,
          False,
          False
      )'

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Name], [t].[Type]
      FROM [TableA] AS [t]
      WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) OR (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
```

### Include provider and version information

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.4

**Comment by roji** [comment]
> that make the query to exclude wrong result.

The writing of `!(x == a && y ==b)` to `x != a || a != b` is by-design (see [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws)), can you provide more detail on how exactly this is causing wrong results?

**Comment by Tasteful** [comment]
For me the `!(x == a && y ==b)` should be transformed as "all items that not x == a and not y == b" but it will be transformed to "all items that not x == a or not y == b"

So if yo have the `!(x.Name == "Adam" && x.Type == "Person")` is that I want all items that not name is "Adam" where type is "Person" but is transformed to all items where not Name is "Adam" or not Type is "Person".

If we having the following items in database
Item1: Name: Adam Type: Person
Item2: Name: Ben Type: Person

I will get 0 result out because both of them have Type == "Person".

If I rewrite the query to `.Where(x => !(x.Name == "Adam" || x.Type == "Person"))` it will be translated into
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Name], [t].[Type]
      FROM [TableA] AS [t]
      WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) AND (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
```
result in: give me all items that not have name "Adam" or is null and the Type is "Person" or null. 
This will result in if the Name or Type column be `NULL` then the record will also be excluded but the result is more in the direction that I want.

My original code is dynamic built expression, in simplified form
```
Expression<Func<TableA, bool>> w = x => x.Name == "Adam" && x.Type == "Person";
Expression<Func<TableA, bool>> negative = Expression.Lambda<Func<TableA, bool>>(Expression.Not(w.Body), w.Parameters);
_db.TableA.Where(negative).ToList();
```

**Comment by Tasteful** [comment]
If the result of `.Where(x => x.Name == "Adam" && x.Type == "Person")` should result in all items that "Name is Adam and Type is Person", the inverse version should return all items that NOT "Name is Adam and Type is Person".

Do it exists any way to get around the De Morgan's laws to get my expected result?

**Comment by Tasteful** [comment]
> If I rewrite the query to `.Where(x => !(x.Name == "Adam" || x.Type == "Person"))` it will be translated into
> 
> ```
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
>       SELECT [t].[Id], [t].[Name], [t].[Type]
>       FROM [TableA] AS [t]
>       WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) AND (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
> ```
> 
> result in: give me all items that not have name "Adam" or is null and the Type is "Person" or null.
> This will result in if the Name or Type column be `NULL` then the record will also be excluded but the result is more in the direction that I want.

I can see that this probably will return the rows that I want but need to write an expression visitor to change the "AND" to "OR" before passing that into the Where.

**Comment by roji** [comment]
I think there's some confusion above... Speaking purely in logic (which is what De Morgan's law is), `!(x AND y)` is the same as `!x OR !y`... You can calculate the results for all possible values (truth table), and see that they come out the same in both cases:

| x | y | !(x AND y) | !x OR !y
| - | - | ---------- | --------
| F | F | T          | T
| T | F | T          | T
| F | T | T          | T
| T | T | F          | F

If you're still convinced you're getting raw data because of EF's logic transformation, can you please provide a precise LINQ query, the precise SQL query the EF generates, the data and the results?

**Comment by Tasteful** [comment]
It seams that `!(...)` is working with correct result, but not combining multiple `!xx && !yy`. See "Query 1" and "Query 2" is that also because of the De Morgan's law?

```cs
            if (_db.TableA.Count() == 0)
            {
                _db.TableA.Add(new TableA { Name = "Adam", Type = "Person" });
                _db.TableA.Add(new TableA { Name = "Ben", Type = "Person" });
                _db.TableA.Add(new TableA { Name = "Fabrikam", Type = "Company" });
                _db.SaveChanges();
            }

            {
                var result = _db.TableA.ToList(); // Returns all results
                PrintResult("Query 0", result);
                /*
warn: BugTest.TestRunner[0]
      Query 0 created the following result
      { Name: "Adam", Type: "Person" }
      { Name: "Ben", Type: "Person" }
      { Name: "Fabrikam", Type: "Company" }

                 */
            }
            {
                var result = _db.TableA.Where(x => x.Name != "Adam" && x.Type != "Person").ToList(); // Wrong result, expecting to get Ben included in the result
                PrintResult("Query 1", result);
                /*
warn: BugTest.TestRunner[0]
      Query 1 created the following result
      { Name: "Fabrikam", Type: "Company" }


dbug: Microsoft.EntityFrameworkCore.Query[10111]
      Compiling query expression:
      'DbSet<TableA>()
          .Where(x => x.Name != "Adam" && x.Type != "Person")'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<TableA>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: TableA.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: TableA.Name (string), 1], [Property: TableA.Type (string), 2], }
              SELECT t.Id, t.Name, t.Type
              FROM TableA AS t
              WHERE (t.Name != N'Adam') && (t.Type != N'Person')),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, TableA>,
          BugTest.Db,
          False,
          False
      )'
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Name], [t].[Type]
      FROM [TableA] AS [t]
      WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) AND (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
                 */
            }
            {
                var result = _db.TableA.Where(x => !(x.Name == "Adam") && !(x.Type == "Person")).ToList(); // Wrong result, expecting to get Ben included in the result
                PrintResult("Query 2", result);
                /*
warn: BugTest.TestRunner[0]
      Query 2 created the following result
      { Name: "Fabrikam", Type: "Company" }


dbug: Microsoft.EntityFrameworkCore.Query[10111]
      Compiling query expression:
      'DbSet<TableA>()
          .Where(x => !(x.Name == "Adam") && !(x.Type == "Person"))'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<TableA>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: TableA.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: TableA.Name (string), 1], [Property: TableA.Type (string), 2], }
              SELECT t.Id, t.Name, t.Type
              FROM TableA AS t
              WHERE Not(t.Name == N'Adam') && Not(t.Type == N'Person')),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, TableA>,
          BugTest.Db,
          False,
          False
      )'
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Name], [t].[Type]
      FROM [TableA] AS [t]
      WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) AND (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
                */
            }
            {
                var result = _db.TableA.Where(x => !(x.Name == "Adam" && x.Type == "Person")).ToList(); // Correct result
                PrintResult("Query 3", result);
                /*
warn: BugTest.TestRunner[0]
      Query 3 created the following result
      { Name: "Ben", Type: "Person" }
      { Name: "Fabrikam", Type: "Company" }


dbug: Microsoft.EntityFrameworkCore.Query[10111]
      Compiling query expression:
      'DbSet<TableA>()
          .Where(x => !(x.Name == "Adam" && x.Type == "Person"))'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<TableA>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: TableA.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: TableA.Name (string), 1], [Property: TableA.Type (string), 2], }
              SELECT t.Id, t.Name, t.Type
              FROM TableA AS t
              WHERE Not((t.Name == N'Adam') && (t.Type == N'Person'))),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, TableA>,
          BugTest.Db,
          False,
          False
      )'
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Name], [t].[Type]
      FROM [TableA] AS [t]
      WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) OR (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
                 */
            }
            {
                var result = _db.TableA.Where(x => !(x.Name == "Adam" || x.Type == "Person")).ToList(); // Correct result
                PrintResult("Query 4", result);
                /*
warn: BugTest.TestRunner[0]
      Query 4 created the following result
      { Name: "Fabrikam", Type: "Company" }


dbug: Microsoft.EntityFrameworkCore.Query[10111]
      Compiling query expression:
      'DbSet<TableA>()
          .Where(x => !(x.Name == "Adam" || x.Type == "Person"))'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      Generated query execution expression:
      'queryContext => new SingleQueryingEnumerable<TableA>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache.SelectExpression(
              Projection Mapping:
                  EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: TableA.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: TableA.Name (string), 1], [Property: TableA.Type (string), 2], }
              SELECT t.Id, t.Name, t.Type
              FROM TableA AS t
              WHERE Not((t.Name == N'Adam') || (t.Type == N'Person'))),
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, TableA>,
          BugTest.Db,
          False,
          False
      )'
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Name], [t].[Type]
      FROM [TableA] AS [t]
      WHERE (([t].[Name] <> N'Adam') OR [t].[Name] IS NULL) AND (([t].[Type] <> N'Person') OR [t].[Type] IS NULL)
                 */
            }
```

**Comment by smitpatel** [comment]
```
var result = _db.TableA.Where(x => x.Name != "Adam" && x.Type != "Person").ToList(); // Wrong result, expecting to get Ben included in the result
   ```
This is fundamentally wrong assumption. 
The filter explicitly specify that filter out all the rows where Name is "Adam" which removes row1
**AND**
filter out all the rows where Type is "Person" which removes row1 and row2

So only row3 in result is correct. 2nd query is the same way.

So where are the wrong results?

**Comment by Tasteful** [comment]
> This is fundamentally wrong assumption.

> So where are the wrong results?

I have test now with Linq over a regular `List<>` and directly with TSQL and can see that my assumption was wrong about how `&&` is working. Have never recognize that before and probably that is because I try to write queries that not using `NOT`. Then the result will be what I expect anyway.

Thanks for clarifying.

**Comment by maumar** [comment]
@Tasteful on top of what @roji  and @smitpatel have already said, you can use Linq to Objects, completely circumventing EF query pipeline and see that it produces the same result:

```cs
_db.TableA.ToList().Where(x => !(x.Name == "Adam" && x.Type == "Person")).ToList();
```

--------------------------

Perhaps, your example can be demonstrated easier if you have 4 elements in your database:

```
1.) Name: Adam, Type: Person
2.) Name: Ben, Type: Person
3.) Name: Fabrikam, Type: Company
4.) Name: Adam, Type: Company // <-- added element
```

The query which is not negated:
```cs
Expression<Func<TableA, bool>> w = x => x.Name == "Adam" && x.Type == "Person";
```

will return true if entity is *simultaneously* named Adam and is a person (so returning the first element only).
Negation of that MUST return everything else, so it should return elements 2, 3, 4.

This can be done by returning elements whos name is not adam *OR* who's type is not person - which is what EF translates the negation to.


They way that you thought the negation should be translated (if I understood correctly), it should only return 3rd element (something that is not named Adam, and is also not a Person). This leads to contradiction, because all 4 elements should be returned if you combine the first query and its negated version, but you only get 2 of them.

If you want to go around de Morgan laws, you need to write the query without parentheses in the way that you want them to behave, rather than putting negation around and rely on EF to optimize it for you. 

From EF perspective this issue is by design - we follow all the rules of 2-value logic correctly here.
