### ISSUE TITLE
Migration command missing services for console apps without Startup class

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2466]
Simple DNX console apps work with EF but migrations doesn't work without a Startup class. (Use https://gist.github.com/natemcmaster/90e2388c0ee1d29f440a to repro).

EF will bootstrap services correctly when `dnx . run` executes Program, but `dnx . ef migration add Initial` throws and error because no "Startup" class is present to configure services. Context discover still works fine.

```
$ dnx . ef migration add Initial
Using context 'MyContext'.
System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'ef-xplat'.
```

_Workaround_

Add an empty class to the project. Just adding the sample class below is enough to make migrations happy, even though startup does not actually configure services.

``` c#
public class Startup
{
    public void Configure(){}
}
```

**Comment by divega** [comment]
I believe it is related to #2357.

**Comment by natemcmaster** [comment]
Yes, this is a dup.
