### ISSUE TITLE
Is there an easy way to create relationships between two new entities?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#24674]
I have this model:

```c#
TableA
{
    IDTable;
}

RelationsTableA
{
    IDTableA;
    IDRelatedTableA;
}
```

Then I have two entities:

```c#
class TableA
{
    long IDTableA;

    virtual ICollection<RelationsTableA> RelationsTableAIDFacturaNavigation;
    virtual ICollection<RelationsTableA> RelationsTableAIDFacturaRelacionadaNavigation;
}

class RelationsTableA
{
    long IDTableA;
    long IDRelatedTableA;

    TablA IDTableANavigation;
    tableA IDRelatedTableANavigation;
}
```

Sometimes in the same process I need to create two tables and relate them, and I want two relationships, when TableA1 is main table and TableA2 is related table and also the contrary, when TableA2 is the main and the TableA1 is the related. So I do this:

```c#
TableA myTableA = new TableA();
TableA myRelatedTableA = new TableA();

RelationsTableA myRelation1 = new RelationsTableA();
myRelation1.IDTableANavigation = myTableA1;
miRRelation1.IDRelatedTableNavigation = myTableA2;

myTableA1.RelationsTableAIDFacturaNavigation.Add(myRelation1);


RelationsTableA myRelation2 = new RelationsTableA();
myRelation2.IDTableANavigation = myTableA2;
miRRelation2.IDRelatedTableNavigation = myTableA1;

myTableA2.RelationsTableAIDFacturaNavigation.Add(myRelation2);
```

Then problem is that EF Net5 detects that there are 2 relations with the same key, 0, because both entities are new. But it doesn't take in account that the entities in the navigation properties are diferent.

I know that EF doens't ensure the order of the operations, so it iseems it tries to add the RelationsTableA before add the TableA entities, so they still have 0 as ID.

So I don't if there is some easy to solve this problem, perhaps some option in EF that I don't know.

Thanks.

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ComptonAlvaro** [comment]
I am trying to reproduce the problem with a simple example and it works, so it leads me to think that the problem it is mine.

If i could determinate the problem and finally it could be about EF, I will tell, but I now i am thinking that it is because in my real application the case is a bit more complex.

Perhaps it would be better to close this issue and if it is needed, I could open a new one with an example.
