### ISSUE TITLE
Multiple DB Context and join across them

### ISSUE THREAD

**Issue by oNoobMastero** [dotnet/efcore#24681]
## Is there a way to join between 2 tables ( from 2 different schema ) from 2 different DbContexts ( same connection string ) with 1 query ?

```C#
[Table(Schema = "Schema1")]
public class TableA 
{
  [Key]
  public int Id { get; set; }

  public string Name { get; set; }
}

[Table(Schema = "Schema2")]
public class TableB
{
  [Key]
  public int Id { get; set; }

  public string Name { get; set; }

  public int? tableAId { get; set; }
  [ForeignKey("tableAId ")]
  public TableA tableA { get; set; }
}

public class DbContextA : DbContext
{
    public DbContextA (DbContextOptions<DbContextA> options) : base(options) { }
    DbSet<TableA> TableAs { get; set; }
}

public class DbContextB : DbContext
{
    public DbContextB  (DbContextOptions<DbContextB> options) : base(options) { }
    DbSet<TableB> TableBs { get; set; }
}


var result = from a in _dbContextA.TableAs
                   join b in _dbContextB.TableBs on b.tableAId  equals a.Id
                   select new { 
                        a.Name,
                        b.Name
                  };
```

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10 
IDE: (e.g. Visual Studio 2019 16.9.3)

**Comment by roji** [comment]
@oNoobMastero you can perform the join client-side by introducing a ToEnumerable on the two DbSets; EF Core will only translate your query to SQL up to the ToEnumerable, and the rest will be done with LINQ to Objects.

**Comment by oNoobMastero** [comment]
@roji  but `AsEnumerable()` will download all the data from each table then will do the join .
 i want that operation be on server side, because we have filter on the query and paging like fetch only 10 records, but `AsEnumerable()` will fetch all records then performs filter and paging.

**Comment by roji** [comment]
@oNoobMastero if you have two DbContexts, that means that you have two different database connections, to possibly two different connections - it simply isn't possible to perform the join on the server in that situation. A query is something that is sent to a database over a single connection, and cannot join with another query running via another connection...

However, if you can apply filtering and paging on on each DbContext (i.e. before the AsEnumerable), those would be evaluated server-side, and then only the relevant data would be fetched to the client and joined there.

**Comment by oNoobMastero** [comment]
@roji ok thanks for the explanation
