### ISSUE TITLE
Add access to generated raw SQL for modifying

### ISSUE THREAD

**Issue by lansman** [dotnet/efcore#24680]
EF Core 5.0.5
Npgsql 5.0.4
Postgres 13

We have trigger on all DB tables
```
CREATE TRIGGER history_iud_trigger
BEFORE update or insert or delete
ON public.TABLE_NAME
FOR EACH ROW
EXECUTE PROCEDURE history_iud_func();

```

Trigger function
```sql
CREATE OR REPLACE FUNCTION public.history_iud_func()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare user_name varchar;  
begin

-- get user name from temp variable
user_name = current_setting('session.user_name', true);

-- save added/modified/deleted columns data to audit tables with user

end;
$function$
;
```

Function requeres user_name to be passed from API.

EF Core 5 introduces SaveChanges Interceptors, but i dont see access to generated SQL.
I want to append my custom SQL to any INSERT/UPDATE/DELETE query generated by EF;

Eg turn
`INSERT ...`
to
`SET session.curr_user = 'user123'; INSERT ...`

**Comment by lansman** [comment]
I've tried database interception, but it seems it can only intercept SELECT queries, not INSERT/UPDATE/DELETE

**Comment by lansman** [comment]
I've tried database interception, introduced in netcore 3, but it seems it can only intercept SELECT queries, not INSERT/UPDATE/DELETE

**Comment by ajcvickers** [comment]
@lansman It intercepts all database commands, including those from SaveChanges. If you're not seeing this, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
