### ISSUE TITLE
Warning NU1608: Detected package version outside of dependency constraint: Pomelo.EntityFrameworkCore.MySql 3.2.4 requires Microsoft.EntityFrameworkCore.Relational (>= 3.1.8 && < 5.0.0) but version Microsoft.EntityFrameworkCore.Relational 5.0.5 was resolved. (NU1608)

### ISSUE THREAD

**Issue by devmuaz** [dotnet/efcore#24691]
## Packages version conflicts
Trying to use/install those packages 
- Pomelo.EntityFrameworkCore.MySql (3.2.4)
- Microsoft.EntityFrameworkCore.Relational (5.0.5)

## Warring Message
I get this warring when the installation completed, says there's a version conflicts between the two:
```
Warning NU1608: Detected package version outside of 
dependency constraint: Pomelo.EntityFrameworkCore.MySql 3.2.4 requires 
Microsoft.EntityFrameworkCore.Relational (>= 3.1.8 && < 5.0.0) but version 
Microsoft.EntityFrameworkCore.Relational 5.0.5 was resolved. (NU1608)
```

and I can't use different version of `Microsoft.EntityFrameworkCore.Relational` because others depends on the latest of it.

Any solutions?

**Comment by roji** [comment]
@devmuaz mixing package versions across major versions is not supported. You have to use the same versions for all EFCore-related packages (including providers), except for the patch versions. Try using Pomelo 5.0.0-alpha.2.

**Comment by devmuaz** [comment]
@roji So what should I do in this case?

**Comment by roji** [comment]
Try using Pomelo 5.0.0-alpha.2?

**Comment by devmuaz** [comment]
@roji GREAT!! I'll try it out, Thank you.
