### ISSUE TITLE
How to use EF7 from VSCode in Mac?

### ISSUE THREAD

**Issue by tinganho** [dotnet/efcore#2471]
I'm new to C# and I'm trying to connect to a DB preferably PostgresSQL(or do I must use MS SQL?). How do I do that in VSCode and Mac(using dnu CLI)?

I have looked at your wiki page. It didn't helped me that much.

**Comment by natemcmaster** [comment]
We are working on writing a guide into our documentation. As we are still in the pre-release phase, we haven't finished this. When the guide is ready, it will be published to our docs.  You can watch for it here:  http://ef.readthedocs.org/en/latest/getting-started/index.html.

Also, you may get a better answer if you try asking on StackOverflow. Feel free to post the question there and add a link to your question here on this issue.

**Comment by tinganho** [comment]
@natemcmaster I just posted it here: https://stackoverflow.com/questions/31062895/how-to-use-ef7-from-vscode-in-mac

**Comment by tinganho** [comment]
@natemcmaster could you answer another problem I had? http://stackoverflow.com/questions/31064306/npsql-entityframework7-cannot-use-npgsql-server

**Comment by natemcmaster** [comment]
Sorry, you are better off addressing this issue to the npgsql repository. https://github.com/npgsql/npgsql
