### ISSUE TITLE
6.0 API Reviews

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#24743]
## February 19
<details><summary>Done</summary>

- [x] Investigate removing `IModelCreationDependencies`
- [x] Rename `SingletonModelDependencies` to `RuntimeModelDependecies`
- [x] Consider renaming `IConventionModel.GetEntityTypes(Type type);` to `FindEntityTypes`
- [x] Rename `IConventionModel.FindPrincipals` to `GetPrincipals`
- [x] @AndriySvyryd Add `RelationalEntityTypeExtensions.FindRowInternalForeignKeys` `IEntityType` overload, and more generally have three overloads for each of these.
- [x] @AndriySvyryd `RelationalPropertyExtensions.FindOverrides` may not need a mutable overload

</details>

## March 4
<details><summary>Done</summary>

- [x] Change `Annotatable.IsReadonly` to `ReadOnly`
- [x] Change `EnsureReadonly` to `EnsureMutable`
- [x] @ajcvickers Review template methods on `RelationalConnection` and remove `DbConnectionState`

</details>

## March 24
<details><summary>Done</summary>

- [x] Rename `DisableConcurrencyDetection` to `EnableThreadSafetyChecks`
- [x] @bricelam Check that dropping `ITableMigrationOperation` from `DropIndexOperation`  is expected.
- [x] Rename `IRelationalCommand.PopulateFromTemplate` to `PopulateFrom`
- [x] Rename parameter of above from `templateCommand` to `command`

</details>

## April 21
<details><summary>Done</summary>

- [x] Move `DbContext.DesignTimeModel` to `GetService<IDesignTimeModel>()` or similar
- [x] @AndriySvyryd Consider making `ForeignKey.ReferencingSkipNavigations` return an `ISet`
- [x] @AndriySvyryd Consider if `SlimModel.RelationalModel` can be made an explicit interface implementation and will still show up in the debugger. Also consider for DebugView.

</details>

## June 16
<details><summary>Done</summary>

- [x] @AndriySvyryd Make CSharpRuntimeAnnotationCodeGenerator and friends internal so we can add language-agnostic APIs later (#25110), try to move `ICSharpHelper` back to .Design
- [x] @AndriySvyryd Make UpdateEntryEventData derive from DbContextEventData
- [x] @AndriySvyryd  Move more classes under the Microsoft.EntityFrameworkCore.Design namespace in Relational into the core assembly
- [x] @AndriySvyryd  Make RelationalCSharpRuntimeAnnotationCodeGenerator pubternal
- [x] @ajcvickers Why did ContextParamaterBinding change to an array of IPropertyBase?
  - Should it have params?
- [x] @ajcvickers Review IRelationalCommandDiagnosticsLogger
- [x] @smitpatel Remove IClonable from FromSqlExpression and TableExpression. Pattern match or introduce a new interface.
  - Clone should return something more specific than `object`
- [x] @smitpatel Mitigate future breaks to SelectExpression. Mark more members as pubternal.

</details>

## August 2

<details><summary>Done</summary>

- [x] @roji Why is CoreOptionsExtension.DefaultLoggingCacheTime public? #25422
- [x] @AndriySvyryd Rename IMutableModificationCommandFactory to just *IModificationCommandFactory*
- [x] @AndriySvyryd Make ColumnModificationParameters and ModificationCommandParameters structs and use `in`
- [x] @andriySvyryd Rename IModificationCommand to *IReadOnlyModificationCommand*
  - Rename IMutableModificationCommand to *IModificationCommand*
- [x] @ajcvickers Move commandSource constructor parameters to the end in *EventData classes and IRelationalCommandDiagnosticsLogger
- [x] @ajcvickers Address confusion beween AddSqlite and AddEntityFrameworkSqlite
- [x] @maumar Make IQueryRootCreator a generic extensitiliby helper for nav expansion
- [x] @maumar Can we mitigate timezone issues on TemporalAll/AsOf/etc methods?
- [x] @maumar Rename *With* to *Use* in new methods on SqlServerEntityTypeBuilderExtensions
- [x] @maumar Remove *Temporal* from new methods in SqlServerEntityTypeExtensions
  - Keep it in the underlying annotation names
- [x] @maumar Add Core and Relational dependency objects to SqlServerTemporalConvention
- [x] @bricelam Move MigrationsBundle to the Migrations namespace
  - Rename parameter to *contextTypeName*
- [x] @bricelam Host API Review of CLI and PMC commands

</details>

## August 18

- [x] @bricelam Rename --bundle-runtime to --target-runtime
  - Rename -Runtime to -TargetRuntime in PMC
- [x] @bricelam Remove --bundle-configuration
  - Make --configuration flow when Debug or Release #25906
- [x] @bricelam Rename default bundle name to *efbundle*
- [x] @AndriySvyryd Rename Scalars to DefaultTypeMapping
  - Singularize methods in ScalarConfigurationBuilder and ScalarConfigurationBuilderExtensions
- [x] @ajcvickers ~~Remove CosmosDbContextOptionsBuilder.HttpClientFactory and enable ReplaceService instead.~~ Looked at this and talked to Andriy. It's quite complicated and somewhat ugly to do a service, so leaving as is.
- [x] @smitpatel Can we remove the override of TranslateSubquery in RelationalQueryableMethodTranslatingExpressionVisitor?
- [x] @ajcvickers Revert ProviderCodeGenerator.RelationalDependencies to just Dependencies

**Comment by bricelam** [comment]
> Check that dropping ITableMigrationOperation from DropIndexOperation is expected.

Yes, the table doesn't need to be specified when dropping an index on some providers. This one case of nullability crippled the usability of the interface, so I removed the interface from this type and strengthened its semantics to include a non-nullable table name.

The interface was added for table rebuids. That code was unaffected by this change since DropIndex operations were handled separately.
