### ISSUE TITLE
[Style] RelationalStrings.resx, Inconsistent format/structure of messages about conflicting values

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#24749]
## File a bug

https://github.com/dotnet/efcore/blob/487ad93ea8d7854ee5f37ab2d34c369b5faf7a1a/src/EFCore.Relational/Properties/RelationalStrings.resx#L160-L162

**have different property values '{firstConflictingValue}' and '{secondConflictingValue}'**

(values with quotes)

and

https://github.com/dotnet/efcore/blob/487ad93ea8d7854ee5f37ab2d34c369b5faf7a1a/src/EFCore.Relational/Properties/RelationalStrings.resx#L148-L150

**have different original property values {firstConflictingValues} and {secondConflictingValues}**

(values without quiotes)

BuildCurrentValuesString and BuildOriginalValuesString (which was used for build a string with values) look identicaly:

https://github.com/dotnet/efcore/blob/487ad93ea8d7854ee5f37ab2d34c369b5faf7a1a/src/EFCore/Update/UpdateEntryExtensions.cs#L239-L287

---
https://github.com/dotnet/efcore/blob/487ad93ea8d7854ee5f37ab2d34c369b5faf7a1a/src/EFCore.Relational/Properties/RelationalStrings.resx#L157-L159

**Instances of entity types '{firstEntityType}' and '{secondEntityType}' are mapped**

and

https://github.com/dotnet/efcore/blob/487ad93ea8d7854ee5f37ab2d34c369b5faf7a1a/src/EFCore.Relational/Properties/RelationalStrings.resx#L145-L147

**An instance of entity type '{firstEntityType}' and an instance of entity type '{secondEntityType}' are mapped**

Different structure of text....

---
These are not errors and absolutely not critical, but maybe it is better to use one format/structure in these messages? :)

**Comment by smitpatel** [comment]
specific values coming from the code generating the string are quoted using single quote. Single quotes are in resx file when the argument represent 1 value so it is quoted in the resx file. When passing a argument which contains multiple values then it is not single quoted here and caller is responsible for putting single quote around each value and converting it to string.
