### ISSUE TITLE
2.2 -> 5.0.5 (.Net Core 3.1) strange subquery in simple select with Include

### ISSUE THREAD

**Issue by freerider7777** [dotnet/efcore#24745]
I've first posted to npgsql (https://github.com/npgsql/efcore.pg/issues/1808), but it works the same with sqlite

`var deliveryChannel = dbContext.DeliveryChannel.AsNoTrackingWithIdentityResolution().Include(c => c.ClientData).ThenInclude(c => c.DeliveryChannel).Where(c => (c.State == State.Active && c.ExtendedData == "someData") ).OrderByDescending(d => d.Id).FirstOrDefaultAsync().Result;`

ClientData has a collection of DeliveryChannels. I'm selecting all DeliveryChannels from the Client of some exact DeliveryChannel (why not? :) ).

and it produces strange subquery in first select of split query (in EF 2.2 there is no subquery):

![image](https://user-images.githubusercontent.com/6572573/115918525-4a0bf980-a480-11eb-8982-d3a949ba1bbc.png)

```
public class ClientData
{
...
 public virtual ICollection<DeliveryChannel> DeliveryChannel { get; set; }
}

public class DeliveryChannel{
...
      public int ClientDataId { get; set; }
      public ClientData ClientData { get; set; }
}

options.UseSqlite("Data Source=sqlitedemo.db", p => p.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery));
```

**Comment by smitpatel** [comment]
EF Core doesn't do split query unless you use `AsSplitQuery` operator. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#eager-loading-single-query
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#split-queries

**Comment by freerider7777** [comment]
@smitpatel You can set it globally (as I did) https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#enabling-split-queries-globally
But the question is about examining the produced query

**Comment by smitpatel** [comment]
If the query is actually run to generate the results then split queries are fired as needed. If there are no parents then the split query for dependent is not actually run. So whichever way you are seeing SQL on execution, it will show whatever was run.
If you are using `ToQueryString` API which doesn't actually run the query against database then we only show the first query. See #22080

**Comment by freerider7777** [comment]
@smitpatel Do you know sql? :) Have a look at the underlined lines and you will see that inner select is with limit 1, so it is not needed to do subquery and order by in outer query. In 2.2 it was a simple select without subquery. It'a pity EF is not consistent and every new version brings some hidden surprises...

**Comment by smitpatel** [comment]
First share your whole query because the screenshot doesn't contain whole SQL query. EF Core doesn't create a subquery following a random number generator. In 2.2 it could have been simple select without subquery because rest of the query was client evaluated.

**Comment by freerider7777** [comment]
The full query is on the picture (just some fields on the right), on mobile now, I'll send it as text later

**Comment by freerider7777** [comment]
Here are the full queries  5.0.5 and 2.2 (the only difference is AsNoTrackingWithIdentityResolution in 5.0.5 vs AsNoTracking in 2.2)
[ef505vs22.txt](https://github.com/dotnet/efcore/files/6370350/ef505vs22.txt)

**Comment by freerider7777** [comment]
Any more information needed?

**Comment by freerider7777** [comment]
Cool, thanks! Will it get to 5.X.X ?

**Comment by smitpatel** [comment]
It requires some big changes happened in 6.0 so sadly the earlier release will be 6.0-preview5
