### ISSUE TITLE
[Suggestion] Support non-value arguments in FromSqlInterpolated

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/efcore#24756]
Hello there,
sometimes I need to customize my SQL query according to user input, e.g. by using different column names or SQL keywords, such as `ASC` and `DESC`.

Here's a simplified example: the ordering direction is decided by the user.
```
// User inputs - these come in from the querystring, I sanitized them before use
decimal price = 10.0m;
string direction = "ASC";

// Get results
List<Course> courses = await dbContext.Courses.FromSqlInterpolated(
             $"SELECT * FROM Courses WHERE Price>={price} ORDER BY Price {direction}" //here is a non-value
             ).ToListAsync();
```
As you can see, the `direction` argument is not a value. Since it's a SQL keyword, it must not become a `DbParameter`.
How can I instruct the `FromSqlInterpolated` method to format it as-is instead of making it a `DbParameter`?

If this is not supported already (docs don't seem to mention it), how about a simple type cast to discriminate between values and non-values?

```
$"SELECT * FROM Courses WHERE Price>={price} ORDER BY Price {(NotValue) direction}"
```

Thanks
Moreno

**Comment by roji** [comment]
@BrightSoul as you note above, ASC/DESC cannot be parameterized in SQL. But you can still use string interpolation in C# to create your SQL string; you just have to use FromSqlRaw instead of FromSqlInterpolated ([see the docs](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)).

However, when doing this be very careful with preventing SQL injection attacks. String interpolation (as opposed to real parameterization with DbParameter) is exactly how those happen.

**Comment by BrightSoul** [comment]
Hey @roji, thanks for your answer.
I won't use `FromSqlRaw` because it's risky and because its arguments are position-based. That makes them too error prone to use and make my code less readable than the `FromSqlInterpolated` solution, which is superior in most cases imho.

So, let me restate my question: would you consider improving the `FromSqlInterpolated` method so that it allows explicitly marked arguments to be formatted verbatim instead of being converted to DbParameters? If not, what would be the main reason?

My current/fallback strategy is to compose the SQL query with LINQ ([when possible, as noted in the docs](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#composing-with-linq)) but that often results in a long `switch` block or a series of nested `if` blocks which I'd rather avoid. I resorted to dynamic LINQ in the past but that's also something I'd do without in this case.

**Comment by roji** [comment]
Well, if we added a raw-interpolation option to FromSqlInterpolated (which is basically what this would mean), that would make it pretty much as risky as FromSqlRaw... It seems better to keep FromSqlInterpolated 100% safe. In addition, I'm not sure how something like that would technically work; it seems you want to somehow configure - on a case-by-case basis - if interpolation should lead to database parameterization (safe) or string interpolation (raw, unsafe). I'm not aware of a way to do that with C# string interpolation - am I missing something?

**Comment by ajcvickers** [comment]
We discussed this in triage and agree with @roji's assessment.

**Comment by BrightSoul** [comment]
> it seems you want to somehow configure - on a case-by-case basis - if interpolation should lead to database parameterization (safe) or string interpolation (raw, unsafe)

@roji Yes, exactly. It'd be flexible and still safer than relying on `FromSqlRaw`, since the programmer would have to knowingly and explicitly choose which (few) arguments should be **opted-out** of parametrization.

> I'm not aware of a way to do that with C# string interpolation

Indeed, it cannot be done with a language construct, unfortunately but it could be implemented [around here in the QuerySqlGenerator](https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L355) as follows: 
- If the argument is some ad-hoc container type, then interpolate its contained value;
- Parametrize in all other cases.

Now that I give a better look at the code, It seems to me that this "ad-hoc container type" I mentioned already exist. It could be the [SqlConstantExpression](https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Query/SqlExpressions/SqlConstantExpression.cs). In fact, it gets special treatment in the `QuerySqlGenerator` here.
[https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L384-L392](https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L384-L392)

If I can read this correctly, a Sql literal is printed instead of a new parameter being added, i.e. the behavior I was after. I tried experimenting with it but without success so far.

> We discussed this in triage and agree

Ok @ajcvickers, thanks anyways, I appreciate your opinions. Discussing it was useful.
Moreno
