### ISSUE TITLE
Filtering fields with type JsonElement

### ISSUE THREAD

**Issue by huseyingoztok** [dotnet/efcore#24757]
```
{
    "Age": 25,
    "Name": "Joe",
    "Orders": [
        { "OrderPrice": 9, "ShippingAddress": "Some address 1", "IsActive": true },
        { "OrderPrice": 23, "ShippingAddress": "Some address 2", "IsActive": false },
        { "OrderPrice": 24, "ShippingAddress": "Some address 3", "IsActive": true }
    ]
}
```

How to filter such Json data in the database?

For Example: Get IsActive true orders

**Comment by roji** [comment]
Probable duplicate of #4021.

@huseyingoztok I'm assuming you're trying to map an EF property to a JSON document in the database, and then express a query filtering on one of the JSON fields in that document - can you confirm? If that's the case, then unless you're using the PostgreSQL provider, this isn't currently possible without dropping down to raw SQL.

**Comment by huseyingoztok** [comment]
var isActive = "[{\"IsActive\": true}]";
query = query.Where(x => EF.Functions.JsonContains(x.Orders, isActive));

Thanks for your reply @roji. I solved my problem as above. I am closing issue.
