### ISSUE TITLE
Data lost when unit testing with in-memory database, but works fine on the real database

### ISSUE THREAD

**Issue by MrYossu** [dotnet/efcore#24763]
I have some code that saves a `Term` (as in an investor, who invests in property for a fixed term). Each term has an associated collection of shares, one for each property...

```c#
public class Term {
    public Term() => Shares = new();

    public int Id { get; set; }
    public string InvestorId { get; set; }
    // Other properties removed for clarity
    public List<Share> Shares { get; set; }
}

public class Share {
    public int Id { get; set; }
    public int TermId { get; set; }
    public Term Term { get; set; }
    public int PropertyId { get; set; }
    public Property Property { get; set; }
    public int Quantity { get; set; }
}
```

My view model has an `_investor` property. When a term is updated, say if the investor changes the number of shares they have, the change is made, and then saved. After that, a method is called that calculates the balance brought forward from the previous term (ie, how much they over/underpaid)...

```c#
private async Task SetBalanceBroughtForward() {
    Term previousTerm = _investor.Terms.OrderByDescending(t => t.Start).Skip(1).First();
    Term latestTerm = _investor.Terms.OrderByDescending(t => t.Start).First();
    latestTerm.BalanceBroughtForward = CalculateBbf(previousTerm);
    _appDbContext.Terms.Update(latestTerm);
    await _appDbContext.SaveChangesAsync();
}
```

This code works fine when running locally (ie from Visual Studio sing a web browser), but fails unit testing. I have a test that tests the scenario when the investor has an extra share added to the term.

My `InitialiseData` method sets up the in-memory database...

```c#
      ServiceProvider serviceProvider = new ServiceCollection()
        .AddEntityFrameworkInMemoryDatabase()
        .BuildServiceProvider();
      DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
        .UseInMemoryDatabase("Achim", new InMemoryDatabaseRoot())
        .UseInternalServiceProvider(serviceProvider)
        .Options;
      AppDbContext appDbContext = new(options);
```

Here is the test code...

```c#
[TestMethod]
public async Task TestMethodNameShortenedForClarity() {
    // GetInvestorDetailsViewModel sets up the test view model,
    // passing in the in-memory db context (see above) and other dependencies
    InvestorDetailsViewModel investorDetailsVm = GetInvestorDetailsViewModel();
    // Tell the VM to get the investor from the database and set various VM properties
    // The investor used in this test has 6 shares in one property in the current term
    await investorDetailsVm.SetInvestor(_investorId);
    // Get a VM for the renewal window
    RenewalViewModel newRenewalVm = await investorDetailsVm.NewRenewalViewModel();
    // Add 7 shares for a second property to the current term
    Share addedShare = new() { PropertyId = _property2.Id, Quantity = 7 };
    newRenewalVm.Shares.Add(addedShare);
    // Call the VM method to do the renewal. This calls the code shown earlier
    await investorDetailsVm.OnSubmitRenew(newRenewalVm);
    // Get the modified investor from the database
    Investor modifiedInvestor = await _appDbContext.Investors
    .SingleAsync(i => i.Id.ToString() == _investorId);
    // Test the changes. All removed for clarity except the failing one
    Assert.AreEqual(2, latestTerm.Shares.Count);
}
```

If I use tracepoints to check the number of shares in the latest term, I can see that just before the call to `
SaveChangesAsync`, it has two shares as expected, but straight after that call, the newly-added share has disappeared.

The `_investor` has been reloaded from the database after the share was added (in the renewal code), before `SetBalanceBroughtForward` was called, and the new share was there.

Just as a check, I tried changing the code in `SetBalanceBroughtForward` to get the latest term from the database...

```c#
Term latestTerm = await _appDbContext.Terms.Where(t => t.InvestorId==_investor.Id)
    .OrderByDescending(t => t.Start).FirstAsync();
```

...but it didn't make any difference. `latestTerm` had two shares before calling `SaveChangesAsync` but only one afterwards.

Anyone any idea why this newly-added share gets removed? Thanks.

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.9.3

**Comment by ajcvickers** [comment]
I don't see anything obviously wrong in the snippets you posted, but it's hard to tell without knowing how the snippets are used together. Please attach a small, _runnable_ project or post a small, _runnable_ code listing that reproduces what you are seeing so that we can investigate.

**Comment by MrYossu** [comment]
@ajcvickers I guessed that would be the case. Trouble is, I don't know if I can isolate/reproduce it all. I'll give it a go and see if I can.

Thanks for the reply.

**Comment by MrYossu** [comment]
@ajcvickers Turned out to be easier than I expected.

Please see [this github repo](https://github.com/MrYossu/EfCoreMemoryUnitTestIssue), where I created a sample project that shows the issue.

If you debug the one test, you'll see it fail, and you'll see the output from some calls to `Debug.WriteLine` I added in. You can see that in the `InvestorDetailsViewModel.SetBalanceBroughtForward` method, the term has 2 shares before saving to the database, but only 1 afterwards.

As I said, the same code works fine when run against a real database. However, the fact that it loses the share here means that some unit tests fail.

If you have any idea what I did wrong, or if this is indeed a bug, I would be very grateful.

Thanks.

**Comment by ajcvickers** [comment]
@MrYossu Looking at the debug logs, it seems the `Share.Avreich` is set to null, which results in the required dependent being deleted:

```
dbug: 4/27/2021 10:24:36.790 CoreEventId.ReferenceChangeDetected[10805] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      The navigation 'Share.Avreich' for entity with key '{Id: 2123}' was detected as changed.
dbug: 4/27/2021 10:24:36.791 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      The 'Share' entity with key '{Id: 2123}' tracked by 'AppDbContext' changed state from 'Unchanged' to 'Modified'.
dbug: 4/27/2021 10:24:36.796 CoreEventId.CascadeDeleteOrphan[10003] (Microsoft.EntityFrameworkCore.Update) 
      An entity of type 'Share' with key '{Id: 2123}' changed to 'Deleted' state due to severed required relationship to its parent entity of type 'Avreich'.
dbug: 4/27/2021 10:24:36.797 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      The 'Share' entity with key '{Id: 2123}' tracked by 'AppDbContext' changed state from 'Modified' to 'Deleted'.
dbug: 4/27/2021 10:24:36.801 CoreEventId.DetectChangesCompleted[10801] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      DetectChanges completed for 'AppDbContext'.
info: 4/27/2021 10:24:36.803 InMemoryEventId.ChangesSaved[30100] (Microsoft.EntityFrameworkCore.Update) 
      Saved 2 entities to in-memory store.
dbug: 4/27/2021 10:24:36.804 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      The 'Term' entity with key '{Id: 231}' tracked by 'AppDbContext' changed state from 'Modified' to 'Unchanged'.
dbug: 4/27/2021 10:24:36.806 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      The 'Share' entity with key '{Id: 2123}' tracked by 'AppDbContext' changed state from 'Deleted' to 'Detached'.
dbug: 4/27/2021 10:24:36.807 CoreEventId.SaveChangesCompleted[10005] (Microsoft.EntityFrameworkCore.Update) 
      SaveChanges completed for 'AppDbContext' with 2 entities written to the database.
VM.SetBalanceBroughtForward - Shares in investor after saving: 1
VM.RenewTerm - Shares in new VM after saving: 1
```

I suspect that one of the main issues here is that you create a single context instance for both setting up (seeding) your context and executing the test. This means that the context instance is already tracking all your seed data when the test runs. This isn't usually how the context is used in a real application.

**Comment by MrYossu** [comment]
@ajcvickers Thanks for the reply.

How should I set it up for testing? When working against a real database, the dbcontext always gets the right data, as there is only one database, and any dbcontext created uses that. However when testing, I'm using an in-memory context, and need to set that up with seed data. If I don't reuse the same context, how can I get at the data that was modified by the code under test in the first one?

Hope that makes sense. Thanks again.

**Comment by MrYossu** [comment]
@ajcvickers Sorry, forgot to mention that I set `Share.Avreich` to null, as it is an existing entity, and if I don't set it to null, EF tries to add a new one with the same Id and throws an exception. In the real code, leaving the AvreichId set to a non-null value (which it has to be) is enough to ensure the link is preserved. Why doesn't the in-memory database do the same?

Thanks

**Comment by ajcvickers** [comment]
@MrYossu See [Testing code that uses EF Core](https://docs.microsoft.com/en-us/ef/core/testing/)

**Comment by MrYossu** [comment]
@ajcvickers Thanks for that, very enlightening.

So am I right in thinking that as long as I hold on to the same `ContextOptions` object, I can new up as many instances of `DbContext` as I like, and it will always point to the same in-memory database? If so, that would require some rewriting, but should hopefully solve the problem.

Thanks again. Please can you confirm if I got the idea right.

**Comment by ajcvickers** [comment]
@MrYossu That's the general idea, yes.

**Comment by MrYossu** [comment]
@ajcvickers Thanks, I'll try changing the code and see how it goes.
