### ISSUE TITLE
EF Core 3.1 - SqlFunctions Not Fully Supported?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#24765]
I'm was trying to do a Haversine in query linq code against doubles (not Geo data) - was trying to avoid post-query filtering or relying on DBFunctions (though I know DBFunctions would solve this too).

I had code like:
```
from.....
let R = 3960

let dLat = SqlFunctions.Radians(ztll.ZtllLat - st.StLat)
let dLon = SqlFunctions.Radians(ztll.ZtllLon - st.StLon)

let a = SqlFunctions.Sin(dLat / 2) * SqlFunctions.Sin(dLat / 2) +
		SqlFunctions.Cos(SqlFunctions.Radians(st.StLat)) *
		SqlFunctions.Cos(SqlFunctions.Radians(ztll.ZtllLat)) *
		SqlFunctions.Sin(dLon / 2) * SqlFunctions.Sin(dLon / 2)
let c = 2 * SqlFunctions.Asin(SqlFunctions.SquareRoot(a))
let d = R * c
select ...
```

When the query ran, it kept throwing "This function can only be invoked from LINQ to Entities." - the stack trace was looking at "SqlFunctions.Radians".

I'm hoping this is a syntax thing - but otherwise let know what's possible here. 

Thanks!

---

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Framework 4.8

**Comment by roji** [comment]
@OpenSpacesAndPlaces unless I'm mistaken, SqlFunctions is part of Entity Framework 6 (not Core) - are you by any chance mixing EF Core and EF6? If you're looking to do math operations on SQL Server, take a look at [the function mapping page](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/functions#numeric-functions).

**Comment by OpenSpacesAndPlaces** [comment]
@roji  Definitely EF Core 3.1 via .Net Framework.
The library it is pulling from is listed as: System.Data.Objects.SqlClient.SqlFunctions
Which looks like it's a Framework reference:
https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.sqlclient.sqlfunctions?view=netframework-4.8

**Comment by ErikEJ** [comment]
That is EF6

**Comment by roji** [comment]
@OpenSpacesAndPlaces take a look at the provider docs I linked to above, they clearly list what is translated in LINQ queries and to what.
