### ISSUE TITLE
How to handle unsigned values in type mapping

### ISSUE THREAD

**Issue by rykr** [dotnet/efcore#2477]
I'm working on implementing the type mapping and our integer fields can be unsigned.  This is really no problem when mapping from a Clr type like DbType.UInt16  but what about when mapping from text (I assume EF7 will allow model creation by DB reverse engineer)

So when it is trying to come up with a mapping for   create table foo( id int unsigned )  how is that going to map?

**Comment by rykr** [comment]
As a followup to that how would I handle the crazy case we have of a 3 byte integer.  Of course this would never map from CLR type to SQL but again when reverse engineering a DB and we run into a 3 byte column (medium int) is this handled with the simpleNameMappings?

**Comment by ajcvickers** [comment]
@rykr I think maybe you are expecting EF type mapping to do more than it does. Here is a quick overview.

EF7 has three pieces of information about each type in the model:
-	CLR type
-	Store type name
-	Max length

EF7 type mapping is designed to use these three pieces of information together with how the type is used (e.g. is it for a key property?) to create a RelationalTypeMapping object that can then be used to:
- Create DbParameter objects, complete with DbType, Size, etc. set as appropriate
- Determine the store type name for Migrations to use when creating a column

Of the three pieces of information in the model, only the CLR type is required. So the type mapper should be able to create default type mappings for any CLR type, or fail if it cannot map the type. But the type mapper can also look at the store type name. max length, and how the type is being used to create different mappings. For example, SQL Server will by default map a string to a RelationalTypeMapping for nvarchar(max), but if the string is being used as a key property, then it will instead map to nvarchar(400).

With regard to reverse engineering, you should create a model that contains these three pieces of information as appropriate. So, for your 3 byte integer case the model should have an appropriate CLR type (e.g. int) and a store type name (e.g. "medium int"). This should then be used by your type mapper to create DbParameters that will work with your ADO.NET provider, setting DbType (or your provider-spcefic XxxType) as appropriate.

Note that currently EF type mapping only supports mapping of types that are handled by the underlying ADO.NET provider. We plan to add type conversion to support even more types, but this isn't implemented yet.

**Comment by rykr** [comment]
@ajcvickers  thanks so much for the good information.  A quick followup if that is ok.  How are we supposed to create type mappers for types like stirngs without having a max length property or attribute.  My provider has several different char data types based on max length.   I guess the user is supposed to set some attribute or annotation in the context for that entity type?   Is there some thought to use an attribute on the property to set a max length?

**Comment by ajcvickers** [comment]
@rykr The model can have the max length of a property set either using the fluent API or a data annotation and that can be used to determine which store type to use as described above.
