### ISSUE TITLE
ToAsyncList() throws NullReferenceException but ToList() doesn't

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [dotnet/efcore#24779]
I am at my wits end with this bug. Please help me solve it.

I am building a ToDo list app with ASP.NET Core Razor Pages and I am using EF Core.

I have a model that is ToDo

```
public class ToDo
{
    public int Id { get; set; }
    public string Title { get; set; }
    public bool IsCompleted { get; set; }
}
```

Heres PageModel:
```
public class IndexModel : PageModel
{
    public IEnumerable<ToDo> ToDos { get; set; }

    // constructor and DI code omitted 

    public async void OnGet()
    {
        ToDos = await _context.ToDos.ToListAsync();
    }
}
```

Here's razor page that uses this:
```
@page
@model IndexModel
@{
    Layout = "_Layout";
}

<div>
    @foreach(var todo in Model.ToDos)
     {
        <h4>@todo.Title</h4>
        <p>Is Completed: @(todo.IsCompleted ? "Yes" : "No")</p>
     }
</div>
```

When I visit this page I get ```System.NullReferenceException``` at ```Model.ToDos```

However, when I change OnGet method to use ```ToList()``` instead:
```
public void OnGet()
{
    ToDos = _context.ToDos.ToList();
}
```
Everything works perfectly.

Why can't I use ```ToListAsync()```

**Comment by smitpatel** [comment]
"async void" is the issue. That is fire and forget the async task. Your method returns before `ToListAsync` is completed hence you see null in `Model.ToDos`

**Comment by Prajwal-Jadhav** [comment]
@smitpatel  Can you please explain more. I don't understand what is happening exactly. I have seen people use "async void" with seemingly no problems. In which case should I avoid "async void". I am new to C#.

P.S.  what do you mean by "fire and forget the async task".

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void

There are several articles on the web which explains why async void shouldn't be used unless very specific case requires it.

> what do you mean by "fire and forget the async task".

You start your async task `ToListAsync` inside `OnGet` method. Since it is async void method you don't have any way to know when that task completed.

**Comment by Prajwal-Jadhav** [comment]
Got it, thanks.
