### ISSUE TITLE
Sqlite fails on 2nd run (beta 6 13586)

### ISSUE THREAD

**Issue by balneaves** [dotnet/efcore#2479]
A bit of a weird one, but background info:
- EF version (EntityFramework.Sqlite/7.0.0-beta6-13586)
- Sqlite file
- OSX / Mono-x64-1.0.0-beta6-12120
- ASP.NET 5 web application (running under kestrel)

Problem:
I have an ASPNET web application which worked on the `EntityFramework/7.0.0-beta6-13554` binaries.  However after upgrade, the application throws on error when using a database created by a prior instance.  i.e. If I delete the sqlite file my app uses, it will create a new file and work perfectly fine.  However if I then shut down kestrel and restart it, I get the below error.

```
NullReferenceException: Object reference not set to an instance of an object
Microsoft.Framework.DependencyInjection.ServiceProvider.CaptureDisposable (System.Object service) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceProvider+ScopedCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceLookup.Service+ConstructorCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceProvider+ScopedCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceProvider+<>c__DisplayClass8_0.<RealizeService>b__0 (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>
Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IEntityQueryProvider] (IServiceProvider provider) [0x00000] in <filename unknown>
Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[IEntityQueryProvider] (IAccessor`1 accessor) [0x00000] in <filename unknown>
Microsoft.Data.Entity.Internal.InternalDbSet`1[Kraken.Models.Component].<.ctor>b__2_0 () [0x00000] in <filename unknown>
Microsoft.Data.Entity.Internal.LazyRef`1[Microsoft.Data.Entity.Query.EntityQueryable`1[Kraken.Models.Component]].get_Value () [0x00000] in <filename unknown>
Microsoft.Data.Entity.Internal.InternalDbSet`1[Kraken.Models.Component].System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator () [0x00000] in <filename unknown>
System.Linq.Enumerable+<CreateGroupByIterator>c__Iterator5`2[Kraken.Models.Component,System.String].MoveNext () [0x00000] in <filename unknown>
Asp.ASPV__Views_Shared_Components_ComponentsMenu_Default_cshtml+<ExecuteAsync>d__17.MoveNext () [0x00000] in <filename unknown>
```

**Comment by bricelam** [comment]
Weird. We recently changed the database encoding from UTF-16 to UTF-8. I wonder if it's related.

**Comment by salerth** [comment]
I've been trying to figure it out (as making a simple new asp.net app doesn't have the same issue) and narrowed it down to custom services.  Why it acts differently between a new database and an existing database still escapes me though.

e.g. in Startup.cs I have
`services.AddSingleton<ComponentService>();`

Any controller/viewcomponent that uses the DbContext via those services fails.

Some code from one of my controllers:
```
Logger.LogError((ComponentService == null).ToString()); //False
Logger.LogError((ComponentService.DbContext == null).ToString()); //False
Logger.LogError((DbContext.Components.Count()).ToString());  //2
Logger.LogError((ComponentService.DbContext.Components.Count()).ToString());  //Exception
```

**Comment by natemcmaster** [comment]
Looks like this could be a bug in [aspnet/DependencyInjection](https://github.com/aspnet/DependencyInjection), not EF.

**Comment by salerth** [comment]
I made a basic repo that reproduces this  https://github.com/salerth/aspnet5test

**Comment by rowanmiller** [comment]
@natemcmaster can you just make sure there is nothing EF specific here and then move (copy) the issue to config.

**Comment by salerth** [comment]
Btw, changing this the service to Scoped rather than Singleton fixes this issue (not sure if thats the right solution but it closes this for me).  Just weird how it works on the first run and not subsequent.

**Comment by natemcmaster** [comment]
Yes, the issue you are seeing is a result of how you are using dependency injection. `TestModelService` is a singleton, which requests to be injected with a scoped service (ApplicationDbContext). Using TestModelService as a scoped service is the correct solution.

cc @rowanmiller DI, EF, and MVC. cref https://github.com/aspnet/Docs/issues/72
