### ISSUE TITLE
Why does ChangeDetector.DetectChanges() only filter out EntityState.Detatched entities?

### ISSUE THREAD

**Issue by intronate67** [dotnet/efcore#24798]
Spent some time determining why a call to DbContext.SaveChanges() was taking more than a few seconds without any changes to be committed to the database. 

We saw that, while debugging, our ChangeTracker's StateManager had almost all of the entities still attached in the EntityState Unchanged (~47,000 entities in our case). We figured this is because we had previously made a modification where the entity was Added or Modified in our application. This made sense as there was a previous call to SaveChanges() to persist those to the database. 

The interesting fact here comes from looking at the result of what AcceptChanges() in Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry has on the DetectChanges() in the ChangeDetector and property comparisons following.

```C#
public virtual void AcceptChanges()
{
    if (!_storeGeneratedValues.IsEmpty)
    {
        ...
    }
    
    _stateData.FlagAllProperties(EntityType.PropertyCount(), PropertyFlag.IsTemporary, false);

    var currentState = EntityState;
    if ((currentState == EntityState.Unchanged)
        || (currentState == EntityState.Detached))
    {
        return;
    }

    if ((currentState == EntityState.Added)
        || (currentState == EntityState.Modified))
    {
        _originalValues.AcceptChanges(this);
        SharedIdentityEntry?.AcceptChanges();

        SetEntityState(EntityState.Unchanged, true);
    }
    else if (currentState == EntityState.Deleted)
    {
        SetEntityState(EntityState.Detached);
    }
}
```
```C#
public virtual void DetectChanges(IStateManager stateManager)
{
    _logger.DetectChangesStarting(stateManager.Context);

    foreach (var entry in stateManager.ToList()) // Might be too big, but usually _all_ entities are using Snapshot tracking
    {
        if (entry.EntityState != EntityState.Detached) // This is the line in question
        {
            LocalDetectChanges(entry);
        }
    }

    _logger.DetectChangesCompleted(stateManager.Context);
}
```
```C#
// Method that gets called even on Unchanged Entities
private void LocalDetectChanges(InternalEntityEntry entry)
{
    var entityType = entry.EntityType;

    if (entry.EntityType.GetChangeTrackingStrategy() != ChangeTrackingStrategy.Snapshot)
    {
        return;
    }

    foreach (var property in entityType.GetProperties())
    {
        if (property.GetOriginalValueIndex() >= 0
            && !entry.IsModified(property)
            && !entry.IsConceptualNull(property))
        {
            var current = entry[property];
            var original = entry.GetOriginalValue(property);

            var comparer = property.GetValueComparer();

            if (comparer == null)
            {
                if (!Equals(current, original))
                {
                    SetPropertyModified();
                }
            }
            else if (!comparer.Equals(current, original))
            {
                SetPropertyModified();
            }

            void SetPropertyModified()
            {
                if (entry.EntityState == EntityState.Deleted)
                {
                    ThrowIfKeyChanged(entry, property);
                }
                else
                {
                    LogChangeDetected(entry, property, original, current);
                    entry.SetPropertyModified(property);
                }
            }
        }
    }

    foreach (var property in entityType.GetProperties())
    {
        DetectKeyChange(entry, property);
    }

    if (entry.HasRelationshipSnapshot)
    {
        foreach (var navigation in entityType.GetNavigations())
        {
            DetectNavigationChange(entry, navigation);
        }

        foreach (var navigation in entityType.GetSkipNavigations())
        {
            DetectNavigationChange(entry, navigation);
        }
    }
}
```
The reassignment of the EntityState when the EntityState was previously either Added or Modified in AcceptChanges() confirmed our assumption that's why they we're still in the change tracker. Also, here is where we see the DetectChanges() method only filter the entities that are Detached and pass those that are not on to the LocalDetectChanges() method.

To fix this momentarily, as we we're unnecessarily saving when there were no changes, we modified our code to only call SaveChanges() if the previous method call did some call that needed DB persistence like below.

```C#
private void RemoveSomeItemFromDB(item i)
{
    // Performs the change on the DbSet (delete in this case)
    // returns a boolean representing if .Remove was actually called
    if (_repository.DeleteRelatedEntityToI(i.some_id))
        _repository.Save(); // Calls SaveChanges()
}
```
Though, we still ran into the long running SaveChanges() when something needed to be _actually_ committed. 

After reviewing one of entities we were updating and/or adding, we noticed that it had ~400 columns. Ideally this gets split up in the future as it is a quite dense table but there is a few roadblocks, including legacy applications, we have to solve until we can do that. In the mean time, we noticed when the ChangeDetector is trying to detect changes, it was going through all 47,000 of our Unchanged entities looking for changes, while in reality the only change it needed to commit was the entity that _was_ changed (deleted in this case). 

So this leads me to the question, why does the loop to detect local changes in the ChangeDetector, pass through Unchanged entities to the LocalDetectChanges function? Is it as simple as just adding another conditional to the if inside the loop in DetectChanges to also filter out Unchanged? Or is there some side effect that I am not aware of? In our case, it has resulted in the LocalDetectChanges being called many more times than necessary involving ~18 million more property comparisons than is necessary. This seemed appropriate enough to attribute our prolonged execution time of SaveChanges().

**Comment by ajcvickers** [comment]
> why does the loop to detect local changes in the ChangeDetector, pass through Unchanged entities to the LocalDetectChanges function

Because DetectChanges is the thing that determines whether or not the entity has changed. If a change is detected in an Unchanged entity, then it gets marked as Modified. This is what DetectChanges is for.

Are you using a single context instance per unit-of-work? Typically in a unit of work you would load only the entities needed for that unit-of-work.

I would suggest reading though some of the documentation on [how change tracking works](https://docs.microsoft.com/en-us/ef/core/change-tracking/) in EF Core since it covers the different entity states and changes between them.
