### ISSUE TITLE
EF.Function.Like(x=>x.property,"");How to make the type of string to repalce the x.property

### ISSUE THREAD

**Issue by BoomJY** [dotnet/efcore#24801]
override the function the property。 must specify the properties of the entity.
How is a string condition passed from the front end passed as a property of the entity

**Comment by smitpatel** [comment]
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by BoomJY** [comment]
Here is the API Main Code&nbsp;


Expression<Func<Mission_BasicInfo, Base_User, Mission_BasicInfoDto&gt;&gt; select = (a, b) =&gt; new Mission_BasicInfoDto
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; PractitionersName = b.RealName
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; };
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var q_MissBasic = GetIQueryable();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var where = LinqHelper.True<Mission_BasicInfo&gt;();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var search = input;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; select = select.BuildExtendSelectExpre();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var q = from a in q_MissBasic.AsExpandable()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; join b in Db.GetIQueryable<Base_User&gt;() on a.Practitioners equals b.Id into ab
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; from b in ab.DefaultIfEmpty()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; select @select.Invoke(a,b);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;//Problem
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;condition --string ,equal the property&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;var condition = $"%{search.condition}%";
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; q = q.Where(x =&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;EF.Functions.Like(condition, keyword)&nbsp;;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;this is the problem
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (!search.keyword.IsNullOrEmpty())
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var keyword = $"%{search.keyword}%";
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; q = q.Where(x =&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;EF.Functions.Like(x.PractitionersName, keyword) ||
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; EF.Functions.Like(x.MissionInfo, keyword)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; || EF.Functions.Like(x.Participants, keyword)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; || EF.Functions.Like(x.LastModifiRealName, keyword));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var list = await q.GetPageResultAsync(input);




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Smit ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnet/efcore] EF.Function.Like(x=&gt;x.property,&quot;&quot;);How to make the type of string to repalce the x.property (#24801)






这个问题缺乏足够的信息，我们无法有效复制。请张贴一个可运行的项目/解决方案或完整的代码清单，演示您看到的行为。

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by smitpatel** [comment]
@BoomJY - There are still not enough details provided by you. We can see some bits and pieces of query but still it is hard to figure out what is the LINQ query and what it is supposed to do and what issue you are running into. Please provide more details.

**Comment by BoomJY** [comment]
@Smit Patel&nbsp;-Thank you very much for noticing my problem.
I have found a suitable solution in the community，I haven't been working on EFCore for a long time so I'm sorry to bother you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Smit ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午12:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnet/efcore] EF.Function.Like(x=&gt;x.property,&quot;&quot;);How to make the type of string to repalce the x.property (#24801)





 
@BoomJY - There are still not enough details provided by you. We can see some bits and pieces of query but still it is hard to figure out what is the LINQ query and what it is supposed to do and what issue you are running into. Please provide more details.
