### ISSUE TITLE
EF CORE : Calling SaveChangesAsync on invalid data inserted (foreign key does not exist), causes database volume to increase.

### ISSUE THREAD

**Issue by tessierp** [dotnet/efcore#24816]
In reference to this issue : https://github.com/dotnet/efcore/issues/24663, I am experiencing the same issue where the volume size increases. I am using NLog through Microsoft's Logging middleware. Trying to save changes with an invalid foreign key ID will result in the call hanging there and memory will increase. I started to get this issue when I moved from EF CORE 3.0 to EF CORE 5.0. 

With EF CORE 3.x the behavior would be that an exception would be generated to let me know there was a foreign key violation but this no longer occurs. Each call to SaveChangesAsync after adding a model with invalid data will cause it to hang there with no exceptions being thrown and it causes the size of the volume to increase. until I stop the process.

I experienced these issues with PostgreSQL, think it was maybe due to the provider, I decided to test against MSSQL but had the same issue.

**Comment by roji** [comment]
@tessierp I'm assuming you mean the *process* memory size increases, rather than the database size? If so, this indeed sounds like #24663 - check whether your logging framework is configured to log the exception, including all referenced objects (which would make it query all data from the database).

Otherwise, please submit a minimal, runnable code sample which demonstrates this.

**Comment by tessierp** [comment]
@roji Unless I'm reading this wrong, it is not the processes memory but the volume data that increases. Doing "docker system df -v" reveals that the volume data for PostgreSQL is increasing when it hangs on the SaveChangesAsync(). I have looked if data was inserted in the tables but couldn't find anything in there. This situation happens when I try to save data from a model that contains a ForeignKey reference that is invalid, it will just hang there..

Also, I'm using NLOG not Serilog.

Providing a code sample may be difficult at the moment. If I absolutely have to, I'll have to switch back to .NET CORE 3.1

**Comment by roji** [comment]
Yes, we're going to have to see a code sample to investigate this.

**Comment by tessierp** [comment]
I understand. I may not be able to provide that for a while since I have to find a solution and the solution is to go back to 3.1.

**Comment by tessierp** [comment]
I still do not have code to provide, providing the same structure of code involved would be too complicated and long in producing a "demo". However, there was an interesting turn of event.  I decided to implement the event "SaveChangesFailed" and then when I call SaveChangesAsync with an invalid ForeignKey it does fire the event and I get the error message stating that it is violating a Foreign Key Relationship. 

I never had to do this in the past in order for SaveChangesAsync to throw an exception. Is this something that was implemented recently ?

**Comment by tessierp** [comment]
I confirm the problem seems to be caused by AuditNet which, keeps on calling SavesChanges to infinity on a failure.

**Comment by ErikEJ** [comment]
Do you mean this: https://github.com/thepirat000/Audit.NET ?

**Comment by tessierp** [comment]
Hi Erik,

Yes that is the exact one I am using. I am unsure yet if it due to something I may have done wrong or missed or a bug in Audit.Net. In my implementation I'm using DbContextHelper which comes with the framework and that helper has a Savechanges implementation and that is the one that keeps on being called in a loop.
