### ISSUE TITLE
what is the best way to resolve AsSplitQuery perf warning vs transactionally consistent data?

### ISSUE THREAD

**Issue by dirething** [dotnet/efcore#24812]
I have a context used throughout a blazor project, conveniently it warns when someone creates a perf issue by .include 'ing too many child tables:

`Compiling a query which loads related collections for more than one collection navigation either via 'Include' or through projection but no 'QuerySplittingBehavior' has been configured. By default Entity Framework will use 'QuerySplittingBehavior.SingleQuery' which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'`

That link mostly seems to be there so you can find the link to this page: https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries which has some warnings about how splitqueries are not guarenteed to be transactional ly consistant and some notes about turning the settings on and off globally.

As best as I can follow you can only configure the warnings on an injected context at the point you are configuring it.  It seems that I should be able to use splitqueries with DbContext.Database.BeginTransaction but manually creating a read-isolated transaction on a bunch of very busy tables when the query the EF warning is triggering on is already running pretty efficiently seems like the wrong answer.

Am I missing an option somewhere to suppress the warning on a specific query?  I can change the splitting behaviour with .AsSplitQuery but I do not see anything like that for warnings

Am I underestimating how bad the non-split version actually is and even though it is fast it would be safer to split it and wrap it in a longer lasting (and to my understanding of sql internals probably more expensive) manual transaction?

Ideally i would like to leave this warning on then specifically suppress it on queries that have a high likelihood of a dirty read, but perhaps I am misunderstanding something here.

**Comment by roji** [comment]
>  It seems that I should be able to use splitqueries with DbContext.Database.BeginTransaction but manually creating a read-isolated transaction on a bunch of very busy tables when the query the EF warning is triggering on is already running pretty efficiently seems like the wrong answer.

Note that the default isolation level - read committed - is not enough to prevent potential inconsistencies; this is why the docs mention serializable or snapshot level, which should always guarantee consistent results across queries. However, this indeed have an even higher potential cost than regular transactions.

> Am I missing an option somewhere to suppress the warning on a specific query? I can change the splitting behaviour with .AsSplitQuery but I do not see anything like that for warnings

You can add AsSingleQuery to a specific query - this should make the warning go away for that query. You can think of it as meaning that you've acknowledged the potential perf issue with the single query and explicitly want that behavior.

> Am I underestimating how bad the non-split version actually is and even though it is fast it would be safer to split it and wrap it in a longer lasting (and to my understanding of sql internals probably more expensive) manual transaction?

Whether single query is bad (or bad enough) really depends on your actual data in the database, so it's a decision you must make on a case-by-case basis... In some cases, you can have many collection includes but which don't actually yield many dependent rows; single query should be fine. On the other hand, even a single collection include could be problematic from a perf perspective, as the principal columns are duplicated for each dependent row.

On the split query side, the potential consistency issues of multiple queries typically occur only in database with highly-concurrent updating going on, and even then, they might not actually cause problems in your code... This again is highly-dependent on your specific application.

**Comment by dirething** [comment]
I have a log of queries where there is no reason not to use .AsSplitQuery, but so far about 5 places where .AsSplitQuery without the transactional guarantee seems like a risk and at least one where it has proven to be a risk because of the number of parallel updates.

What seems like the best course of action here would be to run the at risk queries without .AsSplitQuery as their performance is currently not an issue, but since some of these are run quite frequently I would like to suppress the warning without disabling it globally since there are many other queries, and other less database oriented developers, where I would like to catch such mistakes everywhere except these particular queries.

I was expecting there was something similar to ConfigureWarnings at the query or instance level but that does not seem to be the case.

**Comment by stevendarby** [comment]
As suggested above you can explicitly add `AsSingleQuery` to get rid of the warning (I know it’s easy to read over this as ‘Split’ so just wanted to draw attention to it again)

**Comment by dirething** [comment]
Apologies to @roji - dyslexic reading has had exactly the result @stevendarby assumed was happening here.  

This does suppress the error.

Am I missing somewhere that this is explained in the documentation? or is it just too new since I get less than a full page of google results for the RelationalQueryableExtensions version of AsSingleQuery?

**Comment by stevendarby** [comment]
@dirething 
https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#enabling-split-queries-globally

This mentions the 3 conditions under which the warning will appear and how to turn it off.

**Comment by dirething** [comment]
thank you, I definitely was not looking at the section about turning off consistency globally after I first ran into these warnings and tried the suggested .AsSplitQuery with undesirable results.
