### ISSUE TITLE
[Question] SQLQuery

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2483]
What is the current alternative way to query raw sql?
Database.SqlQuery - Not Exists

**Comment by divega** [comment]
You can do `context.Products.FromSql("select * from archive.products")`. Compared to `Database.SqlQuery()` it is limited to queries that can be expressed in terms of entities, or that at least start with an entity (you can later project using LINQ and the projection will be executed on the server, e.g.: `context.Products.FromSql("select * from archive.products").Select(p => new {p.Id, p.Name})`.

Does this work for you?

**Comment by XcoderTeam** [comment]
@divega above example is good enough if i want to query the entities it make sense.

so how to do if i need to do something like procedure, i know that ef7 still not implement sp yet, so what is the current alternative ways.

DECLARE @Id INT, @quantity INT;
SELECT TOP 1 @Id=Id, @quantity=quantity FROM [Products] WHERE Name = @Name --'Computer'

IF (@id IS NULL)
BEGIN
	SELECT -1 AS [status] --Item not exists
END

UPDATE [Products] SET quantity = quantity - 1 WHERE Id=@Id;

SELECT 1 AS [status], @Name AS ProductName

**Comment by divega** [comment]
@XcoderTeam it won't be possible to map CRUD operations to stored procedures in EF7.0.0 RTM, but stored procedures can already be invoked from the `FromSql()` method. As I mentioned previously, the requirement in that case is that the stored procedure returns a result with the same shape of the entity. 

We also have plans to include an API for the execution of commands that do not return results (see #1863) in EF7.0.0 RTM. However that is not implemented yet. 

Other scenarios, including the execution of arbitrary SQL queries with arbitrary result shapes are going to be addressed later. 

In the meanwhile, as a workaround you can use code like the one described in this thread on StackOverflow.com:

http://stackoverflow.com/questions/30470281/db-database-executesqlcommand-equivalent-in-ef-7/30487747#30487747

Hope this helps,
Diego
