### ISSUE TITLE
ServiceProviderCache is memory leak

### ISSUE THREAD

**Issue by ZhiqiangTao** [dotnet/efcore#24841]
Recently, I meet a problme that the memory is grow slow until oom , and then my container is restart due to OOM.
So, I use dotnet-dump to collect dump file, and use dotMemory tool to analyze it. I see some strange things(cause root of OOM) as below:
![image](https://user-images.githubusercontent.com/16182251/117116517-0ccd3300-adc1-11eb-8677-84c483d00bdc.png)
![image](https://user-images.githubusercontent.com/16182251/117116424-f030fb00-adc0-11eb-8040-a782d086d144.png)
you can see that there are large retained object[] exist which cause my container OOM and restart. This is maybe a memory leak issue. 
go on👇
open the "largest object[]' and order by the retained bytes, I fount that the "ServiceProviderCache" is the largest:
![image](https://user-images.githubusercontent.com/16182251/117117256-ebb91200-adc1-11eb-8ff8-e86da948a049.png)
step in 👇
![image](https://user-images.githubusercontent.com/16182251/117117311-fe334b80-adc1-11eb-9631-670cda2c9060.png)
![image](https://user-images.githubusercontent.com/16182251/117117433-1d31dd80-adc2-11eb-953f-71da87cd163a.png)
so what's the problem?

I think it's due to my "no-official" way to use DbContext, eh~~~, but i'm not sure for it......
some key infos as below:
![image](https://user-images.githubusercontent.com/16182251/117118031-d395c280-adc2-11eb-9147-1ed661288e4a.png)
![image](https://user-images.githubusercontent.com/16182251/117118032-d395c280-adc2-11eb-9ff3-6bde65975d0c.png)
![image](https://user-images.githubusercontent.com/16182251/117118072-e5776580-adc2-11eb-8775-fa0b50b8d811.png)
di:
![image](https://user-images.githubusercontent.com/16182251/117118122-fa53f900-adc2-11eb-8278-5c3f90dc90b9.png)
init a dbcontext instance for per request(repository is scope)
![image](https://user-images.githubusercontent.com/16182251/117118905-ed83d500-adc3-11eb-88da-c401be8a7fcf.png)
I have to use the "ShardModelCacheKeyFactory" to implement some special biz rule, so i can't use the "official way" like "services.AddContextPool()".

so what the root reason let the ServiceProviderCache memory leak? How can fix this probelm? thanks in advance!!!

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.MySql
Target framework: (NET 5.0)
Operating system: an console app 5.0 in docker container (official 5.0 runtime image)
My Container limit : 800m
GC:  workstation + bgc
dll version in csproj:
![image](https://user-images.githubusercontent.com/16182251/117119598-e3aea180-adc4-11eb-8111-0ab895f6696e.png)

**Comment by ZhiqiangTao** [comment]
host info :
centos 8 + 8 cores CPU + 16GB RAM + Docker with K8S

**Comment by ZhiqiangTao** [comment]
I will execute 'InitDbContext' method before each dbcontext operation, just like below:
![image](https://user-images.githubusercontent.com/16182251/117121459-30937780-adc7-11eb-8cbc-febb8f7d2a7c.png)
ps: InitDbContextAfterVerify is a simple wrapper of InitDbContext

**Comment by ajcvickers** [comment]
@ZhiqiangTao Please post [debug-level EF Core logs](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/) from the application startup through where DbContext instances start to be used.

**Comment by ZhiqiangTao** [comment]
@ajcvickers I use console.writeline log:
![image](https://user-images.githubusercontent.com/16182251/117237230-0c827580-ae5d-11eb-9897-30dc9d9e985b.png)
the logs [here](https://raw.githubusercontent.com/ZhiqiangTao/Debug/main/log.txt).
ps: I have replaced the secret ip with other chars

**Comment by ZhiqiangTao** [comment]
update some useful pictures:
![image](https://user-images.githubusercontent.com/16182251/117301924-b12ca380-aead-11eb-9d2a-5af16d261e1e.png)
![image](https://user-images.githubusercontent.com/16182251/117301983-c0abec80-aead-11eb-90e4-5e47a567f7c8.png)
![image](https://user-images.githubusercontent.com/16182251/117302025-cd304500-aead-11eb-9e59-ec2062a043dc.png)
![image](https://user-images.githubusercontent.com/16182251/117302432-31eb9f80-aeae-11eb-8b4f-2adadbc5eb83.png)

**Comment by ajcvickers** [comment]
@ZhiqiangTao From the logs it does not appear that an excessive number of service providers are being built. How many entity types do you have in your EF model? How many properties, on average, do each of those types contain?

**Comment by ZhiqiangTao** [comment]
@ajcvickers I have about 6 tables with the format 'user00,user01,user02....user99; red00,red01....red99', so I don't want to crete 6*100 dbset<T> , then I consum the 'IModelCacheKeyFactory' interface to cache model with the partial key (eg: 00,01). each table contains about 15 properties.
my OnModelCreating like below:
![image](https://user-images.githubusercontent.com/16182251/117521980-454c5700-afe3-11eb-8702-3758b2447201.png)

**Comment by ZhiqiangTao** [comment]
upload my code snippet to use dbcontext (controller ->service -> repository)
![image](https://user-images.githubusercontent.com/16182251/117538166-82423900-b037-11eb-8587-2af47898a013.png)
my ShardingDBRepository.cs refer to [here](https://raw.githubusercontent.com/ZhiqiangTao/Debug/main/ShardingDBRepository)

**Comment by ajcvickers** [comment]
@ZhiqiangTao It looks like your custom model cache is caching many model instances.

**Comment by ZhiqiangTao** [comment]
JamesLoveForever is mine

**Comment by ajcvickers** [comment]
@JamesLoveForever If you post the code you have that makes use of `IModelCacheKeyFactory`, then I will take a look. However, it's often the case that we need fully runnable code to reproduce and debug issues.

**Comment by AndriySvyryd** [comment]
@ZhiqiangTao From what you've posted this looks like the expected behavior.

Make sure that the objects produced by the `IModelCacheKeyFactory` implementation for the same key value are actually `.Equals()` to each other.

If the `OnModelCreating` methods is being invoked more than once for any given model cache key value then please post a small self-contained repro project and we'll reopen this issue.
