### ISSUE TITLE
efcore mysql json object property filter

### ISSUE THREAD

**Issue by Ashionnal** [dotnet/efcore#24854]
#### Demo Entity

    /// <summary>
    /// demo
    /// </summary>
    public class Demo : BaseModel
    {
        /// <summary>
        /// name
        /// </summary>
        public string name { get; set; }

        /// <summary>
        /// age
        /// </summary>
        public int age { get; set; }

        /// <summary>
        /// content: json type 
        /// </summary>
        public JsonObject<Content> content { get; set; }

    }
    public class Content
    {
        public string name { get; set; }

        public int age { get; set; }
    }

#### Context Code

    /// <summary>
    /// demo
    /// </summary>
    public class FrameworkDbContext: DbContext
    {
    /// <summary>
    /// 
    /// </summary>
    /// <param name="dbContextOptions"></param>
    public FrameworkDbContext(DbContextOptions<FrameworkDbContext> dbContextOptions) : base(dbContextOptions)
    {
    }
    /// <summary>
    /// 
    /// </summary>
      public DbSet<Demo> demo { get; set; }
    }

#### Business Code
            using(var transaction = _frameworkDbContext.Database.BeginTransaction())
            {
                // 1. get all data
                var all_demo_data = _frameworkDbContext.demo.ToList();
                // 2. add a demo object data
                _frameworkDbContext.demo.Add(new Demo
                {
                    age = 20,
                    content = new Content { age = 89, name = "test_name" },
                    name = "main_name"
                });

                _frameworkDbContext.SaveChanges();
                // 3. again get all data 
                var all_demo_data_again = _frameworkDbContext.demo.ToList();

                // 4. this step will error when i want to filter the content(a json object)
                var filter_data = _frameworkDbContext.demo.Where(m => m.content.Object.age > 22).ToList();

                transaction.Commit();
            }

#### 1. this is the first step to query all demo data, it works success.

![1](https://user-images.githubusercontent.com/23193694/117430143-661c9a00-af5a-11eb-9102-0074a73c7796.png)

#### 2. this is the second step to add one demo data, it also works success.

![2](https://user-images.githubusercontent.com/23193694/117430365-a54aeb00-af5a-11eb-92eb-c210770129b1.png)

#### 3. this is the third step to query demo data when i want to filter the content field(this field's db type is JSON)

![3](https://user-images.githubusercontent.com/23193694/117430525-d0cdd580-af5a-11eb-83c9-69d550820968.png)

#### 4. follow is mysql db structure and data
![6](https://user-images.githubusercontent.com/23193694/117430729-f8bd3900-af5a-11eb-97b0-9e8ae094da2a.png)
![7](https://user-images.githubusercontent.com/23193694/117430735-f9ee6600-af5a-11eb-9728-fb5567f70501.png)

**Comment by roji** [comment]
This looks a question for the EF Pomelo MySQL provider - please move the issue there: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql.

**Comment by roji** [comment]
When opening an issue, please try to provide a simple, runnable code sample - the snippets and screenshots make it hard to understand exactly what you're doing and what's necessary to reproduce the problem.
