### ISSUE TITLE
Adding a data migration with dotnet cli creates a migration which as redundant actions which prevent the database from updating

### ISSUE THREAD

**Issue by logan-cy** [dotnet/efcore#24851]
Having updated my app's data model, I added a new migration and attempted to push the updated schema to the database:

    dotnet ef migrations add <description>
    dotnet ef database update

I was stumped initially when Entity Framework output the following error:

> Column names in each table must be unique. Column name 'FirstName' in table 'AspNetUsers' is specified more than once.

Checking the migration, I found that it does indeed add a column called FirstName onto the AspNetUsers table (this is in line with my extension of the IdentityUser class).

There were other anomalies as well, where the schema identification against the database is concerned:

- 3 columns were added that already existed in the target database
- 15 tables were added that already existed in the target database
- 18 indexes were added that already existed in the target database

It's worth noting that I haven't changed the connection string for the database since started this project.

The full migration can be found here: https://pastebin.com/mAhhCUGd

As a workaround, I was able to persist the new changes to the database by commenting out the code that added the duplicate entities, but if that's going to be necessary whenever I update my database, I see little point in generating migrations with EF rather than writing them myself.

**Comment by ajcvickers** [comment]
@logan-cy That behavior is not expected, but this issue is lacking enough information for us to be able to effectively investigate. Can you please post a small, runnabe project that reproduces what you are seeing when adding a migration and updating the database.

**Comment by AndriySvyryd** [comment]
@bricelam FYI

**Comment by bricelam** [comment]
@logan-cy It sounds like you're making changes directly to the database, updating your model to match the database, then trying to add and apply a migration. Is that correct?

Indeed, there is there is little point in generating migrations this way... Please see the [Migrations documentation](https://docs.microsoft.com/ef/core/managing-schemas/migrations/) to learn more about the workflow for making schema changes.
