### ISSUE TITLE
Cosmos: Simple select * across a partitionkey bugs if same id?

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/efcore#24864]
Hi, im trying to do the most simple thing which is a SELECT all, which include all items in all partitions.
For example, i have a container named "Person", which have the partitionkey "/Country".
I have 3 items in the container. They all have different PartitionKeys but the same id.

![image](https://user-images.githubusercontent.com/6762656/117583728-22b45e00-b109-11eb-92ba-7beeeb9fc830.png)

![image](https://user-images.githubusercontent.com/6762656/117583752-39f34b80-b109-11eb-83d0-61e75dffc51a.png)

![image](https://user-images.githubusercontent.com/6762656/117583746-2f38b680-b109-11eb-9896-3527aaf21296.png)

And here is my C# code, trying to list all of them:

```
public class Person
{
	public string Country { get; set; }
	public string Id { get; set; }
	public string Name { get; set; }
}
public class AppDbContext: DbContext
{
	public DbSet<Person> Persons { get; set; }

	public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
	{
	}
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Person>().ToContainer(nameof(Person));
		modelBuilder.Entity<Person>().HasNoDiscriminator();

		modelBuilder.Entity<Person>().Property(x => x.Id).ToJsonProperty("id");
		modelBuilder.Entity<Person>().HasKey(x => x.Id);
		modelBuilder.Entity<Person>().HasPartitionKey(x => x.Country);
	}
}
public class Program
{
	public static async Task Main()
	{
		var optionsBuilder = new DbContextOptionsBuilder<AppDbContext>();
		optionsBuilder.UseCosmos(
			"https://localhost:8081",
			"C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
			"Scratch");

		using (var dbContext = new AppDbContext(optionsBuilder.Options))
		{
			var people = await dbContext.Persons.ToListAsync();
			Console.WriteLine(JsonConvert.SerializeObject(people, Formatting.Indented));
		}

		Console.ReadLine();
	}
}
```

The Console writes out:
![image](https://user-images.githubusercontent.com/6762656/117583833-b5ed9380-b109-11eb-8682-2b1940b2f96f.png)

So, why does it write out 3 times "Peter" from Denmark?

If i try to use the Cosmos SDK, then everything works as i expect, like this:

```
using (var dbContext = new AppDbContext(optionsBuilder.Options))
{
	var cosmosClient = dbContext.Database.GetCosmosClient();
	var database = cosmosClient.GetDatabase("Scratch");
	var container = database.GetContainer("Person");

	var resultSet = container.GetItemQueryIterator<Person>(new QueryDefinition("SELECT * FROM c"));
	var items = (await resultSet.ReadNextAsync()).ToList();
	Console.WriteLine(JsonConvert.SerializeObject(items, Formatting.Indented));
}
```

Then Console writes out
![image](https://user-images.githubusercontent.com/6762656/117583986-9d31ad80-b10a-11eb-982e-a4ed3a2e4905.png)

Is it a bug, or am i configuring something wrong with ef core?

**Comment by smitpatel** [comment]
Your Id column is configured as PK using `HasKey` but it is not unique across results. EF Core change tracker performs identity resolution so it will not materialize result if an entity with same PK already available in the context. So results just repeated first record since PK value was same. You need to configure PK which is unique across records. May be "Id", "Country" composite key would be a good candidate.

**Comment by Assassinbeast** [comment]
@smitpatel Thanks for clearing that out for me.
I tried to configure my primary key like this, and it actually worked :D

`modelBuilder.Entity<Person>().HasKey(x => new { x.Id, x.Country });`

But at the end of the day, isn't it a bug of the EF Core implementation then?

**Comment by smitpatel** [comment]
> isn't it a bug of the EF Core implementation then?

Looking at code above, user actually configured the Id as primary key. Primary key by definition implies that it has to be unique across records in all data (not just inside a given partition). When the data doesn't match model configuration then there is potential for having bad results for queries from server. This is just one such case so this is usage bug. Further, there is no remedy for this in EF Core without making things worse for everyone.
