### ISSUE TITLE
Wiki repository cannot be cloned to browse locally

### ISSUE THREAD

**Issue by weltkante** [dotnet/efcore#2486]
I'm keeping clones of various github wiki repositories for browsing them locally and this one causes errors:

```
git clone https://github.com/aspnet/EntityFramework.wiki.git
[...]
error: Invalid path 'Design-Meeting-Notes:-April-16-2015.md'
error: Invalid path 'Design-Meeting-Notes:-December-4,-2014.md'
error: Invalid path 'Design-Meeting-Notes:-January-15,-2015.md'
error: Invalid path 'Design-Meeting-Notes:-January-16,-2015.md'
error: Invalid path 'Design-Meeting-Notes:-January-29,-2015.md'
error: Invalid path 'Design-Meeting-Notes:-January-8,-2015.md'
error: Invalid path 'Design-Meeting-Notes:-June-18,-2015.md'
error: Invalid path 'Design-Meeting-Notes:-November-20,-2014.md'
error: Invalid path 'Design-Meeting-Notes:-October-30,-2014.md'
error: Invalid path 'Design-Meeting-Notes:-October-9,-2014.md'
```

See https://help.github.com/articles/adding-and-editing-wiki-pages-locally/ for the wiki rules:

```
Warning: Don't use the following characters in your wiki page's titles: \ / : * ? " < > |
Users on certain operating systems won't be able to work with filenames containing these characters.
```

**Comment by ajcvickers** [comment]
This is really an external github issue. Assuming it is not fixed by github, we don't plan to fix it on our side, although it is important to anybody in the community and they have a fix, then we would be willing to take a pull request for it.

**Comment by weltkante** [comment]
@ajcvickers Actually thats not a github issue, someone has been creating pages with a colon in their name and Windows can't handle files with a colon in the name. Anyways, someone already renamed those pages so nothing more to do here. `git clone https://github.com/aspnet/EntityFramework.wiki.git` works fine right now.
