### ISSUE TITLE
Calling FromSqlRaw with the sql statement generated by ToQueryString throws error 

### ISSUE THREAD

**Issue by dbereghici** [dotnet/efcore#24876]
**Steps to reproduce**
`var paramInt = 42;
var sql = db.Set<MyEntity>().Where(e => e.MyInt == paramInt).ToQueryString();`

The output is: 

`.param set @__p_0 42

SELECT "k"."MyInt"
FROM "MyEntity" AS "k"
WHERE "k"."MyInt" = @__p_0`

Then when calling `dbContext.MyEntities.FromSqlRaw(sql)` I get the following error: 
`SQLite Error 1: 'near “.”: syntax error'.'`

**Technical details**
EF Core version: 5.0.5
Database provider: SQLite

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.query.iqueryingenumerable.toquerystring?view=efcore-5.0

Documentation indicates that the string may not be suitable for direct execution and for debugging purposes only.

**Comment by dbereghici** [comment]
I see, thank you for the answer
