### ISSUE TITLE
One-to-One Self-Referencing Relation in EF Core

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#24885]
I want to create a table like this with ef core
```SQL
create table Post
(
	Id int not null primary key identity(1,1),
	Text nvarchar(1000) not null,
	ForwardPostId int null foreign key references Post(Id),
	BackwardPostId int null foreign key references Post(Id)
)
```
`ForwardPostId ` and `BackwardPostId ` columns are self-referencing foreign keys of the `Id` column.   
Also, I created this model class for it:
```c#
 public class Post
    {
        public long Id { get; set; }
        public string Text { get; set; }

        public long? ForwardPostId { get; set; }
        public Post ForwardPost { get; set; }

        public long? BackwardPostId { get; set; }
        public Post BackwardPost { get; set; }
    }
```
This is natural to write this c# code for creating a table with that relations:
```c#
 builder.Entity<Post>().HasOne(p1 => p1.ForwardPost)
    .WithOne(p2 => p2.BackwardPost)
    .HasPrincipalKey<Post>(p2 => p2.BackwardPostId);

builder.Entity<Post>().HasOne(p2 => p2.BackwardPost)
    .WithOne(p1 => p1.ForwardPost)
    .HasForeignKey<Post>(p1 => p1.ForwardPostId);
```
But when I add migration and update my database, ef core created just one foreign key like this `FK_Posts_Posts_ForwardPostId` for me!    
Where is another foreign key? (like this `FK_Posts_Posts_BackwardPostId` for example)   
This is just for the time that `ForwardPostId ` and `BackwardPost` are nullable. If they were not nullable `dotnet ef database update` command get this error `Introducing FOREIGN KEY constraint 'FK_Posts_Posts_ForwardPostId' on table 'Posts' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.`    

---   

Finally, I realized that if I want to have a table Iike what I show above, I have to write a code like this!: 🤯🤯🤯🤦‍♂️🤦‍♂️🤦‍♂️

```c#
 public class Post
    {
        public long Id { get; set; }
        public string Text { get; set; }

        public long? ForwardPostId { get; set; }
        public Post ForwardPost1 { get; set; }
        public Post ForwardPost2 { get; set; }

        public long? BackwardPostId { get; set; }
        public Post BackwardPost1 { get; set; }
        public Post BackwardPost2 { get; set; }
    }
```
and 
```c#
builder.Entity<Post>()
    .HasOne(p1 => p1.ForwardPost1)
    .WithOne(p2 => p2.BackwardPost1)
    .HasForeignKey<Post>(p2 => p2.BackwardPostId);

builder.Entity<Post>()
    .HasOne(p2 => p2.BackwardPost2)
    .WithOne(p1 => p1.ForwardPost2)
    .HasForeignKey<Post>(p2 => p2.ForwardPostId);
```

**Is there a way to create both one-to-one self-referencing foreign keys without this strange code?**

**Comment by ajcvickers** [comment]
@KazemJavadi Navigations cannot be shared between relationships. So you don't need to include all those navigations in your model, but any navigations that you do map must be used by only a single relationship.

**Comment by KazemJavadi** [comment]
Thanks for your reply.
I think I should check further.
