### ISSUE TITLE
Migrations: Interpret model

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2488]
There are a few places in Migrations that we should "interpret" the model to create database artifacts:
- Guid columns with a store generated pattern of Identity should have a default SQL value of `NEWSEQUENTIALID()`
  - `NEWID()` on Azure
- "Implicit" indexes
  - For each FK
    - Unique when FK is unique
  - Stop doing this and collapse them when #700 is implemented
- Possibly interpret unique indexes as UNIQUE constraints
- Other places?

**Comment by divega** [comment]
> Possibly interpret unique indexes as UNIQUE constraints
What would the motivation be for this one?

**Comment by bricelam** [comment]
@divega It was more compelling when we didn't have the `AlternateKey()` API.

**Comment by divega** [comment]
I was only thinking that indexes could potentially become more expressive than alternate keys, e.g. support direction, filters and included columns. But I guess it would be ok anyway if we only match the simple cases to alternate keys.

**Comment by rowanmiller** [comment]
Already covered by other issues
