### ISSUE TITLE
Compiled model: Allow use of lazy loading and change tracking proxy types.

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#24902]
Depends on #24898

**Comment by viniciusverasdossantos** [comment]
Hi. Will we be able to CompiledModel with UseLazyLoadingProxies until the final version of .NET 6?

**Comment by AndriySvyryd** [comment]
@viniciusverasdossantos No, this issue is in the Backlog, so we don't have plans for shipping it in any specific release yet

**Comment by viniciusverasdossantos** [comment]
> @viniciusverasdossantos Não, este problema está no Backlog, então não temos planos para enviá-lo em nenhum lançamento específico ainda

I am suffering a lot with my 550 entity model in development due to the delay each time I compile. I use lazyload and changetrackproxy. For Lazy Load if I implement the manual form in each class I will be able to use the CompiledModel right? Is there a similar alternative for ChangeTrackProxy? Well, I use both resources.

**Comment by AndriySvyryd** [comment]
@viniciusverasdossantos You might be hitting https://github.com/dotnet/efcore/issues/20135, where proxy type creating is taking longer for each type.

For change tracking you can [implement INotifyPropertyChanging and INotifyPropertyChanged](https://docs.microsoft.com/en-us/ef/core/change-tracking/change-detection#notification-entities).

**Comment by viniciusverasdossantos** [comment]
Hi. Will we be able to CompiledModel with UseLazyLoadingProxies until the final version of .NET 6?

**Comment by ajcvickers** [comment]
@viniciusverasdossantos This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 7.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by viniciusverasdossantos** [comment]
> @viniciusverasdossantosEsse problema está no marco do Backlog. Isso significa que não está planejado para a próxima versão (EF Core 7.0). Reavaliamos [o backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) após esta versão e consideramos este item naquele momento. No entanto, lembre-se de que existem muitos outros recursos de alta prioridade com os quais ele competirá por recursos. Certifique-se de votar (👍) para este problema se for importante para você.
This is very slow development on my model with more than 600 entities. I really hope this feature because it's a huge job to refactor all entities to get the compiled model. Thanks

**Comment by viniciusverasdossantos** [comment]
> @viniciusverasdossantos This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 7.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

This is very slow development on my model with more than 600 entities. I really hope this feature because it's a huge job to refactor all entities to get the compiled model. Thanks

**Comment by viniciusverasdossantos** [comment]
thank you very much

**Comment by dneeper** [comment]
I'm using the latest 7.0.1 version of the Microsoft.EntityFrameworkCore.Design, .Proxies and .Relational packages, and have installed the latest 7.0.1 version of the dotnet-ef tool. I've spent the past few days trying to get Lazy Loading proxies to work with the compiled model, without having any luck. Adding .UseModel() to the options builder always results in the poco entity class being returned from EF queries, instead of the Castle proxy. The [What's New In EF Core 7.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew) page claims that Lazy Loading proxies now work with Compiled Models, and I was hoping you could share any insights for setting it up?

```
public class CATSContextFactory : IContextFactory<CATSContext>
{
	public CATSContext Create(string dbConnection, ILoggerFactory loggerFactory = null)
	{
		var serverVersion = ServerVersion.AutoDetect(dbConnection);

		var optionsBuilder = new DbContextOptionsBuilder<CATSContext>()
			.UseMySql(dbConnection, serverVersion)
			.UseLazyLoadingProxies()
			.UseModel(CATSContextModel.Instance)
			.EnableThreadSafetyChecks();

		if (loggerFactory != null)
		{
			optionsBuilder.UseLoggerFactory(loggerFactory);
		}

		return new CATSContext(optionsBuilder.Options);
	}
}

```

**Comment by ajcvickers** [comment]
@dneeper It's working for me--see my test code below. If you're still running into an issue, then please open a _new_ issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Blog
{
    public int Id { get; set; }
    public virtual List<Post> Posts { get; } = new();
}

public class Post
{
    public int Id { get; set; }
    public int? BlogId { get; set; }
    public virtual Blog? Blog { get; set; }
}

public class SomeDbContext : DbContext
{
    public DbSet<Blog> Blogs => Set<Blog>();
    public DbSet<Post> Posts => Set<Post>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseModel(SomeDbContextModel.Instance)
            .UseLazyLoadingProxies()
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
            // await context.Database.EnsureDeletedAsync();
            // await context.Database.EnsureCreatedAsync();

            context.Add(new Post { Blog = new() });

            await context.SaveChangesAsync();
        }

        using (var context = new SomeDbContext())
        {
            var post = context.Posts.First();
            Console.WriteLine(post.GetType());
            Console.WriteLine(post.Blog!.Id);
        }
    }
}
```

**Comment by sccrgoalie1** [comment]
@dneeper It didn't work for us at first either.  Then realized in production we called `UseLazyLoadingProxies`, but in our `IDesignTimeDbContextFactory` we were not.  Once we added that and regenerated the models, all was good.

**Comment by dneeper** [comment]
I did find my problem - I was setting the options and creating the context in the ContextFactory, but, I needed to call `UseLazyLoadingProxies()` in the `OnConfigurating()` method so that the external process that compiled the model would know to use proxies. It works great now!

**Comment by tacktaro** [comment]
> I did find my problem - I was setting the options and creating the context in the ContextFactory, but, I needed to call `UseLazyLoadingProxies()` in the `OnConfiguring()` method so that the external process that compiled the model would know to use proxies. It works great now!

Hi @dneeper , can you help me with the code?

**Comment by MaxwellDAssistek** [comment]
If this issue is resolved, documentation should be updated here: https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Csimple-with-parameter#limitations-1
