### ISSUE TITLE
Seems like CommandTimeout is not reset when services.AddDbContextPool<ApplicationDbContext>

### ISSUE THREAD

**Issue by freerider7777** [dotnet/efcore#24914]
I have .Net Core 3.1 application with Entity Framework Core 5.0.6
I add Context like this:
```
services.AddDbContextPool<ApplicationDbContext>(
 options =>
{
  options.UseNpgsql(connectionString, p => p.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery));
  options.EnableSensitiveDataLogging();
});
```

In some cases (some requests) DbCommandTimeout is set explicitly
```
_dbContext.Database.SetCommandTimeout(timeout)
```
after getting the context, but in the other cases timeout is not set and it's supposed to have default value (30 sec).
But it seems that CommandTimeout is not reset after returning DbContext to the pool - in requests that **do not** explicitly set Timeout I see (under high load) different values of CommandTimeout (instead of 30)

`17.05.2021 11:52:56.944|INFO|Executed DbCommand (15ms) [Parameters=[@__messageId_0='1708184'], CommandType='Text', **CommandTimeout='3'**]`

If I replace AddDbContextPool with AddDbContext - everything works as expected - all records are processed with expected timeouts (where **not set** - 30 seconds)
`17.05.2021 12:10:44.303|INFO|Executed DbCommand (21ms) [Parameters=[@__messageId_0='1708391'], CommandType='Text', **CommandTimeout='30'**]`

**Comment by freerider7777** [comment]
Only in 6? :)

**Comment by roji** [comment]
Reopening to discuss possibly servicing in triage.

**Comment by roji** [comment]
Triage decision - we won't be backporting the fix, mainly because there's an easy workaround (setting the CommandTimeout explicitly).

**Comment by freerider7777** [comment]
Setting explicitly means additional config value or parsing the connection string, not to elegant...
