### ISSUE TITLE
ExecuteSqlRaw return -1

### ISSUE THREAD

**Issue by ByteCraftServices** [dotnet/efcore#24926]
I'm trying to check if a UDT already exists

```
public static bool TypeExists(DbContext dbContext, string typeName, string schema = "dbo")
{
    string sql = @$"Select  1 HAVING TYPE_ID('{schema}.{typeName}') IS NOT NULL";

    return dbContext.Database.ExecuteSqlRaw(sql) > 0; 
}
```
The ExecuteSqlRaw will return -1 in my case. I do not know why it does not return 1 => I've ensured that the UDT exists in the database

The TSQL Select  1 HAVING TYPE_ID('dbo.UDTName') IS NOT NULL will return one line as expected.

I would expect that 0 will be returned if no record exists otherwise the number of record should be returned.
What is causing the return value of -1

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0)
Operating system: Win 10
IDE: Visual Studio 2019 16.9.4

**Comment by roji** [comment]
ExecuteSqlRaw returns the number of rows affected by the SQL command, and not its result - [see the API doc page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlraw?view=efcore-5.0#Microsoft_EntityFrameworkCore_RelationalDatabaseFacadeExtensions_ExecuteSqlRaw_Microsoft_EntityFrameworkCore_Infrastructure_DatabaseFacade_System_String_System_Collections_Generic_IEnumerable_System_Object__). -1 is the expected value for queries, which don't affect any rows.

EF doesn't currently have a direct way of executing a raw SQL query and retrieving a result which isn't an entity in the model (for that, see [raw SQL queries](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)). However, it's very easy to drop down to ADO.NET and perform this yourself, something like the following:

```c#
static bool TypeExists(DbContext dbContext, string typeName, string schema = "dbo")
{
    dbContext.Database.OpenConnection();
    try
    {
        using var cmd = dbContext.Database.GetDbConnection().CreateCommand();
        cmd.CommandText = @$"Select  1 HAVING TYPE_ID('{schema}.{typeName}') IS NOT NULL";
        return (bool)cmd.ExecuteScalar();
    }
    finally
    {
        dbContext.Database.CloseConnection();
    }
}
```

**Comment by roji** [comment]
PS always beware of using string interpolation in SQL - if you `schema` or `typeName` may contain user input, this is vulnerable to SQL injection.

**Comment by ANM86** [comment]
That is the solution I am currently using, but if I try to open the connection a second time. I get a Exception regarding a missing ConnectionString. I've checked this. GetConnectionString() still returns the correct string.

 System.InvalidOperationException : The ConnectionString property has not been initialized.
  Stapelüberwachung: 
    SqlConnection.PermissionDemand()
    SqlConnectionFactory.PermissionDemand(DbConnection outerConnection)
    DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
    DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
    SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
    SqlConnection.Open(SqlConnectionOverrides overrides)
    SqlConnection.Open()

**Comment by roji** [comment]
You probably need to look at [this page](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/) for the various ways to configure your DbContext with a connection string. Your problem most probably isn't related to executing raw SQL - using your context with a regular LINQ query should show the same error.

If you still can't get it to work after reading the docs, please submit a minimal, runnable code sample that shows what you're doing.
