### ISSUE TITLE
Missing required argument '<PROVIDER>' is back in preview 3

### ISSUE THREAD

**Issue by boatcoder** [dotnet/efcore#24929]
## Bug

Using SQLite in any kind of "mixed" environment (or in the preview3 environment doesn't work.  And the error message it gives is just wrong.  I've tried it with all preview3 components with some preview3 components, but the only way it works if if you remove all the preview components and run the old stuff.  So your new shiny version is busted.

### Include your code

The app I used for this is just a plain console app created by Rider, doesn't have any of my code in it.  I drop in the `Sqllite` file and issue the command  and it fails.

When Microsoft.EntityFramework.Design is missing you get a legit and understandable message.  If you don't get the connection string right, the message is valid, but if you get all that correct, the next error is just misleading.  

```bash
/private/tmp/scrapapp/ConsoleApp1 $ dotnet ef dbcontext scaffold "Data Source=../dggt.db;" Microsoft.EntityFrameworkCore.Sqlite --context-dir ./ef --context testdb --verbose --output-dir ./entities

Using project '/private/tmp/scrapapp/ConsoleApp1/ConsoleApp1.csproj'.
Using startup project '/private/tmp/scrapapp/ConsoleApp1/ConsoleApp1.csproj'.
Writing '/private/tmp/scrapapp/ConsoleApp1/obj/ConsoleApp1.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/var/folders/j0/_h3b8hwj3ylg96ww2jrz7rrh0000gn/T/tmpchhXoz.tmp /verbosity:quiet /nologo /private/tmp/scrapapp/ConsoleApp1/ConsoleApp1.csproj
Writing '/private/tmp/scrapapp/ConsoleApp1/obj/ConsoleApp1.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/var/folders/j0/_h3b8hwj3ylg96ww2jrz7rrh0000gn/T/tmpURdsfM.tmp /verbosity:quiet /nologo /private/tmp/scrapapp/ConsoleApp1/ConsoleApp1.csproj
Build started...
dotnet build /private/tmp/scrapapp/ConsoleApp1/ConsoleApp1.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.42
Build succeeded.
dotnet exec --depsfile /private/tmp/scrapapp/ConsoleApp1/bin/Debug/net5.0/ConsoleApp1.deps.json --additionalprobingpath /Users/mark/.nuget/packages --runtimeconfig /private/tmp/scrapapp/ConsoleApp1/bin/Debug/net5.0/ConsoleApp1.runtimeconfig.json /Users/mark/.dotnet/tools/.store/dotnet-ef/6.0.0-preview.1.21102.2/dotnet-ef/6.0.0-preview.1.21102.2/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll dbcontext scaffold ../dggt.db Microsoft.EntityFrameworkCore.Sqlite --context-dir ./ef --context testdb --output-dir ./entities --assembly /private/tmp/scrapapp/ConsoleApp1/bin/Debug/net5.0/ConsoleApp1.dll --startup-assembly /private/tmp/scrapapp/ConsoleApp1/bin/Debug/net5.0/ConsoleApp1.dll --project-dir /private/tmp/scrapapp/ConsoleApp1/ --language C# --working-dir /private/tmp/scrapapp/ConsoleApp1 --verbose --root-namespace ConsoleApp1
Microsoft.EntityFrameworkCore.Tools.CommandException: Missing required argument '<PROVIDER>'.
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Validate()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Missing required argument '<PROVIDER>'.
```

**To get this to work, I had to use this version:**
/private/tmp/scrapapp/ConsoleApp1 $ dotnet tool install --global dotnet-ef
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '5.0.6') was successfully installed.
**And the nuget packages shown below.  Mixing in any or all parts of 6.0.0.preview.3.21201.2 fails with this error on the same project.**
### provider and version information

![image](https://user-images.githubusercontent.com/18578897/118671903-771ca500-b7bd-11eb-85ee-d2581ed5c152.png)

![image](https://user-images.githubusercontent.com/18578897/118672040-90255600-b7bd-11eb-8eb5-a22d36dcdf10.png)

![image](https://user-images.githubusercontent.com/18578897/118672199-af23e800-b7bd-11eb-8ad1-26e461f3b2fc.png)

**Comment by ErikEJ** [comment]
The .Design package is old and obsolete

**Comment by boatcoder** [comment]
So why not display THAT error message?  Why give some meaningless error instead?

**Comment by AndriySvyryd** [comment]
It's an issue inherit in the approach using by our tooling where the assemblies are decoupled, but provide backwards compatibility (new .Design with older runtime)
