### ISSUE TITLE
How to use only one instance of a tracked immutable entity

### ISSUE THREAD

**Issue by robertlarkins** [dotnet/efcore#24923]
This question is about what or whether there is a good way of telling the context to use only a particular instance of an immutable entity in the context, as it is producing an _EF Core instance of entity type cannot be tracked_ error, I know there are a number of issues pertaining to this, but havn't seen a good solution on how to avoid this when using statically defined entities.

(I suspect this relates to this issue: https://github.com/dotnet/efcore/issues/20124)

I have these two entities (using [vkhorikovs Entity class](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/Entity/Entity.cs)):
```C#
public class AppointmentStatus : Entity<int>
{
	public static readonly AppointmentStatus Planned = new(1, "Planned");
	public static readonly AppointmentStatus Occurring = new(2, "Occurring");
	public static readonly AppointmentStatus Finished = new(3, "Finished");

	protected AppointmentStatus()
	{
	}

	private AppointmentStatus(int id, string name) : base(id)
	{
		Name = name;
	}

	public string Name { get; } = string.Empty;

	public static List<AppointmentStatus> GetAll()
	{
		return new()
		{
			Planned,
			Occurring,
			Finished
		};
	}
}
```
and
```C#
public class Appointment : Entity<int>
{
	public Appointment(AppointmentStatus appointmentStatus)
	{
		AppointmentStatus = appointmentStatus;
	}

	protected Appointment()
	{
	}

	public AppointmentStatus AppointmentStatus { get; private set; } = null!;

	public void SetStatus(AppointmentStatus appointmentStatus)
	{
		AppointmentStatus = appointmentStatus;
	}
}
```
From reading and my (limited) understanding what is happening is some query pulls the static defined variable into the context (say `AppointmentStatus.Finished` in this case), such as when getting all the Appointments, so this become the instance known to the context, but when updating an appointment to `AppointmentStatus.Finished` from the static reference in `AppointmentStatus`, this becomes a second instance tracked by the context. EF then sees these as two separate instances for the same thing (even though they are the same, and immutable), as EF determines equivalency by reference equals.

This is the solution with tests to show this in action: https://github.com/robertlarkins/efcore-cannot-track-entity-issue

What would be the best way of telling the context to only use one of the instances and ignore the other?

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.InMemory and Microsoft.EntityFrameworkCore.Sqlite (both v5.0.5) - would ideally be using this against NpgSql, but for the demo solution using inmemory.
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.5

**Comment by TonyValenti** [comment]
I don't think you can do what you're wanting.  However, you might consider creating extension methods like ```IsPlanned``` or ```IsOccurring``` that determine whether an instance matches what you want.

Alternatively, it looks like you're basically just storing an enum in the database.  In that case, why not just store it as an enum?

**Comment by AndriySvyryd** [comment]
@robertlarkins As you've said #20124 should enable this scenario

**Comment by robertlarkins** [comment]
Thanks for you suggestions @TonyValenti, in this case I was following articles like this
 - https://fanzootechnology.com/blog/static-entity-implementation-with-domain-driven-design/
 - https://enterprisecraftsmanship.com/posts/reference-data-as-code/
I guess at this stage I use some work arounds and hope that EFCore gets this capability in the not to distant future.
