### ISSUE TITLE
Understanding `The navigation '...' was ignored from 'Include' in the query since the fix-up will automatically populate it...` and dealing with it

### ISSUE THREAD

**Issue by NatanBagrov** [dotnet/efcore#24924]
## Ask a question

**Edit:**
related info - 
https://github.com/dotnet/efcore/pull/24225
https://github.com/dotnet/efcore/issues/23674

Hello,
I'm receiving this warning since updating to 5.0.6 (think it was from 5.0.2):
```
The navigation 'PurchasingRecordLine.ContainingRecord' was ignored from 'Include' in the query since the fix-up will automatically populate it. If any further navigations are specified in 'Include' afterwards then they will be ignored. Walking back include tree is not allowed.
```

I'm not sure I understand it.

My models are `PurchasingRecord` which has many `PurchasingRecordLine`s which have many `PurchasingRecordLineAction`s. Every entity has also a navigation to the parent.

```c#

class PurchasingRecord {
    ...
    List<PurchasingRecordLine> Lines { get; set; }
    ...
}

class PurchasingRecordLine {
    ...
    List<PurchasingRecordLineAction> Actions { get; set; }
    PurchasingRecord ContainingRecord { get; set; }
    Guid ContainingRecordId { get; set; }
    ...
}

class PurchasingRecordLineAction{
    ...
    PurchasingRecordLine ContainingRecordLine { get; set; }
    Guid ContainingRecordLineId { get; set; }
    ...
}

```

When querying - it looks like this:
```c#
    Context.Set<TDepartmentRecord>()
    .Include(r => r.AssociatedUser)
    .Include(r => r.Lines)
        .ThenInclude(l => l.Actions)
        .ThenInclude(rs => rs.NextActions)
    .Include(r => r.Lines)
        .ThenInclude(l => l.ContainingRecord)
    ...
```
Questions and concerns:

1. What I understand from the warning is: `.Include(r => r.Lines).ThenInclude(l => l.ContainingRecord)` is redundant since `l.ContainingRecord` is to be populated anyway. Is that correct?
2. If this property (`l.ContainingRecord`) is *not* being included - what should I do to include it?
3. If I understood correctly, in order to get rid of these warnings - Should I just omit this inclusion?
4. Is there any configuration to provide more info about the *location* of the warning, because I have plenty of queries...

Thanks!

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0.6
Operating system: W10 x64
IDE: Rider 2021.1

**Comment by smitpatel** [comment]
1. Yes
2. It is being included due to fix-up no matter Include is written or not.
3. To avoid warnings you can remove the `Include` which is populating navigation back to parent which will be shown in the warning.
4. No easy way for us to provide location. We will discuss in team meeting.

**Comment by AndriySvyryd** [comment]
https://github.com/dotnet/efcore/issues/15127 would help identifying the query

**Comment by NatanBagrov** [comment]
> 1. Yes
> 2. It is being included due to fix-up no matter Include is written or not.
> 3. To avoid warnings you can remove the `Include` which is populating navigation back to parent which will be shown in the warning.
> 4. No easy way for us to provide location. We will discuss in team meeting.

Can you please elaborate on this "fix-up"? it sound vague.
I guess it "connects" the relevant entities...

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/change-tracking/relationship-changes#relationship-fixup
