### ISSUE TITLE
Investigate removing IndentedStringBuilder

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#2492]

**Comment by bricelam** [comment]
:+1: The only reason we had our own in EF6 was to support partial trust scenarios.

**Comment by smitpatel** [comment]
One alternative to IndentedStringBuilder is `IndentedTextWriter' which is not available for UWP or DNX 5.0
https://msdn.microsoft.com/en-us/library/system.codedom.compiler.indentedtextwriter
Clearing flags for re-triage.

**Comment by bricelam** [comment]
(Just the milestone needs to be cleared.)

**Comment by rowanmiller** [comment]
In triage we decided just to keep what we have
