### ISSUE TITLE
Support inline Table Valued Parameter without User Defined Type

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#24928]
#The Problem:

I'm trying to replace slow `WHERE IN (...)` produced by following code:

```csharp
int[] blogIds = ....
dbContext.Blogs.Where(blog => blogIds.Contains(blog.Id));
```

with JOIN on table valued parameter:

```csharp
var dataTable = new DataTable();
dataTable.Columns.Add("Id", typeof(int));
foreach (var id in blogIds)
{
   dataTable.Rows.Add(id);
}
var parameter = new SqlParameter("@ids", SqlDbType.Structured);
parameter.Value = dataTable;
//parameter.TypeName = "dbo.IdTable"; I don't want this
return dbContext.FromSqlRaw("SELECT * FROM [Blogs] b INNER JOIN @ids item ON [b].[BlogId]=[item].[Id]", parameter);
```

Currently I have to define the parameter.TypeName as existing user defined type, but IMHO it is should not be mandatory.

# The Solution

The parameter type can be declared inline:

```sql
DECLARE @param1 TABLE(Id INT)
```

**Comment by roji** [comment]
I'm not 100% familiar with SQL Server TVPs, but I don't think this is a good idea. For one thing, it seems you're suggesting that the database type (INT above) can be inferred from the CLR type of the DataTable column, but that's not always the case: there may be multiple database types corresponding to the same CLR type. For example, what we we do with CLR string, `nvarchar(max)`? `nvarchar(10)`? `xml`?).

Another problem here, is that if what you propose is indeed safe, then SqlClient could be doing this at a lower level - EF Core doesn't have any more extra information here at its level that allow it to perform the task better.

At the end of the day, EF Core doesn't attempt to do "magic" in its raw SQL support - the goal is to allow users to write raw queries, and to expose the lower-level ADO.NET APIs when that's necessary (which is how you can use SqlParameter above).
