### ISSUE TITLE
IsTemporary not properly set when using DatabaseGenerated(DatabaseGeneratedOption.Computed) attribute

### ISSUE THREAD

**Issue by alexandrejobin** [dotnet/efcore#24930]
I need to use the IsTemporary property on the ChangeTrack object to get the old and new values of a database generated field. Here's the model that I use:

```C#
[Table("Book")]
public class Book
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int BookId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public decimal RandomNumber { get; set; }
}
```

My understanding is that if you put the `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]` the attribute on a property, the IsTemporary of the `RandomNumber` property should be set to true but this is not the case.

Is it an issue or this is the normal behavior?

### provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9

**Comment by AndriySvyryd** [comment]
@alexandrejobin `IsTemporary` is only set for PK properties before the entity is saved to the database, indicating that the value can still be changed.
