### ISSUE TITLE
library for filtering by expression

### ISSUE THREAD

**Issue by dpr-dev** [dotnet/efcore#24945]
Hi. Are you planning to develop a client and server library for filtration / sorting entities with EF Core by  expression (passed from the query string or body) ? It would be great if EF Core had this feature "out of the box" like dev express (https://docs.devexpress.com/WindowsForms/2567/controls-and-libraries/data-grid/filter-and-search/advanced-filter-and-search-concepts#expressions)

I have found the library that provides similar functionality https://github.com/Biarity/Sieve#fluent-api

**Comment by roji** [comment]
@dpr-dev we don't have any such plans currently. There are already various technologies out there for accepting queries over the web (I'm thinking of GraphQL, OData), and these are already well-integrated with EF Core. I'd recommend looking at those
