### ISSUE TITLE
Removing then adding back a many-to-many relationship deletes it from DB

### ISSUE THREAD

**Issue by jods4** [dotnet/efcore#24947]
### Include your code

Consider a many-to-many relationship between `Blog` and `Tag`.
If you do the following:

```C#
// Load blog with id = 1
var blog = db.Blogs.Find(1);
// Load its tags, assume there's one with id = 1
db.Entry(blog).Navigation("Tags").Load(); 
// Remove the tag with Id = 1 from the many-to-many relationship
blog.Tags.Clear();
// Now put it back
blog.Tags.Add(db.Tags.Find(1));
// Save changes: the tags is gone
db.SaveChanges();
// Funny thing is:
blog.Tags.Count == 1; // Although this is not true in DB anymore.
```

### Include provider and version information

EF Core version: 5.0.6
Database provider: Oracle.ManagedDataAccess.Core
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019 16.9.1

**Comment by jods4** [comment]
BTW I would love to attach a TrackGraph that includes many-to-many relationships. 
Not sure if this is a question, which I asked here https://stackoverflow.com/questions/67626840/ef-core-5-trackgraph-update-many-to-many-relationship, or if I should open a bug for that as well.

**Comment by AndriySvyryd** [comment]
@jods4 Please create a small repro project that shows this issue, preferably with a different database provider.

I'm not able to reproduce it on SQL Server:
```C#
[ConditionalFact]
public virtual void Issue24947()
{
    using (var context = Fixture.CreateContext())
    {
        var left = context.Set<EntityOne>().Find(3);

        context.Entry(left).Collection(e => e.TwoSkip).Load();

        Assert.Equal(7, left.TwoSkip.Count);

        var twos = left.TwoSkip.ToList();

        left.TwoSkip.Clear();

        foreach (var entityTwo in twos)
        {
            left.TwoSkip.Add(context.Set<EntityTwo>().Find(entityTwo.Id));
        }

        Assert.Equal(7, left.TwoSkip.Count);

        context.SaveChanges();

        Assert.Equal(7, left.TwoSkip.Count);
    }

    using (var context = Fixture.CreateContext())
    {
        var left = context.Set<EntityOne>().Find(3);

        context.Entry(left).Collection(e => e.TwoSkip).Load();

        Assert.Equal(7, left.TwoSkip.Count);
    }
}
```

**Comment by jods4** [comment]
Strange, that's exactly what I did.
Do you think that behavior could be provider specific?

As I mentioned in the issue, I'm not using SQL Server but rather the official Oracle managed provider.

**Comment by AndriySvyryd** [comment]
Yes, if you can't repro it with SQL Server, then it's provider-specific and you need to contact Oracle.

**Comment by jods4** [comment]
Sorry for not getting back to you.

I don't have a SQL Server handy and I unfortunately don't have the bandwidth right now to investigate further.

On my project we have worked around this problem by doing things another way, so this is not a priority for us.

Without actionnable repro I suppose closing is the only thing left to do.
Thanks for having looked into it.
