### ISSUE TITLE
InMemoryProvider and Model initialization

### ISSUE THREAD

**Issue by joelmandell** [dotnet/efcore#24958]
Hey friends!

I have implemented an Interceptor that takes the commands and proxies them trough a secure channel and builds the result with a DbDataReader implementation.

For the moment I am using the Sql Server as provider for EF Core. But because the data fetching is handled by a proxy instead it seems unnecessary. I tried to change to use an InMemoryProvider, but it throws exception that the Model is not initialized.
Because EF Core is "only" going to take care of generating SQL. and other things, how can I trigger an dummy initializion?

Do you have any idea on how to fix this?

**Using:**
EF Core version:
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 5.0

**Comment by ajcvickers** [comment]
@joelmandell The provider used determines the flavor of SQL generated, as well as other provider-specific behaviors. This means you will need to use the SQL Server provider, even if you don't connect directly to SQL Server.

**Comment by joelmandell** [comment]
@ajcvickers Well that makes total sense. Did not think about that 😅. Well I will use an dummy sql-db in this case then.
