### ISSUE TITLE
Outdated documentation in DBContext.SaveChanges().

### ISSUE THREAD

**Issue by tengr** [dotnet/efcore#24959]
https://github.com/dotnet/efcore/blob/main/src/EFCore/DbContext.cs#L507-L547 it doesn't throw `DBUpdateException` anymore.

Should the documentation be updated? https://github.com/dotnet/efcore/blob/main/src/EFCore/DbContext.cs#L499-L501

**Comment by ErikEJ** [comment]
I think .StateManager.SaveChanges throws DbUpdateException

**Comment by roji** [comment]
DbUpdateException is definitely thrown from SaveChanges if any error occurred that prevented the changes from being saved.
