### ISSUE TITLE
Add a .editorconfig to the Migrations folder

### ISSUE THREAD

**Issue by dxrdxr** [dotnet/efcore#24961]
When I add a Migration, the generated code invariably does not match the style of the project I am working on. Depending on the project .editorconfig (or VS settings) this will generate messages, warnings, or in some cases errors.

This is a big waste of time to have to edit Migration files to remove warnings that I otherwise will not (or minimally) edit.

### Solution

When creating the Migrations folder, add a default .editorconfig that matches the default style used by the efcore code generator.

This is the least intrusive solution as it breaks no existing code.

**Comment by ajcvickers** [comment]
@dxrdxr Have you tried dropping an empty `.editorconfig` into the appropriate folder? As I understand it, this should cause the build to use default configuration for these files, rather than your custom configuration.

Also, you might consider using a tool that does automatic code-cleanup.

**Comment by dxrdxr** [comment]
@ajcvickers Good feedback. I would then modify my suggestion to drop an empty `.editorconfig` in the Migrations folder when it is created.

**Comment by roji** [comment]
@dxrdxr we discussed this internally, and we're not convinced this is something that EF Core should do for users by default. Migration code has a code-generated part which users shouldn't touch, but it also has code which is "scaffolded", and can be edited by users. Some users view this as part of their project like other source files, and would prefer coding standards to apply there as well.

It basically seems like users who just want to suppress all the warnings can just drop the empty .editorconfig in themselves, as suggested above; it's a simple, one-time action when first bootstrapping migrations.

**Comment by TomBarten** [comment]
@dxrdxr another option you have is to create a new 'migration' project that has no `.editorconfig` file. You will have to configure your database provider to use that new 'migration' project as its migration assembly.

For further reference see: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli

Hope this might help you further.
