### ISSUE TITLE
TPT with table splitting fails to insert dependent

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#24970]
See `TPTTableSplittingSqlServerTest.Can_insert_dependent_with_just_one_parent`. Currently this test doesn't verify the dependent was inserted.

**Comment by ajcvickers** [comment]
Investigated this; it isn't fixed. `FuelTank` is shared a table with `CombustionEngine`, but there is no `CombustionEngine` in the entities being inserted. The update pipeline therefore never updates the `ModificationCommand` from the default `Modified` state, and attempts this:

```sql
UPDATE "CombustionEngines" SET "Capacity" = @p0, "FuelType" = @p1
WHERE "VehicleName" = @p2
RETURNING 1;
```

Which, not surprisingly, throws an optimistic concurrency exception.

It seems to me that this is a negative case that should throw a better exception, but there is a lot going on here (TPT and table-splitting), so maybe I am missing something.

Everything works if `CombustionEngine` is included in the entities inserted:

```C#
context.Add(
    new PoweredVehicle
    {
        Name = "Fuel transport",
        SeatingCapacity = 1,
        Operator = new LicensedOperator { Name = "Jack Jackson", LicenseType = "Class A CDC" }
    });
context.Add(
    new FuelTank
    {
        Capacity = 10000_1,
        FuelType = "Gas",
        VehicleName = "Fuel transport"
    });
context.Add(
    new ContinuousCombustionEngine
    {
        VehicleName = "Fuel transport",
        Description = "Engine"
    });
context.SaveChanges();
```

```sql
INSERT INTO "Vehicles" ("Name", "SeatingCapacity", "Operator_Name")
VALUES (@p0, @p1, @p2);
INSERT INTO "LicensedOperators" ("VehicleName", "LicenseType")
VALUES (@p0, @p1);
INSERT INTO "PoweredVehicles" ("Name", "Computed", "Description")
VALUES (@p0, @p1, @p2);
INSERT INTO "CombustionEngines" ("VehicleName", "Capacity", "FuelType")
VALUES (@p0, @p1, @p2);
INSERT INTO "ContinuousCombustionEngines" ("VehicleName")
VALUES (@p0);
```

**Comment by AndriySvyryd** [comment]
This is by design. Inserting a table-splitting dependent without principal is an update operation, it's up to the user to ensure that the principal exists in the database. We cannot detect this case without loading more data to throw a better exception.
