### ISSUE TITLE
Add support for DateOnly and TimeOnly types

### ISSUE THREAD

**Issue by JohnyL** [dotnet/efcore#24979]
As of .NET 6 Preview 4, new `DateOnly` and `TimeOnly` types [were added](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4//#new-dateonly-and-timeonly-structs). However, in EF Core 6 Preview 4 I get the following error (I use SQL Server):
> System.InvalidOperationException: 'The property 'Product.DateAdd' is of type 'DateOnly' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'

**Comment by ErikEJ** [comment]
Duplicate, and not yet implemented.

**Comment by roji** [comment]
Duplicate of #24507

**Comment by roji** [comment]
Duplicate of #24506
