### ISSUE TITLE
[Question]How to update entity model mapping in runtime?

### ISSUE THREAD

**Issue by Flithor** [dotnet/efcore#24986]
I have a table (T1) that allow user to add some custom columns during running time.
The custom columns info will be recorded in another table (T2).
I hope I can use the shadow property to access these custom columns to execute queries by EF Core and linq.
But shadow property requires mapping.
I did not find a way to "Get column information from one table (T2) and update the model mapping of another table (T1) based on the obtained column information".

I've tried to employ `ModelBuilder`, but it cannot work out of `OnModelCreating`.
The solutions on the Internet are "regenerate all model mapping", but I hope to "update part of the property mapping of the specified table".

Is there a way to do this?

**Comment by ajcvickers** [comment]
@Flithor There isn't anyway to do this that I am aware of. You could try extracting all this information from the tables manually and then using it to build an EF model, but it would be a lot of work and I wouldn't recommend it.

**Comment by Flithor** [comment]
Now I have tried to use a random GUID as schema cache key to switching on update the model mapping (use `IModelCacheKeyFactory` to create a new model schema cache).
So here comes the question: how should I remove these old schema caches that will never be used again?

**Comment by Flithor** [comment]
I did it:
I'm not found a way to remove the model cache which managed by framework, but I can manage model cache which create by myself outside of the framework.
```
partial class jitonarchivesContext
{
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // use my model cache if exsits, than it will not call the OnModelCreating
        if (modelCache != null)
            optionsBuilder.UseModel(modelCache);
    }

    // ConventionSet Cache, use on create ModelBuilder
    static ConventionSet defalutConventionSet;
    //
    static IModel modelCache;

    public static void UpdateModelCache()
    {
        var mb = new ModelBuilder(defalutConventionSet);
        CreateModel(mb);
        modelCache = mb.FinalizeModel();
    }
    // call OnModelCreating at first time, I need get ConventionSet of current database service provider
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        if (defalutConventionSet == null)
            defalutConventionSet = this.GetService<IConventionSetBuilder>().CreateConventionSet();
        CreateModel(modelBuilder);
    }

    private static void CreateModel(ModelBuilder modelBuilder)
    {
        // build model

        // set MyModel.CustomFields after fisrt initialization and call the UpdateModelCache
        if (MyModel.CustomFields != null)
        {
            // mapping custom fields
        }
    }
}
```
