### ISSUE TITLE
Unable to use Model.ToDebugString with EF Core 6 preview 4

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#24987]
### Include your code

```C#
var result =dbContext.Model.ToDebugString(MetadataDebugStringOptions.LongDefault);
```

And I am not able to find "DesignTimeModel" mentioned in the error message anywhere.

### Include stack traces

```
System.InvalidOperationException: The requested configuration is not stored in the read-optimized model, please use 'DbContext.DesignTimeModel'.
   at Microsoft.EntityFrameworkCore.Metadata.SlimModel.Microsoft.EntityFrameworkCore.Metadata.IReadOnlyModel.GetChangeTrackingStrategy()
   at Microsoft.EntityFrameworkCore.Metadata.IReadOnlyModel.ToDebugString(MetadataDebugStringOptions options, Int32 indent)
   at Modelling.EfCoreModelBuilder.BuildResult(String outputPath, String startupOutputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\EFCoreModelBuilder.cs:line 41
   at Modelling.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt30.core\Program.cs:line 57
```

### Include provider and version information

EF Core version: 6.0 preview 4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by ErikEJ** [comment]
Did some spelunking, and found this: https://github.com/dotnet/efcore/commit/3be1be44b5f746ca060612e6fcba12ab3cfa2649 
So this works:

`dbContext.GetService<IDesignTimeModel>().Model.ToDebugString(MetadataDebugStringOptions.LongDefault);`

I guess the issue is about updating the error message then.

**Comment by AndriySvyryd** [comment]
Fixed in a60795c94b6fc071f1247474793bcf1adf8eaff8

**Comment by ErikEJ** [comment]
@AndriySvyryd I most likely misunderstand, but what exactly was fixed in the linked 125 file PR?
I still do not see DbContext.DesignTimeModel in preview 5 !?

**Comment by ErikEJ** [comment]
Ping?

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd I most likely misunderstand, but what exactly was fixed in the linked 125 file PR?

Sorry, the specific fix is `this is Model` condition in https://github.com/dotnet/efcore/commit/a60795c94b6fc071f1247474793bcf1adf8eaff8#diff-5f6aa389ba014558ff3ca0fe47cd2c69a874c34e32f4e7ee4d7c7b4841f36748

> I still do not see DbContext.DesignTimeModel in preview 5 !?

Now it's `context.GetService<IDesignTimeModel>().Model`, see https://github.com/dotnet/EntityFramework.Docs/issues/3030

**Comment by ErikEJ** [comment]
@AndriySvyryd  Thanks :-)

**Comment by jcummings2** [comment]
> Did some spelunking, and found this: [3be1be4](https://github.com/dotnet/efcore/commit/3be1be44b5f746ca060612e6fcba12ab3cfa2649) So this works:
> 
> `dbContext.GetService<IDesignTimeModel>().Model.ToDebugString(MetadataDebugStringOptions.LongDefault);`
> 
> I guess the issue is about updating the error message then.

For those like me who encountered this issue later, you may also need to add:

    using Microsoft.EntityFrameworkCore.Infrastructure;

line to find the correct extension method.
