### ISSUE TITLE
Investigate strange behavior on Release x64

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#2499]
If  4f5b718 is reverted tests start failing on Release x64 build.

**Comment by rowanmiller** [comment]
@AndriySvyryd anything for us to do here?

**Comment by AndriySvyryd** [comment]
We need to investigate whether it's us and forward the issue if it isn't.

**Comment by rowanmiller** [comment]
This isn't a priority for us since it's external and we have a workaround.
