### ISSUE TITLE
Using 'Include' for loading related data for types that in hierarchy produces LEFT JOIN with an expensive execution plan

### ISSUE THREAD

**Issue by tatarincev** [dotnet/efcore#24998]
## Ask a question

It seems the EF Core produces the slow-down LEFT JOIN for `Include` statements if an include statement contains types that in the hierarchy.

Let’s say we have one base class `AddressEntity` and one derived class  `AddressEntity2:  AddressEntity`.
Both types are registered in dbCOntext via Fluent API and are mapped to the one `OrderAddress` table (TPH) that has the `Discriminator` column.

Let's say we have the next EF query:
```C#
InPayments.Where(x => ids.Contains(x.CustomerOrderId))
.Include(x => x.Addresses).Load();
```
EF Core converts  this query to the following SQL command:
```SQL
SELECT [o].[Id] ...
FROM [OrderPaymentIn] AS [o]
LEFT JOIN (
    SELECT [o2].[Id] ...
    FROM [OrderAddress] AS [o2]
    WHERE [o2].[Discriminator] IN (N'AddressEntity', N'AddressEntity2')
) AS [t0] ON [o].[Id] = [t0].[PaymentInId]
WHERE [o].[CustomerOrderId] IN (N'774c4296c2614c5686042430ec63506a')
ORDER BY [o].[Id]
```
The resulting execution plan for this query looks very expensive 

![image](https://user-images.githubusercontent.com/7566324/120003369-f7b97d80-bfd5-11eb-9407-c06ae8e2a1d8.png)

because `LEFT JOIN` contains the `SELECT` for all records from the  `OrderAddress` table, which leads to bad performance for query execution and high resource utilization on the SQL server.

My question is this expected behavior for loading related data in inheritance hierarchy via `Include` statement? 
How I can optimize the resulting SQL query to avoid such an expensive LEFT JOIN?

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@tatarincev The implementation of [complete discriminator mappings](https://github.com/dotnet/efcore/issues/18106) in EF Core 5.0 should result in no clause for `WHERE [o2].[Discriminator] IN (N'AddressEntity', N'AddressEntity2')` in the query. Can you try with EF Core 5.0 and report back if you are still seeing an issue.

**Comment by AndriySvyryd** [comment]
I'm closing this as resolved. Feel free to comment if this is still an issue in EF Core 5.0.
