### ISSUE TITLE
Unnecessary null check for StartsWith

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25010]
```c#
_ = await ctx.Blogs
    .Where(b => b.Name.StartsWith("hello"))
    .ToListAsync();
```

SQL:

```sql
SELECT [b].[id], [b].[name]
FROM [blogs] AS [b]
WHERE [b].[name] IS NOT NULL AND ([b].[name] LIKE N'hello%')
```

/cc @maumar

**Comment by roji** [comment]
Ah, seems like [that bit in QueryOptimizingExpressionVisitor](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs#L78) I always forget (and complain) about.

**Comment by ranma42** [comment]
Currently EFCore emits
```sql
SELECT [b].[BlogId], [b].[Name]
FROM [Blogs] AS [b]
WHERE [b].[Name] LIKE N'hello%'
```
as it should :)

**Comment by roji** [comment]
Thanks @ranma42! Done as part of #31482
