### ISSUE TITLE
Microsoft.EntityFrameworkCore.Tools - Azure Functions with .NET 5 (Isolated) Design-time DbContext Creation with HostBuilder

### ISSUE THREAD

**Issue by Ogglas** [dotnet/efcore#25036]
I have created a new `FunctionApp` in `Visual Studio Version 16.10.0` using the template `Azure Functions` with `.NET 5 (Isolated)` and `Http trigger`.

[![enter image description here][1]][1]

I have then created the following files:

Blog.cs

    public class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

ApplicationDbContext.cs

    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(
            DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<Blog> Blogs { get; set; }
    }

Program.cs

    public class Program
    {
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(services =>
                {
                    var connectionString = Environment.GetEnvironmentVariable("ConnectionStrings:DefaultConnection");
                    services.AddDbContext<ApplicationDbContext>(options =>
                            options.UseSqlServer(
                            connectionString,
                            sqlServerOptions => sqlServerOptions.CommandTimeout(600)));
                })
                .Build();

            host.Run();
        }
    }

Function1.cs

    public class Function1
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public Function1(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        [Function("Function1")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req,
            FunctionContext executionContext)
        {
            var logger = executionContext.GetLogger("Function1");
            logger.LogInformation("C# HTTP trigger function processed a request.");

            var connectionString = _applicationDbContext.Database.GetDbConnection().ConnectionString;

            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            response.WriteString("Welcome to Azure Functions!");

            return response;
        }
    }

local.settings.json:

    {
      "ConnectionStrings": {
        "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=FunctionApp1.Test;Trusted_Connection=True;MultipleActiveResultSets=true"
      },
      "IsEncrypted": false,
      "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
      }
    }

host.json

    {
        "version": "2.0",
        "logging": {
            "applicationInsights": {
                "samplingSettings": {
                    "isEnabled": true,
                    "excludedTypes": "Request"
                }
            }
        }
    }

I have verified that dependency injection works from `Program.cs` -> `new HostBuilder`

[![enter image description here][2]][2]

If I run `Add-Migration InitialCreate` in Package Manager Console I get the following error:

> Unable to create an object of type 'ApplicationDbContext'. For the
> different patterns supported at design time, see
> https://go.microsoft.com/fwlink/?linkid=851728

https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs

https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=vs

To obtain the DbContext object from the application's service provider the example code looks like this:

    public class Program
    {
        public static void Main(string[] args)
            => CreateHostBuilder(args).Build().Run();
    
        // EF Core uses this method at design time to access the DbContext
        public static IHostBuilder CreateHostBuilder(string[] args)
            => Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(
                    webBuilder => webBuilder.UseStartup<Startup>());
    }
    
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
            => services.AddDbContext<ApplicationDbContext>();
    
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
        }
    }
    
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }

> The tools first try to obtain the service provider by invoking
> Program.CreateHostBuilder(), calling Build(), then accessing the
> Services property.

Is there anyway to make Tools work with HostBuilder instead?

  [1]: https://i.stack.imgur.com/sEUYb.png
  [2]: https://i.stack.imgur.com/gnzEM.png

### Include provider and version information

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.10.0

**Comment by AndriySvyryd** [comment]
cc: @bricelam

**Comment by bricelam** [comment]
> Is there anyway to make Tools work with HostBuilder instead?

The key is having the `CreateHostBuilder` method. The contents don't really matter to EF. This should work just fine:

```cs
public class Program
{
    public static void Main(string[] args)
    {
        var host = CreateHostBuilder(args)
            .Build();

        host.Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args)
        => new HostBuilder()
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureServices(services =>
            {
                var connectionString = Environment.GetEnvironmentVariable("ConnectionStrings:DefaultConnection");
                services.AddDbContext<ApplicationDbContext>(options =>
                        options.UseSqlServer(
                        connectionString,
                        sqlServerOptions => sqlServerOptions.CommandTimeout(600)));
            });
}
```

**Comment by Ogglas** [comment]
@bricelam Causes the exception below when adding a new migration:

> System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')

I guess this is expected since environment variables are not present when running via `Package Manager Console`. I can not use code like this either:

```
$ConnectionStrings.DefaultConnection="Server=tcp:mySqlServerStuffxxx"
Add-Migration InitialCreate
```

Will result in the following error:

> The property 'DefaultConnection' cannot be found on this object. Verify that the property exists and can be set.

https://stackoverflow.com/a/67822243/3850405

I can get migrations working like this but it would be nice to use `public static IHostBuilder CreateHostBuilder(string[] args)`:

    public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("local.settings.json")
                .Build();

            var connectionString = configuration.GetConnectionString("DefaultConnection");

            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseSqlServer(connectionString);

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }

I then tried to use `-Args` as mentioned in MS Docs for `IDesignTimeDbContextFactory`.

https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=vs#args

    var connectionString = args[0];

With this I could add a new migration and it looked good.

    Add-Migration InitialCreate -Args 'Server=(localdb)\\mssqllocaldb;Database=FunctionApp1.Test;Trusted_Connection=True;MultipleActiveResultSets=true'

However when running `Update-Database` it fails with the following error:

> Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related
> or instance-specific error occurred while establishing a connection to
> SQL Server. The server was not found or was not accessible. Verify
> that the instance name is correct and that SQL Server is configured to
> allow remote connections. (provider: SNI_PN11, error: 50 - Local
> Database Runtime error occurred. Specified LocalDB instance name is
> invalid.

    Update-Database -Args 'Server=(localdb)\\mssqllocaldb;Database=FunctionApp1.Test;Trusted_Connection=True;MultipleActiveResultSets=true'

If I either hard code the exact same value or get the value from `ConfigurationBuilder` everything works with these settings.

    var connectionString = "Server=(localdb)\\mssqllocaldb;Database=FunctionApp1.Test;Trusted_Connection=True;MultipleActiveResultSets=true";

[![enter image description here][2]][2]

**Comment by bricelam** [comment]
A few comments:
* You set environment variables in PowerShell using `$env:NAME=VALUE`
* `\` is not an escape sequence in PowerShell strings, so the connection string passed via `-Args` is looking for an invalid SQL Server instance
* We added the `-ConnectionString` parameter to Update-Database in 5.0 that you can also use

**Comment by Ogglas** [comment]
@bricelam 

1. Yes I know but even setting a value like this:

`$ConnectionStrings = [PSCustomObject]@{DefaultConnection = 'Server=tcp:mySqlServerStuffxxx'}`

Will also cause the error `Value cannot be null. (Parameter 'connectionString')`. My point was showing that `DefaultConnection` is nested and the solution shown below won't work:

https://dev.to/azure/using-entity-framework-with-azure-functions-50aa#adding-an-entity-framework-migration

I also tried the solution above with changing to `var connectionString = Environment.GetEnvironmentVariable("ConnectionString");` in `CreateHostBuilder` and then running:

```
$env:ConnectionString='Server=(localdb)\mssqllocaldb;Database=FunctionApp1.Test;Trusted_Connection=True;MultipleActiveResultSets=true'
Update-Database
```

This also caused the exception: `Value cannot be null. (Parameter 'connectionString')`.

Is it a dead end with `CreateHostBuilder`?

2. I did not think about that! Worked after fixing this. 

3. Really nice. I first tried with `-ConnectionString` but got this error:

> Update-Database : A parameter cannot be found that matches parameter name 'ConnectionString'.

After reading documentation I saw that the parameter was actually `-Connection`. After trying that it worked like a charm with the simple `IDesignTimeDbContextFactory` below.

https://docs.microsoft.com/en-us/ef/core/cli/powershell#update-database

`Update-Database -Connection 'Server=(localdb)\mssqllocaldb;Database=FunctionApp1.Test;Trusted_Connection=True;MultipleActiveResultSets=true'`

    public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseSqlServer();

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }

**Comment by MacMcDell** [comment]
@Ogglas any chance you could provide a working sample using efcore 7 and azure isolated .net 6 sample or even a .net5 one? I am having the similar/exact same issues as you with migrations, database update etc. It is super frustrating... my question is posted over here. https://github.com/dotnet/efcore/issues/30897. Out of the box, I can get it to work with the db, but trying to do migrations etc is really really tedious.  If you can provide any working samples that would be great. Thanks!

**Comment by MacMcDell** [comment]
I was able to work around this issue implementing IDesignTimeDBContextFactory as above. 
https://github.com/dotnet/efcore/issues/30897
This post was helpful.
