### ISSUE TITLE
Make it easier to use semantic datatypes with EF core.

### ISSUE THREAD

**Issue by thargol1** [dotnet/efcore#25037]
A semantic data type is a struct or class with a single member of a primitive type. For example:
```c#
struct Email
{
   public string Value {get; set;}
   // other code, but no other public properties or fields
}
```

I use semantic data types to prevent stupid programming errors like assigning an email address to a user code or assigning a employeeId to a studentId. I get the errors at compile time.
```C#
EmployeeId employeeId = 3;
StudentId studentId = employeeId ; // gives compiler error

int employeeId = 3;
int studentId = employeeId ; // compiles but give an error at run-time or causes unexpected behavior.
```

However for each data type I have to make a bit of plumbing code to make it work with EF core and with Json.

I want to get rid of or the plumbing code perhaps using an extra data annotation or extra function in the context:

```c#
[UseSingleValue]
struct Email
{
   public string Value {get; set;}
}
```
or (but not preferred by me)
```c#
entity.Property(e => e.Email).UseSingleValue<Email>(v => v.Value)
```
So EF core knows that a property of type Email really is a string stored in property Value and generates the plumbing code it self.

**Comment by roji** [comment]
Have your taken a look at [value converters](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations)? That provides almost exactly the UseSingleValue API above.

**Comment by thargol1** [comment]
I know of value converter and have used them. The problem is I use a Source Generator to generate my semantic value structures. As source generators cannot change existing code, they can not change the DbContext on the fly. So I still have to do stuff manually (not that much) which could otherwise be generated automatically.

(For Json I can register a auto generated conversion with an attribute on the struct.)

My source generator takes this input:
```c#
//# ValueStruct: double,json,comparable,plusminus
public readonly partial struct Celcius
{
	private const string PostFix = "°C";
	public bool IsValid => Value >= -273.15d;
}
```
And then generates the rest of the struct, with a TryParse, ToString, conversion to double, validator, json conversion etc etc. But still without automatic EF-core support.

**Comment by roji** [comment]
> As source generators cannot change existing code, they can not change the DbContext on the fly.

The regular pattern here would be to have a partial method on your DbContext, and have your source generator create that method, with all the necessary model configuration (setting up the value converters in your case). This is described in the [source generator cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#augment-user-code).

More generally, we do have a planned feature for EF Core 6.0 called "value objects", which would go in this direction, and may allow these types to be configured implicitly (i.e. by convention). The tracking issue here would be https://github.com/dotnet/efcore/issues/9906.

**Comment by lakeman** [comment]
You could visit every property in your `OnModelCreating`, eg `modelBuilder.Model.GetEntityTypes().Select(t => t.GetProperties())` and create a converter based on reflection information.

**Comment by thargol1** [comment]
For now I'll just go with the `OnModelCreatingPartial` partial method. I will have to research how to find the dbcontext classes where my types are used, but that should be possible.

It feels wrong for me personally to use reflection when all of the code is generated by tools and the reflected information is already known before hand.

**Comment by roji** [comment]
Seems like the rest of this is about value objects, so we can probably close as a dup of #9906.
