### ISSUE TITLE
[Question]Can I use Owned Entity as Subset of Owner Entity?

### ISSUE THREAD

**Issue by LuNyit** [dotnet/efcore#25038]
I would like to to use Owned Entity as following way. and It is possible?

       public class SaleItem
       {
               public long SaleItemID { get; set; }
       
               public long SaleID { get; set; }
               public Sale Sale { get; set; }
       
               public TransactionData SaleItemData {get;set;}
       }

       public class PurchaseItem
       {
               public long PurchaseItemID { get; set; }
       
               public long PurchaseID { get; set; }
               public Purchase Purchase{ get; set; }
       
               public TransactionData PurchaseItemData {get;set;}
       }

       [Owned]
       public class TransactionData
       {
               public long ItemID { get; set; }

               public int Quantity { get; set; }

               public decimal Rate { get; set; }

               public decimal SubTotal { get; set; }

               public decimal Discount { get; set; }

               public decimal Total { get; set; }

               public Item Item {get;set;}
       }

The question is, it is possible to put Foreign Key(ItemID) in TransactionData Entity for Owner Entities (Saleitem and PurchaseItem).

**Comment by AndriySvyryd** [comment]
Yes, as long as there are no navigations to the owned entity other than from the owner
