### ISSUE TITLE
Is there any solution how to run EF migrations that referenced to EF 3.1 on the runtime with EF 5.0?

### ISSUE THREAD

**Issue by tatarincev** [dotnet/efcore#25045]
We have an application with plugins and want to migrate the main application to EF 5.0 while still being able to run plugins that are still referenced to EF Core 3.1, and by this way, provide a seamless update for our clients.

Everything goes well, except applying migrations, plugins successfully run with 5.0 but fail with many `System.MissingMethodException: Method not found: `   exceptions for all our migrations from plugins, because their code is still referenced to EF Core 3.1. 

This behavior is explained by major binary breaking changes that have introduced with the [MigrationBuilder](https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore.Relational/Migrations/MigrationBuilder.cs) and [ColumnsBuilder](ColumnsBuilder) in the EF Core 5.0 in comparison to 3.1.

This sample migration code, which references to EF Core 3.1 
```C#
migrationBuilder.CreateTable(
                name: "Notification",
                columns: table => new
                {
                    Id = table.Column<string>(maxLength: 128, nullable: false),
                    CreatedDate = table.Column<DateTime>(nullable: false)
               }
```

But fails with this exception when running this code on EF Core 5.0 runtime.

```C#
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.OperationBuilder`1 Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.ColumnsBuilder.Column(System.String, System.Nullable`1, System.Nullable`1, Boolean, System.String, Boolean, System.Object, System.String, System.String, System.Nullable`1, System.String)'
```

It's a very pity since the rest of EF logic works perfectly with the 5.0  runtime, and only migration code fails. 

My question to the EF Core team is there any recommendation or solution on how to run migrations scripts that are referenced to 3.1 on the runtime that has EF Core 5.0?

**Comment by AndriySvyryd** [comment]
We strive to avoid breaking changes when possible, but sometimes we have no choice if we want to keep the product moving forward. You will have to recompile the migrations assembly in order to upgrade to EF Core 5.0
