### ISSUE TITLE
GetMigrations does not work for context subclass

### ISSUE THREAD

**Issue by PaulBol** [dotnet/efcore#25055]
## Bug details

We are using a main shared assembly that defines `MyContext : DbContext` and associated migrations. Migrations declare the attribute `[DbContext(typeof(MyContext))]`

In an executable assembly we have `ExecutableContext : MyContext`.

`MyContext.Database.GetMigrations` returns the migrations from the main assembly as expected.

`ExecutableContext.Database.GetMigrations` always returns an empty list.

I figured out that this comes from the following code in `Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsAssembly.Migrations`

```cs
var items
   = from t in Assembly.GetConstructibleTypes()
     where t.IsSubclassOf(typeof(Migration))
         && t.GetCustomAttribute<DbContextAttribute>()?.ContextType == _contextType
     let id = t.GetCustomAttribute<MigrationAttribute>()?.Id
     orderby id
     select (id, t);
```

- `DbContextAttribute.ContextType` is `MyContext` 
- `_contextType` is `ExecutableContext`
- -> no type can ever be returned.

Does that make sense or should the line read (same for `ModelSnapshot`)

```cs
         && t.GetCustomAttribute<DbContextAttribute>()?.ContextType?.IsAssignableFrom(_contextType) == true
```

### Provider and version information

EF Core version: 3.1.15 (master)
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.10

**Comment by AndriySvyryd** [comment]
cc: @bricelam

**Comment by bricelam** [comment]
Migrations are generated against a specific model. Since a derived DbContext type can (and probably will) change the model, Migrations only look for ones generated for that exact type.

Assuming both contexts have the same model, what is the purpose of ExecutableContext? Why not just use MyContext instead?

**Comment by PaulBol** [comment]
Thanks for your input @bricelam.

I'm defining the `DbContext` (`MyContext`) in an assembly that is shared between a console application and a ASP.NET Core web application.

In the web application dependency injection is used to automatically populate a user ID that the context uses (console application and unauthenticated access will use 0). `ExecutableContext` is pretty short.

```cs
public class ExecutableContext : MyContext
{
    private IHttpContextAccessor mHttpContextAccessor;

    public ExecutableContext(IHttpContextAccessor httpContextAccessor, IServiceProvider serviceProvider) : base(serviceProvider)
    {
        mHttpContextAccessor;
    }

    protected override int UserId
    {
        get
        {
            if (mHttpContextAccessor.HttpContext?.User?.Identity.IsAuthenticated != true) { return 0; }
            return mHttpContextAccessor.HttpContext.User.GetUserId();
        }
    }
}
```

The context class is registered with `services.AddDbContext<MyContext, ExecutableContext>()`. Due to the behavior described above `serviceProvider.GetRequiredService<MyContext>()` will not find and apply any migration when called from the ASP.NET Core web application.

Can you suggest a different design that allows using migrations from the web application?

**Comment by AndriySvyryd** [comment]
cc: @roji

**Comment by roji** [comment]
@PaulBol I think the simplest way forward here is for you to have a single DbContext class, which you can use both from your console and ASP.NET applications. This should be doable by having two constructors on the same DbContext type - one which your console program can use, and another which DI uses. For the tenant ID, the DI constructor would presumably accept some ITenantService which is responsible for getting the tenant information out of the HTTP context, and the constructor would set that information on the context instance.

/cc @JeremyLikness

**Comment by PaulBol** [comment]
@roji Thanks for your input. I appreciate you taking the time to share the suggestion.

I liked my approach of using inheritance to insert the user ID into the context. But apparently that's not what you guys had planned for migrations in Entity Framework Core. I'll apply your idea of injecting a service that gets the user ID and will implement `MyContext` as `sealed`.
