### ISSUE TITLE
Official guidance: code first vs scaffolding

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#25051]
I seem to remember a comment in the EF core documentation that says something to the effect that EF is primarily designed to work with code first vs reverse-engineering.  I've spent the better part of an hour searching the documentation and github and I can not find it.  Was it my imagination or is there official guidance that recommends code first or scaffold, all other factors being equal?

**Comment by ajcvickers** [comment]
@sam-wheat Both ways are equally recommended and supported.

**Comment by roji** [comment]
@sam-wheat it's worth mentioning that reverse-engineering an existing database creates a code model for you. At that point you're pretty much we're you'd be had you written it by hand (aside from possible tweaks which you can do to the scaffolded model of course). So it really isn't either-or - in all cases you're doing "code first" in the sense that you end up having a code model.

**Comment by ErikEJ** [comment]
@sam-wheat @roji  

Imho, EF Core Power Tools offers a workflow where you can evolve the database and re-scaffold code, even with "tweaks" added to the model.

**Comment by roji** [comment]
@ErikEJ that's a good point - that's more of a "database-first" workflow indeed. Though it's worth mentioning that at the end of the day there's always a code model in your application.

**Comment by sam-wheat** [comment]
@ErikEJ I've been looking at EF Core Power Tools.  It's a great tool.  Thank you!
