### ISSUE TITLE
Compiled models don't have the correct default namespace/directory

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25059]
Currently, the compiled model is generated in the same namespace and in the same folder as the existing model. I have found that it is very useful to have the compiled model in its own directory so that it can easily be blown away. We should consider making this the default. (Note this is somewhat similar to generating migrations in `\Migrations` by default.)

**Comment by AndriySvyryd** [comment]
EFCoreOptimization
 ├ CompiledModels
 └ CompiledQueries

Rooted at the `DbContext` namespace/folder.
Namespace will mirror the folder structure.
