### ISSUE TITLE
Poorly performing query when selecting parent entity from filtered child entities

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/efcore#25052]
## Ask a question

I'm trying to pull data for an entity, by filtering it's related entities. This is like the v5 include filtering, except I actually want the entire query filtered by it vs just the child entities that are returned.

The query that's generated is terribly inefficient when doing this. What can I do to get a better generated query for this, while also getting the results I want in a single query?

#### Models
(Somewhat simplified for this purpose)

```cs
    public class MineGroup : EquatableModel
    {
        public long Id { get; set; }

        public HashSet<Mine> _mines;
        public IEnumerable<Mine> Mines => _mines?.ToList();
    }

    public class Mine
    {
        public long Id { get; set; }

        public long MineGroupId { get; private set; }
        public MineGroup MineGroup { get; private set; }

        public float Latitude { get; set; }
        public float Longitude { get; set; }
    }
```

#### EF Core Query

The objective here is to get all `MineGroup` where their mines exist within the specified bounds, and have the `Mines` collection populated.

```cs
        MineGroup[] groups = await _context.Mines
                .Where(x => x.Longitude >= bbox.West)
                .Where(x => x.Longitude <= bbox.East)
                .Where(x => x.Latitude <= bbox.North)
                .Where(x => x.Latitude >= bbox.South)
                .Include(x => x.MineGroup)
                    .ThenInclude(x => x.Mines)
                .Select(x => x.MineGroup)
                .AsNoTracking()
                .ToArrayAsync();
```

#### Generated SQL

I actually have ~500 mines that are in this area. However, this query has a result set of 100k
```sql
      SELECT "m0"."Id", "m"."Id", "m1"."Id", "m1"."Latitude", "m1"."Longitude", "m1"."MineGroupId"
      FROM "Mines" AS "m"
      INNER JOIN "MineGroups" AS "m0" ON "m"."MineGroupId" = "m0"."Id"
      LEFT JOIN "Mines" AS "m1" ON "m0"."Id" = "m1"."MineGroupId"
      WHERE ((("m"."Longitude" >= -119.13574) AND ("m"."Longitude" <= -119.11377)) AND ("m"."Latitude" <= 43.755226)) AND ("m"."Latitude" >= 43.739353)
      ORDER BY "m"."Id", "m0"."Id", "m1"."Id"
```

### Include provider and version information

EF Core version: 5.0.3
Database provider: Sqlite
Target framework: .Net 5
Operating system: Windows 10
IDE: VS 2019 16.8.5

**Comment by smitpatel** [comment]
The LINQ query and your expected SQL in text are different queries hence the result set differs.

> I actually have ~500 mines that are in this area. However, this query has a result set of 100k

This implies that you only want mines inside the area. But your query is asking to find all the mine groups associated with mines inside this area and load all the mines for all those minegroups. Both are different sets.

**Comment by douglasg14b** [comment]
The SQL I pasted is the SQL generated from this query, not my expected SQL.

**Comment by smitpatel** [comment]
> I actually have ~500 mines that are in this area. However, this query has a result set of 100k

Your LINQ query doesn't ask for mines in the area so EF generated SQL gives different results than what you expect. For the given LINQ query, the generated SQL is pretty much best optimized possible. Perhaps you need to verify the LINQ query written if that is what you want.

**Comment by douglasg14b** [comment]
> Perhaps you need to verify the LINQ query written if that is what you want.

If you are willing to provide assistance, I would highly appreciate it. I realize the LINQ query is the issue, however, I don't know how to write it in a way that it's interpreted for the results I'm aiming for:

That is preciously why I asked:

> _What can I do to get a better generated query for this, while also getting the results I want in a single query?_

**Comment by smitpatel** [comment]
We don't know that what results are you trying to get, What is your model and database schema. I understand you are looking for better generated query but without knowing what is the goal here, we cannot write a LINQ query.

**Comment by douglasg14b** [comment]
> We don't know that what results are you trying to get.

I specifically said this in my post:

> The objective here is to get all MineGroup where their mines exist within the specified bounds, and have the Mines collection populated.

 Can you call out what you need clarification on or how I can make this clearer in order for you to assist?
 
 <hr>
 
 > What is your model and database schema.
 
In my post, I have my model, which translates to the schema EF Core would build for that based on convention. We can assume there are indexes for the `Latitude` and `Longitude`.

<hr>

I appreciate any help you are willing to provide, however, I am confused by the intention of your questions & concerns. Which are covering things that I have already provided or written out. Perhaps you can be more specific as to what is not understood, and needs clarification, after reading my entire post?

**Comment by smitpatel** [comment]
> The objective here is to get all MineGroup where their mines exist within the specified bounds, and have the Mines collection populated.

The LINQ query you posted above corresponds to that and generated SQL is accurate SQL for it. Having only 500 mines within specified bounds has no connection to the result set size of SQL or LINQ query based on above.

**Comment by roji** [comment]
@douglasg14b I took a look at this as well... I agree with @smitpatel's comment above that your LINQ query does seem to correspond to what you're try to do ("get all MineGroup where their mines exist within the specified bounds, and have the Mines collection populated"), and that the SQL EF generates seems correct as well. But I think we have a slight communication disconnect here.

> I actually have ~500 mines that are in this area. However, this query has a result set of 100k

So importantly, as you've written it, your query returns all MineGroups which contain at least one mine in your bbox, but for each of these groups it pull back **all** mines when population the Mines collection. That means it returns mines which are *not* in your original bbox, simply because they're in a MineGroup with another mine that **is** in the bbox. That probably explains why you're seeing a lot more mines coming back than you expect.

If what you want is to get back MineGroups with their Mines collection populated, **but only** with mines in the bbox, then you need to repeat your filter in the filtered include as well:

```c#
var groups = await ctx.Mines
    .Where(m => m.Longitude >= bbox.West && m.Longitude <= bbox.East && m.Latitude <= bbox.North && m.Latitude >= bbox.South)
    .Include(x => x.MineGroup)
    .ThenInclude(x => x.Mines
        .Where(m => m.Longitude >= bbox.West && m.Longitude <= bbox.East && m.Latitude <= bbox.North && m.Latitude >= bbox.South))
    .Select(x => x.MineGroup)
    .AsNoTracking()
    .ToArrayAsync();
```

SQL:

```sql
SELECT [m0].[Id], [m].[Id], [t].[Id], [t].[Latitude], [t].[Longitude], [t].[MineGroupId]
FROM [Mines] AS [m]
INNER JOIN [MineGroups] AS [m0] ON [m].[MineGroupId] = [m0].[Id]
LEFT JOIN (
    SELECT [m1].[Id], [m1].[Latitude], [m1].[Longitude], [m1].[MineGroupId]
    FROM [Mines] AS [m1]
    WHERE ((([m1].[Longitude] >= @__bbox_West_0) AND ([m1].[Longitude] <= @__bbox_East_1)) AND ([m1].[Latitude] <= @__bbox_North_2)) AND ([m1].[Latitude] >= @__bbox_South_3)
) AS [t] ON [m0].[Id] = [t].[MineGroupId]
WHERE ((([m].[Longitude] >= @__bbox_West_0) AND ([m].[Longitude] <= @__bbox_East_1)) AND ([m].[Latitude] <= @__bbox_North_2)) AND ([m].[Latitude] >= @__bbox_South_3)
ORDER BY [m].[Id], [m0].[Id], [t].[Id]
```

If that seems unnecessary, consider that in other scenarios the two things - which groups are returned, and which mines are populated in their mines lists - really are separate. You may want all groups in the database, but with only bounded mines in their collections (so some groups would have 0 mines), or you may want only groups which have at least one bounded mine, but with all mines populated (which is what your query does above).

I hope this helps explain why your query behaves the way it does, and what you may need to do to get the behavior you want.
