### ISSUE TITLE
Update SQL Server transient error list

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#25050]
Filed originally at https://github.com/dotnet/SqlClient/issues/649#issuecomment-657433993
> Please consider adding some of these that EF Core's SqlServerTransientExceptionDetector does not recognize:

Number | Severity | Message | Reasoning
-- | -- | -- | --
601 | 12 | "Could not continue scan with NOLOCK due to data movement." | Advice in&nbsp;Hints (Transact-SQL) - Table
617 | 20 | "Descriptor for object ID %ld in database ID %d not found in the hash table during attempt to unhash it. A work table is missing an entry. Rerun the query. If a cursor is involved, close and reopen the cursor." | "Rerun"
669 | 22 | "The row object is inconsistent. Please rerun the query." | "Rerun"
921 | 14 | "Database '%.*ls' has not been recovered yet. Wait and try again." | "Try again"
1203 | 20 | "Process ID %d attempted to unlock a resource it does not own: %.*ls. Retry the transaction, because this error may be caused by a timing condition. If the problem persists, contact the database administrator." | "Retry"
1204 | 19 | "The instance of the SQL Server Database Engine cannot obtain a LOCK resource at this time. Rerun your statement when there are fewer active users. Ask the database administrator to check the lock and memory configuration for this instance, or to check for long-running transactions." | "Rerun"
1221 | 20 | "The Database Engine is attempting to release a group of locks that are not currently held by the transaction. Retry the transaction. If the problem persists, contact your support provider." | "Retry"
1222 | 16 | "Lock request time out period exceeded." | "Time out"
3935 | 16 | "A FILESTREAM transaction context could not be initialized. This might be caused by a resource shortage. Retry the operation. Error code: 0x%x." | "Retry"
3960 | 16 | "Snapshot isolation transaction aborted due to update conflict. You cannot use snapshot isolation to access table '%.*ls' directly or indirectly in database '%.*ls' to update, delete, or insert the row that has been modified or deleted by another transaction. Retry the transaction or change the isolation level for the update/delete statement." | "Retry"
3966 | 17 | "Transaction is rolled back when accessing version store. It was earlier marked as victim when the version store was shrunk due to insufficient space in tempdb. This transaction was marked as a victim earlier because it may need the row version(s) that have already been removed to make space in tempdb. Retry the transaction" | "Retry"
8628 | 17 | "A time out occurred while waiting to optimize the query. Rerun the query." | "Rerun"
8645 | 17 | "A timeout occurred while waiting for memory resources to execute the query in resource pool '%ls' (%ld). Rerun the query." | "Rerun"
8651 | 17 | "Could not perform the operation because the requested memory grant was not available in resource pool '%ls' (%ld). Rerun the query, reduce the query load, or check resource governor configuration setting." | "Rerun"
9515 | 16 | "An XML schema has been altered or dropped, and the query plan is no longer valid. Please rerun the query batch." | "Rerun"
10922 | 16 | "%ls failed. Rerun the statement." | "Rerun"
14355 | 16 | "The MSSQLServerADHelper service is busy. Retry this operation later." | "Retry"
17197 | 16 | "Login failed due to timeout; the connection has been closed. This error may indicate heavy server load. Reduce the load on the server and retry login.%.*ls" | "Retry"
20041 | 16 | "Transaction rolled back. Could not execute trigger. Retry your transaction." | "Retry"

> Also, if SqlClient does not recognize the specific error code, perhaps it can still treat some of the [Database Engine Error Severities](https://docs.microsoft.com/sql/relational-databases/errors-events/database-engine-error-severities?view=sql-server-ver15) as transient; like 13 (deadlock) or 17 (out of resources).

**Comment by AndriySvyryd** [comment]
Also consider 
>997,    // A connection was successfully established with the server, but then an error occurred during the login process. (provider: Named Pipes Provider, error: 0 - Overlapped I/O operation is in progress)

**Comment by AndriySvyryd** [comment]
After discussion we've decided to add the above errors to the transient list as retrying would be appropriate action for them in most cases and shouldn't have significant negative consequences in the cases that the error is not transient. With the following exceptions:
- -2 (Timeout) - There's a high chance of it being caused by user error, especially during initial development.

- 1222 (Lock request time out) - By default LOCK_TIMEOUT is set to -1 (Infinite), so this error only happens when the user explicitly set it to a different value.

**Comment by ajcvickers** [comment]
Consider documenting as a breaking change.
