### ISSUE TITLE
PluralizationService returns "Respons" as singular form of "Responses"

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/efcore#2506]
This is the code:

System.Data.Entity.Design.PluralizationServices.PluralizationService.CreateService(System.Globalization.CultureInfo.CreateSpecificCulture("en-US")).Singularize("Responses");

the result is: "Respons"

**Comment by rowanmiller** [comment]
The pluralization service is removed in EF7. We aren't taking changes to it for EF6 since changes can break existing models.

**Comment by divega** [comment]
Just to add to what @rowanmiller said, in EF6 you can customize the pluralization service to fix any words. Here is some example code:

http://stackoverflow.com/questions/17471391/how-to-customize-the-pluralization-ef6

Note that this does not help when the EF Designer automatically singularizes table names to produce entity types, but those can be manually edited in the designer after the model is created.

**Comment by weitzhandler** [comment]
@divega @rowanmiller Is the pluralization service still provided with DNX/Core as part of an external package or elsewhere?

**Comment by rowanmiller** [comment]
@weitzhandler no, the pluralization service was just an EF component and it's not something we are pulling forwards. You could always copy the code from the EF6 code base if you want since the license is very permissive.

**Comment by weitzhandler** [comment]
@rowanmiller @divega 
I've ported the PluralizationService rep. It might be cool if it gets in the .NET Framework. It's a useful service.
I'll add admins and even transfer ownership if needed.
https://github.com/weitzhandler/Pluralization

**Comment by weitzhandler** [comment]
@rowanmiller @divega 
I've discovered someone already worked on that before:
https://github.com/eduaquiles/PluralizationService
