### ISSUE TITLE
How do I get the Cosmos database Id so I can use GetCosmosClient()

### ISSUE THREAD

**Issue by acrov** [dotnet/efcore#25063]
## Question

Occasionally EF doesn't support what I need so I want to bypass it and make a quick cosmos query.  I thought I could do this easily by using the `DbContext.GetCosmosClient()` extension method.  However, I've run into the issue that I still need to know the database id and container id in order to get a container to query on.

I want to do something like this...
```
var ctx = ServiceProvider.GetRequiredService<MyCosmosDbContext>();
var client = ctx.Database.GetCosmosClient();
var databaseId = HOW_DO_I_GET_THIS;
var containerName = ctx.Model.GetDefaultContainer();
var container = client.GetContainer(databaseId, containerName);
var result = container.GetItemQueryStreamIterator("query");
```

Of course, somewhere I must call `DbContextOptionsBuilder.UseCosmos(connectionString, databaseId)` but this is different in different environments/applications so I don't have a reliable way to get the database Id that way.

Any help much appreciated.

### Provider and version information

Microsoft.EntityFrameworkCore 5.0.6
Microsoft.EntityFrameworkCore.Cosmos 5.0.6
Microsoft.Azure.Cosmos 3.12.0

**Comment by AndriySvyryd** [comment]
There's currently no public way of doing it. We could add `ctx.Database.GetCosmosDatabase()` or `ctx.Database.GetCosmosDatabaseId()`

**Comment by acrov** [comment]
@AndriySvyryd Many thanks for your reply.  `ctx.Database.GetCosmosDatabase()` would be simpler to use but I guess could have concurrency issues if not a new database connection.  `ctx.Database.GetCosmosDatabaseId()` would give more flexibility/control and makes any concurrency issues to the caller's responsibility so is possibly the better option.

**Comment by koenbeuk** [comment]
As a workaround, I've been using the following methods as part of my DbContext:
```csharp
public string GetCosmosDbName()
{
#pragma warning disable EF1001 // Internal EF Core API usage.
    var dbContextOptions = this.GetService<IDbContextOptions>();
    var cosmosOptionsExtension = dbContextOptions.FindExtension<CosmosOptionsExtension>();
    Debug.Assert(cosmosOptionsExtension is not null);

    return cosmosOptionsExtension.DatabaseName;
#pragma warning restore EF1001 // Internal EF Core API usage.
}

public string? GetCosmosContainerName(Type type)
{
    var entityType = Model.FindEntityType(type);
    return entityType?.GetContainer();
}

var cosmosClient = Database.GetCosmosClient();
var databaseName = GetCosmosDbName();
var databaseClient = cosmosClient.GetDatabase(databaseName);
var containerName = GetCosmosContainerName(typeof(MyEntity));
var containerClient = databaseClient.GetContainer(containerName);
```
