### ISSUE TITLE
String array is throwing exception in memory database

### ISSUE THREAD

**Issue by binshidhak** [dotnet/efcore#25073]
I have an issue while running the x unit test using inmemory database

Result Message:    System.InvalidOperationException : The property 'X.Y' is of type 'string[]' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

-- Applied the solution  found in another thread,but it is not working for me

    public class AbcDbContext : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuestionnaireDbContext"/> class.
        /// </summary>
        /// <param name="options">The options.</param>
        public AbcDbContext(DbContextOptions<AbcDbContext> options)
               : base(options)
        {
            ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
        }

        public DbSet<InvitationView> InvitationViews { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Set dummy key for invitation view mapper when using in memory database.
            modelBuilder.Entity<InvitationView>(entity =>
            {
                if (!Database.IsInMemory())
                {
                    entity.HasNoKey().ToView(null);
                }
                else
                {
                    entity.HasKey(e => e.ParticipantId);
                    entity.Property(e => e.ReviewLocked)
                          .HasConversion(
                           v => new ArrayWrapper(v),
                           v => v.Values);
                }
            });
            base.OnModelCreating(modelBuilder);
        }
        private struct ArrayWrapper
        {
            public ArrayWrapper(string[] values)
                => Values = values;

            public string[] Values { get; }
        }
    }
}

Tried the following codes as well
                  
         1)    var converter = new ValueConverter<string[], string>(
                                      v => string.Join(";", v),
                                      v => v.Split(";", StringSplitOptions.RemoveEmptyEntries).Select(val => val).ToArray());
                    entity.Property(e => e.Y)
                                 .HasConversion(converter);

        2)          entity.Property(p => p.Y)
                      .HasConversion(
                    v => string.Join("'", v),
                    v => v.Split(',', StringSplitOptions.RemoveEmptyEntries));
        3)             entity.Ignore("Y");
these codes were not working working for me.

**Comment by roji** [comment]
The InMemory provider indeed does not support arrays, just like most regular database providers don't.

However, value converters can indeed help here. Your solution 2 above does work - please see the minimal code sample below. The fact that even ignoring the property doesn't work (solution 3) points to their being another array property (not Y) which is possibly causing the issue. Carefully review your model to apply the value converter to all array properties. If you're still having issues, please post a full, runnable code sample.

<details>
<summary>Working code</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.InvitationViews.ToList();

public class BlogContext : DbContext
{
    public DbSet<InvitationView> InvitationViews { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseInMemoryDatabase("foo");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InvitationView>()
            .Property(i => i.Values)
            .HasConversion(
                v => string.Join("'", v),
                v => v.Split(',', StringSplitOptions.RemoveEmptyEntries));
    }
}

public class InvitationView
{
    public int Id { get; set; }
    public string[] Values { get; set; }
}
```
</details>

**Comment by binshidhak** [comment]
This is working for me. Thankyou
