### ISSUE TITLE
MAUI preview 4 does not work with EF Core, any version

### ISSUE THREAD

**Issue by ponyspeed888** [dotnet/efcore#25080]
EF Core 3.1, 5.0, and 6.0 preview does not work with MAUI application preview 4.  The root cause seems to be in Microsoft.Data.Sqlite.  It caused a "Target Invokation Error" when a SQLite connection is opening.  In the attached project, this line

			SqliteConnection con = new SqliteConnection();  // THIS LINE CAUSED A TARGET INVOKATION ERROR

At MainApplication.cs, line 34				

Attached project google drive link :

https://drive.google.com/file/d/1BcCGk26ZIHNJaxGb6vqVupsfhGAcmc-V/view?usp=sharing

**Comment by zleao** [comment]
I'm having this issue as well. When I try to run my app in an Adnroid local device, I noticed 2 things:
- **Build warning**: `Cannot determine ABI of native library 'C:\Users\...\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.5-pre20210521085756\runtimes\linux-arm64`
- **At runtime when trying to create a DbContext**:  
  - **Exception** - `System.TypeInitializationException: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception`
  - **Inner Exception** - `DLLNotFound - e_sqlite3`

I'm using:
- MAUI 6.0.1-preview.5.794
- EFCore 6.0.0-preview.7.21362.1
- Running on an Android device with API 28

**Comment by bricelam** [comment]
I'm not able to repro this on the latest bits. Both the emulator and my ancient API 26 device worked for me.
