### ISSUE TITLE
Lazy Loading appears to be broken in 6.0.0-preview.4

### ISSUE THREAD

**Issue by boatcoder** [dotnet/efcore#25097]
## File a bug

Remember:
It appears that Lazy Loading should now be working, but for the life of me I cannot seem to get it to to work.  I have a very simple example (2 Entities) that demonstrates this https://github.com/boatcoder/LazyLoadingFailureEFCore. See the README.md for what is happening.

What else has to be done to get LazyLoading to work?  I've got the proxies, I tell it to `.UseLazyLoadingProxies(true)`. All of the connections appear to be configured, but nothing will cause it to lazyload, I have to use `.Include`

### Include your code

https://github.com/boatcoder/LazyLoadingFailureEFCore

Here is a 4 `.cs` file project that illustrates the problem along with a Readme that shows that the output is doing.

### Include verbose output

Done, it doesn't crash, it just doesn't lazy load even though it should.
```
-------
ParticipantList 'I'm a P List' Id=1
        1: 123@gmail.com
        2: 456@gmail.com
-------

Clearing Change Tracker
via LazyLoading LazyLoadingEnabled=True
-------
ParticipantList 'I'm a P List' Id=1
:-(
-------

After Also selecting emails from DB LazyLoadingEnabled=True
-------
ParticipantList 'I'm a P List' Id=1
:-(
-------

Clearing Change Tracker
via Include LazyLoadingEnabled=True
-------
ParticipantList 'I'm a P List' Id=1
        1: 123@gmail.com
        2: 456@gmail.com
-------
```

### Include provider and version information

EF Core version: 6.0.0-preview.4.21253.1 (Also described in the .sln file
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework:  .NET 5.0
Operating system: MacOS 11.2.3
IDE: Rider

**Comment by ajcvickers** [comment]
From a quick glance it looks like `UseLazyLoadingProxies` never gets called because the database provider is already configured by the previous call to `UseSqlite` by the time `OnConfiguring` is called.
