### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite DatabaseFacade.CanConnect() doesnt check if file is not a database

### ISSUE THREAD

**Issue by Abdragiz** [dotnet/efcore#25091]
When using Microsoft.EntityFrameworkCore.Sqlite database provider, it seems like dbContext.Database.CanConnect() only checks if database file exists. When dummy database file provided (.txt file renamed to .db), method returns true.

```C#
var result = dbContext.Database.CanConnect(); // true
```

### Include version information

Database provider: "Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.6"
Target framework:.NET 5.0
Operating system: Windows 10
IDE: Jetbrains Rider

**Comment by ErikEJ** [comment]
The check could be improved to test for a minimum file size https://www.sqlite.org/fileformat.html

**Comment by ErikEJ** [comment]
But there are complications with encrypted databases: https://stackoverflow.com/questions/3888529/how-to-tell-if-sqlite-database-file-is-valid-or-not

**Comment by bricelam** [comment]
An empty file is a valid SQLite file. CanConnect opens the connection which will validate that it's a database file.

**Comment by bricelam** [comment]
Fun fact: In System.Data.SQLite, calling SQLiteConnection.CreateFile() literally just creates an empty file. 🙂
