### ISSUE TITLE
Consider using Verify for SQL baselines

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#25106]
See https://dotnetfoundation.org/projects/verify

**Comment by SimonCropp** [comment]
let me know if you need any help with this. happy to get on a call and discuss the pros and cons

**Comment by smitpatel** [comment]
1 file for each test is bit of overkill for verifying SQL in our tests. Especially, our current system is not causing any issues.

**Comment by SimonCropp** [comment]
> 1 file for each test is bit of overkill for verifying SQL in our tests

yep that is one of the drawbacks. But it is mostly hidden from the user experience since those files are nested under the parent test file, so they are not seen (by default) in the solution explorer.

> Especially, our current system is not causing any issues

I dont think i have ever seen assert "causing issues", but snapshot testing does have a lot of advantages over traditionally asserts https://github.com/VerifyTests/Verify/blob/master/docs/compared-to-assertion.md

**Comment by SimonCropp** [comment]
also specific to ef, there is helpful approach i call "recording" https://github.com/VerifyTests/Verify.EntityFramework#recording

it allows people to, for any ef calls being done as part of a test, to capture all the interactions EF had with the db and write them in the snapshot file

**Comment by AndriySvyryd** [comment]
> Especially, our current system is not causing any issues.

The biggest benefit for us would be the ability to batch accept the new snapshots when making a global change.

> I dont think i have ever seen assert "causing issues", but snapshot testing does have a lot of advantages over traditionally asserts https://github.com/VerifyTests/Verify/blob/master/docs/compared-to-assertion.md

I am just talking about SQL baselines, which is already a snapshot-based approach, I wasn't proposing to replace other asserts.

**Comment by smitpatel** [comment]
We have python script which can update all SQL baselines for a provider in (nearly instantly). So the only improvement would be to the diffs we generate currently.

**Comment by AndriySvyryd** [comment]
> We have python script which can update all SQL baselines for a provider in (nearly instantly).

Is it checked in?
