### ISSUE TITLE
ToView("something") does not imply ToTable(null)

### ISSUE THREAD

**Issue by midgleyc** [dotnet/efcore#25114]
## File a bug

By the [documentation on breaking changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#toview), `ToView("something")` implies `ToTable(null)`. This does not appear to be the case: `EnsureCreated` is creating a sqlite database containing the view as a table, and the `ModelSnapshot` includes a `b.ToTable` call (in addition to a `b.ToView` call). The `b.ToTable` call does not appear, and the table is not created, if I explicitly additionally write `ToTable(null)`.

### Include your code

Created a project at https://github.com/midgleyc/EntityFramework-ViewBug. Comment / uncomment the code in `JobViewsConfig` to see the different behaviour.

Based on the specific error:
```
Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'table "Jobs" already exists'.
```

I think something slightly different is going on with this project, but the fundamental part -- that `ToView("j")` does not imply `ToTable(null)` -- is the same.

### Include provider and version information

EF Core version: 5.0.7
Database provider: EntityFrameworkCore.Sqlite
Target framework: NET 5.0
Operating system: Ubuntu 20.04
IDE: Rider 2021

**Comment by AndriySvyryd** [comment]
`JobsConfig` implements `IEntityTypeConfiguration<JobView>` instead of `IEntityTypeConfiguration<Job>`

**Comment by midgleyc** [comment]
Yes, my bad. I've also generated a snapshot in the given project and it doesn't display the behaviour I'm seeing in a more complex project that caused me to raise this bug. I'll raise another if I can replicate it in a project I can put public. Thanks for checking!

**Comment by midgleyc** [comment]
Looked into this more: it was a bug on our side. In `onModelCreating`, we were examining entities in `builder.Model.GetEntityTypes()` and changing the table names to snake case (for postgres). `entity.GetTableName()` still returns non-null for views at that point. The fix was to check `entity.GetViewName()` first, which is non-null only for views.
