### ISSUE TITLE
DbContext for multi tenant database

### ISSUE THREAD

**Issue by sergiojrdotnet** [dotnet/efcore#25121]
### How can I configure DbContext for multi tenant database with the same tables separated by schemas as the identification of customers?

I've been looking for the last few days for a solution to my case. I'm architeting a platform for multiple customers that will consume very few database resources. With the intention of effectively isolating the data for each client, I chose to replicate the tables, identifying them using schemas as guids and cataloging them in a single shared table.

```
SELECT * FROM [CustomerA].[Records]
SELECT * FROM [CustomerB].[Records]
SELECT * FROM [CustomerC].[Records]
...
```

I found a possible solution [using mapping for entities](https://stackoverflow.com/a/39631404/2016140) on OnModelCreating method in DbContext class and another with [ModelCacheKeyFactory](https://stackoverflow.com/a/50529432/2016140).

However, the negative aspect of this methods are the cache is grow up for each new company and can cause a memory overflow exception.

I was wondering if now we have a better approach for this scenario with a single database.

EF Core version: 5.0.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by AndriySvyryd** [comment]
There isn't a better approach for multi-tenancy, however in EF Core 6 we've reduced memory usage for models up to 40%, just make sure to override the new method in ModelCacheKeyFactory
