### ISSUE TITLE
Is nullable annotation of DbSet.Find{Async} correct?

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/efcore#25122]
## Ask a question

Currently, the key values in Find/FindAsync is annotated as `object[]? keyValues`. It looks wrong to me.
It's meaningless to pass a null array. But for a composed key, one member can be null (SQL Server allows me to do so). So the correct annotation could be `object?[]`.

**Comment by roji** [comment]
Thanks for raising this, it indeed looks incorrect. Following the code, it seems that we do allow both null values in the array and for the entire array to be null; the method always  returns null in both these cases.

I'm not sure if this is very useful behavior, but that's the way the function works - so for minimum pain for current code adopting NRTs, we should annotate as `object?[]?`. Will wait for a quick triage discussion on this though.
