### ISSUE TITLE
Migrations don't include annotations

### ISSUE THREAD

**Issue by Fosol** [dotnet/efcore#25137]
The `.HasAnnotation("name", value)` doesn't work in EF Core 5.  I have attempted it with both `EntityTypeBuilder<T>` and `ModelBuilder`.  Neither result in the annotation added to the generated migration.

The old workaround was to create a custom `SqlServerMigrationsAnnotationProvider`.  However in EF Core 5 this class comes with a warning and only includes a `ForRemove` lacking the necessary `For`.

In addition, related to this, it is impossible to set the column order.

```C#
modelBuilder.HasAnnotation("ProductVersion", "2.0.0");
// Or
builder.ToTable("name").HasAnnotation("ProductVersion", "2.0.0")
```

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Linux Docker Container

**Comment by AndriySvyryd** [comment]
@Fosol `"ProductVersion"` and other EF annotations are not guaranteed to be represented in migrations. Do you experience this issue with any non-EF annotation?

In EF 5.0 part of `SqlServerMigrationsAnnotationProvider` was split into `SqlServerAnnotationProvider`

Post your scenario that requires a different column order in https://github.com/dotnet/efcore/issues/10059

**Comment by Fosol** [comment]
Client has DB schema standards that request column ordering.  While you and I know that isn't a big deal, but to them it is...

Another fluent API function that doesn't work is `HasConstraintName("name")`.  The migration continues to use the default naming conventions.  Another no-no for DB schema standards.

**Comment by AndriySvyryd** [comment]
If I remember correctly we only use the constraint name when creating it, but we don't generate an operation just to rename it.
@bricelam cc

**Comment by bricelam** [comment]
> If I remember correctly we only use the constraint name when creating the constraint, but we don't generate an operation just to rename it.

This is not how I remember it working.

**Comment by Fosol** [comment]
My expectation for `.HasConstraintName("name")` was for the constraint to named.  However it names the foreign key and generates a random constraint name (i.e. `DF__{TABLE NAME ABBR}__DB_CR_{some number}`).  I would have expected the constraint to be named appropriately and a separate extension method to name the foreign key.

**Comment by bricelam** [comment]
Which constraint are we talking about? A DEFAULT constraint?

**Comment by Fosol** [comment]
This is what I'm seeing after doing the migration.  A bunch of constraints that I'm having a hard time controlling their naming.

![image](https://user-images.githubusercontent.com/3180256/123706968-db4f7180-d81d-11eb-9d18-d357a62b31cb.png)

**Comment by smitpatel** [comment]
I don't see "DF_" being prefix for our naming anywhere in EF Core.

**Comment by Fosol** [comment]
Those constraints show up after I run the migration.  I reviewed the generated migration script, but those constraints are not in there.  Looks like something else must be creating those, or perhaps something to do with Azure Data Studio...  

For now I'll ignore them, as they're not coming from the migration.
