### ISSUE TITLE
Unrecognized command or argument 'optimize' on Entity Framework Core .NET Command-line Tools 5.0.7

### ISSUE THREAD

**Issue by thangchung** [dotnet/efcore#25135]
I have found the blog post about EF on .NET Core 6 Preview 5 at https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-5-compiled-models/ 

Then, I tried it on my laptop. I upgraded my EF Core CLI to the latest version as the guidance at https://docs.microsoft.com/en-gb/ef/core/cli/dotnet. But when I tried to run `dotnet ef dbcontext optimize -c MyContext -o MyFolder -n My.Namespace`. It threw the exception below

```bash
# dotnet ef dbcontext optimize -output-dir MyCompiledModels --namespace MyCompiledModels
Build started...
Build succeeded.
Specify --help for a list of available options and commands.
Unrecognized command or argument 'optimize'.
```

I wonder it might be has a nightly build for the EF tool for EF 6 preview 5, but not sure so that I posted the issue here.
 
My dev environment:

- Windows 10
- .NET SDK: 6.0.100-preview.5.21302.13
- EF Core Tools: 5.0.7
- Microsoft.EntityFrameworkCore: 6.0.0-preview.5.21301.9
- Npgsql.EntityFrameworkCore.PostgreSQL: 6.0.0-preview4
- Microsoft.EntityFrameworkCore.Design: 6.0.0-preview.5.21301.9
- Microsoft.EntityFrameworkCore.Tools: 6.0.0-preview.5.21301.9

**Comment by jeffk100** [comment]
Same here.

**Comment by chrarnoldus** [comment]
Update EF Core Tools to the preview version?

```
dotnet tool update --global dotnet-ef --version 6.0.0-preview.5.21301.9
```

**Comment by jeffk100** [comment]
Yes, mine is similar to @thangchung:

Microsoft.EntityFrameworkCore.Design: 6.0.0-preview.5.21301.9
Microsoft.EntityFrameworkCore.SqlServer: 6.0.0-preview.5.21301.9
Microsoft.EntityFrameworkCore.Tools: 6.0.0-preview.5.21301.9
Microsoft.VisualStudio.Web.CodeGeneration.Design: 6.0.0-preview.5.21321.1
Swashbuckle.AspNetCore: 6.1.4

**Comment by thangchung** [comment]
Thanks, @chrarnoldus. I could handle installing the newest tool and run `Compiled Model` sucessfully.

For those people who have got the issue just like me, I write down what I did as below

- Install EF Core tools

```bash
$ dotnet tool update --global dotnet-ef --version 6.0.0-preview.5.21301.9
Tool 'dotnet-ef' was successfully updated from version '5.0.7' to version '6.0.0-preview.5.21301.9'.
```

- Generate the compiled model

```bash
$ # stand at the root project which has the DbContext reside
$ dotnet ef dbcontext optimize -c MainDbContext -o CompiledModels -n ProductService.Infrastructure
Build started...
Build succeeded.
Connection String: Server=localhost;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
Server=localhost;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
Successfully generated a compiled model, to use it call 'options.UseModel(ProductService.Infrastructure.MainDbContextModel.Instance)'. Run this command again when the model is modified.
```

- Register it

```csharp
services.AddDbContext<MainDbContext>(options =>
{
    options.UseNpgsql(connString, sqlOptions =>
    {
        sqlOptions.MigrationsAssembly(typeof(MainDbContext).Assembly.GetName().Name);
        sqlOptions.EnableRetryOnFailure(5, TimeSpan.FromSeconds(10), null);
    }).UseSnakeCaseNamingConvention();

    options.UseModel(ProductService.Infrastructure.MainDbContextModel.Instance); // this line of code is important
});
```

**Comment by matteo1010** [comment]
Hello, 
check if you have a folder .config in the root project where in the file dotnet-tools.json is specify an older version in tools.dotnet-ef.version
I deleted the file an all work properly

**Comment by zahrazandi** [comment]
I had this problem, I set right project for Default Project  in Package Manager Console so it Build succeeded
