### ISSUE TITLE
DbContext: Make SqlQuery (etc.) honor [Column] (EF6 -> EF7)

### ISSUE THREAD

**Issue by dsaf** [dotnet/efcore#2513]
Migrated from https://entityframework.codeplex.com/workitem/233:

> When using a class like 
> 
> public MyClass 
> { 
> [Column("my_col")] 
> public string MyCol {get; set;} 
> } 
> 
> and selecting this entity using an sql query like 
> 
> <dbcontext>.Database.SqlQuery<MyClass>("SELECT \* FROM myclasstable"); 
> 
> Then the resulting Sql-Statement is like "SELECT MyCol FROM myclasstable" but the column is named "my_col". Therefore an exception is thrown, because column was not found. (Ok, in MSSQL Server case insensitive is the default, but in PostgreSQL this causes an issue.) 
> 
> We should also consider taking any mapping done with the Fluent API into account. 
> 
> Also consider Translate etc. on ObjectContext. 
> 
> _This item was migrated from the DevDiv work item tracking system [ID=401604]._

**Comment by rowanmiller** [comment]
This is already done in EF7. `FromSql` (the replacement for SqlQuery) takes mapping into account. 

Note that Data Annotations are not supported in the public betas yet, so mapping needs to be done with the Fluent API. Some basic support for annotations has just been checked into our working code base and will ship with our next beta.
