### ISSUE TITLE
Removed pinned dependency to Microsoft.Extensions.Caching.Memory.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/efcore#25148]
https://github.com/dotnet/efcore/pull/25092 added a pinned dependency to Microsoft.Extensions.Caching.Memory, which we'll need to update before shipping

@AndriySvyryd

**Comment by bricelam** [comment]
We can unpin it in the preview6 branch them merge that change to main once preview 6 ships

**Comment by bricelam** [comment]
Things are getting pretty messy. Timeline of problems:

* Pinned for Logging breaks around Span - https://github.com/dotnet/efcore/pull/25092
* One-off unpin for preview 6 - https://github.com/dotnet/efcore/pull/25155
* More logging breaks around skipEnabledCheck - https://github.com/dotnet/efcore/pull/25244
* One-off unpin for preview 7 (more breaks found) - https://github.com/dotnet/efcore/pull/25324
