### ISSUE TITLE
Incorrect GUID parameter value logged for Sqlite provider

### ISSUE THREAD

**Issue by nwessing** [dotnet/efcore#25147]
I have noticed an issue with the logging of parameter data in EFCore. I have a SqlLite database schema that uses GUIDs encoded as TEXT for a primary key. In my migration I insert some baseline data that I need, including generating a record with a GUID. The mistake I made was not realizing that GUID's string representation's are upcased before being sent to the database. This detail was hard to discover however because when I turn on `EnableSensitiveDataLogging()` the logs print out an incorrect value for the GUID parameter. Example here:

```
fail: 6/24/2021 08:02:55.837 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (2ms) [Parameters=[@p0='d958a4b6-e0c4-4dce-bfc6-07b58d41dc74' (DbType = String), @p1='03103f4d-9a35-40f3-830c-36a8babcbe9f' (DbType = String), @p2='Test User 2' (Nullable = false) (Size = 11)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "user" ("id", "accessCodeId", "name")
      VALUES (@p0, @p1, @p2);
```
The insert ends up failing because of foreign key constraint, even though the log indicates that the `accessCodeId` it used was `03103f4d-9a35-40f3-830c-36a8babcbe9f`, it actually tried to insert with the value `03103F4D-9A35-40F3-830C-36A8BABCBE9F`. 

Here is a link to a project that reproduces the issue: https://github.com/nwessing/EfCoreLoggingBug

EF Core version: 5.0.7
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 5.0
Operating system: Windows 10
IDE: None

**Comment by bricelam** [comment]
The Parameters section in the log just uses `ToString()` to display the parameter value since all it knows is that it's passing a Guid object to the ADO.NET provider. The conversion to upper-case happens inside the ADO.NET provider and EF logging knows nothing about it.
