### ISSUE TITLE
EF Core Cosmos provider - strange behavior for entities with same RowKey and different PartitionKey

### ISSUE THREAD

**Issue by lihmad** [dotnet/efcore#25146]
We are using EF Core provider for Cosmos and we see some strange behavior.

We have class which looks like this: 

```
    public class Entity
    {
        public string EntityId { get; set; }
        public string Key { get; set; }
        public DateTime Created { get; set; }
        public int TimeToLive { get; set; }
        public string Data { get; set; }
    }
```

In model builder, we have defined entity like this:

```
    modelBuilder.Entity<Entity>(sm =>
    {
        sm.ToContainer("EntityContainer");
        sm.HasPartitionKey(e => e.EntityId);
        sm.HasKey(e => e.Key);
        sm.HasNoDiscriminator();
        // This way we can use ttl at cosmos, but we need to manually turn Time to Live setting at cosmos container (On (no default) choice).
        sm.Property(p => p.TimeToLive).ToJsonProperty("ttl");
        sm.Property(p => p.Key).ToJsonProperty("id");
    });
```

In service we have this logic:

1. Try to find out if entity exists
```
    var messageEntityId = await context.Entities
        .Where(e => e.EntityId == entityId && e.Key == key)
        .Select(e => e.EntityId)
        .FirstOrDefaultAsync();
```
2. If so get whole entity
```
    var entity = await context.Entities
        .Where(e => e.EntityId == entityId && e.Key == key)
        .FirstOrDefaultAsync();
``` 
3. Do some work with data from entity
4. Delete entity
```
    context.ScheduledMessages.Remove(entity);
    await context.SaveChangesAsync();
```
5. Do some work
6. Create new entity (new entity has the same `PartitionKey` (`EntityId`) and same `RowKey` (`Key`).
```
    await context.ScheduledMessages.AddAsync(newEntity);
    await context.SaveChangesAsync();
```

For one entity it works great, but when we process two entities, the problem is at step 2. where we query the whole entity, but instead of returning correct entity, context return the first processed Entity. The main problem is probably that first and second entity has exactly the same `Key` (so `RowKey`). 

When we look into `ChangeTracker` and see `InternalEntry` for the first entity we see
```
{{Key: the_same_row_key_for_both_entities} Unchanged Entity Type: Entity}
```
If I understand it properly, it means that `ChangeTracker` has `Key` as unique identifier, so when both entities has same `RowKey` (but different `PartitionKey`) he looks if any entity with same `Key` is tracked and if so he returns it.

My questions are:
1. Do we understand the problem correctly?
2. If so, is this correct behavior? Should not be cosmos entity be tracked with combination of `PartitionKey` and `RowKey` not just with `RowKey`?

EF Core version: 3.1.11
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET Core 3.1
Operating system: Windows 10 Enterprise 21H1 19043.1052
IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 1.0

**Comment by AndriySvyryd** [comment]
EF Core uses the primary key value as the identity of an entity type. You need to include the partition key in the primary key:

```C# 
    modelBuilder.Entity<Entity>(sm =>
    {
        sm.HasPartitionKey(e => e.EntityId);
        sm.HasKey(e => new { e.Key, e.EntityId });
        ...
    });
```
