### ISSUE TITLE
Warn when using a newer version of dotnet ef with old runtime (command specific)

### ISSUE THREAD

**Issue by nicolas-2008** [dotnet/efcore#25153]
I'm looking for the possibility to get the list of unapplied migrations in Ef Core.
I found the [discussion](https://github.com/dotnet/efcore/issues/577) about the same and it seems like it was [implemented](https://github.com/dotnet/efcore/pull/22109) in Ef Core 5.0.
This however doesn't work for me.

**Preconditions**
1. The latest version of the tool is installed:
`dotnet ef --version`
_Entity Framework Core .NET Command-line Tools
5.0.7_

2. There is a project with migrations and `DbContextFactory` class that implements `IDesignTimeDbContextFactory<CoreContext>` interface to build the `DbContext`. It is successfully picked up by the tool (`dotnet ef database update` and other commands that required db connection work without issues).

**What I tried so far**
1. `dotnet ef migrations list --json` 
"applied" property is null for all migrations, however all of them are applied. (Operation fails in case if incorrect connection string passed to `CoreContext` from `DbContextFactory`).
_[
 {
    "id": "20210620081822_SomeMigration",
    "name": "SomeMigration",
    "safeName": "SomeMigration",
    "applied": null
  },
  {
    "id": "20210620083523_SomeOtherMigration",
    "name": "SomeOtherMigration",
    "safeName": "SomeOtherMigration",
    "applied": null
  }
]_

2. `dotnet ef migrations list --no-connect --json`
Operation executed successfully (so option `--no-connect` which was added in scope of aforementioned PR does exist). 
Result is the same.

3. `dotnet ef migrations list --no-connect false --json`
Operation fails with the message:
_Unrecognized command or argument 'false'._

Am I doing something wrong or is it a bug?

**Comment by bricelam** [comment]
Could you share a repro? If `dotnet ef database update` works, it should be able to show whether a migration has been applied.

**Comment by nicolas-2008** [comment]
My fault. I found that it happens only if project uses older version of ef core.
Though, having "applied: null" in the output and no warnings about version mismatch is a bit confusing.

**Comment by bricelam** [comment]
> no warnings about version mismatch

It didn't show the following warning?

> The Entity Framework tools version '5.0' is older than that of the runtime '3.1'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.

Can you share a repro?

**Comment by bricelam** [comment]
Oh wait, that warning goes the other way. You were using newer tools with an older runtime, right?

We should consider showing a warning for specific features that might not work. Another example would be the new compiled models command.

**Comment by nicolas-2008** [comment]
Hi @bricelam,
I was using dotnet ef tool 5.0.7 with a project that targets net5.0 and references "Microsoft.EntityFrameworkCore" 2.2.6, "Microsoft.EntityFrameworkCore.Design" 2.2.6.

**Comment by bricelam** [comment]
Added an error for `dotnet ef migrations bundle` here:

https://github.com/dotnet/efcore/blob/302b2466a149d3317e76030b5ea68a1e711c6806/src/ef/Commands/MigrationsBundleCommand.cs#L39-L42

We should add similar code to *warn* for `dotnet ef migrations list` and *error* for `dotnet ef dbcontext optimize`.
