### ISSUE TITLE
Inheritance - Changing default shared column naming behaviour?

### ISSUE THREAD

**Issue by jordanwallwork** [dotnet/efcore#25152]
According to the docs here https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#shared-columns

> By default, when two sibling entity types in the hierarchy have a property with the same name, they will be mapped to two separate columns. However, if their type is identical they can be mapped to the same database column:

I'm working on a project which makes heavy use of inheritance on one entity, with a lot of overlapping fields, and it's tedious having to manually map the shared columns. I'm always going to want identical properties to share a database column, so is it possible to change the default behaviour to achieve this?

Apologies if I'm asking a question that's already been answered, but I've had a look through the docs and also through the issues here but can't find an answer

**Comment by AndriySvyryd** [comment]
Making this easier is tracked under https://github.com/dotnet/efcore/issues/9329
