### ISSUE TITLE
Memory Leak issue with EF Core with ODP.Net Core

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/efcore#25159]
we have recently migrated API service to EF Core with ODP.net Core.
We see the memory usage went up 1GB in and around 5 mins of usage.
we have observed that memory usage for following OracleInternal Objects are causing this issue

Object Type							Count	Size (Bytes)	Inclusive Size (Bytes)	Module	
 OracleInternal.ServiceObjects.DataUnmarshaller	        	858	135,595,448	135,595,448	Oracle.ManagedDataAccess.dll
 OracleInternal.ServiceObjects.OracleConnectionImpl		73	17,204,520	159,984,712	Oracle.ManagedDataAccess.dll
 OracleInternal.ServiceObjects.CachedStatement			1,765	6,269,888	140,517,248	Oracle.ManagedDataAccess.dll
 Dictionary<String, OracleInternal.ServiceObjects.CachedStatement>	73	2,258,368	132,589,808	System.Private.CoreLib.dll
 + OracleInternal.ConnectionPool.OraclePoolManager	3	121,184	146,906,752	Oracle.ManagedDataAccess.dll

We are using Startup class to for DBConexts to injected to other classes.
Could you please suggest how we can fix this memory leak issue
![MemoryLeakGraph](https://user-images.githubusercontent.com/3326148/123531281-e8a71780-d6c8-11eb-8cd8-c1be54cf85dd.PNG)
![MemoryLeakSplitOfObjects](https://user-images.githubusercontent.com/3326148/123531285-ef358f00-d6c8-11eb-85fe-e67548ad18f0.PNG)

**Comment by AndriySvyryd** [comment]
This looks like an issue with the Oracle provider, please contact Oracle for assistance.
