### ISSUE TITLE
Filtered include on Entity Framework Core

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/efcore#25162]
I have been reading the link below:
https://docs.microsoft.com/en-gb/ef/core/querying/related-data/eager#filtered-include

> Caution
> 
> In case of tracking queries, results of Filtered Include may be
> unexpected due to navigation fixup. All relevant entities that have
> been queried for previously and have been stored in the Change Tracker
> will be present in the results of Filtered Include query, even if they
> don't meet the requirements of the filter. Consider using NoTracking
> queries or re-create the DbContext when using Filtered Include in
> those situations.
> 
>  Note
> 
> In case of tracking queries, the navigation on which filtered include
> was applied is considered to be loaded. This means that EF Core will
> not attempt to re-load it's values using explicit loading or lazy
> loading, even though some elements could still be missing.

    var orders = context.Orders.Where(o => o.Id > 1000).ToList();
    
    // customer entities will have references to all orders where Id > 1000, rather than > 5000
    var filtered = context.Customers.Include(c => c.Orders.Where(o => o.Id > 5000)).ToList();

It seems to me that **using Include with Tracking queries is error prone**. Because you have to make sure no tracking queries have been used before Filtered Include is used.

Is there a way to prevent it and make code more robust?

Please correct me if it is wrong.

**Comment by AndriySvyryd** [comment]
You could use [DbContextFactory](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor) to create a fresh context.

**Comment by AndriySvyryd** [comment]
If you want to isolate the methods without creating a new context you'd need to use non-tracking queries. There's really no in-between solution with how tracking works in EF Core.

Related to https://github.com/dotnet/efcore/issues/11564

**Comment by PingPongSet** [comment]
@AndriySvyryd

Thanks. That was what I wanted to confirm. 

If non-tracking query is the only option, I think this Filtered Include is error prone. 

I wonder if NHibernate will have the similar issue.

**Comment by ajcvickers** [comment]
@PingPongSet It is error prone to use a single context instance for multiple units of work, regardless of whether you use filtered Include or not.

**Comment by emperador-ming** [comment]
Definitely, it’s error-prone. A strange bug was caught in UAT due to a filtering navigation property that didn’t meet the filter requirements
