### ISSUE TITLE
Do not use discriminaton in derived class with no new  primitive type properties.

### ISSUE THREAD

**Issue by pank85** [dotnet/efcore#25180]
Hello,

I want to be able to create derived models, which will only have navigation properties , without creating a discriminator field.

What i am trying to do is this:

I have two projects that share a model, the second project inherits the first and has some extra features.
In the second project i need to add some navigation properties to the shared model, so i created a new model, which inherits from the  base project's model and has some extra navigation properties.

E F  automatically creates and uses a discriminator to identify the type, but in my case this is no needed as the derived class will only have navigation properties.

Here is a sample code

```
Class Base {
        public int Id{ get; set; }
        public string Description { get; set; }
}

Class Derived: Base{
  public ICollection<Detail> Details{ get; set; }
}

Class  Detail
{
        public int Id{ get; set; 
        public string Description { get; set; }
        public  decimal Amount {get;set;}
}

I 

```
I believe that it would be a good idea to skip the use of discriminator, in cases where derived models does not add new columns to the database.

Thank You

**Comment by AndriySvyryd** [comment]
EF needs a discriminator to determine whether an object of type `Base` or `Derived` should be created.
