### ISSUE TITLE
Can we create an extension method which will translate the STRING_SPLIT function of the SQL Server?

### ISSUE THREAD

**Issue by amoldorkar-ezest** [dotnet/efcore#25198]
I would like to perform an inner join on the comma-separated string by doing the STRING_SPLIT as we usually do in the SQL Server but this is missing in the LINQ of the EF core, OR is there any other option to do so?

**Comment by amoldorkar-ezest** [comment]
I would like to perform an inner join on the comma-separated string by doing the STRING_SPLIT as we usually do in the SQL Server but this is missing in the LINQ of the EF core

**Comment by AndriySvyryd** [comment]
@smitpatel cc

**Comment by smitpatel** [comment]
You can use `STRING_SPLIT` function using [TVF feature](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping#mapping-a-queryable-function-to-a-table-valued-function). That way result of string_split becomes a regular entity which you can use inside EF Core query.
