### ISSUE TITLE
Reverse engineer error: Unable to launch 'dotnet' version 3.1. Do you have the runtime installed?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/efcore#25195]
Getting, Reverse engineer error: Unable to launch 'dotnet' version 3.1. Do you have the runtime installed?
I Opened my project on new machine that does not have 3.1 installed only .NET 5 and .NET 6.

Does it need to have 3.1 installed or can it be configured to use the newer version ?

 Check with 'dotnet --list-runtimes'
Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ErikEJ** [comment]
This looks like an error message from EF Core Power Tools, and yes, currently, you need to have the .NET Core 3.1 x64 runtime installed.
