### ISSUE TITLE
EF Core In Memory Provider Data Sharing Question

### ISSUE THREAD

**Issue by fahrigoktuna** [dotnet/efcore#25206]
Hi everyone,

I'm able to execute ef core with in memory provider in my local enviroment. What I want to achive that, is that possible to when I publishedd this app instance behind load balancer(as 2 nodes) sharing those in memory data between behind nodes?

I'm using this feature as previewing and application, so that my published apps already stored in postgresql environment

but I would like to create a preview enviroment for test data not affecting real postgresql environment.

Is there any solutions that springs to mind to offer me? (Maybe provider like redis, or something like that..)

**Comment by AndriySvyryd** [comment]
It's recommended to use a temporary postgresql database instead. Not only will you be able to share it easily it will also behave in the same way as the production environment and avoid having to deal with potential issues that arise from using a different environment.
