### ISSUE TITLE
Concurrency with a shared transaction

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#25201]
Reading the [document on shared transactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions), I am not clear on what the requirements are for concurrency when you have multiple DbContexts sharing a transaction that was begun by one of them. 

Are the multiple DbContexts allowed to read and write (SaveChanges) at the same time? Will a lower-end database like SQLite break under simultaneous reads mixed with writes? 

Hoping there is some performance gain when using SQL Server or similar. 

sjb

**Comment by AndriySvyryd** [comment]
To be able to share a transaction the contexts would need to share the connection and the `DbConnection` is not thread safe, so you can't reliably perform the operations concurrently. Even if you use some mechanism to serialize access to the underlying connection some operations could take a lock in the database until the transaction is committed, so if you issue another operation that would need to take the same lock you can end up with a deadlock.
