### ISSUE TITLE
Add support for basic DateTime properties

### ISSUE THREAD

**Issue by SparkyTD** [dotnet/efcore#25212]
I would like to be able to use some basic date functions like YEAR(), MONTH(), DAY(), HOUR(), etc.. on columns that are mapped to a DateTime property, but this currently seems to be impossible. For example, with basic MySQL, it would look like this:
```mysql
SELECT * FROM orders GROUP BY DAYOFMONTH(orders.date)
```
This statement should be the equivalent of the following query:
```c#
var query = database.Orders
    .GroupBy(o => o.Date.Day);
```
But currently EF Core is unable to translate this to the corresponding SQL statement.

I would like to see all the DateTime functions and properties mapped to EF Core databases.

Some more examples: 

- DateTime.Year -> YEAR(date)
- DateTime.Month -> MONHT(date)
- DateTime.Day -> DAY(date)
- DateTime.DayOfWeek -> DAYOFWEEK(date)
- DateTime.DayOfYear -> DAYOFYEAR(date)
- DateTime.Hour -> HOUR(date)
- etc...

**Comment by ErikEJ** [comment]
Which MySql provider do you use?
It sounds like a provider specific issue.

Have you tried the Pomelo provider?

**Comment by SparkyTD** [comment]
> Which MySql provider do you use?
> It sounds like a provider specific issue.
> 
> Have you tried the Pomelo provider?

I'm using Pomelo, and I get the usual error that says it can't evaluate the query on the server side.

**Comment by smitpatel** [comment]
This issue should be reported to the provider you are using. We translate most of above properties. See https://docs.microsoft.com/en-us/ef/core/providers/sql-server/functions#date-and-time-functions

**Comment by SparkyTD** [comment]
Oh, that's my bad. Sorry for opening the issue.
