### ISSUE TITLE
OrderBy().FirstOrDefault(<condition>) vs. Where(<condition>).OrderBy().FirstOrDefault()

### ISSUE THREAD

**Issue by TheVanice** [dotnet/efcore#2521]
Hello!
I'm having a strange issue which I've already posted on stackoverflow http://stackoverflow.com/questions/31162938/orderby-firstordefaultcondition-vs-wherecondition-orderby-firstorde
Is this a Bug or am I doing something wrong?

**Comment by rowanmiller** [comment]
@maumar has provided an answer on the StackOverflow post
