### ISSUE TITLE
How to set a auto-increment key field in EF7?

### ISSUE THREAD

**Issue by Pedrazl** [dotnet/efcore#2522]
I have tried several ways but no way, with Fluentapi:
  builder.Entity<Terremoto>().Property(t => t.Id).GenerateValueOnAdd(true);
...and with Data Annotations:
[Key,DataBaseGenerateOption(DataBaseGenerateOption.Identity)]

None of this methods actually works.

**Comment by ErikEJ** [comment]
If you are using the latest nightly, SQL Server will use Identity by convention for columns named Id. Or you can set the StoreGeneratedPattern

**Comment by Pedrazl** [comment]
Ok, thank you Erik, I´ll try that.
