### ISSUE TITLE
Can't find single property and navigate related data without IQueryable all properties

### ISSUE THREAD

**Issue by BretMishler** [dotnet/efcore#25221]
I have relational data properties on my objects that I would like to access:

```
    public class Person
    {
       public ICollection<Address> Addresses { get; private set; } = new Collection<Address>();
       ...
    }
```
    
```
    public class Address
    {
       ...
       public int PersonId { get; set; }
       public Person Person { get; set; }
       ...
    }
```

The only way I have found to traverse, or even exercise, this navigation property without lazy loading (and pulling in proxies, etc) is to eager load it:

```
    var entityList = await _context.Persons.Where(p => p.Id == request.PersonId)
        .Include(p => p.Addresses)
        .ToListAsync();
```

which is inconvenient because now I always have to do the following in order to cleanly access the class (and its properties):

`    var person = entityList.FirstOrDefault();`

Every example in the [Microsoft docs][1]:

```
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .ToList();
```

they grab **every blog entity**, instead of just a single one, before loading in related data.

I can't Explicitly load because that relies on the [`public virtual EntityEntry<TEntity> Entry<TEntity>(TEntity entity)`][2] which I can't accesses via my injected `DbContext` interface.

Is there a cleaner way to do this without the IQuerable `where` expression? I simply want to find my single entity and navigate its properties.

  [1]: https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager
  [2]: https://github.com/dotnet/efcore/blob/106ac1ab4f0948ad52ca7318d376b1def9148321/src/EFCore/DbContext.cs#L915

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
You can write query like this also
```C#
   var person = await _context.Persons.Where(p => p.Id == request.PersonId)
        .Include(p => p.Addresses)
        .FirstOrDefaultAsync();
