### ISSUE TITLE
EF Core Cosmos: Owned Embedded id property not persisted

### ISSUE THREAD

**Issue by jcookpob** [dotnet/efcore#25232]
Have an existing cosmosdb database with over a billion docs so changing schema is a little difficult.

One of our embedded owned properties is Tags which is an ICollection<Tags> Tags {get; set;} = new HashSet<Tags>(); 
we have another property that is similar and works great but the only difference is that Tag has 2 properties id and name.  I can't find a way to get id to save to cosmos using EF Core 5 and i am assuming because EF is using this property name under the hood for tracking purposes.  Instead of changing the property field to something other than id which appears to work fine and try to update over a billion documents is there a way to configure EF Core 5 to use a different field for its indexing so we can continue using the id property?

![image](https://user-images.githubusercontent.com/18537904/125137737-e8e4e100-e0d2-11eb-856e-27d58ce4aa4e.png)

No matter what i do i can't get ef to save the id value I set in code but it does save the name property to cosmos.  When i read the record back through EF Core it has a generated value in the id property.

![image](https://user-images.githubusercontent.com/18537904/125137957-54c74980-e0d3-11eb-8822-83d860f14244.png)

![image](https://user-images.githubusercontent.com/18537904/125137892-37927b00-e0d3-11eb-9233-86cdb78aa327.png)

currently using .NET 5
EntityFrameworkCore v5.0.7
EntityFrameworkCore.Cosmos v5.0.7
and Microsoft.Azure.Cosmos v3.20.1

**Comment by AndriySvyryd** [comment]
You need to explicitly set the json property name to make sure that it's stored:
```C#
entity.OwnsMany(
    j => j.Tags, b =>
        {
            b.Property(p => p.id).ToJsonProperty("id");
        })
```

**Comment by AndrewTriesToCode** [comment]
@AndriySvyryd 

I ran into this and yes setting the JSON property on Id seems to work around it, but it seems like that should maybe be the default behavior?

When would you ever **not** want to have it persisted?

Without persisting it any call to `SaveChanges` results in a local copy that has invalid Id values for all but the last owned item in the collection resulting in an exception if any subsequent `SaveChanges` are called within the same scope.
