### ISSUE TITLE
Migrations: Drop generated column should come before dropping the columns it's generated from

### ISSUE THREAD

**Issue by benstevens48** [dotnet/efcore#25237]
Using EF core 5, I removed three columns from my model, with the third column being of type NpgsqlTsVector and computed from the other two via HasGeneratedTsVectorColumn. When I generated the SQL using migrations, it tried to drop the generated column after the other two. However, PostgreSQL doesn't seem to like this - I guess the generated column is already dropped when the columns it's generated from are dropped. It would be good if the order was changed so the generated column was dropped first.

**Comment by roji** [comment]
Thanks, this repros for me with SQL Server as well - simply trying to drop two columns, where one is computed and depends on the other, may fail depending on the drop order. We should probably order column drop operations so that computed columns are dropped first.

<details>
<summary>Repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Blog>().Property(b => b.Y).HasComputedColumnSql("X + 1");
}

public class Blog
{
    public int Id { get; set; }
    public int X { get; set; }
    public int Y { get; set; }
}
```

</details>
