### ISSUE TITLE
Elasticsearch provider

### ISSUE THREAD

**Issue by YohanSciubukgian** [dotnet/efcore#25270]
As document databases like CosmosDB are now supported by EF Core, could it be possible to consider having an ElasticSearch provider ?

AFAIK, EF Core relies on the CosmosDB SDK for its implementation.
For Elasticsearch, NEST provides a solid baseline with attributes mapping etc that could be used to defined structures on which EF Core could relies on to request data.

**Comment by ajcvickers** [comment]
@YohanSciubukgian We don't have any plans for the team to create an Elasticsearch provider. That being said, EF Core is designed to allow third-party providers, of which [there are many](https://docs.microsoft.com/en-gb/ef/core/providers/?tabs=dotnet-core-cli), both community driven (e.g. PostgeSQL, MySQL) and commercial (e.g. Oracle, IBM.) The Cosmos provider would be a good place to start for a document database, and our [test suites are published on NuGet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Specification.Tests/) so you can run the same set of tests that we use in the repo.
