### ISSUE TITLE
Document for contributors how to allow missing headers and doc comments in developer builds

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25278]
See https://github.com/dotnet/efcore/pull/23324

**Comment by ZarakiKanzaki** [comment]
@ajcvickers Hi! I didn't really understand what should be done, may I have  more info about it?
thanks in advance

**Comment by ErikEJ** [comment]
@ZarakiKanzaki I think this is about adding the info from #23324 to the[ contribution document](https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md)

**Comment by ZarakiKanzaki** [comment]
> @ZarakiKanzaki I think this is about adding the info from #23324 to the[ contribution document](https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md)

Thanks for the answer, I'll post a PR with the changes following all the guidelines :)

**Comment by ZarakiKanzaki** [comment]
@ajcvickers  Is there a way to link you as a reviewer to the Pr?

**Comment by roji** [comment]
@ZarakiKanzaki we get notifications on new PRs and review them as soon as we can (but that can take time, we're quite busy with other things at the moment). There's no specific need to mark anyone as a reviewer.

**Comment by ZarakiKanzaki** [comment]
> @ZarakiKanzaki we get notifications on new PRs and review them as soon as we can (but that can take time, we're quite busy with other things at the moment). There's no specific need to mark anyone as a reviewer.

I see! thank you for your reply :)
