### ISSUE TITLE
[BUNDLES] Suggestion to show the full path of the bundle .exe file

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#25274]
Running: 

    Bundle-Migration

Does not show the location of the generated bundle.exe file.

It would be very handy to know.

```
Building bundle...
Bundle created: C:\Code\BundleTester\Bundle.exe
Done.
```

EF Core version: Latest daily build

**Comment by bricelam** [comment]
Closing. Work is tracked by #19693
