### ISSUE TITLE
New deferred attribute missing from BeginTransactionAsync

### ISSUE THREAD

**Issue by mind-bending-forks** [dotnet/efcore#25280]
Microsoft.Data.Sqlite version: 5.0.8
Target framework: .NET 5.0
Operating system: Linux

Support for deferred transactions was recently added (#21212), which is great, thanks. However, the deferred argument is not currently available via asynchronous calls (whereas everything else I have used so far is). So:

```csharp
using ( System.Data.Common.DbTransaction transaction = sqliteConnection.BeginTransaction(deferred: true))
{
  ...
```

builds fine, whereas 

```csharp
using ( System.Data.Common.DbTransaction transaction = await sqliteConnection.BeginTransactionAsync(deferred: true))
{
  ...
```
reports

> The best overload for 'BeginTransactionAsync' does not have a parameter named 'deferred'

or alternatively, if the deferred argument is not named, the following is reported

> Argument 1: cannot convert from 'bool' to 'System.Data.IsolationLevel'

Assuming its possible to add it, support for deferred transactions via asynchronous calls too would be very welcome. Thanks.

**Comment by ajcvickers** [comment]
Note for triage: SqliteConnection does not have any async BeginTransacation methods, likely because it is never an async operation on SQLite, so this seems like by-design. /cc @bricelam

**Comment by bricelam** [comment]
Yeah, by design. Don't use the async versions unless you're using `DbConnection` polymorphically (in which case you can't use deferred). See [Async limitations](https://docs.microsoft.com/dotnet/standard/data/sqlite/async) in the docs for more details.

**Comment by mind-bending-forks** [comment]
@bricelam, if I've understood your first comment about polymorphism correctly, you're saying that if I wanted to code support other types of database connection - which themselves might support async operations, then you could use the async versions of the methods. However, you would need to do so knowing that they don't operate in asynchronously way when used with Sqlite.

Thanks both for the clarification.

**Comment by bricelam** [comment]
Correct. Put another way: Using the async versions on SQLite only adds overhead actually making your database calls *less* responsive. Theses APIs are only implemented on SQLite to make it compatible (at least functionally) with other ADO.NET providers.
