### ISSUE TITLE
EF Core 6.0.0 Preview-6 no longer compatible with .NET 5.

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/efcore#25282]
## File a bug

Trying to update the EF Core packages to Preview-6 results in the following:

```
Checking compatibility for Microsoft.EntityFrameworkCore 6.0.0-preview.6.21352.1 with net5.0.
Package Microsoft.EntityFrameworkCore 6.0.0-preview.6.21352.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore 6.0.0-preview.6.21352.1 supports: net6.0 (.NETCoreApp,Version=v6.0)
Checking compatibility for Microsoft.EntityFrameworkCore.SqlServer 6.0.0-preview.6.21352.1 with net5.0.
Package Microsoft.EntityFrameworkCore.SqlServer 6.0.0-preview.6.21352.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore.SqlServer 6.0.0-preview.6.21352.1 supports: net6.0 (.NETCoreApp,Version=v6.0)
Checking compatibility for Microsoft.EntityFrameworkCore.Sqlite 6.0.0-preview.6.21352.1 with net5.0.
Package Microsoft.EntityFrameworkCore.Sqlite 6.0.0-preview.6.21352.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore.Sqlite 6.0.0-preview.6.21352.1 supports: net6.0 (.NETCoreApp,Version=v6.0)
Checking compatibility for Microsoft.EntityFrameworkCore.Tools 6.0.0-preview.6.21352.1 with net5.0.
Package Microsoft.EntityFrameworkCore.Tools 6.0.0-preview.6.21352.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore.Tools 6.0.0-preview.6.21352.1 supports: net6.0 (.NETCoreApp,Version=v6.0)
Checking compatibility for Spontane.MobileAppService 1.0.0 with net5.0.
Checking compatibility for Microsoft.EntityFrameworkCore.Design 6.0.0-preview.6.21352.1 with net5.0.
Package Microsoft.EntityFrameworkCore.Design 6.0.0-preview.6.21352.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore.Design 6.0.0-preview.6.21352.1 supports: net6.0 (.NETCoreApp,Version=v6.0)
Package restore failed. Rolling back package changes for 'MyProject.MobileAppService'.
```

6.0.0 Preview-5 and below packages were still compatible with .NET 5. All other ASP.NET Core 6 preview packages (like caching) are compatible with .NET 5.

Is it intentional that .NET 5 support was pulled? If so, please reconsider because it is important that we test the preview releases before release, and requiring .NET 6 support makes it not really feasible at least for me to test these packages anymore (I am using Azure App Service and don't want to go through the hoops to migrate my entire server to .NET 6 Preview). Furthermore, no other ASP.NET packages seem to require .NET 6.

If this was unintentional, could a new preview release be released very quickly as 6.0.0 Preview-6 is not really usable for a lot of us because of the .NET 6 Preview dependency.

Thank you.

### Include provider and version information

EF Core version: 6.0.0-preview.6.21352.1
Database provider: Any
Target framework: 5.0
Operating system: macOS Big Sur
IDE: VS For Mac 8.10.6

**Comment by ErikEJ** [comment]
Yes, this was intentional. Eventually, ASP.NET Core will also only run on .net 6.

You can also use .net 6 with app service https://azure.github.io/AppService/2021/04/15/Running-dotnet-6-Preview-on-App-Service.html

**Comment by Tommigun1980** [comment]
> Yes, this was intentional. Eventually, ASP.NET Core will also only run on .net 6.
> 
> You can also use .net 6 with app service https://azure.github.io/AppService/2021/04/15/Running-dotnet-6-Preview-on-App-Service.html

Thank you, but I am using VS For Mac so those options aren't available to me. I also don't want to add the extreme overhead of starting to package my apps with the runtime, as right now I can just easily deploy from VS For Mac with one click while developing.

Would you reconsider the decision as other ASP.NET Core 6.0.0 Preview packages don't seem to have this restriction yet? Or at least release one more preview build of EF Core without said requirement, as Preview-5 narrowly missed out on a critical fix I was waiting for?

Thank you!

**Comment by ErikEJ** [comment]
I doubt you can expect that level of support for beta software...

I assume you have other development environment options available?

**Comment by Tommigun1980** [comment]
> I doubt you can expect that level of support for beta software...
> 
> I assume you have other development environment options available?

It’s not really my loss, I just prefer using preview packages to be proactive about issues so that they can be solved early.

If I have to go out of my way to help test them it’s not really a tenable situation.

Thank you.
