### ISSUE TITLE
Sql Server built in TVF being escaped in 5.x

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#25296]
@smitpatel 

I am trying to use the built in TVF OPENJSON.  In the 5.x branch the TVF call is being escaped by brackets [] and thus failed.  
I tried the latest 6.x and this has been fixed.  

Do you know of any way to make this work in 5.x?  I couldn't think of any. 

Oh the irony - the first time I try to use TVF at work and I find an edge case I missed in the original code :(

**Comment by smitpatel** [comment]
https://github.com/dotnet/efcore/issues/24569

The only way to fix this in 5.x would be replacing the service. Not too complicated but remember to derive from provider specific generator which may be using EFCore internal code. 
We will discuss in triage if we want to patch this.

**Comment by pmiddleton** [comment]
Thanks @smitpatel that worked.  I should have thought about replacing the whole sql generator.  

One thing you might want to consider is exposing the ISqlGenerationHelper via a property like you did with IRelationalCommandBuilder in QuerySqlGenerator.  No biggie as you can just pull another copy out of the dependencies in the derived class

**Comment by smitpatel** [comment]
> One thing you might want to consider is exposing the ISqlGenerationHelper via a property like you did with IRelationalCommandBuilder in QuerySqlGenerator. 

Command builder is there because it is instance value. Factory for that is service, when generating command we create new builder.
`ISqlGenerationHelper` should be available to access via `Dependencies.SqlGenerationHelper`

**Comment by ajcvickers** [comment]
We discussed this in triage and we're not going to patch 5.0 at this time since it is an edge case and there is a workaround.
