### ISSUE TITLE
Cannot change the base class of ApplicationDbContext

### ISSUE THREAD

**Issue by avinashtauro-arctechinfo** [dotnet/efcore#25302]
ApplicationDbContext which is auto generated always has DbContext as the base class.
We use Identity and need the base class to be IdentityDbContext<ApplicationUser, IdentityRole, string>

Currently our developers, copy-paste this base class after every reverse engineering task, and add the using's for these. Though it takes only a few seconds , would be good if there is an option in settings to specify base class instead of DbContext.

**Comment by ajcvickers** [comment]
This is covered by #4038.
