### ISSUE TITLE
Is there a way to accidentally configure efcore to eagerly fetch by default?

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#25308]
I've got a very simple example where I've mapped users with a one to many with contacts. I've validated that my configuration results in a `Users` table, and a `Contacts` table, and that the typical pk/fk relationships exist. I then populated a few entries in the db with their respective contacts.

Where I'm running into some serious confusion is in simply calling `context.Users.ToListAsync()` is returning users objects with contacts being populated.

My understanding is that without explicitly calling `.Include(x=>x.Contacts) `, contacts should effectively be returned as null, or an empty collection.

I've attached code/pseudo code in hopes that I maybe misconfigured something. Is it possible I've configured something wrong. As you can see the query output seems right, but the returned users definitely do have contacts populated on them when I browse the object in the debugger etc. I'm very confused as to how this could be happening.

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: Net5.0
Operating system: Windows 10 20H2
IDE: Visual Studio 2019 16.9.6

**Test.cs**
``` cs
 [Fact]
 public async Task ContactsShouldntPopulateByDefault()
 {
       var users = await _fixture.Context.Users.ToListAsync();
       var hasContacts = users.Any(x => x.Contacts.Count > 0);
       _fixture.WriteLine($"Has Contacts: {hasContacts}");
       Assert.False(hasContacts);
 }
```

The query/test output logged out as:
``` sql
SELECT "u"."Id", "u"."Age", "u"."BirthDate", "u"."Created", "u"."FirstName", "u"."LastName", "u"."Modified"
FROM "Users" AS "u"
-- there are additional fields reported here that ARE on the entities, but removed from the classes for brevity

Has Contacts: True
```

**User.cs**
``` cs
public class User {
   public int Id {get;set;}
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public int Age { get; set; }
   public DateTimeOffset BirthDate { get; set; }
   public List<Contact> Contacts { get; set; } //tried this as ICollection<T> as well, made no difference
}
```

**Contact.cs**
``` cs
public class Contact
{
     public int Id {get;set;}
     public int UserId { get; set; }
     public string Name { get; set; }
     public string Address { get; set; }
     public string PhoneNumber { get; set; }
     public TestUser TestUser { get; set; }
}
```

**TestDbContext.cs**
``` cs
 protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
        modelBuilder.Entity<User>(u =>
        {
            u.HasMany(u => u.Contacts)
                .WithOne(c => c.User);
        });
 }
```

**Comment by smitpatel** [comment]
This happens where contacts are already being tracked by context. When doing a tracking query, EF Core will fix-up navigations in query results with already tracked instances. So as side-effect you may see data in navigations which were not asked to be reloaded. Make sure that you are using fresh dbcontext instance which has no entities being tracked if you want to make sure that navigations remain unpopulated.

**Comment by ronnyek** [comment]
I feel like this is less than desirable... when I have a bit of code that expects to fetch users without contacts, but then it can sometimes be populated with contacts solely based on the fact that its already present in the tracked context. You can fetch user and get 0 contacts or null (whatever actually happens) but you dont know if there are actually 0 contacts, or they are just not being included

**Comment by smitpatel** [comment]
Hence, DbContext is supposed to be as unit of work. If you are starting a new query to perform some work on it, you should have a fresh DbContext which is not tracking any existing entities.

**Comment by ronnyek** [comment]
> Hence, DbContext is supposed to be as unit of work. If you are starting a new query to perform some work on it, you should have a fresh DbContext which is not tracking any existing entities.

Literally just updated my last comment to say this very thing. Appreciate the input and sanity checking. I'll close this
