### ISSUE TITLE
PossibleIncorrectRequiredNavigationWithQueryFilterInteractionWarning with table by hierarchy and navigations

### ISSUE THREAD

**Issue by phija** [dotnet/efcore#25300]
Hi all,

I am using EF Core 5.0.3 and have some nested entities with also Table per Hierarchy (TPH) in place.
I also make use of the AspNet Boilerplate (ABP) and AspNetZero packages which provide global query filters for soft delete and multi tenancy functionality. (interfaces are IMayHaveTenant, IMustHaveTenant and ISoftDelete). I use only IMayHaveTenant at the moment.
In detail the entities look like this:

```C#
public class Base : Entity<Guid>, IMayHaveTenant
{
    public int? TenantId { get; set; }
    ...
}

public class A : Base
{
    public B InnerPart { get; set; }
    ...
}

public class B : Entity<Guid>, IMayHaveTenant
{
    public int? TenantId { get; set; }
    ...
}
```

My DbContext and model configuration look like this:
```C#
public class MyDbContext : AbpZeroDbContext<Tenant, Role, User, Ptw100DbContext>, IAbpPersistedGrantDbContext
{
    public DbSet<A> As { get; set }
    public DbSet<B> Bs { get; set }
    ...

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<A>(b =>
        {
            b.HasOne(p => p.InnerPart).WithOne().HasForeignKey<A>("InnerPartId");
        }
    }
}
```

I need that explicit navigation statement because otherwise eager loading is not working with tracking the entities.
But when running the application I get the EF Core warning:
```
.. [WRN] { Id: 10622, Name: "Microsoft.EntityFrameworkCore.Model.Validation.PossibleIncorrectRequiredNavigationWithQueryFilterInteractionWarning" } Entity '"B"' has a global query filter defined and is the required end of a relationship wit
h the entity '"A"'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=21
31316 for more information.
```

The point is: I don't want to make the navigation optional because it is not. If there is no ```B``` then there is something broken and ```A``` is not in a state how it should be.

I investigated by debugging a query to identify the global query filters to possibly match them on the parent entity type but the resulting query for a single query shows me it is basically just the IMayHaveTenant (?correct me if I'm wrong!) which is not seen as it maybe should be:
```SQL
DECLARE @__ef_filter__p_2 bit = CAST(0 AS bit);
DECLARE @__ef_filter__CurrentTenantId_3 int = 1;
DECLARE @__ef_filter__p_0 bit = CAST(0 AS bit);
DECLARE @__ef_filter__CurrentTenantId_1 int = 1;
DECLARE @__id_0 uniqueIdentifier = 'b9ded491-8651-469d-8e53-08d94a9dde27';

SELECT [r].[Id], ..., [r].[TenantId], ..., [d].[Id], ..., [t].[Id], ..., [t].[TenantId]
FROM [Base] AS [r]
INNER JOIN [A] AS [d] ON [r].[Id] = [d].[Id]
INNER JOIN (
    SELECT [i].[Id], [i].[CreationTime], [i].[CreatorUserId], [i].[LastModificationTime], [i].[LastModifierUserId], [i].[SamplingTime], [i].[TenantId]
    FROM [B] AS [i]
    WHERE (@__ef_filter__p_2 = CAST(1 AS bit)) OR ([i].[TenantId] = @__ef_filter__CurrentTenantId_3)
) AS [t] ON [d].[SetupId] = [t].[Id]
WHERE ((@__ef_filter__p_0 = CAST(1 AS bit)) OR ([r].[TenantId] = @__ef_filter__CurrentTenantId_1)) AND ([r].[Id] = @__id_0)
```

### Question
How can I make the warning disappear without making the navigation optional?
Adding the global query filter to ```A``` is not possible because then I get an error that it needs to be added to the base class (don't remember the exact error here). Adding it to ```Base``` doesn't make sense because there it is already existing.

Thanks for any help!

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: windows 10
IDE: independent

**Comment by smitpatel** [comment]
> The point is: I don't want to make the navigation optional because it is not. If there is no B then there is something broken and A is not in a state how it should be.

The warning is for the case when things could be broken in database since it is dependent on data. But if you are sure that data doesn't have invalid state then you can ignore the warning using following
```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .ConfigureWarnings(b => b.Ignore(CoreEventId.PossibleIncorrectRequiredNavigationWithQueryFilterInteractionWarning));
```

**Comment by phija** [comment]
Thanks for the reply! With switching off the warning by ```ConfigureWarnings``` I turn off those warnings globally. This is not exactly what I was looking for.
I was hoping to be able to "clean" the entity-specific warnings by telling EF Core that the configuration is ok for exactly those entities. If later other entities are added I would like to see the warning again for the new ones if they are adequate.

In my opinion the pattern to warn about something and then not being able to clean up the warnings specifically is a (small) gap that could be enhanced in the future. Think about other situations of life in general where false warnings are seen more critical because they lead to ignorance by the user for other warnings to pop up.
