### ISSUE TITLE
Unable to generate the model because of the following exception: 'System.TypeLoadException: Could not load type 'System.Data.Entity.Core.Mapping.StorageEntityContainerMapping' from assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

### ISSUE THREAD

**Issue by GusGus2008** [dotnet/efcore#2530]
Hi, I have met very strange problem, I can't generate the model using DataBase first mode.
it said:
Unable to generate the model because of the following exception: 'System.TypeLoadException: Could not load type 'System.Data.Entity.Core.Mapping.StorageEntityContainerMapping' from assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

can anyone tell me how to fix this?
I am using VS2013 & SQL Server 2012
The entityframework version is 6.1.3

Thanks

**Comment by smitpatel** [comment]
@GusGus2008 This repo is for EF 7. You can file issues for EF 6 on our Codeplex project at https://entityframework.codeplex.com.

**Comment by rowanmiller** [comment]
When you open the issue on CodePlex be sure to include details of how to reproduce the issue
