### ISSUE TITLE
ExecuteSqlRaw fails due to classifying null byte array parameter as nvarchar(4000) instead of varbinary

### ISSUE THREAD

**Issue by ognamala** [dotnet/efcore#25310]
Hi everyone, I have been using the library quite successfully for a long time, however I have just encountered a peculiar issue. 

I recently needed to perform a change in the parameters we pass for ExecuteSqlRaw, specifically we are now passing null byte arrays on some occasions:

```
byte[] p1 = null;
byte[] p2 = null;
byte[] p3 = null;

_context.Database.ExecuteSqlRaw("[REDACTED SQL SCRIPT]", "Test", p1, p2, p3);
```

However, this causes ExecuteSqlRaw to fail with the following error:

`Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:`

Hence I decided to take a look at the profiler to take a look at what is actually being executed, which results in the following unexpected script:

`exec sp_executesql N'[REDACTED SQL SCRIPT]',N'@p0 nvarchar(4000),@p1 nvarchar(4000),@p2 nvarchar(4000),@p3 nvarchar(4000)',@p0=N'Test',@p1=NULL,@p2=NULL,@p3=NULL`

As you can see all 3 parameters (p1, p2 and p3) have been assigned type nvarchar(4000) when in fact they should be classified are varbinary and not as nvarchar(4000) - this later causes an issue in the (redacted) sql script as we assume that these have the correct type assigned by EFCore i.e. varbinary.

That said, in the normal case when the byte arrays passed to ExecuteSqlRaw have a value, then everything will work as expected and p1, p2 and p3 will be assigned the correct type varbinary in the profiler i.e:

`_context.Database.ExecuteSqlRaw("[REDACTED SQL SCRIPT]", "Test", new byte[32], new byte[32], new byte[32]);`

Which yields the following in the profiler (which is as expected)

`exec sp_executesql N'[REDACTED SQL SCRIPT]',N'@p0 nvarchar(8000),@p1 varbinary(8000),@p2 varbinary(8000),@p3 varbinary(8000)',@p0=N'Test',@p1=0x0000000000000000000000000000000000000000000000000000000000000000,@p2=0x0000000000000000000000000000000000000000000000000000000000000000,@p3=0x0000000000000000000000000000000000000000000000000000000000000000`

Hence, one would expect that when a null byte array is passed as a parameter, it would result in a varbinary classification as well. 

If this is not an issue, I am still very curious to at least know what is the logic behind such a decision as it is quite unexpected.

Thanks for your attention

**Comment by ajcvickers** [comment]
@ognamala This is because EF Core has no way to determine the type of the parameter if the value is null, which means SQL Server is using the default for the parameter type. You can pass `SqlParameter` objects to `ExecuteSqlRaw` instead of just the raw parameter values. This allows you to specify all the facets for the parameters explicitly, rather than having them inferred from the parameter value.

Note for triage: should we warn when we can't determine an appropriate parameter type? Always Encrypted means that parameters have to be exactly right in more cases now. This means we could also get it wrong for, for example, key verses non-key string parameters.

**Comment by ognamala** [comment]
@ajcvickers thanks for the reply, very helpful - this is what I assumed that it is due to the null and the inability to determine a type - although I did expect to some degree to receive a warning/exception that the type cannot be determined and will be defaults to nvarchar

Once again - thanks for the reply !

**Comment by ajcvickers** [comment]
Note from triage: leave as is. We could warn for nulls, but this is provider-specific and will create spurious warnings in many cases.
