### ISSUE TITLE
ChangeTracker.DebugView crashes when 2 Entities with different Id Types share the same OwnedEntity

### ISSUE THREAD

**Issue by Jejuni** [dotnet/efcore#25311]
## Description

When 2 entities that have different Id types (for instance `Guid` and `long`) share the same owned entity the debug view crashes with the exception `System.InvalidOperationException: 'Failed to compare two elements in the array.'`.
Exception details are below.

If I had to guess I'd say it's because internally it's expected that a single type can ever only have exactly one Id type, which is the case for most types. In the case of owned entities this is not necessarily the case, however, as shadow properties for the owning entity's `Id` may differ despite the owned entity having the same CLR type. As such the cast described in the exception fails.

![image](https://user-images.githubusercontent.com/33608497/126551190-582f7f5a-ae13-4db7-b1e5-d41272306747.png)

## Repo

A Repo to quickly demonstrate the bug can be found here:
https://github.com/Jejuni/EfCoreDebugViewProblem

You will have to change the connection string in the `TestDbContext`'s `OnConfiguring` to point to a valid SqlServer.

### Code

DbContext is configured with the required `.OwnsOne` calls and seeds the referenced data via `.HasData`.
See Repo for details

```cs
public class OwnedEntity
{
    public string Nothing { get; set; } = string.Empty;
}

public class LongEntity
{
    public long Id { get; set; }
    public OwnedEntity OwnedEntity { get; set; } = null!;
}

public class GuidEntity
{
    public Guid Id { get; set; }
    public OwnedEntity OwnedEntity { get; set; } = null!;
}

class Program
{
    static void Main(string[] args)
    {
        CreateDb();
        Test();
    }

    static void CreateDb()
    {
        using var ctx = new TestDbContext();
        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();
    }

    static void Test()
    {
        using var ctx = new TestDbContext();

        GuidEntity guidEntity = ctx.Set<GuidEntity>().Find(Guid.Parse("305BFC5B-8492-467D-AFAF-408BD36366BD"));
        LongEntity longEntity = ctx.Set<LongEntity>().Find(1L);

        string debugView = ctx.ChangeTracker.DebugView.ShortView;
    }
}
```

### Exception:

```cs
System.InvalidOperationException: 'Failed to compare two elements in the array.'

InvalidCastException: Unable to cast object of type 
'System.Func`2[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.Snapshot`1[System.Guid],System.Guid]' to type 
'System.Func`2[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.Snapshot`1[System.Guid],System.Int64]'.
```

### Include provider and version information

EF Core version: 5.0.8 (present in 5.0.0 - 5.0.8)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.10.3

**Comment by ajcvickers** [comment]
Verified that this is fixed in 6.0 preview 7

Output:
```
GuidEntity {Id: 305bfc5b-8492-467d-afaf-408bd36366bd} Unchanged
GuidEntity.OwnedEntity#OwnedEntity {GuidEntityId: 305bfc5b-8492-467d-afaf-408bd36366bd} Unchanged FK {GuidEntityId: 305bfc5b-8492-467d-afaf-408bd36366bd}
LongEntity {Id: 1} Unchanged
LongEntity.OwnedEntity#OwnedEntity {LongEntityId: 1} Unchanged FK {LongEntityId: 1}
```
