### ISSUE TITLE
Critical bug for production with EF 5.0.*: NullReferenceException hides actual exception

### ISSUE THREAD

**Issue by freerider7777** [dotnet/efcore#25320]
NullReferenceException hides the actual exception in EF5.
The details are in this issues, which were fixed for EF6

[https://github.com/dotnet/efcore/issues/23157](https://github.com/dotnet/efcore/issues/23157)
[https://github.com/dotnet/efcore/issues/24181](https://github.com/dotnet/efcore/issues/24181)

It is critical for production to get the actual information about an error. So for now we cannot use EF5 in prom.
There is a workaround with [FirstChanceException Event](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception?view=net-5.0) but it increases logs and complicates the investigation.

**Comment by ajcvickers** [comment]
@freerider7777 This does not meet the bar for patching the 5.0 release. See the [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for information on how we decide which issues to patch.

**Comment by freerider7777** [comment]
It's strange... Obvious bugs don't get fixes, which are "regression from previous release", this one, also my other found bugs:
[https://github.com/dotnet/efcore/issues/24914](https://github.com/dotnet/efcore/issues/24914)
[https://github.com/dotnet/efcore/issues/24745](https://github.com/dotnet/efcore/issues/24745)

EF 6 is not coming soon and we can't use current version...
