### ISSUE TITLE
EntityFrameworkCore.Tools stops Application Insights correlation for Azure Function Apps

### ISSUE THREAD

**Issue by Itamaram** [dotnet/efcore#25339]
After installing the `EntityFrameworkCore.Tools` (version 3.1.17) package in my function app project, my requests are no longer correlated in AppInsights. Additionally, most dependencies are also not tracked.

This is caused simply by installing the package, no additional steps need to be taken, and it is most apparent when looking at an end-to-end transaction in AppInsights in the portal, which looks like this:

![image](https://user-images.githubusercontent.com/25465/127095375-ce941b0d-5600-405c-9d0c-7b3485c74567.png)

Instead of like this:

![image](https://user-images.githubusercontent.com/25465/127095431-624583d3-a694-4f71-8039-d6c3ec7c53e8.png)

The trivial sample below, includes two functions with a service bus between them:

```csharp
    public class Function1
    {
        [FunctionName(nameof(Start))]
        public async Task<IActionResult> Start(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            [ServiceBus("%queueName%")] IAsyncCollector<Foo> collector, ILogger logger)
        {
            logger.LogInformation("Let's get started");
            await collector.AddAsync(new Foo());
            return new OkResult();
        }

        [FunctionName(nameof(Finish))]
        public void Finish([ServiceBusTrigger("%QueueName%")] Foo foo, ILogger logger)
        {
            logger.LogInformation("Done");
        }
    }

    public class Foo { }
``` 

This works for the following csproj file:
```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

But fails if a package reference is added to the aforementioned package, ie:
```csproj
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

[The complete sample is available here](https://github.com/Itamaram/AppInsightsDepTest)

The `Working` projects showcases the request correlation working as intended, and the `NotWorking` project, which only differs from the `Working` one in the one added dependency, does not.

**Comment by bricelam** [comment]
Does using version 3.0.3 of EFCore.Tools fix it?

If not, does adding this to your project file fix it?

```xml
<PropertyGroup>
  <GenerateRuntimeConfigurationFiles>False</GenerateRuntimeConfigurationFiles>
</PropertyGroup>
```

**Comment by Itamaram** [comment]
Yes, using version 3.0.3 resolves this issue. Would you like for me to try it with the `GenerateRuntimeConfigurationFiles` directive on either version?

**Comment by bricelam** [comment]
No need to try the other.

The Microsoft.NET.Sdk.Functions package has an exclusive upper bound on ASP.NET Core 3.1. By installing EF Core 3.1, I suspect we're bumping up a few transitive dependencies (Logging, etc.) that breaks the App Insights integration.

Is there a way to create a functions project targeting .NET Core 3.1?

**Comment by Itamaram** [comment]
I'm not sure I understand your question. This is for a functions project targeting .NET Core 3.1 or at least that's what I believe the `<TargetFramework>netcoreapp3.1</TargetFramework>` element in the csproj file means.

**Comment by ajcvickers** [comment]
Any further follow up on why Azure Functions require specific packages should be directed to the Functions team at https://github.com/Azure/Azure-Functions
