### ISSUE TITLE
Find() with AsNoTracking()

### ISSUE THREAD

**Issue by marceloodiniz** [dotnet/efcore#2533]
I've checked the Find() method on DbSet class can not be used together with AsNoTracking().
There are numerous situations where I need to use the Find() and do not put the object returned in context.
I would like to suggest this functionality within the Entity Framework.

Portugues:
Estive verificando que o método Find() da classe DbSet não pode ser usado junto com o AsNoTracking().
Existem inumeras situações em que preciso usar o Find() e não colocar o objeto retornado dentro do contexto.
Gostaria de sugerir essa funcionalidade dentro do Entity Framework.

**Comment by rowanmiller** [comment]
`AsNoTracking` doesn't really make sense for `Find` since one of the key features of find is that it will return the already tracked version of the entity without hitting the database if it is already in memory. If you want to load an entity by key without tracking it then use `Single`.

**Comment by satvik1986** [comment]
if i use if (lstemployeeRepository.Find(employee.LstEmployeeId)==null)
                return NotFound();

            if (!ModelState.IsValid)
            {
                return new UnprocessableEntityObjectResult(ModelState);
            }

            lstemployeeRepository.Update(employee);
Getting error "System.InvalidOperationException: 'The instance of entity type 'LstEmployee' cannot be tracked because another instance with the same key value for {'LstEmployeeId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'
"

**Comment by mrmartan** [comment]
I'm hitting the same issue.

```csharp
    var props = typeof(TState).GetProperties();
    var primaryKey = this.sqlStore.Model.GetEntityTypes().Single(et => et.ClrType == typeof(TState)).FindPrimaryKey();

    var keyValues = primaryKey.Properties.Select(p => props.Single(pp => pp.Name == p.Name).GetValue(state)).ToArray();

    var entity = await this.sqlStore.FindAsync<TState>(keyValues);
    if (entity == null)
    {
        this.sqlStore.Add(state);
    }
    else
    {
        this.sqlStore.Update(state);
    }
```

Now the Update() fails because `entity` and `state` have the same value of key (as intended). I cannot really use Single() here as I am relying on the "dynamic/untyped" nature of Find().

**Comment by ajcvickers** [comment]
@satvik1986 @mrmartan Can you file new issues for the problems you are seeing, including a runnable project/solution or complete code listing that demonstrates the problem?
