### ISSUE TITLE
How can I remove the relationship between many to many data?

### ISSUE THREAD

**Issue by Feuerhamster** [dotnet/efcore#25340]
## Description
I'm sorry to create an issue for this, but I've been searching for days and haven't found a working solution neither in the official Microsoft documentation nor anywhere else on the Internet.

I have employees and badges.
An employee can have multiple badges and a badge can be assigned to multiple employees.
What I've already done and what worked is that I can add badges and assign them to an employee.
**But what I haven't been able to do at all is to remove a badge from an employee or to remove all badges from an employee.**

I know that the entity framework automatically creates a jointable to achieve the many-to-many relationships. 
**So how can I remove a relationship without having to completely delete an employee or badge for it?**

### The models

```c#
public class Employee
{
  public int Id { get; set; }
  public string Username { get; set; }
  public virtual ICollection<Badge> Badges { get; set; }
}
```

```c#
public class Badge
{
  public int Id { get; set; }
  public string Name { get; set; }
  
  [JsonIgnore]
  public virtual ICollection<Employee> Employees { get; set; }
}
```

### The Entity Framework context

```c#
public class StaffOverviewContext : DbContext
{
    public DbSet<Employee> Employees { get; set; }

    public DbSet<Badge> Badges { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Employee>(employee =>
        {
            employee.HasKey(e => e.Id);

            employee.HasMany(e => e.Badges)
                    .WithMany(b => b.Employees);
        });

        modelBuilder.Entity<Badge>(badge =>
        {
            badge.HasKey(b => b.Id);

            badge.HasMany(b => b.Employees)
                .WithMany(e => e.Badges);
        });

    }
}
```

### The used methods from my DAL

```c#
public Employee GetEmployee_ById(int id)
{
    using (var context = new StaffOverviewContext())
    {
        Employee employee = context.Employees
            .Include(e => e.Badges)
            .Single(e => e.Id == id);

        return employee;
    }
}

public Employee ChangeEmployee(Employee e)
{
    using (var context = new StaffOverviewContext())
    {
        Employee changedEmpl =  context.Employees.Update(e).Entity;
        context.SaveChanges();
        return changedEmpl;
    }
}
```

### The code I assumed to work properly
This is the code where I try to remove all badges from an employee.

```c#
Employee employee = db.GetEmployee_ById(id);
employee.Badges.Clear();
db.ChangeEmployee(employee);
```
## Expected result
The badges should still exist, but the employee should not have any badges assigned anymore.

## Actual result
Nothing has changed.

## SQLite Database
As you can see, the tables (including the jointable) were created automatically and seems to be correct.

![image](https://user-images.githubusercontent.com/38376566/127178699-b4d1f209-1a70-4f8b-8e28-a629d5b490b3.png)

## Include provider and version information

**EF Core version:** 5.0.8
**Database provider:** Microsoft.EntityFrameworkCore.SqlServer
**Target framework:** .NET Core 3.1
**Operating system:** Windows 10 (x64)
**IDE:** VS Code 1.58.2

**Comment by da3dsoul** [comment]
I encountered a similar thing on inserting. Before clearing badges, remove the employee from each of the badges. If that works, then it's a step in the right direction for understanding why it happens

**Comment by AndriySvyryd** [comment]
For the relationships to be removed the related badges need to be tracked before the collection is modified, as otherwise there's no way for EF to detect that the collection was modified.

Try something like this instead:
```C#
public Employee ChangeEmployee(int id, Action<Employee> change)
{
    using (var context = new MyContext())
    {
        Employee employee = context.Employees
            .Include(e => e.Badges)
            .Single(e => e.Id == id);

        change(employee);

        context.SaveChanges();
        return employee;
    }
}
```

```C#
ChangeEmployee(id, employee => employee.Badges.Clear());
```
