### ISSUE TITLE
DbContextActivator.CreateInstance failing in .NET 6 Preview 7 with new minimal dotnet apps.

### ISSUE THREAD

**Issue by deepchoudhery** [dotnet/efcore#25356]
I've been running into an issue [here ](https://github.com/dotnet/efcore/blob/02c913dc8e95e34916f61720d239459e8db9224e/src/EFCore.Design/Design/DbContextActivator.cs#L25)with the new .NET 6 Preview 7 bits. Trying to a create a DbContext using DbContextActivator.CreateInstance where I pass it the correctly created context Type and startup assembly, it fails with this stack trace : 

### Include stack traces
```
Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(System.IServiceProvider provider) Line 383  C#
Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(System.IServiceProvider provider, System.Type instanceType, object[] parameters) Line 76   C#
Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(System.IServiceProvider provider, System.Type type) Line 141   C#
Microsoft.EntityFrameworkCore.Design.dll!Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes.AnonymousMethod__13() Line 314  C#
```

Upon debugging it further, seems like failing on this call right [here ](https://github.com/dotnet/efcore/blob/9ac01d6035c76626d89aa1a3cd8d200db2c3c0e1/src/EFCore.Design/Design/Internal/DbContextOperations.cs#L221)and subsequently [here ](https://github.com/dotnet/efcore/blob/9ac01d6035c76626d89aa1a3cd8d200db2c3c0e1/src/EFCore.Design/Design/Internal/DbContextOperations.cs#L314). Failing to create some service which I can't see the values for in the debugger.
This is only occurring in the new .NET 6 Preview 7 bits with the minimal style projects. Does not fail with the same sdk, full Startup.cs and Program.cs files.

### Include provider and version information

EF Core version: 6.0.0-preview.7.21365.2 (EFCore.Design)
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 6
Operating system: Win x64
dotnet sdk : 6.0.100-preview.7.21377.35

**Comment by ajcvickers** [comment]
Looks like a minimal API and/or D.I. break. @davidfowl @bricelam

**Comment by davidfowl** [comment]
Needs more repro steps. This might be something specific to how scaffolding is calling this type. If I call it from another project that references the DbContext type it seems to work.

**Comment by ajcvickers** [comment]
Note from triage: resolved via internal thread.
