### ISSUE TITLE
Setting foreign key to null by PropertyEntry.CurrentValue deletes entity

### ISSUE THREAD

**Issue by majbo** [dotnet/efcore#25360]
Given is an entity with a self-referencing relationship that is configured with `DeleteBehavior.Cascade`.

```C#
public class Tag
{
    public Guid Id { get; set; }
    public string Name { get; set; } = null!;
    public Tag? SynonymFor { get; set; }
    public Guid? SynonymForId { get; set; }
    public IEnumerable<Tag> Synonyms { get; set; } = null!;
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Tag>().HasMany(p => p.Synonyms)
        .WithOne(p => p.SynonymFor)
        .OnDelete(DeleteBehavior.Cascade);
}
```

When setting the foreign key to null using the `PropertyEntry.CurrentValue`, the `EntityEntry.State` changes to `Deleted` and thereby the call to `SaveChanges` deletes the entity.

```C#
var barTag = context.Tags.Single(p => p.Name == "Bar");
var barEntry = context.Entry(barTag);
barEntry.Property(nameof(Tag.SynonymForId)).CurrentValue = null;
```

I created a simple app here: (https://github.com/majbo/EFCascadeDeleteError)
Execute the unit tests. The first one succeeds, it sets the foreign key directly on the entity. The second one fails, it sets the foreign key using `PropertyEntry.CurrentValue`.

### Include provider and version information

EF Core version: 5.0.8
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Rider 2021.1.5

**Comment by ajcvickers** [comment]
Note for triage: this appears to be a bug. Setting the FK to null should trigger delete orphans behavior when the relationship is set to cascade and delete orphans timing has not been changed. However, the relationship here is not required, which is causing this to be behave inconsistently.
