### ISSUE TITLE
 Microsoft.EntityFrameworkCore.Query.SqlExpressions.LikeExpression.Equals(Microsoft.EntityFrameworkCore.Query.SqlExpressions.LikeExpression likeExpression) missing null check on the nullable instance

### ISSUE THREAD

**Issue by Truetotosse** [dotnet/efcore#25362]
in the `Microsoft.EntityFrameworkCore.Query.SqlExpressions.LikeExpression.Equals(Microsoft.EntityFrameworkCore.Query.SqlExpressions.LikeExpression likeExpression)` method:
NullReferenceException when trying to access `EscapeChar` properties with `EscapeChar` being null

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)

**Comment by smitpatel** [comment]
Fixed in #23185
