### ISSUE TITLE
Table rename does not include existing index (RenameTable & DropIndex)

### ISSUE THREAD

**Issue by bgever** [dotnet/efcore#2536]
After upgrading from EF5.0.0 to EF6.1.3, I had to add a migration, because EF apparently decided it should swap the naming convention for more-to-more table relations.

Below you can see a part of the generated code of the Code-First Migration:

``` C#
        public override void Up()
        {
            RenameTable(name: "dbo.JobSites", newName: "SiteJobs");
            DropIndex("dbo.JobSites", new[] { "Job_Id" });
            DropIndex("dbo.JobSites", new[] { "Site_Id" });
            DropPrimaryKey("dbo.SiteJobs");
            AddPrimaryKey("dbo.SiteJobs", new[] { "Site_Id", "Job_Id" });
            CreateIndex("dbo.SiteJobs", "Site_Id");
            CreateIndex("dbo.SiteJobs", "Job_Id");
        }

        public override void Down()
        {
            DropIndex("dbo.SiteJobs", new[] { "Job_Id" });
            DropIndex("dbo.SiteJobs", new[] { "Site_Id" });
            DropPrimaryKey("dbo.SiteJobs");
            AddPrimaryKey("dbo.SiteJobs", new[] { "Job_Id", "Site_Id" });
            CreateIndex("dbo.JobSites", "Site_Id");
            CreateIndex("dbo.JobSites", "Job_Id");
            RenameTable(name: "dbo.SiteJobs", newName: "JobSites");
        }
```

Note however, that the rename happens before existing Indexes are dropped.

The problem can be resolved by either placing the rename after the index drops, or renaming the table used in the index drop.

I also wonder why the rename is necessary in the first place? Because it's a more-to-more relation, I'd say the left and right name should be decided on alphabetical order (what it was).

**Comment by ErikEJ** [comment]
@bgever Notice that the issues here are for EF7, for EF6, go to http://entityframework.codeplex.com/workitem/list/basic

**Comment by bgever** [comment]
@ErikEJ Thanks for pointing that out, sorry I was unaware. Found the issue to be considered of low importance to the EF team: https://entityframework.codeplex.com/workitem/759

I haven't been able to test with EF7, but if the issue is still present, it would be great if it could be addressed.

**Comment by bricelam** [comment]
It should be fixed. Renames are always the last thing to happen. [See ModelDiffer.cs line 218](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs#L218).

**Comment by rowanmiller** [comment]
We aren't going to address this for EF6, manually editing the scaffolded code is the correct thing to do. As @bricelam mentioned, this is already addressed in EF7.

**Comment by bgever** [comment]
Thanks for confirming @bricelam and @rowanmiller, nice to know it works in EF7.
The workaround works for me in EF6, having it mentioned in this issue should help others.
