### ISSUE TITLE
Asynchronous query getting custom objects

### ISSUE THREAD

**Issue by ctrl-alt-d** [dotnet/efcore#25377]
I know it exists a way to retrieve async `Entities` with linq:

```c#
var blogs = await context.Blogs.Where(b => b.Rating > 3).ToListAsync();
```

But, if instead to get `Entities` I want to get custom objects, how must I should perform an async query ?

For example, I have tried unsuccessfully with

```c#
var blogs = context.Blogs
    .Where(b => b.Rating > 3)
    .Select(
        blog => new { Id = blog.BlogId, Url = blog.Url } // <-- custom object
     )  // <-- enumerable at this time, unable to get a task
    .ToListAsync();  // <--- ERROR 
```

I guess I miss a kind of `ToListAsync` with expression, like this:

```c#
var blogs = context.Blogs
    .Where(b => b.Rating > 3)
    .ToListAsync(  // <--- I miss this feature
        blog => new { Id = blog.BlogId, Url = blog.Url }); 
```

I know I can get a fake task with `Task.FromResult`, but exists a real async way to query returning custom objects instead of entities?

Thanks! Best regards!! Congrats about EF, is awesome!

**Comment by roji** [comment]
The above code works just fine - see the code sample below. The Select operator accepts and returns an IQueryable (not IEnumerable), which means it's fully translated into SQL.

What exact exception are you seeing? It's very unlikely the failure has anything to do with sync or async, i.e. try change ToListAsync to ToList and you should be seeing the same error.

<details>
<summary>Working code</summary>

```c#
var blogs = ctx.Blogs
    .Where(b => b.Rating > 3)
    .Select(blog => new { Id = blog.BlogId, Url = blog.Url })
    .ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public int Rating { get; set; }
}
```
</details>

**Comment by ctrl-alt-d** [comment]
Wow @roji , thanks about your very fast answer. You are right, the code I posted has no issues.

My issue is that I'm using a function to create new objects, like this:


```c#
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace tmpprova
{
    class Program
    {        

        private static object ToObject(Blog blog)
        {
            return new { Id = blog.BlogId, Url = blog.Url };
        }

        static void Main(string[] args)
        {
            var ctx = new BlogContext();

            var blogs =
                ctx
                .Blogs
                .Where(b => b.Rating > 3)
                .Select(ToObject) // <--- 'IEnumerable<object>' does not contain a definition for 'ToListAsync'
                .ToListAsync();
        }
    }

    public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseSqlite(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
                .EnableSensitiveDataLogging();
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public int Rating { get; set; }
    }
}
```

**Comment by roji** [comment]
Try changing `.Select(ToObject)` to `.Select(b => ToObject(b))`; the former method group shorthand seems to resolve Enumerable.Select instead of Queryable.Select (not sure why).

**Comment by ctrl-alt-d** [comment]
I confirm, this workaround solves the issue. Is this a kind of bug?

**Comment by roji** [comment]
I'll try to take a look and understand this (maybe @smitpatel already knows about this quirk?)

**Comment by smitpatel** [comment]
This should be raised on runtime repo. This doesn't related to EF Core or expression tree construction either. Looks like some odd rules in method resolution.

**Comment by roji** [comment]
Opened https://github.com/dotnet/roslyn/issues/55325 in the Roslyn repo, we'll see where it goes.
