### ISSUE TITLE
model builder for view does not include primary key - EF Core Version 5.0.3

### ISSUE THREAD

**Issue by aquacat123** [dotnet/efcore#25376]
Hello, i am trying to get a scaffolded sql view to work in EF Core 5.0.3.  In order to create a key on the view i am using ROW_NUMBER() with ISNULL, which worked in older versions of entity framework.  Unfortunately the scaffolded code does not detect the primary key and generates "entity.HasNoKey();" instead.  Is this a bug in EF?  How can I get EF to recognize a column in my view as a primary key WITHOUT having to manually update the generated context code every time i run scaffolding.  Thanks for all your help with this!

### Include your code

**SAMPLE VIEW:** 

CREATE VIEW [dbo].[TestView] 
AS

SELECT ISNULL(ROW_NUMBER() OVER (order by (Select 1)), -1) as  TempId , 
	a.TemplateId
FROM 
 Template A

### Model Builder code after scaffolding

            modelBuilder.Entity<TestView>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("TestView");

                entity.Property(e => e.TemplateId).ValueGeneratedOnAdd();
            });

**Comment by ErikEJ** [comment]
You should be able to create a partial DbContext class, and use OnModelCreatingPartial to set the primary key and use ToTable().

**Comment by aquacat123** [comment]
Thanks @ErikEJ , I tried the code below but got the following error: ""The key {'TempId'} cannot be added to keyless type 'TemplateLocationView'.""  Do you know what I am doing wrong?

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TemplateLocationView>().HasKey(e => e.TempId);

            modelBuilder.Entity<TemplateLocationView>().ToTable("TemplateLocationView");
        }

**Comment by ErikEJ** [comment]
Maybe reorder the statements?

**Comment by ErikEJ** [comment]
Or maybe it is not possible...

**Comment by ajcvickers** [comment]
@aquacat123 Looks like you are running into #24789, which is planned to be fixed for 6.0.

**Comment by aquacat123** [comment]
@ajcvickers Thanks for the update!
