### ISSUE TITLE
Get metadata Schema Name return null value from dbcontext with UseInMemoryDatabase.

### ISSUE THREAD

**Issue by JuanIrigoyen** [dotnet/efcore#25380]
### Include your code

```C#

var options = new DbContextOptionsBuilder().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
var context = new Adventureworks2019fullContext(options);

var entity = context.Model.FindEntityType("Person");
var schema = entity.GetSchema();

schema always return null
```
### Include provider and version information

EF Core version: 6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022  Preview 2.1)

**Comment by ErikEJ** [comment]
Wrong repo?

**Comment by JuanIrigoyen** [comment]
> Wrong repo?

I don´t know Eric, 

Is a small test from AdventureWorks https://mega.nz/file/L1BBGaoS#YoxsZmGzSAouEoPv124F_EGIquaq1a61No2AtIBTXjE

`var options = new DbContextOptionsBuilder<Adventureworks2019fullContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;

var context = new Adventureworks2019fullContext(options);
var entity = context.Model.FindEntityType("Person");
if (entity == null) continue;

var schema = entity.GetSchema();
if (schema == null) continue;
`
I generated my model with your tool
![Capture](https://user-images.githubusercontent.com/4987574/127764917-42ac30cd-5ab4-4fb4-92af-64517056b654.PNG)

**Comment by roji** [comment]
GetSchema returns the schema of the table to which the entity type is mapped; if it hasn't been explicitly set, it will return null and the table is in the default schema (dbo under SQL Server).

The IEntityType returned from FindEntityType indeed contains information which you can access like this;

```c#
var entityType = ctx.Model.FindEntityType("Blog");

Console.WriteLine(entityType.GetProperty("Name").GetDefaultValue());
Console.WriteLine(entityType.GetProperty("Name").IsNullable);
```

**Comment by JuanIrigoyen** [comment]
Thank you roji, I knew this, in my model the schema is configured by attributes like [Table("Person", Schema = "Person")] 
or [StringLength(8)]

But entityType.GetSchema() always return null
and
entityType.GetProperty("Title").GetMaxlenght() return the correct value.

**Comment by roji** [comment]
@JuanIrigoyen I am unable to reproduce the issue, with the below code the schema configured via the data annotation attribute is returned just fine.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new MyContext();
var entityType = ctx.Model.FindEntityType("Person");
Console.WriteLine("Table schema is: " + entityType.GetSchema());
Console.WriteLine("Max length is: " + entityType.GetProperty("Name").GetMaxLength());

public class MyContext : DbContext
{
    public DbSet<Person> People { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0");
}

[Table("Person", Schema = "Person")]
public class Person
{
    public int Id { get; set; }
    [StringLength(8)]
    public string Name { get; set; }
}
```

</details>

**Comment by JuanIrigoyen** [comment]
roji, thank you!!!

Try this https://mega.nz/file/m55SDQzC#2j9H5nXf_aSiTeTNgxGfBoZJmbwfn3mgwzsMuzlXsQA

It doesn't work, maybe its because I used InMemory Datatabase or Ef Core 6 beta

**Comment by JuanIrigoyen** [comment]
The problem is InMemory Database

**Comment by ErikEJ** [comment]
Inmemory is not a relational provider.

**Comment by JuanIrigoyen** [comment]
ok, thank you Eric, I need get this information for my test.

I try get this information using Attribute.GetCustomAttribute

**Comment by roji** [comment]
>  I thing this should not depend on the provider but on the attributes

The concept of a schema has no meaning in InMemory database - it's a relational concept; this is why the attribute isn't even processed by EF Core when using InMemory.

**Comment by JuanIrigoyen** [comment]
> > I thing this should not depend on the provider but on the attributes
> 
> The concept of a schema has no meaning in InMemory database - it's a relational concept; this is why the attribute isn't even processed by EF Core when using InMemory.

Similar to the GetMaxlenght(), DefaultValue or others attributes, for me Schema an attribute and I need this for test how my program load the metadata to setup my controls

Another problema is how I can test my context in memory for example: 

var entityType = ctx.Model.FindEntityType("Blog"); doesn´t work

**Comment by roji** [comment]
> Similar to the GetMaxlenght(), DefaultValue or others attributes, for me Schema is an attribute and I need this for test how my program load the metadata to setup my controls.

InMemory is by-design not meant to be fully compatible with a real database provider - that would be impossible. For example, if you try to run tests which use database transactions or raw SQL, those tests wouldn't work since InMemory cannot support these features; the schema metadata/attribute is a similar case. We explicitly discourage using InMemory in order to test applications - [see the docs](https://docs.microsoft.com/en-us/ef/core/testing/#approach-3-the-ef-core-in-memory-database).

> Another problem is how I can test my context in memory for example:
> 
> var entityType = ctx.Model.FindEntityType("Person"); return null in memory. It doesn´t work

This does work for me (see code below) - the entity type is defined and exists in the model for InMemory, even if the schema metadata does not. Check your code.

<details>
<summary>Sample code</summary>

```c#
await using var ctx = new MyContext();
var entityType = ctx.Model.FindEntityType("Person");
Console.WriteLine("Entity name is: " + entityType.Name);

public class MyContext : DbContext
{
    public DbSet<Person> People { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseInMemoryDatabase("foo");
}

public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

**Comment by JuanIrigoyen** [comment]
Thank you roji, the problem is the namespace

`
namespace ConsoleApp1
{
    await using var ctx = new MyContext();
    var entityType = ctx.Model.FindEntityType("Person");
    Console.WriteLine("Entity name is: " + entityType.Name);
    
    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }
    
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseInMemoryDatabase("foo");
    }
    
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}`

InMemory, I need modify my code to `var entityType = ctx.Model.FindEntityType("ConsoleApp1.Person");`  

So your example works correctly and mine fails. I need to refer to my nameSpace as class name. but, 
this shouldn't work like that, right?

**Comment by roji** [comment]
Your code above doesn't compile - you can't place statements directly under a namespace without a class.

Apart from that, you can use `ctx.Model.GetEntityType()` to enumerate through all the types in the model (see my code sample below). Doing so shows that the entity name contains the namespace, so it's `ConsoleApp1.Person` - this is done to support multiple types with the same name in different namespaces.

<details>
<summary>Code</summary>

```c#
namespace ConsoleApp1
{
    class Program
    {
        public static async Task Main()
        {
            await using var ctx = new MyContext();
            var entityType = ctx.Model.GetEntityTypes().Single();
            Console.WriteLine("Entity name is: " + entityType.Name);
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseInMemoryDatabase("foo");
    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```

</details>

**Comment by JuanIrigoyen** [comment]
ok, thank you very much for your support.

Best Regards.
