### ISSUE TITLE
Query: add translation for string.IndexOf(string, int)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#25396]
we only translate overload that starts from the beginning. We could also translate the one that takes starting position, TSQL method has that overload also.

**Comment by yosoyhabacuc** [comment]
I've added a PR with a proposal to implement the enhancement, It's basically taking the already existing logic for IndefOx and adding the start index at the end. The PR includes moving the logic to a method to be used by both versions (with or without the start index). I hope the proposal makes sense.
