### ISSUE TITLE
How to apply unique constraint in case of global query filter

### ISSUE THREAD

**Issue by nicolapiccinelli** [dotnet/efcore#25401]
Hello,
I cannot find anyway a solution for the following behaviour (maybe is by design, but I cannot figure out if it is): i've setup a query filter to provide global soft delete to my context, but it seems to be ignored by the unique check. Can anyone give me ad advice if there is a solution to achieve this? Right now I'm getting an exception in case of deleted records.

```C#

foreach (var type in modelBuilder.Model.GetEntityTypes())
{
    if (type.ClrType.BaseType == typeof(Models.Entities.EFExtensions.BaseEntity))
    {
        modelBuilder.SetSoftDeleteFilter(type.ClrType);
    }
}

modelBuilder.Entity<MyClass>().HasIndex(p => p.Name).IsUnique();
```

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqLite
Target framework: .NET 5.0
Operating system: Linux/MacOs/Windows
IDE: Visual Studio Code

**Comment by ajcvickers** [comment]
@nicolapiccinelli Setting up this kind of filter on the index automatically is something that we would likely do as part of supporting [soft-delete across the stack](https://github.com/dotnet/efcore/issues/19695). It is not something that will happen automatically when setting a query filter. However, you can manually [add a filter to the index](https://docs.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#index-filter) in your model building code.
