### ISSUE TITLE
Uniqueidentifier PKs: Are there settings in SQL (or another way) to get .ValueGeneratedOnAdd() added to entities w/ DBScaffold command?  (DB first)

### ISSUE THREAD

**Issue by mrcoymeeks** [dotnet/efcore#25407]
Hello!

Thank you for the hard work!

Version: EF Core v5

Our team uses DB First approach and scaffold the db context using the Db-Scaffold command.  A lot of our entity tables use uniqueidentifiers are PKs.  We have been using the default value-"newid()" approach for generating our PKs on add but we are wanting to implement auditing of creates/modifications at the ef level.  Since we are allowing SQL to generate the guid on add by way of newid(), the PK that gets stored in the DB is different from the guid that we have access to in the ef context  (makes sense why that is).

We would like move away from the newid() approach so that we can continue with our plan to leverage ef core for auditing purposes.

To do this, we can modify the DbContext entity by adding .ValueGeneratedOnAdd() to the entity PKs and this gets us where we want to be.

However, the challenge is that the next time we have db schema changes and we scaffold the db context, .ValueGeneratedOnAdd() is removed and we have to manually add them back in.  Manageable for the immediate, but could cause problems down the road.

My understanding is that .ValueGeneratedOnAdd() gets applied to identities but in SQL v15, you are not able to set uniqueidentifiers as identities.

Using DB first, is there a way to have .ValueGeneratedOnAdd() added to an entity using DbScaffold?

Is the solution to move to Code first?

EF Core version:   5
Database provider: MSSQLSERVER
Target framework: .NET 5.0
Operating system: WIN10
IDE: Visual Studio 2019 16.3

**Comment by ErikEJ** [comment]
You should be able to do that in a partial class, using the OnModelCreatingPartial method.

The partial class will then survive a new scaffold run.

**Comment by mrcoymeeks** [comment]
Thank you @ErikEJ!

We will give that a shot
