### ISSUE TITLE
Eager Loading sometimes not loading data for Navigation Properties

### ISSUE THREAD

**Issue by alexyoungman** [dotnet/efcore#2541]
The property is a one to one relationship with another class; most of time it loads correctly but sometime it loads a class with no values at all, just nulls. But if you look in the database the record does exist and should be loaded.

**Comment by ErikEJ** [comment]
Plz show us ze codez!

**Comment by alexyoungman** [comment]
Here are the classes in question:

```c#
public class ProductModel
{
    public int EntityKey { get; set; }

    public ICollection<ProductMetaDataModel> MetaData { get; set; }
}

public class ProductMetaDataModel
{
    public int EntityKey { get; set; }

    public ProductModel Product { get; set; }

    public UrlRecordModel UrlRecord { get; set; }
}

public class ProductConfig : EntityTypeConfiguration<ProductModel>
{
    public ProductConfig()
    {
        HasKey(x => x.EntityKey);
        HasMany(x => x.MetaData).WithRequired(x => x.Product).WillCascadeOnDelete();
    }
}

public class ProductMetaDataConfig : EntityTypeConfiguration<ProductMetaDataModel>
{
    public ProductMetaDataConfig()
    {
        HasKey(x => x.EntityKey);
        HasRequired(x => x.Product).WithMany(x => x.MetaData).HasForeignKey(x => x.ParentEntityKey).WillCascadeOnDelete();
    }
}

public class UrlRecordModel
{
    public int EntityKey { get; set; }

    public string UrlSlug { get; set; }
}
```

We load the ProductModels from a service, which uses includes to load the collection of ProductMetaDataModels and in turn loads the UrlRecordModel for each of those. The UrlRecordModel usually loads properly with the UrlSlug property populating most of the time, but some of the time it returns a blank class with only null values. When we look in the database, the record does exist and should have been loaded. Even if you make an SQL query to load the class, inside of SQL Server, it loads it correctly.

**Comment by ErikEJ** [comment]
Is that EF7?

**Comment by alexyoungman** [comment]
We are using EF6.

**Comment by rowanmiller** [comment]
@alexyoungman given this is an EF6 issue could you open an issue on the EF6 project https://entityframework.codeplex.com/.

To be able to address this we are going to need some code we can run to reproduce the issue. So please include some for of application/service we can run. I realize this is an intermittent issue so we may need to run your code for some period of time to see the issue.

One thing we did want to check is that you do not have multiple threads using the same context instance. The context is not thread safe, and this is the kind of issue we would expect to see if multiple threads were sharing a context.
