### ISSUE TITLE
HasDbFunction mapping incorrect schema

### ISSUE THREAD

**Issue by NanFengCheong** [dotnet/efcore#25432]
```
 modelBuilder.HasDbFunction(typeof(JsonDbFunctions).GetMethod(nameof(JsonDbFunctions.Value),
     new[] { typeof(string), typeof(string) }))
   .HasName("JSON_VALUE")
  .HasSchema("");
```

generated function still return dbo.JSON_VALUE even though I specify the schema to empty string.

EF Core version: 5.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2022 Preview

**Comment by stevendarby** [comment]
Does chaining on `IsBuiltIn()` to the function builder fix it?

**Comment by ajcvickers** [comment]
@smitpatel @maumar Assuming `JSON_VALUE` is the [built-in function](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver15), is this a case where using `.IsBuiltIn()` is needed to avoid using the default schema name when calling the function?

**Comment by ajcvickers** [comment]
Confirmed that `.IsBuiltIn()` should be used here.
