### ISSUE TITLE
Custom Oracle DB Types in EFCore

### ISSUE THREAD

**Issue by RejectKid** [dotnet/efcore#25442]
## Ask a question

Im currently utilizing an existing database where they have, what I believe to be called, custom data types store in columns.  When reverse engineering the DB it naturally is skipping those types.  Is there any way to map these? or how do i go about settng up EFCore in a way to use these? (ive obfuscated the below output).

My original thought was to create a CLR type with all the properties and such that it contains however I get (see "my attempt").  Its suggested to ignore it which wont work for me.  

Tried several other solutions such as `.HasConversion()`, `.HasValueGenerator()` with no results.

This is also an example view of what the schema looks like in DBeaver
![Untitled](https://user-images.githubusercontent.com/6117898/128575247-b59f0be7-8fe6-4e9b-b3f3-7bffb95aa14f.png)

Any help would be appreciated!

### Scaffolding output
```
Could not find type mapping for column 'SCHEMA.TABLE.COLUMN1' with data type 'MULTIMEDIA_T'. Skipping column.
Could not find type mapping for column 'SCHEMA.TABLE.COLUMN2' with data type 'STRING_T'. Skipping column.
```

### My Attempt
```
System.InvalidOperationException: The property 'TABLE.COLUMN1' is of type 'CustomStringType' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

### Include provider and version information

EF Core version: 5.0.8
Database provider: Oracle.EntityFrameworkCore
Target framework: .NET5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by roji** [comment]
@RejectKid value converters (HasConversion, HasValueGenerator) are typically for mapping an arbitrary CLR type to another CLR type that is already supported by your EF provider. For example, you could use them to convert any custom CLR type to a CLR string, which would then be mapped to a database text column.

You seem to be looking for a way to use EF Core to access custom Oracle types in your database, which is different. This ultimately is going to depend on support at the EF Oracle provider - you will need to check that with that provider specifically.
