### ISSUE TITLE
Memory usage : big difference between 32 bits (500MB)/ 64 bits (1.4GB)

### ISSUE THREAD

**Issue by filmar25** [dotnet/efcore#25441]
Hi,

I would like to understand what's happen with our project.

Before now, we always compiled 32 bits, but we want change to 64 bits to remove 2 GB limitation.

When we compile 32 bits, after startup, memory usage is around 500MB.

When we compile 64 bits, same code here, after startup, memory usage is around 1.4 GB.

We has pointed that the first initialization of DbContext is causing that memory usage in 64 bits.

Can someone can help us with that ?

Thank you very much !

**Comment by ajcvickers** [comment]
@filmar25 Make sure that you understand how .NET uses memory, and how to measure what is being used. It sounds to me like the 64-bit version is not running GC as frequently, which is expected when more memory is available. See [Analyze memory usage](https://docs.microsoft.com/en-us/visualstudio/profiling/analyze-memory-usage?view=vs-2019) and its subsections in the .NET docs.
