### ISSUE TITLE
Wrong model-namespace using in generated context

### ISSUE THREAD

**Issue by SchroeerM** [dotnet/efcore#25473]
Hello,

if I try to scaffold an empty database to control it later by ef-versioning the generated context contains an using for the models-namespace. If the database is empty this namespace is empty as well and the compilation throws an error.

Steps to reproduce:

1. create an empty database
2. use "dotnet ef database scaffold" in an project
3. try to compile the generated code.

Ive fixed this on my site but an general fix should prevent the first error-message which appears directly after executing the scaffold command.

Thanks,
Michael

**Comment by bricelam** [comment]
As far as I can tell, you need to meet **both** of the following conditions to hit this.

1. Have a database with no views or tables
2. Specify a `--context-namespace` that's different from the entity types' `--namespace`

If this isn't the case, can you share more details?

**Comment by ajcvickers** [comment]
Note from triage: this very much a corner case. With the introduction of templates in EF7, this can be handled by editing the template if desired.
