### ISSUE TITLE
The specified deps.json [..] does not exist  

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#25477]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-specified-depsjson--does-not-ex/1491756)._

---
[severity:I'm unable to use this version]
Hello. This error appeared 2 days ago. 
 
What I tried: 
1) I updated some version of 2019 to the newest one, it didn't help 
2) I downloaded the 2017 version, there the same 
3) The most interesting. I went into an old project that never had such errors, and when migrating, this error appeared

I also tried everything I found on the internet. It seems that I moved the project.
! [one.png] (https://aka.ms/dc/image?name=B372e2b209a184d619f30e4271e62837e637634454939953538_one.png&tid=372e2b209a184d619f30e4271e62837e637634454939953538)
deps.json file to the root directory, as indicated in the error, but another error came out ...

---
#### Feedback Bot on 8/2/2021, 07:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Duplicate of #16386
