### ISSUE TITLE
Polymorphic collection in efcore 5

### ISSUE THREAD

**Issue by arkum** [dotnet/efcore#25472]
Wondering whether it is possible to achieve the below with efcore 5

```C#
public class Booking
{
    public Guid Id {get;set}

    public BookingType BookingType {get;set;}

   public ICollection<BookingDetail> BookingDetails {get;set;}

}
```
BookingDetail is an abstract class
There are different types of Booking Details

```C# 
public class PoolGroupBooking : BookingDetail
{
}
```
```C#
public class DriveupBooking : BookingDetail
{
}

```
I want BookingDetails collection to be populated with the object of the appropriate derived type, based on BookingType column

I would like to use TPH for storing the different attributes of BookingDetail into one BookingDetail table. However, the discriminator is in the parent table Booking

* Can i use polymorphic collections where the BookingDetails property gets filled with the appropriate concrete type based on the BookingType property
* Can i use a column from a different table as a discriminator

### Include provider and version information

EF Core version:5.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
Note for triage: Possibly related to #7623

**Comment by ajcvickers** [comment]
Note from triage: we believe this is covered by #7623. Please vote for that issue.
