### ISSUE TITLE
NRE when adding property named "Count" to a property bag entity type

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#25485]
Originally filed at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1491

This seems to be a bug in EF Core that is only triggered for specific entity property names (e.g. when your property is named `Count`) in migration snapshots.

The underlying issue seems to be, that EF Core is checking the properties of the wrong type. It does enumerated the properties of the `Metadata.ClrType` property, but it is not set to the actual entity type (since this is a migration snapshot), but to a type of `Dictionary<string, object>`.
It then hits the `Count` property of this `Dictionary<string, object>`, checks its `int` type against the expected `double` type of the entity's property, realizes that they do not match, and finally returns null, which will then throws the NRE.

This is the line with the issue:

https://github.com/dotnet/efcore/blob/159c7e728b29cef1a8208e69d15eb058eae0c4d8/src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs#L579

```c#
memberInfo ??= Metadata.ClrType.GetMembersInHierarchy(propertyName).FirstOrDefault();
```

---

@AndriySvyryd, @ajcvickers Reproduced with the following code:

<details>
<summary>Program.cs</summary>

```c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class RegistryOrderServices
    {
        public Guid Id { get; set; }
        public double Count { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<RegistryOrderServices> RegistryOrderServices { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = "server=127.0.0.1;port=3308;user=root;password=;database=Issue1491";
                var serverVersion = ServerVersion.AutoDetect(connectionString);

                optionsBuilder.UseMySql(connectionString, serverVersion)
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            b => b
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }
    }

    internal static class Program
    {
        private static void Main()
        {
        }
    }
}
```

</details>

Add an initial migration and then another one (can be empty).
Should be reproducible with any provider.

**Comment by war-beast** [comment]
The same thing happen with a property named "Values"
