### ISSUE TITLE
Please update SQLitePCLRaw.bundle_e_sqlite3 from 2.0.2 to 2.0.4 in EFCore 3.1.*

### ISSUE THREAD

**Issue by jakubsuchybio** [dotnet/efcore#25497]
Hi,
in https://github.com/ericsink/SQLitePCL.raw there is a bug in version 2.0.2, which only happens on .NET Framework, but not on .NET Core or .NET 5+.

The bug is this: https://github.com/ericsink/SQLitePCL.raw/issues/321 and it is fixed in version 2.0.4.

EFCore 5+ uses the library version 2.0.4
EFCore 3.1.* uses the library version 2.0.2

However on .NET Framework, we can only use EFCore 3.1.* as the latest version of EFCore.

Because of this I'd like to propose, that you create new EFCore 3.1.X version that has this library updated to 2.0.4, so that .NET Framework users are not affected by this bug.

Thanks!

### Include version information

Microsoft.Data.Sqlite version: That is the question! ;-)
Target framework: .NET Framework 4.8
Operating system: Windows 10

Edit:
There is an easy workaround for this, if anybody is affected by this. Because EFCore 3.1.* has this library as >= 2.0.2, we can just add this library's nuget package in version 2.0.4 and everything works fine.

**Comment by ajcvickers** [comment]
@jakubsuchybio We will start the process of getting this approved for a 3.1.x version.
