### ISSUE TITLE
Add Option to InMemoryDB to ignore Relational-specific methods

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/efcore#25500]
# Problem
We are using the InMemoryDatabase to test all our business logic. Now we have this one place where we need to `ExecuteSqlRaw` (to enable identity insert).

Of course we get the `System.InvalidOperationException : Relational-specific methods can only be used when the context is using a relational database provider.` exception.

I know this issue popped up in the past several times - I guess with migrations. I myself run into this issue several times over the years.

# Solution

I think it would be nice to have an option for the InMemoryDatabase to just silently ignore Relational-specific method calls instead of throwing this exception. The InMemoryDatabase already ignores so many relational-specific things like foreign keys or schema checks (not null, max length, etc.) so it doesn't seem totally inappropriate to have such an option. Default disabled. 

The InMemoryDatabase is a great tool for testing and this would make it even more useable.

**Comment by ErikEJ** [comment]
You could use the context.Database.IsSqlServer() method

**Comment by roji** [comment]
> The InMemoryDatabase already ignores so many relational-specific things like foreign keys or schema checks (not null, max length, etc.) so it doesn't seem totally inappropriate to have such an option

Foreign keys and schema checks are purely database-side migration things that don't really affect program flow aside from throwing an exception if some check fails; whereas raw SQL is an actual command being sent to the database. It seems a bit unlikely that most code paths would work as expected if all raw SQL operations are silently ignored (could be quite a pit of failure).

**Comment by matthiaslischka** [comment]
@ErikEJ that's not a very beautiful solution, adding complexity and guardian statements just for a test.
I usually try very hard to avoid changing my production code at all, just for a test. However, here I'm forced to because the alternative would be adding a new DB provider and infrastructure to my tests. That's also a bit too much just for this one very specific testcase.

My solution will be something like moving the `ExecuteSqlRaw` in the DBContext. Maybe a 'SaveChanges' overload, specific for this single usecase or something like that.

@roji Yes I know. I still think it could be a nice additional flag just for testing purposes. And no harm if the default behavior is not changed.
I would guess that actually most code parts would work because you usually do not use raw sql when working with EF. Only in the rarest occasions and for DB specific things that are not part of your business logic (e.g. enable identity insert).
And if raw sql statements are for some reason part of your business logic you would not be using the InMemoryDatabase in the first place, right?

**Comment by roji** [comment]
> I would guess that actually most code parts would work because you usually do not use raw sql when working with EF. Only in the rarest occasions and for DB specific things that are not part of your business logic (e.g. enable identity insert).

Right, but this option would be for those who *are* using raw SQL... And once again, if the statement is there, chances are it needs to do something important - just ignoring a user operation seems problematic.

> And if raw sql statements are for some reason part of your business logic you would not be using the InMemoryDatabase for testing in the first place, right?

I definitely agree with this one - but that's another argument against needing the flag, no?

**Comment by roji** [comment]
Thanks, we'll discuss this as a team and see what we think.

FWIW we do have an explicitly documented consensus that InMemory is **not** a good choice for testing EF Core applications ([see the docs](https://docs.microsoft.com/en-us/ef/core/testing/#approach-3-the-ef-core-in-memory-database)). Either you want to completely mock out your data layer and test your business logic - in which case a repository pattern is the right layer to mock (and avoid issues such as raw SQL) - or you want to exercise your data layer, in which case you should ideally be testing against your production database system. In our experience many people end up using InMemory because they think running tests on SQL Server or other production databases isn't feasible, and that isn't really true.

**Comment by ajcvickers** [comment]
@matthiaslischka As @roji said, we discussed this as a team and we believe things like this are exactly why using the in-memory provider for testing is an anti-pattern. We don't plan to change the in-memory provider in the way you suggest. Instead, take a look at the documentation that @roji pointed to and consider using a relational provider for your testing.
