### ISSUE TITLE
Conditionally mapping two entities to a base entity

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/efcore#25517]
This goes against the inheritance model.

I have a model consisting of a ```Person``` and an ```Organization``` entity. Both entities can be considered to be a ```Customer```.  They are their own tables, but share fields in common - such as ```CustomerNo```.

But, a ```Person``` might also be a person that IS NOT a ```Customer``` in its own right. Rather, connected to an ```Organisation```.

I want to conditionally map the ```Persons``` and ```Organization``` that are ```Customers``` to on DbSet based on a condition, a discriminator. The shared fields can exist in their own respective tables, but I want to treat the entities as ```Customer```.

The requirements:

* Adding either a ```Person``` or an ```Organization``` to the ```Customer``` DbSet should store them in their respective table, market as customer.

* Accessing the ```Customer``` DbSet should only return the entities of ```Persons``` and ```Organization``` that are ```Customer```.

Is this possible with some trickery in the ModelBuilder? I'm trying to figure out.

**Comment by robertsundstrom** [comment]
I am thinking about creating to derived ```Person``` types with discriminators ```CustomerPerson```or ```ContactPerson``` (or similar).

If mapping DbSets with interfaces were allowed then I could just create interfaces for ICustomer, IPerson, IOrganization.

```DbSet<ICustomer> Customers { get; set; }```

**Comment by ajcvickers** [comment]
@robertsundstrom Can you show the C# code for the shape of the entity types and their relationships? If we know what your classes look like, then it may be easier to suggest ways it can be mapped to the database.
