### ISSUE TITLE
UseCosmos with serialization options

### ISSUE THREAD

**Issue by Ethan0007** [dotnet/efcore#25519]
How to add CosmosSerializationOptions on UseCosmos? I want to set PropertyNamingPolicy to CamelCase.

It seems like the JsonPropertyName is not working at all when saving the data.
![128348847-d20b0b98-abb4-4650-8beb-1cdf5a6c84c2 (1)](https://user-images.githubusercontent.com/12542052/129449685-6a647e55-2fb8-40e5-a82c-31eb0ca35385.png)
![128347943-ccbdc05d-0baa-45bf-94c0-a3732e577924 (1)](https://user-images.githubusercontent.com/12542052/129449691-f5b24fd7-30a2-4bb9-aac8-27a6c265dceb.png)

**Comment by AndriySvyryd** [comment]
CosmosSerializationOptions are not supported. Use `.ToJsonProperty()` to specify the property name. See [Example](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#embedded-entities)
