### ISSUE TITLE
Is there a full list of methods that EF supports for translation?

### ISSUE THREAD

**Issue by sjd2021** [dotnet/efcore#25522]
I often wonder if a method will convert nicely to SQL, and I make it a good habit to view the queries due to being burned in the past and having worked with junior developers who don't have much DB experience. I've had questions on things like `Enum.HasFlag` which  I was surprised to see works just fine, and I found myself recently unable to remember if `Dictionary.ContainsKey(x)` works properly or if I need to write `Dictionary.Keys.Contains(x)`. Other than trial and error, what is the suggested way of finding out the list of supported methods in expression trees?

I started by looking in this folder: https://github.com/dotnet/efcore/tree/cd0bc8bff3053a67e352fff64bf58020e1421ad5/src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/Internal

**Comment by sjd2021** [comment]
I've found this list for npgsql - guess I'm looking for something like this for other providers such as sqlite, mssql, etc.
https://www.npgsql.org/efcore/mapping/translations.html

**Comment by roji** [comment]
I think you're looking for [this for SQL Server](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/functions), and [this for Sqlite](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/functions); though if you're comfortable looking around in the sources, that's always the ultimate source of truth :)

BTW trial and error isn't a bad way to see if a particular .NET function call can be translated. The docs listing is more useful for the other way, i.e. when you know of a SQL function you want to translate to, and don't know which .NET function/construct corresponds to it.

**Comment by sjd2021** [comment]
Thanks! That's exactly what I needed.
