### ISSUE TITLE
Commands silently swallow exceptions from Startup.cs

### ISSUE THREAD

**Issue by rytmis** [dotnet/efcore#2553]
We use startup.cs in a class library to configure connection strings for running migrations and other commands that are common to multiple projects.

Now, if the Startup ctor or one of the configuration methods throws an exception, `ContextTool.TryCreateContextFromStartup` silently swallows it without a trace. This makes it rather difficult to understand why our connection strings aren't being found. :)

**Comment by rytmis** [comment]
### Minimal repro steps
1. Create a new web project with a Startup.cs
2. Create a new EF DbContext
3. add "throw new Exception();" to the ctor of Startup.cs
4. run dnx . ef migration add empty --context YourContextName

### Expected result
Exception details printed to the console

### Actual result
No trace of the exception

**Comment by bricelam** [comment]
Yeah, we should at least show them as warnings before falling back to other ways of constructing DbContext classes.

This is part of the higher-level issue #639.

**Comment by bricelam** [comment]
Closing since this work is tracked by #2294
