### ISSUE TITLE
5.0.9 release notes says there are no changes, but there are

### ISSUE THREAD

**Issue by andrerom** [dotnet/efcore#25549]
> This is a patch release of EF Core 5.0 containing only updates to dependencies. There are no additional fixes in this release beyond those already shipped in EF Core 5.0.8.

However there are some fixes
https://github.com/dotnet/efcore/compare/v5.0.8...v5.0.9

Including fixes for  #25133 and #25156

**Comment by ajcvickers** [comment]
@AndriySvyryd Did these go into 5.0.8 or 5.0.9?

**Comment by smitpatel** [comment]
They are in 5.0.9 tag

**Comment by wtgodbe** [comment]
Interesting - where do the EF release notes live? CC @rbhanda @danroth27

**Comment by ajcvickers** [comment]
@wtgodbe They live here: https://github.com/dotnet/efcore/releases I think this was my mistake; I will move them to 5.0.9.
