### ISSUE TITLE
RevEng: Foreign key annotations are not printed if it has default facets for core

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#25542]
https://github.com/dotnet/efcore/blob/cc1d81a18c6e939ae900d5a0e90ecb7ef12ea921/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs#L702

This variable ignores the fact that annotations can add more fluent API lines. We only print if PrincipalKey/DeleteBehavior/Name differs ignoring all other facets.

**Comment by ajcvickers** [comment]
This code has changed significantly. I don't believe the issue here is still relevant.
