### ISSUE TITLE
Operation on Entities without code dublication

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/efcore#25551]
## Ask a question

Remember:
I have 5 entities derived from the same base class.  So I have 5 same structure tables.

I implemented some complex logic on updates for one of the entities. And want to have the same logic for others.
Is it any way to pass entity as T Template and not to duplicate code for each 5 entity (with just different name)?

EF Core version: 3.1
Database provider: (e.g. Postgress)
Target framework: (e.g. .NET 3.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.11)

**Comment by roji** [comment]
@IrakliLomidze it's a bit difficult to understand exactly what you're trying to achieve... Posting your code - the 5 entities and the update logic should make that clearer.

**Comment by IrakliLomidze** [comment]
public class DocumentAttributeBase 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        public float? DisplayOrder { get; set; }

        [StringLength(512)]
        public String Caption { get; set; }
        ...
    }

Then
 I have Entities in DbContext

 [Table("main_document_attribute_authors", Schema = "main")]
    public class DocumentAttributeAuthor : MainDocumentAttributeBase 
    { }
    

    [Table("main_document_attribute_types", Schema = "main")]
    public class DocumentAttributeType : MainDocumentAttributeBase
    { }

    [Table("main_document_attribute_status", Schema = "main")]
    public class DocumentAttributeStatus : MainDocumentAttributeBase
    { }


I Implemented some code for DocumentAttributeAuthor in the Scope of DbContext

void SomeCode(dbContext db)
{
...
   db.tbl_DocumentAttributeAuthor.
...
}

I want to use the same logic for DocumentAttributeType  and DocumentAttributeStatus 

Is it possible to achieve that without duplication code for DocumentAttributeType and for DocumentAttributeStatus.

**Comment by roji** [comment]
It seems like you may be looking for a way to generically access a DbSet on a DbContext; if so, that can be done as follows:

```c#
db.Set<SomeEntityType>().Where(...)...
```

This can allow that SomeCode method to be generic on T, and to pass that T to DbContext.Set.

**Comment by IrakliLomidze** [comment]
Type f;
            if (i == 0) f = typeof(DocumentAttributeAuthor );
            else f = typeof(DocumentAttributeStatus );
Please help, it seems very basic error but. 
But the compiler does not like my code  "f is used as variable not as type"

db.Set<f>().Where

**Comment by roji** [comment]
@IrakliLomidze this isn't how generic code works. You'd likely need to do something like this:

```c#
void SomeCode<T>(dbContext db) where T : DocumentAttributeBase
{
...
   db.Set<T>()......
...
}
```

You can then invoke this with:

```c#
SomeCode<DocumentAttributeType>(context);
```

**Comment by IrakliLomidze** [comment]
Thanks a lot. : )

**Comment by IrakliLomidze** [comment]
One More Question is it posible 
in Where Clause to have Generic Type ?
db._MainDocuments.Where(w => w.[GenetricType]

**Comment by roji** [comment]
You can have a generic property on your MainDocument class, and then access that inside the Where. I'd recommend getting more familiar with generics in C# and .NET regardless of EF Core, and then see how you can make things work with EF.

**Comment by IrakliLomidze** [comment]
Ok I will try, Thanks again for help
