### ISSUE TITLE
Questions about Compiled Models

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/efcore#25576]
## Ask a question

I'm a big fan of this article and concept:
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-5-compiled-models/

In fact, I posted [a question to the blog post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-5-compiled-models/#comment-10060) but apparently there is a time limit to comments and no more can be added.

So I'm asking here now. :)

I did try to apply a compiled model to my solution, but I am not seeing any noticeable performance gains.  I wanted to check in here to see if there is anything obvious I should be trying.

A note about my context: it is a monolith.  ALL my entities are contained within it, mostly because I that is how I believed that is the only way to make a `DbContext` (one per application).  I see now that applications can have several `DbContext`s and I am now redesigning my entity access tier to accommodate.

Anyways, my questions:

1. Is there a way to find out how many properties/relationships there are in my model?
2. If I am not seeing any performance gains, is there something obvious to check to see if maybe something isn't configured correctly?
3. After reading the article above, I removed all my `DbSet` properties on my monolith `DbContext` and call `context.Set<TEntity>()` now instead.  Is this perhaps the reason why I am not seeing obvious benefits?

The last note I will say is that performance tuning is so variable.  Right now my application takes 11.5-12.5 seconds to load, sometimes even as high as 13.5 seconds.  That's a _lot_ of variability.  So, the optimization might be in there, but because of so much going on it isn't very noticeable, especially if we're only talking 200-300ms.

Thank you for any assistance you can provide!

### Include your code

NA

### Include stack traces

NA

### Include verbose output

NA

### Include provider and version information

EF Core version: `6.0.0-rc.1.21416.1`
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `net6.0`
Operating system: Windows 10
IDE: Visual Studio 2022 Preview 3.1

**Comment by roji** [comment]
> Is there a way to find out how many properties/relationships there are in my model?

Your model can be accessed via the DbContext.Model property, so you can count various things as followed:

```c#
var numEntityTypes = ctx.Model.GetEntityTypes();
var numProperties = ctx.Model.GetEntityTypes().SelectMany(e => e.GetProperties()).Count();
... and so on
```

> If I am not seeing any performance gains, is there something obvious to check to see if maybe something isn't configured correctly?

First, it's important to understand that compiled models mostly improves startup time, and doesn't improve general runtime perf in a significant way. In addition, the improvement in startup time is proportional to the complexity of your model - the more entities/properties/navigations/etc it has, the more gains you can expect. If you're not seeing improvements where you're expecting them, please post some sort of code sample which we can use to investigate.

> After reading the article above, I removed all my DbSet properties on my monolith DbContext and call context.Set<TEntity>() now instead. Is this perhaps the reason why I am not seeing obvious benefits?

Using DbSets (or not) is orthogonal to the question of compiled models and model building; the new compiled model feature is there to improve startup time (by cutting down model building), whereas using DbSets or not is a matter of initializing new DbContext instances (so general runtime perf). I'd recommend concentrating on one thing at a time - decide if you need to optimize startup or runtime perf, and then explore the appropriate feature.

BTW to get the absolute fastest runtime performance, use DbSet properties with [DbContext pooling](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#dbcontext-pooling) (though depending on your application, the effect may be minimal compared to other things happening elsewhere).

**Comment by Mike-E-angelo** [comment]
Cool thank you for taking the time to answer my questions, @roji!  It is very much appreciated.

> Your model can be accessed via the DbContext.Model property, so you can count various things as followed

I am indeed aware of being able to do this manually. :)  I was wondering if there was a way/tool that is already available that does this for me, in a way that is aligned with the metrics/expectations shown in the article.  

That stated I do appreciate your starting point, and would like to thank you for providing it.  I did use it and now see that I have 710 properties in my model.  That doesn't include relationships, however.  Eyeballing the blog post graph, it would seem I am expected to get around ~170ms which is very much within the margin of variance that I am experiencing when launching my Blazor server-side project (between 1-1.5 seconds of variance, sometimes more).

> First, it's important to understand that compiled models mostly improves startup time

That is where my interest lies. :)  Thank you for pointing out the difference in my approaches here.  It seems I was trying to improve the wrong area of interest, but the work is done with the `DbSet` property removal and can enjoy those improvements as well (which I am happy with already, btw).  I am also aware of `DbContext` pooling and look forward to exploring it further with my entity tier redesign.

OK... so all things considered, unless I have an inordinate amount of relationships, it sounds like everything is working as expected.  I should put some logging around that `DbContext` initialization/creation to get better metrics on the compiled model gains.  The tricky part with that is that I use scoped DI and not the `IDbContextFactory` (yet -- as per above I am working on it) so I have to "grab" it from DI when it's first initialing to get those metrics.

Btw, my startup time used to be 20 seconds and now it's down to 11.5-12.5 so I'm happy already with where things sit with .net6. 👍

Thank you again for your time and assistance.

**Comment by Mike-E-angelo** [comment]
FWIW in case anyone else is interested, additional discussion/example found here:
https://github.com/dotnet/efcore/issues/25523#issuecomment-902895492
