### ISSUE TITLE
How to find out which column(s) violated constraints and checks when calling SaveChangesAsync()

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [dotnet/efcore#25590]
Suppose I am building an ASP.NET Core web app using PostgreSQL as datastore (using Npgsql provider) and I have a User entity model such as
```c#
[Index(nameof(EmailAddress), IsUnique = true)]
[Index(nameof(EmployeeNo), IsUnique = true)]
public class User
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string FullName { get; set; }

    [Required]
    public string EmailAddress { get; set; }
    
    [Required]
    public int EmployeeNo { get; set; }
}

```

Now, when user provides me these details by submitting a form and in my business logic I create a User instance and save to the database using ```_db.SaveChangesAsync() ```

Now, suppose there is already a user with given EmailAddress or EmployeeNo. So ```_db.SaveChangesAsync() ``` will throw an error.

So, my questions are: 
1. how can I know which of the two - EmailAddress or EmployeeNo - caused this error. Either one of them or both of them might have caused it. So how do I know which one?

2. How to know the cause behind this error: Was it because of the unique index constraint? Or was it because of the ```[Required]``` attribute.

3. What kind of error handling techniques (using try-catch) should be used here?

4. What about error happened by integeroverflow, string length mismatch, etc.

     
Thanks!
     
     
#### Include provider and version information

EF Core version: 5.0.8
Database provider: Npgsql.EntityFrameworkCore.Postgres
Target framework:  .NET 5.0)
Operating system: Windows
IDE: VS Code

**Comment by roji** [comment]
Cross-posted as https://github.com/npgsql/efcore.pg/issues/1959 where I've answered for PostgreSQL.
