### ISSUE TITLE
Conversion errors in debugger are unhelpful

### ISSUE THREAD

**Issue by neil-119** [dotnet/efcore#25600]
## Ask a question

When we have `HasConversion<...>()` set in the mapping (e.g. enum saved as a string in the database), any kind of conversion error throws an exception like this:

![image](https://user-images.githubusercontent.com/4636522/130119223-c8209e96-7869-4ab0-a6ba-68e390231eda.png)

It doesn't say which column / table has the invalid data. This is a pain because we have a split query that's accessing numerous tables, and there's some column somewhere that has bad data, but it's very hard to narrow down what that column is. I tried enabling Source Link and stepping into the Enum.TryParse via the call stack, but all the locals in there seem to be optimized away. This has to be made clearer.

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2021 Preview

**Comment by ajcvickers** [comment]
@neil-119 Have you tried [EnableDetailedErrors](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#detailed-query-exceptions)?
