### ISSUE TITLE
HasDefaultValue(constant)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#25648]
Is there a variant of ```HasDefaultValue``` (or ```HasDefaultValueSql```) that allows you to:
1.  Provide a C# value

And will:
1. Convert the value to the SQL equivalent of it.
2. Take any conversions (ie. Enum<->String) into account
3.  Configure the database table so that the value is provided as a default.

I essentially want to be able to do the following:
```
.HasDefaultValueXXX(string.Empty)
.HasDefaultValueXXX(Visibility.Visible)
.HasDefaultValueXXX(TimeSpan.FromHours(1))
.HasDefaultValueXXX(1.1m)
```

Thoughts?

**Comment by roji** [comment]
@TonyValenti unless I'm missing something, the above is exactly how HasDefaultValue already behaves. See the sample code below and the resulting CREATE TABLE generated by EF Core. Can you please provide more detail on what you think is missing?

<details>
<summary>Code sample</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Property(b => b.SomeEnum)
            .HasDefaultValue(SomeEnum.Two)
            .HasConversion(e => e.ToString(), s => Enum.Parse<SomeEnum>(s));
    }
}

public class Blog
{
    public int Id { get; set; }
    public SomeEnum SomeEnum { get; set; }
}

public enum SomeEnum { One, Two };
```

</details>

<details>
<summary>CREATE TABLE</summary>

```sql
CREATE TABLE [Blogs] (
    [Id] int NOT NULL IDENTITY,
    [SomeEnum] nvarchar(max) NOT NULL DEFAULT N'Two',
    CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
);
```

</details>

**Comment by TonyValenti** [comment]
Odd!  I did some tests and that's not what I saw happen. Maybe I forgot to delete my DB between tests. 

Thanks!

**Comment by roji** [comment]
If you come with a scenario that looks problematic, please post a code sample for that - I'll close this issue in the meantime.
