### ISSUE TITLE
PMC Reverse-Engineer command not working with recent changes to reveng

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2564]
The Package Manager Console Reverse-Engineer command help needs to be updated to include the new runTimeProviderAssembly parameter

```
 PM> Reverse-Engineer -ConnectionString "Data Source=C:\Users\eejj\Downloads\WpfApplication1\WpfApplication1\WpfApplication1\Chinook.sdf"
Value cannot be null.
Parameter name: runtimeProviderAssemblyName
```

In fact, it looks like it is not working at all:

```
Reverse-Engineer : A parameter cannot be found that matches parameter name 'RuntimeProviderAssemblyName'.
At line:1 char:134
+ ... 1\Chinook.sdf" -RuntimeProviderAssemblyName "EntityFramework7.SqlServerCompact40 ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Reverse-Engineer], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Reverse-Engineer
```

Looks like EntityFramework.psm1 needs to be updated

**Comment by ErikEJ** [comment]
After implementing the fix, I now get this nice message :smile: 

    Unable to find design-time provider assembly. Please install the EntityFramework7.SqlServerCompact40.Design NuGet package and ensure that the package is referenced by the project.

**Comment by SherryDay** [comment]
Hi Erik,
I already installed EntityFramework.MicrosoftSqlServer.Design 7.0.0-rc1-final , but when I run the Command `Scaffold-Dbcontext -provider entityFramework.MicrosoftSqlServer -connection "Server=(localdb)\mssqllocaldb;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;"`

Still got error message
`Unable to find design-time provider assembly. Please install the EntityFramework.MicrosoftSqlServer.Design NuGet package and ensure that the package is referenced by the project.` Could you help me with this?
![image](https://cloud.githubusercontent.com/assets/8225531/14070960/6bf2ae22-f4e0-11e5-92ce-44b6c47da12c.png)

**Comment by ErikEJ** [comment]
I am note sure your issue is related - did you add the design dll to the correct project?
