### ISSUE TITLE
"Possible null reference return" in auto-generated compiled model

### ISSUE THREAD

**Issue by jamesgurung** [dotnet/efcore#25647]
When running `dotnet ef dbcontext optimize -c Database` with version `6.0.0-rc.2.21421.3` of the `dotnet-ef` tool, the generated code contains a compiler warning in `DatabaseModel.cs`:

```c#
private static DatabaseModel? _instance;
public static IModel Instance => _instance; // <-- warning CS8603: Possible null reference return
```

Not a big issue, but thought it might be helpful to report.

**Comment by roji** [comment]
@AndriySvyryd generate #nullable disable here too for now?

**Comment by AndriySvyryd** [comment]
No, we can just declare it as non-nullable, since it's initialized in the static constructor

**Comment by roji** [comment]
Sounds good, assuming there isn't other stuff...
