### ISSUE TITLE
Scaffolding doesn't generate default values

### ISSUE THREAD

**Issue by cilerler** [dotnet/efcore#25654]
Scaffolding doesn't generate default values, and I wonder if there is a way to enforce it.
Ideally I would expect `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]` attribute in models.

e.g.:

### Source

```SQL
[CreatedAt] DATETIME2 (3) CONSTRAINT [DF_importQueue_CreatedAt] DEFAULT (sysutcdatetime()) NOT NULL,
[SoftDelete] BIT CONSTRAINT [DF_importQueue_SoftDelete] DEFAULT ((1)) NOT NULL,
```

### Actual

```csharp
public DateTime CreatedAt { get; set; }
public bool SoftDelete { get; set; }
```

### Expected

```csharp
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public DateTime CreatedAt { get; set; }
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public bool SoftDelete { get; set; }
// OR at least
// public bool SoftDelete { get; set; } = true;
```

**Comment by ajcvickers** [comment]
@cilerler `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]` is only be scaffolded for computed columns, which these are not. Can you provide some more details about what it is you are trying to achieve?

**Comment by cilerler** [comment]
Thanks, @ajcvickers. I want the database default values to be available in the codebase.  
Right now, it ignores any default values on the database, and C# assigns `false` to `SoftDelete` and `DateTime.Min` to `CreatedAt`.  
The database default value only applies if the property is null, where those will never be `null`.  
On second thought, the best solution would be scaffolding to mark the field as `nullable` if it has a **DefaultValue** on the database.  So C# won't go to assign value, and it will get the default value from the server if there is no data for the field.  
Is that make sense?

**Comment by ajcvickers** [comment]
@cilerler We have [documentation on default values in change tracking](https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#working-with-default-values). Hopefully it answers your questions.

**Comment by cilerler** [comment]
@ajcvickers As stated in the subject, the issue is **Scaffolding doesn't generate default values**.  Can you elaborate on which part you think is related to the topic, please?

**Comment by ajcvickers** [comment]
@cilerler Default values are scaffolded into the EF model. For example:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

    modelBuilder.Entity<Foo>(entity =>
    {
        entity.Property(e => e.CreatedAt)
            .HasPrecision(3)
            .HasDefaultValueSql("(sysutcdatetime())");

        entity.Property(e => e.SoftDelete)
            .IsRequired()
            .HasDefaultValueSql("((1))");
    });

    OnModelCreatingPartial(modelBuilder);
}
```

**Comment by cilerler** [comment]
@ajcvickers, are you sure? It is not the case in my scenario. Did you hand-typed those, or did you test it?

**Comment by ajcvickers** [comment]
@cilerler I tested it and copy-pasted the generated code into here.

**Comment by cilerler** [comment]
thanks for the quick reply, 
any idea why it may not generate it? _(by the way source database is Azure SQL, if that make any difference)_

**Comment by ajcvickers** [comment]
@cilerler Post the database schema for the tables you are scaffolding from and I'll take a look.

**Comment by cilerler** [comment]
```sql
CREATE TABLE [dbo].[Foo] (
   [ID]                   BIGINT        IDENTITY (1, 1) NOT NULL,
   [CreatedAt]            DATETIME2 (3) CONSTRAINT [DF_Foo_CreatedAt] DEFAULT (sysutcdatetime()) NOT NULL,
   [SoftDelete]           BIT           CONSTRAINT [DF_Foo_SoftDelete] DEFAULT ((1)) NOT NULL,
   CONSTRAINT [PK_Foo] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
);
```

**Comment by ErikEJ** [comment]
Lack of rights to the Azure SQL db, known issue.

**Comment by cilerler** [comment]
@ErikEJ, can you provide me a link that states the issue, please?
@ajcvickers I tested with the initial admin on AzureSQL, and it worked.  So clearly it is a permission issue, and I wonder what permissions it needs to retrieve DefaultValues; other than being SA, any lead appreciated.

**Comment by ErikEJ** [comment]
@cilerler This is the related issue (notice that I have added a check for this to EF Core Power Tools) https://github.com/dotnet/efcore/issues/22842

**Comment by cilerler** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/c10864c1-2acd-4397-89d0-3a5667aab6d2-ccdabca3-9682-4342-aa5e-1222b8adc35f-v1.png?transparent=1&palette=1&width=246)
