### ISSUE TITLE
SharedTypeQueryRelationalTestBase does not delimit identifiers in raw SQL

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25661]
Test Can_use_shared_type_entity_type_in_query_filter_with_from_sql fails on PostgreSQL since ViewQuery24601 uses raw SQL without any identifier delimiting (`Select * from STET`), should use RelationalTestStore.NormalizeDelimitersInRawString.

/cc @maumar

**Comment by smitpatel** [comment]
The FromSqlRaw is being used inside HasQueryFilter on OnModelCreating. We cannot access method from test store there. So we cannot use the method. I can add `[]` as enclosing brackets rather than without one. Otherwise providers should just derive from context and override the test.
