### ISSUE TITLE
Roadmap Questions

### ISSUE THREAD

**Issue by jasonrichardcraig** [dotnet/efcore#2566]
Would you know where I can find the documentation so I can implement the HierarchyId, 2D / 3D Spatial and custom CLR types to EF7? Also do you know if Microsoft has any OData V4 tooling ready to work with EF7?

I have also a few questions about the scalability and performance of EF7; some developers in a different division abandoned EF altogether because of this. Have these problems been addressed?

Regards,

Jason Craig

**Comment by rowanmiller** [comment]
Custom types aren't really supported in EF7 just yet. We have laid some ground work to enable it in the future, but it won't be there for the initial RTM. You can track the work item here https://github.com/aspnet/EntityFramework/issues/240.

EF7 should address a number of the perf/scale issues with EF6. There are still some significant bottlenecks in the current beta code, we are waiting to address these until we have most of the features implemented (since new features change design, which in turn changes where the bottleneck is).

cc @danroth27 to answer the question of OData.

**Comment by marinehero** [comment]
@rowanmiller (or anybody): any news/update re core support for spatial? (last I saw was [dotnet/corefx#12034](https://github.com/dotnet/corefx/issues/12034))

Am super excited that ef on .netcore work on Linux machines... was about to port some services to run on the cloud with Redis (for caching in HA mode) when I hit the show stopper on spatial which would hit my DB to seed the data.

Was looking at creating my own CustomSqlServerTypeMapper and adding _temporary_ support for spatial based on (**surprise** I found the source to VS2010 [here](https://github.com/tforsberg/z/blob/518c5625642f99cbb6e1c87f1c15da8c4a93af87/Visual%20Studio%202013/Source/ndp/fx/src/DataEntity/System/Data/SqlClient/SqlTypesAssembly.cs))

**What would be the quickest realistic approach to get running live** ?

1. Wait for it to come via official core channels
2. Implement my temporary hack
3. Is there an alternative?

Basically the main spatial function I require is the .FromText() and .Distance() one(s).

Nutshell query I need to support:

```
var msgTarget = categoryId <= 0
        ? (from p in ctx.PostedMessages
            join t in ctx.MessagesTrendings on p.MessageID equals t.MessageID
            join r in ctx.MessageMedias on new {A = p.MessageID, B = 0} equals
            new {A = r.MessageID, B = (int) r.SeqNo}
            join u in ctx.UserFaceBookInfoes on p.UserID equals u.UserID
            where 
                (p.Expires >= DateTime.Now || p.Expires == null)
                && p.Deleted == null && p.Coordinate.Distance(targetGeo) <= userDistance
            select new {pm = p, m = r, ufb = u, t = t, distance = p.Coordinate.Distance(targetGeo)})
        : (from p in ctx.PostedMessages
            join t in ctx.MessagesTrendings on p.MessageID equals t.MessageID
            join r in ctx.MessageMedias on new {A = p.MessageID, B = 0} equals new {A = r.MessageID, B = (int) r.SeqNo}
            join u in ctx.UserFaceBookInfoes on p.UserID equals u.UserID
            where
                (p.Expires >= DateTime.Now || p.Expires == null)
                && p.Deleted == null && p.Coordinate.Distance(targetGeo) <= userDistance
                && (p.CategoryID & categoryId) > 0
            select new {pm = p, m = r, ufb = u, t = t, distance = p.Coordinate.Distance(targetGeo)});

var msgTargets = rankBy == 2
        ? msgTarget.OrderByDescending(m => m.t.AlgoB)
        : rankBy == 0 ? msgTarget.OrderBy(m => m.pm.Coordinate.Distance(targetGeo))
            : rankBy == 3 ? msgTarget.OrderBy(m => m.t.NewScore/(0.004*(m.pm.Coordinate.Distance(targetGeo) + 250)))
                : msgTarget.OrderByDescending(
                        m => m.t.NewScore*(100 - SqlFunctions.Exp(SqlFunctions.SquareRoot(m.pm.Coordinate.Distance(targetGeo)/userDistance*100)/2.25))/100
                    )
                    .ThenBy(m => m.pm.Coordinate.Distance(targetGeo));
```

**Comment by rowanmiller** [comment]
@marinehero we are planning the exact feature set for 1.2 at the moment - type conversion work (which would enable spatial) is something we are considering. We'll blog as soon as plans are locked.

cc @divega  in case he has any ideas about type mapping. I don't think it is as easy as replacing the type mapper.
