### ISSUE TITLE
Can't create tables in sqlite file

### ISSUE THREAD

**Issue by JokHuang** [dotnet/efcore#25694]
I want to use efcore sqlite, so code a sample project following the page 'https://docs.microsoft.com/zh-cn/ef/core/get-started/overview/first-app?tabs=visual-studio'.
the versions of 'Microsoft.EntityFrameworkCore.Sqlite' and 'Microsoft.EntityFrameworkCore.Tools' are both 3.1.17
it works in the console project, but doesn't work in the UWP project.

in console project, works well
![image](https://user-images.githubusercontent.com/27217397/130711222-7ac8dd89-cd32-4334-bc29-a3295aceb33d.png)
dbfile is created with tables
![image](https://user-images.githubusercontent.com/27217397/130712538-e036e208-e189-46b5-82c6-8b3832b17117.png)

in UWP project, fails
error when run 'Add-Migration InitialCreate' in Package Manager Console
error: _Startup project 'EFCoreUWP' is a Universal Windows Platform app. This version of the Entity Framework Core Package Manager Console Tools doesn't support this type of project. For more information on using the EF Core Tools with UWP projects, see https://go.microsoft.com/fwlink/?linkid=858496_
![image](https://user-images.githubusercontent.com/27217397/130712097-37562eae-79b7-49ea-9d61-1ba7b8f9369a.png)

when project runs the dbfile will be created with no tables, and error also occurs
![image](https://user-images.githubusercontent.com/27217397/130712953-50eabf2a-8dff-4143-8999-7611f303529c.png)

I tried some other versions in UWP project, all failed. Is there any version can work? Please tell me.

**Comment by ajcvickers** [comment]
@JokHuang In general EF Core doesn't work with UWP. We are working to make EF Core a great experience for some of the newer U.I. stacks such as MAUI and WinUI as they mature, but that doesn't include traditional UWP. For one thing, UWP doesn't support .NET Standard 2.1 or newer .NET runtimes, which essentially precludes it from working with EF Core.
