### ISSUE TITLE
EF Core Migration Bundles: dotnet ef 6.0.0-preview.7.21378.4: No --output option

### ISSUE THREAD

**Issue by jaliyaudagedara** [dotnet/efcore#25699]
I am trying EF Core Migration Bundles, and in the #19693 says,
>  Add --output to allow renaming the bundle as TODO: Checked

But I am not seeing such an option.
![image](https://user-images.githubusercontent.com/5653381/130774592-fab85e1f-ee1e-44d2-b562-38351cf3fe5e.png)

dotnet ef version:
```
PS E:\Temp\EfCore6\EfCore6> dotnet ef --version
Entity Framework Core .NET Command-line Tools
6.0.0-preview.7.21378.4
PS E:\Temp\EfCore6\EfCore6>
```

**Comment by roji** [comment]
`--output` was only added for 6.0.0-rc1 (note the milestone on #19693). You can use a daily build to try it.

**Comment by ErikEJ** [comment]
@julielerman  Are your tools updated?

`dotnet ef --version`

**Comment by julielerman** [comment]
facepalm ...all the moving parts. Thanks. No coffee yet LOL 
tools were at 6.0.0-rc.1.21409.5
just updated to 6.0.0-rtm.21507.9 and it's there.
