### ISSUE TITLE
Missing ORDER BY

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#25696]
### Include your code

```C#
[Table("Table_1")]
public partial class Table1
{
    [Key]
    public int Id { get; set; }

    public DateTime CreateTime { get; set; }
}

public partial class TestContext : DbContext
{
    public TestContext()
    {
    }

    public TestContext(DbContextOptions<TestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Table1> Table1 { get; set; }
}

var services = new ServiceCollection();
services.AddDbContext<TestContext>();
var serviceProvider = services.BuildServiceProvider();

var testContext = serviceProvider.GetRequiredService<TestContext>();
var sql = testContext.Table1.OrderBy(a => a.Id).Distinct().ToQueryString();
Console.WriteLine(sql);

```

### Expected Behavior

```
SELECT DISTINCT [t].[Id], [t].[CreateTime]
FROM [Table_1] AS [t]
ORDER BY [t].[Id]
```

### Actual Behavior

```
SELECT DISTINCT [t].[Id], [t].[CreateTime]
FROM [Table_1] AS [t]
```

### Include provider and version information

EF Core version:6.0.0-preview.7.21378.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system:Win11
IDE: Visual Studio 2022 17.0

**Comment by roji** [comment]
@Varorbc Distinct does not preserve ordering. As state in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.distinct):

> The expected behavior is that it returns an unordered sequence of the unique items in source.

Apply your OrderBy after Distinct to get the results you want:

```c#
var sql = testContext.Table1.Distinct().OrderBy(a => a.Id).ToQueryString();
```

**Comment by Varorbc** [comment]
I want to explain this question again. It is no problem for Distinct to return a disorder. If the data of Distinct is in order, should the returned data be in order?

**Comment by smitpatel** [comment]
> If the data of Distinct is in order, should the returned data be in order?

No. The definition of Distinct says that you can return in any order ignoring any inner orderings.

**Comment by Varorbc** [comment]
I checked the implementation of [Distinct](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Distinct.cs), [HashSet ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Distinct.cs)is used internally 
> A set is a collection that contains no duplicate elements, and whose elements are in no particular order.
> A HashSet<T> collection is not sorted and cannot contain duplicate elements.

HashSet is a collection without a specific order, not an unordered collection.If I insert a collection in a specific order, it will also be returned in a specific order.

**Comment by smitpatel** [comment]
> If I insert a collection in a specific order, it will also be returned in a specific order.

That is implementation detail and not the contract. It can be changed any time in future. We don't rely on undocumented behavior. This has been discussed at length in past. (Github is not being really co-operative in finding the earlier issue where discussion took place). And we are not going to change the behavior. As said above, if ordering is important for results, then specify it after Distinct operator.

**Comment by ajcvickers** [comment]
A a very simple example where items are not returned in the order they are inserted:

```C#
var hashSet = new HashSet<int>();
for (var i = 0; i < 10; i++)
{
    hashSet.Add(i);
}

hashSet.Remove(2);
hashSet.Add(1000);

foreach (var i in hashSet)
{
    Console.WriteLine(i);
}
```

```
C:/local/AllTogetherNow/FiveOh/bin/Debug/net5.0/FiveOh.exe
0
1
1000
3
4
5
6
7
8
9
```

**Comment by Varorbc** [comment]
@ajcvickers Thanks for your explanation

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/131972554-2c9d4e71-e040-4f58-b4ba-5a5a90ec39b4.png)

`Distinct `disorder is a description in C#, but is it also disorder in SQL? But the fact does not seem to be the case. As an ORM, should ef core be consistent with database behavior?

**Comment by roji** [comment]
@Varorbc this is definitely not something that's guaranteed to work, especially once you look at multiple databases and not just SQL Server. In fact, the ordering of rows coming out of a subquery (any SELECT inside parentheses) is also unordered, so the ORDER BY in your sample above has no guaranteed effect. This isn't just a theoretical thing - if you check across databases you really will see unordered items coming out.

**Comment by Varorbc** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#distinct-queries

@roji @ajcvickers  why are there different behaviors on different database providers?

**Comment by Varorbc** [comment]
@smitpatel
