### ISSUE TITLE
Cosmos: translate indexing into collection 

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25701]
```c#
_ = await ctx.Blogs.Where(b => b.Posts[2].Name == "foo").ToListAsync();
```

Note that since we support primitive collections, this should translate on those too.

**Comment by dalokey** [comment]
Really love this package, but without this key feature, I am very limited and will just have to go back to using the SDK for now

**Comment by ajcvickers** [comment]
Note from triage: also consider other issues related to primitive collections--see label `area-primitive-collections`.
