### ISSUE TITLE
Using EF & SQLite crashes in aspnet:5.0-alpine docker image with Segmentation Fault

### ISSUE THREAD

**Issue by drathnow** [dotnet/efcore#25703]
This issue was originally reported over two years ago [here](https://github.com/dotnet/efcore/issues/14504) and I followed the thread and reference to the new issue.  The Docker image used in that issue was microsoft/dotnet:2.2.1-aspnetcore-runtime-alpine and the issue is listed as resolved but I am having the same issue with EF and Sqlite in the Docker image aspnet:5.0-alpine.  I can't figure out if this is an issue with EF, .NET Runtime, or with the 5.0-alpine image.

 I have created a project that can reproduce the problem:

git clone repro repo https://github.com/drathnow/SqliteTestApp.git
cd SqliteTestApp/SqliteTestApp
dotnet publish -c Release -v n -o ./obj/Docker/publish SqliteTestApp.csproj
docker build -t sqlitetestapp .
docker run -it --rm sqlitetestapp /bin/sh
dotnet SqliteTestApp.dll

Has anyone else come across this problem?  Is there a solutions/workaround? 

If this is the wrong forum to ask this question could you point me in the right direction?

Thanks.

**Comment by BravoTango86** [comment]
Had the same issue overnight although with plain Microsoft.Data.Sqlite.  There seems to be an issue with journaling and setting journal_mode of the connection to MEMORY or OFF works and I can run your sample.  Will try to find some time to take a deeper dive later but I'm not anything that would necessitate a rollback.

**Comment by drathnow** [comment]
I am using the latest version of Microsoft.Data.Sqlite.  If I wanted to use SQLitePCLRaw, is it a straight replacement or is there other work that needs to be done?

**Comment by Lazer91** [comment]
I have the same issue, downgrading to .NET Core 3.1 and using `3.1-alpine` image, it is working.

**Comment by mockjv** [comment]
I appear to be experiencing this same issue with .NET 6.0 on Alpine arm64v8, but not on amd64 or bullseye-slim-arm64v8 (just as a base image comparison).  Once I gather enough details I'll probably publish a new issue on the matter (been trying to experiment with the options suggested across the various related issues first).
