### ISSUE TITLE
Report connection security: using SSL or not.

### ISSUE THREAD

**Issue by rlgordey** [dotnet/efcore#25719]
My original ConnectionString: `Server=localhost;Database=Test;Trusted_Connection=True;MultipleActiveResultSets=true;Pooling=false;`

With the latest build, I got an exception: `Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)`

I changed my ConnectionString to: `Server=localhost;Database=Test;Trusted_Connection=True;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=true;Pooling=false;`

No error now, fine. But I was thinking it would be nice if EF Core reported if SSL was in use when it opened the connection.

My Asp.Net Core API logs to Seq via Serilog. Ef Core automatically logs its info as well. It would be nice to add SSL on/off in the log for Open Connection Event along with the host/Instance and database.

```json
{"@t":"2021-08-25T22:31:54.4867037Z","@mt":"Opened connection to database '{database}' on server '{server}'.","@m":"Opened connection to database 'Test' on server 'localhost'.","@i":"fcd09a07","@l":"Debug","database":"Test","server":"localhost","EventId":{"Id":20001,"Name":"Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpened"},"SourceContext":"Microsoft.EntityFrameworkCore.Database.Connection","ActionId":"c95b8256-07c4-4060-a483-6fb1bc098bd4","ActionName":"EcommerceWebAPI.Controllers.v1.HeaderController.GetHeaderAsync (EcommerceWebAPI)","RequestId":"80003df9-0004-f300-b63f-84710c7967bb","RequestPath":"/api/v1/Header","ClientIp":"127.0.0.1","ClientAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0","EnvironmentName":"Development","MachineName":"ZACH-OMEN","EnvironmentUserName":"ZACH-OMEN\\rgord","DebuggerAttached":true,"Application":"EcommerceAPI"}
```

**Comment by ajcvickers** [comment]
@rlgordey We discussed this, and we believe that this kind of logging is something that can easily be done by the application which can include anything interesting to those application developers. This seems better than trying to guess what applications might want (if anything) if EF Core we to do this.
