### ISSUE TITLE
AddDbContext Split ModelBuilders in a Shared Project

### ISSUE THREAD

**Issue by lixaotec** [dotnet/efcore#25724]
Dear folks, 

How to split ModelBuilders configuration, lets say for a 'generic dbcontext', and apply them by DI?

Lets say I have the Shared Project with a SharedDbContext that does know which entity confi will be applied, and I pass them with DI in its constructor, is it possible?

Something like the schematics bellow. Note that SharedDbContext would not know / references others projects that uses it. (so its like inversion .

```C#
public class SharedDbContext : DbContext
{
    public MyDbContext(DbContextOptions<SharedDbContext > options, **CustomConfiguration customConfigs[]**) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
 
        foreach( customConfigs )
        modelBuilder.AddConfiguration(new CustomConfigs());
    }
}
```

Hope to make it clear

Appreciate you help;

**Comment by ajcvickers** [comment]
@lixaotec By default, EF Core creates a single model for a given DbContext type. You can change this by overriding the model cache key. See [Alternating between multiple models with the same DbContext type](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model) in the docs.

**Comment by lixaotec** [comment]
I could accomplish it, simply by injecting an interface of context at my Repositories classes. so at startup I call the addscoped to Icontext and it works. hope it is right though
