### ISSUE TITLE
How to use two SQL Server database tables (localhost) at the same time?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnet/efcore#25752]
Hello:
I have two SQL Server 2019 databases in one PC (localhost). 
The one in production is called [LiveDB], and the one in backup is called [BackupDB].  Every night near 11:00PM, all data tables in [LiveDB] will be copied to [BackupDB], then all data table in [LiveDB] will be cleared, so new data can be written to it.
Now, I have to write one C# function to retrieve records from one data table, it is called [Table1].

The following is the [Table1] definition: (SQL Server 2019)

```sql
CREATE TABLE [dbo].[Table1](
[Name] [nvarchar](30) NOT NULL,
[ID]      [int] NOT NULL,
[Value] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Table1] PRIMARY KEY CLUSTERED 
(
[ID] ASC, [Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

Usually, there are some records in [LiveDB].[DBO].[Table1] and other records in [BackupDB].[DBO].[Table1], but those records in [LiveDB], are not in [Backup].
I want to write one C# function to retrieve all the records from both [LiveDB] and from [BackupDB], how I can proceed?

I created one C# console project with Visual Studio 2019 (version 16.11.2), I installed nuget package:
PM > Install-Package Microsoft.EntityFrameworkCore -Version 5.0.9
The following is the C# code for [LiveDB].

```sql
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseSqlServer(@"Data Source=.;Initial Catalog=LiveDB;Integrated Security=True");
    optionsBuilder.EnableSensitiveDataLogging();
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Table1>().ToTable("Table1").HasKey(k => new { k.ID, k.Value });
}
```

I can write C# function to retrieve all records in [Table1] from [LiveDB] database (SQL Server 2019), but I also need the records in [Table1] from [BackupDB].
The connection string for [BackupDB] is almost the same as for [LiveDB], like this:
@"Data Source=.;Initial Catalog=BackupDB;Integrated Security=True");
Please advise on how I can write a C# function to do this.
Thanks,

**Comment by ajcvickers** [comment]
@zydjohnHotmail Typically this would be done using two different DbContext instances of the same DbContext type, each configured with its own connection string to point to the correct database. You could potentially mutate the connection string on the connection returned by `context.Database.GetDbConnection`, but it would be easy to get conflicts if you try to track entities from both databases like this.

**Comment by zydjohnHotmail** [comment]
Hello:
Can you show some code for what you have said?
Thanks,
