### ISSUE TITLE
Run SqlClient test passes for 7.0

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25766]

**Comment by roji** [comment]
All tests pass with both SqlClient 3.0.0 and 4.0.0-preview1.21237.2.

However, there seems to be **quite** the perf regression in one of our tests - opened https://github.com/dotnet/SqlClient/issues/1234. This look like a pure SqlClient issue.

**Comment by roji** [comment]
We've just updated to use the recently-released 5.0... @ajcvickers I think that should cover this, no?

**Comment by ajcvickers** [comment]
Yep.
