### ISSUE TITLE
Cosmos: Narrow gap between EF and SDK LINQ provider

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25764]
https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql

Partial issue list:

* [ ] #25701
* [ ] #25700
* [ ] #17312
* [ ] #17317

**Comment by AndriySvyryd** [comment]
Is this just a dupe of https://github.com/dotnet/efcore/issues/33033 now?

**Comment by ajcvickers** [comment]
@AndriySvyryd Yeah, I'm going to go do the older composites for cosmos and see if they need retaining for anything.
