### ISSUE TITLE
Cosmos: Support queries into primitive collections

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25765]
Consider:

- [x] #25701
- [x] #25700
- [x] Contains
- [ ] Join

Composition over (non-primitive) embedded collection - see also #16926, #17957

**Comment by roji** [comment]
Aha, so we want both labels *and* story/epic tracking issues!

**Comment by roji** [comment]
Querying into primitive collections has been implemented for 9.0.
