### ISSUE TITLE
Hang `CosmosQueryableExtensions.FromSqlRaw` from `DbSet`

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25778]
As previously discussed, this extension method clashes with the relational method of the same name. However, two points that I don't think we discussed explicitly:
* When both packages are referenced, the compiler chooses one or the other. There is no error. So it's very hard to figure out what is wrong.
* You get the relational one with just these packages:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-rc.1.21423.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="6.0.0-rc.1.21423.18" />
  </ItemGroup>
```

Presumably because Design pulls in Relational.

**Comment by AndriySvyryd** [comment]
It's probably because the Cosmos version is declared on `IQueryable<TEntity>` instead of `DbSet<TEntity>`

**Comment by smitpatel** [comment]
That should be updated!

**Comment by ajcvickers** [comment]
Which would be a bug, right? It should be on DbSet only for the same reason the relational one is.

**Comment by smitpatel** [comment]
Yes.
