### ISSUE TITLE
Sequence Default Value & Configure Identity As Default

### ISSUE THREAD

**Issue by brent-russell** [dotnet/efcore#2580]
I found this, noting the decision to default auto-incrementing fields to sequences: https://github.com/aspnet/EntityFramework/wiki/Entity-Framework-Design-Meeting-Notes---July-31,-2014#sql-server-value-Generation
1. Why is the default sequence increment set to 10 when a migration is added, and not 1?
2. Is there a way to specify the sequence cache value? The default 50 is likely fine 90% of the time, but is the cache value something that will be supported, or is it considered too low level for schema design?
3. Is there a way to configure a DbContext to force the "migration add" command to always use Identity instead of Sequence for auto-incrementing PK columns?

**Comment by rowanmiller** [comment]
@brent-russell we actually [reverted this decision](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-June-18,-2015#default-sql-server-value-generation-strategy) and will use identity as the default. But to answer your questions.

1) The discussion isn't about using a default value on a column to access the sequence during insertion of records, but pulling blocks of values back from the database and assigning them to objects as they are added to the context (HiLo pattern).

2) Not currently. Easiest way would be to use the `Sql(string)` method within your migration to run an `ALTER SEQUENCE` command after the sequence is created.

3) Yes. Well we actually do that by default now. But the API was `modelBuilder.ForSqlServer().UseIdentity()`.

**Comment by brent-russell** [comment]
Thanks for the response. That makes sense. And if the majority of insertions are happening through EF, the cache value becomes less relevant.

Are the "low" sequence values being cached somehow so unused values will be used on the next transaction/batch, or do new batches get a new "high" increment?

**Comment by rowanmiller** [comment]
@brent-russell they are cached and used by any additions within the AppDomain.
