### ISSUE TITLE
SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)

### ISSUE THREAD

**Issue by hariramp** [dotnet/efcore#25803]
I'm trying to connect SQL Server using Entity Framework 5.0 and .NET 5.0

I;m able to connect to SQL Server with Single Node instance without any issue I have DR SQL Server when I have MultiSubnetFailover=True in my connection string like

data source=server1;Initial Catalog=db;User ID=uid;Password=pwd;MultipleActiveResultSets=True;MultiSubnetFailover=True;

I'm getting errors in connection
SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)

I'm able to successfully connect in Dot Core 2.1 with the above connection string

**Comment by robi26** [comment]
I'm having the exactly same issue, migrating from .net 5 to 6. what was the solution?
