### ISSUE TITLE
.UseSqlite : Does not apply HasQueryFilter correctly on "include" childrens properties

### ISSUE THREAD

**Issue by plemieux-sg** [dotnet/efcore#25800]
### Include version information

Assemblies

- Microsoft.EntityFrameworkCore.Sqlite, Version=5.0.9.0
- Microsoft.EntityFrameworkCore, Version=5.0.9.0

Target framework:  NET 5.0

After upgrading a project from .net core 2.2 to .net 5.0, some of our unit test starts failing suddenly. All of them are trying to validate the number of "ParticipantDetails" return by an Entity framework query that is using a query filter defines like this ...

modelBuilder.Entity<ParticipantDetail>().HasQueryFilter(o => !o.IsRecordCanceled);

The unit tests are all using a "SqliteConnection". The entities use for these tests are quite simple. 

- Participant
- ParticipantDetail
- AdditionalParticipant

The entity "participant" have multiple "ParticipantDetail". A "ParticipantDetail" only have one "AdditionalParticipant". The "ParticipantDetail" have a property call "IsRecordCanceled" that we used to filter the record that should be output in our system. If the "IsRecordCanceled" property is set to true, the record should never be returning to the application. 

For example, if we run this query on a dataset of 4 "ParticipantDetail", with 2 of the with the "IsRecordCanceled" property set to "true", the expected output should be 2 results ... 

var query2 = _participantContext.ParticipantDetails.ToList()

And that is the case. It's working perfectly. Now, if we execute the query on the "Participant" object, we would expect the number of "ParticipantDetail" to still be at 2, well this time it doesn’t work. So, the following query return 1 Participant, but 4 participantdetail.

var query = _participantContext.Participant.Include(i => i.ParticipantDetails).ToList();

If we try to execute the same code, but this time using an SQL Server database connection, instead of the Sqlite connection, the filters are applied correctly. Both queries return only 2 "ParticipantDetails" just like we expected. The error only occurs if we are using "SQLite".

Using a "Entity Framework Interceptor", we were able to confirm that the query generates by EF does include the filter in both queries.

If the query is executed against a SQL Server database, the filter is applied like this in the query 

WHERE ([p0].[IsRecordCanceled] = CAST(0 AS bit))

But, in SQlite, the filter is applied like this instead : 

WHERE ("p0"."IsRecordCanceled" = 0)

We try to change the query execute by SQLite, to use the first syntax but it did not solve the problem. We were still getting "ParticipantDetail" with the IsRecordCanceled property set to true.

Do you have any ideas how to fix this?

I will include a sample project you can use to replicate the issue. Just let me know if you have any problem with it.
[QueryFilterExceptions.zip](https://github.com/dotnet/efcore/files/7084420/QueryFilterExceptions.zip)

Best regards,

**Comment by plemieux-sg** [comment]
Hi,

I found this section on the "Eager Loading of Related Data" in the Microsoft Documentation (https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include)

> Caution : 
> 
> In case of tracking queries, results of Filtered Include may be unexpected due to navigation fix up. All relevant entities that have been queried for previously and have been stored in the Change Tracker will be present in the results of Filtered Include query, even if they don't meet the requirements of the filter. Consider using NoTracking queries or re-create the DbContext when using Filtered Include in those situations.

In our unit tests, before running our test, we need to clear any tracked changes in the DBContext.

_context.ChangeTracker.Clear();

This will reset the tracked changes, and then if we execute a query using the "HasQueryFilter", it will work as expected.

It will solve the problem with the Sqlite, and our unit tests will work as expected.

But I'm not sure if this solution is a workaround. What do you think?

Regards,
_

**Comment by smitpatel** [comment]
I investigated the repro code provided. Issue is reusing the same context which was used to seed data to server. Since the context is already tracking all ParticipantDetails, regardless of Include or query being run, participant.ParticipantDetails navigation will have all 4 records. The note referred above is accurate. The Include will apply proper filter if the entities which should be not included are not being tracked by the context. 

You can use either ChangeTracker.Clear() or initialize new context which is different from the context used for seeding data. DbContext is supposed to be used as unit of work only.
