### ISSUE TITLE
Move Thread_safety_in_relational_command_cache out of QueryBugsTest

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25815]
As part of https://github.com/dotnet/SqlClient/issues/1234, it turns out we have a concurrent test (Thread_safety_in_relational_command_cache) in QueryBugsTest, which reuses the same SqlConnection instance. This isn't an actual problem at the moment since SqlClient's unmanaged Windows networking implementation seems fully thread-safe, but this test would fail badly on Linux/Mac. It also fails/blocks on SqlClient 4.0.0-preview.1.

**Comment by smitpatel** [comment]
Move where though?

**Comment by roji** [comment]
I don't know :) We'd have to think of something.

**Comment by roji** [comment]
BTW maybe it can just be in on of the regular test suites - it doesn't need any specific database schema, so any test suite where DbContext instances don't share DbConnections should be fine...

**Comment by smitpatel** [comment]
I mean what issue the test particularly have inside query bugs test? As part of deprecating QueryBugsTest, we have non shared model tests which are somewhat provider agnostic.

**Comment by roji** [comment]
Maybe in SqlServerEndToEnd tests?

**Comment by AndriySvyryd** [comment]
To make that test use connection string replace the first line with
```C#
var contextFactory = await InitializeAsync<MyContext21666>(
    onConfiguring: options =>((IDbContextOptionsBuilderInfrastructure)options).AddOrUpdateExtension(
        options.Options.FindExtension<SqlServerOptionsExtension>()
            .WithConnection(null)
            .WithConnectionString(SqlServerTestStore.CreateConnectionString(StoreName))));
```
