### ISSUE TITLE
Precompiling models and missing usings

### ISSUE THREAD

**Issue by Enngage** [dotnet/efcore#25812]
Hey everyone,

I'm attempting to generate precompiled models with: 

```optimize-DbContext -Context AppDbContext -OutputDir EFPrecompiledModels```

which is working fine in itself, but the problem I have is that the generator does not add `usings` if my model references some stuff from other projects within the solution. I have to manually go and add these usings myself.

Is there some setting I'm missing or is this perhaps something that was not yet implemented?

Additionally, it would be nice if there was an option to mark the class extending `RuntimeModel` public - I have migrations & EF models in a separate project, and so if I generate models here, I have to manually add `public` accessor to the class so I can use it in `Startup` configuration.

Thanks!

### Include provider and version information

EF Core version: 6.0.0-preview.7.21378.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET6
Operating system: Win
IDE: VS 2022

**Comment by ajcvickers** [comment]
@Enngage Can you please show some examples of when this is needed. Usings are already added for things we detect, so we must be missing something here.

**Comment by Enngage** [comment]
@ajcvickers in my case it seems to happen exclusively with `enums`. All my models are defined in `Entity` project and some of them have enum field like: 

```
        [NotMapped]
        public ClientFeedTypeEnum FeedType
        {
            get => FeedTypeInternal.ToEnum<ClientFeedTypeEnum>();
            set => FeedTypeInternal = value.ToString();
        }
```

In this case of field above, if the `ClientFeedTypeEnum` is defined in a different project, the `using` is missing from the generated model.

**Comment by AndriySvyryd** [comment]
@Enngage I'm unable to repro this. Could you provide a small project that shows the issue?

**Comment by Enngage** [comment]
@AndriySvyryd, thanks for getting back to me & adding the `public` accessor. 

I've updated our project to `.NET 6 RC1` and for whatever reason it all works fine. It seems that the `enums` are not even used in generated models, and so the project builds ok.

**Comment by Enngage** [comment]
I suspect this might have been a problem with previous version of VS because multiple usings were broken just by updating VS and making no code changes.
