### ISSUE TITLE
FromSqlParameterExpandingExpressionVisitor incorrect works with (invariant) parameterName

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#25822]
EFCore: main

**Description**
FromSqlParameterExpandingExpressionVisitor incorrect works with parameterName and invariantParameterName

parameterName may contains prefix of named parameter.

invariantParameterName contains clear name (without prefix) of parameter.

https://github.com/dotnet/efcore/blob/f31406b9acba4ade0a7d6b730283e30eb8ae2925/src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs#L116-L138
This code must be write like that:

``` c#
                        var invariantParameterName = _parameterNameGenerator.GenerateNext();
                        if (parameterValues[i] is DbParameter dbParameter)
                        {
                            if (string.IsNullOrEmpty(dbParameter.ParameterName))
                            {
                                dbParameter.ParameterName = _sqlGenerationHelper.GenerateParameterName(invariantParameterName);
                            }
                            else
                            {
                                invariantParameterName = _sqlGenerationHelper.ExtractInvariantParameterName(dbParameter.ParameterName);
                            }

                            subParameters.Add(new RawRelationalParameter(invariantParameterName, dbParameter));
                        }
                        else
                        {
                            subParameters.Add(
                                new TypeMappedRelationalParameter(
                                    invariantParameterName,
                                    _sqlGenerationHelper.GenerateParameterName(invariantParameterName),
                                    _typeMappingSource.GetMappingForValue(parameterValues[i]),
                                    parameterValues[i]?.GetType().IsNullableType()));
                        }
```

where _sqlGenerationHelper.ExtractInvariantParameterName may looks like that:
``` c#
        public virtual string ExtractInvariantParameterName(string parameterName)
            => parameterName.StartsWith("@", StringComparison.Ordinal)
                ? parameterName.Substring(1)
                : parameterName;

```

Same problem in following lines:

https://github.com/dotnet/efcore/blob/f31406b9acba4ade0a7d6b730283e30eb8ae2925/src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs#L152-L162

Proposal:
```c#
                            var invariantParameterName = _parameterNameGenerator.GenerateNext();
                            if (string.IsNullOrEmpty(dbParameter.ParameterName))
                            {
                                dbParameter.ParameterName = _sqlGenerationHelper.GenerateParameterName(invariantParameterName);
                            }
                            else
                            {
                                invariantParameterName = _sqlGenerationHelper.ExtractInvariantParameterName(dbParameter.ParameterName);
                            }

                            constantValues[i] = new RawRelationalParameter(invariantParameterName, dbParameter);

```

**Comment by smitpatel** [comment]
Please provide details how is this causing an error.

**Comment by dmitry-lipetsk** [comment]
> Please provide details how is this causing an error.

I detected these problems when executed your tests FromSqlQueryTestBase with my providers.

For example:

https://github.com/dotnet/efcore/blob/b820df402b100846ea0419a27fe4e701e33a0b8b/test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs#L1113-L1130

generates SQL:

`
SELECT * FROM "Customers" WHERE "CustomerID" = @@somename
`

Reason:

1. parameterName "@somename" passed into RawRelationalParameter as invariantName

https://github.com/dotnet/efcore/blob/f31406b9acba4ade0a7d6b730283e30eb8ae2925/src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs#L128

2. This incorrect "invariantName" was processed by GenerateParameterNamePlaceholder and transformed into "@@somename"

https://github.com/dotnet/efcore/blob/f31406b9acba4ade0a7d6b730283e30eb8ae2925/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L372

----
I think, need rename parameter 'name' in (ISqlGenerationHelper) GenerateParameterName, GenerateParameterNamePlaceholder to 'invariantName'.

This will reduce a confusion with names.

**Comment by smitpatel** [comment]
It generates following in SqlServer provider. I don't see a double "@" there. The bug could be somewhere else too.

![image](https://user-images.githubusercontent.com/1528107/131730114-8d6f327f-6e28-4dd3-af20-a38e468c8205.png)

**Comment by dmitry-lipetsk** [comment]
https://github.com/dotnet/efcore/blob/681727494fcdd6f795d719d38857820fad89c70e/src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs#L77-L80

I know about this hack for avoid an incorrect work of caller side.

But OK.

In general, this is not critical problem for me.

**Comment by smitpatel** [comment]
It is not a hack.
`InvariantName` refers to the name to look for in the dict. Plus it refers to candidate parameter name. `GenerateParameterName` method is supposed to generate a valid parameter name given candidate name which would be in-built into the SQL. Caller & method both are working as expected in current design.
