### ISSUE TITLE
How to compare json string when using JsonValueConverter

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#25823]
Background:
When I map JSON column to a complex C# object, I would like to perfom comparison using the json string rather than implementing complex ValueComparer.

### GIVEN 
following SQL Table with json column

```SQL
CREATE TABLE isys.Records
(
  Id  INT NOT NULL IDENTITY(1, 1), 
  ComplexObjectJson NARCHAR(MAX) NULL,
);
```

and following  C# entities

```csharp
public class Record 
{
       public int Id { get; private set; }
       public ComplexObject ComplexObject { get; private set; } //JSON is a complex mutable object
}

public class ComplexObject 
{
   public string Name { get; set; }
   public List<int> Values {get; set;}
}
```

### WHEN 
I use the Value Converter
```csharp
public void Configure(EntityTypeBuilder<Record > entity)
{          
    entity.Property(e => e.Steps)
       .HasColumnName("ComplexObject")
       .HasConversion(new JsonObjectConverter<ComplexObject >());
}

public class JsonObjectConverter<TModel> : ValueConverter<TModel, string>
{
    public JsonObjectConverter() : base(
        v => JsonSerializer.Serialize(v, null),
        v => JsonSerializer.Deserialize<TModel>(v, null)
    )
    { }
}
```

### THEN
 detecting changes in the deserialized JSON object won't work, because it uses comparison by reference

```csharp
//mutate the JSON object
Record record = MyDbContext.Find<Record>(id);
record.Steps[0].Name += "*";

//detect changes
MyDbContext.DetectChanges();
Console.Log(MyDbContext.Entry<Record>().State); //Unchanged
```

### Question:
Is it possible to compare the original JSON string value with current JSON value (obtained by serializing current value)?

Current fluent mapping API does not allow me to use the original JSON string as a snapshot and it forces to create copy of `ComplexObject` and implement comparison on the deserialized object.

**Comment by smitpatel** [comment]
See https://docs.microsoft.com/ef/core/modeling/value-comparers

**Comment by Liero** [comment]
@smitpatel: I have read the documentation, of course. There is no answer to my question:

> Is it possible to compare the original JSON string value with current JSON value (obtained by serializing current value)?


The best I could achieve is this very inefficient ValueComparer.

```csharp
public class JsonValueComparer<T> : ValueComparer<T>
{
    public JsonValueComparer(JsonObjectConverter<T> converter) : base(
        (i1, i2) => Equals(i1, i2, converter),
        i => i.GetHashCode(), 
        i => Snapshot(i, converter))
    {
    }

    public static bool Equals(object left, object right, JsonObjectConverter<T> converter)
    {
        var leftProviderValue = converter.ConvertToProvider(left);
        var rightProviderValue = converter.ConvertToProvider(right);
        return Object.Equals(leftProviderValue, rightProviderValue);
    }

    public static T Snapshot(T instance, JsonObjectConverter<T> converter)
    {
        return (T)converter.ConvertFromProvider(converter.ConvertToProvider(instance));
    }
}
```

**Comment by ajcvickers** [comment]
@Liero No, this is not possible. You should compare ComplexObject instances in the normal C# way.

**Comment by Liero** [comment]
> @Liero No, this is not possible. You should compare ComplexObject instances in the normal C# way.

Thanks for reply. Using the original value as a snapshot would be IMHO great, because it would remove a lot of overhead needed to create a snapshot
