### ISSUE TITLE
Cast error when using InMemoryDb (tests) and GetColumnType()

### ISSUE THREAD

**Issue by elvirdolic** [dotnet/efcore#25844]
## File a bug

When upgrading from .net core 3.1 to net5 we found an issue in our tests by using following code to determine the ColumnType of a Database Column

```C#
         var classificationType = typeof(EpcClassification);
            var entityType = _context.Model.FindEntityType(classificationType);
            var schema = entityType.GetSchema();
            var tableName = entityType.GetTableName();
            var storeObjectIdentifier = StoreObjectIdentifier.Table(tableName, schema);
            var entityProperties = entityType.GetProperties().ToList();
            List<string> columns = new List<string>();
            foreach (var p in entityProperties)
            {
                columns.Add($"`{p.GetColumnName(storeObjectIdentifier)}` {p.GetColumnType()}");
            };
  
```

```
 Error Message:
   System.InvalidCastException : Unable to cast object of type 'Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTypeMapping' to type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping'.
  Stack Trace:
     at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindRelationalTypeMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnType(IProperty property)
```

### Include provider and version information

EF Core version: 5.0.9
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .Net 50
Operating system: Linux | Windows
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@elvirdolic The in-memory database is not a relational database. It does not have column names. See https://docs.microsoft.com/en-us/ef/core/testing/

**Comment by elvirdolic** [comment]
This code was working with .net core 3.1

When I debug and check: p.GetColumnName(storeObjectIdentifier)}` {p.GetColumnType()}" => I get a column name but I get an exception when try to access p.GetColumnType()

**Comment by ajcvickers** [comment]
@elvirdolic It may have "worked" by accident on 3.1, although I expect there were cases where it gave incorrect data. Nevertheless, the in-memory database does not support columns or their names or types, and so these methods should not be used with the in-memory database.

**Comment by elvirdolic** [comment]
Thank you for the information - it's clear now.
