### ISSUE TITLE
Improve exception message when configuring an owned entity type as non-owned

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#25863]
I have a two entities in a one to many relationship.

I have created a DbSet for the principal. I _do not_ want a DbSet for the dependent entity.

The expected result is that implicit ownership kicks in and the dependent is stored within the principal's document.

If I want to override that, having the dependent in its own document, I can explicitly configure it as

`modelBuilder.Entity<childentity>();`

So far so good.

But if I want to configure a property of that childentity e.g.,

`modelBuilder.Entity<childentity>().ToJsonProperty("xyz");`

this will ALSO force the child entity into its own document, even if I still want it to be separated.

Is this a bug? Is there a better way?

Note: I can't add an explicit OwnsMany for the property. This results in a runtime error saying that it's already configured as non-owned.

EF Core version: 6.0.0-rc.2.21452.24
Database provider:Microsoft.EntityFrameworkCore.Cosmos)
Target framework: .NET 6.0
Operating system: macOS
IDE: VS Code

**Comment by AndriySvyryd** [comment]
All embedded entity types are owned, so you should be able to use `OwnsMany`. Can you post the code that throws?

**Comment by julielerman** [comment]
Not sure how much detail so here are the mappings:

    modelBuilder.Entity<Person> ().OwnsMany (p => p.Addresses);
    modelBuilder.Entity<Address> ().Property( a=>a.PostalCode).ToJsonProperty("zipcode");

In this order, the error is 
```Unhandled exception. System.InvalidOperationException: The entity type 'Address' cannot be configured as _non-owned_ because it has already been configured as a _owned_. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'.```

If I reverse those lines then the exception is the opposite:

```Unhandled exception. System.InvalidOperationException: The entity type 'Address' cannot be configured as _owned_ because it has already been configured as a _non-owned_. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'.```

**Comment by AndriySvyryd** [comment]
Ok, I see. To configure owned types you need to use a nested lambda;

```
modelBuilder.Entity<Person>().OwnsMany(p => p.Addresses, b => b.Property(a => a.PostalCode).ToJsonProperty("zipcode"));
```

**Comment by julielerman** [comment]
facepalm! Didn't think of that for a related object. I have to get used to owned type paradigms applying to related objects in this scenario. :)

So this way I can have my cake and eat it too. Set up the related type as a nested document and still configure it if needed. THanks
