### ISSUE TITLE
Internal function parameter type added as entity type on model creation when model contains many-to-many relation

### ISSUE THREAD

**Issue by slavanap** [dotnet/efcore#25879]
#### Sample program
Copy-paste from [official documentation](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#other-relationship-patterns), but with debug output and added user function (without DbFunctionAttribute)

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1 {

    internal class MyContext : DbContext {
        public DbSet<Post> Posts { get; set; }
        public DbSet<Tag> Tags { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
                Console.WriteLine(entity); // <<< DEBUG OUTPUT IS FROM HERE

            modelBuilder.Entity<Post>()
                .HasMany(p => p.Tags)
                .WithMany(p => p.Posts)
                .UsingEntity<PostTag>(
                    j => j
                        .HasOne(pt => pt.Tag)
                        .WithMany(t => t.PostTags)
                        .HasForeignKey(pt => pt.TagId),
                    j => j
                        .HasOne(pt => pt.Post)
                        .WithMany(p => p.PostTags)
                        .HasForeignKey(pt => pt.PostId),
                    j => {
                        j.HasKey(t => new { t.PostId, t.TagId });
                    });
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            optionsBuilder.UseInMemoryDatabase("test");
        }

        public async Task MyFunc(string a, Dictionary<string, object> b, CancellationToken c)
            => throw new NotImplementedException();
    }

    public class Post {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public ICollection<Tag> Tags { get; set; }
        public List<PostTag> PostTags { get; set; }
    }

    public class Tag {
        public string TagId { get; set; }

        public ICollection<Post> Posts { get; set; }
        public List<PostTag> PostTags { get; set; }
    }

    public class PostTag {
        public DateTime PublicationDate { get; set; }

        public int PostId { get; set; }
        public Post Post { get; set; }

        public string TagId { get; set; }
        public Tag Tag { get; set; }
    }



    class Program {
        static void Main(string[] args) {
            new MyContext().Set<Post>().SingleOrDefault(); // force OnModelCreating
        }
    }
}
```

#### Program output
```
EntityType: Post
EntityType: PostTag Keyless
EntityType: Tag
EntityType: PostTag (Dictionary<string, object>) CLR Type: Dictionary<string, object>
```

#### Actual behaviour
modelBuilder.Model.GetEntityTypes() contains `EntityType: PostTag (Dictionary<string, object>) CLR Type: Dictionary<string, object>`

#### Expected behavior
This element is missing in entities set.
It does not seem right to me that unrelated type is presented in this list. Please correct me if I'm wrong.

#### Versions
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
  </ItemGroup>

</Project>
```

**Comment by ajcvickers** [comment]
@slavanap The entity types in the model at the beginning of OnModelCreating are those that have been discovered by convention. This includes the by-convention many-to-many join entity type. Once the model has been built and finalized it should not be present because PostTag has then been configured as the join type. In other words, the model observed is OnModelCreating should not be considered final and will change as the model is further configured.

**Comment by slavanap** [comment]
@ajcvickers could you please elaborate on how entity
`EntityType: PostTag` ended up being related to `CLR Type: Dictionary<string, object>` after such automatic discovery?

**Comment by ajcvickers** [comment]
@slavanap I don't see the two types as related in the output you posted. I see two entity types, both called PostTag, one of which is of type `Dictionary<string, object>`. This is the by-convention join type.

**Comment by slavanap** [comment]
@ajcvickers the why if I comment `MyFunc` declaration, type called PostTag with CLR type Dictionary, disappears from the output?

**Comment by ajcvickers** [comment]
@slavanap That I don't know. But does it matter? If so, how?

**Comment by ajcvickers** [comment]
@slavanap 

>  I expect the list returned by modelBuilder.Model.GetEntityTypes() to be intact.

This is not a valid expectation. The entity types in the model during model building may both contain types that are not ultimately mapped as entity types, and not contain types that are ultimately mapped as entity types.

**Comment by slavanap** [comment]
@ajcvickers alright. Where's the description of what to expect in that list? For instance I want to select all entity records related to "PostTag" class in the scenario above, then how would I do that?

**Comment by ajcvickers** [comment]
@slavanap There isn't a simple answer to that. The only way to do it reliably is to not use the EF model as the source for entity types, but rather to use your own mechanism of identifying the correct types--for example, by putting an attribute on them or implementing a marker interface and then scanning the assembly.

**Comment by slavanap** [comment]
@ajcvickers have you just suggested to copy logic that DbContext and DbContext.OnModelCreating contains? In the result it'll be a spaghetti code that, the copy of logic in 2 different places to support. Am I getting you right?

**Comment by ajcvickers** [comment]
@slavanap No, I'm not suggesting you do this because the EF code doesn't do what you want. I'm suggesting that if you need a way to identify entity types accurately before the model is built, then you will need to use your own code to do that, since EF Core doesn't. EF Core's list of entity types is only accurate _after_ the model is fully built and finalized.

**Comment by slavanap** [comment]
@ajcvickers 
> EF Core's list of entity types is only accurate after the model is fully built and finalized.

When this happens? At the end of OnModelCreating function? Is it user controllable? If not, then such statement doesn't help to solve for problem of model analysis, I'm sorry.

Back to entities list, if that Entity with Dictionary CLR type had some anonymous, empty, autogenerated or MyFunc related name, it'll be better in any case than it is now.

**Comment by ajcvickers** [comment]
@slavanap It happens when `IMutableModel.FinalizeModel` is called. You can take over model building by creating your own `DbModelBuilder`, but this won't help much because once the model is finalized it can't be changed. And no, this doesn't help model analysis, because this kind of model analysis is not possible to do robustly while the model is being created.

**Comment by slavanap** [comment]
@ajcvickers am I getting you right that you don't consider a bug 
* the entity added to `modelBuilder.Model.GetEntityTypes()` for a context user function has unrelated `Name` value
* an attempt to call `modelBuilder.Entity(entity.ClrType)` for such an `entity` in the list throws an exception because `Dictionary<string, object>` is unsupported entity type although it's assigned to `entity.ClrType`.

@ajcvickers for further reference please confirm the 2 bullets above before closing the ticket.

cc @roji

**Comment by ajcvickers** [comment]
@slavanap Yes, neither of those things seem like bugs.
