### ISSUE TITLE
Implement the new OpenTelemetry Metrics API

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25880]
This is a standardized API which replaces event counters, https://devblogs.microsoft.com/dotnet/new-dotnet-6-apis-driven-by-the-developer-community/#new-metrics-api

**Comment by noahfalk** [comment]
These APIs also have walkthroughts in the docs here: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics. I think this gives more depth than any of the announcement blurbs.

**Comment by roji** [comment]
Thanks @noahfalk, I'll definitely hope we'll get around to this soon.
