### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.1.0.0'

### ISSUE THREAD

**Issue by iampratishtha** [dotnet/efcore#25885]
Issue: Whenever I run the following scaffolding command after the build succeeds, it gives an error.
"dotnet ef dbcontext scaffold "Database=mydb; server=myserver; UID=user; PWD=password" OneDB.EntityFramework.Core -o Models --project MyApp.csproj -v" 

```
Error:
System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language, String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```
D:>dotnet ef core --version
Entity Framework Core .NET Command-line Tools
5.0.5

D:>dotnet --version
3.1.401

**Comment by ErikEJ** [comment]
Please share your csproj file contents.

**Comment by iampratishtha** [comment]
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
	<Reference Include="Informix.Net.Core">
      <HintPath>$(HOME)\bin\Net.Core.dll</HintPath>
    </Reference>
	<Reference Include="OneDB.EntityFramework.Core">
	  <HintPath>$(HOME)\bin\EntityFramework.Core.dll</HintPath>
	</Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.1.20451.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="5.0.0-rc.1.20451.14" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0-rc.1.20451.14" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0-rc.1.20451.14" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0-rc.1.20451.14" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0-rc.1.20451.14" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="5.0.0-rc.1.20451.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-rc.1.20451.13" />
  </ItemGroup>
</Project>

**Comment by ErikEJ** [comment]
Why are you running 5.0 RC1?

And the first itemgroup look very weird.

What happens if you remove it?

**Comment by ajcvickers** [comment]
@iampratishtha To echo what @ErikEJ said, you need to update to a GA/RTM release. Preview and RC releases are not supported after the corresponding GA release has been made.

**Comment by AraHaan** [comment]
I have a similar issue, however it is from it not being able to load ``System.Runtime v6.0.0`` when trying to scaffold.
