### ISSUE TITLE
Avoid generating proxies when they're not needed

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25892]
Proxy generation is a very heavy process perf-wise, and we may be doing it in cases where we don't have to (came out of investigating the model in #20135).

* For lazy loading proxies, a type without any virtual methods shouldn't require proxies
* For change tracking proxies, we currently set up all the entity types in the model (and throw if any type is sealed). We could have some sort of type-by-type opt-in/opt-out.

/cc @ajcvickers

**Comment by ajcvickers** [comment]
Partially covered by #10787

Note that mixing notification entities with non-notification entities tends to be a pit of failure (based on EF6 experience) which is why we do not allow it in EF Core.

**Comment by ajcvickers** [comment]
Note from triage: 

* Selecting lazy-loading proxy types covered by #10787. Types with no relationships can the be excluded.
* For change-tracking proxies, we will keep things as they are now.
