### ISSUE TITLE
Conventions: Add public model building API

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#2589]
The InternalModelBuilder has several problems:
- It is a leaky abstraction, as it exposes ConfigurationSource and requires the users to keep track of the last returned builder that contains the up-to-date configuration.
- Its shape resembles ModelBuilder, but the behavior is different, sometimes in non-obvious ways
- The API is inconsistent in parameters as it can take string ids, Model objects or InternalModelBuilder objects.

**Comment by AndriySvyryd** [comment]
One approach that could solve these issues is the following:
Make `InternalModelBuilder` the only source-of-truth while the model is being built.
Make all users go through one of the interfaces that the `InternalModelBuilder` would implement:
* IMutableModel, would have mostly the same shape as `Model` currently has, but using strings for element identification (e.g. `AddKey(IEnumerable<string>)`). Can be dropped down to from `ModelBuilder`. 
* IConventionModel and IDataAnnotationModel, would have a similar shape to IMutableModel, while conveying that configuration is not assured (e.g. `TryAddKey(IEnumerable<string>)`, `TrySetRequired(bool)`). 
* All these interfaces would derive from IModel and IAccessor<InternalModelBuilder>
* Add 3 more values to ConfigurationSource: `WhatIfExplicit`, `WhatIfDataAnnotations`, `WahttIfConvention`. When used they would not perform any changes, but would return the same success result as the equivalent 'real' sources.
* When the model is built and the ModelValidator ran successfully it can be converted to ReadOnlyModel, that only implements IModel and is optimized for reading speed and low memory consumption.

**Comment by AndriySvyryd** [comment]
Marking for retriage.
I think this should be pri0 since it would introduce a big API surface and early release can generate helpful feedback.
Also it will make other changes and fixes in the builders easier as there would be less code duplication.

**Comment by rowanmiller** [comment]
@AndriySvyryd can you bring a proposal to the design meeting... or a corridor meeting in our corridor-less open space

**Comment by AndriySvyryd** [comment]
We've discussed this and decided to keep the model and the model building logic separate. To improve perf `ConfigurationSource` will be stored as part of the model, see #3476

This issue is now only for adding public model building API for conventions.

**Comment by rowanmiller** [comment]
Custom conventions is tracked by https://github.com/aspnet/EntityFramework/issues/214, so closing this out.
