### ISSUE TITLE
Reference to type 'EntityOptionsBuilder' claims it is defined in 'EntityFramework.Core', but it could not be found

### ISSUE THREAD

**Issue by angelcalvasp** [dotnet/efcore#2591]
UseSqlServer seems to be missing when I use

optionsBuilder.UseSqlServer(configuration.Get("Data:DefaultConnection:ConnectionString"));

on my overriden OnConfiguring

revelant c#

``` c#
public class CRMDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, int>
    {
        public CRMDbContext()
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            var configuration = new Configuration()
                .AddJsonFile("config.json")
                .AddEnvironmentVariables();

            // Visual Studio 2015 | Use the LocalDb 12 instance created by Visual Studio
            optionsBuilder.UseSqlServer(configuration.Get("Data:DefaultConnection:ConnectionString"));

        }

}
```

heres my project.json

``` json
"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.Framework.Configuration.Json": "1.0.0-*",
    "Microsoft.AspNet.Authentication": "1.0.0-*",
    "Microsoft.AspNet.Authentication.OAuthBearer": "1.0.0-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-*",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-*",
    "EntityFramework.SqlServer": "7.0.0-*",
    "EntityFramework.Commands": "7.0.0-*"
  },
```

**Comment by natemcmaster** [comment]
What build is installed? `dnu list` will show you which what is installed. Look for "EntityFramework.SqlServer 7.0.0-beta#-#####"

**Comment by angelcalvasp** [comment]
* EntityFramework.SqlServer 7.0.0-beta5
thats what the list shows

**Comment by natemcmaster** [comment]
In beta5, it is `EntityOptionsBuilder`. In beta4 and the nightly builds, it is `DbContextOptionsBuilder`. 

Try changing to `protected override void OnConfiguring(EntityOptionsBuilder optionsBuilder)` as a temporary workaround until beta6 rolls.

**Comment by angelcalvasp** [comment]
I changed it to Beta 5 and Beta 6 both cases made that error go away but now on the dependency injection


An exception of type 'System.MissingMethodException' occurred in WebApplication1 but was not handled in user code

on the line where I set up the EF service

```c#
services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<CRMDbContext>();
```
Additional information: Method not found: 'Boolean Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd(Microsoft.Framework.DependencyInjection.IServiceCollection, System.Collections.Generic.IEnumerable`1<Microsoft.Framework.DependencyInjection.ServiceDescriptor>)'.
