### ISSUE TITLE
Comparison with TimeSpanToStringConverter doesn't work correctly for 1 day+ TimeSpans

### ISSUE THREAD

**Issue by danzel** [dotnet/efcore#25920]
When a TimeSpan property is configured to be converted using `TimeSpanToStringConverter` the resulting string only includes days if needed, so the comparison doesn't work correctly for TimeSpans less than a day and TimeSpans more than a day:

`'1.00:00:00' < '23:00:00' = true`

https://github.com/dotnet/efcore/blob/v5.0.10/src/EFCore/Storage/ValueConversion/TimeSpanToStringConverter.cs
https://github.com/dotnet/efcore/blob/v5.0.10/src/EFCore/Storage/ValueConversion/Internal/StringTimeSpanConverter.cs

This reproduces easy with sqlite, but should also occur with other sql providers.
We ran in to this in our tests which use sqlite in memory.

I don't expect this is easily fixable, but may be worth documenting [here(?)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.timespantostringconverter?view=efcore-5.0)

### Code
```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace EfCoreBug
{
	class Program
	{
		static void Main(string[] args)
		{
			string connectionString = "Data Source=" + Guid.NewGuid().ToString() + ";Mode=Memory;Cache=Shared";
			var options = new DbContextOptionsBuilder<MyContext>()
				//.UseInMemoryDatabase("name")
				.UseSqlite(connectionString)
				.Options;

			var Connection = new SqliteConnection(connectionString);
			Connection.Open();

			using var context  = new MyContext(options);
			context.Database.EnsureCreated();

			context.Add(new MyEntity { Time = TimeSpan.FromDays(1) });
			context.SaveChanges();

			Console.WriteLine("How many Total? " + context.MyEntities.Count());
			Console.WriteLine("How many < 23 hours? " + context.MyEntities.Count(x => x.Time < TimeSpan.FromHours(23)));
			Console.WriteLine("Query String: " + context.MyEntities.Where(x => x.Time < TimeSpan.FromHours(23)).ToQueryString());
		}
	}

	class MyEntity
	{
		[Key]
		public Guid Id { get; set; }

		public TimeSpan Time { get; set; }
	}

	class MyContext : DbContext
	{
		public DbSet<MyEntity> MyEntities { get; set; }

		public MyContext(DbContextOptions<MyContext> options) : base(options)
		{

		}

		/// <inheritdoc />
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			modelBuilder.Entity<MyEntity>().Property(x => x.Time).HasConversion(new TimeSpanToStringConverter());
			//modelBuilder.Entity<MyEntity>().Property(x => x.Time).HasConversion(new TimeSpanToTicksConverter());
		}
	}
}

```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5.0.9
Operating system: Windows 10
IDE: Visual Studio 2019 16.11

Thanks!

**Comment by ajcvickers** [comment]
Note for triage: manifestation of #10434

**Comment by roji** [comment]
Can we fix this by switching the TimeSpan formatting from `c` to [`G`](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings#the-general-long-g-format-specifier)? That seems to always include days...

**Comment by ajcvickers** [comment]
Discussed in triage and decided not to change the format, since it would be breaking. A custom converter can always be used to generate strings with a different format.
