### ISSUE TITLE
SQLite Migration: Disable foreign key enforcement

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2592]
This is required by both #329 &  #1127.

We may be able to do this by adding an operation like the following to the beginning of the migration.

``` C#
migrationBuilder.Sql("PRAGMA FOREIGN_KEYS=OFF;", suppressTransaction: true);
```

If not, we'll have to add a hook for providers to manipulate the connection before migrating.

**Comment by rowanmiller** [comment]
We'll deal with this as an implementation detail of the other scenarios where we may need it.
