### ISSUE TITLE
Migrations: Update discriminator values when changed

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2593]
For discriminator values (not expressions), we could send an operation like the following when it changes.

``` SQL
UPDATE Shape SET Discriminator = 'Rectangle' WHERE Discriminator = 'Square';
```

**Comment by bricelam** [comment]
Marking for re-triage since it seems like a bug that we ignore changes here.

**Comment by rowanmiller** [comment]
We haven't seen folks ask for this, we can reconsider if we get requets
