### ISSUE TITLE
Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1[System.Boolean]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Object]'

### ISSUE THREAD

**Issue by emaborsa** [dotnet/efcore#25958]
EF Core version: 5.0.9
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 5.0.7
Target framework: .NET 5.0
Operating system: Windows 10
IDE:  Visual Studio 2019

I am working with Dynamic Linq, when working with strings I have no problems, when dealing with bool's, i got the following error:

##### Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1[System.Boolean]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Object]'

For testing purpuses I wrote three cases:

            IQueryable iQueryable = dbContext.MyEntity.AsQueryable();
            var one = iQueryable.Select("MyBooleanField").Distinct();
            var two = iQueryable.Select("MyBooleanField").Distinct().Cast<object>();
            var three = iQueryable.Select("MyBooleanField").Distinct().Cast<bool>();

`one` and `three` work fine, `two` leads to the above exception.
What's the problem?
I made a sample: [EF-Test.zip](https://github.com/dotnet/efcore/files/7136646/EF-Test.zip)

**Comment by roji** [comment]
@emaborsa it's not quite clear what you're doing here (e.g. where does the Select overload with a string argument come from?). Can you please submit a runnable code sample rather than a fragment?

**Comment by emaborsa** [comment]
@roji Actually I am not doing that much. I added the missing part to the question `IQueryable iQueryable = dbContext.MyEntity.AsQueryable();`.

**Comment by ajcvickers** [comment]
@emaborsa As @roji said, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by emaborsa** [comment]
I added a sample project.

**Comment by ajcvickers** [comment]
@emaborsa This should be reported to the maintainers of the [System.Linq.Dynamic.Core](https://www.nuget.org/packages/System.Linq.Dynamic.Core/) package.
