### ISSUE TITLE
Connection Resilience with Cross Context Transaction while using same sql connection.

### ISSUE THREAD

**Issue by logvinay** [dotnet/efcore#25987]
All these activities are done in Asp.Net core 3.1 with the Latest EF core packages.

Facing issues getting errors most of the Time.
**"An exception has been raised that is likely due to a transient failure. Consider enabling transient error resilienct by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call".**

I went through the following links in docs.
https://docs.microsoft.com/en-us/ef/core/saving/transactions#share-connection-and-transaction
https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions

My implementation is something like 

```
using (SqlConnection conn = new SqlConnection(option)) {

var options = new DbContextOptionsBuilder<BloggingContext>()
    .UseSqlServer(conn )
    .Options;
    
    using var db= new BloggingContext(options);
    
    var strategy = db.Database.CreateExecutionStrategy();

    strategy.Execute(
        () =>
        {
                 using (var transaction = db.Database.BeginTransaction())
                {

                    using (var context1 = new BloggingContext(options))
                    {
                     context1.Database.UseTransaction(transaction.GetDbTransaction());
                      context1.Blogs.Add(new Blog { Url = "http://blogs.msdn.com/dotnet" });
                      context1.SaveChanges();
                     }

                    using (var context2 = new BloggingContext(options))
                    {
                       context2.Database.UseTransaction(transaction.GetDbTransaction());
                       
                      var blogs = context2.Blogs
                     .OrderBy(b => b.Url)
                     .ToList();
                     }
                    using (var context3 = new BloggingContext(options))
                    {
                     context3.Database.UseTransaction(transaction.GetDbTransaction());
                      context3.Blogs.Add(new Blog { Url = "https://docs.microsoft.com/en-us/" });
                      context3.SaveChanges();
                     }
                }
           });
        }
```
As per both links in the document I see this is the way we use connection resiliency with the cross-context transactions.

I don't see any great example with both of'em Connection Resilience with Cross Context Transaction.

Not sure what is missing and what is wrong here. In the local environment, it works well enough. In the production environment multiple times it gives quoted exceptions.

If any resource is available on Microsoft Docs that would help and we can use it as Best practices while using both of these areas with EF core would be a great and helpful resource for most of us.

Thanks in advance for helping out here :)

**Comment by stevendarby** [comment]
In the code given, no call is made to `EnableRetryOnFailure()` when configuring the DbContextOptions. Without this I believe the execution strategy is a non-retrying one, so you still get the exception advising you to call `EnableRetryOnFailure()`

**Comment by logvinay** [comment]
Yeah, I believe the same, 
But if you go through 
https://docs.microsoft.com/en-us/ef/core/saving/transactions#share-connection-and-transaction
here we have no sample where options have EnableRetryOnFailure.

Confusing part with Transaction Could we use option with EnableRetryOnFailure then each of query become a retriable unit. Which could cause InvalidOperationException for Transaction?

And If we use this option with EnableRetryOnFailure for creating an Execution strategy same options.
Q: Could we use the options for Contexts and Transaction within the delegate action of Execution Strategy?

**Comment by AndriySvyryd** [comment]
https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency shows how to add `EnableRetryOnFailure` at the very beginning.

When creating a transaction across different contexts you don't need to call `EnableRetryOnFailure` or `context.Database.CreateExecutionStrategy()`, you can create the needed strategy directly: `new SqlServerRetryingExecutionStrategy(context)`
