### ISSUE TITLE
Indicate in OnConfigure if the DbContext if a Migration is being created.

### ISSUE THREAD

**Issue by DizzyDeveloper** [dotnet/efcore#25981]
This is probably more of a heavy nice-to-have.

It would be nice if as part of the overridable  `OnConfiguring` method it could indicate that the current instance of the DbContext has been initialized as the migration process. Particularly in respect to a DbContext instance is being used to generate a new migration.
Maybe something similar to the `IsConfigured` boolean flag? Or maybe just a state enum of sorts.

The reason for this being, is that a connection string isn't required when generating a migration script. i.e. For postgres simply having the an empty `UseNpsql()` is enough for ef to generate a migration. So the "migration being created" flag would allow me to or not "throw" an error if an connection string is to be expected.

**Comment by AndriySvyryd** [comment]
You could use [IDesignTimeDbContextFactory<TContext>](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-a-design-time-factory) to accomplish this
