### ISSUE TITLE
Nullable references not supported by GetColumnType/GetDefaultValueSql

### ISSUE THREAD

**Issue by SetTrend** [dotnet/efcore#25991]
## File a bug

In EFCore source code's `RelationalPropertyExtensions` method extension class, many return values are declared not taking nullable reference types into account in their return value:

```c#
...
public static string GetColumnType([NotNullAttribute] this IProperty property);
...
public static string GetDefaultValueSql([NotNullAttribute] this IProperty property);
...
```

Both should return `string?` instead:

```c#
...
public static string? GetColumnType([NotNullAttribute] this IProperty property);
...
public static string? GetDefaultValueSql([NotNullAttribute] this IProperty property);
...
```

### Include provider and version information

EF Core version: `5.0.9`
Target framework: `.NET 5.0`
Operating system: `Windows 10x64 20H2`
IDE: `Visual Studio 2019 16.11.2`

**Comment by roji** [comment]
EF Core 5.0 has not been annotated for nullable reference types, but 6.0 has been; I've taken a quick look, and the annotations for the above methods seems correct there. Can you give the latest 6.0.0 preview a try and report if you see anything that looks incorrect?

**Comment by SetTrend** [comment]
Ah, I see ... Fine ... if it's in v6 then that'll be perfectly sufficient.

Closing this issue for now.
