### ISSUE TITLE
EntityFrameworkCore 5.0.9 Extension Method with eager loading Include does not work without Load();

### ISSUE THREAD

**Issue by Ogglas** [dotnet/efcore#26006]
I have the following code:

    public static class IntegrationServiceExtensions
    {
        public static IQueryable<T> LearningObjectContainerIncludeNestedProperties<T>(this IQueryable<T> query) where T : LearningObjectContainer
        {
            query.Include(x => x.Bases)
                .Include(x => x.LearningObjectives).ThenInclude(x => x.Classifications)
                .Include(x => x.Classifications)
                .Include(x => x.ContainerPropertyImplementations);

            return query;
        }
    }

    //Include does not work
	public async Task<LearningObjectContainer> GetLearningObjectContainer(int id)
    {
        var query = _applicationDbContext.LearningObjectContainers.LearningObjectContainerIncludeNestedProperties();

        var learningObjectContainer = await query.FirstOrDefaultAsync(x => x.Id == id);

        return learningObjectContainer;
    }
 
    //Include works
	public async Task<LearningObjectContainer> GetLearningObjectContainer(int id)
    {
        var query = _applicationDbContext.LearningObjectContainers
            .Include(x => x.Bases)
            .Include(x => x.LearningObjectives).ThenInclude(x => x.Classifications)
            .Include(x => x.Classifications)
            .Include(x => x.ContainerPropertyImplementations);

        var learningObjectContainer = await query.FirstOrDefaultAsync(x => x.Id == id);

        return learningObjectContainer;
    }

[![enter image description here][1]][1]

[![enter image description here][2]][2]

Working:

[![enter image description here][3]][3]

[![enter image description here][4]][4]

It does not matter if I run the code asynchronous or synchronous.

The only way I made the extension method work is by using `.Load();` (explicit loading).

https://docs.microsoft.com/en-us/ef/core/querying/related-data/explicit

    public static class IntegrationServiceExtensions
    {
        public static IQueryable<T> LearningObjectContainerIncludeNestedProperties<T>(this IQueryable<T> query) where T : LearningObjectContainer
        {
            query.Include(x => x.Bases).Load();
            query.Include(x => x.LearningObjectives).ThenInclude(x => x.Classifications).Load();
            query.Include(x => x.Classifications).Load();
            query.Include(x => x.ContainerPropertyImplementations).Load();

            return query;
        }
    }
	
	public async Task<LearningObjectContainer> GetLearningObjectContainer(int id)
    {
        var query = _applicationDbContext.LearningObjectContainers.LearningObjectContainerIncludeNestedProperties();

        var learningObjectContainer = await query.FirstOrDefaultAsync(x => x.Id == id);

        return learningObjectContainer;
    }

[![enter image description here][5]][5]

Why can I not use eager loading when using an extension method?

https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager

I tried to use split queries with eager loading but it did not work.

    public static IQueryable<T> LearningObjectContainerIncludeNestedProperties<T>(this IQueryable<T> query) where T : LearningObjectContainer
    {
        query.Include(x => x.Bases)
            .Include(x => x.LearningObjectives).ThenInclude(x => x.Classifications)
            .Include(x => x.Classifications)
            .Include(x => x.ContainerPropertyImplementations)
            .AsSplitQuery();

        return query;
    }

https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries

  [1]: https://i.stack.imgur.com/8aV3F.png
  [2]: https://i.stack.imgur.com/j8RtS.png
  [3]: https://i.stack.imgur.com/1Gy1x.png
  [4]: https://i.stack.imgur.com/Af07O.png
  [5]: https://i.stack.imgur.com/yJVgz.png

### Include provider and version information

EF Core version: 5.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.11.1

**Comment by smitpatel** [comment]
```C#
    public static IQueryable<T> LearningObjectContainerIncludeNestedProperties<T>(this IQueryable<T> query) where T : LearningObjectContainer
    {
        query.Include(x => x.Bases)
            .Include(x => x.LearningObjectives).ThenInclude(x => x.Classifications)
            .Include(x => x.Classifications)
            .Include(x => x.ContainerPropertyImplementations);

        return query;
    }
```

Calling any method on Queryable (in correctly designed API), generates new expression tree with called methods. That means the queryable object generated by the method (Include) is different from the one passed in. Above method body is incorrect. You are creating new expression tree by calling Include but you are sending back the original queryable (which doesn't have include calls) back so there are no includes. Update the method body to following and it will work correctly.

```C#
    public static IQueryable<T> LearningObjectContainerIncludeNestedProperties<T>(this IQueryable<T> query) where T : LearningObjectContainer
    {
        return query.Include(x => x.Bases)
            .Include(x => x.LearningObjectives).ThenInclude(x => x.Classifications)
            .Include(x => x.Classifications)
            .Include(x => x.ContainerPropertyImplementations);
    }
```

**Comment by Ogglas** [comment]
Totally missed that, thank you @smitpatel!
