### ISSUE TITLE
how to replace SqlServer SqlServerUpdateSqlGenerator with my own custom implementation?

### ISSUE THREAD

**Issue by egarim** [dotnet/efcore#26019]
Hi, I would like to Replace SqlServer SqlServerUpdateSqlGenerator (https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs) with my own custom implementation but I don't know when is the right time to replace the registration with the dependency service?

**Comment by AndriySvyryd** [comment]
You would need to call `UseInternalServiceProvider`:

```C#
            var serviceProvider = new ServiceCollection()
                .AddSingleton<ISqlServerUpdateSqlGenerator, MySqlServerUpdateSqlGenerator>()
                .AddEntityFrameworkSqlServer()
                .BuildServiceProvider();

            optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["BigDataDB"].ConnectionString)
                .UseInternalServiceProvider(serviceProvider);
```

Just make sure to build/store the service provider outside of `OnConfiguring`/`AddDbContext` to avoid extra allocations
