### ISSUE TITLE
QuerySplittingBehavior warning

### ISSUE THREAD

**Issue by brockallen** [dotnet/efcore#26018]
We build a library that makes use of `.Include` queries and we rely upon the default behavior for split vs single query semantics. We rely upon the default behavior, because a user of our library can change the default via `.UseQuerySplittingBehavior` if they decide they want a different behavior for our queries.

The issue is that with all of the defaults, we get this warning:

```
Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.
```

These warnings show up in production server logs and the customer thinks there's a problem, but there is no problem. This confuses customers and makes them think there's a problem with the data access layer.

Only show these warnings in a debug/non-prod release of the host.

**Comment by smitpatel** [comment]
User should configure the default query splitting behavior regardless of it being prod/dev and it should be a must in prod. I don't see why the warning is incorrect in prod.

**Comment by brockallen** [comment]
> User should configure the default query splitting behavior regardless of it being prod/dev and it should be a must in prod. I don't see why the warning is incorrect in prod.

Then why not throw instead of just emit a warning? The default behavior seems to imply that the default behavior is an acceptable choice.

**Comment by ajcvickers** [comment]
@brockallen Can you not disable the warning in `OnConfiguring` if you don't want it?

**Comment by brockallen** [comment]
Given our architecture, we don't know what DB provider is being used. We give our customers a callback and they configure it. Here's a link to a sample host that uses our EF library:

https://github.com/DuendeSoftware/IdentityServer/blob/main/hosts/EntityFramework/Startup.cs#L35

As you can see it's configured to suppress the warning, but that's just our internal sample. We don't control how our customers write their Startup code, thus this issue.

**Comment by ajcvickers** [comment]
@brockallen But do you not own the DbContext type? You can use OnConfiguring in there, even if there is additional configuration provided through DbContextOptions to the constructor.

**Comment by brockallen** [comment]
So you're suggesting we configure the logs, or the default behavior?

If we were to configure the default behavior, could the code in Startup then change/control that behavior?

**Comment by brockallen** [comment]
Ah, I found the `IsFrozen` property on the options builder that seems to be what I need.

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    base.OnConfiguring(optionsBuilder);
    if (!optionsBuilder.Options.IsFrozen)
    {
        optionsBuilder.ConfigureWarnings(w => w.Ignore(new EventId[] { RelationalEventId.MultipleCollectionIncludeWarning }));
    }
}
