### ISSUE TITLE
'System.MissingMethodException' 

### ISSUE THREAD

**Issue by angelcalvasp** [dotnet/efcore#2603]
An exception of type 'System.MissingMethodException' occurred in WebApplication1 but was not handled in user code

on the line where I set up the EF service

services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<CRMDbContext>();

{"Method not found: 'Boolean Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd(Microsoft.Framework.DependencyInjection.IServiceCollection, System.Collections.Generic.IEnumerable`1)'."}

Additional information: Method not found: 'Boolean Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd(Microsoft.Framework.DependencyInjection.IServiceCollection, System.Collections.Generic.IEnumerable`1)'.

think I will make a new Issue

**Comment by natemcmaster** [comment]
Tell us more please. What version of EF are you using? (`dnu list`) What is your `project.json` file look like? 
It is most helpful if you can create a sample project that reproduces the issue. Post a link to the code here.

**Comment by mmelosan** [comment]
[Target framework DNX,Version=v4.5.1 (dnx451)]

Framework references:
  framework/fx/Microsoft.CSharp 4.0.0.0
  framework/fx/mscorlib 4.0.0.0
  framework/fx/System 4.0.0.0
  framework/fx/System.Collections 4.0.0.0
  framework/fx/System.Collections.Concurrent 4.0.0.0
  framework/fx/System.ComponentModel.DataAnnotations 4.0.0.0
  framework/fx/System.Core 4.0.0.0
  framework/fx/System.Data 4.0.0.0
  framework/fx/System.Diagnostics.Debug 4.0.0.0
  framework/fx/System.Diagnostics.Tools 4.0.0.0
  framework/fx/System.Globalization 4.0.0.0
  framework/fx/System.IO 4.0.0.0
  framework/fx/System.Linq 4.0.0.0
  framework/fx/System.Linq.Expressions 4.0.0.0
  framework/fx/System.Linq.Queryable 4.0.0.0
  framework/fx/System.ObjectModel 4.0.0.0
  framework/fx/System.Reflection 4.0.0.0
  framework/fx/System.Reflection.Extensions 4.0.0.0
  framework/fx/System.Resources.ResourceManager 4.0.0.0
  framework/fx/System.Runtime 4.0.10.0
  framework/fx/System.Runtime.Extensions 4.0.0.0
  framework/fx/System.Security 4.0.0.0
  framework/fx/System.Text.Encoding 4.0.0.0
  framework/fx/System.Threading 4.0.0.0
  framework/fx/System.Threading.Tasks 4.0.0.0
  framework/fx/System.Transactions 4.0.0.0
  framework/fx/System.Xml 4.0.0.0
  framework/fx/System.Xml.Linq 4.0.0.0

Package references:
* EntityFramework.Commands 7.0.0-beta5
  EntityFramework.Core 7.0.0-beta5
  EntityFramework.Relational 7.0.0-beta5
  EntityFramework.Relational.Design 7.0.0-beta5
* EntityFramework.SqlServer 7.0.0-beta5
  Ix-Async 1.2.3
* Kestrel 1.0.0-beta7-12006
  Microsoft.AspNet.Antiforgery 1.0.0-beta7-10173
  Microsoft.AspNet.Authorization 1.0.0-beta7-12715
  Microsoft.AspNet.Cors.Core 1.0.0-beta7-10695
  Microsoft.AspNet.Cryptography.Internal 1.0.0-beta7-11641
  Microsoft.AspNet.DataProtection 1.0.0-beta7-11641
  Microsoft.AspNet.DataProtection.Abstractions 1.0.0-beta7-11641
* Microsoft.AspNet.Diagnostics 1.0.0-beta7-13424
  Microsoft.AspNet.Diagnostics.Abstractions 1.0.0-beta7-13424
  Microsoft.AspNet.FileProviders.Abstractions 1.0.0-beta7-11642
  Microsoft.AspNet.FileProviders.Physical 1.0.0-beta7-11642
  Microsoft.AspNet.Hosting 1.0.0-beta7-12154
  Microsoft.AspNet.Hosting.Abstractions 1.0.0-beta7-12154
  Microsoft.AspNet.Hosting.Server.Abstractions 1.0.0-beta7-12154
  Microsoft.AspNet.Html.Abstractions 1.0.0-beta7-11746
  Microsoft.AspNet.Http 1.0.0-beta7-11746
  Microsoft.AspNet.Http.Abstractions 1.0.0-beta7-11746
  Microsoft.AspNet.Http.Extensions 1.0.0-beta7-11746
  Microsoft.AspNet.Http.Features 1.0.0-beta7-11746
  Microsoft.AspNet.JsonPatch 1.0.0-beta7-14327
  Microsoft.AspNet.Loader.IIS 1.0.0-beta7-12089
  Microsoft.AspNet.Loader.IIS.Interop 1.0.0-beta7-12089
  Microsoft.AspNet.Localization 1.0.0-beta7-10356
* Microsoft.AspNet.Mvc 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Abstractions 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.ApiExplorer 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Core 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Cors 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.DataAnnotations 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Formatters.Json 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Localization 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Razor 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Razor.Host 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.ViewFeatures 6.0.0-beta7-14327
  Microsoft.AspNet.PageExecutionInstrumentation.Interfaces 1.0.0-beta7-14327
  Microsoft.AspNet.Razor 4.0.0-beta7-11703
  Microsoft.AspNet.Razor.Runtime 4.0.0-beta7-11703
  Microsoft.AspNet.Routing 1.0.0-beta7-12016
* Microsoft.AspNet.Server.IIS 1.0.0-beta7-12089
  Microsoft.AspNet.Server.Kestrel 1.0.0-beta7-12006
* Microsoft.AspNet.Server.WebListener 1.0.0-beta7-12466
  Microsoft.AspNet.WebUtilities 1.0.0-beta7-11746
  Microsoft.CodeAnalysis.Analyzers 1.0.0
  Microsoft.CodeAnalysis.Common 1.0.0
  Microsoft.CodeAnalysis.CSharp 1.0.0
  Microsoft.Framework.Caching.Abstractions 1.0.0-beta7-11632
  Microsoft.Framework.Caching.Memory 1.0.0-beta7-11632
  Microsoft.Framework.Configuration 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.Abstractions 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.Binder 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.CommandLine 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.EnvironmentVariables 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.Ini 1.0.0-beta7-11604
  Microsoft.Framework.DependencyInjection 1.0.0-beta7-11603
  Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta7-11603
  Microsoft.Framework.Globalization.CultureInfoCache 1.0.0-beta7-10356
  Microsoft.Framework.Localization 1.0.0-beta7-10356
  Microsoft.Framework.Localization.Abstractions 1.0.0-beta7-10356
  Microsoft.Framework.Logging 1.0.0-beta7-11608
  Microsoft.Framework.Logging.Abstractions 1.0.0-beta7-11608
* Microsoft.Framework.Logging.Console 1.0.0-beta7-11608
  Microsoft.Framework.Notification 1.0.0-beta7-10241
  Microsoft.Framework.OptionsModel 1.0.0-beta7-11572
  Microsoft.Framework.Runtime.Abstractions 1.0.0-beta7-12255
  Microsoft.Framework.Runtime.Caching 1.0.0-beta5
  Microsoft.Framework.Runtime.Roslyn 1.0.0-beta5
  Microsoft.Framework.Runtime.Roslyn.Abstractions 1.0.0-beta7-12255
  Microsoft.Framework.Runtime.Roslyn.Common 1.0.0-beta7-12255
  Microsoft.Framework.WebEncoders 1.0.0-beta7-11746
  Microsoft.Framework.WebEncoders.Core 1.0.0-beta7-11746
  Microsoft.Net.Http.Headers 1.0.0-beta7-11746
  Microsoft.Net.Http.Server 1.0.0-beta7-12466
  Microsoft.Net.WebSockets 1.0.0-beta7-12466
  Newtonsoft.Json 6.0.6
  Remotion.Linq 2.0.0-alpha-002
  System.Collections.Immutable 1.1.36
  System.Reflection.Metadata 1.0.21


[Target framework DNXCore,Version=v5.0 (dnxcore50)]

Package references:
* EntityFramework.Commands 7.0.0-beta5
  EntityFramework.Core 7.0.0-beta5
  EntityFramework.Relational 7.0.0-beta5
  EntityFramework.Relational.Design 7.0.0-beta5
* EntityFramework.SqlServer 7.0.0-beta5
  Ix-Async 1.2.3
* Kestrel 1.0.0-beta7-12006
  Microsoft.AspNet.Antiforgery 1.0.0-beta7-10173
  Microsoft.AspNet.Authorization 1.0.0-beta7-12715
  Microsoft.AspNet.Cors.Core 1.0.0-beta7-10695
  Microsoft.AspNet.Cryptography.Internal 1.0.0-beta7-11641
  Microsoft.AspNet.DataProtection 1.0.0-beta7-11641
  Microsoft.AspNet.DataProtection.Abstractions 1.0.0-beta7-11641
* Microsoft.AspNet.Diagnostics 1.0.0-beta7-13424
  Microsoft.AspNet.Diagnostics.Abstractions 1.0.0-beta7-13424
  Microsoft.AspNet.FileProviders.Abstractions 1.0.0-beta7-11642
  Microsoft.AspNet.FileProviders.Physical 1.0.0-beta7-11642
  Microsoft.AspNet.Hosting 1.0.0-beta7-12154
  Microsoft.AspNet.Hosting.Abstractions 1.0.0-beta7-12154
  Microsoft.AspNet.Hosting.Server.Abstractions 1.0.0-beta7-12154
  Microsoft.AspNet.Html.Abstractions 1.0.0-beta7-11746
  Microsoft.AspNet.Http 1.0.0-beta7-11746
  Microsoft.AspNet.Http.Abstractions 1.0.0-beta7-11746
  Microsoft.AspNet.Http.Extensions 1.0.0-beta7-11746
  Microsoft.AspNet.Http.Features 1.0.0-beta7-11746
  Microsoft.AspNet.JsonPatch 1.0.0-beta7-14327
  Microsoft.AspNet.Loader.IIS 1.0.0-beta7-12089
  Microsoft.AspNet.Loader.IIS.Interop 1.0.0-beta7-12089
  Microsoft.AspNet.Localization 1.0.0-beta7-10356
* Microsoft.AspNet.Mvc 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Abstractions 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.ApiExplorer 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Core 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Cors 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.DataAnnotations 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Formatters.Json 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Localization 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Razor 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.Razor.Host 6.0.0-beta7-14327
  Microsoft.AspNet.Mvc.ViewFeatures 6.0.0-beta7-14327
  Microsoft.AspNet.PageExecutionInstrumentation.Interfaces 1.0.0-beta7-14327
  Microsoft.AspNet.Razor 4.0.0-beta7-11703
  Microsoft.AspNet.Razor.Runtime 4.0.0-beta7-11703
  Microsoft.AspNet.Routing 1.0.0-beta7-12016
* Microsoft.AspNet.Server.IIS 1.0.0-beta7-12089
  Microsoft.AspNet.Server.Kestrel 1.0.0-beta7-12006
* Microsoft.AspNet.Server.WebListener 1.0.0-beta7-12466
  Microsoft.AspNet.WebUtilities 1.0.0-beta7-11746
  Microsoft.CodeAnalysis.Analyzers 1.0.0
  Microsoft.CodeAnalysis.Common 1.0.0
  Microsoft.CodeAnalysis.CSharp 1.0.0
  Microsoft.CSharp 4.0.0-beta-23109
  Microsoft.Framework.Caching.Abstractions 1.0.0-beta7-11632
  Microsoft.Framework.Caching.Memory 1.0.0-beta7-11632
  Microsoft.Framework.Configuration 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.Abstractions 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.Binder 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.CommandLine 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.EnvironmentVariables 1.0.0-beta7-11604
  Microsoft.Framework.Configuration.Ini 1.0.0-beta7-11604
  Microsoft.Framework.DependencyInjection 1.0.0-beta7-11603
  Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta7-11603
  Microsoft.Framework.Globalization.CultureInfoCache 1.0.0-beta7-10356
  Microsoft.Framework.Localization 1.0.0-beta7-10356
  Microsoft.Framework.Localization.Abstractions 1.0.0-beta7-10356
  Microsoft.Framework.Logging 1.0.0-beta7-11608
  Microsoft.Framework.Logging.Abstractions 1.0.0-beta7-11608
* Microsoft.Framework.Logging.Console 1.0.0-beta7-11608
  Microsoft.Framework.Notification 1.0.0-beta7-10241
  Microsoft.Framework.OptionsModel 1.0.0-beta7-11572
  Microsoft.Framework.Runtime.Abstractions 1.0.0-beta7-12255
  Microsoft.Framework.Runtime.Caching 1.0.0-beta5
  Microsoft.Framework.Runtime.Roslyn 1.0.0-beta5
  Microsoft.Framework.Runtime.Roslyn.Abstractions 1.0.0-beta7-12255
  Microsoft.Framework.Runtime.Roslyn.Common 1.0.0-beta7-12255
  Microsoft.Framework.WebEncoders 1.0.0-beta7-11746
  Microsoft.Framework.WebEncoders.Core 1.0.0-beta7-11746
  Microsoft.Net.Http.Headers 1.0.0-beta7-11746
  Microsoft.Net.Http.Server 1.0.0-beta7-12466
  Microsoft.Net.WebSockets 1.0.0-beta7-12466
  Microsoft.Win32.Primitives 4.0.0-beta-23109
  Microsoft.Win32.Registry 4.0.0-beta-23109
  Newtonsoft.Json 6.0.6
  Remotion.Linq 2.0.0-alpha-002
  System.Collections 4.0.10-beta-23109
  System.Collections.Concurrent 4.0.10-beta-23109
  System.Collections.Immutable 1.1.36
  System.Collections.NonGeneric 4.0.0-beta-23109
  System.ComponentModel 4.0.0-beta-23109
  System.ComponentModel.Annotations 4.0.10-beta-23109
  System.ComponentModel.EventBasedAsync 4.0.10-beta-23109
  System.ComponentModel.Primitives 4.0.0-beta-23109
  System.ComponentModel.TypeConverter 4.0.0-beta-23109
  System.Console 4.0.0-beta-23109
  System.Data.Common 4.0.0-beta-23019
  System.Data.SqlClient 4.0.0-beta-23019
  System.Diagnostics.Contracts 4.0.0-beta-23109
  System.Diagnostics.Debug 4.0.10-beta-23109
  System.Diagnostics.Process 4.0.0-beta-23109
  System.Diagnostics.Tools 4.0.0-beta-23109
  System.Diagnostics.TraceSource 4.0.0-beta-23109
  System.Diagnostics.Tracing 4.0.20-beta-23109
  System.Dynamic.Runtime 4.0.0-beta-23109
  System.Globalization 4.0.10-beta-23109
  System.Globalization.Calendars 4.0.0-beta-23109
  System.Globalization.Extensions 4.0.0-beta-23109
  System.IO 4.0.10-beta-23109
  System.IO.FileSystem 4.0.0-beta-23109
  System.IO.FileSystem.Primitives 4.0.0-beta-23109
  System.IO.FileSystem.Watcher 4.0.0-beta-23109
  System.Linq 4.0.0-beta-23109
  System.Linq.Expressions 4.0.10-beta-23109
  System.Linq.Queryable 4.0.0-beta-23019
  System.Net.NetworkInformation 4.0.10-beta-23109
  System.Net.Primitives 4.0.10-beta-23109
  System.Net.WebSockets 4.0.0-beta-23109
  System.ObjectModel 4.0.10-beta-23109
  System.Private.Networking 4.0.0-beta-23109
  System.Private.Uri 4.0.0-beta-23109
  System.Reflection 4.0.10-beta-23109
  System.Reflection.Emit 4.0.0-beta-23109
  System.Reflection.Emit.ILGeneration 4.0.0-beta-23109
  System.Reflection.Emit.Lightweight 4.0.0-beta-23109
  System.Reflection.Extensions 4.0.0-beta-23109
  System.Reflection.Metadata 1.0.21
  System.Reflection.Primitives 4.0.0-beta-23109
  System.Reflection.TypeExtensions 4.0.0-beta-23109
  System.Resources.ReaderWriter 4.0.0-beta-23109
  System.Resources.ResourceManager 4.0.0-beta-23109
  System.Runtime 4.0.20-beta-23109
  System.Runtime.Extensions 4.0.10-beta-23109
  System.Runtime.Handles 4.0.0-beta-23109
  System.Runtime.InteropServices 4.0.20-beta-23109
  System.Runtime.Numerics 4.0.0-beta-23109
  System.Security.Claims 4.0.0-beta-23109
  System.Security.Cryptography.Encoding 4.0.0-beta-23109
  System.Security.Cryptography.Encryption 4.0.0-beta-23109
  System.Security.Cryptography.Encryption.Aes 4.0.0-beta-23109
  System.Security.Cryptography.Hashing 4.0.0-beta-23109
  System.Security.Cryptography.Hashing.Algorithms 4.0.0-beta-23109
  System.Security.Cryptography.RandomNumberGenerator 4.0.0-beta-23109
  System.Security.Cryptography.RSA 4.0.0-beta-23109
  System.Security.Cryptography.X509Certificates 4.0.0-beta-23109
  System.Security.Principal 4.0.0-beta-23109
  System.Security.Principal.Windows 4.0.0-beta-23109
  System.Security.SecureString 4.0.0-beta-23109
  System.Text.Encoding 4.0.10-beta-23109
  System.Text.Encoding.CodePages 4.0.0-beta-23019
  System.Text.Encoding.Extensions 4.0.10-beta-23109
  System.Text.RegularExpressions 4.0.10-beta-23109
  System.Threading 4.0.10-beta-23109
  System.Threading.Overlapped 4.0.0-beta-23109
  System.Threading.Tasks 4.0.10-beta-23109
  System.Threading.Tasks.Parallel 4.0.0-beta-23109
  System.Threading.Thread 4.0.0-beta-23109
  System.Threading.ThreadPool 4.0.10-beta-23109
  System.Threading.Timer 4.0.0-beta-23109
  System.Xml.ReaderWriter 4.0.10-beta-23109
  System.Xml.XDocument 4.0.10-beta-23109

**Comment by mmelosan** [comment]
I think i have the same issue, here is what my project.json looks like :
{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "exclude": [
        "wwwroot"
    ],
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {
        "Kestrel": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-*",
        "Microsoft.AspNet.Mvc": "6.0.0-*",
        "Microsoft.AspNet.Server.IIS": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "Microsoft.Framework.Logging.Console": "1.0.0-*",
        "EntityFramework.SqlServer": "7.0.0-beta5",
        "EntityFramework.Commands": "7.0.0-beta5"
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004",
        "ef": "EntityFramework.Commands"
    },
    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    }
}


and dnu list : 

{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "exclude": [
        "wwwroot"
    ],
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {
        "Kestrel": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-*",
        "Microsoft.AspNet.Mvc": "6.0.0-*",
        "Microsoft.AspNet.Server.IIS": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "Microsoft.Framework.Logging.Console": "1.0.0-*",
        "EntityFramework.SqlServer": "7.0.0-beta5",
        "EntityFramework.Commands": "7.0.0-beta5"
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004",
        "ef": "EntityFramework.Commands"
    },
    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    }
}

anyone can help, please let me now.

**Comment by BrennanConroy** [comment]
Try not to mix beta versions, you have beta5, beta6, and beta7 all in use in this application. Make it only 1 of those.

**Comment by cnblogs-dudu** [comment]
Same issue. I fixed it by upgrading Entity Framework to 7.0.0-beta6-13752.
```
"dependencies":{
    "EntityFramework.SqlServer": "7.0.0-beta6-13752",
    "EntityFramework.Commands": "7.0.0-beta6-13752"
}
```

**Comment by mmelosan** [comment]
How do I install "7.0.0-beta6-13752'? I only have "7.0.0-beta5" as the latest version

**Comment by cnblogs-dudu** [comment]
@mmelosan 
Change EntityFramework version to 7.0.0-beta6-13752 in project.json and run `dnu restore`.

**Comment by rowanmiller** [comment]
@mmelosan those ones with the timestamps come from our nightly build feed. If you standardize everything on Beta 5 it should work just fine. We will also be releasing Beta 6 shortly.

**Comment by shreedevishete** [comment]
Can anyone share the code , how to read Config.json in Beta7.
Looks like the package is changed
