### ISSUE TITLE
EF Core save built model for subsequent startup

### ISSUE THREAD

**Issue by Luigi6821** [dotnet/efcore#26038]
Hi,
I have read, at the following link 
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-5-compiled-models/,  
the proposed solution on version 6 for improving speed on startup of application that is using EF Core.
For what I understood the solution provide a mechanism using the EF Core tools Command Line Interface (CLI) to pre-build model during code compile time.
Unfortunately this solution, at least for what I understood, does not cover scenario where the final model depends from the database schema version to which the EF Core is connecting to, information available only during runtime.
This scenario frequently happens when application want support different database schema versions.
So what I propose is a solution, here below, that could expose some APIs for making persistent the compiled model:

```c#
string tenant = SomeServices.GetConfiguredTenant();
var connection = Microsoft.Data.SqlClient.SqlClientFactory.Instance.CreateConnection();
connection.ConnectionString = "<connection_string>"
			
ISerializedModel serializedModel; // Example of proposed solution:  have a serializable class of the compiled model
IModel model;

var optionBuilder = new DbContextOptionsBuilder();
optionBuilder.UseLazyLoadingProxies(true);
optionBuilder.UseLoggerFactory(loggerFactory);

if (!SomePersistentCacheService.Get($"{tenant}.model", out serializedModel))
{	
    connection.Open();
    string version;
     using (var cmd = connection.CreateCommand())
     {
	  cmd.CommandText = "SELECT VERSION FROM MYINSTALLEDSCHEMAVERSION";
	  version = (string) cmd.ExecuteScalar();
     }
     connection.Close();

     var modelBuilder = new ModelBuilder(SqlServerConventionSetBuilder.Build());

     modelBuilder.HasDefaultSchema("AMOS");
     modelBuilder.Entity<AMOS_ADDRESS>(b => b.ToTable("ADDRESS"));
     modelBuilder.Entity<AMOS_ADDRESS>().HasKey(e => e.ADDRESSID);
				
     // An example of a model change based on database schema version
     if (version >= "v.1.0")
	modelBuilder.Entity<AMOS_ADDRESS>().Property(e => e.CODE).HasColumnName("CODE");
     else
         modelBuilder.Entity<AMOS_ADDRESS>().Ignore(e => e.CODE);

      // Other entities and properties model setting

      model = modelBuilder.FinalizeModel();
      SomePersistentCacheService.GetOrCreate($"{tenant}.model", () => model.GetSerializedModel());
 }
 else
      model = serializedModel.GetModel();
			
 optionBuilder.UseModel(model);
 optionBuilder.UseSqlServer(connection);

 using (var dbContext = new DbContext(optionBuilder.Options))
  {
				
  }
```

Thanks in advance for the answer.
Regards
Luigi

**Comment by ajcvickers** [comment]
@Luigi6821 

With regard to:

> model depends from the database schema version to which the EF Core is connecting to, information available only during runtime.

Given EF Core doesn't natively support this, how do you currently handle it without compiled models? What does your current DbContext and its configuration look like?

**Comment by Luigi6821** [comment]
> @Luigi6821
> 
> With regard to:
> 
> > model depends from the database schema version to which the EF Core is connecting to, information available only during runtime.
> 
> Given EF Core doesn't natively support this, how do you currently handle it without compiled models? What does your current DbContext and its configuration look like?

Hi,
At the moment I am doing it using Entity Framework. I can produce a model, compile it, store it into persistent cache and re-utilize it on startup...

**Comment by ajcvickers** [comment]
@Luigi6821 Yes, please show what you are doing.

**Comment by Luigi6821** [comment]
> @Luigi6821 Yes, please show what you are doing.
[ConsoleApp4.zip](https://github.com/dotnet/efcore/files/7185956/ConsoleApp4.zip)
Hi,
Attached you can find a solution project containing 3 project: Model, EF and EF Core.
The Entity Framework project does what I want to achieve using EF Core.

Regards
Luigi

**Comment by ajcvickers** [comment]
@Luigi6821 There are a couple of things going on in your EF6 code. First, you are dynamically generating an EDMX model at runtime. This isn't really a compiled model in the sense that EF Core compiled models are. EF Core compiled models need to be pre-generated because they are then compiled into code by the C# compiler.

Second, if you want to load different compiled models depending on some runtime information, then this is possible with EF Core compiled models. The different compiled models will need to be generated into different folders and namespaces. Runtime information, such as the connection string, can then be examined and the correct model returned as needed. For example:

```C#
public static class RuntimeModelCache
{
    private static readonly ConcurrentDictionary<string, IModel> _runtimeModels
        = new();

    public static IModel GetOrCreateModel(string connectionString)
        => _runtimeModels.GetOrAdd(
            connectionString, cs =>
                {
                    if (cs.Contains("X"))
                    {
                        return BlogsContextModel1.Instance;
                    }

                    if (cs.Contains("Y"))
                    {
                        return BlogsContextModel2.Instance;
                    }

                    throw new InvalidOperationException("No appropriate compiled model found.");
                });
}
```

**Comment by Luigi6821** [comment]
> @Luigi6821 There are a couple of things going on in your EF6 code. First, you are dynamically generating an EDMX model at runtime. This isn't really a compiled model in the sense that EF Core compiled models are. EF Core compiled models need to be pre-generated because they are then compiled into code by the C# compiler.
> 
> Second, if you want to load different compiled models depending on some runtime information, then this is possible with EF Core compiled models. The different compiled models will need to be generated into different folders and namespaces. Runtime information, such as the connection string, can then be examined and the correct model returned as needed. For example:
> 
> ```cs
> public static class RuntimeModelCache
> {
>     private static readonly ConcurrentDictionary<string, IModel> _runtimeModels
>         = new();
> 
>     public static IModel GetOrCreateModel(string connectionString)
>         => _runtimeModels.GetOrAdd(
>             connectionString, cs =>
>                 {
>                     if (cs.Contains("X"))
>                     {
>                         return BlogsContextModel1.Instance;
>                     }
> 
>                     if (cs.Contains("Y"))
>                     {
>                         return BlogsContextModel2.Instance;
>                     }
> 
>                     throw new InvalidOperationException("No appropriate compiled model found.");
>                 });
> }
> ```

I got your point  but,  I guess, for having static instances of different models I have to compile a set of classes for each different scenarios we want to support which can be virtually not definable for all our customers. In the EF6 solution I simply generate model for customer that is using it.
 
Regards
Luigi

**Comment by roji** [comment]
@Luigi6821 note that, as @ajcvickers wrote above, EF Core's compiled models feature is very different from EF6 EDMX models. EF Core compiled models are by definition pregenerated (at design time or at CI time), which is why they can speed up program startup; dynamically-generated EF6 EDMX models simply do not do the same thing.

So I think the fundamental question is what exactly you're trying to achieve by using EF Core compiled models. If the idea is simply to have a multi-tenant model-per-customer, you probably don't need compiled models for that (and it may not be feasible to use them in that specific scenario).

**Comment by Luigi6821** [comment]
> @Luigi6821 note that, as @ajcvickers wrote above, EF Core's compiled models feature is very different from EF6 EDMX models. EF Core compiled models are by definition pregenerated (at design time or at CI time), which is why they can speed up program startup; dynamically-generated EF6 EDMX models simply do not do the same thing.
> 
> So I think the fundamental question is what exactly you're trying to achieve by using EF Core compiled models. If the idea is simply to have a multi-tenant model-per-customer, you probably don't need compiled models for that (and it may not be feasible to use them in that specific scenario).

The purpose is exactly to generate multi-tenant model per customer.  The EF6 solution, before the EDMX implementation, needed for each "run" more than one minute (we are talking about more than 600 entities), while now after the first run is ready in less then 2 secs. I remember that, till EF Core 3.1 version, compiling a model of more than 600 hundred table needed a lot of time.  The goal of this approach is that I don't need to provide different set of classes for each customer scenario but simply the service adapt itself basing on the tenant db I am going to connect to.
The current EF Core approach is good when you have a finite set of possible scenarios, in my opinion is not good when you don't know which is the scenario db and it saves time during development phase (at least in EF6 scenario).

**Comment by roji** [comment]
May I ask why you're using compiled models? How big is the model for a single tenant, and what kind of speedup are you seeing for it when using compiled models?

**Comment by Luigi6821** [comment]
> May I ask why you're using compiled models? How big is the model for a single tenant, and what kind of speedup are you seeing for it when using compiled models?

Hi please find here attached a project that in a simplified form explain what I want to achieve.
The tables I added are more than 600 but are still not the whole set.

Let me explain the very simple console project lines of code:

`
            var optionsBuilder = new DbContextOptionsBuilder();
            optionsBuilder.UseLazyLoadingProxies(true);
            double dbschemaVersion;

            // Get running schema version
            var connection = SqlClientFactory.Instance.CreateConnection();
            connection.ConnectionString = "Data source=localhost\\SQL2019;Initial catalog=amos10300;User ID=amos;Password=voyager";
            connection.Open();
            using (var command = connection.CreateCommand())
            {
                command.CommandText = "SELECT APPLICATIONVERSIONNO FROM AMOS.APPLICATIONINFO WHERE APPLICATIONID = 1";
                dbschemaVersion = double.Parse((string)command.ExecuteScalar());
            }

            // Build model
           //  Build a very large model. Ever time application starts it needs  about 22 seconds
           //  I understand that I can solve it with Precompiled model but in my case I can't know how many possible
           // db schema scenario I can meet. Also having a set of classes for each supported version (which anyway do
          //  not cover the whole requirements) is something that I want avoid.
            var s = Stopwatch.StartNew();
            var modelBuilder = ModelBuild.Build(dbschemaVersion);
            s.Stop();
            Console.WriteLine($"Build model : [{s.ElapsedMilliseconds}]");

            // Finalize model
            s.Restart();
            // My propose is to have a serializable version of IModel (from modelBuilder.FinalizeModel()).
            // Is it so bad?
            optionsBuilder.UseModel(modelBuilder.FinalizeModel());
            s.Stop();
            Console.WriteLine($"Finalize model : [{s.ElapsedMilliseconds}]");
y
            optionsBuilder.UseSqlServer(connection);
            var context = new DbContext(optionsBuilder.Options);
            
            // First query
            s.Restart();
            var cnt = context.Set<Accident>().Count();
            s.Stop();
            Console.WriteLine($"First query : [{s.ElapsedMilliseconds}]");
            Console.ReadLine();

`
Please have a look at code comments.

Thank you in advance
Regards
Luigi

**Comment by ajcvickers** [comment]
@Luigi6821 I think the thing that I don't fully understand is how the schema is changing but the mappings are not changing. Typically if the schema is different, then the mappings in code also need to be different. Can you give an example of where the schema changes but this does not require the mappings to change?

**Comment by Luigi6821** [comment]
I hope to clarify which is my scenario:
- Database schema is maintained using database tools and not using EF Core creation/migration tools.
- My purpose is to have a set of classes which always is the in memory representation of the last database schema version.
- Use EF/EFCore for database interaction as follows:
   - Map class/property to table/column if some conditions are satisfied. Database schema changes during time and some 
     columns could  be added/removed
   - Linq as query tool. Avoid to select all columns because of some of them could be not mapped, eventually mapping missing 
      properties with default values.
  - CRUD operations
- Write business code basing on the valid schema / mappings

I hope to have clarified but just a question for you basing on the actual implementation of the pre-compiled model.
Suppose my db consists of 2 tables and 2 columns for each of them,
The classes could be
class tableA
{
    ID;
    Code;
}

class tableB
{
   ID,
   Description;
   tableA Parent;
}

using ef core tools I can easily compile this model without problem.
Suppose then a new db schema release, tableB has a new column:
class tableBVx: tableB
{
   NewColumn;
}

or 

class tableBVx
{
   ID,
   Description;
   tableA Parent;
   NewColumn;
}

and of course tableA then command line for compiling it ... is it the way ?

Regards
Luigi

**Comment by ajcvickers** [comment]
@Luigi6821 So why cannot the compiled model be regenerated at the time that the `tableBVx` class is added?

**Comment by Luigi6821** [comment]
> @Luigi6821 So why cannot the compiled model be regenerated at the time that the `tableBVx` class is added?

Becasue I hould have a set of classes for each of the possible scenarios that are so many that makes it unmaintainable.

**Comment by ajcvickers** [comment]
@Luigi6821 How does the context optionally include those classes in the model? In other words, you're building the model from code before writing it out to an EDMX file. How does the model built from code either include or not include these optional classes?

**Comment by ajcvickers** [comment]
@Luigi6821 If you have a handful of different schema versions, then compiling a model for each of these seems reasonable. If you have dozens, then I agree it would not be reasonable. In that case you could look into running the tool dynamically, compiling the resulting code with Roslyn, and then dynamically loading it. I'm not saying it would be easy, but I think it could theoretically be done. Beyond this, we don't intend to add support for what you have been doing in EF6. EF Core does not have an XML format like EDMX or any equivalent serialization format, and it's not something that we plan to add to EF Core.

**Comment by Luigi6821** [comment]
> @Luigi6821 If you have a handful of different schema versions, then compiling a model for each of these seems reasonable. If you have dozens, then I agree it would not be reasonable. In that case you could look into running the tool dynamically, compiling the resulting code with Roslyn, and then dynamically loading it. I'm not saying it would be easy, but I think it could theoretically be done. Beyond this, we don't intend to add support for what you have been doing in EF6. EF Core does not have an XML format like EDMX or any equivalent serialization format, and it's not something that we plan to add to EF Core.

Hi Arthur,
You have been very clear.
Let me only try to check with you if an alternative way can be implemented that could really save my work.
Here below my EF core running time tests (milliseconds):
Build model : [36347]
Finalize model : [4498]
First query : [447]  
As is easy to get the build model time is the most expensive one. 
Basically the code:

`
    var modelBuilder = new ModelBuilder(SqlServerConventionSetBuilder.Build());
    modelBuilder.HasDefaultSchema("amos").HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");
    modelBuilder.Entity<AccTemplate>(entity =>
    { 
      ...
    }
    ...
    return modelBuilder
`
my propose 

`
    var modelBuilder = new ModelBuilder(SqlServerConventionSetBuilder.Build());
    if (!FileExists($"model{dbSchemaVersion}")
    {
       modelBuilder.HasDefaultSchema("amos").HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");
       modelBuilder.Entity<AccTemplate>(entity =>
       {   
          // Entity definition
       }
      // Other entities definition
      var entitiesConfiguration = modelBuilder.GetEnititesConfiguration();  // Return a serializable class entities configuration
      File.WriteAllText(JsonConvert.Serialize($"model{dbSchemaVersion})", entitiesConfiguration))
   }
   else
    {
        var deserializeEntitiesConfiguration = File.ReadAllText($"model{dbSchemaVersion}");
        modelBuilder.RestoreEntitiesConfiguration(deserializeEntitiesConfiguration);
    }
    return modelBuilder
`

that should be not so difficult to implement because it's enough to save the internal catalogue of entities and properties.
Normally for developer that uses EF only for interacting with db and not for creating db objects (table, column, function, sequence) a serializable catalogue as proposed could be enough.

**Comment by Luigi6821** [comment]
> @Luigi6821 It's considerable work to implement something that would serialize to and from a catalogue. That's not something we plan to do.

What a bad news for me :-(

**Comment by ajcvickers** [comment]
@Luigi6821 No, that's not something we are going to implement.

**Comment by Luigi6821** [comment]
Seems no way. Thanks
