### ISSUE TITLE
Ensure temporal tables tests run on PRs/C.I.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#26040]
They need SQL Server 2019 or later.

See https://github.com/dotnet/efcore/pull/26039

**Comment by ErikEJ** [comment]
I think 2016 is enough?

**Comment by smitpatel** [comment]
Temporal table needs SqlServer 2017. Helix on linux has that configuration.

**Comment by smitpatel** [comment]
Something wrong happened with helix ubuntu docker image at some point that it is not running any SqlServer tests.
