### ISSUE TITLE
[Question] SQL Server

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2605]
Hi

I have encounter this in my apps after upgrade to beta5.
"SQL Server-specific methods can only be used when the context is using a SQL Server data store."

It is something wrong with my connection string?
Data Source=WIN-S6OBBNTD9P9;Initial Catalog=Wallet1;Integrated Security=False;User ID=sa;Password=1234;Min Pool Size=5;Max Pool Size=5000;Connect Timeout=30;Application Name=Wallet

beta4: rollback to beta4 i do not have an error encounter.
beta5: Change Database.AsSqlServer().ApplyMigrations(); to Database.AsRelational().ApplyMigrations()

I have able to create the apply the migrations, but the query to the database above err will encounter.

**Comment by Ph47** [comment]
I have same problem.

ConfigureServices:
`services.AddEntityFramework().AddSqlServer().AddDbContext<Context>();`

later with using
`if (!context.Database.EnsureCreated()) context.Database.AsSqlServer().Create();`

**Comment by rowanmiller** [comment]
@XcoderTeam can you share your project with us so that we can reproduce the issue and debug what is happening?

**Comment by rowanmiller** [comment]
Closing as we have not heard back with the requested details
