### ISSUE TITLE
Scaffold-DbContext with NoPluralize flag incorrectly singularizes the navigation property name for the collection

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#26061]
I have tables User, Role and UserRole.  One user can have ,many roles. 
Using Scaffold-DbContext with NoPluralize flag, we notice that the collection property within the Model gets changed to singular. For e.g. in User Model class that is generated:
                         `public virtual ICollection<UserRole> UserRole { get; set; }`

This I feel is a bug. The property name should be plural regardless of whether we use NoPluralize flag or not:
                        `public virtual ICollection<UserRole> UserRoles { get; set; }`

#25503

**Comment by ajcvickers** [comment]
@geetmenon Can you explain more why this is a bug? Names are not pluralized or singularized when `NoPluralize` is used.

**Comment by geetmenon** [comment]
With `NoPluralize,` my expectation is that it should use the singular form of actual table name and column name. But it should not affect navigation property name. 

If the navigatory property is not a collection, it should be in singular, else it should be in plural regardless of whether or not we use `NoPluralize.`

**Comment by ajcvickers** [comment]
@geetmenon We discussed this, but it is not something we plan to change. Customization of this is covered by #4038, which we are considering for EF Core 7.0. Also, it's possible that @ErikEJ's EF Core Power Tools may have better support for this.
