### ISSUE TITLE
WHY NOT VIEWS !?!?

### ISSUE THREAD

**Issue by papiermache** [dotnet/efcore#26072]
much often an enterprise uses views to denormalize extreme complex data. To do equivalent in C# app would be nightmare. Why would EF Core scaffolding not support Views ?!?  Just tables and schemas ?!? I'm astounded, and humbly ask this be added soon someday.

sorry realized this page is not from where I was - which is "Microsoft.EntityFrameworkCore.Scaffolding" class "DatabaseModelFactoryOptions" - used by db reverse engineering apps.

**Comment by ErikEJ** [comment]
Views are supported! What makes you think otherwise?

**Comment by papiermache** [comment]
i was trying to use product Loresoft EntityFrameworkCore.Generator. It does not support views. So I cloned the app to review it. IT uses underlying microsoft entityframework scaffolding  DatebseModeFactoryOptions (assembly  Assembly Microsoft.EntityFrameworkCore.Relational) which only has Tables and Schemas. Thus limiting this product to .. tables and schemas. My question is why?

**Comment by ErikEJ** [comment]
Tables without keys = views.

Have a look at EF Core Power Tools (i think the Loresoft tool is quite old)

**Comment by roji** [comment]
@papiermache EF Core does support reverse engineering views, and as @ErikEJ says, EF Core Power Tools is a great option for a UI to do that.
