### ISSUE TITLE
ToTable(string) doesn't adhere to modelBuilder.HasDefaultSchema(string)

### ISSUE THREAD

**Issue by SetTrend** [dotnet/efcore#26106]
Using an Oracle database I'd like all objects to be created in a specific schema, so I used [`modelBuilder.HasDefaultSchema(string)`](https://docs.microsoft.com/dotnet/api/microsoft.entityframeworkcore.relationalmodelbuilderextensions.hasdefaultschema#Microsoft_EntityFrameworkCore_RelationalModelBuilderExtensions_HasDefaultSchema_Microsoft_EntityFrameworkCore_ModelBuilder_System_String_).

Yet, the schema name I provide in the above clause is not being used when I map an entity to a database table like this: [`entity.ToTable(string)`](https://docs.microsoft.com/dotnet/api/microsoft.entityframeworkcore.relationalentitytypebuilderextensions.totable#Microsoft_EntityFrameworkCore_RelationalEntityTypeBuilderExtensions_ToTable_Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder_System_String_). Instead, the current user's schema is being used.

### Expected Behaviour

The schema name provided by `RelationalModelBuilderExtensions.HasDefaultSchema(string)` should be used when mapping an entity to a table using `RelationalEntityTypeBuilderExtensions.ToTable(string)`.

**Comment by roji** [comment]
This does work in SQL Server (see code sample below), so you're most probably running into an Oracle provider issue. You'll need to raise that with them.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("foo");
        modelBuilder.Entity<Blog>().ToTable("bar");
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

This properly creates the `bar` table in the `foo` schema:

```sql
CREATE TABLE [foo].[bar] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(max) NULL,
    CONSTRAINT [PK_bar] PRIMARY KEY ([Id])
);
```
</details>

**Comment by SetTrend** [comment]
My mistake. I had a typo in my code. My sincere apologies for the trouble!! 😊
