### ISSUE TITLE
Deleting entry using Attach results in exception being thrown 

### ISSUE THREAD

**Issue by remus-corneliu** [dotnet/efcore#26102]
I'm a little confused in regards with the execution outcome of the following, and would like to understnad if this is normal or is it something that I don't understand.

```

 Author entity = new Author(id);

EntityEntry<Author> entry = _appDbContext.Author.Attach(entity);

_appDbContext.Author.Remove(entity);

int rows = await _appDbContext.SaveChangesAsync();
```

If the entity with the given id is present in the database, then the SaveChangesAsync method compleats without any issues.
However, if the entity with the given id is not present in the database, the SaveChangesAsync method will result in a `DbUpdateConcurrencyException`

Following are the EF package versions
```

<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.9" />
```

I'm a little confused because if the entity with the given id is not in the database I was expecting that SaveChangesAsync would return `0` for number of rows affected by the statement, and not throw the mentioned exception.

Is it something that I'm missing? is it a bug? I'm not sure.

**Comment by ErikEJ** [comment]
How is the key for MyEntity configured?

**Comment by remus-corneliu** [comment]
This is the configuration. MyEntity is actually an Author, I've updated the initial question as well.

        public void Configure(EntityTypeBuilder<Author> builder)
        {
            builder.HasKey(pk => pk.Id);

            builder
                .Property(col => col.Name)
                .HasColumnType("NVARCHAR(128)")
                .IsRequired();

            builder
                .HasMany(pt => pt.Books)
                .WithMany(p => p.Authors);
        }
