### ISSUE TITLE
Documentation is missing information on how to set up database users and rights

### ISSUE THREAD

**Issue by SetTrend** [dotnet/efcore#26126]
Setting up a fresh database installation (using Entity Framework Core [`EnsureCreated()`](https://docs.microsoft.com/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated)), I need to create a number of database users and grant appropriate rights to them for all objects that [`ModelBuilder`](https://docs.microsoft.com/dotnet/api/microsoft.entityframeworkcore.modelbuilder) is creating (e.g. entities, sequences etc., but also user permissions, like [`CREATE SESSION`](https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/CREATE-USER.html) system privilege).

My goal is to end up with a single DBA user for later database migration and a less privileged application user for running the app.

I've been looking for corresponding `ModelBuilder` extension methods, but couldn't find any.

As far as I can see, documentation lacks information on how to create database users and grant privileges using EF Core Code-first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview of Entity Framework Core - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by devklick** [comment]
I understand that the recommended approach to creating DB users is to add them via raw SQL within the migration, however what is the recommended approach to dealing with passwords within these migrations?

Obviously we dont want them stored in plain text within the migration script, and as far as I can tell, the migration doesnt have access to config values from the likes of user secrets. 

Is the only option to use environment variables, e.g.
```cs
migrationBuilder.Sql($"CREATE USER my_user WITH PASSWORD {Environment.GetEnvironmentVariable("MY_USER_PASSWORD")}");
```

**Comment by roji** [comment]
@devklick I don't think EF specifically has any guidance here. I suspect you're generally better off not managing users in migrations at all, but rather doing that completely externally to the application. Another option is to not use passwords at all (e.g. "integrated security").
