### ISSUE TITLE
Can't generate a migration using HiLo

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#26134]
When I generate the migrations, I have this error for all the primary keys that are configured to use HiLo

![image](https://user-images.githubusercontent.com/4983925/134301252-85724a7f-26a2-48a3-a8a5-1163b5e78ba4.png)

### Include provider and version information

EF Core version: 6.0.0-rtm.21471.18
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.3

**Comment by roji** [comment]
Thanks, I can see the bug and have submitted #26136 to fix this for 6.0.

**Comment by YeskaNova** [comment]
Thank you @roji

**Comment by roji** [comment]
As a workaround, you can replace SqlServerModelBuilderExtensions with SqlServerPropertyBuilderExtensions on all property configurations.
