### ISSUE TITLE
EF Core has the same issue as my Linq provider wrt VB.NET build in ns libraries

### ISSUE THREAD

**Issue by FransBouma** [dotnet/efcore#26137]
This code here: https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs#L312

has to check for `Microsoft.VisualBasic.CompilerServices.EmbeddedOperators.CompareString` as well. 

My linq provider for LLBLGen Pro has the same issue. Here's the description of when this occurs: https://www.llblgen.com/tinyforum/Message/Goto/150044

So a Linq query in a netstandard library using VB.NET will have references to `Microsoft.VisualBasic.CompilerServices.EmbeddedOperators.CompareString`, not `Microsoft.VisualBasic.CompilerServices.Operators.CompareString`. 

It sucks to find this out via a user, as I had to, so I hope this report will safe you all from this trouble.

**Comment by roji** [comment]
Thanks @FransBouma, not very pretty indeed.

**Comment by roji** [comment]
Note that EF no longer targets .NET Standard (recent versions only target .NET Core). It's conceivable that a .NET Standard VB library may be used by a .NET Core application, and that library produces the expression tree executed by EF Core, but that seems a bit unlikely...
