### ISSUE TITLE
Globally Opt of out Tracking, but opt in for just one Entity

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#26135]
In one of our solutions, we update only one table. All the other tables are read-only. So instead of having to modify all our queries to specify .AsNoTracking()   (except for the one related to this one table), is there a way to turn if off globally ( in Context) and turn it on (for e.g. in OnModelCreatingPartial() ) for just this one Entity?

**Comment by roji** [comment]
@geetmenon you can use AsTracking on queries touching your specific table, and default to AsNoTracking for all others; this should help reduce lots of boilerplate if most of your queries are non-tracking. However, there isn't any way to configure tracking on a per-entity-type basis, mixing tracking and no-tracking in a single query.

**Comment by geetmenon** [comment]
Thanks @roji. By `.....default to AsNoTracking for all others...`, are you saying that we should set AsNoTracking in our DBContext, and then override it with AsTracking in the queries touching this specific table?

**Comment by roji** [comment]
Yes, you can have the following in your context options:

```c#
optionsBuilder
            .UseSqlServer(...)
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
```

**Comment by geetmenon** [comment]
I would like to do this by adding a Partial class for my DBContext.  But OnConfiguring() is not a partial method of DbContext. So how do it do it without having to subclass my DbContext created using Scaffolding?

**Comment by ErikEJ** [comment]
Use the OnConfiguringPartial method in a partial class.

**Comment by geetmenon** [comment]
There is no OnConfiguringPartial method. I am using EF Core 5. Why are guy in a hurry to close tickets without waiting for us to confirm if the question is answered /issue is resolved. I will open another ticket for the same then,

**Comment by roji** [comment]
@geetmenon this ticket was not closed - it is still open; the `closed-question` label simply means we don't think there's an EF Core issue here, but rather a user question.

**Comment by geetmenon** [comment]
I had opened this ticket as a question ( I did not open it as a bug/issue). So the labelling it as `closed-question` doesn't make sense and it is confusing. Anyways I did open another ticket #26142 to get a correct/proper answer for the same question.

**Comment by roji** [comment]
Closing as the questions here and in #26142 were answered.
