### ISSUE TITLE
Hacktoberfest 2021 Participation?

### ISSUE THREAD

**Issue by Psypher9** [dotnet/efcore#26140]
Hello! I'm just curious to know if this project is open to participating in Hacktoberfest this year. 

Is that something you all would be open to? 

I realize that there have been some low quality issues in the past for some repos, but I am trying to get a list of projects together to coach some experienced devs in getting involved in the open source world. I've contributed some in the past and love this project and the people that would be interested in contributing use EF Core in pretty much all of their everyday projects.

If not, I understand, but I figured I would ask.

Thank you guys for everything you're doing!

**Comment by ajcvickers** [comment]
@Psypher9 We're open to it. I have added the `hacktoberfest` topic to this repo. However, if things go sideways again, then no promises; we'll deal with as best we can.
