### ISSUE TITLE
Where is "HasColumnOrder"?

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#26145]
## File a bug
According to this:
https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs

It looks like there should be a ```HasColumnOrder``` method but:
```<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0-rc.1.21452.10" />```
Does not seem to contain it.

Where should I be looking?

**Comment by ErikEJ** [comment]
In the daily build?

**Comment by TonyValenti** [comment]
@ErikEJ Is that Nuget-able?

**Comment by ErikEJ** [comment]
Yes: https://github.com/dotnet/efcore/blob/release/6.0/docs/DailyBuilds.md
