### ISSUE TITLE
Command line option to add HasColumnName to every property on scaffolding

### ISSUE THREAD

**Issue by markatk** [dotnet/efcore#26154]
I need to import many databases with the scaffold tool. The imported models need to be reviewed and most properties need to be renamed since the databases were created in a foreign language. When renaming the properties the columns cannot be found in the table if the scaffolding did not create a `HasColumnName()` entry for the given property. So I need to manually check each model and add the missing `HasColumnName()` calls afterwards.

I would like to have a command line option to force the scaffold tool to add the `HasColumnName()` to every property so renaming is a LOT faster afterwards. I can imagine this would help other developers as well.

**Comment by ErikEJ** [comment]
EF Core Power Tools has a renaming mechanism, that you may be able to use (UI or Json file) ??

**Comment by ajcvickers** [comment]
This is covered by #4038, which we are considering for EF Core 7.0.
