### ISSUE TITLE
Model differ cannot alter column when type mapping is missing

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26168]
Npgsql 6.0 does a breaking change to map a CLR type to a different PostgreSQL type (NodaTime Instant is now mapped to `timestamp with time zone` instead of `timestamp without time zone`); the old mapping is no longer supported (breaking change).

When upgrading to 6.0 with an existing model snapshot and adding a migration, the model differ throws an NRE since the CLR type is [looked up](https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L1171) on the source type mapping, which is always expected to be there.

As a workaround, I can make the old type mapping available specifically when the CLR/store type pair is looked up, though that would allow users to use it (it would fail later and uglier at the ADO level). We may want to consider making the differ resilient to missing type mappings for this case. If we go all the way, that means that IColumnMapping.TypeMapping becomes nullable in the relational model.

Otherwise, if this really is an unsupported scenario, we probably want to throw earlier and cleaner on it.

/cc @bricelam

**Comment by ajcvickers** [comment]
Note from triage: providers should continue to support type mappings that exist in snapshots. Providers can choose to throw in model validation if they are used outside of snapshots if they need to make a breaking change like this.
