### ISSUE TITLE
 Why does Microsoft.Data.SqlClient.SNI.dll get published under runtimes?

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#26175]
I have a .net core 5 library project (using VS2019) for my data layer which includes the following nuget packages:
Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.8" 
Microsoft.EntityFrameworkCore.Tools" Version="5.0.8"

When I build/publish my solution, I notice a "runtimes" folder with the following files underneath:
win-x64\native\Microsoft.Data.SqlClient.SNI.dll
win\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll
win\lib\netstandard2.0\System.Runtime.Caching.dll
win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll

Why is this? Is it because I am doing something wrong (like not including a package, etc)? If I remove any of the above files from my deployed folder, I run into errors at runtime. What do I need to do so that at runtime, there is no dependency on these files under "runtimes" folder?

**Comment by ErikEJ** [comment]
Those files are required to connect to SQL Server under with Windows.

**Comment by ajcvickers** [comment]
@geetmenon As @ErikEJ says, [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient), the underlying ADO.NET data provider for SQL Server, has required dependencies, some of which are native DLLs for Windows. If these are problematic in some way, then feel free to follow up with the SqlClient team at https://github.com/dotnet/SqlClient.

**Comment by geetmenon** [comment]
@ErikEJ,  if EFCore is using Microsoft.Data.SqlClient (which is still not fully migrated to .Net Core), then EFCore is not truly production ready.  The onus is on Microsoft to have this addressed at the earliest.

**Comment by ErikEJ** [comment]
It is fully migrated to .NET Core.

But under Windows (win-x64) it depends on some native components. This is not the case under Linux.

**Comment by geetmenon** [comment]
@ErikEJ,  you said `..But under Windows (win-x64) it depends on some native components. ..` .  So then please have Microsoft fix this asap.

**Comment by ErikEJ** [comment]
I do not work for Microsoft - but: fix what? What issue are you actually facing?

**Comment by ajcvickers** [comment]
@geetmenon It is by-design that Microsoft.Data.SqlClient using native code on Windows. There is no requirement that .NET Core be fully managed. Several components use native code on various platforms. For example, Microsoft.Data.Sqlite uses native code everywhere.

**Comment by geetmenon** [comment]
We understand this @ajcvickers . However we did not run this issue when we were using EF6.  Now that we are migrating to EF Core, why is there a dependency now on a native dll? We are now being forced to change our builds to push the files in win-x64\native and win\lib folders under runtimes folder because of this constraint.  So why is that EFCore has an indirect dependence on a native library whereas EF6 did not?

**Comment by ajcvickers** [comment]
@geetmenon The native code shipped with .NET Framework.

**Comment by geetmenon** [comment]
Thanks for this information @ajcvickers! Will check in `dotnet/core`  repo if they have any information/clarification on this.

**Comment by ajcvickers** [comment]
@geetmenon This is all by-design. Microsoft.Data.SqlClient is shipped from [dotnet/SqlClient](https://github.com/dotnet/SqlClient), so if you do want to follow up more, then that would be the best place to start. However, nothing will change here, other than long-term plans to make Microsoft.Data.SqlClient fully managed.
