### ISSUE TITLE
EntityFramework beta5 / NuGet Public

### ISSUE THREAD

**Issue by Antaris** [dotnet/efcore#2617]
Hi Devs,

Do you know when beta5 will make its way to the public NuGet feed? I don't want to depend on nightly builds (beta6+ stuff), and from what I can see only beta4 has reached the public NuGet feed

https://github.com/aspnet/EntityFramework/releases/tag/7.0.0-beta5
https://www.nuget.org/packages/EntityFramework/7.0.0-beta4

Unfortunately beta4 still has a dependency on `Microsoft.Framework.DependencyInjection.Interfaces` which has since been renamed to `Abstractions` so I can't mix framework beta5 bits with EF7 beta4.

**Comment by ErikEJ** [comment]
Beta5 is on NuGet.org, but the EntityFramework package is no longer in use, reference the provider package that you want to use, for example 

    EntityFramework.SqlServer -Pre

https://www.nuget.org/packages/EntityFramework.SqlServer/7.0.0-beta5

**Comment by Antaris** [comment]
@ErikEJ Thanks for this information, makes sense! Most of my framework components are being designed as provider-agnostic, so I can take dependencies on sub-packages like `EntityFramework.Core` etc, and just have the host dependant on the provider-specific package.

Thanks for your help!

**Comment by ryanwinter** [comment]
Is the beta5 available for sqlite on NuGet? I can only find a beta1 version.

Thanks!

**Comment by natemcmaster** [comment]
Beta5 is not available on Nuget yet. We hope it will be soon. Until then, you can try using the [nightly builds of SQLite.](https://www.myget.org/gallery/aspnetvnext)

**Comment by rowanmiller** [comment]
Just to clarify - Beta 5 in general is available but we did not publish the SQLite provider as part of Beta 5. Our plan is to ship it as part of Beta 6 which will release shortly.

**Comment by ryanwinter** [comment]
Thanks guys, can't wait to try it out.
