### ISSUE TITLE
Update columns only for modified properties from disconnected entity.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#26183]
I am querying the entity using one context instance and updating this entity using another context instance. The update is working fine but the problem is that it's generating the SQL update command for all properties even if there are no changes in values as follows::

```C#
// Getting the entity using one repository (one context instance) as follows:
Employee employeeToBeUpdated = await _queryRepository.GetByIdAsync<Employee>(employee.EmployeeId);

// Changing the values
employeeToBeUpdated.EmployeeName = employee.EmployeeName;
employeeToBeUpdated.DepartmentName = employee.DepartmentName;

// Updating the entity using another repository (another context instance)
await _commandRepository.UpdateAsync(employeeToBeUpdated); // Generating update command for all properties
```

Is there any way to use tracking of one context instance in another context so that the update command is generated only for modified properties of the disconnected entity?

**Comment by ajcvickers** [comment]
@TanvirArjel Attach the entity first, then change the properties. Calling Update marks all properties as modified. This is the easy way to ensure everything that has changed gets saved. On the other hand, calling Attach marks no properties as modified. If you then change the properties, EF will detect those changes and mark only those properties as modified.

**Comment by TanvirArjel** [comment]
@ajcvickers I am aware of this. But how would you achieve this with repository pattern? when you have to  make changes even before calling attach or update.

Please look at my code.

**Comment by ajcvickers** [comment]
@TanvirArjel I don't see anything in your code that precludes you from doing this.

**Comment by TanvirArjel** [comment]
@ajcvickers I am calling the `await _commandRepository.UpdateAsync(employeeToBeUpdated);` with changes  so calling `Attach()` method inside `_commandRepository.UpdateAsync` would not make any effect. Maybe you proposing something as follows:

// Getting the entity using one repository (one context instance) as follows:
Employee employeeToBeUpdated = await _queryRepository.GetByIdAsync<Employee>(employee.EmployeeId);

// Attach the entity  to the other instance of dbContent
_commandRepository.Attach(employeeToBeUpdated);

// Changing the values
employeeToBeUpdated.EmployeeName = employee.EmployeeName;
employeeToBeUpdated.DepartmentName = employee.DepartmentName;

// Updating the entity using another repository (another context instance)
await _commandRepository.UpdateAsync(employeeToBeUpdated); // Generating update command for all properties

am I correct?

**Comment by ajcvickers** [comment]
Yes.

**Comment by TanvirArjel** [comment]
@ajcvickers This option would not help. It would have been great if there is an option to configure the tracking across context instances in scope lifetime.

**Comment by ajcvickers** [comment]
@TanvirArjel There is nothing to do this. I would not recommend using two context instances like this; it defeats EF Core change tracking. You can of course find every modified property on the first context instance and mark the same properties as modified in the second context. But that's not something we're going to do automatically.

**Comment by TanvirArjel** [comment]
Got your point. But you said:

>You can of course find every modified property on the first context instance and mark the same properties as modified in the second context.

I shall be very happy if you show me a small example with the code. It should fix my issue.

Thanks in advance.

**Comment by ajcvickers** [comment]
@TanvirArjel Here's an example:

```C#
public class Employee
{
    public int EmployeeId { get; set; }
    public string EmployeeName { get; set; }
    public string DepartmentName { get; set; }
    public string Notes { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(new Employee
                {
                    EmployeeName = "Pinky Pie",
                    DepartmentName = "Fun",
                    Notes = "Pink"
                },
                new Employee
                {
                    EmployeeName = "Rainbow Dash",
                    DepartmentName = "Wonderbolts",
                    Notes = "Wild"
                });

            context.SaveChanges();
        }

        using var readContext = new SomeDbContext();
        var employee = readContext.Set<Employee>().Find(1);

        employee.EmployeeName = "Fluttershy";
        employee.DepartmentName = "Animal Rescue";

        using var writeContext = new SomeDbContext();
        var writeEntry = writeContext.Attach(employee);

        foreach (var property in readContext.Entry(employee).Properties)
        {
            if (property.IsModified)
            {
                writeEntry.Property(property.Metadata.Name).IsModified = true;
            }
        }

        writeContext.SaveChanges();
    }
}
```

Update SQL does not write Notes, since it was not modified:

```
info: 9/30/2021 12:32:07.594 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[@p2='1', @p0='Animal Rescue' (Size = 4000), @p1='Fluttershy' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      UPDATE [Employee] SET [DepartmentName] = @p0, [EmployeeName] = @p1
      WHERE [EmployeeId] = @p2;
      SELECT @@ROWCOUNT;
```

**Comment by TanvirArjel** [comment]
@ajcvickers Thank you but this would not help in the case of the repository pattern.
