### ISSUE TITLE
Warning Entity 'Role' has a global query filter defined and is the required end of a relationship with the entity in a Many to Many relationships

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#26185]
## File a bug
I have the following model which has a many to many relationship between Role and Permission. Role implements a Global query filter (ITenant). I manually set the M2M relationship in dbcontext because I have an extra property between Role and Permission (IsGranted). I dont want to set ITenant on Permission since Permissions are the same for all tenants. (No reason to repeat lets say Permission user.create) 

```C#
public class Role : ITenant
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public long Id { get; set; }

	public string Name { get; set; }

	private readonly List<RolePermission> permissions = new List<RolePermission>();
	public virtual IReadOnlyCollection<RolePermission> Permissions => permissions;

	public long TenantId { get; set; }
	public Tenant Tenant { get; set; }
}

public class Permission
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public long Id { get; set; }

	public string Name { get; set; }
}

public class RolePermission
{
	public long RoleId { get; set; }
	public Role Role { get; set; }

	public long PermissionId { get; set; }
	public Permission Permission { get; set; }

	public bool IsGranted { get; set; }
}

public interface ITenant
{
	long TenantId { get; set; }

	Tenant Tenant { get; set; }
}
	
public class MyDbContext : DbContext
{
	public SessionInfo SessionInfo { get; set; }

	public MyDbContext(DbContextOptions options)
		: base(options)
	{
		Database.Migrate();
	}

	public virtual DbSet<Role> Role { get; set; }
	public virtual DbSet<Permission> Permission { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		
		modelBuilder.Entity<RolePermission>()
			.HasKey(ttd => new {ttd.RoleId, ttd.PermissionId});

		modelBuilder.Entity<RolePermission>()
			.HasOne(tt => tt.Role)
			.WithMany()
			.HasForeignKey(tt => tt.RoleId)
			.OnDelete(DeleteBehavior.Restrict);

		modelBuilder.Entity<RolePermission>()
			.HasOne(s => s.Permission)
			.WithMany()
			.HasForeignKey(s => s.PermissionId)
			.OnDelete(DeleteBehavior.Restrict);

		modelBuilder.SetQueryFilterOnAllEntities<ITenant>(e => e.TenantId == SessionInfo.TenantId);
	}
}
```

When I run Add-Migration <MigrationName> I get the following warning:

> Entity 'Role' has a global query filter defined and is the required end of a relationship with the entity 'RolePermission'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.

I understand that this happen if you have an one to Many relationship but this is not the case on my scenario (M2M). The issue I suppose is because I specify 2 one to many relationships (to form the M2M). Is there any resolution to this warning?

### Include provider and version information

EF Core version: 5.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net5
Operating system: Win10
IDE: VS2019 16.8.5

**Comment by smitpatel** [comment]
There is no many-to-many relation in the model. Model has one-to-many relation between Role & RolePermission configured by below code.
```C#
modelBuilder.Entity<RolePermission>()
			.HasOne(tt => tt.Role)
			.WithMany()
			.HasForeignKey(tt => tt.RoleId)
			.OnDelete(DeleteBehavior.Restrict);
```
Hence warning is accurate. The exception message has details on how to deal with it.

**Comment by pantonis** [comment]
@smitpatel there is a many to many relationship between Role and Permission. I manually configure it instead of using collections on both models because IsGranted exists on the relationship. The exception states that I need to add TenantId into Permission. As i stated there is no need to repeat same permissions for all tenants

**Comment by smitpatel** [comment]
There are 2 one-to-many relationship in the model. While it may give the same effect and look like many-to-many, in the model and database there are actually 2 one-to-many relationships only. (Many to many cannot be modeled in relational database directly.). So either you would need to set up filter on RolePermission also or if you believe that your data would be accurate without adding that filter then you can suppress the warning.

**Comment by magals** [comment]
please explain, how can I suppress this warning?
there is not even a warning code in the console.
I even set <WarningLevel>0</WarningLevel> in the project file, but the warning still appears when adding or deleting a migration.
