### ISSUE TITLE
Migrations: Ignore default value if column is Identity

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#2622]
We decided in API review that if SQL Server decides that a column is Identity, then is should ignore any default value set rather than generating invalid SQL. This will take a bit of refactoring because the default value code is not SQL Server specific, but the Identity column information is known only to SQL Server.

**Comment by rowanmiller** [comment]
Discussed and decided not to do this. If you specify both, then the database can just give you the appropriate error. 

Note, this is about DefaultValue and not DefaultValueSql (which is valid)
