### ISSUE TITLE
Microsoft.Data.Sqlite: Can't load extensions that modify existing functions or collations

### ISSUE THREAD

**Issue by krazado** [dotnet/efcore#26220]
LoadExtension method from SqliteConnection(Microsoft.Data.Sqlite) throws exception, but same method from SQLiteConnection(System.Data.SQLite) works fine.

I built a ICU extension and trying to load it with efcore, ef uses the SqliteConnection which is root reason of the problem, because I tried to create new SqliteConnection and same error is thrown, but as I stated out exactly same setup works fine with SQLiteConnection(System.Data.SQLite).

here is the code snippets, but I attached complete working project with both examples.

```C#
 //this is throwing exception 
        public static void LoadICUWithSqliteConnection(SqliteConnection sqliteConn)
        {
            try
            {                              
                if (sqliteConn.State == System.Data.ConnectionState.Closed)
                    sqliteConn.Open();

                if (sqliteConn != null
                    && File.Exists(ICUPath))
                {
                    sqliteConn.EnableExtensions(true);
                    sqliteConn.LoadExtension(ICUPath, "sqlite3_icu_init");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

//this works like it should
        public static void LoadICUWithSQLiteConnection(SQLiteConnection sqliteConnection)
        {
            try
            {

                if (sqliteConnection != null
                    && sqliteConnection.State == System.Data.ConnectionState.Open
                    && File.Exists(ICUPath))
                {
                    sqliteConnection.EnableExtensions(true);
                    sqliteConnection.LoadExtension(ICUPath, "sqlite3_icu_init");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
```

```
Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'error during initialization: '.'
```

### Include version information

Microsoft.Data.Sqlite version:5.0.10.0
Target framework: NET 5.0
Operating system: Windows 10 

Unfortunately I could not upload .zip here, it says file is not supported, but here is the public link and you can download sample project: https://drive.google.com/file/d/1o7mXRxnNNFU1CFLokI106YTUQ6z4z5yC/view?usp=sharing

**Comment by bricelam** [comment]
Two native libraries (icuin69.dll and icuuc69d.dll) seem to be missing from the sample...

**Comment by bricelam** [comment]
Just for fun, here's the horrible C code I had to write to get to the bottom of this. 😬 Don't bother pointing out all the leaked memory; handling all those result codes was painful enough.
```c
#include <cassert>
#include <cstdio>
#include "sqlite3.h"

int main()
{
    sqlite3* db;
    int rc = sqlite3_open(":memory:", &db);
    assert(rc == SQLITE_OK);

    rc = sqlite3_enable_load_extension(db, 1);
    assert(rc == SQLITE_OK);

    sqlite3_stmt* stmt;
    rc = sqlite3_prepare_v2(db, "SELECT load_extension('ICU_2017_V2', 'sqlite3_icu_init')\0", -1, &stmt, NULL);
    assert(rc == SQLITE_OK);

    rc = sqlite3_step(stmt);
    if (rc == SQLITE_ERROR)
    {
        printf(sqlite3_errmsg(db));
    }
}
```
