### ISSUE TITLE
Mix AsSingleQuery / AsSplitQuery

### ISSUE THREAD

**Issue by angelaki** [dotnet/efcore#26244]
It would be great if we were able to mix both of these behaviors for one query. E:g. if I have several 1:1 and only a single (but huge) 1:n relation, I'd like to include them via `AsSingleQuery` and only the last one via `AsSplitQuery`.

But I'm afraid implementing this isn't that easy?

**Comment by roji** [comment]
@angelaki 1:1 relationships are always loaded via a single query, regardless of whether you specify AsSingleQuery/AsSplitQuery, only collection navigations are affected by those ([see this note in the docs](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#split-queries-1).
