### ISSUE TITLE
Cosmos: FromSql allows omitting properties from the projection

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26243]
While investigating #26124, I came across a discrepancy in behavior with relational. Our current behavior for relational is to throw if any columns are missing from the raw SQL projection (test FromSqlRaw_queryable_simple_columns_out_of_order_and_not_enough_columns_throws); Cosmos does not throw in this case, and returns a partially-populated entity instance instead.

I'm guessing we disallow partial projections because of change tracking; we probably want to align the Cosmos behavior here (doing so after 6.0 would be a breaking change).

**Comment by ajcvickers** [comment]
I'm in favor of matching the relational behavior. @AndriySvyryd? @smitpatel?

**Comment by smitpatel** [comment]
Though we should discuss difference of key missing and key having null value in JSON since relational doesn't have that feature.
