### ISSUE TITLE
Fix "Relational: Lift sub-queries in Where and OrderBy clauses" breaks SQLCE

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2626]
@anpete  The recent fix for this unfortunately breaks the SQLCE provider, as the SQL generated with nested SELECTs is not supported by the SQL CE engine. https://github.com/aspnet/EntityFramework/commit/cd1839b224ab0f1b49473216a146510d562d9735 
What do I need to change in order for this to work again?

Affected query tests include: 

OrderBy_correlated_subquery_lol()
Where_query_composition()
Where_shadow_subquery_first()
Where_subquery_correlated()
Where_subquery_recursive_trivial()

**Comment by anpete** [comment]
In the short term we can add a flag to the base RelationalQueryCompilationContext so that providers could disable sub-query lifting for these cases. Of course, this means that those providers would be doing client eval of those sub-queries.

To implement a better solution, once query is fully DI enabled, a specific provider could specialize the appropriate parts of the query pipeline in order to perform a different translation. E.g. Convert sub-queries into joins etc. This could likely be done either by pre-processing the QueryModel, or by post-processing the actual SQL SelectExpression. Given that these transformations often lead to better SQL, we would ideally incorporate them into base relational.

**Comment by divega** [comment]
I am curious if similar kinds of queries were translated differently for SQL Server and SQL CE providers in EF6. Is there a relevant example?

**Comment by anpete** [comment]
@divega The tests listed above would be a starting point. It could be that we do the join optimization more often in EF6...

**Comment by ErikEJ** [comment]
I will try to execute the same 5 queries with EF6 and SQLCE, and report back

**Comment by ErikEJ** [comment]
@anpete @divega ??

**Comment by divega** [comment]
@anpete still needs to look deeper in to this but the tentative plans is:

1. For the short term, have some kind of way to opt out of the new behavior to avoid breaking your provider.
2. Longer term, revisit how we produce the lifted translation to make it more compatible with other providers, probably resulting in something more similar to what we did in EF6.

BTW @anpete do we need to do (1) for Beta6?

**Comment by ErikEJ** [comment]
@anpete any plans to enable this switch for beta 8 or RC?

**Comment by rowanmiller** [comment]
@ErikEJ we are going to pretty hard pressed to get this done for RC, any chance you could look at a contribution for it?

**Comment by ErikEJ** [comment]
@rowanmiller I guess I could, at least the opt out...

**Comment by rowanmiller** [comment]
@ErikEJ just a general note on this (and a couple of other issues where we need to make things more flexible to support CE). Given how much is on our plate to get RC done, we aren't going to be able to dedicate a lot of time to sorting this out for RC. We will spend the time to unblock things before RTM. Our perspective is that the limitations should be ok for the CE provider for RC - as they don't seem to be super common cases (not that they aren't important, just that we need to prioritize things). That said, if you want to look at working around them, then we'd be happy to take contributions on them.

**Comment by rowanmiller** [comment]
@anpete can you respond to this from @ErikEJ 

> @anpete Could you point me to the proper location where to change the flow based on the flag?  cd1839b  - and do you have a suggestion for a name for it?

**Comment by ErikEJ** [comment]
@anpete @rowanmiller Thanks both, looking forward to some pointers to get me started with a workaround - but as you say Rowan, certainly not high prio, concentrate on the SQL Server and SQLite experiences for now. I have not heard of anybody being hit by this, either!

**Comment by ErikEJ** [comment]
Now this test also breaks: Join_navigation_translated_to_subquery_self_ref 
Still looking forward to some workaround pointers...

**Comment by ErikEJ** [comment]
Looks like the recent fix https://github.com/aspnet/EntityFramework/pull/4433 unblocks some of these failing tests!

**Comment by divega** [comment]
Good to hear. Can you detail which tests still fail and or the general pattern that still doesn't work?

**Comment by ErikEJ** [comment]
@divega Not yet, still waiting for the latest daily. Once available, I will post a list of tests that still fail.

**Comment by divega** [comment]
I totally understand. I was just wondering if the remaining issue are queries that contain singleton subqueries in the WHERE clause, which AFAIR are not supported in SQL CE, e.g.:

``` SQL    
SELECT [e1].[EmployeeID], [e1].[FirstName]
FROM [Employees] AS [e1]  
WHERE ([e1].[FirstName] = (  
    SELECT TOP(1) [e].[FirstName]  
    FROM [Employees] AS [e]  
    ORDER BY [e].[EmployeeID]  
))
``` 

Because for those maybe you can just introduce the ALL operator in the SQL CE translation (or even ANY - it shouldn't make a difference since the subquery will return just one row anyway), e.g.:

``` SQL    
SELECT [e1].[EmployeeID], [e1].[FirstName]
FROM [Employees] AS [e1]  
WHERE ([e1].[FirstName] = ALL (  
    SELECT TOP(1) [e].[FirstName]  
    FROM [Employees] AS [e]  
    ORDER BY [e].[EmployeeID]  
))
```

**Comment by divega** [comment]
Or you could replace = with IN:

``` SQL
SELECT [e1].[EmployeeID], [e1].[FirstName]
FROM [Employees] AS [e1]  
WHERE ([e1].[FirstName] IN (  
    SELECT TOP(1) [e].[FirstName]  
    FROM [Employees] AS [e]  
    ORDER BY [e].[EmployeeID]  
))
```

**Comment by ErikEJ** [comment]
Both the IN and ALL solution works, but many of the remaining queries seem to have this shape:

    SELECT * 
    FROM [Customers] AS [c] 
     ORDER BY ( 
     SELECT CASE  
         WHEN EXISTS ( 
             SELECT 1 
             FROM [Customers] AS [c2] 
             WHERE [c2].[CustomerID] = [c].[CustomerID]) 
 
           THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) 
       END 
     )

**Comment by divega** [comment]
Yeah, IN or ALL can help with singleton subqueries in a search condition, i.e. in the WHERE clause, but it won't help in other places like ORDER BY or SELECT.

**Comment by divega** [comment]
@ErikEJ should we keep this open for the remaining cases?

**Comment by ErikEJ** [comment]
Yes, please

**Comment by ErikEJ** [comment]
@divega Finally got a never build with the mentioned fix. Now "only" the following tests fail (From QuerySqlCeTest class):

OrderBy_correlated_subquery_lol()
OrderBy_correlated_subquery_lol2()
Where_query_composition()
Where_shadow_subquery_first()

**Comment by rowanmiller** [comment]
@ErikEJ we would take a PR for this, but it's not something we are planning to address.

**Comment by ErikEJ** [comment]
@rowanmiller ok 😢 Could you possibly give me some hints re what I would need to change??
