### ISSUE TITLE
Invalid results ordering in InMemoryDatabase

### ISSUE THREAD

**Issue by alexvaluyskiy** [dotnet/efcore#2627]
I have this class and a code and i use InMemoryDatabase in my unit tests

``` C#
public class Country
{
    public int Id { get; set; }
    public string Name { get; set; }
}

private async Task CreateSampleData(SampleContext dbContext)
{
    var countries = new List<Country>
    {
        new Country { Id = 1, Name = "USA" },
        new Country { Id = 2, Name = "France" }
    };
    dbContext.Countries.AddRange(countries);
    await dbContext.SaveChangesAsync();
}

public List<Country> GetData() {
    return dbContext.Countries.ToList();
}
```

And on each method call I can get these data in a random order if I don't have OrderBy in this method.

**Comment by Phasiq** [comment]
Why would this be a bug? Your DbSet is not sorted, so unless you specify a sort order in your query, the resulting list should/will be random.

**Comment by ravengerUA** [comment]
Why randomly, but not successively?

**Comment by Phasiq** [comment]
Because DbSet by definition, is an *unordered* list. Primary keys do not dictate sort order (how would you sort a primary key that is a uniqueidentifier?), even in a relational database.  How would you sort an inner join of two tables which both have a primary key? Which primary key wins? Data sets are not ordered and you cannot expect them to be. This isn't a bug, this is how they function.

**Comment by ravengerUA** [comment]
But if i put the data in this order, why I can't get the data in the same order?
````
[id]    [name]
  1      USA
  2      France
  3      UK         
````

I don't think it is a good idea to put Order By primary key to hundreds of queries only for unit testing with InMemoryDatabase

**Comment by Phasiq** [comment]
When you add data to a DbSet, they're not going into the set "in order" and
they're not stored in the order that you add them. A DbSet has NO logical
order, even if your data does. A primary key field is not default sort
column, it identifies a relationship from one data set to another.  If you
want to sort your data when queried, you MUST be explicit.

What exactly are your unit tests testing for? If you just want to see if a
particular record is present in a dataset, you can accomplish the same
thing without an order by using any:   ex. dbContext.Countries.Any(x=>x.Id
== 1) would return true if a record with Id equal to 1 exists in the set
and no order by would be necessary.

**Comment by rowanmiller** [comment]
As @Phasiq mentioned, this is by design. DbSet does not impose any ordering and EF has not contract with the provider around the order things are stored in the database. If you want things in a particular order then adding sorting to the query is the right way to do this.
