### ISSUE TITLE
FirstOrDefaultAsync() indicates return value is not ever null

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#26272]
Can anyone tell me why the following code does not produce a warning when `nullable` is enabled?

    CustomerRailcar customerRailcar = await dbContext.CustomerRailcars
        .Where(cr => cr.RailcarNumber == railcar.RailcarNumber)
        .FirstOrDefaultAsync();

This code could clearly return null. But `FirstOrDefaultAsync()` shows it's returning `Task<CustomerRailcar>` and not `Task<CustomerRailcar?>`.

Isn't this wrong?

I'm using .NET 5.0.

**Comment by smitpatel** [comment]
EF Core 5.0 is not annotated for nullable types. This has been fixed in EF Core 6.0.
