### ISSUE TITLE
You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#26273]
This is what I currently have, and it scaffolds fine: 

```
Scaffold-DbContext  -Connection "Server=.\sql2012express; Database=MyDbName; Trusted_Connection=True; MultipleActiveResultSets=true;"  -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir ..\MyComp.MySolution.Data.Model  -Namespace MyComp.MySolution.Data.Model  -ContextDir . -Context MyDbContext -ContextNamespace MyComp.MySolution.Data  -StartupProject MyComp.MySolution.Data -UseDatabaseNames -DataAnnotations -NoPluralize
```

However, it ends up adding the following in MyDbContext.cs:

```c#
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=.\\sql2012express; Database=MyDbName; Trusted_Connection=True; MultipleActiveResultSets=true;");
            }
        }
```

How do I prevent it from either adding `OnConfiguring()` or prevent it from including the hard coded connection string value?  Some documents say we need to use `--no-onconfiguring` option and some says we need to use the Name= syntax. The documentation for this is very poor. I read somewhere that I need to install `dotnet-ef tool` which I have now. And I have added `Microsoft.EntityFrameworkCore.Design` package. I also read that `--no-onconfiguring` option will not work with `Scaffold-DbContext` command and that I would have to use `dotnet ef dbcontext scaffold` command. 

If this the case, and if say my connection string name is MyConnection, then please let me know the exact command (along with the necessary options) I need to pass with `dotnet ef dbcontext scaffold` command in my package manager console to do all that my above` Scaffold-DbContext` command does (please refer to all the switches I am passing) and in addition 
	a) prevent it from either adding` OnConfiguring()`, 
	b) or include connection string name instead of the hard coded connection string value

**Comment by ErikEJ** [comment]
Try 
-NoOnconfiguring

Which EF Core version?

Or use EF Core Power Tools 😀
