### ISSUE TITLE
Using Mysql database Collation function ForMySQLHasCollation() with dotnet ef command not generating correct ModelSnapshot 

### ISSUE THREAD

**Issue by acpsa** [dotnet/efcore#26280]
I am using efcore with mysql database in code first approach.
[Reference](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-charset.html)

This is how I am adding the collation in DbContext using FluentAPI -
```
modelBuilder
       .Entity<EntityName>()
       .Property(p => p.PropWithCollation)
       .ForMySQLHasCollation("utf8mb4_0900_ai_ci");
```

After I add migration using `dotnet ef migrations add MigrationName` , the generated ModelSnapshot `MyDbContextModelSnapshot.BuildModel()` shows as 
``` 
b.Property<string>("PropWithCollation")
       .HasCollation("utf8mb4_0900_ai_ci");
``` 
, and leads to build errors about missing references.

Now When I manually replace it with (also including the namespace `MySQL.EntityFrameworkCore.Extensions` )
``` 
b.Property<string>("PropWithCollation")
       .ForMySQLHasCollation("utf8mb4_0900_ai_ci");
```
 , then it works fine and my migrations run as expected. **But I have to do it in every subsequent migration since I added that collation**.

And If I use this in my DBContext file -
``` 
b.Property<string>("PropWithCollation")
       .UseCollation"utf8mb4_0900_ai_ci");
```
, then it generates the default collation in my database table `utf8_general_ci` and not the one I specify.

Am I missing anything here ?

EF Core version: Entity Framework Core .NET Command-line Tools 5.0.10
Database provider: MySql.EntityFrameworkCore 5.0.5
Target framework:  .NET 5.0
Operating system: Win 10 Enterprise
IDE: Visual Studio 2019 16.11.2

**Comment by ajcvickers** [comment]
@acpsa Have you tried using the [Pomelo MySQL EF Core provider](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql), on [NuGet](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/)? A lot of people have had luck with this provider in cases where the official provider from Oracle doesn't work.

Beyond that, you will likely need to report this to Oracle as a provider issue.
