### ISSUE TITLE
Question: How do it reference Entityframework 6.2.* in Asp.Net 5 StartUp.cs

### ISSUE THREAD

**Issue by mbharodia** [dotnet/efcore#2628]
Hi,

I was doing some experiment and looking in to the details of EF 7. Looks like that It may be a while before we could migrate existing data project to EF 7. Therefore, I was thinking to reuse our existing project in Asp.Net 5. I was wondering how I go about referencing it in Startup.cs? I am not adding Entityframework 7 Beta references to project.json. Therefore, SqlServer option is not available.

Our data project is a separate, which has references to EF 6.2.*. In the current web application (Asp.Net MVC 4) we have used Unity to  inject required services. As shown below we have container which registers services.

![image](https://cloud.githubusercontent.com/assets/10344641/8697784/291254ae-2ab5-11e5-80f4-d44d31b10c48.png)

Do I have to follow the same convention or could I still use services.AddEntityFramework()? If I can use services.AddEntityFramework(), then I am not sure how do I do that? As said earlier I do not have references to EF 7 in Asp.Net 5 project.

Any other idea or any other suggestion? Really appreciate your help.

**Comment by ErikEJ** [comment]
@julielerman Has an MSDN article about using EF6 from ASP.NET 5 (Full desktop CLR) https://msdn.microsoft.com/magazine/dn973011.aspx

**Comment by mbharodia** [comment]
Hi ,

Thanks for your reply.
