### ISSUE TITLE
Sql Server Feature Request:  Dynamic Order By clause

### ISSUE THREAD

**Issue by roysurles** [dotnet/efcore#26284]
### Is your feature request related to a problem? Please describe.
I cannot find any location to submit a Sql Server feature request, so please point me in the right direction.

### Describe the solution you'd like
I want to submit a feature request: Dynamic Order By clause via parameter (@OrderBy) without using dynamic sql (@Sql + ' ' + @OrderBy), Case or IIf.
This should allow for multiple columns in any order and direction (ASC|DESC) per column.

**Comment by ajcvickers** [comment]
@roysurles I'm not aware of any place you can publicly request features from SQL Server. Happy to be corrected if there is such a place and someone can point to it. @ErikEJ?
