### ISSUE TITLE
EF 6 making NOT NULL columns of properties/fields that are not marked with RequiredAttribute

### ISSUE THREAD

**Issue by blazorin** [dotnet/efcore#26302]
I'm using .NET 6 RC1, and I'm seeing an issue that was not happening on NET 5 (I've not used EF in older .NET 6 previews rather than preview 7(rc1) )

Here is a screenshot browsing the table data and structure. Only the column I marked as not required with Fluent API is allowed to have null values (not doing this also creates the email column as NOT NULL like the other ones)
![Screen Shot 2021-10-10 at 5 26 01 PM](https://user-images.githubusercontent.com/32218025/136702356-47cd1089-00dc-4790-b030-f43fc9d2451f.png)

Property definition:
![Screen Shot 2021-10-10 at 5 30 13 PM](https://user-images.githubusercontent.com/32218025/136702709-e7fdfc56-0554-470e-933c-241d7d55448e.png)

Here is a screenshot of how an old database scheme from .NET 5 looks like using similar properties:
Those two fields are NOT marked with RequiredAttribute
![Screen Shot 2021-10-10 at 5 38 51 PM](https://user-images.githubusercontent.com/32218025/136703176-ed5dc2dc-5588-49a1-86b1-f2009faa1729.png)

> Seems a quite critical issue, in my opinion. Something is not working correctly in schema creation.

**Comment by roji** [comment]
@3DSX can you please post a full model? It's difficult to know what's going on from a partial code snippet.

In some cases, a database column is nullable even when the property is marked as required in the EF mode; this is notably the case when the TPH inheritance is being used, and there are other entity types in the hierarchy which do not have that property.

**Comment by ajcvickers** [comment]
@3DSX Do you have nullable reference types enabled? Check for `<nullable>enable</enable>` in your csproj file.

**Comment by 3DSX** [comment]
> Ah, I understood the issue backwards. If the problem is that columns _aren't_ nullable, that definitely sounds related to NRTs being enabled. If so, use `string?` instead of `string`.



> @3DSX Do you have nullable reference types enabled? Check for `<nullable>enable</enable>` in your csproj file.

Thank you guys for the quick response. Yes, it was that! I forgot .NET 6 new project files at least for Web API had nullables enabled by default. In fact, it makes more sense than just using the attribute. 
Have a good day.
