### ISSUE TITLE
Problem with SQL-translation of double Negate: -(-column)

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#26309]
EFCore 6.0

Seems, your infrastructure incorrect translate the double negate operation:

**MSSQL test**

```c#
ss => ss.Set<Squad>().Where(s => -(-s.Id) == -s.Id))
```
**Error message** 
> Microsoft.Data.SqlClient.SqlException : Incorrect syntax near 'WHERE'.

**Comment by roji** [comment]
Confirmed, this generates `WHERE --[s].[Id] = [s].[Id]`, the double-dash is interpreted as a SQL comment.
