### ISSUE TITLE
Hidden Columns Removed in EF Core 6 RC 2 Scaffold

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#26329]
RC 1 of EF Core 6 scaffold did not run due to a bug in temporal table hidden field properties I think. We upgrade to RC 2 and now it seems hidden columns are removed from our models where before they were added. I see #8192 whereby it looks like the default behavior could be now to not scaffold hidden columns. However this change effects a ton of our models. Is there a way in scaffold to specify to include hidden columns by default? We would like to remain backward compatible we transition.

EF Core: 6.0.0-rc.2.21480.5
Microsoft Visual Studio Enterprise 2022 Preview
Version 17.0.0 Preview 5.0
VisualStudio.17.Preview/17.0.0-pre.5.0+31808.319
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA920
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.0.763.32329
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.763.32329
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.763.32329
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.4000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.0.763.32329
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.4000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.9.0
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   4.0.0-5.21501.19+8e1779e16298415843e85029d8b52a1ae9bb4c30
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service   2.6.4000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.4000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2150514+d9e17e7b7f06829e976f616716a987599c5c66e9
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62109.30190
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-5.21501.19+8e1779e16298415843e85029d8b52a1ae9bb4c30
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21472.3+f0b5108c92b92ba5ee440228aadba3bae79b43a3
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Web Compiler   1.13.004
Compiler for LESS, Sass and CoffeeScript files

**Comment by ErikEJ** [comment]
Hidden columns were ignored since EF Core 2. Are you sure the columns are actually defined as HIDDEN in your tables,?

**Comment by ajcvickers** [comment]
@chassq Currently temporal table period columns must be mapped to shadow properties. For now, you will likely need to use 5.0 to scaffold your database to get back to the prvious behavior. We will discuss possible ways forward here and get back to you.

/cc @maumar

**Comment by chassq** [comment]
Thank you @ajcvickers !
