### ISSUE TITLE
[Q] Average/Min/Max  and error message "Sequence contains no elements."

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#26376]
Hello,

EF 6.0.

I create tests for Average function and get strange error message "_Sequence contains no elements_."

EFCore query:
``` c#
var valueWithResult
  =db
    .testTable
    .Where(r => r.TEST_ID>(r.TEST_ID+1))
    .Average(x=>x.DATA);
```

SQL:
```sql
SELECT AVG(CAST("t"."COL_INTEGER" AS DOUBLE PRECISION))
FROM "TEST_MODIFY_ROW" AS "t"
WHERE "t"."TEST_ID" > ("t"."TEST_ID" + 1)
```

This SQL returns **one** record with NULL value.

So, sequence **has** element. And this element is NULL.

Maybe throw more useful error message like - "_Aggregate function <name> return a NULL value, which can't be translated to not null value for client code_" ?

**Comment by ajcvickers** [comment]
@dmitry-lipetsk This is by-design. The defined behavior of `Average` in LINQ is to throw if the input contains no elements. For consistency, we throw the same exception as LINQ to Objects.

**Comment by douglasg14b** [comment]
Is there conventional ways to elegantly handle this without much extra logic in these locations?

An SQL query to sum or average a query with no elements doesn't fail, it returns an expected result, EF Core's corollary does not.

**Comment by roji** [comment]
@douglasg14b I'm not sure what exactly you're asking. As @ajcvickers wrote above, EF's general goal is to have LINQ operators behave as they would when used in-memory (LINQ to objects), so the failure is by-design.
