### ISSUE TITLE
How to access the Shadow-ForeignKey-properties of an EntityEntry

### ISSUE THREAD

**Issue by NormanGiHu** [dotnet/efcore#26381]
Hi,
how can i access the Shadow-ForeignKey-properties of an EntityEntry?

For example, i want to know the propertyName which stores the foreign key of a Navigation Property (reference):
Ef core scaffolding is creating models from database-tables.
When in these tables a foreign key is defined, then a navigation property is created in the model of these tables.
If foreign key references to a primary key => good, the reference property gets the ForeignKey DataAnnotation with the name of the foreignkey property.

But when referencering to an alternate key then a Shadow property is created inside the "OnModelCreating" method of dbcontext
```C#             
           entity.HasOne(d => d.FirstModel)
                    .WithMany(p => p.SecondModelFirstModel)
                    .HasPrincipalKey(p => p.UniqueValues)
                    .HasForeignKey(d => d.FirstModelUniqueValues)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Name_of_the_FK");
```

The foreign key is stored as shadow property with "HasForeignKey" according to [https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key](url)
But how i must query dbcontext to access the property of "SecondModel", which stores the foreignKey referencing FirstModel?
Is it even possible, when only the name of the navigation property "FirstModel" is known?
I couldn't find an answer in [https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties](url)

I tried it with this:
```C#   
var entityFrameworkEntity = DbContext.Entry(SecondModel);
var referenceMetadata = entityFrameworkEntity.Reference("FirstModel")
                                                             .Metadata;
```
But in Metadata could't find info, what the foreignKey property is.

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
Something like this will give you the property metadata for the FK property:

```C#
var property = context.Model
    .FindEntityType(typeof(SecondModel))
    .FindNavigation(nameof(SecondModel.FirstModel))
    .ForeignKey
    .Properties
    .Single();
```

**Comment by ajcvickers** [comment]
@NormanGiHu If you are starting with an instance of `SecondModel`, then you're making things more difficult than they need be by looking up the metdata twice.  Your code can be shortened to:

```C#
var navigation = (INavigation)context.Entry(secondModel).Reference(propertyOfEntity).Metadata;
var fkName = navigation.ForeignKey.Properties.Select(p => p.Name).Single();
```
