### ISSUE TITLE
How can I measure a performance of queries executed with SplitQuery()

### ISSUE THREAD

**Issue by risogolo** [dotnet/efcore#26388]
How can I measure a performance of queries executed with SplitQuery(), so I will see overall measured time aggregated from all "subqueries", is it for instance possible to write some kind of an interceptor and how?

EF Core 5

**Comment by roji** [comment]
I don't think an interceptor helps here - database interceptors once again work at the level of a single DbCommand.

Note: if we implement batching for split queries (#10878), this gets resolved on its own, since all split queries would be sent as a single DbCommand.
