### ISSUE TITLE
RC2 Sqlite provider no longer clears temporary files on exit

### ISSUE THREAD

**Issue by ExtendedSpice** [dotnet/efcore#26422]
Since RC2 update scoped sqlite dbcontext no longer deletes *-shm and *-wal files on app exit.
Maybe I am missing some clean up behavior settings but it worked without apparent tweaks in previous versions.

Microsoft.EntityFrameworkCore.Sqlite version 6.0.0-rc.2.21480.5
Target framework: NET 6.0 preview

**Comment by ajcvickers** [comment]
@bricelam Ping; possible patch issue.

**Comment by bricelam** [comment]
As a workaround, you can add this to your application startup:

```cs
AppDomain.CurrentDomain.ProcessExit += (sender, e) =>
{
    SqliteConnection.ClearAllPools();
};
```

**Comment by ajcvickers** [comment]
FYI for those impacted by this issue: EF Core 6.0.1 is now [available from NuGet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/6.0.1).

**Comment by hippieZhou** [comment]
you can use this way

```bash
 if (dbContext.Database.GetDbConnection() is SqliteConnection conn)
{
    SqliteConnection.ClearPool(conn);
}
```
