### ISSUE TITLE
Non-nullable value comparer can't be applied on nullable type

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#26429]
sadly the above solution does not work anymore with RC2 for **Nullable** DateOnlys/TimeOnlys

```csharp
protected sealed override void ConfigureConventions(ModelConfigurationBuilder builder)
        {
            builder.Properties<DateOnly>()
                .HaveConversion<DateOnlyConverter, DateOnlyComparer>()
                .HaveColumnType("date");

            builder.Properties<DateOnly?>()
                .HaveConversion<NullableDateOnlyConverter, NullableDateOnlyComparer>()
                .HaveColumnType("date");
        }
```

I get the error message, that the "DateOnlyComparer" cannot be used for a nullable DateOnly property. It seems that the Nullable DateOnly conversion is completely ignored.

Because of that, I reverted my whole solution back to RC1.

Are there any changes known regarding this and how to solve that?

_Originally posted by @CleanCodeX in https://github.com/dotnet/efcore/issues/24507#issuecomment-947487900_

**Comment by ajcvickers** [comment]
FYI for those impacted by this issue: EF Core 6.0.1 is now [available from NuGet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/6.0.1).
