### ISSUE TITLE
Suggestions to making QueryIterationFailed a bit more useful

### ISSUE THREAD

**Issue by jespersh** [dotnet/efcore#26421]
# Issue description
If an exception happens in iteration of a result set, then the details of `public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)` are not very useful of tracking down the column or row this happened at since it appears to only log the contexttype that was used to generate the error https://github.com/dotnet/efcore/blob/dbc4314043394f658573e67ff5476948b369abe8/src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs#L215

The information that provides is like `System.InvalidCastException` "Unable to cast object of type 'System.DBNull' to type 'System.String'." from type ApplicationDbContext.

# Possible solutions
In addition to the ContextType I'd love to see the EntityType, Column name, and possibly row id or identifier of some kind or just the entity itself.

Much love to the EFCore team

**Comment by smitpatel** [comment]
Consider enabling sensitive data logging. By default we don't log those details as it may contain sensitive user data. See https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#getting-detailed-messages
