### ISSUE TITLE
[Bug]: Attach with `ValueGenerator` composite key not working in case of Relations (FK)

### ISSUE THREAD

**Issue by mseada94** [dotnet/efcore#26448]
## Setup
- Two entities (Book, Author) have one-to-many relation with a composite foreign key. (One Author Has Many Books)
- Single entity (Student) has no relations.
- One of the key properties is generated using custom `ValueGenerator<Guid>`. (`TenantId`)

## Error and notes
- When trying to attach the `book` entity with the `TenantId` property unset, The value will be generated correctly but the entity will be attached as a new **Added** entity.
- This behavior is not the same when the entity has no relations like the `Student` entity in this sample
- When trying to attach the entity (student) with the `TenantId` property unset, The value will be generated correctly and the entity will be attached as **Unchanged** entity.

Code Sample (Console App) >> `attach-demo branch`
https://github.com/mohamed-seada-1994/EFCore-ValueGenerator-Bug-Sample/tree/attach-demo
> Note: this sample use  the workaround mentioned in #26332

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Win10
IDE: Visual Studio 2019 16.11.5

**Comment by ajcvickers** [comment]
@eation All of that seems by-design, except possibly changing the handling of stable generated values.

@mohamed-seada-1994 If you have a shadow property that is part of a primary key, then it needs to be set explicitly to the correct value before attaching. This is one reason (of many) not to put PKs into shadow state. If you're seeing some behavior that involves a FK that is not also part of a PK, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
Note from triage: generation of a stable value should not be enough to treat an entity as new.

**Comment by mohamed-seada-1994** [comment]
@ajcvickers Is there any workaround I could use to set/generate shadow property explicitly before update/attach?

**Comment by eation** [comment]
@mohamed-seada-1994 I was make a sample fix for #6999 on [this fork](https://github.com/eation/efcore/tree/release/5.0), it work for this test [ConcurrencyValueGeneratorTest](https://github.com/eation/ConcurrencyValueGeneratorTest) current in efcore5,but need more test in efcore6, maybe u can test it.
ps: **Attach(entity)** has a bug, it not tracked any entity, ChangingCount or ChangedCount is 0, so u can replace with **Add()** or **Update()**. To set/generate a key property, need to set **[DatabaseGenerated(DatabaseGeneratedOption.None)]** dataannotations and then use custom ValueGenerator to avoid **Identity Insert OFF** error at this time.

@ajcvickers

**Comment by ajcvickers** [comment]
@mohamed-seada-1994 `TenantId` is part of the PK. It has a generated value. This means the state of the entity should be `Added`. EF Core 6.0 has the correct behavior here. Other than what has been discussed with stable values above, this is behaving as designed.

I should point out again that using value generators to generate primary key values that _are not new_ (i.e. are already stored in the database) is not something EF Core was designed for. It's not something I have ever seen anyone do before this issue. Stable keys potentially allows for this, again as discussed above. The best workaround is to not used a value generator to set values that already exist in the database.

**Comment by mohamed-seada-1994** [comment]
@eation I think you solution is related to generate values on update before saving the changes, It's not going to work in case of autogenerated PK before attach, update.

---
@ajcvickers `ValueGenerator` is designed to work on `Add` not on `Update`.
Entity with **Shadow PK** `Attach` and `Update` behaviors were not considered on design, and should be avoided if possible.

> The use case I have requires using **Shadow Property as PK**.

`GeneratesStableValues` option is a feature that allows for **Shadow property** to be used as **primary key**, this feature should support a stable solution to all possible operations not just adding such as (searching, updating) this added entity .
This require a way to set the value of the shadow property with 2 possible situations:
1- `ValueGenerator` generate a consistence value based on the current context (could be a scoped option or constant) so it could be used with search and update.
2- `ValueGenerator` generate a random value or sequence which require an explicit way to set the **Shadow Key** before search and update.

---

I found this workaround to set the value of the shadow property before `Attach` or `Update`, which work fine for EFCore 5 and EFCore 6.

```cs
var generatedTenantId = Guid.Parse("98D06A82-C691-4988-EA39-08D98E2C8D8F");

var entry = context.Entry(book);
entry.Property("TenantId").OriginalValue = generatedTenantId;
entry.Property("TenantId").CurrentValue = generatedTenantId;
entry.Property("TenantId").IsModified = false;
                
book.Title = "Modified!";
var attachedEntry = context.Books.Update(book); // attachedEntry.Status >> "Modified"
context.SaveChanges();
``` 
With this workaround I have to set the shadow property on before calling `Update`, `Attach`.
The shadow property value should be resolved from `Request Context` as a scoped option, Is there a way to enforce this behavior implicitly using `ValueGenerator` or custom `DbContext` Property  without changing the caller code?
