### ISSUE TITLE
Query: enable temporal tables for table splitting scenarios

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#26469]
Currently we block temporal tables for table splitting scenarios (owned entities). We could enable it as long as all entities from the table are marked as temporal and all their periods are the same. 

related to https://github.com/dotnet/efcore/issues/26451

**Comment by alienwareone** [comment]
Temporal tables doesn't work with **"same table / complex type" owned entities**.
`System.InvalidOperationException: 'Temporal tables are not supported for table splitting scenario. Table: '{TableName}'.'`
Also in **same table** scenarios there shouldn't be a need for adding redundant "PeriodStart"and "PeriodEnd" columns.

**Comment by ajcvickers** [comment]
Note for triage: reconsider servicing. (Additional internal request received.)

**Comment by Badea741** [comment]
@maumar 
This can't be enabled in EF 6 with owned entity types even if configuring them with the same period
```C#
modelBuilder.Entity<Customer>(customer =>
        {
            customer.ToTable("Customers", t => t.IsTemporal(x =>
            {
                x.UseHistoryTable("CustomersHistory");
                x.HasPeriodStart("PeriodStart");
                x.HasPeriodEnd("PeriodEnd");
            }));
            customer.Property<DateTime>("PeriodStart").HasColumnName("PeriodStart");
            customer.Property<DateTime>("PeriodEnd").HasColumnName("PeriodEnd");
            customer.OwnsOne(x => x.CustomerDetail, customerDetail =>
            {
                customerDetail.ToTable("Customers", t => t.IsTemporal(x =>
                {
                    x.UseHistoryTable("CustomersHistory");
                    x.HasPeriodStart("PeriodStart");
                    x.HasPeriodEnd("PeriodEnd");
                }));
                customerDetail.Property<DateTime>("PeriodStart").HasColumnName("PeriodStart");
                customerDetail.Property<DateTime>("PeriodEnd").HasColumnName("PeriodEnd");
            });
        });
```
and that's the error message
![image](https://github.com/dotnet/efcore/assets/63262064/2239b49a-3acf-4015-978a-491d6d7b34e1)
