### ISSUE TITLE
TagWith/TagWithCallSite with lazy loading tags only first query

### ISSUE THREAD

**Issue by romfir** [dotnet/efcore#26474]
When using ```.TagWith()``` and ```TagWithCallSite()``` only first query is tagged, other queries from lazy loaded properties are not tagged.

```C#
var e = _context.A.TagWith("my special tag").First();
var zxc = e.B;
```

sql:
```sql
-- my special tag

SELECT TOP(1) ***removed***
GO

-- Region Parameters
-- @__p_0='101118'
-- EndRegion
SELECT ***removed***
GO


```

EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0/6.0

**Comment by ajcvickers** [comment]
Note from triage: closing as by-design. Lazy loading generates separate queries that are only tangentially related to any previous queries.
