### ISSUE TITLE
Insert record sequentially in DB without identity on PK

### ISSUE THREAD

**Issue by Uraharadono** [dotnet/efcore#26480]
I asked this on SO as well, unfortunately I didn't get any number of notable responses: 
https://stackoverflow.com/questions/69750232/ef-core-insert-record-sequentially-in-db-without-identity-on-pk

**Disclaimer:** This question is regarding "modernization" of almost 17 years old system. ORM that was used 17 years ago required that PK's don't use **Identity**.
I know how bad it is, and I can't change anything regarding this.  

So I have (simplified) following table in database:

    CREATE TABLE [dbo].[KlantDocument](
    	[OID] [bigint] NOT NULL,
    	[Datum] [datetime] NOT NULL,
    	[Naam] [varchar](150) NOT NULL,
    	[Uniek] [varchar](50) NOT NULL,
    	[DocumentSoort] [varchar](50) NULL,
     CONSTRAINT [PK_KlantDocument] PRIMARY KEY CLUSTERED 
    (
    	[OID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
    ALTER TABLE [dbo].[KlantDocument] CHECK CONSTRAINT [FK_KlantDocument_Klant]
    GO

As you can see, table doesn't have **Identity** set on PK, so it has to be inserted manually.

Project is being rebuilt in **Web Api .Net Core 5**, that is going to do all of the CRUD operations.
It is using **EF Core** as ORM, and it is agreed that **Unit of Work** pattern is going to be used here (***please do keep reading, UoW is not issue here***). 

*For those curious or for what it's worth, you can take a look at it here (https://pastebin.com/58bSDkUZ) ( this is by no means full UoW, just partially and without comments).*

Controller Action:

    [HttpPost]
            [Route("UploadClientDocuments")]
            public async Task<IActionResult> UploadClientDocuments([FromForm] ClientDocumentViewModel model)
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelStateExtensions.GetErrorMessage(ModelState));
    
                var dto = new ClientDocumentUploadDto
                {
                    DocumentTypeId = model.DocumentTypeId,
                    ClientId = model.ClientId,
                    FileData = await model.File.GetBytes(),
                    FileName = model.File.FileName, // I need this property as well, since I have only byte array in my "services" project
                };
    
                var result = await _documentsService.AddClientDocument(dto);
                return result ? Ok() : StatusCode(500);
            } 

When I am inserting record I am doing it like so: 

    // Called by POST method multiple times at once
    public async Task<bool> AddClientDocument(ClientDocumentUploadDto dto)
    {
        try
        {
            var doc = new KlantDocument
            {
    		/* All of the logic below to fetch next id will be executed before any of the saves happen, thus we get "Duplicate key" exception. */
                // 1st try to fetch next id
                // Oid = _uow.Query<KlantDocument>().OrderByDescending(s => s.Oid).First().Oid + 1,
                // 2nd try to fetch next id
                // Oid = _uow.Query<KlantDocument>().OrderBy(s => s.Oid).Last().Oid + 1,
                // 3rd try to fetch next id
                // Oid = await _uow.Query<KlantDocument>().OrderBy(s => s.Oid).AsNoTracking().Select(s => s.Oid).LastAsync() + 1,
                // 4th try to fetch next id
                // Oid = _uow.Query<KlantDocument>().OrderBy(s => s.Oid).AsNoTracking().Select(s => s.Oid).Last() + 1,
                // 5th try to fetch next id
                // Oid = (_uow.Query<KlantDocument>().OrderBy(s => s.Oid).AsNoTracking().Max(s => s.Oid) + 1),
                Naam = dto.FileName,
                DocumentSoort = dto.DocumentTypeId,
                Datum = DateTime.Now,
                Uniek = Guid.NewGuid() + "." + dto.FileName.GetExtension()
            };
    
            _uow.Context.Set<KlantDocument>().Add(doc); // Does not work
            _uow.Commit();
        }
        catch (Exception e)
        {
            _logger.Error(e);
            return false;
        }
    }

I get **"Duplicate key" exception** because 2 of the records are overlapping when inserting. 

I have tried to wrap it into the transaction like so:

    _uow.ExecuteInTransaction(() => { 
            var doc = new KlantDocument
            {
    		/* All of the logic below to fetch next id will be executed before any of the saves happen, thus we get "Duplicate key" exception. */
                // 1st try to fetch next id
                // Oid = _uow.Query<KlantDocument>().OrderByDescending(s => s.Oid).First().Oid + 1,
                // 2nd try to fetch next id
                // Oid = _uow.Query<KlantDocument>().OrderBy(s => s.Oid).Last().Oid + 1,
                // 3rd try to fetch next id
                // Oid = await _uow.Query<KlantDocument>().OrderBy(s => s.Oid).AsNoTracking().Select(s => s.Oid).LastAsync() + 1,
                // 4th try to fetch next id
                // Oid = _uow.Query<KlantDocument>().OrderBy(s => s.Oid).AsNoTracking().Select(s => s.Oid).Last() + 1,
                // 5th try to fetch next id
                // Oid = (_uow.Query<KlantDocument>().OrderBy(s => s.Oid).AsNoTracking().Max(s => s.Oid) + 1),
                Naam = dto.FileName,
                DocumentSoort = dto.DocumentTypeId,
                Datum = DateTime.Now,
                Uniek = Guid.NewGuid() + "." + dto.FileName.GetExtension()
            };
    
            _uow.Context.Set<KlantDocument>().Add(doc); // Does not work
            _uow.Commit();
    });

and it does not work. I still get "Duplicate key" exception. 

From what I know, **shouldn't EF by default lock database until transaction is complete?** 

I tried to manually write insert SQL like so:

    using (var context = _uow.Context)
    {
        using (var dbContextTransaction = context.Database.BeginTransaction())
        {
            try
            {
                // VALUES ((SELECT MAX(OID) + 1 FROM KlantDocument), -- tried this also, but was not yielding results
                var commandText = @"INSERT INTO KlantDocument
                (
                 OID
                ,Datum
                ,Naam
                ,Uniek
                ,DocumentSoort
                )
                VALUES (
                        (SELECT TOP(1) (OID + 1) FROM KlantDocument ORDER BY OID DESC),
                        @Datum,
                        @Naam,
                        @Uniek,
                        @DocumentSoort
                )";
                var datum = new SqlParameter("@Datum", DateTime.Now);
                var naam = new SqlParameter("@Naam", dto.FileName);
                var uniek = new SqlParameter("@Uniek", Guid.NewGuid() + "." + dto.FileName.GetExtension());
                var documentSoort = new SqlParameter("@DocumentSoort", dto.DocumentTypeId ?? "OrderContents");
    
                context.Database.ExecuteSqlRaw(commandText, datum, naam, uniek, documentSoort);
                dbContextTransaction.Commit();
            }
            catch (Exception e)
            {
                dbContextTransaction.Rollback();
                return false;
            }
        }
    }

Same thing. 

I did a lot research to try to tackle this issue:

 1. https://stackoverflow.com/questions/65234534/net-core-executesqlraw-last-inserted-id - solutions either don't work, or work only with identity columns
 2. I got idea to use **SQL OUTPUT** variable, but issue is that it's really hard or even impossible to achieve, feels hacky and overall if managed, there is no guarantee that it will work. As seen here: https://stackoverflow.com/questions/5558582/sql-server-output-clause-into-a-scalar-variable and here https://stackoverflow.com/questions/12566493/how-can-i-assign-inserted-output-value-to-a-variable-in-sql-server/12566529

As noted above, ORM at the time did some magic where it did sequentially insert records in database and I would like to keep it that way. 

Is there any way that I can achieve sequential insert when dealing with given scenario?

**Comment by Uraharadono** [comment]
Hello @roji, 
Sorry for late reply. I was confused as hell why is this happening, then I took a bit time to rest over the weekend. Today I created **POCO solution** which replicates this behavior. 
You can find it here: https://github.com/Uraharadono/RojiSequencePoco



Setup is as follows:

1. Create local DB with name **BloggingDb**
2. **Package Manager Console** -> `Update database `
3. Run project


I have setup 3 ways to try to insert new Blog record, and every one of 3 fails:

1. Using **Unit of work context**

```
                var ctx = _uow.Context as Net5BoilerplateContext;
                ctx.Blogs.Add(new() { Url = dto.Url });
                ctx.SaveChanges(); // doesn't work, either
```

produces:

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Blogs] ([Oid], [Url])
VALUES (@p0, @p1);
',N'@p0 bigint,@p1 nvarchar(4000)',@p0=0,@p1=N'AddBlogUsingUoWContext'

```
2.  Using **manually created context**: 
```
                await using var ctx = Net5BoilerplateContext.Create("Server=.;Database=BloggingDb;Trusted_Connection=True;MultipleActiveResultSets=True;", 1);
                // ctx.Database.EnsureDeletedAsync();
                // await ctx.Database.EnsureCreatedAsync();

                ctx.Blogs.Add(new() { Url = dto.Url });
                await ctx.SaveChangesAsync();
```
produces:
```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Blogs] ([Oid], [Url])
VALUES (@p0, @p1);
',N'@p0 bigint,@p1 nvarchar(4000)',@p0=0,@p1=N'AddBlogUsingProperContext'
```


3. Using my **Unit of Work**:

```
                var dbBlog = new DbContext.Entities.Blog
                {
                    Url = dto.Url,
                };
                _uow.Context.Set<DbContext.Entities.Blog>().Add(dbBlog);
                _uow.Commit();
```

produces:

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Blogs] ([Oid], [Url])
VALUES (@p0, @p1);
',N'@p0 bigint,@p1 nvarchar(4000)',@p0=0,@p1=N'AddBlogUsingUoW'
```


I don't know what the deal is, as in 2nd migration there is `defaultValueSql: "NEXT VALUE FOR BlogSeq",`. 
If I create **both Sequence and set default value of the Blog PK to sequence in single migration, it works**.

**Comment by roji** [comment]
@Uraharadono you have `[DatabaseGenerated(DatabaseGeneratedOption.None)]` on the Blog.Oid property. Although the database column indeed has the proper default value SQL (`NEXT VALUE FOR BlogSeq`), DatabaseGeneratedOption.None tells EF Core that there is no value generation configured. This makes EF Core always send whatever value is contained in the Blog.Oid, which is zero if it's unset. If you remove this attribute, things should start working.

**Comment by Uraharadono** [comment]
@roji Thanks a lot for coming back to me once again. Can I just ask another thing: 
Is this same behavior if we have `ValueGeneratedNever ` using fluent api?


Or to put more perspective and sense into this whole mess of a question. 

My code first entities are created using EF Scaffold command on existing (17 y.o. DB), and it generated this code for this table:


```
modelBuilder.Entity<KlantDocument>(entity =>
            {
                entity.HasKey(e => e.Oid);

                entity.ToTable("KlantDocument");

                entity.Property(e => e.Oid)
                    .ValueGeneratedNever()
                    .HasColumnName("OID");

                entity.Property(e => e.Datum).HasColumnType("datetime");

                entity.Property(e => e.DocumentSoort)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Naam)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Uniek)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.GebruikerNavigation)
                    .WithMany(p => p.KlantDocuments)
                    .HasForeignKey(d => d.Gebruiker)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_KlantDocument_Gebruiker");

                entity.HasOne(d => d.KlantNavigation)
                    .WithMany(p => p.KlantDocuments)
                    .HasForeignKey(d => d.Klant)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_KlantDocument_Klant");
            });
```

So it has automatically generated `.ValueGeneratedNever()` part.
