### ISSUE TITLE
Related property key value resets when attaching a disconnected entity.

### ISSUE THREAD

**Issue by Metritutus** [dotnet/efcore#26490]
## The Issue

I have encountered a peculiar problem where performing `DbContext.Attach()` on a disconnected entity was seemingly resetting one of the property values.  In addition, this value reset seems to happen without the property's set accessor being invoked.

Also, [according to the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.attach?view=efcore-5.0#Microsoft_EntityFrameworkCore_DbContext_Attach__1___0_), _"Generally, no database interaction will be performed until SaveChanges() is called."_, yet it does seem to be retrieving the original value somehow.

I struggled to try and understand what was going on, and eventually worked to step into Entity Framework Core's code to try and see if I could see what was happening.  As a result of this and a bit of trial-and-error, I was able to replicate the problem.

It looks like it's something to do with the navigation properties and Entity Framework Core's 'graph traversal', however I confess that although I stepped into that code, I currently lack sufficient knowledge to be able to understand it.  The stuff's complicated!

Anyway, below is the example project that demonstrates this issue.

### The code

Code written to specifically replicate this may be found [here](https://github.com/Metritutus/EFCoreAttachBugTest002/).

Simply run the project and observe the output.

In particular, note the final chunk of output:
```
Setting mystery type to 2 (Mystery2)
Example before attach: Example - Id: 1, IntegerValue: 30, MysteryType: 2 (Mystery2)
Example after attach: Example - Id: 1, IntegerValue: 30, MysteryType: 1 (Mystery1)
Value has been reset!?
```
It shows that MysteryId was set to `2`, but after `Attach()` was called the property value was reset to its original value of `1`.  The line producing this output is [here].(https://github.com/Metritutus/EFCoreAttachBugTest002/blob/1ade6ffe39947c4626b56a9700ed8dd9bfcabd8e/Program.cs#L82)

If you comment out the `Holder` navigation property on [line 10](https://github.com/Metritutus/EFCoreAttachBugTest002/blob/1ade6ffe39947c4626b56a9700ed8dd9bfcabd8e/Models/Example.cs#L10) in the `Example` model, the behaviour does not occur.

This looks to me like a bug, but it's always possible this is by design in some way.  If this is the case, can someone explain what's going on here and how to expect/anticipate this behaviour?

### Provider and version information

EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.1 (although I have also tested it in .NET 5 and seen the same behaviour).
Operating system: Windows 21H1 (OS Build 19043.1237)
IDE: Visual Studio 2019 16.11.3

**Comment by ajcvickers** [comment]
@Metritutus The graph being attached as inconsistent relationships between the entities. This is the EF model:

```
Model: 
  EntityType: Example
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      HolderId (no field, Nullable<int>) Shadow FK Index
      IntegerValue (Nullable<int>)
      MysteryTypeId (Nullable<int>) FK Index
    Navigations: 
      Holder (Holder) ToPrincipal Holder Inverse: Examples
      MysteryType (MysteryType) ToPrincipal MysteryType Inverse: Examples
    Keys: 
      Id PK
    Foreign keys: 
      Example {'HolderId'} -> Holder {'Id'} ToDependent: Examples ToPrincipal: Holder ClientSetNull
      Example {'MysteryTypeId'} -> MysteryType {'Id'} ToDependent: Examples ToPrincipal: MysteryType ClientSetNull
    Indexes: 
      HolderId 
      MysteryTypeId 
  EntityType: Holder
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
    Navigations: 
      Examples (ICollection<Example>) Collection ToDependent Example Inverse: Holder
    Keys: 
      Id PK
  EntityType: MysteryType
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Name (string)
    Navigations: 
      Examples (ICollection<Example>) Collection ToDependent Example Inverse: MysteryType
    Keys: 
      Id PK
```

And this is the graph of entities being attached:

![image](https://user-images.githubusercontent.com/1430078/139832729-bb76ec55-69c9-4061-b966-41694f17bd50.png)

- example1 (being attached) references mysteryType2, indicating that example1 is related to mysteryType2
- However, mysteryType2 has an empty collection of examples, indicating that it is not related to example1
- example2 references mysteryType1, and mysteryType1 has a collection of examples that contains both example1 and example2, indicating that example1 is related to mysteryType1

It is important to ensure the relationships are in a consistent state before attaching, otherwise the behavior is undefined and will depend on which relationship is discovered first in the graph.

**Comment by Metritutus** [comment]
Okay, I believe I understand, and what you are saying does make sense.

To follow on from your response, in terms of the creation of navigation properties, etc, do you have any recommendations on how best to avoid this scenario?  Am I expected to just set the navigation property to `null` when changing it to another entity?  Is there any documentation with guidance on this?  I did check the article in disconnected entities before in relation to the behaviour I was seeing, but it [seemed to primarily speak of the issues relating to duplicate entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#working-with-graphs), rather than a mismatch of collections containing other entities.

My scenario does not feel like it is particularly complicated or outlandish, so I presume that my approach must be incorrect to have led me to this point.

Finally, how did you produce the output shown in your response in order to identify this?  I was using the Watch window myself but missed the collection content mismatch.

**Comment by ajcvickers** [comment]
@Metritutus Some things to consider:
* Only change navigations or only change foreign key values, not both
* Attach before making changes so that the attached graph is always consistent, and EF can respond to each change made
* Query for the current graph, and then apply changes to that graph
* Or if all else fails, make sure that when one end of a relationship is changed, then the other end is also changed before attaching the graph.

I just used the debugger view in the IDE I use. Most IDEs have similar views to this, but what you get exactly will depend on what your IDE supports.

**Comment by Metritutus** [comment]
With regards to the third point, how would I query for the current graph?  Or is this just a way of saying to get the entity from the database, eg `Examples.FirstOrDefault(e => e.Id == 1)`?

With regards to the mistake I made, based on your first point, it looks like the mistake was to manually set the navigation property then.

To follow on with your first point though, "Only change navigations or only change foreign key values, not both", only changing the navigation property and not the key value still results in the same effect.  ie:

```csharp
            //example.MysteryTypeId = mysteryTypeId;
            example.MysteryType = mysteryType;
```

Based on your previous explanation of the problem, this would seem to be correct (ie undefined behaviour, graph traversal resolves whatever it hits first), right?  If so, did I misunderstand what you meant by changing only the navigation property?

**Comment by ajcvickers** [comment]
@Metritutus 

> Or is this just a way of saying to get the entity from the database, eg Examples.FirstOrDefault(e => e.Id == 1)?

Yes.

> "Only change navigations or only change foreign key values, not both", only changing the navigation property and not the key value still results in the same effect.

The navigations on either side of the relationship are still in conflict. I wasn't trying to say that only changing one or the other would solve the problem, only that it helps to not put relationships into an inconsistent state.
