### ISSUE TITLE
[Minor/Convenience] Creating classes from model snapshot.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#26492]
When creating models with high degree of encapsulation (yes, DDD), we end up with classes which can hardly be used for UI queries (Aggregate Root usually hides all its related entities).

Now we have to scaffold DbContext from database.
It would be nice, if we could build read model from model snapshot of plain classes with 1-to-1 relationship to DB table.

**Comment by ajcvickers** [comment]
@voroninp I've read this several times over the past few days, and I really have no idea what it is that you are asking for. Could you explain in more detail?

**Comment by voroninp** [comment]
Ok...

I define aggregate: aggregate root, entities, owned entities. I try to encapsulate as much as possible, so developer sees mostly methods, state is mapped to private fields. You cannot do `A.B.C.Items`.

Fetching aggregates for updates works fine: read it, call some methods, save changes of the aggregate.
 
But queries become a problem. We do not need that level of encapsulation.  It's ok to do joins between tables which belong to different aggregates.
So what I need is to be able to generate DTOs from model snapshot. One table = one POCO (ideally immutable record) with all navigational properties to other tables.

Now I have to define them myself with `ExcludeFromMigrations`, or I have to use scaffolding creating `ReadOnlyDbContext` from the database  which I get after migrations are applied:

1. Define Aggregates
2. Setup mappings
3. Create migration
4. Apply migration
5. Scaffold `ReadOnlyDbContext` with `--force`

What I'd like to have:
1. Define Aggregates
2. Setup mappings
3. Create migration? Or maybe not even needed.
3. Generate read models.

**Comment by ajcvickers** [comment]
@voroninp This is not something we plan to implement. Scaffolding from the database seems sufficient.
