### ISSUE TITLE
RevEng command dependencies

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2649]
Am I correct in assuming that the PMC Reverse-Engineer command only is available/functional in VS 2015? ( @lajones )

**Comment by bricelam** [comment]
It should work in any VS where NuGet 3 and PowerShell 3 are installed.

**Comment by ErikEJ** [comment]
I thought it depended on Roslyn...

**Comment by bricelam** [comment]
Roslyn should be distributed with it as a NuGet dependency

**Comment by ErikEJ** [comment]
Thanks!
