### ISSUE TITLE
How to create custom EF Core extension?

### ISSUE THREAD

**Issue by bezchastnyi** [dotnet/efcore#26500]
Hi everyone 
I want to extend EF core with custom bulk update that update query with expression that explain what have been changed

I found nothing about this question 
Can somebody help with it ?

**Comment by roji** [comment]
@bezchastnyi you'll have to provide a bit more detail than that. SQL bulk update is a feature which is [planned](#795) for EF Core 7.0, and in the meantime, various 3rd-party extensions exist for that (see the [extensions page](https://docs.microsoft.com/en-us/ef/core/extensions/). However, I'm not sure what you mean with "update query with expression that explain what have been changed".

**Comment by bezchastnyi** [comment]
So, example:

```
Expression<Func<T, T>> updateEx = x => new T
{
    Field1 = value1,
    Field2 = value2,
};

var result = await this._dbContext.Table.Where(x => x.Field3 == value3)
                   .**BulkUpdateAsync**(updateEx, cancellationToken);
```


and this **BulkUpdateAsync** that I need -> have to update all lines in DB with updateEx expression
and this **BulkUpdateAsync** I must implement

**Comment by roji** [comment]
@bezchastnyi as I wrote above, there are already extensions which accomplish that, and native support for it is planned in EF Core 7.0. I would recommend against developing this in another new extension.
