### ISSUE TITLE
Defect: Select after projection behaves unexpectedly in Azure Cosmos DB provider

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/efcore#26517]
I have a simple model with a GUID as the key. 

A blog:

```csharp
public class Blog
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string? Title { get; set; }
    public string? Description { get; set; }
    public Uri? Link { get; set; }
    public Uri? Image { get; set; }

    public IList<Post> Posts { get; set; } = new List<Post>();
}
```

Has several posts:

```csharp
public class Post
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string? Title { get; set; }
        public string? Description { get; set; }
        public Uri? PermaLink { get; set; }

        public Blog? Blog { get; set; }
    }
```

With a very simple DbContext:

```csharp
public class BlogContext : DbContext
{
    public BlogContext()
    {
    }

    public BlogContext(DbContextOptions<BlogContext> opts) : base(opts)
    {
    }

    public DbSet<Blog> Blogs { get; set; } = null!;
}
```
If you filter _before_ projecting, like this:

```csharp
public async Task<Blog> GetBlogAsync(Guid blogId)
{
    using var ctx = context.CreateDbContext();
    return await ctx.Blogs
        .Where(b => b.Id == blogId)
        .Select(b => new Blog
        {
            Id = blogId,
            Description = b.Description,
            Image = b.Image,
            Link = b.Link,
            Title = b.Title,
        })
        .FirstOrDefaultAsync();
}
```
The filter works correctly. However, if you reverse them like this:

```csharp
public async Task<Blog> GetBlogAsync(Guid blogId)
{
    using var ctx = context.CreateDbContext();
    return await ctx.Blogs
        .Select(b => new Blog
        {
            Id = blogId,
            Description = b.Description,
            Image = b.Image,
            Link = b.Link,
            Title = b.Title,
        })
        .Where(b => b.Id == blogId)
        .FirstOrDefaultAsync();
}
```
The result is always the first blog entry found, regardless of what's passed. The filter appears to be ignored. 

**Expected behavior:** the filter should work. If the provider doesn't support filtering after projectios, it should throw an appropriate exception or generate a warning. 

### Include provider and version information

EF Core version: 6.0.0-rc2
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 6
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.0 preview 7)

**Comment by smitpatel** [comment]
The first query - filter is written against the database blog. So it does find the blog which is Id same as blogId.
The second query - filter is written against the constructed blog, so b.Id is actually same as `blogId`. so result of filter is always true hence filter is redundant and would be same as not there. This would also give first result from server as result.
