### ISSUE TITLE
Why the order of adding entities is not preserved?!

### ISSUE THREAD

**Issue by PatryxCShark** [dotnet/efcore#26524]
I have a problem with the order of adding entities and generating primary key. I tested it using Sql Server and Sqlite.
I cannot find the right answer how to force EF to preserve the order with I added entities before SaveChanges.
In core 2.2 everything works as expected and when I moved to .NET 5.0 I have a big problem with it.
Beofre the behaviour was logic, now I cannot find a "key" why such changes have been done.

How to resolve the problem? I don't want to use extra transactions etc. because I have a lot of code in my app.

My code:

1. _User_ class:
```
    public class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
    }
```

2. _UserConfig_, when I have Id as primary key with _ValueGeneratedOnAdd_.
```
    internal class UserConfig : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
        {
            builder.HasKey(u => u.Id);
            builder.Property(u => u.Id).ValueGeneratedOnAdd();
            builder.Property(u => u.Login).IsRequired();
            builder.HasIndex(u => u.Login).IsUnique();
        }
    }
 ```  
 
 3, Problem with the order and generated id:
 
 ```
            var user1 = new User
                { Login = "UserA" };
            var user2 = new User
                { Login = "UserB"};

            _context.Users.Add(user1);
            _context.Users.Add(user2);

            _context.SaveChanges();

            var users = _context.Users.ToList();
```
 
**Result:**

User1 ("UserA") has Id = 2
User2 ("UserB") has Id = 1

**Expected result** (as it was in core 2.2):

User1 ("UserA") has Id = 1
User2 ("UserB") has Id = 2
 

Provider and version information:

EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer / Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5.0
Operating system:
Visual Studio 2019 16.11

Thanks you for helping.

**Comment by ajcvickers** [comment]
@PatryxCShark No version of EF Core (or EF for that matter) has ever preserved the order that entities are added to the context. This is because a) the internal data structures are not setup to preserve this order and doing so would add overhead, and b) SaveChanges needs to define the order of insertions anyway to ensure database constraints are not violated. If the order was the same in 2.2, then this was just by chance.

**Comment by roji** [comment]
To add to @ajcvickers's answer above, `_context.Users` is a DbSet which roughly represents the database table; in the database itself, there is no ordering for the rows, and you must specify ordering yourself when querying (e.g. `_context.Users.OrderBy(u => u.Id)`.

**Comment by PatryxCShark** [comment]
As I know OrderBy Key is default one.

**Comment by ajcvickers** [comment]
@PatryxCShark There is no default ordering. See this SO post: https://stackoverflow.com/questions/20050341/when-no-order-by-is-specified-what-order-does-a-query-choose-for-your-record#:~:text=With%20SQL%20Server%2C%20if%20no%20ORDER%20BYis%20specified%2C,ORDER%20BY%2C%20make%20no%20assumptions%20about%20the%20order. It also has links to blog posts by SQL architects reiterating that there is no ordering.
