### ISSUE TITLE
EfCore incorrect SQL when altering column with type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#26523]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EfCore-incorrect-SQL-when-altering-colum/1563983)._

---
[severity:I'm unable to use this version]
Hi, this is in MSSQL. Don't know if in other providers the same could be reproduced.
Create simple model with some decimal property like:

```
public class Model
{
    public int Id {get; set;}
    public decimal Value {get;set;}
    public decimal Value2 {get;set;}
}
```

And do some configuration like:

```
builder. Property(x => x.Value). IsRequired();
builder. Property(x => x.Value2). IsRequired();
```

Create migration and update database.

Now change configuration to:

```
builder. Property(x => x.Value). IsRequired()
    . HasColumnType("int");

builder. Property(x => x.Value2). IsRequired()
    . HasColumnType("double")
    . HasPrecision(4);
```

Now create a migration and try to update database. You will get an error:

Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var0 sysname;
SELECT @var0 = [d]. [name]
FROM [sys]. [default_constraints] [d]
INNER JOIN [sys]. [columns] [c] ON [d]. [parent_column_id] = [c]. [column_id] AND [d]. [parent_object_id] = [c]. [object_id]
WHERE ([d].[ parent_object_id] = OBJECT_ID(N'[BatchCompositionItems]') AND [c]. [name] = N'VatRatePercent');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [BatchCompositionItems] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [BatchCompositionItems] ALTER COLUMN [VatRatePercent] double(4,2) NOT NULL;
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '('.

---
#### Feedback Bot on 10/27/2021, 03:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by roji** [comment]
`double` is not a valid type name in SQL Server, you are probably looking for [`decimal`](https://docs.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-ver15) or [`float`](https://docs.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-ver15).
