### ISSUE TITLE
Change in behavior in EntityTypeExtensions FullName betweeen 5.x and 6.x

### ISSUE THREAD

**Issue by mhartvig** [dotnet/efcore#26543]
Hi,

In EF 5.x the method FullName() found in https://github.com/dotnet/efcore/blob/release/5.0/src/EFCore/Extensions/EntityTypeExtensions.cs#L344 returned the DisplayName of the entity, in 6.x the method has been marked Obsolete and points to the property "Name". However, the functionality of function has changed, from displaying the display name to now return the fully qualified name https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Extensions/EntityTypeExtensions.cs#L28

The property "Name" also returns the fully qualified name, the function DisplayName() returns what the old "FullName()" did. Is this intended?

- Martin

**Comment by ajcvickers** [comment]
@mhartvig We discussed this, but based on the way FullName was intended to be used, Name is the more appropriate redirection. However, if you want the display name, then by all means use `DisplayName`.
