### ISSUE TITLE
Add embedded READMEs to NuGet packages

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#26556]
See:

* [Introducing the New NuGet.org Package Details Page](https://devblogs.microsoft.com/nuget/introducing-the-new-nuget-org-package-details-page/)
* [Sample Microsoft.EntityFrameworkCore readme](https://dev.nugettest.org/packages/loic.dotnet.efcore)
* [Documentation for PackageReadme](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)

**Comment by loic-sharma** [comment]
Let us know if you need any help at all! /cc @chgill-MSFT

**Comment by ajcvickers** [comment]
Assigning to @bricelam, @JeremyLikness, and myself. If one of you starts work on this, then please let the others know. Would be good to get in by the 15th for 6.0.1, but not critical.
