### ISSUE TITLE
Entity temporary values not being generated client side by EF

### ISSUE THREAD

**Issue by demian-floreani** [dotnet/efcore#26567]
I am currently facing an issue where adding a new entity to the context does not generate a local temporary ID value to link the entity to another entity before calling SaveChanges().

The behavior that I am seeking is defined here: https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations

> Depending on the database provider being used, values may be generated client side by EF or in the database. If the value is generated by the database, then EF may assign a temporary value when you add the entity to the context; this temporary value will then be replaced by the database generated value during SaveChanges(). For more information, see the docs on temporary values.

For example, after adding the author object below, the ID remains with value 0 so the Save Changes will throw an error related to the external key contraint violation.

### Example code

```
EFCoreDemoContext context = new EFCoreDemoContext();

var author = context.Authors.Add (new Author ()
{
    Name = "John",
    Surname = "Skeet",
    ParentID = 1,
    DoB = DateTime.Now
});

context.Books.Add (new Book ()
{
    Code = "ABC",
    Name = "Book",
    AuthorID = author.Entity.ID // value is 0
});

context.SaveChanges();
```

Error after calling Save Changes: 

PostgresException: 23503: The INSERT o l'UPDATE in table "Books" violates external key contraint "FK_Books_Authors_AuthorID"

### Provider and version information

EF Core version: 5.0.11
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (5.0.10)
Target framework: .NET 5

**Comment by roji** [comment]
@demian-floreani can you please submit a full code sample which shows the error happening? We need to see your model configuration as well, for example.

**Comment by demian-floreani** [comment]
@roji 

Here is the context and model classes. Do you need anything else?

Thank you

```
namespace LocalEFProject
{
    class EFCoreDemoContext : DbContext
    {
        public DbSet<Author> Authors { get; set; }
        public DbSet<Book> Books { get; set; }

        protected override void OnConfiguring (DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql("Host=localhost;Database=mydatabase;Username=postgres;Password=password");

        }

        protected override void OnModelCreating (ModelBuilder modelBuilder)
        {
        }
    }
}
```

```
namespace LocalEFProject.Models
{
    public class Author
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime DoB { get; set; }
    }
}
```

```
namespace LocalEFProject.Models
{
    public class Book
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int? AuthorID { get; set; }
        public Author Author { get; set; }
    }
}

```

**Comment by ajcvickers** [comment]
@demian-floreani See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#tkv

**Comment by demian-floreani** [comment]
@ajcvickers 

Thank you. You can close this issue.
