### ISSUE TITLE
Help migrating out of `GetColumnName()` removed in .NET 6

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/efcore#26565]
[We (nuget-trends)](https://github.com/dotnet/nuget-trends) were happily relying on [this answer from @ajcvickers](https://github.com/dotnet/efcore/issues/23301#issuecomment-727003676)  to keep the original code even after we bumped to .NET 5:

```
The method is obsolete because it will not always give the correct answer for newer models. For EF Core 5.0, this only means models that have TPT inheritance mapping, but as we add more features there will be more cases where the method will give the wrong answer.

If you have a model for 3.1 and you haven't changed it to use TPT, then you should be okay calling the implementation above in 5.0.
```

Now, we're targeting .NET 6 and the obsolete method is gone. 
It's unclear to me how I can use `StoreObjectIdentifier.Create` given the information I have in scope.

The code we want to move to .NET 6 is here:

https://github.com/dotnet/nuget-trends/blob/b99c6d484db384049138b40bd9bc9f72fcc4db0d/src/NuGetTrends.Data/BasePostgresContext.cs#L64

Help appreciated as [this is the only blocker](https://github.com/dotnet/nuget-trends/pull/178) we have to release [NuGet Trends on .NET 6 RC2](https://nugettrends.com/).

**Comment by YeskaNova** [comment]
You only need to give it the tablename:
```
           foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                var tableName = entity.GetEntityTableName();
                foreach (var p in entity.FindPrimaryKey().Properties)
                    p.SetColumnName(p.GetColumnName(StoreObjectIdentifier.Table(tableName)).Replace("Dbo", "", StringComparison.InvariantCultureIgnoreCase));
            }
```

**Comment by ajcvickers** [comment]
@bruno-garcia Sorry, I didn't mean to imply by my answer that it was okay to keep calling the obsolete method. I meant it was okay to use the code contained in the _implementation_ of the obsolete method. That is:

```C#
var columnName = property.GetColumnName(
    StoreObjectIdentifier.Table(property.DeclaringEntityType.GetTableName(), null));
```

This is also described in the [breaking changes documentation](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#ipropertygetcolumnname-is-now-obsolete).

**Comment by bruno-garcia** [comment]
Oh, that helps a lot. Thanks @YeskaNova and @ajcvickers.
