### ISSUE TITLE
TargetFramework for Microsoft.EntityFrameworkCore.Abstractions 6.0.0

### ISSUE THREAD

**Issue by mustaddon** [dotnet/efcore#26576]
may be is there an error in the target framework? 
netstandard2.1 ?...

**Comment by ajcvickers** [comment]
@mustaddon EF Core 6.0 requires .NET 6. See [The Plan for EF Core 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/plan) for more information.
