### ISSUE TITLE
Using Cosmos Db with EfCore and Managed Identity

### ISSUE THREAD

**Issue by dogabariscakmak** [dotnet/efcore#26573]
Hello, 
Since [Cosmos: Resolve HttpClientFactory from DI if available](https://github.com/dotnet/efcore/issues/21274) is resolved, now using Cosmos Db provider for Ef Core with Managed Identity is technically possible. 

However, the underlying flow could be complicated. Therefore it would be great if there is a tutorial/guide on how to use those.

**Comment by ajcvickers** [comment]
@dogabariscakmak By "Managed Identity", do you mean ASP.NET Core Identity? If so, then that model is designed assuming relational databases, and we don't think it is a great fit for a document database.

**Comment by dogabariscakmak** [comment]
What I meant Managed Identities for Azure resources. When using EfCore CosmosDb provider, it can be used with managed identity without connection string or secret.

**Comment by ajcvickers** [comment]
@dogabariscakmak This? #26491

**Comment by dogabariscakmak** [comment]
yes
