### ISSUE TITLE
dbscaffold creates reference error CS0120 in nameof() for InverseProperty in certain conditions

### ISSUE THREAD

**Issue by janschreier** [dotnet/efcore#26588]
when table names in n:m relations meet certain criteria, the below code is created by dbScaffold (DDL statements at the bottom)
```csharp
namespace ScaffoldError.database
{
    public partial class MA
    {
        public MA()
        {
            MFMA = new HashSet<MFMA>();
        }

        [Key]
        public int MAId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string? Bezeichnung { get; set; }

        [ForeignKey("MAId")]
        [InverseProperty(nameof(database.MFMA.MA))]
        public virtual ICollection<MFMA> MFMA { get; set; }
    }
}
```
The problem is line `[InverseProperty(nameof(MFMA.MA))]` which wants to reference the class called MFMA but actually references the next line's Icollection. this creates compiler error CS0120	"An object reference is required for the non-static field, method, or property 'MFMA.MA'"

The solution is to qualify the MFMA like so `[InverseProperty(nameof(database.MFMA.MA))]`
I could imagine the issue comes from the naming pattern that one table ends with the other tables names but that's just a guess.

Statement used for scaffolding
```shell
dotnet ef dbcontext scaffold "data source=localhost;initial catalog=dbname;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework" Microsoft.EntityFrameworkCore.SqlServer `--output-dir "database" --table ma --table mfma --table mfmama --data-annotations --use-database-names --force --no-onconfiguring --no-pluralize 
```

DDL-Statements:
```sql
CREATE TABLE dbo.MA (
  MAId INT IDENTITY
 ,Bezeichnung VARCHAR(50) NULL
 ,CONSTRAINT Pk_ma PRIMARY KEY CLUSTERED (MAId)
) ON [PRIMARY]
GO

CREATE TABLE dbo.MFMA (
  MFMAId INT IDENTITY
 ,Bezeichnung VARCHAR(50) NULL
 ,CONSTRAINT pk_mfma PRIMARY KEY CLUSTERED (MFMAId)
) ON [PRIMARY]
GO

CREATE TABLE dbo.MFMAMA (
  MAId INT IDENTITY
 ,MFMAId INT NOT NULL
 ,CONSTRAINT PK_MFMAMA PRIMARY KEY CLUSTERED (MAId, MFMAId)
) ON [PRIMARY]
GO

ALTER TABLE dbo.MFMAMA
ADD CONSTRAINT FK_MFMAMA_MAId FOREIGN KEY (MAId) REFERENCES dbo.MA (MAId)
GO

ALTER TABLE dbo.MFMAMA
ADD CONSTRAINT FK_MFMAMA_MFMAId FOREIGN KEY (MFMAId) REFERENCES dbo.MFMA (MFMAId)
GO
```
### provider and version information

EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0 
Operating system:
IDE: (e.g. Visual Studio 20202 current)

**Comment by ajcvickers** [comment]
Note for triage: regression in 6.0. 5.0 generates:

```C#
        [InverseProperty("MA")]
        public virtual ICollection<MFMAMA> MFMAMA { get; set; }
```

While 6.0 generates:

```C#
        [InverseProperty(nameof(MFMA.MA))]
        public virtual ICollection<MFMA> MFMA { get; set; }
```

**Comment by ajcvickers** [comment]
Notes from triage:
* For 7.0, we will revert the change to use `nameof` since it is complex to get all the scoping rules correct.
* We may consider patching this issue based on feedback. For now, the workaround is to manually (e.g. regex search and replace) the scaffolded code.

**Comment by janschreier** [comment]
I would prefer this as a patch but since this is a compile time issue I think we could live with a workaround for a year if it is too much effort to fix it now

**Comment by HakanL** [comment]
@ajcvickers I'd love to have this as a patch to 6 since manually patching the generated files (or adding a search/replace process) is  cumbersome and error-prone. Nameof is a great feature, but in generated code it's less valuable since you won't refactor generated code (which I understand is why you revert the changes, good).

**Comment by ajcvickers** [comment]
Note from triage: patch this in 6.0.
