### ISSUE TITLE
Update C# Documentation to give unit testing examples

### ISSUE THREAD

**Issue by the-patience-tester** [dotnet/efcore#26589]
The C# documentation is while extensive could be made better if it had a section with guidance on how to test the subject of the documentation 

For example here is a fairly straightforward bit of EF documentation about [Global filter queries](https://docs.microsoft.com/en-us/ef/core/querying/filters) now it is a quick read and very to the point documentation but there's no mention of how best to go about testing a model configuration. So while implementing the query filter is a 10 second job thanks to this great documentation it would be easy to sink a lot of time into figuring out a way/how best to test it

**Comment by roji** [comment]
Note we have [a section addressing testing specifically](https://docs.microsoft.com/en-us/ef/core/testing/). #3539 is out, reworking it and going into more depth on both unit testing and integration testing.

If you find that insufficient, then what exactly are you looking for, is there something specific about global filter queries that warrants special test notes? What kind of testing do you want to do?

**Comment by the-patience-tester** [comment]
I just picked that as an example because it seemed like an easy and simple bit of documentation to make my point, I was really thinking that it would be good generally for the C# documentation to have more smaller examples of testing implementations in the same documentation. Generally speaking testing tends to be a completely separate section within the docs but it doesn't feel like it needs to be or should be that way.

**Comment by roji** [comment]
@the-patience-tester I'm not sure I agree... We can't really add testing samples for each and every feature EF Core has - it would make the documentation considerably longer everywhere without necessarily adding any value... Once general principles around testing EF Core applications are understood (that's the job of the testing section of the docs), I don't really see what makes global query filters (or any other specific EF Core feature) special or different enough to warrant specific testing info...

**Comment by the-patience-tester** [comment]
Nevermind, I think the general nature of my observation/request has been completely lost by the specific nature of how these issues are assigned and addressed. I don't think making documentation longer is such a drawback tbh. Examples of how to test some parts of the different libraries would could also server as the example of how to use something. 

Anyway I am thinking out loud I didn't mean to specifically victimise global queries, and it's fine if you don't agree about implementation specific testing examples
