### ISSUE TITLE
How to compare 2 type mappings to be equal

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#26581]
While fixing #19503,
we need to add additional parameter of type mapping of earlier parameter is different. But how to figure out in code that type mapping is "different"? `==` or `Equals` is doing reference comparison which is not giving expected answer.

**Comment by smitpatel** [comment]
Current hack in place, match store type and converter. If any of those differs then it is different TypeMapping

**Comment by ajcvickers** [comment]
Notes from triage: it seems it is more appropriate for consumers of the mapping to choose which parts of the mapping are important and compare those. This will be different depending on how the consumer is using the mapping.
