### ISSUE TITLE
EF Core 6 get notmapped/ignored members

### ISSUE THREAD

**Issue by rizi** [dotnet/efcore#26594]
In EF Core 5 I was able to get all not mapped/ignored members like the this:

var x = _dbContext.Model.FindEntityType(typeof(MyEntityType)) as EntityType;

x.GetIgnoredMembers();

With EF Core 6 the as EntityType returns null, is there any other way?

Btw. MyEntityType has a configuration that derives from IEntityTypeConfigurationyEntityType>.

And in this config I use builder.Ignore(y => y.PropertyName);

**Comment by AndriySvyryd** [comment]
EF Core 6 converts `EntityType` to `RuntimeEntityType` after the model is built and discards ignored members. Why do you need to access them on a finished model?

**Comment by rizi** [comment]
> EF Core 6 converts `EntityType` to `RuntimeEntityType` after the model is built and discards ignored members. Why do you need to access them on a finished model?

Thx for your answer.
We need this information because we are joining (.Include()) all "Navigation Properties" automatically and if we ignore one of them we don't want it to be used in the join.

I just found a very easy way to get this information.

```
 IEntityType entityType = DatabaseContext.Model.FindEntityType(typeToCheck);
        if (entityType == null)
            return query;

        IReadOnlyCollection<INavigation> relevantNavigationProperties = entityType.GetNavigations()
            .Where(navigation => (navigation.ClrType.GetInterface(nameof(IEnumerable)) != null && navigation.ClrType.IsGenericType
                       ? navigation.ClrType.GetGenericArguments().Single()
                       : navigation.ClrType) != parentType)
            .ToList();
```

br
