### ISSUE TITLE
DbScaffold should honor table names in n:m-relations

### ISSUE THREAD

**Issue by janschreier** [dotnet/efcore#26607]
With EF Core 6.0 pure n:m-tables are not created anymore with scaffolding but an ICollection is created carrying the name of the linked table not the name of the link itself. This is fine for simple relations but you may loose important context. 
E. g. we have three tables:
* Books
* Labels
* LabelsToExcludeFromBooks (Linking the previous 2)

EF Core 6.0's dbscaffold creates two classes:
* Books  (with an ICollection Labels)
* Labels (with an ICollection Books)

the meaning of Labels in Books is not "Labels" but "Labels to Exclude".  In  EF Core 5 this was clear because the Link-Table was created as own class, making the meaning explicit. In EF Core 6 this meaning is lost. So I would suggest that the names of the ICollection in Scaffolding should be the name of the link-table and not just the linked-table's name.

We're rebuilding the EF database tables every time our database model changes (thus not actually doing what db scaffold actually implies by its name). So if you decide to keep it the current way, I am fine, but I thought I let you know and eventually we're not the only ones with this problem and you might consider this idea.

**Comment by ajcvickers** [comment]
@janschreier Is your desired behavior here to go back to scaffolding an explicit join entity, as in EF Core 5.0, or to create a many-to-many relationship as in EF Core 6.0, but with a differently named navigation?

**Comment by janschreier** [comment]
I think a differently named navigation should be good enough. Althoug there are some WPF scenarios were it was quite handy to be able to create a new relation by simply adding two IDs instead of having to ensure that both objects are loaded in the same dbContext. but that's another story (I haven't thought through sufficiently)

**Comment by ErikEJ** [comment]
@ajcvickers Any ideas how I could make this optional in EF Core - where in the reverse engineer pipeline can best hook in, and with what?

**Comment by ajcvickers** [comment]
@janschreier This will be possible with [templates for scaffolding](https://github.com/dotnet/efcore/issues/4038), which is currently planned for EF7. For now, you could [go back to the original join table code with a bit of post scaffolding tweaking](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many). Or hopefully @ErikEJ can do something in the Power Tools.

@ErikEJ Response from team was, "hook into the place where navigations are named." I assume this is design-time service that you can override. Probably going to be ugly.

**Comment by smitpatel** [comment]
For @ErikEJ 
https://github.com/dotnet/efcore/blob/fb61eb7cfb75253fbae93aeac23c404ba68b83a8/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L658-L660

Override and bypass whole code to detect M2M.

**Comment by ajcvickers** [comment]
Covered by #4038.
