### ISSUE TITLE
Not synced data for non-backing filed properties

### ISSUE THREAD

**Issue by KazemJavadi** [dotnet/efcore#26606]
There is a problem with non-backing field properties. For non-backing field properties, data is not synced with the database!

I have `DbContext` like this:
```C#
internal class AppDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("server=.;database=MyTestDb;Trusted_Connection=true");
    }

    public DbSet<Person> People { get; set; }
}
```
My entity code is (Please pay attention to my comments in the code):
```C#
public class Person
{
    public int Id { get; set; }

    //backing field
    private string _name_BackingField;
    public string Name_BackingField { get => $"Mr.{_name_BackingField}"; set => _name_BackingField = value; }

    //non-backing field
    private string _x;
    public string Name_NonBacakingField { get => $"Mr.{_x}"; set => _x = value; }

    //override
    public override string ToString() =>
        $"[Name - BackingField]: {Name_BackingField} - [Name - NonBackingField]: {Name_NonBacakingField}";
}
```
`Name_BackingField` property have `_name_BackingField` backing field, and `Name_NonBacakingField` have `_x` *private* filed but not *backing filed*.  
This is my `Program.` class:
```C#
AppDbContext context = new();
context.Database.EnsureDeleted();
context.Database.EnsureCreated();

Person person1 = new() { Name_BackingField = "Kurosh", Name_NonBacakingField = "Kurosh" };
context.People.Add(person1);
context.SaveChanges();

//output 1
foreach (var person in context.People)
    WriteLine(person);

//output 2
AppDbContext newContext = new();
foreach (var person in newContext.People)
    WriteLine(person);

ReadLine();
```
In this part of my  code in the `Program` class I create a `new` `Person` and add it to my `context` and `SahveChanges()`:
```C#
Person person1 = new() { Name_BackingField = "Kurosh", Name_NonBacakingField = "Kurosh" };
context.People.Add(person1);
context.SaveChanges();
```
After saving changes my data in database is:

<table>
<tr>
	<th>Id</th>
	<th>Name_BackingField</th>
	<th>Name_NonBackingField</th>
</tr>
<tr>
	<td>1</td>
	<td>Kurosh</td>
	<td>Mr.Kurosh</td>
<tr>
</table>

In this part of my code in the `Program` class read and print the data:
```C#
//output 1
foreach (var person in context.People)
    WriteLine(person);
```
My printed data in the console is:
```
[Name - BackingField]: Mr.Kurosh - [Name - NonBackingField]: Mr.Kurosh
```
As you can see, my output for both properties is `Mr.Kurosh`, which is not correct. Why? 
Because for my `Name_NonBacakingField` column in database I have `Mr.Kurosh` data and as you can see in my `Person` class for `Name_NonBacakingField` property I have this code:
```C#
//non-backing field
private string _x;
public string Name_NonBacakingField { get => $"Mr.{_x}"; set => _x = value; }
```
Based on this code in my getter (`get`), EF core must add a `Mr.` to *DB data* (in this case `Mr.Kurosh`) and get it back to me. So, the correct result must be `Mr.Mr.Kurosh` not `Mr.Kurosh`. Because `_x` is not *backing filed*.

In the next lines of my code in `Progam` class, I create another `new` `AppDbContext` and then read data again:
```C#
//output 2
AppDbContext newContext = new();
foreach (var person in newContext.People)
    WriteLine(person);
```
Output is:
```
[Name - BackingField]: Mr.Kurosh - [Name - NonBackingField]: Mr.Mr.Kurosh
```
Which is the correct output. Because for `Name_BackingField` I have `Mr.Kurosh` output and for `Name_NonBacakingField` I have `Mr.Mr.Kurosh` and both are correct.
***Why data is not synced with the database's data after saving changes in my first `AppDbContext` instance?***

----

I can guess why.
This is because when I `set` `Kurosh` value to the `Name_NonBacakingField` property, the *setter*(`set`) put the value to the `_x` private filed. And when I `SaveChhages()` EF Core read data of `Name_NonBacakingField` from *getter* of property and *getter* add `Mr.` to data and get it back to the EF Core. So data now is `Mr.Kurosh`. Then EF Core saves it to the database. So, also data in the database is `Mr.Kurosh`, which is correct. But problem is that the `Name_NonBacakingField` property reads data from `_x` and data of `_x` is `Kurosh` not `Mr.Kurosh` which is real data in the database. And when I read the data of *People* from my first `AppDbContext` instance, getter of  `Name_NonBacakingField` (` get => $"Mr.{_x}";`) add `Mr.` to the value of `_x` private field (which still is `Kurosh`) and return `Mr.Kurosh`, which is logically correct. But this logical behavior is not compatible with the logic of EF Core that should return `Mr.Mr.Kurosh` not `Mr.Kurosh`. Because in the database, real data is `Mr.Kurosh` and based on getter part of `Name_NonBacakingField` (` get => $"Mr.{_x}";`) I should get back `Mr.Mr.Kurosh`.

**Comment by ajcvickers** [comment]
@KazemJavadi Firstly, this seems like a pretty bad idea:

```C#
    private string _name_BackingField;
    public string Name_BackingField { get => $"Mr.{_name_BackingField}"; set => _name_BackingField = value; }
```

It means that:

```C#
person.Name_BackingField = "Arthur";
person.Name_BackingField = person.Name_BackingField;
Console.WriteLine(tag1.Name_BackingField);
```

will print:

```
Mr.Mr.Arthur
```

That being said, EF Core by default writes do and from backing fields when they can be found. You can configure a backing field explicitly when it is not found by convention, or you can configure EF to use the property instead of the backing field. See [Backing fields](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations) and [Property versus field access](https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#property-versus-field-access) in the documentation for more info.

**Comment by KazemJavadi** [comment]
Thank you @ajcvickers for your answer.
But this is not about a good idea or a bad idea. This is about the concept.
And in my question, I don't talk about the `Name_BackingField` property. This is an example of working right. The problem is with the `Name_NonBacakingField` property.

*I must say that I read all the links you gave me.*

Ok, let me explain (ask my question) in another way.

This is my simple `AppDbContext` class:
```C#
internal class AppDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("server=.;database=TestDb;user id=sa;password=2019");
    }

    public DbSet<Person> People { get; set; }
}
```
This is my simple model:
```C#
```

**Comment by KazemJavadi** [comment]
@ajcvickers I test It with *backing field*s too.
Even in *backing field*s I get 2 different results from the same data by 2 different instances of `AppDbContext`.

In `OnModelCreating` I add `_x` private field as *bakcing filed* and set `PropertyAccessMode` to `Property`. So, now `_x` private field is backing filed of `Name` property.
```C#
 internal class AppDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer($"server=.;database={nameof(_0085__BackingField)};Trusted_Connection=true;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>()
            .Property(p => p.Name)
            .HasField("_x")
            .UsePropertyAccessMode(PropertyAccessMode.Property);
    }

    public DbSet<Person> People { get; set; }
}
```

My *model* class (`Person`) and my `Program` class are exactly like the example above. And the printed result have the same problem: 
```
1:Mr.Kurosh
1:Mr.Mr.Kurosh
```
***If data in the database is the same, Why 2 different instances of the `AppDbContext` class return 2 different results from the same data?***

**Comment by ajcvickers** [comment]
@KazemJavadi Your property getter effectively changes the value of the property every time it is read. EF will write that value to the database, and then set the changed value back into the property when read from the database. Reading the value again will again change it. This is expected behavior if you code properties like this.

**Comment by KazemJavadi** [comment]
Thank you 🙏 @ajcvickers
