### ISSUE TITLE
Show workaround when Remove-Migration fails

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2660]
Remove-Migration fails when the project won't build. User's can get stuck (sometimes [our fault](https://github.com/aspnet/EntityFramework/issues/2545)).

Workaround: `Remove-Migration -ErrorAction SilentlyContinue`. (This doesn't always work either. It removes the model snapshot, but doesn't actually delete the last migration.)

**Work item** Add this to the error message when build fails so users can get around it.
#1242

**Comment by rowanmiller** [comment]
Discussed and concluded we shouldn't do this. We need to be able to compile the project to get the snapshot from the previous migration so that the model snapshot can be updated. We shouldn't ever produce code that doesn't compile (so we should fix any bugs where this happens).
