### ISSUE TITLE
SqliteConnectionFactory.cs is not thread-safe

### ISSUE THREAD

**Issue by sebastienros** [dotnet/efcore#26612]
Reads on the `Dictionary` are not locked with the write operations, which is not supported.
Suggestion is to use a `ConcurrentDictionary` and remove some of the locks, or use a `ReaderWriterLockSlim`.

https://github.com/dotnet/efcore/blob/main/src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs#L53

c.f. Dictionary source that is can throw an exception if the collection was changed while reads occur.
https://source.dot.net/#System.Private.CoreLib/Dictionary.cs,398

**Comment by ajcvickers** [comment]
FYI for those impacted by this issue: EF Core 6.0.1 is now [available from NuGet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/6.0.1).
