### ISSUE TITLE
Cosmos dbcontext retrieves empty results

### ISSUE THREAD

**Issue by vdeunzue** [dotnet/efcore#26628]
I have a DbContext set up to use Cosmos DB as follows:

```C#
    public class AuthenticationCosmosDataContext : DbContext, IUnitOfWork
    {
        private readonly CosmosOptions cosmosOptions;

        public DbSet<Settings> Settings { get; set; }

        public AuthenticationCosmosDataContext(DbContextOptions<AuthenticationCosmosDataContext> options, IOptions<CosmosOptions> cosmosOptions) : base(options)
        {
            this.cosmosOptions = cosmosOptions.Value;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultContainer(cosmosOptions.DefaultContainer);
            modelBuilder.Entity<Settings>().ToContainer(cosmosOptions.DefaultContainer);
            modelBuilder.ApplyConfiguration(new SettingsConfiguration());
        }
```

Which is set up from Startup.cs like this:

```C#
    services.AddDbContext<AuthenticationCosmosDataContext>((serviceProvider, options) =>
    {
       var cosmosOptions = serviceProvider.GetRequiredService<IOptions<CosmosOptions>>().Value;
       options.UseCosmos(cosmosOptions.AccountEndpoint, cosmosOptions.AccountKey, cosmosOptions.DatabaseName);
```

Now, the SettingsConfiguration doesn't have much in it:

```C#
    builder.HasKey(x => x.Id).HasName("id");
    builder.HasPartitionKey(x => x.Id); 
```

And the Settings look like this:

```C#
    public class Settings
    {
        public string Id { get; set; }
        public int SomeId { get; private set; }
        public string Type { get; private set; }
        public int AnotherId { get; private set; }
```

 I've tried querying data from the database, buy everything returns either null or 0 results:

```C#
    await cosmosContext.Settings.FirstOrDefaultAsync().ConfigureAwait(false); // returns null
    await cosmosContext.Settings.CountAsync().ConfigureAwait(false); // returns 0
```

The connection seems to be fine as there are no exceptions and I did have to make some adjustments in my model because there was some mismatch with the documents. 

What could be going wrong? 

I filed the same question in https://stackoverflow.com/posts/69885114/edit

Provider and version information:
EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 4.8.0484

**Comment by vdeunzue** [comment]
UPDATE: It appears the HasName() method in the configuration is not working as expected. If I rename the field from "Id" to "id" it works as expected. Looking for a way to properly set the configuration

**Comment by AndriySvyryd** [comment]
@vdeunzue You can configure the property name by calling `builder.Property(p => p.Id).ToJsonProperty("id");`
