### ISSUE TITLE
IDbContextFactory async contract vs covariance

### ISSUE THREAD

**Issue by MikeAmputer** [dotnet/efcore#26630]
Just a quick question. Was it worth it to add `IDbContextFactory.CreateDbContextAsync` in https://github.com/dotnet/efcore/pull/24768 sacrificing the covariance?
I used to inherit sqlite contexts for tests in my solution. I will find the way to deal with the new contract, but I'm really curious.

**Comment by ajcvickers** [comment]
@MikeAmputer In retrospect, it's possible we should not have added this; it might turn out to be YAGNI. Could you provide some more details on how you were using the covariance.

**Comment by MikeAmputer** [comment]
@ajcvickers thank you for your reply. Here is an example of covariance usage:
```
public class TransactionalContextFactory<TContext> : ITransactionalContextFactory<TContext>
    where TContext : DbContext
{
    protected readonly IDbContextFactory<TContext> ContextFactory;

    public TransactionalContextFactory(IDbContextFactory<TContext> contextFactory)
    {
        ContextFactory = contextFactory ?? throw new ArgumentNullException(nameof(contextFactory));
    }

    // ITransactionalContextFactory<TContext> implementation
    public virtual TransactionalContext<TContext> Create(...) { ... }
}
```

```
internal class TestTransactionalContextFactory<TContext, TContextStub> : TransactionalContextFactory<TContext>
    where TContext : DbContext
    where TContextStub : TContext
{
    public TestTransactionalContextFactory(IDbContextFactory<TContextStub> contextFactory)
        : base(contextFactory) { } // here

    // ITransactionalContextFactory<TContext> implementation override
}
```
DI consumer classes get `ITransactionalContextFactory<ProductionContext>` that builds a `TransactionalContext<InMemSqliteContext>` in tests (`InMemSqliteContext` inherits `ProductionContext`).

**Comment by ajcvickers** [comment]
@MikeAmputer Thanks. We discussed, and while maybe we should not have added this API (time will tell), we don't think making a breaking change to remove it would be the best thing to do now.

**Comment by wertzui** [comment]
@ajcvickers could you elaborate why the covariance needed to be removed for this feature to work?
Or would it be possible to reintroduce the covariance and still keep the async feature?

For me this breaks my library which basically adds a `Set<TEntity>()` method to `IDbContextFactory<DbContext>`
The signature is this
```
public static IQueryable<TEntity> Set<TEntity>(this IDbContextFactory<DbContext> contextFactory)
            where TEntity : class
```

That way, the consumers can call it like this
```
await factory.Set<MyEntity>().Where(...).Select(...).ToListAsync();
```

Because the covariance is gone now, I need to change the signature to this
```
public static IQueryable<TEntity> Set<TContext, TEntity>(this IDbContextFactory<TContext> contextFactory)
            where TContext: DbContext
            where TEntity : class
```

This forces the consumers to call it like this
```
await factory.Set<MyContext, MyEntity>().Where(...).Select(...).ToListAsync();
```

So they already have a `IDbContextFactory<MyContext>` and they need to repeat that generic type every time they call the `Set` method which seems redundant.

**Comment by ajcvickers** [comment]
@wertzui Because async methods return `Task<TContext>`, not `TContext`.

**Comment by wertzui** [comment]
Thanks!
However I would still vote to reintroduce the covariance :)

**Comment by georg-jung** [comment]
I used the covariance too. It was usable in EF Core 5 but is removed with EF Core 6. If I haven't overlooked it it is not listed in the [list of breaking changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes) though.

**Comment by georg-jung** [comment]
For others facing the same difficulties as I did, following workaround works for me:

I previously had in my DI config:

    services.AddTransient<IDbContextFactory<ApplicationDbContext>>(sp => sp.GetRequiredService<IDbContextFactory<ClientDbContext>>());

I created a helper factory class like this:

    internal class CovariantDbContextFactory<TContextOut, TContextIn>
        : IDbContextFactory<TContextOut>
        where TContextOut : DbContext
        where TContextIn : TContextOut
    {
        private readonly IDbContextFactory<TContextIn> _contextInFactory;

        public CovariantDbContextFactory(IDbContextFactory<TContextIn> contextInFactory)
        {
            _contextInFactory = contextInFactory;
        }

        public TContextOut CreateDbContext()
            => _contextInFactory.CreateDbContext();

        public async Task<TContextOut> CreateDbContextAsync(CancellationToken cancellationToken = default)
            => await _contextInFactory.CreateDbContextAsync(cancellationToken);
    }

And register it in DI:

	services.AddTransient<CovariantDbContextFactory<ApplicationDbContext, ClientDbContext>>();
	services.AddTransient<IDbContextFactory<ApplicationDbContext>>(sp => sp.GetRequiredService<CovariantDbContextFactory<ApplicationDbContext, ClientDbContext>>());

Now my old EF Core 5 code works without changes.

Anyone: If this approach has considerable flaws I'm overlooking, I am happy if you point me to it.

**Comment by FuzzyPhilip** [comment]
@georg-jung your elegant solution (OK, massive hack!) is another example of "there is no problem in computer science that can't be solved by using another layer of indirection" 😉
