### ISSUE TITLE
Foreign Key Case Sensitive Issue in EF Core v5.x

### ISSUE THREAD

**Issue by veizx** [dotnet/efcore#26647]
## Bug explanation
I use Microsoft.AspNetCore.Identity and Microsoft.EntityFrameworkCore in my project. 
I have following domain models lets say:
```C#
public class ApplicationRole : IdentityRole
{
}

/// <summary>
/// The default implementation of <see cref="IdentityRole{TKey}"/> which uses a string as the primary key.
/// </summary>
public class IdentityRole : IdentityRole<string>
{
    /// <summary>
    /// Initializes a new instance of <see cref="IdentityRole"/>.
    /// </summary>
    /// <remarks>
    /// The Id property is initialized to form a new GUID string value.
    /// </remarks>
    public IdentityRole()
    {
        Id = Guid.NewGuid().ToString();
    }
    ..
    ...
}

public class UserManagerOptions
{
  public string RoleId { get; set; }
  [ForeignKey("RoleId")]
  public ApplicationRole Role { get; set; }
}
```
So, we have UI part from where we do create Users and Roles, also we do have a functionality named as BulkImport for importing list of roles directly to the database with store procedure.
This results with having Roles in database some with lower case string ids(the ones created with UserManager) and some with upper case string ids(the ones imported with store procedure).

Later on when we define the application default role from all roles in db, if selection is made for imported role we do end up with entry in UserManagerOptions table where the RoleId(FK) is lowercase string. 

Example:
```
AspNetRoles.Id = 324D3AC1-7F4A-464F-B9A0-27130FA5B02C
UserManagerOptions.RoleId =  324d3ac1-7f4a-464f-b9a0-27130fa5b02c
```
There was not any problem until i tried the following LINQ:
```C#
var userManagerOptions = await _applicationDbContext.UserManagerOptions.Include(x => x.Role).FirstOrDefaultAsync();
```

UserManagerOptions where loaded without navigational property Role. Role was null in this case. 

I read about the already reported issues for string collations: https://github.com/dotnet/EntityFramework.Docs/issues/2979

But my question is why the `Include()` does not work in this case where the following code works:
```C#
var role = await _roleManager.FindByIdAsync("324d3ac1-7f4a-464f-b9a0-27130fa5b02c");
```
OR
```C#
var role = await _applicationDb.Roles.FirstOrDefaultAsync(x => x.Id == "324d3ac1-7f4a-464f-b9a0-27130fa5b02c");
```

It seems to me like `Include()` does somehow case-sensitive check for navigational properties but the other cases like I described above does case-insensitive check for loading the role entity and loads it successfully.

I do understand the problem for collations but isn't it obvious that if it is a **Foreign Key** column and has some value in it (even if it is a string column) it means there is an entity that can be loaded from database ?

I already addressed the problem and the better solution for me right now is to make sure that store procedure also imports the data to database with lowercase string Ids for Roles.

Maybe this is not an issue but I am just curious and I would appreciate it if someone explains in details this case.

### Further technical details

Microsoft.AspNetCore.Identity: v5.0.3
Microsoft.EntityFrameworkCore: v5.0.3
Target framework: .NET 5.0

**Comment by ajcvickers** [comment]
@veizx See [Use case-insensitive string keys](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#use-case-insensitive-string-keys).
