### ISSUE TITLE
[NuGet] EntityFramework.Commands has Windows 5.0 runtime

### ISSUE THREAD

**Issue by punitganshani** [dotnet/efcore#2664]
The NuGet Package EntityFramework.Commands has Windows 5.0 runtime.  Is this an error or there is a new runtime called Windows 5.0?

_Link:_ https://www.nuget.org/packages/EntityFramework.Commands/

![image](https://cloud.githubusercontent.com/assets/1032553/8761597/f9ad31f0-2d8b-11e5-97f7-75d35c17dbf6.png)

**Comment by bricelam** [comment]
It's due to the temporary TFM `netcore50`. We still need to update it to `uwp10`.

**Comment by punitganshani** [comment]
@bricelam ok, I could get that when I saw the metadata using NuGet API but "Windows 5.0" is a bit confusing especially when Win10 will be launched soon.

**Comment by bricelam** [comment]
:smile: We're not the only ones: https://www.nuget.org/packages/System.Runtime/

**Comment by bricelam** [comment]
Blocked on aspnet/dnx#2302

**Comment by bricelam** [comment]
Re-opening. This was regressed in 78559e6321aec1d6b0aa67abb08673452235d99e

**Comment by divega** [comment]
@bricelam what do we need to do? Need to fix it for RC1?

**Comment by bricelam** [comment]
Just use `uwp10.0` instead of `netcore50`. It's not functionally important.

**Comment by rowanmiller** [comment]
Closing as we have packages that work. We will continue to do whatever is needed to make things work.
