### ISSUE TITLE
Why Microsoft.Data.* as namespace rather than System.Data?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#2665]
Why is the namespaces under **`Microsoft`**`.Data.*` rather than **`System`**`.Data.*`?

Problem and painful when upgrading existing code.

**Comment by rowanmiller** [comment]
This is to be consistent with other frameworks (such as ASP.NET). Moving to EF7 is more of a port scenario than an upgrade so changing namespaces also helps convey that you are really targeting different objects than EF6.

**Comment by weitzhandler** [comment]
Will it eventually change to `System.*` after release etc?

**Comment by rowanmiller** [comment]
No, they will stay as Microsoft.*. This is consistent with what other technologies that are not part of the BCL have done.
