### ISSUE TITLE
Parentheses put around IS NULL only if operand is of type boolean (6.0)

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26652]
#25722 fixed #23990 by adding parentheses around `IS NULL`/`IS NOT NULL`, preventing operator precedence issues. However, it did so [only when the operand of `IS NULL` is a bool](https://github.com/dotnet/efcore/blob/fa3cea4fc4cfd65dd87995f4d72bb46dd550db22/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L524). However, the same problem can happen if a non-bool column is being checked for null.

See https://github.com/npgsql/efcore.pg/issues/2090 on PostgreSQL where the following LINQ query:

```c#
var boolParam = true;
_ = ctx.Blogs.Where(c => boolParam != c.NullableGuid.HasValue).ToList();
```

... generates the following SQL ...

```sql
SELECT b."Id", b."NullableGuid"
FROM "Blogs" AS b
WHERE @__boolParam_0 <> b."NullableGuid" IS NOT NULL
```

... which fails with `operator does not exist: boolean <> uuid`, because in PostgreSQL the precedence of `<>` is higher than the precedence of `IS NOT NULL` ([docs](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-PRECEDENCE)). The issue also causes wrong data to be returned in Sqlite.

**Comment by ajcvickers** [comment]
@roji You put `servicing-consider` on this. Are you planning to get it into 6.0.1?

**Comment by roji** [comment]
@ajcvickers @smitpatel sorry, I confused this issue with something else in triage; the reason I put `servicing-consider` on this is that it makes SQLite return incorrect data (because of bad operator precedence). A patch specifically for this (without full-on general parentheses support) would be quite easy and risk-free.

**Comment by roji** [comment]
```sql
SELECT TRUE <> (NULL IS NULL); -- returns 0
SELECT TRUE <> NULL IS NULL; -- return 1
```

**Comment by smitpatel** [comment]
@roji - Can you file a separate issue for 7.0 fix? (You can assign to me if you want)

**Comment by roji** [comment]
@smitpatel is that basically #23895?

**Comment by smitpatel** [comment]
That issue has been fixed. You would need to file a new issue for this particular query if we plan to fix it differently.

**Comment by roji** [comment]
Well we'll definitely need to... I'd track it all under #23895 (correct parentheses around IS NULL, remove unneeded parentheses around AND/OR), but if you want to file something different go ahead.

**Comment by smitpatel** [comment]
#23895 is about adding mechanism which is already done.

**Comment by roji** [comment]
Filed #26767. You probably need another one for the AND/OR simplification?
