### ISSUE TITLE
Cannot create default/global query filter with variable when using an EntityTypeConfiguration class. 

### ISSUE THREAD

**Issue by cdarrigo** [dotnet/efcore#26666]
When abstracting entity configuration to its own class, I am unable to create a query filter that references a property on the data context. 

Given a DataEntity defined as 
```C#
   public class TodoListDataEntity : DataEntity,  IMapToAndFrom<TodoList>, IMapToAndFrom<TodoListDto>
    {
        public string TenantId { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public int Id {get;set;}
        public Guid? Guid {get;set;}
   }
```

and a DbContext defined as:
```C#
public class PlatformDbContext : DbContext
  {
      protected readonly string TenantId = "HardcodedForDemo"
      public DbSet<TodoListDataEntity> TodoLists { get; set; } = null!;
  ...
 }
```

Defining a query filter on Tenant Id in the OnModelCreating method  of the Data context _does_ work:

```C#
protected override void OnModelCreating(ModelBuilder builder)
        {            
            base.OnModelCreating(builder);            

             builder.Entity<TodoListDataEntity>()
                 .HasQueryFilter(i => i.TenantId == TenantId);
        }
```

But abstracting the creation of the query filter to an EntityConfiguration class does not work

```C#
  public class TodoListDataEntityConfiguration : IEntityTypeConfiguration<TodoListDataEntity>
    {
        protected override void ConfigureEntity(EntityTypeBuilder<TodoListDataEntity> builder)
        {
            builder.ToTable(WellKnownData.TableNames.TodoLists, WellKnownData.Schemas.ApplicationSchema);

            // build up the expression "i=>i.TenantId == TenantId" (TenantId is a property on the PlatformDbContext)
            var parameterExpression = Expression.Parameter(typeof(TodoListDataEntity), "i");
            var property = Expression.Property(parameterExpression, "TenantId"));
            var variable = Expression.Variable(typeof(string), "TenantId");
            var expression = Expression.Equal(property, variable);

            // convert it to a lambda
            var lambda = Expression.Lambda<Func<TodoListDataEntity, bool>>(expression, parameterExpression);

            // create a global filter for this
            builder.HasQueryFilter(lambda);
        }
    }

```
and changing the OnModelCreating method of the data context to apply the configuration 

```C#
        protected override void OnModelCreating(ModelBuilder builder)
        {           
            builder.ApplyConfiguration(new TodoListDataEntityConfiguration());
            base.OnModelCreating(builder);
        }
```
 
There is no run-time exception, but rather the query filter is never applied.  There is no where clause in the generated sql for the TenantId filter condition. 

EF Core version:  5.0.11
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 5.0
Operating system: Windows 10 21H1
IDE:  Visual Studio 2022

**Comment by smitpatel** [comment]
>  var variable = Expression.Variable(typeof(string), "TenantId");

This is just a local variable, it has no connection to your dbcontext. When you write `TenantId` inside `OnModelCreating` it is actually `this.TenantId` where this refers to db context instance.

**Comment by cdarrigo** [comment]
> > var variable = Expression.Variable(typeof(string), "TenantId");
> 
> This is just a local variable, it has no connection to your dbcontext. When you write `TenantId` inside `OnModelCreating` it is actually `this.TenantId` where this refers to db context instance.

so how can the abstracted entityconfiguration class reference the property on the dbcontext?

**Comment by stevendarby** [comment]
@cdarrigo If your TenantId property was public (or internal?), you could pass the context into the configuration class constructor, store it in a field/property and reference that in your query filter. I'm not sure if this fully meets your definition of "abstracted" as the configuration is now coupled with your PlatformDbContext*, but it does still allow neat separation of the configuration into separate classes, which is the main benefit for me.

*You could go further, only coupling to any DbContext with a TenantId, by creating an interface for the TenantId property, making your configuration a generic constrained to DbContext + the interface, etc.
