### ISSUE TITLE
IMethodCallTranslatorPlugin is Scoped in ServiceCharacteristics but Singleton in document

### ISSUE THREAD

**Issue by yang-er** [dotnet/efcore#26667]
## File a bug

https://github.com/dotnet/efcore/blob/b38c2698045f44073a76b29c8e9126adbb379b79/src/EFCore.Relational/Query/IMethodCallTranslatorPlugin.cs#L14

The document says it is singleton.

https://github.com/dotnet/efcore/blob/b38c2698045f44073a76b29c8e9126adbb379b79/src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs#L105

As the service builder says it is scoped.

Since I was directly adding ServiceDescriptor to IServiceCollection, so I cannot catch the problem with EntityFrameworkRelationalServicesBuilder.

### Include stack traces

It is hard to debug and it makes the following stack trace originally:

```
(System.ArgumentNullException) -----
    ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
    DbContextServices.CreateModel(Boolean designTime)
    DbContextServices.get_Model()
    <>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
    CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
    CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
    CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
    CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    <other 92 frames…>
    IServiceProvider>.get_Instance()
    InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
    AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
    DatabaseFacade.get_Dependencies()
    DatabaseFacade.EnsureCreated()
```

As I read the source code I guess it was a dependency injection container problem, so I modified this in ServiceProviderCache:

```
var serviceProvider = services.BuildServiceProvider(validateScopes: true);
```

Then it becomes:

```
System.InvalidOperationException : Cannot consume scoped service 'Microsoft.EntityFrameworkCore.Query.ISqlExpressionFactory' from singleton 'Microsoft.EntityFrameworkCore.Query.IMethodCallTranslatorPlugin'.
```

This makes debugging a little bit harder. Is it possible to add some debug option to turn the option `validateScopes` on?

### Include provider and version information

EF Core version: 6.0
Database provider: Any relational provider
Target framework: .NET 6.0
Operating system: Windows 11 22000
IDE: Visual Studio 2022 17.0.0

**Comment by yang-er** [comment]
Also for `IQueryableMethodTranslatingExpressionVisitorFactory`.

The document is different in main branch and release/6.0 branch.

**Comment by ajcvickers** [comment]
@smitpatel Over to you.

**Comment by smitpatel** [comment]
Same bug appears for `IMethodCallTranslatorProvider` too. Seems like all query services which changed lifetime are wrong at this point.
