### ISSUE TITLE
Change EF Core merge behaviour

### ISSUE THREAD

**Issue by CyraxSputnik** [dotnet/efcore#26668]
I have several invoices that I want to save, or update if they are already registered in my database

I have my invoice entity. It has its primary key set to type long.

At this point I called the following code: context.Invoices.UpdateRange (invoice);

When I save several of these to the database using the code above, I have noticed that internally efcore creates a "merge". It means that it will update a row in the table if it was previously registered, or it will create a new entry if this entity is new.

When I checked my table of invoices in the database, I noticed that the behavior is far from what I expected, because it does not update entities if they were already loaded into the database. It only creates new records in the database.

After realizing the above, I change the primary key of the invoice entity, now taking its UUID as the primary key. I have to point out that this UUID is not generated within the program, rather it is only read from an XML.

The invoice entity now has its primary key set to type string, or varchar (36) in the database.

Once I have made the change and modified my tables in the database as well, I do a new test:

context.Invoices.UpdateRange (invoice);

But this time I noticed that instead of ef core creating a "merge" it just tries to update the invoice one by one.

================================================================================

I would like to know if there is any way to change this last behavior. That is, to be able to save or update all the invoices in a single operation.

Likewise, why when the primary key of the entity is a long, and it is self-generated, does it create a merge? And why when the primary key is a string or varchar (36) it just tries to update one by one.

I appreciate your comments in advance, thank you

**Comment by ajcvickers** [comment]
@CyraxSputnik I'm really not following the details of what you are saying. It might be useful to read through the [change tracker documentation](https://docs.microsoft.com/en-us/ef/core/change-tracking/). to understand how EF deals with generated key values. If this doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by CyraxSputnik** [comment]
> @CyraxSputnik I'm really not following the details of what you are saying. It might be useful to read through the [change tracker documentation](https://docs.microsoft.com/en-us/ef/core/change-tracking/). to understand how EF deals with generated key values. If this doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I just edited all of the above, hope I explained it better this time.

**Comment by ajcvickers** [comment]
@CyraxSputnik 

> When I checked my table of invoices in the database, I noticed that the behavior is far from what I expected, because it does not update entities if they were already loaded into the database. It only creates new records in the database.

UpdateRange should update or insert all properties of all entities. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by CyraxSputnik** [comment]
@ajcvickers 

[Example.zip](https://github.com/dotnet/efcore/files/7573268/Example.zip)

When I call context.UpdateRange(GetInvoices()); it just tries to update entity by entity.

If I use an autogenerated key (long in my case), it does use a merge.

**Comment by ajcvickers** [comment]
@CyraxSputnik This is working as expected--see [Updating existing entities](https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#updating-existing-entities) in the documentation. However, I don't understand how this example relates to your statements above.
