### ISSUE TITLE
Use EqualsExact in DefaultDateTimeOffsetValueComparer

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#26672]
https://github.com/dotnet/efcore/blob/f62cf1b1fa45d6026e8f98113d6d6712d81094c3/src/EFCore/ChangeTracking/ValueComparer.cs#L286

Current code correctly considers the offset, but the runtime provides an [EqualsExact](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.equalsexact?view=net-5.0#System_DateTimeOffset_EqualsExact_System_DateTimeOffset_)  method which I believe achieves the same thing. It may be more DRY / future proof to use this instead.

**Comment by roji** [comment]
Thanks @stevendarby, would you like to submit a PR for this?

**Comment by stevendarby** [comment]
@stevendarby Yep, sure. (I wasn’t sure if it was always necessary to raise an issue first for a small PR, but erred on the side of caution- would you say that’s good practice for this repo?)

**Comment by roji** [comment]
@stevendarby yeah, we usually do prefer receiving an issue prior to a PR - that allows discussing details and design before any work is done which could go in the wrong direction.

However, for small stuff like typos or very minor changes a simple PR is also ok - I personally think this does qualify for that, but when in doubt it's always ok to raise an issue beforehand.
