### ISSUE TITLE
Replace FunctionEvaluationDisablingVisitor and FunctionEvaluationEnablingVisitor with EvaluatableExpressionFilter

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/efcore#2667]
@maumar 
re-linq now (#2666) has an extension point for excluding expressions from partial evaluation: EvaluatableExpressionFilterBase, injected into the PartialEvaluatingExpressionTreeProcessor et al. The filter can take over the role played by FunctionEvaluationDisablingVisitor, removing the need for wrapping and unwrapping the expressions.

I should have time to send a PR sometime this week / over the weekend (based on PR #2668)

Best regards, Michael

**Comment by divega** [comment]
Clearing up milestone so that we can review in triage and determine priority.

**Comment by rowanmiller** [comment]
@MichaelKetting are you still planning to send a PR for this?

**Comment by MichaelKetting** [comment]
Oh dear. Yeah, I'm afraid not in time for the release :(

**Comment by rowanmiller** [comment]
Closing, but feel free to send a PR
