### ISSUE TITLE
ToSqlQuery method not working in 6.0.0

### ISSUE THREAD

**Issue by Quynn** [dotnet/efcore#26685]
Moving from 6.0.0-rc.2.21480.5 to 6.0.0 the extension method ToSqlQuery stopped working when used for mapping Database entities

**Comment by ajcvickers** [comment]
@Quynn Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by adil-portable** [comment]
Could you please share your project or code here so that I can have a look and try to solve the issue?

**Comment by Quynn** [comment]
To reproduce the error just change the version in the .csproj file

[EFIssue.zip](https://github.com/dotnet/efcore/files/7569747/EFIssue.zip)

**Comment by ajcvickers** [comment]
Duplicate of #26629.
