### ISSUE TITLE
Issues with publishing and Microsoft.EntityFrameworkCore.Design.dll

### ISSUE THREAD

**Issue by Andrew-Oliveira** [dotnet/efcore#26694]
I've been having issues with this for years now. It happened with previous versions of .NET and fixing it required copying the DLL to the publish directory. Now with upgrading to .NET 6 the copying trick isn't working and I'm at a loss.

`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

**Comment by ajcvickers** [comment]
@Andrew-Oliveira Please post your csproj file.

**Comment by Andrew-Oliveira** [comment]
I assume you're primarily looking for this section which is referenced [here](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#dip). I added the compile because it wouldn't build otherwise.

`		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive; compile</IncludeAssets>
		</PackageReference>`

**Comment by ajcvickers** [comment]
@Andrew-Oliveira If you are referencing the design package from your code (as opposed to just using it for tooling) then remove all the conditions and reference it as a normal package:

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0" />
```

**Comment by Andrew-Oliveira** [comment]
That did the trick! Thank you!
