### ISSUE TITLE
Query: model building for temporal table with explicitly defined period columns could fail if conventions are executed in a delayed fashion

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#26705]
When we explicity define column name for period property on temporal table, we rely on the property being created at the time HasColumnName is called (because we need to stick column name annotation on it). However, those properties are created by convention. Conventions *could* be executed with a delay, causing property to not be created by the time it is needed

**Comment by ajcvickers** [comment]
Note from triage: already fixed for 7.0 in other work. Could consider for patch if this comes in later as a customer reported issue.
