### ISSUE TITLE
Temporal Tables support for InMemoryDatabase

### ISSUE THREAD

**Issue by mhoerandner** [dotnet/efcore#26717]
## Temporal Tables support for InMemoryDatabase

I' m using `InMemoryDatabase` for testing purposes (e.g. integration tests) in EF Core 6.0 and was wondering if there is any support for `temporal tables`?

Specifically, I have an _integration test_ in which some rows of a table are updated several times. At the end I have to count the different column values of a specific entity.

Something like this:

```C#
public Task<int> CountAnyColumnsDifferentValues(int id)
    => DbContext.AnyTable
          .TemporalBetween(AnyDate, AnyOtherDate)
          .Where(t=> t.Id == id)
          .Select(t=> t.AnyColumn)
          .Distinct()
          .CountAsync();
```
Unfortunately the method always returns **1**, as if there is no real implementation for temporal tables in `InMemoryDatabase`?

**Comment by smitpatel** [comment]
InMemory database is not a SqlServer database. There is no table (let alone temporal) in InMemory.

**Comment by roji** [comment]
@mhoerandner InMemory is specifically not about integration testing, but rather unit testing. For integration testing, you'll have to test against SQL Server - we have [some docs being prepared](https://github.com/dotnet/EntityFramework.Docs/pull/3539) with guidelines on how to do that.

InMemory does not behave like SQL Server (e.g. temporal tables, transactions) and it isn't possible to make it do that.

**Comment by mhoerandner** [comment]
> 
> 
> @mhoerandner InMemory is specifically not about integration testing, but rather unit testing. For integration testing, you'll have to test against SQL Server - we have [some docs being prepared](https://github.com/dotnet/EntityFramework.Docs/pull/3539) with guidelines on how to do that.
> 
> InMemory does not behave like SQL Server (e.g. temporal tables, transactions) and it isn't possible to make it do that.

Thanks for the clarification. I could see from your [PR3539](https://github.com/dotnet/EntityFramework.Docs/pull/3539) that you clearly differentiate between end-to-end and integration testing. In addition, your "recommendation" about using in-memory for testing has changed from "_... can be useful..._" to "_... is discouraged_".

So far I thought a fake database like in-memory would be well suited for my tests (end-to-end tests via `WebApplicationFactory`) because it is lightweight (e.g. no SQL server required on the build server) and for my previous (very simple) use cases it was sufficient. 

Anyway, now I know and will use SQL Server for testing as well. 
Thank you very much.
