### ISSUE TITLE
How to resolve an IExecutionStrategy?

### ISSUE THREAD

**Issue by drauch** [dotnet/efcore#26710]
In EF 6 we used to resolve `IDbExecutionStrategy` from the container and use it for other (non EF) database operations as well. For EF Core we now want to basically do the same thing, i.e., resolving an `IExecutionStrategy`. How to do that?

Simply using `serviceProvider.GetRequiredService<IExecutionStrategy>()` fails just as much as resolving an `IExecutionStrategyFactory` object.

Do we need to register it somehow special? At the moment we only have the following registration code for all EF:

```
services.AddDbContext<MyDbContext>(options => options.UseSqlServer(connectionString, o => o.EnableRetryOnFailure()));
```

### Include provider and version information

EF Core version: 5.0.12 (we cannot go higher, as we are not yet on .NET 6)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: VS 2019 16.11.5

**Comment by AndriySvyryd** [comment]
`IExecutionStrategy` and other EF services are only available in the internal service provider that is usually not accessible by users.

If you have a context instance you can get an `IExecutionStrategy` by calling `DbContext.Database.CreateExecutionStrategy()`

See [Connection Resiliency](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) for more information
