### ISSUE TITLE
Incorrect optional dependent (owned type) warning when saving optional dependent with the _same_ data

### ISSUE THREAD

**Issue by skyflyer** [dotnet/efcore#26712]
I have checked open (and closed) issues regarding Optional Dependents and could not find the bug that we're seeing in our codebase. 

The warning emitted by `ModificationCommand` is incorrect when an owned type has the same data as the original:

> The entity of type 'Dependent' is an optional dependent using table sharing. The entity does not have any property with a non-default value to identify whether the entity exists. This means that when it is queried no object instance will be created instead of an instance with all properties set to default values. Any nested dependents will also be lost. Either don't save any instance with only default values or mark the incoming navigation as required in the model. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values of the entity.

Owned type `Dependent` in the sample:
* has a required property (`c.Property(y => y.HasFlag).IsRequired(true);`)
* is optional (`public Dependent? Child { get; set; }`)

### Include your code

The minimal reproduction code which illustrates this "bug" is here: https://github.com/skyflyer/efcore-optional-dependent-warning

```c#
using (var ctx = new EfTestDbContext(loggerFactory))
{
    var parent = new Parent { Child = new Dependent { HasFlag = true, Optional = "Opts" } };
    ctx.Parents.Add(parent);
    await ctx.SaveChangesAsync();

    parent.Child = new Dependent { HasFlag = true, Optional = "Opts" };
    await ctx.SaveChangesAsync(); // triggers the warning
}
```

<details><summary>DbContext config</summary>

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

public class EfTestDbContext : DbContext
{
    private readonly ILoggerFactory? _loggerFactory;
#nullable disable
    public DbSet<Parent> Parents { get; set; }
#nullable enable

    public EfTestDbContext(ILoggerFactory? loggerFactory=null)
    {
        _loggerFactory = loggerFactory;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder opts)
    {
        opts
            .UseSqlite("Filename=test.db", o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery));
            // .UseSqlServer(
            //     "yadayada",
            //     o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery)
            // );
        if (_loggerFactory != null) {
            opts.UseLoggerFactory(_loggerFactory);
        }
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<Parent>(conf => {
            conf.HasKey(x => x.Id);

            conf.OwnsOne(x => x.Child, c => {
                c.Property(y => y.Optional).IsRequired(false);
                c.Property(y => y.HasFlag).IsRequired(true);
            });
        });
    }
}

```

</details>

The code will repro when the data of the `Dependent` owned type is _equal_. The bug is present in `ModificationCommand` class, where the `optionalDependentWithAllNull` is defined.

I believe it is not defined correctly:

* the naming is not correct - the check does not check for nulls at all
* the value of `optionalDependentWithAllNull` is not "fixed" in cases when data is the same and hence not written to the database

The code reproduces with SQLite and SqlServer (and probably others as well).

I have also reproduced this code with the latest efcore from this repository. As an aside: what is the best approach to "pull latest efcore bits into my sample project"? I built the efcore using `./build.sh` and then replaced package includes with references and hintpaths to artifacts directory, which is cumbersome. Is there a better way (@smitpatel, @ajcvickers)?

### Include provider and version information

EF Core version: 6.0.0 (and latest)
Database provider: Microsoft.EntityFrameworkCore.SqlServer and SQLite
Target framework: .NET 6.0
Operating system: Mac OS 12.0.1
IDE: VS Code / irrelevant

**Comment by ajcvickers** [comment]
Note from triage: this does look like a bug. `HasFlag` is required and has a value.

**Comment by skyflyer** [comment]
@ajcvickers, thank you for taking the time to look into this. Is there a workaround perhaps? Or should we live with warnings for a year until 7.0.0? (we alert on all warnings and wouldn't like to ignore them...)

**Comment by ajcvickers** [comment]
@skyflyer You can disable the warning globally, or change its level to to something less than warning--see https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#configuration-for-specific-messages

**Comment by skyflyer** [comment]
That looks perfect, thanks!
