### ISSUE TITLE
EFCore 6 InMemory throw exception on ignored type lookup

### ISSUE THREAD

**Issue by erwan-joly** [dotnet/efcore#26731]
Hi,
It seems like there is a regression on EFCore 6
https://github.com/erwan-joly/EF6Bug

exact same code throw an exception when doing 
``` var entityBuilder = modelBuilder.Entity(entity.ClrType);```
https://github.com/erwan-joly/EF6Bug/blob/master/InMemoryEf6/TestDbContext.cs#L34

System.InvalidOperationException: The entity type 'Dictionary<string, string>' requires a primary key to be defined.If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.

This is happening with InMemory provider and an entity created for Npgsql provider
```
[Column(TypeName = "jsonb")]
public Dictionary<string, string>? Values { get; set; } = new();
```

this type is not known by InMemory this is why we Ignore it in our InMemoryDbContext but since the upgrade to EF Core 6 it just throw an error even if we ask it to be ignored

**Comment by AndriySvyryd** [comment]
We could fix it, but the fix would be medium risk as it could potentially make EF ignore types that shouldn't be ignored.

**Comment by AndriySvyryd** [comment]
As a workaround add `modelBuilder.Ignore<Dictionary<string, string>>();` before the loop

**Comment by erwan-joly** [comment]
> As a workaround add `modelBuilder.Ignore<Dictionary<string, string>>();` before the loop

I confirm this is solving the issue
