### ISSUE TITLE
Blazor - disposed DbContext conflicts with other instance of DbContext

### ISSUE THREAD

**Issue by sipi41** [dotnet/efcore#26743]
I think I found an error while trying to update an entity on my blazor server page.  The error I get is this:

**A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext.**

First I receive a parameter, in this case the CustomerId, something like this:

```C#
[Parameter]
    public int id { get; set; }
private Customer? customer { get; set; }
```

Now Customer has inside a list of pets and other properties, now I search for the Customer like this:

```C#
protected override async Task OnParametersSetAsync(){

using AppDbContext db = await DbContextFactory.CreateDbContextAsync();
        customer = await db.Customers
            .Include(i => i.Pets)
            .FirstOrDefaultAsync(f => f.Id == id);

        await db.DisposeAsync();

}
```

This works like a charm! it load correctly showing the Customer info, but before I show the data, I make something like this:

```C#
If(customer is null){<p>Loading</p>} else {
if(customer.Pets.Count == 0) { --------------> LINE SHOWING THE ERROR
<p>No pets yet</p>} else {
  foreach... etc etc etc
}
 .... MY HTML SHOWING THE CLIENT INFO ...
}
```

So when the OnParameterSetAsync method runs, it fills the customer property with a Customer entity and as you can see, I 'm using the DbContextFactory to create a dbcontext and I make sure to dispose the dbcontext (using should do this perfectly but just in case), so basically my understanding is that I have an entity of type Customer (with the list of Pets) separated from the dbcontext, as the dbcontext was disposed.

Now, after the Customer is loaded, I created a form field to update a vaccine date on each pet, so I created a method to update this value (if the user wants to of course) like this:

```C#
private async Task UpdateRabiesVaccine(int PetId)
    {

        Pet pet = customer.Pets.FirstOrDefault(f => f.Id == PetId);

        if (pet is not null)
        {
            pet.RabiesVaccineExpiresOn = DateTime.Now;

            using AppDbContext mydb = await DbContextFactory.CreateDbContextAsync();

             mydb.Update(pet);
                await mydb.SaveChangesAsync();
            await mydb.DisposeAsync();

        }

    }
```

What I did is, I did search for the Pet in the list of pets loaded inside my Customer entity, once I found it, update the value then, I did open a new dbcontext and tried to update the entity. The app immediately goes into ERROR saying that a simple count of entities is producing a conflict but makes no sense, the update of my method goes as desired, in other words, the date update is saved correctly in the database, is just that it for some reason after the update, the page says this operation conflicts with other, the problem I see is that the method OnParameterSetAsync did run a while ago, when the page was loading, the page is completely loaded, in fact at this point the dbcontext should not exist anymore, so this method when is called creates a new instance... makes no sense. 

The only way to make this works is if I lookup for the instance directly into the new dbcontext, not in the list I already have.  The app swears the first dbcontext (the one created in OnParameterSetAsync ) is dead, as I tried to get data like notes, etc and it shows me an error saying it has been disposed, so how's possible that I cant make this update way after and conflict?

Please help!

PD... I would like to map it simple:

FIRST THING IT DOES:

Page opens >> inject DbContextFactory >> OnParameterSetAsync  >> Creates first Context  using DbContextFactory >> Load Customer Data (including the Pet list) >> DbContext is Destroyed  >> Page Displayed  >> Finished  

AFTER PAGE COMPLETELY LOADS:

On Page, a Button is Displayed to Run Method >> Method objective: Update a Date in a Pet from the List  >> Search Pet in Pet List (on Customer Entity already loaded)  >> Pet Found, Update Field with new Value  >> Create New DbContext using DbContextFactory >> Update Entity, Save Data  >> Data is Saved but Error is Displayed, I think it tried to re-render and a simple check on Customer.Pets.Count Fires error but first DbContext was created and disposed way back.

**Comment by ajcvickers** [comment]
@sipi41 Are you using lazy-loading? If so, accessing `customer.Pets` will attempt to run a query while the query for `customer` is still executing.

**Comment by sipi41** [comment]
@ajcvickers, @javiercn and @Kahbazi thank you all for trying to help me.  Regarding the disposing twice, I did add that later, as "using" is supposed to call the dispose() method by itself, I did add it because it was weird it was trying to use it and it was disposed and the page fully loaded.

Mr @ajcvickers, yes, I'm using lazy loading, in fact I'm not sure why I have that because I did notice that if I use DbContextFactory, I can't invoke dynamically lazy data, this is why I used the "include(entity)" in my first query, because I tried to do it later and an error was returned as it clearly stated that I was trying to use a dbcontext that was already disposed, do you think is Lazy Loading the cause of this problem?

@javiercn Thank you, I will try your suggestion (use AsNoTracking()) this sounds right but I will run some tests as questions still here, like why is still tracking something is already disposed? or will this no-tracking affect re-rendering when something changes on blazor?

**Comment by sipi41** [comment]
@ajcvickers Yes, it was lazy loading, I did remove it and now it works like a charm! now you may excuse my ignorance as this is leading me to another question... I encounter Lazy Loading very useful, is there a way to implement something like LL in this approach? just curious... 

Know that I see my code back it makes sense my first approach, as why should I re-query the database again to find an entity I already have (with Id and everything)? I just need to send the changes to the db... at least I did learn something as I'm trying to get my first job as .net core programmer... :-)

Thank you all, this problem was resolved!! hip! hip! hurra!

**Comment by ajcvickers** [comment]
> I encounter Lazy Loading very useful, is there a way to implement something like LL in this approach?

Loading an entity requires a DbContext and its associated database connection. To achieve this, lazy loading requires the the entity instance keep a reference to the DbContext that was used when it was queried. This is usually handled by the automatically generated proxy type, so you don't see it. However, even though it is hidden, it is still there and couples the entity instance to the context.

This means that when lazy-loading is triggered, the context referenced must not be disposed, which in turn means that it is no longer possible to query the entity and then dispose the context. Instead, the lifetime of the context must be managed at a higher scope--for example, for the entire request. This can be difficult to do, especially in scenarios like yours.

In addition, since the DbContext and its associated connection are not thread-safe, it is important to ensure that lazy-loading happens on the same thread as the original query, or the loading is protected in some other way to ensure it does not happen concurrently with the query. This is again difficult to do in a scenario like yours.

Finally, lazy-loading queries are always synchronous. This means you will have more thread blocking when using lazy loading than will be the case if you just execute async queries.
