### ISSUE TITLE
How to *not* nest entities with CosmosDb provider?

### ISSUE THREAD

**Issue by rallianto** [dotnet/efcore#26746]
Just saw the presentation on EF Core 6 with CosmosDb provider here: https://www.youtube.com/watch?v=MicJm1hRNKU

Now sub-entities are nested automatically, which begs the question. How do we add related entities, without nesting them?

If I want, let's say a product, to be shown in multiple catalogs, I wouldn't go and have copies of the product, nested in each catalog.
If I want to insert a Catalog, that has a nested Product, but I want Catalog and Product to go their own collection (or not be nested and redundant), how to I do that?

**Comment by ajcvickers** [comment]
@rallianto Just explicitly configure the relationship in the normal way with `HasOne`, `HasMany`, etc. It will override the implicit ownership.

**Comment by rallianto** [comment]
So if I have some Catalog's, each have a list of Product's to show. I would configure it like this:
`modelBuilder.Entity<Catalog>()
        .HasMany(c => c.Product));`

**Comment by ajcvickers** [comment]
@rallianto Yes, although you should also configure the inverse with `WithOne`. See [Relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key) in the docs.

**Comment by rallianto** [comment]
Okay so for Catalog:
`modelBuilder.Entity<Catalog>().HasMany(c => c.Product));`

For the Product:
`modelBuilder.Entity<Product>().HasOne(c => c.Catalog));`

So I assume a rule of thumb for working with EF Core 6 and Cosmos Db:
If nothing has been configured, the children will be nested into one document
If you do configure, like shown above, you can 'split' your entities into different documents
Thank you very much!
