### ISSUE TITLE
Code inheritance without database inheritance

### ISSUE THREAD

**Issue by andre9349** [dotnet/efcore#26741]
I have two EF models:

```C#
public class Child: BaseClass
{ 
    public string SomeProp {get; set;}
}
```

```C#
[Table("TableName")]
public abstract class BaseClass
{
    public int ID {get; internal set;}
    ... some other properties and navigation collections...
}
```
I have only one table "TableName" with all columns from "BaseClass" and "Child" classes and I would use 'Child' type to access the table. 
But, when i've tried to do it, i got exception: "Invalid column name 'Discriminator'."
With EF 6, I was able to do it.

**Comment by roji** [comment]
@andre9349 it looks like you're trying to do a simple Table-Per-Hierarchy (TPH) mapping, which is fully supported ([see the docs](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration)). Can you please post a runnable code sample which reproduces the problem?

**Comment by andre9349** [comment]
> @andre9349 it looks like you're trying to do a simple Table-Per-Hierarchy (TPH) mapping, which is fully supported ([see the docs](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration)). Can you please post a runnable code sample which reproduces the problem?

I sure what Discriminator and TPH are. But in my case there isn't real inheritance - there is only one child type on base class per context and we don't need discriminator. I just trying to use common base class in differrent contexts to avoid copy-paste .

https://drive.google.com/file/d/140UZ2EiBZ00cIHtBhiDLsrVj-a0OiEeb
I tried to attach zip file here, but it fails.
I've attached a solution with two projects: first on EF Core 5, second on EF6. Databases test.sqlite in both bin/debug folders are the same. The query completes successfully on EF6 and fails on EF Core (Mappings are equals).

**Comment by ajcvickers** [comment]
@andre9349 I'm not sure how this was working in EF6, but I suspect that the base class was not mapped--i.e., it was acting as an unmapped base class. I was able to get your repro working by doing the same on EF Core. Specifically:

* Don't configure the base type. No `modelBuilder.Entity` call. No EntityTypeConfiguration.
* Move the Table attribute to the derived type.

For example:

```C#
    public abstract class BaseClass
    {
        public int ID { get; set; }
    }

    [Table("SomeTable")]
    public class ChildClass : BaseClass
    {
        public string Foo { get; set; }
    }

    public class EFCoreContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=test.sqlite");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ChildClass>();
        }
    }
```

**Comment by andre9349** [comment]
> @andre9349 I'm not sure how this was working in EF6, but I suspect that the base class was not mapped--i.e., it was acting as an unmapped base class. I was able to get your repro working by doing the same on EF Core. Specifically:
> 
> * Don't configure the base type. No `modelBuilder.Entity` call. No EntityTypeConfiguration.
> * Move the Table attribute to the derived type.

Ok, it I'll work in simple case. But if we add other entity with foreign key to "BaseClass", EF Core starts join table "BaseClass" and throws an exception, even BaseClass isn't mapped:
`SQLite Error 1: 'no such table: BaseClass'."`
In EF6, it works (with BaseClass mapping).
Please check my updated solution https://drive.google.com/file/d/140UZ2EiBZ00cIHtBhiDLsrVj-a0OiEeb.

**Comment by ajcvickers** [comment]
> Ok, it I'll work in simple case. But if we add other entity with foreign key to "BaseClass", EF Core starts join table "BaseClass" and throws an exception, even BaseClass isn't mapped:

When I copy the entity classes from your EF Core project into the EF6 project, then it also maps the base class:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/1430078/142924175-7421fe66-4c6a-4878-a7da-f09fb8dfd85e.png">

I've spent some time debugging into your sample, but I'm really unsure which of the differences between the two projects are incidental, and which are intentional. It would really help if you could update the sample to have the same entity types for both projects, and the same explicit configuration in both projects. By explicit configuration, I mean not discovering configuration from the assembly, but rather explicitly configuring the types that are intended to be mapped.

**Comment by andre9349** [comment]
> It would really help if you could update the sample to have the same entity types for both projects, and the same explicit configuration in both projects. By explicit configuration, I mean not discovering configuration from the assembly, but rather explicitly configuring the types that are intended to be mapped.

I don't completely understand what I should to do but I've updated my sample as you ask: now I use the same models in both projects (I've made a reference from .NET 5 project to .NET framework project).
Also I've removed mapping classes from EF6 project and place all mappings into OnModelCreating() method.

**Comment by ajcvickers** [comment]
@andre9349 I'm going to ask @AndriySvyryd to take a look at this, since I don't understand why the table is not mapped in EF6.

**Comment by andre9349** [comment]
I've made a workaround - create column "Discriminator" with default single value. It works, but it would be great if you fix it.

**Comment by ajcvickers** [comment]
Note from triage: we're not sure why EF6 is creating the model in this way. It seems possible that it is creating a TPC mapping, which is tracked in EF Core by #3170.
