### ISSUE TITLE
SaveChangesAsync doesn't preserve the sync context across retries

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26763]
In [this Helix build](https://dev.azure.com/dnceng/public/_build/results?buildId=1477673&view=logs&j=f95328f7-07f5-5106-5c2a-5dc7069f305c) we have the following [test failure](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-efcore-refs-pull-26723-merge-4311429c9bd948b5bf/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.dll/1/console.284d46c7.log?sv=2019-07-07&se=2021-12-09T12%3A00%3A16Z&sr=c&sp=rl&sig=l1vTnIZuvkC6JKjKDoOd%2Ftqf0tVmhUikM%2FhejIgooRk%3D), seems to be flaky:

```
    Microsoft.EntityFrameworkCore.Query.QueryBugsTest.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841 [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        D:\a\_work\1\s\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs(9132,0): at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841()
        --- End of stack trace from previous location ---
```

**Comment by ajcvickers** [comment]
@roji Disable the test for now?

**Comment by roji** [comment]
I think we've only seen it fail like once (AFAIK), will try to take a look at it in the next few days, if it fails again we can disable for sure...

**Comment by ajcvickers** [comment]
@roji I am probably missing something, but it looks to me like SaveChangeAsync always uses `ConfigureAwait(false)`.

```C#
var entitiesSaved = interceptionResult.HasResult
    ? interceptionResult.Result
    : await DbContextDependencies.StateManager
        .SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken)
        .ConfigureAwait(false);
```

https://github.com/dotnet/efcore/blob/197479e871148acfc882cd166e8ac28a089a30c9/src/EFCore/DbContext.cs#L730

**Comment by roji** [comment]
@ajcvickers as discussed offline, ConfigureAwait controls where the continuation rnus, i.e. the code *after* SaveChangesAsync - and we don't really care about that.

**Comment by vonzshik** [comment]
@roji from the looks of it, SingleThreadSynchronizationContext22841 has the same issue, SingleThreadSynchronizationContext had in npgsql (npgsql/npgsql/issues/3856).

**Comment by ajcvickers** [comment]
@roji SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841 just failed on my C.I. run.

**Comment by smitpatel** [comment]
Also failed in https://github.com/dotnet/efcore/pull/27011

**Comment by roji** [comment]
@vonzshik that's exactly what #27019 is supposed to address (I did it just 4 hours before your comment :wink:).

However, I can't see how SaveChangesAsync wouldn't yield... it's guaranteed to insert a row into SQL Server, which is supposed to always do networking and yield... If there's some situation in which SqlClient does sync I/O instead of async, then that would explain it; I'm not aware of such a thing (and it shouldn't happen), but it's possible.

**Comment by ajcvickers** [comment]
@roji It's not doing "networking" when using LocalDb. It's doing named-pipes.

**Comment by roji** [comment]
AFAIK that's still I/O that's supposed to be async... Put another way, if LocalDB communication were always sync, this test would have failed consistently, rather than being flaky. But maybe under some conditions SqlClient decides to do sync I/O...

**Comment by vonzshik** [comment]
> AFAIK that's still I/O that's supposed to be async... Put another way, if LocalDB communication were always sync, this test would have failed consistently, rather than being flaky. But maybe under some conditions SqlClient decides to do sync I/O...

Well, for example, SqlClient's login handshake is sync only (because it's called from a constructor) :trollface:

https://github.com/dotnet/SqlClient/blob/c56baaabb641de6dd595203f78a2e93b65ac2317/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L537

**Comment by roji** [comment]
:confused: 

I'd still hope that ExecuteReaderAsync (as opposed to logging in) would actually be async - but you're right that we can't be sure...

**Comment by roji** [comment]
Keeping open for a few days to make sure we re-discuss in triage and see if the test failed after #27019.
