### ISSUE TITLE
Can't concat/union two IQueryable<> of types inherited from one parent 

### ISSUE THREAD

**Issue by andre9349** [dotnet/efcore#26762]
I have following clasess:
```
public class A : BaseClass
{
    public string Prop1 {get; set;}
}
public class B : BaseClass
{
    public string Prop2 {get; set;}
}
```
And i'm trying to make query like this:
`var list = context.Set<A>().Where(x => x.Prop1 == "foo").Cast<BaseClass>().Concat(context.Set<B>().Where(x => x.Prop2 == "bar")).ToArray()`

And I got exception like this:
`Expression of type 'System.Linq.IOrderedQueryable1[A]' cannot be used for parameter of type 'System.Linq.IQueryable1[B]' of method 'System.Linq.IQueryable1[B] Concat[B](System.Linq.IQueryable1[B], System.Collections.Generic.IEnumerable1[B])' Arg_ParamName_Name"`

In EF 6, this construction works fine.
How can I make UNION of two different types on server side with EF Core?

**Comment by smitpatel** [comment]
Please provide a runnable repro code which demonstrate the exception you are hitting.

**Comment by andre9349** [comment]
> Please provide a runnable repro code which demonstrate the exception you are hitting.

https://drive.google.com/file/d/1bTQDEnCKKqfvgkZHBeK51UMLtRkKtXMj

**Comment by ajcvickers** [comment]
@smitpatel Isn't this a duplicate of #16298?

/cc @roji

**Comment by smitpatel** [comment]
Exception 
```
Unhandled exception. System.ArgumentException: Expression of type 'System.Linq.IQueryable`1[ConsoleApp21.ChildClass]' cannot be used for parameter of type 'System.Linq.IQueryable`1[ConsoleApp21.ChildClass2]' of method 'System.Linq.IQueryable`1[ConsoleApp21.ChildClass2] Concat[ChildClass2](System.Linq.IQueryable`1[ConsoleApp21.ChildClass2], System.Collections.Generic.IEnumerable`1[ConsoleApp21.ChildClass2])' (Parameter 'arg0')
```
Yes duplicate of #16298, should have thrown better error message.
