### ISSUE TITLE
ColumnOrder with different behaviour between Create and Alter table ?

### ISSUE THREAD

**Issue by juchom** [dotnet/efcore#26765]
We have a `BaseEntity` with fields that will exists in all entities

```C#
public abstract class BaseEntity
{
    // I would like to have it as the first column
    public int Id { get; private set; } = Ulid.NewUlid();

   // I would like to have all the properties of my entities that inherit this class here


    // I would like to have it as the last columns
    public DateTime CreatedAtUtc { get; private set; } = DateTime.UtcNow;
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
```

Now I have a simple class where I want `MyField` to be right after `Id` and before `CreatedAtUtc`

```C#
public class MyEntity : BaseEntity
{
    public string MyField { get; private set; }
}
```

Here is the `BaseEntity` configuration

```C#
public abstract class BaseEntityConfiguration<T> : IEntityTypeConfiguration<T> where T : BaseEntity
{
    public virtual void Configure(EntityTypeBuilder<T> builder)
    {
        builder.Property(p => p.Id)
            .HasColumnOrder(0);  // Will be first column

        builder.Property(p => p.CreatedAtUtc)
            .HasColumnOrder(1000); // Big values to make sure it will be last field
        builder.Property(p => p.UpdatedAtUtc)
            .HasColumnOrder(1001);
    }
}
```

Now, below is `MyEntity` configuration that inherits from the config just above

```C#
public class MyEntityConfiguration : BaseTenantEntityConfiguration<MyEntity>
{
    public override void Configure(EntityTypeBuilder<MyEntity> builder)
    {
        base.Configure(builder);

        builder.Property(p => p.MyField)
               .HasMaxLength(32);
    }
}
```

Generated column order, if I'm not specifiying `HasColumnOrder(1)` in `MyEntityConfiguration`

```
Id
CreatedAtUtc
UpdatedAtUtc

MyField
```

Generated column order, if I'm specifiying `HasColumnOrder(1)` in `MyEntityConfiguration`

```
Id

MyField

CreatedAtUtc
UpdatedAtUtc
```

Is there a way to have the second generated orders without specifying `HasColumnOrder` for every fields on a `CREATE TABLE` only ?

**Comment by ajcvickers** [comment]
@juchom No; For the column to be ordered before any other columns, then it needs to have an index that places it there. Otherwise it goes to the end.

**Comment by juchom** [comment]
Ok thanks for the quick reply !

Are there any drawbacks or side effects, if I edit the generated migrations to have the the `CreatedAtUtc` and `UpdatedAtUtc` at the end of the columns ?

**Comment by ajcvickers** [comment]
@juchom No drawbacks. IMO, that's the best way to handle column order in general.

**Comment by juchom** [comment]
Actually, if I modify `BaseEntityConfiguration`  like this

```C#
public abstract class BaseEntityConfiguration<T> : IEntityTypeConfiguration<T> where T : BaseEntity
{
    public virtual void Configure(EntityTypeBuilder<T> builder)
    {
        builder.Property(p => p.Id)
            .HasColumnOrder(0);
   }
}
```

This does exactly what I was expected !
