### ISSUE TITLE
Many To Many Exception when adding and removing same entity

### ISSUE THREAD

**Issue by DanielBlazevic** [dotnet/efcore#26779]
## File a bug

Not sure if this is bug, but I noticed different behavior when using many-to-many feature in "old" and "new" way.

If I configure many-to-many in "old" way with third model defined (Post, Tag, PostTag) and test adding and removing same PostTag, everything works as expected. Nothing is changed and no saves are necessary.

But if I do it "new" way without third model defined (only Post and Tag) and test adding Tag to Post and then removing the same Tag from same Post I get exception when trying to save changes, because context tries to delete PostTag entity which does not exists in database.

### Include your code

Example code can be found in [https://github.com/DanielBlazevic/EFCoreTest](https://github.com/DanielBlazevic/EFCoreTest)

```C#
    static void SeedData()
    {
        var ctx = new Context();

        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();

        var post = new Post() { Title = "Post 1" };

        var tag = new Tag() { Text = "Tag 1" };

        ctx.Add(post);
        ctx.Add(tag);

        ctx.SaveChanges();
    }
```
"Old" way:
```C#
    static void Main(string[] args)
    {
        SeedData();

        var ctx = new Context();

        var post = ctx.Posts.First();

        var tag = ctx.Tags.First();

        var postTag = new PostTag() { Post = post, Tag = tag };

        post.PostTags.Add(postTag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        post.PostTags.Remove(postTag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        ctx.SaveChanges(); // <- Nothing to save, no exception
    }
```

"New" way:
```C#
    static void Main(string[] args)
    {
        SeedData();

        var ctx = new Context();

        var post = ctx.Posts.First();

        var tag = ctx.Tags.First();

        post.Tags.Add(tag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        post.Tags.Remove(tag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        ctx.SaveChanges(); // <- Tries to delete PostTag entity, Exception here
    }
```

### Exception

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: 'The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.'
```

### Include provider and version information

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer / Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10 x64
IDE: Visual Studio 2022

**Comment by BewaControl-ReneDivossen** [comment]
Try Including Tags when you load your post:
var post = ctx.Posts.Include(p => p.Tags).First();

**Comment by DanielBlazevic** [comment]
Already tried that, same results.

**Comment by ajcvickers** [comment]
Note for triage: looks like a bug, but may be complicated by join entity synthesis.
