### ISSUE TITLE
Migrations bundle EF core 6 error

### ISSUE THREAD

**Issue by vekani** [dotnet/efcore#26782]
## Ask a question

 **I´m trying to generate a migration using the new feature migration bundle**, but with any project the migration bundle fails and always throws the same message, with different applications, as well as when the example that I found here : 
[MinimalApiExample](https://github.com/anuraj/MinimalApi)  

Using visual studio 2022 or PowerShell

PS C:\MinimalApi-main> dotnet ef --version
Entity Framework Core .NET Command-line Tools
6.0.0-preview.7.21378.4

1. I have update dotnet tool:

dotnet tool update --global dotnet-ef --version 6.0.0-preview.7.21378.4
Tool 'dotnet-ef' was successfully updated from version '5.0.5' to version '6.0.0-preview.7.21378.4'.

2. I use this frameworks
```
  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="6.0.0-rc.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
  </ItemGroup>
```

3. I run the command: 
**dotnet ef migrations bundle --verbose**

Building bundle...
dotnet publish --output C:\Users\User\AppData\Local\Temp\5uzvyk12.n4x\publish
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\User\AppData\Local\Temp\5uzvyk12.n4x\bundle.csproj (in 403 ms).
  1 of 2 projects are up-to-date for restore.
  MinimalApi -> C:\MinimalApi-main\bin\Debug\net6.0\MinimalApi.dll
**C:\Users\User\AppData\Local\Temp\5uzvyk12.n4x\Program.cs(4,8): error CS0103: The name 'MigrationsBundle' does not exist in the current context [C:\Users\User\AppData\Local\Temp\5uzvyk12.n4x\bundle.csproj]**
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Build failed. Use --verbose to see errors.

**Comment by ajcvickers** [comment]
@vekani Please update to version 6.0.0 of the dotnet-ef tool.

**Comment by vekani** [comment]
The error is resolved, but now the bundle throws a different error that is reported by other users like [#19693](https://github.com/dotnet/efcore/issues/19693)
I have updated tool version
**PS C:\MinimalApi-main> dotnet ef --version**
Entity Framework Core .NET Command-line Tools
6.0.0

With any application I have the same error

**PS C:\MinimalApi-main> dotnet ef migrations bundle --verbose**

C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3027: Could not copy "obj\Debug\net6.0\MinimalApi.dll" to "bin\Debug\net6.0\MinimalApi.dll". Exceeded retry count of 10. Failed.  [C:\MinimalApi-main\MinimalApi.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3021: Unable to copy file "obj\Debug\net6.0\MinimalApi.dll" to "bin\Debug\net6.0\MinimalApi.dll". The process cannot access the file 'C:\MinimalApi-main\bin\Debug\net6.0\MinimalApi.dll' because it is being used by another process. [C:\MinimalApi-main\MinimalApi.csproj]
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

I have tried what other users but always the same error.

**Comment by ajcvickers** [comment]
@vekani This is being investigated and tracked by #25555.
