### ISSUE TITLE
Entity's state should be modified if entity's owned object is modified.

### ISSUE THREAD

**Issue by IvanZheng** [dotnet/efcore#26783]
If we change entity's owned object (change owned object's properties or totally replace the owned object), the entity's state in ChangeTracker will still be unchanged. According to the DDD's aggregate, there is no difference between value object (owned object) and other primary values (int, string) in an entity. Since entity's primary properties changing will make entity's state modified, owned object changing should also make it modified.
I want to do something in dbcontext.SaveChange for modified aggregate root, such as setting modified time, publishing domain events which belong to the aggregate root.  It's appreciated that I can find the all modified aggregate roots with ChangeTracker even if their owned objects are modified.

**Comment by ajcvickers** [comment]
@IvanZheng Defining appropriate behaviors for aggregates is tracked by https://github.com/dotnet/efcore/issues/13947. In addition, owned types are not a good match for DDD value objects. See https://github.com/dotnet/efcore/issues/9906 and https://github.com/dotnet/efcore/issues/13947.

**Comment by IvanZheng** [comment]
I know that struct is better to match the value objects, but efcore doesn't support it. So, Is there any plan to implement it? And when will it support?

**Comment by ajcvickers** [comment]
@IvanZheng This isn't about classes verses structs. This is about not mapping value objects as entity types. Check the issues that I referenced.

**Comment by IvanZheng** [comment]
@ajcvickers Something like IValueObjectTypeConfiguration is going to support mapping value objects in 7.0.0 milestone, isn't it? It's inspiring.
