### ISSUE TITLE
[Q] SqlServerConventionSetBuilder and valueGenerationConvention [SqlServerValueGenerationConvention]

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#26789]
Hello,

EF6.0

**Question**
Why SqlServerConventionSetBuilder.CreateConventionSet does not replace valueGenerationConvention in conventionSet.ForeignKeyPropertiesChangedConventions and conventionSet.ForeignKeyOwnershipChangedConventions?

It is correct (by design) or it is small mistake?

**Some research**

ProviderConventionSetBuilder.CreateConventionSet

valueGeneratorConvention [ValueGenerationConvention] registered in:
 - conventionSet.EntityTypeBaseTypeChangedConventions [add] +
 - conventionSet.EntityTypePrimaryKeyChangedConventions [add] +
 - conventionSet.ForeignKeyAddedConventions [add] +
 - conventionSet.ForeignKeyRemovedConventions [add] +
 - conventionSet.ForeignKeyPropertiesChangedConventions [add] +
 - conventionSet.ForeignKeyOwnershipChangedConventions [add] +

(+) - will replaced in derived class

RelationalConventionSetBuilder.CreateConventionSet

valueGenerationConvention[RelationalValueGenerationConvention] registered in:
 - conventionSet.EntityTypeBaseTypeChangedConventions [replace] +
 - conventionSet.ForeignKeyPropertiesChangedConventions [replace]
 - conventionSet.ForeignKeyOwnershipChangedConventions [replace]
 - conventionSet.EntityTypeAnnotationChangedConventions [add] +
 - conventionSet.EntityTypePrimaryKeyChangedConventions [replace] +
 - conventionSet.ForeignKeyAddedConventions [replace] +
 - conventionSet.ForeignKeyRemovedConventions [replace] +
 - conventionSet.PropertyAnnotationChangedConventions [add] +

So, this method completely replaces ValueGenerationConvention instance

SqlServerConventionSetBuilder.CreateConventionSet

valueGenerationConvention [SqlServerValueGenerationConvention] registered in:
 - conventionSet.EntityTypeBaseTypeChangedConventions [replace]
 - conventionSet.EntityTypeAnnotationChangedConventions [replace]
 - conventionSet.EntityTypePrimaryKeyChangedConventions [replace]
 - conventionSet.ForeignKeyAddedConventions [replace]
 - conventionSet.ForeignKeyRemovedConventions [replace]
 - conventionSet.PropertyAnnotationChangedConventions [replace]

 Not replaced in:
 - ForeignKeyPropertiesChangedConventions [IForeignKeyPropertiesChangedConvention]
 - ForeignKeyOwnershipChangedConventions [IForeignKeyOwnershipChangedConvention]
  
IForeignKeyPropertiesChangedConvention and IForeignKeyOwnershipChangedConvention
 - implemented in ValueGenerationConvention class
 - use a virtual method GetValueGenerated(IConventionProperty property)

SqlServerValueGenerationConvention overrides GetValueGenerated method.

So, conventionSet still contains instance of RelationalValueGenerationConvention which may works not propertly?

Thanks for answers.

**Comment by AndriySvyryd** [comment]
Mistake. Will be fixed by #214
