### ISSUE TITLE
Which fluent builder APIs can I safely omit when not using code generation or migrations?

### ISSUE THREAD

**Issue by nathan-alden-sr** [dotnet/efcore#26792]
I am defining my PostgreSQL data model completely by hand and also my EF entities by hand. I can't find any documentation that states what fluent builder APIs I _must_ use and what APIs have no effect in database-first. As an example, does me defining a key or index in code lead to indexing hints being generated by query builders internally?

Among others, do I need to define the following:

- Primary keys (`HasKey`)
- Indexes, both unique and non-unique (`HasIndex`)
- Foreign key names (`HasConstraintName`)
- Foreign key cascade rules (`OnDelete`)
- Default values (`HasDefaultValueSql`)

I suspect the answer is "no" to these, but I want to make sure with some authoritative guidance.

Instead of this:
```cs
public sealed class IdentityAuthenticationHistoryConfiguration : IEntityTypeConfiguration<IdentityAuthenticationHistory>
{
    public void Configure(EntityTypeBuilder<IdentityAuthenticationHistory> builder)
    {
        builder.ToTable("identity_authentication_history");

        builder
            .HasKey(
                a => new
                {
                    a.IdentityId,
                    a.Sequence
                })
            .HasName("identity_authentication_history_pk");

        builder
            .HasIndex(a => a.Sequence, "identity_authentication_history_sequence_idx")
            .IsUnique()
            .HasSortOrder(SortOrder.Descending);

        builder
            .Property(a => a.IdentityId)
            .ValueGeneratedNever();

        builder
            .Property(a => a.Sequence)
            .ValueGeneratedOnAdd()
            .HasDefaultValueSql("nextval('identity_authentication_history_sequence'::regclass)");

        builder.Property(a => a.Method);

        builder.Property(a => a.Succeeded);

        builder.Property(a => a.Timestamp);

        builder
            .HasOne(a => a.Identity)
            .WithMany(a => a.IdentityAuthenticationHistories)
            .HasForeignKey(a => a.IdentityId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("identity_authentication_history_identity_fk");
    }
}
```
can I just do this:
```cs
public sealed class IdentityAuthenticationHistoryConfiguration : IEntityTypeConfiguration<IdentityAuthenticationHistory>
{
    public void Configure(EntityTypeBuilder<IdentityAuthenticationHistory> builder)
    {
        builder.ToTable("identity_authentication_history");

        builder
            .Property(a => a.IdentityId)
            .ValueGeneratedNever();

        builder
            .Property(a => a.Sequence)
            .ValueGeneratedOnAdd();

        builder.Property(a => a.Method);

        builder.Property(a => a.Succeeded);

        builder.Property(a => a.Timestamp);

        builder
            .HasOne(a => a.Identity)
            .WithMany(a => a.IdentityAuthenticationHistories)
            .HasForeignKey(a => a.IdentityId);
    }
}
```

**Comment by ajcvickers** [comment]
@nathan-alden-sr 

Generally, EF Core needs to know about most of the constructs you mention at runtime, with the notable exceptions being constraint names, and the actual SQL in default and computed column constraints. (EF Core does need to know if the constraint itself exists.)

However, EF Core also has conventions for things like automatic configuration of [keys](https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations) and discovery of [relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key). There is no harm in configuring these things anyway, but learning the conventions can reduce the amount of code in your model configurations.

See also https://github.com/dotnet/EntityFramework.Docs/issues/3540 and https://github.com/dotnet/efcore/issues/10890

**Comment by nathan-alden-sr** [comment]
Thanks. This is just what I was looking for.

An exhaustive list of the fluent APIs that are important in database-first design would be very welcomed. It goes beyond the top-level methods like `HasKey` and `HasIndex` to further refinements like `HasSortOrder`. I tried browsing the `efcore` source last night with ReSharper but everything is so abstracted behind builders and such that I found it impossible to determine usages.

**Comment by ErikEJ** [comment]
@nathan-alden-sr You could reverse engineer a database and get an idea.

**Comment by nathan-alden-sr** [comment]
That's what I had done originally. The issue is it generates a whole lot of unneeded code (now that I have a better idea of what is needed and what isn't). I only just learned this morning that I don't even need to call `Property` because there's a convention that all public properties will be picked up.

It seems like there are two classifications of "required" here:

1. Required for the EF runtime to properly interact with the database and its own architecture (e.g., keys, foreign keys, unique indexes, etc.)
2. Required only in cases where convention-based configuration might lead to unexpected results (e.g., `Property()` is unnecessary if all `public` properties in an entity are intended to be mapped).

**Comment by ajcvickers** [comment]
@nathan-alden-sr The scaffolder is designed to not generate configuration that matches conventions. For example, it won't generate `HasKey` calls for keys that are called `Id`. (There are a few bugs in this, please file others if you find them.) However, it does generate configuration for things like constraint names that are not needed by the runtime--this is what #10890 is about.

We discussed this recently and came to the conclusion that _only constraint names_ are really safe to remove. Other configuration should be included in the model. Almost all of it is used already by the runtime, and the things that are not used now may be used in the future. For example, early versions of EF Core didn't make use of database index metadata at runtime, but that changed to improve ordering in the update pipeline.

So, the bottom line is that it's okay not include explicit configuration for things EF configures by convention. All other configuration should be included, except it's safe to not configure database constraint names.

Also, `context.Model.DebugView` (or `ToDebugString`) is your friend when examining the models EF creates. For example:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1430078/143291836-8de338e2-66bc-40c6-a0fb-e11481f78c88.png">

**Comment by nathan-alden-sr** [comment]
Thanks for the guidance! This is really useful.
