### ISSUE TITLE
Adding graph of entries to already filled ChangeTracker

### ISSUE THREAD

**Issue by mtomberger2** [dotnet/efcore#26803]
I have a query expression which I can't change. It cannot be converted to SQL and client evaluation is not possible as of 3.1
As a result i had to load all entries using ```Entries.AsEnumerable().AsNoTracking()``` and apply the expression later (see: [https://github.com/dotnet/efcore/issues/26747](url)). As the results of this query should be changed and saved later I had to re-add them to the  ChangeTracker using ```.AttachRange()``` which works fine if the ChangeTracker is empty at this time.

If there are already entries in the ChangeTracker that would be added again with the ```.Attach()``` the method throws:
```
The instance of entity type 'PaymentLevel' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.
When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
```
This occurs when the query includes values from other tables with  ```.Include("Payments.PaymentPlan.PaymentLevel")```
I tried to only attach the entries to the ChangeTracker if they aren't already there as adviced [here](https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution#resolve-duplicates) but its very slow for more than 100 entries.

**How can i attach a graph of untracked entities to the ChangeTracker which might have already tracked some of the entities referenced in the untracked graph in acceptable time?**

## The example

The database has the entities and relations described below. I try to query for employees including with  ``` "Payments.PaymentPlan.PaymentLevel" ``` with a not convertable query so i have to load every entry without tracking, execute the query and only reattach the result.  I try to avoid attaching the all results, as this pollutes the ChangeTracker with many entries. 

![erd4](https://user-images.githubusercontent.com/94608236/143046660-8222d997-3246-4ea5-90c9-60a224006dc6.png)

This works as the ChangeTracker is empty before the query.

```
var employee = db.Employee
  .AsQueryable()
  .Include("Payments.PaymentPlan.PaymentLevel")
  .AsNoTrackingWithIdentityResolution()
  .AsEnumerable()
  .FirstOrDefault(unconvertableExpression.Compile());
db.Attach(employee);
```

With some entries attached to the ChangeTracker it fails with the Exception described above.

```
//load some entries before querying
var plans = db.PaymentPlan.Include("PaymentLevel").ToList();
var employee = db.Employee
  .AsQueryable()
  .Include("Payments.PaymentPlan.PaymentLevel")
  .AsNoTrackingWithIdentityResolution()
  .AsEnumerable()
  .FirstOrDefault(unconvertableExpression.Compile());
db.Attach(employee);
```

Attaching only not attached entries works again but is very slow (> 2 sec attaching one entry). 

```
//load some entries before querying
var plans = db.PaymentPlan.Include("PaymentLevel").ToList();
var employee = db.Employee
  .AsQueryable()
  .Include("Payments.PaymentPlan.PaymentLevel")
  .AsNoTrackingWithIdentityResolution()
  .AsEnumerable()
  .FirstOrDefault(unconvertableExpression.Compile());
db.ChangeTracker.TrackGraph(employee, node => {
  var keyValue = node.Entry.Property("Id").CurrentValue;
  var entityType = node.Entry.Metadata;
  var existingEntity = node.Entry.Context.ChangeTracker.Entries()
      .FirstOrDefault(
          e => Equals(e.Metadata, entityType)
               && Equals(e.Property("Id").CurrentValue, keyValue));

  if (existingEntity == null)
  {
      node.Entry.State = EntityState.Modified;
  }
});
```

## What I sadly can't do

* Ensure that the ChangeTracker is always empty
* Ensure there are no tracked entries overlapping with the query result
* Rewrite the not convertable query
* Load all entries with tracking (blows up the ChangeTracker)
* Reduce the ```.Include()``` content as that data is needed later on

## Additional info

EF Core version: 2.1 / 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 2.1 / .NET 5.0
Operating system: Windows 10 Home
IDE: Visual Studio 2019 16.10.3

## Minimal reproducible example

[EfCoreAttachEntriesExample.zip](https://github.com/dotnet/efcore/files/7588572/EfCoreAttachEntriesExample.zip)

**Comment by ajcvickers** [comment]
@mtomberger2 Most of the time in the "very slow" version is taken by the repeated calls to `Entries`, which in turn does [automatic  DetectChanges](https://docs.microsoft.com/en-us/ef/core/change-tracking/change-detection). Here's numbers from my machine (limited to the two interesting tests and running each test twice so as not to measure query compilation):

```
test...
EntityFramework Core 5.0 - 2 - works as long as the ChangeTracker is empty before the execution:
    1 Entities tracked. 1431ms
---------------------
EntityFramework Core 5.0 - 4 - Manually check if the entries are already tracked - VERY SLOW:
    1 Entities tracked. 1891ms
---------------------
EntityFramework Core 5.0 - 2 - works as long as the ChangeTracker is empty before the execution:
    1 Entities tracked. 1060ms
---------------------
EntityFramework Core 5.0 - 4 - Manually check if the entries are already tracked - VERY SLOW:
    1 Entities tracked. 1855ms
---------------------
```

Disabling automatic `DetectChanges` like this:

```C#
try
{
    db.ChangeTracker.AutoDetectChangesEnabled = false;

    db.ChangeTracker.TrackGraph(employee, node =>
    {
        var keyValue = node.Entry.Property("Id").CurrentValue;
        var entityType = node.Entry.Metadata;
        var existingEntity = node.Entry.Context.ChangeTracker.Entries()
            .FirstOrDefault(
                e => Equals(e.Metadata, entityType)
                     && Equals(e.Property("Id").CurrentValue, keyValue));

        if (existingEntity == null)
        {
            node.Entry.State = EntityState.Modified;
        }
    });
}
finally
{
    db.ChangeTracker.AutoDetectChangesEnabled = true;
}
```

Results in these numbers:

```
test...
EntityFramework Core 5.0 - 2 - works as long as the ChangeTracker is empty before the execution:
    1 Entities tracked. 1409ms
---------------------
EntityFramework Core 5.0 - 4 - Manually check if the entries are already tracked - VERY SLOW:
    1 Entities tracked. 1163ms
---------------------
EntityFramework Core 5.0 - 2 - works as long as the ChangeTracker is empty before the execution:
    1 Entities tracked. 1038ms
---------------------
EntityFramework Core 5.0 - 4 - Manually check if the entries are already tracked - VERY SLOW:
    1 Entities tracked. 1071ms
---------------------
```
