### ISSUE TITLE
How to query if a varbinary has a byte value?

### ISSUE THREAD

**Issue by mcguu** [dotnet/efcore#26809]
There is a `varbinary` in my table.
and I want to query if it has 0x05 or others byte.

for example.
maybe the varbinary is `00 10 01 10 05 03` or `00` or `00 01`

**Comment by mcguu** [comment]
@ajcvickers  thank you

**Comment by roji** [comment]
@mcguu assuming your `varbinary` column is mapped as a .NET `byte[]` property, then simply calling Contains on that works:

```c#
_ = ctx.Blogs
    .Where(b => b.Data.Contains((byte)80))
    .ToList();
```

... produces the following SQL:

```sql
SELECT [b].[Id], [b].[Data], [b].[Name]
FROM [Blogs] AS [b]
WHERE CHARINDEX(0x50, [b].[Data]) > 0
```

**Comment by roji** [comment]
@mcguu the SQL Server provider doesn't natively support mapping arrays of enums - are you using a value converter? If so, the provider wouldn't translate Contains on that (#10434 tracks that), though you should be able to define your own method and map it via [user-defined function translation](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping).

Otherwise can you please post some code showing what you'er trying to do?

**Comment by mcguu** [comment]
What I want to do is to make a permission table.

the permission is to the groups no matter who creates the group if he has the permission then he can do the operation.

I am a newbie so what I consider may be wrong.

So I think there should be columns of : `Id`,`ClaimId`,`ClaimType`,`UserId`
the `claimId` is the group id and the userId is the user's Id.
ClaimType is the operation that one can do like `GetGroup`,`UpdateGroup` so I consider it to be byte or enum?
means the ClaimType maybe `0x01 0x02 0x03` or `GetGroup;UpdateGroup;DeleteGroup` or `1,2,3`.
and what is more
I also want to query the relation of each users
for example user01 has the permission of group01,group02,group03
and he give the permission of group01 to user02,group02 to user03,group03 to user10.
then 
                    ------------
                  - user01     -
                  - -----------
      -------             ------------         ----------
     -user02-          - user03   -         - user10-
    ----------          ------------        -----------
user02 or user03 can also give the permisson(some or all) to others

and other can also create his self group which user01 have not the permisson but I still can get the list to write this relation of the users.
I wonder if there is any better solution for you experienced great guy?

so what I want is:
1. can easily change the permisson of each user
2. can get the relations by a group or userid or claimId.

thank you.

**Comment by roji** [comment]
@mcguu you could indeed model your permission table as above, with each row assigning a specific claim to a user and/or group. In that case, your ClaimType can indeed be an .NET enum, which EF Core maps to an int by default (you can use a byte enum, but there's usually no real need for that). For example, you can have the follow DbContext and entity types:

```c#
public class BlogContext : DbContext
{
    public DbSet<Permission> Permissions { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Permission
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public ClaimType ClaimType { get; set; }
}

public enum ClaimType
{
    GetGroup,
    UpdateGroup,
    DeleteGroup,
    // ... more claim types can follow
}
```

EF Core will create the following table from this:

```sql
CREATE TABLE [Permissions] (
    [Id] int NOT NULL IDENTITY,
    [UserId] int NOT NULL,
    [ClaimType] int NOT NULL,
    CONSTRAINT [PK_Permissions] PRIMARY KEY ([Id])
);
```

Once your Permissions table is populated, you can check if a given user has a specific permission as follows:

```c#
var hasPermission = ctx.Permissions.Any(p => p.UserId == userId && p.ClaimType == ClaimType.GetGroup);
```

This will generate the following SQL for SQL Server:

```sql
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Permissions] AS [p]
        WHERE ([p].[UserId] = @__userId_0) AND ([p].[ClaimType] = 0)) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
```

**Comment by mcguu** [comment]
@roji  thank you but there is several questions.
there maybe 20 permissions for one group and a user may has 30 groups then only one user may has `List<Permissions>` which `count` =600? with same `[UserId]` and `[GroupId]` is it really good?

so I think can it be true that the `[ClaimType]` be an array.
```
CREATE TABLE [Permissions] (
    [Id] int NOT NULL IDENTITY,
    [UserId] int NOT NULL,
    [ClaimType] varchar(1000) NOT NULL,
    CONSTRAINT [PK_Permissions] PRIMARY KEY ([Id])
);
```

```
public class Permission
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public ClaimType[] ClaimType { get; set; }
}
```

so there is only 1 for same user and same group no matter how many ClaimTypes there are.

and set a `ValueConverter`
```
ValueConverter splitClaimConverter = new ValueConverter<ClaimType[], string>(v => string.Join(";", v.AsEnumerable().Select(x => Enum.GetName(x.GetType(), x))), v =>
               v.Split(new[] { ';' }).AsEnumerable().Select(x => Enum.Parse<ClaimType>(x)).ToArray()
            );
```

the ClaimType may be a string of the ClaimTypes one have.
"GetGroup;UpdateGroup;DeleteGroup;`

what do you suggests me to do? @roji ?

**Comment by roji** [comment]
@mcguu I don't know exactly what you're trying to do, but trying to represent everything in a single table may not be the way to go. To model things in the classical, normalized relational way, you could have a table for groups, a table for users and a many-to-many relationship between them. You could then have a GroupPermissions table and a UserPermissions table, with one-to-many relationships to the groups and users tables, respectively.

For possibly better efficiency, you could represent all the claims for a given group or user as a single, delimited string column using a value converter as you've written above. At that point you can no longer just use a standard Contains operator, but must explicitly do a substring check to see if a given claim is contained in the group.

There are various variations in ways to model this, but I'd suggest posting a question on stackoverflow to get more help.
