### ISSUE TITLE
Update optional dependents message to indicate non-null value rather than non-default

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#26800]
Current message:

> The entity of type 'Dependent' is an optional dependent using table sharing. The entity does not have any property with a non-default value to identify whether the entity exists. This means that when it is queried no object instance will be created instead of an instance with all properties set to default values. Any nested dependents will also be lost. Either don't save any instance with only default values or mark the incoming navigation as required in the model. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values of the entity.

**Comment by voroninp** [comment]
> This means that when it is queried no object instance will be created **instead of** an instance with all properties set to default values. 

does it mean: 

_If all properties of saved instance had default values, then returned value for the object will be just null._

How do I turn this warning off for concrete type?
