### ISSUE TITLE
Support "Add" on View-DbSets for InMemoryDbProvider

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/efcore#26817]
**Problem:**

I'm using xUnit and Moq for Unit- and IntegrationTests. As DbContext I use the InMemoryDbProvider.

Before a test is running I arrange the content of the InMemoryDb for my current test szenario. But if the logic uses a view on database I have a problem.
The View itself is represented as a DbSet. But arrange that DbSet is not possible. When I call "Add" on that DbSet I get an 'InvalidOperationException'.

`System.InvalidOperationException: "Unable to track an instance of type 'viewType' because it does not have a primary key. Only entity types with primary keys may be tracked."`

**Solution:**

Activate "Add" for DbSets but only for InMemoryDatabase.

**Comment by ajcvickers** [comment]
@Der-Kraken Take a look at [Defining query for in-memory provider](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#defining-query-for-in-memory-provider).

**Comment by Der-Kraken** [comment]
> @Der-Kraken Take a look at [Defining query for in-memory provider](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#defining-query-for-in-memory-provider).

Yes, that could be a way to go. 
I'm looking forward until we migrate to dot.Net 6.0
