### ISSUE TITLE
Can we Add a new extentsion line AddInclude on IQueryable<T> interface?

### ISSUE THREAD

**Issue by dxq0126** [dotnet/efcore#26810]
We have Include and ThenInclude extension for IQueryable, I want add a new function on it.
The Include function include the child properties for the top entity, and the ThenInclude function includes the next lever entities of the parent. 
I want  add AndInclude for the sibling entity.

```

public class Libary
{
    public int Id { get; set; }
    public ICollection<Subject> Subjects { get; set; }
}


public class Subject
{
    public string Name { get; set; }
    public string Location { get; set; }
    public Mamager Mamager { get; set; }

    public ICollection<Book> Books { get; set; }
}

public class Mamager
{
    public string Name { get; set; }
    public string Job { get; set; }
}

public class Book
{
    public string Name { get; set; }
    public DateTime Date { get; set; }
}

public class Services
{
    IRepository<Libary> _libaryService;
    public Services(IRepository<Libary> libaryService)
    {
        _libaryService = libaryService;
    }

    public async Task<Libary> Get(int id)
    {
        return await _libaryService.Where(x => x.Id == id)
            .Include(x => x.Subjects)
                .ThenInclude(x => x.Books)

```

            .AddInclude(x => x.Mamager)

```
            .FirstOrDefaultAsync();
    }
}
```

**Thanks!!!**

**Comment by ajcvickers** [comment]
@dxq0126 This is a complex area of API design which has been discussed extensively in #4490 and #23110. As [this comment](https://github.com/dotnet/efcore/issues/23110#issuecomment-948442557) says, we are looking at this area in conjunction with #2953. If you have something new to add after reading the existing discussions, then I suggest you comment on #23110.
