### ISSUE TITLE
Why EF core get different results when use AsNoTracking 

### ISSUE THREAD

**Issue by wpycs** [dotnet/efcore#26811]
Setp1:Query a Entity with Tracking，get result res1
Setp2:Update this Entity by other connection
Setp3:Query this Entity again with Tracking，get result res2 
Setp4:Query this Entity again with AsNoTracking，get result res3

I think res1 should not eq res2,but now res1 eq res2,and res3 not eq res2

I was also test pgsql，and EF Core 6，it have the same result。

Is this a feature? why this result?

###  example

```C#
    public class EFQueryTest
    {
        [TestMethod]
        public void QueryTest()
        {
            using var context = new TestContext();
            context.TestTables.Add(new TestTable { id = "1", name = "name" });
            context.SaveChanges();
            var query = context.TestTables.First(c => c.id == "1");

            #region other changed this record
            using var context2 = new TestContext();
            var entity = context2.TestTables.First(c => c.id == "1");
            entity.name = "new_name";
            context2.SaveChanges();
            #endregion

            var query2 = context.TestTables.First(c => c.id == "1");
            var query3 = context.TestTables.AsNoTracking().First(c => c.id == "1");
           
            //it should be successed,but faied
            Assert.AreEqual(query2.name, query3.name);
            //it should be successed,but faied
            Assert.AreNotEqual(query2.name, query.name);
        }
        class TestContext : DbContext
        {
            public DbSet<TestTable> TestTables { get; set; }
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseInMemoryDatabase("my_test");
            }
        }
    }
    [Table("table_test")]
    public class TestTable
    {
        [Key]
        public string id { get; set; }
        public string name { get; set; }
    }
```

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.InMemory,Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: .NET Core 3.1
Operating system: Windows
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@wpycs This is by-design. See [tracking queries](https://docs.microsoft.com/en-us/ef/core/querying/tracking#tracking-queries) in the documentation. In particular:

> When the results are returned in a tracking query, EF Core will check if the entity is already in the context. If EF Core finds an existing entity, then the same instance is returned. EF Core won't overwrite current and original values of the entity's properties in the entry with the database values.

See also [Change tracking](https://docs.microsoft.com/en-us/ef/core/change-tracking/) for more information about how EF Core change tracking works and [EntityEntry.Reload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.entityentry.reload?view=efcore-5.0#Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntry_Reload)

**Comment by wpycs** [comment]
@ajcvickers Thank you so much
