### ISSUE TITLE
How to dealing with multy source Database using DbContext

### ISSUE THREAD

**Issue by sumer5020** [dotnet/efcore#26828]
I used clean arch steps to create the project, but the problem that i have more then three aggregate that i need to put them in different Databases.

I tried to use DbContext for each aggregate like this:

```C#
public class AppDbContext : DbContext
{
  private readonly IMediator? _mediator;

  public AppDbContext(DbContextOptions<AppDbContext> options, IMediator? mediator)
      : base(options)
  {
    _mediator = mediator;
  }
.
.
.
public class AnalyzeDbContext : DbContext
{
  private readonly IMediator? _mediator;

  public AnalyzeDbContext(DbContextOptions<AnalyzeDbContext> options, IMediator? mediator)
      : base(options)
  {
    _mediator = mediator;
  }
.
.
.
public class ProviderMgrDbContext : DbContext
{
  private readonly IMediator? _mediator;


  public ProviderMgrDbContext(DbContextOptions<ProviderMgrDbContext> options, IMediator? mediator)
      : base(options)
  {
    _mediator = mediator;
  }
```

And i send the connection string for each DbContext like this:

```C#
public static void AppDbContext(this IServiceCollection services, string connectionString) =>
   services.AddDbContext<AppDbContext>(options => options.UseMySql(connectionString, new MySqlServerVersion(new Version(8, 0, 27))));

 public static void ProviderMgrDbContext(this IServiceCollection services, string connectionString) =>
   services.AddDbContext<ProviderMgrDbContext>(options => options.UseMySql(connectionString, new MySqlServerVersion(new Version(8, 0, 27))));
  
  public static void AnalyzeDbContext(this IServiceCollection services, string connectionString) =>
   services.AddDbContext<AnalyzeDbContext>(options => options.UseMySql(connectionString, new MySqlServerVersion(new Version(8, 0, 27))));
.
.
.
```
  

**But when i try to migrate them it's balded all my aggregates  into all contexts, and i need each DbContext build only his aggregate, so how to fix it ?**

**Comment by ajcvickers** [comment]
@sumer5020 It's hard to be sure from just the information provided, but if your aggregates are connected, then I suspect you need to [exclude certain entity types from migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#excluding-parts-of-your-model) in the context configuration that doesn't own them.

If this isn't it, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sumer5020** [comment]
Dear  @ajcvickers ,
I created an Example Repo on github, may you check it at: [multySourceDatabaseExample](https://github.com/sumer5020/multySourceDatabaseExample)
You can see in my migrations [init_1, init_2 and init_3] take all my aggregates into

**Comment by sumer5020** [comment]
> @sumer5020 It's hard to be sure from just the information provided, but if your aggregates are connected, then I suspect you need to [exclude certain entity types from migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#excluding-parts-of-your-model) in the context configuration that doesn't own them.
> 
> If this isn't it, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Dear @ajcvickers , After hard time I catch my issue with DbContext, at first I used modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly()); to config my entities but my Assembly always take all configrations for the context for some reason, I tried to use modelBuilder.ApplyConfiguration(new AccGeneralJournalConfiguration()); of OnModelCreating in each DbContext and it's work successfully, but that make me confuse a little bit.

**Comment by sumer5020** [comment]
the problem solved by change  `modelBuilder.ApplyConfigurationsFromAssembly`, that would add every configs we make to the current DbContext to `modelBuilder.ApplyConfiguration(new MyDbSetConfiguration());` that separate my DbSet to DbContexts as i need.
