### ISSUE TITLE
SQLite leaks file handle

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#2682]
See http://stackoverflow.com/questions/31486760/how-to-close-a-sqlite-file-opened-with-system-data-sqlite-and-dbcontext

**Comment by bricelam** [comment]
Note, the issue is about EF6 & **System**.Data.SQLite.

**Comment by anpete** [comment]
OH, didn't see the EF6 part - assumed EF7 after @bricelam referenced IX-Async on twitter.
