### ISSUE TITLE
Nullable reference with DeleteBehavior.Cascade that is deleted is reloaded back after DetectChanges

### ISSUE THREAD

**Issue by xsmerek** [dotnet/efcore#26827]
We are using EF with .NET 6.0 and we have an entity which is child of several other entities:

```C#
    public partial class Car
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Car Car { get; set; } // FK is defined in Car table
    }
```

All FKs are nullable and defined on `Car` table and with `DeleteBehaviour.Cascade`:

```C#
                entity.Property<int?>("PersonId").HasMaxLength(100).IsRequired(false);
                entity.HasOne<Person>()
                    .WithOne(p => p.Car)
                    .HasForeignKey<Car>("PersonId")
                    .OnDelete(DeleteBehavior.Cascade);
```

We want to be able to delete the child by setting parent reference to null:

```C#
                person.Car = null;
```

After `ChangeTracker.DetectChanges()` is called, the child is correctly marked as deleted but the reference itself is reloaded, so `person.Car != null`. Having a deleted entity hanging in the reference causes trouble for subsequent business logic.

I tried to debug the issue, it seems to be a combination of `InternalEntityEntry.SetProperty()` not setting the value of underlying property to `null` because of `DeleteBehaviour.Cascade` and the fact that subsequent `ChangeDetector.DetectKeyChange()` compares snapshot value (contains `null`) with actual value of underlying property (contains original key).

### Steps to reproduce

Project:
https://github.com/xsmerek/EFCoreDeletingNullableReference

Steps:
 - run EFCoreDeletingNullableReference\setup.sql to create DB and data.
 - adjust connection sting in EFCoreDeletingNullableReferenceContext
 - Run test DeleteReferenceTest

### Provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.0

Please let me know if you need any additional information.

**Comment by ajcvickers** [comment]
Verified that this is fixed in the latest daily build. Will add a test.
