### ISSUE TITLE
HierarchyId bug report and lack of response

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/efcore#26835]
Hello Guys,
I reported a bug in [EFCore.SqlServer.HierarchyId](https://github.com/efcore/EFCore.SqlServer.HierarchyId/) repo
[(https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/86)]((https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/86))
and I can't see any response or much activity in general  in this specific repo.
Do I need to report it here to be seen or what I can do to have attention ?
Thanks in advance
-Vince

**Comment by ajcvickers** [comment]
@vRITHNER While we try to be responsive, much of the team has been out for the Thanksgiving holiday in the U.S. Sometimes it takes a few days for us to investigate issues.
