### ISSUE TITLE
Support multiple params for `.ThenInclude(...)`

### ISSUE THREAD

**Issue by ksydex** [dotnet/efcore#26837]
When using multiple `.ThenInclude(...)`  for `IQueryable<T>`, the query itself becomes very complicated, for example:
```csharp
q.Include(x => x.ComplexProperty)
.ThenInclude(x => x.Property1OfComplexProperty)
.Include(x => x.ComplexProperty)
.ThenInclude(x => x.Property2OfComplexProperty)
```
So, we need to use `.Inlude(...)` several times to include data for _one property_.

I think next syntax gonna solve that problem:
```csharp
q.Include(x => x.ComplexProperty)
.ThenInclude(x => x.Property1OfComplexProperty, x => x.Property2OfComplexProperty)
```
It's way more clear and two times shorter (in this exact case)

**Comment by ajcvickers** [comment]
@ksydex This has been discussed previously on in #4490 and #23110. The main problem with this approach is that it precludes further chaining. If you have something new to add after reading the existing discussions, then I suggest you comment on #23110.
