### ISSUE TITLE
How to join a table with out a foreign key?

### ISSUE THREAD

**Issue by mcguu** [dotnet/efcore#26832]
There is TableA and TableB and I can use it like this
```
from a in _context.TableA
from b in _context.TableB
where a.Id==b.UserId
select a;
```

but what about 
`_context.TableA.Include(TableB)?`
there is no foreign key

**Comment by ajcvickers** [comment]
@mcguu `Include` relies on [relationships defined in the model](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key). EF relationships are represented byu foreign keys, so you need to define a foreign key in the EF model to define a relationship. (Technically, the database does not need the foreign key _constraint_, but the data must be consistent with the semantics of a foreign key.)
