### ISSUE TITLE
Cosmos Where query on owned properties throws a translation exception

### ISSUE THREAD

**Issue by yochail** [dotnet/efcore#26849]
## Ask a question
 I'm in the process of implementing a Cosmos DB access with an entity framework provider,
 And every query I'm trying to run on Owned Entity gets a translation error.
I tried many different queries.  and I get this error only on owned entities like in the code example.
I think this query type should be possible like in this test:
https://github.com/dotnet/efcore/blob/main/test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs

### code
The (simplefied) document classes
```C#
	public class StructuredTrial
	{
		public string TrialId { get; set; }
		public ICollection<StringWrapper> ConditionCodesList { get; set; }
	}

	public class StringWrapper
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public string Id { get; set; }
		public string StrValue { get; set; }
	}
```
Context definition:
```C#
modelBuilder.HasDefaultContainer("StructuredTrials");
			modelBuilder.Entity<StructuredTrial>().HasKey(s => s.TrialId);
			modelBuilder.Entity<StructuredTrial>().HasPartitionKey(s => s.TrialId);
			modelBuilder.Entity<StructuredTrial>().OwnsMany(c => c.ConditionCodesList, c =>
			{
				c.HasKey(p => p.Id);
			});
```
Calling code I tried, with similar error (error provided is for the first one):
```C#
var db = new KnowledgeGraphDBContext(_dbOptions);
var studiesQuery = await db.StructuredTrials.AsQueryable()
				                       .Where(s => s.ConditionCodesList.IsDefined()).ToListAsync();
				                       
var studiesQuery = await db.StructuredTrials.AsQueryable()
				                       .Where(s => s.ConditionCodesList.Count() > 0).ToListAsync();	

var studiesQuery = await db.StructuredTrials.AsQueryable()
				                       .Where(s => s.ConditionCodesList.Contains(null)).ToListAsync();				                     
```

### Error Output

```
System.InvalidOperationException: 'The LINQ expression 'DbSet<StructuredTrialTest>()
    .Where(s => MaterializeCollectionNavigation(
        Navigation: StructuredTrialTest.ConditionCodesList,
        subquery: EF.Property<ICollection<StringWrapperTest>>(s, "ConditionCodesList")
            .AsQueryable()
        .IsDefined())' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

```
### stack traces
```
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& ) in /_/src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs:line 105
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos 5.0.12)
Target framework: (e.g. .NET 3.1)
Operating system:
IDE: (e.g. Visual Studio 2022 17.0.1)

**Comment by smitpatel** [comment]
`IsDefined` function is unknown to us. 
Others #17957

**Comment by ajcvickers** [comment]
@smitpatel `IsDefined` comes from the `Microsoft.Azure.Cosmos.Linq` LINQ provider. It's interesting to consider that people may try to use these with the EF Core LINQ provider.

/cc @AndriySvyryd

**Comment by yochail** [comment]
@smitpatel it was just an examle, none of the other options there worked, i dont need specificlly the IsDefined function, I plan to implement a custum Sql function using Array contains but the issue is on the owned property access

**Comment by ajcvickers** [comment]
@yochail The pattern in general is tracked by issue #17957, as referenced by @smitpatel above. Please vote for that issue if this is something important to you.

**Comment by yochail** [comment]
@ajcvickers but isnt that the same pattern as in this test:
https://github.com/dotnet/efcore/blob/main/test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs

**Comment by ajcvickers** [comment]
@yochail Which test do you mean, specifically? Many of those tests are skipped with reference to #17246.
