### ISSUE TITLE
Progress on #24889: EF read operation kills app consistently after 535 accesses....

### ISSUE THREAD

**Issue by AndroidEFCoreLover** [dotnet/efcore#26868]
Issue described in https://github.com/dotnet/efcore/issues/24889. Still not resolved.

Is there any progress on this? Anything on the horizon? Any guidelines? 

This being fixed will have large implications for our team in current and future projects. Although this is not EF Core bug, it is still causing long going implications...

**Comment by ajcvickers** [comment]
@AndroidEFCoreLover We have seen a lot of stability issues with SpatiaLite. #22138 tracks updating to SpatiaLite 5 in the EF7 timeframe. We're hoping that this will greatly improve the situation, but only time will tell.
