### ISSUE TITLE
EF Core materializes projection property as object with default values

### ISSUE THREAD

**Issue by Alexander-Leontiev** [dotnet/efcore#26873]
I have a LINQ expression like the following:

```C#
from u in Context.Users.Where(u => u.Id == 123).Select(UserDto.Map)
join l in Context.Locations.Select(LocationDto.Map) on u.LocationId equals l.Id into locations
from l in locations.DefaultIfEmpty()
join a in Context.Agencies.Select(AgencyDto.Map) on l.CompanyId equals a.Id into agencies
from a in agencies.DefaultIfEmpty()
join m in Context.Markets.Select(MarketDto.Map) on l.CompanyId equals m.Id into markets
from m in markets.DefaultIfEmpty()
select new UserEntityData {
   User = u,
   Location = l,
   Agency = a,
   Market = m
}
```

User via Location can be connected to Agency or Market, not both.
EF translates it correctly into SQL query with left joins. Query returns correct data with Agency or Market columns all NULL.
However when query data is materialized I get UserEntityData objects with both Agency and Market properties not null. UserEntityData property for missing DB record is initialized with object with default values. I expect property to be null.

May be usefull:
1. If I read full entities for agency\market (not projected DTOs) all works fine.
2. I tried EF Core 5\6 and got another error 'Nullable object must have a value' during materialization. Looks like EF tries to put NULLs from DB response into not-nullable properties of my DTOs.

Project to reproduce the original issue: [EfTest.zip](https://github.com/dotnet/efcore/files/7639436/EfTest.zip)

EF Core version: 3.1.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Framework 4.8

**Comment by ajcvickers** [comment]
@Alexander-Leontiev 

> Looks like EF tries to put NULLs from DB response into not-nullable properties of my DTOs.

If the result is a null, then your object needs to be nullable to accept that result.

**Comment by Alexander-Leontiev** [comment]
@ajcvickers yes, however I still have 2 questions:
1. Why my code works fine, if I use entities instead of projections?
2. Why EF treats complex result properties (objects) as set of field they consist of? I expect null property in result at the place of missing left-joined entity.

**Comment by Alexander-Leontiev** [comment]
@smitpatel could you please give some estimate for the issue?

**Comment by smitpatel** [comment]
The repro code doesn't contain any seed data. I am not seeing any error with empty database (which is expected). Provide a repro code with the seed data in databse which generates above error.

**Comment by Alexander-Leontiev** [comment]
@smitpatel I have added test data, please take a look: [EfTest_WithSeed.zip](https://github.com/dotnet/efcore/files/7863181/EfTest_WithSeed.zip).
@ajcvickers jfyi

**Comment by smitpatel** [comment]
Duplicate of #22517

**Comment by Alexander-Leontiev** [comment]
@smitpatel are you sure it's the same thing? From https://github.com/dotnet/efcore/issues/22517: "confirmed this works in 3.1, but fails in latest daily" - my example fails in 3.1 also.

**Comment by smitpatel** [comment]
It is same. Refer to this comment https://github.com/dotnet/efcore/issues/22517#issuecomment-692236476
