### ISSUE TITLE
Add output to Script-Migration

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2687]
**Repro**
1. Create project with a context and model
2. `Add-Migration Initial` -> 001_Initial.cs
3. Modify model
4. `Add-Migration Migration2` -> 002_Migration2.cs
5. Apply migrations
6. Run `Script-Migration 001_Initial`

**Expected**
It should produce the script to reverse 'Migration2'.

**Actual**
It produces the 'Up' script for Migration2
#1162 #1242
## Update

This is user error -- will fix by improving output to console.

**Comment by natemcmaster** [comment]
May be related to https://github.com/aspnet/EntityFramework/issues/1972#issuecomment-123899357

**Comment by bricelam** [comment]
`Script-Migration` has two ordinal parameters: `From` and `To`. `From` defaults to `0` and `To` defaults to the latest migration. I've been wondering if we should make the behavior more like `Script-Migration [[From] To]` so if you only specify one parameter, it's the `To`. But even that wouldn't meet your expectations. :smile:

**Comment by natemcmaster** [comment]
So really, this is user error. I think we could help this by printing to the console the 'from' and 'to' parameters. Just that little piece of feedback would help me understand what the resulting script represents.

**Comment by bricelam** [comment]
Good call. Something like...
> Generating script from initial database to '20150723092116_LatestMigration'.
> Generating up script for migration '20150723092108_FirstMigration'.
> Generating up script for migration '20150723092116_LatestMigration'.
> Done.

**Comment by natemcmaster** [comment]
:+1:

**Comment by natemcmaster** [comment]
Additionally (and for less-verbose output), could we print something like this?

> Generating script from ___ to ____

**Comment by bricelam** [comment]
Given that we already log the "Generating up script" statements, and we're now forcing you to specify the `-To` or `-From`, I think this issue is resolved.

**Comment by natemcmaster** [comment]
Agreed.
