### ISSUE TITLE
Poor useability of EF Core as compared to EF 6

### ISSUE THREAD

**Issue by phyrexians** [dotnet/efcore#26874]
In order to follow the crowd, EF Core now makes use of the Command Line to even work. 
This is an obvious downgrade to how EF6 was where users simply follow a GUI to connect to the database and all connection strings are automatically created in the web.config or app.config. A nice database diagram/schema will also be automatically generated. Any update can be done easily by a right-click to regenerate the model.
EF Core just seems to be a poor product to court people who refuses to use .Net but instead pushes the existing EF6 users away.
I, for one, sincerely hope EF6 makes a comeback in .Net 6 or .Net 7 even if it is at the cost of the person who pushes for EF Core. Because GUI > Command Line any day even if the Linux die-hard fans say otherwise.

**Comment by ErikEJ** [comment]
Have you tried EF Core Power Tools?

**Comment by roji** [comment]
@phyrexians EF6 definitely won't be making a comeback, but the GUI tool isn't necessarily something that has to come with EF Core itself. @ErikEJ's EF Core Power Tools is a good option, as is LLBLGen Pro and other options out there.

**Comment by phyrexians** [comment]
I wouldn't say it's necessary but it certainly makes it much easier to just plug-ang-play. It's also much to teach and share to students new to C#, database and ORMs. Then there's the area of competitions (World Skills for instance) where students are not allowed to use 3rd party tools during the live coding session.
I did a quick Google on EF Core Power Tools and I can say it's comes pretty close to what EF6 was. I would probably research and use this for my personal project. In terms of teaching, probably not as much. 
But the issue still remains that EF6 had this feature but they removed it and now we have to rely on 3rd party tools (without guarantee of support for future versions) to do what was available. So why make life more difficult for people using a newer version of their product? EFCore is really dissuading me from fully embracing the .Net Core part of the .Net 6 technology at the moment.

**Comment by roji** [comment]
@phyrexians I don't disagree that a full-featured UI would have been useful. However, the EF Core team isn't very big, and the development and maintenance of an EF Core UI inside Visual Studio would have taken substantial work; we've preferred to invest  the limited resources of the team in features etc.

There's also the question of different UIs - .NET isn't just about Visual Studio, there's also Visual Studio Code, Visual Studio for Mac, etc. Any work on a VS UI wouldn't have benefited users of other IDEs, or command-line users.

I do hope that the lack of a Microsoft-provided EF Core UI doesn't deter you from using EF Core. We believe that for the .NET ecosystem to thrive, people also need to get used to using tools and libraries which don't come from Microsoft - there are lots of community components (like EF Core Power Tools or LLBLGen Pro) which are very high-quailty, and there's really no need to avoid them just because they don't come from Microsoft.

**Comment by phyrexians** [comment]
Hi roji,

That's actually a great point about the EF Core team that I failed to consider.

The ease of usage and maintenance is actually "A" feature especially when trying to convince students from another language like Python, NodeJS to try out or convert to DotNet. This was a major selling point for students who had prior experience in other languages where they have to memorize the commands, the connection strings in order to connect to their database before they can start coding.

I'm not sure about the backend code behind EF6 that will prevent other IDEs from displaying the diagram, but the models are created just like in EF Core. In fact, it could just as well be a diagram that is viewable only in Visual Studio which would be a nice pull for people to install Visual Studio as well. The ability to view a database diagram is a bonus, the ease of connecting and generating the models is the main selling point. So that isn't really a strong justification for removing the GUI Wizard for setting up EntityFramework just because someone running Linux can't view a diagram.

I believe in 3rd party libraries, especially open source ones, as they have proved to be useful in many cases. For a start, I've always used Automapper, log4net in most C# project. In fact, EF Core Power Tools could be something that I might have to turn to for my future projects should any client choose to go for Dotnet Core. LLBLGen Pro, however, is a paid library which makes it difficult to evaluate or recommend to others.

In my humble opinion, when it's something integral like EntityFramework, I would expect Microsoft to ship it better than the previous version instead of pulling away features and had to rely on 3rd party libraries to cover up the missing features. Another consideration for 3rd party library is their support to future versions of DotNet Core becomes an unknown. Also like I said previously in the area of education, there are local/international competitions (World Skills) that doesn't easily allow 3rd party libraries to be used.

**Comment by roji** [comment]
FWIW I do agree GUI integration is important - especially for new users, students etc; there's definitely value in having at least basic EF Core gestures in UIs, even without a full-blown modeling experience with diagrams etc.

> So that isn't really a strong justification for removing the GUI Wizard for setting up EntityFramework just because someone running Linux can't view a diagram.

It's important to understand that the GUI wizard/components weren't removed; EF Core is sufficiently different from EF6 that they would have had to be developed pretty much anew, from the ground up. Specifically, EF6 relies on the Entity Data Model (with EDMX), whereas EF Core does not. Hopefully this provides more context on why there's no built-in UI for EF Core - it really would have been a big effort to develop that, and not just "let's continue using the EF6 UI with maybe a few tweaks". That investment simply did not seem justified compared to other things the team could (and needed to) do.

I don't have much to add beyond that, aside from the somewhat special expectation some users have in the .NET ecosystem, to only ever use Microsoft-provided components. This is IMHO something we need to get past if the ecosystem is to thrive further; other ecosystems don't typically have a similar situation where a single company is so dominant, and users are generally more comfortable looking at tools and libraries from multiple companies/open source projects etc.
