### ISSUE TITLE
Stop scaffolding DbSet initialization to `null!`

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26877]
Now that we have a diagnostics suppressor for uninitialized DbSet properties (#26795), we can stop scaffolding DbContext code which initializes DbSet properties to `null!`.

**Comment by ajcvickers** [comment]
Note from triage: looks like an issue with analyzers during tests. @roji will investigate.

**Comment by roji** [comment]
@bricelam I did some trivial testing from a console program against 7.0.0-preview.6, and everything seems to be working correctly - I'm getting no uninitialized warnings for DbSets (with a DbContext, constructor or without it). So I guess there's some testing issue there - if you want to point me to some failing test I can look...
