### ISSUE TITLE
SQL Server Migrations: Unable to rename or drop Table with custom schema.

### ISSUE THREAD

**Issue by jonaramos** [dotnet/efcore#26887]
**Provider information**

EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
Terminal: Windows Terminal

**Issue description**

I applied a table mapping like the following:

```C#
[Table("Users", Schema = "School")]
 public class Users
```

Upon using _Add-Migration_ and _Update-Database_, changes are applied correctly in the DB.

Later, renaming the class and the table name attribute,  add migration, apply update to DB, and I get the error:

> Cannot drop the table 'Users', because it does not exist or you do not have permission.

The auto generated migration is resulting like the following:

```C#
migrationBuilder.DropTable(
      name: "Users");
```

If I specify the table schema, the database update is applied correctly.

```C#
 migrationBuilder.DropTable(
      name: "Users"
      schema: "School");
```

So the auto generated migration is missing to include the class schema.

**Comment by ajcvickers** [comment]
@jonaramos Do you know if this was working in EF Core 5.0?

**Comment by jonaramos** [comment]
I noticed the issue in a new PC box. I do not know if this was working in previous versions.

**Comment by ajcvickers** [comment]
@jonaramos I am not able to reproduce this. Starting with this class:

```C#
[Table("Users", Schema = "School")]
public class Users
{
    public int Id { get; set; }
}
```

and changing to this:

```C#
[Table("NewUsers", Schema = "School")]
public class NewUsers
{
    public int Id { get; set; }
}
```

I get:

```C#
migrationBuilder.DropTable(
    name: "Users",
    schema: "School");
```

Can you post the class you are migrating before an after the change so we can attempt to reproduce what you are seeing?

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
