### ISSUE TITLE
SQLite: Preserve Inlined PK Names

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2688]
When SQLite inlines a primary key, the constraint name is lost.
## Expected

``` SQL
CREATE TABLE "Person" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Person" PRIMARY KEY AUTOINCREMENT
);
```
## Actual

``` SQL
CREATE TABLE "Person" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);
```

**Comment by natemcmaster** [comment]
What do we need the named constraint for?

**Comment by bricelam** [comment]
You know, so we can drop it... oh wait. :wink: We don't, but the user may have specified it and we should honor that as best we can while creating the database.
