### ISSUE TITLE
What happened to CSharpMigrationsGenerator?

### ISSUE THREAD

**Issue by MelGrubb** [dotnet/efcore#26888]
## Ask a question

I am trying to update an existing codebase from EFC5 to EFC6, and we have a class that inherits from CSharpMigrationsGenerator. Looking in the repo, it sure seems to be there, but I can't compile, and VS insists that the ...Migrations.Design namespace no longer exists, and I can't even use the fully-qualified name of the class.

### Include your code

```C#
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore.Design.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations.Design;
using Microsoft.EntityFrameworkCore.Migrations.Operations;

namespace MyProject.Domain.Framework
{
    /// <summary>
    ///     Create the main migration file
    /// </summary>
    public class MyProjectCSharpMigrationsGenerator : CSharpMigrationsGenerator
    {
...
```

### Include verbose output

"The type or namespace name 'Design' does not exist in the namespace 'Microsoft.EntityFrameworkCore.Migrations' (are you missing an assembly reference?)"

### Include provider and version information

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system:
IDE: Visual Studio 2022 17.0.1

**Comment by ajcvickers** [comment]
@MelGrubb  If you are referencing the design package from your code (as opposed to just using it for tooling) then remove all the conditions and reference it as a normal package:

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0" />
```

**Comment by MelGrubb** [comment]
Well, I didn't have any actual _conditions_ as such, but the reference wasn't a simple one-liner, either. Here's what I had

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

Shortening it to this solves the reference issue, thanks
`
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0" />
`

Now to track down the signature changes. GenerateMigration seems to have changed slightly. Hopefully this will get caught in the next guy's search.

**Comment by MelGrubb** [comment]
It appears that our project had the correct reference types previously, but updating the packages changed it from a simple library to an analyzer reference automatically.

**Comment by ajcvickers** [comment]
@MelGrubb Yes, this is an unfortunate behavior of NuGet.
