### ISSUE TITLE
Why still no bulk commands?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#26895]
One thing that bothered me the first time I used Entity Framework was the inefficiency of a bulk delete.

I actually need to perform a query, pull down the rows to be deleted, mark them for deletion, and then save my changes. (I realize I only need the primary keys, but I still need these steps if I don't know the primary keys in advance.)

Considering how efficiently SQL Server can perform a delete, this seems terribly inefficient. Here we are at EF version 6 and still no support for bulk commands.

How hard is it to do something like this?

    DbContext.Comments.BulkDelete().Where(c => c.CreateDate < DateTime.Now.AddYears(-1));

Similar support for bulk updates would also be awesome!

I suspect this has been discussed somewhere already. But I was unable to find any discussions on it.

**Comment by ajcvickers** [comment]
This is tracked by #795.
