### ISSUE TITLE
Old cached query executing against database when using LINQ .Contains in traffic heavy environment

### ISSUE THREAD

**Issue by plittlewood-rpt** [dotnet/efcore#26905]
Originally noted in #13617 

I have an API that switches DbContext from request to request based on the customer accessing it (this is because we use single tenant databases). We are seeing on occasion, after periods of high traffic, that the expressions compiled after using the .Contains() operator use old values, as though a cache is being exhausted.

To give you some context:

Users might call `GET /myEndpoint?ownerId=ABC&ownerId=DEF`

The query parameters get translated into SQL via LINQ using something similar to:

```
       if (query.OwnerIds!= null && query.OwnerIds.Any())
       {
           predicate = predicate.And(p => query.OwnerIds.Contains(p.OwnerId) || query.OwnerIds.Contains(p.OwnerId2) || query.OwnerIds.Contains(p.OwnerId3));
       }
``` 

The predicate then gets used when calling the database context ie: `dbContext.Data.Where(predicate)`

This correctly gets converted to a MySQL statement using `IN ()` as I'd expect, as using `.Contains()` does not result in a parameterized query. If we take the URL example above (`GET /myEndpoint?ownerId=ABC&ownerId=DEF`) however, the query that gets executed against the database sometimes uses values from a previous query, so it might run `WHERE ownerId IN ('GHI', 'JKL') OR ownerId2 IN ('GHI', 'JKL') OR ownerId3 IN ('GHI', 'JKL')` - where someone has previously made a call to  `GET /myEndpoint?ownerId=GHI&ownerId=JKL` 

This only seems to occur after a period of high traffic has hit the API and so far hasn't seemed to be able to right itself if left alone. Restarting the container that the API runs in resolves the issue, until it eventually happens again. 

I have attempted to replicate this locally and in our development environment by firing thousands of requests with different query string parameters (upwards of 15k requests) and cannot recreate the issue, which seems to suggest it's something to do with switching between DbContexts. The DbContext is created using a factory, which is registered with transient lifetime so _should_ be a fresh instance with each request. I have added `.AsNoTracking()` to the queries to try and bypass any caching with no success.

I can rewrite the LINQ to chain OR conditions together, which then results in a parameterized query but rather horrible SQL. Can anybody suggest anything that might be causing the underlying problem? I'm not bothered if the `IN ()` is not parameterized IF I can explain and resolve what's going on with old values being used.

### Include provider and version information

EF Core version: 5.0.1 (testing 5.0.12)
Database provider: Pomelo.EntityFrameworkCore.MySql (5.0.0 - testing 5.0.3)
Target framework: .NET Core 3.1
Operating system: Windows 10/Ubuntu 
IDE: Visual Studio 2019 16.7.4
Other packages: LinqKit.Microsoft.EntityFrameworkCore (5.0.21 - testing 5.0.27)

**Comment by ajcvickers** [comment]
@plittlewood-rpt We discussed this, and it sounds very much like a concurrency issue with two threads accessing the same context. I understand that it will be difficult to create anything that will allow us to reproduce what you are seeing. However, maybe you can attach a stripped down project that at least shows how your services are configured and resolved?

**Comment by plittlewood-rpt** [comment]
Hi @ajcvickers - really appreciate your response. Leave this with me and I'll try and get something to get something together that's shareable

**Comment by plittlewood-rpt** [comment]
@ajcvickers We have a repository class which is registered as scoped. The db context factory class which is injected into the repository is registered as transient. I'm going to explore this as a potential cause of the problem but wanted to highlight it now in case you're any pointers here

**Comment by ajcvickers** [comment]
@plittlewood-rpt Yes, that could make a difference. It means that you will only get a single instance of the DbContext per Repository instance, since a dependent service is only injected when a new instance of the higher-level service is created, regardless of whether the injected service is transient or not.
