### ISSUE TITLE
Does Compiled models work when using Lazy loading without proxies?

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#26917]
At https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#compiled-models it reads "Lazy loading and change-tracking proxies are not supported".

Does it mean, that Compiled models work when using Lazy loading without proxies, i.e. like https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies?

**Comment by ajcvickers** [comment]
@henrikdahl8240 Yes; only proxies are not supported.
