### ISSUE TITLE
EF Core Migration Bundles: no way to passthrough custom args to generated efbundle

### ISSUE THREAD

**Issue by bo-bac** [dotnet/efcore#26945]
I use IDesignTimeDbContextFactory and custom args in CreateDbContext(string[] args)

Then it is possible to apply update like so
`dotnet ef database update -- --environment TEST

It is expected to do the same with bundles 
` .\efbundle.exe -- --environment TEST

**Comment by ajcvickers** [comment]
Note for triage: repros for me.

```
PS C:\local\code\AllTogetherNow\SixOh> dotnet ef database update -- --environment TEST
Build started...
Build succeeded.
--environment
TEST
Applying migration '20211217110035_One'.
Done.
PS C:\local\code\AllTogetherNow\SixOh> dotnet ef migrations bundle
Build started...
Build succeeded.
Building bundle...
Done. Migrations Bundle: C:\local\code\AllTogetherNow\SixOh\efbundle.exe
PS C:\local\code\AllTogetherNow\SixOh> .\efbundle.exe -- --environment TEST           
Specify --help for a list of available options and commands.
Unrecognized option '--'
PS C:\local\code\AllTogetherNow\SixOh> .\efbundle.exe --environment TEST   
Specify --help for a list of available options and commands.
Unrecognized option '--environment'
PS C:\local\code\AllTogetherNow\SixOh>
```

/cc @bricelam

**Comment by bricelam** [comment]
Doh, looks like I forgot to set `AllowArgumentSeparator` to true in [MigrationsBundle.Configure](https://github.com/dotnet/efcore/blob/b39ca7f24c96df9aec977a29f35b1c0c70b54f5f/src/EFCore.Design/Migrations/Design/MigrationsBundle.cs#L65).
