### ISSUE TITLE
Migration step duplicate assembly?

### ISSUE THREAD

**Issue by Bidou44** [dotnet/efcore#2694]
I installed the latest beta 6 nightly build, created a small model with a DbContext (ConsoleApplication + Framework 4.5, VS 2013) and then, in the Package Manager Console, entered the following:

PM> Add-Migration
cmdlet Add-Migration at command pipeline position 1
Supply values for the following parameters:
Name: InitialMigration
Cannot execute this operation because EntityFramework7.Commands is not installed in the targeted Project

I then installed this package, but after that nothing compiled any more. It seems that there is a conflict between some assemblies. A part of my package.config:

`<package id="EntityFramework.Core" version="7.0.0-beta6-13752" targetFramework="net45" />
  <package id="EntityFramework.Relational" version="7.0.0-beta6-13752" targetFramework="net45" />
  <package id="EntityFramework.SqlServer" version="7.0.0-beta6-13752" targetFramework="net45" />
  <package id="EntityFramework.SqlServer.Design" version="7.0.0-beta6-13752" targetFramework="net45" />
  <package id="EntityFramework7.Commands" version="7.0.0-beta7-13816" targetFramework="net45" />
  <package id="EntityFramework7.Core" version="7.0.0-beta7-13816" targetFramework="net45" />
  <package id="EntityFramework7.Relational" version="7.0.0-beta7-13816" targetFramework="net45" />
  <package id="EntityFramework7.Relational.Design" version="7.0.0-beta7-13816" targetFramework="net45" />`

**Comment by ErikEJ** [comment]
Make sure all pacakges are the same daily buid - ie 7.0.0-beta7-13816, and remove the EF7 ones from your project/references, only use the ones named "EntityFramework.*"

**Comment by Bidou44** [comment]
The latest version is the 13679, not 13816 (this is what I see in VS2013 for the package EntityFramwork).
I installed the EntityFramwork7.* because of the message I received after doing an "Add-Migration" (see my first post) :

`Cannot execute this operation because EntityFramework7.Commands is not installed in the targeted Project`

**Comment by ErikEJ** [comment]
I think that could be a missing rename @bricelam  ??

**Comment by Bidou44** [comment]
Not sure that it is a missing rename, because i do have a reference on EntityFramework.Command, and it still does not work. I always have the following error in Package Manager Console:

`Cannot execute this operation because EntityFramework7.Commands is not installed in the targeted Project`

**Comment by bricelam** [comment]
It looks like we're still waiting for the EntityFramework7 -> EntityFramework re-rename to make it through our CI.

**Comment by rowanmiller** [comment]
Renames have all made their way through, and we have deleted the EntityFramework7.* packages from the feed.

Can you confirm if you are still seeing this with the latest nightly build?

**Comment by rowanmiller** [comment]
Closing out as we think this is resolved now that the renames have propagated and old packages removed from feed. Feel free to reopen if not.
