### ISSUE TITLE
Make context.Database.Migrate able to find migrations using an assembly name and namespace

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#26957]
I have been trying to get context.Database.Migrate working. I have used the model of a derived DbContext per provider and one assembly to store the different migrations. I have also used one derived DbContext with a migration assembly per provider. Both have difficulties. Then I looked at the DbContextAttribute and had the question "Does context.Database.Migrate look for migrations based on this attribute?". I don't know if it does, I have not looked at the source, but it seems like running migrations from code could be much simpler. I don't make that statement as put down on the development team, I am trying to suggest something that is not DbContext centered, which seems to cause more problems than it solves when running context.Database.Migrate.

For the assembly per provider case I had to run the code, shown below, to do a migration in code, because the context.Database.Migrate could not load the migration assembly, and then could not open the database file. 

I have been over the article, [Applying Migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli
), and we do not want to generate a script, use command line tools or create a bundle. We want to apply migrations using something like context.Database.Migrate but where the migrations are independent of any derived DbContext.

Would it make context.Database.Migrate easier to run and simpler to find migrations if we could specify a namespace and an assembly, rather than just an assembly. If migrations are in a single assembly we  need one context per provider, and if they are in a different assembly then context.Database.Migrate cannot load the assembly. Would specifying a namespace and assembly remove the problems, and allow migrations in a single assembly with one or more DbContext, and allow for removal of any kind of derived DbContext and or the DbContextAttribute. context.Database.Migrate could then look for classes in the assemblies specified namespace that derive from Migration.

`using Microsoft.EntityFrameworkCore;
 using Microsoft.EntityFrameworkCore.Infrastructure;
 using Microsoft.EntityFrameworkCore.Migrations;

           var path = AppDomain.CurrentDomain.BaseDirectory;

            switch ( DatabaseType )
            {
                case DatabaseType.SQLite:

                    {
                        var assemblyPath = Path.Combine ( path, "SqliteMigration.dll" );
                        var assemblyName = AssemblyLoadContext.GetAssemblyName ( assemblyPath );
                        var assembly = Assembly.LoadFrom ( assemblyPath );
                    }

                    break;

                case DatabaseType.MsSql:

                    {
                        var assemblyPath = Path.Combine ( path, "MsSqlMigration.dll" );
                        var assemblyName = AssemblyLoadContext.GetAssemblyName ( assemblyPath );
                        var assembly = Assembly.LoadFrom ( assemblyPath );
                    }

                    break;
            }

            var migrator = context.Database.GetService<IMigrator> ();

            await migrator.MigrateAsync ();

            //context.Database.Migrate ();`

Refer to #26889 in what I thought was a bug, but is really the work involved to get context.Database.Migrate running.

**Comment by ajcvickers** [comment]
@dgxhubbard It seems to me that using a derived context is much easier than doing this. Is there a particular reason you can't use the derived context approach?

**Comment by dgxhubbard** [comment]
@ajcvickers 
We have been developing our code since EF4, now in EF Core 6 we are trying to get migrations working.
Latest issue in our code is migrations not being able to find database annotations. With multiple context there are more places to not have the setup correct. In addition, we won't use migrations update from the command line so now we need to use a different context for each database provider and call that Database.Migrate on that context. Tying migrations to a separate context for each provider is redundant and makes for more places that something might be wrong. We have used one database context for years, and I believe the only reason migrations requires multiple contexts now was to enable not needing some way to call setup code when generating a migrations. With a connection string, namespace and assembly there are less places to change in code to generate and apply migrations

**Comment by ajcvickers** [comment]
@dgxhubbard 

> Latest issue in our code is migrations not being able to find database annotations.

If you can provide a repro for this, then it's certainly something we would investigate/fix.

> Tying migrations to a separate context for each provider is redundant and makes for more places that something might be wrong.

I don't think this is much of a burden, especially since the sample you provided already uses a factory to create context instances. It's an approach that has been used for years and is easily understandable.

**Comment by dgxhubbard** [comment]
This is not a fix it is a request for an improvement. When we use the command line to generate migrations we have to give a context that is specified for that provider in order to differentiate the provider. I understand the DbSets are in the context. I am looking to open up the migration code, so that users can create their own command line app to run it and then initialize their db context how they choose. We have a db context for each provider, in order to run migrations from the command line. In our code we have one db context for all providers and it is setup the way we want it set up. With the command line we have to replicate the setup to each of these db context, and then use then in our code to create or upgrade a database. That is their only purpose. By opening up the migration tools to being used in our command line app we can setup everything the way we need, not replicate this setup across the board

**Comment by ajcvickers** [comment]
> This is not a fix it is a request for an improvement. 

I understand that, and I'm saying it's not something that we are going to do.
