### ISSUE TITLE
Store column order in model snapshot

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#26956]
If no explicit order is specified we determine the column order partially based on the property declaration order on the CLR types. However for down migrations the snapshot is used and it doesn't have associated CLR types.

This means that in some cases when a migration that deletes a table is reverted the table columns will be in a different order.

We can precaulculate and store the column order in the design-time model only.

Also we shouldn't use declaration order for indexer properties and navigations.

**Comment by ajcvickers** [comment]
Note from triage: it is intentional that order is not changed when going from one undefined order in the model to another undefined order in the model. Ordering is only tracked when it is defined.
