### ISSUE TITLE
Table-valued parameters are not allowed in remote calls between servers

### ISSUE THREAD

**Issue by apetrut** [dotnet/efcore#26951]
Hi,

I am using SQL Server v18.1.

When I execute the below code, I get this error:

**Table-valued parameters are not allowed in remote calls between servers.**

```
var tableParameter = new SqlParameter()
            {
                SqlDbType = SqlDbType.Structured,
                TypeName = "dbo.CustomTypeName",
                Value = dt
            };

            var result = await _myContext.My_Custom_DbSet
                .FromSqlInterpolated($"EXEC [Database_Name].[dbo].[My_Custom_Stored_Procedure] @DateFrom = {dateFrom}, @DateTo = {dateTo}, @TableParameter= {tableParameter}")
                .AsNoTracking()
                .ToListAsync();

```
I know this was an issue with SQL Server 2008 like described [here](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b3f1a1d2-6016-4273-8f1c-23d2a4cf071a/erro-7380-tablevalued-parameters-are-not-allowed-in-remote-calls-between-servers?forum=sqldataaccess).

Is this still a limitation of SQL Server or is it some setting that needs to be made to make it work?

Thanks.

**Comment by roji** [comment]
@apetrut this seems to be purely a SQL Server question that isn't related to EF Core in any way. I'd recommending consulting the SQL Server docs or posting a question on stackoverflow or a similar forum.

**Comment by apetrut** [comment]
@roji , I am using EF Core 3.1 hence I believe it's also related to it.

**Comment by roji** [comment]
@apetrut what makes you think this is related to EF Core? This is a pure SQL Server error triggered by using raw SQL (which happens to be done via EF Core APIs) - are you able to make this work by using SqlClient directly, without EF Core?

**Comment by apetrut** [comment]
@roji I found a workaround. Details can be found [here](https://stackoverflow.com/questions/12719738/executing-remote-procedure-with-user-defined-table-type-variable-parameter).
