### ISSUE TITLE
db.EnsureCreated() doesn't seem to create views

### ISSUE THREAD

**Issue by sjd2021** [dotnet/efcore#26965]
"Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'no such table: my_view'.

Setup:
```
  builder.Entity<MyView>(entity =>
            {
                entity.ToView("my_view");
            });

```

Usage:

```
ctx.Database.EnsureDeleted();
ctx.Set<MyView>().Where(x => x.Id == id);
```

This code works when the view exists. The tables are created, but the view is not so I'm unable to craft the unit tests I'd like to use for this type of thing.

### Include version information

Microsoft.Data.Sqlite version: 
![image](https://user-images.githubusercontent.com/84007094/145653560-7cf7a69d-00d5-4651-8baf-bd544e010963.png)

Target framework: .NET Core 3.1
Operating system: Windows and Ubuntu

I found this as a general issue so I'm not sure I've posted on the correct repository: https://stackoverflow.com/questions/60663961/ef-core-3-1-creating-views-in-sqlite-in-memory-database-for-testing

**Comment by ajcvickers** [comment]
@sjd2021 This is tracked by #14537.
