### ISSUE TITLE
'variable '__p_1' of type 'System.Collections.Generic.IEnumerable`1[FileModel]' referenced from scope '', but it is not defined'

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#26964]
Using Net 6 and Entity Framework Core I have the query:

```C#
    var models = context.Posts
      .Select(x => new Model {
        Id = x.Id,
        Files = 
          !fieldsToLoad.Contains("files") ? new List<FileModel>() :
            x.PostFiles.Select(y => new FileModel {
              Id = y.File.Id,
            })
        }).ToListAsync();
```

This query was running on Net Core 5 but with Net 6 I get the exception:

    Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'The client projection contains a reference to a constant expression of 'System.Collections.Generic.List<FileModel>'. This could potentially cause a memory leak; consider assigning this constant to a local variable and using the variable in the query instead.

I then used local variables:

```C#
    var loadFiles = fieldsToLoad.Contains("files");

    files = new List<FileModel>(); // Strangely I had to also add this

    var models = context.Posts
      .Select(x => new Model {
        Id = x.Id,
        Files = 
          loadFiles ? 
          x.PostFiles.Select(y => new FileModel {
            Id = y.File.Id,
          }) :
          files
        }).ToListAsync();
```

Now I get the error:

    Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'variable '__p_1' of type 'System.Collections.Generic.IEnumerable`1[FileModel]' referenced from scope '', but it is not defined'

This only happens if `loadFiles` is `false` so the post `Files` would be `files`, e.g.,  an empty list of `FileModel`.

**Side note:**

The objective is to include some child collection conditionally to optimize an API response ...
I'm not using `Include` because some File table columns have large content and I need to exclude them using projection.

### Further technical details
- ASP.NET Core version: 6.0.0
- VS Code version: Version: 1.63.0

<details>
  <summary>dotnet --info Output</summary>

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

</details>

**Comment by smitpatel** [comment]
This is **NOT** a regression. Query failed same way in 5.0 also.

**Comment by MVanella-Sabal** [comment]
Is there a workaround for this for those of us who cannot upgrade to 7 at the moment?

**Comment by roji** [comment]
@MVanella-Sabal note that the first issue above has a pretty easy workaround. For the second one, I don't think there's a workaround unfortunately. EF 8.0 (which is LTS) will be out in about a month, I recommend planning for upgrading to that in any case.
