### ISSUE TITLE
Referencing Microsoft.EntityFrameworkCore.Tools from a WASDK 1.0 / WinUI 3 / .NET 6 project causes build to fail.

### ISSUE THREAD

**Issue by kmgallahan** [dotnet/efcore#26973]
## File a bug

Referencing Microsoft.EntityFrameworkCore.Tools from a project that uses WASDK, WinUI 3, and .NET 6 results in build failure.

```
C:\Users\kmgal\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): error APPX1101: Payload contains two or more files with the same destination path 'MyApp.deps.json'. Source files: 
C:\Users\kmgal\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): error APPX1101: C:\Dev\Projects\MyApp\MyApp\obj\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\MyApp.deps.json
C:\Users\kmgal\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): error APPX1101: C:\Dev\Projects\MyApp\MyApp\bin\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\MyApp.deps.json
```

### Include your code

Create a project using the basic WinUI 3 single project app template and modify the `.csproj`:

```
<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0" />
```

A sample project can also be found here:

https://github.com/microsoft/microsoft-ui-xaml/issues/6465#issue-1077623561

### Include provider and version information

EF Core version: 6.0.0
Database provider: N/A
Target framework: .NET 6
Operating system: Windows 10 build 19044.1348
IDE: VS Community 2022, v17.1.0 Preview 1.1

**Comment by bricelam** [comment]
This is being tracked internally.

Adding this to your csproj might work around the issue.

```xml
<PropertyGroup>
  <GenerateRuntimeConfigurationFiles>False</GenerateRuntimeConfigurationFiles>
</PropertyGroup>
```
