### ISSUE TITLE
Issue with HasPartitionKey when specify nested property

### ISSUE THREAD

**Issue by naveen-arcadis** [dotnet/efcore#26978]
## Ask a question
I am trying to configure EF core with Cosmos DB most of the part works but when I specify partition key using 'HasPartitionKey' method so it throws following exception

The expression 'e => e.myObject.SomeProperty' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')

Now my Partition Key is in nested object, isn't it possible to provided nested property?

### Include your code
```C#
// in my context file
modelBuilder.Entity<MyEntity>(elem =>
{
    elem.ToContainer("myContainerName");
    elem.HasNoDiscriminator();
    elem.HasPartitionKey(e => e.data.myProperty);
    elem.OwnsOne(p => p.data, d =>
      {
          d.OwnsOne(p => p.SomeOtherObject);
      });
});

// in service while querying

 var re = context.MyEntity.WithPartitionKey("myPropertyValue").ToList(); 
```
### Include stack traces
```
The expression 'e => e.data.myProperty' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 6.0 (LTS)
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@naveen-arcadis This currently isn't possible; it is tracked by #25548. Make sure to vote (👍) for that issue.
