### ISSUE TITLE
Owned entity with compound key

### ISSUE THREAD

**Issue by Zefek** [dotnet/efcore#26984]
Hello,

I didn't find anything about owned entity with compound key. In our database each table has compound key because of we have database for each department. So in each table there are columns as Id - which is unique for each department/table and DepartmentId - which is Id of department. Data is replicated between departments so there are records in table as follow (Id - DepartmentId):

1 - 1
2 - 1
3 - 1
1 - 2
2 - 2
3 - 2
1 - 3
2 - 3
3 - 3
etc...

There is no problem with relations between entities. But how to set this key to owned entity? When I use HasKey there is exception Method not found. 

Second problem with this is that Id value cannot be as identity column but each table has table with identity column which takes last Id for table on department. So when I want to insert new entity (owned or not) I need to insert record to table with identity column and give new Id value back. I have tested solution how to give new Id value. 

My entities likes follow:

```C#
public class Order
{ 
    public string OrderNumber { get; set; }
    public ICollection<OrderStatus> Statuses { get; set; }
}

public class OrderStatus
{
    public int Id { get; set; }
    public int DepartmentId { get; set; }
    public string Code { get; set; }
    public string OrderNumber { get; set; }
    public DateTime StatusDate { get; set; }
}
```

In OnModelCreating I have likes follow:

```C#
modelBuilder.Entity<Order>(order=>
{
    order.ToTable("Orders");
    order.HasKey(k=>k.OrderNumber);
    order.OwnsMany(k=>k.Statuses, status=>
    {
        status.ToTable("OrderStatuses");
        status.HasKey(k=>new { k.Id, k.kDepartmentId });
        status.WithOwner().HasForeignKey(k=>k.OrderNumber);
    }
}
```

This code throws System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.KeyBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.OwnedNavigationBuilder`2.HasKey(System.Linq.Expressions.Expression`1<System.Func`2<!1,System.Object>>)'.

**Comment by ajcvickers** [comment]
@Zefek "MissingMethodException" often means that there are multiple different versions of the EF Core packages referenced. Can you post your csproj, or better yet, please attach a small, runnable project that reproduces what you are seeing so that we can investigate.

**Comment by Zefek** [comment]
I need to solve another issues, please stand by. I have this issue in order ...

**Comment by Zefek** [comment]
@ajcvickers Thank you. There was problem with migration project to .net6.0 but some libraries were in .netstandard2.1 so WebApi project references .net6.0 packages and these libraries reference .net3.0 packages. After migration to .net6.0 all libraries, everything is fine.
