### ISSUE TITLE
[Cosmos] How and where discriminator functionality is implemented?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/efcore#26980]
I'm building a library to access Cosmos DB in F# and as long as EF Core 6 already implemented the ability to store different models in the same container I'd like to borrow that logic to my library.
Could you point me to the files where it is implemented?
Maybe you have some explanation in form of a diagram, a text, or a video to get into it quickly.

**Comment by ajcvickers** [comment]
@xperiandri The EF Core Cosmos provider is tightly coupled to the EF Core model, as implemented for all providers. I doubt it will be worthwhile to try exact anything useful from that code. That being said, if you want to try, then the Cosmos discriminators are created using [CosmosDiscriminatorConvention](https://github.com/dotnet/efcore/blob/main/src/EFCore.Cosmos/Metadata/Conventions/CosmosDiscriminatorConvention.cs), which is an EF model building convention.
