### ISSUE TITLE
Insert Order (Incorrect) for children entities after upgrading from 3.1 to 6

### ISSUE THREAD

**Issue by ahmedtolba1984** [dotnet/efcore#26997]
Dears,
I faced an issue when upgrading my project from .NET Core 3.1 to latest version 6.0,
I have an entity Customer with children collection (Person Documents), when inserting the customer with its person documents, i can see the documents inserted order is different from the behavior we have in 3.1
Let us say, we have a customer with Identity first and Driver License second, when i check the database for the inserted rows, i can see  Driver License get created first, then Identity, in 3.1, it was working properly

``` 
var customer = new Customer
{
    Name = "Customer1",
    Documents = new List<PersonDocument>()
    {
        new Identity
        {
            Number = "Identity1"
        },
        new DriverLicense
        {
            Number = "Driver1"
        }
    }
};

using (var ctx = new CustomersDbContext())
{
    ctx.Customers.Add(customer);
    ctx.SaveChanges();
}`

This is a sample that describe my isue
[https://github.com/ahmedtolba1984/EFCore6.0_Parent_With_Children]


Further technical details
EF Core version: 6.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2022

![EF_Children_Issue](https://user-images.githubusercontent.com/6592222/146007738-65132b77-0f13-4041-8a06-e42c956026a0.png)

**Comment by roji** [comment]
@ahmedtolba1984 insertion rows doesn't actually control the ordering of the rows in the database; in fact, unless you explicitly specify the ordering you want via ORDER BY, databases return rows in completely non-deterministic order, regardless of the storage order on disk. If 3.1 was providing a certain ordering that matched the insertion ordering, that was coincidental.

Use OrderBy to specify the ordering you want in your queries.

**Comment by ahmedtolba1984** [comment]
@roji 
I got your point but i am wondering that was working properly in 3.1, I mean if Customer Documents list contains Identity(First), Driver (Second), then the row inserted in this order but that doesn't happen in EF 6.0, they always inserted Driver first, then Identity Second

**Comment by roji** [comment]
@ahmedtolba1984 it's possible that the insertion order did indeed change between EF Core 3.1 and 6.0, and that by coincidence, that affected the (non-deterministic!) ordering of rows selected. However, nothing about the above is guaranteed - various seemingly unrelated operations (e.g. insertion of another unrelated row, creation of an index) could suddenly make the database return rows in a different order, regardless of how they were inserted. If row order is important to you in your query, then that query must include an implicit OrderBy operator.

**Comment by ahmedtolba1984** [comment]
@roji 
Thanks :)
