### ISSUE TITLE
Update Production Database to With Migration Files

### ISSUE THREAD

**Issue by Rsaleh11** [dotnet/efcore#26998]
I'm using code-first database approach in my project. and I want to reflect the changes to production server. I tried to use the following peace of code in startup file to achieve this target but it doesn't work :

```
using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                var context = serviceScope.ServiceProvider.GetRequiredService<BaseDBContext>();
                var GetPendingMigrations = context.Database.GetPendingMigrations(); // Used to check data 
                var GetAppliedMigrarions = context.Database.GetAppliedMigrations();// Used to check data 
                
                context.Database.Migrate();
            }
```
How to update production database with latest migration files in entity framework core ?

**Comment by roji** [comment]
@Rsaleh11 `context.Database.Migrate()` should indeed update your target database to the latest migration. Check that you've created the new migration (e.g. `dotnet ef migrations add ...`), that on your production server you're actually running the latest version of your application (which includes that new migration), and that your application is actually running against the expected database.

Documentation on managing and applying migrations can be found [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli).
