### ISSUE TITLE
Migrations : dropping a column leaves the snapshot out of sync - is it ok to manually modify snapshots?

### ISSUE THREAD

**Issue by AlexSapple** [dotnet/efcore#27017]
Trying to work through the following scenario on a code first database that has got me a bit stuck.

two entities that were linked by foreign key (in this case it was an entity called whiteboard and an entity called meeting) - where the whiteboard entity belonged to the meeting. 

one day, it was decided to decouple the whiteboard entity from the meeting entity and so I updated the model and removed the foreign key field `MeetingId` from the whiteboard entity. Great - the (UP) migration looked like;

            migrationBuilder.DropForeignKey(
                name: "FK_Whiteboards_Meetings_MeetingId",
                table: "Whiteboards");

            migrationBuilder.AlterColumn<int>(
                name: "MeetingId",
                table: "Whiteboards",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AddForeignKey(
                name: "FK_Whiteboards_Meetings_MeetingId",
                table: "Whiteboards",
                column: "MeetingId",
                principalTable: "Meetings",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

excellent, EF doesn't drop the column as it has data - but now I want to be able to delete meetings, previously the relationship was cascaded but now the referentialAction is restrict and I get errors, so I wrote another (UP) migration - it looked like;

            migrationBuilder.DropForeignKey(
                "FK_Whiteboards_Meetings_MeetingId",
                "Whiteboards");

and we all moved on and everything seemed great, 

then 6 months later - someone decided, hey let's clean this up and actually drop the now redundant column `MeetingId` as we will not roll back to that point. 

so, I wrote another (UP) migration and it looked like;

            migrationBuilder.DropIndex("IX_Whiteboards_MeetingId", "Whiteboards");
            migrationBuilder.DropColumn("MeetingId", "Whiteboards");

so that seemed sensible, however after updating the database - when running the code, I now get SQL errors when querying the `Whiteboard` entity that the `MeetingId` column does not exist - which indeed it does not. 

So what's going on here - the `MeetingId` column is still present in the latest snapshot, and I hazard a guess that it's this structure in the snapshot that is resulting in the converted SQL still referencing it (it's not present in any entity or projection).

so assuming this is an out of sync issue - is it safe to just delete this from the snapshot? I don't know what manually editing the snapshot will do... any advice would be really appreciated. Dropping this column is not exactly important, but it's surely something that I should be able to do without issues...

### Include provider and version information

EF Core version: 5 and 6 
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET5 and then .NET6
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
> excellent, EF doesn't drop the column as it has data - but now I want to be able to delete meetings, previously the relationship was cascaded but now the referentialAction is restrict and I get errors,

The first change didn't remove the Foreign key from model. Since user removed configuration EF Core created foreign key by convention (that happens when there are navigation properties between entities). This convention foreign key is by default nullable unless configured otherwise. So the first migration is just making the column nullable and applying foreign key again with different referential action.

So the model still contains and uses the `MeetingId` property. If you modify the migration file directly (writing inside Up/Down methods) then it will update database but it doesn't change the runtime model used to generate queries and hence you are running into issues. You would need to actual update your model to remove the navigations so foreign key is actually removed (and EF Core doesn't generate a shadow property to use as foreign key)

**Comment by AlexSapple** [comment]
thanks @smitpatel - oh shoot, I think I've missed something obvious...

the relations were fully qualified, i.e. the Whiteboard entity had a "MeetingId" field and the Meeting entity had a collection of Whiteboard entities... it appears as though I've only removed the "MeetingId" field from the Whiteboard entity (i.e. only half of the qualified relation...) - :( this appears to have been a mistake of mine from months ago.. oh dear 

(because as soon as I read your comment above - I thought, hey... I did remove it from the Model... but looks like I didn't fully remove it)

**Comment by AlexSapple** [comment]
yup, I've removed the accidental navigation link and sure enough a new migration is taking care of the index, foreign key and drop column :) 

now I've just got to unpick it slightly because of the manual migrations that have already been run - that's the fun bit I guess :) but alas... my fault for screwing up in the first place. 

closing this - thanks @smitpatel for your guidance.
