### ISSUE TITLE
SqlServer: Translate string.IsNullOrEmpty with LIKE for column type char

### ISSUE THREAD

**Issue by nikodz** [dotnet/efcore#27013]
Hello,

As it's described in #23037 translation of `string.IsNullOrEmpty` is translated using `LIKE`. 
It's not working properly when column type is `char`.

In this sample, it returns 0
```SQL
select case when cast('' as char) like N'' then 1 else 0 end
```

But when I remove `N` (Unicode symbol) after `like`, then it works correctly and returns 1.
```SQL
select case when cast('' as char) like '' then 1 else 0 end
```

**Comment by smitpatel** [comment]
We need repro here. It is not possible to use string.IsNullOrEmpty on char type.
