### ISSUE TITLE
Migrations creates shadow key on entities with primary and foreign key relationship of the same name when it is not needed

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#27032]
[CoreMigrationMs.zip](https://github.com/dotnet/efcore/files/7737237/CoreMigrationMs.zip)

@ajcvickers 

We are using EF Core 6 and trying to move to using fluent api because our data annotations were being ignored in migrations add. In this example of blog and posts when we do migrations add we get the following warning:

The foreign key property 'Post.Blog_RID1' was created in shadow state because a conflicting property with the simple name 'Blog_RID' exists in the entity type, but is either not mapped, is already used for another relationship, or is incompatible with the associated primary key type.

In the sample code Blog has primary key Blog_RID, and Post has navigation property Blog and Foreign Key Blog_RID. Both Blog_RIDs are integers, so there is no incompatibility problem. Posts Blog_RID is not used for anything besides being the foreign key for Blog. So it is not used for another relationship. 

If I rename Posts Blog_RID to AssociatedBlog_RID then I get no warning that a shadow key was created. Why does can migrations not distinguish between a primary key in one class and a foreign key in another class that have the same name. This is important because it means in our main code I would have to rename our foreign keys everywhere. The only reason we are using Fluent API is because in our main code Key is being ignored or not found.

**Comment by ajcvickers** [comment]
@dgxhubbard Your relationship configuration is this:

```C#
builder.HasOne ( c => c.Blog ).WithOne ().HasForeignKey<Post> ( c => c.Blog_RID );
```

This creates a 1:1 relationship with a navigation from Post to Blog, but no navigation from Blog to Post (because `WithOne()` is empty). This means that the `Blog.Posts` navigation is being explicitly excluded from this relationship, and hence is configured by convention as a navigation for a separate relationship, which in turn means that it needs another foreign key.

You probably want this instead:

```C#
builder.HasOne(c => c.Blog).WithMany(c => c.Posts).HasForeignKey(c => c.Blog_RID);
```

This creates a 1:* relationship with navigations in both directions. An additional foreign key is not needed, since both navigations are now part of the same relationship.

**Comment by dgxhubbard** [comment]
So is this a case of ef core does see both keys, but because it is not documented properly in fluent api that it will not recognize there are different properties in both classes? Because I had to do three days of renaming foreign keys because of this.

**Comment by ajcvickers** [comment]
> So is this a case of ef core does see both keys, but because it is not documented properly in fluent api that it will not recognize there are different properties in both classes? Because I had to do three days of renaming foreign keys because of this.

No. It's because `WithOne` was called with no arguments, indicating that there was no navigation property on that side of the relationship. (And also that it was a 1-to-1, not a 1-to-many.)
