### ISSUE TITLE
AddEntityFramework method error on OS X with latest beta6

### ISSUE THREAD

**Issue by d0pare** [dotnet/efcore#2704]
Getting such an error on OS X with `1.0.0-beta7-12264    mono         ~/.dnx/runtimes      default`

`Startup.cs(46,22): DNX,Version=v4.5.1 error CS0121: The call is ambiguous between the following methods or properties: 'Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework(Microsoft.Framework.DependencyInjection.IServiceCollection)' and 'Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework(Microsoft.Framework.DependencyInjection.IServiceCollection)'`

**Comment by natemcmaster** [comment]
Weird. Try cleaning EF packages (`rm -r ~/.dnx/packages/EntityFramework*`)?

**Comment by dopare** [comment]
Thanks, but didn't help :(

**Comment by dopare** [comment]
`1.0.0-beta7-12274    mono` have fixed this issue.
