### ISSUE TITLE
Why I can't use AsSplitQuery() in all places where I want to?

### ISSUE THREAD

**Issue by tkachuk2222** [dotnet/efcore#27044]
Why I can't use .AsSplitQuery() in all places where I want to?

I use .NET 5.0
EF Core NuGet package version is 5.0.13

in some part code, I can use .AsSplitQuery(), but in some parts of code, I can't use it. I don't understand why...
 
f.e.:
here I can use
```c#
var defaultEntity = await _dbContext.Entity1
                            .Include(e => e.ChildEntity)
                            .Include(e => e.ChildEntity2)
                            .Include(e => e.ChildEntity3)
                            .Include(e => e.ChildEntity4)
                            .Include(e => e.ChildEntity5).ThenInclude(e => e.ChildEntity6).ThenInclude(e => e.ChildEntity7)
                            .AsSplitQuery()
                            .FirstOrDefaultAsync(e => someId == e.Id, CancellationToken.None);`
```

here I can't use:

![image](https://user-images.githubusercontent.com/20381930/146750595-afecdc0f-d54b-4de6-9e78-afca15256f4c.png)

EF Core version: 5.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.11.7

**Comment by roji** [comment]
@tkachuk2222 AsSplitQuery lives in the Microsoft.EntityFrameworkCore.Relational package, make sure you're referencing that and importnig the Microsoft.EntityFrameworkCore namespace. If it's still not working, please submit a runnable code sample which triggers the error.

**Comment by tkachuk2222** [comment]
> 

ah, It's an answer to my question. didn't see this information in the documentation.

thanks.
