### ISSUE TITLE
does efcore has IDbCommandTreeInterceptor like ef6?

### ISSUE THREAD

**Issue by flyingfive** [dotnet/efcore#27043]
I have to auto trim string values from query in db when use linq to ef. 
In my old solution in .net framework is defined a StringTrimmerQueryVisitor inherit from DefaultExpressionVisitor and then add a 
interceptor class implement by  IDbCommandTreeInterceptor。but i could't find both IDbCommandTreeInterceptor and DefaultExpressionVisitor in efcore now, is there any other suggestions, thanks~

**Comment by ajcvickers** [comment]
@flyingfive Interceptors for expression trees is tracked by #19748.

> I have to auto trim string values from query in db when use linq to ef.

Do you mean you want to trim parameter values, or something else?

**Comment by flyingfive** [comment]
> Do you mean you want to trim parameter values, or something else?

Sorry,  I want to auto trim the ending whitespace from db value into C#.  for db columns like char/varchar/nvarchar type when queried by linq, ex: dbType is char(6), when queried out from this column into C# like  "jason ", then compare to like "jason", the result is false.

**Comment by roji** [comment]
You should be able to do that with a [command interceptor](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#database-interception), that seems like a better way than intercepting the expression tree anyway.

**Comment by flyingfive** [comment]
> You should be able to do that with a [command interceptor](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#database-interception),

No, It's not a goods idea. In command interceptor now is whole sql script to be executed, it's hard to reslove which select columns are char/varchar/nvarchar type. and how to kown select clause is a subquery? i only want to trim final select columns returned to C#, don't need trim other columns like a subquery. 
Does EFCore don't supply a way that how to custom reslove linq expressions?

**Comment by roji** [comment]
> i only want to trim final select columns returned to C#, don't need trim other columns like a subquery.

Final select columns returned to C# aren't sent from your .NET client to your database as parameters - they're sent from your database back to the .NET client in the resultset. So these wouldn't be affected.

Parameters are indeed also used in queries when an external C# variable is referenced:

```c#
var name = "foo";
var blogs = context.Blogs.Where(b => b.Name == name).ToList();
```

If you don't want these to be trimmed, you can restrict your command interceptor to only work on DbCommands originating from SaveChanges, by checking that the CommandSource property of the CommandEventData is SaveChanges.

**Comment by flyingfive** [comment]
It's not about SaveChagnes and query parameters, I want sql script to be executed with EFCore like this:
`SELECT TOP (2) 
    RTRIM([Extent1].[oper_id]) AS [oper_id], 
    [Extent1].[save_discount] AS [save_discount], 
    [Extent1].[ctrl_branch] AS [ctrl_branch], 
    [Extent1].[ctrl_cls] AS [ctrl_cls], 
    [Extent1].[ctrl_sup] AS [ctrl_sup], 
    [Extent1].[ctrl_dept] AS [ctrl_dept], 
    RTRIM([Extent1].[oper_status]) AS [oper_status], 
    RTRIM([Extent1].[oper_type]) AS [oper_type], 
    RTRIM([Extent1].[data_grant]) AS [data_grant], 
    RTRIM([Extent1].[sp_flag]) AS [sp_flag], 
    RTRIM([Extent1].[oper_system]) AS [oper_system], 
    RTRIM([Extent1].[branch_no]) AS [branch_no], 
    RTRIM([Extent1].[confirm_pw]) AS [confirm_pw], 
    RTRIM([Extent1].[oper_range]) AS [oper_range], 
    RTRIM([Extent1].[pos_id]) AS [pos_id], 
    RTRIM([Extent1].[oper_name]) AS [oper_name], 
    RTRIM([Extent1].[oper_pw]) AS [oper_pw], 
    [Extent1].[last_time] AS [last_time], 
    [Extent1].[output_rate] AS [output_rate], 
    RTRIM([Extent1].[in_price]) AS [in_price], 
    RTRIM([Extent1].[auth_flag]) AS [auth_flag], 
    RTRIM([Extent1].[tools_flag]) AS [tools_flag], 
    RTRIM([Extent1].[homepage_map_menuid]) AS [homepage_map_menuid], 
    RTRIM([Extent1].[openid]) AS [openid], 
    RTRIM([Extent1].[save_grant]) AS [save_grant]
    FROM [dbo].[t_sys_operator] AS [Extent1]
    WHERE [Extent1].[oper_id] = @p0`
The string columns are auto around by RTRIM, and the database value without whitespaces returned into C# client

**Comment by roji** [comment]
@flyingfive sorry, I misunderstood this being about parameters.

First, it may be possible to perform the trimming via [value converters](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations). That is, instead of injecting RTRIM around every text column in the database, you may be able to use [bulk configuration](https://docs.microsoft.com/en-us/ef/core/modeling/bulk-configuration) to set up a value converter for all your string properties which trims in .NET as values come back from the database.

Otherwise, you can indeed set up an expression tree visitor in EF Core's query pipeline. This is probably more work than EF6's interceptor, but it will work. Below is a code sample doing wrapping all `nvarchar(max)` column expressions with RTRIM - you may want to use that as a basis.

Finally, I can only recommend sanitizing the database values themselves, in the database, rather than trimming them in your SQL expressions - though of course there are scenarios where that's not feasible.

<details>
<summary>Sample trimming visitor</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var blogs = ctx.Blogs.Where(b => b.Name == "foo").ToList();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .ReplaceService<IRelationalParameterBasedSqlProcessorFactory, TrimmingParameterBasedSqlProcessorFactory>()
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}

class TrimmingParameterBasedSqlProcessorFactory : IRelationalParameterBasedSqlProcessorFactory
{
    public TrimmingParameterBasedSqlProcessorFactory(
        RelationalParameterBasedSqlProcessorDependencies dependencies)
    {
        _dependencies = dependencies;
    }

    private RelationalParameterBasedSqlProcessorDependencies _dependencies;

    public RelationalParameterBasedSqlProcessor Create(bool useRelationalNulls)
        => new TrimmingParameterBasedSqlProcessor(_dependencies, useRelationalNulls);

    class TrimmingParameterBasedSqlProcessor : SqlServerParameterBasedSqlProcessor
    {
        public TrimmingParameterBasedSqlProcessor(RelationalParameterBasedSqlProcessorDependencies dependencies, bool useRelationalNulls)
            : base(dependencies, useRelationalNulls)
        {
        }

        public override SelectExpression Optimize(
            SelectExpression selectExpression,
            IReadOnlyDictionary<string, object?> parametersValues,
            out bool canCache)
        {
            var optimizedSelectExpression = base.Optimize(selectExpression, parametersValues, out canCache);

            optimizedSelectExpression =
                (SelectExpression)new ColumnTrimmingExpressionVisitor().Visit(optimizedSelectExpression);

            return optimizedSelectExpression;
        }

        class ColumnTrimmingExpressionVisitor : ExpressionVisitor
        {
            protected override Expression VisitExtension(Expression extensionExpression)
                => extensionExpression is ColumnExpression { TypeMapping.StoreType: "nvarchar(max)" } columnExpression
                    ? new SqlFunctionExpression(
                        "RTRIM",
                        new[] { columnExpression },
                        true,
                        new[] { true },
                        columnExpression.Type,
                        columnExpression.TypeMapping)
                    : base.VisitExtension(extensionExpression);
        }
    }
}
```

</details>

**Comment by flyingfive** [comment]
@roji Thanks for your valueable suggestion and the sample code. It's very helpful me. There are some historical reasons, and i have to think about this way to trim db values.
Thanks, and merry christmas~

**Comment by roji** [comment]
> There are some historical reasons, and i have to think about this way to trim db values.

Note specifically that adding RTRIM everywhere probably prevents you from using indexes in your queries - this could impact performance in a very serious way. It's always better to clean up your actual data if that's at all possible.

**Comment by flyingfive** [comment]
Thanks for you notice~ I know that is not a good way for high query performance. And it can be ignore in my case, because there are not too many rows in my table(less than 10000 rows per table).

**Comment by flyingfive** [comment]
> 

Thanks for you notice~ I know that is not a good way for high query performance. And it can be ignore in my case, because there are not too many rows in my table(less than 10000 rows per table).

**Comment by flyingfive** [comment]
> > There are some historical reasons, and i have to think about this way to trim db values.
> 
> Note specifically that adding RTRIM everywhere probably prevents you from using indexes in your queries - this could impact performance in a very serious way. It's always better to clean up your actual data if that's at all possible.

Thanks for you notice~ I know that is not a good way for high query performance. And it can be ignore in my case, because there are not too many rows in my table(less than 10000 rows per table).
