### ISSUE TITLE
Question: Is there a sample for SQLight?

### ISSUE THREAD

**Issue by manfredsteyer** [dotnet/efcore#2705]
Hi,
I've read, that the current beta supports SQLight again. Is there a sample that shows how to use this Feature?
Wishes,
Manfred

**Comment by rowanmiller** [comment]
Hey,
SQLite will be supported in Beta6 (coming out shortly). There will be a walkthrough on our doc site (http://ef.readthedocs.org) that shows how to use SQLite.
~Rowan

**Comment by tinganho** [comment]
@rowanmiller how about Redis support?

**Comment by rowanmiller** [comment]
@tinganho We prototyped a Redis provider (to help us design the core to support non-relational stores) but we won't be working on that provider again until after we get the first stable release of EF7 out.

**Comment by manfredsteyer** [comment]
great. Thx for the quick reply.
