### ISSUE TITLE
LocalView<TEntity>.Contains returns true for detached entity

### ISSUE THREAD

**Issue by GromanSoft** [dotnet/efcore#27056]
class: Microsoft.EntityFrameworkCore.ChangeTracking.LocalView<TEntity>
method: Contains
bug: returns true for detached entity
solution: also check entry.EntityState != EntityState.Detached

**Comment by ajcvickers** [comment]
@GromanSoft I'm not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseInMemoryDatabase("Test")
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            var entity = new Blog { Name = "OneUnicorn" };

            Console.WriteLine($"Not tracked: {context.Blogs.Local.Contains(entity)}");

            context.Add(entity);

            Console.WriteLine($"Added: {context.Blogs.Local.Contains(entity)}");

            context.SaveChanges();

            Console.WriteLine($"Saved: {context.Blogs.Local.Contains(entity)}");

            context.Entry(entity).State = EntityState.Detached;

            Console.WriteLine($"Detached: {context.Blogs.Local.Contains(entity)}");
        }
    }
}
```

Output:

```
Not tracked: False
Added: True
Saved: True
Detached: False
```

**Comment by GromanSoft** [comment]
Add these 2 lines at the end of your test

            Console.WriteLine($"Is Detached: {context.Entry(entity).State == EntityState.Detached}");
            Console.WriteLine($"Now Detached: {context.Blogs.Local.Contains(entity)}");

When you change state from Unchanged to Detached state manager does not move entry to detached reference map.
But when you request entry for untracked entity it registers entry in detached reference map.
