### ISSUE TITLE
EF Core 3.1 - Allow mapping of multiple entities using stored procedure

### ISSUE THREAD

**Issue by KevinMaguire** [dotnet/efcore#27068]
Hi I was wondering if there are any plans to introduce soon the capability to allow mapping of related entities by calling stored procedures? ie: by using FromSqlRaw or FromSqlInterpolated?

( using EF Core 3.1, .Net Core 6.0, Visual Studio 2022)

If we take the 2 classes below, is it or will it be possible to execute 1 database call and create the Address entity inside my customer object?

 public class Customer
 {
      public int CustomerID { get; set; }
      public string Name{ get; set;}
      public Address Address{ get; set; }
  }
  
  public class Address
  {
     public int AddressID { get; set; }
     public string PremisesNo { get; set; }
     public string Line1{ get; set; }
     public string Line2{ get; set; }
     public string PostCode { get; set; }
 }

thanks

**Comment by smitpatel** [comment]
Duplicate of #14525
