### ISSUE TITLE
Entity Map ToSqlQuery  Skip Take Query slowly

### ISSUE THREAD

**Issue by ryanryanorient** [dotnet/efcore#27065]
## Skip Take slowly

```C#
Context.Set<Entity>().Skip(10000).Take(20).ToList()
```
Entity was Map to ToSqlQuery(" ....")

ToView is not affected 

Like this Url
https://entityframeworkcore.com/knowledge-base/49859193/parameterised-offset-fetch-next-query--ef-core--has-10x-slower-performance

The generated Sql query converts the offset value and fetch value into parameterized form, which causes the query to be very slow 

The larger the value of skip, the longer the query will take 

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 5.0)
Operating system:
IDE: (Visual Studio 2019 16.3)

**Comment by roji** [comment]
> The generated Sql query converts the offset value and fetch value into parameterized form, which causes the query to be very slow. [...] The larger the value of skip, the longer the query will take

@ryanryanorient it's true that the larger the value of skip, the longer the query is expected to take - [take a look at these docs](https://github.com/dotnet/EntityFramework.Docs/pull/3617/files#diff-4bae7c87f1e7ae6430998dcf323abcc835728d8b1e5f4a36d1a73df1b69469af) (which aren't yet live).

However, what makes you think that the query performance is worse because the offset value is parameterized? Can you point to any resources documenting this, or submit a minimal query scenario which shows this?

I've done a quick SQL test, and am strangely seeing that the parameterized query should actually run faster:

<details>
<summary>Test SQL</summary>

```sql
-- Setup: load 1,000,000 rows into a table
CREATE TABLE data (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(10));
CREATE INDEX IX_name ON data(name);

BEGIN TRANSACTION;

DECLARE @i INT = 0;
WHILE @i < 1000000
BEGIN
    INSERT INTO data (name) VALUES (CAST(@i AS NVARCHAR(MAX)));
    SET @i = @i + 1;
END;

COMMIT;

-- Turn on query plan dumps instead of execution
SET SHOWPLAN_ALL ON;

-- Query 1: with constant offset
SELECT * FROM data
ORDER BY name
OFFSET 900000 ROWS FETCH FIRST 10 ROWS ONLY;

-- Query 2: with parameterized offset
DECLARE @i INT = 900000;
SELECT * FROM data
ORDER BY name
OFFSET @i ROWS FETCH FIRST 10 ROWS ONLY;
```

</details>

### Query plan for constant offset value

```sql
SELECT * FROM data
ORDER BY name
OFFSET 900000 ROWS FETCH FIRST 10 ROWS ONLY",1,1,0,,,1,,10,,,,6.4733534,,,SELECT,false,
  |--Top(OFFSET EXPRESSION:((900000)),TOP EXPRESSION:((10))),1,2,1,Top,Top,"OFFSET EXPRESSION:((900000)),TOP EXPRESSION:((10))",,10,0,0.090001,25,6.4733534,"[test].[dbo].[data].[id], [test].[dbo].[data].[name]",,PLAN_ROW,false,1
       |--Index Scan(OBJECT:([test].[dbo].[data].[IX_name]), ORDERED FORWARD),1,3,2,Index Scan,Index Scan,"OBJECT:([test].[dbo].[data].[IX_name]), ORDERED FORWARD","[test].[dbo].[data].[id], [test].[dbo].[data].[name]",900010,5.992014,1.100157,25,6.3833523,"[test].[dbo].[data].[id], [test].[dbo].[data].[name]",,PLAN_ROW,false,1
```

### Query plan for parameterized offset value

```sql
DECLARE @i INT = 900000;,1,1,0,,,1,,,,,,,,,ASSIGN,false,
SELECT * FROM data
ORDER BY name
OFFSET @i ROWS FETCH FIRST 10 ROWS ONLY;",2,2,0,,,2,,10,,,,0.0033479,,,SELECT,false,
  |--Top(OFFSET EXPRESSION:(CONVERT_IMPLICIT(bigint,[@i],0)),TOP EXPRESSION:((10))),2,3,2,Top,Top,"OFFSET EXPRESSION:(CONVERT_IMPLICIT(bigint,[@i],0)),TOP EXPRESSION:((10))",,10,0,0.000001,25,0.0033479,"[test].[dbo].[data].[id], [test].[dbo].[data].[name]",,PLAN_ROW,false,1
       |--Index Scan(OBJECT:([test].[dbo].[data].[IX_name]), ORDERED FORWARD),2,4,3,Index Scan,Index Scan,"OBJECT:([test].[dbo].[data].[IX_name]), ORDERED FORWARD","[test].[dbo].[data].[id], [test].[dbo].[data].[name]",10,5.992014,1.100157,25,0.0033469,"[test].[dbo].[data].[id], [test].[dbo].[data].[name]",,PLAN_ROW,false,1
```

**Comment by ryanryanorient** [comment]
> ```sql
> TE TABLE data (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(10));
> ```

I found the reason
My query statement contains a join query, and its matching item types are inconsistent (varchar and nvarchar), which leads to excessive time-consuming
The strange thing is that when paging is not parameterized, its performance is not so bad (7s),
After parameterization, its time-consuming will increase significantly (60s),
This is not caused by EF CORE
Thanks for your reply
