### ISSUE TITLE
EnsureCreated throws "The requested configuration is not stored in the read-optimized model" after version update 

### ISSUE THREAD

**Issue by msallin** [dotnet/efcore#27063]
Our tests run against SQLite. After updating to the 6.0.1 version of EF Core, the following code doesn't work anymore. I found this issue #25154 but we do not use `IModelCacheKeyFactory`. 
Can you advise?

```csharp
using IServiceScope scope = WebApplicationFactory.Services.CreateScope();
IDbContextFactory<AppDbContext> dbContextFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
using AppDbContext dbContext = dbContextFactory.CreateDbContext();
dbContext.Database.EnsureCreated();
```

```
  Message: 
System.InvalidOperationException : The requested configuration is not stored in the read-optimized model, please use 'DbContext.GetService&lt;IDesignTimeModel&gt;().Model'.

  Stack Trace: 
RelationalEntityTypeExtensions.IsTableExcludedFromMigrations(IReadOnlyEntityType entityType)
Table.get_IsExcludedFromMigrations()
<>c.<GetSchemas>b__79_0(ITable t)
WhereSelectEnumerableIterator`2.MoveNext()
ConcatIterator`1.MoveNext()
WhereEnumerableIterator`1.MoveNext()
DistinctIterator`1.MoveNext()
SelectManySingleSelectorIterator`2.MoveNext()
ConcatIterator`1.MoveNext()
MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
RelationalDatabaseCreator.GetCreateTablesCommands(MigrationsSqlGenerationOptions options)
RelationalDatabaseCreator.CreateTables()
RelationalDatabaseCreator.EnsureCreated()
DatabaseFacade.EnsureCreated()
```

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0

**Comment by AndriySvyryd** [comment]
Do you call `.UseModel()` in the context configuration? Please provide a small repro project.

**Comment by msallin** [comment]
It actually was `IModelCacheKeyFactory`... I just didn't find it the first time. Sorry for bothering you and thank you for the quick reaction.

**Comment by yakeer** [comment]
@msallin 
Could you please explain how did you solve it?

I'm facing the same issue trying to use DynamicContext.

**Comment by msallin** [comment]
@yakeer problem was what was described here: https://github.com/dotnet/efcore/issues/25154
The new overload. I just missed it and then created the issue.

**Comment by yakeer** [comment]
Well, I did overload it in ModelCacheFactory, but still I get this exception when I'm trying to run this code:
in order to create a migration SQL dynamically on  runtime.


```
var infrastructure = this.GetInfrastructure();
var migSqlGen = infrastructure.GetService<IMigrationsSqlGenerator>();
var modelDiffer = infrastructure.GetService<IMigrationsModelDiffer>();
var conn = infrastructure.GetService<IRelationalConnection>();
var diffs = modelDiffer.GetDifferences(this.GetService<IDesignTimeModel>().Model.GetRelationalModel(),
                                       Model.GetRelationalModel());//  
```

Can you think of any reason why?

My cache factory is:
`
public class CapitanModelCacheKeyFactory : IModelCacheKeyFactory
    {
        public object Create(DbContext context, bool designTime) => (new CapitanModelCacheKey(context, designTime), designTime);

        //public object Create(DbContext context, bool designTime) => context is CapitanDbContext dynamicContext ? (context.GetType(), designTime) : (object)context.GetType();

        public object Create(DbContext context) => Create(context, false);
    }

    public class CapitanModelCacheKey : ModelCacheKey
    {
        readonly int? _contextVersion;

        public CapitanModelCacheKey(DbContext context, bool designTime) : base(context, designTime)
        {
            _contextVersion = (context as CapitanDbContext)?.GetContextVersion();
        }

        protected override bool Equals(ModelCacheKey other) => base.Equals(other)
                                                               && (other as CapitanModelCacheKey)?._contextVersion == _contextVersion;
    }`

**Comment by msallin** [comment]
Here what we did

```csharp
public class UseSqliteModelCacheKeyFactory : IModelCacheKeyFactory
{
    public object Create(DbContext context) => Create(context, false);

    public object Create(DbContext context, bool designTime)
    {
        if (context is not AppDbContext dynamicContext)
        {
            return context.GetType();
        }

        dynamicContext.UseSqliteProvider = true;
        return (context.GetType(), dynamicContext.UseSqliteProvider, designTime);
    }
}
```
