### ISSUE TITLE
Is it possible to disable optimistic concurrency checks temporarily?

### ISSUE THREAD

**Issue by groogiam** [dotnet/efcore#27070]
## Ask a question
Is it possible to disable optimistic concurrency checks on a given context? E.g. if there is a use case to update a entities regardless of it's current state? Something like below.  I have not been able to find a mechanism other than to reload the data and merge it from the database which is expensive or have a duplicated model without concurrency checks. It would be nice to just have the context ignore applying the checks in the first place. Thanks.

```C#
ctx.DisableConcurrencyChecks = true;
//update some entities
ctx.SaveChanges();
```
EF Core version:
Database provider: All providers
Target framework: 6.0

**Comment by ajcvickers** [comment]
Duplicate of #10443.

**Comment by nycgavin** [comment]
this is not the same issue as 10443, this is asking if we can force EF to not generate the concurrency check in the following generated SQL:

Delete from XYZ where ID = @P and RowVersion = NULL

when you want to delete an entity by ID

**Comment by roji** [comment]
@nycgavin how is that different from #10443? Removing the RowVersion from the WHERE is exactly what #10443 tracks.
