### ISSUE TITLE
Add a prompt y/n

### ISSUE THREAD

**Issue by nerd3717** [dotnet/efcore#27079]
Hello!
When creating a migration where a data type is converted from larger to smaller a warning is displayed:
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy

It would be nice to see here some prompt y/n, because some people may not pay attention to it.

**Comment by ErikEJ** [comment]
And what would a reply of "n" result in?

**Comment by sigmade** [comment]
I agree that many people ignore the warnings. Entity Framework Core already faced the issue of warnings  https://github.com/dotnet/efcore/issues/14935

**Comment by sigmade** [comment]
> And what would a reply of "n" result in?

Cancel Migration

**Comment by nerd3717** [comment]
> And what would a reply of "n" result in?

As I understand this happening after a migration have been created, I suppose the warning just result of comparing old and new state.
if there is any possibilities to predict this behaviour before 'creation', give a choice to user 'continue the process or not'

**Comment by ajcvickers** [comment]
@nerd3717 Best practice for any generated migration is to review it to ensure that it's doing what you expect/want it to do. This is also the case for migrations that _may_ cause data loss. The change might not _actually_ cause data loss in any _meaningful way_ to your application. Reviewing the migration is therefore the correct next step after this happens, after which it is easy to remove the migration if it isn't what was wanted.
