### ISSUE TITLE
Fluent Api - .Ignore() doesn't work for a specific property

### ISSUE THREAD

**Issue by FraidZ** [dotnet/efcore#27080]
Hello everyone!

I tried to apply `.Ignore()` to exclude a specific property from entity type but it doesn't work.

`.GetEntityTypes()` returns all my entities and also `Tuple <decimal, Nullable <decimal>> `

**Note:** EF ignores this property only through the attribute `[NotMapped]`

```C#
class Entity 
{
   public IEnumerable<Tuple<decimal, decimal?> Items { get; set; }
}

modelBuilder.Entity<Entity>().Ignore(x => x.Items);

// List of entity types contains Tuple <decimal, Nullable <decimal>> Keyless
var entityTypes = modelBuilder.Model.GetEntityTypes().ToList();

```

EF Core version: 5.0.12
Database provider: (e.g. Microsoft.EntityFrameworkCore.PostgreSQL)
Target framework: .NET 5.0
Operating system: Windows 10
IDE: JetBrains Rider 2021.2.2

**Comment by AndriySvyryd** [comment]
Unused entity types are removed from the model after it has been finalized.

If you need it to be removed before that you can call `modelBuilder.Ignore(typeof(Tuple<decimal, decimal?>));`
