### ISSUE TITLE
When scaffolding, namespace isn't added for generic type parameter within an array

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27087]
For example, a PostgreSQL column of type `CIDR[]` (array of IP subnets) is scaffolded as:

```c#
public ValueTuple<IPAddress, int>[] Subnets { get; set; }
```

But the System.Net namespace isn't used. System.Net is used when the value tuple isn't in an array, and also for IPAddress[] without the tuple (PostgreSQL type `inet[]`).

Flagged by @ajruckman in https://github.com/npgsql/efcore.pg/issues/2193

**Comment by ErikEJ** [comment]
Link seems wrong

**Comment by roji** [comment]
Thanks @ErikEJ, corrected.
