### ISSUE TITLE
EntityFrameworkCore6.0.0 memory footprint is very high

### ISSUE THREAD

**Issue by LingDian2019** [dotnet/efcore#27104]
## Ask a question

    Hi, I am testing Jmeter WebAPI and found the following problem, but I don't know where the problem is. Looking forward to your reply, thank you!

1：WebAPI test was conducted through Jmeter, with a total of three interfaces, two inserts and one paging query. The specific configuration is as follows 
![image](https://user-images.githubusercontent.com/49890738/148036187-0ee38817-1dd8-406e-805b-1326d5dab2ee.png)

2：After a round of testing, the.NET WebAPI took up more than 7GB of memory, and the number of database connections completed was not released, and the memory was not reduced for more than an hour of observation

3：Below are some of the data analyzed by DMP with Microsoft Visual Studio Enterprise 2022
![image](https://user-images.githubusercontent.com/49890738/148036131-7fbf038b-8fb8-45f7-b70a-4be023c0b0c3.png)

### Include your code
databaseConfig.PoolSize：1024;
![image](https://user-images.githubusercontent.com/49890738/148034492-88fa2f70-82b5-41c3-ab11-0f644bde72a4.png)

### Include provider and version information

EF Core version:Microsoft.EntityFrameworkCore 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:.NET 6.0
Operating system:Windows 10 Professional
IDE:Microsoft Visual Studio Enterprise 2022 17.0.4

**Comment by roji** [comment]
@LingDian2019 the code sample above (CreateEntityFrameworkDatabaseContext) seems to create a PooledDbContextFactory every time a context is created. This is definitely how the factory is meant to be used - you should instantiate the factory exactly once, and then use that same factory repeatedly to get DbContext instances. This ensures that DbContext configuration and model building happens exactly, and that DbContext instances are pooled.

If after fixing this you're still seeing abnormal results, then please submit a full benchmarking project - preferably isolating EF Core (e.g. without ASP.NET) - it's always difficult to provide precise answers to performance questions when the full benchmarking code isn't provided.

**Comment by LingDian2019** [comment]
According to your suggestion, the modification is normal. Thank you very much
