### ISSUE TITLE
MigrationBuilder.InsertData does not use default schema anymore

### ISSUE THREAD

**Issue by 123fulltimedev** [dotnet/efcore#27100]
Assume a default schema is specified in `OnModelCreating`:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.HasDefaultSchema("dbo");
    }
```

An attempt to enter data in a migration's `Up` method:

```
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData("People", "Name", "John Doe");
        }
```

raises an exception: "There is no entity type mapped to the table 'People' which is used in a data operation. Either add the corresponding entity type to the model, or specify the column types in the data operation.".  With previous versions of EF Core (e. g. 3.1) there was not an issue.

When the schema is specified explicitly everything works fine again:

```
migrationBuilder.InsertData("People", "Name", "John Doe", "dbo");
```

If I interpret the documentation for `InsertData` correctly the default schema should be assumed if no schema is supplied explicitly.

**Comment by ajcvickers** [comment]
@123fulltimedev Are you writing the `InsertData` calls by hand? Or are these being generated when adding a migration?

**Comment by 123fulltimedev** [comment]
We have written the `InsertData` calls by hand.
