### ISSUE TITLE
"The entity of type ... does not have any property with a non-default value to identify whether the entity exists"

### ISSUE THREAD

**Issue by taspeotis** [dotnet/efcore#27111]
Hi,

Since upgrading to EF Core 6 I receive the following log message:

>  The entity of type `'SessionReportSessionOfCare.Address#Address'` with primary key values `{SessionReportSessionOfCareId: fa61d24f-0b98-46c5-b898-a43500a9e464}` is an optional dependent using table sharing. The entity does not have any property with a non-default value to identify whether the entity exists. This means that when it is queried no object instance will be created instead of an instance with all properties set to default values. Any nested dependents will also be lost. Either don't save any instance with only default values or mark the incoming navigation as required in the model.

I believe somewhere around here... 

https://github.com/dotnet/efcore/blob/1526c25eab53c8bd7efb58cbf98305d4e17727ea/src/EFCore.Relational/Update/ModificationCommand.cs#L284-L288

...EF Core has decided that it's ambiguous as to whether an `Address` exists or not. [The documentation](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#changes-to-owned-optional-dependent-handling) suggests it's because when the entity is persisted to the database all the columns could have `NULL` in them.

My model contains:

```cs
    [Owned]
    public sealed class Address {
        public string Line1 { get; set; } = default!;
        public string? Line2 { get; set; }
        public string Suburb { get; set; } = default!;
        public State State { get; set; }
        public string PostCode { get; set; } = default!;
    }

    public sealed class SessionReportSessionOfCare
    {
        public Guid Id { get; set; }
        ...
        public Address? Address { get; set; }
        ...
    }
```

Any of `Line1` or `Suburb` or `State` (especially `State` - it's an enum i.e. a value type so it cannot be null) or `PostCode` tells Entity Framework whether an `Address` should exist or not. All properties in the database being `NULL` unambiguously means `SessionReportSessionOfCare.Address` was `null`.

I do not believe the warning is correct in this instance.

I am not an EF Core contributor but to me the check I linked above should read something like:

```cs
            var optionalDependentWithAllNull =
                (entry.EntityState == EntityState.Deleted
                    || entry.EntityState == EntityState.Added)
                && tableMapping.Table.IsOptional(entry.EntityType)
                and all columns in the entry.EntityType are optional
                && tableMapping.Table.GetRowInternalForeignKeys(entry.EntityType).Any();
```

### Include provider and version information

EF Core version: 6.0.1
Database provider: Npgsql
Target framework: .NET 6
Operating system: Windows
IDE: Rider

**Comment by ajcvickers** [comment]
@AndriySvyryd @smitpatel Could be a duplicate/same root cause as #26712. Consider patching?

**Comment by AndriySvyryd** [comment]
@ajcvickers Could be

@taspeotis Does the warning only trigger when you replace an owned instance?

**Comment by taspeotis** [comment]
Thank you for the reply.

> Does the warning only trigger when you replace an owned instance?

I will investigate further and test to see. You are correct that some replacement does occur: the line of code that sets the address is:

```
sessionOfCare.Address = GetAddress(...);
```

And that parses an address and returns a new `Address` object or `null`. If there is already an address it's discarded.

**Comment by AndriySvyryd** [comment]
Ok, thank it's likely the same issue.
