### ISSUE TITLE
Use of AddDbContextFactory() can't be easily overridden by Unit Tests

### ISSUE THREAD

**Issue by derekgreer-swagup** [dotnet/efcore#27118]
The semantics of `ServiceCollection.Add()` and all variants is for the last service registration to override any previously registered types.  It should follow that all convenience extension methods _should_ follow this semantic behavior.  This is not the case with the `AddDbContextFactory()` extension method (and I'm guessing the `AddDbContext()` extension method as well).  This appears to be at least partially due to using `TryAdd()` on various types internally .  This is problematic when writing automated tests using TestServer and attempting to override the implementation to use a different provider.  One way to overcome this is to dig into the code to find all the service descriptors that are registered and then remove each one, but that sucks to have to do that:  

```C#
      var application = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.ConfigureServices(services =>
                {
                    var factoryDescriptor = services.FirstOrDefault(descriptor => descriptor.ServiceType == typeof(IDbContextFactory<WidgetDbContext>));
                    bool x = false;
                    
                    if(factoryDescriptor != null)
                        x = services.Remove(factoryDescriptor);
                    
                    var contextDescriptor = services.FirstOrDefault(descriptor => descriptor.ServiceType == typeof(WidgetDbContext));
                    
                    if(contextDescriptor != null)
                        x = services.Remove(contextDescriptor);
                    
                    var factorySourceDescriptor = services.FirstOrDefault(descriptor => descriptor.ServiceType == typeof(IDbContextFactorySource<WidgetDbContext>));
                    
                    if(factorySourceDescriptor != null)
                        x = services.Remove(factorySourceDescriptor);
                    
                    var dbContextDescriptor = services.FirstOrDefault(descriptor => descriptor.ServiceType == typeof(DbContextOptions<WidgetDbContext>));
                    
                    if(dbContextDescriptor != null)
                        x = services.Remove(dbContextDescriptor);
                    
                    
                    services.AddDbContextFactory<WidgetDbContext>(b =>
                    {
                        b.UseSqlite(SQLiteConnectionManager.Connection);
                    });

...
}
```

Please rethink this design as I would image most would expect any subsequent calls to these extension methods with different parameters to override any prior registrations that may occur.

EF Core version: 6.0.1
Database provider: N/A
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: N/A

**Comment by ajcvickers** [comment]
@derekgreer-swagup This is by-design so that customized registrations of these services are not clobbered by the EF calls.

**Comment by derekgreer-swagup** [comment]
Can you elaborate on this a bit?  What do you mean by "clobbered by the EF calls"?

Also, I would ask that you think about this from the perspective of a consumer of this API.  Someone is trying to drive out their design through TDD or even writing after the fact end-to-end tests.  They want to replace an SqlServer implementation with something that is more conducive to fast-ish tests which don't result in side-effects, so they want to use something like SQLite.  What is the advised approach to this and what is the experience of the developer taking this approach?  I spent several hours yesterday trying to figure out why my override of the registration wasn't behaving semantically like I assumed it should (see Principle of Least Astonishment) along with tracing through the registration code figuring out everything I needed to remove to make this possible.  That was a really sucky experience.

**Comment by ajcvickers** [comment]
@derekgreer-swagup For example, if an application registers `DbContextOptions<TContext>` as a singleton, and then calls `AddDbContext<TContext>`, EF should not replace that singleton registration with a scoped registration.

It's true, that an argument can also be made in the other direction, and this was discussed many years ago. However, going the other way now would be a significant breaking change. Since methods like `AddDbContext` are only sugar for more general service registrations, nothing prevents applications from doing their own registrations in whichever way they see fit.
