### ISSUE TITLE
EF Core InMemory Sequential Guid generation

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#27123]
.Net 6 / EF Core 6

I use EF Core 6 for SQL Server with Guid as primary keys.
When I add my entity to the context a sequential guid is generated , it's perfect.

Now I'm working on unit tests and I use an in memory context.
Sequential Guids are no more genrated and remains to default.

Is there a way to fix this problem?

Thanks.

**Comment by ErikEJ** [comment]
Inmemory is not a relational provider, and not a SQL Server emulator. To test this, use one of the many SQL Server editions.
