### ISSUE TITLE
NpgsqlTsVector.Matches() does not honour the TEXT SEARCH CONFIGURATION

### ISSUE THREAD

**Issue by kejdajar** [dotnet/efcore#27146]
## Description

The entity:
```
 public class Page
    {
        public long Id { get; set; }
        public string? Title { get; set; }
        public string? Content { get; set; }
        public NpgsqlTsVector? SearchVector { get; set; }
    }
```

The configuration:
```
modelBuilder.Entity<Page>()
               .HasGeneratedTsVectorColumn(
                   p => p.SearchVector!,
                   // 'mydict' is the name of the TEXT SEARCH CONFIGURATION
                   config: "mydict", 
                   p => new { p.Title, p.Content })
               .HasIndex(p => p.SearchVector)
               .HasMethod("GIN");
```

The query:
```
var results = await _appDbContext.Pages
            .Where(p => p.SearchVector!.Matches(query))
            .ToListAsync();
```

Actual SQL:
```
SELECT p."Id", p."Content", p."SearchVector", p."Title"
FROM "Pages" AS p
WHERE p."SearchVector" @@ plainto_tsquery(@__query_0)
```

Expected SQL:
```
SELECT p."Id", p."Content", p."SearchVector", p."Title"
FROM "Pages" AS p
WHERE p."SearchVector" @@ plainto_tsquery('mydict', @__query_0)
```

Example:
```
SELECT plainto_tsquery('zluty dzus') ---> 'zluti' & 'dzus'
SELECT plainto_tsquery('mydict', 'zluty dzus') ---> 'zluty' & 'dzus'
```
Note the 'y' vs 'i' character in the first word. The first query generated by EF Core apparently uses a default TEXT SEARCH CONFIGURATION, even though the 'mydict' configuration was explicitly configured to be used for the ``` NpgsqlTsVector? SearchVector ``` property.

The 'mydict' is a custom TEXT SEARCH CONFIGURATION, created explicitly using the following SQL.
```
CREATE EXTENSION unaccent;
CREATE TEXT SEARCH CONFIGURATION mydict ( COPY = simple );
ALTER TEXT SEARCH CONFIGURATION mydict ALTER MAPPING FOR hword, hword_part, word  WITH unaccent, simple;

# test the correct expected query
SELECT * FROM "Pages" p WHERE p."SearchVector" @@  plainto_tsquery('mydict', 'zluty dzus')

# test the query created by EF Core ('mydict' settings is ignored)
SELECT * FROM "Pages" p WHERE p."SearchVector" @@  plainto_tsquery('zluty dzus')
```

## How to reproduce
Use the attached demo project:
1. Update the connection string to postgres database in the Program.cs file.
2. Apply db migration using ```dotnet ef database update --project NpgsqlNet6 --startup-project NpgsqlNet6```
3. Run the app.
4. Use swagger to call the /seed endpoint to seed some data.
5. User swagger to call /search endpoint to invoke the fulltext searching.
6. Inspect the actual SQL.

## My environment
- Target framework: net6.0
- Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 6.0.2
- Operating system: Windows 11 Pro 64bit
- IDE: Microsoft Visual Studio Community 2022 (64-bit), version 17.0.3
[NpgsqlNet6.zip](https://github.com/dotnet/efcore/files/7833957/NpgsqlNet6.zip)

**Comment by roji** [comment]
This seems like an Npgsql-specific issue - could you please reopen this in https://github.com/npgsql/efcore.pg?

**Comment by kejdajar** [comment]
Thank you, reopened here https://github.com/npgsql/efcore.pg/issues/2210.
