### ISSUE TITLE
Include for multiple entities on the same sub-level

### ISSUE THREAD

**Issue by ygoe** [dotnet/efcore#27145]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.theninclude

You can see examples for blogs, posts and tags.

But what doesn't work is including two entities of a common sub-entity. Something like this:

* Blog
    * Post
        * Tag
        * Author

This fails:

```
context.Blogs
    .Include(blog => blog.Posts).ThenInclude(post => post.Tags)
    .ThenInclude(post => post.Author)
```

I have to drop the include thing and do a separate database query for the second sub-entity now to complete my task.

**Comment by roji** [comment]
You definitely don't need a separate query for this, you simply need to restart another Include chain

```c#
context.Blogs
    .Include(blog => blog.Posts).ThenInclude(post => post.Tags)
    .Include(blog => blog.Posts).ThenInclude(post => post.Author)
```

This is documented in the doc section on [including multiple levels](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#including-multiple-levels).
