### ISSUE TITLE
Join same table twice, INNER JOIN instead of LEFT JOIN

### ISSUE THREAD

**Issue by tovich37** [dotnet/efcore#27151]
Hello,

I have a problem when I want to join the same table twice (once with object property and once with collection property) (the code is attached, with SQL script), EF generate an INNER JOIN for the object property instead of a LEFT JOIN.
The code: [EfCoreMultipleRelations.zip](https://github.com/dotnet/efcore/files/7838839/EfCoreMultipleRelations.zip)

## The schema (I use SQL Server)
**Table EfTable1**
- Id (uniqueidentifier) NOT NULL
- ObjectNumber (decimal(10,0)) NULL

**Table EfTable1**
- ObjNum (decimal(10,0)) NOT NULL
- ParentNumber (decimal(10,0)) NULL

## The code
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<EfTable1>(entity =>
	{
		entity.ToTable("EfTable1");

		entity.HasKey(e => e.Id)
			.IsClustered(false);

		entity
			.HasOne(e => e.SingleObject)
			.WithOne()
			.HasForeignKey<EfTable1>(e => e.ObjectNumber);

		entity
			.HasMany(e => e.MultipleObjects)
			.WithOne()
			.HasPrincipalKey(e => e.ObjectNumber)
			.HasForeignKey(e => e.ParentNumber);
	});
}
```
```C#
// Use queryable to check the query
var queryable = _applicationDbContext
	.EfTable1
	.Include(e => e.SingleObject)
	.Include(e => e.MultipleObjects)
	.AsQueryable();

var result = await queryable
	.ToListAsync()
	.ConfigureAwait(false);
```

**Generated query (I need a LEFT JOIN instead of an INNER JOIN)**
```
SELECT [e].[Id], [e].[ObjectNumber], [e0].[ObjNum], [e0].[ParentNumber], [e1].[ObjNum], [e1].[ParentNumber]
FROM [EfTable1] AS [e]
INNER JOIN [EfTable2] AS [e0] ON [e].[ObjectNumber] = [e0].[ObjNum]
LEFT JOIN [EfTable2] AS [e1] ON [e].[ObjectNumber] = [e1].[ParentNumber]
ORDER BY [e].[Id], [e0].[ObjNum]
```
If I remove the collection property, EF generate a LEFT JOIN
```
SELECT [e].[Id], [e].[ObjectNumber], [e0].[ObjNum], [e0].[ParentNumber]
FROM [EfTable1] AS [e]
LEFT JOIN [EfTable2] AS [e0] ON [e].[ObjectNumber] = [e0].[ObjNum]
```
What I need:
```
SELECT [e].[Id], [e].[ObjectNumber], [e0].[ObjNum], [e0].[ParentNumber], [e1].[ObjNum], [e1].[ParentNumber]
FROM [EfTable1] AS [e]
LEFT JOIN [EfTable2] AS [e0] ON [e].[ObjectNumber] = [e0].[ObjNum]
LEFT JOIN [EfTable2] AS [e1] ON [e].[ObjectNumber] = [e1].[ParentNumber]
ORDER BY [e].[Id], [e0].[ObjNum]
```
### Provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.1
Target framework: .NET 6.0
Operating system: Windows 8.1
IDE: Visual Studio 2022 17.0.1

Thank you!

**Comment by ajcvickers** [comment]
@tovich37 `ObjectNumber` is used as the principal end of a relationship. This currently forces it to be a required property (non-nullable) in the EF model--see #4415. Because EF forces this to be non-nullable, it means that an inner join is used since the principal side of the relationship cannot be missing.

**Comment by tovich37** [comment]
@ajcvickers is there a workaround for my situation (to get two LEFT JOIN)?

**Comment by ajcvickers** [comment]
@tovich37 The fundamental problem here is that if the "ObjectNumber" column contains nulls, then it won't behave correctly as the principal end of the relationship, but if "ObjectNumber" column does not contain nulls, then the inner join is appropriate.

**Comment by tovich37** [comment]
@ajcvickers thank you for your answer, but this "problem" is a business use-case. Indeed, this information ("ObjectNumber") is not always known. And when this field is null, we still have to bring back this record (LEFT JOIN). How do you think we can still get this LEFT JOIN (workaround)?

**Comment by ajcvickers** [comment]
@tovich37 I don't think there is any way to make this work while the property is being used as the principal end of a relationship. This in of itself is likely to cause issues since EF doesn't support nulls in such a column--see #4415. However, you may get away with his depending on how the data is used. But because EF does not currently support modeling your database structure, the Include will also not generate queries matching your database structure. You may be able to bring back what you need using an explicit join, or by running multiple queries and having EF fix up the results in the change tracker.

**Comment by rbonomo** [comment]
Cant you do HasOne(...).WithMany(...).HasForeingKey(...).HasPrincipalKey(...) + unique index on principal key to get the desired left join and one-to-one relationship?

**Comment by ajcvickers** [comment]
@rbonomo If all that is needed is a unique index, then yes. In this case the column is acting as the principal end of a relationship, so it needs to be a key in the EF model.
