### ISSUE TITLE
ServiceProviderCache keeps initially created IServiceProvider indefinitely

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#27169]
The `ServiceProviderCache` uses instances of `IDbContextOptions` as keys for the internal `ConcurrentDictionary`.  A key of type `IDbContextOptions` contains, among other things, the extension `CoreOptionsExtension` which has an `_applicationServiceProvider`.

After creation and disposal of the first `DbContext` the `ServiceProviderCache` keeps the `IDbContextOptions` incl. the (disposed) `IServiceProvider`, which keeps all `IDisposable` instances in it. One of the disposables is the `DbContext` itself.

The result is that the reference `_applicationServiceProvider` prevents GC to reclaim the memory.

![image](https://user-images.githubusercontent.com/7135790/149024699-2671d124-7b01-4eed-b90a-dba2fcb5ae66.png)

### Repro

**Program.cs**
```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Extensions.DependencyInjection;

var rootServiceProvider = new ServiceCollection()
                          .AddDbContext<DemoDbContext>(builder =>
                                 builder.UseSqlServer("server=localhost;database=demo;integrated security=true"))
                          .BuildServiceProvider();

CreateAndDisposeContext(rootServiceProvider);

var cache = ServiceProviderCache.Instance;

static void CreateAndDisposeContext(IServiceProvider rootServiceProvider)
{
   using var scope = rootServiceProvider.CreateScope();

   scope.ServiceProvider.GetRequiredService<DemoDbContext>();
}


public class DemoDbContext : DbContext
{
   public DemoDbContext(DbContextOptions<DemoDbContext> options)
      : base(options)
   {
   }
}

```

**csproj file**

```xml
<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net6.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
   </ItemGroup>

</Project>
```

### Provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system: Windows 10 x64
IDE: Rider 2021.3.2

**Comment by ajcvickers** [comment]
@AndriySvyryd This looks like a consequence of no longer just using the hash. I now remember that this was why we did it the hash way in the first place!
