### ISSUE TITLE
No Intellisense on beta7-12274

### ISSUE THREAD

**Issue by NoralK** [dotnet/efcore#2716]
Using VS-Code and when using beta7-12274 there is no Intellisense.  There is Intellisense for beta5.

**Comment by rowanmiller** [comment]
Possibly related to https://github.com/aspnet/Announcements/issues/44

Are you only seeing this issue with EF APIs? Or is IntelliSense missing for other libraries too?

**Comment by NoralK** [comment]
I do not believe so - I see the initial Intellisense as I type but as soon as I hit the "." and any "." after there is no Intellisense anywhere until I hit ctrl-space.  I am thinking that this might be a Visual Studio Code issue.  What are your thoughts?  I am thinking close the ticket.

BTW - I am running beta7-12302 and the same is happening.

**Comment by rowanmiller** [comment]
Hey,

Yes I agree, this doesn't appear to be an EF issue. We suspect it is a result of the change discussed in https://github.com/aspnet/Announcements/issues/44. I guess VS Code probably needs to react to this, so opening an issue in [their tracker](https://code.visualstudio.com/Issues/List) is probably the way to go.

~Rowan
