### ISSUE TITLE
Select query  with custom projections methods

### ISSUE THREAD

**Issue by dkezri** [dotnet/efcore#27172]
Hi

i have  a select  query with a custom projection method ( ToTableMode() )  in dotnet 5    and was wondering if it will be executed in memory locally instead of database?  I don't see any kind of Error or Warning logs for the query will be executed locally :

```C#
await _context.Tables
                .Include(x => x.Rows)
                .ThenInclude(r => r.RowAudits)
                .Where(x => x.Id == id)
                .Select(t => ToTableModel(t, true))
                .FirstOrDefaultAsync();


 private static TableModel ToTableModel(Table table, bool includeRows = true)
        {
            return new TableModel
            {
                Id = table.Id,
                Title = table.Title,
                Description = table.Description,
                HasDetails = table.HasDetails,
                SortOrder = table.SortOrder,
                Approved = table.Approved,
                ValidationId = table.ValidationId,
                LastSignedAt = table.LastSignedAt,
                LastSignedBy = table.LastSignedBy,
                Rows = includeRows ? table.Rows.Select(r => ToRowModel(r)).ToList() : null
            };
        }
```

Thanks

**Comment by roji** [comment]
@dkezri anything in the top-most projection (last Select) which EF Core can't translate to SQL is indeed evaluated locally in-memory, without any warnings; that should be the case with ToTableModel above. This is documented [here](https://docs.microsoft.com/en-us/ef/core/querying/client-eval#client-evaluation-in-the-top-level-projection).

**Comment by dkezri** [comment]
thanks @roji
