### ISSUE TITLE
VB.net Support for Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by BigBasti123** [dotnet/efcore#27179]
**Problem:**
I want to Update a WindowsForms App written in VB.net from .net Framework 4.8 to new .NET 5 (and maybe 6 in the future). The assembly uses EF 6.4.4 and i need to update it to EFCore, because the database provider (Oracle) needs to be updated to the Core Version together with EF. I changed all the code and then i realizied when trying a first migration with EF Core, that the package-manager console tool isn't working with VB.net any more. The following message occurs, when trying:

add-migration IntialDB

The project language 'VB' isn't supported by the built-in IModelCodeGenerator service. You can try looking for an additional NuGet package, which supports this language;
moving your DbContext type to a C# class library referenced by this project; or manually implementing and registering the design-time service for programming language.
 
In EF 6.4.4 it works just fine.

**Solution:**
Please get back VB.net Support for the package-manager-console tool to handle the migrations in EFCore, otherwise the users cannot port their projects from .net Framework to .NET 5 and newer.

**Comment by ErikEJ** [comment]
You should be able to use this: https://github.com/efcore/EFCore.VisualBasic

**Comment by ajcvickers** [comment]
@BigBasti123 EF Core is written in an extensible manner so that support for additional languages can be added externally. There are currently good external packages for F# and VB--as referenced by @ErikEJ above.
