### ISSUE TITLE
Raise exceptions for unsupported property setup/metadata?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#2717]
I'm working on sequence support for Npgsql, and I'm wondering about what to do with properties that are impossible. I'm referring, for example, to identity columns that aren't numeric, to properties that have both DefaultValue and DefaultValueSql, or, in the PostgreSQL case, to computed columns in general which aren't really supported (although there may be alternate ways to implement this).

The current approach I see in the code is to silently ignore these invalid or unsupported "specs". Wouldn't it be better to raise exceptions for these?

**Comment by ajcvickers** [comment]
@roji I think there are a couple of things we can do here. In some cases it may be fine to just throw in Migrations. For example, if it might be possible for a database to be setup with triggers, etc. to do what is asked, but there is no way to create such a database from Migrations. In cases where the model is always going to invalid then look into implementing an IModelValidator, This seems to be the place where most model validation is gravitating, and is something that providers can implement. @smitpatel can provide more info if needed.
