### ISSUE TITLE
AsSplitQuery does not keep consistent sort order with Included resources, Resulting in mismatch when a LIMIT is applied

### ISSUE THREAD

**Issue by TheGreatestEvan** [dotnet/efcore#27188]
When building the following query, the expected result is to get a subset of records from "audit" and the associated entries in "Actors".   However, the SQL that is executed places the key value in the ORDER BY clause of the main query, but only in the ORDER BY of the outermost query on the secondary SQL statement.  The result is a different list of entries from "audit" which do not all match up with the entries returned from "Actors"
```C#
            var queryExample = (from audit in _context.AuditEvents.AsNoTracking()
                                select audit)
                .Include(a => a.Actors)
                         .AsSplitQuery();

            queryExample = queryExample.Skip(150).Take(50);
            var queryExampleResults = queryExample.ToList();
```
The SQL Output looks like this:
```sql
SELECT a.id, a.action, a.correlation_id, a.description, a.outcome, a.time_stamp
FROM audit_events AS a
ORDER BY a.id
LIMIT 50 OFFSET 150

SELECT a0.id, a0.display_name, a0.identifiers, a0.audit_id, t.id
FROM (
    SELECT a.id
    FROM audit_events AS a
    LIMIT 50 OFFSET 150
) AS t
INNER JOIN actors AS a0 ON t.id = a0.audit_id
ORDER BY t.id
```
Notice how the LIMIT/OFFSET is applied to the subquery portion of the split query, however the "ORDER BY id" is only on the parent query.  This is causing the Actors information not to populate on most of my records in the returned queryResults.

**Comment by TheGreatestEvan** [comment]
I did find the following issue, which seems to be very similar, if not a duplicate.  
https://github.com/dotnet/efcore/issues/25260

If I'm reading that correctly, it's just expected that I would be adding a unique field to order by prior to using skip/take for pagination.  My uncertainty lies in the fact that I did not manually add sorting on the "id" field that causes the primary query to return different results than the secondary sub-query.

**Comment by ajcvickers** [comment]
@TheGreatestEvan This is by-design. Using Skip/Take requires an explicit ordering--you should be seeing a warning in the logs from the query above because there is no explicit ordering. EF Core adds its own ordering for splitting the query, but this does not remove the need for an explicit ordering when using Skip/Take.
