### ISSUE TITLE
Issue with Scaffold-DbContext

### ISSUE THREAD

**Issue by kiranknz** [dotnet/efcore#27180]
## File a bug

When running Scaffold-DbContext on a SQL Server database with a table named Staff, the models created have a named staff.cs (ie. in lower case) and the entity name is also in lower case staff.

However, if I change the name of the table to say Astaff , the class name is Astaff ie. first letter is capitalise, Using the option UseDatabaseNames makes no difference; a table named Staff will always generate code with staff in lower case.

So strange!!

**Comment by kiranknz** [comment]
If I rename the table to say Staffs, then the class name & entity name is fine ie Staff. So only if the table name is Staff that class name & entity name is in lower case staff

**Comment by ajcvickers** [comment]
@kiranknz Can you post the SQL schema that results in this behavior?

**Comment by kiranknz** [comment]
Certainly. In order to recreate this issue, I created a new database in SQL Server (v15.0.2080.9) and called it BooksDB. Created a table called Staff as follows:

USE [BooksDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Staff](
	[StaffID] [int] IDENTITY(1,1) NOT NULL,
	[StaffName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Staff] PRIMARY KEY CLUSTERED 
(
	[StaffID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

Next, I create a new project using the ASP.Net Core Web API template using VS2022. Install the 2packages Microsoft.EntityFrameworkCore.SqlServer & Microsoft.EntityFrameworkCore.Tools both v6.0.1.

Then I run the command from the Console Manager: 
Scaffold-DbContext "Server=.;Database=BooksDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -DataAnnotations -UseDatabaseNames -Force

In the Models forlder BooksDBContext is created & staff.cs in lower case with code as follows

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BooksDBAPI.Models
{
    [Table("Staff")]
    public partial class staff
    {
        [Key]
        public int StaffID { get; set; }
        [StringLength(50)]
        public string StaffName { get; set; } = null!;
    }
}

Hope the above helps recreate the issue

**Comment by kiranknz** [comment]
BooksDB	Latin1_General_CI_AS

**Comment by kiranknz** [comment]
I used collation SQL_Latin1_General_CP1_CI_AS. Still the same issue.

This is so strange!!

**Comment by ajcvickers** [comment]
@kiranknz Can you try reverse engineering into a barebones console app (instead of your main project/solution) and see if this still reproduces? If it does, then please attach that project. If it does not, then its possible that something in your main project is changing design-time services in a way that causes this to happen.

**Comment by kiranknz** [comment]
Thanks Arthur.

Here's a link to the console project: https://github.com/kiranknz/BooksDBConsoleApp

The command used in the Package Manager Console to reverse engineer is: 
Scaffold-DbContext "Server=.;Database=BooksDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -DataAnnotations -UseDatabaseNames -Force

Hope this helps with your diagnosis.

**Comment by ErikEJ** [comment]
What collation is the database using when created?, not clear from the script:

    WITH CATALOG_COLLATION = DATABASE_DEFAULT

**Comment by kiranknz** [comment]
The default is Latin1_General_CI_AS.

As mentioned earlier, I changed the collation of the database to SQL_Latin1_General_CP1_CI_AS but this made no difference.

I have now tried this on 2 of my development PCs but same issue.

I'm confused why this happens for the Staff table. None of the other tables are affected. Maybe there is something in the scaffolding code that uses Staff but it seems unlikely as why would such a name be used in EF code.

If I change the table name to say Staffs, then the class is now Staff. But Staff created staff (in lower case).

Even more confusing is that you can't generate at your end.

**Comment by ErikEJ** [comment]
What locale is your PC?

**Comment by ajcvickers** [comment]
@kiranknz What happens if you add the `-NoPluralize` flag to your `Scaffold-DbContext` command?

**Comment by kiranknz** [comment]
System locale for Windows 10 PC is English (New Zealand)

**Comment by kiranknz** [comment]
Haha, I tried -NoPluralize as suggested. The Staff table is now created as Staff.cs and class name fine too.

But without -NoPluralize, the Staff table generated as staff.cs and class name staff (ie. lower case).

Any idea why this happens? Haven't come across any other table names that are impact like this.

**Comment by kiranknz** [comment]
I'm guessing that's something to do with not being able to have a plural for Staff.

Noted that if I changed the table name to Staffs, then the plural in the DbSet is Staffs and the name is fine (Staff.cs & Staff as class name) without -NoPluralize

**Comment by ErikEJ** [comment]
Finally remembered!

https://github.com/Humanizr/Humanizer/commit/daa87811fcf15a0556c539ed144cb4ccd9cc99df#diff-7f70e79d5a852f8e407071f64f25b3fc778d5e924ab9f126327120c434a559caL103 

https://github.com/Humanizr/Humanizer/issues/1030 

Potential fix could be to reference a newer version of Humanizer.Core

`<PackageReference Include="Humanizer.Core" Version="2.13.14" />`

**Comment by ajcvickers** [comment]
Note from triage: EF will pick up the new version of Humanizer for 7.0.

**Comment by kiranknz** [comment]
Erik & Arthur, much appreciated both your assistance on this.
