### ISSUE TITLE
Null data in DB required data in UI/Service

### ISSUE THREAD

**Issue by chaseaucoin** [dotnet/efcore#27186]
## Ask a question

Context Setting:
We have a lot of database first models and contexts (20+ contexts 300+ models) for our many years old database. Much of that data historically could be null but in recent years have become required for new entries. Historic entries that are null are not a problem, but we just don't want new items null. 

Question:
In trying to migrate to EF6 there has been a big problem with this scenario in that is seems like it is no longer supported. We cannot have a required tag and nullable data. How can we configure that to make sure it works without rewriting 300+ models?

Example situations

```c#
public class SomeModel
{
   [Key]
   [Required]
   public int? ID { get; set; } //Will be null when class is created and populated from database

   [Required]
   public string SomeBusinessValue { get; set; } //nullable when inbound from the database not nullable from service via validation.
}
```

**Comment by ajcvickers** [comment]
@chaseaucoin If you want a database column to be nullable, but keep the `[Required]` attribute for validation, then you can override the EF model configuration for that property without removing the attribute. For example:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<SomeModel>().Property(e => e.SomeBusinessValue).IsRequired(false);
}
```

However, PK properties must be non-null, so if the `ID` column in the example above is null, then this will always fail with EF. This is true for EF6 as well as EF Core, and every other version of EF.
