### ISSUE TITLE
The specified deps.json [C:\Users\pwens\source\repos\WaterWithdrawl-3\WaterWithdrawal\Client\bin\Debug\net6.0\WaterWithdrawal.Client.deps.json] does not exist

### ISSUE THREAD

**Issue by patrickwensel** [dotnet/efcore#27194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had to rename the solution file, project files and namespaces due to a spelling error.  Now, I am getting this error when adding a migration or updating a database in the paackage manager console.  BTW, it does work in the CLI.

DO NOT CLOSE THIS TICKET as a duplicate.  This is .Net 6 and the other tickets are related to upgrades (with no solutions!!) not related to changing names.

### Steps To Reproduce

1. rename the folders, solution file, project files. 
2. Open the solution file
3. remove old projects
4. add existing projects with new name.
5. add a migration

### .NET Version

6.0

### Anything else?

![image](https://user-images.githubusercontent.com/3652914/149617882-a792df73-b035-4d77-a194-b8a9cbe56767.png)

**Comment by ajcvickers** [comment]
@patrickwensel This is a long-standing problem with the project system. It is not specific to EF Core or other application frameworks. The project system team has never been able to solve it, and there is nothing that can be done at the ASP.NET or EF level. Sometimes fully cleaning (i.e. deleting the "obj", "bin" and any other intermediate files/folders) and doing a full rebuild can resolve the problem.

**Comment by patrickwensel** [comment]
Thanks!  Now others at least know
________________________________

**Comment by RodolfoRoman** [comment]
If you are working in Blazor, you must set your DataAccess solution as the startup project

**Comment by AceSyntax** [comment]
Thank you! Yes, setting the EF Core project as the startup worked for me!

**Comment by SbongaMabaso** [comment]
Changing your default project works perfectly. [ref] (https://stackoverflow.com/questions/59265606/your-target-project-x-doesnt-match-your-migrations-assembly-xx-either-chan)

**Comment by joshodey** [comment]
I had this issue, if you are using VS, just change the active project to the Project that has the context, then make sure the Default Project where the add-migration would be run should be where the context is. By active project i mean start-up project, (at least where your design is installed...

**Comment by GiovanniCarrero** [comment]
> Si está trabajando en Blazor, debe configurar su solución DataAccess como proyecto de inicio

Muchas gracias me funciono, saludos

**Comment by codercodingthecode** [comment]
Incredibly, that is not an official solution from MS regarding this issue.
It is not strictly for VS or Windows.

I'm on MacOS with a MAUI project and have the same issue.
Frustrating.

**Comment by MacKey-255** [comment]
Any news?
