### ISSUE TITLE
Is possible to get the Global Filter attached to specific Entity?

### ISSUE THREAD

**Issue by Deivisson** [dotnet/efcore#27207]
Hi,

I'd like to know if is possible to get the global filter that was set to an Entity through HasQueryFilter?

e.g: 
```C#
     // setting QueryFilter
     modelBuilder.Entity<MyEntity>()
        .ToTable("my_table")
        .HasQueryFilter(q => q.TenantId == _idTenant);
```

I need, programmatically, to know if MyEntity has the global query filter by tenantId, to make a unit test coverage.

Ps.: I need this on tests environment that runs on in-memory database

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: 5.0

**Comment by ajcvickers** [comment]
@Deivisson You can get it from the model. For example:

```C#
var filter = context.Model.FindEntityType(typeof(MyEntity)).GetQueryFilter();
```

**Comment by Deivisson** [comment]
@ajcvickers, Perfect! tks
