### ISSUE TITLE
Seeding one-to-many relationships

### ISSUE THREAD

**Issue by darthhiggy** [dotnet/efcore#27208]
So, I've run into this problem multiple times on different projects sense updating and working in EF core 6. I've looked through multiple sources and tried several work arounds but nothing is working for me. 

I have two classes, pies and categories. Pie has a category and category can reference multiple pies. 

doing the following gives me the following error. 

 ```C#
modelBuilder.Entity<Category>().HasData(new Category { CategoryId = 1, CategoryName = "Fruit pies" });
modelBuilder.Entity<Pie>().HasData(new Pie
                {
                    PieId = 1,
                    CategoryId = 1,
                    Name = "Apple Pie",
                    ...
            });
```
The seed entity for entity type 'Pie' with the key value 'PieId:1' cannot be added because it has the navigation 'Category' set. To seed relationships, add the entity seed to 'Pie' and specify the foreign key values {'CategoryId'}.

I even tried explicitly defining the relationship like so: 
```C#
modelBuilder.Entity<Pie>(e =>
            {
                e.HasOne(c => c.Category).WithMany(p => p.Pies).HasForeignKey("CategoryId");
            });
```

Now, when I try it as an owned type i get the following using the following modelbuilder 

```C#
modelBuilder.Entity<Pie>(p =>
            {
                p.HasData(new Pie
                {
                    PieId = 1,
                    CategoryId = 1,
                    ...
                });

                p.OwnsOne(c => c.Category)
                    .HasData(new Category { CategoryId = 1, CategoryName = "Fruit pies"});
            });
```

The seed entity for entity type 'Category' cannot be added because no value was provided for the required property 'PieId'.

I understand that there has to be something i'm missing here but i don't know what. It acts like it is trying to create a shadow property for PieId but I don't want this. I want the entity pie to reference the entity category. I tried taking out the navigation property in Category but that didn't work either.

**Comment by ajcvickers** [comment]
@darthhiggy I'm not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>().HasData(new Category { CategoryId = 1, CategoryName = "Fruit pies" });
        modelBuilder.Entity<Pie>().HasData(new Pie
        {
            PieId = 1,
            CategoryId = 1,
            Name = "Apple Pie",
        });
    }
}

public class Pie
{
    public int PieId { get; set; }
    public string Name { get; set; }

    public int CategoryId { get; set; }
    public Category Category { get; set; }
}

public class Category
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }

    public ICollection<Pie> Pies { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var pies = context.Set<Pie>().Include(e => e.Category).ToList();
        }
    }
}
```
