### ISSUE TITLE
Migrations containing strings with many line-breaks will truncate strings silently

### ISSUE THREAD

**Issue by btastic** [dotnet/efcore#27206]
## Description
This was originally filed in #24112 and got fixed in #24944.

We first found out about this issue when inserting a large legal text into our database, which contains a lot of line breaks. EF Core generates a large script which uses `CONCAT()` with up to 254 arguments, before starting a new `CONCAT()`. (\r and \n get converted to nchar(10) and nchar(13) and will be concatenated with the rest of the text)

As in #24112 described, there is an issue with `CONCAT` if you don't CAST the first parameter as `nvarchar(max)` the sql server will assume the 4000 byte limit.

This was fixed with #24944 by adding a `CAST` to the first parameter of `CONCAT`. However, subsequent `CONCAT`s will not use a `CAST`. This will lead to silently truncated strings in the database.

I already had a look at the code and decided to fix it and contribute to this project. 

https://github.com/dotnet/efcore/blob/652333575b6a7147e2652627365c591a4f303234/src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs#L312-L317

It seems that resetting the `castApplied` flag to false inside the if fixes the issue.

As per the the contribution guidelines, I am requesting permission to file a PR.

### Include provider and version information

EF Core version: latest (main branch)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by dnxit** [comment]
I've faced the same issue while importing html templates via seed, it was truncating the template after a lot of investigation came to know its because of the CAST(0 AS bit), NULL, NULL, CONCAT(CAST(N'<!DOCTYPE html PUBLIC..........
It was working ok in .Net Core 3.1 and 5.0 now we upgraded to .Net 6 and started facing this issue.

**Comment by AndriySvyryd** [comment]
@dnxit Can you share a small repro project so we can ensure that you are hitting the same issue?

**Comment by dnxit** [comment]
@AndriySvyryd yeah sure, I've created a sample. just set the connection string and run the sample, by the way I've added generated query from SQL profiler as well.
https://github.com/dnxit/StringTruncationSampleEF6

**Comment by kAleksei** [comment]
Hey, can we also add this fix for 6.0.x ?
