### ISSUE TITLE
Consoles when request prints DB Commands

### ISSUE THREAD

**Issue by Siumauricio** [dotnet/efcore#27212]
## Why when I made a request all commands print in the console?

###Printing this commands

I'm using Ngpsql and when I made a request all the request or commands prints in the console.
For example i made a request to this API
![image](https://user-images.githubusercontent.com/47042324/150071026-dd25d2e4-afd5-464c-a4d6-09a6b7269fc0.png)

and when i made a request appear this in console.
![image](https://user-images.githubusercontent.com/47042324/150071087-b80ab946-941a-40fd-8c84-1b1b74c40371.png)

### Include provider and version information

EF Core version: this all my packages
![image](https://user-images.githubusercontent.com/47042324/150071392-2ef7b844-cec4-4b99-857d-781c650fdf97.png)

Database provider: (Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (.NET 6.0)
Operating system: Windows
IDE: (Visual Studio 2022 and Visual Studio Code)

**Comment by roji** [comment]
This is by-design: EF Core logs SQL commands and other information at the "Information" log level, this is typically configured in your appsettings.json file.

**Comment by Siumauricio** [comment]
How can I hide that information? I tried deleting the information in appsettings.json and appsettings.Development.json but none worked

![image](https://user-images.githubusercontent.com/47042324/150232820-bbb342eb-d01c-4ca0-80a0-3ef4ecd8d5ef.png)

**Comment by Siumauricio** [comment]
How can I hide that information? I tried deleting the information in appsettings.json and appsettings.Development.json but none worked
![image](https://user-images.githubusercontent.com/47042324/150233000-2c543b7c-7981-4333-a9bf-ef41943ae5bb.png)

**Comment by Siumauricio** [comment]
Thanks !!
