### ISSUE TITLE
Apply FirstOrDefault() before Select() in Entity Framework

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#27211]
I have the following Entity Framework query against SQL Server. It produces the correct results.

```cs
var result = await query
    .Select(r => new RailcarSearchResultDto()
    {
        Id = r.Id,
        RailcarNumber = r.RailcarNumber,
        FleetId = r.FleetId,
        Fleet = (r.FleetId != null) ? r.Fleet.Name : null,
        Ownership = r.Ownership,
        LastClm = DbContext.CarLocationMessages
            .Where(clm => clm.RailcarNumber == r.RailcarNumber && clm.CompanyCode == companyCode)
            .OrderByDescending(clm => clm.SightingDate)
            .Select(clm => CarLocationMessage.ToShortString(clm.City, clm.State, clm.SightingDate, clm.SightingCode))
            .FirstOrDefault()
        })
        .ToListAsync()
    };
```

First thing I want to say is that it's amazing this works. The assignment to `LastClm` involves a C# method in the `Select()` clause. It seems Entity Framework has got much smarter about being able to retrieve the data needed and then apply C# code as needed. Kudos to the team if this is the case.

That said, it looks like I have a performance issue here. The data is downloaded at the point before the call to `CarLocationMessage.ToShortString()`. That means, it's going to bring down all matching rows. And only apply `FirstOrDefault()` after `CarLocationMessage.ToShortString()` has been called. Obviously, this would be a performance issue if the number of rows gets very large.

I know I can bring the data down without the C# method into an anonymous type, and then assign it to my final object type, calling any C# code then as needed. But to me this query is totally cool. Could there be a way to tell Entity Framework I want to apply the `FirstOrDefault()` before calling my C# method and before the data is downloaded?

FWIW, here's the SQL generated for this query.

```sql
SELECT [t].[Id], [t].[RailcarNumber], [t].[FleetId], CASE
    WHEN [t].[FleetId] IS NOT NULL THEN [f0].[Name]
    ELSE NULL
END, [t].[Ownership], [t0].[City], [t0].[State], [t0].[SightingDate], [t0].[SightingCode], [t0].[c]
FROM (
    SELECT [f].[Id], [f].[FleetId], [f].[Ownership], [f].[RailcarNumber]
    FROM [FleetRailcars] AS [f]
    WHERE ([f].[CompanyId] = @__companyCode_0) AND ([f].[CarType] = @__Trim_1)
    ORDER BY (SELECT 1)
    OFFSET @__p_2 ROWS FETCH NEXT @__p_3 ROWS ONLY
) AS [t]
LEFT JOIN [Fleets] AS [f0] ON [t].[FleetId] = [f0].[Id]
LEFT JOIN (
    SELECT [t1].[City], [t1].[State], [t1].[SightingDate], [t1].[SightingCode], [t1].[c], [t1].[RailcarNumber]
    FROM (
        SELECT [c].[City], [c].[State], [c].[SightingDate], [c].[SightingCode], 1 AS [c], [c].[RailcarNumber], ROW_NUMBER() OVER(PARTITION BY [c].[RailcarNumber] ORDER BY [c].[SightingDate] DESC) AS [row]
        FROM [CarLocationMessages] AS [c]
        WHERE [c].[CompanyCode] = @__companyCode_0
    ) AS [t1]
    WHERE [t1].[row] <= 1
) AS [t0] ON [t].[RailcarNumber] = [t0].[RailcarNumber]
```

**Comment by smitpatel** [comment]
> WHERE [t1].[row] <= 1

It only downloads one row worth of data actually. i.e. `FirstOrDefault` is actually applied to the database query before applying `Select` to call into client method.

**Comment by SoftCircuits** [comment]
@smitpatel D'oh! I missed that.

That is absolutely awesome then. My original query should work fine then. I don't know if it's just me but EF seems like it's gotten *so* much better.

Thanks!
