### ISSUE TITLE
Stop automatically deleting orphans for optional relationships with cascade delete configured

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#27217]
See #27174

Cascade delete is typically used with required relationships, where a dependent cannot exist in the database without a principal. In this case, delete orphans behavior makes sense. However, if cascade delete is used with optional relationships, then the dependent can still exist without the principal, which means it probably doesn't make sense to delete orphans automatically.

**Comment by stevendarby** [comment]
Hi @ajcvickers I've tried reading this over a few times and feel I'm missing something. Are you saying that if the relationship is optional and cascade delete has been configured, it will no longer cascade the delete? Why would it not respect the delete behaviour configured for the relationship? Sorry if I've misunderstood.

**Comment by archer87pl** [comment]
Please take a look at issue https://github.com/dotnet/efcore/issues/33610
That change is causing strange behaviour for simple updates and there should be an option to change default behaviour like it was in EF Core 6.0
