### ISSUE TITLE
Correct SqliteType inference from string, DateOnly, TimeOnly

### ISSUE THREAD

**Issue by xinbingyiran** [dotnet/efcore#27213]
Microsoft.Data.Sqlite 6.0.1
TargetFramework net6.0-windows

当我创建一个字符串类型的SqliteParameter时，我查询它的类型，得到的类型信息是 “SqliteType.Integer”

```C#

var p = new Microsoft.Data.Sqlite.SqliteParameter("Name","123");

```

后来我在源码中定位到了以下位置，这就有点不合适了吧

https://github.com/dotnet/efcore/blob/8144d50ec0d15b87c35a9a3a425b1faadafb87f1/src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs#L240-L263

**Comment by roji** [comment]
Google Translate:

```
When I create a SqliteParameter of type string, I query its type, and the type info I get is "SqliteType.Integer"
...
Later, I located the following location in the source code, which is a bit inappropriate.
```

/cc @bricelam
