### ISSUE TITLE
dbContext.Database.GetMigrations() retuns an empty list

### ISSUE THREAD

**Issue by sommmen** [dotnet/efcore#27215]
Hiya,

For some reason `dbContext.Database.GetMigrations()` returns an empty list.
Could it be due to the fact that i use the base `DbContext` instead of the derived class? (that should be no problem afaik, but for some reason this doesnt work.

``` csharp
rivate async Task WarmupDbContext(DbContext dbContext, CancellationToken cancellationToken)
    {
        if (!await dbContext.Database.CanConnectAsync(cancellationToken))
            _logger.LogError("Cannot connect to {DbContextName} with {ConnectionString}", dbContext.GetType().Name, dbContext.Database.GetConnectionString());
        else
        {
            _logger.LogDebug("Connected successfully to {DbContextName} with {ConnectionString}", dbContext.GetType().Name, dbContext.Database.GetConnectionString());

           // Returns an empty list
            var t = (await dbContext.Database.GetPendingMigrationsAsync(cancellationToken)).ToList();

           // Returns an empty list
            var allMigrations = dbContext.Database.GetMigrations()
                .ToList();

           // Returns actual values (about 120)
            var appliedMigrations = (await dbContext.Database.GetAppliedMigrationsAsync(cancellationToken))
                .ToList();

            var pendingMigrations = allMigrations
                .Except(appliedMigrations)
                .ToList();

            var extraMigrations = appliedMigrations
                .Except(allMigrations)
                .ToList();

            if (pendingMigrations.Any())
            {
                foreach (var pendingMigration in pendingMigrations)
                {
                    _logger.LogCritical("{DbContextName} has pending migration: {PendingMigration}", dbContext.GetType().Name, pendingMigration);
                }
            }

            if (extraMigrations.Any())
            {
                foreach (var extraMigration in extraMigrations)
                {
                    _logger.LogCritical("{DbContextName} has extra migration: {ExtraMigration}", dbContext.GetType().Name, extraMigration);
                }
            }
        }
```

We use the tools to generate an sql script so we don't migrate automatically.

The dbContext is configured like so:

``` csharp
options.UseSqlServer(_defaultConnectionString, b =>
{
    // NOTE migrations are located in the current assembly, so we make that known to EF here.
    b.MigrationsAssembly(typeof(InitialStockDb).Assembly.GetName().FullName);
});
```

The projects are setup like this:

```
- DAL.csproj
  - DbContextWarmupHostedService
    - WarmupDbContext(...)
- ExecutableProject.csproj
  - DAL (namespace/folder)
    - Migrations (namespace/folder)
      - All migrations are here. 
- BackgroundServiceProject.csproj
  - Calling DbContextWarmupHostedService.WarmupDbContext(...) here.
```

Calling this from my backgroundservice i would assume an empty list since the migrations assembly can't be loaded.
This is not true for `ExecutableProject` however. I'd expect this to return values.

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows
IDE: Visual Studio 2022

**Comment by sommmen** [comment]
As i expected - this looks like its because the migration assembly is not loaded. 
Feel like i could use an exception when its missing but this is not an issue and by design so im closing this.

**Comment by br3nt** [comment]
> As i expected - this looks like its because the migration assembly is not loaded.
> Feel like i could use an exception when its missing but this is not an issue and by design so im closing this.

It would be super helpful if you provided an example or a link of how you got this to work.  I'm getting this problem from my text project.  The assembly is definitely loaded as I am accessing many classes and functionality from the assembly containing my migrations.

I don't understand at all how my test project is able to migrate the database, but then later dbContext.Database.GetMigrations() in the same test project returns empty.

And yes, an exception message with a useful/helpful message would be ideal.

**Comment by benjamincburns** [comment]
> It would be super helpful if you provided an example or a link of how you got this to work.

![image](https://github.com/dotnet/efcore/assets/803016/577fdbc7-55ea-46b8-9edb-1742ae0e01fd)

**Comment by sommmen** [comment]
My case was a simple error of my own, if something is not work for you i'd suggest opening a new issue with a minimal reproducible sample.

**Comment by ngochivinh** [comment]
@intelli-joe Thanks you!
