### ISSUE TITLE
Collection Navigation Property is not Loading 

### ISSUE THREAD

**Issue by JohnFasc** [dotnet/efcore#27226]
I have the problem, that my navigation property "PaymetnConditions" is always empty. I tried different solutions I also tried to solve the problem with the moduleBuilder but nothing seems to work. 

Probably it has something to do with the table prefix we set on startup in the context class.

`foreach (IMutableEntityType entity in modelBuilder.Model.GetEntityTypes())
            {                    
                entity.SetTableName(TablePrefix + "_" + entity.GetTableName());                                              
            }  `

    [Table("Receipt")]
    public class ReceiptEntity : ReportEntity
    {
        [Column(TypeName = "nvarchar(50)")]
        public List<PositionEntity> Positions { get; set; }
        public CustomerEntity Customer { get; set; }
        public List<AddressEntity> Addresses { get; set; }
        public string ExternalSystemId { get; set; }
        public string ExternalSystemDescription { get; set; }
        public string ReceiptNumber { get; set; }
        public Guid? ClerkId { get; set; }
        public Guid? ProjectManagerId { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string DocumentGuid { get; set; }
        public string ObjectType { get; set; }
        public string ObjectRef { get; set; }
        public DateTime ReceiptDate { get; set; }
        public DateTime? DocumentDate { get; set; }
        public DateTime? OrderDate { get; set; }
        public Guid? CanceledReceiptGuid { get; set; }
        public Guid? FromReceiptGuid { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public string DeliveryType { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public ReceiptTypeEnum ReceiptType { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public ReceiptStateEnum ReceiptState { get; set; }
        public bool Paid { get; set; }
        public string Period { get; set; }
        
        public List<PaymentConditionEntity> PaymetnConditions { get; set; }
    }

    [Table("PaymentCondition")]
    public class PaymentConditionEntity :BaseEntity
    {
        public double Days { get; set; }
        public decimal Value { get; set; }

        [Column(TypeName = "nvarchar(50)")]
        public PaymentConditionTypeEnum PaymentConditionType { get; set; }

        [Column(TypeName = "nvarchar(50)")]
        public PaymentConditionStateEnum PaymentConditionState { get; set; }

        [ForeignKey("ReceiptGuid")]
        public ReceiptEntity Receipt { get; set; }
        public Guid ReceiptGuid { get; set; }
    }

modelBuilder.Entity<ReceiptEntity>()
                .HasMany(nameof(ReceiptEntity.PaymetnConditions))
                .WithOne();

The call for getting the data from the context

context.Receipts
                .Include(receipt => receipt.PaymetnConditions)
                .Where(receipt => receipt.ReceiptState != ReceiptStateEnum.Deleted)
                .Where(receipt => receipt.Paid == false)
                .Where(receipt => receipt.ReceiptType == ReceiptTypeEnum.Deposit || 
                       receipt.ReceiptType == ReceiptTypeEnum.PartialInvoice || 
                       receipt.ReceiptType == ReceiptTypeEnum.Invoice ||
                       receipt.ReceiptType == ReceiptTypeEnum.FinalInvoice)
                .Where(receipt => receipt.ReceiptState == ReceiptStateEnum.Locked).ToList();

**Comment by roji** [comment]
@JohnFasc please submit a minimal, runnable code sample - the above doesn't provide us enough to investigate. Assuming you have PaymetnConditions rows in your database corresponding to your ReceiptEntity, these should get loaded; the table prefix shouldn't have anything to do with it.

**Comment by JohnFasc** [comment]
I created an minimal [Sample](https://novotec365-my.sharepoint.com/:u:/g/personal/j_fasching_novotec_at/Edl-JEgeWBFFqi3O8TfaiB4Byxeaq5T_rJwTtNagM1Sayg?e=veHKAn) an provided the data, which I use in my test project. 

I also included the Migration.sql and SampleData.sql to provide my data and db scheme and data. 
Please fill in the connection Parameters in the Program.cs

I also recognized, when the <Nullable>enable</Nullable> section in the project file is set, the PaymentConditions get loaded, but I have to remove nearly all propertys in the ReceiptType to get it running.

**Comment by JohnFasc** [comment]
I tried now to create an Sample Project. I copied all files into a new project and and connect it to the same database. Now the PaymentConditions get loaded. I tried the same code in the other project, with no result. 

I think I have to figure out, where the differences could be.
