### ISSUE TITLE
Test: Convert query tests to conditional theory

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#27229]
https://github.com/dotnet/efcore/blob/e42407cb9332bc9bb4357342bf2ddd312873cb23/test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs#L319-L330

Test is of type void. Method used inside is AssertTranslationFailed is async and not awaited. There are several tests like that in the same file. Could be more.

**Comment by maumar** [comment]
was on my list to fix when I saw Arthur's pr.
