### ISSUE TITLE
Context Prematurely Disposed While In Scope

### ISSUE THREAD

**Issue by sbscomp** [dotnet/efcore#27246]
I'm not sure if this is a bug in .NET core itself, or in EFCore, but here's what I'm seeing:

```C#
//Startup DI Registration
services.AddDbContext<Context>(opts => opts
    .UseLazyLoadingProxies()
    .UseSqlServer(configuration.GetConnectionString("Context")));
services.AddScoped<Repository>();
services.AddScoped<Service>();

public class Service{
  //injected: Repository

  public async Task UpdateStatus(int id, StatusEnum NewStatus)
  {
    var app = await repository.Get(id);
    app.Status = NewStatus;
    await repositorySave(app);
  }
}

public class Repository{
  //injected: DbContext
  public async Task<Application> Get(int id) {
    return await context.Applications.Get(id);
  }
  public async Task<Application> Save(Application app) {
    app.UpdatedDate = DateTime.Now;
    //attach if new, etc.
    await context.SaveChangesAsync()
    return app;
  }
}
```
Within Service::UpdateStatus, after the first awaited call to the repository comes back to the service, the context inside the repository is disposed, and the second call to the repository yields a System.ObjectDisposedException. In .Net 6, Blazor incorrectly reports this as "a second operation started when the first one hasn't completed", which is not the case.

If I change the first call to a synchronous one, the context is not disposed and the second call is able to continue as expected.

Expected Result: The context is not disposed as the repository class (and thus the context) are still in scope, and the second awaited call continues as expected.
Actual Result: The context is prematurely disposed as somewhere along the line, something thinks that the context is no longer in scope and the second call throws an exception.

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target frameworks: .NET 3.1, .NET 6
Operating system: Windows
IDE: Visual Studio 2022

**Comment by taspeotis** [comment]
Hi, I am not a contributing I am just passing through the repo...

`//injected: Repository` and `//injected: DbContext` leave a lot of ambiguity, like presumably the DbContext has per-request scope but how are `Service` and `Repository` registered? e.g. Singleton.

> The context is prematurely disposed as somewhere along the line

I would recommend overriding `Dispose` in `Context` and add a `Debugger.Break()` call and then look at the call stack to see what is disposing your context.

I suspect the DI container has decided the lifetime has of the context has ended, but `Service` or `Repository` has a longer lifetime (like singleton).

**Comment by sbscomp** [comment]
Thanks for the suggestion and the additional question about the DI context.

Both classes are set up using `services.AddScoped()`. Either way, the Repository itself is still in scope, and has not been disposed, so the DbContext should not be getting disposed at this point.

When I override `Dispose()` and `DisposeAsync` in my context, and add a debugger breakpoint, `Dispose` is called immediately on the return of the `.SingleAsync()` call in my `Repository::Get` function. The callstack for the `.Dispose` call shows "External Code" / "Resuming Async Function" / "External Code".

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
