### ISSUE TITLE
Delete and add an object with child object, the child object will double

### ISSUE THREAD

**Issue by Gavinluo** [dotnet/efcore#27245]
i have migration framework 4.6 solution  to netcore 3.1 , my service will delete object with child , and  readd a new object with child by same primary key, the problem is readd object , child objects will double in EFCore， objects state is half EntityState.Added and half EntityState.Deleted . this will lead to incorrect  service logic calculations.

[project is here ](https://github.com/Gavinluo/EFCoreReproduceProblem)

For example:

```C#
           //add a new item  with detail
            using (var dbContext = new demoContext())
            {
                var item = dbContext.Set<item>().Find("ItemGID");
                if (item == null)
                {
                    var addItem = new item();
                    addItem.ItemGID = "ItemGID";
                    addItem.itemDetail = new List<itemDetail>() { new itemDetail {
                     GUID ="GUID",
                 ItemGID = "ItemGID"} };
                    dbContext.Set<item>().Add(addItem);
                    dbContext.SaveChanges();
                }
            }

            
            using (var dbContext = new demoContext())
            {
                // remove the item and itemDetail
                IEnumerable<item> items = dbContext.Set<item>().Where(a => a.ItemGID == "ItemGID").AsEnumerable();
                dbContext.Set<item>().RemoveRange(items);

                IEnumerable<itemDetail> itemDestails = dbContext.Set<itemDetail>().Where(a => a.ItemGID == "ItemGID").AsEnumerable();
                dbContext.Set<itemDetail>().RemoveRange(itemDestails);

                //ReAdd the item and itemDetail
                item item = new item { ItemGID = "ItemGID", itemDetail = new List<itemDetail> { new itemDetail { ItemGID = "ItemGID", GUID = "GUID" } } };
                dbContext.Set<item>().Add(item);

                //in Framework EF , this count value is 1 , but in netcore this is 2
                Console.WriteLine(item.itemDetail.Count);
            }
```

EF Core version:
Database provider: Pomelo.EntityFrameworkCore.MySql 3.2.7
Target framework: NetCore 3.1
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@Gavinluo EF Core, unlike EF6, does not "shred" the graph of connected entities when an entity is marked as deleted. This generally makes it easier to work with graphs of entities without ending up with a lot of disconnected single entities.

Looking at the contents of the change tracker at the end of your code shows that both the new ad deleted items are being tracked:

```
item (Shared) {ItemGID: ItemGID} Added
  ItemGID: 'ItemGID' PK
  itemDetail: [{GUID: GUID}, {GUID: GUID}]
item (Shared) {ItemGID: ItemGID} Deleted
  ItemGID: 'ItemGID' PK
  itemDetail: [{GUID: GUID}]
itemDetail (Shared) {GUID: GUID} Added
  GUID: 'GUID' PK
  ItemGID: 'ItemGID' FK
  item: {ItemGID: ItemGID}
itemDetail (Shared) {GUID: GUID} Deleted
  GUID: 'GUID' PK
  ItemGID: 'ItemGID' FK
  item: {ItemGID: ItemGID}
```

Once SaveChanges is called, the entities marked as Deleted are removed from the database and disconnected  from the graph, leaving just the new entities:

```
item {ItemGID: ItemGID} Unchanged
  ItemGID: 'ItemGID' PK
  itemDetail: [{GUID: GUID}]
itemDetail {GUID: GUID} Unchanged
  GUID: 'GUID' PK
  ItemGID: 'ItemGID' FK
  item: {ItemGID: ItemGID}
```

**Comment by Gavinluo** [comment]
thanks , i know EFCore will merge delete and insert option into update, but my question is ReAdd item after delete , the item.itemDetail has two objects ?
`
//ReAdd the item and itemDetail
                item item = new item { ItemGID = "ItemGID", itemDetail = new List<itemDetail> { new itemDetail { ItemGID = "ItemGID", GUID = "GUID" } } };
                dbContext.Set<item>().Add(item);  // why item.itemDetail.Count is 2
`

**Comment by ajcvickers** [comment]
@Gavinluo Because the entity remains in the collection when marked as Deleted, and is only removed from the collection when SaveChanges is call to actually perform the deletion.

**Comment by Gavinluo** [comment]
thanks @ajcvickers , i will use this code to rebuild item , if i do that , is any effect to EF Core ?
```
if(item.itemDetail[0].GetType().FullName.StartsWith("Castle.Proxies.") == true)
                    item.itemDetail.Remove(item);
```

**Comment by ajcvickers** [comment]
@Gavinluo I don't know how that is related to the question you are asking.

**Comment by Gavinluo** [comment]
hi @ajcvickers , my question is **ReAdd** a new item with **one** itemDetail, after `dbContext.Set<item>().Add(item);`  the item.itemDetail.Count is **2**,  by entity framework 6, the count is 1,  the key point is my service code will loop itemDetail to caulate some value  (such as TotalWeight ) , now we get the double Weight because the itemDetail double .

i find the extra one detail type is "Castle.Proxies.itemDetailProxy" , so may i remove it by this code up here

**Comment by ajcvickers** [comment]
The item only matches the proxy type because it happens to be a proxy in this case, while the other entity is not. This is not a reliable way of determining the duplicate.

Why not just remove the first item from the collection before adding the new item?

**Comment by Gavinluo** [comment]
sorry @ajcvickers , my code is not accuracy , Acutally ReAdd itemDetail is different by Deleted itemDetail, i cant remove itemDetail before adding the new item.

by this case created by proxy, may i remove it after add?

**Comment by ajcvickers** [comment]
@Gavinluo If you can accurately show the code you are using, then I'll do my best to suggest a way to make it work.

**Comment by Gavinluo** [comment]
thanks @ajcvickers , i will try my best to give you a simplest demo to explain it . 
```
 using (var dbContext = new demoContext())
            {
                // remove the order and details at first 
                IEnumerable<order> orders = dbContext.Set<item>().Where(a => a.OrderID== "OrderID").AsEnumerable();
                dbContext.Set<order>().RemoveRange(orders);

                IEnumerable<orderDetail > orderDetails = dbContext.Set<orderDetail >().Where(a => a.OrderID == "OrderID").AsEnumerable();
                dbContext.Set<orderDetail >().RemoveRange(orderDetails );


                //Rebuild order and details ,  then ReAdd them
                var orderNew = new order { OrderID = "OrderID", OrderDetail = new List<orderDetail> { new orderDetail { OrderID= "OrderID", GUID = "GUID", Weight=100 } } };
                dbContext.Set<order>().Add(orderNew);
                
                // Loop detail to caculate total weight
                var totalWeight = orderNew.OrderDetail.Sum(a=>a.Weight);

                // Update order invoice total weight
                var inovice = dbContext.Set<orderInovice>().Find("OrderID");
                inovice.TotalWeight = totalWeight;
                dbContext.SaveChange();
            }
```

**Comment by ajcvickers** [comment]
@Gavinluo I'm not following what the code you posted is supposed to do. The `orderNew` object has one `orderDetail`, for which the sum of `Weight` is calculated. Where does the deleted entity come into this?

**Comment by Gavinluo** [comment]
@ajcvickers  Order and Order Detail are existed before i deleted them,  after `dbContext.Set<order>().Add(orderNew);`    `orderNew.OrderDetail`  has two object

**Comment by ajcvickers** [comment]
@Gavinluo Sorry, I didn't realize that you changed the key values between the first and last examples. You could do something like this:

```C#
foreach (var order in orders.ToList())
{
    foreach (var detail in orderDetails.ToList())
    {
        order.OrderDetail.Remove(detail);
    }
}

// Loop detail to caculate total weight
var totalWeight = orderNew.OrderDetail.Sum(a=>a.Weight);
```

**Comment by Gavinluo** [comment]
@ajcvickers thanks for your code , i have tested it , still double weight, only remove it by TypeFullName start with "Castle.Proxies." before caculate, that`s ok
```

    foreach (var detail in orderNew.orderDetails.ToList())
    {
        if(detail.GetType().FullName.StartsWith("Castle.Proxies.") == true)
                    order.OrderDetail.RemoveAt(detail);
    }

```
