### ISSUE TITLE
SQLitePCLRaw.provider.e_sqlite3: Unable to load shared library 'e_sqlite3' or one of its dependencies. 

### ISSUE THREAD

**Issue by solidHeroLink** [dotnet/efcore#27243]
Using Microsoft EF Core version 6.0.1 on Macbook Pro M1.  Trying to save to the database using EF Core but getting the following error message back.

` System.Private.CoreLib: Exception while executing function: AddCompany. Microsoft.Data.Sqlite: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. System.Private.CoreLib: Exception has been thrown by the target of an invocation. SQLitePCLRaw.provider.e_sqlite3: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libe_sqlite3, 0x0001): tried: 'libe_sqlite3' (no such file), '/usr/local/lib/libe_sqlite3' (no such file), '/usr/lib/libe_sqlite3' (no such file), '/Users/intelligentai/RiderProjects/iAi-API/iAI.API.Admin/bin/Debug/net6.0/libe_sqlite3' (no such file), '/usr/local/lib/libe_sqlite3' (no such file), '/usr/lib/libe_sqlite3' (no such file).
`

I've tried installing 'SQLitePCLRaw.bundle_e_sqlite3 2.0.8-pre20220111224339' package but I still get the same problem.

Running MacOS Monterey version 12.1
IDE Jetbrains Rider version 2021.3.2

I have the following packages installed.

` <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="2.0.0-preview1-final" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.8-pre20220111224339" />`

**Comment by ajcvickers** [comment]
@solidHeroLink Can you post your csproj file?

**Comment by solidHeroLink** [comment]
Sure, here is the csproj file.

`<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AzureFunctionsVersion>V4</AzureFunctionsVersion>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.0.0" />
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="6.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.1" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
          <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.1" />
          <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="6.0.1" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\iAi.Services\iAi.Services.csproj" />
    </ItemGroup>
</Project>
`

**Comment by ajcvickers** [comment]
@solidHeroLink Does it work if you're running locally and not targeting Azure Functions?

**Comment by solidHeroLink** [comment]
I am trying to do all this locally.  Connecting to the built in SQLite db on macos.

Any ideas what could be causing the problem?

**Comment by ajcvickers** [comment]
@solidHeroLink Does it work if you're not targeting Azure Functions?

Ideas:
* The M1 architecture might not be supported by Azure Functions
* The project is building for the one target/CPU architecture
* The project is building for the correct architecture, but the there is a bad/wrong installation of that architecture
* Everything is building correctly, but the package for the correct architecture is not being found
* The package is being found, but is not working in some way

**Comment by KirillFrolov** [comment]
In my case,  problem solved with package SQLitePCLRaw.bundle_e_sqlite3 2.0.7

**Comment by RaspeR87** [comment]
Same problem here: https://github.com/dotnet/maui/issues/4490

**Comment by ajcvickers** [comment]
@solidHeroLink Can you try updating to SQLitePCLRaw.bundle_e_sqlite3 [2.0.8-pre20220111224339](https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3/2.0.8-pre20220111224339)?

@RaspeR87 Looks like your issue could be specific to iOS/MAUI.

/cc @ericsink

**Comment by RaspeR87** [comment]
@ajcvickers I tested with https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3/2.0.8-pre20220111224339 too. All same.Yes, it is specific to iOS/MAUI.

**Comment by ericsink** [comment]
I am currently working on net6.0-ios/android support for SQLitePCLRaw.  See ericsink/SQLitePCL.raw#467 and ericsink/SQLitePCL.raw#468.  I hope to release a preview soon for testing.
