### ISSUE TITLE
EF Core 5 on Unity 2021.2

### ISSUE THREAD

**Issue by anorak3** [dotnet/efcore#27241]
According to https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms EF core 5 supports Unity 2021.2.

When I try I get PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.

How can I make Microsoft.Data.SqlClient work in Unity?

**Comment by roji** [comment]
EF Core supports various databases, SQL Server is only one of them.

Unity support for Microsoft.Data.SqlClient is something that can be raised on [their repo](https://github.com/dotnet/SqlClient).

**Comment by anorak3** [comment]
Thanks, I wil ask them.
