### ISSUE TITLE
Problems with ToTable in IEntityTypeConfiguration

### ISSUE THREAD

**Issue by luizfernando1996** [dotnet/efcore#27252]
I want some tables in _**Identity**_ schema but I want this with IEntityTypeConfiguration. 
So, for that my code is 

```C#
    public class AspNetUserClaimsConfiguration : IEntityTypeConfiguration<IdentityUserClaim<Guid>>
    {
        public void Configure(EntityTypeBuilder<IdentityUserClaim<Guid>> builder)
        {
            builder.ToTable("AspNetUserClaims", "Identity");
        }
    }
```
and my context code is

```C#
    public class IdentityContext : IdentityDbContext<ApplicationUser, IdentityRole<Guid>, Guid>
    {
        public IdentityContext(DbContextOptions<IdentityContext> options) : base(options) {}

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.ApplyConfigurationsFromAssembly(typeof(IAsyncDisposable).Assembly);
        }
    }
```
when I run command for generate the migration the configuration for schema is not preserved.
In my project my command is

`dotnet ef --startup-project ..\PadroesTabela\ migrations add Initial --context IdentityContext --verbose`

the file generated for this tools doesn't have that 
`migrationBuilder.EnsureSchema(name: "Identity");`
So the tables generated has the dbo schema.

But when I put this command
`builder.Entity<IdentityUserClaim<Guid>>().ToTable("AspNetUserClaims", "Identity");`
 below this command 
`builder.ApplyConfigurationsFromAssembly(typeof(IAsyncDisposable).Assembly);`
the file is generated the proper way.

EF Core version: Microsoft.EntityFrameworkCore 6.0.1
Microsoft.EntityFrameworkCore.Design 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.1
Target framework: .NET 6.0
Operating system: Windows 10 PRO 10.0.19043
IDE: Visual Studio 2022 17.0.4

More details: I am using Identity Core also but I don't believe is the reason but:
Microsoft.AspNetCore.Identity 2.2.0
Microsoft.AspNetCore.Identity.EntityFrameworkCore 6.0.1
Microsoft.AspNetCore.Identity.UI 6.0.1

**Comment by ajcvickers** [comment]
@luizfernando1996 Have you verified that `AspNetUserClaimsConfiguration` is being executed? By, for example, using a break point?

**Comment by luizfernando1996** [comment]
In this Saturday I will see that and I talk more after that

**Comment by luizfernando1996** [comment]
Yes!! I already verified that!

**Comment by luizfernando1996** [comment]
I have two DbContext in my project and that is the reason. 
In my searchs I found that IEntityTypeConfiguration not works with two DbContext. :/

**Comment by JJong-nl** [comment]
IEntityTypeConfiguration is working. even with multiple dbcontexts.

```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasDefaultSchema("Identity");
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
        }
```

the `base.OnModelCreating` must be before `ApplyConfigurationsFromAssembly`
because for a `IdentityDbContext` the `base.OnModelCreating` is initializing all the user entities.

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/EntityFrameworkCore/src/IdentityUserContext.cs#L320
