### ISSUE TITLE
Make it clear how to disable LazyLoadOnDisposedContextWarning in the exception message

### ISSUE THREAD

**Issue by TimKras** [dotnet/efcore#27255]
Is there a way toe check if the related navigation properties are loaded without getting an LazyLoadOnDisposedContextWarning error.
In EF6 there was an IsLoaded property.

**Comment by ajcvickers** [comment]
@TimKras EF Core has `IsLoaded`. See [Working with a single navigation](https://docs.microsoft.com/en-us/ef/core/change-tracking/entity-entries#working-with-a-single-navigation).

**Comment by TimKras** [comment]
@ajcvickers, but it requires a Context, which is not available anymore in our case.

**Comment by ajcvickers** [comment]
@TimKras Access to the context is required either explicitly or implicitly to check if something is loaded or not. This was the case for EF6 as well. What is the specific situation you are working with?

**Comment by TimKras** [comment]
@ajcvickers We work with detached entities.
In EF6 we could simple check simply check the navigation property for null (!= null).
In EFCore we get an Exception.

**Comment by ajcvickers** [comment]
@TimKras If that is all you need, then you can disable the warning. See [Suppress logging an event](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#suppress-logging-an-event).

**Comment by ajcvickers** [comment]
Exception message already contains details on how to disable it:

```
Unhandled exception. System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.LazyLoadOnDisposedContextWarning': An attempt was made to lazy-load navigation 'PostProxy.Blog' after the associated DbContext was disposed. This exception can be suppressed or
 logged by passing event ID 'CoreEventId.LazyLoadOnDisposedContextWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
```
