### ISSUE TITLE
InvalidOperationException with HasPeriodStart and InMemoryDatabase

### ISSUE THREAD

**Issue by pekspro** [dotnet/efcore#27277]
If InMemoryDatabase ❤️ is used and a temporal table is defined like this:

        modelBuilder
            .Entity<Customer>()
            .ToTable("Customers", b => b.IsTemporal(ttb =>
            {
                ttb
                    .HasPeriodStart("PeriodStart")
                    .HasColumnName("PeriodStart");
            }));

Then an `InvalidOperationException` is thrown with this error message:

    The property 'Customer.PeriodStart' could not be found. Ensure that the property exists and has been included in the model.

I could add PeriodStart into my model, but then the code breaks when with SQL Server provider. A workaround is to simply remove the calls to HasPeriodStart. However, the code is generated like this if it is scaffolded.

### Full sample code

This code demonstrates the issue:

```C#
using Microsoft.EntityFrameworkCore;

OrdersContext context = new OrdersContext();
Customer customer1 = new Customer()
{
    Name = "Alfa"
};

context.Add(customer1);
await context.SaveChangesAsync();

public class Customer
{
    public Guid Id { get; set; }
    public string Name { get; set; }
}

public class OrdersContext : DbContext
{
    public OrdersContext()
    {
    }

    public DbSet<Customer> Customers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        //optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EfCore6TemporarlTest");
        
        optionsBuilder.UseInMemoryDatabase(Guid.NewGuid().ToString());

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // This breaks with InMemoryDatabase:
        modelBuilder
            .Entity<Customer>()
            .ToTable("Customers", b => b.IsTemporal(ttb =>
            {
                ttb
                    .HasPeriodStart("PeriodStart")
                    .HasColumnName("PeriodStart");
            }));

        // Using this instead solves/hides the issue:
        // modelBuilder
        //    .Entity<Customer>()
        //    .ToTable("Customers", b => b.IsTemporal());
    }
}
```

.csproj:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.1">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.1" />
  </ItemGroup>

</Project>
```

### Include provider and version information

EF Core version: 6.0.1
Database provider: InMemoryDatabase
Target framework: .NET 6.0
Operating system: Windows 10

**Comment by dragos-durlut** [comment]
@pekspro 
I've had the same issue as you.
It appears that temporal tables aren't really supported in `InMemoryDatabase`.
I think it has to do with *Shadow Properties*. They might not be supported there.
I was using `InMemoryDatabase` to run some tests and the setup kept failing.
I tried to use a flag to tell if I am using the `InMemoryDatabase` but I couldn't figure out how. At least not a flag I could call in the DB setup.

In the end I had to use a reflection method to check if I was using "NUnit".
```C#
/// <summary>
/// Detect if we are running as part of a nUnit unit test.
/// This is DIRTY and should only be used if absolutely necessary 
/// as its usually a sign of bad design.
/// </summary> 
public static class UnitTestDetector
{
	public static readonly bool IsRunningFromNUnit =
		System.AppDomain.CurrentDomain.GetAssemblies().Any(
			a => a.FullName.ToLowerInvariant().StartsWith("nunit.framework"));
}
```
```C#
public static TemporalTableBuilder<TEntity> SetPeriodStartAndEnd<TEntity>(this TemporalTableBuilder<TEntity> temporalTableBuilder, 
	string periodStartPropertyName,
	string periodEndPropertyName,
	string periodStartColumnName = null,
	string periodEndColumnName = null
	) where TEntity : class
{
	if (Common.UnitTestDetector.IsRunningFromNUnit)
		return temporalTableBuilder;
	if (string.IsNullOrEmpty(periodStartPropertyName))
	{
		throw new ArgumentNullException(nameof(periodStartPropertyName), "Period start property name must have a value");
	}

	if (string.IsNullOrEmpty(periodEndPropertyName))
	{
		throw new ArgumentNullException(nameof(periodEndPropertyName), "Period end property name must have a value");
	}

	var periodStartTemporalPeriodPropertyBuilder = temporalTableBuilder.HasPeriodStart(periodStartPropertyName);
	if (periodStartColumnName != null)
		periodStartTemporalPeriodPropertyBuilder.HasColumnName(periodStartColumnName);

	var periodEndTemporalPeriodPropertyBuilder = temporalTableBuilder.HasPeriodEnd(periodEndPropertyName);
	if (periodEndColumnName != null)
		periodEndTemporalPeriodPropertyBuilder.HasColumnName(periodEndColumnName);

	return temporalTableBuilder;
}
```

**Comment by dragos-durlut** [comment]
Having another look at this [answer on stack-overflow](https://stackoverflow.com/questions/40621262/determine-at-runtime-which-db-provider-is-being-used-with-ef-core/51487154) I've noticed that you can use the extension method [IsSqlServer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverdatabasefacadeextensions.issqlserver?view=efcore-6.0) on DatabaseFacade.

This can be used at runtime to determine if you are using SQL Server or not.

Maybe this would be better than my smelly DLL detector method.

**Comment by ajcvickers** [comment]
@pekspro The in-memory database does not support SQL Server-specific features, like temporal tables. We strongly discourage using the in-memory database for testing like this. See [Testing EF Core Applications](https://docs.microsoft.com/en-us/ef/core/testing/) for more information.

**Comment by anthony-keller** [comment]
@ajcvickers I have a similar situation whereby I'm using temporal tables with SQL Server but have some automated tests using the same DbContext with an InMemoryDatabase.

I understand that temporal tables are not supported in the InMemoryDatabase - ideally there would be a way in to detect whether temporal tables are supported from an EntityTypeBuilder.

e.g.

```
if (entityTypeBuilder.Metadata.HasTemporalTableSupport()) {
  // configure the temporal table here
}
```

I know there is an extension method on `DatabaseFacade` to detect the in memory database so I could use that and pass it around to where I need it in my entity builders but I was hopeful there would be an easier way.
