### ISSUE TITLE
Is there a way to create a migration by comparing the current ContextModelSnapshot to a live DB?

### ISSUE THREAD

**Issue by rowanmoul** [dotnet/efcore#27275]
Since recently switching to EF Core from EF 6, where we were using automatic migrations, my team has unfortunately fallen into this trap, or one very similar to it with EF Core code-based migrations:
https://www.mikee.se/posts/corrupted_model_snapshot_in_ef_core_20210117

To summarize, we have a ContextModelSnapshot that includes changes that were never applied to the database in any migration, but we don't know which changes have not been applied aside from the one we noticed which led to this post.

Despite my best efforts searching I cannot find a way to generate a migration by comparing the current ContextModelSnapshot to the current live database and create migration changes that would bring the live database back in sync with the code.

I could restore an older copy of the ContextModelSnapshot, create a migration, and then manually delete lines from that new migration that I can see by visual inspection exist in a previous migration, but not only is that tedious, I don't actually know for sure if that older ContextModelSnapshot actually reflected the DB schema correctly at the time. I could revert to the original snapshot created when we switched to EF Core (I can probably assume that original was in sync at the time as changes before this would have been automatically applied under EF 6 automatic migrations), but that's nearly 80 migrations ago, and most of them are probably fine.

Is there no way to do this aside from following the tedious process above?

**Comment by ajcvickers** [comment]
@rowanmoul As I understand it, you have a current model and model snapshot that are not in sync with the current database. If this is the case, then we discussed this, and there isn't a great way to ensure that they are in sync. One think to try is reverse engineering the database and compare the entity types created to those in your current model. This may be cumbersome if your model has a lot of mapping customizations, such as inheritance hierarchies, but we haven't been able to come up with any better ideas.

**Comment by ErikEJ** [comment]
Does @jpsmith not have some tooling for that?

**Comment by JonPSmith** [comment]
I don't have anything, but its easy to create a test database using the  `context.Database.Migrate` method (which the ContextModelSnapshot represents) and create a database using the `context.Database.EnsureCreated` method (which represents the current model). From there must be a tool somewhere to compare the two schemas. [SQL Server Data Tools (SSDT)](https://docs.microsoft.com/en-us/sql/ssdt/how-to-use-schema-compare-to-compare-different-database-definitions) has one but maybe not easy to automate.

**Comment by ErikEJ** [comment]
Did you not have a compare tool?

**Comment by ErikEJ** [comment]
https://github.com/JonPSmith/EfCore.SchemaCompare

**Comment by JonPSmith** [comment]
I do have a compare tool, which compares EF Core's current model to a existing database, but it has some limitations. I thought there were lots of compare schema tools between two databases.

If @rowanmoul is happy with the [EfCore.SchemaCompare limitations](https://github.com/JonPSmith/EfCore.SchemaCompare#List-of-limitations) then the process would be:

1. Create a test database using `context.Database.Migrate`
2. Install the EfCore.SchemaCompare library and create a test / Console app that [runs the `CompareEfWithDb` method ](https://github.com/JonPSmith/EfCore.SchemaCompare#how-to-use-efschemacompare) against the database created in step 1.

**Comment by rowanmoul** [comment]
@JonPSmith this tool looks really useful. I ended up doing it the manual way described in my original post due to time constraints, but I'll definitely give this a try as soon as I can!
This seems like a tool that should be included in dotnet-ef as it is a bit precarious to just assume the snapshot matches the DB.

**Comment by JonPSmith** [comment]
hi @rowanmoul,

I'm glad you sorted out your migration, and sorry I didn't get back more quickly. As someone who moved from EF6 to EF Core I can tell you that EF Core is MUCH better :)

PS. Have a look at my [GitHub page](https://github.com/JonPSmith) as I have a number of libraries that helps with EF Core and ASP.NET Core issues. Also my tech blog https://www.thereformedprogrammer.net/ has lots of EF Core / ASP.NET Core articles.
