### ISSUE TITLE
EF 5.X net5.0 target gone from Nuget

### ISSUE THREAD

**Issue by dealdiane** [dotnet/efcore#27273]
Our builds have stopped working today because it couldn't install any EF 5.X dependencies. Sure enough, when I checked [the nuget page](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.13), net5.0 is nowhere to be found and instead was replaced with NETStandard2.1.

Seems to be an issue specific to any EF Core package. The ASPNet core packages work fine.

The build error is:
`Package Microsoft.EntityFrameworkCore.SqlServer 5.0.9 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.SqlServer 5.0.9 supports: netstandard2.1 (.NETStandard,Version=v2.1)`

**Comment by smitpatel** [comment]
tfm with net50 represent .NET Framework version 5.0 which is not same as .NET 5. To use .NET 5 (what EF Core 5 supports), the correct tfm would be "net5.0" (with . between 5 & 0)

**Comment by dealdiane** [comment]
Looks like a muck up from our part! 

@smitpatel yes, correct. The log was taken from a deprecated test build so never worked.
