### ISSUE TITLE
After migrating 2.2.6 to 6.0.0 EF Core Migrations Snapshot problems

### ISSUE THREAD

**Issue by hookenful** [dotnet/efcore#27298]
Hello there!

Recently we have updated our project libraries for .NET 6 and EF Core 6.0.0. And after that creating migraion causes something strange behavior. 
I've noticed that after executing command ```  dotnet ef migrations add Initial2 -p .\src\Only.Portal.Data\ -s .\src\Only.Portal.Web ``` in developer powershell in VS2019 it is starting a project there and after I stop it with CTRL + C migration being created. Previously there was only Build started .. Build finished and EF Core tools info. What happened ? What does project start with migration?

After all it is adding strange scaffoldings into migration and causes some missing references in migration file and ContextSnapshot.
```
           migrationBuilder.AlterColumn<DiscoveryStepStage>(
                name: "DiscoveryStepStage",
                table: "UserDiscoveryStep",
                type: "smallint",
                nullable: false,
                defaultValue: DiscoveryStepStage.Started,
                oldClrType: typeof(byte),
                oldType: "smallint",
                oldDefaultValue: (byte)1);

            migrationBuilder.AlterColumn<DiscoveryStep>(
                name: "DiscoveryStep",
                table: "UserDiscoveryStep",
                type: "smallint",
                nullable: false,
                defaultValue: DiscoveryStep.GoldRush,
                oldClrType: typeof(byte),
                oldType: "smallint",
                oldDefaultValue: (byte)1);

            migrationBuilder.AlterColumn<UserCourseState>(
                name: "State",
                table: "UserCourse",
                type: "smallint",
                nullable: false,
                defaultValue: UserCourseState.Start,
                oldClrType: typeof(byte),
                oldType: "smallint",
                oldDefaultValue: (byte)0);

            migrationBuilder.AlterColumn<PageWallAccessType>(
                name: "WallAccessType",
                table: "Page",
                type: "smallint",
                nullable: false,
                defaultValue: PageWallAccessType.Open,
                oldClrType: typeof(byte),
                oldType: "smallint",
                oldDefaultValue: (byte)1);

            migrationBuilder.AlterColumn<PageAccessType>(
                name: "AccessType",
                table: "Page",
                type: "smallint",
                nullable: false,
                defaultValue: PageAccessType.Open,
                oldClrType: typeof(byte),
                oldType: "smallint",
                oldDefaultValue: (byte)1);

            migrationBuilder.AlterColumn<NotificationType>(
                name: "NotificationType",
                table: "Notification",
                type: "smallint",
                nullable: false,
                defaultValue: NotificationType.PushNotification,
                oldClrType: typeof(short),
                oldType: "smallint",
                oldDefaultValue: (short)1);

            migrationBuilder.AlterColumn<MeetingRecurrenceType>(
                name: "Type",
                table: "MeetingRecurrence",
                type: "smallint",
                nullable: false,
                defaultValue: MeetingRecurrenceType.DailyPattern,
                oldClrType: typeof(byte),
                oldType: "smallint",
                oldDefaultValue: (byte)11);

            migrationBuilder.AlterColumn<MailingType>(
                name: "Type",
                table: "Mailing",
                type: "integer",
                nullable: false,
                defaultValue: MailingType.WelcomeTui,
                oldClrType: typeof(int),
                oldType: "integer",
                oldDefaultValue: 1);
```

After resolving missing references and creating new migration, that causes absolutely the same scaffolded changes like in previous code chunk. As well with damaging snapshot with missing references. 

What can cause the problem?

Thanks in advance!

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.PostgresSQL)
Target framework: .NET 6.0

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by hookenful** [comment]
@ajcvickers @roji  i think that it is not possible to provide autonomous code that can reproduce the problem, because that is big project.

The problem is described in first post. After migrate from 2.2.6 to 6.0.0 EF Core, when creating new migration -> something strange happens. I can provide screenshots step by step.

1) First strange behavior. When applying command dotnet ef migrations add.. It starts app from developer powershell and waiting for stop (CTRL + C) before creating migration.
[https://i.gyazo.com/37dfdc66fe551537f6fc02b3dd880378.png](https://i.gyazo.com/37dfdc66fe551537f6fc02b3dd880378.png)

2) Second strange behavior. After app stop CTRL + C. It says of creating migration
[https://i.gyazo.com/37dfdc66fe551537f6fc02b3dd880378.png]()

3) Third strange behavior. I am getting this change in ContextSnapshot which causes all enum type reference fail
[https://user-images.githubusercontent.com/31849464/151502924-95fee986-c48f-495a-a549-2046e760d75e.png](url)

4) Fourth strange behavior. This changes in migrations related to the enum: byte entites.
[https://i.gyazo.com/104b203ba7de8208df84fa28771e340b.png](url)

5) Fifth strange behavior. After reference error fix (put back enum using Only.Portal.Domain.Enums reference and creating new migration. All the 1-4 steps are the same. E.g the same migrations with enum: byte -> smallint, defaulvalue from (byte)1. to enum  WallPrivacy.Public. 

I am so tired of these 2 days of trying to fix, that hands down really..

Thanks for any help!

**Comment by hookenful** [comment]
I suppose, I found the problem.

Maybe you can reproduce the problem introducing bottom extension method `HasDefaultEnumValue` and in your entity configuration use it


```
 typeBuilder.Property(p => p.Type)
 .HasDefaultValue(GiftCardType.BirthDay);
```




```
internal static class PropertyBuilderExtensions
    {
        internal static PropertyBuilder<TProperty> HasDefaultEnumValue<TProperty>(this PropertyBuilder<TProperty> builder, TProperty defaultValue)
        {
            Type enumType = typeof(TProperty);
            
            if (!enumType.IsEnum)
            {
                if (!enumType.IsGenericType) return builder;

                enumType = enumType.GetGenericArguments().First();

                if (!enumType.IsEnum) return builder;
            }
            else
            {
                builder = builder
                    .HasDefaultValue(defaultValue)
                    .ValueGeneratedNever();
            }
            
            return builder
                .HasConversion(
                    v => GetValue(enumType, v, defaultValue),
                    v => v
                );
        }

        internal static TProperty GetValue<TProperty>(Type enumType, TProperty value, TProperty defaultValue)
        {
            return value == null || EnumExtensions.IsDefined(enumType, value) ? value : defaultValue;
        }
    }
```

**Comment by ajcvickers** [comment]
@hookenful 

> Maybe you can reproduce the problem introducing bottom extension method HasDefaultEnumValue and in your entity configuration use it.

Have you been able to build a small test application that reproduces the behavior you are seeing when using the code you posted above? If not, then chances are we will not be able to do so either. We really need to be able to reproduce what you are seeing to be able to properly investigate it. So if you are able to build something that reproduces what you are seeing, then please attach it so that we can dig into it./
