### ISSUE TITLE
Missing link efcore-manage-schemas

### ISSUE THREAD

**Issue by zanejgr** [dotnet/efcore#27290]
Link aka.ms/efcore-manage-schemas in article docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated?view=efcore-6.0#remarks redirects to www.bing.com/?ref=aka&shorturl=efcore-manage-schemas

**Comment by smitpatel** [comment]
the real vanity names are prefixed with efcore-docs-manage-schemas & efcore-docs-ensure-created (another link on the same line).

Should also check for other broken links if any. Since these links redirects to something, broken links report doesn't detect them as broken.

**Comment by smitpatel** [comment]
There are more broken links. Found a few while randomly searching. A good search would be to check for aka.ms/efcore- not followed by docs

**Comment by smitpatel** [comment]
Co-assigning myself so that I can mirror changes on the live site from source code.

**Comment by ajcvickers** [comment]
@smitpatel Now updated in main.
