### ISSUE TITLE
Support for EF Core 3.1 on .NET Framework

### ISSUE THREAD

**Issue by Tobias-08** [dotnet/efcore#27294]
Will the support for EF Core 3.1 on .NET Framework be extended beyond 12/2022 like it has been for ASP.NET Core 2.1 on .NET Framework?

Context:

We have applications that use EF Core 3.1 on .NET Framework (net48). These applications cannot be migrated to .NET 6 because they have dependencies to libraries that do not support netcoreapp/net6.0 or netstandard. As EF Core 6 does not support netstandard2.0 any more these applications also cannot be updated to use EF Core 6. So there is no migration path but support (for EF Core 3.1) ends 12/2022.

Thanks!

**Comment by ajcvickers** [comment]
@Tobias-08 The EF Core packages are included in the extended support for ASP.NET Core 2.1 on .NET Framework. There are no plans to extend 3.1 support.

**Comment by Tobias-08** [comment]
Thanks @ajcvickers . So is the official guidance for use cases like above to downgrade to EF Core 2.1? Looking at the changes from EF Core 2.1 to 3.1 this is not a reasonable approach in my opinion.

Maybe you could rethink about extending EF Core 3.1 support. In my opinion many applications are affected by this issue (e. g. applications that use SharePoint-CSOM-dll on prem which does not support .NET Core/.NET 6).

As this issue is a consequence of (the questionable strategy of) dropping netstandard2.0 support in EF Core 5 it in my opinion justifies an adjustment of the support policy in this case.

**Comment by ajcvickers** [comment]
@Pilchie Who can we reach out to about "SharePoint-CSOM-dll" support for modern .NET?

**Comment by ErikEJ** [comment]
??? What is the issue: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard#key-differences-between-the-net-framework-version-and-the-net-standard-version

**Comment by Tobias-08** [comment]
The issue is that SharePoint on prem is not supported (third row in the table from your link).

**Comment by roji** [comment]
Yeah, that's unfortunate (@ajcvickers [see this blog post](https://devblogs.microsoft.com/microsoft365dev/net-standard-version-of-sharepoint-online-csom-apis/#faq) where this is discussed and justified).

Note that there seems to be at least some support for [using the Graph API when in hybrid mode](https://docs.microsoft.com/en-us/answers/questions/224266/graph-api-for-on-prem-and-hybrid-deployments.html), but I'm not seeing anything for pure on-premise.

@Tobias-08 concretely, here are some possible options:

* In some cases, you can reference .NET Framework assemblies/packages from a modern .NET (Core) application ([see docs](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-0#support-for-net-framework-libraries)); this can help exactly in this case, where a dependency only exists in .NET Framework. This won't always work: it depends on the CSOM library not using any APIs which aren't compatible etc., but it's probably worth trying. This would mean porting your application itself to modern .NET (which ideally would happen at some point anyway).
* I can see other ways to access on-premise Sharepoint, e.g. REST - that may be worth looking into.
* Finally, one (extreme) way to work around this is to split the application into a .NET Framework component (for Sharepoint) and a modern .NET component (for all the rest). The two programs would communicate with each other in some way (i.e. networking). This definitely isn't a great situation to be in, but it may be a possible way forward.

**Comment by ErikEJ** [comment]
Our SharePoint experts believe they can help, feel free to email me to discuss

**Comment by Pilchie** [comment]
@Tobias-08 There are currently know plans to extend support for EFCore 3.1 on .NET Framework. With that said, the best way to engage in that conversation is through your companies Microsoft Account Manager.
