### ISSUE TITLE
First migration rollback does not delete the __EFMigrationsHistory table

### ISSUE THREAD

**Issue by cristipufu** [dotnet/efcore#27300]
Hello,

In case there's an error in the first migration, the rollback does not delete the __EFMigrationsHistory table. Is there a way I can force EF to remove this table as well?

```C#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
                name: "Entities",
                schema: "dbo",
                columns: table => new {
                ....
    });

   throw Exception("force rollback");
}

protected override void Down(MigrationBuilder migrationBuilder)
{
    migrationBuilder.DropTable(
                name: "Entities",
                schema: "dbo");
}
```

I was looking over the code, and found this https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Migrations/Internal/Migrator.cs#L302 (this is the place where we ensure the migration history table exists). Shouldn't this happen inside the same transaction that executes the migration's code?

### Provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0

**Comment by ajcvickers** [comment]
@cristipufu Why does the history table need to be deleted?

**Comment by cristipufu** [comment]
Ideally speaking, after a rollback, one would expect the state of the database to match the exact state of the database before the migration was applied, right?

In our case, we have an msi installer of a suite of products, most of them using EF6 and all of them can be installed on the same database with a different schema. If the upgrade to a new product version fails, we have some validation steps that ensure the database has the same state (no of tables, columns, etc) as before the upgrade. This worked just fine in EF6. Now we re trying to add a new product that uses EFCore and in case of a rollback, we have the leftover _MigrationHistory table which makes our generic validation scripts fail. We can work around this, but imo this behavior is unexpected and it should be considered an issue.

**Comment by ajcvickers** [comment]
@cristipufu The migration history table can contain data from multiple different DbContext types. We therefore intentionally never delete it, just remove the appropriate data for the action being performed. In your specific case, if the table is known to be empty and not being used by any other DbContext type, then it should be pretty easy to add your own step to fully delete the database.
