### ISSUE TITLE
Add AddDbContextPool overloads to configure the ServiceLifetime

### ISSUE THREAD

**Issue by Strandedpirate** [dotnet/efcore#27303]
My application runs multiple database queries in parallel on the same thread. This is a non-issue when I register my context using `AddDbContext` using a transient lifetime as follows:

```
builder.Services.AddDbContext<MyDbContext>(options => options.UseSqlServer(appSettings.ConnectionStrings.MyContext), ServiceLifetime.Transient);
```

I would like to use pooling with `AddDbContextPool` to get better performance, but there is are no overloads that accept a `ServiceLifetime` argument.

I would like to be able to do this:
```
builder.Services.AddDbContextPool<RippleDbContext>(options => options.UseSqlServer(appSettings.ConnectionStrings.ApparelContext, 128, ServiceLifetime.Transient);
```

**Comment by roji** [comment]
@Strandedpirate you can use AddPooledDbContextFactory, which will cause a pooling IDbContextFactory to get injected to your types. At that point you can call CreateDbContext on it to get a pooled context - be sure to dispose it when you're done.

**Comment by Strandedpirate** [comment]
@roji , that worked, thanks!
