### ISSUE TITLE
Can't map two classes with same name from different namespace

### ISSUE THREAD

**Issue by LostBalloon1** [dotnet/efcore#2731]
As I have no clue if CodePlex is even being looked at anymore.
I would like to know what is going on with the following issue:
https://entityframework.codeplex.com/workitem/483?FocusElement=CommentTextBox

as it still has not been completely fixed with EF6 and despite the low priority it is being given, general consensus is that it's priority should be much higher that the one that has been give to it.

The issue dates from September 4th 2012.

**Comment by rowanmiller** [comment]
We are still using the CodePlex project for EF6. This isn't something we are planning to address on EF6 (though we would consider accepting a pull request on it). It is addressed in EF7.
