### ISSUE TITLE
Support IMutableNavigation.SetJsonPropertyName/IReadOnlyNavigation.GetJsonPropertyName - CosmosDB Provider

### ISSUE THREAD

**Issue by georgechond94** [dotnet/efcore#27328]
I am setting the json property names for all the non-shadow properties in my model as such: 

```C#
var scalarProperties = builder.Model.GetEntityTypes()
                .SelectMany(et => et.GetProperties().Where(p => !p.IsShadowProperty()).ToList());

foreach (var mutableProperty in scalarProperties)
{
    var str = mutableProperty.GetJsonPropertyName();
    mutableProperty.SetJsonPropertyName(char.ToLowerInvariant(str[0]) + str[1..]);
}
```

The above works well for scalar properties, although the same functionality is not there for navigation properties:

```C#
var navigationProperties = builder.Model.GetEntityTypes()
                .SelectMany(et => et.GetNavigations().Where(p => !p.IsShadowProperty()).ToList());

foreach (var mutableNavigation in navigationProperties)
{
    var str = mutableNavigation.GetJsonPropertyName(); // doesn't exist
    mutableNavigation.SetJsonPropertyName(char.ToLowerInvariant(str[0]) + str[1..]); // doesn't exist
}
```

I tried setting the `CosmosAnnotationNames.PropertyName` annotation explicitly but it seems that it's being ignored for the `IMutableNavigation` objects.

```C#
public static void SetJsonPropertyName(IMutableNavigation navigation, string? name)
    => navigation.SetOrRemoveAnnotation(CosmosAnnotationNames.PropertyName, name);
```

Any reason why this is not supported?

Thanks!

**Comment by AndriySvyryd** [comment]
Try `IMutableNavigation.SetContainingPropertyName()`

**Comment by georgechond94** [comment]
Hi @AndriySvyryd, thanks for your reply, that works as expected!

Question: do you think it makes sense to align that part a bit so these extension methods exist for both `INavigation` & `IProperty`?

I tried to implement that as my first contribution to efcore here: https://github.com/georgechond94/efcore/commit/719ebf076ccf198de8b84eeadb022d33d0ba7bfa
It works as expected and there are no failing tests.

Let me know if that change is welcome, if yes, I will go on with creating some tests & a PR.

**Comment by AndriySvyryd** [comment]
I don't think it improves the experience that much. Hopefully https://github.com/dotnet/efcore/issues/15258 will make it unnecessary so use the methods on IMutable* interfaces
