### ISSUE TITLE
Calling setter for ICollection of navigation properties

### ISSUE THREAD

**Issue by Anakael** [dotnet/efcore#27329]
I want to use setter for collection of navigation property.

Like:
```cs
public class User
{
  private IEnumerable<Post> posts;

  public IReadOnlyCollection<Post> Posts
  {
     get => posts;
     set
     {
        posts = value;
        // call other side effects
     }
  }
}
```

Is there any way to achieve that? Such works for me only for one navigation property, not for collection.

**Comment by ajcvickers** [comment]
@Anakael This should work. What specific issues are you having?

**Comment by Anakael** [comment]
> @Anakael This should work. What specific issues are you having?

Problem is in fact that setter is not called (although field value is have been set).

**Comment by Anakael** [comment]
For some reasons, now it works. Perhaps, I just missed something when tried in first time.
Thank you for your time!

**Comment by Anakael** [comment]
I noticed in debugger that `value` in setter is empty list. But after object is created it's not and setter for non-empty list wasn't called.

I've set 
```cs
builder.Metadata
                .FindNavigation(nameof(User.Posts))
                .SetPropertyAccessMode(PropertyAccessMode.Property);
```

**Comment by ajcvickers** [comment]
@Anakael EF creates an empty collection if one does not already exist when first accessing the collection. It then adds and removes items from the collection as they are loaded or otherwise manipulated.

**Comment by Anakael** [comment]
I've put `posts = new List<Post>()` and it still populated with data.

**Comment by Anakael** [comment]
But how EF core knows that I've put my own collection for posts and EF should use it instead of creating new one?

**Comment by ajcvickers** [comment]
@Anakael It reads the field/property to see if it is null or not.

**Comment by Anakael** [comment]
Oh, I see. Thank you!
