### ISSUE TITLE
Construct IDesignTimeDbContextFactory without first discovering all DbContext types

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#27322]
Currently, services are discovered before creating any IDesignTimeDbContextFactory instance. This ensures that we get the correct DbContext type when multiple may be registered, possibly from different assemblies. However, this is problematic when the context factory is being used as an escape hatch for something that is failing in service discovery--for example, see #27306 and comments on #9076.

To fix this, we could do an initial search using some heuristics. For example, we could search for `IDesignTimeDbContextFactory` implementations and if there is only one found for one context type which matches the context type specified on the command line, then use it with no further discovery.

**Comment by Andrey-Ignatenko** [comment]
Hi guys.

We are migrating from .NET 3.1 to .NET 6, and we'd like to use EF6 as well. However, the issue mentioned here #27306  and here #9076 makes the experience of adding migrations really frustrating... 

As I understand current issue (Constructing IDesignTimeDbContextFactory without first discovering all DbContext types) should resolve it for us. So hopefully it will be done soon. Do you have any timeline for this?

Thanks!
