### ISSUE TITLE
Nullable String with Unique Index Converted to Empty String

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#27347]
We have a field defined like:
```

        [Column("MyField")]
        [StringLength(450)]
        public string? MyField { get; set; }
```

```
                entity.HasIndex(e => e.MyField)
                    .HasName("UniquePageUrlExceptNulls")
                    .IsUnique()
                    .HasFilter("([MyField] IS NOT NULL)");
```

When we pass null to EF Core on insert, under the hood it converts to "".
Coming back out of the DB nulls are converted to "".

We tried:
`.HasDefaultValueSql("(NULL)");`

To no effect.

Is this a bug or is there something we're missing related to configuration?

---

Edit: Currently working around this an adjustment to the filtered index
`.HasFilter("([MyField] IS NOT NULL AND [MyField] <> '')");`

Not an ideal long term solution though.

---
EF Core 6
Microsoft.EntityFrameworkCore.SqlServer
.NET 6.0
Win 11
VS 22

**Comment by ajcvickers** [comment]
@OpenSpacesAndPlaces 

> When we pass null to EF Core on insert, under the hood it converts to "".

EF doesn't do this, so if this is happening, then something is wrong somewhere. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by OpenSpacesAndPlaces** [comment]
I was able to put to together a simple sample project and tracked it down to an XSS library we were using.
Thanks for pointing me in the right direction.
