### ISSUE TITLE
Survey: GitHub contributor experience for dotnet/efcore

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#27348]
We’d like to hear from you as members of the community in this repo to learn how we were doing as maintainers.

Whether you've been involved for some time or you're relatively new, please tell us about your experience participating and contributing to this project. It should only take a few minutes, and you can answer for up to 3 repos.

[SurveyMonkey survey for dotnet/efcore repo](https://www.surveymonkey.com/r/8QTQTGJ?Source=efcore)

**Comment by danmoseley** [comment]
Survey is now closed - thanks for everyone that responded. We'll look through the feedback now.
