### ISSUE TITLE
Migrations: PK indexes not renamed when renaming table with non-default schema

### ISSUE THREAD

**Issue by petedavis** [dotnet/efcore#2735]
Using EF 6.1.3, .net 4.5.2

It appears that the query to rename the PK index after the table name has been renamed does not apply the schema name to the index name. Therefore the index is not being renamed if the schema is not the default schema.

This is the SQL that is generated by the following migration:

``` csharp
RenameTable(name: "trade.AspNetUsers", newName: "TradeUsers");
```

was

``` sql
EXECUTE sp_rename @objname = N'trade.AspNetUsers', @newname = N'TradeUsers', @objtype = N'OBJECT'
IF object_id('[PK_trade.AspNetUsers]') IS NOT NULL BEGIN
    EXECUTE sp_rename @objname = N'[PK_trade.AspNetUsers]', @newname = N'PK_trade.TradeUsers', @objtype = N'OBJECT'
END
```

I would assume that the PK index exists and rename queries should be prefixed with the new table name:

``` sql
EXECUTE sp_rename @objname = N'trade.AspNetUsers', @newname = N'TradeUsers', @objtype = N'OBJECT'
IF object_id('[trade].[TradeUsers].[PK_trade.AspNetUsers]') IS NOT NULL BEGIN
    EXECUTE sp_rename @objname = N'[trade].[TradeUsers].[PK_trade.AspNetUsers]', @newname = N'PK_trade.TradeUsers', @objtype = N'OBJECT'
END
```

Also when executing the same command through SQL Management studio, the objtype parameter is N'INDEX' rather than N'OBJECT'

**Comment by rowanmiller** [comment]
Hey,

This is fixed in EF7. Unfortunately in EF6.x we don't specify a name for the index and the database is left to pick one. So we don't know what the name is to change it. This has caused a lot of issues and so in EF7 we have been careful to make sure that everything always has a name that we chose.

~Rowan
