### ISSUE TITLE
Scaffolding for Sqlite doesn't generate ValueGeneratedOnAdd() in model builder for autoincremented indices

### ISSUE THREAD

**Issue by antgraf** [dotnet/efcore#27359]
Scaffolding for Sqlite doesn't generate ValueGeneratedOnAdd() in model builder for autoincremented indices

### Steps:
1. Create a Sqlite DB
2. Create a table
`CREATE TABLE "table1" (
	"id"	INTEGER NOT NULL UNIQUE,
	"field"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);`
3. Create a .NET 6 console app (Tested on SDK Version: 6.0.101)
4. Install nuget packages:
`Microsoft.EntityFrameworkCore.Sqlite 6.0.1, Microsoft.EntityFrameworkCore.Tools 6.0.1`
5. Issue a command in package manager console:
`Scaffold-DbContext 'Data Source=d:/temp/testdb.db' Microsoft.EntityFrameworkCore.Sqlite -Project TestSqliteScaffolding -StartupProject TestSqliteScaffolding -ContextDir Data -OutputDir Models -Force`
6. Inspect generated db context code in testdbContext.cs

### Expected:
OnModelCreating() method contains `entity.Property(e => e.Id).ValueGeneratedOnAdd();`

### Actual:
Code isn't there

**Comment by ErikEJ** [comment]
I think this is not needed, as it is covered by conventions.

https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations
