### ISSUE TITLE
[Question] SQL server query with update operation in EF core

### ISSUE THREAD

**Issue by chintanr97** [dotnet/efcore#27353]
Hi team,

I was observing the query that EF core executes on SQL server during an update operation. Let us consider, that we are editing an employee record in a table which has following properties: `Id (PK), FirstName, LastName`. The EF core code snippet would look like:

```C#
var employee = context.Employees.FirstOrDefault(employee => employee.Id == requestId); 
employee.FirstName = "NewName";
context.SaveChanges();
```

A corresponding SQL server query in this case would look like:
```SQL
UPDATE [Employees] SET [FirstName] = @p0
WHERE [Id] = @p1;
```

Here, the query was executed with a filter on the primary key. Now, let us say, we have another table: `EmployeeDetails` in the database with properties: `EmployeeId (FK, Employee.Id), Address, PhoneNumber`. In this case if an update is executed using EF core, then a corresponding SQL server query would look like:
```SQL
UPDATE [EmployeeDetails] SET [Address] = @p0
WHERE [EmployeeId] = @p1;
```

Here, the query was executed with a filter on the foreign key. Now, based on this observation, I wanted to understand how EF core defines the filtering logic during the update (or let us say, for delete operation too). For example, if we had an additional foreign key in the `EmployeeDetails` table like: `EmployeeId (FK, Employee.Id), Address, PhoneNumber, VehicleId (FK, EmployeeVehicles.Id)`, then would the filtering include the second foreign key as well in the SQL server query during the update operation?

More generally, the table could have a primary key, multiple foreign keys (in absence or presence of primary key), unique key constraints. So, I wanted to learn about how the logic for filtering records, is implemented by the EF core and which key components are included in the filtering during the update query execution on the SQL server.

### Include provider and version information

EF Core version: 5.0
Database provider: SQL server
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by roji** [comment]
@chintanr97 EF Core uses the primary key to identify rows, i.e. when deleting or updating them; when updating `EmployeeDetails` above, `EmployeeId` is specified in the UPDATE WHERE clause because it's the primary key (even if it's also the foreign key to another table).

If this isn't clear, can you please submit a full code sample, including both your model and the query?

**Comment by chintanr97** [comment]
@roji , thanks a lot for your response.

> If this isn't clear, can you please submit a full code sample, including both your model and the query?

As this is more of learning query, I built the entity schemas in above examples on the fly. I am currently learning how the update/delete operations are executed with the help of EF core.

I think it makes sense that EF core uses primary key or the foreign keys (which are implicitly a reference to a primary key) for the WHERE clause with update or delete operations. However, let us consider the last example where the `EmployeeDetails` table is described as: `EmployeeId (FK, Employee.Id), Address, PhoneNumber, VehicleId (FK, EmployeeVehicles.Id)`. In this case would both the FKs, `EmployeeId` and `VehicleId` be used in the WHERE clause?

Also, I am guessing if there are no FK or primary key constraints on the table, then EF core executes an update operation over the complete table. And same goes with a delete operation too. Am I right, or am I missing something?

**Comment by roji** [comment]
Again, in order for EF Core to support update/deletion, EmployeeDetails must have a primary key configured, and that's what get used - yourr definition above is missing that. Note that EF doesn't necessarily care about your database table configuration - what matters is how you configure your EF model (although if the two diverge that could quickly cause various problems).

If this still isn't clear, I highly suggest writing a quick, minimal EF code sample and trying to play with that; if anything isn't clear, you can post that sample and I can help understand what the concrete code does.

**Comment by chintanr97** [comment]
@roji , I think I understood now. The example I was playing with locally, had primary key on the `EmployeeId` column apart from the FK. When I removed that, I observed that entity was not tracked in the change tracker upon query.

```csharp
var entityWithoutKey = context.EmployeeDetails.FirstOrDefault(employeeDetails => employeeDetails.EmployeeId == requestId); 
```

So, I manually requested the call to `context.Update(entityWithoutKey)` and I got an exception: `Only entity types with primary keys may be tracked` .

So, I think I now understand that EF core always expects a primary key to be present on the entity for it to be tracked in different states, so that it can be inserted, updated, or deleted. Please let me know if I have misunderstood anything here.

Regards,
Chintan Rajvir

**Comment by roji** [comment]
That's correct - a primary key is required for an entity to be tracked (which is a requirement for insert/update/delete). EF Core does support [keyless entity types](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations), but these cannot be inserted/updated/deleted.
