### ISSUE TITLE
Custom Execution Strategy with Entity Framework Core

### ISSUE THREAD

**Issue by chekm8** [dotnet/efcore#27368]
I have a .Net Core 3.1 Windows Service running using EF Core with a custom ExecutionStrategy. This strategy has some logic in ShouldRetryOn() to perform time based logging when exceptions occur. It is working well form the perspective of issuing the warnings when I want them.

What I would like to know is if there is a way from within the ExecutionStrategy to know if the retry attempt succeeds. Let's assume I have a MaxRetryCount of 10, but after 3 retries it was successful, I would like to know about the success.

I did look into the Execute and ExcecuteAsync methods but they are only called once so there doesn't seem to be a way to tie into them. I didn't see anything else in the ExecutionStrategy that I could leverage to be notified.

### Include provider and version information

EF Core version: 3.1.18
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Standard 2.0
Operating system:  Windows
IDE: Visual Studio 2019 16.9.12

**Comment by roji** [comment]
@chekm8 you can look at the [ExceptionsEncountered](https://github.com/dotnet/efcore/blob/main/src/EFCore/Storage/ExecutionStrategy.cs#L112) list to see all exceptions encountered so far (counting them gives you the number of previous retries).

Note that you can always implement IExecutionStrategy directly, at which point you'll be in complete control of what your strategy does.

**Comment by roji** [comment]
To know if the operation succeeded in general (with or without retries), you can override Execute and ExecuteAsync, call their base methods, and if those base methods haven't raised any exception, then the operation succeeded.

**Comment by ajcvickers** [comment]
We discussed this in triage and overriding Execute and ExecuteAsync seems like the best way to do this.
