### ISSUE TITLE
Slow DB performance with SQLite using EF Core in UWP app

### ISSUE THREAD

**Issue by Bondarenko1990** [dotnet/efcore#27365]
I have the problem with SQLite in C# UWP project. If ".Net Native Toolchain" enabled DB perfomance slowly up to 3-5 times. 

EF Core version: 3.1.8
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10 Enterprise, version: 21H2
IDE: (e.g. Visual Studio 2019 16.11.9)

**Comment by ajcvickers** [comment]
UWP is not supported.

**Comment by Bondarenko1990** [comment]
> 

uwp doesn't support what?

**Comment by ajcvickers** [comment]
@Bondarenko1990 Using EF Core in UWP applications is no longer a scenario that we support.

**Comment by Bondarenko1990** [comment]
@ajcvickers thanks for the answer. What platforms do EF Core support? WPF, Xamarin, Maui?

**Comment by roji** [comment]
@Bondarenko1990 you probably want to take a look at our [Supported .NET Implementations page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms).
