### ISSUE TITLE
Add-Migration, Update-Database etc. (EF5) not working with Visual Studio 2013 Update 5

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2736]
After I installed Update 5 for Visual Studio 2013 EF-Commands for EF5 stopped working.

The solution contains  several projects using EF5 from NuGet-repos. The following happens if you try to add a new Migration:

``` powershell
PM> Add-Migration test
Exception calling "CreateInstanceFrom" with "8" argument(s): "Could not load file or assembly 'EntityFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its 
dependencies. Das System kann die angegebene Datei nicht finden."
At C:\Source\pegasus7\packages\EntityFramework.5.0.0\tools\EntityFramework.psm1:431 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

```

I could figure out a workaround. Adding Entity Framework 5.dll to GAC will make it work, but I think this should also work without having to add EF to the GAC, else we always would have to add the assembly to the GAC even on the deployment and build system.

**Comment by rowanmiller** [comment]
Hey,

This project is for EF7, EF6.x (and EF5) are managed on http://entityframework.codeplex.com/. Given this issue relates to EF5, please open an issue on the CodePlex site. Please be sure to include a sample solution that we can use to see the issue (or steps to setup a solution that hits this issue).

~Rowan
