### ISSUE TITLE
Use update pipeline to get DML commands for HistoryRepository

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2737]
While implementing the `HistoryRepository`, I was trying to get simple `INSERT` and `DELETE` statements out of the Update pipeline. I traced it back to having to create `InternalEntityEntry` object, but that was impractical due to all its dependencies. We should look at simplifying this scenario.

Also, I needed the ability to use literals instead of parameters.

**Comment by divega** [comment]
Related to #2495.

**Comment by ajcvickers** [comment]
@AndriySvyryd @bricelam Does the work we did for seeding cover this?

**Comment by ajcvickers** [comment]
@AndriySvyryd @bricelam And if so, should we reuse it in the Migrations History table?

**Comment by ajcvickers** [comment]
Closing this as we believe the requirements are different enough that we should not try to combine.
