### ISSUE TITLE
Ef Core 5 - Many to Many Migration - Dictionary Error

### ISSUE THREAD

**Issue by paul-charlton** [dotnet/efcore#27388]
Hi,
I'm trying to add a Many-to-many relationship, following the code set out [here](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many) and I'm getting the below error:

```
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: The class Dictionary`2 was not found in the {MYCONTEXT} DbContext. The class must be either be an entity class derived from the GenericServiceDto/Async class.
```

The code I'm using on the Entities is:
```
public ICollection<CarePlanTemplateEntity> CarePlanTemplates { get; private set; }

...

public ICollection<DiscountCodeEntity> DiscountCodes { get; private set; }
```

And the Config:
```
            builder
                .HasMany(x => x.CarePlanTemplates)
                .WithMany(x => x.DiscountCodes)
                .UsingEntity(j => j.ToTable("CarePlanTemplateDiscountCodes"));
```

I've also tried the fuller configuration alternatives from that url (and leaving it to do via convention), but I get the same error every time.  I'm not sure where I'm going wrong?

EF Core version: 5.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: VS 2022 17.0.5

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by paul-charlton** [comment]
I'll try and get that as soon as - I think I was more after more information about the error messages.  I'm assuming it's something to do with how EF handles the Many to Many underneath.  I get the same error if I explicitly define the relationship as (mentioned in the url):
```
.UsingEntity<Dictionary<string, object>>(...
```

I'll get the runnable asap.

**Comment by ajcvickers** [comment]
I don't think "The class must be either be an entity class derived from the GenericServiceDto/Async class." is coming from EF.

**Comment by paul-charlton** [comment]
Aha - that may be a clue I need - thank you.

**Comment by paul-charlton** [comment]
Incase anyone else gets here - It seems to have been a problem with a nuget package GenericServices - I wasn't using this so removed and all good!
@ajcvickers  - thank you!
