### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2738]
SAMPLE
  protected override void OnModelCreating(ModelBuilder builder)
 {
            builder.Entity&lt;Empresa&gt;(entity =>
            {
                entity.Property(value => value.Endereco.TipoEndereco)
            }
}
ERROR
System.ArgumentException: The expression 'value => value.Endereco.TipoEndereco' is not a valid property expression. The expression should represent a property access: 't => t.MyProperty'.

I do not know where I can get a sample with the solution

**Comment by rowanmiller** [comment]
Hey,

It looks like you are trying to dot thru a navigation property, which is not supported. `Property` can only be used to configure properties directly defined on the type (i.e. `Property(post => post.Name)`) and not nested or referenced proeprties (i.e. `Property(post => post.Blog.Url)`).

~Rowan

**Comment by rowanmiller** [comment]
If you want to configure `TipoEndereco` then you need to configure it on the entity that it is defined on.

**Comment by ragt1975** [comment]
Thanks for the information, I will think of another solution
