### ISSUE TITLE
Slow First Query after project startup

### ISSUE THREAD

**Issue by DanVUT** [dotnet/efcore#27392]
Hi guys,

I would like to ask. We have a "problem" that causes that first query after project startup takes long to handle. First time query is handled takes several seconds let's say 2-8 seconds (depending on complexity of DbContext model). Queries after the first query are handled in expected amount of time (under 1 second depending on query complexity). After searching a little on internet I found out that this happens due to Model compilation on the first query but didn't find any solution that was for EFCore (only for Entity Framework). 

As we would like all queries to have same response no matter if it is first or 100th query in a row we would like to move this initialization process to project startup phase rather than first query. Is something like this possible? Because we have some automated testing where we measure also response times of our database services and if some service is freshly started we must run tests repeatedly because of this "issue".

Thank you in advance :) 

Entity Framework Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by NirmalaVennapusa** [comment]
Is there any solution on this area?

If yes.. could you please share the solution. I am also facing same issue for the first time to get the results it took 15 sec and second time results are getting in ms itself.

**Comment by roji** [comment]
@NirmalaVennapusa have you try the compiled models feature as above?

**Comment by NirmalaVennapusa** [comment]
> @NirmalaVennapusa have you try the compiled models feature as above?

No.. not yet. will the compiled model solve this problem? If yes will try that out

**Comment by osmangunen51** [comment]
Proje başlarken db en basit tabloya bir basit sorgu at bu async olsun

**Comment by CodingOctocat** [comment]
My database is not a large model, using `EnsureCreated` or `Add without savechange` to warm up, first query went from 2.0s to 1.7s

**Comment by roji** [comment]
@CodingOctocat EnsureCreated/Add  only warm up very specific parts of EF, the whole query pipeline notably still needs to get JITted etc. I'd suggest doing a dummy query.

**Comment by CodingOctocat** [comment]
@roji Are `await _dbContext.MyTable.FirstOrDefaultAsync();` is dummy query? The first query has been shortened to 1.5s, and it feels like the effect is minimal, am I not doing the dummy query correctly?

**Comment by roji** [comment]
@CodingOctocat well the best thing would obviously be to "warm up" the exact query which you want to go fast; but otherwise any query should reasonably improve things. 1.5s after a query does sound like a lot, but I'd need a proper repro to be able to say anything more.

**Comment by CodingOctocat** [comment]
@roji I think I may have misunderstood what is in #15568 `context.Model` and `context.MyTable` are not the same, also, on my other computer, the first query without warm-up is as fast as 1s and after warm-up 0.7s (same program), maybe my database is not the same, anyway, #15568's solution is worth a try.
