### ISSUE TITLE
How to map private/protected properties as well?

### ISSUE THREAD

**Issue by drauch** [dotnet/efcore#27400]
How to map private/protected properties as well?

In EF6 we used a model convention for this, but they doesn't seem to exist anymore in EF Core.

**Comment by ErikEJ** [comment]
Maybe this? https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations

**Comment by AndriySvyryd** [comment]
The public convention are planned for 7.0 https://github.com/dotnet/efcore/issues/214
