### ISSUE TITLE
Sorting of navigation properties - InMemoryDatabase

### ISSUE THREAD

**Issue by bamancio-futura** [dotnet/efcore#27415]
The feature implemented in https://github.com/dotnet/efcore/issues/15171 is not supported by `Microsoft.EntityFrameworkCore.InMemory`, ie. children aren't sorted. It works as expected in `Pomelo.EntityFrameworkCore.MySql`. The feature added the possibility to include children structures and order them. Like below:

```C#
public class Model {
    public Guid Id {get; set;} = Guid.Empty;
    public string YourProperty {get; set; } = "";
    public IEnumerable<Model> Children {get; set; } = new List<Model>();
}
```
```C#
var modelId = new Guid("<existing model id>");
var results = await DbSet<Model>.Where(t => t.Id == modelId)
                                .Include(t => t.Children.OrderBy(child => child.YourProperty))
                                .ToListAsync(cancellationToken);
```

### Provider and version information

`Microsoft.EntityFrameworkCore` version: 6.0.1
`Microsoft.EntityFrameworkCore.InMemory` version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 6.0
Operating system: Windows/Unix
IDE: Irrelevant

**Comment by AndriySvyryd** [comment]
Please provide your model or, even better, a small repro project.

**Comment by bamancio-futura** [comment]
Updated example with model.

**Comment by AndriySvyryd** [comment]
Unfortunately we can't repro the behavior you are seeing.

<details>
<summary>Code used</summary>

```C#
var model = new Model()
{
    Children = new[]
    {
        new Model{ YourProperty = "2"},
        new Model{ YourProperty = "1"},
        new Model{ YourProperty = "3"},
    }
};

using (var context = new MyContext())
{
    context.Add(model);
    context.SaveChanges();
}

using (var context = new MyContext())
{
    var results = context.Set<Model>().Where(t => t.Id == model.Id)
                    .Include(t => t.Children.OrderBy(child => child.YourProperty))
                    .ToList();

    Assert.Equal(
        model.Children.OrderBy(child => child.YourProperty).Select(c => c.YourProperty),
        results.Single().Children.Select(c => c.YourProperty));
}
```

</details>

**Comment by bamancio-futura** [comment]
I've noticed it fails when a single instance of `DBContext` is used to save and query the data. A sample project can be found in https://github.com/bamancio-futura/DotNet.EFCore.Issues.Number27415.Tests

Note Test_002 in `ModelTests.cs` fails because it uses a single instances of `ModelContext` while Test_001 is successful with .

**Comment by ajcvickers** [comment]
@bamancio-futura This is by-design. Since the entities are already tracked by the context instance they are not created, and navigations are not populated, by the query. Therefore the order remains unchanged. It is best practice to use a new DbContext instance for each unit-of-work. In this case, the test setup is conceptually a different unit-of-work from the test execution.

**Comment by bamancio-futura** [comment]
I see. For my unit test it indeed does not make much sense, since I am simply testing that the query works. That might not be true in real-case scenarios, though. I mean, I can imagine people saving the data in an unorderly fashion and querying the structure in the same unit of work. 

So it is designed so that the save and query operations  (to the same structure) **must** not be executed in the same unit of work?

**Comment by ajcvickers** [comment]
> So it is designed so that the save and query operations (to the same structure) must not be executed in the same unit of work?

No, but entity instances that are already tracked in a unit-of-work are not replaced/updated by anything from the database.

**Comment by bamancio-futura** [comment]
Understood. Thank you for your time and effort.
