### ISSUE TITLE
ASP.Net core  x86 application

### ISSUE THREAD

**Issue by NickSx9** [dotnet/efcore#27414]
Hello, 
I'm very new to Docker, I have been asked to make a Dockerized version of a pre-existing WPF app.

The application uses 
C# Assembly.LoadFrom() to get details from different .dll's
these .dll's HAVE to be built in x86 architecture.

For this reason, I need to find away of either converting those x86 dll's to 64bit   (Which google says is not possible)
or building my Docker ASP.Net core app in x86 to make it compatible.

I have tried to do this with a few different combinations of 'build/base' dotnet core images - but I have had no luck.
Google - (well, stackoverflow) mentioned there are a few ways this can be done inside docker, but requires some 'hacking' :(

The Dockerfile is pretty standard

_FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base            # tried changing this multiple times
WORKDIR /app
RUN apt-get update && apt-get install -y nuget                   # this is added because i make a dynamic nuget install inside the app.
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build                  # tried changing this multiple times.
WORKDIR /src
COPY ["./myApp.csproj", "."]
RUN dotnet restore "myApp.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "myApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "myApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "myApp.dll"]_

Any advice would be gratefully received.

Thanks.

**Comment by roji** [comment]
@NickSx9 EF Core consists of pure managed assemblies, without any native code, and as such are neither x86 nor x64 (but can be used on either).

It's not clear exactly what problem you're running against or how it's related to EF Core. If you're new to Docker, I'd recommend first making things work (build, run) without Docker; at that point, packaging and making things run inside Docker should be less problematic.

**Comment by NickSx9** [comment]
@roji  my application will run, build and compile fine (when it targets *AnyCPU* inside a docker container using the above dockerfile) 
but the application will fail when the Assembly.LoadFrom() code is hit. 
After debugging and lots of headbanging, I found that the dll's being called are created in x86 - which means Assembly in x64 *AnyCPU* won't read them. (or so it would seem)
When I debugged the same code in x84 (not inside a container) the application worked fine.

The error code inside the docker log is something like *BadImage Format Exception* - and after some digging, I found some reference to x86 not being supported with the base/build images above.

thus, the reason for my question.

**Comment by roji** [comment]
Are you able to reproduce the error without docker? I'd definitely look at that first. Either way, we're going to need a minimal code sample which reproduces the problem in order to understand exactly what's going on.

**Comment by NickSx9** [comment]
@roji So, the Error message inside the Docker log; when my application target build architecture is x86  
says  
"Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/app/MyApp.dll'. An attempt was made to load a program with an incorrect format.
File name: '/app/MyApp.dll'"

If I target the build for AnyCpu - it will compile fine, but the code hits a try/catch exception 
try
{
 assembly = Assembly.LoadFrom(filePath);                     <- file path links to x86 built test dll's
}

**Comment by roji** [comment]
@NickSx9 as I wrote above, I really advise trying to work on this outside of Docker first.

Regardless, this is unlikely to be related to EF Core, which is just a managed .NET library like most others. In any case, if you're seeing an EF Core-specific problem, we're going to need a sample project/repro in order to investigate.
