### ISSUE TITLE
Is it by design for In-Memory provider that BeingTransactionAsync returns value, but Database.CurrentTransaction stays null?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#27420]
Is it by design for In-Memory provider that BeingTransactionAsync returns value, but Database.CurrentTransaction stays null?

I saw the warning that in-memory provider does not support fair transactions, but I am surprised that

```
_transaction = await _dbContext.Database.BeginTransactionAsync(IsolationLevel.Snapshot, cancellationToken);
```
Initializes `_transaction` with proper value, but `_dbContext.Database.CurrentTransaction` stays null after the call.

![image](https://user-images.githubusercontent.com/9202028/153350465-11ba683f-7d0f-4138-9dc7-d0f053700355.png)

Is it a bug or expected behavior?

EF Core version: 6
Database provider: In-memory database
Target framework:  .NET 6.0
IDE: Visual Studio 2022 17.0.6

**Comment by roji** [comment]
@voroninp InMemory doesn't implement any sort of transaction support - the call to BeginTransactionAsync is currently simply a no-op, so CurrentTransaction isn't set. We generally recommend against using InMemory for writing tests, as it doesn't behave like a real database in many ways.

**Comment by voroninp** [comment]
@roji , Yeah, but how can I mock `DatabaseFacade`? Its constructor requires the instance of DbContext. And if latter is mocked, facade throws =(

**Comment by voroninp** [comment]
DbFacade complains about provider, when I do this.  I guess, I need to mock more DbContext behaviors.

**Comment by AndriySvyryd** [comment]
@voroninp If your application depends on a transaction being present we suggest testing with a relational provider
see [docs](https://docs.microsoft.com/en-us/ef/core/testing/) and [video](https://www.youtube.com/watch?v=KO2aFuLqGkc)
