### ISSUE TITLE
Renaming and dropping columns with Temporal Tables generates faulty migration

### ISSUE THREAD

**Issue by zengouu** [dotnet/efcore#27423]
Renaming and dropping columns in the same migration when using EF Core 6 supported Temporal Tables results in non-working migration syntax. Ordering of drop and rename (see code below) results in following error:

> Setting SYSTEM_VERSIONING to ON failed because column 'RemovedTS' at ordinal 6 in history table 'history.GeneralVendorContact' has a different name than the column 'EndedTS' at the same ordinal in table 'prc.GeneralVendorContact'.

```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsRemoved",
                schema: "prc",
                table: "GeneralVendorContact")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "GeneralVendorContact")
                .Annotation("SqlServer:TemporalHistoryTableSchema", "history");

            migrationBuilder.RenameColumn(
                name: "RemovedTS",
                schema: "prc",
                table: "GeneralVendorContact",
                newName: "EndedTS");

            migrationBuilder.RenameColumn(
                name: "RemovedByUserId",
                schema: "prc",
                table: "GeneralVendorContact",
                newName: "EndedByUserId");
        }
```

This can be fixed by manually editing the generated Up() method and switching the migration to first rename and then drop columns, as follows:

```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "RemovedTS",
                schema: "prc",
                table: "GeneralVendorContact",
                newName: "EndedTS");

            migrationBuilder.RenameColumn(
                name: "RemovedByUserId",
                schema: "prc",
                table: "GeneralVendorContact",
                newName: "EndedByUserId");

            migrationBuilder.DropColumn(
		    name: "IsRemoved",
		    schema: "prc",
		    table: "GeneralVendorContact")
	            .Annotation("SqlServer:IsTemporal", true)
	            .Annotation("SqlServer:TemporalHistoryTableName", "GeneralVendorContact")
	            .Annotation("SqlServer:TemporalHistoryTableSchema", "history");
        }
```

### Versions used

EF Core version: 6.0.1 (all ef related packages @ version 6.0.1)
Database provider: Microsoft.EntityFrameworkCore.SqlServer (6.0.1)
Target framework: NET 6.0
Operating system: Microsoft Windows 11 Pro, Version 10.0.22000 Build 22000
IDE: Microsoft Visual Studio 2022 (64bit) 17.0.6

**Comment by maumar** [comment]
problem is that when we drop column from the history table we need to disable versioning (and drop columns in both tables separately). However, since we have disabled the period, renaming also needs to happen for both tables now and we don't do it. So the column is only renamed for the temporal table and the name in history table stays the same. When we try to switch versioning back on the exception is thrown. We need to flow the information to RenameColumnOperation that the column is part of temporal table, and if that table had it's versioning disabled we need to mirror the operation to the history table also.
