### ISSUE TITLE
dbcontext scaffold parameter "-use-database-name" still changes generated entity class names  

### ISSUE THREAD

**Issue by KaiWesterschwiensterdt** [dotnet/efcore#27430]
### description

1. database table name:
 - Users
 - States
 - User_States

2. command:
```JS
dotnet ef dbcontext scaffold "Data Source=myServer; Initial Catalog=myTable; User ID=myUsername; Password=myPassword; MultipleActiveResultSets=true;" Microsoft.EntityFrameworkCore.SqlServer --context-dir Databases --output-dir Models --data-annotations --use-database-names
```

3 .model name:
 - User
 - State
 - User_State

4. dbset names in context file
 - Users
 - States
 - User_States

### problem
The name of the entity class is renamed to the singular form. This is to be avoided.

### provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system:
IDE: Visual Studio 2022 17.0.5

**Comment by ErikEJ** [comment]
Have you tried adding

    --no-pluralize

**Comment by KaiWesterschwiensterdt** [comment]
fixed the problem.

**Comment by KaiWesterschwiensterdt** [comment]
Thank you, this fixed the problem. I thought no-pluralize does exactly what it names is, it just don't pluralize the dbset names.
