### ISSUE TITLE
EFCore how to dynamic specific table name

### ISSUE THREAD

**Issue by xiaodongcool** [dotnet/efcore#27434]
such as
```cs
Db.Set<User>().SetTableName("User_1").Find(123);
```

or

```cs
// cover default table name
Db.Set<User>().SetTableName("User_1");
Db.Set<School>().SetTableName("School_1");

// always read  table User_1
Db.User.Find(123);
```

**Comment by ajcvickers** [comment]
@jyller EF Core works with a defined metadata model that maps .NET types to database tables. See [Creating a model](https://docs.microsoft.com/en-us/ef/core/modeling/) and [Table name](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#table-name). The table that a type is mapped to cannot be changed dynamically.

**Comment by jyller** [comment]
so how to split table ?  @ajcvickers

**Comment by ralmsdeveloper** [comment]
Hello @jyller 

Take a look at this documentation here:
https://docs.microsoft.com/pt-br/ef/core/modeling/inheritance

**Comment by ajcvickers** [comment]
@jyller Can you be more specific about what you mean by "split table"?

**Comment by jyller** [comment]
@ajcvickers  
I can choose which tables I want to operate on based on any custom criteria ， such as

```
if(user.Gender == Gender.Male)
{
    db.Set<User>().SetTableName("user_male").Add(user);
}
else
{
    db.Set<User>().SetTableName("user_female").Add(user);
}
```

**Comment by xuejmnet** [comment]
i have a sharding project for efcore,[ShardingCore](https://github.com/dotnetcore/sharding-core) that is very easy to sharding table and sharding data source，u should create route to support any business rule,  like sharding by day,month,day,mod,like sharding-jdbc in java,i think u will like this project [ShardingCore](https://github.com/dotnetcore/sharding-core)

**Comment by xuejmnet** [comment]
@jyller it's a sharding plugin for efcore

**Comment by ajcvickers** [comment]
@jyller Not sure if this is what you are looking for, but you can re-use the same CLR type with mappings to different tables:

```C#
modelBuilder.SharedTypeEntity<User>("Male").ToTable("usr_male");
modelBuilder.SharedTypeEntity<User>("Female").ToTable("usr_female");
```

Here's a full example:

```C#
public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.SharedTypeEntity<User>("Male").ToTable("usr_male");
        modelBuilder.SharedTypeEntity<User>("Female").ToTable("usr_female");
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Set<User>("Male").Add(new User {Name = "John"});
            context.Set<User>("Female").Add(new User {Name = "Mary"});
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            Console.WriteLine(context.Set<User>("Male").Single().Name);
            Console.WriteLine(context.Set<User>("Female").Single().Name);
        }
    }
}
```

**Comment by LucaZiegler** [comment]
Not working:

{"Cannot create a DbSet for 'XXX' because this type is not included in the model for the context."}

**Comment by LucaZiegler** [comment]
And when added to DbContext:

Cannot create a DbSet for 'Project.DataModels.Data.Value' because this type is not included in the model for the context. However the model contains an entity type with the same name in a different namespace: 'Project.DataModels.Data.Value'.

**Comment by roji** [comment]
@LucaZiegler please open a new issue with a minimal, runnable code sample.
