### ISSUE TITLE
Should Migrations create Indexes for BOTH properties of a M2M Skip Navigation Join Entity

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#27445]
## Ask a question

I have two simple entities in a skip navigation many to many relationships.
Migrations creates the join table and FK constraints but only creates an index for ONE of the FK properties on the join.

### Include your code

```C#
public class Artist
{
    public int ArtistId { get; set; }
    public string FirstName { get; set;}
    public string LastName { get; set;}
    public List<Cover> Covers { get; set; }
}
  public class Cover
  {
      public int CoverId { get; set; }
      public string DesignIdeas { get; set; }
      public bool DigitalOnly { get; set; }
      public List<Artist> Artists { get; set; }
  }

```
I ahve DbSets for both in my context.

Migration file creates the join table and FK's as expected but only one index on one of the FK's in the join table
 
 ```
 migrationBuilder.CreateTable(
                name: "ArtistCover",
                columns: table => new
                {
                    ArtistsArtistId = table.Column<int>(type: "int", nullable: false),
                    CoversCoverId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ArtistCover", x => new { x.ArtistsArtistId, x.CoversCoverId });
                    table.ForeignKey(
                        name: "FK_ArtistCover_Artists_ArtistsArtistId",
                        column: x => x.ArtistsArtistId,
                        principalTable: "Artists",
                        principalColumn: "ArtistId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ArtistCover_Covers_CoversCoverId",
                        column: x => x.CoversCoverId,
                        principalTable: "Covers",
                        principalColumn: "CoverId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ArtistCover_CoversCoverId",
                table: "ArtistCover",
                column: "CoversCoverId");
        }
```
I asked some SMART DBAs if there's a perf or other reason and then checked with @bricelam who said it might just be a bug and there should be indexes on both and was tagging @AndriySvyryd . 

Thanks!

### Include provider and version information

EF Core version: 6.02
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: windows 10
IDE: Visual Studio 2022

**Comment by AndriySvyryd** [comment]
An explicit index is not needed as `ArtistsArtistId` is already covered by the PK `ArtistsArtistId, CoversCoverId`. Due to the way composite PKs and indexes are implemented `CoversCoverId` by itself is not covered and thus does need another index.

**Comment by julielerman** [comment]
Thanks so much

**Comment by ErikEJ** [comment]
Maybe one could argue that this should include both columns, and be a unique index? 

CoversCoverId, ArtistsArtistId

migrationBuilder.CreateIndex(
               name: "IX_ArtistCover_CoversCoverId",
               table: "ArtistCover",
               column: "CoversCoverId");

**Comment by AndriySvyryd** [comment]
@ErikEJ That would make the index use more resources, but wouldn't improve any query that EF generates
