### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by xbaha** [dotnet/efcore#27449]
I am unable to catch errors when the DNS is not resolved, and the retry policy is not working in this case.
To reproduce, just unplug the Internet Connection at the try block.
I would expect the normal behavior to be caught by my try-catch block when the connection goes down.

```C#
                optionsBuilder.UseSqlServer(ConnectionString,
                    options => options.EnableRetryOnFailure(
                        maxRetryCount: 10,
                        maxRetryDelay: TimeSpan.FromSeconds(30),
                        errorNumbersToAdd: null
                        ));
```

Code:
```
var school = azureContext.RemoteSchool.ToList();
school.FirstOrDefault().city = "boba3";


bool saveFailed;
do
{
    saveFailed = false;
    try
    {
        azureContext.SaveChanges();
    }
    catch (DbUpdateConcurrencyException ex)
    {
        saveFailed = true;
        ex.Entries.Single().Reload();
    }

} while (saveFailed);
```

The Errors are below at the line azureContext.SaveChanges();

```
SqlException: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The semaphore timeout period has expired.)
```
```
System.InvalidOperationException: 'An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.'
```

### Version Information

EF Core version: EF6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework:  .NET 6.0
Operating system: Win10
IDE: Visual Studio 2021

**Comment by ajcvickers** [comment]
@xbaha Can you explain a bit more why you expect a "DbUpdateConcurrencyException" in this case?

**Comment by xbaha** [comment]
I just searched the error I had, and found the example for infinite retry policy from the doc here: 
https://docs.microsoft.com/en-us/ef/ef6/saving/concurrency
Then added EnableRetryOnFailure from other docs. which it seems that it doesn't work in my situation because the error happens around 15 seconds after stepping over SaveChanges()

I am running a console app that needs to write to Azure SQL every xx minutes, so when such an error occurs, I had to rerun the application all over again. 

What exception should I have for connections errors, like unresolved DNS?

And by the way, I had a Continue when unhandled in user code on the exception "System.InvalidOperationException" but the debugger stops.

**Comment by xbaha** [comment]
I just searched the error I had, and found the example for infinite retry policy from the doc here: 
https://docs.microsoft.com/en-us/ef/ef6/saving/concurrency
Then added EnableRetryOnFailure from other docs. which it seems that it doesn't work in my situation because the error happens around 15 seconds after stepping over SaveChanges()

I am running a console app that needs to write to Azure SQL every xx minutes, so when such an error occurs, I had to rerun the application all over again. 

What exception should I have for connections errors, like unresolved DNS?

And by the way, I had a Continue when unhandled in user code on the exception "System.InvalidOperationException" but the debugger stops.

**Comment by ajcvickers** [comment]
@xbaha A few things:

- The documentation you reference is for EF6, but you are using EF Core 6.0. Make sure to look in the [EF Core docs](https://docs.microsoft.com/en-us/ef/core/).
- DbUpdateConcurrencyException is specifically designed to handle [optimistic concurrency](https://docs.microsoft.com/en-us/ef/core/saving/concurrency). What you are describing is not related to this.
- [Connection resiliency](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) is intended for recovery from short-lived transient errors. It's not clear to me that you situation is really this. However, if you want to use it and the exception is not already covered, then you can [extend the resiliency to handle it](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.executionstrategy.shouldretryon?view=efcore-6.0) and [increase the timeout/retries](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.executionstrategy.-ctor?view=efcore-6.0#microsoft-entityframeworkcore-storage-executionstrategy-ctor(microsoft-entityframeworkcore-dbcontext-system-int32-system-timespan)) appropriately.
