### ISSUE TITLE
How to customize IMemoryCache service options

### ISSUE THREAD

**Issue by viktorz** [dotnet/efcore#27458]
## How to customize IMemoryCache service options

I am building a WorkerRole server application using EF Core 3.1.21 and .Net Framework 4.7.2 targeting Azure SQL database(s).
The application uses some kind of multi-tenancy for client data by utilizing different SQL Server Schemas for each tenant. The entity models for the tenants are 95% the same in terms of entities and properties, may use same or different connection string, and always use different schema name for all database objects in the model.  

In production we have about 300 active tenants, with peaks up to 1300 at some points.
Unfortunately the default `IMemoryCache` service component that is build out of the box has insufficient cache size (`Size = 10240`) as per [EntityFrameworkServiceBuilder line 262](https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs#L262)). We are very quickly maxing it with about 15 SqlServerCompiledQuery cache items, 13 Command cache items and 97 IModel cache items.
We are using a separate Microsoft Unity-based dependency container for managing application services so EF Core is the only one relying on `IServiceCollection` dependency injection approach.

### Further details
I have implemented custom `IModelCacheKeyFactory` like this:
```C#
public sealed class MultiTenantModelCacheKeyFactory : IModelCacheKeyFactory
{
    public object Create(DbContext context)
    {
        if (context is TenantEfContext clientContext)
        {
                return $"{clientContext.TenantId}@{nameof(TenantEfContext)}";
        }
        return context.GetType().Name;
    }
}
```

I have implemented custom `ModelSource` that support removal of tenant models once they are no longer needed:
```C#
public sealed class EvictableModelSource : ModelSource
{
    public EvictableModelSource(ModelSourceDependencies dependencies)
        : base(dependencies)
    {
    }

    public void RemoveModel(DbContext context)
    {
        var modelsCache = this.Dependencies.MemoryCache;

        var cacheKey = this.Dependencies.ModelCacheKeyFactory.Create(context);
        modelsCache.Remove(cacheKey);
    }
}
```

### Provider and version information

EF Core version: 3.1.21
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Framework 4.7.2
Operating system: Windows Server 2019
IDE: Visual Studio 2022 17.0.6

**Comment by viktorz** [comment]
I am digging further into the memory consumption of my multi-tenant implementation and I am staring to believe that handling `IModel` cache is only one of the many concerns that I have to deal with.  
A memory dump surprised me with a 3 GB `ConcurrentDictionary` in `KeyValueIndexFactorySource` component and I wonder what are the other places where something is cached for reuse, but not removed once the respective tenant model is evicted.

**I am starting to explore the option to create and manage manually separate `IServiceCollection` instances for each tenant, but I will greatly appreciate some advice whether this is a good idea and how to do it safely.**

**Comment by viktorz** [comment]
@ajcvickers Thank you. 
I have already started a spike using `UseInternalServiceProvider()`.
I have two options for creating the DbContext instance and I ask you for guidance which one would be better as the documentation and samples for this scenario are scarce.
```C#
IServiceCollection tenantInfrastructure = tenantInfrastructureFactory.GetTenantInfrastructure(tenantId);

IServiceProvider serviceProvider = tenantInfrastructure.BuildServiceProvider();

// Option1: requires "tenantId" to be registered as Service in the serviceProvider so the value is passed to ctor
// assuming there is ctor like this
// public EfContext(DbContextOptions<EfContext> options, string tenantId) : base(options) {...}
var context1 = serviceProvider.GetService<EfContext>();

// Option2: calls directly the ctor
// assuming there is ctor like this
// public EfContext(IServiceProvider serviceProvider, string tenantId) : base() {...}
var context2 = new EfContext(serviceProvider, tenantId);
```
Code for `tenantInfrastructureFactory.GetTenantInfrastucture(tenantId)`:
```C#
serviceCollection = new ServiceCollection();

serviceCollection.AddEntityFrameworkSqlServer();

serviceCollection.AddDbContext<EfContext>(
    (IServiceProvider serviceProvider, DbContextOptionsBuilder optionsBuilder) =>
        optionsBuilder.UseSqlServer(connectionString)
                      .UseInternalServiceProvider(serviceProvider)
                      // TODO: set more options here,
    contextLifetime: ServiceLifetime.Transient,
    optionsLifetime: ServiceLifetime.Singleton
    );

// required for Option1 from above code snippet, otherwise will be avoided
serviceCollection.AddSingleton<string>(tenantId);
```

If you have some test in the repository that show how to manage the internal provider and use like some kind of isolation, please give me some pointers so I can explore them and avoid taking your time.

**Comment by ajcvickers** [comment]
@viktorz If your application architecture is based around D.I., then I would probably stick with that and use option 1. However, I don't think one option is fundamentally better than the other.

> If you have some test in the repository that show how to manage the internal provider and use like some kind of isolation

I don't think there is anything like this. Managing service providers like this for extremely dense multitenancy is a pretty advanced scenario. I would be interested to find out if you make this work successfully. I suspect it will only be effective if many tenants are used, but each is only used infrequently, since if a tenant is frequently evicted from the cache, but then it is immediately loaded again it will likely cause the whole system to thrash.

**Comment by ajcvickers** [comment]
@viktorz Glad you got it working. This was something that was not possible with EF6, which had many unloadable caches. We explicitly tried to make it possible with EF Core even though it is not a common request, so it's great to see it working.
