### ISSUE TITLE
Create a migration failed with PowerShell command in PMC

### ISSUE THREAD

**Issue by mm-ryo** [dotnet/efcore#27457]
Hi,

When I try to create a migration in Visual Studio PMC with the command 'Add-Migration'. It seems the ef-core tool tries to start our app and waits until the web host return timeout.
We just upgraded the framework to .net6 and vs2022 to v17.1.0. Before the upgrade, both commands are working fine.

```PowerShell
Add-Migration Test1 -Project DAL\EF\Migrations -Context TestContext
```
Logs:
![image](https://user-images.githubusercontent.com/1568013/154282899-fecf1455-5ff3-4080-93bc-3c1cde931de9.png)

But it works if using the ef-core CLI command. it didn't start our app.

```CMD
dotnet ef migrations add Test1 --project DAL\EF\Migrations --context TestContext
```
![image](https://user-images.githubusercontent.com/1568013/154286503-af3a1fb6-4494-4d47-b58b-f25069ec8bda.png)

### Include provider and version information

EF Core version: efcore 6.0.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET6
Operating system: Windows 10
IDE: VS2022 17.1.0

**Comment by robinNode** [comment]
I just tested following steps. it seems working fine.
1. In VS2022 and to set other project which there is no entry point method as a startup project 
2. run 'Add-migration' command

It is obvious that there are some changes in 'Add-Migration'
