### ISSUE TITLE
Is it possible to save only some properties?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#27462]
I have an edit page for one of my entities. However, want to exclude one column from the update query.

I tried the following code based on an answer I found online.

```cs
var entity = DbContext.Entry(facility);
entity.Property(f => f.NextTruckBol).IsModified = false;
DbContext.SaveChanges();
```

But the column is still updated.

Is this no longer supported? And is there any way to accomplish this?

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.0.6

**Comment by roji** [comment]
The above code does work for me - I can see the column not getting updated. Given the following code (see full sample below):

```c#
var blog = await ctx.Blogs.SingleAsync();
blog.Prop1 = "changed";
blog.Prop2 = "changed";
ctx.Entry(blog).Property(b => b.Prop2).IsModified = false;
await ctx.SaveChangesAsync();
```

EF Core generates the following SQL (note that Prop2 is not updated):

```sql
UPDATE [Blogs] SET [Prop1] = @p0
WHERE [Id] = @p1;
SELECT @@ROWCOUNT;
```

If you're still having trouble, please send a full code sample or tweak the below to show the problem.

<details>
<summary>Full attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var blog = await ctx.Blogs.SingleAsync();
blog.Prop1 = "changed";
blog.Prop2 = "changed";
ctx.Entry(blog).Property(b => b.Prop2).IsModified = false;
await ctx.SaveChangesAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Blog>().HasData(new Blog { Id = 1, Prop1 = "Unchanged", Prop2 = "Unchanged" });
}

public class Blog
{
    public int Id { get; set; }
    public string Prop1 { get; set; }
    public string Prop2 { get; set; }
}
```

</details>

**Comment by SoftCircuits** [comment]
> The above code does work for me

My apologies. I was able to get this to work. Excellent!

Thanks!
