### ISSUE TITLE
Writing from an overriden property causes unexpected behavior.

### ISSUE THREAD

**Issue by agreentejada** [dotnet/efcore#27476]
## File a bug

I was experimenting around EF Core for storing log events of information when I came across this issue.

These are the relevant entities.
```C#
public abstract class TestEvent
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Time { get; set; }

        [MaxLength(50)]
        public virtual string Type { get; set; }

        public virtual string Content { get; set; }
    }

    public class FileUploadData
    {
        public string Filename { get; set; }
        public string UploadUrl { get; set; }
    }

    public class FileUploadEvent : TestEvent
    {
        public override string Type => "FileUploaded";
        public override string Content 
        { 
            get => JsonSerializer.Serialize(Data); 
            set => Data = JsonSerializer.Deserialize<FileUploadData>(value); 
        }

        [NotMapped]
        public FileUploadData Data { get; set; }
    }
```
``` C#
public class ApplicationDbContext : IdentityDbContext<AppUser>
{
      // Extraneous DbSets...
     public DbSet<TestEvent> TestEvents {get; set;}
}

protected override void OnModelCreating(ModelBuilder builder)
{
     // Initialization for other things...
     builder.Entity<FileUploadEvent>().HasBaseType<TestEvent>();
}
```

Here is the test case.
``` C#
        [Fact]
        public void WriteTestEvents()
        {
            using (var testContext = new ApplicationDbContext(ServerOptions))
            {
                var uploadEvent = new FileUploadEvent()
                {
                    Data = new FileUploadData()
                    {
                        Filename = "TEST FILE",
                        UploadUrl = "www.google.com"
                    },
                    Time = DateTime.UtcNow,
                };

                Log.Information(uploadEvent.Content);
                testContext.TestEvents.Add(uploadEvent);
                Log.Information(uploadEvent.Content);
                testContext.SaveChanges();
            }
        }
```

Expected Behavior:
The `FileUploadEvent` will be saved as a row in `TestEvents`, with the Content cell having a JSON representation of `FileUploadData Data`.

|Id | Time | Type | Content|
|--- | -----------------------------------|--------------|--------------------------------------------------------------|
|1 | 2022-02-19 03:20:01.9696746 | FileUploaded | {"Filename":"TEST FILE","UploadUrl":"www.google.com"}|	

Actual Behavior :
|Id | Time | Type | Content|
|--- | -----------------------------------|--------------|--------------------------------------------------------------|
| 1 | 2022-02-19 03:20:01.9696746 | FileUploadEvent | NULL	|

I've also recorded the logging output from this unit test, if it will help.
```
19:55:50 [INF] info: 2/18/2022 19:55:50.056 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "type" = 'table' AND "rootpage" IS NOT NULL;
19:55:50 [INF] {"Filename":"TEST FILE","UploadUrl":"www.google.com"}
19:55:50 [INF] {"Filename":"TEST FILE","UploadUrl":"www.google.com"}
19:55:50 [INF] info: 2/18/2022 19:55:50.186 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (2ms) [Parameters=[@p0=NULL, @p1='FileUploadEvent' (Nullable = false) (Size = 15), @p2='2022-02-19T03:55:50.0677214Z' (DbType = String), @p3=NULL], CommandType='Text', CommandTimeout='30']
      INSERT INTO "TestEvents" ("Content", "Discriminator", "Time", "Type")
      VALUES (@p0, @p1, @p2, @p3);
      SELECT "Id"
      FROM "TestEvents"
      WHERE changes() = 1 AND "rowid" = last_insert_rowid();
```

EF Core version: 5.0.13
Database provider: Microsoft.EntityFrameworkCore.Sqlite, vrs 5.0.13
Target framework: .NET 5.0 on UnitTests, with data library as .NET Standard 2.1
Operating system:
IDE: Visual Studio 2019 Latest Version

**Comment by roji** [comment]
@agreentejada in the above code sample, you seem to be populating the Data property on FileUploadEvent, but that property has the [NotMapped] attribute, so EF Core ignores it. The Content property on TestEvent is indeed mapped (and so there's a column in the database), but you don't seem to be setting it anywhere, so it's NULL in the database.

If you're still having difficulties, please submit a full, runnable code sample rather than snippets, and we can try to help further.

**Comment by agreentejada** [comment]
@roji , I thought that this was the issue too, until I noticed that the Content property does get filled in the Unit Tests.

If you take a look at this code segment:
```C#
Log.Information(uploadEvent.Content);
testContext.TestEvents.Add(uploadEvent);
Log.Information(uploadEvent.Content);
```

and the Log statement.

```
19:55:50 [INF] {"Filename":"TEST FILE","UploadUrl":"www.google.com"}
19:55:50 [INF] {"Filename":"TEST FILE","UploadUrl":"www.google.com"}
```

You'll notice that Content is being filled in until .SaveChanges() is applied.

EDIT: After some testing, I forget that I had added and removed the ``` builder.Entity<TestEvent>().HasDiscriminator(X => X.Type); ``` section in ```ApplicationDBContext```. This changes the actual results to...

| Id | Time | Type | Content | Discriminator |
| -- | -- | -- | -- | -- |
| 1 | 2022-02-19 03:20:01.9696746 | NULL | NULL | FileUploadEvent |

which means that
```C#
public override string Type => "FileUploaded";
```

isn't being responded to. Does EF Core have any written guidance for `override` properties?

**Comment by agreentejada** [comment]
@roji , as per your advice, I've also created a console application that logs the issue. Please run this, https://github.com/agreentejada/EFCoreOverride/tree/master.

**Comment by ajcvickers** [comment]
@agreentejada The issue here is that EF Core reads and writes directly from backing fields by default. So, since the property 	`Content` has a backing field inherited from the base class, EF is reading and writing from this. But the overridden property ignores the backing field, and hence it is always null.

You might want to consider if this is a good design--having a backing field in a base class that is never used is unusual. It would be more common to define the base class properties as abstract:

```C#
        [MaxLength(50)]
        public abstract string Type { get; set; }

        public abstract string Content { get; set; }

```

And override them:

```C#
        public override string Type
        {
            get => "FileUploaded";
            set {}
        }

        public override string Content
        {
            get => JsonSerializer.Serialize(Data);
            set => Data = JsonSerializer.Deserialize<FileUploadData>(value);
        }
```

This will then work out-of-the-box with EF Core. Nevertheless, if you want to keep the design this way, then you can tell EF to always use property access, rather than the backing field:

```C#
builder.UsePropertyAccessMode(PropertyAccessMode.Property);
```
