### ISSUE TITLE
Shadow key property not known error after property set by value generator

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/efcore#27472]
I have a [sample project to reproduce the issue](https://github.com/AndrewTriesToCode/ShadowKeyTest). The  unit test will see an exception `System.InvalidOperationException The value of shadow key property 'MyEntity.ShadowKey' is unknown when attempting to save changes.` Although the value should be known because I have a value generator in place and the debugger confirms it is used prior to the error.

Also tested for .NET Core 3.1 and .NET 5.0 -- similar error but slightly different wording.

This issue seems similar to https://github.com/dotnet/efcore/issues/26330 but this isn't an owned entity situation.

Thanks!

The entity:
```cs
public class MyEntity
{
    public int Key1;
}
```

The DbContext:
```cs
public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<MyEntity> MyEntity { get; set; }
    public string ShadowKeyValueOnGenerate { get; set; } = "";

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>().Property<string?>("ShadowKey").HasValueGenerator<ShadowKeyGenerator>();
        modelBuilder.Entity<MyEntity>().HasKey("Key1", "ShadowKey");
    }
}
```

Te value generator:
```cs
public class ShadowKeyGenerator : ValueGenerator<string?>
{
    public override string? Next(EntityEntry entry)
    {
        // This runs right before the error saying the value isn't known...
        return ((MyDbContext)entry.Context).ShadowKeyValueOnGenerate;
    }

    public override bool GeneratesTemporaryValues => false;
}
```

The test:
```cs
[Fact]
public void RemoveFreshlyAttachedEntry()
{
    var context = new MyDbContext(_options);
    context.ShadowKeyValueOnGenerate = "value1";
    
    var entity1 = new MyEntity { Key1 = 1 };
    
    // Error here that the shadow key property isn't known although the generator has provided the value...
    context.Remove(entity1);
    
    context.SaveChanges();
    
    Assert.Empty(context.MyEntity.ToList());
}
```

**Comment by ajcvickers** [comment]
@AndrewTriesToCode Currently value generators are only run when entities are put in the `Added` state--usually when `Add` is called. They are not run when `Attach`, `Update`, or `Remove` are called. Please vote (👍) for #6999 to indicate that running generators at other times is important to you.

**Comment by AndrewTriesToCode** [comment]
Thanks for taking a look. I gave my thumbs up on that issue.
