### ISSUE TITLE
Cascade deletion of related records are dangerous, why is it the default?

### ISSUE THREAD

**Issue by steynpjm** [dotnet/efcore#27479]
When creating foreign keys for required one-to-many relationships, the default behavior is to create it as "ON DELETE CASCADE".
However, I believe that this is the most dangerous option for a database used in an enterprise. It is just too easy to delete records this way unknowingly.

Is there a global way of changing this behavior to enforce "NO ACTION" by default?

Currently, I have to write code in DBContext OnModelCreating, to specify this behavior for each and every foreign key as there is no way to put this in an attribute on the model. This is not a good way of handling this as the future me is going to forget to add this line after creating yet another model(database table).

**Comment by ajcvickers** [comment]
@steynpjm It is the default because it is the most useful behavior for required relationships where the dependent entities cannot logically exist without their principal. We did carefully consider the implications of this many years ago before making it the default, but opted for the most useful behavior, rather than reducing utility to protect against application logic errors.

There isn't currently a way to configure no-action by default, although I can see that could be useful.

**Comment by steynpjm** [comment]
@ajcvickers Thank you for prompt response.
The protection is not from an application side, but from a user doing a direct SQL query against the database (like for a data-fix).
The problem with "cascade delete timing" is that it is an app thing. The SQL constraint still gets generated with "ON DELETE CASCADE" by default on table/constraint generation (or am I missing something?).

I believe an attribute, that can be set on the foreign-key in a model, is the best option (because it is explicit and visible). Failing that, a single line of code in OnModelCreating against the modelbuilder will also work. Setting the DeleteBehaviour to NoAction in code for each and every foreign-key constraint is time consuming and not really maintainable in the long run.

**Comment by roji** [comment]
Maybe a custom convention could be the answer here.

**Comment by steynpjm** [comment]
@roji Would you suggest I inherit (and customize) a current convention or create a new one from scratch?
If possible, which of the current conventions makes sense to look at or use?

**Comment by roji** [comment]
@steynpjm custom conventions are something we plan to implement for EF Core 7.0 - it isn't currently supported.

However, you can bulk-configure all the foreign key in your model by placing something like the following in your OnModelCreating:

```c#
foreach (var foreignKey in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
{
    foreignKey.DeleteBehavior = DeleteBehavior.NoAction;
}
```

Note that this affects *all* foreign keys (including for collection navigations), so you may want to tweak it to your needs. There may also be some cases where this won't work - so test carefully.

**Comment by steynpjm** [comment]
@roji Thank you. I will try this (and test).

I was just about to respond with "modelBuilder.Properties()" as defined in the documentation, gives a syntax error because the method does not exist... :)

**Comment by steynpjm** [comment]
@roji 
If have created an attribute:
	
```
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
public class NoActionConstraintAttribute : Attribute
{
}
```
and in OnModelCreating, I have modified your code to the following:

```
// This sets all foreign-keys to be no action and not use "ON DELETE CASCADE"
// NB: This should always be last in this method.
foreach (IMutableForeignKey foreignKey in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
{
 if(foreignKey.DependentToPrincipal.PropertyInfo.GetCustomAttributes(typeof(NoActionConstraintAttribute), true).Any())
 {
  foreignKey.DeleteBehavior = DeleteBehavior.NoAction;
 } 
}
```
When adding this attribute on the model to the foreign-key property, it generates that foreign-key as expected with no "ON DELETE CASCADE" SQL phrase for the generated SQL constraint.

If that attribute is not found, it generates the default "ON DELETE CASCADE".

**Comment by roji** [comment]
Sure, if that works for you, use it - though your point above was rather to change the default so that you wouldn't have to explicitly specify this for every property. The attribute-based solution is basically the same thing as using the Fluent API manually, except that it uses an attribute.

**Comment by steynpjm** [comment]
@roji True, but at this point I cannot have my cake and eat it...
The attribute solution is still less coding than the fluent version, which, with my OCD, goes over multiple lines... :)

In the scenario of creating models for Code-First, I prefer attributes directly on the model as it makes things way clearer than a wall of fluent code, and, I believe, more maintainable in the long run.

Thank you for the assistance. Much appreciated.
