### ISSUE TITLE
Change Tracker events lost on pooled context

### ISSUE THREAD

**Issue by pinkfloydx33** [dotnet/efcore#27473]
When using a pooled DbContext, the `SavingChanges` and `SavedChanges` event handlers are preserved between uses of a context. However event handlers added to the change tracker, ie `ChangeTracker.Tracked` and `ChangeTracker.StateChanged` are lost. 

I have no idea if this is expected or not, but it does feel like a disconnect where one set of events is preserved and the other is not. I was unable to find documentation indicating the expected behavior for the events individually or as a whole. 

I am not sure if this is a bug, working as intended or needs to be a potential feature request. If this indeed sounds like a bug I can provide a reproduction. I am on mobile at the moment so unable, but will follow-up accordingly. 

### Include provider and version information

EF Core version: 6.0.2
Database provider: Npgsql/Postgres
Target framework: NET 6.0

**Comment by ajcvickers** [comment]
Note for triage: see #17086.

**Comment by AndriySvyryd** [comment]
This is a bug, we missed resetting `ChangeTracker.Tracked` and `ChangeTracker.StateChanged`
