### ISSUE TITLE
Owned types' changes are not described correctly

### ISSUE THREAD

**Issue by MartinBuna** [dotnet/efcore#27489]
Let's have an entity Person with an owned type Address. When I replace the Address in the Person entity with another Address, the change tracker doesn't show any changes that would imply the Address of Person was changed.
The shadow PK FK is unchanged for original Address, too, pointing it to original Person object.

Table splitting (sharing) is used for below example, but the same thing happens when second table is used.

Original change tracker full debug output:
```
Address {PersonId: 1} Unchanged
  PersonId: 1 PK FK
  City: 'Granada'
  IsOnEarth: 'True'
  Street: 'Cerveza st.'
Person {PersonId: 1} Modified
  PersonId: 1 PK
  Name: 'Peter' Modified
  Address: <not found>
```

Code to test this: https://github.com/MartinBuna/EfCoreOwnedTypeProblem/blob/main/EfCoreOwnedTypeProblem/Program.cs

I haven't found this in https://github.com/dotnet/efcore/issues/22954 and I thought it should me mentioned.

**Comment by AndriySvyryd** [comment]
@MartinBuna The context doesn't detect changes immediately. To get the view of what `SaveChanges` will actually see call `context.ChangeTracker.DetectChanges()` first:

```
Address (Shared) {PersonId: 1} Added
  PersonId: 1 PK FK
  City: 'London'
  IsOnEarth: 'False'
  Street: 'Downing Street'
Address (Shared) {PersonId: 1} Deleted
  PersonId: 1 PK FK
  City: 'Granada'
  IsOnEarth: 'True'
  Street: 'Cerveza st.'
Person {PersonId: 1} Modified
  PersonId: 1 PK
  Name: 'Peter' Modified
  Address: {PersonId: 1}
```
