### ISSUE TITLE
Issue on startup project resolution in migration commands.

### ISSUE THREAD

**Issue by a99cl208** [dotnet/efcore#2748]
Hi,

There is an issue regarding the startup project resolution in migration command (or maybe i'm using it in the wrong way).

Let's say I've got two projets :
- MyApp.Data (The data access layer, containing the db context)
- MyApp.Web (The web application)

So to add a new migration, I go to the folder "D:\MyApp\src\MyApp.Data", then I run the command "dnx . ef migration add v2 -s MyApp.Web".

The command tool says : "Unable to resolve startup project 'MyApp.Web'". However, the migration process continues. Since the startup project has not been resolved, the migration tool does not switch the current directory to the MyApp.Web one. So all components referenced by MyApp.Web but not by MyApp.Data throws in the assembly resolution during host initialization. In addition, the config.json file in searched into the MyApp.Data directory. A workaround is to clone the config.json file and the dependencies of the web project to the data one.

It seems that the root issue is the fact that the migration tool is not able to resolve the startup project. The library manager fails to resolve the project since, i guess, none of the IDependencyResolver implementations resolve dependency from project structure. There is a GAC resolver and a reference resolver, but since MyApp.Data does not references MyApp.Web, there is no chance that the assembly is found.
So maybe you should add your own resolver for migration, or do not use the library manager.

What do you think of it?

Regards.

**Comment by bricelam** [comment]
@davidfowl Is this true? You can't load a project/assembly if the current project doesn't list it as a dependency?

**Comment by toddlucas** [comment]
I had the same problem, but it was a simpler case. I have two projects, with my DbContext in the Data project and the Startup.cs in my Web project. When I ran the command the first time, I got this:

```
C:\...\src\MyProject.Data.Persistence>dnx . ef migration add Initial -s MyProject.Web.Api
Unable to resolve start-up project 'MyProject.Web.Api'.
Using context 'MyContext'.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNet.Mvc, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNet.Mvc, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Presence.Hermes.Web.Api.Startup.ConfigureServices(IServiceCollection services)
```

I was able to fix this by adding a reference to Microsoft.AspNet.Mvc in my Data project (!). I'm hoping to remove this workaround at some point.

One related issue: if my Startup class was not in the same namespace as my assembly (e.g., namespace MyProject.Web vs. assembly name MyProject.Web.Api), then I got an additional error:

```
Unable to resolve start-up project 'MyProject.Web.Api'.
Using context 'MyContext'.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   ...
```

I hope this is helpful.

**Comment by leak** [comment]
I have similar issues as described above.

Additionally I'd like to point out another potential issue.

If the database path in the connection string is specified in a relative position to the application and the project layout is split up like described above, the actual database will not be found either by the application or by the dnx ef migration command.

Because relative path are not really supported in connection strings, I'm using the following code:

````
.AddDbContext<AppDbContext>(
    options => options.UseSqlite(
        "Data source=" + AppEnv.ApplicationBasePath + @"\db\database.sqlite")
);
````

Problem is that the AppEnv.ApplicationBasePath points to the MyApp.Web base folder when starting the application and it points to MyApp.Data base folder when invoked from dnx ef.

**Comment by davidfowl** [comment]
@bricelam yes this is true. The project needs to be referenced for it to be loadable/compilable.

**Comment by bricelam** [comment]
:disappointed: :wrench: => :bike:
Thanks, we'll rethink our strategy for start-up projects.

**Comment by bricelam** [comment]
Closing since this work is tracked by #2294
