### ISSUE TITLE
Scaffolding with NRT generates non-nullable navigation property from principal to dependent

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27496]
Scaffolding the following schema in a project with NRT enabled:

```c#
CREATE TABLE Principal
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
);

CREATE TABLE Dependent
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PrincipalId INT NOT NULL,
    CONSTRAINT FK_A_B FOREIGN KEY (PrincipalId) REFERENCES [Principal](Id)
);

CREATE UNIQUE NONCLUSTERED INDEX [IX_Dependent_PrincipalId] ON [Dependent] ([PrincipalId] ASC);
```

... generates the following CLR type for Principal:

```c#
public partial class Principal
{
    public int Id { get; set; }

    public virtual Dependent Dependent { get; set; } = null!;
}
```

The Dependent navigation property should be nullable.

Raised by @AFract in https://github.com/ErikEJ/EFCorePowerTools/issues/1298

**Comment by ErikEJ** [comment]
Patch in 6.0?

**Comment by roji** [comment]
Yeah, I think it makes sense - will bring to the team for discussion.

**Comment by roji** [comment]
Whoops, looks like this slipped under the radar - we didn't service this. I'll prepare a PR.
