### ISSUE TITLE
OnModelCreating ForSqlServer().UseIdentity() is not found in beta 6

### ISSUE THREAD

**Issue by heathyates** [dotnet/efcore#2749]
Has `ForSqlServer().Identity()` been depreciated or refactored in beta 6? I have the following line of code that worked in beta 5: 

`entity.Property(building => building.BuildingId).ForSqlServer().UseIdentity();`

After some digging, I found something like this in beta 6: 

 `entity.Property(building => building.BuildingId).UseSqlServerIdentityColumn();`

Are these two equivalent? Intuitively, I think so, but I want to confirm. Thanks.

**Comment by bricelam** [comment]
Yes, the API was flattened a bit.

**Comment by ErikEJ** [comment]
If your Entity class is called Building, you do not need any code, as IDENTITY is now the default (as sequence was before)

**Comment by heathyates** [comment]
@ErikEJ @bricelam I will take out this code since it isn't needed. That being said thanks for replying. I hope this helps other folks moving forward. You two are awesome.
