### ISSUE TITLE
System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by pabermod** [dotnet/efcore#27490]
Hi,

I have a library that references Microsoft.EntityFrameworkCore.SqlServer. This library has a method for migrating the database model using entity framework core.

I'm loading this library dinamically from another library with a custom AssemblyLoadContext (to avoid problems with different dependencies version and to allow to unload the dll once executed) and executing this method.

This is working with other providers I have referenced in the first library (for example Npgsql). This is also working if I copy the first library deps.json file to the deploy folder. I don't understand Why I need the deps.jsonof the library only for te Sql dependency. I also don't know how to deploy it

The exception:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ConsoleApp10.Program.ExecuteAndUnload(AssemblyLoadContext context, String assemblyPath, WeakReference& alcWeakRef) in C:\Users\pablo.bernal\source\repos\ConsoleApp10\ConsoleApp10\Program.cs:line 205
   at ConsoleApp10.Program.Main(String[] args) in C:\Users\pablo.bernal\source\repos\ConsoleApp10\ConsoleApp10\Program.cs:line 159

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.

The assembly loader
```C#
public class MyAssemblyLoadContext : AssemblyLoadContext
    {
        private AssemblyDependencyResolver _resolver;

        public MyAssemblyLoadContext(string mainAssemblyToLoadPath) : base(isCollectible: true)
        {
            _resolver = new AssemblyDependencyResolver(mainAssemblyToLoadPath);
        }

        protected override Assembly Load(AssemblyName name)
        {
            string assemblyPath = _resolver.ResolveAssemblyToPath(name);
            if (assemblyPath != null)
            {
                return LoadFromAssemblyPath(assemblyPath);
            }
            
            return null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (libraryPath != null)
            {
                return LoadUnmanagedDllFromPath(libraryPath);
            }

            return IntPtr.Zero;
        }
    }
```

My code to execute the method
```cs
var SourceDirectory = @"C:\dev\myproject\bin\net6.0";
            string ConnectionString = @"Data Source=myhost\SQLExpress;Initial Catalog=mydb;User Id=myuser;Password=mypass;";
            string ProviderName = "System.Data.SqlClient";

            var assembly = context.LoadFromAssemblyPath(assemblyPath);
            alcWeakRef = new WeakReference(context, trackResurrection: true);

            var adContext = assembly.GetType("MyType");
            var instance = Activator.CreateInstance(adContext, ConnectionString, ProviderName, null);
            PropertyInfo databaseProperty = adContext.GetProperty("Database");
            var database = databaseProperty.GetValue(instance);

            var efAssembly = context.LoadFromAssemblyPath(Path.Combine(SourceDirectory, "Microsoft.EntityFrameworkCore.Relational.dll"));
            var extensionsType = efAssembly.GetType("Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions");
            MethodInfo mmigrateMethod = extensionsType.GetMethod("Migrate");

            mmigrateMethod.Invoke(database, new object[] { database });
            context.Unload();
```

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 (latest version)

Packages used in called library:

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.2" />
		<PackageReference Include="Devart.Data.Oracle.EFCore" Version="9.16.1434" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.3" />
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="6.21.5" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.1" />
	</ItemGroup>

**Comment by roji** [comment]
Cross-filed as #1521

**Comment by roji** [comment]
@pabermod this doesn't seem like it's related to EF Core in any way, to https://github.com/dotnet/SqlClient/issues/1521 is probably the right place to investigate.

**Comment by pabermod** [comment]
Should I keep this one open just in case until it is resolved?

**Comment by roji** [comment]
Better to close this and let the investigation happen in https://github.com/dotnet/SqlClient/issues/1521, we can always move that issue here if needed.
