### ISSUE TITLE
Filtered Includes for hidden navigation properties

### ISSUE THREAD

**Issue by mgraf1** [dotnet/efcore#27493]
## Ask a question
Hello, I'm working on an application that uses EF Core to map DDD-style aggregates to a SQL Server database. Several aggregates have private collections which are treated as collections of owned entities. When I query these aggregates, I make use of string-based include statements to eagerly load the collections

```C#
var myObject = await this.context.MyObjects
    .Include("children")
    .FirstOrDefaultAsync(p => p.Id == myObjectId && EF.Property<int>(p, "tenantId") == tenantId);
```

This works very well. However I'd like to take advantage of the new filtered-include functionality to apply an order-by clause to children to ensure that children loaded from the database are always retrieved in a specific order. 

Is there a way to do this for a private collection, or do I need to make `children` a public property and do something like:

```C#
var myObject = await this.context.MyObjects
    .Include(x => x.Children.OrderBy(c => c.Date))
    .FirstOrDefaultAsync(p => p.Id == myObjectId && EF.Property<int>(p, "tenantId") == tenantId);
```

Thanks!

**Comment by ajcvickers** [comment]
There isn't currently a way to do this. In the future we could consider implementing something like this:

```C#
var posts = context.Posts.Include(e => EF.Property<Blog>(e, "Blog")).ToList();
var blogs = context.Blogs.Include(e => EF.Property<ICollection<Post>>(e, "Posts").OrderBy(c => c.Date)).ToList();
```

**Comment by smitpatel** [comment]
This should be very easy to enable if we want to do it. Basically we would make `c => c.Navigation` as same as `c => EF.Property<NavigationType>("Navigation")` inside Include nodes.

**Comment by mgraf1** [comment]
In recent releases, EF Core has making big strides in allowing developers to create encapsulated domain models. IMO, this would be another win on that front since it removes the need to have a public navigation to leverage an important feature.

**Comment by ajcvickers** [comment]
Design meeting for Navigation or Property.
