### ISSUE TITLE
Does EFCore automatically parameterize Skip/Take values now?

### ISSUE THREAD

**Issue by julealgon** [dotnet/efcore#27512]
On EF Classic, there used to be overloads for `Skip` and `Take` that took `Expression<Func<int>>` as parameters. Those would be used to make EF parameterize the values instead of inlining them as constants. It was done as a means to ensure consistent query text, which helps with caching and query plans in the database side.

So instead of doing this:
```csharp
context.Set.Skip(2).Take(10).ToList();
```

You'd do this:
```csharp
context.Set.Skip(() => 2).Take(() => 10).ToList();
```

On EFCore however, I can't seem to find those overloads anymore.

Has EFCore been adapted to avoid the original issue from EFClassic, and always parameterize the value now? Or are those overloads living in a different namespace I'm unaware of?

**Comment by roji** [comment]
@julealgon yes, EF Core parameterizes Skip and Take. You can simply inspect the generated SQL via ToQueryString to find out exactly what gets generated.

**Comment by julealgon** [comment]
Thanks @roji . That's actually really nice!

**Comment by mkamal-sejeltech** [comment]
@julealgon Yes, EFCore always parameterize the value now in the generated sql
