### ISSUE TITLE
EF Core 6 , on model builder configuration doesn't have (Map) Method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#27517]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF-Core-6--on-model-builder-configurati/1665636)._

---
In this case ,you can see my Modelbuilder  Created and actually i can't use of many methods like (Map,HasRequired,....).
what can i do?

! [Screenshot (9).png] (https://aka.ms/dc/image?name=B0888d754fcb847fe9155a43411962dbe637805235057468486_Screenshot_(9).png&tid=0888d754fcb847fe9155a43411962dbe637805235057468486)

---
#### Feedback Bot on 2/16/2022, 01:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
EF Core is a completely different codebase to EF6, with a similar but different model building API. See [Port from EF6 to EF Core](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/).

**Comment by ChavaNava** [comment]
What happens with this issue? Is there any workaround for this?

**Comment by ajcvickers** [comment]
@ChavaNava EF Core is a completely different codebase to EF6, with a similar but different model building API. See [Port from EF6 to EF Core](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/).
