### ISSUE TITLE
Controlling version number (with a prerelease) when building

### ISSUE THREAD

**Issue by hounddog22030** [dotnet/efcore#27527]
If I make a fork and build EF Core, I see that I should use build.sh/cmd.

Is there a method to `build -pack` with a pre-release version number, e.g. 6.0.2-with-my-new-feature?

**Comment by hounddog22030** [comment]
I edited Version.props as below:

      <PropertyGroup Label="Version settings">
        <VersionPrefix>6.0.3</VersionPrefix>
        <PreReleaseVersionLabel>rollback</PreReleaseVersionLabel>
        <PreReleaseVersionIteration>1</PreReleaseVersionIteration>
        <IncludeSourceRevisionInInformationalVersion>False</IncludeSourceRevisionInInformationalVersion>
        <IsServicingBuild Condition="'$(PreReleaseVersionLabel)' == 'servicing'">true</IsServicingBuild>
        
        <StabilizePackageVersion Condition="'$(StabilizePackageVersion)' == ''">false</StabilizePackageVersion>
        <DotNetFinalVersionKind Condition="'$(StabilizePackageVersion)' == 'true'">release</DotNetFinalVersionKind>
      </PropertyGroup>

specifically editing `PreReleaseVersionLabel` and `PreReleaseVersionIteration`.

When I build, I get 

`efcore/artifacts/packages/Debug/Shipping/Microsoft.EntityFrameworkCore.Tools.6.0.3-dev.nupkg`

I would have expected `Microsoft.EntityFrameworkCore.Tools.6.0.3-rollback.nupkg`, not `dev`

How do I get `Microsoft.EntityFrameworkCore.Tools.6.0.3-rollback.nupkg`?

**Comment by hounddog22030** [comment]
Seems like the only way I can find to control this is from this as below?

      <PropertyGroup Label="Version settings">
        <MajorVersion>6</MajorVersion>
        <MinorVersion>0</MinorVersion>
        <PatchVersion>2</PatchVersion>
        <PreReleaseLabel>preview</PreReleaseLabel>
        <BuildNumber Condition="'$(BuildNumber)' == ''">$(CODEBUILD_BUILD_NUMBER)</BuildNumber>

        <VersionPrefix>$(MajorVersion).$(MinorVersion).$(PatchVersion)</VersionPrefix>
        <VersionSuffix>$(PreReleaseLabel)-$(BuildNumber)</VersionSuffix>

        
        <IsFinalBuild Condition=" '$(IsFinalBuild)' == '' ">false</IsFinalBuild>
        <IncludePreReleaseLabelInPackageVersion>true</IncludePreReleaseLabelInPackageVersion>
        <IncludePreReleaseLabelInPackageVersion Condition=" '$(IsFinalBuild)' == 'true' AND ('$(PreReleaseLabel)' == 'servicing' OR '$(PreReleaseLabel)' == 'rtm')">false</IncludePreReleaseLabelInPackageVersion>

        
        <PackageVersion>$(VersionPrefix)</PackageVersion>
        <PackageVersion Condition=" '$(IncludePreReleaseLabelInPackageVersion)' == 'true' ">$(VersionPrefix)-$(VersionSuffix)        
       </PackageVersion>
      </PropertyGroup>

**Comment by hounddog22030** [comment]
> @hounddog22030 This is not something I have tried to do. @dougbu @wtgodbe Any ideas here?

Ok.  If you've never tried doing it, maybe I'm barking up the wrong tree.  Let me go back to my use case here:

I am:
1. Trying to build the current 6.0 branch and add some debugging logging to diagnose something
2. I am building the code off a branch in a fork in AWS CodeBuild and publishing the results to a NuGet repository
3. Trying to use the resultant NuGet packages in our application to exercise the logging 

Because I cannot overwrite in the NuGet repository, I want to be able to do iterative builds as I get closer to the issue.  e.g. Microsoft.EntityFrameworkCore.Tools.6.0.4-rollback-18.nupkg, Microsoft.EntityFrameworkCore.Tools.6.0.4-rollback-19.nupkg, Microsoft.EntityFrameworkCore.Tools.6.0.4-rollback-20.nupkg

That's the tree I want to bark up.

What would be the best way, using the current versioning infrastructure in EF Core (arcade?) to do the above.

**Comment by dougbu** [comment]
Local builds mostly ignore the prerelease settings in Eng/Versions.props. The way around it is to add a fake "official" build id to your build e.g. `./build.sh /p:OfficialBuildId=20220302.6`. I normally update the identifier each time I need one of these odd builds to get unique package names.

**Comment by dougbu** [comment]
A PowerShell script to create the build parameter:

``` powershell
$private:buildIdValue = [System.DateTime]::Now.ToString("yyyyMMdd.6")
$private:BuildId = "/p:OfficialBuildId=$buildIdValue"
Set-Clipboard -Value $BuildId
$BuildId
```

Update the `.6` part of that if you need to do more than one unique build per day.

**Comment by ErikEJ** [comment]
Something for the build docs?

**Comment by ajcvickers** [comment]
@dougbu Thanks! I didn't know that trick.
@ErikEJ Good idea.
