### ISSUE TITLE
RelationalMethodCallTranslatorProvider and explicit typeMapping

### ISSUE THREAD

**Issue by mm3141** [dotnet/efcore#27524]
Hi,
is it on purpose that `dbFunction.TypeMapping` is not passed in into these calls, but the default `null` is used?

https://github.com/dotnet/efcore/blob/f8585c2166974887eac17063a7b180316a537218/src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs#L78-L91

We have some SQL function returning `string[]`, and have to use `HasDbFunction` with a more complex `HasTranslation` instead of the simple fluent API, presumably because of this.

**Comment by smitpatel** [comment]
Currently, the TypeMapping on DbFunction is not set by anything. It is derived when accessing based on store type string specified. This means that the store type must be mappable by the provider for given CLR type returned by function. There is no way to specify a value converter for DbFunctions yet. So the CLR type has to be mappable by provider for this to work correctly in all path (till we get value converter support). If the CLR type can be mapped to multiple different store type then store type string helps figuring out the correct one.

Passing in the type mapping here will help with inferring the type mapping. Currently user set type mapping is ignored other than validating that it is mappable type.

**Comment by smitpatel** [comment]
Poaching
