### ISSUE TITLE
Temporal table for InMemory or SQLite

### ISSUE THREAD

**Issue by grinay** [dotnet/efcore#27522]
Hello. Does Inmemory or SQLIte ef core providers support temporal table, I wrote fe integrations tests with temporal tables, but non of them seems to be working. Can you advice?

**Comment by maumar** [comment]
No, temporal tables are only supported on Sql Server in EF Core 6

**Comment by roji** [comment]
@grinay give our [testing docs](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy) a read. If you choose to test without your real database (SQL Server in this case), substitutes (or fakes) such as InMemory or SQLite do not behave in the same way, and some functionality simply cannot be tested. Your options are either to write tests which execute against SQL Server ([this doc page provides some guidelines](https://docs.microsoft.com/en-us/ef/core/testing/testing-with-the-database), or to add a repository layer which allows abstracting EF Core entirely, and mock that.
