### ISSUE TITLE
Getting primary keys with just a model, no db context/db context provider

### ISSUE THREAD

**Issue by deepchoudhery** [dotnet/efcore#27538]
Want to get the primary keys for a given model/entity using [Microsoft.EntityFrameworkCore.Metadata.IEntityType.FindPrimaryKey() without activating a DbContext instance (avoiding DbContext.Model.FindEntityType(Type). Anyway to create EntityType correctly (without DbContext) to use FindPrimaryKey(). Haven't particularly found a way.

**Comment by AndriySvyryd** [comment]
Generally a `DbContext` is needed to obtain the `Model`
