### ISSUE TITLE
Throws System.InvalidOperationException where Any is used with FromSqlRaw

### ISSUE THREAD

**Issue by fscavo** [dotnet/efcore#27546]
System.InvalidOperationException: The query contains usage of 'Any' or 'AnyAsync' operation after 'FromSqlRaw' or 'FromSqlInterpolated' me ││ thod. Using this raw SQL query more than once isn't currently supported. Replace the use of 'Any' or 'AnyAsync' with 'Count' or 'CountAsync'

**Comment by ErikEJ** [comment]
Please share some code.

**Comment by fscavo** [comment]
This code used to work fine with EF core 5
```csharp
var mappings = dbContext.Set<IdMappingDbEntity>().FromSqlRaw(query).AsNoTracking();
var result = mappings.Any() ? .....
```

**Comment by ajcvickers** [comment]
Duplicate of #26167
