### ISSUE TITLE
index added to model not being added in migration

### ISSUE THREAD

**Issue by MolallaComm** [dotnet/efcore#27552]
Yesterday, I added a new filtered index to my DbContext in OnModelCreating:

`modelBuilder.Entity<CreditCard>().HasIndex(d => new { d.AccountID, d.Recurring }).HasFilter("\"Recurring\" = true").IsUnique();`

I then ran `dotnet ef migrations add AddCCAccountRecurringConstraint` but the resulting migration Up routine was empty - seems like a bug - maybe because of the HasFilter or maybe combination of HasFilter with compound index - as I have lots of other IsUnique indexes defined this way and they always showed up in the migrations as expected.  I'm using EFCore6 latest with npgsql latest.  

I can make a sample project using SqlServer provider if it would be helpful and to rule out that it is a problem with Npgsql.

For testing, a simplified CreditCard POCO would look like this:

```
public class CreditCard
{
  [Key]
  public long CreditCardID {get; set;}
  public int AccountID {get; set; }
  public bool Recurring {get; set; }
}
```

**Comment by MolallaComm** [comment]
Doh - it occurred to me that there was a small possibility that i didn't save changes to my dbcontext.cs file before kicking off the migration generation in a separate window - it appears that was it - because when i tried it again, it worked.

**Comment by ajcvickers** [comment]
@MolallaComm Happens to us all at some point. :-)
