### ISSUE TITLE
'using' vs 'await using' usage while creating DbContext object

### ISSUE THREAD

**Issue by xdsrivastava001** [dotnet/efcore#27560]
## I want to know the use-case for both the ways and which one is better while initializing the DbContext object?

Here is what I am trying to do:

```C#
var optionsBuilder = new DbContextOptionsBuilder<MasterDBContext>();
optionsBuilder.UseSqlServer(_config["ConnectionStrings:MasterDB"]);
await using var uow = new UnitOfWork(new MasterContext(optionsBuilder.Options));
```

### Include provider and version information

EF Core version: 6.4.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 (build: 18363.2094)
IDE: Visual Studio 2022

**Comment by roji** [comment]
@xdsrivastava001 in your example above, the `await using` is done over UnitOfWork, which seems like an object of yours and not a DbContext (XpoMasterContext seems to be that).

Regarding using vs. await using on a DbContext... In practice, disposing a context very rarely needs to perform any I/O; that should only happen in some very specific scenarios. As a result, there usually isn't a specific need to use await using. On the other hand, the actual overhead of `await using` over `using` is very likely to be negligible, so I'd default to using `await using` in async code. It ensures asynchronicty in case any I/O does need to be done, and always removes IDE suggestions for doing that.

**Comment by xdsrivastava001** [comment]
@roji Thank you for clarifying this. Makes sense now.
