### ISSUE TITLE
Allow scaffolder to accept in a manifest file.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#27577]
Currently there are a few things unconfigurable by conventional means into the scaffolder:
- making some columns (represented as text in db) as DateTime objects (I store datetimes as text as they are or well should be always stored as UTC/read as UTC)
- which types should be generated as internal by the scaffolder
- if the scaffolder should use file-scoped.
- if the scaffolder should not generate the using statements on top of generated files (when they are added to the global usings)
- any of the other options that can be done in command line but optionally included in the manifest file to make the command just ``dotnet ef dbcontext scaffold --manifest [manifest file here]`` where the command could pick up the connection string, etc if the user wants to place them there.

I would like to have support in the scaffolder for a manifest file to use when generating code.

**Comment by roji** [comment]
@AraHaan most of the above are already being discussed in various other issues, on which you've commented (e.g. #25223 for file-scoped namespaces). 

We have no plans for introducing a "manifest" file for code generation. As written elsewhere, #4038 should provide code generation flexibility via templates.
