### ISSUE TITLE
Add a flag to opt into SaveChanges transactions even where they're not necessary

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27574]
#27439 made us stop starting transactions where that isn't necessary (e.g. single-statement insertion). However, there may be cases where users still want a transaction to be created. For example, a user may be using a command interceptor to commit an additional row to the database (e.g. audit), and may want transactionality for the two rows.

Add a flag to allow users to get a transaction even when we don't require it.

**Comment by benlongo** [comment]
It might be worth mentioning that this exists near `DbTransactionInterceptor`. I had a hard time figuring out what guarantees I have around when `DbTransactionInterceptor` gets called, and a similarly difficult time finding out that this option exists.

**Comment by voroninp** [comment]
Is it possible to set it on the options not on Database?

**Comment by roji** [comment]
@voroninp no, but it's trivial to simply set the flag in the constructor of your DbContext type.

**Comment by voroninp** [comment]
True. Just got used to being able to configure such things in options.
