### ISSUE TITLE
OnModelCreated _or_ ChangeTracker configuration hook

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#27578]
There are some ChangeTracker settings that I would like to always apply for all of my DbContexts. Specifically I would like to assign to DeleteOrphansTiming, CascadeDeleteTiming, AutoDetectChangesEnabled. But I don't have a place to put that code as part of my derived DbContext. It cannot go into OnModelCreating because the access to ChangeTracker requires the model to be already created. I believe that OnConfiguring is also too soon. 

Add a virtual method that is called after the model is created and access to the dbContext.ChangeTracker is valid. Perhaps OnModelCreated or OnChangeTrackerCreated. 

An alternative would be to allow configuration of these attributes through the ModelBuilder.

**Comment by roji** [comment]
@sjb-sjb any reason you cannot simply set these in the constructor?

**Comment by sjb-sjb** [comment]
Um, uh, gee, that works just great !! 
I did this just to wrack up another notch on the dumb questions list :-) 
Thanks, @roji
