### ISSUE TITLE
Question: Obfuscation guidelines

### ISSUE THREAD

**Issue by virzak** [dotnet/efcore#27581]
## Are obfuscation rules summarized anywhere?

I spent a few days debugging an app just to find out that the use of reflection changed the behavior by renaming
- System.Runtime.CompilerServices.NullableContextAttribute and [not finding it](https://github.com/dotnet/efcore/blob/87f933f70a33015d834cc7f2118991fcccc5db9c/src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs#L124). This actually caused a bug with owned entity.
- the backing field `<...>k__BackingField` and returning null instead of [appropriate FieldInfo](https://github.com/dotnet/efcore/blob/e8b51bdec79b5b78e4c3acb1287121c9b273f65d/src/EFCore/Metadata/Conventions/BackingFieldConvention.cs#L161). This did not cause a bug, but there was a discrepancy in logging: Feature.Id (*no field*, Guid)

I guess the safest rules are to not obfuscate
- Any type inside namespace `System.*`
- Any type mentioned in DBContext, their base classes, their mapped members

Please let me know your thoughts.

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Obfuscator: obfuscar

**Comment by ajcvickers** [comment]
@virzak EF Core uses many extra-linguistic patterns that make it incompatible with obfuscation.

**Comment by virzak** [comment]
Warning or error from EF Core would be extremely useful when obfuscation is detected. In my case the entities are part of an assembly that has business logic, so obfuscation is important.

**Comment by ajcvickers** [comment]
@virzak We don't have any plans to try to detect obfuscation.
