### ISSUE TITLE
IsTemporal() with SetIsMemoryOptimized(true) generates invalid CREATE TABLE

### ISSUE THREAD

**Issue by yzorg** [dotnet/efcore#27592]
[supported in SQL 2019 - see link](https://docs.microsoft.com/en-us/sql/relational-databases/tables/system-versioned-temporal-tables-with-memory-optimized-tables?view=sql-server-ver15)

* SqlContext.cs
```cs
entity.ToTable("VendorTable1", "lookup", b =>
{
    b.IsTemporal();
    b.Metadata.SetIsMemoryOptimized(true);
})
    // not actual name, but external vendor numeric ID
    .HasIndex(e => e.Vendor_ID) 
        .IsUnique();
// external vendor-assigned string code, displayed to users
entity.HasKey(e => e.Vendor_Code);
```

When scripting with `dotnet ef migrations script --output migrations\ef_00_initial.sql` it generated invalid SQL:

* ef_00_initial.sql
```sql
CREATE TABLE [lookup].[VendorTable1] (
    [Vendor_Code] varchar(50) NOT NULL,
    [Vendor_ID] BIGINT NOT NULL,
-- 50 more columns not shown
    [Regional_Stamp_Indicator] varchar(4) NULL,
    [PeriodEnd] datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
    [PeriodStart] datetime2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    CONSTRAINT [PK_VendorTable1] PRIMARY KEY NONCLUSTERED ([Vendor_Code]),
    PERIOD FOR SYSTEM_TIME([PeriodStart], [PeriodEnd])
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [lookup].[VendorTable1History]))
    WITH
        (MEMORY_OPTIMIZED = ON);
GO

```

It was really close, but added 2 "WITH" clauses instead of combining them.

### version information

EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
MSSQL: SQL 2019, 15.0.4198.2
Target framework: .NET 6.0
Operating system: Win10 (production is k8s/Linux)
IDE: Visual Studio 2022
But I use `dotnet ef` for all scaffolding, migrations, and migration scripting.

**Comment by roji** [comment]
Muhahaha I got there first, issuesCount++
