### ISSUE TITLE
Perf: Replace IProperty.IsShadowProperty with ClrPropertyInfo

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#2760]
We can save CPU time by not looking up the PropertyInfo after the model is built.
We can also save memory by not storing the property name and type for non-shadow properties and just getting them from the PropertyInfo

**Comment by rowanmiller** [comment]
**Triage:** We will optimize this based on results from perf runs. We suspect the benefit would be negligible, but profiling will show if it is something we should change.
