### ISSUE TITLE
InMemory generates and assigns Id before SaveChanges

### ISSUE THREAD

**Issue by Toxantron** [dotnet/efcore#27611]
## File a bug

Since moving to EF Core many tests fail because InMemory behaves different to old Entity Framework and more importantly to real databases. When creating entities, the InMemory database assigns the Id property on `Add` and not on `SaveChanges`. It get's even weirder, because if the backing field is named `_id` instead of e.g. `_myId` it even bypasses the setter and assigns the field directly.

### Include your code

```C#
public class MyEntity
{
    private long _id;

    /// <inheritdoc />
    [Key] // Apparently optional if Property is named "Id"
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public virtual long Id
    {
        get => _id;
        set
        {
            _id = value;
            IdChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    /// <inheritdoc />
    public event EventHandler IdChanged;
}

// Test
var entity= new MyEntity(); 
entitySet.Add(entity);
Assert.AreEqual(0, entity.Id); // Fails with InMemory, Id already 1 and setter bypassed
await context.SaveChangesAsync(); // With real database Id is set here
```

Our Open Source Repo with the issue: https://github.com/PHOENIXCONTACT/MORYX-Core/blob/future/src/Tests/Moryx.Model.Tests/InMemoryTests.cs#L31

### Include provider and version information

EF Core version: > 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.InMemory)
Target framework: (e.g. .NET 5.0): NET Core 3.1, NET 5.0; NET 6.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3) VS 2022

**Comment by ajcvickers** [comment]
@Toxantron This is by-design. The in-memory database is not a relational database as is not intended to behave in the same way as a relational database. Using it for testing is not recommended; see [Testing EF Core Applications](https://docs.microsoft.com/en-us/ef/core/testing/).
