### ISSUE TITLE
The global interceptor must take effect under the DbContext

### ISSUE THREAD

**Issue by zhenlei520** [dotnet/efcore#27612]
Hi:
I now have a requirement to use a global interceptor, but I found that the interceptor is only valid under the DbContext class, and moving the QueryFilter to other classes will not work. The specific requirements:
1. Query the data of the current tenant based on the login information
2. Hope the HasQueryFilter method can be migrated to other classes for use

``` C#
public class MasaDbContext : DbContext
{
  public UserDbContext(DbContextOptions<UserDbContext> options, IServiceProvider serviceProvider): base(options)
  {
  	_options = options;
  	_serviceProperty = serviceProvider;
  	_tententProvider = serviceProvider.GetRequiredService<ITententProvider>();
  }
  	
  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    base.OnModelCreating(modelBuilder);
    foreach (var entityType in modelBuilder.Model.GetEntityTypes())
    {
  	  var parameter = Expression.Parameter(entityType.ClrType);
      if (typeof(IMultiTenant<Guid>).IsAssignableFrom(entityType.ClrType))
      {
        var propertyMethodInfo = typeof(EF).GetMethod("Property")!.MakeGenericMethod(typeof(Guid));
        var property = Expression.Call(propertyMethodInfo, parameter, Expression.Constant(nameof(IMultiTenant<Guid>.TenantId)));
      
        var instanceCast = Expression.Constant(this);
        var methodCallExpression = Expression.Call(instanceCast, nameof(GetTententId), Type.EmptyTypes);
        var compareExpression = Expression.Equal(property, methodCallExpression);
      
        var lambda = Expression.Lambda(compareExpression, parameter);
        modelBuilder.Entity(entityType.ClrType).HasQueryFilter(lambda);
      }
    }
  }

  public Guid GetTententId() => _tententProvider.TententId;
}

public interface ITententProvider
{
    Guid TententId { get; set; }
}
```

The above operation is no problem. When the tenant changes, the changed data will be found, but I don't want to write a complete Filter in OnModelCreating under DbContext. I hope that the operations related to global filtering in OnModelCreating can be migrated to other files , like this

``` C#

public class MasaDbContext : DbContext
{
  private readonly IModelCreatingProvider _modelCreatingProvider;
  public UserDbContext(DbContextOptions<UserDbContext> options, IServiceProvider serviceProvider): base(options)
  {
  	_options = options;
  	_serviceProperty = serviceProvider;
	_modelCreatingProvider = serviceProvider.GetRequiredService<IModelCreatingProvider>();
  }
  	
  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    base.OnModelCreating(modelBuilder);
    _modelCreatingProvider.OnModelCreating(modelBuilder);
  }
}

public class GlobalFilter : IModelCreatingProvider
{
    public readonly ITententProvider _tententProvider;
    public GlobalFilter(ITententProvider tententProvider)
    {
        _tententProvider = tententProvider;
    }

    public void Configure(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var parameter = Expression.Parameter(entityType.ClrType);
            if (typeof(IMultiTenant<Guid>).IsAssignableFrom(entityType.ClrType))
            {
                var propertyMethodInfo = typeof(EF).GetMethod("Property")!.MakeGenericMethod(typeof(Guid));
                var property = Expression.Call(propertyMethodInfo, parameter, Expression.Constant(nameof(IMultiTenant<Guid>.TenantId)));

                var instanceCast = Expression.Constant(this);
                var methodCallExpression = Expression.Call(instanceCast, nameof(GetTententId), Type.EmptyTypes);
                var compareExpression = Expression.Equal(property, methodCallExpression);

                var lambda = Expression.Lambda(compareExpression, parameter);
                modelBuilder.Entity(entityType.ClrType).HasQueryFilter(lambda);
            }
        }
    }

    public Guid GetTententId() => _tententProvider.TententId;
}
```

**Comment by zhenlei520** [comment]
I learned that OnModelCreating has a cache, so I deliberately processed it through lambda expressions, hoping to get the corresponding tenant data after changing the tenant, but it is still useless. After passing the test, after OnModelCreating is migrated to other classes, the GetTententId() method will only Called once, and under DbContext, GetTententId() will be called again for each query. I don't know how to deal with this problem. I tried to call the `_tententProvider.OnModelCreating()` method through the lambda tree, and the result is still it's the same

**Comment by zhenlei520** [comment]
I have been researching this problem for two or three days and still haven't solved it. I feel really bad. I also tried to query other solutions, but all I can find are used under DbContext, and no one has tried to move the filtering operation to other location, but I wish the filtering could be moved elsewhere, I don't want these functions coupled together, I really hope to get back to you sooner, thanks a lot

**Comment by zhenlei520** [comment]
> @zhenlei520查询过滤器为什么设计为通过在当前 DbContext 实例上配置或引用的值进行参数化。这允许每个查询自动从当前 DbContext 中获取当前参数值，该 DbContext 是所有查询的根。你可以解释一下你想不想吗？

I'm very happy to have received your response

This is related to design. I understand that DbContext is the solution provided by EFCore, but multi-tenancy, soft deletion, etc. are the products of business. I put DbContext in the tool library here, but multi-tenancy and soft deletion are put into a project called Masa.BuildingBlock, and the filtering that implements multi-tenancy and soft deletion is put in the implementation class library of BuildingBlock.

As a framework, multi-tenancy and soft deletion must be implemented, but these functions are not necessarily implemented using EFCore, so I don't want to have to put these filtering operations into the DbContext project, because that's the way If so, the framework that provides multi-tenancy and soft deletion needs to have a dependency on the library that provides DbContext, but I don't want them to have any intersection, so I hope to achieve the goal in other ways

**Comment by ajcvickers** [comment]
@zhenlei520 Then I don't think you can use query filers for multi-tenancy, since query features require interaction with the DbContext. You will need to find another way to achieve this; I'm don't have any good ideas how to do it.

**Comment by zhenlei520** [comment]
> @ajcvickers Then I don't think you can use query filers for multi-tenancy, since query features require interaction with the DbContext. You will need to find another way to achieve this; I'm don't have any good ideas how to do it.

The multi-tenancy here is the way of sharing the database and the shared scheme. It is only used for filtering through a multi-tenant field. Independent database or mixed mode are not considered for the time being, so I hope to use the global interceptor to achieve the purpose. What do you think is wrong with this?

**Comment by zhenlei520** [comment]
https://github.com/abpframework/abp/blob/7317e493279e09d2f11322b04310c7442916bf27/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L677-L694

I see that the same is true for abp design, but it is also used directly under DbContext without moving the position.

**Comment by ajcvickers** [comment]
@zhenlei520 That's not supported by EF query filters.

**Comment by zhenlei520** [comment]
> @ajcvickers  That's not supported by EF query filters.

Hmm, thanks for your reply, any better suggestion then? I have always felt that global interceptors are the most convenient to use. There is no need to manually specify the conditions every time. It would be too bad if you need to manually specify these same conditions every time. Operating under the current root?

**Comment by ajcvickers** [comment]
@zhenlei520 As I said above, I don't have any good ideas how to do this.

**Comment by zhenlei520** [comment]
> @ajcvickers  As I said above, I don't have any good ideas how to do this.

Well thank you for your reply, then I will check if there are other solutions or consider adjusting the dependencies between the projects
