### ISSUE TITLE
NU1202 Package Microsoft.EntityFrameworkCore 6.0.3 is not compatible with netstandard2.1

### ISSUE THREAD

**Issue by santoshpatro** [dotnet/efcore#27636]
I am trying to install the latest Microsoft.EntityFrameworkCore 6.0.3 into a class library project targetting netstandard2.1 using Nuget Package Manager and I get this error:

`Package Microsoft.EntityFrameworkCore 6.0.3 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.EntityFrameworkCore 6.0.3 supports: net6.0 (.NETCoreApp,Version=v6.0)`

Can anyone help me with their guidance to fix this issue?

**Comment by roji** [comment]
@santoshpatro it's exactly as the error message says: EF Core 6.0 isn't compatible with netstandard2.1, it requires .NET 6.0. See [this page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms) for a table of supported versions of .NET.
