### ISSUE TITLE
Migration from old Entity Framework, one complex request not execute properly

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#27649]
Hello guys, for my client i actually migrate an old stack Net framework 4.0/WCF/Entity framework 5 to a new stack .NET6/REST/Ef core 6.

The idea is to retrieve all the existing code because its really complex and made perfectly the job since years. 

I was able to make all the old work compile in the new environment without too many problems, with some adaptation.

Now i begin to run the code and the trouble started. I have a complex request which fail at execution with this message "Anomalie: The LINQ expression 'ProjectionBindingExpression: 0' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'"

this is the request
````C#
var result = Container.Histos_Enfs
                .Where
                (lHe =>
                    lHe.NumDos == pNumDos && !lHe.Histo.IsPattern
                    &&
                    (!lHe.AbsenceID.HasValue || lHe.AbsenceID == Absence.V_nValide || lHe.AbsenceID == Absence.PRESENT)
                    &&
                    (
                        //(lHe.Histo.Action.Grp1 != null && lHe.Histo.Action.Grp1.Num == 1)               // pour debug
                        (lHe.Histo.Action.Grp1 != null && lHe.Histo.Action.Grp1.ShowOnSummary)
                        //|| (lHe.Histo.Action.Grp2 != null && lHe.Histo.Action.Grp2.Num == 1)            
                        || (lHe.Histo.Action.Grp2 != null && lHe.Histo.Action.Grp2.ShowOnSummary)
                        || lHe.Histo.Action.ShowOnSummary
                    )
                 )
                .GroupBy
                (lHe => (lHe.Histo.Action.Grp1 != null && lHe.Histo.Action.Grp1ID == 1)
                    ? lHe.Histo.Action.Grp1ID
                    : (lHe.Histo.Action.Grp2 != null && lHe.Histo.Action.Grp2ID == 1)
                        ? lHe.Histo.Action.Grp2ID
                        : lHe.Histo.ActionID)
                .Select(lHe => lHe.OrderByDescending(lHe2 => lHe2.Histo.DtDeb).FirstOrDefault().Histo).Select(lH => new { DtDeb = lH.DtDeb, AxCode = lH.Action.Code }).ToList()
````

Do you see anything on this request which can explain that ? its normal for you it was working in old EF and not now ? i read somewhere we can't use navigation properties after a group by in ef core but i see nothing like that on the official doc, can you clarify that ?

thanks !

**Comment by smitpatel** [comment]
Can you share a stand-alone runnable repro code?

**Comment by roji** [comment]
@julienGrd yes, double ternary is supposed to work - do you have a repro where it fails?

We generally can't do much with a complicated LINQ query and no context - how you configure your model can have an important impact on how the query is executed, and that information isn't included. Typically you'd strip down your application until a minimal code repro is left which still triggers the exception.
