### ISSUE TITLE
[CompiledQuery] Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable cannot be used for return type 'System.Linq.IQueryable

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#27657]
Hello guys, i met an exception when i try to execute compiled queries in ef core 6
````
  static readonly Func<ModelContainer, int, byte?, IQueryable<Histo_Enf>> s_compiledGetHistosEnf =
 EF.CompileQuery<ModelContainer, int, byte?, IQueryable<Histo_Enf>>((ctx, pNumDos, pSejIndex)
 => (from histEnf in ctx.Histos_Enfs.Include("Histo.HIntervs")
     where histEnf.NumDos == pNumDos
         && !histEnf.Histo.IsPattern
         && histEnf.Histo != null
         && (!pSejIndex.HasValue || histEnf.SejourIndex == pSejIndex.Value)
     orderby histEnf.Histo.DtDeb
     select histEnf)
            ); 

var lHistos = s_compiledGetHistosEnf.Invoke(Container, pNumDos, lSejIndex);
````
this query throw an exception
Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1[Is.GeckosSL.EntityModel.Histo_Enf]' cannot be used for return type 'System.Linq.IQueryable`1[Is.GeckosSL.EntityModel.Histo_Enf]'

If i activate the SplitQuery globally the exception is slightly different
````
UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)
...
System.ArgumentException : 'Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1[Is.GeckosSL.EntityModel.Histo_Enf]' cannot be used for return type 'System.Linq.IQueryable`1[Is.GeckosSL.EntityModel.Histo_Enf]''
````

Whats wrong with my request ?

thanks !

**Comment by smitpatel** [comment]
> EF.CompileQuery<ModelContainer, int, byte?, IQueryable<Histo_Enf>>

EF.CompileQuery's return type cannot be of `IQueryable`, use `IEnumerable` instead.

For EF team: #14551 if we don't plan to support composition after EF.CompileQuery then TResult doesn't need to be of `IQueryable<T>` we could throw a better exception message here.

**Comment by smitpatel** [comment]
Can you elaborate? Are you trying to compose over result of CompileQuery?

**Comment by julienGrd** [comment]
not exactly other result, but associate the compiled query with other critera, for example
````
var lHistos = s_compiledGetHistosEnf.Invoke(Container, pNumDos, lSejIndex);
var lFilteredHisto = lHistos.Where(h => h.IsTrue).ToList().the SQL is executed here
````

I don't know if compiled query can bu used on this way on ef core. I make a migration from an old stack entity framework 5.0 (not core, the old one) and this way of working with compile query was OK

**Comment by julienGrd** [comment]
@ajcvickers  : yes it make sense, i understand the problem now. Maybe a better error message would be nice but otherwise it's close for me.
