### ISSUE TITLE
Allow templates to be placed anywhere instead of CodeTemplates from the scaffolder.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#27656]
On old ef6 projects, templates were generated along beside the edmx file (which could have been anywhere they wanted) and the files it generated automatically, in this case it would be great if such thing could be done here for compatibility.

The ability to have the templates picked up from anywhere within our projects from the scaffolder.

**Comment by bricelam** [comment]
Those templates in EF6 generated code directly from the edmx. There was [another set of templates](https://www.nuget.org/packages/EntityFramework.CodeTemplates.CSharp) in EF6 that were used when [generating code first from an existing database](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/existing-database#3-reverse-engineer-model) which also had to be in a specific place in the project: (we stole [the design from ASP.NET Scaffolding](https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/june/asp-net-mvc-override-the-default-scaffold-templates#override-the-scaffold-templates))

* CodeTemplates/
  * EFModelFromDatabase/
    * Context.cs.t4
    * Context.vb.t4
    * EntityType.cs.t4
    * EntityType.vb.t4

**But** I say all that just for historical context. We should still discuss the feasibility of this issue.

**Comment by AraHaan** [comment]
![image](https://user-images.githubusercontent.com/15173749/158740037-b7eec342-72e6-4e71-8bd3-61dc4536c58d.png)

**Comment by AraHaan** [comment]
Now that EFCore 7 has templates, I feel like a lot of the formatting issues could be closed now that is in the backlog.

**Comment by ajcvickers** [comment]
Note from triage: we don't plan to support this.
