### ISSUE TITLE
Relational-specific methods can only be used when the context is using a relational database provider.

### ISSUE THREAD

**Issue by priyankt3i** [dotnet/efcore#27667]
Do you plan to support CosmosDB? I am working on a REST API app using .Net 5.0 Entity Framework to manage a Database in Azure Cosmos DB. Recently I had to make some bulk changes and AddRangeAsync with SaveChanges() takes forever. So I found this extension but now I am not sure if you support Cosmosdb

I am using In Memory Storage with DbContext: 

 services
            .AddHealthChecks()
            .Services
            .AddHealthChecksUI()
            .AddInMemoryStorage();

services.AddDbContext<CompassContext>(opt => opt.UseCosmos(
            "https://localhost:8081",
            "<KEY>",
            databaseName: "<DBNAme>"));

Previous Working but slow Code:
            await _context.Students.AddRangeAsync(students);
            _context.SaveChanges();

New Code:
            await _context.BulkInsertAsync(students);

API Error: 500 
            error message : Relational-specific methods can only be used when the context is using a relational database provider.

**Comment by roji** [comment]
@priyankt3i are you asking about the BulkInsertAsync API? If so, that's not an EF Core API, but is coming from some 3rd-party library.
