### ISSUE TITLE
Different delete behaviour

### ISSUE THREAD

**Issue by Zefek** [dotnet/efcore#27661]
Hello,

I would like to ask, where is problem?

```C#
[ToTable("Entity")]
public class Entity
{
    [Key]
    public Guid Id {get; set; }
    public Address Address {get; set; }
    public Amount Insurance {get; set; }
}
```

Both property is mapped as owned entity to same table (Entity) as OwnOne. But I have exception:
'The foreign keys {'Id'} on 'Entity.Insurance#Amount' and {'Id'} on 'Address' are both mapped to 'Entity.FK_Entity_Entity_Id' but with different delete behavior ('Cascade' and 'Restrict').'

I cannot set delete behaviour on owned entities.

**Comment by roji** [comment]
@Zefek please post a full, runnable code sample, including the entire model and the context's model configuration.

**Comment by Zefek** [comment]
@roji I tried to extract configuration to small console project but it works. I work with large project and there is error. I don't know where is difference but configuration is same. In large project there is part in OnModelCreating method which takes all foreign keys where Cascade delete is set and change it to Restrict mode. 
But when I look into model (modelBuilder.Model.GetEntityTypes()) I can see foreign key but all they have Restrict model. 

I assume there is one foreign key with Cascade delete mode. I have two owned entities which are mapped to owner table. It means Amount Insurance and Amount GoodsAmount and it is mapped like:
entity.OwnsOne(k=>k.Insurance, insurance=> 
{
    insurance.ToTable("Entity);
    insurance.Property(amount=>amount.Amount).HasColumnName("InsuranceAmount);
    insurance.Property(currency=>currency.CurrencyId).HasColumnName("InsuranceCurrencyId);
}

entity.OwnsOne(k=>k.GoodsAmount, goodsAmount=> 
{
    goodsAmount.ToTable("Entity);
    goodsAmount.Property(amount=>amount.Amount).HasColumnName("GoodsAmount);
    goodsAmount.Property(currency=>currency.CurrencyId).HasColumnName("GoodsCurrencyId);
}

If I have only one owned entity there is not problem but there is problem when I have two entities as in example above. 
I thinks there would be something wrong in context configuration. I don't know where to see and what to see to check there is mistake. In small project it works perfectly but as part of large project it doesn't work. Where the message I wrote in first comment come from? What does it mean?

**Comment by Zefek** [comment]
I didn't find out what exactly caused this exception. It is clear there is one foreign key with cascade delete mode and another with restrict delete mode. I don't know why because I see all foreign key with restrict delete mode in ModelBuilder. 
But after I spend hours of debugging EF core with large project I decide to move base.OnModelCreating(modelBuilder) from begin to end as last command in OnModelCreating method. It works. There must be something what change foreign key delete mode and it is in relation to owned entities. It is very hard to find out because there is high DbContext inheritance depth in our large project. 
So issue can be closed. Thank you :)
