### ISSUE TITLE
FirstOrDefault when using datetime type fails

### ISSUE THREAD

**Issue by saasaTom** [dotnet/efcore#27684]
## File a bug

When using a FirstOrDefault on a subquery that doesn't exist for a column that is `datetime` in SQL server i.e. NOT `datetime2` the generated SQL tries to coallesce the subquery to `'0001-01-01T00:00:00.0000000'` which fails with the following conversion error:
```
SqlException: Conversion failed when converting date and/or time from character string.
```

### Include your code
```C#

-- Entity Definition
public class ActivityLog {
        [Column(TypeName = "datetime")]
        public DateTime SignInDateLocal { get; set; }
}

-- Model
public class PersonModel {
public string FirstName {get;set;}
public DateTime? SignInDateLocal {get;set;}
}

-- Code that fails with SQL error
var persons = persons.Select(p => new PersonModel() {
  FirstName = p.FirstName,
  SignInDateLocal = p.ActivityLog.OrderByDescending(a => a.SignInDateLocal).Select(a => a.SignInDateLocal).FirstOrDefault()
});

```

This generates the following SQL:
```sql
SELECT [p].[FirstName], COALESCE((
    SELECT TOP(1) [a].[SignInDateLocal]
    FROM [ActivityLog] AS [a]
    WHERE [p].[PersonID] = [a].[PersonID]), '0001-01-01T00:00:00.0000000') AS [D]
FROM [Person] AS [p]
GO

```
This query will fail if the person does not have an activity log entry as you cannot convert  '0001-01-01T00:00:00.0000000' to a datetime.

e.g. The following fails
`select convert(datetime,  '0001-01-01T00:00:00.0000000')`

EF should be able to take into account that the field has been defined as a `datetime` SQL type and instead use the value:
`convert(datetime,  '1753-01-01T00:00:00')`

Or realise that using FirstOrDefault won't work on a field defined as `datetime` and return null

Or provide a compile time error

### Include stack traces

```
SqlException: Conversion failed when converting date and/or time from character string.
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: WIndows
IDE: VS Code

**Comment by ajcvickers** [comment]
The problem here is that the CLR default value for DateTime cannot be represented as a SQL Serer `datetime`. The fix for this is to support specification of an explicit default, which is tracked by #17783. For now, the workarounds are to use `datetime2` or to make the property nullable such that the returned default is null.
