### ISSUE TITLE
Allow migration bundles to include migrations for multiple contexts

### ISSUE THREAD

**Issue by Pilchard123** [dotnet/efcore#27685]
If there are multiple contexts in a project that will all need deploying at once, the infrastructure for updating a database (and potentially the framework too, if the bundle is self-contained) must be included in each bundle. While storage space is generally relatively cheap and network speed generally relatively fast, it does seem redundant to have the infrastructure bits copied into each bundle when they are (I assume) identical in each one.

It would be good if it could be possible to make a bundle that cntains migrations for multiple contexts, maybe by using `dotnet ef migrations bundle --contexts [context1 context2 ...]` or `dotnet ef migrations bundle --allcontexts`. It could be run using an analogous parameter list (`bundle.exe --contexts [context1 context2 ...]` or `bundle.exe --allcontexts`).

**Comment by ajcvickers** [comment]
Note from triage: bundles are designed for a single context. It adds considerable complexity to support multiple different contexts in one bundle, so this is not something we plan to implement.

**Comment by w0244079** [comment]
So what's the workaround if you have multiple contexts?

**Comment by ajcvickers** [comment]
@w0244079 Create a bundle per context.

**Comment by Herve-M** [comment]
Sorry to revive this old thread, but the answer is too light in my sense. 

> @w0244079 Create a bundle per context.
How should we know which context is being worked on from within the `EF.IsDesignTime` scope in program/startup/setup? 

Today if a bundle is created blindly from a project using 2 or more DbContext supporting migration with possibly to diff. connection-string, it will work if provided appsettings.json is setup correctly; without any warning at build or run.  _(btw, `--connection` have undocumented behavior is this case)_

Should we name our bundle with the context name and do logic depending on it?

**Comment by ajcvickers** [comment]
> Today if a bundle is created blindly from a project using 2 or more DbContext supporting migration ,with possibly two diff. connection-string provided by appsettings.json, it will work without any warning at build or run. (btw, --connection have undocumented behavior is this case)

This should not be happening. If there are two DbContext types, then the command should fail creating the bundle unless the DbContext type is specified. Please can you open a _new issue_ and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Herve-M** [comment]
> This should not be happening.

Actually, after trying to re-produce the issue I just found out that when launching a generated bundle,  `EF.IsDesignTime` isn't set to true; making the migration use the dev. env. startup behavior which in my cases do the migrations for all contexts and others DI stuff. 

Not sure it is normal or not, I was expecting to have a lightened version of startup from bundle context.

**Comment by cultivatorchosen** [comment]
This could work wonders for you, https://contentful-paid.github.io/miLlhuTD8g4yO4JUkTfnvo5Q02pl8oZwdolfKiP5YSgCgrWeFW8BRPum8Amws/ I think
