### ISSUE TITLE
THIRD-PARTY-NOTICES.TXT needed for efcore repo?

### ISSUE THREAD

**Issue by leecow** [dotnet/efcore#27699]
If third-party components are used in a .NET repo, a THIRD-PARTY-NOTICES.TXT detailing any third-party source code included in final built artifacts, along with the controlling license information must be included and maintained at the root of the affected repo ([dotnet/runtime example](https://github.com/dotnet/runtime/blob/main/THIRD-PARTY-NOTICES.TXT)). 

During product build, these files are used to create a unified TPN file and included in the final installer builds ([example](https://github.com/dotnet/runtime/blob/main/src/installer/pkg/THIRD-PARTY-NOTICES.TXT)) and source-build offerings. 

Some repos will not need this notice as no third-party code is included in the final build artifacts.

Tracking issue: https://github.com/dotnet/runtime/issues/61466

**Comment by ajcvickers** [comment]
@leecow It was my understanding from @Pilchie that third-party notices were only needed for source code that was included in the built artifacts. Are they also required for referencing any third-party package?

**Comment by Pilchie** [comment]
That's my understanding as well - if the 3rd party content is not inside the nupkg, then why would we include a 3PN for it?

**Comment by leecow** [comment]
Yes, thanks for that clarification; I'll add it to the description. This process is to somewhat formalize repo status as part of the overall source-build effort. It's fine if the answer is "we don't do that".

**Comment by ajcvickers** [comment]
@leecow Confirmed that there is no third-party code included in the build artifacts.
