### ISSUE TITLE
EFCore will not populate `Id` after save when the collection is not of concrete type

### ISSUE THREAD

**Issue by PaperNick** [dotnet/efcore#27698]
## .NET Info

I'm using the stable .NET 6.0.100 version.

```
.NET SDK (reflecting any global.json):
Version:   6.0.100
Commit:    9e8b04bbff

Runtime Environment:
OS Platform: Linux

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.Sqlite
```

## Problem 

When a generic LINQ collection is passed to `dbContext.AddRange()`, the identity `Id` field of the Entity doesn't contain the value generated from the database.

The identity `Id` field is populated correctly only when a collection of a concrete type is given to `dbContext.AddRange()`.

I've reproduced this problem with `Microsoft.EntityFrameworkCore.Sqlite` and `Npgsql.EntityFrameworkCore.PostgreSQL` providers. I assume that other providers have the same issue.

## Steps to reproduce

1. Create a new webapi project
    ```
    dotnet new webapi
    ```
2. Navigate to `Controllers/WeatherForecastController.cs` and paste the code given below
3. Install the project dependencies
    ```
    dotnet add package Microsoft.EntityFrameworkCore.Sqlite
    dotnet add package Microsoft.EntityFrameworkCore.Design
    dotnet new tool-manifest
    dotnet tool install dotnet-ef
    dotnet tool restore
    dotnet restore
    ```
4. Create the database
    ```
    dotnet ef migrations add InitialCreate
    dotnet ef database update
    ```
5. Start the project
    ```
    dotnet watch
    ```
6. Open the Swagger UI page and interact with the endpoints
7. Upon inspecting the response of `GET ​/Blog/GenericCollection`, we see that the `Id` field **is not** populated
8. Upon inspecting the response of `GET ​/Blog​/ConcreteCollection`, we see that the `Id` field is correctly populated

### Code to reproduce

```C#
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFCoreIdField;

public class BlogContext : DbContext
{
    public DbSet<BlogPost> BlogPosts { get; set; }

    public static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=project.db")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}

public class BlogPost
{
    public long Id { get; set; }

    public string Content { get; set; }
}


[ApiController]
[Route("[controller]")]
public class BlogController : ControllerBase
{
    private static readonly string[] BlogPostsContent = new string[]
    {
        "Hello world! This is my first blog post.",
        "Second blog. This is my second blog post.",
    };

    [HttpGet]
    [Route("GenericCollection")]
    public IEnumerable<BlogPost> GenericCollection()
    {
        using var db = new BlogContext();

        IEnumerable<BlogPost> posts = BlogPostsContent
            .Select(content => new BlogPost { Content = content });

        db.AddRange(posts);
        db.SaveChanges();

        // BlogPost.Id field DOES NOT contain the generated value from DB
        return posts;
    }

    [HttpGet]
    [Route("ConcreteCollection")]
    public IEnumerable<BlogPost> ConcreteCollection()
    {
        using var db = new BlogContext();

        IEnumerable<BlogPost> posts = BlogPostsContent
            .Select(content => new BlogPost { Content = content })
            .ToArray();

        db.AddRange(posts);
        db.SaveChanges();

        // BlogPost.Id now contains the generated value from DB
        return posts;
    }
}
```

**Comment by joakimriedel** [comment]
@PaperNick each time you enumerate `posts` in the `GenericCollection` method, you will get two new `BlogPost` objects. **By enumerating twice**, first in the call to `db.AddRange(posts)` and second in `return posts`, you are generating four `BlogPost` objects in total, whereof two will be saved to database and the other two will be returned from your method.

This is expected behaviour.

By using `ToArray` in `ConcreteCollection` **you will only enumerate once** and hence generate only two `BlogPost` objects which will be used both for adding to database and returning from your method.

**Comment by PaperNick** [comment]
Thanks for the clarification @joakimriedel! I wasn't aware of this behavior.
I assume that this is more related to Linq and collections in general rather than EFCore. I'll read the docs to get myself up to speed.

Thank you once again, and sorry for bothering :pray:
