### ISSUE TITLE
BenchmarkDotNet - EF6 performs better than EF Core for ToList()

### ISSUE THREAD

**Issue by BrianMikinski** [dotnet/efcore#27694]
## BenchmarkDotNet - EF6 performs better than EF Core for simple ToList() calls
Hi EF Core Team!

First off, thank you all for the incredible work you do. I am always impressed with the new features the community receives with every release. Y'all are awesome! 

🎊 🥇 🎊 

# EF Core vs EF6 Benchmarking
I was recently doing some EF Core vs EF6 performance comparisons using BenchmarkDotNet and I've been coming across some peculiarities in the result's.  Effectively, EF6 is beating EF Core for performance in almost all benchmarks I am running and I cannot explain why that is the case. Overall, I would expect EF Core to perform better than EF6 for most benchmarks, especially benchmarks returning larger lists of entities.

You can find my full project on my [github](https://github.com/BrianMikinski/EfPerformance).

## Solution Layout
I have an EF6 project called **Blog** and and EF Core project called CoreBlog. 

The EF6 database is being deployed using the package manager while the EF Core database is being deployed via [command line scripts](https://github.com/BrianMikinski/EfPerformance/tree/main/CoreBlog).

I have also automated my benchmarks with PowerShell Scripts and those can be found in the [EfPeformance](https://github.com/BrianMikinski/EfPerformance/tree/main/EfPerformance) project.

The most egregious offender for the Benchmarks is the [RetrieveAllEntitiesBenchmark](https://github.com/BrianMikinski/EfPerformance/blob/main/SharedModels/RetrieveAllEntitiesBenchmark.cs) (runnable by the following [PowerShell script](https://github.com/BrianMikinski/EfPerformance/blob/main/EfPerformance/retrieveAllEntities.Benchmark.ps1))

A sample of the code can be seen below.

### Example code

```C#
    /// <summary>
    /// Retrieve and update a single entity with ef 6
    /// </summary>
    [BenchmarkCategory(nameof(RetrieveManyEntitiesBenchmark)), Benchmark(Baseline = true)]
    public void PostRetrieveListEf6()
    {
        var posts = _blogContext
                     .Posts
                     .AsNoTracking()
                     .ToList();
    }

    /// <summary>
    /// Retrieve and update a single entity with ef core
    /// </summary>
    [BenchmarkCategory(nameof(RetrieveManyEntitiesBenchmark)), Benchmark]
    public void PostRetrieveListEfCore()
    {
        var posts = _coreBlogContext
                      .Posts
                      .AsNoTracking()
                      .ToList();
    }
```

### BenchmarkDotnet Output
``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1586 (21H1/May2021Update)
Intel Core i5-6200U CPU 2.30GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET SDK=6.0.201
  [Host]     : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
  Job-GARFUT : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT

InvocationCount=1  UnrollFactor=1  WarmupCount=1  
Categories=RetrieveManyEntitiesBenchmark  

```
|                 Method |     Mean |    Error |    StdDev |      Min |        Max | Ratio | RatioSD |
|----------------------- |---------:|---------:|----------:|---------:|-----------:|------:|--------:|
|    PostRetrieveListEf6 | 358.8 ms | 16.10 ms |  46.21 ms | 279.3 ms |   485.8 ms |  1.00 |    0.00 |
| PostRetrieveListEfCore | 931.0 ms | 43.85 ms | 125.09 ms | 706.6 ms | 1,301.5 ms |  2.63 |    0.44 |

While the Intel Core i5 above is a bit dated but I have tested this same benchmarking code on other machines and seen the same results.

Anyways, thanks in advance for any help diagnosing this performance issue and keep up the great work!

**Comment by AraHaan** [comment]
This is a bit interesting.

**Comment by BrianMikinski** [comment]
@roji @AraHaan @ajcvickers -

A quick update -

If you pull the repo down now you'll see a big perf improvement on the EF Core tests.  I am now reusing the same context for every iteration of the benchmark and EF Core beats EF6 hands down for every iteration.

See the following files for more context -

[RetrieveManyEntitiesBenchmark.cs](https://github.com/BrianMikinski/EfPerformance/blob/main/SharedModels/RetrieveManyEntitiesBenchmark.cs)

```c#

// benchmark class
[GroupBenchmarksBy(BenchmarkLogicalGroupRule.ByCategory)]
[CategoriesColumn]
public class RetrieveManyEntitiesBenchmark : BenchmarkBase
{
    [GlobalSetup]
    public void GlobalSetup()
    {
        AddPostsToSeedLimit(100000, true);
    }

    [IterationSetup]
    public void IterationSetup()
    {
        NewDbContexts(); // code in this base class method to create new db context for each iteration is now disabled
    }
   
    // ef core vs ef6 tests found below

```

[BenchnmarkBase.cs](https://github.com/BrianMikinski/EfPerformance/blob/main/SharedModels/BenchmarkBase.cs)

```C#
   ...
  // benchmark base class
  public abstract class BenchmarkBase
  {
     // ...
     // initialization properties
     // ...


    public BenchmarkBase()
    {
        _coreBlogContext = new();
        _blogContext = new();
    }

    /// <summary>
    /// Create new db contexts for benchmarks
    /// </summary>
    protected void NewDbContexts(bool isEnabled = false)
    {
        if (isEnabled)
        {
            _coreBlogContext = new();
            _blogContext = new();
        }
    }
 
    // remainder of Benchmark base class
```

My best guess for the improved EF Core perf is that the EF query cache is able to reuse the same query plan for each query rather than having to regenerate the query for each new db context.

**Comment by roji** [comment]
> If you pull the repo down now you'll see a big perf improvement on the EF Core tests. I am now reusing the same context for every iteration of the benchmark and EF Core beats EF6 hands down for every iteration.

You may want to also try using [context pooling](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling), which should bring similar optimized perf without forcing you to reuse the same instance in your code.

> My best guess for the improved EF Core perf is that the EF query cache is able to reuse the same query plan for each query rather than having to regenerate the query for each new db context.

Whether you use the same DbContext instance or not isn't related to whether EF reuses cached queries or not.

I'll investigate this when I get a spare moment.

**Comment by roji** [comment]
I took a look and could not reproduce your results. Since your repro benchmark suite is somewhat elaborate and I encountered some issues creating and seeding the databases, I whipped up a quick comparison which does the same thing: query 1000 default/empty rows via EF Core and EF6; EF Core is usually faster (but see below), and never as slow as in your scenario.

It's certainly possible that your benchmark does something slightly different, which is somehow much slower on EF Core than it is on EF6 - or it could be an issue in the benchmarks themselves. Note also that your absolute numbers are very slow: 358ms or 931ms is a very long time for a single query pulling back 1000 mostly empty rows.

The code for my benchmark is minimal and included below - please take a look and see if something stands out in comparison to yours.

Results:

|       Method | Rows |       Mean |    Error |    StdDev |     Median |
|------------- |----- |-----------:|---------:|----------:|-----------:|
|       EFCore |    1 |   974.1 us | 44.82 us | 131.46 us |   960.2 us |
| EFCorePooled |    1 |   479.4 us | 31.75 us |  93.11 us |   444.4 us |
|          EF6 |    1 |   752.9 us | 28.42 us |  81.09 us |   743.3 us |
|       EFCore |  100 |   593.3 us | 10.00 us |   8.87 us |   593.4 us |
| EFCorePooled |  100 |   370.0 us |  5.94 us |   6.10 us |   371.2 us |
|          EF6 |  100 |   931.1 us | 29.72 us |  87.15 us |   919.6 us |
|       EFCore | 1000 | 1,316.6 us | 18.80 us |  17.59 us | 1,311.5 us |
| EFCorePooled | 1000 | 1,123.6 us | 13.69 us |  11.43 us | 1,124.2 us |
|          EF6 | 1000 | 2,149.7 us | 42.79 us | 101.70 us | 2,137.3 us |

Note that for a single row, EF Core is slower than EF6 unless using context pooling; this could be the cost of setting up all the scoped services for each instance (which isn't done when context pooling is on). For multiple rows, EF Core batches and EF6 doesn't, so EF Core quickly becomes much faster.

<details>
<summary>Benchmark code</summary>

```c#
BenchmarkRunner.Run<Benchmarks>();

public class Benchmarks
{
    private const string ConnectionString = "Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false";

    [Params(1, 100, 1000)]
    public int Rows { get; set; }

    private DbContextOptions<EfCoreContext> _efCoreOptions;
    private PooledDbContextFactory<EfCoreContext> _pooledFactory;

    [GlobalSetup]
    public void Setup()
    {
        using var connection = new SqlConnection("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Trust Server Certificate=true");
        connection.Open();

        using var command = new SqlCommand(@"
DROP TABLE IF EXISTS [Posts];
CREATE TABLE [Posts] (
    [Id] uniqueidentifier NOT NULL,
    [Title] nvarchar(50) NULL,
    [Content] nvarchar(1000) NULL,
    [CategoryId] uniqueidentifier NULL,
    CONSTRAINT [PK_Posts] PRIMARY KEY ([Id])
);
", connection);
        command.ExecuteNonQuery();

        command.CommandText = "INSERT INTO [Posts] (id) VALUES (NEWID())";
        for (var i = 0; i < Rows; i++)
        {
            command.ExecuteNonQuery();
        }

        var efCoreOptionsBuilder = new DbContextOptionsBuilder<EfCoreContext>();
        efCoreOptionsBuilder.UseSqlServer(ConnectionString);
        _efCoreOptions = efCoreOptionsBuilder.Options;

        _pooledFactory = new PooledDbContextFactory<EfCoreContext>(_efCoreOptions);
    }

    [Benchmark]
    public void EFCore()
    {
        using var context = new EfCoreContext(_efCoreOptions);

        _ = EntityFrameworkQueryableExtensions.AsNoTracking(context.Posts).ToList();
    }

    [Benchmark]
    public void EFCorePooled()
    {
        using var context = _pooledFactory.CreateDbContext();

        _ = EntityFrameworkQueryableExtensions.AsNoTracking(context.Posts).ToList();
    }

    [Benchmark]
    public void EF6()
    {
        using var context = new Ef6Context();

        _ = context
            .Posts
            .AsNoTracking()
            .ToList();
    }

    public class EfCoreContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public EfCoreContext(DbContextOptions<EfCoreContext> options)
            : base(options)
        {
        }

        public Microsoft.EntityFrameworkCore.DbSet<Post> Posts { get; set; }
    }

    public class Ef6Context : System.Data.Entity.DbContext
    {
        public Ef6Context()
            : base(ConnectionString)
        {
            Configuration.LazyLoadingEnabled = false;
        }

        public System.Data.Entity.DbSet<Post> Posts { get; set; }
    }


    public class Post
    {
        public Guid Id { get; set; }

        [StringLength(50)]
        public string Title { get; private set; }

        [StringLength(1000)]
        public string Content { get; set; }

        public Guid? CategoryId { get; set; }
    }
}
```

</details>

**Comment by BrianMikinski** [comment]
@roji thanks for looking into this and building out a sample repo. For reading a single record on a new EF Core DbContext it seems totally reasonable that configuring new services would take a bit longer than the EF6 version. When I have a second, I'll run the sample that you provided, see if I can get some comparable perf and then test it against my repo. Thanks again for looking into this. I much appreciate it!

**Comment by ErikEJ** [comment]
@roji  >> For multiple rows, EF Core batches and EF6 doesn't, so EF Core quickly becomes much faster.

Is that not only applicable to  SaveChanges() ??

**Comment by AraHaan** [comment]
I wonder if the performance of doing EFCoreStoredProcedures and using them with or without being pooled would make a huge performance difference?

**Comment by BrianMikinski** [comment]
@AraHaan @ErikEJ @roji @ajcvickers I should have followed up with this after @roji replied to me. To summarize, I had my benchmarkdotnet tests poorly configured and the perf of EF Core (especially with pooled contexts) is definitely better than EF6 for ToList. If you look at my repo now I've fixed the core issue. Effectively, because I was doing all of my EF6 and EfCore context setup within each iteration run, it was skewing the results of all tests and making the EF6 runs appear more performant or equally as performant as EF Core. Because each iteration new'ed up every context, it didn't matter which was actually running faster because the latest time addition to each test was the same from the contexts. If you want me to further elaborate I can do so in another post to this thread or elsewhere.

**Comment by roji** [comment]
@ErikEJ 

>> For multiple rows, EF Core batches and EF6 doesn't, so EF Core quickly becomes much faster.
>
> Is that not only applicable to SaveChanges() ??

That's true - I must have gotten confused above...

@AraHaan 

> I wonder if the performance of doing EFCoreStoredProcedures and using them with or without being pooled would make a huge performance difference? [...]

It obviously depends on your specific scenario, and how much work your stored procedure does. Initializing a new context should be a more or less fixed overhead for every time a context gets initialized, and it's that overhead that gets eliminated when context pooling is used. It should be very easy to set up a benchmark as above for your specific scenario and find out how significant that overhead is.

Note that this overhead is essentially orthogonal to whether tracking is being used or not.

**Comment by ErikEJ** [comment]
@roji Still interesting that EF Core is slightly slower than EF6 is this benchmark getting many rows from a wide table (but faster that Dapper) https://github.com/FransBouma/RawDataAccessBencher/blob/master/Results/20220722_net6_2.txt#L66
