### ISSUE TITLE
What causes differences in verbosity between IDesignTimeDbContextFactory class library and console application project?

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/efcore#27704]
I have two projects:

 - a class library project using `IDesignTimeDbContextFactory` as follows:

    class Program : IDesignTimeDbContextFactory<TheContext>
    {
        public TheContext CreateDbContext(string[] args)
        {
            IConfiguration config = new ConfigurationBuilder()
                                        .AddUserSecrets<MyUserSecrets.Empty>()
                                        .Build();

            string connectionString = config.GetConnectionString("Duplicate");

            string assemblyName = Assembly.GetAssembly(typeof(MigrationTarget.Empty))!
                                          .GetName()
                                          .Name!;

            var dcob = new DbContextOptionsBuilder<TheContext>()
                            .UseSqlServer(connectionString, ssdcob => ssdcob.MigrationsAssembly(assemblyName));

            return new(dcob.Options);
        }
    }

- a console application project as follows:

```
Host.CreateDefaultBuilder()
    .ConfigureHostConfiguration(icb => icb.AddUserSecrets<MyUserSecrets.Empty>())
    .ConfigureServices((hbc, isc) =>
    {
        isc.AddDbContext<TheContext>(dcob =>
        {
            string connectionString = hbc.Configuration.GetConnectionString("Duplicate");

            string assemblyName = Assembly.GetAssembly(typeof(MigrationTarget.Empty))!
                                          .GetName()
                                          .Name!;

            dcob.UseSqlServer(connectionString, ssdcob => ssdcob.MigrationsAssembly(assemblyName));
        });
    })
    .Build();
```

When I invoke `update-database`, the former project produces fewer logs compared to the latter project.

former:

```
PM> update-database
Build started...
Build succeeded.
Applying migration '20220325084814_Initialization'.
Done.
```

latter:

```
PM> update-database
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.3 initialized 'TheContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.3' with options: MigrationsAssembly=MigrationTarget 

........ trimmed because too long ............

Done.
```

### Question

What causes this difference?

**Comment by ajcvickers** [comment]
@pstricks-fans With the console application, your application code is executed in order to discover services, which is in turn used to discover context types for the IDesignTimeDbContextFactory. The application code is logging. With the class library, there is no application code to run, and hence no application logging.

See also #27322 and #8350.

**Comment by pstricks-fans** [comment]
@ajcvickers : OK. Thank you very much.
