### ISSUE TITLE
Enabling TPT with default table name.

### ISSUE THREAD

**Issue by Abdragiz** [dotnet/efcore#27702]
## Ask a question
Is it possible to enable TPT without providing table name in .ToTable() method, so that default table name (name of DbSet property) is used?

### Include provider and version information
EF Core version: Microsoft.EntityFrameworkCore.Relational 6.0

**Comment by ajcvickers** [comment]
@Abdragiz Not currently; this is covered by #27642.

**Comment by ajcvickers** [comment]
@Abdragiz It's also worth pointing out that in EF Core 7.0 it will be possible to specify this once-per-hierarchy instead of calling `ToTable` on every table.
