### ISSUE TITLE
Hybrid TPT and TPH

### ISSUE THREAD

**Issue by adamreed90** [dotnet/efcore#27707]
I have a TPT database model created, however for one of the Types I would like to use TPH for that specific type and it's inherited typed and use TPH on those entities. 

However, I get the error: 
The property 'CallLogType' cannot be added to entity type 'LogDetail' because it is declared on the CLR type 'CallLogDetail'.

**Comment by ajcvickers** [comment]
@adamreed90 We don't plan to support hybrid inheritance mappings in EF Core. In EF6 it didn't work correctly for many cases, and for EF Core the complexity/cost of implementation and maintenance is too high for the value it adds.
