### ISSUE TITLE
Remove System.Diagnostics.DiagnosticSource and System.Collections.Immutable for reference and runtime pack version.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#27715]
The discussion was started in https://github.com/dotnet/efcore/pull/27673, however it was not completed on if I should open a pull request with my already made changes to remove these dependencies as they can be replaced with the runtime and ref pack versions of them for .NET 6+ when using efcore which can help clean up the dependencies list (as well as prevent possible version downgrades for them).

Also another thing I think is also the case for S.D.DS and S.C.I:
- the API shape seems to not change much for a while now on the assemblies (that I know of so far)
- the API on these assemblies seems to be completely (or almost if not completely) stable
- other things I cannot think of at the moment.

As such I think the best route for these is to utilize the built in copies on the default ``Microsoft.NETCore.App`` framework packs over the package reference for this reason, if new functionality is required (if new apis are added to them), then require them to update their runtime and ref packs.

**Comment by AraHaan** [comment]
Can we also try unpinning to preview.2 for preview.4?

**Comment by ajcvickers** [comment]
@AraHaan Thanks; we have merged the PR.
