### ISSUE TITLE
Should you be able to avoid circular dependency error if all ID's are manually assigned?

### ISSUE THREAD

**Issue by mattbrailsford** [dotnet/efcore#27714]
I'm trying to persist a bunch of entities at the same time, but there is a circular dependency, but from what I can tell regarding the circular dependency error, it's usually explained around needing to lookup / validate the DK ID's. In my application though, all ID's are assigned at runtime and so there should be all the required knowledge within the transaction to know that everything will be valid once persisted. In this case then, is there any way to persist all these entities in one go without the warning? Or will I still need to trigger multiple `SaveChanges()`? 

A simplified cut down version of my models would be something like:

````csharp
public class StoreState
{
    public Guid Id { set; get; }
    public Guid? BaseCurrencyId { set; get; }
    public Guid? DefaultCountryId { set; get; }
    public Guid? DefaultTaxClassId { set; get; }
}

public class CurrencyState
{
    public Guid Id { set; get; }
    public Guid StoreId { set; get; }
}

public class CountryState
{
    public Guid Id { set; get; }
    public Guid StoreId { set; get; }
}

public class TaxClassState
{
    public Guid Id { set; get; }
    public Guid StoreId { set; get; }
}
````

With my mappings

````csharp
internal class StoreConfiguration : AggregateConfigurationBase<StoreState>
{
    public override void Configure(EntityTypeBuilder<StoreState> builder)
    {
        builder.HasKey(x => x.Id);

        ...

        builder.HasOne<CurrencyState>().WithMany().HasForeignKey(x => x.BaseCurrencyId);
        builder.HasOne<CountryState>().WithMany().HasForeignKey(x => x.DefaultCountryId);
        builder.HasOne<TaxClassState>().WithMany().HasForeignKey(x => x.DefaultTaxClassId);
    }
}

internal class CurrencyConfiguration : AggregateConfigurationBase<CurrencyState>
{
    public override void Configure(EntityTypeBuilder<CurrencyState> builder)
    {
        builder.HasKey(x => x.Id);

        ...

        builder.HasOne<StoreState>()
            .WithMany()
            .HasForeignKey(x => x.StoreId)
            .IsRequired();
    }
}

internal class CountryConfiguration : AggregateConfigurationBase<CountryState>
{
    public override void Configure(EntityTypeBuilder<CountryState> builder)
    {
        builder.HasKey(x => x.Id);

        ...

        builder.HasOne<StoreState>()
            .WithMany()
            .HasForeignKey(x => x.StoreId)
            .IsRequired();
    }
}

internal class TaxClassConfiguration : AggregateConfigurationBase<TaxClassState>
{
    public override void Configure(EntityTypeBuilder<TaxClassState> builder)
    {
        builder.HasKey(x => x.Id);

        ...

        builder.HasOne<StoreState>()
            .WithMany()
            .HasForeignKey(x => x.StoreId)
            .IsRequired();
    }
}
````

All entities are assigned their ID before being added to the DB Context, the store is added first, followed by all the child entities and then the store is updated with the ID's of the child entities in the relevant properties (obviously creating the circular dependency). 

When I then attempt to persist everything with a single `SaveChanges()` I then reiceive the error

````
Unable to save changes because a circular dependency was detected in the data to be saved: 'StoreState { 'Id': f4ff9a50-89aa-466e-9f73-017fcb7dd173 } [Added] <- ForeignKey { 'StoreId': f4ff9a50-89aa-466e-9f73-017fcb7dd173 } CurrencyState { 'Id': e4c03f14-6b1c-4528-ba8c-017fcb7dd176 } [Added] <- ForeignKey { 'BaseCurrencyId': e4c03f14-6b1c-4528-ba8c-017fcb7dd176 } StoreState { 'Id': f4ff9a50-89aa-466e-9f73-017fcb7dd173 } [Added]'.
````

EF Core version:  5.0.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 11
IDE:  Visual Studio Community 2022 - 17.06

**Comment by mattbrailsford** [comment]
The only reason I can think why this would be the case could be because all changes occur at once, such that store is tried to be added with the child ID's set and visa-versa. I wonder if in these scenarios could there be an API to define a "flush" point in the change tracking such that when the SQL commands are generated, they are split and applied in an point order?

    - Store entity added
    - Create flush point
    - Child entity 1 added
    - Child entity 2 added
    - Store updated with child ids

This could then result in the SQL being sent like

    - Begin transaction
    - Insert store (with child ID's not set)
    - Insert child entity 1
    - Insert child entity 2
    - Update store with changes that occurred after first flush point (child ID's added)
    - Commit transaction

**Comment by ajcvickers** [comment]
@mattbrailsford The problem is that the relational database provider will throw with a constraint exception on one or the other FK. Doing a two-stage update where nulls are inserted first is tracked by #1699.
