### ISSUE TITLE
Migration Update Problem Due to Non-English Character in Database Name

### ISSUE THREAD

**Issue by memoony** [dotnet/efcore#27712]
I'm having a problem doing a migration update.

The name of the database given to me is made with a non-English naming like `ZİRVEDB`. I don't know why they did such a thing, but they named the database like this in Microsoft SQL Server.

The "ConnectionStrings" in the `appsettings.json` looks like this:

```C#
{
  "ConnectionStrings": {
    "DefaultConnection" : "Server=myServerAddress;Database=ZİRVEDB;User Id=myUsername;Password=myPassword;"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
```
`Program.cs` looks like this:

```C#
global using MyAPI.Data;
global using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddDbContext<DataContext>(options =>
{
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
});

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

And  when I try to `dotnet ef database update`, due to non-English character; it creates a new database like `Z�RVEDB` and saves the migration there. But I already have an existing database and I want it to save in that database.

How can I solve this problem?

Thanks.

Target framework: .NET 6.0
EF Core version: 6.0.3 (latest)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10

**Comment by bricelam** [comment]
Have you checked the encoding of `appsettings.json`? This might be an issue with Microsft.Extension.Configuration...

**Comment by Memoony** [comment]
> Have you checked the encoding of `appsettings.json`? This might be an issue with Microsft.Extension.Configuration...

Yes, I checked. Everything seems correct.

**Comment by Memoony** [comment]
> Have you checked the encoding of `appsettings.json`? This might be an issue with Microsft.Extension.Configuration...

After you said it, while checking again, I opened the `appsettings.json` file with notepad and saved it as `UTF-8` via the "save as" option. After that, when I tried to migration again, the problem was solved.
