### ISSUE TITLE
Feature request: Providing us with MigrationsAssembly<T>()

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/efcore#27711]
The following overload allows
```
public static IConfigurationBuilder AddUserSecrets<T>(this IConfigurationBuilder configuration) where T : class
{
      return configuration.AddUserSecrets(typeof(T).Assembly, optional: true, reloadOnChange: false);
}
```
us to write 
```
icb.AddUserSecrets<MyProject.Something>();
```
instead of 
```
icb.AddUserSecrets(typeof(MyProject.Something).Assembly);
```

### Request

I think it is a good idea if we can also write
```
dcob.UseSqlServer(constr, _=> _.MigrationsAssembly<MyProject.Something>());
```
instead of
```
dcob.UseSqlServer(constr, _=> _.MigrationsAssembly(typeof(MyProject.Something).Assembly.GetName().Name));
```

So the proposed addition looks like the following:
```
public virtual TBuilder MigrationsAssembly<T>() where T : class
{
     return MigrationAssembly(typeof(T).Assembly.GetName().Name);
}
```

**Comment by roji** [comment]
The point of MigrationsAssembly() is frequently to split out migrations to another project which isn't referenced from the main project - that's why it accepts a string.

But an overload which accepts an Assembly could be helpful for some scenarios (I'm personally against a `MigrationsAssembly<T>` overload, as the meaning/function of the type parameter isn't clear).

**Comment by ajcvickers** [comment]
@pstricks-fans Almost always referencing the assembly directly is either not needed or results in a circular reference. Are you using this in a case where the migration assembly must be explicitly specified and where this would not create a circular reference? If so, can you give details?

**Comment by pstricks-fans** [comment]
@ajcvickers I usually separate entity model, database context, migration, migrating startup, scaffolding startup and application in their own projects. For example, in the [migrating startup](https://github.com/pstricks-fans/EFCoreSolution/blob/main/MigrationStartup/Program.cs), I need to reference the migration project assembly.

**Comment by ajcvickers** [comment]
Note from triage: low value; this is not something we plan to implement.
