### ISSUE TITLE
Groub by not working at all

### ISSUE THREAD

**Issue by lmartinez-innovaj** [dotnet/efcore#27717]
## File a bug

Group by not working, no way, no table. Just group by whatever column I choose, it returns this exception

```
The LINQ expression 'DbSet<Readings>()
    .GroupBy(r => r.Id)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

This example just group by id and fails. Is happening for all the entities in 3 different application, with different db context and the same version of ef core (6.x)

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.1.1 & linqpad 7.2.7

**Comment by smitpatel** [comment]
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
