### ISSUE TITLE
Question: Use SaveChanges interception to perform actions after database update was successful

### ISSUE THREAD

**Issue by pjonusas** [dotnet/efcore#27725]
### Question

We're currently using SavedChangesAsync() from SaveChanges interception to publish domain event, which among other data contains affected records' ids. In the event handler we pull records based on these ids and perform some actions based on other properties. Unfortunately we noticed that if we don't introduce some manual delay, sometimes it seems that handler pulls data before changes were saved.

Is there a way to use interceptor and make sure it performs some actions (e.g. publish event) after database was successfully updated?

### Provider and version information

EF Core version: 6.0.1
Database provider: EntityFrameworkCore.SqlServer
Target framework: NET 6.0

**Comment by roji** [comment]
EF Core only calls your ISaveChangesInterceptor.SavedChanges after all SaveChanges completed and all changes have been committed to the database. Once the commit completes, another query (e.g. from your event handler) should generally always see the updated data; if that really isn't the case and SQL Server still shows the database state from before the commit, there unfortunately isn't anything EF Core can do about it.

But I'd double-check to confirm what you're seeing, since the database really should always return the updated state after commit. For example, can you put together a standalone repro which shows this happening?

**Comment by pjonusas** [comment]
Hi @roji, thanks for your response, will try to find time to setup standalone repro, meanwhile here is some simplified logic on how we have this implemented:

```
public override async ValueTask<int> SavedChangesAsync(
    SaveChangesCompletedEventData eventData,
    int result,
    CancellationToken cancellationToken = default)
{
    var records = changeTracker.Entries<RecordAggregate>()
        .Where(entry => entry.Entity.ModifiedBy != "ParticularDomainEvent")
        .Select(entry =>
            new UpdatedRecordDataDTO(
                entry.Entity,
                IndexActionType.MergeOrUpload))
        .ToList();

    if (records.Count() > 0)
    {
        var batchedEvents = ParticularDomainEvent.BatchEvents(records).ToList();

        await TransactionUtility.SuppressTransactionScope(
            () => _eventPublisher.PublishAsync(batchedEvents));
    }

    return await ValueTask.FromResult<int>(result);
}
```
```
public async Task HandleAsync(ParticularDomainEvent @event)
{
    var recordsUpdated = @event.Data;

    ...

    var toBeIndexedRecordsIds = recordsUpdated
        .UpdatedRecordsDetails
        .Where(o => o.IndexAction == IndexActionType.MergeOrUpload)
        .Select(o => o.recordId)
        .ToList();

    if (toBeIndexedRecordsIds.Count > 0)
    {
        // Uncommenting bellow line resolves our issues
        // await Task.Delay(1000);
        var records = await _recordSystemService
            .GetRecordsByIds(toBeIndexedRecordsIds);

        await _recordSearchService.UpdateRecordIndexes(records, IndexActionType.MergeOrUpload);
        
        // UpdateRecordOfferIndexes() does following:
        // Maps record fields to search index fields
        // pushes documents using action defined
        // creates telemtery with responses received
    }
}
```

Before we introduced the delay, we successfully updated search indexes, but the data uploaded was matching the data before the change. Also we noticed that time difference between `ModifiedDate` value for the record in DB and this upload request (as seen in application insights) was 70ms.

So was wondering if you could see anything wrong with this implementation.

**Comment by pjonusas** [comment]
After further investigation I suspect that the issue is not with the database, since managed to reproduce it with some tests using InMemory database as well.

At the moment I suspect issue could be related with scopes or possibly how we use them.

If we try querying data from inside `SavedChangesAsync()` correct values are returned, but since we create events and they are picked up in a different scope, I believe issue occurs if in that other scope we try to access the updated values before `SavedChangesAsync()` has completed and/or its lifetime has ended.

Example bellow:
```
// Scope 1
SavedChangesAsync(...)
{
   ...
   var RecordA = _context.Find<Record>(savedRecordId);
   
   CreateEvents(savedRecordId);
   ...
}
```

```
// Scope 2
HandleEvent(...)
{
   ...
   var RecordB = _context.Find<Record>(savedRecordId);
   ...
}
```

`RecordA` will containt accurate data, but if we try to get `RecordB` before `SavedChangesAsync()` finished work, it will contain outdated data.

Perplexing part is, that this only affectes updates - if record was created, `RecordB` will still get it.

**Comment by roji** [comment]
@pjonusas note that the Find method specifically first checks if an entity instance is already tracked with the given ID; if so, it returns that without accessing the database. In other words, a DbContext instance where you're already tracking some row will return its "cached" version of that row, and if some change occurred in the database, that change will not be returned. If that's the case in your scenario, you can dispose the DbContext and instantiate a new one, or call context.ChangeTracker.Clear() to clear the context.

If that doesn't help, please put together a minimal code sample that shows the issue happening, and we'll investigate.
