### ISSUE TITLE
.Take(0) after .Skip(n>0) causes an SqlException on SQL Server

### ISSUE THREAD

**Issue by anreton** [dotnet/efcore#27730]
The problem is similar to [this one](https://github.com/dotnet/efcore/issues/22525).

An error occurs `The number of rows provided for a FETCH clause must be greater then zero.` when executing the following expression:

```C#
dbContext
	.Events
	.OrderBy(e => e.Created)
	.Skip(5)
	.Take(0)
	.ToList();
```

EF Core generates the following sql query:
```SQL
DECLARE @__p_0 int = 5;
DECLARE @__p_1 int = 0;
...
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

That LINQ query was expected to return an empty set.

### Provider and version information

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10 21H2 19044.1586
IDE: Visual Studio 2022 17.1.2

**Comment by ajcvickers** [comment]
Note from triage: this is not something we are going to attempt to identify automatically for the SQL Server provider, since that's not trivial. Instead, don't execute the query if the value for Take is zero.

**Comment by anreton** [comment]
@ajcvickers, Thank you for your response. Yes, this is the solution we are currently using.

Hmm, should I close this issue?
