### ISSUE TITLE
Change Detection: Exception when adding child to parent entity

### ISSUE THREAD

**Issue by ChristianLavigne** [dotnet/efcore#27736]
When updating an existing entity by adding children to a collection property, db context throws on SaveChanges.

'Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Attempted to update or delete an entity that does not exist in the store.'

The same process works when creating the entity.

Update code (throws an exception):
```C#
    public async Task AddChild(Guid parentId)
    {
        var parent1 = _ctx.Parents
                .Include(item => item.Children)
                .SingleOrDefault(item => item.Id == parentId);            
        if(parent1 != null)
        {
            var child = new Child() {
                Id = Guid.NewGuid(),
                Name = "this is a test",
                ParentId = parentId
            };
            parent1.Children.Add(child);
    
            // _ctx.ChangeTracker.DetectChanges();
            // Console.WriteLine(_ctx.ChangeTracker.DebugView.LongView);

            await _ctx.SaveChangesAsync(); // throws exception here...
        }
    }
```
Create code (this code works):
```C#
    public async Task<Guid> CreateParent()
    {
        Guid result = Guid.Empty;
        var parent1 = new Parent() {
            Id = Guid.NewGuid(),
            Name = "Parent1"
        };
        _ctx.Parents.Add(parent1);

        var child = new Child() {
            Id = Guid.NewGuid(),
            Name = "Child1",
            ParentId = parent1.Id
        };
        parent1.Children.Add(child);

        await _ctx.SaveChangesAsync();
        result = parent1.Id;
        return result;
    }
```
NOTE: The change detection does detect the new child, but the new child Status is Modified. The Status should be Added. If the status is manually set to Added, the save works as expected.

This is the output for ChangeTracker.DebugView.LongView:

```pre
Child {Id: 989eff64-6c80-4ecb-8793-ad2a057ae371} Modified
  Id: '989eff64-6c80-4ecb-8793-ad2a057ae371' PK
  Name: 'this is a test' Modified
  ParentId: '1dafab94-8334-4004-8d2d-180a65ad66ab' FK Modified
Child {Id: b934403e-949b-414d-976f-f9b971c2af1c} Unchanged
  Id: 'b934403e-949b-414d-976f-f9b971c2af1c' PK
  Name: 'Child1'
  ParentId: '1dafab94-8334-4004-8d2d-180a65ad66ab' FK
Parent {Id: 1dafab94-8334-4004-8d2d-180a65ad66ab} Unchanged
  Id: '1dafab94-8334-4004-8d2d-180a65ad66ab' PK
  Name: 'Parent1'
  Children: [{Id: b934403e-949b-414d-976f-f9b971c2af1c}, {Id: 989eff64-6c80-4ecb-8793-ad2a057ae371}]
```

This is problematic for us because we add children in a location where the DbContext is not available.

Target framework: .NET 6.0
EF Core version: 6.0.3 (latest)
Database provider: Any 
(tried: Npgsql.EntityFrameworkCore.PostgreSQL and Microsoft.EntityFrameworkCore.InMemory)
Operating system: Linux
[TestChildren.zip](https://github.com/dotnet/efcore/files/8391899/TestChildren.zip)

**Comment by ajcvickers** [comment]
@ChristianLavigne The problem is that the primary key for Child is configured as automatically generated by convention, but the code is setting an explicit value. When a new entity is detected and the key is set to automatically generate, then if the key is already set it means that the new entity is treated as if it already exists--since otherwise the key value would not have been generated and set.

Unless you really want to use a mix of generated and not generated keys on the same entity type, you should either configure the key as not generated--for example:

```C#
public class Child
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid Id { get; set; }
    public string Name { get; set; }
    public Guid ParentId { get; set; }
}
```

Or stop setting the key value explicitly. For example:

```C#
var child = new Child() {
    Name = "this is a test",
    ParentId = parentId
};
parent1.Children.Add(child);
```

**Comment by ChristianLavigne** [comment]
@[ajcvickers](https://github.com/ajcvickers)
We can work with that.

I get what you're saying, it is still odd behaviour that something is added but the change detection marks it as modified...

Thanks for your help!
