### ISSUE TITLE
IDbConnectionInterceptor DbConnection replacement

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/efcore#27744]
## File a bug
 public override InterceptionResult ConnectionOpening(DbConnection connection, ConnectionEventData eventData, InterceptionResult result)

public override ValueTask<InterceptionResult> ConnectionOpeningAsync(DbConnection connection,
            ConnectionEventData eventData,InterceptionResult result,CancellationToken cancellationToken = default)

DbConnectionInterceptor doesn't allow the replacing of the DbConnection to allow overriding the DbConnection implementation

**Comment by 3GDXC** [comment]
I believe this could be a design/implementation issue with regards the DbConnectionInterceptorAggregator and the private sealed class CompositeDbConnectionInterceptor which prevents the replacing of the DbConnection instance that an Interceptor many wish to use.

I wish to use a generic EntityFrameworkCore provider to build/generate SQL syntax commands (Sqlite/SqlServer) but redirect these commands to a (SQL-92 compliant, ODBC, ADO.NET or gRCP provider (that hasn't got a specific EntityFramework/EntityFrameworkCore provider) with minimal efforts ie. not writing a complete provider.

**Comment by roji** [comment]
@3GDXC trying to go around "writing a complete provider" by using an interceptor to redirect SQL is unlikely to be a good way to do things, and would probably not reduce work. For one thing, you'd have to pick a specific relational provider (SQL Server? SQLite?), and the SQL generated would be specific for that database. While it may be possible to parse or search/replace certain SQL constructs, that approach is much worse than customizing the SQL generated at the source. I'd really advise looking at writing a provider instead.

**Comment by ajcvickers** [comment]
@3GDXC The connection interceptor is not intended to be used to replace the DbConnection. You can replace the DbConnection on the context if you do so before it is opened, but I doubt it will get you what you want for the reasons that @roji outlined.
