### ISSUE TITLE
Default value set to entity when retrieve data is null

### ISSUE THREAD

**Issue by Zefek** [dotnet/efcore#27743]
Hello,

I would like to ask about possibility to set default value to property when retrieve data from database. 
I need to use stored procedure because of backward compatibility with another part of system. This stored procedure can return column with null value. It means property should be nullable (i.e. public int? Count { get; set; }. 
But because of backward compatibility I cannot use nullable property. 
There is any method on Property (e.i. method DefaultValueOnRetreive<int>(0)) how to say default value when retrieve data is null? 

Thanks.

**Comment by ajcvickers** [comment]
@Zefek You could use a [value converter](https://github.com/dotnet/efcore/issues/13850) for this. This could also be done using #10768, when implemented. However, be aware that this could cause problems if the converted value is part of a key or foreign key--see #26209 and #26210.

**Comment by Zefek** [comment]
Thank you. I aware of some kind of problem but I want to use it for query (read) model where each entity is configured as HasNoKey and will not be saved back to database. 
Command model is configured with nullable properties and there is some validation to check if value is null.
