### ISSUE TITLE
Why do you recommend for EF to create and maintain its own IServiceProvider for internal EF services?

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/efcore#27751]
`EntityFrameworkServiceCollectionExtensions` has some overloads with a `Action<IServiceProvider, DbContextOptionsBuilder> optionsAction` parameter. The documentation for those overloads says:

> By default, we recommend using [Add... `Action<DbContextOptionsBuilder>` overload] which allows Entity Framework to create and maintain its own IServiceProvider for internal Entity Framework services.

What are the downsides of using the `Action<IServiceProvider, DbContextOptionsBuilder>` overloads? The commit adding the documentation (https://github.com/dotnet/efcore/commit/df4ee7fbc7263d9ecc9e62acd1fc65771d643099) and the original issue (#5102) does not offer much insight.

**Comment by ajcvickers** [comment]
@stijnherreman A few reasons:

* EF requires specific services registered with specific scopes to work correctly. If you manage the service provider yourself, then you must ensure that these services are registered and not replaced with other implementations or with different scopes that are incompatible with what EF needs.
* Certain changes in configuration between context instances require EF to build a new service provider (typically when a singleton service changes). If you manage the service provider yourself, then you'll need to make sure that you build a different service provider manually for these situations.
* EF creates scopes for a specific purpose. This can interfere with other scopes on the service provider if it is also used in other ways.

**Comment by stijnherreman** [comment]
Thank you for the clarification!
