### ISSUE TITLE
errors while migrationg drive to m365

### ISSUE THREAD

**Issue by saellab** [dotnet/efcore#27757]
getting this error while migration one drive docs to m365 which keeps appearing for many folders : 
An item with the same key has already been added. CallStack -- at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at Microsoft.SharePoint.Deployment.FileSerializer.SetObjectData(Object obj, SerializationInfo info, StreamingContext context, ISurrogateSelector selector) at Microsoft.SharePoint.Deployment.XmlFormatter.CallSetObjectData(Object obj, SerializationInfo objectData, ISerializationSurrogate surrogate, ISurrogateSelector selector) at Microsoft.SharePoint.Deployment.XmlFormatter.ParseObject(Type objectType, Boolean isChildObject) at Microsoft.SharePoint.Deployment.XmlFormatter.DeserializeObject(Type objectType, Boolean isChildObject, DeploymentObject envelope) at Microsoft.SharePoint.Deployment.XmlFormatter.Deserialize(Stream serializationStream) at Microsoft.SharePoint.Deployment.ObjectSerializer.Deserialize(Stream serializationStream) at Microsoft.SharePoint.De...

**Comment by roji** [comment]
@saellab the error above doesn't seem to be related to EF Core in any way. If you think it is, please submit a runnable, minimal code sample which shows the error happening.

**Comment by saellab** [comment]
actually i am using a tool to migrate an account from google workspace to M365, while migration the onedrive folders, it's giving me this error. i think it's an error from sharepoint reported by the tool i am using

**Comment by roji** [comment]
@saellab this repo is for [Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/), which is a data access layer; it has nothing to do with M365, OneDrive or Sharepoint. If you suspect your migration tool uses EF Core and is encountering an issue, please report the problem to your tool's maintainers.

**Comment by saellab** [comment]
thank you for replying, i got confused between 2 different forums .
 i will try to delete my post
