### ISSUE TITLE
Inserting Integer Key WIth Default Value

### ISSUE THREAD

**Issue by jonahShaf** [dotnet/efcore#27760]
I am working on porting our project from EF 6 to EF Core 3. A problem I have encountered is that EF Core will replace default values in keys when inserting. This is a problem as we use int keys and 0 is a valid key that we need to be able to insert. 

A simplified example:

```C#
public class userEdit {
  public int ID {get; set; }
  public DateTime editInstant {get; set; }
}

...

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  modelBuilder.Entity<userEdit>(entity =>
  {
    entity.HasKey(e => e.ID)
    entity.HasForeignKey(d => d.ID)
      .HasConstraintName("FK_userTable")
  }
```

This will cause inserting a row into userEdit with an ID of 0 to crash since the foreign key constraint fails when 0 is replaced with default value (-2147482647). Is there a way I can get EF Core not to touch this value? I tried adding ValueGeneratedNever() to the property, but that did not seem to work and I have not been able to find other suggested solutions for this case.

EF Core version: 3.1.23
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Framework 4.8
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@jonahShaf 

> I tried adding ValueGeneratedNever() 

This should work. If not, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jonahShaf** [comment]
Here is a project where you can see the issue. To setup the DB, run the files in the SQL folder in order. You will also need to add the server and DB information to your connection string in CurrentContext.cs

[IssueDemo.zip](https://github.com/dotnet/efcore/files/8420589/IssueDemo.zip)

**Comment by CorsairRO** [comment]
Hello jonah.

I am not a very big expert either in EF Core, but i think i can tell you for sure 1 thing.
If your DB needs to insert 0 in PK's then basically i assume you cannot use EF Core. At least for the moment

There are LOTS of default assumptions in the mapping process / generating SQL, and i think the 0 is DEEPLY embedded in tons of places where it assumes is a NEW Entry. That's why it translates automatically to Int.MinValue ( -2147... ), because it needs to KNOW which objects are new to context, and therefore spawn INSERT instead of UPDATE.

**Comment by ajcvickers** [comment]
@CorsairRO This absolutely isn't true. Using zero as a key value is fine unless you are also trying to use generated key values. In this case, EF uses zero to determine whether the key value has been generated or not.

**Comment by jonahShaf** [comment]
@ajcvickers I see, so since we have an FK to dimCustomer here and that column is in the PK, we need to mark that as value generated never. Is that right? Want to make sure I'm understanding the general rule at play here.

**Comment by ajcvickers** [comment]
@jonahShaf Yes, that's correct.

**Comment by jonahShaf** [comment]
Got it, thanks for the help!

**Comment by CorsairRO** [comment]
Hello @ajcvickers ,
sorry for my misunderstanding there, is was assuming that he wants the autoincrementation to work also in addition to allow 0 for PK's. 

So, sorry for the mistake there, if he doesnt use Autoincrement, then ok, he can use 0 as PK with ValueGenerated.Never, otherwise, no.
