### ISSUE TITLE
Fluent API HasConversion  Inheritance  EF.Core NET 6

### ISSUE THREAD

**Issue by MatteoBonzanini** [dotnet/efcore#27784]
Hi, i have a conversion problem using the Fleunt API when a class is inherited 

1) The base class has the following property that converts the value to uppercase:

```
internal abstract class BaseEntityConfiguration<T> : IEntityTypeConfiguration<T> where T : BaseEntity
{
    public virtual void Configure(EntityTypeBuilder<T> builder)
    {
         builder.Property(x => x.UtenteUpdate).HasConversion(v => v.ToUpper(), v => v.ToUpper()).HasMaxLength(50);
       
    }
} 
```

2) The inheriting class has the following definition:

```
internal class UtentiConfiguration : BaseEntityConfiguration<Utenti>
{
    public override void Configure(EntityTypeBuilder<Utenti> builder)
    {
        builder.ToTable("UTENTI");

        builder.Property(x => x.Utente).HasConversion(v => v.ToUpper(), v => v.ToUpper()).IsRequired().HasMaxLength(50);
       
    }
}
```

3) When saving the record the value of property Utente is correctly converted (Example: pippo , save to PIPPO)
but the value of the inherited property UtenteUpdate is not converted. (Example: pippo , save to pippo)

Does the converter not work when inherited ?

I use Microsoft.EntityFrameworkCore.SqlServer 6.0.3

PS) Excuse me if I wrote something wrong, is my first post.

Many Thanks for any Help

Matteo

**Comment by Aurelio67** [comment]
Hi, You have not entered the base.Configure into the class UtentiConfiguration:

```
internal class UtentiConfiguration : BaseEntityConfiguration<Utenti>
{
    public override void Configure(EntityTypeBuilder<Utenti> builder)
    {
        base.Configure(builder);
        builder.ToTable("UTENTI");

        builder.Property(x => x.Utente).HasConversion(v => v.ToUpper(), v => v.ToUpper()).IsRequired().HasMaxLength(50);
       
    }
}
```

It's work Ok..

Many Thanks
Aurelio

**Comment by MatteoBonzanini** [comment]
Hi Aurelio. 
Many Thanks,
and sorry for the inconvenience.

Matteo.
