### ISSUE TITLE
dotnet-ef needs to multi-target (3.1 and 6)

### ISSUE THREAD

**Issue by tylermichael** [dotnet/efcore#27787]
I'm trying to get x64 and amd64 to play nicely together on my machine.

I've followed the steps [here](https://github.com/dotnet/installer/issues/11164#issuecomment-896993092) and so far things seem to be ok for normal usage.

However, when I run this I get:

```bash
> dnx64 ef --help
Failed to load /usr/local/share/dotnet/x64/host/fxr/5.0.10/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/x64/host/fxr/5.0.10/libhostfxr.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/x64/host/fxr/5.0.10/libhostfxr.dylib: mach-o, but wrong architecture
	/usr/local/share/dotnet/x64/host/fxr/5.0.10/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/x64/host/fxr/5.0.10/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

dnx64 is `alias dnx64="/usr/local/share/dotnet/x64/dotnet"`

I installed the ef tool with dotnet 6 arm64 version.

```bash
> file ~/.dotnet/tools/dotnet-ef
/Users/username/.dotnet/tools/dotnet-ef: Mach-O 64-bit executable arm64
```

The dotnet-ef binary is arm64 but I'm trying to execute it with my x64 dotnet install.

Any ideas how I can get this to work?

**Comment by bricelam** [comment]
Workaround
========

You should be able to get it to work if you use the following to install it.

```sh
dotnet tool install -g -a arm64 dotnet-ef
```

**Comment by rebebop** [comment]
> # Workaround
> You should be able to get it to work if you use the following to install it.
> 
> ```shell
> dotnet tool install -g -a arm64 dotnet-ef
> ```

Running this gives the following error
```
System.AggregateException: One or more errors occurred. (Resolving the current runtime identifier failed.)
 ---> Microsoft.DotNet.Cli.Utils.GracefulException: Resolving the current runtime identifier failed.
   at Microsoft.DotNet.Cli.CommonOptions.GetCurrentRuntimeId()
   at Microsoft.DotNet.Cli.CommonOptions.ResolveRidShorthandOptionsToRuntimeIdentifier(String os, String arch)
   at Microsoft.DotNet.ShellShim.ShellShimTemplateFinder.ResolveAppHostSourceDirectoryAsync(String archOption, NuGetFramework targetFramework, Architecture arch)
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
  ```

However, this is working

> Try this out : https://stackoverflow.com/questions/70929949/on-mac-m1-machine-not-able-to-run-ef-core-migrations-add-update-in-asp-net-co/71683322#71683322

**Comment by richlander** [comment]
The workaround version only works if two things are true:

- The .NET 6 SDK is 6.0.200+.
- A compatible x64 runtime is installed.

That makes it a not completely compelling workaround. It also needs to be better explained.

**Comment by pfeifix** [comment]
> The workaround version only works if two things are true:
> 
> * The .NET 6 SDK is 6.0.200+.
> * A compatible x64 runtime is installed.
> 
> That makes it a not completely compelling workaround. It also needs to be better explained.

Can you point me to a workaround I can apply to make the following work on Windows ARM64? I have installed .NET SDK 6.0.202 (which contains the .NET runtimes, see https://dotnet.microsoft.com/en-us/download/dotnet/6.0). Executing

`dotnet ef migrations add InitialCreate`

on my ASP.NET Core project yields

```
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\6.0.4\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\6.0.4\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

**Comment by richlander** [comment]
As a test, can you try (before running that command):

```bash
set DOTNET_ROLL_FORWARD=Major
```

**Comment by pfeifix** [comment]
> As a test, can you try (before running that command):
> 
> ```shell
> set DOTNET_ROLL_FORWARD=Major
> ```

Tried. Same Error shown.

**Comment by richlander** [comment]
Can you enable tracing and share the result (preferably as a link to a gist)?

Instructions: https://github.com/dotnet/runtime/blob/main/docs/design/features/host-tracing.md

**Comment by pfeifix** [comment]
Update: I just found out that issuing

`dotnet tool update --global dotnet-ef`

updated the version to 6.0.4. After that the migration command works as expected. I am happy now. Thanks for your help anyway!

**Comment by richlander** [comment]
Strange. Glad to hear that it helped. I don't know why, however.

**Comment by agocke** [comment]
> Can you point me to a workaround I can apply to make the following work on Windows ARM64?

I believe adding `-a arm64` to the `dotnet install` command will allow it to run on ARM64. The long-term fix here is for ef core to add a NET 6 target, as tracked at https://github.com/dotnet/efcore/pull/27807

I also don't know why the `dotnet tool update` worked. :) That may also be a bug.

**Comment by richlander** [comment]
Back to the actual issue ... upon further investigation, we actually need this package to do two things:

- Multi-target 3.1 and .NET 6
- Add a [shim for Windows Arm64](https://github.com/dotnet/efcore/blob/main/src/dotnet-ef/dotnet-ef.csproj#L18)

For folks reading this, the shim isn't something that most tools creators need to worry about. It's a Microsoft policy for signing binaries and doesn't apply to others (although anyone is free to do it). We may do the same for Linux and macOS later, but we're starting with completing the full set of supported Windows architectures for the moment.

**Comment by richlander** [comment]
Thanks @bricelam!

**Comment by roofiq** [comment]
> Update: I just found out that issuing
> 
> `dotnet tool update --global dotnet-ef`
> 
> updated the version to 6.0.4. After that the migration command works as expected. I am happy now. Thanks for your help anyway!

hey @preetikr, I'm using version 6.0.5 and still getting error. Could it be that 6.0.4 is the only working one?
