### ISSUE TITLE
Unnecessary memory allocations in SnapshotRows

### ISSUE THREAD

**Issue by lahma** [dotnet/efcore#27798]
EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: NET 6.0
Operating system: Windows

This is basically an improvement request, not a bug I guess. Currently following code allocates a lot when I checked why our tests are running somewhat slow. There's a lot of allocations happening in `SnapshotRows`, in test case I profiled it contributed to 30% of all memory allocations.

https://github.com/dotnet/efcore/blob/73db32dd0d7d034717ac3a53c75f0b241d40840d/src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs#L129-L161

1. There's unnecessary list creation (and its inner array allocation) just to get count of items
   * Should check if returned collection is already `ICollection` (this is true when dictionary is returned) and read Count directly from it, otherwise using LINQ `.Count()` skips unnecessary list creation

2. Boxed enumerators are being create to loop both `_valueConverters` and `_valueComparers` because the private fields are unnecessary of interface type
   * Fields should be changed to concrete list type which allows calling concrete `GetEnumerator` without boxin
   * *Could* use `for` loop which removes need to access enumerator and is a bit faster too
   * This is a loop inside a loop so really adds up

I'm willing to submit a PR if these changes make sense to the team.

**Comment by roji** [comment]
@lahma the InMemory provider isn't suitable for production use, and we also recommend against using it in testing ([see docs](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#in-memory-as-a-database-fake)); as a result, it is generally un-optimized and performs poorly. That isn't to say we'd necessarily reject any PR optimizing it, but it's generally preferable to spend both our time and yours on other improvements in the codebase.

Can you elaborate how you're using the InMemory provider and why the additional allocations are a concern for you?

**Comment by lahma** [comment]
@roji this is an old code base that still uses the InMemory provider. Basically it seeds data into the store and then does queries and tests data retrieval rules and output (integration format) structure. There's some data seeding happening at the start of each test which then causes snapshot logic to kick in and allocate a lot.

I understand the reasoning not supporting it and I'm also fine with closing this issue.
