### ISSUE TITLE
Make Scaffold generate field as CLR Enum

### ISSUE THREAD

**Issue by mikhail-rozum** [dotnet/efcore#27792]
Hello!
I use ef core **database-first approach** in my project, and I have a table that is described with the class

```C#
public class Item
{
  public int Id { get; set; }
  public string Name { get; set; }
  public int Status { get; set; }
}

public enum Status
{
  New = 1,
  InProgress = 2,
  Complete = 3
}
```

I want Scaffold to make Item.Status property as Status type. Is it possible to point out to use a **pre-defined enum** for some fields when using **Scaffold**?

I found a post on SO (https://stackoverflow.com/questions/44262314/how-can-i-make-ef-core-database-first-use-enums), but the answer is for code-first approach

EF Core version: 6.0.3
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: . .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.1.1

**Comment by ErikEJ** [comment]
This is possible semi-automatic with EF Core Power Tools

**Comment by roji** [comment]
Note that in the PostgreSQL context above we have native enum types in the database itself, which can be mapped to CLR enums ([see the npgsql docs](https://www.npgsql.org/efcore/mapping/enum.html?tabs=tabid-1)). I'm not sure if there's a place where user code could be placed for execution before reverse engineering takes place - if so, doing `NpgsqlConnection.GlobalTypeMapper.MapEnum<T>()` would be the right way (/cc @bricelam). This would require some work on the Npgsql side.

Otherwise, in the more general context, this could probably be achieved by customizing templates, which is being done for EF Core 7.0 (see #4038).

**Comment by mikhail-rozum** [comment]
Thank you for your advices. I was thinking about using either native Postgresql enums and current int fields. But in the case with using int type I admitted to add Item.Status field manually in a partial class, but I didn't find a way to exclude fields (not whole tables) from generating by Scaffold. Is there a way to exclude field from Scaffold?

**Comment by ErikEJ** [comment]
Yes excluding columns is possible with EF Core Power Tools.

**Comment by mikhail-rozum** [comment]
Thank you all. I will use EF Core Power Tools

**Comment by rmcp** [comment]
Is it possible to achieve this using CLI?

**Comment by ErikEJ** [comment]
@rmcp Yes, if you combine with .t4 templates.

**Comment by JohnYoungers** [comment]
Would there be any reason to avoid a solution like this?

```c#
public class CustomDesignTimeServices : IDesignTimeServices
{
	public void ConfigureDesignTimeServices
		(IServiceCollection serviceCollection) => serviceCollection.AddSingleton<IScaffoldingTypeMapper, CustomScaffoldingTypeMapper>();

	private sealed class CustomScaffoldingTypeMapper : ScaffoldingTypeMapper
	{
		public CustomScaffoldingTypeMapper(IRelationalTypeMappingSource typeMappingSource)
			: base(typeMappingSource)
		{
		}

		public override TypeScaffoldingInfo? FindMapping(string storeType, bool keyOrIndex, bool rowVersion, Type? clrType = null) =>
			storeType switch
			{
				"public.status" => new TypeScaffoldingInfo(typeof(Status), true, null, null, null, null, null),
				_ => base.FindMapping(storeType, keyOrIndex, rowVersion, clrType)
			};
	}
}
```
