### ISSUE TITLE
Ability to hook into model finalization?

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#27790]
During model creation, I'm guessing some entity types get detected as candidates for the model, but are later excluded. The code below shows an example where a class is initially included the model even though it doesn't map to a table, view or SQL etc. and just corresponds to a JSON column.

In my app, at the end of OnModelCreating, I loop through all entity types in the model to ensure they have a TenantId column and apply a query filter to them. This is useful as developers on the app don't have to worry about adding this filter for new entities and can't accidentally add entities that don't have a TenantId property. However, classes like `NonEntity` are included at this point. Is there a way to 'hook in' to the finalization process - e.g. after EF has produced the close-to-final model, but allows the application to make some last modifications? Or is there a way to generically identify such non-entity types at this stage?

Thanks

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Linq;
using System.Text.Json;

{
    using var context = new TestContext();
    Console.WriteLine(
        $"Finalized entity types: {string.Join(", ", context.Model.GetEntityTypes().Select(x => x.ClrType))}");
}

public class TestContext : DbContext
{
    public DbSet<Entity> Entities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"Server=.;Database=ModelBuilding;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entity>(
            entityBuilder => entityBuilder
                .Property(p => p.Details)
                .HasConversion(
                    new ValueConverter<NonEntity, string>(
                        c => JsonSerializer.Serialize(c, (JsonSerializerOptions)null),
                        s => JsonSerializer.Deserialize<NonEntity>(s, (JsonSerializerOptions)null))));

        Console.WriteLine(
            $"OnModelCreating entity types: {string.Join(", ", modelBuilder.Model.GetEntityTypes().Select(x => x.ClrType))}");
    }
}

public class Entity
{
    public int Id { get; set; }
    public int TenantId { get; set; }
    public NonEntity Details { get; set; }
}

public class NonEntity
{
    public string Name { get; set; }
    public string Notes { get; set; }
}
```

Output:
```
OnModelCreating entity types: Entity, NonEntity
Finalized entity types: Entity
```

**Comment by ajcvickers** [comment]
Covered by #214 via IModelFinalizingConvention.
