### ISSUE TITLE
CodeFirst: Set column collation

### ISSUE THREAD

**Issue by seriouz** [dotnet/efcore#2779]
It would be nice to set a collation for a column with the code-first approach:
Change the std **SQL_Latin1_General_CP1_CI_AS** to **SQL_Latin1_General_CP1_CS_AS**

**Comment by rowanmiller** [comment]
Hey,

We discussed and concluded that setting different collations per column isn't a very common requirement and it's probably not something we would make first class in EF. This would be a good candidate for using annotations to define additional metadata and then extending our SQL generators to process those and specify collation.

~Rowan

**Comment by roji** [comment]
Duplicate of #19275

**Comment by roji** [comment]
This is currently being implemented as part of #19275.
