### ISSUE TITLE
Query a subclass that shares the same table than its parents may result in a downcasting issue

### ISSUE THREAD

**Issue by djon2003** [dotnet/efcore#27802]
## Context

- Having two classes one is the child of the other: `A` being the parent of `B`.
- The classes share the same table with a Discriminator column.
- `AsNoTracking()` is not used.

## How to reproduce

- Make a query that loads an object A with Id == 1
- Make another query that loads an object B with Id ==1

It gives the following exception if using proxies: System.InvalidCastException: Unable to cast object of type 'Castle.Proxies.AProxy' to type 'B'. 

It gives the following exception if using not proxies: System.InvalidCastException: Unable to cast object of type 'A' to type 'B'.

StackTrace when using an enumerator:
```
   at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void* toTypeHnd, Object obj)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at MY_CLASS.MY_METHOD in MY_FILE:MY_LINE
```

## How to circumvent the issue

Before calling `.ToList()`, uses `.AsNoTracking()`.

So: `databaseContext.Bs.Where(b => b.Id == 1).AsNoTracking().ToList()`

## How the issue could be fixed

- Remove an existing `A` object in cache when it shall be loaded as `B` in 
```Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext```
- Allow downcasting from `A` to `B`: either automatically or by implementing manually an "implicit|explicit operator": https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators

### Provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6
Operating system: Windows 11
IDE: Visual Studio 2022 17.1.3

**Comment by ajcvickers** [comment]
@djon2003 EF doesn't support multiple entities in a hierarchy that share the same primary key value. Instead, the discriminator should be included in the EF key mapping so that the two entities have different primary key values.

**Comment by djon2003** [comment]
@ajcvickers 
Now, I don't need that anymore, but others may.

The whole picture here is this one:
I had two classes because the child one only existed to be able to have a column that is generated by the SQL query, but only when using the subclass with a raw query. The be clear, I have a table what contains movies and the second class existed to do fuzzy search on those and it would then include a column `Distance`. So, the trick I have be able to do it was to use a subclass. But then I had another issue with the subclass not loading the navigation properties that has been fixed stating both classes using the same table (instead of the subclass being keyless) with a discriminator. This column was in fact always filled with the parent class name and overriden by the fuzzy search raw query.

**Comment by djon2003** [comment]
@ajcvickers You closed it. So, this was a too far fetch usage?

**Comment by ajcvickers** [comment]
@djon2003 I thought you were saying that this wasn't an issue for you anymore.

In general, as I said above, EF doesn't support multiple entities in a hierarchy that share the same primary key value. Instead, the discriminator should be included in the EF key mapping so that the two entities have different primary key values.

**Comment by djon2003** [comment]
@ajcvickers I understood what you said, but I said, even though I am using something else now due to some needed changes, others may need it. The way I did it is almost fully working and I presume it would be a great improval.  Don't you think?

**Comment by ajcvickers** [comment]
@djon2003 I don't see much value in it, and it would be quite expensive to implement.

**Comment by djon2003** [comment]
@ajcvickers I see. If you have a "maybe" features column, you may add it there.

And, I know it is not the "proper" way to ask for that, but as you are there reading my comments... Did you see in another issue that I am currently looking for a new job?

**Comment by ajcvickers** [comment]
@djon2003 

>  Did you see in another issue that I am currently looking for a new job?

Not sure how that is relevant here?

**Comment by djon2003** [comment]
@ajcvickers It is not, But I didn't find any other way to communicate with you.

**Comment by ajcvickers** [comment]
@djon2003 If you're asking if we are hiring, then I'm afraid not.

**Comment by djon2003** [comment]
@ajcvickers OK! Sorry for this "not relevant" question.

Thank you to take your time looking into this issue.
