### ISSUE TITLE
Rowversion type generates timestamp data type.

### ISSUE THREAD

**Issue by stevanusw** [dotnet/efcore#27806]
The EF migration generates rowversion type however the generated SQL column is timestamp which is deprecated.

![image](https://user-images.githubusercontent.com/16387544/162952107-7e058b4b-6073-4e70-b2d6-8e0d5f1f3b60.png)

![image](https://user-images.githubusercontent.com/16387544/162952636-c87c5b99-0972-4707-9142-7ab3494a41f2.png)

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 11
IDE: VS2022 17.1.2

**Comment by ErikEJ** [comment]
That is an SSMS / SMO issue, not an EF Core issue.

**Comment by stevanusw** [comment]
![image](https://user-images.githubusercontent.com/16387544/163075979-9a7f0809-3e72-4a3d-97fd-307a5eea6089.png)

Ok i can confirm that EF script generates rowversion.

Thanks.
