### ISSUE TITLE
EF Core with spatial column throws exception: Could not load file or assembly Microsoft.SqlServer.Types

### ISSUE THREAD

**Issue by Dimigergo** [dotnet/efcore#27804]
### My code to reproduce the bug
[EFCore5Geography.zip](https://github.com/dotnet/efcore/files/8470538/EFCore5Geography.zip)

### Bug descrption
I have a small db.sql file in the project which creates a minimal database with one table and one table value function. The table has a geography column and the function makes a query for this table.
First question is why the function return type has byte[] for spatial type, why not Geometry like the table parse?

When you run the sample code, the insert is perfect, but when query the function the followin error occures:
![error](https://user-images.githubusercontent.com/11498949/162908236-1c7f2c04-6f40-4d24-9c4e-723d88065417.png)
I know that Microsoft.SqlServer.Types is a .net framework package only, issued by SQLServer (thats why we use NetTopologySuite), and no .netstandard or core version from it, but who want to use these package? 
If I query the table with linq, without the function, there is no error.

In the MyDbContext.partial.cs I made a connection with the following settings:
```C#
        public MyDbContext(string connectionString, int commandTimeout = 30)
            : base(new DbContextOptionsBuilder<MyDbContext>()
                .UseLazyLoadingProxies()
                .UseSqlServer(
                    connectionString,
                    sqlServerOptions =>
                    {
                        sqlServerOptions.CommandTimeout(commandTimeout);
                        sqlServerOptions.UseNetTopologySuite();
                    })
                .Options)
        {
        }
```
### Include provider and version information

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer 5.0.16)
Target framework: (.NET 5.0)
Operating system: 
Windows 10 (19041)
IDE: (Visual Studio 2022 17.1.3)

**Comment by bricelam** [comment]
Does it work if you use Geometry in the class instead?
```diff
  public partial class funcGetCoordinatesResult
  {
-     public byte[] DevCoordinates { get; set; }
+     public Geometry DevCoordinates { get; set; } 
  }
```

**Comment by Dimigergo** [comment]
Yes, in this case it works perfect.

**Comment by ajcvickers** [comment]
Note from triage: using the NTS types is the recommend and supported way to do this.

**Comment by ErikEJ** [comment]
It is a bug in EF Core Power Tools, and I will fix it.

see https://github.com/ErikEJ/EFCorePowerTools/issues/1349

**Comment by ErikEJ** [comment]
Fixed in latest daily EF Core Power Tools build
