### ISSUE TITLE
The dotnet dbcontext Scaffold ef and scaffold-dbcontext command does not find the package

### ISSUE THREAD

**Issue by vngounou26** [dotnet/efcore#27829]
I am trying to generate my models from the database using Entity framework via reverse engineering. but the command does not work.
Here is the exact command I entered

```C#
dotnet ef dbcontext scaffold  "Data Source=.; Initial Catalog=DiceDatatable; " Microsoft.EntyFrameworkCore.SqlServer --output-dir Models
```
it gives me the following error:

![image](https://user-images.githubusercontent.com/71229551/163651480-c7932e9a-eb9c-49ad-8c50-84f04348d93e.png)

```
Unable to find provider assembly 'Microsoft.EntyFrameworkCore.SqlServer'. Ensure the name is correct and it's referenced by the project.
```

I don't understand what is happening because I installed everything as you can see in the image above

I specify that all the old and new project generates the same error.

the problem occurs after i updated visual studio 2022 from preview to current version.
I am also moving from sql server 2016 to sql server 2022

Environmental Information

EF Core version: 6.4
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: windows 11
IDE:  Visual Studio 2022 17.1.4

**Comment by ajcvickers** [comment]
@vngounou26 You spelled "Entity" wrong in "Microsoft.EntyFrameworkCore.SqlServer".

**Comment by vngounou26** [comment]
@ajcvickers I really feel like zero to this answer. I've been on this problem for two days and haven't noticed anything. Thanks, I'll try to do that and get back to you.
