### ISSUE TITLE
Table valued function with left joined table generates wrong nullable types

### ISSUE THREAD

**Issue by Dimigergo** [dotnet/efcore#27823]
I have created a sample app with a small sql to create two tables queried with table valued function and stored procedure.

As you can see the following picture, the tables contain not null integers and the functions have no return type defined, only the selects with left join.
![error1](https://user-images.githubusercontent.com/11498949/163391265-96e8fbdc-dc24-4c8e-8620-26dc61172eca.png)

The left joined table int will be nullable, but the main table value remains non nullable. The stored procedure and the function generation are the same symptoms. This is a difference between the Entity Framework 6 (.NET framework), because in that case both of them non nullable types.
![error2](https://user-images.githubusercontent.com/11498949/163391326-77c9a83c-5d3d-415c-80c4-c277657594f7.png)

### Steps to reproduce
[EFCoreJoinedNullable.zip](https://github.com/dotnet/efcore/files/8489169/EFCoreJoinedNullable.zip)

### Further technical details
EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer 5.0.16)
Target framework: (.NET 5.0)
Operating system:
Windows 10 (19041)
IDE: (Visual Studio 2022 17.1.3)

**Comment by ErikEJ** [comment]
My bad, this is a Power Tools issue.

**Comment by ajcvickers** [comment]
Closing as external per @ErikEJ's comment.
