### ISSUE TITLE
LINQ : Select top distinct from group order by creationTime

### ISSUE THREAD

**Issue by sohaibameenpk007** [dotnet/efcore#27839]
Hello, 

I am trying to select top distinct result from each group which is ordered by creation time in descending order through LINQ. I created the query on database side and its working fine but LINQ query is not returning the exact data. 

SQL Query & Result 
![image](https://user-images.githubusercontent.com/88434445/163944277-86abad53-22c4-4416-b194-7825de452eb1.png)

Most Recent

```c#
IEnumerable<DocumentSession> top5Results2222 = query.Include(x => x.Document)
    .ThenInclude(x => x.Branches)
    .AsEnumerable()
    .GroupBy(row => row.DocumentId)
    .Select(grp =>
        grp.OrderByDescending(historyItem => historyItem.CreationTime)
        .FirstOrDefault()
    )
    .Take(pageSize);

IEnumerable<DocumentSession> top5Results233333 = query.AsEnumerable()
    .GroupBy(row => row.DocumentId)
    .Select(grp =>
        grp.OrderByDescending(historyItem => historyItem.CreationTime)
        .FirstOrDefault()
    )
    .OrderByDescending(historyItem => historyItem.Id)
    .Take(pageSize);


IEnumerable<DocumentSession> top5Results = query.AsEnumerable()
    .GroupBy(row => row.DocumentId)
    .Select(grp =>
        grp.OrderByDescending(historyItem => historyItem.CreationTime)
        .FirstOrDefault()
    )
    .OrderByDescending(historyItem => historyItem.CreationTime)
    .Take(pageSize);
```

All queries returning the same data whose screenshot is given below. 
![image](https://user-images.githubusercontent.com/88434445/163944505-d7cac029-a1bd-437c-bd72-bad8db2bf400.png)

Please let me know if somebody can help me to refine the LINQ query I am using. 

Thanks, 
Sohaib

**Comment by ajcvickers** [comment]
@sohaibameenpk007 All your code snippets are using `.AsEnumerable()`, which tells LINQ to pull in all results from the database and then do everything else (the `GroupBy`, the `Select`, etc.) in-memory. Is this what you are intending?

**Comment by sohaibameenpk007** [comment]
Actually I took care of it by making a minor correction so thank you everyone.
