### ISSUE TITLE
Add support for Azure SQL Edge reverse engineering

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#27835]
Azure SQL Edge has a new EngineEdtion value:
https://docs.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql?view=sql-server-ver15

It does not support a number of features:

https://docs.microsoft.com/en-us/azure/azure-sql-edge/features

### Include provider and version information

EF Core version: 7.0
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)

**Comment by ErikEJ** [comment]
It most likely just works

**Comment by ajcvickers** [comment]
@ErikEJ Have you tested it?

**Comment by ErikEJ** [comment]
@ajcvickers no - let me try if I can figure out how to get it running.

**Comment by ErikEJ** [comment]
Yes, it works!

**Comment by ajcvickers** [comment]
Thanks, Erik!
