### ISSUE TITLE
Parameter and SQL length check don't take pending bulk insert commands into account

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27840]
This means that if a user adds a massive amount of INSERTs, we would attempt to add them in a single batch even if they go over the parameter limit (2100), which would fail.

**Comment by MateiIonutEduard** [comment]
I will come up with a solution, because the bug is starting to annoy me.

**Comment by roji** [comment]
@MateiIonutEduard this issue refers to a bug introduced in in 7.0.0-preview.3 (or maybe even preview.4), and is not present in 6.0 - are you sure this is affecting you?

Either way, I plan to work on this soon, and it's not necessarily a good issue for an external contributor to work on (as I'm working in this area of the code at this moment).

**Comment by MateiIonutEduard** [comment]
oki
