### ISSUE TITLE
How can I get a deleted owned entity from the parent entity?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#27848]
I need to traverse entities graph; both its versions: before and after the changes.

In case property holds an owned entity, and this property is set to `null`, owned entity is marked as deleted, but EntityEntry for the parent entity does not contain any reference to deleted entity.

Parent entity has `Unchanged` status, and corresponding navigation property has `IsModified = false` as well.

I think this can also be related to this [issue](https://github.com/dotnet/efcore/issues/16513)

![image](https://user-images.githubusercontent.com/9202028/164319252-9138702d-fce2-4fca-83da-393f5331bd9a.png)

**Comment by ajcvickers** [comment]
@voroninp On looking at this again, this seems to be expected behavior. In particular:

> In case property holds an owned entity, and this property is set to null, owned entity is marked as deleted, but EntityEntry for the parent entity does not contain any reference to deleted entity.

If the navigation property to the owned entity "is set to null", then this removes the reference to it from the parent entity, so there is no reference to it from the parent EntityEntry. That is, the reference has been explicitly severed by setting the navigation property to null.

**Comment by voroninp** [comment]
@ajcvickers , then let me ask it differently.

I want to ensure that the set of changed entities belong to the same aggregate. My idea was to traverse the graph starting from the aggregate root entity entry, then count the number of changed entries and compare that number in ChangeTracker. 
But if navigation property is cleared, then how can I check the "origins" of the deleted entity?

**Comment by ajcvickers** [comment]
I don't think there is any easy way to do this. You'll probably need to use FK original values, assuming you have original values available, and then use the metadata model to manually connect up previously associated entities.

**Comment by voroninp** [comment]
Yes, this could work.

Is there any trick to tag all entity entries which are materialized as a result of a single query?

**Comment by ajcvickers** [comment]
Materialization interception? https://devblogs.microsoft.com/dotnet/announcing-ef7-preview7-entity-framework/
