### ISSUE TITLE
Cycle navigation

### ISSUE THREAD

**Issue by wzxinchen** [dotnet/efcore#27851]
It could be a bug, or it could be by design.
```
class EF : DbContext
    {
        public DbSet<A> As { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql("server=localhost");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<A>(x =>
            {
               // debug string show here
                var view = x.Metadata.ToDebugString();
            });
        }
    }

    public class A
    {
        public int Id { get; set; }
        public B B { get; set; }
        public List<B> Bs { get; set; }
    }

    public class B
    {
        public int Id { get; set; }

        public A A { get; set; }
    }
```

If the property B.A does not exist, then everything is fine

If this property is included, A's navigation properties are all lost, as below

```
EntityType: A
  Properties: 
    Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
  Keys: 
    Id PK
```
I know that would result in a circular navigation, which would result in a circular Include if AutoInclude was enabled, however, should I think the navigation property should still be there?

### Include provider and version information

EF Core version: 6.0
Database provider: Npgsql
Target framework: .NET5.0
Operating system: Windows 10
IDE:  Visual Studio 2019 16.11

**Comment by wzxinchen** [comment]
I found out that I built a one to one relationship and that was my problem, I'll test it again.

**Comment by roji** [comment]
@wzxinchen can this issue be closed? If you're still experiencing an issue, can you please post a full, runnable code sample?
