### ISSUE TITLE
Release a hotfix for TPT Check Constraint Duplication Issue in new patch release of EF Core 6.0

### ISSUE THREAD

**Issue by anreton** [dotnet/efcore#27860]
We are faced with the problem described in https://github.com/dotnet/efcore/issues/24219.

The solution to this problem has already been implemented and is available in [Microsoft.EntityFrameworkCore 7.0.0-preview.3.22175.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/7.0.0-preview.3.22175.1).

Stable version EntityFrameworkCore 7.0.0 is expected only in November.

Is it possible to release this fix in new patch release of EF Core 6.0 (e. g. 6.0.5)?

### Include provider and version information
EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10 21H2 19044.1586
IDE: Visual Studio 2022 17.1.2

**Comment by ajcvickers** [comment]
@anreton We typically don't patch issues that have easy workarounds--in this case, editing the generated migration. It also only has one vote even though it was opened in February of last year, indicating that it isn't impacting a large number of people. See [the release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information on how we decide what to patch.

**Comment by anreton** [comment]
@ajcvickers, yes, it makes sense.

In any case, thank you very much for your response.
