### ISSUE TITLE
How to make a method generic using lambda expressions?

### ISSUE THREAD

**Issue by rutger-koperdraad** [dotnet/efcore#27864]
I have a .NET Core Web API that uses the Entity Framework to access the database. I am still on .NET 2.2, of which I know it is obsolete (will update soon). My API contains a generic extension method that adds a where clause to a query, using a property name and value from a configuration file, so only known at runtime.

```
public static IQueryable<T> Filter<T>(this IQueryable<T> query, string propertyName, object propertyValue)
{
	var parameter = Expression.Parameter(typeof(T));
	var left = Expression.Property(expression, propertyName);
	var right = Expression.Constant(propertyValue);
	var body = Expression.Equal(left, right);
	var predicate = Expression.Lambda<Func<T, bool>>(body, new ParameterExpression[] { parameter });

	return query.Where(predicate);
}
```

The query executes fine, but it does not parametrize the property value, which alledgedly causes a memory leak. If the property type is string, the WHERE clause looks like WHERE [e].[PropertyName] = N'PropertyValue'. On https://dzone.com/articles/investigating-a-memory-leak-in-entity-framework-co I read that can be solved using lambda expressions. However, I do not understand how to implement that in a generic way. I created the following hybrid solution, where string properties are correctly parametrized, but other properties aren't.

```
public static IQueryable<T> Filter<T>(this IQueryable<T> query, string propertyName, object propertyValue)
{
	var parameter = Expression.Parameter(typeof(T));
	var left = Expression.Property(expression, propertyName);

	if (left.Type == typeof(string))
	{
		var right = (Expression<Func<string>>)(() => (string)propertyValue);
		var body = Expression.Equal(left, right.Body);
		var predicate = Expression.Lambda<Func<T, bool>>(body, new ParameterExpression[] { parameter });

		return query.Where(predicate); // propertyValue correctly parametrized
	}
	else
	{
		var right = Expression.Constant(propertyValue);
		var body = Expression.Equal(left, right);
		var predicate = Expression.Lambda<Func<T, bool>>(body, new ParameterExpression[] { parameter });

		return query.Where(predicate); // propertyValue not  parametrized!
	}
}
```

How can I make this function generic, using lambda expressions for all types?

EF Core version: 2.2.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 2.2)
Operating system: Windows 11
IDE: Visual Studio 2017 15.9.45

regards,
Rutger.

**Comment by davidfowl** [comment]
You can try adding a second generic argument to represent the property value

```C#
public static IQueryable<T> Filter<T, V>(this IQueryable<T> query, string propertyName, V propertyValue)
{
	var parameter = Expression.Parameter(typeof(T));
	var left = Expression.Property(expression);
	var right = Expression.Constant(propertyValue, typeof(V));
	var body = Expression.Equal(left, right);
	var predicate = Expression.Lambda<Func<T, bool>>(body, new ParameterExpression[] { parameter });

	return query.Where(predicate);
}
```

**Comment by stevendarby** [comment]
Define `right` as a `Func<object>` expression, then use `Expression.Convert` to convert to its actual type and use that in the Equal expression

```C#
Expression<Func<object>> right = () => propertyValue;
var convertedRight = Expression.Convert(right .Body, propertyValue.GetType());
var body = Expression.Equal(left, convertValueExpression);
var predicate = Expression.Lambda<Func<T, bool>>(body, new ParameterExpression[] { parameter });

return query.Where(predicate); // propertyValue correctly parametrized
```

**Comment by ajcvickers** [comment]
@rutger-koperdraad If you're willing to have another generic argument, then you can do this:

```C#
    public static IQueryable<T> Filter<T, TProperty>(this IQueryable<T> query, string propertyName, TProperty propertyValue)
        => query.Where(e => Equals(EF.Property<TProperty>(e, propertyName), propertyValue));
```

If you have a well-known list of possible property types, then you can have this:

```C#
    public static IQueryable<T> Filter<T>(this IQueryable<T> query, string propertyName, object propertyValue)
        => propertyValue switch
        {
            string stringValue => query.Where(e => EF.Property<string>(e, propertyName) == stringValue),
            DateTime dateTimeValue => query.Where(e => EF.Property<DateTime>(e, propertyName) == dateTimeValue),
            int intValue => query.Where(e => EF.Property<int>(e, propertyName) == intValue),
            _ => throw new NotImplementedException()
        };
```

(But it doesn't handle nulls)

If you want to go fully generic, then @stevendarby's solution seems reasonable.

**Comment by ajcvickers** [comment]
Actually, it seems that this also works and is fully generic:

```C#
    public static IQueryable<T> Filter<T>(this IQueryable<T> query, string propertyName, object propertyValue)
        => query.Where(e => Equals(EF.Property<object>(e, propertyName), propertyValue));
```

**Comment by ajcvickers** [comment]
> The solution suggested by @ajcvickers, which uses object as return type for the lambda expression, does not work either: it actually omits the entire filter silently from the WHERE clause.

If this isn't working for you, then that indicates a bug in EF Core. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by rutger-koperdraad** [comment]
Please find atached a small .NET Core 2.2 Web API project. The end point /api/works-fine implements @stevendarby's solution and generates the following SQL:

```
SELECT [e].[Id], [e].[Property]
FROM [Entities] AS [e]
WHERE [e].[Property] = @__propertyValue_0
```

The end point /api/does-not-work implements @ajcvickers's solution and generates the following SQL:

```
SELECT [e].[Id], [e].[Property]
FROM [Entities] AS [e]
```

As you see, the where clause is simply not there.

[GenericFilter.zip](https://github.com/dotnet/efcore/files/8592600/GenericFilter.zip)

**Comment by ajcvickers** [comment]
@rutger-koperdraad I missed that you are using EF Core 2.2. This is an old version that has been [out-of-support since 2019](https://docs.microsoft.com/en-us/ef/core/what-is-new/). The pattern I showed is translated in all recent releases of EF Core.

**Comment by rutger-koperdraad** [comment]
@ajcvickers We are in the process of updating, but several EF issues have to be fixed before we can do so. Good to know that once in .NET Core 6.0 we can use this more consise construct.
