### ISSUE TITLE
Migrations SQL script (npgsql) truncates some identifiers to 64 not 63 characters

### ISSUE THREAD

**Issue by markm77** [dotnet/efcore#27862]
Hi there,

I recently ran the command

```
dotnet ef migrations script --startup-project ..\OpenBanking.WebApp.Connector --context PostgreSqlDbContext -o Migrations/PostgreSql/20220420094645_InitialCreate.sql -- --OpenBankingConnector:Database:Provider=PostgreSql
```

to create [this script](https://github.com/finlabsuk/open-banking-connector/blob/aa9e10f776c888055a887d9916448786251c9f79/src/OpenBanking.Library.Connector/Migrations/PostgreSql/20220420094645_InitialCreate.sql).

My JetBrains IDE alerted me to three identifiers in the script which exceed 63 characters by one character:
fk_account_access_consent_bank_registration_bank_registration_id
fk_auth_context_account_access_consent_account_access_consent_id
fk_auth_context_domestic_payment_consent_domestic_payment_consen 

and sure enough, pgAdmin shows that PostgreSQL has truncated the last character from these identifiers.

I guess this is a harmless bug in terms of future migrations (??) but thought I should let you know about it.

BR,
Mark

### Include provider and version information

EF Core version: 6.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Rider 2022.1

**Comment by roji** [comment]
@markm77 can you please post the full, runnable code sample that produced this migration script? I'm not able to reproduce this with a simple attempt.

For example, trying to reproduce an FK name of `fk_account_access_consent_bank_registration_bank_registration_id`, the below code produces `FK_account_access_consent_bank_registration_bank_registration_~` instead, which is 63 characters long.


<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<BankRegistration> BankRegistration { get; set; }
    public DbSet<AccountAccessConsent> AccountAccessConsent { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql(@"Host=localhost;Username=test;Password=test")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

[Table("bank_registration")]
public class BankRegistration
{
    [Column("bank_registration_id")]
    public int BankRegistrationId { get; set; }
    public string Name { get; set; }
}

[Table("account_access_consent")]
public class AccountAccessConsent
{
    public int AccountAccessConsentId { get; set; }
    public string Name { get; set; }

    public BankRegistration BankRegistration { get; set; }
    [Column("bank_registration_id")]
    public int BankRegistrationId { get; set; }
}
```

</details>

**Comment by markm77** [comment]
Hi there, thanks for looking at this, I will try to create a minimal repro in the next day or two. BR, Mark

**Comment by markm77** [comment]
Small update. Tweaks to the above pasted code didn't repro so I've begun the job of trimming and bisecting my very large multi-project code to get a minimal repro. I made some good progress tonight. Since I need to do this as a background activity 
 and some important things are happening this week I might not be able to complete this until next week. I will do this though because I've always found investigating small unexpected behaviours to be a surprisingly profitable activity.

**Comment by roji** [comment]
@markm77 any progress on this?

**Comment by markm77** [comment]
@roji I'll tackle it again tomorrow and give you an update.

**Comment by markm77** [comment]
Hi @roji , Here's a minimal repro. Sorry for the delay.

```csharp
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

await using var ctx = new PostgreSqlDbContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

internal class AccountAccessConsent
        
{
    public AccountAccessConsent(Guid bankRegistrationId, Guid id)
    {
        BankRegistrationId = bankRegistrationId;
        Id = id;
    }

    [ForeignKey("BankRegistrationId")]
    public BankRegistration BankRegistrationNavigation { get; set; } = null!;

    public Guid BankRegistrationId { get; }
        
    public Guid Id { get; private set;  }

}

internal class BankRegistration
{
    public BankRegistration(Guid id)
    {
        Id = id;
    }

    public Guid Id { get; private set; }

}
public class PostgreSqlDbContext : DbContext
{
    internal DbSet<BankRegistration> BankRegistration => Set<BankRegistration>();
    internal DbSet<AccountAccessConsent> AccountAccessConsent => Set<AccountAccessConsent>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseNpgsql(@"Host=localhost;Username=test;Password=test")
            .UseSnakeCaseNamingConvention();

        base.OnConfiguring(optionsBuilder);
    }

}

```

You can test the issue is present with the following PowerShell command:
```powershell
rm -recurse .\Migrations\; dotnet ef migrations add InitialCreate --context PostgreSqlDbContext; dotnet ef migrations script --context PostgreSqlDbContext | Select-String fk_account_access_consent_bank_registration_bank_registration_id
```

This project does take a dependency on `EFCore.NamingConventions` but I believe you are involved with that project too - sorry if this is the wrong repo to use for reporting.

I also should comment that if I remove `BankRegistrationNavigation` the issue goes away.

**Comment by markm77** [comment]
Thanks for looking into this @roji .

Moved here: https://github.com/efcore/EFCore.NamingConventions/issues/141
