### ISSUE TITLE
How to handle DateTime with Unix timestamps in SQLite

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/efcore#27872]
According to the [SQLite documentation](https://www.sqlite.org/datatype3.html) (section 2.2), date objects can be stored as text (ISO), reals (Julian) or integers (Unix timestamp)

I found this piece of code in the `SqliteValueReader` and it seems that Unix timestamps (`SQLITE_INTEGER`) get parsed as Julian dates as well. 

```C#
public virtual DateTime GetDateTime(int ordinal)
{
    var sqliteType = GetSqliteType(ordinal);
    switch (sqliteType)
    {
        case SQLITE_FLOAT:
        case SQLITE_INTEGER:
            return FromJulianDate(GetDouble(ordinal));

        default:
            return DateTime.Parse(GetString(ordinal), CultureInfo.InvariantCulture);
    }
}
```

I get the following stack trace when trying to fetch values from the database.

```
System.ArgumentOutOfRangeException: Valid values are between 0 and 999, inclusive. (Parameter 'millisecond')
         at System.DateTime.ThrowMillisecondOutOfRange()
         at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
         at Microsoft.Data.Sqlite.SqliteValueReader.FromJulianDate(Double julianDate)
         at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
         at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
```
Is this functionality missing? If so, I am happy to submit a PR.

### Include provider and version information

EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0.201
Operating system: macOS
IDE: Rider 2022.1

**Comment by bricelam** [comment]
SQLite's built-in [date and time functions](https://sqlite.org/lang_datefunc.html) do ***not*** interpret integer values as Unix timestamps by default. Instead, both floating-point and integer values are interpreted as Julian day values. You need to explicitly pass the *unixepoch* modifier.

If you're using EF Core and want to store Unix timestamps, you can use a [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations). But note that this would make the [default property and method translations](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/functions#date-and-time-functions) for DateTime incorrect, so you'd also have to override them.

**Comment by CollinAlpert** [comment]
Got it, thanks for the explanation.

**Comment by bricelam** [comment]
Thanks for submitting the issue! I love digging into questions like this to see if there are ways we could improve our design. (I always end up learning a thing or two.)

Out of curiosity, do you have an existing database that uses Unix timestamps? If so, what library/tool did you use to insert the data?

**Comment by CollinAlpert** [comment]
That's great, I'd be happy to explain my setup a bit more. I created an empty file and then let JetBrains DataGrip initialize and create the database. I didn't do any fancy extra configurations, so everything should have been pretty much default.
Here are my relevant columns for the table which was causing problems:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/14217185/166563956-dce0bbbd-baf5-4c6d-ba7e-95eb32a0bc1b.png">

This is how I had implemented the properties:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/14217185/166564124-efd2fb56-dab3-4c5e-a282-6b943b3b3c7b.png">

DataGrip offers a date view, however converts the dates to _milliseconds_ for some reason by default. There is a setting to change that to seconds (which would be more appropriate for SQLite) which I found out later.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/14217185/166609291-0de53f69-4a78-4a3f-96cb-96a4dc2e1e5b.png">

I managed to convert to seconds by removing the last the digits via manual SQL query.

After I had done that I got the error when querying the table, which I posted above. Not sure you can do anything about this since, as you mentioned, it is by design. Maybe this helps you anyway though.
