### ISSUE TITLE
Scaffolding creates lowercase DbContext

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/efcore#27886]
When scaffolding from a SQLite database using the `dotnet ef` tool it will create the DbContext with the initial lowercase if the database filename is lowercase.

Example:

    dotnet ef dbcontext scaffold "DataSource=blogging.db;Cache=Shared" Microsoft.EntityFrameworkCore.Sqlite

It creates the `DbContext` with the filename `bloggingContext.cs` and the class name `bloggingContext` which is rather ugly.

Running `dotnet ef dbcontext scaffold --help` it states:

    -c|--context <NAME>                    The name of the DbContext. Defaults to the database name.

But my expectation was that it would still create the filename and the class name with the initial letter uppercase as is the .NET convention.

EF Core version: 6.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET 6.0)

**Comment by ajcvickers** [comment]
@vanillajonathan The filename should not have any impact here. Instead, the database name defined in the SQLite database is being used for the context name. As you state, the context name can be specified if you want something different, including different casing. Beyond that templates (#4038) will allow this to be changed if you choose.

**Comment by bricelam** [comment]
Nope, it actually does come directly from the file name. Technically, the database name is (almost) always `main` in SQLite. I agree that we should scrub these to make them more idiomatic to .NET.

**Comment by ilmalte** [comment]
Hey I have seen the tag, may I try to work on this? @bricelam

**Comment by bricelam** [comment]
Sure! It’s probably easiest to do it here:

https://github.com/dotnet/efcore/blob/22722576eb8064901df6c432061ae2d42336d4f1/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L169

And use _candidateNamingService to clean up the name when _options.UseDatabaseNames is true.

But you might also be able to do it here: 🤷‍♂️

https://github.com/dotnet/efcore/blob/22722576eb8064901df6c432061ae2d42336d4f1/src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs#L113

**Comment by bricelam** [comment]
…or here

https://github.com/dotnet/efcore/blob/22722576eb8064901df6c432061ae2d42336d4f1/src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs#L123

**Comment by ilmalte** [comment]
Thanks for your suggestion @bricelam!

Do you think could be a good idea to keep the file name as input or is it better to pick up the database name instead?

In case you prefer the first option, if this problem is only related to SQLite, I would go for the file SqliteDatabaseModelFactory.cs since it's in the project EFCore.Sqlite.Core and not in EFCore.Design:

https://github.com/dotnet/efcore/blob/22722576eb8064901df6c432061ae2d42336d4f1/src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs#L123

My approach would be to capitalize the first letter (of the value) of the variable called `name`.

To achieve this, I would do something like:

```csharp

    private static string GetDatabaseName(string? str)

    {

        var name = Path.GetFileNameWithoutExtension(str);

        if (!string.IsNullOrEmpty(name))

        {

            //name = char.ToUpper(name[0]) + name.Substring(1);

            name = char.ToUpper(name[0]) + name[1..];

        }

 

        if (string.IsNullOrEmpty(name))

        {

            name = "Main";

        }

        return name;

    }

```

 

Do you think is better to create a method for capitalization? If so, where?

**Comment by bricelam** [comment]
I don't see this issue being specific to SQLite. If a SQL Server database was named *blogging*, it would also generate *bloggingContext*. So it probably shouldn't be fixed just inside SqliteDatabaseModelFactory.

The `CandidateNamingService.GenerateCandidateIdentifier` method has logic to transform strings into Pascal case--it capitalizes the first letter of each word and remove things like underscores and hyphens. I'd reuse that.
