### ISSUE TITLE
Scaffolding option to specify a class suffix

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/efcore#27887]
To avoid having my scaffolded class names have the same names as classes I already have I would like an option for the `dotnet ef` tool to specify a suffix for the class name.

Example:

    dotnet ef dbcontext scaffold "DataSource=..." Microsoft.EntityFrameworkCore.Sqlite --class-suffix=ReadModel

which would generate:

```cs
public class BloggingContext : DbContext
{
    public DbSet<BlogReadModel> Blogs { get; set; }
    public DbSet<PostReadModel> Posts { get; set; }
```

**Comment by ErikEJ** [comment]
Fwiw, there is a renaming feature in EF Core Power Tools .

**Comment by roji** [comment]
7.0 is introducing scaffolding templates; this would allow you to tweak the templates for the above and any other similar customizations.

**Comment by roji** [comment]
Duplicate of #4038
