### ISSUE TITLE
EF is populating available data from Local into nested collection automatically.. can this be turned off? 

### ISSUE THREAD

**Issue by pajacz** [dotnet/efcore#27883]
## Ask a question

Please consider this scenario:

You have a tables 

Products 1:N ProductVariants
SalesOrder N:1 Products
                    N:1 ProductVariants

When I load from DB SalesOrder with Include<ProductVariant>
and than lover in the code load Product as well, EF will automatically populate a collection property on Product

```C#
public ICollection<ProductVariant> ProductVariants {get; set;}
```

so then the product.ProductVarians has an collection instance with one member, when in DB there is much more... 

I can't use:

```C#
product.ProductVarians ??= context.ProductVariants.Where(pv => pv.ProductId == product.Id).ToListAsync().
```

as property is already instantiated... is there a way to let EF know i don't want this to happen?

Thanks!

----

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0.3

**Comment by ajcvickers** [comment]
@pajacz What specific problem is this causing? The best way forward likely depends on what you are doing with the DbContext.

**Comment by pajacz** [comment]
> @pajacz What specific problem is this causing? The best way forward likely depends on what you are doing with the DbContext.

I need to keep collection properties as NULL to be able to make lazy load all nested when needed.

The use case:

Context will load SalesOrder and SalesOrderLines, where each line has a link to Product and ProductIssue.

Once Product get loaded into Local, it will automatically fill collection property. 

Love in the code I have a method to find first and last issue of the product, and generate a new issues period once missing in collection, i was using ??= to load collection member from DB in not loaded yet, but it's already filled in, but with only one or few members, not all. 

The reason to do that is to optimise the need to  load issues all again and again as few methods need this collection but not all methods are called all the time, it depends on a lot of conditions. 

So for me it will be the best to have collections NULL not being pre-populated by EF at all. 

Do you get what issue i have or you would like to see few lines of code? 

Thanks a lot for any hint!

**Comment by pajacz** [comment]
I don't use EF LazyLoad, having this line in my code instead. 

```
product.ProductVarians ??= context.ProductVariants.Where(pv => pv.ProductId == product.Id).ToListAsync().
```

**Comment by pajacz** [comment]
Is there a way I can know it's not loaded? How LazyLoad does know that? Thanks!

**Comment by pajacz** [comment]
Ok, if i understand what you are saying, does that mean if I'll setup lazy-loading for this property, it will solve my issue i have also?

**Comment by ajcvickers** [comment]
@pajacz Consider using [explicit loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data/explicit) to load the `ProductVariants` navigation. For example:

```C#
context.Entry(product).Collection(e => e.ProductVariants).Load();
```

This will only load if the collection isn't already fully loaded. You can also check this explicitly if needed:

```C#
var isLoaded = context.Entry(product).Collection(e => e.ProductVariants).IsLoaded;
```

**Comment by pajacz** [comment]
ok, great.. thanks!
