### ISSUE TITLE
Unreliable DateTime comparison in `WHERE` clause

### ISSUE THREAD

**Issue by kevinharing** [dotnet/efcore#27889]
### The issue
When querying via EF Core 6.0 on a Sqlite database I'm getting unreliable results when selecting based on DateTime values. 

Sometimes (when running our unit tests) the saved entity can not be found. The given DateTime value is being generated on add according to the format `strftime('%Y-%m-%d %H:%M:%f','now')` and the `%f` is 3 decimals wide. I traced the issue back to the DateTime values. When the DateTime value has trailing zeros, the provider does not consider it equal. I suspect the trailing zero(s) are somewhere not taken into account. See below examples.

Does **not** return added entity:

2022-04-25T09:32:32.**100**0000Z
2022-04-25T09:48:53.**590**0000Z
2022-04-25T10:16:16.**700**0000Z
2022-04-25T13:14:52.**320**0000Z

Does return added entity:

2022-04-25T09:32:32.**111**0000Z
2022-04-25T09:48:53.**595**0000Z
2022-04-25T10:16:16.**707**0000Z
2022-04-25T13:14:52.**323**0000Z
```C#

// Model
public class Release
{
    public long Id { get; set; }
    public int MajorVersion { get; set; }
    public DateTime CreatedAt { get; }
}

// Context
modelBuilder
    .Entity<Release>()
    .Property(release => release.CreatedAt)
    .ValueGeneratedOnAdd()
    .HasDefaultValueSql(Database.IsSqlServer() ? "sysutcdatetime()" : "strftime('%Y-%m-%d %H:%M:%f','now')");

// Query
var dbRelease = await _context.Releases
                .Where(release => release.CreatedAt == createdAt)
                .OrderByDescending(release => release.MajorVersion)
                .ThenByDescending(release => release.CreatedAt)
                .FirstOrDefaultAsync();
```

Note that when I manually set CreatedAt (via reflection) before saving, that it all functions properly. So this issue seems to be related to `HasDefaultValueSql`.

### Potential solution

I suspect the issue is with the DateTime format specified [here](https://github.com/dotnet/efcore/blob/70cd92974e09e938a92384e91b5c3179f4773725/src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs#L16). Shouldn't the `FFFFFFF` in `@"'{0:yyyy\-MM\-dd HH\:mm\:ss.FFFFFFF}'"` be lower-case? [The Microsoft docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#FFFFFFF_Specifier) say the trailing zeros are dropped when using the former format, the latter does not.

### Include version information

Microsoft.Data.Sqlite version: 4.1.0
Target framework: .NET 6.0.4
Operating system: Windows 10 Pro X64

**Comment by bricelam** [comment]
To match the format used by Microsoft.Data.Sqlite and EF Core, use this as your default value expression:

```sql
rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', 'now'), '0'), '.')
```
