### ISSUE TITLE
Switch to Microsoft.CodeAnalysis.CSharp 4.2.0 and unskip suppressor tests

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27895]
#27869 fixed the uninitialized DbSet suppressor to suppress warnings when a constructor is present, following a Roslyn fix in https://github.com/dotnet/roslyn/issues/58073. In order to test this, version 4.2.0 of Microsoft.CodeAnalysis.CSharp (Roslyn) is required, which contains the fix, but that version hasn't yet RTMed and causes issues with current versions of VS. As a result, we're using Microsoft.CodeAnalysis.CSharp 4.1.0 and the relevant tests are currently skipped.

Note: this does not affect the actual suppressor functionality, only the tests. Manually verified with a test program as follows:

Version                 | Warning status
----------------------- | --------------
6.0.4                   | Uninitialized DbSet warnings always issued (with or without a constructor)
7.0.0-preview.3         | Warnings issued only when a constructor is present, suppressed without a constructor
7.0.0-preview.5.22226.3 | No warnings are issues (with or without a constructor)

**Comment by AndriySvyryd** [comment]
VS 2022 17.2.5 appears to be working fine with 4.2.0
