### ISSUE TITLE
migration " ConcurrencyToken"  every time

### ISSUE THREAD

**Issue by FatuityCookie** [dotnet/efcore#27908]
## File a bug

Remember:

no change

### Include your code

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "ConcurrencyToken",
                table: "AM_AuditOrderDetail",
                type: "timestamp(6)",
                rowVersion: true,
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp(6)",
                oldRowVersion: true,
                oldNullable: true)
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.ComputedColumn);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "ConcurrencyToken",
                table: "AM_AuditOrderDetail",
                type: "timestamp(6)",
                rowVersion: true,
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp(6)",
                oldRowVersion: true,
                oldNullable: true)
                .OldAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.ComputedColumn);
        }

### Include provider and version information

EF Core version:
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: net 6.0
Operating system:
IDE: (Visual Studio 2022)

**Comment by roji** [comment]
This issue is lacking information - we need to have a model and your migrations' model snapshot in order to investigate why this happens. Please submit full steps for reproducing this, or post a minimal project which does so.

**Comment by FatuityCookie** [comment]
i test in [abpframework](https://github.com/abpframework/abp) , discover encapsulation of DbContext like AbpDbContext  this problem occurs,but no find this in  other Attribute
samples  use the following link,use Volo.Abp.EntityFrameworkCore.MySQL
https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore

**Comment by FatuityCookie** [comment]
I don't think it's an issue with efcore, so I turned it off，but the other Attribute seem to work fine,I don't know why
