### ISSUE TITLE
DbContext Thread Safe

### ISSUE THREAD

**Issue by jeromep01** [dotnet/efcore#27900]
Hi,

Is v 7 will resolve this issue with .NET Core web sites and multiple calls relying to "A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913." 

Best regards

**Comment by SomnathKadam** [comment]
Hi @roji is any simple example avaiable, can please post here

**Comment by ErikEJ** [comment]
@SomnathKadam Have a look at the docs! https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/
