### ISSUE TITLE
How to explicitly run model validation as part of a unit test in EF Core 6

### ISSUE THREAD

**Issue by poke** [dotnet/efcore#27914]
I would like to explicitly run the model validation as part of a unit test to ensure that the model configuration is sensible. Model validation usually runs automatically when you *use* the database context to make some queries to the database, but in order to avoid attributing model issues with random unit tests, I would like to have an explicit test that runs the model validation explicitly.

In EF Core 5.0, I did this successfully with the following test code:

```csharp
[Fact]
public void ValidateModel()
{
    using var serviceProvider = new ServiceCollection()
        .AddDbContext<DataContext>(options => options
            .UseOracle()
            .UseLoggerFactory(_loggerFactory)
            .ConfigureWarnings(w => w.Default(WarningBehavior.Throw))
        )
        .BuildServiceProvider();

    using var scope = serviceProvider.CreateScope();
    var dbContext = scope.ServiceProvider.GetRequiredService<DataContext>();

    var dependencies = dbContext.Database.GetService<ProviderConventionSetBuilderDependencies>();
    dependencies.ModelValidator.Validate(dbContext.Model, dependencies.ValidationLogger);
}
```

This used the internal service provider to retrieve some dependencies so that it can run the `IModelValidator` with the `DbContext.Model`.

Unfortunately, in EF Core 6.0, this produces two issues:

1. `ProviderConventionSetBuilderDependencies.ModelValidator` is now deprecated (and removed in EF Core 7 as far as I can tell) since “The validation is no longer performed by a convention”. This is not an issue since I can easily retrieve the `IModelValidator` directly from the internal service provider instead.

2. `DbContext.Model` is now a `IRuntimeModel` and unfortunately the model validator contains a hard casting to `IConventionModel` which fails:

   https://github.com/dotnet/efcore/blob/aca50aef8604cc23910d18edce820e0fa7c61910/src/EFCore/Infrastructure/ModelValidator.cs#L756-L757

   It seems that this is also verified internally before calling the model validator:

   https://github.com/dotnet/efcore/blob/aca50aef8604cc23910d18edce820e0fa7c61910/src/EFCore/Infrastructure/ModelRuntimeInitializer.cs#L85-L89

I don’t fully understand the idea around this runtime model yet; the way I understood it is that the runtime model allows model changes/extensions during runtime? That probably makes model validation more complicated but I would be fine just getting the same set of convention-validations that were obtainable before. Especially for the Oracle database provider this contains a lot of interesting details that are really useful when configuring the context for a database-first setup.

After digging a while through the code, I simply cannot find a way that would allow me to get an `IConvention`-compatible model though. Is this obtainable at all after building the service provider, or would I have to maybe restructure my test completely so that I create my own model builder instead?

I realize that I am in a highly unsupported territory here, and I’m totally fine with that. This is not used for any production code anyway and is only meant to be part of a unit test. But I would really glad about any hints you could give me on this. Thanks :blush:

**Comment by ajcvickers** [comment]
Validation happens automatically when the model is built. If you get the mode by accessing `context.Model`, then validation will run.

**Comment by poke** [comment]
Ohhhhhh! 🤯

This turned out to be way easier that I expected this to be! That’s the kind of magic that I like 😁

Thanks a ton @ajcvickers for your help and the super quick response!
