### ISSUE TITLE
Nullability check in in-memory provider does not recognize default value

### ISSUE THREAD

**Issue by poke** [dotnet/efcore#27913]
The nullability-check that was added in #23094 apparently does not respect configured default values which causes required nullable fields that have a configured default value to cause a `DbUpdateException` for the nullability validation.

For example, take this database configuration:

```csharp
public class ExampleContext : DbContext
{
    public DbSet<ExampleItem> Items { get; set; }

    public ExampleContext(DbContextOptions<ExampleContext> options)
        : base(options)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<ExampleItem>(e =>
        {
            e.Property(i => i.IsImportant)
                .IsRequired()
                .HasDefaultValue(false);
                //.HasDefaultValueSql("0");
        });
    }
}

public class ExampleItem
{
    public int Id { get; set; }
    public string Value { get; set; }
    public bool? IsImportant { get; set; }
}
```

Here, the `IsImportant` is nullable because while it is configured to be `NOT NULL` (via `IsRequired`), it has a configured default value using `HasDefaultValue` or `HasDefaultValueSql` which enforces this value at the database layer *if* the property has the value `null`.

If I make the `IsImportant` a non-nullable `bool` and configure it with a SQL-based default, then EF Core will also warn me about this:

> Microsoft.EntityFrameworkCore.Model.Validation [Microsoft.EntityFrameworkCore.Model.Validation.BoolWithDefaultWarning] The 'bool' property 'IsImportant' on entity type 'ExampleItem' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead, so that the default will only be used for inserts when the property value is 'null'.

---

Now, the problem is of course that the in-memory provider will not able to recognize the `HasDefaultValueSql` since it doesn’t actually do SQL. But maybe it should at least *not* generate a `DbUpdateException` from the null-check. While it cannot interpret what the default value is (so maybe there be a warning logged that the default value is not available), it can interpret that there is *some* default value, so keeping the value as `null` in the item is fine.

In the case of the `HasDefaultValue` is could at least theoretically also interpret this value properly, but that is probably a feature extension which I also wouldn’t expect the in-memory provider to have for now. So having the same behaviro as with `HasDefaultValueSql` would be fine to me.

### Test code

If you take the above `ExampleDbContext` and `ExampleItem` declarations and put it into a standard xUnit project then you can use this test class to test this behavior:

```csharp
public class Test 
{
    [Fact]
    public async Task Sqlite()
    {
        using var connection = new SqliteConnection("Data Source=:memory:");
        connection.Open();

        var dbOptions = new DbContextOptionsBuilder<ExampleContext>()
            .UseSqlite(connection)
            .Options;

        await RunTest(dbOptions);
    }

    [Fact]
    public async Task InMemory()
    {
        var dbOptions = new DbContextOptionsBuilder<ExampleContext>()
            .UseInMemoryDatabase(nameof(InMemory))
            .Options;

        await RunTest(dbOptions);
    }

    private async Task RunTest(DbContextOptions<ExampleContext> dbOptions)
    {
        using (var db = new ExampleContext(dbOptions))
        {
            await db.Database.EnsureCreatedAsync();
            db.Items.Add(new ExampleItem() { Value = "Foo" });
            db.Items.Add(new ExampleItem() { Value = "Bar", IsImportant = false });
            db.Items.Add(new ExampleItem() { Value = "Baz", IsImportant = true });
            await db.SaveChangesAsync();
        }

        using (var db = new ExampleContext(dbOptions))
        {
            var items = await db.Items.ToArrayAsync();
            Assert.Contains(items, x => x.Value == "Foo" && x.IsImportant == false);
            Assert.Contains(items, x => x.Value == "Bar" && x.IsImportant == false);
            Assert.Contains(items, x => x.Value == "Baz" && x.IsImportant == true);
        }
    }
}
```

I’m comparing the Sqlite and in-memory providers here, the former obviously supporting the configured default value while the in-memory provider does not.

If you run these tests, with either `HasDefaultValue` or `HasDefaultValueSql` configured on the required `IsImportant` property, then the test for the in-memory provider will fail with the following message:

> Microsoft.EntityFrameworkCore.DbUpdateException : Required properties '{'IsImportant'}' are missing for the instance of entity type 'ExampleItem'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the entity key value.

---

Version info: This is EF Core 6.0.4 with the InMemory and Sqlite providers, running on .NET 6.

**Comment by ajcvickers** [comment]
Both `HasDefaultValue` and `HasDefaultValueSql` are relational concepts for setting the column default. The in-memory provider does not support relational concepts, including column defaults. Consider [not using the in-memory provider for testing](https://docs.microsoft.com/en-us/ef/core/testing/).

**Comment by poke** [comment]
I am aware of the limitations the in-memory provider has and I am not using it to test actual database logic. Instead it is being used to test services that depend on easy database interactions (which the in-memory provider handles just fine) as an alternative to completely mocking the contexts and DbSets.

Unfortunately, I cannot rely on a different provider for testing since the project is working with a database-first Oracle database with a lot of Oracle specific configurations that make it impossible to run this e.g. against an SQLite database, and running the tests as integration tests against a real Oracle database is too expensive and far from trivial.

As I said, I am absolutely fine with the limitations of the in-memory provider and that’s also why I was a bit confused when I learned about the introduction of this nullability check since that is a functionality that I would not expect the provider to have. But the way it is implemented right now at least impacts the null check’s usefulness for more complicated model configurations.

So as mentioned above, I wouldn’t expect the in-memory provider to interpret the `HasDefaultValue` or `HasDefaultValueSql` to provide an actual value but maybe the nullability check could be adjusted so that it realizes that a default value is configured and no nullability error needs to be thrown.

**Comment by poke** [comment]
Yes, that’s what I did and I’m totally fine with that for my project! :blush: (forgot to mention that in the OP)

I just thought that it might make sense to make the nullability check *a little bit* smarter and make it recognize that there are configured default values before throwing because of a configured required property.

At least the way I understand it is that `IsRequired` is just as much a foreign concept to the in-memory provider as `HasDefaultValue` is. So if there was interest in adding the former, maybe it would be worth to go a step further and make it that check at least recognize the existence of a default value.
