### ISSUE TITLE
Add support for user defined aggregate window functions

### ISSUE THREAD

**Issue by eugenpaval** [dotnet/efcore#27912]
Would like to be able to define my own aggregate window functions. Sqlite engine has support for this via sqlite3_create_window_function but Microsoft.Data.Sqlite supports only regular aggregate functions. This will be useful, for example to define group_concat() function which works over partitions by concatenating values in a column, optionally indicating the separator and the max number of concatenations.

A function similar with connection.CreateAggregate(), say connection.CreateWindowAggregate() would achieve the desired result.

**Comment by AndriySvyryd** [comment]
How is this different from https://github.com/dotnet/efcore/issues/27901?

**Comment by eugenpaval** [comment]
It is the same issue. The first one was a question I posted on stackoverflow. I was directed to open an issue here which is this one. I am not sure how the stackoverflow question ended as an issue in github. I guess you can close https://github.com/dotnet/efcore/issues/27901.
