### ISSUE TITLE
OnModelCreating(ModelBuilder modelBuilder) is triggered twice by dbContext.Database.EnsureCreated()

### ISSUE THREAD

**Issue by AvtsVivek** [dotnet/efcore#27921]
I am using Sqlite, and for the scenario when initially the database is not yet created, OnModelCreating is called twice at the point when dbContext.Database.EnsureCreated is executed. If the database is already existing, then OnModelCreating is called only once as expected. 

Steps to reproduce.
1. Create a console app on .net 6 with Visual Studio 2022. The files are as follows.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
```

The cs file is as follows.

```cs



using Microsoft.EntityFrameworkCore;

class Program
{
    static void Main(string[] args)
    {
        using var dbContext = new BlogContext();
        dbContext.Database.EnsureCreated();

        dbContext.Blogs.Add(new Blog
        {
            Name = "Blog1",
            Posts = new List<Post>
            {
                new Post { Title = "Title1" }
            }
        });

        dbContext.SaveChanges();
    }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; } = default!;
    public DbSet<Post> Posts { get; set; } = default!;

    protected override void OnModelCreating(ModelBuilder modelBuilder) 
    {

    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    { 
        optionsBuilder.UseSqlite("Data Source=database.sqlite");
    } 
}

public class Blog
{
    public int BlogId { get; set; }
    public string Name { get; set; } = default!;
    public List<Post> Posts { get; set; } = default!;
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; } = default!;
}

```

3. Inside of \bin\Debug\net6.0 of you csproj folder, ensure the database.sqlite is not yet created. If it exists, delete it.

4. Now place a breakpoint at **dbContext.Database.EnsureCreated();** and also inside of the method **OnModelCreating(ModelBuilder modelBuilder)**

5. Run, Press F10 at **dbContext.Database.EnsureCreated();**. You should notice that OnModelCreating is triggered twice. 
6. Running once creates the database. Then next time when you run, since the database is already existing, OnModelCreating is triggered only once as exptected.

Applies to Sqlite db. I have **NOT** checked with other db providers.

**Comment by AndriySvyryd** [comment]
This is by design. When a database is created a design-time model is created that contains additional metadata, that's typically not needed during normal operation.

**Comment by ARULKUMAR30024** [comment]
public DynamicDbContext(DbContextOptions<DynamicDbContext> options, Type dynamicEntityType) : base(options)
    {
        _dynamicEntityType = dynamicEntityType;
       
    }
    public Type dynamicType { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Dynamically add the entity to the model
        if (_dynamicEntityType != null)
        {
            modelBuilder.Entity(_dynamicEntityType);
           
            
        }


    } my problem is onmodelcreating is not triggered again. we dont have any static models in our application so i just build in run time everything goes fine due  onmodelcreating not triggered again new entity is not append in context model  please if you have any solution suggest to me and if you need any clarification about this feel free to ask
