### ISSUE TITLE
Unclear docs on test from cmd line

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#27923]
On https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md

It is not clear if test.cmd builds and runs test (as per the table) or requires build first:

sentence further on: Tests can be run on the command line (after build)

Happy to do a PR - assume the table must be updated.

**Comment by ajcvickers** [comment]
@ErikEJ It requires build first. I often run tests from the command line with `.\test` after building in the IDE.

**Comment by ErikEJ** [comment]
I will try to make it clearer.
