### ISSUE TITLE
Temporal Tables HIDDEN (INMEMORY ISSUE?)

### ISSUE THREAD

**Issue by cgountanis** [dotnet/efcore#27949]
Think we have an issue here. I have a few temporal tables that we set the ValidFrom/ValidTo fields to HIDDEN. Scaffold used to ignore them now if adds lines to the CONTEXT. UnitTesting InMemory has issues with this complaining there are missing fields. I mean is this a XUNIT issue or the fact the Context is now including more of this information.

I tried removing the HIDDEN property on ValidFrom/ValidTo fields, scaffold skips automatically (that's cool now!) but same error.

```
public ApplicationTests()
{
	// Create in memory database context.
	var optionsBuilder = new DbContextOptionsBuilder<Context>();
	optionsBuilder.UseInMemoryDatabase("InMemoryDatabase");
	optionsBuilder.EnableSensitiveDataLogging();
	_context = new Context(optionsBuilder.Options);

	// Create repository.
	_repository = new Repository(_context);
}
```

The reason why this might be XUNIT. Should it be skipping SQL HIDDEN fields like it used to? I mean the error says it all, how can the property be in the model, if HIDDEN and never got scaffolded into the generated model?
`System.InvalidOperationException : The property 'TEMPORALTABLENAME.ValidFrom' could not be found. Ensure that the property exists and has been included in the model.`

New in Context (Since NET6 Scaffold DB-First)
```
entity.ToTable(tb => tb.IsTemporal(ttb =>
{
	ttb.UseHistoryTable("XXXTABLENAME", "task");
	ttb
		.HasPeriodStart("ValidFrom")
		.HasColumnName("ValidFrom");
	ttb
		.HasPeriodEnd("ValidTo")
		.HasColumnName("ValidTo");
}
```

**Comment by cgountanis** [comment]
```
Stack Trace:
IReadOnlyEntityType.GetProperty(String name)
IMutableEntityType.GetProperty(String name)
TemporalPeriodPropertyBuilder.HasColumnName(String name)
<>c.<OnModelCreating>b__503_760(TemporalTableBuilder`1 ttb) line 1898
SqlServerTableBuilderExtensions.IsTemporal[TEntity](TableBuilder`1 tableBuilder, Action`1 buildAction)
<>c.<OnModelCreating>b__503_748(TableBuilder`1 tb) line 1895
RelationalEntityTypeBuilderExtensions.ToTable[TEntity](EntityTypeBuilder`1 entityTypeBuilder, Action`1 buildAction)
<>c.<OnModelCreating>b__503_58(EntityTypeBuilder`1 entity) line 1895
ModelBuilder.Entity[TEntity](Action`1 buildAction)
Context.OnModelCreating(ModelBuilder modelBuilder) line 1889
<41 more frames...>
DbContext.get_DbContextDependencies()
DbContext.get_ContextServices()
DbContext.get_Model()
InternalDbSet`1.get_EntityType()
InternalDbSet`1.CheckState()
InternalDbSet`1.get_EntityQueryable()
IQueryable.get_Provider()
Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
Repository.GetSomethingUnrelated();
```

**Comment by ajcvickers** [comment]
@cgountanis The in-memory database doesn't support temporal tables. In general, the [in-memory database is not recommended for testing](https://docs.microsoft.com/en-us/ef/core/testing/).

**Comment by cgountanis** [comment]
Just surprised because it worked like 3 years. For some reason it just
doesn't like those added context entries. Thanks

**Comment by ajcvickers** [comment]
@cgountanis If the model contains temporal table configuration, then it will likely not work with the in-memory database, regardless of whether the tests use that particular part of the model or not. You could consider conditionally building the model differently for different providers, as shown here: https://github.com/dotnet/efcore/issues/27587#issuecomment-1061919558

**Comment by cgountanis** [comment]
Thanks
