### ISSUE TITLE
Does EFCore 6 supports table valued parameters of table valued functions?

### ISSUE THREAD

**Issue by andrey-bulat** [dotnet/efcore#27955]
I am trying to pass table valued parameter to table valued UDF but got InvalidOperationExceptin.
Code for UDF call was generated by EFCore Power Tools for EFCore6
Is it valid scenario?

Stored procedures which contain DataTable parameters (TVP) as well produce the same exception.
_What is interesting is that I was able to call stored procedures with TVP when use EFCore3._

**_project_**:

net6.0
PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0"
PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.4"

_I updated SqlClient to latest version but this didn't help._

**_Generated code_** seems correct:

    public partial class Shared_CampaignContext
    {

        [DbFunction("campaign_label_find_udf", "dbo")]
        public IQueryable<campaign_label_find_udfResult> campaign_label_find_udf(DataTable LabelIds, int? CampaignID, int? CampaignIDSort, int? CategoryID, string Name)
        {
            return FromExpression(() => campaign_label_find_udf(LabelIds, CampaignID, CampaignIDSort, CategoryID, Name));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<campaign_label_find_udfResult>().HasNoKey();
            modelBuilder.Entity<IntValueEntry>().HasNoKey();
        }
    }

**_Unit test_**:

        [Fact]
        public async Task Test1()
        {
            using(var ctx = new Shared_CampaignContext())
            {
                DataTable dataTable = new DataTable();
                dataTable.Columns.Add("Value", typeof(int));

                var result = ctx.campaign_label_find_udf(dataTable,null,null,null,null);
            }
        }

**_Exception_**:

  Message: 
System.InvalidOperationException : The parameter 'LabelIds' for the DbFunction 'Context.Context.Shared_CampaignContext.campaign_label_find_udf(System.Data.DataTable,int?,int?,int?,string)' has an invalid type 'DataTable'. Ensure the parameter type can be mapped by the current provider.

  Stack Trace: 
RelationalModelValidator.**ValidateDbFunctions**(IModel model, IDiagnosticsLogger`1 logger)
RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
DbContextServices.CreateModel(Boolean designTime)
DbContextServices.get_Model()
<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
ServiceProviderEngineScope.GetService(Type serviceType)
ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
DbContext.get_DbContextDependencies()
DbContext.get_ContextServices()
DbContext.get_InternalServiceProvider()
DbContext.get_DbContextDependencies()
DbContext.FromExpression[TResult](Expression`1 expression)
Shared_CampaignContext.campaign_label_find_udf(DataTable LabelIds, Nullable`1 CampaignID, Nullable`1 CampaignIDSort, Nullable`1 CategoryID, String Name) line 17
UnitTest1.Test1() line 30

**Comment by ErikEJ** [comment]
Suggest you provide a complete repro incl. SqL create scripts in the EF Core Power Tools repository.

**Comment by andrey-bulat** [comment]
> 

Please see https://github.com/andrey-bulat/EfCore6Test

**Comment by ErikEJ** [comment]
I have created https://github.com/dotnet/efcore/issues/27955
