### ISSUE TITLE
[Required] Used to get generated and be super helpful with MVC validation

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#27962]
[Required] Used to get generated and be super helpful with MVC validation. e.g. EF would scaffold the model with [Required]. Now it just does nullable ? fields. But this doesn't see to play nice with ModelState.IsValid anymore and you don't get warnings about missing fields.

ModelState.IsValid supports nullable ? fields or [Required] is brought back.

Any help appreciated. Thanks!

.Net Core 6.

**Comment by roji** [comment]
This would probably be enabled via scaffolding templates (#4038).

**Comment by OpenSpacesAndPlaces** [comment]
Worked around this with "TryValidateModel" being explicitly called
