### ISSUE TITLE
EF7 beta6 missing from myget release source?

### ISSUE THREAD

**Issue by bitcrazed** [dotnet/efcore#2796]
Might me misunderstanding something here, but is the EF 7 Beta6 package missing from the [MyGet release source](http://myget.org/gallery/aspnetrelease)?
![image](https://cloud.githubusercontent.com/assets/961950/9142393/41995044-3cf4-11e5-97d4-bc5f73754803.png)

**Comment by ErikEJ** [comment]
The EntityFramework meta package has been removed, use for ex EF.SqlServer or EF.Relational

**Comment by bitcrazed** [comment]
Thanks, but shouldn't the meta package be removed from MyGet?

**Comment by rowanmiller** [comment]
That's a good question, I'm not sure if we have left all the previous version of the packages there (the meta package did ship for Beta 5). 

cc @Eilon to see what he thinks.

**Comment by Eilon** [comment]
No one should ever use the `aspnetrelease` source anyway, outside of the feature team working on stabilization. If you see anything pointing at it, we should fix it to point to a correct feed.

We don't generally go back and purge those feeds, but they do occasionally get purged for other maintenance purposes.
