### ISSUE TITLE
GetColumnName() in EF Core 6 returns property name not mapped column name

### ISSUE THREAD

**Issue by e-duran** [dotnet/efcore#27968]
I'm using EF Core 6 (6.0.2) with SQL Server 2019 with the following entity:

```
public partial class MyEntity
{
        [Column("External_ExternalId")]
        public Guid? ExternalId { get; set; }
}
```
I'm trying to get the mapped column name (`External_ExternalId`) for the `ExternalId` property with the following code:
```
var entityType = dbContext.Model.FindEntityType(typeof(MyEntity));
var property = entityType.GetProperties().Single(property => property.Name.Equals("ExternalId", StringComparison.OrdinalIgnoreCase));
var columnName = property.GetColumnName(StoreObjectIdentifier.Create(property.DeclaringEntityType, StoreObjectType.Table).GetValueOrDefault());
```
`columnName` is `ExternalId` instead of `External_ExternalId`. How can I get the actual name of the table's column? I tried GetColumnBaseName() but got the same result. Same if I configure the mapping with the fluent API.

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2022 (17.1.6)

**Comment by AndriySvyryd** [comment]
@e-duran Can you provide a repro project? The code you posted and `GetColumnBaseName` return the expected result when I tested it

**Comment by e-duran** [comment]
@AndriySvyryd My apologies, I don't know why the first time I tried the code above it didn't work. After playing around a bit with it and restarting Visual Studio, that same snippet of code seems to be working fine now.
