### ISSUE TITLE
Add MaxByAsync and MinByAsync

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/efcore#27977]
.NET 6 introduces the `MaxBy` and `MinBy` APIs. I would like to query the database using these methods, more specifically the async version.

I am proposing to add the following methods to `EntityFrameworkQueryableExtensions`:
```c#
public static Task<TSource> MaxByAsync<TSource, TKey>(this IQueryable<TSource> source, Expression<Func<TSource, TKey>> selector, CancellationToken cancellationToken = default);

public static Task<TSource> MinByAsync<TSource, TKey>(this IQueryable<TSource> source, Expression<Func<TSource, TKey>> selector, CancellationToken cancellationToken = default);
```

I am happy to provide a PR as soon as I get feedback on this issue.

**Comment by ajcvickers** [comment]
Duplicate of #25566.

**Comment by CollinAlpert** [comment]
@ajcvickers I saw that issue but decided my issue was different, as I am proposing to add async versions. My apologies for raising a duplicate.

**Comment by ajcvickers** [comment]
@CollinAlpert Sync and async should be done at the same time.
