### ISSUE TITLE
Caching query result for the lifetime of DbContext

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#27989]
There are extension libraries for having 2nd level cache for EF Core, but I want its lifetime to be the same of DbContext. It is if all queries behaved like `Find`. Change Tracker already plays the role of a cache, and only memoizing of expression tree is required.

Is there a step when expression is transformed, so everything is replaced with const values, and what interceptor should I use to get access to such expression tree?

**Comment by roji** [comment]
> Change Tracker already plays the role of a cache [...]

The change tracker only deals with entity instances, for the purposes of tracking changes - so they can be saved back to the database. This is why Find exists for entity instances only, given their primary key. The change tracker is not designed to track the non-entity results of arbitrary queries.

Out of curiosity, what's the logic behind caching query results only for the lifetime of a DbContext? If the same query is executed on a different DbContext, aren't its cached results just as valid (as long as they're not stale)?

**Comment by voroninp** [comment]
> If the same query is executed on a different DbContext

My aggregates produce domain events as a result of their state change (not Event Sourcing though).
Event handlers run within transaction of `SaveChanges`. (intentionally).
Multiple handlers can process the same event and query the same data, that's why I would like to have caching to avoid repetitive db reads. `Find` would suffice if I only used PKs, but this is not always the case.

**Comment by roji** [comment]
> Event handlers run within transaction of SaveChanges. (intentionally).

Note that this by itself doesn't guarantee that queries return the same data; at the default isolation level (ReadCommitted), the same query can return different results when executed multiple times in the same transaction. RepeatableRead/Serializable/Snapshot provide stronger guarantees - but make sure that's really what you want (there are costs).

So again, if this is about avoiding reads for perf, I'm not sure why you wouldn't cache cross-context with one of the 2nd-level caching extensions; if you're OK with slightly stale data within your single context's handlers, that should generally also be acceptable across contexts.

Otherwise you may be able to build a context-scoped caching mechanism by injecting a visitor into the query pipeline - but it's not likely to be simple.

**Comment by voroninp** [comment]
Yes, it's a kind of client-side snapshot, though not 100%.

**Comment by voroninp** [comment]
@roji , could you give me slightly more guidance about implementing the feature myself?

For example, here is the method:
```
Task<Foo> FindByOrderId(string orderId) => 
    DbContext.Set<Foo>().SingleOrDefaultAsync(_ => _.OrderId == orderId);
```

I can turn it into this one:
```
async Task<Foo> FindByOrderId(string orderId)
{
    var cached = DbContext.ChangeTracker.Entries<Foo>()
        .Select(_ => (Foo)_.Entity)
        .SingleOrDefault(_ => _.OrderId == orderId);
    
    return cached ?? await DbContext.Set<Foo>().SingleOrDefaultAsync(_ => _.OrderId == orderId);
}
```

I can generalize it this way:
```
async T? CachedSingleOrDefaultAsync<T>(this DbQuery<T> query, Expression<Func<T, bool>> predicate)
{
    var cached = DbContext.ChangeTracker.Entries<T>()
        .Select(_ => (T)_.Entity)
        // How large is the performance hit here?
        .SingleOrDefault(predicate.Compile()); 

    return cached ?? await DbContext.Set<Foo>().SingleOrDefaultAsync(predicate);
}
```

But ideally I'd have it as a prefix method:
```
DbContext.Set<Foo>().FromChangeTrackerFirst().AnyQuery(...);
```

**Comment by roji** [comment]
@voroninp it looks like your FindByOrderId can simply call EF's DbSet.Find, which already looks in the change tracker before going to the database ([see the docs](https://docs.microsoft.com/en-us/ef/core/change-tracking/entity-entries#find-and-findasync).

Other queries which don't just look up by primary key would need to perform actual queries on ChangeTracker, similar to what you're attempting above. Calling Compile() on each query invocation definitely is going to have an impact, but you'll have to benchmark to see if that matters in your application. Some sort of cache from the the expression tree to a compiled delegate could help with the perf.

Apart from that you should be able to pack this up as an extension method over IQueryable.

**Comment by voroninp** [comment]
@roji , unfortunately `OrderId` is not a primary key. But... If EF had a counterpart of `Find` for searching by alternative key, that would suffice. ;-)

**Comment by stevendarby** [comment]
Be cautious with the generalised version as it may not be as generalisable as it looks.

For example, if the predicate involves a reference navigation (e.g. `x => x.Order.Id == orderId`) then if a local entity hasn't loaded that reference entity you would get a NRE / it wouldn't be accurate. Whereas when translated and executed as SQL, it would work and be accurate.

**Comment by voroninp** [comment]
@stevendarby That's exactly one of the reasons why Aggregate tactical pattern is cool. One always fetches all parts of the aggregate (owned entities + always include).
In that regard Navigation properties is a two edged sword. Devs abuse them more often than not. It's a nightmare to have an entity with a set of properties which are null or not null depending on the implicitly defined requirements encoded in query with a bunch of includes somewhere earlier in the call stack.
