### ISSUE TITLE
How to specify which SQL Server DbContext constructor to use in ASP.NET Core dependency injection?

### ISSUE THREAD

**Issue by ryancole** [dotnet/efcore#27982]
I'm trying to pass the current HTTP request user information to my DbContext constructor in an ASP.NET Core application. My DbContext has the following constructors ...

        public WibWorkspaceContext(DbContextOptions<WibWorkspaceContext> options) : base(options)
        {

        }

        public WibWorkspaceContext(DbContextOptions<WibWorkspaceContext> options, string username) : base(options)
        {

        }

So one is the usual default constructor and the other I'm trying to pass in a username. My ASP.NET Core code for configuring the DbContext looks like ...

        ... .AddDbContext<WibWorkspaceContext>(ConfigureWorkspaceContext);

        private void ConfigureWorkspaceContext(IServiceProvider serviceProvider, DbContextOptionsBuilder options)
        {
            var httpContext = serviceProvider.GetService<IHttpContextAccessor>().HttpContext;
            var httpRequest = httpContext.Request;

            var identityEmail = httpContext
                .User
                .FindFirstValue(ClaimTypes.Email);

            var connectionString = m_configuration["ConnectionStrings:Sql"];

            var migrationsAssembly = typeof(WibWorkspaceContext).GetTypeInfo().Assembly.GetName().Name;

            options
                .UseLazyLoadingProxies()
                .UseSqlServer(connectionString, x => x.MigrationsAssembly(migrationsAssembly));
        }

So you can see the `UseSqlServer` line, but is there a way to pass in more parameters to the DbContext constructor some how? I want to somehow pass in the `identityEmail` variable into the `DbContext`.

**Comment by AndriySvyryd** [comment]
@ryancole You can use
``` C#
AddDbContextFactory<WibWorkspaceContext, WibWorkspaceContextFactory>(options => 
            .UseLazyLoadingProxies()
            .UseSqlServer(connectionString, x => x.MigrationsAssembly(typeof(WibWorkspaceContext).GetTypeInfo().Assembly.GetName().Name)))
```

Where `WibWorkspaceContextFactory` implements `IDbContextFactory<WibWorkspaceContext>` and can depend on services in DI like `IHttpContextAccessor` and `DbContextOptions<WibWorkspaceContext>`

**Comment by ajcvickers** [comment]
See also [ActivatorUtilitiesConstructorAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilitiesconstructorattribute?view=dotnet-plat-ext-6.0)
