### ISSUE TITLE
Using EXECUTE AS USER puts session in kill state

### ISSUE THREAD

**Issue by ryancole** [dotnet/efcore#27999]
I'm using Entity Framework Core in an application and am trying to switch the user context of a connection / session. I'm attempting to do this using a `DbConnectionInterceptor`. My idea is to intercept the connection-opened event and run my context-switching query there. I have an interceptor coded that looks like the following ...

    public class ExecuteAsDbInterceptor : DbConnectionInterceptor
    {
        private readonly string m_username = "wibuser";

        public ExecuteAsDbInterceptor(string username)
        {
            m_username = username;
        }

        #region Methods

        public override async Task ConnectionOpenedAsync(DbConnection connection, ConnectionEndEventData eventData, CancellationToken cancellationToken = default)
        {
            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = $"EXECUTE AS USER = '{m_username}' WITH NO REVERT";

                var result = await cmd.ExecuteNonQueryAsync(cancellationToken);

                Console.WriteLine(result.ToString());
            }

            await base.ConnectionOpenedAsync(connection, eventData, cancellationToken);
        }

        #endregion
    }

This runs seemingly without error (`-1` result code) but it results in the following error found in the SQL Server Logs as soon as the next queries come through ...

> The connection has been dropped because the principal that opened it subsequently assumed a new security context, and then tried to reset the connection under its impersonated security context. This scenario is not supported. See "Impersonation Overview" in Books Online.

> Error: 18059, Severity: 20, State: 1.

And then ultimately the following EF Core exception ...

    Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot continue the execution because the session is in the kill state.
    A severe error occurred on the current command.  The results, if any, should be discarded.
       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
       at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
       at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

I've tried using both the `WITH NO REVERT` and without it - it doesn't seem to make a difference, although [the documentation][1] says to use `WITH NO REVERT` when connection pooling is in place. I believe EF Core uses connection pooling.

Is this possible with EF Core? Judging by the SQL Server Log text, it looks like EF is maybe trying to set its own context and it's clashing with this query of mine maybe?

  [1]: https://docs.microsoft.com/en-us/sql/t-sql/statements/execute-as-transact-sql?view=sql-server-ver15#using-with-no-revert

**Comment by roji** [comment]
@ryancole at the SQL Server/SqlClient level, you're required to revert your impersonation before the connection is returned to the pool - remove the `WITH NO REVERT` clause and execute [REVERT](https://docs.microsoft.com/en-us/sql/t-sql/statements/revert-transact-sql) in your interceptor before the connection is closed (i.e. returned).

Note that this has nothing to do with EF Core; connection pooling is implemented at the SqlClient level (so underneath EF Core), and can be disabled by setting `Pooling=false` (but performance is likely to degrade considerably when doing so). See below for a minimal repro using SqlClient only (without EF Core).

<details>
<summary>Repro without EF</summary>

```c#
var connectionString =
    "Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false";

await using var conn = new SqlConnection(connectionString);

await conn.OpenAsync();

using var cmd = new SqlCommand("EXECUTE AS USER = 'dbo'", conn);
await cmd.ExecuteNonQueryAsync();

// Without the below lines, the first execution after the connection is returned from the pool (below) fails with
// 'Cannot continue the execution because the session is in the kill state'.
// cmd.CommandText = "REVERT";
// await cmd.ExecuteNonQueryAsync();

await conn.CloseAsync();

await conn.OpenAsync();
cmd.CommandText = "SELECT 1";
Console.WriteLine(await cmd.ExecuteScalarAsync());
```

</details>

**Comment by ryancole** [comment]
@roji Ah, I see. Yea I'd like to leave pooling enabled. I'll give your suggestion a try. Thank you for the sample code too. I went ahead and went down a "plan B" path and went to full fledged server logins for each user instead of just server principals without logins. The server logins are not needed though, so I'd like to ideally get the `EXECUTE AS USER` approach working.

I'm unsure about the long term pros and cons of either approach, but I guess that's what I'm eventually going to find out. :P

**Comment by roji** [comment]
@ryancole note that adding `EXECUTE AS USER ...` and `REVERT` in your interceptor would add two database roundtrips for each and every command - that's likely to be quite bad for perf. A server login for each user is likely to be the better option here, especially snice `EXECUTE AS USER` requires server users in any case. The one possible disadvantage is that since the login is specified on the connection string, you'll end up with a pool per user; if each user typically does one operation (or very few), that almost amounts to disabling pooling.

I'm going to go ahead and close this as there isn't anything EF-related to be done, but feel free to post back if you have any further thoughts or questions.

**Comment by facu79** [comment]
Hi @roji  If I need to use the impersonation mechanism (motivations not listed here), and to avoid double round trips to the server, is it correct to add "execute as..." and "revert" to each command text (using EFC interceptor)? From my point of view, it avoids the performance issue and the sqlclient can still maintain a connection pool for the logged in user. I'm fine?

Thanks in advance.
