### ISSUE TITLE
can provide a method for obtaining query parameters?

### ISSUE THREAD

**Issue by saber-wang** [dotnet/efcore#28001]
Currently, 'ToQueryString' method has been provided, but no method to obtain parameters has been provided.

**Comment by roji** [comment]
@saber-wang are you looking for access to the parameter data as .NET objects? If so, that's not what ToQueryString was designed for - it exists to provide a string that can be viewed and printed for debugging purposes.

To access parameter data, you may want to implement a [command interceptor](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#database-interception) - that's a piece of code which sees the low-level DbCommand before it gets executed. That contains the actual SQL as well as all the parameter data.

**Comment by roji** [comment]
@saber-wang take a look at command interceptors as I wrote above.

**Comment by saber-wang** [comment]
@roji command interceptor does not meet requirements.

**Comment by roji** [comment]
@saber-wang you'll have to provide a bit more detail than that.

**Comment by saber-wang** [comment]
@roji  This is just a little expectation😁.
At present, there is a need to obtain query strings and parameters in specific business operations and process them as part of the operation. If the command interceptor is used, the business code has been separated, and the command interceptor is predefined and global.

**Comment by roji** [comment]
The command interceptor receives a [CommandEventData](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.commandeventdata?view=efcore-6.0) instance that provides contextual information; it notably provides access to the DbContext instance being used. This allows you place arbitrary data on your context which can be accessed by the interceptor.

If this still seems insufficient, you'll have to provide concrete information on exactly what you're trying to achieve is a bit vague, and why interceptors cannot meet that need.
