### ISSUE TITLE
How can I see what issues are fixed in a release?

### ISSUE THREAD

**Issue by mattfrear** [dotnet/efcore#28000]
Hello

How can I find out what issues are fixed in a release?

e.g. yesterday I upgraded from 3.1.x to 6.0.4 and found an issue - I was getting an ArgumentException
`Expression of type 'Task<List<ServiceAddOn>>' cannot be used for return type 'Task<IEnumerable<ServiceAddOn>>'`

Today I upgraded to 6.0.5 and my issue was fixed, yay! I would like to see what issues were fixed in 6.0.5 so that I can find out the root cause.

Perhaps this project should [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)?

**Comment by roji** [comment]
@mattfrear all fixed issues are referenced by their Github milestone - [here are all the milestones for released versions](https://github.com/dotnet/efcore/milestones?state=closed). For example, [here are the issues fixed for 6.0.4](https://github.com/dotnet/efcore/milestone/136?closed=1).

As 6.0.5 has just been released, its milestone hasn't yet been updated (/cc @AndriySvyryd we need to reassign the appropriate issues from 6.0.x).

**Comment by mattfrear** [comment]
Thanks @roji. 

Looking forward to seeing the 6.0.5 milestone when it is updated.

**Comment by stevendarby** [comment]
You can find changelogs in the Releases but again 6.0.5 is lacking
https://github.com/dotnet/efcore/releases

**Comment by mattfrear** [comment]
Thanks @stevendarby, yep I went to the Releases page first. The first 4 releases at the top of the page didn't have any info, so I looked elsewhere. 

I think this team's release process needs a bit of polish to get that info up on there in a timely manner.

**Comment by AndriySvyryd** [comment]
The only issue fixed in 6.0.5 was [Query exception after upgrading from 6.0.1 to 6.0.2](https://github.com/dotnet/efcore/issues/27600)
