### ISSUE TITLE
Read-only transaction support

### ISSUE THREAD

**Issue by nanasi880** [dotnet/efcore#28003]
**What problem are you trying to solve?**

I mainly use MySQL.
MySQL and other major databases allow you to specify read-only mode when initiating a transaction.
If these can be properly specified by the application, they can provide performance and safety benefits.

**Describe the solution you'd like**

A typical code snippet that initiates a transaction is as follows

```
await using var tx = await dbContext.Database.BeginTransactionAsync(token);
```

I prefer the design where BeginTransactionAsync receives transaction hints.

```
public enum TransactionHint
{
    ReadWrite = 0,
    ReadOnly = 1
}
```

```
await using var tx = await dbContext.Database.BeginTransactionAsync(TransactionHint.ReadOnly, token);
```

The parameter is a hint, and databases that do not support transaction mode can ignore it or throw an exception.

**Comment by roji** [comment]
Read-only transactions are also supported in PostgreSQL and Oracle, but not in SQL Server or MySQL. The main use AFAIK is to have a higher isolation level (e.g. repeatable read) across multiple statements.

You can start the transaction yourself at the ADO.NET level and provide it to EF Core, [see the docs](https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-external-dbtransactions-relational-databases-only) - this allows you to access any database-specific features for your transaction without EF Core needing to implement specific support for it.

Out of curiosity, what's your specific usecase for the read-only transaction with EF Core?

**Comment by nanasi880** [comment]
I apologize if I am mistaken.
MySQL supports read-only transactions with the following syntax
````
START TRANSACTION READ ONLY;
```


> Out of curiosity, what's your specific usecase for the read-only transaction with EF Core?
Use a read-only transaction, we can easily prevent accidental write operations from being added to the database.
In addition, the database engine may operate more optimally on read-only transactions and may receive performance benefits.

There are other relational databases that require an explicit read-only/read-write choice when initiating a transaction, and some databases have significantly different performance characteristics (e.g. Google Cloud Spanner).

**Comment by roji** [comment]
@nanasi880 see my above comment for achieving this via an external transaction (you can wrap the code from our docs with your own extension method to make it less verbose).

Re introducing something into EF Core itself, we'll discuss this in triage.

**Comment by nanasi880** [comment]
I understand the point of using external transactions. Thanks for the guide.

**Comment by roji** [comment]
Triage decision: since readonly transactions aren't universally supported acrossdatabases, we don't think this belongs in EF Core's relational layer; but providers can add their own overloads of BeginTransaction to support this.

In the meantime, as written above, external transactions can be used to work around this.
