### ISSUE TITLE
How do I convert DbContextOptions<DbContextB> to DbContextOptions<DbContextA> ?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#28012]
For the testing purposes I need to slightly change model configuration, I want to do it by inheriting from actual DbContext and overriding its `OnModelCreating`

If `DbContextB` accepts ` DbContextOptions<DbContextA>` as an input, then I have the following exception:

```
_.AddDbContext<OrderFulfillmentDbContext, TestOrderFulfillmentDbContext>(_ =>
{
    _.UseSqlite(_sqLiteConnection);
});
```

> System.InvalidOperationException : Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[OrderFulfillmentDbContext]' while attempting to activate 'OrderFulfillmentDbContext'.

I have a feeling that it registers options as `DbContextOptions<TestOrderFulfillmentDbContext>` instead of ` DbContextOptions<OrderFulfillmentDbContext>`, but if I switch `TestOrderFulfillmentDbContext` to accept `DbContextOptions<TestOrderFulfillmentDbContext>` , 

**then I need convert `DbContextOptions<TestOrderFulfillmentDbContext>` options to `DbContextOptions<OrderFulfillmentDbContext>`**  to pass it in the `base` constructor. 

How can I do this conversion?

Currently I am using this workaround:
```
_.RemoveAll<DbContextOptions<OrderFulfillmentDbContext>>();
_.RemoveAll<OrderFulfillmentDbContext>();
_.AddSingleton(
    new DbContextOptionsBuilder<OrderFulfillmentDbContext>()
        .UseSqlite(_sqLiteConnection)
        .Options);
_.AddDbContext<OrderFulfillmentDbContext, TestOrderFulfillmentDbContext>();
```

**Comment by AndriySvyryd** [comment]
You should be able to accept `DbContextOptions` in `OrderFulfillmentDbContext` constructor instead of `DbContextOptions<OrderFulfillmentDbContext>`

**Comment by voroninp** [comment]
@AndriySvyryd If I have two unrelated DbContexts in my app, and both of them accept `DbContextOptions`  how would DI distinguish `options` for each of them?

**Comment by AndriySvyryd** [comment]
The last registered one wins

**Comment by voroninp** [comment]
Not good =)

**Comment by AndriySvyryd** [comment]
Ok, then answering your original question:
``` C#
new DbContextOptions<OrderFulfillmentDbContext>(options.Extensions.ToDictionary(e => e.GetType()))
```
