### ISSUE TITLE
Calling user defined function cosmos

### ISSUE THREAD

**Issue by anupdg** [dotnet/efcore#28014]
Hello there,

I have two questions-

- I am trying to call a user-defined function in cosmos DB from entity framework core through DB context
- Also looking for an option to call ARRAY_CONTAINS through entity framework

My data access layer is as GraphQL.net => GraphQL.EntityFramework => EntityFrameworkCore.Cosmos => CosmosDb

Regards

**Comment by smitpatel** [comment]
Duplicate of #15338
