### ISSUE TITLE
Nesting `DbContext` scopes breaks filtering semantics on queries on the outer context

### ISSUE THREAD

**Issue by ehonda** [dotnet/efcore#28025]
# Overview

I noticed some strange behaviour when nesting `DbContext` scopes, breaking semantics of filtering (specifically, `Single` with a predicate, but `Where` is impacted as well) on queries on the outer context, i.e. the entity returned by the filter does not satisfy the predicate used for filtering.

I don't know if what I'm doing is not supposed to be done that way, i.e. nesting `DbContext` scopes, or continuing to use a context after `SaveChanges` has been called (It certainly does not represent the typical lifetime of a `DbContext` instance described in the [documentation](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#the-dbcontext-lifetime)), but I could not find anything in the documentation stating that those use cases are illegal.

The reproduction uses `Microsoft.EntityFrameworkCore.Sqlite 6.0.5` as database provider because it's easy to set up a file based database for testing that way, I haven't investigated whether the issue is provider specific or not.

## Reproduction

A reproduction of the issue in a small demo repository can be found [here](https://github.com/ehonda/EfCoreNestedDbContextScopes). It adds a second inner context (omitted in the summary here) to show that querying works consistently in that scope. The gist of the issue is as follows (`MovieDbContext` and `Movie` classes omitted for brevity, they can be found in the linked demo repository):

```csharp
using var outerContext = new MovieDbContext();

outerContext.Database.EnsureDeleted();
outerContext.Database.EnsureCreated();

outerContext.Movies.Add(new("Action Movie"));
outerContext.SaveChanges();

using (var innerWriteContext = new MovieDbContext())
{
    innerWriteContext.Movies.Single().Title = "Documentary";
    innerWriteContext.SaveChanges();
}

var outerDocumentary = outerContext.Movies.Single(movie => movie.Title == "Documentary");
Console.WriteLine($"documentary title in outer context is {outerDocumentary.Title}");
```

This produces the following output:

```console
$ dotnet run -c Release
documentary title in outer context is Action Movie
```

which shows the aforementioned breakage of query semantics, because we explicitly obtained `outerDocumentary` by filtering for `Movies` that have `Title == "Documentary"`, but the entity returned by the query actually has `Title == "Action Movie"`.

## Provider and version information

EF Core version: `6.0.5`
Database provider: `Microsoft.EntityFrameworkCore.Sqlite 6.0.5`
Target framework: `net6.0`

**Comment by smitpatel** [comment]
See https://docs.microsoft.com/en-us/ef/core/querying/tracking#tracking-queries

Even though different context has changed value and the query ran against the new values in database, when materializing results, since the entity with same PK exists in the context, we just return the same instance which doesn't have same values as database. If you have concurrent operations where database may be updated in different thread (by different db context) then tracked entities in current context will not have same values as database anymore.
