### ISSUE TITLE
Development of the Include Delegate 

### ISSUE THREAD

**Issue by suleymanlimann** [dotnet/efcore#28021]
While use Include, I want only the data associated with other tables to come, but the properties of the table also appear.for example i can include entity property Id value.

1.Include delagate should only display evaluations marked as virtual
2.Write a delegate that can only suggest virtıals.

**Comment by AndriySvyryd** [comment]
Could you show example code of how you would use the requested feature if we added it?

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
