### ISSUE TITLE
Error when try to configure optional owned entity with nested required owned entity

### ISSUE THREAD

**Issue by KyMback** [dotnet/efcore#28030]
Can't understand why I can't configure my data model as following:

```c#
public class A
{
    public Guid Id { get; set; }
    public Owned1? Owned1 { get; set; }
}

public class Owned1
{
    public Owned2 Owned2 { get; set; }
}

public class Owned2
{
    public string Value { get; set; }
}

public class AConfiguration : IEntityTypeConfiguration<A>
{
    public void Configure(EntityTypeBuilder<A> builder)
    {
        builder.OwnsOne(e => e.Owned1, n =>
        {
            n.OwnsOne(e => e.Owned2, n2 =>
            {
                n2.Property(e => e.Value).IsRequired();
            });
            n.Navigation(e => e.Owned2).IsRequired();
        });
    }
}
```

I receive the following error: 
```
 Initializing the storage structure failed!
      System.InvalidOperationException: Entity type 'Owned1' is an optional dependent using table sharing and
 containing other dependents without any required non shared property to identify whether the entity exists.
If all nullable properties contain a null value in database then an object instance won't be created in the q
uery causing nested dependent's values to be lost. Add a required property to create instances with null valu
es for other properties or mark the incoming navigation as required to always create an instance.
```

I defined that Owned2.Value is required + Owned1.Owned2 is required. What's wrong? Please help. Thank you

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by AndriySvyryd** [comment]
You need to add a required non-navigation property on `Owned1` or make `A.Owned1` required

**Comment by Xriuk** [comment]
Is there a reason for a required **non-navigation** property? Why a required navigation property cannot be sufficient? In this case the navigation property is an owned entity so it will generate properties on the entity itself, so why can't those be checked?

**Comment by AndriySvyryd** [comment]
@Xriuk A property will be persisted to the database, so if it's required and there is no value in the database it means that there should be no owned entity instance. A navigation property only exists in the model type, it's not directly persisted.

**Comment by ozdotnet** [comment]
> You need to add a required non-navigation property on `Owned1` or make `A.Owned1` required

How can I make `A.Owned1` required ?

**Comment by AndriySvyryd** [comment]
```C#
            builder.Navigation(e => e.Owned1).IsRequired();
```

**Comment by ozdotnet** [comment]
> builder.Navigation(e => e.Owned1).IsRequired();

If it doesn't complain that there is already `builder.OwnsOne(e => e.Owned1...)` defined, then ok.
