### ISSUE TITLE
[Question] SET IDENTITY_INSERT

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2803]
Hi

I migrate my source using EF7 beta5 to beta6, an early code.

conn.Open()
cmd.CommandText = "SET IDENTITY_INSERT dbo.Vendor ON";
cmd.ExecuteScalar();

//Entity
db.Vendors.Add(vendor);
db.SaveChanges();

cmd.CommandText = "SET IDENTITY_INSERT dbo.Vendor OFF";
cmd.ExecuteScalar();

using beta5 is work fine, after I upgrade to beta6 I encounter an error message, during perform insert entity.

"Cannot insert explicit value for identity column in table 'Vendor' when IDENTITY_INSERT is set to OFF."

I went to SQL Profiler, I can see the it execute "SET IDENTITY_INSERT dbo.Vendor ON"
![image](https://cloud.githubusercontent.com/assets/1622986/9155372/b4de42a4-3e6a-11e5-9013-33def7fa12b8.png)

And when performing the above 3 line in raw sql in smms it work perfect.
It is something wrong when performing the insert identity using EF?
What is the workaround to fix the current issue.

**Comment by rowanmiller** [comment]
@mikary can you take a look at this and see why it doesn't work. Depending on findings we may do something for first release (or not).

**Comment by mikary** [comment]
I attempted to reproduce the behavior you described, and I think the solution is to ensure that you enable and disable the identity insert on the same connection that is being used by the context. Here is an example of the code I used to perform the insert (updated to use the current RC API)

```cs
using System.Data.SqlClient;
using Microsoft.Data.Entity;

namespace IdentityInsert
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }

            using (var context = new MyContext())
            {
                context.Database.OpenConnection();
                context.Database.ExecuteSqlCommand("SET IDENTITY_INSERT dbo.Vendor ON");
                context.Vendors.Add(new Vendor { VendorId = 2 });
                context.SaveChanges();
                context.Database.ExecuteSqlCommand("SET IDENTITY_INSERT dbo.Vendor OFF");
                context.Database.CloseConnection();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Vendor> Vendors { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                new SqlConnectionStringBuilder
                {
                    DataSource = @"(localdb)\MSSQLLocalDB",
                    MultipleActiveResultSets = true,
                    InitialCatalog = "IdentityInsertDb",
                    IntegratedSecurity = true,
                    ConnectTimeout = 30
                }.ConnectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Vendor>()
                .Property(v => v.VendorId)
                .UseSqlServerIdentityColumn();
        }
    }

    public class Vendor
    {
        public int VendorId { get; set; }
    }
}
```

**Comment by jaredcnance** [comment]
I just encountered this issue and while the solution above works, it's unclear to me why. 

> enable and disable the identity insert on the same connection that is being used by the context

It is counterintuitive to me that I have to call `OpenConnection` to ensure the commands run on the same connection.

Based on [this comment](https://github.com/aspnet/EntityFrameworkCore/issues/10125#issuecomment-338259321)

> This involves loading some services from EF's internal D.I. that are scoped to the same lifetime as the context.

And the fact that in both cases the `IRelationalConnection` gets resolved from the container, I would have expected `SaveChanges` and `ExecuteSqlCommand` to share the same connection as long as the `DbContext` instances are resolved from the same scope. Is there any documentation that would illuminate the situation?

**Comment by ajcvickers** [comment]
@jaredcnance `OpenConnection` is just there to ensure the connection is open before executing the command. There is nothing here that relates to ensuring the same connection instance is used--as you say, D.I. ensures that this is the case.

**Comment by mikary** [comment]
@jaredcnance @ajcvickers if I recall correctly, this was a work-around that makes use of the `RelationalConnection` `_openedCount` to make sure both commands run on the same connection.

The `RelationalConnection` class opens a connection on the first call to `OpenConnection`, and increments a counter on each subsequent call. Each call to `CloseConnection` decrements the counter until the number of `OpenConnection` and `CloseConnection` calls are equal, at which point the connection is actually closed.

Both `SaveChanges` and `ExecuteSqlCommand` make calls to `OpenConnection` and `CloseConnection`, but by bookending these calls in an additional pair of `OpenConnection` and `CloseConnection` calls, the connection will remain open the entire time.

**Comment by jaredcnance** [comment]
Yeah, I don't have a minimum reproducible example on hand. But, the solution that fixed this for us was just calling `OpenConnection` and if we removed that call we received the error. If I get extra cycles I'll put together a repro of the issue.

**Comment by mikary** [comment]
@jaredcnance I would say that is reasonable, yes. The framework is sharing the same connection instance through D.I. and the connection should remain open if it was opened before making calls to the API.
