### ISSUE TITLE
Subclassing DbContext Duplicates Migration Changes

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/efcore#28049]
### Include your code

We have a base DbContext in a class library NuGet package, e.g.:

```
public class BaseDbContext : IdentityDbContext
{
    public DbSet<Person> People { get; set; }
}

public class Person 
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

Then add a migration like normal which adds the Person table.

Then we have individual projects which use that class library and need to be able to add new entities to that DbContext which can relate to the existing entities. E.g. in a separate ASP.NET Core project we will have:

```
public class DerivedDbContext : BaseDbContext
{
    public DbSet<Pet> Pets { get; set; }
}

public class Pet
{
    public Person Owner { get; set; }
    public int OwnerId {get; set;}
}
```

But when adding a migration for DerivedDbContext to add the Pets table, it also tries to re-add the Person table (and all the other AspNet* tables from IdentityDbContext) even though they already exist in the database.

Is there a way to make it so any DerivedDbContext can be aware of the existing snapshot of BaseDbContext and only apply changes that differ from it?

### Include provider and version information

EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: Windows 10
IDE: Visual Studio 2022 17.2.0

**Comment by AndriySvyryd** [comment]
You can [exclude shared tables from migrations](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#excluding-from-migrations)

**Comment by DanielStout5** [comment]
Hmm.. the only solution is to mark every single table in the base DbContext as excluded from migrations in every single derived db context? 

That's.. not very convenient. Thanks for answering.
