### ISSUE TITLE
Where are Database initialisers like DropCreateDatabaseAlways?

### ISSUE THREAD

**Issue by XiaoweiJia** [dotnet/efcore#2804]
I cannot find the database initialisers such as DropCreateDatabaseAlways? 
The Database.SetInitializer seems to be removed as well. What's the best way to initialise database?
Thanks

**Comment by rowanmiller** [comment]
Database initializers no longer exist in EF7. You can use `DbContext.Database.EnsureCreated` `EnsureDeleted` etc. in your startup code to achieve the same thing (generally most useful for testing etc.).
