### ISSUE TITLE
Using DbCommand with TransactionScope on an open connection does not create an active transaction.

### ISSUE THREAD

**Issue by mnissl** [dotnet/efcore#28066]
I would like to execute a stored procedure that assumes an active transaction when it creates a transaction save point:

```sql
create procedure dbo.SaveTranTest as
begin
  save tran MySavePoint;
end
```

Furthermore, I would like to keep EF Core's connection open, so the connection is already open before creating the `TransactionScope`:

```cs
using var context = new MyDbContext(options);
context.Database.OpenConnection();
using var scope = new TransactionScope();
context.Database.ExecuteSqlRaw("exec dbo.SaveTranTest");
scope.Complete();
```

While `ExecuteSqlRaw()` works, the same approach using `DbCommand` does not:

```cs
using var context = new MyDbContext(options);
context.Database.OpenConnection();
using var scope = new TransactionScope();
DbCommand cmd = context.Database.GetDbConnection().CreateCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "dbo.SaveTranTest";
cmd.ExecuteNonQuery();
scope.Complete();
```

This raises the exception: _"Cannot issue SAVE TRANSACTION when there is no active transaction."_

I found out that adding a simple `ExecuteSqlRaw("select 1")` makes the same code work:

```cs
using var context = new MyDbContext(options);
context.Database.OpenConnection();
using var scope = new TransactionScope();
context.Database.ExecuteSqlRaw("select 1"); // in terms of transactions a no-op
DbCommand cmd = context.Database.GetDbConnection().CreateCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "dbo.SaveTranTest";
cmd.ExecuteNonQuery();
scope.Complete();
```

Is this a bug in EF Core and/or `DbCommand` or what am I doing wrong?

P.S.: I'm on EF Core 6.0.5 using Microsoft.EntityFrameworkCore.SqlServer.

**Comment by AndriySvyryd** [comment]
You need to create the transaction scope before opening the connection or call `context.Database.EnlistTransaction(scope)`

**Comment by AndriySvyryd** [comment]
Consider using `context.Database.BeginTransaction()` instead.

**Comment by mnissl** [comment]
> You need to create the transaction scope before opening the connection or call `context.Database.EnlistTransaction(scope)`

As I wrote in my original post, the connection is already open before the transaction is about the start.

Then again, I don't have access to the transaction scope where I call the DbCommand.

**Comment by mnissl** [comment]
> Consider using `context.Database.BeginTransaction()` instead.

As I wrote before, the transaction is started at another place.

**Comment by mnissl** [comment]
Why is this issue closed although no true solution was provided?

In fact, I pointed out a strange behaviour: why does it matter whether the connection is already open?

Just closing this issue without explaining or examining this circumstance is non-constructive.

**Comment by roji** [comment]
> In fact, I pointed out a strange behaviour: why does it matter whether the connection is already open?

This is how System.Data and TransactionScope works. If a TransactionScope is created before the connection is opened, then the connection automatically enlists into it. But if the connection is opened first and the TransactionScope is created only afterwards, than you need an explicit Enlist call. It works like this at the System.Data level and has nothing really to do with EF Core.

**Comment by AndriySvyryd** [comment]
`DbTransaction` and `Transaction` are two completely separate mechanisms in ADO.NET. If you don't control which one is used then you'd need to have code that handles both.

**Comment by mnissl** [comment]
> `DbTransaction` and `Transaction` are two completely separate mechanisms in ADO.NET. If you don't control which one is used then you'd need to have code that handles both.

Thanks for point the difference out. I wasn't aware of the fact that two mechanisms exist.
