### ISSUE TITLE
ReplaceService on AddDbContext doesn't work at design time, but it does in OnConfiguring

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/efcore#28060]
This **doesn't** work - the custom migrations assembly is not used at design time (e.g. when adding a migration), even though in the debugger at design time I can see it was configured:

```
services.AddDbContext<MyDbContext>(bld =>
{
    bld.ReplaceService<IMigrationsAssembly, MyMigrationsAssembly>();
    bld.UseSqlServer(Config.GetConnectionString("DefaultConnection"));
});
```

Whereas this **does** work at design time, inside MyDbContext:

```
protected override void OnConfiguring(DbContextOptionsBuilder bld)
{
    bld.ReplaceService<IMigrationsAssembly, MyMigrationsAssembly>();
}
```

Is this intentional? Is there another way to achieve this without having to add OnConfiguring?

EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: Windows 10
IDE: Visual Studio 2022 17.2.0

**Comment by AndriySvyryd** [comment]
What version of EF Core are you using? Can you share a small repro project?

**Comment by DanielStout5** [comment]
Sorry, I meant to attach the version info. This is EF Core 6.0.4.

EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: Windows 10
IDE: Visual Studio 2022 17.2.0

**Comment by ajcvickers** [comment]
@DanielStout5 As @AndriySvyryd said, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by DanielStout5** [comment]
Hmm.. When I created a runnable example it did work the same way for both calls.

It might be because in my previous example the code calling AddDbContext was actually in a separate assembly. If that's the case it's probably not relevant to most people so I'll go ahead and close this issue.
