### ISSUE TITLE
Scaffolding issue with Beta7

### ISSUE THREAD

**Issue by NoralK** [dotnet/efcore#2807]
Is the Scaffolding repository still the place to post issues EF7 Scaffolding?  I open a ticket almost a week ago and no one has commented - https://github.com/aspnet/Scaffolding/issues/106.

Thank you

**Comment by rowanmiller** [comment]
@NoralK yes that is the correct place

**Comment by bricelam** [comment]
Word is that that repository is "on hold"...

**Comment by NoralK** [comment]
Thank you for the update.  It is understandable since MVC is constant flux right now, but I hope that its status is resolved soon because it is a useful productivity tool that we take for granted - I even liked the return to the command line, it brings back memories of CP/M and MS/DOS v3.3 never PC-DOS :)
