### ISSUE TITLE
Cosmos: Translate regex matching

### ISSUE THREAD

**Issue by sekarcse** [dotnet/efcore#28078]
How to use RegexMatch in EF Core Cosmos C#

I want to apply the below in Linq. Here code is in-case sensitive 
 
Cosmos Query
SELECT * FROM c
WHERE RegexMatch (c.Code, "ZWw","i")

**Comment by roji** [comment]
This isn't currently supported, but you can use [raw SQL queries](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) to call the function in SQL yourself.

[Cosmos docs for the function](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-regexmatch)

**Comment by sekarcse** [comment]
Thanks @roji for the quick reply

**Comment by Marusyk** [comment]
@roji @AndriySvyryd  What is your point of view for implementing this feature?

smth like this?
```
dataSet.Where(x => EF.Functions.RegexMatch(x, "Zxw", "i"));
```

**Comment by roji** [comment]
@Marusyk if possible, translatnig built-in .NET functions is preferred. For example, the PG provider supports regex by translating `Regex.IsMatch(stringValue, "^A+")` ([see docs](https://www.npgsql.org/efcore/mapping/translations.html#string-functions)).

**Comment by AndriySvyryd** [comment]
Adding to what @roji said you can also translate some of the options, but throw for the ones not supported by Cosmos.

<table>
<tr>
	<td>RegexOptions
	<td>Modifier
<tr>
	<td>Multiline
	<td>m
<tr>
	<td>Singleline
	<td>s
<tr>
	<td>IgnoreCase
	<td>i
<tr>
	<td>IgnorePatternWhitespace
	<td>x
</table>

**Comment by roji** [comment]
Note: we also already translate Regex.IsMatch in SQLite and have tests for it in NorthwindFunctionsQueryTestBase.
