### ISSUE TITLE
Environment-specific Data Seeding

### ISSUE THREAD

**Issue by yarus** [dotnet/efcore#28082]
Hi, 

I am trying to find a better approach for environment-specific data seeding. Please advise.

Scenario is the following:
We need to configure webhooks for the Partner. The main attribute of a webhook is TargetUrl which is different for each environment.
Local - https://www.test1.com
Staging - https://www.test2.com
Production - https://www.test3.com

This data should be entered 1 time and lives there. We don't want to lose it in case of data from DB get lost or we need to rebuild environment so we want to add this as a Migration or as a script which has to be version controlled.

What options do we have to achieve that?

FluentMigrator use Tags Attribute approach to achieve this.

`    [Tags("Development", "Staging")]
    [Migration(201702211740)]
    public class Development_And_Staging_Key_Change : Migration
`

So this migration going to be applied for Development and Staging while we ca n create another one specifically for Production.

How can we achieve the same using EF Core?

**Comment by AndriySvyryd** [comment]
You could manually edit the migrations and add conditional logic based on environment

**Comment by yarus** [comment]
> You could manually edit the migrations and add conditional logic based on environment

Can you provide any specific example? You mean something like

```
var env = Environment.GetEnvironmentVariable("Environment");
var partnerId = env == "Development" ? "Value1" : "Value2";

```
?

**Comment by AndriySvyryd** [comment]
> You mean something like

Yes, something like that
