### ISSUE TITLE
Exclude LazyLoader when use System.Text.Json

### ISSUE THREAD

**Issue by EfimenkoAndrew** [dotnet/efcore#28083]
Hi, I am using **System.Text.Json** and get trouble like in this issue https://github.com/dotnet/efcore/issues/12772
But I do not have it in [Newtonsoft](https://www.newtonsoft.com/). 

I think that **System.Text.Json** does not work with [IgnoreDataMember] like it was fixed in this PR https://github.com/dotnet/efcore/pull/13340/files 
please add  [JsonIgnore] to ignore lazy loader

**Comment by EfimenkoAndrew** [comment]
please review https://github.com/dotnet/efcore/pull/28084 #28084

**Comment by EfimenkoAndrew** [comment]
@ajcvickers hi, I would like to sign the contributing agreement one more time. now I no longer work for Sitecore so I want to remove that part from my agreements
please tell me if it is possible to reset my previous sign and i will be glad to sign everything again

**Comment by EfimenkoAndrew** [comment]
I wanted to find myself in contributors :D but for some reason i am not there(

**Comment by ajcvickers** [comment]
@Pilchie What is the process for updating a CLA?

> I wanted to find myself in contributors :D but for some reason i am not there(

If you mean in the biweekly updates, then then the cutoff is the end of Wednesday, so you will be in the next one.
