### ISSUE TITLE
Entity framework .net6 generating wrong queries with old column names that don't exist anymore

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#28107]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entity-framework-net6-generating-wrong-/10045132)._

---
\[severity:I’m unable to use this version\]  
I have an EF data access in my DB data.  
I have updated the classes in C# and also the DB, rebuilt the solution and the code still generating queries with OLD properties. I looked for that column name in the solution and that text doesn’t exist anywhere. I have restarted VS and Cleaned and rebuilt everything but still generating quiries with OLD property names.  
I don’t know if there is something cached that doesn’t get rebuilt, but this is making me waste a huge amount of time.

![image.png](https://aka.ms/dc/image?name=Bb86a6ad76f6547b4b89fb5f69ab9ebd9637884269663966503_20220518-092926-image.png&tid=b86a6ad76f6547b4b89fb5f69ab9ebd9637884269663966503)

![image.png](https://aka.ms/dc/image?name=B01c60159dc344b06a8a378fa9aba1099637884270622875651_20220518-093102-image.png&tid=01c60159dc344b06a8a378fa9aba1099637884270622875651)

![image.png](https://aka.ms/dc/image?name=Bfb997e12747b4bf587161ee7f0aa3ab5637884531302389068_20220518-164529-image.png&tid=fb997e12747b4bf587161ee7f0aa3ab5637884531302389068)

![image.png](https://aka.ms/dc/image?name=Ba24e7fc4432e49c988418b08164df914637884328239081839_20220518-110703-image.png&tid=a24e7fc4432e49c988418b08164df914637884328239081839)

![image.png](https://aka.ms/dc/image?name=B568a086c94fc4f489754b80a2c59517f637884328992007307_20220518-110818-image.png&tid=568a086c94fc4f489754b80a2c59517f637884328992007307)

---
#### Roberto Mencia Franco on 5/18/2022, 07:42 AM: 

(private comment, text removed)
#### Feedback Bot on 5/18/2022, 09:31 AM: 

(private comment, text removed)
#### Roberto Mencia Franco on 5/19/2022, 00:30 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
