### ISSUE TITLE
SQLite Query: Consider translating Sum to TOTAL

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#28101]
Every now and then I obsess over this, so I'm filing an issue to remind myself why it's not actually worth doing.

Today, we translate Sum into SQL like this: `COALESCE(SUM(X), 0)`

This is to compensate for the fact that SUM returns NULL for the empty set.

SQLite has a built-in function TOTAL that is *almost* exactly like SUM except that it returns 0 for the empty set.

So, we should just translate Sum to SQL like this, right? `TOTAL(X)`

No, Brice! It's not that cut and dry. TOTAL has another difference. It always returns REAL--even if all the inputs are INTEGER. That means the result might be lossy. And, even if it's not lossy, we should probably generate a CAST for it which would make the SQL even longer than the current COALESCE call.

So yes, we *could* do it for double and float values, but the value-add is low and not worth the extra code.

**Comment by roji** [comment]
We should have more of these issues
