### ISSUE TITLE
dotnet ef migrations bundle build fails when there is more than one project file

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#28113]
When I am trying to bundle my migrations the directory has a .csproj file and a .obproj file (Obfuscation file by a 3rd party obfuscation tool) I am running the following command 

```dotnet ef migrations bundle -o eff.exe --configuration Bundle --self-contained --project "MyProject.Web.csproj" -f```

and I get 

```dotnet : Specify which project file to use because this 'C:\SourceControl\\Github\MyProject\src\MyProject.Web' contains more than one project file.```

A screenshot of the file
![image](https://user-images.githubusercontent.com/3295086/170654889-99df11d7-9636-4c9e-ad94-0c93e196d7bb.png)

When I run ```dotnet build "MyProject.Web.csproj"``` it builds successfully

### Include provider and version information

EF Core version: 6.0.5
Database provider: Pomelo.EntityFrameworkCore.MySql v 6.0.1
Target framework: .NET 6.0
Operating system: Windows 10
IDE: VS2022 v17.0.0
Entity Framework Core .NET Command-line Tools: 6.0.5

**Comment by ajcvickers** [comment]
A single project file is a limitation of the tool, and indeed other tools that do builds. This is not something we plan to change.

**Comment by pantonis** [comment]
@ajcvickers What do you mean? I specify which project to build and it still fails..

**Comment by MilanRaval** [comment]
Any update on this, I am getting same issue 

![image](https://github.com/dotnet/efcore/assets/1009560/4cdebc8a-639e-4b27-964f-c5e41893254d)

**Comment by ajcvickers** [comment]
@MilanRaval The EF Core tools only support a single project file.
