### ISSUE TITLE
No-Relational Provider

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#28114]
I am trying to write a non realtion provider for EF Core 6 loking at Cosmos provider implementation. I am at poit to build the shaper, for EntityShaperExpression it was quite simply, InjectEntityMaterializers do almost all the work and all works fine but about Includes, Cosmos provider support only the automatic include for owned Entities so i have not an example on wath i have to do. I already built the IncludeExpression but I need informations on how process it before compile it.
Can u please suggest something on the approch i can have to try to achive the information i need?
I know it is a so general question, but seems a very complex point, so any information(also conceptual), any suggestion, any thing can help me is very very appreciate

**Comment by ajcvickers** [comment]
@GLuca74 Processing included entities in the shaper is perhaps one of the hardest parts of the EF code to understand and work with. We discussed this as a team and maybe if you can point to your existing code or show what you are currently doing, then we can try to provide some pointers.

**Comment by GLuca74** [comment]
Hello @ajcvickers  and thanks for your Replay

Actually I would have been useful some suggestions at High-Level on how to build the shaper starting from the EntityShaperExpression generated by InjectEntityMaterializers
For example, something like: Generate the two EntityShaperBody and do [Something at High-Level to do]
This is because now my code only handles the EntityShaperExpression case and it is similar to the Cosmos code:
In Cosmos ShapedQueryCompilingExpressionVisitor Implementation

```
            var jObjectParameter = Expression.Parameter(typeof(JObject), "jObject");

            var shaperBody = shapedQueryExpression.ShaperExpression;
            shaperBody = new JObjectInjectingExpressionVisitor().Visit(shaperBody);
            shaperBody = InjectEntityMaterializers(shaperBody);

```

In my ShapedQueryCompilingExpressionVisitor Implemementation became
```
            var dataReaderParameter = Expression.Parameter(typeof(NodeReader), "dataReader");
            var shaperBody = shapedQueryExpression.ShaperExpression;

            shaperBody = new NodeReaderInjectingExpressionVisitor().Visit(shaperBody);
            shaperBody = InjectEntityMaterializers(shaperBody);

```
Where NodeReader is the Type of the reader of dati sottostanti
After I build the lambda on Top of ShaperBody and pass it compiled to the new Expression of my QueryingEnumerable Implementation (that talk to my dataSource)

Exactly like Cosmos does:


```
                        return Expression.New(
typeof(QueryingEnumerable<>).MakeGenericType(shapedQueryExpression.QueryExpression.Type).GetConstructors()[0],
                                Expression.Convert(
                                    QueryCompilationContext.QueryContextParameter,
                                    typeof([MyCustom]QueryContext)),
                                Expression.Constant(selectExpression.Node),
                                Expression.Constant(shaperLambda.Compile()),
                                Expression.Constant(
                                                    QueryCompilationContext.QueryTrackingBehavior == Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTrackingWithIdentityResolution)
                                );

```



When there is an Explicit Include, I already built the IncludeExpression which contains the two EntityShaperExpression for the two involved entities, but I have no idea how to combine them to obtain a single Shaper.

If it is not possible to provide a High-Level suggestion on how to combine them, I will try to understand what Cosmos does for the Owned Includes and see if it is useful for my purpose.

If I can't, I'll come back with my code attempt
