### ISSUE TITLE
'OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.

### ISSUE THREAD

**Issue by jamel056** [dotnet/efcore#28123]
hello everyone
I am using .net 5 project with graphql
I am using in my dbcontext onconfigure method to use logger in dubug mode 

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
#if DEBUG
            optionsBuilder.UseLoggerFactory(DbLoggerFactory);
#endif
        }

and in my startup I registered the dbcontext by using PooledDbContextFactory

 services.AddPooledDbContextFactory<AppDbContext>(options =>
                options.UseSqlServer(configuration.GetConnectionString("IdentityConnectionString")));

when i am adding any entity to the dbset of my dbcontext and using 
add-migration the error message shows like:
'OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.

how can I fix this problem?               

### Include provider and version information

EF Core version:
Microsoft.EntityFrameworkCore.SqlServer
 .NET 5.0
Operating system:
Visual Studio 2022 Version 17.1.6

**Comment by roji** [comment]
This is by-design; you need to pass *all* the context options to your DbContextFactory, rather than configuring them in OnConfiguring, as follows:

```c#
services.AddPooledDbContextFactory(options => options
    .UseSqlServer(configuration.GetConnectionString("IdentityConnectionString"))
    .UseLoggerFactory(DbLoggerFactory));
```

See the [context pooling docs](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling) for more info.

**Comment by jamel056** [comment]
thank you @roji It Works

**Comment by RobK410** [comment]
Yet, you cannot migrate without OnConfiguring to define the DbContextOptions, when your Entities and Context are in a separate library; which is pretty common if you have multiple programs/services using the same database.
