### ISSUE TITLE
TableExpressionBase implements IMutableAnnotatable making it mutable expression

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#28120]
![image](https://user-images.githubusercontent.com/1528107/170797310-e4f2235e-49f1-43f0-a800-216e5d3e1a3f.png)

**Comment by ajcvickers** [comment]
Note from triage: stop using IMutableAnnotatable and implement a simple annotation mechanism that returns a new expression rather than mutating the existing expression.

**Comment by smitpatel** [comment]
We need to do this in this release. Earlier the better as it would be breaking change.
