### ISSUE TITLE
Command Timeout doesn't set  sqlite3_busy_timeout

### ISSUE THREAD

**Issue by Belphemur** [dotnet/efcore#28135]
## File a bug
When setting the CommandTiemout on the SQLite option I'm expecting that this will also set the `busy_timeout` for all the underlying pooled sqlite connection.

I discovered that it isn't the case and I need to manually set a SQL request to be ran just after the connection is open everytime.

### Include your code

```C#
   protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite($"Data Source={DbPath};Cache=Shared", builder => builder.CommandTimeout(30));
    }
```

### Work around
```csharp
 Database.GetDbConnection().StateChange += (_, args) =>
        {
            if (args.CurrentState != ConnectionState.Open)
            {
                return;
            }

            Database.ExecuteSqlRaw("PRAGMA busy_timeout = 5000;");
        };
```
It's not really elegant to have to set that up in the DBContext  constructor.

### Suggested solution
Either propagte the CommandTimeout as `busy_timeout` or provide another setting to set it up and have the lib handle it.

### Reason
I'm using [Litestream](https://litestream.io/) to backup my sqlite database throught streaming wal. The issue is, every now and then, it locks the database to finish the snapshot.  They [suggest setting the `busy_timeout` to `5000`](https://litestream.io/tips/#busy-timeout) to avoid having locking issue as it tell sqlite to wait longer before giving up getting a lock.

### Include version information

Microsoft.Data.Sqlite version: 6.0.5.0
Target framework: .NET 6.0
Operating system: Linux

**Comment by bricelam** [comment]
Oh, one more aspect of this is statement batching. One command may have multiple SQL statements in it. `PRAGMA busy_timeout` would mean that each statement within that command gets the full timeout value. Instead, we keep track of the timeout for the entire batch to better honor the ADO.NET API semantics.

**Comment by Belphemur** [comment]
@bricelam I see, that makes a lot of sense, so technically using busy_timeout would be a "downgrade" of the feature compared to the setting `CommandTimeout`.

Thank you for this great explanation, I agree that being able to set `busy_timeout` doesn't make sense in the case of the current implement of `CommandTimeout`.

Maybe [Locking, retries, and timeouts](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/database-errors#locking-retries-and-timeouts) page could have a section with your explanation why it was decided to not rely on `busy_timeout`. 

I'm closing the issue.
