### ISSUE TITLE
Include filter information is lost after Select method

### ISSUE THREAD

**Issue by wzxinchen** [dotnet/efcore#28141]
## Ask a question

Remember:

* Please make your question as clear and specific as possible.
* Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

### Include your code

https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include

```C#
    var q= dbContext.Set<ProjectDoc>().Include(x => x.BuildingDocs.Where(b => b.Id == "123"));
            var q1 = q.Select(x => new
            {
                x.Id
            }).AsSingleQuery();
```
![image](https://user-images.githubusercontent.com/5409541/171312704-b7185830-103d-41c8-8d7f-6101a27ec170.png)

Include filter information is lost after Select method

Am I missing some setting?
### Include stack traces

No need

### Include verbose output

No need

### Include provider and version information

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .Net 6.0
Operating system:
IDE: Visual Studio 2022 17.2.2)

**Comment by wzxinchen** [comment]
test again

```
  var q= dbContext.Set<ProjectDoc>().AsSingleQuery().Include(x => x.BuildingDocs.Where(b => b.Id == "123"));
            var q1 = q.Select(x => new
            {
                x.Id
            });
```
still lost, and it seems that the include information is also lost

**Comment by ajcvickers** [comment]
@wzxinchen `Include` is used to load additional related entities specified by navigations on entities that are loaded. Once there is a projection in the query (with `Select`), it means that full entities are no longer being loaded, and hence the Include is no longer valid.

**Comment by wzxinchen** [comment]
@ajcvickers Theoretically, it is true, but there should be many such application scenarios. I think at least if I select a navigation attribute, its filtering and sorting information should not be lost.

Because such a mechanism requires me to write additional mechanisms to deal with this situation. You may think that this should be the case in terms of design, but we always need to implement it in the face of business.

For example, the solution I can think of is to call tolist to find out the data and execute the select logic in memory, but this is not a perfect solution.

**Comment by wzxinchen** [comment]
@ajcvickers   And for the sorting information, in fact, I have no way to reorder it.
