### ISSUE TITLE
Defining partial index discards foreign key index

### ISSUE THREAD

**Issue by aromaa** [dotnet/efcore#28144]
## File a bug
When defining a partial index with composite key of (A,B) the default index for foreign key A is discarded. This would make sense when using normal index as queries can still be optimized for key A but not in the case when partial indexes are used.

### Repro

```C#
public class TestContext : DbContext
{
	public DbSet<UserOwnedData> Data { get; init; }
    
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<UserOwnedData>(e =>
		{
			e.HasOne<User>()
				.WithMany()
				.HasForeignKey(d => d.UserOneId);
			
			e.HasOne<User>()
				.WithMany()
				.HasForeignKey(d => d.UserTwoId)
				.OnDelete(DeleteBehavior.SetNull);
            
			e.HasIndex(d => new { d.UserOneId, d.UserTwoId })
				.HasFilter("user_two_id IS NULL");
		});
	}
}

public class User
{
	public int Id { get; init; }
}

public class UserOwnedData
{
	public int Id { get; init; }
	public int UserOneId { get; set; }
	public int? UserTwoId { get; set; }
}
```

### Current behavior: 
```sql
CREATE INDEX ix_data_user_one_id_user_two_id ON data (user_one_id, user_two_id) WHERE user_two_id IS NULL;
CREATE INDEX ix_data_user_two_id ON data (user_two_id);
```

### Expected behavior: 
```sql
CREATE INDEX ix_data_user_one_id ON data (user_one_id);
CREATE INDEX ix_data_user_one_id_user_two_id ON data (user_one_id, user_two_id) WHERE user_two_id IS NULL;
CREATE INDEX ix_data_user_two_id ON data (user_two_id);
```

### Workaround
You can workaround this by explicitly specifying the index with `e.HasIndex(d => d.UserOneId)`

### Include provider and version information

EF Core version: 7.0.0-preview.4.22229.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7

**Comment by ajcvickers** [comment]
Duplicate of #24237.

**Comment by aromaa** [comment]
Was unable to find the issue when trying to search for related issue, oh well, closing.
