### ISSUE TITLE
PM> Install-Package EntityFramework.SqlServer -Pre

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet/efcore#2815]
Hello,

I have just run PM> Install-Package EntityFramework.SqlServer -Pre
but it doesn't work... I am using a windows console app and I am targeting .NET4.6!

PM> Install-Package EntityFramework.SqlServer -Pre
Install-Package : Unable to find package 'EntityFramework.SqlServer'
At line:1 char:1
- Install-Package EntityFramework.SqlServer -Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by bricelam** [comment]
What if you add `-Source nuget.org` to the command?

**Comment by MaherJendoubi** [comment]
It's the same.

**Comment by MaherJendoubi** [comment]
I tested now 3 times and it works! But yesterday, all the night it wasn't working even with -Source nuget.org! Thank you @bricelam :-)

**Comment by bricelam** [comment]
Huh, must have had an outage..
