### ISSUE TITLE
Add EF.Parameter to force parameterization in query

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28151]
In F#, closure parameters are integrated into the query expression tree as constant nodes - see https://github.com/dotnet/fsharp/issues/12841 for the full details. This means that by default, all EF queries generate SQL with constants rather than parameters.

A workaround is to use a F# ref, which gets properly parameterized by EF Core:

```f#
let i = ref 8
db.Events.Where(fun x -> x.Data = i.Value).ToList();
```

However, while this works well with local variables, it's problematic for use with function parameters, since the parameter needs to be typed as `Ref<T>` (it isn't great to require people to change method signatures just so that an EF query inside get properly parameterized). Note that the variable name is also lost, so the SQL contains `@__Value_0`.

We could introduced an EF.Param() mechanism, which is identified by EF Core and forces parameterization. The same mechanism could be used in C# to force parameterization for better perf when two queries use different constants, without needing to extract a variable:

```c#
var query1 = await ctx.Blogs.Where(b => b.Name == EF.Param("foo")).ToListAsync();
...
var query2 = await ctx.Blogs.Where(b => b.Name == EF.Param("bar")).ToListAsync();
```

EF.Param could optionally also accept the SQL parameter name, to produce more readable SQL queries.

/cc @dsyme @NinoFloris

**Comment by roji** [comment]
Additional advantage of this: for users building an expression tree dynamically, it would make it considerably easier to integrate a value as a parameter into the expression tree.

**Comment by smitpatel** [comment]
Restriction on the API would be that the argument to the method must be a constant value. (this also works in dynamic tree building scenario where user generally creates ConstantExpression).

We would also evaluate anything which composes over as long as it is evaluate-able using normal rules of maximum possible evaluation. 

e.g. `EF.Param("foo").Length` would get fully evaluated and generated parameter of value `3` in expression tree.

**Comment by pinkfloydx33** [comment]
This would be really useful for us. We have a bunch of query building methods that dynamically craft an expression tree. We were ending up with constant values plugged directly into the query because we were using `Expression.Constant`. As a workaround I use the following helper method to force a closure over the value(s) passed into our builders:

```csharp 
public static Expression CloseOver<T>(T constant)
   => ((Expression<Func<T>>)(() => constant)).Body;
```

Which we then use in lieu of `Expression.Constant` when dealing with various input values. So far this seems to work w/r/t parametrization, however we end up with parameters all named `constant_{n}` (the name of the parameter/display class field) which is a bit unfortunate. I'm also not sure if it's guaranteed to work or not and it feels a tad bit hacky. 

It'd be great if we had some built-in method we could `Expression.Call` instead that would properly recognize this and turn the inputs into parameters named accordingly.

**Comment by roji** [comment]
@pinkfloydx33 your workaround above is fine and guaranteed to work - it just reproduces the normal non-dynamic thing that happens when a closure variable is captured. But it's true that the parameter name isn't pretty.

**Comment by roji** [comment]
Thinink about https://github.com/dotnet/efcore/issues/28151#issuecomment-1146368308:

> We would also evaluate anything which composes over as long as it is evaluate-able using normal rules of maximum possible evaluation.
>
> e.g. EF.Param("foo").Length would get fully evaluated and generated parameter of value 3 in expression tree

Evaluating operators composed over EF.Param seems unnecessary, since they'd get evaluated anyway with it; in other words, `"foo".Length` already gets fully parameterized, so there's no reason to use EF.Param() here in the first place.

There might conceivably also be cases where a user may want to block evaluation at a higher level, i.e. ensuring that some part of the tree is sent as a parameter, and **not** subsumed into a larger parameter (as contrived as it sounds, this may be helpful to optimize certain SQL queries).

(plus it's a bit more difficult implementation-wise to allow EF.Param() to be evaluated within a larger subtree)

**Comment by kjeske** [comment]
I really like it and thank you for it. But do we need to wait till November 2024 to have it in non-prerelease version?

**Comment by roji** [comment]
@kjeske yes.
