### ISSUE TITLE
Query: Provide a way to indicate that part of a query should translate to server or throw

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#28155]
Rather than client eval when in top-level projection

**Comment by roji** [comment]
Aggregate functions are a motivation for this: https://github.com/dotnet/efcore/issues/28409#issuecomment-1179695122

**Comment by stevendarby** [comment]
Is this distinct from https://github.com/dotnet/efcore/issues/24509?

**Comment by smitpatel** [comment]
#28155 supersedes #24509

**Comment by ajcvickers** [comment]
Duplicate of #24509.
