### ISSUE TITLE
How to perform normal db operations with one SQLite provider and perform migrations with another SQLite provider

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#28168]
We are using SQLite, with a provider other than ms. This provider has good performance, but does not support drop column. While the ms SQLite provider supports drop column. I tried to switch to ms SQLite provider to perform migrations, but the drop column still failed so I think the other provider is still being used. Is there a way to run the ms SQLite provider for migrations only?

**Comment by ajcvickers** [comment]
@dgxhubbard This isn't supported. You may be able to hack it to work with an [IDesignTimeDbContextFactory](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli), but I suspect it won't be trivial, and it will certainly be ugly.

**Comment by dgxhubbard** [comment]
@ajcvickers Oh My! I suspected as much and went the create new table route in sql.
