### ISSUE TITLE
EF Core connection performance with Managed Identity is slow

### ISSUE THREAD

**Issue by yarus** [dotnet/efcore#28161]
Hello,

We are using EF Core 6 with Azure functions (isolated) and facing performance issues. Some of our EF Core requests take 4-6 seconds which are much higher than our expected SLA.

Diving into the logs we figured out that major performance hit is happening while EF Core initialize DbContext and specifically obtaining access token. This sometimes take up to 4 seconds. We tried to changed connection string to use shared username and password and we no longer see such issue. We want to use Managed Identity since it is more secured approach but such a huge performance hit is unacceptable.

Could you please advice if there are known workarounds to handle this performance issue?

We also tried to use Interceptor to manually set Access Token - we saw such approaches on stackoverflow but that didn't really solved the issue. Only when we use connection string with username and password we don't see such a performance hit.

### Include provider and version information

EF Core version: 6.0.5
atabase provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by roji** [comment]
This wouldn't something specific to EF Core, but rather a SqlClient/SQL Azure issue; I'd advise asking on those forums rather than here.

One general piece of advice though. It sounds like you may be fetching an access token with every single connection (e.g. in the interceptor); if that's the case, then it's certainly not a good idea. It's generally recommended to re-fetch access tokens periodically, some time before they are set to expire, and to set them in some global place which the interceptor would access. Even if the actual fetching still takes 4 seconds (which certainly sounds abnormal), doing things this way would make that unimportant, since the token would no longer be fetched constantly with every connection.

**Comment by ErikEJ** [comment]
What does your connection string look like?

**Comment by yarus** [comment]
Managed Identity version of Connection string generated like this:

```
        var sqlConnBuilder = new SqlConnectionStringBuilder
        {
            DataSource = sqlServer!.FullyQualifiedDomainName,
            InitialCatalog = database.Name,
            PersistSecurityInfo = false,
            Authentication = SqlAuthenticationMethod.ActiveDirectoryDefault,
            MultipleActiveResultSets = false,
            Encrypt = true,
            TrustServerCertificate = false,
            ConnectTimeout = 30
        };
```

Than we tried approach with Interceptor and token assignment (we are caching token, so no issue with this):

`Data Source=<dbServer>.database.windows.net;Initial Catalog=<dbName>;Persist Security Info=False;Multiple Active Result Sets=False;Connect Timeout=30;Encrypt=True;Trust Server Certificate=False`

And lastly we tried the same connection string without Interceptor but with user name and password which showed the best performance.

**Comment by roji** [comment]
> Some of our EF Core requests take 4-6 seconds which are much higher than our expected SLA.
> [...]
> we are caching token, so no issue with this

My advice would be to altogether remove the token fetching itself from interception; perform the fetching in the background with a timer, where the actual fetching doesn't matter at all. This would remove any slowdown from actual EF queries.

Note that it's still abnormal to have to wait 4 seconds for a token refresh - this is something you may want to continue investigating with SqlClient and/or SQL Azure. However, if that time was reduced to 200ms, this isn't something you generally want in your actual query time when you can move it out to the background.

**Comment by ErikEJ** [comment]
That does not look like the appropiate connection string for Managed Identity. You should use [this](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#using-active-directory-managed-identity-authentication)

**Comment by yarus** [comment]
Should use specifically Authentication=Active Directory Managed Identity; to enforce managed identity or 
Authentication=Active Directory Default? Is there any other recommended settings while working with Azure Functions?

**Comment by ajcvickers** [comment]
@yarus This is a question for https://github.com/dotnet/SqlClient and/or https://github.com/Azure/Azure-Functions
