### ISSUE TITLE
Spatial: Translate EnvelopeCombiner.CombineAsGeometry aggregate function

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28184]
@airbreather graciously added EnvelopeCombiner.Combine for us in https://github.com/NetTopologySuite/NetTopologySuite/issues/610, so once NTS is next released we can add an aggregate method translation for that as a follow-up to #13278:

.NET                            | SQL Server                          | SpatiaLite                             | PostGIS
------------------------------- | ----------------------------------- | -------------------------------------- | -------
EnvelopeCombiner.CombineAsGeometry(geoms) | EnvelopeAggregate(@​geoms)   | Extent(@​geoms)                 | ST_Extent(@​geoms)

**Comment by douglasg14b** [comment]
Are the code example of how this works? For instance using `EnvelopeCombiner.CombineAsGeometry` ?
