### ISSUE TITLE
Better support for raw sql

### ISSUE THREAD

**Issue by wsq003** [dotnet/efcore#28182]
```C#

using var trans = await db.Database.BeginTransactionAsync();
int row = await db.Database.ExecuteSqlRawAsync(
    "update t_position set total = total + {0}, frozen = frozen - {0} where uid={1} and symbol={2} ", 
    val, uid, symbol);
if (row == 0)
{
    await db.Database.ExecuteSqlRawAsync(
        $"insert into t_posistion (uid, symbol, total, frozen) values ({uid}, {symbol}, {val}, 0)");
}
await db.Database.ExecuteSqlRawAsync(
        $"insert into t_order (uid, symbol, price, quantity) values ({uid}, {symbol}, {val}, 1)");
await trans.CommitAsync();
```

We need the atomic feature of `update ... where ...` to ensure financial level correction.
Such kind of logic is very common in business, and can not be implemented by LINQ. 

So, raw SQL is necessary and important. Current support for raw SQL is not enough in convenient and safety.

`Dapper` in C# and `squirrel + gorm` in go-lang has much better support for raw SQL.
Using two different ORM in one application is uncomfortable.

Here is my suggestion 1:
```C#
using var trans = await db.Database.BeginTransactionAsync();
var conditions = new Dictionary<string, object>();
conditions["uid"] = 12345;
conditions["symbol"] = "MSFT";
var updates = new Dictionary<string, object>();
updates["total"] = new EFExpr("total + {}", 5);
updates["frozen"] = 0;
var row = await db.Database.Table("t_position").Where(conditions).Update(updates);
if (row == 0)
{
    await db.Database.Table("t_position").Insert(
        new TPosition() { Uid = 12345, Symbol = "MSFT", Total = 5, Frozen = 0 });
}
await db.Database.Table("t_order").Insert(
        new TOrder() { Uid = 12345, Symbol = "MSFT", Price = 5, Quantity = 1 });
await trans.CommitAsync();
```

Here is my suggestion 2:
```C#
using var trans = await db.Database.BeginTransactionAsync();
var row = await db.Database.TPosition
    .Where(x=>x.Uid == uid && x.Symbol = symbol)
    .Update(c => c.Total = c.Total + 5 && c.Frozen = 0)
    .Execute();
if (row == 0)
{
    await db.Database.TPostion
        .Insert(new { Uid = 12345, Symbol = "MSFT", Total = 5, Frozen = 0 })
        .Execute();
}
await db.Database.TOrder
    .Insert(new { Uid = 12345, Symbol = "MSFT", Price = 5, Quantity = 1 })
    .Execute();
await trans.CommitAsync();
```

Edited on 06/09: Add suggestion 2

**Comment by ErikEJ** [comment]
Why not just write a stored procedure?

**Comment by wsq003** [comment]
> Why not just write a stored procedure?

Two reasons:
1, MySQL do not support stored procedure well. 
2, Our company want to manage all business logic in C# source code, with gitlab version control.

**Comment by ajcvickers** [comment]
@wsq003 These kind of updates are covered by https://github.com/dotnet/efcore/issues/795, which is planned for 7.0.

**Comment by wsq003** [comment]
@ajcvickers I'm not sure if it is a good idea to add `BulkUpdate` to `DbSet`. The basic design of `DbSet` is to maintain a copy of data in memory, now the `BulkUpdate` try to reverse the previous design. This would seems ambiguous and confusing.

```C#
dbSet.BulkUpdate(c => new { Age = c.Age + 1 });
```
If c.Age has a current value of 7, previous clause may have two assumptions: 
`update user set age = age + 1` or `update user set age = 7 + 1`

In previous `dbSet.Update(c => new { Age = c.Age + 1 })` we always think it would be `update user set age = 7 + 1`.
This would be misleading.

Base on previous consideration, maybe it's better to move `BulkUpdate` from `DbContext.DbSet` to `DbContext.DatabaseFacade`

**Comment by roji** [comment]
@wsq003 the design of the bulk update feature has been discussed extensively - please see the admittedly long discussions in #795.

>> dbSet.BulkUpdate(c => new { Age = c.Age + 1 });
>
> If c.Age has a current value of 7, previous clause may have two assumptions:
> update user set age = age + 1 or update user set age = 8

The BulkUpdate operator is being expressed over the entire DbSet, and not on any specific row, so I'm not sure where the constant "8" value would come from. The SQL here - `age = age + 1` corresponds exactly to the LINQ expression.

> Based on previous consideration, I think maybe it's better to move BulkUpdate from DbContext.DbSet to DbContext.DatabaseFacade

Unlike DbSet, DatabaseFacade isn't generic over the entity type, so you can't express strongly-typed LINQ queries from there.

**Comment by wsq003** [comment]
> Unlike DbSet, DatabaseFacade isn't generic over the entity type, so you can't express strongly-typed LINQ queries from there.

What I am asking here may be a built-in `convenient&safe sql query builder`. This `sql query builder` coincidently can do something like `BulkUpdate`.

**Comment by roji** [comment]
@wsq003 EF Core's SQL builder is LINQ, I'm not sure why another one is necessary. When you want to express some specific SQL which EF's current LINQ support can't generate, raw SQL is always there as a fallback.

What exact problem are you looking to solve that #795 wouldn't already address?

**Comment by wsq003** [comment]
> @wsq003 EF Core's SQL builder is LINQ, I'm not sure why another one is necessary. When you want to express some specific SQL which EF's current LINQ support can't generate, raw SQL is always there as a fallback.
> 
> What exact problem are you looking to solve that #795 wouldn't already address?

DbSet.SaveAllChanges() is supposed to `Saves all changes made in this context to the database`.
It is quite different from the interactive behavior with `BeginTransaction ... Commit`.

```C#
if (row == 0)
{
    await db.Database.ExecuteSqlRawAsync(
        $"insert into t_posistion (uid, symbol, total, frozen) values ({uid}, {symbol}, {val}, 0)");
}
```
Whether `insert t_position` or not, depends on the result of previous `update`.
When we start the batch execution, `how many changes are there` is not determined yet.

**Comment by wsq003** [comment]
```C#
using var trans = await db.Database.BeginTransactionAsync();
var row = await db.Database.TPosition
    .Where(x=>x.Uid == uid && x.Symbol = symbol)
    .Update(c => c.Total = c.Total + 5 && c.Frozen = 0);
if (row == 0)
{
    await db.Database.TPostion.Insert(
        new TPosition() { Uid = 12345, Symbol = "MSFT", Total = 5, Frozen = 0 });
}
await db.Database.TOrder.Insert(
        new TOrder() { Uid = 12345, Symbol = "MSFT", Price = 5, Quantity = 1 });
await trans.CommitAsync();
```

How about this LINQ style proposal?
Add LINQ ability to DbContext.DatabaseFacade looks nice.

**Comment by roji** [comment]
> How about this LINQ style proposal?

The syntax you propose above is impossible because you can't use assignment in expression trees (the above wouldn't compile).

More generally, there's already been an extensive design discussion about the API shape in #795 - including on the option you say above. It's a bit late to reopen this discussion, but if you do want to do so, you'll have to read #795 and be up to date with the different options.

Other than that, as I wrote above, not everything that happens on DbSet interacts with the change tracker: raw SQL queries (mentioned above) are one example, non-tracking queries are another. So we don't think there's a need to introduce BulkUpdate on DatabaseFacade.

Finally, I'm not sure exactly what you're trying to say in https://github.com/dotnet/efcore/issues/28182#issuecomment-1150198755. Database transactions can be used with change tracking or without - they're completely orthogonal to the question being discussed here.

**Comment by wsq003** [comment]
> > How about this LINQ style proposal?
> 
> The syntax you propose above is impossible because you can't use assignment in expression trees (the above wouldn't compile).

If LINQ is a SQL builder, it should be possible. It seems that LINQ is different from a common SQL builder.
A SQL builder is a `convenient&safe String.Format()`

> 
> More generally, there's already been an extensive design discussion about the API shape in #795 - including on the option you say above. It's a bit late to reopen this discussion, but if you do want to do so, you'll have to read #795 and be up to date with the different options.
> 
> Other than that, as I wrote above, not everything that happens on DbSet interacts with the change tracker: raw SQL queries (mentioned above) are one example, non-tracking queries are another. So we don't think there's a need to introduce BulkUpdate on DatabaseFacade.
> 
> Finally, I'm not sure exactly what you're trying to say in [#28182 (comment)](https://github.com/dotnet/efcore/issues/28182#issuecomment-1150198755). Database transactions can be used with change tracking or without - they're completely orthogonal to the question being discussed here.

Maybe this proposal is not related to #795
A lot of articles out there introduce how to use `Dapper` together with `EF Core`. Then I thought, why not integrated `Dapper` ability to `EF Core`, since `Dapper` is not complicated.

**Comment by roji** [comment]
@wsq003 if you're looking for a raw SQL API that's safe from SQL injection, see [FromSqlInterpolated](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql). That API is quite similar to what Dapper provides in many ways.

**Comment by wsq003** [comment]
> @wsq003 if you're looking for a raw SQL API that's safe from SQL injection, see [FromSqlInterpolated](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql). That API is quite similar to what Dapper provides in many ways.

Thanks for your information. 

[FromSqlInterpolated](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) looks very close to what I want, but it has some limitations:
```
Limitations
There are a few limitations to be aware of when using raw SQL queries:

The SQL query must return data for all properties of the entity type.
The column names in the result set must match the column names that properties are mapped to. Note this behavior is different from EF6. EF6 ignored property to column mapping for raw SQL queries and result set column names had to match the property names.
The SQL query can't contain related data. However, in many cases you can compose on top of the query using the Include operator to return related data (see [Including related data](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#including-related-data)).
```

A new function that returns raw database result (includes affected rows and unlimited fields/columns) would be sweet.

**Comment by roji** [comment]
@wsq003 for raw SQL that doesn't return query results (and so doesn't care about unlimited fields/columns), and just affected rows, use [ExecuteSqlInterpolated](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolated?view=efcore-6.0) or [ExecuteSqlRaw](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlraw?view=efcore-6.0).

I'm going to go ahead and close this as I think we've covered everything:
* ExecuteSqlRaw/Interoplated allow safely executing arbitrary raw SQL and return rows affected.
* FromSqlRaw/Interpolated allow safely executing arbitrary raw SQL, and return query results, including materialized entity types
* #795 will allow expressing bulk update/delete via LINQ operators (not raw SQL)
