### ISSUE TITLE
Cosmos db Hierarchical Partitions in EF Core

### ISSUE THREAD

**Issue by Ntethelelom** [dotnet/efcore#28186]
Hi I have a question, when it comes to working with hierarchical partition keys in Entity Framework. The hierarchical partitions are defined in the cosmos database, but I am struggling to work with them in EF when I have to specify HasPartitionKey method. I get an error that my partition specified does not match the partition defined in the document. Please assist on how I can work with hierarchical partitions in EF. See code below:

```C#
modelBuilder.Entity(entity =>
{
entity.HasNoDiscriminator();
entity.ToContainer((“Document”));
entity.HasPartitionKey(x => new {x.ClientId , x.ProjectId} );
entity.HasKey(x => new { x.id });
});
```

### Include stack traces
```
System.ArgumentException: 'The expression 'x => new <>f__AnonymousType1`2(ClientId = x.ClientId, ProjectId = x.ProjectId)' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')'
```

EF Core version: Microsoft.EntityFrameworkCore (6.0.5)
Database provider: Microsoft.EntityFrameworkCore.Cosmos (6.0.5)
Target framework: NET 6.0
IDE: Visual Studio 2022

**Comment by CR-CA** [comment]
I don't think those functions are suported in Entity Framework.

**Comment by smitpatel** [comment]
This feature is currently in preview in CosmosDb Sql API.

**Comment by Ntethelelom** [comment]
@ajcvickers Do we know when it's going to be released ?

**Comment by umairb-pedal** [comment]
Hi. Where is this in the backlog prioritisation? I assume it won't make it for the 8.0 release?

**Comment by ajcvickers** [comment]
@umairb-pedal This issue has zero votes, which, all other things being equal, buts it way down the priority list. Make sure to vote (👍) if its something you need.

**Comment by EstherSY** [comment]
Hello,  is there any workaround to have EF working with the container with hierarchical partition keys?   Is there plan for tentative release date for this support?

**Comment by ajcvickers** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 8.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by henryhom** [comment]
👍

**Comment by vitorlinares** [comment]
I can see this is labeled to be considered for current release, do we have any idea of when that will be released?

**Comment by ajcvickers** [comment]
@vitorlinares There is a reasonable chance this will end up in EF9, which ships November 2024.

**Comment by vitorlinares** [comment]
Thanks @ajcvickers, 
That's helpful for my roadmap planning.
I appreciate the prompt answer.

**Comment by aiimi-cclifton** [comment]
Kind of crazy this feature is missing. Just inherited a project using EF Core and cosmos, this prevents you leveraging best practices and if nothing else, should really be added to the docs as an absent feature 

Looking forward to its release!
