### ISSUE TITLE
Problem with simple projection

### ISSUE THREAD

**Issue by jarrettv** [dotnet/efcore#2818]
![image](https://cloud.githubusercontent.com/assets/219295/9203016/44628a88-401a-11e5-86c0-d061fa447faf.png)

I'm doing a simple projection through a relationship and it is failing. Sequence contains more than one element

**Comment by jarrettv** [comment]
![image](https://cloud.githubusercontent.com/assets/219295/9203096/ac4451a4-401a-11e5-9816-a947052d9a0b.png)

**Comment by rowanmiller** [comment]
This is a duplicate of #325 - traversing navigation properties in LINQ is being implemented at the moment.
