### ISSUE TITLE
DbSet.FromSqlRaw produces error when executing stored procedure

### ISSUE THREAD

**Issue by jmvvliet** [dotnet/efcore#28192]
Hi,

I am using DbSet.FromSqlRaw<entity> to obtain data from a stored procedure. This usually works, but in my case, I can't get it to work the way I want.

I have an entity:
```C#
public class School
{
  int Id { get; set; }
  string Name { get; set; }
}
```

Calling code:
```C#
var parameters = new List<SqlParameters>();

var dt = new DataTable();

dt.Columns.Add("ParameterIndex", typeof(int));
dt.Columns.Add("ParameterName", typeof(string));
dt.Columns.Add("Operator", typeof(string));
dt.Columns.Add("ParameterValue", parameterType);

foreach (IParameters param in parameters)
{
    DataRow dr = dt.NewRow();
    dr["ParameterIndex"] = autoIncrementSeed++;
    dr["ParameterName"] = param.ParameterName;
    dr["Operator"] = param.Operator;
    dr["ParameterValue"] = param.ParameterValue;
    dt.Rows.Add(dr);
}

parameters.Add(new SqlParameter($"@{typeName}", dt)
{
    SqlDbType = SqlDbType.Structured,
    TypeName = $"[dbo].[{typeName}]",
    Direction = ParameterDirection.Input,
});

//omitted other parameters for brevety

var result = await _dbSet.FromSqlRaw<School>(query.ToString(), parameters.ToArray()).ToListAsync();
```
The error:
The required column 'Id' was not present in the results of a 'FromSql' operation.

My stored procedure (inside an Azure SQL Database) looks like this
```SQL
ALTER PROC [dbo].[School_GetList] (
	@IntWhereClauses IntWhereClauses READONLY
	,@debug bit = 0)
AS
BEGIN
	DECLARE		@sql nvarchar(MAX),
				@paramlist nvarchar(max),
				@nl char(2) = char(13)+char(10),
				@paramValues nvarchar(max)

	select @paramValues = N'AND ' + dbo.GenerateWhereClauseForIntegers(@IntWhereClauses)

	SELECT @sql = 
		'SELECT 
		 t.[Id], t.[Name], t.[SchoolBoardId], t.[CreatedBy], t.[CreatedDate], t.[UpdatedBy], t.[UpdatedDate]
		 FROM dbo.School t
		 WHERE 1=1 ' + @nl + @paramValues

	select @paramList = dbo.GenerateParametersForIntegers(@IntWhereClauses)

	IF (@debug = 1)
	BEGIN
		PRINT @sql
		PRINT @paramList
	END

	EXEC sp_executesql @sql, @paramlist

		--EXEC sp_executesql @test = N'SELECT 
		-- t.[Id], t.[Name], t.[SchoolBoardId], t.[CreatedBy], t.[CreatedDate], t.[UpdatedBy], t.[UpdatedDate]
		-- FROM dbo.School t'
END
```
Don't mind about the complexity, the functions starting with 'Generate' are meant to check existence of columnames in the incoming TVP's to prevent sql injection.

Te resulting query is something like:
```SQL
SELECT 
		 t.[Id], t.[Name]
		 FROM dbo.School t
		 WHERE 1=1 
AND [SchoolBoardId] >= @p1 AND [SchoolBoardId] <= @p2 
```
with @paramlist = '@p1 INT = 1, @p2 INT = 100'

However, it seems that, when I comment out the actual procedure, and uncomment the last three rows, all is working correctly and I don't get the error. So I can work around it.

But to conclude, I think that executing a parameterized sp_execute_sql INSIDE a stored procedure causes this problem.  But maybe I'm doing something wrong myself?

Thanks in advance for investigating.

**Comment by jmvvliet** [comment]
I've done that, inside sql server management studio. They both give exactly the same results. 

But FromSqlRaw<entity> gives an error on the first, and a list of entities on the second. So, that was why I was issuing this.

**Comment by ErikEJ** [comment]
Full repro then?

**Comment by jmvvliet** [comment]
Check, I'll provide a sample console application (tomorrow) and will post it here

**Comment by jmvvliet** [comment]
I've created a sample console app here (https://github.com/jmvvliet/SqlRawSpTestApp). It's public available.

Create a database, fill in connectionstring, update the database and run the sample.

I've created five stored procs, all just a bit different. Only the last one works in the console app. 
All stored procedures will work in SQL server management studio. (T-sql to test included in program.cs as comment).

I cannot discover why this behavior occurs, maybe you can based on this example.

Thanks in advance.

**Comment by jmvvliet** [comment]
Just added ado.net style data fetching with a datareader, that works with all of the stored procedures

**Comment by roji** [comment]
@jmvvliet you're not correctly executing the stored procedure with EF. [As per the docs](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters), the parameter name has to be specified after the procedure name. Also, you probably need to specify SqlDbType.Structured on the parameter type, like you're doing with raw ADO.NET:

```c#
var filterParameter = new SqlParameter(...);

var blogs = context.Blogs
    .FromSqlRaw("EXECUTE dbo.GetMostPopularBlogsForUser @IntWhereClauses", filterParameter)
    .ToList();
```

**Comment by jmvvliet** [comment]
Well, thanx, so I was doing something wrong myself. 

The parameter already had a DbType of structured, but I was confused because the parametername is specified in the SqlParameter already and didn't need to add it to the SqlCommand to get it working.

Thanx and I will close the case.

**Comment by ErikEJ** [comment]
Just got around to it myself - this is the code generated by EF Core Power Tools stored procedure mapping...

```csharp
        public virtual async Task<int> School_GetListAsync(DataTable IntWhereClauses, bool? debug, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IntWhereClauses",
                    Value = IntWhereClauses ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[IntWhereClauses]",
                },
                new SqlParameter
                {
                    ParameterName = "debug",
                    Value = debug ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[School_GetList] @IntWhereClauses, @debug", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
```

so

      query.Append($"EXEC {command} @IntWhereClauses");

**Comment by ErikEJ** [comment]
You should - could save you some plumbing code. (Full disclosure: I am the maintainer) :smile:
