### ISSUE TITLE
Support nosql databases

### ISSUE THREAD

**Issue by dpoornabi29088** [dotnet/efcore#28208]
Sometimes we need to use NoSQL databases in our projects so if you could handle it in EfCore it great for us. In addition, please improve EfCore load data performance like Dapper tools.

Thank you so much
🙏🙏🙏

**Comment by ErikEJ** [comment]
EF Core already supports a NoSQL database and its performance is on par with Dapper.

**Comment by roji** [comment]
As @ErikEJ wrote, the EF team maintains a provider for CosmosDB, which is NoSQL (community providers exist for other databases). Regarding performance, [see this blog post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-4-performance-edition/) for query perf improvements done in 6.0. If you think you're hitting a specific performance problem, please open an issue with a minimal benchmark showing the issue (with BenchmarkDotNet).

**Comment by dpoornabi29088** [comment]
Thank you so much. I hope your features enhance every day.

Best regards
