### ISSUE TITLE
Nullable data types different behavior in OwnsOne usage

### ISSUE THREAD

**Issue by mnsrulz** [dotnet/efcore#28201]
I am seeing a behavior where properties included as OwnsOne method not throwing the null data type error.

### code to reproduce
This is my sample table which contains few columns and most of them are nullable
```
CREATE TABLE [dbo].[Group](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](80) NULL,
	[EmailNotify] [varchar](255) NULL,
	[HasDiscount] [bit] NULL,
	[Discount] [int] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
))

```

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContextFactory<AppDbContext>(options => options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddDatabaseDeveloperPageExceptionFilter();
builder.Services.AddHealthChecks().AddDbContextCheck<AppDbContext>();
var app = builder.Build();

app.MapGet("/groups",
async (IDbContextFactory<AppDbContext> dbContextFactory, HttpContext http) =>
{
    using (var dbContext = dbContextFactory.CreateDbContext())
    {
        return Results.Ok(await dbContext.Campaigns.AsNoTracking().ToListAsync());
    }
}).ProducesProblem(401);
app.UseRouting();
app.Run();

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }
    public DbSet<Group> Campaigns => Set<Group>();
}


public class GroupConfiguration : IEntityTypeConfiguration<Group>
{
    public void Configure(EntityTypeBuilder<Group> builder)
    {
        builder.ToTable("Group");
        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id)
            .UseIdentityColumn();

        builder.OwnsOne(
           p => p.Options,
           o =>
           {
               o.Property(p => p.Discount).HasColumnName("Discount");
               o.Property(p => p.EmailNotify).HasColumnName("EmailNotify");
               o.Property(p => p.HasDiscount).HasColumnName("HasDiscount");
           });
    }
}

public class Group
{
    public Group()
    {
        Options = new Options();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public Options Options { get; set; }
    public bool IsActive { get; set; }
}
public class Options
{
    public string EmailNotify { get; set; }
    public bool HasDiscount { get; set; }
    public int Discount { get; set; }
}
```

### Include verbose output
Given above configuration, 
```
Id	Name	        EmailNotify	HasDiscount	Discount	IsActive
1	Test Group	email@email.com	NULL	        10		0
```
when the table has Null in the HasDiscount column then system eat the error silently and produces the JSON
`[{"id":1,"name":"Test Group","options":{"emailNotify":null,"hasDiscount":false,"discount":0},"isActive":false}]`

however, when the table has Null in the IsActive column the system generates the error as below
`SqlNullValueException: Data is Null. This method or property cannot be called on Null values.`

I am assuming getting an exception is an expected behavior in both of the scenarios.

### Include provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 6
Operating system: Windows 10
IDE: VS 2022 Enterprise

**Comment by ajcvickers** [comment]
@mnsrulz All columns in an owned type are nullable by default to account for the case where the owner exists but has no owned instance. This is a limitation of owned types.

**Comment by mnsrulz** [comment]
Makes sense. May I ask why the emailNotify property came back as null despite having data in it in database. I guess it would make more sense if we can get the exception thrown in this case or get the values filled. Currently it’s failing silently.

**Comment by smitpatel** [comment]
Your properties in owned type `HasDiscount` and `Discount` are marked as non-nullable in C# class (bool/int are non-nullable types). But your database contains null value in `HasDiscount` column. Materializing an instance here meaning assigning a null value to a bool property which is an error. Owned type materialization checks if for the type existence using the non-nullable properties and if they contain null value we take it that owned type doesn't exist and hence we don't materialize.

Your database mode and your C# model are not matching each other hence you are seeing wrong behavior.
