### ISSUE TITLE
EF Core idempotent migration script fails despite check on applied migration

### ISSUE THREAD

**Issue by trevonmckay** [dotnet/efcore#28209]
## File a bug

Our CD pipeline is failing because SQL is reporting that a column could not be found while trying to apply a migration. Our script is generated in the CI process using the --idempotent flag. The column is not expected to be there by the time this statement is run because the column was removed in a later migration step that was previously applied. I've manually verified the IF NOT EXISTS statement for the given migration name.

### Generate migrations command
```bash
dotnet ef migrations script --verbose --output /home/vsts/work/1/a/migrations/SupplierServiceContext.sql --project /home/vsts/work/1/s/SupplierService.Infrastructure.csproj --startup-project /home/vsts/work/1/s/SupplierService.API.csproj --context SupplierWriteDbContext -i
```

### Snippet of migrations script
```sql
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20220511184352_StartsEntityIdRefactor')
BEGIN
    UPDATE [dbo].[SupplierLists] SET [LegacyId] = [Id];
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20220511184352_StartsEntityIdRefactor')
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20220511184352_StartsEntityIdRefactor', N'6.0.5');
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20220512193747_NullableDescription-DropLegacyId')
BEGIN
    DECLARE @var11 sysname;
    SELECT @var11 = [d].[name]
    FROM [sys].[default_constraints] [d]
    INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
    WHERE ([d].[parent_object_id] = OBJECT_ID(N'[SupplierLists]') AND [c].[name] = N'LegacyId');
    IF @var11 IS NOT NULL EXEC(N'ALTER TABLE [SupplierLists] DROP CONSTRAINT [' + @var11 + '];');
    ALTER TABLE [SupplierLists] DROP COLUMN [LegacyId];
END;
GO

```

### Include stack traces

```
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, D:\a\_tasks\SqlAzureDacpacDeployment_ce85a08b-a538-4d2b-8589-1d37a9ab970f\1.202.0\DeploySqlAzure.ps1: line 220
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Invalid column name 'LegacyId'. 
##[debug] Msg 207, Level 16, State 1, Procedure , Line 4.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
##[error]Invalid column name 'LegacyId'. 
 Msg 207, Level 16, State 1, Procedure , Line 4.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
##[debug]Processed: ##vso[task.logissue type=error]Invalid column name 'LegacyId'. %0D%0A Msg 207, Level 16, State 1, Procedure , Line 4.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
##[debug]Processed: ##vso[task.complete result=Failed]

```

### Include verbose output

```
Invalid column name 'LegacyId'.
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.3

**Comment by furier** [comment]
Hi @trevonmckay and @roji we are experiencing exactly this problem now.

downloading the `migrations.sql` script from azure devops build artifacts and running it locally against dev and prod databases restored locally works fine for the prod database but not for the dev database.

using azure data studio schema compare shows no difference when comparing the dev and prod databases, the same goes for data compare, comparing the __EfMigrationsHistory table, the same data is present in both but for some reason it ties to apply an already applied migration to the dev database but not the prod database.

here is one of the statements that gives an error
```sql
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20231219145849_TenantId2CustomerId')
BEGIN

                    UPDATE [dbo].[ApiClients]
                    SET [TenantId] = [Customer].[Id]
                    FROM [dbo].[ApiClients] AS [ApiClient]
                    INNER JOIN [dbo].[Customers] AS [Customer] ON [ApiClient].[TenantId] = [Customer].[TenantId]
                
END;
GO
```

running the `SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20231219145849_TenantId2CustomerId'` sql statement alone returns a row for the dev database so it baffles me why this statement fails, saying the `TenantId` column no longer exists which is true.

I have use the whole day trying to figure out this ans tried everything and consulted with colleagues but without avail, so now we are here in hopes of getting an answer. 🤷‍♂️

**Comment by hisuwh** [comment]
We're seeing the same issue.
@roji why was this closed without a response?

**Comment by AndriySvyryd** [comment]
The OP closed the issue. Please file a new one and share a small runnable project that shows it.

It might be caused by different database version or settings.
