### ISSUE TITLE
Move table configuration methods to `(OwnedNavigation)TableBuilder`

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#28205]
- [ ] `HasComment`
- [ ] `HasCheckConstraint`
- [ ] `IsMemoryOptimized`

**Comment by ajcvickers** [comment]
Note from triage: Obsolete existing methods.

**Comment by roji** [comment]
Thinking about this again, maybe it's OK to leave the current methods on EntityTypeBuilder as easy sugar for when you don't map to multiple tables (which is the majority case, after all)... Would also avoid the obsoletion/breaking change...

**Comment by AndriySvyryd** [comment]
These methods only apply to tables and if we leave them they could me misinterpreted as somehow applicable to views/functions/sprocs

**Comment by roji** [comment]
Comment specifically could actually work on those other things. For the other two, throwing if they're applied on a non-table could be reasonable - just to provide the shortcut and prevent the break. But am OK for removal if there are strong feelings here.

**Comment by AndriySvyryd** [comment]
> Comment specifically could actually work on those other things.

Yes, hence the confusion since it won't be applied
