### ISSUE TITLE
If we group on an expression (e.g. a ternary), should the expression be re-used rather than further translated when selected in another expression (e.g. ternary)?

### ISSUE THREAD

**Issue by CaiusJard** [dotnet/efcore#28219]
## Ask a question

As an example, the following C# query generates a problematic SQL. It groups on whether an order is complete or not and then uses the ternary result twice for two different outputs:

    context.Orders
      .GroupBy(o => new { IsCompleted = o.OrderStatus == "C" } )
      .Select(g => new { 
        OrderStatusText = g.Key.IsCompleted ? "Completed" : "Pending",
        OrderStatusCode = g.Key.IsCompleted ? 1 : 2
      } );

It generates the following:

```
SELECT 
  CASE WHEN [o].[OrderStatus] = 'C' THEN N'Completed' ELSE N'Pending' END AS [OrderStatusText], 
  CASE WHEN [o].[OrderStatus] = 'C' THEN 1 ELSE 2 END AS [OrderStatusCode]
FROM [Orders] AS [o]
GROUP BY
  CASE WHEN [o].[OrderStatus] = 'C' THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END
```

I can reason why it generates thus, but it's syntactically invalid because the expressions selected are not contained in the group by/not aggregated, and SQLServer isn't going to go to the extent of working out that the CASE WHENs all having the same predicate means that they're essentially interchangeable/something like functionally dependent. 

If the expression grouped by had been re-used in its entirety, like the C# does, SQLServer would have accepted it:

```
SELECT 
  CASE WHEN (

    --here is the expression from the group by re-used
    CASE WHEN [o].[OrderStatus] = 'C' THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END

  ) = CAST(1 AS BIT) THEN N'Completed' ELSE N'Pending' END AS [OrderStatusText], 

  CASE WHEN (

    --here is the expression from the group by re-used
    CASE WHEN [o].[OrderStatus] = 'C' THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END

  ) = CAST(1 AS BIT) THEN 1 ELSE 2 END AS [OrderStatusCode]
FROM [Orders] AS [o]
GROUP BY
  CASE WHEN [o].[OrderStatus] = 'C' THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END
```

At the moment when I hit this, I group by the same thing repeatedly in the C# and generate the values I will use as part of the grouping; in essence I can see the inherent deterministic equivalence of repeating the predicate and I generate something like:

    context.Orders
      .GroupBy(o => new { 
        OrderStatusText = o.OrderStatus == "C" ? "Completed" : "Pending,
        OrderStatusCode = o.OrderStatus == "C" ? 1 : 2
      } )
      .Select(g => new { 
        g.Key.OrderStatusText,
        g.Key.OrderStatusCode
    } );

This naturally generates a redundant grouping op, but it does work:

```
SELECT 
  CASE WHEN [o].[OrderStatus] = 'C' THEN N'Completed' ELSE N'Pending' END AS [OrderStatusText], 
  CASE WHEN [o].[OrderStatus] = 'C' THEN 1 ELSE 2 END AS [OrderStatusCode]
FROM [Orders] AS [o]
GROUP BY
   CASE WHEN [o].[OrderStatus] = 'C' THEN N'Completed' ELSE N'Pending' END,
   CASE WHEN [o].[OrderStatus] = 'C' THEN 1 ELSE 2 END
```

So the question is, would it be reasonable for EF to generate SQL where expressions in the Select, derived from expressions in the GroupBy, do just repeat the generated GROUP BY expression and then examine its output value:

    SELECT
      CASE WHEN (expression from group by) = someValue THEN ...
    ...
    GROUP BY expression 

### Include provider and version information

EF Core version: 6.0.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)

**Comment by smitpatel** [comment]
Fixed in nightly builds
