### ISSUE TITLE
regression in efcore 6.0.5 causes crashes when table name starts with a number

### ISSUE THREAD

**Issue by mxswd** [dotnet/efcore#28211]
## File a bug

When attempting to update from dotnet 3.1 to dotnet 6 and efcore 3 to 6 my queries now crash with the error:

```
Core Microsoft SqlClient Data Provider: Invalid object name '3AData'.
```

All these queries worked in efcore 3.

### Include your code

This code causes the crash: 

```C#
var data = _context.AData.ToList();
```

It works in efcore 3 and not in 6.

The table is defined as:

```
[Table("3AData", Schema = "App")]
public class AData {
  public class AData();
  [Column("3aid")]
  [Key]
  public Guid aid {get; set; }
}
```

The context fluent API build is defined as:

```
modelBuilder.Entity<3AData>().ToTable("3AData");
```

### Include provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  dotnet 6
Operating system: azure windows
IDE: vscode

**Comment by roji** [comment]
This works fine for me, please see my minimal code sample below. I suspect something else is the issue - you may have forgotten to run migrations, and the table simply doesn't exist in your database.

If you're still encountering issues, please post a fully runnable, minimal repro (such as the below) which shows the problem occurring.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.ADatas.ToList();

public class BlogContext : DbContext
{
    public DbSet<AData> ADatas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

[Table("3AData", Schema = "App")]
public class AData
{
  [Column("3aid")]
  [Key]
  public Guid aid {get; set; }
}
```

</details>

**Comment by mxswd** [comment]
Thanks! I think I found the problem. The code configured the table and scheme name in the annotation as well as the builder configuration. 

```
modelBuilder.Entity<3AData>().ToTable("3AData");
```

But this is missing a scheme name and it seems to override the schema in the annotation and default to dbo. Changing it to this fixes the problem. 

```
modelBuilder.Entity<3AData>().ToTable("3AData", "App");
```
