### ISSUE TITLE
Add additional overloads to provider ServiceCollectionExtensions methods.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#28217]
I have a problem where there are no overloads of the provider ServiceCollectionExtensions that accepts in the lifetimes that ``ServiceCollectionExtensions.AddDbContext`` can accept.

Why would I want this? It can be common for providers to want to include a way for the developer to pass in the lifetimes themselves if they do not want to worry about using ``AddDbContext`` themselves.

Also doing this could simplify the normal versions of the provider ServiceCollectionExtensions by calling into the additional ones to help stub them out better.

The solution would be to add additional ones that adds ``contextLifetime`` and ``optionsLifetime`` to all providers for their ServiceCollectionExtensions.

**Comment by ajcvickers** [comment]
@AraHaan `AddSqlServer`, etc. are designed explicitly to be a very simple way of doing the simple thing. Adding more options is a slippery slope where it is no longer simple. Guidance is that once you get to the point where you want to change anything. (Likely very soon after creating your first app), then you switch to AddDbContext, which is the proper way of doing things within the design of EF.

(Nobody on the team thinks that `AddSqlServer`, etc. were a good idea, but other stakeholders wanted them.)
