### ISSUE TITLE
Many to Many - Additional Properties

### ISSUE THREAD

**Issue by DominikErnst** [dotnet/efcore#28218]
Hi.

I have three entities: User, Customer, User_Customer (n:n).

The Configuration for the User - Entity  is following:
```
	modelBuilder.Entity<User>().HasMany(p => p.Customers).WithMany(p => p.Users).UsingEntity<User_Customer>(
		j => j.HasOne(pt => pt.Customer).WithMany(t => t.UsersCustomers).HasForeignKey(pt => pt.Customer_Id),
		j => j.HasOne(pt => pt.User).WithMany(p => p.UsersCustomers).HasForeignKey(pt => pt.User_Id),
		j => j.HasKey(pt => new { pt.User_Id, pt.Customer_Id }));
```

There are additional **mandatory** Fields in User_Customer:

- UserKey
- CompanyKey
- CustomerKey

In C# Code, I add Customers to a User:
```
user.Customers.Add(customer);
```
while saving there is an Exception
```
await db.SaveChangesAsync();
```
Exception:
` Cannot insert the value NULL into column 'CompanyKey', table 'sqldb-ams-dev.dbo.Users_Customers'; column does not allow nulls. INSERT fails. The statement has been terminated.`

I think that the additional fields are not automatically filled in by EF Core. How can I configure that the additional fields are set?

If I use the following configuration, it works, but of course the fields are filled incorrectly:

```
modelBuilder.Entity<User>().HasMany(p => p.Customers).WithMany(p => p.Users).UsingEntity<User_Customer>(
j => j.HasOne(pt => pt.Customer).WithMany(t => t.UsersCustomers).HasForeignKey(pt => pt.Customer_Id),
j => j.HasOne(pt => pt.User).WithMany(p => p.UsersCustomers).HasForeignKey(pt => pt.User_Id),
j => {
	j.Property(pt => pt.CompanyKey).HasDefaultValue("1");
	j.Property(pt => pt.CustomerKey).HasDefaultValue("2");
	j.Property(pt => pt.UserKey).HasDefaultValue("3");
	j.HasKey(pt => new { pt.User_Id, pt.Customer_Id });
});
```

My Workaround at the moment is to save the User_Customer - Entity:
```
db.UsersCustomers.Add(new User_Customer
	{
		User_Id = user.Id,
		Customer_Id = customer.Id,
		UserKey = uc.UserKey,
		CompanyKey = uc.CompanyKey,
		CustomerKey = uc.CustomerKey
	});
```

Thanks in advance

**Comment by ajcvickers** [comment]
@DominikErnst 

> I think that the additional fields are not automatically filled in by EF Core. How can I configure that the additional fields are set?

Do you want EF to automatically create some values for these fields? Or are you asking how to set the fields manually to some values before the `User_Customer` join entity is inserted?

**Comment by ajcvickers** [comment]
@DominikErnst Unfortunately, I'm not following what you mean. When you say, "But the values are present here in the customer object," which customer object are you referring to?

**Comment by uehlbran** [comment]
@ajcvickers Any chance the documentation will be updated to reflect how you set additional properties on a join entity manually? Your documentation fails to address this, all of the videos you've put out on ef core 5 and 6 also fail to address this issue.

**Comment by DominikErnst** [comment]
> @DominikErnst Unfortunately, I'm not following what you mean. When you say, "But the values are present here in the customer object," which customer object are you referring to?

I refer to the User and Customer Object:

**USER**
```
	public int Id { get; set; }                                         // The Primary-Key for EF/Database
        ...
	public string UserKey { get; set; } = null!;              // Additional Field
        ...
```

**CUSTOMER**
```
	public int Id { get; set; }                                         // The Primary-Key for EF/Database
        ...
	public string CompanyKey { get; set; } = null!;      // Additional Field
	public string CustomerKey { get; set; } = null!;      // Additional Field
        ...
```

**N:N - Object**
```
		public int User_Id { get; set; }                                 // User - ID, is set by EF
		public User User { get; set; } = null!;

		public int Customer_Id { get; set; }                        // Customer - ID, is set by EF
		public Customer Customer { get; set; } = null!;

		public string UserKey { get; set; } = null!;             // Additional Fields, NOT set by EF* (from User-Entity)
		public string CompanyKey { get; set; } = null!;     // Additional Fields, NOT set by EF* (from Customer-Entity)
		public string CustomerKey { get; set; } = null!;     // Additional Fields, NOT set by EF* (from Customer-Entity)
```

_"NOT set" is the same as "How to configure?"_

Thanks for helping.

**Comment by ajcvickers** [comment]
@DominikErnst So you want to duplicate the values from the entities on either end into the join table? if so, there's no way to do that automatically, but you could override `SaveChanges` and copy the values over before saving the entities. Let me know if you need me to show some code how to do that.

**Comment by DominikErnst** [comment]
@ajcvickers ok, thank you. Then I stick to my "workaround". But thanks for the info that you can overwrite SaveChanges, again what learned. ;-)
The additional Fields are the PKs from a AS400/iSeries DB2 Database. I want them stored for debugging and researching.
