### ISSUE TITLE
Version 6.0.6 Does not support 3.1

### ISSUE THREAD

**Issue by slongietti** [dotnet/efcore#28225]
Version 6.0.0 - 6.0.5 supported .NET Core 3.1 however 6.0.6 does not.

If this is intended, that's fine, but without any notice, this was a  surprise for many enterprise pipelines today that use the latest dotnet-ef  cli w/ .NET Core 3.1. 

Package dotnet-ef 6.0.6 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1)

**Comment by ErikEJ** [comment]
Breaking change in 6.0.6: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#dotnet-ef-targets-net-6

**Comment by ErikEJ** [comment]
@bricelam Maybe the docs could be enhanced with:

    dotnet tool install dotnet-ef --version 6.0.5

**Comment by ajcvickers** [comment]
@slongietti To be clear, EF Core 6.0 never supported .NET Core 3.1, but the `dotnet-ef` tool did.

**Comment by slongietti** [comment]
@ajcvickers  Agreed. The dotnet-ef tool no longer supports .NET Core 3.1 in version 6.0.6 (which is fine if intended). As @ErikEJ mentioned maybe there is a way to annotate that in the documentation in the Mitigations section where it talks about being able to use dotnet-ef without .NET 6

**Comment by ajcvickers** [comment]
@slongietti If you're using an older version of EF, then it would be better to use an older version of the tool.
