### ISSUE TITLE
ConfigureWarnings example deprecated

### ISSUE THREAD

**Issue by peet-brits** [dotnet/efcore#28236]
The example provided on the ConfigureWarnings page is deprecated in version 6. Could someone please update this with new examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dacb17-7fce-1e8c-2722-25de729c0811
* Version Independent ID: b9d51491-c6f0-b258-812a-8bd75577e437
* Content: [DbContextOptionsBuilder.ConfigureWarnings Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.configurewarnings?view=efcore-6.0#microsoft-entityframeworkcore-dbcontextoptionsbuilder-configurewarnings(system-action((microsoft-entityframeworkcore-diagnostics-warningsconfigurationbuilder))))
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Note for triage: This was done in https://github.com/dotnet/efcore/pull/26439. Not sure why this change is not reflected in the published docs.

**Comment by smitpatel** [comment]
Published docs are merge mode.

**Comment by ajcvickers** [comment]
Note from triage: we will manually update the published docs as part of MQ.

**Comment by smitpatel** [comment]
Filed internal issue to see what docs team say.

**Comment by smitpatel** [comment]
> This was done in https://github.com/dotnet/efcore/pull/26439. Not sure why this change is not reflected in the published docs.

Those changes are not in 6.0 release or that PR didn't fix this issue. 6.0 source code contains example in the code and docs are correctly showing 6.0 docs.

**Comment by ajcvickers** [comment]
Note for triage: there is no example code in the current code in main.
