### ISSUE TITLE
Migration with comment

### ISSUE THREAD

**Issue by Zefek** [dotnet/efcore#28239]
Hello, 
I want to ask you if there is possibility to add comments into migration C# generated code. Many of teams have rule that each method or class needs to be commented. In migration script it is easy, because Up/Down method is override and comments it should be <inheritdoc />. 
For migration class (or type) empty summary comment will be enough. Or there could be option in dotnet-ef tool to add comment when generating migration and this comment will be in summary tag. 

Thank you.

**Comment by ajcvickers** [comment]
Duplicate of #10695.
