### ISSUE TITLE
Is there a way to skip a property from insert?

### ISSUE THREAD

**Issue by alewmt** [dotnet/efcore#28255]
Hi!
I map the same class to a table and a view. The view contains more fields than the table.
Additional fields are from join and are readonly. So the problem is an error on insert "column does not exist"
Is there a way not to map the property on insert and update?

EF Core version:  5.0
Database provider: Npgsql 5.0.14
Target framework: .NET 6.0

**Comment by roji** [comment]
I don't think it's impossible to have a different set of properties for querying and for updating - you're going to have to instruct EF Core ignore the extra fields in the view. Another option is of course to split into two entities, one mapped to your table and the other to your view.

**Comment by alewmt** [comment]
It works! Thank you!
