### ISSUE TITLE
EF.Functions.Contains blocking results from being returned

### ISSUE THREAD

**Issue by ermaugustinas** [dotnet/efcore#28251]
### Include your code

C# code 

```c#
  var query =
      from i in db.Incidents
      join t in (
          from t in db.Texts
          where EF.Functions.Contains(t.Value, "person")
          select t
      ) on i.Id equals t.IncidentId
      select i.Id;
  var raw = query.ToQueryString();
        var results = await query.ToListAsync(ct);
        var tmp = results;
       
```

Generated SQL

```sql
SELECT [i].[ID]
FROM [Incident] AS [i]
INNER JOIN (
    SELECT [t].[IncidentID]
    FROM [Text] AS [t]
    WHERE CONTAINS([t].[Value], N'person')
) AS [t0] ON [i].[ID] = [t0].[IncidentID]
```

Result from Direct to Db:

```
ID
1
1
1
```

As soon as `where EF.Functions.Contains(t.Value, "person")` is removed, the correct data is returned

### Include stack traces

No failure occurs

### Include provider and version information

EF Core version: 6.0.4
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET 6.0)
Operating system: Ubuntu
IDE: (Jetbrains Rider)

**Comment by ermaugustinas** [comment]
Side note, using any other `where` statement works fine

**Comment by ermaugustinas** [comment]
Even smaller test case:

```sql
DECLARE @__incident_Id_0 int = 1;

SELECT [t].[ID], [t].[DatasetID], [t].[IncidentID], [t].[LookupID], [t].[Value]
FROM [Text] AS [t]
WHERE ([t].[IncidentID] = @__incident_Id_0) AND CONTAINS([t].[Value], N'person')
```

```c#
    var query = from t in db.Texts
        where t.IncidentId == incident.Id
        where EF.Functions.Contains(t.Value, "person")
        select t;
```

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ermaugustinas** [comment]
I'm sorry @ajcvickers , I got frustrated an was grasping at the straws here. I had some data arranging happening before the query runs and then the testing function ran.

From what it seems I need to add a timeout of at least 4 seconds after new text is added for MSSQL to index it, only then am I amble to see the results. I'm leaving this in the hopes that someone else doesn't have to burn 4 hours debugging it.
