### ISSUE TITLE
efcore 6.0.6 notmapped apply datetime property is invalid

### ISSUE THREAD

**Issue by MingLiao1986** [dotnet/efcore#28256]
efcore 6.0.6 notmapped apply datetime property is invalid

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MingLiao1986** [comment]
sorry, no problem. it's issue of abp.
