### ISSUE TITLE
Why can't a CosmosDB partition key be an int when working with EF Core?

### ISSUE THREAD

**Issue by benrhere** [dotnet/efcore#28265]
## Ask a question
As you can see here: https://github.com/dotnet/efcore/blob/4a2e4ebc03f07536e400843105b8ed3c9a32a10b/src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs#L313-L318

EF Core Cosmos provider seems to force that a partition key be a string (or have a value converter to map to a string). But CosmosDB itself does not seem to have this restriction. According to: https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview : 

"The partition key value can be of string or numeric types."

I've confirmed that I can successfully use int as a Cosmos DB document partition key type (when EF Core is not in the picture). But Cosmos seems to throw the exception outlined in the above github link whenever you use WithPartitionKey for the relevant document:

```
"System.InvalidOperationException: 'The type of the partition key property [property] on [document] is 'int'. All partition key properties need to be strings or have a string value converter.'"
```

It seems like I should be able to specify an integer partition key when using EF Core with Cosmos DB. Am I mistaken?

### Include provider and version information

EF Core version: 6.0.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.2.4)

**Comment by HY1221** [comment]
use this to avoid the error .HasConversion<string>()

**Comment by benrhere** [comment]
If I understand correctly, .HasConversion() will allow me to work with an integer type in my code, but will still require the underlying type in the document to be a string. I'd like to have the underlying type be an integer, which .HasConversion() doesn't solve.
