### ISSUE TITLE
Use C# 11 raw string literals

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28260]
Docs: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#raw-string-literals

These should come in very handy for all SQL assertions, C# code generation (e.g. migrations), scaffolding SQL queries, etc.

:tada: Yay! :tada:

**Comment by ralmsdeveloper** [comment]
It's been a long time since I made contributions, I can start working on it (**Tests and Migrations**), if that's okay with you!

**Comment by roji** [comment]
@ralmsdeveloper not sure it's a good idea to work on this before C# 11 ships (or at least goes RC), in case the feature is changed or even pulled out.
