### ISSUE TITLE
RowVersion column in SQL Server doesn't work on normal update?

### ISSUE THREAD

**Issue by Markz878** [dotnet/efcore#28272]
## Why doesn't normal update method respect RowVersion expected behavior?

I have a .NET6 API project that allows users to fetch resources from a database (SQL Server), and update them on a web client, and submit the updated resource back for saving to db. I need to notify users if another user has already updated the same resource during editing. I tried using EF IsRowVersion property for this concurrency check.

I noticed that "normal" update procedure (just getting the entity, changing properties and saving) does not respect the RowVersion expected behavior. But if I get the entity using AsNoTracking and use the db.Update method, the concurrency check works as expected. What could be the reason, and is the db.Update the only way to force the RowVersion check? That method has the downside that it tries to update every property, not just those that have changed. Simplified and runnable console app example below:

```C#
using Microsoft.EntityFrameworkCore;
Guid guid;
using (PeopleContext db = new())
{
    Person p = new() { Name = "EF", Age = 30 };
    db.Database.EnsureDeleted();
    db.Database.EnsureCreated();
    db.People.Add(p);
    await db.SaveChangesAsync();
    guid = p.Id;
}
using (PeopleContext db = new())
{
    Person p = await db.People.FirstAsync(x => x.Id == guid);
    p.Name = "FE";
    p.RowVersion = Convert.FromBase64String("AAAAAADDC9I=");
    await db.SaveChangesAsync(); // Does not throw even though RowVersion is incorrect
}
using (PeopleContext db = new())
{
    Person p = await db.People.AsNoTracking().FirstAsync(x => x.Id == guid);
    p.Name = "EFFE";
    p.RowVersion = Convert.FromBase64String("AAAAAAGGC9I=");
    db.People.Update(p);
    await db.SaveChangesAsync(); // Throws DbUpdateConcurrencyException as expected, but updates all properties
}
public class Person
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public int Age { get; set; }
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();
}

public class PeopleContext : DbContext
{
    public PeopleContext(){}

    public DbSet<Person> People => Set<Person>();
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=EFRowVersionDb;Integrated Security=True;");
        optionsBuilder.LogTo(Console.WriteLine, Microsoft.Extensions.Logging.LogLevel.Information);
        optionsBuilder.EnableSensitiveDataLogging();

    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion();
        });
    }
}
```

### Include provider and version information

EF Core version: 6.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.2

**Comment by ajcvickers** [comment]
@Markz878 The concurrency check uses the original values of the entity--that is, the values that were in the database when the entity was queried. See discussion here: https://github.com/dotnet/efcore/issues/27865#issuecomment-1147298618. Better documentation for this is being tracked by https://github.com/dotnet/EntityFramework.Docs/issues/860.

**Comment by Markz878** [comment]
@ajcvickers Thanks for the answer! I looked at the discussion but I can't understand the decision behind this, but I understand that it would be a pretty big breaking change.
I fixed this by overriding the SaveChangesAsync
``` 
public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
{
    foreach (var item in ChangeTracker.Entries().Where(x=>x.State == EntityState.Modified))
    {
        item.OriginalValues["RowVersion"] = item.CurrentValues["RowVersion"];
    }
    return base.SaveChangesAsync(cancellationToken);
}
```
Can you tell me if this is an acceptable way to deal with this or is there a better way? This way at least does not "overpost" the properties.

Ps. Have been watching all your community stand-ups, feels like I'm talking to a celebrity :)

**Comment by ajcvickers** [comment]
@Markz878 Yes, that's an acceptable way of doing this. I think we need to start with some good docs on how to handle these cases and then take it from there.

> Ps. Have been watching all your community stand-ups, feels like I'm talking to a celebrity :)

Thanks! :-)
