### ISSUE TITLE
OnConfiguring when parametrized Constructor is used

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#28286]
Hello,

In my DBContext I need to have a default Configuration but also should be possible to instantiate the DBContext to let it point to another database. So I putted the default configuration in OnConfiguring and I added to DBContext the constructor with DBContextOption parameter, the result is :

```
    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions<TestContext> options): base(options)
        {
        }

        public TestContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer(@"Data Source=localhost\DEV2019;Integrated Security=true;Initial Catalog=Catalog1");
        }


```

So I tried to do this :
`            var DB = new TestContext();`
to get the default Configuration

And 
```
            var contextOptions = new DbContextOptionsBuilder<TestContext>().UseSqlServer(@"Data Source=localhost\DEV2019;Integrated Security=true;Initial Catalog=Catalog2").Options;
            var DB2 = new TestContext(contextOptions);

```
to use anoter Configuration

But when I use the second context, despite the configuration is passed in the constructor, OnConfiguration run anyway, overriding the configuration i passed in the constructor.

So, if i write 
```
            var DB1 = new TestContext();
            var cs1 = DB1.Database.GetDbConnection().ConnectionString;

            var contextOptions = new DbContextOptionsBuilder<TestContext>().UseSqlServer(@"Data Source=localhost\DEV2019;Integrated Security=true;Initial Catalog=Catalog2").Options;
            var DB2 = new TestContext(contextOptions);
            var cs2 = DB2.Database.GetDbConnection().ConnectionString;

```

cs1 and cs2 are equal and both point to Catalog1.

It is not reasonable that if i use the constructor with the configuration, OnConfiguring should not run?

Also, if in the constructon I pass a configuration that uses another porvider

```
            var contextOptions3 = new DbContextOptionsBuilder<TestContext>().UseSqlite(@"Data Source=c:\mydb.db;Version=3;").Options;
            var DB3 = new TestContext(contextOptions3);
            var cs3 = DB3.Database.GetDbConnection().ConnectionString;

```

when i use the DBContext it thow an exception because it found two registered providers

`Services for database providers 'Microsoft.EntityFrameworkCore.Sqlite', 'Microsoft.EntityFrameworkCore.SqlServer' have been registered in the service provider
`

[TestEFCore.zip](https://github.com/dotnet/efcore/files/8950738/TestEFCore.zip)

**Comment by ajcvickers** [comment]
@GLuca74 It is by-design that `OnConfiguring` always runs. Use `if (!optionsBuilder.IsConfigured)` if you want to only run code in `OnConfiguring` when a provider has not already been configured.

**Comment by GLuca74** [comment]
OK, and sorry for my oversight

Many thanks
