### ISSUE TITLE
Duplicates returned when using AsNoTracking

### ISSUE THREAD

**Issue by bruzkovsky** [dotnet/efcore#28288]
We have multiple Views which are 1:n-related, and including those related entities results in duplicate data.

There are at least 2 factors that are affecting this issue:
1. we noticed this after the upgrade from EF6 to EF Core, but the Database and the way we access the data did not change. We figured that it has to be related to this breaking change: https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md#removed-last-order-by-when-joining-for-collections
2. it only appears when using IQueryable with the `.AsNoTracking()` option.

Our data model has some specialities, but we broke it down to a simple scenario in a school context. This ER diagram shows the gist of it.

![EFCoreProblem drawio](https://user-images.githubusercontent.com/10390959/174866199-4826b737-e599-4f6f-8206-6adab1989082.png)

Note that the Books are resolved not over a FK on Student, but they are in the Course view with a PrincipalKey StudentId. With this setup, the other relationship to Assignment will resolve duplicate entries, as you can see when you run the code.

### Code

[EntityFrameworkCoreDuplicates.zip](https://github.com/dotnet/efcore/files/8951405/EntityFrameworkCoreDuplicates.zip)

Before running the app, run this SQL script to create and fill the database (.txt, because .sql is not supported here):

[EF_Core_Duplicates_Test.txt](https://github.com/dotnet/efcore/files/8951438/EF_Core_Duplicates_Test.txt)

### Provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.0.4

**Comment by ajcvickers** [comment]
@bruzkovsky Have you tried, `AsNoTrackingWithIdentityResolution`?

**Comment by bruzkovsky** [comment]
Wow, I never heard of this method before, and indeed it does exactly what I want it to do! Thank you for pointing that out!

I will close the issue, because we can use use AsNoTrackingWithIdentityResolution for the faulting cases, or perhaps as a default if the performance impact is not too great.
