### ISSUE TITLE
TPC migration attempts to drop nonexistent table for base type

### ISSUE THREAD

**Issue by smstromb** [dotnet/efcore#28298]
Reproducible with: https://github.com/smstromb/efcore-tpc-issue-reproducable

```cs
using Microsoft.EntityFrameworkCore;

public abstract class Animal
{
    public int Id { get; set; }
    public string Species { get; set; }
}
public class FarmAnimal : Animal
{
    public decimal Value { get; set; }
}
public abstract class Pet : Animal
{
    public string Name { get; set; }
}
public class Cat : Pet
{
    public string EducationLevel { get; set; }
}
public class Dog : Pet
{
    public string FavoriteToy { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=database.db")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Cat> Cats { get; set; }
    public DbSet<Dog> Dogs { get; set; }
    public DbSet<FarmAnimal> FarmAnimals { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Animal>().UseTpcMappingStrategy();
    }
}
```

Running `dotnet ef migrations add Initial` creates the expected sql schema with 3 tables for each concrete type but running a second migration, without any changes, results in a migration that attempts to drop `Animal`, a table that doesn't actually exist in the schema:

`dotnet ef migrations add ExpectedToBeEmpty`
```cs
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataModelPOC.Migrations
{
    /// <inheritdoc />
    public partial class ExpectedToBeEmpty : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Animal");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Animal",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Species = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Animal", x => x.Id);
                });
        }
    }
}
```

EF Core version: `7.0.0-preview.5.22302.2`
Database provider: `Microsoft.EntityFrameworkCore.Sqlite`
Target framework: 7.0 Preview

**Comment by ajcvickers** [comment]
Note for triage: repros with latest daily build.

**Comment by pheuter** [comment]
@AndriySvyryd This still appears to be an issue, tested on `Entity Framework Core .NET Command-line Tools 7.0.0-preview.7.22376.2`

**Comment by AndriySvyryd** [comment]
@pheuter The fix was to store more information in the snapshot, so you'd need to create a new migration and manually remove the drop table operations from it, but the next migration should be fine.

**Comment by pheuter** [comment]
@AndriySvyryd That's what I did:

1. Delete `Migrations/` folder and database file (Sqlite)
2. Execute `dotnet ef migrations add Base`
3. Execute `dotnet ef database update`
4. Execute `dotnet ef migrations add Second`

And it was after executing #4 that I got a migration with the `DropTable` again.

**Comment by AndriySvyryd** [comment]
@pheuter Could you open another issue and share a repro? The one in the initial comment here is fixed.

**Comment by pheuter** [comment]
@AndriySvyryd My mistake, I updated the SDK and `dotnet ef` cli tools, but forgot to update the project nuget ef core packages. Thanks again for looking into and fixing this issue 🙏
