### ISSUE TITLE
EFCore Many to many join tables are no longer mapped

### ISSUE THREAD

**Issue by ReStoreSupport** [dotnet/efcore#28296]
## File a bug

At [https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many) docs says 
**Simple join tables containing only two foreign key properties to other tables are no longer mapped to explicit entity types, but are instead mapped as a many-to-many relationship between the two joined tables.**

If I scaffold an existing sql server db using `dotnet ef dbcontext scaffold` command the many to many join tables are not scaffolded as entity class so I can't add more items in join. 

For ex. if I have a class admin and a class role In a many to many relationship how can I add new roles to user if I have no access to the join table ? in the code below the AdminsToRoles is not scaffolded

### Include your code

```
  public partial class Admin
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Admin()
        {
            Roles = new HashSet<Role>();
        }

        public virtual ICollection<Role> Roles { get; set; }
    }
```
```

    public partial class Role
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Role()
        {
            Admins = new HashSet<Admin>();
        }

        public virtual ICollection<Admin> Admins { get; set; }
    }
```

In the OnModelCreating function
```
entity.HasMany(d => d.Roles)
                    .WithMany(p => p.Admins)
                    .UsingEntity<Dictionary<string, object>>(
                        "MmCncAdminsToRole",
                        l => l.HasOne<Role>().WithMany().HasForeignKey("FkRId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AdminsToRoles_Roles"),
                        r => r.HasOne<Admin>().WithMany().HasForeignKey("FkAId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AdminsToRoles_Admins"),
                        j =>
                        {
                            j.HasKey("FkAId", "FkRId").HasName("PK_AdminsToRoles");

                            j.ToTable("AdminsToRoles", "cnc");

                            j.IndexerProperty<int>("FkAId").HasColumnName("fk_aId");

                            j.IndexerProperty<int>("FkRId").HasColumnName("fk_rId");
                        });

```
### Include provider and version information

EF Core version:  Entity Framework Core .NET Command-line Tools 6.0.6
Database provider: . Microsoft.EntityFrameworkCore.SqlServer
Target framework: 6.0

Operating system:
Visual Studio Community 2022 for Mac
Version 17.0.4 (build 23)

**Comment by ErikEJ** [comment]
EF Core Power Tools allows you to scaffold the join table (optional)

**Comment by ReStoreSupport** [comment]
> 

Hi ErikEJ, as you can see I'm working with VS Mac, I cannot instal .vsix plugin

**Comment by ReStoreSupport** [comment]
@ajcvickers 
admin.Roles.Add(new Role { Name = "Role1" );
actually adds new record to role table too.

if I want to add an exist role I had to query the role then add to the entity. this add a db hit that was not necessary previously

With EF6
`
var roleIdToAdd = 2;
var roleToAdd = context.Roles.First(x=> x.Id == 2);
admin.Roles.Add(roleToAdd);
context.SaveChanges();
`

With EF5
`
var adminId = 1
var roleIdToAdd = 2;
context.MmCncAdminsToRole.Add(new MmCncAdminsToRole{
   FKAId = adminId,
   FkRId = roleIdToAdd
});
context.SaveChanges();
`

the other mitigation is to manually add join tables every time I scaffold the db, you can imagine how many errors this can add.

Why not to introduce a new parameter to the `dotnet ef dbcontext scaffold ` to scaffold join table as EF5 ? for example `--include-join-table`
