### ISSUE TITLE
Allow passing in other arguments to msbuild when building project with dotnet ef.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#28306]
I would love to be able to define an special msbuild property ``IsScaffoldingWithDotNetEF`` to my projects to trap the case where the ``dotnet ef`` tool is used to scaffold.

To be able to pass in ``/p:IsScaffoldingWithDotNetEF=true`` to the invoked msbuild here https://github.com/dotnet/efcore/blob/main/src/dotnet-ef/Project.cs#L137-L173 (there might need to be other places to make changes to to be able to pass in those to msbuild/dotnet build however).

**Comment by AraHaan** [comment]
cc: @roji would you think this could be something to consider adding to where either the tool defining it for us or for us to be able to pass in manually so we can properly trap when the tool is being used other than assuming that ``Debug`` is the scaffolder?

**Comment by roji** [comment]
@AraHaan can you please provide more context on what you're trying to achieve, and what that MSBuild property would be used for?

**Comment by AraHaan** [comment]
Sure, I been wanting to be able to not assume that debug is the configuration where scaffolding is being run and instead rely on a property in which the scaffolder (or something that I) can define to use to detect the scaffolding happening.

Why is this needed? Well when scaffolding I depend on the template system in the 7.0.0-* preview releases of efcore, However when not scaffolding I want the 6.0.6 release of efcore to be used at runtime. By assuming debug, it will instead use the 7.0.0-* preview releases of efcore instead if I ever needed to go in and build a true debug build of my project. Also I might want to use it to know when I might actually want the deps file in my db project to be generated, but when scaffolding is not used to turn off generating that deps file to that project (since it's an library that gets consumed in the real entrypoint of my project)

**Comment by ajcvickers** [comment]
> ell when scaffolding I depend on the template system in the 7.0.0-* preview releases of efcore, However when not scaffolding I want the 6.0.6 release of efcore to be used at runtime. 

This is certainly not something we would recommend doing.

**Comment by ajcvickers** [comment]
@AraHaan if you're using 7.0 features, why not just use 7.0 for everything?

**Comment by ErikEJ** [comment]
Or why nor just create a seperate .net 7 project used for scaffolding?

**Comment by AraHaan** [comment]
but create an separate project for scaffolding would include additional maintenance costs over doing just a single project and having an msbuild property defined by the scaffolding tool to identify that scaffolding is being run..
