### ISSUE TITLE
GroupJoin leads to exception

### ISSUE THREAD

**Issue by verdysh** [dotnet/efcore#28318]
Here is the query which works:

EF Core version: 6.0.5
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6)
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by roji** [comment]
@verdysh the issue above is lacking the actual query. Please post a runnable, minimal sample and the full exception transaction which it causes.

**Comment by verdysh** [comment]
Sorry, this post was accidentally posted and closed immediately. I don't know how it happened. Here is correct post: https://github.com/dotnet/efcore/issues/28319
