### ISSUE TITLE
SqlClient version in EF Core.

### ISSUE THREAD

**Issue by janseris** [dotnet/efcore#28320]
## Ask a question

Hi, I am using EF Core 6 (6.0.3).
 I am trying to use it on Android.
  I am receiving errors seen where:
https://github.com/dotnet/SqlClient/issues/1656

We are talking in the thread with SqlClient crew about versions 4 and 5 but meanwhile EF Core 6 uses SqlClient 2.1.4 according to the dependency list in Visual Studio.
Is that intended and why is that and can that cause issues?

(my errors are not fixed in latest SqlClient (`Microsoft.Data.SqlClient`) anyways, but still, I am very surprised by this fact)

Edit: I can see tha there is something more to the versions, it's not necessary linear versioning, there are versions 2, 3, 4 and 5 (Preview). Is there anything special about these? (I suppose that there is)

My SQL Server version is 2012. Support ended 7/12/2022. Is there a list of supported/unsupported features of SqlClient for various SQL Server versions? I could not find these by quick look into the GitHub SqlClient repository info.

Thank you

**Comment by ErikEJ** [comment]
Yes, it is completely intended as 2.1 was the latest LTS release when EF Core 6 was released.
