### ISSUE TITLE
renaming entities while scaffolding in EF Core 6

### ISSUE THREAD

**Issue by kedarrkulkarni** [dotnet/efcore#28329]
*This might be a feature request and not support query, hence posting here

Looking for a suggestion about database first, Scaffold-Dbcontext utility in **EF Core 6**
All our database tables start with fixed prefix that I am keen to remove while entities are generated by scaffold I am looking to 

I have previously handled similar requirement using code similar to the one below, with **EF Core 3.0**

```
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Scaffolding.Internal;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;

namespace ProjectName.Entity.Models
{
    public class ProjectNameEntityTypeGenerator : CSharpUtilities
    {
        public override string Uniquifier(string proposedIdentifier, ICollection<string> existingIdentifiers)
        {
            var finalIdentifier = base.Uniquifier(proposedIdentifier, existingIdentifiers);

            //Prefix entity names with underscore
            if (finalIdentifier.ToLower().StartsWith("tbl"))
            {
                finalIdentifier = finalIdentifier.Replace("Tbl", string.Empty);
            }

            return finalIdentifier;
        }
    }

    public class CustomEFDesignTimeServices : IDesignTimeServices
    {
        //Used for scaffolding database to code
        public void ConfigureDesignTimeServices(IServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<ICSharpUtilities, ProjectNameEntityTypeGenerator>();
        }
    }
}
```

However, EF Core has completely changed the namespace/class structure and CSharpUtilities class is no longer available.

What is the alternate option available in EF Core 6 to control naming of the entities as part of entity generation? we certainly don't want to manually rename the entity names after generation as it's not very productive and also because we want to add more options over naming of auto generated entities.

### Include provider and version information

EF Core version: 6
Database provider: (e.g. Oracle.EntityFrameworkCore)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022)

**Comment by ErikEJ** [comment]
You can do regex based renaming with EF Core Power Tools.

**Comment by AndriySvyryd** [comment]
This will be supported in 7.0 with https://github.com/dotnet/efcore/issues/4038
