### ISSUE TITLE
Problem with setting cte max recursion depth value using raw sql

### ISSUE THREAD

**Issue by ragi-vuedata** [dotnet/efcore#28336]
Not able to set the cte max recursion depth value using raw sql with db parameterization.

I am using MySql database and have few programs which uses recursive cte's. I am trying to set the max cte recursion depth value from the code using raw sql with db parameters but its not working as expected.
I am following https://dev.mysql.com/doc/refman/8.0/en/with.html#common-table-expressions-recursion-limits to set the max cte recursion value as part of the cte query.

Here is the code for the same - 

```C#
var cteString = @"WITH RECURSIVE cte (n) AS
(
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM cte
)
SELECT /*+ SET_VAR(cte_max_recursion_depth = {0}) */ * FROM cte";

result = await this.DbContext
                        .Set<TEntity>()
                        .FromSqlRaw(cteString, new object[] { 10 })
                        .CountAsync(cancelToken) > 0;

```
For some reason, its not working (no errors thrown, but default cte_max_recursion_depth is used instead). It works just fine if I hardcode the max recursion depth value instead of parametrizing it. It also works if I use interpolated string. 
I really want to use parametrized way to set the value as its a recommended approach. Any help would be appreciated.

**Provider details -**
EF Core version: 6.0.2
Database provider: (e.g. Pomelo.EntityFrameworkCore.MySql)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.0.3)

**Comment by roji** [comment]
@ragi-vuedata I'd advise turning on SQL logging, along with [EnableSensitiveDataLogging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#sensitive-data), to see exactly what's being sent to MySQL; that would allow isolating whether EF Core is sending the SQL you think it should be or not.

/cc @lauxjpn

**Comment by ragi-vuedata** [comment]
Hi @roji, thanks for the advice. 
I have enabled the sensitive logging and this is what's being logged. 
```C#
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (74ms) [Parameters=[p0='6'], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)
FROM (
    SELECT t.* FROM
                    (WITH RECURSIVE cte (n) AS
                    (
                      SELECT 1
                      UNION ALL
                      SELECT n + 1 FROM cte
                    )
                    SELECT /*+ SET_VAR(cte_max_recursion_depth = @p0) */ * FROM cte)
) AS `d`
```

I guess, @p0 value is actually put in as string char something like - `SET_VAR(cte_max_recursion_depth = '6'` 
As per the documentation int values are used in the examples as db paramters, not sure why its not working here!

**Comment by roji** [comment]
@ragi-vuedata so it seems that EF Code is doing it's job properly and parameterizing the SQL; from that point it's a question of whether MySQL supports parameterizing cte_max_recursion_depth as you're trying to do. I'd advise asking in a MySQL forum, or possibly posting an issue on https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql (though I don't think that's the right place either, as a general MySQL question /cc @lauxjpn). Or you can just choose to embed the number directly without parameterizing.

I'm going to go ahead and close this as external to EF Core, but feel free to continue posting questions/comments here.

**Comment by lauxjpn** [comment]
@ragi-vuedata As far as I can see, the following code does not evaluate any user variables if executed by MySQL (without any EF Core or Pomelo involvement):

```sql
set @maxDepth = 10;

WITH RECURSIVE cte (n) AS
(
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM cte
)
SELECT /*+ SET_VAR(cte_max_recursion_depth = @maxDepth) */ * FROM cte;

/*
Error Code: 3636. Recursive query aborted after 1001 iterations. Try increasing @@cte_max_recursion_depth to a larger value.
*/
```

Looks like user variables/parameters are not supported in that expression by MySQL and you will need to inject the raw value in the SQL string.
