### ISSUE TITLE
Why type of DbSet property at runtime is shown as of type InternalDbSet1?

### ISSUE THREAD

**Issue by verdysh** [dotnet/efcore#28355]
I have MyDbContext which was generated from database with Scaffold-DbContext:

```
public partial class MyDbContext : DbContext
{
	public MyDbContext()
	{
	}

	public MyDbContext(DbContextOptions<MyDbContext> options): base(options)
	{
	}

	public virtual DbSet<Tenant> Tenant { get; set; } = null!;
}
```

Here is a code snippet:

```
var dbContextType = _db.GetType();
var realTenantDbSetType = _db.GetType().GetProperties().Where(p => p.PropertyType.FullName.Contains("Entities.Tenant")).First().GetMethod.ReturnType;
var tenantDbSetType = _db.Tenants.GetType();
```

- dbContextType is of type MyDbContext
- realTenantDbSetType is of type Microsoft.EntityFrameworkCore.DbSet1[[Data.Entities.Tenant
- tenantDbSetType is of type Microsoft.EntityFrameworkCore.Internal.InternalDbSet1[[Data.Entities.Tenant

Based on this it looks like something changed my MyDbContext type at runtime. Is it true?
If true, where and how does this "magic" happen?
if it isn't true, how it's possible that tenantDbSetType is of type InternalDbSet1 and not of type DbSet1?

--
EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: Windows
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@verdysh Because `DbSet` is an abstract base type. `InternalDbSet` is the concrete type created at runtime when a `DbSet` is needed. This is normal C# stuff; nothing magic here.

**Comment by verdysh** [comment]
@ajcvickers, that was a stupid question. The head does not think today. I'm sorry.
