### ISSUE TITLE
Entity is not updated using new context instance from new service provider scope, InMemoryProvider

### ISSUE THREAD

**Issue by khdevnet** [dotnet/efcore#28362]
# Bug Details
1. Register DbContext using In memory provider  sc.AddDbContext<TestDbContext>(b => b.UseInMemoryDatabase("test"));
2. Build provider
3. Create a scope1 and get DbContext ctx1
4. Add new item to DbSet in ctx1 and save changes
5. Create scope2 and get new DbContext ctx2
6. Do updated of entity in ctx2 and save
7. Get entity from ctx1 using id

Actual:
 Entity from ctx1 not updated and contains the  old value
Expected:
 Entity from ctx1 updated and contains new value

# Example

```C#

public class UnitTest1
{

    [Fact]
    public void Test1()
    {
        var sc = new ServiceCollection();
        sc.AddDbContext<TestDbContext>(b => b.UseInMemoryDatabase("test"));

        var sp = sc.BuildServiceProvider();
        var scope1 = sp.CreateScope();
        var ctx1 = scope1.ServiceProvider.GetService<TestDbContext>();
        var id = Guid.NewGuid();

        ctx1.Add(new Customer() { Id = id, Name = "init name" });
        ctx1.SaveChanges();

        var scope2 = sp.CreateScope();

        var ctx2 = scope2.ServiceProvider.GetService<TestDbContext>();
        var myCustomer = ctx2.Customers.Find(id);

        myCustomer.Name = "updated";

        ctx2.Update(myCustomer);
        ctx2.SaveChanges();

        var updated = ctx1.Customers.Find(id);

        Assert.Equal("updated", updated.Name);
    }
}

public class TestDbContext : DbContext
{
    public TestDbContext(DbContextOptions<TestDbContext> options) : base(options)
    {

    }

    public DbSet<Customer> Customers { get; set; }
}

public class Customer
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public string Name { get; set; }
}
```

# Provider and version information

EF Core version:
    Microsoft.EntityFrameworkCore.InMemory : 6.0.6
DependencyInjection:
    Microsoft.Extensions.DependencyInjection: 6.0.0
Operating system: Windows 11
IDE: Visual Studio Professional  2022 17.1.2

**Comment by ajcvickers** [comment]
@khdevnet This is by-design. The first context has a cached entity instance which is therefore used instead of getting the updated row from the database. See [Tracking vs. No-Tracking Queries](https://docs.microsoft.com/en-us/ef/core/querying/tracking#tracking-queries) for more information.
