### ISSUE TITLE
Concurrency token not working when Tracking is activated

### ISSUE THREAD

**Issue by FenderFred** [dotnet/efcore#28379]
## Bug

When I Attach my entity and updated it with the wrong DateTime for concurrency (DtTimestamp different that the one in the database for this row), the row is updated whenever the DtTimestamp value.

If I do the same without attach the entity (no tracking enabled), the concurrency is managed correctly and send me the DbUpdateConcurrencyException.

```C#
 modelBuilder.Entity<TestTable>(entity =>
            {
                entity.ToTable("Test_Fred");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.DtTimestamp)
                    .HasColumnType("datetime")
                    .HasColumnName("Dt_Timestamp")
                    .IsConcurrencyToken();

                entity.Property(e => e.Nom)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

// Working (no tracking set at dbContext)
var x = await UnitOfWork.DbContext.Set<TestTable>().Where(x => x.Id == 1).SingleAsync();
x.Nom = "Tremblay";
x.DtTimestamp = DateTime.Now;

UnitOfWork.DbContext.Set<TestTable>().Update(x);
await UnitOfWork.SaveChangesAsync().ConfigureAwait(false);

// Not working (no tracking set at dbContext, tracking with attach)
var x = await UnitOfWork.DbContext.Set<TestTable>().Where(x => x.Id == 1).SingleAsync();

UnitOfWork.DbContext.Set<TestTable>().Attach(x);
x.Nom = "Tremblay";
x.DtTimestamp = DateTime.Now;

await UnitOfWork.SaveChangesAsync().ConfigureAwait(false);
```

### Provider and version information

EF Core version: 6.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10 21H2
IDE: Visual Studio 2022 17.2.5

**Comment by ajcvickers** [comment]
@FenderFred The concurrency check uses the original values of the entity--that is, the values that were in the database when the entity was queried. See discussion here: https://github.com/dotnet/efcore/issues/27865#issuecomment-1147298618. Better documentation for this is being tracked by https://github.com/dotnet/EntityFramework.Docs/issues/860.
