### ISSUE TITLE
How to pass the args values to IDesignTimeDbContextFactory CreateDbContext method in EFCore

### ISSUE THREAD

**Issue by goldytech** [dotnet/efcore#28375]
As per this [blog post](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#args) `CreateDbContext(string[] args)` method can accept the parameters from `dotnet ef` cli.

This is my code; I want to pass the connection string from the cli as the custom argument.

```
public AppDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<AppDbContext>();
        var connStr = args[0];

        optionsBuilder.UseSqlServer(connStr);

        return new AppDbContext(optionsBuilder.Options);
    }
``` 

Now when I'm passing this argument from the cli with the command
`dotnet ef database update -- --constr Server=localhost;Database=DotNetSixPoc2;User Id=sa;Password=P@ssw0rd!; `

I get the following error.

> Format of the initialization string does not conform to specification starting at index 0.

Please help. Thanks

**Comment by ajcvickers** [comment]
@goldytech Does it work if you quote the string? For example:

```
dotnet ef database update -- --constr "Server=localhost;Database=DotNetSixPoc2;User Id=sa;Password=P@ssw0rd!;"
```

**Comment by goldytech** [comment]
No, already had tried this.

**Comment by goldytech** [comment]
Ok finally after trial and error got this working. The correct syntax for it is `dotnet ef database update -- 'Server=localhost;Database=DotNetSixPoc2;User Id=sa;Password=P@ssw0rd!;`

In a nutshell, you don't require the name of the parameter. The official document is misleading.
