### ISSUE TITLE
Dictionary property is being stored as an empty dictionary in cosmos db?

### ISSUE THREAD

**Issue by Keerthikan** [dotnet/efcore#28374]
I've been having some issues with storing my dictionary into cosmos db via Ef core. 
My situation is similar to this SO post : https://stackoverflow.com/questions/64982780/dictionary-property-in-cosmos-db-using-ef

### Include your code

I have a datacontract as such 

```C#
    public class DbModel
    {
        public Guid Id { get; set; }

        public string FormName { get; set; }
        
        public Dictionary<string, object> Form { get; set; }
    }
```

and store it into the database as such 

```C#
                  IEnumerable<DbModel> forms = jsonResponse.Select(x => new DbModel()
                    {
                        Id = new Guid(x["guid"].ToString()),
                        FormName = x["name"].ToString(),
                        Form = x
                    });
                dbContext.AddRange(forms);
                dbContext.SaveChanges();
```         
                
what I seen in CosmosDb is this though: 

```
    "Id": "000f8fa2-f0db-484c-869b-cfd864391e2f",
    "Discriminator": "DbModel",
    "FormName": "Some name",
    "id": "DbModel|000f8fa2-f0db-484c-869b-cfd864391e2f",
    "Form": {},
    "_rid": "58gcAMf4b08BAAAAAAAAAA==",
    "_self": "dbs/58gcAA==/colls/58gcAMf4b08=/docs/58gcAMf4b08BAAAAAAAAAA==/",
    "_etag": "\"bf0005bf-0000-0d00-0000-62c55e700000\"",
    "_attachments": "attachments/",
    "_ts": 1657101936
```

An empty `form`, which should at least contain a `Guid `and a `FormName`. 

But according to the github issue linked in the SO post (https://github.com/dotnet/EntityFramework.Docs/issues/2895), should this issue have been resolved in version 5?
so why am I having it in version 6?

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Cosmos (6.0.6) and Microsoft.EntityFrameworkCore (6.0.6) 
Target framework: .NET 6.0
Operating system:
IDE: Visual Studio 2022

**Comment by AndriySvyryd** [comment]
Only collections of primitive types are supported by EF Core 6, So `DictionaryList` needs to be typed as `Dictionary<string,string>`

`Dictionary<string,object>` is recognized as a nested entity type, you could use it, but you'd need to explicitly configure all the keys that it can contain:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<TestDictionary>()
        .OwnsOne(t => t.DictionaryList, c =>
        {
            c.Property<string>("Type");
            c.Property<string>("TagName");
        });
}
```

**Comment by lukelimasilva** [comment]
Hi @AndriySvyryd ! I have a question. Eveytime I try to map a list of complex type, the same problem mentioned above occurs. But, I tried to add a collection of complex types without mapping it using entity and everything worked! Entity knew how to create the document and retrieve it without the mapping. 

Well, since entity knows how to do it (or at least it seemed to me that it knows), is there any way to map the collection of complex type itself without having to use a dictionary?
