### ISSUE TITLE
How to map and use SQL Server user defined function with EF Core when using value objects?

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/efcore#28393]
I want to call a user defined SQL SERVER function and use as parameter a property that is a value object. The EF Core documentation shows only samples with primitive types. I can't manage to create a working mapping. 

The entities of our business domain need to support multi-language text properties. The text is provided by the user. We created a multi-language value object (ML\<T\>) that internally uses a dictionary. In the database multi-language properties are saved as JSON in a nvarchar(max) column. An EF Core converter handles the conversion to and from string data type. 

This is a simplified country entity just to comprehend the test code below:

    public class Country : VersionedEntity
    {
       public string CountryId { get; set; }
       public ML<CountryName> Name { get; set; }
    }

A sample row in the database looks like this:

> DEU	|
> [{"language":"de-DE","value":"Deutschland"},{"language":"en-US","value":"Germany"},{"language":"it-IT","value":"Tedesco"}]

Text (i.e. a product description) might not be translated in all supported languages. Therefore the users can define a language preference list. The best matching language will be displayed.

Since paging requires sorting in the database, I created a user defined function `GetLanguage` in SQL SERVER that returns the best matching language for each row and allows sorting for each user's language preference.

I declared the function in the DbContext

    public string? GetLanguage(string json, string preferredLanguages)
        => throw new NotSupportedException($"{nameof(GetLanguage)} cannot be called client side");

and mapped it

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDbFunction(typeof(AccountsDbContext)
            .GetMethod(nameof(GetLanguage),
            new[] { typeof(string), typeof(string) })!);
    }

I tried to call the function in a test LINQ query

    string preferredLanguages = "de-DE,en-US,fr-FR";    
    List<string?> list = _dbContext.Country.Select(c => _dbContext.GetLanguage(c.Name, preferredLanguages)).ToList();

It does not compile. c.Name creates an error, because it is of type ML\<CountryName\> and not of type string as the first parameter of the function is defined.

I was expecting that EF Core would not convert the property, because the function runs on the server and just needs to use the table column of the database. It should create SQL like

    Select dbo.GetLanguage(name, 'de-DE,en-US,fr-FR');

Is there a way to tell EF Core to just use the table column? 

For testing I tried to change the function declaration to

    public string? GetLanguage(ML<CountryName> json, string preferredLanguages)
        => throw new NotSupportedException($"{nameof(GetLanguage)} cannot be called client side");

and the mapping to

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDbFunction(typeof(AccountsDbContext)
            .GetMethod(nameof(GetLanguage),
            new[] { typeof(ML<CountryName>), typeof(string) })!);
    }

The code compiled, but I get a runtime error. 

> System.InvalidOperationException : The parameter 'json' for the
> DbFunction
> 'App.Accounts.Persistence.AccountsDbContext.GetLanguage(App.SharedKernel.Domain.ML<App.SharedKernel.Domain.CountryName>>,string)'
> has an invalid type 'ML\<CountryName\>'. Ensure the parameter type can
> be mapped by the current provider.

The types are identical, one just is fully qualified and the other not. I don't understand why this error occurs and how I can fix it.

It seems a general issue when a value object with a converter is used. EF Core should create SQL that uses the DB function and the table column, because everything should run on the server. 
How can I achieve this?

**Comment by KillerBoogie** [comment]
My colleague found a first workaround using a cast to `object `and `string` to satisfy the compiler:

```
string preferredLanguages = "de-DE,en-US,fr-FR";    
List<string?> list = _dbContext.Country.Select(c => _dbContext.GetLanguage((string)(object)c.Name, preferredLanguages)).ToList();
```

EF Core produced the following SQL code:

```
SELECT [dbo].[GetLanguage](CAST([c],[CountryName] AS nvarchar(max), @__preferredLanguages_1
```

The cast is unnecassary, because CountryName is of type nvarchar(max), but it produces the desired result. Is there any option that avoids the cast?

**Comment by KillerBoogie** [comment]
Thanks for your answer. I will try out the options. 

The parameter has a proper type mapping with a value converter. General reading and writing to the property work. As you can see in the error message above, when I use the multi-language type the type with full namespace is compared to the same one without the namespace. Still EF Core thinks they don't match.

**Comment by KillerBoogie** [comment]
I was trying to use:

```
    modelBuilder.HasDbFunction(typeof(AccountsDbContext)
        .GetMethod(nameof(GetLanguage), new[] { typeof(ML<CountryName>), typeof(string) })!)
        .HasParameter("json").HasStoreType("varchar(max)")
        .HasParameter("preferredLanguages");
```

The code does not compile. I'm getting an error on the 2nd HasParameter call:

> 'DbFunctionParameterBuilder' does not contain a definition for 'HasParameter' and no accessible extension method 'HasParameter' accepting a first argument of type 'DbFunctionParameterBuilder' could be found (are you missing a using directive or an assembly reference?).

It seems HasParameter needs a DbFunctionBuilderBase. Is there any good description, blog, tutorial, examples where I can learn more about the usage?

**Comment by roji** [comment]
Yep, make sense (wrote that blindly).

Leaving open to possibly track extended parameter configuration APIs for type mappings.

**Comment by KillerBoogie** [comment]
I just discovered another issue. Our multi-langage type ML is generic. With the above workaround, I would need to define the function for each ML<T>, if this is even possible.

**Comment by roji** [comment]
Yep, object should work fine, or you can have your Generic ML extend a non-generic one (or implement an interface), and accept that. That would constrain your method to only be used with ML.

**Comment by ajcvickers** [comment]
May be covered by #28393. May want to add something to #4319.

/cc @roji

**Comment by ajcvickers** [comment]
Duplicate of #4978
