### ISSUE TITLE
Untranslated aggregate queries cause incorrect SQL instead of translation failure

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28409]
It seems that if GroupBy is used with an unknown aggregate function, instead of a translation failure we're generating incorrect SQL. To see this, comment out SqlServerStringAggregateMethodTranslator in SqlServerAggregateMethodCallTranslatorProvider, and try running test String_Join_over_non_nullable_column. This causes the following to get generated:

```sql
SELECT [t].[City], [c0].[CustomerID]
FROM (
    SELECT [c].[City]
    FROM [Customers] AS [c]
    GROUP BY [c].[City]
) AS [t]
LEFT JOIN [Customers] AS [c0] ON [t].[City] = [c0].[City]
ORDER BY [t].[City]
```

/cc @smitpatel

**Comment by smitpatel** [comment]
That happens because `string.Join` gets client evaluated in top level projection.

**Comment by roji** [comment]
Oops, of course...

**Comment by roji** [comment]
BTW aggregate methods provide a good argument against client eval in the top-level projection. We usually say that it's OK to client-eval there because we unlike with e.g. filter, we don't transfer lots of unneeded data. But since an aggregate function reduces an entire column to a single value, evaluating it on the server or on the client can have quite a big impact. A motivation for #28155.

**Comment by smitpatel** [comment]
For our defined aggregate function, it may be fine to throw. For built-in ones, it may be a breaking change because we evaluated them in client before.

**Comment by roji** [comment]
Yeah, for sure. I mean, it's not like we're going to change EF to not support client eval in top-level projection; just possibly more motivation to do #28155, is all.
