### ISSUE TITLE
EF Core probably should have an option to not log `OperationCanceledException`s

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/efcore#28406]
I have a code sample like this:
```cs
try
{
  await db.SaveChangesAsync(cancellationToken);
}
catch (OperationCanceledException)
{
 // my custom logic to handle cancels
}
```
This setup, however, doesn't stop EF Core and it still logs `OperationCanceledException` to the console as a `fail` with the whole stack trace. I verified this by putting a break point at the first statement in the `catch` block. When break point is hit, the log entry is already there. I've found it rather inconvinient, because I now have to either live with an overflown by this exceptions log or disable **all** errors from `Microsoft.EntityFrameworkCore.Update`, so if something bad happens, it will not log the really valuable exception. It would be nice IMO if there is a flag, that indicates whether EF Core logs `OperationCanceledException`s (and maybe `TaskCanceledException`s) or not. It should probably be enabled by default, because these exceptions are usually used in a normal non-exceptional code pathes

**Comment by ajcvickers** [comment]
Duplicate of #19526.

**Comment by DoctorKrolic** [comment]
Nice!
