### ISSUE TITLE
Scaffold non-nullable columns as C# 11 required properties

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28400]
C# 11 has required properties ([specs](https://github.com/dotnet/csharplang/blob/main/proposals/required-members.md)), which users must initialize (in an object initializer). Among other things, this solves the problem that non-nullable reference properties must currently be initialized in the constructor, or the compiler issues a warning.

We could scaffold non-nullable columns as required non-nullable properties (when the property is a reference type and NRT is enabled), by default. We currently scaffold a bang initialization instead. So instead of:

```c#
public class Blog
{
    public string Name { get; set; } = null!;
}
```

... we'd scaffold:

```c#
public class Blog
{
    public required string Name { get; set; }
}
```

Note that this may be inappropriate for scenarios where the user instantiates early, and only later initializes some property which is mapped to a non-nullable column; after all, the database column is the non-nullable thing, but it may be OK for the property to temporarily contain null, until SaveChanges is called. So if we do this, some users will need to edit their templates etc.

**Comment by stevendarby** [comment]
Would you put `required` on required navigation properties too? This would seem wrong, as you should be allowed to only set the scalar property as a way of linking to another entity on save. Therefore I think you would still need the `bang!` solution for required navigations, leading to a mix of the two solutions in the entity.

I personally think `required` is going to be most useful for `init` properties and properties with `set` aren't really the intended target of this new feature.

**Comment by roji** [comment]
> This would seem wrong, as you should be allowed to only set the scalar property as a way of linking to another entity on save.

It's worth remembering that what we decide in scaffolding is just a default - users are free to change things, and starting with 7 they would even be able to change the templates themselves. Regarding your scenario, since setting the scalar property (the foreign key) is relatively rare practice - compared to just setting the property - it still makes sense to me as the default. 

However, even more important is the question of circular required navigations: these would be impossible to initialize in one go (the same issue exists with constructor initialization). This is already a tricky situation regardless of EF: the enforcing of the constraints must be deferred to the end of the transaction. We'd ideally detect this situation and special-case it, but again, I wouldn't let this specific case change our overall default strategy here.

Am putting `needs-design` on this to discuss when the time comes.

**Comment by stevendarby** [comment]
I don’t think setting the scalar is that rare. In web APIs it’s not unusual to have an endpoint like `POST /authors/1234/books`

You would create a new Book from the request body and set the foreign key to Author. You don’t want to query the full Author entity if you can avoid it. 

I understand that you’re discussing the default behaviour and that people would be free to edit, I just wanted to give feedback that I think it’s a bad default :)

**Comment by roji** [comment]
Thanks @stevendarby, we'll definitely take this into account when discussing. Also, maybe having scalar properties required but not navigations is reasonable - I'm not sure that different strategies here are a bad thing.

**Comment by ajcvickers** [comment]
Note from triage: we don't believe there is a close enough match in semantics to do this by default. The T4 template can be edited to add it in where desired.
