### ISSUE TITLE
Entity Framework core error issue with .netcore 6.0 version

### ISSUE THREAD

**Issue by vk77093** [dotnet/efcore#28413]
I Am getting the following error while try to add the package and apart from that not able to add the new scaffold items, getting the error

Severity Code Description Project File Line Suppression State
Error NU1202 Package Microsoft.EntityFrameworkCore.SqlServer 6.0.6 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.EntityFrameworkCore.SqlServer 6.0.6 does not support any target frameworks.

**Comment by roji** [comment]
@vk77093 please post your full csproj and dotnet SDK versions, you may have a misconfigured project our an outdated SDK.

**Comment by vk77093** [comment]
@roji  Please find the attached file . I Have cross checked the my asp.net core version it is already 6.0 and apart from that i had the latest Visual Studio. Find the Image
![Screenshot (151)](https://user-images.githubusercontent.com/25607218/178443179-2398286a-e434-4b1c-9c72-2bd18f4cb57c.png)


[IdentityTestProject_IssueSend.zip](https://github.com/dotnet/efcore/files/9090894/IdentityTestProject_IssueSend.zip)

**Comment by vk77093** [comment]
Dear Team

Please find the attached file . I Have cross checked the my asp.net core
version it is already 6.0 and apart from that i had the latest Visual
Studio. Find the Image
[image: Screenshot (151).png]

Thanks and Regards
Vijay Kumar

**Comment by roji** [comment]
After downloading your repro, I indeed saw the error occuring. However, once I deleted the bin and obj directories, everything started working fine. There must have been some leftover issue from a previous version of the project.
