### ISSUE TITLE
Custom DbFunctions extension methods reject the DbFunctions parameter (“parameter has invalid type DbFunctions”)

### ISSUE THREAD

**Issue by poke** [dotnet/efcore#28419]
I would like to create a custom DbFunction so that I can write `EF.Functions.Test(…)` within my queries and have it translated by my translation logic. However, when I try to declare my custom DbFunction as an extension method, with the `DbFunctions` object as the first parameter, I get the following exception:

> Unhandled exception. System.InvalidOperationException: The parameter `'_'` for the DbFunction `'DbFunctionsExtensions.Test(Microsoft.EntityFrameworkCore.DbFunctions,string)'` has an invalid type `'DbFunctions'`. Ensure the parameter type can be mapped by the current provider.
>   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateDbFunctions(IModel model, IDiagnosticsLogger\`1 logger)
>   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger}`1 logger)

This is the shortened `DbFunctionsExtensions` class that I am trying to use to declare my own extension methods:

```csharp
public static class DbFunctionsExtensions
{
    public static string Test(this DbFunctions _, string param)
        => param;

    public static void RegisterFunctionsExtensions(this ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDbFunction(typeof(DbFunctionsExtensions).GetMethod(nameof(Test)))
            .HasTranslation(TranslateTest);
    }

    public static SqlExpression TranslateTest(IReadOnlyList<SqlExpression> args)
        => args[1];
}
```

As you can see, the `Test` method is an extension method on the `DbFunctions` type, which makes it possible to call it as `EF.Functions.Test()` inside expressions. But during model validation, this parameter is rejected because it has no configured type mapping, even though I don’t want to use it for the actual translation:

https://github.com/dotnet/efcore/blob/796d2f8b516781d64bbdf4c21b0163de9fa56ab8/src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs#L151-L158

To work around that, I can actually add a random store type by adding `.HasParameter("_").HasStoreType("none")` to the `HasDbFunction` call. This works but feels very strange and hacky.

What of course also works is declaring the method without the `DbFunctions` parameter, and calling it explicitly on the static class using `DbFunctionsExtensions.Test(…)`. Then the function also works.

Since the built-in `DbFunctions` extension methods are configured using `IMethodCallTranslator`s (e.g. the [`LikeTranslator`](https://github.com/dotnet/efcore/blob/796d2f8b516781d64bbdf4c21b0163de9fa56ab8/src/EFCore.Relational/Query/Internal/LikeTranslator.cs)), I am wondering if the `HasDbFunction` is actually the correct way to declare extension methods on the DbFunction type. Unfortunately, there isn’t much documentation on DbFunctions and the only examples were direct translations to SQL functions and they were also declared on the DbContext instead.

So is declaring custom extension methods on `DbFunctions` actually supported and if so what would be the right approach here to handle the `DbFunctions` parameter in the method setup?

---

Here is the rest of the console application that can be used to reproduce the error, depending only on Microsoft.EntityFrameworkCore.Sqlite version 6.0.6:

```csharp
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using Microsoft.EntityFrameworkCore.Sqlite;

var options = new DbContextOptionsBuilder<TestContext>().UseSqlite("Data Source=test.db").Options;
using var db = new TestContext(options);
db.Database.EnsureCreated();

// does not make sense but is also not required to; this just triggers the model validation
var result = db.Models.Select(x => EF.Functions.Test(x.Name)).ToArray();

public class TestContext : DbContext
{
    public DbSet<Model> Models { get; set; }
    public TestContext(DbContextOptions<TestContext> options) : base(options) { }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.RegisterFunctionsExtensions();
    }
}

public class Model
{
    public int Id { get; set; }
    public string Name { get; set; }
}

// (include the DbFunctionsExtensions declaration here)
```

**Comment by roji** [comment]
Extension methods over EF.Functions are meant to be done by database providers (e.g. for SQL Server, SQLIte); they implement IMethodCallTranslators which do the translations. All that is the "tool chain" for providers, and not meant to be used by users; that is also why IMethodCallTransators aren't well-documented.

Users, on the other hand, have user-defined function mappings via HasDbFunction ([docs](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping)). This is supposed to be a simpler API, that's more suitable for users mapping a .NET function to a SQL one, without having to deal with some of the more complex aspects (e.g. type mappings). That also means that a dummy parameter such as the DbFunctions type causes issues.

I'd recommend putting your function somewhere else - not on EF.Functions, and using HasDbFunction as documented to map it. You do have the option of going down the IMethodCallTranslator route, but that's going to be significantly more complicated; I'd definitely advise against it if the only goal here is to have your function under EF.Functions.

**Comment by poke** [comment]
@roji Alright, thank you! That certainly clarifies my assumption that extending EF.Functions does not appear to be the right thing to do here. Though—if I may suggest—I guess the validation could probably be adjusted to simply skip a `DbFunctions` type parameter to make this work.

Alternatively, maybe the error message could be adjusted to clarify that extending `DbFunctions` is not recommended when using `HasDbFunction`.

> [HasDbFunction] is supposed to be a simpler API, that's more suitable for users mapping a .NET function to a SQL one

Unfortunately, I cannot map directly to an existing SQL function (and I also don’t have the desire to provide a custom SQL function that I could map to 😅). But using `HasDbFunction` together with a translation function via `HasTranslation` that then returns a custom SqlExpression does work just fine for me.

I made my function available on a different static class (without using an extension method) and I’m happy with that. I just have some struggles naming that class since I would really like to use `DbFunctions` but that name is already squatted by EF 😜

Thanks for the quick clarifications! 😊 I’ll stay away from `IMethodCallTranslator` (for now at least 😁)

**Comment by thomaslevesque** [comment]
TBH, I don't really see a good reason why this doesn't work.

An extension method is just syntax sugar for a static method. And as long as we don't use the DbFunctions argument in the translation, it shouldn't matter.

I understand making this scenario work won't be a priority, but it feels like there's very little missing for it to work. Maybe ValidateDbFunctions could just ignore the first parameter of type DbFunctions if the method is an extension method?

**Comment by roji** [comment]
I agree it's probably not very complicated to make work, but it's also not nothing, and there's virtually no need for it. Given everything else that we have going on, it's simply not something that makes sense investing time in.

**Comment by thomaslevesque** [comment]
Got it.

Anyway, now with extension members in C# 14, there's an even simpler approach: you can expose the method directly on `EF`, rather than on `EF.Functions`.

```csharp
public static class MyDbFunctions
{
    extension(EF)
    {
        public static bool MyFunction(string arg) => throw new NotSupportedException();
    }
}
```

There's no extraneous DbFunctions parameter, it's a "normal" static method, so it just works. It just happens to be callable with `EF.MyFunction(arg)` instead of `MyDbFunctions.MyFunction(arg)`.

**Comment by roji** [comment]
Good point @thomaslevesque with the static extension method. Though the original intent with EF (and EF.Functions) was really to have provider-specific stuff there, rather than arbitrary functions that the user adds; that's another reason to put user-defined functions on the user's DbContext or whatever other type that the user owns. I think there's some value in maintaining that distinction (though it's not huge, I admit).

**Comment by stevenbenitez** [comment]
Here is the approach I have used in several applications.

```csharp
// ReSharper disable once CheckNamespace
namespace Microsoft.EntityFrameworkCore;

/// <summary>
/// More EF.Functions that are unique to this application.
/// </summary>
// ReSharper disable once InconsistentNaming
public static class MoreEF
{
    public static class Functions
    {
        // your method stubs go here
    }
}
```
