### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one element

### ISSUE THREAD

**Issue by damccull** [dotnet/efcore#2842]
Hi all you smart people,

I have an issue. Using EF7 beta 6

``` csharp
        public IViewComponentResult Invoke(/*ICollection<Mission> missions*/) {
            var ticks = SystemClock.Instance.GetCurrentInstant().Ticks;
            var missions = db.Missions
                .Include(m => m.Owner)
                .Include(m => m.Players)
                    .ThenInclude(p => p.User)
                .Include(m => m.Activity)
                    .ThenInclude(a => a.Game)
                .Where(m => m.Scheduled >= ticks)
                .Where(m => m.Players.Count < m.Activity.Slots)
                .OrderBy(m => m.Scheduled)
                .Take(4).ToList();
            return View(missions);
        }
```

The code above produces `System.InvalidOperationException: Sequence contains more than one element` on the ToList() and I don't think it should. See the stack trace at https://gist.github.com/damccull/0ea09acbeb668d72f465

The gist also contains each of the models, the applicationdbcontext, and anything else I thought may be relevant to this...

I'd like to know why this is, and how to fix it if possible. I've been told my code is horribly inefficient, but optimization is something I'll tackle after I get it working.

I'll post anything else you need, but I'm not sure what that might be, so please ask away.

**Comment by damccull** [comment]
I have determined the culprit is `.Where(m=>m.Players.Count < m.Activity.Slots)`

This causes exception.
```csharp
.Where(m => m.Scheduled >= ticks)
.Where(m => m.Players.Count < m.Activity.Slots)
```

This does not.
```csharp
.Where(m => m.Scheduled >= ticks)
```

Am I just doing it wrong or is this a bug?

**Comment by rowanmiller** [comment]
@damccull traversing navigation properties in LINQ queries is being implemented at the moment. Some scenarios are enabled in our working code base, but not in Beta 6. Work is tracked by #325.
