### ISSUE TITLE
How to prohibit cross aggregate navigation properties?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#28422]
I would like to prohibit entities to contain navigation properties (that is references) to other aggregates.

I guess, I need to enforce it with implementation of `IModelValidator` , but can I actually do it without implementing custom provider?

**Comment by roji** [comment]
You can use ReplaceService in your context configuration to replace the provider's IModelValidator with your own, which would extend the provider's and add any arbitrary checking.

**Comment by voroninp** [comment]
Can I somehow just wrap it, so it's composition instead of inheritance?
I would like to avoid being dependent on concrete type.

```
class MyModelValidator : IModelValidator
{
    public MyValidator(IModelValidator providerModelValidator)
    {
    }
}
```
