### ISSUE TITLE
Remove "stable" test packages from Myget feed

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2843]
The packages EntityFramework.Core.FunctionalTests and EntityFramework.Relational.FunctionalTests appear as version 1.0.0 (by mistake), but Nuget seems to prefer these  "Stable" packages over the latest.
The feed is here: https://www.myget.org/gallery/aspnetvnext

**Comment by rowanmiller** [comment]
@Eilon could you take care of this for us?

**Comment by Eilon** [comment]
Will do.

**Comment by Eilon** [comment]
Deleted. It'll take MyGet a few minutes to purge from its cache.
