### ISSUE TITLE
Should `addAsync` also get default sql values?

### ISSUE THREAD

**Issue by barahonajm** [dotnet/efcore#28446]
This is more a question than a feature request, I set-up some default values via `HasDefaultValueSql` for an entity and I am adding a new one to DBContext via `AddAsync` my initial expectation was for the default values to get fetched from database, thoughts?

**Comment by barahonajm** [comment]
@roji thanks for answering!! my initial logic was like this:

1. If I use a `Add` followed by a `SaveChanges`, then Default values will only get populated into the model as expected.
2. If I use a `AddAsync` then I don't need to wait `SaveChanges` for the default values to get populated into the model.

I know a person needing case #2 will be very rare, yesterday I had that need but it was more an issue of "concerns" than an issue on EF, but still #2 sounded logical to me so that is why I decided to ask.

**Comment by roji** [comment]
@barahonajm it's generally rare for a sync/async method pair to behave in a fundamentally different way as you were expecting above. The general expectation is that they do the same things, except that one blocks the thread while doing I/O while the other doesn't.
