### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by risogolo** [dotnet/efcore#2846]
I'm not aware of the feature I'm going to describe here. 
I'd like to create "code first database migration" to the script file which creates a script file which is not checking a previous state,  Let's say I have 2 environments, development and production, I'd like to create migration script in development environment which I want to apply against production database which is not aware of previous migration.(migration table does not exist, and of course the user must be responsible for applying the script file)  Is it possible somehow?
I think it creates in my case pl/sql migration script file which wants to check if the migration was already applied. Also it would be nice if it would be pure sql script not pl/sql in my case.

**Comment by risogolo** [comment]
Based on this article http://www.bricelam.net/2014/10/22/ef7-nuget-commands.html it seems something like that maybe planning for 7 release, am I right?

**Comment by rowanmiller** [comment]
This isn't something we are planning to natively support. You can generate the script and then remove the calls to insert into __MigrationHistory or override the migrations components not to generate these statements.
