### ISSUE TITLE
Owned entity mapping for NoKey entity

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/efcore#28469]
I need map class like
```
[Owned]
public class MulticurrencyData
{
   public decimal Eur{get;set;}
   public decimal Usd{get;set;}
   ...
}
```
to keyless entity (it is mapped to columnstore table without key).

```
public class ReportItem
{
    ...
    public MulticurrencyData Sales{get;set;}
    ...
}
```

```
clazz.HasNoKey();
...
clazz.OwnsOne(x => x.Sales, sales =>
                {
                    sales.Property(x => x.Usd).HasColumnName("SalesUsd");
                    sales.Property(x => x.Eur).HasColumnName("SalesEur");
                });
 ```

But it throws exception
```
System.InvalidOperationException: 'The keyless entity type 'ReportItem' cannot be on the principal end of the relationship between 'ReportItem.Sales' and 'MulticurrencyData'. The principal entity type must have a key.'
```

This is needed to make some "expression magic" for selecting different currency data. I made same trick with nhibernate many years ago (component mapping). How I can make same with Entity Framework?

### Include provider and version information

EF Core version: 6.0.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2021 17.2)

**Comment by AndriySvyryd** [comment]
We don't plan to allow this for owned types, but this scenario will be covered under https://github.com/dotnet/efcore/issues/13947
