### ISSUE TITLE
EF7 preview: SaveChangesAsync with large number of changes leads to "DbUpdateException: The incoming request has too many parameters"

### ISSUE THREAD

**Issue by nstdspace** [dotnet/efcore#28475]
I am not sure if this is a bug and I have a hard time reproducing this behaviour in a demo environment, so I will formulate my problem as a question: What exactly has changed in the way ef constructs insert / update queries?

I have a bunch of import operations which are creating / updating a ton of entities. In the end, `DbContext#SaveChangesAsync` is called once, which always worked fine. 
Using the EF7 preview (7.0.0-preview.3.22175.1) however, `SaveChangesAsync` throws a `DbUpdateException` saying "The incoming request has too many parameters". Since no queries are constructed manually I have no Idea where the problem on my side could be. 
I suspected some problem with batchin and dug into ef itself. What I found is, that some of the batches created by `RelationalDependencies.BatchPreparer.BatchCommands(...)` in `RelationalDatabase#SaveChangesAsync` some of the commands have way more than the allowed 2100 parameters (defined by the azure database?). As far as I can tell all of those commands (ReaderModificationCommandBatch#StoreCommand) look similar to this:

```
MERGE [Table1] USING (
VALUES (@px, @py, .....)
....;
MERGE [Table2] USING (
VALUES (@pz, @pw, .....)
....;
```

i.e., consist of multiple MERGE commands with a total of 2500 parameters or more.

Is there anything I'm doing wrong with respect to changes in ef7 or is this i fact a bug in the CommandBatchPreparer?

**Comment by roji** [comment]
Yeah, we're aware of this; I'll fix this by the time 7.0 is released.
