### ISSUE TITLE
Got the Exception when ef migration add/remove on .NET core 6

### ISSUE THREAD

**Issue by seanmars** [dotnet/efcore#28478]
I use the ASP .Net Core 6(6.0.7) with minimal API. And when I use the ef migrations Add ..., I get the exceptions below:

```
[17:56:30::FTL::] Host terminated unexpectedly
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<<Main>$>g__CreateApplication|0_4(<>c__DisplayClass0_0& ) in Program.cs:line 178
   at Program.<Main>$(String[] args) in Program.cs:line 206
Done. To undo this action, use 'ef migrations remove'
```

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework:.NET 6.0.7
Operating system: Windows 10
IDE: Visual Studio 2022

**UPDATED**
I create a project to reproduce this issue.

https://github.com/seanmars/ef-exception

**Comment by seanmars** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Hi, I'm sorry I forgot to provide the runnable project. I have updated the information in the post.

**Comment by ajcvickers** [comment]
@seanmars This exception is expected at design-time and is intended to be caught and handled by the design-time code. Is there a reason you are explicitly catching the exception here rather than letting it escape your code?

/cc @davidfowl 

Relevant code:

```C#
WebApplication? CreateApplication()
{
    try
    {
        var builder = WebApplication.CreateBuilder(args);

        var configuration = builder.Configuration;
        var services = builder.Services;

        services.AddDbContext<ApplicationDbContext>(options =>
        {
            options.UseSqlite(
                configuration.GetConnectionString("DefaultConnection"));
        });

        var app = builder.Build();

        return app;
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.ToString());
    }

    return default;
}

try
{
    var app = CreateApplication();
    if (app == null)
    {
        return;
    }

    await app.RunAsync();
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

**Comment by seanmars** [comment]
> @seanmars This exception is expected at design-time and is intended to be caught and handled by the design-time code. Is there a reason you are explicitly catching the exception here rather than letting it escape your code?


Just don't know why the same code in `.NET 5` will not get the exception. Why `.NET 6` get? It's really weird.

**Comment by ajcvickers** [comment]
@seanmars This functionality is new in .NET 6. See https://github.com/dotnet/runtime/pull/53757

**Comment by seanmars** [comment]
@ajcvickers Thanks. 
And answer the question
> Is there a reason you are explicitly catching the exception here rather than letting it escape your code?

Even if I don't explicitly catch the exception here, it still throws this exception. This code wants to show the exception throw when I use `ef migration`.
And I don't know why this exception needs to be thrown out when using ef migration?
Is there a right sample to do this?

**Comment by davidfowl** [comment]
This same code didn’t work in .NET 5. There was a different entry point that the migrations tooling used (CreateHostBuilder). Without this method, we have to call main which runs your code and then throws an exception to stop the execution flow once we have the service provider. 

It should work fine even if you catch the exception though, you just happen to be writing it to the console. You can skip that by checking for “StopTheHostException” as a type name.

**Comment by seanmars** [comment]
> This same code didn’t work in .NET 5. There was a different entry point that the migrations tooling used (CreateHostBuilder). Without this method, we have to call main which runs your code and then throws an exception to stop the execution flow once we have the service provider.
> 
> It should work fine even if you catch the exception though, you just happen to be writing it to the console. You can skip that by checking for “StopTheHostException” as a type name.

Ok, I see; even this rule is wired.
Maybe this information should write into the document.

**Comment by davidfowl** [comment]
cc @eerhardt @IEvangelist

**Comment by qui8t** [comment]
I am having the same issue, the exception is thrown when adding migration script. I have tried everything in the following docs and most if not all of the related SO questions: 

https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?source=recommendations&tabs=dotnet-core-cli

If relevant, I am using psql (`UseNpgsql`).

**Comment by qui8t** [comment]
I tracked it to `Environment.Exit(exitCode);` in the following code, removing this fixes the issue for me, though not sure how it is relevant. 

```csharp
try
{
    CreateHost();
}
catch (Exception e)
{
    Console.Error.WriteLine(e.Message);
}
finally
{
    Environment.Exit(exitCode);
}
```

**Comment by Mapiarz** [comment]
I am also affected by this issue, dotnet 6, EF 6.07. Possibly related to https://github.com/dotnet/runtime/issues/60600?

I'm using `System.CommandLine.Builder.CommandLineBuilder` which the problem worse as I am unable to try/catch the exception. I guess I'll just have to live with it for the time being.

**Comment by artizzan** [comment]
I've run into this issue after introducing Serilog Bootstrap logger. As indicated above ☝️, there may be other similar scenarios where such crash may happen. I've not found the root cause, but generally worked around it using code similar to this:

```
        if (args.Any(s => "--run-by-ef-cli".Equals(s, StringComparison.OrdinalIgnoreCase)))
        {
            // This is a workaround for when this executable is run by dotnet ef cli.
            // When run by ef cli, Serilog Bootstrap logger causes runtime crash, specific reason not found.

            BuildAndRun(args);
        }
        else
        {
            // This logger is created to log any initialization errors.
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.Debug()
                .WriteTo.AzureApp()
                .CreateBootstrapLogger();

            try
            {
                BuildAndRun(args);
            }
            catch (Exception e)
            {
                Log.Fatal(e, "Application terminated unexpectedly");
                throw;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
```

BuildAndRun() contains all the ASP.NET bootstrap code.

I run the CLI like so:

```
dotnet ef migrations add SomeMigrationName --project .\Sample_WebService -- --run-by-ef-cli
```

[This](https://learn.microsoft.com/en-us/ef/core/cli/dotnet) article explains cmd line arg passing.
