### ISSUE TITLE
Scaffold-DbContext remembers the last project and reports that as a dependency

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#28484]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Scaffold-DbContext-remembers-the-last-pr/10096761)._

---
VS 2022 - 17.2.6

We have a repo/solution with multiple projects.

Open Visual Studio  
Set Startup Project for Project 1  
Run Scaffold-DbContext on Project 1 (meeting all nuget package --Microsoft.EntityFrameworkCore…-- requirements)  
Output will be generated.  
Set Startup Project for Project 2  
Run Scaffold-DbContext on Project 2 (meeting all nuget package --Microsoft.EntityFrameworkCore…-- requirements)

I get the following error: Could not load assembly Project 1 Ensure it is referenced by the startup project Project 2.

If I close VS and reopen, then the command for Project 2 works.

Peter

---
#### Feedback Bot on 7/18/2022, 03:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Brice Lambson
[commented Yesterday](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1577650#3176644)
 
(edited)

In addition to setting the startup project, did you also set the default project in the dropdown of the package management console? See [Target and startup project](https://docs.microsoft.com/ef/core/cli/powershell#target-and-startup-project) for more info.

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
Thanks for the clarification
