### ISSUE TITLE
@asante07 that error means you actually connect to the database Server. Suggest you create a issue with proper information about your environment.

### ISSUE THREAD

**Issue by asante07** [dotnet/efcore#28517]
@asante07 that error means you actually connect to the database Server. Suggest you create a issue with proper information about your environment.

_Originally posted by @ErikEJ in https://github.com/dotnet/efcore/issues/13726#issuecomment-1194501671_

Using .NET 6 Visual Studio 2022 community Edition and Sql server express v 18.12.1. Windows 10 Pro. 
I started by opening VS 2022 and created an asp.net web core app(Model View Controller) with C#. I gave the project a name with a framework of .NET 6.0(long term support). I unchecked the option 'Configure for HTTPS'. I successfully created the project. Built project and 'added the Nugget packages' to the .NET project. .SqlServer, Design and Tools. Rebuilt the project successfully. Built my connection string to connect to existing database.
 
I am not able to successfully run the command to get classes from database even though it actually connects to the existing database. 

Sql Server running, Sql Server Browser and Sql Server VSS Writer all running. Except SQL Server agent(SQLExpress) not running. Using windows authentication. SQL Server express properties include 'Microsoft Windows NT 6.2 (9200)',  platform 'NT x64' and version '10.0.1600.22'

From the above title it means that I am actually able to connect to the database server but with an errors...

So now my issue is what is the correct command to successfully get classes from existing database without any errors at all???. (Package Manager Console).

**Comment by ErikEJ** [comment]
Please share your connection string

**Comment by asante07** [comment]
> Please share your connection string

"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },

  "ConnectionStrings": {
    "DBConnection": "Data Source=DESKTOP-8C6F6G4\\SQLEXPRESS; Initial Catalog=DummyDB2;"
  },

  "AllowedHosts": "*"
}

THIS IS MY CONNECTION STRING

**Comment by ErikEJ** [comment]
That is not a valid SQL Server connection string - this is:

    "Data Source=DESKTOP-8C6F6G4\SQLEXPRESS; Initial Catalog=DummyDB2;Integrated Security=true"
