### ISSUE TITLE
Add virtual methods to existing interceptor base classes

### ISSUE THREAD

**Issue by frandazzo** [dotnet/efcore#28516]
In the code snippet below is not possible to override the ConnectionCreating method.

```C#
public class ConnectionInterceptor:DbConnectionInterceptor
{
    public override InterceptionResult<DbConnection> ConnectionCreating(ConnectionCreatingEventData eventData,
        InterceptionResult<DbConnection> result)
    {
        return InterceptionResult<DbConnection>.SuppressWithResult(new 
           SqlConnection(@"Server=.\SQLEXPRESS;Database=mydb;Trusted_Connection=True;TrustServerCertificate=True"));
    }
       
}
```

Attached is a simple project test that cannot compile. If removing the override keyword the project compiles but the overload is obviously ignored.

[WebApplication1.zip](https://github.com/dotnet/efcore/files/9189073/WebApplication1.zip)

EF Core version: 7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)
Operating system: windows
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@frandazzo The method is defined in the interface, and not implemented by the abstract base class. This means it can't be overridden, merely implemented, and hence should have the `override` keyword.

@dotnet/efteam Where we have existing abstract base types as well as interfaces with default implementations, should we consider adding methods to the abstract base types to avoid this confusion?

**Comment by frandazzo** [comment]
Ok i've removed the override keyword but if i try to debug the interceptor method, nothing happens. It seems like no interceptor was added or that the ConnecitonCreating Method is not called.

**Comment by frandazzo** [comment]
Moreover this ticket https://github.com/dotnet/efcore/issues/23087 was closed stating that it was implemented from version 6
if i've well understood. Or i'm missing something? Thank you in advance

**Comment by ajcvickers** [comment]
@frandazzo You're right; this doesn't work unless the interface is implemented explicitly as well as inheriting from the base class:

```C#
ConnectionInterceptor : DbConnectionInterceptor, IDbConnectionInterceptor
```

I will discuss with the team.

**Comment by frandazzo** [comment]
Thank you @ajcvickers ;
The code now compile and gets executed but i don't know why i get and exception. 
My goal is to use a connection factory on the connection interceptor and the code

return InterceptionResult.SuppressWithResult(new
SqlConnection(@"Server=.\SQLEXPRESS;Database=mydb;Trusted_Connection=True;TrustServerCertificate=True"));

is an exmple of what i have in mind. 
Can you help me explaining why i get an exception

thank you in advance

**Comment by ajcvickers** [comment]
@frandazzo Please post the exception message and stack trace.

**Comment by frandazzo** [comment]
![image](https://user-images.githubusercontent.com/11243974/181010624-e4d1a8eb-8231-47ac-84eb-5c5abf8f96dd.png)


the db mydb3 does not exist! if i remove the interceptor the db is correcly created. At this point if rerun the app reenabling the interceptor it works. Why the ensureCreated does not work?
Thanks

**Comment by frandazzo** [comment]
Why the ensureCreated does not work (with the interceptor)?

**Comment by ajcvickers** [comment]
@frandazzo When EnsureCreated needs to create a database, it does so by opening a connection to the "master" database on the server for which the database needs to be created. (Since it can't open a connection to a database that doesn't exist.) Your code is blindly replacing that with a connection to the database that does not exist, and hence it is failing. You need to be more selective about when you replace the connection so that the connection to the master database is not replaced. The connection string can be obtained from, `eventData.Context.Database.GetConnectionString()`.

Note for triage: we should make the `RelationalConnection`, or at least the connection string more easily accessible from

**Comment by frandazzo** [comment]
@ajcvickers Thank you for your answer. Unfortunately i've found no way to use interceptors to pass a connection fatory to the dbcontext. 
Thankyou the same
