### ISSUE TITLE
ChangeTracker keeps EntityEntry after Remove() and SaveContext()

### ISSUE THREAD

**Issue by FelixSFD** [dotnet/efcore#28530]
I have some models in a MSSQL Database that use `char(10)` (fixed length) as Datatype in their Primary Key.
The database was generated by EF.

```csharp
[Column(TypeName = "char(10)")]
[MinLength(10)]
[MaxLength(10)]
[Key]
public string OrderId { get; set; }
```

Since EF doesn't enforce the exact length of 10, the model will still be stored in the database, but the key will include additional whitespaces.

If you then try to delete all models using something like `await context.Order.ForEachAsync(m => context.Order.Remove(m))`, there will be one entry left in the `ChangeTracker`, using the old key without whitespaces.

Trying to delete the model with the old key results in an Exception:

```stacktrace
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Program.<Main>$(String[] args) in C:\dev\ef-mssql-char-bug\Program.cs:line 91
   at Program.<Main>(String[] args)
```

### Code to reproduce the issue

I have created a sample-project to reproduce the bug: https://github.com/FelixSFD/ef-mssql-char-bug (requires Docker to run, because I use Testcontainers to run a temporary MSSQL Server)

https://github.com/FelixSFD/ef-mssql-char-bug/blob/master/Program.cs#L39-L92

That's the main part of the code:

```csharp
using (var serviceScope = app.Services.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
  var context = serviceScope.ServiceProvider.GetRequiredService<SampleDbContext>();

  OrderModel? order1 = new OrderModel
  {
    OrderId = "123456789",
    Info = "9 chars"
  };
  OrderModel? order2 = new OrderModel
  {
    OrderId = "0123456789",
    Info = "10 chars"
  };

  context.Order.Add(order1);
  context.Order.Add(order2);
  context.SaveChanges();

  OrderItemModel item1 = new OrderItemModel
  {
    OrderId = order1.OrderId,
    ItemName = "You-No-Poo",
    Quantity = 435345.0
  };
  OrderItemModel item2 = new OrderItemModel
  {
    OrderId = order1.OrderId,
    ItemName = "Portable swamp",
    Quantity = 1.2
  };
  context.OrderItem.Add(item1);
  context.OrderItem.Add(item2);
  context.SaveChanges();

  Console.WriteLine("Added models");


  await context.OrderItem.ForEachAsync(m => context.OrderItem.Remove(m));
  context.SaveChanges();

  await context.Order.ForEachAsync(m => context.Order.Remove(m));
  context.SaveChanges();

  Console.WriteLine("Removed models");

  foreach (var entry in context.ChangeTracker.Entries())
  {
    Console.WriteLine(entry);
  }

  context.Order.Remove(order1);
  context.SaveChanges();
}
```

This is the output of the full sample program:

>Added models
>Removed models
>OrderModel {OrderId: 123456789} Unchanged
>Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
>   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
>   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
>   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
>   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
>   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
>   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
>   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
>   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
>   at Program.<Main>$(String[] args) in C:\dev\ef-mssql-char-bug\Program.cs:line 91
>   at Program.<Main>(String[] args)

### Debugger Screenshots
Before deleting:
![image](https://user-images.githubusercontent.com/2721240/181498913-9b413095-4818-41a0-9de0-d1d9f59f9878.png)

After deleting Orders but before saving context:
![image](https://user-images.githubusercontent.com/2721240/181499246-89b30330-4764-4377-bc70-65407df0516c.png)

After deleting and saving:
![image](https://user-images.githubusercontent.com/2721240/181499040-fce981c3-b080-4fa0-810f-4d2949e3452a.png)

### Expected behavior

`var entry in context.ChangeTracker.Entries()` at the end of my sample program should return an empty result.

I guess it's okay that `context.Order.Remove(order1); context.SaveChanges();` throws an Exception, since that object should not exist anymore, but it looks like the issue with the ChangeTracker causes problems in more complex applications. However I could not share my whole application where I found this issue in the first place. This example is the closest I got and the Exception is the same, but it happens before trying to delete the Order again. (probably because linked tables were cleared as well)

### Workaround

Make sure, you validate the input before saving a `char(x)`-value.

### System information

EF Core version: 6.0.7 (with LazyLoadingProxies)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Linux in Docker Container (+ Sample Project on Windows)
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@FelixSFD See [Handle fixed-length database strings](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#handle-fixed-length-database-strings).
