### ISSUE TITLE
How to dispose pooled `DbContext` correctly when using the `PooledDbContextFactory` approach to pass state 

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [dotnet/efcore#28533]
Hi there,

I am having difficulties to track this issue down and I did search for a solution for like 2 days, even digging in the EF Core code did not help.

I have a multi-tenant DB setup where each tenant has a separate DB. Therefore I need to attach the tenant ID to the context. The [example](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Performance/AspNetContextPoolingWithState) linked in the [Managing state in pooled contexts](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#managing-state-in-pooled-contexts) documentation perfectly fits my needs BUT ... I need to resolve the `MyDbContext` consecutively in a for loop to iterate over all tenant DBs like

``` csharp
foreach (var tenantId in tenantIds)
{
   ...
    
    using (var context = serviceProvider.GetRequiredService<MyDbContext>())
    {
        ...
    }
}
```

and this throws a 

```
System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'WeatherForecastContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_Database()
```

as soon as I resolve `MyDbContext` a second time.

You can repro this by extending the `WeatherForecastController` from the aforementioned [example](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Performance/AspNetContextPoolingWithState) with

``` csharp
[HttpPost(Name = "GetWeatherForecast")]
public async Task<IEnumerable<WeatherForecast>> Post()
{
    using (var context1 = _services.GetRequiredService<WeatherForecastContext>())
    {
        await context1.Database.EnsureCreatedAsync();
    }

    using (var context2 = _services.GetRequiredService<WeatherForecastContext>())
    {
        await context2.Database.EnsureCreatedAsync();
    }

    return null;
}
```

... then start the application and run the action. It will fail with the same error as mentioned above.

Now the strange part: when I use `AddDbContextPool` instead of `AddPooledDbContextFactory` in my application everything works flawlessly ... but with `AddDbContextPool` I cannot  attach state to `MyDbContext`.

I think it has something to do with the scoped lease stuff, somehow this works differently when using the factory approach.

So I am a bit lost now as simply not disposing `MyDbContext` is not an option, right?

Is there something missing that I need to do to make resolving in consecutive order possible?

### Provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: VS 2022 Version 17.3.0 Preview 5.0

**Comment by AraHaan** [comment]
Not a bug, you are most definitely doing it wrong with those using blocks.

**Comment by ajcvickers** [comment]
@ViRuSTriNiTy With `AddPooledDbContextFactory`, the D.I. container takes care of disposing the context instance when the scope from which it is resolved is disposed. So, when getting a context instance from D.I. like this:

```C#
_services.GetRequiredService<WeatherForecastContext>()
```

it should not be explicitly disposed by the application by, for example, the `using` statement you show above.

**Comment by ViRuSTriNiTy** [comment]
@ajcvickers My bad, I added the `_services.GetRequiredService<>()` calls in the example for simplicity. The actual code uses factory BUT this factory then uses the said calls which is obviously wrong. I somehow have overseen that, thanks for pointing that out. Closed.
