### ISSUE TITLE
Should pre-convention configuration overwrite data annotations?

### ISSUE THREAD

**Issue by Peter-B-** [dotnet/efcore#28541]
I use pre-convention configuration to set the default maximum string length for my context to 256:

```csharp
    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        base.ConfigureConventions(configurationBuilder);

        configurationBuilder.Properties<string>()
            .HaveMaxLength(256);
    }
```

When I override this with a `[StringLength(100)]` or `[MaxLength(100)]` attribute, the default value (here 256) is used and the attribute ignored. Overwriting the string length with fluent configuration is working.

```csharp
public class User
{
    [Key]
    public int UserId { get; set; }

    // Attribute is ignored
    // length is set to nvarchar(256)
    [StringLength(100)] 
    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    internal class DbConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
        {
            // Fluent API configuration is respected
            // length is set to nvarchar(100)
            builder.Property(u => u.LastName).HasMaxLength(100);
        }
    }
}
```

Is this intended behavior or an issue?

I personally prefer to set string length in attributes, since this is configured directly next to the property.

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net 6.0

Kind regards
Peter

**Comment by smitpatel** [comment]
Intended behavior. The bulk configuration has same priority as fluent API since it is explicitly specified by user.

**Comment by Peter-B-** [comment]
Actually, I'm not sure if this is really true: According to [`ConfigurationSourceExtensions.Overrides()`](https://github.com/dotnet/efcore/blob/1ff156c24897e4962defb9204bdee9068bb76c2d/src/EFCore/Metadata/ConfigurationSourceExtensions.cs#L26), both `DataAnnotation` and `Explicit` should overwrite `Convention`.

So is it really intended, that pre-convention overrides `DataAnnotation`?

**Comment by ajcvickers** [comment]
We discussed this, and while the naming is perhaps unfortunate, and the experience of overriding with an annotation would be nice, the reality is that this method sets up low-level type mapping which acts like explicit configuration. [Public conventions](#214), which are planned for EF7, will allow a convention to be written that will allow overriding via data annotations.

**Comment by DanielStout5** [comment]
For anyone else finding this and intending to use it to avoid the warning about Precision not configured (without overriding any attributes you did set) you can do:


```
 if (prop.Builder.Metadata.GetPrecision() == null)
 {
     prop.Builder.HasPrecision(18, ConfigurationSource.DataAnnotation);
     prop.Builder.HasScale(2, ConfigurationSource.DataAnnotation);
 }
```

**Comment by darman96** [comment]
@ajcvickers Your "Public Conventions" Link links to this issue and I can't find anything on that topic. What is the status of this?
