### ISSUE TITLE
Is it possible to switch the database without having to change the connection string?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [dotnet/efcore#28545]
Hi there,

in the process of digging through #14625 I found the section [Pool Fragmentation Due to Many Databases]() in the documentation providing a solution to reduce the number of connections when having a multi-tenant scenario with one DB per tenant, namely using the [USE statement](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql) to switch to a specific database.

Can this be done with EF Core?

**Comment by roji** [comment]
There's nothing in particular EF can do for you here - you can easily send `USE <db>` as raw SQL via `context.Database.ExecuteSqlRaw()` yourself.

Note that this won't work across different database. In PostgreSQL, for example, a physical connection is always against a specific database, and it's not possible to switch the database of an open connection like in SQL Server.
