### ISSUE TITLE
Owned entities collection table name inconsistencies

### ISSUE THREAD

**Issue by Xriuk** [dotnet/efcore#28543]
When adding a collection of owned entities (`Category`) to another entity (`Shop`, `Blog`, `Forum`, ...) there is an inconsistency in table naming:

- If the owned entity is not used anywhere else (for now) the resulting table gets named like the owned entity itself (`Category`)
- If the owned entity is used in more than one entity the tables get named correctly: `Owner_PropertyName` (`Shop_Categories`, `Blog_Tags`, `Forum_Topics`, ...)

I think that the latter behaviour should be universal, and also include multiple nested owned entities (`Shop_Categories_SubCategories`, ...), this may also cause problems because if an entity starts being owned by multiple entities its initial table gets renamed anyways.

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10 21H1
IDE: Visual Studio 2022 17.2.4

**Comment by ajcvickers** [comment]
@Xriuk This is by-design. We choose a simple name by default whenever we can. It's always possible to explicitly specify a table name if you want something different.
