### ISSUE TITLE
Scaffold-DbContext generate directories based on schema

### ISSUE THREAD

**Issue by irfandar** [dotnet/efcore#28550]
While trying to Scaffold an existing database using EFCore tools it generates all the POCO classes in one directory provided by the **-OutputDir** parameter.

I would prefer the following improvements

1. It would be better if there was a option to generate POCO classes inside the directory based on the schema of table e.g. for table **HR.Employees** and **--OutputDir** Models it should generate Modes\HR\Employees.cs
2. It should also sort the DBSet rows based on schema then table in the **-Context**.cs file
3. It should also append the namespace to duplicate objects e.g. for the second occurrence of **Settings** object it should generate **Schema**Setting POCO class instead of **Setting1**

**Comment by ErikEJ** [comment]
Item 1 is possible via EF Core Power Tools.
