### ISSUE TITLE
Reexamine the requirement for unique index (and key?) CLR types to be comparable

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28566]
Currently, trying to define a unique index over a property whose CLR isn't comparable errors with: 

```
Property 'Entity.Range' cannot be used as a key because it has type 'NpgsqlRange<decimal>' which does not implement 'IComparable<T>', 'IComparable' or 'IStructuralComparable'. Use 'HasConversion' in 'OnModelCreating' to wrap 'NpgsqlRange<decimal>' with a type that can be compared.
```

Apparently this wasn't a requirement in 3.1, and @ajcvickers says that maybe we don't need it any more now that we have provider value comparers.

/cc @AndriySvyryd 

Raised in https://github.com/npgsql/efcore.pg/issues/2457

**Comment by roji** [comment]
Team discussion:

* For unique indexes, we indeed no longer need the type to be orderable (IComparable). This restriction can be removed.
* For primary keys we do still need it, to order updated entities in deterministic ordering in the update pipeline, in order to avoid deadlocks (e.g. reverse-order updates). For these cases, the provider can still provide an ordering for the type (any arbitrary determistic ordering will do).

**Comment by AndriySvyryd** [comment]
Actually we still need this. Blocked on https://github.com/dotnet/efcore/issues/27761

**Comment by roji** [comment]
Team discussion: it's unlikely we'd be able to lift the requirement for unique indexes.

More importantly... We could stop blocking non-comparable types in the update pipeilne; this would allow users to define primary keys/unique indexes over those types, but would open them up to deadlocks due to concurrent transactions with different ordering. It's better to make it the provider's responsibility to add some (arbitrary) ordering instead (opened https://github.com/npgsql/efcore.pg/issues/2567 for the PG side).

Closing for now. If we see a type where it's really not feasible to provide a comparer for some reason, and that type really needs to be in a primary key/unique index column, we can revisit.
