### ISSUE TITLE
Is it possible to use in-memory DB with DbContext pooling in a multi-tenant environment?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [dotnet/efcore#28565]
Hi there,

the extension method `UseInMemoryDatabase` configures a `DbContext` to work with an in-memory database. When I call this in the callback of `AddPooledDbContextFactory` I have to pass a database name that is not yet defined because for resolution I need the tenant ID.  Using the connection string approach discussed in https://github.com/dotnet/efcore/issues/14625#issuecomment-1199446972 throws exceptions because it is obviously not supported for in-memory stuff.

So how do I implement "Pooled factory, please give me a DbContext that associates to in-memory DB of tenant X"? Is it even possible?

So lonG

**Comment by ajcvickers** [comment]
@ViRuSTriNiTy As long as you can get the tenant ID into your context instance, then you can use `OnConfiguring` to call `UseInMemoryDatabase`.
