### ISSUE TITLE
Look into the performance of AsNoTrackingWithIdentity

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28579]
We've received reports that AsNoTrackingWithIdentityResolution can perform 4 times slower compared to non-tracking queries. Of course, it's expected that identity resolution add an overhead, but this seems like a bit much. Also see how AsNoTrackingWithIdentityResolution is doing compared to tracking queries.

**Comment by ajcvickers** [comment]
Duplicate of #23558.
