### ISSUE TITLE
Ef 7 Cosmos support?

### ISSUE THREAD

**Issue by thorgeirk11** [dotnet/efcore#28570]
### Why are all of the roadmap items for cosmos on the backlog?

EF 7 roadmap contains a section for [cosmos with 13 issues on it](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#azure-cosmos-db-provider). All of the issues have been removed from the 7.0.0 milestone and put on the backlog. 

### How committed is the EF to cosmos?
Should I refrain from using EF with cosmos due to lack of support?

**Comment by ErikEJ** [comment]
They still appear on the 7.0 milestone for me !?

**Comment by ajcvickers** [comment]
@thorgeirk11 Some of the Cosmos work was cut from 7.0 due to resource constraints. We are committed to Cosmos support in the EF Core provider.

**Comment by thorgeirk11** [comment]
@ErikEJ There are only 2 issues that still have a milestone 7.0.0: #19944 and #26491

@ajcvickers 2 out of 13 issues seems excessive, can you elaborate?
 
I am honestly disappointed about the lack of progress with the cosmos provider 😞

**Comment by ajcvickers** [comment]
> 2 out of 13 issues seems excessive, can you elaborate?

We needed to make some pretty significant cuts. Other items not from Cosmos were also cut. It's always a hard decision what to cut, with many competing interests, and this is the way it turned out this time.

**Comment by thorgeirk11** [comment]
@ajcvickers @ErikEJ What is the change log for the cosmos provider in .net 8? 
The [website ](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/plan) and [blog post](https://devblogs.microsoft.com/dotnet/announcing-ef8/) is even more vague then for .net 7

**Comment by ajcvickers** [comment]
@thorgeirk11 As always, GitHub is the source of truth: https://github.com/dotnet/efcore/issues?q=is%3Aissue+milestone%3A8.0.0+label%3Aarea-cosmos+is%3Aclosed

**Comment by thorgeirk11** [comment]
@ajcvickers What happened to all of the [changelog items which were cut in ef 7](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#azure-cosmos-db-provider)?

Are you telling me that all that happened during the last year of development are six issues, and out of those, four are for improving error messaging due to a lack of support for new features?

Please do not forget the users you already have in this product. It feels like the EF team has completely discontinued development for Cosmos. This is strange since Cosmos is still the number 1 database Microsoft is pushing to its clients.

**Comment by ajcvickers** [comment]
@thorgeirk11 There are four engineers on the .NET Data Access team. Cosmos is important to us, but many other areas are also important. We can't do everything that all our users want all at once. Make sure to vote (👍) for the issues that are important to you.
