### ISSUE TITLE
Query: ExecuteDelete on entity type owning other entities do not work

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#28573]

**Comment by roji** [comment]
Seems like either #28521 or #28520, no?

**Comment by smitpatel** [comment]
This stems from a different code path. Suppose your owned entities are mapped to a different table then delete should be fine. But currently it would fail because we check for entity shaper in projection but for owned (or non-owned scenario in AutoInclude), we will get IncludeExpression and fail with non-entity projection. But those projections are added by us and user cannot control for owned entity.

**Comment by roji** [comment]
Makes sense, thanks!

**Comment by smitpatel** [comment]
Fixed in #29023
