### ISSUE TITLE
Configuring base class properties results in TBH

### ISSUE THREAD

**Issue by jimjimjimhaha** [dotnet/efcore#28588]
Given this model:
```c#
public abstract class BaseEntity
{
    public int Id { get; set; }
}

public class Course : BaseEntity
{
    public string Title { get; set; }
}

public class Instructor : BaseEntity
{
    public string FullName { get; set; }
}
```
And this DB context class:
```C#
public class AppDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql(
            "Host=localhost;Username=postgres;Password=123456;Database=efcorebaseentityissue"
        );
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<BaseEntity>()
            .Property(e => e.Id)
            .UseIdentityAlwaysColumn()
            .HasIdentityOptions(startValue: 1000);
    }

    public DbSet<Course> Courses { get; set; }

    public DbSet<Instructor> Instructors { get; set; }
}
```
And then running:
```shell
dotnet ef migrations add Initial
```
I get the following migration:
```c#
namespace efcore_base_entity_issue.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BaseEntity",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:IdentitySequenceOptions", "'1000', '1', '', '', 'False', '1'")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    Discriminator = table.Column<string>(type: "text", nullable: false),
                    Title = table.Column<string>(type: "text", nullable: true),
                    FullName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BaseEntity", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BaseEntity");
        }
    }
}
```
Which means that the configuration of the `Id` property in the `OnModelCreating` method made EF Core think that `BaseEntity` should be part of a hierarchy; but I don't want that. `BaseEntity` is simply an abstract base class for the entity classes just to avoid duplicating properties that are shared between them like `Id`, and I simply wanted to configure that property.

How can I solve this problem?

### Dependencies:
`Npgsql.EntityFrameworkCore.PostgreSQL` version 6.0.6
`Microsoft.EntityFrameworkCore.Design` version 6.0.7

**Comment by roji** [comment]
The reason this is happening is because you're mapping BaseEntity (builder.Entity<BaseEntity>()). Perform your configuration on the subtypes directly instead, and you should get two separate tables.

**Comment by jimjimjimhaha** [comment]
> The reason this is happening is because you're mapping BaseEntity (builder.Entity<BaseEntity>()). Perform your configuration on the subtypes directly instead, and you should get two separate tables.

@roji Well, I understand that but the whole point was to avoid repeating the configuration for the shared properties for every single entity. Isn't that possible?

**Comment by roji** [comment]
Not in that particular way. But you can have a small generic local function accepting BaseEntity subclasses and applying the same common configuration to them. If BaseEntity isn't part of the EF model - which would mean it needs to be mapped via TPH - then it can't contain EF model configuration either...
