### ISSUE TITLE
[Suggestion] EF.Commands as a dependency to all design-time projects

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2858]
The design-time features in EntityFramework.SqlServer.Design are inaccessible to an end user without EF.Commands. This is a "user-time" dependency. We should add EF.Commands to the dependency graph for SqlServer.Design and Sqlite.Design.

**Comment by ErikEJ** [comment]
Makes a lot of sense, I wil do the same for the sqlce ce design time providers

**Comment by bricelam** [comment]
We actually talked about doing it the other way around at one point: (working names)
* Provider.Tools
    * Provider.Design
    * EF.Commands

**Comment by natemcmaster** [comment]
:+1: I like this idea even better than my initial suggestion.

**Comment by rowanmiller** [comment]
**Triage:** Closing this out as what we have may not be perfect but it works ok. We can look at add/restructuring packages in the future if needed.
