### ISSUE TITLE
How do you unit test a ValueComparer<T>?

### ISSUE THREAD

**Issue by jsmarsch** [dotnet/efcore#28606]
I have a custom ValueComparer, and I would like to write some unit tests to confirm that it is working correctly.

**Comment by roji** [comment]
@jsmarsch you can simply write unit tests directly against your value comparer, making sure it performs its conversions correctly.

If you wish, you can also write tests against EF Code while using your comparer. For the most end-to-end coverage, your tests would work against the database system you're using in production; see [Choosing a testing strategy](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy) in our documentation.

**Comment by jsmarsch** [comment]
@roji  I see what I missed now -- the Equals() method is overloaded to accept the types that the ValueComparer compares.  I couldn't initially find the entry point for performing the comparison -- I was mentally filtering out the Equals() method since it is traditionally to compare "this"  with another object.
