### ISSUE TITLE
How can I dynamically create a sequence?

### ISSUE THREAD

**Issue by a510** [dotnet/efcore#28610]
I have two tables 

1. Customers (Id, ...)
2. Invoices (Id, Number, CustomerId..)

Each customer has many invoices and his invoices should be numbered sequentially without gaps starting from 1, apart from the sequences of the invoices of other customers.

I tried using [Sequences ](https://docs.microsoft.com/en-us/ef/core/modeling/sequences) for that but I need a separate sequence for each new customer.

How can I create a separate sequence for each customer dynamically ?
Or is there's a better solution for this problem ?

**Comment by roji** [comment]
@a510 for this kind of requirement, before creating a new invoice you can simply query for the maximum invoice number for that customer (via a regular LINQ query) and add 1 for the new invoice's ID.

**Comment by a510** [comment]
@roji but how to handle concurrency issues ?
I thought of adding a unique constraint on (Number, CustomerId) columns but I'm afraid that with high traffic many insertions will fail.

**Comment by roji** [comment]
You can catch those failures and retry - it's pretty easy to identify a unique constraint/key violation in code (exactly how depends on your database). If you catch such a unique constraint violation exception, you simply requery for the new maximum ID and retry. This sort of "optimistic" strategy is in any case better than attempting to create a sequence per customer.
