### ISSUE TITLE
ORDBMS

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#2861]
Hi,

Now that code first and EF is a trend, is it time to start moving towards the ORDBMS?

Say something like (_Startup.cs_):

```
services
    .AddEntityFramework()
    .AddDbContext<ApplicationContext>()
    .AddOrdbms();
```

Entity Framework will utilize a file-system based DB that is an open-end for .NET objects and natively query against it.

Here are some areas that will benefit from this:
- Unified code for both model and server
- Easier migration and deployment of DB changes
- Easier querying and LINQing against DB
- Tooling

We could even have the DB depend on EF or have an extension faucet so that it generates the DB based on the model.

**Comment by rowanmiller** [comment]
Hey,

There isn't really anything actionable from the EF project team here, so we are closing this out. ORDBMS may grow in popularity and an ORDMBS provider (or someone else) may want to write an EF provider.

~Rowan

**Comment by weitzhandler** [comment]
I wan't talking about Oracles DB. I was talking about the general idea of [ORDBM](https://en.wikipedia.org/wiki/Object-relational_database).

I merely wanted top open a discussion rather than an issue. I'm curious if there is any interest in this field.  
Personally I think that it would be awesome (especially for < enterprise projects) to have EF be treated as the database itself by having an underlying object database EF serializes and stores from/to.

I'd like to hear people's thoughts and what could be the consequences of this.

**Comment by rowanmiller** [comment]
> I wasn't talking about Oracles DB, but about the general idea of ORDBM.

Yes that was what we understood you were talking about :smile: 

From the EF perspective we want to be able to connect to all types of data stores. My opinion is that you need to start by picking the type of data store that best suites the way your application will be using data and then pick a data access API that suits the type of store you need. EF7 will be able to connect to some, but not all, of these different types of data stores. I agree EF would work well over an ORDBMS and we'd be very willing to work with someone who wants to write a provider for one (as we do with provider writers for other DBMS).

**Comment by rowanmiller** [comment]
Reopening and moving to Discussion for anyone who wants to discuss.

**Comment by leus** [comment]
As I see it, an ORDBMS built on top of EF would be *awesome*, but I don't see how it affects EF's development process if at all.

**Comment by weitzhandler** [comment]
@leus 
It shouldn't. I think it's time for reuse. As we're starting to get used to code-first and generate DB from it, if we have a .NET object oriented DB, it can be really integrated with the language and decrease overhead. Like Visual FoxPro use to do.

**Comment by leus** [comment]
I don't think I get your point. What do you mean "integrated with the language"? How can EF help to accomplish that? What is in your vision that Linq (for example) has not?

**Comment by weitzhandler** [comment]
@leus 
Having a .NET oriented DB will open a whole new world of capabilities in persistent storage.
Here are some simple examples:
 - Use your native .NET syntax to search the DB
 - Search with Regex
 - No limitations to [Canonical Functions](https://msdn.microsoft.com/en-us/library/vstudio/bb738626) in LINQ to entities (Entity SQL)
 - Complex nesting of queries
 - Easy graph transactions of any size and shape
 - No generation of SQL overhead
 - And a zillion of more options

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
