### ISSUE TITLE
Change database name in runtime using entity framework core and .net core6

### ISSUE THREAD

**Issue by badrdouah** [dotnet/efcore#28620]
i have a mysql server with multiple databases, i need to access them during runtime, i have this working correctly with ADO.net but i need to do this with EF core, i have managed to do that but i'm not really sure if that is the correct way to do it.

```
public class UserRepo : IUserRepo
{
    public DBContext DBContext { get; }

    public UserRepo(DBContext dBContext)
    {
        DBContext = dBContext;
    }

    public async Task<int> GetCount(string dbName)
    {
       DBContext.Database.OpenConnection();
       await DBContext.Database.GetDbConnection().ChangeDatabaseAsync(dbName);
       return DBContext.Users.Count();

    }
}
```

the confusing part is why i need to open the connection first before being able to change the database name,

`DBContext.Database.OpenConnection();`

it feels like i'm doing something wrong (Creating a new instance of dbcontext each time i'm changing the database name), please correct me if i'm wrong.

EF Core version: 6.0.7
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework:  .NET 6.0
Operating system: Mac os
IDE: (Visual Studio 2022 17.0.7

**Comment by roji** [comment]
EF doesn't provide any specific infrastructure for switching databases at runtime, so dropping down to ADO.NET (and therefore opening the ADO connection yourself) as you're doing it should be fine.

**Comment by badrdouah** [comment]
> EF doesn't provide any specific infrastructure for switching databases at runtime, so dropping down to ADO.NET (and therefore opening the ADO connection yourself) as you're doing it should be fine.

Got it, Thank you for your reply,
