### ISSUE TITLE
Relative path in connection string does not work with Sqlite

### ISSUE THREAD

**Issue by leak** [dotnet/efcore#2864]
Related to #2748

Specifying a relative path to a database file does not work, the application dies with 
"SQLite Error 14: 'unable to open database file'".

```
            services.AddEntityFramework()
                .AddSqlite()
                .AddDbContext<AppDbContext>(
                    options => options.UseSqlite("Data Source=db/database.sqlite"));
```

For the "dnx ef" command it already seems to be working (ref https://github.com/aspnet/Microsoft.Data.Sqlite/issues/55)

**Comment by natemcmaster** [comment]
Moving to https://github.com/aspnet/Microsoft.Data.Sqlite/issues/55#issuecomment-132265437
