### ISSUE TITLE
Adding many-to-many relationships without mapping table

### ISSUE THREAD

**Issue by JYasgarYTGI** [dotnet/efcore#28662]
## How do I add an existing item to a collection that is a many-to-many collection in another existing item. Only examples I can find show adding where one or both of the items are new.

Have a project that has several many to many relationships. I'v looked for hours trying to determine how to handle creating the relationships in EF Core 6 with existing records. Neither of the data elements on either side of the many to many relationship will be new. We are basically trying to map existing records to have the many to many relationship.

Since I have to rewrite many linq queries to accommodate the new relationships, I'm trying to create unit tests with an InMemoryDatabase.

```C#
                // Create a new one that is In Memory
                services.AddDbContext<RVResearchContext>(options =>
                {
                    options.UseInMemoryDatabase("TopTenTests");
                });

                // Rebuild the provider
                ServiceProvider sp = services.BuildServiceProvider();

```

I have an existing Parent item that can have many features. The features are in a feature table so that they are reused by all the items. The Parent item exists in the DB, then the features are added one by one. 

So in a seed method, I try:
```C#
            RVModels _rv01 = dbContext.RVModels.Include(f => f.FeatureBase).Single(r => r.Id == 229);
            var _feat01 = dbContext.Features_Base.Single(f => f.Id == 7);
            _rv01.FeatureBase.Add(_feat01);
            dbContext.SaveChanges();
```

Stop point at "SaveChanges" shows that the feature is part of the FeatureBase collection of _rv01 and SaveChanges is successful, however, a stop point later shows that the value is no longer in the collection. I look at the _rv99 item and it has nothing in the FeatureBase collection.

```C#
            dbContext.SaveChanges();
            RVModels _rv99 = dbContext.RVModels.Include(f => f.FeatureBase).AsNoTracking().Single(r => r.Id == 229);
```

I've tried different variations of AsTracking and AsNoTracking, with only beginning to get the "item is already being tracked" error as a reward.

There is a table called Map_RVModels_Features that has a FK - FeatureBaseId and FK - RVModelsId. This table is not scaffolded, but the relationship is there perfectly for selects.

### Include provider and version information
EF Core version: 6.0.7
Database provider: UseInMemoryDatabase("AllTests");
Target framework: 6.0
Operating system:  Windows 10
IDE: Visual Studio 2022 Professional 64bit 17.2.5

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by JYasgarYTGI** [comment]
Had secret hope you would look at what I was doing and say, oh no, you're doing it wrong! :-)

I've created a scaled down version of the tests here:

https://github.com/YTGI/UnitTestSample.git

Let me know if you'd prefer zip file.

**Comment by ajcvickers** [comment]
@JYasgarYTGI The code is using `NoTracking` queries when seeding. This means that the code makes changes to untracked entities, which will never be saved to the database since they are not being tracked.  If I remove both lines that do `/dbContext.ChangeTracker.QueryTrackingBehavior` and both calls to AsNoTracking in the seeding code, then your test passes.

**Comment by JYasgarYTGI** [comment]
> @JYasgarYTGI The code is using `NoTracking` queries when seeding. 

Thanks, Arthur, those lines were actually added during my troubleshooting. Looks like with all my attempts I still always had the wrong combination of settings. Really appreciate you looking at it.
