### ISSUE TITLE
Use fully qualified names in typeof() for compiled models

### ISSUE THREAD

**Issue by ronymeyer** [dotnet/efcore#28674]
When we generate a compiled model (in Core 7, preview 7) and we have a class with the same name as the namespace then the generated compiled model doesn't compile. This is due to the fact that it only uses the class name in typeof instead of the fully qualified name. Same applies when the class also exist as a class in one of the included namespaces.

Currently it generates:
`var runtimeEntityType = model.AddEntityType(
    "CompanyName.Entity.Account.Account",
    typeof(Account),
    baseEntityType,
    changeTrackingStrategy: ChangeTrackingStrategy.ChangingAndChangedNotifications);
`

It should generate:
`var runtimeEntityType = model.AddEntityType(
    "CompanyName.Entity.Account.Account",
    typeof(CompanyName.Entity.Account.Account),
    baseEntityType,
    changeTrackingStrategy: ChangeTrackingStrategy.ChangingAndChangedNotifications);
`

Same also applies to other places where typeof is used, for example in CreateForeignKey{n} methods.

**Comment by ajcvickers** [comment]
@ronymeyer See https://github.com/dotnet/efcore/issues/25523

@AndriySvyryd Should this be promoted to full-public?

**Comment by AndriySvyryd** [comment]
https://github.com/dotnet/efcore/issues/27203 should be enough
