### ISSUE TITLE
DbUpdateConcurrencyException when setting owned entity to modified

### ISSUE THREAD

**Issue by RyanGaudion** [dotnet/efcore#28675]
## File a bug

When modifying an model with an owned entity I get the following `DbUpdateConcurrencyException` consistently for every call

```
The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

### Include your code

Here is the method throwing the exception 

```
_dbContext.ChangeTracker.Clear();

var dBModel = _dbContext.MyModel.Attach(model);

dBModel.State = EntityState.Modified;
dBModel.Reference(x => x.Features).TargetEntry.State = EntityState.Modified; //This Line

dBModel.Property(x => x.Name).IsModified = false;

await _dbContext.SaveChangesAsync();
_dbContext.ChangeTracker.Clear();
return model;
```

When commenting out "This Line" the code doesn't throw an error, however (features are not updated).

Here is my `IEntityTypeConfiguration`:
```
public void Configure(EntityTypeBuilder<MyModel> builder)
{
    builder.Property(t => t.Name).IsRequired();

    builder.OwnsOne(t => t.Features, f => { f.ToTable($"{nameof(FeatureSet)}s"); });
}
```

### Include provider and version information

EF Core version: 6.0.8
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 6.0.6
Target framework:.NET 6
Operating system: Win 10
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by RyanGaudion** [comment]
All resolved - data in db was corrupt
