### ISSUE TITLE
Excluding queries from compiled query cache

### ISSUE THREAD

**Issue by RichardD2** [dotnet/efcore#28689]
We have an API using EF Core 6.0.7 which builds queries based on user-supplied parameters. (Eg: filtering, sorting, paging, etc.)

As far as I can see, each time a different sort order or filter is specified, a new entry will be added to the `CompiledQueryCache`, resulting in increased memory usage.

Is there any way to tag queries which should not be cached?

**Comment by ajcvickers** [comment]
@RichardD2 This should not happen if the queries are built to be appropriately parameterized. If you are building parameterized queries and still hitting this, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by RichardD2** [comment]
@ajcvickers The problem is that the filters and sort order are specified by the user; they can't be parameterized.

Just running [this simple example](https://gist.github.com/RichardD2/b02320b15803450f38aaa7d69daea715), you can see that each time a query uses a different sort order - whether it's a different property, or a different order on the same property - a new "compiled query" cache entry is added.

Since the users can chose to sort by multiple properties, the number of cache entries can quickly grow unmanageable. Combined with the option to filter and search the entities, the memory usage from the compiled query cache just keeps on growing.

Rather than telling the users that they're not allowed to search or sort the data, I'm just looking for a way to indicate that a particular ad-hoc query doesn't need to have its compiled version cached.

**Comment by roji** [comment]
@RichardD2 the query cache is supposed to have an upper bound (1024 queries in total), so you should not be seeing unbounded growth here; can you confirm that?

Though it's true that even with an upper bound, the dynamic queries can push out non-dynamic hot queries, thereby hurting their performance.

**Comment by RichardD2** [comment]
@roji Is that limit documented anywhere? The only reference to 1024 I can see in the [Advanced Performance Topics](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#query-caching-and-parameterization) page relates to context pooling; the query caching section doesn't seem to mention a limit.

**Comment by roji** [comment]
@RichardD2 no, you're right - we don't currently mention this, as it's quite a low-level/internal detail. But regardless, can you confirm that you're indeed seeing memory usage not growing in an unbounded way (allow for time for the GC to collect memory created by all those compilations though)?

**Comment by RichardD2** [comment]
@roji As far as I can see, it doesn't seem to be growing unbounded at the moment. But as you said in your earlier comment, ad-hoc queries will probably be pushing more stable queries out of the cache, leading to more churn and additional recompilations.

**Comment by ajcvickers** [comment]
@RichardD2 We discussed this in triage and it was pointed out that a [compiled query]() can be used for this. For example, call [CompileQuery](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef.compilequery?view=efcore-6.0#microsoft-entityframeworkcore-ef-compilequery-2(system-linq-expressions-expression((system-func((-0-system-linq-iqueryable((-1)))))))) to get back a delegate for your query, and then throw it away when done.
