### ISSUE TITLE
Add global query filter dynamically to entity types that implement a specific interface

### ISSUE THREAD

**Issue by a510** [dotnet/efcore#28697]
I'm trying to implement a global query filter as described [here](https://docs.microsoft.com/en-us/ef/core/querying/filters) and this code works fine.

``` csharp
modelBuilder.Entity<Customer>().HasQueryFilter(b => EF.Property<int>(b, "TenantId") == tenantService.CurrentTenantId);
```

The problem is that I need to add this line of code for each entity type that has the `TenantId` property and if I missed this line for any entity the query will return data from all tenants which is a very unpleasant bug.
So, I'm trying to get all entity types that have `TenantId` property (i.e. implements `ITenantEntity` interface) and add the query filter to them dynamically but for some reason the code below throws an exception.

``` csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var entityTypes = modelBuilder.Model.GetEntityTypes().Where(a => typeof(ITenantEntity).IsAssignableFrom(a.ClrType)).ToList();
    foreach (var entityType in entityTypes)
    {
        modelBuilder.Entity(entityType.ClrType).HasQueryFilter((ITenantEntity b) => EF.Property<int>(b, nameof(ITenantEntity.TenantId)) == tenantService.CurrentTenantId);
    }
}
```

Exception:
```
System.InvalidOperationException: 'The filter expression ... specified for entity type 'Customer' is invalid. The expression must accept a single parameter of type 'Customer' and return bool.'
```

How can I achieve that ?

**Comment by ajcvickers** [comment]
@a510 Query filters currently need an expression per type. Making this easier is tracked by #24445.
