### ISSUE TITLE
Use reference counting to determine what members added by convention should be removed

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#2869]
Currently we do an explicit graph traversal to find if there are any references to the given member and remove it if there aren't. This could lead to an incorrect removal if the traversal is triggered by a convention invoked while a reference to the given member is being added.
The current method also doesn't recalculate the ConfigurationSource if a reference is removed (e.g. if an explicit relationship to a conventional entity type is removed the entity type will remain marked as added explicitly). This could lead to some orphan members not being removed.

**Comment by rowanmiller** [comment]
We will do this as part of https://github.com/aspnet/EntityFramework/issues/214 if we determine that it is needed when we implement that feature
