### ISSUE TITLE
System.ExecutionEngineException iOS Release

### ISSUE THREAD

**Issue by Kylar182** [dotnet/efcore#28710]
## File a bug

Related - 
[System.ExecutionEngineException iOS Release](https://github.com/dotnet/maui/issues/9176)
Linking this for info as the original may not be in the correct local.

**Comment by ajcvickers** [comment]
@Kylar182 I don't think there is anything actionable in EF here.

**Comment by Kylar182** [comment]
> @Kylar182 I don't think there is anything actionable in EF here.

Okay, close if you need too. Just wanted to make sure the information was shared.

**Comment by Ghevi** [comment]
@Kylar182 @ajcvickers I'm sorry, so the way to go is not using EF and try with another orm? or use sqlite without one?

**Comment by ajcvickers** [comment]
@Ghevi We're doing some further investigation here to make sure the issue is understood and tracked appropriately.

**Comment by IndexOutOfLimit** [comment]
Is there any tentative timeline when it could be fixed?
