### ISSUE TITLE
DbCommandInterceptor ReaderExecuted not firing for ExecuteReader() on command created by GetCommand()

### ISSUE THREAD

**Issue by rexxmagnus** [dotnet/efcore#28715]
ReaderExecuted on my DbCommandInterceptor is not triggering for ExecuteReader() when fired by a command created using GetCommand.

I am constructing commands using:

```C#
using var cmd = context.Database.GetDbConnection().CreateCommand();
// command creation code
using (var reader = cmd.ExecuteReader())
{
   // handle data
}
```

I have correctly configured a DbCommandInterceptor, overriding ReaderExecuted. I can capture execution of data updates via regular ef core method and triggering of stored procedures (when usingcontext.[dataset].FromSqlInterpolated(...) ) but using the above code to run updates or call stored procedures that have multiple result sets (hence not using FromSqlInterpolated in some cases) the ReaderExecuted event is never fired.

Is this by design, or a bug? If it's by design, is there a way to trigger the event on the interceptor/context manually?

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:net6.0
Operating system:
IDE: Visual Studio 2022 community 17.2.5

**Comment by roji** [comment]
@rexxmagnus this is by-design: EF Core's interceptors can only work when you use an EF Core API; but in the code above you're dropping down to the lower-level ADO.NET APIs, outside of EF's control. You'll have to specify your interception logic in the code driving ExecuteReader.

**Comment by rexxmagnus** [comment]
Thanks for the clarification. I'd assumed the logic ran on triggering of that method, but suspected it was something in the EF wrapper that fires the actual updates.
