### ISSUE TITLE
Getting Obsolete warnings from scaffolding

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#28743]
This is generated using EF Core 7 preview 7 reverse engineering:

```csharp
 modelBuilder.Entity<Category>(entity =>
            {
                entity.HasIndex(e => e.CategoryName)
                    .HasName("CategoryName");
```

Using latest daily runtime, I am getting obsolete warning on HasName (should be HasDatabaseName) 

But maybe it is a point in time issue?

**Comment by ErikEJ** [comment]
Tried 7.0.0-rc.1.22415.10 scaffolding, same issue

**Comment by roji** [comment]
Is everything OK here @ErikEJ?

**Comment by ErikEJ** [comment]
Yes, error 40 (bug in EF Core Power Tools)

**Comment by ErikEJ** [comment]
I see this now:

```csharp
    modelBuilder.Entity<Category>(entity =>
        {
            entity.HasIndex(e => e.CategoryName, "CategoryName");

```
