### ISSUE TITLE
EntityFramework.SqlServer beta6 fails to install in UWP apps in VS2015...

### ISSUE THREAD

**Issue by ArnaudFaucher** [dotnet/efcore#2876]
... but EntityFramework.Sqlite installs fine. (see `EntityFramework.SqlServer 7.0.0-beta6 is not compatible with UAP,Version=v10.0.` in the log below)

It there a framework problem in project.json for EntityFramework.SqlServer (should support 'dotnet' instead of 'dnxcore50') ???

```
Restoring packages for C:\Users\public.WIN-S1AFH7CB1FJ\documents\visual studio 2015\Projects\App1\App1\project.json...
Using source https://api.nuget.org/v3/index.json.
Using source https://www.myget.org/F/aspnetvnext/api/v2.
Using source https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/.
Restoring packages for UAP,Version=v10.0...
Resolving conflicts for UAP,Version=v10.0...
Scanning packages for runtime.json files...
...
Merging in runtimes defined in Package/System.Linq.Expressions 4.0.10-beta-23109.
Merging in runtimes defined in Package/System.Linq.Expressions 4.0.10-beta-23109.
Restoring packages for UAP,Version=v10.0 (win10-arm)...
Resolving conflicts for UAP,Version=v10.0 (win10-arm)...
Restoring packages for UAP,Version=v10.0 (win10-arm-aot)...
Resolving conflicts for UAP,Version=v10.0 (win10-arm-aot)...
Restoring packages for UAP,Version=v10.0 (win10-x86)...
Resolving conflicts for UAP,Version=v10.0 (win10-x86)...
Restoring packages for UAP,Version=v10.0 (win10-x86-aot)...
Resolving conflicts for UAP,Version=v10.0 (win10-x86-aot)...
Restoring packages for UAP,Version=v10.0 (win10-x64)...
Resolving conflicts for UAP,Version=v10.0 (win10-x64)...
Restoring packages for UAP,Version=v10.0 (win10-x64-aot)...
Resolving conflicts for UAP,Version=v10.0 (win10-x64-aot)...
Checking compatibility of packages on UAP,Version=v10.0.
Checking compatibility for App1 1.0.0 with UAP,Version=v10.0.
Checking compatibility for EntityFramework.Sqlite 7.0.0-beta6 with UAP,Version=v10.0.
Checking compatibility for EntityFramework.SqlServer 7.0.0-beta6 with UAP,Version=v10.0.
EntityFramework.SqlServer 7.0.0-beta6 is not compatible with UAP,Version=v10.0.
...
Some packages are not compatible with UAP,Version=v10.0.
...
EntityFramework.SqlServer 7.0.0-beta6 is not compatible with UAP,Version=v10.0 (win10-arm).
...
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).

```

**Comment by rowanmiller** [comment]
Hey,

The SQL Server provider can not be used in UWP apps. This isn't really an EF limitation but because the underlying ADO.NET SQL Client provider does not support UWP (at least not yet).

At this stage SQLite is the only provider that works on UWP (and the InMemory one too... but that is mostly for testing/prototyping).

~Rowan

**Comment by ArnaudFaucher** [comment]
Thanks Rowan,

Your "at least not yet" is reassuring. Do you know if there are plans for this support (which is very important for LOB apps)?

**Comment by rowanmiller** [comment]
@ArnaudFaucher I agree that this is an important scenario. Plenty of discussion about how we support this, not official commitment I can point you to at this stage.

**Comment by clinton05** [comment]
any updates on this???

**Comment by rowanmiller** [comment]
@clinton05 not yet, tackling SQL Server support on UWP will be a post 1.0.0 task. BTW the work to make this happen is mostly in the SQL Client code base - here is an issue in their project that you could add your voice to https://github.com/dotnet/corefx/issues/6751.

**Comment by Advanium** [comment]
@rowanmiller Is there any update on this?

The [EF core documentation](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/) states to install the SQL Server provider, yet the install fails on my UWP project:

> System.Threading.Thread 4.3.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).

**Comment by ErikEJ** [comment]
The SQL Server provider does not support UWP, as stated here: https://docs.microsoft.com/en-us/ef/core/providers/sql-server/

**Comment by aliatienza** [comment]
Posts are dated 2016. It's already 2017 going on 2018. May I know if EF is or will be applicable to UWP apps?
