### ISSUE TITLE
Typo in aka.ms link

### ISSUE THREAD

**Issue by rygargamel** [dotnet/efcore#28771]
The Remarks section has a type in an aka link.

As written:

## Remarks

See [Modeling entity types and relationships](https://aka.ms/efcore-docs-modeling) and [EF Core model-building conventions](https://aka.ms/efcore-docs-coventions) for more information.

https://aka.ms/efcore-docs-coventions should be https://aka.ms/efcore-docs-conventions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a863b34f-1e89-32ca-92e6-d825dbad21ad
* Version Independent ID: c6e736a1-3446-0b07-fa22-27e66e7bfe73
* Content: [ModelBuilder Constructor (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.modelbuilder.-ctor?view=efcore-3.1#microsoft-entityframeworkcore-modelbuilder-ctor(microsoft-entityframeworkcore-metadata-conventions-conventionset))
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/ModelBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/ModelBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Thanks, submitted #28770 to fix this.

**Comment by smitpatel** [comment]
I will update the live docs.
