### ISSUE TITLE
A method to configure all dbcontexts in the same service collection at one place.

### ISSUE THREAD

**Issue by CamusGao** [dotnet/efcore#28772]
I have more than one DbContext following the same rule(eg. naming convention). I need to apply the config for every dbcontext now and future.

`void ConfigureAllDbContextOptions(this IServiceCollection services,  Action<DbContextOptionsBuilder> optionsAction){}`
All the operation in optionsAction will be applied to all dbcontexts

**Comment by roji** [comment]
@CamusGao you can have all your contexts accept in their constructor some singleton service which you register in DI, and then call that type from the context's OnConfiguring. Below is a sample for the general idea:

```
// Common configuration service, to be registered in DI as a singleton
public class DbContextConfigurationManager
{
    public void Configure(DbContextOptionsBuilder optionsBuilder)
    {
        // Do common config here
    }
}

// Base class for all your contexts
public abstract class ConfigurableDbContextBase : DbContext
{
    private readonly DbContextConfigurationManager _configurationManager;

    public ConfigurableDbContextBase(DbContextConfigurationManager configurationManager)
        => _configurationManager = configurationManager;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => _configurationManager.Configure(optionsBuilder);
}
```

**Comment by CamusGao** [comment]
> 
The feature request is for convenience.
The idea you mentioned is ok but a bit inconvenience.  There is a problem that I can't force 3rd-part dbcontext and the dbcontext added by others in the future to extend my base db context type without communicating with their authors.
Currently I replace the ServiceDescriptors which ServiceType is DbContextOptions<> with mine and wrap the original factorys and my configure action into mine.
But there is also a problem that the replacement code must be put after all AddDbContext calls. 
Both of those two are inelegant.

**Comment by ajcvickers** [comment]
Note from triage: this is not something we plan to implement at the EF level.
