### ISSUE TITLE
UseMigrationsAssembly may not work on DNX

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2877]
DNX only loads assemblies listed as dependencies of the project. The point of `UseMigrationsAssembly` is to use the assembly for Migrations without actually referencing it. We do this because you may not want to deploy your migrations classes with your app.

We should verify the experience on other non-DNX projects too.

**Comment by rowanmiller** [comment]
I think not having to reference the assembly is a good thing, but if it's going to be difficult then I don't think it's critical to support for the initial release since the vast majority of apps will have it referenced.

**Comment by rowanmiller** [comment]
Discussed and decided this is just a limitation of DNX that we should not try and hack around. It will continue to work in other frameworks.

**Comment by davidfowl** [comment]
Can we easily fixed with a custom loader in the tool though.

**Comment by bricelam** [comment]
@davidfowl Yes, for the tool (#2748) that'll work. This issue is about the runtime. I don't think we want to spin up a design-time host there.

**Comment by davidfowl** [comment]
I see. Why wouldn't the app reference the project?

**Comment by rowanmiller** [comment]
@davidfowl because the project needs to reference the app :smile: (the migrations project needs to reference the project with the context... so you can't also have a reference the other way around).
