### ISSUE TITLE
`dotnet-ef database update` fails with PlatformNotSupported on Fedora Linux

### ISSUE THREAD

**Issue by christianfosli** [dotnet/efcore#28786]
## Potential bug description

`dotnet-ef database update` fails with a `System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient` error,
with dotnet-ef version 6.0.8, dotnet SDK 6.0.107 (installed from Fedora package repositories).

I found a similar error here https://github.com/dotnet/SqlClient/issues/1427, but it is supposed to be fixed already.
That issue also had a potential work-around: https://github.com/dotnet/SqlClient/issues/1427#issuecomment-1194517555 ,
but I'm not sure if I can pass `--arch` and `--os` into `dotnet-ef` tool execution?

**disclaimer** I'm not sure if this is an issue with Entity Framework, Microsoft.Data.SqlClient, .NET SDK, or fedora packagers. Feel free to move it / close it if it's not the correct place.

### Work-around

`dotnet-ef database update` succeeds from a mcr.microsoft.com/dotnet/sdk:6.0 docker container.

E.g.
```bash
docker run --rm -v "$PWD:/app" \
  -w /app `# adjust working directory as needed` \
  mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash -c "dotnet tool install -g dotnet-ef && ~/.dotnet/tools/dotnet-ef database update"
```

#### ef-test.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ef_test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8" />
  </ItemGroup>

</Project>
```

#### Program.cs:

Username and password removed from connection string. It connects to mssqlserver docker container.

```
using Microsoft.EntityFrameworkCore;

Console.WriteLine("Hello, World!");

public class Blog
{
	public int Id { get; set; }
	public string? Name { get; set; }
}

public class BloggingContext : DbContext
{
	public DbSet<Blog> Blog => Set<Blog>();
	
	protected override void OnConfiguring(DbContextOptionsBuilder options) =>
		options.UseSqlServer("Server=tcp:localhost,1433;Initial Catalog=ef-test;User ID=<userid>;Password=<password>;");
}
```

#### Shell commands

```bash
dotnet-ef migrations add InitialCreate # succeeeds
dotnet-ef database update # fails
```

### Include stack traces

```
System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Include verbose output

<details>
<summary>Verbose output</summary>
[cfosli ef-test]$ dotnet-ef database update --verbose
Using project '/home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj'.
Using startup project '/home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj'.
Writing '/home/cfosli/Gists-and-Prototypes/ef-test/obj/ef-test.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpSoS5kv.tmp /verbosity:quiet /nologo /home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj
Writing '/home/cfosli/Gists-and-Prototypes/ef-test/obj/ef-test.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpIjtz91.tmp /verbosity:quiet /nologo /home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj
Build started...
dotnet build /home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
        0 Error(s)
        
        Time Elapsed 00:00:02.28
        Build succeeded.
        dotnet exec --depsfile /home/cfosli/Gists-and-Prototypes/ef-test/bin/Debug/net6.0/ef-test.deps.json --additionalprobingpath /home/cfosli/.nuget/packages --runtimeconfig /home/cfosli/Gists-and-Prototypes/ef-test/bin/Debug/net6.0/ef-test.runtimeconfig.json /home/cfosli/.dotnet/tools/.store/dotnet-ef/6.0.8/dotnet-ef/6.0.8/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll database update --assembly /home/cfosli/Gists-and-Prototypes/ef-test/bin/Debug/net6.0/ef-test.dll --project /home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj --startup-assembly /home/cfosli/Gists-and-Prototypes/ef-test/bin/Debug/net6.0/ef-test.dll --startup-project /home/cfosli/Gists-and-Prototypes/ef-test/ef-test.csproj --project-dir /home/cfosli/Gists-and-Prototypes/ef-test/ --root-namespace ef_test --language C# --framework net6.0 --nullable --working-dir /home/cfosli/Gists-and-Prototypes/ef-test --verbose
        Using assembly 'ef-test'.
        Using startup assembly 'ef-test'.
        Using application base '/home/cfosli/Gists-and-Prototypes/ef-test/bin/Debug/net6.0'.
        Using working directory '/home/cfosli/Gists-and-Prototypes/ef-test'.
        Using root namespace 'ef_test'.
        Using project directory '/home/cfosli/Gists-and-Prototypes/ef-test/'.
        Remaining arguments: .
        Finding DbContext classes...
        Finding IDesignTimeDbContextFactory implementations...
        Finding application service provider in assembly 'ef-test'...
        Finding Microsoft.Extensions.Hosting service provider...
        No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
        No application service provider was found.
        Finding DbContext classes in the project...
        Found DbContext 'BloggingContext'.
        Using context 'BloggingContext'.
        Finding design-time services referenced by assembly 'ef-test'...
        Finding design-time services referenced by assembly 'ef-test'...
        No referenced design-time services were found.
        Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
        Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
        Finding IDesignTimeServices implementations in assembly 'ef-test'...
        No design-time services were found.
        'BloggingContext' disposed.
        System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
           at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
           at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
           at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
           at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
           at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
           at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
           at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
           at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
           at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
        Strings.PlatformNotSupported_DataSqlClient
</details>

### Include provider and version information

EF Core version: 6.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net6.0
Operating system: Fedora Linux 36 on Windows Subsystem for Linux
IDE: N/A

<details>
<summary>Output from `dotnet --info`</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.107
 Commit:    f6ec7508e3

Runtime Environment:
 OS Name:     fedoraremixforwsl
 OS Version:  36
 OS Platform: Linux
 RID:         fedora.36-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.107/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [/usr/lib64/dotnet/sdk]
  6.0.107 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>

**Comment by roji** [comment]
@christianfosli this error shouldn't be related to EF Core. Are you able to connect with the same connection string from a non-EF SqlClient console program?

**Comment by christianfosli** [comment]
> @christianfosli this error shouldn't be related to EF Core. Are you able to connect with the same connection string from a non-EF SqlClient console program?

Good point, I'll try that out.
I never used SqlClient directly before, just through Microsoft.EntityFrameworkCore.SqlServer.

**Comment by christianfosli** [comment]
With 

> @christianfosli this error shouldn't be related to EF Core. Are you able to connect with the same connection string from a non-EF SqlClient console program?

Using SqlClient directly I get the same behavior as https://github.com/dotnet/SqlClient/issues/1427#issuecomment-1194517555

```bash
dotnet run
```
 fails with PlatformNotSupported, but

```bash
dotnet run --arch x64 --os linux
```

works fine.

Do you know if `--arch` and `--os` can be passed to `dotnet-ef` tool?

**Comment by christianfosli** [comment]
I found a work-around I'm pretty happy with. Using .NET SDK from Docker and volume mounting the source code:

```bash
docker run --rm -v "$PWD:/app" \
  -w /app `# adjust working directory as needed` \
  mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash -c "dotnet tool install -g dotnet-ef && ~/.dotnet/tools/dotnet-ef database update"
```

Maybe this indicates that it's a problem with [dotnet source build](https://github.com/dotnet/source-build).
I know fedora builds dotnet using this tool, and I read [Canonical just started doing the same for Ubuntu](https://devblogs.microsoft.com/dotnet/dotnet-6-is-now-in-ubuntu-2204/).

**Comment by ajcvickers** [comment]
> Do you know if --arch and --os can be passed to dotnet-ef tool?

Passing `--runtime` on the command line should work.

**Comment by christianfosli** [comment]
> Passing `--runtime` on the command line should work.

That worked, thanks! :smile:

I used

```sh
dotnet-ef database update --runtime linux-x64
```

So I guess this should be closed as a duplicate of https://github.com/dotnet/SqlClient/issues/1427,
but maybe that issue should be reopened first?

**Comment by ajcvickers** [comment]
This is by-design behavior from the EF perspective.

**Comment by christianfosli** [comment]
I found another issue describing the bug in SqlClient btw, see https://github.com/dotnet/SqlClient/issues/1423
This one is still open, so I guess no need to reopen https://github.com/dotnet/SqlClient/issues/1427 after all.
