### ISSUE TITLE
When you run "dotnet ef migrations add Blogs" in command prompt, you get an error: "your startup project doesn't reference Microsoft.EntityFrameworkCore.Design."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/efcore#28785]
**Azure DevOps work item:**
https://devdiv.visualstudio.com/DevDiv/_queries/edit/1593279

**Testcases Affected**
[SimpleWebAppWithNoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VS/AspNetCore60/60_SimpleWebAppWithNoAuth.md)

**Repro Steps**
1. File > New project > ASP.NET Core Web App > .NET 7.0 > Create
1. Right-click the project > Manage NuGet Packages > Navigate to Browse tab, check "Include prerelease" and set Packages source to All
1. Install the package Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Tools with the version which matches (are same or older than) the latest runtime verion under C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App
1. Create a folder called 'Models' in Solution Explorer, Right-click the Models folder to add a class called 'Blog.cs' and paste the following code
```
namespace SimpleWebAppWithNoAuth1.Models
{
    public class BloggingContext : DbContext
    {
        public BloggingContext(DbContextOptions<BloggingContext> options)
            : base(options)
        { }
        public DbSet<Blog>? Blogs { get; set; }
    }
    public class Blog
    {
        public int BlogId { get; set; }
        public string? Url { get; set; }
    }
}
```

5. Open appsettings.json file and add a new connection to the ConnectionStrings section 

```
"ConnectionStrings": {
    "BlogConnection": "Server=(localdb)\\mssqllocaldb;Database=SimpleWebAppWithNoAuth1;Trusted_Connection=True;"
},
```
6. Open Program.cs and add the following AddDbContext method
```
var connectionString = builder.Configuration.GetConnectionString("BlogConnection") ?? throw new InvalidOperationException();
builder.Services.AddDbContext<BloggingContext>(options => options.UseSqlServer(connectionString));
```

7. Right click the project > Open Folder in File Explorer, open up a nomal Command Prompt, navigate to project directory
8. Run "dotnet ef migrations add Blogs"

**PackageReference：**
![image](https://user-images.githubusercontent.com/71361488/185578738-caf09e94-bc3f-4dfd-bcb0-8b0f0c449653.png)

**Actual Result**
Your startup project 'webapplication1' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package and tyr again.
![image](https://user-images.githubusercontent.com/71361488/185579354-656a42a9-425c-40ae-a227-ed2a1945d864.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/71361488/185584396-3f421070-4a0f-4aa1-82e9-ab4bab7c4fad.png)

**Comment by ajcvickers** [comment]
@v-sherryfan Are the packages restored correctly after step 3?

**Comment by v-sherryfan** [comment]
@ajcvickers  Yes the package is restored correctly after step 3.

![image](https://user-images.githubusercontent.com/71361488/185831983-40252c5e-e3f1-46ba-b517-675acef40d18.png)
![image](https://user-images.githubusercontent.com/71361488/185832095-aee709ca-1b55-4e03-8bf2-55577dfd406d.png)

**Comment by ajcvickers** [comment]
@v-sherryfan Please attach the project in the state that it doesn't work so that we can investigate.

**Comment by v-sherryfan** [comment]
@ajcvickers Solved the problem by saving the changes files and building the project, so I will close this issue.
