### ISSUE TITLE
Json: add support for Sqlite provider

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#28816]
Currently Json support is only for SqlServer, we should light it up for sqlite also. Infrastructure is in relational so this shouldn't be too much work

**Comment by ajcvickers** [comment]
Consider a better exception if we don't get to this in 8: #29632

**Comment by Jogai** [comment]
> Consider a better exception if we don't get to this in 8: #29632

A better exception in 7 would've been nice too. This is what npgsql does: https://github.com/npgsql/efcore.pg/blob/03f9eb362cdd116b66af0c2c08983368b080d569/src/EFCore.PG/Infrastructure/Internal/NpgsqlModelValidator.cs#L197
