### ISSUE TITLE
Json: allow customizing (some) serialization options when creating json, so that it's more readable

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#28815]
Currently we use default serialization options, but it would be nice to allow some customization in how the json looks (e.g. casing of property names. Similar thing was asked on npg: https://github.com/npgsql/efcore.pg/issues/1107

**Comment by alienwareone** [comment]
@maumar What are the default serialization options?
I was expecting that enum values are serialized to int values by default, but they are serialized as string values.
(Which is desired by myself but I'm curious why?)

```
enum Test { One, Two, Three }

[Fact]
public async Task Json_serialize_enum_as_int_value()
{
    var test = Test.Two;
    var json = System.Text.Json.JsonSerializer.Serialize(test);
    json.Should().Be("1");
}
```

**Comment by maumar** [comment]
dupe of https://github.com/dotnet/efcore/issues/28043
