### ISSUE TITLE
API for raw JSONPATH queries

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28824]
#28616 tracks translating LINQ operators inside JSON documents to JSONPATH. But just like we have raw SQL query APIs, we should also have a raw JSONPATH API, which allows the user to directly provide a JSONPATH string query and get results out. This would act as an escape hatch API for when we don't support a LINQ translation.

Ideal LINQ construct (would be possible as part of #28616):

```c#
ctx.Entity.Where(e => e.JsonThing.Track.Segments.Any(s => s.HR > 130))
```

Escape hatch with raw JSONPATH:

```c#
ctx.Entity.Where(e => EF.Functions.Jsonpath<Segment>(e.JsonThing, "$.track.segments[*].HR ? (@ > 130)"))
```

We may need different functions, one for returning an enumerable and another for returning a single thing (e.g. JSON_VALUE vs. JSON_QUERY in SQL Server).

**Comment by ajcvickers** [comment]
Note from triage: @ajcvickers to test and document the wokaround.

**Comment by roji** [comment]
Given that JSONPATH support is very limited across databases (see https://github.com/dotnet/efcore/issues/28616#issuecomment-1320956002), this probably doesn't make sense as a relational feature. PostgreSQL can implement support for this as a provider-specific translation.
