### ISSUE TITLE
Query: Change JsonQueryExpression.Path to be a List<PathSegment>

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#28836]
Where PathSegment can be either 
KeyAccess which is string joined using `.`
ArrayAccess which is SqlExpression using `[]`
Or random string which we would just append, in case provide wants to add more fancier thing.

It cannot be SqlExpression even though SQL syntax allows it because neither user can write a LINQ query which accesses an arbitrary key on an object using column/parameter nor we can translate it because we need metadata of the bound property in order to materialize.

**Comment by roji** [comment]
> It cannot be SqlExpression even though SQL syntax allows it because neither user can write a LINQ query which accesses an arbitrary key on an object using column/parameter nor we can translate it because we need metadata of the bound property in order to materialize.

I'm not sure how much we're designing with weakly-typed JSON mapping in mind... But if so, then the above is definitely possible (and important). For example, the PG provider supports the following:

```c#
_ = ctx.JsonEntities.Single(e => e.CustomerElement.GetProperty("Name").GetString() == "Joe");
```

... where GetProperty is an expression-based way to access arbitrary properties (or keys) on JSON elements. We may not allow materializing the result, but at the very least if the query represents a scalar we can read it back or generate a SQL expression that compares it to something, as above.

But maybe you have something else in mind for when we implement weakly-typed JSON...

**Comment by smitpatel** [comment]
> weakly-typed JSON mapping

Weakly-typed JSON doesn't work in EF Core metadata. We cannot translate it and generate metadata for materializing. Bottom-line is weakly-typed JSON, even if we support it cannot use any of the code we have added for now. Let's not ruin the design for the sake of something which will never use the design in first place.

**Comment by roji** [comment]
Up to you, of course. JsonQueryExpression specifically looks like it should be usable for weakly-typed, since it simply expresses traversal... But we can deal with it later, as you wish.

**Comment by smitpatel** [comment]
Well `JsonQueryExpression` contains `IEntityType`, it cannot support weakly-typed.

**Comment by smitpatel** [comment]
In future if we add support for weakly-typed, we could create expression to support weakly-typed and use wrapper over it in place of current expressions we use to add additional metadata.

**Comment by roji** [comment]
Makes sense.
