### ISSUE TITLE
How to properly migrate column from nullable to non-nullable

### ISSUE THREAD

**Issue by NiJeTi** [dotnet/efcore#28849]
So I have a database entity with nullable property and a lot of data in the related table. I want to make this property non-nullable. If I just remove question mark from it's type and create a migration EF generates this:
```C#
migrationBuilder.AlterColumn<DateTime>(
    name: "CreatedDate",
    table: "Attachments",
    type: "timestamp without time zone",
    nullable: false,
    defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
    oldClrType: typeof(DateTime),
    oldType: "timestamp without time zone",
    oldNullable: true);
```
According to logs this code lately being translated to such code:
```SQL
alter table "Attachments"
    alter column "CreatedDate" set not null;
alter table "Attachments"
    alter column "CreatedDate" set default timestamp '-infinity';
```
Eventually all this operations lead to application fail to start.

What is a correct way to perform migrations like this?

### Stack trace
![2022-08-23_16-54](https://user-images.githubusercontent.com/5685857/186178042-dd8ffa97-9b63-44ee-a21c-e4f08ccc46a3.png)
 
### Provider and version information

EF Core version: 6.0.1
Database provider: PostgreSQL
Target framework: .NET 6
Operating system: Windows 10
IDE: JetBrains Rider 2022.2.1

**Comment by roji** [comment]
I can see the same thing happening with SQL Server when making a nullable string property non-nullable:

```sql
ALTER TABLE [Blogs] ALTER COLUMN [Name] nvarchar(max) NOT NULL;
ALTER TABLE [Blogs] ADD DEFAULT N'' FOR [Name];
```

I'm not 100% sure, but it seems like we intend to add the default before making the column non-nullable, so that the ALTER COLUMN succeeds, but the ordering is wrong?

**Comment by NiJeTi** [comment]
> I'm not 100% sure, but it seems like we intend to add the default before making the column non-nullable, so that the ALTER COLUMN succeeds, but the ordering is wrong?

I've tested this too but it did not work. So my current workaround is to modify the `Up` method of the migration to perform data update before altering column.

**Comment by bricelam** [comment]
Duplicate of #21765 for SQL Server. I think Npgsql can fix it independently. IIRC it was already fixed in the Pomelo provider.

**Comment by roji** [comment]
Thanks @bricelam, I'll take a look for Npgsql and also for SQL Server.

**Comment by roji** [comment]
Opened https://github.com/npgsql/efcore.pg/issues/2483 to track on the Npgsql side, closing this as a dup of #21765.

**Comment by roji** [comment]
Duplicate of #21765
