### ISSUE TITLE
EF7 TPC Mapping Strategy generates duplicate index names for navigation properties declared in base type

### ISSUE THREAD

**Issue by benedict-odonovan** [dotnet/efcore#28848]
Using .UseTpcMappingStrategy() with a base type that includes navigation properties will generate a migration that cannot be used because of duplicate index names. The index names use the base type's name `base_entity_trackables` rather than that of the child's table `candidates`.

Models:
```C#
public abstract class BaseEntityTrackable<TKey>
{
    public TKey Id { get; set; }
    public DateTime CreatedOn { get; set; }
    public int CreatedById { get; set; }
    public Consultant CreatedBy { get; set; }

    public DateTime EditedOn { get; set; }
    public int EditedById { get; set; }
    public Consultant EditedBy { get; set; }
}

[Table("candidates")]
public class Candidate : BaseEntityTrackable<int>
{
    public string FirstName { get; set; }
}

[Table("addresses")]
public class Address : BaseEntityTrackable<int>
{
    public string? PostCode { get; set; }
}

[Table("consultants")]
public class Consultant
{
    public int Id { get; set; }
}
```

OnModelCreating:
```C#

public DbSet<BaseEntityTrackable<int>> BaseEntityTrackables { get; set; }
public DbSet<Candidate> Candidates { get; set; }
public DbSet<Address> Addresses { get; set; }
public DbSet<Consultant> Consultants { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<BaseEntityTrackable<int>>().UseTpcMappingStrategy();

    modelBuilder.Entity<BaseEntityTrackable<int>>().Property(e => e.CreatedOn).HasDefaultValueSql("current_timestamp").ValueGeneratedOnAdd();
    modelBuilder.Entity<BaseEntityTrackable<int>>().Property(e => e.EditedOn).HasDefaultValueSql("current_timestamp").ValueGeneratedOnAddOrUpdate();
}
```

Generates:

```C#
            migrationBuilder.CreateIndex(
                name: "ix_base_entity_trackables_created_by_id",
                table: "addresses",
                column: "created_by_id");

            migrationBuilder.CreateIndex(
                name: "ix_base_entity_trackables_edited_by_id",
                table: "addresses",
                column: "edited_by_id");

            migrationBuilder.CreateIndex(
                name: "ix_base_entity_trackables_created_by_id",
                table: "candidates",
                column: "created_by_id");

            migrationBuilder.CreateIndex(
                name: "ix_base_entity_trackables_edited_by_id",
                table: "candidates",
                column: "edited_by_id");
```

When `update-database` is run the following error is returned:
`42P07: relation "ix_base_entity_trackables_created_by_id" already exists`

### Include provider and version information

EF Core version: 7.0.0-preview.7.22376.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL:7.0.0-preview.7
Target framework: (e.g. .NET 5.0) .NET 6.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3) Visual Studio 2022 17.3

**Comment by AndriySvyryd** [comment]
@benedict-odonovan I am not able to repro this and I also get different names for properties. Are using `EFCore.NamingConventions` by any chance? If so, you'll need to file an issue at https://github.com/efcore/EFCore.NamingConventions/issues to add support for TPC

**Comment by benedict-odonovan** [comment]
Thanks - you were spot on. Removing `.UseSnakeCaseNamingConvention()` from `builder.Services.AddDbContext<EntityContext>` solved the issue immediately.

**Comment by majorregal** [comment]
@AndriySvyryd Thank you so much!
Was going crazy by not understanding why I had this issue and when I read your comment mentioning `EFCore.NamingConventions` it dawned on me.
Wasn't even considering that this could be an issue.
Thanks again!
