### ISSUE TITLE
Prevent EF Core from generating foreign key

### ISSUE THREAD

**Issue by Sn3b** [dotnet/efcore#28853]
I'd like to create an entity that keeps a reference to a clone of itself, and that clone would actually be serialised to json before saving to database.

```C#
public class Foo
{
    public string StringProperty { get; set; }
    public int IntProperty { get; set; }
    public Foo Snapshot { get; set; }
}
```
```C#
public class FooConfiguration : IEntityTypeConfiguration< Foo >
{
    public virtual void Configure( EntityTypeBuilder< Foo > builder )
    {
        builder.Property( e => e.StringProperty );
        builder.Property( e => e.IntProperty )
               .IsRequired();
        builder.Property( e => e.Snapshot )
               .HasConversion( new FooToJsonConverter() );
    }
}
```
The problem is that because EF knows about Foo (it is referenced in the context and there is a fluent configuration file for it) it creates a foreign key. Even when I try to ignore it with builder.Ignore( e => e.Snapshot ).

I have successfully serialised another type with a custom converter, but that other type is unknown to EF (no reference in the context and no fluent configuration file).

Is there a way to achieve this?

**Comment by roji** [comment]
> Even when I try to ignore it with builder.Ignore( e => e.Snapshot ).

This should work, making EF ignore the property entirely; the minimal code sample at the bottom works for me, and produces the following table:

```sql
CREATE TABLE [Blogs] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(max) NULL,
    CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
);
```

As you can see, there's no trace of the Snapshot property in the actual database schema created. If Snapshot isn't getting properly ignored, please post a minimal code sample such as the below, or just tweak the below to show the problematic behavior.

<details>
<summary>Ignore code sample</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Ignore(b => b.Snapshot);
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Blog Snapshot { get; set; }
}
```

</details>

**Comment by Sn3b** [comment]
So while preparing a mini project to show you my issue I rearranged some generic parameters and stuff, and now it works 😅

So it was my fault and indeed the property is properly ignored or converted to a nvarchar(max) for the serialised snapshot 🎉

Thanks for your support!
