### ISSUE TITLE
EF5 to EF6 getting 'Unable to translate set operation when matching columns on both sides have different store types.'

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/efcore#28865]
EF Core version: 6.08
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 10
IDE: VS 17.3.2

After migrating from EF5 to EF6 and and  .NET 5 to .NET 6 we get above error from this query

```csharp
        public async Task<IEnumerable<ReconcilationSummaryData>> Handle(GetReconciliationSummaryQuery query)
        {
            return await _ctx.Set<PaymentTransaction>()
                .Where(pt => !pt.Balanced && pt.PaymentState == PaymentState.PaymentComplete)
                .Select(pt => new
                {
                    Amount = pt.PaymentDirection == PaymentDirection.Incoming ? pt.Amount : -pt.Amount,
                    pt.PaymentCategory,
                    pt.ReferredAccount.AccountNumber,
                    pt.ReferredAccount.AccountName,
                    pt.ReferredAccount.BgcCustomer.ExternalSystem
                })
                .Concat(_ctx.Set<PaymentTransactionAggregation>()
                    .Select(pta => new
                {
                    pta.Amount,
                    pta.PaymentCategory,
                    pta.ReferredAccount.AccountNumber,
                    pta.ReferredAccount.AccountName,
                    pta.ReferredAccount.BgcCustomer.ExternalSystem
                }))
                .GroupBy(pt => new {pt.PaymentCategory, pt.AccountNumber, pt.AccountName, pt.ExternalSystem })
                .Select(g => new ReconcilationSummaryData
                {
                    AccountNumber = g.Key.AccountNumber,
                    AccountName = g.Key.AccountName,
                    Category = (TransactionCategory) g.Key.PaymentCategory,
                    ServiceType = (ServiceTypeEnum) g.Key.ExternalSystem,
                    Amount = g.Sum(pt => pt.Amount)
                })
                .ToListAsync();
        }
```

**Comment by smitpatel** [comment]
We need a full runnable repro.

**Comment by AndersMalmgren** [comment]
> We need a full runnable repro.

All right I'll try to create a repro tomorrow

**Comment by AndersMalmgren** [comment]
[EF6Repro.zip](https://github.com/dotnet/efcore/files/9422967/EF6Repro.zip)

Make sure the dacpac project have been built. run program.

Code found in Program.cs is relevant. Rest is just copied plumbing code to get it as close to the real deal as possible.

**Comment by AndersMalmgren** [comment]
@smitpatel Have you guys had time to look at the repro? 

Thanks

**Comment by ajcvickers** [comment]
@AndersMalmgren Configuration of `PaymentTransaction.Amount` is invalid:

```C#
builder.Property(p => p.Amount)
    .HasColumnType("decimal(18,2")
    .IsRequired();
```

Correcting it to:

```C#
builder.Property(p => p.Amount)
    .HasColumnType("decimal(18,2)")
    .IsRequired();
```

fixes the error in the given repro.

**Comment by AndersMalmgren** [comment]
> @AndersMalmgren Configuration of `PaymentTransaction.Amount` is invalid:
> 
> ```cs
> builder.Property(p => p.Amount)
>     .HasColumnType("decimal(18,2")
>     .IsRequired();
> ```
> 
> Correcting it to:
> 
> ```cs
> builder.Property(p => p.Amount)
>     .HasColumnType("decimal(18,2)")
>     .IsRequired();
> ```
> 
> fixes the error in the given repro.

haha, crazy it worked in EF5. Would never have caught that one. Maybe a better error message would be in order :P

**Comment by vslee** [comment]
@AndersMalmgren consider using the strongly typed `HasPrecision(int precision, int scale)` to prevent this issue from occuring.

```cs
 builder.Property(p => p.Amount)
.HasPrecision(18, 2)
 .IsRequired();
```

Or use the attribute ```[Precision(18, 2)]```

**Comment by AndersMalmgren** [comment]
> @AndersMalmgren consider using the strongly typed `HasPrecision(int precision, int scale)` to prevent this issue from occuring.
> 
> ```cs
>  builder.Property(p => p.Amount)
> .HasPrecision(18, 2)
>  .IsRequired();
> ```
> 
> Or use the attribute `[Precision(18, 2)]`

Good point, thanks!
