### ISSUE TITLE
[Question] How to build table metadata at runtime via migration API and generate DDL.

### ISSUE THREAD

**Issue by anchurcn** [dotnet/efcore#28864]
Are there APIs in ef core to do things like following?
```csharp

// Use Npgsql ef provider.

MigrationBuilder migrationBuilder = TheApiWhatIWant();

// The db schema from outside (maybe a xml)
dynamic dbSchema = null;

foreach (var table in dbSchema)
{
    migrationBuilder.CreateTable(table.Name);

    foreach (var column in table)
    {
        migrationBuilder.AddColumn(column.Name, table.Name, column.Type);
    }
}

IMigrator migrator = TheApiWhatIWant(migrationBuilder);
var ddlScript = migrator.GenerateScript();

```
Thanks

**Comment by roji** [comment]
@anchurcn can you provide some more context on why you'd like to do the above, and why you don't want to (or cannot) use regular EF patterns with migrations?

**Comment by smitpatel** [comment]
There are no CLR type to use model building API. It is just some form of serialization of database schema.

**Comment by anchurcn** [comment]
My purpose is to make a tool like Navicat to migrate database and the tool can be used by the end user.
The tool provides migration version control, custom type mapping...
The source db have no Navicat support, no ef support.

**Comment by anchurcn** [comment]
cc @roji @smitpatel

**Comment by roji** [comment]
@anchurcn EF's migrations feature wasn't designed to be used this way. However, something like the following works:

```c#
var migrationBuilder = new MigrationBuilder("SqlServer");

migrationBuilder.CreateTable(
    name: "Blogs",
    columns: table => new
    {
        Id = table.Column<int>(type: "int", nullable: false)
            .Annotation("SqlServer:Identity", "1, 1"),
        Name = table.Column<string>(type: "nvarchar(max)", nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Blogs", x => x.Id);
    });

var services = new ServiceCollection()
    .AddEntityFrameworkDesignTimeServices()
    .AddDbContextDesignTimeServices(ctx);
new SqlServerDesignTimeServices().ConfigureDesignTimeServices(services);
var serviceProvider = services.BuildServiceProvider();

var migrationsSqlGenerator = serviceProvider.GetService<IMigrationsSqlGenerator>();

var migrationCommands = migrationsSqlGenerator.Generate(migrationBuilder.Operations);

foreach (var command in migrationCommands)
{
    Console.WriteLine(command.CommandText);
}
```

This currently requires using an internal service (SqlServerDesignTimeServices), but isn't too bad (/cc @bricelam).

**Comment by bricelam** [comment]
> This currently requires using an internal service (SqlServerDesignTimeServices)

Here's the non-internal way to do it:

```cs
var providerAssembly = Assembly.Load("Microsoft.EntityFrameworkCore.SqlServer");
var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
var providerServicesType = providerAssembly.GetType(providerServicesAttribute.TypeName);
var providerServices = (IDesignTimeServices)Activator.CreateInstance(providerServicesType);
providerServices.ConfigureDesignTimeServices(services);
```

**Comment by ajcvickers** [comment]
@roji @bricelam Doesn't this require that an EF Core database provider is available for the target database? It's my assumption that "no ef support." means that there isn't a provider.

**Comment by roji** [comment]
@ajcvickers yeah, this would definitely require having the right EF provider for the database being targeted (since actual SQL varies considerably from database to database). I'm not sure what @anchurcn is looking for exactly and whether the provider is a problem or not...

**Comment by anchurcn** [comment]
@roji I'm using the efcore.pg. This sort of internal API has no ef core abstraction?

**Comment by roji** [comment]
@anchurcn no, but as @bricelam showed above, you can do all this via public APIs, so you can just wrap this code in a method. Using EF Core's migration SQL generation like this, completely detached from the rest of EF (e.g. without a model) is extremely uncommon.

**Comment by bricelam** [comment]
@anchurcn Are you looking for a library like [Fluent Migrator](https://fluentmigrator.github.io/)?
