### ISSUE TITLE
Consider removing unnecessary CASTs around JSON_VALUE

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28881]
We currently generate JSON queries such as the following:

```sql
SELECT [a].[Id], [a].[Name], JSON_QUERY([a].[Contact],'$')
FROM [Authors] AS [a]
WHERE CAST(JSON_VALUE([a].[Contact],'$.Address.City') AS nvarchar(max)) = N'Chigley'
```

We seem to systematically wrap JSON_VALUE with a CAST to the specific type - we should consider whether this is actually necessary and when.

Aside from the general verbosness/ugliness factor and unknown perf implications, I expect users will just follow the [SQL Server documentation for JSON indexes](https://docs.microsoft.com/en-us/sql/relational-databases/json/index-json-data?view=sql-server-ver16#example-index), which instruct users to create a virtual computed column with the JSON_VALUE expression, and create an index over that. I expect lots of users won't know to include the CAST inside their compuetd column, leading to the index not getting used.

**Comment by roji** [comment]
FYI, the cast causes SQL Server to do an index scan instead of a seek, which causes a **very** significant perf degradation. We should really prioritize this (and possibly even consider patching, if it's really low-risk). See https://github.com/roji/JsonColumnsPerf for more details.

**Comment by ErikEJ** [comment]
And you cannot create indexes on nvarchar(MAX) columns...

**Comment by ErikEJ** [comment]
Re-open to consider for current?

**Comment by ajcvickers** [comment]
I may have drunk a glass or two of wine, but fuck it, let's patch this!

**Comment by ErikEJ** [comment]
That will make a lot of DBAs happy and Reduce carbon footprint 😅

**Comment by ajcvickers** [comment]
Rejected for servicing: "It's only perf on a new feature (not a regression) and no customers have reported an impact on their business."

**Comment by ErikEJ** [comment]
Too bad. Assume it is in 8.0 today?

**Comment by ajcvickers** [comment]
Yes.
