### ISSUE TITLE
Support filtered Include in EF Core 3

### ISSUE THREAD

**Issue by evannah** [dotnet/efcore#28895]
Hello,
Could you support filtered Include in EF Core 3 ?
Thank you.

_Originally posted by @evannah in https://github.com/dotnet/efcore/issues/1833#issuecomment-1228282572_

**Comment by ErikEJ** [comment]
EF Core 3.1 will be out of support by the end of this year, and currently on gets security fixes.

**Comment by evannah** [comment]
Thank you @ErikEJ .
Does it mean the only way to get new features from EF Core is to migrate to .NET 6?
I'm stuck with .NET Framework 4.7.2 because of some libraries that are not available for the newer platforms :(
Thanks!

**Comment by ErikEJ** [comment]
Correct. 

Wonder what those libraries are and if there are replacements or alternatives available?

**Comment by evannah** [comment]
@ErikEJ Too bad.
The library that's preventing me from migrating to .NET 6 is Sharepoint 2013 on-premises CSOM : https://www.nuget.org/packages/Microsoft.SharePoint2013.CSOM/
Would have to migrate to a newer Sharepoint version, or rewrite all the code using Sharepoint's REST API instead.
Anyways, thank you for your help!

**Comment by roji** [comment]
Thanks @ErikEJ. Yeah, unfortunately staying on .NET Frameworks means that no new features will become available; it's highly recommended to plan for a transition to modern .NET.
