### ISSUE TITLE
Concurrency Check

### ISSUE THREAD

**Issue by NormanGiHu** [dotnet/efcore#28896]
Hello,

we are working on a big migration project with many tables in a MS-SQLServer database.

Is it possible to handle every exisiting field (or table column) in ef core dbcontext with "[ConcurrencyCheck]" per default, i.e. without annotating every column with [ConcurrencyCheck] and without to add to every table an additional "RowVersion"- column?

The goal is to get an exception. every time any field of a modified row was changed in the database externally too, after ef core did read the Original Values.

**Comment by ErikEJ** [comment]
You should be able to loop over all entities:

```csharp
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                foreach (var property in entity.GetProperties())
                {
                    property.IsConcurrencyToken = true;
                }
            }

```

**Comment by NormanGiHu** [comment]
Hello Erik,
thank you for your quick reply.

Are then (big) performance issues or other problems to expect?
If not this could be a solution for us.

**Comment by roji** [comment]
@NormanGiHu can you please provide more context on why you want to do this, as opposed to using a rowversion? This solution would mean that EF sends all your properties to the database on *every* update, just to detect whether any column change. This could affect performance and network load in a significant manner.

**Comment by NormanGiHu** [comment]
@roji In our current project we have an old (20+ years) ms-sql database which was used with Access as UI. 
The database contains around 400 Tables where most of them have no timestamp and not one has a rowversion column.

Now the UI is going to be changed to WPF (.net 6).
We reverse engineered the ef core models with ef core PT (@ErikEJ :+1: ).

A requirement for the project is not to use simple optimistic concurency handling.

Instead at least the wpf user has to be informed, that on saving he would be overwriting data, which was externally changed in the db.

using a rowversion column would mean to modify 300-400 tables.

**Comment by roji** [comment]
I'd still highly recommend addding the rowversions. Although it sounds daunting, adding a rowversion column to all tables can be automated with a quick SQL script. Making all your properties concurrency tokens really isn't a very good idea.

But if that's what you want to do, then @ErikEJ's code snippet above should work.
