### ISSUE TITLE
Migrations: Is there any way to change the AUTO_INCREMENT constraint?

### ISSUE THREAD

**Issue by buzzers** [dotnet/efcore#28910]
We are using TiDB, which provides a way of generating primary key data similar to AUTO_INCREMENT called AUTO_RANDOM.
AUTO_RANDOM and efcore work just fine until we want to use the migration feature. 
I didn't find a way to change the AUTO_INCREMENT constraint of the generated primary key to AUTO_RANDOM,
which prevented us from taking advantage of the migration feature.
Is there any way to do this now?

EF Core version: 6.0
Database provider: TiDB + Pomelo.EntityFrameworkCore.MySql
Target framework: NET 6.0
Operating system: Debian 11
IDE: Visual Studio Code

**Comment by roji** [comment]
@buzzers that sounds like a MySQL-specific question, which isn't maintained in this repo - can you please open this in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?

**Comment by ajcvickers** [comment]
@buzzers It's worth pointing out that scaffolded migrations are intended to be edited when necessary. This might be a case where editing the migration to create an `AUTO_RANDOM` column is appropriate.

**Comment by buzzers** [comment]
@ajcvickers But the problem here is that adding `AUTO_INCREMENT` is up to the provider. It cannot be changed by modifying the generated migration code.

**Comment by ajcvickers** [comment]
@buzzers If that's the case, then as @roji says, it would need to be addressed by the provider.

**Comment by buzzers** [comment]
@ajcvickers yes, I did it by inherit `MySqlMigrationsSqlGenerator` and overriding some methods, 
but it's not a very elegant solution. 
I am looking to see if there is a better solution.

**Comment by roji** [comment]
@buzzers have you opened an issue to flag this in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql? If so, can you please point to it here?

**Comment by buzzers** [comment]
@roji yes, PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1702
