### ISSUE TITLE
How to query array contains array with Azure CosmosDB with EFCore

### ISSUE THREAD

**Issue by klyse** [dotnet/efcore#28929]
I'm using
`dotnet 7.0.100-preview.7.22377.5`
`Microsoft.EntityFrameworkCore 7.0.0-preview.7.22376.2`
`Microsoft.EntityFrameworkCore.Cosmos 7.0.0-preview.7.22376.2`

I have a Serverless Azure CosmosDB with an SQL container.

In the SQL container I'm storing documents that contain, amon others, an array of strings (`Tags`):
```json
{
    "Name": "another test",
    "Tags": ["test", "test2"], <= array of strings
    "id": "aaa",
    "_rid": "xxx",
    "_self": "xxx",
    "_etag": "xx",
    "_attachments": "attachments/",
    "_ts": 1661800590
},
{
    "Name": "another test",
    "Tags": ["tag1", "tag2", "tag3"], <= array of strings
    "id": "bbb",
    "_rid": "xxx",
    "_self": "xxx",
    "_etag": "xx",
    "_attachments": "attachments/",
    "_ts": 1661800590
}
```

Task:
Query input: Array of `Tags` (`["tag1", "tag2"]`)
Objective: Qerry all documents from the database that have the Tags `tag1` and `tag2` like example document `id` `bbb`

Example query:
```csharp
var query = _dbContext.Documents.AsNoTracking();
foreach (string tag in queryTags)
{
	query = query.Where(doc => doc.Tags.Contains(tag));
}
```

Exception:
```
Translation of method 'System.Linq.Enumerable.Contains' failed.
```

# Question:

How can I query CosmosDB documents that contain a list of tags by another list of tags? The goal is to have a REST API that can filter documents based on tags.

**Comment by ajcvickers** [comment]
This is tracked by #25765.  Make sure to vote (👍) for that issue if this feature is important to you.

**Comment by klyse** [comment]
Hi @ajcvickers, thanks for the link to the correct PR. Is this a efcore limitation or a cosmosDb limitation?
Do you think using a [User-defined function](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-udfs) makes sense in this case or should I apply the filter locally (in memory)? I expect to have tops 5.000 documents. I also expect to have many executions of the query however.

**Comment by ajcvickers** [comment]
@klyse It's a limitation in the EF provider. Probably the best workaround is to write a raw SQL query for this case: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#raw-sql-queries-with-fromsql

**Comment by klyse** [comment]
@ajcvickers thanks for the response. Is there a way to append a SQL query to a linq query? In oder that only a small part must be written AND MAINTAINED in the RAW query. Something like: https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#composing-with-linq but after the initial filters:

```csharp
var query = _dbContext.Tasks
	.Where(c => c.Name == "x")
	.FromSqlRaw("where some query")
``

**Comment by ajcvickers** [comment]
@klyse I don't think that is currently possible.
