### ISSUE TITLE
Translate DateTimeOffset.ToUnixTime[Seconds|Milliseconds]

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#28925]
ToUnixTime* methods on DateTimeOffset can be translated in SQL Server as `DATEDIFF(second|millisecond, '1970-01-01T00:00:00.000', [Date])`. 

This can even be done today verbosely with `EF.Functions` as `EF.Functions.DateDiffSecond(DateTimeOffset.UnixEpoch, date)`. It would be nice if translation of ToUnixTimeSeconds/ToUnixTimeMilliseconds was supported natively.

**Comment by Marusyk** [comment]
Please assign it to me

**Comment by ajcvickers** [comment]
@Marusyk Feel free to submit a PR.
