### ISSUE TITLE
Migration commands fail for projects in a visual studio solution folder

### ISSUE THREAD

**Issue by tlaimer** [dotnet/efcore#2893]
### Functional impact

Migrations stop working as long as the project remains in the solution folder. The workaround of moving the project into the solution root, doing the migration and moving it back into the solution folder works, but isn't that obvious.
### Minimal repro steps
1. Create a project
2. Add nuget package for EF latest stable (6.1.3)
3. Enable migrations
4. Create a solution folder
5. Move the project into the solution folder
6. Try to add a migration
### Expected result

Migration is added
### Actual result

Command fails with the message `The EntityFramework package is not installed on project ''.`

**Comment by ErikEJ** [comment]
This is the EF7 repository, you should report EF6 issues here: https://entityframework.codeplex.com/WorkItem/Create?ProjectName=entityframework

**Comment by tlaimer** [comment]
Will do, sorry for the hassle.
