### ISSUE TITLE
The DbContext self entity tracing will affect the working of global filter on navigation properties

### ISSUE THREAD

**Issue by ma-hua** [dotnet/efcore#28936]
### Background
I am testing soft-delete by unit test. So I use in memory database to mock a DbContext. 
I have two tables, one for authors and one for blogs. A single author can include multiple blogs.

### Steps
When I add a new author with two blogs by dbContext,  save changes;
and I soft delete one of the blogs,  save change.

```C#
        [TestMethod]
        public void Test_SoftDelete()
        {
            var dbContext = MockDbContext();

            var author = new Author { Blogs = new List<Blog> { blog1, blog2 } };
            dbContext.Add(author); 
            dbContext.SaveChanges();

            // Soft Delete: SaveChanges() be rewritten
            dbContext.Remove(blog1); 
            dbContext.SaveChanges();

            // Soft deletion worked
           dbContext.Blogs.Count().ShouldBe(1); 

           // Although soft deletion works, bbut the following query blogs count is 2
           var author = dbContext.Author.Include(x => x.Blogs).First();
           author.Blogs.Count.ShouldBe(2); 

           //If i use AsNoTracking(),  the blogs count will be 1
           author = dbContext.Author.AsNoTracking().Include(x => x.Blogs).First();
           author.Blogs.Count.ShouldBe(1); 
        }


```

1. So we can see whether DbContext uses 'AsNoTracking()', which gives different results.
    **(Reference second assert and third assert).**

3. There is also a difference between querying data directly from DbSet and getting results from include
  **(Reference first assert and second assert).**

### Include provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.InMemory 6.0.3
Target framework: .NET 6.0
Operating system:
IDE: Visual Studio 2022 17.2

**Comment by ajcvickers** [comment]
@ma-hua The `DbContext` instance is still tracking the flagged entity. Query filters are applied to queries; there is no attempt to filter anything already tracked by the context. The correct thing to do here is to use a new `DbContext` instance for each unit of work--so, in this case, dispose of the first instance after calling `SaveChanges` and create a new one. `ChangeTracker.Clear()` could be used instead, but that's more of a workaround than being the correct solution. It would probably also be a good idea to check out the [documentation on testing](https://docs.microsoft.com/en-us/ef/core/testing/).
