### ISSUE TITLE
CREATE NEW PROJECT WITH SPECIFIC VERSION of FRAMEWORK .NET

### ISSUE THREAD

**Issue by Ghad1ee2r3** [dotnet/efcore#28954]
Hi 

I install .Net framework Version 4.7.2, Because I have the project built already in that version I want to run this project but not working 

Can you tell me, How can I create a new .Net framework Version 4.7.2  project with specifying the version of the framework, please?

**Comment by roji** [comment]
@Ghad1ee2r3 this repository is for Entity Framework Core, but your question doesn't seem to have anything to do with it.

Choosing the version of .NET Framework should be possible in the Visual Studio user interface when you create a new project.
