### ISSUE TITLE
All entity types sharing a CLR type must be configured as owned in 'OnModelCreating'.

### ISSUE THREAD

**Issue by intermension** [dotnet/efcore#28975]
Using Microsoft.EntityFrameworkCore 5.0.17 we get the following error:

`Failed to construct an Repository System.InvalidOperationException: The entity type 'Theme.LastChange#ChangeTracking' is configured as owned, but the entity type 'Tag.LastChange#ChangeTracking' is not. All entity types sharing a CLR type must be configured as owned in 'OnModelCreating'.`

Can anyone please explain what this new error message is supposed to mean? 
Why would entity types sharing a CLR type need to configured as owned? Are they not the OWNER? 
Surely, the CLR type being shared is the type that needs to be configured as owned? This is being explicitly done via Fluent in the map   for the owning types (example below) so why the new error message?

```
 public void Configure(EntityTypeBuilder<Tag> builder)
        {
            builder.ToTable("Tag");
            builder.HasKey(p => p.ID);
            builder.Ignore(p => p.State);

            builder.Property(p => p.ID).HasColumnName("ID");
            builder.Property(p => p.Name).HasColumnName("Name");
            builder.Property(p => p.Description).HasColumnName("Description");
            builder.Property(p => p.OwnerID).HasColumnName("OwnerID");
            builder.OwnsOne(obj => obj.LastChange,
                changeTracking =>
                {
                    changeTracking.Property(obj => obj.CreatedBy).HasColumnName("CreatedBy");
                    changeTracking.Property(obj => obj.CreatedWhen).HasColumnName("CreatedWhen");
                    changeTracking.Property(obj => obj.ModifiedBy).HasColumnName("ModifiedBy");
                    changeTracking.Property(obj => obj.ModifiedWhen).HasColumnName("ModifiedWhen");
                });
            builder.Property(p => p.SubscriptionID).HasColumnName("SubscriptionID");
}
```

**Comment by AndriySvyryd** [comment]
`Theme.LastChange` and `Tag.LastChange` have the same CLR type - `ChangeTracking`. Everywhere `ChangeTracking` is used it must be configured a owned. So you need to also call
``` C#
modelBuilder.Entity<Theme>().OwnsOne(t => t.LastChange);
```

**Comment by intermension** [comment]
Yes but I'm already doing that for all changed tracked entities and the error message specifically says it's the `Tag.LastChange` which is the issue not `Theme.LastChange`.

**Comment by AndriySvyryd** [comment]
Did you try placing a breakpoint at `builder.OwnsOne(obj => obj.LastChange` to make sure it's called?

**Comment by intermension** [comment]
Yes all the code is executed starting from OnModelCreating. Would you happen to know which branch of EFCore = 5.0.17?
