### ISSUE TITLE
Column order not scaffolded as attribute

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29007]
See this in 7.0 RC1, when using DataAnnotations

```csharp
        modelBuilder.Entity<Shipper>(entity =>
        {
            entity.Property(e => e.ShipperId).HasColumnOrder(0);
            entity.Property(e => e.CompanyName).HasColumnOrder(1);
            entity.Property(e => e.Phone).HasColumnOrder(2);
        });
```

```csharp
public partial class Shipper
{
    [Key]
    [Column("ShipperID")]
    public int ShipperId { get; set; }

    [StringLength(40)]
    public string CompanyName { get; set; } = null!;

    [StringLength(24)]
    public string? Phone { get; set; }

    [InverseProperty("ShipViaNavigation")]
    public virtual ICollection<Order> Orders { get; } = new List<Order>();
}
```

I was hoping for this:

```csharp
public partial class Shipper
{
    [Key]
    [Column("ShipperID", Order = 0)]
    public int ShipperId { get; set; }

    [StringLength(40)]
    [Column("CompanyName", Order = 1)]
    public string CompanyName { get; set; } = null!;

    [StringLength(24)]
    [Column("Phone", Order = 2)]
    public string? Phone { get; set; }

    [InverseProperty("ShipViaNavigation")]
    public virtual ICollection<Order> Orders { get; } = new List<Order>();
}
```

**Comment by roji** [comment]
@ErikEJ it's not clear to me that most users are actually interested in preserving the column order, and this would add lots of clutter for those that aren't... But now that we have templates everyone can choose as they wish?

**Comment by ErikEJ** [comment]
>> But now that we have templates everyone can choose as they wish?

Maybe - not sure how complex that would be but I can investigate.

**Comment by ErikEJ** [comment]
>> actually interested in preserving the column order

The column order is already scaffolded, just via fluent API only

**Comment by roji** [comment]
Ah OK, was not aware of that. If we do that for the fluent API, we should probably also do it for data annotations then.

**Comment by ErikEJ** [comment]
@roji Yeah, that was my point - or ignore ordering entirely in scaffolding?

**Comment by ajcvickers** [comment]
Also surprised with scaffold this. I don't think we should by default. /cc @bricelam

**Comment by bricelam** [comment]
Yeah, we're not supposed to scaffold that. We just use it to sort the CLR properties.

**Comment by ErikEJ** [comment]
This is not my code. It is the code generated by EF Core 7 scaffolding.

**Comment by bricelam** [comment]
Oh funny, you only get the `HasColumnOrder` call when `--data-annotations` is specified. It should be filtered out there.
