### ISSUE TITLE
Add Migration fails due to pre-existing migration with same name even though using separate MigrationHistory tables for multiple DbContexts in same database

### ISSUE THREAD

**Issue by bhehe** [dotnet/efcore#29015]
### **Scenario:**

We have multiple DbContexts, where each 'domain' is using its own. I.e. CustomersDbContext, OrdersDbContext, ProductsDbContext but the target database is shared between them. 

Knowing that migrations rely on the History table to track state, we have ensured that when we configure the SQL Server provider we have specified a distinct table name for each; I.e. __EFMigrationsHistory-CustomersDbContext, __EFMigrationsHistory-OrdersDbContext, __EFMigrationsHistory-ProductsDbContext

### **Issue:**

While the dotnet EF tool is recognizing that we have configured these specfic table names, the 'does migration already exist' check is not honoring or using that configured value and on first attempt to add an initial migration for the 2nd context I hit the following error:

```
Microsoft.EntityFrameworkCore.Design.OperationException: The name 'CreateInitialDatabase' is used by an existing migration.
```

I can observe in the output that it should be seeing/using the distinctly named history table:

```
Finding DbContext classes in the project...
Using DbContext factory 'CustomersDbContextDesignTimeFactory'.
Using context 'OrdersDbContext'.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
    Entity Framework Core 6.0.8 initialized 'OrdersDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.8' 
    with options: MigrationsHistoryTable=dbo.__EFMigrationsHistory-OrdersDbContext
```
Above we can see that it knows the specific table name it **_should_** be using.

### **Temporary Workaround:**

We'll use discrete names as that should be viable for us, but this doesn't seem like it should have been necessary if things were working correctly given the separate history tables for each context.

### **Environment:**
EF Core version: 6.x
Database provider: Microsoft.EntityFrameworkCore.SqlServer  (and Sqlite for testing)
Target framework: .NET 6.0

### **Suggestions:**

In the future, would it be feasible to simply add the DbContext name as part of the History table? That would seem to alleviate this issue and prevent the need for having a discrete/separate history table _per context_.  And then this 'migration name already exists' check would include the context name in its logic as well.

**Comment by bhehe** [comment]
Disregard, sorry; classic **EBKAC** - previous experimentation efforts did leave behind some artifacts where a migration of that name was already present in the 2nd project.

The **_suggestions_** section remains valid though re: the History table, it would seem this scenario could be supported out-of-the-box with far less hassle if the context name itself was included in the History table/tracking.

**Comment by roji** [comment]
@bhehe using multiple context types with the same database and requiring separate migration history tables is quite a rare scenario. Including the context name would raise all kinds of tricky questions, like what happens if the context is renamed.

**Comment by ajcvickers** [comment]
@bhehe As @roji said, this is not something we plan to implement. However, there are [docs here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table) indicating how the history table can be customized.

Note for triage: I couldn't find any issue on doing this without pubternal code.

**Comment by ajcvickers** [comment]
Created https://github.com/dotnet/efcore/issues/29066 to track customization without internals.
