### ISSUE TITLE
IMaterializationInterceptor async methods

### ISSUE THREAD

**Issue by GoNextGroup** [dotnet/efcore#29046]
Hello.

I have one simple question connected with the new feature - materialization interceptor.
So, currently, this kind of interceptors contain just only synchronous methods, but no async methods.

Will you have plans to add async version (all/part) methods in the `IMaterializationInterceptor` interface?
Also example from https://github.com/ajcvickers/EF7Interceptors doesn't contain any examples of DI usage in these interceptors. 

Let me explain simpliest case (maybe stupid, but) I try to use this kind of interceptors.

Let me have class like this:

```
public class Order
{
     public Guid Id { get; set; }
    
      public string Description { get; set; }
      public User OrderMaker { get; set; } //These both User classes really were added for information and there is no need to have any type of relations in database between User and Order tables.
      public User OrderTaker { get; set; }
}
```

I'd like to have something like this:

```
public class Order
{
     public Guid Id { get; set; }
    
      public string Description { get; set; }
      
      public Guid OrderMakerId { get; set; }
      [NotMapped]
      public User OrderMaker { get; set; } //These both User classes really were added for information and there is no need to have any 
type of relations in database between User and Order tables.

      public Guid OrderTakerId { get; set; }
      [NotMapped]
      public User OrderTaker { get; set; }
}
```

In the `MyMaterializationInterceptor` I'd like to write something like this:

```
public class MyMaterializationInterceptor : IMaterializationInterceptor
{
       private readonly ICreateScopeFactory factory;
       public ConnectionInterceptor(ICreateScopeFactory factory) => this.factory = factory;
       
       public async Task<object> InitializedInstanceAsync(MaterializationInterceptionData materializationData, object instance)
       {
              if (instance is Order order)
             {
                  var userDbContext  = factory.CreateScope().ServiceProvider.GetRequiredService<UserDbContext>(); //Because MaterializationInterceptor is a singleton object by outer design

                   var userIds = new[] { order.OrderMakerId, order.OrderTakerId };
                   var users = await userDbContext.Users.Where(e => userIds.Contains(e.Id)).ToListAsync();

                   order.OrderMaker = users.FirstOrDefault(e => e.Id == order.OrderMakerId);
                   order.OrderTaker = users.FirstOrDefault(e => e.Id == order.OrderTakerId);
             } 

             return instance;
       }
}
```

Why weren't async method be added in this interceptor? Is this connected with different EF Core internal limitation? For example, `IDbCommandInterceptor` has async methods.

EF Core version: EF Core 7.0 preview7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7.0 preview7
Operating system:
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0
Windows 2019 Server

**Comment by ajcvickers** [comment]
Materialization is not on an async code path, so there is no way to call async materialization interceptors without plumbing async through the system, which would be a major change.

**Comment by GoNextGroup** [comment]
It's a great pity.((((

**Comment by ajcvickers** [comment]
Note from triage: async here would be prohibitively difficult due to these interceptors being compiled into dynamically generated shaper code.
