### ISSUE TITLE
Add Migration is not working in Ubuntu 22.04

### ISSUE THREAD

**Issue by Iam-Luik** [dotnet/efcore#29052]
Hello guys, i'm having a problem when I try to add a migration, i got the following error that I don't understand well.

Command: dotnet ef migrations add --project src/services/NSE.Identidade.Api/NSE.Identidade.Api.csproj --startup-project src/services/NSE.Identidade.Api/NSE.Identidade.Api.csproj --context NSE.Identidade.Api.Data.ApplicationDbContext --configuration Debug Initial --output-dir Migrations Exit code: 139

I don't know if it's a common error, a missconfiguration or even a issue. If there is any guide/tutorial to configurate entity framework and .net in ubuntu 22.04 it will be trully helpless... 

.NET SDKs installed:
  6.0.400 [/snap/dotnet-sdk/177/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/snap/dotnet-sdk/177/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/snap/dotnet-sdk/177/shared/Microsoft.NETCore.App]

EF Core version: 6.0.0
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework:  .NET 6.0
Operating system: Ubuntu 22.04
IDE: Rider

**Comment by ajcvickers** [comment]
@Iam-Luik Can you post the full `--verbose` output of running the command?

**Comment by Iam-Luik** [comment]
I tried to run in vscode but I can't, I don't find the correct path to run the command

**Comment by roji** [comment]
@Iam-Luik this may be an issue in Rider rather than anything related to EF Core; it's hard to tell since the above doesn't provide any actual error or stack trace.

Can you please try running `dotnet ef migrations add` yourself on the command-line, [as described in our docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli)?

**Comment by Iam-Luik** [comment]
i find out the problem, the dotnet sdk was not installing correctly, I had to reinstall my distro to solve the problem. Now is everything up, thanks everybody
