### ISSUE TITLE
UriToStringConverter: original string not preserved 

### ISSUE THREAD

**Issue by SebastiaanPolfliet** [dotnet/efcore#29053]
The value converter for Uri does not preserve the original string. The implementation of `UriToStringConverter` uses `Uri.ToString()` in the provider mapping which returns [the unescaped canonical representation of the Uri instance](https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring?view=net-6.0). 

What is the reason the implementation of `UriToStringConverter` uses `Uri.ToString()` and not [`Uri.OriginalString`](https://docs.microsoft.com/en-us/dotnet/api/system.uri.originalstring?view=net-6.0)?

### Uri example
`new Uri("https://foo/%20bar")`

#### Uri before save
`.OriginalString`: `https://foo/%20bar`
`.ToString()`: `https://foo/ bar`

#### String value persisted in database
`https://foo/ bar`

#### Uri after fetching
`.OriginalString`: `https://foo/ bar`
`.ToString()`: `https://foo/ bar`

### Reference to the implementation: 
[UriToStringConverter](https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Storage/ValueConversion/UriToStringConverter.cs) relies on `ToString()` of [StringUriConverter](https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Storage/ValueConversion/Internal/StringUriConverter.cs). 
 
### Provider and version information

EF Core version: 6.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by ajcvickers** [comment]
We discussed this, and using the normalized form seems like the correct thing to do in many cases--it's one of the main reasons to use a `Uri` rather than just a string.

@SebastiaanPolfliet It's really easy to add your own converter that uses the `OriginalString`, if that's something you need.
