### ISSUE TITLE
Why do we need to bootstrap a functional startup project to generate an idempotent migration script?

### ISSUE THREAD

**Issue by jeremy-holovacs-sp** [dotnet/efcore#29063]
Instead of something like this:
``` ps 
migrations script --no-build --configuration $(BuildConfiguration) --idempotent --output \"$(Build.ArtifactStagingDirectory)/migrations.sql\" --project MyDataProject --startup-project MyStartupProject
```
...where we have to invoke the startup project and get all its configurations, we should be able to do this:
``` ps 
migrations script --no-build --configuration $(BuildConfiguration) --idempotent --output \"$(Build.ArtifactStagingDirectory)/migrations.sql\" --project MyDataProject --context MyDbContext
```
...that should work with no more things necessary; the script should just build. This is based off the model, not the connection and business logic, so you should be able to pull in fake dependencies, as long as the model builds correctly. So why can't we do that?

**Comment by ajcvickers** [comment]
@jeremy-holovacs-sp Historically, this was to support .NET Standard class libraries, since these need an actual runtime to be loaded. However, if you have a .NET 6 class library, and if that library has either a DbContext type with a parameterless constructor or an IDbDesignTimeCOntextFactory, then the startup project should not be needed. Please let us know if you find this not to be the case.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jeremy-holovacs-sp** [comment]
I missed the notification; I do think the `IDbDesignTimeContextFactory` is a bad pattern and shouldn't be necessary either...
