### ISSUE TITLE
Debug dnx . ef commands?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#2906]
Hi,

I'm developing a vNext project.

I was wondering if it's possible to attach a debugger to the `dnx . ef` command, so that when executing migrations, I can place a breakpoint at the `OnModelCreating` piece in my context.

I believe this feature doesn't exist, but do you think it would be a good idea? Is it easily achievable?

**Comment by bricelam** [comment]
Hmm.. [I asked xUnit.net](https://github.com/xunit/dnx.xunit/commit/5b310337f9057bab1d3f86d70edd4a2ffe295bf5) to add a `-debug` flag for similar reasons, but I'm not sure if debugging models and migrations is quite as common. You can always add the following to you code to get a debugger attached.
```C#
Debugger.Launch();
```

**Comment by bricelam** [comment]
Closing. We discussed as a team and decided that this should either be a DNX feature or left up to the users--there's nothing for the EF team to do here.
