### ISSUE TITLE
Creating Migration failed by the issue with Geometry type in entity

### ISSUE THREAD

**Issue by Bogdan-Shklanka2002** [dotnet/efcore#29067]
## Ask a question
I'm trying to add new migration in the project which migrated from .net core 2.2 to .net 6.  But I received such Exception:

> _System.ArgumentException: GenericArguments[0], 'System.Byte[]', on 'Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerGeometryTypeMapping`1[TGeometry]' violates the constraint of type 'TGeometry'._ 

Early to store spatial data is used **byte[]** but now is necessary used the type which inherited _NetTopologySuite.Geometries.**Geometry**_.
It's a problem with ContextModelSnapshot, because in it is wrote that entity field have a type **byte[]** and **SqlServerGeometryTypeMapping** method could not receive **byte[]** instead of **Geometry** as generic type. 
How can I solve it? 

EF Core version: 6.0.6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer 
Target framework: .NET 6.0
Operating system: Win 10
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@Bogdan-Shklanka2002 Can you post an example of the code in the snapshot and the mapping code that you were using for spatial types in 2.2?

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
