### ISSUE TITLE
Optional dependents and entity splitting

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#29079]
In entity splitting and owned dependents with table sharing,
The main fragment of dependent has to be table sharing with any fragment of principal.
Additional fragment of dependent can be table sharing with other fragments of principal.
So combined this it creates question for optional dependents where
we check for all non-principal shared non-pk properties to see if they contain any value to figure out if dependent exists, we use this check in property access too.
How do we figure out across all tables if dependent is sharing property with principal across all of its fragments?
If we somehow arrive at the complex condition for this question, it could mean that we don't remove additional split tables even though value is not used in final result because we would use them in property access to figure out if used value should be null or column value which reduces the value of entity splitting itself if we have to join all the table all the time.

**Comment by ajcvickers** [comment]
Note from triage: waiting for @AndriySvyryd
