### ISSUE TITLE
Any plans to update M.D.S. for EF Core 6?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29082]
Latest LTS is now 4.0 and an important hotfix was just released (4.0.2) 

https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver16

https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.2.md

**Comment by ajcvickers** [comment]
@ErikEJ I don't think we can ever update to 4.0 in a patch release since it is massively breaking.
