### ISSUE TITLE
Can include and exclude model property for EntityState

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#2908]
For example in mvc action when want edit model use

```
db.Entry(user).State = EntityState.Modified;
db.SaveChanges();
```

if use bind include/exclude or some property not in view, EF raise validation error or set null.
please add same BindAttribute in mvc to Entry method can easy assign properties that want updated.

**Comment by rowanmiller** [comment]
@mojtabakaviani if you want to specify that particular properties are modified then rather than marking the whole entity as modified you can use `db.Entry(user).Property(u => u.Name).IsModified = true` to mark specific properties as modified. EF will only include these in the update statement.
