### ISSUE TITLE
Auto migrations with GenerateScript

### ISSUE THREAD

**Issue by datnt97** [dotnet/efcore#29108]
### THE SITUATION: 
I am working on a project that has multiple Tenant that has its database.
And I have to update the database when it has new migrations for every tenant.
I also look through [issue "Automatic migrations"](https://github.com/dotnet/efcore/issues/6214#issuecomment-332980580), but I dont' really understand it @@

### MY SOLUTION: 
I found a solution [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying).
I get the pending migrations of context, and update if it contains in the pending list.
```cs 
private Task Test()
{
	using (var context = new SampleContext())
	{
		var migrationStart = nameof(F5_RemoveUnnecessaryProperty);
		var migrationEnd = nameof(F6_Refactor_Topic_V3);

		var migrator = context.GetService<IMigrator>();

		// Error with transaction
		//await migrator.MigrateAsync(migration);

		var scripts = migrator.GenerateScript(migrationStart, migrationEnd, MigrationsSqlGenerationOptions.NoTransaction);
		var lines = scripts.Split($"{Environment.NewLine}GO{Environment.NewLine}").ToList();
		lines = lines.Take(lines.Count - 1).ToList();
		
                foreach (var line in lines)
		{
			using (var trans = context.Database.BeginTransaction(System.Data.IsolationLevel.ReadUncommitted))
			{
				await context.Database.ExecuteSqlRawAsync(line);
				await trans.CommitAsync();
			}
		}
	}
}
```
### THE ERROR: 
Sometimes I encounter problems with transaction. If I use `await migrator.MigrateAsync(migration);`
![image](https://user-images.githubusercontent.com/59597401/190312041-76e1a6c2-9be1-4124-90a8-42bf1684641b.png)

### ASP.NET CORE VERSION: 
I am using `net5.0` and EntityFramework Core:  `5.0.3`.

### QUESTIONS: 
- Has any solutions better than my solution?

**Comment by datnt97** [comment]
I have many migrations. I worry about `SetCommandTimeout()` which takes a long time to migrate.

**Comment by roji** [comment]
@datnt97 whether you use migrator.Migrate() or your custom solution to generate SQL and execute it separately has no bearing on how long your migrations will take. Regardless of how exactly you execute your migrations, you need to make sure your migrations either run quickly enough, or raise the timeout.

**Comment by datnt97** [comment]
I will notice this.


@roji Thank you for your advice. I will close this issue.
