### ISSUE TITLE
Still no bulk update with  EF Core 7 RC?

### ISSUE THREAD

**Issue by niltor** [dotnet/efcore#29112]
I have read a lot of blogs about ef 7 support `bulk update`, and the  #27185  show that this feature had been completed.

But when I try to use ef 7 preview7 and RC, there is no `ExecuteDeleteAsync` method. This is so confusing！

**Comment by ErikEJ** [comment]
What have you tried?

**Comment by roji** [comment]
@niltor this [7.0 what's new](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) section may help.

**Comment by niltor** [comment]
- IDE : Visual Studio 2022 17.4 Preview2.0
- EF Core : 
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0-rc.1.22426.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.0-rc.1.22426.7" />
```
- Code: 
```csharp
await context.Users.ExecuteDeleteAsync();
```
The IDE show: There is no `ExecuteDeleteAsync`  method.

**I tried it on two different computers with the same Code.**

**UPDATE**
>  PS:
Today I just opened VS, the code works well, and the IDE show correct!😂
