### ISSUE TITLE
Convert between StringBuilder and IndentedStringBuilder

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2912]
`IndentedStringBuilder` can't derive from `StringBuilder` since it's sealed, but we could have implicit conversion operators between the two.

**Comment by divega** [comment]
Would we use the conversions or is this just a nice to have?

**Comment by bricelam** [comment]
Just nice to have.

**Comment by bricelam** [comment]
Nevermind. I just realized `IndentedStringBuilder` was "internal".
