### ISSUE TITLE
Reverse engineer Synapse Serverless SQL Pool and Dynamics 365 TDS Endpoint

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29121]
**Why**

As a EF Core developer I would like to be able to use my familiar API to query a Synapse Server SQL Pool and Dynamics 365 TDS Endpoint and get the model generated for me by the EF Core tooling, so I can do read-only queries against theses data sources. 

(This currently breaks with the EF Core tooling)

**How**

I recently enabled this in EF Core Power Tools, and can port my tweaks to SqlServerDatabasemodelFactory to the product, if this has any traction.

**More info**
[Dynamics 365 CRM TDS Endpoint](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query)  - EngineEdition = 1000

[Azure Synapse Analytics Serverless SQL pool](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/on-demand-workspace-overview) - EngineEdition = 11

**Comment by roji** [comment]
@ErikEJ what kind of errors have you encountered, and what kind of fixes? I think that if it's a few tweaks to SqlServerDatabasemodelFactory (and not like a total redo or something) then there's no reason we wouldn't take it... If you already have some changes ready, submitting them as a PR would be best so we can get a sense of things.

**Comment by ErikEJ** [comment]
Perfect  - just wanted to find out if this was relevant before I created a PR.

It is some rephrased SQL + conditional processing to be more compatible with these "non-standard" / new engine editions - no total redo.

**Comment by ajcvickers** [comment]
@ErikEJ Please create the PR for the main branch. We're closed down on EF7 work except for high impact bug fixes or other exceptions.

**Comment by ErikEJ** [comment]
Tag community contribution??
