### ISSUE TITLE
When EF7 RC is referenced from a Function App, the app throws a runtime error on startup

### ISSUE THREAD

**Issue by elninoisback** [dotnet/efcore#29123]
A minimal reproduceable repo is here: https://github.com/elninoisback/ef7rc-fnapp-issue

The following error is thrown in the console when the function app startsup. It goes away when you remove the ef core dependancy,

`The 'Function1' function is in error: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

The following is my .csproj file of the function app.
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <RootNamespace>ef7rc_fnapp_issue</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0-rc.1.22426.7" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

EF Core version: 7.0.0-rc.1.22426.7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system: Windows 10 Pro
IDE: Visual Studio Enterprise 2022

**Comment by ajcvickers** [comment]
@JeremyLikness Azure Functions contact?

**Comment by AraHaan** [comment]
Currently I would recommend for you to test this with .NET 7's TFM and see if you can still reproduce it with that as well.

**Comment by elninoisback** [comment]
> Currently I would recommend for you to test this with .NET 7's TFM and see if you can still reproduce it with that as well.

I did try with .NET 7 using VS preview build but the result is the same.

**Comment by elninoisback** [comment]
I've spent too many hours trying to make this work, but to no avail.

The only workaround which seems to work at the moment is changing the function runtime to "dotnet-isolated" and change everything else in your code to support it.

**Comment by AraHaan** [comment]
hmm looks to me that the aspnetcore shared framework is referenced right? if so ensure that ```xml
    
    <GenerateDependencyFile>true</GenerateDependencyFile>
```

in the csproj of the function application.

**Comment by elninoisback** [comment]
> hmm looks to me that the aspnetcore shared framework is referenced right? if so ensure that:
> 
> ```
>     
>     <GenerateDependencyFile>true</GenerateDependencyFile>
> ```
> 
> in the csproj of the function application.

I do not have any aspnetcore dependency. I've used the standard Azure Function App Template to create the project. The following is my .csproj file.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <RootNamespace>ef7rc_fnapp_issue</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0-rc.1.22426.7" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
````

And I tried adding `<GenerateDependencyFile>true</GenerateDependencyFile>` inside `<PropertGroup>` as you suggested, but it didn't make any difference.

**Comment by AraHaan** [comment]
ironically I had the same thing happen with scaffolding today as well, and that fixed it (along with an ``FrameworkReference`` to the aspnetcore shared framework.

**Comment by ajcvickers** [comment]
@Ved2806 Can you shed any light on this?

**Comment by ajcvickers** [comment]
Moved to https://github.com/Azure/Azure-Functions/issues/2281
