### ISSUE TITLE
How to use EF Core in applications targeting .NET Framework 4.8 after EF Core 3.1 end of support?

### ISSUE THREAD

**Issue by bairog** [dotnet/efcore#29136]
In **December 2022** EF Core 3.1 will [reach EOL](https://learn.microsoft.com/en-us/ef/core/what-is-new/). It is the only EF Core version available for applications targeting .NET Framework 4.8.
.NET Framework 4.8 is still supported (since its lifecycle is tied to Windows) and ironically EF 6.4.4 is still supported (since there are currently [no plans to end support](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/support#entity-framework-60-61-62-63-and-64)). According [the docs](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/support#entity-framework-60-61-62-63-and-64):
> It is strongly encouraged that new applications and existing applications that are in active development use EF Core.

@ajcvickers @bricelam @ErikEJ How EF Core is supposed to be used (in a supported manner of course) in applications targeting .NET Framework 4.8 after EF Core 3.1 end of support (December 3, 2022)?

**UPDATE**. I know that EF Core 2.1 [will be supported when used with ASP.NET Core 2.1 on .NET Framework](https://learn.microsoft.com/en-us/ef/core/what-is-new/). But my question is about other project types: class libraries, WinForms and WPF applications targeting .NET Framework 4.8

**Comment by ErikEJ** [comment]
As far as I can tell there will be no supported way to do this after December  13  2022 

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core 

It is a little unclear to me, but it looks like you can use EF Core 2.1 in a supported manner.

**Comment by bairog** [comment]
> It is a little unclear to me, but it looks like you can use EF Core 2.1 in a supported manner.

According to [docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/) and [blog post](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/) EF Core 2.1 has reached EOL on August 21, 2021.  EF Core 2.1 will be supported **only** when used with **ASP.NET Core 2.1** on .NET Framework.
But I'm interested in other project types: class libraries, WinForms and WPF applications targeting .NET Framework 4.8.
So I think I should wait for clarifications from @ajcvickers and @bricelam.

**Comment by ajcvickers** [comment]
@bairog I'm aiming for an answer this week.

**Comment by ajcvickers** [comment]
We have followed up on this with management to clarify the situation. After much discussion, there will be no change in support policy here. That is, [EF Core 3.1 will go out-of-support on December 3](https://learn.microsoft.com/en-us/ef/core/what-is-new/). There will be no extended support for .NET Framework applications.

Options for those using EF Core 3.1 are:

- Move to EF Core 6.0, or later, on .NET 6, or later.
- Port to [legacy EF6](https://github.com/dotnet/ef6), where there are currently no plans to end support on .NET Framework.
- ASP.NET Core applications using EF Core on .NET Framework can downgrade to EF Core 2.1, which is still supported for ASP.NET Core applications.
- Continue to use EF Core 3.1 without support. Note that EF Core 3.1 will not get any future security fixes.

**Comment by bairog** [comment]
Sad but predictable..
**Move to EF Core 6.0, or later, on .NET 6, or later** is not an option for those companies that are still using Visual Studio 2019.
So the most common scenario for such companies would be to continue using EF Core 3.1 without support :(
