### ISSUE TITLE
Synapse database first approach - FUNCTION OBJECT_SCHEMA_NAME not supported

### ISSUE THREAD

**Issue by mrzenca** [dotnet/efcore#29137]
Hi, 

When will a version be available that allows model generation based on Azure Synapse (SQL connection)?

EF Version 7.0.0-rc.1.22426.7
dotnet ef dbcontext scaffold "..." Microsoft.EntityFrameworkCore.SqlServer -o Model
Error message: FUNCTION OBJECT_SCHEMA_NAME not supported

Thanks,
Michał

**Comment by ErikEJ** [comment]
You can do that today with EF Core Power Tools, and I have a PR in (for EF Core 8)

**Comment by ajcvickers** [comment]
Duplicate of #29121
