### ISSUE TITLE
Index incorrectly named in migration

### ISSUE THREAD

**Issue by glen-84** [dotnet/efcore#29151]
### Include your code

Configuration:

```cs
builder
    .HasIndex(u => u.Username, "UNIQ_1483A5E9F85E0677")
    .IsUnique();
```

Initial migration:

```cs
migrationBuilder.CreateIndex(
    name: "ix_users_username",
    table: "users",
    column: "username",
    unique: true);
```

Shouldn't the index name in the migration also be `UNIQ_1483A5E9F85E0677`?

If this is unexpected behaviour I can create a reproduction repository, if it helps.

### Include stack traces

n/a

### Include verbose output

n/a

### Include provider and version information

EF Core version: 6.0.9
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET 6.0
Operating system: Windows 11 Home
IDE: VS Code

**Comment by ajcvickers** [comment]
This is likely an issue with the Pomelo MySQL provider; you'll probably want to file an issue at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql
/cc @lauxjpn
