### ISSUE TITLE
Query filter in including relation

### ISSUE THREAD

**Issue by orlicekm** [dotnet/efcore#29175]
I tried to implement soft delete using query filter, but my query filters aren't applied in include relations. Multiple articles and Microsoft docs say that it should be.
[https://learn.microsoft.com/en-us/ef/core/querying/filters](https://learn.microsoft.com/en-us/ef/core/querying/filters)
[https://www.thereformedprogrammer.net/ef-core-in-depth-soft-deleting-data-with-global-query-filters](https://www.thereformedprogrammer.net/ef-core-in-depth-soft-deleting-data-with-global-query-filters)
[https://www.meziantou.net/entity-framework-core-soft-delete-using-query-filters.htm](https://www.meziantou.net/entity-framework-core-soft-delete-using-query-filters.htm
)
### Code sample
Here is simple test that fails:

```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;
using Xunit.Abstractions;

namespace TestSoftDelete.Tests;

public class SoftDeleteTest
{
    private readonly SqliteConnection _connection;
    private readonly DbContextOptions _options;
    private readonly ITestOutputHelper _testOutputHelper;

    public SoftDeleteTest(ITestOutputHelper testOutputHelper)
    {
        _testOutputHelper = testOutputHelper;
        _connection = new SqliteConnection("datasource=:memory:");
        _connection.Open();

        _options = new DbContextOptionsBuilder()
            .UseSqlite(_connection)
            .Options;

        using var context = new BloggingContext(_options);
        context.Database.EnsureCreated();
    }

    [Fact]
    public void Test()
    {
        using var dbContext = new BloggingContext(_options);

        var post = new Post();
        var blog = new Blog
        {
            Posts = new List<Post>
            {
                post
            }
        };

        dbContext.Blogs.Add(blog);
        dbContext.SaveChanges();

        _testOutputHelper.WriteLine(dbContext.Blogs.Include(_ => _.Posts).ToQueryString());

        Assert.True(dbContext.Posts.Any()); //this is ok
        Assert.True(dbContext.Blogs.Include(_ => _.Posts).First().Posts.Any()); //this is ok

        post.IsDeleted = true;
        dbContext.Posts.Update(post);
        dbContext.SaveChanges();
        
        Assert.False(dbContext.Posts.Any()); //this is ok
        Assert.False(dbContext.Blogs.Include(_ => _.Posts).First().Posts.Any()); //this fails
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public bool IsDeleted { get; set; }
    public List<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public bool IsDeleted { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}

public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().HasQueryFilter(p => !p.IsDeleted);
        modelBuilder.Entity<Post>().HasQueryFilter(p => !p.IsDeleted);
    }
}
```

However when I run the SQL query from example manually, it works fine. Query:

```SQL
SELECT "b"."BlogId", "b"."IsDeleted", "t"."PostId", "t"."BlogId", "t"."IsDeleted"
FROM "Blogs" AS "b"
LEFT JOIN (
    SELECT "p"."PostId", "p"."BlogId", "p"."IsDeleted"
    FROM "Posts" AS "p"
    WHERE NOT ("p"."IsDeleted")
) AS "t" ON "b"."BlogId" = "t"."BlogId"
WHERE NOT ("b"."IsDeleted")
ORDER BY "b"."BlogId"
```

### Provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.Sqlite (also tried in-memory, mysql)
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by smitpatel** [comment]
Reusing the same context is the issue.

**Comment by ajcvickers** [comment]
@orlicekm After `SaveChanges` is called, the context is still tracking the entities that were saved to the database. This means that they are fixed up to the result of a tracking query regardless of whether the query returns those entities or not. In general, a new DbContext instance should be used for each unit-of-work. The [DbContext](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/) and [testing](https://learn.microsoft.com/en-us/ef/core/testing/) docs have more info.
