### ISSUE TITLE
.HasNoKey() and migrations creating tables

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#29189]
I am attempting to use EF Core to execute a stored procedure in sql server, and return me a list of entities. The entity type is essentially read only. (i.e I don't want it to be tracked and don't want to create, update, or delete these).
I have created the entity type with properties to match the stored procedure result set, and addedthis entity type to my dbcontext as a typical DbSet, but with `HasNoKey` but when I add a migration, the migration still attempts to create a table for this entity. I can't do what this commenter suggests and map it to a view because this entity isn't backed by a view, its a stored procedure providing the data. Is this behaviour expected and if so what is the solution?

> for future readers, if adding .HasNoKey() didn't prevent the CodeFirst migration from creating a table for that view, try adding the following:
`modelBuilder.Entity<User>().ToView("Users").HasNoKey()`

> as in my situation the migration kept creating a table for the view and using ToView fixed it

_Originally posted by @MuhAssar in https://github.com/dotnet/efcore/issues/15656#issuecomment-536802455_

**Comment by ajcvickers** [comment]
@dazinator Have you considered `ToSqlQuery`?

> can't do what this commenter suggests and map it to a view because this entity isn't backed by a view

Mapping to a view should also work. In what way does this fail for you?

**Comment by dazinator** [comment]
@ajcvickers 
ToSqlQuery didn't seem appropriate as I need to supply paramater values when selecting the data. E.g I want to load these records based on parameters the user is selecting in the UI. I haven't mapped using ToSqlQuery before but I did look at it and my impression was its for mapping a dbset to a singular sql statement to supply the data and so I wouldn't be able to vary sql params per request? Or is that not the case?

ToView() made no sense for me to use on this occasion either, because the data I am querying does not reside in a SQL View and when I did attempt to use a View tosupply the data the perf was abysmal... the issue is i need a vary specific range of data based on the input parameters supplied from the user.. which vary per request. Creating a view, the view must include all the data, then I must query the view for the specific subset I need based on the input params from the user - but at that point the query of the view is no longer leveraging the indexes in the underlying tables as opposed to querying the tables directly. So i need to query the tables directly, with a query that can use parameter values per request. A sproc is a convenience for that but if there is another way to fo this bia EF im all ears.

P.s at this point I'm considering using Dapper to execute the sproc and get a list of dto's back, but I'm just surprised that I'd have to bypass EF for this  and would prefer not to if possible, for consistency within my data layer.

**Comment by stevendarby** [comment]
@dazinator I think this feature might be what you're after: https://github.com/dotnet/efcore/issues/10753. It's suggested in the thread that something like Dapper is an alternative for now - as you have also considered.

**Comment by dazinator** [comment]
>  If you don't want a table to be created for the entity type when using Migrations, 

@ajcvickers that api makes no sense to me either, as its only available when mapping to a table e.g:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<IdentityUser>()
        .ToTable("AspNetUsers", t => t.ExcludeFromMigrations());
}
```
Telling EF that this entity maps to table feels wrong to me when there isn't one and feels like if EF has a wrong conceptual model it might get me into trouble in other areas that leverage this conceptual model.

I'll look into FromSql, - I beleive I tried that but even with that it still showed up as a table in my Migration.

**Comment by dazinator** [comment]
@ajcvickers with respect to FromSql() the docs show loading blogs from a sproc like so:

```
var blogs = context.Blogs
    .FromSql($"EXECUTE dbo.GetMostPopularBlogsForUser {user}")
    .ToList();
```

However in this case `Blog` is an entity that is also mapped to a table and thus included in migrations and can also be queried as normal.

What it doesn't cover is, what if Blog was a keyless entity, loaded by a sproc instead. In that case there is no View or Table, so telling EF to map it to View or to a Table (to leverage ExcludeFromMigratons option) seems wrong. 

Ideally I'd just tell Ef it .HasNoKey() and this would prevent  EF from generating a migration to create a table for it but this didn't work, which was surprising. 

However I just discovered this behaviour: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#why-7 so perhaps EF has a default table mapping for it in absence of calling ToView or ToTable, I'll try calling ToTable(null) and see what effect that has on migrations..

**Comment by dazinator** [comment]
Just an update, my suspicion worked i.e calling `ToTable(null)` like so:

```
   builder.HasNoKey();
            builder.ToTable((string?)null);

```

caused EF to clear its table mapping that it was assuming by default. This was confirmed when I generated another migration:

```
 public partial class TestMigration  : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Test",
                schema: "FOO");
        }

```

**Comment by ajcvickers** [comment]
Discussed with team: Using `ToTable(null)` is the correct way to remove the by-convention table mapping such that a type in the model is not mapped to any database construct.
