### ISSUE TITLE
Generate SQL migration script programmatically

### ISSUE THREAD

**Issue by icrocket** [dotnet/efcore#29193]
Hi, is there any way to generate a migration SQL script at runtime? 

In our project, some models are generated at runtime and compiled with roslyn, these types are injected into the DBContext but we need to create the related SQL tables (at the moment, we use a small SQL Migrator developed by us with all the limitations of the case)

Therefore, we were wondering if there was a way to compare the current state of the migrations (at design time) with that at runtime and ask efcore to produce a sql script with the differences, to be run on the db.

Example: 

1) I compile a runtime type consisting of: 

```
[Key]
public int Id {get;set;}
public string Title {get; set;}
public string Description {get;set;}
```

Current migrations (scaffolded) do not contain such type, so I would like to generate the related create table.

2) I fill in the same type at runtime, adding a field:

```
[Key]
public int Id {get;set;}
public string Title {get; set;}
public string Description {get;set;}
**public string AddedField {get;set;}**
```

I need the relative ALTER TABLE.

Thanks in advance to everyone.

**Comment by roji** [comment]
Assuming you have the two EF models, you can generate the migration step from the source to the target via the following code:

```c#
await using var context = new BlogContext();

var sourceModel = context.GetService<IDesignTimeModel>().Model;
var targetModel = sourceModel;

var services = new ServiceCollection()
    .AddEntityFrameworkDesignTimeServices()
    .AddDbContextDesignTimeServices(context);

// We want to simplify the following part, see https://github.com/dotnet/efcore/issues/29068
var provider = context.GetService<IDatabaseProvider>().Name;
var providerAssembly = Assembly.Load(new AssemblyName(provider));
var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
var designTimeServicesType = providerAssembly.GetType(providerServicesAttribute.TypeName, throwOnError: true);
((IDesignTimeServices)Activator.CreateInstance(designTimeServicesType)!).ConfigureDesignTimeServices(services);

var serviceProvider = services.BuildServiceProvider();

var modelDiffer = context.GetService<IMigrationsModelDiffer>();

var migrationsCommandExecutor = serviceProvider.GetRequiredService<IMigrationCommandExecutor>();
var migrationsSqlGenerator = serviceProvider.GetRequiredService<IMigrationsSqlGenerator>();
var connection = serviceProvider.GetRequiredService<IRelationalConnection>();

var operations = modelDiffer.GetDifferences(sourceModel.GetRelationalModel(), targetModel.GetRelationalModel());
await migrationsCommandExecutor.ExecuteNonQueryAsync(
    migrationsSqlGenerator.Generate(operations, sourceModel),
    connection);
```

**Comment by icrocket** [comment]
Thanks a lot @roji!

I have a question: do you use the IDesignTimeModel interface present in EFCore 6, I am currently using EFCore 3.1. Do you have any advice on this?

**Comment by ErikEJ** [comment]
I have code to generate an idempotent script for 3.1 here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/efpt30.core/EFCoreMigrationsBuilder.cs#L176

**Comment by ErikEJ** [comment]
Assume you are aware that 3.1 goes out of support in December this year?

**Comment by icrocket** [comment]
> Assume you are aware that 3.1 goes out of support in December this year?

Hi Erik, of course we are aware of that. We are working to upgrade our frameworks to 6.0.

Thanks a lot for your help!

Your code generates an idempotent SQL script for database creation / migration. On the other hand, I need a migration sql script related to dynamic types compiled via roslyn's emit, therefore, I practically need the sql script deriving from AddMigration. @Roji's solution seems appropriate since it compares two models and generates the differences by applying the changes through an ExecuteNonQuery.

**Comment by bricelam** [comment]
Yep. We need them for dbContext.Database.EnsureCreated()

**Comment by roji** [comment]
Of course, makes sense...!
