### ISSUE TITLE
DbUpdateException Entries contain all items from AddRange when > 3

### ISSUE THREAD

**Issue by mikeleigh1010** [dotnet/efcore#29190]
DbUpdateException Entries property inconsistent with returned values (and includes items which are not involved with exception).

I'm seeming to observe that 3 items (one duplicate and two happy day) can fail and entries will return only the item failed but > 3 in an addrange seems to be where the exception entries includes all items attempted.

```C#
    [Index(nameof(Name), IsUnique = true)]
    public class Cat
    {
        public int Id { get; init; }
        public string Name { get; init; } = string.Empty;
        public int Age { get; init; }
    }
    
    public class AppDbContext : DbContext
    {
        public DbSet<Cat> Cats { get; set; }

        public AppDbContext(DbContextOptions<PspDbContext> options) : base(options)
        {
        }
    }

    public class Processor
    {

        private IDbContextFactory<AppDbContext> _contextFactory;
        public Processor(IDbContextFactory<AppDbContext> contextFactory)
        {
            _contextFactory = contextFactory;
        }

        public async Task ProcessCats()
        {
            await using var context = await _contextFactory.CreateDbContextAsync();
            var cat = new Cat
            {
                Name = "garfield",
                Age = 10
            };

            context.Cats.Add(cat);
            await context.SaveChangesAsync();
            
            try
            {
                context.Cats.AddRange(new List<Cat>
                {
                    cat,
                    new()
                    {
                        Name = "topcat",
                        Age = 3
                    },
                    new()
                    {
                        Name = "felix",
                        Age = 2
                    }
                });
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException dbEx)
            {
                var entries = dbEx.Entries;
                // entries collection will only contain duplicate cat of "garfield"
            }
            
            try
            {
                context.Cats.AddRange(new List<Cat>
                {
                    cat,
                    new()
                    {
                        Name = "topcat",
                        Age = 3
                    },
                    new()
                    {
                        Name = "felix",
                        Age = 2
                    },
                    new()
                    {
                        Name = "lucky",
                        Age = 55
                    }
                });
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException dbEx)
            {
                var entries = dbEx.Entries;
                // entries collection will contain all cats attempted to be inserted
            }
        }
    }
```

_Originally posted by @mikeleigh1010 in https://github.com/dotnet/efcore/issues/26530#issuecomment-1256289498_
      
To give context, we are looking to capture offending items (duplicate cats of the same name) and disregard so we can continue to insert.

**Comment by ajcvickers** [comment]
@mikeleigh1010 The exception will always contain all entities included in the batch. In EF Core 6.0 on SQL Server, updates aren't batched until there are more than 3 entities to save, which explains the differing behavior you are seeing. If you always want to know whether an entity was saved or not, then you can set the max batch size to 1 so that EF will send an update for and detect a failure for each entity individually.

For example:

```C#
.UseSqlServer(Your.ConnectionString, b => b.MaxBatchSize(1))
```

**Comment by mikeleigh1010** [comment]
Thanks @ajcvickers for the reply, ah yes I had missed being able to set this when configuring EF.

**Comment by nettashamir-allocate** [comment]
I am seeing the same problem having upgraded from efcore 6.0 to 7.0. But in my case, if MaxBatchSize is left as the default, I get only one entity in my exception but not the one that is causing the error. However, if I set the MaxBatchSize to 1, I do see the correct entity in the exception. My concern is that the batch size impacts performance and I would expect a higher batch size to perform better so am reluctant to leave it at 1.

**Comment by philvmx1** [comment]
> @mikeleigh1010 The exception will always contain all entities included in the batch.

This is not true, it only contains all when the first one fails. It contains only one when a subsequent record fails.

DbCommand.ExecuteReader creates the DbDataReader AND reads the first row. If there is an error in the first row, ExecuteReader throws the exception. I think the bug here is in EF Core - it doesn't handle exceptions the same within Execute and Consume.


Execute catch https://github.com/dotnet/efcore/blob/baae39267197866446da1e9533487d18d7bcd317/src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs#L358
```
        catch (Exception ex) when (ex is not DbUpdateException and not OperationCanceledException)
        {
            throw new DbUpdateException(
                RelationalStrings.UpdateStoreException,
                ex,
                ModificationCommands.SelectMany(c => c.Entries).ToList());
        }
```

Consume catch https://github.com/dotnet/efcore/blob/42e6cfbd0c5b431a89b1923e7b73296705cf7ddf/src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs#L139
```
        catch (Exception ex) when (ex is not DbUpdateException and not OperationCanceledException)
        {
            throw new DbUpdateException(
                RelationalStrings.UpdateStoreException,
                ex,
                ModificationCommands[commandIndex < ModificationCommands.Count ? commandIndex : ModificationCommands.Count - 1].Entries);
        }
```

**Comment by philvmx1** [comment]
> I am seeing the same problem having upgraded from efcore 6.0 to 7.0. But in my case, if MaxBatchSize is left as the default, I get only one entity in my exception but not the one that is causing the error. However, if I set the MaxBatchSize to 1, I do see the correct entity in the exception. My concern is that the batch size impacts performance and I would expect a higher batch size to perform better so am reluctant to leave it at 1.

You shouldn't have to set it to 1.

The way we've handled it is:
```
catch(DbUpdateExpection ex)
{
   // assume the first one is the failed one whether there are one (i > 0 fails) or more than one (i = 0 fails).
   var entity = ex.Entries.FirstOrDefault();
   if (entitry == null) return;
   
   // handle failed entity... (set as unmodified and try the batch again?)
}
```
