### ISSUE TITLE
Migrations generates unnecessary AlterColumn operation for SQLite

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2920]
Creating a new migration for a SQLite context will produce unnecessary AlterColumn operations even though the code definition has not changed.

**Repro**
1. Clone the code from https://github.com/aspnet/EntityFramework.Docs/tree/master/docs/getting-started/x-plat/sample
2. Using dnx 1.0.0-beta6, run `dnu restore`
3. `dnx . ef migration add ShouldBeBlankMigration`

**Expected**
Should generate an empty migration as nothing has changed

**Actual**
It produces a migration with alter column operations

``` c#
...
 public override void Up(MigrationBuilder migration)
        {
            migration.AlterColumn(
                name: "PostId",
                table: "Post",
                type: "INTEGER",
                nullable: false)
                .Annotation("Sqlite:Autoincrement", true);
            migration.AlterColumn(
                name: "BlogId",
                table: "Blog",
                type: "INTEGER",
                nullable: false)
                .Annotation("Sqlite:Autoincrement", true);
        }
...
```

**Comment by bricelam** [comment]
Doh, I should have thought of this case while doing #2859! I bet it's comparing attribute value references.

**Comment by bricelam** [comment]
No wait, there's [already code for that](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L869). It must be something else...

**Comment by bricelam** [comment]
Ah, @ajcvickers did it in ea658e95e47aebf2efd0889888e536bcc811458a. It will be fixed in beta8.

**Comment by natemcmaster** [comment]
Ah yup. Just tested on newer bits.
