### ISSUE TITLE
EF7 Json column: constructor with optional enum-parameter throws ArgumentException

### ISSUE THREAD

**Issue by alienwareone** [dotnet/efcore#29214]
I've attached a minimal repo that produces the exception.

https://github.com/alienwareone/EfCoreContructorBinding

**Comment by maumar** [comment]
Problem is in `CreateExtractJsonPropertyExpression` method and how we generate shaper code for nullable properties with converters defined on entities mapped to json.

**Comment by maumar** [comment]
fixed in d4c22b2d3ab7a803b41a554c8f357ebfec4c2f3b
