### ISSUE TITLE
ef log some of queries in level of Information

### ISSUE THREAD

**Issue by vamcan** [dotnet/efcore#29211]
hi,
After upgrading from EF3.1 to EF6, some database queries are logged at the information level! while they should all be logged at the debug level.

![image](https://user-images.githubusercontent.com/4617755/192494383-5802792e-d150-411c-946d-5858dd1b5808.png)

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 )

**Comment by ajcvickers** [comment]
@vamcan These queries have always been logged at the info level. ASP.NET Core used to suppress this, but that has been fixed. See https://github.com/dotnet/aspnetcore/issues/32977
