### ISSUE TITLE
Json: error when trying to materialize json entity with nullable property that is missing in the json string - should materialize the property as null instead

### ISSUE THREAD

**Issue by vipwan** [dotnet/efcore#29219]
## File a bug

* 当查询一组数据如果改类型包含一个JSON列,当该JSON列的特定属性不存在时 查询结果绑定到实体会报错 !

![image](https://user-images.githubusercontent.com/13956765/192665843-4ec80d7f-3fde-43a5-a6af-6bc38fa3271d.png)

### Include your code

```C#
    public class Author
    {
        public string? UserName { get; set; }

        public string? Email { get; set; }

        public string? Address { get; set; }

    }
```

OnModelCreating :

```C#
    modelBuilder.Entity<Blog>()
        .OwnsMany(b => b.Versions, builder =>
        {
            builder.ToJson("Versions");
        })
        .OwnsMany(b => b.Comments, builder =>
        {
            builder.ToJson();
        })
        .OwnsOne(b => b.Author, bulider =>
        {
            bulider.ToJson();
        });
```

```C#

var item = await _dbContext.Blogs.FirstOrDefaultAsync(x => x.Id == 1);   //Error! 

var item2 = await _dbContext.Blogs.FirstOrDefaultAsync(x => x.Id == 2);   //Success ! 

```

### Include stack traces

Id=1 的这行数据是历史数据 插入时 JSON对象并不包含 `Address` 字段, 所以当更新实体对象后 (Author对象新增 Address 字段 ),查询这条记录抛出如下错误: 

```
  System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
     at lambda_method697(Closure, QueryContext, Object[], JsonElement)
     at lambda_method696(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
     at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
     at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
     at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

我认为`Address` 属性没有序列化到JSON和` {Address:null ...}` 应该是等价的 而不应该抛出异常! 

### Include provider and version information

EF Core version:  7.0.0-rc.1.22426.7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)

**Comment by vipwan** [comment]
#29199  The exceptions are similar, but the trigger points are different

**Comment by maumar** [comment]
When querying a set of data, if the type contains a JSON column, when the specific attribute of the JSON column does not exist, the query result is bound to the entity and an error will be reported

(,,,)

The row of data with Id=1 is historical data. The JSON object does not contain the Address field when it is inserted, so when the entity object is updated (the Address field is added to the Author object), the following error is thrown when querying this record:

(...)

I think the Address property is not serialized to JSON and {Address:null ...} should be equivalent and should not throw an exception!

**Comment by alienwareone** [comment]
> I think the Address property is not serialized to JSON and {Address:null ...} should be equivalent and should not throw an exception!

👍

That's what I would expect when migrating from a [Value Conversion based json column](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#composite-value-objects).

**Comment by vipwan** [comment]
> > I think the Address property is not serialized to JSON and {Address:null ...} should be equivalent and should not throw an exception!
> 
> 👍
> 
> That's what I would expect when migrating from a [Value Conversion based json column](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#composite-value-objects).


It is enough to use `Conversion `to access the serialized JSON string, but EF7 supports JSON operations at the database level, such as retrieving the `Address `field through Linq->SQL, and even using SQL's built-in JSON function. 

In addition used `Conversion `that `bulider. ToJson();` Isn't that redundant...

**Comment by maumar** [comment]
fixed in d4c22b2d3ab7a803b41a554c8f357ebfec4c2f3b

**Comment by imranmomin** [comment]
@maumar Thanks for fixing the above issue. Unfortunately,  I'm facing a similar issue when an object is missing from the JSON document. Lets say the Address was not a string and is an actual class representing different fields of an address. 

```csharp
public class Contact
{
    public int Id{ get; set; }
    public ContactDetails? Contact { get; set; }
}

public class ContactDetails
{
    public string? Email { get; set; }
    public string? Phone { get; set; }
    public Address? Address { get; set; }
}

public class Address
{
    public string? Street { get; set; }
    public string? City { get; set; }
    public string? PostCode { get; set; }
    public string? State { get; set; }
    public string? Country { get; set; }
}
```

Configuration
```csharp
public class ContactConfigurations : IEntityTypeConfiguration<Contact>
{

    public void Configure(EntityTypeBuilder<Contact> builder)
    {
        builder.ToTable("tbl_contacts", "member");
        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id)
            .HasColumnName("id")
            .IsRequired();
           
        builder.OwnsOne(x => x.Contact, b =>
        {
            b.ToJson("contact_details");
            b.OwnsOne(x => x.Address);
        });
    }
}
```

Data
| id | contact_details                                                         |
|----|-------------------------------------------------------------------------|
| 1  | { "Email": "me@example.com", "Phone": "123-456-5555" }                  |
| 2  | { "Address": null, "Email": "me@example.com", "Phone": "123-456-5555" } |
| 3  | { "Address": {}, "Email": "me@example.com", "Phone": "123-456-5555" } |
| 4  | { "Address": { "Country": "Canada" }, "Email": "me@example.com", "Phone": "123-456-5555" } |

```csharp
var contact1 = await _dbContext.Contacts.SingleOrDefaultAsync(x => x.id == 1);  // error with the below exception
var contact2 = await _dbContext.Contacts.SingleOrDefaultAsync(x => x.id == 2);  // success
var contact3 = await _dbContext.Contacts.SingleOrDefaultAsync(x => x.id == 3);  // success
var contact4 = await _dbContext.Contacts.SingleOrDefaultAsync(x => x.id == 3);  // success
```

Exception
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at lambda_method40(Closure, QueryContext, Object[], JsonElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.IncludeJsonEntityReference[TIncludingEntity,TIncludedEntity](QueryContext queryContext, Nullable`1 jsonElement, Object[] keyPropertyValue
s, TIncludingEntity entity, Func`4 innerShaper, Action`2 fixup)
   at lambda_method39(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

**Comment by rvplauborg** [comment]
@imranmomin Have you found out anything regarding that or created a new separate issue given this one is closed? We just stumbled into that unexpected behavior as well.

**Comment by imranmomin** [comment]
@rvplauborg I have not created any separate issue for it. Thanks for doing it.
