### ISSUE TITLE
Should AsNoTracking support IQueryable of a nullable type?

### ISSUE THREAD

**Issue by glen-84** [dotnet/efcore#29221]
### Include your code

```C#
public IQueryable<Article?> GetArticle(int id, [Service] ArticleService articleService)
{
    return articleService.GetArticle(id).AsNoTracking();
}
```

> The type 'Application.Modules.Editorial.Entities.Article?' cannot be used as type parameter 'TEntity' in the generic type or method 'EntityFrameworkQueryableExtensions.AsNoTracking<TEntity>(IQueryable<TEntity>)'. Nullability of type argument 'Application.Modules.Editorial.Entities.Article?' doesn't match 'class' constraint. [Application]

Is there any reason not to allow `AsNoTracking` when the type is nullable?

### Include stack traces

n/a

### Include verbose output

n/a

### Include provider and version information

EF Core version: 6.0.9
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET 6.0
Operating system: Windows 11 Home
IDE: VS Code

**Comment by ajcvickers** [comment]
@glen-84 Queries for anything that isn't an entity type are always no-tracking.

**Comment by glen-84** [comment]
`Article` _is_ an entity type.

Having said that, I think my method _should_ actually return `IQueryable<Article>` (non-nullable), since it'll return a list of one article or an empty list, and not a list with a null article.

For that reason, I'll close this, as there may not be any valid use cases for `AsNoTracking` on an `IQueryable` of a nullable type.

Thank you.
