### ISSUE TITLE
EF Core 7 RC produces different translation from EF Core 6 (VB/sqlite)

### ISSUE THREAD

**Issue by ericcan** [dotnet/efcore#29222]
I have the following LINQ query in my VB code:

            Dim testq = From cf In dbContxt.Cashflows
                        Where cf.Date >= #4/1/2022# And cf.Deposit IsNot Nothing
                        Select cf.Date

It produced the following SQL in EF Core 6.0 (using testq.ToQueryString()):

SELECT "c"."Date" 
FROM "Cashflows" AS "c"
WHERE ("c"."Date" >= '2022-04-01 00:00:00') & ("c"."Deposit" IS NOT NULL)

In EF Core 7.0, I am getting a different result, which changes the order of operations of the query:

SELECT "c"."Date" 
FROM "Cashflows" AS "c"
WHERE ("c"."Date" >= '2022-04-01 00:00:00') & "c"."Deposit" IS NOT NULL

Note that if I change the query to:

            Dim testq = From cf In dbContxt.Cashflows
                        Where cf.Date >= #4/1/2022# AndAlso cf.Deposit IsNot Nothing
                        Select cf.Date

I get:

SELECT "c"."Date" 
FROM "Cashflows" AS "c"
WHERE "c"."Date" >= '2022-04-01 00:00:00' AND "c"."Deposit" IS NOT NULL

This works around the issue, giving me the same results I got in EF Core 6.0

Thanks!

EF Core version: 7.0 RC.1.22426.7
Database provider: Microsoft.EntityFrameworkCore.Sqlite.Core
Target framework:  .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.3.4

**Comment by roji** [comment]
This is #26652. We fixed this for 6.0.2 in #26653, but it seems like the merge into main didn't carry over the fix (bcdeef9c85bcbd9efcbd73b9b945fb1325c52020). I vaguely remember us treating that as a temporary fix (because it added lots of unneeded parentheses), with the 7.0 plan being to do some better/more comprehensive (which became #26652).

We should fix this for 7.0.

**Comment by ericcan** [comment]
I wanted to confirm that the latest daily build does, in fact, fix the issue I reported. Thanks for the quick turnaround and the incredible product.
