### ISSUE TITLE
Will EF7 target .NET 6?

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#29238]
From the plan: "EF7 currently targets .NET 6. This may be updated to .NET 7 as we near the release."

Has a decision been made about which .NET it will target on general release?

Thanks

**Comment by roji** [comment]
This hasn't changed - EF7 will target .NET 6.

**Comment by stevendarby** [comment]
Just for avoidance of doubt, are you saying it _has_ changed, from "may be updated to .NET 7" to "won't be updated to .NET 7"? Thanks!

**Comment by roji** [comment]
Nothing has changed here - "EF7 will target .NET 6", so it won't be updated to .NET 7.

**Comment by stevendarby** [comment]
Thanks, I’m pleased to hear you’re no longer considering targeting .NET 7.
