### ISSUE TITLE
Can IgnoreQueryFilters apply to a single DbSet or Include in a query?

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#29237]
## Ask a question

On this [docs page](https://learn.microsoft.com/en-us/ef/core/querying/filters#disabling-filters), the following example shows how to use the `IgnoreQueryFilters` operator.

```C#
blogs = db.Blogs
    .Include(b => b.Posts)
    .IgnoreQueryFilters()
    .ToList();
```

Will it always apply to the whole query, or can it be used with a single `DbSet` or `Include`? e.g.

```C#
blogs = db.Blogs
    .Include(b => b.Posts).IgnoreQueryFilters() // applies only to Posts
    .Include(b => b.SomethingElse)
    .ToList();
```

### Include provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by ajcvickers** [comment]
@mrlife No. Instead, consider writing a query filter that is conditional on some state of the context instance.
