### ISSUE TITLE
How to re-arrange columns order of mysql database after updated database?

### ISSUE THREAD

**Issue by kehmMenovoo** [dotnet/efcore#29248]
Currently, I am working to update/modify columns order by modifying code in ef core 6 project only. I have researched and found annotation [Column(order=0)]  or [Column(order=1)] ... . But exactly if it works only first migration, for the next migrations by modifying column order in the model, the database doesn't update the following migr

**Model at first:**
```C#
public class Passenger
{
    [Column(Order=0)]
    public int Id {get; set;}

    [Column(Order = 1)]
    public string Name {get; set;}

    [Column(Order = 2)]
    public DateTime Created_at {get; set;}

}
```
![image](https://user-images.githubusercontent.com/83124370/193497382-c271b94e-c5b8-49fb-b774-6f57cfe5dba7.png)

After I add the new property **"Age"** into the model by setting column _order=2_ and **"Created_at"** 's _order=3_ but in the database, it displays **"Age"** at the last which is not my expectation.
**Latest Model:**
```C#
public class Passenger
{
    [Column(Order=0)]
    public int Id {get; set;}

    [Column(Order = 1)]
    public string Name {get; set;}

    [Column(Order = 2)]
    public int Age {get; set;}

    [Column(Order = 3)]
    public DateTime Created_at {get; set;}

}
```
![image](https://user-images.githubusercontent.com/83124370/193497344-d87c4b64-0b0c-449b-9d0c-c9376e2b0a86.png)

**Expectation:**
![image](https://user-images.githubusercontent.com/83124370/193498343-88e10524-504f-4b7b-9b31-970eb0cae586.png)

### Provider and version information

Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: EF Core 6.0
IDE: Visual Studio 2019 16.3

**Comment by roji** [comment]
@kehmMenovoo this is a provider-specific question which you'd need to post in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql.

Note that most database do not support reordering columns on an existing table (IIRC MySQL does support it, but whether the Pomelo provider has implemented support for this is another question). It's generally discouraged to worry about column order, and it shouldn't matter in most cases (e.g. EF always selects columns explicitly anyway).
