### ISSUE TITLE
AddSqlServer should have an `optionsAction` that provide the `IServiceProvider`

### ISSUE THREAD

**Issue by MarkusBux** [dotnet/efcore#29242]
Providing an EfCore Interceptor within the `AddSqlServer` extension method, that should be resolved from DI, is currently not possible, as the only available method signature is
```c#
public static IServiceCollection AddSqlServer<TContext>(
        this IServiceCollection serviceCollection,
        string? connectionString,
        Action<SqlServerDbContextOptionsBuilder>? sqlServerOptionsAction = null,
        Action<DbContextOptionsBuilder>? optionsAction = null)
        where TContext : DbContext
```

Therefore, doing something like this, is not possible
```c#
services.AddSqlServer<AppDbContext>(
        configuration.GetConnectionString("DataSource"),
        null,
        (sp, options) => options
            .EnableSensitiveDataLogging()
            .EnableDetailedErrors()
            .AddInterceptors(sp.GetRequiredService<MyCustomInterceptor>())
```

It would be helpful, to also have this method available
```c#
public static IServiceCollection AddSqlServer<TContext>(
    this IServiceCollection serviceCollection,
    string connectionString,
    Action<SqlServerDbContextOptionsBuilder>? sqlServerOptionsAction = null,
    Action<IServiceProvider, DbContextOptionsBuilder>? optionsAction = null) //<-- changed to also provide SP
    where TContext : DbContext
```

**Comment by ajcvickers** [comment]
@MarkusBux This is by-design. `AddDbContext` with `UseSqlServer` should be used for anything other than the most simple case. (Arguably, `AddDbContext` should always be used since `AddSqlServer` is so limited.)

**Comment by MarkusBux** [comment]
Hm... 
I understand, that `AddSqlServer` should be a very simple extension for adding a `DbContext` that is configured for using Sql Server.
But, as the method signature already covers an action for configuring the Sql options as well as an action  to configure context options, why not adding a second extension also include the `IServiceProvider` for the context options.
Therefore, I think the current extension is far away from just covering the simplest things.

As this is not a big deal, I will just use my own extension for that. But I'm still thinking that the addition of this possibility will not change the basic intent of this extensions but increase the usability and readability in some cases.

**Comment by ajcvickers** [comment]
@MarkusBux `AddSqlServer` convolutes two things together. We would not perpetuate this pattern. This seems fine:

```C#
services.AddDbContext<AppDbContext>(
	(sp, options) => options
		.UseSqlServer(configuration.GetConnectionString("DataSource"))
		.EnableSensitiveDataLogging()
		.EnableDetailedErrors()
		.AddInterceptors(sp.GetRequiredService<MyCustomInterceptor>()));
```

**Comment by MarkusBux** [comment]
Yeah, that is also valid. Will close the issue.
