### ISSUE TITLE
Entity is still returned by DbSet<T>/Queryable<T> after Remove() on DbContext has been called

### ISSUE THREAD

**Issue by hkoestin** [dotnet/efcore#2925]
I have the following test, which should verify, that within the same open DbContext and in a fresh DbContext, an aggregate is removed from the DB in background and not found anymore.

`store.StartTransaction|ReadScope` basically just opens a new DbContext and keeps this context alive for the using-scope.

``` c#
[TestMethod]
public void DocumentStore_Remove_aggregate_from_the_store_does_not_find_aggregate_anymore()
{
    var aggregate = new SimpleTestAggregate("42-test-value");
    var store = CreateStore();

    // put it into the store, commit the Tx here
    using (var transaction = store.StartTransaction())
    {
        store.Put(aggregate);
        transaction.Commit();
    }

    store = CreateStore();

    using (var transaction = store.StartTransaction())
    {
        store.AssertAggregateExistsInDatabase(aggregate.Version); // works

        store.Remove(aggregate.Identity); // --> Entity is marked as "Deleted" in the ChangeTracker

        // within this Tx, we do not want to see it anymore! 
        Assert.IsNull(store.Get(aggregate.Identity)); // --> this assert fails already

        transaction.Commit();
    }

    // and in another read tx neither
    using (store.StartReadScope())
    {
        Assert.IsNull(store.Get(aggregate.Identity));
        store.AssertAggregateNotExistsInDatabase(aggregate.Version);
    }
}

...
// the store.Get() method looks like 
Get<T>(Identity identity)
{
return context.Set<T>().SingleOrDefault(x => x.Identity == (Guid) identity);
}
```

Already the first assert after the Remove() method fails. The Entity is correctly marked for deletion in the change-tracker instance of the DbContext. I can verify this in the debugger.

However, when I then execute a query on the store (i.e. the Get(...) call), I still get back the entity, although it is being marked as "Deleted" in the change tracker.

Shouldn't a query on the DbSet<T> take into account the "Deleted" state and **NOT** return the entity anymore?
Or am I doing something obvious wrong?

**Comment by hkoestin** [comment]
Update:
Currently, only the call to transaction.Commit() calls a SaveChanges() on the DbContext.

If I change it to the following, it works:
* StartTransaction() really starts a Transaction on the DbContext
* Put/Remove call SaveChanges() on the DbContext
* Commit() on the transaction calls a SaveChanges() + a CommitTransaction() on the DbContext

Is this the way it should be done?

**Comment by divega** [comment]
@hkoestin whether you should call `SaveChanges()` after each individual change or wait until later depends on what behavior you want from your application, e.g. `SaveChanges()` typically wraps all changes sent to the database in a transaction, so either all changes will succeed or all will fail, so one criterion to decide when to call `SaveChanges()` is when you have completed a group of changes that should be treated as a transaction to maintain the database in a consistent state.

What you need to know to understand the behavior you are seeing is that LINQ queries in EF are primarily evaluated as database queries, i.e. whether an entity belongs in the results of a query is decided based on data for that entity in the database, and not data on the DbContext. Once we obtain the data from the database we proceed to apply necessary evaluation on the client and if you are using tracking queries we will merge the results from the database with existing entities in the DbContext (if we find an entity with the same key values). As a consequence, if an entity is marked for removal doesn't make it disappear from query results and conversely a new entity that only exists in the context will not show up on query results.

BTW, we have thought about doing more hybrid evaluation to address this expectation and we may enable it in the future.

**Comment by rowanmiller** [comment]
Hybrid eval scenarios now tracked by https://github.com/aspnet/EntityFramework/issues/2982
