### ISSUE TITLE
EF Core automatically creates expensive database when executing migrations

### ISSUE THREAD

**Issue by julienFlexsoft** [dotnet/efcore#29251]
Hi,

The software I made executes migrations in a controlled automatic process. Sometimes there is a small bug there than can cause the migration to happen for a DB that doesn't exist. The server of the connectionstring does exist, but the DB doesn't.
This causes EF Core to automatically create the DB and apply migrations. The issue here is that we use Azure SQL Server and the default pricing plan is a General purpose Gen5, this results in a massive bill if we don't notice the new DB right away.

Is there a way to modify this behavior or change the default pricing plan?
I saw some posts about Database Initializers but those seem to only exist in Entity Framework, not EF Core.

I saw this ["Specifying Azure SQL Database Options"](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/azure-sql-database). But this isn't what I'm looking for, I'd like for the default to be "basic" but this shouldn't be applied to all DB's we have deployed.

**Comment by ErikEJ** [comment]
Maybe add a check if the database  exists and use that in your further processing?

**Comment by ajcvickers** [comment]
As @ErikEJ says, you can use something like this:

```C#
if (context.GetService<IRelationalDatabaseCreator>().Exists())
{
    // Do stuff..
}
```

**Comment by vigouredelaruse** [comment]
apologies for harping on this but looked at another way, this feature pressents an attack vector for disgrunteled exployees exiting their jobs, or even ungruntled employeess just doing their jobs

in more detail, (copied from my query over here https://github.com/dotnet/efcore/issues/24866)

re: automatic creation of azure resources, specifically today referencing azure sql database (excluding managed instances, caveated here https://techcommunity.microsoft.com/t5/azure-sql-blog/what-azure-permissions-are-required-to-create-sql-managed/ba-p/386275)

a cursory investigation will show that database resource deployment in azure depends on an intersection of permissions

azure policy
azure arm
azure sql user permissions
azure policy permits macro governance and the document here https://learn.microsoft.com/en-us/azure/azure-sql/database/policy-reference?view=azuresql has the following to say about azure policy and azure sql database

Azure Policy applicable to a Azure SQL Database creation is not enforced when using T-SQL or SSMS.

in the form of a question:
given

an entity framework core app
running against azure sql database
authenticated with a user who does not have sql drop database or create database privs
is it reasonable to expect that developers cannot 'accidentally' spin up arbitrary azure sql server instances by using .ensurecreated() or .ensuredeleted() and/or .ensuremigrated()

i suggest that no, it's not reasonable to leave unaddressed a situation whereby incomplete or buggy implementations of database generation can spin up expensive resources and in the azure case, circumvent the entire rbac stack

please advise

**Comment by ajcvickers** [comment]
@julienFlexsoft EF Core doesn't have any special permissions here. It doesn't do anything that couldn't be done without EF Core, which includes creating databases. If you think Azure shouldn't allow this, then that's probably something you should bring up with the Azure folks.

**Comment by roji** [comment]
@julienFlexsoft as indicated [above](https://github.com/dotnet/efcore/issues/29251#issuecomment-1267386370), it's already trivial to add code which checks whether the database exists. So I'm not sure how the flag would help, given that it would default to true: anyone bitten by the issue today would continue getting bitten by the same issue tomorrow. All it would do is integrate the existence change inside MigrateAsync.

**Comment by vigouredelaruse** [comment]
further to @roji's suggestion of bringing this up with the azure entity see
https://feedback.azure.com/d365community/idea/cb36c798-3025-ec11-b6e6-000d3a4f0f84

given the longevity of the issue i'm getting the feeling the best that can be currently hoped for is a red card caveat in the documentation
