### ISSUE TITLE
No-Relational Provider - SaveChanges

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#29263]
Hello,

I am writing a non realtion provider for EF Core 6 and now I'am implement my `DatabaseWrapper` class that inherit from the class `Database`.

I'd like to ask about the override of `public override int SaveChanges(IList<IUpdateEntry> entries)`

I would expected that this method would receive as input parameter an `IEnumerable<IUpdateEntry>` instead of `IList<IUpdateEntry> entries`.

Is there any reason fr this? Is it possible to think that in some future `SaveChanges` will receive an `IEnumerable<IUpdateEntry>` and SaveChangesAsync an  `IAsyncEnumerable<IUpdateEntry>` ?

Many Thanks

**Comment by ajcvickers** [comment]
Two questions:

* Given you can treat `IList` as `IEnumerable`, what would be the advantage of `IEnumerable`?
* In what way could this be async?

**Comment by GLuca74** [comment]
Hello ajcvickers,

yes, I can treat `IList` as `IEnumerable`, it is wath I am doing now, but like this I loose all the advantages of `IEnumerable`.

For example, with `IEnumerable`, all elements are never all referenced in the same time so, for some scenarios, the `OutOfMemeryException` may be avoided.
Also, if for same reasons(for example an exception processing one element) I may decide to not process all the remained elements and if I stop to process the work of generating the remain elements is saved.

In my specific case, for each `IUpdateEntry` I create an object and I pass it to a web api using HTTP stream. 
Now my upload streaming can not start till all the `ILIst<IUpdateEntry>` is full created while if I receive an `IEnumerable<IUpdateEntry>` my upload streaming can start just after the first element is available.

About the async, pobability I have not enought skills to answer so maybe is better i say nothing, but also fo `SaveChangeAsync`, If i receive an `IEnumerable<IUpdateEntry>` I can get the same advantages.

**Comment by ajcvickers** [comment]
@GLuca74 But this object is coming from EF Core. Even if it's exposed as an IEnumerble, it's still going to be whatever EF creates from data in the state manager.

**Comment by GLuca74** [comment]
Yes, of course, I am not talking about just change the signature of the method, I am asking if  it is possible plan in some future to change the approch of generating the list of `IUpdateEntry`.

EF Core is full of `IEnumerable` approches, a small example, the first i found:

```
        public virtual IEnumerable<EntityEntry<TEntity>> Entries<TEntity>()
            where TEntity : class
        {
            TryDetectChanges();

            return StateManager.Entries
                .Where(e => e.Entity is TEntity)
                .Select(e => new EntityEntry<TEntity>(e));
        }

```
the `ChangeTracker` returns the Entries as `IEnumerable<EntityEntry<TEntity>>`. Who get the Entries through this method, get the advantages I wrote of `IEnumerable` approch.

**Comment by ajcvickers** [comment]
@GLuca74 No, because the state manager needs to make a defensive copy here so that the underlying data structures aren't modified while they are being enumerated.

**Comment by GLuca74** [comment]
OK, Thank you

**Comment by roji** [comment]
> About the async, pobability I have not enought skills to answer so maybe is better i say nothing, but also fo SaveChangeAsync, If i receive an IEnumerable<IUpdateEntry> I can get the same advantages.

For the async part, as @ajcvickers wrote above, the IUpdateEntry instances are calculated by EF Core when the user invokes SaveChanges/SaveChangesAsync, and then handed off to the provider for actual execution. There's nothing about this calculation (which is purely an in-memory change tracking operation) which could possibly involve I/O, so there's no reason for it to be an IAsyncEnumerable.
