### ISSUE TITLE
EF7 - GroupBy on Json column property + First/FirstOrDefault generates incorrect SQL

### ISSUE THREAD

**Issue by alienwareone** [dotnet/efcore#29279]
I've attached a minimal repo that produces the exception.

https://github.com/alienwareone/EfCoreGroupByJsonColumnProperty

**Comment by maumar** [comment]
VisitChildren on JsonQueryExpression doesn't visit key property map elements, so they don't get updated

**Comment by maumar** [comment]
fixed in 245f23d1ec0fc9cd907bdd409a79cad52db9b4dd
