### ISSUE TITLE
Global Query Filters for Owned Entities

### ISSUE THREAD

**Issue by Xriuk** [dotnet/efcore#29283]
Currently it's not possible to use Global Query Filters with Owned Entities.

In our project we have an Owned Entity used for localization, like this:

``` csharp
[Owned]
public class Localizable<TLocalization> {
	public string? LanguageCode { get; set; } // Mapped as composite key with the Owner in fluent API
	public TLocalization? LocalizedData { get; set; } // Nested owned entity
}

[Owned]
public class NameAndDescription{
	public string? Name { get; set; }
	public string? Description { get; set; }
}

public class Category{
	[...]

	public ICollection<Localizable<NameAndDescription>>? Localization { get; set; }
}
```

Which is used everywhere to localize our entities. The problem is that when we query our entities all the localizations are loaded (because of AutoInclude), of course we could load them manually by using Filtered Includes, but it would be nice to specify a global filter to allow us to filter a single language for all the entities (even included ones).

This could work on a per-class owned like `Localizable<NameAndDescription>` of `Category` like this:
``` csharp
modelBuilder.Entity<Category>()
	.OwnsMany<Localizable<NameAndDescription>>(p => p.Localization).WithOwner()
	.HasQueryFilter(l => l.LanguageCode == "en-us"); // Or a dynamic variable in DbContext like regular filters
```

**Comment by ajcvickers** [comment]
@Xriuk We discussed this, and it doesn't seem like `Localization` is part of the `Category` aggregate, and hence is not a good fit for an owned type. (Owned types don't have independent query filters since it is intended that the aggregate root is always used to query an aggregate, and it its therefore the root that should have the query filter.)

**Comment by Xriuk** [comment]
But owned entities can have their own table, right? That's what OwnsMany is for, so why Localization shouldn't be a good fit for an owned type?
This seems like the right case to me.
And since Localization can get its own table it should get its own query filter, only when it's OwnedMany of course

**Comment by ajcvickers** [comment]
@Xriuk Why not have a normal relationship? Why does it need to be owned?

**Comment by Xriuk** [comment]
Localization needs to be owned in our case because different entities have different localized, so they all generate different Localization tables which have different PK/FK which they get from the owner entity.
Logically it makes sense imho because an entity "owns" all its translations
What would be an acceptable case for OwnsMany otherwise?

**Comment by ajcvickers** [comment]
@Xriuk So, conceptually, this is a "dynamic" aggregate? That is, the localization info is always part of the aggregate, but what that aggregate actually is changes based on some external factor?

**Comment by Xriuk** [comment]
It's more like a "link" which connects an Entity with its localizable properties, each Entity has its own, it's owned in the sense that its PK depends on the owner's key:
```
[Owned]
public class NameAndDescription{
	public string? Name { get; set; }
	public string? Description { get; set; }
}

public class Category{
	public int Id { get; set; } // PK

	[...]

	public ICollection<Localizable<NameAndDescription>>? Localization { get; set; }
}
```
so the generated table becomes:
```
Category_Localization

        Composite PK         |  Properties (columns renamed)
----------------------------------------------------
CategoryId  |  LanguageCode  |  Name  |  Description
```


Another entity would have different localizable properties
```
[Owned]
public class NameAndImage{
	public string? Name { get; set; }
	public string? Image { get; set; } // Image URL, different for each language
}

public class Product{
	public string? Code { get; set; } // PK

	[...]

	public ICollection<Localizable<NameAndImage>>? Localization { get; set; }
}
```
and the resulting table would look similar:
```
Product_Localization

        Composite PK          |  Properties (columns renamed)
-----------------------------------------------
ProductCode  |  LanguageCode  |  Name  |  Image
```

So both Category_Localization and Product_Localization have different properties but have one (for now) common column which is the language code which would be useful to filter by, because we might want to retrieve only certain languages for the translations.

I don't know if owned entities is the right approach, to me it looks correct, because an entity owns its translation, and they're not used anywhere else, and should not be accessed outside entity's scope because a translation is unique to that instance of the entity.

The alternatives don't seem appealing: TPH would be impossible because all the entities have different PKs, TPT would add another table just to group all the translations for all the entity types, which is useless.

Imho if an Entity maps to a table it should be filterable.

**Comment by ajcvickers** [comment]
@Xriuk We will discuss again, but keep in mind that you can easily add a relationship between the two entity types without that relationship being owned.

**Comment by ajcvickers** [comment]
@Xriuk We discussed this again, and came to the conclusion that it won't work with EF Core aggregates. EF Core expects the aggregate to be fully loaded, since that is how aggregates are intended to be used. Having an aggregate which is either partially loaded, or changes based on some external condition, has the potential to corrupt the database when it is saved.

**Comment by Xriuk** [comment]
Cannot owned entities already be filtered when including them?
If i disable `AutoInclude()` on an owned entity I would have to include it manually via `Include()` and it supports filtering. Am I missing something? Is it wrong? How could it corrupt the database if I were to edit a single included owned entity instead of including them all?

**Comment by ajcvickers** [comment]
@Xriuk Owned entities model "aggregates". That is, a root type and dependent types where the dependent types are always part of the aggregate and never used independently of the root, and where the complete aggregate is always loaded in its entirety and operated on as a single unit. If only part of an aggregate is loaded, then when the aggregate is saved, there is potential for the part that is not loaded to be lost.

So doing what you want with a normal entity and a normal, required relationship to dependents filtered is fine, but making it an aggregate where only part of the aggregate is loaded does not align with how aggregates are intended to be used.
