### ISSUE TITLE
Ensure schema migration problematic to implement for PostgreSQL

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#2928]
Creating a schema in PostgreSQL is done with [`CREATE SCHEMA`](http://www.postgresql.org/docs/9.4/static/sql-createschema.html). In order to implement the ensure schema migration, it is therefore necessary to first query the database. However, we can't execute queries within the context of a MigrationsSqlGenerator...

SqlServer doesn't have this issue because it can use `IF SCHEMA_ID(...)`.

(note: the `CREATE SCHEMA IF NOT EXISTS`, which would have been perfect for this, was only introduced in PostgreSQL 9.3 which is quite recent).

**Comment by anpete** [comment]
@roji Querying the database from the client while migrating is not an option because it breaks scripting. Can you gen the query in SQL and check the result inline?

**Comment by roji** [comment]
Well, I was wondering why schema creation isn't handled like all other migrations... For everything else we have CreateTableOperation, CreateSequenceOperation, but only schemas have EnsureSchemaOperation... Is there a specific reason?

I don't think PostgreSQL will support querying and checking the result, but if there's really no other choice I'll try to take a look...

**Comment by bricelam** [comment]
The main reason is because we'll never scaffold a call to `DropSchema()`. We do this because there may be non-EF artifacts contained in the schema.

We only scaffold `EnsureSchema()` if a table or sequence has a schema that wasn't being used in the previous migration.

Most cases would work if you just implement it using `CREATE SCHEMA`. The case where it would fall down is:

1. Migration 1 adds `my.Table` (ensures `my` schema exists)
2. Migration 2 removes `my.Table` (`my` schema isn't dropped)
2. Migration 3 adds `my.OtherTable` (ensures `my` schema exists)

**Comment by roji** [comment]
@bricelam what you say makes sense, thanks for the explanation.

I guess since EF7 is "new tech" we can simply require PostgreSQL 9.3 or above, which has a clean `CREATE SCHEMA IF NOT EXISTS` syntax that can implement ensures. It seems better then to avoid this syntax and bomb in your 3rd migration above.

**Comment by bricelam** [comment]
Any reason you can't do something like this?
```SQL
IF (SELECT COUNT(*) FROM information_schema.schemata WHERE name = 'my') = 0 THEN
    CREATE SCHEMA my;
END IF;
```

**Comment by roji** [comment]
AFAIK PostgreSQL doesn't support IF statements in the wild, i.e. these aren't valid statements. I was kind of surprised to see that code for SqlServer actually.

What I could do is create a temporary stored procedure (in plpgsql) as part of the migration, then execute it, then drop it. This would be a pretty ugly approach but it would probably work...

**Comment by anpete** [comment]
http://www.postgresql.org/docs/7.3/static/plpgsql-control-structures.html

?

**Comment by roji** [comment]
@anpete, yep, that's plpgsql - which is PostgreSQL's stored procedure language. So it's not something you can just send to the database: you have to create the function first, then possibly drop it like I said above.

I guess there's nothing wrong with that approach apart from it being a bit ugly/cumbersome...

**Comment by anpete** [comment]
Makes sense. So I guess something like this: http://stackoverflow.com/questions/11299037/postgresql-if-statement

**Comment by roji** [comment]
Yeah, that's right. I'll go ahead with that.

**Comment by roji** [comment]
FYI the plpgsql function approach seems to work just fine, so compatibility with PostgreSQL < 9.3 is just fine.
