### ISSUE TITLE
Add support for validating data and reporting problems during data migrations

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#29299]
### Problem Description

I am customizing a complex data migration by adding custom SQL to make required changes.

For example, I have a `PurchaseOrders` table that includes a product name, but I'm changing it to be a foreign key to the `Products` table. So I need to write custom SQL set each foreign key to the ID of the matching product (this must be done before the migration can set that foreign key to be non-nullable).

However, it's possible for a product name not to match any product. In this case, I would like to flag this as an error with a message that the user must first add the missing product, preferably with the names of the missing products.

This doesn't appear to be possible. First off, `MigrationBuilder.Sql()` does support returning query results that I could use to verify the state of the database. And second, I couldn't find any information about the advisability of throwing exceptions within a data migration.

### Preferred Solution

I'm not looking for a big effort here. But if there was access to functionality that performs a query and could look at the results, and then if it was safe to throw an exception with a detailed error message, that would really help.

That would allow for faster deployments because all these steps could be automated, which could mean sites being updated would be down for a shorter period.

**Comment by ajcvickers** [comment]
@SoftCircuits How would this work when generating a SQL script for the migration?

**Comment by SoftCircuits** [comment]
@ajcvickers How does `MigrationBuilder.Sql()` work now?

A migration is just C# code. I was hoping I could just do a query and then throw an exception if the query returned certain results. Otherwise, just continue normally.

Or is a migration not run like normal C# code?

**Comment by ajcvickers** [comment]
@SoftCircuits One of the recommended and most common ways to deploy migrations is through generation of a SQL script. We generally don't want to add features that break that.

**Comment by SoftCircuits** [comment]
@ajcvickers I don't want to break anything.

My migrations look something like this:

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "Product",
            table: "Railcars",
            newName: "OldProduct");

        migrationBuilder.RenameColumn(
            name: "Product",
            table: "PurchaseOrders",
            newName: "OldProduct");
    }

Why couldn't code be inserted at the top of this method to run a query and, depending on the results, either throw an exception or allow the remaining lines to run?

**Comment by ajcvickers** [comment]
And when generating a SQL script to do that, what would the SQL look like?

**Comment by SoftCircuits** [comment]
@ajcvickers How does MigrationBuilder.Sql() work now?

From my perspective, no script would be generated for the added C# code I'm talking about. It would run like any other C# code.

And then if it threw an exception, the error message should be propagated to the user and no SQL would be generated.

If no exception is thrown, then the SQL would be generated exactly as before.

**Comment by ajcvickers** [comment]
> How does MigrationBuilder.Sql() work now?

The SQL goles into the script.

> From my perspective, no script would be generated for the added C# code I'm talking about. It would run like any other C# code. The code would run a query to test the state of the database. But that query would run immediately and no additional SQL would be generated from it.

But this doesn't work when generating a SQL script for the migration, which is a fundamental tenet of EF Core Migrations.

**Comment by SoftCircuits** [comment]
@ajcvickers Let me ask this:

1. If I had a class to access the database, would there be a problem with utilizing the class from within the `Up()` method?
2. Is it safe to throw an exception within the `Up()` method?

**Comment by SoftCircuits** [comment]
@ajcvickers Okay, I get it now. I guess I was thinking `MigrationBuilder.Sql()` ran immediately. But clearly it does not.

I see the only purpose of these migrations is to build a script that can be run multiple times on multiple systems, if needed. So putting validity checks in the `Up()` method doesn't make a lot of sense.

**Comment by ajcvickers** [comment]
> If I had a class to access the database, would there be a problem with utilizing the class from within the Up() method?

Yes, because a) the database may not be accessible then, and b) accessing the database there could not be replicated when generating a SQL script.

> Is it safe to throw an exception within the Up() method?

Safe? Depends what you mean? It would stop migrations being generated.
