### ISSUE TITLE
EFCore cannot get new value in docker, if use rsync replace sqlite file

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/efcore#29302]
Program environment
```
.NET6
Microsoft.EntityFrameworkCore.Sqlite:  6.0.9
Docker Desktop:  20.10.16
OS: Win10
```

I create an asp.net core project, which has an API query SQLite
```c#
[ApiController]
[Route("[controller]")]
public class HomeController : ControllerBase
{
    private readonly HeroDbContext _dbContext;

    public HomeController(HeroDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    [HttpGet("{id:int}")]
    public async Task<IActionResult> Get(int id, CancellationToken cancellationToken)
    {
        var hero = await _dbContext.Heroes.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
        var response = new { Data = hero, Successed = hero != null };
        return Ok(response);
    }
}
```

I deploy the project using the docker base on wsl2:
` docker run -d --name ddocker -p 9100:80  -v /mnt/c/Users/chiwenjun/Desktop/pdemo/docs/:/home/db/ ddocker`

If I change the SQLite file in `/mnt/c/Users/chiwenjun/Desktop/pdemo/docs` directory directly, the API can return the new value. But, if use rsync command sync a new SQLite file into the  `/mnt/c/Users/chiwenjun/Desktop/pdemo/docs` directory replace the old file, the value returned by the API was not changed.

I use python fastapi to write an API query the same SQLite file, it's can return the new value.

```python
class HeroDbContext:
    def __init__(self, conn_str):
        self.__conn_str = conn_str
        self.__conn = sqlite3.connect(conn_str)

    async def __aenter__(self):
        if self.__conn is None:
            self.__conn = sqlite3.connect(self.__conn_str)
        return self

    async def __aexit__(self, ex_type, ex_value, ex_traceback) -> bool:
        if self.__conn is not None:
            self.__conn.close()
        return True

    def get_by_id(self, id: int) -> Union[Hero, None]:
        try:
            cur = self.__conn.cursor()
            r = cur.execute("SELECT * FROM Heros WHERE Id=:id", [id])
            return self.__handle_db_result(r)
        finally:
            cur.close()

    def __handle_db_result(self, result: Cursor) -> Optional[Hero]:
        if result is None:
            return None
        data = result.fetchone()
        return None if data is None else Hero(data[0], data[1])
```

**Comment by bricelam** [comment]
Does it work if you add `Pooling=False` to the connection string?

**Comment by CwjXFH** [comment]
@bricelam It works after set `Pooling=False`, thanks! 
Could you please explain it?

**Comment by bricelam** [comment]
Sounds like a caching issue in the native SQLite library. Another workaround would be to call `SqliteConnection.ClearAllPools()` after the file is updated. That way you wouldn't have to disable pooling entirely.

**Comment by CwjXFH** [comment]
I use rsync command to sync file, so cannot exec `SqliteConnection.ClearAllPools()` method 😅 , anyway thanks!

**Comment by ajcvickers** [comment]
@CwjXFH Switching off connection pooling is the way to go. It is very likely that none of the other tools you are using have something like connection pooling, and hence they open a new physical connection to the database file every time. This is what Microsoft.Data.SqlClient will do when connection pooling is turned off, and rarely has significant performance cost.
