### ISSUE TITLE
Why was my previous bug about windows 11 and ef core toooling not working 

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/efcore#29319]
Why was my previous bug removed about ef core tooling not working I even provided a steps video !!!!!!

**Comment by roji** [comment]
@davidbuckleyni can you please point the the previous bug in question? I'm not seeing any previously-filed issue by you with a video etc.

**Comment by ajcvickers** [comment]
@roji https://github.com/dotnet/sdk/issues/28452

@davidbuckleyni It was moved to the SDK repo since it appears that the `donet` command line is not available, which is not something specific to EF.

**Comment by davidbuckleyni** [comment]
@ajcvickers many thanks cause I didn't get notified i thought was deleled can u link it here for me thanks

**Comment by roji** [comment]
Duplicate of https://github.com/dotnet/sdk/issues/28452
