### ISSUE TITLE
Decimal Parameters in query default to Precision=18, Scale=2

### ISSUE THREAD

**Issue by awdorrin** [dotnet/efcore#29313]
Decimal parameters passed into queries get unexpectedly transformed to Precision = 18, Scale = 2, generating invalid results.

The following code 
```
decimal value = 1.5m;
var query = context.SystemParameters.Select(x => (value / 100));
```
generates this SQL:
```
-- Region Parameters
-- @__p_0='?' (Precision = 18) (Scale = 2) (DbType = Decimal)
-- EndRegion
SELECT @__p_0
FROM [SystemParameter] AS [s]
```

Rather than getting back 0.015, the actual value passed to the database is 0.02, due to rounding up to 2 decimal places.
We discovered this while migrating code from EF6/.net4.5 to EFCore6/.Net6.

EF Queries in the legacy code might do something like this:
`
.Select( x=> x.PurchaseDetails.Sum( ld => (ld.POLineData.NetPrice * ld.ReceivedQty) * (LiquidationFactor / 100))
`
which would result in an expected calculation like: `14371.44 * 0.015`

However, due to the change in default precision, the parameter is calculated in C# and passed in as 0.02,
resulting in a calculation like: `14371.44 * 0.02`

While the model builder allows for configuring property/column precision, there does not appear to be a way to define the defaults for parameters. The only work around appears to be to change the order of operations, for example:

`
.Select( x=> x.PurchaseDetails.Sum( ld => ((ld.POLineData.NetPrice * ld.ReceivedQty) * LiquidationFactor) / 100))
`
which is not intuitive.

### Include provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows/Linux
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@awdorrin The default type mapping can be altered like this:

```C#
```

**Comment by awdorrin** [comment]
@ajcvickers Ah, I did not find that in my searching yesterday, unfortunately, it does not appear to be working for me.

Something very strange is going on...

If I alter the query to this:
 `.Select( x=> x.PurchaseDetails.Sum( ld => (LiquidationFactor / 100))`
Then in the SQL I see the parameter defined as:
 `@__p_4='?' (Precision = 18) (Scale = 8) (DbType = Decimal)`

But if I keep everything in one line:
 `.Select( x=> x.PurchaseDetails.Sum( ld => (ld.POLineData.NetPrice * ld.ReceivedQty) * (LiquidationFactor / 100))`
The parameter definition changes back to:
 `@__p_4='?' (Precision = 18) (Scale = 2) (DbType = Decimal)`

LiquidationFactor is defined as decimal and has a value of 1.5. 
It should be going across as 0.015, but in the second case it gets rounded to 0.02.

**Comment by awdorrin** [comment]
After a bit more reading and experimentation, it looks like the DefaultTypeMapping is not consistent.
However, using Properties<decimal>().HavePrecision(18,8) does appear to work.
I currently have the following:
```
        protected override void ConfigureConventions(ModelConfigurationBuilder configBuilder)
        {
            configBuilder.DefaultTypeMapping<decimal>(b => b.HasPrecision(18, 8));
            configBuilder.Properties<decimal>().HavePrecision(18, 8);
        }
```

**Comment by ajcvickers** [comment]
@awdorrin

Sorry, when you said, "While the model builder allows for configuring property/column precision, there does not appear to be a way to define the defaults for parameters," I thought that meant you were already doing the `configBuilder.Properties` part. This is needed when the type mapping is inferred from a property, but doesn't help in cases where the parameter is not correlated with any property, in which case the default type mapping is used. So you'll need both to cover all cases.

**Comment by awdorrin** [comment]
@ajcvickers  Make sense. Thanks so much for the help on this, we were pulling our hair out trying to figure out how to fix this.
I will close this issue out, since it isn't a bug, just a lack of our understanding in the new features.

**Comment by awdorrin** [comment]
@ajvickers Hoping you might be able to clear something up for me as we ran into an issue when adding a new migration to our application.
With the following code:
```
protected override void ConfigureConventions(ModelConfigurationBuilder configBuilder)
        {
            configBuilder.DefaultTypeMapping<decimal>(b => b.HasPrecision(18, 8));
            configBuilder.Properties<decimal>().HavePrecision(18, 8);
        }
```
A new migration is now overriding the precision for fields that have specific column types defined.
For instance, in our OnModelCreating() method we have a column defined like:
` entity.Property(e => e.VendorDefectiveQty).HasColumnType("decimal(13, 0)");`

but the migration gets:
```
            migrationBuilder.AlterColumn<decimal>(
                name: "VendorDefectiveQty",
                table: "QnoteHeader",
                type: "decimal(18,8)",
                precision: 18,
                scale: 8,
                nullable: true,
                oldClrType: typeof(decimal),
                oldType: "decimal(13,0)",
                oldNullable: true);
```
We thought that the ConfigureConventions would only override the default, not the entries specifically defined for the entities.
Hoping you can tell us what we are doing wrong.
Thank you!

**Comment by ajcvickers** [comment]
@AndriySvyryd This doesn't seem correct, since the column type is specified in the fluent API.

**Comment by awdorrin** [comment]
I found that this appears to impact both decimal and numeric values.
The migration appears to ignore .HasColumnType("decimal(x,y)") or .HasColumnType("numeric(x,y)")

but, if I add HasPrecision, the migration gets created correctly.
Example:
```
entity.Property(e => e.OpenQty).HasPrecision(18, 0).HasColumnType("numeric(18, 0)");
entity.Property(e => e.NetPrice).HasPrecision(18, 2).HasColumnType("decimal(18, 2)");
```

**Comment by ajcvickers** [comment]
@awdorrin Filed #29600 for this.
