### ISSUE TITLE
What is the best way to get the database column name of Entity Property (EF core 7 RC2)

### ISSUE THREAD

**Issue by TimKras** [dotnet/efcore#29321]
What is the best way to get the database column name of Entity Property (EF core 7 RC2).
Currently this is working, but is it possible to write it 'shorter'?

```c#
ColumnNameDB = property.Metadata.GetColumnName(StoreObjectIdentifier.Table(property.Metadata.DeclaringEntityType.GetTableName(), property.Metadata.DeclaringEntityType.GetSchema()));
```

**Comment by ajcvickers** [comment]
See https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#getcolumnname-obsolete

**Comment by TimKras** [comment]
Ok, you can simply use ```c#
ColumnNameDB = property.Metadata.GetColumnName();
```
