### ISSUE TITLE
IEntityStateListener, entity.IsPropertyModified never returns true.

### ISSUE THREAD

**Issue by jhermsen** [dotnet/efcore#2934]
I implemented a StateListener with the IEntityStateListener, but wheter I check in StateChanging or StateChanged the IsPropertyModified on the entry never returns true even though original value and entity value defer in the StateChanging method.

**Comment by rowanmiller** [comment]
**EF Team Triage:** Can you share code to demonstrate the specific issue you are seeing? There are a lot of moving pieces here so we'd need some code to understand the specific issue you are seeing.

**Comment by jhermsen** [comment]
Sorry for the delayed response.
I used the Identity project for the test and registered this statelistener:
```C#
    public class StateListener : IEntityStateListener
    {
        public void StateChanged(InternalEntityEntry entry, EntityState oldState)
        {
            if (oldState == EntityState.Modified)
            {
                foreach (var property in entry.EntityType.GetProperties())
                {
                    var changed = entry.IsPropertyModified(property);
                    if (changed)
                    {

                    }
                    
                    var changed2 = !Equals(entry.OriginalValues[property], entry.EntityType.ClrType.GetProperty(property.Name).GetValue(entry.Entity));
                    if (changed2)
                    {
                        
                    }
                }
            }
        }

        public void StateChanging(InternalEntityEntry entry, EntityState newState)
        {
            if (newState == EntityState.Modified)
            {
                foreach (var property in entry.EntityType.GetProperties())
                {
                    var changed = entry.IsPropertyModified(property);
                    if (changed)
                    {

                    }
                    var changed2 = !Equals(entry.OriginalValues[property], entry.EntityType.ClrType.GetProperty(property.Name).GetValue(entry.Entity));
                    if (changed2)
                    {
                        
                    }
                }
            }
        }
    }
```
I used brake points to check and changed is never true, but changed2 in StateChanging is true when changes occur.

**Comment by ajcvickers** [comment]
@jhermsen I just tried using your listener and after setting the entity state to Modified I got a StateChanged event as expected. In your code your are checking if the oldState is Modified, so nothing else kicks in because I'm changing from Unchanged to Modified, but if I change this to check for an oldState of Unchanged, then I see IsPropertyModified returning true for all non-key properties.

At this point it seems like everything is working. If you are still seeing an issue could you provide full code to reproduce it so we can dig down to the root cause?
