### ISSUE TITLE
How to delete the child rows via foreign key without loading navigation property?

### ISSUE THREAD

**Issue by ry18847** [dotnet/efcore#29341]
There are parent and child entities with foreign key constraints constructed with the option of NO ACTION. The primary key of the parent is known and retrieved from the DB, but the child is not loaded into the navigation property of the parent entity instance. In this situation, I want to delete both parent (1 row) and child (0~N rows).

* First I simply tried `DbContext.Parent.Remove(parent)`, `DbUpdateException` was thrown because the child's foreign key column is NOT NULL. this is to be expected because of the NO ACTION.
* Next I tried to load the parent's navigation property by `DbContext.Entity(parent).Collection(x => x.Children).Load()` and then removing both parent and child, it works correctly. However, this method would cause an extra DB query for load, which I would prefer to avoid (since the children are actually multiple tables).
* Finally, I tried a `DELETE FROM Child WHERE ParentId = @id` query in a raw SQL statement before `DbContext.Parent.Remove(parent)`. In this case, `DbUpdateConcurrencyException` was thrown from `SaveChanges`. Efcore try to null the child's foreign key after deleting the parent, but the child has already been deleted outside of EntityFramework, so concurrency error occured .

What I want to do is to retrieve one row of the parent entity, perform the necessary processing, and then delete both the parent and child rows from the database via foreign key, without executing SELECT statement for the child entity.
I am creating the DbContext by scaffolding, so I cannot add the settings for cascade deletion to the DbContext.
Is there a good way to do this?

EF Core version: 6.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.8
Target framework: NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.2.5

**Comment by ajcvickers** [comment]
@ry18847 This is covered by `ExecuteDelete` in EF7: See https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates. However, if you also want to keep tracked entities in sync and also use SaveChanges, then you'll need to make sure to make appropriate changes to the states of the tracked entities. In this case, it's probably best to stick with just SaveChanges and let it do all the work.

**Comment by ry18847** [comment]
Wow, it is written almost everything I wanted to know. 
Seems like it would be difficult to track. If so, I would like to use ExecuteDelete in EF7.
Thanks for the reply!
