### ISSUE TITLE
JSON Columns produce NULL value for empty collections

### ISSUE THREAD

**Issue by cschulzsuper** [dotnet/efcore#29348]
I played around with the new JSON Column mapping for SQL Server and found an issue when the owned property is a collection.

If I add a new object, an empty collection will produce a NULL in the database. I expected that it would produce an empty JSON array. (see `CreateJsonColumnWithNullValue` from the example) 

If I add a new object with at least one element in the collection, save the changes in the database, and subsequently remove the element and save the changed object again, an empty JSON array is stored in the database. (see `CreateJsonColumnWithEmptyArray` from the example) 

![image](https://user-images.githubusercontent.com/55575593/195678806-cc10c2eb-1484-4de3-9162-75233d7208a4.png)

```C#
using Microsoft.EntityFrameworkCore;

CreateJsonColumnWithNullValue();
CreateJsonColumnOneElement();
CreateJsonColumnWithEmptyArray();

void CreateJsonColumnWithNullValue() {
    var context = new TodoContext();

    context.Database.EnsureCreated();

    var todoList = new TodoList
    {
        Title = "List1",
    };

    context.Add(todoList);
    context.SaveChanges();

    context.Dispose();
}

void CreateJsonColumnOneElement() {

    var context = new TodoContext();

    context.Database.EnsureCreated();

    var todoList = new TodoList
    {
        Title = "List2",
        Items = new List<TodoItem>{
        new TodoItem { Text = "Item" }
    }
    };

    context.Add(todoList);
    context.SaveChanges();

    context.Dispose();
}

void CreateJsonColumnWithEmptyArray() {

    var context = new TodoContext();

    context.Database.EnsureCreated();

    var todoList = new TodoList
    {
        Title = "List3",
        Items = new List<TodoItem>{
        new TodoItem { Text = "Item" }
    }
    };

    context.Add(todoList);
    context.SaveChanges();

    todoList.Items.Clear();
    context.SaveChanges();

    context.Dispose();
}


public class TodoList
{
    public int Id { get; set; }
    public required string Title { get; set; }
    public IList<TodoItem> Items { get; set; } = new List<TodoItem>();
}

[Owned]
public class TodoItem
{
    public required string Text { get; set; }
}

public class TodoContext : DbContext
{
    public DbSet<TodoList> Todos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseSqlServer("SUPER_SECRET_CONNECTION_STRING");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<TodoList>()
            .OwnsMany(c => c.Items)
            .ToJson();
    }
}
```

### Include provider and version information

EF Core version: 7.0.0-rtm.22512.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0 RC2
IDE: Visual Studio 2022 17.4.0 Preview 3.0

**Comment by cschulzsuper** [comment]
The whole issue becomes problematic, when I read from the database. The collection might have a `null` value which the caller might not expect.

**Comment by ajcvickers** [comment]
@dradovic We will discuss. /cc @maumar

**Comment by kavehghelich** [comment]
I had the same issue when trying to change an owned collection to a JSON Column. For me the workaround was to tweak the generated migration, changing it from

```
migrationBuilder.AddColumn<string>(
    name: "PreviousLoans",
    table: "LoanRequests",
    type: "nvarchar(max)",
    nullable: true);
```
to
```
migrationBuilder.AddColumn<string>(
    name: "PreviousLoans",
    table: "LoanRequests",
    type: "nvarchar(max)",
    nullable: false,
    defaultValue: "[]");
```

**Comment by ajcvickers** [comment]
Notes for triage: let's agree on the behaviors for empty/null owned collections mapped to JSON. Proposal:

- Required (non-nullable) collection property:
  - Save:
    - If null when `SaveChanges` is called, then throw
    - If empty when `SaveChanges` is called, then save empty collection: `[]`
  - Query:
    - If property is missing in JSON, then throw or ignore?
    - If property is empty collection, then materialize empty collection
- Optional (nullable) collection property:
  - Save:
    - If null when `SaveChanges` is called, then don't save any property value
    - If empty when `SaveChanges` is called, then save empty collection: `[]`
  - Query:
    - If property is missing in JSON, then materialize null
    - If property is empty collection, then materialize empty collection

**Comment by antmeehan** [comment]
I'm guessing this isn't going to be fixed for EF Core 8 now? Might have to stick with https://github.com/Innofactor/EfCoreJsonValueConverter for a while longer.
