### ISSUE TITLE
Data migration using Parallel.For

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#29363]
## Ask a question
I need to migrate / ingest tens of thousands of records into SQL DB. I use `Parallel.For` to optimize the operation but bump into https://go.microsoft.com/fwlink/?linkid=2097913 How can I effectively use DbContext for this use case?

Remember:

* Please make your question as clear and specific as possible.
* Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include verbose output when asking questions about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version: 6.0.9
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) PostgreSQL
Target framework: (e.g. .NET 5.0) .Net 6.0
Operating system: Ubuntu 22.04
IDE: (e.g. Visual Studio 2019 16.3) VSCode

**Comment by roji** [comment]
@khteh EF isn't currently the most optimized way to import large amounts of data (#27333 tracks making this better). For optimal performance, use Npgsql's [binary COPY API](https://www.npgsql.org/doc/copy.html) directly.

If you'd like to use EF for this, it may be more efficient to run multiple imports on different instances of DbContext concurrently; but you can never use the same DbContext instance from more than one thread at a time. This will still be significantly slower than the Npgsql COPY API, though.

**Comment by khteh** [comment]
https://www.npgsql.org/doc/copy.html#binary-copy is rather crude. I need to ingest tens of thousands of record from Excel sheet into the DB without any duplicate.

**Comment by roji** [comment]
Cross-posted in https://github.com/dotnet/efcore/issues/27333#issuecomment-1434207095, continuing conversation there.
