### ISSUE TITLE
Query/Test: convert FromSql tests to use query infra

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#29365]
We will still need to provide the expected query as there is no way we can interpret the sql string to generate it automatically, but we can take advantage of the result verification and entire infra around context setup, sync/async etc. Also consider moving those tests to sql server as they can't really be reused by other providers.

**Comment by roji** [comment]
Sounds overall good, but don't we already use NormalizeDelimitersInRawString to make this provider-agnostic? As long we keep actual SQL queries simple, they should work well across providers etc.
