### ISSUE TITLE
Returns wrong count of a ICollection<T> with Include

### ISSUE THREAD

**Issue by cschuchardt88** [dotnet/efcore#29367]
```csharp
var something1 = db.Table1 // database table with 2 records.
                           // 1) 4 records in the list for Table2 with 3 records having DELETE status
                           // and 1 record with ENABLE status.
    .Include(i => i.Table2.Where(w => w.status != Status.DELETE)).ThenInclude(t => t.Table3)
    .Include(i => i.Table2.Where(w => w.status != Status.DELETE)).ThenInclude(t => t.Table4)
    .Where(w => w.Status != Status.DELETE); // Returns all 4 records
```
![image](https://user-images.githubusercontent.com/8141309/196017570-4aad147a-148e-4136-956b-5bd538269bdb.png)
[EFCoreTestBug.zip](https://github.com/dotnet/efcore/files/9793583/EFCoreTestBug.zip)

**Comment by maumar** [comment]
works fine on current bits. 
Table2 contains only 1 element for the first root entity and 4 elements for the second.

this is the sql we produce:

```sql
SELECT [t].[Id], [t].[Status], [t2].[Id], [t2].[Table1Id], [t2].[status], [t2].[Id0], [t2].[Table2Id], [t2].[Id1], [t2].[Table2Id0]
FROM [Table1] AS [t]
LEFT JOIN (
    SELECT [t0].[Id], [t0].[Table1Id], [t0].[status], [t1].[Id] AS [Id0], [t1].[Table2Id], [t3].[Id] AS [Id1], [t3].[Table2Id] AS [Table2Id0]
    FROM [Table2] AS [t0]
    LEFT JOIN [Table3] AS [t1] ON [t0].[Id] = [t1].[Table2Id]
    LEFT JOIN [Table4] AS [t3] ON [t0].[Id] = [t3].[Table2Id]
    WHERE [t0].[status] <> 2
) AS [t2] ON [t].[Id] = [t2].[Table1Id]
WHERE [t].[Status] <> 2
ORDER BY [t].[Id], [t2].[Id], [t2].[Id0]
```

**Comment by cschuchardt88** [comment]
SQL looks right, but the linq functions are not giving the right result.

**Comment by cschuchardt88** [comment]
What is happening here, is their are 4 records of table2; 3 with "delete" status and 1 with "enable" status.
The function is returning all 4 and not filting out the "delete" status ones like the expression says. So somewhere in code, not in sql is loading up all 4 records and returning them.

**Comment by cschuchardt88** [comment]
Im not understanding here! Regardless of the record count, Im filting out the ones with "DELETE" status and the collection has the "DELETED" status records. I WANT ANYTHING OTHER THEN "DELETE"!

**Comment by cschuchardt88** [comment]
@ajcvickers Thank you that information and your time.
```CSharp
var count = something1.Select(s => s.Table2.Count); // you get 4 with no tracking
```
add this code to the end with no tracking and you get "4". But only one item in table2

![image](https://user-images.githubusercontent.com/8141309/196205828-bed9c4bc-b689-450a-ad8f-a8f3463ddb1b.png)
