### ISSUE TITLE
It has an endless loop, and its ideal result is the same as "Teacher=null", because I have no Include.

### ISSUE THREAD

**Issue by panjonsen** [dotnet/efcore#29364]
It has an endless loop, and its ideal result is the same as "Teacher=null", because I have no Include.

![image](https://user-images.githubusercontent.com/61653451/196002507-2d78bc51-fb96-4d33-bd62-f577fa22a1e0.png)
![image](https://user-images.githubusercontent.com/61653451/196002510-668ec9b6-7082-4f76-92cc-ee5d3dc8d00e.png)
![image](https://user-images.githubusercontent.com/61653451/196002512-f63135c8-f28d-4d0f-8249-800d9d0a6567.png)
![image](https://user-images.githubusercontent.com/61653451/196002516-266b1f7b-60c7-4570-8c4c-6057c7795715.png)

```C#
    public class Student
    {
        public long StudentId { get; set; }

        public string StudentName { get; set; }

        public List<Teacher> Teachers { get; set; } = new List<Teacher>();

        public List<Student_Teacher> Student_Teachers { get; set; } = new List<Student_Teacher>();
    }
```
```C#
    public class Teacher
    {
        public long TeacherId { get; set; }

        public string TeacherName { get; set; }

        public List<Student> Students { get; set; } = new List<Student>();

        public List<Student_Teacher> Student_Teachers { get; set; } = new List<Student_Teacher>();
    }
```
```C#
    public class Student_Teacher
    {
        public long StudentId { get; set; }

        public long TeacherId { get; set; }

        public Student? Student { get; set; } 

        public Teacher? Teacher { get; set; }

        public int IsBind { get; set; }
    }
```

```C#
            var list = db.Students
                 .AsNoTracking()
                   .Include(m => m.Student_Teachers)
                   .ToList();

            Console.WriteLine(list);
```

### Include provider and version information

EF Core version:6.0.9
Database provider: Pomelo.EntityFrameworkCore.MySql 
Target framework:NET 6.0
Operating system:
IDE: 2022

**Comment by panjonsen** [comment]
My expression may not be very good. The problem I want to say is that it is infinitely nested.

**Comment by panjonsen** [comment]
I don't know how to solve this problem. I hope I can get help. Thank you.

**Comment by panjonsen** [comment]
> 它有一个无限循环，它的理想结果与“Teacher=null”相同，因为我没有Include。
> 
> ![图片](https://user-images.githubusercontent.com/61653451/196002507-2d78bc51-fb96-4d33-bd62-f577fa22a1e0.png) ![图片](https://user-images.githubusercontent.com/61653451/196002510-668ec9b6-7082-4f76-92cc-ee5d3dc8d00e.png) ![图片](https://user-images.githubusercontent.com/61653451/196002512-f63135c8-f28d-4d0f-8249-800d9d0a6567.png) ![图片](https://user-images.githubusercontent.com/61653451/196002516-266b1f7b-60c7-4570-8c4c-6057c7795715.png)
> 
> ```cs
>     public class Student
>     {
>         public long StudentId { get; set; }
> 
>         public string StudentName { get; set; }
> 
>         public List<Teacher> Teachers { get; set; } = new List<Teacher>();
> 
>         public List<Student_Teacher> Student_Teachers { get; set; } = new List<Student_Teacher>();
>     }
> ```
> 
> ```cs
>     public class Teacher
>     {
>         public long TeacherId { get; set; }
> 
>         public string TeacherName { get; set; }
> 
>         public List<Student> Students { get; set; } = new List<Student>();
> 
>         public List<Student_Teacher> Student_Teachers { get; set; } = new List<Student_Teacher>();
>     }
> ```
> 
> ```cs
>     public class Student_Teacher
>     {
>         public long StudentId { get; set; }
> 
>         public long TeacherId { get; set; }
> 
>         public Student? Student { get; set; } 
> 
>         public Teacher? Teacher { get; set; }
> 
>         public int IsBind { get; set; }
>     }
> ```
> 
> ```cs
>             var list = db.Students
>                  .AsNoTracking()
>                    .Include(m => m.Student_Teachers)
>                    .ToList();
> 
>             Console.WriteLine(list);
> ```
> 
> ### 包括提供者和版本信息
> EF Core version:6.0.9 Database provider: Pomelo.EntityFrameworkCore.MySql Target framework:NET 6.0 Operating system: IDE: 2022

```C#
    internal class Student_TeacherConfig : IEntityTypeConfiguration<Student_Teacher>
    {
        public void Configure(EntityTypeBuilder<Student_Teacher> builder)
        {
            builder.ToTable("T_Student_Teacher");

            ////复合主键
            builder.HasKey(b => new { b.StudentId, b.TeacherId });

            builder.Property(m => m.IsBind).HasDefaultValue(0);
        }
    }
```
```C#
   internal class StudentConfig : IEntityTypeConfiguration<Student>
    {
        public void Configure(EntityTypeBuilder<Student> builder)
        {
            builder.ToTable("T_Student");

            builder.HasMany(m => m.Student_Teachers)
                .WithOne(m => m.Student)
                .HasForeignKey(m => m.StudentId);
        }
    }
```
```C#
    internal class TeacherConfig : IEntityTypeConfiguration<Teacher>
    {
        public void Configure(EntityTypeBuilder<Teacher> builder)
        {
            builder.ToTable("T_Teacher");

            builder.HasMany(m => m.Student_Teachers)
               .WithOne(m => m.Teacher)
               .HasForeignKey(m => m.TeacherId);
        }
    }
```

**Comment by cschuchardt88** [comment]
I have something similar to this. Seems to be a problem with include function

**Comment by panjonsen** [comment]
> I have something similar to this. Seems to be a problem with include function

In my opinion, many historical questions are similar to this problem. It seems that there is no good solution. There is self reference. If the referenced object is still its own object, the result will be extended indefinitely.

**Comment by ajcvickers** [comment]
@panjonsen See #11564. Make sure to read the full discussion to really understand what is going on.

**Comment by panjonsen** [comment]
@ajcvickers  I have seen this problem, but it seems that there is no effective solution. For example, you can set it not to be fixed by infinite loops through features or code. As a result, people need to do a lot of extra things to make up for him. At present, I also use select to repair, but I think this is just a forced method. It should not be the solution he really should have.

**Comment by panjonsen** [comment]
@ajcvickers  I hope that the solution proposed with previous developers will be more effective and useful. To set it so that it will not continue to be repaired.

**Comment by ajcvickers** [comment]
@panjonsen Your questions are answered in the comments on https://github.com/dotnet/efcore/issues/11564.

**Comment by panjonsen** [comment]
services.AddDbContext<AppDbContext>(options =>
{
    options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
});

This is the best solution I think, but it will also bring some additional work, such as the update needs additional processing.
