### ISSUE TITLE
the query can not be translated, nested model filtering

### ISSUE THREAD

**Issue by ghostinside** [dotnet/efcore#29370]
how the code should be rewritten to have query be translated (filtered) to sql 

```cs
DbSet<Component>()
          .Include(_ => _.Function)
          .Select(dtoComponent => new Object_-1873088468___Function_ComponentAttribute1_ComponentIdentifier_Crc16checksum_Id_ImageLocation_Kobetron_LastUpdated_Md5hash_Media_Notes_Notif_UserName{
              UserName = dtoComponent.UserName,
              Notif = dtoComponent.Notif,
              Notes = dtoComponent.Notes,
              Media = dtoComponent.Media,
              Md5hash = dtoComponent.Md5hash,
              LastUpdated = dtoComponent.LastUpdated,
              Kobetron = dtoComponent.Kobetron,
              ImageLocation = dtoComponent.ImageLocation,
              Id = dtoComponent.Id,
              Crc16checksum = dtoComponent.Crc16checksum,
              ComponentIdentifier = dtoComponent.ComponentIdentifier,
              ComponentAttribute1 = dtoComponent.ComponentAttribute1,
              __Function = dtoComponent.Function ?? new Gfunction()
          }
          ) .Select(dtoLet => new ComponentModel{
              Id = dtoLet.Id,
              ComponentIdentifier = dtoLet.ComponentIdentifier,
              ComponentAttribute1 = dtoLet.ComponentAttribute1,
              Function = dtoLet.__Function == null ? null : new GlossaryItem{
                  Code = dtoLet.__Function.Code,
                  Description = dtoLet.__Function.Description
              }
              ,
              CRC16Checksum = dtoLet.Crc16checksum,
              MD5Hash = dtoLet.Md5hash,
              Kobetron = dtoLet.Kobetron,
              Media = dtoLet.Media,
              Notes = dtoLet.Notes,
              ImageLocation = dtoLet.ImageLocation,
              Notif = dtoLet.Notif,
              UserName = dtoLet.UserName,
              LastUpdated = (DateTime?)dtoLet.LastUpdated
          }
          )
          .OrderBy(_ => _.ComponentIdentifier)
          .Where(item => item.Function.Code.ToLower() == "i")
          .Count()'
```

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The LINQ expression 'DbSet<Component>()
          .OrderBy(c => c.ComponentIdentifier)
          .LeftJoin(
              inner: DbSet<Gfunction>(),
              outerKeySelector: c => EF.Property<string>(c, "FunctionId"),
              innerKeySelector: g => EF.Property<string>(g, "Code"),
              resultSelector: (o, i) => new TransparentIdentifier<Component, Gfunction>(
                  Outer = o,
                  Inner = i
              ))
          .Where(c => (c.Inner ?? new Gfunction()).Code.ToLower() == "i")' **could not be translated.**
```

with inline fields works well

EF Core version: 6.0.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: 6.0.3
Operating system: win 11
IDE: (e.g. Visual Studio 2019 16.3) 2022

**Comment by ajcvickers** [comment]
@ghostinside `new Gfunction()` cannot be translated. It is opaque to the EF Core query translator.

**Comment by ghostinside** [comment]
> @ghostinside `new Gfunction()` cannot be translated. It is opaque to the EF Core query translator.

so, the only way we can "fix" it is to flatten the model, right?

**Comment by ghostinside** [comment]
the server code is 

`var result = await _mapper.ProjectTo<ComponentModel>(
                _corpDbContext.Component
                    .Include(_ => _.Function))
                .OrderBy(_=>_.ComponentIdentifier)
                .ToDataSourceResultAsync(request.DataSourceRequest);
            return new DataEnvelope<ComponentModel>()
            {
                Data = result.Data.Cast<ComponentModel>().ToList(), 
                Total = result.Total
            };`

the component model is 
`public partial class Component
    {
        public Component()
        {
            ProductVersionComponentMapping = new HashSet<ProductVersionComponentMapping>();
        }

        public int Id { get; set; }
        public string ComponentIdentifier { get; set; }
        public string Crc16checksum { get; set; }
        public string Md5hash { get; set; }
        public string Kobetron { get; set; }
        public string Media { get; set; }
        public string Notes { get; set; }
        public string FunctionId { get; set; }
        public string ComponentAttribute1 { get; set; }
        public DateTime LastUpdated { get; set; }
        public string UserName { get; set; }
        public bool Notif { get; set; }
        public string ImageLocation { get; set; }

        public virtual Gfunction Function { get; set; }
        public virtual ICollection<ProductVersionComponentMapping> ProductVersionComponentMapping { get; set; }
    }`

if I got you right that the core of the issue is how the query was constructed by automapper & expression builder, if I rewrite it manually or change the expression to something like this 

"_corpDbContext.Component.Include(_ => _.Function).where(_=>_.Function.Code = 'A')" it will be successfully translated?

**Comment by ghostinside** [comment]
seems the problem is in automapper, changed mapping a little bit, got 

` The LINQ expression 'DbSet<Component>()
          .OrderBy(c => c.ComponentIdentifier)
          .Where(c => new ComponentModel{
              Id = c.Id,
              ComponentIdentifier = c.ComponentIdentifier,
              ComponentAttribute1 = c.ComponentAttribute1,
              CRC16Checksum = c.Crc16checksum,
              MD5Hash = c.Md5hash,
              Kobetron = c.Kobetron,
              Media = c.Media,
              Notes = c.Notes,
              ImageLocation = c.ImageLocation,
              Notif = c.Notif,
              UserName = c.UserName,
              LastUpdated = (DateTime?)c.LastUpdated
          }
          .GFunction.Key.ToLower() == "i")'`

so, finally, know where to dig

**Comment by ghostinside** [comment]
i made it work, thx for help,
