### ISSUE TITLE
Raw new DbContext will memory leak

### ISSUE THREAD

**Issue by Cricle** [dotnet/efcore#29371]
### Include your code

```C#
public class OOMInsetOrQuery : ITestCase
{
    public Task RunAsync()
    {
        Console.ReadLine();
        var mem1 = GC.GetTotalMemory(true);
        for (int i = 0; i < 1000; i++)
        {
            var mb = new ModelBuilder();
            mb.SharedTypeEntity<Dictionary<string,object>>("dynamic", x =>
            {
                x.Property(typeof(long), "id").IsRequired();
                x.Property(typeof(DateTime), "name").IsRequired();
                x.Property(typeof(string), "id1").HasMaxLength(40).IsRequired(false);
                x.HasKey("id");

                x.ToTable("student1");
            });
            var builder = new DbContextOptionsBuilder()
                .UseMySql($"Database='sakila';Data Source=127.0.0.1;Port=3306;User ID=root;Password=;Character Set=utf8;",
                ServerVersion.Create(new Version(8, 0, 0), ServerType.MySql))
                .UseModel(mb.FinalizeModel());
            var opt = builder.Options;
            opt.GetExtension<CoreOptionsExtension>().WithServiceProviderCachingEnabled(false);
            var dbc = new DbContext(opt);
            
            dbc.Set<Dictionary<string, object>>("dynamic")
                .Add(new Dictionary<string, object>
                {
                    ["name"] = DateTime.Now.AddHours(i),
                    ["id1"] = i.ToString()
                });
            dbc.SaveChanges();
            dbc.Dispose();//I sure it will be execute!
        }
        var mem2 = GC.GetTotalMemory(true);
        Console.WriteLine($"Sub: {(mem2-mem1)/1024/1024.0:f4}MB");
        Console.ReadLine();
        return Task.CompletedTask;
    }
}
```

Result is `55MB`

### Include stack traces
![image](https://user-images.githubusercontent.com/26201412/196078866-e558bde4-d517-4ed9-824a-40084dcd8cab.png)
Here is memory diagnostics.object results.

![image](https://user-images.githubusercontent.com/26201412/196079398-62582a77-145d-4520-8c93-eaf33b948eff.png)
Here is memory diagnostics.heap results.

### Include provider and version information

EF Core version:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.9" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.1" />
  </ItemGroup>
```
Target framework: (.NET 6.0)
Operating system:
IDE: (Visual Studio 2022 17.3.3)

**Comment by Cricle** [comment]
When i change to 
```csharp
public class OOMInsetOrQuery1 
{
    public class Student
    {
        public int id { get; set; }

        public DateTime name { get; set; }

        public string id1 { get; set; }
    }
    public Task RunAsync()
    {
        Console.ReadLine();
        var mem1 = GC.GetTotalMemory(true);
        for (int i = 0; i < 1000; i++)
        {
            var mb = new ModelBuilder();
            mb.Entity<Student>(x =>
            {
                x.Property(typeof(int), "id").IsRequired();
                x.Property(typeof(DateTime), "name").IsRequired();
                x.Property(typeof(string), "id1").HasMaxLength(40).IsRequired(false);
                x.HasKey("id");
                x.ToTable("student1");
            });
            var builder = new DbContextOptionsBuilder()
                .UseMySql($"Database='sakila';Data Source=127.0.0.1;Port=3306;User ID=root;Password=;Character Set=utf8;",
                ServerVersion.Create(new Version(8, 0, 0), ServerType.MySql))
                .UseModel(mb.FinalizeModel());
            var opt = builder.Options;
            opt.GetExtension<CoreOptionsExtension>().WithServiceProviderCachingEnabled(false);
            var dbc = new DbContext(opt);

            dbc.Set<Student>()
                .Add(new Student
                {
                    name = DateTime.Now.AddHours(i),
                    id1 = i.ToString()
                });
            dbc.SaveChanges();
            dbc.Dispose();
        }
        var mem2 = GC.GetTotalMemory(true);
        Console.WriteLine($"Sub: {(mem2 - mem1) / 1024 / 1024.0:f4}MB");
        Console.ReadLine();
        return Task.CompletedTask;
    }
}

```

Result is `48MB`

**Comment by Cricle** [comment]
But if i add

```csharp
dbc.SaveChanges();
dbc.Dispose();
//add begin
var map=(IDictionary)ServiceProviderCache.Instance.GetType()
    .GetField("_configurations", BindingFlags.NonPublic | BindingFlags.Instance)
    .GetValue(ServiceProviderCache.Instance);
map.Clear();
//add end
```

Result is `2MB`

**Comment by ajcvickers** [comment]
@Cricle EF Core works by caching various information across uses of DbContext instances. This generally shouldn't be a problem, but if it is, then you can manage the internal service provider yourself using `.UseInternalServiceProvider()` when building your DbContextOptions. This is not recommended; it requires understanding when to cache and when not to. Or, if you never cache, it will result in extremely inefficient code.

**Comment by roji** [comment]
To add to what @ajcvickers wrote, creating a new model for every context instance is extremely bad for perf, and not the way EF is intended to be used. You may want to give [this doc page](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model) a read.

**Comment by Cricle** [comment]
The actual business is that even databases and models are not necessarily equal and unknown model changes will occur (like the `Navicat` database management tool). You need to request http from other places to obtain models and connection strings at runtime. In this case, can you continue to use `IModelCacheKeyFactory`?
Thinks.

**Comment by roji** [comment]
@Cricle IModelCacheKeyFactory makes sense where the number of models is relatively limited, and you reuse models based on some key which can be extracted. It's fine to do some HTTP request to fetch some information, and then use that information in the key, which determines which model gets selected; that's what the example in [the doc page](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model) shows: the UseIntProperty member on the DbContext determines which model gets used.

However, if you really are in a totally dynamic scenario where you need to build a model for each request, then I don't think EF is the right tool for that; you're better off using something else. So it's fine to have multiple models and select them via IModelCacheKeyFactory based on something, but totally dynamic scenarios are something else.

**Comment by Cricle** [comment]
Thanks.
