### ISSUE TITLE
RelationalEntityTypeExtensions.GetSchemaQualifiedTableName() should ignore schemas when used with SQLite

### ISSUE THREAD

**Issue by scott-moxham** [dotnet/efcore#29378]
## File a bug
When working with a Sqlite database, `RelationalEntityTypeExtensions.GetSchemaQualifiedTableName()` has a result of the form `schema.table` but Sqlite doesn't support schemas within a database so I would expect the result to be just `table`.

This is causing me problems because I'm generating some simple SQL that needs to work for both PostgreSQL and Sqlite. The table name part of the sql needs to be different as PostgreSQL needs the schema name, Sqlite does not. I expected `GetSchemaQualifiedTableName()` to help with this, but it doesn't.

The scenario I have is that my production database runs on PostgreSQL but my unit tests run in an in-memory SQLite database.

```
var tableName = dbContext.Model.FindEntityType(typeof(ClientHistory))!.GetSchemaQualifiedTableName();
```
### Include your code

Demonstration solution can be found at https://github.com/scott-moxham/SQLiteTableNameBug

### Include provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.Sqlite v6.0.9
Target framework: .Net6
Operating system: Windows 10
IDE: Visual Studio 2022 17.3.5

**Comment by ajcvickers** [comment]
@scott-moxham Rightly or wrongly, if a schema is configured for a SQLite model, then it remains part of the model, but is ignored when generating SQL. There are some historical reasons for this which may not now be valid, but it's not something we can change now.

A few ideas/questions:
* We're curious why do you specifically need `GetSchemaQualifiedTableName` in your tests? Understanding this might make it easier to suggest what could be done.
* Consider conditionally building the model in `OnModelCreating` to not specify a schema when building the model for SQLite. For example:
  ```C#
  if (!Database.IsSqlite())
  {
      // ...
  }
  ```
* Consider using PostgreSQL for your testing--see [Testing against your production database system](https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database).

**Comment by scott-moxham** [comment]
I need to execute some SQL in my repository that is too complex for EF Core to do efficiently on its own but the currently I have to have two lots of SQL in my repo as the table name is different depending on whether running on Postgres / SQLite (schema.table vs table). This is far from ideal as my tests are testing slightly different code to that running in production.

I hoped that I could use GetSchemaQualifiedTableName() to get the table name and I could insert this into the SQL and thus use the same code for both databases.

Using PostgreSQL for unit tests isn't practical as it would require a lot of work making it available on all machines that run the tests and isolation between tests requires a lot of work / reducing parallelism, which would also impact performance (we have a lot of tests that add / modify / delete data, often in transactions). We currently create a new in memory SQLite db for every test, which ensures 100% isolation, while keeping performance snappy.

**Comment by ajcvickers** [comment]
> I need to execute some SQL in my repository that is too complex for EF Core to do efficiently on its own

Does the same SQL work on SQLite and PostgreSQL? Differences in SQL dialects often make this kind of thing impossible.

**Comment by scott-moxham** [comment]
In this case, it does, with the exception of the table name.

**Comment by roji** [comment]
I'd suggest doing a simple extension method which checks which provider is being used, and then either calls GetSchemaQualifiedTableName (on PG) or GetTableName (on SQLite).
