### ISSUE TITLE
Is the usage of enums as discriminators supported in TPH?

### ISSUE THREAD

**Issue by lennartb-** [dotnet/efcore#29373]
I've found #18769, but the error is different and since it's closed as "not planned", I'm unsure if this is even supported.

My structure looks like this:

```
public abstract class FooEntity
{  
    public Guid FooTypeId { get; set; }
  
    public FooTypeEntity FooType { get; set; } = null!;

    public BarKind BarKind => FooType.TypeIdentifier;
	
}

public class FooTypeEntity
{   
    public Guid Id { get; set; }
    
    public BarKind TypeIdentifier { get; set; }
}

public class DerivedEntity : FooEntity
{
}

public enum BarKind
{
    A = 1,
    B = 2
}

```

I'm assigning the discriminator like this:

```
_ = modelBuilder.Entity<FooEntity>()
     .HasDiscriminator<BarKind>(nameof(FooEntity.BarKind))
     .HasValue<DerivedEntity>(BarKind.A);
```

which fails with
> System.InvalidOperationException: 'Both 'DerivedEntity' and 'FooEntity' are mapped to the table 'dbo.contoso_foo'. All the entity types in a hierarchy that don't have a discriminator must be mapped to different tables. See https://go.microsoft.com/fwlink/?linkid=2130430 for more information.'

However, if I don't use the `BarKind` enum, but the `FooTypeId` GUID, the mapping succeeds:

```
= modelBuilder.Entity<FooEntity>()
      .HasDiscriminator(a => a.FooTypeId)
      .HasValue<DerivedEntity>(new Guid("1D973DD8-EBC8-44E9-93E8-91B7B1CE19A5"));
```

Are enums not supported as discriminators? I don't find a conclusive answer that it's _not_ supported, but all examples don't use an enum in the first place.

### Include provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: Win 11
IDE: VS 2021 17.5.6

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
Btw, enum discriminators are supported. Here's a simple example:

```C#
public abstract class FooEntity
{  
    public Guid FooTypeId { get; set; }
    public FooTypeEntity FooType { get; set; } = null!;
    public BarKind BarKind { get; set; }
}

public class FooTypeEntity
{   
    public Guid Id { get; set; }
    public BarKind TypeIdentifier { get; set; }
}

public class DerivedEntity : FooEntity
{
}

public enum BarKind
{
    A = 1,
    B = 2
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FooEntity>().HasKey(e => e.FooTypeId);
        
        modelBuilder.Entity<FooEntity>()
            .HasDiscriminator<BarKind>(nameof(FooEntity.BarKind))
            .HasValue<DerivedEntity>(BarKind.A);
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
   }
}
```

**Comment by ajcvickers** [comment]
@lennartb- I think this is going to require a concrete schema and/or code sample for me to be able to fully understand.

**Comment by lennartb-** [comment]
Yeah, sorry, our DB and application is just much larger, and I have to cut the unnecessary stuff while keeping everything consistent. Does this schema help?

```
USE [Contoso_DB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[contoso_fooTypes](
	[type_identifier] [nvarchar](250) NULL, 	        /** This is the string that will be the BarKind enum **/		
	[fooType_id] [uniqueidentifier] NOT NULL,	/** PK **/	
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[contoso_foo](
	[foo_id] [uniqueidentifier] NOT NULL,			/** PK **/	
	[name] [nvarchar](250) NOT NULL,				/** DerivedA, DerivedB,... **/
	[foo_type_id_ref] [uniqueidentifier] NOT NULL,	/** FK on contoso_fooTypes.fooType_id **/
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[contoso_fooTypes] ADD  DEFAULT (newid()) FOR [fooType_id]
GO
ALTER TABLE [dbo].[contoso_foo] ADD  DEFAULT (newid()) FOR [foo_id]
GO
```

**Comment by ajcvickers** [comment]
@lennartb- I don't think that schema can be mapped with an enum discriminator. Also, if the type of a `contoso_foo` can change (by changing the FK to point to a different `contoso_fooTypes`), then inheritance mapping is probably not a good choice, since objects cannot change their types in .NET. Consider using simple composition instead.
