### ISSUE TITLE
Inconsistent behaviour with Parent-Children Relations

### ISSUE THREAD

**Issue by default0** [dotnet/efcore#2937]
The following model has inconsistent behaviour when queried via LINQ with entities:

```
    public class Test
    {
        public Test()
        {
            Children = new List<Test>();
        }

        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        [ForeignKey(nameof(ParentId))]
        public ICollection<Test> Children { get; set; }

        public int? ParentId { get; set; }
        [ForeignKey(nameof(ParentId))]
        public Test Parent { get; set; }

        [NotMapped]
        public string Path
        {
            //get { return "Test"; }
            get { return Parent != null ? Parent.Path + '.' + Name : Name; }
        }
    }
```

Given a simple Context like this:

```
    public class MyContext : DbContext
    {
        public DbSet<Test> Tests { get; set; }
    }
```

And then adding some data to it (in my case, like this):

```
            Test t = new Test()
            {
                Text = "Child",
            };
            Test p = new Test()
            {
                Text = "Parent",
                Children = new List<Test>() { t }
            };
            t.Parent = p;
            ctx.Tests.Add(p);
            ctx.SaveChanges();
```

And then restarting the application (so the Query/Object-Cache is cleared) and then querying like so:

```
            foreach (Test test in ctx.Tests.Where(x => x.Text == "Child" && x.Parent != null))
            {
                Console.WriteLine("Is the parent null?: " + (test.Parent == null).ToString());
            }
```

Outputs "true" for the added "Child" object.

However, querying like so:

```
            Console.WriteLine("=== ALL ELEMENTS ===");
            foreach (Test test in ctx.Tests)
            {
                Console.WriteLine("Found t with path " + test.Path);
            }
            Console.WriteLine("=== FILTERED ELEMENTS ===");
            foreach (Test test in ctx.Tests.Where(x => x.Text == "Child" && x.Parent != null))
            {
                Console.WriteLine("Is the parent null?: " + (test.Parent == null).ToString());
            }
```

Outputs "false" for the added "Child" object.

I tried this on a MySql Database, with both the Devart MySql Provider, and Oracles MySql Provider, and got the same behaviour on both, which leads me to think this is an issue with EntityFramework.
Note that `test.ParentId` is set to its correct value, just the property `test.Parent` does not get populated unless you first load the parent objects into the cache (ie, the caching mechanism causes a change in behaviour of population).

I find this behaviour really odd, I'm not sure if this is a bug, but it is very weird that the cache has effects like that.

Best Regards

**Comment by ErikEJ** [comment]
If this is a EF6 issue, it is better to report it here http://entityframework.codeplex.com/workitem/list/basic , as this is the EF7 code repository

**Comment by default0** [comment]
Has been done https://entityframework.codeplex.com/workitem/2809#
Might still be worthwhile to try a repro on EF7 and see if it's also an issue there, or if no one cares, this can be closed :-)

**Comment by rowanmiller** [comment]
Closing as we will follow up on the EF6 issue.
