### ISSUE TITLE
add-migration within VS Package Manager Console hangs due to Debug.Assert() (in own code)

### ISSUE THREAD

**Issue by springy76** [dotnet/efcore#29386]
Just placing a `Debug.Assert()` call (which fails) inside `DbContext.OnModelCreating()` ends with package manager console waiting forever whithout any result, hitting the red square cancel button also does nothing.

Finding the dotnet.exe in TaskManager (and capturing its command line) and killing it finally results in "The pipeline has been stopped." error message.

Inserting the captured command line (2 miles long) into console at least revealed that the process was terminated (yeah? really?) due to a failed assertion.

EF/net 6.0.8

**Comment by ajcvickers** [comment]
@springy76 The action taken when `Debug.Assert()` fails is not something that EF Core can control. In my experience, execution usually stops and some kind of user interaction is initiated; for example, a dialog box. If the execution environment cannot handle this, then it can appear to be a hang. Similar issues happen in some test runners.

You could potentially bring this up with VS or the PMC team, but I suspect it's unlikely to change anything.

**Comment by springy76** [comment]
Speaking of "control":

After having entered `Add-Migration Initial` I see 2 messages
1) Building...
2) Build succeeded

Then I see a new dotnet.exe process with a command line which contains things like `ef.dll`, `--verbose` (I did not specify verbose) and `outputtype json`.

When I execute this command line in a fresh console I receive plenty of verbose messages like `Finding application service provider in assembly` or `No application service provider was found`.

But the point is: I don't find code/commits for those message in this repo:
https://github.com/dotnet/efcore/search?q=Finding+application+service+provider+in+assembly&type=code
https://github.com/dotnet/efcore/search?q=No+application+service+provider+was+found&type=code

Under whose control this is?

**Comment by ajcvickers** [comment]
https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Properties/DesignStrings.Designer.cs#L291
https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Properties/DesignStrings.Designer.cs#L559
