### ISSUE TITLE
Columns with name "Id" in JSon object causes System.ArgumentException in materialization

### ISSUE THREAD

**Issue by jonnybee** [dotnet/efcore#29380]
Using EF Core 7.0.0-rc.2.22472.11 (also same in v7.0.0-rtm.22504.12)

When JSon child object has a column named Id (f.ex of type Int) the materialization will throw: 
**System.ArgumentException**: 'Expression of type 'System.Object' cannot be used for constructor parameter of type 'System.Int32' 

Make these modifications to NewInEFCore7 sample in EntityFramework.Docs to reproduce the bug: 
```C#
public class Commit
{
    public Commit(int id, DateTime committedOn, string comment)
    {
        Id = id;
        CommittedOn = committedOn;
        Comment = comment;
    }

    public int Id {get; private set; }
    public DateTime CommittedOn { get; private set; }
    public string Comment { get; set; }
}

// Update BuildPostMetadata method to send in an id as constructor parameter

    for (var j = 0; j < random.Next(3); j++)
     {
           update.Commits.Add(new(j+1, DateTime.Today, $"Commit #{j + 1}"));
     }
```

When you run the sample it will now throw ArgumentException here: 
![image](https://user-images.githubusercontent.com/3512406/196225180-c81b8b65-c6c5-4b3d-9cb8-cf78accab960.png)

If I change Id to a property with { get; set; } and no parameters to the CTOR this exception is thrown: 
**System.ArgumentException:** 'Expression of type 'System.Object' cannot be used for assignment to type 'System.Int32''

**Comment by ajcvickers** [comment]
@maumar Looks like it could be a problem with constructor binding for JSON objects in the materializer.

**Comment by jonnybee** [comment]
@maumar @ajcvickers Other properties of type int is deserialized OK - but when named Id will throw the ArgumentException. Could it be that **Id** is considered Key by convention for that type?

**Comment by ajcvickers** [comment]
@jonnybee Yes, I suspect that it is something to do with that.

**Comment by maumar** [comment]
we should at least throw in validation until flexible ordinal key is implemented

**Comment by ajcvickers** [comment]
Note from triage: we should investigate if this is a materialization bug separate from #28594.

Possible workaround if the entity doesn't need the property to be called `Id` but `Id` is required in the JSON::

```C#
modelBuilder.Entity<Customer>()
    .OwnsOne(customer => customer.Contact, b =>
    {
        b.ToJson();
        b.OwnsMany(e => e.PhoneNumbers, b =>
        {
            b.Property(e => e.Key).HasJsonPropertyName("Id");
        });
    });
```

**Comment by maumar** [comment]
the problem comes from the fact that the Id property is considered to be a key.
In case of JSON entity each property is either column access (in case of key - we project the key column and access value based on that column index) or JsonElement.TryGetProperty (in case of normal JSON property). In this case Id column is considered to be a key, so we try to access it based on index (which isn't there) and hence the bug.

There doesn't seem to be a separate materialization bug, apart from https://github.com/dotnet/efcore/issues/28594.

**Comment by johnatanstanley** [comment]
Hi, I'm also facing the same (or very similar) problem when a property is like:

`public int [CLASSNAME]Id {get; set; } // Like "CommitId" in the first example of this post`

If I'm not mistaken, entity use this nomenclature to generate reference between classes, so may be is "reserved" too.

**Comment by ajcvickers** [comment]
Notes from triage:

- It should be possible to have a property called "Id" that is not the ordinal key.
- Being able to explicitly map the key (#28594) is also important, but different from this issue.

**Comment by Tizioincognit0** [comment]
> * It should be possible to have a property called "Id" that is not the ordinal key.

Is there a way to have this feature on EF 7.0.8?

**Comment by thomas-darling** [comment]
According to the [Npgsql release notes](https://www.npgsql.org/efcore/release-notes/8.0.html), they've deprecated their support for `.HasColumnType("jsonb")`, which worked perfectly, in favor of `.ToJson()` - which won't work for us until this is fixed, as we just got blocked by https://github.com/dotnet/efcore/issues/32360.

Please prioritize fixing this - it's been open for more than a year already...

**Comment by markushaslinger** [comment]
I ran into this today as well and it took me quite some time to figure it out (found this issue only after having identified the root cause). If this can't be fixed soon I'd suggest adding a warning to the documentation at least.

**Comment by btecu** [comment]
Just ran into this issue and spent a couple of hours until I got to this ticket.
A warning would be useful but even better fixing the issue.

**Comment by oleg-varlamov** [comment]
I also encountered this problem today. Microsoft writes everywhere about good JSON support in the EF, but in fact we have many problems that prevent the use of JSON in real applications. I'm waiting for a solution from the EFCore team.

**Comment by VaclavElias** [comment]
I have just run into the same issue.

**Comment by roji** [comment]
Everyone, please upvote this issue (👍) rather than posting "me too" comments. This is how we gauge user demand when prioritizing.

**Comment by VaclavElias** [comment]
I just 👍your comment, but also the issue itself. Thanks for great work @roji here and also in Community Standups.

**Comment by linchenrr** [comment]
This issue wasted my whole day and finally found the reason here

**Comment by ajcvickers** [comment]
Note from team triage: really fixing this in 8.0 is not feasible. However, we can throw a better exception message with directions to the workarounds.

**Comment by sclarke81** [comment]
> Note from triage: we should investigate if this is a materialization bug separate from #28594.
> 
> Possible workaround if the entity doesn't need the property to be called `Id` but `Id` is required in the JSON:
> 
> ```cs
> modelBuilder.Entity<Customer>()
>     .OwnsOne(customer => customer.Contact, b =>
>     {
>         b.ToJson();
>         b.OwnsMany(e => e.PhoneNumbers, b =>
>         {
>             b.Property(e => e.Key).HasJsonPropertyName("Id");
>         });
>     });
> ```

If you do need/want the property to be called Id as well, the following worked for me. It feels messy, but I haven't found a better way.

```cs
modelBuilder.Entity<Customer>()
    .OwnsOne(customer => customer.Contact, b =>
    {
        b.ToJson();
        b.OwnsMany(e => e.PhoneNumbers, b =>
        {
            b.Property<string>("_identifier");
        });
    });
```

```cs
public class PhoneNumber
{
    [JsonPropertyName("id")]
    [JsonInclude]
    private string _identifier;

    [NotMapped]
    [JsonIgnore]
    public string Id
    {
        get => _identifier;
        set => _identifier = value;
    }
}
```

**Comment by Xen0byte** [comment]
> @sclarke81 ...

Thank you so much for this! It's a little messy but I'd rather use it and have consistent property names across my entities.

**Comment by alecgorge** [comment]
Thanks @sclarke81 for the example! I ended up using a slight variation (removing `[JsonIgnore]`) to get parsing from a JSON API response to work as well:

```csharp
public class Tag
{
    [JsonPropertyName("Id")]
    [JsonInclude]
    private int _identifier;

    [NotMapped]
    public int Id
    {
        get => _identifier;
        init => _identifier = value;
    }
    
    public required string Name { get; init; }
}
```

**Comment by WhiteScorpion** [comment]
Are there any new developments?☺️

**Comment by joseangelyanez** [comment]
Any updates?

**Comment by roji** [comment]
@ajcvickers didn't this go into rc2 as opposed to rc1 (the milestone)?

**Comment by andreyerick** [comment]
Thx for the example @sclarke81. For anyone else still having trouble: the workaround doesn't seem to work if you're using No-Tracking queries, it throws an exception "shadow properties cannot be preserved when attempting to SaveChanges".

**Comment by GaetanVigner** [comment]
Hello, thx for the fix, when can we expect to see a RC2 Nuget ?

**Comment by roji** [comment]
@GaetanVigner in around a month,
