### ISSUE TITLE
Migrations messing up my schema.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#29389]
When you have migrations either from code or script and something goes wrong there is no way to continue from the point where an error occurred. (E.g. transport level errors). The migration then is only partially done and migrations are not transactional so we cannot rollback a migration on database level. Even worse the migration script just continues and records a successful migration in the history.

This can lead to schema's that are not inline with the snapshot and through time this accumulates until an application just breaks.

Personally I think the MigrationsHistory should contain a more fine grained history of each step in the migration script such that in case of error we can fix and retry from that point on. Also the script should not continue when an error occurs. Currently it just runs until the end and keeps trying updating the schema.

**Comment by roji** [comment]
@qsdfplkj see #22616, #22613 and #7681; we do have plans in this area, but more around ensuring transactionality.

**Comment by qsdfplkj** [comment]
Ok good to hear. Btw, sometimes it is just a command timeout and it breaks. 

I did read a bit on the reference issues and adding transactions but is that workable in huge tables with lots of migrations that take long time up to an hour. Or longer. It's almost sounds as a backup restore feature. 

I think I could even adjust the migration scripts manually by adding a step number and break on any errors. It would at least have helped me on the issues I had. (Like index already exists) but then I would continue from the next step or mark it as done in the history.

**Comment by roji** [comment]
> I think I could even adjust the migration scripts manually by adding a step number and break on any errors.

You could do that now, though in the future that's something the migrations system should ideally be doing for you (that's what those issues up there are about). For long operations there's always the possibility of adjusting the command timeout, or disabling it completely.

**Comment by michaelakin** [comment]
Mine too.  please put this in a transaction
