### ISSUE TITLE
multiple interceptor and ordering of execution

### ISSUE THREAD

**Issue by gabriel-systems** [dotnet/efcore#29392]
this there any reliable way to provide an ordering of interceptor within the dependency injection systems and their execution from efcore?

**Comment by ajcvickers** [comment]
@gabriel-systems Interceptors are executed in the order that they are provided from D.I., followed by any interceptors in the order they are provided to `AddInterceptors`. If the D.I. system doesn't guarantee the order of the registered `IInterceptor` services, then the order is also not guaranteed in EF Core.
