### ISSUE TITLE
EF core change the datetime property of a object when saving

### ISSUE THREAD

**Issue by masterchess33** [dotnet/efcore#29399]
## Datetime format change when saving a entity to the database

Hi, I'm working in an API in asp.net core 6, and I have encounter a problem when saving the data to the database. When I save the entity the datetime get an extra (E.g. +13:00) but when I check the database with another endpoint it show it without it. I'm not sure if this is a bug but I will add some screenshots. I did not find any similar problem on google so that's why I'm here.

To reproduce this error you just need to setup a new asp.net core api with MySQL. I also tried with a new project to check if the project I'm working on is the problem but no, the problem persist.

Here are the screenshots of the project.
<img width="320" alt="bug 1" src="https://user-images.githubusercontent.com/48487897/196813957-3154da77-e600-41f2-8986-6810ac98201e.png">
<img width="250" alt="bug 2" src="https://user-images.githubusercontent.com/48487897/196813985-d39f4c5b-4441-4a52-b99c-1d21c02946ec.png">
And here are the screenshots of the test project I made to test if was my project.
<img width="251" alt="bug3" src="https://user-images.githubusercontent.com/48487897/196820649-b4a21566-4afe-4d88-ab0c-318f6d92e409.png">
<img width="207" alt="bug4" src="https://user-images.githubusercontent.com/48487897/196820661-861ebf3a-3e3b-4c69-97f7-5c84d5ee80aa.png">

Also some code from the test project:

the controller:
```C#
[ApiController]
[Route("[controller]")]
public class TestController : ControllerBase
{
    private readonly ApplicationDbContext _db;

    public TestController(ApplicationDbContext db)
    {
        _db = db;
    }

    [HttpGet("get")]
    public List<Test> Get()
    {
        var data = _db.Tests.ToList();
        return data;
    }

    [HttpPost]
    public Test Create()
    {
        var test = new Test
        {
            DateTime = DateTime.Now
        };
        _db.Tests.Add(test);
        _db.SaveChanges();
        return test;
    }
}

```
The test entity:
```C#
public class Test
{
    [Key]
    public int IdTest { get; set; }
    public DateTime DateTime { get; set; }
}
```
And the db context:
```C#
public class ApplicationDbContext :DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {

    }

    public DbSet<Test> Tests { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseLazyLoadingProxies();
    }

}
```

The thing is that when I call the database in the same post method the datetime property of the entity I just create it get showed with the +13:00. The problem persist in Docker container in a Linux server (ubuntu). I don't know if it's important but I'm using a docker container for the database. I know this is somethings related with the time zones but I'm don't know how to solve it. The last things to add is that the project is in in a server (first two screenshots) with a different time zone than my computer and the test project I did it in my computer (third and fourth).

### Include provider and version information

EF Core version: 6.0.10
Database provider: Pomelo.EntityFrameworkCore.MySql 6.0.2
Target framework: NET 6.0
Operating system: Windows 10
IDE: Rider 2022.2.3

**Comment by roji** [comment]
This issue looks like it belongs in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql, since it's about MySQL-specific handling of timestamps and time zones.

**Comment by masterchess33** [comment]
I did a test with sql server and it give me the same result, I also did it with posgresql and then it change the behavior, so it seems you're right.
