### ISSUE TITLE
All built-in conventions must be build from publicly available content!

### ISSUE THREAD

**Issue by kabua** [dotnet/efcore#2940]
If one of the core ideas behind EF's code first, is the ability to build the database/model through the use of conventions then ALL the built-in conventions MUST be built using ONLY publicly available classes, properties, extension methods, etc. In other words, an external developer must be able to duplicate all the functionality of all the built-in conventions without being impeded.

The is a real problem in EF6 right now. There are several conventions we are trying to create but are block because the classes, properties or extension methods we need are marked as internal. For conventions to be truly useful then these internals must be made public otherwise the idea that Conventions is a extensibility point is just a facade.

**Comment by Grinderofl** [comment]
This seems to be also mentioned in #2589, but this. One should be easily able to recreate (not just override) any convention through public API. While we have ways of quickly creating model with default conventions, we lack ways of truly customizing it.

**Comment by rowanmiller** [comment]
The good news is that in EF7 everything is public. We put some classes in a `.Internal` namespace to identify them as APIs that may change between releases, but they are there for you to use without needing to use reflection.
