### ISSUE TITLE
Select{Count(field)} translation error

### ISSUE THREAD

**Issue by Cricle** [dotnet/efcore#29408]
### Include your code

DebugView.Expression
```C#
DbSet<<>f__AnonymousType0<string, DateTime, bool, decimal?, decimal?, DateTime?>>()
    .AsNoTracking()
    .GroupBy( => new <>f__AnonymousType1<decimal?>{ a11 = .a11 }
    )
    .Select( => new <>f__AnonymousType5<int, DateTime, decimal?>{ 
        Rfcc58ba2e977446ab7f0e309a8e4e0f4 = 
            .Select( => .a2)
            .Count(), 
        R5dbd4794917f4856bb94bd0eebac926f = 
            .Max( => ._timestamp), 
        R94e9333533d749d584a6a7568eb7eb1c = .Key.a11 
    }
    )
```

DebugView.Query
```sql
SELECT COUNT(*) AS `Rfcc58ba2e977446ab7f0e309a8e4e0f4`, MAX(`f`.`_timestamp`) AS `R5dbd4794917f4856bb94bd0eebac926f`, `f`.`a11` AS `R94e9333533d749d584a6a7568eb7eb1c`
FROM `f78ad4f8-bd27-4323-9d74-125bf5da37af` AS `f`
GROUP BY `f`.`a11`
```

But in 

```C#
Rfcc58ba2e977446ab7f0e309a8e4e0f4 = 
            .Select( => .a2)
            .Count(), 
```

The correct one is not that it should be generated

```sql
COUNT(a2) AS `Rfcc58ba2e977446ab7f0e309a8e4e0f4`
```

This affects whether the field is empty, in many database null row count will be ignore.

### Include stack traces

No

### Include verbose output

No

### Include provider and version information

EF Core version:
Database provider: (Pomelo.EntityFrameworkCore.MySql 6.0.1)
Target framework: (.NET 6.0)
Operating system:
IDE: (Visual Studio 2022 17.3.3)

**Comment by roji** [comment]
@Cricle first, I'm not seeing a behavior different between the translation of Count() with or without GroupBy; using the SQL Server or PostgreSQL providers, both translations use COUNT(*). I've attached a full, minimal code sample below; if you're seeing another behavior e.g. with the SQL Server provider, please post a similar code sample which shows the issue. If you're seeing problematic behavior specifically with the Pomelo MySQL provider, you should report the problem on that provider's repo (we don't maintain it).

> The correct one is not that it should be generated

Are you saying that for the following LINQ query:

```c#
var count = ctx.Blogs
    .Select(b => b.Name)
    .Count();
```

EF should be translating using `COUNT(Name)` instead of the current translation, using `COUNT(*)`? That doesn't seem right: COUNT(*) counts the number of rows - including where the column value is null - whereas `COUNT(Name)` counts the number of rows where Name is non-null. The LINQ to Objects behavior - to which EF generally aligns - is the former, not the latter.

<details>
<summary>Code sample</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var count1 = ctx.Blogs
    .GroupBy(b => b.Id)
    .Select(g => new
    {
        Count = g.Select(b => b.Name).Count()
    })
    .ToList();

var count2 = ctx.Blogs
    .Select(b => b.Name)
    .Count();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}

**Comment by Cricle** [comment]
I'm sorry that the problem description was not very clear at the beginning, because it was generated from a large project using dynamic linq, so I wrote a mini example.

In mini sample I use `MySQL`, `MSSQL`, `SQLite` provider in `group and select (Count{field}) `

Database providers used(I already use [nuget.org](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/) latest stable version)
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.10" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.10" />
  <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" />
</ItemGroup>
```

The model I defined

```csharp
public class User
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string Name { get; set; }

    public long? Score { get; set; }
}
```

The query code is 

```csharp
var sql = dbc.Users.GroupBy(x => x.Name).Select(x => new
{
    Score = x.Select(y => y.Score).Count()
}).ToQueryString();
```

I want to generic like(MSSQL)
```sql
SELECT COUNT([Score]) AS [Score] -- Count(field)
FROM [Users] AS [u]
GROUP BY [u].[Name]
```

Result I got was

```text
MSSQL:
SELECT COUNT(*) AS [Score]
FROM [Users] AS [u]
GROUP BY [u].[Name]

Mysql:
SELECT COUNT(*) AS `Score`
FROM `Users` AS `u`
GROUP BY `u`.`Name`

Sqlite:
SELECT COUNT(*) AS "Score"
FROM "Users" AS "u"
GROUP BY "u"."Name"
```

My code is here(The compressed package and the project name are randomly named by me)

[rsa1.zip](https://github.com/dotnet/efcore/files/9897326/rsa1.zip)

Thanks.

**Comment by roji** [comment]
@Cricle what is your intention with the query above:

1. To get the count of users that share the same name, or
2. To get the count of users **with non-null scores** that share the same name?

The LINQ query you posted above expresses option 1: there is nothing filtering out null scores; the SQL EF generates does exactly this via `COUNT(*)`, so EF is behaving correctly here.

If you want to filter out users with a null score (option 2), you need to specify that in your LINQ query:

```c#
var sql = ctx.Users
    .Where(u => u.Score != null)
    .GroupBy(x => x.Name)
    .Select(x => x.Count())
    .ToQueryString();
```

This generates the following SQL:

```sql
SELECT COUNT(*)
FROM [Users] AS [u]
WHERE [u].[Score] IS NOT NULL
GROUP BY [u].[Name]
```

**Comment by Cricle** [comment]
I need to generate option 2. 

(To illustrate the scenario, I added Age(int?) property in model)

In fact, I aggregate more than one field, like below sql(Count the number and average age of users with scores of the same name)

```sql
SELECT COUNT([Score]) AS [Score], Avg([Age]) AS [AvgAge]
FROM [Users] AS [u]
GROUP BY [u].[Name]
```

In Linq I wrote
```csharp
var sql2 = dbc.Users.GroupBy(x=>x.Name).Select(x => new
{
    Score = dbc.Users.Select(y => y.Score).Count(),
    AvgAge = dbc.Users.Average(q => q.Age)
}).ToQueryString();
Console.WriteLine(sql2);
```

Result is 

```sql
SELECT (
    SELECT COUNT(*)
    FROM [Users] AS [u0]) AS [Score], (
    SELECT AVG(CAST([u1].[Age] AS float))
    FROM [Users] AS [u1]) AS [AvgAge]
FROM [Users] AS [u]
GROUP BY [u].[Name]
```

The generated sql, what's different from what I expected is `COUNT(*)`, not `COUNT([Score])`.

When I change to

```csharp
var sql2 = dbc.Users.GroupBy(x=>x.Name).Select(x => new
{
    Score = dbc.Users.Where(y => y.Score!=null).Count(), //Changed Select()->Count() to Where()->Count()
    AvgAge = dbc.Users.Average(q => q.Age)
}).ToQueryString();
Console.WriteLine("a==>" + sql2);
```

The sql will be

```sql
SELECT (
    SELECT COUNT(*)
    FROM [Users] AS [u0]
    WHERE [u0].[Score] IS NOT NULL) AS [Score], (
    SELECT AVG(CAST([u1].[Age] AS float))
    FROM [Users] AS [u1]) AS [AvgAge]
FROM [Users] AS [u]
GROUP BY [u].[Name]
```

This is what I want.

But when I use this method to select data(`Select()->Count()`), shouldn't it be `Count({field})`?

Thanks.

**Comment by roji** [comment]
> But when I use this method to select data(Select()->Count()), shouldn't it be Count({field})?

Let's forget EF and SQL for a moment, and look at this pure LINQ to Objects code sample which uses `Select().Count()`:

```c#
var users = new List<User>
{
    new User { Name = "User1", Score = 8.1 },
    new User { Name = "User1", Score = null },
    new User { Name = "User2", Score = 9 }
};

var groups = users
    .GroupBy(u => u.Name)
    .Select(g =>
        new
        {
            Name = g.Key,
            ScoreCount = g.Select(u => u.Score).Count()
        })
    .ToList();

foreach (var group in groups)
{
    Console.WriteLine($"Name: {group.Name}, ScoreCount: {group.ScoreCount}");
}
```

This prints the following results:

```
Name: User1, ScoreCount: 2
Name: User2, ScoreCount: 1
```

In other word, the behavior of LINQ here is to **not** filter out the null values; the LINQ Count operator doesn't automatically do that for you - after all, you may be interested in including the nulls in your count. If you want to filter out the nulls, you must explicitly add a `Where(s => s != null)` to do that.

Back to EF... EF generally tries to translate LINQ operators to SQL so that the SQL behaves in the same way as the LINQ query would if you executed it as LINQ to Objects (as above). That's why EF translates the LINQ Count() operator to `COUNT(*)` (which doesn't filter out nulls), and not to `COUNT([Score])` (which does).

I hope that clarifies things.

**Comment by Cricle** [comment]
I got it!
Thank you very much.
