### ISSUE TITLE
ManyServiceProvidersCreatedWarning

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/efcore#29412]
Hi,

I get this error. example of the project
https://github.com/maikebing/EntityFrameworkCore.LiteDB 

System.InvalidOperationException: 'An error was generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.ManyServiceProvidersCreatedWarning': More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling 'UseLoggerFactory' passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. This may lead to performance issues, consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built. This exception can be suppressed or logged by passing event ID 'CoreEventId.ManyServiceProvidersCreatedWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'

```

public static IServiceCollection AddEntityFrameworkLiteDBDatabase([NotNull] this IServiceCollection serviceCollection)
        {
            Check.NotNull(serviceCollection, nameof(serviceCollection));

            var builder = new EntityFrameworkServicesBuilder(serviceCollection)
               .TryAdd<LoggingDefinitions, LiteDBLoggingDefinitions>()
               .TryAdd<IDatabaseProvider, DatabaseProvider<LiteDBOptionsExtension>>()
                .TryAdd<IValueGeneratorSelector, LiteDBValueGeneratorSelector>()
                .TryAdd<IDatabase>(p => p.GetService<ILiteDBDatabase>())
                .TryAdd<IDbContextTransactionManager, LiteDBTransactionManager>()
                .TryAdd<IDatabaseCreator, LiteDBDatabaseCreator>()
                .TryAdd<IQueryContextFactory, LiteDBQueryContextFactory>()
                .TryAdd<IQueryableMethodTranslatingExpressionVisitorFactory, LiteDBQueryableMethodTranslatingExpressionVisitorFactory>()
                .TryAdd<IEvaluatableExpressionFilter, EvaluatableExpressionFilter>()
                 .TryAdd<IConventionSetBuilder, LiteDBConventionSetBuilder>()
                .TryAdd<ISingletonOptions, ILiteDBSingletonOptions>(p => p.GetService<ILiteDBSingletonOptions>())
                .TryAdd<ITypeMappingSource, LiteDBTypeMappingSource>()

                .TryAddProviderSpecificServices(
                    b => b
                        .TryAddSingleton<LiteDBLoggingDefinitions, LiteDBLoggingDefinitions>()
                        .TryAddSingleton<ILiteDBSingletonOptions, LiteDBSingletonOptions>()
                        .TryAddSingleton<ILiteDBStoreCache, LiteDBStoreCache>()
                        .TryAddSingleton<ILiteDBTableFactory, LiteDBTableFactory>()
                        .TryAddSingleton<IRelationalSqlTranslatingExpressionVisitorFactory, LiteDBSqlTranslatingExpressionVisitorFactory>()
                        .TryAddScoped<ILiteDBDatabase, LiteDBDatabase>());
               // .TryAddScoped<ILiteDBMaterializerFactory, LiteDBMaterializerFactory>());

            builder.TryAddCoreServices();
       
            return serviceCollection;
        }


```

**Comment by ajcvickers** [comment]
@suatsuphi Likely causes of this are that `ShouldUseSameServiceProvider` is always indicating that a new service provider is needed, one of the `ISingletonOption` is changing every time the service provider is built. or something else is causing the service provider caching to generate a cache miss every time.
