### ISSUE TITLE
Projects targeting .NET Framework 4.6.1

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#29415]
I've run the [build script](https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md#build) but some projects fail to build with the error message:

`The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`

The given page lists 4.6.1 in the "Out of support version" section.

Questions:
1. Is it correct that EF Core still targets this version?
2. If so, should the build script install it?

Thanks

**Comment by ajcvickers** [comment]
@stevendarby Current main requires .NET 6 to run, and is using .NET 7 RC2 to build. We still cross-target a few things, but I'm not aware of needing these dependencies. Can you post the full output?

**Comment by stevendarby** [comment]
@ajcvickers The [ef project](https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/src/ef/ef.csproj#L4) is the only one in the the `EFCore.slnf` solution filter which targets `net461`. When building all, there were a few other Sqlite test projects targeting it too.

It's not a huge obstacle at the moment, as I don't think I need those projects, but for example I can't simply run all tests as it fails to build all. I'd be happy to install that SDK if needed but thought it was worth checking if that was right or if the helper script could be improved.

![image](https://user-images.githubusercontent.com/41150696/197611981-4facc0da-3548-43aa-aec0-1380a07fb8c5.png)

**Comment by ajcvickers** [comment]
@stevendarby Are you running `.\build.cmd` from the command prompt first? Do you have .NET 7 RC2 installed?

**Comment by stevendarby** [comment]
> @stevendarby Are you running `.\build.cmd` from the command prompt first?

Yes, sorry I wasn't clear but that's the script I was referring to in the opening post and question 2.

> Do you have .NET 7 RC2 installed?

Yes. But I don't have .NET Framework 4.6.1 installed, which is the problem here.

**Comment by stevendarby** [comment]
Ok, I think my mistake was trying to use VS to run the tests, which then tries to build it, which doesn't work. The guide says to use the test command, so I'll use that instead!
https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md#run-tests
