### ISSUE TITLE
Throw more specific exceptions from ShapedQueryCompilingExpressionVisitor

### ISSUE THREAD

**Issue by kjkrum** [dotnet/efcore#29446]
An `InvalidOperationException` thrown by an EF extension method like `SingleAsync` often maps to an error like HTTP 404. However, it is indistinguishable higher in the call stack from other errors that could generate `InvalidOperationException`. Error handling could be simplified if <a href="https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs">`ShapedQueryCompilingExpressionVisitor`</a> threw more specific subtypes of  `InvalidOperationException`.

**Comment by roji** [comment]
Note that LINQ to Objects Single also throws InvalidOperationException ([docs](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=net-7.0#system-linq-enumerable-single-1(system-collections-generic-ienumerable((-0))))), so EF's behavior is aligned to that. If you need better error differentiation for HTTP, you'll have to use more specific LINQ operations e.g. to check how many times an item occurs in the list.

**Comment by kjkrum** [comment]
Hence why I suggested throwing a *subtype* of `InvalidOperationException`. This is the standard way to convey more information when the exception type is constrained by an interface or convention.

**Comment by ajcvickers** [comment]
@kjkrum Getting an `InvalidOperationException` should be interpreted as, "there is an error in the code somewhere." In other words, the code has asserted by using `Single` that there is only one object returned from the query. But that assertion turned out to be false. Given this, it's not clear to me how changing the exception type would make debugging this any easier.

**Comment by roji** [comment]
> Hence why I suggested throwing a subtype of InvalidOperationException. This is the standard way to convey more information when the exception type is constrained by an interface or convention.

As I wrote, EF simply aligns with the regular LINQ to Objects behavior here, and your argument doesn't seem specific to EF's version of Single/SingleAsync than it does to the standard .NET Enumerable.Single; after all, you could claim that some instance of Enumerable.Single somewhere throwing InvalidOperationException is just as ambiguous when catching it higher up the stack. If that's accepted at the LINQ level and implemented, I think we'd align with that in EF.

**Comment by kjkrum** [comment]
It would still be aligned after this change. A subtype of `InvalidOperationException` is-a `InvalidOperationException` in every meaningful sense. Another project not taking an opportunity to improve is not a reason not to improve this one.

**Comment by ajcvickers** [comment]
@kjkrum 

> However, it is indistinguishable higher in the call stack

I guess the fundamental question here is why do you need to distinguish it in any way other than through reading the exception message as part of debugging the error in the application?

**Comment by kjkrum** [comment]
Because EF Core is commonly used to create web applications where zero elements matching a predicate is a user-facing error case, but finding multiple elements would imply a developer-facing programming error. They are semantically different errors that should be handled differently.

Exception messages should include failure-capture information, but recoverable exceptions (i.e., those that would be checked exceptions in languages that have them) should also provide accessors for all the information in the exception message. Parsing exception messages is fragile and not recommended.

**Comment by ajcvickers** [comment]
@kjkrum The whole point is that catching this exception and using it to generate user-facing messages is a misuse of the exception. This exception means that the programmer has asserted by writing this code that there is one and only one possible result from the query, and anything else means there is a bug in the code.

**Comment by roji** [comment]
> Because EF Core is commonly used to create web applications where zero elements matching a predicate is a user-facing error case, but finding multiple elements would imply a developer-facing programming error. They are semantically different errors that should be handled differently.

Then SingleOrDefault should be used for that case instead of Single, and the application should check for null as the result. As @ajcvickers wrote, using Single here and trying to detect which error the exception corresponds to basically amounts to using exceptions for normal control flow, which is an anti-pattern. To properly distinguish between user-facing error scenarios, use LINQ operators which don't generate exceptions for those scenarios (i.e. SingleOrDefault)..

> It would still be aligned after this change. A subtype of InvalidOperationException is-a InvalidOperationException in every meaningful sense. Another project not taking an opportunity to improve is not a reason not to improve this one.

If we did that and the Enumerable version of Single() were to be modified in the future to throw a specialized exception, EF would be incompatible with that (and aligning would be a breaking change).

**Comment by kjkrum** [comment]
Fair enough. Suggestion withdrawn.
