### ISSUE TITLE
Should I dispose transaction?

### ISSUE THREAD

**Issue by verdysh** [dotnet/efcore#29443]
EF transaction is IDisposable:

`IDisposable transaction = await context.Database.BeginTransactionAsync(IsolationLevel.ReadCommitted);`

Within Dispose() method it calls Rollback() method.

What will happen if I don't call Dispose() method? I think in this case transaction lives a little longer than should, but I'm not sure if it's a reason or if it's the only reason.

If my assumption above is wrong, why/in what cases should I call Dispose() method for transaction?

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6

**Comment by ajcvickers** [comment]
@verdysh Always dispose the transaction. If you want to commit the transaction, then call `CommitAsync` before disposing.

**Comment by verdysh** [comment]
After you said that I have no doubts I have to do so, but it's still interesting why? What interesting happens there and what happen if I don't do that?

**Comment by ajcvickers** [comment]
@verdysh It's undefined. Maybe nothing bad. Maybe something bad. Maybe nothing bad now, but something bad later.

**Comment by verdysh** [comment]
Got it. Thanks for the answer!
