### ISSUE TITLE
The naming convention of custom foreign keys and shadow attributes conflicts. Types that can be null cannot be null during migration

### ISSUE THREAD

**Issue by zhuangState** [dotnet/efcore#29452]
[EFModel.zip](https://github.com/dotnet/efcore/files/9893641/EFModel.zip)

EF Core version 6.0.9
 Migration result: AccountID = table.Column(type: "int", nullable: false)
![image](https://user-images.githubusercontent.com/98197028/198831727-354c11e3-904a-407b-b448-63080e3b56a5.png)

**Comment by zhuangState** [comment]
I'm not sure if this is a feature
Because the following writing methods can get correct results


`    public class RegisterSerial
    {
        public int ID { get; set; }

        [ForeignKey("AccountID")]
        public Account? Account { get; set; }
        public int? AccountID { get; set; }
    }`

`    public class RegisterSerial
    {
        public int ID { get; set; }

        [ForeignKey("AccountID2")]
        public Account Account { get; set; }
        public int? AccountID2 { get; set; }
    }`
` public class RegisterSerial
    {
        public int ID { get; set; }
        public Account Account { get; set; }
        public int? AccountID { get; set; }
    }`

**Comment by ajcvickers** [comment]
Related to #27859 and #27925.

**Comment by ajcvickers** [comment]
Note from triage: when the foreign key property and navigation nullability conflict, then, in addition to warning (#27925), the foreign key nullability should take preference.
