### ISSUE TITLE
Data Annotations not overriding configurationBuilder properties

### ISSUE THREAD

**Issue by Eaglef90** [dotnet/efcore#29453]
In my `DbContext`, I am setting all strings to `varchar(250)`, but I have some strings marked as `varchar(max)"`. After creating my migrations, I see the tables marked as max are still being created with a max length of 250. 

How can I have my data annotations override the config builder command?

Config builder:
```

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.Properties<string>()
                            .HaveColumnType("varchar(250)")
                            .AreUnicode(false);
    }
```

Entity:

```
        [Column(TypeName = "varchar(max)")]
        public string? AffectedColumns { get; set; }
```

What is generated in the migration:

`    AffectedColumns = table.Column<string>(type: "varchar(250)", unicode: false, nullable: true)`

How are we supposed to set the default value/length of strings but then over ride it for specific columns later on?

I am using SQL Azure as my target DB using .Net Core and EF Core 7. RC.2.22472.11 in VS  17.4.0 Preview 5.0

**Comment by roji** [comment]
Duplicate of #28655

**Comment by roji** [comment]
You can use the Fluent API to override pre-convention configuration, but not Data Annotations.


Note that this is called out in the [docs](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#pre-convention-configuration):

> Data annotations do not override pre-convention configuration.

**Comment by Eaglef90** [comment]
Sorry I did not see 28655. I was doing a lot of googling but never ran across that doc. So if I am understanding this write if I want string to not default to nvarchar(max). I must doe the per-convention config and then over ride hat via fluent APi in modelBuilder, thus splitting up my calls between in class annotations and DBContext API calls?

Is it possible to have annotations override API in configurationBuilder but not modelBuilder?

**Comment by roji** [comment]
No, the way that pre-convention configuration is architected, that is not possible (this is what #28655 details).

**Comment by Eaglef90** [comment]
That is what I figured but thought I would ask anyways. Yhanks for the help.
