### ISSUE TITLE
Change in behaviour of CSharpHelper.Identifier(string name)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29450]
Not sure if this can be considered a bug, but here you have it:

Given:

    code.Identifier("MyStrange_ParameterName")

This returns:

     MyStrange_ParameterName

using EF Core 6

But

     MyStrangeParameterName

using EF Core 7

**Comment by ajcvickers** [comment]
@ErikEJ Do you know what scenarios this breaks?

**Comment by ErikEJ** [comment]
Well- the behaviour change exposed a bug in my stored procedure mapping code. Could imagine it would effect some reverse engineering scenarios.

**Comment by ErikEJ** [comment]
Looks like the first issue is in now: https://github.com/ErikEJ/EFCorePowerTools/issues/1577

**Comment by ErikEJ** [comment]
Related commit https://github.com/dotnet/efcore/commit/41bd78813bc7aaa4b118f9fc24ada1262c7bc850#diff-d464e59a794ae7fd54b1770c49a469cbf1fe00850256d8660bd0fc833cc70a6e

**Comment by ajcvickers** [comment]
@bricelam Looks like we should probably patch this.
