### ISSUE TITLE
why there is no SqliteDateDiffFunctionsTranslator 

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/efcore#29471]
Hi,

I'm trying to add sqlite to the project. why there is no SqliteDateDiffFunctionsTranslator?

```
        private IMethodCallTranslator FindMethodCallTranslator(MethodInfo sourceMethod)
        {
            var translators = _translatorsField.GetValue(this) as List<IMethodCallTranslator>;
            if (translators != null)
            {
                if (sourceMethod.Name.StartsWith("DateDiff"))
                {
                    return translators.FirstOrDefault(x => x is **SqlServerDateDiffFunctionsTranslator**);
                    //MySqlDateDiffFunctionsTranslator
                }
            }

            return null;
        }

```

[efcore](https://github.com/dotnet/efcore)/[src](https://github.com/dotnet/efcore/tree/main/src)/[EFCore.Sqlite.Core](https://github.com/dotnet/efcore/tree/main/src/EFCore.Sqlite.Core)/[Query](https://github.com/dotnet/efcore/tree/main/src/EFCore.Sqlite.Core/Query)/Internal/

**Comment by ajcvickers** [comment]
@suatsuphi Because DateDiff is a SQL Server function.

**Comment by suatsuphi** [comment]
> @suatsuphi Because DateDiff is a SQL Server function.

Is it adaptable? Or why not adapt?

**Comment by ajcvickers** [comment]
@suatsuphi I'm not sure what that means. Please provide more details on what you mean by "adapt."

**Comment by suatsuphi** [comment]
https://github.com/smartstore/Smartstore/tree/main/src/Smartstore.Data

I tried to add SQLite to this project. there are some limitations on SQLite. I get some error about those limitations.  one o them that translator error.  No file database support on entityframework (Iike SQLite). You cannot use it because of such errors.

You said this is a SQL Server function. But there is a same function on MySQL > MySqlDateDiffFunctionsTranslator

I guess everything is commercial. :)) I think it is desired that sqlite has constraints on the entityframework.

**Comment by ajcvickers** [comment]
@suatsuphi I'm still really not sure what you mean. However, of you are suggesting that EF should somehow provide behaviors in SQLite that are not supported by SQLite, then this is outside the scope of EF. EF explicitly does not attempt to abstract away the underlying database or make things work the same across all databases.
