### ISSUE TITLE
Decimal variable precision is not properly converted to SQL

### ISSUE THREAD

**Issue by zipa** [dotnet/efcore#29482]
When I use a decimal variable in the query, EF Core converts it to decimal(18,2). The consequence is an erroneous calculation if the variable has more than two decimal places.

For example:
```
decimal c = 0.102m;
var tmp = context
    .Payrolls
    .Where(x => x.HealthContributionAmount > 0)
    .Select(x => new
    {
        value = x.HealthContributionAmount,
        calc = x.HealthContributionAmount * c
    }
    );
string sql = tmp.ToQueryString();
var result = await tmp.FirstAsync();
```
For this example, if the _value_ is 117.38, the _calc_ value calculates as 11.738, which is wrong. The correct calculation should be 11.97276.
The _value_ was multiplied by 0.1 instead of 0.102.

I found out that the variable _c_ was not properly translated to SQL, as it was declared as decimal(18,2), even though it has more decimal places:
```
DECLARE @__c_0 decimal(18,2)(18) = 0.102;

SELECT [p].[HealthContributionAmount] AS [value], [p].[HealthContributionAmount] * @__c_0 AS [calc]
FROM [fi].[Payroll] AS [p]
WHERE ([p].[IsDeleted] = CAST(0 AS bit)) AND ([p].[HealthContributionAmount] > 0.0)
```

If I write the value of _c_ as a constant within the query, then the calculation is correct, as there is no declaration of the decimal variable in the query. This is not the solution, as in the actual code the value of _c_ is a parameter.

Is there any possibility to specify the precision of generated decimal variables?

---
EF Core version: 6.0.10
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 6.0
Operating system: Windows 10 Pro 22H2 (19045.2193)
IDE: Visual Studio 2022 17.3.6)

**Comment by zipa** [comment]
I found the solution in one of the closed issues (https://github.com/dotnet/efcore/issues/29313)

**Comment by roji** [comment]
Duplicate of #29313
