### ISSUE TITLE
UseInMemoryDatabase with PostgreSQL NpgsqlTsVector throws exception

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#29485]
## File a bug
I configure full-text search according to https://www.npgsql.org/efcore/mapping/full-text-search.html?tabs=pg12%2Cv5 and bump into the following exception when running integration tests using in-memory DB:

```
{"The property 'Product.SearchVector' is of type 'NpgsqlTsVector' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'."}
```

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version: 6.0.10
Database provider: PostgreSQL but UseInMemoryDatabase for integration tests which throws the exception
Target framework: .NET 6.0
Operating system: Windows 11 and Ubuntu 22.10
IDE: Visual Studio 17.3.6

**Comment by roji** [comment]
You can't use full-text search capabilities - or any PostgreSQL-specific API - with the InMemory database. We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/).
