### ISSUE TITLE
type RuntimeEntityType throws InvalidOperationException during IsTableExcludedFromMigrations

### ISSUE THREAD

**Issue by JinnFletch** [dotnet/efcore#29490]
https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs#L1480

https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/src/EFCore.Relational/Metadata/Internal/Table.cs#L214

I'm hoping to get some clarification either on why this was decided to throw an exception, or what is causing my Fluent API Mappings to register my types as a `RuntimeEntityType`.  I am trying to check `IEntityType.IsTableExcludedFromMigrations()`.  The below code reproduces this issue and, as far as I can tell, essentially renders `IsTableExcludedFromMigrations` unusable.

``` CSharp
    public class BasicContext : DbContext
    {
        public BasicContext(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TestEntity>().ToTable(t => t.ExcludeFromMigrations());
        }

        public void DoSomething()
        {
            var skipThese = Model.GetRelationalModel().Tables
                        .SelectMany(x => x.EntityTypeMappings).Select(x => x.EntityType)
                        .Where(x => x.IsTableExcludedFromMigrations()) // <-- Issue here when evaluated
                        .ToList();
        }
    }
```

The issue could be in how I'm getting to `IsTableExcludedFromMigrations` through `Model.GetRelationalModel`.  If there's an alternative that draws out types that are not `RuntimeEntityType`s, that could work.

**Comment by AndriySvyryd** [comment]
`IsTableExcludedFromMigrations` is usually only needed to be checked by Migrations and related services, so it's removed from the model used at run-time.
You can get the full model by calling `((IInfrastructure<IServiceProvider>)context).GetService<IDesignTimeModel>().Model`. But this can take some time the first time it's called as it will build the model again.

**Comment by JinnFletch** [comment]
Thanks for the reply Andriy.  I do know you can get the model from IDesignTimeModel.  But I may just be missing how to call `IsTableExcludedFromMigration()` on it, or another question I have about checking `IMigrationsModelDiffer.GetDifferences`, which is currently failing because the table exclusion is called internally there.

**Comment by AndriySvyryd** [comment]
> But I may just be missing how to call IsTableExcludedFromMigration()

Should be the same:
```C#
                        ((IInfrastructure<IServiceProvider>)context).GetService<IDesignTimeModel>().Model.GetRelationalModel().Tables
                        .SelectMany(x => x.EntityTypeMappings).Select(x => x.EntityType)
                        .Where(x => x.IsTableExcludedFromMigrations())
                        .ToList();
```

> So you're saying that when "Migrations" are run, the models are treated differently than when an executable depending on Entity Framework runs. How do I stop that? I DO want to check this information during runtime.

Essentially - yes. This is currently not configurable. Why and how often do you need to get this information? If it's only occasionally, the above method should be ok. It really should only be noticeable perf-wise if you need it (almost) every time a context is created.

**Comment by JinnFletch** [comment]
Oh duh, get the RelationModel from the IModel, and my other code works fine now.  I am doing some double-checking at app startup, some logging about differences, and other low level stuff that nobody ever notices.  It simply broke when I updated the EF version and that Runtime model stuff was in there.  It's all working again now, thanks!
