### ISSUE TITLE
Error when mapping a common abstracted relationship table to more than one case

### ISSUE THREAD

**Issue by MikeStonoga** [dotnet/efcore#29498]
Hello,
I had stumbled in a specific case while designing my new system.

Well, I will try to explain this using the concept of responsible:

I can have responsibles for an activity, for a place, for a person, etc...

So, i want to map this relationship on a table called ResponsibleContext which will have three properties: ResponsibleId, ContextId and ContextType.

Then, I had made a mapping to the first case using the suggested syntax. 

> ## Implementation proposal
> ### Fluent API
> ```cs
> modelBuilder.Entity<Tag>()
>   .HasMany(e => e.Posts)
>   .WithMany(e => e.Tags)
>   .UsingEntity<PostTag>(
>     pt => pt
>       .HasOne()
>       .WithMany(e => e.PostTags),
>     pt => pt
>       .HasOne()
>       .WithMany(e => e.PostTags))
>   .ToTable("PostTags");

It worked well.
But, when i add another case mapping to the same ResponsibleContext i receive the following error:

The skip navigation 'Person.Responsibles' doesn't have an inverse navigation configured. Every skip navigation should have an inverse skip navigation.

It seems that when i made the first configuration EF has removed the ResponsibleContext table from being able to be mapped for another cases.

My real scenario was with PhoneContext with the following mappings on each IEntityTypeConfiguration

For a Place which have ISet Phone I Used:

```C#
builder.HasMany(e => (ISet<Telefone>)e.Telefones)
               .WithMany(e => (ISet<Local>)e.Contextos)
               .UsingEntity<TelefoneContexto>(j =>
                   j.HasOne<Telefone>()
                       .WithMany()
                       .HasForeignKey("TelefoneId"),
              j =>
                   j.HasOne<Local>()
                       .WithMany()
                       .HasForeignKey("ContextoId")
               )
               .ToTable("TelefoneContexto")
               .HasNoKey();
```
               
 For a Person which have ISetPhone I Used:
 
 ```C#
 builder.HasMany(e => (ISet<Telefone>)e.Telefones)
                .WithMany(e => (ISet<Pessoa>)e.Contextos)
                .UsingEntity<TelefoneContexto>(j =>
                    j.HasOne<Telefone>()
                        .WithMany()
                        .HasForeignKey("TelefoneId"),
               j =>
                    j.HasOne<Pessoa>()
                        .WithMany()
                        .HasForeignKey("ContextoId")
                )
                .ToTable("TelefoneContexto")
                .HasNoKey();
```
                

```C#
public class Telefone : FullAuditedEntity, ITelefone
{
    public string Numero { get; private set; }
    public string DDD { get; private set; }
    public string CodigoPais { get; private set; }

    [JsonIgnore]
    [IgnoreDataMember]
    public virtual ISet<object> Contextos { get; set; } = new HashSet<object>();

    protected Telefone() { }
    protected Telefone(string numero, string ddd, string codigoPais, Guid creatorId)
        : base(creatorId)
    {
        Numero = numero;
        DDD = ddd;
        CodigoPais = codigoPais;
    }

    public static ITelefone Cadastrar(ICadastrarTelefoneRequisito requisito)
        => new Telefone(requisito.Numero, requisito.DDD, requisito.CodigoPais, requisito.CommanderId);
}
```

The JsonIgnore and IgnoreDataMember are there only because swagger falls into self referency loop. and this is the way i found to avoid that. And, all of that works fine until i add a second case.

_Originally posted by @MikeStonoga in https://github.com/dotnet/efcore/issues/19003#issuecomment-1306518719_

**Comment by ajcvickers** [comment]
Note for triage: probably covered by #7623, but this looks like a complex case.
