### ISSUE TITLE
SQLite: RETURNING clause doesn't work with virtual tables

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#29512]
Our new usage of the RETURNING clause in 7.0.0 is incompatible with SQLite virtual tables. Note that the provider doesn't yet support creating virtual tables in migrations (but can still be used to update tables created externally/via raw SQL).

We can add metadata about virtual tables, which would trigger opting out of RETURNING. We can also add a general context option to opt out of it, which would be an escape hatch for any further incompatibility scenarios.

Note that we already automatically opt out of RETURNING for old versions of SQLite (#28911).

Thanks @JesperTreetop for reporting this in https://github.com/dotnet/efcore/pull/27663#issuecomment-1308023414.

**Comment by bricelam** [comment]
Virtual tables just have two pieces of information--the backing virtual table module, and a comma-separated list of zero or more arguments. The API could look something like this:

```cs
t.IsVirtualTable("csv", "filename='thefile.csv'");
t.IsVirtualTable("fts5", "Name", "Address", "Uuid ININDEXED", "tokenizer='porter ascii'");
```

**Comment by roji** [comment]
Providing a standalone opt-out from RETURNING is now tracked by #29916 - should we have a separate issue to track implementing virtual tables in Sqlite?
