### ISSUE TITLE
ValueGenerated and ValueGeneratedSensitive have property/entity type swapped in message

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#29517]
See https://github.com/dotnet/efcore/issues/29502#issuecomment-1308613511

**Comment by tmricardo7** [comment]
In the line https://github.com/dotnet/efcore/blob/089a035ecff8b066ec9ea0d51efeee652a1db4e5/src/EFCore/Properties/CoreStrings.resx#L980
 
The formatter transforms that into 
`'{0}' generated value '{1}' for the property '{2}.{3}`

I don't know if that way to call the variables works to specify the order, the used class is `LogValuesFormatter`.

This way to format strings using `{number}_{variableName}` like `1_myProperty` is also used in other places of the `.resx`
