### ISSUE TITLE
RevEng generates the *Context.cs file with hard coded connection string.

### ISSUE THREAD

**Issue by mhenderson442** [dotnet/efcore#2952]
When I use the RevEng command, it generates a `*Context.cs` file with a hard coded connection string.

```
options.UseSqlServer(@"Server=....")
```

As a developer, I would like the ability to have the generated code reference a connection string defined in the `config.json` file.

So that I can better move the code base to different environments.

```
{
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Server=......"
    }
  },
  "EntityFramework": {
    "MercurySchoolContext" :  "Data:DefaultConnection:ConnectionString"
  }
}
```

**Comment by rowanmiller** [comment]
@mhenderson442 the challenge here is that config.json and Startup.cs are specific to ASP.NET 5. Reverse engineer also works in all other project types, which have different config systems.

WPF, WinForms, Console, etc. are all pretty easy to integrate into config, but ASP.NET 5 and UWP are quite a bit more complicated.

**Comment by mhenderson442** [comment]
I think I could live with editing the context file each time I execute the RevEng command.

Since I was entering the full connection string in the command, I was hoping for the ability to reference a config file in the arguments.

**Comment by lajones** [comment]
Also see #1940

**Comment by mhenderson442** [comment]
Issue #1940 speaks to security concerns, which is certainly more important. 

I was looking at it from workflow perspective of managing connections, and moving applications from development, to staging, and finally production environments.

**Comment by divega** [comment]
> I was hoping for the ability to reference a config file in the arguments.

We also have https://github.com/aspnet/EntityFramework/issues/2464 which might help with this but isn't of the highest priority so may happen after RTM. If you have any feedback on how that would work best for you, please comment on that issue.

**Comment by mhenderson442** [comment]
Sorry for the redundancy. Looks like I didn't search hard enough to related issues.

Issue #2464 speaks more of what I had in mind.
