### ISSUE TITLE
EF core 7 build generates warnings

### ISSUE THREAD

**Issue by damilpanchal** [dotnet/efcore#29525]
I recently upgraded to EF core 7 on my project still using .NET6 and the build started failing with the following. 
 
The following two analyzers fail
1. Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer
2. Microsoft.EntityFrameworkCore.UninitializedDbSetDiagnosticSuppressor

****An instance of analyzer Microsoft.EntityFrameworkCore.InternalUsageDiagnosticAnalyzer** cannot be created from .nuget/packages/microsoft.entityframeworkcore.analyzers/7.0.0/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..**

  ****An instance of analyzer Microsoft.EntityFrameworkCore.UninitializedDbSetDiagnosticSuppressor** cannot be created from .nuget/packages/microsoft.entityframeworkcore.analyzers/7.0.0/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..**

In order to get past this Error, I had to disable **TreatWarningsAsErrors** on my projects. But I would like to know why is this warning generated. 

EF Core version: 7.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: Visual Studio 2022 17.4 & Rider 2022.2.4

**Comment by roji** [comment]
Try to fully clean your project (`git clean -xfd`, `dotnet clean`...). If the error persists, please post your full csproj.

**Comment by damilpanchal** [comment]
I tried that but had no luck. Eventually, i updated Visual studio and Rider and the issue was resolved. Thanks for the help. Closing this issue
