### ISSUE TITLE
EF Core IsTemporal() creates huge migration

### ISSUE THREAD

**Issue by HellHunterMax** [dotnet/efcore#29536]
When using EF core to make a table temporal after creation of the table, EF core creates Alter column commands for each field.
This should not be necessary because Temporal is table based, not column based.
Now in the test project you can see there are not that many fields on the entity, but imagine an entity with 30 fields.
This creates a migration that is 1000+ lines of code.

In the old EF core 6 it would create a small migration, but it would recreate the same migration every time you add-migration (this has been fixed here in version 7 but introduced this "bug?")

[Project to reproduce bug](https://github.com/HellHunterMax/DatabaseSelf)

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: windows 10
IDE: Visual Studio 2022 17.4

**Comment by HellHunterMax** [comment]
Not Just this. But adding properties and adding Temporal at the same time does not work.
![image](https://user-images.githubusercontent.com/39444801/202221925-119e982b-547d-437d-9dd3-92e9e265761c.png)

**Comment by pvidal-hdr** [comment]
seeing this as well and it makes checking/validating migrations very difficult. out of curiosity, is the annotation on the columns needed? from my use, it hasn't seemed to be required, but want to confirm before i make it my standard to remove the extra annotation calls to "clean up" the migration. thanks!
