### ISSUE TITLE
SqlServer fail to execute datetime where inline

### ISSUE THREAD

**Issue by Cricle** [dotnet/efcore#29548]
### Include your code

```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Linq.Expressions;

internal class Program
{
    private static void Main(string[] args)
    {
        var opt = new DbContextOptionsBuilder()
            .UseSqlServer("Data Source=.;Initial Catalog='6a997b6d6800421c9a0987ee25da881c_data';User Id=sa;Password=355343;TrustServerCertificate=true;");
        
        var dbc=new AppDbContext(opt.Options);
        var now = DateTime.Now;
        var raw = dbc.Students.Where(x => x.a4 == new DateTime(638040180120000000, DateTimeKind.Utc));//QueryString fail to exeucute
        var q = dbc.Students.Where(CreateExpression());
        var query = q.ToQueryString();
        var datas = raw.ToList();
    }
    private static Expression<Func<Student,bool>> CreateExpression()
    {
        var par1 = Expression.Parameter(typeof(Student));        
        var propValue = Expression.Property(par1, "a4");
        var otherValue = Expression.Convert(Expression.Constant(new DateTime(638040180120000000, DateTimeKind.Unspecified)),typeof(DateTime?));
        var body = Expression.Equal(propValue, otherValue);
        return Expression.Lambda<Func<Student, bool>>(body, par1);
    }
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions options) : base(options) { }

        public DbSet<Student> Students=>Set<Student>();
    }
    [Table("1743bc3e-826e-4419-b10a-590d48025de1")]
    public class Student
    {
        [Key]
        public string _id { get; set; }

        public DateTime? a4 { get; set; }
    }
}
```

In `dbc.Students.Where(x => x.a4 == new DateTime(638040180120000000, DateTimeKind.Utc))` will generic sql 

```sql
SELECT [1].[_id], [1].[a4]
FROM [1743bc3e-826e-4419-b10a-590d48025de1] AS [1]
WHERE [1].[a4] = '2022-11-14T10:20:12.0000000Z'
```

I execute it as a native query will got it. When converting date and/or time from string, conversion fails

![image](https://user-images.githubusercontent.com/26201412/201564128-bac7e248-078e-469a-a412-810d527ed4cf.png)

The query will also throw an exception.

![image](https://user-images.githubusercontent.com/26201412/201564286-edce22e3-071f-47d8-bc8f-dddb1830f6b0.png)

But when I use closure form incoming parameter.

```csharp
var dt = new DateTime(638040180120000000, DateTimeKind.Utc);
var raw = dbc.Students.Where(x => x.a4 == dt);
```

The generated sql is

```sql
DECLARE @__dt_0 datetime2 = '2022-11-14T10:20:12.0000000Z';

SELECT [1].[_id], [1].[a4]
FROM [1743bc3e-826e-4419-b10a-590d48025de1] AS [1]
WHERE [1].[a4] = @__dt_0
```

It will be ok.

### Include stack traces

```
   在 Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   在 Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   在 Microsoft.Data.SqlClient.SqlDataReader.Read()
   在 Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Program.Main(String[] args) 在 C:\Users\Administrator\Desktop\c\rsa2\Program.cs 中: 第 20 行
```

### Include verbose output
No

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 7.0.0
Target framework: .NET 6.0
Operating system: Win10-x64
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
I'm unable to reproduce the issue. See below for a tweaked version of your code sample which both runs with a regular inline DateTime value in the LINQ query, and which uses your CreateExpression() function to generate the filter expression tree. Both queries execute fine. Can you please modify this code to show it failing? Also, which version of SQL Server are you using?

Note that using expression trees to dynamically insert constant values into the query can be bad for performance. Read [query caching and parameterization](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#query-caching-and-parameterization) to learn more - it's recommended to avoid expression trees unless you're sure need them.

<details>
<summary>Attempted repro</summary>

```c#
var opt = new DbContextOptionsBuilder()
    .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
    .LogTo(Console.WriteLine, LogLevel.Information)
    .EnableSensitiveDataLogging();

await using var ctx = new AppDbContext(opt.Options);
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var dbc = new AppDbContext(opt.Options);

// Both of the following work fine:
_ = dbc.Students.Where(x => x.a4 == new DateTime(638040180120000000, DateTimeKind.Utc)).ToList();
_ = dbc.Students.Where(CreateExpression()).ToList();

static Expression<Func<Student,bool>> CreateExpression()
{
    var par1 = Expression.Parameter(typeof(Student));
    var propValue = Expression.Property(par1, "a4");
    var otherValue = Expression.Convert(Expression.Constant(new DateTime(638040180120000000, DateTimeKind.Unspecified)),typeof(DateTime?));
    var body = Expression.Equal(propValue, otherValue);
    return Expression.Lambda<Func<Student, bool>>(body, par1);
}

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions options) : base(options) { }

    public DbSet<Student> Students=>Set<Student>();
}

[Table("1743bc3e-826e-4419-b10a-590d48025de1")]
public class Student
{
    [Key]
    public string _id { get; set; }

    public DateTime? a4 { get; set; }
}
```

</details>

**Comment by Cricle** [comment]
SQL Service version is
```
Microsoft SQL Server 2017 (RTM-GDR) (KB5014354) - 14.0.2042.3 (X64) 
Apr 29 2022 21:04:31 
Copyright (C) 2017 Microsoft Corporation
Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) (Hypervisor)
```
Culture is `Simplified Chinese`
![image](https://user-images.githubusercontent.com/26201412/202058120-b2f7a225-571e-4b6c-945a-2b157617b383.png)

The computer time zone is `UTC+08:00`

The query is OK today.

![image](https://user-images.githubusercontent.com/26201412/202058378-367d7b4c-0d17-4e36-af74-ef9f855839ff.png)

The sql service has not changed and the time zone has not changed in recent days.

**Comment by roji** [comment]
@Cricle I still need to be able to reproduce this. Have you taken a look at my attempted repro above - does that fail for you as well? If it does not, can you please tweak it so that it does fail, and post the code?

**Comment by Cricle** [comment]
@roji I know what the problem is.

In sqlserver define is datetime
![image](https://user-images.githubusercontent.com/26201412/202366478-b59f8322-2f34-4231-b4b5-f4a68f610f70.png)

But in the code, I do not define a type and the default type is datetim2.

In the query, insufficient number of milliseconds.

At datetime will be **2022-11-17 13:44:40.`507`**
At datetime2 will be **2022-11-17 13:45:42.`6933333`**

When I specify that the type of the column is datetime, the query will be normal.
![image](https://user-images.githubusercontent.com/26201412/202367011-0430a723-cb21-4f39-b3c7-1a9751638a03.png)

**Comment by ErikEJ** [comment]
Maybe you should use a tool to define your DbContext to ensure correct mapping?

**Comment by roji** [comment]
@Cricle yeah, that makes sense - this is an unfortunate consequence of SQL Server's datetime/datetime2 types, and people run into this kind of bug every now and then. When you use EF to create your database from your context (via migrations), or create your context from your database (via reverse engineering), everything works fine as everything is in sync. But otherwise, it's your responsibility to correctly configure your EF context.

**Comment by Cricle** [comment]
This is a thing that should be noted when using SQL Server or similar situations.

Thanks.
