### ISSUE TITLE
Adding an existing item to a many-to-many relationship with a custom join entity does not get fixed up by the change tracker

### ISSUE THREAD

**Issue by JohnCgp** [dotnet/efcore#29554]
Given a `Student` that can have many `Course`s, and a `Course` can also have many `Student`s, if I try to add an existing `Course` to an existing `Student`, the `StudentCourses` navigation property is not updated with the new relationship when `.SaveChanges()` is called. Doing so with a new `Course` does result in the navigation property being updated, and the new relationship appears in the collection after saving.

Issue #28662 seems similar, but their issue was calling `.AsNoTracking()` on the queries, I'm not doing so.

Here's a [runnable project with two tests](https://github.com/JohnCgp/efcore-many-to-many-add-existing-entity-fails). One should pass (ManyToMany_AddNewEntity_IsFixedUpByEFCore), the other should fail (ManyToMany_AddExistingEntity_IsNotFixedUpByEFCore).

The failing test attempts to add an existing entity to the many-to-many relationship, but it is not fixed up by EF Core's change tracker when .SaveChanges() is called. When adding a new entity, fixing up does happen.

I've configured the relationship following [the docs](https://learn.microsoft.com/en-us/ef/core/modeling/relationships#join-entity-type-configuration):

```cs
modelBuilder.Entity<Student>(s =>
{
    s.HasMany(s => s.Courses)
        .WithMany(c => c.Students)
        .UsingEntity<StudentCourse>(
            j => j
                    .HasOne(sc => sc.Course)
                    .WithMany(c => c.StudentCourses)
                    .HasForeignKey(sc => sc.CourseId),
            j => j
                    .HasOne(sc => sc.Student)
                    .WithMany(s => s.StudentCourses)
                    .HasForeignKey(sc => sc.StudentId),
            j =>
            {
                j.Property(sc => sc.HasAttended).HasDefaultValue(false);
                j.HasKey(t => new { t.StudentId, t.CourseId });
            }
        );
});
```

[Source](https://github.com/JohnCgp/efcore-many-to-many-add-existing-entity-fails/blob/e5e6d07bae62fceb0b3b139da2c8b3fe7dbdf2c0/Data/SchoolContext.cs#L19-L39)

Adding a new entity works:

```cs
[Fact]
public async Task ManyToMany_AddNewEntity_IsFixedUpByEFCore()
{
    Student? student = null;

    await using var dbContext = new SchoolContext(BuildOptions());
    student = new Student() { FirstMidName = "John", LastName = "Doe" };

    var course = new Course() { Title = PhysicsCourseName, Credits = 20 };

    student.Courses = new List<Course>() { course };
    dbContext.Students.Add(student);

    await dbContext.SaveChangesAsync();

    // EF Core fixes up the relationship as expected when it's a new
    // entity.
    student.StudentCourses.ShouldSatisfyAllConditions(
        sc => sc.Count.ShouldBe(1),
        sc => sc.ShouldContain(x => x.Course.Title == PhysicsCourseName)
    );
}
```

[Source](https://github.com/JohnCgp/efcore-many-to-many-add-existing-entity-fails/blob/e5e6d07bae62fceb0b3b139da2c8b3fe7dbdf2c0/Tests/PersistenceTests.cs#L108-L129)

While adding an existing entity fails:

```cs
// [...]

// Create a course in the database, but don't add it to the student
// yet.
var existingCourse = new Course { Title = ExpectedCourseName, Credits = 20 };
dbContext.Courses.Add(existingCourse);
await dbContext.SaveChangesAsync();

// Add the previously existing course, Data Structures, to the
// student.
persistedStudent.Courses.Add(existingCourse);

// Change detection hasn't happened, so StudentCourses still has
// two courses.
persistedStudent.StudentCourses.ShouldSatisfyAllConditions(
    sc => sc.Count.ShouldBe(2),
    sc => sc.ShouldContain(x => x.Course.Title == MathsCourseName),
    sc => sc.ShouldContain(x => x.Course.Title == PhysicsCourseName)
);

// This triggers change detection.
await dbContext.SaveChangesAsync();

// StudentCourses should now have the extra course, Data
// Structures, but doesn't.
persistedStudent.StudentCourses.ShouldSatisfyAllConditions(
    sc => sc.Count.ShouldBe(3), // This fails, there are only 2.
    sc => sc.ShouldContain(x => x.Course.Title == ExpectedCourseName), // This course is not in the collection.
    sc => sc.ShouldContain(x => x.Course.Title == MathsCourseName),
    sc => sc.ShouldContain(x => x.Course.Title == PhysicsCourseName)
);
```

[Source](https://github.com/JohnCgp/efcore-many-to-many-add-existing-entity-fails/blob/e5e6d07bae62fceb0b3b139da2c8b3fe7dbdf2c0/Tests/PersistenceTests.cs#L69-L97)

### Include provider and version information

EF Core version: 6.0.4
Database provider: (in memory, original behaviour observed with Npgsql)
Target framework: (.NET 6.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 Version 17.1.2)

**Comment by ajcvickers** [comment]
@JohnCgp This is a duplicate of #26886, which is fixed in EF7.

**Comment by JohnCgp** [comment]
Phew, thought it was a PEBKAC, and didn't stumble on that linked issue. Thanks!
