### ISSUE TITLE
Trouble with nested entity with no partition key and with a collection of enum values in Cosmos DB

### ISSUE THREAD

**Issue by wbuck** [dotnet/efcore#29558]
Currently I have the following document structure:

    public enum FsmoRole {  /*Bunch of FSMO roles*/ }

    public class Project
    {
        public IList<WorkItem> WorkItem { get; set; }
    }

    public class WorkItem
    {
        public IList<FsmoRole> FsmoRoles { get; set; }
    }

The `WorkItem` entity is not a document, it is just a part of the `Project` document and thus does not have a defined partition key.

When I attempt to run the application, I receive the following error:

> 'WorkItem.FsmoRoles' could not be mapped because it is of type 'IList<\FsmoRole>', which is not a supported primitive type or a valid entity type

Now, the `FsmoRoles` property is used is some other places as well, but those usages haven't been an issue because the entities it's defined on are actual documents within Cosmos DB, so I was able to explicitly map those with a converstion:

    builder.Entity<SomeEntity>()
        .Property(e => e.FsmoRoles)
        .HasConversion(
            v => v.Select(e => e.ToString()).ToList(),
            v => v.Select(e => Enum.Parse<FsmoRole>(e, true)).ToList());

But if I attempt to do that with the `WorkItem` entity I receive the following error:

> System.InvalidOperationException: 'The entity type 'WorkItem' does not have a partition key set, but is mapped to the container 'organization' shared by entity types with partition keys. Configure a compatible partition key on 'WorkItem'.'

How can I get this to work?

I also want to note that I do have another entity which has the `FsmoRoles` property which is nested even further which also does not contain a partition key as it's not a document, just a part of a document.

So, imagine I have the following:

    public enum FsmoRole {  /*Bunch of FSMO roles*/ }

    public class Project
    {
        public IList<WorkItem> WorkItem { get; set; }
    }

    public class WorkItem
    {
        public IList<Computer> Computers { get; set; }
    }

    public class Computer
    {
        public IList<FsmoRole> FsmoRoles { get; set; }
    }

Both the `WorkItem` and `Computer` entities do not have a partition key as both entities make up a larger entity `Project` which is a document in Cosmos DB with a partition key.

I'm also storing these `enum` values as a `array` of `string` in Cosmos DB.

Here is the `OnModelCreating`

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.HasDefaultContainer(Options.ContainerId);

        builder.Entity<Project>()
            .ToContainer(Options.ContainerId)
            .HasPartitionKey(e => e.OrganizationId)
            .Property(e => e.Etag).IsETagConcurrency();

        builder.Entity<DomainController>(b =>
        {
            b.ToContainer(Options.ContainerId)
             .HasPartitionKey(e => e.OrganizationId)
             .Property(e => e.Etag).IsETagConcurrency();

            b.Property(e => e.FsmoRoles)
            .HasConversion(
                v => v.Select(e => e.ToString()).ToList(),
                v => v.Select(e => Enum.Parse<FsmoRole>(e, true)).ToList());
        });      

        builder.Entity<Backup>()
            .ToContainer(Options.ContainerId)
            .HasPartitionKey(e => e.OrganizationId)
            .Property(e => e.Etag).IsETagConcurrency();

        base.OnModelCreating(builder);
    }
    
EF Core version: 6.0.11
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)
Host: Azure Functions (in process)

**Comment by ajcvickers** [comment]
@wbuck Can you post your model configuration--for example, the `OnModelCreating` code?

**Comment by wbuck** [comment]
@ajcvickers I've posted what I currently have. I didn't add the commented-out code as it's obviously incorrect. For example, my attempts to add a conversion to entities using `enum` collections that are not documents.

**Comment by wbuck** [comment]
OK I *think* I've figured out how to get this working (now I just need to figure out how to handle our camel cased naming convention..)

I used `OwnsMany` and `OwnsOne` to configure the owned types, which seems to be allowing me to query the DB.
Like I mentioned above I just need to figure out what I'm going to do about EF wanting to use pascal cased property names.

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.HasDefaultContainer(Options.ContainerId);

        builder.Entity<Project>(tb =>
        {
            tb.HasDiscriminator(p => p.Type)
              .HasValue("project");

            tb.ToContainer(Options.ContainerId)
             .HasPartitionKey(e => e.OrganizationId)
             .Property(e => e.Etag).IsETagConcurrency();

            tb.OwnsMany(p => p.WorkItems, pb =>
            {
                pb.OwnsOne(c => c.ComputerInformation, wb =>
                {
                    wb.Property(e => e.FsmoRoles)
                    .HasConversion(
                        v => v.Select(e => e.ToString()).ToList(),
                        v => v.Select(e => Enum.Parse<FsmoRole>(e, true)).ToList());
                });
            });
        });

        builder.Entity<DomainController>(tb =>
        {
            tb.HasDiscriminator(dc => dc.Type)
              .HasValue("controller");

            tb.ToContainer(Options.ContainerId)
              .HasPartitionKey(e => e.OrganizationId)
              .Property(e => e.Etag).IsETagConcurrency();

            tb.Property(e => e.FsmoRoles)
              .HasConversion(
                v => v.Select(e => e.ToString()).ToList(),
                v => v.Select(e => Enum.Parse<FsmoRole>(e, true)).ToList());
        });

        builder.Entity<Backup>(tb =>
        {
            tb.HasDiscriminator(b => b.Type)
              .HasValue("backup");

            tb.ToContainer(Options.ContainerId)
              .HasPartitionKey(e => e.OrganizationId)
              .Property(e => e.Etag).IsETagConcurrency();
        });

        base.OnModelCreating(builder);
    }

**Comment by AndriySvyryd** [comment]
@wbuck You can specify the JSON property names by calling `.ToJsonProperty` on properties or owned types, see [docs](https://learn.microsoft.com/ef/core/providers/cosmos/?tabs=dotnet-core-cli#embedded-entities)
