### ISSUE TITLE
EF 7 Navigation propeties fixup

### ISSUE THREAD

**Issue by gaglia** [dotnet/efcore#29568]
Hello everyone,

I would like a clarification on the handling of relationship update in EF 7
I would like to understand if there is the possibility to have in EF 7 the navigation properties always fixup even before calling SaveChanges ?

We are converting a project that still uses Entity Frameword 4.0 where this behavior was the default.
Unfortunately the application code relies heavily on this behavior that I can't figure out if and how it can be achieved with EF 7

Here's a simple example of what I mean:

Table veDocumenti with FK on table genAnag

modelBuilder veDocumenti:

```C#

entity.HasOne(d => d.genAnag).WithMany(p => p.veDocumenti).HasConstraintName("FK_veDocumenti__genAnag");

```
veDocumenti - genAnag navigation property:

```C#

private genAnag? _genAnag ;

[ForeignKey("IdAnag")]
[InverseProperty(nameof(WpfApp.DataAccess.Entities.genAnag.veDocumenti))]

public virtual genAnag? genAnag { get { return _genAnag; } set => _genAnag = value; }

```

Sample VB.NET code:

```VB

db = New iMioEntities()

'Load entity documento
documento = db.veDocumentiSet.Include("genAnag").First(Function(c) c.IdDoc_T = 424620)

'Check navigation properties: documento.genAnag is loaded correctly
Me.IdAnag.Text = documento.genAnag.RagSociale

'Change FK IdAnag
documento.IdAnag = "SINESR"

'Check navigation properties:
'Without UseLazyLoadingProxies -> documento.genAnag == null 
'With UseLazyLoadingProxies -> documento.genAnag still has the previous value
Me.IdAnag.Text = documento.genAnag.RagSociale

```
In the example I try to make you understand what I mean, after changing the IdAnag field (FK) on veDocumenti table the genAnag navigation property does not update.

Thanks in advance for any feedback

### Provider and version information

EF Core version: EF 7
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET 7.0)
Operating system: Win11
IDE: (Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by gaglia** [comment]
Hi @ajcvickers I am attaching an example project.

If needed in the SQLScripts folder of the WpfApp.DataAccess project I have inserted the scripts to recreate the SQL database

As said earlier I can't figure out how the "relationship fixup" mechanism works.

Here I report what I found in the documentation
(https://learn.microsoft.com/en-us/ef/core/change-tracking/relationship-changes)

Relationship fixup
EF Core keeps navigations in alignment with foreign key values ​​and vice versa. That is, if a foreign key value changes such that it now refers to a different principal/parent entity, then the navigations are updated to reflect this change. Likewise, if a navigation is changed, then the foreign key values ​​of the entities involved are updated to reflect this change. This is called "relationship fixup".

So I would expect the relations to always be kept up to date by EF but that's not what happens in my project and I don't understand if maybe I'm missing some settings or what I'm doing wrong in my approach.

A thousand thanks

[EFCoreTest.Solution.zip](https://github.com/dotnet/efcore/files/10029973/EFCoreTest.Solution.zip)

**Comment by ajcvickers** [comment]
@gaglia Please provide details of what I should run in the given project, what behavior you are seeing in which part of the code, and what behavior you expect to see.

**Comment by gaglia** [comment]
Hi @ajcvickers 
clicking the "SELEZIONA DOCUMENTO" button of the wpf application I tried to produce what I expected.
In the comments I tried to insert the detail of the behavior:

```VB
db = New iMioEntities()

'Load entity documento
documento = db.veDocumentiSet.First(Function(c) c.IdDoc_T = 424620)

'Check navigation properties: documento.genAnag is loaded correctly
Me.IdAnag.Text = documento.genAnag.RagSociale

'Change FK IdAnag
documento.IdAnag = "SINESR"

'Check navigation properties: documento.genAnag == NULL -> I would expect genAnag to be valued with the new genAnag set
Me.IdAnag.Text = documento.genAnag.RagSociale

```
In practice, I expect that after changing the IdAnag field, which is the connection field with the FK, the relative navigation property genAnag updates automatically.
So that the next time I access the property it returns the updated genAnag object instead in this case it is null

In general, therefore, I would like to understand how to make sure that the navigation properties are always updated without having to worry about updating them "manually"

In the model I am using Lazy-loading without proxies by injecting the ILazyLoader service into entities

In the SQLScripts folder of the WpfApp.DataAccess project I placed the SQL scripts to create the tables and data to start the project.

Thank you

**Comment by ajcvickers** [comment]
@gaglia This could be a bug; I will investigate.

**Comment by ajcvickers** [comment]
Note for triage: when the FK is changed, then the navigation is correctly set to null, but it then fails to lazy-load when accessed. This only happens when injecting the loading delegate. Same behavior on 6.

Workaround is to inject ILazyLoader instead of the delegate:

```C#
private ILazyLoader LazyLoader { get; set; }
```

Small repro:

```C#
public static class Your
{
    public static string ConnectionString = @"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow";
}

public class Blog
{
    private ICollection<Post> _posts;

    private Action<object, string> LazyLoader { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    public ICollection<Post> Posts
    {
        get => LazyLoader.Load(this, ref _posts);
        set => _posts = value;
    }
}

public class Post
{
    private Blog _blog;

    private Action<object, string> LazyLoader { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    public int? BlogId { get; set; }

    public Blog Blog
    {
        get => LazyLoader.Load(this, ref _blog);
        set => _blog = value;
    }
}

public static class PocoLoadingExtensions
{
    public static TRelated Load<TRelated>(
        this Action<object, string> loader,
        object entity,
        ref TRelated navigationField,
        [CallerMemberName] string navigationName = null)
        where TRelated : class
    {
        loader?.Invoke(entity, navigationName);

        return navigationField;
    }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs => Set<Blog>();
    public DbSet<Post> Posts => Set<Post>();
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog { Id = 1, Posts = new List<Post>{new() { Id = 1 }}});
            context.Add(new Blog { Id = 2 });

            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            var post = context.Posts.Single(e => e.Id == 1);

            Console.WriteLine(post.Blog.Id);
            post.BlogId = 2;
            context.ChangeTracker.DetectChanges();
            Console.WriteLine(post.Blog.Id);
        }
    }
}

```

**Comment by gaglia** [comment]
Hi @ajcvickers thanks for the feedback!

I will try the suggested Workaround right away

**Comment by ajcvickers** [comment]
This was fixed by the recent lazy-loading work.
