### ISSUE TITLE
Json: predicate on json bool property generates incorrect sql 

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#29572]
```cs
ss.Set<JsonEntityAllTypes>().Where(x => !x.Reference.TestBoolean)
```

produces:

```sql
SELECT [j].[Id], [j].[Collection], [j].[Reference]
FROM [JsonEntitiesAllTypes] AS [j]
WHERE NOT (CAST(JSON_VALUE([j].[Reference],'$.TestBoolean') AS bit))
```

problem is search condition visitor doesn't correctly process json bool properties

**Comment by roji** [comment]
Reopening to consider patching this for 7.0.

**Comment by ajcvickers** [comment]
Note from triage: we could consider patching this if we get a lot of customer reports. Workaround is to use `ss.Set<JsonEntityAllTypes>().Where(x => x.Reference.TestBoolean == false)`

**Comment by ajcvickers** [comment]
@maumar Let's create the patch PR for this.
