### ISSUE TITLE
Possible mistake in translation from LINQ to SQL by EFC 6

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#29581]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Possible-mistake-in-translation-from-LIN/10104271)._

---
(Would delete this post, if I knew how. I did not completely understand the logic when I wrote it.)

\[severity:Other\]  
I have developed a Core MVC 6.0 Web application with VS 2022 Community, using the latest version. I think that the SQL translation of an EFC query may be slightly incorrect. Below you will find a simplified version of the query, together with the translation to SQL performed by EFC.

First, some background on the involved database tables:  
Person,  
Measure,  
Situation,  
Department,  
MeasurePermission, and  
SituationPermission.

The Person table is a child table of the Department table and uses the FK DepartmentID. This FK can be null.  
The MeasurePermission table is a join table between the Person and the Measure tables.  
The SituationPermission table is a join table between the Person and the Situation tables.

Here is the simplified LINQ query:

```  
dc.Persons
  .Where(p => p.PersonID == personID)
  .Select(p => new
  {
      DEM =
	    p.Department != null &&
            p.Department.Active &&
            p.Department
                .MeasurePermissions
                .Any(mp => mp.Measure.Active),

      DES =
	    p.Department != null &&
            p.Department.Active &&
            p.Department
            .SituationPermissions
            .Any(sp => sp.Situation.Active)
  })
  .FirstOrDefault();
  
  
  
  
```

“DEM” means that a Person can perform data entry operations on Measures.  
“DES” means that a Person can perform data entry operations on Situations.

Here is the translation into SQL:

```  
SELECT TOP(1) CASE
    WHEN (([d].[DepartmentID] IS NOT NULL) AND ([d].[Active] = CAST(1 AS bit))) AND EXISTS (
        SELECT 1
        FROM [MeasurePermission] AS [m]
        INNER JOIN [Measure] AS [m0] ON [m].[MeasureID] = [m0].[MeasureID]
        WHERE (([d].[DepartmentID] IS NOT NULL) AND ([d].[DepartmentID] = [m].[DepartmentID])) AND ([m0].[Active] = CAST(1 AS bit))) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END AS [DEM], CASE
    WHEN (([d].[DepartmentID] IS NOT NULL) AND ([d].[Active] = CAST(1 AS bit))) AND EXISTS (
        SELECT 1
        FROM [SituationPermission] AS [s]
        INNER JOIN [Situation] AS [s0] ON [s].[SituationID] = [s0].[SituationID]
        WHERE (([d].[DepartmentID] IS NOT NULL) AND ([d].[DepartmentID] = [s].[DepartmentID])) AND ([s0].[Active] = CAST(1 AS bit))) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END AS [DES]
FROM [Person] AS [p]
LEFT JOIN [Department] AS [d] ON [p].[DepartmentID] = [d].[DepartmentID]
WHERE [p].[PersonID] = @__personID_0
  
  
  
  
```

In both cases, “p.Department != null” is translated as “\[d\].\[DepartmentID\] IS NOT NULL”.

It seems to me that it should be translated as “\[p\].\[DepartmentID\] IS NOT NULL” (in both cases).

(I get the point now. It is not a mistake. Would delete post if I knew how.)

---
#### Feedback Bot on 7/27/2022, 06:46 AM: 

(private comment, text removed)
#### Feedback Bot on 11/3/2022, 05:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by roji** [comment]
> (I get the point now. It is not a mistake. Would delete post if I knew how.)

Closing as the SQL seems fine.
