### ISSUE TITLE
How to get metadata that configed on OnModelCreating

### ISSUE THREAD

**Issue by anchurcn** [dotnet/efcore#29583]
We can utilize metadata to write some DbContext extensions.
Actually, we want the type mapping between entity's property and database column type, include the default type mapping and configed in OnModelCreating.

**Comment by ajcvickers** [comment]
@anchurcn `context.Model` is the entry point to the EF model.  Here's an example:

```C#
foreach (var entityType in context.Model.GetEntityTypes())
{
    foreach (var property in entityType.GetDeclaredProperties())
    {
        Console.WriteLine(((RelationalTypeMapping)property.GetTypeMapping()).StoreType);
    }
}
```

**Comment by anchurcn** [comment]
Thank you, it works. I wonder where the data is stored, I'm hard to find it on the debugger watch window.

**Comment by ajcvickers** [comment]
@anchurcn Drill down into the Model property.
