### ISSUE TITLE
"Scaffolding:ConnectionString" annotation scaffolded

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29580]
I use this to pass a "fake" connection string from my .dacpac IDatabaseModelFactory

```csharp
 var dbModel = new DatabaseModel
            {
                DatabaseName = Path.GetFileNameWithoutExtension(connectionString),
                DefaultSchema = schemas.Any() ? schemas.First() : "dbo",
            };

            dbModel["Scaffolding:ConnectionString"] = $"Data Source=(local);Initial Catalog={dbModel.DatabaseName};Integrated Security=true";
```
With EF Core 6 and 7, this is included in the generated DbContext:

`         modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=GroupOnline.DigitalContracts.Database;Integrated Security=true");
`

But maybe I got the name wrong?

### Include provider and version information

EF Core version: 6 and 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system:
IDE: Visual Studio 2022 17.3

**Comment by bricelam** [comment]
Hmm, I don't think anything changed around this in 7.0...

Here's the code that takes it from the database model and sets it on the ModelCodeGenerationOptions:

https://github.com/dotnet/efcore/blob/bf20e32fa8d0888f7d531a25c146284285d980a3/src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs#L93-L99

**Comment by ErikEJ** [comment]
This also happens in 6.

**Comment by ajcvickers** [comment]
@ErikEJ Can you give a few more details on what the impact is here? For example, is this breaking anything for customers?

**Comment by ErikEJ** [comment]
No, it just adds this line to the generated DbContext as mentioned above:

`modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=GroupOnline.DigitalContracts.Database;Integrated Security=true");`

Feel free to close as it is more of a cosmetic issue

**Comment by bricelam** [comment]
Ah, we don't remove it from the model. Yeah, we should do that.
