### ISSUE TITLE
Migration doesn't detect alterations to existing properties EF core 7

### ISSUE THREAD

**Issue by Kinoo3** [dotnet/efcore#29595]
Hello, I have an existing Entity, let's call it book, that has the title property, which is a string without any restraints, I then create the first migration to this specific entity, and works fine
But when I add new characteristics to it down the line, i.e. adding to the book property
```C#
 Property(x => x.Title).IsRequired();
```
The new migration doesn't detect the new rule to the existing property

Is there a solution to force the migration to look at that alteration? or any workaround that isn't manually changing it at the database level or simply deleting the first migration and doing a new one (possible data loss)? Thanks in advance!

Repro: 
Create a random basic entity with string property, add it to context dbset, create migration, after that alter the string property to contain the isrequired constraint, create new migration and it should be empty

**Comment by roji** [comment]
I cannot reproduce this - after adding IsRequired and adding a migration, that migration properly contains an operation to alter the column accordingly.

Are you sure your property wasn't required before adding IsRequired? Note that with C# non-nullable reference types, a simple `string` property is considered required (as opposed to a nullable `string?`).

**Comment by Kinoo3** [comment]
Well that explains it!
Thank you, and sorry for your time
