### ISSUE TITLE
DbSet Moq Exception

### ISSUE THREAD

**Issue by vhforte** [dotnet/efcore#29598]
I want to have IDbSet interface based on IQuerable and Save/Update and other methods of DbSet.
This will help me to write Unit Tests for repositories. Right now I cannot do it - Moq framework gives me exceptions - Cannot mock because class must have default constructor. With Interfaces there are no problems in mocking.

**Comment by roji** [comment]
@vhforte mocking DbSet is discouraged, and isn't considered a good way to test applications using EF; I suggested giving [this doc page](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy) a good read.

If you still want to mock DbSet, libraries such as [Moq.EntityFrameworkCore](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore); an IDbSet interface is not required. Also see #1282, #4273 and other related issues.
