### ISSUE TITLE
Discriminator is always filled with a default value when it is (or part of) the primary key AND a shadow field

### ISSUE THREAD

**Issue by NikoGJ** [dotnet/efcore#29605]
Hello,
I've been pulling my hair for too long now, but I think this ultimately boils down to a bug.
* I'm using TPH
* The discriminator field is part of the primary key
* The discriminator field is a shadow field

I've replicated the bug using a minimalist example (my business case is much more complex and involves relationships from other tables to this inheritance hierarchy):
* Domain model
```csharp
public abstract class MyBaseClass
{
    public string SomeIrrelevantField { get; set; }
}

public class MyDerivedClassOne : MyBaseClass
{
}

public class MyDerivedClassTwo : MyBaseClass
{
}
```
* EF Mapping using fluent Api
```csharp
modelBuilder.Entity<MyBaseClass>(build =>
{
    build.HasDiscriminator<string>("MyType")
        .HasValue<MyDerivedClassOne>("one")
        .HasValue<MyDerivedClassTwo>("two")

    build.HasKey("MyType");
});
```

### Reproduction
I add a new entity to the DbSet using the derived entities.
```csharp
// Database schema is generated on the fly from code when starting the test using EnsureCreated()
[TestMethod]
public async Task InsertDerivedEntity_ShouldHaveMatchingValueInDiscriminator()
{
    using var context = Fixture.CreateContext();
    context.Database.BeginTransaction(); // The transaction rollbacks at the end of the test

    context.MyBaseClasses.Add(new MyDerivedClassOne
    {
        SomeIrrelevantField = "foo"
    });
    await context.SaveChangesAsync();

    context.ChangeTracker.Clear(); // Just to force EF to SELECT from database

    // This will fail when trying to materialize the entity because of the wrong discriminator field value that has been stored.
    var tested = await context.MyBaseClasses.FirstAsync(); 
    Assert.IsNotNull(tested);
}
```
### Actual result
The record created has `MyType` field with value "MyBaseClass".
As a consequence, the entity cannot be materialized back (cause the base class is abstract and there is no mapping defined with `HasValue`)
### Expected result
The record created should have had the `MyType` field with value "one". (based on the instanciated entity type)

### Found workarounds
* Make the discriminator field not shadowed : and pass the value manually
```csharp
context.MyBaseClasses.Add(new MyDerivedClassOne
{
    SomeIrrelevantField = "foo",
    MyType = "one"
});
```
But this defeats the purpose of having a discriminator field handled by EFCore.

* Get the discriminator field out of the primary key
Using a shadow property is enough to make the discriminator have the good value as long as it's not part of the PK anymore. But we loose the uniqueness constraint brought by the primary key.
```csharp
modelBuilder.Entity<MyBaseClass>(build =>
{
    build.Property<int>("Id").UseIdentityColumn();
    build.HasDiscriminator<string>("MyType")
        .HasValue<MyDerivedClassOne>("one")
        .HasValue<MyDerivedClassTwo>("two")

    build.HasKey("Id");
});
```

Please share your thoughts :)

### Version information

EF Core version: 6.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
This is working for me when I use EF Core 7. If it's still failing for you with EF Core 7, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by NikoGJ** [comment]
Ah, interesting, then !
I'll try to upgrade to EF Core 7 and see if it's working on y business case. I'll post a comment with my findings. Thanks !

**Comment by NikoGJ** [comment]
Tested in EF7, it works indeed !
