### ISSUE TITLE
Conditional dependent entity?

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#29604]
## Ask a question

As an illustrative example, say you want to pull back a blog post and the comments made by the current user. The blog post properties are always the same, however, the dependent `List<Comments>` would take, in this case, the user's Id to pull back the relevant comments.

The data can be added as `[NotMapped]` properties, however that rules out being able to sort and filter on those properties as part of paging (skip/take).

Is there a mechanism to do this with EF Core?

**Comment by roji** [comment]
Are you looking for [Filtered include](https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include)? That allows you to only load the the comments matching a specific filter (e.g. the user's Id).

**Comment by mrlife** [comment]
@roji, thanks that does sound like the mechanism for this. Is it possible to use that with read-only tables/views? I have a view that's set up using `ToView` that I would like to use in this scenario. I suspect that the needed relationships cannot be set up, which would preclude using `Include()`. I have attempted to add `Key` and `ForeignKey` data annotations, but they don't seem to work with views -- would you say that is the case?

**Comment by roji** [comment]
EF doesn't really care about tables vs. views (note that views can also be updatable in certain databases). You can definitely have read-only views configured with primary keys and foreign keys, and as long as everything corresponds in the database things should work fine. Creating such views may not be doable with standard migrations generated by EF, but that's a different concern.

**Comment by mrlife** [comment]
@roji, thanks I'm trying to get this sorted using a composite key in both views. The [docs for composite key](https://learn.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-composite-key%2Ccomposite-key#foreign-key) have a `<PrincipalEntity><CompositeKeyPropertyN>` in the dependent entity for each composite key property in the principal entity.

With an existing dependent view, it's not clear how to create those new properties. I've added them to the dependent entity's model, however when running the app, it throws an error that they don't exist in the actual dependent view. If there's something in the docs addressing this situation, I apologize that I haven't been able to find it.

**Comment by roji** [comment]
I don't follow exactly... Can you please post a minimal, runnable code sample so I understand exactly what you're trying to do?

I advise forgetting for a second the fact that you're using views, and approach the problem as if you're just dealing with tables that are already created in the databases; EF doesn't support creating views via migrations in any case, and when it's querying from something, it doesn't care (or even know) whether it's a view or a table - it just selects from it.

**Comment by mrlife** [comment]
@roji, thanks for offering to take a look. I'm sorry it's not that clear, but hopefully this repro project will help. When running the project, it attempts to read from the dependent entity and throws an error on the composite key property that is in the dependent entity's model but I'm not sure how to create or populate in the actual view.

https://github.com/mrlife/GetStarted

**Comment by ajcvickers** [comment]
@mrlife How are you creating the views in the database?

**Comment by mrlife** [comment]
@ajcvickers, thanks for jumping in. The views are pre-existing.

**Comment by ajcvickers** [comment]
@mrlife So how can we investigate with the code you provided since it contains no definitions for the views?

**Comment by mrlife** [comment]
@ajcvickers, I'm sorry I misremembered and provided an incorrect response. They are created on lines 35 and 40 of Program.cs

```
db.Database.ExecuteSqlRaw(
    @"DROP VIEW IF EXISTS View_Blog;
        CREATE VIEW View_Blog AS
        SELECT BlogId, Url
        FROM Blogs;");
db.Database.ExecuteSqlRaw(
    @"DROP VIEW IF EXISTS View_Post;
        CREATE VIEW View_Post AS
        SELECT PostId, BlogId
        FROM Posts;");
```

**Comment by ajcvickers** [comment]
@mrlife Okay, I see that now. The view doesn't have a `BlogBlogId` column. The view needs to have columns for all mapped properties in the same way that a table does.

**Comment by mrlife** [comment]
@ajcvickers, yes that's what I was referencing in [this comment](https://github.com/dotnet/efcore/issues/29604#issuecomment-1322377574). It doesn't have `BlogBlogId` or `BlogUrl`, and it's not clear how to create both of those. The first one can be created since `BlogId` already exists, but how would one have access in the dependent entity to the `Url` column that exists in the principal entity?

**Comment by ajcvickers** [comment]
@mrlife That doesn't seem like an EF issue. EF can map to a view, but it has nothing to say about what the view can return or how it returns it.

**Comment by mrlife** [comment]
@ajcvickers, maybe it's just the nature of working with composite keys. In this case, I need to find a way to include the `Url` column from `View_Blog` in `View_Post` in order to create a successful link between the 2 tables. It is a little awkward, but I can see how this is the only way to structure it to work. I really appreciate your and @roji's help with this!

**Comment by mrlife** [comment]
@ajcvickers @roji, is it possible when a filtered `Include` would return null properties to return default values instead? This would be really helpful for tabular data that is being sorted by a column in the `Include`. I haven't found a way but wanted to double check before changing my approach. Thank you.

**Comment by roji** [comment]
@mrlife that wouldn't work for any application that's interested in the distinction between null and default value - EF generally doesn't arbitrarily transform data in this way.
