### ISSUE TITLE
Scaffold-DbContext does not produce empty constructor in EF7 anymore

### ISSUE THREAD

**Issue by DJDoena** [dotnet/efcore#29613]
In EF Core, a DB-first scaffolding could be achieved like this

```
Scaffold-DbContext "Server=<connection string here>" Microsoft.EntityFrameworkCore.SqlServer -Context TheDbEntities -NoOnConfiguring
```
The output would generate an empty constructor. From this class one could inherit and override the `OnConfiguring` method to inject the SQL server connection string like this:

```
public sealed class TheSqlEntities : TheDbEntities 
{

    private readonly string _connectionString;

    public TheSqlEntities (string connectionString)
    {
        _connectionString = connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connectionString);
    }
}
```

However, when using the `-NoOnConfiguring` switch, no empty constructor is generated anymore, only the `DbContextOptions` version

```
public partial class TheDbEntities : DbContext
{
    public TheDbEntities(DbContextOptions<TheDbEntities> options)
        : base(options)
    {
    }
...
```

Without this switch, an empty constructor is generated but also the `OnConfiguring` method containing the connection string in the clear.

.NET6
EF7

**Comment by ErikEJ** [comment]
You can use the T4 templates to change that or add the empty constructor in a partial class

**Comment by ajcvickers** [comment]
@DJDoena This is by-design. It ensures that the generated context is compatible with D.I. when OnConfiguring it not being used. As Erik says, the T4 template can be changed if desired.
