### ISSUE TITLE
Find many objects by key - The right way?

### ISSUE THREAD

**Issue by mkalinski93** [dotnet/efcore#29621]
Hello,

we want to start with efcore 7 and found out, that we will have at least one major problem within our project scope.
Our requirement is to fetch a ton of data by their unique keys from the database.

We are using MSSQL, so we also have a 2100 query parameter limit, too.
I found some solutions, but all are not suitable performance-wise.

Some suggested to use .Contains, some created ExpressionTrees, and some used chunking with both previous strategies.
The problem I see is that I also have to take into account, that the entities I´m looking for could already being tracked (local).

So my question is: How can I query 100.000 objects by their keys fast and how can I make sure that it´s also checking its local cache before querying the data from the remote database?

**Comment by ErikEJ** [comment]
This is one apporach: https://erikej.github.io/efcore/sqlserver/2021/11/22/efcore-sqlserver-cache-pollution.html

**Comment by stevendarby** [comment]
DbSet.Local is a list of the locally tracked entities, so you can check that first. You can then query the remaining keys. 

Using Contains does not use parameters so you can query more than 2100. 

The suggestion above is an alternative to Contains, to avoid a problem with cache pollution on the DB server. I wouldn't automatically assume it's necessary to do that unless you see memory problems. I think SQL Server estimates there are only 50 records when you use string_split so the plan it produces might be suboptimal if it turns out there are actually 100,000.

**Comment by mkalinski93** [comment]
thank you for your help. I didn´t knew that contains does not use parameters, maybe that could be helpful in the future.

I may have found something else, a library called EfCore.BulkExtensions. 
So what I could end up with is a hybrid solution by looking at DbSet.Local first and query the remaining data from the database with BulkRead. It uses sqlbulkcopy under the hood and may heavily relies on temp tables.

Anyway, I also like the approach from @ErikEJ. I will get into both of them.
What really is mind boggling to me is the fact that so less people actually looking up for a solution to this.
I can´t think about this being too "specific". We have a LOB Project including prices and we generate millions of rows (including archive). Mass-edit functionality is a must and people could up end changing a lot of "pre-selected" data which can grow exponentially with the amount of selected price lists. I would really love to see efcore adapting a solution, but I´m sure that there´s no "one function fits all" approach. It always "depends" :)

**Comment by roji** [comment]
Duplicate of #13617

**Comment by roji** [comment]
@ErikEJ @stevendarby thanks for chiming in. This is indeed a known pain point - this kind of thing generally doesn't map well to the relational database concept. However, this is something that's high on our top-requested issues, and we're thinking about ways to integrate a good solution in EF.

**Comment by yv989c** [comment]
@mkalinski93 @ErikEJ you will find [QueryableValues](https://github.com/yv989c/BlazarTech.QueryableValues) useful.

**Comment by mkalinski93** [comment]
okay, I think with the answers so far, I could get something working. Thank you for your time and good luck @roji finding a good solution 👍
