### ISSUE TITLE
[Inheritance] INSERT derived class as base class

### ISSUE THREAD

**Issue by SuRGeoNix** [dotnet/efcore#29637]
Hi, shouldn't be able to save C as B in db?
I've also noticed that INSERT statement will send NULLs properties while I was make them null to avoid sending them.

```csharp
class A {}
class B : A {}
class C : B {}

DbSet<A> As
DbSet<B> Bs
DbSet<C> Cs

C c = new();

dbContext.Bs.Add(c);
```

Thanks,
John

### Include provider and version information
EF Core version: 7
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
> Hi, shouldn't be able to save C as B in db?

This works for me, see the minimal code sample below. If it isn't working for you, please tweak the sample below to show it failing, or a runnable, minimal sample of your own.

> I've also noticed that INSERT statement will send NULLs properties while I was make them null to avoid sending them.

You'll need to submit a runnable code sample for us to see what exactly you're doing.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

C c = new();

ctx.Bs.Add(c);
await ctx.SaveChangesAsync();

public class BlogContext : DbContext
{
    public DbSet<A> As { get; set; }
    public DbSet<B> Bs { get; set; }
    public DbSet<C> Cs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite(@"Filename=/tmp/db.sqlite")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class A
{
    public int Id { get; set; }
    public string? Name { get; set; }
}

public class B : A
{
    public int BProp { get; set; }
}

public class C : B
{
    public int CProp { get; set; }
}
```

</details>

**Comment by SuRGeoNix** [comment]
Hi @roji and thanks for your quick response. I run your sample code and the Discriminator in the db is C not B.

I will give you also the INSERT log (mainly for NULLs, you can also see that inserts Movie instead of Video for Discriminator that I was expecting)

```
16.38.42.205 | Debug | [Flyleaf] [DB] dbug: 21/11/2022 16:38:42.205 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[@p0=NULL (DbType = Int64), @p1=NULL (DbType = DateTime), @p2='5.1(side)' (Size = 9), @p3='EAC3' (Size = 4), @p4='English' (Size = 7), @p5='48000' (Nullable = true), @p6=NULL (DbType = Int32), @p7='2022-11-21T14:38:41.8055828Z' (DbType = DateTime), @p8=NULL (DbType = Int64), @p9=NULL, @p10='Movie' (Nullable = false) (Size = 5), @p11='26619840000', @p12=NULL (DbType = Int32), @p13=NULL, @p14=NULL (DbType = Int32), @p15=NULL (DbType = Int32), @p16=NULL (DbType = Int32), @p17=NULL (DbType = Int32), @p18=NULL (DbType = Int32), @p19=NULL (DbType = Int32), @p20=NULL (DbType = Int32), @p21=NULL (DbType = Int32), @p22=NULL (DbType = DateTime), @p23=NULL (DbType = Int32), @p24=NULL (DbType = Int32), @p25='0', @p26=NULL (DbType = Int32), @p27=NULL (DbType = Date), @p28=NULL (DbType = Int64), @p29=NULL (DbType = Int32), @p30=NULL (DbType = Double), @p31='Video Not Movie' (Nullable = false) (Size = 10), @p32=NULL, @p33='C:\VideoNotMovie.mkv' (Nullable = false) (Size = 89), @p34='H264' (Size = 4), @p35='23.976023976023978' (Nullable = true), @p36='960' (Nullable = true), @p37='1920' (Nullable = true)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Media" ("AD", "Accessed", "AudioChannels", "AudioCodec", "AudioLangs", "AudioSampleRate", "BackdropId", "Created", "CurTime", "Description", "Discriminator", "Duration", "EAS", "ESS", "EVS", "IAS", "IMDBId", "ISS", "IVS", "ImageId", "LandscapeId", "LogoTextId", "Modified", "MovieCollectionId", "PI", "PlayCount", "PortraitId", "Released", "SD", "TMDBId", "TMDBRating", "Title", "TrailerUrl", "Url", "VideoCodec", "VideoFPS", "VideoHeight", "VideoWidth")
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37)
      RETURNING "Id";
```

**Comment by roji** [comment]
> I run your sample code and the Discriminator in the db is C not B.

That's the expected behavior - because you're inserting a C, not a B. Think of a DbSet like a polymorphic List that you insert stuff into; EF Core doesn't change the type of C into B just because you're inserting it into DbSet<B>.

> I will give you also the INSERT log [...]

That isn't a runnable code sample - it's always difficult to understand from snippets and partial descriptions what the actual question is.

But it's likely that you're using the TPH inheritance strategy (the default), which maps the entire hierarchy to a single database table. In that case, each row must contain columns for *all* properties in the hierarchy, and EF inserts NULLs into sibling columns. I suggest giving our [Inheritance doc page](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration) a good read to understand how this works.

If that's not what you're asking, please provide an actual runnable code sample, and describe what you think should be happening differently.

**Comment by SuRGeoNix** [comment]
That answers all my questions, thanks again @roji 

Just a note for NULLs (yes I'm using the default TPH) for performance and bandwidth reasons I guess it could avoid sending the NULL properties.
