### ISSUE TITLE
Cannot any method like AsRelational or ApplyMigrations to My DbContext

### ISSUE THREAD

**Issue by tabi786** [dotnet/efcore#2963]
Hi,
I have all references to Entity Framework 7 beta 8. but I cannot find any like AsRelational or ApplyMigrations to my DBContext. Am I missing something?

Regards.

Aftab Ahmad
![2015-08-31_07-28-03](https://cloud.githubusercontent.com/assets/11976604/9572646/62f9fd94-4fb2-11e5-8f07-0b690dff2d0a.png)

**Comment by ErikEJ** [comment]
AsRelational does no longer exist, and ApplyMigrations => Migrate

**Comment by tabi786** [comment]
Hi ErikEJ,
I am using 7.0.0-beta8-15538.
I can now see the Migrate() extension method. Thank you so much for your quick response.
Regards.
Aftab Ahmad
