### ISSUE TITLE
entityframeworkcore 7.0.0 is not compatible with netstandard2.1

### ISSUE THREAD

**Issue by sraban75** [dotnet/efcore#29639]
I want to update my application from Net Core 5.0 to 7.0, but I am facing this error.

**Comment by ajcvickers** [comment]
@sraban75 EF Core 7 requires .NET 6 or .NET 7.

**Comment by ajcvickers** [comment]
No. See [The Future of .NET Standard](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/).

**Comment by sraban75** [comment]
Thanks Man @ajcvickers
