### ISSUE TITLE
CompiledQuery with ExpressionTree

### ISSUE THREAD

**Issue by mkalinski93** [dotnet/efcore#29648]
Hey,

I just want to ask if I can pre compile a query by an ExpressionTree.
We have a generic Repository and I want to pre compile a "GetByKey" ExpressionTree for performance reasons.

I was able to create a basic ExpressionTree using this code:

```csharp
ParameterExpression pe = Expression.Parameter(typeof(T), "entity");
MemberExpression me = Expression.Property(pe, primaryKeyName);
ConstantExpression constant = Expression.Constant(primayKeyValue, primaryKeyType);
BinaryExpression body = Expression.Equal(me, constant);
Expression<Func<T, bool>> expressionTree = Expression.Lambda<Func<T, bool>>(body, new[] { pe });
``` 
All I know is the KeyName, the KeyType and the KeyValue - so it has to be working with generics, too.
For the EF.CompileQuery part, I need to have a TContext, TParam and a TResult.

How do I have to adapt the ExpressionTree to get it working or is it even possible to do that?
Backup plan is to have the Expression in each Entity, but that doesn´t seems right.

Thank you for your help

**Comment by roji** [comment]
You can pass the above predicate expression to a Where operator on an EF LINQ query, something like the following:

```c#
public T GetByKey<T>(int key) where T : class
{
    Expression<Func<T, bool>> predicate = ...;

    return Set<T>().Where(predicate).Single();
}
```

(this assumes the method is on your DbContext directly, otherwise you can pass in a context instance.

Note that this isn't "pre-compiled", it's just dynamically building the expression tree (EF does support something called [compiled queries](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#compiled-queries), but that's a high-perf feature which you're probably not looking for).

**Comment by mkalinski93** [comment]
CompiledQuery is actually the part I'm most interested in. AFAIK the CompiledQuery will cache the compiled expression and makes it execute faster, because it doesn't have to compile (heavy part) the expression anymore as it has been cached. This would be perfect in my scenario. My problem though is, that I don't have access to the "concrete" part.

All I have is the type (generic), the key name and the value (which can be literally any kind of key)

**Comment by roji** [comment]
@mkalinski93 EF always "compiles" your queries and caches the result; the second time you run a given LINQ query is considerably faster than running it the first time. Compiled queries optimize away even more up-front processing of the LINQ tree, but that mostly makes sense for very high-perf scenarios.

I highly recommend benchmarking first (use [BenchmarkDotNet](https://benchmarkdotnet.org)), and only choosing to use compiled queries if your benchmarks confirm that the difference is worth it. The drawback of using compiled queries is that you can no longer just put LINQ queries anywhere in your source code, so be sure you need them before using them.

**Comment by mkalinski93** [comment]
@roji we use BenchmarkDotNet to test our current implementation. 
I will follow your advice and try to do some benchmarks with CompiledQuery and the regular approach.

On the other hand, you´ve mentioned that " EF always "compiles" your queries and caches the result".
That sound familiar to me, but how long will the cache remain in memory or will the cache be disposed after the DbContext's scope ends?

In the end, our goal is to have a generic GetByKey<TEntity> method. I could up end having for each entity an ExpressionTree, but will the query be cached even with different key parameters? 
If so, then it really doens´t make sense to use CompileQuery, because the execution gains speed after the first execution.

**Comment by roji** [comment]
The cache is a singleton, so it's not bound to the DbContext's scope; it has a finite capacity and ejects based on usage. Each GetByKey would generate a different query, so would be cached separately; if you call GetByKey for the same entity type multiple times, subsequent times won't need to recompile (unless a large number of other executions occured in the meantime).

EF's internal query caching mechanisms generally work well for most scenarios, I'd advise not trying to optimize things prematurely before you know you have an actual problem.
