### ISSUE TITLE
Issue Running EF Core Bundle in DevOps Pipeline

### ISSUE THREAD

**Issue by dotnetron** [dotnet/efcore#29641]
I am able to generate an [EF Core Bundle](https://devblogs.microsoft.com/dotnet/introducing-devops-friendly-ef-core-migration-bundles/) in a single stage build pipeline and run it successfully using the [AzurePowerShell@5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) with the correct service connection that has the needed permissions to Azure SQL.

However, I am unable to get this work in a multi-stage pipeline that has the 1st stage build and product the migration artifact that gets published and the 2nd stage download the artifact and run it. It gives the following error:

![image](https://user-images.githubusercontent.com/25188913/203134098-9e1cb2d9-1280-4104-89d7-59bdee39f31e.png)

Any ideas where the issue might be? Below are snippets of both the working and non-working pipelines:

**Working Single Stage Pipeline**

`
trigger:
  batch: true
  branches:
    include:
    - main

stages:
  - stage: Build
    displayName: "Build/Test/Publish"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      buildConfiguration: "Release"

    jobs:
      - job: BuildPublish
        steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core sdk 6.0"
    inputs:
      version: "6.0.403" # replace this value with the version that you need for your project - https://github.com/dotnet/core/blob/master/release-notes/releases-index.json

  - task: DotNetCoreCLI@2
    displayName: "Install Dotnet EF Tool"
    inputs:
      command: custom
      custom: "tool"
      arguments: "install --global dotnet-ef --version 6.0.9"

  - task: NuGetToolInstaller@0
    displayName: "Install NuGet"
    inputs:
      checkLatest: true

        - template: "../../templates/CreateFolder.yml"
          parameters:
            folderPath: "$(Build.ArtifactStagingDirectory)/EFMigrations"

        - template: "../../templates/CreateMigrationBundle.yml"
          parameters:
            outputPath: "$(Build.ArtifactStagingDirectory)/EFMigrations"
            name: "Config"
            spnName: "DEV SPN"
            projectPath: "src/Services/Config/ODL.Config.API"
            connStr: $(ConfigDbConnectionString)
            context: "ConfigDbContext"

        - template: "../../templates/ApplyMigrationsBundle.yml"
          parameters:
            bundlePath: "$(Build.ArtifactStagingDirectory)/EFMigrations"
            name: "Config"
            spnName: "DEV SPN"
            connStr: $(ConfigDbConnectionString)

        - powershell: |
            Write-Host "##vso[build.addbuildtag]Completed"
`
**CreateMigrationBundle.yml**

`
parameters:
  - name: name
    type: string
  - name: spnName
    type: string
  - name: context
    type: string
  - name: projectPath
    type: string
  - name: connStr
    type: string
  - name: outputPath
    type: string

steps:
  - task: AzurePowerShell@5
    displayName: "Create EF Migrations Bundle - ${{ parameters.name }}"
    inputs:
      azureSubscription: "${{ parameters.spnName }}"
      scriptType: "inlineScript"
      azurePowerShellVersion: latestVersion
      inline: "dotnet ef migrations bundle --verbose --configuration EFBundle --context ${{ parameters.context }} --project ${{ parameters.projectPath }} --output ${{ parameters.outputPath }}/${{ parameters.name }}_efbundle.exe"
    env:
      ConnectionStrings__DefaultConnection: ${{ parameters.connStr }}
`

**ApplyMigrationsBundle.yml**

`
parameters:
  - name: name
    type: string
  - name: spnName
    type: string
  - name: connStr
    type: string
  - name: bundlePath
    type: string

steps:
  - task: AzurePowerShell@5
    displayName: "Apply EF Migrations Bundle - ${{ parameters.name }}"
    inputs:
      azureSubscription: "${{ parameters.spnName }}"
      scriptType: "inlineScript"
      azurePowerShellVersion: latestVersion
      inline: "${{ parameters.bundlePath }}/${{ parameters.name }}_efbundle.exe --verbose --connection '${{ parameters.connStr }}'"
    env:
      ConnectionStrings__DefaultConnection: ${{ parameters.connStr }}
`

**Non-Working Multi-Stage Pipeline**

`
trigger:
  batch: true
  branches:
    include:
    - release
    exclude:
    - main
    - users/*

stages:
  - stage: "CI"
    displayName: "CI: Build Artifacts"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      buildConfiguration: "Release"
    jobs:
      - job: BuildPublish
        steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core sdk 6.0"
    inputs:
      version: "6.0.403" # replace this value with the version that you need for your project - https://github.com/dotnet/core/blob/master/release-notes/releases-index.json

  - task: DotNetCoreCLI@2
    displayName: "Install Dotnet EF Tool"
    inputs:
      command: custom
      custom: "tool"
      arguments: "install --global dotnet-ef --version 6.0.9"

  - task: NuGetToolInstaller@0
    displayName: "Install NuGet"
    inputs:
      checkLatest: true

        - template: "../templates/CreateFolder.yml"
          parameters:
            folderPath: "$(Build.ArtifactStagingDirectory)/EFMigrations"

        - template: "../templates/CreateMigrationBundle.yml"
          parameters:
            outputPath: "$(Build.ArtifactStagingDirectory)/EFMigrations"
            name: "Config"
            spnName: "STG SPN"
            projectPath: "src/Services/Config/ODL.Config.API"
            connStr: $(STG_ConfigDbConnectionString)
            context: "ConfigDbContext"

        - publish: "$(Build.ArtifactStagingDirectory)/EFMigrations"
          displayName: "Publish Artifacts - EFMigrations"
          artifact: "EFMigrations" # output artifact named EFMigrations

        - powershell: |
            Write-Host "##vso[build.addbuildtag]Completed"

  - stage: "CDStage"
    dependsOn: "CI"
    displayName: "CD: Deploy to Staging"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      buildConfiguration: "Release"
    jobs:
    - deployment: "STG"
      displayName: "Deploy to Staging"
      environment: "STG"
      strategy:
        runOnce:
          deploy:
            steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core sdk 6.0"
    inputs:
      version: "6.0.403" # replace this value with the version that you need for your project - https://github.com/dotnet/core/blob/master/release-notes/releases-index.json

  - task: DotNetCoreCLI@2
    displayName: "Install Dotnet EF Tool"
    inputs:
      command: custom
      custom: "tool"
      arguments: "install --global dotnet-ef --version 6.0.9"

  - task: NuGetToolInstaller@0
    displayName: "Install NuGet"
    inputs:
      checkLatest: true

            - template: "../templates/ApplyMigrationsBundle.yml"
              parameters:
                bundlePath: "$(Pipeline.Workspace)/EFMigrations"
                name: "Config"
                spnName: "STG SPN"
                connStr: $(STG_ConfigDbConnectionString)

            - powershell: |
                Write-Host "Deployment to STAGING completed."
`

Thanks!

**Comment by ErikEJ** [comment]
You should really share your pipeline if you want help.

Maybe building on Windows and executing on Linux??

**Comment by dotnetron** [comment]
I have updated my original post and included the details on the pipelines.

**Comment by dotnetron** [comment]
So, I added a step to zip up the bundle exe files before publishing the artifact in CI stage of my build pipeline and downloading and unzipping them before running in the CD stage and now it is working. So I am guessing the publish artifacts step in the pipelines is messing up the file that is downloaded in the deploy stage somehow?
