### ISSUE TITLE
Performance regression in model building in Entity Framework Core 7

### ISSUE THREAD

**Issue by MaQy** [dotnet/efcore#29642]
Hi,

I have just migrated an application to Entity Framework Core 7 and noticed that executing the migrations for a new database takes twice or even three times longer than with Entity Framework Core 6. As far as I could see, adding interceptors, the actual SQL statements perform roughly the same, it's the time between migrations that takes longer (I guess building the operations, but I didn't go that deep).

I created a repo with a very simple project to showcase this scenario: https://github.com/MaQy/EfCoreMigrationsBenchmark

Even with just 5 migrations, 4 of them pretty small, the issue can be seen according to the results I got:

| Method |  Runtime |       Mean |    Error |   StdDev |
|------- |--------- |-----------:|---------:|---------:|
|   Test | .NET 6.0 |   547.9 ms | 302.9 ms | 200.4 ms |
|   Test | .NET 7.0 | 1,412.9 ms | 421.2 ms | 278.6 ms |

### Include provider and version information

EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11 21H2
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
Any chance you can create a SQL migration script for both versions and post the results? (`dotnet ef migrations sql`)

**Comment by MaQy** [comment]
Sure, here you can find both SQL files in the repository I shared:

https://github.com/MaQy/EfCoreMigrationsBenchmark/blob/master/migrations_6.0.11.sql
https://github.com/MaQy/EfCoreMigrationsBenchmark/blob/master/migrations_7.0.0.sql

As I mentioned in my initial post, the SQL statements are basically the same and take the same time to execute. It's the time between migrations that takes longer. In the traces I got from my own application with interceptors, EF Core 6 takes around 200-300 ms between migrations (that is, from the last SQL statement of a migration to the first SQL statement of the following one), while EF Core 7 takes around 700-1000 ms. I also added the script generation into the benchmark and the overhead is clearly visible:

|         Method |  Runtime |        Mean |     Error |    StdDev |
|--------------- |--------- |------------:|----------:|----------:|
|      Migration | .NET 6.0 |   467.22 ms |  7.899 ms | 28.819 ms |
| GenerateScript | .NET 6.0 |    83.00 ms |  0.531 ms |  1.902 ms |
|      Migration | .NET 7.0 | 1,304.72 ms | 10.119 ms | 36.918 ms |
| GenerateScript | .NET 7.0 |   953.80 ms |  4.492 ms | 16.101 ms |

**Comment by roji** [comment]
Thanks @MaQy, I can indeed see that something is wrong and will investigate.

**Comment by roji** [comment]
I think I found it; when generating the migration script twice, I'm seeing Property.GetContainingForeignKeys called around 330 million times. The bulk of the calls seem to happen from Property.GetValueConverter, where #29073 added [this for loop](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/Internal/Property.cs#L671). It seems that in certain conditions we may be looping 10000 times for no reason.

The same thing also seems to be happening in [GetProviderClrType](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/Internal/Property.cs#L750), which takes up 100 million of the 330 million calls.

/cc @AndriySvyryd

**Comment by samisq** [comment]
+1 for this. We're experiencing the exact same issue after upgrading to .NET7 & EF7. We're using Npgsql.EntityFrameworkCore provider. Migration now takes at least twice as long for
