### ISSUE TITLE
Temporal table - TemporalAsOf() - nested children entities on navigation property not loaded

### ISSUE THREAD

**Issue by KamilMakowski** [dotnet/efcore#29644]
When doing select on temporal table with `.TemporalAsOf()` children elements are not loaded on navigation property.
When doing exactly same query but without `.TemporalAsOf()`, children elements are loaded properly.

Findings (last most important):
* Changes in history table doesn't matter, might be empty - same results
* Making joins via `.Include()` or `.Join()` doesn't matter (example in code) - same results
* Children elements are fetched correctly as we are getting them on the root level, but not in the children naviagtion property
* When Including children property, we are getting one level of nested child (only one), when including for the 2nd time (`.ThenInclude().ThenInclude()`) we are getting two level of nested children and so on.
* When getting SQL via `.ToQueryString()` for two type of queries (with and without `.TemporalAsOf()`) and then running this SQL on DB, results are exactly the same, but C# objects look different (children list navigation property is null for query with `.TemporalAsOf()`). So it looks like there is a problem with mapping back results from SQL to C# object

Code example:
Create DB and set connection string, create and run migration, set breakpoint and check for Form[0].Questions[0].ChildQuestions

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

public class Program
{
    public static void Main()
    {
        using var context = new FormsContext();
        
        // Select include history method 1
        var selectWithHistory = context.Forms
            .TemporalAsOf(DateTime.Parse("2042-11-21 12:00:20"))
            .Include(f => f.Questions)
            .Where(x => x.Name == "Form 1").ToList();
        
        // Select include history method 2
        var forms = context.Forms.TemporalAsOf(DateTime.Parse("2042-11-21 12:00:20"));
        var questions = context.Questions.TemporalAsOf(DateTime.Parse("2042-11-21 12:00:20"));
        var selectWithHistory2 = forms.Join(questions, form => form.Id, question => question.FormId, (form, question) => new
        {
            FormName = form.Name,
            Questions = form.Questions
        }).Where(x => x.FormName == "Form 1").ToList();
        
        // Select without history
        var selectPlain = context.Forms
            .Include(f => f.Questions)
            .Where(f => f.Name == "Form 1").ToList();
    }
    
    public class Form
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Question> Questions { get; set; }
    }
    
    public class Question
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? ParentId { get; set; }
        public Question ParentQuestion { get; set; }
        public virtual Form Form { get; set; }
        public int FormId { get; set; }
        public ICollection<Question> ChildQuestions { get; set; }
    }
    
    public class FormsContext : DbContext
{
    public DbSet<Form> Forms { get; set; }
    public DbSet<Question> Questions { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"CONNECTION_STRING_HERE");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Form>()
            .ToTable("Forms", b => b.IsTemporal());
        modelBuilder.Entity<Form>()
            .HasMany(e => e.Questions)
            .WithOne(e => e.Form)
            .HasForeignKey(e => e.FormId);
        
        modelBuilder.Entity<Question>()
            .ToTable("Question", b => b.IsTemporal());
        modelBuilder.Entity<Question>()
            .HasMany(e => e.ChildQuestions)
            .WithOne(e => e.ParentQuestion)
            .HasForeignKey(e => e.ParentId);
        
        // seed data
        modelBuilder.Entity<Form>().HasData(new Form
        {
            Id = 1,
            Name = "Form 1"
        });
        modelBuilder.Entity<Question>().HasData(new Question
        {
            Id = 1,
            Name = "Question 1",
            FormId = 1
        });
        modelBuilder.Entity<Question>().HasData(new Question
        {
            Id = 2,
            Name = "Question 2",
            FormId = 1,
            ParentId = 1
        });
        modelBuilder.Entity<Question>().HasData(new Question
        {
            Id = 3,
            Name = "Question 3",
            FormId = 1,
            ParentId = 2
        });
    }
}
}

```

EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 7.0
Operating system: Win 10 / MacOs
IDE: Rider 2022.2.4

**Comment by maumar** [comment]
the reason for the discrepancy is that queries using temporal operations are executed in NoTracking mode (we don't want to pollute the change tracker with historical data). So the ChildQuestions are not automatically populated. In the plain query we run with query as tracking, so all the objects found in Question collection are populated everywhere else.

To solve this you need to explicitly include the ChildQuestions navigation also:

```cs
        var selectWithHistory = context.Forms
            .TemporalAsOf(DateTime.Parse("2042-11-21 12:00:20"))
            .Include(f => f.Questions)
            .ThenInclude(x => x.ChildQuestions)
            .Where(x => x.Name == "Form 1").ToList();

```


There is also an issue tracking EF using NoTrackingWithIdentityResolution, which will not pollute the state manager but will still populate the ChildQuestion navigation in your case. - https://github.com/dotnet/efcore/issues/27289
