### ISSUE TITLE
How to inject data into a my dbcontext to dynamically configure the database?

### ISSUE THREAD

**Issue by sturlath** [dotnet/efcore#29657]
**Scenario**
Based on where my code is running (cloud/on-prem) I am trying to **conditionally configure** (`ApplyConfiguration`)  my data in `OnModelCreating` but am having problem injecting that data into the derived class.

**Question**
How can I get dynamic data injected into my context class, like [here in my example](https://github.com/sturlath/InjectDataToDbContext/blob/9b2e4b6d5efca9f3f6b4ae0566b16357e065dd7d/EFData/Model.cs#L26)?

Or can I configure the dbContext and/or `ApplyConfiguration `in some other way to achieve this?

**Comment by roji** [comment]
@sturlath you'd typically construct your DbContext type with whatever information you need in order to dynamically build your context (e.g. your IMyConfiguration), store that in fields, and then look at those fields from OnModelCreating (see [this doc page](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model)).

If you do this, make sure to set up a correct IModelCacheKeyFactory to make sure the models get cached correctly.

**Comment by sturlath** [comment]
Thanks @roji 

I **guess** (_if I understood you correctly_) that **caching is not an issue** in my case since the code will **either** be run in the cloud **or** on prem and use their own models **each and every time** it gets run. Never switching between configuration after it runs.

 So, the value it gets from e.g., an `.env` file at startup time will just determine the model configuration used.

__________________________
Then to finish answering my own question on how to get dynamic values into the `OnModelCreating` method I have updated my code so that now I can get the information either from `.env` file or by injecting it into the `GetService` method on the DbContext.

So, either[ like this](https://github.com/sturlath/InjectDataToDbContext/blob/ac7434486270e994f3c2557e3ab2291214c17704/EFData/Model.cs#L20)

```csharp 
IsCloud = Environment.GetEnvironmentVariable("CLOUD");
```

or using `GetService` like [this](https://github.com/sturlath/InjectDataToDbContext/blob/ac7434486270e994f3c2557e3ab2291214c17704/EFData/Model.cs#L34)

```csharp 
var myConfiguration = this.GetService<IMyConfiguration>();
```

**Comment by roji** [comment]
> I guess (if I understood you correctly) that caching is not an issue in my case since the code will either be run in the cloud or on prem and use their own models each and every time it gets run. Never switching between configuration after it runs.

Right. If you know you'll only ever have one actual model in a running application instance, then you can ignore the caching problem.

> IsCloud = Environment.GetEnvironmentVariable("CLOUD");

That's possible, yes.

> var myConfiguration = this.GetService<IMyConfiguration>();

If this line of code is inside your context's OnModelCreating, as it seems to be, then no - that doesn't work. DbContext.GetService accesses EF's internal service provider, which is distinct from the service provider used e.g. in an ASP.NET application.

**Comment by sturlath** [comment]
> If this line of code is inside your context's OnModelCreating, as it seems to be, then no - that doesn't work. DbContext.GetService accesses EF's internal service provider, which is distinct from the service provider used e.g. in an ASP.NET application.

It's actually working in my example (its returning read values from .env) , but I guess that is only because of the migrations being run from the ASP.NET application. I had tried to get it to work in the data project but had given up when a college of mine got it to work in there. 

I thought it was strange that it worked because of the comment on that method "_Resolves a service from the IServiceProvider exposed from a type that implements IInfrastructure_"... MyConfiguration doesn´t have anything like that.

**Comment by ajcvickers** [comment]
@sturlath 

It would be much more common, and more reliable, to use constructor injection:

```C#
    public IMyConfiguration? PhysicalStructureConfiguration { get; }

    public BloggingContext(IMyConfiguration physicalStructureConfiguration)
    {
        PhysicalStructureConfiguration = physicalStructureConfiguration;
        // ...
    }
```

@roji

> DbContext.GetService accesses EF's internal service provider, which is distinct from the service provider used e.g. in an ASP.NET application.

There is a bridge to the external service provider, but it doesn't always work as expected.

**Comment by roji** [comment]
Thansk @ajcvickers, need to learn more about that.
