### ISSUE TITLE
Could not load file or assembly Microsoft.SqlServer.Server

### ISSUE THREAD

**Issue by TobiasLaving** [dotnet/efcore#29658]
Hello, 

We recently upgraded to EF 7.0.0 but sometimes hit a strange issue loading Microsoft.SqlServer.Server assembly:
```
Could not load file or assembly 'Microsoft.SqlServer.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'. A device attached to the system is not functioning.
```

This only happens on linux app service hosted on azure and seems to happen every now and again, maybe 3/10 deployments
No idea what could be causing it, unable to reproduce locally

Sorry for the terrible issue, but any guidance on how troubleshoot would be appreciated.

**Comment by roji** [comment]
"A device attached to the system is not functioning." soundsl ike an OS or I/O error that doesn't have anything to do with EF Core, SqlClient or .NET... I'd try to see if you access that assembly via 
external means.

**Comment by TobiasLaving** [comment]
That is a good point.
It does not happen when running EF 6, but I guess the underlying issue is Microsoft.SqlServer.Server assembly
Funny enough, the application appear to work afterwards, only the first time running the code it works, so probably some kind of timing issue.
I have yet to find a good place to post bugs for that assembly, do you have any idea ?

**Comment by ErikEJ** [comment]
You should provide a repro in the dotnet/sqlclient repository
