### ISSUE TITLE
Support for TBT and TBC in ExecuteUpdate(Async) & ExecuteDelete(Async)

### ISSUE THREAD

**Issue by aredfox** [dotnet/efcore#29666]
Will ExecuteUpdate(Async) and ExecuteDelete(Async) get support for TBT (Table-Per-Type) and TBC (Table-Per-Concrete Type) mappings. Don't get me wrong, I applaud this feature and welcome it with both hands, but I think this would make sense for readability & uniformity/consistency perspective when it also would support TBT & TBC scenarios.

Furthermore, larger or complex scenarios / projects who would be able to take big advantage of this might actually now feel left out because they opted for another inheritance strategy and still use the vulnerable magic strings of ExecuteSQLRaw or move to Dapper for some scenarios then. 

Again, I highly appreciate the idea - I just hope extending it to the other inheritance strategies is on the roadmap somewhere. Hence my second questions related: is there a way to look at the roadmap for EF Core 7.x or EF Core 8.0, as the link on the current github page redirects to https://learn.microsoft.com/nl-nl/ef/core/what-is-new/ and the link itself on the main readme page of dotnet/efcore here actually points to a /roadmap endpoint, ref: "https://learn.microsoft.com/nl-nl/ef/core/what-is-new/roadmap".

**Comment by roji** [comment]
Duplicate of #28520
