### ISSUE TITLE
DB ContextPooling no Performance gain

### ISSUE THREAD

**Issue by AlexanderFrit** [dotnet/efcore#29661]
Hey,

We tried to replicate your Benchmark for ContextPooling and followed [this](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Benchmarks/ContextPooling.cs) example.
We expected performance gains like in your [documentation](https://learn.microsoft.com/en-gb/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling).
<img width="890" alt="image" src="https://user-images.githubusercontent.com/98812209/203531147-47849acc-c650-4c8b-975c-e7a00472f8ac.png">
But instead saw no performance increase. 
<img width="861" alt="image (1)" src="https://user-images.githubusercontent.com/98812209/203531365-79beeacd-059d-468f-a0aa-14fa622322a4.png">

This is our Code
```
[MemoryDiagnoser]
public class TestBenchmark {

    private DbContextOptions<BenchmarkDbContext> _options;
    private PooledDbContextFactory<BenchmarkDbContext> _pooledDbContextFactory;


    [GlobalSetup]
    public void Setup() {
        
        string nativeSqlConnectionString = "Server=localhost;User Id=sa;Password=*********;Database=TestA;Persist Security Info=true;";

        _options = new DbContextOptionsBuilder<BenchmarkDbContext>()
            .UseSqlServer(nativeSqlConnectionString).Options;

        _pooledDbContextFactory = new PooledDbContextFactory<BenchmarkDbContext>(_options);
    }

    [Benchmark]
    public List<Product> WithoutContextPooling() {
        using var context = new BenchmarkDbContext(_options);
        return context.Set<Product>().ToList();
    }

    [Benchmark]
    public List<Product> WithContextPooling() {
        using var context = _pooledDbContextFactory.CreateDbContext();
        return context.Set<Product>().ToList();
    }
}
```

Are we missing something?

**Comment by roji** [comment]
@AlexanderFrit each method invocation in your benchmark is taking around 330 **milliseconds**, which is a very long time for a database query; I'm guessing that there are a lot of Products in your database, and you're loading them all - note that ~130MB heap allocation **per invocation**. In that kind of super-heavy query, context pooling is unlikely to make any difference.

**Comment by AlexanderFrit** [comment]
Ok, we ran some more Benchmarks and yes, you are right, Context Pooling has a way harder impact on smaller Queries.
