### ISSUE TITLE
Enable JsonColumn JSON_UNESCAPED_UNICODE

### ISSUE THREAD

**Issue by romanov** [dotnet/efcore#29699]
Hello,

when i try to save data into JsonColumn i'm getting the escaped characters in the database.

Example:
![image](https://user-images.githubusercontent.com/644179/204565007-df219773-78e4-44b2-b5d1-9717e8f2b49e.png)

Is it possible to disable escaping and save text as it is in Unicode?

Thank you.

**Comment by maumar** [comment]
it's not possible at the moment, we should enable this scenario as part of https://github.com/dotnet/efcore/issues/28043

**Comment by romanov** [comment]
Thank you, i will close the issue.
