### ISSUE TITLE
Define DeleteBehavior from the child class.

### ISSUE THREAD

**Issue by eestein** [dotnet/efcore#29698]
The only reason why I'm posting it here and not as question, is because I've already posted on SO ([link here](https://stackoverflow.com/questions/74520404/how-to-define-deletebehavior-in-the-class-inheriting-from-another)) 8 days ago and got no answers nor comments. So, I'm *assuming* this functionality doesn't exist, if it does, please explain how it works.

Define DeleteBehavior from the child class.

I know I could use `DeleteBehavior` attribute in a property, the problem is that property is inherited.

I have the following classes:

````csharp
[Table("Profiles")]
public class Profile 
{
    public Guid Id { get; set; }
    // ...
}

[Table("Agents")]
public class AgentProfile : Profile
{
    // ...
}
````

And this is the migration generated:

``` lang-csharp
migrationBuilder.CreateTable(
    name: "Agents",
    columns: table => new
    {
        Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
        // ...
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Agents", x => x.Id);
        // ...
        table.ForeignKey(
            name: "FK_Agents_Profiles_Id",
            column: x => x.Id,
            principalTable: "Profiles",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    });
```

The problem is this line:

`onDelete: ReferentialAction.Cascade);`

How do I mark that specific FK as Restrict? I know how to do it for explicit relationships like:

``` lang-csharp
EntityTypeBuilder<AgentProfile>
    .HasMany(a => a.Cases)
    .WithOne(c => c.Agent)
    .OnDelete(DeleteBehavior.Restrict);
```

But I couldn't find out how to do that for my scenario (the inherited relationship). The migration is created (a weird behavior from EF Core IMO, I think the error should be thrown during the migration creation), but I can't update the database because I get the error:

> Introducing FOREIGN KEY constraint 'FK_Agents_Profiles_Id' on table 'Agents' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors

**I know I could simply change the generated migration to Restrict, but I don't want to do that**, otherwise it'll be an extra step, using the FluentApi would be ideal. **I also understand MS SQL Server has its own restrictions, but I'm assuming it's possible to define this behavior without having to change the auto generated migration.**
How can I do so using an attribute or the FluentApi?

Using EF Core 7.

**Comment by ajcvickers** [comment]
@eestein I've read this through several times and unfortunately I don't know what it is you are asking for. Can you attach a small, runnable project or post a small, runnable code listing that shows what your entity types look like, how they are configured currently, what the database schema is that you are hoping to achieve.

**Comment by ajcvickers** [comment]
@eestein For example, what do the relationships look like? How are the entity types and relationships mapped to the database?

**Comment by eestein** [comment]
@ajcvickers ok, I'll create a repro later today and post here.
Thank you for now

**Comment by eestein** [comment]
Hi, @ajcvickers 
Sorry about the delay, I thought I'd had time, but...

Please find the repro project [here](https://easyupload.io/zqtg5c). There you'll see the Id is marked as Cascade. I'd like an option to mark that as Restrict from the class (using an attribute) or from `EntityTypeBuilder` as stated in my original question. Hopefully you can help me!

Please, let me know if you need more info.

**Comment by ajcvickers** [comment]
@eestein 

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
        .Entity<AgentProfile>()
        .HasOne<Profile>()
        .WithOne()
        .HasForeignKey<AgentProfile>(e => e.Id)
        .OnDelete(DeleteBehavior.Restrict);
}
```

See https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#tpt-cascade-delete

**Comment by eestein** [comment]
@ajcvickers thank you, sir! :)
In my fiddling I almost got to that solution, glad I wasn't too far away.

Thanks again!
