### ISSUE TITLE
T4 - How to change file names

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#29700]
When following this guide:
[https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-clil)
How do you modify filenames to match modifications to the class names in "EntityType.t4"

**Comment by bricelam** [comment]
Duplicate of #29541
