### ISSUE TITLE
GetRelationalModel() does not return any Stored Procedures?

### ISSUE THREAD

**Issue by deanparkr** [dotnet/efcore#29701]
I am using EF Core 7.0.0 and have an existing database I have reverse engineered with EF Core PowerTools. I am now wanting to get a list of all the Functions and Stored Procedures in the project. 

For Functions this is easy:

```C#
ctx.Model.GetRelationalModel().Functions;
```
But when I do:

```C#
ctx.Model.GetRelationalModel().StoredProcedures;
```

It returns an empty collection.

![image](https://user-images.githubusercontent.com/718161/204611615-d992eb77-67bc-4eb1-9421-1973ea50eec4.png)

There are plenty of stored procs in the project as created by EF Core Power Tools and they are located in my _xxxContextProcedures.cs_ file

The documentation here: [ https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.irelationalmodel.storedprocedures?view=efcore-7.0](url)

Says:

"IRelationalModel.StoredProcedures Property:
Returns all stored procedures contained in the model."

However I cannot get it to return anything and am wondering why this would be?

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET 6.0
Operating system:
IDE: e.g. Visual Studio 2022 17.4.1

**Comment by roji** [comment]
IRelationalModel.StoredProcedures contains stored procedures that have been configured via the new EF 7.0 [stored procedure mapping feature](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#stored-procedure-mapping). I'm pretty sure the EF Core Power Tools doesn't scaffold that - it probably only scaffolds the SQL definitions for those sprocs, not the new 7.0 model configuration as per the docs above).

/cc @ErikEJ

**Comment by ErikEJ** [comment]
Correct. Not sure how Power Tools would be able to do that anyway.

**Comment by deanparkr** [comment]
Ah I see. Thanks for setting me right on this understanding. Appreciated!
