### ISSUE TITLE
T4 template removes implicit usings

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#29713]
T4 template removes implicit usings

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ErikEJ** [comment]
@Varorbc I think no all development environments support this equally well

**Comment by ErikEJ** [comment]
@Varorbc You can just modify the T4 template EntityType.t4

**Comment by ajcvickers** [comment]
Note from triage: This is not something we plan to implement in the default templates since involves significant plumbing. On the other hand, it's very easy to edit the application template to do this for a well-known list of namespaces.
