### ISSUE TITLE
Signing of assemblies with a strong name

### ISSUE THREAD

**Issue by hkoestin** [dotnet/efcore#2971]
Are there any plans on when you will release signed assemblies?

I would need to have signed assemblies in place for my release builds, but do not really want to sign them manually all the time, I get a fresh nightly build.

**Comment by rowanmiller** [comment]
Just following up with the Microsoft.Framework.* package owners as EF is dependent on these being strong named before we can be. I've started a follow up on https://github.com/aspnet/EntityFramework/issues/999 so we can continue discussion on timeframe etc. there.

**Comment by hkoestin** [comment]
Is there any progress?
See https://github.com/aspnet/EntityFramework/issues/999#issuecomment-143674933
