### ISSUE TITLE
Enable non-tracking for specific Entity

### ISSUE THREAD

**Issue by Deivisson** [dotnet/efcore#29719]
Hi everyone!

I have a situation where I have an Entity that can do only ReadOnly queries against the database table... To avoid passing in all queries **.AsNoTracking()**, I'd like to know if is possible to configure that entity to never be tracked?

EF Core version: 6
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 6.0)
Operating system: Linux
IDE: (VsCode)

**Comment by ErikEJ** [comment]
Make it Keyless?

**Comment by Deivisson** [comment]
@ErikEJ thank you for answering me!!

But, If make it keyless, I lose the option to retrieve the record by its ID, using the Find methods.

My entity
```
...
builder.ToTable("customers", "shared", t => t.ExcludeFromMigrations()).HasNoKey();
...

```

Generic method to check if the entity is Active
```
public virtual bool ActiveEntity<TCustomEntity, TKey>(TKey key)
      where TCustomEntity : class, IEntity
      where TKey : notnull
    {
      var entity = GetDbContext().Set<TCustomEntity>().Find(key);
      var property = entity?.GetType().GetProperty("Status");
      var value = property?.GetValue(entity);
      if (value == null) return false;
      return (short)value == StatusGeneric.Active.Id;
    }

   // checking if the entities are Activity
  bool fooIsActive = .ActiveEntity<FooReadOnlyEntity, long?>(1));
  bool barIsActive = .ActiveEntity<BarReadOnlyEntity, long?>(999));
```
Below is the error when set entity to keyless
```
"exception": {
        "ClassName": "System.NullReferenceException",
        "Message": "Object reference not set to an instance of an object.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)\n   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)\n   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)\n   at Linear.Infrastructure.Common.BaseRepository`1.ActiveEntity[TCustomEntity,TKey](TKey key) in /code/src/submodules/infrastructure/Common/BaseRepository.cs:line 118\n   at
```

**Comment by roji** [comment]
> But, If make it keyless, I lose the option to retrieve the record by its ID, using the Find methods.

There's no particular reason to use Find if you're not going to involve change tracking (which doesn't make sense if the entities are read-only). You can simply query by the ID using `Single(x => x.Id == "something")` (but without having EF treat that property as a key).

**Comment by ajcvickers** [comment]
Notes from triage: Read-only entities are tracked by #7586. We don't plan to make it possible to mark entities as no-tracking.
