### ISSUE TITLE
Can we make IEntityType.DynamicallyAccessedMemberTypes and constants alike public?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#29714]
I'd like to reuse these constants when preparing my code for trimming.

**Comment by roji** [comment]
@voroninp these are definitely not meant for public consumption. You can just copy the definition out to your own code.

**Comment by voroninp** [comment]
That's what I did, but what's the harm of exposing it? Trim Analyzer will force me to apply same values in case I wrap `Set<TEntity>` method:
```
public virtual DbSet<TEntity> Set<[DynamicallyAccessedMembers(IEntityType.DynamicallyAccessedMemberTypes)] TEntity>()
```

**Comment by roji** [comment]
Trimming support in EF is experimental (and partial) at this stage - we definitely don't want to expose any public APIs at this point, which it would be a breaking change to change/remove later. You can very easily just copy that definition.
