### ISSUE TITLE
EF migration runner still checks for Configure()+ConfigureServices() if project is a vnext *PCL*

### ISSUE THREAD

**Issue by kaelanfouwels** [dotnet/efcore#2972]
The EntityFramework.Commands migration runner still checks whether a `Startup.cs` with a `Configure` and `ConfigureServices` is present if the project is a ASP.NET5 portable class library, (rather than a Web project) before it will run.

Adding a dummy `Startup.cs` with blank methods named the above solves the issue, but shouldn't be necessary.

Running it via `dnx . ef migration add -etc`
- With `ef` added as a command bound to `"EntityFramework.Commands"` in the `project.json.` as per usual.

**Comment by bricelam** [comment]
Dupe of #2867
