### ISSUE TITLE
Add overload to ToListAsync with an initial capacity.

### ISSUE THREAD

**Issue by mjkozicki** [dotnet/efcore#29720]
[ToListAsync<TSource>](https://github.com/dotnet/efcore/blob/089a035ecff8b066ec9ea0d51efeee652a1db4e5/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2298) creates a default capacity `List<TSource>()`. When the is size of the result set is large, this can require several resizing operations on the `List` that may be unnecessary if the result set size can be reasonably predicted at compile time. Since there is a possibility that the operation is cancelled, this may cause issues with an oversized `List`, but this is a calling implementation to determine by a developer.

Add an overload for [ToListAsync<TSource>](https://github.com/dotnet/efcore/blob/089a035ecff8b066ec9ea0d51efeee652a1db4e5/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2298) that allows for an initial capacity to be set similar to [new List(int capacity)](https://github.com/dotnet/corert/blob/c6af4cfc8b625851b91823d9be746c4f7abdc667/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L46).
```csharp
private const int DefaultCapacity = 4;

public static async Task<List<TSource>> ToListAsync<TSource>(
        this IQueryable<TSource> source,
        CancellationToken cancellationToken = default,
        int capacity = DefaultCapacity)
    {
        var list = new List<TSource>(capacity);
        await foreach (var element in source.AsAsyncEnumerable().WithCancellation(cancellationToken))
        {
            list.Add(element);
        }

        return list;
    }
```
This approach could also be applied to other async methods that create a collection with the default size.

**Comment by roji** [comment]
This can be implemented pretty trivially outside of EF Core, i.e. just allocate an array/list with the capacity you want, and then do a foreach over the results, adding them to your pre-allocated list.

Note that while ToListAsync is part of EF, ToList isn't; we generally try to keep symmetrry between the two unless there's a compelling reason to do so (which doesn't seem to be the case here, given that it's trivial to implement without the overload as above).
