### ISSUE TITLE
Allow stripping away all model building code to reduce application size

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#29755]
Since users can support precompiled models, model building code shouldn't be needed in runtime, and we can get rid of it to reduce application size. This is especially important for AOT, but isn't necessarily coupled to it.

EF invokes model building implicitly, i.e. there's no explicit gesture for building a model. This unfortunately means that normal trimming cannot detect that model building isn't being used in the application - unless we change EF's API and introduce a breaking change around this (e.g. a new API to trigger model building, without which implicit model building doesn't occur).

We can instead use a [feature switch](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md) to allow users to opt into stripping the model building code. This feature switch could be activated automatically when publishing to AOT.

**Comment by AndriySvyryd** [comment]
Fixed for AOT in d6fdc4da7946cb200165f052b40167f1450d0156
Feature switches for trimming are tracked by https://github.com/dotnet/efcore/issues/24901

**Comment by roji** [comment]
@AndriySvyryd d6fdc4da7946cb200165f052b40167f1450d0156 seems to be about SQLite, is it related to stripping away model building code?

**Comment by AndriySvyryd** [comment]
@roji  https://github.com/dotnet/efcore/commit/d6fdc4da7946cb200165f052b40167f1450d0156#diff-7d029030f0ec65e31737f68b1e654f060ae1d81db0da05bbd20acb6b27affe9cR89-R91 takes care of this
