### ISSUE TITLE
AutoTransactionBehavior change breaks under AWS RDS Aurora MySql Proxy -- throws DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by ericjpeters** [dotnet/efcore#29785]
AWS Aurora v2.x and v3.x MySql are not working properly with .NET 7 / Entity Framework 7 when connected to via an RDS Proxy.

EF 7 changed the behavior of SaveChanges() from wrapping the save in a transaction "Always"  to wrapping the save in a transaction "When Needed".   This change works great when connecting to Aurora directly (or to a local MySql instance), but fails when connecting to an RDS proxy targeting the same database.

There is an easy workaround -- simply add "Database.AutoTransactionBehavior = AutoTransactionBehavior.Always;" to the constructor of the EF 7 DbContext subclass, and everything clears up.   Without that, a DbUpdateConcurrencyException is sometimes (not always?) thrown.

I realize this is very likely not an EF 7 issue, but rather an AWS Aurora issue, and I have reported it to Amazon as well.   I'm reporting here in case it's an edge case which affects other proxies or systems that your team might want to investigate.  Hope it's helpful!

EF Core version: EF 7
Database provider: Pomelo
Target framework: .Net 7
Operating system: Win64
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
@ericjpeters can you provide a bit more context? How exactly is it failing?

The change from Always to WhenNeeded simply means that for a single SQL statement, SaveChanges just sends it without explicitly starting a transaction before and committing it afterwards (two additional roundtrips). It's hard to imagine that AWS Aurora has an issue with single SQL statements which aren't wrapped by an explicit transaction, so understanding the problem better would be helpful.

**Comment by ericjpeters** [comment]
I want to emphasize -- it's not simply AWS Aurora which demonstrates the issue, it's AWS Aurora MySQL when connecting through an AWS RDS Proxy.   Connecting directly to the Aurora instance works fine.   This is easily reproducible using Aurora v2.x and v3.x (MySql v5.4 and v8.0 compatible).   Also, my tests did a select and update before SaveChanges.

The error which is thrown is a DbUpdateConcurrencyException.

Here's an example of the output:
```
Executed DbCommand (86ms) [Parameters=[@__id_0='204' (Nullable = true)], CommandType='Text', CommandTimeout='60']
SELECT [field-list] FROM [table] WHERE [filters] AND (`a`.`id` = @__id_0) LIMIT 1
Context 'TestDataContext' started tracking 'SystemNotification' entity with key '{Id: 204}'.
Closing data reader to '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com'.
A data reader for '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com' is being disposed after spending 279ms reading results.
Closing connection to database '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com'.
Closed connection to database '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com' (6ms).
SaveChanges starting for 'TestDataContext'.
DetectChanges starting for 'TestDataContext'.
The unchanged property '[field]' was detected as changed from '[val-old]' to '[val-new]' and will be marked as modified for entity with key '{Id: 204}'.
The '[entity]' entity with key '{Id: 204}' tracked by 'TestDataContext' changed state from 'Unchanged' to 'Modified'.
DetectChanges completed for 'TestDataContext'.
Opening connection to database '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com'.
Opened connection to database '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com'.
Creating DbCommand for 'ExecuteReader'.
Created DbCommand for 'ExecuteReader' (0ms).
Initialized DbCommand for 'ExecuteReader' (2ms).
Executing DbCommand [Parameters=[@p1='204', @p0='2' (Nullable = true)], CommandType='Text', CommandTimeout='60']
UPDATE `[table]` SET `[field]` = @p0
WHERE `id` = @p1;
SELECT ROW_COUNT();
Executed DbCommand (15ms) [Parameters=[@p1='204', @p0='2' (Nullable = true)], CommandType='Text', CommandTimeout='60']
UPDATE `[table]` SET `[field]` = @p0
WHERE `id` = @p1;
SELECT ROW_COUNT();
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Closing data reader to '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com'.
A data reader for '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com' is being disposed after spending 40ms reading results.
Closing connection to database '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com'.
Closed connection to database '[db-name]' on server '[proxy-name].proxy-[proxyid].us-east-2.rds.amazonaws.com' (8ms).
An exception occurred in the database while saving changes for context type 'ConsoleApp1.TestDataContext'.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

Happy to provide more detail if it help.

**Comment by roji** [comment]
Can you provide a minimal code sample which reproduces this?

**Comment by ericjpeters** [comment]
Sure.   It's a little quick-n-dirty, but this is what I used to research the issue:

The line `this.Database.AutoTransactionBehavior = AutoTransactionBehavior.Always;` is not needed when targeting EF6, nor when targeting the MySql DB directly from EF7.   But when targeting the AWS RDS Proxy for an AWS Aurora DB, removing that line will demonstrate the issue.   This test was targeting the most recent Aurora v3.x (MySql v8.0), but I also replicated the issue (and workaround) against Aurora v2.x (MySql v5.4, if I remember correctly).

In case it's not obvious, this uses Pomelo - which I am fairly certain is not part of the problem.  I could be wrong about that assumption.

```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleApp1;

internal class App
{
    public const string ConnectionString = "[connection-string]";
    public const string DatabaseVersion = "8.0.23";

    public static IServiceProvider ServiceProvider { get; set; } = default!;
    private readonly Random _rand = new();

    internal async Task Run()
    {
        var ioc = new ServiceCollection();
        ioc.AddScoped<ILoggerFactory, ConsoleLoggerFactory>();
        ioc.AddDbContextPool<TestDataContext, TestDataContext>((_di, _optionsBuilder) =>
             {
                 var dbConfig = new DatabaseConfiguration();
                 dbConfig.ConfigureContext(_optionsBuilder);
             });

        ServiceProvider = ioc.BuildServiceProvider();
        var ef = ServiceProvider.GetRequiredService<TestDataContext>();

        SystemNotification? target = null;
        do
        {
            var id = _rand.Next() % 5000;

            target = await ef.SystemNotifications
                .Where(_ => _.RowState == RowStatuses.Normal)
                .FirstOrDefaultAsync(_ => _.Id == id);
        }
        while (target == default);

        if (target.SystemNotificationStatusType.HasValue)
        {
            var tmp = (int)target.SystemNotificationStatusType;
            tmp = 1 - (tmp - 1);
            tmp = tmp + 1;
            target.SystemNotificationStatusType = (SystemNotificationStatusTypes)tmp;
        }
        else
        {
            target.SystemNotificationStatusType = SystemNotificationStatusTypes.Unread;
        }

        await ef.SaveChangesAsync();
    }
}

public enum SystemNotificationStatusTypes
{
    Unread = 1,
    Read = 2
}

public enum RowStatuses
{
    Normal = 0,
    Deleted = 1
}

public enum SystemNotificationTypes
{
    System = 1
}

[Table("[table-name]")]
public class SystemNotification
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("RowState")]
    public RowStatuses RowState { get; set; } = RowStatuses.Normal;

    [Column("SystemNotificationTypeId")]
    public SystemNotificationTypes? SystemNotificationType { get; set; } = SystemNotificationTypes.System;

    [Column("Subject")]
    public string? Subject { get; set; }

    [Column("Body")]
    public string? Body { get; set; }

    [Column("SystemNotificationStatusTypeId")]
    public SystemNotificationStatusTypes? SystemNotificationStatusType { get; set; } = SystemNotificationStatusTypes.Unread;

    [Column("RecipientUserId")]
    public int? RecipientUserId { get; set; }

    [Column("CreatedOn")]
    public DateTime? CreatedOn { get; set; }

    [Column("CreatedBy")]
    public int? CreatedBy { get; set; }

    [Column("UpdatedOn")]
    public DateTime? UpdatedOn { get; set; }

    [Column("UpdatedBy")]
    public int? UpdatedBy { get; set; }
}

public class TestDataContext : DbContext
{
    public DbSet<SystemNotification> SystemNotifications { get; set; }

    public TestDataContext(DbContextOptions options)
        : base(options)
    {
        this.Database.AutoTransactionBehavior = AutoTransactionBehavior.Always;
    }
}

public class DatabaseConfiguration
{
    public void ConfigureContext(DbContextOptionsBuilder optionsBuilder)
    {
        var enableSensitiveDataLogging = true;
        var databaseServerVersion = App.DatabaseVersion;

        var version = ServerVersion.Parse(databaseServerVersion);

        optionsBuilder
            .UseMySql(App.ConnectionString, version)
            .EnableSensitiveDataLogging(enableSensitiveDataLogging)
            .UseLoggerFactory(App.ServiceProvider.GetService<ILoggerFactory>());

        new MySqlDbContextOptionsBuilder(optionsBuilder)
            .EnableStringComparisonTranslations(true);
    }
}

public class ConsoleLoggerFactory : ILoggerFactory, ILogger
{
    public void AddProvider(ILoggerProvider provider)
    {
        // purposely no-op
    }

    public ILogger CreateLogger(string categoryName)
    {
        return this;
    }

    protected virtual void Dispose(bool isDisposing)
    {
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter)
    {
        var msg = formatter(state, exception);
        Console.WriteLine(msg);
    }

    public bool IsEnabled(LogLevel logLevel)
    {
        return true;
    }

    public IDisposable? BeginScope<TState>(TState state)
        where TState : notnull
    {
        return this;
    }
}
```

**Comment by lauxjpn** [comment]
@ericjpeters I will take a look at this using the provided sample code.

**Comment by ajcvickers** [comment]
@lauxjpn Any update on this?

**Comment by lauxjpn** [comment]
This could be connected to `AUTOCOMMIT` set to `OFF`.

**Comment by ericjpeters** [comment]
@lauxjpn - Here's a little backstory in case it might help...

I migrated a project from EFCore 6 to EFCore 7.  Originally, it worked against a local MySQL instance, MySQL in AWS RDS AuroraDB / MySQL, as well as against an AWS RDS Proxy pointing at AuroraDB.   After the migration to EFCore 7, only the proxy failed - the other configurations worked fine.   As soon as I added the setting `this.Database.AutoTransactionBehavior = AutoTransactionBehavior.Always;`, it worked against the proxy as well.    I did not explicitly change anything regarding AUTOCOMMIT.

I read that EFCore 7 has some changed behavior around the AutoTransactionBehavior, and there was some autodetection going on to determine if it should be on or off.   I'm speculating that it is not auto-detecting the AWS RDS Proxy "properly" and that could be the root cause.   However, I don't have any insight on if that is because EFCore 7 isn't detecting the settings properly, or if the AWS RDS proxy is sending improper information causing EFCore 7 to not autodetect the proper setting for AutoTransactionBehavior, or if I'm completely off track and it's something else entirely.   But that's what I was able to figure out.

Hope it helps!
-Eric.

**Comment by roji** [comment]
@ericjpeters EF Core isn't supposed to auto-detect anything - it simply refrains from start an explicit transaction when SaveChanges sends a single SQL statement.

@lauxjpn given that `AutoTransactionBehavior = AutoTransactionBehavior.Always` made this go away, should we close this as a duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1740?

**Comment by lauxjpn** [comment]
@ericjpeters We just release `7.0.0` GA, which includes the fix for https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1740. Please test, whether this release fixes this issue or not.

@roji Let's first see, if it is resolved with the latest version. If that's not the case, we'll open a new issue on our repo, so we can close this one.

**Comment by ericjpeters** [comment]
> @ericjpeters EF Core 7.0 isn't supposed to auto-detect anything - it simply refrains from start an explicit transaction when SaveChanges sends a single SQL statement.

Thanks for the clarification @roji -- I thought I saw that EF Core 7 did an autodetect and set the AutoTransactionBehavior as it saw fit.  I can't find the source for that again...  I'm probably mis-remembering.

**Comment by ericjpeters** [comment]
> @ericjpeters We just release `7.0.0` GA, which includes the fix for [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1740](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1740). Please test, whether this release fixes the issue you are experiencing or not.
> 
> @roji Let's first see, if it is resolved with the latest version. If that's not the case, we'll open a new issue on our repo, so we can close this one.

@lauxjpn - I am a little surprised, I was suspecting 1740 was different.   But I'm glad to be wrong -- Pomelo 7.0.0 GA fixed the issue for me.   Thanks much for the guidance on this!!
