### ISSUE TITLE
.NET 7 MigrateAsync() not working anymore

### ISSUE THREAD

**Issue by rawmotionmb** [dotnet/efcore#29786]
Hey, I started to upgrade my .NET 5/6 applications to .NET 7, I also updated from EF6 to EF Core 7 (latest nuget package 7.0.0), which seems to be more difficult than expected :-(

I managed to find out that there were breaking changes in the new SqlClient (5.0.1) library, which now forces you to turn off encryption or trust the server certificate:

`Encrypt = false; or TrustServerCertificate = yes`

After I have set these properties in the connection string, I was again able to connect to my database.

BUT, I am using a code first approach, this means my app (windows desktop WPF) is creating / migrating the database if it does not exist or needs migration.
I am now running into the issue that my app is not able to create an empty database anymore. I am still getting an exception

**_Microsoft.Data.SqlClient.SqlException Cannot open database "XXX" requested by the login. The login failed. Login failed for user 'YYY\ZZZ'._**

I am using migrations and therefore i call:
`Context.Database.MigrateAsync();`
to migrate/build my database.

My DbContexts OnConfiguring method looks like that:
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    base.OnConfiguring(optionsBuilder);
    optionsBuilder.EnableSensitiveDataLogging(true);
    optionsBuilder.UseSqlServer(ConnectionString);
}
```

This exception only happens when I am trying to create a new database, migrating new fields works fine so far.
If I create an empty database (no scheme) manually on my SQL Server Express, all works fine, the scheme gets created and migrations applied. The issue is only the initial creation of the database itself.

Application and SQL Server Express (latest version) are running on the same machine, SQL Server runs in mixed authentication mode. "Trusted Connection" is enabled in my connection string looks like this:

`Server =.\\SQLExpress; Database = TEST_DB; Trusted_Connection = Yes; Connection Timeout = 5; Encrypt = false;`

Before I updated to .NET 7 everything worked fine with the exact same connection string.

Any ideas?

**Comment by ajcvickers** [comment]
@rawmotionmb The exception you posted should be caught and handled by EF Core when checking the database exists. If you are running in the debugger, then make sure this isn't a "first chance exception" that VS is showing you as soon as it is thrown, but ultimately will not escape.

**Comment by rawmotionmb** [comment]
thanks, @ajcvickers, thats it, for some reason VS resetted my exception handling config!
