### ISSUE TITLE
Exceptions not thrown, only if running with debugger

### ISSUE THREAD

**Issue by Mastahh** [dotnet/efcore#29791]
I have very strange behavior for EF
If I run it without debugger
Then I have following result

_Total data read: 165 of 26224
Max time: 4637.00ms
Avg time: 4422.34ms
Errors: 0_

With debugger I have following result

_Total data read: 1941 of 26226
Max time: 277072.00ms
Avg time: 20599.99ms
Errors: 3087
**Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.**: 3087_

I do not knwo what happened with other 21198 records why they are missing in Error or Read log :(
Why EF not produces these errors while i'm not debugging.

This error for some reason not throws if not debugging :(

Code is follows:
<sub>

        public async Task Customer_JustTest()
           {
            var options = new ParallelOptions()
            {
                MaxDegreeOfParallelism = 100
            };
            using var dbContext = dbContextFactory.CreateDbContext();
            var customers = await dbContext.Customers
                .AsNoTracking()
                .ToListAsync();

            var reads = new ConcurrentDictionary<string, long>();
            var errorsData = new ConcurrentDictionary<string, int>();

            Parallel.ForEach(customers, options, async (item) =>
            {
                try
                {
                    var sw = new Stopwatch();
                    sw.Start();
                    var result = await GetCustomerAsync(item.CustomerNumber);
                    sw.Stop();
                    if (result == null)
                    {
                        errorsData.AddOrUpdate($"Null: {item.CustomerNumber}", 1, (key, value) => { return value++; });
                    }

                    if (!reads.TryAdd(item.CustomerNumber, sw.ElapsedMilliseconds))
                    {
                        errorsData.AddOrUpdate($"Duplicated read {item.CustomerNumber}", 1, (key, value) => { return value + 1; });
                    }
                }
                catch (Exception ex)
                {
                    errorsData.AddOrUpdate(ex.Message, 1, (key, value) => { return value + 1; });
                }
            });
            logger.LogInformation($"Total data read: {reads.Keys.Count} of {customers.Count()}");
            logger.LogInformation($"Max time: {reads.Values.Max():f2}ms");
            logger.LogInformation($"Avg time: {reads.Values.Average():f2}ms");

            logger.LogInformation($"Errors: {errorsData.Values.Sum()}");
            foreach (var logEntry in errorsData)
            {
                logger.LogError($"{logEntry.Key}: {logEntry.Value}.");
            }
        }

       public DB.Entities.Customer GetCustomer(string customerNumber)
        {
            using var dbContext = dbContextFactory.CreateDbContext();
            var customer = dbContext.Customers.Where(c=>c.CustomerNumber == customerNumber)
                .AsNoTracking()
                .FirstOrDefault();
            return customer;
        }
</sub>

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Mastahh** [comment]
Hi,

I added sample project.
The problem with /GetCustomerAsync, if you run normarl way not exceptions, but if you run in debug, then a lot of exceptions.
But I expected these exceptions not only under debug.
[TestDbContext.zip](https://github.com/dotnet/efcore/files/10185835/TestDbContext.zip)

**Comment by ajcvickers** [comment]
@Mastahh The async code is calling async functions without waiting for them to finish. Among other issues, this means that `RunTestAsync` can finish before some or all of its async calls have completed. Instead using async appropriate. For example:

```C#
public static async Task<string> RunTestAsync(List<CustomerEntity> customers, DbService dbService)
{
	var reads = new ConcurrentDictionary<string, long>();
	var errorsData = new ConcurrentDictionary<string, int>();

	await Parallel.ForEachAsync(customers, _parallelOptions, async (item, ct) =>
	{
		try
		{
			var sw = new Stopwatch();
			sw.Start();

			CustomerEntity result = await dbService.GetCustomerAsync(item.CustomerNumber);
			sw.Stop();
			if (!reads.TryAdd(item.CustomerNumber, sw.ElapsedMilliseconds))
			{
				errorsData.AddOrUpdate($"Duplicated read {item.CustomerNumber}", 1, (key, value) => { return value + 1; });
			}
			if (result == null)
			{
				errorsData.AddOrUpdate($"Null: {item.CustomerNumber}", 1, (key, value) => { return value++; });
			}
		}
		catch (Exception ex)
		{
			errorsData.AddOrUpdate(ex.Message, 1, (key, value) => { return value + 1; });
		}
	});
	return GenerateSummary(customers.Count(), reads, errorsData);
}
```

Called like this:

```C#
app.MapGet("/GetCustomerAsync", async (HttpContext httpContext) =>
{
	var customers = app.GetAllCustomers();
	using (var scope = app.Services.CreateScope())
	{
		var dbService = scope.ServiceProvider.GetRequiredService<DbService>();
		var result = await RunTestAsync(customers, dbService);
		return result;
	}
});
```

I should also note that creating many threads in this way to do database operations is likely to have very poor performance and easily exhaust the connection pool. There is generally no value in attempting to run things in parallel like this.

**Comment by Mastahh** [comment]
Thanks, as I was expected issue with my code :)
In real app we do not have same usage in parallel, I just wanted to test that there are no issues to run EF in parellel.
it looks like that issue with somethin else.
