### ISSUE TITLE
Lazy and Eager Loading 

### ISSUE THREAD

**Issue by batesm** [dotnet/efcore#2980]
Please can you provide an update on current status of lazy and eager loading of navigation properties in EF7. Or point me to some documentation of existing or future implementation. I have tried googling on Bing and ReadTheDocs but to no avail. Thank you.

**Comment by rowanmiller** [comment]
Eager loading is implemented (using the Include/ThenInclude extension methods). 

Lazy loading is not yet implemented. Lazy loading is a common request but is also the number 1 source of performance issues we see and folks are often not aware that they are using it. Based on this we are going to see how we go without it... but will add it if feedback shows that folks really need it.

**Comment by batesm** [comment]
Yep, lazy loading can get quite contentious in my experience. Thanks, Rowan, for the swift response :)

**Comment by Kagamine** [comment]
https://github.com/aspnet/EntityFramework/issues/3176
Are there any method to make a lift include?

**Comment by Kagamine** [comment]
+1 for lazy load

**Comment by ryanlin1986** [comment]
+100 for lazy load, that's just ridiculous without it.
