### ISSUE TITLE
Ability to specify serializer for ToJson() method 

### ISSUE THREAD

**Issue by ivanpolish5** [dotnet/efcore#29810]
```
 builder.OwnsOne(m => m.MyProperty, ownedNavigationBuilder =>
  {
    ownedNavigationBuilder.ToJson();
  });
```

I would like to be able to specify serializer for `ToJson()` method so that I don't have to write 
`[JsonPropertyName("myInnerProperty")]` for each property inside of the class for it to follow camelCase naming convention.

**Comment by ajcvickers** [comment]
Duplicate of #28043. Make sure to vote (👍) for that issue.
