### ISSUE TITLE
Installing dotnet-ef not working on ubuntu 22.04

### ISSUE THREAD

**Issue by naturedamends** [dotnet/efcore#29824]
## File a bug

When running dotnet ef i'm getting the following message

```
You must install .NET to run this application.

App: /home/ubuntu/.dotnet/tools/dotnet-ef
Architecture: x64
App host version: 6.0.11
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=6.0.11
```

### Include provider and version information
```
 dotnet --version
6.0.111
```
```
.NET SDK (reflecting any global.json):
 Version:   6.0.111
 Commit:    b3bb659a9d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.111/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.111 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

I"m using macos 13 inside ubuntu (multipass launch test)
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

Then installing dotnet6 sdk and dotnet ef into the global location, I also have ~/.dotnet/tools in my path

**Comment by ajcvickers** [comment]
@naturedamends Please post the full command line that you are executing and also the output when using the --verbose option.

**Comment by rbanks54** [comment]
Just following up on this since I had the same issue when installing `dotnet-ef` as a global tool

I had originally installed .NET using `apt`, but since the package manager limits you to a single version and I needed multiple dotnet versions,  I switched over to the install-scripts approach and cleaned out the apt install.

The root cause relates to how the runtime is found for global tools as as such, I needed to edit the path defined in `/etc/dotnet/install_location_x64` to get it working. This is even with the `$DOTNET_ROOT` environment variable set and dotnet in the path. 

For more info: https://github.com/dotnet/runtime/issues/79237#issuecomment-1338168740

**Comment by arizon-dread** [comment]
> Just following up on this since I had the same issue when installing `dotnet-ef` as a global tool
> 
> For me, I had originally installed .NET using `apt`, but since the package manager limits you to a single version and I needed multiple dotnet versions, I switched over to the install-scripts approach and cleaned out the apt install. I guess not everything was fully cleaned up.
> 
> The root cause of this issue relates to how the runtime is found for global tools. I needed to edit the path defined in `/etc/dotnet/install_location_x64` to get it working, even with the `$DOTNET_ROOT` environment variable set and dotnet in the path.
> 
> For more info on why, see: [dotnet/runtime#79237 (comment)](https://github.com/dotnet/runtime/issues/79237#issuecomment-1338168740)


Thanks! After cleaning up all my dotnet 6 installs and having only dotnet 8 binarys, setting the /etc/dotnet/install_location_x64 to the path of the dotnet_sdk_8 folder made it work!
