### ISSUE TITLE
How to create the query which is translated into SQL declaring multiple entries deletion by WHERE condition?

### ISSUE THREAD

**Issue by alexandis** [dotnet/efcore#29846]
I want the query like this:

`await entitytRepository,DeleteAsync(e => field1Ids.Contains(e.Field1))`

to be translated into

`DELETE FROM ENTITY_TABLE WHERE FIELD1 IN (1, 2, 3)`

Instead, it is translated into this:

      Executed DbCommand (102ms) [Parameters=...], CommandType='Text', CommandTimeout='0']
      SELECT ... FROM ENTITY_TABLE m
      WHERE m.FIELD1 IN (1, 2, 3)

      Executed DbCommand (188ms) [Parameters=...], CommandType='Text', CommandTimeout='0']
      DECLARE
      v_RowCount INTEGER;
      BEGIN
      DELETE FROM ENTITY_TABLE 
      WHERE FIELD1  = :p0;
      v_RowCount := SQL%ROWCOUNT;
      OPEN :cur1 FOR SELECT v_RowCount FROM DUAL;
      DELETE FROM ENTITY_TABLE 
      WHERE FIELD1  = :p0;
      v_RowCount := SQL%ROWCOUNT;
      OPEN :cur2 FOR SELECT v_RowCount FROM DUAL;
      DELETE FROM ENTITY_TABLE 
      WHERE FIELD1  = :p0;
      v_RowCount := SQL%ROWCOUNT;
      OPEN :cur2 FOR SELECT v_RowCount FROM DUAL;

i.e. one DELETE per EACH RECORD.

Why is that?

I understand I can write a raw SQL, But I need a cross-database solution using EfCore...

Why I'm expermenting with this - I have several thousands of entries to delete and now I'm getting timeout. I don't know if it's related to the SQL translation shown above or not. If I had a free extension for BULK delete - I would use it instead. So I've decided to delete by chunks. Here is the simplified scenario - the chunk consists of 3 entries to delete (in reality I wanted to use something like 100).

**Comment by ErikEJ** [comment]
What EF Core provider?

**Comment by alexandis** [comment]
It's [Oracle v.6.21.5](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/6.21.5)

**Comment by ErikEJ** [comment]
DeketeAsync is not provided by EF Core. Then only way to do deletes with EF Core 6 is as noted. Depending on the implementation of the EF Core 7 provider for Oracle this may improve.

**Comment by roji** [comment]
@alexandis just to make sure you are aware of [ExecuteUpdate/ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) which were introduced in EF 7.0, and are ideal exactly for bulk changes like you're doing. If the Oracle provider has a 7.0-compatible version of the driver, these should work out of the box.
