### ISSUE TITLE
List constructs EF uses that require non-public code access

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#29843]
Put together a list of everything we do that operates on non-public code when we would not normally have permission to do so.

**Comment by ajcvickers** [comment]
Code that compiles expression trees:

- [RelationalPropertyExtensions.GetReaderFieldValue](https://github.com/dotnet/efcore/blob/16c1380d3bd839b6adee586bc990797fbdb64597/src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs#L1778)
  - Reads a value from a DbDataReader
  - Does not need non-public access
- [SqlServerGeometryTypeMapping.CreateSqlDbTypeAccessor](https://github.com/dotnet/efcore/blob/16c1380d3bd839b6adee586bc990797fbdb64597/src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs#L170)
- [SqlServerGeometryTypeMapping.CreateSqlDbTypeAccessor](https://github.com/dotnet/efcore/blob/16c1380d3bd839b6adee586bc990797fbdb64597/src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs#L184)
- [SqlServerUdtTypeMapping.CreateUdtTypeNameAccessor](https://github.com/dotnet/efcore/blob/16c1380d3bd839b6adee586bc990797fbdb64597/src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs#L121)
  - Sets the SqlDbType or UdtTypeName of a parameter
  - Does not need non-public access
  - Not clear to me why this is a compiled delegate? Maybe to avoid hard reference to SqlParameter?
- [SnapshotFactoryFactory](https://github.com/dotnet/efcore/blob/main/src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs)
  - Reads values from entity properties or fields
  - Needs non-publc access
- [DbContextFactorySource](https://github.com/dotnet/efcore/blob/main/src/EFCore/Internal/DbContextFactorySource.cs)
- [DbContextPool.CreateActivator](https://github.com/dotnet/efcore/blob/16c1380d3bd839b6adee586bc990797fbdb64597/src/EFCore/Internal/DbContextPool.cs#L52)
  - Calls constructor for DbContext type with single parameter for `DbContextOptions<TContext>`
  - Does not need non-public access; only calls public constructors
- [ClrCollectionAccessorFactory](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs)
  - Creates instances of HashSet<T>, List<T>, etc. or of a custome ICollection type
  - Does not need non-public access; collection must have public, parameterless constuctor
- [ClrPropertyGetterFactory](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs)
  - Reads value of property or field
  - Needs non-publc access
- [ClrPropertySetterFactory](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/Internal/ClrPropertySetterFactory.cs)
  - Sets valuye of property or field
  - Needs non-publc access
- [DependencyInjectionMethodParameterBinding](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/DependencyInjectionMethodParameterBinding.cs)
- [ServiceParameterBinding](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/ServiceParameterBinding.cs)
  - Gets a value from a service provider
  - Does not need non-public access direcyly, but value may be assigned to private field by materializer
- [EntityMaterializerSource](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/Internal/EntityMaterializerSource.cs)
  - Creates entity instances
  - Writes property and field values
  - Calls entity constructors, including parameterized constructors
  - Integrates and compiles arbitary expressions from user code
  - Needs non-publc access
- [ValueComparer](https://github.com/dotnet/efcore/blob/main/src/EFCore/ChangeTracking/ValueComparer%60.cs)
  - Compares values of two objects
  - May call non-public methods, such as typed Equals
  - User can supply arbitary expression that may need non-public access
  - Read values of fields or properties
- [RelationalSqlTranslatingExpressionVisitor.GetConstantOrNotTranslated](https://github.com/dotnet/efcore/blob/16c1380d3bd839b6adee586bc990797fbdb64597/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L1539)
  - Also other similar code in other providers
  - Evaluates an arbitary expression
  - May need non-public access depending on what is in the arbitary expression
- [ValueConverter](https://github.com/dotnet/efcore/blob/main/src/EFCore/ChangeTracking/ValueConverter%60.cs)
  - Converts a value from one type to a value of (usually) another type
  - User can supply arbitary expression that may need non-public access

**Comment by AndriySvyryd** [comment]
As for the shape of the API we'd prefer to be able to use just the name string and declaring type to access properties and fields instead of `PropertyInfo`/`FieldInfo`

**Comment by roji** [comment]
> Fields may be compiler-generated and so not have valid C# identifiers

As discussed offline, let's ask for a way to access backing fields of auto-properties. This isn't critical: we can use the regular API for accessing private fields, passing it the compiler-generated name (as today). But it would be good to remove knowledge of compiled-generated names from EF.

The two API options for this would be:

1. A dedicated API returning the name of the backing field, given a property. The slight disadvantage for us would be to embed the compiler-generated name obtained from this API in our generated C# code.
2. APIs accepting the property and directly reading/writing its backing field (assuming its an auto-property). The consumer would have to know they're accessing an auto-property (via another API? Or this API would be some sort of TryReadXXX, returning false for non-auto-properties?). This would also require us to generate different access code for auto-properties and other things.

So option 1 seems to be the preferred way for us, in any case.

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/runtime/issues/81741
