### ISSUE TITLE
The QueryTranslationPostprocessor.Process()  executed only once when with AsSplitQuery() method

### ISSUE THREAD

**Issue by Rwing** [dotnet/efcore#29855]
I ran this test and I expected method Process() to execute 2 times, but it only executed once
https://github.com/dotnet/efcore/blob/d00fa6f55ad5be8986d365ef32f4cea905f59258/test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs#L6788-L6801

https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs#L37

**Comment by roji** [comment]
QueryTranslationPostprocessor should run once per LINQ query, even if it ends up getting executed as two SQL queries. Are you seeing an actual issue, or is this about understanding EF's internals?

**Comment by Rwing** [comment]
> QueryTranslationPostprocessor should run once per LINQ query, even if it ends up getting executed as two SQL queries. Are you seeing an actual issue, or is this about understanding EF's internals?

Yep, I think I have a problem, for example, I want to force the “order by” to descending, so I changed some code in RelationalValueConverterCompensatingExpressionVisitor class, but the generated sql is incorrect, only the first sql set to desc, it doesn't affect the second sql.

**Comment by Rwing** [comment]
@roji 
I forked a repo to reproduce the problem, you can check this commit to see what I changed.
https://github.com/Rwing/efcore/commit/80898311c966d49bb51bdbf4cda9c7a44cfa6871
And I ran test as above, the generated sql is
```
 SELECT [p].[Id] 
 FROM [Parents] AS [p] 
 ORDER BY [p].[Id] **DESC**

 SELECT [c].[Id], [c].[ParentId], [p].[Id] 
 FROM [Parents] AS [p] 
 INNER JOIN [Child21355] AS [c] ON [p].[Id] = [c].[ParentId] 
 ORDER BY [p].[Id] 
```
The second sql did not add "DESC".

As for why I want to change it to DESC, this is just an example. In the real case, I created a custom `ExpressionVisitor` to change Offset/Limit paging to RowNumber paging.

**Comment by ajcvickers** [comment]
@Rwing If changing code in `RelationalValueConverterCompensatingExpressionVisitor` causes tests to break, then that means that the change was incorrect. We're not really sure what your expectations are here.
