### ISSUE TITLE
EF 7.0.1: EFCore 7.0 Bug - Invalid Operation Exception RE "Temporary Value"

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#29871]
## File a bug
Hi EFCore Team, @roji , and @ajcvickers,
I thought that these issues were resolved in 7.0.1, but we are still seeing them happen, just not as frequently:
https://github.com/dotnet/efcore/issues/29570
https://github.com/dotnet/efcore/issues/29502

Can you please give me instructions on how to enable the SQL logging so that I can get you the relevant information?

### Include provider and version information
EF Core version: 7.0.1
Database provider: MSSQL
Target framework: .NET 7.0.1
Operating system: Windows
IDE: Visual Studio 2022 17.4.3

**Comment by ErikEJ** [comment]
You have to wait for 7.0.2 or use a daily build  I think. Looking at the milestone.

**Comment by TonyValenti** [comment]
Oh.  That is too bad.  I was sure that would be in for 7.0.1.

Thanks so much!
