### ISSUE TITLE
 Alpine 3.17 for mcr.microsoft.com/dotnet/aspnet:3.1 docker image

### ISSUE THREAD

**Issue by tvbishan** [dotnet/efcore#29886]
Will we receive a docker image with **Alpine 3.17** for **aspnet 3.1** or since the support ended on **December 13, 2022**,  Alpine **3.16** will remain?

**Comment by ajcvickers** [comment]
@danmoseley On which repo should issues with docker images be filed?

**Comment by tvbishan** [comment]
@ajcvickers Sorry, my bad. I asked on wrong repo.
