### ISSUE TITLE
Azure Function and Entity Framework Sql Server error - Could not load file or assembly Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0

### ISSUE THREAD

**Issue by tomaszpychynski** [dotnet/efcore#29883]
It appears Microsoft.Azure.WebJobs depends on Microsoft.Extensions.Logging.Abstractions 2.1.0 and Microsoft.EntityFrameworkCore 7.0.0 depends on Microsoft.Extensions.Logging.Abstractions 7.0.0. 

The 'Function1' function is in error: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=[7.0.0.0], Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

Steps:

1. Create a new HTTP Trigger Azure Function, .NET 6 or 7
2. Add the below class to create a new DbContext to SQL Server
- Add the following nuget packages to fix compile errors : Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.SqlServer
3. The azure function will no longer execute because of the below error.

**Comment by ajcvickers** [comment]
@tomaszpychynski Please report this issue at https://github.com/Azure/Azure-Functions
