### ISSUE TITLE
DBNull shows up as a large negative  value -9223372036854774807 automatically triggering DBConcurrencyException for Concurrency tokens

### ISSUE THREAD

**Issue by rajasrinvasan** [dotnet/efcore#29900]
Hello,
I have a Concurrency column in the DB with a value of NULL. I am handling the  DBUpdateConcurrency Exception when there is an actual exception where the original values do not match with the database values.  When EF Core retrieves the Original value for a column that has a DB Value of null it shows up as large negative number -9223372036854774807 automatically triggering the exception because original value is -9223372036854774807 and databasevalue is  null which I believe is a bug. On the other hand, if I go to the DB and directly set the column to -9223372036854774807   savechanges works and concurrency exception is  also triggered  correcly only when there is an actual change in value from  the original  value to the database value . I tested the latter scenario by loading  -9223372036854774807 in to my inmemory dataset ,  updating  column in db to a different value and  then continuing code execution by saving changes.

The question I have is how can I make DBNull show up as null rather than -9223372036854774807  and avoid incorrect trigger of  DBConcurrencyUpdate Exceptions?

EFCore version being used in our project is 2.2.2

Thanks,
Raja

**Comment by ajcvickers** [comment]
@rajasrinvasan EF Core 2.2 is [out-of-support](https://learn.microsoft.com/en-us/ef/core/what-is-new/). Please update to EF Core 7.0 and if you are still seeing the issue, then attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by rajasrinvasan** [comment]
Thanks aj. Will do.
