### ISSUE TITLE
UninitializedDbSetDiagnosticSuppressor doesn't work when the severity is set to Error

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#29904]
### Include your code

``` editorconfig
dotnet_diagnostic.CS8618.severity = error
```

### Include provider and version information

EF Core version:7.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system: win11
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
Duplicate of #29582
