### ISSUE TITLE
Migration trying to make foreign key to a synonym

### ISSUE THREAD

**Issue by danielpetkovski** [dotnet/efcore#29914]
I have a situation where the project was initially created with a class ExternalUsers, which within it had a navigation property User.
The initial migrations made a Foreign key connecting these tables (ExternalUsers and User).
Due to the needs of the business the navigation User had to be replaced by MobileUser navigation property which is a synonym in the db and this synonym was created through sql.
Now when requests come (lets say to get data) the data is collected from MobileUsers synonym which works as intended.
The problem is when I do new migrations, in the UP method EF intends to drop the foreign key  to Users table and add foreign key to the new synonym and it fails to add the synonym. 
The MobileUsers synonym is excluded from migrations, but due to the navigation property in ExternalUsers it tries to create this foreign key.
If i add .Ignore for this property i evade this, but the then the data cannot be collected and exceptions are thrown.
Is there a way to evade this from showing up in future migrations and still be able to have it function properly?
I have attached screenshots of the class and the migrations and the error during the update-database.
  

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

![Class 1](https://user-images.githubusercontent.com/59264422/209099042-35895603-73a6-4ac2-afc9-c218da85e0b8.png)
![Screenshot_3](https://user-images.githubusercontent.com/59264422/209099055-44740ddd-2617-46a7-9de1-0211c455f50e.png)
![PM error](https://user-images.githubusercontent.com/59264422/209103987-c33ff0af-85bf-4829-9c57-abc430ac3d42.png)

**Comment by ajcvickers** [comment]
@danielpetkovski If the database has been updated outside of the migrations process, then the generated migration should be edited to reflect the current state of the database. This will mean the database and migrations are back in sync again. In this case, that likely means deleting the Drop and Add FK commands from the Up migration.
