### ISSUE TITLE
How to get rid of warning: The decimal property 'id' is part of a key on entity type 'SampleTable'?

### ISSUE THREAD

**Issue by ellaine5** [dotnet/efcore#29912]
**Is there a way to prevent this warning message without modifying the database?** 
We are migrating to EF6 and we got this warning:
`Microsoft.EntityFrameworkCore.Model.Validation: Warning: The decimal property 'id' is part of a key on entity type 'SampleTable'. If the configured precision and scale don't match the column type in the database, this will cause values to be silently truncated if they do not fit in the default precision and scale. Consider using a different property as the key, or make sure that the database column type matches the model configuration and enable decimal rounding warnings using 'SET NUMERIC_ROUNDABORT ON'.`

Our model looks like this:
```
        [Key]
        [Column("id", TypeName = "numeric(10, 0)")]
        [Precision(10,0)]
        public decimal id { get; set; }
```

(I am also attaching the sample solution here for reference.)
[MyEFConsoleApp.zip](https://github.com/dotnet/efcore/files/10286009/MyEFConsoleApp.zip)

We are trying to fetch data from a DB column with datatype `numeric(10,0)` to the model with datatype `decimal(10,0)`
We also enabled the sensitive data logging to see the warnings and queries.

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio Community 2022

**Comment by ajcvickers** [comment]
@ellaine5 Use `ConfigureWarnings`. For example:

```C#
var contextOptions = new DbContextOptionsBuilder<MyDbContext>()
    .LogTo(Console.WriteLine, LogLevel.Information)
    .ConfigureWarnings(w => w.Ignore(SqlServerEventId.DecimalTypeKeyWarning))
    //.UseLoggerFactory(loggerFactory)
    .EnableSensitiveDataLogging()
```

See [Configuration for specific messages](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#configuration-for-specific-messages).
