### ISSUE TITLE
Query Best Practices for TPH and filtered data

### ISSUE THREAD

**Issue by nhwilly** [dotnet/efcore#29911]
I have to choose between two different methods for querying a TPH set of derived classes.  I would like to know that I am executing as much of the logic in the right place as possible (presumably SQL Server).  

I have two approaches:
- **Bring all the items back via a base class query (which will include unrelated entries)** and then do filtering in my code executing on the web server.  Since there is a join on the selected records, this is likely more expensive than I'd want.
- **Ask SQL Server to filter based on the type and properties of the derived classes**.  This only selects the exact records and therefore does the minimal join effort, but I'm not really sure where it's executing or if there are hidden penalties.

I have written both approaches, and they both work.  I have not done performance testing as I'm not set up for that yet.

It strikes me that the second approach is trying to be too clever and asking too much of EF or SQL Server.  Maybe not.

I'm looking for basic guidance on this approach.  I expect I'll see it again in this project.

Thanks.
.net Core 7, EF Core 7, SQL Server 2022, solo developer

----------------------
Basically, an "account" has a list of "permissions groups" which have defined permission sets.  A similar relationship exists for "locations" and "entries".

All three have "permissions group enrollments" and are all tied together for a user for a given account via an "account membership".

In code, a collection of TPH `PermissionsGroupMemberBase` is many-to-many relationship between an `AccountMembership` and its TPH `PermissionsGroupBase`.   

These queries are an ambitious attempt to get all permissions from all permissions groups in a single query.

```csharp
public partial class AccountMembership
{
  private readonly List<PermissionsGroupMemberBase> _permissionsGroupMembers = new();
  public IReadOnlyCollection<PermissionsGroupMemberBase> PermissionsGroupMembers => _permissionsGroupMembers;

  public void AddPermissionsGroupMember(PermissionsGroupBase group)
  {
    {
      PermissionsGroupMemberBase members = group switch
      {
        AccountPermissionsGroup => new AccountPermissionsGroupMember(Id, group.Id, this.AccountId),
        LocationPermissionsGroup => new LocationPermissionsGroupMember(Id, group.Id, ((LocationPermissionsGroup)group).LocationId),
        EntryPermissionsGroup => new EntryPermissionsGroupMember(Id, group.Id, ((EntryPermissionsGroup)group).EntryId),
        _ => throw new Exception("Invalid permissions group type.  Did you create a new permissions group type?")
      };
      _permissionsGroupMembers.Add(members);
    }
  }
}
```

I'm using a specification pattern package from Steve Smith (@ardalis).

### Get them all approach:
```csharp
  public UserWithPermissionsSpec(string identityProvider, string providerAssignedId, Guid accountId)
  {

    Query.Where(user =>
      user.Identities.Any(identity =>
        identity.ProviderId == identityProvider
        && identity.ProviderAssignedUserId == providerAssignedId))
          .Include(u => u.AccountMemberships.Where(a => a.AccountId == accountId))
          .ThenInclude(m => m.PermissionsGroupMembers)
          .ThenInclude(x => x.PermissionsGroup)
          .Include(u => u.AccountMemberships.Where(a => a.AccountId == accountId))
            .ThenInclude(au => au.Account)
          .AsSplitQuery()
          .AsNoTracking();
  }
```
As you can see, I'm not filtering on `locationId` or `entryId`, I'm simply getting them all and the filtering methods are done post query.  

### Filter them at the server approach
```csharp
public class UserWithFilteredPermissionsSpec : Specification<User>, ISingleResultSpecification
{
  public UserWithFilteredPermissionsSpec(
    string identityProvider, 
    string providerAssignedId, 
    Guid accountId, 
    Guid? locationId, 
    Guid? entryId)
  {
    Query.Where(user =>
      user.Identities.Any(identity =>
        identity.ProviderId == identityProvider
        && identity.ProviderAssignedUserId == providerAssignedId))
          .Include(u => u.AccountMemberships.Where(a => a.AccountId == accountId))
          .ThenInclude(m => m.PermissionsGroupMembers
            .Where(member => (

              (AccountPermissionsGroupMember)member).AccountId == accountId ||

              (locationId.HasValue && 
              locationId != Guid.Empty && 
              ((LocationPermissionsGroupMember)member).LocationId == locationId.Value) ||

              (entryId.HasValue && 
              entryId != Guid.Empty && 
              ((EntryPermissionsGroupMember)member).EntryId == entryId.Value)))

          .ThenInclude(x => x.PermissionsGroup)
          .Include(u => u.AccountMemberships.Where(a => a.AccountId == accountId))
            .ThenInclude(au => au.Account)
          .AsSplitQuery()
          .AsNoTracking();
  }
}
```
(I've made the formatting ugly so that it wouldn't wrap in this post.)

In a test where I passed in valid values for the `locationId` and `null` for the `entryId`, EF Core logging shows what's below, so I know that the evaluation of the booleans is taking place before the SQL query.  Not sure about the casting:
```csharp
'DbSet<User>()
  .Where(user => user.Identities
      .Any(identity => identity.ProviderId == __identityProvider_0 && identity.ProviderAssignedUserId == __providerAssignedId_1))
  .Include(u => u.AccountMemberships
      .Where(a => a.AccountId == __accountId_2))
  .ThenInclude(m => m.PermissionsGroupMembers
      .Where(member => ((AccountPermissionsGroupMember)member).AccountId == __accountId_2 || True && ((LocationPermissionsGroupMember)member).LocationId == __locationId_Value_3 || False))
  .ThenInclude(x => x.PermissionsGroup)
  .Include(u => u.AccountMemberships
      .Where(a => a.AccountId == __accountId_2))
  .ThenInclude(au => au.Account)
  .AsNoTracking()
  .AsSplitQuery()
  .FirstOrDefault()'
```

**Comment by roji** [comment]
@nhwilly I haven't fully read all of the above (there's a lot), but it seems that you're asking whether to query many rows from the database to your .NET cilent process and filter there, or to push the filtering to your database.

In the vast majority of cases, it is almost always better to filter at the database:

* This prevents transfering lots of useless data over the network - just to filter it out at the client 
* If properly done, the database can use an index to filter, which can vastly improve performance

Exceptions to this rule are rare, usually when you know there's little data in the table (or little data that would be filtered out), etc.

Now, I haven't examined your specific model and queries, but do you have any reason to suspect that bringing everything back is better than filtering at the server? Is the generated SQL somehow bad and leads you to think that loading everything is better?

**Comment by nhwilly** [comment]
@roji Thanks for the quick response.  I totally understand your focus on bringing only back what's needed.

Sorry I dumped a lot in my example, I thought more was better.  :)

Basically, this is a TPH table and I'm trying to filter by the derived type and its unique properties.  

If you check out the second query, you can see this section:

```csharp
.ThenInclude(m => m.PermissionsGroupMembers
            .Where(member => (

              (AccountPermissionsGroupMember)member).AccountId == accountId ||

              (locationId.HasValue && 
              locationId != Guid.Empty && 
              ((LocationPermissionsGroupMember)member).LocationId == locationId.Value) ||

              (entryId.HasValue && 
              entryId != Guid.Empty && 
              ((EntryPermissionsGroupMember)member).EntryId == entryId.Value)))

          .ThenInclude(x => x.PermissionsGroup)
```
And you can see the cast in order to filter on a property unique to the derived type.

That's where what's happening under the hood gets foggy for me.

Is that a better description?  Certainly simpler. :D

**Comment by nhwilly** [comment]
Also, I tried to sift through the SQL that it generated and...  I'm both impressed *and* lost.

**Comment by roji** [comment]
If you're looking for an explanation of how EF is translating this query, then feel free to post the SQL and ask specific questions about it - I'd be happy to help. There shouldn't be anything particularly magical about this; all types in a TPH hierarchy get mapped to a single table, so this simply queries the different columns in the single table.

**Comment by nhwilly** [comment]
Will do. 

I just didn't/don't understand how the SQL knows about the casting of my C# object and where that takes place. 

I read about client evaluation happening under other circumstances and wanted avoid that happening here. 

TPH seems pretty magical to me at all levels and I like it. I just don't want to get bitten by making assumptions.

**Comment by roji** [comment]
EF Core never client evaluates anything in a Where clause; it either translates it to SQL or throws a translation error.

**Comment by nhwilly** [comment]
🤦‍♂️

Of course it can't on a `Where` clause.  If it did, it would have to bring the entire table, maybe the entire database, down to the client.  Duh.

Sorry I didn't do that calculus earlier.

I've looked at the SQL it generated again.  It's a split query and a complex one at that, so there are lots of `select` statements in the log.  Too much to waste your time with.

I guess it would make sense that EF Core knows about all of the column names in the shared table and really doesn't need to select based on the discriminator to get values it needs.  It sees all the columns and just generates select statements on the ones that I've specified.  The cast is happening for C#'s/my benefit.

If my interpretation is not correct, let me know.  Otherwise, I'll just close this.

Thanks for explaining this to me.  

------

Sorry it took me so long to respond.  My furnace _and_ my ISP both died within about 6 hours of each other.  Holidays, massive snowstorm, sub-zero temperatures and 18 for dinner on Saturday.

Yay.

**Comment by roji** [comment]
> I guess it would make sense that EF Core knows about all of the column names in the shared table and really doesn't need to select based on the discriminator to get values it needs. It sees all the columns and just generates select statements on the ones that I've specified. The cast is happening for C#'s/my benefit.

Yeah, that's mostly true (though TPH allows sharing a column between multiple properties, at which point it can become tricky, #29913). You try to switch to single query and see what the SQL looks like - it may make things more understandable.
