### ISSUE TITLE
Maybe wrong literal mapping of SQL Server TimeSpan?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29922]
I had [a bug report](https://github.com/ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly/issues/2) and realized where I got it from. 

Wonder if this means there is also a bug here ?

https://github.com/dotnet/efcore/blob/06a41bb4d04eba17826e1af8ebeddc14417f90a2/src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs#L22

**Comment by ErikEJ** [comment]
Looks like this test needs hour values above 12:

https://github.com/dotnet/efcore/blob/06a41bb4d04eba17826e1af8ebeddc14417f90a2/test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs#L213

**Comment by ErikEJ** [comment]
https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings OMG

**Comment by stevendarby** [comment]
Ah of course, it's a time span and not a time of day :)

**Comment by ajcvickers** [comment]
@ErikEJ What's the conclusion here?

**Comment by ErikEJ** [comment]
That there is special formatting string for Timespan that are different from DateTime formatting strings

so for Timespan: `hh` is 24 hours, where `hh` is 12 hours + AM/PM for DateTime and `HH` is 24 hours for DateTime (and TimeOnly)

**Comment by ErikEJ** [comment]
Better link: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings

**Comment by stevendarby** [comment]
I wouldn't say it's special, just that it's a time interval and not a time of day so it would never make sense to represent e.g. a time interval of 13 hours as 1 hour.

**Comment by ErikEJ** [comment]
@stevendarby I just meant that the meaning of `hh` differs here.
