### ISSUE TITLE
Need a way for adding Entitytypes to DbContext using ModelBuilder for scaffolding

### ISSUE THREAD

**Issue by PradeepKadubandi** [dotnet/efcore#2992]
I am logging this after our discussion about scaffolding.

When scaffolding fetches the DbContext from the application using reflection, we need a way to dynamically add entity sets to DbContext (to support a scenario where user selected to scaffold a model which is not a DbSet property in the selected DbContext) - this would avoid us to have to compile the application again one more time to figure out the metadata ...

**Comment by AndriySvyryd** [comment]
To make this flexible and useful for other scenarios we came up with several requirements:
1. Be able to add actions that run before or after `OnModelCreating` without changing the service provider
2. Be able to avoid calling `OnModelCreating`
3. Be able to create a model cache key for a given context instance

One way of satisfying these is with the following singleton service:
```
public interface IModelCustomizer
{
    event Action<ModelBuilder, ModelCacheKey> BeforeOnModelCreating;
    event Action<ModelBuilder, ModelCacheKey> AfterOnModelCreating;

    ModelCacheKey GetCacheKey(DbContext context);

    void Customize(ModelBuilder modelBuilder, ModelCacheKey cacheKey);
}
public class ModelCacheKey
{
    public virtual DbContext Context { get; protected set; }

    public override int GetHashCode()

    public override bool Equals(object obj)
}
```
`ModelSource` would use it instead of invoking `OnModelCreating` directly.

**Comment by rowanmiller** [comment]
Closing as we discussed with @sayedihashimi and it's not clear if this is still needed. If the conclusion is that it is needed, we will re-open and implement.

**Comment by Grinderofl** [comment]
I disagree with the singleton service described here. This is a scenario whereby each separate DbContext instance should have its own individual configuration, that isn't exposed to all other dbcontext instances, but rather directly injected into the dbcontext. Perhaps an addition to DbContextServices with ```IEnumerable<ModelBuilderOverride> Overrides {get; set;}```? This would also extend to `ModelBuilder.AddOverride(ModelBuilderOverride)` or `ModelBuilder.AddOverridesFromAssembly(Assembly)`
