### ISSUE TITLE
NU1202 Microsoft.EntityFrameworkCore 7.0.1 and dotnet 6.0.404

### ISSUE THREAD

**Issue by Torkolis** [dotnet/efcore#29938]
## Ask a question

I am trying to add efcore to my project. On the NuGet Gallery I see that the package version 7.0.1 is compatible with dotnet 6.0
![image](https://user-images.githubusercontent.com/98939160/209783739-d191f2bd-11ff-4dda-a6ac-b30adbc16c44.png)
 but when I try to add it, it fails with NU1202
I even just updated to the newest dotnet 6.0 and updated all the packages in nuget package manager ui (in visual studio code) and deleted bin and obj folders in my project, but it didn't work.

### Include your code

```
dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore
  Wiederherzustellende Projekte werden ermittelt...
  Writing C:\Users\xxx\AppData\Local\Temp\tmpC298.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Die PackageReference für das Paket "Microsoft.AspNetCore.Identity.EntityFrameworkCore" wird dem Projekt "C:\Users\xxx\xxx.csproj" hinzugefügt.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.aspnetcore.identity.entityframeworkcore/index.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.aspnetcore.identity.entityframeworkcore/page/0.0.1-alpha/3.1.11.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.aspnetcore.identity.entityframeworkcore/page/3.1.12/6.0.5.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.aspnetcore.identity.entityframeworkcore/page/6.0.6/7.0.1.json
info : Pakete für "C:\Users\xxx\xxx.csproj" werden wiederhergestellt...
error: NU1202: Das Paket Microsoft.AspNetCore.Identity.EntityFrameworkCore 7.0.1 ist nicht mit net6.0 (.NETCoreApp,Version=v6.0) kompatibel. Paket Microsoft.AspNetCore.Identity.EntityFrameworkCore 7.0.1 unterstützt Folgendes: net7.0 (.NETCoreApp,Version=v7.0)
error: Das Paket "Microsoft.AspNetCore.Identity.EntityFrameworkCore" ist mit all Frameworks im Projekt "C:\Users\xxx\xxx.csproj" nicht kompatibel.
```

### Include provider and version information

EF Core version: 7.0.1
Target framework: (NET 6.0)
Operating system: Windows 10
IDE: Visual Studio Code

**Comment by ErikEJ** [comment]
I think it is because the "Microsoft.AspNetCore.Identity.EntityFrameworkCore" package requires .NET 7. 

That package is not managed by the EF Core team

**Comment by Torkolis** [comment]
you are completely right, those are 2 different packages, I just searched for the "EntityFrameworkCore" keyword, sorry 🤦‍♂️.
