### ISSUE TITLE
?? Translation error?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#29935]
### Include your code

```C#

using System.ComponentModel.DataAnnotations;

var testContext = new TestContext();

var sql = testContext.Table1.GroupBy(a => a.Name).Select(a => new
{
    a.Key,
    V = a.Sum(b => b.A ?? 0 + b.B)
}).ToQueryString();
Console.WriteLine(sql);

sql = testContext.Table1.GroupBy(a => a.Name).Select(a => new
{
    a.Key,
    V = a.Sum(b => (b.A ?? 0) + b.B)
}).ToQueryString();
Console.WriteLine(sql);

public partial class TestContext : DbContext
{
    public virtual DbSet<Table1> Table1 { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("");
}

public partial class Table1
{
    [Key]
    public int Id { get; set; }

    public string? Name { get; set; }

    public decimal? A { get; set; }

    public decimal B { get; set; }
}

```

### Output

```
SELECT [t].[Name] AS [Key], COALESCE(SUM(COALESCE([t].[A], 0.0 + [t].[B])), 0.0) AS [V]
FROM [Table1] AS [t]
GROUP BY [t].[Name]

SELECT [t].[Name] AS [Key], COALESCE(SUM(COALESCE([t].[A], 0.0) + [t].[B]), 0.0) AS [V]
FROM [Table1] AS [t]
GROUP BY [t].[Name]
```

### Expect

sql are consistent

### Include provider and version information

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
@Varorbc what's your question? Where's the translation error, can you post an exception?

**Comment by roji** [comment]
> The two query string should be consistent, but they are not

Why should they be consistent? Here are your two source C# expressions:

1. `b.A ?? 0 + b.B`
2. `(b.A ?? 0) + b.B`

In C#, addition has a higher precedence than the null-coalescing operator ([docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence)); that means that these two expressions have different, and can yield different results. Accordingly, the SQL that is generated from them is different in the same way.

Am I missing something?
