### ISSUE TITLE
Source Browser for EF Core

### ISSUE THREAD

**Issue by NetMage** [dotnet/efcore#29937]
It would be really nice if Microsoft would host a Source Browser site for EF (Core) source like the [.Net](https://referencesource.microsoft.com/) and [.Net Core](https://source.dot.net/) and [Roslyn](http://sourceroslyn.io/) source browsers.

**Comment by ErikEJ** [comment]
Have you tried github source browsing recently?

**Comment by ajcvickers** [comment]
Note from triage: not planning anything here.
