### ISSUE TITLE
Ordering with Multiple constructors in the Entity type 

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/efcore#29940]
Hi,
I have an aggregate, and I want to know what is the ordering algorithm in calling constructor of the entity?
Should I have a parameter constructor always in my aggregate? In many sample codes, for example [here](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/Modules/Meetings/Domain/Meetings/Meeting.cs#L55) and [here](https://github.com/oskardudycz/EventSourcing.NetCore/blob/main/Sample/ECommerce/Orders/Orders/Orders/Order.cs#L36), I see this parameterless constructor. Maybe the reason of defining a parameterless constructor is that, in their [parameters constructor](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/Modules/Meetings/Domain/Meetings/Meeting.cs#L87) they have some class as parameter and [ef can't map](https://learn.microsoft.com/en-us/ef/core/modeling/constructors#binding-to-mapped-properties) them correctly, so for bypassing this parameter constructor they defined a [parameterless one](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/Modules/Meetings/Domain/Meetings/Meeting.cs#L55).

Does support injection class (navigation property classes) in entity type of .net 7, or it is in .net 8 plans?

This is my `AggregateRoot` class:

``` csharp
public class Customer : Aggregate<CustomerId>
{
    // EF
    private Customer()
    {
    }

    public Customer(
          CustomerId id,
          Email email,
          PhoneNumber phoneNumber,
          CustomerName name,
          Guid identityId)
      {
        //...
      }

    public Guid IdentityId { get; private set; }
    public Email Email { get; private set; } = default!;
    public CustomerName Name { get; private set; } = default!;
    public Address? Address { get; private set; }
    public Nationality? Nationality { get; private set; }
    public BirthDate? BirthDate { get; private set; }
    public PhoneNumber PhoneNumber { get; private set; } = default!;

    public static Customer Create(
        CustomerId id,
        Email email,
        PhoneNumber phoneNumber,
        CustomerName name,
        Guid identityId)
    {
        var customer = new Customer
        {
            Id = Guard.Against.Null(id),
            Email = Guard.Against.Null(email),
            PhoneNumber = Guard.Against.Null(phoneNumber),
            Name = Guard.Against.Null(name),
            IdentityId = Guard.Against.NullOrEmpty(identityId),
        };

        customer.AddDomainEvents(new CustomerCreated(customer));

        return customer;
    }
}
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.PostgreSql)
Target framework: (e.g. .NET 7.0)

**Comment by ajcvickers** [comment]
@mehdihadeli EF doesn't need a parameterless constructor, but it does need a constructor with parameters that set only mapped properties of the entity, and not also other referenced entity instances. It's difficult to tell how your properties are mapped in the example code above, but if they are all owned typed--which means the parameters are all different entity instances--then EF can't currently can't set those in the constructor--this is tracked by #12078.

**Comment by mehdihadeli** [comment]
@ajcvickers Thanks for your response.
