### ISSUE TITLE
DOTNET CORE7+MySQL migrations are failing

### ISSUE THREAD

**Issue by 1988gadocansey** [dotnet/efcore#29941]
below is my project file

 
![Screenshot 2022-12-29 013536](https://user-images.githubusercontent.com/7513799/209895927-238aea90-d188-4779-b515-448409224094.png)

![gad](https://user-images.githubusercontent.com/7513799/209895767-df656762-5c62-4bf3-96f1-ebb778bfe45a.png)

**Comment by ErikEJ** [comment]
Update your references to 7.0.0 and consider using the Pomelo provider

**Comment by roji** [comment]
@1988gadocansey MySql.EntityFrameworkCore does not yet have a 7.0.0 release, only a 7.0.0-preview5; if you want to use that, you must use the corresponding version of EF Core (7.0.0-preview.5.22302.2), and cannot mix a newer version of EF Core (7.0.0-rc.2.22476.2) with an older version of MySql.EntityFrameworkCore.
