### ISSUE TITLE
Include the table name when throwing an "Invalid column name" exception

### ISSUE THREAD

**Issue by StijnVA** [dotnet/efcore#29947]
When encountering a SqlException of the format "Invalid column name '{columName}'" you know EF is looking for a column that isn't there. But you still have to guess where it is looking for that column. Most of the times I got this is in a query spanning multiple entities and you just missed some configuration or misplaced an navigation property. 

When throwing a SqlException include the table name in the exception text.
for example: "Invalid column name 'FooId'" => "column 'FooId' not found on table 'Bar'".

**Comment by maumar** [comment]
those exceptions come from sql server (or other provider) - EF doesn't control what is the exception message thrown from providers. In case of "invalid column name" errors the query translates correctly from EF's perspective so we can't even provide extra information about properties/entities that the column belongs to.

**Comment by StijnVA** [comment]
That make sens... do you by any change know if the SqlServer Team has a feature request channel?

**Comment by ErikEJ** [comment]
They do, and your suggestion is already there: https://feedback.azure.com/d365community/idea/0fd2bc1d-5825-ec11-b6e6-000d3a4f0da0
