### ISSUE TITLE
Consider "freezing" package dependencies

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2996]
Currently, the package dependencies are "open ended", and potentailly causing all kinds of havoc if you happen to have newer packages in your packages folder.

I freeze the dependenecies like this in my .nuspec, not sure how to do the same in project.json:

```
 <dependencies> 
    <group targetFramework=".NETFramework4.5"> 
        <dependency id="EntityFramework.Relational" version="[7.0.0-beta8-15538]" /> 
     </group> 
 </dependencies> 
```

**Comment by davidfowl** [comment]
Never never never never never freeze package dependencies. You're making it worse for everyone. NuGet always chooses the minimum required dependency so there's no real need to do what you're saying.

**Comment by ErikEJ** [comment]
Hmmm... Wonder why folks then end up with a mix of beta 7 and beta 8 packages? Also, can you not specify the dependency behavior in the NuGet UI?

**Comment by davidfowl** [comment]
because they are using floating versions. That ui does not work for project.json based projects.
