### ISSUE TITLE
Executing command dnx ef dbcontext scaffold fails, regardless of the arguments specified

### ISSUE THREAD

**Issue by apDyn** [dotnet/efcore#2997]
Running under an asp.net 5 beta 7 project, with EF 7 beta 7:
     C:\Dev\project>dnx ef dbcontext scaffold provider EntityFramework.SqlServer connection "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=database;Integrated Security=True"

<b>Expected</b>:
Generated POCO dbcontext & classes from db tables.

<b>Result</b>:
Specify --help for a list of available options and commands.
System.Exception: TODO: Error: unrecognized argument 'connection'
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.HandleUnex
pectedArg(CommandLineApplication command, String[] args, Int32 index, String arg
TypeName)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(St
ring[] args)...

Snippet of my project.json dependencies:

```
 "EntityFramework.SqlServer": "7.0.0-beta7",
 "EntityFramework.SqlServer.Design": "7.0.0-beta7",
 "EntityFramework.Commands": "7.0.0-beta7",
```

Version of the EntityFramework Commands:

```
C:\Dev\project>dnx ef --version
Entity Framework Commands
7.0.0-beta7-15540
```

To be frank I've tried almost any possible combination of the arguments connection & provider (like connection="connection string" provider="EntityFramework.SqlServer" but I keep getting various exceptions.
You should have provided a example on how to use it, as there is nothing about it in your EF wiki or any other docs on the net.

**Comment by lajones** [comment]
Try running `dnx ef dbcontext scaffold --help` to see how you should use this. The usage is:

`dnx ef dbcontext scaffold <connection_string> <provider>`

So in your case:

`dnx ef dbcontext scaffold "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=database;Integrated Security=True" EntityFramework.SqlServer`

Closing. But feel free to re-open if you're still having problems.

**Comment by alfberga** [comment]
Be sure to nave installed the package EntityFramework.SqlServer.Design

**Comment by lajones** [comment]
@alfberga That's right. The runtime provider assembly defines its design-time provider assembly - which may be itself. If the design-time assembly is separate and you've failed to install it you should see a helpful error message saying what you're missing.
