### ISSUE TITLE
EF Core transaction retries, ChangeTracker and ConcurrencyCheck weird behavior

### ISSUE THREAD

**Issue by vzarskus** [dotnet/efcore#29987]
## File a bug
When using `SqlServerRetryingExecutionStrategy` with a transaction and having `[ConcurrencyCheck]` on an entity property, the `ChangeTracker` seems to be `accepting all changes` depending on the assignment operator used on the property.

I am not 100% if this is a bug, since it might be an expected behavior but I believe it is worth looking into nevertheless, because if it is an intended behavior, it is not exactly intuitive and requires an explanation.

This above is best explained by looking at the code:

### Include your code
I have created a small project that reproduces the issue: https://github.com/vzarskus/EFCore-dbUpdateConcurrencyException-interestingBehavior
There you will find one entity `Product` that has a `ConcurrencyCheck` on `Price` property and one context `ProductContext`. Besides the initial setup and cleanup code, there are two tests for the method `ApplyDiscountToCoconut`. This method creates an `SqlServerRetryingExecutionStrategy` and executes a function inside it. The function creates a transaction (since there are several DB actions that are being invoked), gets one existing Product from the DB, **modifies its Price** and saves it with `acceptAllChangesOnSuccess` flag set to `true`. Then a transient error is being emulated in order to trigger a retry and transaction never commits.
The two tests each provide a different way in which the Price modification happens. The first one uses an assignment subtraction operator which results in `ApplyDiscountToCoconut` throwing a `DbUpdateConcurrencyException`. The second one uses an assignment operator which results in the same method throwing `RetryLimitExceededException`.
I cannot tell if it is an expected behavior or not, but it does feel weird. 
It seems the `ChangeTracker` didn't `AcceptAllChanges` in the **assignment operator test** and the transaction was retried until the retry limit was reached. 
Meanwhile in the **assignment subtraction operator test** the code threw a `DbUpdateConcurrencyException` on the first retry as it should since the `ChangeTracker` accepted all changes on `SaveChangesAsync(true)` before the first retry. Then, on the first retry the modified entity was treated as an `original values` which resulted in a failed concurrency check because the `database values` ([relevant docs on `original` and `database` values](https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=data-annotations#resolving-concurrency-conflicts)) are different (the transaction never committed on the initial run).
Why is the behavior of `ChangeTracker` so different in the two tests?

Thank you very much for your time!

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: VS Code latest

**Comment by ajcvickers** [comment]
@vzarskus In `ExecuteAsync` code, `SaveChangesAsync(true)` tells EF to update the state of tracked entities if saving the changes succeeds. When working with transactions, the context state should only be updated after everything in the transaction has succeeded and the transaction has been committed.

For the case that uses `coconut.Price -= 2`, this means that before the first call to `SaveChanges`, the tracked entities are:

```
Product {Id: 1} Modified
  Id: 1 PK
  Description: 'A very tasty coconut.'
  Name: 'Coconut'
  Price: 8.00 Modified Originally 10.00
```
And after they are:

```
Product {Id: 1} Unchanged
  Id: 1 PK
  Description: 'A very tasty coconut.'
  Name: 'Coconut'
  Price: 8.00
```

Then for the next retry, the tracked entities are:

```
Product {Id: 1} Modified
  Id: 1 PK
  Description: 'A very tasty coconut.'
  Name: 'Coconut'
  Price: 6.00 Modified Originally 8.00
``

This then results in a concurrency exception because the value in the database is not 8--it's still 10 because the transaction was not committed the first time round.

On the other hand, for the case that uses `coconut.Price = 8`, the tracked entities initially are

```
Product {Id: 1} Modified
  Id: 1 PK
  Description: 'A very tasty coconut.'
  Name: 'Coconut'
  Price: 8.00 Modified Originally 10.00
```

And after `SaveChanges`:

```
Product {Id: 1} Unchanged
  Id: 1 PK
  Description: 'A very tasty coconut.'
  Name: 'Coconut'
  Price: 8.00
```

That is, the same as before. But, on the second call to `SaveChanges`, the values are still:

```
Product {Id: 1} Unchanged
  Id: 1 PK
  Description: 'A very tasty coconut.'
  Name: 'Coconut'
  Price: 8
```

This is because no change was made to the price--it was 8 and it is still 8. This means that `SaveChanges` is a no-op, and continues to be no matter how many times it is called in this state.

**Comment by vzarskus** [comment]
Got it, thank you!
