### ISSUE TITLE
Entities in collections are not tracked after AddRangeAsync is called

### ISSUE THREAD

**Issue by Jackie-L** [dotnet/efcore#29996]
# Entities in collections are not tracked after AddRangeAsync is called

Microsoft.EntityFrameworkCore 6.0.5

After SaveChangesAsync, why is the state of the entity Detached？

![image](https://user-images.githubusercontent.com/38280253/210928716-8cb4a96a-5fae-476c-8c74-27c3a87d0e52.png)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Jackie-L** [comment]
I created a demo [https://github.com/Jackie-L/Demo](url),In line 32 of the Program.cs file in the EFAddRangeAsync project, the value I want to return is [{"id":1,"name":"C"}],But the program returns [{"id":1,"name":"A"}].
If I add ToList() to line 23, as I did on line 24, the program returns [{"id":1,"name":"C"}]
I'm not sure why is there such a difference, is it the default setting of EFCore?
![image](https://user-images.githubusercontent.com/38280253/211026340-69b80e3e-91aa-446c-9a0a-139542c87094.png)
![image](https://user-images.githubusercontent.com/38280253/211026464-2f38c577-3895-4536-bf39-c147756533a4.png)

**Comment by roji** [comment]
@Jackie-L without the ToList, your `summaries.Select(e => new MyEntity { Name = e })` fragment gets evaluated **twice** - once when adding the entities, and then later against in your foreach. In other words, you have two distinct instances of each entity, and the entity being inserted isn't the same as the one being modified below.

If you add ToList, the Select is evaluated exactly once and the results are stored in the resulting List. You then add and modify the same entity instance.

**Comment by Jackie-L** [comment]
@roji I understand.Thanks for your response.
