### ISSUE TITLE
ExecuteInsert (bulk insert)

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/efcore#29994]
EF 7 gave us [`ExecuteUpdate` and `ExecuteDelete` (Bulk updates)](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates). Is there a way to leverage any of this to do a bulk insert? Are there plans for an `ExecuteInsert` method?

**Comment by roji** [comment]
Duplicate of #27333

**Comment by roji** [comment]
See also #29897
