### ISSUE TITLE
Test: Revisit workaround that deletes database files in DeleteDatabase and DeleteDatabaseAsync on SqlServerTestStore

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#3000]
Currently we have [code there that deletes the database files](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.SqlServer.FunctionalTests/SqlServerTestStore.cs#L417) after sending a drop database command.

We initially didn't expect to need to do this but DROP DATABASE seems to return before it is done with housekeeping, so unless we delete the files manually, if another test comes in soon enough that needs to create a database with the same name, it will fail. 

Although the workaround helps in getting next tests to pass, we don't know how this might affect the server and the stability of our test runs.

I am creating this issue so that we can track this as a possible source of test instability and to consider finding a more robust approach.

**Comment by divega** [comment]
Actually SQL Server may leave the files in place by design if the database wasn't online. That might be what we are compensating for, in which case it should be ok.

**Comment by smitpatel** [comment]
@AndriySvyryd - Is this something no longer relevant after new testing pattern?
