### ISSUE TITLE
@MarounMaroun 

### ISSUE THREAD

**Issue by fadak** [dotnet/efcore#30006]
@MarounMaroun ths fix for this will be released as part of 7.0.3, in February. In the meantime, you can use the 8.0 [daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md), which contain the fix and are otherwise very stable.

_Originally posted by @roji in https://github.com/dotnet/efcore/issues/29534#issuecomment-1365028949_
      
upgrading to 8.* daily builds is like falling from a hole into a well

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
