### ISSUE TITLE
InMemory store fails to change new Entity state to ''Unchanged"

### ISSUE THREAD

**Issue by mustaphakd** [dotnet/efcore#3001]
Everything works fine when I manually set the primary keys value; but when I let
the framework generate the key value with its generator, an exception occurs.

I am using EF7 in-memory in a test fact/case for my UnitOfWork without explicitely defining a derived
DbContext.
I have blog the detail about it please check out the scenario and advice.
www.mustaphakd.wordpress.com

look at the bottom of the page for the exception details.

**Comment by rowanmiller** [comment]
Hey @mustaphakd,

By default, key generation should work just fine with the InMemory provider. For example, the following code just uses all the default conventions (which includes generation for the `Blog.BlogId` property).

```c#
using Microsoft.Data.Entity;
using System;

namespace ConsoleApplication4
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new BlogContext())
            {
                context.Blogs.Add(new Blog { Name = "Blog One" });
                context.Blogs.Add(new Blog { Name = "Blog Two" });
                context.SaveChanges();

                foreach (var blog in context.Blogs)
                {
                    Console.WriteLine($"{blog.BlogId}: {blog.Name}");
                }
            }
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Name { get; set; }
    }

    public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase();
        }
    }
}
```

Running the code gives the following output, showing that values are successfully generated for the property.

> 1: Blog One
2: Blog Two

There is a lot of repository layering etc, going on in the blog post that you linked to. If you are finding cases where key generation is breaking, can you distill it down to an example that just uses EF.

~Rowan
