### ISSUE TITLE
SqlLite and non-ascii characters

### ISSUE THREAD

**Issue by ruicraveiro** [dotnet/efcore#3003]
Hello, I'm having a problem with EF7 and Sqlite. I have the following code:

``` C#
using (MyContext context = new MyContext())
{
    Employee employee = new Employee{ Name = "John Doe" };
    context.Add(employee);
    employee = new Employee { Name = "Mário" };
    context.Add(employee);
    employee = new Employee { Name = "Januário Ancião e ansioso" };
    context.Add(employee);
    context.SaveChanges();
}
```

Notice that the first employee has no character accents while the two other employees have accents  in their names. The second employee has only one accent. The latter has two.

Employee class has nothing special to it:

``` C#
[Table("Employee")]
public class Employee
{
    public Employee()
    {
    }

    [Key]
    public long Id { get; set; }

    [StringLength(100)]
    [Display(Name = "Nome")]
    public string Name { get; set; }

}
```

MyContext is also quite trivial:

``` C#
public class MyContext : DbContext
{
    public DbSet<Employee> Employees { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=./data.db");
        base.OnConfiguring(optionsBuilder);
    }
}
```

After running the code, look at what happens to the table:
![image](https://cloud.githubusercontent.com/assets/8490712/9671347/31dfa9ae-528a-11e5-815a-9806866de5cd.png)

The first name is persisted exactly as expected. 
The second name **lost the final character**, becoming "Mári" instead of "Mário".
The third name **lost the two final characters**, becoming "Januário Ancião e ansio" instead of "Januário Ancião e ansioso".

So, the conclusion that can be reached is that for each character that has a high character code (probably requiring two bytes when encoded in UTF-8), EF7 is losing a character (I would bet it's losing a byte, not necessarily a character) in the end.

I didn't test this scenario with APIs other than Entity Framework 7, but I did manually test inserting rows using "Sql Server Compact/SQLite Toolbox" for Visual Studio and after refreshing the table, values do appear OK, so it is not SQLite's problem, but somewhere in EF7 or one of it's dependencies. Here's the result after inserting values manually (without EF7):
![image](https://cloud.githubusercontent.com/assets/8490712/9671569/b0e2e080-528b-11e5-901b-b7a21029223e.png)

**Comment by bricelam** [comment]
Possibly fixed by aspnet/Microsoft.Data.Sqlite#127. What version are you using?

**Comment by ruicraveiro** [comment]
I'm using the released Beta7 version, so yes, most probably it's the same bug.

**Comment by natemcmaster** [comment]
Fixed in https://github.com/aspnet/Microsoft.Data.Sqlite/pull/127. 
@ruicraveiro  Please reopen if you see this behavior in anything later than 1.0.0-beta8-**15530**

**Comment by Kagamine** [comment]
@natemcmaster How to install 1.0.0-beta8-15530?

**Comment by mishfit** [comment]
@Kagamine it depends (mostly on your runtime and os), for me on OSX:
```
dnvm install 1.0.0-beta8-15530 -r mono -OS linux/darwin -u
```

the important parts are 
-r, which runtime
-OS which operating system
-u, use the unstable feed (beta8 isn't released yet)

available from `dnvm help`
