### ISSUE TITLE
Add DbSet AddRangeAsync overload that takes IAsyncEnumerable

### ISSUE THREAD

**Issue by Gotcha7770** [dotnet/efcore#30044]
I really enjoyed using `IAsincEnumerable<T>` and sometimes i face with need to store async stream of entities in Data Base. Now I'm forced to materialize the collection in order to use `AddRangeAsync` or i have to call `Add` in async foreach loop.
What if we added overload
```csharp
public virtual Task AddRangeAsync(IAsyncEnumerable<TEntity> entities, CancellationToken cancellationToken = default);
```
to DbSet?

I have seen the `InternalDbSet` code and it doesn't seem very complicated to implement it. I could create PR

**Comment by roji** [comment]
AddRange itself only updates the internal state of the change tracker, so it's a fundamentally non-async operation (no I/O being done).

We could introduce an AddRangeAsync just to remove the burden of doing materialization from the user, but I don't think that makes sense. There are an infinite number of APIs out there which accept IEnumerable, and it's not reasonable to have an overload to each one of them, accepting IAsyncEnumerable, just to remove that burden...

**Comment by Gotcha7770** [comment]
Do you mean that due to keeping track of all added objects, we will not be able to save memory, even if we can get rid of the materialization?

**Comment by Gotcha7770** [comment]
Ok i see your point, thanks! Perhaps we can close this issue then
