### ISSUE TITLE
OWNED BY <column>  Sequences not scaffolded in a database first scenario

### ISSUE THREAD

**Issue by SNiedinger** [dotnet/efcore#30067]
## "Sequence Owned By" (bug or new feature?)

In Postgresql a sequence can be linked to a table column via the OWNED BY parameter option. This is not scaffolded and then results in an error during migration.

E.g. A SQL sequence script in a schema named 'crm' which has a table called 'persons' with a column named 'id' which defaults to the nextval of the sequence.

```
CREATE SEQUENCE IF NOT EXISTS crm.persons_person_no_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1
    OWNED BY persons.id;
```

Sequences that are not owned are however scaffolded in the DbContext E.g.

`modelBuilder.HasSequence("not_owned_seq", "crm").HasMax(2147483647L);`

I propose the following c# syntax in case this could be a new feature request.

```
...
modelBuilder.Entity<Person>(entity =>
{
    entity.HasKey(e => e.Id).HasName("pk_persons");
    
    entity.Property(e => e.Id).HasSequence("persons_person_no_seq", "crm").HasMax(2147483647L)); // proposed syntax
    
    entity.Property(e => e.Id).HasDefaultValueSql("nextval('crm.persons_person_no_seq'::regclass)");
...
```

The Migration should then include the OWNED BY <column> in the CREATE SEQUENCE script.

Database provider: Npgsql.EntityFrameworkCore.PostgreSQL Version  "7.0.1"
Target framework: NET7.0
EF Core version: "7.0.2"

Postgresql CREATE SEQUENCE documentation:
https://www.postgresql.org/docs/current/sql-createsequence.html

**Comment by roji** [comment]
@SNiedinger Npgsql/PostgreSQL-specific issues belong in https://github.com/npgsql/efcore.pg, please move it there.
