### ISSUE TITLE
How to mock response for GetConnectionString()?

### ISSUE THREAD

**Issue by sturlath** [dotnet/efcore#30075]
I have a ASP.net Core middleware that is used for multitenancy and it has a call to GetConnectionString() on the current context that I would like to mock out (with FakeItEasy but I don´t think its a limitation of it) but I get the following error

> Member GetConnectionString can not be intercepted. Only interface members and virtual, overriding, and abstract members can be intercepted.

The code I trying to mock is just this

```csharp
var dbContextConnectionString = dbContext.Database.GetConnectionString();

//then omitted logic where I check the string and do stuff
```

and the test has this (that has the error)

```csharp
var db = A.Fake<DatabaseFacade>();
A.CallTo(() => db.GetConnectionString()).Returns("tenantConnectionString");
```

I see that you might be doing it like this [CreateBackingContext](https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/test/EFCore.SqlServer.FunctionalTests/TwoDatabasesSqlServerTest.cs). Is that my only option?

**My version
EF Core 6.0.6**

**Comment by sturlath** [comment]
What I did was to create my own `BaseDbContext` that inherits from `DbContext` and then use these methods directly and since I make them `virtual `I can then mock them out.

Wouldn´t you say this is the way to go ?

```csharp
public class BaseDbContext : DbContext
{
	public BaseDbContext(DbContextOptions options) : base(options)
	{
	}

	public BaseDbContext() : base()
	{
	}

	public virtual string GetConnectionString()
	{
		return Database.GetDbConnection().ConnectionString;
	}

       // I also need to mock the following two methods  
	public virtual async Task<List<string>> GetPendingMigrationsAsync()
	{
		var migrations = await Database.GetPendingMigrationsAsync();
		return migrations.ToList();
	}

	public virtual async Task MigrateAsync()
	{
		await Database.MigrateAsync();
	}
}
```

**Comment by ajcvickers** [comment]
@sturlath Extension methods are by their nature hard to mock. Introducing another level of abstraction, as you have done in your comment, is probably the most pragmatic way to handle this.

**Comment by sturlath** [comment]
Thank you @ajcvickers. It seems to be holding up quite well atm. Would have liked to skip all these extra abstractions but what ever to make the code more testable. Closing this now.
