### ISSUE TITLE
Stylecop is interfering with EfBundle creation in docker image in gitlab CI

### ISSUE THREAD

**Issue by vyaskuldeep20** [dotnet/efcore#30074]
U have stylecop configured in my project and when I run 
RUN dotnet ef migrations bundle --project ${CSPROJ_PATH}.csproj --startup-project ${CSPROJ_PATH}.csproj -r alpine.3.7-x64 --self-contained  --configuration Bundle   -o /build/migrationbundle --verbose
 to create ef bundle for my docker image in gitlab CI, I get stylecop errors and it fails to create EF bundle.
 
![image](https://user-images.githubusercontent.com/68455719/212615178-c2d9771a-cadc-41d4-b3d2-38d24b8b4c44.png)

Can anyone help how can create efbundle with stylecop

**Comment by ajcvickers** [comment]
Note from triage: mark the code as generated.
