### ISSUE TITLE
Issue on managing one-to-one relationships

### ISSUE THREAD

**Issue by gaglia** [dotnet/efcore#30084]
Hello,

I'm having trouble managing a one-to-one relationship with SQL Server databases.

When I go to save the entities that I'm trying to add in the database, an error is generated on the FK one by one because it seems that the FK field is not automatically valued correctly, as I expect it to be.

I am attaching an example where I have inserted comments in the code to reproduce the error and better understand what I mean.
(Within the attached EF7Test project there is a CreateDatabase.sql sql script which generates the database with tables to replicate the problem)
[EF7TestSolution.zip](https://github.com/dotnet/efcore/files/10439356/EF7TestSolution.zip)

I can't figure out if this is the default behavior of EF 7, if instead it's a problem or if I'm doing something wrong in configuring and managing this type of relationship.

I await your feedback
Thank you

EF Core version: 7.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Win11
IDE: Visual Studio 2022 17.4.4

**Comment by ajcvickers** [comment]
@gaglia Your code is using notification entities, but the navigations properties are not sending notifications when their values are changed. If I update

```C#
public cnPrNota_Righe cnPrNota_Righe { get => LazyLoader.Load(this, ref _cnPrNota_Righe); set => _cnPrNota_Righe = value; }
```

to

```C#
public cnPrNota_Righe cnPrNota_Righe { get => LazyLoader.Load(this, ref _cnPrNota_Righe); set { SetWithNotify(value, ref _cnPrNota_Righe); } }
```

then the code no longer throws.

**Comment by gaglia** [comment]
@ajcvickers making the suggested change everything works as I expected.

Thank you!
