### ISSUE TITLE
PostgreSQL Array Type Mapping and SQLite in EF Core 7

### ISSUE THREAD

**Issue by mu88** [dotnet/efcore#30095]
In one of our .NET 7 apps (using EF Core 7) I want to make use of the [PostgreSQL Array Type Mapping][1] feature and I'm struggling with testing a certain part of the code base.

Please see the following (rather simplified) example:
```c#
public class Blog
{
    public int Id { get; set; }

    public string Url { get; set; }

    public string[] Tags { get; set; }
}

public class BlogContext : DbContext
{
    DbSet<Blog> Blogs { get; set; }
}
```

This works nicely in PostgreSQL, the corresponding data type for `Tags` in PostgreSQL is `text[]` and all the system integration tests (running PostgreSQL in Docker) are passing.

But for the integration tests, we're using an in-memory SQLite database. Since SQLite doesn't seem to support `text[]` as data type, I came up with the following workaround:
```c#
public class TestDbContext : BlogContext
{
    public TestDbContext(DbContextOptions options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder
            .Entity<Blog>()
            .Property(blog => blog.Tags)
            .HasColumnType("text")
            .HasConversion(
                strings => string.Join(",", strings),
                s => s.Split(",", StringSplitOptions.RemoveEmptyEntries));
    }
}
```

All the integration tests are now working, except for the following class:
```c#
public class BlogService
{
    public BlogService(IDbContextFactory<BlogContext> factory) => _factory = factory;

    public async Task<List<Blog>> FindBlogsWithTag(string tag)
    {
        await using var context = await _factory.CreateDbContextAsync();
        return context.Blogs.Where(blog => blog.Tags.Contains(tag)).ToList();
    }
}
```

The corresponding test fails with:
```
System.InvalidOperationException
The LINQ expression 'DbSet<Blog>()
    .Where(b => b.Tags
        .Contains(__tag_0))' could not be translated. Additional information: Translation of method 'System.Linq.Enumerable.Contains' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

So my question: how can I make this test pass with SQLite? Is it even possible? Or should I convert the integration test into a system integration test and hereby implicitly switch from SQLite to PostgreSQL?

Thanks!

  [1]: https://www.npgsql.org/efcore/mapping/array.html

EF Core version: 7.0.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7.0
Operating system: Windows 10 21H2 (OS Build 19044)
IDE: Rider 2022.3.1, VS 2022 (17.4.3)

**Comment by roji** [comment]
@mu88 we generally recommend testing against the database type that you use in production (PostgreSQL), and not attempt to swap out it out with a fake (e.g. SQLite). A database fake can never be compatible with your actual production database, and queries will sometimes not work or even return different results. In addition, setting up a PostgreSQL instance for testing is quite easy - see [testcontainers](https://dotnet.testcontainers.org/modules/postgres/) for a nice way to do this, and tests can run very efficiently. [Our documentation on testing](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy) contains extensive information on why database fakes aren't a good idea, and provide tips on testing again your real database type.

Specifically on your question above, you can indeed use value converters to save and read back any CLR type (e.g. arrays), but you cannot call functions on it in LINQ queries.

**Comment by mu88** [comment]
Thank you very much for your response, @roji! I really appreciate it.

So if I understand you correctly, the short answer: _there is no solution to my problem, so write tests against PostgreSQL._

**Comment by roji** [comment]
If you need to invoke methods over arrays in your LINQ query, then yeah, there's no solution for that currently.
