### ISSUE TITLE
Update to Microsoft.Data.SqlClient 5.1.0

### ISSUE THREAD

**Issue by hoerup** [dotnet/efcore#30105]
SQLCLient 5.0.1 has a memory leak which has been solved in 5.1.0

Please update https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/EFCore.SqlServer.csproj#L51 accordingly

https://github.com/dotnet/SqlClient/issues/1810

**Comment by ErikEJ** [comment]
@hoerup In the meantime you can just add an explicit reference: https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli#install

**Comment by roji** [comment]
I've started working on DateOnly/TimeOnly support (#24507), will do this as part of that.

However, I'm not sure we'd bump a minor version in a patch - I think a SqlClient 5.0.2 should be released at some point, which we could update to.

**Comment by ajcvickers** [comment]
Note from triage: this is done for 8.0 (https://github.com/dotnet/efcore/pull/30120). We will not be updating 7.0, but as @ErikEJ, the package can be pulled in explicitly to opt-in on 7.0.
