### ISSUE TITLE
Is it possible that SavingChangesAsync will be called again before SavedChangesAsync returns in SaveChangesInterceptor

### ISSUE THREAD

**Issue by Duke4848** [dotnet/efcore#30103]
## Ask a question

I'm implementing `SaveChangesInterceptor` and I would like to pass information from SavingChangesAsync  to  SavedChangesAsync.
To facilitate thit I use a private field:

`private List<Item>? _temporaryEntries;`

        public override ValueTask<InterceptionResult<int>> SavingChangesAsync(DbContextEventData eventData, InterceptionResult<int> result, CancellationToken cancellationToken = default)
        {
         [...]
         _temporaryEntries = newValue
            return base.SavingChangesAsync(eventData, result, cancellationToken);
        }

        public override ValueTask<int> SavedChangesAsync(SaveChangesCompletedEventData eventData, int result, CancellationToken cancellationToken = default)
        {
            //consumes
             foreach(var item in _temporaryEntries){...}
        }

Is it possible that SavingChangesAsync will be called again before SavedChangesAsync returns in SaveChangesInterceptor causing `SavingChangesAsync` ovewriting what I store in` _temporaryEntries` before `SavedChangesAsync` consumes it?

If that is the case should I replace List<Item> with blocking queue or it is possible to add entry to `SaveChangesCompletedEventData`?

**Comment by ajcvickers** [comment]
@Duke4848 For a given context instance there cannot be another call to `SavingChangesAsync` before the corresponding `SavedChangesAsync` or `SaveChangesFailedAsync` is called. Two notes:

- `DbContext` is not thread-safe, so the same context instance cannot be used for concurrent calls to `SaveChangesAsync`.
- If the same interceptor instance is shared by multiple context instances, then these calls can be interleved.
