### ISSUE TITLE
Modifying the model outside of OnModelCreating

### ISSUE THREAD

**Issue by Perustaja** [dotnet/efcore#30108]
I've seen some similar questions but I'm not sure about this as it seems most people wanted something quite different. 

All I need to do is add entities (classes made as expected for EF) to the model given the type of their dbcontext. I want to avoid inheritance because it can block my library users from using stuff like IdentityDbContext. Any way to do this outside of the context itself if I have the type of their context?

I don't see any way to obtain/modify a given context's model without instantiating it, thus finalizing its model. I also don't want to use a DbContextOptionsBuilder because UseModel completely negates their configuration. Are we forced to basically create our own separate context or make them inherit from ours?

**Comment by ajcvickers** [comment]
Related to #30061.

@Perustaja At what point will the application indicate that the types should be included in the model? For example, should this happen in `AddDbContext`? Or somewhere else?

**Comment by Perustaja** [comment]
@ajcvickers thanks for the reply. Yes that issue is pretty much right on and I agree with the changes, as the problem is really inheritance.

For my uses it will be known at registration time. The plan was that the end user would add their own dbcontext using AddDBContext, then later on call my library code with AddEntityFrameworkStores<TContext>. Then I just add my entities into the model for my own internal code using that context type.

Since it seems like it won't be doable my workaround is basically what that ticket shows but without inheritance. Instead I tried to add an IModelBuilder extension for them to call during OnModelCreate. This allows them to inherit still. I had an issue during migrations with finding a service collection so I'm not sure if my plan is feasible but that error may be entirely unrelated. If you'd like to see my exact code please let me know. Thanks.

**Comment by ajcvickers** [comment]
I agree that it would be great to make this easier. I think it's covered by #30061. For now, using a workaround like shown there is a reasonable way to go.

**Comment by Perustaja** [comment]
Got it
