### ISSUE TITLE
EF7 - IsLoaded property is always false on navigation-properties when using AsNoTracking()

### ISSUE THREAD

**Issue by luca-domenichini** [dotnet/efcore#30140]
### Actual behaviour

Given 2 related entities `Person` and `PersonDetail` and executing a query with an `Include()` from `Person` to `PersonDetail` as follows, the corresponding navigation property has the `IsLoaded` value `false`

```C#
    var p = context.Persons
        .AsNoTracking()
        .Include(p => p.PersonDetail)
        .FirstAsync();

    Assert.True(context.Entry(p).Navigation(nameof(Person.PersonDetail)).IsLoaded); // this assertion fails!
```

### Expected behaviour

The assertion should not fail, because the navigation property was loaded as part of the query.

### Include provider and version information

EF Core version: 7.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 6.0 / .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

Repro csproj: [EF7AsNoTrackingBugTests.zip](https://github.com/dotnet/efcore/files/10501408/EF7AsNoTrackingBugTests.zip)

**Comment by luca-domenichini** [comment]
Ok this is by design, since when loading with - no tracking - means exactly that the DbContext do not know anything about that entity.
Closing issue.

**Comment by ajcvickers** [comment]
@luca-domenichini Note that this will change in EF8 due to https://github.com/dotnet/efcore/issues/10042

**Comment by luca-domenichini** [comment]
@ajcvickers from what I have read in #10042, I understand that EF8 will be able to lazy fetch navigations starting from an untracked entity. Does it means that the DbContext will populate the IsLoaded property too?
Thanks very much for your support!

**Comment by luca-domenichini** [comment]
@ajcvickers from what I understand, with #10042 merged, my assertion above now basically works OK, but only if lazy loading is enabled.
Is that correct?
If that is the case, I would want to ask why not having `IsLoaded` property populated to `true` even when lazy loading is not enabled. Maybe is there another issue tracking this?

I mean, I see a bit of misleading behavior in entity tracking (asymmetry?): whether or not lazy-loading is enabled, if a navigation is included in a query, I would expect its backing `Entry.Navigation("..").IsLoaded` property to tell me if it was included or not.
