### ISSUE TITLE
Support some form of dependency injection to parameterize a `Migration`

### ISSUE THREAD

**Issue by kriswuollett** [dotnet/efcore#30141]
__Issue:__

Roles in PostgreSQL are for the entire database instance/cluster, not the individual named "database". This causes a problem when one wants to control access by roles in a multi tenant and/or instance environment in a single database cluster. Say for example you have an app called `my_app`. So for production and development there may be PostgreSQL databases called `prod_my_app` and `dev_my_app` respectively in a single database cluster. At least for PostgreSQL if you grant a role called say `my_app_viewer` to a development user, then the only way to prevent the development user from reading production data is to only grant the database connect privilege on `dev_my_app`. Ideally it would be nice to have the extra bit of protection and parameterize the role name in the raw sql given to `migrationBuilder.Sql` so the production one would be called `prod_my_app_viewer` for example. I'd use Handlebars for example when working with raw sql.

I've seen a handful of replies to this issue brought up in other discussion forums which simply state a combination of:

- it is impossible
- why would you want to do it anyways since calculation of migration depends on current state

Yes, this may be a "foot gun" for inexperienced developer, but I currently don't see a way how I create something along the lines of creating dozens or even hundreds of simultaneous instances of a database/schema in a single PostgreSQL cluster for a situation like a CI/CD system using efcore migrations.

 __Workarounds:__

- use static and/or environment variables to parameterize the migrations
- use something like the following in the raw sql:

```sql
DO $$
BEGIN
  EXECUTE format('CREATE ROLE "%1$s"', current_database() || '_viewer');
  EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA public TO "%1$s"', current_database() || '_viewer');
  EXECUTE format('CREATE ROLE "%1$s"', current_database() || '_editor');
  EXECUTE format('GRANT "%1$s" TO "%2$s"', current_database() || '_viewer', current_database() || '_editor');
END
$$ LANGUAGE plpgsql;
```

But I'd rather not dynamically generate DDL to execute since it is harder to understand diffs when generating the migration sql.

__Desired solution:__

Support something like dependency injection [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0) so I can pass something as simple as a `roleNamePrefix: string` to the migration classes.

**Comment by kriswuollett** [comment]
There is some precedence to this capability in database migration libraries, [Alembic](https://alembic.sqlalchemy.org/) for example:

- [get command line options in customized `env.py` script](https://alembic.sqlalchemy.org/en/latest/api/config.html#alembic.config.Config.cmd_opts)
- [get `-x` command line arguments in customized `env.py` script](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.get_x_argument)
- in migration script step get context with custom configuration from `env.py` by using [`alembic.op.get_context()`](https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.get_context)

**Comment by roji** [comment]
First, an important note:

> So for production and development there may be PostgreSQL databases called prod_my_app and dev_my_app respectively in a single database cluster.

Regardless of the above issue, hosting your production and development databases on the same PG cluster generally isn't a great idea - separation of these environments is usually quite important (e.g. to prevent developement testing to affect production performance). I'd strongly recommend considering having different server for production and development.

As a side-effect, this would also resolve the issue you have above, since you can have the same username on both environments (though different passwords are a good idea!).

> Ideally it would be nice to have the extra bit of protection and parameterize the role name in the raw sql given to migrationBuilder.Sql so the production one would be called prod_my_app_viewer for example.

Where would you get this bit of information from? Where would the production vs. development distinction actual be recorded (and from there, injected into migrations)?

Finally, note that you don't necessarily have to manage role creation via raw SQL in your migrations; it's perfectly fine to manage certain aspects of your database externally.

**Comment by kriswuollett** [comment]
> Regardless of the above issue, hosting your production and development databases on the same PG cluster generally isn't a great idea - separation of these environments is usually quite important (e.g. to prevent developement testing to affect production performance). I'd strongly recommend considering having different server for production and development.

The names were given as an example. In a CI/CD environment the names could be named after the PR number or branch, e.g., `pr_12345` or `new_feature`. So in a more performance isolated environment one would pay for a production database cluster with one database/schema, and a separate development one with multiple database/schema clones as needed. But this use case can still apply in a production environment if one is talking about production multi-tenant SaaS with separate database instances.

> As a side-effect, this would also resolve the issue you have above, since you can have the same username on both environments (though different passwords are a good idea!).

Having the same username isn't necessarily clean in the CI/CD environment since the application instances shouldn't accidentally be able to read or modify another environment. Also I'd assume developers would like to remove the latency of spinning up a new database cluster to run integration tests on a pull request (even though cloud providers usually can charge by the minute or even seconds of use).

Yes... I'm practicing good password hygiene with databases -- don't even need passwords with [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) and [Cloud SQL Auth proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy).

> Where would you get this bit of information from? Where would the production vs. development distinction actual be recorded (and from there, injected into migrations)?

I'm currently parameterizing `IDesignTimeDbContextFactory` so I can pass the DB credentials to a `NpgsqlConnectionStringBuilder` by overriding `CreateDbContext(string[] args)`. For environments like production or staging I'd generate the idempotent SQL script, check it in, and, for example, run the script through a [Terraform `null_resource` provisioner](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource). For CI/CD I could do the same, but could also use [`EnsureCreated`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.idatabasecreator.ensurecreated?view=efcore-7.0#microsoft-entityframeworkcore-storage-idatabasecreator-ensurecreated) with some more .NET code like I'd do in unit tests with optionally a different database provider like SQLite if compatible/appropriate.

> Finally, note that you don't necessarily have to manage role creation via raw SQL in your migrations; it's perfectly fine to manage certain aspects of your database externally.

Yes, that's true. But it is nice to apply role-based access controls to database objects right next to the creation of said objects in code.

**Comment by kriswuollett** [comment]
Just being able to inject a `Dictionary<string,string>` would be great if one wants to make it somewhat restrictive.

**Comment by roji** [comment]
> The names were given as an example. In a CI/CD environment the names could be named after the PR number or branch, e.g., pr_12345 or new_feature.

User creation for a PR branch really sounds like something that belongs outside of EF's migrations... Since it's a specific detail of running your migrations in CI, it feels like it belongs as a CI configuration step, much like starting up PostgreSQL, configuring its postgresql.conf to tweak PG options, or any other environmen setup that needs to be done in CI.

However, if you do insist on managing this via a migration, then it sounds like something that can come from an environment variable. If that's what you're looking for, you can simply access the environment variable from your migration's raw SQL code.

> Just being able to inject a Dictionary<string,string> would be great if one wants to make it somewhat restrictive.

I'm still not quite clear where this Dictionary would come from, where you'd set it and how you'd expect it to get injected... Can you provide a concrete example where you need to do it via a migration, and an environment variable doesn't work or make sense?

**Comment by kriswuollett** [comment]
I'd image the process in CI as:

- Use database admin user outside of .NET to:
  - create `${env}_my_app_owner` role
  - create `${env}_my_app` database owned by `${env}_my_app_owner`
  - grant role `${env}_my_app_owner` to admin user
  
- Use [CreateDbContext args](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#args) to:
  - run `dotnet ef migrations script --idempotent -- --dbconfig dbconfig.json`
  - Deserialize a configuration object from `dbconfig.json`
  - Some config goes towards configuring the database connection string
  - Some config goes towards specifying things like a name prefix to add to roles... maybe by an extension method on `DbContextOptionsBuilder` called `AddMigrationOptions`? Said migration options object gets injected into the constructor of a `Migration` if it has a matching type parameter for it
  - generate SQL content with statements like `GRANT SELECT ON orders TO pr_1234_my_app_viewer` by using raw sql templates that get rendered with say Handlebars by just passing something as simple as `options.migrationOptions` reference as template data if designed that way. Interpolate strings to be used by the Fluent API could also be done if needed.
 
- Use database admin user outside of .NET to:
  - change role to `${env}_my_app_owner`
  - run the script that was generated above by `dotnet ef migrations script`
  - grant roles like `${env}_my_app_viewer` to login roles like `dev_my_query_service@my-project.iam.gserviceaccount.com`

- When CI run is done:
  - use database admin user to drop the `${env}_my_app` database then the drop all the roles with the `${env}_` prefix

Overall... yes, I can use environment variables directly in a `Migration`, but I'd assume that re-using the existing [CreateDbContext args](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#args) along with a builder extension of some sort would be the more developer friendly of accomplishing the same.

**Comment by kriswuollett** [comment]
The only additional context I can give for the concept is that the above would be deployed in a cluster using name prefixes as well through Kustomize [transformers](https://github.com/kubernetes-sigs/kustomize/blob/d5e1940fc243365756bf44f9eb3cef1a63f5bffc/examples/transformerconfigs/README.md) to create separate environments. So naturally db roles should have same naming convention.

Or this (name prefix, or suffix) could possibly be done differently like [snake case conventions](https://github.com/efcore/EFCore.NamingConventions)?

Anyhow... thanks for your comments and any consideration for the feature -- I think it could be very useful if possible in the future.

**Comment by ajcvickers** [comment]
@bricelam The only issue I can find related to this is https://github.com/dotnet/efcore/issues/10258.

**Comment by bricelam** [comment]
Duplicate of #10660
