### ISSUE TITLE
ExecuteUpdate: Add SetProperty overload that accepts a property name or property info directly (no lambda)

### ISSUE THREAD

**Issue by stanvanrooy** [dotnet/efcore#30149]
I noticed that the `SetProperty` method doesn't accept an actual property name / `PropertyInfo` object as its first argument, only an expression.

Because of this, it is currently not possible to make use of the `ExecuteUpdate` method in dynamic update statements.

Is there a particular reason behind this?

Example:
```c#
.SetProperty("Name", p => "value");
```

instead of
```c#
.SetProperty(p => p.Name, p => "value");
```

**Comment by roji** [comment]
Following discussion in the team:

> .SetProperty("Name", p => "value");

This syntax isn't possible, since the return type of the 2nd lambda is inferred from the first. In other words, we need the first lambda to be typed in order to know what the second one needs to return.

However, you can use EF.Property to achieve what you want:

> .SetProperty(p => EF.Property<string>(p, "Name"), p => "value");

**Comment by Kokujou** [comment]
just to add up on that... it's not neccessary to infer the type.
maybe you could simply create a method that accepts any type, that's how the most reflection based methods do it. if you call ProeprtyInfo.SetValue it also accepts an object and if the types not match it throws. it's not type-safe anymore, but it wasn't type-safe from the beginning.

as per my understanding - please correct me if i'm wrong - all you need to care is the final type of the object to determine how the object is sent to the database...

**Comment by ajcvickers** [comment]
We discussed this in triage, and we believe that the current combinations are a good middle ground between flexibility and not exposing and `object` signature in the case which would all compile time checks.
