### ISSUE TITLE
DbContext Scaffolding of geography type columns fail

### ISSUE THREAD

**Issue by apDyn** [dotnet/efcore#3014]
Executing dnx ef dbcontext scaffold <context> EntityFramework.SqlServer
For column [country][coordinates]. Could not find type mapping for SQL Server type geography. Skipping column.

**Comment by ErikEJ** [comment]
That is by design, there is currently no support for geography columns. It is in the backlog: https://github.com/aspnet/EntityFramework/issues/1100

**Comment by apDyn** [comment]
Do you have any recommended workarounds?

**Comment by ErikEJ** [comment]
If you are running on full .NET 4.5/4.6, use EF 6.x!

**Comment by rowanmiller** [comment]
BTW we may be able to introduce an interim workaround until we have proper spatial support https://github.com/aspnet/EntityFramework/issues/3076

**Comment by tsasioglu** [comment]
For anyone that ends up here from google, this is now supported via adding the nuget package `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite`. Details at https://docs.microsoft.com/en-us/ef/core/modeling/spatial

**Comment by Freysi21** [comment]
> For anyone that ends up here from google, this is now supported via adding the nuget package `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite`. Details at https://docs.microsoft.com/en-us/ef/core/modeling/spatial

Not the hero we deserve
