### ISSUE TITLE
How to add conventions by assembly instead of manually setting them up in ConfigureConventions

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/efcore#30150]
## Ask a question

I have a lot of ValueObjects in my codebase. Those are _never_ stored as entities in the database but instead each have a ValueConverter that transforms them to their base type and back.

I do not want to set this up for every entity that uses these ValueObjects so I register these conversions as conventions:
```
    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.Properties<ValueObjectType>().HaveConversion<ValueObjectType.EfCoreValueConverter>();
    }
```

However these calls get pretty long. Especially if pulling in ValueObjects from multiple assemblies. I've started creating static methods in each assembly that basically take the configurationBuilder and apply these conventions for all ValueObjects in that assembly.

I'm wondering however if there is an easier way by just defining Attributes/Classes for each of these ValueObjects so that they are automatically picked up similar to how IEntityTypeConfiguration works. I haven't found any class that would fit the bill (an obvious name would be IConventionConfiguration or similar) and there is no method on the ModelConfigurationBuilder that allows you to just add a whole assembly.

Maybe there is a simpler way in general that I'm missing completely.

**Comment by roji** [comment]
There's nothing built into EF that scans assemblies for bulk configurations. But it should be pretty trivial to write that code yourself, i.e. use reflection yourself over the assembly.

**Comment by Blackclaws** [comment]
I see. The question is whether this might be interesting for more people or if its just a niche use case.

In general I could see ValueConversions being set up by attributes on classes to be something that might be interesting. There simply are cases where you _never_ want to store a class in any other way than converted.

**Comment by ajcvickers** [comment]
An attribute for specifying the value converter is tracked by #29426.

**Comment by Blackclaws** [comment]
Gotcha, I'll close this as completed as its ValueConverterAnnotations that is being tracked elsewhere and in general setting up configuration by assembly scanning is currently not planned it seems.
