### ISSUE TITLE
ORA-01460: unimplemented or unreasonable conversion requested for more than 32kb size string even after giving conversion

### ISSUE THREAD

**Issue by Jincearanmula** [dotnet/efcore#30153]
## File a bug
I am getting the same error "ORA-01460: unimplemented or unreasonable conversion requested", when i am trying to save string value which is more than 32kb in size, to a BLOB storage.

I have added below configuration, however i still get error while saving this from EF Core. we are using Oracle.EntityFrameworkCore version 6.21.61
.HasColumnType("BLOB")
.HasConversion<byte[]>(t => Encoding.UTF8.GetBytes(t), t => Convert.ToString(t))
.HasMaxLength(1000000000)

### Include provider and version information
Oracle.EntityFrameworkCore version 6.21.61
Target framework: (e.g. .NET 6.0)
Operating system: Windows
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
@Jincearanmula Please report this to Oracle, since it is an issue in the Oracle database provider which is supported by them.
