### ISSUE TITLE
No relational provider - TPT

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#30157]
Hello,

I am trying to implement the TPT inheritance strategy (TPH already works)in my no relational provider but i need your help because something that i am not able to understand is happening.

I have this model :

```
    public abstract class Company
    {
        public Guid CompanyID { get; set; }
        public string CompanyName { get; set; }
    }

    public class Shop : Company
    {
        public string ShopType { get; set; }
    }

    public class Corporation : Company
    {
        public int EmployersNumber { get; set; }
    }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Company>().HasKey(itm => itm.CompanyID);
            modelBuilder.Entity<Shop>().ToTable("Shops");
            modelBuilder.Entity<Corporation>().ToTable("Corporations");
        }


```
if i execute this query

`q = DB.Set<Company>().ToArray();`

all seems works but actually not as expected. If i get an Entry from the ChangeTracker for a Shop and i call `Entry.Properties` I get 4 properties instead of 3. The unaxpected property is the Discriminator, so I tried to compare wath happen in my provider with the SqlServer Provider.
SqlServer Provider create a `RelationalEntityShaperExpression `that inherit from `EntityShaperExpression`, while my entity shaper class inherit directly from `EntityShaperExpression `. I saw that `RelationalEntityShaperExpression `override this:

`protected override LambdaExpression GenerateMaterializationCondition(IEntityType entityType, bool nullable)`

and inside this sub there is a test that check the case of TPT, so I added a reference to `EFCore.Relational` Project and now my shaper entity class inherit from `RelationalEntityShaperExpression `instead of `EntityShaperExpression`.
But when `GenerateMaterializationCondition `runs, this test fail :

```
            if (entityType.FindDiscriminatorProperty() == null
                && entityType.GetDirectlyDerivedTypes().Any())

```

`entityType.FindDiscriminatorProperty()` 
calls `(IProperty?)((IReadOnlyEntityType)this).FindDiscriminatorProperty() `
that calls var `propertyName = GetDiscriminatorPropertyName();`
that calls `RuntimeEntityType.GetDiscriminatorPropertyName()` that return :

`return (string?)this[CoreAnnotationNames.DiscriminatorProperty];
`
with my provider this last line returns `"Discriminator"` and this let fail the original test `entityType.FindDiscriminatorProperty() == null`

wath I not understand is why if I use The same Context class with the same `OnModelCreating` sub just changing the provider(UseSqlServer...) all the calls i wrote above remain the same, but 

`return (string?)this[CoreAnnotationNames.DiscriminatorProperty];`

returns `null `so the original test is verified.

My provider do nothing on building the model metadata(and I not know all this part of EF because I never had to implement something), it should be all demanded to EF, so I can not understand wath my provider do (or not do) to produce this difference.

Can you please help me or pointing me in a right way to understand?

Many many thanks

I am on 6.0.9.0 version

**Comment by GLuca74** [comment]
I am sorry, I just realized that if I get the `EntityTypes` from model Metadata, for the Company Entity the properties are 3 instead of 2, while if I get the metadata with Sql Server Provider the properties are 2, so it is totally not related to query, in the Sql Server  Provider I have to found the service that works on Model and try to understand wath I have to do.

Please ignore this post, and if is possible to indicate me wich is this service please write it.

Again many thanks.

**Comment by ajcvickers** [comment]
@GLuca74 TPT is a relational concept and as such is implemented in the Relational package and used from there by relational providers such as the SQL Server provider. What are the characteristics of the database you are targeting such that it is both non-relational and should support TPT?

**Comment by GLuca74** [comment]
Yes, you are right, it is easy that wath I wrote confuse.
My provider is a no relational provider and it not target a database, it will support TPH,TPT and TPC.
A large set of my tests works like this :

I instantiate the same context(and model configuration) two times, one with my provider and one with Sql Server Provider.
On the two Context I perform the same query
The two result of the query must be equal(via reflection)
The two ChageTracking must contains the same data

In the test i wrote up, the check on the change tracking fails because the Entity entries in my change tracking has the Discriminator as a propertyEntry while the change tracker with Sql server no.
In the ChangeTracking of the context with my provider the Discriminator is returned as a propertyEntry while should be an internal information to check the entity type.

Since, in this case, almost all the work is performed by `EntityShaperExpression` I tried to see if the Sql Server provider do something different. And actually it use `RelationalEntityShaperExpression `that inherits from `EntityShaperExpression`. When `RelationalEntityShaperExpression `is created, we are in a situation that is the same for a relation provider and mine, it is just a class that produce the expression that will be used to fill the entity with the valueBuffers that the specific provider have(later) to replace with specific data access.
I saw that `RelationalEntityShaperExpression` override `GenerateMaterializationCondition` from `EntityShaperExpression` and do somenthing that is related to TPC case :

```
        protected override LambdaExpression GenerateMaterializationCondition(IEntityType entityType, bool nullable)
        {
            Check.NotNull(entityType, nameof(EntityType));

            LambdaExpression baseCondition;
            if (entityType.FindDiscriminatorProperty() == null
                && entityType.GetDirectlyDerivedTypes().Any())
            {
                **// TPT**
                var valueBufferParameter = Parameter(typeof(ValueBuffer));
                var discriminatorValueVariable = Variable(typeof(string), "discriminator");
                var expressions = new List<Expression>
                {
                    Assign(
                        discriminatorValueVariable,
                        valueBufferParameter.CreateValueBufferReadValueExpression(typeof(string), 0, null))
                };

                var derivedConcreteEntityTypes = entityType.GetDerivedTypes().Where(dt => !dt.IsAbstract()).ToArray();
                var switchCases = new SwitchCase[derivedConcreteEntityTypes.Length];
                for (var i = 0; i < derivedConcreteEntityTypes.Length; i++)
                {
                    var discriminatorValue = Constant(derivedConcreteEntityTypes[i].ShortName(), typeof(string));
                    switchCases[i] = SwitchCase(Constant(derivedConcreteEntityTypes[i], typeof(IEntityType)), discriminatorValue);
                }

                var defaultBlock = entityType.IsAbstract()
                    ? CreateUnableToDiscriminateExceptionExpression(entityType, discriminatorValueVariable)
                    : Constant(entityType, typeof(IEntityType));

                expressions.Add(Switch(discriminatorValueVariable, defaultBlock, switchCases));
                baseCondition = Lambda(Block(new[] { discriminatorValueVariable }, expressions), valueBufferParameter);
            }
            else
            {
                baseCondition = base.GenerateMaterializationCondition(entityType, nullable);
            }
[...]


```

So I only tried to let my custom `EntityShaperExpression `inherit also from `RelationalEntityShaperExpression `(all my  other code is not affected by this)and check if the ovverride fix the problem.
But just after I wrote the first post, I realized that wath `RelationalEntityShaperExpression `expect to found when `entityType.FindDiscriminatorProperty()` is performed, is quite sure done on the model when the model is built, also because if i check the models of the two Contexts also the metadata are different (With Sql Server Provider the Discriminator is not a property(only one annotation), with my provider the Discriminator is a property) so surely in the Sql Server Provider there is a Service that when the model is built, it prepare the metadata in a "right way". Until now, in my provider I wrote no service to manage the model so I have to found the Service in the Sql Server Provider that avoid that the discriminator is a property, see wath it do on the discriminator and reproduce it on my provider.

**Comment by ajcvickers** [comment]
Services in the Relational assembly can only be expected to work when the provider is a relational provider. The model building services in the Relational assembly do things like set the Discriminator where appropriate. You should not uses services from the Relational assembly if your provider is not a relational provider.

**Comment by GLuca74** [comment]
Yes, I agree, I not want to use Relation Assembly, just found the service that set the discriminator and see wath it do

**Comment by ajcvickers** [comment]
`Microsoft.EntityFrameworkCore.Metadata.Conventions.DiscriminatorConvention`

**Comment by GLuca74** [comment]
Many thanks
