### ISSUE TITLE
Fix for #2950 not working

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3015]
Still same issue with the INSERT statement ending in two semi-colons.
I think the issue may be caused by the fact, that the SQL statements here are hard-coded to end with ";" - https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/HistoryRepository.cs

**Comment by bricelam** [comment]
Hmm, [the tests](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs#L40-L41) seem to only have one...

**Comment by ErikEJ** [comment]
Hmm.. I will add that test, it is missing from my test suite. sql ce only allows a single statement per batch...

**Comment by ErikEJ** [comment]
Ah, I think the test packages on MyGet were not updated yet!

**Comment by ErikEJ** [comment]
@bricelam thanks for pointing me to the tests, btw,. I had several bugs in my migrations code, that those tests exposed :fire:
