### ISSUE TITLE
Missing closing ) for decimal type when generating migration. Core 7.0.2

### ISSUE THREAD

**Issue by Eaglef90** [dotnet/efcore#30169]
It appears that when using `TypeName = "decimal(3,2)"` as a DataAnnoation the migration generated does not contain the closing ")" for the database type

### Include your code
Entity:

```
    public sealed class ReleaseDate
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public string ReleaseTitle { get; set; }

        [Column(TypeName = "decimal(3,2")]
        public decimal? VersionNumber { get; set; }
        public DateTime? DateReleased { get; set; }
        public string Platform { get; set; }
        public string Region { get; set; }
        public string? Note { get; set; }
        public int SectionID { get; set; }

        [ForeignKey("SectionID")]
        public Section Section { get; set; }
    }
```

Generated line in the migration:

```
migrationBuilder.CreateTable(
                name: "ReleaseDates",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ReleaseTitle = table.Column<string>(type: "varchar(250)", unicode: false, nullable: false),
                    VersionNumber = table.Column<decimal>(type: "decimal(3,2", nullable: true),
                    DateReleased = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Platform = table.Column<string>(type: "varchar(250)", unicode: false, nullable: false),
                    Region = table.Column<string>(type: "varchar(250)", unicode: false, nullable: false),
                    Note = table.Column<string>(type: "varchar(250)", unicode: false, nullable: true),
                    SectionID = table.Column<int>(type: "int", nullable: false)
                },
```
Attached a zip that has the entire DB schema and generated migration file

### Include provider and version information

EF Core version: 7.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4.4
[FFInfo.DAL.zip](https://github.com/dotnet/efcore/files/10527955/FFInfo.DAL.zip)

**Comment by pinkfloydx33** [comment]
Just an observer here, but I think your repro code is the culprit. Compare these two lines:

```csharp 
[Column(TypeName = "decimal(3,2")]  // your repro
[Column(TypeName = "decimal(3,2)")] // TypeName from OP
```

I think you're visualalizing the attribute's closing `)` as part of the data type... I know I did on first glance. It would appear that the migration is doing exactly what you asked it to.

**Comment by roji** [comment]
In your ReleaseData definition above I'm seeing:

```c#
        [Column(TypeName = "decimal(3,2")]
        public decimal? VersionNumber { get; set; }
```

Isn't that the bug in your code there? EF just takes the value of that attribute, it doesn't do anything to it.

**Comment by Eaglef90** [comment]
> 

You are correct, I looked at it a few times and I never noticed it. I think, just like you, I was visualizing the attribute's `)` as part of the data type. I corrected the entity and the migration is being generated correctly. I will close this out as it was a type-0 in my part I could not see. Thanks for the help.
