### ISSUE TITLE
Complex query generated for Include(Where).SingleOrDefault

### ISSUE THREAD

**Issue by RaicuRobert** [dotnet/efcore#30170]
### Issue
I can't understand why such a complex query is generated.
The goal is to load the IndividualTourProvider that has the Tour with id tourId and also include that Tour.

Consider the query
```C#
await _context.IndividualTourProviders
                .Include(t => t.Tours.Where(tour => tour.Id == tourId))
                .SingleOrDefaultAsync(tp => tp.Tours.Any(t => t.Id == tourId),
                cancellationToken);
```
it is generated as
```SQL
 SELECT [t0].[Id], [t0].[Description], [t0].[Identification_FirstName], [t0].[Identification_LastName], [t1].[Id], [t1].[Description], [t1].[IndividualTourProviderId], [t1].[Itinerary], [t1].[Name]
      FROM (
          SELECT TOP(2) [i].[Id], [i].[Description], [i].[Identification_FirstName], [i].[Identification_LastName]
          FROM [IndividualTourProviders] AS [i]
          WHERE EXISTS (
              SELECT 1
              FROM [Tours] AS [t]
              WHERE [i].[Id] = [t].[IndividualTourProviderId] AND [t].[Id] = @__tourId_0)
      ) AS [t0]
      LEFT JOIN (
          SELECT [t2].[Id], [t2].[Description], [t2].[IndividualTourProviderId], [t2].[Itinerary], [t2].[Name]
          FROM [Tours] AS [t2]
          WHERE [t2].[Id] = @__tourId_0
      ) AS [t1] ON [t0].[Id] = [t1].[IndividualTourProviderId]
      ORDER BY [t0].[Id]
```

I would expect a query of the form:
```SQL
select top(1) * from  [IndividualTourProviders]
join Tours on Tours.IndividualTourProviderId = [IndividualTourProviders].Id
where tours.Id = 51
```

### Code

The classes in essence are
```C#
class IndividualTourProvider {
 public int Id { get; set;}
 public List<Tour> Tours {get;set;}
}

class Tour {
 public int Id { get; set;}
}
```

The debug info being 
```
 Generated query execution expression: 
      'queryContext => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<IndividualTourProvider>(
          asyncEnumerable: new SingleQueryingEnumerable<IndividualTourProvider>(
              (RelationalQueryContext)queryContext, 
              RelationalCommandCache.QueryExpression(
                  Client Projections:
                      0 -> Dictionary<IProperty, int> { [Property: IndividualTourProvider.Id (_Id, int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: IndividualTourProvider.Description (_description, string) Required, 1] }
                      1 -> Dictionary<IProperty, int> { [Property: IndividualIdentification.IndividualTourProviderId (no field, int) Shadow Required PK FK AfterSave:Throw, 0], [Property: IndividualIdentification.FirstName (string) Required, 2], [Property: IndividualIdentification.LastName (string) Required, 3] }
                      2 -> 0
                      3 -> Dictionary<IProperty, int> { [Property: Tour.Id (_Id, int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 4], [Property: Tour.Description (_description, string) Required, 5], [Property: Tour.IndividualTourProviderId (no field, int?) Shadow FK Index, 6], [Property: Tour.Itinerary (_itinerary, string) Required, 7], [Property: Tour.Name (_name, string) Required, 8] }
                      4 -> 4
                  SELECT t0.Id, t0.Description, t0.Identification_FirstName, t0.Identification_LastName, t1.Id, t1.Description, t1.IndividualTourProviderId, t1.Itinerary, t1.Name
                  FROM 
                  (
                      SELECT TOP(2) i.Id, i.Description, i.Identification_FirstName, i.Identification_LastName
                      FROM IndividualTourProviders AS i
                      WHERE EXISTS (
                          SELECT 1
                          FROM Tours AS t
                          WHERE ((i.Id != NULL) && (i.Id == t.IndividualTourProviderId)) && (t.Id == @__tourId_0))
                  ) AS t0
                  LEFT JOIN 
                  (
                      SELECT t2.Id, t2.Description, t2.IndividualTourProviderId, t2.Itinerary, t2.Name
                      FROM Tours AS t2
                      WHERE t2.Id == @__tourId_0
                  ) AS t1 ON t0.Id == t1.IndividualTourProviderId
                  ORDER BY t0.Id ASC), 
              null, 
              Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, IndividualTourProvider>, 
              Touro.Infrastructure.TouroDbContext, 
              False, 
              True, 
              True
          ), 
          cancellationToken: queryContext.CancellationToken)'
```

### Workaround

It does generate a less complex query if I add a navigation property on the other side also. But that might not be a solution for everyone.

```C#
var tour = await _context.Tours.Include(t => t.IndividualTourProvider)
                .FirstOrDefaultAsync(t => t.Id == tourId);
return tour.IndividualTourProvider;
```
```SQL
SELECT TOP(1) [t].[Id], [t].[Description], [t].[IndividualTourProviderId], [t].[Itinerary], [t].[Name], [i].[Id], [i].[Description], [i].[Identification_FirstName], [i].[Identification_LastName]
      FROM [Tours] AS [t]
      INNER JOIN [IndividualTourProviders] AS [i] ON [t].[IndividualTourProviderId] = [i].[Id]
      WHERE [t].[Id] = @__tourId_0
```

### Provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 10
IDE:  Visual Studio 2022 17.5 preview 3.0

**Comment by ska737** [comment]
The LINQ you provided and the query you in SQL that you think it should be are very different. To generate the query you supplied in SQL, it would be:
```csharp
await _context.IndividualTourProviders
                .Include(t => t.Tours)
                .FirstOrDefaultAsync(tp => tp.Tours.Id == tourId),
                cancellationToken);
```
I do not believe this is a bug. The complex query is caused by the `.SingleOrDefault()` and the filtered `.Include()`.

**Comment by RaicuRobert** [comment]
@ska737 Do you mean this? 
```C#
await _context.IndividualTourProviders
                .Include(t => t.Tours)
                .FirstOrDefaultAsync(tp => tp.Tours.Any(t=> t.Id == tourId)),
                cancellationToken);
```
I don't remember seeing the ``` tp.Tours.Id == tour``` syntax and it's not working.

Also, this will load all tours into memory and I don't want this.

My use case is in a DDD scenario where I only need this specific tour entity loaded such that I delete it through the aggregate root IndividualTourProvider.

**Comment by ska737** [comment]
My apologies, I meant to do the `.Any()` with the filter.
So you need to delete the Tour through the IndividualTourProvider using the entities instead of the context? I'm just trying to make sure I understand... That seems like a heavy load just to delete an entity when you have the ID already.
But, to solve your specific case, the way EF pulled it with the complex query is actually correct. It gets EXACTLY what you asked for.

**Comment by RaicuRobert** [comment]
I'm trying to do a by the book implementation of DDD for the sake of identifying any painpoints.
Vernon Vaughn said in 'Implementing Domain-Driven Design' that 
`As a rule of thumb, we should try to avoid the use of Repositories (12) from inside Aggregates, if at all possible.`

As such, the only way of removing the Tour is by calling a RemoveTour method on the IndividualTourProvider and then removing it from its Tours list. I can't do it by id, although I did not try to do it with Lazy Loading Proxies.

Probably I will open source the code in the future once I iron all the kinks out as I would like to make a course or write a few articles on it and share the issues I had and the solutions I found.

Considering that the Aggregate and its entities should be updated transactionally, maybe a document store would be a better fit for this situation. I chose the easy path and went with EFCore as it let me focus on the domain more in the beginning.

**Comment by roji** [comment]
> await _context.IndividualTourProviders
                .Include(t => t.Tours.Where(tour => tour.Id == tourId))
                .SingleOrDefaultAsync(tp => tp.Tours.Any(t => t.Id == tourId),
                cancellationToken);

The main thing to understand is that Include simply populates the included navigation (Tours). By design, it does not filter which IndividualTourProviders are fetched, only which Tours are fetched for those IndividualTourProviders. In other words, if you add or remove an Include never changes which IndividualTourProviders are brought back. As @ska737 wrote above, if you want to filter which IndividualTourProviders are fetched, you need to use to specify that in the SingleOrDefault, or a Where clause.

> Considering that the Aggregate and its entities should be updated transactionally, a document store would be a better fit for this situation.

You may also want to look at JSON support for document store functionality within relational databases. EF supports JSON across various providers in various ways.

**Comment by RaicuRobert** [comment]
I was kind of hoping that it could infer more from the query and entity configurations.
If we are to add the data available from configurations and the LINQ query, we might have a way to get the more simple query.
Sadly I don't remember the relational algebra part as I have not done it since Uni.

We can close this issue.
If I have some time I'll look over some algebra and query optimizations.
Meanwhile, can you point me to where this is done in EF?

**Comment by roji** [comment]
> I was kind of hoping that it could infer more from the query and entity configurations.

This isn't really about inference - it's about what Include is designed to do. There are many use cases where users do want to load all IndividualTourProviders, filtering only the related Tours which are fetched for them; that's what Include is designed to do. So it really is a matter of using the right LINQ construct for the thing you'er trying to achieve.

> Meanwhile, can you point me to where this is done in EF?

What exactly are you looking for? The internal implementation inside EF implementing Include?
