### ISSUE TITLE
How to deal with array_agg(column1, column2) in Entity Framework and Postgres?

### ISSUE THREAD

**Issue by CarstenK1** [dotnet/efcore#30183]
I've created a custom object to get the result of an Raw SQL. I used JSONB to aggregate some data. The object is defined like this:

```
modelBuilder.Entity<PermissionWithScopesByPropertyDto>(entity =>
            {
                entity.HasNoKey();
                entity.Property(e => e.Permissions)
                    .HasColumnType("jsonb")
                    .HasColumnName("permissions");
                
                entity.Property(e => e.ResourceId)
                    .HasColumnName("resource_id");

            });
```

This works good, but than I noticed that using array_agg is much faster and I changed the query to use that aggregation function like this:

Select array_agg((code, permission_scope_ids)) ..... that creates an Array of Tupels <string,int[]>. The return datatype is record[]. Now I try to match that to the Entity Framework. The NPGSQL support that Datatype. I've tried using object[] or record as Type, but does not work.  Can entity Framework map that to an Array of Objects?

**Comment by roji** [comment]
@CarstenK1 this is a PostgreSQL-specific question, please reopen it in https://github.com/npgsql/efcore.pg, and also include the relevant parts of your model as well as the SQL you're looking to have EF generate.

**Comment by CarstenK1** [comment]
Thanks, done.
