### ISSUE TITLE
ExecuteSqlRaw(string) fails with FormatException 'Input string was not in a correct format.'

### ISSUE THREAD

**Issue by gavinreid2004** [dotnet/efcore#30188]
I am trying to import email templates from files into my database for testing. These templates are HTML so have style elements, for example
```css
body
{
    font-family: Helvetica Neue, Arial, Helvetica, Geneva, sans-serif;
    font-size: 13px;
}
```

When running tests in LinqPad, a typical stack trace is :
```
   at System.Text.ValueStringBuilder.ThrowFormatInvalidString()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RawSqlCommandBuilder.Build(String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, Object[] parameters)
   at UserQuery.Main(), line 7
```

## Minimal reproduction
Create a table called Test 
```tsql
CREATE TABLE [dbo].[Test](
	[Css] [nvarchar](200) NULL
) ON [PRIMARY]
```
Then, with a context that connects to the database with this table, attempt to run this:
```C#
private string sql = """
INSERT INTO [dbo].[Test]
           ([Css])
     VALUES
           ('minimal { test }')
""";

context.Database.ExecuteSqlRaw(sql);
```

### Workaround

To side step the issue I am using a `SqlCommand` to execute the insert statement.

```C#
private async Task RunAsCommand(string sql)
{
	var cnn = context.Database.GetDbConnection();
	try
	{
		await using var cmd = cnn.CreateCommand();
		cmd.CommandText = sql;
		await cnn.OpenAsync();
		await cmd.ExecuteNonQueryAsync();
		await cnn.CloseAsync();
	}
	catch (Exception)
	{
		if (cnn.State == ConnectionState.Open)
			await cnn.CloseAsync();

		throw;
	}
}
```
## Environment
EF Core version: 7.0.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7
OS: Windows 10

**Comment by roji** [comment]
You need to escape the curlies by duplicating them, since they're being interpreted as a placeholder:

```c#
private string sql = """
INSERT INTO [dbo].[Test]
           ([Css])
     VALUES
           ('minimal {{ test }}')
""";
```

Regardless, it's recommended to switch to ExecuteSql instead of ExecuteSqlRaw, which provides protection against accidental SQL injection. You can also combine this with the new C# raw string literals to avoid having to duplicate your curlies:

```c#
FormattableString sql =
$$"""
INSERT INTO Blogs (Name) VALUES ('minimal { test }')
""";

ctx.Database.ExecuteSql(sql);
```

**Comment by gavinreid2004** [comment]
Thank you for your swift reply. In my code I am not using string literals, I used a literal here just for simplicity, I am loading the actual text from resources/files which are scripts that can be run directly from SSMS. - I am in the process of migrating a large linq to sql project to EF Core and our scripts are in a database project so I am running these scripts currently to reduce the changes at this point.

Based on your suggestion however I can change my execution code to:
```C#
var fmtSql = FormattableStringFactory.Create(sql.Replace("{", "{{").Replace("}","}}"));
context.Database.ExecuteSql(fmtSql);
```

**Comment by roji** [comment]
Yes, you can. Although if you're loading your SQL this way, using ExecuteSql no longer really has any advantage over ExecuteSqlRaw, since your SQL is coming from the outside, and you're responsible for preventing any SQL injection in any case.
