### ISSUE TITLE
SQL Server Graph support

### ISSUE THREAD

**Issue by wstaelens** [dotnet/efcore#30180]
SQL Server (express) has Graph capabilities, but there is almost nothing provided to work with it.

Working with Graph capabilities in SQL Server (express). (maybe link to [dotnetrdf](https://dotnetrdf.org/) project?)

ultimate goal:
Easily create graphs with EF (who knows an rdf triplestore? 😃 )
https://codingsight.com/how-to-make-use-of-sql-server-graph-database-features/
https://learn.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample?view=sql-server-ver15

**Comment by ajcvickers** [comment]
Duplicate of #8527. Please vote for that issue.

**Comment by roji** [comment]
Duplicate of #8527
