### ISSUE TITLE
RelationalConnectionDependencies depending on IRelationalCommandBuilderFactory

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#30187]
## Ask a question

When looking into the dependencies of RelationalConnectionDependencies, it has a dependency on 'IRelationalCommandBuilderFactory'.

```C#
public RelationalConnectionDependencies(
        IDbContextOptions contextOptions,
        IDiagnosticsLogger<DbLoggerCategory.Database.Transaction> transactionLogger,
        IRelationalConnectionDiagnosticsLogger connectionLogger,
        INamedConnectionStringResolver connectionStringResolver,
        IRelationalTransactionFactory relationalTransactionFactory,
        ICurrentDbContext currentContext,
        IRelationalCommandBuilderFactory relationalCommandBuilderFactory)
```

Logically a connection shouldn't depend on the command related dependencies. 

Please could someone let me know why does EFCore need to initialize IRelationalCommandBuilderFactory for initializing RelationalConnection. Is this necessary to have?

### Include provider and version information
EF Core version: 7.0.0
Database provider: 
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

**Comment by shvmgpt116** [comment]
@ajcvickers

**Comment by roji** [comment]
@shvmgpt116 is this dependency causing you a particular problem, or are you just asking the question ecause you're interested in understanding EF's internal design?

**Comment by shvmgpt116** [comment]
RelationalCommandBuilderDependencies depends on IRelationalTypeMappingSource.
```C#
public RelationalCommandBuilderDependencies(
        IRelationalTypeMappingSource typeMappingSource,
        IExceptionDetector exceptionDetector)
```

This means whenever we want RelationalConnection, IRelationalTypeMappingSource would have to be initialized.
However a database provider may want to provide the type mapping based on the db version the customer is using. For this we would need to have IRelationalConnection initialized whenever TypeMappingSource constructor is called.
However this is not happening. When TypeMappingSource constructor is called, we don't have IRelationalConnection initialized.
