### ISSUE TITLE
Navigation json column IReadOnlyCollection

### ISSUE THREAD

**Issue by cdrfenix** [dotnet/efcore#30195]
Json column mapped into a navigational IReadOnlyCollection property produces a System.Security.VerificationException when projecting in a query, for example:

**Entity**

```
public class User
{
    private readonly List<Image> _images = new();

    public Id Id { get; private set; } = null!;
    public string Name { get; private set; } = string.Empty;

    public IReadOnlyCollection<Image> Images { get => _images; }
}
```
**Builder**

```
modelBuilder.Entity<User>().OwnsMany(x => x.Images, ownedType =>
{
    ownedType.ToJson();
});
```

**Query**

```
var query = 
  from user in _users
  select new { Images = user.Images }
  
return await query.ToListAsync();
```

I traced the issue to this part: https://github.com/dotnet/efcore/blob/46fc0e331e91a6a2ac3aa6a7cc46d1fb7eee468e/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs#L1256

Also here: https://github.com/dotnet/efcore/blob/06a41bb4d04eba17826e1af8ebeddc14417f90a2/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs#L942

Setting ICollection in the navigational property makes it work, but is not optimal, ICollection still exposes Add methods and even if it throws a exception its still annoying.

**Environment**

EF Core version: 7.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7
OS: Windows 11 Pro

**Comment by AndriySvyryd** [comment]
Also consider https://github.com/dotnet/efcore/issues/21176

**Comment by cdrfenix** [comment]
Any news on this?

**Comment by roji** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 8.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by maumar** [comment]
this is now fixed, as part of some other improvement around JSON feature, closing

**Comment by maumar** [comment]
dupe of https://github.com/dotnet/efcore/issues/31760 (actually the other way around, but we tracked the bug fix to that other issue)
