### ISSUE TITLE
SQL Server: use EnableOptimizedParameterBinding in SaveChanges

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#30190]
SqlClient introduced [EnableOptimizedParameterBinding](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlcommand.enableoptimizedparameterbinding?view=sqlclient-dotnet-standard-5.1), which improves performance for commands with large numbers of parameters; it also disables the use of Output/InOut parameters.

We should enable this option in SaveChanges - our batching there causes us to use lots of parameters on a single command. This would help in scenarios such as bulk insertion and similar. Note that we do use output parameters in SaveChanges sproc binding (so cannot use it there).

/cc @Wraith2 @ErikEJ

**Comment by ajcvickers** [comment]
@roji Is this different from #29841?

**Comment by roji** [comment]
Absolutely not!

**Comment by roji** [comment]
Duplicate of #29841
