### ISSUE TITLE
Use init setter for DbSet

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/efcore#30198]
In the documentation, when scaffolding and reverse engineering a database the dbsets are currently defined as:
```cs
public DbSet<User> Users { get; set; }
```

Change this to to use `init` instead of `set` like this:
```cs
public DbSet<User> Users { get; init; }
```

**Comment by roji** [comment]
@vanillajonathan EF is the one injecting the DbSet property via reflection, in the DbContext constructor. With that in mind, any particular value in doing the above change?

**Comment by vanillajonathan** [comment]
It does not need to be `set`, so it is unnecessarily so, having `init` seems to work.

It seems it still is `set` because it has been so since before the introduction of the `DbContext` prior to the existence of the `init` keyword, so it is for legacy reasons that it hasn't taken advantage of modern C#.

Using `init` is more clear as how it is intended to be used and not used it. Having it as `set` is misleading as it leads users to believe that it is something that perhaps they can set.

**Comment by ajcvickers** [comment]
Note from triage: the value of making this the default seems low, and it is only one of several patterns for DbSet properties. The pattern used can easily be changed by [customizing the T4 templates](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli).
