### ISSUE TITLE
IEnumerable Contains(...) generates non parameterized sql

### ISSUE THREAD

**Issue by gokhanabatay** [dotnet/efcore#30201]
We are using postgresql with ef core 7.

If query parameter is IEnumerable then it generates non parameterized sql.

```c#
var cardsUnderDek = new List<string>(){"1","2"}.AsEnumerable();
var cardTokens = await context.Set<TblCardToken>()
                .Where(x => cardsUnderDek.Contains(x.CardUnderDek) && x.KeyId == cryptoProvider.KeyId)
                .ToListAsync();

```
Sql is not parameterized, `t.card_under_dek IN ('1','2')`

```sql
SELECT t.card_no, t.tenant_id, t.card_under_dek,t.key_id
FROM tbl_card_token AS t
WHERE t.tenant_id= @__ef_filter__Value_0 AND (t.card_under_dek IN ('1','2') ) AND t.key_id = @__cryptoProvider_KeyId_1
```

If we remove `.AsEnumerable()` it generates parameterized sql.

```c#
var cardsUnderDek = new List<string>(){"1","2"};
var cardTokens = await context.Set<TblCardToken>()
                .Where(x => cardsUnderDek.Contains(x.CardUnderDek) && x.KeyId == cryptoProvider.KeyId)
                .ToListAsync();
```

But sql contains odd is null and is not null conditions. ` OR ((t.card_under_dek IS NULL) AND (array_position(@__cardsUnderDek_0, NULL) IS NOT NULL))`

```sql
SELECT t.card_no, t.tenant_id, t.card_under_dek,t.key_id
FROM tbl_card_token AS t
WHERE t.tenant_id= @__ef_filter__Value_0 AND (t.card_under_dek = ANY (@__cardsUnderDek_0) OR ((t.card_under_dek IS NULL) AND (array_position(@__cardsUnderDek_0, NULL) IS NOT NULL))) AND t.key_id = @__cryptoProvider_KeyId_1
```

**Comment by gokhanabatay** [comment]
@ajcvickers could you explain why ` OR ((t.card_under_dek IS NULL) AND (array_position(@__cardsUnderDek_0, NULL) IS NOT NULL))` is generated.

And why IEnumerable.Contains(...) generetas different sql then list.Contains(...) linked issue #13617  is based on IEnumerable am i missing something?

Also I would like to add this note, this is basic feature I am still trying to understand why it does not implemented until today.
Please look nhibernate or hibernate there are several choices for this issue.

**Comment by gokhanabatay** [comment]
Our application supports SqlServer/Oracle/PostgreSql with the same code base, its just an environment variable that decides which database will be used at runtime.

Postgresql supports array parameter with `= ANY` clause but sql server and oracle does not. The issue with PostgreSQL i described above.

Is it possible to rewrite expression rather then using different extension method like below.

If expression type is method call expression and method is one of  Contains/Any and input is IEnumerable then rewrite expression like below only for sql server and oracle?

Because using non parameterized sql is too bad for memory and performance.

https://github.com/dotnet/efcore/blob/main/src/EFCore/Diagnostics/IQueryExpressionInterceptor.cs

```c#
public static IQueryable<TQuery> Exists<TQuery, TKey>(this IQueryable<TQuery> queryable,
   Expression<Func<TQuery, TKey>> propertyExpression, IEnumerable<TKey> values)
{
    if (values.Any())
    {
        var body = values
            .Select(p =>
            {
                Expression<Func<TKey>> expression = () => p;
                return Expression.Equal(propertyExpression.Body, expression.Body);
            })
            .Aggregate((a, b) => Expression.OrElse(a, b));

        var whereClause = Expression.Lambda<Func<TQuery, bool>>(body, propertyExpression.Parameters);
        queryable = queryable.Where(whereClause);
    }

    return queryable;
}

public static IQueryable<TQuery> NotExists<TQuery, TKey>(this IQueryable<TQuery> queryable,
   Expression<Func<TQuery, TKey>> propertyExpression, IEnumerable<TKey> values)
{
    
    if (values.Any())
    {
        var body = values
            .Select(p =>
            {
                Expression<Func<TKey>> expression = () => p;
                return Expression.NotEqual(propertyExpression.Body, expression.Body);
            })
            .Aggregate((a, b) => Expression.AndAlso(a, b));


        var whereClause = Expression.Lambda<Func<TQuery, bool>>(body, propertyExpression.Parameters);
        queryable = queryable.Where(whereClause);
    }

    return queryable;
}
```

**Comment by gokhanabatay** [comment]
Hi @ajcvickers 
Below fixes postgresql IEnumerable issue query generated with parameterized for IEnumerables, but I am struggling with SqlServer and Oracle because I cannot fetch values of ParameterExpression. 
I suppose that if I can get the values of parameter expression it will fail because the count of IEnumerable parameter is important. If ef expression cache is not consider count of enumerable parameter then this approach will fail. Could you guide us?
 
```c#
public class QueryExpressionInterceptor : IQueryExpressionInterceptor
{
    public Expression QueryCompilationStarting(Expression queryExpression, QueryExpressionEventData eventData)
    => new QueryRewriterExpressionVisitor().Visit(queryExpression);

    private class QueryRewriterExpressionVisitor : ExpressionVisitor
    {
        private static readonly MethodInfo ContainsMethod
            = typeof(Enumerable).GetMethods()
                .Single(m => m.Name == nameof(Enumerable.Contains) && m.GetParameters().Length == 2);

        protected override Expression VisitMethodCall(MethodCallExpression methodCallExpression)
        {
            var methodInfo = methodCallExpression.Method;
            if (methodInfo.DeclaringType == typeof(Enumerable)
                && methodInfo.Name == nameof(Enumerable.Contains)
                && methodInfo.GetParameters().Length == 2)
            {
                if(methodCallExpression.Arguments[0] is ParameterExpression parameter &&
                    !parameter.Type.IsArray &&
                    parameter.Type.IsGenericType &&
                    methodCallExpression.Arguments[1] is MemberExpression member)
                {
                    var type = parameter.Type.GenericTypeArguments[0];
                    return Expression.Call(ContainsMethod.MakeGenericMethod(type), 
                        Expression.Parameter(type.MakeArrayType(), 
                        parameter.Name), member);
                }
            }

            return base.VisitMethodCall(methodCallExpression);
        }
    }
}
```

**Comment by roji** [comment]
> could you explain why  OR ((t.card_under_dek IS NULL) AND (array_position(@__cardsUnderDek_0, NULL) IS NOT NULL)) is generated

This is a PG-specific question; the extra SQL is there in order to make sure the query works as expected with regards to nulls. Since your `card_under_dek` column is null, the extra code is needed in order for the query to return rows where that column is null and the provided array also contains null. If you make card_under_dek non-nullable, you should see simpler SQL which doesn't include this.

> And why IEnumerable.Contains(...) generetas different sql then list.Contains(...) linked issue https://github.com/dotnet/efcore/issues/13617 is based on IEnumerable am i missing something?

The PG provider currently supports Contains over array/List, but not over arbitrary IEnumerables. This is because only array/List are mapped to PG arrays, but specifically for the translation of IEnumerable.Contains this is something that we could consider relaxing. Is there a specific reason you need to pass the List as an IEnumerable rather than as a List?

For other databases, as has been pointed out there's no native database array support; as @ajcvickers wrote above, #13617 tracks doing something better there.

**Comment by gokhanabatay** [comment]
> The PG provider currently supports Contains over array/List, but not over arbitrary IEnumerables. This is because only array/List are mapped to PG arrays, but specifically for the translation of IEnumerable.Contains this is something that we could consider relaxing. Is there a specific reason you need to pass the List as an IEnumerable rather than as a List?
> 

There is no specific reason to pass as an IEnumerable, using IEnumerable without knowing causes major issue both application and database side. We kindly ask somehow to support `in` with parameters for all databases or if array parameter is not supported rewrite `Contains` to `or` expression.

**Comment by aradalvand** [comment]
This seems to have been fixed in EF8, by the way. For anyone still curious.
