### ISSUE TITLE
Switch to Prevent Scaffolding of Connection String in Class Library

### ISSUE THREAD

**Issue by MChez** [dotnet/efcore#30215]
## Issue
The OnConfiguration  code generated by the EF 7 scaffolding from an existing SQL Server database is causing issues with our development and deployment process.

A database is created and managed from a database project in Visual Studio 2022.

We use a command similar to the following to scaffold the EF DbContext and model classes from an existing database:

`dotnet ef dbcontext scaffold "Data Source=(localdb)\ProjectsV13;Initial Catalog=MyDatabase" Microsoft.EntityFrameworkCore.SqlServer --schema myschema --context MyContext --context-dir Data --output-dir DbModels --data-annotations --force`

In EF 6 the default OnConfiguration pattern generated code like this:

``` C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
        optionsBuilder.UseSqlServer("Data Source=(localdb)\\ProjectsV13;Initial Catalog=MyDatabase");
    }
}
```

This pattern allowed us to scaffold a SQL Server database into a class library which is then referenced by an ASP.NET Core API project without requiring us to modify the generated code. The setting for the database connection is set in the API project appsettings.json files. We do not modify the scaffolded code which allows us to: update the database project, publish the changes, then run the same scaffold command to refresh the EF models and context. The EF model is always driven by database first development.

I recently upgraded the EF version to EF 7. The default OnConfiguration pattern generates code like this:

``` C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseSqlServer("Data Source=(localdb)\\ProjectsV13;Initial Catalog=MyDatabase");
```

Because you have dropped the `if (!optionsBuilder.IsConfigured)` check, options set in the API project cannot replace the connection string added by the scaffold in the core project. This requires us to either modify the scaffolded code, which means we need to remember to modify the code every time we update the database, or we have to wrap the generated code in a way that overrides the scaffolded code without modify it.

I have a solution for wrapping the code, but it is a bit ugly:

I rename the context generated in the scaffold command to MyContextScaffold.

`dotnet ef dbcontext scaffold "Data Source=(localdb)\ProjectsV13;Initial Catalog=MyDatabase" Microsoft.EntityFrameworkCore.SqlServer --schema myschema --context MyContextScaffold --context-dir Data --output-dir DbModels --data-annotations --force`

I create a wrapper class for the generated scaffold class by using inheritance. This makes all the code in the parent scaffolded class available through the wrapper class (it also prevents me from needing to rename any references in the API project). I then need to override the constructors and the offending OnConfiguration method:

``` C#
using Microsoft.EntityFrameworkCore;

namespace MyProject.Core.Data;

public class MyContext : MyContextScaffold
{
    public MyContext()
    {
    }

    public MyContext(DbContextOptions<MyContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // This code is similar to that in EF 6 scaffold but was removed in EF 7 scaffold
        if (!optionsBuilder.IsConfigured)
        {
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```

In order to allow the scaffolded class to pass the DbContextOptions of type MyContext to the DbContext class, I extend the MyContextScaffold class using a partial class. This is required so that the DbContext class calls the OnConfiguration method of the wrapper class and not the scaffolded class. This means the parent (scaffold) class has a reference to a child (wrapper) class, which is I why I call this ugly:

``` C#
using Microsoft.EntityFrameworkCore;

namespace MyProject.Core.Data
{
    public partial class MyContextScaffold
    {
        // This is required to allow the MyContext wrapper to override the OnConfiguration
        // of the MyContextScaffold class generated by EF 7 scaffold command.
        // This removes the need to constantly modify the generated context class when updating the
        // context from changes made to the database.
        public MyContextScaffold(DbContextOptions<MyContext> options)
            : base(options)
        {
        }
    }
}
```

**NB:** There may be a better way of doing this but I had issues trying to convert DbContextOptions\<MyContext\> to DbContextOptions\<MyContextScaffold\>. I need to improve my C# generics knowledge.

## Proposed Solution
Can you add a switch to the `dotnet ef dbcontext scaffold` command that would completely remove the database connection string from the generated scaffold code, something like `--remove-connection`. The generated OnConfiguration code would not be created or it would be simply:

`protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {}`

This also has the advantage of removing the `#warning` from the generated code.

**NB:** The method of removing the connection string with the `name=` pattern will not work because the scaffolded code is being generated in a class library. A class library rarely has a settings file.

And/Or could you revert to using the OnConfiguration code generated in EF 6:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
        optionsBuilder.UseSqlServer("Data Source=(localdb)\\ProjectsV13;Initial Catalog=MyDatabase");
    }
}
```

**NB:** I couldn't find a way of modifying the expression-bodied method with the `!optionsBuilder.IsConfigured` condition.

**Comment by ErikEJ** [comment]
It is already there: --no-onconfiguring

**Comment by MChez** [comment]
@ErikEJ Thanks for the information. I read that documentation a while ago and completely forgot to check it again when I ran into this problem. Sorry to bother you.
