### ISSUE TITLE
Adding a no-restore argument for building

### ISSUE THREAD

**Issue by soc-martin** [dotnet/efcore#30222]
I have an issue generating a migration bundle where the NuGet dependencies need not be restored.

I'd like to have the no-restore argument added to the build process.

**Comment by ajcvickers** [comment]
Related to #27456

**Comment by ajcvickers** [comment]
@soc-martin A restore will always be needed since the temporary project is new and therefore, by definition, does not have packages restored. However, as #27456, we could ignore errors in the restore.
