### ISSUE TITLE
Prevent changing value of columns by attribute

### ISSUE THREAD

**Issue by inlineHamed** [dotnet/efcore#30238]
I want to make sure a column value is not changed by an EF query or even someone querying the database directly. By now the best solution I found is to create a trigger like this:

```
CREATE TRIGGER Person_Type_Readonly ON AspNetUsers AFTER UPDATE
AS IF UPDATE(Type) BEGIN
	THROW 50017, 'Person.Type can not be updated', 16
	ROLLBACK TRANSACTION
END
```
(If you have better code/solution for this part please share it)
(I only use SQL Server)

So by now I need to add an empty migration and use migrationBuilder.Sql("....") and paste this code everytime I want to make a column readonly.
I'm wondering if instead I can use an Attribute in my C# class like this:

```
public class ApplicationUser
{
   [ReadOnly]
   public PersonType Type {set;get;}
}
```

So some code in OnModelCreating would scan the Entities to find props with this attribute and add the proper Trigger to snapshot and next migration. indeed, it should drop the trigger whenever detect removal of the attribute.

**Comment by roji** [comment]
Read-only columns isn't a built-in feature of any database I'm aware of; it's indeed possible to do that via a trigger (as you've done above), but I don't see EF having a 1st-class feature for that.

However, it should be possible to implement this by adding your own convention type, which identifies the [ReadOnly] attribute and adds metadata to it; then, override your provider's MigrationSqlGenerator to pick up that metadata and emit the trigger code. This isn't trivial, but shouldn't be too hard either.

**Comment by inlineHamed** [comment]
Thanks, I will try that.
