### ISSUE TITLE
Query: incorrect results for complex predicate with bitwise AND operation with bool args

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#30245]
query:

```cs
from o1 in context.Set<OperatorEntityString>()
from o2 in context.Set<OperatorEntityString>()
from o3 in context.Set<OperatorEntityBool>()
where ((EF.Functions.Like(o2.Value, "B") || o3.Value) & (o1.Value != null)) != false
select new { Value1 = o1.Value, Value2 = o2.Value, Value3 = o3.Value };
```

that predicate gets "optimized" out completely, but it's actually doing something when executed on L2O

**Comment by maumar** [comment]
problem is IsNull checks on bitwise operations with bool values are not handled correctly. On database those ops behave like regular binary, meaning if any of the values is null the result is also null. However on C# those ops behave like AndAlso/OrElse, meaning `NULL & false` returns `false`, `NULL | true` returns `true`. We can either provide proper expansions for IsNull/IsNotNull or try normalize bitwise on bool arguments into AndAlso/OrElse.

Expansions look like this:

```cs
a & b == null -> (a == null && b == null) || (a == null && b == true) || (a == true && b == null)
a | b == null -> (a == null && b == null) || (a == null && b == false) || (a == false && b == null)
a & b != null -> (a != null && b != null) || (a == null && b == false) || (a == false && b == null)
a | b != null -> (a != null && b != null) || (a == true && b == null) || (a = null && b == true)
```

**Comment by ranma42** [comment]
I went forward and tried it out in
 - #33873
