### ISSUE TITLE
NotSupportedException result when using scalar returning function

### ISSUE THREAD

**Issue by go2toa** [dotnet/efcore#30258]
NotSupportedException result when using scalar returning function.  A Plural Site Author already created a simple project that shows the issue.  It can be found at:

https://github.com/julielerman/PSBlogEFCore5MappingDemo

I recommend simplifying her integer returning function to this:

```c#
migrationBuilder.Sql(@"
             CREATE FUNCTION [dbo].[TotalSpentbyCustomer]
             (	@CustomerId int	)
             RETURNS int
             AS
             BEGIN
             	
             
             	RETURN 1;
             
             END");
```

per MSDN documentation, her declaration is simple and intended to be accessed only via EF Core

public int TotalSpentByCustomer(int customerId)
     => throw new NotSupportedException();

However, when the client is ran, it throws the exception NotSupportedException, instead of accessing the UDF on Sql Server.  I have the same error in another project wherein the IQueryable object returns fine from the UDF.  It's only an issue with the scalar UDF.   The full stack trace is:

System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=MappingDemo
  StackTrace:
   at MappingDemo.SalesContext.TotalSpentByCustomer(Int32 customerId) in C:\Temp\zip\PSBlogEFCore5MappingDemo-main\PSBlogEFCore5MappingDemo-main\MappingDemo\SalesContext.cs:line 13
   at MappingDemo.Program.QueryWithScalar() in C:\Temp\zip\PSBlogEFCore5MappingDemo-main\PSBlogEFCore5MappingDemo-main\MappingDemo\Program.cs:line 18
   at MappingDemo.Program.Main(String[] args) in C:\Temp\zip\PSBlogEFCore5MappingDemo-main\PSBlogEFCore5MappingDemo-main\MappingDemo\Program.cs:line 11

EF Core version: 6.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0 in author's example.  My project demonstrates it in 6.0
Operating system: Windows 10 Pro
IDE: Visual Studio 2022 17.3.4

**Comment by roji** [comment]
@go2toa the demo project you linked to presumably works (given that it's a PluralSight demo project); can you please submit a minimal, runnable code sample which shows the error happening?

**Comment by go2toa** [comment]
[MappingDemo.zip](https://github.com/dotnet/efcore/files/10737834/MappingDemo.zip)

 I created this simple project which only demonstrates scalar functions.

**Comment by ajcvickers** [comment]
@go2toa The code in your repro just calls the method on the DbContext instance. It does not use it in a query. See [User-defined function mapping](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping) for information about how functions can be used in queries.

**Comment by go2toa** [comment]
After referencing a table that is irrelevant, the function did return a value.  Closing issue.
