### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by Saotome38** [dotnet/efcore#3025]
I'm porting one services, from the preview in krl using EntityFrameWork 7.0.0-Beta4, to the new version with Dnx, and using EntityFramework 7.0.0-Beta6, i can't find the way to set the relation betwen my entities, i try to follow the examples but theres is always something missing. 

var alm = Builder.Model.GetEntityType(typeof(Almacen));
var fkAlm = alm.ForeignKeys.Single(k => k.ReferencedEntityType == tras);

The error is:

Error   CS1061  'EntityType' does not contain a definition for 'ForeignKeys' and no extension   method 'ForeignKeys' accepting a first argument of type 'EntityType' could be found (are you missing a using directive or an assembly reference?)

**Comment by smitpatel** [comment]
Try replacing `alm.ForeignKeys` to `alm.GetForeignKeys()`

**Comment by Saotome38** [comment]
i make the change to someting like this, i have to run migration proces tosee how does it generate the model. 

            var tras = Builder.Model.GetEntityType(typeof(Traspaso));
            var alm = Builder.Model.GetEntityType(typeof(Almacen));
            var fkAlm =( (List<ForeignKey>) alm.GetForeignKeys());
            tras.AddNavigation( "Almacen", fkAlm[0], pointsToPrincipal: true);

I see other method, is GetForeingKey(), but i don't know wich param send it, or how to send it.

**Comment by rowanmiller** [comment]
You probably want something like:

```
builder.Entity<Post>()
    .Reference(p => p.Blog)
    .Collection(b => b.Posts)
```
