### ISSUE TITLE
EnitytFrameworkCore.InMemory  v6.0.13: FromSqlRaw throws InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.ConstantExpression' to type 'Microsoft.EntityFrameworkCore.Query.QueryRootExpression.

### ISSUE THREAD

**Issue by akm151** [dotnet/efcore#30267]
After upgrading to EFCore 6.0.13, Microsoft.EntityFrameworkCore.InMemory 6.0.13 is throwing an error for 'FromSqlRaw'  expressions.

The same scenario is working properly in EF Core 3.1.7 and EFCore.InMemory 3.1.7 and does not throw the error.

```C#
var someNumber = _dbContext.MaxLogOfSomeNumber.FromSqlRaw($"schema.procedureName").AsEnumerable()?.FirstOrDefault();
//MaxLogOfSomeNumber is of type DbSet
```
The code above throws the error

Unable to cast object of type 'System.Linq.Expressions.ConstantExpression' to type 'Microsoft.EntityFrameworkCore.Query.QueryRootExpression'.

```
at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.GenerateFromSqlQueryRoot(IQueryable source, String sql, Object[] arguments, String memberName)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.FromSqlRaw[TEntity](DbSet`1 source, String sql, Object[] parameters)
```

EF Core version: v6.0.13
Database provider: Microsoft.EntityFrameworkCore.InMemory v6.0.13
Target framework: .NET 6.0
IDE: Visual Studio 2022 17.4.1

**Comment by ajcvickers** [comment]
@akm151 The in-memory provider is not a relational provider and does not support raw SQL. If it wasn't throwing before, then it was returning incorrect results, or, at best, results that were only correct by chance. See [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/).

**Comment by PrefixAM** [comment]
> After upgrading to EFCore 6.0.13, Microsoft.EntityFrameworkCore.InMemory 6.0.13 is throwing an error for 'FromSqlRaw' expressions.

I couldn't reproduce this issue with InMemory v6.0.13, given example does not throw an exception (unlike v7.x.x as in https://github.com/dotnet/efcore/issues/30246).
