### ISSUE TITLE
How to use DbGeography and DbGeometry data types with UseChangeTrackingProxies() mode?

### ISSUE THREAD

**Issue by sergeykorobeynikov** [dotnet/efcore#30269]
I am working with `Geography` and `Geometry` types at the database SQL-level.
To work with objects, there are `DbGeography` and `DbGeometry` data types from the `System.Data.Entity.Spatial` namespace.
For example:
```cs
using System.Data.Entity.Spatial;

namespace Example
{
    public class Location
    {
        public virtual string Name { get; set; }
        public virtual CountryCode Country { get; set; }        
        public virtual DbGeography Center { get; set; }
        public virtual int Zoom { get; set; }
        public virtual DbGeometry Extent { get; set; }
    }
}
```
The `UseChangeTrackingProxies()` mode requires all properties to be `public` and `virtual`, including nested ones.

Currently I am getting the error:
>  ---> System.InvalidOperationException: Property 'DbGeography.WellKnownValue' is not virtual. 'UseChangeTrackingProxies' requires all entity types to be public, unsealed, have virtual properties, and have a public or protected constructor. 'UseLazyLoadingProxies' requires only the navigation properties be virtual.

How can I get around this limitation without turning off the `UseChangeTrackingProxies()` mode?

**Comment by ajcvickers** [comment]
@sergeykorobeynikov I am not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NetTopologySuite.Geometries;

public class Location
{
    public virtual int Id { get; set; }
    public virtual Point Center { get; set; }
    public virtual int Zoom { get; set; }
    public virtual Geometry Extent { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
            await context.Database.EnsureDeletedAsync();
            await context.Database.EnsureCreatedAsync();
        }
    }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseChangeTrackingProxies()
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow", p => p.UseNetTopologySuite())
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Location>();
    }
}
```

**Comment by sergeykorobeynikov** [comment]
@ajcvickers Your code is really working. Now I'm consulting with the XAF developers, which settings break it. Please give me time.

**Comment by sergeykorobeynikov** [comment]
The question is closed. The reason was that the program had several connection settings and one of them did not have the `UseNetTopologySuite()` option. My apologies :-(
