### ISSUE TITLE
Query: Null semantics doesn't convert LIKE to 2-value logic when optimized expansion is not allowed

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#30262]
When optimized expansion is false (i.e. when the predicate is negated) we should remove all the nulls and only reason in 2-value logic. However, for LIKE this is not the case. This is most apparent on sqlite, but also can cause problems for Sql Server.

```cs
from e in ss.Set<NullSemanticsEntity1>()
select new { e.Id, Like = EF.Functions.Like(e.NullableStringA, "Foo") },
```

this will result in nullable object must have a value error on Sqlite
We should consider adding null check to the argument to prevent that.

**Comment by maumar** [comment]
problem: Contains/StartsWIth/EndsWith use LIKE under the covers and they are inherently 3-value logic based. 

null Contains (foo) yields null - result is unknown, foo might be contained in the unknown value, it might not
NOT (null Contains (foo)) also yields null for same reason

**Comment by maumar** [comment]
contains/startwith/endswith - yes, but when Like is called explicitly using EF.Function, (iirc) we decided to leave the relational null semantics.

**Comment by roji** [comment]
Ah I see... Though I'm not sure how we'd distinguish between a LikeExpression produced from EF.Functions.Like and one produced during translation from Contains/StartsWith/EndsWith (given that we do expansion in SqlNullabilityProcessor, much later). But maybe I'm missing something.

So I guess we have another issue for fixing Contains/StartsWith/EndsWith as opposed to this one?

**Comment by ajcvickers** [comment]
Tracked by #30493.
