### ISSUE TITLE
Forcing non-null type when scaffolding

### ISSUE THREAD

**Issue by nikiGagliardi** [dotnet/efcore#30271]
## Is there a way to force scaffolding and set the properties to non-null?

The problem only happens when I set the field to boolean, not null and default to true

on stackoverflow I put various information on what I'm trying to do

https://stackoverflow.com/questions/75436280/entity-framework-core-set-nullable-prop-only-if-default-is-true

### Include provider and version information

EF Core version: 7.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1
Database : PostgreSQL 14
Target framework: .NET 6.0
Operating system: Windows 10 22H2
IDE: Visual Studio 2022 17.4.4

**Comment by ErikEJ** [comment]
It is by design, but EF Core Power Tools allows you to oppose the design.

**Comment by ajcvickers** [comment]
See #13613.

@nikiGagliardi You can also [change the T4 templates](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) to scaffold non-nullable properties.

**Comment by nikiGagliardi** [comment]
A thousand thanks.
browsing the various threads I understood why the property is set to null.
especially thanks to this post https://github.com/dotnet/efcore/issues/10840#issuecomment-362047565
leaving the var to null, during the insert the database will take care of adding the default value
