### ISSUE TITLE
Querying a million records

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#30299]
I'm querying about a million records (from a remote machine) which in management studio takes about 20 seconds and with entity framework it takes about 60 seconds. Why is there such a difference?

It's a simple query just get all the records  from a single table no joins and one check for a single column being non null.

I cannot disable tracking but without tracking its about the same. But still why is there such a performance difference?

Is there anything I can do about this?

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by qsdfplkj** [comment]
I figured it out: avoid Multiple Active Result Sets

**Comment by roji** [comment]
MARS support in SqlClient is known to have various performance issues (as well as other bugs), some of them severe. It's recommended to avoid it.

**Comment by dario-l** [comment]
@roji is this still relevant today?

**Comment by roji** [comment]
@dario-l in what sense?

**Comment by dario-l** [comment]
> @dario-l in what sense?
About MARS. We are using ms sql in-memory tables and MARS is required for transactions with mixed use of disc and in-memory tables.

**Comment by roji** [comment]
@dario-l that's a question for SqlClient, not EF, though I'm not aware of changes on that front.

**Comment by dario-l** [comment]
> @dario-l that's a question for SqlClient, not EF, though I'm not aware of changes on that front.

Right. Thanks for the answer anyway. 😃
