### ISSUE TITLE
asp.net core entity framework core issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30292]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/aspnet-core-entity-framework-core-issue/10274608)._

---
[severity:It's more difficult to complete my work]
Using Razor Pages to create a web app with EF Core for dynamic data using SQL.  Working on a code first scenario but when I come to apply a migration I get the error:

"Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3)'."

I have gone back and re-done the code three times but each time this is what happens.  I am using .net 7 and VS 17.44.

---
#### Feedback Bot on 2/9/2023, 01:03 AM: 

(private comment, text removed)
#### Nigel Booth on 2/9/2023, 07:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Closed per comment on original issue that this was a version mismatch between packages.
