### ISSUE TITLE
MissingMethodException: Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.

### ISSUE THREAD

**Issue by pawansingh168** [dotnet/efcore#30313]
Hi everyone, i update the entityframework version 3.1.5 to 5.00.
And i migrate the .netcore 3.1.5 to 6.00.
But while run the application loading assembly version 7.00 of entity framework by default. Not loading the nuget package .

**Comment by roji** [comment]
@pawansingh168 you are most likely mixing different versions of Entity Framework, e.g. EF 5.0 with a provider package version 7.0.

Note also that Entity Framework 5.0 is out of support. Consider using 6.0 or 7.0 instead.
