### ISSUE TITLE
Add calculated properties unmapped to database

### ISSUE THREAD

**Issue by qduyhoang** [dotnet/efcore#30319]
Hello, I have a question on the capability to have properties on an EF model that are not mapped to any column in the corresponding database table (EF Core v3.1.18).

Particularly, I have a class Host that is scaffolded from the database table Host. Because the code is generated automatically, I don’t want to make any modification to class Host because it will be overwritten when rescaffolded, so in a partial file Host.p.cs I define a partial Host class to add a property that is calculated based on an existing database field (as seen below).

 

public partial class Host

    {

        public MaintenanceWindowCollection MaintenanceWindows

        {

            get

            {

                // null is placeholder for business logic

                return null;

            }

            set { }

        }

   }

 

However, when the OData Controller is hit, here is the error that I get back

The query specified in the URI is not valid. Unable to determine the relationship represented by navigation property 'Host.MaintenanceWindows' of type 'MaintenanceWindowCollection'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

Using [NotMapped] tag would exclude the field from being returned from the API, and there is no relationship in the database to configure, so
my question is, how do I tell EF Core to not try to map this calculated property to the database and just use the Getter I define to return the data? Is this even possible?

**Comment by ErikEJ** [comment]
Do not expose the class via the API, create another class and map to it.

**Comment by ErikEJ** [comment]
With EF Core Power Tools and T4 templates you can generate multiple sets of classes. That would solve your issues.

**Comment by qduyhoang** [comment]
Thanks for your help Erik. 2 more questions: is T4 templates available for EF Core 3? And it sounds like there is not a way to add the additional unmapped property to the model directly-at least not an easy way?

**Comment by ErikEJ** [comment]
No, T4 is not available for EF Core 3, but you could easily use them. There is a POCO template you could use just to generate the DTO classes.

BTW EF Core 3 is out of support

**Comment by ajcvickers** [comment]
@qduyhoang Properties without setters are not mapped by default.

**Comment by qduyhoang** [comment]
Thank so much for help you guys! Having no setter did the trick!
