### ISSUE TITLE
Warn on using HashSet with mutated hash code, or similar broken collections

### ISSUE THREAD

**Issue by uecasm** [dotnet/efcore#30312]
I recently ran into some weird behaviour with using EF (Core 6.0.14) with `HashSet` navigation properties (**sample code available if you want**) -- this was absolutely my fault as a side effect of breaking `HashSet`'s contract (although it was not visibly problematic until interaction with EF), but it was a very easy trap to fall into and it would be nice if EF could detect and log warnings if it encounters a collection in a broken state (similar to how it warns if you use `First` without `OrderBy`), and/or if the Right Way™ is documented.

The key aspects I'd consider to be a "broken collection state" in this context is:

* When EF scans the collection for changes before saving changes, `foreach` reports the exact same instance more than once.
* Or, after saving changes and updating the `Id` or equivalent as needed, `foreach` now reports the exact same instance more than once.

This sort of thing happens (for `HashSet<T>` in particular) when the hash implementation is incorrect and e.g. hashes the `Id` property, or hashes some other property that is mutated by application code after being added to the set; this (combined with `SaveChanges`) results in the same instance appearing in multiple hash buckets, and thus enumerated multiple times.  But it is probably an error in general for any collection type to contain duplicate-reference instances (value-equal but reference-unequal instances are usually ok, barring unique key constraints).

I regard this as an easy trap because the usual mitigation for this is to make the properties immutable (perhaps even using a `record` type), but you can't do that for EF entity types.  Perhaps worse, EF itself can hide the issue, because if you do your hash-breaking updates in one `DbContext`, the correct thing gets written to the database, and then reading back the results in a separate `DbContext` will also be correct; it's only the collections in the original context that remain messed up.

Perhaps the right answer is to avoid using sets as navigation properties, but it does seem a natural choice in some cases, and there is even an example of doing this (albeit without much commentary, and without an overridden hash code) in the EF docs.

(Though FWIW I actually really wanted a `Dictionary` as navigation property, but the general advice I found on that was to flatten it to a key-value set/collection explicitly instead.)

((It's tempting to check `T` directly for `IEquatable<T>` and/or its own hash code implementation, but that would be wrong, because the collection might be using a custom equality comparer, and that's the one that really matters.))

**Comment by uecasm** [comment]
See dotnet/EntityFramework.Docs#3397 (but having some code to detect it as well and link to the docs would be nice).

**Comment by ajcvickers** [comment]
@uecasm This is not something we can do without adding unreasonable overhead to the case where the developer is doing everything right. Where possible, we do try to surface useful error messages, but there is a limit to what we can do without negatively impacting the vastly more common, and fully functioning, case.

**Comment by uecasm** [comment]
It doesn't seem like it would be that much of an additional burden; you have to iterate the collection anyway in order to detect changes to the model.

**Comment by ajcvickers** [comment]
Keeping track of what has already been seen and checking for duplicates is too much additional burden.

**Comment by uecasm** [comment]
It could just be another `HashSet<T>` where you _know_ that you've used reference equality instead of another type, populated as you're iterating the collection anyway, then sanity checked as you're adding back to the model collection -- the error case being that your internal set says it's already there but the external collection denies this.  This doesn't seem like that much of a burden; LINQ-to-objects already uses lots of HashSet internally anyway.

----

A more performant (but less flexible) sanity check might just be to specifically check for `collection.Comparer != ReferenceEqualityComparer.Instance` for `collection is HashSet<T>` navigation properties -- as the comments on the related issues suggest, it's dangerous to allow that to use the default comparer or a custom comparer, as presumably the as-yet-unwritten documentation update would say.  This would probably flag some existing code that is currently safe thanks to not (yet) implementing `IEquatable<T>` on `T`, but it seems safer to suggest requiring reference equality explicitly anyway, so this doesn't break in the future.  There's many reasons why someone might later want to implement `IEquatable<T>`.

Or, if you need to still support earlier-than-.NET-5, perhaps just exercise the `GetHashCode` for some sample instances to verify that it returns the same thing as the standard reference equality comparer, to allow for different implementations of a reference equality comparer (since there wasn't previously a standard one).

**Comment by roji** [comment]
> It could just be another HashSet<T> where you know that you've used reference equality instead of another type, populated as you're iterating the collection anyway [...]

I agree with @ajcvickers that adding this overhead for everyone just in order to catch this error is unacceptable. This isn't likely to be a negligible perf hit, and making everyone pay it constantly just for detecting the pretty marginal error case doesn't seem like a good trade-off.

At the end of the day, it's not really possible for EF to confirm whether the equality/hash code logic that the user uses is correct or not - that really is up to the user. I understand that some bugs in this area may be manifested mostly when working with EF, but I really don't see how we can reliably detect such user bugs without adding unacceptable overhead or making an imprecise check that would have both significant false positives and negatives.
