### ISSUE TITLE
Query: converter from bool used in predicate without comparison fails on sqlite (and other non-sql server backends?)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#30326]
query:

```cs
ss.Set<JsonEntityConverters>().Where(x => x.Reference.BoolConvertedToStringYN)
```

produces

```sql
SELECT "j"."Id", "j"."Reference"
FROM "JsonEntitiesConverters" AS "j"
WHERE json_extract("j"."Reference",'$.BoolConvertedToStringYN')
```

which gives incorrect results

if we construct the predicate manually, like so:

```cs
ss.Set<JsonEntityConverters>().Where(x => x.Reference.BoolConvertedToStringYN == true)
```

we produce the correct sql and results

```sql
SELECT "j"."Id", "j"."Reference"
FROM "JsonEntitiesConverters" AS "j"
WHERE json_extract("j"."Reference",'$.BoolConvertedToStringYN') = 'Y'
```

sql server is not affected because search condition visitor always adds the comparison in the predicate, but sqlite can execute query without it. We should be adding comparisons always when predicate has bool value with a converter.

**Comment by maumar** [comment]
reopening for potential servicing. Minimal risk, causes data corruption but it was not a customer report - thoughts @ajcvickers ?

**Comment by ajcvickers** [comment]
Note from triage: bring to Tactics for patch.

**Comment by maumar** [comment]
now that I think about it, patching this doesn't make much sense - we don't support JSON on non-sql server providers, and SQL Server is already covered by search condition visitor
