### ISSUE TITLE
Why tracking queries do not update already tracked entities?

### ISSUE THREAD

**Issue by Xriuk** [dotnet/efcore#30329]
Quoting from: https://learn.microsoft.com/en-us/ef/core/querying/tracking#tracking-queries

> When the results are returned in a tracking query, EF Core will check if the entity is already in the context. If EF Core finds an existing entity, then the same instance is returned. **EF Core won't overwrite current and original values of the entity's properties in the entry with the database values.**

Is there any reason why this happens? If the entity was queried it means that it was retrieved from the database, so it might be updated as well.

This allows to refresh multiple entities (in case they are updated by another context) by just querying them again, instead of detaching them and reattaching them manually.

For example in this SO answer: https://stackoverflow.com/a/53099150/2672235
```csharp
//  1.  Load a [User] record from our database 
int chosenUserID = 12345;
User usr = dbContext.Users.FirstOrDefault(s => s.UserID == chosenUserID);

//  2. Call a web service, which updates that [User] record
HttpClient client = new HttpClient()
await client.PostAsync("http://someUrl", someContent);

//  3. Attempt to load an updated copy of the [User] record
User updatedUser = dbContext.Users.FirstOrDefault(s => s.UserID == chosenUserID);
```

At step 3 it retrieves the same user of step 1, even if it was queried again.
I would expect the same instance to be returned only if I call Find/FindAsync, if I explicitly query an entity again I would expect it to have the same values of the database and be in the Unchanged status.

**Comment by davidroth** [comment]
The current behavior is as design and also makes sense because Efs DBcontext implements UOW and Identity Tracking.
If it would always materialize a new entity from the database, the unit of work / identity tracking would be completely broken. You would now have many instances of the same entity in the current unit of work, making it impossible to track the "right" one.
Within a unit of work, an entity with a given key must only exist ones. 

If you want fresh entities either clear the context  or create a new one.

**Comment by Xriuk** [comment]
I'm not saying creating a new entity, I'm saying updating the values of already tracked entity(ies) which the change tracked can do, since it retrieved them from the database anyway again

**Comment by Xriuk** [comment]
Also the problem with EntityEntry.Reload is that you would need to reload each navigation too, which may have been updated

**Comment by ajcvickers** [comment]
@Xriuk This is tracked by #16491. Make sure to cote (👍) for that issue.

Some of the complications are:
* What to do if both the values in the tracked entity have changed and the values in the database
* What to do if entities have been deleted in the database
* What to do if foreign key values, and therefore relationships have been changed
