### ISSUE TITLE
EntityTypeBuilder<T>.HasTrigger("My Trigger")

### ISSUE THREAD

**Issue by micktion** [dotnet/efcore#30324]
Hi so we have to declare that our tables have triggers in EF 7 in order to get Inserts to work.

It seems this has to be done using the ModelBuilder as so...

```
 modelBuilder.Entity<Blog>()
        .ToTable(tb => tb.HasTrigger("SomeTrigger"));

```
I would have liked to do this inside the Configure method of my IEntityTypeConfiguration\<T\> classes however there's no HasTrigger method available on EntityTypeBuilder\<T\>. Would it be possible to add this method?

Also if a table has multiple triggers do we have to declare each of these?  If so how do you do this?

**Comment by ErikEJ** [comment]
The name does not matter, as mentioned in the  [docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#mitigations-2)

**Comment by roji** [comment]
@micktion the HasTrigger method isn't on EntityTypeBuilder, it's on the TableBuilder that's inside the ToTable method. So you can define a trigger as follows:

```c#
public void Configure(EntityTypeBuilder<Blog> builder)
{
    builder.ToTable(t => t.HasTrigger("SomeTrigger"));
}
```

Re multiple triggers... For now, HasTrigger doesn't actually create the triggers - it's simply a way to inform EF to use SQL that's compatible with triggers (i.e. avoid the more efficient OUTPUT clause). So there's no benefit in defining multiple triggers on the same table - just one should do the trick.

**Comment by micktion** [comment]
One last question.  Is there a way to turn this off the INSERT output for the whole context?  I have another project which I'll migrate to EF 7 in the near future for which nearly every table in the database has triggers.

**Comment by ErikEJ** [comment]
@micktion Did you read the docs link above?

**Comment by micktion** [comment]
Guess I hadn't...

```
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.Conventions.Add(_ => new BlankTriggerAddingConvention());
}
```
