### ISSUE TITLE
Multiple left joins results in error

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#30337]
This Linq

	var query = from p in Db.Portfolios
	join customPortfolio1 in Db.PortfolioCustoms on p.Id equals customPortfolio1.PortfolioId into customPortfolios
	from customPortfolio in customPortfolios.DefaultIfEmpty()
	join substratagy1 in Db.ListItemLookup("Portfolio Strategy") on customPortfolio.ListItem10Id equals substratagy1.ID 
	where portfolioIDs.Contains(p.Id)
	select new pGetPortfoliosResult
	{
		PortfolioID = p.Id,
		Name = p.Name,
		AbbrevName = p.AbbrevName,

	};

produces this SQL

	DECLARE @__ListCodeName_1 nvarchar(4000) = N'Portfolio Strategy';

	SELECT [p].[ID] AS [PortfolioID], [p].[Name], [p].[AbbrevName], [l].[Name] AS [SubStrategy]
	FROM [Portfolio].[Portfolio] AS [p]
	LEFT JOIN [Portfolio].[PortfolioCustom] AS [p0] ON [p].[ID] = [p0].[PortfolioID]
	INNER JOIN [Reference].[ListItemLookup](@__ListCodeName_1) AS [l] ON [p0].[ListItem10ID] = [l].[ID]
	WHERE [p].[ID] IN (1, 2, 3, 4, 5)

which works fine.  The problem is when I try to left join:

		        var query = from p in Db.Portfolios
                    join customPortfolio1 in Db.PortfolioCustoms on p.Id equals customPortfolio1.PortfolioId into customPortfolios
                    from customPortfolio in customPortfolios.DefaultIfEmpty()
                    join substratagy1 in Db.ListItemLookup("Portfolio Strategy") on customPortfolio.ListItem10Id equals substratagy1.ID into substratagies
                    from substratagy in substragies.DefaultIfEmpty()
                    where portfolioIDs.Contains(p.Id)
                    select new pGetPortfoliosResult
                    {
                        PortfolioID = p.Id,
                        Name = p.Name,
                        AbbrevName = p.AbbrevName,
                        SubStrategy = substratagy1 == null ? string.Empty : substratagy1.Name
                        
                    };

Above linq produces this error:

    System.InvalidOperationException : The LINQ expression 'DbSet<Portfolio>()
    .LeftJoin(
        inner: DbSet<PortfolioCustom>(), 
        outerKeySelector: p => p.Id, 
        innerKeySelector: customPortfolio1 => customPortfolio1.PortfolioId, 
        resultSelector: (p, customPortfolio) => new { 
            <>h__TransparentIdentifier0 = new { 
                p = p, 
                customPortfolios = customPortfolios
             }, 
            customPortfolio = customPortfolio
         })
    .GroupJoin(
        inner: ListItemLookup(__ListCodeName_1), 
        outerKeySelector: <>h__TransparentIdentifier1 => <>h__TransparentIdentifier1.customPortfolio.ListItem10Id, 
        innerKeySelector: substratagy1 => (int?)substratagy1.ID, 
        resultSelector: (<>h__TransparentIdentifier1, substratagies) => new { 
            <>h__TransparentIdentifier1 = <>h__TransparentIdentifier1, 
            substratagies = substratagies
         })' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

`Db.ListItemLookup("Portfolio Strategy")` is a table valued function and works fine on it's own:

    List<ListItemLookupResult> substragies = await Db.ListItemLookup("Portfolio Strategy").ToListAsync(); // works
	

Am I just using wrong syntax?  [This issue](https://github.com/dotnet/efcore/issues/17095) leads me to beleive I am close however that issue shows joining A to B and C  and in my case I am joining A to B and B to C.

EF version 6.0.5
dotnet 6

**Comment by maumar** [comment]
@sam-wheat can you provide full repro for this issue (or at least listings of entities and OnModelCreating) - I want to make sure i have all the navigations set up correctly, which might be lost if I attempt to reverse-engineer the model from information you provided so far.

**Comment by sam-wheat** [comment]
Thanks @maumar I got it solved.  Developer error!
