### ISSUE TITLE
EF6 : DTO with collection property generates LEFT JOIN instead INNER JOIN

### ISSUE THREAD

**Issue by padhumailin** [dotnet/efcore#30336]
Hi 

Binding data to the DTO which has collections (one-many relationship) with the LINQ, the sql query is generated with LEFT JOIN instead INNER JOIN.

DB context 

```c#
public DbSet<Standard> Standard { get; set; }
public DbSet<Student> Student { get; set; }
```

Classes  : 

```c#
Public class Standard
{
[Key]
Public string StandardID {get; set;}
Public string StandardName {get; set;}
Public string StandardDescription {get; set;}

public ICollection<Student> Students {get; set;}
}

Public class Student
{
[Key]
Public string StudentID {get; set;}
Public string StudentName {get; set;}
Public string StudentDescription {get; set;}

Public string StandardID {get; set;}
}
```

DTO Class to response from API

```c#
Public class StandardDTO
{
Public string StandardID {get; set;}
Public string StandardName {get; set;}
Public string StandardDescription {get; set;}
public ICollection<StudentDTO> Students {get; set;}
}

Public class StudentDTO
{
Public string StudentID {get; set;}
Public string StudentName {get; set;}
Public string StandardDescription {get; set;}
}
```

Web API
Standard Controller

```c#
public async Task<IActionResult> GetStandard()
{
  var data = (from s in _dbcontext.Standard

                        select new StandardDTO
                        {
                            StandardID = s.StandardID,
                            StandardName = s.StandardName,
                            StandardDescription = s.StandardDescription
                           
                              Students = s.Students.Select(m => new StudentDTO {
                                StudentID = m.StudentID,
                                StudentName = m.StudentName,
                                StudentDescription = m.StudentDescription
                            }).ToList(),
                        });

                      return Ok(data);
}
```

SQL query generated with LEFT JOIN from LINQ 

```sql
SELECT [t].[StudentId], [t].[StudentName], [t].[StudentDescription],
		   [p0].[StandardId], [p0].[StandardName], [p0].[StandardDescription]
 FROM [Student] AS [t]
**LEFT JOIN** [Standard] AS [p0] ON [t].[StandardId] = [p0].[StandardId]
ORDER BY [t].[StandardId]
```

here the join is generated as **LEFT JOIN**  instead of **INNER JOIN**.

CASE 2
when the singe DTO is populated with all Standard and Student in same dto class
and LINQ written as below:

```c#
  var data = (from s in _dbcontext.Standard
                       join m in _dbcontext.Student
                        select new StandardStandardDTO
                        {
                            StandardID = s.StandardID,
                            StandardName = s.StandardName,
                            StandardDescription = s.StandardDescription,
                             StudentID = s.StudentID,
                            StudentName = s.StudentName,
                            StudentDescription = s.StudentDescription,
                         });
```

```sql
SELECT [t].[StudentId], [t].[StudentName], [t].[StudentDescription],
		   [p0].[StandardId], [p0].[StandardName], [p0].[StandardDescription]
 FROM [Student] AS [t]
**INNER JOIN** [Standard] AS [p0] ON [t].[StandardId] = [p0].[StandardId]
ORDER BY [t].[StandardId]
```

in **case 2 INNER  JOIN is generated as expected**.

But when DTO has collection property in it, LINQ written for nested collection  then LEFT JOIN is generated in SQL query.

Anyone know how to fix it?

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
@padhumailin It likely because the foreign key `Student.StandardID` is nullable. If this isn't the case, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by padhumailin** [comment]
@ajcvickers i have created the sample code here : 
https://github.com/padhumailin/EFJoins

please have a look

**Comment by maumar** [comment]
@padhumailin this is expected behavior. In first case the query has collection navigation that gets translated by EF's navigation expansion. We always translate collections into left joins. Otherwise, if you had `Standard` entity whose `Students` collection was empty, INNER JOIN query would not return any results. (which is wrong from our perspective and not what LINQ to objects would have returned). 

In the second query you manually produce LINQ join, which we translate to inner join. If you want inner joins for in case of collections, you need to write it yourself like you did in case 2.
