### ISSUE TITLE
JSON/Sqlite: use `->` and `->>` where possible when traversing JSON, rather than `json_extract`

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#30334]
We use json_extract function to access parts of JSON, but we could/should use `->` and  `->>`

**Comment by AndriySvyryd** [comment]
Related to https://github.com/dotnet/efcore/issues/30724

**Comment by roji** [comment]
@maumar looked at this while working on #30724, so poaching... Hope that's ok.
