### ISSUE TITLE
Inefficient heap allocation in SqlServerConvertTranslator 

### ISSUE THREAD

**Issue by erdalsivri** [dotnet/efcore#30338]
We are observing thousands of unrooted `MethodInfo[]` objects in our prod heap dumps. Example output from `dotnet-dump` `dumpheap -stat -dead`:

```C#
00007f487db5bd78    73966     25371816 System.Reflection.MethodInfo[]
```

We've noticed that these arrays contain methods from the `System.Convert` class. Searching for `typeof(Convert)` in EFCore code-base has a single match: https://github.com/search?q=repo%3Adotnet%2Fefcore%20typeof(Convert)&type=code in [SqlServerConvertTranslator](https://github.com/dotnet/efcore/blob/e2c1e169cb4595d12955465f3b44f63223fb5402/src/EFCore.SqlServer/Query/Internal/SqlServerConvertTranslator.cs#L45).

At first, we ignored this because reflection result is saved in a `static readonly` field. However, after running a profiling session with Rider's memory profiler, we saw `SqlServerConvertTranslator` in many stacktraces: ![image](https://user-images.githubusercontent.com/4797942/221273348-0d23e416-595f-4b95-bd62-ee2c504a46b9.png)

The problem is that even though the result is stored/cached in a `static` field, it stores an `IEnumerable`, which is evaluated on each `SupportedMethods.Contains(method)` call in `SqlServerConvertTranslator.Translate`.

I don't know the EFCore codebase so maybe part of this behavior is WAI. Maybe this method isn't supposed to be called frequently and some non-standard thing we are doing is causing it to be called more frequently. For example, we use linqkit and have some custom expression builder code to optimize `Contains` queries etc.

However, I thought it is still worth fixing the extra allocation given that the fix is as easy as adding a `ToList`. Here is an example code I wrote to reproduce the issue:

```c#
using System.Reflection;
 
public static class Program
{
    public static void Main()
    {
        const int numIterations = 100000;
        var methodInfo = typeof(Convert).GetTypeInfo().GetDeclaredMethods(nameof(Convert.ToBoolean)).First();
 
        PrintGcInfo();
        
        for (var i = 0; i < numIterations; ++i)
        {
            if (SupportedMethodsEnumerable.Contains(methodInfo))
            {
                // Do nothing.
            }
        }
 
        PrintGcInfo();
    }
 
    private static void PrintGcInfo()
    {
        Console.WriteLine(
            "[{0:hh:mm:ss tt zz}] TotalAllocatedMb={1:0.00}, TotalPauseMs={2:0.00}",
            DateTime.UtcNow,
            GC.GetTotalAllocatedBytes(precise: true) / 1024.0 / 1024.0,
            GC.GetTotalPauseDuration().TotalMilliseconds);
    }
    
    private static readonly Dictionary<string, string> TypeMapping = new()
    {
        [nameof(Convert.ToBoolean)] = "bit",
        [nameof(Convert.ToByte)] = "tinyint",
        [nameof(Convert.ToDecimal)] = "decimal(18, 2)",
        [nameof(Convert.ToDouble)] = "float",
        [nameof(Convert.ToInt16)] = "smallint",
        [nameof(Convert.ToInt32)] = "int",
        [nameof(Convert.ToInt64)] = "bigint",
        [nameof(Convert.ToString)] = "nvarchar(max)"
    };
 
    private static readonly List<Type> SupportedTypes = new()
    {
        typeof(bool),
        typeof(byte),
        typeof(DateTime),
        typeof(decimal),
        typeof(double),
        typeof(float),
        typeof(int),
        typeof(long),
        typeof(short),
        typeof(string)
    };
 
    private static readonly IEnumerable<MethodInfo> SupportedMethodsEnumerable
        = TypeMapping.Keys
            .SelectMany(
                t => typeof(Convert).GetTypeInfo().GetDeclaredMethods(t)
                    .Where(
                        m => m.GetParameters().Length == 1
                             && SupportedTypes.Contains(m.GetParameters().First().ParameterType)));
 
    private static readonly IList<MethodInfo> SupportedMethodsList
        = TypeMapping.Keys
            .SelectMany(
                t => typeof(Convert).GetTypeInfo().GetDeclaredMethods(t)
                    .Where(
                        m => m.GetParameters().Length == 1
                             && SupportedTypes.Contains(m.GetParameters().First().ParameterType)))
            .ToList();
```

This prints the following output on my Linux machine on .Net 7:

```
[07:18:07 PM +00] TotalAllocatedMb=1.47, TotalPauseMs=0.00
[07:18:18 PM +00] TotalAllocatedMb=5271.27, TotalPauseMs=77.91
```

It allocated 5GB of data in 100K iterations. Using `SupportedMethodsList` significantly drops the duration and heap allocations:

```
[07:21:03 PM +00] TotalAllocatedMb=1.47, TotalPauseMs=0.00
[07:21:03 PM +00] TotalAllocatedMb=1.65, TotalPauseMs=0.00
```

EF Core version: 7.1.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0.3)
Operating system: Debian (mcr.microsoft.com/dotnet/runtime:7.0.3)

**Comment by roji** [comment]
Thanks, I agree that we shouldn't statically store an IEnumerable that would get evaluated again and again - submitted #30340 to fix that.

However, note that method translators such as SqlServerConvertTranslator are only invoked when compiling a query; under normal operations, a given query is only compiled once, and the results are cached and reused when the same query (i.e. same expression tree shape) is executed again. In other words, your custom expression builder code is very likely causing some query to be recompiled each time it's executed, which is quite bad for performance. This typically happens when constants are injected into the expresion tree when dynamically constructing queries - [see the docs on this](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dynamically-constructed-queries).

Regardless of this specific issue, I'd recommend looking into whether you can avoid having the query recompile on each execution; this should help both EF's runtime perf (no more recompilation each time) as well as SQL Server the plan cache (hopefully since the same SQL can be generated rather than different SQLs). I'd need to know more about what you're doing to say more.

**Comment by erdalsivri** [comment]
Thanks for the quick fix @roji! We are definitely affected by recompilation due to injecting constants into the expression tree. I will look in to the [link](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dynamically-constructed-queries) you shared.

**Comment by stevendarby** [comment]
@erdalsivri That link has good info but frames it as if the only solution for undesirable constants in a query built via the Expression API is to not use that API at all and just use regular LINQ. This isn't always possible, so I think it would be really useful to point out another solution.

A "With parameter" example retaining use of the Expression API would be:

```C#
var blogParam = Expression.Parameter(typeof(Blog), "b");
Expression<Func<string>> urlExpression = () => url; // Add this line
var whereLambda = Expression.Lambda<Func<Blog, bool>>(
    Expression.Equal(
        Expression.MakeMemberAccess(
            blogParam,
            typeof(Blog).GetMember(nameof(Blog.Url)).Single()
        ),
        urlExpression.Body // Replace Expression.Constant with this
    blogParam);
blogs = blogs.Where(whereLambda);
```

**Comment by roji** [comment]
@stevendarby you're right that this doc section is a bit light, I've submitted https://github.com/dotnet/EntityFramework.Docs/pull/4270 to improve it.

FYI I originally wrote it the way it is, since we've seen many users using the Expression API when they don't actually need to; so a big part of that is to guide them away from it for those cases. But of course in some scenarios you really do need to dynamically construct queries via the Expression API, and so I've added more information on how to do that, very similar to your code sample above.

**Comment by erdalsivri** [comment]
For context, here is a simplified version of what we are doing:

```c#
public static class IQueryableExtensions
{
  public static IQueryable<TSource> WhereIn<TSource>(
    this IQueryable<TSource> query,
    Expression<Func<TSource, int>> keySelector,
    IEnumerable<int> values) where TSource : class
  {
    // GetDbContextFromIQueryable does some ugly reflection to be able to reach the AppDbContext
    var valuesQuery = GetAppDbContextFromIQueryable(query).AsQuery(values);
    var body = Expression.Call(null, s_containsIntMethod, valuesQuery.Expression, keySelector.Body);
    return query.Where(Expression.Lambda<Func<TSource, bool>>(body, keySelector.Parameters[0]));
  }
}

public partial class AppDbContext
{
  public IQueryable<int> AsQuery(IEnumerable<int> values)
  {
    var valuesParam = BuildStringSplitParameter(SqlDbType.VarChar, values);
    return Set<StringSplitIntResult>()
      .FromSqlRaw(
        "SELECT CAST([Value] as INT) AS [Value] FROM STRING_SPLIT({0}, '|')", valuesParam)
      .Select(x => x.Value);
  }
}
```

We are basically trying to optimize `Contains` queries to avoid cache plan bloat by pushing all parameters as a varchar.

I expect these two to be equivalent:

```c#
_context.Users.Where(u => _context.AsQuery(userIds).Contains(u.Id));
_context.Users.WhereIn(u => u.Id, userIds); // Dynamic expression
```

However, the dynamic version seems to be not taking advantage of EFCore's caching for some reason and ends up allocating thousands of `PropertyInfo[]` and `MethodInfo[]` objects.

If we use `Linqkit` to construct the expression, the performance is equivalent to the first version:

```c#
public static class IQueryableExtensions
{
  public static IQueryable<TSource> WhereIn<TSource>(
    this IQueryable<TSource> query,
    Expression<Func<TSource, int>> keySelector,
    IEnumerable<int> values) where TSource : class
  {
    // GetDbContextFromIQueryable does some ugly reflection to be able to reach the AppDbContext
    var valuesQuery = GetAppDbContextFromIQueryable(query).AsQuery(values);
    return query.AsExpandable().Where(u => valuesQuery.Contains(keySelector.Invoke(u));
  }
}
```

I still don't see why our dynamic expression is not cached. @stevendarby  `AsExpandable` seems to be working fine but I will investigate the example you shared to understand how it relates to our code.

**Comment by erdalsivri** [comment]
By the way, there is a significant performance difference between these two static expressions as well:

```c#
_context.Users.Where(u => _context.AsQuery(userIds).Contains(u.Id)).Select(u => u.Id).ToQueryString();
// TotalAllocatedMbDiff=391.89, TotalGcPauseMsDiff=112.10 DurationMs=5859.4
```

```c#
_context.Users.Where(u => userIds.Contains(u.Id)).Select(u => u.Id).ToQueryString();
// TotalAllocatedMbDiff=81.47, TotalGcPauseMsDiff=54.31 DurationMs=787.4
```

I executed these 10K times to get these numbers. The dynamic version with `WhereIn` is much worse:

```c#
_context.Users.WhereIn(u => u.Id, userIds).ToQueryString();
// TotalAllocatedMbDiff=1731.69, TotalPauseMsDiff=1520.23 DurationMs=25846.3
```

**Comment by erdalsivri** [comment]
Interesting to note that this `Join` version is slightly better than the `Contains` query version but not as fast as vanilla Contains:

```c#
_context.Users.Join(s_context.AsQuery(s_userIds), u => u.Id, id => id, (u, _) => u).Select(u => u.Id).ToQueryString();
// TotalAllocatedMbDiff=308.75, TotalPauseMsDiff=57.14 DurationMs=2507.9
```

**Comment by roji** [comment]
@erdalsivri it's difficult to tell what's going on, because you're WhereIn has various non-EF things going on which aren't visible here (e.g. AsExpandable, AsQuery).

For one thing, I'd recommend looking at the actual SQL that comes out; does it embed different constant values? If so, then it must be recompiling each time. This, by the way, is the current behavior of EF for most database provider when using Contains with a collection parameter (#13617, hopefully we'll find a solution for this soon).

Otherwise, I'd try to compare the actual, final expression trees - the thing on which you invoke the final ToQueryString operation. The differences there should tell you what's going on.

**Comment by erdalsivri** [comment]
@roji I shared the implementation of `AsQuery` above. `AsExpandable` is from the [LinqKit](https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/) package.

Generated SQL definitely doesn't have embedded constant values. That's the whole reason we had created this `WhereIn` extension: https://github.com/dotnet/efcore/issues/13617. We are pushing values in a single `varchar` to avoid generating distinct queries for different values of parameters. I hope that feature request is addressed soon we can get rid of this custom code.

Here is an example SQL generated by our `WhereIn` extension:

```sql
DECLARE p0 varchar(max) = '1|4|6|8|10';

SELECT [u].[Id]
FROM [Users] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT CAST([Value] as INT) AS [Value] FROM STRING_SPLIT(@p0, '|')
    ) AS [e]
    WHERE [e].[Value] = [u].[Id])
```

I created a simple ConsoleApp to demonstrate the issue: [EFCoreWhereInBenchmark.tar.gz](https://github.com/dotnet/efcore/files/10834456/EFCoreWhereInBenchmark.tar.gz)

Here are the results:

```
/home/kaggle/RiderProjects/EFCoreWhereInBenchmark/EFCoreWhereInBenchmark/bin/Debug/net7.0/EFCoreWhereInBenchmark
Starting the benchmark...

=========================
Contains:
SELECT [u].[Id]
FROM [Users] AS [u]
WHERE [u].[Id] IN (1, 4, 6, 8, 10)

TotalAllocatedMbDiff=58.14, TotalPauseMsDiff=25.44 DurationMs=569.7
=========================


=========================
ListOfEqualityChecks:
DECLARE @__Value_0 int = 1;
DECLARE @__Value_1 int = 4;
DECLARE @__Value_2 int = 6;
DECLARE @__Value_3 int = 8;
DECLARE @__Value_4 int = 10;

SELECT [u].[Id]
FROM [Users] AS [u]
WHERE ((((CASE
    WHEN [u].[Id] = @__Value_0 THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END | CASE
    WHEN [u].[Id] = @__Value_1 THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END) | CASE
    WHEN [u].[Id] = @__Value_2 THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END) | CASE
    WHEN [u].[Id] = @__Value_3 THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END) | CASE
    WHEN [u].[Id] = @__Value_4 THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END) = CAST(1 AS bit)

TotalAllocatedMbDiff=138.43, TotalPauseMsDiff=11.48 DurationMs=809.9
=========================


=========================
StringSplit_Direct:
DECLARE p0 varchar(max) = '1|4|6|8|10';

SELECT [u].[Id]
FROM [Users] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT CAST([Value] as INT) AS [Value] FROM STRING_SPLIT(@p0, '|')
    ) AS [e]
    WHERE [e].[Value] = [u].[Id])

TotalAllocatedMbDiff=274.11, TotalPauseMsDiff=139.00 DurationMs=3430.4
=========================


=========================
StringSplit_WithAsExpandable:
DECLARE p0 varchar(max) = '1|4|6|8|10';

SELECT [u].[Id]
FROM [Users] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT CAST([Value] as INT) AS [Value] FROM STRING_SPLIT(@p0, '|')
    ) AS [e]
    WHERE [e].[Value] = [u].[Id])

TotalAllocatedMbDiff=276.27, TotalPauseMsDiff=15.63 DurationMs=1533.3
=========================


=========================
StringSplit_WithDynamicExpression:
DECLARE p0 varchar(max) = '1|4|6|8|10';

SELECT [u].[Id]
FROM [Users] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT CAST([Value] as INT) AS [Value] FROM STRING_SPLIT(@p0, '|')
    ) AS [e]
    WHERE [e].[Value] = [u].[Id])

TotalAllocatedMbDiff=1381.59, TotalPauseMsDiff=1172.41 DurationMs=17664.1
=========================
```

Even though our custom LINQ expression doesn't have any constants, EFCore seems to be still struggling with caching it IIUC because the difference between `StringSplit_WithDynamicExpression` and `StringSplit_Direct` is huge:

```
TotalAllocatedMbDiff=274.11, TotalPauseMsDiff=139.00 DurationMs=3430.4
TotalAllocatedMbDiff=1381.59, TotalPauseMsDiff=1172.41 DurationMs=17664.1
```

**Comment by roji** [comment]
FWIW I'd really advise using BenchmarkDotNet when benchmarking this kind of stuff. But in any case, I unfortunately don't have time to dive into your code just now - but a comparison of the actual expression tree between the two cases should show the difference, as I wrote above.

**Comment by erdalsivri** [comment]
Of course I don't expect you to dive into our code and fix our problem. I prepared simplified version because you said "it is difficult to tell what's going on". I thought maybe you'd like to investigate if there is a problem on your side. We've fixed the problem on our side with `LinqKit` already.

By the way, expression trees and the generated SQL are exactly the same in each iteration because we don't do anything conditional or include any constants in the expression. We just use `FromSqlRaw` with a `SqlParameter`.

**Comment by roji** [comment]
I'm definitely interested in understanding the cause for this; especially if there's some sort of EF problem here (e.g. if FromSqlRaw somehow causes re-compilation). Let me know what you find, or if you get stuck and need help.

**Comment by stevendarby** [comment]
> @stevendarby you're right that this doc section is a bit light, I've submitted https://github.com/dotnet/EntityFramework.Docs/pull/4270 to improve it.
> 
> 
> 
> FYI I originally wrote it the way it is, since we've seen many users using the Expression API when they don't actually need to; so a big part of that is to guide them away from it for those cases. But of course in some scenarios you really do need to dynamically construct queries via the Expression API, and so I've added more information on how to do that, very similar to your code sample above.

Thanks @roji, those changes look great. And yeah, I get that about wanting to guide people away from building queries that way- I actually found it a little painful to write the 'better' Expression API version because of how avoidable the whole thing is in that example 😆 Hopefully the parmaterization trick helps some people though!
