### ISSUE TITLE
Database don't create at first execution of app!!

### ISSUE THREAD

**Issue by mikeandersun** [dotnet/efcore#3033]
Database don't create at first execution of app. Is there any breaking changes?
How I can config DbContext to create database on Sql Server?
 the error is : 
   Login failed for user 'x'
Thanks

**Comment by ErikEJ** [comment]
Did you ask EF to create the database? (There is no "magic" any more) - http://ef.readthedocs.org/en/latest/getting-started/full-dotnet.html#create-your-database

**Comment by mikeandersun** [comment]
Is there any automatic database creation ? at least for development environment.
With build before 15564 the database was created automatically.

**Comment by ErikEJ** [comment]
You can use 

    Database.EnsureDeleted();
    Database.EnsureCreated();

**Comment by mikeandersun** [comment]
This way just create database with no any table.
I need a way to create database from model.

**Comment by ErikEJ** [comment]
Have you tried it? https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/BasicEndToEndScenarioForIdentity.cs ?

**Comment by mikeandersun** [comment]
The error was I override OnConfiguring on my dbcontext and forgot to call 
` base.OnConfiguring(optionsBuilder);`

**Comment by divega** [comment]
@mikeandersun If you inherit directly from DbContext then `base.OnConfiguring(...)` does absolutely nothing. On the other hand in EF7 we have moved away from automatically creating databases on first run. That is intentional. While automatic creatiation is nice for fast prototyping and demos, it makes things more complicated down the road.

**Comment by mikeandersun** [comment]
In my opinion automatic database creation is very nice for developing phase of a project. 
If this done by automatic migrations creation/apply by the tooling(VS.NET) of from code it is better.

**Comment by ErikEJ** [comment]
If (IsRunningFromVisualStudio())
    {
        Database.EnsureDeleted();
        Database.EnsureCreated();
    }

**Comment by divega** [comment]
@mikeandersun in EF7 is an imperative/opt-in model vs. the declarative/opt-out model EF6 had in database initializers. E.g. you can use the `EnsureCreated()` API @ErikEJ mentioned or the Migrations APIs if you really want to create or update the database programmatically and you somehow know you won't ever have more than one thread or user trying to do it concurrently. But outside of prototyping, testing or simple an ephimeral applications that will ever only have one user, you will be better off managing the lifetime of the database out-of-band from the application.
