### ISSUE TITLE
migrations bundles.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#30348]
Are the migrations bundles a solution for creating migrations transactional? 

Without transactions the migrations might get applied only partially where in case of an timeout or other error the migration might abort halfway.

**Comment by ajcvickers** [comment]
@qsdfplkj Each migration is applied in its own transaction.

**Comment by qsdfplkj** [comment]
My question is related to #22616, #22613 and #7681

**Comment by ajcvickers** [comment]
@qsdfplkj What, specifically, is your question?

**Comment by qsdfplkj** [comment]
Normally when I update a database and a migration has e.g. a timeout this can cause the the migration to be partially applied. (Let's say an index is not added.) but the migration is added to the migration table as being applied. Some could argue to rerun it and maybe the index is added but let's assume that won't work. Preferably the whole migration should be applied or not transactionally. Which I assumed isn't  possible. But reading about the bundles I got the impression it does something clever and might have a solution for this.

**Comment by ajcvickers** [comment]
@qsdfplkj Each migration in the bundle is applied in its own transaction.

**Comment by qsdfplkj** [comment]
Ok, so I guess it doesn't solve it because it is already solved as it (now/already) is using transactions. I will do some more tests...
