### ISSUE TITLE
"Login failed for user '<token-identified principal>" when creating database in migration (at runtime) 

### ISSUE THREAD

**Issue by sturlath** [dotnet/efcore#30363]
We are having connection issues while running migrations that **creates** a database at runtime (I know I know.. this is temporary thing).

> login failed for user < token-identified principal >

_Note applying migrations **works** if the database **exists**!_

We have this code below that is supposed to create the database (if not existing and then apply migrations) but we get a exception that seems to lock up the db so that we can´t do anything. 

```csharp
    public virtual async Task MigrateAsync()
    {
        await Database.MigrateAsync();
    }
```

This is a example of our connection string

`Server=tcp:mydbserver.database.windows.net;Authentication=Active Directory Managed Identity;User Id=a62a62d7-d9fa-48a8-b3cd-e5c8d5ea59b5;Database=mydb;`

Are we missing something?

Version info:
.net 6.0
EF Core 6.0.6

p.s
We updated to user/pass to be able to test our scenarios and that works fine.

**Comment by ErikEJ** [comment]
@sturlath I highly recommend that you create the Azure SQL Database outside of running migrations, assume it is a rights issue. Will give you full control of DB SKU and all settings

**Comment by sturlath** [comment]
We are creating the db with an event and using `MigrateAsync()` for our multitenant setup (hundreds of tenants) so we want to create the databases at runtime (not running the migrations (we will remove that soon)). 

Do you mean @ErikEJ that we should create the db first then e.g. fire an event that we catch and runs the migrations there (or some other disconnected way)?

How would we create the db without migrations in code?

Something like this?
`context.Database.EnsureCreated();`

Or would you recommend doing it with raw sql?

```sql
string sqlCommand = $@" IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'{database}')
                              BEGIN
                                  CREATE DATABASE [{database}] (  ) );
                              END;";

using (var connection = new SqlConnection(maserConnectionString))
{
    connection.Open();

    using (var command = new SqlCommand(sqlCommand, connection))
    {
        command.ExecuteNonQuery();

    }
}
```

**Comment by ErikEJ** [comment]
I have thought more  about this, I think your are facing the issue that completion of  a "CREATE DATABASE" command does not guarantee that the database is online and ready to accept connections.

**Comment by sturlath** [comment]
So what would be the best approach? Using some EF methods or just creating the DB with the raw SQL above that connects/disconnect and then apply the migration with `MigrateAsync()`? 

**How does this here look?** It creates the db if not created and then tries to create to connect to the db with few retries.

```csharp
public async Task<bool> CreateDbAndRunMigration(string database)
{
   await CreateDbAsync(database);
   return await TryRunningMigrationAsync();
}

private async Task CreateDbAsync(string database)
{
    string sqlCommand = $@" IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'{database}')
                              BEGIN
                                  CREATE DATABASE [{database}] (  ) );
                              END;";

    using (var connection = new SqlConnection(maserConnectionString))
    {
        await connection.OpenAsync();

        using (var command = new SqlCommand(sqlCommand, connection))
        {
            await command.ExecuteNonQueryAsync();
        }
    }
}


public virtual async Task<bool> TryRunningMigrationAsync()
{
    var retryPolicy = Policy
        .Handle<Exception>()
        .WaitAndRetryAsync(5, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)));

    try
    {
        await retryPolicy.ExecuteAsync(async () =>
        {
            await Database.MigrateAsync();
        });

        return true;
    }
    catch (Exception)
    {
        return false;
    }
}

```

 Or is there some other **pattern** we should follow?

**Comment by roji** [comment]
@sturlath I'm a bit confused...

> We have this code below that is supposed to create the database (if not existing and then apply migrations) but we get a exception that seems to lock up the db so that we can´t do anything.

Can you please provide more details on this, what exact exception are you seeing? I'm not sure why creating the database via SQL would avoid the same exception/lock-up - after all MigrateAsync just does CREATE DATABASE at the end of the day etc.

If there's something special that MigrateAsync does which causes the lockup, we should probably look into it; that would be better than trying to work around it by creating the database via raw SQL etc.

**Comment by sturlath** [comment]
The code we have isn´t doing anything special. We get an azure servicebus event to our AppService and just run `MigrateAsync()` and get this error `Login failed for user <token-identified principal>`  but if we raw-create the first db and then apply the migrations it works.

We tried to do some fancy things like try/catch the exception and then create the db and then apply the migration but that seemed to lock all access to the db. But raw-creating the db and then applying the migrations worked.

Here is the error (I don´t think we got anything more detailed on it)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2386572/222396110-49454b86-94d2-4914-9124-a69202658d85.png)

The extra logging is from us.

**Comment by sturlath** [comment]
Just to note we are having this issue with `Active Directory Managed Identity` while the code works with `user/pass`

**Comment by ajcvickers** [comment]
@sturlath As @ErikEJ said above, the completion of the command to create the database does not mean that the database is available to connect to. The less time there is between the command to create the database and the first access to it, the more likely it is to fail. In general, it's not a good idea to create a database from code, both because, as far as I know, there is no way to know how long it will take for the database to be available or even reliably check whether or not it is available, and also because the default settings for new database can change without notice such that you may find yourself automatically creating very expensive databases without realizing it. This has happened in the past.

**Comment by sturlath** [comment]
@ajcvickers  I totally agree running migrations on run time is something we shouldn´t be doing (migration could fail etc) but we have multitenant scenarios where we have a UI where its possible to create a "site" for a tenant (tenant can have many sites) and we have many tenants. A site == new db so really many db´s

So manually creating (and managing) these db´s is not practical so we really like to create them "on the fly" in code. Or is there some other way we are missing?

We could of course make sure that no migration is ever run right after creating a db. It would be a separate step where we make sure the db has been created before allowing the migrations to be applied.

**Comment by ajcvickers** [comment]
@sturlath In my experience, this approach doesn't really work well with Azure, but you could try contacting Azure support about it and see what they say. If there is some pattern for doing this that they recommend and is reliable, then we could look into adding support for that in .NET.

**Comment by sturlath** [comment]
FYI I posted the question [here](https://learn.microsoft.com/en-us/answers/questions/1185847/issue-creating-a-database-at-run-(with-ef)-time-wi). I´ll update this question if I get some relevant feedback.

Thank you so much for your (like always) swift responses. That is what I love about this community!

**Comment by ErikEJ** [comment]
@sturlath when using username/password - I assume that is the user name for an admin on the logical Server?

**Comment by sturlath** [comment]
Your are correct @ErikEJ
