### ISSUE TITLE
SaveChanges sometimes fails to save added entity in multithread context - is this known/expected?

### ISSUE THREAD

**Issue by Ubereil** [dotnet/efcore#30375]
We have an diagnostics application that other applications call to register themselves with. When they do the diagnostics application creates a session entity, adds it to a DbSet and then call SaveChanges(). Sometimes, when we restart all applications (which triggers that they all re-registers with the diagnostics application) we've found that not all applications manages to register successfully.

In our attempts to investigate this we found that when this happens the session entity quite simply isn't saved when we call SaveChanges. As in, if we look at the database file with a browser the entity isn't there and if we try to find the entity in the DbSet it isn't there either, even when we're querying the same DbContext. When we investigated the entity we've seen that the entity status was Added prior to SaveChanges and Unchanged after - same as when the entity was successfully saved to the database. And, strangest of all, SaveChanges() does not throw any exception even though it fails to save to the database.

Now, we've found that the problem disappeared when we added "Cache=Shared" to the connection string. But what I would like to know is if multi-threaded addition of entities is supposed to be supported with private caches for connections? And if it isn't supported, shouldn't SaveChanges at least throw an exception if an added entity disappears?

**Comment by ErikEJ** [comment]
Which provider do you use?

**Comment by Ubereil** [comment]
> Which provider do you use?

Oh, I'm sorry, I forgot to mention that. We're using SqLite, writing to a file.

> DbContext is not thread safe, and neither is DbConnection.

Yeah, that's true. I learnt that the hard way a few years ago. Also, we recently turned on logging (*coughs nervously*) which made us realize that we'd forgotten to set the DbContext lifetime to transient. The thing is though, the result when we didn't use a transient DbContext was exceptions galore.

The connections is perhaps another matter - I wouldn't bet my house on my understanding of how connections work in EF Core. But the call to register with the service is a regular Rest endpoint in a controller, which passes the call on to a dependency injected DbRepository. The repo is marked as transient and it is, in turn, dependent on the transient DbContext. My understanding is that this will result in one new DbContext per call and that each DbContext will have a separate connection (with the connections coming from a connection pool, if I'm not mistaken). It seems to work once we updated the connection string with "Cache=Shared".

Another thing worth mentioning is that we did a quick experiment where we moved to SqlServer Express. And this worked too. So I'm pretty confident there's nothing wrong with the actual code.

**Comment by ajcvickers** [comment]
@Ubereil I'm having trouble understanding what you are asking for here. Can you be more specific about what your question or issue is?

**Comment by Ubereil** [comment]
Ok. I'll try to boil it down.

We're using EF Core with an SqLite database. We have a rest controller with a post method where we create entities in a (transient) DbContext. Since it's a rest controller it's quite possible that we get parallel attempts to create entities. We recently realized that these entities occasionally disappears after we call SaveChanges (with no exception thrown). When we added "Cache=Shared" to the SqLite connection string the problem went away.

Why is that?

Also, the fact that no exception is thrown when the entity isn't saved seems like a bug to me. But maybe I'm missing something.

**Comment by ajcvickers** [comment]
@Ubereil Reading about what "Cache-Shared" does, it seems like this may well have the behavior you are seeing. But all this is at the SQLite level, rather than at the EF or even the .NET level.

**Comment by ajcvickers** [comment]
@Ubereil I discussed with the team, and using "Cache-Shared" is definitely the way to go with this. Without it, we would expect to see errors, such as timeouts, coming from the SQLite code. These should be surfaced, so if they are not, then that's either because they are not happening at the SQLite layer (which should be reported as a SQLite bug) or we are missing them, which would be a Microsoft.Data.Sqlite bug. We can investigate this if you can provide a runnable repro where this happens, otherwise there is not much we can do.

**Comment by Ubereil** [comment]
@ajcvickers  Thanks for the feedback.

Unfortunately I can't give you our production service becuase that's production code. And I'm afraid I won't be able to find the time to write a new runnable repro based on that solution either. 

So, in the end, I guess you won't be able to do that much. At least you're aware of the problem. And at least I know that we've solved it properly.
