### ISSUE TITLE
EF fetching entity from tracked region

### ISSUE THREAD

**Issue by syedqutub** [dotnet/efcore#30382]
Let say you have a Blog enitity with some records in a SQL db. 
1. using ef db context fetch the one Blog record from the database
2. hold the debugger after fetch
3. change the Title property of the Blog entity directly from the databse (not using the ef db context).
4. continue the debugger and the fetch the same record using it's id.

the record u will get will be from the DbContext tracked region not UPDATED record (title was unchanged) from the Db.
i was using FirstOrDefaultAsync() for this problem

is this an issue or this is expected?

**Comment by ajcvickers** [comment]
This is expected behavior. See https://learn.microsoft.com/en-us/ef/core/querying/tracking#tracking-queries
