### ISSUE TITLE
Commit "Query: Implements support for collection nav. prop translation" breaks SQL CE

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3038]
The change in #2959 causes the SQL Server Compact provider to fail, as it does not support the kind of nested SELECTs in use, meaning that Collection nav prop translation for SQLCE is not available:

```
SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
FROM [Customers] AS [c]
ORDER BY (
   SELECT COUNT(*)
   FROM [Orders] AS [o]
   WHERE [c].[CustomerID] = [o].[CustomerID]
)
```

In other places SQL CE nav prop queries break because a pattern similar to the one reported in #2626  is used:

```
SELECT (
  SELECT CASE
    WHEN
        (EXISTS (
            SELECT 1
            FROM [Orders] AS [o]
            WHERE [c].[CustomerID] = [o].[CustomerID])
        )
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
)
FROM [Customers] AS [c]  
```

**Comment by ErikEJ** [comment]
The following tests fail:
        public override void Collection_orderby_nav_prop_count()
        public override void Collection_select_nav_prop_all()
        public override void Collection_select_nav_prop_any()
        public override void Collection_select_nav_prop_count()
        public override void Collection_select_nav_prop_long_count()
        public override void Collection_select_nav_prop_sum()
        public override void Collection_where_nav_prop_all()
        public override void Collection_where_nav_prop_any()
        public override void Collection_where_nav_prop_any_predicate()
        public override void Collection_where_nav_prop_count()
        public override void Collection_where_nav_prop_count_reverse()
        public override void Collection_where_nav_prop_sum()
        public override async Task Collection_where_nav_prop_sum_async()

**Comment by rowanmiller** [comment]
@anpete any thoughts on a way we could unblock CE without fundamentally changing things? It seems like the SQL we generate is optimal for other providers.

**Comment by ErikEJ** [comment]
@rowanmiller @anpete Any suggestions or anything I can do?

**Comment by rowanmiller** [comment]
@ErikEJ just a general note on this (and a couple of other issues where we need to make things more flexible to support CE). Given how much is on our plate to get RC done, we aren't going to be able to dedicate a lot of time to sorting this out for RC. We will spend the time to unblock things before RTM. Our perspective is that the limitations should be ok for the CE provider for RC - as they don't seem to be super common cases (not that they aren't important, just that we need to prioritize things). That said, if you want to look at working around them, then we'd be happy to take contributions on them.

@anpete if you are able to give a hint at where Erik could get started with this, that would be great.

**Comment by rowanmiller** [comment]
We think we have the correct defaults in the relational components. Given the limitations of CE you could look at overriding parts of the query stack to not use nested queries. A starting point might be to try triggering client eval for these parts of the query. Feel free to reach out with specific issues if you try it.

**Comment by ErikEJ** [comment]
@rowanmiller How do I "trigger client eval" ?

**Comment by rowanmiller** [comment]
cc @anpete is looking up the entry point for you

**Comment by anpete** [comment]
@ErikEJ There is no single place and you will likely have to dig a little to find the best way to do it in your provider. Broadly speaking, the SqlTranslatingExpressionVisitor is the class responsible for doing most of the translation work. The way it works is that it visits the incoming LINQ expression fragment (E.g. The predicate expression of a Where operation) and attempts to produce a corresponding SQL expression tree fragment. If it decides that it can't translate the input expression, let's say because the input expression contains a call to a method that we don't know about, then the visitor returns null for the translation. When this happens, the higher level calling code will trigger client eval for the predicate by folding the original input expression into the generated compiled query.
