### ISSUE TITLE
Sql syntax error if use Default Values

### ISSUE THREAD

**Issue by isbdnt** [dotnet/efcore#30405]
### Include stack traces

![image](https://user-images.githubusercontent.com/26591233/222959083-bc62193f-0474-4807-b819-606d348fed6f.png)

### Include verbose output

![image](https://user-images.githubusercontent.com/26591233/222959059-d130a981-026f-482e-b535-1683d17eb5dd.png)

### Include provider and version information

EF Core version: 7.0.0
Database provider: MySql.EntityFrameworkCore 7.0.0
Target framework: NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4
Mysql version: mysql-8.0.32-winx64

**Comment by isbdnt** [comment]
To reproduce it, create a new entity, leave everything as default, add it to the DbContext, and save changes.
![image](https://user-images.githubusercontent.com/26591233/223065667-8fb73c3a-70f2-4455-9e10-ae5158a75f08.png)

**Comment by ajcvickers** [comment]
@isbdnt This looks like an issue with the MySQL provider and therefore should be reported to Oracle. You might also consider trying to Pomelo community driven provider for MySQL: https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/

**Comment by isbdnt** [comment]
https://bugs.mysql.com/bug.php?id=101294
