### ISSUE TITLE
Using transaction with EF core 6 with SQL Server Temporal tables leads to generation of rows with identical values for Start/End datetimes on period columns that cannot be retrieved with temporal query

### ISSUE THREAD

**Issue by OculiViridi** [dotnet/efcore#30416]
I'm using a **EF Core 6 DbContext transaction** to create/update entities on a **SQL Server temporal table**.

The data I'm processing (array of items) has a key (Year-Sequential, like: `2023-001`, `2023-002`, etc.) and then a set of attributes that corresponds to other columns on the underlying table.
One of this attributes identifies the kind of operation: `Create`, `Update`, `Cancel`.

It may happen that I receive a request with many different operations related to a single Year-Sequential key, such as:

    2023-001 - Create (<data>)
    2023-001 - Update (<data>)
    2023-001 - Cancel (<data>)
    2023-002 - Create (<data>)
    2023-002 - Update (<data>)
    2023-002 - Cancel (<data>)
    etc.

Since I'm using a temporal table to store this data to be able to track changes on the rows over time, I've coded the processing method like a single DB transaction with inside a recursive method that process subsets of the items. The recursive method works this way:

 1. It takes the first occurrence of each Year-Sequential key, process it and add it to the `DbContext` using the `dbContext.MyEntities.Add()` method.
 2. If the same Year-Sequential key is found again for another kind of operation, it puts it aside on a new list for the next round of processing.
 3. When all the "not duplicated key" items have been processed, there's a call to `dbContext.SaveChangesAsync()`.
 4. The processed entities are created and receives the `EntityId` value assigned by the database (that I need to use for the next steps of processing).
 5. If the list of "duplicated key items" is not empty, the method recursively calls itself on the duplicates list and starts again from step 1. Instead, if the duplicated key items list is empty, the method ends and then there's a call to `transaction.CommitAsync()`, to commit the transaction and save everything to the database.

For each round of the recursive method I correctly get a row created on each single Year-Sequential key. So, taking previous data example, on the History table I've 2 old rows about `2023-001` (1 for the Create and 1 for the first Update) with the same `EntityId` and, on the Current table, I've the third (for second Update) row, so the one related to the last `2023-001 Cancel` operation.

Everything works, but there's a **problem with Start/End datetime columns** used for temporal table period.

#### See the queries screenshot below.

The problem is that if **I make a temporal query on that data** (`[MovimentiDati]` table), using the `FOR SYSTE_TIME ALL` clause, **I get back only the current row! No way I can get the old rows too, but they exists!** So, the history is all there but I can't get it!

Instead, if I query the History table (`[MovimentiDatiHistory]`) I correctly see the old rows all referring to the same `EntityId`.

On the screenshot, you can see 5 rows with the same issue.
For example, take the row with `MovimentoId = 399`, you can see:
 - on `MovimentiDatiHistory` table: Creation of the row (first run of recursive method and first call to `dbcontext.SaveChangesAsync()`)
 - on `MovimentiDatiHistory` table: First update on the row (second run of recursive method and second call to `dbcontext.SaveChangesAsync()`)
 - on `MovimentiDati` (current) table: Second (and last) update on the row (third run of recursive method and third call to `dbcontext.SaveChangesAsync()`)

But, as highlighted in red, you can also see that **Start/End date timestamps are identical!** And I think this is the reason why I cannot get the correct result when I query the data from `[MovimentiDati]` (the table with current data) with the temporal clause.

![image](https://user-images.githubusercontent.com/42179710/223174506-489e2450-e7fd-440f-9f6d-1fe93eb0f644.png)

### Expected result

I am not able to say whether it is EF Core library's or SQL Server's responsibility, but:

- the Start/End datetime values should be different from each other on a single row (at least for 0.0000001 seconds)
- the Start datetime value should be related at the time the call is made to the `dbContext.SaveChanges()` method.

If this is not possible, then there should be at least a way to **avoid the creation of identical Start/End timestamps** because this makes impossible to make temporal queries and to obtain the correct data.

### Provider and version information

EF Core version: 6.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Database: SQL Server 2019 v15.0.4298.1
Target framework: .NET 6.0
Operating system: Windows 11 build 22621.1265
IDE: Visual Studio 2022 17.5.1

**Comment by maumar** [comment]
looks like by design behavior from sql server perspective. Consider temporal tables documentation: https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16#how-do-i-query-temporal-data, specifically:

```
FOR SYSTEM_TIME filters out rows that have a period of validity with zero duration (ValidFrom = ValidTo).

Those rows will be generated if you perform multiple updates on the same primary key within the same transaction. In that case, temporal querying returns only row versions before the transactions, and current rows after the transactions.

If you need to include those rows in the analysis, query the history table directly.
```

EF naively/transparently translates the update statements. Perhaps we could improve this by making it easier to query the HistoryTable directly (suggested solution/workaround for the problem). Or detect the case where multiple updates to the same row are made in the same transaction and issue a warning? - but that seems like too much work for what it's worth.

**Comment by OculiViridi** [comment]
@maumar Thanks for the reference to the documentation! I did some searching, but couldn't find anything...
Good to know that at least this is a known behavior anyway.

> `FOR SYSTEM_TIME filters out rows that have a period of validity with zero duration (ValidFrom = ValidTo).
`

I'm wondering why a period with zero duration is admitted if this leads to a different behavior when making temporal queries... What is it useful for?

> Or detect the case where multiple updates to the same row are made in the same transaction and issue a warning? - but that seems like too much work for what it's worth.

I don't know how much effort this would take, but at least when enabling logs of EF, users can be aware of such behavior. This would be not so bad, to me.

If there's no way to change how SQL Server behave, maybe an help on EF side when querying such data, would be appreciated too! 😁 
Right now, if I wanted to directly query the History table I should create the corresponding entity by my self (I'm using EF Core Power Tools for reverse engineer the DB), create a separated query and then merge the results with the actual "standard" temporal query. It wouldn't be so straightforward...

**Comment by gparissis** [comment]
I am not sure why the issue is out of scope. I do understand what the documentation says, but this doesn't apply to what is described. 

The developer has a list of records that is grouping based on the unique record Id in case he has more records pointing to the same Id and then is calling SaveChangesAsync. 
A transaction will be created and committed when the initial set is processed.

Then the user will group again and get the next set of the unique record Ids and call again SaveChangesAsync. This is a second transaction that is created. It is not the same uncommitted transaction from the first SaveChangesAsync call.

So, I don't understand why is this not an EF Core issue. Can someone please advice?

**Comment by ajcvickers** [comment]
> Then the user will group again and get the next set of the unique record Ids and call again SaveChangesAsync. This is a second transaction that is created. It is not the same uncommitted transaction from the first SaveChangesAsync call.

As I read the description, it says that all the SaveChanges calls are made in a single transaction. Where are you seeing otherwise?

**Comment by gparissis** [comment]
> > Then the user will group again and get the next set of the unique record Ids and call again SaveChangesAsync. This is a second transaction that is created. It is not the same uncommitted transaction from the first SaveChangesAsync call.
> 
> As I read the description, it says that all the SaveChanges calls are made in a single transaction. Where are you seeing otherwise?

I am very sorry, I missed this sentence when I was reading the description.

**Comment by akwasi-cot** [comment]
Are you using Multiple Active Results? This can play with the underlying transactions that are being saved. What would happen is that conenction timestamp would be the same resulting in the underlying entities having the same timestamp...

Using a `await Database.Database.CloseConnectionAsync()` creates a clear boundary which helps!
