### ISSUE TITLE
[NotMapped] and Fluent API .Ignore() does not work when using EF Core alongside MVVM

### ISSUE THREAD

**Issue by DJRM2021** [dotnet/efcore#30423]
When using EF Core 8.0.0-preview.1.23111.4 and CommunityToolkit.Mvvm 8.1.0 in the same C# project (WASDK 1.2/ WinUI 3), the [NotMapped] annotation and even the modelBuilder.Entity.Ignore does not work as intended.

Using Data Annotations:
```
internal partial class Person : ObservableObject
{
    [Key]
    [ObservableProperty]
    int id;

    [ObservableProperty]
    string name;

    [ObservableProperty]
    [NotMapped]
    ImageSource profilePicture;
}
```
```
internal class PersonDbContext : DbContext
{
    public DbSet<Person> Person { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=MyServer;Database=Person;TrustServerCertificate=True;Integrated Security=True");
        optionsBuilder.EnableSensitiveDataLogging();
    }
}
```
```
PM> Add-Migration Person -Context PersonDbContext
```
![image](https://user-images.githubusercontent.com/77593544/223335104-e30752c0-1ef5-446b-aca5-fb35e5acdbfb.png)

Using Fluent API:
```
internal partial class Person : ObservableObject
{
   [Key]
   [ObservableProperty]
   int id;

   [ObservableProperty]
   string name;

   [ObservableProperty]
   ImageSource profilePicture;
}
```
```
internal class PersonDbContext : DbContext
{
    public DbSet<Person> Person { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=MyServer;Database=Person;TrustServerCertificate=True;Integrated Security=True");
        optionsBuilder.EnableSensitiveDataLogging();
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().Ignore(p => p.ProfilePicture);
    }
}
```

Both ```[NotMapped]``` and Fluent API's ```modelBuilder.Entity<Person>().Ignore(p => p.ProfilePicture);``` will result in the same error message.

### Include provider and version information

EF Core version:  8.0.0-preview.1.23111.4
Database provider: SQLServer
Target framework: .NET 7.0
Operating system: Windows 11 22H2
IDE: VS 2022 17.5.1

**Comment by roji** [comment]
@DJRM2021 double-check that you're not referencing ImageSource from some other entity where it isn't ignored. If that's not the case, please submit a minimal, runnable code sample that shows the error.

**Comment by DJRM2021** [comment]
I fixed the issue by removing Mvvm's ```[ObservableProperty]``` attribute on ImageSource profilePicture class member and converted it into a property: ```[NotMapped] public ImageSource ProfilePictureSource { get; set; }```

It turns out, MVVM and EF Core can have misalignments with models because MVVM needs a partial class to generate codes.
In my example, the Person class is partial, which means there is another definition of the same class generated by MVVM source gen, and in that auto-generated read-only file, the ProfilePicture property loses the [NotMapped] attribute which in turn makes the Add-Migration command to fail.
