### ISSUE TITLE
In efcore 6, Is it possible to generate migration file  with table already exists or not  condition.( when we run commands) 

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [dotnet/efcore#30428]
I want to get generated code automatically that table exists or not asper our requirements. 
Please let me know is it possible by customizing code to generate file.

**Comment by roji** [comment]
In general, the concept of migrations is that EF checks which migrations have already been applied in your database (these are recorded in the special `__EFMigrationsHistory` table), and only applied the needed migrations. Assuming your database is in sync with your migrations, that check should be the only one needed: there's no need to check if a table exists, instead we check whether the migration that creates that table has already been applied.

If your table may or may not have been created externally (outside of EF's migrations mechanism), and you wish an EF migration to **conditionally** create it - only if it's not already there - then you'll have to [drop down to raw SQL](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql) and do this yourself.
