### ISSUE TITLE
Limits mapping to JSON columns - EF Core 7, SQL Server

### ISSUE THREAD

**Issue by christiannagel** [dotnet/efcore#30434]
Trying to do some ToJson mappings, it seems I'm hitting some limitations with TpH and TpC. 

With an abstract base class and derived generic types, such as

```C#
public abstract record class MoveData(Guid GameId, Guid MoveId, int MoveNumber);

public record class MoveData<TField>(Guid GameId, Guid MoveId, int MoveNumber)
    : MoveData(GameId, MoveId, MoveNumber)
{
    public required ICollection<TField> Fields { get; init; }
}
```

and using these types for `TField`:

```C#
public record ColorField(string Color);

public record ShapeAndColorField(string Shape, string Color);
```

And using TpH, mapping the fields with OwnsMany / ToJson, I had the error it's not possible to map different derived types to the same column. Is this because of OwnsMany restrictions? I was successful mapping to different columns.

The complete sample project with similar functionality with a conversion to a simple string instead of conversion to JSON:
https://github.com/ProfessionalCSharp/ProfessionalCSharp2021/tree/main/5_More/EFCore/InhertianceMappingWithConversion

Using TpC instead, I reached an `InvalidOperationException` with `RelationalStrings.JsonEntityWithNonTphInheritanceOnOwner`.

ToJson is not supported with TpT and TpC?

## Provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11 22H2 22621.1344
IDE: Visual Studio 2022 17.6.0 Preview 1

**Comment by ajcvickers** [comment]
TPT/TPC mapping is tracked by #28443

Looks like the other issue is likely this: #28688

**Comment by christiannagel** [comment]
Thanks, @ajcvickers 

Yes for the TPT/TPC mapping.

It doesn't look like the other issue is a match. In my scenario I don't have primitive types directly in the collection - and it works if I create separate columns for every derived class. With a converter, I can map properties of derived types to the same column. However, when using ToJson (which requires OwnsMany) this is not possible.

**Comment by ajcvickers** [comment]
@christiannagel While https://github.com/dotnet/efcore/issues/28688 says primitive types, this applies to any non-entity types. Non-entity types will always have limitations if they are stored as values of types not recognized by the database, since database querying into JSON is generally limited to types the database knows about. On the other hand, just storing non-entity types should be fine once #28688, assuming the type converts appropriately to JSON.

**Comment by ajcvickers** [comment]
Thanks for providing more details. That is indeed a different issue, tracked by #28592.

**Comment by christiannagel** [comment]
Thank you - I really missed finding this issue.

Both TPT/TPC with JSON columns and sharing the same JSON column are "consider-for-current-release". Thanks!

https://github.com/dotnet/efcore/issues?q=is%3Aopen+is%3Aissue+label%3Aconsider-for-current-release+label%3Aarea-json
