### ISSUE TITLE
Retrive shadow properties with Notrack

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#30438]
Hello, summarizing, I have this semplified model :

```
    public class Nation
    {
        public Guid NationID { get; set; }
        public string NationName { get; set; }
        public virtual ICollection<City> Cities { get; set; }
    }

    public class City
    {
        public Guid CityID { get; set; }
        public virtual Nation Nation { get; set; }
        public string CityName { get; set; }
    }

```

Configured like this :

```
	modelBuilder.Entity<Nation>().HasKey(itm => itm.NationID);

	modelBuilder.Entity<City>().HasKey(itm => itm.CityID);
	modelBuilder.Entity<City>().HasOne(itm => itm.Nation).WithMany(itm => itm.Cities).IsRequired();

```

In a web api controller, I have some queries on City that return DTO and must be as fast as possible, so I am traing to perform the queries without tracking.
The problem is that City has the shadow property NationID that i have to return also.

So if one query is 

`db.Set<City>().ToArray() 
`
I simply add a projection 

`db.Set<City>().Select(itm => new { itm.CityID, itm.CityName, NationID = EF.Property<Guid>(itm, "NationID") }).AsNoTracking().ToArray()
`
the query with the projection produce the same sql query without the projection, but if the query is different the produced sql may change significantly.

for example, this query:

`db.Set<Nation>().Select(itm=>itm.Cities.First()).ToArray();`

produce the sql query :

```
SELECT [t0].[CityID], [t0].[CityName], [t0].[NationID]
FROM [Nation] AS [n]
LEFT JOIN (
    SELECT [t].[CityID], [t].[CityName], [t].[NationID]
    FROM (
        SELECT [c].[CityID], [c].[CityName], [c].[NationID], ROW_NUMBER() OVER(PARTITION BY [c].[NationID] ORDER BY [c].[CityID]) AS [row]
        FROM [City] AS [c]
    ) AS [t]
    WHERE [t].[row] <= 1
) AS [t0] ON [n].[NationID] = [t0].[NationID]

```

adding the projection

`db.Set<Nation>().Select(itm=>itm.Cities.First()).Select(itm => new { itm.CityID, itm.CityName, NationID = EF.Property<Guid>(itm, "NationID") }).AsNoTracking().ToArray();`

produce this sql query 

```
SELECT (
    SELECT TOP(1) [c].[CityID]
    FROM [City] AS [c]
    WHERE [n].[NationID] = [c].[NationID]) AS [CityID], (
    SELECT TOP(1) [c0].[CityName]
    FROM [City] AS [c0]
    WHERE [n].[NationID] = [c0].[NationID]) AS [CityName], (
    SELECT TOP(1) [c1].[NationID]
    FROM [City] AS [c1]
    WHERE [n].[NationID] = [c1].[NationID]) AS [NationID]
FROM [Nation] AS [n]

```
that seems not only very different, but also very inefficient compared to the origianl, also the estimate execution plan, show an access to index on `City.NationId` field for each field i add to the query, so more field on City entity more access to the same index

So my question is, is there a way to retrive the Shadow properties in a not tracked query?

Many thanks
[ShadowProperties.zip](https://github.com/dotnet/efcore/files/10921166/ShadowProperties.zip)

**Comment by ajcvickers** [comment]
@GLuca74 As a general rule, I would say that if you need the value in a no-tracking query, then it's not a great candidate to map as a shadow property. That being said, improving the query here is covered by the [pending selectors](https://github.com/dotnet/efcore/issues/30221) work.

**Comment by GLuca74** [comment]
@ajcvickers yes, of course I totally agree with you but I often work with third part queries and models, and sometimes I can not change both, thanks for point me on pending selectors work, i will follow the related threads

Have a greath day
