### ISSUE TITLE
ReadOnly DbContext for multithreading (only read operations)

### ISSUE THREAD

**Issue by cephaluspiraeus** [dotnet/efcore#30436]
I know that DbContext is not thread safe. 
I wonder is it possible to make DbContext thread safe only for read operations? 
Except change tracker what causes DbContext not to be thread safe? 
Would be great if there is some ReadOnlyDbContext which will be used for only read operations.
Can you explain why ReadOnlyDbContext is not possible?

**Comment by ajcvickers** [comment]
@cephaluspiraeus 

> I wonder is it possible to make DbContext thread safe only for read operations?

No; we discussed this in the past, and it's not practical.

> Except change tracker what causes DbContext not to be thread safe?

Internal state.

> Would be great if there is some ReadOnlyDbContext which will be used for only read operations.
> Can you explain why ReadOnlyDbContext is not possible?

As with most feature requestion that don't get implemented, it's not that its not possible, its that the value and complexity is not worth the benefit. [Context pooling](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling) is a very efficient way of re-using context instances such that there is very little overhead for high-performance read scenarios.

**Comment by roji** [comment]
It's also worth mentioning that DbContext needs to send actual database queries for your read-only operations; but database connections (which are generally TCP connections) themselves aren't thread-safe. A context could *theoretically* open multiple database connections, but that would mean potential loss of transaction consistency. And at that point it really begs the question of why you're not simply using two DbContext instances with context pooling, as @ajcvickers wrote above.

**Comment by wertzui** [comment]
I've created [EntityFrameworkCore.Parallel](https://github.com/wertzui/EntityFrameworkCore.Parallel) ([NuGet](https://www.nuget.org/packages/EntityFrameworkCore.Parallel)) for that exact purpose.
it uses `IDbContextFactory<T>` to create a new `DbContext` instance for every query and dispose it afterwards.
Since every query is running on its own context, you can await multiple queries at the same time.
```
var task1 = myDbContextFactory.Parallel().Set<MyTable1>().Where(t => t.Id < 10).ToListAsync(cancellationToken);
var task2 = myDbContextFactory.Parallel().Set<MyTable2>().Where(t => t.Id >= 10).ToListAsync(cancellationToken);

await Task.WhenAll(task1, task2);

var result1 = task1.Result;
var result2 = task2.Result;
```
