### ISSUE TITLE
The scaffolding not work properly

### ISSUE THREAD

**Issue by pampua84** [dotnet/efcore#30435]
Hi all, 
I have installed the latest version of EF Core 7.0.3 and its updated tool. 
I'm trying to scaffold Asp.Net Core Identity tables as per image:

![image](https://user-images.githubusercontent.com/17255890/223684713-b13d132a-1e26-4715-83ca-d3c4ea006a1a.png)

When I scaffold the above tables, the UserRoles entity is not reported and in the generated code I see this:

```
   entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserRole",
                    r => r.HasOne<Role>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<User>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("UserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_UserRoles_RoleId");
                    });
```
and not this like with EF Core 6:
```
  entity.HasMany(e => e.UserRoles)
            .WithOne(role => role.User)
            .HasForeignKey(ur => ur.UserId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);
```
the entity object is of type User in the code.

Why is this happening?

**Comment by ajcvickers** [comment]
@pampua84 See https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many

**Comment by pampua84** [comment]
Thanks a lot for the answer.
