### ISSUE TITLE
"dnx ef migrations add [name]" generates subsequent migrations into the wrong folder

### ISSUE THREAD

**Issue by axefrog** [dotnet/efcore#3044]
In Power Shell, I am currently in the following folder:
D:\Dropbox\Work\Clients\MyClient\Dev\Website

This folder contains many files, including: Startup.cs, project.json and a Migrations folder that was generated using the yeoman aspnet generator. The accompanying .sln file is in the parent Dev folder.

I now enter the following:
`dnx ef migrations add Alpha`

While the model snapshot is written to the correct location, the migration is erroneously deposited here:
D:\Dropbox\Work\Clients\MyClient\Dev\Website\MyClient\Dev\Website\Migrations

I'm assuming this is a bug.

**Update**
Doesn't seem to happen if the migrations folder doesn't already exist.

**Comment by ErikEJ** [comment]
Which exact EF 7 version?

**Comment by axefrog** [comment]
7.0.0-beta7

**Comment by bricelam** [comment]
This may be related to #3050. To the commands, *Website* is the default namespace, so by convention things in the `MyClient.Dev.Website` namespace should be written to `MyClient\Dev\Website`. It's interesting that the snapshot is correct.

Is the namespace of the migration and snapshot correct?

**Comment by bricelam** [comment]
@axefrog I'm not able to reproduce this issue locally. Could you share more of your solution?

**Comment by axefrog** [comment]
Yeah I have also been unable to reproduce it on subsequent attempts, so I don't know if it's resolved or perhaps was subject to a very specific, hard-to-reproduce set of conditions. I guess you can close it for now. If I see it happen again, I'll come back to you.

**Comment by bricelam** [comment]
Sounds good. Thanks for following up.
