### ISSUE TITLE
Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 was not found. An approximate best match of Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1 was resolved.

### ISSUE THREAD

**Issue by mayadav1** [dotnet/efcore#30444]
Following command gets failed with  below error  message while running "database.single_query."

Command:
dotnet publish Benchmarks.csproj -c Release -o C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-6280\zgtfkv0n.df2\benchmarks\src\Benchmarks\published /p:MicrosoftNETCoreAppPackageVersion=6.0.14 /p:MicrosoftAspNetCoreAppPackageVersion=6.0.14 /p:GenerateErrorForMissingTargetingPacks=false /p:RestoreNoCache=true /p:MicrosoftWindowsDesktopAppPackageVersion=6.0.14 /p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App --framework net6.0 --self-contained -r win-x64
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-6280\zgtfkv0n.df2\benchmarks\src\Benchmarks\Benchmarks.csproj : warning NU1603: Benchmarks depends on Npgsql.EntityFrameworkCore.PostgreSQL (>= 6.0.8) but Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 was not found. An approximate best match of Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1 was resolved.
  Restored C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-6280\zgtfkv0n.df2\benchmarks\src\Benchmarks\Benchmarks.csproj (in 1.81 sec).
C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-6280\zgtfkv0n.df2\benchmarks\src\Benchmarks\Benchmarks.csproj : warning NU1603: Benchmarks depends on Npgsql.EntityFrameworkCore.PostgreSQL (>= 6.0.8) but Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 was not found. An approximate best match of Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1 was resolved.
CSC : error CS1705: Assembly 'Npgsql.EntityFrameworkCore.PostgreSQL' with identity 'Npgsql.EntityFrameworkCore.PostgreSQL, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' uses 'Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' which has a higher version than referenced assembly 'Npgsql' with identity 'Npgsql, Version=6.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' [C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-6280\zgtfkv0n.df2\benchmarks\src\Benchmarks\Benchmarks.csproj]
Exit code: 1

Target framework: NET 6.0
Target SDK : 6.0.406
Target .NET Runtime : 6.0.14
Target ASP.NET Core Runtime : 6.0.14
VS Version : 22

**Comment by mayadav1** [comment]
@roji, I used  crank command to execute same benchmarks and path of .csproj is not  available.

**Comment by roji** [comment]
@mayadav1 you should be able to obtain the csproj; in any case, there's nothing I can do without seeing it - you most likely have some sort of mismatch there.

**Comment by roji** [comment]
I'm assuming this is a copy of the ASP.NET benchmark repo (i.e. [this file](https://github.com/aspnet/Benchmarks/blob/main/src/Benchmarks/Benchmarks.csproj)). I don't know exactly what you're attempting, but I advise writing your own project with a csproj that matches what you're actually trying to measure; this ASP.NET benchmarks csproj is meant for the specific needs of the ASP.NET performance lab.

In any case... As you can see, Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 [is definitely available on nuget.org](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/6.0.8), so I'm assuming you're not using nuget.org in your nuget feeds; that would be the case if you just cloned the ASP.NET benchmarks repo (they use private, internal feeds only). Edit your nuget.config to make sure nuget.org is there.
