### ISSUE TITLE
Make DbContext accessible from DbSet

### ISSUE THREAD

**Issue by ygoe** [dotnet/efcore#3045]
The `DbSet` class has a reference to the `DbContext` that it belongs to. But it is private and cannot be used from the outside (without hacking which can reduce stability). When writing extension methods for `DbSet`, it would be really useful to have access to the `DbContext` as well to perform additional actions.

Today I have to write my extension methods for the `DbContext` class and use it like this:

```
context.MyExtension<EntityType>();
```

And then it can access `context.Set<EntityType>()...`. It would be much nicer if I could write extension methods directly for `DbSet` that would be used like this:

```
context.MyEntities.MyExtension();
```

For this, there must be a public getter or method to retrieve the internal `DbContext` field. Hiding it behind an explicit interface implementation is fine, too. Would that work?

**Comment by ajcvickers** [comment]
@dg9ngf You can use the GetService extension method from the Microsoft.Data.Entity.Infrastructure namespace:
```C#
var myContext = mySet.GetService<DbContext>();
```

**Comment by etrafiee** [comment]
What if we have more than one DbContext in services?
