### ISSUE TITLE
Verify No Changes Command

### ISSUE THREAD

**Issue by justindbaur** [dotnet/efcore#30457]
**Problem:**
I need to be able to create a CI job that can verify that there have been no changes to our database schema without a migration being added for it. So that I can create a PR gate. 

**Solution:**
I would love a command in the `dotnet ef` CLI to verify no migrations are needed, something like.

`dotnet ef migrations verify-no-changes`

This would respond with exit code 0 if no migrations are needed and exit code 1 if migrations are needed. 

I believe it would essentially just need to gather up operations like here:
https://github.com/dotnet/efcore/blob/702f1ceb935c0d74af95d08263c4c3a735ebfa9d/src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs#L145-L146

Then it would just check that both lists are empty. I would be more than willing to work on this if the idea is approved.

**Alternate Solution:**
Add an additional options to `dotnet ef migrations add` for `--ensure-empty` so that it will fail when there are operations that are needed and will return with a non-zero exit code.

**Comment by ajcvickers** [comment]
Duplicate of #26348. Please make sure to vote (👍) for that issue.

**Comment by justindbaur** [comment]
@ajcvickers Thank you! I tried to find one but my google-fu isn't good enough I guess.
