### ISSUE TITLE
EF Core 8 + MVVM - ObservableCollection<string> gives errors in TPC

### ISSUE THREAD

**Issue by DJRM2021** [dotnet/efcore#30459]
I am using EF Core 8 Preview 1.2 and CommunityToolkit.Mvvm 8.1.0 in a WASDK 1.2/WinUI 3 C# desktop app project.

Here are my models:
```
public abstract partial class Person : ObservableObject
{
    [ObservableProperty][Key] int personId;
    [ObservableProperty] string name;
}
public partial class Employee : Person
{
    [ObservableProperty] string employeeId;
    [ObservableProperty] string department;
}
public partial class Teacher : Employee
{
    [ObservableProperty] string teacherId;
    [ObservableProperty] ObservableCollection<string> competencies;
}
```
Here is my DbContext:
```
public class PersonDbContext : DbContext
{
    public DbSet<Person> Person { get; set; }
    public DbSet<Employee> Employee { get; set; }
    public DbSet<Teacher> Teacher { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().UseTpcMappingStrategy();
    }
}
```
Here is the error when running **Add-Migration** in the PM console:

PM> Add-Migration D Build started... Build succeeded.

Unable to create a 'DbContext' of type ''. **The exception 'The entity type 'ObservableCollection' requires a primary key to be defined.** If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

Error is not supposed to occur because Teacher inherits from Employee which inherits from Person. Person base class has the [Key] annotation which tells EF core which primary key to use. Am I missing something here? The project compiles without any errors. It's the migration that fails.

I am using Visual Studio Community Edition 17.5.1

The following NuGet packages are installed:
Microsoft.EntityFrameworkCore.SqlServer 8.0.0-preview.1.23111.4
Microsoft.EntityFrameworkCore.Tools 8.0.0-preview.1.23111.4
Microsoft.EntityFrameworkCore.Design 8.0.0-preview.1.23111.4
CommunityToolkit.Mvvm 8.1.0

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by DJRM2021** [comment]
Repro Steps:
1. Create a C# project in VS 2022, using this template:
![image](https://user-images.githubusercontent.com/77593544/224582794-0a0f98f0-5993-4af9-99cf-feb5d7f3edf4.png)
2. Install the following NuGet packages
    Microsoft.EntityFrameworkCore.SqlServer 8.0.0-preview.1.23111.4
    Microsoft.EntityFrameworkCore.Tools 8.0.0-preview.1.23111.4
    Microsoft.EntityFrameworkCore.Design 8.0.0-preview.1.23111.4
    CommunityToolkit.Mvvm 8.1.0
3. Update the following NuGet packages
    Microsoft.Windows.SDK.BuildTools
    Microsoft.Windows.AppSDK
4. Add a file and name it "Person.cs" in the project.
![image](https://user-images.githubusercontent.com/77593544/224583032-5c6e8e57-a209-4e10-ae4c-80b9f899bb09.png)
5. Inside the "Person.cs" file, define 3 classes, Person (abstract), Employee (inherit Person) and Teacher (inherit Employee)
```
using CommunityToolkit.Mvvm.ComponentModel;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;

namespace App2
{
    public abstract partial class Person : ObservableObject
    {
        [ObservableProperty][Key] int personId;
        [ObservableProperty] string name;
    }
    public partial class Employee : Person
    {
        [ObservableProperty] string employeeId;
        [ObservableProperty] string department;
    }
    public partial class Teacher : Employee
    {
        [ObservableProperty] string teacherId;
        [ObservableProperty] ObservableCollection<string> competencies;
    }
}
```
6. Build the project. There should be no compiler errors/warnings.
7. Open the Package Manager Console window and enter Add-Migration myMigration, the error should appear.
![image](https://user-images.githubusercontent.com/77593544/224583268-ea1cdd95-eb8c-4654-a864-a8e6303d620e.png)

**Comment by DJRM2021** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I've added the repro steps in the comments, thank you.

**Comment by ajcvickers** [comment]
@DJRM2021 Collections of primitive types are not yet supported by convention--see #25163 and #29427. You can use a value converter for this, as documented here:

For example: https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#examples

```C#
modelBuilder.Entity<Teacher>().Property(e => e.Competencies).HasConversion(
    v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
    v => JsonSerializer.Deserialize<ObservableCollection<string>>(v, (JsonSerializerOptions)null),
    new ValueComparer<ObservableCollection<string>>(
        (c1, c2) => c1.SequenceEqual(c2),
        c => c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),
        c => new ObservableCollection<string>(c)));
```

**Comment by DJRM2021** [comment]
@ajcvickers Thanks for the prompt reply and assistance. I'm hoping support for collections of objects will be added in EF Core 8.
