### ISSUE TITLE
Scaffolding doesn't know how to handle SQL Server xml data type

### ISSUE THREAD

**Issue by abelepereira** [dotnet/efcore#3046]
On beta7, when scaffolding a database containing tables with xml data columns:

```
dnx ef dbcontext scaffold "Server=myserver;Database=mydatabase;user id=me;password=pwd" EntityFramework.SqlServer
```

Produces the warning/error:

```
For column [dbo][Table][Column]. Could not find type mapping for SQL Server type xml. Skipping column.
```

**Comment by rowanmiller** [comment]
XML is not yet supported, we did however open https://github.com/aspnet/EntityFramework/issues/3076 to see if we can just scaffold a string property in reverse engineer to unblock the scenario.
