### ISSUE TITLE
Add NuGet Package README file for EFcore

### ISSUE THREAD

**Issue by lyndaidaii** [dotnet/efcore#30467]
Issue: 
Currently, there is no README file for EF Core package. for example: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.0-preview.1.23111.4

Action: 
Add NuGet README file so that it will be easier for users to get started with know about the EF core packages.

**Comment by ajcvickers** [comment]
Duplicate of #26556

**Comment by lyndaidaii** [comment]
> Duplicate of #26556

Thanks, I opened PR for README packages. Please feel free to take a look and leave comments or feedback. Thanks!
