### ISSUE TITLE
efcore7 mysql8 jsonColumn null error

### ISSUE THREAD

**Issue by tianmafly** [dotnet/efcore#30472]
It is a simple demo. Does  efcore7 not support mysql8?
the code is:
![image](https://user-images.githubusercontent.com/38370307/224878773-9a4cc039-17cf-47d9-adea-415ceeef6a97.png)
![image](https://user-images.githubusercontent.com/38370307/224878857-7da2c86d-de2d-408a-906b-287c0a564bee.png)
the version is:
![image](https://user-images.githubusercontent.com/38370307/224878965-cfdbfc9e-3f8c-4525-bcfd-755ef889bacd.png)
the mysql8 table:
![image](https://user-images.githubusercontent.com/38370307/224880004-15ce4e18-4e4a-4b1a-86c6-89f86408daf1.png)

the error is:
![image](https://user-images.githubusercontent.com/38370307/224879250-11407cad-0925-4fec-a5a3-ff3001affdc1.png)

**Comment by maumar** [comment]
JSON support is only added for SQL Server and (in the upcoming preview) Sqlite. MySql provider (Pomelo) needs to make some changes in order to light up the functionality on it's end. From EF side, we could only throw a better error as NRE is not helpful at all.
