### ISSUE TITLE
Performance update

### ISSUE THREAD

**Issue by verdysh** [dotnet/efcore#30473]
Microsoft.EntityFrameworkCore.SqlServer, Version="6.0.5"
ASP .NET Core 6

I need to update a row. I have an `Id` of the row which comes somewhere outside and some properties. I'm sure the row exists in database. I want to perform simple UPDATE query: `UPDATE Folders SET Name=@c1 WHERE Id = @Id`

Standard approach to do this is to get the entity from `DbSet`, change the properties and call `SaveChanges` on `DbContext` instance. Using this approach it gets the entity with all its properties from DB and then it sends UPDATE query with all the properties back to the database.

Recently I discovered that you can perform accurate UPDATE:

```
var documentsFolder = new Folder
{
    Id = documentsFolderId,
    Name = "Documents 3"
};

db.Folders.Attach(documentsFolder);
var entry = db.Entry(documentsFolder);

entry.Property(e => e.Name).IsModified = true;

db.SaveChanges();
```

In this case you perform exactly this query: `UPDATE Folders SET Name=@c1 WHERE Id = @Id`

I'm asking because I've not seen such approach anywhere in real applications. I have been thinking that the only option you have is to get full entity, change the properties and update full entity.

Is it "legal" to use such simple UPDATE?

**Comment by roji** [comment]
@verdysh that's all covered in our [change tracking docs](https://learn.microsoft.com/en-us/ef/core/change-tracking/); yeah, it is indeed fine to do so, and is faster than loading the entity from the database when you don't need to do that.

However, note that the above can be done even more efficiently (and simply) using the new EF Core 7.0 ExecuteUpdate API ([see docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates)):

```c#
db.Folders
    .Where(f => f.Id == documentsFolderId)
    .ExecuteUpdate(s => s.SetProperty(f => f.Name, "Documents 3"));
```

**Comment by verdysh** [comment]
Thank you!
