### ISSUE TITLE
Navigation Property with backing fields can't work in Lazy Load mode

### ISSUE THREAD

**Issue by occulter** [dotnet/efcore#30498]
## I get blank returns when I tried to access backing fields from collections.

Before this, I define the BCollections to  public virtual  List<B> BCollections, it works properly.

### My code like this

```C#
public class A
{
      public virtual IEnumerable<B> BCollections => _bCollections;
      
      protected (or private) virutal  List<B> _bCollections =new();
}

pubic class B
{
}

public class MyDbContext : DbContext
{
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .UseLazyLoadingProxies()
        .UseSqlServer(myConnectionString);
}
```

### Include provider and version information

EF Core version: 7.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: 7.0
Operating system:
IDE: (e.g. Visual Studio 2022 17.5)

**Comment by ajcvickers** [comment]
@occulter Lazy-loading proxies work because they can override the property implementation and add additional loading behavioer. Fields cannot be overridden, so this mechanism cannot work for fields.

**Comment by occulter** [comment]
> @occulter Lazy-loading proxies work because they can override the property implementation and add additional loading behavioer. Fields cannot be overridden, so this mechanism cannot work for fields.

thanks , but how to fix my code so let it works. please help

**Comment by occulter** [comment]
> @occulter Lazy-loading proxies work because they can override the property implementation and add additional loading behavioer. Fields cannot be overridden, so this mechanism cannot work for fields.

Thanks again.

What I wanna do is to avoid from out of class add or remove entity to this collections. (but can be operated inside class)

**Comment by ajcvickers** [comment]
@occulter If you want to lazy-load via a proxy, then you will have to call the property to load the collection before attempting to access the backing field. You could also use [lazy-loading without proxies](https://learn.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies).

**Comment by occulter** [comment]
> @occulter If you want to lazy-load via a proxy, then you will have to call the property to load the collection before attempting to access the backing field. You could also use [lazy-loading without proxies](https://learn.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies).

Actually in my domain entity model, I don't want to inject ILazyLoader , what I wanna do is just to let a Navigation Object in Collections can exposed for readonly from outside view, and the backing field can be lazy load (if eager or include will load many data into memory that's very chaos..

Any suggestion? or update in next version?  thanks

**Comment by ajcvickers** [comment]
@occulter That's not possible.
