### ISSUE TITLE
android.runtime.JavaProxyThrowable: System.InvalidOperationException: You specified a password in the connection string, but the native SQLite library you're using doesn't support encryption.                    at Microsoft.Data.Sqlite.SqliteConnection.Open ()

### ISSUE THREAD

**Issue by dgandhi1-godaddy** [dotnet/efcore#30492]
Have been trying to add encryption to my Xamarin native project using efcore + sqlcipher. but it keep crashing saying...
Reproducible steps would be to create traditional Xamarin app and add below packages.

```
android.runtime.JavaProxyThrowable: System.InvalidOperationException: You specified a password in the connection string, but the native SQLite library you're using doesn't support encryption.
                   at Microsoft.Data.Sqlite.SqliteConnection.Open ()
```

Packages in shared project
```
<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="3.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.3" />

```
Packages in Xamarin.Native project

   ```
 <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.3" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.3" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.0.3" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.android" Version="2.0.3" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3.android" Version="1.1.14" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="3.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.6" />
```
and other related efcore packages.

### Include version information

Microsoft.Data.Sqlite version:
Target framework: (e.g. .netstandard2.0 & Xamarin.Native old way [ no .net 6+])
Operating system: MacOS

**Comment by ajcvickers** [comment]
@dgandhi1-godaddy EF Core 3.1 is [out-of-support](https://learn.microsoft.com/en-us/ef/core/what-is-new/). Please update to EF Core 6 or 7. Also, "SQLitePCLRaw.bundle_e_sqlcipher" is [unofficial and unsupported](https://github.com/ericsink/SQLitePCL.raw#included-providers). Official builds are available from [Zetetic](https://www.zetetic.net/) code, which is a commercial product, but is supported by them.

**Comment by dgandhi1-godaddy** [comment]
@ajcvickers Since Xamarin.Android project are using .net 4.7.x. And recent EFCore will have conflict with other xamarin.android packages.

**Comment by ajcvickers** [comment]
I don't think there is a currently supported solution for that combination.
