### ISSUE TITLE
Cannot find module './en.js' ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find module './en.js'

### ISSUE THREAD

**Issue by pawansingh168** [dotnet/efcore#30499]
When we update the angular with aspnet zero  verison to 13 .

**Comment by roji** [comment]
@pawansingh168 this doesn't seem to be related to EF Core in any way, but rather an Angular/Javascript issue. If you believe this is related to EF, please paste a runnable, minimal code sample showing what's going on.
