### ISSUE TITLE
Migrations fails since EF Core 7.0.4

### ISSUE THREAD

**Issue by jochenjonc** [dotnet/efcore#30503]
Hi,

Yesterday I did a minor dotnet upgrade from 7.0.3 to 7.0.4 and suddenly I couldn't run/create any migrations. Because of the following error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The comparer for type 'double?' cannot be used for 'Customer.Latitude' because its type is 'decimal'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateTypeMappings(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Oracle.EntityFrameworkCore.Infrastructure.Internal.OracleModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   ...
```

The EntityTypeConfiguration is the following:

```C#
builder.Property<double?>(e => e.Latitude)
       .HasColumnName("POS_Y")
       .HasColumnType("NUMBER(8,5)")
       .HasPrecision(8, 5);
```

The property is of type double? and the column is a NUMBER.

I think the problem is caused by the following change in EF Core https://github.com/dotnet/efcore/commit/f4e549ead524b1fcb3514ad49ce85fbef328b564 which is a fix for https://github.com/dotnet/efcore/issues/29985.

Somehow EF Core returns another ClrType or ProviderClrType that makes the OracleModelValidator.Validate fail.

I was able to fix this by adding a HasConversion<decimal?>.

```C#
builder.Property<double?>(e => e.Latitude)
       .HasConversion<decimal?>()
       .HasColumnName("POS_Y") 
       .HasColumnType("NUMBER(8,5)") 
       .HasPrecision(8, 5);
```

I only need to add this HasConversion<decimal?> on fields where NUMBER is used in the database and int, long, double, … is used in code. I'm not a 100% sure, but I think it is also only Nullable types that are impacted.

Can you verify if the workaround is valid and won't cause any additional problems? 
I created this post because maybe other database providers can have similar issues.

FYI, I cross-posted this on https://forums.oracle.com/ords/apexds/post/migrations-fails-since-ef-core-7-0-4-6440.

Regards,

Jochen

### Provider and version information

EF Core version: 7.0.4
Database provider: Oracle.EntityFrameworkCore
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.5

**Comment by ajcvickers** [comment]
@jochenjonc Please post your .csprog file.

**Comment by ajcvickers** [comment]
@jochenjonc I am not able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by 0xced** [comment]
I forked your project at https://github.com/0xced/efcore-migration-issue and simplified the code to a very minimal reproduction. It's not really a migration issue but a model validation issue.

Run the `efcore-7.0.3` project ⇒ ✔️ everything is fine.
Run the `efcore-7.0.4` project ⇒ ❌ fails with this exception:

```
Unhandled exception. System.InvalidOperationException: The comparer for type 'double?' cannot be used for 'Issue.Weight' because its type is 'decimal'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateTypeMappings(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Oracle.EntityFrameworkCore.Infrastructure.Internal.OracleModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   …
```

Full source code here (also available in my fork):
```csharp
using Microsoft.EntityFrameworkCore;

var options = new DbContextOptionsBuilder<IssueDbContext>()
    .UseOracle("Data Source=MyOracleDB;Integrated Security=yes;")
    .ConfigureWarnings(builder => builder.Default(WarningBehavior.Throw))
    .Options;

var context = new IssueDbContext(options);
_ = context.Model; // Throws InvalidOperationException here, only with EF Core 7.0.4 (works fine with 7.0.3)

public record Issue(int Id, string? Name, double? Weight);

public class IssueDbContext : DbContext
{
    public IssueDbContext(DbContextOptions<IssueDbContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var builder = modelBuilder.Entity<Issue>();
        builder.ToTable("ISSUE");
        builder.HasKey(i => i.Id);
        builder.Property(i => i.Id).HasColumnName("ISSUE_ID");
        builder.Property(i => i.Name).HasColumnName("NAME");
        builder.Property(i => i.Weight).HasColumnName("WEIGHT").HasColumnType("NUMBER(8,5)");
    }
}
```

Note: remove `.HasColumnType("NUMBER(8,5)")` and the exception vanishes!

**Comment by ajcvickers** [comment]
This is a bug in the Oracle provider, which is using a `decimal` type mapping for a `double` property:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1430078/228808750-8aa3bf86-0740-4c47-bbdc-f6292b4ac4be.png">

The issue should be reported to Oracle.

As a workaround, the change made in #29985 can be reverted by setting the `AppContext` switch "Microsoft.EntityFrameworkCore.Issue29985". For example, call this at application start:

```C#
AppContext.SetSwitch("Microsoft.EntityFrameworkCore.Issue29985", true);
```

**Comment by jochenjonc** [comment]
Thx, I already reported it on the Oracle forum.

My solution was to add `.HasConversion<decimal?>()` to force it to decimal. Is that any valid option or will it cause other problems?

**Comment by ajcvickers** [comment]
@jochenjonc That should be fine.

**Comment by jochenjonc** [comment]
@ajcvickers thx, I'll close the issue.

**Comment by indrajitjadeja** [comment]
> This is a bug in the Oracle provider, which is using a `decimal` type mapping for a `double` property:
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/1430078/228808750-8aa3bf86-0740-4c47-bbdc-f6292b4ac4be.png">
> 
> The issue should be reported to Oracle.
> 
> As a workaround, the change made in #29985 can be reverted by setting the `AppContext` switch "Microsoft.EntityFrameworkCore.Issue29985". For example, call this at application start:
> 
> ```cs
> AppContext.SetSwitch("Microsoft.EntityFrameworkCore.Issue29985", true);
> ```

I have taken the same project as a reference shared by @jochenjonc to check the behavior with SQL Server migration.

The model is having Weight property with "double?" type and when I include .HasColumnType("DECIMAL") on same property in OnModelCreating method as below,
`  
public class Issue
{
    public Issue(int id)
    {
        Id = id;
    }
    public int Id { get; }
    public string? Name { get; set; }
    public double Weight { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    var issueBuilder = modelBuilder.Entity<Issue>();

    issueBuilder.ToTable("ISSUE");

    issueBuilder.HasKey(i => i.Id);

    issueBuilder.Property(i => i.Id)
        .HasColumnName("ISSUE_ID");

    issueBuilder.Property(i => i.Name)
        .HasColumnName("NAME");

    issueBuilder.Property(i => i.Weight)
        .HasColumnName("WEIGHT")
        .HasPrecision(8, 5)
        .HasColumnType("DECIMAL");
  }`

After migration completes it maps to "decimal" data type instead of "double" as shown in below Up method

`
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ISSUE",
                columns: table => new
                {
                    ISSUEID = table.Column<int>(name: "ISSUE_ID", type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NAME = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WEIGHT = table.Column<decimal>(type: "DECIMAL(8,5)", precision: 8, scale: 5, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ISSUE", x => x.ISSUEID);
                });
        }
`
sql server migration is converting double to decimal and not throwing such error:
> System.InvalidOperationException: The comparer for type 'double?' cannot be used for 'Issue.Weight' because its type is 'decimal'.

Is this the expected behavior? 
or 
sql server efcore has some TypeMapping issue?
