### ISSUE TITLE
Couple of JSON support ideas

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#30519]
I'm working through my project and I wanted to make sure that two concepts are tracked somewhere as JSON support is worked on:

 - `@>` operator support -- I would love to be able to provide a C# object that could be used to perform a structural + subset match against an object in a JSON column.
 - Many-to-many using a JSON array column.  Basically, store the foreign keys as a JSON array, rather than using a join table.

**Comment by ajcvickers** [comment]
@atrauzzi I filed #30551 for the second bullet. Please provide a lot more details on what you mean in first bullet.

**Comment by atrauzzi** [comment]
I have the following query which I currently have to do raw:

```csharp
    public static async Task<Stuff?> FindStuffsByType(this MyContext db, Configuration configuration)
    {
        var something = await db.Stuffs.FromSqlRaw(@"
            select *
            from stuff
            where 
                and {1}::jsonb @> configuration 
        ", JsonSerializer.Serialize(configuration))
        .FirstOrDefaultAsync();

        // ...
    }
```

Basically I'm taking a C# type, bonking it on the head into JSON and then passing it to the query to be used as a way to do a structural comparison on a JSON column using the `@>` operator.

If the value provided contains the values in the DB, it matches.

**Comment by atrauzzi** [comment]
Ah yes, for some reason I never remember that `EF.*` set of utilities is where a lot of non-LINQy goodies can be found.  As always, thanks @roji. :slightly_smiling_face:
