### ISSUE TITLE
Allow Client Side to define relationships not in DB side

### ISSUE THREAD

**Issue by AcousticGuitar** [dotnet/efcore#3051]
About a year ago I was on a project whereby the developers of the application had no clue concerning DB fundamentals.  In fact not a single foreign key was defined anywhere.  They wanted the application side migrated to an MVC application but did not want the DB to be altered.   The solution to me was that "I should map the tables as they were using DB first, but then I would go further and add the relationships client side only."   I was unable to do that.

_Please consider allowing the client side to define foreign key relationships that are not in the database._

**Comment by anpete** [comment]
@AcousticGuitar Neither EF6 or EF7 require FKs to be defined in the database. The only time we ever introspect into the DB is when reverse engineering.
