### ISSUE TITLE
LoadExtension SQLite

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/efcore#30522]
Hi,

LoadExtension is not working with ddl of https://github.com/nalgeon/sqlean/releases/tag/0.19.3 

Is there a reason ?

```cs
connection.Open();
connection.EnableExtensions(true);
connection.LoadExtension(filename);
```

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. Also, please provide the message and full stack trace of any exceptions thrown.

**Comment by suatsuphi** [comment]
[https://github.com/suatsuphi/ConsoleAppSqlean](https://github.com/suatsuphi/ConsoleAppSqlean)

Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
An unhandled exception of type 'Microsoft.Data.Sqlite.SqliteException' occurred in Microsoft.Data.Sqlite.dll
SQLite Error 1: ''.


`cs
connection.LoadExtension(file.ToString());`

**Comment by ajcvickers** [comment]
@suatsuphi This works on my machine when I use `LoadExtension`. Are you sure you have compatible versions of the extensions? I downloaded from https://github.com/nalgeon/sqlean/releases/tag/0.19.3

**Comment by suatsuphi** [comment]
[sqlean-win-x64.zip](https://github.com/nalgeon/sqlean/releases/download/0.19.3/sqlean-win-x64.zip)

it is working

``` cs
//connection.LoadExtension(file.ToString());
ar command = connection.CreateCommand();
command.CommandText = $"select load_extension(\"{file}\"); "; ;
command.ExecuteScalar();
```

it is not working 

connection.LoadExtension(file.ToString());
//var command = connection.CreateCommand();
//command.CommandText = $"select load_extension(\"{file}\"); "; ;
//command.ExecuteScalar();

**Comment by ajcvickers** [comment]
@suatsuphi Don't know what to tell you. Running your code works for me.

**Comment by suatsuphi** [comment]
I know running my code because of me.

https://github.com/suatsuphi/ConsoleAppSqlean/blob/master/ConsoleAppSqlean/Program.cs 

update it try again

**Comment by ajcvickers** [comment]
@suatsuphi Still works for me.

**Comment by ajcvickers** [comment]
@suatsuphi Still works for me.

**Comment by suatsuphi** [comment]
how ? could you explain ?

**Comment by suatsuphi** [comment]
well, I downloaded my project [https://github.com/suatsuphi/ConsoleAppSqlean](https://github.com/suatsuphi/ConsoleAppSqlean)

it is not working. You said me that It is working.

`connection.LoadExtension("file")`

**Comment by ajcvickers** [comment]
Just noticed you are on 7.0.1. You should always be on the latest patch version--I was running with 7.0.4.

**Comment by suatsuphi** [comment]
thank you so much. 
I said that my project was not working.... :-)

But now, It is just working for commandText

It is not working for UseSqlite

**Comment by ajcvickers** [comment]
I downloaded your project, updated it to 7.0.4:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.4" />
  </ItemGroup>

```

Changed the path to where I the SQLite native dlls loaded (since I'm not going to load random native code posted on the Internet!):

```C#
var path = Path.GetFullPath(Path.Combine(@"C:\local\code\repros\sqlean-win-x64"));
```

And it runs fine:

```
C:/local/code/repros/ConsoleAppSqlean-master/ConsoleAppSqlean-master/ConsoleAppSqlean/bin/Debug/net7.0/ConsoleAppSqlean.exe
----------------------------
>>>>> aI
>>>>> aI
>>>>> ai
>>>>> aIlk Içerik
>>>>> ailk olmayan
-----------search-----------
ai
ailk olmayan
----------------------------


Process finished with exit code 0.
```

**Comment by suatsuphi** [comment]
I mean I have to get same result.  Because of like '%ai%' and contain("ai")

**Comment by ErikEJ** [comment]
i.Title.Contains(value))

Is probably not translated using LIKE .

**Comment by ajcvickers** [comment]
@suatsuphi So, is this issue no longer about calling `LoadExtension`? But rather than you think the translation for `Contains` should be have in the same way as the `like` function you are using? If so, this is because Contains is translated as below, and is case-sensitive. This is by-design.

```C#
      SELECT "p"."PostId", "p"."Title"
      FROM "Posts" AS "p"
      WHERE @__value_0 = '' OR instr("p"."Title", @__value_0) > 0
      ORDER BY "p"."Title"
```

**Comment by suatsuphi** [comment]
I guess you mean like and contain are not equal

**Comment by ajcvickers** [comment]
Correct. They are not the same.

**Comment by suatsuphi** [comment]
But It is working for SqlServer. There is patch for SQLite but it is just working for commandText, it is not working for UseSqlite

**Comment by suatsuphi** [comment]
> i.Title.Contains(value))
> 
> Is probably not translated using LIKE .

loadextentions doesn't work if you are using UseSqlite. shouldn't it work? why are unicode characters not wanted to work?

**Comment by ajcvickers** [comment]
@suatsuphi You are again being very unclear. To clarify what I think you mean, no loading of extensions will change the SQL that EF generates. This is by-design. This is not going to change.
