### ISSUE TITLE
When removing prior EDMX in Visual Studio residual things remain...

### ISSUE THREAD

**Issue by AcousticGuitar** [dotnet/efcore#3052]
If a user creates an EDMX file, and then wants to delete and create a new one (of the same table or even the same connection strings) the new work cannot have the same name because there's residual collateral in the project not entirely removed.  It can be common during development to delete and recreate the same things in order to "get a fresh start at times".

**Comment by rowanmiller** [comment]
This is an EF6 issue, can you open an issue on our CodePlex project http://entityframework.codeplex.com/. This GitHub project is for EF7 onwards.

BTW can you also include details of the artifacts that are left behind.
