### ISSUE TITLE
Changing Default Column Order

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#30529]
## Ask a question
I would like to change the default column order of all properties on all tables in my DB using custom logic.

What is the best way to do this?

Here are a few things unique about my scenario:
1.  All of my type inherit from a generic type.  Ie.  '''Frame<Contact>''', '''Frame<ContactAddress>''', etc.
2.  I use owned entities.

Also, it seems that EntityType.GetProperties only returns "direct" properties on my base generic instead of all properties from owned types on it too.

### Include provider and version information
EF Core version: 7.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.5.2)

**Comment by roji** [comment]
Have you seen [the documentation](https://learn.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-order) on this, is that insufficient?

**Comment by ajcvickers** [comment]
@TonyValenti Curious _why_ you want to change the column order. What does it impact?

**Comment by TonyValenti** [comment]
@roji - that is a good plan and I can do that.  But how do I get a list of all properties of an entity type since EntityType.GetProperties does not return all properties.?

**Comment by roji** [comment]
IEntityType.GetProperties() should return all properties that EF knows about an is mapping to columns (note the difference with entityType.ClrType.GetProperties() in the code sample on that page, which returns only properties on your CLR type and excludes shadow properties).

**Comment by TonyValenti** [comment]
@roji - Mabe there is a bug then.  Or I'm doing something wrong.
Here is some sample code that demonstrates the issue I have getting all properties.

Should I do something different?

```
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp6 {
    internal class Program {
        static void Main(string[] args) {

            var C = new MigrationDbContext();
            C.Database.EnsureCreated();
        }
    }

    public class MigrationDbContext : DbContext {
        public DbSet<Frame<Contact>> Contacts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder.UseInMemoryDatabase("Test");

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            base.OnModelCreating(modelBuilder);

            var EntityTypes = modelBuilder.Model.GetEntityTypes()
                .Where(x => !x.IsOwned())
                .ToList()
                ;

            foreach (var EntityType in EntityTypes) {
                var Props = EntityType.GetProperties().ToList();
                //ERROR:  NOT ALL PROPERTIES.  Only 1 Listed.
            }

        }

    }

    public class Frame { 
        public long Id { get; set; }
    }

    public class Frame<TData> : Frame
        where TData : class, new()
        {
        public TData Original { get; set; } = new();
        public TData Final { get; set; } = new();

    }

    [Owned]
    public abstract class OwnedMember { 
    
    }


    public class Contact : OwnedMember {
        public ContactCategoryId Category { get; set; } = new();
        public string Name { get; set; } = string.Empty;
    }

    public class IdReference : OwnedMember {
        public string Id { get; set; } = string.Empty;
    }

    public class ContactCategoryId : IdReference { }

}
```

**Comment by TonyValenti** [comment]
@roji -

This seems to group properties by the table, but I havent found a way to find the column name that will be used for a property.  All the values below seem to show the "relative to the owned type" column name and not the "relative to the table" column name.

```

            var G3 = AllProps.GroupBy(x => x.DeclaringEntityType.GetSchemaQualifiedTableName())
                .Select( x => new { 
                    Key = x.Key,
                    Values = (
                        from y in x
                        select new { 
                            A = y.GetColumnName(),
                            B = y.GetColumnBaseName(),
                            C = y.GetDefaultColumnBaseName(),
                            D = y.GetDefaultColumnName(),
                            E = y.GetFieldName(),
                            F = y.Name,
                        }
                    ).ToList()
                })
                .ToList()
                ;
```

**Comment by TonyValenti** [comment]
@roji -

This seems to group properties by the table, but I havent found a way to find the column name that will be used for a property.  All the values below seem to show the "relative to the owned type" column name and not the "relative to the table" column name.

```

            var G3 = AllProps.GroupBy(x => x.DeclaringEntityType.GetSchemaQualifiedTableName())
                .Select( x => new { 
                    Key = x.Key,
                    Values = (
                        from y in x
                        select new { 
                            A = y.GetColumnName(),
                            B = y.GetColumnBaseName(),
                            C = y.GetDefaultColumnBaseName(),
                            D = y.GetDefaultColumnName(),
                            E = y.GetFieldName(),
                            F = y.Name,
                        }
                    ).ToList()
                })
                .ToList()
                ;
```
