### ISSUE TITLE
Q: EF Core Connection resiliency ignore queries in transactions.

### ISSUE THREAD

**Issue by sommmen** [dotnet/efcore#30533]
Hello,

I have 2 apps:
- ASP.NET core rest WebApi
- Background job server (Hangfire)

99% of calls in the WebApi are either `.ToListAsync()` or `.FirstOrDefault()` to return some database results.
The background processor either Updates entities without a roundtrip (read, update) or with a round trip.
When a roundtrip is used i enclose the entire thing in a transaction (`.BeginTransactionAsync()`).

Now and then I get deadlocks in the WebApi (and perhaps also in my background processor).
In that case i want to just retry the query,
I don't want to retry any queries i set in a transaction, because i have my own error handling in that case.

I read:
https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency

But my problem with this is that i now have to refactor my app and create a custom execution strategy (because of custom transactions).
I don't like this, because its hard for colleagues who are not all too familiar with EF, and i'd have to refactor a bunch of code.

Is there a way to retry deadlocked `SELECT` statements whilst skipping queries inside a custom transaction?

EF Core version: 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows
IDE: Visual Studio 2022 17.4

**Comment by AndriySvyryd** [comment]
> Is there a way to retry deadlocked SELECT statements whilst skipping queries inside a custom transaction?

No. By definition, a transaction is atomic, no part can be retried without retrying the whole. If you don't need to retry the queries together with the update then don't include them in the same transaction.
