### ISSUE TITLE
Partial clearing of tracked entities

### ISSUE THREAD

**Issue by Zetanova** [dotnet/efcore#30540]
Tracked entities can be used to cache the parent entity 
and only the child entitles would need to be cleared. 

The `dbContext.ChangeTracking.Clear()` clears all entities 
and the next batch would require to reload all parent entries.

To add some kind of filter parameter like `dbContext.ChangeTracking.Clear(n => n.Entity is MyEntity)` 
or a simpler and stricter form like `dbContext.ChangeTracking.Clear<MyEntity>()`.

It would make sense in scenarios where a lot of child entities get added/updated 
and the parent entities are only a view.

**Comment by ajcvickers** [comment]
@Zetanova Is there a reason you can't use the recommended approach of a new context instance (or one from the pool) per unit of work here?

**Comment by Zetanova** [comment]
@ajcvickers The DbContext can be used to cache the foreign entities, else the would need to be fetched for each batch

if the algo is to first try to find the entity in the local store and after try to fetch it and then add/create it.

Example:
```csharp
var parent = await context.Parents.FindAsync(new object[] { model.Parent.Id }, cancellationToken);
if(parent is null) {
  parent = new ParentEntity 
  {
      Id = model.Parent.Id
  };
  context.Parents.Add(parent);
} 

var child = await context.Childs.FindAsync(new object[] { model.Child.Id }, cancellationToken);
if(child is null) {
  child= new ChildEntity 
  {
      Id = model.Child.Id,
      ParentId = parentEntity.Id
  };
  context.Childs.Add(child);
}

child.Value1 = model.Child.Property1;
child.Value2 = model.Child.Property2;
```

If this algo is used by an import job and the ratio between parent:child is 1000:100000 
it makes sens to only save+flush the childs after each 100-500 records 
and use the context to cache the parent entities.

**Comment by ajcvickers** [comment]
@Zetanova If you really want to do this, then you can use something like this:

```C#
foreach (var blogEntry in context.ChangeTracker.Entries<Blog>())
{
    blogEntry.State = EntityState.Detached;
}
```

**Comment by Zetanova** [comment]
@ajcvickers This method creates the entry instance.
It is a slim perf coast ok, but then it triggers the hole events
To make it for 500 entries x 1000 times it is noticeable

**Comment by ajcvickers** [comment]
@Zetanova The context data structures are not designed for detaching entities in a performant way, so whatever we do here will be someone slow. We don't plan to add any specific overloads of Clear that would encourage this.
