### ISSUE TITLE
PK Constraint error

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#30573]
I have and XtdRoot entity which is inherited in other entities like this:
```csharp
public abstract class XtdRoot
{
    public Guid Id { get; protected set; }
}
```

```csharp
[Table("xtd_languages", Schema = "dictionary")]
public sealed class XtdLanguage : XtdRoot
{
    public string Code { get; private set; }
    public string EnglishName { get; private set; }
    public string? NativeName { get; private set; }
    public string[]? Comments { get; private set; }
    public bool IsDefault { get; private set; }

    [Column(Order = 100)]
    public DateTime DateOfCreation { get; private set; }

    [Column(Order = 200)]
    public DateTime DateOfUpdate { get; private set; }

    [Column(Order = 300)]
    public User CreatedBy { get; private set; }

    [Column(Order = 400)]
    public User? UpdatedBy { get; private set; }
}
```

```csharp
[Table("value_aggregates", Schema = "dictionary")]
public class ValueAggregate : XtdRoot, IAggregateRoot
{
    public int Major { get; set; }
    public int Minor { get; set; }
    public string Code { get; private set; }
    public StatusOfActivation Status { get; set; }
    public Guid DictionaryId { get; set; }
    public XtdDictionary Dictionary { get; set; }
    public IReadOnlyCollection<XtdValue> Values => _values;
    public DateTime DateOfCreation { get; protected set; }
    public DateTime DateOfUpdate { get; protected set; }
    public User CreatedBy { get; protected set; }
    public User? UpdatedBy { get; protected set; }
```

I use TPC Mapping startegy like this:

```csharp
modelBuilder.Entity<XtdRoot>().UseTpcMappingStrategy();
```

and snakecase naming strategy like this:

```csharp
builder.Services.AddDbContext<ApplicationDbContext>(options =>
{
    options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTrackingWithIdentityResolution);
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default"), sql =>
    {
        sql.MigrationsHistoryTable("entity_framework_migrations", "dictionary");
    })
    .UseSnakeCaseNamingConvention();

    if (builder.Environment.IsDevelopment())
    {
        options.EnableDetailedErrors();
        options.EnableSensitiveDataLogging();
    }
});
```

The migration files shows that primary key constraints have the same name from XtdRoot:

```csharp
 public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "dictionary");

            migrationBuilder.CreateTable(
                name: "xtd_languages",
                schema: "dictionary",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    date_of_creation = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    date_of_update = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    code = table.Column<string>(type: "text", nullable: false),
                    english_name = table.Column<string>(type: "text", nullable: false),
                    native_name = table.Column<string>(type: "text", nullable: true),
                    comments = table.Column<string[]>(type: "text[]", nullable: true),
                    is_default = table.Column<bool>(type: "boolean", nullable: false),
                    created_by_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_by_name = table.Column<string>(type: "text", nullable: false),
                    updated_by_id = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by_name = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_xtd_root", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "value_aggregates",
                schema: "dictionary",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    date_of_creation = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    date_of_update = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    major = table.Column<int>(type: "integer", nullable: false),
                    minor = table.Column<int>(type: "integer", nullable: false),
                    code = table.Column<string>(type: "text", nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    dictionary_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_by_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_by_name = table.Column<string>(type: "text", nullable: false),
                    updated_by_id = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by_name = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_xtd_root", x => x.id);
                });
                
                ......................
}
```

And it's a problem:

warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (24ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='dictionary' AND c.relname='entity_framework_migrations');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DO $EF$
      BEGIN
          IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dictionary') THEN
              CREATE SCHEMA dictionary;
          END IF;
      END $EF$;
      CREATE TABLE dictionary.entity_framework_migrations (
          migration_id character varying(150) NOT NULL,
          product_version character varying(32) NOT NULL,
          CONSTRAINT pk_entity_framework_migrations PRIMARY KEY (migration_id)
      );
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='dictionary' AND c.relname='entity_framework_migrations');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT migration_id, product_version
      FROM dictionary.entity_framework_migrations
      ORDER BY migration_id;
info: Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '00000000000000_InitialCreate'.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DO $EF$
      BEGIN
          IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dictionary') THEN
              CREATE SCHEMA dictionary;
          END IF;
      END $EF$;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE dictionary.xtd_languages (
          id uuid NOT NULL,
          date_of_creation timestamp with time zone NOT NULL,
          date_of_update timestamp with time zone NOT NULL,
          code text NOT NULL,
          english_name text NOT NULL,
          native_name text NULL,
          comments text[] NULL,
          is_default boolean NOT NULL,
          created_by_id uuid NOT NULL,
          created_by_name text NOT NULL,
          updated_by_id uuid NULL,
          updated_by_name text NULL,
          CONSTRAINT pk_xtd_root PRIMARY KEY (id)
      );
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE dictionary.value_aggregates (
          id uuid NOT NULL,
          date_of_creation timestamp with time zone NOT NULL,
          date_of_update timestamp with time zone NOT NULL,
          major integer NOT NULL,
          minor integer NOT NULL,
          code text NOT NULL,
          status integer NOT NULL,
          dictionary_id uuid NOT NULL,
          created_by_id uuid NOT NULL,
          created_by_name text NOT NULL,
          updated_by_id uuid NULL,
          updated_by_name text NULL,
          CONSTRAINT pk_xtd_root PRIMARY KEY (id)
      );
Unhandled exception. Npgsql.PostgresException (0x80004005): 42P07: relation "pk_xtd_root" already exists
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Dictionaries.Api.Extensions.DatabaseExtension.DatabaseSeed(WebApplication app) in C:\code\Dictionaries\Dictionaries.Api\Extensions\DatabaseExtension.cs:line 14
   at Program.<Main>$(String[] args) in C:\code\Dictionaries\Dictionaries.Api\Program.cs:line 65
   at Program.<Main>(String[] args)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "pk_xtd_root" already exists
    File: index.c
    Line: 866
    Routine: index_create

**Comment by Julien-Marpault** [comment]
No, I juste tried it, and removing UseSnakeCaseNamingConvention avoid the problem

**Comment by Julien-Marpault** [comment]
I also tried to override key naming like this:

```csharp
modelBuilder.Entity<XtdDictionary>().HasKey(p=>p.Id).HasName("pk_xtd_dictionary_id");
modelBuilder.Entity<XtdLanguage>().HasKey(p=>p.Id).HasName("pk_xtd_language_id");
modelBuilder.Entity<XtdMultiLanguageText>().HasKey(p=>p.Id).HasName("pk_xtd_multi_language_text_id");
modelBuilder.Entity<XtdText>().HasKey(p=>p.Id).HasName("pk_xtd_text_id");

modelBuilder.Entity<ValueAggregate>().HasKey(p=>p.Id).HasName("pk_value_aggregate_id");
modelBuilder.Entity<XtdValue>().HasKey(p=>p.Id).HasName("pk_xtd_value_id");
```

But it doesn't work because the id property is inherited

**Comment by Julien-Marpault** [comment]
LowerCaseNamingConvention produces the same issue

**Comment by roji** [comment]
@Julien-Marpault since this doesn't reproduce without UseSnakeCaseNamingConvention, please move this issue to https://github.com/efcore/EFCore.NamingConventions. If it ends up being a problem in EF Core (unlikely), we can revisit it here.
