### ISSUE TITLE
Log Entity Framework queries to new output window source

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30576]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Log-Entity-Framework-queries-to-new-outp/10257847)._

---
Currently, when logging EF queries to the console they are mixed in with the Debug output. It would be really helpful to have the queries written to their own custom EF output window.

---
#### Feedback Bot on 1/20/2023, 03:21 AM: 

(private comment, text removed)

**Comment by roji** [comment]
EF cannot open a special window for its logging output - it's just a library that isn't aware of any windowing system. However, you can easily distinguish EF logs from non-EF logs, and set up your logging configuration to redirect EF logs to a special file, or possibly even open a window.
