### ISSUE TITLE
Support custom sqlite3.dll builds and PRAGMA execution

### ISSUE THREAD

**Issue by rainman-63** [dotnet/efcore#3057]
SQLite supports custom extensions, like the SQLite encryption extension, it would be helpful if there was a way to use a custom sqlite3.dll and execute PRAGMA commands to communicate with those extensions.

Thanks.

**Comment by rowanmiller** [comment]
You should be able to use a custom build, EF will just use whatever PInvoke will load. You should also be able to execute commands via `context.Database.ExecuteSqlCommand(...)`.

If you hit particular issues where EF is doing something that is blocking this scenario can you open issues with details of the issue.
