### ISSUE TITLE
[EF CORE 7] Some FluentAPI instruction ignored when configuring Stored Procedure

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#30584]
Hello guys, for configuring my model i use the fluent API. For my tables everything seem fine. But for the configuration of stored procedure some instruction doesn't work

for example this instruction
````
modelBuilder.Entity<AlertesDInac_Result>(entity =>
            {
                entity.HasNoKey();
                entity.Ignore(e => e.EcheanceStr).Ignore(e => e.Texte);//ne fonctionne pas ici, todo voir pourquoi
                entity.ToView(null);
            });
````
the stored procedure return a collection of AlertesDInac_Result, i added a partial on this class with these property not part of the database
````
public string EcheanceStr {get;set;}
public string Texte {get;set;}
````
if i run my stored procedure like that i have an error which say it cant fin these columns in the database

If i use the attribute decoration on my properties directly, this time it works
````
[NotMapped]
public string EcheanceStr {get;set;}
[NotMapped]
public string Texte {get;set;}
````

i don't know whats happen, i check the configuration was correctly called, and anyway some instruction works because if a remove for example le hasNoKey() i have another error

In addition of the NotMapped/Ignore instruction on the property, i notice the same behavior on a global class.

Do you have any explanations on that ?

thanks !

**Comment by ErikEJ** [comment]
Please share a complete repro. Have you considered letting EF Core Power Tools do the mapping for you?

**Comment by ErikEJ** [comment]
@julienGrd That is an old Obsolete version of the extension method.

**Comment by julienGrd** [comment]
@ErikEJ OK i understand, a first try of the migration was made in .NET 5 or 6, thanks for your help, the subject is close
