### ISSUE TITLE
JSON column update not tracked as "Modified" in ChangeTracker state

### ISSUE THREAD

**Issue by neozhu** [dotnet/efcore#30596]
I have noticed that when I update a JSON column in my database using Entity Framework Core, the ChangeTracker state of the corresponding entity is not set to "Modified". In my code, I have a "Pictures" column defined as JSON in the "Product" entity. When I update only this column, the following code does not return any entities with a state of "Modified":
```c#
foreach (var entry in context.ChangeTracker.Entries<BaseAuditableEntity>())
{
if (entry.State == EntityState.Modified)
{
// Do something
}
}
```

Is this expected behavior or is there something wrong with my code? How can I ensure that changes to JSON columns are tracked as "Modified" in the ChangeTracker state? Thanks for your help!

```C#
public class Product : BaseAuditableEntity
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public string? Brand { get; set; }
    public string? Unit { get; set; }
    public decimal Price { get; set; }
    public IList<ProductImage>? Pictures { get; set; }

}

public class ProductImage
{
    public required string Name { get; set; } 
    public decimal Size { get; set; }
    public required string Url { get; set; }
}
public class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.Ignore(e => e.DomainEvents);
        builder.OwnsMany(e => e.Pictures, build => build.ToJson());
    }
}
private void updateEntities(DbContext context)
    {
        var userId = _currentUserService.UserId;
        var tenantId = _tenantProvider.TenantId;
        foreach (var entry in context.ChangeTracker.Entries<BaseAuditableEntity>())
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    entry.Entity.CreatedBy = userId;
                    entry.Entity.Created = _dateTime.Now;
                    if (entry.Entity is IMustHaveTenant mustenant)
                    {
                        mustenant.TenantId = tenantId;
                    }
                    if (entry.Entity is IMayHaveTenant maytenant && !string.IsNullOrEmpty(tenantId))
                    {
                        maytenant.TenantId = tenantId;
                    }
                    break;

                case EntityState.Modified:
                    entry.Entity.LastModifiedBy = userId;
                    entry.Entity.LastModified = _dateTime.Now;
                    break;
                case EntityState.Deleted:
                    if (entry.Entity is ISoftDelete softDelete)
                    {
                        softDelete.DeletedBy = userId;
                        softDelete.Deleted = _dateTime.Now;
                        entry.State = EntityState.Modified;
                    }
                    break;
                case EntityState.Unchanged:
                    if (entry.HasChangedOwnedEntities())
                    {
                        entry.Entity.LastModifiedBy = userId;
                        entry.Entity.LastModified = _dateTime.Now;
                    }
                    break;
            }
        }
    }
```

![image](https://user-images.githubusercontent.com/1549611/228733927-cca2d6a8-676c-4daa-a206-0956b1e6c4e0.png)

EF Core version:7.04
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:7
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by neozhu** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Thank you for your reply,
this is my project https://github.com/neozhu/CleanArchitectureWithBlazorServer
you can just upload picture or remove a picture and then save
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/1549611/230234088-576928ff-1bd7-4e2e-b3b8-abc059b2eb0b.png">

**Comment by neozhu** [comment]
I found the product object's references are empty. normally the ProductImage collection includes the parent owner object references
![image](https://user-images.githubusercontent.com/1549611/230519862-8746e02f-8d2d-4999-a109-4afb1cf2fa6c.png)

**Comment by ajcvickers** [comment]
@neozhu This is by-design. The `Product` entity itself has not changed; rather the `ProductImage` entities have changed, and so will show up as Added/Deleted/Modified in the change tracker.
