### ISSUE TITLE
Mapping entity and derived entity to separate tables using TPC

### ISSUE THREAD

**Issue by lonix1** [dotnet/efcore#30607]
I originally asked this on [SO](https://stackoverflow.com/q/75906462/9971404) without success, so I'm asking here as a last resort. Thanks.

## Ask a question
Consider my simple example:
- I have two entities: `ProformaInvoice` and `Invoice`
- a proforma is issued, and if accepted, is "converted" to a real invoice
- should be mapped to different tables because there are 100x more proforma invoices (which are often treated as quotations) than invoices
- schema of a proforma invoice and invoice are almost identical

So I assumed that I must use TPC.

Entities:
````cs
public class Customer
{
  public long Id { get; set; }
  public ICollection<ProformaInvoice> ProformaInvoices { get; set; }
  public ICollection<Invoice> Invoices { get; set; }
}

public class Invoice
{
  public long Id { get; set; }
  public double Value { get; set; }
  public Customer Customer { get; set; }
}

public class ProformaInvoice : Invoice
{
  public string Notes { get; set; }
}
````

Context:
````cs
public class MyContext : DbContext
{

  public DbSet<Customer> Customers => Set<Customer>();
  public DbSet<ProformaInvoice> ProformaInvoices => Set<ProformaInvoice>();
  public DbSet<Invoice> Invoices => Set<Invoice>();

  protected override void OnModelCreating(ModelBuilder builder)
  {
    base.OnModelCreating(builder);

    var customerBuilder = builder.Entity<Customer>();
    customerBuilder.HasKey(x => x.Id);
    customerBuilder.HasMany(x => x.ProformaInvoices).WithOne(x => x.Customer).OnDelete(DeleteBehavior.Cascade);
    customerBuilder.HasMany(x => x.Invoices).WithOne(x => x.Customer).OnDelete(DeleteBehavior.Cascade);

    var invoiceBuilder = builder.Entity<Invoice>();
    invoiceBuilder.UseTpcMappingStrategy();             // TPC
    invoiceBuilder.HasKey(x => x.Id);
    invoiceBuilder.Property(x => x.Value).IsRequired();

    var proformaInvoiceBuilder = builder.Entity<ProformaInvoice>();
    //proformaInvoiceBuilder.HasKey(x => x.Id);         // do not configure key else get error "A key cannot be configured on 'ProformaInvoice' because it is a derived type. The key must be configured on the root type 'Invoice'."
    proformaInvoiceBuilder.Property(x => x.Value).IsRequired();
    proformaInvoiceBuilder.Property(x => x.Notes).IsRequired();
  }

}
````

Create migration:
````shell
$ dotnet ef migrations add AddEntities
````

Error:
> Cannot create a relationship between 'Customer.Invoices' and 'Invoice.Customer' because a relationship already exists between 'Customer.ProformaInvoices' and 'ProformaInvoice.Customer'. Navigations can only participate in a single relationship. If you want to override an existing relationship call 'Ignore' on the navigation 'Invoice.Customer' first in 'OnModelCreating'.

In the SO question linked above, it was explained to me that TPC is for mapping relationships that should be represented in the db as well. Obviously that's not what I want - I just want a 1:1 mapping of my classes to separate tables. However in the [community standup](https://www.youtube.com/watch?v=HaL6DKW1mrg) I recall that someone said I could use TPC for this use case too.

TPC is still relatively new, so there's not that much on SO right now.

What is the correct approach? Thank you!

### Include provider and version information

EF Core version: 7
Database provider: Postgres
Target framework: 7
Operating system: linux
IDE: vscode

**Comment by ajcvickers** [comment]
@lonix1 I don't think you need TPC for this. You just need to tell EF not to treat the invoice types are part of the same hierarchy:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<ProformaInvoice>().HasBaseType((Type?)null);
}
```
