### ISSUE TITLE
How to change the type of a single entity in a one-to-many collection?

### ISSUE THREAD

**Issue by ilivit** [dotnet/efcore#30611]
### Question
How to properly replace an item kind A with an item kind B without changing the item's Id (there are other entities referencing the item)?

### Summary
In our project we want to be able to change the kind of an entity from the collection of entities (one to many relationship). I.e. given the items map containing a collection of items (each item has a set of common properties and some specific properties defined by its kind); in the items map we should be able to change the item's kind (and redefine its properties values accordingly) without breaking the refernces to other entities.

### Failed attempt 1
Originally we had the entities defined in the following way:
```C#
public class ItemsMap
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public virtual List<Item> Items { get; set; }
}

public abstract class Item
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public virtual ItemsMap ItemsMap { get; }
}

public class ItemA : Item
{
    public string A { get; set; }
}

public class ItemB : Item
{
    public string B { get; set; }
}
```

DbContext:

```c#
public class AppDbContext : DbContext
{
    public DbSet<ItemsMap> ItemsMaps => Set<ItemsMap>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<ItemsMap>().HasMany(m => m.Items).WithOne(i => i.ItemsMap);

        builder.Entity<Item>().UseTptMappingStrategy();
        builder.Entity<ItemA>();
        builder.Entity<ItemB>();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseLazyLoadingProxies();
}
```

The initial data state:
```c#
context.ItemsMaps.Add(new ItemsMap()
{
    Items = new() { new ItemA() { A = "a" } }
});
```

With that configuration we tried to simply replace the the item in the collection
```c#
// executed in the domain project thus doens't have access to the context
var itemA = map.Items.First();
var idx = map.Items.IndexOf(itemA);
map.Items[idx] = new ItemB() { Id = itemA.Id, B = "b" };
```
or delete and insert the item
```c#
// executed in the domain project thus doens't have access to the context
var itemA = map.Items.First();
map.Items.Remove(itemA);
var itemB = new ItemB() { Id = itemA.Id, B = "b" };
map.Items.Add(itemB);
```

This approach didn't work. The ChangeTracker would contain:
```
[0] = {EntityEntry} ItemB (Shared) {Id: 3aeb6d8a-561e-40e9-a549-99b870299ce1} Modified FK {ItemsMapId: 1569a107-25b9-431c-85cc-18ce0c0d37a5} FK {Id: 3aeb6d8a-561e-40e9-a549-99b870299ce1}
[1] = {EntityEntry} ItemA (Shared) {Id: 3aeb6d8a-561e-40e9-a549-99b870299ce1} Deleted FK {ItemsMapId: 1569a107-25b9-431c-85cc-18ce0c0d37a5} FK {Id: 3aeb6d8a-561e-40e9-a549-99b870299ce1}
[2] = {EntityEntry} ItemsMap {Id: 1569a107-25b9-431c-85cc-18ce0c0d37a5} Unchanged
```

Calling `context.SaveChanges()` would generate these SQL commands:
```sql
Executed DbCommand (2ms) [Parameters=[@p1='36f849b8-d85e-4b74-87e9-a2a6cb64779d', @p0='004c0b63-8605-40de-a2c3-84cd6e5fefe0', @p3='36f849b8-d85e-4b74-87e9-a2a6cb64779d', @p2='b' (Nullable = false)], CommandType='Text', CommandTimeout='30']

UPDATE "Item" SET "ItemsMapId" = @p0
WHERE "Id" = @p1;

UPDATE "ItemB" SET "B" = @p2
WHERE "Id" = @p3;
```

### Failed attempt 2

Then we tried to make the kind-related attributes as a separate entity, so we only change them instead of replacing the whole item. But this try failed as well.

Entities structure:

```c#
public class ItemWithAttrs
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public virtual Attrs Attrs { get; set; }
}

public abstract class Attrs
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ItemId { get; }
}

public class AttrsA : Attrs
{
    public string A { get; set; }
}

public class AttrsB : Attrs
{
    public string B { get; set; }
}
```

DbContext:
```c#
public class AppDbContext : DbContext
{
    public DbSet<ItemWithAttrs> ItemsWithAttrs => Set<ItemWithAttrs>();    

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<ItemWithAttrs>().HasOne(i => i.Attrs).WithOne().HasForeignKey<Attrs>(a => a.ItemId);

        builder.Entity<Attrs>().UseTpcMappingStrategy();
        builder.Entity<AttrsA>();
        builder.Entity<AttrsB>();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseLazyLoadingProxies();
}
```

The initial data state:
```c#
context.ItemsWithAttrs.Add(new ItemWithAttrs() { Attrs = new AttrsA() { A = "a" } });
```

Updating the item was made the following way:
```c#
// executed in the domain project thus doens't have access to the context
item.Attrs = new AttrsB() { B = "b" };
```

 The ChangeTracker would contain:
```
[0] = {EntityEntry} AttrsB {Id: 52218988-dc52-45b5-8eb7-482b3bac3c74} Modified FK {ItemsMapId: fb0ef1cf-f1ab-4613-a1ac-f06d5b1c0575}
[1] = {EntityEntry} ItemWithAttrs {Id: fb0ef1cf-f1ab-4613-a1ac-f06d5b1c0575} Unchanged
```

Calling `context.SaveChanges()` would generate these SQL commands:
```sql
Executed DbCommand (2ms) [Parameters=[@p2='428dfbce-592a-426b-87e8-39d7a7b6f557', @p0='b' (Nullable = false), @p1='6dab5186-4082-45fb-99ac-6e1504914aaf'], CommandType='Text', CommandTimeout='30']

UPDATE "AttrsB" SET "B" = @p0, "ItemsMapId" = @p1
WHERE "Id" = @p2;
```

### Provider and version information
EF Core version: 7.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7.0
Operating system: Windows, Linux

**Comment by ajcvickers** [comment]
@ilivit We will discuss this. Since C# does not allow an object to change its type, it becomes very easy to get into an inconsistent state if the representation of the object changes type in the database. That being said, we do allow this with TPH if the discriminator is mapped as a property that can still be changed after it has been saved for the first time. (As a foot guard, it's not allowed by default even in TPH.) In this case, you are using TPT, which means the representation in the database would need to be moved from one table to another. I suspect this will require raw SQL, but, as I said, we will discuss.

**Comment by ilivit** [comment]
@ajcvickers Note that the attempt 2 has one-to-one relation on `ItemWithAttrs.Attrs`.

I tried to make a workaround by keeping the kind specific attributes in one-to-many collection internally (and showing them as a singular property publicly) but this doesn't work either. Seems like a bug to me, here's an example how to reproduce it.

The item class has `Attrs` as a collection with the base type 
```c#
public class ItemWithAttrs
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public virtual List<Attrs> Attrs { get; set; }
}
```
`Attrs` and its inheritors has the same configuration as in the first message, `ItemWithAttrs` configuration is the following:
```c#
builder.Entity<ItemWithAttrs>().HasMany(i => i.Attrs).WithOne().HasForeignKey(a => a.ItemsMapId);
```

Initially, there is one `ItemWithAttrs` item with one `AttrsA` item in the `Attrs` collection  in the database:
```c#
new ItemWithAttrs() { Attrs = new List<Attrs>() { new AttrsA() { Id = Guid.NewGuid(), A = "a" }}}
```

Then execute these steps
```c#
item.Attrs.Clear();
item.Attrs.Add(new AttrsB() { Id = Guid.NewGuid(), B = "b"});
```
The ChangeTracker would contain 
```
[0] = {EntityEntry} AttrsB {Id: c5fe8eb2-df4e-4d03-b932-dbb5b8c35760} Modified FK {ItemsMapId: 91b34f2a-81bb-44ba-aabe-1c89fc4f5e91} FK {Id: c5fe8eb2-df4e-4d03-b932-dbb5b8c35760}
[1] = {EntityEntry} AttrsA {Id: 526b9b61-c46c-42f9-8a88-823413ee469c} Deleted FK {ItemsMapId: 91b34f2a-81bb-44ba-aabe-1c89fc4f5e91} FK {Id: 526b9b61-c46c-42f9-8a88-823413ee469c}
[2] = {EntityEntry} ItemWithAttrs {Id: 91b34f2a-81bb-44ba-aabe-1c89fc4f5e91} Unchanged
```

The newly added item should be in the `Added` state but it is in the `Modified` state. This behavior doesn't chage regardless of the type (A or B) of the added item.

This behavior reproducible when TPT or TPC strategy used for `Attrs`, but with TPH this works fine. Unfortunately, we can't use TPH.

Should I report this separately?

**Comment by ajcvickers** [comment]
@ilivit It's in the modified state because the primary key properties are configured as generated, but the code is setting an explicit key value. When EF sees that a key value exists, it uses that information to mean that the entity is not new and so attempts to update it in the database. If you tell EF that the key properties are not generated, then it will no longer assume that a key with a value set indicates an existing entity. For example:

```C#
        builder.Entity<Attrs>().Property(e => e.Id).ValueGeneratedNever();
        builder.Entity<ItemWithAttrs>().Property(e => e.Id).ValueGeneratedNever();
```

See [Generated versus explicit key values](https://learn.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#generated-versus-explicit-key-values).

**Comment by ajcvickers** [comment]
Note from triage: this should be supported by the implementation of #30705.
