### ISSUE TITLE
EFCore6.x 用代码实现自动迁移

### ISSUE THREAD

**Issue by xiaomazz** [dotnet/efcore#30619]
现在实际开发中，我们都是在PMC中敲Add-Migration ，然后执行Update-Database这样来迁移数据库和数据表；

但是现在我想用代码来实现全自动数据库，表的迁移，查了很多资料都没有找到合适的，很多都是efcre 3.x以下的，很多方法都被移除了，不适用于efcore6.x

所以我想得到一些推荐的开源库或者其他的途径可以解决我提的这个功能

Machine translation:

Automated Migration with Code

Now in the actual development, we all type Add-Migration in the PMC, and then execute Update-Database to migrate the database and data table;

But now I want to use code to realize fully automatic database and table migration. I searched a lot of information but failed to find a suitable one. Many of them are below efcre 3.x. Many methods have been removed and are not applicable to efcore6.x

So I want to get some recommended open source libraries or other ways to solve the function I mentioned

**Comment by ajcvickers** [comment]
Automatic migrations are not implemented by design. See #6214 for more information.

**Comment by xiaomazz** [comment]
var commands = sqlGenerator?.Generate(operations, context.Model);
            var connection = serviceProvider.GetService<IRelationalConnection>();
            var typeMappingSource = serviceProvider.GetService<IRelationalTypeMappingSource>();
            // Take a snapshot to the newest model
            var codeHelper = new CSharpHelper(typeMappingSource);

       
            var dependencies = serviceProvider.GetRequiredService<MigrationOperationGeneratorDependencies>();
            var generator = new MigrationsGenerator(
                new MigrationsCodeGeneratorDependencies(typeMappingSource),
                new MigrationsGeneratorDependencies(
                    codeHelper,
                    new MigrationOperationGenerator(
                        new MigrationOperationGeneratorDependencies(codeHelper)),
                    new SnapshotGenerator(new SnapshotGeneratorDependencies(codeHelper, typeMappingSource))));

            var modelSnapshot = generator.GenerateSnapshot(
                DbMigrationConstant.ModelSnapshotNamespace, context.GetType(),
                DbMigrationConstant.ModelSnapshotClassPrefix + DateTime.UtcNow.Ticks, context.Model);
                
                
                
![image](https://user-images.githubusercontent.com/52307384/229736696-90693600-6b0a-436b-817d-655eed4b2d28.png)
我的efore版本为6.015，貌似没有这些类
