### ISSUE TITLE
Set different configuration in IEntityTypeConfiguration based on provider

### ISSUE THREAD

**Issue by Bykiev** [dotnet/efcore#30624]
Hi, I'm using fluent API to configure entities and I need to use 2 DB providers: Postgres and SQL Server. I didn't find any way to set different configuration for specific providers. Of course I can pass `DatabaseFacade.ProviderName` directly in constructor, but I'm loading configuration classes dynamically from assembly and don't want to create them manually. Is any other way to get provider name from `IEntityTypeConfiguration`?

EF Core version: latest
Target framework: (.NET 6.0)

**Comment by ajcvickers** [comment]
We discussed this in triage, and it is not something for which we are going to build in support. Adding dependencies to configuration classes (or, indeed using a completely different implementation) is pretty easy, and custom assembly scanning code can be used to do whatever is needed with for these configurations.

**Comment by Bykiev** [comment]
Thank you!
