### ISSUE TITLE
Review AddEntityFramework for consistency with other AddXyz 

### ISSUE THREAD

**Issue by HaoK** [dotnet/efcore#3064]
Looks like we've settled on the the following pattern for the other frameworks top level IServiceCollection extension method:

`AddXyz()`
`AddXyz(Action<XyzOptions)` overload that configures the framework

Just filing this issue for EF to see if this is an applicable pattern to consider using as well

**Comment by divega** [comment]
I think EF is already as consistent as it needs to be with the pattern. The only difference is by design: the options apply to the context type as there aren't framework wide options to set.
