### ISSUE TITLE
Cannot drop a column and add another one in the same migration when using temporal tables

### ISSUE THREAD

**Issue by orty** [dotnet/efcore#30648]
Hi,

I encountered an issue when, in the same migration, I try to add a new column and drop an existing one in a table with the `SYSTEM_VERSIONING = ON` setting. 

A quick debug through an empty custom `SqlServerMigrationsSqlGenerator` to look at the operations executed showed that the following order is applied:

- SYSTEM_VERSION=OFF
- DROP COLUMN
- ADD COLUMN
- SYSTEM_VERSION=ON

which fails with error: `Setting SYSTEM_VERSIONING to ON failed because table '[tableName]' has 19 columns and table '[tableName]History' has 18 columns.`

I double checked that the following order works as intended, but had to modify manually the order of the operation to validate this test:

- SYSTEM_VERSION=OFF
- DROP COLUMN
- SYSTEM_VERSION=ON
- ADD COLUMN

Any chance this correct order of operation could be generated when applying such a migration ?
Thanks

### Include provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 11
IDE: Visual Studio 2022 17.3.6

**Comment by orty** [comment]
As I read the source of the class `SqlServerMigrationsSqlGenerator` in the main branch, I have the feeling that this issue has been addressed in EF Core 7, am I right ?

We currently have too many breaking changes dependencies to justify a version update, but if this is the case, it adds up on the list of 'pros' ^^

**Comment by ajcvickers** [comment]
> too many breaking changes dependencies

Can you elaborate on the breaking dependencies that prevent you updating to EF Core 7? (Note that EF Core 7 runs on .NET 6.)

**Comment by maumar** [comment]
I verified that this scenario works on 7.0 bits

The order we do is:

- SYSTEM_VERSION=OFF
- DROP COLUMN in actual table
- DROP COLUMN in history table
- ADD COLUMN in actual table
- ADD COLUMN in history table
- SYSTEM_VERSION=ON

**Comment by maumar** [comment]
related issue: https://github.com/dotnet/efcore/issues/27423

**Comment by roji** [comment]
@orty whatever 3rd-party library you're using for UPSERTs should presumably work also with EF Core 7. The new [ExecuteUpdate/ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) APIs in EF Core 7.0 don't mean you have to drop your 3rd-party library (note that they also do not provide any UPSERT functionality).
