### ISSUE TITLE
AddPooledDbContextFactory and AddScoped

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#30654]
Is the following approach to using both a pooled `DbContext` and the "regular" way of resolving `DbContext` safe?

```csharp
services.AddPooledDbContextFactory<MyDbContext>((options) =>
{
    // options.UseNpgsql(...
});

services.AddScoped<MyDbContext>((provider) => provider.GetRequiredService<IDbContextFactory<MyDbContext>>().CreateDbContext());
```

My issue is that some code in my application needs to be able to use a pooled `DbContext`, while others require it to be resolved in the more typical fashion (without a factory).  I just want to make sure that what I'm doing makes sense and that I shouldn't be trying to discover if a context has already been served for the current thread, or if the one I'm getting is safe to use and will be disposed of correctly...

**Comment by ajcvickers** [comment]
@atrauzzi Looks like it should be okay.

**Comment by moander** [comment]
This exact behavior is documented here

https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics

<img width="978" alt="image" src="https://user-images.githubusercontent.com/380191/232130199-bdbdd24e-e3c1-4caa-995a-fe848c480368.png">
