### ISSUE TITLE
Make the compiled query more suitable for use in Repository Pattern

### ISSUE THREAD

**Issue by luizfbicalho** [dotnet/efcore#30658]
The real problem for me is that the compiled query is to conected with the dbcontext, my idea is that the Compiled query would be just based on the entity Type

This way it could be better used in Abstract repository pattern

instead of this method (and obviously the other methods and different parameters, cancellation token, and others) 

```C#
Func<TContext, IAsyncEnumerable<TResult>> CompileAsyncQuery<TContext, TResult>(
            Expression<Func<TContext, IQueryable<TResult>>> queryExpression)
            where TContext : DbContext
```

I would think of this method

```C#
Func<DbSet<TEntity>, IAsyncEnumerable<TResult>> CompileAsyncQuery<
            TEntity,
            TResult>(
            Expression<Func<IQueryable<TEntity>, IQueryable<TResult>>> queryExpression)
            where TEntity: class
```

One other example would be

``` C#
 static Func<TContext, Task<TResult>> CompileAsyncQuery<TContext, TResult>(
            Expression<Func<TContext, TResult>> queryExpression)
            where TContext : DbContext
```
``` C#
 Func<DbSet<TEntity>, Task<TResult>> CompileAsyncQuery<TEntity, TResult>(
           Expression<Func<IQueryable<TEntity>, TResult>> queryExpression)
            where TEntity: class
```

**Comment by ajcvickers** [comment]
@luizfbicalho How does using `DbSet` instead of `DbContext` fundamentally change the dependencies?

**Comment by luizfbicalho** [comment]
@ajcvickers 
In my example I don't pass anything other than the entity, and the returned function has a dbset parameter, this way I can register the compiled query in my repository just passing the func and only internally in the repository it would use the DbSet

**Comment by roji** [comment]
@luizfbicalho keep in mind that a single query may need to access more than a single DbSet (e.g. because of Join).

In any case, the typical pattern is for the repository to wrap a DbContext rather than a DbSet; I'm not sure why exactly you're looking to do it differently - maybe some code showing what you're trying to do could help understand.

**Comment by luizfbicalho** [comment]
I created this example, it doesn't work but it's just to show the idea

How I use my repository today, and my idea for the compiled queries



```C#
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;

namespace CompileQuery
{
    public class CompileQuery
    {
        static async Task Main(string[] args)
        {
            CancellationToken ct = CancellationToken.None;
            var optionsBuilder = new DbContextOptionsBuilder<ModelContext>().UseLazyLoadingProxies()
                .UseSqlServer("Server=.\\sql2019;Database=CompileQuery;Trusted_Connection=false;user id=sa;pwd=sa!2019;MultipleActiveResultSets=true;Encrypt=false");
            using (var context = new ModelContext(optionsBuilder.Options))
            {
                await context.Database.EnsureDeletedAsync();
                await context.Database.EnsureCreatedAsync();

                var child1 = new Child() { Name = "Child 1" };
                var child2 = new Child() { Name = "Child 2" };
                var child3 = new Child() { Name = "Child 3" };

                var parent1 = new Parent() { Name = "Parent 1", Child = child1 };
                var parent2 = new Parent() { Name = "Parent 2", Child = child2 };
                var parent3 = new Parent() { Name = "Parent 3", Child = child3 };

                context.Add(parent1);
                context.Add(parent2);
                context.Add(parent3);
                context.Add(child1);
                context.Add(child2);
                context.Add(child3);
                await context.SaveChangesAsync();

                //This is how I use today
                IAsyncRepository<Parent> repo = new Repository<Parent>(context);

                var parent = await repo.QueryScalarAsync(x => x.Include(i => i.Child).FirstOrDefaultAsync(ct));
                var list = await repo.QueryAsync(x => x.Include(i => i.Child), ct);

                // this is the compiled today
                var compiled = EF.CompileAsyncQuery((DbContext c) => c.Set<Parent>().Include(i => i.Child).First());
                var compiledList = EF.CompileAsyncQuery((DbContext c) => c.Set<Parent>().Include(i => i.Child));

                await compiled(context);

                await foreach (var i in compiledList(context))
                {

                }

                // this is how I imagine, lot of work to make it run 

                var newCompiled = EF.CompileAsyncQuery<Parent, Parent?>((q) => q.Include(i => i.Child).FirstOrDefaultAsync(ct));
                var newCompiledList = EF.CompileAsyncQuery<Parent, Parent>((q) => q.Include(i => i.Child));

                var newparent = await repo.QueryScalarAsync(newCompiled);
                var newlist = await repo.QueryAsync(newCompiledList);

            }

        }

    }
    public class Repository<TEntity> : IAsyncRepository<TEntity> where TEntity : class
    {
        private DbSet<TEntity> Set { get; }
        public Repository(DbContext context)
        {
            Set = context.Set<TEntity>();
        }
        public async Task<IQueryable<T>> QueryAsync<T>(Expression<Func<IQueryable<TEntity>, IQueryable<T>>> expression, CancellationToken ct = default)
        {

            var list = await expression.Compile().Invoke(Set).ToListAsync(ct);
            return list.AsQueryable();
        }

        public async Task<T> QueryScalarAsync<T>(Expression<Func<IQueryable<TEntity>, Task<T>>> expression, CancellationToken ct = default)
        {
            return await expression.Compile().Invoke(Set);
        }
    }


    public interface IAsyncRepository<TEntity> where TEntity : class
    {
        Task<IQueryable<T>> QueryAsync<T>(Expression<Func<IQueryable<TEntity>, IQueryable<T>>> expression, CancellationToken ct = default);
        Task<T> QueryScalarAsync<T>(Expression<Func<IQueryable<TEntity>, Task<T>>> expression, CancellationToken ct = default);
    }

    public class Parent
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        [Required]
        public virtual Child Child { get; set; } = null!;
    }

    public class Child
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }

    public class ModelContext : DbContext
    {
        public Func<DbSet<TEntity>, IAsyncEnumerable<TResult>> CompileAsyncQuery<
            TEntity,
            TResult>(
            Expression<Func<IQueryable<TEntity>, IQueryable<TResult>>> queryExpression)
            where TEntity : class
        {
            return s => queryExpression.Compile().Invoke(s).AsAsyncEnumerable();
        }
        public Func<DbSet<TEntity>, Task<TResult>> CompileAsyncQuery<TEntity, TResult>(
          Expression<Func<IQueryable<TEntity>, Task<TResult>>> queryExpression)
           where TEntity : class
        {
            return s => queryExpression.Compile().Invoke(s);
        }

        public ModelContext(DbContextOptions<ModelContext> options) : base(options) { }
        public DbSet<Parent> Parent { get => Set<Parent>(); }
        public DbSet<Child> Child { get => Set<Child>(); }
    }
}
```

**Comment by roji** [comment]
@luizfbicalho there are many things that don't really work with you proposal. For one thing, as I wrote, a single query can access multiple DbSets (e.g. via Join), so EF.CompileAsyncQuery needs the get the DbContext as a parameter so it can access them.

More importantly, EF simply cannot compile a LINQ query without a DbContext; the DbContext is the configuration where you e.g. determine which database provider is being used (SQL Server? PostgreSQL?), as well as various other essential info. Nothing can be done without all that.

Note that EF.CompileAsyncQuery does not (and should not) return an IQueryable, as implied by your code above - it returns a fully baked delegate that's ready to run. If it returned an IQueryable, that wouldn't be a ready-to-run compiled query, since you could compose more operators on top of it etc.

I also don't really understand the sense of having a `Repository<TEntity>` with generic QueryAsync methods that accept an expression tree as an argument... The usual point of having a repository layer is to encapsulate the query within it, so that e.g. the repository can be easily mocked for testing, or that implementations (e.g. for different database providers) can be swapped out. Your above design goes against that by externalizing the query, to the point where I'm not sure what the Repository is actually supposed to achieve.

**Comment by luizfbicalho** [comment]
Thanks for that complete explanation @roji , in my head the compilation was an otimization only in the linq query.

I'll comment each paragraph just for make the result of this issue complete

> @luizfbicalho there are many things that don't really work with you proposal. For one thing, as I wrote, a single query can access multiple DbSets (e.g. via Join), so EF.CompileAsyncQuery needs the get the DbContext as a parameter so it can access them.

In our projects we don't give all the developers the chance to make joins besides the object relations that we expose, this way we control more the visibility of the model and prevent loading errors

> More importantly, EF simply cannot compile a LINQ query without a DbContext; the DbContext is the configuration where you e.g. determine which database provider is being used (SQL Server? PostgreSQL?), as well as various other essential info. Nothing can be done without all that.

I think that this is the most critical issue in my proposal


> Note that EF.CompileAsyncQuery does not (and should not) return an IQueryable, as implied by your code above - it returns a fully baked delegate that's ready to run. If it returned an IQueryable, that wouldn't be a ready-to-run compiled query, since you could compose more operators on top of it etc.

The idea os using a partially compiled query was in my radar, I admit that was a big improvement for me.

> I also don't really understand the sense of having a Repository<TEntity> with generic QueryAsync methods that accept an expression tree as an argument... The usual point of having a repository layer is to encapsulate the query within it, so that e.g. the repository can be easily mocked for testing, or that implementations (e.g. for different database providers) can be swapped out. Your above design goes against that by externalizing the query, to the point where I'm not sure what the Repository is actually supposed to achieve.

We have a generic repository and we use commands to read and events do make changes in the database, so the generic repository works fine with the expressions


Thanks again @ajcvickers  and @roji  for the time and the ideas changed here

**Comment by roji** [comment]
> In our projects we don't give all the developers the chance to make joins besides the object relations that we expose, this way we control more the visibility of the model and prevent loading errors

I'm not aware of any particular reason to avoid joins, or what loading errors you might be referring to - joins are a safe, valid thing to do in queries.
