### ISSUE TITLE
Sqlite: Cannot add a column with non-constant default

### ISSUE THREAD

**Issue by replaysMike** [dotnet/efcore#30667]
I am unable to add a default value to a new datetime column if the Sqlite table is not empty. It works fine if the table has no data, but altering a table to add a column does not work in this instance.

```csharp
ALTER TABLE "Users" ADD "DateModifiedUtc" TEXT NOT NULL DEFAULT (DATETIME('now'));
// throws exception: SqliteException Cannot add a column with non-constant default
```

```csharp
ALTER TABLE "SomeOtherTable" ADD "DateModifiedUtc" TEXT NOT NULL DEFAULT (DATETIME('now'));
// works fine if table is empty
```

**The problem:** 

The reason of course being Sqlite doesn't support modifying the default value using a computed field on a non-empty table. EF creates ef_temp_* tables normally when performing modifcations, but it doesn't seem to do this when altering the default value for a column in a table - hence the error.

```sql
ALTER TABLE "SomeOtherTable" ADD "DateModifiedUtc" TEXT NOT NULL DEFAULT (DATETIME('now'));
```

**Proposed fix:**

I think the fix here has to be adding temp table, modifying the schema, then import the data and rename the temp table to the original.

This is tough to deal with outside of the provider. I can't easily come up with a workaround, as I'm supporting a DbContext with multiple providers (each utilizing a `MigrationsSqlGenerator`) which translates default values for Created/Modified date using the date method for the appropriate provider. Sqlite is the only one this doesn't work for.

EF Core version: 7.0.4
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7.0)
Operating system: Windows 10 Pro
IDE: Visual Studio 2022 17.4

**Comment by replaysMike** [comment]
In an attempt at a workaround, I've tried using the `MigrationsSqlGenerator` to overwrite the DefaultValueSql to null and replace it with a constant DefaultValue: "2023-04-12T04:22:29Z".

However this just leads to a `Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 20: 'datatype mismatch'.` which seems to be due to the way `ef_temp_*` tables are generated.

```
CREATE TABLE "ef_temp_OAuthCredentials" (
    "OAuthCredentialId" INTEGER NOT NULL CONSTRAINT "PK_OAuthCredentials" PRIMARY KEY AUTOINCREMENT,
    "AccessToken" TEXT NULL,
    "DateCreatedUtc" TEXT NOT NULL DEFAULT '"2023-04-12T04:22:29Z"',
    "DateExpiresUtc" TEXT NOT NULL,
    "DateModifiedUtc" TEXT NOT NULL DEFAULT '"2023-04-12T04:22:29Z"',
    "Ip" INTEGER NOT NULL DEFAULT 0,
    "Provider" TEXT NOT NULL,
    "RefreshToken" TEXT NULL,
    "UserId" INTEGER NULL,
    CONSTRAINT "FK_OAuthCredentials_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO "ef_temp_OAuthCredentials" ("OAuthCredentialId", "AccessToken", "DateCreatedUtc", "DateExpiresUtc", "DateModifiedUtc", "Ip", "Provider", "RefreshToken", "UserId")
      SELECT "OAuthCredentialId", "AccessToken", "DateCreatedUtc", "DateExpiresUtc", "DateModifiedUtc", "Ip", "Provider", "RefreshToken", "UserId"
      FROM "OAuthCredentials";
Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "ef_temp_OAuthCredentials" ("OAuthCredentialId", "AccessToken", "DateCreatedUtc", "DateExpiresUtc", "DateModifiedUtc", "Ip", "Provider", "RefreshToken", "UserId")
SELECT "OAuthCredentialId", "AccessToken", "DateCreatedUtc", "DateExpiresUtc", "DateModifiedUtc", "Ip", "Provider", "RefreshToken", "UserId"
FROM "OAuthCredentials";
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 20: 'datatype mismatch'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
SQLite Error 20: 'datatype mismatch'.
```

**Comment by bricelam** [comment]
In SQLite, you need to use `CURRENT_TIMESTAMP` instead of `datetime('now')` inside DEFAULT constraints. In other words, it would fail the same inside of a CREATE TABLE statement.

**Comment by ChaosEngine** [comment]
> In SQLite, you need to use `CURRENT_TIMESTAMP` instead of `datetime('now')` inside DEFAULT constraints. In other words, it would fail the same inside of a CREATE TABLE statement.

I do not think this has anything to do with `CURRENT_TIMESTAMP` but limitation of Sqlite's `ALTER TABLE`:

_The new column may take any of the forms permissible in a CREATE TABLE statement, with the following restrictions:_
- _The column may not have a PRIMARY KEY or UNIQUE constraint._
- _The column may not have a default value of CURRENT_TIME, CURRENT_DATE, CURRENT_TIMESTAMP, or an expression in parentheses._

I've tried to generate migration for timestamp/datetime/rowversion (byte[]) with regular EF core methods and I failed when applying this new migration to existing table because here is no way we can default value column with generated current datetime, timespan.
Maybe trigger(s) would do but this could be an overkill for some

**Comment by Nekzuris** [comment]
> I do not think this has anything to do with `CURRENT_TIMESTAMP` but [limitation of Sqlite's](https://www.sqlite.org/lang_altertable.html) `ALTER TABLE`:

I agree.

Also column like `updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` don't work.
The `ON UPDATE` apparently isn't supported.

**Comment by wldevries** [comment]
The standard SQLite way around this is to create new table, copy entries over, delete the old table and rename the new table.

https://web.archive.org/web/20200206070252/http://sqlite.1065341.n5.nabble.com/Can-t-insert-timestamp-field-with-value-CURRENT-TIME-td42729.html
