### ISSUE TITLE
Enum value entity framework considers the default value is 0

### ISSUE THREAD

**Issue by safaairaq100** [dotnet/efcore#30661]
hello, 
If I set the value in model LeftThumb (0) the value is saved in the database RightIndexFinger (6) because the entity framework considers the default value is 0 so the value will be RightIndexFinger (6) in (_.HasDefaultValue(Fingers.RightIndexFinger_)).
The issue was solved by setting LeftThumb=1 but is this issue or its normal behavior?
_EntityFramework6 c# .netcore_

 
    ` public enum Fingers
    {
        LeftThumb,
        LeftIndexFinger,
        LeftMiddle,
        LeftRingFinger,
        LeftPinky,
        RightThumb,
        RightIndexFinger,
        RightMiddle,
        RightRingFinger,
        RightPinky
    }
    public class EmployeeFingerPrint
    {
        public Guid EmployeeFingerPrintGuid { set; get; }
        public Guid EmployeeGuid { set; get; }
        public Fingers FingerNumber { set; get; }
    }
    
    public class EmployeeFingerPrintConfiguration : IEntityTypeConfiguration<EmployeeFingerPrint>
    {
        public void Configure(EntityTypeBuilder<EmployeeFingerPrint> builder)
        {
            builder.ToTable("EmployeeFingerPrint").HasKey(k => k.EmployeeFingerPrintGuid);

            builder.Property(p => p.FingerNumber).HasColumnType("tinyint")
                .HasDefaultValue(Fingers.RightIndexFinger).IsRequired();
       }
    }`

**Comment by ajcvickers** [comment]
Covered by #701 and other related issues.
