### ISSUE TITLE
miss the command   in beta7 ??   dnx  ef migrations apply   

### ISSUE THREAD

**Issue by lovemory** [dotnet/efcore#3066]
dnx ef migrations --help

Usage: ef migrations [options] [command]

Options:
  -?|-h|--help  Show help information

Commands:
  add     Add a new migration
  list    List the migrations
  remove  Remove the last migration
  script  Generate a SQL script from migrations

Use "migrations [command] --help" for more information about a command.

**Comment by bricelam** [comment]
It [got renamed](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes---July-23,-2015#nugetdnx-commands) to `dnx ef database update`.
