### ISSUE TITLE
SqlServerCompact EFCore Model Generation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30675]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SqlServerCompact-EFCore-Model-Generation/10331100)._

---
I want to generate a EF Model (under . NET6) from a SQLServerCompact file.

Using Scaffold-DbContext command (see below) I receive an error:

Method ‘Create’ in type ‘EFCore.SqlCe.Scaffolding.Internal.SqlCeDatabaseModelFactory’ from assembly ‘EntityFrameworkCore.SqlServerCompact40, Version=2.2.0.0, Culture=neutral, PublicKeyToken=9af395b34ac99006’ does not have an implementation.

Scaffold-DbContext -Connection “Data Source= C:\\temp\\TestModelEFCore\\TestModelEFCore\\dbsqlcompact\\gsdata.sdf;” -Provider EntityFrameworkCore.SqlServerCompact40 -OutputDir dbsqlcompact/Entities -ContextDir DatabaseModel -Context MyContext -UseDatabaseNames -f -Verbose

Any suggestion?

thank you  
Gianluca

---
#### Feedback Bot on 4/6/2023, 04:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
SQL Server Compact is not supported by any supported version of EF Core.
