### ISSUE TITLE
SQLite `Take` in Combination with `OrderBy` behaves differently to other providers

### ISSUE THREAD

**Issue by DanielHabenicht** [dotnet/efcore#30676]
The `Take()` function in combination with `OrderBy()` with the SqliteProvider does not produce the same results as other DBMS.
Possibly because of [Sqlite Optimization](https://www.sqlite.org/optoverview.html).

My expectation would be that they behave the same. 

```C#
actionGroupRepo
    .GetAll()
    // Yes, the Take before the OrderBy is not "right", but that's what was introducing the bug.
    .Take(10)
    .OrderBy(c => c.ExecPlannedFor).ToQueryString()
```

It's producing the following SQL: 
```sql
.param set @__p_0 10

SELECT "t"."Id", "t"."ActionGroupType", "t"."CreatedAt", "t"."CreatedBy", "t"."DelayType", "t"."Description", "t"."ExecPlannedFor", "t"."IsProcessed", "t"."IsProcessing", "t"."ModifiedAt", "t"."ModifiedBy", "t"."RouterId", "t"."WorkerHostName", "t"."WorkerProcessingState", "t"."WorkerRequestState"
FROM (
    SELECT "a"."Id", "a"."ActionGroupType", "a"."CreatedAt", "a"."CreatedBy", "a"."DelayType", "a"."Description", "a"."ExecPlannedFor", "a"."IsProcessed", "a"."IsProcessing", "a"."ModifiedAt", "a"."ModifiedBy", "a"."RouterId", "a"."WorkerHostName", "a"."WorkerProcessingState", "a"."WorkerRequestState"
    FROM "ActionGroup" AS "a"
    LIMIT @__p_0
) AS "t"
ORDER BY "t"."ExecPlannedFor"
```
Which can be shortened to this example: http://sqlfiddle.com/#!5/d13ac/1/0

![image](https://user-images.githubusercontent.com/13590797/231458177-4f07b5bc-e15f-4515-99f3-6545870fc8cc.png)

As can be seen the `LIMIT` is applied after the `ORDER BY` (although it is stated in the subquery). 
The expected result would be `2 3 9`, as validated by other DBMS ([MySQL](http://sqlfiddle.com/#!9/d13ace/1/0), [pSQL](http://sqlfiddle.com/#!17/d13ace/1/0))

## Fix

In order for SQLite to take the first rows one has to include `OFFSET 0`

![image](https://user-images.githubusercontent.com/13590797/231458817-2c8fc003-ef5f-47e6-946f-e3c916e83cb9.png)

http://sqlfiddle.com/#!5/d13ac/10/0

This probably has to be applied everywhere where `Skip` is not called. 

### Include version information

Microsoft.Data.Sqlite version: 6.0.1
Target framework:  .NET 6.0
Operating system: Windows 10

## Remarks

For SQLite the following code change thus produces the same result: 
```c#
actionGroupRepo
    .GetAll()
    .OrderBy(c => c.ExecPlannedFor).ToQueryString()
    .Take(10)
```

```sql
.param set @__p_0 10

SELECT "a"."Id", "a"."ActionGroupType", "a"."CreatedAt", "a"."CreatedBy", "a"."DelayType", "a"."Description", "a"."ExecPlannedFor", "a"."IsProcessed", "a"."IsProcessing", "a"."ModifiedAt", "a"."ModifiedBy", "a"."RouterId", "a"."WorkerHostName", "a"."WorkerProcessingState", "a"."WorkerRequestState"
FROM "ActionGroup" AS "a"
ORDER BY "a"."ExecPlannedFor"
LIMIT @__p_0
```
Which can be shortened to this example: http://sqlfiddle.com/#!5/d13ac/30/0
![image](https://user-images.githubusercontent.com/13590797/231458353-bbf01a02-24bf-43d7-a797-968ba1b3d8be.png)

Now the results are matching with the other DBMS ([MySql](http://sqlfiddle.com/#!9/d13ace/2/0), [pSQL](http://sqlfiddle.com/#!17/d13ace/2/0))

**Comment by roji** [comment]
Since OrderBy is missing, there is no guarantee for the order of the returned rows, regardless of whether you add `OFFSET 0` or not; even if it may seem to fix the issue in your particular test, there's no guarantee that it consistently does so, and various factors (e.g. whether an index exists or not) may cause this to behave differently.

To summarize, if your query uses Skip/Take without an OrderBy, its results are non-deterministic, and it therefore makes sense for different providers to return different results; EF emits a warning for such queries.

**Comment by DanielHabenicht** [comment]
Yes, I do understand that this is the underlying issue that's why I included that the initial use of Take before the `OrderBy` is not really a valid usecase. 

Still, I think that the providers should behave the same. 
The Sqlite Query returns the Ordered results, although it should return the selected non-deterministic rows in an order.

**Comment by DanielHabenicht** [comment]
Also, I haven't tested it yet, but we never saw the `RowLimitingOperationWithoutOrderByWarning`. Maybe because we still used the `OrderBy` - just afterwards?

**Comment by roji** [comment]
> Still, I think that the providers should behave the same.
> The Sqlite Query returns the Ordered results, although it should return the selected non-deterministic rows in an order.

Why? The whole point here is that the results are non-deterministic, so it's perfectly valid for the database to return the rows in whatever order it wants. That means the ordering can vary both across providers, and even when using the same provider, depending on the data in the table, indexes or any other factor. If you apply a Take over such an unordered set, you effectively get X random rows. You could even get a different answer if you execute the same query twice on the same provider.
