### ISSUE TITLE
Get ConnectionString in OnModelCreating returns error after the version of 7.0.0-preview.7.22376.2

### ISSUE THREAD

**Issue by ChesterChuTw** [dotnet/efcore#30670]
MyCode
```
using (var context = new MyContext(new DbContextOptionsBuilder<MyContext>().UseSqlServer(connectionString).Options))
{
	return context.Database.CanConnect().ToString().ToLower();
}
```
```
public partial class MyContext : DbContext
{
	partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
	{
		if ((this.Database.GetDbConnection().ConnectionString ?? "").Contains("Azure")) # Error at this line
		{
			modelBuilder.HasDatabaseMaxSize("2 GB");
			modelBuilder.HasServiceTier("Basic");
			modelBuilder.HasPerformanceLevel("Basic");
			modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");
		}
	}
}
```

Error:
```
An attempt was made to use the model while it was being created. A DbContext instance cannot be used inside 'OnModelCreating' in any way that makes use of the model that is being created.
```
It will work before version 7.0.0-preview.7.22376.2 of ef core , but after that the above error message will be responsed.

What's the correct way to get `ConnectionString` in `OnModelCreating` ?

**Comment by ajcvickers** [comment]
@ChesterChuTw If this worked in early previews of EF7, then it was only be accident. The exception is thrown by every released version of EF Core from at least 3.1 to 7.

If you need the connection string as part of model building, then it will need to be passed to or obtained by the context in some way that it can be accessed without creating the actual DbConnection. For example, by reading it directly from config. Keep in mind that the model is only built once and then cached, so if the connection string is different for different context instances, then the model will not reflect this.

**Comment by ChesterChuTw** [comment]
In our context, we need to initialize a db connect using the connect string that saved in database, and use the connectstring that is returned by `OnModelCreating`, on top of that, check if it is a connect string that connect to Azure SQL Server.

We have thought to use some cached storage to achieve this, but it would have some problems when we work in a multi-thread situation.

Therefore, is there any idea to achieve the same goal or deal with this problem?
We have used version 6 of EFCore also, and it can get the connection string as expected, but not working after `7.0.0-preview.7.22376.2`

**Comment by ajcvickers** [comment]
> We have used version 6 of EFCore also, and it can get the connection string as expected, 

I tested your code on EF Core 6 and it throws just as it does on 7. If you're not seeing this, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

> Initialize a db connect using the connect string that saved in database

You will have to use some other mechanism to get the string out of the database. EF Core can't access the database until the context is initialized, which requires the model to be built.
