### ISSUE TITLE
Visual studio 2019 Professional  16.11.25

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30672]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-2019-Professional--16112/10313593)._

---

Entity Framework 6 -> Generate views information: **A constructible type deriving from DbContext could not be found in the selected file.**  
File is: **Stanowisko.cs:**
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace KartaUprCoreRazor.Models
{
    public class Stanowisko
    {
        public int Id { get; set; }

        [StringLength(6)] //kier, prac
        public string Symbol { get; set; }

        [StringLength(70, MinimumLength = 4)] //kierownik, pracownik
        public string Nazwa { get; set; }
    }
}
**AplicationDbContext.cs:**
public class ApplicationDbContext : IdentityDbContext
    {
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public ApplicationDbContext(DbContextOptions options)
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        : base(options)
        {
        }
        public DbSet Contact { get; set; }
        public DbSet Stanowisko { get; set; }        
    }

**Installed extensions:**
Microsof.EntityFrameworkCore v. 5.0.17
Etnity Framework 6 Power Tools Community Edition

---
#### Feedback Bot on 3/17/2023, 08:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
EF Core 5.0 is out-of-support. Please update to EF Core 6 or later.
