### ISSUE TITLE
Use DbConnection.GetSchema for RevEng?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3068]
Am looking into RevEng for Npgsql, and had a quick question - is there any particular reason not to use `DbConnection.GetSchema` rather then (re-)embed metadata queries in the RevEng provider? I'm not sure how widely implemented this feature is (or how "standardized" its results are), but at the very least it could be an optional implementation base class that would allow RevEng to be implemented with relatively little work?

**Comment by roji** [comment]
A related, alternative idea would be to provide a default implementation for providers who implement the standard information_schema.

**Comment by roji** [comment]
The second idea, using information_schema, would probably not work simply because querying across different databases is different (e.g. quoting in SqlServer vs. PostgreSQL)

**Comment by ErikEJ** [comment]
@roji GetSchema is available in ADO.NET in .NET Core. And the second idea will just not work.

**Comment by bricelam** [comment]
The RevEng contract should be loose enough to allow providers to retrieve schema information however they want--`DbConnection.GetSchema`, `INFORMATION_SCHEMA`, etc. The problem with these "standards" is that they aren't very standard across providers :smile:, and even if they were, they aren't complete enough for EF (e.g. no indexes).

**Comment by roji** [comment]
Sure, I wasn't thinking about constraining the API or anything, just providing a default implementation that would work where `DbConnection.GetSchema` does work in a standard way. I admit I know nothing about how standard it is though.

Feel free to close if this approach doesn't seem helpful (or if GetSchema is actually being removed from CoreCLR, as opposed to just not being there yet).

**Comment by roji** [comment]
Note new discussion on standardized replacement API for `DbConnection.GetSchema` and `DbDataReader.GetSchemaTable`: https://github.com/dotnet/corefx/issues/3423
