### ISSUE TITLE
Extremely large memory consumption in "ToListAsync()" when using cancellation token

### ISSUE THREAD

**Issue by Stocki916** [dotnet/efcore#30691]
Dear community,

i faced a memory issue and a big difference in selecting data from a microsoft sql database when using an async "ToListAsync()" with and without a cancellation token.
Im selecting "ids" of type "bigint / long" from a table in the database by using this statement which returns 140 mio ids:

`        return await _context.Items.AsNoTracking().Select(s => s.Id.GetValueOrDefault(0)).Distinct().ToListAsync();`

The memory consumption of the app is round about 2 GB of memory.

The largest object in memory monitor is the list with "Ids". That's clear so far :-)

If i modify the statement and pass a cancellation token to the "ToListAsync(ct)", then the memory consumption increases to > 15 GB

`        return await _context.Items.AsNoTracking().Select(s => s.Id.GetValueOrDefault(0)).Distinct().ToListAsync(ct);`

Now there are really large "CancellationTokenSource" and "CallBacknode" objects, which cause the high memory usage:

![InkedRavenDataDistribution_WithCancellationToken_LI](https://user-images.githubusercontent.com/60972798/232051824-32ce266f-0376-4172-b1c3-0f4f7d74fa43.jpg)

In general i could just remove the cancellation token but i would like to understand how i can still use a cancellation token and prevent such a large memory consumption.

**Comment by ErikEJ** [comment]
@roji Any plans to adopt 5.0.2 for EF Core 7.0.x ?

**Comment by roji** [comment]
@ErikEJ yeah, I think we'll be doing that - though it's probably wise to wait a little bit to see that 5.0.2 is stable...

**Comment by ErikEJ** [comment]
@roji agree, issue is that is will have small adoption now that higer versions are out (5.1.x)
