### ISSUE TITLE
RevEng: Reuse SqlServerRelationalTypeMapper

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3069]
The RevEng provider's `SqlServerTypeMapping` seems to be redundant, reproducing information that's already available in `SqlServerTypeMapper` - any reason for not using the latter?

**Comment by roji** [comment]
Apologies, have noticed that `RelationalTypeMapping` doesn't contain the CLR type that corresponds to the database type. However, that information could be added to it, concentrating all type mapping information in one place...

**Comment by ErikEJ** [comment]
@roji I think this is already logged here #1671

**Comment by roji** [comment]
Thanks @ErikEJ, once again I don't search well enough before opening an issue...
