### ISSUE TITLE
Autogenerated ids are not populated to EntityEntry

### ISSUE THREAD

**Issue by daze99** [dotnet/efcore#30717]
I have a function in a service which basically adds an entity to the DB. Notice, that I do not call `_dbContext.SaveChanges()` because this is done outside this service.

```
public class MyEntity
{
    public int Id { get; set; }
}

public class MyService
{
    public override int? Create(MyEntity entity)
    {
        var created = _dbContext.Set<MyEntity>().Add(entity);

        return created.Entity?.Id;
    }
}
```

Since I updated to EF 6.0.13 the `Id` of my entity is always 0. This used to work in an older 6.0.* release.

Only autogenerated properties of type `int` have this issue.

This case here still works as expected:

```
public class MyOtherEntity
{
    public Guid Id { get; set; }
}

public class MyOtherService
{
    public override Guid? Create(MyOtherEntity entity)
    {
        var created = _dbContext.Set<MyOtherEntity>().Add(entity);

        return created.Entity?.Id;
    }
}
```

EF Core version: 6.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0

**Comment by ajcvickers** [comment]
@daze99 This behavior [hasn't changed since EF Core 3.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#tkv). If you are seeing otherwise, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing and indicate which version it was working in so that we can investigate.

**Comment by daze99** [comment]
You are right. Why is `int` handled differently than `Guid`?

**Comment by ajcvickers** [comment]
@daze99 Int properties get temporary values until the row is inserted into the database and the real value is generated. Guids, by default, are generated on the client.
