### ISSUE TITLE
EFCore allow binary serialisation of built model to speed up subsequent restarts

### ISSUE THREAD

**Issue by nettashamir-allocate** [dotnet/efcore#30716]
Our model is very large and complex and takes about 25s to build. As it stands, the model compilation mechanism provided fails for us as it does not seem to exactly replicate the runtime model building process and I get dependency issues coming up when I try the compilation that I do not get at normal runtime.

Our main pain point is during troubleshooting with unit tests. This involves running unit tests over and over and each run (even for a tests that itself only takes milliseconds) incurs a wait of around 25s to build the model.

Having looked at [EF Core save built model for subsequent startup #26038](https://github.com/dotnet/efcore/issues/26038), I wonder whether a simple alternative solution would be to just allow binary serialisation of the built model? This would only require adding the Serializable interface to all classes involved in the final model object tree. Might that be possible?

**Comment by roji** [comment]
> Our model is very large and complex and takes about 25s to build. As it stands, the model compilation mechanism provided fails for us as it does not seem to exactly replicate the runtime model building process and I get dependency issues coming up when I try the compilation that I do not get at normal runtime.

If there's a bug somewhere in building the compiled model, that's something we need to investigate and fix - can you please try to put together a repro for this?

Other than that, binary serialization is more or less deprecated in .NET; I'm also not sure sure that this would provide a meaningful speed-up compared to the code we generate, which should build the model with little overhead... I'd advise concentrating on why your model takes 25s to build - approximately how many entities/properties/relationships are we talking about here?

**Comment by nettashamir-allocate** [comment]
@roji 
>  - approximately how many entities/properties/relationships are we talking about here?

We have about 630 entities with about 3000 properties and 1200 associations between them. 

We are also using some extensions (Neinlinq and Projectables) which were causing additional errors in the compilation. 
I can try to reproduce the errors with a cut-down model and see if I can narrow down the causes.

**Comment by roji** [comment]
Great, thanks. Note that we're interested in two things here: the failure/error in model compilation, and also why your model takes so long to build.. The first would require some sort of repro (ideally as a minimal, runnable code sample), whereas the second simply means sending us your model so that we can profile what's taking so long. You can do that by sending an email to the address listed on my Github profile.

**Comment by ajcvickers** [comment]
Following up offline.
