### ISSUE TITLE
I get different results when registering the concurrency update: one throws an exception, the other doesn't

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#30720]
I have a `DbContext` which is build to support different database providers. I also want to incorporate concurrency tokens to this `DbContext`, but because concurrency checks differs by the the database provider I use code within the `OnModelCreating`. This works for SQLServer, but I have problems with other database providers. 

I have build a SQLite example shown below where the `Customer` entity uses the normal (manual) way to add a concurrency checks, and another where the `OtherCustomer` entity is added a via `modelBuilder.Model.GetEntityTypes()` (see code below).

_NOTE: I have a similar problem with Postgres, but I haven't looked into this in the same level as with the SQLite example. I only note this as there may be an overall problem that I am doing, although [SQLServer config](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions.BaseCode/DataLayer/EfCode/AuthPermissionsDbContext.cs#L70-L81) works._

There are two tests and the results are:

- `Customer` entity uses the normal (manual) - works as expected, i.e. is throws `DbUpdateConcurrencyException` event
- `OtherCustomer` entity via `Model` - this fails, with no `DbUpdateConcurrencyException` thrown.

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using TestSupport.EfHelpers;
using Xunit;
using Xunit.Abstractions;
using Xunit.Extensions.AssertExtensions;

namespace Test;

public class TestSqliteConcurrency
{
    private readonly ITestOutputHelper _output;

    public TestSqliteConcurrency(ITestOutputHelper output)
    {
        _output = output;
    }


    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Version { get; set; }
    }

    public class OtherCustomer
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class TestConcurrencyDbContext : DbContext
    {
        public TestConcurrencyDbContext(DbContextOptions<TestConcurrencyDbContext> options)
            : base(options) {}

        public DbSet<Customer> Customers { get; set; }

        public DbSet<OtherCustomer> OtherCustomers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<Customer>()
                .Property(c => c.Version)
                .HasDefaultValue(0)
                .IsRowVersion();

            var entityType = modelBuilder.Model.GetEntityTypes()
                .Single(x => x.Name.EndsWith("OtherCustomer"));
            entityType.AddProperty("Version", typeof(int));
            entityType.FindProperty("Version")
                .ValueGenerated = ValueGenerated.OnAddOrUpdate;
            entityType.FindProperty("Version")
                .SetDefaultValue(0);
            entityType.FindProperty("Version")
                .IsConcurrencyToken = true;
        }
    }

    //This passes.
    [Fact]
    public void TestSqliteAuthPermissionsDbContext_ConcurrencyTokens_Customers()
    {
        //SETUP
        var options = SqliteInMemory.CreateOptionsWithLogTo<TestConcurrencyDbContext>(_output.WriteLine);
        var context = new TestConcurrencyDbContext(options);
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        context.Database.ExecuteSqlRaw(@"CREATE TRIGGER UpdateCustomerVersion
AFTER UPDATE ON Customers
BEGIN
    UPDATE Customers
    SET Version = Version + 1
    WHERE rowid = NEW.rowid;
END;
");

        var initial = new Customer{Name = "Initial"};
        context.Add(initial);
        context.SaveChanges();
        context.ChangeTracker.Clear();

        //ATTEMPT
        var entity = context.Customers.Single();
        context.Database.ExecuteSqlInterpolated($"UPDATE Customers SET Name = 'XYZ'");
        entity.Name = "ABC";
        try
        {
            entity.Name = "ABC";
            context.SaveChanges();
        }
        catch (DbUpdateConcurrencyException e)
        {
            e.Message.ShouldStartWith("The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded");
            return;
        }

        //VERIFY
        false.ShouldBeTrue("The concurrency event didn't trigger.");
    }

    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THIS FAILS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    [Fact]
    public void TestSqliteAuthPermissionsDbContext_ConcurrencyTokens_OtherCustomers()
    {
        //SETUP
        var options = SqliteInMemory.CreateOptionsWithLogTo<TestConcurrencyDbContext>(_output.WriteLine);
        var context = new TestConcurrencyDbContext(options);
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        context.Database.ExecuteSqlRaw(@"CREATE TRIGGER UpdateOtherCustomerVersion
AFTER UPDATE ON OtherCustomers
BEGIN
    UPDATE OtherCustomers
    SET Version = Version + 1
    WHERE rowid = NEW.rowid;
END;
");

        var initial = new OtherCustomer { Name = "Initial" };
        context.Add(initial);
        context.SaveChanges();
        context.ChangeTracker.Clear();

        //ATTEMPT
        var entity = context.OtherCustomers.Single();
        context.Database.ExecuteSqlInterpolated($"UPDATE Customers SET Name = 'XYZ'");
        entity.Name = "ABC";
        try
        {
            entity.Name = "ABC";
            context.SaveChanges();
        }
        catch (DbUpdateConcurrencyException e)
        {
            e.Message.ShouldStartWith("The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded");
            return;
        }

        //VERIFY
        false.ShouldBeTrue("The concurrency event didn't trigger.");
    }
}
```

### Include provider and version information

EF Core version: EntityFrameworkCore.Exceptions.Sqlite" Version="6.0.3"
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: windows
IDE: Visual Studio 2022 7.5.2

**Comment by ajcvickers** [comment]
I @JonPSmith, good to hear from you. :-) The problem is that in the second test you are updating the `Customers` table rather than the `OtherCustomers` table:

```C#
context.Database.ExecuteSqlInterpolated($"UPDATE Customers SET Name = 'XYZ'");
```

Also, personally, I would use the model builder API to create the shadow concurrency token property, although this doesn't have a functional difference:

```C#
modelBuilder
    .Entity<OtherCustomer>()
    .Property<int>("Version")
    .HasDefaultValue(0)
    .IsConcurrencyToken()
    .ValueGeneratedOnAddOrUpdate();
```

**Comment by JonPSmith** [comment]
Doh! I do have a problem, but the code is complex so I build a simple version to send to you, but I got it wrong! Sorry for wasting your time. I will close this issue but if I can get a failing version I'll open it again.

PS. You said that I should the normal model builder code, but I can't do that because each database providers have different concurrency token, for instance:

- SQLServer: `ColumnType("ROWVERSION")`
- Postgres: `ColumnType("xid")`
- Sqlite: `int`

Am I missing something here?

**Comment by roji** [comment]
You should be able to look at DbContext.Database.ProviderName to vary model configuration based on the provider being used; you could have a utility function that configures an automatic concurrency token.

**Comment by JonPSmith** [comment]
Hi @roji,

My [AuthPermissions.AspNetCore](https://github.com/JonPSmith/AuthPermissions.AspNetCore) library (AuthP) has a [AuthPermissionsDbContext](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions.BaseCode/DataLayer/EfCode/AuthPermissionsDbContext.cs) that supports both SQL Server and Postgres. Note that SQL Server and Postgres have different concurrency token approaches.

To implement this I have entity classes without concurrency tokens and I add concurrency tokens  with in the `OnModelCreating` (see below). If you see any problems my approach, then let me know.

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.HasDefaultSchema("authp");
    
    //Add concurrency token to every entity 
    foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())
    {
        if (Database.IsSqlServer())
        {
            entityType.AddProperty("ConcurrencyToken", typeof(byte[]))
                .SetColumnType("ROWVERSION");
            entityType.FindProperty("ConcurrencyToken")
                .ValueGenerated = ValueGenerated.OnAddOrUpdate;
            entityType.FindProperty("ConcurrencyToken")
                .IsConcurrencyToken = true;
        }
        else if (Database.IsNpgsql())
        {
            //see https://www.npgsql.org/efcore/modeling/concurrency.html
            //and https://github.com/npgsql/efcore.pg/issues/19#issuecomment-253346255
            entityType.AddProperty("xmin", typeof(uint))
                .SetColumnType("xid");
            entityType.FindProperty("xmin")
                .ValueGenerated = ValueGenerated.OnAddOrUpdate;
            entityType.FindProperty("xmin")
                .IsConcurrencyToken = true;
        }
    }

    //This allows a developer to add a custom configuration to this DbContext
    //Typical use is to set up the concurrency tokens parts when using a custom database type
    _customConfiguration?.ApplyCustomConfiguration(modelBuilder);

//... rest of code left out
```

I have two requests to support other database providers and I am adding code to allow a developer add a different database provider - currently using Sqlite.  I have some problems, but I haven't got to bottom of the problem yet. My incorrect code (Doh!) has has shown that it can work. I will keep digging.

**Comment by roji** [comment]
@JonPSmith yeah, that approach look like it should work. FYI rather than configuring via the low-level metadata APIs, you can build an EntityTypeBuilder over your IEntityType, and then use the regular, higher-level APIs to configure things as usual:

```c#
new EntityTypeBuilder(entityType).Property<byte[]>("ConcurrencyToken").IsRowVersion();
```

**Comment by JonPSmith** [comment]
@roji, thanks for that tip. I'll try it out
