### ISSUE TITLE
`Remove` together with `SaveChangesAsync` didn't delete entities.

### ISSUE THREAD

**Issue by tautvydasversockas** [dotnet/efcore#30723]
## Description

Today I observed a case when calling `Remove` and then `SaveChangesAsync` methods succeeded, but the data was never deleted from the database. The code was executed ~20 times and it worked as expected ~19 times, it just didn't work this one time. In other words, I can't replicate the issue. The code runs on a dedicated environment and I'm sure it was not changed in between the executions.

### Code 

This is what the code looks like. Mind you, I could not replicate the issue after that single occurrence (running the code both from a dedicated environment and from my local machine).
 
#### Entities & their configurations

```C#
public class Parent
{
    public Guid Id { get; set; }
    public List<Child> Children { get; set; }
}

public class Child
{
    public Guid Id { get; set; }
    public Guid ParentId { get; set; }
    public bool IsProcessed { get; set; }
}

public class ParentConfig : IEntityTypeConfiguration<Parent>
{
    public void Configure(EntityTypeBuilder<Parent> builder)
    {
        builder
            .HasKey(p => p.Id);
            
        builder
            .HasMany(p => p.Children)
            .WithOne()
            .HasForeignKey(c => c.ParentId);
    }
}

public class ChildConfig : IEntityTypeConfiguration<Child>
{
    public void Configure(EntityTypeBuilder<Child> builder)
    {
        builder
            .HasKey(c => c.Id);
    }
}
```

#### DbContext

```C#
public class ServiceDbContext : DbContext
{
    private readonly string _connectionString;

    public ServiceDbContext(string connectionString)
    {
        _connectionString = connectionString;
    }

    public DbSet<Parent> Parents => Set<Parent>();

    public DbSet<Child> Children => Set<Child>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(ServiceDbContext).Assembly);
    }
}
```

#### Application code

```C#
public record ProcessChildRequest(Guid ChildId);

public class RequestHandler 
{
    public readonly ServiceDbContext _dbContext;

    public RequestHandler(ServiceDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task Handle(ProcessChildRequest request, CancellationToken token)
    {
        var parent = await _dbContext.Parents
            .Include(p => p.Children)
            .FirstAsync(p => p.Children.Any(c => c.Id == request.ChildId), token);

        var child = parent.Children.First(c => c.Id == request.ChildId);
        child.IsProcessed = true;

        if (parent.Children.All(c => c.IsProcessed))
            _dbContext.Remove(parent);

        await _dbContext.SaveChangesAsync(token);
    }
}
```

##### Parents

Id 
------------- |
499635F8-0A57-45ED-9FF2-5987B9F97D68

##### Children 

Id | ParentId | IsProcessed 
------------- | ------------- | -------------
CC42C28F-5261-4ECC-B5A9-0E7C9F8E65EF  | 499635F8-0A57-45ED-9FF2-5987B9F97D68 | 1
7A732A2B-2CB8-4BC0-B5E4-34607B86F48C  | 499635F8-0A57-45ED-9FF2-5987B9F97D68 | 0

##### Parents

Id 
------------- |
499635F8-0A57-45ED-9FF2-5987B9F97D68

##### Children 

Id | ParentId | IsProcessed 
------------- | ------------- | -------------
CC42C28F-5261-4ECC-B5A9-0E7C9F8E65EF  | 499635F8-0A57-45ED-9FF2-5987B9F97D68 | 1
7A732A2B-2CB8-4BC0-B5E4-34607B86F48C  | 499635F8-0A57-45ED-9FF2-5987B9F97D68 | 1

It's a bit weird, because the `IsProcessed` was updated, but no entities were deleted.

### Additional Information

EF Core version: 7.0.5
Database provider:  Microsoft.EntityFrameworkCore.SqlServer 
Target framework: .NET 7
Operating system: Debian GNU/Linux 11 (bullseye)
Sql server: Windows Server 2019 Standard (10.0)

**Comment by ajcvickers** [comment]
@tautvydasversockas The only thing that stands out is that the `Handle` method could be called concurrently by multiple threads, which would then result in the `DbContext` being used concurrently my multiple threads. `DbContext` is [not thread-safe](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues).
