### ISSUE TITLE
Avoiding duplicate code in Linq Select method and only project the properties I need

### ISSUE THREAD

**Issue by Ogglas** [dotnet/efcore#30726]
I have tried to find an answer to this but not found any. What I want to avoid is duplicate code for a Linq Select method as the title says and only project the properties I need for querying efficiently via EF Core.

https://learn.microsoft.com/en-us/ef/core/performance/efficient-querying#project-only-properties-you-need

ExternalLinkDto class:
		
	public class ExternalLinkDto : EntityDto
    {
        public int Id { get; set; }

        ...

        public static Expression<Func<ExternalLink, ExternalLinkDto>> Conversion = externalLink =>
                new ExternalLinkDto()
                {
                    Id = externalLink.Id,
                    Link = externalLink.Link,
                    LinkType = externalLink.LinkType,
                    LinkText = externalLink.LinkText
                };
    }

The following code works but I do not like the code duplication:

	public static IQueryable<ProductSummaryDtoHelper> QueryProductSummary(this IQueryable<Product> query)
    {
        var summary = query.Select(product => new ProductSummaryDtoHelper()
        {
            UnresolvedThreatAndCountermeasures =
                product.ThreatAndCountermeasures.Where(tac => !tac.NotApplicable && !(tac.Verified && tac.Implemented)).Select(
                    vuln => new ProductSummaryVulnerabilityDtoHelper()
                    {
                        ExternalLinksHelper = vuln.ExternalLinks.Select(externalLink => new ExternalLinkDto()
                        {
                            Id = externalLink.Id,
                            Link = externalLink.Link,
                            LinkType = externalLink.LinkType,
                            LinkText = externalLink.LinkText
                        }),
                        ExternalLinksHelperThreat = vuln.Threat.ExternalLinks.Select(externalLink => new ExternalLinkDto()
                        {
                            Id = externalLink.Id,
                            Link = externalLink.Link,
                            LinkType = externalLink.LinkType,
                            LinkText = externalLink.LinkText
                        }),
                        ExternalLinksHelperThreatFork = vuln.Threat.Fork.ExternalLinks.Select(externalLink => new ExternalLinkDto()
                        {
                            Id = externalLink.Id,
                            Link = externalLink.Link,
                            LinkType = externalLink.LinkType,
                            LinkText = externalLink.LinkText
                        })
                    })
        });

        return summary;
    }

This results in the following SQL sent:

	SELECT [t0].[Id], [t1].[Id] AS [Id0], [t3].[Id] AS [Id1], [e].[Id] AS [Id2], [e].[Link], [e].[LinkType], [e].[LinkText], [e0].[Id] AS [Id3], [e0].[Link] AS [Link0], [e0].[LinkType] AS [LinkType0], [e0].[LinkText] AS [LinkText0], [e1].[Id] AS [Id4], [e1].[Link] AS [Link1], [e1].[LinkType] AS [LinkType1], [e1].[LinkText] AS [LinkText1], [t0].[ProductId]
      FROM [ThreatAndCountermeasure] AS [t0]
      INNER JOIN [Threats] AS [t1] ON [t0].[ThreatId] = [t1].[Id]
      LEFT JOIN [Threats] AS [t3] ON [t1].[ForkId] = [t3].[Id]
      LEFT JOIN [ExternalLink] AS [e] ON [t0].[Id] = [e].[ThreatAndCountermeasureId]
      LEFT JOIN [ExternalLink] AS [e0] ON [t1].[Id] = [e0].[ThreatId]
      LEFT JOIN [ExternalLink] AS [e1] ON [t3].[Id] = [e1].[ThreatId]
      WHERE [t0].[NotApplicable] = CAST(0 AS bit) AND ([t0].[Verified] = CAST(0 AS bit) OR [t0].[Implemented] = CAST(0 AS bit))

I have tried to create an `Expression<Func<>>` as @JonSkeet suggests.

https://stackoverflow.com/a/34649951/3850405

Final working version looked like this:

    public static IQueryable<ProductSummaryDtoHelper> QueryProductSummary(this IQueryable<Product> query)
    {
        var compiledFunction = ExternalLinkDto.Conversion.Compile();

        var summary = query.Select(product => new ProductSummaryDtoHelper()
        {
            UnresolvedThreatAndCountermeasures =
                product.ThreatAndCountermeasures.Where(tac => !tac.NotApplicable && !(tac.Verified && tac.Implemented)).Select(
                    vuln => new ProductSummaryVulnerabilityDtoHelper()
                    {
                        ExternalLinksHelper = vuln.ExternalLinks.Select(x => compiledFunction(x)),
                        ExternalLinksHelperThreat = vuln.Threat.ExternalLinks.Select(x => compiledFunction(x)),
                        ExternalLinksHelperThreatFork = vuln.Threat.Fork.ExternalLinks.Select(x => compiledFunction(x)),
                    })
        }); ;

        return summary;
    }

SQL generated will pick up every extra field and I do not want that:

    SELECT [t0].[Id], [t1].[Id] AS [Id0], [t3].[Id] AS [Id1], [e].[Id] AS [Id2], [e].[Created], [e].[CreatedById], [e].[Guid], [e].[Link], [e].[LinkText], [e].[LinkType], [e].[PeriodEnd], [e].[PeriodStart], [e].[ProductId], [e].[ThreatAndCountermeasureId], [e].[ThreatId], [e].[Updated], [e].[UpdatedById], [e].[Version], [e0].[Id] AS [Id3], [e0].[Created] AS [Created0], [e0].[CreatedById] AS [CreatedById0], [e0].[Guid] AS [Guid0], [e0].[Link] AS [Link0], [e0].[LinkText] AS [LinkText0], [e0].[LinkType] AS [LinkType0], [e0].[PeriodEnd] AS [PeriodEnd0], [e0].[PeriodStart] AS [PeriodStart0], [e0].[ProductId] AS [ProductId0], [e0].[ThreatAndCountermeasureId] AS [ThreatAndCountermeasureId0], [e0].[ThreatId] AS [ThreatId0], [e0].[Updated] AS [Updated0], [e0].[UpdatedById] AS [UpdatedById0], [e0].[Version] AS [Version0], [e1].[Id] AS [Id4], [e1].[Created] AS [Created1], [e1].[CreatedById] AS [CreatedById1], [e1].[Guid] AS [Guid1], [e1].[Link] AS [Link1], [e1].[LinkText] AS [LinkText1], [e1].[LinkType] AS [LinkType1], [e1].[PeriodEnd] AS [PeriodEnd1], [e1].[PeriodStart] AS [PeriodStart1], [e1].[ProductId] AS [ProductId1], [e1].[ThreatAndCountermeasureId] AS [ThreatAndCountermeasureId1], [e1].[ThreatId] AS [ThreatId1], [e1].[Updated] AS [Updated1], [e1].[UpdatedById] AS [UpdatedById1], [e1].[Version] AS [Version1], [t0].[ProductId] AS [ProductId2]
    FROM [ThreatAndCountermeasure] AS [t0]
    INNER JOIN [Threats] AS [t1] ON [t0].[ThreatId] = [t1].[Id]
    LEFT JOIN [Threats] AS [t3] ON [t1].[ForkId] = [t3].[Id]
    LEFT JOIN [ExternalLink] AS [e] ON [t0].[Id] = [e].[ThreatAndCountermeasureId]
    LEFT JOIN [ExternalLink] AS [e0] ON [t1].[Id] = [e0].[ThreatId]
    LEFT JOIN [ExternalLink] AS [e1] ON [t3].[Id] = [e1].[ThreatId]
    WHERE [t0].[NotApplicable] = CAST(0 AS bit) AND ([t0].[Verified] = CAST(0 AS bit) OR [t0].[Implemented] = CAST(0 AS bit))

If I use `Expression<Func<>>` without Compile I get the following error:

> CS1929
> 'List<ExternalLink>' does not contain a definition for 'Select' and 
> the best extension method overload 
> 'Queryable.Select<ExternalLink, ExternalLinkDto>(IQueryable<ExternalLink>,
>     Expression<Func<ExternalLink, ExternalLinkDto>>)' 
> requires a receiver of type
> 'System.Linq.IQueryable<MyProject.Models.Entities.ExternalLink>':

    public static IQueryable<ProductSummaryDtoHelper> QueryProductSummary(this IQueryable<Product> query)
    {
        var summary = query.Select(product => new ProductSummaryDtoHelper()
        {
            UnresolvedThreatAndCountermeasures =
                product.ThreatAndCountermeasures.Where(tac => !tac.NotApplicable && !(tac.Verified && tac.Implemented)).Select(
                    vuln => new ProductSummaryVulnerabilityDtoHelper()
                    {
                        ExternalLinksHelper = vuln.ExternalLinks.Select(ExternalLinkDto.Conversion),
                        ExternalLinksHelperThreat = vuln.Threat.ExternalLinks.Select(externalLink => new ExternalLinkDto()
                        {
                            Id = externalLink.Id,
                            Link = externalLink.Link,
                            LinkType = externalLink.LinkType,
                            LinkText = externalLink.LinkText
                        }),
                        ExternalLinksHelperThreatFork = vuln.Threat.Fork.ExternalLinks.Select(externalLink => new ExternalLinkDto()
                        {
                            Id = externalLink.Id,
                            Link = externalLink.Link,
                            LinkType = externalLink.LinkType,
                            LinkText = externalLink.LinkText
                        })
                    })
        });

        return summary;
    }

Creating an extension method like this also works:

    public static IQueryable<ProductSummaryDtoHelper> QueryProductSummary(this IQueryable<Product> query)
    {
        var summary = query.Select(product => new ProductSummaryDtoHelper()
        {
            UnresolvedThreatAndCountermeasures =
                product.ThreatAndCountermeasures.Where(tac => !tac.NotApplicable && !(tac.Verified && tac.Implemented)).Select(
                    vuln => new ProductSummaryVulnerabilityDtoHelper()
                    {
                        ExternalLinksHelper = vuln.ExternalLinks.MapToExternalLinkDto(),
                        ExternalLinksHelperThreat = vuln.Threat.ExternalLinks.MapToExternalLinkDto(),
                        ExternalLinksHelperThreatFork = vuln.Threat.Fork.ExternalLinks.MapToExternalLinkDto()
                    })
        });

        return summary;
    }
	
	public static IEnumerable<ExternalLinkDto> MapToExternalLinkDto(this List<ExternalLink> externalLinks)
    {
        var summary = externalLinks.Select(externalLink => new ExternalLinkDto()
        {
            Id = externalLink.Id,
            Link = externalLink.Link,
            LinkType = externalLink.LinkType,
            LinkText = externalLink.LinkText
        });

        return summary;
    }

However SQL generated will pick up every extra field here as well:

    SELECT [t0].[Id], [t1].[Id] AS [Id0], [t3].[Id] AS [Id1], [e].[Id] AS [Id2], [e].[Created], [e].[CreatedById], [e].[Guid], [e].[Link], [e].[LinkText], [e].[LinkType], [e].[PeriodEnd], [e].[PeriodStart], [e].[ProductId], [e].[ThreatAndCountermeasureId], [e].[ThreatId], [e].[Updated], [e].[UpdatedById], [e].[Version], [e0].[Id] AS [Id3], [e0].[Created] AS [Created0], [e0].[CreatedById] AS [CreatedById0], [e0].[Guid] AS [Guid0], [e0].[Link] AS [Link0], [e0].[LinkText] AS [LinkText0], [e0].[LinkType] AS [LinkType0], [e0].[PeriodEnd] AS [PeriodEnd0], [e0].[PeriodStart] AS [PeriodStart0], [e0].[ProductId] AS [ProductId0], [e0].[ThreatAndCountermeasureId] AS [ThreatAndCountermeasureId0], [e0].[ThreatId] AS [ThreatId0], [e0].[Updated] AS [Updated0], [e0].[UpdatedById] AS [UpdatedById0], [e0].[Version] AS [Version0], [e1].[Id] AS [Id4], [e1].[Created] AS [Created1], [e1].[CreatedById] AS [CreatedById1], [e1].[Guid] AS [Guid1], [e1].[Link] AS [Link1], [e1].[LinkText] AS [LinkText1], [e1].[LinkType] AS [LinkType1], [e1].[PeriodEnd] AS [PeriodEnd1], [e1].[PeriodStart] AS [PeriodStart1], [e1].[ProductId] AS [ProductId1], [e1].[ThreatAndCountermeasureId] AS [ThreatAndCountermeasureId1], [e1].[ThreatId] AS [ThreatId1], [e1].[Updated] AS [Updated1], [e1].[UpdatedById] AS [UpdatedById1], [e1].[Version] AS [Version1], [t0].[ProductId] AS [ProductId2]
    FROM [ThreatAndCountermeasure] AS [t0]
    INNER JOIN [Threats] AS [t1] ON [t0].[ThreatId] = [t1].[Id]
    LEFT JOIN [Threats] AS [t3] ON [t1].[ForkId] = [t3].[Id]
    LEFT JOIN [ExternalLink] AS [e] ON [t0].[Id] = [e].[ThreatAndCountermeasureId]
    LEFT JOIN [ExternalLink] AS [e0] ON [t1].[Id] = [e0].[ThreatId]
    LEFT JOIN [ExternalLink] AS [e1] ON [t3].[Id] = [e1].[ThreatId]
    WHERE [t0].[NotApplicable] = CAST(0 AS bit) AND ([t0].[Verified] = CAST(0 AS bit) OR [t0].[Implemented] = CAST(0 AS bit)

I do not want to use a thrid party library like [LINQKit](https://github.com/scottksmith95/LINQKit), [NeinLinq](https://github.com/axelheer/nein-linq) or [DelegateDecompiler](https://github.com/hazzik/DelegateDecompiler).

https://stackoverflow.com/q/66378438/3850405

### Include provider and version information

EF Core version: 7.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0
Operating system: Windows 11 Pro
IDE: Visual Studio 2022 Version 17.5.4

**Comment by maumar** [comment]
@Ogglas can you post a small standalone repro that represents this scenario? It should be possible to write an `Expression<Func>` based helper that would do what you need. Since you get the error, there's something wrong. In order to efficiently investigate, I would like to see the complete scenario.

**Comment by stevendarby** [comment]
@maumar I think the issue is this is being used for navigation property selects within the main select...

I have a minimal repro which I think makes what OP is coming across a bit clearer

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

using var context = new MyDbContext();
context.Database.EnsureDeleted();
context.Database.EnsureCreated();

// Explicit selector for Post Ids
var blogPostIds1 = context.Blogs
    .Select(b => new
    {
        BlogId = b.Id,
        PostIds = b.Posts.Select(p => p.Id)
    })
    .ToList();

// First attempt to use a selector helper. For the below to even compile, Posts would need to be
// IQueryable to accept an Expression selector. But even then, it will fail to execute.
//var blogPostIds2 = context.Blogs
//    .Select(b => new
//    {
//        BlogId = b.Id,
//        PostIds = b.Posts.Select(Helper.Selector)
//    })
//    .ToList();

// As mentioned by OP, compiling the expression allows this code to compile & execute, but it's
// evaluated client-side, bringing back more columns
var compiled = Helper.Selector.Compile();
var blogPostIds3 = context.Blogs
    .Select(b => new
    {
        BlogId = b.Id,
        PostIds = b.Posts.Select(p => compiled(p))
    })
    .ToList();

// Using DbSet with manual foreign key filter instead of navigation property
// It works, but lack of navigation property is a drawback
var blogPostIds4 = context.Blogs
    .Select(b => new
    {
        BlogId = b.Id,
        PostIds = context.Posts.Where(p => p.BlogId == b.Id).Select(Helper.Selector).ToList()
    })
    .ToList();

public static class Helper
{
    public static Expression<Func<Post, int>> Selector
        => x => x.Id;
}

public class MyDbContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Data Source=(LocalDb)\\MSSQLLocalDB;Initial Catalog=PoolDemo;Integrated Security=SSPI;")
            .LogTo(Console.WriteLine, LogLevel.Information);
}

public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
    public IEnumerable<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

**Comment by Ogglas** [comment]
> @Ogglas can you post a small standalone repro that represents this scenario? It should be possible to write an `Expression<Func>` based helper that would do what you need. Since you get the error, there's something wrong. In order to efficiently investigate, I would like to see the complete scenario. 

The example from @stevendarby is exactly what I want to achieve.

**Comment by maumar** [comment]
Ahh, I see. Thanks @stevendarby.

@Ogglas you can make this work by adding `AsQueryable()` call after the Enumerable navigation and before the `Select` method. Using @stevendarby's example, it would look something like this:

```cs
        var blogPostIds2 = context.Blogs
            .Select(b => new
            {
                BlogId = b.Id,
                PostIds = b.Posts.AsQueryable().Select(Helper.Selector).ToList()
            })
            .ToList();
```

this should produce sql with only the necessary columns:

```sql
SELECT [b].[Id], [p].[Id]
FROM [Blogs] AS [b]
LEFT JOIN [Posts] AS [p] ON [b].[Id] = [p].[BlogId]
ORDER BY [b].[Id]
```

**Comment by Ogglas** [comment]
@maumar Sorry I completely missed to answer. Thank you very much, this is exactly what I wanted. :)
