### ISSUE TITLE
Automatically set modified date on each SaveChanges

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/efcore#30737]
Hello everyone, our requirement is to update the modified field of this entity when the data recode is updated.

I found a solution while searching,
URL：https://www.entityframeworktutorial.net/faq/set-created-and-modified-date-in-efcore.aspx
```
public override int SaveChanges()
{
    var entries = ChangeTracker
        .Entries()
        .Where(e => e.Entity is BaseEntity && (
                e.State == EntityState.Added
                || e.State == EntityState.Modified));

    foreach (var entityEntry in entries)
    {
        ((BaseEntity)entityEntry.Entity).UpdatedDate = DateTime.Now;

        if (entityEntry.State == EntityState.Added)
        {
            ((BaseEntity)entityEntry.Entity).CreatedDate = DateTime.Now;
        }
    }

    return base.SaveChanges();
}
```
But I looked at the source code of efcore7, and I found that SaveChanges and SaveChangesAsync are two completely different functions, they are executed separately, and we can't just override the part of SaveChanges.

I'm worried that we haven't found the right method, so I want to ask, is there a best practice method?

**Comment by roji** [comment]
@SF-Simon you can override both to call a common function that does this.

**Comment by SF-Simon** [comment]
> @SF-Simon you can override both to call a common function that does this.

Thank you, roji. 

After reviewing the EF source code, I found that this writing is probably the most comprehensive. Give others a reference.
```
        public override int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            this.Function();
            return base.SaveChanges(acceptAllChangesOnSuccess);
        }

        public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
        {
            this.Function();
            return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
        }

        private void Function()
        {
...
        }
```
