### ISSUE TITLE
Table with same name as a materialized view gives error

### ISSUE THREAD

**Issue by slymuffhugger** [dotnet/efcore#30733]
We have a table "TRAFFIC.ASSOCIATE", and there are also two materialized views "IMPORT.ASSOCIATE" and "IMPORT2.ASSOCIATE". I'm attempting to add the TRAFFIC.ASSOCIATE table, and getting the error "Sequence contains no elements".. 

Turning the logging to verbose, I was able to get the query being generated to list out the tables and views. (this is only one portion, it's unioned with views and materialized views)
![image](https://user-images.githubusercontent.com/27185349/233367602-d8e6433e-ca02-4319-9ea7-e0fd65fd382c.png)
The circled portion is causing my table to be excluded from the list. Is there any way to prevent this? I'm using EF Core 6 so I'm not sure if the issue would be the same in EF core 7.

I can probably get by, by adding the table manually, but the next time I regenerate to add another table, or modify existing tables, the error will happen again..

Here's my package manager scaffold command plus the verbose log after running
[commandPlusVerboseLog.txt](https://github.com/dotnet/efcore/files/11286276/commandPlusVerboseLog.txt)

**Comment by ErikEJ** [comment]
I think you need to address this with Oracle.

**Comment by ajcvickers** [comment]
@slymuffhugger Do the table and view have the same name? If so, how is one distinguished from the other in SQL?

**Comment by slymuffhugger** [comment]
> @slymuffhugger Do the table and view have the same name? If so, how is one distinguished from the other in SQL?

Yes they have the same name, but are in different schemas. But I think Erik was correct, it's an issue in Oracle.EntityFrameworkCore. They don't consider the "OWNER (schema)" when removing materialized views from the list of tables.
