### ISSUE TITLE
Inconsistent delete behavior when clearing a list 

### ISSUE THREAD

**Issue by mathetic** [dotnet/efcore#30748]
We upgraded EF Core from version 6.0.10 to version 7.0.4 and our program started to throw DbUpdateExceptions on a unique constraint. We tracked the issue down to a table which keeps track of items being processed, which had not been emptied from previous runs.

The issue comes up in the following test program: target framework net6.0

```
public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    public string ConnectionString => "Server=localhost;Database=BlogDb;Trusted_Connection=True;TrustServerCertificate=true;MultipleActiveResultSets=true";

    public BloggingContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer(ConnectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().HasMany(b => b.Posts).WithOne().OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<Post>().HasIndex(b => b.PostNumber).IsUnique();
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; } = new();
}

public class Post
{
    public int PostId { get; set; }
    public int PostNumber { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
}
public class Program
{
    public static void Main(string[] args)
    {
        using var db = new BloggingContext();

        var blog = new Blog { Url = "http://blogs.msdn.com/adonet" };

        Console.WriteLine("Inserting a new blog");
        db.Add(blog);

        Console.WriteLine("Adding a post");
        blog.Url = "https://devblogs.microsoft.com/dotnet";
        blog.Posts.Add(
            new Post { Title = "Hello World", Content = "I wrote an app using EF Core!", PostNumber = 1 });
        db.SaveChanges();

        // ef core 6.0.x behaviour is to remove the posts from the database
        // ef core 7.0.5 behaviour is to set blogId to null
        blog.Posts.Clear();
        db.SaveChanges();
    }
}
```

In EF Core 6.0.x (tested versions 6.0.10 and 6.0.16) all posts for the blog are deleted from the database while on EF Core 7.0.5 only the foreign key is set to null.
If the unique constraint is removed in version 7.0.5 it removes the rows from the database. 

What is the intended behavior?

**Comment by ajcvickers** [comment]
See [Orphaned dependents of optional relationships are not automatically deleted](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#optional-deletes)

**Comment by mathetic** [comment]
Thank you for the answer. 

What I still find wierd is that if you remove the row 
```
modelBuilder.Entity<Post>().HasIndex(b => b.PostNumber).IsUnique();
```
from onModelCreating the Posts are removed. Why are they removed when there is no unique index? 

From the breaking changes: _The dependent can exist without any relationship to a principal, so severing the relationship should not cause the entity to be deleted._

**Comment by ajcvickers** [comment]
@mathetic

> What I still find wierd is that if you remove the row `modelBuilder.Entity<Post>().HasIndex(b => b.PostNumber).IsUnique();` from onModelCreating the Posts are removed. 

I'm not able to reproduce this. I see the same SQL generated with or without the index:

```
info: 4/25/2023 20:31:29.973 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (3ms) [Parameters=[@p1='1', @p0=NULL (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      UPDATE [Post] SET [BlogId] = @p0
      OUTPUT 1
      WHERE [PostId] = @p1;
```

**Comment by mathetic** [comment]
It seems I had the wrong version of EF Core installed in my example. It now works as intended.
