### ISSUE TITLE
TPC with Sqlite - key generation on Attach

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#30746]
I am using EF Core Sqlite 7.0.4 and in my model I have a hierarchy of classes. I applied TPC at the entity type builder of the base class (well, not actually the base CLR class but the least-derived class that is included in the model). 

When I used DbContext.Attach( entity) for a concrete entity in the hierarchy, it did not set the Id. 

The hierarchy is more or less: 

    abstract public class TreeNode: ... 
    abstract public class Holdable: TreeNode {...}
    public class HoldableFolder: Holdable {...}
    abstract public V: H {...}
    public class C: V {...}
    public class S: V {...}
    public class I: V {...}

Then I also have another class Option which is not in this hierarchy, as well as some other TreeNode-derived classes. The TreeNode base class is in the model and I called UseTpcMappingStrategy() for it's entity type builder. 

As part of seeding I attached three instances of Option to a DbContext, each time it went into the Added state and assigned a negative Id (i.e. this is prior to saving). That was fine. However, when I attached a HoldableFolder, it went into the Unmodified state with Id = 0. After modifying the HoldableFolder, I then tried to add a second HoldableFolder, which also attached as unmodified and during the Attach it gave an exception saying the Id was duplicate. When I looked in the change tracker entries, I saw the states and Id's as just described. 

The exact exception was line 266 in IdentityMap.cs, InvalidOperationException, "The instance of entity type 'HoldableFolder' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values."

The database file was created by migrations. The EF migrations generated were different for the keys of the Option table and the HoldableFolder table. Declarations of the keys in C# were identical (indeed the key is declared in a shared base class that is not in the model). For the Option class, it had an autoincrement but for the HoldableFolder class it did not: 

            migrationBuilder.CreateTable(
                name: "HoldableFolder",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false),
                    IsLeaf = table.Column<bool>(type: "INTEGER", nullable: false),
                    ParentId = table.Column<long>(type: "INTEGER", nullable: true),
                    Description = table.Column<string>(type: "TEXT", nullable: false),
                    ConcurrencyVersion = table.Column<byte[]>(type: "BLOB", rowVersion: true, nullable: true),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    IsHidden = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HoldableFolder", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Options",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Setting = table.Column<string>(type: "TEXT", nullable: false),
                    ConcurrencyVersion = table.Column<byte[]>(type: "BLOB", rowVersion: true, nullable: true),
                    IsHidden = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Options", x => x.Id);
                });

Sorry I don't have a reproduction in a smaller project --

**Comment by roji** [comment]
@sjb-sjb there's a lot of text above - it really would be useful to just see a simple code sample showing the problem.

**Comment by ajcvickers** [comment]
@sjb-sjb 

> The short version is, in EF core Sqlite, it looks like the key values are not being autogenerated when TPC is used and the key is defined in a base class that is not in the entity hierarchy, and migrations are used.

If this is really true, then it should be easy for you to create a project which reproduces this. The fact that you haven't been able to do so indicates that something else is going on.

**Comment by roji** [comment]
@sjb-sjb just for background, we get tons of issues with no repro - these generally turn out to be of little value, and in fact take up valuable time in triaging and investigating. Besides it being very hard for us to understand exactly what's going on from a textual description, in a great number of cases, there's a user coding mistake, and in many cases they find it themselves after being urged to create a code sample.

So I'd generally recommend putting the time and doing the work to isolate the problem and produce a repro before submitting an issue.
