### ISSUE TITLE
One to many, but only one is main version.

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/efcore#30740]
```
    public class Zoo
    {
        public required int Id { get; set; }

        public List<Animal> Animals { get; set; } = new();
    }

    public class Animal
    {
        public Zoo Zoo { get; set; } = null!;
        public required int Id { get; set; }
        public required string Name { get; set; }

        /// <summary>
        /// The King of Zoos
        /// only one
        /// </summary>
        public bool IsTheKing { get; set; } = false;
    }
```

In this model, there are many animals in my zoo, but the king of the zoo only has one. Perhaps it's a lion today and a tiger every day. I don't know how to write this logic. Currently, whenever the King of Zoos changes, I need to search for the previous King and modify its properties.

This is equivalent to the concept of a main version content.

May I ask if there is a better way to write in EF? When I modify an animal to be the King of the Zoo, the previous King will automatically change this _IsTheKing_ attribute.

**Comment by roji** [comment]
You should be able to have a King reference navigation on Zoo, pointing to the Animal that's currently the king.

**Comment by SF-Simon** [comment]
> You should be able to have a King reference navigation on Zoo, pointing to the Animal that's currently the king.

Hello, @roji, can you provide sample code? I still haven't understood this logic.

thanks.

**Comment by roji** [comment]
You don't need IsTheKing on Animal: just have `public Animal? King` on your Zoo, that should be sufficient.

**Comment by SF-Simon** [comment]
> You don't need IsTheKing on Animal: just have `public Animal? King` on your Zoo, that should be sufficient.

I got it! thank you.
