### ISSUE TITLE
Reverse Engineer: allow customizing the model after it is generated, before being passed to code gen

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#3077]
We want a simple "seam" where folks can get the `Model` just before it is passed to code generation and manipulate it. This is particularly important since we are removing templating for the moment.

**Comment by natemcmaster** [comment]
This is `MetadataReader.GetModel()`. The method is virtual and can be overwritten.

**Comment by divega** [comment]
I think this item was to track how the application developer would do it, not the provider. @rowanmiller?

**Comment by natemcmaster** [comment]
Ah, yes. Who are "folks"?

**Comment by divega** [comment]
:smile:

**Comment by divega** [comment]
Reopening for now.

**Comment by abelepereira** [comment]
I didn't undertand if templating via .cshtml is being definitely replaced for the ```GetModel()``` approach or if the @rowanmiller 's "for the moment" means it will come back on a later release.
The cshtml templating was actually a pretty nice way to enable [the unsupported] pluralization: https://empiricalthoughts.wordpress.com/2015/09/12/entity-framework-7-database-model-pluralization-part-22/

**Comment by divega** [comment]
We have decided to leave the choice of a template based code-gen technology open for now. It is true that Razor enabled plugging in your own pluralization logic... after all you can do pretty much anything with it, but it also leads to complicated templates that mix concerns like this with the actual code generation. One of the ideas we decided to explore is to provide a hook that allows any customization of the model (covered by this issue) plus very simple code gen at the end that just binds to the resulting model and focuses only on what code to generate and its formatting.

**Comment by rowanmiller** [comment]
Closing in favor of https://github.com/aspnet/EntityFramework/issues/4038
