### ISSUE TITLE
Should the valueconversion mapping for guard keys work with EF COre 6?

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#30772]
I was testing out (to demo) before and after for the eF Core 7 support for value conversions that now support mapping guard key objects.

Without the mapping (in either 6 or 7) I get the expected complaint about the missing key property on the entity.

With the mapping, in EF Core 6, dotnet ef dbcontext info fails as expected also.

However integration tests that use the dbcontext to store and retrieve data are working. I would expect them to fail also.

I tried shifting back to an earlier version of EF Core 6 (6.0.13) ...and I get the same behavior.

Here is the repro repo: [https://github.com/julielerman/KeyAsValueObjectDemo](https://github.com/julielerman/KeyAsValueObjectDemo)

### Include provider and version information

EF Core version: 6.0.13 - 6.0.16
Using EF CLI Tools 6.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10  
IDE: Visual Studio 2022 17.5

**Comment by ajcvickers** [comment]
@julielerman The code in the integration tests is not using generated keys. Generated key support is what was added in EF Core 7.  (Although this did work for some simple cases in EF Core 6, it didn't work in the general case.) See [https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#value-generation-for-ddd-guarded-types](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#value-generation-for-ddd-guarded-types) and the [associated sample code](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Miscellaneous/NewInEFCore7/ValueGenerationSample.cs) for more information.

**Comment by julielerman** [comment]
Ahh ...I was using dbgen'd ints in last experiments and switched to code assigned Guids. Got it. Thanks
