### ISSUE TITLE
Include should be able to filter on the JOIN clause with an expression on not enumerables

### ISSUE THREAD

**Issue by alandecastros** [dotnet/efcore#30781]
This problem is useful when you're creating a filter and you want to filter your objects based on some child's attributes.

Example: 

```C#
public class City
{
    public string Name { get; set; }
}

public class User
{
    public string Id { get; set; }
    public City City { get; set; }
}
```

When I want to find users based on city name:

```C#
context.Set<User>().Where(x => x.City.Name == "...")...
```

It happens that it uses the WHERE clause and there are cases that the performance degrades a lot.

If I could filter using:

```C#
context.Set<User>().Include(x => x.City, x => x.Name == "..")...
```

And this added the filters on JOIN clause it would be awsome and the generated query would be a lot faster.

Regards!

**Comment by roji** [comment]
Can you please post the (problematic) SQL you're currently seeing, and the SQL you'd like to see from EF?

Note that if you're looking to express a SQL JOIN directly (that's what it looks like), you can use the LINQ Join operator instead of Include.

**Comment by alandecastros** [comment]
Roji,
Didn't know about the Join operator. 
I'll close the feature request.
Thank you!
