### ISSUE TITLE
Update many to many relationship by using skip navigation properties.

### ISSUE THREAD

**Issue by goodstas** [dotnet/efcore#30798]
Hello, i'm using .NET 6 version with EF Core 7.
I defined two entities :

```C#
public class Country
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Language> Languages { get; set; }
}

// One language -> Many Countries
public class Language
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Country> Countries { get; set; }
}
```

My DB context has a many to many relationship definition : 

```C#
    modelBuilder.Entity<Country>
                        .HasMany(_ => _.Languages)
                        .WithMany(_ => _.Countries);
```

Under the hood , EF Core creates linkage table CountryLanguage.
For example I have a country with ID = 1 and languages with IDs : 1, 2,3 and lets say Country with ID 1 is currently linked to Language with ID 1. It means table CountryLanguage has one row with CountryId = 1 and LanguageId =1.

Now i want to change it , that Country with ID = 1 will be linked to Languages with IDs : 2 and 3.
But when i try to use Update method of DbSet for Country it adds new links but the previous link is not deleted and the result
i got Country with ID=1 which is linked to Languages with IDs :1, 2 and 3.
It means table CountryLanguage has now three rows with CountryId = 1 and LanguageId =1, CountryId = 1 and LanguageId =2 and 
CountryId = 1 and LanguageId =3.
 
The desired behavior was to get Country with ID=1   which is linked to Languages with IDs : 2 and 3 only.
Please, help me to figure out how to do it.
Thank you.

**Comment by ajcvickers** [comment]
@goodstas Here's an example:

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.AddRange(new Country { Languages = new List<Language> { new() } }, new Language(), new Language());

    await context.SaveChangesAsync();
}

using (var context = new SomeDbContext())
{
    var country = context.Set<Country>().Include(e => e.Languages).Single();
    var languages = context.Set<Language>().ToList();
    country.Languages.Remove(languages[0]);
    country.Languages.Add(languages[1]);
    country.Languages.Add(languages[2]);
    await context.SaveChangesAsync();
}

public class Country
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Language> Languages { get; set; }
}

// One language -> Many Countries
public class Language
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Country> Countries { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Country>()
            .HasMany(_ => _.Languages)
            .WithMany(_ => _.Countries);
    }
}
```

**Comment by ajcvickers** [comment]
@goodstas That seems overly complicated. You should just be able to relate the entities with each other as I demonstrated.

**Comment by goodstas** [comment]
but how i can do it if everything what i know about the entity that it;'s impemented interface IEntity which has one generic property Id ?

**Comment by goodstas** [comment]
@ajcvickers please look how microsoft suggest to implement generic repository pattern :
[https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application]
This is an implementation of the update method : 
       `public virtual void Update(TEntity entityToUpdate)
        {
            dbSet.Attach(entityToUpdate);
            context.Entry(entityToUpdate).State = EntityState.Modified;
        }` 
I don't understand how it's possible to do a merge of one properties of the entity like you did.
With my current implementation, i just know that each entity has ID of specific type because it's implements interface IEntity : 
`public interface IEntity<T>
{
     T _EntityId {get; set;}
}`

**Comment by goodstas** [comment]
@ajcvickers So how can i do it with a generic repository?

**Comment by goodstas** [comment]
@ajcvickers I read this article.
Can you help me to understand according to the provided example how calling Merge method adds one more tracking instance and does not change the already tracked one? Because the changes that i do inside the Merge method are done on the already tracked instance . I don't create any new instance of TEntity with the same id and i don't add nothing to db context as you can see..
May be casting from TEntity to IMergeable for calling Merge method confuse the EF Core tracker?

**Comment by ajcvickers** [comment]
> and not some Equals method which returns bool because otherwise it can not translate it to the correct sql query and i got an exception during runtime.

Please open a _new issue_ for this and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by goodstas** [comment]
@ajcvickers ok. i'll do it. 10x
