### ISSUE TITLE
EF7 json Column - Set Max String Length

### ISSUE THREAD

**Issue by BrianMikinski** [dotnet/efcore#30793]
Hi EF Core Team!

Quick question related to[ EF7 json columns](https://devblogs.microsoft.com/dotnet/announcing-ef7-release-candidate-2/) - is there a way to set a max string length via the fluent api? Similar to the default sql data type for string values, a json column migration sets the json data column to be an ```nvarcar(max)```. While I know I can update the migration itself to change the type, is there a more elegant way to do this that can change with the model in the fluent api?

**Comment by maumar** [comment]
not at the moment, tracked by https://github.com/dotnet/efcore/issues/28591
