### ISSUE TITLE
Using postgres enum types generates migration files that depends on the clr enum type

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#30796]
Reopening this issue here: https://github.com/npgsql/efcore.pg/issues/2733

Please see below:

When using postgres enums, the generated migration creates a dependency on the clr enum type. This makes removal of the cumbersome and unintuitive as to what's the proper way to handle this. Do we edit the generated designer files directly? Delete the migration files altogether?

What's the best practice on how we delete the enum, or change it's namespace, etc?

possibly resolved as part of this: https://github.com/dotnet/efcore/issues/2174?

```c#

  public enum MyEnum
    {
        A,
        B,
        C

    }

    public class Entity
    {
        public string Id {get;set;}
        public MyEnum MyEnum {get;set;}
    }

    public class ApplicationDbContext : IdentityDbContext
    {
        static ApplicationDbContext()
        {
            NpgsqlConnection.GlobalTypeMapper.MapEnum<MyEnum>();
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.HasPostgresEnum<MyEnum>();
        }
}
```

generated designer.cs:
```c#

modelBuilder.Entity("Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<MyEnum>("MyEnum") //reference to MyEnum type here
                        .HasColumnType("my_enum");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });
```

**Comment by ajcvickers** [comment]
Note from triage: this is by-design. Types that the provider handles natively are considered to be stable, and we can't think of any better rule than this. Removing all types from the generated code would be a big change. It's unfortunate that the PostgreSQL provider over-achieves in what it can map natively, but then that is in the nature of all things PostgreSQL.
