### ISSUE TITLE
Migration File Generation Command Comment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30808]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Migration-File-Generation-Command-Commen/10316716)._

---
Due to complexities and different users, please add a file level comment at the first comment level of the partial class to record the command that generated the migration file.  The comment should be verbose enough to know what CLI command, or other tool generation, could be used at the command line to replicate the migration if needed.  The comment would also be useful as a learning tool.

---
#### Feedback Bot on 3/22/2023, 09:22 AM: 

(private comment, text removed)

**Comment by ajcvickers** [comment]
Note from triage: this is not something we will implement.
