### ISSUE TITLE
enable-migrations fails -target project doesn't reference EntityFramework

### ISSUE THREAD

**Issue by vigouredelaruse** [dotnet/efcore#30802]
greetings earth people. i 
* cannot enable-migrations because
* i cannot conveniently use new CannotMigrateThisDbContext() because the context depends on a plethora of injected services  since 
* the scenario features a highly abstracted dbcontext with a dynamically constructed model that 
* uses assembly scanning on startup to identify and cache entity model classes with certain marker interfaces and
* consequently depends on a plethora of supporting services registered in di and
* i suppose i'm asking here whether it's possible to use the di container in a 
* design time dbcontext factory implementation

a visual guide to the problematic onmodelcreatingpartial now follows
![image](https://user-images.githubusercontent.com/31052867/235485586-c6f3c4ba-8b54-4f56-a340-4a80a922e254.png)

please advise

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by vigouredelaruse** [comment]
apologies for the scenario complexity. if we take it in parts the first (migrations) blocking issue is ef core tools does not accept that the dbcontext target project properly references ef core as per the below

* enable-migrations fails with the following error. note image depicts the project is correctly selected
```
Your target project 'TheHorselessNewspaper.HostingModel' doesn't reference EntityFramework. 
This package is required for the Entity Framework Core Tools to work. 
Ensure your target project is correct, install the package, and try again.
```
![image](https://user-images.githubusercontent.com/31052867/235502475-7522bfe3-de01-4717-8574-570aa82b27a8.png)

* project file uses  
```
<TargetFrameworks>net6.0;net7.0</TargetFrameworks>
```
but the dependency trees
![image](https://user-images.githubusercontent.com/31052867/235502056-3d5b375b-998b-41c6-add2-21cf21f0b15b.png)

![image](https://user-images.githubusercontent.com/31052867/235502119-b4533ea1-e6ea-4b50-bcd5-9471ec32d632.png)

the raw csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>TheHorselessNewspaper.HostingModel</PackageId>
    <Version>1.0.0</Version>
    <Authors>sechele</Authors>
    <Company>Ataxlab</Company>
    <Product>TheHorselessNewspaper.HostingModel</Product>
    <Description>entity framework core model classes</Description>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Include symbol files (*.pdb) in the built .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.*" />
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.*" />
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Finbuckle.MultiTenant" Version="6.*" />
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" Version="6.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="7.*" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="7.*" />

    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.*" />

    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Finbuckle.MultiTenant" Version="6.*" />
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" Version="6.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="6.*" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="6.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\Design\" />
    <Folder Include="Context\MySQL\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>

```

**Comment by ajcvickers** [comment]
@vigouredelaruse Looks like you are trying to use EF6 tools with EF Core.

**Comment by vigouredelaruse** [comment]
@ajcvickers i've obviously reached my natural level of incompetence with ef core but the situation is more nuanced than mixing up the tools. the below shows the use of ef core command line tools against the project, which
* contains more than one context
* contexts are unusable via default constructors because the dbsets are dynamically created at runtime by services made available by constructor injection
* contexts do not directly inherit from dbcontext
* slightly offbook adddbcontext semantics viz  services.AddTransient<IHostingModelContext, MSSQLHostingContext>();

```
dotnet ef migrations add Initial --context MSSQLHostingContext
Build started...
Build succeeded.
Unable to create an object of type 'MSSQLHostingContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```
[this](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli) indicates that the migrations tools can cooperate with di but in this case that's not working out as per

> Some of the EF Core Tools commands (for example, the [Migrations](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/) commands) require a derived DbContext instance to be created at design time in order to gather details about the application's entity types and how they map to a database schema. In most cases, it is desirable that the DbContext thereby created is configured in a similar way to how it would be [configured at run time](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/).

so while i have your second pair of eyes please comment on
* is it supported (even if inadvisable) to have a purely runtime migrations workflow involving no command line tools?

**Comment by ajcvickers** [comment]
> is it supported (even if inadvisable) to have a purely runtime migrations workflow involving no command line tools?

Applying migrations at runtime can be done safely, but its easy to get it wrong. Generating migrations at runtime is not recommended, and we don't provide a built-in mechanism to do this.

> users will consume project i'm inquiring about containing dbcontexts as nuget packages and never have the ability to run ef core tools against said dbcontext containing project

This is not necessarily a problem, if the NuGet package can contain the generated migrations.

> application users may deploy plugins (on live production servers without compiling or restarting cluster nodes) that apply dbcontext modifications by deploying nuget packages containing new entities and triggering migrations

This is very unlikely to work if the new entities have any kind of relationship with existing entities or share the same DbContext type.

**Comment by vigouredelaruse** [comment]
thanks
