### ISSUE TITLE
Move analyzer tests to `VerifyCS`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/efcore#30803]
Current implementation of analyzers' tests is not actually that easy to read. Other analyzer-related repos in .NET ecosystem use `Microsoft.CodeAnalysis.Testing` library, which simplifies test setup process and allows to use visual markup for defining diagnostics locations. Using it in this repo will help with readability and simplify test setup for potential contributors in this field.

I fully acknowledge that analyzer area has one of the least priorities among other tasks. I am happy to contribute, so I just want team's approve on this change, since this is not that much trivial (+1 dependency and quite a bit of infrastructure rework, even though I strogly believe this will make it better).

**Comment by roji** [comment]
As you wrote, I don't think there's a lot of value in investing in our analyzer test infrastructure - but if you'd like to work on this please go ahead.
