### ISSUE TITLE
Specific attribute not getting generated in cosmos db when creating objects

### ISSUE THREAD

**Issue by HHOSSAIN** [dotnet/efcore#30824]
## Ask a question
I have a container called "Templates" and a container called "GlobalSettings" in cosmos db. When I create Template objects in general, the template objects are created in the expected manner in the "Templates" container. However, when I try to create "GlobalSettings" object, I have noticed that the "templates" attribute is missing in those objects in cosmos db even though I have clearly created a list of "Template" objects when creating the "GlobalSettings" object. 
I have attached the screenshot of the "GlobalSettings" object that got created in cosmost db and you can see that there is no "templates" attribute in there even though I defined a "templates" attribute in GlobalSettings as can be seen in the code snippet.
Can you please suggest how could I get this sorted to get the templates to be appearing when creating "GlobalSettings" object or where am I making a mistake?

### Include your code
![image](https://user-images.githubusercontent.com/59385182/236122901-631b23fe-68b5-427b-90e1-873719bf6329.png)
![image](https://user-images.githubusercontent.com/59385182/236123157-5dc7b700-1967-40cd-8f46-0271789452e7.png)
![image](https://user-images.githubusercontent.com/59385182/236123932-b24d1b0d-ef58-4c51-bbd9-c26d5e6af4a5.png)
![image](https://user-images.githubusercontent.com/59385182/236124208-c7e757d0-d796-4e2e-af39-eeafe5b5d96a.png)

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by HHOSSAIN** [comment]
@ajcvickers I am attaching a screenshot of my project structure(asp .net mvc web app) where you can see how I connect to the database from the testcosmos101context.cs file. I have also attached the program.cs file code which shows how cosmos db context was added. 
I have also attached the db_test() action method from my HomeController which creates the "GlobalSettings" object. I have also added how the models "GlobalSettings" and "Template" look like. 
Now when I call the db_test() action method to create a global settings object, the "templates" attribute does not get created and the "Template" objects that I specified when creating the "GlobalSettings" object goes missing as well in the "GlobalSettings" object created in cosmos db. I have attached screenshot of the object created from running the code in Cosmos db as well.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/59385182/236354201-d97b3fcb-3e9e-4558-a369-d8bdc26e4565.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/59385182/236354482-3b21a199-4cdd-4b95-8ce4-66485519b1ac.png">
<img width="844" alt="image" src="https://user-images.githubusercontent.com/59385182/236354711-f3fb5467-3b04-45c3-8a95-0900e4d5f220.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/59385182/236354846-a5f993cf-9d47-4a11-b27d-be7e4fc40505.png">
<img width="207" alt="image" src="https://user-images.githubusercontent.com/59385182/236354930-dea43c93-95e8-4d2c-89b5-aaa92bd997a2.png">
<img width="221" alt="image" src="https://user-images.githubusercontent.com/59385182/236355528-f14c5cef-8082-477c-9ef9-b025770d826e.png">

**Comment by HHOSSAIN** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

@ajcvickers I am attaching a runnable code which you can clone and test for this issue.  You will just need to add your cosmos db account details(url, account key, database name) in the testcosmos101context.cs file.
Here is the link the to the public repo for you to test: https://github.com/HHOSSAIN/CosmosTestPublic/tree/master/CosmosTestPublic

**Comment by ajcvickers** [comment]
@HHOSSAIN EF doesn't map fields by convention. Did you intend to use a property? For example: `public List<Template>? templates { get; set; }` instead of `public List<Template>? templates;`.

With this change, I see the two `Template` objects being saved to the `Templates` container, with a reference back to the `GlobalSettings` object. For example:

```json
{
    "Id": "bbb7b2cc-49a8-4245-baaa-232acb327a6e",
    "Discriminator": "Template",
    "GlobalSettingsId": "386a27be-49ae-454e-a57f-bee6b56337c0",
    "id": "Template|bbb7b2cc-49a8-4245-baaa-232acb327a6e",
    "templateContent": "<h1>This is GS public2 </h1>",
    "_rid": "GxdRAM0+dtsCAAAAAAAAAA==",
    "_self": "dbs/GxdRAA==/colls/GxdRAM0+dts=/docs/GxdRAM0+dtsCAAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-81e0-27d7044d01d9\"",
    "_attachments": "attachments/",
    "_ts": 1683572772
}
```

**Comment by HHOSSAIN** [comment]
@ajcvickers I do not want the "Template" object that I create inside the "GlobalSettings" object to save in the "Templates" container. I was looking for it to just save inside "GlobalSettings" object. I have given an example below on how I would like my created "GlobalSettings" object to save in the "GlobalSettings" container. Is it possible to achieve something like this as shown in the code below?
`
{
    "Id": "57295435-9470-46ae-af8e-bf63b7a90f14",
    "Discriminator": "GlobalSettings",
    "Expiry": null,
    "IsSubscribed": true,
    "MinimumAttendees": 2,
    "OrgId": "your-org-id",
    "templates": [
       {
       "Id": "bbb7b2cc-49a8-4245-baaa-232acb327a6e",
       "Discriminator": "Template",
       "GlobalSettingsId": "386a27be-49ae-454e-a57f-bee6b56337c0",
       "id": "Template|bbb7b2cc-49a8-4245-baaa-232acb327a6e",
       "templateContent": "<h1>This is GS public2 </h1>",
       "_rid": "GxdRAM0+dtsCAAAAAAAAAA==",
       "_self": "dbs/GxdRAA==/colls/GxdRAM0+dts=/docs/GxdRAM0+dtsCAAAAAAAAAA==/",
       "_etag": "\"00000000-0000-0000-81e0-27d7044d01d9\"",
       "_attachments": "attachments/",
       "_ts": 1683572772
        }
      ],
    "Version": 1,
    "id": "GlobalSettings|57295435-9470-46ae-af8e-bf63b7a90f14",
    "_rid": "31gaALZpdgwIAAAAAAAAAA==",
    "_self": "dbs/31gaAA==/colls/31gaALZpdgw=/docs/31gaALZpdgwIAAAAAAAAAA==/",
    "_etag": "\"00000443-0000-1b00-0000-645979ed0000\"",
    "_attachments": "attachments/",
    "_ts": 1683585517
}
`

**Comment by ajcvickers** [comment]
@HHOSSAIN Don't map `Template` as a top-level entity type. That is, remove the `DbSet<Template>` property , and remove the call to `modelBuilder.Entity<Template>()`. Then you should get:

```json
{
    "Id": "61bec065-ba44-4dcf-ad3e-1e2a48436a34",
    "Discriminator": "GlobalSettings",
    "id": "GlobalSettings|61bec065-ba44-4dcf-ad3e-1e2a48436a34",
    "templates": [
        {
            "Id": "03bb77f1-2026-41a6-9952-d1338f9f7335",
            "templateContent": "<h1>This is GS public1</h1>"
        },
        {
            "Id": "c175fc63-9af8-4fca-90d5-37807d123c50",
            "templateContent": "<h1>This is GS public2 </h1>"
        }
    ],
    "_rid": "H559AJ4XTLYBAAAAAAAAAA==",
    "_self": "dbs/H559AA==/colls/H559AJ4XTLY=/docs/H559AJ4XTLYBAAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-8313-a922e46601d9\"",
    "_attachments": "attachments/",
    "_ts": 1683704844
}
```
