### ISSUE TITLE
Got a runtime exception by trying to translate Linq query to SQL query

### ISSUE THREAD

**Issue by goodstas** [dotnet/efcore#30838]
Hello,
i want to use Generic Repository pattern with EF core  for CRUD operations.
I put runnable project here : [https://github.com/goodstas/LinqToSqlManyToMany]

I try to delete an entity by providing it's ID which has also a Generic type and i got the following exception : 
    **System.InvalidOperationException** : The LINQ expression 'DbSet<Genre>()
    .Where(g => g.HasIdenticalId(__id_0))' could not be translated. 
Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.
See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

The definition of the Generic Repository looks as following: 
```
public class GenericRepository<TEntity, TEntityIdType> : IDataRepository<TEntity, TEntityIdType> where TEntity : class, IEntity<TEntityIdType>
```

The definition of the DeleteById method looks as following : 
```
        public async Task<TEntityIdType> DeleteByIdAsync(DbContext context, TEntityIdType id)
        {
            var deletedEntities = await context.Set<TEntity>().Where(_ => _.HasIdenticalId(id)).ExecuteDeleteAsync();
            return id;
        }
```

The definition of interface IEntity:
```
    public interface IEntity<TEntityIdType>
    {
        TEntityIdType Id { set;  get; }

        bool HasIdenticalId(TEntityIdType id);
    }
```
The definition of one of the classes which implements the above interface : 
```
public class Genre : IEntity<long>, IMergeable<Genre>
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public List<Movie> Movies { get; set; }

        public bool HasIdenticalId(long id)
        {
            return this.Id == id;
        }

        public void Merge(Genre entity)
        {
            this.Name   = entity.Name;

            Dictionary<long, Movie> currentMovies = new System.Collections.Generic.Dictionary<long, Movie>();
            Dictionary<long, Movie> updatedMovies = new System.Collections.Generic.Dictionary<long, Movie>();

            this.Movies.ForEach(genre => currentMovies.Add(genre.Id, genre));
            entity.Movies.ForEach(genre => updatedMovies.Add(genre.Id, genre));

            this.Movies.Clear();

            foreach (var genre in updatedMovies)
            {
                if (currentMovies.ContainsKey(genre.Key))
                {
                    this.Movies.Add(currentMovies[genre.Key]);
                }
                else
                {
                    this.Movies.Add(genre.Value);
                }
            }
        }
    }
```

EF Core version: 8.0.0-preview.3.23174.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL Version="8.0.0-preview.3"
Target framework: NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4.5

@ajcvickers I opened a new issue and provided a runnable project as you asked. Thank you.

**Comment by roji** [comment]
HasIdenticalId is a .NET function - you can't call arbitrary functions within your queries, since EF has no way of translating that to SQL.

**Comment by goodstas** [comment]
@roji I understand this and it was my question to @ajcvickers . He told me to open a new issue and to attach the runnable project.
I try to use Id of generic type in the Where clause and the only way that i found is
```
public async Task<TEntityIdType> DeleteByIdAsync(DbContext context, TEntityIdType id)
        {
            var deletedEntities = await context.Set<TEntity>().Where(_ => _.Id.ToString() == id.ToString()).ExecuteDeleteAsync();
            return id;
        }
```
Is this solution good/legal? or it's kind of hack? (i know that it works)
Do you have any suggestions how i can do it in another way?

**Comment by roji** [comment]
It seems fine to me - I don't see how wrapping it in a function would make it any better. I'd recommend not using the underscore as the variable name, as you're actually accessing a property on it.

**Comment by ajcvickers** [comment]
I think the issue is that the `==` operator can't be used because it is not defined for the generic types involved. However, there was an assertion that using `Equals` also doesn't work, which is what I asked for a repro of.

**Comment by goodstas** [comment]
@roji thank you.
@ajcvickers i can't use Equals with the generic type. i can only define some kind of Equals method like HasIdenticalIds.
Trying to define the IEquatable interface didn't succeed as well..
