### ISSUE TITLE
Wishlist: No generate empty lines with public virtual DbSet<Foo> Foos { get; set; } and public virtual DbSet<ViewFoo> ViewFoos { get; set; } and modelBuilder.Entity<Foo>(...)

### ISSUE THREAD

**Issue by donhuvy** [dotnet/efcore#30839]
Current status: DBContext always is the longest file in Visual studio project, event with small number of tables, views. With large-scale database (for example, accounting software, about 600 tables, 350 views), File DBContext has length about 41.000 lines of code (41 thousand lines of code). Editing is hard, because text file is too big. By reduces empty lines, performance for editing, view file will improve (performance for read/edit/modify) about 15%.

If apply for section `modelBuilder.Entity<Foo>(...)`, performance for read/edit/modify will reach more, about 40% .

![image](https://user-images.githubusercontent.com/1328316/236672124-67705754-5b63-4860-bccf-ca98ea650469.png)

![image](https://user-images.githubusercontent.com/1328316/236672174-2a964456-f192-45a1-afcd-b3f540726601.png)

Wishlist: No generate empty lines with 

```csharp
public virtual DbSet<Foo> Foos { get; set; }
```
and 
```csharp
public virtual DbSet<ViewFoo> ViewFoos { get; set; }
```

It is development experience. I also hope has parameters for generating, can separate DBContext to many small files.

**Comment by ErikEJ** [comment]
@donhuvy You can do that with T4 templates

**Comment by donhuvy** [comment]
Thank you for your suggestion. Yesterday, I spent about 8h for delete empty lines (https://stackoverflow.com/a/65699493/3728901 ), concatenation multi-lines of builder to single lines. I reduced 41000 lines of code to 31.000 lines of code. The Visual Studio code editor reduce lag.

**Comment by roji** [comment]
@donhuvy as mentioned above, there's really no reason to spend time manually deleting empty lines - you can easily change the template which EF uses when it generates scaffolded C# files.
