### ISSUE TITLE
GenerateCreateScript difference between 3.1 and 7.0

### ISSUE THREAD

**Issue by aleksvujic** [dotnet/efcore#30844]
Until now, we have been using EF Core 3.1. We would like to migrate to EF Core 7.0. In our unit tests, we create the database from existing C# database models using the following code snippet (key ingredient: `IRelationalDatabaseCreator.GenerateCreateScript`). We are using PostgreSQL database and Npgsql provider.

```cs
private void PrepareEmptySchema<T>(T dbContext) where T : DbContext
{
  try
  {
	// GenerateCreateScript() returns CREATE scripts for all database entities, even for the ones which already
	// exist in the database.
	//    Q:  Why do some entities already exist?
	//    A:  If GenerateCreateScript is called on FitDbContext, it also contains SQL for creating related
	//      entities from other schemas (ex. SupDbContext).
	// If an entity has some default data set with modelBuilder.Entity<T>().HasData(...), it is included
	// in this SQL script with INSERT INTO ... statements, which is awesome.
	var createAllDbEntitiesSqlScript = dbContext.GetService<IRelationalDatabaseCreator>().GenerateCreateScript();

	// Split one giant SQL script into one-script-per-entity so that we can create them one-by-one and
	// create all the missing entities. Split on ';' character which is not inside single or double quotes.
	var entitiesScripts = Regex.Split(createAllDbEntitiesSqlScript, @";(?=(?:[^\""\'\n]*(\""|\')[^\""\'\n]*(\""|\'))*(?![^\""\'\n]*(\""|\')))");

	foreach (var entityScript in entitiesScripts)
	{
	  try
	  {
		dbContext.Database.ExecuteSqlRaw(entityScript);
	  }
	  catch (Npgsql.PostgresException pe)
	  {
		if (pe.SqlState == PostgresErrorCodes.DuplicateTable)
		{
		  // Table already exists. Ignore the exception, continue with creating other entities.
		  Console.WriteLine($"Relation already exists. Error: {pe}");
		  continue;
		}

		throw pe;
	  }
	  catch (Exception e)
	  {
		// Unknown exception type, this sould not happen under normal circumstances.
		Console.WriteLine($"Unknown exception while creating a database entry. Error: {e}");
		Console.WriteLine("Terminating...");
		throw e;
	  }
	}
  }
  catch (Exception e)
  {
	Console.WriteLine($"There was an exception while preparing empty schema for database context {typeof(T)}. Error: {e}");
	throw e;
  }
}
```

In version 3.1, `GenerateCreateScript` returned the following SQL:

```sql
CREATE SCHEMA IF NOT EXISTS fit;
CREATE SCHEMA IF NOT EXISTS sup;

-- many more commands
```

Now, in version 7.9, `GenerateCreateScript` returns the following SQL:

```sql
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'fit') THEN
        CREATE SCHEMA fit;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sup') THEN
        CREATE SCHEMA sup;
    END IF;
END $EF$;

-- many more commands
```

What's the reasoning behind wrapping it with `BEGIN` and `END`? How can I reliably execute each SQL statement separately. Previously, I was able to split by `;` to get separate SQL statements, but now `;` charachters are inside `BEGIN` and `END` as well.

**Comment by roji** [comment]
This change was done to fix https://github.com/npgsql/efcore.pg/issues/1770 - `CREATE SCHEMA IF NOT EXISTS` doesn't work if there's no CREATE privileges.

By design, migration SQL isn't supposed to be easily splittable on semicolons, and you're generally not supposed to parse that SQL - just execute it. What's you're reason for splitting by semi-colons rather than just executing the SQL?

Note that for unit tests, it's common to use [EnsureCreated](https://learn.microsoft.com/en-us/ef/core/managing-schemas/ensure-created) which does everything for you.

**Comment by aleksvujic** [comment]
We have multiple database contexts, each for its own PostgreSQL schema. There exist foreign keys between the schemas. We would like to create all schemas and their tables.

We have 2 PostgreSQL database schemas:

1. `test1` with `Test1DbContext`
2. `test2` with `Test2DbContext`

When we execute `test1DbContext.Database.EnsureCreated();`, it also creates related tables from schema `test2`. Then, when we execute `test2DbContext.Database.EnsureCreated();`, nothing happens because schema is not empty (tables already exist). This is documented [here](https://learn.microsoft.com/en-us/ef/core/managing-schemas/ensure-created#ensurecreated).

That's why we created our own `PrepareEmptySchema<T>(T dbContext) where T : DbContext` method, which is invoked like this for both contexts:

```cs
PrepareEmptySchema<Test1DbContext>(test1DbContext);
PrepareEmptySchema<Test2DbContext>(test2DbContext);
```

`PrepareEmptySchema` method obtains a complete SQL for creating schema and tables with `GenerateCreateScript`. It tries to execute each SQL statement separately. That's because `PrepareEmptySchema<Test1DbContext>(test1DbContext);` also creates referenced tables from schema `test2` - executing complete SQL for creating schema `test2` would throw an exception because some of the tables already exist.

Related issue created by me some months ago: https://github.com/dotnet/efcore/issues/29144

**Comment by aleksvujic** [comment]
For anyone wondering, I found a solution with custom implementation of `IRelationalDatabaseCreator`. We use this in unit tests to initialize an empty database from C# models.

Create a `CustomNpgsqlDatabaseCreator` which exposes `GetSqlStatements` function.

```cs
public class CustomNpgsqlDatabaseCreator : NpgsqlDatabaseCreator
{
  public CustomNpgsqlDatabaseCreator(
    RelationalDatabaseCreatorDependencies dependencies,
    INpgsqlRelationalConnection connection,
    IRawSqlCommandBuilder rawSqlCommandBuilder) : base(dependencies, connection, rawSqlCommandBuilder)
  {

  }

  /// <summary>
  /// Get a list of all create commands for initializing the database. No need to parse anything,
  /// each element of the list already represents a single SQL statement.
  /// </summary>
  public IReadOnlyList<MigrationCommand> GetSqlStatements()
  {
    return GetCreateTablesCommands();
  }
}
```

Then, replace `IRelationalDatabaseCreator` with `CustomNpgsqlDatabaseCreator`:

```cs
private static void ConfigureDbContext<T>(IServiceCollection services) where T : DbContext
{
  services.AddDbContext<T>(options =>
  {
    options.UseNpgsql(GetDbConnection())
      .ReplaceService<IRelationalDatabaseCreator, CustomNpgsqlDatabaseCreator>();
    options.EnableSensitiveDataLogging(true);
  });
}
```

Then, when you want to obtain separate SQL commands and execute them one-by-one, use the following code snippet:

```cs
var entitiesScripts = (dbContext.GetService<IRelationalDatabaseCreator>() as CustomNpgsqlDatabaseCreator).GetSqlStatements();
foreach (var entityScript in entitiesScripts)
{
  dbContext.Database.ExecuteSqlRaw(entityScript.CommandText);
}
```
