### ISSUE TITLE
Decimals being truncated in EF Core

### ISSUE THREAD

**Issue by Brian-Con** [dotnet/efcore#30858]
Hi,

In EF Core, decimal values are truncated to 2 decimal places. EF has the same behavior, but in EF you can override that behavior with the following code:

```c#
public class DbContextConfiguration : DbConfiguration
    {
        public DbContextConfiguration()
        {
            var providerInstance = SqlProviderServices.Instance;
            SqlProviderServices.TruncateDecimalsToScale = false;
            this.SetProviderServices(SqlProviderServices.ProviderInvariantName, SqlProviderServices.Instance);
        }
    }
    [DbConfigurationType(typeof(DbContextConfiguration))]
``` 

Is there an equivalent to this in EF Core - A central place when you can configure the code not to truncate decimals?

I'm aware of the **[Precision(15,6)]** keyword which you can use to override the behavior at the individual Property level, but I'd rather not go down the path of having to set this attribute for each Property if there is a better option.

```c#
        [Precision(15,6)]
        public decimal? HZ_Qty { get; set; }
        public string? HZ_UOM { get; set; }
        [Precision(15, 6)]
        public decimal? HZ_OriginalQty { get; set; }
        public string? HZ_OriginalUOM { get; set; }
``` 

Thanks,
Brian

**Comment by roji** [comment]
@Brian-Con you're probably looking for [bulk configuration](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#pre-convention-configuration) - you can easily set the (default) precision and scale for all decimals in your model.

**Comment by Brian-Con** [comment]
That worked, thank you!
