### ISSUE TITLE
Running with compiled model fails to load entity properties defined in abstract base class when in different assembly

### ISSUE THREAD

**Issue by nettashamir-allocate** [dotnet/efcore#30853]
I have an abstract class in our core "framework" project which is then extended as a mapped EFCore concrete class in our "product" project (in a separate assembly). Both the abstract class and the concrete class have the **same name** (but different namespaces). This is logical in the use case since the classes represent a specific concept and so adding "Base" to the one in the framework would result in ugly code. 

Running with an uncompiled model, this all works fine. However, using the compiled model (which I need to do since our model is very large and takes a long time to load), when I try to load an instance of the concrete class, any properties declared on the abstract class fail to load.

This can currently be worked around by either:

1. Change the name of the base class to be different from that of the concrete class - Results in ugly code in the framework
2. Make the properties abstract on the base class and implement them in the concrete class - Possible but shouldn't be necessary
3. Move the classes into the same assembly - not an option since the framework is there to be reused by multiple projects.

All of these workarounds do work however none are ideal.

**Framework class and mappings** in Framework.csproj

```
namespace Framework;

public abstract class ChangeSet {
	protected DateTime created;
	public abstract long ID { get; }
	public DateTime Created { get { return created; } }
}

public abstract class ChangeSetMappings<TChangeSet> : IEntityTypeConfiguration<TChangeSet> where TChangeSet : ChangeSet {
	public virtual void Configure(EntityTypeBuilder<TChangeSet> entity) {
		entity.ToTable(typeof(TChangeSet).Name);
		entity.HasKey(e => e.ID);
		entity.Property(e => e.ID)
			.HasColumnName("ChangeSetID")
			.HasField("id")
			.ValueGeneratedNever(); // trivial emulation of our generated keys
		entity.Property(e => e.Created)
			.HasColumnName("Created")
			.HasColumnType("datetime2(2)");
	}
}

```

**Minimal product class and mappings** in BugRepro.csproj

```
namespace BugRepro;

public class ChangeSet : Framework.ChangeSet {

	protected long id;

	public static ChangeSet Create(string name, DateTime created) {
		return new ChangeSet { id = 1, Name = name, created = created };
		// Note: id is normally generated but just set explicitly here for simplicity
	}
	public override long ID { get { return id; } }
	public string Name { get; set; }
}

public class ChangeSetMappings : ChangeSetMappings<ChangeSet> {
	public override void Configure(EntityTypeBuilder<ChangeSet> entity) {
		base.Configure(entity);
		entity.Property(e => e.Name);
	}
}

```

DbContext

```
namespace BugRepro;

public class TestDbContext : DbContext {

	private const string DATA_SOURCE = ""; //Insert DataSource string here eg. MACHINE_NAME\\DB_INSTANCE_NAME
	const string CONNECTION_STRING = $"Data Source={DATA_SOURCE};Initial Catalog=TestEFCoreBugs;Integrated Security=True;TrustServerCertificate=True";

	public DbSet<ChangeSet> ChangeSets { get; set; }
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
		if (string.IsNullOrEmpty(DATA_SOURCE)) throw new Exception("Specify a valid DATA_SOURCE in TestDbContext");

		optionsBuilder.UseSqlServer(CONNECTION_STRING);
		optionsBuilder.UseModel(CompiledContextModels.TestDbContextModel.Instance);
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder) {
		modelBuilder.ApplyConfiguration(new ChangeSetMappings());
	}
}

```

Repro test

```
namespace BugRepro;

public class TestPropertiesOnAbstractBase {
	private TestDbContext context;

	[SetUp]
	public void SetUp() {
		context = new TestDbContext();
		foreach (var changeSet in context.ChangeSets) { context.Remove(changeSet); }
		context.SaveChanges();
		context.ChangeTracker.Clear();
	}

	[TearDown]
	public void TearDown() { context.Dispose(); }

	[Test]
	public void DoTest() {
		var createTime = new DateTime(2023, 2, 23, 23, 23, 23);
		const string name = "Bob";

		var changeSet = ChangeSet.Create(name, createTime);
		context.Add(changeSet);
		context.SaveChanges();
		Assert.That(changeSet.Created, Is.EqualTo(createTime), "Created value straight after Save Changes");

		context.ChangeTracker.Clear(); // ensure we are re-fetching the entity

		var foundChangeSet = context.ChangeSets.Single();
		Assert.That(foundChangeSet.Name, Is.EqualTo(name));
		Assert.That(foundChangeSet.Created, Is.EqualTo(createTime), "Created value from DB");
	}
}
```
_Note that if you comment out the UseModel line in the TestDbContext, it passes ok._

Minimal repro VS solution to demonstrate this issue (including the above code) is attached here: [AbstractClassBugRepro.zip](https://github.com/dotnet/efcore/files/11429112/AbstractClassBugRepro.zip)

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer v 7.0.5
Target framework: NET 6.0
Operating system: Win 11
IDE: Visual Studio 2022 17.5.4

**Comment by ajcvickers** [comment]
Note from triage: covered by https://github.com/dotnet/efcore/issues/27203. Make sure to vote (👍) for that issue.
