### ISSUE TITLE
GenerateCreateScript doesn't return SQL for creating views

### ISSUE THREAD

**Issue by aleksvujic** [dotnet/efcore#30854]
We are using .NET 7, EF Core 7 and Npgsql 7. In our application, we use database-first approach. We scaffold the database structure into C# models. We have a simple database context, which contains a single view:

```cs
public partial class MatDbContext : DbContext
{
    public MatDbContext(DbContextOptions<MatDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ViBaseUnits> ViBaseUnits { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ViBaseUnits>(entity =>
        {
            entity.ToView("vi_base_units", "mat");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
```

In unit tests, we want to go the opposite way - code first approach. We want to recreate an empty database so that unit tests always start with fresh set of data. For this purpose, we have the following code snippet which obtains a SQL script for creating the database.

```cs
var script = dbContext.GetService<IRelationalDatabaseCreator>().GenerateCreateScript();
dbContext.Database.ExecuteSqlRaw(script);
```

However, `GenerateCreateScript` function doesn't create database views. I understand why it's the case - EF has no way of knowing how view is defined.

The following idea came to my mind: Is it possible to "trick" EF scaffolder to include metadata about the view column (its SQL statement) so that it can later be read by `GenerateCreateScript` and included in the final SQL?

Example:

Database view `vi_base_units` was created using the following SQL:

```sql
CREATE OR REPLACE VIEW mat.vi_base_units
AS SELECT
	unit.id AS unit_id,
	status.name AS status_name
   FROM mat.unit unit
     LEFT JOIN mat.status status ON unit.status_id = status.id;
```

This results in the following C# model when scaffolded:

```cs
[Keyless]
public partial class ViBaseUnits
{
    [Column("unit_id")]
    public int UnitId { get; set; }

    [Column("status_name")]
    public string StatusName { get; set; }
}
```

Is it possible to configure EF scaffolder to also store information about view columns (possibly in `[Column]` attribute) so that the view can later be reconstructed using `GenerateCreateScript`?

**Comment by roji** [comment]
@aleksvujic is this request different from #20940?

**Comment by aleksvujic** [comment]
If I understand the linked issue correctly, the OP noticed that the EF scaffolder generated `ToTable()` call instead of `ToView()` for the database view. This is not the case for me, EF Core 7 scaffolder correctly generates `ToView()` for database views.

Our normal workflow is database-first. We modify the database and scaffold it to get new C# models. However, in unit tests, we take the reverse approach (code-first). We create an empty database dedicated to unit tests. We obtain the SQL script with `GenerateCreateScript()`. Nonetheless, `GenerateCreateScript` doesn't contain any `CREATE OR REPLACE VIEW` statements, which is understandable since it has no way of knowing how database view columns are defined.

If we want to create a database view from an existing scaffolded C# model, the EF scaffolder would have to store some metadata about how database view columns are defined so that `GenerateCreateScript` can recreate it.

I hope I explained myself in an understandable manner. If anything is unclear, please let me know.

**Comment by roji** [comment]
Yeah, the issue was originally about correctly generating ToView(), but as you've noticed that has already been done. It now tracked reverse-engineering the view's SQL definition into C# code, to be included in the EF model.

**Comment by aleksvujic** [comment]
Yes, our ultimate goal is to be able to recreate a PostgreSQL view with `GenerateCreateScript ` from an existing EF model. I assume this includes changing the scaffolder so that it stores some metadata about the database view in the EF model.

What's the progress of https://github.com/dotnet/efcore/issues/20940? Can we expect it in future releases of EF Core 7?
