### ISSUE TITLE
7.0.5 nuget Microsoft.EntityFrameworkCore.Sqlite copies wrong version of SQLitePCLRaw.core.dll

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#30863]
I have a visual 2022 sln that has about 20 projects. In the solution all project are net7.0. Only one project uses Microsoft.EntityFrameworkCore.Sqlite.

When I run I get an exception for the wrong version of SQLitePCLRaw.core.dll. In my bin directory I keep getting version 2.0.4.976 when the 7.0.5 version of Microsoft.EntityFrameworkCore.Sqlite uses version 2.1.4. I have been trying to  figure out why version 2.0.4 of SQLitePCLRaw.core.dll gets copied. 

On top of that after a build sometimes the version is 2.1.4 shows up as it should be. There is only one project using Microsoft.EntityFrameworkCore.Sqlite so it is not an issue of another project using an older version of Microsoft.EntityFrameworkCore.Sqlite. The solution is all .net 7 and in my .nuget directory ".nuget\packages\microsoft.entityframeworkcore.sqlite.core\7.0.5\lib" I have net6.0 not net7.0. I am not sure if that is an issue. How do get net7.0 and also get, Microsoft.EntityFrameworkCore.Sqlite,  using the correct version of SQLitePCLRaw.core.dll.

**Comment by dgxhubbard** [comment]
[Projects.zip](https://github.com/dotnet/efcore/files/11444234/Projects.zip)
Here they are

**Comment by dgxhubbard** [comment]
I found the issue, telerik reporting depends on SQLitePCLRaw.

![image](https://github.com/dotnet/efcore/assets/5032382/2e3a79ea-9ab1-45e9-8100-775666217b29)

**Comment by AndriySvyryd** [comment]
cc @bricelam

**Comment by bricelam** [comment]
Yeah, SQLitePCLRaw.bundle_green is the problem. You might be able to reconcile everything by adding these to your csproj:

```xml
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.4" ExcludeAssets="all" />
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.4" />
```

But I'm not sure how Telerik.Reporting uses SQLitePCLRaw, so there's a slight chance this will break them.

**Comment by dgxhubbard** [comment]
I don't know why they are using it but it took me a bit to find it
