### ISSUE TITLE
Registering AddPooledDbContextFactory side by side with AddDbContext

### ISSUE THREAD

**Issue by Yosif-Smint** [dotnet/efcore#30878]
## Ask a question
Greetings Microsoft folks,

I have a scenario where I want to use AddDbContext and AddPooledDbContextFactory at the same time.
I was looking at the source and I want to double confirm with someone familiar with the code.

Lets say, the DB context is named SomeDbContext.

In this scenario, when requesting a SomeDbContext using DI in the constructor, will it then by default use the pool or not?
Currently, our codebase is using this everywhere, and we do (not yet) want to change that behavior everywhere.

What we want to achieve is:

If we request SomeDbContext through DI in the constructor, the pool should not be used (staying backwards compatible).
ONLY if we request it through _pooledDbContextFactory.CreateDbContextAsync(), the pool should be used.

### Include your code
```C#
services.AddDbContext<SomeDbContext>(
    options =>
    {
        options.UseNpgsql(connectionString...);
    }, 
    contextLifetime: ServiceLifetime.Scoped,
    optionsLifetime: ServiceLifetime.Singleton);

services.AddPooledDbContextFactory<SomeDbContext>(
    options =>
    {
        options.UseNpgsql(connectionString...);
    });
```
### Include provider and version information

EF Core version: 6.0.9
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.5.5

Best Regards,
Yosif

**Comment by ajcvickers** [comment]
> If we request SomeDbContext through DI in the constructor, the pool should not be used (staying backwards compatible).
ONLY if we request it through _pooledDbContextFactory.CreateDbContextAsync(), the pool should be used.

This is how its designed to work.

**Comment by Yosif-Smint** [comment]
I appreciate the quick response.
Thanks for the confirmation!
