### ISSUE TITLE
ExecuteUpdate ExecuteDelete methods are thread safe ?

### ISSUE THREAD

**Issue by YakupIpek** [dotnet/efcore#30875]
Can you please document that `ExecuteDelete` and `ExecuteUpdate` update methods are thread safe or not ?

**Comment by ajcvickers** [comment]
@YakupIpek Nothing that uses a DbConnection under the hood is thread safe. So, no, they are not.

**Comment by YakupIpek** [comment]
@ajcvickers These methods doesn't open new connection for per call ?

**Comment by ajcvickers** [comment]
@YakupIpek Yes, by default they will _open_ a connection per call, but they use the connection _instance_ that is on the context.

**Comment by YakupIpek** [comment]
Why it is needed to use same connection instance for these methods ? IMO it would be better to design them as thread safe.
