### ISSUE TITLE
untheorized access exception on running dotnet ef migration bundle command

### ISSUE THREAD

**Issue by Shyam268** [dotnet/efcore#30876]
tools used to create bundle:
    Entity Framework Core .NET Command-line Tools 7.0.5 
nuget packages - 
  Microsoft.EntityFrameworkCore.Tools" Version="7.0.1 
  Microsoft.EntityFrameworkCore" Version="7.0.1" 
dotnet version: 7.0.105
 
Getting exception on running this command: 
 dotnet ef migrations bundle -c myproject.Infrastructure.Database.ApplicationDbContext -o Database/Migrations -s ../myproject.Web

![image](https://github.com/dotnet/efcore/assets/30112490/66155edc-5467-41ca-a69c-0e21bf26e079)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Shyam268** [comment]
the issue is fixed by changing output directory which is already exist. but the error details are confusing on windows and it is clear on linux machine.
