### ISSUE TITLE
Sub-Entity will not be loaded correctly after applying a soft delete-mechanism within the same dbcontext with include

### ISSUE THREAD

**Issue by PassionateDeveloper86** [dotnet/efcore#30884]
**Problem:**
_Under certain circumstances EFCore will load a as deleted marked entity, even a map (global filter) is active and the query itself will not be loading the entity._

**Circumstances:**

1) A soft delete is applied (global filter by map, deleted entities will be marked modified and IsDeleted will be set instead of the entity will be deleted completly)
See details here:  https://digitaldrummerj.me/ef-core-soft-deletes/
2) An entity has sub entites (only applies to sub entities) e.g.

```
// Main entity
public class Person 
{
    public Guid Id { get ;set; }

    public List<Email> Emails { get; set; }

    public bool IsDeleted { get; set; }
}

// sub entity
public class Email 
{
    public Guid Id { get ;set; }

    public string Email { get; set; }

    public Person Person { get; set; }

    public Guid PersonId { get ;set; }
   
    public bool IsDeleted { get; set; }
}
```

**Reproduce the bug:**
The bug occurs when we have an entity with subentites and we delete a subentity. 
With the soft delete in place, the sub entity will only be marked as "IsDeleted=true" but with the Map and global filter it should not be loaded again ever.
When we now load the main entity again, even the sql query itself vie log is applying the filter correctly, the entity will load the freshly marked "isDeleted=true" subentites within.

**This only happens:**
- when using Include. When we load the sub entites by an extra query it doesnt happen
- when using the same DbContext in which the updated happened. If we close the DbContext and open a new one, the load is correct and the as deleted marked subentities will not be loaded.
- When the subentity is not manuelly removed from the main entity when deleting. This might "solving" the bug, but we implemented the softdelete to have the data in place later - if we remove the sub from the main entity it cause a deletion of the foreign key in the database of the sub entity which means the whole idea of soft delete is crashed.

** Code**
(given are the both entites above and a fitting and open dbcontext)

```
// create an entry
var person = new Person();
person.Id = Guid.NewGuid();
person.Emails = new List<Emails>() { new Email() { Id = Guid.NewGuid(),  Email  = "Test" };
dbcontext.Persons.Add(person);
await dbcontext.SaveChangesAsync();

// delete the sub entry, but dont remove it from the main entity
dbContext.Emails.Remove(person.Emails[0]);
await dbcontext.SaveChangesAsync();

// read the main entity again
var newPerson = await dbcontext.Persons.Include(x => x.Emails).Single(x => x.Id == person.Id);

// Error here - I would expect 0 email addresses, but instead it has one.
var shouldNotHave = newPerson.Emails;
```

**Workarounds**
1) Close and reopen the db context between the Remove and the Single command -> 0 Emails will be loaded instead 1
2) Read the emails directly:
var emails = await dbcontext.Emails.Where(x => x.Personid == person.id).ToList()
-> 0 Emails will be loaded instead 1

**More Info:**
I checked the outcomming SQL, which seems okay, it will be filtered on IsDeleted in all levels (main entity and joined sub entity).
If I run the query manually in my SQL browser (e.g. DBWeaver) it is correctly (0 Emails).

### Include provider and version information

EF Core version:
Database provider: NGSQL 7.0.2 with Eneity Framework Core 7.0.3
Target framework: .NET 60
Operating system: Windows 11
IDE: Rider newest

**Comment by ajcvickers** [comment]
If an entity instance with a given ID is already tracked by the context, then that entity instance will be returned in the query. This is by-design. Generally, a new DbContext instance should be used from each unit-of-work.

**Comment by PassionateDeveloper86** [comment]
@ajcvickers Does that mean the here discribed behaviour is intentionally and not a bug?
Is there a setting to have this changed?

**Comment by ajcvickers** [comment]
Yes, this behavior is by-design, and can't be changed. Running into this typically means that either a) the context is being used for more than a single unit-of-work, and/or b) a no-tracking query is more appropriate.

**Comment by PassionateDeveloper86** [comment]
Thank you for clarifying that.
Can you elaborate 1 and 2?

1) What do you mean with single UoW - is it best practice to use a single UoW for each query like, when I update and reload the entity, should I use 2 DbContextes (is 1 DbContext 1 UoW)? Maybe your have en example of a best practice
2) Would a no-tracking query for reading after the update causing not to have this behaviour?

**Comment by ajcvickers** [comment]
1. The [change tracking docs](https://learn.microsoft.com/en-us/ef/core/change-tracking/) cover this. In a nutshell, use a DbContext instance for a single unit-of-work, and then dispose of it. That is, create instance, query/track, make changes, call SaveChanges, dispose.
2. A no-tracking query will always return the data as it is in the database, but it doesn't sound like that's what you want.

**Comment by PassionateDeveloper86** [comment]
Hi @ajcvickers 
thank you very much again for taking the time and explainig it to me.
Last question:
Can you give me an example of the best practice you describer in 1)?

E.g. you told be I should use a single DbContext for each single unit of Work, then disposing it.
I tried to google this approach a bit, but even the first google sites and patterns show a different behauvior like this:
https://dotnettutorials.net/lesson/repository-design-pattern-csharp/

In this repository pattern (Yes, I know we usually dont need it in EF) the idea is to have a capsule of different query-methods which can end up in a single savechanges - so with your comment under 1) I would understand, that this is by-design, wrong?

Maybe you can give an example / example page how it should be correctly handled?

**Comment by PassionateDeveloper86** [comment]
Im very sorry, but Im still dont get it...
If course single unit of work can do everything like 100 quieres, read and write etc. But as far as I understand your comment "use a DbContext instance for a single unit-of-work, and then dispose of it" I should never do that.

So to keep it simple:
How many queries, in your example, is the best practice for a single dbcontext when opened and closed?

AFAIK when having the usecase "Delete a subentity, then read the entity", I would do both queries in a single dbcontext - right?
But with this I would accur the bug, that the soft-detelted subentity is still in the read....

**Comment by ajcvickers** [comment]
@PassionateDeveloper86 What, exactly, is the change to the database that you are attempting to make?
