### ISSUE TITLE
Sqlite Geometry insert via command as parameter throws: violates Geometry constraint

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#30890]
## File an error
Exception:

> SQLite Error 19: 'Address.Location violates Geometry constraint [geom-type or SRID not allowed]'.'

### Include your code
```C#
// Entity
public class Address
{
    public int AddressId { get; set; } // autoIncrement 
    public string Street { get; set; } = null!;
    public Geometry Location { get; set; } = null!;
}
```
```C#
// Context options config
optionsBuilder.UseSqlite(connectionString, opt =>
  {
      opt.UseNetTopologySuite();
  });
```
```C#
// code that throws an Error on ExecuteNonQuery (analogous code works fine when there is no spatial type)
context.Database.OpenConnection();
var connection = return (SqliteConnection)context.Database.GetDbConnection();
transaction = (SqliteTransaction)connection.BeginTransaction();

SqliteCommand command = connection.CreateCommand();
command.Transaction = transaction;
command.CommandText = "INSERT INTO [Address] ([Location], [Street]) VALUES (@Location, @Street)";

parameter1 = new SqliteParameter("@Location", SqliteType.Blob); // tried also with DbType.Binary and to add 3rd arg size, but still same error
parameter1.Value = new Point(52, 13).AsBinary(); // tries also with ToBinary, no effect
parameter2 = new SqliteParameter(@Street", SqliteType.Text);
parameter2.Value = "Some Str. N";

command.Parameters.Add(parameter1);
command.Parameters.Add(parameter2);

command.Prepare();
command.ExecuteNonQuery();

transaction.Commit();
```
```C#
// When used with EF like bellow then it WORKS !, so the issue seems to be in parameter config but not sure what is the solution.
context.Addresses.Add(newAddress { Street = "Some Str. N", Location = new Point(52, 13) });
context.SaveChanges();
```

### Include version information
Nuget Microsoft.EntityFrameworkCore.Sqlite.Core 7.0.5
Target framework: .NET 7.0
Sqlite v: 3.35.5
Operating system: Windows 11 Pro

**Comment by bricelam** [comment]
> parameter1.Value = new Point(52, 13).AsBinary(); // tries also with ToBinary, no effect

This is passing the WKB directly into SpatiaLite. SpatiaLite uses its own binary format to store geometry values. When working with SqliteCommand directly, you have to convert the values to SpatiaLite's binary format yourself using GaiaGeoWriter (and GaiaGeoReader for any results):

```cs
parameter1.Value = new GaiaGeoWriter().Write(new Point(52, 13));
```

EF Core automatically performs this conversion for you. You should be able to do this instead:

```cs
context.Database.ExecuteSqlRaw(
    "INSERT INTO [Address] ([Location], [Street]) VALUES ({0}, {1})",
    new Point(52, 13),
    "Some Str. N");
```

**Comment by roji** [comment]
ExecuteSqlRaw and command.ExecuteNonQuery are very similar:

* Both are vulnerable to SQL injection, and you must take care to use SQL parameterization and not include user data in the SQL (or sanitize it beforehand). Note that there's ExecuteSql (without Raw) which accepts a FormattableString, and which provides protection against SQL injection - this is generally recommended for safety (in versions before 7.0, this is called ExecuteSqlInterpolated).
* ExecuteNonQuery *may* perform slightly better (since it's the lower-level ADO.NET function and ExecuteSqlRaw is a higher-level EF API using ADO.NET), but that's unlikely to affect actual user applications (benchmark to get a precise answer).
* "ability to be in Transaction scope with multiple inserts" - not sure exactly what this refers to, but there shouldn't be a difference between the two methods.

**Comment by borisdj** [comment]
Probably will keep it with _ExecuteNonQuery_, for max efficiency.

**Comment by borisdj** [comment]
@bricelam to extend the same question.
If there would also be type `LineString` how to make this work then?
prop: `public LineString GeoLine { get; set; } = null!;`
value: `address.GeoLine = new LineString(new List<Coordinate> { new Coordinate(52, 13), new Coordinate(50, 12) }.ToArray());`

Have tried with
`param.Value = new GaiaGeoWriter().Write((Geometry)value);`
also with
`param.Value = new GaiaGeoWriter().Write((LineString)value);`
but getting

> 'SQLite Error 19: 'Address.GeoLine violates Geometry constraint [geom-type or SRID

**Comment by bricelam** [comment]
@borisdj The error indicates that you may have specified the wrong SRID for the linestring.
