### ISSUE TITLE
EFCore 7  - Some JSON GIT tests removed from EFCore 7?

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#30899]
I see following git tests are not present in either of the EFCore 7 released versions. They are present in EFCore 8 preview version.
```
JsonQuerySqlServerTest.Json_collection_element_access_in_predicate_using_ElementAt
JsonQuerySqlServerTest.Json_collection_element_access_in_predicate_nested_mix
JsonQuerySqlServerTest.Json_boolean_predicate
```
It seems earlier they were included in efcore 7 development code. Is my understanding correct?
If yes, Please could someone clarify why they have been removed in EFCore 7.
Are these features/LINQs not supported in EFCore 7 and will be supported in EFCore 8?
Or is there some other reason?

**Comment by roji** [comment]
Using git blame shows that test Json_collection_element_access_in_predicate_using_ElementAt was added in commit 94be38cf686; this is the implementation of issue https://github.com/dotnet/efcore/issues/28648, which was release in 8.0-preview1. So this is functionality which was added for 8.0.
