### ISSUE TITLE
[Sqlite] `PRAGMA journal_mode=WAL;` no work!

### ISSUE THREAD

**Issue by Cricle** [dotnet/efcore#30900]
### Include your code

Execute the sql PRAGMA journal_mode=WAL;
I will got result delete, not WAL.

### Include stack traces

None.

### Include version information

Microsoft.Data.Sqlite version:
Target framework: .NET 6.0
Operating system: win10

 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by bricelam** [comment]
Are you inside a transaction? You can't change the journal mode inside a transaction.

**Comment by Cricle** [comment]
I tried to separate the following simple code, but during runtime, the output was `wsl`. My runtime environment system and package version are exactly the same, but when integrated into the system for use, it always returns `delete` instead of `wal`.

And I'm pretty sure I'm not doing it in a transaction.

```csharp
var dir = new DirectoryInfo("sqlites");
if (!dir.Exists)
{
    dir.Create();
}//I will save the sqlite file in other directory
using (var conn=new SqliteConnection("Data source=sqlites/a.db"))
{
    conn.Open();
    using (var comm = conn.CreateCommand())
    {
        comm.CommandText = "SELECT true";//I try to create database file by use this command
        comm.Prepare();
        comm.ExecuteNonQuery();
    }
    using (var comm = conn.CreateCommand())
    {
        comm.CommandText = "PRAGMA journal_mode=WAL;";
        comm.Prepare();
        using (var reader = comm.ExecuteReader())
        {
            reader.Read();
            Console.WriteLine(reader[0]);
        }
    }
}
```

**Comment by Cricle** [comment]
I am very sorry, I made a mistake in connecting the string while executing the switch wal command.
