### ISSUE TITLE
How to disable any conventions related to relationship discovery?

### ISSUE THREAD

**Issue by Abdragiz** [dotnet/efcore#30906]
Repost from https://stackoverflow.com/q/76263986/16478093
I have model with one-to-one and one-to-many relationships similar to this:

```C#
public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Author Author { get; set; } // one-to-one reference navigation
    public ICollection<Post> Posts { get; } // one-to-many collection navigation
}
public class Author
{
    public int Id { get; set; }
    public string Name { get; set; }
}
public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }
}
```

I want to create two migrations for this model: one with basic CREATE TABLE sql statements and another with foreign keys and constrains according to model relationships, but added relationship navigations are automatically discovered and included in initial migration.

I tried two ways:

1. Disable relationship discovery by ```[NotMapped]``` attribute or by ```EntityTypeBuilder<TEntity>.Ignore()``` method. I think it will work, but I need to find ALL relationship navigations in my code, add ```[NotMapped]``` attribute, create initial migration, remove ALL added attributes and then create relationships migration.

2. Disable relationship discovery convention by removing ```RelationshipDiscoveryConvention``` in ```ConfigureConventions``` method.

```C#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    ArgumentNullException.ThrowIfNull(configurationBuilder);
    configurationBuilder.Conventions.Remove(typeof(RelationshipDiscoveryConvention));
}
```

But after disabling ```RelationshipDiscoveryConvention``` I got new error, similar to this:

```Unable to determine the relationship represented by navigation 'Blog.Posts' of type 'ICollection<Post>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.```

So, removing ```RelationshipDiscoveryConvention``` does not actually disable relationship discovery but disables configuring class properties as relationship navigations.

What convention I need to remove to disable relationship discovery?

**Comment by ajcvickers** [comment]
@Abdragiz This is probably not going to be easy, and likely to be fragile. Can you provide more details on why you want to, "create two migrations for this model: one with basic CREATE TABLE sql statements and another with foreign keys and constrains according to model relationships?"

**Comment by Abdragiz** [comment]
I'm currently just testing things, but I need to populate a database with data. According to https://www.postgresql.org/docs/current/populate.html it's better to load data into a database that doesn't have indexes and foreign key constraints.

So I wanted to populate database like this:
```C#
IMigrator migrator = dbContext.GetInfrastructure().GetRequiredService<IMigrator>();
await migrator.MigrateAsync("InitialCreate").ConfigureAwait(false); // apply a migration that only has CREATE TABLE statements
ImportDataAsync(dbContext);
dbContext.Database.MigrateAsync() // apply migrations that add indexes, foreign key constraints, etc.
```

**Comment by ajcvickers** [comment]
@Abdragiz How much data do you have?

@roji Any thoughts on this from a PostgreSQL perspective?

**Comment by Abdragiz** [comment]
By the way, I found out about RelationshipDiscoveryConvention
     from here https://github.com/dotnet/efcore/issues/27647#issuecomment-1069420819.

**Comment by Abdragiz** [comment]
@ajcvickers 
> How much data do you have?

About 300 GB of xml files.

**Comment by roji** [comment]
It's true that when bulk-loading massive amounts of data, it's generally recommended to remove any constraints/indexes and re-add them after the procedure, since checking/updating them during the import takes more time. IIRC the same is probably true with SQL Server as well.

But in general, rather than trying to tweak the conventions to remove the relationships, I'd recommend generating a SQL script instead and doing the tweaking there... The bulk import process is likely to be single-time only, so there's not much value in getting EF to generate exactly the migration you want (without foreign keys) just to add them right back in the next migration...

**Comment by Abdragiz** [comment]
Ok, i'll look into it.

**Comment by great-fed** [comment]
If I use multiple DbContexts for my database I have to manually ignore all the relations with entities not included in smaller contexts? No workaround to prevent exceptions like "System.InvalidOperationException: Unable to determine the relationship represented by navigation ..." ?
