### ISSUE TITLE
How to insert item without track by EFCore

### ISSUE THREAD

**Issue by Flithor** [dotnet/efcore#30901]
I'm testing on insert 100M item on 30+field table, and one of field has auto-generate value in database.
I found that EFCore always query the auto-generate field value of the item just inserted after each insert due to the existence of the database generated value, which caused insert unusually inefficient.

**Comment by ajcvickers** [comment]
Duplicate of #29897

**Comment by Flithor** [comment]
@ajcvickers Is there any way to stop EFCore to query the database generated values after each insert?

**Comment by ajcvickers** [comment]
Not currently.

**Comment by roji** [comment]
@Flithor I'm generally not aware of a case where the fetching of the database-generated ID on its own significantly slows down insertion - is this something you've actually verified in benchmarking? If so, can you please share that?
