### ISSUE TITLE
List is not saving to database

### ISSUE THREAD

**Issue by cambo2015** [dotnet/efcore#30918]
## Ask a question
I am trying to save a list to the database using a model but it's not saving. I am using SQLite as a database on a mac using vs code.
Any help is appreciated

#### Here is  my code

```C#
public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
    }


public class UserPurchases
    {
        [Key]
        public int Id { get; set; }
        public ICollection<Product>? Products { get; set; }
        public string? UserId { get; set; }

    }
```
#### How I call the Code
```C#
var product = FindProduct(li.Description, (float)li.Price.UnitAmount, db);// create user payment
var userPurchases = new UserPurchases(){
      UserId = id,
       Products = new List<Product>{
       product
        },
 };
db.UserPurchases.Add(userPurchases);
await db.SaveChangesAsync();

public Product FindProduct(string name, float price, ApplicationDbContext db)
    {
        var product = db.Products.FirstOrDefault(x => x.Name == name);

        if (product == null)
        { 
            product = new Product
            {
                Name = name,
                Price = price,
            };
            return product;
        }
        return product;
    }
```

### Include stack traces

No stack traces.

### Include verbose output
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@p0='?' (Size = 36)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "UserPurchases" ("UserId")
      VALUES (@p0)
      RETURNING "Id";
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@p1='?' (Size = 6), @p2='?' (DbType = Single), @p3='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Products" ("Name", "Price", "UserPurchasesId")
      VALUES (@p1, @p2, @p3)
      RETURNING "Id";

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7
Operating system: Mac OS
IDE: VS Code

**Comment by roji** [comment]
@cambo2015 the SQL log you posted seems to indicate that INSERTs are happening correctly, so it isn't clear exactly what the problem is. Best would be to post a minimal, runnable code sample which we can run and which shows the problem.

**Comment by cambo2015** [comment]
I wonder if I am misunderstanding how it saves the data. The product should get saved to the list in userPurchases right? But when I look in my sql application tables the Product is saved to its own table and no list is found in the userPurchases. Is this how the data is supposed to save?

**Comment by cambo2015** [comment]
I figured it out. I had to change my code to the .Include. Here is what I changed it to.
```C#
void ShowUserPurchases(ApplicationDbContext db)
{
    var userPurchases = db.UserPurchases.Include(x => x.Products).ToList();//I changed this line
    for (var i = 0; i < userPurchases.Count; i++)
    {
        var up = userPurchases[i];
        if (up.Products != null)
        {
            var p = up.Products.ToList();
            for (int j = 0; j < p?.Count; j++)
            {
                var purchase = p[j];
                Console.WriteLine($"Product Name: {purchase.Name}");
            }
        }
        else
        {
            Console.WriteLine($"UserPurchases at position {i} does not contain products. ");
        }

    }
}
```

I also found this website helpful: https://www.learnentityframeworkcore.com/dbset/querying-data. I was confused because I looked in the SQLiteStudio and I didn't see a product list in with my UserPurchasesTable, but I saw where the Products table had UserProduct Id's. I guess this is how ef core saves the data. I needed to use the .Include to include and retrieve the products list. Thanks

**Comment by roji** [comment]
@cambo2015 reading the documentation EF could help clarify the basic concepts; [this page](https://learn.microsoft.com/en-us/ef/core/modeling/relationships) discusses how relationships are represented in the database (i.e. separate table with a foreign key constraint), whereas [this page](https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager) discusses querying out related entities and Include.

**Comment by cambo2015** [comment]
Thanks @roji. I'll look at those.
