### ISSUE TITLE
Translate DegreesToRadians

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#30926]
Once https://github.com/dotnet/runtime/issues/86402 is available (and we target that version of .NET), we should translate those methods to SQL.

.NET | RadiansToDegrees | DegreesToRadians
--- | --- | ---
**SQL Server** | DEGREES | RADIANS
**Cosmos** | DEGREES | RADIANS
**SQLite** | degrees | radians
**PostgreSQL** | degrees | radians
**MySQL** | DEGREES | RADIANS
**Db2** | DEGREES | RADIANS

**Comment by ErikEJ** [comment]
@bricelam Gentel reminder to get this documented :smile:

**Comment by bricelam** [comment]
Yep, I usually do all the new method/member translators in one big pass around RC1
