### ISSUE TITLE
OUTPUT clause and triggers

### ISSUE THREAD

**Issue by TimurMannapov** [dotnet/efcore#30932]
Hello, 
While switching to EF core we stumbled upon breaking change regarding [OUTPUT and triggers](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sqlserver-tables-with-triggers) 
We are not using triggers, except for database migrations (own developed tool). For migration, triggers are created for the time of migration to track changes and dropped afterwards. So 99.9999% of time there are no triggers and we would like to have more performant queries with OUTPUT.

Question:
Is it possible to custumize(settings or extra development) EF to gracefully fallback to old query generation, once Microsoft.EntityFrameworkCore.DbUpdateException is thrown? So if Microsoft.EntityFrameworkCore.DbUpdateException thrown, old-style query is generated and executed (everything is hidden from the caller).
Main target is to avoid app redeployment only for the purpose of migration (with OUTPUT generation enabled/disabled) as such deployments violates our CI/CD pipeline.

EF Core version: 7.0
Database provider: Sql Server 2017/2019
Target framework: (e.g. .NET 6.0)

**Comment by roji** [comment]
> Is it possible to custumize(settings or extra development) EF to gracefully fallback to old query generation, once Microsoft.EntityFrameworkCore.DbUpdateException is thrown?

No, this isn't possible; the error could have various side effects which wouldn't make this work reliably.

However, it should be possible for you to switch off OUTPUT only for migrations - IIRC we added a way to check whether the current program is executing from the design-time tools (e.g. add migration), @bricelam @ajcvickers do you remember the API here?

**Comment by TimurMannapov** [comment]
Migration tool is standalone tool and is generating raw sql for migration, it doesn't use ef.core

May be it is possible to provide a hint on how to generate queries at runtime? So once Microsoft.EntityFrameworkCore.DbUpdateException  will be caught by user code, we can set some variable to indicate that old style quries should be generated and retry processing.

**Comment by roji** [comment]
I'd recommend exposing some way to know that you're running within your migration tool (e.g. a static global flag), and tweaking your model configuration to opt out of the OUTPUT clause based on that.

**Comment by roji** [comment]
Are you saying that you *sometimes* have triggers added (and than dropped) to your production database tables, against which your ASP.NET application runs? If so, then yeah - you'll need to disable the OUTPUT clause in your application.

**Comment by TimurMannapov** [comment]
Yes, exactly like this.
Thanks for help!
