### ISSUE TITLE
In 8.0.0-preview.4.23259.3 version, Can't migrate db.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/efcore#30933]
### Include your code

```C#
using var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope();
        serviceScope.ServiceProvider
        .GetService<DbCxt>()
        .Database.Migrate();
```

Migrate() not found.

### Include provider and version information

EF Core version: 8.0.0-preview.4.23259.3
Database provider: npgsql
Target framework: .net8 preview4
Operating system: win11 x64
IDE: Visual Studio 2022 17.7 preview1

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MiyamuraMiyako** [comment]
@ajcvickers In this [page](https://learn.microsoft.com/zh-cn/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli), 
![图片](https://github.com/dotnet/efcore/assets/10345361/2b4c864a-4f83-42d2-a5ea-241a7ef991cd)
this method not found in 8.0.0-preview.4.23259.3

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MiyamuraMiyako** [comment]
@ajcvickers I restarted Visual Studio and the problem disappeared.
