### ISSUE TITLE
In-query Filtered Include()?

### ISSUE THREAD

**Issue by brent-russell** [dotnet/efcore#3093]
``` C#
if (includeChildren)
{
    if (activeOnly)
    {
        query = query.Include(t => t.Children.Where(c => c.IsActive));
```

Are there any plans to support the above syntax, or another method to filter Include() content in-query?

**Comment by Suchiman** [comment]
:+1: I'd really like to see something like this, always bothered me in EF6.

**Comment by rowanmiller** [comment]
Duplicate of https://github.com/aspnet/EntityFramework/issues/1833
