### ISSUE TITLE
EF core7 will multi resultset.

### ISSUE THREAD

**Issue by xheox** [dotnet/efcore#30940]
Hi, 
Working on a leagacy project where refactoring the SQL is not a priority and I need to use few stored procs with MultiResultSet. 
What is the best way to do this in EF 7 ?
With EF core 6 I used this code :  https://stackoverflow.com/questions/41740636/working-with-multiple-resultset-in-net-core
However when upgrading to NET7.0 and EF core7 I get an error because "IRelationalValueBufferFactoryFactory" (and its sub classes) is not there anymore. 
I could not find any doc about this. 
Thanks

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 7.0)

**Comment by ErikEJ** [comment]
EF Core Power Tools can map multiple stored procedure result sets for you.

**Comment by xheox** [comment]
Thanks @ErikEJ. 
I actually used in net3.1, 5 and 6. 
For this project I used with net6.0 first and for some reason it did not map the SPs with results sets :  it returned some resultTypes with empty definitions (no fileds). That's why I did that "myself" (using the SOF link above)
I will update Ef Power tools and give it a try. 
Thanks again

**Comment by ErikEJ** [comment]
@xheox Please create an issue if it does not work, there are some ways to tweak the result set discovery proces.

**Comment by xheox** [comment]
I cannot share any code for this project so it did not make sense to open an issue. 
I will be grateful if you could point me to the part of documentation about tweaking the discovery process.

**Comment by ErikEJ** [comment]
Sure, you can find it in the docs here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures

**Comment by roji** [comment]
> I cannot share any code for this project so it did not make sense to open an issue.

The standard thing here is for you to create a standalone, minimal code repro that isn't part of your project, so that it can be shared. Many times, while attempting to create such a repro, users realize what it is that they did wrong.

**Comment by xheox** [comment]
Thanks @roji, this is what I do usually when I start refactoring anyways. (class library and reverse engineer there)
In this case however, I first suspected the issue was in the SPs code itself and that I could not share. After reading more and watching the community standup about EF power tools, it is expected that I get an empty result class. ( and just the first result in the result set).
I will try the couple global settings and see if that works when I get back to it.
I guess this could be closed then.

**Comment by xheox** [comment]
closing ...
