### ISSUE TITLE
Connection To SQL Server

### ISSUE THREAD

**Issue by miroslavsiska** [dotnet/efcore#3094]
Hi, I have this problem with EF7-beta 7
Migration is done, but after command: dnx ef database update 
Error Message: Login failed. The Login is from an untrusted domain and cannot be used with Windows Authentication.
See my connection String: 

```
  var connection = @"Server=tcp:happycone.cloudapp.net,1433;Database=DBNAME;User ID=USERNAME;Password=MYPASSWORD;Trusted_Connection=True;MultipleActiveResultSets=true;";

     services.AddEntityFramework()
          .AddSqlServer()
          .AddDbContext<ApplicationDbContext>(options =>
              options.UseSqlServer(connection));
```

Error Number: 18452,State:1,Class:14

Working with modification of connection string:
Trusted_Connection=False;
Encrypt=False;
Connection Timeout=30;

**Comment by rowanmiller** [comment]
@miroslavsiska you have specified `Trusted_Connection=True` in the connection string which means it will try to use Windows Auth. Given you also have a username and password, you should just remove this.
