### ISSUE TITLE
Make migrations .Designer file optional

### ISSUE THREAD

**Issue by kirchesch** [dotnet/efcore#30967]
Right now every migration I make, no matter how small it is, a .Designer file with the complete state of my database is created (including the persistent data (created on the DbContext with .HasData())).

I don't know why this is required since we already have a snapshot and the up()/down() file already contains all the changes from each migration.

And that is not the only problem, since each migration contains a snapshot it makes it harder to merge branches that developed at the same time.

 ---

A great solution would be to allow us to optionally disable migrations .Designer file.

**Comment by ajcvickers** [comment]
Note for triage: I know we discussed this recently, but I can't find where. Anybody remember?

**Comment by ajcvickers** [comment]
Discussion on this subject is here: https://github.com/dotnet/efcore/issues/2174#issuecomment-1450949232

**Comment by matheus-kirchesch-btor** [comment]
Hello @ajcvickers, thanks for informing me, is this something you guys plan on doing?

**Comment by ajcvickers** [comment]
@matheus-kirchesch-btor No, it's not something we plan on changing.
