### ISSUE TITLE
EF Core 7.0.6 release date

### ISSUE THREAD

**Issue by Mavox** [dotnet/efcore#30974]
Hi, not sure if this is the right place to ask these kinds of questions, but it's the only one I could find.

A project I'm working on are having an issue that will be solved by a change coming in EF core 7.0.6. However we are a bit tight on time and are concidering making a workaround depending on when EF core 7.0.6 is expected to be released.

Therefore I thought I'd ask the question here (as there is no date set on the milestone for EF core 7.0.6) Is there a release date set for version 7.0.6? Or is there at least an estimation of when a release could happen?

Also as a followup question, do releases of patches follow some sort of pattern? Judging by earlier patch releases in EF core there seems to have come a new patch about once a month or so, but for all I know, that might just be a coincidence.

If this is the wrong place to ask these kinds of questions, then I'd be very grateful if I could be pointed in the right direction

**Comment by roji** [comment]
EF Core (and .NET) patch versions are released roughly every month; there are some exceptions but that's the general schedule (you can see this by looking at the [nuget package history](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore)). Since 7.0.5 was released 10 days ago, expect 7.0.3 in around 20 days.

**Comment by Mavox** [comment]
Thank you for the quick reply, that will help us decide wether to make a workaround meanwhile :) .

**Comment by ErikEJ** [comment]
@roji 7.0.5 was actually released on April 11! So 7.0.6 was expected second Tuesday but was skipped due to ?? (BUILD) - and is now expected second Tuesday in June, I guess.

**Comment by roji** [comment]
Ah sorry, I misread the nuget history and looked at 8.0.0-preview.4. I don't think 7.0.6 was skipped, but maybe slightly delayed...

**Comment by Mavox** [comment]
I thought I saw a different release date for 7.0.5 somewhere, thanks for clearing it up @ErikEJ :)
