### ISSUE TITLE
How to extend EF Core to conditionally modify Select, Insert and Update expressions for certain tables?

### ISSUE THREAD

**Issue by ianclegg** [dotnet/efcore#30977]
im looking for some advice around developing an extension for ef core using postgres. we have a mature app with tables storing 'temporal data' and they have 'effective from' and 'effective to' columns so we can determine which rows were valid at a given point in time. As result, all the linq expressions involving these entities require 'where' expressions constraining these two fields. having looked at the temporal table support for SqlServer i think we could do something similar and handle this in an extension.

 - define some annotations like `IsTemporal`, `PeriodStartColumnName`, etc
 - add some extension methods to enable us to add these annotations to the aforementioned tables when building out the model

however, since postgres does not have integrated support for temporal tables (`FOR SYSTEM_TIME AS OF`...) we would probably need to register an `IQueryTranslation(Pre/Post)Processor` derived from `RelationalQueryTranslation(Pre/Post)Processor` (rather than a SqlGenerator) that would update the expression tree (override `VisitExtension` for `SelectExpressions`) and use the `Tables` property of the `SelectExpression` to update the `Predicate` SqlExpression to include our Where 'effective from' and 'effective to', again guided by the table annotations?

the more complex case is an update of these tables, we currently expire a row by setting the effective_to and insert a new row with the new data - to do this we would need to generate an update and an insert - I have no idea how to approach this

- am I going about this the right way? I notice that `RelationalQueryPreprocessor` has a `NormalizeQueryableMethod`, how is this intended to be used and is this a better fit?
- in the case of a select, how do you determine whether this should be a `IQueryTranslationPreProcessor` or `IQueryTranslationPostProcessor`
- what are your thoughts on building an extension for the 'update' scenario? 

and of course, many thanks for the great work!

**Comment by roji** [comment]
@ianclegg this kind of deep integration with the query pipeline is probably far from trivial, as you've probably understood. 

I'd actually recommend looking at the SQL Server source to see how that's implemented, and take inspiration from there. I think the general gist would be to have e.g. an TemporalAsOf() extension method over DbSet which generates a temporal query root expression (extending EntityQueryRootExpression), and then recognize that in your overridden version of NpgsqlQueryableMethodTranslatingExpressionVisitor and inject the temporal predicate you want at that point. If that matches what you want, simply replacing NpgsqlQueryableMethodTranslatingExpressionVisitor should probably be enough.

For the update side, I'm not 100% where would be the best place to integrate your logic... You could replace the IModificationCommandFactory, overriding CreateModificationCommand to create your own IModificationCommands where you'd add the setting of the temporal properties. If/when this becomes more relevant (e.g. the query side is done), I can ask the other team members for advise on how best to do this.

/cc @maumar @AndrySvyryd

**Comment by ianclegg** [comment]
@roji thanks for the quick response and pointing out `NpgsqlQueryableMethodTranslatingExpressionVisitor` - as you say not exactly trivial in terms of LoC, but it doesn't feel too complex
