### ISSUE TITLE
Database.SqlQuery<bool> does not work

### ISSUE THREAD

**Issue by exyi** [dotnet/efcore#30979]
Documentation suggests that the `Database.SqlQuery` method can be used to retrieve primitive values from the database: https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#querying-scalar-non-entity-types
However, I can't get it to work with any primitive types I tried.

It seems that EF always expect a column named `"Value"` on the primitive types. It doesn't even respect the snake_case naming convention I configured. Both of the following queries fail:

```csharp
var a = dbContext.Database.SqlQuery<bool>($"SELECT 1 = 1").Single()
var b = dbContext.Database.SqlQuery<int>($"SELECT 1").Single()
```

The error message on Sqlite:

```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "t"."Value"
      FROM (
          SELECT 1 = 1
      ) AS "t"
      LIMIT 2
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'SqlQuery.Data.ApplicationDbContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 17: 'no such column: t.Value'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
```

On Npgsql, it's very similar.

### Include provider and version information

EF Core version: 7.0.3, with same behavior observed on 8.0.0-preview.4.23259.3
Database provider: Similar behavior on Npgsql and Sqlite
Target framework: net7.0
Operating system: Linux (Arch)

Repro web app from template is attached: 
[SqlQuery.tar.gz](https://github.com/dotnet/efcore/files/11578394/SqlQuery.tar.gz)
 (navigate to / and it crashes; if it worked, it would print `true`)

**Comment by roji** [comment]
> It seems that EF always expect a column named "Value" on the primitive types. It doesn't even respect the snake_case naming convention I configured.

This is the [documented behavior](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#querying-scalar-non-entity-types):

> You can also compose LINQ operators over your SQL query. However, since your SQL becomes a subquery whose output column needs to be referenced by the SQL EF adds, you must name the output column Value.

It's your responsibility to make sure that your SQL projects out a column with the exact name `Value`. You can do this easily as followed:

```c#
var b = dbContext.Database.SqlQuery<int>("""SELECT 1 AS "Value"""").Single()
```

**Comment by exyi** [comment]
Ok, I see, sorry for spam. I didn't try to quote the name `"Value"`.

But still, I don't get why is it needed when I don't chain any operations on the selected value. Does `Single()` count as "LINQ operators over your SQL query"? I understand it wants to put `LIMIT 2` on the query, but that could be just as well done as `select * from (...) limit 2`

**Comment by roji** [comment]
> Does Single() count as "LINQ operators over your SQL query"?

Absolutely.

> I understand it wants to put LIMIT 2 on the query, but that could be just as well done as select * from (...) limit 2

In this very particular case, it could have been technically possible to use star (*) - but EF never does that in general case, since the column order becomes unknown (or rather, dependent on the table column order as it was created). We don't try to do different behavior here for Single(), compared to any other LINQ operator(s); if you compose anything over you raw SQL, it's your responsible to project `Value`.

**Comment by exyi** [comment]
Ok :shrug:  I don't want to "compose" anything over the query, I just want to get the (single) value from the DB and I'm not exactly happy about writing `as "Value"` after each query :/
