### ISSUE TITLE
Cosmos: Is it possible to re-add the Discriminator constraint when using FromSqlRaw on specific set?

### ISSUE THREAD

**Issue by JamesBroadberry** [dotnet/efcore#30997]
When querying against a DbSet, we'd like to further limit some fields using some custom SQL since EF doesn't currently support what we need.

However, when doing so, we've noticed that the discriminator field gets dropped from the query (intentionally as part of #26124)

If we have entities such as "Animals" which have the property `List<string> Tags` and we want to query where Tags contain some element, we have to currently use FromSqlRaw on the set like so: `dbContext.Set<Animal>.FromSqlRaw(SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail'))`

If we want to provide a repository wrapping EF, limiting entities by tags like `IRepository<T> where T: Animal` which has method `GetAnimalsByTag(string tag)`, we can do so using the above raw SQL. 

If we leave the Discriminator field out of the query and did something like `dbContext.Set<Tiger>.FromSqlRaw(SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail'))`, I've not tested what happens, but the generated SQL won't limit the results to "Tiger" objects. Even then, when querying `dbContext.Set<Animal>`, this doesn't guarantee that the entities returned have to be of type "Animal".

However, since the discriminator doesn't get applied, it makes things difficult. Is there a way to add it back based on the set being queried? We've noticed that EF does a great job at determining which discriminators to include when there are multiple inheritors.

Since we've specified the DbSet that we're querying, is there a way I can get EF to apply the discriminator constraint? I'd understand the decision to remove it if we were just writing any raw SQL, but it doesn't make sense given that we're in the context of a DbSet, unless I'm missing something.

I understand that primitive collection querying is upcoming, but this is just an example of where we'd like to use FromSqlRaw.

### Provider and version information

EF Core version: 6.0.6
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 6.0
Operating system: Windows 11
IDE: JetBrains Rider 2023.1.2

**Comment by ajcvickers** [comment]
@JamesBroadberry 

> Is there a way to add it back based on the set being queried?

Composition over the raw SQL can be used to add back the filter. For example:

```C#
var results = context.Tigers
    .FromSqlRaw("SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail')")
    .Where(t => EF.Property<string>(t, "Discriminator") == nameof(Tiger))
    .ToList();
```

```sql
SELECT c
FROM (
     SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail')
) c
WHERE (c["Discriminator"] = "Tiger")
```

Note for triage: Ideally, `OfType` could be used here. It works used when using a `DbSet` of `Animal`. For example:

```C#
context.Animals
    .FromSqlRaw("SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail')")
    .OfType<Tiger>()
    .ToList();
```

```sql
SELECT c
FROM (
    SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail')
) c
WHERE (c["Discriminator"] = "Tiger")
```

But is doesn't work when the `DbSet` is of type `Tiger`:

```C#
context.Tigers
    .FromSqlRaw("SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail')")
    .OfType<Tiger>()
    .ToList();
```

```sql
SELECT c
FROM (
    SELECT * FROM c WHERE ARRAY_CONTAINS(c.Tags, 'long-tail')
) c
```

**Comment by JamesBroadberry** [comment]
@ajcvickers Thanks for the response. Ideally, we'd also like to include other types, for example, if we were to do `DbSet<Animal>`, the generated SQL goes something like `WHERE c.Discriminator IN ('Tiger', 'Lion', 'Bear')` and that's missing by just adding a single discriminator to the query in your example.

**Comment by ajcvickers** [comment]
We discussed this, and _technically_, the raw SQL query for a `DbSet<Tiger>` should be written to only return `Tiger` instances. This is why `OfType` is ignored--the SQL must already be doing this filtering. By this logic, the explicit `Where` clause should also not be needed, but we are unlikely to optimize that away, and it seems like a reasonable way of adding to the filter for cases where the raw SQL is returning more than it should.
