### ISSUE TITLE
DBContext is not thread-safe. How to correctly use EFCore in a multi-threaded environment? Is it not recommended to use EFCore in multi-threaded programs?

### ISSUE THREAD

**Issue by luy710** [dotnet/efcore#30995]
DBContext is not thread-safe. How to correctly use EFCore in a multi-threaded environment? Is it not recommended to use EFCore in multi-threaded programs?

**Comment by roji** [comment]
The correct way is simply to instantiate a new DbContext for each thread that needs to perform a database operation, just like each thread needs its own database connection. Do you have any concerns with doing that?

**Comment by luy710** [comment]
> Reference i

I currently need to scan images in real-time, approximately around 100 per second, and store the results in a database. I'm using asynchronous functions to improve efficiency and make them not wait for each scan. However, I believe that instantiating a new DbContext for each asynchronous function would result in excessive performance overhead. Additionally, it doesn't feel elegant to instantiate a new DbContext whenever the asynchronous function needs to perform a database operation.

**Comment by luy710** [comment]
> The correct way is simply to instantiate a new DbContext for each thread that needs to perform a database operation, just like each thread needs its own database connection. Do you have any concerns with doing that?

I currently need to scan images in real-time, approximately around 100 per second, and store the results in a database. I'm using asynchronous functions to improve efficiency and make them not wait for each scan. However, I believe that instantiating a new DbContext for each asynchronous function would result in excessive performance overhead. Additionally, it doesn't feel elegant to instantiate a new DbContext whenever the asynchronous function needs to perform a database operation.

**Comment by luy710** [comment]
eg:
`using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp
{
    internal class Program
    {
        private static IServiceProvider _serviceProvider;

        public static void Main(string[] args)
        {
            var services = new ServiceCollection();
            ConfigureServices(services);
            _serviceProvider = services.BuildServiceProvider();

            var testService = _serviceProvider.GetRequiredService<TestService>();
            // Time-consuming and real-time execution, simulate testing 5 times.
            for (int i = 0; i < 5; i++)
            {
                var th = testService.GetAllAsync();
            }

            Console.ReadLine();
        }

        private static void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MyDbContext>(options =>
            {
                options.UseSqlServer("Data Source=.;Initial Catalog=Photo;User ID=sa;Password=sa;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False");
            });
            services.AddScoped<TestRepository>();
            services.AddScoped<TestService>();
        }

    }

    /// <summary>
    /// service
    /// </summary>
    public class TestService
    {
        private readonly TestRepository _testRepository;
        private readonly IServiceProvider _serviceProvider;
        public TestService(TestRepository testRepository, IServiceProvider serviceProvider)
        {
            _testRepository = testRepository;
            _serviceProvider = serviceProvider;
        }
        public async Task GetAllAsync()
        {
            Console.WriteLine("start no");
            await Task.Delay(10000);

            var result = _testRepository.GetAllAsync();


            Console.WriteLine("end  no");
            using (var scope = _serviceProvider.CreateScope())
            {
                var _testRepositoryScope = scope.ServiceProvider.GetRequiredService<TestRepository>();

                Console.WriteLine("start scope");
                var result2 = _testRepositoryScope.GetAllAsync();
                Console.WriteLine("end scope");

            }
        }
    }

    /// <summary>
    /// repository
    /// </summary>
    public class TestRepository
    {
        private readonly MyDbContext _dbContext;
        public TestRepository(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task GetAllAsync()
        {
            var query = _dbContext.PicResults.Where(p => string.IsNullOrWhiteSpace(p.Key));
            Thread.Sleep(2000);
            var lls = await query.ToListAsync();
            await _dbContext.Set<PicResult>().ToListAsync();
        }
    }

    /// <summary>
    /// entity
    /// </summary>
    public class PicResult
    {
        public int Id { get; set; }
        public string Key { get; set; } = "";
        public string? Value { get; set; }
    }
    /// <summary>
    /// dbcontext
    /// </summary>
    public class MyDbContext : DbContext
    {
        public DbSet<PicResult> PicResults { get; set; }
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
        }
    }
}`

**Comment by roji** [comment]
> Additionally, it doesn't feel elegant to instantiate a new DbContext whenever the asynchronous function needs to perform a database operation.

Keep in mind that each DbContext instance encapsulates an ADO.NET database connection (DbConnection), and database connections themselves aren't thread-safe since they (typically) use a TCP network connection. This is simply how networking works.

Regardless, EF has [DbContext pooling](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cexpression-api-with-constant#dbcontext-pooling) for when performance is important and you need lots of instances. If you use that feature, then getting a "new" DbContext costs almost nothing.

Finally, regardless of EF or databases, it's usually a pretty bad idea to spawn an infinite number of asynchronous tasks, which is what I think you have in mind above. You usually want to have a fixed number of threads, where the number is some function of your CPU cores; each thread loops and does work. Otherwise, you're creating a huge amount of parallel work, forcing lots of context switching both on your application server and in the database, and degrading performance.
