### ISSUE TITLE
[SCAFFOLDING] Wrong scaffolding with quirky composite primary key

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#31004]
```sql
CREATE TABLE [dbo].[PS_CasterLaserWidth](
	[Currentlaserwidth] [float] NULL,
	[updated] [datetime] NOT NULL,
	[TimeStamped] [timestamp] NOT NULL,
 CONSTRAINT [PK_PS_CasterLaserWidth] PRIMARY KEY CLUSTERED 
(
	[updated] ASC,
	[TimeStamped] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

Code generated with EF Core 7 scaffolding:

```csharp
public partial class PS_CasterLaserWidth
{
    public double? Currentlaserwidth { get; set; }

    public DateTime updated { get; set; }

    public byte[] TimeStamped { get; set; } = null!;
}

        modelBuilder.Entity<PS_CasterLaserWidth>(entity =>
        {
            entity.HasKey(e => new { e.updated, e.TimeStamped });

            entity.Property(e => e.updated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TimeStamped)
                .IsRowVersion()
                .IsConcurrencyToken();
        });
```

see https://github.com/ErikEJ/EFCorePowerTools/issues/1821#issuecomment-1569680665

**Comment by roji** [comment]
@ErikEJ what exactly is the problem above - the HasDefaultValueSql?

BTW regardless of scaffolding, having a rowversion column within the primary key isn't supported by EF at various levels. In general, a changing primary key isn't something that will work.

**Comment by ErikEJ** [comment]
@roji it is this:

```csharp
entity.Property(e => e.TimeStamped)
                .IsRowVersion()
                .IsConcurrencyToken();
```

Removing it fixes the runtime error, which I forgot to add:


`'The property 'TimeStamped' cannot be configured as 'ValueGeneratedOnUpdate' or 'ValueGeneratedOnAddOrUpdate' because it's part of a key and its value cannot be changed after the entity has been added to the store.'
`

**Comment by roji** [comment]
But the database column being scaffolded really is a timestamp, and so removing the above EF configuration would be incorrect, no? The error seems to be exactly right - it's telling you that the scaffolded database isn't compatible with EF as-is; if at that point the user wants to make the column non-timestamp, that's their decision, no?

**Comment by roji** [comment]
Yeah, there's definitely some schemas which EF cannot support, at least for the moment.

BTW I'm very curious how it works to have a rowversion as part of the composite key: any change to the row means that all foreign keys need to be immediately updated? It also means that the key can never be sent/stored somewhere else (e.g. sent to a web client), since it isn't stable... I wonder what's the motivation for doing something like this...

**Comment by KayakFisher205** [comment]
I sent this info to Erik and the best answer I can provide on the table structure is that in some cases, the data inserted into the Updated field was not unique. The data comes from a data acquisition system that captures every fast and in some cases, it is able to capture data faster than 1 ms. This caused the data to be duplicated according to the Updated primary key. The Timestamp was  added. In this case, what is the best option, drop the updated column and keep the Timestamp, or what would be the preferred suggestion.

**Comment by roji** [comment]
@KayakFisher205 the point of a primary key is usually to identify the row in a stable way - it's problematic for a primary key to change in this way. One way to do model your schema would be to just use a regular auto-incrementing identity number as your primary key - the database will ensure its uniqueness (another option is an auto-generated GUID). The imported data from your data acquisition system occupy all the other columns, but the primary key would be generated on insertion.

**Comment by ErikEJ** [comment]
@KayakFisher205 long or uniqueidentifier as primary key

**Comment by KayakFisher205** [comment]
Thanks to @roji  and @ErikEJ . Good information and I'll pass it on to the team.
