### ISSUE TITLE
Remove DISTINCT inside IN/EXISTS/set operations

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#31016]
When a subquery is in IN or EXISTS, DISTINCT has no effect and can be removed. The same is true of all set operations, with exception of Concat.

**Comment by ranma42** [comment]
I would like to tackle this

**Comment by roji** [comment]
Sure, go ahead!

**Comment by ranma42** [comment]
While working on this I noticed that there are other cases in which DISTINCT can be safely removed:
 - when `Take`ing 0 or 1 elements (in general, when limiting to 1 element with no skip; this includes `.First[OrDefault]()` & co)
 - when doing a `MAX` or `MIN` over the distinct

I will open other issues on this
