### ISSUE TITLE
Are there any best practices for seeding data only on a given environment?

### ISSUE THREAD

**Issue by alex-bello** [dotnet/efcore#31018]
I am using Code-First to generate our dbs and seed lookups that don't change very often. I would like to start using [Bogus](https://github.com/bchavez/Bogus) to generate identical fake data on our LocalDb, Dev, and Test environments. The problem I'm having is that seed data is inserted at the end of the `Up()` method of each migration we create. We generate up/down SQL scripts for each migration and run the same exact script on all environments to ensure our DBs are identical. Is there a way to split out the seed data specifically so we can run it only on local/dev/test? 

Here's what I've tried so far:

1. Create a new project in the solution that references our EFCore project.
2. Update our DbContext to 
    - Add an optional `Action<ModelBuilder> seedMethod` parameter to the constructor and a field `_seedMethod` to store the object if provided.
    - Updated the overridden `OnModelCreating(ModelBuilder builder)` with `if (_seedMethod != null) _seedMethod(builder);`
3. Create a new `IDesignTimeDbContextFactory<TDbContext>` in the new solution that:
    - Sets the option `options.MigrationsAssembly("[Name of Assembly]")` 
    - Returns a new TDbContext that passes the seed method to the TDbContext constructor with all the fake data we want to seed.

The issues I'm seeing so far are that the migrations from the main EFCore project don't exist in the new one so we have to copy them into the new project and change all the namespaces before generating the new Migration and DbScript. We'd have to do this every single time to keep them in sync and in my experience, that is not going to work long term. 

I also thought about maybe just creating a new DbContext `FakerDbContext : TDbContext` which overrides the `OnModelCreating(ModelBuilder builder)` method and then specifying the DbContext when running `dotnet ef ...`. However, that also seems like it would be messy to keep synchronized.

Thanks in advance!

### Provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: VSCode 1.78.2 & Visual Studio 2022 17.16.1

**Comment by ajcvickers** [comment]
@alex-bello Building seed data into the model often creates more problems than it solves. I would advise running some kind of initialization code to see the data appropriately, at which point that code can build/load the data as appropriate for the target platform.

**Comment by ajcvickers** [comment]
See also https://github.com/dotnet/efcore/issues/27959.

**Comment by alex-bello** [comment]
@ajcvickers Your response got me thinking and perhaps I can just update the `IDesignTimeDbContextFactory` to listen for an argument (`--seedDatabase`, for example) and only call the method that adds the seed data if it's true. We could just perform migrations as we normally would without including any of the fake seeding data. We'd generate migrations and scripts like we normally would. Then, when we need the fake data, we pass the arg. 

Not sure if it'll work as I expect it to, but will give it a try. I know it's not the best practice to do so but I want this to be as repeatable as possible. Thanks
