### ISSUE TITLE
Implement null semantics for comparison operators

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#31020]
We don't currently do any compensation for comparison operators (e.g. `a > b`). Note that the C# behavior for [lifted comparison operators](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#lifted-operators) is that the operator returns null if either (or both) the operands is null. We could make the SQL mimic the C# behavior by injecting IS NOT NULL checks in un-optimized contexts.

**Comment by maumar** [comment]
related: https://github.com/dotnet/efcore/issues/9544

**Comment by roji** [comment]
@ajcvickers I don't think this is (fully?) implemented, and #9544 was closed as out of scope... Should we reconsider?

**Comment by ajcvickers** [comment]
In my notes from last week I had it marked as close/dupe. But happy to keep it open.

**Comment by roji** [comment]
Let's see what @maumar says

**Comment by maumar** [comment]
fixed as part of https://github.com/dotnet/efcore/commit/b77d2f4f221fb7edd863deeb0dddc962ecb0ace5
