### ISSUE TITLE
Translate DateOnly.ToString() / TimeOnly.ToString() ??

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#31035]
Should it be added to ?:

https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs

**Comment by roji** [comment]
Yeah, seems like I forgot that...

**Comment by ajcvickers** [comment]
@ErikEJ Any chance of a PR?

**Comment by ErikEJ** [comment]
@ajcvickers Yes, if you can point me to the related tests, have a hard time finding them

**Comment by roji** [comment]
@ErikEJ the model where we added the DateOnly/TimeOnly tests is gears of war, so I think you want to add the tests to GearsOfWarQueryTestBase.

**Comment by sulton-max** [comment]
Hi. I'm Interested in contributing to EF Core and came across this issue. Could I work on it ?

I located the mentioned tests, such as assertions like `Where_datetimeoffset_day_component`. Is it how `DateOnly` should be tested ? I would appreciate some guidance on how to approach this testing and any specific considerations. Thanks

**Comment by roji** [comment]
@ErikEJ are you planning on doing this?

@sulton-max note that this is only about ToString support, IIRC Where_datetimeoffset_day_component isn't about that.

**Comment by sulton-max** [comment]
@roji ok, I added `DateOnly` to the dictionary of `TypeMapping` in `SqlServerObjectToStringTranslator`. How and where I should add tests for this ?

**Comment by ErikEJ** [comment]
@roji Yes  I was planning to do this in July.

**Comment by sulton-max** [comment]
@ErikEJ Sir, can I work on this one? I really want to contribute to EF Core, but I see there only few issues I can work as I'm not expert, so if this doesn't require to be expert in the EF Core architecture, I would love to contribute.

**Comment by ErikEJ** [comment]
@sulton-max Sure, go ahead

**Comment by roji** [comment]
@sulton-max see my comment above about where to add tests.

**Comment by sulton-max** [comment]
@roji  @ErikEJ sorry for late response, I'm still struggling to find where exactly tests must be added for `DateOnly`

1. I found and learned about GearsOfWarQueryTestBase and its models relationship
2. Searched reference chain of methods where `DateOnly` is added 

So here is reference of `TypeMapping` in dictionary `SqlServerObjectToStringTranslator`, up to the top of hierarchy it will be used  with `AddEntityFrameworkSqlServer` from `SqlServerServiceCollectionExtensions` 

![image](https://github.com/dotnet/efcore/assets/63746735/1f771970-ce97-4bd2-b77d-0d4c9d94d69d)

All references are in 2 projects 
- EFCore.SqlServer.FunctionalTests
- EFCore.SqlServer.Tests

![image](https://github.com/dotnet/efcore/assets/63746735/88bf390f-0701-4461-8ff0-97edabbf2aaf)

whereas `GearsOfWarQueryTestBase` is being used in other projects 
- EFCore.InMemory.FunctionalTests
- EFCore.Relational.Specification.Tests
- EFCore.Specification.Tests

![image](https://github.com/dotnet/efcore/assets/63746735/1ebc133b-1c00-4a21-ae78-fb45c9c49403)

**Comment by ErikEJ** [comment]
Look at the Where_DateOnly_AddDays and do the same for your new test, named for example Where_DateOnly_ToString and Where_TimeOnly_ToString and add these new tests around the same place as the existing tests.

**Comment by ErikEJ** [comment]
@sulton-max You can look at my recent pull request here also for inspiration: https://github.com/dotnet/efcore/pull/31180

**Comment by sulton-max** [comment]
@ErikEJ Thank you very much

**Comment by sulton-max** [comment]
@ErikEJ 

Sorry if I'm asking too many questions

- Which one is correct implementation
![image](https://github.com/dotnet/efcore/assets/63746735/0e0d15f4-98cb-4536-9593-277c0b612cc0)
![image](https://github.com/dotnet/efcore/assets/63746735/7f5ef41c-987f-4587-b2a2-80799c5cf905)

- Should it be in `SqlServerObjectToStringTranslator` -> `Translate` method ( because translation for bool is there or in `SqlServerDateTimeMethodTranslator`

**Comment by sulton-max** [comment]
@ErikEJ got it, added it like this, so then actual translation must be in `SqlServerDateOnlyMethodTranslator`, right ?
![image](https://github.com/dotnet/efcore/assets/63746735/83ab6439-3d0e-4a4f-a03b-b61f6d890e72)

**Comment by ErikEJ** [comment]
No, just add some tests now. It would move them down one line.

I can help but feeling I am handholding you....

**Comment by sulton-max** [comment]
@ErikEJ  Ok, I wrote first test on `GearsOfWarQueryTestBase`, and checked the execution flow to make sure translator is being executed 

- translator 
![image](https://github.com/dotnet/efcore/assets/63746735/6e52ea8f-5225-4f4a-8103-8e447a22f311)

- test 
![image](https://github.com/dotnet/efcore/assets/63746735/737168a2-74f5-4cd8-82b7-c36620a6b653)

but test is failing, and there is not enough information in test failure message, at least  "Expected : 0 Actual : 1", confused, with some changes, Actual changing to 0 and Expected to 1

![image](https://github.com/dotnet/efcore/assets/63746735/3a901628-505b-4c33-a2c9-020511e9af2b)
 
Could you give some guidance on what expected and actual means ?

**Comment by sulton-max** [comment]
@ErikEJ @roji Sorry for late update, finished implementation and tests for `DateOnly`, used `Format` method of SQL with 'M/d/yyy' format for translator, can I commit and create PR ?

**Comment by roji** [comment]
Sure.
