### ISSUE TITLE
HasConversion for DbContext wide

### ISSUE THREAD

**Issue by Kiryuumaru** [dotnet/efcore#31034]
I would like to ask is there any way to make a `HasConversion` for all type inside context without calling `modelBuilder.Entity` each

ex:
```csharp
modelBuilder.Type<DateTime>().HasConversion(new DateTimeToBinaryConverter());
modelBuilder.Type<DateTime?>().HasConversion(new DateTimeToBinaryConverter());
modelBuilder.Type<DateTimeOffset>().HasConversion(new DateTimeOffsetToBinaryConverter());
modelBuilder.Type<DateTimeOffset?>().HasConversion(new DateTimeOffsetToBinaryConverter());
```
Usually I do:
```csharp
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    foreach (var property in entityType.ClrType.GetProperties()
        .Where(p =>
            p.PropertyType == typeof(DateTime) ||
            p.PropertyType == typeof(DateTime?) ||
            p.PropertyType == typeof(DateTimeOffset) ||
            p.PropertyType == typeof(DateTimeOffset?)))
    {
        if (property.PropertyType == typeof(DateTime) || property.PropertyType == typeof(DateTime?))
        {
            modelBuilder.Entity(entityType.Name)
                .Property(property.Name)
                .HasConversion(new DateTimeToBinaryConverter());
        }
        else if (property.PropertyType == typeof(DateTimeOffset) || property.PropertyType == typeof(DateTimeOffset?))
        {
            modelBuilder.Entity(entityType.Name)
                .Property(property.Name)
                .HasConversion(new DateTimeOffsetToBinaryConverter());
        }
    }
}
```
Which will trigger a table creation in my case. I have an owned model with a property DateTime type inside.

Or is there any way to avoid calling `modelBuilder.Entity` to do this?

**Comment by Kiryuumaru** [comment]
I am using SQLite, I may have forgotten the reason why I have to convert all datetime to binary on SQLite

**Comment by roji** [comment]
There's really no reason for you to be doing that - the SQLite provider handles these types just fine. The timestamps are represented as text in the database, which can also be queried with SQLite date/time functions. I highly recommend removing these conversions.

**Comment by Kiryuumaru** [comment]
Thank you for your recommendation. I removed the datetime conversion part of my config and my code works fine. But this is just my sample code, I have this issue converting `decimal` to text or to binary in SQLite to properly work with `OrderBy` queries. SQLite converts [System.Decimal](https://learn.microsoft.com/en-us/dotnet/api/system.decimal?view=net-7.0) to text by default which will make the order queries in alphabetical order.

**Comment by roji** [comment]
Unless I'm mistaken, the textual format used to store DateTime/DateTimeOffset (ISO8601) should be safely sortable, so this shouldn't be a problem. Decimals are a different case - I recommend thinking about this case-by-case.

**Comment by Kiryuumaru** [comment]
Adding conversions uisng the snippet above works if I do not have any [Owned entities](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities) with properties inside that I want to convert. Or are there other ways to address the [System.Decimal](https://learn.microsoft.com/en-us/dotnet/api/system.decimal?view=net-7.0) problem.

**Comment by roji** [comment]
> Adding conversions uisng the snippet above works if I do not have any [Owned entities](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities) with properties inside that I want to convert.

Have you seen my [comment above](https://github.com/dotnet/efcore/issues/31034#issuecomment-1579058133)? EF now has a 1st-class way of applying a value conversion to e.g. all DateTime properties everywhere (inside owned entities or not).

**Comment by Kiryuumaru** [comment]
> @Kiryuumaru you're probably looking for [bulk model configuration](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#pre-convention-configuration).

Thank you for this, I solved this problem. I used the `ConfigureConventions` in `DbContext` and I try to add `NumberToStringConverter<decimal>` or `NumberToBytesConverter<decimal>` but the order query is still not ordered properly, seems like I should add a custom NumberToStringConverter with padded zeros.

**Comment by roji** [comment]
I'm not sure it's feasible to produce a string representation of a decimal that also orders correctly - unless we always pad it with leading zeros so that it has the same length. Not sure that's what people want.

**Comment by ajcvickers** [comment]
>  seems like I should add a custom NumberToStringConverter with padded zeros

There is no universal conversion for decimals that will fulfil all requirements. If padding works for you, then go for it.
