### ISSUE TITLE
DbUpdateConcurrencyException exception when saving a master-detail graph where detail entity PK is Guid. (or Not)?

### ISSUE THREAD

**Issue by tzarot** [dotnet/efcore#31042]
When saving a master-detail (one-many) graph, where the child/detail entity has a PK of Guid, that **gets assigned from within the detail entity's constructor**, and the master/principal entity is fetched from the database, I am getting a **DbUpdateConcurrencyException**. 
If however, I do not fetch the Principal/Master entity from the database. but instead I create a new one and also add the child entity to it, then all work without any problems. 

Am I missing something here?

**Also**, if I remove the initializer, **Guid.NewGuid()**; from the Order Id property, all work without any errors. 

However I want to point-out that the Order.Id property, in the migration, is declared as .ValueGeneratedOnAdd() so reading the documentation in https://learn.microsoft.com/en-us/dotnet/api/Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder-1.ValueGeneratedOnAdd?view=efcore-7.0&viewFallbackFrom=net-7.0, the approach taken should work.

```C#
public class Customer
{
    public int Id { get; private set; }

    public string Name { get; set; } = null!; 

    public IList<Order> Orders { get; set; } = new List<Order>();
}

public class Order
{
    public Guid Id { get; private set; } = Guid.NewGuid(); // if I remove this assignment, all work fine.

    public int CustomerId { get; set; }
    
    public Customer Customer { get; set; }

    public DateTime OrderDate { get; set; }
    
}

public class PlayDbContext:DbContext
{
    public DbSet<Customer> Customers => Set<Customer>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(
            "Server=.;Database=PlayAcmeDatabase;Trusted_Connection=true;TrustServerCertificate=true;");
    }
}

 // This throws a DbUpdateConcurrencyException exception!
    var order = new Order()
    {
        OrderDate = DateTime.Now,
    };

    var c = db.Customers.FirstOrDefault(c => c.Name == "A2"); // A2 customer exists in database
    if (c == null) return;
    
    c.Orders.Add(order);
    db.SaveChanges();
    
// This works perfectly !!!
    var c = new Customer()
    {
        Name = "A3"
    };
    var order = new Order()
    {
        OrderDate = DateTime.Now,
    };

    c.Orders.Add(order);
    db.Customers.Add(c);
    
    db.SaveChanges();
```

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)

Attached the solution zip file. 
[Play.EFCore.Master-Detail-Detail2.zip](https://github.com/dotnet/efcore/files/11667835/Play.EFCore.Master-Detail-Detail2.zip)

**Comment by ajcvickers** [comment]
@tzarot Calling `DbSet.Add` or `DbContext.Add` always marks the pass entity as new, even if its key is set. This is essentially the way you tell EF to insert the entity _even though it has a key value already set_. Using `DbSet.Attach/Update`, `DbContext.Attach/Update`, or having EF detect the change, like you are doing in your first example, results in a state based on the key value. See [Explicitly tracking entities](https://learn.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking) for more info.
