### ISSUE TITLE
Fair IQueryable<T>.ToArrayAsync()

### ISSUE THREAD

**Issue by xrem** [dotnet/efcore#31040]
For now we have `ToArrayAsync` extension method that is using `ToListAsync` under the hood
https://github.com/dotnet/efcore/blob/fc5be30e0d0cda5b350c6b73cb7879f31888c1da/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2333-L2336

After researching a little bit I have found [article about performance improvement](https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/#collections) that were made in .NET 7 for collections and decided that it could be useful to change this method.

I am suggesting to use fair `ImmutableArray<T>.Builder` instead.

On my machine benchmarking have following results:

## Using ToListAsync().ToArray()
|            Method | Async | Tracking |            Mean |         Error |        StdDev |         Op/s |     Gen0 |    Gen1 | Allocated |
|------------------ |------ |--------- |----------------:|--------------:|--------------:|-------------:|---------:|--------:|----------:|
| WhereToArrayAsync |  True |    False | 3,332,160.94 ns | 61,145.760 ns | 57,195.782 ns |        300.1 | 242.1875 | 70.3125 |  803872 B |
| WhereToArrayAsync |  True |     True | 2,880,705.47 ns | 35,243.681 ns | 32,966.961 ns |        347.1 | 367.1875 |       - |  763459 B |

## Using ImmutableArray.Builder
|            Method | Async | Tracking |            Mean |         Error |        StdDev |         Op/s |     Gen0 |    Gen1 | Allocated |
|------------------ |------ |--------- |----------------:|--------------:|--------------:|-------------:|---------:|--------:|----------:|
| WhereToArrayAsync |  True |    False | 2,926,757.81 ns | 14,903.918 ns | 13,941.134 ns |        341.7 | 246.0938 | 74.2188 |  803373 B |
| WhereToArrayAsync |  True |     True | 2,809,698.47 ns | 22,967.420 ns | 19,178.836 ns |        355.9 | 367.1875 |       - |  762941 B |

**Comment by roji** [comment]
@xrem thanks for the benchmarking - it's a good idea to test on various element numbers (how many did you try), and also to always include minimal benchmark sources whenever publishing results.

I threw together a quick minimal benchmark, here are the results I'm seeing?

|                   Method | NumElements |         Mean |        Error |       StdDev |   Gen 0 |   Gen 1 | Allocated |
|------------------------- |------------ |-------------:|-------------:|-------------:|--------:|--------:|----------:|
|                  ViaList |           1 |     53.85 ns |     0.551 ns |     0.489 ns |  0.0229 |       - |     144 B |
| ViaImmutableArrayBuilder |           1 |     52.12 ns |     0.257 ns |     0.200 ns |  0.0255 |       - |     160 B |
|                  ViaList |           5 |     86.34 ns |     1.243 ns |     1.102 ns |  0.0343 |       - |     216 B |
| ViaImmutableArrayBuilder |           5 |     71.72 ns |     0.712 ns |     0.666 ns |  0.0280 |       - |     176 B |
|                  ViaList |          10 |    136.91 ns |     1.216 ns |     1.137 ns |  0.0508 |       - |     320 B |
| ViaImmutableArrayBuilder |          10 |    115.34 ns |     1.246 ns |     1.166 ns |  0.0446 |       - |     280 B |
|                  ViaList |         100 |    698.55 ns |     7.775 ns |     7.273 ns |  0.2623 |  0.0010 |   1,648 B |
| ViaImmutableArrayBuilder |         100 |    638.02 ns |    12.395 ns |    12.729 ns |  0.2556 |  0.0010 |   1,608 B |
|                  ViaList |         500 |  2,761.08 ns |    15.209 ns |    14.227 ns |  1.0147 |  0.0153 |   6,368 B |
| ViaImmutableArrayBuilder |         500 |  2,505.01 ns |    14.534 ns |    12.884 ns |  1.0071 |  0.0229 |   6,328 B |
|                  ViaList |        1000 |  5,269.47 ns |    85.152 ns |    79.652 ns |  1.9836 |  0.1144 |  12,488 B |
| ViaImmutableArrayBuilder |        1000 |  5,357.14 ns |    58.303 ns |    54.537 ns |  1.9836 |  0.1144 |  12,448 B |
|                  ViaList |       10000 | 54,906.57 ns |   899.454 ns |   841.350 ns | 26.9775 | 26.5503 | 171,464 B |
| ViaImmutableArrayBuilder |       10000 | 53,518.98 ns | 1,033.352 ns | 1,190.010 ns | 26.9775 | 26.5503 | 171,424 B |

<details>
<summary>Benchmark code</summary>

```c#
BenchmarkRunner.Run<Benchmarks>();

[MemoryDiagnoser]
public class Benchmarks
{
    [Params(1, 5, 10, 100, 500, 1000, 10000)]
    public int NumElements { get; set; }

    [Benchmark]
    public int[] ViaList()
    {
        var list = new List<int>();
        foreach (var i in Enumerable.Range(0, NumElements).ToArray())
            list.Add(i);
        return list.ToArray();


    }

    [Benchmark]
    public int[] ViaImmutableArrayBuilder()
    {
        var arrayBuilder = ImmutableArray.CreateBuilder<int>();
        foreach (var i in Enumerable.Range(0, NumElements))
            arrayBuilder.Add(i);
        return arrayBuilder.ToArray();
    }
}
```

</details>

This inded shows a small improvement by using immutable array builder, though it seems quite negligible - 20ns for 10 elements is unlikely to be significant when the call does actual network I/O etc.

The built-in non-async ToArray uses the internal [LargeArrayBuilder](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Collections/Generic/LargeArrayBuilder.SpeedOpt.cs) - would you like to benchmark what happens when that's copied out and used instead?

**Comment by xrem** [comment]
Not sure that it is possible to access that internal class in Private.CoreLib 🤔 
The only public API I was able to found is ImmutableArray.Builder

Looks like difference will only be visible on larger number of elements, accoring to [this article](https://olegkarasik.wordpress.com/2019/07/23/what-is-the-difference-between-toarray-and-tolist/)

Running your example with 50k elements is saving about 200kb of allocations 👀

**Comment by roji** [comment]
> Not sure that it is possible to access that internal class in Private.CoreLib thinking

I was suggesting copying the code out.

> Running your example with 50k elements is saving about 200kb of allocations

For 10k elements, my benchmark showed the exact same allocation (see above), are you saying that dramatically changes afterwards? Even if so, doing ToArray on a 50k resultset is (or at least should be) pretty rare, and I doubt 200k would be very noticeable in that scenario...

**Comment by xrem** [comment]
@roji Here is results of benchmarking suggested internal struct, not sure that it is worth duplicating implementation from runtime into EFCore :D

Actual code 🙈:
https://gist.github.com/xrem/d96268a6755b08b232dfa7f3ead3c93d

|                   Method | NumElements |         Mean |       Error |      StdDev |     Gen0 |     Gen1 |     Gen2 | Allocated |
|------------------------- |------------ |-------------:|------------:|------------:|---------:|---------:|---------:|----------:|
|                  ViaList |         100 |     358.1 ns |     4.15 ns |     3.88 ns |   0.9904 |        - |        - |   2.02 KB |
| ViaImmutableArrayBuilder |         100 |     645.9 ns |    11.40 ns |    11.70 ns |   0.7687 |        - |        - |   1.57 KB |
|     ViaLargeArrayBuilder |         100 |     962.0 ns |     9.03 ns |     8.45 ns |   0.6113 |        - |        - |   1.25 KB |
|                  ViaList |         500 |   1,525.6 ns |    27.44 ns |    41.07 ns |   4.0092 |        - |        - |    8.2 KB |
| ViaImmutableArrayBuilder |         500 |   2,844.6 ns |    55.95 ns |    90.35 ns |   3.0251 |        - |        - |   6.18 KB |
|     ViaLargeArrayBuilder |         500 |   4,083.3 ns |    78.79 ns |    93.80 ns |   2.1744 |        - |        - |   4.45 KB |
|                  ViaList |        1000 |   2,928.4 ns |    21.81 ns |    17.02 ns |   7.8850 |        - |        - |  16.13 KB |
| ViaImmutableArrayBuilder |        1000 |   5,178.6 ns |    84.68 ns |    75.07 ns |   5.9509 |        - |        - |  12.16 KB |
|     ViaLargeArrayBuilder |        1000 |   7,858.9 ns |   149.09 ns |   165.71 ns |   4.1046 |        - |        - |   8.42 KB |
|                  ViaList |       10000 |  30,582.9 ns |   535.76 ns |   474.94 ns |  99.9756 |        - |        - | 206.53 KB |
| ViaImmutableArrayBuilder |       10000 |  52,843.4 ns |   987.64 ns | 2,039.66 ns |  81.0547 |        - |        - | 167.41 KB |
|     ViaLargeArrayBuilder |       10000 |  76,417.6 ns | 1,498.75 ns | 1,725.96 ns |  49.9268 |        - |        - | 103.82 KB |
|                  ViaList |       20000 | 104,630.5 ns | 1,953.48 ns | 3,990.44 ns | 145.7520 |  41.6260 |  41.6260 | 412.69 KB |
| ViaImmutableArrayBuilder |       20000 | 145,492.7 ns | 2,800.98 ns | 2,997.01 ns | 124.7559 |  41.5039 |  41.5039 | 334.51 KB |
|     ViaLargeArrayBuilder |       20000 | 158,296.4 ns | 2,906.94 ns | 2,719.15 ns |  94.9707 |  23.6816 |        - | 206.91 KB |
|                  ViaList |       50000 | 407,365.6 ns | 2,933.19 ns | 2,600.20 ns | 249.5117 | 249.5117 | 249.5117 | 903.16 KB |
| ViaImmutableArrayBuilder |       50000 | 458,252.7 ns | 6,713.25 ns | 5,951.12 ns | 181.6406 | 181.6406 | 181.6406 | 707.76 KB |
|     ViaLargeArrayBuilder |       50000 | 516,850.4 ns | 5,617.11 ns | 5,254.24 ns |  99.6094 |  99.6094 |  99.6094 | 452.15 KB |

**Comment by roji** [comment]
@xrem to benchmark precisely, I'd really copy and paste the source code into your benchmark project, rather than using fancy reflection tricks which could add some overhead to the operation and skew the results.

If LargeArrayBuilder really does perform as above, then I'd open an issue on https://github.com/dotnet/runtime, to make sure the runtime developers are aware that large array builder has worse runtime performance than the other options (even though it does cut down on allocations).

In any case, in light of the above, I'm not sure it's worth changing anything in EF - do you agree?

**Comment by xrem** [comment]
Sure. Thanks for your time.

**Comment by roji** [comment]
Thanks for looking into EF perf and engaging!

**Comment by xrem** [comment]
@roji 

JFYI, copying this really makes sense when copying instead of emiting IL.
![image](https://github.com/dotnet/efcore/assets/7121898/860cd5c5-3a54-4360-b725-ed6cd972c1c8)

On mac:
```
BenchmarkDotNet=v0.13.5, OS=macOS Ventura 13.0 (22A380) [Darwin 22.1.0]
Apple M1 Pro, 1 CPU, 10 logical and 10 physical cores
.NET SDK=7.0.203
  [Host]     : .NET 7.0.5 (7.0.523.17405), Arm64 RyuJIT AdvSIMD
  DefaultJob : .NET 7.0.5 (7.0.523.17405), Arm64 RyuJIT AdvSIMD
```
|                      Method | NumElements |         Mean |       Error |      StdDev |     Gen0 |     Gen1 |     Gen2 | Allocated |
|---------------------------- |------------ |-------------:|------------:|------------:|---------:|---------:|---------:|----------:|
|                     ViaList |         100 |     264.0 ns |     3.07 ns |     2.87 ns |   0.3300 |   0.0005 |        - |   2.02 KB |
|    ViaImmutableArrayBuilder |         100 |     414.2 ns |     0.45 ns |     0.35 ns |   0.2561 |        - |        - |   1.57 KB |
| ViaManagedLargeArrayBuilder |         100 |     610.8 ns |     0.92 ns |     0.86 ns |   0.2031 |        - |        - |   1.25 KB |
|        ViaLargeArrayBuilder |         100 |     453.7 ns |     0.68 ns |     0.60 ns |   0.1898 |        - |        - |   1.16 KB |
|                     ViaList |         500 |     969.4 ns |     0.84 ns |     0.70 ns |   1.3371 |   0.0076 |        - |    8.2 KB |
|    ViaImmutableArrayBuilder |         500 |   1,747.8 ns |     2.11 ns |     1.98 ns |   1.0071 |   0.0038 |        - |   6.18 KB |
| ViaManagedLargeArrayBuilder |         500 |   2,452.9 ns |     1.61 ns |     1.34 ns |   0.7248 |   0.0038 |        - |   4.45 KB |
|        ViaLargeArrayBuilder |         500 |   1,854.7 ns |     1.11 ns |     0.99 ns |   0.7114 |   0.0038 |        - |   4.36 KB |
|                     ViaList |        1000 |   1,839.8 ns |     3.29 ns |     2.91 ns |   2.6302 |        - |        - |  16.13 KB |
|    ViaImmutableArrayBuilder |        1000 |   3,422.0 ns |     4.34 ns |     4.06 ns |   1.9836 |        - |        - |  12.16 KB |
| ViaManagedLargeArrayBuilder |        1000 |   4,683.9 ns |     3.47 ns |     3.25 ns |   1.3733 |   0.0153 |        - |   8.42 KB |
|        ViaLargeArrayBuilder |        1000 |   3,551.8 ns |     2.58 ns |     2.15 ns |   1.3580 |   0.0114 |        - |   8.34 KB |
|                     ViaList |       10000 |  16,593.0 ns |    18.84 ns |    16.70 ns |  33.5999 |   4.1809 |        - | 206.53 KB |
|    ViaImmutableArrayBuilder |       10000 |  33,577.5 ns |    38.05 ns |    33.73 ns |  27.2217 |   2.2583 |        - | 167.41 KB |
| ViaManagedLargeArrayBuilder |       10000 |  44,866.2 ns |   104.87 ns |    98.10 ns |  16.8457 |   3.2959 |        - | 103.82 KB |
|        ViaLargeArrayBuilder |       10000 |  33,872.7 ns |    46.01 ns |    38.42 ns |  16.8457 |   2.0752 |        - | 103.73 KB |
|                     ViaList |       20000 |  43,876.1 ns |   457.79 ns |   428.22 ns |  83.2520 |  41.6260 |  41.6260 | 412.71 KB |
|    ViaImmutableArrayBuilder |       20000 |  74,564.8 ns |   548.60 ns |   458.11 ns |  41.6260 |  41.6260 |  41.6260 | 334.52 KB |
| ViaManagedLargeArrayBuilder |       20000 |  88,332.8 ns |   187.36 ns |   166.09 ns |  33.3252 |   7.3242 |        - | 206.91 KB |
|        ViaLargeArrayBuilder |       20000 |  67,044.8 ns |   350.61 ns |   327.96 ns |  33.3252 |   1.0986 |        - | 206.82 KB |
|                     ViaList |       50000 | 160,029.7 ns | 3,118.48 ns | 3,712.33 ns | 249.7559 | 249.7559 | 249.7559 | 903.24 KB |
|    ViaImmutableArrayBuilder |       50000 | 201,704.9 ns |   989.36 ns |   925.45 ns | 181.6406 | 181.6406 | 181.6406 | 707.82 KB |
| ViaManagedLargeArrayBuilder |       50000 | 260,594.5 ns | 1,026.64 ns |   960.32 ns |  99.6094 |  99.6094 |  99.6094 | 452.18 KB |
|        ViaLargeArrayBuilder |       50000 | 193,440.6 ns |   385.90 ns |   342.09 ns |  99.8535 |  99.8535 |  99.8535 |  452.1 KB |

And on windows:
```
BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19045.3031/22H2/2022Update)
AMD Ryzen 5 5500U with Radeon Graphics, 1 CPU, 12 logical and 6 physical cores
.NET SDK=7.0.302
  [Host]     : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
```
|                      Method | NumElements |         Mean |       Error |      StdDev |     Gen0 |     Gen1 |     Gen2 | Allocated |
|---------------------------- |------------ |-------------:|------------:|------------:|---------:|---------:|---------:|----------:|
|                     ViaList |         100 |     363.0 ns |     4.99 ns |     4.42 ns |   0.9904 |        - |        - |   2.02 KB |
|    ViaImmutableArrayBuilder |         100 |     684.5 ns |    13.43 ns |    24.56 ns |   0.7687 |        - |        - |   1.57 KB |
| ViaManagedLargeArrayBuilder |         100 |     983.0 ns |    12.32 ns |     9.62 ns |   0.6104 |        - |        - |   1.25 KB |
|        ViaLargeArrayBuilder |         100 |     603.6 ns |     1.33 ns |     1.03 ns |   0.5693 |        - |        - |   1.16 KB |
|                     ViaList |         500 |   1,508.4 ns |     8.54 ns |     7.57 ns |   4.0092 |        - |        - |    8.2 KB |
|    ViaImmutableArrayBuilder |         500 |   3,063.4 ns |    60.89 ns |   114.37 ns |   3.0251 |        - |        - |   6.18 KB |
| ViaManagedLargeArrayBuilder |         500 |   3,729.1 ns |    38.29 ns |    33.94 ns |   2.1744 |        - |        - |   4.45 KB |
|        ViaLargeArrayBuilder |         500 |   2,578.8 ns |     5.98 ns |     5.30 ns |   2.1324 |        - |        - |   4.36 KB |
|                     ViaList |        1000 |   2,947.8 ns |     7.83 ns |     6.94 ns |   7.8850 |        - |        - |  16.13 KB |
|    ViaImmutableArrayBuilder |        1000 |   5,577.5 ns |   110.80 ns |   308.88 ns |   5.9509 |        - |        - |  12.16 KB |
| ViaManagedLargeArrayBuilder |        1000 |   7,750.9 ns |   154.04 ns |   144.09 ns |   4.1046 |        - |        - |   8.42 KB |
|        ViaLargeArrayBuilder |        1000 |   4,789.9 ns |    22.71 ns |    21.24 ns |   4.0741 |        - |        - |   8.34 KB |
|                     ViaList |       10000 |  32,284.5 ns |   574.09 ns |   589.55 ns |  99.9756 |        - |        - | 206.53 KB |
|    ViaImmutableArrayBuilder |       10000 |  57,222.8 ns | 1,031.55 ns | 1,103.75 ns |  81.0547 |        - |        - | 167.41 KB |
| ViaManagedLargeArrayBuilder |       10000 |  80,375.7 ns | 1,597.21 ns | 4,007.09 ns |  49.9268 |        - |        - | 103.82 KB |
|        ViaLargeArrayBuilder |       10000 |  48,105.4 ns |   393.48 ns |   348.81 ns |  49.9878 |        - |        - | 103.73 KB |
|                     ViaList |       20000 | 103,172.6 ns | 1,744.67 ns | 1,631.97 ns | 145.7520 |  41.6260 |  41.6260 | 412.69 KB |
|    ViaImmutableArrayBuilder |       20000 | 145,840.0 ns | 2,005.40 ns | 1,674.60 ns | 124.7559 |  41.5039 |  41.5039 | 334.51 KB |
| ViaManagedLargeArrayBuilder |       20000 | 151,467.8 ns | 2,963.55 ns | 4,056.54 ns |  95.2148 |  23.6816 |        - | 206.91 KB |
|        ViaLargeArrayBuilder |       20000 |  90,094.6 ns | 1,072.93 ns |   895.94 ns |  99.9756 |        - |        - | 206.82 KB |
|                     ViaList |       50000 | 419,379.4 ns | 3,817.12 ns | 3,383.78 ns | 249.5117 | 249.5117 | 249.5117 | 903.16 KB |
|    ViaImmutableArrayBuilder |       50000 | 466,038.3 ns | 5,593.19 ns | 4,958.21 ns | 181.6406 | 181.6406 | 181.6406 | 707.76 KB |
| ViaManagedLargeArrayBuilder |       50000 | 492,687.2 ns | 2,717.03 ns | 2,268.84 ns |  99.6094 |  99.6094 |  99.6094 | 452.15 KB |
|        ViaLargeArrayBuilder |       50000 | 356,205.7 ns | 1,165.32 ns | 1,033.02 ns |  99.6094 |  99.6094 |  99.6094 | 452.06 KB |
