### ISSUE TITLE
change model after initialization

### ISSUE THREAD

**Issue by aghasemiN** [dotnet/efcore#31056]
Hi
I am wondering is there any way to reconfigure model, onModelCreating in asp.net core is called only once when application starts and the first instance of dbcontext is built and onModelCreating is not called again unless you change dbcontextoptions ,in order to do some changes to model you have to build a new dbcontext manually, this approach has several limitation, first I don't have any changes in dbcontextOptions (I want to add for example some shadowProperties ), the second is that it doesn't effect all users and dbcontext service, and the dbcontext service still works with old model configuration and when dbcontext is injected to other contollers still has old configuration. I want to change the dbcontext model which has been created as scoped service in startup globally.
the best option for me would be to call onModelCreating again
thanks

**Comment by roji** [comment]
Carefully consider exactly why it is that you think you need to change your model at runtime; a model models your database schema, so will you be e.g. adding the corresponding columns to the database for the properties that you're planning to add? If you provide more context on exactly what you're trying to do, we can probably help you better.

Aside from that, EF does support multiple models, [see this doc page](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model) - but I'd recommend against implementing this without carefully understanding why you need this.

**Comment by aghasemiN** [comment]
thanks for your response, I want to add user the ability to extend model , for example I have a standard model of table Person with followin class structure
`public Person() `<br/>`
{ `<br/>`
      public int personId {get; set;} `<br/>`
      public string Name {get; set;}  `<br/>`
}`  
now after application starts and all users are working , I want to add a field to database called TestField , but I want to add it as shadow property in onModelCreating callback I have implemented a code which reads a file and dynamically adds shadow properties to model, the only problem is that I can do it only if I restart the whole application  then new changes will be applied and I am not able to do it in runtime, with this approach I give each customer the ability to extend the model based on thier requirements.

**Comment by roji** [comment]
@aghasemiN how would that work exactly, do you plan to add the corresponding column to the database when the user does that? What happens if the user removes a property, do you also drop the column?

Database schema changes are rarely something that makes at runtime; just like .NET doesn't allow changing type definitions at runtime, relational databases have a strict strongly-typed schema that should be changed only very carefully, and typically as part of the deployment of a new application version. There are various options if you want to store loosely-typed, unstructured data, e.g. a JSON column.

**Comment by aghasemiN** [comment]
@roji well the maintainace of database scheme is done by user itself and a system admin, ofcourse I have created a form which I display list of additional columns which are not part of standard model and when user selects a column, I will store the column defintion to a file like column name and clr type and database type and etc, he also can remove these properties (I mean those props which are not part of standard model) ,then he has to restart the application in order to apply changes , and with something like this
`modelBuilder.Entity(EnttiyTypeName).Property(entityProp.Type, entityProp.Name).HasColumnName(entityProp.Name);`
the property will be added to model, the json type doesn't work in this case because these props structured data and later they used in lookup field and grids and automatic linq will be created based on these column to allow filtering based on these columns.they also will be part of REST Api  and everything that a normal field can do.
it is good to say that even the user can add new entites also.
what I have implemented is perfect and it is working fine with several big customer. the only big issue, is that they have to restart application which causes a big delay and session problem

**Comment by ajcvickers** [comment]
@aghasemiN The model being used by a given DbContext instance cannot be changed. When creating a new instance, [customized model caching](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model) can be used to determine which model to use.

**Comment by ajcvickers** [comment]
@aghasemiN Evicting models from the cache is tracked by #30475.

**Comment by aghasemiN** [comment]
@ajcvickers is there any plan to implement this in near future? it seems it has been open for a while.

**Comment by ajcvickers** [comment]
@aghasemiN I think its unlikely to get implemented in the near future.

**Comment by roji** [comment]
It should also be possible to construct the model yourself, using your provider's convention set, and then pass it explicitly when configuring the context (e.g. with UseSqlServer), /cc @AndriySvyryd?

**Comment by AndriySvyryd** [comment]
Yes, you can start with `var modelBuilder = SqlServerConventionSetBuilder.CreateModelBuilder()` and after you've finished building the model call `UseModel(modelBuilder.FinalizeModel())` in the context options
