### ISSUE TITLE
Entity Framework Core skip and take from the back?

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#31057]
I have the following query:
```
IQueryable<SellerProductDTO> result = _dbContext.Products
            .Where(product => EF.Property<Guid?>(product, "SellerId") != null && EF.Property<Guid?>(product, "SellerId") == sellerId
                    && (!string.IsNullOrEmpty(phrase) ? product.SearchVector.Matches(EF.Functions.ToTsQuery("english", phrase)) : true))
            .OrderByDescending(td => td.SearchVector.Rank(EF.Functions.ToTsQuery("english", phrase)));

List<Product> products = await result.Skip(page * pageSize).Take(pageSize).ToListAsync();
```
I would like to optimize it so that if the result is big and the client provides small page size for pagination, navigating from 1st to the last page should not take a long time. I am thiking if the page that the client requests crosses the half point, skip and take from the back instead. How could I achieve that? Thanks.

### Include provider and version information

EF Core version: 7.0.5
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) Postgresql
Target framework: (e.g. .NET 6.0) .Net 7
Operating system: Ubuntu 23.04
IDE: (e.g. Visual Studio 2022 17.4) VSCode

**Comment by roji** [comment]
You can always do OrderByDescending and then Skip and Take, is that what you're asking?

However, note that if you're trying to make pagination efficient (assuming the list your paginating is big), you should carefully think about how indexing will be used and how much data you're forcing the database to go over. I highly recommend reading and understanding the differences between offset pagination (with Skip) and keyset pagination (with Where), [see our docs](https://learn.microsoft.com/en-us/ef/core/querying/pagination).

**Comment by khteh** [comment]
Use redis cache
