### ISSUE TITLE
Include parent entity column name in child entity column name using data annotations

### ISSUE THREAD

**Issue by glen-84** [dotnet/efcore#31068]
### Include your code

```C#
[Owned]
public sealed class QuickPollModel
{
    public string QuestionText { get; init; } = null!;

    public QuickPollOptionModel Option1 { get; init; } = null!;

    public QuickPollOptionModel Option2 { get; init; } = null!;
}

[Owned]
public sealed class QuickPollOptionModel
{
    // Replace OWNER_PROPERTY_NAME with Option1 (option_1) or Option2 (option_2) from QuickPollModel.
    [Column("quick_poll_{OWNER_PROPERTY_NAME}")]
    public string Text { get; init; } = null!;
}
```

In an attempt to use data annotations for all configuration, I'm experimenting with the idea of using a "templated column name" where the name of the parent property can be inserted into the name of the child property, as shown above.

I don't know if something like this would be considered for inclusion in EF Core itself, so I'm just coding something in `OnModelCreating`:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var ownedEntityTypes = modelBuilder.Model.GetEntityTypes().Where(e => e.IsOwned());

    foreach (var ownedEntityType in ownedEntityTypes)
    {
        var parentPropertyName = ownedEntityType.FindOwnership()?.PrincipalToDependent?.Name; // => Option1

        foreach (var property in ownedEntityType.GetProperties())
        {
            // Update the column name.
        }
    }
}
```

1. Is this the correct way to get the name of the parent property?
2. Is it possible to get its processed/SQL name? (f.e. `option_1` instead of `Option1` [we're using `EFCore.NamingConventions`])
3. Is there another way of accomplishing this with data annotations?

### Include provider and version information

EF Core version: 7.0.5
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET 7.0
Operating system: Windows 11 Home
IDE: VS Code 1.79.0

**Comment by ajcvickers** [comment]
@glen-84 It would probably be better to do this as a model-finalizing convention. There is no "processed/SQL" name at this point. That only happens once columns exist. How the navigation name pointing to the owned entity is used to name columns is up to your code.

In general, mapping attributes allow for the static configuration for some sub-set of possible model configurations. It is not intended that mapping attributes support everything.

**Comment by glen-84** [comment]
@ajcvickers

I apologize for the late reply (moving apartments).

I understand that there are some limitations to attribute-based mapping, so this was more of an experiment than anything else.

I think my confusion was in thinking that the properties `Option1` and `Option2` would have column names, but as navigation properties that's obviously not the case. I guess if I'm formatting the names myself, then a model-finalizing convention is no longer required anyway.

Thanks for your help.
