### ISSUE TITLE
scaffolding command fail

### ISSUE THREAD

**Issue by lucadibiagio** [dotnet/efcore#3106]
hello i'm trying to use scaffolding feature but unfortunatelly something goes wrong:

scenario:
trying scaffolding from database SqlExpress on MVC6  web site

installed package 
    "EntityFramework.SqlServer": "7.0.0-beta7",  
     "EntityFramework.Commands": "7.0.0-beta7",
     "EntityFramework.SqlServer.Design": "7.0.0-beta7"

command from powershell
dnx ef dbcontext scaffold "Data Source=.\sqlexpress;Initial Catalog=FT360.DB;Integrated Security=False;User ID=sa;Password=xxx;Connect Timeout=60;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" EntityFramework.SqlServer

Error:
[ERROR] dnx : System.InvalidOperationException: Instance failure.
[ERROR] At line:1 char:1
[ERROR] + dnx ef dbcontext scaffold "Data Source=.\sqlexpress;Initial Catalog= ...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : NotSpecified: (System.InvalidO...stance failure.:String) [], RemoteException
[ERROR]     + FullyQualifiedErrorId : NativeCommandError
[ERROR]  
[ERROR]    at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean 
[ERROR] ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boole
[ERROR] an integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
[ERROR]    at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, 
[ERROR] SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
[ERROR]    at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, 
[ERROR] SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, 
[ERROR] SqlCredential credential, TimeoutTimer timeout)
[ERROR]    at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString 
[ERROR] connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean 
[ERROR] redirectedUserInstance)
[ERROR]    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString 
[ERROR] connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString 
[ERROR] newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData 
[ERROR] reconnectSessionData, DbConnectionPool pool, String accessToken)
[ERROR]    at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey 
[ERROR] poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions 
[ERROR] userOptions)
[ERROR]    at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection 
[ERROR] owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
[ERROR]    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions 
[ERROR] userOptions, DbConnectionInternal oldConnection)
[ERROR]    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions 
[ERROR] userOptions, DbConnectionInternal oldConnection)
[ERROR]    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 
[ERROR] waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions 
[ERROR] userOptions, DbConnectionInternal& connection)
[ERROR]    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 
[ERROR] retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
[ERROR]    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, 
[ERROR] TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, 
[ERROR] DbConnectionInternal& connection)
[ERROR]    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, 
[ERROR] DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
[ERROR]    at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, 
[ERROR] DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
[ERROR]    at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
[ERROR]    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
[ERROR]    at System.Data.SqlClient.SqlConnection.Open()
[ERROR]    at Microsoft.Data.Entity.SqlServer.Design.ReverseEngineering.SqlServerMetadataModelProvider.LoadMetadataFromData
[ERROR] base(String connectionString)
[ERROR]    at Microsoft.Data.Entity.SqlServer.Design.ReverseEngineering.SqlServerMetadataModelProvider.ConstructRelationalM
[ERROR] odel(String connectionString)
[ERROR]    at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringMetadataModelProvider.GenerateMe
[ERROR] tadataModel(String connectionString)
[ERROR]    at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator.GetMetadataModel(IData
[ERROR] baseMetadataModelProvider provider, ReverseEngineeringConfiguration configuration)
[ERROR]    at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator.<GenerateAsync>d__25.M
[ERROR] oveNext()
[ERROR] --- End of stack trace from previous location where exc
[ERROR] eption was thrown ---
[ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[ERROR]    at Microsoft.Data.Entity.Commands.Program.<ReverseEngineerAsync>d__16.MoveNext()
[ERROR] --- End of stack trace from previous location where exception was thrown ---
[ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[ERROR]    at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass9_4.<<Main>b__11>d.MoveNext()
[ERROR]

**Comment by davezych** [comment]
Afaik an `Instance Failure` normally means it can't connect to your database. Make sure your connection string is correct.

**Comment by rowanmiller** [comment]
@lucadibiagio was it an invalid connection string?

**Comment by gilbertogwa** [comment]
Only register proposer... To me, works changes "\\" on string connection to "\":

EG

 <add name="DefaultConnection" connectionString="Server=localhost\\SQLEXPRESS...

rather then

 <add name="DefaultConnection" connectionString="Server=localhost\SQLEXPRESS...

Source: https://stackoverflow.com/questions/36084770/entity-framework-core-use-windows-service
