### ISSUE TITLE
Is it possible to map with fluent API a value object to separate table in the database?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#31093]
Supose that i have orders as entity and State as value object in my domain model.

This is the model:

```
//Entity
public class Order
{
    long id;
    string Number;
    //another prperties

    State Status; //value object
}


//Value object
public class State
{
    string Status;
}
```

And this is the tables in the database:

```
Orders(Id, Number,...);
OrderStates(Id, Status);
```

I know i could configure State as owned property of the Order entity, but in this case in the database I only would have one table, orders, with one varchar colum for the status, and I wouldn't have the State table:

`Orders(Id, Number, State_Status,...)`

But I would like to know if it is possible to map the states in another table in the database and keep the state in the domain model as value object with no ID.

Is it possible?

Thanks.

**Comment by ajcvickers** [comment]
@ComptonAlvaro Use `ToTable` or `TableAttribute`.
