### ISSUE TITLE
Switch to storing enums as ints in JSON instead of strings

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#31100]
We currently serialize .NET enums into JSON as their string label; this is:

1. Incompatible with the behavior of System.Text.Json and Newtonsoft.Json, which serialize to the underlying int value.
2. Incompatible with our relational behavior, which also value-converts to the int value. This notably means that it's impossible to compare an enum value inside JSON with another enum value outside of JSON in a LINQ query.

**Comment by petersladek** [comment]
We ran into this issue - we have json stored in db with enum values as ints. Is there any workaround right now? i.e. possibility of specifying value converter for json property?

**Comment by ajcvickers** [comment]
@petersladek Use `HasConversion<int>` on the property configuration inside `OnModelCreating`.`
