### ISSUE TITLE
Check constraints not being re-enabled for some tables

### ISSUE THREAD

**Issue by andref15** [dotnet/efcore#31115]
I have a project where I use the `DbContex.Database.MigrateAsync` method to apply all pending migrations. When de database is deleted and newly created, at least one of the tables has foreign key constraints, that aren't being enforced.
I enabled Microsoft.EntityFrameworkCore.Database.Command logs and I can see that before applying the migrations, `EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';` is executed, which disables all FK checks on all tables.
Later in the logs I can see a bunch of `ALTER TABLE <tablename> CHECK CONSTRAINT ALL;` statemends. However this statement is missing for at least one of the tables and I can see in SSMS, that the FK constraint is not being enforced for this table.

I can't see any difference between this table and the other tables, where the FK checks are enforced, therefore I think this might be some kind of bug.
I'm also wondering why `EXEC sp_msforeachtable` isn't being used to re-enable all checks.

EF Core version: 7.0.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11 22H2
IDE: e.g. Visual Studio 2022 17.6

**Comment by ajcvickers** [comment]
@andref15 Can you post the generated migration code?

**Comment by andref15** [comment]
@ajcvickers 
[db_log.txt](https://github.com/dotnet/efcore/files/11829988/db_log.txt)
The disabling happens on line 1964, and the re-enabling starts on line 5098

**Comment by ajcvickers** [comment]
@andref15 I don't think EF Core generates these kinds of statements as part of migrations. Can you post the C# code for the migration that is seeds `DimensionLayoutStandards` entities?

**Comment by roji** [comment]
@andref15 EF doesn't generate sp_msforeachtable as far as I can tel (it doesn't show up in the codebase at all); it looks like that's maybe coming from your code?

**Comment by andref15** [comment]
@roji Really sorry, you're right. Another team member created an sql script containing data from the production DB and this script contains these statements and gets executed during the migration. I must have missed that when I reviewed his PR.

Sorry for wasting your time

**Comment by andref15** [comment]
> @roji Really sorry, you're right. Another team member created an sql script containing data from the production DB and this script contains these statements and gets executed during the migration. I must have missed that when I reviewed his PR.
> 
> Sorry for wasting your time
