### ISSUE TITLE
Feature request: add way to override eliminating transaction using SaveChangesInterceptor

### ISSUE THREAD

**Issue by amyboose** [dotnet/efcore#31119]
EF Core added new Feature to [eliminate unneeded transactions](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#unneeded-transactions-are-eliminated). But sometimes It useful to override this behavior.

My short example withot full project:
```C#
internal sealed class DomainEventsInterceptor : SaveChangesInterceptor
{
    public override ValueTask<InterceptionResult<int>> SavingChangesAsync(DbContextEventData eventData, InterceptionResult<int> result, CancellationToken cancellationToken = default)
    {
        if (eventData.Context is not IDomainEventStorableContext domainEventContext)
        {
            return base.SavingChangesAsync(eventData, result, cancellationToken);
        }

        foreach (EntityEntry entry in eventData.Context.ChangeTracker.Entries())
        {
            if (entry is not IContainsDomainEvent entryWithDomainEvent)
                continue;

            foreach (BaseEvent domainEvent in entryWithDomainEvent.DomainEvents)
            {
                domainEventContext.AddDomainEvent(domainEvent);
            }
        }

        return base.SavingChangesAsync(eventData, result, cancellationToken);
    }
}

internal sealed class MartinEventInterceptor : DbTransactionInterceptor
{
    private readonly IDocumentStore _documentStore;

    public MartinEventInterceptor(IDocumentStore documentStore)
    {
        _documentStore = documentStore;
    }

    public override async ValueTask<DbTransaction> TransactionStartedAsync(DbConnection connection, TransactionEndEventData eventData, DbTransaction result, CancellationToken cancellationToken = default)
    {
        NpgsqlTransaction npgsqlTransaction = (NpgsqlTransaction)eventData.Transaction;

        await using var session = _documentStore.LightweightSession(SessionOptions.ForTransaction(npgsqlTransaction));

        IDomainEventStorableContext context = (IDomainEventStorableContext)eventData.Context!;

        foreach (BaseEvent domainEvent in context.Events)
        {
            session.Store(domainEvent);
        }

        await session.SaveChangesAsync();

        return await base.TransactionStartedAsync(connection, eventData, result, cancellationToken);
    }
}
```

As you can see I want to use DbTransactionInterceptor and save data into MartinDB's session at the same time as EF Core's data. I use single transaction for both data writes. My DbContext is extended by using custom property **Events**. And I want to use transaction even though DbContext have just single object. I add my objects in SaveChangesInterceptor to context to use it later.

Describe the solution you'd like:
I would like to override eliminating transaction behaviour in SaveChangesInterceptor to use it later.

**Comment by roji** [comment]
@amyboose you're probably looking for [share connection and transaction](https://learn.microsoft.com/en-us/ef/core/saving/transactions#share-connection-and-transaction): EF allows you to provide an arbitrary DbConnection and DbTransaction, so that you can run include EF operations along with operations from any external component (such as MartinDB) in the same transaction.

**Comment by amyboose** [comment]
> @amyboose you're probably looking for [share connection and transaction](https://learn.microsoft.com/en-us/ef/core/saving/transactions#share-connection-and-transaction): EF allows you to provide an arbitrary DbConnection and DbTransaction, so that you can run include EF operations along with operations from any external component (such as MartinDB) in the same transaction.

Unfortunately, no. I know about external DbTransactions and can't use this approach in my case. I want to automatically add every DomainEvent to context. I use DDD with aggregates and all my infrastructure logic is hidden under repositories. It's not the first time when this feature can be usefull. I also had similar approach to save events using CAP library. Also there will be a lot of redundant code using external DbTransactions.

**Comment by amyboose** [comment]
If needed, I can show another case with the CAP library when it might be useful.

**Comment by roji** [comment]
@amyboose I'm not sure I completely follow what you're asking for.

> And I want to use transaction even though DbContext have just single object.

Are you saying that you want to disable the EF Core 7.0 optimization, where we no longer wrap SaveChanges in a transaction when there's only one change to be saved? If so, and you'd like EF to always wrap SaveChanges in a transaction, you can do that as follows:

```c#
context.Database.AutoTransactionBehavior = AutoTransactionBehavior.Always;
```

This can be placed in your context's constructor to apply it always/everywhere.

Otherwise, you'll have to provide a bit more detail on what exactly you're asking for.

**Comment by roji** [comment]
Great, opened https://github.com/dotnet/EntityFramework.Docs/issues/4396 to add docs on this.
