### ISSUE TITLE
Scaffolding with use-database-names and events table generates invalid code

### ISSUE THREAD

**Issue by dshook** [dotnet/efcore#31121]
## File a bug

I'm running this command 
`dotnet ef dbcontext scaffold --use-database-names --context-dir "Models" --output-dir "Models" -f "Name=ConnectionStrings:WebApiDatabase" Npgsql.EntityFrameworkCore.PostgreSQL`
on a database that has an `events` table. 

This generates an `event.cs` model file.  However the `event` file is generated with invalid syntax because of the reserved keyword.

```C#
using System;
using System.Collections.Generic;

namespace reporting_api.Models;

public partial class event  // Identifier expected error here
{
    public int id { get; set; }

    public string type { get; set; } = null!;

    .....
}
```

This also happens with a `files` table.

### Include provider and version information

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 7.0.4
Target framework: .NET 7.0
Operating system: OSX

**Comment by dshook** [comment]
The workaround I found is to use the `--no-pluralize` option, however it would be nice to have this automatically applied to only the conflicting names and not every table.

**Comment by ajcvickers** [comment]
Note from triage: we should generate `@events` for this. This might be a regression from introduction of the T4 templates.
