### ISSUE TITLE
Self reference owned types in EF Core JSON columns

### ISSUE THREAD

**Issue by ImanBahrampour** [dotnet/efcore#31131]
I want to save these models into a SQL Server database as JSON:

    public class VersionEntity 
    {
        public VersionEntity()
        {
        }

        public VersionItemEntity Items { get; set; }
        public long ProjectId { get; set; }
        public int TenantId { get; set; }
    }

    public class VersionItemEntity
    {
        public List<VersionItemsEntity> VersionItems { get; set; }
    }

    public class VersionItemsEntity
    {
        public VersionItemsEntity()
        {
        }

        public string Key { get; set; }
        public string Label { get; set; }
        public VersionItemsDataEntity Data { get; set; }
        public string Icon { get; set; }
        public List<VersionItemsEntity> Children { get; set; } = new();
    }

    public class VersionItemsDataEntity
    {
        public string Title { get; set; }
        public int? Order { get; set; }
        public DateTime? ReleaseDate { get; set; }
    }

And the `OnModelCreating` method is :

   ```
private void VersionModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.Ignore<VersionItemsDataEntity>();
            modelBuilder.Entity<VersionEntity>().OwnsOne(
              version => version.Items, ownedNavigationBuilder =>
              {
                  ownedNavigationBuilder.OwnsMany(
                  metadata => metadata.VersionItems, ownedOwnedNavigationBuilder =>
                  {
                      ownedOwnedNavigationBuilder.OwnsMany(vi => vi.Children);
                      ownedOwnedNavigationBuilder.OwnsOne(vi => vi.Data);
                      ownedNavigationBuilder.ToJson();
                  }
                  );
              });
            modelBuilder.Entity<VersionEntity>().Property(o => o.Id).UseIdentityColumn(Back_SoftConsts.InitialValue);
     }
```

When I run `Add-Migration version` in the Package Manager Console, this error appears:

> Unable to determine the owner for the relationship between 'VersionItemsEntity.Children#VersionItemsEntity.Data' and 'VersionItemsDataEntity' as both types have been marked as owned. Either manually configure the ownership, or ignore the corresponding navigations using the [NotMapped] attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'. See https://aka.ms/efcore-docs-owned for more information and examples.

note: If I remove the line `ownedOwnedNavigationBuilder.OwnsMany(vi => vi.Children);` it is fixed, but the children are not saved

**Comment by ajcvickers** [comment]
In mapping the children, you also need to map the `Data` navigation on the children. For example:

```C#
ownedOwnedNavigationBuilder
    .OwnsMany(
        vi => vi.Children, b =>
        {
            b.OwnsOne(e => e.Data);
        });
```
