### ISSUE TITLE
Manage platform-dependent newlines in tests

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3116]
The tests currently fail in various cases of mixed newline situations. For example, if you run tests on Linux SQL will can generated with LF, but expected strings will have CRLF. There should probably be a normalization of whitespace before asserting equality in various places...

**Comment by bricelam** [comment]
In our repo, we use [.gitattributes](https://github.com/aspnet/EntityFramework/blob/dev/.gitattributes#L1) to ensure the tests are checked out with native line endings. Thus if you're running them on Linux, it should assert that unix line endings are used.

**Comment by bricelam** [comment]
I suppose you could still run into problems if you compile the tests on Windows and try to run them on Linux. Personally, I've tried to avoid this in my tests by putting `Environment.NewLine` in the tests instead of using verbatim string literals.

**Comment by roji** [comment]
Thanks for the suggestion, I guess this should be enough.
