### ISSUE TITLE
EF set nvarchar(450) in case of having index for string property

### ISSUE THREAD

**Issue by sa-es-ir** [dotnet/efcore#31167]
I have a model like this:

```C#
public class Student
{
    public int Id { get; set; }

    public string UniqueCode { get; set; }
}
```
Configuration:
```C#
 modelBuilder.Entity<Student>()
            .HasKey(x => x.Id);

  modelBuilder.Entity<Student>()
            .HasIndex(x => x.UniqueCode)
            .IsUnique();
```
And generated migrations:

```C#
migrationBuilder.CreateTable(
                name: "Students",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UniqueCode = table.Column<string>(type: "nvarchar(450)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Students", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Students_UniqueCode",
                table: "Students",
                column: "UniqueCode",
                unique: true,
                filter: "[UniqueCode] IS NOT NULL");
```
EF set the string property to ``nvarchar(450)``, I know maybe EF is wise enough to know that SQL will not allow creating an index on ``nvarchar(max)`` but why 450 chars? why not at least give a warning during generating migrations?

### Include provider and version information

EF Core version: EF 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows

**Comment by ErikEJ** [comment]
Max index size is 900 characters .

**Comment by sa-es-ir** [comment]
The behavior is a little confusing, I couldn't find any document about it, and no hint during migrations, As @ErikEJ mentioned the max size for an index is 900 chars.

**Comment by sa-es-ir** [comment]
Thanks, @ajcvickers 
Yeah, I always set max length for my strings but I just wondered how this number (450) was chosen.
**Can I say that it only happens if I set an index on the string property?**

**Comment by ajcvickers** [comment]
@sa-es-ir 450 is also used for properties of primary, alternate, and foreign keys.

**Comment by sa-es-ir** [comment]
Great and thanks for the clarification @ajcvickers
