### ISSUE TITLE
Querying an entity, that has previously been updated using Attach, using Include does not include the entity

### ISSUE THREAD

**Issue by kevinboss** [dotnet/efcore#31183]
## Ask a question

I have a scenario where I update a property of EntityA using Attach, then query another EntityB Including its property ```List<EntityA>```.
That list does not include the previously updated EntityA.

Is this an expected behavior?

### The following sample applications reproduces the behaviour

```C#
using Microsoft.EntityFrameworkCore;

using var context = new BloggingContext();
context.Database.EnsureDeleted();
context.Database.EnsureCreated();

using var transaction = context.Database.BeginTransaction();
var blog = new Blog { BlogId = 1, Url = "Url"};
context.Add(blog);
context.SaveChanges();
var post = new Post { PostId = 1, BlogId = blog.BlogId, Title = "A", Content = "A"};
context.Add(post);
context.SaveChanges();
transaction.Commit();

context.ChangeTracker.Clear();

using var transactionB = context.Database.BeginTransaction();
var updatePost = new Post { PostId = 1};
context.Posts.Attach(updatePost);
updatePost.Title = "B";
updatePost.Content = "B";
context.SaveChanges();
transactionB.Commit();

var blogB = context.Blogs.Include(e => e.Posts).SingleOrDefault();
Console.WriteLine($"Posts: {blogB.Posts.Count}");

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    public DbSet<Post> Posts { get; set; }

    // The following configures EF to create a Sqlite database file as `C:\blogging.db`.
    // For Mac or Linux, change this to `/tmp/blogging.db` or any other absolute path.
    protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseSqlite(@"Data Source=LocalDatabase.db");
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
    }
}

public class Blog
{

    public int BlogId { get; set; }

    public string Url { get; set; }

    public List<Post> Posts { get; set; } = new List<Post>();
}

public class Post
{
    public int PostId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int BlogId { get; set; }

    public Blog Blog { get; set; }

```

### Include provider and version information

EF Core version: 7.0.8
Database provider: Microsoft.EntityFrameworkCore.Sqlite and SqlServer
Target framework:  NET 7.0
Operating system: Windows 11 22H2
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
@kevinboss The call to `Attach` tells EF that the tracked entity exists and has this state in the database. Since the FK property is 0, this indicates that the tracked post is not related to the blog with Id 1. Since this entity is still tracked when the query is executed, it means that the tracked entity is used instead of the entity that is in the database. See [change tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more information.

**Comment by kevinboss** [comment]
@ajcvickers I understand that, it is still quite confusing. EF executes the following Query 

```SQL 
SELECT "t"."BlogId", "t"."Url", "p"."PostId", "p"."BlogId", "p"."Content", "p"."Title"
      FROM (
          SELECT "b"."BlogId", "b"."Url"
          FROM "Blogs" AS "b"
          LIMIT 2
      ) AS "t"
      LEFT JOIN "Posts" AS "p" ON "t"."BlogId" = "p"."BlogId"
      ORDER BY "t"."BlogId"
```

which includes any Posts but then decides to ignore the already tracked Entity?

I also don't really understand why it would assume that FK is 0 as that value is not changed to 0 after attaching.

**Comment by ajcvickers** [comment]
@kevinboss It's zero because that's the value it has when it is attached. Calling `Attach` says to EF, this entity already exists in the database _with these values_. In general, it's dangerous to use `Attach` when some property values are not known.

**Comment by kevinboss** [comment]
@ajcvickers We use Attach when we only want to execute an update without first loading the complete entity. Since that seems to require us to clear the ChangeTracker or load the whole entity in the first place. Is there another way to do that then?

Also just to make sure I understand. In the above scenario EF does the following:

1. Attach the Post-Entity and update the modified fields
2. Query the Blog-Entity including the join on Post
3. EF then gets the server response including the Post-Entity from step 1
4. EF then decides that the Post-Entity it got from the server does actually not belong to the Blog-Entity and does not materialize it?

That is the part where I am struggeling to understand the reasoning behind this behavior. The server returns the Post-Entity in question but EF decides it does not belong to the Blog-Entity because it has a version of it in the ChangeTracker that does not have a FK to the Blog-Entity.

**Comment by kevinboss** [comment]
@ajcvickers I really don't want to be annoying here. But it is confusing that the incorrect FK from the Post-Entity overrides the queried entitites from loading a Blog-Entity including Posts. EF seems to value the information it has in its Cache over what it actually gets from the server. That would only make sense if it would not actually run the query to save a DB-Call. But it did call the DB already and then still decides that the local Cache it has must be true.

That is what I do not understand, if I have actual data as well as a Cache why do you value the information in the Cache as correct?

**Comment by ajcvickers** [comment]
>  if I have actual data as well as a Cache why do you value the information in the Cache as correct?

There are two answers to this. At the basic level, EF uses the cached entity instance because you told EF to do so by calling Attach. Going deeper, the general case of how to merge two different graphs doesn't have an unambiguous answer, and so EF does not attempt to merge two graphs, with some information coming from the database and some information coming from the tracked graph. The change tracking docs, linked above, go into this in more detail.
