### ISSUE TITLE
Install Microsoft.EntityFrameworkCore.SqlServer into project .NET 7 error

### ISSUE THREAD

**Issue by tamsps** [dotnet/efcore#31194]
Hi all,
When I install Microsoft.EntityFrameworkCore.SqlServer into project in .NET7 then occur this error:

NU1202: Package System.Text.Encoding.CodePages 5.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package System.Text.Encoding.CodePages 5.0.0 supports:error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: NU1202: Package System.Security.AccessControl 5.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package System.Security.AccessControl 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
error: NU1202: Package System.Security.Permissions 5.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package System.Security.Permissions 5.0.0 does not support any target frameworks.
error: Package 'Microsoft.EntityFrameworkCore.SqlServer' is incompatible with 'all' frameworks in project 'F:\Project...

May you help me resolve it?
Thanks,
Tam

**Comment by ajcvickers** [comment]
@tamsps Please post your csproj file.

**Comment by tamsps** [comment]
@ajcvickers Thanks for reply me, this is my csproj file:

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>tntt_cms_models</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>The model for TNTT system</Title>
    <Authors>Tam Vu</Authors>
    <Company>TNTT</Company>
    <Description>The model of TNTT system</Description>
    <Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\HiepDoan.cs" />
    <Compile Remove="Models\KetQuaHocTap.cs" />
    <Compile Remove="Models\LienDoan.cs" />
    <Compile Remove="Models\LopHoc.cs" />
    <Compile Remove="Models\MonHoc.cs" />
    <Compile Remove="Models\Profile.cs" />
    <Compile Remove="Models\Role.cs" />
    <Compile Remove="Models\TongLienDoan.cs" />
    <Compile Remove="Models\XuDoan.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
`
I successed to install three package: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Design and Microsoft.EntityFrameworkCore.Tools. But I got error above when install Microsoft.EntityFrameworkCore.SqlServer 7.0.8

**Comment by ajcvickers** [comment]
@tamsps I am not able to reproduce this--see my output below using your csproj.

```
PS C:\local\code\AllTogetherNow\tntt_cms_models> dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 7.0.8
  Determining projects to restore...
  Writing C:\Users\ajcvi\AppData\Local\Temp\tmp1puvl0.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.SqlServer' into project 'C:\local\code\AllTogetherNow\tntt_cms_models\tntt_cms_models.csproj'.
info : Restoring packages for C:\local\code\AllTogetherNow\tntt_cms_models\tntt_cms_models.csproj...
info : Package 'Microsoft.EntityFrameworkCore.SqlServer' is compatible with all the specified frameworks in project 'C:\local\code\AllTogetherNow\tntt_cms_models\tntt_cms_models.csproj'.
info : PackageReference for package 'Microsoft.EntityFrameworkCore.SqlServer' version '7.0.8' added to file 'C:\local\code\AllTogetherNow\tntt_cms_models\tntt_cms_models.csproj'.
info : Writing assets file to disk. Path: C:\local\code\AllTogetherNow\tntt_cms_models\obj\project.assets.json
log  : Restored C:\local\code\AllTogetherNow\tntt_cms_models\tntt_cms_models.csproj (in 314 ms).
PS C:\local\code\AllTogetherNow\tntt_cms_models>
```

**Comment by tamsps** [comment]
@ajcvickers Thanks for your supporting. Let's me try again. Perhaps my computer missing something else
