### ISSUE TITLE
How to use dotnet required keyword and [key] attribute together?

### ISSUE THREAD

**Issue by SveinnB** [dotnet/efcore#31195]
Is it possible to set the dotnet required keyword and the [Key] attribute together in entity class?
I want to have my ef core project set to nullable:enable

I have the following entity/Table
```C#
public class User {
    [Key]
    public required Guid Id { get; set; }

    [MaxLength(200)]
    public required string Name { get; set; }
};
```
the problem with this is that now when I create a new user I have to define and give the Id.
I do not want that.
I want the database to do it

```C#
// Can't do that because Id is not set
var user = new User {
    Name = "Sveinn"
};

// Ok, but here the Id is not set by the database
// and if the Id definition/column is int, i'm in trouble
var user = new User {
    Id = Guid.NewGuid(),
    Name = "Sveinn"
};
```

so my question is: **Is it possible to have a both required property and database generated values?**
and if not which way is better?

- skip the required keyword and use the [Key] attribute and always have to deal with possibly null reference in the code from now on
- set the required keyword and skip the [Key] and always give new user id with Guid.NewGuid() and how would you do that if the id is int

### Include provider and version information
EF Core version: 7.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.6.4

**Comment by ajcvickers** [comment]
@SveinnB The `required` keyword is not appropriate for properties that will get values generated by EF since the property is set later and does not need to be set when creating an instance.
