### ISSUE TITLE
Use built-in json support in EF7 for properties that have a different name in sql server

### ISSUE THREAD

**Issue by PaulVrugt** [dotnet/efcore#31217]
We are trying to migrate from the `HasConversion` option to map ef core properties to .net types which are actually json columns in the database, to the native support for Json columns in ef core 7. 

So we used to have something like:

```c#
builder.Property(x => x.Definition).HasConversion(x => x.ToJSON(), x => x.ToObject<ViewDefinition>());
```

and now we are doing:
```c#
builder.OwnsOne(x => x.Definition, nb =>
{
    nb.ToJson();
}
```

however, in our case, the `Definition` isn't called `Definition` in the database, but is called `ViewDefinition`. However, we need the property in the ef entity to be called `ViewDefinition`. Now it seems that the `OwnsOne` setup ignores the `[Column("ViewDefinition")]` attribute on the property, and I can also not find any way to set the name of the property in the builder.

Now my question is, what can I do in my ef configuration to make sure the `Definition` property maps to the `ViewDefinition` column in sql server?

### Version info
EF Core version: 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0

**Comment by doddgu** [comment]
I fell in, too.
I used Json Column, and it need to support polymorphism.
Use `builder.OwnsOne(x => x.JsonProperty, builder => builder.ToJson())` , it writes sql server correctly, but read alwasy the base class. It does not support deserialization of polymorphic settings like System.Text.Json.

**Comment by ajcvickers** [comment]
@PaulVrugt `.ToJson("ViewDefinition");`.

**Comment by PaulVrugt** [comment]
> @PaulVrugt `.ToJson("ViewDefinition");`.

If only everything in life turned out to be this easy....
