### ISSUE TITLE
Tests don't run in VS2015 Test Explorer

### ISSUE THREAD

**Issue by staff0rd** [dotnet/efcore#3121]
I followed the steps [here](https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code) and have EntityFramework 7 building in VS2015.

Under _RunTests_ the instructions above note the following:

> Our tests are written using [xUnit.net 2.0](https://github.com/xunit/xunit), and can be run using your
> favorite runner. We recommend either the built-in Visual Studio test
> runner or [TestDriven.Net](http://www.testdriven.net/).

In VS2015, executing _Test > Run > All Tests_ results in:

```
------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.0990702) ==========
```

Taking a look at [Running xUnit.net tests in Visual Studio](http://xunit.github.io/docs/running-tests-in-vs.html) reveals that you need to:

> Search for (and install) a package named `xunit.runner.visualstudio`

However doing so results in a failed install, for either the current stable or prerelease package;

```
Resolving conflicts for DNXCore,Version=v5.0...
Unable to find a version of package 'System.Dynamic.Runtime' that is compatible with version constraint '[4.0.0, )'.
Unable to find a version of package 'System.Text.RegularExpressions' that is compatible with version constraint '[4.0.10, )'.
Unable to find a version of package 'System.ComponentModel' that is compatible with version constraint '[4.0.0, )'.
Unable to find a version of package 'System.IO.FileSystem' that is compatible with version constraint '[4.0.0, )'.
Unable to find a version of package 'System.Collections.Concurrent' that is compatible with version constraint '[4.0.0, )'.
========== Finished ==========
  NotFound https://az320820.vo.msecnd.net/v3-flatcontainer/microsoft.framework.primitives/index.json 1078ms
```

Originally asked on [stackoverflow](http://stackoverflow.com/questions/32546675/how-can-i-run-entityframework-7-tests?noredirect=1#comment52951662_32546675).

**Comment by ErikEJ** [comment]
+1

**Comment by rowanmiller** [comment]
At this stage we are maintain code to keep test runners working. Given this we are just going to keep Test Driven .NET working (as that is what our team uses), but we would accept contributions if folks want to keep others working too.

Once things stabilize we will make other things work.

**Comment by arielszklarkiewicz** [comment]
Hi. Any update on this?
I'm trying to run tests targetint to dnxcore50, but with not success until now. I've also tried with Test Driven .Net.
Thanks!

Ariel

**Comment by rowanmiller** [comment]
Test Driven .NET is the runner that we use and we will ensure that it continues to work. We will enable others once the project system, runtimes, etc. stabilize (meaning we don't spend a bunch of time fixing stuff that breaks all the time).

If you are hitting issues with Test Driven .NET then file a new issue as that should work.
