### ISSUE TITLE
Is a SQLite connection over SMB without mounting possible?

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/efcore#31227]
## Ask a question

I'm currently using https://github.com/TalAloni/SMBLibrary in a MAUI app, to read and write a JSON file on a remote machine.
My data is becoming more complex and relational thus I'm looking to migrate my data and move over to using EF Core and its SQLite provider.
Is it possible to connect to a SQLite database via the SMB protocol? I assume if this is not currently supported, it would require support being added to the SQLite provider NuGet package? I know I could mount the location as a virtual path and EF core could read it, however seeing as I'm using MAUI, the application runs on both Windows Desktop and Android devices. Android cannot mount directories without being rooted.

**Comment by roji** [comment]
@KieranDevvs I'm not a mobile export, but as far as I'm aware, the standard approach is to have your SQLite database in your app-specific storage (either by creating it, or downloading it). 

There's definitely no way to implement an SMB client into Sqlite, nor do I think it would make sense to do so. For one thing, Microsoft.Data.Sqlite is just a wrapper over the native SQLite libraries, so support would need to be done there. But I don't think it's sustainable to ask all client libraries that access files to integrate SMB support into them to avoid having the file locally etc.

**Comment by KieranDevvs** [comment]
> @KieranDevvs I'm not a mobile export, but as far as I'm aware, the standard approach is to have your SQLite database in your app-specific storage (either by creating it, or downloading it).

The data is shared between clients and thus it wouldn't make sense to only store the database on the local device. SQLite does support multi client access over a shared network as this is somewhat of a primary use case: https://www.sqlite.org/useovernet.html

Managed to stumble onto Androids storage access framework API's that let you "mount" a storage provider and thus apps can access files via a URI. I'll look further down this avenue to see if it works with SQLite.

If not, I might just have to bite the bullet and host a traditional server backed database.

Thanks for the reply.
