### ISSUE TITLE
how to : optimize away entry.collection.loadAsync() 

### ISSUE THREAD

**Issue by vigouredelaruse** [dotnet/efcore#31226]
given
* multitarged ef core project Net6_0, Net7_0 
* the following generic code for adding ef core entity reference collection items
* please advise on the necessity for LoadAsync()

```
  relatedEntity = ((DbContext)_context).Set<U>().Where(w => w.Id.Equals(item.Id)).First();

  if (((DbContext)_context).Entry(trackedEntity).Collection(propertyName) != null)
  {
      // the many to many case
      await ((DbContext)_context).Entry(trackedEntity)
      .Collection(propertyName)
      .LoadAsync();
      ((ICollection<U>)trackedEntity.GetType().GetRuntimeProperty(propertyName).GetValue(trackedEntity)).Add(relatedEntity);
  }
```
i seem to remember or perhaps misremember 
* entity.Collection.LoadAsync() is required to prevent accidental reference collection deletion on SaveChanges()
* LoadAsync() materializes the collection in memory

i would like to know if i can optimize the resource requirements of this code by removing LoadAsync() before i start tinkering with the associated unit tests

thanks

**Comment by ajcvickers** [comment]
@vigouredelaruse I'm really not sure what you are asking. `LoadAsync` loads related entities from the database. You should use it if you need to do that, and not otherwise.

**Comment by vigouredelaruse** [comment]
i think i'm seeking clarity on the pattern for mutating entity.collection 

i want to make sure that modifying entity.collection translates the appropriate updates to join tables without having to use .loadasync()
