### ISSUE TITLE
Raising PropertyChanged notification on entity key throws exception "The property 'EntityId' on entity type 'Entity' is part of a key and so cannot be modified or marked as modified."

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#3123]
### Environment

UniversalWindowsApp running on Windows 10.
Visual Studio 2015
Entity Framework 7 beta 6
SQLite database
{
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-beta6",
    "EntityFramework.Sqlite": "7.0.0-beta6",
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.CodeAnalysis.CSharp": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Microsoft.NETNative.Analyzer": "1.0.0",
    "Prism.Mvvm": "1.1.1"
  },
  "frameworks": {
    "uap10.0": {}
  },
### Create an entity similar to this, and raise Property changed event for entities primary key as below

```
public class Entity : INotifyPropertyChanged
{
    private int entityId;
    public int EntityId
    {
        get { return entityId; }
        set
        {
            // For brevity sake checking if value has really changed, and if it really not on the UI thread removed.
                        var ignored = Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(
                            Windows.UI.Core.CoreDispatcherPriority.Normal,
                            () =>
                            {
                                PropertyChanged(this, new PropertyChangedEventArgs(nameof(AccountId)));
                                // Exception raised here. Note: set is being called by EntityFramework and not by user code; though the above statement is occurring on the UI thread and not directly by Entity Framework.
                            });
        }
    }
```

   }
### Steps to reproduce
1. Create object context.
2. Create an instance of entity.
3. Save changes on object context.
### Call stack of exception looks like

Exception thrown as "The property 'EntityId' on entity type 'Entity' is part of a key and so cannot be modified or marked as modified."

   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetPropertyModified(IProperty property, Boolean isModified)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.<>c__DisplayClass12_0.<PropertyChanged>b__0(IPropertyListener l)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.Dispatch(Action`1 action)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntrySubscriber.<>c__DisplayClass2_0.<SnapshotAndSubscribe>b__2(Object s, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at MyNamespace.Entity.<set_EntityId>b__3_0()
### Workaround

Do not raise property changed events just for primary key from user code. When we use code generators this becomes an issue to not raise events just for primary keys.

**Comment by divega** [comment]
@sgmon Could you provide some information about the pattern you are using in your implementation of `INotifyPropertyChanged`? Did you need to do this to have the UI work correctly with notifications in UWAs? Is this a pattern you found somewhere? Where? How common is this type of implementation?

To give you some background: EF needs the notification to happen immediately and in the same thread as the change, otherwise it won't work. We cannot think of any way we can support notifications being dispatched in a different thread in the way your code does it, so at this point we are mulling whether we are going to need a flag somewhere in our API to force change detection to compare property values against snapshots even if the `INotify*` interfaces are implemented (in case they are implemented in an unsupported way).

**Comment by rowanmiller** [comment]
Closing as this does not seem like a common scenario
