### ISSUE TITLE
Multitenancy: Dynamic Connection strings or connection interceptor w/ pooleddbcontexts

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#31266]
## Ask a question
I'd like to implement schema per tenant multi-tenancy (postgres) with efcore, in a relatively efficient way.  My thought is that I'd like to treat all schemas as 1 schema. For this reason, I'm inclined to run migrations against a default schema, and any application of migrations to other tenants will happen out of band. 

Postgres allows me to either provide a dedicated connection string setting targetpath such that I scope that connection to a particular schema... or I can run some sql to set search-path which should theoretically scope remaining calls that session with provided schema.

Finally, if possible... I'd like to use this for pooleddbcontext.

I'm wondering if any of the following should be possible whilst remaining somewhat efficient.

1. Somehow setup my `DbContext` such that I can access a `TenantContextProvider` (already exists), and in `OnConfiguring`, have `TenantContextProvider` provide the `TenantId` and call `.UseNpgsql(dynamicConnStr)`. Currently I can't find a workaround to pass `TenantContextProvider` to my db context (constructor parameter doesn't work, and injection of the `DbContextFactory` throws an exception saying something along the lines of DbContext lacking the proper constructor.

2.  Use `IDbConnectionInterceptor` to dynamically set search path from values retrieved from `TenantContextProvider`. Right now these aren't dependency injected... and even if I register with my DI container and fetch that to pass to `IDBConnectionInterceptor`, I'm unclear of lifecycle of the interceptor (to ensure I'm setting the connection up correctly for the request/tenant).

I'm also thinking this may be more designed for something like tracing where I can catch connection creation, but not really intended to be used to manipulate that connection.

OR:

Does anyone have any other recommendations for any other workarounds that wouldn't negate the value of `PooledDbContext` whilst still letting me effectively set connection parameter or connectionstring dynamically per request (or scope), and use another service to provide current `TenantId`?

This functionality is pretty essential, and if there are other classes I can extend and `options.ReplaceService<>` to make this work. I'm willing to do the research and implementation if someone can point me in the correct direction.

Remember:

> * Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
> * Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

** I googled this, and searched github issues...** 

Found lots of implementations of multi-tenancy, but none that seemed to circumvent the challenges I listed above. Some answers like building a custom implementation of `IModelCacheKeyProvider` I didn't fully understand, but led me to believe that would treat each tenant as a fully separate schema I could generate a migration for and maintain independently. 

I'd like to avoid that, and for all intents and purposes have efcore think there is 1 db, 1 schema, and either modify connection after creation, or to be able to dynamically pull in connection string. Migration sql generated already appears to work and doesn't require providing namespace/schema name on ddl creation.

**I really appreciate any pointers here, I've already started down many paths in many blog posts, or the samples in this repo, and cant seem to get it working.**

**Comment by ajcvickers** [comment]
1. Pooled contexts share the model across uses, but use different connection string and other context state, so it should be okay.
2. The context will not maintain the connection state across uses, so I don't think this is an issue.
3. You can register your own IDbContextFactory service, if you want to change what the default does.
