### ISSUE TITLE
Query: SelectExpression.Update always creates new instance of SelectExpression without checking if anything changed

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#31276]
This is not how any other Update methods on SqlExpression work. We should figure out if it was intentional and if it's safe to make changes. This may cause functional changes because Equals method on SelectExpression is (intentionally) implemented as ReferenceEquals. We could be missing some optimizations by "updating" the same SelectExpression in effect creating a copy, that we can't recognize as being equivalent anymore.

**Comment by roji** [comment]
I suspect that we currently use Update() only in cases where we know we're going to change the expression anyway... But I think you're right and we should look into it...
