### ISSUE TITLE
Conditional detection of dotnet ef migrations add command in .csproj

### ISSUE THREAD

**Issue by ThatDeveloper** [dotnet/efcore#31273]
## Ask a question

How to know if project is build / executed from within dotnet-ef tools in regards to .csproj conditions.

```
    <ItemGroup>
        <ProjectReference Include="..\Shared.Test.csproj" Condition="<what to use here so it is used IF NOT dotnet-ef migrations add command>">
            <Private>false</Private>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>

        <ProjectReference Include="..\Shared.Test.csproj" Condition="<what to use here so it is used IF dotnet-ef migrations add command>" />
    </ItemGroup>
```

### Include provider and version information

EF Core version:
Database provider: Various
Target framework: NET 7.0 (Microsoft.EntityFrameworkCore.Design v 7.0.8)
Operating system: Windows
IDE: Various

**Comment by ajcvickers** [comment]
@ThatDeveloper See [Detect when tools are running](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#detect-when-tools-are-running) for detecting when code is being run from the EF tools.
