### ISSUE TITLE
How to populate collection of a many to many relation without needed to use Include()?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#31283]
This is a sample to reproduce the error.

[EntityCorePopulateManyToManyError.zip](https://github.com/dotnet/efcore/files/12071906/EntityCorePopulateManyToManyError.zip)

In a one to many relationships, entity core it is able to populate the navigation properties when I use entity resolution, when I don't use AsNoTracking(). And this is true no matter if the navigation property is an object or a collection.

However, I have realize that in the many to many relationships, it is needed to use always Include(), beacuse if not, the entities aren't add to the collection of the entity.

In the sample that I attached, I have the Documents entity, with one collection to know the related documents. I have only one collection in the entity, because I want only one navigation direction.

This is the entity:

```
public class Document
{
    public long Id { get; set; }
    public string Name { get; set; }


    public List<Document> RelatedDocuments { get; set; } = new List<Document>();
}
```

This is the configuration:

```
public class DocumentConfiguration : IEntityTypeConfiguration<Document>
{
    public void Configure(EntityTypeBuilder<Document> paramDocumentfiguracion)
    {
        paramDocumentfiguracion.ToTable("Documents");


        paramDocumentfiguracion.HasKey(o => o.Id);
        paramDocumentfiguracion.Property<long>(o => o.Id)
            .HasColumnName("IDDocument")
            .HasColumnType("bigint")
            .IsRequired();

        paramDocumentfiguracion.Property<string>(o => o.Name)
            .HasColumnName("Name")
            .HasColumnType("varchar(200)")
            .IsRequired();



        paramDocumentfiguracion
            .HasMany<Document>()
            .WithMany(x => x.RelatedDocuments)
            .UsingEntity(
                "RelatedDocuments",
                l => l.HasOne(typeof(Document)).WithMany().HasForeignKey("IDDocument").HasPrincipalKey(nameof(Document.Id)),
                r => r.HasOne(typeof(Document)).WithMany().HasForeignKey("IDRelatedDocument").HasPrincipalKey(nameof(Document.Id)),
                j => j.HasKey("IDDocument", "IDRelatedDocument"));
    }
}
```

And this is the repository with the two queries:

```
internal class Repository
{
    #region variables
    private readonly Context _context;
    #endregion variables



    #region constructors
    public Repository(string paramConnectionString)
    {
        //La configuarción que tendrá el dbContext
        DbContextOptionsBuilder<Context> miBulider = new DbContextOptionsBuilder<Context>();

        miBulider.UseSqlServer(paramConnectionString);

        _context = new Context(miBulider.Options);
    }
    #endregion constructors



    //This should't populate the collection becase I am using entity resolution? I am not using AsNotracking().
    public async Task<Models.Document> GetDocumentWithRelatedDocumentsWithNoInclude(long paramIdDocument)
    {
        return await _context.Documents
            .FirstAsync(x => x.Id == paramIdDocument);
    }



    //This works
    public async Task<Models.Document> GetDocumentWithRelatedDocumentsWithInclude(long paramIdDocument)
    {
        return await _context.Documents
            .Include(x => x.RelatedDocuments)
            .FirstAsync(x => x.Id == paramIdDocument);
    }
}
```

The problem is that using Include(), the query that is send to the database is more complex, if the Document entity has many properties and there are many documents in the databse, I get a timeout exception. If entity core would populate the collection without the needed of the Include(), I am sure i would have a better performance.

Anyway, if I am not wrong, the expected behavior should be that entity core populates the collection, because I am using entity resolution, in the same way in the one to many relationships, I don't need to use include to populate the navigation properties. So in some way the behavior is not consistent.

Perhaps the configuration with fluent API is not correct.

Thanks.

**Comment by VenkateshUttur** [comment]
Hi
have tried with lazy loading options.

**Comment by ComptonAlvaro** [comment]
Thanks for the suggestion, but in my case I would prefer to avoid to use lazy loading, because it is an aditional query to the database.

Also, one of the reasons I opened the issue is because I would like to know if this is the expected behavior, if although I get all the documents from the database, entity core doesn't populate the collection, when in the one to many relationships it does it.

**Comment by ajcvickers** [comment]
@ComptonAlvaro 

> If entity core would populate the collection without the needed of the Include()

How would EF do this? Where would the information come from about which entities are related?

**Comment by ComptonAlvaro** [comment]
@ajcvickers 

Well, I thought that when I configure the many to many relationship in fluent API, EF knows how the entities are related. In my case, I am using this way to configure the relationship:

```
paramDocumentfiguracion
            .HasMany<Document>()
            .WithMany(x => x.RelatedDocuments)
            .UsingEntity(
                "RelatedDocuments",
                l => l.HasOne(typeof(Document)).WithMany().HasForeignKey("IDDocument").HasPrincipalKey(nameof(Document.Id)),
                r => r.HasOne(typeof(Document)).WithMany().HasForeignKey("IDRelatedDocument").HasPrincipalKey(nameof(Document.Id)),
                j => j.HasKey("IDDocument", "IDRelatedDocument"));
```

In this configuration, I am telling that there is a join table, RelatedDocuments, and the items of the collection has a foreign key.

If EF doesn't have the needed information to populate the collection, why does it can when I use Include()? From where does the Include() get the information to can populate the collection?

Suponse that relationship is one to many. For example, Supose I have files and the file can be only one type (document, video, audio... and so on). I would configure the relationship in this way:

```
paramEstadoFacturaFacturafiguracion
    .HasMany(x => x.Files)
    .WithOne()
    .HasForeignKey(x => x.IdType);
```

Now I do two queries to avoid the use of include:

```
_context.Types.ToList();

//At this point the collection of files of the Type entity is empty.

_context.Files.ToList();

//At this point, the collection of files of the Type entity is populated with the files.
```

In this case I don´t need to use include in this way:

`_context.Types.Inlcude(x => x.Files).ToList();`

So in sumary:

Why in a many to many relationships EF doesn't have the needed information to populate the collection and in a one to many relationships it has?



Thanks.

**Comment by ajcvickers** [comment]
> If EF doesn't have the needed information to populate the collection, why does it can when I use Include()?

`Include` is the way to tell EF to load that relationship from the database. So it gets the information...from the database.

> Why in a many to many relationships EF doesn't have the needed information to populate the collection and in a one to many relationships it has?

Because many-to-many relationships are represented by a join table.
