### ISSUE TITLE
Code Analysis should also check for EF client side evaluation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#31288]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Analysis-should-also-check-for-EF-c/1631605)._

---
After EF 3.0 releases, Client side evaluation of queries are restricted. Code Analysis tool should detect LinQ queries in the solution that is performing or having code that does Client side evaluation as a warning.

---
#### Feedback Bot on 1/10/2022, 08:18 AM: 

(private comment, text removed)
#### Billy Xing on 3/8/2022, 04:16 AM: 

(private comment, text removed)

**Comment by roji** [comment]
@vsfeedback this issue has been discussed many times before; unfortunately, there are technical reasons that make it infeasible to detect and perform translation of EF LINQ queries from a Roslyn analyzer. We do have some targeted diagnostics in mind, but the general task of knowing when a LINQ query is translatable or not isn't feasible.
