### ISSUE TITLE
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: 'A non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#31280]
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```C#
        using (var scope = Services.CreateScope())
        {
            var scopedServices = scope.ServiceProvider;
            var appDb = scopedServices.GetRequiredService<AppDbContext>();
            var identityDb = scopedServices.GetRequiredService<AppIdentityDbContext>();
            var logger = scopedServices.GetRequiredService<ILogger<CustomWebApplicationFactory<TStartup>>>();

            // Ensure the database is created.
            appDb.Database.EnsureCreated(); <- throws
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: 'A non-blocking socket operation could not be completed immediately. [::1]:5432'
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version: 7.0.9
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) PostgreSQL 15
Target framework: (e.g. .NET 6.0) .NET 7.0
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.4) Version 17.6.4

**Comment by roji** [comment]
@khteh there's no context at all about your exception; please post at least a description, preferably a minimal, runnable code sample.

**Comment by khteh** [comment]
https://github.com/khteh/AspNetCoreWebApi/blob/master/test/Web.Api.IntegrationTests/CustomWebApplicationFactory.cs

**Comment by roji** [comment]
That's a pretty huge solution - please make the effort of submitting a minimal, runnable code sample, preferably as a console program. Also, the full stack trace of the exception you're seeing is missing.

One thought re "A non-blocking socket operation could not be completed immediately"... This exception may get thrown internally by Npgsql as part of the normal connection process; it gets caught and handled, and the connection succeeds. Some users have reported this, when in fact it was only a "first-chance exception" while debugging their application. Are you seeing this exception actually bubbling out of Npgsql while running your application (not in debug mode)?

**Comment by khteh** [comment]
Yes, the exception is caught at `appDb.Database.EnsureCreated();` when debugging the integration test code fixture.

**Comment by roji** [comment]
@khteh does this **only** happen when debugging? If so, then it's as I wrote above: the exception isn't actually thrown from Npgsql, but rather just thrown internally and caught. You can safely ignore it.
