### ISSUE TITLE
Consider if opening up the SQL-generation would be possible

### ISSUE THREAD

**Issue by MikaelEliasson** [dotnet/efcore#313]
Hi!

As the creator of EFUtilities that has methods for DeleteByQuery, UpdateByQuery and similar I wish the api's where more open. I realize there are reasons to keep as much code as possible internal. But I think a balance could be found which would benefit the ecosystem.  

In EFUtilities I've implemented DeleteByQuery and UpdateByQuery by calling ToTraceString() and parsed the sql with a regex and replaced some stuff. It seems to work well but it's a hack, and a quite ugly one. What I would have wanted was a way to give the SqlProvider a spec and let it generate the query or parts of the query. My point is that translating LINQ to SQL is non-trivial and it would be very nice to be able to use the work you have already done.

As I said I realize there is a trade off between reducing the public api and this request. I just hope you can think about it and if you find an acceptable way to make the great work you have done with query translation I think it would benefit EF.

**Comment by MikaelEliasson** [comment]
Hi again! Last time I looked at this EF7 was too unfinished to draw any conclusions.

I've been poking around the code to see what can be done. It feels much more open and I like that. Nice work! 

I'm hitting a wall trying to reimplement some of the Batch operations I built for EFUtilities. Some background:

Take for example my version of DeleteByQuery
```
var count = EFBatchOperation.For(db, db.BlogPosts).Where(b => b.Created < upper && b.Created > lower && b.Title == "T2.0").Delete();
```

That works outside the DbContext and generates a single sql query to delete all rows matching the predicate. Basically even EF6 already have everything needed for this but we can't use it. The way I solved it was to pretend it was a Where query and get the command text and just use string manipulations on the generated sql to make it a delete. 

Now that is of course an ugly hack and I wanted to make it "proper" for EF7. I can see that all the pieces are there and accessible in the SqlGenerator + SqlServerSqlGenerator. But here I get stuck because they all use the ColumnModification which is tied to the StateEntry. 

I've not given up on getting it to work by creating a fake state entry yet. But I was thinking that it's quite small changes needed to make this much easier. I will continue trying to implement it and hopefully come back with more detailed suggestions.

For now my preliminary thoughts are that it would be nice if we could use the sql generation with info like: 
- Generate the sql for setting PropertyA on TypeA to ValueX 
- Generate the sql for checking if PropertyA on TypeA is smaller than ValueX
etc etc

**Comment by madelson** [comment]
We would also benefit a ton from this functionality. We have similar hacks built on EF6 to translate an EF queryable into raw SQL text which then gets further manipulated. Making this easy would go a long way towards not forcing developers to choose between the type-safe composable LINQ and hand-optimized SQL in every case
