### ISSUE TITLE
EFCore pulls latest packages from dotnet/runtime but LKG shared framework from the SDK

### ISSUE THREAD

**Issue by ericstj** [dotnet/efcore#31300]
Example where this causes a problem: https://github.com/dotnet/efcore/pull/31178#issuecomment-1640695789

The packages from dotnet/runtime target the latest build of `net8.0` and expect API to be present in the shared framework.   EFCore does not set it's tests up to run on the matching build, instead it runs on whatever build was present in the SDK it downloaded.

So we're using packages out of dotnet/runtime build 8.0.0-preview.7.23364.11 which depend on API in the shared framework of the same version, however EFCore is running against a shared framework version 8.0.0-preview.7.23329.8 - which is nearly a month out of date.  This is going to create problems whenever we depend on new API added to the shared framework.  It just so happened that recently we made a change where every library we built against net8.0 depended upon attributes added to the shared framework.

EFCore should make sure that it acquires the matching runtime and makes it's tests target this runtime.  ASPNetCore does something similar cc @wtgodbe

**Comment by wtgodbe** [comment]
@bricelam do you know why we haven't had problems with this before? Was it because pre-8.0, EF updated runtimes/SDKs less frequently/more intentionally?

**Comment by bricelam** [comment]
I think we *just* started actually running on .NET 8 with @AndriySvyryd's latest AoT tests.

I'm bringing in the code to do this now (assuming it hasn't changed since 6.0)
