### ISSUE TITLE
Does EFCore scaffolding using T4 templates support Oracle.EntityFrameworkCore or another alternative?

### ISSUE THREAD

**Issue by victorromeo** [dotnet/efcore#31305]
I need to customize the scaffolding produced from EFCore, as we have internal preferences for Property names and overrides for .Net data types, not currently supported via Oracle EDM mappings. Specifically NUMBER(38,0) for us should map to a INT64 long data type.

For example, the following command does scaffold, but it doesn't use the CoreTemplates\EFCore folder content to do so.

```dotnet ef scaffold dbcontext "connection string" Oracle.EntityFrameworkCore```

also, no joy...

```Scaffold-DbContext -Connection "connection string"  -Provider Oracle.EntityFrameworkCore ... ```

Does EFCore 7 support this provider, when using the T4 templates?  If not, what feature is the Oracle.EntityFrameworkCore library missing to support the scaffolding via the TemplatedModelGenerator?

EF Core version: 7.0.9
Database provider: (e.g. Oracle.EntityFrameworkCore)
Target framework: .NET 6 or .NET 7 
Operating system: Win 11 x64
IDE: Visual Studio 2022 Enterprise / VS Code

**Comment by ErikEJ** [comment]
It should be "CodeTemplates\EFCore" .. and T4 works with any provider
