### ISSUE TITLE
Include if a migration has destructive operations in `ef migrations list --json`

### ISSUE THREAD

**Issue by justindbaur** [dotnet/efcore#31319]
## Problem:
Sometimes in a CI pipeline you may want an extra review on a PR based on if the migrations added have destructive operations. 

When a migration is scaffolded a warning is printed to console but this would normally be done by the developer and the PR CI pipeline would have no knowledge that this happened and a PR that causes data loss when manual data migration should have taken place could occur. 

https://github.com/dotnet/efcore/blob/c6b5eac69fb2ec5dfdb4b990837d8cfdd91753a2/src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs#L167-L170

## My Solution:
Include a `hasDestructiveOperations` property in the `--json` response of `dotnet ef migrations list`. The json response can be programatically parsed and queried on to see if any of the migrations added in a PR are ones that could be destructive. Then the pipeline can choose to do whatever it wants, like add a required reviewer or add a label. The new output would look like:
```diff
[
  {
    "id": "20210617183900_DropAllTables",
    "name": "DropAllTables",
    "safeName": "DropAllTables",
    "applied": true,
+   "hasDestructiveOperations": true
  }
]
```

**Comment by ajcvickers** [comment]
@justindbaur We discussed this, but the problem is that while a scaffolded migration may have the potential for a destructive change, this may not be true after the migration has been edited, or just because of the state of the data. Likewise, a migration that was not destructive could be edited such that it is. So we feel including the information here is likely going to be misleading.

**Comment by justindbaur** [comment]
@ajcvickers Sorry I missed that comment, I do see the possible confusion it could create and there isn't a good json property that could convey that 😄. I can utilize existing public API's in a unit test to get the info I need, thanks for your time!
