### ISSUE TITLE
Query: Relational: Interaction between custom fragment translator and requires materialization flag

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#3132]
The interaction between custom fragment translators and the requires materialization detection is broken right now.

**Comment by smitpatel** [comment]
We should fix this before 2nd anniversary of the bug :trollface:

**Comment by ajcvickers** [comment]
We discussed this again in triage and decided that we won't do this now based on YAGNI. If this becomes an actual issue with some real custom fragment translator, then we would fix the issue at that time, using the real issue to drive exactly what is needed.

As always, we will reconsider this with enough feedback. We would also consider a community PR for this.
