### ISSUE TITLE
Setting a default value to a binary field causes an "everlasting" migration

### ISSUE THREAD

**Issue by montoner0** [dotnet/efcore#31330]
## File a bug

When a binary (byte[]) field is assigned a default value an "everlasting" migration appears (same change appears in all subsequent migrations).

### Include your code

[ClassLibrary1.zip](https://github.com/dotnet/efcore/files/12129874/ClassLibrary1.zip)

### Include provider and version information

EF Core version: 7.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer (the same with npgsql)
Target framework: .NET 6.0
Operating system: Windows 10 22H2
IDE: Visual Studio 2022 17.6.4

**Comment by bricelam** [comment]
This was probably fixed by PR #31396
