### ISSUE TITLE
Cascade delete child entities, where parent has no navigation property to children

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#31340]
I've got entities which I track revisions on. Each revision is somewhat heavy, so I've option to have an additional property called `.CurrentRevision` but otherwise you have to explicitly select from the `DbSet<DocumentRevision>` to query child revisions by `DocumentId`.

``` cs
public class Document
{
   public int Id{ get ;set; }
   public string Description{ get; set; }
   public DocumentRevision CurrentRevision { get; set; }
}

public class DocumentRevision
{
   public int Id { get; set; }
   public int DocumentId { get; set; }
   public Document Document { get; set; }
}
```

We manually set `CurrentRevision` when a new revision is created. Ideally pulling Document only really fetches the current revision.

Being that there is no `List<DocumentRevision>`, it seems like efcore wont automatically delete children with cascade delete. Being that the difference to the underlying schema wont actually change between having `List<DocumentRevision>`, and not having that navigation property... I'd assume there is SOME way to say delete `DocumentRevision` that reference the parent document, when document is deleted.

Is there a way to set this up explicitly in mapping `OnModelCreating` or should I just expect to have to check for revisions associated with the `Document` and delete those as a part of our business logic when we delete `Document`?

Note: if anyone has better places to ask this sort of question, I'll use that rather than creating an issue as a question in the future.

EF Core version: 6.0.0
Database provider: (e.g. Npgsql)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
@ronnyek Cascade delete is not determined by navigation property. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
