### ISSUE TITLE
Not detecting changes when setting a nullable relationship property to null

### ISSUE THREAD

**Issue by ctrl-alt-d** [dotnet/efcore#31346]
I am currently facing an issue with Entity Framework (EF) where it doesn't recognize value changes when I set a nullable property to null. After investigating, I noticed that the `DetectChanges` method fails to detect this specific change.

Here's a code snippet illustrating the problem:

```c#
using var db = Db_factory.CreateDbContext();
var item1 = db.Items.Find(1)!; // Existing item with related Tag.
item1.Tag = null;  // From existing value to null
db.SaveChanges();
item1.Tag; // <-- Not null here! Why?!
```

As a workaround to address this situation and help EF detect the change, I have tried loading the related model like so:

```
db.Entry(item1).Reference(i => i.Tag).Load(); // Workaround
item1.Tag = null;  
```

However, I've realized that this workaround comes with a potential downside: if I forget to load the related item, my code will fail. I'm concerned that relying on this approach might not be the best solution in the long run.

I would greatly appreciate any insights or suggestions on how to effectively deal with this issue. How can I make sure EF detects the value change without resorting to potentially risky workarounds?

### Full test

Here a complete full test to reproduce the issue:

```c#
/*
dotnet add package FluentAssertions
dotnet add package Microsoft.EntityFrameworkCore
dotnet add package Microsoft.EntityFrameworkCore.Sqlite
*/
namespace efsetp;

using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

public class Item
{
    public int Id { get; set; }
    public Tag? Tag { get; set; }
}

public class Tag
{
    public int Id { get; set; }
    public override string ToString() => $"Tag: {Id}";
}

public class TestDbContext: DbContext
{
    public DbSet<Item> Items { get; set; } = default!;
    public DbSet<Tag> Tags { get; set; } = default!;
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        =>
        optionsBuilder
            .UseSqlite("Data Source=file:f1?mode=memory&cache=shared");
}

public class RelationshipNullableItegrationTest
{
    private const int ItemNumber1 = 1, TagId1 = 1, TagId2 = 2;
    private readonly IDbContextFactory<TestDbContext> Db_factory = 
        new ServiceCollection()
        .AddDbContextFactory<TestDbContext>()
        .BuildServiceProvider()
        .GetRequiredService<IDbContextFactory<TestDbContext>>();

    [Fact]
    public void Changing_related_model()
    {
        // Arrange            
        using var db = Db_factory.CreateDbContext();
        db.Database.EnsureCreated();

        var tag1 = new Tag() {Id = TagId1};
        var item1 = new Item() {Id = ItemNumber1, Tag = tag1};
        db.Items.Add(item1);

        var tag2 = new Tag() {Id = TagId2};
        db.Tags.Add(tag2);
        db.SaveChanges();

        // Act - Assert
        UoW_changetag(TagId2);
        db.Entry(item1).Reload();
        (item1.Tag?.Id).Should().Be(
            TagId2, 
            "We can change tag from 1 to 2. THIS IS OK");

        UoW_changetag(TagId1);
        db.Entry(item1).Reload();
        (item1.Tag?.Id).Should().Be(
            TagId1, 
            "We can change tag from 2 to 1. THIS IS OK");

        UoW_changetag(null);
        db.Entry(item1).Reload();
        item1.Tag.Should().BeNull(
            "We set tag to null. THIS FAILS! WHY?"
        );
    }

    private void UoW_changetag(int? tagid)
    {
        using var db = Db_factory.CreateDbContext();
        var item1 = db.Items.Find(ItemNumber1)!;
        Tag? tag = db.Tags.FirstOrDefault(tag=>tag.Id == tagid);
        // db.Entry(item1).Reference(i => i.Tag).Load(); // Workaround
        item1.Tag = tag;
        db.SaveChanges();
    }
}
```

>Expected item1.Tag to be <null> because We set tag to null. THIS FAILS! WHY?, but found Tag: 1.

### Versions:

* Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Sqlite version 7.0.2
* SDK 7.0.302

Thank you for your time and expertise!

**Comment by ctrl-alt-d** [comment]
I understand. The issue is that we are conflating `null` to represent two different semantics: "Not loaded" and "No value."

Unfortunately, using `Include` here is not possible, as `Find` does not have the `Include` extension available. (I am aware that using `First` is an option, but it would raise a new select each time.) Consequently, I must always remember to execute a `Reference.Load` before setting `null` to a nullable navigation property.

Understood, are you so kind to close issue?

**Comment by ajcvickers** [comment]
@ctrl-alt-d Find has no advantage over running a query in this situation. The result will be the same, but Find will do more work and take longer to return it.

**Comment by ctrl-alt-d** [comment]
@ajcvickers Thank you for providing the extra explanation. The test shared was a minimal, complete, and verifiable example, and I agree that using `First + Include` is the appropriate approach in this case.

However, my team believed that implementing the repository pattern and using the `GetByID` method with Find was a good idea. `Find` avoids reloading the model from the database since it is tracked by the context, additionally, the navigation properties' getter performs a `Reference.Load` operation (the repository pattern we implemented has a kind of custom lazy load system) All criticism is welcome.

Best regards.
