### ISSUE TITLE
Why a left join when the right part is the result?

### ISSUE THREAD

**Issue by DJDoena** [dotnet/efcore#31350]
## Ask a question

I have a query for object `Z` where the start of the query is object `X` and goes from `X` via `Y` to `Z`. Since not every `Y` leads to a `Z`, there is a lot of `null` results because the Linq is doing a `left join` instead of an `inner join`:

Note: `X` is a cross table between `V` (not relevant) and `X`. `Z` contains a mandatory reference to `Y` but not every `Y`has a reference to `Z`

```C#
var xIds = new List<int>() { 78, 85 };

var zResult = _context.TableX
    .Where(x => xIds.Contains(x.Id))
    .Select(x => x.TableY.TableZ)
    .ToList();
```
```SQL
SELECT [z].[zId]
    FROM [TableX] AS [x]
    INNER JOIN [TableY] AS [y] ON [x].[yId] = [y].[yId]
    LEFT JOIN [TableZ] AS [z] ON [y].[yId] = [z].[yId]
    WHERE [x].[xId] IN (78, 85)
```

The fix is to add another `null` check at the end:

```C#
var xIds = new List<int>() { 78, 85 };

var zResult = _context.TableX
    .Where(x => xIds.Contains(x.Id))
    .Select(x => x.TableY.TableZ)
    .Where(z => z != null)
    .ToList();
```
```SQL
SELECT [z].[zId]
    FROM [TableX] AS [x]
    INNER JOIN [TableY] AS [y] ON [x].[yId] = [y].[yId]
    LEFT JOIN [TableZ] AS [z] ON [y].[yId] = [z].[yId]
    WHERE [x].[xId] IN (78, 85)
        AND ([z].[zId] IS NOT NULL)
```

But why return `null` objects in the result?

If this were pure `SQL` I would have written the query the other way around anyway:

```SQL
SELECT TableZ.TableZId
    FROM TableZ
    WHERE TableZ.yId IN
        (SELECT TableY.yId FROM TableY WHERE TableY.yId IN
            (SELECT TableX.yId FROM TableX WHERE TableX.xId IN (78, 85))
        )
```
or even leave out `Y` completely to jump directly from `Z` to `X`

```SQL
SELECT TableZ.TableZId
    FROM TableZ
    WHERE TableZ.yId IN
        (SELECT TableX.yId FROM TableX WHERE TableX.xId IN (78, 85))
```

[JoinTest.zip](https://github.com/dotnet/efcore/files/12162477/JoinTest.zip)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by DJDoena** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

[JoinTest.zip](https://github.com/dotnet/efcore/files/12161889/JoinTest.zip)

**Comment by DJDoena** [comment]
Add info: I've created a full-framework project with EF6 and attached it to the sample project. It generates a structurally different `SQL` and only returns the desired non-`null` objects

```SQL
SELECT
    [Extent2].[zId] AS [zId],
    [Extent2].[yId] AS [yId],
    [Extent2].[zName] AS [zName]
    FROM  [dbo].[TableX] AS [Extent1]
    INNER JOIN [dbo].[TableZ] AS [Extent2] ON [Extent1].[yId] = [Extent2].[yId]
    WHERE [Extent1].[vId] IN (78, 85)
```
[JoinTest.zip](https://github.com/dotnet/efcore/files/12162477/JoinTest.zip)

**Comment by ajcvickers** [comment]
Note for triage: EF8 generates the following query:

```sql
      SELECT [t1].[zId], [t1].[yId], [t1].[zName]
      FROM [TableX] AS [t]
      INNER JOIN [TableY] AS [t0] ON [t].[yId] = [t0].[yId]
      LEFT JOIN [TableZ] AS [t1] ON [t0].[yId] = [t1].[yId]
      WHERE [t].[vId] IN (
          SELECT [v].[value]
          FROM OPENJSON(@__vIds_0) WITH ([value] int '$') AS [v]
      )
```

**Comment by ajcvickers** [comment]
@maumar to investigate.

**Comment by maumar** [comment]
looking at the EF Core model, this is by design. You have X-Y relationship where Y is the principal and then Y-Z where Y is principal again. For the first navigation we are going from dependent to principal so we can safely produce INNER JOIN, but going from principal do dependent in Y-Z we need to use LEFT JOIN because case where there is a Y without corresponding Z, and we can't know the user's intention here. If you want to remove those you need to add your own filter clause, or write join in a linq query manually:

```cs
context.TableX
    .Where(x => vIds.Contains(x.vId))
    .LeftJoin(context.TableZ, x => x.yId, z => z.yId, (x, z) => z).ToList();
```

Going from X to Z, skipping Y in the dependent to principal to dependent is a nice optimization and we should apply it - will file an issue to track this improvement.

**Comment by jerviscui** [comment]
> looking at the EF Core model, this is by design. You have X-Y relationship where Y is the principal and then Y-Z where Y is principal again. For the first navigation we are going from dependent to principal so we can safely produce INNER JOIN, but going from principal do dependent in Y-Z we need to use LEFT JOIN because case where there is a Y without corresponding Z, and we can't know the user's intention here. If you want to remove those you need to add your own filter clause, or write join in a linq query manually: 
> 
> ```cs
> context.TableX
>     .Where(x => vIds.Contains(x.vId))
>     .LeftJoin(context.TableZ, x => x.yId, z => z.yId, (x, z) => z).ToList();
> ```

Can LeftJoin() be executed correctly?

The test will get exception:

```cs
var ss = Blogs.LeftJoin(BlogTags, outer => outer.Id, inner => inner.BlogId, (b, t) => new { b, t })
    .ToList();
```

> NotSupportedException
> Specified method is not supported.

**Comment by maumar** [comment]
@jerviscui ahh, my bad. I meant to provide example with inner join, as this was what @DJDoena was expecting. (corrected in my original post). For left join you can use 

```cs
from x in context.TableX
join z in context.TableZ on x.yId equals z.yId into grouping
from z in grouping.DefaultIfEmpty()
select z;
```

**Comment by jerviscui** [comment]
@maumar thx!

I see that a new extension method LeftJoin has been added to EF Core, but it doesn't work!

**Comment by jerviscui** [comment]
Ruthless. Ha ha ha. 🤣
