### ISSUE TITLE
SQLite: Add EF.Functions.Unhex

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#31355]
This is the inverse of the existing `Hex` function.

**Comment by roji** [comment]
Alternatve naming Dewitch()? :rofl:

**Comment by smnsht** [comment]
@bricelam Hello, Brice

Shell I convert my draft to PR? https://github.com/dotnet/efcore/pull/31454

**Comment by bricelam** [comment]
@smnsht Yeah, looks like it’s ready to me
