### ISSUE TITLE
How to use ExecuteUpdate for update from ExpandoObject

### ISSUE THREAD

**Issue by P9avel** [dotnet/efcore#31367]
I am  want to use ExecuteUpdate for update objects in DB from ExpandoObject.  I am wrote code

```C#
private static int BulkExecuteUpdate<TEntity>(IQueryable<TEntity> queryable, ExpandoObject expandoObject)
       where TEntity : class
    {
        Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> AppendSetProperty(
            Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> left,
            Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> right)
        {
            var replace = new ReplacingExpressionVisitor(right.Parameters, new[] { left.Body });
            var combined = replace.Visit(right.Body);
            return Expression.Lambda<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>>(combined, left.Parameters);
        }
        
        var modifiedProperties = (IDictionary<string, object>)expandoObject;
        
        Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> setPropertyCalls = _ => _;
        foreach (var modifiedProperty in modifiedProperties)
        {
            var propInfo = typeof(TEntity).GetProperty(modifiedProperty.Key);

            setPropertyCalls = AppendSetProperty(setPropertyCalls, s => s.SetProperty(e => Expression.Property(Expression.Constant(e, e.GetType()), propInfo), modifiedProperty.Value));
        }

        return queryable.ExecuteUpdate(setPropertyCalls);
    }
```

But my code not works. Issue in s => s.SetProperty(e => Expression.Property(Expression.Constant(e, e.GetType()), propInfo), modifiedProperty.Value   Please help me, how to write SetProperty call  correctly?

EF Core version: 7.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
@P9avel This is not something that is supported by EF Core. You may be able to do something custom with expression trees, but I wouldn't count on it.

**Comment by roji** [comment]
@P9avel it should indeed be possible to construct the expression tree as you're attempting to do, but there seem to be issues in the tree structure you're generating. Dynamically constructing expression trees is an advanced usage and must be done in a precise manner, and unfortunately I don't have time to dive into your code and find your exact error.

I'd advise comparing your generated expression tree to the expression tree that's generated when ExecuteUpdate is used in the normal way, and try to locate any discrepancy there. Otherwise, you can ask for help from other users on stackoverflow or similar.

**Comment by P9avel** [comment]
How to see  expression tree that's generated when ExecuteUpdate is used ? can you to describe by steps

**Comment by roji** [comment]
If you look at a simple line using ExecuteUpdateAsync:

```c#
_ = await ctx.Blogs.ExecuteUpdateAsync(s => s.SetProperty(b => b.Name, "foo"));
```

You'll see that the parameter type is `Expression<Func<SetPropertyCalls<Blog>, SetPropertyCalls<Blog>>>`. You can then simply extract the argument out to a variable as follows:

```c#
Expression<Func<SetPropertyCalls<Blog>, SetPropertyCalls<Blog>>> foo = s => s.SetProperty(b => b.Name, "foo");

_ = await ctx.Blogs.ExecuteUpdateAsync(foo);
```

You now have the variable `foo` which contains the expression tree of the right shape. You can inspect it with the debugger to understand its exact shape, and make sure that your dynamic construction logic produces the same form.

**Comment by P9avel** [comment]
Many thx for detail example. Very helped to me

**Comment by roji** [comment]
Happy it helped!
