### ISSUE TITLE
Programmatic approach to avoid DateOnly / TimeOnly mapping in EF Core 8

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#31377]
In the breaking changes docs for EF Core 8 it is mentioned that you can use T4 templates to avoid the introduction of DateOnly and TimeOnly in your EF Core model. Is there a programmatic (non t4) approach to achieve the same goal?

**Comment by roji** [comment]
@ErikEJ it should be possible to replace SqlServerTypeMappingSource with an inherited version which returns DateTime/TimeSpan type mappings when resolving from SQL Server `date`/`time`.

Do you see any particular concern here?

**Comment by ErikEJ** [comment]
@roji Thanks.

I am planning EF Core Power Tools support for EF Core 8 reverse engineering, and as "always" users will complain that someone moved their cheese, and I would like to offer a simple solution to that. I already have a "Map DateOnly/TimeOnly" flag, which I intend to turn on by default for EF Core 8, but I would like to support it being turned off for EF Core 8 in a simple way.

**Comment by roji** [comment]
We can also have a snippet of such a replacement type mapping source in our breaking change mitigation note if we want...

**Comment by ErikEJ** [comment]
@roji Cool, thanks, that worked great!

**Comment by ErikEJ** [comment]
@roji @ajcvickers What am i doing wrong? The properties stay DateOnly/TimeOnly


```csharp
                    serviceCollection.AddSingleton<IRelationalTypeMappingSource, SqlServerTypeMappingSource>(
                        provider => new RevEng.Core.SqlServerTypeMappingSource(
                            provider.GetService<TypeMappingSourceDependencies>(),
                            provider.GetService<RelationalTypeMappingSourceDependencies>(),
                            provider.GetService<ISqlServerSingletonOptions>(),
                            options.UseDateOnlyTimeOnly));


using System;
using System.Data;
using Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

namespace RevEng.Core
{
    public class SqlServerTypeMappingSource : Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerTypeMappingSource
    {
        private readonly bool useDateOnlyTimeOnly;

        public SqlServerTypeMappingSource(TypeMappingSourceDependencies dependencies, RelationalTypeMappingSourceDependencies relationalDependencies, ISqlServerSingletonOptions singletonOptions, bool useDateOnlyTimeOnly)
            : base(dependencies, relationalDependencies, singletonOptions)
        {
            this.useDateOnlyTimeOnly = useDateOnlyTimeOnly;
        }

        protected override RelationalTypeMapping FindMapping(in RelationalTypeMappingInfo mappingInfo)
        {
            if (!useDateOnlyTimeOnly && (mappingInfo.ClrType == typeof(DateOnly)))
            {
                return new SqlServerDateTimeTypeMapping("date", DbType.Date);
            }

            if (!useDateOnlyTimeOnly && (mappingInfo.ClrType == typeof(TimeOnly)))
            {
                return new SqlServerTimeSpanTypeMapping("time");
            }

            return base.FindMapping(mappingInfo);
        }
    }
}

```

**Comment by roji** [comment]
@ErikEJ when scaffolding, RelationalTypeMappingInfo has no ClrType - only a StoreType (i.e. the database type as a string). You should be matching on that.

ClrType is for the other side, i.e. when working with a code model where the CLR type of properties are known and we want to resolve the database types from them.

**Comment by ErikEJ** [comment]
Ah!
