### ISSUE TITLE
underlying sql log

### ISSUE THREAD

**Issue by askdong** [dotnet/efcore#31375]
Dear brothers，

why efcore7 always write underlying sql log to Linux journal，even I add loggerfactory to filter loglevel with warning？  I used Oracle.EntityFrameworkCore.    logs look like below:
![image](https://github.com/dotnet/efcore/assets/3634698/a78ee6ac-780e-4df5-9972-5866035049e9)

thanks!

**Comment by roji** [comment]
@askdong these don't look like logs coming out of EF Core, are they maybe logs on the Oracle database side? If so, EF has no control over them.

Otherwise, you may need to ask the maintainers of the Oracle provider - we don't maintain that.

**Comment by askdong** [comment]
@roji, those select sql logs as shown came from my business application,  i looked for oracle efcore document, it says that
![image](https://github.com/dotnet/efcore/assets/3634698/64fd97e5-aabe-49a9-918f-8e7465e6f90d)

so oracle's log mechanism should work same as  MS efcore.
I can disable/enable those log ouput to windows console and windows log file by setting log level, but i can NOT control those log output to redhat journal,  it's very wired.

**Comment by roji** [comment]
> I can disable/enable those log ouput to windows console and windows log file by setting log level, but i can NOT control those log output to redhat journal

That sounds like an issue in your logging configuration - if you can control the output to the console/log file, you should be able to do it in the same way for the redhat journal. It doesn't sound like either an EF or an Oracle provider problem...
