### ISSUE TITLE
Query: Distinct on entity containing primitive array gives wrong results when projecting multiple collections due to result bucketing issues

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#31398]
we rely on property.GetKeyValueComparer() as comparers for identifiers in result coordinator. This can happen in case of Distinct/GroupBy, where we can't use key as identifier (if it's not projected). 

Problem is that for collection of primitives, the comparer does ref comparison, so every row looks like a new element to the result coordinator, and we get data corruption.

As a simple workaround we can omit collection of primitives from identifier list, that works fine but would give wrong results still, if entities next to each other (in the collection) differ only by their collection of primitives. Proper fix is to use structural comparer (?)

@roji @ajcvickers

**Comment by roji** [comment]
@maumar if you have any time before you leave and it's not too complicated, could you post an example LINQ which fails?

**Comment by maumar** [comment]
any json projection of distincted collection and another collection before/after. Collection with distinct must have property of array of primitives. Can be regular entity also (i think - the code is the same for both)

```cs
ss.Set<JsonEntityBasic>()
                .OrderBy(x => x.Id)
                .Select(x => new
                {
                    First = x.OwnedReferenceRoot.OwnedCollectionBranch.Distinct().ToList(),
                    Second = x.EntityCollection.ToList()
                })
                .AsNoTracking()
```

```
ss.Set<JsonEntityBasic>()
                .OrderBy(x => x.Id)
                .Select(x => new
                {
                    First = x.OwnedReferenceRoot.OwnedReferenceBranch.OwnedCollectionLeaf
                        .Where(xx => xx.SomethingSomething != "Baz").ToList(),
                    Second = x.OwnedCollectionRoot.Distinct().ToList(),
                    Third = x.OwnedCollectionRoot
                        .Select(xx => xx.OwnedCollectionBranch.Where(xxx => xxx.Date != new DateTime(2000, 1, 1)).ToList()),
                    Fourth = x.EntityCollection.ToList()
                })
                .AsNoTracking()
```
