### ISSUE TITLE
Migrations and model snapshot for primitive collections

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#31414]

**Comment by bricelam** [comment]
Double-check complex type coverage too

**Comment by bricelam** [comment]
From https://github.com/dotnet/efcore/issues/31630#issuecomment-1709007019

> check that we're not putting user CLR types in migrations for primitive collections (or complex types)

**Comment by bricelam** [comment]
Not seeing any issues with primitive collections. They really are just strings to migrations and the snapshot. I'll double-check that we have automated tests before closing.

Seeing a few issues with complex types. I'll keep testing and file separate issues.
