### ISSUE TITLE
Navigation Property that uses a foreign key from a different table for a middle table.

### ISSUE THREAD

**Issue by dcox2005** [dotnet/efcore#31410]
So I'm trying to do something that I would consider different and unusual but I'm hoping it can be done.  I'm using EF Core 6.0 and MariaDb. So here is what I would like to do. I want to have a GlobalEntity class that has a unique Id for every object across multiple tables.  I have an Address class that saves addresses, and would have a GlobalEntityId saved to it.  I have a Location class that would contain it's own GlobalEntityId, and I want it to access a List<Address> Addresses navigation property.  I have a Manufacturer class that also has it's own GlobalEntityId, and I want it to access a List<Address> Addresses navigation property.  What I don't want to do, is create LocationAddress and ManufacturerAddress middle tables and add both Location and Manufacturer navigation properties to Address.  I would like to use a GlobalEntityAddress table that would act as the middle table for anything that has a GlobalEntityId and an Address.  Can this be done using EF Core with fluent api? I have looked high and low, and I can't find an answer. Here is some of my code to help:

```C#
public class GlobalEntity
{
    [Key]
    public int Id { get; set; }
}

public class Address : Data<Address>
{
    [Key]
    public int Id { get; set; }
    public string Country { get; set; } = null!;
    public string State { get; set; } = null!;
    public string City { get; set; } = null!;
    public string Zip { get; set; } = null!;
    public string StreetAddress { get; set; } = null!;
}

public class GlobalEntityAddress
{
    public int GlobalEntityId { get; set; }
    public GlobalEntity GlobalEntity { get; set; } = null!;
    public int AddressId { get; set; }
    public Address Address { get; set; } = null!;
}

public class Location
{
    [Key]
    public int Id { get; set; }
    public int GlobalEntiyId { get; set; }
    public GlobalEntity GlobalEntity { get; set; } = null!;
    public List<Address>? Addresses { get; set; }
}

public class Manufacturer
{
    [Key]
    public int Id { get; set; }
    public int GlobalEntiyId { get; set; }
    public GlobalEntity GlobalEntity { get; set; } = null!;
    public List<Address>? Addresses { get; set; }
}

```

I have tried to do various things to link these together, but the only way I can think to make it work is to change GlobalEntity to have a List<Address> Addresses navigation property and then when I'm doing my query's to Include the GlobalEntity ThenInclude Addresses. I'd prefer just to set it up so that the Location or Manufacturer class has access to it directly. 

And for anyone curious, I'm using a GlobalEntityId because it allows me to make updates to an object and change any field on it, and reinsert it into the database as a new row but still know that it was this one object originally.  My understanding is that this is the best way for recreating historical data.

EF Core version:
Target framework: (e.g. .NET 6.0)

**Comment by dcox2005** [comment]
I'm confused on how this is many-to-many.  From what I understand, wouldn't it be one-to-many?  A Location/Manufacturer has many Address, but an Address belongs to one Location/Manufacturer.
Also, I'm not seeing a way to do just what I want.  I see 'Unidirectional many-to-many' which relies on the primary key of each object, but doesn't use the GlobalEntityId foreign key.  I also see 'Many-to-many with alternate keys' which could use the foreign key but it doesn't seem to be able to avoid putting the Navigation Property on Address.

**Comment by ajcvickers** [comment]
@dcox2005 If it's not many-to-many, then I don't really understand what it is you're trying to achieve, but I suspect it's not going to be possible.
