### ISSUE TITLE
Is there or will there be support for creating index on function column 

### ISSUE THREAD

**Issue by CamusGao** [dotnet/efcore#31418]
On some databases, I can create an index `idx_xxx` using sql below.
```sql
create index idx_xxx on xxx(lower(a));
```
And when I perform a query like
```sql
select  * from idx_xxx where lower(a) = 'abc';
```
the index will be used.
Is there or will there be suppport for creating index on function column?

**Comment by roji** [comment]
Duplicate of #28360

**Comment by roji** [comment]
See https://github.com/dotnet/efcore/issues/28360#issuecomment-1666821461 for some notes on how to do this yourself.

**Comment by hexxone** [comment]
For anyone coming across the same problem, please take a second and vote for the issue mentioned by roji above, so that Microsoft will prioitize it for implementation.
