### ISSUE TITLE
Bump Cosmos to latest version on EF Core 7

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#31419]
To pull in a secure patch version by default.

**Comment by bricelam** [comment]
Looking at [the changelog](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md), the last mention of security fix was for version 3.21.0. All our supported versions already depend on that version or higher. Is there an undocumented fix we're trying to include?

6.0 | 7.0 | 8.0
--- | --- | ---
3.21.0 | 3.30.1 | 3.35.3 (latest)

AFAICT, their policy is that only the latest 3.x package is "supported" (contains the latest security fixes). Should we be releasing new 6.0.x and 7.0.x (and 8.0.x) patches every time they release?

> Make sure that your applications, when using the .NET V3 SDK, are using at least the version described here to have all the critical fixes.

But they also have a minimum recommended version(s). Should we update to those?

> The **minimum recommended version is 3.33.0 when using Direct mode and 3.35.1 for Gateway mode**.

Or are users responsible for keeping their closure of dependencies up to date?

**Comment by ajcvickers** [comment]
I don't think it' sustainable for us to try to keep up-to-date. The reality is that dependencies are going to go out of support, at which point customers need to update to stay in support.

**Comment by bricelam** [comment]
Closing. Vulnerable packages should be marked as such on NuGet.org and VS should warn you to explicitly upgrade those packages. This is really the only sustainable process. If explicitly updating one of our dependencies in a patch will have a significant impact on user's security (as it has in the past with SqlClient) we can consider it on a case-by-case basis.
