### ISSUE TITLE
Please give me example how replace IModificationCommand to my implementation in MyDbContext

### ISSUE THREAD

**Issue by P9avel** [dotnet/efcore#31434]
Sorry for  dummy questoin. Can you to show example how replace IModificationCommand to my implementation  in MyDbContext?

**Comment by P9avel** [comment]
i am want not send some values to insert. I am now did before SaveChanges follow code 

` 
 public static readonly FieldInfo BeforeSaveBehavior = typeof(RuntimeProperty).GetField("_beforeSaveBehavior", BindingFlags.NonPublic | BindingFlags.Instance);
var runtimeProperty = property.Metadata as RuntimeProperty;
                   BeforeSaveBehavior.SetValue(runtimeProperty, isModified ? PropertySaveBehavior.Save : PropertySaveBehavior.Ignore);`

I am want to send only changed properties and other not send. I am have isModified flag and need calculate for each object. My code works when saved only 1 object. And i have issue with many rows because my code calls only once before SaeChanges

**Comment by roji** [comment]
@P9avel I'd strongly advise overriding SaveChanges/SaveChangesAsync in your code, going over the tracked entities, and modifying their state as suits you - this is probably a much easier way to accomplish what you want than to replace IModificationCommand. You can find out more about doing this on [this doc page](https://learn.microsoft.com/en-us/ef/core/change-tracking/entity-entries).

**Comment by P9avel** [comment]
I cannot, i think. for example, i have  

class Product
{
  public int Id {get;set;}
  public int Count {get;set;}
}

Now i am want to create var p1 = new Product { Id = 123 }. In my case not need send Count to db because user not set value. I am want to get
insert into Product (id) values(123). In this case ms sql calculated default value for Count.  In other case var p1 = new Product { Id = 123, Count = 0 }
In this case need to generate sql insert into Product (id, count) values(123, 0)

**Comment by roji** [comment]
How is Count database-generated? If it's a computed column, you should be [telling this to EF](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns), and it won't send the zero value to the database. Are there *any* cases where the user *does* set Count, and you want that to get sent?

**Comment by P9avel** [comment]
>>How is Count database-generated?
Default
>> Are there any cases where the user does set Count, and you want that to get sent?
Yes.
In common case, if user set any value (and zero) then need to send to dbms. If user not set value and i am dont need send value to sql.   Possible you to show code with replacing IModificationCommand?

**Comment by roji** [comment]
From your description, Count sounds like a simple column with a default value, [as described here in the docs](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#default-values). If you've properly configured it that way (see those docs), EF should not be sending Count to the database when it's equal to 0 (the CLR default).

Note that there is no way to distinguish between `new Product { Id = 123 }` and `new Product { Id = 123, Count = 0 }`, the two produce the exact same Product instance; so you cannot vary behavior based on this. If you want to make a distinction here, you can make Count nullable (`int?`); in that case, if unset it will be null, but the user can set it to 0 to have it sent to the database. However, there really isn't any point in doing if the column default is zero in the database; whether the user sets Count to zero or not - and whether EF sends it to the database or not - yields the same result.

> Possible you to show code with replacing IModificationCommand?

I think you're barking up the wrong tree here with IModificationCommand - I haven't seen any reason for you to need that. Can you clearly explain why EF's support for [plain old default columns](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#default-values) is insufficient?

**Comment by ajcvickers** [comment]
As discussed above, `IModificationCommand` is not the appropriate place to make this change, so showing an example doesn't make sense.
