### ISSUE TITLE
Support for Relational Properties as Parameters in Stored Procedures

### ISSUE THREAD

**Issue by Shaoranlaos** [dotnet/efcore#31441]
The stored procedure support for EF Core does not allow to use navigational properties as a parameter for the procedure.
With this it is not possible to update/insert a reference via a stored procedure.

At the moment this leads to:
```
The expression 'ep => ep.Parameter.Id' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')
```

The StoredProcedureBuilder.HasParameter() Lambda should allow to define fields of navigational properties (e.g. 1:n dependencies on the non-list side).

Example:
```
...
        entityBuilder.UpdateUsingStoredProcedure("ParamUpdate",
                spBuilder =>
                {
                    storedProcedureBuilder.HasParameter(ep => ep.Parameter.Id);
                }
...
```

**Comment by roji** [comment]
You should be able to do this by updating the foreign key property on the dependent side - have you tried this and did you encounter issues?

**Comment by Shaoranlaos** [comment]
I'm not sure what you mean from the dependent side?
I can not add the field from a foreign key property (in my case the Id of the Parameter property to update on the entity) as a parameter to the stored procedure. It gives my the above mentioned error message.

**Comment by Shaoranlaos** [comment]
Here is an example DbContext Class where the problem happens when a migration tried to be added:

```
using Microsoft.EntityFrameworkCore;

namespace EFCoreSProcTest
{
    public class Catalog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Entry> Entries { get; set; } = new();
    }

    public class Entry {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Catalog Catalog { get; set; }
    }

    public class DBContext : DbContext
    {
        public virtual DbSet<Catalog> Catalogs { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=SProcTest;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False");
                optionsBuilder.EnableSensitiveDataLogging();
                optionsBuilder.LogTo(Console.WriteLine);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Entry>(entryBuilder =>
            {
                entryBuilder.UpdateUsingStoredProcedure(sProcBuilder => 
                {
                    sProcBuilder.HasParameter(e => e.Catalog);
                });
            });
        }
    }
}
```

**Comment by roji** [comment]
In your example above, you have a one-to-many relationship where Entry is the dependent and Catalog is the principal; in other words, an Entry cannot exist without a Catalog, but a catalog can exist without Entries. That means that in the database, each Entry row has a foreign key containing the primary key values of its Catalog. Since you don't have a foreign key property in your model (on Entry), EF creates a "shadow" foreign key behind the scenes called CatalogId [See the relationship docs](https://learn.microsoft.com/en-us/ef/core/modeling/relationships) for these basic concepts.

You should be able to directly reference the shadow foreign key by calling EF.Property in your HasParameter:

```c#
entryBuilder.UpdateUsingStoredProcedure(sProcBuilder => sProcBuilder
    .HasOriginalValueParameter(e => e.Id)
    .HasParameter(e => e.Name)
    .HasParameter(e => EF.Property<int>(e, "CatalogId")));
```

But that indeed doesn't work, although it should. As a workaround, you can add an explicit foreign key property in your model and reference that:

```c#
entryBuilder.UpdateUsingStoredProcedure(sProcBuilder => sProcBuilder
    .HasOriginalValueParameter(e => e.Id)
    .HasParameter(e => e.Name)
    .HasParameter(e => e.CatalogId);
```

But you definitely cannot as you're trying above `e.Catalog.Id` - that would mean that updating the Entry changes the primary key of its Catalog, rather than changing the foreign key on the Entry.

**Comment by Shaoranlaos** [comment]
What if i would like to move the Entry into another Catalog?
Isn't the idea that i than set the new Catalog on the Entry.Catalog property and that should update the foreign key column?
Or have i a fundamental missunderstanding?

**Comment by ajcvickers** [comment]
@roji Instead of `.HasParameter(e => EF.Property<int>(e, "CatalogId")));` shouldn't you just do `.HasParameter("CatalogId");`. We generally don't support `Property` calls in model building, although we have discussed doing so.

**Comment by roji** [comment]
Absolutely, you're right - forgot amor that. This should indeed work!
