### ISSUE TITLE
How to define global query filter expression using multi tenancy/non entity values in IEntityTypeConfiguration implementations?

### ISSUE THREAD

**Issue by Doz93** [dotnet/efcore#31459]
In a demo project I have worked on I wanted to move my global query filters out of OnModelCreating and put them in a separate implementation that is called from OnModelCreating instead, My goal is to improve readability and separation of concerns (clearer separation between domain and infrastructure concerns). However, after the change the generated query started to look a bit different when working with an entity that has a global query filter which invokes a method on a service.

My original implementation looked like this:

```
public class TeamDbContext : DbContext
{
     private readonly IFeatureEnabledService featureEnabledService;
...
     public DbSet<FavoriteTeam> FavoriteTeams {get;set;} = null!;

     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
          modelBuilder.Entity<FavoriteTeam>(x => {
             x.HasQueryFilter(ft => ft.Removed == null && featureEnabledService.NewFeatureIsEnabled());
          });
     }

}
```
This worked fine and the produced query looks like this:

```
SELECT [f].[Id], [f].[Name], [f].[Removed]
FROM [FavoriteTeams] AS [f]
WHERE ([f].[Removed] IS NULL) AND @__ef_filter__p_0 = CAST(1 AS bit)
```

After the change the implementation looks like this

```
public class TeamDbContext : DbContext
{
     private readonly IDomainConfiguration domainConfiguration;
...
     public DbSet<FavoriteTeam> FavoriteTeams {get;set;} = null!;

     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
          domainConfiguration.Apply(modelBuilder);
     }

}

public class DomainConfiguration : IDomainConfiguration
{
     private readonly IFeatureEnabledService featureEnabledService;
...
     public void Apply(ModelBuilder modelBuilder)
     {
         ...
         modelBuilder.ApplyConfiguration(new FavoriteTeamConfiguration(featureEnabledService));
         ...
     }
}

public class FavoriteTeamConfiguration : IEntityTypeConfiguration<FavoriteTeam>
{
     private readonly IFeatureEnabledService featureEnabledService;
     ...
     
     public void Configure(EntityTypeBuilder<FavoriteTeam> builder)
     {
         builder.HasQueryFilter(ft => ft.Removed == null && featureEnabledService.NewFeatureIsEnabled());
     }
}

```

Both the implementation of IFeatureEnabledService and IDomainConfiguration are registed as scoped.

This implementation produced the following queries depending on if NewFeatureIsEnabled returned true or false on startup:

```
SELECT [f].[Id], [f].[Name], [f].[Removed]
FROM [FavoriteTeams] AS [f]
WHERE [f].[Removed] IS NULL

or

SELECT [f].[Id], [f].[Name], [f].[Removed]
FROM [FavoriteTeams] AS [f]
WHERE 0 = 1

```

In addition to the different looking queries I also noticed that NewFeatureIsEnabled was only invoked once (on the first request) after my change, while it was invoked at least once per request in the original implementation.

I found another github issue https://github.com/dotnet/efcore/issues/30655 that suggests that the expression tree must contain a field/property from the DbContext. Which it does not do in my second implementation.
However I could not find anything in the EF documentation about that.

My question is: Is my issue caused by the same thing as in the linked issue? And if that is the case, then are there any other options that could resolve my issue of readability and separation of concerns?

### Provider and version information

Application Type: ASP.NET Core Web API
EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by ajcvickers** [comment]
> My question is: Is my issue caused by the same thing as in the linked issue?

Sounds like it.

> And if that is the case, then are there any other options that could resolve my issue of readability and separation of concerns?

Not really, no. The context instance is needed to get the current value to use for the filter. Getting that value from anything else is not supported.
