### ISSUE TITLE
Batch command

### ISSUE THREAD

**Issue by Mr0N** [dotnet/efcore#31455]
I suggest adding an analogue of this https://entityframework-plus.net/ to ef core

**Comment by Mr0N** [comment]
```
ctx.Users.Where(x =>
x.LastLoginDate < DateTime.Now.AddYears(-2))
.Delete();

// UPDATE all users which are inactive for 2 years
ctx.Users.Where(x =>
x.LastLoginDate < DateTime.Now.AddYears(-2))
.Update(x => new User() { IsSoftDeleted = 1 });
```

**Comment by stevendarby** [comment]
Is this what you're looking https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete

**Comment by Mr0N** [comment]
yes, it's good that they added it to .net 7, because without it there were some difficulties
