### ISSUE TITLE
Is there a schema extraction api?

### ISSUE THREAD

**Issue by mattiasw2** [dotnet/efcore#31476]
## Ask a question

I want to write a small tool that fetches data from different databases, initially sqlserver and sqlite, and I need to get access to the schema of the database. 

I can of course implement this myself, but I assume, this already exists in efcore and the different providers for different databases, and was hoping I can reuse this code.

Is there such an api? If not what are the classes currently called that contain this information (so that I could build my custom version)?

I am targeting Windows + Linux.

Thanks!

**Comment by roji** [comment]
While EF's DatabaseModelFactory may be usable for this, it was designed more for EF's scaffolding purposes; at the ADO.NET you can use DbConnection.GetSchemaTable to get schema information ([see docs](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/retrieving-database-schema-information)).

**Comment by bricelam** [comment]
See also https://github.com/dotnet/runtime/issues/19324
