### ISSUE TITLE
How to use ExecuteUpdate - from a dictionary with properties and values to be applied

### ISSUE THREAD

**Issue by ssteiner** [dotnet/efcore#31470]
Basically I'm trying to implement on my own what's been requested as a future feature [here](https://github.com/dotnet/efcore/issues/29654)

I have a `Dictionary<string, object?>` that holds changes to be applied to one or multiple entities.

So this is what I came up with

```c#
Dictionary<string, object?> updates = new()
{
    { nameof(TEntity.StringProp), "hello" },
    { nameof(TEntity.BoolProp), false },
    { nameof(TEntity.GuidProp), Guid.NewGuid() }
};

Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> setExpression = _ => _;
foreach (var propertyValue in updates)
{
    var propertyExp = GetPropertyExpression<TEntity>(propertyValue.Key);
    setExpression = c => c.SetProperty(propertyExp, _ => propertyValue.Value);
}
await items.ExecuteUpdateAsync(setExpression).ConfigureAwait(false);

private static Func<TEntity, object> GetPropertyExpression<TEntity>(string propertyName)
{
    var parameterExpression = Expression.Parameter(typeof(TEntity), "x");
    var memberExpression = Expression.Property(parameterExpression, propertyName);
    var conversion = Expression.Convert(memberExpression, typeof(object));
    var lambda = Expression.Lambda<Func<TEntity, object>>(conversion, parameterExpression);
    return lambda.Compile();
}
```

This compiles, but when I run it, I'm getting an exception: `Unable to cast object of type 'System.Linq.Expressions.TypedParameterExpression' to type 'System.Linq.Expressions.LambdaExpression`  So it seems it doesn't like my `GetPropertyExpression` .  However, if I run this standalone:

```c#
internal object? GetProperty<T>(T entity, string propertyName)
{
    var parameter = Expression.Parameter(typeof(T), "e");
    var property = Expression.Property(parameter, propertyName);

    var conversion = Expression.Convert(property, typeof(object));
    var lambda = Expression.Lambda<Func<T, object>>(conversion, parameter);

    return lambda.Compile().Invoke(entity);
}
```

this works just fine on my entities.. so what do I need to change to make it work with efcore?

EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Win11 Pro 22H2
IDE: Visual Studio 2022 17.7

**Comment by Rlamotte** [comment]
Hi @ssteiner, I'm currently facing exactly the same problem. Did you find any solution before getting early access to : https://github.com/dotnet/efcore/issues/32018 ?

**Comment by ssteiner** [comment]
@Rlamotte : yes I found a solution. Here's my an extension class I'm using. 

```
public static class DynamicRelationalExtensions
{
    static MethodInfo UpdateMethodInfo =
        typeof(RelationalQueryableExtensions).GetMethod(nameof(RelationalQueryableExtensions.ExecuteUpdate));

    static MethodInfo UpdateAsyncMethodInfo =
        typeof(RelationalQueryableExtensions).GetMethod(nameof(RelationalQueryableExtensions.ExecuteUpdateAsync));

    public static int ExecuteUpdate(this IQueryable query, string fieldName, object? fieldValue)
    {
        var updateBody = BuildUpdateBody(query.ElementType,
            new Dictionary<string, object?> { { fieldName, fieldValue } });

        return (int)UpdateMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody });
    }

    public static Task<int> ExecuteUpdateAsync(this IQueryable query, string fieldName, object? fieldValue, CancellationToken cancellationToken = default)
    {
        var updateBody = BuildUpdateBody(query.ElementType,
            new Dictionary<string, object?> { { fieldName, fieldValue } });

        return (Task<int>)UpdateAsyncMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody, cancellationToken })!;
    }

    public static int ExecuteUpdate(this IQueryable query, IReadOnlyDictionary<string, object?> fieldValues)
    {
        var updateBody = BuildUpdateBody(query.ElementType, fieldValues);

        return (int)UpdateMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody });
    }

    public static Task<int> ExecuteUpdateAsync(this IQueryable query, IReadOnlyDictionary<string, object?> fieldValues, CancellationToken cancellationToken = default)
    {
        var updateBody = BuildUpdateBody(query.ElementType, fieldValues);

        return (Task<int>)UpdateAsyncMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody, cancellationToken })!;
    }

    static LambdaExpression BuildUpdateBody(Type entityType, IReadOnlyDictionary<string, object?> fieldValues)
    {
        var setParam = Expression.Parameter(typeof(SetPropertyCalls<>).MakeGenericType(entityType), "s");
        var objParam = Expression.Parameter(entityType, "e");

        Expression setBody = setParam;

        foreach (var pair in fieldValues)
        {
            var propExpression = Expression.PropertyOrField(objParam, pair.Key);
            var valueExpression = ValueForType(propExpression.Type, pair.Value);

            // s.SetProperty(e => e.SomeField, value)
            setBody = Expression.Call(setBody, nameof(SetPropertyCalls<object>.SetProperty),
                new[] { propExpression.Type }, Expression.Lambda(propExpression, objParam), valueExpression);

        }

        // s => s.SetProperty(e => e.SomeField, value)
        var updateBody = Expression.Lambda(setBody, setParam);

        return updateBody;
    }

    static Expression ValueForType(Type desiredType, object? value)
    {
        if (value == null)
        {
            return Expression.Default(desiredType);
        }

        if (value.GetType() != desiredType)
        {
            return Expression.Convert(Expression.Constant(value), desiredType);
            //value = Convert.ChangeType(value, desiredType);
        }

        return Expression.Constant(value);
    }
}```

**Comment by ahmeddjobby** [comment]
> @Rlamotte : yes I found a solution. Here's my an extension class I'm using.
> 
> ```cs
> public static class DynamicRelationalExtensions
> {
>     static MethodInfo UpdateMethodInfo =
>         typeof(RelationalQueryableExtensions).GetMethod(nameof(RelationalQueryableExtensions.ExecuteUpdate));
> 
>     static MethodInfo UpdateAsyncMethodInfo =
>         typeof(RelationalQueryableExtensions).GetMethod(nameof(RelationalQueryableExtensions.ExecuteUpdateAsync));
> 
>     public static int ExecuteUpdate(this IQueryable query, string fieldName, object? fieldValue)
>     {
>         var updateBody = BuildUpdateBody(query.ElementType,
>             new Dictionary<string, object?> { { fieldName, fieldValue } });
> 
>         return (int)UpdateMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody });
>     }
> 
>     public static Task<int> ExecuteUpdateAsync(this IQueryable query, string fieldName, object? fieldValue, CancellationToken cancellationToken = default)
>     {
>         var updateBody = BuildUpdateBody(query.ElementType,
>             new Dictionary<string, object?> { { fieldName, fieldValue } });
> 
>         return (Task<int>)UpdateAsyncMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody, cancellationToken })!;
>     }
> 
>     public static int ExecuteUpdate(this IQueryable query, IReadOnlyDictionary<string, object?> fieldValues)
>     {
>         var updateBody = BuildUpdateBody(query.ElementType, fieldValues);
> 
>         return (int)UpdateMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody });
>     }
> 
>     public static Task<int> ExecuteUpdateAsync(this IQueryable query, IReadOnlyDictionary<string, object?> fieldValues, CancellationToken cancellationToken = default)
>     {
>         var updateBody = BuildUpdateBody(query.ElementType, fieldValues);
> 
>         return (Task<int>)UpdateAsyncMethodInfo.MakeGenericMethod(query.ElementType).Invoke(null, new object?[] { query, updateBody, cancellationToken })!;
>     }
> 
>     static LambdaExpression BuildUpdateBody(Type entityType, IReadOnlyDictionary<string, object?> fieldValues)
>     {
>         var setParam = Expression.Parameter(typeof(SetPropertyCalls<>).MakeGenericType(entityType), "s");
>         var objParam = Expression.Parameter(entityType, "e");
> 
>         Expression setBody = setParam;
> 
>         foreach (var pair in fieldValues)
>         {
>             var propExpression = Expression.PropertyOrField(objParam, pair.Key);
>             var valueExpression = ValueForType(propExpression.Type, pair.Value);
> 
>             // s.SetProperty(e => e.SomeField, value)
>             setBody = Expression.Call(setBody, nameof(SetPropertyCalls<object>.SetProperty),
>                 new[] { propExpression.Type }, Expression.Lambda(propExpression, objParam), valueExpression);
> 
>         }
> 
>         // s => s.SetProperty(e => e.SomeField, value)
>         var updateBody = Expression.Lambda(setBody, setParam);
> 
>         return updateBody;
>     }
> 
>     static Expression ValueForType(Type desiredType, object? value)
>     {
>         if (value == null)
>         {
>             return Expression.Default(desiredType);
>         }
> 
>         if (value.GetType() != desiredType)
>         {
>             return Expression.Convert(Expression.Constant(value), desiredType);
>             //value = Convert.ChangeType(value, desiredType);
>         }
> 
>         return Expression.Constant(value);
>     }
> }
> ```

I was working on a solution conceptually similar but yours came to the rescue, worked gracefully and saved me a lot of trouble and time!!! Thank you for sharing it!

**Comment by KevinMartins84** [comment]
I am using it to.
But when upgrading to EFCore 9, 
RelationalQueryableExtensions.ExecuteUpdate and RelationalQueryableExtensions.ExecuteUpdateAsync no longer exists.

**Comment by roji** [comment]
@KevinMartins84 these have simply been moved to EntityFrameworkQueryableExtensions, so that they can apply to other, non-relational providers.

**Comment by ssteiner** [comment]
Has anybody gotten this ported to .NET 10? It seems that `Microsoft.EntityFrameworkCore.Query.SetPropertyCalls<T>` is no longer present in efcore 10.
