### ISSUE TITLE
Deadlocked transaction didn't rollback

### ISSUE THREAD

**Issue by ctrlaltdan** [dotnet/efcore#31478]
Hi all, when running our migration script, the transaction deadlocked but didn't rollback and caused our db to deploy in an unexpected state.

We're generating idempotent SQL scripts using the `dotnet` tool `(6.0.20)` as part of our CI pipeline (github runners)

```
dotnet ef migrations script \
    --idempotent \
    --startup-project "x" \
    --project "x" \
    --output "${{ github.workspace }}/migrations.sql" \
    --context "x"  \
    --configuration Release
```

This produces the following (trimmed) sql script:

```
BEGIN TRANSACTION;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20230815111759_AddX')
BEGIN
    ALTER TABLE [tablex] ADD [col_a] nvarchar(max) NULL;
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20230815111759_AddX')
BEGIN
    ALTER TABLE [tablex] ADD [col_b] nvarchar(max) NULL; -- ## this command deadlocked ##
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20230815111759_AddX')
BEGIN
    ALTER TABLE [tablex] ADD [col_c] nvarchar(max) NULL;
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20230815111759_AddX')
BEGIN
    ALTER TABLE [tablex] ADD [col_d] nvarchar(max) NULL;
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20230815111759_AddX')
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20230815111759_AddX', N'6.0.20');
END;
GO

COMMIT;
GO
```

We then run with sqlcmd utility:

```
sqlcmd \
  -S "$SERVER_HOSTNAME" \
  -U "$SERVER_USERNAME" \
  -P "$SERVER_PASSWORD" \
  -d "$DATABASE_NAME" \
  -i "$SQL_FILE" \
  -I
```
 
And in this instance, the following error occured:

```
Msg 1205, Level 13, State 56, Server ##dbname##, Line 4
Transaction (Process ID 95) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

(1 rows affected)
Msg 3902, Level 16, State 1, Server ##dbname##, Line 2
The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.
```

Is there a bug in the provider when dealing with deadlocked transactions? I would have expected the idempotent SQL script to fail to apply the migration, and safely rollback the transaction rather than deploying in an incompatible state. 

`col_a` was created, but `b`, `c` and `d` were not, and the migration step was recorded in the `__EFMigrationsHistory` table.

Many thanks.

**Comment by ctrlaltdan** [comment]
Probably related to: https://github.com/dotnet/efcore/issues/22613

**Comment by bricelam** [comment]
Yes, this looks like the same issue described in #22613. Are there command-line options to get sqlcmd to stop when it encounters an error? Have you considered using a [migrations bundle](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#bundles) instead?

**Comment by ErikEJ** [comment]
https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16&tabs=odbc%2Cwindows#-b
