### ISSUE TITLE
Updating Nuget packages yields different results on VS 2015 and 2013

### ISSUE THREAD

**Issue by htuomola** [dotnet/efcore#3149]
I guess this might be more of a Nuget 3 issue but maybe you can guide me towards them then. 
I'm on .NET 4.5.2 and just now moving to use VS 2015. The problem is that upgrading EF 7 nuget packages from the myget feed on VS 2015, it wants to install a lot of System.\* beta packages, like System.Collections 4.0.10-beta-22231.

**_Here's the output from VS 2015 Package Manager Console**_:

PM> Update-Package EntityFramework.Commands -Project DataAccess.Contexts.SqlServer -Source https://www.myget.org/F/aspnetvnext/ -Version 7.0.0-beta8-15721 -whatif -DependencyVersion Lowest
Attempting to gather dependencies information for multiple packages with respect to project '04 - Data Access\Contexts\DataAccess.Contexts.SqlServer', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Uninstall Microsoft.Framework.Caching.Memory 1.0.0-beta8-15567
Uninstall Microsoft.Framework.OptionsModel 1.0.0-beta8-15562
Uninstall Microsoft.Framework.Logging 1.0.0-beta8-15562
Uninstall Microsoft.Framework.Logging.Abstractions 1.0.0-beta8-15562
Uninstall Microsoft.Framework.DependencyInjection 1.0.0-beta8-15562
Uninstall Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta8-15562
Uninstall Microsoft.Framework.Configuration.Binder 1.0.0-beta8-15567
Uninstall Microsoft.Framework.Configuration 1.0.0-beta8-15567
Uninstall Microsoft.Framework.Configuration.Abstractions 1.0.0-beta8-15567
Uninstall Microsoft.Framework.Caching.Abstractions 1.0.0-beta8-15567
Uninstall Microsoft.AspNet.Razor 4.0.0-beta8-15589
Install Microsoft.AspNet.Razor 4.0.0-beta8-15611
Install Microsoft.Framework.Caching.Abstractions 1.0.0-beta8-15583
Install Microsoft.Framework.Configuration.Abstractions 1.0.0-beta8-15586
Install Microsoft.Framework.Configuration 1.0.0-beta8-15586
Install Microsoft.Framework.Configuration.Binder 1.0.0-beta8-15586
Install Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta8-15574
Install Microsoft.Framework.DependencyInjection 1.0.0-beta8-15574
Install Microsoft.Framework.Logging.Abstractions 1.0.0-beta8-15575
Install Microsoft.Framework.Logging 1.0.0-beta8-15575
Install Microsoft.Framework.OptionsModel 1.0.0-beta8-15574
Install Microsoft.Framework.Caching.Memory 1.0.0-beta8-15583
Install System.Linq 4.0.0
Install System.Resources.ResourceManager 4.0.0
**_Install System.Runtime 4.0.10-beta-23019
Install System.Collections 4.0.10-beta-22231
Install System.Diagnostics.Debug 4.0.10-beta-22231
Install System.Globalization 4.0.10-beta-22231
Install System.Runtime.Extensions 4.0.10-beta-22231
Install System.Threading.Tasks 4.0.0-beta-23019
Install System.Threading 4.0.10-beta-22605**_
Install System.Collections.Immutable 1.1.37
Install EntityFramework.Core 7.0.0-beta8-15721
Install EntityFramework.Relational 7.0.0-beta8-15721
Install EntityFramework.SqlServer 7.0.0-beta8-15679
Install System.Reflection.Metadata 1.1.0-alpha-00012
Install Microsoft.CodeAnalysis.Common 1.1.0-beta1-20150907-01
Install Microsoft.CodeAnalysis.CSharp 1.1.0-beta1-20150907-01
Install EntityFramework.Relational.Design 7.0.0-beta8-15721
Install EntityFramework.Commands 7.0.0-beta8-15721

**_And the VS 2013 one for reference**_:

PM> Update-Package EntityFramework.Commands -Project DataAccess.Contexts.SqlServer -Source https://www.myget.org/F/aspnetvnext/ -Version 7.0.0-beta8-15721 -Prerelease -whatif
Updating 'EntityFramework.Commands' from version '7.0.0-beta8-15679' to '7.0.0-beta8-15721' in project 'DataAccess.Contexts.SqlServer'.
Remove 'EntityFramework.Commands 7.0.0-beta8-15679' from project DataAccess.Contexts.SqlServer.
Remove 'EntityFramework.Relational.Design 7.0.0-beta8-15679' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.AspNet.Razor 4.0.0-beta8-15589' from project DataAccess.Contexts.SqlServer.
Remove 'EntityFramework.Relational 7.0.0-beta8-15679' from project DataAccess.Contexts.SqlServer.
Remove 'EntityFramework.Core 7.0.0-beta8-15679' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Logging 1.0.0-beta8-15562' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta8-15562' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.DependencyInjection 1.0.0-beta8-15562' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Caching.Memory 1.0.0-beta8-15567' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.OptionsModel 1.0.0-beta8-15562' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Configuration.Binder 1.0.0-beta8-15567' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Configuration 1.0.0-beta8-15567' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Configuration.Abstractions 1.0.0-beta8-15567' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta8-15562' from project DataAccess.Contexts.SqlServer.
Remove 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta8-15567' from project DataAccess.Contexts.SqlServer.
Add 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta8-15583' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta8-15583'
Add 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta8-15574' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta8-15574'
Add 'Microsoft.Framework.Configuration.Abstractions 1.0.0-beta8-15586' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Configuration.Abstractions 1.0.0-beta8-15586'
Add 'Microsoft.Framework.Configuration 1.0.0-beta8-15586' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Configuration 1.0.0-beta8-15586'
Add 'Microsoft.Framework.Configuration.Binder 1.0.0-beta8-15586' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Configuration.Binder 1.0.0-beta8-15586'
Add 'Microsoft.Framework.OptionsModel 1.0.0-beta8-15574' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.OptionsModel 1.0.0-beta8-15574'
Add 'Microsoft.Framework.Caching.Memory 1.0.0-beta8-15583' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Caching.Memory 1.0.0-beta8-15583'
Add 'Microsoft.Framework.DependencyInjection 1.0.0-beta8-15574' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.DependencyInjection 1.0.0-beta8-15574'
Add 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta8-15575' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta8-15575'
Add 'Microsoft.Framework.Logging 1.0.0-beta8-15575' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.Framework.Logging 1.0.0-beta8-15575'
Add 'EntityFramework.Core 7.0.0-beta8-15721' to project DataAccess.Contexts.SqlServer.
Install 'EntityFramework.Core 7.0.0-beta8-15721'
Add 'EntityFramework.Relational 7.0.0-beta8-15721' to project DataAccess.Contexts.SqlServer.
Install 'EntityFramework.Relational 7.0.0-beta8-15721'
Add 'Microsoft.AspNet.Razor 4.0.0-beta8-15611' to project DataAccess.Contexts.SqlServer.
Install 'Microsoft.AspNet.Razor 4.0.0-beta8-15611'
Add 'EntityFramework.Relational.Design 7.0.0-beta8-15721' to project DataAccess.Contexts.SqlServer.
Install 'EntityFramework.Relational.Design 7.0.0-beta8-15721'
Add 'EntityFramework.Commands 7.0.0-beta8-15721' to project DataAccess.Contexts.SqlServer.
Install 'EntityFramework.Commands 7.0.0-beta8-15721'
Uninstall 'EntityFramework.Commands 7.0.0-beta8-15679'.
Uninstall 'EntityFramework.Relational.Design 7.0.0-beta8-15679'.
Uninstall 'Microsoft.AspNet.Razor 4.0.0-beta8-15589'.
Uninstall 'EntityFramework.Relational 7.0.0-beta8-15679'.
Uninstall 'EntityFramework.Core 7.0.0-beta8-15679'.
Uninstall 'Microsoft.Framework.Logging 1.0.0-beta8-15562'.
Uninstall 'Microsoft.Framework.Logging.Abstractions 1.0.0-beta8-15562'.
Uninstall 'Microsoft.Framework.DependencyInjection 1.0.0-beta8-15562'.
Uninstall 'Microsoft.Framework.Caching.Memory 1.0.0-beta8-15567'.
Uninstall 'Microsoft.Framework.OptionsModel 1.0.0-beta8-15562'.
Uninstall 'Microsoft.Framework.Configuration.Binder 1.0.0-beta8-15567'.
Uninstall 'Microsoft.Framework.Configuration 1.0.0-beta8-15567'.
Uninstall 'Microsoft.Framework.Configuration.Abstractions 1.0.0-beta8-15567'.
Uninstall 'Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta8-15562'.
Uninstall 'Microsoft.Framework.Caching.Abstractions 1.0.0-beta8-15567'.

Any ideas on what's wrong? For now, I've been using VS 2013 to upgrade the packages.

**Comment by htuomola** [comment]
This seems to be caused by System.Collections.Immutable v. 1.1.37+. I just saw similar behavior with NLog and started looking around and then found this: https://github.com/dotnet/corefx/issues/2984.

**Comment by ErikEJ** [comment]
Stay on version 1.1.36!

**Comment by rowanmiller** [comment]
@htuomola yeah this doesn't seem to be anything EF related. Can you open up an issue in the NuGet repo https://github.com/NuGet/Home
