### ISSUE TITLE
How to use EF Core in REST and gRPC Services?

### ISSUE THREAD

**Issue by siegfried01** [dotnet/efcore#31500]
Presently my Blazor Svr Application persists Workers, WorkerTasks, and WorkIntervals to cosmos documentDB via EF core. A worker has many worker tasks and a worker task many work intervals. Work intervals contain a start and stop date-time.

The tracking feature of Ef Core greatly simplifies adding work intervals to tasks as workers take lunch breaks, complete tasks and start new tasks.

What strategies are available for moving this persistence logic to an Azure Function? For example, I'd like to call my azure function that will get the Worker object (as identified by the Azure AD claim in the JWT) that contains the tasks and work intervals and add work intervals as directed by the GUI and then send the Worker object back to the Azure Function (via REST or gRPC) which will call ctx.SaveChangesAsync().

I've tried and failed to pass Tracked entities from the azure functions back to the front end (blazor svr). I get the error "A tracking query is attempting to project an owned entity without a corresponding owner in its result, but owned entities cannot be tracked without their owner. Either include the owner entity in the result or make the query non-tracking using 'AsNoTracking'."

Is this possible to do this with REST? Is it possible with gRPC? Are there any examples I could follow?

Since I suspect this is not possible, especial with the ephemeral nature of in-process azure functions, I'm wondering what the easiest way is to implement the persistence layer inside an in-process azure function.  I'm thinking that the extended reference pattern (exemplified in the planetary docs example [https://learn.microsoft.com/en-us/ef/core/providers/cosmos/planetary-docs-sample](url)) is a bit tedious for my case where I have nested one-to-many relationships because I basically have to reinvent the tracking feature myself and tell my azure function which task with in which worker is getting a new work interval. I'm thinking it might be easier to have each Work Interval contain a reference to the task and each task contain a reference to the worker. Too bad Cosmos DocumentDb does not implement referential integrity! 

How would you implement this? Are there any examples for EF Core & cosmos DocumentDB?

Thanks

Siegfried

**Comment by ajcvickers** [comment]
@siegfried01 Your questions are very open-ended and the answers will depend on a lot of factors, and also are mostly not directly related to EF itself. You might want to contact Microsoft support for such wide-ranging questions.

**Comment by siegfried01** [comment]
How about if I just rephrase the question: 

If I have a C# blazor svr client that calls the azure function to fetch a specific worker (named Joe) using EF Core, can the blazor svr add a WorkInterval (9am to 10am 8/22/23) to a WorkerTask ("paint the bathroom") inside the Worker  (because Joe just finished painting the bathroom) and pass the worker Joe back to the Azure Function so the Azure Function can call ctx.SaveChangesAsync() so the modified Worker entity (Joe) is saved with the new worker interval and Joe is credited with having worked 1 hour on the "paint the bathroom" task?


I'll be pleasantly surprised if this is possible.

Thanks

Siegfried

**Comment by roji** [comment]
@siegfried01 it's generally helpful to exclude non-EF-related concepts from your questions (Blazor, Azure Functions, worker tasks), and to think purely in terms of the EF API; that makes it clearer what it is you're asking from EF specifically.

If I understand correctly, are you asking whether you can perform an EF Add() in one process (worker task), and then apply it to the database calling SaveChanges in another process? If so, then that's not directly possible: EF's DbContext tracks your changes internally (e.g. your Add), and so the same instance must be used both for the Add and the SaveChanges. More generally, a DbContext represents a "unit of work", which it doesn't generally make sense to split up across processes/workers.

What you can do, is transfer the thing you want to add (e.g. WorkInterval) across your workers - this has nothing to with EF, as it's just a plain .NET object. When you want to actually save that to the database, create a DbContext, call Add and then SaveChanges on it.

**Comment by siegfried01** [comment]
Ah! That helps! 

Please clarify that last sentence. What exactly would I be adding? Would I be adding the WorkInterval to the Worker or adding the Worker to the context?

I suspect you mean adding the Worker to the context. If so, does EF core detect that this worker already exists in the database and when you call ctx.SaveChangesAsync(), EF Core is smart enough to only add the new WorkInterval to the Worker that already exists in the cosmos DB?

**Comment by roji** [comment]
> What exactly would I be adding? Would I be adding the WorkInterval to the Worker or adding the Worker to the context?

That depends on your application's specific model, which I'm not familiar with. The point is that all operations having to do with a DbContext instance (Add, SaveChangesAsync) need to be done on the same DbContext instance. I suggest reading our docs (e.g. [this page](https://learn.microsoft.com/en-us/ef/core/saving/)) to get an understanding of the basic EF concepts.

> [...] does EF core detect that this worker already exists in the database and when you call ctx.SaveChangesAsync(), EF Core is smart enough to only add the new WorkInterval to the Worker that already exists in the cosmos DB?

That's an unrelated question; EF doesn't currently support UPSERT ("update-or-insert"), that's tracked by #4526 (I hope we'll be able to deliver that in an upcoming release, as it's a high-priority item).

I'm going to go ahead and close this issue as the answers have been answered and there's nothing actionable on the EF side, but feel free to continue posting here if needed.
