### ISSUE TITLE
Primitive collection type mapping infra doesn't support reverse-engineering

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#31505]
In short, FindCollectionMapping only gets called when the modelType is non-nullable. This makes sense for JSON collections - we don't want to reverse-engineer collections from database strings - but in the PostgreSQL case we have store types which definitely map to primitive collections (i.e. PG arrays).

/cc @ajcvickers

**Comment by ajcvickers** [comment]
After further discussion we don't think anything is needed in the core EF code for this.
