### ISSUE TITLE
How to implement role based Authorization For Blazor WASM accessing Cosmos Document DB via EF Core?

### ISSUE THREAD

**Issue by siegfried01** [dotnet/efcore#31503]
I'm wondering if it is possible to securely implement role based authorization for this application: [https://blog.jeremylikness.com/blog/azure-ad-secured-serverless-cosmosdb-from-blazor-webassembly/](url).

I'm guessing it is not possible because the only place to implement the authorization logic is in the client (browser resident javascript) that the malicious user could tamper with.

Now I see that Jeremy does use the [Authorize] attribute for the authentication feature of Azure AD & Cosmos, but I don't see any roles that could securely restrict some users but allow admins. Did I miss this?

Thanks

Siegfried

**Comment by JeremyLikness** [comment]
A lot has changed with Cosmos DB that I'm frankly not up to date with. If the [Azure AZ RBAC for Cosmos DB](https://learn.microsoft.com/azure/cosmos-db/how-to-setup-rbac) approach isn't feasible, then my guess is that you'd have to map the roles to named permissions, so basically you'd have a backend-for-front end service that looks at the users role(s) and uses some logic to determine the right named permission set in Cosmos that matches and returns a token for that scope.

**Comment by siegfried01** [comment]
Thanks!
