### ISSUE TITLE
EFCore Multiple Inserts - Json Column Null on Object with Same Properties

### ISSUE THREAD

**Issue by nolanblew** [dotnet/efcore#31529]
## File a bug

Remember:

[x] Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
[x] Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

## Description
When saving to a JSON Column in EFCore (7), if you are inserting a range of rows and all the values for the JSON column are the same or point to the same object in memory, only 1 of the columns will be filled out, with the rest being NULL.

#### Github Project
Take a look at my [simple but crude github project](https://github.com/nolanblew/efcore_json_column_issue) if you'd like. Just be sure to edit the "appsettings.json" and insert your own connection string. Then run `/index?generatePeople=true` to generate and insert the files to your db.

#### Code
Here's the sample I have. My models are as follows:
```c#
public class Person
{
    [Key]
    public int Id { get; set; } = 0;
    public string Name { get; set; }
    public Person? BestFriend { get; set; }
    public List<Animal> Pets { get; set; }
}

public class Animal
{
    public string Name { get; set; }
    public int Legs { get; set; }
    public List<Food> AcceptableFood { get; set; }
}

public class Food
{
    public string Brand { get; set; }
    public double Amount { get; set; }
    public int TimesPerDay { get; set; }
}
```

In my DatabaseContext, I have
```c#
    public DbSet<Person> People { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Person>().Property(p => p.Id).UseIdentityColumn();
        builder.Entity<Person>().OwnsMany(p => p.Pets, navBuilder =>
        {
            navBuilder.ToJson();
            navBuilder.OwnsMany(pet => pet.AcceptableFood);
        });
    }
```

Now when if I create a variable called `pets` that is a list of animals and a list of food:
```c#
var food = new[]
{
    new Food("Best Brand", 4, 2),
    new Food("Mid Brand", 1, 1),
    new Food("Worst Brand", 0.5, 1)
}.ToList();

var animals = new Animal[]
{
    new() { Name = "Dog", Legs = 4, AcceptableFood = food },
    new() { Name = "Cat", Legs = 4, AcceptableFood = food }
}.ToList();
```

### Scenario 1
I create a list of people and assign each person's "pets" value to the `pets` variable, EF will only insert the JSON to 1 of the list items:
```c#
var owners = new List<Person>
{
    new Person { Name = "Joe", Pets = animals },
    new Person { Name = "Bob", Pets = animals },
    new Person { Name = "Sue", Pets =  animals },
    new Person { Name = "Amy", Pets =  animals },
};
```
<img width="600" alt="image" src="https://github.com/dotnet/efcore/assets/1565705/57f94e99-a21d-4de8-85f5-7faeade1987e">

### Scenario 2
If I vary some of the items in the list, I get the unique rows but not the rows that have items that are the same:
```c3
var owners = new List<Person>
{
    new Person {  Name = "Joe", Pets = new List<Animal> { animals[0], animals[1] } },
    new Person { Name = "Bob",  Pets = new List<Animal> { animals[0] } },
    new Person { Name = "Sue", Pets = new List<Animal> { animals[0], animals[1] } },
    new Person { Name = "Amy", Pets = new List<Animal> { animals[1] } },
};
```
<img width="650" alt="image" src="https://github.com/dotnet/efcore/assets/1565705/e9658b5b-41a4-4086-a192-77604b23c183">

### Scenario 3
However, I will get unique items if I create **new** animal types:
```c#
var owners = new List<Person>
{
    new Person {  Name = "Joe", Pets = new List<Animal> { animals[0], animals[1] } },
    new Person { Name = "Bob",  Pets = new List<Animal> { animals[0] } },
    new Person { Name = "Sue", Pets = new List<Animal> { animals[0], animals[1] } },
    new Person { Name = "Amy", Pets = new List<Animal> { animals[0], new Animal { Name = "duck", Legs = 2, AcceptableFood = new() { food[2] } } } }
};
```
<img width="400" alt="image" src="https://github.com/dotnet/efcore/assets/1565705/7b62050c-0809-4a19-a254-42f4a56755e5">

### Scenario 4
Finally, if I re-create each animal but assign it the same sub-property (in this case, AcceptableFood), then the columns are not null, however only one of the properties has "AcceptableFood" filled in:
```c#
var owners = new List<Person>
{
    new Person {  Name = "Joe", Pets = new List<Animal> { new Animal { Name = "duck", Legs = 2, AcceptableFood = new() { food[2] } } } },
    new Person { Name = "Bob",  Pets = new List<Animal> { new Animal { Name = "duck", Legs = 2, AcceptableFood = new() { food[2] } } } },
    new Person { Name = "Sue", Pets = new List<Animal> { new Animal { Name = "duck", Legs = 2, AcceptableFood = new() { food[2] } } } },
    new Person { Name = "Amy", Pets = new List<Animal> { new Animal { Name = "duck", Legs = 2, AcceptableFood = new() { food[2] } } } }
};
```
<img width="450" alt="image" src="https://github.com/dotnet/efcore/assets/1565705/aec4b267-5e3d-4cfb-b847-d685fcb010ba">

This was replicated in this small project, but on my live project we have lots of JSON columns that start the same 

### Provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.7.0 Preview 6, but also can replicate on 17.6.6)

**Comment by ajcvickers** [comment]
@nolanblew This is not allowed:

```C#
var animals = new Animal[]
{
    new() { Name = "Dog", Legs = 4, AcceptableFood = food },
    new() { Name = "Cat", Legs = 4, AcceptableFood = food }
}.ToList();
```

This code uses the _same List instance_ on two different entity types. This is not supported by EF; each collection navigation must have its own collection instance.

**Comment by nolanblew** [comment]
@ajcvickers Is there documentation on this? I could not find it in the EFCore docs

**Comment by ajcvickers** [comment]
@nolanblew I'm not sure if it is explicitly mentioned. It might be worth doing so since, while it seems intuitive to most, this question does come up every few years.
