### ISSUE TITLE
How to disable migrations for existing databases

### ISSUE THREAD

**Issue by Vasim-DigitalNexus** [dotnet/efcore#3152]
How do you disable migrations for existing databases in code?

Previously I used this in the DbContext constructor:
`Database.SetInitializer<ApplicationDbContext>(null);`

**Comment by bricelam** [comment]
EF7 will never automatically create or alter your database schema. Users will need to explicitly call one of the following to do that.
```C#
context.Database.EnsureCreated();
context.Database.Migrate();
```

**Comment by davezych** [comment]
@bricelam what's the difference between `Migrate` and `EnsureCreated`?

**Comment by bricelam** [comment]
`EnsureCreated` bypasses Migrations. It will simple create the database schema for the current model. It is primarily used for prototyping and testing.

**Comment by sheinema** [comment]
@bricelam I am running into the same issue. I have tried calling EnsureCreated() and Migrate() as suggested but still get a nondescript error that "There are pending model changes for AppDbContext". Is there another way to disable migrations so I might get a more useful error?

**Comment by rowanmiller** [comment]
@sheinema did you try scaffolding the next migration to see what changes it things are pending?

**Comment by sheinema** [comment]
@rowanmiller yes, I was able to figure out the mismatch; however my team is interested in completely disabling migrations since we are doing database first. It would be nice to get a more useful/specific error and not have to scaffold a new migration each time.

**Comment by rowanmiller** [comment]
@sheinema so the database error page will only ever show if there is an exception trying to access the database (and details of the exception will be shown on the page too). It won't ever show just because you have pending model changes - it's trying to add some helpful information about your model in a situation where you would be getting an error page anyway.

**Comment by rowanmiller** [comment]
You can always remove it, there is an `AddDatabaseErrorPage` call in `Startup.cs`, then you will just see the standard error page in these situations.

**Comment by sheinema** [comment]
@rowanmiller Thank you, removing AddDatabaseErrorPage() indeed reverted to the standard error page.

The migrations error message did include the generic exception but not the stack-trace, which is what we were looking for.

**Comment by rowanmiller** [comment]
@sheinema do you have any migrations in your project? I would only expect to see the pending changes message if you have a model snapshot for the context in question.

**Comment by sheinema** [comment]
@rowanmiller No, there are no migrations in this project; no model snapshot

**Comment by rowanmiller** [comment]
Opened https://github.com/aspnet/Diagnostics/issues/182 to review this scenario as we shouldn't talk about migrations on the page when you have an existing schema and no migrations. We should also include info about how to turn off the error page.

**Comment by Seabizkit** [comment]
> @rowanmiller yes, I was able to figure out the mismatch; however my team is interested in completely disabling migrations since we are doing database first. It would be nice to get a more useful/specific error and not have to scaffold a new migration each time.

is this still a thing 2020, ef 3.1 ? im trying to migrate to ef core and running into these types of issues.

**Comment by Seabizkit** [comment]
@sheinema could you share how you have urs setup, as if i dont create migrations, when i say update database, it just creates it blank instead of creating tables.
