### ISSUE TITLE
Memory Issue with EF Core 7 DbContext ServiceProviderCache

### ISSUE THREAD

**Issue by easaevik** [dotnet/efcore#31539]
We have a .net 7 app using EF Core 7 running on Azure App Service. It's an API for both our web app and mobile app. Memory usage typically grows from 50MB to 3GB during peak hours (8-16) and only get released when things calm down at approximately 16 in the afternoon. During these 8 hours we have around 60k requests to our API. It's a multitenant app with Azure Sql database per tenant and approximately 180 tenants. We use ModelCacheKeyFactory to get correct global query filters for each tenant. Not only that, but we also have to differentiate between user roles in a tenant, given that we do authorization through EF Core global query filters.

![image](https://github.com/dotnet/efcore/assets/29543642/23d32c30-3dbd-40b4-aae6-2c888be61873)

Not sure what happens in the afternoon, but could it be IIS recycling? It's not restarting, that I have checked. Anyway, what could possibly cause such a big pile-up of memory in Gen 2 and the DbContext ServiceProviderCache?

![image](https://github.com/dotnet/efcore/assets/29543642/7d560f56-6c31-4b8d-a1bf-ad62a07cdfa1)

![image](https://github.com/dotnet/efcore/assets/29543642/2385ded1-2cb4-4998-ab32-beb4637002d1)

![image](https://github.com/dotnet/efcore/assets/29543642/fb894cf1-3d71-4287-ab9a-1622c5abf0ff)

As for the code I have tried to short it down to the essentials. In out startup.cs we use services.AddDbContext<IXDbContext, XDbContext>(); so nothing fancy there, but in the DbContext there is a lot more going on:

![image](https://github.com/dotnet/efcore/assets/29543642/7003ff04-fff3-4366-94a5-8585c1c51f90)

![image](https://github.com/dotnet/efcore/assets/29543642/06955e25-72c0-4761-8a58-22900221b6e6)

The EntityDbContextManager uses reflection to get the correct Authorization handler:

![image](https://github.com/dotnet/efcore/assets/29543642/f5ca61ec-e04e-48c8-8bb1-71cd493fb2e6)

A typical Authorization handler for a given entity (i.e. User) looks like this:

![image](https://github.com/dotnet/efcore/assets/29543642/7b232a18-501d-4cdc-88e1-c53eb90acb19)

So all in all a lot going on here. The question is why does ServiceProviderCache retain so much memory under load? The system works as it should, just not happy with all this retained bytes ending up in Gen 2. I fear there could be problems ahead as more tenants are added. Any help would be greatly appreciated.

**Comment by abydal** [comment]
Second this - we are having an issue that is very similar to this.

- Multitenant app - database per tenant, ~160 tenants, Azure SQL
- We use this pattern for switching between models:

``` csharp
public sealed class DynamicModelCacheKeyFactory : IModelCacheKeyFactory
{
	public object Create(DbContext context, bool designTime) =>
		context is IDynamicModelDbContext { CacheKey: not null } dynamicDbModelContext
			? new DynamicModelCacheKey(context, designTime, dynamicDbModelContext.CacheKey)
			: new ModelCacheKey(context, designTime);
}
```

```csharp
public sealed class DynamicModelCacheKey : ModelCacheKey
{
	private readonly string cacheKey;

	public DynamicModelCacheKey(DbContext context, bool designTime, string cacheKey)
		: base(context, designTime) =>
		this.cacheKey = cacheKey;

	protected override bool Equals(ModelCacheKey other) => other is DynamicModelCacheKey otherCacheKey
			&& base.Equals(otherCacheKey)
			&& otherCacheKey.cacheKey == cacheKey;

	public override int GetHashCode() => HashCode.Combine(base.GetHashCode(), cacheKey);
}
```

- We see the `SqlServerValueGeneratorCache` grow steadily during peak hours
![image](https://github.com/dotnet/efcore/assets/5933904/09183d8e-b54e-4696-bd81-014b457e9854)

  - But we reboot servers in the evening in order to wipe the memory - it does not seem to get released by itself.

We also have some memory analysis that we can post, I just dont have access to them right now.

**Comment by roji** [comment]
@abydal you seem to be reporting a case where the number of SqlServerValueGeneratorCache is growing, whereas the original report above seems to have only two instances (which themselves hold a huge number of `object[]` instances.

Though I might be misunderstanding here. The easiest thing really is for someone to produce a minimal, runnable code sample with a loop, showing the memory growing and not getting collected.

**Comment by easaevik** [comment]
@roji It's a bit of a mystery to me what these object arrays are. The content seems to be a bit of everything from what I can see in dotMemory. There are 103 of them in this dump, but they are not the same kind of objects. Only one retain a lot of memory, the others don't. Drilling into the one instance with 2.4GB retained bytes shows the following:

![image](https://github.com/dotnet/efcore/assets/29543642/f69f202f-c837-4cdc-88f1-96b705fa3229)

![image](https://github.com/dotnet/efcore/assets/29543642/b63522f0-ba71-46d9-9552-5b1b405afcf8)

![image](https://github.com/dotnet/efcore/assets/29543642/d027bae0-dd29-405a-a3a3-9b93b5b1039d)

So it's an object array of size 4080. A lot of different stuff in there, including 1 reference to ServiceProviderCache, holding onto 2.4GB of memory:

![image](https://github.com/dotnet/efcore/assets/29543642/1991001a-cd9b-4fe2-b7d1-fda4fbc654ee)

Not really been able to reproduce this scenario locally with profiling, so I'm looking at prod memory dumps.

**Comment by roji** [comment]
@easaevik can you drill down into ServiceProviderCache to show the ownership path leading to the huge data?

**Comment by abydal** [comment]
This is our dominators tree, with `SqlServerValueGeneratorCache`being the top footprint.
![image](https://github.com/dotnet/efcore/assets/5933904/476fc3e4-b7af-41f9-bc21-35bf2e27642c)
We do `services.AddScoped<OurDbContext, OurDbContext>()` so it seems that all the DI wrappings are not present in our stack. 
To me these two cases seems related, but do you still believe this is not the case @roji ?

**Comment by easaevik** [comment]
@roji Here is the drill down into the ServiceProviderCache:

![image](https://github.com/dotnet/efcore/assets/29543642/a95888e8-6cb3-4101-84aa-76e4321c05a9)

**Comment by abydal** [comment]
I think we can say that we have identified the issue on our end at least. I suspect this is your problem as well @easaevik.
I will try to explain. 
The root issue is in the class  `ValueGeneratorCache` [here](https://github.com/dotnet/efcore/blob/affd44045f41a2dd58c5667ce3938e42568fbe84/src/EFCore/ValueGeneration/ValueGeneratorCache.cs#L28). This class sets up a cache for all value generators for all models for all dbcontexts where the CacheKey is a struct that contains `IProperty` and `ITypeBase`. When the application is designed to be multi-tenant using one database per tenant, it leads to, in our case, that we get one entry in this cache per model per tenant. And the cache keys in on themselves takes up quite a bit of memory each. We have over 100 models  in our db context and close to 150  tenants which leads to 100*150 entries * the size of the entry and the CacheKey. Its just too big a footprint per customer in our case.

We have currently solved this by implementing our own version of this class where we have a slightly different implementation of the `Equals` function and differentiate on `EntityType.ClrType` instead of just `EntityType`. 
```csharp
public class MultiTenantValueGeneratorCache : IValueGeneratorCache
{
	public MultiTenantValueGeneratorCache(ValueGeneratorCacheDependencies dependencies) => Dependencies = dependencies;
	protected virtual ValueGeneratorCacheDependencies Dependencies { get; }
	private readonly ConcurrentDictionary<CacheKey, ValueGenerator> cache = new();
	private readonly struct CacheKey : IEquatable<CacheKey>
	{
		public CacheKey(IProperty property, IEntityType entityType)
		{
			Property = property;
			EntityType = entityType;
		}
		public IProperty Property { get; }
		public IEntityType EntityType { get; }
		public bool Equals(CacheKey other) =>
			EntityType.ClrType == other.EntityType.ClrType && Property.Name == other.Property.Name;
		public override bool Equals(object obj) => obj is CacheKey cacheKey && Equals(cacheKey);
		public override int GetHashCode() => HashCode.Combine(Property.Name, EntityType.ClrType);
	}
	public virtual ValueGenerator GetOrAdd(
		IProperty property,
		IEntityType entityType,
		Func<IProperty, IEntityType, ValueGenerator> factory)
		=> cache.GetOrAdd(new CacheKey(property, entityType), static (ck, f) => f(ck.Property, ck.EntityType), factory);
}
```
This will eliminate duplicate entries in this cache and it reduced our memory-footprint quite drastically.
There are probably some internal functionality in EFCore that will break with this implementation. I'm imagining HiLo will not work, but we dont use it so that is noe issue for us. So far it seems to work for us. All tests are green. Maybe you can chime in on this @roji

**Comment by roji** [comment]
Thanks for the analysis... Definitely interesting and important stuff. Just to set expectations, we're heads-down stabilizing the 8.0 release, so it's likely to take a bit of time before we can look into this.

/cc @ajcvickers

**Comment by abydal** [comment]
So far this works for us, so there is no rush.

**Comment by easaevik** [comment]
Interesting @abydal. How do you replace ValueGeneratorCache with your custom MultiTenantValueGeneratorCache?

**Comment by ajcvickers** [comment]
@abydal Thanks for the analysis. This is certainly something we should try to fix on the EF side.

**Comment by abydal** [comment]
We found one more instance of this issue. In `EntityMaterializerSource` [here](https://github.com/dotnet/efcore/blob/release/8.0/src/EFCore/Query/Internal/EntityMaterializerSource.cs#L461) There are two `ConcurrentDictionaries` which also use `IEntityType` as the key. In our case its `_emptyMaterializers` that grows very big. `_materializers` does not seem to contain the same amount of data. 

![image](https://github.com/dotnet/efcore/assets/5933904/6291ef3c-957a-49f9-b96f-63bfb4b3e7a0)


We see that our previous fix alleviates the memory pressure somewhat, and this Singleton class now ranks as top retained bytes. We will probably try to apply the same type of fix on this issue as we did with the previous one. 
![image](https://github.com/dotnet/efcore/assets/5933904/1dd65abf-ed15-4349-9cf0-ee0617378dbf)

**Comment by easaevik** [comment]
@abydal We've tried your solution by changing the ValueGeneratorCache, but it didn't really make any difference to the memory consumption in our scenario. So the behavior of the ServiceProviderCache is still the problem for us.

**Comment by abydal** [comment]
Did you also look into `EntityMaterializerSource` that I pointed out in my last post?
We had to override the class in order to tweak the caching-keys there as well:
```csharp
public class MultiTenantEntityMaterializerSource : EntityMaterializerSource
{
	private readonly ConcurrentDictionary<Type, IEntityType> map = new();

	public MultiTenantEntityMaterializerSource(EntityMaterializerSourceDependencies dependencies) : base(dependencies) { }

	public override Func<MaterializationContext, object> GetEmptyMaterializer(IEntityType entityType) =>
		base.GetEmptyMaterializer(map.GetOrAdd(entityType.ClrType, _ => entityType));

	public override Func<MaterializationContext, object> GetMaterializer(IEntityType entityType) =>
		base.GetMaterializer(map.GetOrAdd(entityType.ClrType, _ => entityType));
}
```

**Comment by ajcvickers** [comment]
Split out the  EntityMaterializerSource issue to #31866.
