### ISSUE TITLE
Native AOT - Microsoft.Data.SQLite crashing on SqliteConnection.Open()

### ISSUE THREAD

**Issue by JOULTICOA** [dotnet/efcore#31541]
I am using Visual Studio 2022 17.7.2, targeting net7.0-windows  (x64), on Win10 Iot LTSC 2021, with latest Win11 SDK installed in build tools

I ran "dotnet add package Microsoft.Data.Sqlite --version 8.0.0-preview.7.23375.4" to install the package

I am running "dotnet publish -r win-x64 -c Release -p:OptimizationPreference=Speed"  to build the executable

When I build the app as managed / .NET it works fine

When I build the app with AOT, it crashes, giving an Exception code: 0x4b1b53b5  code in event log.  No exception window appears

I added some logging to my application, and I confirmed it crashes when calling Open().  I.e. the **connection object gets defined / initialized, but when connection is attempted to be Opened, is when the crash happens.**

I also had my log print the connection string, and it looks correct in the log.  the exact same code works fine without AOT.

Is there a certain known-good environment / versions combination I should try to get it running?

**Comment by roji** [comment]
Can you please try with the latest .NET SDK as well, matching the version of Microsoft.Data.Sqlite (so 8.0.0-preview.7)?

**Comment by JOULTICOA** [comment]
> Can you please try with the latest .NET SDK as well, matching the version of Microsoft.Data.Sqlite (so 8.0.0-preview.7)?

I stuck with non-preview VS but switch to latest 8.0 SDK, and it seems working now.  Sorry I underestimated that 8.0 would be such a significant overhaul

Thank you!
