### ISSUE TITLE
Can't find Guid.ToString() generating different cases in ef 6 to ef core migration guides

### ISSUE THREAD

**Issue by HanMoeHtet** [dotnet/efcore#31558]
Related to #24419 . But I don't find the guide or how to migrate easily without finding and updating all the usages of Guid.ToString() in our project.

**Comment by roji** [comment]
@HanMoeHtet to carify, you're asking for a note to be added about Guid.ToString() on [this page](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-detailed-cases)?

**Comment by HanMoeHtet** [comment]
@roji Yes that would be helpful for those migrating from EF 6 to EF Core 7. 
I got an answer [here](https://stackoverflow.com/questions/76981612/ef-6-to-ef-core-generate-different-cases-for-guid-tostring/76983398#76983398) to override this behavior in EF Core 7 to make it the same as EF 6.

**Comment by roji** [comment]
@HanMoeHtet I don't think we'd necessarily recommend that way of working around the issue (note that the answer author doesn't either):

> In general it is not a good idea to rely on database for string conversions (formatting/parsing) since every database has its own vision, there is no real standard, and also in the most cases it is different from let say C#.

So I'm not sure exactly what you're doing in your queries, but if you're comparing database GUIDs to something, it's strongly recommended to **not** convert them to string, but rather to simply have a Guid on the other side of the conversion.

I do understand that when porting from EF6 to EF Core you don't necessarily want to go over all queries and replace ToString with something else, but switching an ORM (EF6 to EF Core) isn't a transparent operation where the exact same code runs in the same way; it's reasonable to do a bit of query rewriting where necessary. You can use a workaround such as the one suggested above, but that would be carrying over EF6 behavior and make EF Core behave in a non-obvious way.

**Comment by HanMoeHtet** [comment]
@roji I am planning to do this as a temporary fix because this is currently a breaking change for our system. So couldn't perform testing on other major changes. But I will eventually fix the usage of `Guid.ToString()` in the project and hopefully will drop this answered workaround altogether at a later time.
