### ISSUE TITLE
EntityFramework tools stop working after updating to VS 17.7

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#31551]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EntityFramework-tools-stop-working-after/10441377)._

---
All ef tools commands return error “Unrecognized command or argument ‘C#’”  
Here is a verbose log:
net 4.8 desktop project with ef core 3.1.12

```  
Package Manager Console Host Version 6.7.0.127

Type 'get-help NuGet' to see all available NuGet commands.

PM> Get-DbContext -v 
Using project 'DemoProject'.
Using startup project 'DemoProject'.
Build started...
Build succeeded.
C:\Users\user\.nuget\packages\microsoft.entityframeworkcore.tools\3.1.32\tools\net461\any\ef.exe dbcontext list --json --verbose --no-color --prefix-output --assembly C:\source\DemoProject\DemoProject\bin\Debug\DemoProject.dll --startup-assembly C:\source\DemoProject\DemoProject\bin\Debug\DemoProject.exe --project-dir C:\source\DemoProject\DemoProject\ --language C# C# --working-dir C:\source\DemoProject --root-namespace DemoProject
Specify --help for a list of available options and commands.
Unrecognized command or argument 'C#'
  
```

Language option has duplicated name "–language C# C# " it causes the error.

---
#### Feedback Bot on 8/16/2023, 02:39 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by bricelam** [comment]
This value comes directly from the project's `Language` property. No idea why it would be repeated twice. This issue may belong on [dotnet/project-system](https://github.com/dotnet/project-system).
