### ISSUE TITLE
Will DistinctBy be supported in Filtered Include?

### ISSUE THREAD

**Issue by smarts** [dotnet/efcore#31554]
## Ask a question
Is it on the roadmap to support more operations in [Filtered Includes](https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include)? I'm specifically wanting to use `OrderByDescending` (currently supported) + `DistinctBy` (currently unsupported) to get multiple max values.

### Include your code
I'm using comments instead of actual EF Core configuration/attribution
Ex:
```C#
public class ParentEntity
{
  public long Id { get; set; }
  // owned entities
  public List<ChildEntityRevision> ChildEntityRevisions { get; set; }
  // I want the ability to do this 👇🏽 in a Filtered Include
  public IEnumerable<ChildEntityRevision> CurrentRevisions
    => ChildEntityRevisions.OrderByDescending(x => x.Version).DistinctBy(x => x.StableKey);
  // if the former is enabled then this 👇🏽 is trivial to also do via filtered include with an extra `Where` and `Take(1)`
  public ChildEntityRevision? GetCurrentRevisionOrDefault(long stableKey)
    => CurrentRevisions.SingleOrDefault(x => x.StableKey == stableKey);
}

public class ChildEntityRevision
{
  public long StableKey { get; set; }
  // increases with each new revision 
  public long Version { get; set; }
}
```

### Include stack traces
N/A

### Include verbose output
N/A

### Include provider and version information
N/A

**Comment by roji** [comment]
DistinctBy isn't currently supported by EF in any context, outside or inside of filtered includes - #27470 tracks that.

Distinct (without By) is supported, but not within filtered Include; I've opened #31562 to track that.

**Comment by smarts** [comment]
@roji thanks for creating that, I've went ahead and upvoted it.
Out of curiosity, do you know if there's already an issue for using `GroupBy` (in my case with a nested `OrderByDescending(…).Take(1)` or `OrderByDescending(…).First()`) in a filtered include? I'm not sure if that would be more palatable to implement or not, but that's another way to accomplish what I want.

**Comment by roji** [comment]
Not as far as I know... That may be a bit much within filtered include...

**Comment by smarts** [comment]
Got it. I'll close this issue now and we'll see what happens with the 2 issues you mentioned above. Thanks again!
