### ISSUE TITLE
RelationalConverterMappingHints fixedLength: true does not lead to a datatype of binary but to varbinary for byte[]

### ISSUE THREAD

**Issue by michelbieleveld** [dotnet/efcore#31556]
## File a bug

Using MS SQL Server and I have this value converter

```C#
public class CustomerIdConverter : ValueConverter<CustomerId, byte[]>
{
    private static readonly RelationalConverterMappingHints DefaultHints = new(size: 16, fixedLength: true);
    
    public CustomerIdConverter()
        : base(
            v => v.Value.ToByteArray(), 
            v => new CustomerId(new Ulid(v)),
            DefaultHints){}
}
```

that is correctly registered in DbContext and working in my app
```C#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
        configurationBuilder.Properties<CustomerId>().HaveConversion<CustomerIdConverter>();
}    
```

however the output in the migration is

```C#
 migrationBuilder.CreateTable(
                name: "Customers",
                columns: table => new
                {
                    Id = table.Column<byte[]>(type: "varbinary(16)", nullable: false),
          ....
```

this does not occur if I manually set the property with _ IsFixedLength() with the entity type configuration, then I correctly get a binary(16).

**Comment by michelbieleveld** [comment]
Not sure but I think the problem is that in  [SqlServerTypeMappingSource.cs](https://github.com/dotnet/efcore/blob/afef2e53924e1610d32f04cd7f76c40ac602ff4c/src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs#L316)


```
if (clrType == typeof(byte[]))
            {

                var isFixedLength = mappingInfo.IsFixedLength == true;
```

is always either true or false, but in 
[RelationalTypeMappingInfo.cs](https://github.com/dotnet/efcore/blob/afef2e53924e1610d32f04cd7f76c40ac602ff4c/src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs#L68)

```
    public RelationalTypeMappingInfo(
        IElementType elementType,
        string? storeTypeName = null,
        string? storeTypeNameBase = null,
        bool? fallbackUnicode = null,
        bool? fallbackFixedLength = null,
        int? fallbackSize = null,
        int? fallbackPrecision = null,
        int? fallbackScale = null)
    {
        _coreTypeMappingInfo = new TypeMappingInfo(elementType, fallbackUnicode, fallbackSize, fallbackPrecision, fallbackScale);

        fallbackFixedLength ??= elementType.IsFixedLength();
        storeTypeName ??= (string?)elementType[RelationalAnnotationNames.StoreType];

        var customConverter = elementType.GetValueConverter();
        var mappingHints = customConverter?.MappingHints;

        IsFixedLength = fallbackFixedLength ?? (mappingHints as RelationalConverterMappingHints)?.IsFixedLength;
        DbType = (mappingHints as RelationalConverterMappingHints)?.DbType;
        StoreTypeName = storeTypeName;
        StoreTypeNameBase = storeTypeNameBase;
    }
```

The mapping hints are only used if fallbackFixedLength is null, thus if the elementType.IsFixedLength is also null, but I have a feeling that doesn't happen due to it either being false or true.

If this is the issue then the line

 IsFixedLength = fallbackFixedLength ?? (mappingHints as RelationalConverterMappingHints)?.IsFixedLength;

should also include the false case to consider the mappingHints and not just the null case.

**Comment by ajcvickers** [comment]
@michelbieleveld What version of EF Core are you using?

**Comment by michelbieleveld** [comment]
@ajcvickers sorry should have mentioned that, 7.0.10 .

**Comment by ajcvickers** [comment]
@michelbieleveld Can you try the [latest EF Core 8 preview](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/8.0.0-preview.7.23375.4)? Some bugs in this area have been fixed.

**Comment by michelbieleveld** [comment]
Good news

```C#
            migrationBuilder.CreateTable(
                name: "Customers",
                columns: table => new
                {
                    Id = table.Column<byte[]>(type: "binary(16)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customers", x => x.Id);
                });
        }
```

I'll wait patiently until the 8 RC release ;-)
