### ISSUE TITLE
Method for Latest EF core compatible with .NET framework >4.5

### ISSUE THREAD

**Issue by tceioos47** [dotnet/efcore#31564]
as mentioned in the topic.

My models are just in an independent sub-project (.net dll type) in the solution, and I target it under.net 6.0 so that I can use the EF core 6.0 directly while my launching or main project in my solution is targeted with the .net framwork 4.8.

All the launching project needs are merely properties or some CRUD method in the models. Pure Properties are not tightly coupled with a special framework—they use very basic language primitives and can compile well in .net6.0 or .net framwork 4.8. However, the CRUD operation is relevant with the EF core; that's the barrier that the models cannot be referenced by the lauching project.

The number and category of CRUD operations are not that many (insert, update, and query) in my solution. So, I encapsulate the finite CRUD operation in functions. These functions are like an API for the launching project. When the other projects( on .net framwork 4.x) invoke the encapsuated-CRUD function of the models,they don't know the EF core detail.

Sadly,the .net framwork project cannot refer to a project built on .net (core), even the properties and the encapsuated function declaration are so basic.
It should check the compatibility of functions or features between.net and .net framework before referring to each other. If the answer is positive, it should be allowed. 

Migrate the .net framwork project to .net is not possibale beacause of so many third-party dll reference.

**Comment by roji** [comment]
@tceioos47 it's not completely clear what you're trying to achieve from the above.. However, if the goal is to be able to access your .NET model types (just regular POCOs) from .NET Framework, you can put them in a project that targets netstandard2.0 (or which multitargets both e.g. net471 and net60). At that point you can reference that project from both your .NET Framework launching project and from another net60 project.

However, EF Core 6.0 itself cannot be used from a .NET Framework application.

**Comment by tceioos47** [comment]
> netstandard2.0

netstandard2.0 support EF core 5.0, it's the latest version available for my scenario I can try .
