### ISSUE TITLE
Filtering on fields that have conversion do not convert correctly when using "IN" operator

### ISSUE THREAD

**Issue by phuc1640** [dotnet/efcore#31577]
I have a model that has the fields like below

```C#
    public class Post
    {
        public int Id { get; set; }
        public PostType PostType { get; set; }

    }

    public enum PostType
    {
        Food,
        Health,
        Travel
    }
```

And the DbContext set up as below

```C#
    public DbSet<Post> Posts { set; get; }

    private const string connectionString = @"string";

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer(connectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(b => b.Id);
            entity.Property(b => b.PostType).IsRequired().HasConversion<string>();
        });
    }
```
If I build a query using "=" operator then it will correctly get all the data, and I can see in the generated query that the input enum was converted to string correctly.

```C#
List<Post> foodPosts = db.Posts.Where(p => p.PostType == PostType.Food).ToList();
```

But if I build a query using "IN" operator then it will always yield empty result. And I see in the generated query that the input array of enum do not get converted into string but stay as the enum number

```C#
List<PostType> postTypes = new() { PostType.Health, PostType.Travel };

List<Post> healthAndTravelPosts = db.Posts.Where(p => postTypes.Contains(p.PostType)).ToList();
```
I have tested this on .Net 6 and it doesn't have this issue.

Please have a look at this.

EF Core version: 8.0.0-preview.7.23375.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by roji** [comment]
Yes, value converter support for such queries was not yet implemented in preview.7, but has already been done for rc.1, which will come out in a few weeks. I've done a quick test which seems to confirm that everything works; can you please try the latest [daily build](https://github.com/dotnet/efcore/blob/release/8.0/docs/DailyBuilds.md) and confirm that it works for you?

**Comment by molinch** [comment]
Thanks @roji for the feedback we will try this out. Would you know if we can use the daily builds with central package management? i.e. having in a Directory.Packages.props
```xml
<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
```

**Comment by molinch** [comment]
Edit: apparently it's not really doable, but my colleague @phuc1640 will update you if rc1 fixes the issue with his sample project.

**Comment by molinch** [comment]
@roji I just tested the daily nuget and confirm that the bug is fixed !

**Comment by roji** [comment]
@molinch thanks for the confirmation, good to know!
