### ISSUE TITLE
Cannot check if owned entity is null using Cosmos DB provider

### ISSUE THREAD

**Issue by rafalxyz** [dotnet/efcore#31579]
Hi,
I've been using EF Core with Cosmos DB in the current project and encountered a bug.

My data model is as follows:
```C#
public class Order
{
    public string Id { get; private set; } = null!;
    public string OrderId { get; private set; } = null!;
    public OrderAssignedUser? AssignedUser { get; private set; }
}

public record OrderAssignedUser(
    string Id,
    string Login,
    string DisplayName
);

internal sealed class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.ToContainer(nameof(Order)).HasPartitionKey(x => x.OrderId);
        builder.OwnsOne(x => x.AssignedUser);
    }
}
```

The following query:
```C#
var orders = await context.Orders.Where(x => x.AssignedUser == null).ToListAsync();
```
is throwing an exception:

```
.Where(o => EF.Property<OrderAssignedUser>(o, "AssignedUser") == null)' could not be translated. Additional information: Translation of member 'OrderId' on entity type 'OrderAssignedUser' failed. This commonly occurs when the specified member is unmapped.
```

As it's a rather simple query, I'd expect it to be working correctly. Is my configuration incorrect?

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: (e.g. .NET 7.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by JarFrank** [comment]
Hi,

I've encountered a similar issue when using EF Core with Cosmos DB in one of my projects. The setup is almost identical to what you've described and I'm facing the exact same exception.

The query should indeed be straightforward. Has there been any update on this? I'm keenly waiting for a resolution as it's affecting my work.

Thanks in advance.
