### ISSUE TITLE
superfluos JOIN on query conflicts with SQL RLS

### ISSUE THREAD

**Issue by MariovanZeist** [dotnet/efcore#31588]
Assume I have the following (wel known) example Database

```cs
public class Blog
{
    public int Id { get; set; }
    public string Text { get; set; } 
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}

public partial class Post
{
    public int Id { get; set; }
    public string Text { get; set; }
    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();
}
```

Resulting in 3 DB tables (Blogs/ Posts and BlogPosts)

And I want to query **only** the post ID's on a specific blog. (So I am not interested / or dependant on any other field in the Post table)
```cs
  var postIds = ctx.Blogs.Where(b => b.Id==blogIdToFind).Select(b => b.Posts.Select(b => b.Id)).ToList();
```
The SQL generated includes a JOIN to the Post table

```sql
SELECT [b].[Id], [t].[Id], [t].[BlogId], [t].[PostId]
      FROM [Blogs] AS [b]
      LEFT JOIN (
          SELECT [p].[Id], [b0].[BlogId], [b0].[PostId]
          FROM [BlogPosts] AS [b0]
          INNER JOIN [Posts] AS [p] ON [b0].[PostId] = [p].[Id]
      ) AS [t] ON [b].[Id] = [t].[BlogId]
      WHERE [b].[Id] = 1
      ORDER BY [b].[Id], [t].[BlogId], [t].[PostId]
```

which is not needed. This would normally not be an issue, but when you have RLS enabled on the Post table it will trigger RLS, and will 
only return PostId's on which RLS returns True. (which may not be what you want)

In my case the Query is specifically designed to Circumvent RLS.

Is there a way around this, other then creating a SP?

**Comment by roji** [comment]
You should be able to achieve this by having a class for the join entity, and then querying only the foreign key for the Post from that join entity ([docs](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-with-class-for-join-entity)) (in other words, no need to actually use the navigation to Posts if you're only interested in the ID). Note that having a class for the join entity doesn't prevent you from using the direct (skip) navigation between Blogs and Posts in other queries.

**Comment by MariovanZeist** [comment]
@roji Thank you, Your suggestion works great.

I do have a follow-up question though.

As I rely on Scaffolding the Database every time there is a change, I don't want to modify the autogenerated DBContext
I do use the ``partial void OnModelCreatingPartial(ModelBuilder modelBuilder);`` method to enhance the generated DbContext to my needs, and I was wondering if I could use that somehow to modify the autogenerated behavior

The scaffolding generates the following DbContext

```cs
modelBuilder.Entity<Blog>(entity =>
{
    entity.HasMany(d => d.Posts).WithMany(p => p.Blogs)
	.UsingEntity<Dictionary<string, object>>(
		"BlogPost",
		r => r.HasOne<Post>().WithMany()
			.HasForeignKey("PostId")
			.HasConstraintName("FK_BlogPost_Posts"),
		l => l.HasOne<Blog>().WithMany()
			.HasForeignKey("BlogId")
			.HasConstraintName("FK_BlogPost_Blogs"),
		j =>
		{
			j.HasKey("BlogId", "PostId");
			j.ToTable("BlogPosts");
		});
```
I could modify that file to
```cs
modelBuilder.Entity<Blog>(entity =>
{
    entity.HasMany(d => d.Posts).WithMany(p => p.Blogs)
	.UsingEntity<BlogPost>(
	r => r.HasOne<Post>().WithMany(),
	l => l.HasOne<Blog>().WithMany());
}
```

And it works, The problem is that I would have to modify the generated DbContext everytime I scaffold it.


But I was wondering if there was another way to "override" that autogenerated behaviour by adding a file
```cs
partial class BlogPostDbContext
{
  public virtual DbSet<BlogPost> BlogPosts { get; set; }
  partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
  {
     //And do the configuration here
     modelBuilder.Entity<Blog>(entity =>
     {
        entity.HasMany(d => d.Posts).WithMany(p => p.Blogs)
	  .UsingEntity<BlogPost>(
           r => r.HasOne<Post>().WithMany(),
          l => l.HasOne<Blog>().WithMany());
     }
  }
}

public class BlogPost
{
  public int BlogId { get; set; }
  public int PostId { get; set; }
}
```

This solution doesn't work and generates the error
`` Cannot use table 'BlogPosts' for entity type 'BlogPost' since it is being used for entity type 'BlogPost (Dictionary<string, object>)'``  I guess because it conflicts with the autogenerated implementation.

Do you know of a way to accomplish this?

**Comment by ErikEJ** [comment]
@MariovanZeist If you want to bring back the many to many entity, then EF Core Power Tools can do that for you.

**Comment by MariovanZeist** [comment]
@ErikEJ That looks very promising, 
I am closing this issue, as my original question has been answered, but I will follow up on my findings with the CLI Powertool on your github @ErikEJ .
Thank you all.
