### ISSUE TITLE
DetectChanges changes EntityEntry.OriginalValues

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#31592]
## File a bug

When I call DbContext.EntityEntry.DetectChanges() I would expect that original values remains the same as before calling it.
For entries with EntityState = Added, the original values are changed to current values, even if I explicitly set original values

### Include your code

```C#
using var ctx = new BloggingContext();
var entity1 = new Blog { SomeProp = "Default value" }; 
var entry1 = ctx.Add(entity1);	    
Console.WriteLine(entry1.OriginalValues.GetValue<string>("SomeProp")); //writes "Default value"

entity1.SomeProp = "Modified";
Console.WriteLine(entry1.OriginalValues.GetValue<string>("SomeProp"));//writes "Default value"

ctx.ChangeTracker.DetectChanges();
Console.WriteLine(entry1.OriginalValues.GetValue<string>("SomeProp")); //incorrectly writes "Modified"
```
See demo: https://dotnetfiddle.net/3t2N6X

### Include provider and version information

EF Core version: 7.0.10
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)

**Comment by ajcvickers** [comment]
@Liero This is by-design. Original values represent the values in the database. For Added entities, there are no values in the database, so we return current values instead.

**Comment by Liero** [comment]
I wanted to track changes since the entity was attached (or since I explicitly set original values). 
I will leave it up to you, whether it is a good idea or not
