### ISSUE TITLE
Is it possible to create a value generation strategy so it produces a single value for all the entries saved during SaveChanges?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#31608]
I have a timestamp value generator, and I'd like all properties which have this generator to have the same value when entities are saved.

Is it possible to achieve this kind of behavior with value generator?

**Comment by ErikEJ** [comment]
Do you mean rowversion or a date?

**Comment by voroninp** [comment]
Date

**Comment by ajcvickers** [comment]
No.

**Comment by roji** [comment]
@voroninp you can achieve this by overriding SaveChanges and going over all change entries.

**Comment by voroninp** [comment]
@roji that's how I currently do it.

**Comment by voroninp** [comment]
@roji , btw, if I want to make it as a NuGet extension is it possible to add interceptors, conventions and other staff within one extension method: `opt.GenerateTimestampsOnSave()`?

`DbContextOptionsBuilder` allows to add interceptors, but I cannot register service in internal DI container, and use it to resolve interceptor. 

`ModelConfigurationBuilder` - allows me to add conventions. But those are used in different methods of `DbContext`.

**Comment by roji** [comment]
No, interceptors and conventions are different things that work at different levels of EF. Note that interceptors generally are meant to be more app-specific, and not meant to be manipulated from an extension.

**Comment by voroninp** [comment]
Ok, what are the alternatives then?
