### ISSUE TITLE
Problem while saving Byte array in mysql database with entity framework core

### ISSUE THREAD

**Issue by jwdsoft** [dotnet/efcore#31614]
I have a problem while trying to save a byte array to a mysql database all data get saved except the byte array which stays always empty but entity framework doesn't throw any exception it acts like all data is being saved successfully
the same code worked fine on Entity Framework for dotnet Framework. 
here is the info on the console

    
    info: 02/09/2023 21:07:50.424 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
          Executed DbCommand (23ms) [Parameters=[@p0='1', @p1='0x89504E470D0A1A0A0000000D49484452000009B0000003CF08060000001F667F...' (Size = -1)], CommandType='Text', 
    CommandTimeout='30']
          INSERT INTO `ImageData` (`Id`, `ImageBlob`)
          VALUES (@p0, @p1);

And here is the entire program code

    
    await using var ctx = new BlogContext();
    Byte[] img = File.ReadAllBytes("chrono.png");
    ctx.ImageData.Add(new ImageDat { Id=1,ImageBlob = img});
    ctx.SaveChanges();

    public class BlogContext : DbContext
    {
        public DbSet<Orders> orders { get; set; }
        public DbSet<OrderDetails> orderDetails { get; set; }
        public DbSet<ImageDat> ImageData { get; set; } = null!;
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseMySQL(@"Server=localhost;Database=test;User=root;Password=;port=3306")
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging();
    
    }
    public class ImageDat
    {
        public int Id { get; set; }
        public Byte[]? ImageBlob { get; set; }
    }

**Comment by roji** [comment]
@jwdsoft please report this bug to the maintainers of the MySQL connector - that's not maintained in this repo. You may also want to give the [Pomelo MySQL provider](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) a try ([see our providers page](https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli)).
