### ISSUE TITLE
Ability to use application logging subsystem

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [dotnet/efcore#31613]
We use ef bundle to create migration bundle that run as job that installed by helm
All output of process output scrapped by distributed logging system and parsed - system expected json format. But bundle write raw text that cannot be parsed.
Is this possible to use default ILogger that already configurated in application with bundle?

**Comment by ajcvickers** [comment]
@anatoly-kryzhanovsky If the application uses ILogger, then the bundle should also use that. If this isn't happening, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by anatoly-kryzhanovsky** [comment]
ok, i try to create it

**Comment by anatoly-kryzhanovsky** [comment]
ok, i try reproduce error on empty project - and all work fine. so i think that there is error in my exists project. i return with more details if found reason for that.
