### ISSUE TITLE
ModelBuilder.Entity does not return generic instance.

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#31626]
Classifying this as a bug rather than a feature request because, arguably, the current behavior is unintuitive. 

<c>ModelBuilder.Entity&lt;T&gt;()</c> returns an EntityTypeBuilder&lt;T&gt;, while <c>ModelBuilder.Entity( typeof(T))</c> returns an <c>EntityTypeBuilder</c> that is not an <c>EntityTypeBuilder&lt;T&gt;</c>. It would make far more sense that both of them return an instance of <c>EntityTypeBuilder&lt;T&gt;</c>.

Because of this, if one does not know T at compile time then it is difficult to get an instance of <c>EntityTypeBuilder&lt;T&gt;</c>. This actually is a live issue for me as I would like to use reflection to call a method similar to <c>IEntityTypeConfiguration&lt;TEntity&gt;.Configure</c> and pass the generic instance. The reason for doing this myself instead of calling ApplyConfigurationsFromAssembly is primarily that ApplyConfigurationsFromAssembly doesn't call base classes before derived classes and doesn't pass the ModelBuilder. 

It is not very easy to get the <c>Entity&lt;T&gt;</c> method by reflection. The workaround is:  
 
    IEnumerable<MethodInfo> entityMethods = modelBuilder.GetType().GetMember(nameof(ModelBuilder.Entity),BindingFlags.Public|BindingFlags.Instance).Where( m => m is MethodInfo).Cast<MethodInfo>();
    MethodInfo entityMethod = entityMethods.Single(em => em.IsGenericMethod && em.GetParameters().Count() == 0 && em.GetGenericArguments().Count() == 1).MakeGenericMethod(clrType);
    EntityTypeBuilder entityTypeBuilder = entityMethod.Invoke(modelBuilder, null) as EntityTypeBuilder ?? throw new InvalidOperationException();
    Debug.Assert( entityTypeBuilder.GetType().IsAssignableTo( typeof(EntityTypeBuilder<>).MakeGenericType(clrType)));

**Comment by roji** [comment]
I might be misunderstanding what you're asking, if the Entity() method isn't generic (i.e. it accepts a Type parameter and has no generic type parameters), then it cannot return an EntityTypeBuilder<T> in its signature. It could return a non-generic EntityTypeBuilder in its signature, and in actuality return a generic EntityTypeBuilder<T> which **extends** the non-generic EntityTypeBuilder, but the consumer would then have to perform the down-cast from EntityTypeBuilder to EntityTypeBuilder<T>. And at that point, why isn't the consumerj ust calling the generic Entity<T>() method in the first place?

Can you please provide the actual use-case scenario where you want to call a non-generic Entity() - passing a Type argument - and need a generic EntityTypeBuilder<T> to be returned?

**Comment by sjb-sjb** [comment]
Hi @roji 

Correct, although the return signature is EntityTypeBuilder I believe it should return an instance of EntityTypeBuilder&lt;TEntity&gt;. This would be useful because you can then call by reflection a method whose parameter has type EntityTypeBuilder&lt;T&gt;. An example would be calling a method implementing IEntityTypeConfiguration&lt;TEntity&gt;.Configure( EntityTypeBuilder&lt;TEntity&gt;). You can obtain and call that method easily by reflection.

Steve

**Comment by ajcvickers** [comment]
Note from triage: this is something we could do in many places, and we have discussed doing so before, but ultimately the result is almost always still using Reflection at some point. It might be that you have a special case where that's not true, but it's a buig change with a perf impact, so we're not going to change the behavior for your case.

**Comment by sjb-sjb** [comment]
Understandable. @ajcvickers  maybe an optional flag parameter that the user can pass to ApplyConfigurationsFromAssembly that would cause it to sort the Configure calls in base-class-first order?

About getting the model builder from the entity type builder, I’m not familiar with the internal structure but it seems plausible to have a pointer back to the model builder from the entity type builder.

**Comment by AndriySvyryd** [comment]
> Understandable. @ajcvickers maybe an optional flag parameter that the user can pass to ApplyConfigurationsFromAssembly that would cause it to sort the Configure calls in base-class-first order?

See https://github.com/dotnet/efcore/issues/22035. That should allow you to implement the base-class-first order.

> About getting the model builder from the entity type builder, I’m not familiar with the internal structure but it seems plausible to have a pointer back to the model builder from the entity type builder.

See https://github.com/dotnet/efcore/issues/15258. The API design is not final, but it should enable your scenario.

**Comment by ajcvickers** [comment]
Note from triage: the issues Andriy linked cover the scenario in a more compelling way than returning a generic instance here.
