### ISSUE TITLE
TPH + HasTrigger: Potential undocumented breaking change in EFC8

### ISSUE THREAD

**Issue by Suchiman** [dotnet/efcore#31627]
## Ask a question

We've just tried our Code with EFC8 and ran into the following issue:
```
InvalidOperationException: Can't configure a trigger on entity type 'Derived', which is in a TPH hierarchy and isn't the root. Configure the trigger on the TPH root entity type 'Base' instead.
```

The reason this occurs is due to the `BlankTriggerAddingConvention` workaround that was described in the EFC7 breaking changes that we've applied https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sql-server-tables-with-triggers-or-certain-computed-columns-now-require-special-ef-core-configuration

That workaround calls HasTrigger on every table which seems to be no longer allowed on every table in EFC8.

This change should be [documented](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes) and a revised workaround provided.

### Include provider and version information

EF Core version: 8.0 Preview 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0 P7
Operating system: Windows 10
IDE: Visual Studio 2022 17.8P1

**Comment by ajcvickers** [comment]
Note from triage: make it a warning and update the guidance.

**Comment by roji** [comment]
Note that in EF 8.0 we have the new TableBuilder.UseSqlOutputClause (for SQL Server) and TableBuilder.UseSqlReturningClause (for SQLite) which replaces the "add a blank trigger" technique.
