### ISSUE TITLE
Incorrect warning for TPC and Guid Id

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#31629]
I get the following error when I generate the initial migration for my model: "The entity type 'xxx' is using the table per concrete type mapping strategy, but property 'Id' is configured with an incompatible database-generated default. Configure a compatible value generation strategy if available, or use non-generated key values."

Here 'xxx' is a concrete entity type. I am indeed using Type-Per-Concrete Class for all entities in the model. The Id property is declared in an abstract base class as shown in the listing below. The generated model snapshot from the migration includes b => b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT") for the "xxx" entity.

        [Key]
        public Guid Id {
            get { 
                return this._id;
            }
            private set {
                ...
            }
        }
        private Guid _id;

Can you tell me what is going wrong here? I'm not clear what the message means -- what incompatibility is being referred to? Isn't the Guid supposed to be database generated? 

One other question, relating to the fact that I am using SQLite. I noticed some talk out there about the Guid being stored in uppercase instead of standard lower case by SQLite, and this causing various problems during update. See [19651](https://github.com/dotnet/efcore/issues/19651) and [this StackOverflow discussion](https://stackoverflow.com/questions/69209096/guid-values-stored-in-uppercase-by-ef-core-5-and-sqlite). However these references are a bit old, and I am not clear what the final resolution of these questions is. At one point (unfortunately not reproducible) I saw an upper case Guid values in my database and I received an error message saying that 0 rows were updated instead of 1, which fits the problem description in these articles. What is the current advice in relation to casing the Guid?  

P.S. Since SQLite doesn't support autoincrement or named increment sequences, as far as I can tell the only real option is to use Guid for the Id. If there are alternatives I would be interested.

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sjb-sjb** [comment]
Hi @ajcvickers, thanks for writing. Steps to reproduce:

1. Create a new Solution using the "Blank App, Packaged (WinUI 3 in Desktop)" template and add or upgrade to the latest NuGets for Microsoft.EntityFrameworkCore.Sqlite, Microsoft.EntityFrameworkCore.Tools, Microsoft.Windows.SDK.BuildTools, and Microsoft.WindowsAppSDK. 
2. Add the following entities

    abstract public class AbstractEntity
    {
        [Key]
        public Guid Id {
            get {
                return this._id;
            }
            private set {
                this._id = value;
            }
        }
        private Guid _id;
    }

    public class ConcreteEntity : AbstractEntity
    {
        public string Gravel {
            get {
                return this._gravel;
            }
            private set {
                this._gravel = value;
            }
        }
        private string _gravel;
    }

3. Add the following context

    public class SpecializedDbContext: DbContext
    {
        public DbSet<ConcreteEntity> Concretes => this.Set<ConcreteEntity>();

        public SpecializedDbContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.UsePropertyAccessMode(PropertyAccessMode.Field); // this is now the default in EF Core 3

            ((EntityTypeBuilder)modelBuilder.Entity<AbstractEntity>()).UseTpcMappingStrategy();
            ((EntityTypeBuilder)modelBuilder.Entity<ConcreteEntity>()).UseTpcMappingStrategy();
        }
    }

    public class SpecializedContextDesignTimeFactory : IDesignTimeDbContextFactory<SpecializedDbContext>
    {
        public SpecializedDbContext CreateDbContext(string[] args)
        {
            var contextOptionsBuilder = new DbContextOptionsBuilder<SpecializedDbContext>();
            contextOptionsBuilder.UseSqlite<SpecializedDbContext>();
            DbContextOptions<SpecializedDbContext> contextOptions = contextOptionsBuilder.Options;
            return new SpecializedDbContext(contextOptions);
        }
    }

4. Open a Package Manager window and run this command: Add-Migration InitialCreate -Project Testy -Context SpecializedDbContext -Namespace Testy -OutputDir "Migrations" -Verbose

5. Observe the error message "The entity type 'AbstractEntity' is using the table per concrete type mapping strategy, but property 'Id' is configured with an incompatible database-generated default. Configure a compatible value generation strategy if available, or use non-generated key values."

**Comment by sjb-sjb** [comment]
P.S. Note lines 22 - 25 of the generated model snapshot do include value generation: 

```
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

```

**Comment by sjb-sjb** [comment]
The problem seems to be the line

   `((EntityTypeBuilder)modelBuilder.Entity<ConcreteEntity>()).UseTpcMappingStrategy();`

The UseTpcMappingStategy method should only be applied to the abstract base class. 

The messages obviously are far from clear in this example. My suggestion would be that UseTpcMappingStrategy could use reflection to test the entity and throw an exception if it is a concrete class.

**Comment by sjb-sjb** [comment]
Even though the error message is bad, the documentation is correct. I doubt that this is a priority.

**Comment by ajcvickers** [comment]
Output from Migrations when value generation strategy is set on a subtype:

```
PS C:\local\code\AllTogetherNow\Daily> dotnet ef migrations Add One
Build started...
Build succeeded.
warn: 9/13/2023 20:41:41.898 RelationalEventId.TpcStoreGeneratedIdentityWarning[20609] (Microsoft.EntityFrameworkCore.Model.Validation) 
      The entity type 'AbstractEntity' is using the table per concrete type mapping strategy, but property 'Id' is configured with an incompatible database-generated default. Configure a compatible value generation strategy if available, or use non-generated key values.
warn: 9/13/2023 20:41:41.908 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
The entity type 'AbstractEntity' is using the table per concrete type mapping strategy, but property 'Id' is configured with an incompatible database-generated default. Configure a compatible value generation strategy if available, or use non-generated key values.
warn: 9/13/2023 20:41:42.010 RelationalEventId.TpcStoreGeneratedIdentityWarning[20609] (Microsoft.EntityFrameworkCore.Model.Validation)
      The entity type 'AbstractEntity' is using the table per concrete type mapping strategy, but property 'Id' is configured with an incompatible database-generated default. Configure a compatible value generation strategy if available, or use non-generated key values.
Done. To undo this action, use 'ef migrations remove'
PS C:\local\code\AllTogetherNow\Daily> 
```

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=test.db")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AbstractEntity>().UseTpcMappingStrategy();
        modelBuilder.Entity<ConcreteEntity>().UseTpcMappingStrategy();    }
}

public abstract class AbstractEntity
{
    public Guid Id { get; set; }
}

public class ConcreteEntity : AbstractEntity
{
    public string Gravel { get; set; }
}
```

**Comment by ajcvickers** [comment]
Note from triage: the message here is incorrect and happens only when `.UseTpcMappingStrategy();` is called on a non-base type.
