### ISSUE TITLE
💡 Feature Request: Scaffolding models (via "DB First") can generate enums instead of a string/number if we can give the scaffold some hints

### ISSUE THREAD

**Issue by PureKrome** [dotnet/efcore#31644]
👋🏻 G'day EF team 🦄 

I'm old school and LOVE doing all my changes "DB First" (and always afterwards). I love using the `ef dbcontext scaffold` command. Thank you!

## Problem

When I generate my models the scaffold generator has no idea that a db column is actually a representation of an `enum` in my system. There's no way it _could know_ without some help. 

It would be really lovely if we could provide some 'hints' to the generator to know how to replace the destination `type` with a custom `enum`. This means every time I generator the new models and overwrite my old models I don't need to replace all my `int` with `MyCustomeEnumType`

## Suggestion

We can provide hints either via:
- a file which has a specific simple format and we provide that 'hint' file as an optional param in the CLI. e.g. `ef dbcontext scaffold <conn string> <sqlserver> -f -o MyModels -h dbScaffoldHints.txt`
- if the source DB is MS SqlServer, then maybe take advantage of each column (in a table) having a `Description` in the `Column Properties`

⚡IMPORTANT NOTE: the scaffold will NOT generate the `enum` file at all. That is left for the developer to do and that enum should exist somewhere else in their Solution.

### File example

simple format like this
```
table name,column name,enum type
```

e.g.
```
Users,Status,StatusType
Orders,OrderState,OrderStateType
...
```

Of course, if people want JSON, that could work (but more verbose, now). YAML will never be tolerated as an accepted file format, here. 🌶️

### Column Property example

Here's a screenshot of a DB Table/Column from Azure Data Studio

![image](https://github.com/dotnet/efcore/assets/899878/df28d65c-4760-4683-aa82-1b59123748fd)

I have no idea where that `Description` column property info is stored but ADS shows this code:

```
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'AdminRoleType', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AdminUsers', @level2type = N'COLUMN', @level2name = N'AdminRole';
```

So maybe the scaffold can query where this information exists and replace the `Type` with the value provided (in this case, the value is `AdminRoleType`)

🙏🏻 Praying that this issue gets some 👀 from the EF Dev's 🦄 and might be strongly considered.

**LETS MAKE SCAFFOLDING AWESOME**

![image](https://github.com/dotnet/efcore/assets/899878/6300d9db-18bf-46a5-beb9-ba6fd3497001)

**Comment by ErikEJ** [comment]
@PureKrome You can do this today by adding the "hints" to a T4 template.

Docs about [T4 templates with EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli)

Example customization [here](https://github.com/ErikEJ/EFCorePowerTools/issues/1472#issuecomment-1220273164)

**Comment by PureKrome** [comment]
Wait what? this exists already? T4 eh .. this could be tricky. Ok, i'll give this a crack. I'll be back with some answers.

**Comment by ajcvickers** [comment]
Note from triage: T4 templates and/or the Power Tools are the way to do this.
