### ISSUE TITLE
Lazy Loading without proxies documentation is not a pit of success

### ISSUE THREAD

**Issue by Suchiman** [dotnet/efcore#31659]
## Ask a question

If you follow the instructions to lazy load without proxies [here](https://learn.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies), there are several pitfalls not mentioned in the documentation.

In particular for queries in the shape of:
```csharp
var p = context.Posts.AsNoTracking().Include(x => x.Blog).First();
Console.WriteLine(p.Blog.Id);
```
and the Exception:
```
System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning': An attempt was made to lazy-load navigation 'Blog' on a detached entity of type 'Post'. Lazy loading is not supported for detached entities or entities that are loaded with 'AsNoTracking'.
```

# Current Behavior
- If you ctor inject `ILazyLoader` and then store `ILazyLoader` into anything that isn't a property that has both a getter and a setter, you'll receive this exception, even on explicitly included navigations that are provably loaded in the field as confirmed by the debugger at the time that `LazyLoader.Load` is called.
- If you add a property of type `ILazyLoader`, with `{ get; set; }`, then the ctor is optional, EF will set this property (via reflection) regardless of it's name and this seems to be the only case where the exception does not occur.
- If you use `Action<object, string>` to avoid a direct EFC dependency, then you'll receive this exception no matter what it seems.
- If `ILazyLoader` is declared in a base class and marked private, then EF will not set it via reflection, if it is marked protected however, EF will.

# Expected Behavior
Ideally, EFC should not generate that bogus error, regardless of how a lazy loader is injected and being used. If that isn't feasible, the documentation should be clarified to enumerate the exact conditions necessary for this to work.

### Include provider and version information

EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.8P1

P.S.: If you're interested in the reason for us using them, we've migrated from EF6 to EFC7 and we've unknowingly taken a dependency on the performance characteristics of change tracking proxies in EF6. After the migration and finally pushing to prod, we've noticed severe performance regressions in some key scenarios where Snapshot change tracking causes DetectChanges to take more than a second to complete for a few thousand loaded entities where only a dozen are actually modified. We've already been using LazyLoadingProxies so the thought to just switch to ChangeTrackingProxies came to mind, which was unsuccessful however, since EFC (unlike EF6) requires everything to be proxies then, meaning we would need to replace every object construction by CreateProxy<T>() throughout the codebase which was just unacceptable, both due to risk / work and since it would act contrary to our goal of improving null safety via required properties. We've also noticed that Castle.Proxies have atrocious performance characteristics, causing multiple GC allocations for each and every property access. So we've turned to Fody to implement PropertyChanged / PropertyChanging as well as LazyLoading via ILazyLoader automatically on our database entities. This improved our performance in realistic benchmarks by anywhere from 2x up to 10x. It has been a bumpy road to get there though, and this issue is some of the reasons.

**Comment by ajcvickers** [comment]
@Suchiman Please test with the latest [daily build](https://github.com/dotnet/efcore/blob/release/8.0/docs/DailyBuilds.md). We have made several improvements to lazy loading in EF8.

**Comment by space-alien** [comment]
> * If you use `Action<object, string>` to avoid a direct EFC dependency, then you'll receive this exception no matter what it seems.

This is what I am experiencing in EF 8.0.3 when trying to use `AsNoTracking()` despite eager loading all navigations with `Include()`.
