### ISSUE TITLE
Core: Add DbContext.OnConfiguringServices

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#3165]
When a service provider is created by the framework, we should have a hook users can use to override services. One proposal is...

``` C#
class DbContext
{
    protected virtual void OnConfiguringServices([NotNull] IServiceCollection services)
    {
    }
}
```

**Comment by bricelam** [comment]
Implemented this in [bricelam:services](https://github.com/aspnet/EntityFramework/compare/dev...bricelam:services), but didn't like it.

**Comment by rowanmiller** [comment]
We aren't going to use this pattern, we will have higher level sugar APIs for things that are common to replace. For other things, storing a static ServiceProvider in your context isn't too difficult.
