### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design v7 Is Not Net6 Compatible

### ISSUE THREAD

**Issue by brandonryan** [dotnet/efcore#31685]
`Microsoft.EntityFrameworkCore.Design@7.0.10` Requires Net7 System libraries. 

Dependency Resolution Chain:
- `Microsoft.EntityFrameworkCore.Design@7.0.10`
- `Microsoft.Extensions.DependencyModel@7.0.0`
- `System.Text.Json@7.0.0`
- `System.Text.Encodings.Web@7.0.0`

Runtime exceptions occur when project is targeting net6 and is using above system libraries.

Runtime exception:
```
message=Could not load file or assembly 'System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by brandonryan** [comment]
I have a day job.
The issue is very clear.
I'll get around to it when im not slammed with production work.

**Comment by ajcvickers** [comment]
This works for me:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.10" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="7.0.0" />
        <PackageReference Include="System.Text.Json" Version="7.0.0" />
        <PackageReference Include="System.Text.Encodings.Web" Version="7.0.0" />
    </ItemGroup>
</Project>
```

As does this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.10" />
    </ItemGroup>
</Project>
```

**Comment by brandonryan** [comment]
The problem is when you try to use `System.Text.Json` in your code. Youll get a runtime exception because its looking for version 7
...

Ill reproduce in a bit..
