### ISSUE TITLE
How to disable debug messages logged to the Debug console

### ISSUE THREAD

**Issue by silkfire** [dotnet/efcore#31694]
Posting this SO question (https://stackoverflow.com/questions/76712936/how-to-prevent-entity-framework-core-from-logging-sql-queries-to-visual-studio-o) here for wider reach.

Is there currently a way to disable the logging of queries to the Debug console when running an application from within Visual Studio? I tried to disable logging (both by using ClearProviders and LogTo + filter: that returns `false`) but that does not seem to have any effect on the output. It's even shown when running in Release mode, which kind of surprised me.

![image](https://github.com/dotnet/efcore/assets/1554615/bce681e7-0a91-4361-8086-ae3ac5d258ed)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
@silkfire This application doesn't send any EF logs to the Debug console:

```C#
using Microsoft.EntityFrameworkCore;

using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();
    await context.Blogs.ToListAsync();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow");

    public DbSet<Blog> Blogs => Set<Blog>();
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
```

**Comment by ErikEJ** [comment]
Maybe "any ASP.NET Core app" ??

**Comment by silkfire** [comment]
Perhaps, as I have only used EF ever in an ASP.NET Core application.

**Comment by ajcvickers** [comment]
@silkfire ASP.NET Core sets up logging by default. EF hooks into that logging. But that is _all based on ILogger_, which you said was not the culprit. As I said above, the best thing you can do is attach a small, runnable project or post a small, runnable code listing (like I did above) that reproduces what you are seeing so that we can investigate.

**Comment by silkfire** [comment]
I've realized that the culprit most probably lies with **Oracle.EntityFrameworkCore** as that is the provider I am using. I tried your code sample (which uses SQL Server) but did not see any non-`ILogger` output in the Debug console, so basically same result as you had.

But after switching to *Oracle.EntityFrameworkCore*, I immediately saw the logging to the Debug console occur:

![image](https://github.com/dotnet/efcore/assets/1554615/e820c83b-cc47-44ad-b59a-dfc5ace4d118)

I've uploaded a reproducible sample but it requires you to have access to an Oracle database (either a local instance or a remote connection).

https://github.com/silkfire/EfCoreSample

**Comment by roji** [comment]
@silkfire if this problem is specific to the Oracle provider, you'll have to open an issue with its maintainers - we don't maintain that provider.

**Comment by silkfire** [comment]
I took the time to properly debug my app to find out what's actually going on under the covers and finally found the answer.

In the method `Task<RelationalDataReader> OracleRelationalCommandBuilderFactory.ExecuteReaderAsync()` the code actually makes a call to `Debug.WriteLine` unconditionally, so there's no way to disable that, unfortunately.

![image](https://github.com/dotnet/efcore/assets/1554615/82d43397-601b-4490-9fa7-4cb70940fbb6)

Seems almost like an oversight by the developers, but oh well - I'll just accept it and move on with my life.

**Comment by silkfire** [comment]
I couldn't find anywhere where to report it, the library doesn't have a GH repository.

**Comment by ErikEJ** [comment]
@alexkeh FYI

**Comment by alexkeh** [comment]
@silkfire This bug (35579522) has been fixed and will be part of the next Oracle EF Core release, version 7.21.12.

In the future, you can report Oracle .NET related issues on the [Oracle .NET GitHub site](https://github.com/oracle/dotnet-db-samples/issues).

**Comment by silkfire** [comment]
Thank you very much for the good news. I saw that repo but din't know it could be used to report bugs for the ODP as well. I'll remember that for future reference.

How does the versioning system work for the NuGet package? The latest version is 3.21.110 (July 25) and the next version is suddenly 7.21.12?

**Comment by alexkeh** [comment]
The bug is in the Oracle EF Core NuGet package, not the ODP.NET Core package. The Oracle EF Core package versioning leads with the EF Core version it supports. In this case, it's version 7.

The ODP.NET Core version leads with the minimum .NET Core version it supports. In the version you reference, it can support .NET Core 3.x and higher.

The next two version numbers are the Oracle major and minor version numbers.

**Comment by silkfire** [comment]
Sorry I got a bit confused there for a moment. Of course it's EF Core we're talking about 😊

**Comment by alexkeh** [comment]
October
