### ISSUE TITLE
FilteredInclude does not filter when using SelectMany

### ISSUE THREAD

**Issue by mgrosperrin** [dotnet/efcore#31697]
Hello team,

I am trying to delete some child entities in an aggregate without loading them. I try to use the "new" `ExecuteDelete` method combined with a filtered include to do it without loading the entities first.

I see that all child entities are removed when doing so.

By investigating deeper, I am able to have a similar issue when loading the entities:

```
var widgets = context.Dashboards
        .Include(x => x.Widgets.Where(w => w.WidgetId == widgetId))
        .Where(d => d.DashboardId == dashboardId)
        .SelectMany(d => d.Widgets);
```
With this query, the generated SQL does not filter on the WidgetId property/column (only the DashboardId).

If I don't use the `SelectMany`, the generated SQL query is correct (but returns/delete the dashboard and not the widget).

You can find a complete reproduction here: https://github.com/mgrosperrin/repro_issues/tree/efcore/filteredinclude

### Include provider and version information

EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0

**Comment by ajcvickers** [comment]
@mgrosperrin The `Where` clause applied in `Include` only applies to entities that are loaded via the relationship from `Dashboard` when `Dashboard` objects are loaded from the database. But the query never does this, because it selects out the `Widgets` directly, meaning that the `Include` is no longer meaningful and is dropped. Instead, but the `Where` clause doing the filtering into the main query.

**Comment by mgrosperrin** [comment]
Hi @ajcvickers ,
Thanks for you answer.
I just don't know how to filter the `Widgets` children property 😞 .

I tried this
```` chsarp
var dashboardWithExpectedWidget = context.Dashboards
        .Include(x => x.Widgets.Where(w => w.WidgetId == widgetId))
        .Where(d => d.DashboardId == dashboardId && d.Widgets.Any(w => w.WidgetId == widgetId))
        ;
````

But I will have the dashboard and not the widget.
Not a big deal for querying the data, but the `ExecuteUpdate` and `ExecuteDelete` will not work unfortunately.

Any tips to allow this?

**Comment by ajcvickers** [comment]
@mgrosperrin What are you trying to achieve? `ExecuteUpdate` and `ExecuteDelete` do not support use of `Include`.
