### ISSUE TITLE
Mapping the two unrelated entity types to the same table should generate a better warning.

### ISSUE THREAD

**Issue by DanyaSWorlD** [dotnet/efcore#31703]
I have two entities with identical structure mapped to one table. One of them can be created easily, second one throws an exception.
Why only one entity included in table sharing can be created directly?

Here is [Demo project](https://github.com/DanyaSWorlD/Ef-core-Table-Sharing-Issue-Demo)

Let's test on such model:
```
public abstract class AbstractUser
{
    public int Id { get; set; }

    public string Name { get; set; }
}

public class ExactUser : AbstractUser { }

public class SharedUser : AbstractUser { }
```

And configure table sharing between `ExactUser` and `SharedUser`

```
public class ExactUserConfiguration : IEntityTypeConfiguration<ExactUser>
{
    static readonly internal string TableName = nameof(ExactUser);

    public void Configure(EntityTypeBuilder<ExactUser> builder)
    {
        builder.ToTable(TableName)
            .HasKey(x => x.Id);

        builder.Property(x => x.Id)
            .IsRequired();

        builder.Property(x => x.Name)
            .IsRequired()
            .HasMaxLength(255);
    }
}
```
```
public class SharedUserConfiguration : IEntityTypeConfiguration<SharedUser>
{
    static readonly internal string TableName = nameof(ExactUser);

    void IEntityTypeConfiguration<SharedUser>.Configure(EntityTypeBuilder<SharedUser> builder)
    {
        builder.ToTable(TableName)
            .HasKey(x => x.Id);

        builder.Property(x => x.Id)
            .IsRequired();

        builder.Property(x => x.Name)
            .IsRequired()
            .HasMaxLength(255);

        builder.HasOne<ExactUser>()
            .WithOne()
            .HasForeignKey<SharedUser>(x => x.Id)
            .IsRequired();
    }
}
```
In this case creation of `exactUser` passes successfully
```
var exactUser = new ExactUser { Name = "ExactUser" };
db.ExactUsers.Add(exactUser);
db.SaveChanges();
```
When `sharedUser` fails
```
var sharedUser = new SharedUser { Name = "SharedUser" };
db.SharedUsers.Add(sharedUser);
db.SaveChanges(); // Invalid operation exception
```
Exception:
```
System.InvalidOperationException: "The value of 'SharedUser.Id' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known."
```

Only workaround I found this far is to remove `builder.HasOne` entry from `SharedUser` configuration and apply shema
```
builder.ToTable(TableName, "dbo")
```
only to `ExactUser`. This tricks Ef Core and it thinks that this entities linked to different tables. But this approach introduces more errors and unexpected behaviour when table shares between more than two entities. So, this is not an option.

Actually the question is, is discribed behaviour expected and how to deal with `SharedUser` without creating different context?

### Provider and version information

EF Core version: 7.0.11
Database provider: (Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET 7.0)
Operating system: Windows 10 2021H2 and Windows 11 2022H2
IDE: Visual Studio 2022 17.7.2

**Comment by ajcvickers** [comment]
> I have two entities with identical structure mapped to one table. 

What is your goal in doing this? Are the two entity types conceptually related to each other? If so, in what way?

**Comment by DanyaSWorlD** [comment]
This is all for DDD. I have objects with the same data structure, but slightly different behavior depending on the domain

**Comment by ajcvickers** [comment]
How do you determine if a row represents one type or the other?

**Comment by DanyaSWorlD** [comment]
They are same from data perspective, so I can save `ExactUser` and get him as `SharedUser` as I did in demo project. So this fits my needs and works as I expected. Only one issue - I can't add `SharedUser` directly.

**Comment by ajcvickers** [comment]
EF Core doesn't support having two CLR types mapped to the same table without there being an inheritance or containment relationship between the two types.

**Comment by DanyaSWorlD** [comment]
Both types are inherited from `AbstractUser`

```
public abstract class AbstractUser
{
    public int Id { get; set; }

    public string Name { get; set; }
}

public class ExactUser : AbstractUser { }

public class SharedUser : AbstractUser { }
```

If it is not supported, why there isn't any error on db configuration?

**Comment by AndriySvyryd** [comment]
@DanyaSWorlD 

```C#
        builder.HasOne<ExactUser>()
            .WithOne()
            .HasForeignKey<SharedUser>(x => x.Id)
            .IsRequired();
```

The above extract of your configuration code links the two entity types and makes `SharedUser` the dependent. This means that a `SharedUser` can only be inserted when an `ExactUser` is inserted. EF doesn't support a mapping where you could insert either entity to a shared table independently.
