### ISSUE TITLE
Treat SQL Server Error Number 1222 as Transient (Lock request time out period exceeded)

### ISSUE THREAD

**Issue by freakingawesome** [dotnet/efcore#31724]
The SQL Server exception number 1222 (Lock request time out period exceeded) should be treated as a transient exception.

1. The [Microsoft.Data.SqlClient](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconfigurableretryfactory?view=sqlclient-dotnet-standard-5.1) documentation lists 1222 as a transient error in need of a retry (source code for [SqlConfigurableRetryFactory.cs](https://github.com/dotnet/SqlClient/blob/93d4398fbd2ac7aa3f031f8f8fdb908255e45316/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryFactory.cs#L45) contains this number)
2. `sys.messages` lists the error text for 1222 as "Lock request time out period exceeded."
3. [Official Microsoft documentation](https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-1222-database-engine-error) recommends retrying the transaction after it has been aborted

Adding the error number to the giant case statement inside SqlServerTransientExceptionDetector.cs should be enough to satisfy this request.

**Comment by freakingawesome** [comment]
There are two other error numbers inside the [SqlConfigurableRetryFactory](https://github.com/dotnet/SqlClient/blob/93d4398fbd2ac7aa3f031f8f8fdb908255e45316/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryFactory.cs#L56-L57) class which aren't treated as transient by Entity Framework:

- 42108,  // Can not connect to the SQL pool since it is paused. Please resume the SQL pool and try again.
- 42109,  // The SQL pool is warming up. Please try again.

I didn't include these numbers in this PR explicitly because the are not listed in sys.messages, but they are included in official Microsoft documentation, so perhaps it makes sense to broaden this PR to include those two as well?

- [MSSQLSERVER_42108](https://learn.microsoft.com/sv-se/sql/relational-databases/errors-events/mssqlserver-42108-database-engine-error?view=sql-server-2017)
- [MSSQLSERVER_42109](https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-42109-database-engine-error?view=sql-server-ver16)

**Comment by AndriySvyryd** [comment]
> I didn't include these numbers in this PR explicitly because the are not listed in sys.messages, but they are included in official Microsoft documentation, so perhaps it makes sense to broaden this PR to include those two as well?

You can submit a separate PR for this

**Comment by AndriySvyryd** [comment]
> I didn't include these numbers in this PR explicitly because the are not listed in sys.messages, but they are included in official Microsoft documentation, so perhaps it makes sense to broaden this PR to include those two as well?

You can submit a separate PR for this
