### ISSUE TITLE
SqliteException: SQLite Error 19: 'NOT NULL constraint failed' when value is generated on add or update.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#31730]
## File a bug

I have the following entity config:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Entity>(b =>
    {
        b.Property(_ => _.Id).ValueGeneratedNever();
        b.Property(_ => _.Timestamp).ValueGeneratedOnAddOrUpdate().HasValueGenerator<TimestampGenerator>();
    });
}
```

When I save new entity, I get this error:
> SQLite Error 19: 'NOT NULL constraint failed: Entity.Timestamp'.

If I replace `ValueGeneratedOnAddOrUpdate()` with `ValueGeneratedOnAdd()` , `SaveChanges` does its work and does not throw.

### Include your code

Here's [the repo](https://github.com/voroninp/FailingSQLite) with the solution having issue.

### Include stack traces

```
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__106.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__110.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__64.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__64.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in FailingSQLite\FailingSQLite\Program.cs:line 15
```

Microsoft.Data.Sqlite version: (huh?) it's `Microsoft.EntityFrameworkCore.Sqlite` v7.0.11
Target framework: .NET 7.0
Edition	Windows 11 Pro
Version	22H2
OS build	22621.2215
Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by roji** [comment]
EF does not support using value generators on update - see #6999. If you remove `ValueGeneratedOnAddOrUpdate()` everything should work as expected.

As to why exactly ValueGeneratedOnAddOrUpdate causes EF to not send anything to the database, I'm not sure (/cc @ajcvickers).

**Comment by ajcvickers** [comment]
@roji `ValueGeneratedOnAddOrUpdate` basically means use a computed column. EF does send any value because it is expecting the value to be computed by the database.

**Comment by roji** [comment]
@ajcvickers ah, ok.. I was under the impression that you can still send an explicit value with ValueGeneratedOnAddOrUpdate - overriding the database-generated one - just like you ca send an explicit value when adding when ValueGeneratedOnAdd is configured. Although this doesn't work with computed columns (you can't override), it probably can be made to work with triggers.

**Comment by ajcvickers** [comment]
@roji You can do that, but a) no value was specified in this case, so its irrelevant, and b) you have to change the `BeforeSaveBehavior` since by default we make it `Ignored` so that computed columns work out-of-the-box.

**Comment by roji** [comment]
Thanks, makes sense!

Other than all that, @voroninp I don't think there's anything here beyond #6999?

**Comment by voroninp** [comment]
@roji IMO, naming is slightly confusing. It would be nice if the actor (the side which generates the value: EF or DB) was captured in the name.

**Comment by roji** [comment]
@voroninp I agree the naming isn't perfect, but these are rarely-used APIs and I don't think it would make sense to make people go through the breaking change trouble for renaming them etc.

**Comment by voroninp** [comment]
@roji ok, more details in remarks section maybe?

**Comment by roji** [comment]
We haven't seen enough confusion around this, and as I wrote these are pretty rarely-used APIs...
