### ISSUE TITLE
Guidelines for running ef commands

### ISSUE THREAD

**Issue by miguellira** [dotnet/efcore#3174]
Looks like a recent commit (https://github.com/aspnet/EntityFramework/commit/448170f732116607bf4a464e627988f0874317dd#diff-b8c39a3f7fffa559788354a8e675e20eL99) by @bricelam removed the `--startupProject` argument from ef commands.

Are there any guidelines/best practices for running ef commands in a solution where your `DbContext` is in a project other than your startup project?

An open issue (https://github.com/aspnet/EntityFramework/issues/2256) discusses this topic but it goes into a broader hypothetical in which DbContexts and their Migrations are supplied by a third party assembly.

**Comment by bricelam** [comment]
The `--startupProject` didn't work very well. It will come back when #2679 and #2294 are done.

**Comment by miguellira** [comment]
Thanks @bricelam. Subscribed to the referenced issues.
