### ISSUE TITLE
Data inconsistency while loading entities based on new changed prop before SaveChangesInterceptor.SavingChangesAsync

### ISSUE THREAD

**Issue by SasanArham** [dotnet/efcore#31741]
## File a bug

Here is the work flow : 

Change "Deleted" property of my entity and call SaveChangesAsync() :

```C#
myEntity.Deleted = true ;
myEntity.AddDomainEvent(new DeletedDomainEvent(myEntity.ID)) ;
await  myRepo.SaveChangesAsync() ;
```
In my custom "SaveChangesInterceptor"  I publish my events like this : 

```C#
 public override async ValueTask<InterceptionResult<int>> SavingChangesAsync(DbContextEventData eventData, InterceptionResult<int> result, CancellationToken cancellationToken = default)
        {
            await DispatchInstantConsistencyDomainEvents(eventData.Context);

            return await base.SavingChangesAsync(eventData, result, cancellationToken);
        }
```

In one part of corresponding handler I try to load same deleted entity within this method : 

```C#
 public virtual async Task<T> SelectDeletedByIDAsync(int ID)
        {
            try
            {
                var model = await DbSet.FirstAsync(c => c.ID == ID && c.Deleted);
                return model;
            }
            catch (Exception ex)
            {
                throw new CrudException(ErrorMessage.loadError, ex);
            }
        }
```

The strange behavior is that

```C#
await DbSet.FirstAsync(c => c.ID == ID && c.Deleted);
```

throws this exception 

```
Sequence contains no elements.
```

but if I remove "deleted" condition and load it just by ID and then assign its "Deleted" prop to a bool variable its true !

Target framework: EF 7.0.5

**Comment by ajcvickers** [comment]
@SasanArham When a `DbSet` is used to query the database, then that query is always executed against the database and any predicate are applied against the database, even if the value being used may have changed in the tracked entity instance. So, in this case, the `Deleted` has not yet been updated in the database, and hence no rows are found.

**Comment by SasanArham** [comment]
> So, in this case, the `Deleted` has not yet been updated in the database, and hence no rows are found

As I mentioned in last line of my issue:  But if it's that, why when I remove "Deleted" condition and just load it (for test sake) the "Deleted" property value IS the updated value(false) ?

**Comment by ajcvickers** [comment]
@SasanArham Because the entity instance returned by the query is the one cached by the context. See [Change Tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more information.

**Comment by SasanArham** [comment]
@ajcvickers  So with regard to 
> Because the entity instance returned by the query is the one cached by the context
and your previous answer what I understood is that when it comes to checking conditions  it always get executed against database but when it wants to return the data it uses the cached one ? 
Can't it cause confusion or have misunderstood the process ?

**Comment by ajcvickers** [comment]
> Can't it cause confusion or I have misunderstood the process

Yes, this is confusing. However, there are several good reasons why it is this way, and it's not something that is going to change.
