### ISSUE TITLE
Does EF7 eager load support lift include?

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#3176]
There is a lift foreign key in my model:

```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Topicomb.Forum.Models
{
    public class Topic
    {
        public long Id { get; set; }

        ...

        [ForeignKey("Parent")]
        public long? ParentId { get; set; }

        public virtual Topic Parent { get; set; }
    }
}
```

I want to get parent's parent until it equals to null.

In the EF 6, I have used the lazy load, there was no need to use .Include().ThenInclude(), but I don't know how to make this works by using eager load with EF7.

Is there any methods like .LiftInclude(x => x.Parent) in the latest unstable package?

**Comment by maumar** [comment]
You could try something like this:
var topic = context.Topics.Include(t => t.Parent).Where(t => t.Id == someId).SingleOrDefault();
if (topic!= null && topic.Parent != null)
{
topic = context.Topics.Include(t => t.Parent).Where(t => t.Id == topic.Parent.Id).SingleOrDefault();
}

If there are multiple levels of parents, you can use "while" instead of "if".

**Comment by Kagamine** [comment]
It's so complex. Why not make a support for eager load, or implement the lazy load?

**Comment by maumar** [comment]
You could also do it without use of include, by inspecting the foreign key and querying for entity which I'd is topic.ParentId)

Its all matter of priority. While lazy loading makes your code simpler but doesn't enable new scenarios. (you can do everything using eager loading, although its more difficult) There are still things in EF7 that don't work at all and we would like to implement them first

**Comment by Kagamine** [comment]
:disappointed:
