### ISSUE TITLE
Test: Remove tests packages from NugetPackageVerifier exclusion list

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#3177]
NugetPackageVerifier is an fxcop-like tool for required NuGet package and assembly metadata and for proper code signing that now runs automatically in our build. When it was enabled recently in our branch [tests packages we produce were excluded](https://github.com/aspnet/EntityFramework/pull/3157/files#diff-7923ea359ac2a1c7ec90f580db690e1aR28). 

However per #3016 these packages will soon be published to NuGet, hence the exclusion will no longer apply.

**Comment by divega** [comment]
We should try removing the packages from the exclusion list and fix whatever we need to fix. No need to break the build :smile:

cc @Eilon @ajaybhargavb.

**Comment by ajaybhargavb** [comment]
Updated the PR with this change https://github.com/aspnet/EntityFramework/pull/3157/

**Comment by ajaybhargavb** [comment]
b4edf2eabd05752420f434b490c317e8f27488de
