### ISSUE TITLE
Add SqlCe DataProvider  to EF7

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#318]
sqlserver compact is best .NET compact and lite database and very developers use it and need add to EF7. sqlserver compact better support .NET and very performance.
and very user votes to support in visual studio 2013-14 and work on new version
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4714470-support-sql-server-compact-in-visual-studio-2013
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5794792-sql-server-compact-5

**Comment by ErikEJ** [comment]
@rowanmiller Any news on updated guidance for provider writers? https://github.com/aspnet/EntityFramework/wiki/Writing-an-EF7-Provider

**Comment by rowanmiller** [comment]
@ErikEJ saw you got started, other folks have just been looking at our providers. We'll have more docs once things stabilize but they are changing quite rapidly at the moment.

**Comment by ErikEJ** [comment]
@rowanmiller  @mojtabakaviani Implementation of the EF7 SQLCE provider is underway: https://github.com/ErikEJ/EntityFramework.SqlServerCompact - only major stumbling block so far is the Update (SaveChanges) pipeline, due to SQLCE limitations/features

**Comment by ErikEJ** [comment]
@mojtabakaviani @rowanmiller Feel free to close this now, SQLCE provider fully implemented (RevEng support under consideration)

**Comment by mojtabakaviani** [comment]
I think SQLCE rich to end and must migrate to SQLITE. However, Thanks!

**Comment by ErikEJ** [comment]
@mojtabakaviani Good luck with that!
