### ISSUE TITLE
Stylecop rulesets are being applied on generated EF bundle and build is failing in gitlab pipleine

### ISSUE THREAD

**Issue by vyaskuldeep20** [dotnet/efcore#31804]
Command used : 
RUN dotnet ef migrations bundle --project ${CSPROJ_PATH}.csproj --configuration $BUILD_CONFIG  --startup-project ${CSPROJ_PATH}.csproj -r alpine.3.7-x64 --self-contained -o /build/migrationbundle --verbose

Output logs in gitlab ci-cd : 

```
 Restored /build/ConfigurationService/ConfigurationService.csproj (in 1.97 sec).
  Restored /tmp/ngvprek2.jwh/migrationbundle.csproj (in 1.96 sec).
/usr/share/dotnet/sdk/6.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1114,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/build/ConfigurationService/ConfigurationService.csproj]
  ConfigurationService -> /build/ConfigurationService/bin/Debug/net6.0/ConfigurationService.dll
/tmp/ngvprek2.jwh/Program.cs(1,1): error SA1633: The file header is missing or not located at the top of the file. [/tmp/ngvprek2.jwh/migrationbundle.csproj]
CSC : error SA0001: XML comment analysis is disabled due to project configuration [/tmp/ngvprek2.jwh/migrationbundle.csproj]
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Build failed. Use --verbose to see errors.
The command '/bin/sh -c dotnet ef migrations bundle --project ${CSPROJ_PATH}.csproj --configuration $BUILD_CONFIG  --startup-project ${CSPROJ_PATH}.csproj -r alpine.3.7-x64 --self-contained -o /build/migrationbundle --verbose' returned a non-zero code: 1
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### Include provider and version information
EF Core version: 6.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows/Linux
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by vyaskuldeep20** [comment]
I tried using this version as well : v8.0.0-preview.2.23128.3 which has the fix of issue reported earlier .
https://github.com/dotnet/efcore/issues/30074

But still it doesnot fix the problem

**Comment by vyaskuldeep20** [comment]
This is my csproj package info

![image](https://github.com/dotnet/efcore/assets/68455719/7ff5d0a6-e105-4d3c-a5c4-a67a46df781f)

**Comment by bricelam** [comment]
> I tried using this version as well : v8.0.0-preview.2.23128.3 which has the fix of issue reported earlier .
> https://github.com/dotnet/efcore/issues/30074
>
> But still it doesnot fix the problem

Did you update the dotnet-ef tool in addition to your project references?

```cmd
dotnet tool update -g dotnet-ef --version 8.0.0-*
```

**Comment by sharwell** [comment]
It appears that the tool that creates the **Program.cs** file (where the warning is reported) is failing to include this line at the top of the file:

```
// <auto-generated/>
```

**Comment by bricelam** [comment]
@sharwell Yes, that's the bug we fixed in 8.0. We now add that line to the generated Program.cs.

**Comment by vyaskuldeep20** [comment]
Is there any way you could backport this fix to net6.
Because net8 is not released yet and we are blocked due to this.

**Comment by hades200082** [comment]
These days you can add the following to your .editorconfig file (adjust the file path in the square brackets as needed)

```ini
# Do not apply code styles to generated migration files
[**/Migrations/*.cs]
generated_code = true
```
