### ISSUE TITLE
Change Tracker doesn't register updates in inner complex properties

### ISSUE THREAD

**Issue by PeopleDispose** [dotnet/efcore#31818]
I have an entity with non-primitive field (not 'owned' but JSON-serializable with corresponding comparer, I believe this is important). In case if this property changes state, tracker doesn't register it as modified.

Existing test was enhanced to show this behavior:

```C#
[ConditionalFact]
public void DetectChanges_is_called_for_all_tracked_entities_and_returns_true_if_any_changes_detected()
{
    var contextServices = InMemoryTestHelpers.Instance.CreateContextServices(BuildModel());

    var stateManager = contextServices.GetRequiredService<IStateManager>();

    var entry1 = stateManager.GetOrCreateEntry(
        new Category2
        {
            Id = 77,
            Name = "Beverages",
            PrincipalId = 777,
            Item = new()
            {
                A = "One",
                B = 1,
            }
        });
    var entry2 = stateManager.GetOrCreateEntry(
        new Category2
        {
            Id = 78,
            Name = "Foods",
            PrincipalId = 778
        });
    var entry3 = stateManager.GetOrCreateEntry(
        new Category2
        {
            Id = 79,
            Name = "Stuff",
            PrincipalId = 779
        });

    entry1.SetEntityState(EntityState.Unchanged);
    entry2.SetEntityState(EntityState.Unchanged);
    entry3.SetEntityState(EntityState.Unchanged);

    var changeDetector = contextServices.GetRequiredService<IChangeDetector>();

    ((Category2)entry1.Entity).Item.Update();
    ((Category)entry2.Entity).Name = "Doofs";
    ((Category)entry3.Entity).Name = "Ffuts";

    changeDetector.DetectChanges(stateManager);

    Assert.Equal(EntityState.Modified, entry1.EntityState);
    Assert.Equal(EntityState.Modified, entry2.EntityState);
    Assert.Equal(EntityState.Modified, entry3.EntityState);
}

private class Category
{
    public int Id { get; set; }
    public int? PrincipalId { get; set; }
    public string Name { get; set; }
}

private class Category2 : Category
{
    public CategoryItem Item { get; set; }
}

private class CategoryItem
{
    public string A { get; set; }
    public int B { get; set; }

    public void Update()
    {
        A = B.ToString();
        B++;
    }
}
```

And it fails with resolution:
```
Assert.Equal() Failure
Expected: Modified
Actual:   Unchanged
```

At least I've found two workarounds for this behavior.
1. Enforce entry's property `IsModified` flag to be `true` - let's say this is a case of emergency
2. Re-assign entity-level property in case something updated. In my test it will be like:
`((Category2)entry1.Entity).Item = new {}`
but this is almost always semantically incorrect and could break some design principles. My domain case makes me declare this property as mutable, so I would also avoid this without necessity.

**EF Core version:**
Database provider: any, but my project references `npgsql`
Target framework: .NET 7.0
Operating system: any
IDE: any

**Sample project**
[EfCoreChangeTrackerRepro.zip](https://github.com/dotnet/efcore/files/12671744/EfCoreChangeTrackerRepro.zip)

**Comment by roji** [comment]
Can you please post a runnable code sample? The above is missing e.g. the model configuration, which should be important. It's always best to simply submit a minimal console program that can be executed.

**Comment by PeopleDispose** [comment]
> Can you please post a runnable code sample? The above is missing e.g. the model configuration, which should be important. It's always best to simply submit a minimal console program that can be executed.

Your tests are quite big :) But I've tried to copy-paste just everything needed for it.
Updated main post, it should be zip file included. Pls let me know if it works as locally I could run it without errors.

**Comment by ajcvickers** [comment]
@PeopleDispose `CategoryItem` is a mutable reference type, but you don't define a mechanism to snapshot the values in your `JsonValueComparer` implementation.

**Comment by PeopleDispose** [comment]
> @PeopleDispose `CategoryItem` is a mutable reference type, but you don't define a mechanism to snapshot the values in your `JsonValueComparer` implementation.

Indeed this helped me. Thx, I'll close this issue.
