### ISSUE TITLE
Native AOT - Microsoft.Data.SQLite - Statically Link / self contained EXE

### ISSUE THREAD

**Issue by JOULTICOA** [dotnet/efcore#31829]
Hello,

It is intended behavior that e_sqlite3.dll is required when publishing as Native AOT?

Is there some way to statically link Microsoft.Data.SQLite so that I can have a self contained EXE?

Self contained EXE is very important for portable app development

**Comment by bricelam** [comment]
It's not statically linked, but have you tried adding this option to your csproj?

```xml
<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
```

**Comment by PaddiM8** [comment]
`IncludeNativeLibrariesForSelfExtract` doesn't seem to work with with native AOT
