### ISSUE TITLE
DbContextServices should not call dispose on parent service provider

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3183]
Recent changes (https://github.com/aspnet/DependencyInjection/commit/bbb9acf101d4f9b3b818834c60572f67ec16ac63) to DependencyInjection means DbContextServices.Dispose() cleans out a parent service provider. On a 2nd call to the service provider, some services have been removed, e.g. the model.

``` c#
    using (var db = serviceProvider.GetService<MusicStoreContext>())
    {
        // do something
    }

    using (var db = serviceProvider.GetService<MusicStoreContext>())
    {
       // serviceProvider has been cleaned out ==> all sorts of fun runtime errors.
```

**Comment by divega** [comment]
Looks like what #1113 was supposed to fix (dispose the scope instead of the service provider) just became more urgent.@natemcmaster feel free to poach if you can get to it now.

Cc @mikary

**Comment by Tratcher** [comment]
@natemcmaster @divega this is blocking the CI, can it get taken care of today?

**Comment by natemcmaster** [comment]
@Tratcher It's being worked on.

**Comment by natemcmaster** [comment]
Update: this bug is unverified. I found it is not *directly* related to what was blocking CI. Temporarily disabling the broken tests:  aa6a40e56ce4a0450346c3b64797cbd38d3c53bd.

**Comment by natemcmaster** [comment]
Closing as a dup of #1113
