### ISSUE TITLE
EntityState is set to Unchanged instead of Modified when assigning a new complex nested property - CosmosDB

### ISSUE THREAD

**Issue by georgechond94** [dotnet/efcore#31846]
## Ask a question

Hi, I have the following entity:

```
public class Entity {
public Complex Complex { get; set; }
}

public class Complex {
// props
}
```

and configured as: 

```
public class EntityConfiguration : IEntityTypeConfiguration<Entity>
{
        public void Configure(EntityTypeBuilder<Entity> builder)
        {
             builder.OwnsOne(ap => ap.Complex);
        }
}
```

I have the following piece of code:

```
var entity = context.First(// fetch from the database)
var entity.Complex = new Complex { ... };
await context.SaveChangesAsync();
```

Before saving, in the change tracker, I see the `EntityState` of the above Entity object is set to `EntityState.Unchanged` while I was expecting it to be set to `EntityState.Modified`. (I am using a `SaveChangesInterceptor` to check)
The above change is stored in the database as expected.

Is this by design or I am missing something? 

I could check the `Entry.Members.Any(m => m.IsModified == true)` (as this is correctly set to true) but that sounds like a workaround.

Thanks!

---

EF Core version: 7.0.1
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 7.0

**Comment by ajcvickers** [comment]
> After saving, in the change tracker, I see the EntityState of the above Entity object is set to EntityState.Unchanged while I was expecting it to be set to EntityState.Modified.

After saving, the values in the database match the values in the entity instance, so the expected state is `Unchanged`.

**Comment by georgechond94** [comment]
@ajcvickers thanks for the reply, sorry I meant while saving. 
I am using the SavingChangesAsync override.

I am updating the original question.

**Comment by ajcvickers** [comment]
@georgechond94 Are you calling `context.ChangeTracker.DetectChanges()` before looking at the state? EF Core does this automatically during `SaveChanges` but if you want to inspect state before that, then you need to make sure EF has detected any changes made to the object graph.

**Comment by georgechond94** [comment]
@ajcvickers That doesn't change the behavior unfortunately.
Some more context on my use case:

I am trying to have some auditing in place (CreatedBy, CreatedOn, etc), so I created a `SaveChangesInterceptor` which sets these properties on `SavingChanges`/`SavingChangesAsync`. Here is my method which sets these properties:
```
  private void SetAuditableProperties(DbContextEventData eventData)
  {
    var context = eventData.Context;

    if (context is not null)
    {
      var entries = context.ChangeTracker.Entries<IAuditableEntity>();
      foreach (var entry in entries)
      {
        switch (entry.State)
        {
          case EntityState.Modified:
            entry.Property(e => e.ModifiedOn).CurrentValue = DateTimeOffset.UtcNow;
            break;
          case EntityState.Added:
            entry.Property(e => e.CreatedOn).CurrentValue = DateTimeOffset.UtcNow;
            break;
        }
      }
    }
  }
```
(The `Entity` class above implements the `IAuditableEntity` interface)


Here comes the weird part:
If a primitive property changes, that works **great**. Although, if a complex property changes (like the Complex in my case above) the entry.State stays `Unchanged` so the `ModifiedOn` is not set.

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by georgechond94** [comment]
Hi @ajcvickers, sorry for the late response.

Here is the repro: https://github.com/georgechond94/efcore-change-tracker-complex-prop

And that's the output I am seeing:
![image](https://github.com/dotnet/efcore/assets/6044597/bb17b2fe-c482-45cf-afdc-54aedb1180a7)

**Comment by ajcvickers** [comment]
@georgechond94 This is because the owned entity instance has been changed, but the owner is still Unchanged:

```
Complex (Shared) {EntityId: 60efcd55-c2bf-46d2-be45-e7bbe57a662d} Added
  EntityId: '60efcd55-c2bf-46d2-be45-e7bbe57a662d' PK FK
  Value: 'Updated'
  __jObject: <null> Unknown
Complex (Shared) {EntityId: 60efcd55-c2bf-46d2-be45-e7bbe57a662d} Deleted
  EntityId: '60efcd55-c2bf-46d2-be45-e7bbe57a662d' PK FK
  Value: <null>
  __jObject: <null>
Entity {Id: 60efcd55-c2bf-46d2-be45-e7bbe57a662d} Unchanged
  Id: '60efcd55-c2bf-46d2-be45-e7bbe57a662d' PK
  Discriminator: 'Entity'
  Value: 'Updated'
  __id: 'Entity|60efcd55-c2bf-46d2-be45-e7bbe57a662d' AK
  __jObject: '{
  "Id": "60efcd55-c2bf-46d2-be45-e7bbe57a662d",
  "Discr...'
  Complex: {EntityId: 60efcd55-c2bf-46d2-be45-e7bbe57a662d}
```

**Comment by georgechond94** [comment]
@ajcvickers thanks for your reply. Hmm, I was expecting the `Entity` (owner) object to be set to `Modified` and the `Complex` (owned) entity to be set to `Added` in this case. 
Having `Modified` as `Complex`'s state sounds like a property of the `Complex` entity was changed.

**Comment by ajcvickers** [comment]
@georgechond94 The Complex object's state is not Modified. It's being tracked as deleted and re-added--see the debug view I posted above.

**Comment by georgechond94** [comment]
Thanks and sorry for the late response @ajcvickers 

Ah yeah sorry I misread the debug view you posted.

Curious, isn't `Modified` the "right" state for the owner entity in this case?
What's the best way to check that the owned entity changed? Iterate over `EntityEntry.Navigations.IsModified` and check for `true`? That sounds a bit expensive 😟 

I only want to implement the `IAuditableEntity` interface (and update the `ModifiedOn` property) in the owner entity

Thanks!

**Comment by ajcvickers** [comment]
@georgechond94 It's not modified because the owner entity itself is not modified. Only the owned entity has changed. To audit this, you will need to look for owned entities in the Added, Deleted, or Modified states.
