### ISSUE TITLE
How can I map a class inheriting from UserControl?

### ISSUE THREAD

**Issue by asfarley** [dotnet/efcore#31842]
## Ask a question

I have a project with a bunch of models which are being mapped as I expect by EF Core. However, when I try to map two models, I get an error creating the initial migration:

```
No suitable constructor was found for entity type 'GroupStyleSelector'. The following constructors had parameters that could not be bound to properties of the entity type: 
    Cannot bind 'object', 'method' in 'GroupStyleSelector(object object, IntPtr method)'
Note that only mapped properties can be bound to constructor parameters. Navigations to related entities, including references to owned types, cannot be bound.
```

The classes who cause this error both inherit from UserControl. My project doesn't have any occurrences of the term GroupStyleSelector at all, so this must be from EF Core trying to map the base class.

I searched for advice on how to tell EF Core to ignore a base class, and found a variety of suggestions but none worked. I tried adding the following to OnModelCreating() in my DatabaseManager:

```
            modelBuilder.Entity<VSDrawingWindow>().HasBaseType((Type)null);
            modelBuilder.Entity<LayoutElement>().HasBaseType((Type)null);
```

However, I still get the same error about GroupStyleSelector. I also tried telling modelBuilder to ignore the UserControl class:

`modelBuilder.Ignore<UserControl>();`

But the result was still the same.

Provider: SQlite
Target Framework: .NET 6.0
Visual Studio 2022 17.7.4
Microsoft.EntityFrameworkCore (7.0.11)
Microsoft.EntityFrameworkCore.Design (7.0.11)
Microsoft.EntityFrameworkCore.Sqlite (7.0.11)
Microsoft.EntityFrameworkCore.Tools (7.0.11)

**Comment by ajcvickers** [comment]
@asfarley It isn't possible to "ignore" a base class like this--the properties are inherited, so they can't just be ignored. You'll have to either ignore or map individual members as appropriate.
