### ISSUE TITLE
UTF8 case insensitive like operator in sqlite

### ISSUE THREAD

**Issue by jakubmaguza** [dotnet/efcore#31843]
This is followup to #11414

While collations work with equals operator, it does not work with like operator.

I was doing my tests using the same snippet listed in docs [here](https://github.com/dotnet/docs/blob/main/samples/snippets/standard/data/sqlite/CollationSample/Program.cs).

The only difference was to change ` WHERE value = 'λ' COLLATE NOCASE` to ` WHERE value like 'λ' COLLATE NOCASE`

This query returns 1 instead of 2.
Is there any way to make like works with in this scenario?

**Comment by roji** [comment]
Have you seen [this section](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/collation#like-operator) of the SQLite docs?

**Comment by roji** [comment]
See the note/link below for user-defined functions?

**Comment by jakubmaguza** [comment]
Yes, I did in fact.
Here is sample code:

```c#
public class CustomFunctionsInterceptor : DbConnectionInterceptor
{
    public override void ConnectionOpened(DbConnection connection, ConnectionEndEventData eventData)
    {
        var conn = (SqliteConnection)connection;
        conn.CreateFunction("like", (string pattern, string input) => input.Contains(pattern.Replace("%", ""), StringComparison.InvariantCultureIgnoreCase));
    }
    public override Task ConnectionOpenedAsync(DbConnection connection, ConnectionEndEventData eventData, CancellationToken cancellationToken = default)
    {
        var conn = (SqliteConnection)connection;
        conn.CreateFunction("like", (string pattern, string input) => input.Contains(pattern.Replace("%", ""), StringComparison.InvariantCultureIgnoreCase));
        return Task.CompletedTask;
    }
}
```

It's supper simplified, without wildcards etc, but it's working.

The problem is that performance is very bad. In my dataset we are talking about 10 sec difference (from 2s to 12s).

Changing implementation to `input.ToUpper().Contains(pattern.ToUpper().Replace("%", ""));` reduces this time to 7s.

I've been wondering if there is any other way I can try to make it closer to native sqlite implementation.

**Comment by bricelam** [comment]
If you want to compile SQLite yourself, you can enable the SQLITE_ENABLE_ICU compile-time option to get native Unicode support.

If you want to stick with a .NET implementation, I wonder if most of the time is spent converting between UTF-8 (SQLite's text format) and UTF-16 (.NET's string format). If you change your parameters to byte[], are there ways of performing the operation directly on the UTF-8 bytes?

**Comment by jakubmaguza** [comment]
I don't think I know how to make that change. i tried with `conn.CreateFunction("like", (byte[] pattern, byte[] input) => true);` but it's always returning 0 results. Probably because I'm using `EF.Functions.Like` helper method, which accepts strings.

For now, I ended up creating `UPPERCASE` versions of columns I need to search. It's not perfect, because I need to modify DB whenever I want to add new search field.

However I'm still interested in solution if you don't mind. Are there any plans for creating Microsoft nuget package with ICU? From my point of view it feels like it should be default choice, but I belive you never did that, because there are other drawbacks I'm not aware of.

I was trying to do some profiling using VS2022 tools, but I couldn't get deeper than:

|Function Name|Total \[unit, %\]|Self \[unit, %\]|Call Count|Module|
|-|-|-|-|-|
|\| - Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync\(IQueryable\`1, CancellationToken\)|20,99s \(87,74%\)|20,99s \(87,74%\)|4|microsoft.entityframeworkcore|

**Comment by bricelam** [comment]
> Are there any plans for creating Microsoft nuget package with ICU? From my point of view it feels like it should be default choice, but I belive you never did that, because there are other drawbacks I'm not aware of.

We don't actually provide any NuGet packages containing SQLite, they come from the [SQLitePCLRaw](https://github.com/ericsink/SQLitePCL.raw) project. You could request one there. I believe it's not on by default in the SQLite project for two reasons. First, it would be a breaking change to turn it on after so many years of having it off by default (this is the same reason foreign keys aren't enforced by default). Second, I think it adds significant size to the application, and they want to keep SQLite small.

**Comment by jakubmaguza** [comment]
Thank you Brice, I believe we reach maximum from EF point of view, so I will close this issue and will probably try with ICU.
