### ISSUE TITLE
Intentional breaking change in v8?

### ISSUE THREAD

**Issue by bkoelman** [dotnet/efcore#31855]
## Ask a question

After updating from EF Core 6/7 to v8-rc1, a few tests started failing. I traced it down to a breaking change in the signature of `RuntimeTypeBase.AddProperty`. In earlier versions, the third parameter was of type `PropertyInfo?` (see [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.runtimeentitytype.addproperty?view=efcore-7.0)). But in v8-rc1, it has moved to the fourth parameter (see [here](https://github.com/dotnet/efcore/blob/03b94351e0f75de65f9e079ad4e347542a0e1a09/src/EFCore/Metadata/RuntimeTypeBase.cs#L166-L170)). The new third parameter is `object? sentinel = null`.

### Include your code
The following snippet shows our original code:
```c#
private void SetEntityProperties(RuntimeEntityType entityType, List<PropertyInfo> properties)
{
    foreach (PropertyInfo property in properties)
    {
        entityType.AddProperty(property.Name, property.PropertyType, property);
    }
}
```
Running this on v8-rc1 passes the `PropertyInfo` to the `sentinel` field. Because it is typed as `object?`, no compiler error/warning occurs. The effect is that everything becomes a shadow property, causing unobvious downstream failures.

To work with v8-rc1, the code needs to be changed as below to address the signature change:
```c#
private void SetEntityProperties(RuntimeEntityType entityType, List<PropertyInfo> properties)
{
    foreach (PropertyInfo property in properties)
    {
        entityType.AddProperty(property.Name, property.PropertyType, propertyInfo: property);
    }
}
```

Because this is a public type and the breaking change is hard to spot, it may not be intentional. We'll need to use `#if`/`#else` conditionals to make it work in multi-targeted projects. Always passing `propertyInfo: property` fails our code style checks because the parameter name is redundant on EF Core 6/7.

**Comment by ajcvickers** [comment]
@AndriySvyryd Should I move `sentinel` to the end?

**Comment by AndriySvyryd** [comment]
Sounds good

**Comment by bkoelman** [comment]
Thanks!

The same potential issue exists at https://github.com/dotnet/efcore/blob/release/8.0/src/EFCore/Metadata/RuntimeProperty.cs#L45. We don't depend on it, just thought I'd point it out so you're aware.

**Comment by ajcvickers** [comment]
@bkoelman Curious how you are using the RuntimeX... types explicitly? We very nearly made them all internal.

**Comment by bkoelman** [comment]
No worries, we don't. I just scanned the sources for additional occurences of `object? sentinel` parameters. If it's not exposed, probably doesn't need changing.

**Comment by ajcvickers** [comment]
@bkoelman So why are you using `RuntimeTypeBase.AddProperty`?

**Comment by bkoelman** [comment]
It's part of [JsonApiDotNetCore](https://www.jsonapi.net), whose purpose is to generate a REST API from EF Core entity classes with minimal boilerplate code. It is conceptually similar to OData and GraphQL, but implements [JSON:API](https://jsonapi.org/). Consumers annotate their entities with our API-specific attributes to control behavior, such as constraints on what to expose. We strive to leverage the existing information from the EF Core model. Aside from that, we have our own app-static model (called `ResourceGraph`) with supplemental information (constructed from our own attributes usage) which we need to process API requests.

When processing a request, the code that produces LINQ queries (named `QueryableBuilder`) takes as inputs:
- The EF Core `IModel` and the `ResourceGraph`
- A data structure that encapsulates information for the current request (called `QueryLayer`), such as filters, paging, sorting, includes, and selecting subsets of entity properties

All good, so far. Now to answer your question, let me explain a bit of history. We've always provided interfaces to support non-relational data sources, but doing so requires a lot of work (basically implement all data access yourself). A community member discovered that MongoDB comes with a LINQ provider that's able to consume the queries we produce. There are limitations, but it's pretty easy to plug that in. Because `QueryableBuilder` depends on `IModel`, our MongoDB version provides a minimal implementation to feed in the required info. From time to time, people ask how to use our project with in-memory data in the form of `IList<>`s instead of tables. The queries we produce are too complex for the EF Core InMemory provider. So to accommodate that, we apply the same trick as for MongoDB: provide a custom implementation of `IModel`, feed that into `QueryableBuilder`, then compile the resulting `Expression` and execute it against the in-memory data source. In this case, the custom `IModel` implementation is populated from what's in our `ResourceGraph`. And that's where we call `RuntimeTypeBase.AddProperty`.

Looking back, `QueryableBuilder` was never designed to be a general-purpose LINQ builder, but it has kinda grown beyond EF Core. Perhaps we'll abstract away the `IModel` dependency in the future, though that would be a breaking change.
