### ISSUE TITLE
Ignore specified query filters

### ISSUE THREAD

**Issue by amyboose** [dotnet/efcore#31869]
### What problem are you trying to solve? 
I want to ignore some global query filters and use other query filters

### Describe the solution you'd like 

I would like to have generic version of IgnoreQueryFilters:
```C#
List<Post> result = context.Set<Blog>()
    .IgnoreQueryFilters<Post>()
    .ToList();
```

It also usefull to have global ignore filter to prevent [issue](https://go.microsoft.com/fwlink/?linkid=2131316). For example in some cases I want to load ignore Deleted flag for Blog even when it has global QueryFilter
I see solution like this:
```C#
modelBuilder.Entity<Post>(builder =>
{
    builder
        .IgnoreQueryFilter(x => x.Blog.Deleted);
});
```

**Comment by roji** [comment]
Duplicate of #17347
