### ISSUE TITLE
Adding items to child collections when parent has string PK column fails silently

### ISSUE THREAD

**Issue by vyruz1986** [dotnet/efcore#31865]
I ran into a problem when converting one of my entities from a `Guid` type `Id` property/column to a `string` type.
This entity is a DDD aggregate root and has a `List` of child records.

When the entity used `Guid` as its PK, I could just do `parent.Children.Add(<child>)`, then call `SaveChanges()` and the new child would be inserted into the table, this does not work anymore after switching the parent to a `string` type PK.

I've created a minimal example repo [here](https://github.com/vyruz1986/EFCoreStringPKAndChildCollection), it features a unit test which spins up a SQL server container, creates the initial `ParentWithStringPK` record (with 1 child in its `Children` collection), then retrieves that record from the the DB, adds another child record to its `Children` collection, saves changes, then retrieves the `ParentWithStringPK` record again and verifies all 2 child entities exist in the parents children collection.

There is also a 2nd unit test which does the same, but then with a `ParentWithGuidPK` type which has a `Guid` type `Id` column. This test succeeds.

Important bits:

## Entities:

```csharp
public class ParentWithStringPK
{
    public string Id { get; set; }
    public List<Child> Children { get; set; }
}

public record Child(Guid id);
```

## DbContext

```csharp
public class TestContext : DbContext
{
    public TestContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<ParentWithStringPK> ParentsWithString { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ParentWithStringPK>()
            .OwnsMany(e => e.Children);
    }
}
```

## Failling code

```csharp
var parentId = Guid.NewGuid().ToString();
var generatedParent = new ParentWithStringPK
{
    Id = parentId,
    Children = new() { new(Guid.NewGuid()) }
};
var childToAdd = new Child(Guid.NewGuid());

using (var context = new TestContext(ContextOptions))
{
    context.ParentsWithString.Add(generatedParent);
    await context.SaveChangesAsync();
}

// When
using (var context = new TestContext(ContextOptions))
{
    var parent = await context.ParentsWithString.SingleAsync(p => p.Id == parentId);
    parent.Children.Add(childToAdd);
    await context.SaveChangesAsync();
}

// Then
using (var context = new TestContext(ContextOptions))
{
    var parent = await context.ParentsWithString.SingleAsync(p => p.Id == parentId);
    parent.Children.Should().Contain(childToAdd);
}
```

EF Core version: 7.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0
Operating system: Windows 11 22H2
IDE: VSCode 1.82.2

**Comment by ajcvickers** [comment]
@vyruz1986 GUID keys are auto-generated by default. EF therefore uses the absence/presence of a GUID value to determine whether the entity exists in the database or not. However, in your case, you are setting GUIDs explicitly, which defeats this. So, either:
- Stop explicitly specifying GUIDs
- Or mark the property GUID as not-generated. For example, `.Entity<ParentWithStringPK>().OwnsMany(e => e.Children).Property(e => e.id).ValueGeneratedNever()`

**Comment by vyruz1986** [comment]
@ajcvickers that was indeed the cause of my problem. How did I miss that ¯\_(ツ)_/¯
Thanks!
