### ISSUE TITLE
Get all is returning entities which has delete state 

### ISSUE THREAD

**Issue by komdil** [dotnet/efcore#31875]
I am getting all entities (3 items). Removing one of them, but not saving. Then getting all again. It is returning me a deleted entity however state of the entity is deleted. Is it something expected? Why it is not returning 2 items? Also, is there any documentation about this?

```
using (MyDbContext context = new MyDbContext())
{
    var userAsCustomerAndAdmin = context.Set<User>().ToList();//3 items
    context.Set<User>().Remove(userAsCustomerAndAdmin.First());

    var fromTracker = context.ChangeTracker.Entries<User>().ToList();//The state of first item is deleted

    var userAsCustomerAndAdmin2 = context.Set<User>().ToList();//3 items
}
```
**Scenario:** My DbContext life time is longer. I am deleting some entities without saving the context. After that I have some logic that will use GetAll and the problem is this logic is doing something with entities that has been deleted from the context.

EF Core version: 7.0.1

**Comment by ajcvickers** [comment]
@komdil Queries are always executed against the database, and hence the deleted entity is returned in the results because it still exists in the database. See [Change Tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more information.
