### ISSUE TITLE
Enforcing usage of FluentAPI instead of attributes

### ISSUE THREAD

**Issue by sander1095** [dotnet/efcore#31889]
I work in a company where people use EF Core incorrectly. They don't really know what happens under the hood when they configure their properties. They mostly use attributes even though our policy is to use the fluent API because this allows us to really configure EF Core in the way we need it.

Attributes on domain models mix data and domain definitions. Furthermore, they install EF Core specific packages in domain projects where they do not belong.

I would like to be able to configure EF Core to throw, or in other ways, disallow the use of attributes, so one can only use the fluent API + the default conventions. This will make it easier to use EF Core correctly, following company policies, in multiple projects.

**Alternatives**
I could probably use a project like [NetArchTest](https://github.com/BenMorris/NetArchTest) to write an architectural unit test that checks specific namespace/type usage in domain projects and throw an error when attribute namespaces are detected.

However, I would prefer to have this built-in to EF Core. EF Core already allows you to configure warnings and errors, so why not allow us to configure the way we configure our models and constrain us to the fluent API?

**Comment by KennethHoff** [comment]
I don't see the dotnet team doing this. However, it's definitely a good idea. You could create your own analyzer for it. You got me interested as well actually

**Comment by roji** [comment]
@sander1095 EF's support for the attributes is implemented as pluggable "conventions"; if you really want to, you should be able to remove those conventions, making EF ignore the attributes. Some information is available [on this doc page](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#conventions), but you'll have to figure out which conventions need removal by looking at EF's "convention set" in the source code.

However, I'd generally advise against this approach; if your programmers as using EF APIs incorrectly, they really should be educated to do it properly via code reviews etc. (remember that the EF's Fluent APIs can also be used incorrectly, like any other API). Another possible approach could be to have an analyzer which detects usage of the unwanted attributes and raises a warning/error etc.

In any case, we'll discuss this within the team, but I'm skeptical we'd build this option into EF itself.

**Comment by sander1095** [comment]
Hi Roji! 

Thanks for your reply. I also agree that code reviews should be used and understand the downsides of the approach I suggest. However, there are lots of companies where code reviews aren't a lot more than a press of the approve button, or where there simply isn't enough knowledge to catch some mistakes.

I'm grateful for your link to the custom conventions page. I didn't know that feature existed. I'm pretty sure I could use `IModelFinalizingConvention` as a starting point, though I do not know if it is possible to find out if a model is built with EF Core attibutes by using only EF Core features (like the metadata etc ..)
 Does EF Core expose if a property was configured using Fluent API or attributes? My guess is no.

Otherwise I'd need to use reflection or an analyzer, which would also be OK.

If you're willing to talk about this topic with the team, perhaps pivot it towards "add a convention that discourages mixed usage of fluent api and attributes".  This is my opinion based on my previous arguments. And even if the team decides to not add this, I would learn more thanks to your reasoning and could built it myself using the tips you gave me today! I might write a blog post about it someday!

Of course,

**Comment by roji** [comment]
> I'm pretty sure I could use IModelFinalizingConvention as a starting point, though I do not know if it is possible to find out if a model is built with EF Core attibutes by using only EF Core features (like the metadata etc ..)

That wouldn't be the right approach: the simplest would be to just remove the conventions which detect the attributes; see the conventions ending with AttributeConvention in [RelationalConventionSetBuilder.cs](https://github.com/dotnet/efcore/blob/release/8.0/src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs#L57) (but also in ConventionSetBuilder.cs).

**Comment by ajcvickers** [comment]
Note from triage: this is not something we plan to implement. However, it should be relatively easy to either remove or replace the model building conventions for attributes, depending on whether you want the attributes to be ignored or to throw.
