### ISSUE TITLE
Concurrency Detector loses lock when multiple contexts are used in a thread.

### ISSUE THREAD

**Issue by poymanovm** [dotnet/efcore#31890]
## Concurrency Detector loses lock when multiple contexts are used in a thread.

I have a caching layer that loads an entity in a separate context. Subsequently, the entity is detached from this separate context and attached back to the original context. Simplified, this can be represented like this:
```c#
    private static Customer GetOrderCustomerFromCahce(int orderId, Context originalCtx)
    {
       // init "cache"
        var context = new Context();
        var orders = context.Orders.ToArray();
        var order = orders.First(o => o.OrderId == orderId);


        context.Entry(order).State = EntityState.Detached;
        context.Dispose();

        var orderCopy = new Order(originalCtx.GetService<ILazyLoader>())
        {
            OrderId = order.OrderId,
            OrderDate = order.OrderDate,
            CustomerId = order.CustomerId
        };

        var entity = originalCtx.Attach(orderCopy);

        entity.State = EntityState.Unchanged;

        return orderCopy.Customer;
    }
``` 
And the code that uses this cache in a request within the original context
```c#
context.Orders.Select(o => new { Date = o.OrderDate, Name = GetOrderCustomerFromCahce(o.OrderId, context) }
``` 
Аnd as a result, I get an exception
```
InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
``` 

The issue occurs because the ConcurrencyDetector tracks lock acquisition using a static AsyncLocal<bool> variable. This variable is shared between contexts on a single thread.
https://github.com/dotnet/efcore/blob/ea24bdd61de394dd82972be560db79b3fda050ee/src/EFCore/Infrastructure/Internal/ConcurrencyDetector.cs#L15

Therefore, if we have a request in the second context inside a request in the first context, the inner request clears the lock acquisition mark for the first context.

It can be fixed by changing the AsyncLocal variable type from bool to int and tracking not only the fact of lock acquisition but also the total number of locks held by the thread.

I made a [PR](https://github.com/dotnet/efcore/issues/31890) with these small changes, and it also contains a unit test that fails without my changes, reproducing the described problem.

EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer)
Target framework: NET 6.0

**Comment by ajcvickers** [comment]
Note from triage: It's okay for two queries to interleave (non-concurrently) on a single context instance, it is not okay for a context to execute a query on a context instance while SaveChanges is in progress. Therefore, we should find a way to preserve the exception in that case.

**Comment by roji** [comment]
> It's okay for two queries to interleave (non-concurrently) on a single context instance [..]

Just for context, this is fine for example with SQL Server when MARS is enabled, or with Sqlite.
