### ISSUE TITLE
Upgrade 7.0.10 -> 7.0.11

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#31906]
## Ask a question
Why the downgrade on:
System.Buffers and the install of Compiler unsafe. 
Where in the release notes it states it should contain only updates to dependencies?

![Uploading image.png…]()

**Comment by ajcvickers** [comment]
@mmitche The assertion from the customer is that dependencies of EF Core have been downgraded between release 7.0.10 and 7.0.11. Is this expected?

**Comment by qsdfplkj** [comment]
I think it's not a downgrade but a remove (the thing that triggered me was the System.Runtime.CompilerServices.Unsafe package.)
When i use a clean solution:
![image](https://github.com/dotnet/efcore/assets/35060463/e094ffdb-3576-47ca-8bfc-7b3c73276aa0)
