### ISSUE TITLE
Query: unexpected data for queries using (number + fixed_length_string) due to type inference

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#31917]
see: Using_same_parameter_twice_in_query_generates_one_sql_parameter

query:

```cs
        var i = 10;
        return AssertQuery(
            async,
            ss => ss.Set<Customer>().Where(c => i + c.CustomerID + i == "10   ALFKI10   ")
                .Select(c => c.CustomerID));
```

sql: 

```sql
@__i_0='10'

SELECT [c].[CustomerID]
FROM [Customers] AS [c]
WHERE CAST(@__i_0 AS nchar(5)) + [c].[CustomerID] + CAST(@__i_0 AS nchar(5)) = N'10   ALFKI10   '
```

but of course L2O expected result is "10ALFKI10". We would have to override the regular type inference for cases like this. Probably not worth it, as the scenario is very contrived anyway.

**Comment by maumar** [comment]
also see Where_concat_string_int_comparison 1-4

**Comment by ChrisJollyAU** [comment]
@maumar This might not be an issue anymore

Ended up looking at `Using_same_parameter_twice_in_query_generates_one_sql_parameter` in the Sql Server tests as part of updating the Cosmos equivalent as part of another issue.

This test actually works properly

Resultant sql is
```
@__i_0='10'

SELECT [c].[CustomerID]
FROM [Customers] AS [c]
WHERE CAST(@__i_0 AS nvarchar(max)) + [c].[CustomerID] + CAST(@__i_0 AS nvarchar(max)) = N'10ALFKI10'
```

Where_concat_string_int_comparison 1-4 are already enabled and passing with the AssertQuery

**Comment by maumar** [comment]
thanks @ChrisJollyAU ! I submitted the pr for this
