### ISSUE TITLE
Add migrations with different assemblies, using Console App.

### ISSUE THREAD

**Issue by TarasIskiv** [dotnet/efcore#31948]
Hi, I'm trying to add migrations. But I can't, it doesn't work in the same way as it worked for the web API project.
In the current context. I have a console app, where I added db context using Service Collection. Also, I have my context in the separate class library.
Command, that I try to run:

1.  cd **Database project**
2.  dotnet ef --startup-project **Console App project** migrations add Init2

The error: Unable to create an object of type 'FortuneCookieContext'. For the different patterns supported at design time,

My configuration in the console app:
```
var config = GetConfiguration();
        var databaseConnection = config.GetSection("ConnectionStrings")?.GetSection("Database");
        serviceCollection
            .AddLogging()
            .AddDbContext<FortuneCookieContext>(options => options.UseNpgsql(databaseConnection?.Get<string>()));
```

I've installed:
EntityFramework.Tools
EntityFramework.Design
And package for Postgresql in both projects.

Can someone help me with it? Many thanks

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by TarasIskiv** [comment]
Sorry, for the late response. My Context class 
```
public class FortuneCookieContext : DbContext
{
    public FortuneCookieContext(DbContextOptions options) : base(options)
    {
        
    }
    
    public DbSet<UserDetails> UsersDetails { get; set; }
}
```

The context class is located in the FortuneCookie.Database class library.

My Program.cs (Dependency Injection)

```
public static void AddDependencyInjections(this ServiceCollection services)
    {
        var config = GetConfiguration();
        var databaseConnection = config.GetSection("ConnectionStrings")?.GetSection("Database");
       
        services
            .AddLogging()
            .AddDbContext<FortuneCookieContext>(options => options.UseNpgsql(databaseConnection?.Get<string>()));
```
And it is the FortuneCookie.Bot console app project (.net7.0)

To run migrations I used the following steps:
1. cd FortuneCookie.Database
2. dotnet ef --startup-project ../FortuneCookie.Bot/ migrations add Initial

And I always received the error: Unable to create an object of type 'FortuneCookieContext'. For the different patterns supported at design time

**Comment by TarasIskiv** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Added a new comment

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
