### ISSUE TITLE
[QUESTION] Switch entity type for a record in TPH keeping same keys

### ISSUE THREAD

**Issue by CesarD** [dotnet/efcore#31966]
I want to ask if there's any support or workaround for a scenario where I'd like to switch the entity type for a given record while implementing TPH but without losing the ID/keys it already has.

For example, let's say I have:

- `EntityBase`
- `DerivedEntityA` (inherits from `EntityBase`)
- `DerivedEntityB `(inherits from `EntityBase`)

And then I have a record of `DerivedEntityA `with `Id = 1` and at some point I want to transform that record into a `DerivedEntityB`. I could create another record, but I would lose my `ID` and any other entity having a FK referencing it would break, so I'd like to overwrite the same `DerivedEntityA`record with a `DerivedEntityB` instance with the same name.

Has anyone ever presented with such scenario and would there be any solution or workaround to accomplish this?

Thanks.

**Comment by roji** [comment]
You could e.g. use ExecuteUpdate to modify the discriminator of the row - but then it's your responsibility to make sure all the columns are properly filled out. For example, a column that doesn't exist for DerivedEntityA would be null, but if it's required for DerivedEntityB it's your responsibility to make sure it has a value.

**Comment by CesarD** [comment]
That idea crossed my mind, but just wanted to ask anyway in case there was some other mechanism I wouldn't be aware of instead of trying to reinvent the wheel.

Thanks!

**Comment by CesarD** [comment]
> You could e.g. use ExecuteUpdate to modify the discriminator of the row

Excuse me @roji, one more question: is it possible to use `ExecuteUpdate` to pick the `Discriminator` field? Because unless I make it explicitly visible, it seems to me that I'm not able to select it in through the `ExecuteUpdate` API to modify its value. Perhaps you were referring to the `FromSql` methods?

**Comment by roji** [comment]
@CesarD you can use EF.Property to reference shadow properties (EF properties with no mapped CLR property or field). For example, the following changes the discriminator of a Blog with a specific ID:

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

await ctx.Blogs
    .Where(b => b.Id == 5)
    .ExecuteUpdateAsync(s => s.SetProperty(b => EF.Property<string>(b, "Discriminator"), "Blog"));

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<SpecialBlog> SpecialBlogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
}

public class SpecialBlog : Blog
{
    public string SpecialProperty { get; set; }
}
```

**Comment by CesarD** [comment]
Oh, thank you so much for remembering the EF.Property one, I honestly didn't remember it at all. That's a nice one!

Thanks! Cheers!

**Comment by CesarD** [comment]
> @CesarD you can use EF.Property to reference shadow properties (EF properties with no mapped CLR property or field). For example, the following changes the discriminator of a Blog with a specific ID:
> 
> ```cs
> await ctx.Blogs
>     .Where(b => b.Id == 5)
>     .ExecuteUpdateAsync(s => s.SetProperty(b => EF.Property<string>(b, "Discriminator"), "Blog"));
> ```

FWIW: I have been testing this approach, and while it might be useful for shadow properties, it doesn't seem to fit my current scenario because the columns I need to update to keep the record consistent with the new class type it will hold, don't exist in the current type of the record, so some properties that I might try to refer to of the new type, won't exist in the old type and the call to `EF.Property<>()` will throw an `Exception`:

```
Translation of 'EF.Property<Guid>(EntityShaperExpression: (...) failed. Either the query source is not an entity type, or the specified property does not exist on the entity type
```

Using `DbContext.Database.ExecuteSqlRawAsync()` works, though it's a bit more verbose, but it's good enough for me now.

**Comment by SpaceOgre** [comment]
@CesarD I came across this issue when needing to do the same thing.
I know it is old but I tried some things and wanted to share if some else finds it useful.

If we have these entites:
```c#
abstract class Base
{
    public int Id { get; set; }
}

class DerivedOne : Base
{
    public string Name { get; set; }
}

class DerivedTwo : Base
{
   public DateTime Time { get; set; }
}
```

You can do like this to change the Discriminator and the properties using ExecuteUpdate:
```c#
await ctx.Bases
    .Where(b => b.Id == 5)
    .ExecuteUpdateAsync(s => 
        s.SetProperty(b => EF.Property<string>(b, "Discriminator"), "DerivedTwo")
        .SetProperty(b => ((DerivedTwo)b).Time, DateTime.Now)
        .SetProperty(b => ((DerivedOne)b).Name, null as string)
);
```
Then you don't have to use ExecuteSqlRawAsync or similar.

**Comment by connorivy** [comment]
The solution that uses the change tracker without using executeupdate or executesqlraw was very difficult for me to track down, so I'm linking it here

https://github.com/dotnet/efcore/issues/7510#issuecomment-276724175

Note that `Metadata.IsReadOnlyAfterSave = false;` should be replace with `Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Save);`
