### ISSUE TITLE
Is a value comparer really required for record types?

### ISSUE THREAD

**Issue by nschoenberg** [dotnet/efcore#31983]
## Question

I get the following warning from EF when updating my DB or adding new migrations:

> The property 'PlanKonfiguration.DekadenTermine' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.

DekadenTermine is an array of record types and therefore the compiler generates the IEquatable for me. When I understand [the docs](https://learn.microsoft.com/en-us/ef/core/modeling/value-comparers?tabs=ef5#background) correctly, the Equals Method is used by default.

> By default, EF Core uses the default equality comparison defined by types (e.g. the Equals method); for snapshotting, [value types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types) are copied to produce the snapshot, while for [reference types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types) no copying occurs, and the same instance is used as the snapshot.

So my question is, is this warning a false positive? Or please correct my understanding :)

This is the definition of Property ```DekadenTermine``` using the record type ```DekadenBlockId```, as well es EF configuration

```C#
// Entity
public DekadenBlockId[] DekadenTermine { get; private set; } = Array.Empty<DekadenBlockId>();

// Record
public readonly record struct DekadenBlockId
{
    private const string IdRegEx = "^[A-C] [0-2][0-9]|[A-C] 3[0-4]$";

    private DekadenBlockId(string id)
    {
        Id = id;
        Block = Id[..1];
        Termin = int.Parse(Id[2..]);
    }

    public string Id { get; init; }

    public int Termin { get; }

    public string Block { get; }

    public static DekadenBlockId Create(string id)
    {
        Guard.Against.AgainstExpression(len => len == 4, id.Length, "Id must have length of 4. Examples: 'A 01', 'C 34'");
        Guard.Against.InvalidFormat(id, nameof(id), IdRegEx, "Id format does not match. Valid Examples: 'A 01', 'C 34'");

        return new DekadenBlockId(id);
    }

    public void Deconstruct(out string id)
    {
        id = Id;
    }
}

// Configuration for the Property
 builder.Property(conf => conf.DekadenTermine)
        .HasPostgresArrayConversion(
            block => block.Id,
            dbValue => DekadenBlockId.Create(dbValue));
```
### provider and version information

EF Core version: 7.0.9
Database provider: (Npsql Postgres)
Target framework: (NET 7.0)
Operating system: Win 10 22H2 Build 19045.3488
IDE: Visual Studio 2022 17.7

**Comment by ajcvickers** [comment]
@nschoenberg  `DekadenBlockId[]` is not a record type. It's an array containing record types. Without a value comparer, EF cannot detect when, for example, the item at index 2 is replaced with another item at index 2.
