### ISSUE TITLE
IEntityTypeConfiguration<T> defined on a record DB model type does not seem to be picked up or applied during model building

### ISSUE THREAD

**Issue by QuantumToasted** [dotnet/efcore#31993]
Previously, a DB model `MyModel` could inherit `IEntityTypeConfiguration<MyModel>` to define the model building behavior directly in the same class, like so:
```cs
public class MyModel : IEntityTypeConfiguration<MyModel>
{
    public int Id { get; set; }

    void IEntityTypeConfiguration<MyModel>.Configure(EntityTypeBuilder<MyModel> builder)
    {
        builder.HasKey(x => x.Id);
    }
}

// elsewhere, in the DbContext...
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.ApplyConfigurationsFromAssembly(typeof(MyModel).Assembly);
}
```
Ignoring the potential conversation about the pros/cons of doing this, I can attest to the fact that it **worked** at least in the way I was using it.

At the time of this writing, with .NET 7.0 and EFCore 7.0.11 (using the SQLite provider), attempting to define the same behavior with a `record`-based model does not function exactly the same.
```cs
public record MyModel(int Id) : IEntityTypeConfiguration<MyModel>
{
    void IEntityTypeConfiguration<MyModel>.Configure(EntityTypeBuilder<MyModel> builder)
    {
        builder.HasKey(x => x.Id);
    }
}

// elsewhere, in the DbContext...
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.ApplyConfigurationsFromAssembly(typeof(MyModel).Assembly);
}
```
Attempting to add a new migration at this point fails with the following message:
```
The entity type 'MyModel' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
```

I am unsure if this is an indication of a regression in behavior (a bug?), a quirk of `record`s specifically, or if the fact that what I was originally was doing with `class`es was unsupported behavior and that I should consider myself lucky it ever worked at all.

### Alternatives considered
Of course, I could always do things differently or more "by the book" such as having a dedicated `IEntityTypeConfiguration<MyModel>` class, or defining this all in my `DbContext` instead, or not using a `record` for my models. All of those are valid - I am simply filing this as a potential bug if this behavior no longer working on `record` types is something worth looking into.

**Comment by QuantumToasted** [comment]
Update: it has come to my attention that the cause of this issue is the fact that the `record` type in question lacks an empty constructor (or is otherwise unable to be instantiated by EFCore). Adding a dummy empty constructor, while not ideal, also resolves this problem. Might I ask instead if it would be possible to make the failure/error message more informative when it comes to this type of problem? A key **is** defined for the model, yet it claims there is not - not because one isn't actually defined, but it fails at some point to instantiate an instance of the `IEntityTypeConfiguration<MyModel>`.

(I'd actually be curious if it would be possible to utilize `static abstract` interface methods to accomplish this still, avoiding the need to instantiate the class in the first place, for users who do not need stateful data for their entity type configuration...)

Feel free to close this issue if there is nothing more to add.

**Comment by QuantumToasted** [comment]
Sorry for so many comments so quickly - in the interim out of boredom I whipped up a [proposal gist](https://gist.github.com/QuantumToasted/3109c9e6e42c7229a5c048c796a07b90) which might outline what a functioning `static` alternative to `IEntityTypeConfiguration<T>` could look like and function like. I'd be more than happy to open a separate PR if this is something even worth considering, but just thought to drop it here.

**Comment by ajcvickers** [comment]
@QuantumToasted We discussed this, but decided it's not a change we want to make. Adding another way to apply entity type configuration is likely to add more confusion over a space where there are already several options.

**Comment by AndriySvyryd** [comment]
As an alternative you can add a private nested class that implements `IEntityTypeConfiguration<T>`
