### ISSUE TITLE
The table schema is not always scaffolded when creating a migration and table name may be wrong when using schema

### ISSUE THREAD

**Issue by FabienDehopre** [dotnet/efcore#3199]
### Functional impact

When configuring multiple entities to be in a different schema than dbo, not all the tables are created in the given schema.
There is also a confusion in the table name in the migration script for the table(s) assigned to the custom schema.
### Minimal repro steps
1. Create several entities.
2. Create a DbContext class and configure the entities with at least the ".ToTable(tableName, schemaName)" method.
3. Scaffold a new migration using the "dnx ef migrations add <name>" command.
4. Review the newly created migration.
### Expected result

All the "CreateTable" method call in the migration should have both name and schema parameters set according to the configuration in the db context.
### Actual result

Only some (possibly only one) of the "CreateTable" method call in the migration actually have both the name and schema parameters set to a value. The others only have the name parameter set.
### Further technical details

Used version: 7.0.0-beta7
OS: Windows 10 Enterprise

Here is the commit in my project where the problem occured: https://github.com/FabienDehopre/yourls.net/commit/3f1cf0cb8e79b142314cc99541742d04202680f8
And all the code at this particular commit: https://github.com/FabienDehopre/yourls.net/tree/3f1cf0cb8e79b142314cc99541742d04202680f8

**Comment by bricelam** [comment]
It looks like you only configured the name and schema for the `Option` entity ...three times.
```C#
modelBuilder.Entity<Option>()
    .ToTable("Option", "yourls");
modelBuilder.Entity<Option>()
    .ToTable("Url", "yourls");
modelBuilder.Entity<Option>()
    .ToTable("Log", "yourls");
```

**Comment by FabienDehopre** [comment]
Indeed... It seems I did need an external point of view to see my mistake.
Shame on me :$

**Comment by sanalbakis** [comment]
Hi,

I have now also same issue when I want to create the database with entities. I am not sure, if it is my code error. If yes, please let me know. I have updated the EF7 to rc1-final and coreclr rc1-final

I have some models:

public class BaseEntity
{
      public int Id { get; set; }
}

public class BaseObject : BaseEntity 
{
   public string Name { get; set; }
   public DateTime CreatedDate { get; set; }
   public DateTIme UpdatedDate { get; set; }
   public int? CreatedById { get; set;}
   
   private User _createdBy;
   public virtual User CreatedBy {
    get { return _createdBy }
    set { _createdBy = value;
             CreatedById = value != null? value.Id : (int?)null;
         }
    }
}

and user Model
public class User : BaseObject
{
     public string Username { get; set; }
     public string Firstname { get; set; }
....................
}
   
and in Context Class I am writing 
 public DbSet<BaseObject> BaseObject { get; set; }
 public DbSet<User> Users { get; set; }

protected override void OnModelCreating (ModelBuilder modelBuilder)
{
            modelBuilder.Entity<BaseObject>(x =>
            {
                x.ToTable("BaseObject");
                ......
            });

            modelBuilder.Entity<User>(x =>
            {
                x.ToTable("User");
                .....................
            });
}

and after that I migrate the database, in Migration file there is no CreateTable with User, all User field are in BaseObject. 
 
Thank you
