### ISSUE TITLE
More information in TagWithCallSite

### ISSUE THREAD

**Issue by PrPleGoo** [dotnet/efcore#32003]
The TagWithCallSite is very cool but what I usually do is call TagWith(nameof(ContainingMethod)).
It would be cool if it did that automatically with the CallerMemberNameAttribute in addition to the 2 params it has now.

**Comment by ajcvickers** [comment]
@PrPleGoo We looked into this and, as far as we can tell, the containing method does not provide any additional useful information for tracing the query back to its source.

**Comment by PrPleGoo** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute?view=net-7.0#examples
The documentation seems to suggest that it does.

**Comment by ajcvickers** [comment]
> The documentation seems to suggest that it does.

I just read that and I don't see it suggesting that this provides any information about the location of the call site that the file and line number does not already provide.

**Comment by PrPleGoo** [comment]
I find it more useful when looking at traces to see a functional description of the query (method name) instead of a repository name (usually referring to a flow or entity type) plus a line number (only really useful if you also have immediate access to the code base). But that's just my 2 cents.

**Comment by ajcvickers** [comment]
@PrPleGoo And you're free to do that, but we don't believe the default implementation of `TagWithCallsite` should do so.

**Comment by PrPleGoo** [comment]
> @PrPleGoo And you're free to do that, but we don't believe the default implementation of `TagWithCallsite` should do so.

But why not?

**Comment by roji** [comment]
@PrPleGoo for one thing, it's important to keep logs tight and minimal, so that they remain readable; piling on information which doesn't add value makes logs less useful. And it seems like the file name and line are enough here.

**Comment by PrPleGoo** [comment]
Alright, too bad.
