### ISSUE TITLE
UseArtifactsOutput causes dotnet-ef to fail

### ISSUE THREAD

**Issue by deinok** [dotnet/efcore#32020]
Hi, 

Seems like the activation of `UseArtifactsOutput` with or without `ArtifactsPath` causes that `dotnet ef migrations add <migration>` to fail.
Can this be fixed before NET8 GA?

`error MSB4057: The target "GetEFProjec
tMetadata" does not exist in the project.
Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.`

**Comment by bricelam** [comment]
Isn’t the error message correct? You need to specify `--msbuildprojectextensionspath` since `UseArtifactsOutput` changes the default.

**Comment by deinok** [comment]
Can't EF detect the location of the artifacts? Been the default or not?

**Comment by deinok** [comment]
Can't EF detect the location of the artifacts? Been the default or not?

**Comment by gabynevada** [comment]
@bricelam Since UseArtifactsOutput is being oficially supported and promoted by microsoft, woudn't it make sense for dotnet-ef and other official tools to support both the default and the UseArtifactsOutput configurations?

**Comment by deinok** [comment]
For me this looks like a hardcoded issue at first glance.

I'm not sure how is the proper way to ask for the `obj` directory of a project, but fixing that should also fix the artifacts issue

**Comment by bricelam** [comment]
Yes. It is hard-coded. We don't know where the `obj` folder is without calling MSBuild and we can't hook into MSBuild without knowing where the `obj` folder is. Luckily, they added a way for us to avoid this in .NET 8. See #32113
