### ISSUE TITLE
Clearing collection doesn't remove the entities from the database table?

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#32022]
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```
public abstract class BaseEntity
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public Guid Id { get; set; }
    public DateTimeOffset Created { get; set; }
    public DateTimeOffset Modified { get; set; }
}
public class Product : BaseEntity
{
    private readonly List<Document> _documents = new List<Document>();
    public virtual IReadOnlyCollection<Document> Documents => _documents.AsReadOnly();
    public void RemoveDocument(Document doc) => _documents.Remove(doc);
    public void ClearDocuments() => _documents.Clear();
}
```
I have the following in `OnModelCreating`:
```
        var navigation = builder.Metadata.FindNavigation(nameof(Product.Documents));
        //EF access the Documents collection property through its backing field
        if (navigation != null)
            navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
```
The `Remove` and `Clear` doesn't remove the data from the DB table. How to do this correctly and intuitively?

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version: 7.0.11
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) PostgreSQL
Target framework: (e.g. .NET 6.0) .NET 7.0
Operating system: Ubuntu 23.04
IDE: (e.g. Visual Studio 2022 17.4) Does it matter?

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by khteh** [comment]
I expect clearing the `List<Table2>` of navigable items from a `DbSet<Table1>`  remove the records from `Table2` but it doesn't.

**Comment by ajcvickers** [comment]
What happens when you clear the list depends on the configuration and the state of the entities. That's why we need a repro.

**Comment by khteh** [comment]
Any documentation / reference for the configuration?

**Comment by ajcvickers** [comment]
https://learn.microsoft.com/en-us/ef/core/change-tracking/
