### ISSUE TITLE
Ef Core Query loosing rupee unicode symbol ₹ when trying to do a simple like query on it, instead generating "?" mark

### ISSUE THREAD

**Issue by aloksharma1** [dotnet/efcore#32027]
## File a bug
I have checked this issue thoroughly with `console.writeline` and debug breakpoints the symbol exists in memory and db no issues with inserts or updates but unable to query based on symbol itself.
my sql server query is like this and runs without issue:
`SELECT * FROM Currencies WHERE CurrencySymbol LIKE N'₹';`

with ef core the query it generates is something like this :

```
SELECT [c].[IsModified], [c].[CurrencyCode], [c].[CurrencyName], [c].[CurrencySymbol], [c].[DateCreated], [c].[DateModified], [c].[Id], [c].[IsActive]
FROM [dbo].[Currencies] AS [c]
WHERE ((LOWER([c].[CurrencyName]) LIKE N'%?%') OR (LOWER([c].[CurrencyCode]) LIKE N'%?%') OR (LOWER([c].[CurrencySymbol]) LIKE N'%?%')) AND [c].[IsActive] = CAST(1 AS bit)
ORDER BY [c].[CurrencyName]
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

the same query generates correct symbol for euro or dollar signs, for example :

```
SELECT [c].[IsModified], [c].[CurrencyCode], [c].[CurrencyName], [c].[CurrencySymbol], [c].[DateCreated], [c].[DateModified], [c].[Id], [c].[IsActive]
FROM [dbo].[Currencies] AS [c]
WHERE ((LOWER([c].[CurrencyName]) LIKE N'%$%') OR (LOWER([c].[CurrencyCode]) LIKE N'%$%') OR (LOWER([c].[CurrencySymbol]) LIKE N'%$%')) AND [c].[IsActive] = CAST(1 AS bit) AND ([c].[CurrencySymbol] LIKE N'%?%')
ORDER BY [c].[CurrencyName]
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

### Include your code

A simplified version of my query is included, the model is as is defined in query select part:

```C#
var CurrencyList = await _currenciesRepository.Query()!.Where(x=>x.CurrencySymbol.Contains("₹")).Select(x => new CurrenciesDTO
{
    IsModified = x.IsModified,
    CurrencyCode = x.CurrencyCode,
    CurrencyName = x.CurrencyName,
    CurrencySymbol = x.CurrencySymbol,
    DateCreated = x.DateCreated,
    DateModified = x.DateModified,
    Id = x.Id,
    IsActive = x.IsActive,
}).OrderBy(x => x.CurrencyName).ToPagedListAsync(dataQuery.PageNum!.Value, dataQuery.PageSize!.Value);
```
this also generates same result:
`var currency= await _currenciesRepository.Query()!.Where(c => c.CurrencySymbol.Contains("\u20B9")).ToListAsync(); `

And the provider model configuration in db context:

```C#
public override void Configure(EntityTypeBuilder<Currencies> builder)
{
    builder.ToTable(name: "Currencies");

    builder.SetupGuidTypePrimarykey(DatabaseType.SqlServer);

    builder.Property(x => x.CurrencyName).HasColumnType("nvarchar(250)").IsRequired();
    builder.Property(x => x.CurrencyCode).HasColumnType("nvarchar(10)").IsRequired();
    builder.Property(x => x.CurrencySymbol).HasColumnType("nvarchar(25)").IsRequired().IsUnicode(true);
    builder.HasIndex(x => x.CurrencyCode).IsUnique().HasFilter("[IsActive]=1");
    base.Configure(builder);
}
```

### Include provider and version information

EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: win 11
IDE: VS Code latest

**Comment by ajcvickers** [comment]
Note for triage: this appears to be an issue at the SqlClient/SQL Server level. I verified that EF creates the correct character in the query string in both the case that works (Euro) and the case that doesn't (Rupee):

<img width="143" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/aac25bf7-72a5-419d-a991-fdb1cd7367ef">

<img width="132" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/5cff77b4-e879-41fe-947b-976742d3ecce">

The code below executes this query string without using EF Core and shows that the wrong results are returned:

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.AddRange(
        new Currency { CurrencyName = "Dollar", CurrencySymbol = "$", },
        new Currency { CurrencyName = "Rupee", CurrencySymbol = "₹", },
        new Currency { CurrencyName = "Euro", CurrencySymbol = "€", });
    
    await context.SaveChangesAsync();
}

using (var context = new SomeDbContext())
{
    var connection = context.Database.GetDbConnection();
    connection.Open();
    
    using var command = connection.CreateCommand();
    command.CommandText = """
                          SELECT [c].[CurrencyName], [c].[CurrencySymbol], [c].[Id]
                               FROM [Currency] AS [c]
                               WHERE [c].[CurrencySymbol] LIKE N'%₹%'
                               ORDER BY [c].[CurrencyName]
                          """;

    using var reader = command.ExecuteReader();

    var count = 0;
    while (reader.Read())
    {
        count++;
    }

    Console.WriteLine($"Expected 1, got {count}");
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();


    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Currency>();
    }
}

public class Currency
{
    public int Id { get; set; }
    public string CurrencySymbol { get; set; }
    public string CurrencyName { get; set; }
}
```

Also tested with EF Core and Npgsql, and the query works there.

**Comment by ajcvickers** [comment]
Additional note: also fails when Rupee sysmbol is passes as a parameter.

**Comment by ErikEJ** [comment]
On the other hand, this works as expected:

```sql
SELECT [c].[CurrencyName], [c].[CurrencySymbol], [c].[Id]
FROM [Currency] AS [c]
WHERE [c].[CurrencySymbol] LIKE N'%₹%' COLLATE Latin1_General_100_BIN2
ORDER BY [c].[CurrencyName]
```

**Comment by aloksharma1** [comment]
> On the other hand, this works as expected:
> 
> ```sql
> SELECT [c].[CurrencyName], [c].[CurrencySymbol], [c].[Id]
> FROM [Currency] AS [c]
> WHERE [c].[CurrencySymbol] LIKE N'%₹%' COLLATE Latin1_General_100_BIN2
> ORDER BY [c].[CurrencyName]
> ```
> 
> Same fix works for the 🎯 char mentioned [here](https://stackoverflow.com/questions/4251765/how-to-use-like-statement-with-unicode-strings)

thanks for the tip but my column collate is working correctly with raw sql queries. so as @ajcvickers mentioned the issue is with SqlClient.

**Comment by aloksharma1** [comment]
> @aloksharma1 Can you post the raw SQL queries you have that are working?

i meant this same query when used in ssms directly, sorry for my poor choice of verbatim.

**Comment by ajcvickers** [comment]
@aloksharma1 What collation is set on the column in the database?

**Comment by aloksharma1** [comment]
> @aloksharma1 What collation is set on the column in the database?

its `SQL_Latin1_General_CP1_CI_AS`

**Comment by ajcvickers** [comment]
@aloksharma1 I get the same results from SSMS as I get from EF Core:

<img width="385" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/e6e0743a-433f-4009-866c-83fdb077cc18">

</br>

<img width="405" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/0df7802b-3f92-4e93-9c04-2500f71c5b99">

**Comment by aloksharma1** [comment]
> @aloksharma1 I get the same results from SSMS as I get from EF Core:
> 
> <img alt="image" width="385" src="https://user-images.githubusercontent.com/1430078/280060902-e6e0743a-433f-4009-866c-83fdb077cc18.png">
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/1430078/280061128-0df7802b-3f92-4e93-9c04-2500f71c5b99.png">

yes, after checking a few variations of query on my end i am also getting the same results as you if i don't use the collation provided by @ErikEJ :

`like N'%₹%';` or `like N'%₹';` or `like N'₹%';` produces the same result, equals query produces the correct result `like N'₹';` or `= N'₹';`

**Comment by ajcvickers** [comment]
Note for triage: the query generated by EF works if the database column has the appropriate collation--e.g. Latin1_General_100_BIN2. For example, when using Migrations:

```C#
    builder.Entity<Currency>()
        .Property(e => e.CurrencySymbol)
        .UseCollation("Latin1_General_100_BIN2");
```

**Comment by aloksharma1** [comment]
> Note for triage: the query generated by EF works if the database column has the appropriate collation--e.g. Latin1_General_100_BIN2. For example, when using Migrations:
> 
> ```cs
>     builder.Entity<Currency>()
>         .Property(e => e.CurrencySymbol)
>         .UseCollation("Latin1_General_100_BIN2");
> ```

thank you , i can confirm this patch works after applying migration. can you suggest a Collation that works for every language my application is multi-lingual so we want to cover all use cases (i though making columns nvarchar was enough to handle it).

**Comment by roji** [comment]
@aloksharma1 I'd suggest asking that in SQL Server forums/support - we're not the best experts for that kind of question.

**Comment by ajcvickers** [comment]
Closing, as EF and SqlClient are behaving by-design.
