### ISSUE TITLE
Best way to configure default schema retroactively (SQL Server)

### ISSUE THREAD

**Issue by sliekens** [dotnet/efcore#32047]
## Ask a question

Hello,

I have been using Migrations for a long time without ever giving thought to the database schema, only ever using the database default.

- My EF model does not have a default schema configured
- My entity configurations do not explicitly specify the schema name either
- All objects ended up being created in the default `dbo` schema, as decided by SQL Server

Now I would like to make that schema name explicit in the model configuration. I want to specify that all objects belong to the `dbo` schema, rather than having this as an implicit assumption.

The reason is that I am switching from SQL authentication to Windows authentication, and users created from a Windows group do not have `dbo` as their default schema. (They are created with a default schema that mirrors the name of the user.)

How can I do this retroactively without having to recreate all my EF migrations code?

### Include your code

I investigated whether I can set `ModelBuilder.HasDefaultSchema("dbo")`, but it only applies to new migrations. Older migrations are not updated with the schema name. Additionally, a migration is created with a lot of `RenameTable` statements to transfer tables to the `dbo` schema, which is not needed for my existing database.

```C#
public class AppDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("dbo");  // adding this at a later stage does not affect earlier migrations
    }
}
```

I would like a way to retroactively update all my existing migrations with the schema name. Can it be done?

### Include provider and version information

EF Core version: 7.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: N/A
IDE: N/A

**Comment by bricelam** [comment]
> I would like a way to retroactively update all my existing migrations with the schema name. Can it be done?

I can't think of any way to do this besides manually updating them.

**Comment by bricelam** [comment]
The fact that we preserve whether a schema was explicitly defined or not is a feature--you can apply the migrations as a user with a different default schema and they'll be created there instead.

**Comment by sliekens** [comment]
Thanks for your replies. I'm not really certain if executing migrations in the user default schema is ever a good idea as I was told prefixing tables with a schema name is a besy practice. But regardless, I did find a way to configure `dbo` as the default schema for an AD group. To be honest I don't understand why Windows users do not have `dbo` as their default schema like SQL users.
