### ISSUE TITLE
Using database user-defined scalar functions separately

### ISSUE THREAD

**Issue by Mohammad-Nayef** [dotnet/efcore#32056]
I can't use database functions alone, it throws an exception. Unless I use it in another statement.

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Mohammad-Nayef** [comment]
I have a function in my SqlServer database called fn_TotalRevenue, I have mapped it using EF Core:
```c#
modelBuilder.HasDbFunction(typeof(RestaurantReservationDbContext)
    .GetMethod(nameof(TotalRevenueByRestaurant), new[] { typeof(int) }))
    .HasName("fn_TotalRevenue");
```

 and here's the actual function in my code:
```c#
public int TotalRevenueByRestaurant(int restaurantId)
{
    throw new NotSupportedException();
}
```

If I try to execute it as a standalone function like this: 
```c#
var context = new RestaurantReservationDbContext();
var total = context.TotalRevenueByRestaurant(1);
```

It throws the exception `System.NotSupportedException: Specified method is not supported.`, which means that it uses the method as an unmapped method and provide the implementation of the method (which is `throw new NotSupportedException();`)

However, if I use it inside a LINQ query, it works fine, like this:
```c#
var context = new RestaurantReservationDbContext();
var restaurants = context.Restaurants
    .Where(r => context.TotalRevenueByRestaurant(r.Id) > 25)
    .ToList();
```

But in my case, I want to use the function only, without a LINQ query.

**Comment by roji** [comment]
@Mohammad-Nayef it sounds like your function is a table-valued function (TVF), which returns a table of results. If that's the case, you should be mapping it as such, as described [in these docs](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping#mapping-a-queryable-function-to-a-table-valued-function).

**Comment by Mohammad-Nayef** [comment]
No, it is a scalar function and returns a single integer value which is valid in the provided LINQ query.

**Comment by ErikEJ** [comment]
@roji Seems to be by design that it must be used as part of a query, this is not supported:

`var total = context.TotalRevenueByRestaurant(1);`

**Comment by roji** [comment]
A TVF can be used this way, but not a scalar function.

Note that there's no reason at all to use EF to just call a scalar-returning function. You can simply use SQL to call that function, possibly even directly via ADO.NET if that makes sense.

**Comment by Mohammad-Nayef** [comment]
@roji you are right, but knowing that it is not supported could have saved me hours of figuring out why it was throwing an exception. 
Also, before using it in a query, developers will do a quick test to make sure that it works as expected. If it throws an exception as a standalone method, then why would it do the right job inside a query?

**Comment by roji** [comment]
> Also, before using it in a query, developers will do a quick test to make sure that it works as expected. If it throws an exception as a standalone method, then why would it do the right job inside a query?

Because that is how LINQ and IQueryable work. C# code that's within the query isn't executed, it's **translated**: EF receives an expression tree describing the C# code, and generates SQL out of that. When you simply invoke the function out of a query, it's just a regular .NET function which get executes, so you get the exception (since that's what the method is implemented to do).
