### ISSUE TITLE
Cannot use migrations when using DbContexts on multiple databases

### ISSUE THREAD

**Issue by maxmantz** [dotnet/efcore#3206]
I'm developing a multi tenancy setup where I use the same DbContext on multiple databases. However, I can't get migrations to work. When I try a dynamic apporach as the one described in my <a href="http://stackoverflow.com/questions/32737557/how-to-setup-multi-tenancy-in-asp-net-5-web-api-and-entity-framework-7">StackOverflow question </a>, I get errors. When I supply a connection string, the migration gets created successfully, but my dynamic approach fails with an error and no migrations are being applied to the databases. 

However in the created context files I can find no mention of a connection string. When I try the EF7 database or migration commands, I cannot specify a connection string to apply a migration to multiple databases, therefore any hope of maybe creating a shell script to handle migrations across multiple databases is gone. Is it even possible to use EF7 in my use case scenario?

**Comment by maxmantz** [comment]
Solved the problem by specifying `this.Database.Migrate();` in the context constructor.

**Comment by rowanmiller** [comment]
@maxmantz you probably want toad some logic so that it's not done on every context creation, just once per AppDomain. Our recommendation is to do it during app startup rather than inline in the context.

**Comment by maxmantz** [comment]
@rowanmiller Thanks for the hint! I've updated the project to call the following during the configuration phase in order to call the migrations only once per application startup, like this:

    using (var context = tenantContextFactory.GetTenantContext<SamuraiContext>(custId))
    {
          context.Database.Migrate();
    }

Works like a charm so far.
