### ISSUE TITLE
EFCore 8 RC2 - Converters not getting used in some cases for an entity property which is part of JSON 

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#32073]
## Ask a question
I have created a type mapping for UInt32 type for Oracle Provider.
This type mapping uses a converter `OracleUInt32Converter() `also which converts the value to Int64 while writing it to the database.

```C#
public OracleUint32TypeMapping(string storeType,
  DbType? dbType = System.Data.DbType.UInt32
  )
  : this(
	new RelationalTypeMappingParameters(
	  new CoreTypeMappingParameters(
		typeof(UInt32), new OracleUInt32Converter(), jsonValueReaderWriter: JsonInt64ReaderWriter.Instance),
	  storeType,
	  StoreTypePostfix.PrecisionAndScale,
	  dbType))
{
}
```

But I am noticing the converter isn't being used in some scenario while writing the value to JSON data.

For Ex:- In the GIT test "`Can_read_write_collection_of_uint_enum_JSON_values`"
Converter gets called from below place in "JsonConvertedValueReaderWriter.cs"
```C#
public override void ToJsonTyped(Utf8JsonWriter writer, TModel value)
    => _providerReaderWriter.ToJson(writer, (TProvider)_converter.ConvertToProvider(value)!);
```
	

However in the GIT test "`Custom_naming_projection_everything`"
The converter is not called and `ModificationCommand.WriteJson` method directly calls ToJson() API
`(property.GetJsonValueReaderWriter() ?? property.GetTypeMapping().JsonValueReaderWriter)!.ToJson(writer, value);`

Shouldn't converter be called every time before writing the value to db?
Please could someone clarify if this is an issue from relational layer.

I have one more doubt. Is it allowed for a database provider to not use converter if the entity property is part of an aggregate (JSON) type.
For Ex:- For UInt32 entity property, can we use converter if the property is not part of an aggregate type and not use a converter if it is part of aggregate type. Is it allowed?

**Comment by shvmgpt116** [comment]
@ajcvickers @roji

**Comment by ajcvickers** [comment]
@shvmgpt116 Please try with the latest daily build.

**Comment by shvmgpt116** [comment]
I see the same behavior with latest daily build as well.

**Comment by ajcvickers** [comment]
@shvmgpt116 When a `JsonValueReaderWriter` is supplied as part of the type mapping, then it is expected to accept the actual property value, not the converted value. This enables the correct values to be written into JSON even when the database does not natively support the type outside of JSON, without going through the converter which is both inefficient and may be lossy.

**Comment by shvmgpt116** [comment]
@ajcvickers 
In the GIT test "Can_read_write_collection_of_uint_enum_JSON_values"
Converter gets called from below place in "JsonConvertedValueReaderWriter.cs"

public override void ToJsonTyped(Utf8JsonWriter writer, TModel value)
    => _providerReaderWriter.ToJson(writer, (TProvider)_converter.ConvertToProvider(value)!);

If converters are not used while writing the value to json data using JsonValueReaderWriter, why is this test calling the converter which Oracle is using for UInt32 entity property.
Please could you provide some explanation.
