### ISSUE TITLE
Problem with proper configuration database with EF core 7 using UTC dates

### ISSUE THREAD

**Issue by AdamPzpn** [dotnet/efcore#32097]
We have database which is source of data for many applications. It was upgraded to postgreSql 15.4 but a lot of settings need to be held in some older way.

Right now we have set TimeZone to 'Europe/Belgrade'

New project need to be prepared in one of schemes of this database.
New structure have some columns with dates. Type of dates is chosen as: "timestamp with time zone"

After migrating data there is a lot of dates in this format:  2023-10-22 00:00:00.000 +0200

Backend service is using EF Core 7.0.12

Frontend is sending some dates in UTC format: 2023-10-22

Right now i cant solve problem which is:
- after receving date to compare on backend, EF core is checking if date 2023-10-22 is >= then date 2023-10-22 00:00:00.000 +0200. (view from db IDE)

Unfortunately it seems EF core is building date check in this manner:

date_trunc('day',event_end_date, 'UTC') >= '2023-10-22T00:00:00.0000000Z'
which after enabling detailed logging it seem look like this

2023-10-21 02:00:00.000 +0200 >= '2023-10-22T00:00:00.0000000Z' --> it is always false but should be equal

code:

```

var predicate = PredicateBuilder.New<ModelEvent>();

predicate = predicate.And(p =>  p.EventEndDate == null && p.EventEndDate.Value.Date >= dateFrom );

var result = context.ModelEvents.AsNoTracking().AsExpandable().Where(predicate).ToList();

```

DateTime? dateFrom  
DateTime? p.EventEndDate 

How can I compare those dates without legancyBehavior?

EF Core version:
Database provider: (Npgsql.EntityFrameworkCore.PostgreSQL 7.0.11)
Target framework: (e.g. .NET 6.0)
Operating system: Rocky Linux (9.1)
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by AdamPzpn** [comment]
> This means that what's actually in your database is a timestamp for 2023-10-21 22:00:00.000 UTC.

This would be strange due to building timestamps from another table using date column and time for example. 
Date should be 2023-02-13 but after insert from trigger into this structure it seems that it is 2023-02-12 22:00:00.000 UTC.
Is it correct behavior?

Also I dont understand why EF core, when is getting data from colum timestamp with time zone which is apperently  UTC, is casting it again using command: 
date_trunc('day',event_end_date, 'UTC')

example sql query which is EF core generating:

```
SELECT *
FROM SomeTable AS g
WHERE ((g.event_start_date IS NOT NULL) 
AND  date_trunc('day',g.event_end_date, 'UTC') >= '2023-10-22T00:00:00.0000000Z'
AND  date_trunc('day',g.event_end_date, 'UTC')
<= '2023-10-22T00:00:00.0000000Z')
```

'2023-10-20T00:00:00.0000000Z' -- it is parameter from backend
date_trunc('day',g.event_end_date, 'UTC') -- data from database --> visual representation: 2023-10-21 02:00:00.000 +0200

even when i am testing query like this:

```
SELECT *
FROM SomeTable  AS g
WHERE ((g.event_start_date IS NOT NULL) 
AND  g.event_end_date>= '2023-10-22T00:00:00.0000000Z'
AND  g.event_end_date
<= '2023-10-22T00:00:00.0000000Z')
```

it cant find  g.event_end_date>= '2023-10-22T00:00:00.0000000Z' as equal. 
So is it inserted data a problem or is it something with this format? Or data from backend should be changed on the base of timezone due to EF core engine needs?

**Comment by roji** [comment]
@AdamPzpn it's honestly hard to understand exactly what exactly you're asking from the partial information above... If you think some EF-generated doesn't make sense, I need to see the exact LINQ query which produced it etc.

In any case, I'd verify very carefully exactly what type you have in the database (`timestamp with time zone` or `timestamp without time zone`), and what data (I recommend setting TimeZone to UTC to avoid confusion around this).

**Comment by AdamPzpn** [comment]
Problem occured due to my wrong understanding about datetime utc flow.
I was trying comparing UTC date which was prepared without timezone on backend with proper stored data in UTC with timezone offset.

It couldnt work well. Thanks for answers!
