### ISSUE TITLE
Adding a column comment with .HasComment  does not generate working script when targeting Oracle

### ISSUE THREAD

**Issue by b0uch3** [dotnet/efcore#32107]
### Description

We are using Oracle backend and have an operational requirement to provide column comments within our database.
We are using EF Core 7 and documentation clearly shows that .HasComment will generate column comments.  Tested on local SQL server and it works fine.  However, when migrating to our official Oracle database, this does not work.

This seems to be due to incorrectly generated SQL from EF Core.  It prefixes the value with N.  I understand this to indicate Unicode support but this will not execute on oracle.

Unsure if this is a bug or if there is a way to direct EF Core to avoid prefixing the column comment value with N.

### Example

Here is an example in one of our entities:

```C#
builder.Property(sp => sp.HiringManagerId).HasColumnName("HIRING_MANAGER").IsUnicode(false).HasComment<string>("This is an ApplicationUser"); ;
```

This is the generated SQL for migration:
```SQL
EXECUTE IMMEDIATE '
    COMMENT ON COLUMN "HRCMS"."SELECTION_PROCESS"."SUB_DELEGATED" is N''This is an ApplicationUser''
    ';
```

I can execute this command in oracle successfully.

```SQL
COMMENT on COLUMN HRCMS.SELECTION_PROCESS.SUB_DELEGATED is 'This is an ApplicationUser'
```

In contrast, this fails.

```SQL
COMMENT on COLUMN HRCMS.SELECTION_PROCESS.SUB_DELEGATED is N'This is an ApplicationUser'
```

EF Core version: 7.0.8
Database provider: Oracle.EntityFrameworkCore (7.21.9)
Target framework: 7
IDE: Visual Studio 2022 17.6.5

**Comment by roji** [comment]
@b0uch3 please report this to the Oracle provider maintainers - it isn't maintain in this repo.

**Comment by b0uch3** [comment]
thank you.  I wasn't sure whether this was sourced in EF Core or the Oracle provider.
