### ISSUE TITLE
No extra newline between query tags

### ISSUE THREAD

**Issue by kevinarthurackerman** [dotnet/efcore#32104]
Per [the documentation](https://learn.microsoft.com/en-us/ef/core/querying/tags) when you use multiple TagWith calls it is supposed to put an extra newline without comment marks (--) between them. The actual behavior is that is does not include a newline, making it impossible to parse tags unless you can assume that none of them are multiline.

Test Case:
```
var test = db.MyEntity
		.TagWith("Test 1")
		.TagWith(@"Test
2")
		.ToArray();
```

Expected:
```
-- Test 1

-- Test
-- 2

SELECT [m].[Value] FROM [dbo].[MyEntity] AS [m]
```

Actual:
```
-- Test 1
-- Test
-- 2

SELECT [m].[Value] FROM [dbo].[MyEntity] AS [m]
```

Also, I would like to submit a request to add a parsed collection of tags to the CommandEndEventData. It could be added with a method similar to this (assuming the above bug is fixed).

```
IEnumerable<string> ParseTags(string script)
        {
            var sb = new StringBuilder();
            var writingTag = false;

            foreach (var line in script.Split(Environment.NewLine))
            {
                if (line.StartsWith("-- "))
                {
                    writingTag = true;
                    sb.AppendLine(line[3..]);
                    continue;
                }

                if (writingTag)
                {
                    writingTag = false;
                    yield return sb.ToString();
                    sb.Clear();
                    continue;
                }

                break;
            }
```

**Comment by ajcvickers** [comment]
@kevinarthurackerman The docs are out of date on the newline.

**Comment by kevinarthurackerman** [comment]
@ajcvickers does this mean that there is not supposed to be a newline between tags? If not, how can one differentiate between one multiline tag and multiple single line tags?

**Comment by ajcvickers** [comment]
@kevinarthurackerman Correct. There is no built-in way to differentiate. There isn't any fundamental difference between two query tags and a tag with two lines. Why do you need to differentiate this?

**Comment by kevinarthurackerman** [comment]
[The documentation here](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#example-command-interception-to-add-query-hints) suggests using query tags to mark a query to perform some additional logic in interceptors. Is there a more elegant way to accomplish this? If this is not the intended purpose of query tags is it just to add some comments in the query to do things like tracking?

**Comment by roji** [comment]
@kevinarthurackerman you can identify query tags in interceptors and perform special logic, but I don't see how multi-line support is necessary for that.

**Comment by kevinarthurackerman** [comment]
Anyone else writing code in the same code base or any library you take a dependency on might use a multi-line tag since it is supported by Entity Framework. If this is the best feature available to support per-query branching logic then I will have to assume that all query tags are single-line. Honestly, if you can't distinguish between two one line comments and a two line comment I would prefer if the framework did not support multi-line comments at all, but that would be a breaking change.

The logic will need to be something like while the next line begins with "--" check to see if the line matches my tag, if yes do a thing, if no continue to the next line.

**Comment by roji** [comment]
@kevinarthurackerman we've generally seen people using single-line tags - that seems to have been sufficient for all uses, whether for interception logic branching or logging. AFAIK we've never received a complaint about difficulties using multi-line tags.

**Comment by 304NotModified** [comment]
[The docs](https://learn.microsoft.com/en-us/ef/core/querying/tags) are still out of date? Why is this closed?

<img width="1120" height="312" alt="Image" src="https://github.com/user-attachments/assets/c708e848-9b86-4948-ac0c-426362e18477" />

**Comment by roji** [comment]
@304NotModified thanks, merged your [EntityFramework.Docs#5230](https://github.com/dotnet/EntityFramework.Docs/pull/5230).
