### ISSUE TITLE
Explicit default in DB is not preserved in EF with HasDefaultValue

### ISSUE THREAD

**Issue by piskov** [dotnet/efcore#32123]
Suppose we have a bit not null value with explicit default set in SQL Server

```
CREATE TABLE MyTable(
    …
    MyFlag [bit] NOT NULL,
)

ALTER TABLE MyTable ADD CONSTRAINT Smth DEFAULT (0) FOR MyFlag
GO

```

When you reverse engineer the DB into EF you’ll get:
```
class MyTable
{
    bool MyFlag {get; set;}
}
```

If then you would call `dbContext.Database.GenerateCreateScript()` it will lose the explicit `0` as default value in the generated scripts. This is unfortunate when you’re using EF as a tool to migrate between the DB engines. While it’s not an issue if you’re only using EF (CLR bool in code will always be false), it will brake some existing non C# logic (like some SQL that rely on the existing ability to skip those bit properties)

Solution: automatically add `builder.Property(b => b.MyFlag) .HasDefaultValueSql("0"); ` while reverse engineering if the property has explicit default constraint set in the DB.

Why this is an issue: figuring out about this “vanished” defaults during migrations between the database engines is a royal pain in the ass — one needs to manually diff the scripts from SQL Server Management Studio and the EF to see what’s been missing.

**Comment by ErikEJ** [comment]
@piskov Which EF Core version??

**Comment by piskov** [comment]
@ErikEJ sorry, 8rc2.23480.1 with annotations preferred scaffolding and 2.51614 power tools.

dotnet-ef is also 8rc2.23480.1

**Comment by ErikEJ** [comment]
I think there was a bug in RC1 which is what Power Tools uses with your version.  Could you try the latest daily build. Your runtime and dotnet ef versions are not relevant here.

**Comment by piskov** [comment]
@ErikEJ installed the latest daily build 2.5.1624 — still no `HasDefaultValueSql("0")`.

Also tried scaffolding with bare `dotnet ef dbcontext scaffold` with and without data annotations, also without any t4, — everything to no avail.

**Comment by ajcvickers** [comment]
@piskov This is by-design--see #9627.

**Comment by piskov** [comment]
@ajcvickers the referenced issue seems on focusing `bool` vs `bool?`.

I wouldn’t want it to be nullable in c# code as well. That said what’s wrong to have a cake and eat it too: be non-nullable bool property in C# and have `HasDefaultValueSql("0");` (or 1) if that’s what is explicitly set in the db. This way it’s great both in c# and doesn’t break any existing sql (like stored procedures) if they rely on not having to supply that field.

**Comment by piskov** [comment]
@ajcvickers a little off-topic:
> There is anyway no expectation that a scaffolded configuration will result in the same database 

That’s exactly what we’re counting on to migrate from SQL server to Postgres, and with some little quirks it stays mostly the same (we manually diff the scripts between sql server and what EF does with `GenerateScripts()`). Currently the most annoying is this bit stuff but it is easily fixed by adding manually `HasDefaultValueSql("0")`

Are there any links you can please point me at that are make “will not result in the same database”?

**Comment by flier268** [comment]
I have the following C# code:
```C#
    [JsonConverter(typeof(JsonNumberEnumConverter<EDateIsPrintFlag>))]
    public enum EDateIsPrintFlag
    {
        NotPrint = 0,
        Print = 1,
    }
    public class A{
      public EDateIsPrintFlag CustomDate1Flag { get; set; }
    }
```

![圖片](https://github.com/dotnet/efcore/assets/19989232/10265736-c621-4c6f-a255-5feb27c25a08)

I am using the Entity Framework Core to scaffold my database context. The command I use is:
```bat
dotnet tool update --global dotnet-ef
dotnet ef dbcontext scaffold "Data Source=/*connectionstring*/" "Microsoft.EntityFrameworkCore.SqlServer" -o ./EntityModels -c EFCoreContext --context-dir DataContexts -f --data-annotations --project FPS2_Desktop.DB --no-onconfiguring
```
With dotnet-ef version 8.0.0, the generated code is:
```C#
 modelBuilder.Entity<Plu>(entity =>
 {
            entity.Property(e => e.CustomDate1Flag).HasDefaultValue(1);
 }
```
However, this results in an error:
```
System.InvalidOperationException: 'Cannot set default value '1' of type 'System.Int32' on property 'CustomDate1Flag' of type 'FPS2_Desktop.Core.Enums.EDateIsPrintFlag' in entity type 'A'.'
```

dotnet-ef version: 8.0.0


Previously, with an older version of dotnet-ef, the generated code was:
```C#
      entity.Property(e => e.CustomDate1Flag).HasDefaultValueSql("((1))");

```

But this approach no longer works after upgrading to version 8.0.0. Can you help me correct this?

**Comment by ajcvickers** [comment]
@flier268 This is an old issue. Please open a new issue and provide the full SQL needed to create a schema that will generate this error when a context is scaffolded from it.
