### ISSUE TITLE
Possibility of generating migrations with Fluent API

### ISSUE THREAD

**Issue by eimigueloliveir** [dotnet/efcore#32135]
I believe that the way migration files are generated today is not to everyone's taste, making analysis, customization, maintenance in case of errors, etc. very difficult.

An **optional** way to generate migration files using a fluent API similar to [OnModelCreating](https://learn.microsoft.com/en-us/ef/core/modeling/#use-fluent-api-to-configure-a-model) would work would be perfect, below is a comparison using the [FluentMigrator](https://github.com/fluentmigrator/fluentmigrator) library as a base.

I believe that without a doubt this would be possible because [Scaffolding](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli) generates the calls in OnModelCreating's fluent api

```cs
public partial class create_database : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {

        migrationBuilder.CreateTable(
            name: "asp_net_users",
            columns: table => new
            {
                id = table.Column<string>(type: "varchar(255)", nullable: false),
                user_name = table.Column<string>(type: "varchar(256)", maxLength: 256, nullable: true),
                normalized_user_name = table.Column<string>(type: "varchar(256)", maxLength: 256, nullable: true),
                email = table.Column<string>(type: "varchar(256)", maxLength: 256, nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_asp_net_users", x => x.id);
            });

        migrationBuilder.CreateIndex(
            name: "email_index",
            table: "asp_net_users",
            column: "normalized_email");

        migrationBuilder.CreateIndex(
            name: "user_name_index",
            table: "asp_net_users",
            column: "normalized_user_name",
            unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "asp_net_users");
    }
}
```
equivalent
```cs
public override void Up()
{
    Create.Table("asp_net_users")
        .WithColumn("id").AsString().PrimaryKey().Identity()
        .WithColumn("user_name").AsString(256).Nullable()
        .WithColumn("normalized_user_name").AsString(256).Nullable()
        .WithColumn("email").AsString(256).Nullable();

    Create.Index("email_index").OnTable("asp_net_users").OnColumn("normalized_email");
    Create.Index("username_index").OnTable("asp_net_users").OnColumn("normalized_user_name").Unique();
}

public override void Down()
{
    Delete.Table("asp_net_users");
}
```

**Comment by roji** [comment]
@eimigueloliveir the style of the code inside of the generated migration code shouldn't matter much, definitely not to an extent that we'd introduce a whole new API (and keep supporting the old one because migrations already exist).

**Comment by roji** [comment]
I don't think your proposal represents a real improvement - it's mostly just a different style compared to the existing. Such changes are technically possible, but we are very unlikely to invest time in it that could be spent improving more important EF areas.

**Comment by eimigueloliveir** [comment]
Ok, if in the future it is possible...
