### ISSUE TITLE
EF Core type inheritance to be ignored in OnModelCreating

### ISSUE THREAD

**Issue by c0deExplorer** [dotnet/efcore#32145]
## Ask a question

I would like to request expert inputs on how to achieve "an audit" process I am working on.
I have an entity called "ABC" (database table) and a corresponding audit entity "AuditABC" (inheritting ABC, but with audit properties). I want EF to treat both these entities to be disconnected/independent on the backend.
When I do "UseTpcMappingStrategy()" on the base class ABC, its doing "UNION ALL" during ABC fetch, which is expected but I am trying to avoid exactly that -  not sure how to break that relationship and force EF to fire "Select from ABC" without "UNION ALL". Basically I have type inheritance in code but looking for an option to suppress that relationship on the backend.

Here's my C# snippet

```c#
public class ABC
{
    public int Id { get; set; }
    public string FirstName { get; set; }
}

public  class AuditABC : ABC
{
    public new int Id { get; set; }
    public int ABCId { get; set; }
    public DateTime CreatedDate { get; set; }
}
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
        modelBuilder.Entity<ABC>().ToTable("AuditABC");
        modelBuilder.Entity<ABC>().ToTable("ABC").UseTpcMappingStrategy();

}
public override int SaveChanges()
 {
        //Straightforward code to create and save
        //AuditABC records if any Modified
        //or Added or Deleted ABCs

 }
```

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
@c0deExplorer Tell EF that the types should not be considered as a hierarchy like this:

```C#
modelBuilder.Entity<AuditABC>().HasBaseType((Type?)null);
```

**Comment by c0deExplorer** [comment]
Thank you!
