### ISSUE TITLE
Is EF Core 8.0 RC2 defaulting the execution strategy to SqlServerRetryingExecutionStrategy when targeting Azure SQL?

### ISSUE THREAD

**Issue by jonsagara** [dotnet/efcore#32165]
Hi,

Today I updated my ASP.NET Core web application to .NET 8.0 RC2, including EF Core. The application is deployed in Azure App Service, and uses Azure SQL as the database.

We have a page that manually begins a transaction with `myContext.Database.BeginTransactionAsync()`. When running locally, the code still works fine. However, after deploying to Azure, we started getting these exceptions:

`System.InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user-initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.
`

Our `DbContext`s explicitly do not enable `SqlServerRetryingExecutionStrategy`. However, spelunking through the latest EF Core code, I found this in `SqlServerOptionsExtension.cs`, starting at line 110:

```csharp
/// <summary>
///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
///     the same compatibility standards as public APIs. It may be changed or removed without notice in
///     any release. You should only use it directly in your code with extreme caution and knowing that
///     doing so can result in application failures when updating to a new Entity Framework Core release.
/// </summary>
public virtual bool IsAzureSql
    => _azureSql ?? IsAzureSqlDefault;

private bool IsAzureSqlDefault
    => (ConnectionString ?? Connection?.ConnectionString)
        ?.Contains(".database.windows.net", StringComparison.InvariantCultureIgnoreCase)
        == true;

/// <summary>
///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
///     the same compatibility standards as public APIs. It may be changed or removed without notice in
///     any release. You should only use it directly in your code with extreme caution and knowing that
///     doing so can result in application failures when updating to a new Entity Framework Core release.
/// </summary>
public virtual SqlServerOptionsExtension WithAzureSql(bool enable)
{
    var clone = (SqlServerOptionsExtension)Clone();

    clone._azureSql = enable;

    return clone;
}

/// <inheritdoc />
public virtual IDbContextOptionsExtension ApplyDefaults(IDbContextOptions options)
{
    if (!IsAzureSql)
    {
        return this;
    }

    if (ExecutionStrategyFactory == null)
    {
        return WithExecutionStrategyFactory(c => new SqlServerRetryingExecutionStrategy(c));
    }

    return this;
}
```

My question is: does EF Core now inspect the connection string, and if it detects an Azure SQL database, force the DbContext to use `SqlServerRetryingExecutionStrategy`? If so, is there a way to prevent this?

Thank you,

Jon

### Include provider and version information

EF Core version: 8.0 RC2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0 RC2
Operating system: Windows (Azure App Service, and also Windows 11 for local dev)
IDE: (e.g. Visual Studio 2022 17.8 Preview 5)

**Comment by jonsagara** [comment]
FWIW, I enabled `SqlServerRetryingExecutionStrategy`, and I get the same error that I'm seeing in Azure.

**Comment by ErikEJ** [comment]
@jonsagara This was reverted post rc 2, try the latest daily.

**Comment by jonsagara** [comment]
Confirmed fixed with daily build. Thank you!

**Comment by roji** [comment]
Duplicate of #32052
