### ISSUE TITLE
PrincipalKey causes duplicate key problem for tracked entity

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/efcore#32161]
## Ask a question

We have a case were we have a navigation between entities were the PK is not used on one side meaning a PrincipalKey needs to be used. This seems to also create a keyset when the Entity is tracked.  
We have a case when we have one entity loaded into tracked entities. We add a new entity of same type with same principal keys. 

It now breaks with exception

> The instance of entity type 'EntityA' cannot be tracked because another instance with the same key value for {'KeyOne', 'Keytwo' } is already being tracked. 

We cant detach the first entity as we update both in a unit of work context. 
How can we solve this problem? Thanks.

### Include provider and version information

EF Core version: 6.0.12
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system:  Windows 11
IDE:  Visual Studio 2022 17.6.6

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndersMalmgren** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.


Given these two entities.

public class EntityA 
{
   public PKKey {get;set;} 
   public FKKeyOne {get;set;}
   public FKKeyTwo {get;set;}   
   public ICollection<EntityB> EntityBs  {get;set;} 
   public EntityA Parent {get;set; }
}

public class EntityB
{
   public PKKeyOne {get;set;} 
   public PKKeyTwo {get;set;} 
   public PKKeyThree {get;set;}  
}

builder.HasMany(ac => ac.EntityBs)
   .WithOne()
   .HasForeignKey(b => new { b.PKKeyOne, b.PKKeyTwo })
   .HasPrincipalKey(a=> new { a.FKKeyOne , a.FKKeyTwo });


var parent = new EntityA();
db.AddAsync(parent),
db.SaveChangesAsync(); //Works EntityA is now saved to db

New db context 
var parent = db.Set<EntityA>().FindAsync(someId);
var child = new EntityA 
{
   Parent = parent,
   ... copy some properties from parent including FKOne and Two.

}

db.SaveChangesAsync(); //Fails here because EF detects two EntityA with same keys becasuse HasPrincipalKey will override its keys.

Note that navigation to EntityB is readomly and EntityB is created elsewere.

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndriySvyryd** [comment]
@AndersMalmgren These code snippets are not enough, we need a full repro that can be run without any changes.

**Comment by AndersMalmgren** [comment]
@AndriySvyryd Here is a repro using code first and localdb

https://github.com/AndersMalmgren/PrincipalRepro

**Comment by AndriySvyryd** [comment]
So, if I understand correctly, you want to add an entity with the same alternate key values as another entity that's already tracked. This is not supported. Currently all alternate key values must be unique both on the client and in the database.

Instead of adding a new entity you could update the existing one. In EF 8 we added API to lookup tracked entities by any value:
```C#
var existingEntry = db.Set<EntityA>().Local.FindEntry([nameof(EntityA.FKKeyOne), nameof(EntityA.FKKeyTwo)], [1, 2]);
```

**Comment by AndersMalmgren** [comment]
> So, if I understand correctly, you want to add an entity with the same alternate key values as another entity that's already tracked. This is not supported. Currently all alternate key values must be unique both on the client and in the database.
> 
> Instead of adding a new entity you could update the existing one. In EF 8 we added API to lookup tracked entities by any value:
> 
> ```cs
> var existingEntry = db.Set<EntityA>().Local.FindEntry([nameof(EntityA.FKKeyOne), nameof(EntityA.FKKeyTwo)], [1, 2]);
> ```

We use this from projections among others so that will not work. I guess joins are the only solution. But that will mean we need to repeat the join on every place we use this navigation.  Not so DRY
