### ISSUE TITLE
Microsoft.Extensions dependencies in 8.0 latest nightly broken

### ISSUE THREAD

**Issue by antmeehan** [dotnet/efcore#32171]
![image](https://github.com/dotnet/efcore/assets/9822503/28413528-6bd8-4f09-815d-fed61b04b057)

Sorry for the screenshot, but it shows the latest nightly for EF Core 8 have dependencies to `Microsoft.Extensions.Caching.Memory` >= `8.0.0.0` which don't exist yet so you get:

`Error NU1102 : Unable to find package Microsoft.Extensions.Configuration.Abstractions with version (>= 8.0.0)`

(Same for `Microsoft.Extensions.Logging`).

Or is there somewhere I can point to to get the `8.0.0.0` versions needed?

Thanks.

**Comment by antmeehan** [comment]
I've pinned to these as a work-around for now:

```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0-rtm.23518.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0-rtm.23518.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0-rtm.23518.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0-rtm.23518.9">
```

**Comment by roji** [comment]
@antmeehan this is very likely a temporary issue with the daily builds as things are being prepared for the final release in a few weeks. Since 8.0 is now practically done and very little is now getting merged in, it should be fine to just use the latest daily build which works until the release.

**Comment by antmeehan** [comment]
Thanks @roji . Hopefully if anyone else hits this issue they will see this too 👍

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/efcore/pull/32210
