### ISSUE TITLE
SQLite: add preliminary support for Virtual File Systems

### ISSUE THREAD

**Issue by dsshep** [dotnet/efcore#32178]
SQLite has a feature, [Virtual File Systems](https://www.sqlite.org/vfs.html), which allows more control over how SQLite interacts with the OS.

At the moment it is possible to register and use a vfs with `Microsoft.Data.Sqlite`. The native bindings that `SqliteConnection` relies on, `SqlitePclRaw`, has the methods (although not directly exposed) for registering, listing and unregistering a vfs.

However, managing which vfs a `SqliteConnection` is associated with is not currently possible. If you want a different vfs to be used, you must make it the default and therefore all connections will use it. 

For now, if there was a way of passing the vfs name when the connection is being opened (e.g. in the connection string), it would be possible to open connections and pool them with a different vfs. The (involved) process of actually creating the vfs can be left up to the reader...

This had previously been suggested (https://github.com/dotnet/efcore/pull/21797) and closed as no justification was given for it. There has also been some API discussion: https://github.com/dotnet/efcore/issues/27986#issuecomment-1124027723. I have also implemented a more up to date version of this in a fork https://github.com/dsshep/efcore/tree/sqlite-vfs.

**Comment by bricelam** [comment]
> if there was a way of passing the vfs name when the connection is being opened (e.g. in the connection string)

This is possible today.

```cs
var connection = new SqliteConnection("Data Source=\"file:Example.db?vfs=my-vfs\"");
```

**Comment by dsshep** [comment]
Huh, was not aware that it would pass through. Thank you for the quick reply!
