### ISSUE TITLE
IMaterializationInterceptor causes InMemory database to lose entities

### ISSUE THREAD

**Issue by holotrek** [dotnet/efcore#32170]
When using an IMaterializationInterceptor in order to set injected services on an entity, the entities seeded/created in one scope are gone in another scope. Without the interceptor this does not happen and the entity remains.

Steps to reproduce:
1. Create a standard .NET Web API project (Minimal API in my example)
2. Add the Micrsofot.EntityFrameworkCore.InMemory nuget package
3. Create a sample DbContext and an entity
4. Register the DbContext as normal
```c#
builder.Services.AddDbContext<SampleDbContext>(opt => opt
    .UseInMemoryDatabase("Sample"));
```
6. Override `OnModelCreating` and seed a record for the sample entity
7. Create a sample service that does some sort of work
8. Add this property to the entity with the `[NotMapped, JsonIgnore]` attribute.
9. Lift this property to an interface called `IServiceInjectable` and implement this interface with your entity.
10. Create the interceptor:
```c#
    public class EntityServiceInjector : IMaterializationInterceptor
    {
        public object InitializedInstance(MaterializationInterceptionData materializationData, object instance)
        {
            if (instance is IServiceInjectable entity)
            {
                entity.Service = materializationData.Context.GetService<SampleService>();
            }

            return instance;
        }
    }
```
11. Add an endpoint to get the sample entities:
```c#
app.MapGet("/sample", (SampleDbContext context) =>
{
    return context.Samples.ToList();
});
```
12. Add code to ensure seeding of DB happens:
```c#
using var scope = app.Services.CreateScope();
var ctx = scope.ServiceProvider.GetRequiredService<SampleDbContext>();
ctx.Database.EnsureCreated();
```
13. Run the API and hit the `/sample` endpoint. This will succeed in retrieving the entity.
14. Now, add the interceptor to the DbContext registration:
```c#
builder.Services.AddDbContext<SampleDbContext>(opt => opt
    .UseInMemoryDatabase("Sample")
    .AddInterceptors(new EntityServiceInjector()));
```
15. Run the API again and hit the `/sample` endpoint. The resulting list is now empty.

_NOTE:_ Despite not being included in the attached example, this also does affect entities added during regular use of an app, i.e. with a POST endpoint that adds and calls `SaveChanges()`.

### Include your code

Full project attached. The interceptor is commented out so it can be run with the first test case where it works. To show the issue, uncomment the call to `AddInterceptors` in `Program.cs`.

[TestInMemoryDb.zip](https://github.com/dotnet/efcore/files/13182979/TestInMemoryDb.zip)

### Include provider and version information

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.5.5

**Comment by ajcvickers** [comment]
@holotrek `IMaterializationInterceptor` is a "singleton interceptor". This means that the same interceptor instance is used for all context instances. But this in turn means that if a new interceptor instance should not be passed to each DbContext instance. Instead, a singleton interceptor instance should be created and registered. This is often handled by creating the interceptor instance as a static field of the DbContext.

**Comment by holotrek** [comment]
Hi, I tried looking for documentation on this particular interceptor, but couldn't find it. That fixed the issue, although it was very strange that it was causing entities to be dropped completely rather than just not working right or throwing an exception to indicate that there shouldn't be more than one instance. Thanks, I will close this.

**Comment by ajcvickers** [comment]
Documentation is tracked here: https://github.com/dotnet/EntityFramework.Docs/issues/4403
