### ISSUE TITLE
Ef8, Complex property and indexes

### ISSUE THREAD

**Issue by CheloXL** [dotnet/efcore#32176]
How do I setup indexes on properties of complex property? On owned types I have a HasIndex() in the provided nested builder, but I don't see any method to do the same on complex property.

With owned types:
```cs
builder.OwnsOne(x => x.Location, navigationBuilder =>
{
	navigationBuilder.HasIndex(x => x.Latitude);
	navigationBuilder.HasIndex(x => x.Longitude);
});
```

With complex property:
```cs
builder.ComplexProperty(x => x.Location, propertyBuilder =>
{
	propertyBuilder.???
});
```

Thanks in advance!

**Comment by ajcvickers** [comment]
Duplicate of #31246

**Comment by CheloXL** [comment]
Thanks... did a search first but no with that terminology.
