### ISSUE TITLE
Running iterations causes perf tests to crash

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3217]
Running adventure works tests with "benchmarks:runIterations=true" crashes with the xunit.console.exe runner.

```
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
```

**Comment by rowanmiller** [comment]
Are you still seeing this? It sometimes happens when there is another exception occurring. The perf CI runs using the console runner and it's all green now.

**Comment by natemcmaster** [comment]
I was seeing the error on CI, so it must be fixed now.
