### ISSUE TITLE
BUG: AccessViolationException using where expression on decimal in .Net 6, x86 target, Sqlite

### ISSUE THREAD

**Issue by Craig-TSS** [dotnet/efcore#32180]
EF Core version: 6.0.24
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Tested on Windows 10, Windows 11
IDE: Visual Studio 2022 17.7.4

When targeting the x86 platform specifically (no issue on x64), a simple efcore query to an sqlite db with a where clause applied against a decimal value causes the following error, and results in full application termination.
"An unhandled exception of type 'System.AccessViolationException' occurred in SQLitePCLRaw.provider.e_sqlite3.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

I have attached a sample project that reproduces the issue easily. Just run it and it will crash on the db query in Index.cshtml.cs
[SqliteX86FilteringIssue.zip](https://github.com/dotnet/efcore/files/13201335/SqliteX86FilteringIssue.zip)

I am posting under efcore issue as i dont know what is actually triggering the failure in the low level SQLitePCLRaw.provider.e_sqlite3.dll, the sample just includes the Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Sqlite nuget packages so I am not doing anything special.

Please advise as to what can be done as this issue is affecting our ability to offer value based filtering to our customers and resulting in full app crashes when they try. We have only recently upgraded to .Net 6 from .Net Core 3.1 where this previously worked fine.

Thanks

**Comment by Craig-TSS** [comment]
FYI this issue still occurs on .Net 7 as well. 
Microsoft.EntityFrameworkCore 7.0.13
Microsoft.EntityFrameworkCore.Sqlite 7.0.13

For us, we need a fix for this issue in .Net 6 (LTS) as we have a requirement to still continue to support legacy Windows 7 machines due to the specialty POS machines used in the hospitality/retail sector.

**Comment by bricelam** [comment]
Does updating the transient SQLitePCLRaw dependency fix it?

```xml
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.6" />
```

**Comment by ajcvickers** [comment]
@bricelam It still failed for me with the latest bundle package.

**Comment by Craig-TSS** [comment]
> Does updating the transient SQLitePCLRaw dependency fix it?
> 
> ```
> <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.6" />
> ```

No difference, still crashes the same. 

@ajcvickers I run on an x64 machine too, all it needs is for the process to run in 32 bit mode which the sample project is setup to do via the below in the csproj
```
<PlatformTarget>x86</PlatformTarget>
```

**Comment by Craig-TSS** [comment]
Hi Guys, any ideas what the problem is here?

**Comment by ajcvickers** [comment]
@ericsink Hey Eric--is this something you have seen before?

**Comment by ericsink** [comment]
I wonder if this might be ericsink/SQLitePCL.raw#573, but I haven't looked at the repro sample yet.

**Comment by bricelam** [comment]
Yes, I think it's the same underlying issue. Forcing it to use the netstandard2.0 assembly works:

```xml
<ItemGroup>
  <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.2" GeneratePathProperty="True" ExcludeAssets="compile" />
  <Reference Include="$(PkgSQLitePCLRaw_provider_e_sqlite3)\lib\netstandard2.0\SQLitePCLRaw.provider.e_sqlite3.dll" />
</ItemGroup>
```

**Comment by ericsink** [comment]
I'll take a look at getting a fix done.  Thanks.

**Comment by ericsink** [comment]
There's a new SQLitePCLRaw preview (version 2.1.7-pre20231117161811) which contains the (attempted) fix for this.

**Comment by ajcvickers** [comment]
Many thanks for the fast turnaround, Eric!

**Comment by Craig-TSS** [comment]
@ericsink  Great thanks for sorting it out Eric, it does indeed appear to resolve the issue. In terms of using this patch a production app, are there any other risks with this pre-release build, or should I wait for an official release?

@ajcvickers Any idea roughly (eg a week, a month etc) when we are likely to see the next efcore 6 release which includes this updated SQLitePCLRaw fix as standard? Just trying to work out my options for a production build of my software with this fix.

**Comment by ajcvickers** [comment]
> Any idea roughly (eg a week, a month etc) when we are likely to see the next efcore 6 release which includes this updated SQLitePCLRaw fix as standard?

Don't plan for this. Plan for having a direct reference to the latest package from your project.

**Comment by ericsink** [comment]
I intend to publish the 2.1.7 release sometime this week.

**Comment by Craig-TSS** [comment]
Ok, thanks for the info and for getting a fix sorted out.
