### ISSUE TITLE
Does the HierarchyId is supported for InMemoryDatabase?

### ISSUE THREAD

**Issue by hugoMencoboni** [dotnet/efcore#32199]
Do we have a way to use InMemoryDatabase with HierarchyId?

I'm testing the new [HierarchyId support of EF Core](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/hierarchyid?tabs=netcore-cli).

To enable that for SqlServerDatabase, we have to call `UseHierarchyId` when we setup the DbContext:

```cs
		services.AddDbContext<MyDbContext>(options =>
		{
			options.UseSqlServer(connectionString, x => x.UseHierarchyId());
		});
```

I have a Unit test projet that is using a InMemoryDatabase, but I don't find a way to add an equivalency of that `UseHierarchyId` that would allow me to unit test code that rely on HierarchyId. Do I miss something?

I think https://github.com/efcore/EFCore.SqlServer.HierarchyId/pull/33 was including that kind of capabilities in the [kmataru](https://github.com/kmataru)/[EFCore.SqlServer.HierarchyId](https://github.com/kmataru/EFCore.SqlServer.HierarchyId) project, but I don't find that code in https://github.com/dotnet/efcore/tree/main/src/EFCore.InMemory?

Without that support, I'm getting exceptions in my Unit tests:

```cs
using Microsoft.EntityFrameworkCore;

namespace HierarchyId.Tests;

public sealed class TestHierarchyIdTests
{
	public class Contact
	{
		public int Id { get; set; }
		public HierarchyId HierarchyId { get; set; }
	}
	public class MyDbContext : DbContext
	{
		public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
		{
		}

		public DbSet<Contact> Contacts { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
			modelBuilder.Entity<Contact>()
				.HasKey(c => c.Id);
			modelBuilder.Entity<Contact>()
				.HasIndex(x => x.HierarchyId)
				.IsUnique();
		}
	}

	[Fact]
	public async Task Test_HierarchyId()
	{
		var inMemoryDbOptions = new DbContextOptionsBuilder<MyDbContext>()
			.UseInMemoryDatabase("Test_HierarchyId")
			.Options;
		var context = new MyDbContext(inMemoryDbOptions);

		var contact = new Contact
		{
			HierarchyId = HierarchyId.Parse("/"),
		};
		await context.Set<Contact>().AddAsync(contact);
	}
}

```

```
  Message: 
System.InvalidOperationException : The entity type 'HierarchyId' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.

  Stack Trace: 
  Message: 
    System.InvalidOperationException : The 'HierarchyId' property 'Contact.HierarchyId' could not be mapped because the database provider does not support this type. Consider converting the property value to a type supported by the database using a value converter. See https://aka.ms/efcore-docs-value-converters for more information. Alternately, exclude the property from the model using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

  Stack Trace: 
    ModelValidator.ThrowPropertyNotMappedException(String propertyType, IConventionTypeBase typeBase, IConventionProperty unmappedProperty)
    ModelValidator.<ValidatePropertyMapping>g__Validate|7_0(IConventionTypeBase typeBase, <>c__DisplayClass7_0&)
    ModelValidator.ValidatePropertyMapping(IModel model, IDiagnosticsLogger`1 logger)
    ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
    InMemoryModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
    ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
    ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
    DbContextServices.CreateModel(Boolean designTime)
    DbContextServices.get_Model()
    <>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
    <32 more frames...>
    ServiceProviderEngineScope.GetService(Type serviceType)
    ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
    ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
    DbContext.get_DbContextDependencies()
    DbContext.get_ContextServices()
    DbContext.get_InternalServiceProvider()
    DbContext.get_DbContextDependencies()
    DbContext.Set[TEntity]()
    TestHierarchyIdTests.Test_HierarchyId() line 43
    --- End of stack trace from previous location ---
```

### Provider and version information

EF Core version: 8.0.0-rc.2.23480.1
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 8.0
Operating system: Microsoft Windows 11 Pro
IDE: Microsoft Visual Studio Professional 2022 (64-bit) - Preview

**Comment by ErikEJ** [comment]
@hugoMencoboni You should test heirarcyid against a database engine that supports it.

**Comment by ajcvickers** [comment]
@hugoMencoboni `HierarchyId` is a SQL Server feature and will never be implemented in the in-memory database. This is why we [recommend against using the in-memory database for testing](https://learn.microsoft.com/en-us/ef/core/testing/).

**Comment by hugoMencoboni** [comment]
Thanks @ErikEJ and @ajcvickers for that feedback!

Just want to be sure about what it implies: here I'm not really asserting anything on the HierarchyId. I just try to add in the context an entity that now uses a property of type HierarchyId.

Do we say that, if we have an existing solution that is using InMemoryDataBase for unit tests, and SQL Server in production, start using the HierarchyId type will require to either:
- stop unit testing any pieces of code that will end up adding an entity that uses that HierarchyId in our context
- change the entire Unit Test project to use a real SQL Server DB
- not use HierarchyId

Do we have a way to just let that entity being added in the in memory DB without throwing?

**Comment by ajcvickers** [comment]
@hugoMencoboni You can conditionally not map it but then the code you are testing is diverging even further from the code you are running in production.
