### ISSUE TITLE
EF Core 7 + Oracle database = TPT inheritance doesn't work

### ISSUE THREAD

**Issue by i-ORS** [dotnet/efcore#32206]
I am not sure Oracle provider means something in this expression, because I have an impression that the issue is in EF Core. I was not able to find any reports of this problem, so may be I just missed something obvious. I have 2 tables in Oracle, one "base" table with ID (which is generated by the database) and NAME and one "derived" table with ID (FK to the base table) and ANOTHERNAME. Corresponding entities look like this
```C#
[Table("BASE")]
public class Base
{
    [DataMember, Column("ID"), Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    [DataMember, Column("NAME"), Required]
    public string Name { get; set; }

}

[Table("DERIVED")]
public class Derived : Base
{
    [DataMember, Column("ANOTHERNAME"), Required]
    public string AnotherName { get; set; }
}
```
We have temporary Ids created at the client side for the entities, so EF model additionally configured to ignore it
```C#
public class BaseConfiguration : IEntityTypeConfiguration<Base>
{
    public void Configure(EntityTypeBuilder<Base> builder)
    {
        builder.Property(p => p.Id).Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Ignore);
    }
}
```
After we add new instance of Derived entity to the context and try to save changes, we getting the following error from Oracle: "ORA-01400: cannot insert NULL into (???)". The following SQL statement are actually generated and executed (I simplified them, leaving only meaningful part). EF correctly splits them into 2 separate batches. The first one
```
...
INSERT INTO "AAA"."BASE" ("NAME")
VALUES (:p3)
RETURNING "ID", INTO "lBASE_1"(1)."ID";
OPEN :cur0 FOR SELECT "lBASE"(1)."ID" FROM DUAL;
...
```
and the second one
```
INSERT INTO "AAA"."DERIVED" ("ANOTHERNAME")
VALUES (:p4)
RETURNING "ID" INTO "lDERIVED_0"(1)."ID";
OPEN :cur0 FOR SELECT "lDERIVED_0"(1)."ID" FROM DUAL;
```
As you may see the actual issue is with the second batch. EF doesn't insert ID from the base table to the SQL of the derived table, but instead it tries to return it as well, thinking it should be generated by the database.

After some debugging of EF Core code I can see the following in [ModificationCommand.cs](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Update/ModificationCommand.cs)
```C#
...
void HandleColumn(IColumnMappingBase columnMapping)
{
    var property = columnMapping.Property;  // <---- actually prop of the base class here
    var column = columnMapping.Column;
    var storedProcedureParameter = columnMapping is IStoredProcedureParameterMapping parameterMapping
        ? parameterMapping.Parameter
        : null;
    var isKey = property.IsPrimaryKey();
    var isCondition = !adding
        && (isKey
            || storedProcedureParameter is { ForOriginalValue: true }  
            || (property.IsConcurrencyToken && storedProcedureParameter is null));

    // Store-generated properties generally need to be read back (unless we're deleting).
    // One exception is if the property is mapped to a non-output parameter.
    var readValue = state != EntityState.Deleted
        && ColumnModification.IsStoreGenerated(entry, property) // <----  store generated is true for the base prop
        && (storedProcedureParameter is null || storedProcedureParameter.Direction.HasFlag(ParameterDirection.Output));
...
```
This method initialize command parameter and is called for all column mappings in the command. And column mappings for derived class in additional to the explicit column "ANOTHERNAME" contain implicit column "ID" which is the key from the base class (this is correct). But when it takes "property" from this mapping, it actually takes property of the base class with all related configurations (doesn't matter by attributes or in code). And obviously "readValue" will be true because ColumnModification.IsStoreGenerated returns true for the base ID property. And when readValue is true, it doesn't go to the command parameters list and instead "RETURNING" statement is generated for it.

AFAIR TPT inheritance in our project worked in EF Core 6 and stopped working in EF Core 7. But so far we didn't investigate this and instead refactored our code to avoid TPT. But now we at the point when we cannot do this and have to use TPT. So I am not sure if we just missed some additional configuration that need to be done in EF Core 7 for TPT or is this really a bug. Any help will be appreciated.

EF Core version: 7.0.13
Database provider: Oracle EF Core 7.21.12
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.7

**Comment by ajcvickers** [comment]
Please report this to Oracle, as they maintain the Oracle provider.

**Comment by i-ORS** [comment]
But did you read the text or only the title? The code I've provided at the end is from EF Core. This was not a bug report to EF Core but a question issue. I am looking for help to understand what is wrong. And your answer is very brief, it could means both - you investigated the issue and find it is an Oracle problem, or you just saw Oracle in the title and sent me there.

**Comment by ajcvickers** [comment]
@i-ORS It looks like a bug in the Oracle provider to me. If you think otherwise, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by i-ORS** [comment]
Hello @ajcvickers,
I created a simple test with SQLite and to me it looks like the behavior is the same there - https://github.com/i-ORS/TptTest
Executed SQL is
`      
INSERT INTO "BASE" ("NAME")
      VALUES (@p0);
      SELECT "ID"
      FROM "BASE"
      WHERE changes() = 1 AND "rowid" = last_insert_rowid();
...
      INSERT INTO "DERIVED" ("ANOTHERNAME")
      VALUES (@p0);
      SELECT "ID"
      FROM "DERIVED"
      WHERE changes() = 1 AND "rowid" = last_insert_rowid();
`

**Comment by ajcvickers** [comment]
Note for triage: It's not clear to me what the behavior should be for a value-generated column key which has been set to ignore the key value before save. It feels like it should behave the same way as without using `Ignore` when no value has been set for the key. Which would mean this is a bug. However, I'm not sure what that means in terms of FK fixup. Do we also ignore the value for that?
