### ISSUE TITLE
Contains fallback translation fails when the array parameter has AsQueryable

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#32218]
In the legacy translation mode for Contains with an array parameter source (e.g. for old SQL Server), our pattern matching fails when the parameter source is wrapped by AsQueryable. For normal cases, AsQueryable is removed by nav expansion as it's unnecessary (ParameterQueryRootExpression is already queryable); but there are certain cases where nav expansion does not visit (e.g. nested Contains, see #32217 for the full details).

As a workaround suitable for patching 8.0, we can simply recognize and unwrap AsQueryable in the Contains fallback logic.

**Comment by roji** [comment]
@ajcvickers this got fixed by the same PR (#32219) as #32215; I fixed both in a single PR since fixing #32215 caused failures requiring this issue to be fixed as well.

**Comment by ajcvickers** [comment]
@roji Sounds good. Let's leave them both open for now, and then close them both if/when the single PR is approved and merged for servicing.
