### ISSUE TITLE
Exception trying to use EF.Functions.StandardDeviationSample

### ISSUE THREAD

**Issue by awdorrin** [dotnet/efcore#32212]
The 'StandardDeviationSample' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server. 

```C#

    var stdDev = EF.Functions.StandardDeviationSample(_context.EmployeeData.Select(x => x.Value));
```

Am I doing something wrong, or is this just not getting translated to SQL properly?

### Include provider and version information

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0.0.20
Operating system: windows/linux
IDE: e.g. Visual Studio 2022 17.6.5

**Comment by roji** [comment]
@awdorrin you're trying to use the function outside of an EF query; this means that it gets evaluated like a regular .NET function, which isn't supported. Methods on EF.Functions only exist to be used within EF LINQ queries.

To use this in an EF LINQ query, you need to use GroupBy; to simply calculate the standard deviation over all rows (without actual groupings), do something like the following:

```c#
var stddev = await ctx.Blogs
    .GroupBy(b => 1)
    .Select(g => EF.Functions.StandardDeviationSample(g.Select(b => b.Value)))
    .SingleAsync();
```

**Comment by awdorrin** [comment]
Ah, thank you for your quick response, this makes sense the way you explained it.
Perhaps Microsoft can add your explanation as an example in their documentation to explain this. :-)

**Comment by roji** [comment]
@awdorrin yep, you're right - but EF currently requires GroupBy in order to do any custom aggregate functions (like stddev). Supporting this is tracked by #29200 (in the meantime, doing a SQL query is perfectly reasonable).
