### ISSUE TITLE
ValueConverter for entity.

### ISSUE THREAD

**Issue by xvxzvxzvxvzxcusernamegithubav** [dotnet/efcore#32222]
Given an table:

    MyEntity
    {
       public MyEnum MyType { get; set; }
       public DateTime MyDateTime { get; set; }
    }

I need to change the MyDateTime on reading and writing based on MyType I would try a ValueConverter<DateTime,DateTime> but this value converter has no acces to the MyType. 

How can I do this?

I did try to find some previous questions but for me it's not really clear whether this is possible or not.

**Comment by ajcvickers** [comment]
@xvxzvxzvxvzxcusernamegithubav Can you show what code you want to write and what should happen in the database when it executes?

**Comment by xvxzvxzvxvzxcusernamegithubav** [comment]
I just want to get all entities from the database. But based on the type I want to add one day to the date. (Basically to align different types of entities from some legacy systems). This would work with a converter if it was for all entities:

    public class MyConverter: ValueConverter<DateTime, DateTime>
    {
        public MyConverter() : base(x => x.AddDays(1), x=>x.AddDays(-1))
        {
        }
    }

And of course I can run this after or while querying the data but I would like to be completely ignorant of it in my code. I would like to have a single point of definition for this offset.

**Comment by ajcvickers** [comment]
@xvxzvxzvxvzxcusernamegithubav This isn't currently supported by value converters, but is tracked by #12205. Please vote (👍) for that issue.

**Comment by ajcvickers** [comment]
Duplicate of #12205

**Comment by xvxzvxzvxvzxcusernamegithubav** [comment]
Ok, i hope this scenario is covered by the duplicate.
