### ISSUE TITLE
An idea to add SQL Like Functionality in LINQ

### ISSUE THREAD

**Issue by garora** [dotnet/efcore#3225]
`This is not an issue, its just an idea of new feature, if not implemented till date.`
**_Is there any features list available?**_
Currently, there is no feature or support similar to `Like` functionality in `SQL`. However, we can use `Contains` to meet our requirements, which uses `in` at `SQL` side (dbengine). I am just thinking to add a new feature something similar to `sqllike` here is an example: [An idea to add SQL Like Functionality in LINQ](http://social.technet.microsoft.com/wiki/contents/articles/32244.an-idea-to-add-sql-like-functionality-in-linq.aspx).

Any thoughts/suggestions to add this feature? @shanselman @anurse  @srivatsn

**Comment by natemcmaster** [comment]
We already have this. 

https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Query/ExpressionTranslators/ContainsTranslator.cs

**Comment by garora** [comment]
Awesome! Good to know

**Comment by natemcmaster** [comment]
Thanks for the suggestion!
