### ISSUE TITLE
No idea how to make a simple migration using the source code

### ISSUE THREAD

**Issue by rlcarrierscsharp** [dotnet/efcore#32256]
I can't believe it is this difficult, but I all I want to do is add an ASP.NET Core MVC project to the EF solution and test it, that way I can step through the code as I am running the site. In order to do this, I created a basic SQL database and I am now trying to setup my first migration - this is where the all things go down hill.

I simply can't create one. I always get "Unable to retrieve project metadata. Ensure it's an SDK-style project."
I've tried setting the --msbuildprojectextensionspath and the --project path. It simply refuses to create a migration. I've never used Directory.Build.props - no idea why this is being used as it seems to create a bunch of headaches. I just want to create a migration in my ASP.NET Core project that I added to the All.sln. It really shouldn't be this hard.

**Comment by ajcvickers** [comment]
@rlcarrierscsharp Please post your csproj file.

**Comment by ajcvickers** [comment]
@rlcarrierscsharp You need to use EF Core through NuGet packages. It won't work to add references to downloaded source code projects. For SQL Server, add a reference to [Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer) and [Microsoft.EntityFrameworkCore.Design](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design) to use the tools.

You might want to go through some of the [getting started docs](https://learn.microsoft.com/en-us/ef/core/get-started/overview/install).

**Comment by rlcarrierscsharp** [comment]
I don't want to use EF Core through nuget packages though. I want to run a site using the EF core source code. I should be able to do that.

**Comment by roji** [comment]
@ricardobossan can you provide some background on why you want to use EF via source code? Nuget is the standard .NET packaging mechanism, and many things rely on it to work correctly.

**Comment by rlcarrierscsharp** [comment]
I like fully understanding how frameworks do what they do. I am more of a visual person, and a lot of what EF does just has a "This is a public API so we are not going to document it". So I want to be able to step into the code as it is running. For any other repo I can just point the projects to the source projects as references and achieve this. This is the first I've tried where it is not working, which seems to be due to some custom build setup that is over complicating things.

**Comment by rlcarrierscsharp** [comment]
So even if I imported the nuget packages, added the initial migration just to get the database stood up, and then added the project back into the All.sln and used the project references, are you saying that still would not work? I'm not trying to test the migration code, so that was just a convenience method to get everything stood up super quick.

**Comment by ricardobossan** [comment]
> @ricardobossan can you provide some background on why you want to use EF via source code? Nuget is the standard .NET packaging mechanism, and many things rely on it to work correctly.

@roji I think I was tagged by mistake here.

**Comment by ricardobossan** [comment]
> @ricardobossan you should be able to step into library code without referencing its sources; you need to disable "Just My Code" in the debugger, but other than EF is fully debuggable just like any other .NET library. In any case, even if you temporarily reference EF's source code to step into it, I'd strongly advise doing this as your regular way of using EF; you would also be able to use the CLI tools in the normal mode.
> 
> > For any other repo I can just point the projects to the source projects as references and achieve this. This is the first I've tried where it is not working, which seems to be due to some custom build setup that is over complicating things.
> 
> There are various other dependencies where this wouldn't work, e.g. anything relying on a source generator, just OTOH. The EF command-line tools used to generate a migration specifically aren't simply part of the library, so they involve certain additional complexity and reliance on the packages.

@roji I think I was tagged by mistake here. I believed you tried to tag @rlcarrierscsharp

**Comment by roji** [comment]
Thanks @ricardobossan, sorry for the noise!

**Comment by roji** [comment]
The EF command-line tools are unlikely to work well as long as you're referencing EF via project references; at the very least, AFAIK that's not something we've tested. Beyond that, EF itself probably will work fine, so at least in theory, you should be able to do everything except for run the CLI tool.

But once again, using project references is not the right thing to do for anything beyond a very temporary, specific debugging session (or similar), and you shouldn't need to run the CLI tools in that situation specifically.

**Comment by rlcarrierscsharp** [comment]
Well the plan was never to use entity framework core project references in a real project. I work for a very large company and I like to know exactly how all of the frameworks I'm using work. It is what allows me to be effective in both development and supporting features in production. That's the beauty of open source code - you can study it in its entirety while running the code. I am ok with not running the cli tools in this setup. I just want to be able to study the core EF codebase as I am running my test ASP.NET Core project.

**Comment by roji** [comment]
Sure, I think that should work fine - the problem really should be only with the CLI tools.

FWIW I also regularly run with project references to EF for certain scenarios, and that works just fine. But I do that mainly because I need to actually modify/play around with the EF code; just stepping through the code should be doable in a much easier way via regular debugging - VS (or whatever IDE you use) should support that just fine (but as mentioned above, you may have to disable "Just My Code", or enable external source debugging).

**Comment by rlcarrierscsharp** [comment]
I just wanted to report back that I successfully got everything working as you described, so thank you for that! As I said, being able to pick apart a framework is always important to me. I want to be so knowledgeable that I can become a contributor if I so desired. Speaking of which, I do have some questions regarding some of the internal code, which is not documented. I will probably open up a separate question for that.
