### ISSUE TITLE
How to Use EF Core Transactions With ASP.NET Core Identity Methods?

### ISSUE THREAD

**Issue by emre-bener** [dotnet/efcore#32263]
I use EF Core in my project, and I want to achieve atomicity when using built-in Identity methods (such as CreateAsync or AddClaimsAsync). Here is my use case:

```
#region CREATE USER & SET ROLE

var newUser = new ApplicationUser
{
    // set user properties here...              
};

var result1 = await userManager.CreateAsync(newUser);

var result2 = await userManager.AddClaimsAsync(newUser, new Claim[]{
                new Claim("asSuperUser", "asSuperUser")
});
#endregion

#region SEND ACCOUNT INITIALIZATION EMAIL

if (result1.Succeeded && result2.Succeeded)
{
    // continue if everything went fine...
```
    
Of course, if all goes well, there is no problem, but what if Identity failed to add claims to the added user (AddClaimsAsync method failed)? That would be bad news, because entire project revolves around CBAC (claims-based access control), so ensuring atomicity is crucial here. My question is: is there a way to make use of EF Core transactions when using Identity's built-in methods such as CreateAsync or AddClaimsAsync, where I'm not directly using the DbContext via DI, but rather using various Identity services (such as userManager) thus accessing DbContext indirectly?

Things would get even more complicated if I were using multiple Identity services (such as combining SignInManager and UserManager, where each scoped service instance would presumably create their own instance of DbContext)?

Target Framework: net7.0
`Microsoft.EntityFrameworkCore.SqlServer` Version="7.0.13"
`Microsoft.EntityFrameworkCore.Tools` Version="7.0.13"
`Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` Version="7.0.13"
`Microsoft.AspNetCore.Identity.EntityFrameworkCore` Version="7.0.12"

**Comment by emre-bener** [comment]
As it turns out, EF Core transactions can work with Identity service methods. Example:

```
using var transaction = await context.Database.BeginTransactionAsync();

// CREATE USER
var result1 = await userManager.CreateAsync(superUser);
if (!result1.Succeeded)
{
                await transaction.RollbackAsync();
                var errors1 = result1.Errors.Select(error => error.Description);
                return Json(new { success = false, error = string.Join(", ", errors1) });
}

// ASSIGN RELEVANT ROLE
var result2 = await userManager.AddClaimsAsync(superUser, new Claim[]{
                new Claim("asSuperUser", "asSuperUser")
});
if (!result2.Succeeded)
{
                await transaction.RollbackAsync();
                var errors2 = result2.Errors.Select(error => error.Description);
                return Json(new { success = false, error = string.Join(", ", errors2) });
}

await context.SaveChangesAsync();
await transaction.CommitAsync();
```

**Comment by roji** [comment]
@emre-bener yep, your code shows a good way to do this. Am going to go ahead and close this, but if you have further questions don't hesitate to post back here.
