### ISSUE TITLE
Error CS8103 : Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

### ISSUE THREAD

**Issue by harr1424** [dotnet/efcore#32261]
### Create a simple model class, one or two string properties will be sufficient: 
```C#
public class Post
{
    [Key]
    public string Title { get; set; }
    public string Content { get; set; }
}
```
### Implement logic to seed the database
[Microsoft Documentation for modelBuilder.hasData()](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding) 
```C#
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Blog.Models;
using Newtonsoft.Json;

public class PostContext : DbContext
    {
        public PostContext (DbContextOptions<PostContext> options)
            : base(options)
        {
        }

        public DbSet<Blog.Models.Post> Post { get; set; } = default!;
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Post>().HasData(SeedData());
        }

        public List<Post> SeedData()
        {
            var posts = new List<Post>();
            Assembly asm = Assembly.GetExecutingAssembly();
            var allFileNames = asm.GetManifestResourceNames();
            
            using (Stream resStream = asm.GetManifestResourceStream(allFileNames[0])) // embedded resource filename 
            {
                using (StreamReader r = new StreamReader(resStream))
                {
                    string json = r.ReadToEnd();
                    posts = JsonConvert.DeserializeObject<List<Post>>(json);
                }
            }
            return posts;
        }
    }
```

Note that the code above reads a .json file containing data that matches the `Post` model. There are over 3,000 entries, and the content of each post may contain tens of thousands of characters. I have embedded this file in the assembly in an attempt to avoid working with string literals, but as the section below demonstrates, EF Core will still generate a quantity of string literals that exceeds the limits of the Roslyn compiler. 

### Add an initial migration and inspect the script

Here I see thousands of long string literals: 
```C#
...
 migrationBuilder.InsertData(
                table: "Post",
                columns: new[] { "Title", "Content"},
                values: new object[,]
                {
                    { long string 1 },
                    { long string 2 },
                       ...
                 }
```

### Include the full exception message and stack trace for any exception you encounter.

```
0>CSC: Error CS8103 : Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.
0>------- Finished building project: Blog. Succeeded: False. Errors: 1. Warnings: 5
```

### Include verbose output
```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
CSC : error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals. [/Users/user/RiderProjects/Blog/Blog/Blog.csproj]
    5 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.18
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use dotnet build to see the errors.
   at Microsoft.EntityFrameworkCore.Tools.Project.Build()
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Build failed. Use dotnet build to see the errors.

```

## Why am I not opening this issue under roslyn or aspnetcore? 

Because other people already have, and the [roslyn team believes it is an issue for aspnetcore](https://github.com/dotnet/roslyn/issues/39676). Unfortunately, [aspnetcore  believes it is an issue for the roslyn team](https://github.com/dotnet/roslyn/issues/39676). So far, no one has attributed this error to a script generated by EF Core. It is unfortunate that the roslyn compiler is enforcing such a limit. Programmatically seeding 10MB of text from a JSON file isn't an edge case. The data has been embedded as an assembly resource which is appropriate for a larger file. EF Core generates a migration script which contains a quantity and length of user strings proportionate to the data stored in the embedded resource.As long as the roslyn compiler enforces this limit, EF Core is liable to generate string literals that exceed the limits of the compiler. 

Note that my project does not contain any other code than the boilerplate code created as part of a Razor Pages Web Application template. The problematic string literals can only be traced to the migration script. 

### Include provider and version information

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7.0
Operating system: Mac OS 14.0
IDE: Rider 2023.2.3 

### Similar Issues 
[https://github.com/dotnet/roslyn/issues/39676](https://github.com/dotnet/roslyn/issues/39676)
[https://github.com/dotnet/aspnetcore/issues/20224](https://github.com/dotnet/aspnetcore/issues/20224)

**Comment by harr1424** [comment]
https://github.com/dotnet/roslyn/issues/39676#issuecomment-1803111726

**Comment by roji** [comment]
@harr1424 we explicitly discourage using EF's HasData() feature to manage any sort of large data ([see docs](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding#limitations-of-model-seed-data)) - and 10MB certainly falls under that category. Regardless of  the specific issue you're reporting, managing 10MB of data via HasData() means that the data will be duplicated in a new model snapshot every time you add a new migration.

I highly recommend managing the seeding yourself in custom logic rather than doing it via Migrations and HasData().
