### ISSUE TITLE
Issues trying to connect to an existing database using beta7

### ISSUE THREAD

**Issue by etrigoco** [dotnet/efcore#3226]
I'm running beta7 for everything, including EF 7. I'm trying to connect to my remote existing database using the ASP.NET 5 Application template project. My project.json looks like this:

```
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-XXX-409e9e37-b7bb-4185-b7aa-6dc336087524",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-beta7",
    "EntityFramework.SqlServer": "7.0.0-beta7",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta7",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta7",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta7",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta7",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta7",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta7",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta7",
    "Microsoft.AspNet.Mvc": "6.0.0-beta7",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta7",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta7",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta7",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta7",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta7",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta7",
    "Microsoft.Framework.Logging": "1.0.0-beta7",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta7",
    "Microsoft.Framework.Logging.Debug" : "1.0.0-beta7",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta7"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],

  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],

  "scripts": {
   "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}
```

Doing a search online it seemed that in order to accomplish that I want I need to run the following command: 
`dnx ef dbcontext scaffold "ConnectionString" EntityFramework.SqlServer`

Which I could not do because I had an issue which was solved as explained here:
http://stackoverflow.com/questions/32781484/using-existing-database-with-asp-net-5-and-ef7-beta-7/32782634#32782634

Now I can finally get to run the command "dnx", but when I try running it with my connectionstring, which looks like this:
dnx ef dbcontext scaffold "Data Source=192.168.XX.XXX\devsql;Initial Catalog=Development;Integrated Security=False;User ID=system;Password=XXX;" EntityFramework.SqlServer

it gives me the following errors:

[ERROR] dnx : System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
[ERROR] En línea: 1 Carácter: 1
[ERROR] + dnx ef dbcontext scaffold "Data Source=192.168.XX.XXX\devsql;Initial Catalog=De ...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : NotSpecified: (System.InvalidO...,Version=v5.0'::String) [], RemoteException
[ERROR]     + FullyQualifiedErrorId : NativeCommandError
[ERROR]  
[ERROR]    EntityFramework.Commands 7.0.0-beta7
[ERROR]    EntityFramework.SqlServer 7.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.Cookies 1.0.0
[ERROR] -beta7
[ERROR]    Microsoft.AspNet.Authentication.Facebook 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.Google 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.Twitter 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Diagnostics 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta7
[ERROR]    Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta7
[ERROR]    Microsoft.AspNet.Mvc 6.0.0-beta7
[ERROR]    Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta7
[ERROR]    Microsoft.AspNet.Server.IIS 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Server.WebListener 1.0.0-beta7
[ERROR]    Microsoft.AspNet.StaticFiles 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Tooling.Razor 1.0.0-beta7
[ERROR]    Microsoft.Framework.Configuration.Abstractions 1.0.0-beta7
[ERROR]    Microsoft.Framework.Configuration.Json 1.0.0-beta7
[ERROR]    Microsoft.Framework.Configuration.UserSecrets 1.0.0-beta7
[ERROR]    Microsoft.Framework.Logging 1.0.0-beta7
[ERROR]    Microsoft.Framework.Logging.Console 1.0.0-beta7
[ERROR]    Microsoft.Framework.Logging.Debug 1.0.0-beta7
[ERROR]    Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta7
[ERROR] 
[ERROR] C:\XXX\XXX\src\XXX\project.lock.json(1,0): error: The expected lock file doesn't exist. Please run "dnu restore" to generate a new lock file.
[ERROR] Current runtime target framework: 'DNXCore,Version=v5.0 (dnxcore50)'
[ERROR]  Version:      1.0.0-beta7-15532
[ERROR]  Type:         CoreCLR
[ERROR]  Architecture: x64
[ERROR]  OS Name:      Windows
[ERROR]  OS Version:   6.1
[ERROR] 
[ERROR]    at Microsoft.Dnx.Runtime.DefaultHost.GetEntryPoint(String applicationName)
[ERROR]    at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
[ERROR]    at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
[ERROR] --- End of stack trace from previous location where exception was thrown ---
[ERROR]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[ERROR]    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
[ERROR]    at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
[ERROR]    at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
[ERROR]    at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
[ERROR] 

What am I doing wrong?

**Comment by natemcmaster** [comment]
Did you run `dnu restore`?
> [ERROR] C:\XXX\XXX\src\XXX\project.lock.json(1,0): error: The expected lock file doesn't exist. Please run "dnu restore" to generate a new lock file.

**Comment by erictrigo** [comment]
Yes I did, but it doesn't seem to do much. This is what the console command looks like when I run "dnu restore" and the scaffold script right after each other:

PS C:\XXX\XXX (Project folder)> dnu restore
Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta7-15532

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for C:\XXX\XXX\src\Titanes2015\project.json
  GET https://api.nuget.org/v3-flatcontainer/system.threading.threadpool/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.net.sockets/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.threading.threadpool/index.json 1389ms
  OK https://api.nuget.org/v3-flatcontainer/system.net.sockets/index.json 1287ms
Writing lock file C:\XXX\XXX\src\XXX\project.lock.json
Restore complete, 3517ms elapsed

NuGet Config files used:
    C:\Users\XXX\AppData\Roaming\NuGet\NuGet.Config
    C:\XXX\XXX\NuGet.Config

Feeds used:
    https://api.nuget.org/v3-flatcontainer/

PS C:\XXX\XXX> dnx ef dbcontext scaffold "Data Source=192.168.XX.XXX\devsql;Initial Catalog=Development;Integrated Security=False;User ID=system;Password=XXX;" EntityFramework.SqlServer
[ERROR] dnx : System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
[ERROR] En línea: 1 Carácter: 1
[ERROR] + dnx ef dbcontext scaffold "Data Source=192.168.XX.XXX\devsql;Initial Catalog=Dev ...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : NotSpecified: (System.InvalidO...,Version=v5.0'::String) [], RemoteException
[ERROR]     + FullyQualifiedErrorId : NativeCommandError
[ERROR]  
[ERROR]    EntityFramework.Commands 7.0.0-beta7
[ERROR]    EntityFramework.SqlServer 7.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.Cookies 1.0.0
[ERROR] -beta7
[ERROR]    Microsoft.AspNet.Authentication.Facebook 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.Google 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Authentication.Twitter 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Diagnostics 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta7
[ERROR]    Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta7
[ERROR]    Microsoft.AspNet.Mvc 6.0.0-beta7
[ERROR]    Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta7
[ERROR]    Microsoft.AspNet.Server.IIS 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Server.WebListener 1.0.0-beta7
[ERROR]    Microsoft.AspNet.StaticFiles 1.0.0-beta7
[ERROR]    Microsoft.AspNet.Tooling.Razor 1.0.0-beta7
[ERROR]    Microsoft.Framework.Configuration.Abstractions 1.0.0-beta7
[ERROR]    Microsoft.Framework.Configuration.Json 1.0.0-beta7
[ERROR]    Microsoft.Framework.Configuration.UserSecrets 1.0.0-beta7
[ERROR]    Microsoft.Framework.Logging 1.0.0-beta7
[ERROR]    Microsoft.Framework.Logging.Console 1.0.0-beta7
[ERROR]    Microsoft.Framework.Logging.Debug 1.0.0-beta7
[ERROR]    Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta7
[ERROR] 
[ERROR] C:\XXX\XXX\src\XXX\project.lock.json(1,0): error: The expected lock file doesn't exist. Please run "dnu restore" to generate a new lock file.
[ERROR] Current runtime target framework: 'DNXCore,Version=v5.0 (dnxcore50)'
[ERROR]  Version:      1.0.0-beta7-15532
[ERROR]  Type:         CoreCLR
[ERROR]  Architecture: x64
[ERROR]  OS Name:      Windows
[ERROR]  OS Version:   6.1
[ERROR] 
[ERROR]    at Microsoft.Dnx.Runtime.DefaultHost.GetEntryPoint(String applicationName)
[ERROR]    at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
[ERROR]    at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
[ERROR] --- End of stack trace from previous location where exception was thrown ---
[ERROR]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[ERROR]    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
[ERROR]    at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
[ERROR]    at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
[ERROR]    at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
[ERROR]

**Comment by rowanmiller** [comment]
@erictrigo given this seems to be an issue with restoring, resolving dependencies, etc. can you open up an issue in the DNX repo https://github.com/aspnet/DNX.
