### ISSUE TITLE
Best performance way to select large amount of data from a table

### ISSUE THREAD

**Issue by gokujax** [dotnet/efcore#32279]
I'd like to select data from a table has about 1M+ records for export. I'm using EF Core 7.0
Should I use SqlCommand, Raw Sql query, AsAsyncEnumerable, or there is another better way?

**Comment by ErikEJ** [comment]
@gokujax This is more of a StackOverflow question, but you can use any of these methods, but you should do it in batches or you will run out of memory.

**Comment by gokujax** [comment]
Thanks
