### ISSUE TITLE
ApplyConfigurationsFromAssembly is ordering config by class FullName instead by dependencies

### ISSUE THREAD

**Issue by ctrl-alt-d** [dotnet/efcore#32273]
`ApplyConfigurationsFromAssembly` loads class configurations by class name:

https://github.com/dotnet/efcore/blob/255d58facacbf65110f82bad2f0eef2794a12025/src/EFCore/ModelBuilder.cs#L519

This is a problem when the configuration of a model depends on the prior configuration of its base model.

I wrote here a sample, if you try to do migrations for the code bellow, an exception will be raised _"The property 'CustomerTypeId' cannot be added to the type 'Customer' because no property type was specified and there is no corresponding CLR property or field."_ Just changing class name from `A_Config` to `C_Config`, EF will be able to do the migration.

```C#
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public class CustomerType
{
    public int Id { get; set; }
    public IEnumerable<CustomerBase> Customers { get; set; } = default!;
}


public abstract class CustomerBase
{
    public int Id { get; set; }
    protected CustomerType _CustomerType = default!;
    public CustomerType CustomerType
    {
        get => _CustomerType;
    }
}

public class Customer : CustomerBase
{
}


public class MyTestContext : DbContext
{
    public DbSet<Customer> Customers { get; set; } = default!;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlite("Data Source=file:f1?mode=memory&cache=shared");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        Assembly assemblyWithConfigurations = GetType().Assembly;
        modelBuilder.ApplyConfigurationsFromAssembly(assemblyWithConfigurations);
    }
}

internal class B_Config
    : IEntityTypeConfiguration<CustomerBase>
{
    public void Configure(EntityTypeBuilder<CustomerBase> mConfiguration)
    {
        mConfiguration
            .HasOne(x => x.CustomerType)
            .WithMany(x => x.Customers)
            .HasForeignKey("CustomerTypeId");
    }
}
internal class A_Config  // <-- changing A_Config to C_Config makes the migration work
    : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> mConfiguration)
    {
        mConfiguration
            .HasBaseType<CustomerBase>()
            .HasIndex("CustomerTypeId");
    }
}

public class InheritanceIndexTest
{
    [Fact]
    public void CanMigrateTest()
    {
        // No test, just try to create migrations:
        // dotnet ef migrations add Initial
    }
}
```

This is because `Customer` has `CustomerBase` as base and needs a property of base model.

To solve the problem, it is sufficient to order the loading of configuration classes based on their dependencies instead of ordering them by their names.

Obviously, this is much easier said than done. In my opinion, this should be documented, or alternatively, the error message could be changed to provide hints about it: _The property 'CustomerTypeId' cannot be added to the type 'Customer' because no property type was specified and there is no corresponding CLR property or field. If this property is on base type, ensure that the name of the base model configuration class comes earlier in alphabetical order than that of the inherited model._

If this is not a bug, please, provide a way to deal with this issue. Thanks

EF Core version: 7.0.x
Database provider: Agnostic
Target framework: Net 7
Operating system: Agnostic
IDE: Agnostic

**Comment by ctrl-alt-d** [comment]
I would like to create a PR changing:

https://github.com/dotnet/efcore/blob/255d58facacbf65110f82bad2f0eef2794a12025/src/EFCore/ModelBuilder.cs#L519

with:

```csharp
        var constructibletypes = assembly.GetConstructibleTypes().OrderBy(t => string.Join(".", t.GetBaseTypes().Select(t => t.FullName)));
        foreach (var type in constructibletypes)
```

What do you think about?

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/22035

**Comment by AndriySvyryd** [comment]
Feel free to submit a PR that follows the design stated in https://github.com/dotnet/efcore/issues/22035. You can use https://github.com/dotnet/efcore/blob/a60c39995f9878a2efe59388670428b4b8275e08/src/Shared/Multigraph.cs#L126 to sort the configurations in topological order.

**Comment by ctrl-alt-d** [comment]
Hi @AndriySvyryd , thanks about fast reply. Sorry about dup.

I would like to know why it is not enough to sort configuration using chained class base names in alphabetical order. For example:

| class | inherits from | key order |
|--|---|--|
| Z | - | Z |
| P | Z | Z.P |
| O | P | Z.P.O |
| A | - | A |
| B | A | A.B |

Would be enough to loading configuration in `key order`?

| Order | class  | (key order) |
|--|--|--|
| 1st | A | A |
| 2nd| B | A.B |
| 3rd | Z | Z |
| 4th | P | Z.P |
| 5th | O | Z.P.O |

Thanks.

**Comment by AndriySvyryd** [comment]
@ctrl-alt-d While the base configuration is the most common ordering criteria, it's not the only one. For example, one could configure navigations to be required, but for this to work the relationship needs to be configured first and without a specific ordering this would need to be duplicated.
These kinds of dependencies cannot be found easily by EF, therefore providing `Predecessors` would allow to customize the order as necessary.

**Comment by ctrl-alt-d** [comment]
Hi Mr @AndriySvyryd ,I comprehend the value of the 'Predecessors' feature, and I acknowledge that my suggested solution does not encompass that functionality. The slight modification I propose, within my scenario, represents an enhancement to the current sorting and is not incompatible with the potential addition of explicit dependencies' declaration functionality in the future.

**Comment by AndriySvyryd** [comment]
Just changing the configuration order would be a breaking change for the users relying on the current order. So we need a way to apply the current order or to override it for a specific configuration.

**Comment by ctrl-alt-d** [comment]
Understood, appreciate, thanks about explanations. 🙌

**Comment by mwpowellhtx** [comment]
Has this been resolved and in which releases?
