### ISSUE TITLE
Unable to work with nvarcharr(max) code first - generated parameters for insert are length 4000

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#32274]
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

Unable to work with nvarcharr(max)

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

The following code is used to set up a property that is of type string:

        builder.Property(x => x.DataText)
            //.HasColumnType("nvarchar(max)")
            //.HasMaxLength(int.MaxValue)
            .IsUnicode();

Both configurations commented out have been tried.

The generated insert shows in .NET logging:

 (Size = 4000), 
 
 which is a limitation to 4000 characters. This is not what is defined in any combination and makes the use of nvarchar(max) unusable with standard operations.

Been fighting that for a day, asking wherver I come, and the general consensus is either a maxlengh or a columntype definition - both keep getting no change in behavior.

**Comment by roji** [comment]
> So, you tell me that the moment the string is longer, the variable will be a max? 

Yes, you can easily see this at work with a quick test such as the following:

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

ctx.Blogs.Add(new Blog { Name = "short string" });
await ctx.SaveChangesAsync();

ctx.Blogs.Add(new Blog { Name = new string('x', 3999) });
await ctx.SaveChangesAsync();

ctx.Blogs.Add(new Blog { Name = new string('x', 4001) });
await ctx.SaveChangesAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
```

This shows the following in the logs:

```
info: 11/11/2023 12:27:48.009 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Blogs] (
          [Id] int NOT NULL IDENTITY,
          [Name] nvarchar(max) NULL,
          CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
      );
info: 11/11/2023 12:27:48.168 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (34ms) [Parameters=[@p0='short string' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Blogs] ([Name])
      OUTPUT INSERTED.[Id]
      VALUES (@p0);
info: 11/11/2023 12:27:48.217 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (7ms) [Parameters=[@p0='xxxx...' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Blogs] ([Name])
      OUTPUT INSERTED.[Id]
      VALUES (@p0);
info: 11/11/2023 12:27:48.229 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (6ms) [Parameters=[@p0='xxxx...' (Size = -1)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Blogs] ([Name])
      OUTPUT INSERTED.[Id]
      VALUES (@p0);
```

In other words, EF sets the size on parameters to 4000 when the value is 4000 or less, otherwise the size is "max".

**Comment by NetTecture** [comment]
Thanks. had me worried for a moment.
