### ISSUE TITLE
'The property is configured as an EF8 primitive collection. Primitive collections in a Cosmos model are discovered by convention

### ISSUE THREAD

**Issue by xvanneste** [dotnet/efcore#32307]
How to create a simple object like this 

```C#
public class User:BaseModel
{
    public Uri? ImageProfile { get; set; }
    public Setting? Settings { get; set; }
    public List<Guid>? Cars { get; set; }
    public List<UserChargingStation>? Stations { get; set; }
    public string? PayPalVaultID { get; set; }
}
```

and this on context 
```C#
var user = modelBuilder.Entity<User>();
user.ToContainer(nameof(Users))
    .HasNoDiscriminator()
    .HasPartitionKey(u => u.Id)
    .HasKey(u => u.Id);
```

On EntityFramework 7 this work on the EF8 I have this error
System.InvalidOperationException: 'The property 'User.Cars' is configured as an EF8 primitive collection. Primitive collections in a Cosmos model are discovered by convention.'

How configure and use PrimitiveCollection with Cosmos ?

**Comment by ajcvickers** [comment]
I am not able to reproduce this working in EF7--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseCosmos(
                    "https://localhost:8081",
                    "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
                    "PointReads")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var user = modelBuilder.Entity<User>();
        user.ToContainer("Users")
            .HasNoDiscriminator()
            .HasPartitionKey(u => u.Id)
            .HasKey(u => u.Id);
    }
}

public class User:BaseModel
{
    public Uri? ImageProfile { get; set; }
    public List<Guid>? Cars { get; set; }
    public string? PayPalVaultID { get; set; }
}

public class BaseModel
{
    public Guid Id { get; set; }
}
```

**Comment by xvanneste** [comment]
Yes on EF 7 No problem but if I migrate to .Net 8 and EF 8 I have this issue.

**Comment by ajcvickers** [comment]
@xvanneste The code I posted throws on EF7. Can you post runnable code that works on EF7 but throws on EF8?

**Comment by Manu06D** [comment]
hi @ajcvickers , 

here's a small project where you can reproduce the error : https://github.com/Manu06D/Bug-EFCore32307/

Simply launch web site, go to API and Init method .. You'll get the following error : 
System.InvalidOperationException: The property 'Car.Properties' is configured as an EF8 primitive collection. Primitive collections in a Cosmos model are discovered by convention. It's raised on a database save.

Changing the Properties from List<Guid> to List<string> will not trigger the error.

The error has appeared between version 8.0.0-rc.2.23480.1 and 8.0.0 . There's the branch with rc packages that is working properly.

**Comment by ajcvickers** [comment]
@Manu06D This project still throws for me when using EF Core 7. Can you please post a project that works on EF7 and fails on EF8?

```
Unhandled exception. System.InvalidOperationException: The entity type 'List<Guid>' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model, IDiagnosticsLogger`1 logger)
```

**Comment by Manu06D** [comment]
@ajcvickers , you're right, the code is not working with EF7. Was just working with EF8 beta/rc ! Sorry :)
