### ISSUE TITLE
[EF Core 8] Understand why depencies to Microsoft.Identity.* packages

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#32313]
Hello guys, i notice when I reference the packages Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore 8.0.0, i have these dependencies also installed on my project : Microsoft.Identity.Client.dll, Microsoft.Identity.Client.Extensions.Msal.dll, Microsoft.IdentityModel.Abstractions.dll, Microsoft.IdentityModel.JsonWebTokens.dll, Microsoft.IdentityModel.Logging.dll, Microsoft.IdentityModel.Protocols.dll, Microsoft.IdentityModel.Protocols.OpenIdConnect.dll, Microsoft.IdentityModel.Tokens.dll, System.IdentityModel.Tokens.Jwt.dll.

My project don't need identity, It would be better for example to have a package EntityFrameworkCore.Identity which people can reference or not to have the identity layer. 

Moreover, the version referenced are quite old, its the 6.24 from 13/10/2022. this situation lead to some side effect, with these old dll was copied next to a project which this last one was referenced the Microsoft.IdentityModel.JsonWebTokens.dll but the last version, the 7.0.3. This created a dll mismatch in my main app, it was very unfortunate.

Do you think you can make something about that ? (i you can't split these dll for nows, at least upgrade the dependencies)

thanks !

**Comment by roji** [comment]
These dependencies are brought in by [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) - EF has nothing to do with them. If you try a different EF database provider (e.g. SQLite or PostgreSQL) you won't see them.

SqlClient is maintained in [this repo](https://github.com/dotnet/SqlClient).

**Comment by julienGrd** [comment]
https://github.com/dotnet/SqlClient/issues/2218
