### ISSUE TITLE
RevEng: Address Schema/Table Names which Selection currently does not handle

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#3232]
At the moment there are a small set of schema/table names that the table selection algorithm can't handle. See https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational.Design/ReverseEngineering/Internal/TableSelectionSetBuilder.cs#L9. 

This issue is to come up with a workaround for those.

**Comment by rowanmiller** [comment]
No longer needed after decisions form yesterdays design meeting
