### ISSUE TITLE
EntityTypeAttributeConventionBase disappearance from EF7 to EF8

### ISSUE THREAD

**Issue by hawk2000** [dotnet/efcore#32322]
Is there any reason to the disappearance of EntityTypeAttributeConventionBase from EF7 to EF8 or any other equivalent one is used as replacement of that one?

I'm trying to migrate a project to Net 8 and I found out that this class is missing.

EF Core version: 8
Target framework: NET 8

**Comment by ajcvickers** [comment]
@hawk2000 Use `TypeAttributeConventionBase` instead. It now supports complex types as well as entity types.
