### ISSUE TITLE
Unnecessary `SELECT` wrapper around executed SQL

### ISSUE THREAD

**Issue by Atulin** [dotnet/efcore#32327]
Example code with EF Core 8:

```cs
var quote = await context.Database.SqlQueryRaw<QuoteDt
    	SELECT q."Author", q."Body"
    	FROM "Quotes" q
    	OFFSET floor(random() * (
    	    SELECT count(*)
    	    FROM "Quotes"
    	))
    	LIMIT 1
    """)
    .FirstOrDefaultAsync(cancellationToken);
```

will generate the following SQL query:

```sql
SELECT o."Author", o."Body"
FROM (
        SELECT q."Author", q."Body"
        FROM "Quotes" q
        OFFSET floor(random() * (
            SELECT count(*)
            FROM "Quotes"
        ))
        LIMIT 1
) AS o
LIMIT 1
```

that, as you can see, contains basically a passthrough `SELECT` that doesn't do much.

If I understand it correctly, the purpose of it is so that we can chain further EF methods from that raw query. The query gets contained inside, and the outside code is what EF generates, which makes sense as a decent workaround.

However, it would be nice to just get rid of those wrappers in simple cases, such as the above.

**Comment by roji** [comment]
@Atulin EF has no way of knowing that your SQL string already contains `LIMIT 1`; EF does not parse your SQL.

**Comment by Atulin** [comment]
No, I'm not seeing any difference in performance (although I haven't benchmarked it thoroughly), it's purely the difference of having 4 more lines and one more level of indentation in the logs that doesn't need to be there.

**Comment by roji** [comment]
@Atulin you could omit the LIMIT 1 from your SQL, given that you're expressing it outside via FirstOrDefaultAsync(). Or to be more convoluted, you could place AsEnumerableAsync() before FirstOrDefaultAsync() outside, in which case EF doesn't see it and doesn't add a LIMIT 1.

Otherwise I don't see what else can be done.

**Comment by Atulin** [comment]
Oh well, no big deal. You're right that I can remove the limit, though
