### ISSUE TITLE
EFC 8.0: Precompiled model: Error CS0041 Unexpected error writing debug information -- 'Insufficient memory to continue the execution of the program.' 

### ISSUE THREAD

**Issue by ennemoser-mobile** [dotnet/efcore#32321]
Hello there,

with EFC 8.0.0 the precompiled model seems to be much much larger.

In our example the auto-generated [YourName]DbContextModelBuilder.cs went from 3700 lines to over 70000 lines.

It is mostly this newly generated "CreateRelationalModel" method, that spans over many many lines of code.

```Csharp
       private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);
            ...
```

This results in following compilation error when building the project:
Error CS0041 Unexpected error writing debug information -- 'Insufficient memory to continue the execution of the program.' 

What is the maximum number of entities supported per DbContext?

As a workaround I can remove the precompiled model and try to split up the DbContext.

Thanks :)
Paul

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0.0
Operating system: Windows 11 23H2
IDE: Visual Studio 2022 17.8

**Comment by last-Programmer** [comment]
We are also getting this error

Workaround what we are doing now

in csproj file
`
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
`

Any other alternate ways to fix this?

Thanks

**Comment by ajcvickers** [comment]
Note for triage: covered by #31370.

**Comment by last-Programmer** [comment]
This leads to some more issues
We are using this large precompiled model in asp.net core 8 and in windows services.

The cold init time for asp.net core 8 with ef core 8 is very much longer than using ef core 7.0
the windows service is not starting sometimes when we use ef core 8 which was starting fast when we are using ef core 7.

We rollbacked to ef core 7 at present because of these issues. 

Hope we get a fix for this in the next upcoming releases

Thank You

**Comment by ennemoser-mobile** [comment]
> We are also getting this error
> 
> Workaround what we are doing now
> 
> in csproj file `<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'"> <DebugType>none</DebugType> </PropertyGroup> <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'"> <DebugType>none</DebugType> </PropertyGroup>`
> 
> Any other alternate ways to fix this?
> 
> Thanks

Thanks, using this workaround for now.
