### ISSUE TITLE
Using new[] in select query gives exception .NET 8

### ISSUE THREAD

**Issue by Ogglas** [dotnet/efcore#32331]
### Include your code

I could not find anything about this and therefore decided to post this. 

This code worked with .NET 7 and Microsoft.EntityFrameworkCore.SqlServer Version 7.0.13:

`Updated = p.ThreatAndCountermeasures.Count() > 0 ? new[] { p.Updated, p.ThreatAndCountermeasures.Max(tac => tac.Updated) }.Max() : p.Updated,`

With .NET 8 and Microsoft.EntityFrameworkCore.SqlServer Version 8.0.0 I get the following exception:

> Query root of type 'InlineQueryRootExpression' wasn't handled by provider code. This issue happens when using a provider specific method on a different provider where it is not supported.

If I use this code it works:

`Updated = p.ThreatAndCountermeasures.Count() > 0 ? new List<DateTime> { p.Updated, p.ThreatAndCountermeasures.Max(tac => tac.Updated) }.Max() : p.Updated,`

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Windows 11 Pro OS build 22621.2506
IDE: Microsoft Visual Studio 2022 (64-bit) - Current Version 17.8.0

**Comment by roji** [comment]
Minimal repro query:

```c#
_ = context.Blogs
    .Select(b => new[] { b.Updated, b.Posts.Max(p => p.Updated) }.Max())
    .ToList();
```

<details>
<summary>Full repro source code</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

_ = context.Blogs
    .Select(b => new[] { b.Updated, b.Posts.Max(p => p.Updated) }.Max())
    .ToList();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public DateTime Updated { get; set; }
    public DateTime Updated2 { get; set; }
    public List<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public DateTime Updated { get; set; }

    public Blog Blog { get; set; }
}
```

</details>

In 7.0 this indeed translated, with the outer Max() evaluated client-side:

```sql
SELECT [b].[Updated], (
    SELECT MAX([p].[Updated])
    FROM [Post] AS [p]
    WHERE [b].[Id] = [p].[BlogId])
FROM [Blogs] AS [b]
```

This only fails when a subquery is inside the inline collection. Given the following LINQ query:

```c#
_ = context.Blogs
    .Select(b => new[] { b.Updated, b.Updated2 }.Max())
    .ToList();
```

... 8.0 produces the following, translating the outer Max() to SQL:

```sql
SELECT (
    SELECT MAX([v].[Value])
    FROM (VALUES ([b].[Updated]), ([b].[Updated2])) AS [v]([Value]))
FROM [Blogs] AS [b]
```

... whereas 7.0 again evaluates client-side:

```sql
SELECT [b].[Updated], [b].[Updated2]
FROM [Blogs] AS [b]
```

Opened #32332 to improve the 8.0 translation to use `GREATEST()`.

**Comment by roji** [comment]
Reopening to consider servicing.
