### ISSUE TITLE
[PostgreSQL] Add support for AT TIME ZONE

### ISSUE THREAD

**Issue by fabio-stein** [dotnet/efcore#32340]
I have a table with data stored in UTC timestamptz, I want to select and group by date using a specific timezone on each execution. 
As far as I did read, using the operation "AT TIME ZONE" in Postgres seems to be the most ideal solution.
I see that for SQL Server, EF already have the function implemented in #26199 

Can we have **EF.Functions.AtTimeZone** used in PostgreSQL?

**Comment by roji** [comment]
Have you tried using TimeZoneInfo.ConvertTimeBySystemTimeZoneId() as listed in the [docs](https://www.npgsql.org/efcore/mapping/translations.html#date-and-time-functions)? Did you run into any issues?

**Comment by roji** [comment]
Note also that this is the EF repo - Npgsql-specific issues belong in https://github.com/npgsql/efcore.pg. Am going to close this as external, but if you can't make it work with ConvertTimeBySystemTimeZoneId() please open an issue over there with a minimal, runnable repro.
