### ISSUE TITLE
DbContext Scaffold : The specified deps.json does not exist

### ISSUE THREAD

**Issue by sergedevillez** [dotnet/efcore#32358]
### How to recreate :

- Create a Blazorwebassembly project in Visual Studio
- Install the following nugget packages : Microsoft.EntityFrameworkCore.Design, Microsoft.EntityFrameworkCore.SqlServer (if on Visual studio, add Microsoft.EntityFrameworkCore.Tools)
- Use the following command to initiate a reverse engineering
```
Scaffold-DbContext 'myDataSource' Microsoft.EntityFrameworkCore.SqlServer
```

### Stack traces
```
Build started...
Build succeeded.
The specified deps.json [C:\Users\<me>\source\repos\Private\<projectApp>\<project>\bin\Debug\net8.0\<project>.deps.json] does not exist
```

### Verbose output
```
Using project '<project>'.
Using startup project '<project>'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\<me>\source\repos\Private\<projectApp>\<project>\bin\Debug\net8.0\<project>.deps.json --additionalprobingpath C:\Users\<me>\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files (x86)\Progress\ToolboxNuGetPackages" C:\Users\<me>\.nuget\packages\microsoft.entityframeworkcore.tools\8.0.0\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold Name=ConnectionStrings:<database> Microsoft.EntityFrameworkCore.SqlServer --json --verbose --no-color --prefix-output --assembly C:\Users\<me>\source\repos\Private\<projectApp>\<project>\bin\Debug\net8.0\<project>.dll --project C:\Users\<me>\source\repos\Private\<projectApp>\<project>\<project>.csproj --startup-assembly C:\Users\<me>\source\repos\Private\<projectApp>\<project>\bin\Debug\net8.0\<project>.dll --startup-project 
C:\Users\<me>\source\repos\Private\<projectApp>\<project>\<project>.csproj --project-dir C:\Users\<me>\source\repos\Private\<projectApp>\<project>\ --language C# --configuration Debug --working-dir C:\Users\<me>\source\repos\Private\<projectApp> --root-namespace <project> --nullable
The specified deps.json [C:\Users\<me>\source\repos\Private\<projectApp>\<project>\bin\Debug\net8.0\<project>.deps.json] does not exist
```

### Provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer version 8.0.0
Target framework: .Net 8.0.0
Operating system: Windows
IDE: Visual Studio Preview 2022 Professionnal (17.9.0 preview 1.0)
Others IDE tested : Visual Studio 2022 Professionnal (17.8.0), Visual Studio 2022 Community (17.8.0) and Visual Studio Code (1.84.2, 64x)

### What I have tested
- Closing the IDE, restarting
- Opening the same project on another IDE (see above)
- Recreating the project from scratch
- Using the .Net Core CLI (both on VS and VS Code) in place of the Package Manager Console
- Removing and adding again the nugget packages

### Notes
1. The only issue close to this one I could find here was [16386](https://github.com/dotnet/efcore/issues/16386) but I did not see any fix mentionned (other than removing the Azure Development package ?)
2. It seems someone had this problem on .Net  and opened a ticket and was given a workaround [github](https://stackoverflow.com/questions/74948605/how-do-i-fix-the-error-the-specified-deps-json-does-not-exist-for-a-net-6) but I haven't tested yet (necessite to create a console project and use it for the first migration)
3. Yesterday, I used the same (to my knoledge, I may have missed something) steps to create the scaffolding and did not face any problem.
4. For the third step, I have tested : 
- with --output-dir and --context-dir options added too on both PMC and CLI
- with data source in clear in the command and hidden in user-secrets

**Comment by envoydb** [comment]
This issue is likely persisting for as long as it has (years) because of an ongoing misplaced dependency on build tools. A project that you're scaffolding into, won't be built because it needs the scaffolded components in order to build.

There is no genuine requirement for the project to build prior. Once that sinks in, this " the specified deps.json does not exist" bug goes away permanently.

**Comment by ErikEJ** [comment]
@envoydb You can have additional code im your project that can be Executed during scaffolding - this requires the project to be built. 

With "dotnet ef dbcontext scaffold" You have the --no-build option

**Comment by envoydb** [comment]
> @envoydb You can have additional code im your project that can be Executed during scaffolding - this requires the project to be built.
> 
> With "dotnet ef dbcontext scaffold" You have the --no-build option

And if you use the --no-build option, you encounter the "the specified deps.json does not exist" bug, so suggesting --no-build is not a realistic response.

As I will suggest again, the thinking on this is backwards. Building should not be the default. Once you remove that idea from your head this deps.json bug goes away naturally because suddenly you will be forced to ensure that there is no reliance on it.

In real world scenarios where there is a lot of active development happening the project has a lower chance of building successfully than the imaginary scenarios this was developed for.
Having to run a separate project in a separate repo just to scaffold before copying files into the main repo is about the silliest requirement I've heard in decades.

**Comment by Chris-Dickerson** [comment]
**Command**:
`dotnet ef dbcontext scaffold "Host=127.0.0.1;Database=data;Username=postgres;Password=password" Npgsql.EntityFrameworkCore.PostgreSQL --output-dir Database\Primary --context PrimaryModel --force --verbose --no-build --use-database-names --no-onconfiguring`

**Error**:
The specified deps.json [D:\<path>\<project>\bin\Debug\net8.0-windows\<project>.deps.json] does not exist

**BIN Path**:
D:\<path>\<project>\bin\x64\Debug\net8.0-windows

**Fix**:
Copy the "Debug" folder to "bin" (_same level as the platform folder_)

**Comment by TJaenichen** [comment]
Remove the --verbose

**Comment by Chris-Dickerson** [comment]
> Remove the --verbose

Nope, doesn't help to provide the "deps.json" file that it wants.
