### ISSUE TITLE
Special folders as file location for DB

### ISSUE THREAD

**Issue by Hermansson** [dotnet/efcore#32380]
Hi.

I am trying to deploy a database on my MAUI app, currently testing on my local Windows laptop.
Ex:
```
 var folder = Environment.SpecialFolder.ApplicationData;
 var path = Environment.GetFolderPath(folder);

 var dbPath = Path.Join(path, "app.db3");

 services.AddDbContext<ExerciseDBContext>(
options => options.UseSqlite($"Filename={dbPath}", builder => 
    builder.MigrationsAssembly(Assembly.GetExecutingAssembly().GetName().Name)));
```

Fore some reason the db file do not end up in my special folder (C:\Users\myuser\AppData\Roaming). This is where it should end up according to the inspector, I place a breakpoint to examine `dbPath `.

If I change to var `path = "C:\temp"`, sure enough the file pops up as expected.

Is there some limitation I need to be aware of? The idea is to use "SpecialFolder.ApplicationData" to ensure my db can be created correctly regardless if I'm running Android or Windows.

I'm runing .Net 8 and efcore 8.

**Note that the app still works**, I do not know where the file is created.

**Comment by Hermansson** [comment]
![image](https://github.com/dotnet/efcore/assets/6293155/69c34148-2e1d-4cf1-a8dc-6542a622df6d)

This a screenshot from the actual db context in runtime, the path looks correct to me? But the folder is empty when I browse it.

**Comment by ajcvickers** [comment]
> Is there some limitation I need to be aware of?

EF and SQLite have no limitations here. It's possible that the MAUI platform does; I would suggest following up there.
