### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite how to prevent all the runtime binaries from being emitted?

### ISSUE THREAD

**Issue by catmanjan** [dotnet/efcore#32382]
We have a project which only runs on windows x64 and uses Microsoft.EntityFrameworkCore.Sqlite

I notice in the bin folder there are sqlite dependencies for just about every computer on earth... How can we prevent these from being emitted?
![image](https://github.com/dotnet/efcore/assets/137350/83226066-11af-4ae3-ac2b-be86a64056bf)

**Comment by ajcvickers** [comment]
@catmanjan This is the way MSBuild and NuGet work. You could try following up with those teams, but I don't expect it will change anything.

**Comment by catmanjan** [comment]
@ajcvickers other libraries like IKVM will pick up the RuntimeIdentifier setting in the csproj file and only emit the binaries for the selected runtimes - why can't efcore?

I've logged issues with msbuild here https://github.com/dotnet/msbuild/issues/9451 and nuget here https://github.com/NuGet/Home/issues/13039
