### ISSUE TITLE
[EF Core 8] Many-to-many relationship with payload

### ISSUE THREAD

**Issue by GiannhsR** [dotnet/efcore#32381]
Hi all,

I am trying to create a many-to-many relationship as described in https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-and-join-table-with-payload

My models are the following:
```
public class Post
{
    public int Id { get; set; }
    public List<Tag> Tags { get; } = new();
    public List<PostTag> PostTags { get; } = new();
}

public class Tag
{
    public int Id { get; set; }
    public List<Post> Posts { get; } = new();
    public List<PostTag> PostTags { get; } = new();
}

public class PostTag
{
    public int PostId { get; set; }
    public int TagId { get; set; }
    public string CustomPayload { get; set; }
}
```
MyDbContext:
```
public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }
    public virtual DbSet<Post> Posts { get; set; }
    public virtual DbSet<Tag> Tags { get; set; }
}
```
when I try to create the initial migration I get the following error:
```
Unable to create a 'DbContext' of type ''. The exception 'The entity type 'PostTag' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'
```
When adding a primary key on the `PostTag` model:
```
Unable to create a 'DbContext' of type ''. The exception 'Cannot use table 'PostTag' for entity type 'PostTag' since it is being used for entity type 'PostTag (Dictionary<string, object>)' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'PostTag' on the primary key properties and pointing to the primary key on another entity type mapped to 'PostTag'.
```
I have a few questions:

1) What am I missing and cannot make this relationship function?
2) Even if somehow the tables are produced from the migration, will the `PostTag` table be able to return the `CustomPayload ` and how?
3) Is this supposed to be the correct way to supply the join table with a `user defined payload` ?

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system: Windows 10
IDE:  Visual Studio 2022 17.8.0

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
@GiannhsR Your code does not include configuration of the join table. For example:

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Post>()
		.HasMany(e => e.Tags)
		.WithMany(e => e.Posts)
		.UsingEntity<PostTag>();
}
```
