### ISSUE TITLE
[EF Core 6] EFCore.SqlServer uses EOL version of Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by Dahlorna** [dotnet/efcore#32395]
## Update  Microsoft.Data.SqlClient reference to supported version on EF Core 6?

Hi,
First time opening an issue, so forgive me if I'm not following correct format.

I was updating package refs of my project when
I noticed that current newest version of EF Core (v.6.0.25) is still referencing EOL version of Microsoft.Data.SqlClient in  **[EFCore.SqlServer.csproj](https://github.com/dotnet/efcore/blob/v6.0.25/src/EFCore.SqlServer/EFCore.SqlServer.csproj)**
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.4" />
  </ItemGroup>
```
The 2.1.x version of Microsoft.Data.SqlClient reached it's end of support few days ago (Nov 20, 2023) based on what is listed in here
https://learn.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver16#actively-supported-releases

So should that by bumped by efcore project and why that is not been bumped for few years (2.1.6 is the newest version of the client)? I also found this documentation page https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli and I'm bit confused about the tip written in there:
```
The Microsoft.Data.SqlClient package ships more frequently than the EF Core provider. If you would like to take advantage of new features and bug fixes, you can add a direct package reference to the latest version of Microsoft.Data.SqlClient.
```
So one could use even 5.1 version of Microsoft.Data.SqlClient with EF Core v6.0.25 and that works and is supported usage? Or does it mean newest version of that GA release which is referenced in SqlServer nuget package?

### Include provider and version information

EF Core version: **v6.0.25**
Database provider: **Microsoft.EntityFrameworkCore.SqlServer**
Target framework: **.NET 6.0**
Operating system: **n/a**
IDE: **n/a**

**Comment by ajcvickers** [comment]
> So one could use even 5.1 version of Microsoft.Data.SqlClient with EF Core v6.0.25 and that works and is supported usage?

Yes. We don't have any control over the SqlClient packages, so you will frequently need to manually update to the latest package.

**Comment by ErikEJ** [comment]
As stated in the docs, actually

**Comment by Dahlorna** [comment]
> > So one could use even 5.1 version of Microsoft.Data.SqlClient with EF Core v6.0.25 and that works and is supported usage?
> 
> Yes. We don't have any control over the SqlClient packages, so you will frequently need to manually update to the latest package.

Thanks for the fast reply. I understand that you don't have control over what is included or when new packages of SqlClient are published, but you can control which version you have a reference. 
I see dependabot updating SqlClient references in v7.0 versions of EF Core but not in v6.0. Is there a reason for that?
And now when 2.1.X of SqlClient is end of support should you update the package ref as now by default the users will get outdated (and not supported) version of SqlClient when using latest version of EF Core 6?

**Comment by ajcvickers** [comment]
@Dahlorna The team does not decide these things.

**Comment by Dahlorna** [comment]
> @Dahlorna The team does not decide these things.

so you don't decide what is gonna be here in future releases of EF Core SqlServer?
![image](https://github.com/dotnet/efcore/assets/5716225/f63191d4-885e-486a-9b29-ee91381a477e)

Then who does?

**Comment by ajcvickers** [comment]
Management.

**Comment by cssatkmd** [comment]
What does "Management" mean in this context? My understanding of Microsoft is, that it is a fairly technical organisation, so I would assume "Management" has some idea what they are talking about, but also listens to teams/people of interest, who has something to say about this?
