### ISSUE TITLE
How can I use built In-Memory Cache for INSERT queries?

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [dotnet/efcore#32409]
Since there are no changes in the [ChangeTracker ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker?view=efcore-7.0) in EF core `SELECT` queries, I can use the built [Cache in-memory in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-7.0) without any problems. 

However, when I add a new model to the database by fetching from the cache instead of the database, and set this cached data to the model's navigation properties, `ChangeTracker` cannot detect changes to the new data, or `ChangeTracker` creates new `INSERT` queries include the exist. So I can't use caching properly.

I don't want to use a different 3rd party library. Why isn't there any mechanism in EF Core to support `INSERT` queries from cache?

**Comment by roji** [comment]
@g-u-r-k-a-n it's not completely clear to me what you were asking above, I'm assuming that since you closed the question you found an answer for it. If that's not the case, post back here with more details and we can revisit.
