### ISSUE TITLE
Table splitting: Support mapping to the same table/column as another entity/entity's property.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32406]
When entity splitting is set up, I have to specify the same name of the table. This is error prone. But it can be even wore.

I want to have a small projection of `AspNetUsers` table (just Id and Name).
My `AppDbContext` inherits from `IdentityContext`, so I must know the exact table (and scheme) `IdentityUser` entity is mapped to.
Likewise, I need the exact mappings of its properties. Not nice.

So, instead of `builder.ToTable(tableName)` I'd prefer to have something like this `builder.ToTable<TOtherEntity>()`.

And for properties:

`builder.Property(_ => _.Name).SameAs<IdentityUser>(_ => _.UserName);`

**Comment by roji** [comment]
@voroninp you can already get the table name for your other entity by using regular model APIs (i.e. `model.GetEntityType(typeof(TOtherEntity)).GetTableName()`). I don't think it makes sense to add a generic overload for this.

**Comment by voroninp** [comment]
How?

> System.InvalidOperationException : An attempt was made to use the model while it was being created. A DbContext instance cannot be used inside 'OnModelCreating' in any way that makes use of the model that is being created.

How do I get the instance of the model inside `OnModelCreating` method?

**Comment by voroninp** [comment]
Also, if I do not call this:

```
modelBuilder.Entity<IdentityUser>(b =>
{
    b.Property(_ => _.UserName).HasColumnName("UserName");
});
```

I end up having two columns:
```
CREATE TABLE "AspNetUsers" (
    "Id" TEXT NOT NULL CONSTRAINT "PK_AspNetUsers" PRIMARY KEY,
    "UserName" TEXT NULL,
    "IdentityUser_UserName" TEXT NULL,
```

Is this be design?

Here's my `UserName` class:
```
public sealed class UserName
{
    [Required]
    public required string Id { get; set; }

    public string? Name { get; set; }
}
```

and the mapping:
```
modelBuilder.Entity<UserName>(b =>
{
    b.ToTable("AspNetUsers");

    b.HasOne<IdentityUser>().WithOne()
        .HasForeignKey<UserName>(_ => _.Id)
        .Metadata.IsRequiredDependent = true;

    b.Property(_ => _.Name).HasColumnName("UserName");
});
```
