### ISSUE TITLE
Error " nu1202: package dotnet-ef 8.0.0 is not compatible with net7.0 (.netcoreapp,version=v7.0)" pop up  when use command "dotnet tool install --global dotnet-ef" to install dotnet ef tools in Dev 17.7.7 or lower version 

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/efcore#32403]
Testcases Affected
AspNetCore_WebApp_EFCFMigrations

Repro Steps
1. Install VS 17.7.7 latest release build.
2. Open Command Prompt as admin.
3. Type code "dotnet tool install --global dotnet-ef" to install dotnet ef tools.

Note: 
1. Use command "dotnet tool install --global dotnet-ef" to install dotnet ef tools, it will install 8.0 by default,
2. This issue also repro Dev17.6.10, Dev17.4.14, Dev17.2.22.
3. In Dev 17.2.22, the error is "Package dotnet-ef 8.0.0 is not compatible with net6.0"
![image](https://github.com/dotnet/efcore/assets/41678874/48ab95d5-9e0c-4f13-83e1-da604b37c82d)
4. In Dev 17.2.22, if specify the version as "7.0.14" and use code "dotnet tool install --global dotnet-ef --version 7.0.14" to install, it will install successfully.
![image](https://github.com/dotnet/efcore/assets/41678874/a1500ad4-5e22-4ef7-b3e7-1025a8601a91)
5. In Dev 17.2.22, dotnet --info information as below screenshot: 
![image](https://github.com/dotnet/efcore/assets/41678874/17451508-dec5-4a21-a70f-aed0a4219569)
6. In Dev 17.6.10, dotnet --info information as below screenshot:
![image](https://github.com/dotnet/efcore/assets/41678874/b93e103f-703e-4eca-a6b9-7d6bcdc1a1e0)

Actual Result: It will pop up error as below.
![image](https://github.com/dotnet/efcore/assets/41678874/193dfbe6-0b1a-485d-8a4a-2eec28a3015b)

Expected Result: It will install successfully.

**Comment by ajcvickers** [comment]
EF8 requires .NET 8. It will not work with .NET 6 or 7.

**Comment by Serena01** [comment]
@ajcvickers  Hi Arthur, just want to double confirm with you to make sure we are in the same page. 

- For this issue, In Dev 17.2.22, we **didn't** install additional 7.0 SDK or runtime.  That's to say, **no Net7.0** on the machine. Then we run command "dotnet tool install --global dotnet-ef --version 7.0.14" to install EF7, it will install successfully. **Looks like the EF7 is compatible with Net6.0(even through no Net7.0 on the machine)**

- The same scenario in 17.7.7, we **didn't** install additional 8.0 SDK or runtime.  That's to say, **no Net8.0** on the machine. Then we run command "dotnet tool install --global dotnet-ef" to install EF, it will install EF8.0 by default. There is an error " nu1202: package dotnet-ef 8.0.0 is not compatible with net7.0 (.netcoreapp,version=v7.0)" pop up.

What confuses me is that EF**7.0 is** compatible with Net**6.0** even through without installed Net7.0. However, EF**8 is not** compatible with Net**6.0** unless Net80 is installed.  Are there any special reasons for EF8 that is not compatible with Net60/70 unless we install Net80? Do we have a plan for EF8 that is compatible with Net60/70? Thanks in advance!

**Comment by ajcvickers** [comment]
@Serena01 We don't change the required framework version unless we need to. For EF7, we didn't need to, so it stayed at .NET 6. For EF8, we need .NET, so the required framework version was increased to .NET 8.

**Comment by Serena01** [comment]
@ajcvickers Thanks for your detail information. Make sense now. Thanks again!

**Comment by ajcvickers** [comment]
@sankaiss If you are using .NET 7, then install the 7.0.x version of the "dotnet-ef" package.

**Comment by sankaiss** [comment]
@ajcvickers Thank you for your reply!

Where to install it? I have this on my system

**Terminal in VSC** 
_dotnet ef --version
Entity Framework Core .NET Command-line Tools
7.0.0_

**command prompt in Windows**
_C:\Users\saasss>dotnet ef --version
SDK Version: 7.0.402_

**Comment by ajcvickers** [comment]
@sankaiss See [Installing the tools](https://learn.microsoft.com/en-us/ef/core/cli/dotnet#installing-the-tools). You probably need something like this:

```
dotnet tool uninstall --global dotnet-ef
dotnet tool install --global dotnet-ef --version 7.0.15
```

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by masteroleary** [comment]
@sankaiss If you have a global.json file in your project, copy it to your desktop and then delete it from your project. Delete your global tools and install them locally to the project. Then try dotnet tool restore

I had a global.json file targeting 7.0 framework. I deleted it and then eveything was fine

**Comment by ErikEJ** [comment]
You can run 

`    dotnet info`

to find out is a global.json is active
