### ISSUE TITLE
TPC with tables that don't have a common PK?

### ISSUE THREAD

**Issue by clintsinger** [dotnet/efcore#32401]
## Ask a question

I am trying to model an inheritance hierarchy using TPC for some types where they don't share a common primary key because they need to be unique on different columns in each of the derived types.

```C#
public abstract class InventoryProductDbEntity
{
    public Guid InventoryLocationId { get; set; }
        
    public InventoryConditionType Condition { get; set; }

    public InventoryStatusType Status { get; set; }
}

public class InventoryAccessoryDbEntity : InventoryProductDbEntity
{
    public string Model { get; set; } = null!;

    public InventoryAccessoryType Type { get; set; }

    public int Quantity { get; set; }
}

public abstract class InventoryUnitDbEntity : InventoryProductDbEntity
{
    public abstract string SerialNumber { get; }
}

public class InventorySimDbEntity : InventoryUnitDbEntity
{    
    public string Provider { get; set; } = null!;

    public string? Activation { get; set; }
}

public class InventoryDisplayDbEntity : InventoryUnitDbEntity
{
    public string? Version { get; set; }
}
```

If I was to define the model of these tables independently they would look like this.
```C#
modelBuilder.Entity<InventoryAccessoryDbEntity>(entity =>
{
    entity.HasKey(e => new { e.InventoryLocationId, e.Type, e.Condition, e.Status, e.Model })
        .HasName("inventory_accessory_pkey");
}

modelBuilder.Entity<InventorySimDbEntity>(entity =>
{
    entity.HasKey(e => e.SerialNumber)
        .HasName("inventory_sim_pkey");
}

modelBuilder.Entity<InventoryDisplayDbEntity>(entity =>
{            
    entity.HasKey(e => e.SerialNumber)
        .HasName("inventory_display_pkey");
}
```

```C#
public virtual DbSet<InventoryProductDbEntity> InventoryProducts { get; set; }

public virtual DbSet<InventoryAccessoryDbEntity> InventoryAccessories { get; set; }

public virtual DbSet<InventoryDisplayDbEntity> InventoryDisplays { get; set; }

public virtual DbSet<InventorySimDbEntity> InventorySims { get; set; }
```

Is there some way to make this work with TPC?  

I am okay with adding a PK of some type (probably GUID) that is just there to make EF happy but I still need to ensure uniqueness based on how the keys are defined above.   Alternatively, if I must, I can keep them as separate tables without relying on TPC but would like to query them all at once if possible rather than making multiple calls to the database.

I had tried `.HasAlternateKey()` but that didn't work.

EF Core version: 7.0.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 7.0
Operating system: Windows
IDE: Visual Studio 2022 17.7.7

**Comment by ajcvickers** [comment]
@clintsinger TPC requires using the same key space for all types in the hierarchy. This doesn't mean that the types can't be also unique based on some other combination of property values, but these values can't be used by EF for the primary key in a TPC mapping.

**Comment by clintsinger** [comment]
Thanks for that.  I ended up refactoring the classes to have a common key and then used the UNIQUE constraint in PostgreSQL.
