### ISSUE TITLE
"connection's current state is open" 

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#3240]
When i use inject a dbcontext in a controller, and execute multi threaded query, like this:

Task t1 = query 1（ToArrayAsync()）;
Task t2 = query 2;
Task t3 = query 3;

Task.WhenAll(t1, t2, t3);

Often an error occurred: 
A database operation failed while processing the request.

"connection's current state is open" 

There are pending model changes for ApplicationDbContext
Scaffold a new migration for these changes and apply them to the database from the command line:

> dnx . ef migration add [migration name] 
> dnx . ef migration apply

**Comment by divega** [comment]
@endink DbContext is not thread-safe and interleaving query execution like this on the same instance is not supported. The exception condition you are running into ("connection's current state is open") is possibly the most innocuous problem you have if you do this. Any state maintained by the DbContext may as well be corrupted. 

DbContext has never been thread safe in any previous version of EF. In EF6 we added guards in the async APIs to throw a specific exception if were used in this way. We should probably consider doing this again in EF7.

On the other hand, I am not sure how the part about "pending model changes"  is related. Does that go away if you serialize your async queries (e.g. awaiting each individual call to `ToArrayAsync()`)?

**Comment by endink** [comment]
thanks, so i use "await" it works fine, "pending model changes" is a bug in my code, sorry . thanks again.
