### ISSUE TITLE
dotnet ef dbcontext scaffold runs successfully but does not create any models or update existing models

### ISSUE THREAD

**Issue by AlexW68** [dotnet/efcore#32405]
I have this issue across several projects, I work exclusively in a database first way, 

I run the following command

`dotnet ef dbcontext scaffold "Data Source=tcp:(local)\SQLExpress;Initial Catalog=databasenameblanked;User Id=usernameblanked;Password=passwordblanked;TrustServerCertificate=True"  Microsoft.EntityFrameworkCore.SqlServer -o Models --force --context ApplicationDbContext --use-database-names --no-pluralize --verbose
`
Often it will not create the models of new tables and update the models with new fields etc, this in turn chews up the projects, I am now at the point where I am putting the dbcontext/models in one project, the repositories in another and the UI in a third, so I can unload the UI and repositories to repair the damage quickly.

EF core power tools sometimes works, but can equally do a bad job, but sometimes once the power tools work, then the command above will then work for a while after.

Versions of interest, .Net 8 Released version.
EF core power tools 2.5.1678
All of the Microsoft.EntityFrameworkCore dependencies are 8.0.0 these are
Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.Design
Microsoft.EntityFrameworkCore.SqlServer
Microsoft.EntityFrameworkCore.Tools
Windows 11 (Version 10.0.23590.1000
Microsoft Visual Studio Community 2022
Version 17.9.0 Preview 1.0
VisualStudio.17.Preview/17.9.0-pre.1.0+34310.174
Microsoft .NET Framework
Version 4.8.09032

Looking through the verbose logging there is nothing standing out as an issue. Because the issue is intermittent I wonder if it is a memory/RAM issue my computer has 32gb of RAM and it's often in the 80%+ usage.

**Comment by AlexW68** [comment]
I think I may have found part of the issue it is to do with pluralization 

This works but is not what is generated, end of the first line p.WebLogs
```
entity.HasOne(d => d.DeletedByUser).WithMany(p => p.WebLogs)
 .HasPrincipalKey(p => p.UserId)
 .HasForeignKey(d => d.DeletedByUserId)
 .HasConstraintName("fk_WEBLOG_IDUSER");
```

This is what is generated with the command line in the original post, end of he first line p.WebLog
```
entity.HasOne(d => d.DeletedByUser).WithMany(p => p.WebLog)
 .HasPrincipalKey(p => p.UserId)
 .HasForeignKey(d => d.DeletedByUserId)
 .HasConstraintName("fk_WEBLOG_IDUSER");
```

Modify the p.WebLog to pWebLogs and things start to work, it may not fix all of the issues e.g. model creation etc, but it fixes dbcontext creation.

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by roji** [comment]
@AlexW68 EF is entirely open source on this repo, but it's unlikely you'll be able to figure out what's going on by looking at the code.

Are you able to reliably reproduce this error condition, i.e. when your projects get "chewed up"? If so, the thing to do would not be to post your complex project, but rather to try to isolate the problem, either by recreating the issue in a minimal console program (that's ideal), or by gradually simplifying a copy of your real, complex project by stripping away parts of it until a minimal repro occurs.

**Comment by AlexW68** [comment]
Thanks for your reply, I have found the issue, EntityType.t4 was corrupt, I deleted it and reinstalled the templates, it's interesting that the command line failed and the power tools worked some of the time, that suggests the power tool does not use the templates or ignores issues in them.
