### ISSUE TITLE
Fully support inline List (and other non-array) collections as inline collection query roots

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#32413]
For example, the following fails:

```c#
_ = ctx.Projects.Where(b => new List<int> { 1, b.Int }.Where(b => b > 1).Contains(2)).ToList();
```

... whereas the following works:

```c#
_ = ctx.Projects.Where(b => new[] { 1, b.Int }.Where(b => b > 1).Contains(2)).ToList();
```
---

First, QueryRootProcessor.VisitQueryRootCandidate recognizes NewArrayExpression (inline array) and converts it to InlineQueryRootExpression; but it does not do so for an inline List, and possibly other IList collection types.

Then, in QueryableMethodNormalizingEV, we identify List.Contains and convert it to Queryable.Contains ([code](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs#L429)):

```c#
var ids = new List<int> { 1, 2 };
_ = ctx.Blogs.Where(b => ids.Contains(b.Id)).ToList();
```

This is important for recognizing the Contains as a queryable operator later, etc.

However, we specifically exclude this normalization when the instance is a NewExpression or MemberInitExpression:

```c#
_ = ctx.Blogs.Where(b => new List<int> { 1, 2 }.Contains(b.Id)).ToList();
```

That means that Contains is processed as enumerable rather than queryable, ending up in ContainsTranslator (which we eventually want to remove).

I'm not sure why we made these specific exclusions, any idea @maumar?

**Comment by cincuranet** [comment]
@roji What other non-array and non-List (`!IList` and `!IList<T>`) types were on your mind? Does expanding to i.e. `HashSet<T>`, `LinkedList<T>`, `SortedList<T>` make sense?

**Comment by roji** [comment]
/cc @ajcvickers 

I think at this point we only handle `IList<T>` as primitive collections in the EF sense - this is definitely something we can enlarge in the future, but IIRC e.g. our change tracking doesn't support other types yet.
