### ISSUE TITLE
Interception point that gets the returned data after serialization

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#32418]
Hi,

(With some obfuscation because of IP)
All our mapped to EF database entities are deriving from BaseClass:

```csharp
public class BaseEntity {
  public string RequiredPermission { get; set; }
}
```

We are trying to validate that no matter what, the data returned from the database does not include rows the current user doesn't have permission to, (even if the developer  used `set.IgnoreQueryFilter()`

We would like having another interception point, with the reference to the data returned from the database after serialization, instead of having to materialize the DbDataReader twice.

**Comment by ajcvickers** [comment]
>  with the reference to the data returned from the database after serialization

Can you be more specific about what you mean by this?

**Comment by gdoron** [comment]
@ajcvickers Consider this code:

```csharp
await dbContext.Set<Person>().Where(x=> x.Name.Contains("foo").ToListAsync()
```

We would want to have an interceptor that gets the `List<Person>?` as the `object? Results` property of a new interception point of `DbCommandInterceptor`.

Does it make sense?

**Comment by gdoron** [comment]
@ajcvickers I'm afraid I did not understand how to use the `DataReaderClosing` method for our use case.
How can we get the `List<T>` that was read from that `DataReader`?

**Comment by ajcvickers** [comment]
@gdoron EF doesn't ever create a `List<T>`. EF reads values from the `DbDataReader` and inserts them directly into your entity instances without going through any intermediary data structure. The application then determines what to do with each instance streamed back. At that the application may create a `List<T>` if it chooses. If you're looking for some kind of data structure that goes between the `DbDataReader` and the materialized entities, then that doesn't exist.
