### ISSUE TITLE
My DTOs without DBSet declaration in DB Context class, are still generating separate tables.

### ISSUE THREAD

**Issue by inabeel** [dotnet/efcore#32426]
I have multiple projects in my solution. One of those projects contains all models, DTOs called Domain. The Other project called Persistence for all Repository features containing my DB Context class, migrations and my Repository Pattern.
There is WebApi startup project. 

I added some Model classes, and DTOs. and then Declared Dbset of model classes in DB Context class.
But the problem is Entity framework is including all classes in migration.

i am creating migration using following command:
> add-migration "Migration-Name"

Expected behavior: Since DTOs are not declared in DbContext, no way their Schema and table should be generated.

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system: Windows 11
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by inabeel** [comment]
The problem which i figured out is as follows:
In my DTOs. I have field like EventId without any data annotation. While Event is Model Entity in same project. So it maps EventId with Primary key Id of Event.
As workaround, I have marked my DTOs as "NotMapped". But this problem should be fixed
