### ISSUE TITLE
EF8 Breaking Change: Annotation Removed (Minor)

### ISSUE THREAD

**Issue by wdhenrik** [dotnet/efcore#32424]
### Summary
Prior to EF8
Derived Entity in a TPH hierarchy would have annotation "DiscriminatorProperty" with a value of null.

EF8
Derived Entity in a TPH hierarchy does not have annotation "DiscriminatorProperty".

### Problem Info
```if(entity.GetAnnotation("DiscriminatorProperty").Value == null)```
In EF7 & EF8, the `.Value` contains the property name for the discriminator when the entity is a base type.  Prior to EF8, if the entity is a derived type, the annotation still exists, but has a null value.

With the move to EF8, that annotation was removed from the derived type, causing the .Value statement to throw an exception.

Adding a migration returns the following error:
```Unable to create a 'DbContext' of type ''. The exception 'The annotation 'DiscriminatorProperty' was not found. Ensure that the annotation has been added to the object EntityType: [DerivedType] Base: [BaseType]' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728```

### Solution
Use this instead to identify TPH derived types:
```entity.GetMappingStrategy() == "TPH" && entity.BaseType != null```
This works in EF7 & EF8

### Version info
EF Core version: 8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) SQL Server
Target framework: (e.g. .NET 8.0) .Net 8
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 17.8)

**Comment by ajcvickers** [comment]
@wdhenrik Core annotations are considered an implementation detail--something may change from being stored as an annotation do being stored in another way. Using the public APIs is the correct way to manage this metadata, rather than looking at annotations directly.
