### ISSUE TITLE
SQLite or SQLServer

### ISSUE THREAD

**Issue by angelsix** [dotnet/efcore#3242]
Which do you recommend using on Linux. SQLite, or SQLServer (Mono SQL Client)?

I am wondering if the full SQLServer will be natively supported within say 6-12 months and its worth me using that for now, or whether SQLite is the better option for linux?

I expect the database to be fairly sized, nothing mad - likely 20-30 tables, 100,000 to 1,000,000 entries on average. However I would like the best scalable option and if the full SQLServer will be supported fully down the road, I'll start with that.

**Comment by bricelam** [comment]
The [Npgsql provider](www.npgsql.org/doc/ef7.html) for PostgreSQL is another great option to consider on Linux.

**Comment by angelsix** [comment]
As far as a know, that doesnt have an Entity Framework provider. Also both of the others are cross-platform between Linux/Windows. I'm not sure if PostgreSQL is and I've had no experience with that at all so wouldnt really want to change from SQL Server if possible.

**Comment by divega** [comment]
@angelsix yes, the EF7 provider for PostgresSQL is being worked on. That is what @bricelam is pointing to. 

To your original question, we plan to fully support using SQL Server from EF7 on a Linux box, but we are focusing more on CoreCLR based implementation of SqlClient than on Mono.

**Comment by divega** [comment]
Closing since I believe we have answered your question, but feel free to reopen if we haven't.
