### ISSUE TITLE
Busting stale data in DB entities (L1 cache and other sheningans)

### ISSUE THREAD

**Issue by Uraharadono** [dotnet/efcore#32438]
### Provider and version information

EF Core version: **.Net Core 3.1**
Database provider: **Microsoft.EntityFrameworkCore.SqlServer**
Target framework: **.Net Core 3.1**
Operating system: **Microsoft Windows 11 Pro, Version 10.0.22621 Build 22621**
IDE: **Microsoft Visual Studio Professional 2022 (64-bit), Version 17.7.4**

Hello everyone,
I am having issues with **EntityFrameworkCore cache (probably L1)** that I just don't know how to bust for it to work. Maybe it is not L1 cache, and I am wrong, but that is why I am here to find out.

## I will setup the "_stage_" first:

Let's say I have following repository:

        public PaymentTransactionsRepository(PaymentsDbContext dbContext)
            : base(dbContext)
        {
        }

        public async Task<PaymentTransactionEntity> GetEntityByPaymentRequestExternalIdAsync(string paymentRequestExternalId)
        {
            // Sync
            var entity = _dbContext.Set<PaymentTransactionEntity>().Where(pr => pr.Deleted == false && pr.PaymentRequestExternalId == paymentRequestExternalId).FirstOrDefault();
            return entity;

            // Async
            // var entity = await _dbContext.Set<PaymentTransactionEntity>().Where(pr => pr.Deleted == false && pr.PaymentRequestExternalId == paymentRequestExternalId).FirstOrDefaultAsync();
            // return entity;
        }

Inside **Web Api Controller Action** it is being called in **Threading processor** which is initiated like so:

                var paymentAuthorizationThreadProcessor = providerService.GetService<PaymentAuthorizationThreadingProcessor>();
                ThreadPool.QueueUserWorkItem(new WaitCallback((_) => { _paymentStatusThreadingProcessor.PollingStatus(paymentRequest.ExternalId); }));

And here is its (barebone) implementation: 

    public class PaymentAuthorizationThreadingProcessor
    {
        private const int DEFAULT_SLEEP_TIME_MS = 1000;
        private readonly IServiceScopeFactory _serviceScopeFactory;

        public PaymentAuthorizationThreadingProcessor(IServiceScopeFactory serviceScopeFactory)
        {
            _serviceScopeFactory = serviceScopeFactory;
        }

        public class PaymentAuthorizationThreadingProcessor
    {
        private const int DEFAULT_SLEEP_TIME_MS = 1000;
        private readonly IServiceScopeFactory _serviceScopeFactory;

        public PaymentAuthorizationThreadingProcessor(IServiceScopeFactory serviceScopeFactory)
        {
            _serviceScopeFactory = serviceScopeFactory;
        }

        public void PollingStatus(string paymentRequestId)
        {
            // Gets scoped services
            using var scope = _serviceScopeFactory.CreateScope();
            var paymentTransactionsRepository = scope.ServiceProvider.GetService<IPaymentTransactionsRepository>();
            // ... other repos being resolved in same manner

            // ... Step 1 logic here 
            var transactionEntity = paymentTransactionsRepository.GetEntityByPaymentRequestExternalIdAsync(paymentRequestId).Result;
            // ...
            // ...
            // ...
            // ...
            // ... Step 2 logic here 
            transactionEntity = paymentTransactionsRepository.GetEntityByPaymentRequestExternalIdAsync(paymentRequestId).Result;
            // ... some more logic there
            // ...
            // ...
            // ...
            // ...			
            // ... Step 3 logic here 
            transactionEntity = paymentTransactionsRepository.GetEntityByPaymentRequestExternalIdAsync(paymentRequestId).Result;
            // ... some more logic there
            // ...
            // ...
            // ...
            // ...
            // ...
            // Some crazy logic below that I do not dare to touch....
            try
            {
				// Put thread in sleep time
				Thread.Sleep((int)sleepTime);
				// Do some stuff
				
            }
            catch (Exception ex)
            {
				// Log exception
				Thread.Sleep(DEFAULT_SLEEP_TIME_MS);
            }
        }
    }
 
In **Startup.cs** they are being registered like so:

            services.AddDbContextPool<PaymentsDbContext>(x =>
            {
                x.UseSqlServer(Configuration.GetConnectionString("SqlConnection"), options => options.EnableRetryOnFailure());
                x.AddInterceptors(DbInterceptors.CreateInterceptors());
            });
            services.AddMemoryCache(); // this line is there, but there is no usage of ".Cache()" syntax on any of entities
            services.AddScoped<IPaymentTransactionsRepository, PaymentTransactionsRepository>();
            services.AddScoped<PaymentAuthorizationThreadingProcessor>();
			
			
## The problem: 
We are having problem with current code is that on **PaymentAuthorizationThreadingProcessor** Step 1 might return some data.
Before step 2 we have updated and changed this entity data.
After we call step 2 we get entity with old data, while database has updated values. 
In short, `transactionEntity `does not have up to date data from database.
Meaning this is coming from somewhere, most notably from L1 cache but that might not be the case. 

## Solutions we have tried:

1. ### AsNoTracking

We have tried to use `.AsNoTracking `to fetch our data. This is coming with mixed results. 
It has worked most of the time, until it didn't. 
For sure it was creating a lot of inconsistencies with `async ` types of methods, but I am not sure about sync methods.

Tipping point was that at one point our query had to be changed to this: 

        public PaymentTransactionEntity GetEntityByPaymentRequestExternalId(string paymentRequestExternalId, IServiceScopeFactory scopeFactory)
        {
            using var scope = scopeFactory.CreateScope();
            var paymentsDbContext = scope.ServiceProvider.GetService<PaymentsDbContext>();
            var transactionEntity = paymentsDbContext.PaymentTransactions.AsNoTracking().FirstOrDefault(pr => pr.Deleted == false && pr.PaymentRequestExternalId == paymentRequestExternalId);

            _paymentTransactionRedisCache.Create(transactionEntity, DEFAULT_REDIS_TIME_TO_LIVE);
            return transactionEntity;
        }

2. ### Interceptor(s)

I have also written an interceptor for database that looks like this:

		public class CacheInterceptor : DbCommandInterceptor
		{
			public override InterceptionResult<DbDataReader> ReaderExecuting(
				DbCommand command,
				CommandEventData eventData,
				InterceptionResult<DbDataReader> result)
			{
				// Check if the result can be obtained from the cache
				var cachedEntity = eventData.Context.ChangeTracker.Entries()
					.FirstOrDefault(entry => entry.Entity != null && entry.State == EntityState.Unchanged);
		
				if (cachedEntity != null)
				{
					// Reload the entity to update it from the database
					cachedEntity.Reload(); // ISSUE HERE - THIS WILL CAUSE INFINITE LOOP
		
					// result = InterceptionResult<DbDataReader>.Suppress();
					result = InterceptionResult<DbDataReader>.SuppressWithResult(result.Result);
				}
		
				return result;
			}
		
			// As per my question on the GitHub: https://github.com/dotnet/efcore/issues/29560
			// For async stuff, we need to do async interceptor
			public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(
				DbCommand command,
				CommandEventData eventData,
				InterceptionResult<DbDataReader> result,
				CancellationToken cancellationToken = default)
			{
				// Check if the result can be obtained from the cache
				var cachedEntity = eventData.Context.ChangeTracker.Entries()
					.FirstOrDefault(entry => entry.Entity != null && entry.State == EntityState.Unchanged);
		
				if (cachedEntity != null)
				{
					// Reload the entity to update it from the database
					cachedEntity.Reload(); // ISSUE HERE - THIS WILL CAUSE INFINITE LOOP BY CALLING SYNC VERSION
				}
		
				return new ValueTask<InterceptionResult<DbDataReader>>(result);
			}
		}

As you can see by comment on "`cachedEntity.Reload();`" this was causing us a lot of issues by **creating infinite loop**. 
Also, I don't this this is such an good idea, since this will cause a lot of performance issues for sure, this project is huge.
I was so desperate to make this work, that I tried to remove `Intereceptors `in runtime, and re-add them after, but I could not find documentation for **EF .Net**.

3. ### Custom extension method

I have written following extension method:

		public static class DbContextExtensions
		{
			public static async Task<TEntity> GetEntityAsync<TEntity>(this DbContext dbContext, Expression<Func<TEntity, bool>> predicate)
				where TEntity : class
			{
				// check if it's in the cache already
				var cachedEntity = dbContext.ChangeTracker.Entries<TEntity>().FirstOrDefault(entry => entry.Entity != null && predicate.Compile()(entry.Entity));
		
				TEntity result = null;
				if (cachedEntity == null)
				{
					// not in cache - get it from the database
					result = await dbContext.Set<TEntity>().FirstOrDefaultAsync(predicate);
				}
				else
				{
					// we already have it - reload it
					cachedEntity.Reload();
					result = cachedEntity.Entity;
				}
		
				return result;
			}
			
			// Sync version implementation as well
		}

This works like a charm, but the problem with it is that I would need to replace every query in project that has probably million of them.

## Question:

I know for a fact that registering `Repository ` as `Scoped` does not mean anything, because once `Repo `ends up in `Pool `it will behave as `Singleton`.
This means that our **DbContext** is going to be recycled, thus making a way for `L1 cache ` to kick in. 

Is there any way for us to make this work ? To get fresh, and up to date data every time we run our queries ? 

We even had to resort to manually changing the Entity states in some places because of this ...

**Comment by ajcvickers** [comment]
@Uraharadono From the snippets of code, it looks like you are re-using the same DbContext instance for multiple operations, without any protection such as a pool. In general, this isn't going to work. Instead, create a single DbContext instance for each unit-of-work, ensuring it is disposed afterwards, or use context pooling if appropriate to re-use instances safely.

**Comment by Uraharadono** [comment]
Hey @ajcvickers ,
Thanks a lot for your response.

I am well aware of this happening with db context, but as I said there isn't any way for me to achieve this. 
Even if I was manually instantiating `DbContext ` inside the constructor of my `PaymentTransactionsRepository`, even if it was something like so:

    protected readonly DbContext _dbContext; 

    public PaymentTransactionsRepository(IServiceScopeFactory scopeFactory)
    {
        using var scope = scopeFactory.CreateScope();
        _dbContext= scope.ServiceProvider.GetService<DbContext>();
    }
    
This won't work even because inside the pool `IPaymentTransactionsRepository` is going to behave as singleton, since it is instantiated inside the method like so. 

    using var scope = _serviceScopeFactory.CreateScope();
    var paymentTransactionsRepository = scope.ServiceProvider.GetService<IPaymentTransactionsRepository>();
        
meaning effectively I have one instance of `IPaymentTransactionsRepository` and thus one instance of `DbContext`. 



I looked into if `AddDbContextPool ` from `Startup.cs ` is causing these issues, but it isn't. 
The only other way I have figured this is to reset the `IPaymentTransactionsRepository`  inside my pool every time before I call 

    transactionEntity = paymentTransactionsRepository.GetEntityByPaymentRequestExternalIdAsync(paymentRequestId).Result;
    
but this is kind of manual labor thing and does not feel OK at all. 

The only meaningful, "global" way to achieve this was what I have written in my update. It works, and I haven't experienced any issues with it for now, but it does feel like it is solution that is going to explode.

**Comment by roji** [comment]
```c#
public PaymentTransactionsRepository(IServiceScopeFactory scopeFactory)
{
    using var scope = scopeFactory.CreateScope();
    _dbContext= scope.ServiceProvider.GetService<DbContext>();
}
```

Rather storing a DbContext instance as a member on your repository, you can have a pooling DbContext factory in your DI (AddPooledDbContextFactory), and request one from the factory whenever you need one. As @ajcvickers was writing above, do not attempt to store and reuse the same context instance, since that causes tracked changes to interfere between different calls etc. Just request a new context whenever you need to do something on the database.

**Comment by Uraharadono** [comment]
@roji Thanks a lot once again for your time !

I know you guys have best practices in mind, but unfortunately it is almost impossible to change this current `Repo `logic to `DbContext Factory`. It would require way too much effort to get 100+ people and even more repos up to date. 

For now I have dropped the interceptor, and created following extension method:


```
 public static class QueryableExtensions
 {
     public static IQueryable<TEntity> DoCacheBusting<TEntity>(this IQueryable<TEntity> query)
         where TEntity : class
     {
         // Get the DbContext from the query
         var dbContext = query.GetDbContext();

         // check if it's in the cache already
         var cachedEntity = dbContext.ChangeTracker.Entries<TEntity>().FirstOrDefault(entry => entry.Entity != null && query.Contains(entry.Entity));

         if (cachedEntity != null)
         {
             // we already have it - reload it
             cachedEntity.Reload();
         }

         return query;
     }

     // This may be wrong sometimes in future, read comments here: https://stackoverflow.com/a/53340563/4267429
     private static DbContext GetDbContext<TEntity>(this IQueryable<TEntity> query)
         where TEntity : class
     {
         var bindingFlags = BindingFlags.NonPublic | BindingFlags.Instance;
         var queryCompiler = typeof(EntityQueryProvider).GetField("_queryCompiler", bindingFlags).GetValue(query.Provider);
         var queryContextFactory = queryCompiler.GetType().GetField("_queryContextFactory", bindingFlags).GetValue(queryCompiler);

         var dependencies = typeof(RelationalQueryContextFactory).GetField("_dependencies", bindingFlags).GetValue(queryContextFactory);
         var queryContextDependencies = typeof(DbContext).Assembly.GetType(typeof(QueryContextDependencies).FullName);
         var stateManagerProperty = queryContextDependencies.GetProperty("StateManager", bindingFlags | BindingFlags.Public).GetValue(dependencies);
         var stateManager = (IStateManager)stateManagerProperty;

         return stateManager.Context;
     }
 } 
```
 
 
 and I use it like so:
 
 
             var entity = await _dbContext.Set<PaymentTransactionEntity>()
                .Where(pr => pr.Deleted == false && pr.PaymentRequestExternalId == paymentRequestExternalId)
                .DoCacheBusting()
                .FirstOrDefaultAsync();
                
                
This seems to do job for now. But please do inform me if there is something wrong with this approach.

**Comment by roji** [comment]
@Uraharadono a much simpler solution is simply to call `_dbContext.ChangeTracker.Clear()` before performing your query. That clear EF's change tracker, and effectively returns it to an empty state as if it's a new DbContext (this only does so for the change tracker - other parts of the context instance are not reset - but it may be enough for your needs).

**Comment by roji** [comment]
Closing as the question was answered, but feel free to post back if you need further guidance.
