### ISSUE TITLE
Vulnerable package with Microsoft.EntityFrameworkCore.SqlServer 8.0.0

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#32441]
Hi,

There is a vulnerable package included with Microsoft.EntityFrameworkCore.SqlServer 8.0.0

That is Azure.Identity 1.7.0. Can you please update the above package with a new version Or is there any impact in working of existing version if we install a separate updated package for Azure.Identity.

Thanks

**Comment by ErikEJ** [comment]
@satyajit-behera @carlaguinaldo-TU This will most likely be fixed early next year with SqlClient 5.1.4. And it is a SqlClient issue, not an EF Core issue.
