### ISSUE TITLE
Are ReaderExecuting and ReaderExecuted on the DbCommandInterceptor always guaranteed to be called on the same thread?

### ISSUE THREAD

**Issue by nettashamir-allocate** [dotnet/efcore#32465]
I'm in the process of implementing an L2 cache using the DbCommandInterceptor and I was just wondering whether I can rely on the ReaderExecuting and ReaderExecuted methods being called on the same thread. The reason I ask is that I'm doing some parsing of the SQL in the Executing phase to work out which queries I can cache and which commands require cache invalidation etc. and I would like to hold on to my findings to reuse them in the Executed phase rather than having to repeat the parsing step. 

The code looks something like the following (although this is a highly simplified example just to illustrate the issue):

```C#
public override InterceptionResult<DbDataReader> ReaderExecuting(DbCommand dbCommand, CommandEventData eventData, InterceptionResult<DbDataReader> result) {
	var cacheabilityContext = <parse the dbCommand.CommandText and work out whether it is cacheable + some extra info about the command>

	if (!cacheabilityContext.IsCacheable) return result;
	var cachedResult = cache.GetResult(cacheabilityContext.CacheKey); // of type CachedDbDataReader

	if (!cachedResult) return result; // but we've done work here to derive the cacheabilityContext so would like to be able to hold onto it for the ReaderExecuted phase below
	return InterceptionResult<DbDataReader>.SuppressWithResult(cachedResult);
}

public override DbDataReader ReaderExecuted(DbCommand dbCommand, CommandExecutedEventData eventData, DbDataReader result) {
	if (result is CachedDbDataReader) return result; // we had a cache hit

	// having to do this parsing again to chech whether I should insert this result in the cache but would rather not have to repeat it
	var cacheabilityContext = <parse the query and work out whether it is cacheable + some extra info about the query>

	if (!cacheabilityContext.IsCacheable) return result;
	cacheStore.Insert( cacheabilityContext.CacheKey, result);
}
```

So ideally we would have a thread static to hold the cacheabilityContext which is cleared at the end of the ReaderExecuted phase.
Would that be safe?

Note: This is only applying to the synchronous versions of these methods. There is obviously no guarantee for the Async versions.

**Comment by ajcvickers** [comment]
@nettashamir-allocate I think this should be safe. The only thing I can think of is if we do async over sync anywhere; I will follow up with the team on this.
