### ISSUE TITLE
Is there an option to extend the model without inheriting from DbContext?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32462]
For example, I am developing a NuGet library which should support various DB libraries including EF.

Is there any option to extend data model other than requiring `DbContext` to [implement a particular interface](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0#persistkeystodbcontext) or inherit from [another context](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.entityframeworkcore.identitydbcontext?view=aspnetcore-7.0)?

**Comment by roji** [comment]
Your nuget package can integrate into the model-building process by introducing its own conventions; as an example, see [EFCore.CheckConstraints](https://github.com/efcore/EFCore.CheckConstraints) which adds various check constraints to the model.

To help out more, we'd need to know exactly what kind of model changes your library intends to do etc.

**Comment by voroninp** [comment]
Very often, I need to extend entities with service properties like Timestamp or Version and manage such properties automatically.

For example, `Version` can be a (shadow) property which `CurrentValue` is incremented right before the changes are saved to DB.

**Comment by roji** [comment]
Then yeah, plugin conventions seem like the thing to do - take a look at EFCore.CheckConstraints.

**Comment by roji** [comment]
A plugin can also add method and member translators - you can look at the NodaTime and/or NetTopologySuite plugins in this repo for inspiration.

I'll go ahead and close this now as the questions have been answered, but feel free to post back here if you need to.

**Comment by voroninp** [comment]
@roji Q1: Do I get it right that annotations is the way to extend configuration of entites?

For example, I want to mark a property as a timestamp.
```
b.Property(e => e.TimestampUtc).IsTimestamp();
```
```
public static PropertyBulder<DateTime> IsTimestamp(this PropertyBulder<DateTime> propertyBuilder, bool isTimeStamp = true)
{
    return propertyBuilder.HasAnnotation("voroninp:IsTimeStamp", isTimeStamp);
}
``

**Comment by voroninp** [comment]
@roji 

1. Mark a property to work as a timestamp. Either with attribute or with fluent mapping.
2. When DbContext performs `SaveChanges`, scan through the entities (Added/Modified), find those with timestamp properties and assign new value to the property.
3. The value should be acquired via `TimeProvider` which is injected to the service which does the job of updating the property.

**Comment by roji** [comment]
Sounds like you want to set a value generator that works on update (not yet supported, #6999). Until then, although annotations are meant more as an internal and provider thing, you may be able to use that as a workaround, yes. Another option is to get the timestamp generated in the databases e.g. via a trigger ([doc](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#update-timestamp)). /cc @ajcvickers in case he has other ideas.

**Comment by voroninp** [comment]
Well, currently I can just override `SaveChanges` and do the work there. But I'd like to have it as an extension. Currently not possible?

**Comment by voroninp** [comment]
Also, how can I add annotation to the entity via `PropertyBuilder`? For example, I want entity to be annotated with `voroininp:HasTimestampProperty` when I call `.IsTimestamp()`.

**Comment by roji** [comment]
Not sure what you're asking - you seem to already be using PropertyBuilder.HasAnnotation() - IsTimestamp() can be an extension over PropertyBuilder which just does that, no?

**Comment by voroninp** [comment]
I mean, I add annotation to the property, but I'd like to add it to the entity as well when I call `IsTimestamp()`

**Comment by voroninp** [comment]
Ok, thanks.
Next question.
Which service do I need to extend/replace to intercept saving changes?

**Comment by voroninp** [comment]
ping...
