### ISSUE TITLE
Concurrency issues of different transactions in the same context

### ISSUE THREAD

**Issue by chrisdaiii** [dotnet/efcore#32474]
In the following example, I conduct concurrency testing through Jmeter, the configuration is: two threads group, 50 threads in 1 second, there is no concurrency problem when calling Add, the final sequence number is 100, but when calling AddRange it appears Concurrency issues include repeated sequence, which means that the With (tablockx) exclusive lock does not play a role. What puzzles me is that there is no problem when calling once, but concurrency problems occur when calling multiple times.

Please check what the problem is, thank you.

[EFCoreDemo.zip](https://github.com/dotnet/efcore/files/13521407/EFCoreDemo.zip)

**Comment by ajcvickers** [comment]
Note for triage: there is a combination of a raw SQL query using `TABLOCKX`, multiple transactions, and `SaveChanges`. It's not clear to me that the behavior would be any different without EF.

**Comment by 13750573877** [comment]
> Note for triage: there is a combination of a raw SQL query using `TABLOCKX`, multiple transactions, and `SaveChanges`. It's not clear to me that the behavior would be any different without EF.

Is the way I'm using it wrong?

**Comment by ajcvickers** [comment]
Note for triage: the code is below. As far as I can tell, it does the following:

- Starts a transaction using `BeginTransaction`
- Uses that transaction using `UseTransaction` (hopefully a no-op.)
- Runs a raw SQL query with a table lock: `SELECT * FROM [SeedTable] WITH(TABLOCKX)`
- Uses this value to change the state of an entity
- Calls SaveChanges
- Commits the transaction.

The question is whether or not this will suffer from concurrency issues, which I think depends on the table lock and any interactions that EF SaveChanges has with that.

```C#
using var transaction = await _context.Database.BeginTransactionAsync(cancellationToken);

await _context.Database.UseTransactionAsync(transaction.GetDbTransaction());

var sql = new StringBuilder();

var parameters = Array.Empty<object>();

sql.Append("SELECT * FROM [SeedTable] WITH(TABLOCKX)");

if (parameter.ResetDate is not null)
{
    sql.Append(" WHERE [Date] = {0}");

    parameters = new object[] { parameter.ResetDate };
}

var entity = await _context.Set<SeedTable>()
    .FromSqlRaw(sql.ToString(), parameters)
    .SingleOrDefaultAsync(cancellationToken);

if (entity is null)
{
    entity = new SeedTable()
    {
        Date = parameter.ResetDate,
        Sequence = parameter.StartValue
    };

    await _context.AddAsync(entity, cancellationToken);
}
else
{
    entity.Sequence += parameter.IncrementBy;

    if (entity.Sequence > parameter.MaxValue)
    {
        entity.Sequence = parameter.MinValue;
    }

    _context.Update(entity);
}

await _context.SaveChangesAsync(cancellationToken);

await transaction.CommitAsync(cancellationToken);

return entity.Sequence;
```

**Comment by ajcvickers** [comment]
@chrisdaiii I took a deeper look at this and the issue is that the code is reusing the same context instance for each of the three queries in the range. This means that EF sees that the entity is already tracks, and so uses the tracked instance instead of getting a new instance from the database. But this instance has not seen the updates made to the database from another client, and hence duplicates get created.

This can be handled by:
- Using a no-tracking query
- Using a new context instance for each query
- Clearing the change tracker between each query

**Comment by chrisdaiii** [comment]
> @chrisdaiii我更深入地研究了这一点，问题是代码为该范围内的三个查询中的每一个重复使用相同的上下文实例。这意味着 EF 发现该实体已被跟踪，因此使用跟踪的实例而不是从数据库获取新实例。但此实例尚未看到另一个客户端对数据库所做的更新，因此会创建重复项。
> 
> 这可以通过以下方式处理：
> 
> * 使用非跟踪查询
> * 为每个查询使用新的上下文实例
> * 清除每个查询之间的更改跟踪器

Thank you very much!

**Comment by chrisdaiii** [comment]
> @chrisdaiii I took a deeper look at this and the issue is that the code is reusing the same context instance for each of the three queries in the range. This means that EF sees that the entity is already tracks, and so uses the tracked instance instead of getting a new instance from the database. But this instance has not seen the updates made to the database from another client, and hence duplicates get created.
> 
> This can be handled by:
> 
> * Using a no-tracking query
> * Using a new context instance for each query
> * Clearing the change tracker between each query

Thank you very much!
