### ISSUE TITLE
dotnet ef migrations suddenly crashing in OnConfiguration because it can't find the Connection String

### ISSUE THREAD

**Issue by ssteiner** [dotnet/efcore#32479]
Today I wanted to add a new migration. I do my usual ` dotnet ef migrations add <name of migration> --context <name of my context>` and I'm greeted with a `Object reference not set to an instance of an object.` from within the `OnConfiguring` method. Specifically, the first of these two lines

```C#
    var connectionString = ConfigurationManager.ConnectionStrings["AudmDatabase"].ConnectionString;
    optionsBuilder.UseSqlServer(connectionString, options => options.EnableRetryOnFailure());
```

The full stacktrace being
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudmDatabaseLib.Model.AudmDatabaseContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in D:\Repos\AUDM\UnifiedProvisioning\UnifiedDatabaseLib\UnifiedAudmDatabaseLibStdIntegrated\AudmDatabaseContext.cs:line 46
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

So, I changed my code to iterate the `ConfigurationManager.ConnectionStrings`, to find, the only member of the collection is this:

data source=.\SQLEXPRESS;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|aspnetdb.mdf;User Instance=true

No idea where this comes from. My DBL is actually a class lib, not main project (executable) itself, and I've always (for several years) been using `dotnet ef` from the path of the DBL library project, never thinking about connection strings.

Now, of course there's an easy temporary fix, I just hardcode the connection string I want to use, and the migration will work. But now I'm curious where dotnet ef could get the migration strings it uses for a migration in the first place. When my app runs, it instantiates the DB context with a connection string taken from appSettings.json, so that part is safe.. but where does dotnet ef get the connection string from? I tried appendding `--connection <connection string here>` to my migration command, only to be told the parameter is not supported.

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)
Operating system: Win 11 2023H2 Pro
IDE: (e.g. Visual Studio 2022 17.8.2)

Here's a short version of my DB context

````C#
public partial class AudmDatabaseContext : DbContext
{
    private readonly string connectionString;
    private readonly string connectionStringName = "AudmDatabase";

     public AudmDatabaseContext()
        : base()
    {
        connectionString = "data source=(local);initial catalog=AUDM_EFCore;Integrated Security=true;MultipleActiveResultSets=True;Encrypt=false";
    }

    public AudmDatabaseContext(string connectionString = null)
        : base()
    {
        this.connectionString = connectionString;
    }

    public AudmDatabaseContext(DbContextOptions contextOptions, string connectionString = null)
        : base(contextOptions)
    {
        this.connectionString = connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (string.IsNullOrEmpty(connectionString))
        {
            var connectionString = ConfigurationManager.ConnectionStrings[connectionStringName].ConnectionString;;
            optionsBuilder.UseSqlServer(connectionString, options => options.EnableRetryOnFailure());
        }
        else
            optionsBuilder.UseSqlServer(connectionString, options => options.EnableRetryOnFailure());
        optionsBuilder.UseLazyLoadingProxies();
        optionsBuilder.EnableSensitiveDataLogging();
        optionsBuilder.ConfigureWarnings(act => act.Ignore(CoreEventId.DetachedLazyLoadingWarning));
        base.OnConfiguring(optionsBuilder);
    }

}
````

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. Also, post the full exception stack trace: just posting the exception message isn't enough.

**Comment by ssteiner** [comment]
I added the full stacktrace, as well as the highlights of my Context.

At present, what I'm trying to understand is.. when I run `dotnet ef migrations add`  - where is the connection string taken from? It seems from the exception that we enter `OnConfiguring` without `connectionString` filled out. Since my `DbContext` lives in a library, there's no appSettings.json in the output (or other config file). So, running the dotnet et migrations from the folder of the lib that contains my `AudmDatabaseContxt` , how could dotnet ef possibly have found a connection string (this worked for years.. I reverted the changes to the 7.0.14 packages back to 7.0.13 where it worked but that didn't help).

I think it boils down to: how can I give my desired connectionstring to `dotnet ef migrations add`.

**Comment by ajcvickers** [comment]
@ssteiner The tool runs your code and then resolves the DbContext from D.I. So, it runs your code to set the connection string, whatever that happens to be. In your case, this code: `ConfigurationManager.ConnectionStrings["AudmDatabase"].ConnectionString;`. See [Design-time DbContext creation](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli) for more information.
