### ISSUE TITLE
translate `Nullable<T>.GetValueOrDefault()` with `IsNull()` 

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#32471]
Currently,  we must use  `??` , `?:` or  `x==null || x == value` expression with the `Nullable<T>` for compare the column,    but outside the EF linq,  we normally write `.Where(x=>x.GetValueOrDefault() == 0)`, 
and in sqlserver,  we write `IsNull(column,0) == 0` in Sql

So,  I think  `Nullable<T>.GetValueOrDefault()`  should directly translate to those Sql 
-  when `IsNull` or `IfNull` exists ,  use  `IsNull(<column>, default(ClrType))` 
-  when not exists ,  use `COALESCE(<column>, default(ClrType))` which exactlly the same with `CASE WHEN <column> is not null Then <column> ELSE  <defualt(CLRType)> end`

for example : 
```C#
DbSet<Post>().Where(p=>p.IsDelete.GetValueOrDefault() == 1) 
```
translate to 

```sql
declare @__IsDelete_CLRDefault Int = 0

SELECT * FROM POST p WHERE ISNULL(p.IsDelete) == 1

```

**Comment by roji** [comment]
I'm a bit confused... if the value in question is an `int?`, why not simply write `Where(x => x == 0)`? What value does GetValueOrDefault() add here? Also, why not just use the coalescing operator (`??`)?

**Comment by John0King** [comment]
@roji   consider a columen is add after the table is create .   `FiledX  int null `    (it's actully a column that shouldn't be null, but it's a decision made by other one)    and people write sql ` WHERE 1=1 and ISNULL(FiledX,0) == 0`  (because `null` doesn't equals to any value )  and back to EF,  EF turns  (`(int?)null` is equals to null)  , so we need write to `.Where(x=>x.FiledX == null || x.FiledX == 0)`  or  better `.Where(x=>(x.FiledX ?? 0) ==  0)`   and the `Nullable<T>.GetValueOrDefault()`  is not supported by EF currently.

`Nullable<T>` is a very simple type, and all it's properties and methodes can be translate to SQL.

-  `.HasValue`   => ` Column IS NOT NULL`
- `.GetValueOfDefault()` =>  `ISNULL(COLUMN, @ClrDefaultValue)`
- `.Value`   =>  just be the column value

**Comment by roji** [comment]
Duplicate of §22243
