### ISSUE TITLE
Create migration bundle without requiring connection to DB

### ISSUE THREAD

**Issue by klinki** [dotnet/efcore#32485]
I'm trying to create migration bundle on CI/CD server, but it fails because `dotnet ef migrations bundle` command needs to connect to database to produce the bundle.

It would be great if it was possible to produce bundle without connecting to DB.

**Comment by ajcvickers** [comment]
Note for triage: as far as I can tell, the "bundle" command does not connect to the database.

**Comment by klinki** [comment]
You are right, this seems to be problem with Pomelo.EntityFrameworkCore.MySql `ServerVersion.AutoDetect` . There is already issue reported there https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1761  so I'll close this one.
