### ISSUE TITLE
How do I create an optional 1:1 relationship in EF Core where neither side is dependent on the other?

### ISSUE THREAD

**Issue by MrYossu** [dotnet/efcore#32514]
I have a `Device` model, and a `Tid` model. Devices and TIDs can exist independently of each other, or can be associated together. If associated, then exactly one device can be associated with exactly one TID.

For this I need a nullable one-to-one relationship, meaning that either both ends are null, or both ends are not null. However, unlike all the examples I've seen, I don't have a dependent entity. Either one can exist without the other, and I'm having problems setting this relationship up.

I modelled this as follows...

```c#
public class Device {
  // Irrelevant properties excluded for clarity
  public string? TidId { get; set; }
  public virtual Tid? Tid { get; set; }
}

public class Tid {
  // Irrelevant properties excluded for clarity
  public string? DeviceId { get; set; }
  public virtual Device? Device { get; set; }
}

public class AppDbContext : IdentityDbContext<User> {
  // Irrelevant code excluded for clarity
  protected override void OnModelCreating(ModelBuilder builder) {
    base.OnModelCreating(builder);

    builder.Entity<Device>()
      .HasOne<Tid>()
      .WithOne(t => t.Device)
      .HasForeignKey<Tid>(t => t.DeviceId)
      .IsRequired(false);

    builder.Entity<Tid>()
      .HasOne<Device>()
      .WithOne(d => d.Tid)
      .HasForeignKey<Device>(d => d.TidId)
      .IsRequired(false);
}
```

However, when I set the `Tid` on a `Device` and save, although the navigation property is set on the `Device`, the navigation property on the `Tid` is not set, meaning that I can't see what device is associated with the device.

Same goes the other way round, if I set the `Device` for a `Tid`, then the navigation property is set on the `Tid` correctly, but the one on the `Device` is not, so I can't see what TID is associated with the device.

Looking in the database, it looks like it created two foreign key links between the tables, and I guess only one of them is being set, depending on which entity I update...

[![enter image description here][1]][1]

Can anyone explain how I should have done this. Thanks.

  [1]: https://i.stack.imgur.com/EHEMj.png

### Include provider and version information

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.0

**Comment by MrYossu** [comment]
@ajcvickers Thanks for the reply, but I can't see how it answers my question.

If I understand that issue correctly, it's talking about having optional relationships with non-nullable FK constraints. That's not my question, as I would assume I'd need nullable FKs, as the relationship is optional.

My problem is that one-to-one relations in EF Core seem to require one side to be dependent on the other. In my case, the two entities are independent of each other, which is why I'm having problems working out how to model this.

Sorry if I misunderstood. Please can you clarify how that other issue would help me with my issue.

Thanks again

**Comment by ajcvickers** [comment]
@MrYossu In a normal FK, a principal entity with a matching key value must be found. In other words, the principal can only be optional in the sense that it can be null and not point to anything, but it can't be a value that doesn't match a principal value. Issue #13146 would allow the FK value to exist without it matching any principal value, thereby meaning that either side of the relationship can fully exist without the other side.

**Comment by MrYossu** [comment]
@ajcvickers Thanks for the clarification, I think I see what you mean.

However, given that the feature in #13146 hasn't been implemented (as far as I can see), how would I go about doing what I need today? Sorry if that's a dumb question, but I'm not sure I see a solution in there.

Thanks again.

**Comment by ajcvickers** [comment]
@MrYossu Currently, EF requires all relationships to be based on FKs, and FKs are considered constrained, so I don't think it's possible to do what you want to do with EF today.

**Comment by alexTr3** [comment]
wow I cant believe this is still an issue in 2025/2026.. we should not need to add the .Include to have the right foreign key id in a one to one relationship.. why would we include/load the full object when we just need the id to be set.. foreign key ids should never be null when they actually are not and they should not even be dependent on "Include".. you made it so confusing now
