### ISSUE TITLE
Add setting to make migration script creation use EXEC(string) for migrationBuilder.Sql(...) generation

### ISSUE THREAD

**Issue by ryancole** [dotnet/efcore#32526]
When creating an idempotent migration script, `migrationBuilder.Sql(...)` outputs TSQL that looks like the following, for example ...

```
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20231117070637_BoxLogfileToZipfile')
BEGIN
                    UPDATE BoxLogfiles
                    SET BoxZipfileId = u.BoxZipfileId
                    FROM RowsToUpdate AS u
                    WHERE Id = u.BoxLogfileId;
END;
GO
```

This makes it so that SQL Server still evaluates the SQL expression and it will fail even if the IF NOT EXISTS statements is not met. This can cause issues applying idempotent migrations to DBs that already have them.

Perhaps add a setting to make the output use EXEC(string) instead? Like the following, as suggested [here](https://stackoverflow.com/questions/19822843/t-sql-appears-to-be-evaluating-if-statement-even-when-the-condition-is-not-tru) ...

```
IF COL_LENGTH('Database_Name.dbo.Table_Name', 'Column_Name1') IS NOT NULL
BEGIN
    DECLARE @sql VARCHAR(MAX)
    SET @sql = 'UPDATE Table_Name
            SET Column_Name2 = (SELECT Column_Name3 FROM Table_Name2
                WHERE Column_Name4 = ''Some Value'')
            WHERE Column_Name5 IS NULL;

        UPDATE Table_Name
            SET Column_Name6 = Column_Name1
            WHERE Column_Name6 IS NULL;'
     EXEC(@sql)
END
```

I see that the documentation for efcore also mentions what I'm requesting [here](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#using-migrationbuildersql). How would I do this manually in the migration C# though? Rewrite the actual query to include EXEC? Why not just a feature that efcore would allow me to choose between the output style?

**Comment by ajcvickers** [comment]
@ryancole What version of EF Core are you using?

Note for triage: See https://github.com/dotnet/efcore/issues/12911. We need to investigate what we did and didn't do, and whether anything should change.

**Comment by ryancole** [comment]
> @ryancole What version of EF Core are you using?
> 
> Note for triage: See #12911. We need to investigate what we did and didn't do, and whether anything should change.

I'm using the following ...

```
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.12" />
```

**Comment by ajcvickers** [comment]
Note for triage: did some further investigation here. EXEC is used when EF generates the SQL, but not when the SQL is unknown, since we want to avoid parsing it do determine whether EXEC is appropriate. The custom SQL should  include EXEC if it is neeeded.
