### ISSUE TITLE
Column mapping is changed, if table splitting is introduced.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32521]
I have an issue with `IdentityUser` mapping.

If I just inherit from `IdentityDbContext` and check the model for `IdentityUser` this is how its properties are mapped to table:
> Property: IdentityUser.Id (string) Required PK AfterSave:Throw - Column: AspNetUsers.Id (TEXT) NonNullable)
Property: IdentityUser.AccessFailedCount (int) Required - Column: AspNetUsers.AccessFailedCount (INTEGER) NonNullable)
Property: IdentityUser.ConcurrencyStamp (string) Concurrency - Column: AspNetUsers.ConcurrencyStamp (TEXT) Nullable)
Property: IdentityUser.Email (string) MaxLength(256) - Column: AspNetUsers.Email (TEXT) Nullable)
Property: IdentityUser.EmailConfirmed (bool) Required - Column: AspNetUsers.EmailConfirmed (INTEGER) NonNullable)
Property: IdentityUser.LockoutEnabled (bool) Required - Column: AspNetUsers.LockoutEnabled (INTEGER) NonNullable)
Property: IdentityUser.LockoutEnd (DateTimeOffset?) - Column: AspNetUsers.LockoutEnd (TEXT) Nullable)
Property: IdentityUser.NormalizedEmail (string) Index MaxLength(256) - Column: AspNetUsers.NormalizedEmail (TEXT) Nullable)
Property: IdentityUser.NormalizedUserName (string) Index MaxLength(256) - Column: AspNetUsers.NormalizedUserName (TEXT) Nullable)
Property: IdentityUser.PasswordHash (string) - Column: AspNetUsers.PasswordHash (TEXT) Nullable)
Property: IdentityUser.PhoneNumber (string) - Column: AspNetUsers.PhoneNumber (TEXT) Nullable)
Property: IdentityUser.PhoneNumberConfirmed (bool) Required - Column: AspNetUsers.PhoneNumberConfirmed (INTEGER) NonNullable)
Property: IdentityUser.SecurityStamp (string) - Column: AspNetUsers.SecurityStamp (TEXT) Nullable)
Property: IdentityUser.TwoFactorEnabled (bool) Required - Column: AspNetUsers.TwoFactorEnabled (INTEGER) NonNullable)
**Property: IdentityUser.UserName (string) MaxLength(256) - Column: AspNetUsers.UserName (TEXT) Nullable)**

However, if I introduce table splitting like this:
```
public sealed record UserInfo(string Id, string? UserName);

sealed class AppDbContext : IdentityDbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseSqlite("DataSource=:memory:");
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.Entity<UserInfo>(b =>
        {
            var identityUserMetadata = builder.Entity<IdentityUser>().Metadata;
            var table = identityUserMetadata.GetTableName();
            var userNameProperty = identityUserMetadata.GetProperty(nameof(IdentityUser.UserName));

            b.ToTable(table);

            b.HasOne<IdentityUser>().WithOne().HasForeignKey<IdentityUser>(_ => _.Id);

            b.Property(_ => _.UserName).HasColumnName(userNameProperty.GetColumnName());
        });
    }
}
```

The mapping is changed to this one:
> Property: IdentityUser.Id (string) Required PK FK AfterSave:Throw - Column: AspNetUsers.Id (TEXT) NonNullable)
Property: IdentityUser.AccessFailedCount (int) Required - Column: AspNetUsers.AccessFailedCount (INTEGER) Nullable)
Property: IdentityUser.ConcurrencyStamp (string) Concurrency - Column: AspNetUsers.ConcurrencyStamp (TEXT) Nullable)
Property: IdentityUser.Email (string) MaxLength(256) - Column: AspNetUsers.Email (TEXT) Nullable)
Property: IdentityUser.EmailConfirmed (bool) Required - Column: AspNetUsers.EmailConfirmed (INTEGER) Nullable)
Property: IdentityUser.LockoutEnabled (bool) Required - Column: AspNetUsers.LockoutEnabled (INTEGER) Nullable)
Property: IdentityUser.LockoutEnd (DateTimeOffset?) - Column: AspNetUsers.LockoutEnd (TEXT) Nullable)
Property: IdentityUser.NormalizedEmail (string) Index MaxLength(256) - Column: AspNetUsers.NormalizedEmail (TEXT) Nullable)
Property: IdentityUser.NormalizedUserName (string) Index MaxLength(256) - Column: AspNetUsers.NormalizedUserName (TEXT) Nullable)
Property: IdentityUser.PasswordHash (string) - Column: AspNetUsers.PasswordHash (TEXT) Nullable)
Property: IdentityUser.PhoneNumber (string) - Column: AspNetUsers.PhoneNumber (TEXT) Nullable)
Property: IdentityUser.PhoneNumberConfirmed (bool) Required - Column: AspNetUsers.PhoneNumberConfirmed (INTEGER) Nullable)
Property: IdentityUser.SecurityStamp (string) - Column: AspNetUsers.SecurityStamp (TEXT) Nullable)
Property: IdentityUser.TwoFactorEnabled (bool) Required - Column: AspNetUsers.TwoFactorEnabled (INTEGER) Nullable)
**Property: IdentityUser.UserName (string) MaxLength(256) - Column: AspNetUsers.IdentityUser_UserName (TEXT) Nullable)**

It was `AspNetUsers.UserName` and now it is `AspNetUsers.IdentityUser_UserName`.

And UserInfo.UserName has the same mapping:
> Property: IdentityUser.UserName (string) MaxLength(256) - Column: AspNetUsers.IdentityUser_UserName (TEXT) Nullable)

However, if I explicitly reconfigure `IdentityUser`:
```
builder.Entity<IdentityUser>(b => b.Property(_ => _.UserName).HasColumnName("UserName"));
```

I get this exception:
> System.InvalidOperationException: 'IdentityUser.UserName' and 'UserInfo.UserName' are both mapped to column 'UserName' in 'AspNetUsers', but are configured with different maximum lengths ('256' and '').
 
If I define attribute this way:
```
public sealed record UserInfo(string Id, [StringLength(256)]string? UserName);
```
it still fails.

I have to explicitly define the target (maybe EF could support attributes applied to constructor args as well?) to make it work:
```
public sealed record UserInfo(string Id, [property: StringLength(256)]string? UserName);
```
And the mapping returns back to `UserName` instead of `IdentityUser_UserName`.

Ok, maybe the absence of data annotation attribute was the reason for different mapping? I comment out `IdentityUser` mapping once again:
```
// builder.Entity<IdentityUser>(b => b.Property(_ => _.UserName).HasColumnName("UserName"));
```
and `IdentityUser_UserName` is back ='(

If you are going to say that this behavior is be design, then I think this [feature request is relevant](https://github.com/dotnet/efcore/issues/32406): I should not be forced to reverse engineer a 3d party library to clone mapping details precisely as they defined in that library. There should be an option to tell EF: Map this property absolutely the same as that one.

Here is the [repo to reproduce](https://github.com/voroninp/TableSplitting)

EF Core version: 8.0.0
Database provider:  Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8.0
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.8.2)

**Comment by ajcvickers** [comment]
@voroninp The Identity model is notoriously difficult to customize. I wouldn't attempt it.

**Comment by voroninp** [comment]
I am not customizing Identity model. I just want  a pojection of `IdentityUser`.

**Comment by voroninp** [comment]
This mapping issue is not about Identity only:

> Full mappings:
Property: Full.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd - Column: Full.Id (INTEGER) NonNullable)
Property: Full.Prop1 (string) Required - Column: **Full.Prop1** (TEXT) NonNullable)
Property: Full.Prop2 (string) Required - Column: Full.Prop2 (TEXT) NonNullable)

> Part mappings:
Property: Part.Id (int) Required PK FK AfterSave:Throw - Column: Full.Id (INTEGER) NonNullable)
Property: Part.Prop1 (string) Required - Column: **Full.Part_Prop1** (TEXT) Nullable)

```
builder.Entity<Full>();

builder.Entity<Part>(b =>
{
    var metadata = builder.Entity<Full>().Metadata;
    var table = metadata.GetTableName();

    b.ToTable(table);

    b.HasOne<Full>().WithOne().HasForeignKey<Part>(_ => _.Id);
});
```

**Comment by voroninp** [comment]
@ajcvickers the are two columns unless I explicitly name them for both entities.

First, I had only `IdentityUser` and column's name was 'UserName`, then I added a projection `UserInfo` with table splitting, now I see two columns `UserName` and `IdentityUser_UserName`
To make both entities to target the same column, I must define the mapping explicitly both for `UserInfo` and `IdentityUser`.

**Comment by ajcvickers** [comment]
Yes, this is by-design.

**Comment by voroninp** [comment]
Then I am pointing back at #32406

Not only do I have to map properties explicitly for both entities, but I must also provide the same constraints. For example, `IdentityUser.UserName` property has a max length of 256 characters. And this is set somewhere as a fluent config, not as a `[StringLength]` attribute applied to `UserNane` property.

Without the requested feature I need to reverse engineer the code of the 3d party library to ensure mappings are equivalent.

There should be an option to reference an already existing model:
> Map property `A` of entity `Foo` equivalently to property `B` of entity `Bar`.

It's crucial for the case when `Bar` originates not from the code I own.

**Comment by AndriySvyryd** [comment]
This would be handled by #31978
