### ISSUE TITLE
is efcore 7 ro 8 supports BulkExtensions BatchUpdateAsync in a similar way

### ISSUE THREAD

**Issue by ByZhouhang** [dotnet/efcore#32527]
### 
in my project,  i use EFCore.BulkExtensions   for batch update (https://github.com/borisdj/EFCore.BulkExtensions  )

when i up to efcore 8  netcore 8    BulkExtensions   BatchUpdateAsync method is obsolute 

How can switch to a new way of writing without affecting the code  wrote before? (change BatchUpdateAsync to  efcore Executeupdate)

```C#
//BulkExtensions   write like this :
context.Items.Where(a => a.ItemId <= 500).BatchUpdate(a => new Item { Quantity = a.Quantity + 100 });

//in efcore 8 
context.Blogs
    .Where(b => b.Rating < 3)
    .ExecuteUpdate(setters => setters.SetProperty(b => b.Rating, b => b.Rating + 1));

```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)

**Comment by Xor-el** [comment]
> How can switch to a new way of writing without affecting the code wrote before? (change BatchUpdateAsync to efcore Executeupdate)

@ByZhouhang Other than writing an extension that wraps and calls `ExecuteUpdate`, I am not sure there is any other way.

**Comment by ajcvickers** [comment]
@ByZhouhang 

> How can switch to a new way of writing without affecting the code wrote before? (change BatchUpdateAsync to efcore Executeupdate)

This would be up to the maintainers of that package. As @Xor-el said, EF Core [supports bulk updates](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) that you might be able to use instead, but your code will need to be changed.

**Comment by ByZhouhang** [comment]
> @ByZhouhang
> 
> > How can switch to a new way of writing without affecting the code wrote before? (change BatchUpdateAsync to efcore Executeupdate)
> 
> This would be up to the maintainers of that package. As @Xor-el said, EF Core [supports bulk updates](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates) that you might be able to use instead, but your code will need to be changed.

At present, efcore batch updates are possible, but the writing feels a little cumbersome, the type must be specified, and the generic method is not supported, and there are plans to launch a similar way like EFCore.BulkExtensions

**Comment by roji** [comment]
@ByZhouhang please file a new isuse with exactly the problem(s) you're seeing with the API, including code to illustrate them - it's not clear what you mean by "the type must be specified" or "the generic method is not supported" (or what's cumbersome about the API).
