### ISSUE TITLE
Remove command logging extensions from LoggingExtensions

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#3255]
LoggingExtensions is a shared file and so should only contain methods that are generally useful.

**Comment by bricelam** [comment]
I would have put them in `Relational.Design`, but that isn't available on `uwp10.0` projects... I suppose I could use a shared (but not globally) source file.

**Comment by anpete** [comment]
That sounds good.

**Comment by rowanmiller** [comment]
Discussed and decided this doesn't matter
