### ISSUE TITLE
HasDefaultValueSql removal on AutoGen since EF Core 8 update

### ISSUE THREAD

**Issue by Daayal** [dotnet/efcore#32566]
Hello,

Since the EF Core 8 upgrade the HasDefaultValueSql is being removed for Guids and Dates. Now i am sure this is because i am setting something incorrectly but when i roll back to EF Core 7 it adds them back in.

I am also on the latest verion on EF Core Power Tools 

![image](https://github.com/dotnet/efcore/assets/153297517/0a770d99-6f5f-45ac-af75-e295b0d50efa)

![image](https://github.com/dotnet/efcore/assets/153297517/dc6dc546-3196-4d47-ac35-275f2f0d4a1c)

Settings

![image](https://github.com/dotnet/efcore/assets/153297517/5acf26a8-17b8-4615-b5ea-88b26b9c4700)
![image](https://github.com/dotnet/efcore/assets/153297517/51ced071-dfed-4070-8a7b-2a8ccecd63ba)
![image](https://github.com/dotnet/efcore/assets/153297517/95724819-e055-46f5-bea9-18580d929ae4)

**Comment by ajcvickers** [comment]
Please post the schema which, when scaffolded to a DbContext, will generate this error.
