### ISSUE TITLE
Custom value converter on primitive collections

### ISSUE THREAD

**Issue by CheloXL** [dotnet/efcore#32587]
I'm not sure if this is already implemented or not. Found some closed issues, but no documentation on it.

I have a column definition that is of type `IEnumerable<LanguageId>`. LanguageId is basically a value object that has a custom valueconverter/valuecomparer implemented and already registered in EF (and it's working fine when I have a column of type `LanguageId`).

Now, on the above example, I'm getting the following error: The 'IEnumerable<LanguageId>' property 'Installation.Languages' could not be mapped because the database provider does not support this type. Consider converting the property value to a type supported by the database using a value converter.

I understand the error message, but I already implemented a valueconverter that converts the object LanguageId from/to a primitive value (string). What I don't know is how to configure that property, so EF understands that it has to run the converter on every entry, much like when its working on a simple property.

Is there a way to do that? I would like to do so, so I can retain the ability to later query that column. Having to write a custom converter for the IEnumerable<> would not allow me to query the column via "Contains", for example.

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
@CheloXL I don't think this is currently possible; we will consider it. For now, primitive collections like this will need to be explicitly configured:

```C#
public void Configure(EntityTypeBuilder<Installation> builder)
{
	builder
		.PrimitiveCollection(e => e.Languages)
		.ElementType(e => e.HasConversion<LanguageId.EfCoreValueConverter, LanguageId.EfCoreValueComparer>());
	
	builder.ToTable("installations");
	builder.HasKey(x => x.Id);
}
```

**Comment by CheloXL** [comment]
Ah, perfect. I have no problem configuring the property. I didn't find on the documentation what you just posted (it would be great if that could be added to the primitive collection docs). 
Thank you very much!

**Comment by ajcvickers** [comment]
Related to #31413

**Comment by CodingOctocat** [comment]
@ajcvickers An important reason for using `PrimitiveCollection` is the need to support `Where + Any` operations, but `ValueConverter` will cause the query expression translate to fail.
