### ISSUE TITLE
The current provider doesn't have a store type mapping for properties of type 'DateIndex'.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32583]
I am running a custom SQL:
```CSharp
await dbContext.Database.ExecuteSqlAsync(
    $"""
    UPDATE RadioProgramBroadcasts AS ub
    SET
        PrecedingBroadcastId = Ids.PrecedingBroadcastId,
        FollowingBroadcastId = Ids.FollowingBroadcastId
    FROM
    (
        SELECT
        b.Id,
        lag(b.Id) OVER channelAndDate AS PrecedingBroadcastId,
        lead(b.Id) OVER channelAndDate AS FollowingBroadcastId
        FROM RadioProgramBroadcasts AS b
        JOIN RadioPrograms p
        ON b.ProgramInfoId = p.Id
        WHERE b."Date" = {broadcastDate}
        WINDOW channelAndDate AS (PARTITION BY p.ChannelId, b."Date" ORDER BY b.StartTimeSecondsPrecision)
    ) AS Ids
    WHERE ub.Id = Ids.Id;
    """, cancellationToken);
```
And I get the following exception:
```
System.InvalidOperationException: The current provider doesn't have a store type mapping for properties of type 'DateIndex'.
```

Here is how `DateIndex` type is defined:
```CSharp
public readonly record struct DateIndex : IComparable<DateIndex>, ISpanParsable<DateIndex>
{
    public readonly int Value;

    public DateIndex(int value)
    {
        Value = value;
    }
    ....
}
``` 

And its conversion is defined in `OnCOnfigureConventions` method:
```CSharp
configurationBuilder.Properties<DateIndex>(b =>
{
    b.HaveConversion<DateIndexToIntConverter>();
});
```

My expectation is that EF should  use the same value converter.
Here's what docs say:
> [FromSql](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.fromsql) can be used with any scalar type supported by your database provider. If you'd like to use a type not supported by your database provider, you can use [pre-convention configuration](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#pre-convention-configuration) to define a value conversion for it.

If this is by design and is not the case for `ExecuteSql` method, then it should be explicitly mentioned in xmldoc.  

Here's is [a repo](https://github.com/voroninp/ValueConverterIsNotUsedInExecuteSql)

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite)
Target framework:  .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8

**Comment by ajcvickers** [comment]
@voroninp Have you tried: https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#default-type-mapping

**Comment by voroninp** [comment]
@ajcvickers , alas, same error.

**Comment by dehghani-mehdi** [comment]
Same here with the following code:

```
     _db.Database.ExecuteSqlRawAsync("DELETE dbo.Carts WHERE CartId=@cartId", new { cartId = "D080AF0B-6F74-422A-8648-879F324D1379" });
```

The `CartId` column type in the database is `UNIQUEIDENTIFIER`.

**Comment by johnwc** [comment]
@AndriySvyryd I am getting this same error with current release of EF, but using the `FromSqlInterpolated` method. Using accountId in linq to sql works fine. Is this supposed to be fixed for FromSql... methods as well?

Calling `Accounts.FromSqlInterpolated($"EXEC [user].pGetAccounts {accountId}")`

**Comment by roji** [comment]
@johnwc can you please open a new issue with a minimal, runnable repro (a small console program), and make sure that you're using EF Core 9.0?
