### ISSUE TITLE
How to remove children when DeleteBehaviour is set to NoAction?

### ISSUE THREAD

**Issue by Woudjee** [dotnet/efcore#32596]
Hi,

I have the following entity:

```
public class LineLoadEntity : LoadEntity
{
    public LineLoadEntity(VectorEntity startPosition, VectorEntity endPosition, VectorEntity forceVectorStart, VectorEntity forceVectorEnd, string description) : base(description)
    {
        StartPosition = startPosition;
        StartPositionId = startPosition.Id;

        EndPosition = endPosition;
        EndPositionId = endPosition.Id;

        ForceVectorStart = forceVectorStart;
        ForceVectorEndId = forceVectorStart.Id;

        ForceVectorEnd = forceVectorEnd;
        ForceVectorEndId = forceVectorEnd.Id;
    }

    public LineLoadEntity()
    {

    }

    public int StartPositionId { get; set; }
    public virtual VectorEntity StartPosition { get; set; }

    public int ForceVectorStartId { get; set; }
    public virtual VectorEntity ForceVectorStart { get; set; }

    public int EndPositionId { get; set; }
    public virtual VectorEntity EndPosition { get; set; }

    public int ForceVectorEndId { get; set; }
    public virtual VectorEntity ForceVectorEnd { get; set; }
}
```

And the following setup:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<LineLoadEntity>().HasOne(entity => entity.ForceVectorStart).WithOne().OnDelete(DeleteBehavior.NoAction);
    modelBuilder.Entity<LineLoadEntity>().HasOne(entity => entity.ForceVectorEnd).WithOne().OnDelete(DeleteBehavior.NoAction);
    modelBuilder.Entity<LineLoadEntity>().HasOne(entity => entity.StartPosition).WithOne().OnDelete(DeleteBehavior.NoAction);
    modelBuilder.Entity<LineLoadEntity>().HasOne(entity => entity.EndPosition).WithOne().OnDelete(DeleteBehavior.NoAction);

    base.OnModelCreating(modelBuilder);
}
```

I need that setup, because otherwise I have multiple cascade paths. However, when quering this:

```
            _context.RemoveRange(_context.LineLoads.Include(load => load.StartPosition).Include(load => load.EndPosition).Include(load => load.ForceVectorEnd).Include(load => load.ForceVectorStart));

```

I expect that the children are removed as well. How do I achieve this without loading the loads into memory?

**Comment by ajcvickers** [comment]
@Woudjee Are you asking how to cascade delete children without loading them into memory when the database is not configured to perform a cascade delete? If so, EF doesn't do that automatically, but see #18960 and consider using [ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete).

**Comment by Woudjee** [comment]
@ajcvickers that's right, your interpretation is correct. Thank you, I will review the posts you suggested later today :)

**Comment by Woudjee** [comment]
@ajcvickers I have read the links that yo usent, but I must say that I was not able to implement a concete solution to my problem. This `LineLoadEntity` belongs to a building if you go all the way back to the parent. Something like `ExecuteDelete()` could work if I would give all my entities a `buildingId`. I guess this would be kind of efficient, but it also seems like a naughty workaround. Don't you agree?

Do you happen to have any other suggestions to improving this?

**Comment by ajcvickers** [comment]
@Woudjee Generally people don't do this. Instead they load the graph and let EF handle the deletes. However, that can be inefficient, hence #18960. But that isn't implement yet, so for now, load the graph if you want it easy, or implement your own cascading implementation using `ExecuteDelete`, which should be faster, but is certainly not trivial to implement.

**Comment by Woudjee** [comment]
Yeah I see, so if I understand correctly. This (let's call it) feature is something that is in the back of your minds and will be implemented later? Perhaps EF 10?

Then I guess the building id property for all my entities is my only option. Depending on the project, I have around 50.000 - 250.000 entities that have to be removed occasionally (that are stored in this parent-child hiarchy). My current removal time is 23.000 ms for 50.000 entities. So you can see why this is a big problem for me.
