### ISSUE TITLE
Calling Contains inside Where produces SQL with OPENJSON error

### ISSUE THREAD

**Issue by ttosello** [dotnet/efcore#32623]
I have the following code:

```
var providers = await context.Employees
    .Where(w => typeIds.Contains(w.TypeId))
    .ToListAsync();
```

typeIds is an array of integers.

When it executes, the following error is thrown:

`Incorrect syntax near '$'.`

The SQL being generated is as follows:

```
exec sp_executesql N'SELECT [e].[Id], [e].[Commission], [e].[DeletionDate], [e].[Email], [e].[FeeGuideId], [e].[FirstName], [e].[InactivationDate], [e].[LastName], [e].[Password], [e].[TierLevel], [e].[Professional Title], [e].[TypeId], [e].[UserName]
FROM [Employees] AS [e]
WHERE [e].[TypeId] IN (
    SELECT [t].[value]
    FROM OPENJSON(@__typeIds_0) WITH ([value] int ''$'') AS [t]
)',N'@__typeIds_0 nvarchar(4000)',@__typeIds_0=N'[10,8,5]'
```

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system:  Windows 11
IDE: Visual Studio 2022 17.8.3

**Comment by ttosello** [comment]
This error was being thrown because the compatibility of the SQL database was set to 2008.  Once I set it to 2019, the error resolved.

**Comment by ErikEJ** [comment]
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#contains-in-linq-queries-may-stop-working-on-older-sql-server-versions
