### ISSUE TITLE
SqlQuery<T>() and complex properties

### ISSUE THREAD

**Issue by FM1973** [dotnet/efcore#32646]
When I call ```SqlQuery<T>``` it throws an exception if an entity has one or more complex properties.

"System.InvalidOperationException: The property 'CustomerListResponse.Address' of type 'Address' appears to be a navigation to another entity type. Navigations are not supported when using 'SqlQuery". Either include this type in the model and use 'FromSql' for the query, or ignore this property using the '[NotMapped]' attribute."

Address is configured as a complex property of the class customer.

Is there an option in ef core 8 like in dapper (splitOn) to map the complex types into my target type?

Or do I have to make a flat object and then map it manually?

Thanks for your help.

**Comment by ajcvickers** [comment]
@FM1973 `SqlQuery` is used for queries without a defined model--that is the model is built on-demand by convention. It therefore will never contain complex type mappings. Consider using `FromSql` if you have a mapped entity type with mapped complex properties that you want to query with raw SQL.

**Comment by FM1973** [comment]
@ajcvickers The reason I´d like to use ```SqlQuery``` is because I´d like to query a view (not all proprties) and to do it without the use of the change tracker. In dapper one can do so. But I have to say I´m not a big fan of dapper and like to use only one ORM. But I will have a look at FromSql.

**Comment by ajcvickers** [comment]
@ajcvickers Both `FromSql` and `SqlQuery` are equally fine with views and tables. You can do a no-tracking query using `FromSql`.

**Comment by FM1973** [comment]
@ajcvickers does ```fromSql``` return an IQueryable likr ```SqlQuery``` ?
