### ISSUE TITLE
What's the fluent API counterpart of ComplexTypeAttribute?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32655]
How do I declare type as a complex type with fluent mapping API?

`ComplexProperty` must be called on the entity, but I just want the same effect as `[ComplexType]` has.

**Comment by ajcvickers** [comment]
```C#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.ComplexProperties<Contact>();
    configurationBuilder.ComplexProperties<Address>();
    configurationBuilder.ComplexProperties<PhoneNumber>();
}
```

**Comment by voroninp** [comment]
Thanks.

**Comment by voroninp** [comment]
@ajcvickers But how do I configure read-only properties mapping then?

```
public readonly record struct InclusiveDatesRange
{
    public DateOnly Start { get; }
    public DateOnly End { get; }

    public InclusiveDatesRange(DateOnly start, DateOnly end)
    {
        if (end < start)
        {
            throw new ArgumentException($"Start '{start}' cannot be later than end '{end}'.");
        }

        Start = start;
        End = end;
    }
}
```
It's a `readonly struct` so properties cannot have private setters.

Currently I configure this for entity:
```
modelBuilder.Entity<DataActualityPeriod>(b =>
{
    b.HasAlternateKey(e => e.Code);
    b.HasAlternateKey(e => new { e.DatesRange.Start, e.DatesRange.End });

    b.ComplexProperty(
        e => e.DatesRange,
        b =>
        {
            b.Property(b => b.Start);
            b.Property(b => b.End);
        });
});
```

But there's no overload of `ComplexProperties` which lets me configure the mapping.

**Comment by voroninp** [comment]
@ajcvickers , btw, `b.HasAlternateKey(e => new { e.DatesRange.Start, e.DatesRange.End });` this does not work =(

**Comment by voroninp** [comment]
And how do I set index on properties of complex type?

**Comment by roji** [comment]
@voroninp that's https://github.com/dotnet/efcore/issues/31246.

**Comment by voroninp** [comment]
@ajcvickers Wait a second. Not planned what? Combining mapping details with `configurationBuilder.ComplexProperties<TComplexType>();` ? 
I mean [this commen](https://github.com/dotnet/efcore/issues/32655#issuecomment-1865991064)
