### ISSUE TITLE
Translatable columns

### ISSUE THREAD

**Issue by rzurlo** [dotnet/efcore#32657]
I have this need. 
Some tables in my database have translatable columns, and the translations are stored in another table. When I include this table, I would like the columns with the translation to be replaced with those from the translation table (via a raw query, I load the entire table with translatable columns translated) using keys. 
It would be nice to replace the include with a custom include, but the include requires a navigation property, or I don't know if there's another way to do it. 
What is the best way to solve this problem? I could use the dbcommandinterceptor, but I see it as quite risky. 
I welcome suggestions. 
Thank you.

RZ

**Comment by roji** [comment]
It's not easy to understand exactly what you're trying to do - it's always a good idea to include a database schema and some code. What's preventing you from simply using regular Includes to the translation table and getting the translations from there?

**Comment by zraffaele** [comment]
Before this implementation, texts were not translated. By texts, I mean not just the label or menu text, but the actual texts, such as the description of a type of task (Apps) called AppsTypes in our CRM.
To avoid disrupting the internal management, we introduced a table called TranslateText, which contains all translations of all tables that can contain a translatable column, such as the description of AppsTypes. The table is structured as follows:
ID uniqueidentifier
TableName varchar(100)
FieldName varchar(100)
Pkey varchar(200)
Lang varchar(2)
Text nvarchar(MAX)
Where TableName is the table name (AppsTypes), FieldName (Description) is the translatable column, Pkey (Code) is the table key, Lang is the language, and Text is the translated text. All this information is saved in metadata tables.
Currently, when we execute LINQ queries, we start from the parent table 'Apps,' which has navigation to the AppsTypes table, and load the list of Apps with:

var events = CurrentContext().Set<Apps>().AsNoTracking<Apps>()
    .Include(x => x.app_TipoAppNavigation)
However, this would load the description of the table, not the translatable text. The purpose of this post is to address how to load the values of the Description column from the TranslateText table in a generic way.

We have written a custom function for reading the table with translatable texts, which I have provided below:

public IQueryable<T> GetAllTranslated(string contentLanguage)
{
    string tableName = typeof(T).Name;
    var translatableFields = CurrentContext().Set<MetabaseTable>()
        .Where(x => x.Name == tableName)
        .Select(x => new
        {
            Pk = x.PK,
            Fields = x.MetabaseColumns.Where(s => s.AllowTranslation).Select(mc => new
            {
                mc.FieldName
            })
        }).FirstOrDefault();
    if ( translatableFields is null ||!translatableFields.Fields.Any())
    {
        return GetAllNoTracking().AsQueryable();
    }
    System.Text.StringBuilder sqlgframent = new System.Text.StringBuilder();
    System.Text.StringBuilder columnStringBuilder = new System.Text.StringBuilder();
    var columns = GetSchema(tableName);
    int count = 0;
    foreach (var col in columns)
    {

        if (translatableFields.Fields.Any(a => a.FieldName == col.ColumnName))
        {
            count++;
            columnStringBuilder.Append(($"CASE WHEN [t{count}].Text IS NOT NULL THEN [t{count}].Text ELSE A.[{col.ColumnName}] END AS [{col.ColumnName}],"));
        }
        else
            columnStringBuilder.Append(($"A.{col.ColumnName},"));
    }

    sqlgframent.AppendLine($"SELECT {columnStringBuilder.ToString(0, columnStringBuilder.Length - 1)} FROM {tableName} A ");

    count = 0;
    var primaryKey = translatableFields.Pk.Contains(',') ? $"CONCAT(A.{translatableFields.Pk})" : $"A.{translatableFields.Pk}";
    foreach (var item in translatableFields.Fields)
    {
        count++;
        sqlgframent.AppendLine($"LEFT OUTER JOIN TranslateText  T{count} ON CAST({primaryKey} as varchar(200)) = T{count}.Pkey AND [t{count}].[TableName] = '{tableName}' AND T{count}.FIELDNAME = '{item.FieldName}' AND [t{count}].[Lang] = N'{contentLanguage}'");
    }
    return CurrentContext().Set<T>().FromSqlRaw(sqlgframent.ToString()).AsQueryable();
}

My idea was to implement this code directly in a custom Include or ThenInclude, aggregating any previous includes, so as not to disrupt all existing calls. I have tried various approaches without results.
I'm not sure if this is the right path to take or if there are other ways or approaches.
I hope this explanation is sufficient.

**Comment by rzurlo** [comment]
Hi,
does anyone have any ideas?
Thanks

**Comment by ajcvickers** [comment]
@rzurlo I don't think there is a simple way to extend the `Include` functionality like this, but @maumar or @roji might have a better idea.
