### ISSUE TITLE
About call SqlQueryRaw

### ISSUE THREAD

**Issue by dinhsacphd** [dotnet/efcore#32654]
Hi. 
I have the following suggestion about the SqlQueryRaw(string sql, params object[ ]) method in case there are arguments, so
Added Overload method: SqlQueryRaw(string sql, params List<Argument>)
When calling SqlQueryRaw(string sql, params List<Argument>), we do not have to pass the parameter names (if any) to the method call.

public class Arguments
{
     public string? name { get; set; set; }
     public object? value { get; set; set; }
}

Best regards...!

Note: Sorrry, my English not good.

**Comment by ajcvickers** [comment]
`params List<Argument>` is not valid. Params requires an array type.
