### ISSUE TITLE
The timeout occurred because the timestamp function was used when querying a time field, which caused the timeout.

### ISSUE THREAD

**Issue by gzj132** [dotnet/efcore#32667]
DbContext.Set.Where(_ => _.DateTime == DateTime.Now)

EF Core version:7.0
Database provider: (Microsoft.EntityFrameworkCore.MySql)
Target framework: (.NET 6.0)
Operating system:linux / windows 
IDE: (Visual Studio 2022 17.4)

I'm using EF Core 7 in .NET 6, with MySQL version 5.5.42. I encountered a timeout error while executing a SQL query. I'm particularly interested in understanding this error. Upon checking the MySQL console, I found that the timeout occurred because EF generated a SQL statement with a timestamp function when querying a datetime field. The generated SQL looked like `WHERE date >= timestamp('2023-21-14 xxxxxxx')`, which caused my date field to not trigger the index. Could you please advise me on how to modify this behavior without using the timestamp function and ensure it applies globally?

**Comment by roji** [comment]
@gzj132 the MySQL provider isn't maintained here, and as this seems to be a question about the specific SQL it generates for MySQL, you'll need to ask the maintainers.

However, the generated SQL you quote above doesn't seem to correspond to the LINQ query (the SQL has a `>=`, the LINQ query has a `==`). It's important to be very precise in what you quote, i.e. which exact LINQ query was translated to which exact SQL, and why you think that translation may be wrong.

**Comment by gzj132** [comment]
> @gzj132 the MySQL provider isn't maintained here, and as this seems to be a question about the specific SQL it generates for MySQL, you'll need to ask the maintainers.
> 
> However, the generated SQL you quote above doesn't seem to correspond to the LINQ query (the SQL has a `>=`, the LINQ query has a `==`). It's important to be very precise in what you quote, i.e. which exact LINQ query was translated to which exact SQL, and why you think that translation may be wrong.


Thank you for your response. Allow me to rephrase it: My LINQ query looks something like this: `DbContext.Set.Where(_ => _.DateTime >= DateTime.Now)`. When I checked the MySQL console, this LINQ query was translated into SQL as `select * from table where DateTime >= timestamp('2023-12-14 xxxxxxx')`. Due to the use of the timestamp function in this search condition, my index became ineffective. I need to prevent the generated SQL from using the timestamp function and make my index work again. So, which team should I seek help from?

**Comment by roji** [comment]
Well, what kind of SQL do you want to see here exactly? The SQL above seems to correspond to what you wrote in your LINQ query.

You can try extracting the `DateTime.Now` out of the LINQ query, so that it gets parameterized - maybe that might help:

```c#
var now = DateTime.Now;
var x = context.Blogs.Where(b => b.DateTime >= now);
```

**Comment by gzj132** [comment]
> @gzj132 the MySQL provider isn't maintained here, and as this seems to be a question about the specific SQL it generates for MySQL, you'll need to ask the maintainers.
> 
> However, the generated SQL you quote above doesn't seem to correspond to the LINQ query (the SQL has a `>=`, the LINQ query has a `==`). It's important to be very precise in what you quote, i.e. which exact LINQ query was translated to which exact SQL, and why you think that translation may be wrong.

@roji

**Comment by gzj132** [comment]
> Well, what kind of SQL do you want to see here exactly? The SQL above seems to correspond to what you wrote in your LINQ query.
> 
> You can try extracting the `DateTime.Now` out of the LINQ query, so that it gets parameterized - maybe that might help:
> 
> ```cs
> var now = DateTime.Now;
> var x = context.Blogs.Where(b => b.DateTime >= now);
> ```

@roji Yes, that's how I've been handling it all along. I am very concerned about EF performance issues, but this approach doesn't solve the problem of adding window functions to the query condition in SQL, which is fatal to my SQL performance.

Do you have any other suggestions? I have always been checking the SQL statements generated by LINQ in the command window. The generated statements are parameterized. It wasn't until today when I checked the MySQL console that I discovered the direct use of MySQL window functions in the parameterized query. I really don't understand why it is done this way.

**Comment by roji** [comment]
@gzj132 the SQL you showed above doesn't use window functions it's just a simple function call. In fact, it really shouldn't affect index usage; calling functions in SQL is perfectly fine in most situations, and is the right translation for e.g. the LINQ query you wrote above.

If you'd like to dig deeper, I suggest dumping the query plan for the two full SQLs: one with the function (as generated by EF), and another e.g. with a parameter; if the plans are indeed different and the function causes the index to not get used, that's something to discuss with people more knowledgeable about MySQL, and possibly the maintainers of the provider (though I'd b very interested in the results).

But as things are, you haven't really provided the information needed to see a problem...

**Comment by gzj132** [comment]
> @gzj132 the SQL you showed above doesn't use window functions it's just a simple function call. In fact, it really shouldn't affect index usage; calling functions in SQL is perfectly fine in most situations, and is the right translation for e.g. the LINQ query you wrote above.
> 
> If you'd like to dig deeper, I suggest dumping the query plan for the two full SQLs: one with the function (as generated by EF), and another e.g. with a parameter; if the plans are indeed different and the function causes the index to not get used, that's something to discuss with people more knowledgeable about MySQL, and possibly the maintainers of the provider (though I'd b very interested in the results).
> 
> But as things are, you haven't really provided the information needed to see a problem...

Thanks for your advice. Best wishes
