### ISSUE TITLE
is  ExecuteUpdateAsync bug？

### ISSUE THREAD

**Issue by ByZhouhang** [dotnet/efcore#32684]
##  test env

A table in the sqlserver database has a column named UpdateTime, and the type is datetime  or datetime2

### test code

```C#
  await _repository.Where<Subject>(t=>t.Id==find.Id).ExecuteUpdateAsync(t => t.SetProperty(t => t.UpdateTime, u => Convert.ToDateTime("2022-12-12")));

```
when type is datetime, update failed

```C#
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (121ms) [Parameters=[@__find_Id_0='40c10000-9b8e-98fa-4f7c-08da32f41c91'], CommandType='Text', CommandTimeout='30']
UPDATE [s]
SET [s].[UpdateTime] = '2022-12-12T00:00:00.0000000',
    [s].[UpdateUserId] = '95455b8a-2367-40b9-102e-08da0ca34b8d'
FROM [Subject] AS [s]
WHERE [s].[Id] = @__find_Id_0
```
when type is datetime2  update success

```C#
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (34ms) [Parameters=[@__find_Id_0='40c10000-9b8e-98fa-4f7c-08da32f41c91'], CommandType='Text', CommandTimeout='30']
UPDATE [s]
SET [s].[UpdateTime] = '2022-12-12T00:00:00.0000000',
    [s].[UpdateUserId] = '95455b8a-2367-40b9-102e-08da0ca34b8d'
FROM [Subject] AS [s]
WHERE [s].[Id] = @__find_Id_0
```
###  question?
I have a lot of tables, but I don't want to change from datetime to datetime2 because there are too many fields, what should I do, can I update without error

**Comment by roji** [comment]
@ByZhouhang please post a minimal, runnable repro - the above doesn't even show an exception or say how the update failed.

Also, make sure you tell EF that your column is actually a `datetime` and not a `datetime2`, because otherwise EF defaults to mapping .NET DateTime to SQL Server `datetime2`.

**Comment by ByZhouhang** [comment]
> @ByZhouhang please post a minimal, runnable repro - the above doesn't even show an exception or say how the update failed.
> 
> Also, make sure you tell EF that your column is actually a `datetime` and not a `datetime2`, because otherwise EF defaults to mapping .NET DateTime to SQL Server `datetime2`.

thanks ，i found default is datetime2, when i want to use datetime ,i should declare [Column(TypeName = "datetime")]  in domain entity,it will generate right sql
