### ISSUE TITLE
Entity Framework Core in Visual Studio 2022 Migrations freezes (hangs) during migrations (example Add-Migration)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32693]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entity-Framework-Core-in-Visual-Studio-2/10544625)._

---
[severity:It's more difficult to complete my work]
I am working on a project build using Visual Studio 2022.  Before this issue started, I was able to add migrations, remove migrations and update database fine.  Yesterday, I added a new migration and noticed it hanging in the Powershell Package Manager console.   Doing things such as Ctrl-C does not return control to the console.  Visual Studio continues to work as normal.   Closing and restarting Visual Studio is the only thing that stops it.  I re-ran the migration command using -Verbose and noticed everything looks fine until it reaches the DBContext.  I have tried rolling back my migrations, deleting my database and starting the migrations from scratch and commenting out code in the DBContext to make it as simple as possible.  I even deleted the DBContext and create another simple DBContext.  I updated Visual Studio.  Restarted my computer.  Nothing I tried has worked.  It freezes once it reaches the DBContext.

---
#### Feedback Bot on 12/20/2023, 02:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
