### ISSUE TITLE
Redis provider

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#327]

**Comment by wangkanai** [comment]
@rowanmiller Do you have a roadmap for Redis Cache Provider?

**Comment by rowanmiller** [comment]
@wangkanai not at this stage, we're currently planning for the next set of features we want to tackle.

**Comment by divega** [comment]
Consider #855.

**Comment by ajcvickers** [comment]
Closing this as we do not plan to implement and maintain a Redis provider for EF Core. However, we would be supportive of a community effort to create such a provider.
