### ISSUE TITLE
Casting to 'SequentialDataReader' problem

### ISSUE THREAD

**Issue by AmirHeydari** [dotnet/efcore#32707]
Hi,
Does anyone know what the problem is?

```C#
public class Province : Entity<byte>
{
      public string Name { get; private set; }
	  ...
      public ICollection<City> Cities { get; } = new List<City>();
 }

public class City : Entity<int>
{
    public byte ProvinceId { get; private set; }
    ...
    public Province Province { get; private set; }
}

//In service
 public async ValueTask<Province> GetByIdAsync(byte id)
    {
        return await dbContext.Set<Province>()
                .Include(d => d.Cities.OrderBy(c => c.Name))
                .SingleOrDefaultAsync(d => d.Id == id);
}
```

If I remove Include, it works well.
I have several entities and relationships, but they have no any problem!

EF Core version: 8
Database provider: SqlServer
Target framework: 8

error is:

Unable to cast object of type 'SequentialDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.\r\n Stack :    at lambda_method1112(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)\r\n   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateIncludeCollection>g__ProcessCurrentElementRow|23_0[TIncludingEntity,TIncludedEntity](<>c__DisplayClass23_0`2&)\r\n   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection[TIncludingEntity,TIncludedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, SingleQueryResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, IReadOnlyList`1 parentIdentifierValueComparers, IReadOnlyList`1 outerIdentifierValueComparers, IReadOnlyList`1 selfIdentifierValueComparers, Func`5 innerShaper, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)\r\n   at lambda_method1114(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\r\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\r\n

**Comment by ErikEJ** [comment]
@AmirHeydari What is your connection string?

**Comment by AmirHeydari** [comment]
Hi @Erik

"Application Name=Abc;Data Source=.;Initial Catalog=GeneralDb;Integrated Security=True;Persist Security Info=False;Encrypt=False;"

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by roji** [comment]
@AmirHeydari can you please submit a minimal code sample? It's really unclear what exactly is going from the bits and snippets above. If you could also fix the stack trace so that it's readable, that would help as well.

**Comment by AmirHeydari** [comment]
Definitely @roji 
I will try to do this

**Comment by AmirHeydari** [comment]
I found the reason ;-)
I had an interceptor that affected dbContext behavior.
