### ISSUE TITLE
Which is the best methods to test EF Core based applications

### ISSUE THREAD

**Issue by iamdotnet6** [dotnet/efcore#32724]
I have a .NET 6 based Console application which uses MySQL (Pomelo.EnityFrameworkCore.MySql 7.0.0) package to fetch the data from database. Now, to write xUnit test cases for methods defined, I have three ways to go with: 

1. **Mocking** DbContext and DbSet
2. **InMemoryDatabase**
3. **SQLite** 

I have tested all the above methods and below is my observation.

If I go with:
1. **Mocking** then I am able to write and run the test cases successfully, _but it seems to be complicated and lengthy way_. 
2. **InMemoryDatabase** then getting an error "_Relational-specific methods can only be used when the context is using a relational database provider_" .
3. **SQLite** then my test cases able to run but have to done some modification in main code project which is commenting out the code for _Collation as SQLite doesn't supports some collation_. 

**Goal:**
My goal is to write efficient xUnit test cases and I'm not getting which methods should I go without using prod db. Any Ideas/thoughts or suggestions will be highly appreciated!

**Comment by iamdotnet6** [comment]
@roji do you have any code reference on how to use **Testcontainers** with EF Core?

**Comment by ajcvickers** [comment]
@iamdotnet6 https://devblogs.microsoft.com/dotnet/efcore-mongodb/ covers the basics. It uses MongoDB, but the principles are the same for other databases.

**Comment by ErikEJ** [comment]
https://dotnet.testcontainers.org/modules/mssql/

**Comment by iamdotnet6** [comment]
thanks @ajcvickers @ErikEJ @roji for sharing the information! :)
