### ISSUE TITLE
API request failed application stops automatically 

### ISSUE THREAD

**Issue by karthik9728** [dotnet/efcore#32723]
I've created .Net 8 API Project with EF Core version of 8 migration table creation are working but In controller I've used DbContext file to perform CURD operation but it failed application crashed and closes automatically, I tried even try catch block its not even throwing error it directly crash the application.

```
public class EmployeeController : ControllerBase
 {
     private readonly ApplicationDbContext _context;
     public EmployeeController(ApplicationDbContext context)
     {
         _context = context; 
     }

     [HttpPost]
     public ActionResult Create(Employee employee)
     {
         try
         {
             if (!ModelState.IsValid)
             {
                 return BadRequest(ModelState);
             }

             _context.Employee.Add(employee);
             _context.SaveChanges();

             return Ok();
         }
         catch (Exception ex)
         {

             throw ex;
         }
     }
 }
```

I find the issue in my data model, I've one to one relationship, where i add **new keyword for EmployeeDetails** when I removed new keyword then its working fine, but still wonder why without giving error or throw exception it simply close the entire application automatically.

```
previous code

public class Employee
 {
     [Key]
     public int EmployeeId { get; set; }

     [Required]
     public string FirstName { get; set; } = string.Empty;

     public string? MiddleName { get; set; } = string.Empty;

     [Required]
     public string LastName { get; set; } = string.Empty;

     [Range(1980,2100,ErrorMessage = "Employed year should be between 1980 to 2100 only")]
     public int EmployedFrom { get; set; }

     //One to One Relationship
     public virtual EmployeeDetails EmployeeDetails { get; set; } = new();
}

---------------------------------------------------------------------------------------------------------------------------------------
updated code 

public class Employee
 {
     [Key]
     public int EmployeeId { get; set; }

     [Required]
     public string FirstName { get; set; } = string.Empty;

     public string? MiddleName { get; set; } = string.Empty;

     [Required]
     public string LastName { get; set; } = string.Empty;

     [Range(1980,2100,ErrorMessage = "Employed year should be between 1980 to 2100 only")]
     public int EmployedFrom { get; set; }

     //One to One Relationship
     public virtual EmployeeDetails EmployeeDetails { get; set; }
}```

EF Core version:8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system: Windows 11 Pro
IDE: (Visual Studio 2022 17.9.0 Preview 2.1)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by karthik9728** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I try to re-create the issue but after updating visual studio community, everything works fine but still can't figure it out its EF Core issue or VS Community issue.
