### ISSUE TITLE
ThenInclude with GroupBy unexpected behavior 

### ISSUE THREAD

**Issue by daniel18acevedo** [dotnet/efcore#32725]
### Include your code
```C#
IQueryable<Request> requestsQuery = _dbContext.Requests
            .Include(r => r.Category)
                .ThenInclude(c => c.ParentCategory)
            .Where(r => r.Category.IsActive);

        IQueryable<IGrouping<Category, Request>> requestsByCategory = requestsQuery
            .GroupBy(r => r.Category)
            .OrderBy(g => g.Key.Name);

        
        var requestsByCategoryAndSubCategorySummary = await requestsByCategory
            .Select(g => new ResultGroupByCategoryQuery
            {
                Category = g.Key,
                Parent = g.Key.ParentCategory,
                Summary = new CategoryRequestsSummary
                {
                    CategoryId = g.Key.CategoryId,
                    Name = g.Key.Name
                }
            })
            .ToListAsync()

// -----------
public class Request
{
      public Category Category { get; set; }
}

public class Category
{
      public Guid CategoryId { get; set; }
      public string Name { get; set; }
      public Guid? ParentCategoryId { get; set; }
      public bool IsActive { get; set; }
      public Category ParentCategory { get; set; }
}

public class ResultGroupByCategoryQuery
{
     public Category Category { get; set; }
     public Category Parent { get; set; }
     public CategoryRequestsSummary Summary { get; set; }
}

public class CategoryRequestsSummary
{
     public Guid CategoryId { get; set; }
     public string Name { get; set; }
}
```

### Include stack traces
```
Parent property is being null but Category gets included just fine
```

### Include provider and version information

EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
@daniel18acevedo can you please include a runnable, minimal repro? The above is just a query - we don't have your .NET types or the model configuration. A minimal console program would be ideal.

**Comment by daniel18acevedo** [comment]
> @daniel18acevedo can you please include a runnable, minimal repro? The above is just a query - we don't have your .NET types or the model configuration. A minimal console program would be ideal.

I added the types, a minimal console program is still necessary?

**Comment by roji** [comment]
In general yes. We very frequently get bits and pieces like this, and it turns out that there was something e.g. in OnModelCreating that was actually the source of the problem. So as a general rule we ask submitters to provide a console program - that shouldn't be hard to do given what you've already pasted above.

**Comment by daniel18acevedo** [comment]
@roji I wasn't able to reproduce this in a separate context with a simple dbContext, so there must be some sort of configuration in the original dbContext that is causing this. I can't replicate exactly the original dbContext since is not in my domain. The issue is still happening in the app, but you can close the ticket if you want
