### ISSUE TITLE
[RevEng] TableSelection and TableSelectionSet implementation breaks SQLCE

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3272]
The SQL CE engine has not concept of "schema", so the checks on schema in the .Allows and .Matches methods and method signatures causes the SQLCE provider to be not able to use table filtering @lajones

**Comment by lajones** [comment]
@ErikEJ Can you expand a bit more? I deliberately allowed the concept of setting `TableSelection.Schema` to `TableSelection.Any` (i.e. "*") for providers such as SQLCE that don't understand the concept of a schema. All of your table selections should look like `*.<table_name>` and after that the `TableSelectionSet` should work as is.

**Comment by ErikEJ** [comment]
So here: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/src/Design40/ReverseEngineering/SqlCeMetaDataModelProvider.cs#L195

I should use a "*" for schema name?

**Comment by natemcmaster** [comment]
@ErikEJ SQLite has the same issue. This is how we get around it. https://github.com/aspnet/EntityFramework/blob/80108e1f83c79af89c594500e84f62f65cf076d0/src/EntityFramework.Sqlite.Design/ReverseEngineering/SqliteMetadataModelProvider.cs#L63

**Comment by lajones** [comment]
@ErikEJ Use TableSelection.Any (which is underneath the covers * but could be changed).

**Comment by ErikEJ** [comment]
@natemcmaster @lajones Thanks, guys!
