### ISSUE TITLE
Connecting to an database on mac...

### ISSUE THREAD

**Issue by hahmed** [dotnet/efcore#3274]
Can you connect to a database using EF on vnext just yet? As I am seeing some errors which I cannot seem to find any answer for.

If i persist security info (connection string) I get an error message: 

```
error   : [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Persisting security info is not yet implemented
System.NotImplementedException: Persisting security info is not yet implemented
  at System.Data.SqlClient.SqlConnectionStringBuilder.SetValue (System.String key, System.Object value) [0x00000] in <filename unknown>:0 
  at System.Data.SqlClient.SqlConnectionStringBuilder.set_Item (System.String keyword, System.Object value) [0x00000] in <filename unknown>:0 
  at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString (System.String value) [0x00000] in <filename unknown>:0 
  at System.Data.SqlClient.SqlConnectionStringBuilder..ctor (System.String connectionString) [0x00000] in <filename unknown>:0 
  at Microsoft.Data.Entity.SqlServer.SqlServerConnection.get_IsMultipleActiveResultSetsEnabled () [0x00000] in <filename unknown>:0 
```

[Full stack trace removed]

If I try and connect to an **azure sql database** I get another error message:

```
error   : [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: SSL encryption for data sent between client and server is not implemented.
System.NotImplementedException: SSL encryption for data sent between client and server is not implemented.
```

Thanks

**Comment by ErikEJ** [comment]
Could you share your connection string? I think you have some unsupported settings in it.

**Comment by hahmed** [comment]
I just simply copied it directly from azure portal...

This is the connection string for the azure portal sql database, do you want the connection string to my rackspace db too?

````
Server=tcp:test-dbs.database.windows.net,1433;Database=dbname;User ID=user;Password={your_password_here};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
````

**Comment by lucamorelli** [comment]
on mac? seems to me that the mono implementation of the sql driver does not suports encryption. I suppose we have to wait that for the a coreClr implementation of that driver

**Comment by hahmed** [comment]
@lucamorelli yep... on a mac.

Ok cool, is there any idea when that will be shipped?

**Comment by lucamorelli** [comment]
I don't know if this is fixed for beta 8, anyway I suppose that you can check in the documentation site http://ef.readthedocs.org/en/latest/providers/index.html and see if they update the note

**Comment by rowanmiller** [comment]
Correct, CoreCLR will be the ultimate solution to this since there are some significant limitations on the Mono SQL Client implementation.

@danroth27 do we have a public schedule on the availability of CoreCLR on Mac?

**Comment by danroth27** [comment]
@Saurabh500

The .NET Core schedule is aligned to the ASP.NET 5 roadmap: https://github.com/aspnet/home/wiki/roadmap. The xplat SqlClient isn't quite ready for beta8, but it should be available in Nov.

**Comment by natemcmaster** [comment]
@hahmed can we close this issue on EF? As Mono's implementation of SqlClient is *very* outdated and not likely to be updated, there isn't much we can do in EF to alleviate this problem.

**Comment by hahmed** [comment]
@natemcmaster closed this issue. Subscribed to the referenced issue so I can track when this will be fixed.

I am creating my team admin site using vnext and ef. I have managed to connect to my rackspace database I needed to remove the setting Persist Security info to make that work. Hopefully this will be done some time soon.

I know this is off topic, but do migrations work the same way as before? As in if I never want migrations to run, do I need to tell the migrations to do something? How about deploying to azure, I never want my migrations to run either. Has this been documented somewhere that I can get hold off?

**Comment by natemcmaster** [comment]
@hahmed Migrations is an opt-in feature. They do not run automagically. So if you are not sure if migrations run or not, you probably aren't. 

> Has this been documented somewhere that I can get hold off?

Not yet, docs are in progress. https://github.com/aspnet/EntityFramework.docs is all we have.
