### ISSUE TITLE
Table name created by OwnsMany does not use the property name by default

### ISSUE THREAD

**Issue by Kumima** [dotnet/efcore#32748]
For now, when configuring a collection of owned types, the default name is in singular form. It will be better to be in plural form.
`Message` => `Messages`
It's quite easy to configure the name by a single line code, but this is indeed a slight improvement. This won't introduce break changes.

**Comment by roji** [comment]
By design, EF doesn't itself pluralize table names; it seems simple enough for Message->Messages, but then EF needs to know about irregular forms such as Foot->Feet, and that's before thinking about non-English languages.

However, I'd expect the owned entity's table to be named after the .NET owning property name, similar to how we name non-owned entity tables based on the DbSet... We don't seem to be doing that...

**Comment by Kumima** [comment]
@roji yeah, appending `s`  will covers most situations. For that foot -> feet situation, developers should configure themselves. So, it seems this will be on plan, since you said you expeceted it.

**Comment by roji** [comment]
> So, it seems this will be on plan, since you said you expeceted it.

@Kumima you misunderstand, I absolutely do not think EF should append `s` or do anything else of the sort - my comment was that we should consider taking the .NET property name (which the user determines!) and use that as the default table name, just like we already do with DbSet property names.

> yeah, appending s will covers most situations. For that foot -> feet situation, developers should configure themselves.

This is definitely not a good idea - that would mean we create a `foots` table by default, forcing the user to go and explicitly rename to `feet`. And again, that doesn't even begin to consider foreign languages (appending `s` to, say, German, simply doesn't work).

**Comment by Kumima** [comment]
@roji Ah, sorry, I understand now. Yes, the property name is not used for now, it seems using the class name. So will this be improved to use the property name.

**Comment by ajcvickers** [comment]
Note from triage: could have been a nice idea, but too breaking for the benefit it brings to do it now.
