### ISSUE TITLE
Runtime Error in .NET8 App - Cannot Create DbSet for 'ApplicationUser'

### ISSUE THREAD

**Issue by dajma00** [dotnet/efcore#32743]
I used the Blazor .NET8 web app template and added two contexts to it. One is ApplicationDbContext and the other is TenantDbContext.

When I run the application, I get the following error:
``InvalidOperationException: Cannot create a DbSet for ApplicationUser because this type is not included in the model for the context.
``

EFCore Version 8

Sample minimal project to reproduce the problem: https://github.com/dajma00/Test

**Comment by ajcvickers** [comment]
@dajma00 EF8 requires use of an EF8 provider; currently the project is using

```
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
```

which only supports EF7.

**Comment by dajma00** [comment]
I have upgraded Pomelo MySql to version 8. But I get the same error when for example I try to login, so it is something else, not the Pomelo version. I have upgraded the test project.
