### ISSUE TITLE
ISaveChangesInterceptor.SaveChangesFailed is not triggered by DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by Atomosk** [dotnet/efcore#32750]
## Ask a question

It seems that [this commit](https://github.com/dotnet/efcore/commit/a4c9468be45f3cfd589ae4f4be563d3593ffda87) has broken this behavior. I wonder what is the correct way of handling EF exceptions globally?

### Include stack traces

With any other exceptions stack trace looks like this, Interestingly enough, `SaveChangesAsync` goes to `SaveChangesFailedAsync` through a Logger. I wouldn't expect a Logger to be responsible for triggering interceptors.

```
SaveChangesInterceptorAggregator.CompositeSaveChangesInterceptor.SaveChangesFailedAsync()
AsyncMethodBuilderCore.Start<Microsoft.EntityFrameworkCore.Diagnostics.Internal.SaveChangesInterceptorAggregator.CompositeSaveChangesInterceptor.<SaveChangesFailedAsync>d__9>()
AsyncTaskMethodBuilder.Start<Microsoft.EntityFrameworkCore.Diagnostics.Internal.SaveChangesInterceptorAggregator.CompositeSaveChangesInterceptor.<SaveChangesFailedAsync>d__9>()
SaveChangesInterceptorAggregator.CompositeSaveChangesInterceptor.SaveChangesFailedAsync()
CoreLoggerExtensions.SaveChangesFailedAsync()
async DbContext.SaveChangesAsync()
AsyncMethodBuilderCore.Start<Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63>()
AsyncTaskMethodBuilder<int>.Start<Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63>()
DbContext.SaveChangesAsync()
DbContext.SaveChangesAsync()
```

### Include provider and version information

EF Core version: 8.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: net8.0
Operating system: Windows 10.

**Comment by ajcvickers** [comment]
Use `ISaveChangesInterceptor.ThrowingConcurrencyException`.
