### ISSUE TITLE
NotSupportedException while executing to inserts in EF Core 8

### ISSUE THREAD

**Issue by krzysztofplazio** [dotnet/efcore#32765]
Hello

Here's a problem described in SO question:
https://stackoverflow.com/questions/77787123/notsupportedexception-while-executing-to-inserts-in-ef-core-8

I'm not sure it is a bug, but I don't know what more can I do.

**Comment by roji** [comment]
@krzysztofplazio we're going to need a minimal, runnable code sample - that code snippet on SO isn't enough. A small console program would be ideal.

**Comment by krzysztofplazio** [comment]
Okay, so, just create an example cosole program with this issue right?

**Comment by roji** [comment]
Yes. That is in general what you should always be doing when submitting a bug report - this is what allows the maintainers to actually see the bug happening, a code snippet or textual explanation is almost never enough.

I see you closed this issue, was that intentional?

**Comment by krzysztofplazio** [comment]
I wrote a console program and it works. I closed becaused I workaround it in my actual project. I don't have a lot expirience in .NET, so I didn't know I can workaround it in the way which I described in SO question.

**Comment by roji** [comment]
@krzysztofplazio try isolating the difference between your console program and your real application - somewhere in your real application you're doing something that causes the issue. By trying to reproduce it in isolation you'll likely find some bug in your own code.
