### ISSUE TITLE
DropForeignKey() generates incorrect SQL using principalTable overload instead of explicit constraint name

### ISSUE THREAD

**Issue by ianschmitz** [dotnet/efcore#3277]
Looks to be an issue with the generated SQL when trying to drop a foreign key constraint during a migration using a certain overload of `DropForeignKey()`.

I wanted to drop a FK column and it's constraint using migrations. However, i had multiple databases using the schema, and had different names for the FK constraints. This seemed like a good use of the DropForeignKey overload: `DropForeignKey(string dependentTable, string dependentColumn, string principalTable, object anonymousArguments = null);`

However, the SQL generated using this method was:

```
IF object_id(N'[dbo].[FK_dbo.tCalendarEntry_dbo.tPermissionSet_PermissionSetID]', N'F') IS NOT NULL
    ALTER TABLE [dbo].[tCalendarEntry] DROP CONSTRAINT [FK_dbo.tCalendarEntry_dbo.tPermissionSet_PermissionSetID]
DECLARE @var0 nvarchar(128)
SELECT @var0 = name
FROM sys.default_constraints
WHERE parent_object_id = object_id(N'dbo.tCalendarEntry')
AND col_name(parent_object_id, parent_column_id) = 'PermissionSetID';
IF @var0 IS NOT NULL
    EXECUTE('ALTER TABLE [dbo].[tCalendarEntry] DROP CONSTRAINT [' + @var0 + ']')
```

As you can see it's querying `sys.default_constraints`, which doesn't contain my FK constraints. This causes the `DropColumn()` that runs after to fail because the FK constraint still exists.

**Comment by rowanmiller** [comment]
@ianschmitz this repo is for EF7 and it looks like you issue relates to EF6.x. Can open a new issue on the EF6.x project site - http://entityframework.codeplex.com/.
