### ISSUE TITLE
ComplexTypeBulkUpdatesSqlServerTest failing on main

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#32786]
Failed tests
0.3556595s✘ Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesSqlServerTest.Update_complex_type_to_another_database_complex_type_with_subquery(async: False)
Assert.Equal() Failure: Strings differ\r\n                                  ↓ (pos 537)\r\nExpected: ···\"CT [c0].[Id], [c0].[Name], [c0].[BillingA\"···\r\nActual:   ···\"CT [c0].[Id], [c0].[BillingAddress_Addres\"···\r\n                                  ↑ (pos 537)
   at Microsoft.EntityFrameworkCore.TestUtilities.TestSqlLoggerFactory.AssertBaseline(String[] expected, Boolean assertOrder, Boolean forUpdate) in D:\code\efcore\test\EFCore.Relational.Specification.Tests\TestUtilities\TestSqlLoggerFactory.cs:line 59
   at Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesSqlServerTest.AssertExecuteUpdateSql(String[] expected) in D:\code\efcore\test\EFCore.SqlServer.FunctionalTests\BulkUpdates\ComplexTypeBulkUpdatesSqlServerTest.cs:line 234
   at Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesSqlServerTest.Update_complex_type_to_another_database_complex_type_with_subquery(Boolean async) in D:\code\efcore\test\EFCore.SqlServer.FunctionalTests\BulkUpdates\ComplexTypeBulkUpdatesSqlServerTest.cs:line 196
--- End of stack trace from previous location ---
Output:
Creating DbCommand for 'ExecuteReader'.

Created DbCommand for 'ExecuteReader' (0ms).

Initialized DbCommand for 'ExecuteReader' (0ms).

Closing data reader to 'ComplexTypeBulkUpdatesTest' on server 'localhost'.

A data reader for 'ComplexTypeBulkUpdatesTest' on server 'localhost' is being disposed after spending 0ms reading results.

Creating DbCommand for 'ExecuteNonQuery'.

Created DbCommand for 'ExecuteNonQuery' (0ms).

Initialized DbCommand for 'ExecuteNonQuery' (0ms).

Creating DbCommand for 'ExecuteReader'.

Created DbCommand for 'ExecuteReader' (0ms).

Initialized DbCommand for 'ExecuteReader' (0ms).

Closing data reader to 'ComplexTypeBulkUpdatesTest' on server 'localhost'.

A data reader for 'ComplexTypeBulkUpdatesTest' on server 'localhost' is being disposed after spending 0ms reading results.

---- New Baseline -------------------------------------------------------------------
        AssertExecuteUpdateSql(
"""
@__p_0='1'

UPDATE [c]
SET [c].[ShippingAddress_AddressLine1] = [t].[BillingAddress_AddressLine1],
    [c].[ShippingAddress_AddressLine2] = [t].[BillingAddress_AddressLine2],
    [c].[ShippingAddress_Tags] = [t].[BillingAddress_Tags],
    [c].[ShippingAddress_ZipCode] = [t].[BillingAddress_ZipCode],
    [c].[ShippingAddress_Country_Code] = [t].[ShippingAddress_Country_Code],
    [c].[ShippingAddress_Country_FullName] = [t].[ShippingAddress_Country_FullName]
FROM [Customer] AS [c]
INNER JOIN (
    SELECT [c0].[Id], [c0].[BillingAddress_AddressLine1], [c0].[BillingAddress_AddressLine2], [c0].[BillingAddress_Tags], [c0].[BillingAddress_ZipCode], [c0].[ShippingAddress_Country_Code], [c0].[ShippingAddress_Country_FullName]
    FROM [Customer] AS [c0]
    ORDER BY [c0].[Id]
    OFFSET @__p_0 ROWS
) AS [t] ON [c].[Id] = [t].[Id]
""");

9.3764847s✘ Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesSqlServerTest.Update_complex_type_to_another_database_complex_type_with_subquery(async: True)
Assert.Equal() Failure: Strings differ\r\n                                  ↓ (pos 537)\r\nExpected: ···\"CT [c0].[Id], [c0].[Name], [c0].[BillingA\"···\r\nActual:   ···\"CT [c0].[Id], [c0].[BillingAddress_Addres\"···\r\n                                  ↑ (pos 537)
   at Microsoft.EntityFrameworkCore.TestUtilities.TestSqlLoggerFactory.AssertBaseline(String[] expected, Boolean assertOrder, Boolean forUpdate) in D:\code\efcore\test\EFCore.Relational.Specification.Tests\TestUtilities\TestSqlLoggerFactory.cs:line 59
   at Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesSqlServerTest.AssertExecuteUpdateSql(String[] expected) in D:\code\efcore\test\EFCore.SqlServer.FunctionalTests\BulkUpdates\ComplexTypeBulkUpdatesSqlServerTest.cs:line 234
   at Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesSqlServerTest.Update_complex_type_to_another_database_complex_type_with_subquery(Boolean async) in D:\code\efcore\test\EFCore.SqlServer.FunctionalTests\BulkUpdates\ComplexTypeBulkUpdatesSqlServerTest.cs:line 196
--- End of stack trace from previous location ---
Output:
Creating DbCommand for 'ExecuteReader'.

Created DbCommand for 'ExecuteReader' (0ms).

Initialized DbCommand for 'ExecuteReader' (0ms).

Closing data reader to 'ComplexTypeBulkUpdatesTest' on server 'localhost'.

A data reader for 'ComplexTypeBulkUpdatesTest' on server 'localhost' is being disposed after spending 0ms reading results.

Creating DbCommand for 'ExecuteNonQuery'.

Created DbCommand for 'ExecuteNonQuery' (0ms).

Initialized DbCommand for 'ExecuteNonQuery' (0ms).

Creating DbCommand for 'ExecuteReader'.

Created DbCommand for 'ExecuteReader' (0ms).

Initialized DbCommand for 'ExecuteReader' (0ms).

Closing data reader to 'ComplexTypeBulkUpdatesTest' on server 'localhost'.

A data reader for 'ComplexTypeBulkUpdatesTest' on server 'localhost' is being disposed after spending 0ms reading results.

---- New Baseline -------------------------------------------------------------------
        AssertExecuteUpdateSql(
"""
@__p_0='1'

UPDATE [c]
SET [c].[ShippingAddress_AddressLine1] = [t].[BillingAddress_AddressLine1],
    [c].[ShippingAddress_AddressLine2] = [t].[BillingAddress_AddressLine2],
    [c].[ShippingAddress_Tags] = [t].[BillingAddress_Tags],
    [c].[ShippingAddress_ZipCode] = [t].[BillingAddress_ZipCode],
    [c].[ShippingAddress_Country_Code] = [t].[ShippingAddress_Country_Code],
    [c].[ShippingAddress_Country_FullName] = [t].[ShippingAddress_Country_FullName]
FROM [Customer] AS [c]
INNER JOIN (
    SELECT [c0].[Id], [c0].[BillingAddress_AddressLine1], [c0].[BillingAddress_AddressLine2], [c0].[BillingAddress_Tags], [c0].[BillingAddress_ZipCode], [c0].[ShippingAddress_Country_Code], [c0].[ShippingAddress_Country_FullName]
    FROM [Customer] AS [c0]
    ORDER BY [c0].[Id]
    OFFSET @__p_0 ROWS
) AS [t] ON [c].[Id] = [t].[Id]
""");

**Comment by ajcvickers** [comment]
@roji Looks like your recent commit.

**Comment by roji** [comment]
Ah crap, ok - must be a bad rebase etc. I'll take a look now.
