### ISSUE TITLE
Removing and re-adding to a many-to-many nav collection with intervening change detection removes relationship from database

### ISSUE THREAD

**Issue by nevsjs** [dotnet/efcore#32780]
## Description

In our project, we (used to) sometimes clear a many-to-many collection and re-add entities to it, often with the same entities that were in the collection previously.  The method that was updating collections in this manner was updating two collections and we found inconsistent behaviour in the update of the join tables in the database depending on whether both collections had been loaded prior to calling the update method.  If both collections were loaded, the updates were fine.  If not, then the first collection that had `Clear()` called on it would not be updated properly.  ie.  The loading of the second collection would "interfere" with subsequent updates to the first collection.

Found that the issue could be repro'd more simply by calling `DetectChanges()` on the change tracker in between clearing and re-adding entities to the collection.  Entities removed from the collection individually and then added back after change detection also suffer the same update issue.

### Seed Data

```
insert Widgets (IntVal) values (1);
insert Things (IntVal) values (1), (2);
insert WidgetThings (WidgetId, ThingId) values (1, 1), (1, 2);
```

### Repro Code

```C#
using Microsoft.EntityFrameworkCore;

using var context = new TestContext();

var w = context.Widgets.Find(1)!;
context.Entry(w).Collection(x => x.Things).Load();
w.Things.Clear();

// Uncomment the following line to see that items added back to the collection below are removed from WidgetThings in the db if they were previously in the table/collection
//context.ChangeTracker.DetectChanges();

var t1 = context.Things.Find(1)!;
var t2 = context.Things.Find(2)!;
w.Things.Add(t1);
w.Things.Add(t2);

context.SaveChanges();

return;

public partial class TestContext : DbContext
{
    public TestContext()
    {
    }

    public TestContext(DbContextOptions<TestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Thing> Things { get; set; }

    public virtual DbSet<Widget> Widgets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) =>
        optionsBuilder.UseSqlServer("server=(local);database=collection_test;integrated security=true;encrypt=false;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Widget>(entity =>
        {
            entity.HasMany(d => d.Things).WithMany(p => p.Widgets)
                .UsingEntity<Dictionary<string, object>>(
                    "WidgetThing",
                    r => r.HasOne<Thing>().WithMany()
                        .HasForeignKey("ThingId")
                        .HasConstraintName("FK_WidgetThings_Thing"),
                    l => l.HasOne<Widget>().WithMany()
                        .HasForeignKey("WidgetId")
                        .HasConstraintName("FK_WidgetThings_Widget"),
                    j =>
                    {
                        j.HasKey("WidgetId", "ThingId").HasName("PK_WidgetThings");
                        j.ToTable("WidgetThings");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

public partial class Thing
{
    public int ThingId { get; set; }

    public int IntVal { get; set; }

    public virtual ICollection<Widget> Widgets { get; set; } = new List<Widget>();
}

public partial class Widget
{
    public int WidgetId { get; set; }

    public int IntVal { get; set; }

    public virtual ICollection<Thing> Things { get; set; } = new List<Thing>();
}
```

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.0
Target framework: .NET 8.0
Operating system: Win10Pro 22H2
IDE: Visual Studio 17.8.4

**Comment by ajcvickers** [comment]
@nevsjs This is currently by-design; the call to DetectChanges is needed so that EF detects that the items have been removed from the collection. Doing this marks the join entity items as Deleted, since the relationship that they represent no longer exists. Adding the entities back to the collection resurrects these join entities as new again, and puts them in the Added state. However, if EF doesn't get a chance to see the items were removed, then when it sees the collection next time there is no change. The entities were there and then were removed and added back without EF seeing this, so they are still there.

**Comment by nevsjs** [comment]
@ajcvickers Thanks for the explanation.  The "no change" state was what I was expecting at the point of the final SaveChanges, whether a call to DetectChanges along the way happens or not.  However, when DetectChanges **is** called between deleting and adding, it appears that the join entities being marked as Deleted is what sticks and when SaveChanges is called they are deleted from the database.

Happy to close this issue since the behaviour is by-design.

**Comment by ajcvickers** [comment]
@nevsjs I want to briefly discuss with the team if there is anything better we could do here.
