### ISSUE TITLE
Dotnet-ef mismatch causes apply Entity Framework migration fails when publishing an individual web app.

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/efcore#32782]
**REGRESSION INFO**: Worked in: 17.8.4 (Contains runtime 8.0.1).

**TESTCASES AFFECTED**
[[8.0/7.0/6.0] SimpleWebAppWithIndAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.6/E2EWalkthroughs/VS/AspNetCore60/60_SimpleWebAppWithIndAuth.md) 

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 Preview 2.1 latest released build, Preview channel
      - Web workload
      - Includes SDK 8.0.100 and runtime 8.0.0

**REPRO STEPS**
1. New > ASP.NET Core Web App (Razor Pages) > .NET 8.0 > Individual Accounts
2. Right click the project > Publish > Azure > Azure App Service (Windows)
3. After the profile created, go to More actions > Edit, expand "Entity Framework Migration" node

**ACTUAL**
EF Migrations error: You must install or update .NET to run this application.
![image](https://github.com/dotnet/efcore/assets/78580199/de170f2b-5654-4904-8fec-f9c995ae3019)

**Workaround 1**: Uninstall the dotnet-ef 8.0.1 and install version 8.0.0
```
dotnet tool uninstall dotnet-ef
dotnet tool install dotnet-ef --version 8.0.0
```
![image](https://github.com/dotnet/efcore/assets/78580199/55e44075-0902-40af-a7dd-ca06de1dad2a)

**Workaround 2**: Install runtime 8.0.1 Separately

**EXPECTED**
![image](https://github.com/dotnet/efcore/assets/78580199/c6a1a1d2-5bfb-457b-9648-7255decf5d5d)

**Comment by v-elenafeng** [comment]
@ajcvickers This issue can be workaround by installing runtime 8.0.1 or dotnet-ef 8.0.0, but would still like to confirm with you if this is a by design issue as we can wait until the 8.0.1 is plugged into VS 17.9 at the release stage. Any thoughts about this?

**Comment by ajcvickers** [comment]
@v-elenafeng I'm not aware of any intentional change in design from the EF side here. @bricelam might have made some changes to this before he left the company. Either that, or something changed in the way tools are built.

**Comment by BBS-PejoTech** [comment]
same issue on linux, manjaro (arch):

```
dotnet ef                                                                          
You must install or update .NET to run this application.

App: /home/pejotech/.dotnet/tools/dotnet-ef
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.1' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  8.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.1&arch=x64&rid=arch-x64&os=manjaro
```

dotnet info:
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.2d90560f

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.2d90560f
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

it looks like dotnet-ef is looking for runtime 8.0.100 but after the sdk update the runtimes remain at 8.0.0. in `dotnet --info` at least

**Comment by bricelam** [comment]
> @bricelam might have made some changes to this

No changes from me. I suspect something either in Arcade or the .NET SDK (PackAsTool related) changed or our build files.

Version 8.0.1 of the dotnet-ef.runtimeconfig.json file takes an explicit dependency on 8.0.1:

```json
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.1"
    }
}
```

But version 7.0.15 is correct:

```json
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    }
}
```

This may be related to some of @AndriySvyryd's changes around TFMs.

**Comment by AndriySvyryd** [comment]
Interesting. On main it still uses "8.0.0"

**Comment by AndriySvyryd** [comment]
So, this is the commit that causes this - 4ab923148d85ddd7d7d6fe42b815d92cd5419062
My guess is it's just a blanket increase of the minimum version to ensure that it has the security patches.

**Comment by bricelam** [comment]
Hmm, release/6.0 also bumps that, but I don’t think it has the same problem. I don’t see anything in the EF build scrips that have changed around this since release/6.0. 🤷‍♂️

**Comment by bricelam** [comment]
Ah, might need to take [this code](https://github.com/dotnet/efcore/blob/423b1a0d38036efcefdbf1dfb80955449eae1238/Directory.Build.targets#L11) out of the servicing branch.

**Comment by AndriySvyryd** [comment]
> Ah, might need to take [this code](https://github.com/dotnet/efcore/blob/423b1a0d38036efcefdbf1dfb80955449eae1238/Directory.Build.targets#L11) out of the servicing branch.

Yep, that fixes it
