### ISSUE TITLE
Why is my code causing Foreign Key Constraint errors on BulkSaveChanges()?

### ISSUE THREAD

**Issue by asfarley** [dotnet/efcore#32795]
My issue: I'm getting a foreign key constraint after performing this process:
 * Create a database context
 * Load objects
 * Dispose context, keep objects
 * Create new context, clear entire database, dispose context
 * Create new context
 * Add objects to context
 * Call BulkSaveChanges()

At this point I get a foreign key constraint error. From the debugger, I suspect what's happening here is that my child objects are being passed the foreign key to their parent (the 'one' object in a 'many to one') from the first time the objects were loaded from the database.  When the objects are saved, the child cannot be saved pointing to parent with ID e.g. 1 because now the parent has ID e.g. 2 since it's the second time it's been saved to the database, and the database persists the 'next index' value.

I've tried assigning the reference navigation and the reference navigation ID to null before adding to the database, but this results in those values being populated by the parent object, with the old incorrect foreign key. 

I've posted a slightly more complete description of this issue here on StackOverflow, but the 'workaround' is no longer working for me: I'm still getting a foreign-key error if I set the reference-navigation and reference-navigation-id to null before adding to the dbContext. This appears to be happening because, after I add everything to the dbContext, the child objects are re-assigned with the foreign key which becomes outdated when the parent object is actually saved to the database.

The StackOverflow issue:
https://stackoverflow.com/questions/77743493/ef-core-why-are-the-foreign-keys-in-my-one-to-many-association-becoming-outdate

Am I doing something incorrectly here? Happy to provide more details like step-by-step literal key values or whatever would help.

### Versions

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.Sqlite.Core 7.0.13
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.8.3

**Comment by roji** [comment]
BulkSaveChanges() isn't part of EF - it's a 3rd-party extension, so we can't really help with it. If you can produce a minimal, runnable console program that shows the problem without using BulkSaveChanges() (i.e. just using EF's regular SaveChanges() method), then that's something we can definitely look into.

**Comment by asfarley** [comment]
@roji yikes, my mistake - I had totally forgotten I was using an extension method here. Sorry about that.
