### ISSUE TITLE
Updating the reference to Microsoft.Data.SqlClient from 5.1.1 to 5.1.4

### ISSUE THREAD

**Issue by psycrush** [dotnet/efcore#32797]
Microsoft.Data.SqlClient version 5.1.4 has been released a few days ago, which is no longer marked as deprecated and contains a current Azure.Identity dependency without a vulnerability tag.

**Comment by psycrush** [comment]
Update from 5.1.1 to 5.1.2 already performed but not included in latest efcore release 8.0.1

[Bump Microsoft.Data.SqlClient from 5.1.1 to 5.1.2](https://github.com/dotnet/efcore/pull/32187/commits/5184d38604f15e42447a9d9b002519efd04c5189)

**Comment by ErikEJ** [comment]
@psycrush main branch represents the EF Core 9 code base, any changes to release 8 is in another branch

**Comment by ajcvickers** [comment]
All active branches have now been updated.

**Comment by mr-davidc** [comment]
I have version v8.0.1 of `Microsoft.EntityFrameworkCore` package installed however it appears to still reference v5.1.1 of `Microsoft.Data.SqlClient` ? Is there going to be a new 8.0.x version of `Microsoft.EntityFrameworkCore` that bumps this ? Or is it ok to just manually install v5.1.4 of `Microsoft.Data.SqlClient` ? Thanks

**Comment by roji** [comment]
@mr-davidc that's right, 8.0.1 was released before this change was done. 8.0.2 show be updated - and in any case, yes - simply take a reference on 5.1.4 in your own project, that should be fine.

**Comment by radlung** [comment]
> Update from 5.1.1 to 5.1.2 already performed but not included in latest efcore release 8.0.1
> 
> [Bump Microsoft.Data.SqlClient from 5.1.1 to 5.1.2](https://github.com/dotnet/efcore/pull/32187/commits/5184d38604f15e42447a9d9b002519efd04c5189)

**I found out at this merging point the state of SqlClient 5.1.2 was only "preview" and so it was merged into the main-branch.**

 <ItemGroup>
    **<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0-preview4.23342.2" />**
  </ItemGroup>

**Comment by MoishyS** [comment]
when will a new Nuget for efcore be released?

**Comment by psycrush** [comment]
> when will a new Nuget for efcore be released?

I suspect that there will be a new version in mid-February.
