### ISSUE TITLE
Scaffolding a DbContext generates multiple warnings of "Non-nullable properties are uninitialized".

### ISSUE THREAD

**Issue by jscarle** [dotnet/efcore#32792]
As it currently stands, the ef tool generates a scaffolded DbContext with uninitialized properties that are later initialized during runtime. Something along the lines of:
```
public partial class MyDbContext : DbContext
{
    public virtual DbSet<MyEntity> MyEntities { get; set; }
}
```
This is turn generates several warnings in the style of:
`Non-nullable properties '--some DbSet property--' are uninitialized. Consider declaring the properties as nullable.`

This could probably be fixed by generating something more along the lines of:
```
public partial class MyDbContext : DbContext
{
    public DbSet<MyEntity> MyEntities => Set<MyEntity>();
}
```

Now, I generally have no idea what impact this change would have. And I'm not even sure if my proposed solution is the correct one. All I do know is that I, just like many many many other developers who scaffold databases using the ef tool, do not like unnecessary warnings and tend to modify the generated output of the scaffold tool to eliminate those warnings. I know very few developers that simply ignore them. Different approaches are used, some use ` = null!;`, others use `#pragma`, while other like myself lean towards ` => Set<>();`. I'm sure someone on the efcore team would have a better idea of which solution would be most appropriate and why.

Nonetheless, this is often discussed as seen here:
- https://www.reddit.com/r/dotnet/comments/te5i3c/whats_the_best_practice_for_initalizing_dbset/
- https://stackoverflow.com/questions/57342964/how-can-i-hint-the-c-sharp-8-0-nullable-reference-system-that-a-property-is-init
- https://stackoverflow.com/questions/71741927/non-nullable-property-warning-in-dbcontext-class-for-dbset-property
- https://stackoverflow.com/questions/70788694/non-nullable-warning-with-ef-core-dbset

This has been long standing now for many years. Its a very minor quality of life thing, but it would be nice to see an official fix that puts an end to the discussions and the doubts as to which way to properly eliminate those warnings.

**Comment by ajcvickers** [comment]
@jscarle There is supposed to be a suppressor for that message; that's why we haven't updated the scaffolding. What is your development setup--that is, OS, IDE/editor, etc?

**Comment by roji** [comment]
Also, are you getting the nullability warnings when building from the command-line, i.e. via `dotnet build`?

**Comment by jscarle** [comment]
It took me a while to get back to you guys because I wanted to make sure I had all of the information before I answered. I put together a quick project and database to test this properly.

Environment:
 - Windows 11 23H2
 - .NET SDK 8.0.101
 - EF CLI Tool 8.0.1
 - JetBrains Rider 2023.3.2
 - Visual Studio 2022 17.8.5

Csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    </ItemGroup>

</Project>
```

Command run to scaffold:
```PowerShell
"C:\Program Files\dotnet\dotnet.exe" ef dbcontext scaffold
--project EfScaffoldingTest.csproj
--startup-project EfScaffoldingTest.csproj
--configuration Debug "<connection string>" Microsoft.EntityFrameworkCore.SqlServer
--context DemoDbContext
--context-dir Context
--force
--output-dir Entities
Build started...
Build succeeded.
To protect potentially sensitive information in your connection string, you should move it ...
```

Resulting DbContext:
```csharp
using System;
using System.Collections.Generic;
using EfScaffoldingTest.Entities;
using Microsoft.EntityFrameworkCore;

namespace EfScaffoldingTest.Context;

public partial class DemoDbContext : DbContext
{
    public DemoDbContext()
    {
    }

    public DemoDbContext(DbContextOptions<DemoDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it ...
        => optionsBuilder.UseSqlServer("<connection string>");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.Property(e => e.ClientName)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.Property(e => e.OrderDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
```

Resulting Client entity:
```csharp
using System;
using System.Collections.Generic;

namespace EfScaffoldingTest.Entities;

public partial class Client
{
    public int ClientId { get; set; }

    public string ClientName { get; set; } = null!;
}
```

Resulting Order entity:
```csharp
using System;
using System.Collections.Generic;

namespace EfScaffoldingTest.Entities;

public partial class Order
{
    public int OrderId { get; set; }

    public DateTime OrderDate { get; set; }
}
```

After taking the time to dig further, it seems that this affect JetBrains Rider (and probably ReSharper) users only. Because no warnings are generated in Visual Studio nor with dotnet build.

These are the warnings that show up in Rider under default settings:

<img width="608" alt="image" src="https://github.com/dotnet/efcore/assets/29762210/25fad86c-9d58-4c1a-8d14-216a79480534">

I played around with an .editorconfig file to see how this could be muted, but unfortunately, it seems to be tied to the CS8618 warning as both of these settings affect its visibility:
```editorconfig
[*.cs]
resharper_c_sharp_warnings_cs8618_highlighting = true
dotnet_diagnostic.CS8618.severity = warning
```

Now I have no idea if Rider ignores the fact that CS8618 should be muted for the DbContext or if its doing its own static analysis.

I tried adding the SonarAnalyzer.CSharp NuGet package as an additional code analyzer, it didn't pick up on the nullability issues, but does also bark on the partial declaration. However, that's a whole different discussion I'd imagine.
```
0>DemoDbContext.cs(44,5): Warning S3251 : Supply an implementation for this partial method. (https://rules.sonarsource.com/csharp/RSPEC-3251)
0>DemoDbContext.cs(41,9): Warning S3251 : Supply an implementation for the partial method, otherwise this call will be ignored. (https://rules.sonarsource.com/csharp/RSPEC-3251)
```

**Comment by ajcvickers** [comment]
@jscarle This is a known limitation of Rider: see https://youtrack.jetbrains.com/issue/RIDER-45021/Support-Roslyn-based-suppressors

**Comment by jscarle** [comment]
Thanks @ajcvickers, I appreciate the follow up.

Could you offer some feedback on those of us who would like to refactor our code instead of muting the warnings?

Are there any performance considerations when using
```csharp
public DbSet<Client> Clients => Set<Client>();
```
versus
```csharp
public virtual DbSet<Client> Clients { get; set; } = null!;
```

?

**Comment by roji** [comment]
Both are fine, the 1st very theoretically performs a bit worse than the 2nd, since the property invokes the Set() method each time. But that's extremely unlikely to affect and real application.

(the virtual seems completely unrelated)

**Comment by jmevel** [comment]
> @jscarle This is a known limitation of Rider: see https://youtrack.jetbrains.com/issue/RIDER-45021/Support-Roslyn-based-suppressors

There is also [this thread](https://youtrack.jetbrains.com/issue/RSRP-481121/Roslyn-DiagnosticSuppressor-from-SmartAnalyzers-package-does-not-work-in-Rider).

And sad news as a [JetBrains employee replied](https://youtrack.jetbrains.com/issue/RSRP-481121/Roslyn-DiagnosticSuppressor-from-SmartAnalyzers-package-does-not-work-in-Rider#focus=Comments-27-8915763.0-0), they have no plans to support it.

**Comment by jscarle** [comment]
@roji Thanks for the insight!
