### ISSUE TITLE
Default to MigrationsAssembly for migrations add (if specified)

### ISSUE THREAD

**Issue by gordysc** [dotnet/efcore#32791]
EntityFramework allows you to specify a separate migrations project as documented here:
https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli

If I go to my startup project and run the documented command it works:

```sh
dotnet ef migrations add NewMigration --project WebApplication1.Migrations
```

However, I don't have to specify the project when updating the database with the migrations:

```sh
# This finds the migrations without specifying the --project flag
dotnet ef database update
```

While the current flow does work, it's not great having to specify --project anytime a developer wants to add a new migration.

**Proposed Solution 1**

Ideally, if the migrations assembly is defined as described in the above link it'd default to that versus developers having to specify the project anytime they wish to generate a migration

```sh
# New suggested syntax that defaults to MigrationsAssembly (if specified)
dotnet ef migrations add NewMigration

# Instead of this
dotnet ef migrations add NewMigration --project WebApplication1.Migrations
```

**Proposed Solution 2**

Another option would having a default configuration that could be defined somewhere for EF tools to use as the default migration assembly for generating migrations instead of the --project flag for every new migration.

**Comment by ajcvickers** [comment]
@gordysc I may be missing something, but why can't you just run "dotnet ef migrations add NewMigration" in the project directory? This is what I do, and I never specify `--project`.

**Comment by gordysc** [comment]
> @gordysc I may be missing something, but why can't you just run "dotnet ef migrations add NewMigration" in the project directory? This is what I do, and I never specify `--project`.

Do you have a sample project doing this? Here's my setup at a high level, perhaps I'm doing something unconventional?

I have 3 projects in my solution:

- Example.API
- Example.Entities
- Example.Migrations

My Program.cs is in the Example.API (WebAPI) project. 
My DbContext is in the Example.Entities project. 
I am calling `builder.Services.AddDbContext` in the Program.cs

Example.Migrations references Example.Entities. However because the configuration and appsettings.json exist in Example.API I'd have to run the command from that project.

**Comment by ajcvickers** [comment]
@gordysc Ah, I see. So instead of running the command from the project directory and specifying the `startup-project` only, you want to run the command from the startup project, but instead of specifying the project, you want EF to use the configuration from the startup project? That's a nice idea, but I think the problem is that we need the _project_, not just the assembly, because we have to do file-system stuff to it.
