### ISSUE TITLE
EFC Tooling always forces a rebuild

### ISSUE THREAD

**Issue by Suchiman** [dotnet/efcore#32801]
Running any EFC CLI (be it `dotnet ef` or the powershell ones) command will always print
```
PM> dotnet ef ...
Build started...
Build succeeded.
```
even if the project is up to date. Our Database project (which only contains database classes) takes almost a minute to build so having to wait for a build everytime you issue a command severely degrades the innerloop experience. And as for the Powershell Commands, they'll lock up VS until the command has completed.

### Include provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.9P1

**Comment by ErikEJ** [comment]
What commands do you typically run?

**Comment by Suchiman** [comment]
A typical flow might look like this:
I modify the database project, then trigger a build to see if i've gotten everything right and then i issue `Add-Migration` which prompty does another unnecessary build.
I then usually hit F5 to build and start debugging the project which calls `context.Database.Migrate()` on the startup path.
I might now for whatever reason need the SQL that was used for the migration, so i hit up `Script-Migration` which does me another unnecessary build.
From that or because i realized that my changes are not quite done yet i do a `Update-Database -To <previous>` to undo the migration which does another unnecessary build.
Then after that i need to issue `Remove-Migration` which does another unnecessary build (unless i just git undo the migration files).
I'm planning to add `dotnet ef dbcontext optimize` to my workflow because the cold boot time of EFC with debug is currently 9s and that reduces it to 3s.

**Comment by ajcvickers** [comment]
@Suchiman If you are sure the project is up-to-date, then just pass `--no-build`.

**Comment by Suchiman** [comment]
> @Suchiman If you are sure the project is up-to-date, then just pass `--no-build`.

huh i've never noticed that flag, thanks! Is there a particular reason though to not rely on msbuild's up-to-date check?

**Comment by ajcvickers** [comment]
@Suchiman The idea is that when you do `dotnet build`, which is effectively what EF does, then the up-to-date check should kick in automatically. However, MSBUILD is complicated and has gotten more so, such that, for example, a build in VS is now a different beast to build on the command line. That being said, building is a safeguard against the very common problem of people issuing a command without having first built their code. If you are okay to not have that safeguard, then --no-build is the way to go. Or you could write your own shell script to do the build however you want it and then call the tool with --no-build.

**Comment by Suchiman** [comment]
@ajcvickers even if i issue `dotnet ef migrations script` multiple times back to back (which makes no changes to the project), it (re)builds everytime, having VBCSCompiler peg the CPU for quite a while. I found that the command is built and issued here:
https://github.com/dotnet/efcore/blob/9a1b7fc0189132840c4434ad9f161905dafa9e7c/src/dotnet-ef/Project.cs#L137-L174
which is called from here
https://github.com/dotnet/efcore/blob/9a1b7fc0189132840c4434ad9f161905dafa9e7c/src/dotnet-ef/RootCommand.cs#L79-L84
Grabing the command line from taskmgr reveals it issues
`dotnet build C:\Path\To\Database.csproj /verbosity:quiet /nologo /p:PublishAot=false`
which matches that code and looks fine. If i issue it manually in the cmd, it finishes quickly, printing
```
The build completed successfully.
     0 warning(s)
     0 errors

Elapsed time 00:00:01.26
```
indicating that the up-to-date check is working, however everytime i invoke `dotnet ef` it does not, i don't quite understand where the difference lies.
I'll try digging deeper later to see if i can figure that out.

**Comment by ajcvickers** [comment]
@Suchiman Note that this area has been investigated previously. If you find something simple and safe to change that helps, that's great, but in general if you want full control over how builds happen then build outside of the EF command line.

**Comment by Suchiman** [comment]
One thing i've noticed in my first analysis was that the command is running with the `MSBUILDUSESERVER=0` environment variable set, which means it would need to boot up VBCSCompiler fresh every time which might explain it taking so much longer. Although i've tried issuing `dotnet build` with that env variable set and it didn't really seem to have an effect on build time or the outcome of the up-to-date check

> It is slower than building within Visual Studio itself, where it only needs ~1.5 seconds for the same up-to-date check

That is not entirely true, it's not the same check, VS has something called the "fast up-to-date-check" where it bypasses MSBuild entirely and judges if a project is up-to-date on its own. That can be turned off though if needed.

**Comment by Suchiman** [comment]
I have identified the issue, it's this piece of code:
https://github.com/dotnet/efcore/blob/9a1b7fc0189132840c4434ad9f161905dafa9e7c/src/dotnet-ef/Project.cs#L56-L66
which writes a `.target` file into the `obj` directory on every build, thus always bumping it's last modified timestamp and thus always failing the up-to-date check. 

The reason for that is explained as well as `// NB: Copy always in case it changes` but that's a hefty price to pay.
There are two ways to resolve this IMO:
1. Do not override the file if it already exists and rely on the user to clean the project if it's not working right (i think that's in the toolbelt of every VS developer to just nuke `obj` and `bin` if things are not working as expected).
2. Read the existing file and check if it matches the file we expect to be there, only (over)write the file if it doesn't match what we expect

@ajcvickers is any of these options acceptable and would be accepted as a PR?

**Comment by ajcvickers** [comment]
We had a discussion on this in the team yesterday. In general, we don't want to make changes here _just for perf_. In other words, the bottom line is that it should be as reliable as possible, even if that's slower than it needs to be. The reason for this is that anybody is free to do their own thing and use `--no-build`. And this can even be added to a script if desired.

We have a history of changes in MSBUILD and tooling impact what we do, especially when we try to be clever and do something non-standard. So, I can see we might accept a PR that removed some cleverness, as long as the impact is good or not too bad, but I suspect we would reject anything that added in any cleverness.

**Comment by joakimriedel** [comment]
> We had a discussion on this in the team yesterday. In general, we don't want to make changes here _just for perf_. In other words, the bottom line is that it should be as reliable as possible, even if that's slower than it needs to be. The reason for this is that anybody is free to do their own thing and use `--no-build`. And this can even be added to a script if desired.

I tried with `--no-build` and it seems as if some of the projects dependencies are still affected by the tool, probably the `.target` file mentioned above, which leads to the project not being up to date after executing `dotnet ef`.

```powershell
> dotnet build

<build completed>

> dotnet ef migrations list --no-build

<results>

> dotnet build

<starts building, project not up-to-date>
```

**Comment by Mike-E-angelo** [comment]
Awesome, thank you so much to @Suchiman and the team there for all your work in diagnosing and addressing this. 🙏  Adding migrations is becoming quite the pain point for me lately, taking many minutes to both build and optimize the model after the change.  Any improvement to this process is greatly appreciated and welcomed.
