### ISSUE TITLE
Change T4-generated file name for scaffolded entities

### ISSUE THREAD

**Issue by tafs7** [dotnet/efcore#32804]
wondering if there's a way to specify suffix or prefix to the file names of the files generated by the T4 templates used by the `dotnet ef dbcontext scaffold` or the `Scaffold-DbContext` tools.

For example, I would like my generated files to have a `*.g.cs` name, so that anyone can see that it's a generated file.

I know I can add a comment to the top of the file to state that it is auto-generated, but just wondering if affecting the generated file name is possible also.

**Comment by ErikEJ** [comment]
@tafs7 Yes, you can set the extension;

https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli#advanced-usage

**Comment by tafs7** [comment]
Thanks, @ErikEJ.

I assume you're referring to the top line on the Mermaid example?
`<#@ output extension=".md" #>`

If so, I suppose I could just simple do this for my use-case?
`<#@ output extension=".g.t4" #>`

**Comment by ErikEJ** [comment]
@tafs7 I think you need to add .cs , but yes.

**Comment by tafs7** [comment]
oops, yes - sorry, I meant ".cs" :)

THanks, again for the reply!

**Comment by tafs7** [comment]
closing
