### ISSUE TITLE
what's different between use and not use await base.OnAfterRenderAsync 

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/efcore#32808]
what's different between use and not use await base.OnAfterRenderAsync ? 
what's different between these codes ? 

```
@functions {
    protected async override Task OnAfterRenderAsync(bool firstRender)
    {

        if (!firstRender)
        {
            IsDataLoaded = true;
            StateHasChanged();
        }
        await base.OnAfterRenderAsync(firstRender);

    }
}
```

and 

```
@functions {
    protected async override Task OnAfterRenderAsync(bool firstRender)
    {

        if (!firstRender)
        {
            IsDataLoaded = true;
            StateHasChanged();
        }


    }
```

**Comment by roji** [comment]
@MahdiElahi this question doesn't seem to be related to EF Core in any way.

**Comment by Kumima** [comment]
@MahdiElahi This is an asp.net blazor question. Not related to efcore. It's just a `CompletedTask` for `ComponentBase`. If the component is simply inherited from `ComponentBase`, which is the most common situation, there is no different. But if your parent component has its `OnAfterRenderAsync` logic, you should call base.
```csharp
//ComponentBase.cs
protected virtual Task OnAfterRenderAsync(bool firstRender)
        => Task.CompletedTask;
```

**Comment by roji** [comment]
Closing as unrelated to EF Core.
