### ISSUE TITLE
Set context_info in ef core 

### ISSUE THREAD

**Issue by mhdimsy** [dotnet/efcore#32814]
Hello everyone, I need help with setting context_info in EF Core when opening a connection.

EF Core version:6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by roji** [comment]
@mhdimsy you're going to have to post more details than that - ideally a minimal, runnable code sample.

**Comment by ErikEJ** [comment]
You can use ExecuteSqlRaw

**Comment by mhdimsy** [comment]
Thanks @ErikEJ and @roji. In a dotnet core API project, where should I call ExecuteSqlRaw? In dbcontext, in startup, or in custom middleware?

**Comment by ErikEJ** [comment]
Probably an Interceptor https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors

**Comment by roji** [comment]
Closing as this seems to be about simply executing raw SQL, and the question has been answered (but feel free to continue posting here if you have further questions).
