### ISSUE TITLE
Error : Normalizing '_blazor' to ... in balzor .net 8

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/efcore#32810]
Hi, 
My website is worked correctly and it's web app blazor 8 but when run project i have this error in inspect element ? what is the problem ? 
![Capture](https://github.com/dotnet/efcore/assets/32883870/941d35c3-11dc-4308-8e7b-2304b215e141)

**Comment by ajcvickers** [comment]
@MahdiElahi This issue doesn't appear to have anything to do with EF Core. You might want to post on [github.com/dotnet/aspnetcore](https://github.com/dotnet/aspnetcore), but make sure to include full details of your issue.
