### ISSUE TITLE
Migrations does not warn for unspecified decimals in ComplexProperty types

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#32827]
I tried this with records (primary constructor as below and just properties) and a class. Same result for all iterations.
Mapping as an owned entity **does** cause the warning to appear.

### Include your code

```
using Microsoft.EntityFrameworkCore;
Console.WriteLine("Hello, World!");

//record via primary constructor
public record PersonName(string First, string Last,decimal randomDecimal);

//entity that uses the record
public class Person
{
    private Person() { }
    public Person(string first,string last)
    {
        Name = new PersonName(first, last,1.2m);
        RandomDecimal = 1.2m;
    }

    public int PersonId { get; private set; }
    public PersonName Name { get; init; }
    public decimal RandomDecimal { get; init; }

}

public class  PersonContext: DbContext
{
    public DbSet<Person> People { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
       optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=ConsoleRecordExperiments");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       modelBuilder.Entity<Person>().ComplexProperty(Person => Person.Name);
    }

}

```
**The decimal in the Person class gives the warning**
`No store type was specified for the decimal property 'RandomDecimal' on entity type 'Person'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.`

**But there is no warning for the decimal type in PersonName**

### Include provider and version information

EF Core version: 8.0.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 10
IDE: VS 2022 17.8.4

**Comment by ajcvickers** [comment]
@julielerman That's because the changes to the update pipeline in 7 means that this warning is no longer needed in most cases, we just haven't done the changes yet--see #27438. For complex types, it should only warn if the containing entity contains triggers.

**Comment by julielerman** [comment]
Ahh thanks @ajcvickers . I guess still seeing it elsewhere tricked me and, P.S.,  I really did search the repo first . :)
Ta!

**Comment by ajcvickers** [comment]
That's not the behavior I am seeing with your code. When I run the console app below, it round-trips 2.5 to the database without truncation.

```C#
using (var context = new PersonContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.Add(new Person("X", "Y") { RandomDecimal = 2.5m });
    
    await context.SaveChangesAsync();
}

using (var context = new PersonContext())
{
    Console.WriteLine(context.Set<Person>().Single().RandomDecimal);
}

//record via primary constructor
public record PersonName(string First, string Last,decimal randomDecimal);

//entity that uses the record
public class Person
{
    private Person() { }
    public Person(string first,string last)
    {
        Name = new PersonName(first, last,1.2m);
        RandomDecimal = 1.2m;
    }

    public int PersonId { get; private set; }
    public PersonName Name { get; init; }
    public decimal RandomDecimal { get; init; }

}

public class  PersonContext: DbContext
{
    public DbSet<Person> People { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Data Source=localhost;Database=One;Integrated Security=True;TrustServerCertificate=true");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().ComplexProperty(Person => Person.Name);
    }

}
```

**Comment by julielerman** [comment]
I didn't use that code to test. BRB.

**Comment by julielerman** [comment]
Here I'm entering 1.234. I'm not ocnfiguring the decimal in the complex property but I am configuring in the entity to see the difference in values.

```
using Microsoft.EntityFrameworkCore;

var person= new Person("John", "Doe");
using var context = new PersonContext();
context.Database.EnsureDeleted();
context.Database.EnsureCreated();
context.People.Add(person);
context.SaveChanges();
context.ChangeTracker.Clear();
var people= context.People.ToList();
Console.WriteLine("Hello, World!");

//record via primary constructor
public record PersonName(string First, string Last, decimal randomDecimal);

//entity that uses the record
public class Person
{
    private Person() { }
    public Person(string first,string last)
    {
        Name = new PersonName (first,last,1.234m );
        RandomDecimal = 1.234m;
    }

    public int PersonId { get; private set; }
    public PersonName Name { get; init; }
    public decimal RandomDecimal { get; init; }

}

public class  PersonContext: DbContext
{
    public DbSet<Person> People { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
       optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=ConsoleRecordExperiments");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       modelBuilder.Entity<Person>().ComplexProperty(Person => Person.Name);
        modelBuilder.Entity<Person>().Property(Person => Person.RandomDecimal).HasPrecision(18, 4);

    }

}

```
![Snag_8ddc528](https://github.com/dotnet/efcore/assets/5007120/426b384a-dfc2-4b14-bd6c-6baf19cc5406)

**Comment by ajcvickers** [comment]
@julielerman This is SqlClient behavior. The default is still (18, 2); anything that doesn't fit will be truncated. The warning is not about this. You will still see this behavior if you explicitly specify (18, 2). However, prior to EF Core 7, the update pipeline could end up not handling your data correctly if you have very small values or very big values because their is no universal column type that can handle any .NET decimal at the SQL Server level.
