### ISSUE TITLE
Unmodified Custom T4 template scaffolding fails with missing definition for "GetRequiredUsings" method

### ISSUE THREAD

**Issue by tafs7** [dotnet/efcore#32848]
I followed the instructions available on https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/template and added the T4 template files to my project.

Before I made any modifications to the T4 files that were added, I ran the `dotnet ef dbcontext scaffold` tool on my project root folder. It built the project, began the scaffolding process as it showed some database warning about column default values, etc., but then it ran into the following error and exited the tool:

```
CodeTemplates\EFCore\DbContext.t4(89,37) : 
    error CS1061: 'MethodCallCodeFragment' does not contain a definition for 'GetRequiredUsings' and no accessible extension method 'GetRequiredUsings' accepting a first argument of type 'MethodCallCodeFragment' could be found (are you missing a using directive or an assembly reference?)
```
Detailed dotnet tool command used (conn string redacted):

```
dotnet ef dbcontext scaffold "[CONNECTION STRING]" Microsoft.EntityFrameworkCore.SqlServer 
    --context-dir DAL\Generated\Temp 
    --output-dir DAL\Entities\Generated\Temp 
    --context-namespace Infrastructure.DAL 
    --namespace Infrastructure.DAL.Entities 
    --context MyContext
    --no-onconfiguring
```
### NOTE
Worth noting that if I DO NOT add the Code Template T4 files to the project, the scaffolding tool works as expected, generating the entities and DbContext files.

EF Core version: 7.0.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows
IDE: Visual Studio 2022 17.8.1

**Comment by ErikEJ** [comment]
Please share your .csproj.

**Comment by tafs7** [comment]
A little more info...
So, Line 89 in the `DbContext.t4` file that is provided in the `CodeTemplates\EFCore` definitely has issues when running using EF Core 7.0.15:

```csharp
usings.AddRange(useProviderCarl.GetRequiredUsings());
```
The call to the extension method `GetRequiredUsings()` fails as it doesn't think it exists.

When I comment out that line in the template, the scaffolding completes successfully.

**Comment by tafs7** [comment]
I think I see the error in my ways. 🤦‍♂️
When I installed the Templates package in the CLI, I didn't specify a version, so it pulled the latest, which is 8.0.1. When I then added the CodeTemplates folder via `dotnet new ef`-templates`, it created the t4 files using the latest version which I had installed.  Unfortunately, my project is still on .NET 7, so I cannot use EF 8 yet.

Once I uninstalled the 8.0.1 version of the Templates package via the cli, and installed 7.0.15, and re-added the T4 files, it now had the prev version of the templates, without the offending line that depended on new code in 8.0.1.

I'm closing this issue.  Thanks!

**Comment by ajcvickers** [comment]
Note for triage: should we warn if the templates installed are later than the EF version in the project?

**Comment by ErikEJ** [comment]
There already is a check inside the template, but it is broken in this case as the template cannot be compiled

https://github.com/dotnet/efcore/blob/main/src/EFCore.Templates/EFCore.Templates.csproj#L89

**Comment by terryaney** [comment]
@tafs7 How do you specify which version of templates to install?

**Comment by ErikEJ** [comment]
Specify the NuGet package version...
