### ISSUE TITLE
In what scenarios will the new .Contains functionality using OPENJSON change the data being returned by a query?

### ISSUE THREAD

**Issue by jaxidian** [dotnet/efcore#32852]
## In what scenarios will the new .Contains functionality using OPENJSON change the data being returned by a query?

I have a business application that I'm working with for a client where we're working on a query. After migrating to .NET 8, EFCore 8, and everything, we're seeing some different data results from a very specific query. I have tried to recreate my observations in an independent project to write up a bug, but have been unable to reproduce the issue as I minimize the database schema and code. Unfortunately, I have ran out of time I can spend on that for now. Since I can't report a bug and I don't want to lose this knowledge, I figured I'd ask this question and see if this leads anywhere. Maybe this is a known issue that I couldn't find or maybe somebody has a nugget of info that will help me recreate the repro stuff (I know I'm close).

For what I'm seeing, I have a query that has effectively broken when switching to the new OPENJSON functionality in the new versions of EFCore. Specifically, certain records that were returned before are no longer returned under the new functionality. I'm very aware of #32394 and the conversation there, although that bug is about execution time/performance and not the resulting data. What I'm asking about is unrelated to performance and very related to actual data results from the query.

Based on what I learned from that bug's thread, I thought it would be interesting to try changing compatibility level to `120` to avoid the OPENJSON stuff. Sure enough, changing compatibility levels returns the old behavior where there are no records missing. Going back to the default setting (against SQL2022) returns to the behavior with missing data in the results. Additionally, I've implemented @ErikEJ `In` extension method and that also returns the old/correct behavior without the `UseCompatibilityLevel(120)` workaround. There's something about the OPENJSON implementation that breaks the data being returned by this query but I'm really struggling to reproduce it outside of this project.

My query looks something like this (abstracted away from the real industry it's in, so let's talk cars):

```
    public static IQueryable<CarResponseModel> TheQueryUsingContains(IReproContext ctx, List<string> containsCollection)
    {
        const string familyPrefixString  = "DEF-";

        // This is a sub query that is reused multiple times in our real code
        var carQuery = from c in ctx.Cars
                       join cfm in ctx.CarFamilyMappings on c.CarId equals cfm.CarId
                       join cf in ctx.CarFamilies on cfm.FamilyId equals cf.Id
                       where c.CarName != null
                             && ctx.CarProperties.Any(p => p.FamilyCode == cf.FamilyCode)
                            // THIS IS THE FIRST LINE WE'RE INTERESTED IN!!!!!!! There is no problem with this use of Contains. Data from this part is just fine.
                             && containsCollection.Contains(c.CarId.ToString())
                       select new
                              {
                                  CarId = c.CarId,
                                  CarName = c.CarName,
                                  CarFamilyCode = cf.FamilyCode,
                                  CarFamilyName = cf.FamilyName,
                              };

        var finalQuery = ctx.CarFamilies
                            .Where(cf => cf.FamilyCode != null
                                         && ctx.CarPropertyValues.Any(cpv => cpv.CarId == familyPrefixString + cf.FamilyCode))
                            .GroupBy(cf => cf.FamilyCode)
                            .Select(grp =>
                                        new CarResponseModel
                                        {
                                            Id = familyPrefixString + grp.First().FamilyCode,
                                            Name = (grp.First().FamilyCode == "C" ? "Sports Car"
                                                    : grp.First().FamilyCode == "S" ? "Family Car"
                                                    : grp.First().FamilyCode + " Class Car"),
                                            FamilyCode = grp.First().FamilyCode,
                                            FamilyName = grp.First().FamilyName
                                        })
                            // THIS IS THE SECOND LINE WE'RE INTERESTED IN!!!!!!! Changing this WHERE CONTAINS to ErikEJ's IN fixes the problem
                            .Where(c => containsCollection.Contains(c.Id!))
                            .Concat(carQuery.Select(c => new CarResponseModel
                                                         {
                                                             Id = c.CarId.ToString(),
                                                             Name = c.CarName,
                                                             FamilyCode = c.CarFamilyCode,
                                                             FamilyName = c.CarFamilyName
                                                         }));

        return finalQuery;
    }
```

### Include provider and version information

```
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.15.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.5.1" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi.Configuration.AppSettings" Version="1.5.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
	</ItemGroup>
```

- I originally suspected the UNION was a major source of problems, but I temporarily commented that out in my real project and that did not correct the behavior.
- One interesting thing is that the `CarFamilyMappings` table in this database has no PK and FKs are missing in a number of places that you might otherwise assume would be there.
- I suspect there's some combination of missing PKs/FKs that I have added (or perhaps forgotten to add) to my EF configuration with `ModelBuilder`.

But I guess the core of my question is: Are there known issues that will help me focus this down on what's really important and, eventually, create a fully reproducible bug here? Or alternatively, is this already a known issue so I don't have to spend any further time trying to help document/repro this issue?

-----

EF Core version: 8.0
Database provider: SQL Server 2022
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 17.8.3)

**Comment by IanKemp** [comment]
What does the generated query look like with `UseCompatibilityLevel(120)`, versus without? Make sure you use `EnableSensitiveDataLogging` to see the actual values, as I suspect that's where the problem lies.

**Comment by jaxidian** [comment]
@IanKemp The queries are definitely different. Rather than passing the JSON string(s?) in for OPENJSON, it instead passes fixed IDs in for the `WHERE IN (@p1, @p2, etc)` query. I've taken the OPENJSON query and played around with it in SSMS, but as you know, EF can produce some fairly tedious-to-a-human query, even if it's fairly well optimized withing SQL Server. I just haven't been able to narrow it down to where the problem is in that query. But to the point I think you're getting to: The generated SQL does produce different results. But it's a very different query with Compatibility level set to 120.

Here's a totally different query that is MUCH simpler than the rabbit hole I was chasing before that shows the differences and has different results. For the two IDs being passed in, one is a valid ID and one is not. I expect 1 result but only the second query gives me 1 result and the first query gives me 0 results:

```
-- Default Modern Behavior:
-- NOTE: SQL Profiler showed this wrapped in an `exec sp_executesql` call:
DECLARE @__input_InputInfo_CarIds_0 nvarchar(4000) = N'["DEF-S","BadIdValue"]'

SELECT 'DEF-' + COALESCE([p1].[FamilyCode], '')
FROM [AnotherSchema].[Cars] AS [c]
INNER JOIN [AnotherSchema].[CarFamilyMapping] AS [p0] ON [c].[CarId] = [p0].[CarId]
INNER JOIN [AnotherSchema].[CarFamily] AS [p1] ON [p0].[FamilyId] = [p1].[Id]
WHERE [c].[SomeColumn] IS NOT NULL AND EXISTS (
    SELECT 1
    FROM [CarProperty] AS [d]
    WHERE [d].[ProductFamily] = [p1].[FamilyCode])
GROUP BY [p1].[FamilyCode]
HAVING 'DEF-' + COALESCE([p1].[FamilyCode], '') IN (
    SELECT [i].[value]
    FROM OPENJSON(@__input_InputInfo_CarIds_0) WITH ([value] char(1) '$') AS [i]
)

-- Compat set to 120
-- NOTE: SQL Profiler showed this as raw SQL
SELECT 'DEF-' + COALESCE([p1].[FamilyCode], '')
FROM [AnotherSchema].[Cars] AS [c]
INNER JOIN [AnotherSchema].[CarFamilyMapping] AS [p0] ON [c].[CarId] = [p0].[CarId]
INNER JOIN [AnotherSchema].[CarFamily] AS [p1] ON [p0].[FamilyId] = [p1].[Id]
WHERE [c].[SomeColumn] IS NOT NULL AND EXISTS (
    SELECT 1
    FROM [CarProperty] AS [d]
    WHERE [d].[ProductFamily] = [p1].[FamilyCode])
GROUP BY [p1].[FamilyCode]
HAVING 'DEF-' + COALESCE([p1].[FamilyCode], '') IN ('DEF-S', 'BadIdValue')
```

I sanitized this SQL to stay in sync with my Car repro case, but this came from SQL Profiler in my real client application. I may have made an error when sanitizing the query, but all I did was change names and values. Structure is exactly as Profiler shows it.

**Comment by jaxidian** [comment]
If I take those differences and dumb them down even more, the true difference is that these two queries return different results, and that's effectively what EF is generated SQL for:

```
SELECT * FROM CarFamily cf WHERE 'DEF-' + COALESCE(cf.FamilyCode, '') IN ('DEF-S', 'BadTestId')

SELECT * FROM CarFamily cf WHERE 'DEF-' + COALESCE(cf.FamilyCode, '') IN (
    SELECT [i].[value]
    FROM OPENJSON('["DEF-S","BadTestId"]') WITH ([value] char(1) '$') AS [i]
)
```

![image](https://github.com/dotnet/efcore/assets/260128/38a69a1c-316c-48ac-82bf-c218490eb098)

**Comment by roji** [comment]
Seeing that you're dealing with `char(1)`, there's a good change #32735 may have something to do with it indeed (though note that that's causes rows to get returned which shouldn't, rather than the other way around).

**Comment by jaxidian** [comment]
@roji Looks like the daily does have the issue fixed. I can't really say what the exact trigger is from the EF side since my repro project failed to reproduce it, but my real project has the correct data being returned when running with the daily and without the 120 hack. Your suspicion that the `char(1)` is related "feels" like it might be going down the right path to me. I bet my repro project took liberties with some data types in the DB schema just because I was moving fast.

At any rate, looks like y'all are already on whatever it was that I was seeing. However, for me, it was definitely causing missing data rather than extra data in both of my queries where I could see it, in case that's of any value to you.

Thanks y'all! Have a great day!
