### ISSUE TITLE
Is there any example of a C# entity that can use SqlServerUdtTypeMapping for attribute/column mapping?

### ISSUE THREAD

**Issue by indrajitjadeja** [dotnet/efcore#32862]
I want to understand the use case of the [SqlServerUdtTypeMapping](https://github.com/dotnet/efcore/blob/v8.0.1/src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs) class and its relation to SQL Server's UDT column present in a table.

I can only find test coverage of constructor and clone behavior, but there is no entity-based unit test coverage.

Please assist.

### provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by indrajitjadeja** [comment]
@ajcvickers

**Comment by indrajitjadeja** [comment]
@roji

**Comment by ajcvickers** [comment]
@indrajitjadeja SqlServerUdtTypeMapping is part of the type mapping infrastructure of EF Core. It is used by the SQL Server database provider when mapping SQL Server UDT types. It isn't something that can be used directly.
