### ISSUE TITLE
[Microsoft.Data.Sqlite] iOS apps are terminated every time they enter the background if they share an encrypted database with an app extension

### ISSUE THREAD

**Issue by baaaaif** [dotnet/efcore#32863]
Context: https://github.com/sqlcipher/sqlcipher/issues/255
I'm using Microsoft.EntityFrameworkCore.Sqlite.Core together with SQLitePCLRaw.bundle_e_sqlcipher

Related SQLitePCLRaw issue https://github.com/ericsink/SQLitePCL.raw/issues/241#issuecomment-447049979
Related change made in popular sqlite-net https://github.com/praeclarum/sqlite-net/pull/775 (resulting from previous SQLitePCLRaw issue)

When using a SqliteConnection, I currently see no possibility of executing PRAGMA statements directly after the "PRAGMA key".
In my opinion, in order to be able to execute the required PRAGMA cipher_plaintext_header_size directly after the key, it would be great to have a preKeyAction and a postKeyAction, as is now the case with sqlite-net

### Include version information

Microsoft.Data.Sqlite version: 7.0.15
Target framework: NET7/NET8
Operating system: iOS

**Comment by ajcvickers** [comment]
Duplicate of #29186
