### ISSUE TITLE
Multiple DbContext for Single databse

### ISSUE THREAD

**Issue by diamondhna** [dotnet/efcore#32872]
I have two DbContexts, and I want to join  two tables from different dB contexes. All my tables are in one database, and due to the size of the database, I want to separate DbContexts for each part of my software. However, EF does not allow me to join them. The EF code I have checked is a single piece of code that addresses this issue, but there is no way to configure this piece of code to be separate at the level of DbContexts for the databases. Is it possible to configure this and add this capability to EF?

**Comment by roji** [comment]
If you want to join two different tables, that means they must be in the same EF model - EF must be able to reason about the relationship between the tables. You can only "split" a database to multiple models (contexts) if there are no relationships.

**Comment by ajcvickers** [comment]
To add to what @roji said, if there are foreign keys between the two bounded contexts, then don't map these as relationships, but leave the FK properties themselves so that they can still be used to manually join across the bounds of the models.

**Comment by abadakhshan** [comment]
@roji @ajcvickers 

I have the same problem.

If I  join two different tables from different contexts I got this exception:

`: 'Cannot use multiple context instances within a single query execution. Ensure the query uses a single context instance.'`

For example:

```
 from b in _ctx.Branches
                join u in _ctx2.Usets
                    on b.UserID equals u.ID
```

These two tables are in a database and  if EF ignores this exception, the rest will work correctly.

**Comment by roji** [comment]
@abadakhshan yes, that's by-design. You cannot involve two contexts in the same query in this way.

**Comment by abadakhshan** [comment]
@roji 

What's your solution in this case?

**Comment by roji** [comment]
@abadakhshan you cannot involve two different contexts in the same query; each may have a completely different database connection, meaning a single query can't span both (and the different models also raised lots of complications).

You can use AsEnumerable() to switch to client evaluation, effectively performing two database queries and joining on the client:

```c#
from b in _ctx.Branches.AsEnumerable()
join u in _ctx2.Users.AsEnumerable
on b.UserID equals u.ID
```

... but note that this doesn't join in the database (because again, that's not possible) - it brings both tables entirely to the client, and performs the join in .NET. If the tables are big, this is an extremely bad idea.

If you do need to perform a join in the database, then the two entity types need to be in the same model.

**Comment by abadakhshan** [comment]
Thank you @roji 
In Many cases It's not possible  to use client side evaluation.

Many times there are tables that are independent of each other, so we put them in different bounded contexts.( in EF, different DB context). But we need some reports or some list of data that includes combination of data from those tables.
Usually, these lists include features such as paging, sorting and filtering which leads us to use join between those tables.

Maybe using **RawQuery** is a solution But I was wondering if EF could disable this **Exception** with something like Config.

Of course, I did a simple test
(
remove this:
```
 else if (!ReferenceEquals(queryProvider, _currentQueryProvider))
            {
                throw new InvalidOperationException(CoreStrings.ErrorInvalidQueryable);
            }
```
)
 and everything worked fine, but I'm not sure what other issues this could lead to.
