### ISSUE TITLE
.NET8, MS VS 2022 17.8.4, Entity Framework runtime error with "Any"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32908]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET8-MS-VS-2022-1784-Entity-Framewo/10560903)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:could have been move from .NET4 to .NET8]
return db.PlyrLdrs.Where(g => g.seatIdInt == seatIdInt).Where(g => (g.playerLadderId == theLadder.id) || (g.playerLadderId == theLadder.connectId)).Where(g => g.status == PlyrLdrDTO.STATUS_AVAILABLE).Where(g => gids.Any(plyrGlobalId => plyrGlobalId == g.plyrGlobalId)).ToList();

worked prior to .NET 8/Windows 10, Visual Studio 17.8.4.  Now fails at runtime with some mention of improper SQL "WITH".
 
-- seems like everything is fine until 
.Where(g => gids.Any(plyrGlobalId => plyrGlobalId == g.plyrGlobalId)
.
gids is List<string> gids

---
#### Feedback Bot on 1/15/2024, 02:23 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jrkcoder** [comment]
I updated Azure DB compatibility and .Any works now. Thanks!
