### ISSUE TITLE
Copied entity with navigation properties causes duplication of navigation entities

### ISSUE THREAD

**Issue by DrMueller** [dotnet/efcore#32904]
## Ask a question

Hello there, I've found a very strange occurrence. Please clone the repo below, you will see exactly what I mean directly. To describe it: When an entity with sub-entities (like Agenda with a list of AgendaPoints) uses internally a Hashset and if an original entity is deep copied and then added to the change tracker, it somehow adds another Agendapoint to the deep copied Agenda.

To show what I mean in the code:
```
        private static void VerifyDeepCopyProblem()
        {
            var dbContext = new AppDbContext();

            // Create Agenda
            var newAgenda = new Agenda();
            newAgenda.Points.Add(new AgendaPoint());

            // Deepcopy it
            var agendaDeepCopied = newAgenda.DeepCopy();

            // Track i2
            dbContext.Add(agendaDeepCopied);

            // Bam, two agenda points
            Console.WriteLine($"Count with deepcopy {agendaDeepCopied.Points.Count}");
        }
```

The `agendaDeepCopied` will at the end have two AgendaPoints, although never created two nor added them anywhere. 

My assumption is, that there is something fishy in the HashSet comparison. When I use
```
   public Agenda()
   {
       Points = new List<AgendaPoint>();
   }
```

instead of 
```
   public Agenda()
   {
       Points = new HashSet<AgendaPoint>();
   }
```

Everything works fine.

I've also tried to debug EF Core and I'm thinking, that there is something wrong in `StateManager.ResolveToExistingEntry`, but unfortunately the debugger stops working when trying to debug further.

Would you mind having a look, at why copying as HashSet has this very strange behavior? 

Thank you very much!

### Include your code

I've created an example to reproduce it: https://github.com/DrMueller/DeepCopyEfCoreTest

### Include provider and version information

EF Core version: 8.0.1
Database provider: Doesn't matter, The test app uses in-memory
Target framework: (e.g. .NET 6.0): net8

**Comment by ajcvickers** [comment]
@DrMueller I think this is an issue with the deep copy code. In particular, I think the cloning of the private fields of the HashSet puts the new HashSet into an inconsistent state. Replacing the deep copy code that does this manually causes the problem to go away:

```C#
            // Deepcopy it
            var agendaDeepCopied = new Agenda()
            {
                Id = newAgenda.Id
            };
            foreach (var point in newAgenda.Points)
            {
                agendaDeepCopied.Points.Add(new AgendaPoint()
                {
                    Id = point.Id,
                    Description = point.Description
                });
            }
```

**Comment by DrMueller** [comment]
> @DrMueller I think this is an issue with the deep copy code. In particular, I think the cloning of the private fields of the HashSet puts the new HashSet into an inconsistent state. Replacing the deep copy code that does this manually causes the problem to go away:
> 
> ```cs
>             // Deepcopy it
>             var agendaDeepCopied = new Agenda()
>             {
>                 Id = newAgenda.Id
>             };
>             foreach (var point in newAgenda.Points)
>             {
>                 agendaDeepCopied.Points.Add(new AgendaPoint()
>                 {
>                     Id = point.Id,
>                     Description = point.Description
>                 });
>             }
> ```

Hello Arthur, thank you for the feedback. You don't happen to know how to properly copy a HashSet in a generic manner? Otherwise we might need to look for other DeepCopy implementations.

**Comment by ajcvickers** [comment]
@DrMueller I would not trust any code that attempts to copy unknown types via their private fields. I don't believe a completely reliable generic deep copy is possible.

**Comment by DrMueller** [comment]
> @DrMueller I would not trust any code that attempts to copy unknown types via their private fields. I don't believe a completely reliable generic deep copy is possible.

Thank you very much, looking for another solution then.
