### ISSUE TITLE
await dbContext.Database.SqlQuery<*>(....).ToListAsync()  hang

### ISSUE THREAD

**Issue by TheoVC** [dotnet/efcore#32906]
I am transforming some functions to their asynchronous version, I am using the SqlQuery method, but these asynchronous versions hang. without throwing a exception... the application is simply closed.

I made the tests in Entity Framework 6 and 8 with a simple console application with the same result

```C#
static async Task MyNewAsyncTest()
{
    try
    {
        using (var dbContext = new DbContext())
        {
           // Sincronous version, These works fine!
           var data = dbContext.Database.SqlQuery<string>($"select cod_empresa from si_empresa").ToList();
           var data = dbContext.Database.SqlQuery<Persona>($"select grado_discapacidad_persona, nombres_persona from rh_persona").ToList();

           // The same but async version hang up, with primitive types or clases
           var data = await dbContext.Database.SqlQuery<string?>($"select cod_empresa from si_empresa").ToListAsync();
           var data = await dbContext.Database.SqlQuery<Persona>($"select grado_discapacidad_persona, nombres_persona from rh_persona").ToListAsync();

           // even weirder, if I dont apply await inmediately, but wait 2 secs then it works !!! 
           var Get1 = dbContext.Database.SqlQuery<string>("select cod_empresa from si_empresa").ToListAsync();
           Thread.Sleep(2000);
           var data = await Get1;

            foreach (var i in data)
                Console.WriteLine(i);
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.ToString());
    }
    Console.ReadLine();
}

```

```C#
public class Persona
{
    public string nombres_persona { get; set; }

    public int? grado_discapacidad_persona { get; set; }
}
```

```SQL
/*==============================================================*/
/* Table: RH_PERSONA                                            */
/*==============================================================*/
create table RH_PERSONA (
   NOMBRES_PERSONA      varchar(30)          not null,
   GRADO_DISCAPACIDAD_PERSONA int                  null
)
```

EF Core version: 6 and 8
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.Net Framework 4.8 and .NET Core 8.0)
Operating system: Windows 11
IDE: (Visual Studio 2022 17.8.5)

**Comment by roji** [comment]
If the data being loaded is big (e.g. big strings or binary data), then this is probably https://github.com/dotnet/SqlClient/issues/593.

If not, then we need a minimal, runnable repro to investigate this further - a self-contained console program, including the database schema and some data. Basically something we can use to see the bug happening.

**Comment by TheoVC** [comment]
I attach a zip with a simple ConsoleApp and the database used (or use the script)

[ConsoleAppAsyncHang.zip](https://github.com/dotnet/efcore/files/14042403/ConsoleAppAsyncHang.zip)

**Comment by TheoVC** [comment]
Sorry, I discovered it's because the main function is asyncronous, so the main() terminates the execution before the job is done.
