### ISSUE TITLE
Update Microsoft.CodeAnalysis version

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#32926]
Issue to track this following discussion on #32070 and PR #32922.

This is merged to main, but we could consider backporting to a patch if there is demand.

**Comment by 21r8390** [comment]
@ajcvickers When I update from .NET 6 to .NET 8, I get a version conflict because of Microsoft.EntityFrameworkCore.Tools and Microsoft.EntityFrameworkCore.Design. Is it possible that this fix will be integrated into the next version?

**Comment by ajcvickers** [comment]
@21r8390 It's possible we will backport this to a patch, but not decided yet. /cc @SamMonoRT

**Comment by rogereeno** [comment]
Are there any plans to back-port this to EF Core 8 and release something like 8.0.2?  I am running into conflicts when using Microsoft.Orleans.Serialization 8.0.0 and using VS 2022 17.8.5.

**Comment by ajcvickers** [comment]
@rogereeno Can you test with the [daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) to verify that your issue is fixed there. The more people who do this, the more confidence we will have that patching is the right thing to do, if we get approval.

**Comment by ajcvickers** [comment]
@oleggolovkov There is a possibility that we will patch this, but we need enough people to report back that the daily build is working first.

**Comment by ErikEJ** [comment]
@ajcvickers 

<img width="451" alt="image" src="https://github.com/dotnet/efcore/assets/4169187/f039fd4f-210f-4f53-9c45-3405dd5f8346">

**Comment by OskarKlintrot** [comment]
Just chipping in my wish for this to be patched to v8 as well. Atm we can't upgrade to .NET 8 since Powershell SDK requires the latest version for it to properly work with the new RID in .NET 8. But Powershell SDK and EF Core 8 can't be installed together right now due to this conflict.

**Comment by Myster** [comment]
+1, In my case I am working with Umbraco 13, unfortunately, I don't have the bandwidth to be testing daily builds :-(

> Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.10.0 directly to project Redacted to resolve this issue. 
>  Redacted -> Umbraco.Forms 13.5.0 -> Umbraco.Forms.Examine 13.5.0 -> Umbraco.Forms.Core 13.5.0 -> Umbraco.Licensing 13.0.1 -> Umbraco.Cms.Web.Common 13.9.2 -> Umbraco.Cms.PublishedCache.NuCache 13.9.2 -> Umbraco.Cms.Infrastructure 13.9.2 -> Microsoft.CodeAnalysis.CSharp 4.10.0 -> Microsoft.CodeAnalysis.Common (= 4.10.0) 
>  Redacted -> Microsoft.EntityFrameworkCore.Design 8.0.11 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).
> 

So I added these direct references to my csproj

    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />

But when I try create a migration I get.

> Unable to load one or more of the requested types.
> Method 'get_IsParamsArray' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationParameterSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
