### ISSUE TITLE
Loading specific columns without creating additional mapping classes

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [dotnet/efcore#32935]
Is it possible to load only specific columns without having to create anonymous types or additional classes ?

Let's say we have tables `Student` and `EnrolledCourse`

Student table rows -> id (int), name (varchart(100))

EnrolledCourse rows -> id (int), course_id (int), student_id (int)

One to many relationship between `Student` and `EnrolledCourse`

Db is scaffolded and entity c# classes created. 

I want to get students and _only_ the course_id's of the enrolled courses. I could do it like this, but its fetching all columns of courses which I dont want,

```c#
var data = _dbContext.Students.Include(x => x.EnrolledClasses).ToList();
```

So, I do something like this,

```c#
var data = _dbContext.Students
  .Include(x => x.EnrolledClasses)
  .Select(x => new { Student = x, EnrolledCourseIds = x.EnrolledCourses.select(x => x.CourseId) })
  .ToList();
```

The problem here is that I need to deal with anonymous types. Which is fine for a few cases. But this starts to become hard to manage when the tables and use cases grow. 

Is there some way to still use the scaffolded entities and only load those specific columns? Deserialize to the same scaffolded class but with only `CourseId` having value, rest of them can be `default` of that type.

One of the recommendations for efficient querying is to fetch only the columns that we care about but from a management standpoint, this starts to become difficult.

Any other suggestions and/or pointers are more than welcome. Thanks. 

### provider and version information

EF Core version: 5.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by roji** [comment]
Instead of projecting out to anonymous types, you can project out to the same CLR type being used to map the database:

```c#
var data = _dbContext.Students
  .Include(x => x.EnrolledClasses)
  .Select(x => new Student { Name = x.Name, ... })
  .ToList();
```

Note that this disables change tracking - just like when projecting to anonymous types - so changes to the project Student cannot be persisted back to the database with SaveChanges. Partial loading of entity types (with change tracking) is tracked by #1387.
