### ISSUE TITLE
Sugar for HierarchyId path generation

### ISSUE THREAD

**Issue by Rezakazemi890** [dotnet/efcore#32943]
I hope this message finds you well. I am writing to propose a feature enhancement for the HierarchyId type. I believe that the addition of a method or function for automatic path generation would greatly enhance the usability of the Hierarchy data structure.

To illustrate my suggestion, I have prepared a sample implementation using a TreeNode class:

```csharp
public class TreeNode
{
    public TreeNode(int id, int? parentId, string name, HierarchyId path)
    {
        Id = id;
        ParentId = parentId;
        Name = name;
        Path = path;
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public TreeNode? Parent { get; set; }
    public ICollection<TreeNode>? SubCategories { get; set; }
    public int? ParentId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public HierarchyId Path { get; set; }
}
```

Currently, when creating a new TreeNode, users are required to manually define the path with a specific format (Like `"/1/1/2/"`). For instance:

```csharp
var root = new TreeNode(1, null, "Root", HierarchyId.GetRoot());
var first = new TreeNode(2, 1, "First", HierarchyId.Parse("/1/"));
var second = new TreeNode(3, 1, "Second", HierarchyId.Parse("/2/"));
var third = new TreeNode(4, 2, "Third", HierarchyId.Parse("/1/2/"));
```

This approach has the potential for error due to manual path formatting by users.

My suggestion is to introduce an automatic path generation method or function in the HierarchyId class, such as `HierarchyId.GeneratePath(TreeNode parent)` or a similar method for convenient and error-free path creation. This would streamline the process and reduce the likelihood of mistakes.

I believe that implementing this feature would contribute to a more robust and user-friendly experience when working with the HierarchyId type.

Thank you for considering my proposal.

**Comment by ajcvickers** [comment]
Note for triage: we have talked about this in the past. The main problem is that generating valid paths is not possible unless the existing paths are known, some of which may be in the database but not tracked.

**Comment by Rezakazemi890** [comment]
Is it not possible to think about creating the path using the separator and the parent?  I will try to prepare a sample of my proposal and comment here.

**Comment by Rezakazemi890** [comment]
I try to write my suggestion in [This PR](https://github.com/dotnet/efcore/pull/33062).
Thanks for attention.
@ajcvickers

**Comment by bricelam** [comment]
FWIW, I believe that's what the `GetDescendant` method is intended for:

```cs
var root = HierarchyId.GetRoot();
var first = root.GetDescendant(null); // /1/
var second = root.GetDescendant(first); // /2/
var third = first.GetDescendant(null); // /1/1/
```

**Comment by Rezakazemi890** [comment]
> FWIW, I believe that's what the `GetDescendant` method is intended for:
> 
> ```cs
> var root = HierarchyId.GetRoot();
> var first = root.GetDescendant(null); // /1/
> var second = root.GetDescendant(first); // /2/
> var third = first.GetDescendant(null); // /1/1/
> var fourth = first.GetDescendant(third); // /1/2/
> var fifth = first.GetDescendant(third, fourth); // /1/1.5/
> ```

Thanks for your point @bricelam,
but
The `GetDescendant` method is used when we need to have the child of a Node.

While a new overload is created on the `Parse` method.
In the `main Overload`, it was necessary to give a `String` to the `Parse` method and make sure that its `format` and `structure` are **correct**, and in fact, we didn't have any approach except to make sure that we don't make mistakes in string creation.

The new overload that has been added makes it possible that when we want to `create a new node` or we want to `receive a node that we have a parent related` to without getting involved in the `string structure` that we create as `Path`. Have the related `HierarchyId` . And wherever needed, we can use both overloads.

For example:

```cs
//parent created with main overload in this sample:
var parent= HierarchyId.Parse("/1/2/3/1/"); //   /1/2/3/1/

//parent can create with new overload too:
//var parent= HierarchyId.Parse(parentOfParent, 1); //   /1/2/3/1/

var mainOverload = HierarchyId.Parse("/1/2/3/1/2/");  //   /1/2/3/1/2/
var newOverload = HierarchyId.Parse(parent, 2);  //   /1/2/3/1/2/

Assert.Equal(mainOverload, newOverload); // true
```
