### ISSUE TITLE
Update object value by with key

### ISSUE THREAD

**Issue by Timor666** [dotnet/efcore#32955]
Forgive me for being a rookie

for example i have class

```C#
public Class User
{
     public ulong UserID;
     public string UserName;
     public string Sex;
     public int age;
}
```

Context:

```c#
public class DataBaseContext : DbContext
{
        public DbSet<User> User { get; set; }
}
```

and a function to update 

```c#
void Update(ulong id string key ,string value)
{
     User  u = DbContext.User.Where(x=>x.UserId = id);


   //before 
   u.sex = value;
   u.UserName= "jack";
   DbContext.SaveChanges();


   //now   i want update value by with key filed name
    u.Update("UserName,"jack");
    u.Update("Sex,"boy");
     u.Update("Enum,value);
   DbContext.SaveChanges();
}
```

What is the correct update code for updating values based on field names
or

**Comment by Timor666** [comment]
run
UserBaseInfos.Entry(user).Property("RegisterTime").CurrentValue = "2022-11-12 22:33:12";

i get exception
System.InvalidCastException:“Unable to cast object of type 'System.String' to type 'System.DateTime'.”

**Comment by Timor666** [comment]
> 这个问题缺乏足够的信息让我们能够充分了解正在发生的事情。请附上一个小型的、可运行的项目或发布一个小型的、可运行的代码清单，以重现您所看到的内容，以便我们进行调查。

this is all code 


namespace EFCore
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.IO;
    using NetLog4;

    public enum Job 
    { 
        Admin = 0,
        NormalUser = 1,
        Other = 2,
    }
    public class User
    {
        public int ID { get; set; }
        public ulong UserID { get; set; } = 0;
        public string UserName { get; set; } = string.Empty;
        public Job Job { get; set; } = Job.Admin;
        public DateTime CreateTime { get; set; } = DateTime.MinValue;
    }

    public class DataBaseContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DataBaseContext()
        {
            var folder = Environment.CurrentDirectory;

            string DbPath = Path.Join(folder, "DataBase.db");
            Database.EnsureCreatedAsync();
            Log.Info("Start EFCore: " + DbPath);
        }
 
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            var folder = Environment.CurrentDirectory;

            string DbPath = Path.Join(folder, "DataBase.db");
            options.UseSqlite($"Data Source={DbPath}");
        }
    }

    public class Program
    {
        public static DataBaseContext db;
        public static void Main(string[] args)
        {
            db = new DataBaseContext();

            User addUser = new User();
            addUser.UserName = "Jack";
            addUser.UserID = 10001;
            db.Users.Add(addUser);
            db.SaveChanges();

            User queryUser = db.Users.Where(x => x.UserName == "Jack").FirstOrDefault();

            //before  it can run 
            queryUser.UserName = "Tom";
            queryUser.Job = Job.Other;
            db.SaveChanges();


            //now
            //Due to certain limitations, I can only obtain the changed Key and value
            Program.db.Users.Entry(queryUser).Property("UserName").CurrentValue = "Tom";
            Program.db.Users.Entry(queryUser).Property("UserID").CurrentValue = "1002";
            Program.db.Users.Entry(queryUser).Property("Job").CurrentValue = "NormalUser";
            Program.db.Users.Entry(queryUser).Property("CreateTime").CurrentValue = "2024-01-29 23:32:32";
        }
    }
}

**Comment by Timor666** [comment]
I'm not sure if it's helpful

**Comment by ajcvickers** [comment]
@Timor666 First, make sure not to call async methods without awaiting them--for example, the call to `EnsureCreatedAsync`. Second, this code `Program.db.Users.Entry(queryUser).Property("UserName").CurrentValue = "Tom";` just sets the current value of the property. It is roughly equivalent to `queryUser.UserName = "Tom";`.
