### ISSUE TITLE
database update to fast for database

### ISSUE THREAD

**Issue by openblocki** [dotnet/efcore#32960]
When Updating Database with dotnet ef database update, a problem might occurr where the Tool works faster than the Database can finish writing so if in the Migration Code a table references the Table above it with say a Foreign Key, the Database Returns an Error because the Database has not been done creating yet, which can cause issues. 

### Migration Code
```C# 
migrationBuilder.CreateTable(
                   name:"T_Intern",
                   schema:"export",
                   columns:c => new
                   {
                       ID = c.Column<int>(nullable: false),
                       Birthday = c.Column<DateTime>(nullable: false, type: "date"),
                       WorkerID = c.Column<int>(nullable: false),
                       Name = c.Column<String>(nullable: false, maxLength: 100),
                       Gender = c.Column<String>(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
                       Home = c.Column<String>(maxLength: 100),
                       Entry = c.Column<DateTime>(type: "date"), 
                       Exit = c.Column<DateTime>(type: "date"),
                       Education = c.Column<String>(maxLength: 255),
                       sickdays = c.Column<int>(),
                       access = c.Column<int>(nullable: false),
                       NotApplyable = c.Column<Boolean>(nullable: false),
                       NotApplyAbleReason = c.Column<String>(),
                       ImportetAt = c.Column<DateTime>(nullable: false, precision: 7, type: "datetime2")
                   },
                   constraints: table =>
                   {
                       table.PrimaryKey(name:"PL_export.T_Intern", x => x.ID);
                       table.UniqueConstraint(name:"UX_Export_T_Intern_WorkerID", x => x.WorkerID);
                   }
               );

migrationBuilder.CreateTable(
                  name:"T_BestIntern",
                  schema:"export",
                  columns:c => new
                  {  
                      Year = c.Column<int>(nullable: false),
                      IsSecondAccess = c.Column<Boolean>(nullable: false),
                      InternID = c.Column<int>(nullable: false),
                  },
                  constraints: table =>
                  {
                      table.PrimaryKey(name:"PK_export.T_BestIntern",t => new { t.Year, t.IsSecondAccess, t.InternID});
                      table.ForeignKey(
                          name:"FK_export.T_BestIntern_export.T_Intern_InternID",
                          column: x => x.InternID,
                          principalTable:"export.T_Intern"
                      );
                      table.UniqueConstraint(name: "IX_InternID", columns: x=> x.InternID);
                  });


```

```C# 

migrationBuilder.DropTable("export.T_BestIntern");

migrationBuilder.DropTable("export.T_Intern");

migrationBuilder.DropForeignKey("export.T_BestIntern", "InternID", "export.T_Intern");

migrationBuilder.DropIndex("export.T_BestIntern", new[] { "InternID" }.ToString());

migrationBuilder.DropIndex("export.T_Intern", "UX_Export_T_Intern_WorkerID");


```

Microsoft.Data.SqlClient.SqlException (0x80131904): Foreign key 'FK_export.T_BestIntern_export.T_Intern_InternID' references invalid table 'export.T_Intern'.

### Include provider and version information

EF Core version: 7.0.14
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: JetBrains Rider 2023.2

**Comment by roji** [comment]
@openblocki I'm not completely clear on what you're doing from the above discussion, but it sounds like you're trying to apply a migration while at the same time performing regular queries/updates - this is indeed likely to result in such problems as the table schema is changing under the application as it runs.

If so, then in most scenarios, migration should be applied as part of deployment of a new version of the application, without the application running at the same time. If you need zero-downtime migrations, then you  need to first perform non-destructive migrations (e.g. add a new column), change you program code and only then drop the old column, once it's no longer used. This is a complex topic that requires lots of careful planning, and isn't an EF-specific problem but rather a general database management problem.

**Comment by openblocki** [comment]
I see where the missundersanding lies, what i was trying to say is, that when applying the Migration, when a Table that is Dependent on a Table that is codded directly above it like: 
´´´
migrationBuilder.CreateTable(Table1);

migrationBuilder.CreateTable(Table2);
´´´

In this Case Table Table2 contains Table1 as Foreign Key and thus needs it existent in the Database, but now comes the issue of the Database beeing to slow for the code. Because the Code that builds Table2 already started trying to build it before Table1 finished on side of the Database, so the Database can't use Table1 in Table2 thus returns an Error, stopping the Update, 

In my case there is Many more Tables 

Table1=>Table2 : this means that Table1 need Table2

so instead of writing 

´´´
migrationBuilder.CreateTable(Table1);

migrationBuilder.CreateTable(Table2=>Table1);

migrationBuilder.CreateTable(Table3);

migrationBuilder.CreateTable(Table4);

migrationBuilder.CreateTable(Table5);

migrationBuilder.CreateTable(Table6);

migrationBuilder.CreateTable(Table7);

´´´

i would need to write something like
´´´
migrationBuilder.CreateTable(Table1);

migrationBuilder.CreateTable(Table3);

migrationBuilder.CreateTable(Table4);

migrationBuilder.CreateTable(Table5);

migrationBuilder.CreateTable(Table6);

migrationBuilder.CreateTable(Table7);

migrationBuilder.CreateTable(Table2=>Table1);

´´´

For the Database to Finish Table1 before it starts Table2, which is matter of milliseconds but still enough time to make a difference

**Comment by openblocki** [comment]
Seems like it was another issue that was deeper in the code
