### ISSUE TITLE
.net 6 to .net 8, several foreigns keys will be removed and recreate in a migration

### ISSUE THREAD

**Issue by Alexandre-NAUD** [dotnet/efcore#32962]
Hi,

After updating our project to .net 8.0 and perform a migration with no model change, severals foreigns keys are dropped and recreated  with Cascade onDelete like this :

```C#
migrationBuilder.DropForeignKey(
    name: "FK_Common_UpdateConditionalStyleLock_Common_UpdateLock_UpdateLockID",
    table: "Common_UpdateConditionalStyleLock");

migrationBuilder.AddForeignKey(
    name: "FK_Common_UpdateConditionalStyleLock_Common_UpdateLock_UpdateLockID",
    table: "Common_UpdateConditionalStyleLock",
    column: "UpdateLockID",
    principalTable: "Common_UpdateLock",
    principalColumn: "UpdateLockID",
    onDelete: ReferentialAction.Cascade);
```

These keys represents an inheritance :

```C#
[Table("Common_UpdateLock")]
public class UpdateLock
{
    [Required]
    public long UpdateLockID { get; set; }

    [Required]
    public virtual User LockedBy { get; set; }

    [Column(TypeName = "DateTime")]
    public DateTime LockDate { get; set; }
}

[Table("Common_UpdateConditionalStyleLock")]
public class UpdateConditionalStyleLock : UpdateLock
{
    [Required]
    public int ConditionalStyleID { get; set; }
}

```
With .net 6.0 and EFCore 6, no problems.

Have you any idea to resolve this problem ?

Thank you

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 8.0)
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.5

**Comment by Ryujose** [comment]
I suggest to take a look into the history of the other migrations to see if there's some particular behaviour.

**Comment by Alexandre-NAUD** [comment]
It's ok, I made some changes and apply the migration without error, it was due to upgrade EF6 to EF8 (EF6 to EF7)
