### ISSUE TITLE
Spell Check has issues with field names create by Scaffold-DbContext (C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32970]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Spell-Check-has-issues-with-field-names-/10571573)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.19.0 Preview 4.0]
Spell check is a terrific tool, but the way field names are dealt with using Scaffold-DbContext creates the need to ignore a lot of field names.  In the below examples you can see that if Userid were UserId, the spelling error would be resolved.
These fields are used in numerous places. Resolving this would be very tedious.
This is only for one table in one Database.
For me this is a huge issue.
If there were a way to exclude field names from spell check, this problem might be eliminated.

Examples:
 protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
     modelBuilder.Entity<LastUsedBin>(entity =>
     {
         entity.HasKey(e => e.LastBinId).HasName("PK__LastUsed__B3E765EC708EB0F2");

         entity.ToTable("LastUsedBin");

         entity.Property(e => e.LastBinId)
             .ValueGeneratedNever()
             .HasColumnName("lastBinId");
         entity.Property(e => e.LastBinName)
             .IsRequired()
             .HasMaxLength(15)
             .HasDefaultValue("STOCK")
             .HasColumnName("lastBinName");
         entity.Property(e => e.LastBinUserid)
             .IsRequired()
             .HasMaxLength(50)
             .HasDefaultValue("")
             .HasColumnName("lastBinUserid");
     });

public partial class LastUsedBin
{
    public Guid LastBinId { get; set; }

    public string LastBinName { get; set; }

    public string LastBinUserid { get; set; }
}

---
#### Feedback Bot on 1/26/2024, 02:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
We don't plan to change the default name generation. However, you can used [customized T4 templates](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) to change the name generation for your case if you wish.
