### ISSUE TITLE
Design meeting notes - October 1, 2015

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#3297]
# Table selection in reverse engineering

Right now we have the syntax 

`-t|--tables <filters>`

where `<filters>` looks like `*:table,schema:*,schema1:table1...`

Decided to move to `-t|--table` and `-s|--schema` where both `-t` and `-s` are allowed multiple times. `-s` will represent what was previously `schema:*`, `-t` will be some combination of `schema_name` and `table_name` uniquely identifying a specific table. The list will be just sent to each provider as is and it will be up to the provider to interpret the syntax.

So e.g. for SqlServer it will be:

`-s schema1 -s schema.with.dots ...`

`-t schema1.table1 -t schema2.table2 -t [schema.with.dots].[table.with.dots] ...`

For SQLite there is no concept of schema so it will be:

`-t table1 -t table2 ...`

and any `-s` entries will be ignored.

But note that in PowerShell, the arguments will be `-Tables` and `-Schemas` (plural) which take an array of strings. For example:

`-Schemas schema1 -Tables ('table1', 'table2')`

# Command options naming

We also reviewed a few options that have been added to the commands since [the last review](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes---July-23,-2015#nugetdnx-commands). Here are the notes.

NuGet | DNX
----- | ---
--OutputDir~~ectory~~ | -o, --output~~-path~~Dir
-Context~~ClassName~~ | -c, --context~~-class-name~~
-Tables | -t, --table~~s~~ *(multi-value option)*
~~-FluentApi~~ **-DataAnnotations** | ~~-u, --fluent-api~~ **-a, --dataAnnotations**
**-Schemas** | **-s, --schema** *(multi-value option)*
-StartupProject | -~~s~~**p**, --startupProject

Note: with the `-FluentApi` becoming `-DataAnnotations`, using `DataAnnotation` attributes will become opt-in rather than opt-out that I has been up to now. I.e. by default we will now produce code using the fluent API if you don't specify otherwise. 

# Discussion

Please comment on this issue to provide feedback, ask questions, etc.

**Comment by ErikEJ** [comment]
1: Does this mean that Data Annotations will be opt-in rather than opt-out? (A good thing if so)

2: Should the dnx switch not be: --schemas rather than --schema  ?

**Comment by lajones** [comment]
@ErikEJ Re 1. That is correct.
Re 2. no, we will allow multiple `--schema` (or probably just `-s`) flags on the `dnx` command line each of which will take a single schema. Similarly for `--table`. However for the Powershell command it is `-Schemas` because that takes an array as its argument. See the design meeting notes for details - which I've updated to be more clear.

**Comment by pbozovic** [comment]
What parameter should I pass in command line tool (dnx ef dbcontext scaffold ...) to exclude "sysdiagrams" table ?

**Comment by ErikEJ** [comment]
@pbozovic  Currently, you must pass the names of all the tables you wish to scaffold. Would be nice to have some "filtering" syntax

**Comment by pbozovic** [comment]
That is what I was afraid of :)
Found there is "ExcludeIndicator" in "EntityFramework.Relational.Design/ReverseEngineering/Internal/TableSelectionSetBuilder.cs", but there is no use for it if you must specify what you want to include.
It would make sense that if you specifiy something to exclude, it includes all by default except what you specified as exclusion.

**Comment by lajones** [comment]
Yes. We had exclude in the original design but it was taken out. @rowanmiller maybe we should revisit the decision? But note: you can also just include schemas. So you don't have to individually name all tables - you can just individually name all the schemas you want to include with the `--schema` flag (the syntax is `--schema <your_schema_1> --schema <your_schema_2>` if you want to include multiple schemas).

**Comment by rowanmiller** [comment]
@lajones my understanding was that not specifying anything would just scaffold everything.

**Comment by lajones** [comment]
@rowanmiller That's correct but @pbozovic is saying he would like to say "scaffold everything _except_ sysdiagrams". We currently only have selection by inclusion, not exclusion. That was removed after the Oct 1 meeting.

Perhaps my suggestion above wasn't clear - I was suggesting that if the `sysdiagrams` table is in a different schema (e.g. `sys`) then he could replicate the effect of not including that table by listing out only the _schemas_ which contain the tables in which he is interested - which will be a shorter list than listing every table. Of course if it's in the same schema as the tables in which he is interested then that won't work and he's back to doing what @ErikEJ said i.e. individually listing out each table using the --table.

**Comment by rowanmiller** [comment]
@lajones - ah yeah, that is correct.

**Comment by pbozovic** [comment]
I'm in the process of designing my database and scaffolding it to Entities. Do you think the feature of exclusion will be back someday ? Or I should think about developing my own tool to build the command with listing all tables except few of them ?

**Comment by ErikEJ** [comment]
Why not just senere the extra class for Now? A gui VS tool is planned for later...

**Comment by pbozovic** [comment]
Thanks for all your suggestions and quick answers.
Nice to hear there will also be GUI for this functionnality :)

Also wanted to say I'm having great time playing with the new framework that looks awesome !

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
