### ISSUE TITLE
Query/Test: change query test infra to output SQL whenever we encounter an exception during query execution

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#32984]
Could help with investigating of intermittent test failures like https://github.com/dotnet/efcore/issues/32940

**Comment by roji** [comment]
Yeah, I'd even go further and say that *any* exception coming out of a query should be enough to dump the SQL to the logs... It can't hurt...

**Comment by maumar** [comment]
Might as well, although most other exceptions (i.e. stuff coming from translation phase) won't produce any sql.

**Comment by roji** [comment]
Sure, you're generally right about that; though for example if we have an assertion failure inside AssertQuery (expected rows not the same as actual), it could actually be useful to just have the SQL out there as well (just as an example of a non-DbException where SQL is present).
