### ISSUE TITLE
Entity Framework Core in Visual Studio 2022 Migrations freezes (hangs) during migrations (example Add-Migration) 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32998]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entity-Framework-Core-in-Visual-Studio-2/10570498)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:idk]
exactly same issue as here https://github.com/dotnet/efcore/issues/32693 => the only thing that works is to kill the ef6.exe

---
#### Feedback Bot on 1/25/2024, 06:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by geniodellavittoria** [comment]
Thanks you for your answer... I try to setup a small runnable project to which has the same issue and come back to you.
