### ISSUE TITLE
Add support for [MemberNotNull] for Entity Framework properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32997]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-support-for-MemberNotNull-for-Enti/10484951)._

---
If I enter the following code:

```cs
_event = await dbContext.Events
    .Include(e => e.Description)
    .FirstOrDefaultAsync(e => e.Id == pkEvent);
```

then the compiler knows _event.Description is not null.

But if I do the following:

```cs
public static IQueryable<Event> IncludeAll(this IQueryable<Event> source)
{
    return source
        .Include(e => e.Description)
        .Include(e => e.Tags)
        .Include(e => e.Thumbnail);

_event = await dbContext.Events
    .IncludeAll()
    .FirstOrDefaultAsync(e => e.Id == pkEvent);
}
```

I now get a warning when I use _event.Description. Please extend the ability og `MemberNotNullAttribute` to decorate a method like `IncludeAll()` so it can tell the compiler that it is insuring properties will be populated.

thanks - dave

---
#### Feedback Bot on 10/7/2023, 07:17 AM: 

(private comment, text removed)

**Comment by roji** [comment]
This is a C# language request that has nothing to do with EF Core. You're effectively asking for a way to say to decorate a method's argument/return value, to say that when the method completes, one of its members is non-null. You can open a request for this on https://github.com/dotnet/csharplang, though please do a search first, as I'm sure someone has already requested this.

**Comment by DavidThielen** [comment]
I don't know who's right here but [the VS team moved it over here](https://developercommunity.visualstudio.com/t/Add-support-for-MemberNotNull-for-Enti/10484951?port=1025&fsid=be176287-4fc9-4f78-9d99-067458fdc8c2&ref=native&refTime=1713279880977&refUserId=29555b68-18b1-620c-9e60-83d5391f7934). So you've got two teams pointing at each other.

**Comment by roji** [comment]
@DavidThielen the VS team isn't the same thing as the C# language team (whose repo is https://github.com/dotnet/csharplang). As this issue seems to be a C# language request, it belongs there.
