### ISSUE TITLE
Vulnerable transitive nuget packages

### ISSUE THREAD

**Issue by programmersommer** [dotnet/efcore#33009]
When Microsoft.EntityFrameworkCore.SqlServer is installed into the project, then next vulnerable transitive packages are also added:

![image](https://github.com/dotnet/efcore/assets/12097421/233ae4ad-663c-49e8-a661-691d1b068bba)

The easiest solution would be to install updated versions of the above-mentioned packages to Microsoft.EntityFrameworkCore.SqlServer

**Comment by ErikEJ** [comment]
In progress https://github.com/dotnet/efcore/pull/32838

**Comment by programmersommer** [comment]
Thank you @ErikEJ, please don't forget also about version 7 (for .NET 6.0 support)

**Comment by ErikEJ** [comment]
.NET 7 and EF Core 7 is out of support on May 2024, so unlikely to happen. You can always add an explicit reference yourself.

**Comment by ErikEJ** [comment]
Actually both 6 and 7 were updated to 5.1.4 recently: https://github.com/dotnet/efcore/pulls?q=is%3Apr+is%3Aclosed+sqlclient
