### ISSUE TITLE
Ignored/Removed Indexes are still created in GenerateCreateScript

### ISSUE THREAD

**Issue by TheKrisSodroski** [dotnet/efcore#33007]
## Description
I have a model where I'm trying to explicitly ignore indexes.  Even though the indexes are explicitly ignored by using RemoveIndex on the metadata of the entity, the creation scripts still contain the index.  

I would expect, that if the index is explicitly ignored, then the index would not be included in the creation script. 

## Reproduction 

You can find the reproduction here:

https://github.com/TheKrisSodroski/EFCore8IndexRemoval

## Debug Info

EF Core version:
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: 8.0
Operating system: Windows 11 Pro 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
IDE: Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.3

**Comment by ajcvickers** [comment]
Not for EF team: not a regression from 7 and still repros in main. There is very specific manipulation of the model going on in OnModelCreating which I expect will be un-reliable since it as single pass meaning it can't react to newly discovered types. That being said, the end result is an index in the relational model that doesn't exist in the main model:

```
Model:
  EntityType: ChildClass
    Properties:
      ParentClassID (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      ParentClassName (string) Required Index MaxLength(50)
      SomeIdentifierID (int) Required Index
    Keys:
      ParentClassID PK
    Indexes:
      SomeIdentifierID, ParentClassName Unique

RelationalModel:
  Table: ChildClass
    PK_ChildClass {'ParentClassID'} PrimaryKey
    EntityTypeMappings:
      ChildModel.ChildClass - ChildClass
    Columns:
      ParentClassID (int) NonNullable)
      ParentClassName (nvarchar(50)) NonNullable)
      SomeIdentifierID (int) NonNullable)
    Indexes:
      IX_ChildClass_SomeIdentifierID_ParentClassName {'SomeIdentifierID', 'ParentClassName'} Unique
```

**Comment by ajcvickers** [comment]
We discussed this, and likely this requires the ability to ignore indexes in the model, which is tracked by #7605.

That being said, EF model building is reactive. Iterating over parts of the model while it is being built is not a reliable way of configuring the EF model. See [_Model bulk configuration_](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration) for more information.

**Comment by ajcvickers** [comment]
@TheKrisSodroski See [Drawbacks of the Metadata API](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#drawbacks-of-the-metadata-api).
