### ISSUE TITLE
I found an issue related to parentheses within a query in entity framework

### ISSUE THREAD

**Issue by younes-erraji** [dotnet/efcore#33024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```c#
string test = _wrapper.Missions
          .Query(x => x.Id == missionId &&
              (
                  x.Category == (int)Enums.MissionCategory.MissionRequest &&
                  isExecutive == false &&
                  (
                      (
                          (
                              x.MissionStatus == (int)Enums.MissionStatus.PendingFromManagingDirector ||
                              x.MissionStatus == (int)Enums.MissionStatus.PendingFromHeadOfDepartment ||
                              x.MissionStatus == (int)Enums.MissionStatus.PendingFromUnitHead
                          )
                          && x.MissionApprovals.Any(y => (y.IsApproved == null || y.IsApproved == false)
                                  && (y.SubmittedToId == loggedUser.Id || approvers.Contains(y.SubmittedToId))
                                  && y.ApproverId == null
                                  && (
                                      y.Status == (int)Enums.MissionStatus.PendingFromManagingDirector ||
                                      y.Status == (int)Enums.MissionStatus.PendingFromHeadOfDepartment ||
                                      y.Status == (int)Enums.MissionStatus.PendingFromUnitHead
                                  )
                              )
                      )
                      ||
                      (
                          x.MissionStatus == (int)Enums.MissionStatus.Saved &&
                          (loggedUser.Id == x.CreatorId || x.MissionDelegates.Select(x => x.DelegateId).Contains(loggedUser.Id))
                      )
                  )
              ) || (
                  x.Category == (int)Enums.MissionCategory.MissionNomination &&
                  x.MissionStatus == (int)Enums.MissionStatus.Saved &&
                  x.IsMissionExtension
              )
          ).Include(x => x.MissionDelegates)
          .ToQueryString();
```

when this query is translated it includes the (x.Id == missionId) within the first parentheses

### .NET Version

6

**Comment by roji** [comment]
@younes-erraji we need to see the actual SQL being generated, and ideally a minimal, rnunable code sample (what's the Query() function? It's not part of EF).

**Comment by younes-erraji** [comment]
> This looks like an issue for the [dotnet/efcore](https://github.com/dotnet/efcore) repository.

Thanks for letting me know

**Comment by younes-erraji** [comment]
> @younes-erraji we need to see the actual SQL being generated, and ideally a minimal, rnunable code sample (what's the Query() function? It's not part of EF).

what's the Query() function? No it's not, it's just just a function that pass a condition to the Where Linq Function

**Comment by roji** [comment]
@younes-erraji yeah, we need an actual repro.

**Comment by younes-erraji** [comment]
# Generated SQL

DECLARE @__missionId_0 int = 93411;
DECLARE @__loggedUser_Id_1 int = 20083;
DECLARE @__loggedUser_Id_3 int = 20083;
SELECT [m].[Id], [m].[AdditionalInformation], [m].[Category], [m].[ClientAddress], [m].[ClientName], [m].[SubmitedAt], [m].[RequestedBy], [m].[DepositAmount], [m].[EndDate], [m].[EventName], [m].[EventOrganiser], [m].[EventRoleId], [m].[EventTypeId], [m].[Funding], [m].[HotelText], [m].[IsDelete], [m].[IsDepositHeld], [m].[IsHotel], [m].[IsMissionExtension], [m].[IsOtherExpanses], [m].[IsSubsistence], [m].[IsTicket], [m].[MainId], [m].[MissionReference], [m].[MissionStatus], [m].[Name], [m].[OtherExpanses], [m].[StartDate], [m].[SubsistenceText], [m].[TicketText], [m].[TravelTeamStatus], [m].[Type], [m].[VersionNo], [m2].[Id], [m2].[DelegateId], [m2].[IsLeadOfDelegates], [m2].[MissionId]
FROM [Missions] AS [m]
LEFT JOIN [MissionDelegates] AS [m2] ON [m].[Id] = [m2].[MissionId]
WHERE 
(
  ([m].[Id] = @__missionId_0) AND
  (
    ([m].[Category] = 1) AND
    (
	  (
	    [m].[MissionStatus] IN (4, 3, 2) AND
		EXISTS (
		  SELECT 1
		  FROM [MissionApprovals] AS [m0]
		  WHERE ([m].[Id] = [m0].[MissionId]) AND
		    (
			  (
			    (
				  (([m0].[IsApproved] = CAST(0 AS bit)) OR ([m0].[IsApproved] IS NULL)) AND
				  ([m0].[SubmitedTo] = @__loggedUser_Id_1)
				) AND ([m0].[ApprovalBy] IS NULL)
			  ) AND
			  [m0].[ApprovalStatus] IN (4, 3, 2)
			)
		)
	  ) OR
	  (
	    ([m].[MissionStatus] = 1) AND
		(
		  (@__loggedUser_Id_3 = [m].[RequestedBy]) OR
		  EXISTS (
		    SELECT 1
			FROM [MissionDelegates] AS [m1]
			WHERE ([m].[Id] = [m1].[MissionId]) AND ([m1].[DelegateId] = @__loggedUser_Id_3)
		  )
		)
	  )
	)
  )
)
OR
(
  (
    ([m].[Category] = 2) AND ([m].[MissionStatus] = 1)
  )
  AND
  ([m].[IsMissionExtension] = CAST(1 AS bit))
)
ORDER BY [m].[Id]

## As you all can see the ( ([m].[Id] = @__missionId_0)) Condition is within the first parentheses And within the Query method it is not

**Comment by roji** [comment]
@younes-erraji I can see the following in the SQL:

```sql
WHERE 
(
  ([m].[Id] = @__missionId_0) AND
  (
...
```

Is the complaint here that there are parentheses around the equality check (`([m].[Id] = @__missionId_0)`), where the original LINQ query doesn't have them (`.Query(x => x.Id == missionId &&`)? If so, what's the problem with that - the query should work just fine? Parentheses (or the lack thereof) in your LINQ query aren't meant to translate directly to the same thing in SQL.

**Comment by younes-erraji** [comment]
> @younes-erraji I can see the following in the SQL:
> 
> ```sql
> WHERE 
> (
>   ([m].[Id] = @__missionId_0) AND
>   (
> ...
> ```
> 
> Is the complaint here that there are parentheses around the equality check (`([m].[Id] = @__missionId_0)`), where the original LINQ query doesn't have them (`.Query(x => x.Id == missionId &&`)? If so, what's the problem with that - the query should work just fine? Parentheses (or the lack thereof) in your LINQ query aren't meant to translate directly to the same thing in SQL.

### @roji No it's actually caused me a problem because the condition ([m].[Id] = @__missionId_0) is globally in this query to fetch only one record
### and yet it fetched a lot of missions were fetched

**Comment by roji** [comment]
I'm sorry, I don't understand how that has anything to do with any parentheses. Can you please post which SQL you would expect EF to generate, instead of the above SQL?

**Comment by younes-erraji** [comment]
```SQL
DECLARE @__missionId_0 int = 93411;
DECLARE @__loggedUser_Id_1 int = 20083;
DECLARE @__loggedUser_Id_3 int = 20083;
SELECT [m].[Id], [m].[AdditionalInformation], [m].[Category], [m].[ClientAddress], [m].[ClientName], [m].[SubmitedAt], [m].[RequestedBy], [m].[DepositAmount], [m].[EndDate], [m].[EventName], [m].[EventOrganiser], [m].[EventRoleId], [m].[EventTypeId], [m].[Funding], [m].[HotelText], [m].[IsDelete], [m].[IsDepositHeld], [m].[IsHotel], [m].[IsMissionExtension], [m].[IsOtherExpanses], [m].[IsSubsistence], [m].[IsTicket], [m].[MainId], [m].[MissionReference], [m].[MissionStatus], [m].[Name], [m].[OtherExpanses], [m].[StartDate], [m].[SubsistenceText], [m].[TicketText], [m].[TravelTeamStatus], [m].[Type], [m].[VersionNo], [m2].[Id], [m2].[DelegateId], [m2].[IsLeadOfDelegates], [m2].[MissionId]
FROM [Missions] AS [m]
LEFT JOIN [MissionDelegates] AS [m2] ON [m].[Id] = [m2].[MissionId]
WHERE 
[m].[Id] = @__missionId_0 AND
(
  (
    ...
  )
)
OR
(
  (
    ([m].[Category] = 2) AND ([m].[MissionStatus] = 1)
  )
  AND
  ([m].[IsMissionExtension] = CAST(1 AS bit))
)
ORDER BY [m].[Id]
```

All I need is the condition is to be global in this query
This how it should work

**Comment by roji** [comment]
In this SQL, your `[m].[Id] = @__missionId_0` is still not "global": you effectively have SQL code like `[m].[Id] = @__missionId_0 AND x OR y`; with this SQL, if `y` is true than the whole WHERE is true. I think you want parentheses like the following instead: `[m].[Id] = @__missionId_0 AND (x OR y)` (with parentheses around `x OR y`).

If that's what you want, you need to change your .NET LINQ query code accordingly, to add the parentheses; in other words, this has nothing to do with EF - your query is wrong. Try the following:

```c#
string test = _wrapper.Missions
    .Query(x => x.Id == missionId &&
        ((
            x.Category == (int)Enums.MissionCategory.MissionRequest &&
            isExecutive == false &&
            (
                (
                    (
                        x.MissionStatus == (int)Enums.MissionStatus.PendingFromManagingDirector ||
                        x.MissionStatus == (int)Enums.MissionStatus.PendingFromHeadOfDepartment ||
                        x.MissionStatus == (int)Enums.MissionStatus.PendingFromUnitHead
                    )
                    && x.MissionApprovals.Any(y => (y.IsApproved == null || y.IsApproved == false)
                                                   && (y.SubmittedToId == loggedUser.Id || approvers.Contains(y.SubmittedToId))
                                                   && y.ApproverId == null
                                                   && (
                                                       y.Status == (int)Enums.MissionStatus.PendingFromManagingDirector ||
                                                       y.Status == (int)Enums.MissionStatus.PendingFromHeadOfDepartment ||
                                                       y.Status == (int)Enums.MissionStatus.PendingFromUnitHead
                                                   )
                    )
                )
                ||
                (
                    x.MissionStatus == (int)Enums.MissionStatus.Saved &&
                    (loggedUser.Id == x.CreatorId || x.MissionDelegates.Select(x => x.DelegateId).Contains(loggedUser.Id))
                )
            )
        ) || (
            x.Category == (int)Enums.MissionCategory.MissionNomination &&
            x.MissionStatus == (int)Enums.MissionStatus.Saved &&
            x.IsMissionExtension
        ))
```
