### ISSUE TITLE
Owned type's shadow key size should match that of owner's PK

### ISSUE THREAD

**Issue by lonix1** [dotnet/efcore#33037]
I typically use `long` for keys, which EF translates to `bigint`.

When an entity has an owned type, [EF creates](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities#implicit-keys) a shadow key of cli type `int` and db type `integer`. This is used in a composite key with the owner's PK.

Surely in such a case, EF should generate a key of the same size as that of the owner? A long for a long, or an int for an int.

(Of course one can fine tune the mapping via `HasKey` etc., but you'd need to know of the issue in the first place. One would expect the defaults not to have this surprising result.)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
