### ISSUE TITLE
I need a setting or option to store all the enums as string in database including the enum columns or enums inside the json columns (even if they are at root of the json or multi level in depth due to complexity of json)

### ISSUE THREAD

**Issue by mohammad-farsi-kindred** [dotnet/efcore#33035]
Currently we need to define a Converter for each enum property as attribute on the model or in the onModelCreating method of dbContext.

It can be done manually for each single property or dynamically by investigating all the properties in any json class and add StringToEnum converter for it 

It would be great to have a option for setting here:

```
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.**EnableEnumToString**();
    }

```

**Comment by roji** [comment]
@mohammad-farsi-kindred have you taken a look at the [bulk configuration docs](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration)?
