### ISSUE TITLE
Try EF Core 9 now!

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#33030]
EF Core release notes for each version can be found in the [GitHub Releases page](https://github.com/dotnet/efcore/releases/).

You can try EF 9 before it goes GA using the [daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) or a preview release:

- Release notes for [EF Core 9 preview 1](https://github.com/dotnet/efcore/releases/tag/v9.0.0-preview.1.24081.2)

This issue is for general discussion around the EF Core 9 preview releases. See [_What's New in EF Core 9_](https://learn.microsoft.com//ef/core/what-is-new/ef-core-9.0/whatsnew) for details on new features introduced as the EF9 work progresses.

**Comment by erpardeepkaushik** [comment]
official support for IndexedDB will be superb for offline use case in blazor wasm apps. there are many packages but official one will be amazing.

https://github.com/Jinjinov/IndexedDB.Blazor
https://github.com/Reshiru/Blazor.IndexedDB.Framework

**Comment by sajjadarashhh** [comment]
> official support for IndexedDB will be superb for offline use case in blazor wasm apps. there are many packages but official one will be amazing.
> 
> https://github.com/Jinjinov/IndexedDB.Blazor https://github.com/Reshiru/Blazor.IndexedDB.Framework

that would be very nice if we have them...

**Comment by roji** [comment]
Thank you @tuespetre!!

**Comment by caleblloyd** [comment]
Love these new Migration behaviors!

- https://github.com/dotnet/efcore/issues/33731
- https://github.com/dotnet/efcore/issues/22616

I was just starting to write the usual hackery to achieve this outside the library when, much to my delight, I discovered these.  I'm sure you are already planning on adding it but should definitely mention those in the What's New docs.  And as always, great work!

**Comment by jamo-semler** [comment]
How do we migrate to this new behavior regarding replacement of Discriminator to $type (#34269). 

A updated solution just gets:

"Unable to materialize entity instance of type 'MyType'. No discriminators matched the discriminator value ''."

**Comment by roji** [comment]
@jamo-semler it seems like you're asking how to access existing documents, which were created with earlier versions of EF, and so have a `Discriminator` property instead of `$type. If so, please read [this breaking change note](https://github.com/dotnet/EntityFramework.Docs/pull/4812/files#diff-dea8089998c96b23af90e1c58198c8131174cfd9e90b0fc908029b103193e586R102) (the doc update isn't yet live, but this doc PR already contains the info).

Please let me know if that's clear and resolves things for you!

**Comment by jamo-semler** [comment]
@roji that worked perfectly. 

For others arriving here the fix to revert to pre EF Core 9.0 behavior is to add these to the EntityTypeBuilder:

`modelBuilder.Entity<SomeType>(builder =>
{
    // Revert to pre EF Core 9.0 behavior
    builder.HasDiscriminator<string>("Discriminator");
    builder.HasDiscriminatorInJsonId();
}`
