### ISSUE TITLE
Read Description String Into Generated Xml Comments When Scaffolding MS SQL Database

### ISSUE THREAD

**Issue by rhoadscm** [dotnet/efcore#33051]
When using a database-first approach every time a database is rescaffolded, any changes made to generated code will be overwritten. This includes Xml documentation comments.

MS SQL provides a description property for tables, relationships, and columns. It would be nice to read that property for the put that string into a `/// <summary></summary>` tag comment on the generated class and associated properties and relationships. This would allow a database-first approach to documentation.

**Comment by ErikEJ** [comment]
I think that happens already, actually

**Comment by rhoadscm** [comment]
I was surprised when it did not work. I'm using EF Core 6... maybe just need to update? Any settings I should know about to enable this?

**Comment by ErikEJ** [comment]
I think it is just on by default.  Maybe a CLI Update? Or try EF Core Power Tools?
