### ISSUE TITLE
EF.Property throws exception when used with dynamic property name from a different entity

### ISSUE THREAD

**Issue by AhmedMSedeek** [dotnet/efcore#33078]
EF.Property throws exception when used with dynamic property name from a different entity,

Exception: "The EF.Property method may only be used within Entity Framework LINQ queries"

There're some cases where we cannot read properties directly and we need to use EF.Property instead for example with temporal tables as below:

```C#
var modificationLogs = dbContext.Set<ObjectName>().TemporalAll().AsQueryable();
var query = from modificationLog1 in modificationLogs
            join modificationLog2 in modificationLogs on EF.Property<DateTime>(modificationLog1, "ValidTo") equals EF.Property<DateTime>(modificationLog2, "ValidFrom")
            from property in dbContext.Props
            select new ()
            {
                Date = EF.Property<DateTime>(modificationLog1, "ValidTo").ToString(),                     // this one works correctly,
                Field = property.prop,                        // this one works correctly,
                From = EF.Property<object>(modificationLog1, "Name").ToString(),                     // this one works correctly,
                // From = EF.Property<object>(modificationLog1, property.prop).ToString(),                     // this one "when enabled" does not work and throws the exception
                To = EF.Property<object>(modificationLog2, "Name").ToString()                     // this one works correctly,
            };

var items = await query.ToListAsync();                            // exception thrown here
```

Stack Trace:

```
   at Microsoft.EntityFrameworkCore.EF.Property[TProperty](Object instance, String propertyName)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at SolutionName.ProjectName.Access.<GetAsync>d__6.MoveNext() in E:\SolutionName\ProjectName\ModificationLog\Access.cs:line 162
```

### Include provider and version information

EF Core version:8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system:
IDE: Visual Studio 2022 17.8.6
Note: Reverse engineering "scaffolding" was used to automatically generate the dbcontext

**Comment by roji** [comment]
That's (currently) by design - you can't use EF.Property() to generate fully dynamic SQL in the way that you're trying to; the SQL would need to potentially vary for each query (as a different column name would need to be inserted). EF is generally geared more towards a well-known (static) model, and less towards generating fully dynamic queries (you can always drop down to SQL when doing that).

Note also that the second argument to EF.Property() is a property name as a string; but it seems like `property.prop` in your code sample above is the actual .NET property (i.e. you're getting it's value in `Field = property.prop` just above).

**Comment by AhmedMSedeek** [comment]
Thanks for the reply!

as for your note, yes, the `property.prop` is the "string" property of the entity, so I assumed it will be translated to the actual string value for each record before firing the `EF.Property` function

I understood your explanation, but can we at least keep this issue open in case it gets worked on in the future?

**Comment by roji** [comment]
We'll discuss this in the team meeting and see whether this is something we see ourselves supporting.

**Comment by AhmedMSedeek** [comment]
Thanks a lot.

**Comment by ajcvickers** [comment]
Note that the below code works, so we already generate different SQL queries (polluting the cache) if this is used injudiciously.

```C#
void NewFunction(SomeDbContext someDbContext, string propertyName)
{
    someDbContext.Foos.Where(e => EF.Property<int>(e, propertyName) > 0).ToList();
}
```

**Comment by roji** [comment]
Thanks @ajcvickers, that's a good point - I think I got confused there for a bit.

@AhmedMSedeek what kind of SQL would you expect your query to produce? How can different columns be projected out for different rows in this way?

**Comment by AhmedMSedeek** [comment]
@roji 
What I was thinking of is something like this:
Let's say we have two tables, [Foo] and [Property]
[Foo] Table has three columns: [Id], [Name], [Code]
[Property] table has one column [PropertyName] and has three records: "Id", Name", and "Code"

So what I want to be the end resulting data is of structure: 
Id        | Property Name        | Property Value
=============================
1         | Id                             | 1
1         | Name                      | XYZ
1         | Code                        | AA-1

So, the sql query would be something like this:

```
SELECT
	[Id],
	[Property].[PorpertyName],
	CASE [Property].[PorpertyName] WHEN 'Id' THEN [Foo].[Id] WHEN 'Name' THEN [Foo].[Name] WHEN 'Code' THEN [Foo].[Code] END AS [PropertyValue]
FROM
	[Foo]
	, [Property]
```

I understand this is challenging and might generate ugly and complex queries especially with lots of rows and you might consider it an odd requirement with very edge case, however, just to understand the business need behind it and why we need it, the end intention is not join it with a table that has properties names at all, but with an in-memory list that has the properties names:

please see https://github.com/yv989c/BlazarTech.QueryableValues/issues/46 for details

So, the very end requirement is to use sql temporal tables to generate a more human-friendly modification log for UI display that is dynamic to work with different types of objects

Side Node: BTW, it would be excellent if you can support joining with an in-memory list natively instead of needing a third-party library to do so

**Comment by roji** [comment]
I'm not sure I understand - above, the actual column names (Id, Name, Code) seem to be in the database ([Property] table); how would EF now about them in order to put them in the CASE/WHEN in the SQL? Are you suggesting that EF first query the Property table to retrieve the rows, and then generate the SQL for the actual query based on them? If so, I really don't think that's something we'd consider doing.

> of course a casting would be required for the CASE WHEN column, (string mabe to hold any value?)

Yeah, that doesn't really work - we can't make everything into a string and then parse it client-side. I'm not sure how we'd even know what to parse it as (int? DateTime? Based on what?).

> BTW, it would be excellent if you can support joining with an in-memory list natively instead of needing a third-party library to do so

For primitive collections, we do support that since EF 8.0 - see [this post](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/).

**Comment by AhmedMSedeek** [comment]
Hello @roji 
Thanks for your reply!

> you suggesting that EF first query the Property table to retrieve the rows, and then generate the SQL for the actual query based on them?

I only thought of this because I was thinking about passing the properties list as a parameter and not querying them from the table, but I put the table in the example code because I didn't know primitive collections are supported in dotnet 8.0

> Yeah, that doesn't really work - we can't make everything into a string and then parse it client-side. I'm not sure how we'd even know what to parse it as (int? DateTime? Based on what?).

Yes, the values are of different columns so they are in different datatypes, so this is what I though it would be to cast to a type that can "display" all of their values, note the end list is meant only for display to the users as the history of midifications, I donot want to parse any of the values

> For primitive collections, we do support that since EF 8.0 - see [this post](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/).

Thanks! good to know

Note: Maybe I'm searching for a solution to the wrong problem, but I really want to do is to get the modification log in temporal tables from the database in the structure I mentioned in my previous reply, any idea how to do this in a different way?

**Comment by roji** [comment]
> I only thought of this because I was thinking about passing the properties list as a parameter and not querying them from the table, but I put the table in the example code because I didn't know primitive collections are supported in dotnet 8.0

Even for the parameterized list case, this would mean generating dynamic SQL (different SQLs for the same LINQ query), which is something we try hard to avoid, as it defeats query plan caching and causes other performance issues.

> Yes, the values are of different columns so they are in different datatypes, so this is what I though it would be to cast to a type that can "display" all of their values, note the end list is meant only for display to the users as the history of midifications, I donot want to parse any of the values

EF doesn't work that way - if you're projecting out something, you get it typed, not magically transformed into a string. You may only need it for display purposes, but that's your very narrow, specific scenario; someone else will ask "why can't I get an object and then use reflection to look at the actual differing types and use them etc.".

EF - or rather LINQ - is simply not the right tool for the kind of thing you're trying to do. You can always drop down to SQL to do dynamic SQL queries or whatever else wyou want.

**Comment by AhmedMSedeek** [comment]
Ok, thanks a lot for your time and effort, and just as a side note, I meant casting on SQL level, not EF level, something like `CONVERT(CASE WHEN THEN ..... END, NVARCHAR(MAX))`
