### ISSUE TITLE
Thoughts or ideas around high perf scenarios with EF

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#33070]
**Background**
I dropped this on the bottom of a closed ticket and thought there's enough here it warrants it's own ticket, more so since the other ticket is closed. The other ticket is here: 
   https://github.com/dotnet/efcore/issues/23615

Interesting. I'm sure when it comes to how I use EF i'm probably like many, massively abusing it, but I've found that as a testament to how well written it is sometimes just taking an out of the box approach can improve things.

I found that a lot of my problems went away when I instanced up a new context for literally every single row operation on the db. Pooling helped offset the perf hits but on occasion I would get an error from one context where I had somehow attached it to another.

**Correct me if i'm wrong but**
Tracking what entity is attached to what context is certainly not a fun task.
I think the bulk of this thread comes down to "EF did a strange thing, something unexpected was tracked on an instance"

**Random thought**
The change tracker: do we really need it at all?

Bear with me on this ...
So in my situation I do something like this:

new context -> get an entity -> dispose context right away
modify entity based on some event source containing the change details
instance new context -> attach modified entity to it -> call save changes
With context pooling and pooled factories this seems to be really fast, (like stupid fast)
What does the context give us by having just the one "request scoped" and doing all the work on the one instance that I would lose with this approach?

Another idea I had was to put a thread safety wrapper around a singleton context and just throw out all changes after every transaction with the wrapper but that felt ugly and would likely result in poorer perf since in order to scale i'm using a ton of instances at the moment. but if I could "queue" work to be done on an EF context I could probably make that fairly decent as an approach.

**Side quest**
I noticed that "model caching" / using a single model instance for all contexts doesn't work with query filters.
Is this a resolvable problem, I'd really like to take advantage of those gains?

There's a lot to unpack here so apologies, just query to get experts thoughts on my brain dump.

**Comment by roji** [comment]
The general approach when using EF, your context instance lives for the scope of your "unit of work" (query/modify/SaveChanges loop). There are of course various scenarios where having that state live for the entirety of the UoW isn't appropriate; for example, a disconnected web scenario where data is returned to the client (e.g. over JSON), and at some arbitrary later point an update will be posted from that client. In such a case, keeping a DbContext instance alive at the server side is usually what you want, and you indeed instantiate two DbContexts (one for the reading, one for the writing) similar to how you describe above.

As to *why* a single DbContext for the whole UoW is a good idea... For one thing, EF detects all the changes for you, and persists only those properties which actually changed. When attaching your modified entity to a new context instance, you have to track what changed yourself, and manually tell that to EF if you want the efficient partial update. Note that if the changing set of properties is fixed (you always update the same X properties), then ExecuteUpdate is probably the best way to go indeed.

In addition, things are simple enough when you're dealing with a single entity; but it gets complex fast once you're dealing with a graph of objects: tracking (and configuring!) which entity got added/removed where is far from trivial. Just having DbContext figure it all out takes care of a lot of tricky handling.

Finally, I'm struggling to understand exactly what problem you're trying to solve here. You write the following:

> Tracking what entity is attached to what context is certainly not a fun task.

I don't think we have seen a lot of complaints about this. In a given code context, you typically have a single DbContext, and the entities loaded through it are tracked by that context. Period. If you're using multiple context instances in the same place and moving entities between them, then yes, that could get complicated - but then that's specific to that. Basically a bit more context on exactly what you're finding difficult would help.

> Another idea I had was to put a thread safety wrapper around a singleton context [...]

Why would you do that, given that (with pooling) getting new instances is extremely fast? What in other words, what are you trying to solve here? Having such a global lock seems like it would limit your concurrency in a pretty severe way, and lead to far worse performance issues than whatever you're trying to solve.

> I noticed that "model caching" / using a single model instance for all contexts doesn't work with query filters.

It's certainly supposed to. Please open a separate issue with a minimal, runnable repro of what's not working.
