### ISSUE TITLE
Docker + "The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized" on v8.0.2

### ISSUE THREAD

**Issue by rudacomolaplanta** [dotnet/efcore#33088]
Hi, 

I got a problem with this package today

Looks like installing v8.0.2 will get to the error: 
The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized

When use it to build a docker container using [mcr.microsoft.com/dotnet/sdk:8.0.200] (http://mcr.microsoft.com/dotnet/sdk:8.0.200)

Maybe the reference to the Microsoft.EntityFrameworkCore.Analyzers is causing the problem.

I downgraded to v8.0.1 and there's no trouble.

**Comment by rudacomolaplanta** [comment]
Sure, here it is: 

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b19e336e-c7ad-4155-876b-5f2ba1774934</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
</Project>`

**Comment by ErikEJ** [comment]
Are targeting "windows" ? that could why you get the issue, due to SqlClient 5.1.4 using Azure.Identity 10.3

**Comment by ErikEJ** [comment]
[Tracking issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4468) (it is actually Microsoft.Identity.Client that is the culprit)
