### ISSUE TITLE
Include on multiple Many-to-Many relationships of the same CLR-Type returns empty set when bi-directional relationship is configured

### ISSUE THREAD

**Issue by ymotton** [dotnet/efcore#33081]
## Introduction

Migrating a dotnet framework ef6 codebase to dotnet 8.0.1 with efcore 8.0.2 we noticed some issues with many-to-many relationships.

## Context

Consider following models (described as record types for brevity):
```C#
class Product(Guid Id, string Name, List<Code> Tags, List<Code> Categories);
class Code(Guid Id, string Value, List<Product> Products);
```

The DbContext is configured as follows:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var entity = modelBuilder.Entity<Product>();

        entity
            .HasMany(x => x.Tags)
            // .WithMany() // TODO: Uncomment this to fix
            .WithMany(x => x.Products) // TODO: Comment this out to fix
            .UsingEntity<Dictionary<string, object>>(
                "ProductTags",
                x => x.HasOne<Code>().WithMany().HasForeignKey("Code_Id").OnDelete(DeleteBehavior.NoAction),
                x => x.HasOne<Product>().WithMany().HasForeignKey("Product_Id").OnDelete(DeleteBehavior.NoAction),
                x => x.ToTable("ProductTags")
            );
        
        entity
            .HasMany(x => x.Categories)
            // .WithMany() // TODO: Uncomment this to fix
            .WithMany(x => x.Products)  // TODO: Comment this out to fix
            .UsingEntity<Dictionary<string, object>>(
                "ProductCategories",
                x => x.HasOne<Code>().WithMany().HasForeignKey("Code_Id").OnDelete(DeleteBehavior.NoAction),
                x => x.HasOne<Product>().WithMany().HasForeignKey("Product_Id").OnDelete(DeleteBehavior.NoAction),
                x => x.ToTable("ProductCategories")
            );
    }
```

## The issue

Given auto-creation of the db schema, and having seeded one `Product` record, and two `Code` records, with the product's `Tags` collection containing one `Code` reference, and the `Categories` collection containing the other `Code` reference:

Whenever we retrieve the product, including *both* relationships, it only returns results for one.

```C#
using var context = new MyDbContext();
var product = context.Products
    .Include(x => x.Tags)
    .Include(x => x.Categories)
    .Single();

// Expecting 1, Actual 1
Console.WriteLine(product.Tags.Count);
// Expecting 1, Actual 0
Console.WriteLine(product.Categories.Count);
```

As mentioned above, if we configure the many-to-many relationships to *not* have a `Products` collection on the `Code`-entity, the aforementioned query *does* return the expected relationships.

Github repo link: https://github.com/ymotton/efcore-33081/

## Version info

EF Core version: 7.0.16, 8.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net7.0 (7.0.14), net8.0 (8.0.1)
Operating system: Windows 11
IDE: JetBrains Rider

**Comment by ajcvickers** [comment]
@ymotton EF doesn't support using the same navigation used by two different relationships. That is `Code.Products` cannot be the inverse navigation for both `Product.Tags` and `Product.Categories`. Each relationship should either have its own navigation or no navigation on each side of the relationship.

**Comment by ymotton** [comment]
@ajcvickers Thanks, that does make sense!
An improvement idea: it might be useful to have ModelBuilder guard against invalid/unsupported configurations at startup.

Thanks again!

**Comment by ajcvickers** [comment]
> it might be useful to have ModelBuilder guard against invalid/unsupported configurations at startup.

This is a good point, but in general the `ModelBuilder` is lazy-configuration-wins, since this allows overriding existing configuration  to be overridden in order to customize it in, for example, a derived `DbContext` type.
