### ISSUE TITLE
IPluralizer interface seems to be missing from Microsoft.EntityFrameworkCore.Design Package V 8.0.2

### ISSUE THREAD

**Issue by ian-hamlet** [dotnet/efcore#33094]
## Interface Undefined

Having updated packages from 8.0.1 to 8.0.2 the compiler cannot resolve IPluralizer interface from the Microsoft.EntityFrameworkCore.Design package.

### Part of a class definition

Sample 

```C#
using EntityFrameworkCore.Scaffolding.Handlebars;
using Microsoft.EntityFrameworkCore.Design;
using Bricelam.EntityFrameworkCore.Design;

namespace dotConnected.EF.Pluralizer;

public class EfPluralizer : IPluralizer
{
	private readonly Bricelam.EntityFrameworkCore.Design.Pluralizer _pluralizer;
	private readonly ConfigSettings _configSettings;

	public EfPluralizer(ConfigSettings configSettings) : base()
	{
		_pluralizer = new Bricelam.EntityFrameworkCore.Design.Pluralizer();
		_configSettings = configSettings;
	}
	public string Pluralize(string name)
	{
		return name; // to simplify example
	}

	public string Singularize(string name)
	{
		return name; // to simplify example
	}
}
```

### Include provider and version information

EF Core version: 8.0.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.8.6)

**Comment by ajcvickers** [comment]
@ian-hamlet Please post your csproj file(s).

**Comment by ian-hamlet** [comment]
Current csproj


<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Bricelam.EntityFrameworkCore.Pluralizer" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      
    </PackageReference>
    <PackageReference Include="EntityFrameworkCore.Scaffolding.Handlebars" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\dotConnected.EF.Types\dotConnected.EF.Types.csproj" />
  </ItemGroup>
</Project>



Ian Hamlet

Managing Director

[http://dotconnected.com/images/email/dotted.jpg]

[http://dotconnected.com/images/email/dotConnected-logo.jpg]

{t}

+44 (0)1273 270580<tel:+44%20(0)1273%20270580>

{d}

+44 (0)1903 791553<tel:+44%20(0)1903%20791553>

{m}

07968 135909<tel:07968%20135909>

{w}

dotConnected.com<http://dotconnected.com/>

This email and any attachments may be confidential. If you are not the intended recipient of this email you must not take any action based upon its contents, nor copy, nor show it to anyone. Any views or opinions expressed are solely those of the author and do not necessarily represent those of dotConnected. Please contact the sender if you believe that you have received this email in error.

dotConnected Ltd

Registered Office: Unit 12, Triangle Business Centre, 95 Commerce Way, Lancing, BN15 8UP

Registered in England No. 5239899<tel:5239899> VAT No 837 3569 93<tel:837%203569%2093>





________________________________

**Comment by SkipperRoo** [comment]
From what I can see there seems to be a namespace collision between Microsoft.EntityFrameworkCore.Design (8.0.2) and Microsoft.EntityFrameworkCore (8.0.2) which has the same namespace in both.  The workaround that I've found is by including the package reference in a separate target in the csproj file like so:-

	<Target Name="ChangeAliasOfAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
		<ItemGroup>
			<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
				<PrivateAssets>all</PrivateAssets>
				<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			</PackageReference>
		</ItemGroup>
	</Target>

Hope this helps

**Comment by ErikEJ** [comment]
Just remove the privatassets and includassets parts for the packagareference

**Comment by ian-hamlet** [comment]
Thanks, that worked and we are off running again; but can i naively ask why, this came about from doing a package update in visual studio.

**Comment by ErikEJ** [comment]
That is how the design package is built, snd Nuget rewrites your .csproj on each. Always review all changes to your codebase. (Normally you would not use the design package during runtime)
