### ISSUE TITLE
Perf: Address warm initialization

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#3309]
In the  InitializationTests  our cold start numbers show a solid improvement over EF6 but our warm numbers are slower. There are probably common causes across the set, so opening a general item to investigate these and implement improvements.

**Comment by ajcvickers** [comment]
Marking for re-triage.
![image](https://cloud.githubusercontent.com/assets/1430078/10826200/cb50ccc8-7e25-11e5-8272-b2af058326c9.png)

**Comment by anpete** [comment]
Nice!

**Comment by rowanmiller** [comment]
:+1: :tada:

**Comment by rowanmiller** [comment]
Actual numbers are actually better than the screen shot too :smile:
