### ISSUE TITLE
Error: Script-Migration -Idempotent -Context "MyDbContext" -StartupProject "MyStartupProject" -Project "MyDataProject"

### ISSUE THREAD

**Issue by gorgasparyan** [dotnet/efcore#33113]
Script-Migration : Error HRESULT E_FAIL has been returned from a call to a COM component.
At line:1 char:1
+ Script-Migration -Idempotent -Context "AoaDbContext" -StartupProject  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Script-Migration], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Script-Migration
<img width="299" alt="Screenshot 2024-02-16 165210" src="https://github.com/dotnet/efcore/assets/59490811/0f184239-3bea-4fb9-bda2-35a459b9d38c">

**Comment by mcabrerawellgatetechcom** [comment]
happening with VS 2022 17.9.0

**Comment by JustinJmnz** [comment]
I had to revert to using the dotnet cli ef core tools to generate my script. Does seem like an issue with Visual Studio.

**Comment by gorgasparyan** [comment]
> dotnet cli ef core tools to generate my script

Thanks Justin, I also tried and it did generate the script. Here is the command: `dotnet ef migrations script --idempotent --context "MyDbContext" --startup-project "MyStartupProject" --project "MyDataProject"`

**Comment by carlaguinaldo-TU** [comment]
Same issue on VS 2022 17.9.0

**Comment by phillipmunn** [comment]
This bug also affects VS 2022 17.10 Preview 1.

**Comment by phillipmunn** [comment]
This issue appears to be the same as this one below, which is that .sql files cannot be viewed in Visual Studio. 
I'd use the CLI version above to workaround this for now.

https://developercommunity.visualstudio.com/t/sql-Files-cannot-be-opened/10584835
https://developercommunity.visualstudio.com/t/open-sql-in-visaul-studio-after-upgrade/10584421

**Comment by Mark-Phillipson** [comment]
I'm getting this problem in the latest preview and the normal release of Visual Studio.

**Comment by Dave-Townsend** [comment]
Same issue here as above on latest VS 2022

**Comment by Mark-Phillipson** [comment]
I have found that if you change the application that is used to open an SQL file in Visual Studio, it solves the problem.

**Comment by Danotsonof** [comment]
> I have found that if you change the application that is used to open an SQL file in Visual Studio, it solves the problem.

How can that be done?

**Comment by Danotsonof** [comment]
> > I have found that if you change the application that is used to open an SQL file in Visual Studio, it solves the problem.
> 
> How can that be done?

I found a way to set a default sql viewer by following the accepted answer here: [https://stackoverflow.com/questions/2193083/visual-studio-open-a-sql-file-with-sql-management-studio-in-an-existing-ssms-w](https://stackoverflow.com/questions/2193083/visual-studio-open-a-sql-file-with-sql-management-studio-in-an-existing-ssms-w)

**Comment by tp1045** [comment]
I experienced the same issue, the latest [vs release](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.9.1) mentions a similar Developer Community problem:

[.sql Files cannot be opened](https://developercommunity.visualstudio.com/t/sql-Files-cannot-be-opened/10584835)

I've since updated to VS 17.9.1 and scripting migrations is working again.

**Comment by gorgasparyan** [comment]
Yeah, it works after the latest 17.9.1 update.

**Comment by arashberlin** [comment]
hi there. I do have this issue in 17.12.1 dotnet SDK 9.0.11. 

Build without any issue. Migration created. Only Script-Migration fail only in VS 2022.  CLI "dotnet ef migrations script" can generate sql.


Fails:
Script-Migration -From v030 -To v031 -Project Data -Context DBContext -StartupProject Admin


CLI OK:
dotnet ef migrations script v030 v031 --project Data --context DBContext --startup-project Admin



Is there a way to see any logs what is causing the error?


![Image](https://github.com/user-attachments/assets/4272c1d9-8518-4617-aff9-f612afdbc861)




![Image](https://github.com/user-attachments/assets/a7c500de-fb62-47d7-85a2-bb426534d17d)
