### ISSUE TITLE
EF reduce usage of memory

### ISSUE THREAD

**Issue by Endesapt** [dotnet/efcore#33117]
I have an ASP.NET Web API project and I am using some background service where i update my DB and add new data(~20000 rows) every 8 hours
But even for the first iteration of queries my app is using 400mb of memory(though in DB data it is only ~25mb)
And memory usage keeps increasing after each iteration.

I tried to use GC.Collect() and it caused some effect, but it still consumes 660 mb after 3 calls to DB 
There are photos of memory profiler( red line states for end of one iteration)
**Memory usage without GC**
![Without_GC](https://github.com/dotnet/efcore/assets/103508859/22f8ba73-230c-49ec-9729-34a85cc186f6)

**Memory usage with GC**
![with_GC](https://github.com/dotnet/efcore/assets/103508859/deb5207c-ca05-45e5-8224-c86f6d79bf6d)

I have 2 quesitions:
1. Am i doing something wrong with DbContext so it doesnt  dispose correctly?
2. If not, how can i decrease memory usage in my application

I created test ASP.NET project that shows my problem
[EFMemoryTest](https://github.com/Endesapt/EFMemoryExample)

Database provider: mysql.entityframeworkcore\8.0.0\
Target framework: .NET 8.0
Operating system: Windows 10
IDE:  Visual Studio 2022 17.8.4

**Comment by ajcvickers** [comment]
@AndriySvyryd Can you investigate this?

**Comment by AndriySvyryd** [comment]
I changed the sample to use the SQL Server and after ~30s the memory consumption stabilized at ~86MB. So this seems to be an issue in the `MySql.EntityFrameworkCore` provider, please report it to the owners.

Also, consider trying `Pomelo.EntityFrameworkCore.MySql` instead.
