### ISSUE TITLE
Add IncludeAll Method with Recursion Level for IQueryable

### ISSUE THREAD

**Issue by SaeedMolaiy** [dotnet/efcore#33116]
I would like to propose the addition of an IncludeAll method to the Entity Framework Core library for IQueryable instances, allowing the inclusion of related entities with a specified recursion level. Currently, developers often resort to creating virtual methods, using the Include method for each navigation property, or employing reflection and expressions for a similar scenario. Having a dedicated IncludeAll method would simplify and provide more control over the depth of loading.

**Proposed Method Signature:**
```csharp
public static IQueryable<TEntity> IncludeAll<TEntity>(
    this IQueryable<TEntity> query,
    int recursionLevel = 1) where TEntity : class;
```

**Usage Example:**
```csharp
var result = dbContext.Set<YourEntity>()
    .IncludeAll(recursionLevel: 2)
    .Where(yourCondition)
    .ToList();
```

**Reasoning:**
This feature would enhance the flexibility of working with IQueryable instances in Entity Framework Core. Currently, developers commonly create virtual methods, use the Include method for each navigation property, or resort to reflection and expressions for similar scenarios. The proposed IncludeAll method would simplify these approaches and provide a more concise and expressive way to handle related entities loading with a specified recursion level.

**Relevance to Web APIs:**
Given the prevalent use of Entity Framework Core in web APIs, this feature would be particularly valuable for optimizing data retrieval. Controlling the depth of loading is often crucial for performance in web API scenarios, and the IncludeAll method could provide a more efficient alternative to the current practices.

Please consider this feature request, and I would appreciate any feedback or suggestions on its implementation.
Thank you!

**Comment by roji** [comment]
This seems to me like it would encourage fetching a lot more data than is actually needed, i.e. with developers slapping it on although they don't actually need **all** navigations. In other words, this seems like a pit of failure encouraging inefficient programming practices. I'm specifically not clear on how this API would provide a "more efficient alternative to the current practices".

Also, I'm curious about `recursionLevel`; calling code typically needs specific related entities of entity, based on very specific requirements; it may need one thing that's one level deep, and another that's three - I really don't see  "everything 2 levels related" as something that's needed in the general case - that simply isn't how it works. Can you provide a bit more context and maybe examples on what you have in mind here?
