### ISSUE TITLE
An issue with EF Core Recursive Updates on Unchanged Entities across Different DbContext Instances

### ISSUE THREAD

**Issue by SaeedMolaiy** [dotnet/efcore#33122]
**Scenario Description :**
I encountered a problem while working with Entity Framework. The situation involves reading an entity from dbContext1, disposing of this context, and then attempting to update the entity using dbContext2.

**Issue Reproduction :**
1- Read an entity from dbContext1.
2- Dispose of dbContext1.
3- Update the entity.
4- Create new instance of DbContext 
4- Attempt to save the updated values using dbContext2.

**Expected Behavior:**
I expect Entity Framework Core to recognize whether an entity has actual changes before performing updates. This is crucial, especially considering the potential performance impact of recursively updating relations.

**Actual Behavior:**
Currently, EF recursively updates the relations even when there are no changes to the entity, which can lead to unnecessary updates, particularly for heavy entities with multiple relations.

**Impact:**
The observed behavior can have a significant impact on performance, especially when dealing with entities that include multiple relations, resembling an aggregate root in Domain-Driven Design (DDD).

I suggest exploring improvements in the change tracking mechanism or providing an option to explicitly check for changes before updating entities.

**Code Sample:**
```csharp
// Read entity from dbContext1
var entity = dbContext1.Set<MyEntity>().Find(entityId);

// Dispose of dbContext1
dbContext1.Dispose();

// Update the entity or don't
// Create new instance of DbContext

// Attempt to update using dbContext2
dbContext2.Update(entity);
dbContext2.SaveChanges();

//OR!
dbContext2.Attach(entity);
dbContext2.Entry(entity).State = EntityState.Modified;
```

**Request for Guidance:**
I would appreciate your expertise on whether there is an established best practice or recommended approach within Entity Framework Core to handle the scenario described. Specifically, is there any existing mechanism or configuration that can prevent EF Core from recursively updating relations when there are no actual changes to the entity?

Additionally, if there isn't currently a built-in solution, do you believe it would be beneficial to implement a feature in EF Core to address this use case more efficiently? I'm open to your guidance on the best way to handle this situation.

Thank you for your time and assistance.

**Comment by ajcvickers** [comment]
@SaeedMolaiy Consider reading [the documentation on change tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/).

**Comment by SaeedMolaiy** [comment]
@ajcvickers 
Thank you for directing me to the Entity Framework Core change tracking article. I've carefully reviewed the information, and while it provides valuable insights into entity states and how DbContext instances track changes, it seems that the described behavior doesn't fully address the specific scenario I'm encountering.

In my scenario, when a new DbContext instance is unaware of the entity, manually setting the entity state to "Modified" results in EF updating it even in the absence of any actual changes. Conversely, if I refrain from doing so, the EntityState defaults to "Detached" or "Unchanged," thereby preventing the entity from being updated.

**Comment by ajcvickers** [comment]
@SaeedMolaiy Yes, this is by-design. If you want partial updates, then you'll need to either 

- Transfer original values to and from the client
- Re-query for the entity before updating

This is described in the documentation. There are trade-offs with all three approaches.

**Comment by SaeedMolaiy** [comment]
@ajcvickers Thank you for the clarification. I'm willing to give the recommended approaches a try, although I must admit I have some reservations about these practices.

**Comment by stevendarby** [comment]
@SaeedMolaiy is it not possible to update the entity only after attaching it to the second context? Then EF would track the changes. At the moment the second context only knows about the entity after you've already updated it, so can't tell what has changed.
