### ISSUE TITLE
Debugging With Primary Constructor

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/efcore#33126]
### Description

When There Variables From Primary Constructor Like Injecting DbContext
When Debug And Hover Over DbContext And Breakpoint In Method To Query Somthings
I Hovered Over DbContext And dbContext varibale or parameter value is null

![image](https://github.com/dotnet/runtime/assets/104096256/55c1c47c-0651-4e15-a639-1ff7a6dc9507)

![image](https://github.com/dotnet/runtime/assets/104096256/0a2b8927-4480-4ee5-aee5-44c044947c54)

and This is in Watch

![image](https://github.com/dotnet/runtime/assets/104096256/030ac816-0dea-4da7-8765-e4efd4da22b9)

Try It With Your Self

### Reproduction Steps

...

### Expected behavior

....

### Actual behavior

...

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by wisamidris7** [comment]
Visual Studio Update 17.9 Worked Fine Thanks!
