### ISSUE TITLE
Migrate separate Sqlite in-memory database fails

### ISSUE THREAD

**Issue by jarethgoblinking** [dotnet/efcore#33128]
## Description

I have a test scenario where as part of the arrange step I need to create two separate SQLite in-memory databases and run Migrate() or EnsureCreated() on each of them.

Either command runs correctly on the first database, but after running on the second database, OnModelCreating() is not triggered as expected.

Instead it appears that somehow the second database, which should be separate, effectively starts pointing to the first database.

### Reproduction

A minimal reproduction in the context of a test might look as follows.

```
var connection = new SqliteConnection("Filename=:memory:");
connection.Open();

var builder = new DbContextOptionsBuilder<MyContext>().UseSqlite(connection);

var dbContext = new YowieSpyContext(builder.Options);

var dbContext.Database.Migrate();        //or .EnsureCreated()

var connection2 = new SqliteConnection("Filename=:memory:");
connection2.Open();

var builder2 = new DbContextOptionsBuilder<MyContext>().UseSqlite(connection2);

var dbContext2 = new YowieSpyContext(builder2.Options);

dbContext2.Database.Migrate();      //or .EnsureCreated()
```

### Provider and version information

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.27
xUnit Version : 2.7.0
Target framework: .NET 6.0
Operating system: Win 10
IDE: Visual Studio 2022 17.8

**Comment by ajcvickers** [comment]
@jarethgoblinking By default, the model for a given `DbContext` type is cached, so it is expected that `OnModelCreating` will only be called once here. See [Alternating between multiple models with the same DbContext type](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model).

**Comment by jarethgoblinking** [comment]
@ajcvickers implementing the cache key factory has resolved the problem thank you . 

However I would add that this behaviour feels opaque and unexpected.
