### ISSUE TITLE
Why is Package Manager trying to suggest incompatible updates?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#33135]
In Visual Studio, I opened the Package Manager. It tells me there are a number of updates available. So I selected them and clicked Update.

But this gives me a bunch of errors. Here are a few of them.

```
NU1202: Package Microsoft.EntityFrameworkCore.SqlServer 8.0.2 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Microsoft.EntityFrameworkCore.SqlServer 8.0.2 supports: net8.0 (.NETCoreApp,Version=v8.0)
NU1202: Package Microsoft.EntityFrameworkCore.SqlServer 8.0.2 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Microsoft.EntityFrameworkCore.SqlServer 8.0.2 supports: net8.0 (.NETCoreApp,Version=v8.0)
NU1202: Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 8.0.2 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 8.0.2 supports: net8.0 (.NETCoreApp,Version=v8.0)
```
My solution is using .NET 7.0. So why is Package Manager thinking I need version 8?

Is there no way to make this smart enough to know which updates would actually be applicable to my solution? Because, if not, it them becomes incumbent on me to know which packages are updates I need and which ones I must avoid, and I don't readily have such information!

**Comment by roji** [comment]
@SoftCircuits this doesn't sound like something that's related to EF in any way. Try reporting this to VS, including a full project repro (the report above is very partial and doesn't provide all the required information).

**Comment by SoftCircuits** [comment]
@roji What do you mean? These are all EF packages. I'm trying to understand the update strategy when crossing major versions. And I've seen this many times before. It isn't specific to my current project or solution files.

**Comment by stevendarby** [comment]
https://github.com/NuGet/Home/issues/5725

**Comment by SoftCircuits** [comment]
@stevendarby Thanks!
