### ISSUE TITLE
Triggers Error Entity Framework Core 8

### ISSUE THREAD

**Issue by AspektIntern** [dotnet/efcore#33146]
We have a problem with triggers in EF 8.
We use a model where all tables contain a trigger for Audit Log purposes and we have a problem with creating/updating item.

Is this the only solution to tell all tables containing triggers or other solutions exist?
https://learn.microsoft.com/en-gb/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#sqlserver-tables-with-triggers

**Comment by aleksandar-angelov** [comment]
I have encountered the same problem. Maybe a good solution will be to force entity framework to use the older technique for save changes globally in configuration besides this walkaround suggested by Microsoft?

**Comment by ajcvickers** [comment]
@AspektIntern @AspektIntern The convention shown in the linked doc will make all `SaveChanges` calls behave like before.

**Comment by aleksandar-angelov** [comment]
@ajcvickers What are the downsides of using the convention? Other than that, as mentioned the older technique of SaveChanges has less efficiency, are there any slight disadvantages?

**Comment by ajcvickers** [comment]
@aleksandar-angelov The downside is that `SaveChanges` will likely be slower. But the only way to avoid that is to remove the triggers.

**Comment by Milancho** [comment]
If I comprehend correctly, to establish global usage of triggers is by using ConfigureConventions, BlankTriggerAddingConvention ?

**Comment by roji** [comment]
We really should document the newer UseSqlOutputClause() (https://github.com/dotnet/EntityFramework.Docs/issues/4538)... Though IIRC a manual convention is still needed to do a global opt-out...
