### ISSUE TITLE
Invalid error description when migration is not applied

### ISSUE THREAD

**Issue by wzuo** [dotnet/efcore#3314]
Hi,
when migration is not created/applied ASP.NET MVC vNext throws following error:

> A database operation failed while processing the request.
> 
> AggregateException: Wystąpił przynajmniej jeden błąd. 
> AggregateException: Wystąpił przynajmniej jeden błąd. 
> AggregateException: Wystąpił przynajmniej jeden błąd. 
> AggregateException: Wystąpił przynajmniej jeden błąd. 
> AggregateException: Wystąpił przynajmniej jeden błąd. 
> SqlException: Invalid object name 'Car'. 
> There are pending model changes for ApplicationDbContext
> Scaffold a new migration for these changes and apply them to the database from the command line:
> 
> dnx . ef migration add [migration name] 
> dnx . ef migration apply

This error description is not correct, since the commands have changed to:

> dnx ef migrations add [migration name]
> dnx ef database update

I don't know if this is correct place (it may be ASP.NET MVC issue) to report this typo.

**Comment by bricelam** [comment]
Possibly fixed by https://github.com/aspnet/Diagnostics/pull/181
