### ISSUE TITLE
Error after DNU RESTORE [BUG]

### ISSUE THREAD

**Issue by GVX111** [dotnet/efcore#3315]
MissingMethodException: Method not found: 'Void Microsoft.Data.Entity.Query.Internal.QueryCompilationContextFactory..ctor(Microsoft.Framework.Logging.ILogger`1<Microsoft.Data.Entity.Query.Internal.QueryCompilationContextFactory>, Microsoft.Data.Entity.Query.IEntityQueryModelVisitorFactory, Microsoft.Data.Entity.Query.ExpressionVisitors.IRequiresMaterializationExpressionVisitorFactory, Microsoft.Data.Entity.DbContext)'.

**Comment by davidfowl** [comment]
Thats not enough information to know what the problem is.

**Comment by gvx111** [comment]
IT IS MY project.lock.json
http://m.uploadedit.com/ba3k/144389398484.txt

**Comment by gvx111** [comment]
Url of project:
http://tss.ge/
