### ISSUE TITLE
EF Core power tool is not generating mappings for a table with foreign keys in it from other tables 

### ISSUE THREAD

**Issue by sohaibameenpk007** [dotnet/efcore#33186]
Hello, 

I am using EF Core power tool to generate mappings for a table which have foreign keys from other tables. On generating the entities and context, mapping does not show the relationship of the table with other tables. 

SequenceCommodity is the table and "WorkZoneID,  DestinationDockID" coming from WorkZone, DestinationDocks respectively. Context file does not have mappings for WorkZone, DestinationDocks for SequenceCommodity. 

Am I missing something from the configuration / settings from EF Core power tool? 

Please provide some insights. Thanks 

Best, 
Sohaib

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sohaibameenpk007** [comment]
@ajcvickers 

Please check the images given below. I am sure it will help. 

![image](https://github.com/dotnet/efcore/assets/88434445/328d1e92-a346-456d-bfff-7cf5e46f2ff9)

![image](https://github.com/dotnet/efcore/assets/88434445/8465e040-edb4-4b4e-ba94-adb43749e3ee)

**Comment by ErikEJ** [comment]
@sohaibameenpk007 Please open an issue in the EF Core Power Tools repo, with all required scripts and configuration files in order to reproduce this - screenshots do no count!

**Comment by sohaibameenpk007** [comment]
@ErikEJ I have created a ticket for this 
https://github.com/ErikEJ/EFCorePowerTools/issues/2195
