### ISSUE TITLE
RelationalDbContextOptionsBuilder.CommandTimeout should accept zero as a valid value

### ISSUE THREAD

**Issue by SteSinger** [dotnet/efcore#33196]
We are running into an issue while trying to set an infinite timeout for our dbcontext. 
During startup we are configuring our context with UseSqlServer und setting CommandTimeout on the builder.
`options.UseSqlServer(connectionString, builder => builder.CommandTimeout(0));`

This calls WithCommandTimeout internally and throws an exception for values <= 0.

https://github.com/dotnet/efcore/blob/e9b942badcbe6a24518a1f4953251585e8dad8b7/src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs#L163-L170

The [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.relationaldbcontextoptionsbuilder-2.commandtimeout?view=efcore-8.0#microsoft-entityframeworkcore-infrastructure-relationaldbcontextoptionsbuilder-2-commandtimeout(system-nullable((system-int32)))) lists 0 as a valid value.

Setting the timeout with context.Database.SetCommandTimeout(0) or context.Database.SetCommandTimeout(Timeout.Infinite) works as expected.

Should be a small change. We could create a PR if you'd like.

**Comment by ajcvickers** [comment]
> We could create a PR if you'd like.

That would be great!
