### ISSUE TITLE
EF Core Incorrectly Translates DateTime.UtcNow in Queries to NOW() Instead of UTC Equivalent

### ISSUE THREAD

**Issue by HaikAsatryan** [dotnet/efcore#33195]
**Description:**
EF Core translates `DateTime.UtcNow` in LINQ queries to `NOW()` in SQL, which does not account for the UTC context and can lead to incorrect data retrieval based on time. The correct behavior should be to use the UTC equivalent in SQL to ensure time comparisons are accurate and consistent with the application's context.

**Steps to Reproduce:**
1. Use a LINQ query that includes a where clause comparing a DateTime field to `DateTime.UtcNow`, for example: `_dbContext.Tokens.Where(x => x.ExpirationDate >= DateTime.UtcNow).ToList();`
2. Observe the generated SQL query.
3. The SQL query uses `NOW()` instead of a UTC equivalent, leading to potential discrepancies in data retrieval based on time.

**Temporary Workaround:**
Currently, the workaround involves assigning `DateTime.UtcNow` to a variable and using it in the query, which correctly retains the UTC context.

**Expected Behavior:**
EF Core should translate `DateTime.UtcNow` to the appropriate UTC time function in SQL, ensuring accurate time-based queries.

**Actual Behavior:**
`DateTime.UtcNow` is translated to `NOW()`, disregarding the UTC context.

**Environment:**
- EF Core version: [8.0.1]
- Database provider: [npgsql 8.0.1]
- Target framework: [.NET 8.0]
- Operating system: [Windows 11]
- IDE: [Rider]

**Comment by roji** [comment]
> EF Core translates DateTime.UtcNow in LINQ queries to NOW() in SQL, which does not account for the UTC context [...]

That's not true as far as I know; the PostgreSQL `NOW()` function returns a `timestamp with time zone`, which represents a UTC timestamp.

Consider the following code:

```c#
context.Blogs.Add(new Blog { Name = "foo" });
await context.SaveChangesAsync();

var now = DateTime.UtcNow;
var dbNow = await context.Blogs.Select(_ => DateTime.UtcNow).SingleAsync();

Console.WriteLine($"Local DateTime.UtcNow: {now} (Kind={now.Kind})");
// Prinmts: Local DateTime.UtcNow: 2/29/2024 8:26:11 AM (Kind=Utc)
Console.WriteLine($"NOW() from database: {dbNow} (Kind={dbNow.Kind})");
// Prints: NOW() from database: 2/29/2024 8:26:11 AM (Kind=Utc)
```

As you can see, the DateTime returned from the database corresponds exactly to the DateTime returned when DateTime.UtcNow is evaluated locally.

I suspect you have some other issue with your code; if you can put together a minimal, runnable repro I can try helping out. However, note that this is a PostgreSQL-specific issue, so it belongs in https://github.com/npgsql/efcore.pg. I'll go ahead and close this here - but if you're still having trouble please open an issue in that repo with the necessary details.
