### ISSUE TITLE
The specified deps.json [D:\MyProject\MAUI\QA\QA.Client\bin\Debug\net8.0-maccatalyst\maccatalyst-x64\QA.Client.deps.json] does not exist

### ISSUE THREAD

**Issue by QGG886** [dotnet/efcore#33203]
PS D:\MyProject\MAUI\QA\QA.Client> dotnet ef migrations add Init
Build started...
Build succeeded.
The specified deps.json [D:\MyProject\MAUI\QA\QA.Client\bin\Debug\net8.0-maccatalyst\maccatalyst-x64\QA.Client.deps.json] does not exist

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by QGG886** [comment]
namespace mauiefcore
{
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });
            builder.Services.AddDbContext<MyDbContext>(options =>
                options.UseSqlite("Data Source=app.db"));
            return builder.Build();
        }
    }

    public class MyDbContext(DbContextOptions<MyDbContext> options) : DbContext(options)
    {
        public DbSet<A> As { get; set; }
    }

    public record A(int Id = 0, string Name = "");
}
The above code is executed in the console， dotnet ef migrations add Init  have error, don't creat migrations folders

PS D:\MyProject\Demos\mauiefcore> dotnet ef migrations add Init
Build started...
Build succeeded.
The specified deps.json [D:\MyProject\Demos\mauiefcore\bin\Debug\net8.0-android\mauiefcore.deps.json] does not exist

**Comment by ajcvickers** [comment]
Note for team triage: I can't get any MAUI project to work on my machine.

**Comment by Reverse0001** [comment]
How come this not be fixed yet? This exact issue can be traced back to 2019 or earlier

**Comment by QGG886** [comment]
> Note for team triage: I can't get any MAUI project to work on my machine.

Can you provide a solution or temporary solution？

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/16386

**Comment by jinge1936** [comment]
Not sure why don't fix this issue, it's really annoying
