### ISSUE TITLE
Why does migration need singleton lifetime when AddDbContext and AddHostedService exist in ConfigurationServices?

### ISSUE THREAD

**Issue by suugbut** [dotnet/efcore#33219]
When **both** `AddDbContext()` **and** `AddHostedService` exist in `ConfigurationServices()`, the migration will
- fail if the lifetime is set to the default value of  `Scoped` but
- succeed if the lifetime is set to `Singleton`.

When `AddDbContext()`  alone exists (without `AddHostedService()`) in `ConfigurationServices()`, the migration always succeeds no matter which lifetime is activated (any of `Scoped`, `Transient` and `Singleton` works).

I am wondering why migration needs singleton lifetime when both exist.

The following code illustrates the problem.

```cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = Host
    .CreateDefaultBuilder()
    .ConfigureServices(services =>
    {
        string type = "migration"; // set to other for non-migration!
        ServiceLifetime sl = type == "migration" ? ServiceLifetime.Singleton : ServiceLifetime.Scoped;
        services.AddDbContext<AppDbContext>(b => b.UseSqlite("DataSource=Blogs.db"), sl);
        services.AddHostedService<Application>();
    });

await host.Build().RunAsync();

class Application(AppDbContext context) : IHostedService
{
    public async Task StartAsync(CancellationToken token)
    {
        context.Blogs.Add(new Blog { Contents = "Hello World" });
        await context.SaveChangesAsync(token);

        Console.WriteLine(context.Blogs.First().Contents);
    }

    public Task StopAsync(CancellationToken token) => Task.CompletedTask;
}
public class Blog
{
    public int Id { get; set; }
    public string Contents { get; set; } = null!;
}
public class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
    public DbSet<Blog> Blogs { get; set; }
}
```

**Comment by stevendarby** [comment]
Hosted services are singletons, you can't inject a scoped service into a singleton. You can inject the service provider and create a scope within the hosted service. 

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0
