### ISSUE TITLE
How to include children on another children condition

### ISSUE THREAD

**Issue by StepLama** [dotnet/efcore#33217]
I have an SQL Query i try to translate in EFCore 8.02

```
SELECT * FROM History H
	LEFT JOIN Hardware HW 
		ON H.HadwareId= HW.Id
	LEFT JOIN Message M
		ON M.Id= H.MessageId AND M.Priority = H.Priority AND M.Group = HW.Group
```

I have 3 objects History, Hardware and Message

I have defined 2 navigations into History

```

public virtual Hardware? Hardware{ get; set; }
public List<Message>? Message { get; set; }

builder.HasOne(history => history.Hardware).WithMany().HasPrincipalKey(hw => hw.Id).HasForeignKey(h => h.HardwareId);
builder.HasMany(history => history.Message).WithOne().HasPrincipalKey(h=> new {Id = h.MessageId, h.Priority}).HasForeignKey(am => new {m.Id, m.Priority});

```

`History.Include(h=>h.Hardware).Include(h=>h.Message)`

compose the following SQL correctly : 
```
SELECT * FROM History H
	LEFT JOIN Hardware HW 
		ON H.HadwareId= HW.Id
	LEFT JOIN Message M
		ON M.Id= H.MessageId AND M.Priority = H.Priority 

```
how can i make it compose the last AND 

` AND M.Group = HW.Group?`

i try to add 
`builder.HasMany(history => history.Message).WithOne().HasPrincipalKey(h=> new {Id = h.MessageId, h.Priority, h.Hardware.Group}).HasForeignKey(m=> new {m.Id, m.Priority, m.Group});`

i try too
`History.Include(h=>h.Hardware).Include(h=>h.Message.Where(m => m.Group == h.Hardware.Group)`

Both cannot be translated.

Any idea someone?

Thank You
Stéphane

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by StepLama** [comment]
you have a small demo, with a migration for creating the BD and sql file for filling it with data and the last SELECT is what i dlike to reproduce.

I'm just asking if there is a way to do this or not :)

Thank you
[ConsoleApp.zip](https://github.com/dotnet/efcore/files/14465086/ConsoleApp.zip)

**Comment by maumar** [comment]
@StepLama you can build the query manually, using LINQ:

```cs
            var query = from h in ctx.History
                        join hw in ctx.Hardware on h.HardwareId equals hw.Id into grouping1
                        from hw in grouping1.DefaultIfEmpty()
                        join m in ctx.Message on new { h.Number, h.Priority, hw.Group } equals new { m.Number, m.Priority, m.Group } into grouping2
                        from m in grouping2.DefaultIfEmpty()
                        select new { h, hw, m };
```

this produces the following sql:

```sql
SELECT [h].[Id], [h].[HardwareId], [h].[Number], [h].[Priority], [h0].[Id], [h0].[Group], [m].[Id], [m].[Group], [m].[Number], [m].[Priority], [m].[Text]
FROM [History] AS [h]
LEFT JOIN [Hardware] AS [h0] ON [h].[HardwareId] = [h0].[Id]
LEFT JOIN [Message] AS [m] ON [h].[Number] = [m].[Number] AND [h].[Priority] = [m].[Priority] AND ([h0].[Group] = [m].[Group] OR ([h0].[Group] IS NULL AND [m].[Group] IS NULL))
```

Note that the Group join condition also matches nulls (likely bug/oversight on our part). If you don't want to match them, you can simply filter out Messages whose Group is null (`join m in ctx.Message.Where(x => x.Group != null)`)

For tracking query you can rely on state manager to give you the navigation structure that you want, just note that projected results will be duplicated (since you manually joined), so might want to do distinct on the client afterwards


```cs
            var result = await query.ToListAsync();
            var final = result.Select(x => x.h).Distinct().ToList();

```

if you want no tracking query, you will have to bucket results yourself, something like this perhaps:

```cs
            var result = await query.AsNoTracking().ToListAsync();

            var buckets = result.GroupBy(x => x.h.Id, (k, g) => new
            {
                History = g.Select(x => x.h).DistinctBy(x => x.Id),
                Hardware = g.Select(x => x.hw).DistinctBy(x => x.Id).Single(),
                Messages = g.Select(x => x.m).ToList()
            }).ToList();
```

**Comment by StepLama** [comment]
@maumar 
Thank you verry much for the answer.
I have find a way to do it with your examples.

So, if i understand well, it is not possible to do it with the navigation mapping?  it will give me a liste like this : new { h, hw, m }
in place of having a list of h with hw and m properties.

**Comment by maumar** [comment]
@StepLama there is no way to do it with EF built-in navigations, as far as I can tell. Those only reason about the principal and dependent end of the navigation, can't add a third, unrelated entity to the mix.

**Comment by StepLama** [comment]
Ok thank you all for the answer!
