### ISSUE TITLE
DbEntityValidationException - not finding this in Microsoft.Data.Entity

### ISSUE THREAD

**Issue by rhires** [dotnet/efcore#3322]
Transferring a few things to EF7 from EF6, and it doesn't work. Just getting errors about not finding the assembly reference, for both dnx451 and dnxcore50. Running against beta 7 on Mac OS X w/ Yosemite. I'm not sure where DbEntityValidationException would be, if not in Microsoft.Data.Entity. 

```
 catch (DbEntityValidationException e)
        {
            var newException = new FormattedDbEntityValidationException(e);
            throw newException;
        }
```

What am I missing?

**Comment by divega** [comment]
EF7 does not perform automatic data validation so the `DbEtityValidationException` class does not exist in EF7. This article is a good read to understand the differences between EF6 and EF7:

http://blogs.msdn.com/b/adonet/archive/2014/10/27/ef7-v1-or-v7.aspx

**Comment by rhires** [comment]
Thank you. I did see that article, but it doesn't seem to say anything about the validation, and neither did I see what is included in the new version vs what is left out, just that a lot of things are, without it being very specific. I did some other searching around, and didn't see much. Maybe it's just not written in the docs yet?

As a relatively new developer, I wonder how to do the validation instead...does it not belong in this layer? And if there is a better forum for asking these kinds of questions, please let me know (besides stackoverflow - I'm familiar with that one! :-) . I don't want to clutter up what is essentially for development with newbie-ish kinds of questions.

**Comment by divega** [comment]
Thanks for the feedback. We have created a documentation bug to track the need to be more explicit about EF6 features that are not included in EF7: aspnet/EntityFramework.Docs#40.

If you are in an MVC application the best choice is to use MVC support for model validation. Documentation for ASP.NET 5 [isn't there yet](http://docs.asp.net/projects/mvc/en/latest/models/validation.html) but in general I would expect [the same patterns from MVC5](http://www.asp.net/mvc/overview/getting-started/introduction/adding-validation) to work. 

Outside MVC applications you will have to add code to control when validation will happen, but there are several options out there that you can build on, e.g. the [Validation Application Block](https://msdn.microsoft.com/en-us/library/dn440720(v=pandp.60).aspx).

**Comment by StrangeWill** [comment]
@divega it appears the validation application block *only* applies to data annotations and not constraints applied by FluentAPI (at least it isn't catching anything for me on a code-first database that is getting SQL exceptions due to truncated data).
