### ISSUE TITLE
WindowsAppSDKSelfContained set to true Gives Build Error

### ISSUE THREAD

**Issue by DJRM2021** [dotnet/efcore#33227]
Adding **`<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`** makes the build process copy all of Windows App SDK to the project package including WebView2, which in turn, generates a file conflict issue with EF Core's reference to WebView2.

`<Project Sdk="Microsoft.NET.Sdk">`
`  <PropertyGroup>`
`    <OutputType>WinExe</OutputType>`
`    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>`
`    <TargetPlatformMinVersion>10.0.22621.0</TargetPlatformMinVersion>`
`    <RootNamespace>Schoolr</RootNamespace>`
`    <ApplicationManifest>app.manifest</ApplicationManifest>`
`    <Platforms>x86;x64;ARM64</Platforms>`
`    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>`
`    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>`
`    <UseWinUI>true</UseWinUI>`
`    <EnableMsixTooling>true</EnableMsixTooling>`
`    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>`
`    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>`
**`    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`**
`    <ImplicitUsings>enable</ImplicitUsings>`
`</PropertyGroup>`
`<ItemGroup>`
`   <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />`
`   <PackageReference Include="CommunityToolkit.WinUI.Controls.CameraPreview" Version="8.0.240109" />`
`   <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.0.240109" />`
`   <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0-preview.1.24081.2">`
`     <PrivateAssets>all</PrivateAssets>`
`     <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>`
`   </PackageReference>`
`   <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0-preview.1.24081.2" />`
`   <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0-preview.1.24081.2">`
`     <PrivateAssets>all</PrivateAssets>`
`     <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>`
`   </PackageReference>`
`   <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.49-beta">`
`     <PrivateAssets>all</PrivateAssets>`
`     <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->`
`   </PackageReference>`
`   <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240227000" />`
`   <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26031-preview" />`
`   <Manifest Include="$(ApplicationManifest)" />`
`</ItemGroup>`
![image](https://github.com/dotnet/efcore/assets/77593544/8a263c11-81ee-4968-886f-87c53d5148a0)

Why does EF Core transitively reference WebView2?

EF Core version: 9.0.0-preview.1.24081.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net 8
Operating system: 22H2
IDE: VS 17.9.2

**Comment by ErikEJ** [comment]
@DJRM2021 You are hit by this https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4468 via SqlClient
