### ISSUE TITLE
Does DbContext correctly persist inherited properties from a parent class in another project?

### ISSUE THREAD

**Issue by BJToor** [dotnet/efcore#33234]
Unfortunately I won't be able to paste in any associated code snippets directly so I'll try to layout the scenario causing the behaviour in-question.

(Using C# - EF Core 6 - Cosmos DB) There are 3 classes: EntityBase, EntityA and EntityB

**Additional context**

- Both EntityA and EntityB inherit from EntityBase
- Entities A and B are both configured in their respective DbContexts referencing the properties on those entities (nothing is explicitly configured for the inherited fields from EntityBase)

The behaviour seems to come down to where EntityBase is relative to entities inheriting from it.

**Project Scenarios**

(Solution 1) EntityBase is in the same project as EntityA (as well as the DbContext) --> EF _automatically_ persists inherited EntityBase fields when saving EntityA without any explicit configuration
e.g.,

Project 1a
- EntityBase
- EntityA
- DbContext

(Solution 2) EntityBase is in a different project than EntityB (DbContext is in another project as well) --> EF _does not_ persist inherited EntityBase fields when saving EntityB
e.g.,

Project 2a
- EntityA

Project 2b
- EntityBase

Project 2c
- DbContext

Is there any particular reason why in solution 1 it works without issue but in solution 2, it doesn't persist the EntityBase fields as part of EntityB (i.e., is this expected behaviour for EF)?

**Comment by roji** [comment]
@BJToor where the class lives (i.e. in which project) shouldn't have any impact on anything EF does.

I understand you can't copy-paste code from your real project, but is it possible to post a minimal console program showing the problem rather than a textual description?

**Comment by BJToor** [comment]
Hope this helps. I have the following locally connected to Azure Cosmos DB Emulator:

**Solution: EFInheritanceTest**

**Project:** EntityBaseLibrary

_EntityBase.cs_
```
namespace EntityBaseLibrary
{
    public class EntityBase
    {
         public string Id;
         public int SchemaVersion = 1;
        
         public EntityBase()
         {
              Id = Guid.NewGuid().ToString();
         }
    }
}
```

**Project:** EntityLibrary

_EntityA.cs_
```
using EntityBaseLibrary;

namespace EntityLibrary
{
    public class EntityA
    {
         public string PropertyA { get; set; } = "PropertyA";
         public string PartitionKey { get; set; }
        
         public EntityA()
         {
              PartitionKey = "EntityA";
         }
    }
}
```

**Project:** EFInheritanceTest

_Program.cs_
```
using EntityLibrary;
using Microsoft.EntityFrameworkCore;

namespace EFInheritanceTest
{
    public class CosmosDbContext : DbContext
    {
         public DbSet<EntityA> EntityAs { get; set; }
        
         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
         {
             optionsBuilder.UseCosmos(
                  "cosmos_db_uri",
                  "cosmos_db_key",
                  "cosmos_db_database_name"
             );
         }

         protected override void OnModelCreating(ModelBuilder modelBuilder)
         {
             modelBuilder.Entity<EntityA>().ToContainer("EntityAContainer");

             modelBuilder.Entity<EntityA>(
                 entity => 
                     {
                          entity.HasPartitionKey(e => e.PartitionKey);
                          entity.HasKey(e => e.Id);
                          entity.Property(e => e.PropertyA);
                     });
         }
    }

    class Program
    {
        static async Task Main(string[] args)
        {
             using (var context = new CosmosDbContext())
             {
                  var entityA = new EntityA { PropertyA = "value" };
                  context.EntityAs.Add(entityA);
                  await context.SaveChangesAsync();  
             }
        }
    }
}
```

Based on what I understand about EF, this should persist the EntityBase fields automatically (e.g., `SchemaVersion`) when saving `entityA` but it doesn't.

**Comment by ricksu978** [comment]
>  public class EntityA
>  {
>  }

@BJToor 
Did you forget to inherit `EntityBase`? or is this intended?

**Comment by BJToor** [comment]
Accidentally left that out when transferring in the code. It's intended that it inherits from EntityBase and that's what is in the code I've been running. Updated my last reply to reflect that.

**Comment by ajcvickers** [comment]
@BJToor These are fields, not properties:

```C#
         public string Id;
         public int SchemaVersion = 1;
```

EF can map directly to fields, but doesn't do so by convention. You'll need to either make this properties, or map the fields explicitly.

**Comment by BJToor** [comment]
> @BJToor These are fields, not properties:
> 
> ```cs
>          public string Id;
>          public int SchemaVersion = 1;
> ```
> 
> EF can map directly to fields, but doesn't do so by convention. You'll need to either make this properties, or map the fields explicitly.

So that was the discrepancy. Thank you, closing the issue.
