### ISSUE TITLE
How to have only One Column for ForeignKey in one-to-one relation with two entity to one TPH entity

### ISSUE THREAD

**Issue by motsan69** [dotnet/efcore#33257]
Hello everybody. I have a problem with this need : 
I have 2 entities : Company and Person
Each on theses entities have a optional one-to-one relation with an Entity : Address.
Address is based on TPH pattern. So address is base class, and CompanyAddress and PersonAddress are derived class.
My goal is to have to have only one Column in Address Entity to store the foreign key from Company or Person Entity.

All of my attemp result are an ef core error message : 

- "The dependent side could not be determined for the one-to-one relationship between..."
- "The foreign key must be defined on a type that is part of the relationship"

, or an Address table with two fields (one for each foreignKey to Company and Person Table).

I think I'm wrong, but I didn't find the solution. 
Here my code, with comments and some attemps...

Please help needed...

```C#
public class EntityBase  {
    [Key]
    public int ID { get; set; } = 0;
    ...
}
    
public abstract class Address : EntityBase {
    // Primary key in baseClass
    public string? Address1 { get; set; } = string.Empty;
    ...
    // try to have a common Foreignkey in base class : without success
    //public int? FKID { get; set; }
}

public class PersonAddress : Address {
    // Dependant between Person and PersonAddress
    // Optional one to one relation : foreign key
    public int? PersonID { get; set; }
    
    // try to have a common column for FK to both Person and Company : without success
    //[ForeignKey("PersonID")]
    //public int? FKID { get; set; }

    // Optional one to one relation : Reference Navigtion to Person
    public Person? Person { get; set; }
    #endregion
}

public class CompanyAddress : Address {
    // Dependant between Person and PersonAddress
    // Optional one to one relation : foreign key
    public int? CompanyID { get; set; }
    
    // try to have a common column for FK to both Person and Company : without success
    //[ForeignKey("CompanyID")]
    //public int? FKID { get; set; }

    // Optional one to one relation : Reference Navigtion to Company
    public Company? Company { get; set; }
    #endregion
}

public class Company : EntityBase {
    // Primary key in baseClass
    // Principal between Company and CompanyAddress
    public string Name { get; set; } = string.Empty;
    ...
    // Optional One to One relation :  Reference Navigtion to CompanuAddress
    public CompanyAddress? Address { get; set;}
}

public class Person : EntityBase {
    // Primary key in baseClass
    // Principal between Person and PersonAddress
    
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    ...
    // Optional One to One relation : Reference Navigtion to PersonAddress
    public PersonAddress? Address { get; set; }
}

public class MyContext : DbContext {

    protected override void OnModelCreating(ModelBuilder modelBuilder) {
        // Address Configuration
        // Discriminator field in base class
        modelBuilder.Entity<Address>().HasDiscriminator<AddressCategory>("AddressType")
            // May be mandatory
            //.HasValue<Address>(AddressCategory.None)
            .HasValue<PersonAddress>(AddressCategory.Person)
            .HasValue<CompanyAddress>(AddressCategory.Company);

        // first derived Class : CompanyAddress Configuration
        // Try to force column name : without Success
        // don't work because CompanyID is nullable, and property want non nullable
        //modelBuilder.Entity<CompanyAddress>().Property(p => p.CompanyID).HasColumnName("FKID");
        //modelBuilder.Entity<CompanyAddress>().Property(p => p.FKID).HasColumnName("FKID");

        // Optional one-to-one relation
        modelBuilder.Entity<CompanyAddress>()
            .HasOne(o => o.Company)
            .WithOne(x => x.Address)
            .HasForeignKey<CompanyAddress>(ca => ca.CompanyID);
            // try to have common FK : without success
           //.HasForeignKey<CompanyAddress>(ca => ca.FKID);


        // Second derived Class
        // PersonAddress Configuration
        // Try to force column name : without Success
        // don't work because PersonID is nullable, and property want non nullable
        //modelBuilder.Entity<PersonAddress>().Property(p => p.PersonID).HasColumnName("FKID");
        //modelBuilder.Entity<PersonAddress>().Property(p => p.FKID).HasColumnName("FKID");

        // Optional one-to-one relation
        modelBuilder.Entity<PersonAddress>()
            .HasOne(o => o.Person)
            .WithOne(x => x.Address)
            .HasForeignKey<PersonAddress>(ca => ca.PersonID);
            // try to have common FK : without success
            //.HasForeignKey<PersonAddress>(ca => ca.FKID);

        base.OnModelCreating(modelBuilder);
    }

    //entities
    public DbSet<PersonAddress> PersonAddress {
        get; set;
    }
    public DbSet<CompanyAddress> CompanyAddress {
        get; set;
    }

    public DbSet<Company> Company {
        get; set;
    }
    public DbSet<Person> Person {
        get; set;
    }
}
```

**Comment by motsan69** [comment]
I'm sorry, I missed some informations : I use Visual Studio pro 2022 + Ef core 6

**Comment by cincuranet** [comment]
Having only one foreign key column is probably going to give you more trouble than benefits. For example, with one column, you cannot have a real foreign key constraint in the database.

Also one might argue that you now have dependency between columns (i.e. if _discriminant_ column is "Company", then the FK column has ID for company) and hence violating basic normalization rules. Then if you're going to do some joining, you're going to have to add extra condition.

Maybe if you share what are you trying to do and why, we can come up with other solution.

**Comment by motsan69** [comment]
Hello @cincuranet , many thanks for your answer. At first, sorry for my long post.

If I correctly understood the uses of Ef Core and the TPH model: the advantage of using the TPH model is that the discriminant is "hidden" by the use of derived classes. Therefore, the use of an additional criterion in joins should not be done. But I could be wrong because I am not an expert in these technologies.

That said, and even if I realize that this violates the normalization rules, I find it quite ugly to have 2 different columns to manage 2 foreign keys which cannot be confused due to the discriminant via the TPH model. So my goal is to have a single column.

Finally, today I manage 2 types of addresses (via an enum type), but my roadmap dev plans to manage several categories of addresses, so as many columns as categories to make foreign keys and this is not possible .

**Comment by cincuranet** [comment]
> If I correctly understood the uses of Ef Core and the TPH model: the advantage of using the TPH model is that the discriminant is "hidden" by the use of derived classes. Therefore, the use of an additional criterion in joins should not be done. But I could be wrong because I am not an expert in these technologies.

Although the discriminator column is hidden in your EF model and EF manages it for you, the underlying database operations would/will still have to take it into account.

> That said, and even if I realize that this violates the normalization rules, I find it quite ugly to have 2 different columns to manage 2 foreign keys which cannot be confused due to the discriminant via the TPH model. So my goal is to have a single column.

Well, has the "ugly" some practical implication? Because i.e. not having the FK constraint has and it is something to seriously consider.

Similarly to the discriminator column is the two FK columns - all managed for you by EF.

> Finally, today I manage 2 types of addresses (via an enum type), but my roadmap dev plans to manage several categories of addresses, so as many columns as categories to make foreign keys and this is not possible .

I think this is excellent thing to think about. Do you want the flexibility of enums (from database POV) or rigidity of columns (and indices, constraints, ...)? Because now, by modelling through separate objects, you have the rigidity in objects, yet you're trying to have flexibility in DB.

---

That said, if you really want to do it and you know what you're doing, you can do something like this (based on your example).

```csharp
public abstract class EntityBase
{
    public int Id { get; set; } = 0;
}

public abstract class Address : EntityBase
{
    public string? Address1 { get; set; } = string.Empty;
    public int ForeignKey { get; set; }
}

public class PersonAddress : Address
{
    [ForeignKey(nameof(ForeignKey))]
    public Person Person { get; set; } = null!;
}

public class CompanyAddress : Address
{
    [ForeignKey(nameof(ForeignKey))]
    public Company Company { get; set; } = null!;
}

public class Company : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public CompanyAddress? Address { get; set; }
}

public class Person : EntityBase
{
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public PersonAddress? Address { get; set; }
}

public class MyContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<Address>().HasDiscriminator<string>("AddressType")
            .HasValue<PersonAddress>("Person")
            .HasValue<CompanyAddress>("Company");
    }

    public DbSet<PersonAddress> PersonAddress { get; set; }
    public DbSet<CompanyAddress> CompanyAddress { get; set; }
    public DbSet<Company> Company { get; set; }
    public DbSet<Person> Person { get; set; }
}
```

Finally you'd delete/remove the FK constraints from migrations/scripts.

**Comment by motsan69** [comment]
Hello, your solution seems to be pretty, I have carried out similar solution, without succes.
I applied the solution you proposed. I have an error message when inserting data, and now it's obvious : when inserting company and its address, there is a FK_Address_Patient violation...
My DB design is not the good solution. Will search for another way 

Many thanks for your help.

**Comment by motsan69** [comment]
Hello, many thanks for your solution. It's work.
However, I must make several clarifications: 

- EF Core generated script create an Index on ForeignKey, so, it's not possible to have Personaddress.ID =1 and CompanyAddress.ID = 1 => deleted index
- deleted 2 FK constraints and 1 Index, just to have some "nice and beauty" database... shortly, the benefit/risk is not obvious...

anyway, big thanks for help and explanations.
