### ISSUE TITLE
Running on kubernetes: Cannot load library libgssapi_krb5.so.2 Error: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Ryaden** [dotnet/efcore#33271]
I just wanted to throw this out here.

We already fixed the issue, but it was an adventure to figuring out what was wrong because the error in our k8s pod was very strange...

We had an issue with our aspnet web api running in kubernetes where we had a mismatch in the appsettings connectionstring value.

In our startup.cs the expected connectionstring value was the `ActualDatabaseName`

``` C#
services.AddDbContext<AnyDbContext>(options =>
{
    options.UseSqlServer(this.Configuration.GetSection("ConnectionStrings").GetValue<string>("ActualDatabaseName"));
});
```

But in our appsettings, we mistakenly configured the incorrect value `Database`, resulting in a mismatch of names.
(It should've been "ActualDatabaseName", instead of "Database")

``` json
{
...
"Database": "Server=any db;Initial Catalog=db;MultipleActiveResultSets=True;"
...
}
```

When testing this locally, I nicely receive an `InvalidOperationException`:
```
System.InvalidOperationException: The ConnectionString property has not been initialized.
```

But when this was deployed to our cluster, we saw the following in the pod logs:
```
Cannot load library libgssapi_krb5.so.2
Error: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
```

A very interesting error which took us a while to see that the UseSqlServer was filled with a `null` value on this line:
```
options.UseSqlServer(this.Configuration.GetSection("ConnectionStrings").GetValue<string>("ActualDatabaseName"));
```

EF Core version: 8.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET8.0
Operating system: ubuntu 22.04
docker image: mcr.microsoft.com/dotnet/aspnet:8.0

**Comment by roji** [comment]
@Ryaden this doesn't look related to EF in any way - if this happens when doing UseSqlServer(null), it should be reproducible without EF by simply using SqlClient and setting the connection string to null; if that's the case, then this would be a SqlClient issue rather than an EF issue, and should be reported to them.

**Comment by Ryaden** [comment]
After further investigation the issue was not related to a NULL value of the connectionstring. 

It was due to a cascading usage of the appsettings file where the "appsettings.json" file used integrated security, which is why the application was trying to use kerberos to connect.

Anyhow, thanks for your explanation and looking into it!

**Comment by batje** [comment]
If you find this, what might help, is to add this to your connectionstring:

```
GSS Encryption Mode=Disable
```

**Comment by lbdavidkrammer** [comment]
We also ran into this and turned GSS Enryption mode off in the connection string, as we're not using it. That fixed it.
See the "Note" Box in the npgsql docs: https://www.npgsql.org/doc/security.html#gss-session-encryption-gss-api

**Comment by roji** [comment]
Note that this warning will be going away soon, https://github.com/dotnet/runtime/issues/126251.
