### ISSUE TITLE
Async operations get stuck on large fields of database type image

### ISSUE THREAD

**Issue by taipignas** [dotnet/efcore#33293]
We have a database table where we store files. I know its not the best approach but we have it and we dont plan to change it in the near future.
In this table theres a field with type image where we write our byte[] data.
I cannot get the data with async operations such as FirstOrDefaultAsync, ToListAsync, etc. But using regular operations such as FirstOrDefault works without issues.
The issue appears only with larger files, lets say 120MB.

EF Core version:
Database provider: 7 to 8.0.2
Target framework: .NET 7 and .NET 8
Operating system: Windows 10

**Comment by roji** [comment]
Assuming you're using SQL Server, that sounds like https://github.com/dotnet/SqlClient/issues/593.
