### ISSUE TITLE
HasDefaultValueSql is ignored in GenerateCreateScript call for cross-schema table relations

### ISSUE THREAD

**Issue by aleksvujic** [dotnet/efcore#33309]
# Overview

We are using .NET 8, [Microsoft.EntityFrameworkCore 8.0.3](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/8.0.3) and [Npgsql.EntityFrameworkCore.PostgreSQL 8.0.2](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/8.0.2). Our backend database is PostgreSQL v12.

We have 2 database schemas, each represented by its own `DbContext` - `IdentityDbContext` (for `identity` database schema) and `NewsDbContext` (for `news` database schema). There is a **cross-schema** FK relationship between `news.article.creator_id -> identity.app_user.id`.

`AppUser.Cdate` column value has a default value and is configured as `entity.Property(e => e.Cdate).HasDefaultValueSql("now()")`.

## `identity` schema
`IdentityDbContext.cs`
```cs
public partial class IdentityDbContext : DbContext
{
    public IdentityDbContext(DbContextOptions<IdentityDbContext> options)
        : base(options)
    {

    }

    public virtual DbSet<AppUser> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_pkey");

            entity.Property(e => e.Cdate).HasDefaultValueSql("now()");
        });
    }
}
```

`AppUser.cs`
```cs
[Table("user", Schema = "identity")]
public class AppUser
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("surname")]
    public string Surname { get; set; }

    [Column("cdate")]
    public DateTime Cdate { get; set; }

    [NotMapped]
    public virtual ICollection<Article> ArticleCreator { get; set; }
}
```

## `news` schema
`NewsDbContext.cs`
```cs
public partial class NewsDbContext : DbContext
{
    public NewsDbContext(DbContextOptions<NewsDbContext> options)
        : base(options)
    {

    }

    public virtual DbSet<Article> Articles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("article_pkey");
        });
    }
}
```

`Article.cs`
```cs
[Table("article", Schema = "news")]
public partial class Article
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("creator_id")]
    public int CreatorId { get; set; }

    [ForeignKey(nameof(CreatorId))]
    [InverseProperty(nameof(AppUser.ArticleCreator))]
    public virtual AppUser Creator { get; set; }
}
```

# Problem description
In our unit tests, we want to create an empty database based on the C# models. For this purpose, we use [`RelationalDatabaseCreator.GenerateCreateScript`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.relationaldatabasecreator.generatecreatescript?view=efcore-8.0#microsoft-entityframeworkcore-storage-relationaldatabasecreator-generatecreatescript) method.

We observed an interesting behavior when calling `GenerateCreateScript` on both `IdentityDbContext` and `NewsDbContext`. A script for creating `ident.app_user.cdate` column (the one with `HasDefaultValueSql("now()")`) differs. If `GenerateCreateScript` is called upon `IdentityDbContext`, it contains a default SQL value `now()`. However, if it is called upon `NewsDbContext`, it doesn't contain a default value.

## IdentityDbContext
```cs
_identityDbContext.GetService<IRelationalDatabaseCreator>().GenerateCreateScript()
```
Output:
```sql
CREATE TABLE identity."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    surname text NOT NULL,
    cdate timestamp with time zone NOT NULL DEFAULT (now()), -- it contains a default value
    CONSTRAINT user_pkey PRIMARY KEY (id)
);
```

## NewsDbContext
```cs
_newsDbContext.GetService<IRelationalDatabaseCreator>().GenerateCreateScript()
```
Output:
```sql
CREATE TABLE identity."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    surname text NOT NULL,
    cdate timestamp with time zone NOT NULL, -- it doesn't contain a default value
    CONSTRAINT "PK_user" PRIMARY KEY (id)
);
```

Note the difference in how `cdate` column is defined. Why does the difference occur? It looks as though `NewsDbContext` doesn't read `HasDefaultValueSql("now()")` from `IdentityDbContext` when generating SQL script for creating `identity.user` table. Moreover, constraint for `identity.user.id` primary key has a wrong name if generated from `NewsDbContext`. It is `PK_user`, but should be `user_pkey`.

I am attaching a [standalone example](https://github.com/dotnet/efcore/files/14588105/HasDefaultValueSql.zip) where you can reproduce the issue. Just download, uznip, run web project and observe the HTML output difference.

**Comment by maumar** [comment]
when calling `GenerateCreateScript` from `NewsDbContext` we don't know about configuration added in `IdentityDbContext`, so `AppUser` is just a regular object with whatever is defined using attributes. That's why there is no defaultvaluesql and the name of PK is the default one rather than the custom `user_pkey`. You need to add custom configuration in both places. You can use `IEntityTypeConfiguration` to reduce the duplication - https://learn.microsoft.com/en-us/ef/core/modeling/#grouping-configuration
