### ISSUE TITLE
ERROR log with event ID 20205 is raised when committing large transaction asynchronously

### ISSUE THREAD

**Issue by mu88** [dotnet/efcore#33319]
## Ask a question

When committing a transaction with many changes asynchronously, the following error is logged:

```
level=ERROR eventId=20205
eventName=Microsoft.EntityFrameworkCore.Database.Transaction.TransactionError
message="An error occurred using a transaction."
```

However, no exception is thrown and all changes are persisted correctly.

When committing the transaction synchronously, no such error is logged.

I also stumbled over [this question](https://stackoverflow.com/questions/66958867/entity-framework-core-error-transaction-20205) on StackOverflow which just guided me in the right direction of converting my asynchronous to synchronous code.

### Include your code

<details>

<summary>Code I wish to use</summary>

```C#
public async Task Foo(IDbContextFactory<MyDbContext> factory, ILogger logger)
{
    var context = factory.CreateDbContext();
    
    context.Database.CreateExecutionStrategy();
    await strategy.ExecuteAsync(async () => 
    {
        using IDbContextTransaction transaction = await context.Database.BeginTransactionAsync();
        
        // Do a lot of changes
        // ...
        
        await context.SaveChangesAsync();
        await transaction.CommitAsync();
    });
}
```

</details>

<details>

<summary>Code additional error handling</summary>

When adding a dedicated `try/catch`, no exception is thrown, `"I was here!"` is not logged, but the log event `20205` gets logged:

```C#
public async Task Foo(IDbContextFactory<MyDbContext> factory, ILogger logger)
{
    var context = factory.CreateDbContext();
    
    context.Database.CreateExecutionStrategy();
    await strategy.ExecuteAsync(async () => 
    {
        using IDbContextTransaction transaction = await context.Database.BeginTransactionAsync();
        
        // Do a lot of changes
        // ...
        
        try
        {
            await context.SaveChangesAsync();
            await transaction.CommitAsync();
        }
        catch (Exception)
        {
            logger.LogError("I was here!");
            throw;
        }        
    });
}
```

</details>

<details>

<summary>Synchronous code as workaround</summary>

My current workaround is to both save and commit synchronously:

```C#
public async Task Foo(IDbContextFactory<MyDbContext> factory, ILogger logger)
{
    var context = factory.CreateDbContext();
    
    context.Database.CreateExecutionStrategy();
    await strategy.ExecuteAsync(async () => 
    {
        using IDbContextTransaction transaction = context.Database.BeginTransaction();
        
        // Do a lot of changes
        // ...
        
        context.SaveChanges();
        transaction.Commit();
    });
}
```

</details>

</details>

### Include stack traces

Unfortunately, there is no stack trace because no exception is thrown.

### Include verbose output

```
Using project 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj'.
Using startup project 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj'.
Writing 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\obj\MyCompany.MyApp.Service.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\MyUser\AppData\Local\Temp\tmp5chq3h.tmp /verbosity:quiet /nologo C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj
Writing 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\obj\MyCompany.MyApp.Service.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\MyUser\AppData\Local\Temp\tmpj3tm2x.tmp /verbosity:quiet /nologo C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj
Build started...
dotnet build C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj /verbosity:quiet /nologo /p:PublishAot=false

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.15
Build succeeded.
dotnet exec --depsfile C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\bin\Debug\net7.0\MyCompany.MyApp.Service.deps.json --additionalprobingpath C:\Users\MyUser\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\bin\Debug\net7.0\MyCompany.MyApp.Service.runtimeconfig.json C:\Users\MyUser\.dotnet\tools\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\tools\netcoreapp2.0\any\ef.dll dbcontext list --assembly C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\bin\Debug\net7.0\MyCompany.MyApp.Service.dll --project C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj --startup-assembly C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\bin\Debug\net7.0\MyCompany.MyApp.Service.dll --startup-project C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\MyCompany.MyApp.Service.csproj --project-dir C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\ --root-namespace MyCompany.MyApp.Service --language C# --framework net7.0 --nullable --working-dir C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service --verbose
Using assembly 'MyCompany.MyApp.Service'.
Using startup assembly 'MyCompany.MyApp.Service'.
Using application base 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\bin\Debug\net7.0'.
Using working directory 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service'.
Using root namespace 'MyCompany.MyApp.Service'.
Using project directory 'C:\work\Bitbucket\MyOrg\my-app\src\MyCompany.MyApp.Service\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'MyCompany.MyApp.Service'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'DeliveryPlanDbContext'.
Finding DbContext classes in the project...
MyCompany.MyApp.Core.Persistence.DeliveryPlanDbContext
```

### Include provider and version information

EF Core version: 7.0
Database provider: `Npgsql.EntityFrameworkCore.PostgreSQL`
Target framework: .NET 7.0
Operating system: Alpine Linux
IDE: not relevant as it happens on production

**Comment by roji** [comment]
@mu88 you definitely should **not** be converting async code to sync - if anything, the other way around.

To be able to help you out, we need a minimal, runnable code sample. Can you please put together a console program that demonstrates the async path failing?

**Comment by roji** [comment]
I'm not sure... Can you can at least reliably repro this on your production? A good start would be to get the full exception details and stack trace (including inner exceptions) for the transaction failure.

**Comment by mu88** [comment]
Yes, reproducing the issue on production is not an issue 😅 as soon as I enable the async code (I've introduced a feature flag) and process 1000 records, it fails immediately.

> A good start would be to get the full exception details and stack trace (including inner exceptions) for the transaction failure

I agree. However, as already mentioned in the code section _Code additional error handling_, neither `SaveChangesAsync` nor `CommitAsync` throws an exception (or at least doesn't propagate it up to my `catch` block).

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
