### ISSUE TITLE
`00000000000005_Migration5` in `MigrationsInfrastructureTestBase` assumes that `int Bar` is `string Bar`

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#33331]
See https://github.com/dotnet/efcore/pull/32788#discussion_r1526453884 for context.

I suggest to either change the type of `Bar` from `int` to `string` before applying `Migration5`, or change `' '` to an `int` value in the `INSERT` statement.

This issue also concerns `Migration6` and `Migration7`.

**Comment by ChrisJollyAU** [comment]
Is this going to be backported to 8.0?

**Comment by roji** [comment]
@ChrisJollyAU this is a test-only fix, why would it need backporting?

**Comment by ChrisJollyAU** [comment]
maybe backporting wasn't the right word. But is this test-only fix going to be added to the 8.0 series? Both myself and @lauxjpn picked this up when updating from 8.0.2 to 8.0.3. #33404 looks like its only merged into main (9.0 series). The relevant tests will still fail in 8.0

**Comment by roji** [comment]
We pretty rarely cherry-pick/backport test fixes to released branches - only when there's a good reason; for example, when backporting/cherry-picking an actual bugfix, we also take the tests verifying that fix along. But in this case, this seems like a test-only fix (no actual bug) - given that you'll see everything working well in your main branch, it seems like keeping the tests skipped on 8.0 is OK, no?
