### ISSUE TITLE
Column that follows a JSON Path

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#33341]
I have a bunch of JSON api results that I want to store in a database. 

In my table, I want certain properties to always follow values in my json object this way I have direct, indexable access to certain json properties. 

Does EFCore have a way to do this automatically or do I have to roll my own solution?

**Comment by roji** [comment]
@TonyValenti I think you're looking for [computed columns](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns); e.g. for SQL Server you can define a computed column with the `JSON_VALUE()` function following a path in another column that contains JSON data.

**Comment by TonyValenti** [comment]
This is almost exactly what I want, except this is SQL server specific. 

Is there an overload that I can provide a func/expression that will allow me to tell EFCore "whenever adding/updating this object, recompute the value of this property with this C# expression"?

**Comment by roji** [comment]
> Is there an overload that I can provide a func/expression that will allow me to tell EFCore "whenever adding/updating this object, recompute the value of this property with this C# expression"?

No, there's nothing like that (tracked by #11001). However, you can easily check for the database provider being targeted (SQL Server vs. PG or whatever) and vary the computed column SQL definition.
