### ISSUE TITLE
Plans on bumping `Microsoft.Data.SqlClient` v2.1.7 dependency

### ISSUE THREAD

**Issue by deepchoudhery** [dotnet/efcore#33347]
The dependency chain is '[EFCore.SqlServer.csproj](https://github.com/dotnet/efcore/blob/ee2617e5bce336e2e637a827275cdb4541770add/src/EFCore.SqlServer/EFCore.SqlServer.csproj#L23)' --> Microsoft.Data.SqlClient (2.1.7) --> System.Configuration.ConfigurationManager (4.7.0) --> System.Security.Permissions (4.7.0) --> System.Windows.Extensions (4.7.0) --> System.Drawing.Common (4.7.0, vulnerable dep). 

Are there any plans on bump this dependency version for the next servicing??

**Comment by AndriySvyryd** [comment]
The vulnarability in `System.Drawing.Common` 4.7.0 doesn't have an attack vector through `Microsoft.EntityFrameworkCore.SqlServer` or `Microsoft.Data.SqlClient`. Therefore, the dependency update is not needed at this time.

**Comment by deepchoudhery** [comment]
Sounds good, thank you for looking into this!
