### ISSUE TITLE
was EntityTypeAttributeConventionBase removed in v. 8 ?

### ISSUE THREAD

**Issue by omuleanu** [dotnet/efcore#33345]
I'm getting this error: 

> Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Conventions.EntityTypeAttributeConventionBase'

when using EF 8 with `MongoDB.EntityFrameworkCore` Version="7.0.0-preview.1"

using EF 7 solves this issue

**Comment by ajcvickers** [comment]
@omuleanu Generally database providers are tied to the major version of EF Core that they were built against. You won't be able to use the Mongo provider with EF 8 until that provider releases a EF8 version.
