### ISSUE TITLE
Is EF Core dead like EF6 (classic) or why is there no plan for EF9 four months after the release of EF8?

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/efcore#33364]
Is EF Core dead like EF6 (classic) or why is there no plan for EF9 four months after the release of EF8?
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/plan

**Comment by ajcvickers** [comment]
As far as I am aware, we don't have a signed off plan to share yet. @SamMonoRT may know more.

**Comment by SamMonoRT** [comment]
@MarcoLoetscher  - no EF Core is not dead and we have been working on features to support NativeAOT and also CosmosDB. We'll publish a plan on the main page in the next few weeks, but you are welcome to browse through the issues in the 9.0 milestone. That list is evolving and issues can be moved in/out as per resourcing.
