### ISSUE TITLE
value converter: can we access other entity properties/columns while reading from db and converting to model

### ISSUE THREAD

**Issue by mhDuke** [dotnet/efcore#33370]
hello ef people. hope you guys are wonderful. in short, I have an entity with two `Money` properties (value objects), that's `Currency`, `Amount` x 2 which translates to 4 columns in database table. I want to cut them down to 3 columns, where currency is shared between two amounts.

```
class Order {
  Money TotalAmount { get; }
  Money DiscountAmount { get; }
}
class Money {
  string Currency { get; }
  decimal Amount { get; }
}
```
I thought I can have `TotalAmount` as complex property, and use value conversion with `DiscountAmount`, where I can access the currency column to complete the conversion. is this possible?

EF Core version: 8

**Comment by ajcvickers** [comment]
This is not something we currently support, and I think it's unlikely we will add support for this in the future. It's not a mapping strategy that we commonly see.

**Comment by lucahost** [comment]
> This is not something we currently support, and I think it's unlikely we will add support for this in the future. It's not a mapping strategy that we commonly see.

What would the mapping strategy look like that you would propose to convert nested properties of a ComplexProperty?
I recently found myself in the same situation.
Is this something were one would still use a OwnsOne instead?
