### ISSUE TITLE
Using static methods in compiled query issue

### ISSUE THREAD

**Issue by mmateevadeltek** [dotnet/efcore#33395]
I have a scenario in which I am using the same compiled query for tracking and no tracking purposes. I understand that the compiled query can only be used in **one mode** and it will be determined at the compilation time. So that means if I still want to use compiled query, I need to have different query for tracking and no tracking. That is also fine, if I am able to reuse somehow the code. Can you help me understand why in the given example below, I can run query1, but query2 fails with this error:

System.InvalidOperationException: 'The LINQ expression 'CompiledQueriesTests.FilterById(
    query: DbSet<TaskData>(), 
    id: __id)
    .Select(x => x)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.

```
[Fact]
public async TTask CompiledQuery_Tracking()
{
	// Arrange
	var scope = CreateScope();
	using var dbContext = CreateDbContext(scope);

	var id = Guid.NewGuid();
	var query = s_query1(dbContext, id);
	var dtos = await query.ToArrayAsync();

	query = s_query2(dbContext, id);
	dtos = await query.ToArrayAsync();
}

private static IQueryable<TaskData> QueryBody(EstimatorDatabaseContext context, bool tracking)
{
	if (tracking)
		return context.TaskSet.AsTracking();

	return context.TaskSet.AsNoTracking();
}

private static Expression<Func<TaskData, TaskData>> s_selector =>
	x => x;

private static IQueryable<TaskData> FilterById(IQueryable<TaskData> query, Guid id)
	=> query.Where(t => t.Id == id);

private readonly static Func<EstimatorDatabaseContext, Guid, IAsyncEnumerable<TaskData>> s_query1 =
Compiler.CompileAsyncQuery((EstimatorDatabaseContext context, Guid id) =>
	QueryBody(context, true)
	.Where(t => t.Id == id)
	.Select(s_selector));

private readonly static Func<EstimatorDatabaseContext, Guid, IAsyncEnumerable<TaskData>> s_query2 =
Compiler.CompileAsyncQuery((EstimatorDatabaseContext context, Guid id) =>
	FilterById(QueryBody(context, true), id)
	.Select(s_selector));
```

Or if you have another idea how can I achieve that? Or if you think it is a bad idea to use compiled queries in this scenario, let me know why. Thanks!

**Comment by roji** [comment]
@mmateevadeltek sorry for taking so long to answer this.

EF.CompileQueryAsync accepts an expression tree, so the FilterById method invoked inside gets passed to EF itself; EF doesn't invoke your queryable-returning methods (e.g. QueryBody) - its job is to translate them to SQL, which it cannot do for these functions.

Instead of trying to call a function within the lambda you pass to CompileQuery, write a function that will return the entire expression tree, as follows:

```c#
Expression<Func<BlogContext, List<Blog>>> BuildFunc(bool tracking)
    => ctx => ctx.Blogs
        .AsTracking(tracking ? QueryTrackingBehavior.TrackAll : QueryTrackingBehavior.NoTracking)
        .ToList();
```

You can then call this function, passing its return value to CompileQuery:

```c#
var query = EF.CompileQuery(BuildFunc(tracking: true));
```
