### ISSUE TITLE
Are Indexes working for .net 8?

### ISSUE THREAD

**Issue by janusqa** [dotnet/efcore#33396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After reading this page
https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations

and trying it out 
```
  [Index(nameof(DepartmentNumber), IsUnique = true)]
```
I get the following errors
'Index' is not an attribute class
The type or namespace name 'IsUnique' could not be found (are you missing a using directive or an assembly reference?)

### Expected Behavior

Should work as described at https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations ?

### Exceptions (if any)

'Index' is not an attribute class
The type or namespace name 'IsUnique' could not be found (are you missing a using directive or an assembly reference?)

### .NET Version

8.0.202

### Anything else?

```
.NET SDK:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.a7f084b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.202/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  8.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

**Comment by roji** [comment]
The [`[Index]`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.indexattribute?view=efcore-7.0) attribute is in the Microsoft.EntityFramework.Abstractions package, make sure you're referencing it.

If you're still running into trouble, please post a minimal, runnable project that shows the problem.

**Comment by janusqa** [comment]
I had transferred the models out to it's own project and did not put the correct assembly (it was already in the main project) ```Microsoft.EntityFrameworkCore.Abstractions``` there.  I will now quietly disappear into the good night.
Thanks guys.
