### ISSUE TITLE
Reference navigations for required relationships should be nullable 

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#33401]
When using reverse engineering to generate a model from a database, the reference navigation for required  relationships should be nullable , because if not eager loaded, it is an null object.

**Comment by roji** [comment]
That is not the way this is designed; making required navigations nullable would force all C# access to them use the bang operator (!) when using eager loading, even though it is known that there can be no null there. On the other hand, it's a programmer error to access the navigation without having loaded it first, so there's no value in annotating the navigation as property.

Please read [these docs](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#required-navigation-properties) for more on this. I'm going to close this as by-design, but if you have further insights to share, don't hesitate to post back here.

**Comment by roji** [comment]
We haven't seen confusion in this area - I'll keep an eye on it, if we see people getting confused by this we can definitely add a link.
