### ISSUE TITLE
Can't reference EntityFramework.Commands in ASP.net MVC 5 app with 7.0.0-rc1-15886

### ISSUE THREAD

**Issue by htuomola** [dotnet/efcore#3340]
Hi, I just updated to 7.0.0-rc1-15886 and trying to add migration with `add-migration foo` gave the error message: "Cannot execute this command because EntityFramework.Commands is not installed in the startup project 'UserInterfaces.Web'."

I guess this is some new constraint as I don't believe it was in place previously - EF.Commands was referenced by the project where the migrations are.

This alone isn't of course a blocker as normally I should be able to add that reference. However, my app is an ASP.net MVC 5.2.3 app and as such requires Razor v. ≥ 3.2.3 && < 3.3.0 but EntityFramework.Commands (more specifically EntityFramework.Relational.Design) wants to install Razor ≥ 4.0.0-rc1-15715.

Is this expected or some packaging issue? I suppose I can add a dummy project with Razor v4 in it but that's hardly ideal.

Nuget log:

Attempting to resolve dependencies for package 'EntityFramework.Commands.7.0.0-rc1-15886' with DependencyBehavior 'Lowest'
install-Package : Unable to find a version of 'Microsoft.AspNet.Razor' that is compatible with 'EntityFramework.Relational.Design 7.0.0-rc1-15886 constraint: Microsoft.AspNet.Razor (≥ 4.0.0-rc1-15715)', 'Microsoft.AspNet.Mvc 5.2.3 constraint: Microsoft.AspNet.Razor (≥ 3.2.3 && < 3.3.0)', 'Microsoft.AspNet.WebPages 3.2.3 constraint: Microsoft.AspNet.Razor (≥ 3.2.3 && < 3.3.0)'.

```
```

**Comment by bricelam** [comment]
Oh yuck; we should remove our dependency on Razor (Issue #2947) soon. I hadn't realized it would conflict with MVC 5 and newer.

You may be able to work around this by setting the project with your migrations as the VS startUp project (or by using the `-StartupProject` parameter) when running the commands.

**Comment by htuomola** [comment]
Yup, I created an empty console app, added Commands reference there and use it as startup project, works fine for now. 

----- Alkuperäinen viesti -----
Lähettäjä: "Brice Lambson" <notifications@github.com>
Lähetetty: ‎6.‎10.‎2015 19:52
Vastaanottaja: "aspnet/EntityFramework" <EntityFramework@noreply.github.com>
Kopio: "Henri Tuomola" <htuomola@gmail.com>
Aihe: Re: [EntityFramework] Can't reference EntityFramework.Commands inASP.net MVC 5 app with 7.0.0-rc1-15886 (#3340)

Oh yuck; we should remove our dependency on Razor (Issue #2947) soon. I hadn't realized it would conflict with MVC 5 and newer.
You may be able to work around this by setting the project with your migrations as the VS startUp project (or by using the -StartupProject parameter) when running the commands.

**Comment by htuomola** [comment]
Ah right, I could've used the same project for startup which has the migrations. Don't know why I didn't think of that. Anyway, at least the issue is noted now.

----- Alkuperäinen viesti -----
Lähettäjä: "Brice Lambson" <notifications@github.com>
Lähetetty: ‎6.‎10.‎2015 19:52
Vastaanottaja: "aspnet/EntityFramework" <EntityFramework@noreply.github.com>
Kopio: "Henri Tuomola" <htuomola@gmail.com>
Aihe: Re: [EntityFramework] Can't reference EntityFramework.Commands inASP.net MVC 5 app with 7.0.0-rc1-15886 (#3340)

Oh yuck; we should remove our dependency on Razor (Issue #2947) soon. I hadn't realized it would conflict with MVC 5 and newer.
You may be able to work around this by setting the project with your migrations as the VS startUp project (or by using the -StartupProject parameter) when running the commands.

**Comment by rowanmiller** [comment]
Closing as we have update #2947 to explicitly say we need to remove the dependency
