### ISSUE TITLE
How to add only an incremental migration through IMigrationsScaffolder?

### ISSUE THREAD

**Issue by ramayasket** [dotnet/efcore#33422]
I have made some changes to table classes and want to add a migration for those changes. I am using the following code (EF Core 6):
```
            var services = new ServiceCollection()
                .AddEntityFrameworkDesignTimeServices()
                .AddDbContextDesignTimeServices(db); // db = data context

            var designTimeServices = new SqlServerDesignTimeServices();
            designTimeServices.ConfigureDesignTimeServices(services);
            
            var serviceProvider = services.BuildServiceProvider();
            var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();
            var migration = scaffolder.ScaffoldMigration(migrationName, "MyNamespace");
            Console.WriteLine(migration.MigrationCode);
```
I expect that my new migration is "incremental", i.e. it only contains the new changes, but not, it contains all the data as if it was an initial migration for my data context. How do I get an incremental migration similar to what I get in Visual Studio when I do `add-migration` in the Package Manager Console?

**Comment by AndriySvyryd** [comment]
The code above should add a migration containing only the changes from the previous one, provided that the previous migration is located in the same assembly as the context type or [MigrationsAssembly(string)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.relationaldbcontextoptionsbuilder-2.migrationsassembly?view=efcore-8.0#microsoft-entityframeworkcore-infrastructure-relationaldbcontextoptionsbuilder-2-migrationsassembly(system-string)) option has been set.

Also, consider upgrading to EF 8. If you are still experiencing this issue, please provide a small repro project.
