### ISSUE TITLE
Global query filters do not produce same SQL statements as query by DbSet

### ISSUE THREAD

**Issue by osjimenez** [dotnet/efcore#33424]
I'm using global query filters by Entity type for authorization purposes.

When I do this filter:
```csharp
db.SampleEntities.Where(e => ids.Contains(e.ExternalId))
```
EF create this query:
```SQL
SELECT [s].[Id], [s].[ExternalId], [s].[Name]
      FROM [SampleEntities] AS [s]
      WHERE [s].[ExternalId] IN (
          SELECT [i].[value]
          FROM OPENJSON(@__ids_0) WITH ([value] bigint '$') AS [i]
      )
```
Uses the new JSON feature to allow SQL Server to cache the query and do it faster next time, great!

But when I set the same query in a global query filter:
```csharp
entityConfig.HasQueryFilter(e => ids.Contains(e.ExternalId));
```
EF Create the query:
```SQL
SELECT [s].[Id], [s].[ExternalId], [s].[Name]
      FROM [SampleEntities] AS [s]
      WHERE [s].[ExternalId] IN (CAST(1 AS bigint), CAST(2 AS bigint), ...)
```
>I don't understand why cast all longs, but this is not the topic

Why is the final SQL statement not the same? 
Can I do anything to force EF to use JSON feature in global query filter?

I create a simple app to test this on https://github.com/osjimenez/EFSample

Thanks ;)

**Comment by roji** [comment]
In your query filter:

```c#
entityConfig.HasQueryFilter(e => ids.Contains(e.ExternalId));
```

Since `ids` is a captured local variable, it cannot really change from query to query; in order words, it's a constant. As such, translation to a simple IN (without OPENJSON) is the superior translation.

However, note what happens if you instead do Contains on a class property:

```c#
public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().HasQueryFilter(b => Ids.Contains(b.Id));
    }

    public int[] Ids = [1, 2, 3];
}
```

In this case, EF generates SQL with OPENJSON; this allows you to pass an array of IDs e.g. to your DbContext type's constructor, and the query filter will take that into account. And since that means different queries send different actual array values, the array is parameterized and you get OPENJSON.

> I don't understand why cast all longs, but this is not the topic

To help with this I'd need to see a minimal, runnable repro (including one with your issues is always a good idea). See the code sample below which does not reproduce this - you can tweak that sample to make it show the cast.

<details>
<summary>Code sample</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

_ = await context.Blogs.ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var ids = new[] { 1, 2, 3 };
        modelBuilder.Entity<Blog>().HasQueryFilter(b => ids.Contains(b.Id));

        // modelBuilder.Entity<Blog>().HasQueryFilter(b => Ids.Contains(b.Id));
    }

    public int[] Ids = [1, 2, 3];
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

**Comment by osjimenez** [comment]
Thanks for your explanation @roji, I was very surprising to understand how EF captures the variable in a different way if it's a class property.

My real scenario is more complex, I'm using [LinqKit ](https://github.com/scottksmith95/LINQKit) to create authentication expressions and inject it to the DbContext. In this scenario, put the list of values in a property doesn't work for me :(

Finally, I solved the problem with [QueryableValues](https://github.com/yv989c/BlazarTech.QueryableValues) library, which allow me to specify that the list of values must be interpreted as parametrized query.

Thanks a lot!
