### ISSUE TITLE
Scaffolding: Optionally including the `nullable` directive for generated code

### ISSUE THREAD

**Issue by JohnYoungers** [dotnet/efcore#33426]
In EFCore5, using the `.editorconfig` I would mark the scaffolded files as `generated_code = true`: this ensured the classes wouldn't trigger any analytic or styling issues with the build.

In the past few versions, now that code is scaffolded with `<Nullable>enable</Nullable>` in mind, my `generated_code` setting ends up overriding the behavior partially due to this (see the `Important` section):  https://learn.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#plan-your-migration

I'm not sure if it can be detected automatically, or if we could add a flag to do so, but it would be beneficial if we could include `#nullable enable` in the generated files for this scenario

**Comment by JohnYoungers** [comment]
@cincuranet / @roji - does adding that declaration seem feasible?

Without including `generated_code = true`, we end up triggering several other analytic issues (Collection initialization can be simplified, etc)

**Comment by ajcvickers** [comment]
@JohnYoungers You can [update the T4 templates](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) to always output `#nullable` directives in generated files. This will prevent your global settings from changing the behavior in these files.
