### ISSUE TITLE
ChangeTracking not working as expected when using Collections with backing field

### ISSUE THREAD

**Issue by gps-lasrol** [dotnet/efcore#33427]
## Description

I am not sure if this is a bug or if there is something i don't understand. If this is working as intended, then at least i think the documentation should be updated. 

For reference you can view the github project i provided to reproduce this issue. 

I have created a entity named blog, with a collection of posts using a backing field.  
When i add post or remove a post it does not seem to track the changes. So if i add any post or remove any post it does not update the tables. 

The ChangeTracker still reports it has changes to apply, but no changes are done. It could be something wrong with my model configuration, but i think it is as defined in the documentation.

I have also created a entity named blogV2, with a collection of postV2s this time only using properties.   
This seems to work fine, and changes are tracked as expected. 

### Include your code

https://github.com/gps-lasrol/EfBackingfieldDemo/tree/master/EfCoreBackingFieldDemo

### Include verbose output
Blog Requests
```
-------------  Request started ------------- 
Adding new blog, with 1 post
Has changes to apply
-------------  Request finished ------------- 
-------------  Request started ------------- 
Adding 1 post
Has changes to apply
-------------  Request finished ------------- 
-------------  Request started ------------- 
Fetching the blog, with 2 posts. Removing the first post
No post found
-------------  Request finished -------------
-------------  Request started -------------
Fetching the blog, with 1 post.
-------------  Request finished -------------
```
BlogV2 Requests
```
-------------  Request started -------------
Adding new blogV2, with 1 postV2
Has changes to apply
-------------  Request finished ------------- 
-------------  Request started -------------
Adding 1 post
Found post with id: 398e6408-eb52-4405-27e4-08dc4f6a57dd
Has changes to apply
-------------  Request finished -------------
-------------  Request started -------------
Fetching the blog, with 2 posts. Removing the first post
Found post with id: 398e6408-eb52-4405-27e4-08dc4f6a57dd
Found post with id: 809f4108-1397-4993-27e5-08dc4f6a57dd
Removing first post
Has changes to apply
-------------  Request finished ------------- 
-------------  Request started -------------
Fetching the blog, with 1 post.
Found post with id: 809f4108-1397-4993-27e5-08dc4f6a57dd
-------------  Request finished -------------
```

### Include provider and version information

EF Core version: 8.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system: Windows 11 Pro
IDE: Jetbrains Rider 2023.3.3

**Comment by fiseni** [comment]
Hi @gps-lasrol,

In the `Blog` entity you end up with two navigations in your current configuration. You've explicitly set the navigation to the backing field, but the `Posts` collection is unrelated to the field at all.

If you update the model as follows, I think you won't face issues

```csharp
public class Blog
{
    public Guid Id { get; set; }
    
    private readonly List<Post> _posts = new();
    public IEnumerable<Post> Posts => _posts;

    public void AddPost(Post post)
    {
        _posts.Add(post);
    }

    public void RemovePost(Post post)
    {
        _posts.Remove(post);
    }
}
```

Also, you won't need the following configuration.
```csharp
modelBuilder.Entity<Blog>()
	.Metadata
	.FindNavigation("Posts")
	.SetPropertyAccessMode(PropertyAccessMode.Field);
```

**Comment by gps-lasrol** [comment]
From EF Core Backing fields documentation

> By convention, the following fields will be discovered as backing fields for a given property (listed in precedence order).
> 
>    -  <camel-cased property name\>
>    -  _<camel-cased property name\>
>    -  _<property name\>
>    - m_<camel-cased property name\>
>    -  m_<property name\>

I am assuming that the Posts and _posts should be "connected"
I also have the following configuration:
```
modelBuilder.Entity<Blog>()
            .HasMany(p => p.Posts)
            .WithOne(p => p.Blog)
            .HasForeignKey(p => p.BlogId);
```

This should also configure the releationship.
Regarding the metadata config, this was something i just tested to see if i could force it in some way.

**Comment by fiseni** [comment]
That configuration is correct. Since you're following standard naming conventions, you don't need that configuration either, but it doesn't hurt to have it.

The difference is the following line `public IEnumerable<Post> Posts { get; set; }`. You should have it as `public IEnumerable<Post> Posts => _posts;`. In your case, the compiler will generate an additional backing field (something like `<Posts>k__BackingField`).

Makes sense?

**Comment by gps-lasrol** [comment]
Ahh, derp! Need to invest in solid glasses! :1st_place_medal: This was only the issue in my demo project, not in my main. I did figure out why it was failing there as well. So i am closing this as its clearly my own mistakes :)
