### ISSUE TITLE
Could not load type 'SqlGuidCaster' from assembly Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by aj-scram** [dotnet/efcore#33430]
Recently upgrade project from .net7 to .net8 and immediately ran into this old https://github.com/dotnet/SqlClient/issues/1930

Seems that the root cause is any older version of Microsoft.Data.SqlClient (<5.2.0) than the newest release not playing well with reflection calls loading types/assemblies.

Could we get Microsoft.EntityFrameworkCore.SqlServer to update to use the new version?

**Comment by ErikEJ** [comment]
No going to happen, as 5.2 is not LTS and .NET 8 is. You can just add an explicit reference.

**Comment by aj-scram** [comment]
Then can the dotnet team work internally to backport the fix to a 5.1.6 release? This a major and long-standing breaking issue for those trying to migrate their projects; it seems unreasonable to me to have us work around it on our end.

**Comment by ajcvickers** [comment]
We're actually going to revert to an older release for EF Core 9, since we can't take a dependency on a non-LTS version. So EF Core won't depend on anything above 5.1 until at least EF Core 10.

**Comment by rasmusrim** [comment]
> Not going to happen, as 5.2 is not LTS and .NET 8 is. You can just add an explicit reference.

Could I ask you to explain how to do that? Thanks!

**Comment by ErikEJ** [comment]
@rasmusrim 

Add this to your .csproj file that reference the EF Core SQL Server provider:

`<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />`

**Comment by aj-scram** [comment]
> > Not going to happen, as 5.2 is not LTS and .NET 8 is. You can just add an explicit reference.
> 
> Could I ask you to explain how to do that? Thanks!

https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution#direct-dependency-wins

For doc reference

**Comment by amircliper** [comment]
> [@rasmusrim](https://github.com/rasmusrim)
> 
> Add this to your .csproj file that reference the EF Core SQL Server provider:
> 
> `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />`

Thank you for sharing this solution! I ran into the same issue and confirmed that adding the following to the .csproj file resolves it:
‍`<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />`
Tested and worked perfectly
