### ISSUE TITLE
Upgrade Microsoft.EntityFrameworkCore 8.0.3 Error

### ISSUE THREAD

**Issue by sumanth1221** [dotnet/efcore#33431]
**Recently I have migrated my project from .NET 6 to .NET 8.**

I have used [.NET Upgrade Assistant](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.upgradeassistant) to upgrade my project, I am able to build solution with .NET 8 packages. I can see only following packages are upgraded in my solution.

**Old Packages**

```
<PackageReference Include="ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly" Version="7.0.8" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.8" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.8" />
```

**My Upgraded packages**

```

<PackageReference Include="ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly" Version="7.0.8" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.3" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
```

I ran solution solution to test my code, but when code related to EntityFrameworkCore executes it throws following error. 

We are adding db context as follows previously, I can see UseDateOnlyTimeOnly() is part of following package, but there is no upgrade in this package so is it causing any issue @ErikEJ.

`<PackageReference Include="ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly" Version="7.0.8" />`
    
```
builder.Services.AddDbContextFactory<ToolsDevEntities>(
        options => options.UseSqlServer(builder.Configuration.GetConnectionString("ToolsDevEntities"), 
                           x => x.UseDateOnlyTimeOnly()).EnableDetailedErrors(true));
```
```
try
{
    using (var dx = DatabaseFactory.CreateDbContext())
    {
        var obj = new DummyModel();
        obj.Notifications = dx.TableName.Where(c => c.Key == "Key").Select(c => c.Value).SingleOrDefault().Split(',').ToList();
        return obj;
    }
}
catch (Exception e)
{
    return new DummyModel();
}
```

Did not found any specific documentation to fix this error, I am reaching out here, someone faces same issue or is there any solution to resolve this error ? Thanks for your help in advance.

System.MissingMethodException
HResult=0x80131513
Message=Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'. Source=EntityFrameworkCore.SqlServer.DateOnlyTimeOnly 

I can see similar issues were resolved by @ErikEJ @roji

**Comment by fiseni** [comment]
Hi @sumanth1221,

In EF Core 8 there is native support for `DateOnly` and `TimeOnly`, and you don't need additional packages. So, you can remove the `UseDateOnlyTimeOnly`. I assume the package is conflicting in EF8. Also, follow this [documentation](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes?WT.mc_id=DT-MVP-402515#sql-server-date-and-time-now-scaffold-to-net-dateonly-and-timeonly) for a potential breaking change.

If you can reproduce the issue in a small sample app, it would help to find the exact issue. At least, please provide the model and the EF configuration.

**Comment by roji** [comment]
@sumanth1221 as @fiseni wrote, ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly only works with EF Core 7.0 - you cannot mix multiple major versions of EF in the same project (7 and 8 in this case). In any case, DateOnly and TimeOnly are fully supported in EF 8.0 - ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly was only written to help users still on 7.0, so you should be able to remove it.

I'll go ahead and close this, but if you're still encountering issues, post back here and we'll revisit.
