### ISSUE TITLE
Set the ordering as the identifier when translating VALUES

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#33436]
Our translation of inline collections to SQL ValuesExpression does not specify an identifier, making it impossible to use project in certain query contexts.

Flagged by @maumar in https://github.com/dotnet/efcore/issues/33410#issuecomment-2027991786

**Comment by maumar** [comment]
@roji, should we patch this, given that https://github.com/dotnet/efcore/issues/33410 is a regression and the fix is not too complicated?

**Comment by roji** [comment]
See https://github.com/dotnet/efcore/issues/33438#issuecomment-2041024040

**Comment by roji** [comment]
Decision: we won't backport this since the workaround is trivial (add AsEnumerable()), and this doesn't actually address the customer-reported issue (which is about Concat, whereas this fixed Union). If additional user reports come in, we can reconsider.
