### ISSUE TITLE
EF.IsDesignTime not set in efcore bundle context 

### ISSUE THREAD

**Issue by Herve-M** [dotnet/efcore#33445]
`EF.IsDesignTime` has been added to be able to detect if executing context is from an ef-core tools or not, allowing custom setup normally dedicated for EF-Core database jobs. 

While generating a migration bundle, `EF.IsDesignTime` is set to true and so generate a bundle/executor with dedicated/lightened setup for database migration but while running `MigrationsBundle.Execute` might use the StartupAssembly (if provided) which use default startup behavior thus having non wanted setup.  _(like migrating all other db context, connecting to dependencies etc..)_

## Expected behavior 
`EF.IsDesignTime` set to TRUE while running generated ef-core bundle

## Current behavior
`EF.IsDesignTime` is set to FALSE while running generated ef-core bundle

## Include provider and version information

EF Core version: 8.0.3 (nuget) / 8.0.3 (dotnet-ef)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net8.0
Operating system: Windows 10 / 10.0.19045 / win-x64 / 8.0.200-manifests.8cf8de6d 
IDE: Visual Studio 2022 17.9.5 / vscode

**Comment by AndriySvyryd** [comment]
Fixed in 4b80cb93e115c5c0179dc848983c56effa8888a8
See https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Design/Internal/DbContextOperations.cs#L418

**Comment by Herve-M** [comment]
@AndriySvyryd Not sure how it fixes the problem, if my DI setup 2 DB context inside `EF.IsDesignTime` scope and RabbitMQ outside then everything will be still executed: 2 DB context and RabbitMQ.

**Comment by AndriySvyryd** [comment]
@Herve-M Not sure what you mean. Can you share a small repro project? Preferably using 9.0.0-preview7

**Comment by Herve-M** [comment]
In 8.0.3, the issue could be summed-up with a sample like this:
``` csharp
namespace WorkerService
{
    public class Program
    {
        public static void Main(string[] args)
        {
            HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);

            if (EF.IsDesignTime)
            {
                builder.Services
                    .AddDbContext<AppDbContext>(options =>
                    {
                        options.UseSqlite(
                            builder.Configuration["ConnectionStrings:AppDbContext"],
                            x =>
                            {
                                x.MigrationsHistoryTable(HistoryRepository.DefaultTableName, "neverusedbo");
                                x.MigrationsAssembly(typeof(AppDbContext).Assembly.FullName);
                            }
                        );
                    })
                    ;

                _ = builder.Build();
                return;
            }

            throw new Exception("This shouldn't even happen while running from an EF Bunddle context");
        }
    }
}
```

While running the generated bundle targeting `AppDbContext`, we could read `An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: This shouldn't even happen while running from an EF Bunddle context` 

In our case we can replace the throw by like: 
``` csharp
builder.Services
    .AddDbContext<AppDbContext>(options =>
    {
        options.UseSqlite(
            builder.Configuration["ConnectionStrings:AppDbContext"],
            x =>
            {
                x.MigrationsHistoryTable(HistoryRepository.DefaultTableName, "neverusedbo");
                x.MigrationsAssembly(typeof(AppDbContext).Assembly.FullName);
            }
        );
    })
    .AddDbContext<SecondAppDbContext>(options =>
    {
        options.UseSqlite(
            builder.Configuration["ConnectionStrings:SecondDbContext"],
            x =>
            {
                x.MigrationsHistoryTable(HistoryRepository.DefaultTableName, "external");
                x.MigrationsAssembly(typeof(SecondAppDbContext).Assembly.FullName);
            }
        );
    })
    .AddHostedService<DummyDatabaseMigrationService>();

IHost host = builder.Build();
host.Run();
```

And mirgations from `SecondAppDbContext` where executed as for the `DummyDatabaseMigrationService` too.

**Comment by Herve-M** [comment]
Using 8.0.8 fixed the main issue, even if it seems that it removes the capacity of running a HostedService from within the  `EF.IsDesignTime` scope/context.

**Comment by jchen1** [comment]
For what it’s worth, this change proved to be breaking in our transition to EF 9. We use the IsDesignTime flag to determine whether we would try to grab secrets (such as the database password) when constructing our service provider. 
This worked with the previous behavior because we’d pull secrets at bundle runtime but not build time—now, we need a separate flag to distinguish between the two cases.

**Comment by AndriySvyryd** [comment]
@jchen1 Note that if you implement [`IDesignTimeDbContextFactory`](https://learn.microsoft.com/ef/core/cli/dbcontext-creation#from-a-design-time-factory) you can access the `args` supplied to the bundle executable.
