### ISSUE TITLE
LazyLoader.Load remove ConcurrentDictionary _isLoading

### ISSUE THREAD

**Issue by Charles113** [dotnet/efcore#33441]
Hello, 

if i look at the source code of `LazyLoader.Load` then i see some potential issues.

Why would we need a ConcurrentDictionary "_isLoading" for every LazyLoader, that might not even get used.
The ConcurrentDictionary should be lazily initialized.
Not like this:

	private readonly ConcurrentDictionary<(object Entity, string NavigationName), bool> _isLoading = new(NavEntryEqualityComparer.Instance);

Second issue: A DbContext is IMHO not thread safe, so why implement "thread safety" in the LazyLoader.

What should the code 

	if (_isLoading.TryAdd(navEntry, true))	
		...
		entry.Load()
			
Even do?

If two threads arrive at the same time, then the first thread would start loading the `Navigation`.
The second thread would skip the block and just return null, Possible BUG.

A simple lock would be more appropriate here i guess.
Maybe i'm misreading the code.

Best Regards.

**Comment by ajcvickers** [comment]
Entities using proxies for lazy-loading are thread-safe once loading has happened. This allows entities that have gone through a stage where they are lazy-loading to later be shared when they no longer need to lazy-load.

Note that lazy-loading is considered an anti-pattern my many and its use is generally discouraged.
