### ISSUE TITLE
SQL Server connection string for Mono

### ISSUE THREAD

**Issue by angelsix** [dotnet/efcore#3345]
EF7 supports SQL Server on Linux using Mono (http://ef.readthedocs.org/en/latest/providers/index.html#entityframework-sqlserver). However, I have no idea what the connection string will be on Linux using Mono?

I presume we dont have to use localdb either and can use an actual server, but again I have no documentation or idea where to start.

**Comment by natemcmaster** [comment]
EF passes the connection string through to the ADO.NET provider. Mono uses the same format that full .NET uses. Official docs: https://msdn.microsoft.com/en-us/library/ms254500(v=vs.110).aspx. More useful docs: https://www.connectionstrings.com/sqlconnection

**Comment by angelsix** [comment]
I was after some info on how to actually use in on linux/mono. The links you provide are just MS links.

For example, installed mono on linux. Is that it? 
Do I need to manually install something for SQL to be on linux/mono?
How do I see the database, start it, stop it, manage it?
What's the server name? (local), ., machine name, something else?

With my current build on linux with mono installed, running dnx ef database update throws:

Using context 'AppContext'.
Using database 'test-database' on server '.'.
System.Data.SqlClient.SqlException: Server does not exist or connection refused.

Connection string is:             

optionsBuilder.UseSqlServer(@"Server=.;Database=test-database;Trusted_Connection=True;MultipleActiveResultSets=True");

**Comment by natemcmaster** [comment]
Based on your questions, I suggest you read some tutorials on the fundamentals of using SQL Server. I would suggest this as a starting place: [Database Engine Tutorials on MSDN](https://msdn.microsoft.com/en-us/library/ms345318.aspx).

Regarding your question about mono, your error message indicates to me you have mono installed correctly. Mono comes with a version of SqlClient out-of-box, but it is very outdated (2005) and will you will likely have errors (just search EF issues and you will find some.) We are working on .NET Core implementation of SqlClient that will work better.

**Comment by angelsix** [comment]
I have 5 years SQL Server experience on Windows and run multiple 1 million plus user sites so I'm not sure why you feel I would need basic tutorials on how it works.

I've asked specific questions on how it works on Linux which I have zero experience in but again the questions were ignored.

I'll just look at the .Net source code I'm clearly getting nowhere here

**Comment by natemcmaster** [comment]
@angelsix My apologies. Using SQL Server from Linux is the same as using it from another Windows instance except that (obviously) you cannot have a localhost instance of SQL Server. Add the server DNX name or IP address to your connection string. Furthermore, IntegratedSecurity does not work on Linux as that is a Windows-only feature, so you will need SQL Server authentication.

**Comment by angelsix** [comment]
I have mis-read the supporting document. I was under the impression Mono had a version of SQL Server for Linux (which I was very surprised by) and thought it was a new .Net Core feature that SQL Server had been ported to run on linux.

Re-reading it, it looks like its just a provider to access an SQL server running on a windows machine.

So that puts me back to a new requirement. My project will run entirely on Linux so I need a database on Linux. What's the best option for supporting a large complex Entity Framework project?

**Comment by natemcmaster** [comment]
Yup, you and many wish for SQL Server hosting on Linux. Fortunately, EF7 will work with other providers. There is pre-release support for postgres (http://ef.readthedocs.org/en/latest/providers/index.html#entityframework-npgsql) being done by another group (external to the ASP.NET team). It is still a work in progress. You can track the progress on https://github.com/npgsql/npgsql/issues/249.

**Comment by angelsix** [comment]
Thanks. Looks like I'll have to switch to postgres. Is that the only EF database linux option? (in case I find issues with postgres)

**Comment by natemcmaster** [comment]
At the moment, yes postgres is it. (Other than SQLite, which is really only meant for embedded/mobile devices.)

**Comment by rowanmiller** [comment]
SQLite is also good for local dev work if you just want to get up and running without needing to spin up Postgres (you can think of it as somewhat akin to LocalDB). We are working with other provider writers to have EF7 providers for the other common database choices on Linux.

**Comment by angelsix** [comment]
I dont mind putting the work in (currently have Postgres installed a user created and a database manually created via psql) so I'll work with PostgeSQL as its the only option.

I like to have alternative options though in case of issues. Don't suppose you guys plan on porting SQL Server to Linux natively? :)

**Comment by natemcmaster** [comment]
No plans that I'm aware of. 

However, we are hard at work getting SQL Client working well on Linux on .NET Core (not Mono). A [recent change](https://github.com/dotnet/corefx/pull/3567) in CoreFX (the .NET Core implementation of System.Data.SqlClient) makes huge steps towards better Linux support. It should be reflected in our product fairly soon. 

But of course, this means you still need a Windows box to run the SQL Server. So this may not make a big difference for you if you need the database to run on Linux too.

**Comment by angelsix** [comment]
Ok good to know. It would be nice to have a good SQL client as my main machine is now a Linux box and SQL clients really suck for linux.

Looks like I'll work hard at PostgreSQL and hope it works with EF7!

**Comment by angelsix** [comment]
All done and working (at least the initial EF migration) with PostgreSQL.

For anyone wanting to use it basic steps are:

1. Install PostgreSQL (http://www.postgresql.org/download/linux/)
2. Create a username and pass you would like to use in EF. Via terminal type:
sudo -u postgres psql
psql#> create user <desiredusername> createdb createuser password ‘<desiredPassword>’;
psql#> \q

3. In your project.json add reference to Npgsql
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "EntityFramework7.Npgsql": "3.1.0-beta7-1"
      }
    }

4. In your Startup.cs in ConfigureServices, use Npgsql
services.AddEntityFramework()
    .AddNpgsql()
    .AddDbContext<YourContext>();

5. In your context (or in the AddNpgsql() call above) setup the connection string to match the username and password created in step 2. I've done it in the DbContext:

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
        // And PostgreSQL for Linux
        optionsBuilder.UseNpgsql("Server=127.0.0.1;Port=5432;Database=desired_database_name;User Id=username_from_step2; Password = password_from_step2;");
}

6. Back to terminal, go to your project directory, do a dnu restore and dnu build to make sure your project builds ok.

7. From project directory, create your EF initial migration if you havent already.
dnx ef migrations add InitialMigration

8. Now get ef to create the database in your PostgreSQL server
dnx ef database update


Install DbVis or SquirrelSQL to connect to your database and visuall confirm all is well.

**Comment by roji** [comment]
@angelsix am the main Npgsql dev, happy to see things work for you. Please note that the provider is still not production-ready although most thing should work fine. Please report any issues you run across to https://github.com/npgsql/npgsql

**Comment by natemcmaster** [comment]
@angelsix

>  Don't suppose you guys plan on porting SQL Server to Linux natively? :)

https://blogs.microsoft.com/blog/2016/03/07/announcing-sql-server-on-linux/
