### ISSUE TITLE
Win10 vs 11 and 0x80090325: certificate chain issue

### ISSUE THREAD

**Issue by awdorrin** [dotnet/efcore#33451]
Co-worker and I are updating our app from .Net 6 to .Net 8.

This morning I upgraded to 8.0.3 libraries and started getting the exception: (0x80090325): The certificate chain was issued by an authority that is not trusted

We encountered this previously due to the .net7 breaking change, and we updated our database connection string to include:

- Integrated Security=True; TrustServerCertificate=true; Encrypt=false

I get the error, on Windows 11
Co-Worker on Win10 has no error.

Clean-Rebuild of app, we synced our changes through Git and confirmed we are on the same baselines.
I'm not sure what else to check, so not sure if this is a weird Win11 difference.

### Include stack traces

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
 ---> System.ComponentModel.Win32Exception (0x80090325): The certificate chain was issued by an authority that is not trusted.
```

### Include provider and version information

EF Core version: 8.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer to SQL Server 2016 DB
Target framework: .NET 8.0
Operating system: Windows 11 vs Windows 10
IDE: Visual Studio 2022 17.9

**Comment by roji** [comment]
@awdorrin this is a SqlClient change; [see this breaking change note](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#encrypt-true).

**Comment by awdorrin** [comment]
@roji Thanks for the suggestion. We are aware of the .Net 7 breaking change, which I mentioned:

> We encountered this previously due to the **.net7 breaking change**, and we updated our database connection string to include:
> Integrated Security=True; **TrustServerCertificate**=**true**; **Encrypt**=**false**

**Comment by roji** [comment]
@awdorrin sorry, I didn't read your post closely enough.

But at the end of the day, this is a SqlClient question rather than an EF question: 8.0.2 depends on SqlClient 5.1.4 ([nuget.org](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.2#dependencies-body-tab)), whereas 8.0.3 bumped the SqlClient version to 5.1.5 ([nuget.org](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.3#dependencies-body-tab)). You'll have to continue this conversation on the [SqlClient repo](https://github.com/dotnet/sqlClient).

**Comment by awdorrin** [comment]
@roji- didn't realize it was a different library - I'll follow up over there. Thanks!

**Comment by awdorrin** [comment]
@roji 
I managed to get the DB Connection to work on Win11, for me, finally... and I don't think it is the SqlClient.

We use EF Core Power Tools to generate/update the models our database project.
I just found that EF Core Power Tools is creating an OnConfiguring method:
```
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=OurServer;Initial Catalog=OurDB;Integrated Security=True;Encrypt=false");
```
During startup of the app, even though we've configured the context in Startup.cs ConfigureServices(), this OnConfiguring is getting called instead.

``` Structure.dll!Lib.DB.Services.Database.MainDBContext.OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder optionsBuilder) Line 337	C#
[External Code]	
App.dll!Services.CommonUtilities.ValidateOrAddUser(Lib.DB.Services.Database.MainDBContext _context, Lib.DB.Services.Database.WarehouseDB.WarehouseDBContext _prismContext, string ntid) Line 81	C#
 	App.dll!Controllers.UserClaimsController.GetCurrent() Line 37	C#
 	[External Code]	
>	App.dll!Startup.Configure.AnonymousMethod__8_0(Microsoft.AspNetCore.Http.HttpContext context, System.Func<System.Threading.Tasks.Task> next) Line 190	C#
```
I'm not sure why it is calling the OnConfiguring method, rather than using what is configured in ConfigureServices (and getting pulled from user.secrets and appsettings.json.
But, it I add **TrustServerCertificate=true** it works properly.

I don't know why I'm seeing this on Win11 and my coworker isn't on Win10, wondering if we might be on a different version of VS2022...

**Comment by ErikEJ** [comment]
The OnConfiguring method is only added if you explicitly ask for the connection string to be included- not recommended.

**Comment by roji** [comment]
@awdorrin if there's an OnConfiguring method, EF calls it - that's very much by design; if you don't want to have OnConfiguring, you can remove it (and for scaffolding, ask for it to not get created as @ErikEJ writes above).

**Comment by awdorrin** [comment]
Makes total sense that the OnConfiguring would over-ride. 
I should have thought to check this out yesterday, before posting, but this morning I went back through the change log for the MainDBContext.cs file, and something changed with how EF Core Power Tools generates the OnConfiguring method.

In our previous .Net6 baseline:

```
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information... (snip)
                optionsBuilder.UseSqlServer("Data Source=OurServer;Initial Catalog=OurDB;Integrated Security=True;Encrypt=True");
            }
        }
```
And the .net8 baseline:
```
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information...  (snip)
        => optionsBuilder.UseSqlServer("Data Source=OurServer;Initial Catalog=OurDB;Integrated Security=True;Encrypt=True");
```
So the lack of the IsConfigured check explains why I'm hitting this code now, although I don't understand why my co-worker isn't hitting this call when running on Win10... I am going to have to follow up with him and see if we can screenshare as he starts up the app on his system.

I will head over to the EF Core Power Tools Github and see if there is any discussion about the missing IsConfigured check.
And follow up after I've had a chance to check things out with my co-worker.

Thanks!
