### ISSUE TITLE
Filtered index hides the non-filtered index

### ISSUE THREAD

**Issue by jirikanda** [dotnet/efcore#33454]
We have a simple model class.

```C#
public class MyTable
{
	public int Id { get; set; }
	public int SomeNumber { get; set; }
}
```

This table should be mapped using a DbContext to the database with **two indexes**.

```C#
public class MyDbContext : DbContext
{
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);
		modelBuilder.Entity<MyTable>(etb =>
		{
			etb.HasIndex(myTable => myTable.SomeNumber).IsUnique().HasFilter("0=1"); // this index is created but due the (weird) condition, it is useless
			etb.HasIndex(myTable => myTable.SomeNumber); // this index is not created
		});
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		base.OnConfiguring(optionsBuilder);
		optionsBuilder.UseSqlServer("fake connection string");
	}
}
```

When I add a migration, **it creates only one index** (the filtered one).

```C#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
        ... // shortened

    migrationBuilder.CreateIndex(
        name: "IX_MyTable_SomeNumber",
        table: "MyTable",
        column: "SomeNumber",
        filter: "0=1");
}
```
        
### Expected behavior

**Two indexes should be created**:
* unique filtered index: to ensure unique values under the condition (as defined in the model)
* non-unique, non-filtered index: to cover all records in the table by the index (as defined in the model)

### Reprosteps

There is a [simple repository with showing the issue](https://github.com/jirikanda/EFCoreIndexDemo).

### Include provider and version information

EF Core version: 8.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.3
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.9.2

**Comment by fiseni** [comment]
It's targeting the same index, that's why. The index is defined by `HasIndex`. Then you can incrementally configure it if you want. For instance, using your sample, this configuration will create a single index (with all configs aggregated).

```csharp
etb.HasIndex(myTable => myTable.SomeNumber);
etb.HasIndex(myTable => myTable.SomeNumber).IsUnique();
etb.HasIndex(myTable => myTable.SomeNumber).HasFilter("[SomeNumber] <> 0");
etb.HasIndex(myTable => myTable.SomeNumber).HasDatabaseName("Index1");
```

```sql
migrationBuilder.CreateIndex(
    name: "Index1",
    table: "MyTable",
    column: "SomeNumber",
    unique: true,
    filter: "[SomeNumber] <> 0");
```

**Comment by jirikanda** [comment]
@fiseni, thanks for the answer, you are right!

I found this explanation
> Note that if you call HasIndex more than once on the same set of properties, that continues to configure a single index rather than create a new one...

in [the documentation](https://learn.microsoft.com/en-us/ef/core/modeling/indexes).

There is also mentioned
> To create multiple indexes over the same set of properties, pass a name to the HasIndex, which will be used to identify the index in the EF model, and to distinguish it from other indexes over the same properties...

And it is all I need to know!
