### ISSUE TITLE
Elastic DB + Entity Framework 7 Guidance - Samples are broken

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/efcore#3346]
Could someone do up an example of how to use Elastic DB with EF 7?  The samples won't work with a direct update and getting all of the dynamic loading stuff to work seems to be a non-trivial conversion.

Would be really great to have the sample load data from any shard and then save a new entity dynamically to the best shard possible.

Thanks!

**Comment by rowanmiller** [comment]
@JohnGalt1717 can you point us to the sample you are using for EF6?

**Comment by JohnGalt1717** [comment]
Here's the link to the article: https://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-scale-use-entity-framework-applications-visual-studio/

For such a powerful tool in general the documentation, especially to use it with Entity Framework is pretty bad and it doesn't work with EF7 although it looks like there's no reason why it shouldn't.

Perfect world:

1. There would be an updated PowerShell script to update all shards from the command line.
2. Samples or guidance on how to map/reduce from all shards, preferably with one Linq to entities call that is propagated to every data context.
3. Shard lookup based on Entity Type and Key to make changes (or automated way to just attach to a data context and it knows where to go find that key, or looks it up if it's an update and if insert, automatically distributes it to the best shard to balance load)

**Comment by JohnGalt1717** [comment]
Oh, and integration with Identity Framework so that Users can be distributed across shards automatically and in a perfect world, oauth refresh tokens distributed across shards as well.

**Comment by rowanmiller** [comment]
Opened https://github.com/Azure/azure-content/issues/4747 to track the need for that doc to be updated with EF7 samples.

Opened https://github.com/aspnet/EntityFramework/issues/3421 to track improvements to support Elastic DB in EF.

**Comment by KirteeM** [comment]
Any update on this? 
https://github.com/Azure/azure-content/issues/4747  is not accessible.
