### ISSUE TITLE
Internal NullReferenceException when using Owned Entities with TPH Inheritance

### ISSUE THREAD

**Issue by Jejuni** [dotnet/efcore#33465]
## Description and Code

When using the default "TPH" inheritance strategy with a type in that hierarchy that owns an entity that further references another entity a "NullReferenceException" from some EfCore internals is thrown.

This exception **DOES NOT** happen when using "TPC" strategy.
It also does not happen when using `AsNoTracking` on affected queries.

## Repro

A repo for the problem can be found here: https://github.com/ng-commander/TPHInheritanceProblem/tree/master

Replace the SqlServer connection string in `TestDbContext` with a valid one for your machine.

## Code

Given these entities:

```cs
public class Parent
{
    public Guid Id { get; set; }
    public IReadOnlyList<Child> Childs { get; set; } = new List<Child>();
}

public class Child
{
    public Guid Id { get; set; }
    public Guid ParentId { get; set; }
}

public class ChildDerived : Child
{
    public Misc Misc { get; set; } // this is owned
}

public class Misc
{
    public Message Message { get; set; } // this is a regular HasOne-HasMany configuration 
}

public class Message
{
    public Guid Id { get; set; }
}
```

and this configuration:

```cs
modelBuilder.Entity<Child>()
    .HasDiscriminator<string>("Discriminator")
    .HasValue<Child>("Child")
    .HasValue<ChildDerived>("Derived");

modelBuilder.Entity<ChildDerived>().OwnsOne(x => x.Misc);
```

leads to an exception when the following code is run:

```cs
await using (var ctx = new TestDbContext())
{
    await ctx.Database.EnsureDeletedAsync();
    await ctx.Database.EnsureCreatedAsync();
}

await using (var ctx = new TestDbContext())
{
    var parentId = Guid.NewGuid();

    var d1 = new ChildDerived()
    {
        Id = Guid.NewGuid(),
        ParentId = parentId,
        Misc = new Misc()
        {
            Message = new Message() {Id = Guid.NewGuid()}
        }
    };
    var c1 = new Child()
    {
        Id = Guid.NewGuid(),
        ParentId = parentId
    };

    var parent = new Parent()
    {
        Id = parentId,
        Childs = [d1, c1]
    };

    ctx.Parents.Add(parent);
    await ctx.SaveChangesAsync();
}

await using (var ctx = new TestDbContext())
{
    // NEXT LINE CAUSES EXCEPTION. No problem with 'AsNoTracking'
    var parent = await ctx.Parents.Include(p => p.Childs).FirstOrDefaultAsync();
}
```

### Include stack traces

Stack trace shows the code thrown from user error during execution of `InternalEntityEntry`:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateIncludeCollection>g__ProcessCurrentElementRow|23_0[TIncludingEntity,TIncludedEntity](<>c__DisplayClass23_0`2& )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection[TIncludingEntity,TIncludedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, SingleQueryResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, IReadOnlyList`1 parentIdentifierValueComparers, IReadOnlyList`1 outerIdentifierValueComparers, IReadOnlyList`1 selfIdentifierValueComparers, Func`5 innerShaper, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__15`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__15`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\Jejun\Desktop\derp\TPHInheritanceProblem\TPHTest\Program.cs:line 44

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.InternalEntityEntry(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager, Microsoft.EntityFrameworkCore.Metadata.IEntityType, object, Microsoft.EntityFrameworkCore.Storage.ValueBuffer)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(Microsoft.EntityFrameworkCore.Metadata.IEntityType, object, Microsoft.EntityFrameworkCore.Storage.ValueBuffer)
    Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(Microsoft.EntityFrameworkCore.Metadata.IEntityType, object, Microsoft.EntityFrameworkCore.Storage.ValueBuffer)
    Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection.__ProcessCurrentElementRow|23_0<TIncludingEntity, TIncludedEntity>(ref Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<>c__DisplayClass23_0<TIncludingEntity, TIncludedEntity>)
    Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection<TIncludingEntity, TIncludedEntity>(int, Microsoft.EntityFrameworkCore.Query.QueryContext, System.Data.Common.DbDataReader, Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryResultCoordinator, System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Data.Common.DbDataReader, object[]>, System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Data.Common.DbDataReader, object[]>, System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Data.Common.DbDataReader, object[]>, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer>, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer>, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer>, System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Data.Common.DbDataReader, Microsoft.EntityFrameworkCore.Query.Internal.ResultContext, Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryResultCoordinator, TIncludedEntity>, Microsoft.EntityFrameworkCore.Metadata.INavigationBase, System.Action<TIncludingEntity, TIncludedEntity>, bool)
    Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>.AsyncEnumerator.MoveNextAsync()
    Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Threading.CancellationToken)
    Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Threading.CancellationToken)
    Program.<Main>$(string[]) in Program.cs
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer, 8.0.3
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.9.5

**Comment by fiseni** [comment]
You have to define the `Misc` as nullable and would work.

```csharp
public class ChildDerived : Child
{
    public Misc? Misc { get; set; } // this is owned
}
```

It works with TPC since they're completely different tables (and EF doesn't have to deduce the covariance rules). Also, it works with `AsNoTracking`, since the `Include` statements are excluded in that mode. You're not fetching the entities and not adding anything to the tracker. The required SQL joins are deduced by the select expression automatically.

**Comment by Jejuni** [comment]
> You have to define the `Misc` as nullable and would work.
> 
> ```cs
> public class ChildDerived : Child
> {
>     public Misc? Misc { get; set; } // this is owned
> }
> ```
> 
> It works with TPC since they're completely different tables (and EF doesn't have to deduce the covariance rules). Also, it works with `AsNoTracking`, since the `Include` statements are excluded in that mode. You're not fetching the entities and not adding anything to the tracker. The required SQL joins are deduced by the select expression automatically.
> 
> PS. The `Message` navigation and relationship is kind of useless. First, there is no way you can configure that relationship. Second, you can never include that in your queries like `ctx.Parents.Include(p => p.Childs).ThenInclude(x => x.Misc.Message)`, since the base doesn't contain it.

Hey, it does work with making `Misc` nullable, but that is not the design I was going for. I want it to be non-nullable. This also works (and is supposed to work) in these kinds of scenarios. It just happens not to work in this constellation.

As for your other 2 points:
- `Include` most certainly does work with `AsNoTracking`. If you don't include the navigation properties they won't be fetched. The difference is that the Change Detector isn't involved. This explains why the exception doesn't occur with `AsNoTracking`: it occurs within `StartTrackingFromQuery`
- I don't know why you think you can't configure or include relationsships like the one mentioned above, but you absolutely can: `ctx.Parents.Include(p => p.Childs).ThenInclude(x => ((ChildDerived)x).Misc.Message)`
![image](https://github.com/dotnet/efcore/assets/33608497/f82b0e37-a91c-4657-8afb-46af849375f0)

**Comment by ajcvickers** [comment]
Note for triage: No longer repros on the daily build, but I have not found the issue with the same root cause.

**Comment by Jejuni** [comment]
> * That's a hack. It may work by accident :) But, you're on uncharted territory there. Those expressions are not executed, but interpreted by the consumer (in this case EF). So, it's up to EF whether it can interpret correctly the casting there.

Not sure what you mean by that, as it's the way that it is supposed to be done according to the docs: https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#include-on-derived-types
Now I'm sure there'll be some provider for which this doesn't work. There's other ways around this, but let's not try to make this a purely academic discussion

**Comment by fiseni** [comment]
Ok, just ran the sample now. Indeed, it works for non-nullable `Misc` if you add the FK property explicitly (on 8.0.3).
```csharp
public class ChildDerived : Child
{
    public Misc Misc { get; set; } // this is owned
}
public class Misc
{
    public Guid MessageId { get; set; }
    public Message Message { get; set; } // this is a regular HasOne-HasMany configuration 
}
public class Message
{
    public Guid Id { get; set; }
}
```

@Jejuni May I suggest a bit more strongly-typed design? It might give you some ideas. I've been answering this on other mediums, so I'll just post the screenshot.

![image](https://github.com/dotnet/efcore/assets/24314310/ccb0fd71-a935-4276-9f64-3903bc966a75)
