### ISSUE TITLE
When performing a Natural Language Search on MYSQL and limiting the number of rows returned, Entity Framework produces a warning

### ISSUE THREAD

**Issue by wstuart-hlm** [dotnet/efcore#33479]
When performing a Natural Language Search on MYSQL and limiting the number of rows returned, Entity Framework produces a warning.  MySQL automatically orders the results by relevance, and does not allow an ORDER BY clause.  How can I prevent this warning from occurring?

MySQL Reference Manual:
(https://dev.mysql.com/doc/refman/8.3/en/fulltext-natural-language.html) 

Sample Code to Produce the Warning:

```C#
databaseContext
            .Clients
            .Where(c => EF.Functions.IsMatch(
                c.Name,
                searchTerm,
                MySqlMatchSearchMode.NaturalLanguage)
            ).Take(100);
```

Warning Message:

> Microsoft.EntityFrameworkCore.Query[10102]. The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.

**Comment by maumar** [comment]
you can ignore the warning: https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.configurewarnings?view=efcore-8.0
This behavior is specific to the MYSQL provider and as such should be fixed there. We have extensibility point `RelationalQueryableMethodTranslatingExpressionVisitor.IsOrdered` that takes a SelectExpression, that could peek into the select expression and if it's in natural language mode, return true, irrespective of OrderBy clauses defined.

**Comment by lauxjpn** [comment]
@wstuart-hlm If you think ignoring the warning isn't a good enough solution, feel free to open an issue on our [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) repo about it (assuming you are using Pomelo and not Oracle's provider).
