### ISSUE TITLE
Inaccurate query warning about distinct operator after ordering with CROSS APPLY OPENJSON

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/efcore#33477]
## File a bug

The "LogDistinctAfterOrderBy" warning is triggered for SQL that does not use a distinct after ordering

This is the generated SQL:

```
SELECT [t].[Value]
FROM (
    SELECT DISTINCT [o].[Value]
    FROM [cms].[Content] AS [c]
    CROSS APPLY OPENJSON(CAST([c].[Data] AS nvarchar(max)), N'$.SportType') AS [o]
) AS [t]
ORDER BY [t].[Value]
```

From what I can tell, the DISTINCT is applied before the ordering, not after.

### Include verbose output
Microsoft.EntityFrameworkCore.Query The query uses the 'Distinct' operator after applying an ordering. If there are any row limiting operation used before 'Distinct' and after ordering then ordering will be used for it. Ordering(s) will be erased after 'Distinct' and results afterwards would be unordered.

### Include provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows
IDE: Visual Studio 2022 17.8.7

**Comment by roji** [comment]
Can you please post a minimal, runnable sample? The above contains SQL, but we need the LINQ query and the model.

**Comment by roji** [comment]
Suppressing warnings in covered in [this page of the docs](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#configuration-for-specific-messages). I'll go ahead and close this as there doesn't seem to be a problem in EF, but if you need further assistance or think something is problematic don't hesitate to post back here.
