### ISSUE TITLE
Invalid SQL is produced from LINQ Query with Convert.ToString() in join condition

### ISSUE THREAD

**Issue by jamezamm** [dotnet/efcore#33481]
I am using EFCore Version 8.0.3 with Oracle Database.

The Models:
```
[PrimaryKey(nameof(Gkey))]
[Table("NOTIFICATIONS")]
public class Notification
{
	[Column("GKEY")] public long Gkey { get; set; }
	[Column("TITLE")] public string Title { get; set; }

        public virtual ICollection<Privilege> Privileges { get; set; } = new List<Privilege>();
}

[PrimaryKey(nameof(ContextId), nameof(Id), nameof(PrivilegeId))]
[Table("PRIVILEGES")]
public class Privilege
{
	[Column("CONTEXT_ID")] public string ContextId { get; set; }
	[Column("ID")] public string Id { get; set; }
	[Column("PRIVILEGE_ID")] public string PrivilegeId { get; set; }
}
```

The LINQ query:
```
from notification in _db.Set<Notification>()
join privilege in (from p in _db.Set<Privilege>()
                   where p.ContextId == "NOTIFICATIONS"
                   select p)
     on Convert.ToString(notification.Gkey) equals privilege.Id into privileges
select new { Notification = notification, Privileges = privileges};
```

The produced SQL from the above LINQ query:
```
SELECT "s"."GKEY", "s"."TITLE", "t"."CONTEXT_ID", "t"."ID", "t"."PRIVILEGE_ID", "t"."NotificationGkey"
FROM "NOTIFICATIONS" "s"
OUTER APPLY (
    SELECT "w"."CONTEXT_ID", "w"."ID", "w"."PRIVILEGE_ID", "w"."NotificationGkey"
    FROM "PRIVILEGES" "w"
    WHERE (("w"."CONTEXT_ID" = N'NOTIFICATIONS') AND (CAST("s"."GKEY" AS NVARCHAR2(2000)) = "w"."ID"))
) "t"
ORDER BY "s"."GKEY", "t"."CONTEXT_ID", "t"."ID"
```

The query correctly produced SQL for `Convert.ToString(notification.Gkey) equals privilege.Id` but a non existent field **NotificationGkey** is selected. Removing `"t"."NotificationGkey"` and `"w"."NotificationGkey"` would make the SQL work.

**Comment by jamezamm** [comment]
This issue seems to be caused by a navigation w/o a foreign key declaration "Privileges" in Notification. I have edited the models.

**Comment by jamezamm** [comment]
Decorating the navigation property with a NotMapped attribute will solve the issue.

**Comment by jamezamm** [comment]
Decorating the navigation property with a NotMapped attribute will solve the issue.

**Comment by LouisTrinczek** [comment]
> Decorating the navigation property with a NotMapped attribute will solve the issue.

Is that a wanted behavior or still a bug though? 

I encountered a similar issue and setting NotMapped fixed the wrong SQL Generation errors for me.
