### ISSUE TITLE
Compiled models - execution of Initialize is slow

### ISSUE THREAD

**Issue by muzopraha** [dotnet/efcore#33495]
When running my asp.net core app in release mode, the Initialize call in the ContextModel takes ~20s. I profiled my application using dotTrace and ~90% of the time is spent in `coreclr.dll!ThePreStub`. 
![image](https://github.com/dotnet/efcore/assets/69108030/8b3ca6c1-b6c4-4dbe-8445-2cd0f6928149)

I tried to remove `Relational:RelationalModel`, but improvment wasn't significant. However, I discovered that removing TypeMapping from RuntimeProperty in most of the compiled models greatly improved the execution time.
![image](https://github.com/dotnet/efcore/assets/69108030/a92698c9-bfae-493d-938f-c81cc084d39a)

With this issue compiled models lose their purpose for me. In EF7 compiled models worked fine. Database I use has 500+ tables and 13500+ columns.
Unfortunately I am not allowed to share my project or database, but I try to provide as much assistance as I can.

### Provider and version information

EF Core version: 8.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.9

**Comment by ajcvickers** [comment]
@muzopraha This is something we plan to fix for normal compiled models in 9.0. See also #33483

**Comment by eero-dev** [comment]
> @muzopraha This is something we plan to fix for normal compiled models in 9.0. See also #33483

Will the fix be backported to NET 8?

**Comment by roji** [comment]
@eero-dev we don't know yet - we'll have to discuss how this can be dealt with, and whether a backport to EF 8 is possible will come out of that.
