### ISSUE TITLE
Upgrade The Base Package Of Microsoft Like Humanizer To Net8.0

### ISSUE THREAD

**Issue by AmBplus** [dotnet/efcore#33498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When We Publish Our App On IIS We Got Error 500.0 , We Use Net8.0 And Make Sure To Install Latest Sdk And Runtime , But Still Got This Error On Server , This Was Very Odd Because We Can Lunch On Localhost In Our System , Finally We Decide To Install All Net5.0 To Net8.0, And Our Problem Solved , 
Then After Some Time We Decide To See Why Needed The Net8.0 For Running , And See It , In Release We Try Open deps.json And See Humanizer With Net6.0 , also seen other base library Like Identity Use A Base Package , And That Package Use A Lower Version Of Net6.0 , I Can't Say This is Bug , But I Think Needed A Clear Answer And Document For Publish App On IIS And Check This Packages , And Install Lower Package For Running Project , If Publish App On Folder , This Humanizer Added To Our Project Automaticaly And This Package Use Net6.0 

### Expected Behavior

Upgrade Base Package Or Say Needed Lower Version Of Net8.0 On Production

### .NET Version

Asp.net Core V 8

### Anything else?

    "runtimeTarget": {
    "name": ".NETCoreApp,Version=v8.0",
    "signature": ""
  }
 "Humanizer.Core/2.14.1": {
        "runtime": {
          "lib/net6.0/Humanizer.dll": {
            "assemblyVersion": "2.14.0.0",
            "fileVersion": "2.14.1.48190"
          }
        }
      }

**Comment by AndriySvyryd** [comment]
EF 8 already references the most recent version of Humanizer (2.14.1) - https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/8.0.4#dependencies-body-tab
