### ISSUE TITLE
dotnet ef scaffold with MySql.EntityFramworkCore provider doesn't generate .HasDefaultValue(0)

### ISSUE THREAD

**Issue by teobald** [dotnet/efcore#33506]
At the moment I'm working on a project that is using the database first workflow. The are using mySql database and entity framwork. There are tables with columns that are not null int with default value of 0.

When I run dotnet ef scaffold with the MySql.EntityFrameworkCore provider when applying my migrations that contains defaultvalue: 0 I don't get .HasDefaultValue(0) on my entity property.

This causes problems when running tests locally on a in-memorydatabase. It fails on raw sql inserts that do not contain that column that have a default value since the value was not provided in the insert query.

How to fix so that dotnet ef scaffold generates .HasDefaultValue(0) so that I'm able to run my in-memory database tests?

EF Core version: 6.0.29
MySql.EntiframeworkCore version: 6.0.25
Mircrosoft.EntityFrameworkCore.Sqlite version: 6.0.29
Target framework: .NET 6.0)
Operating system: Visual Studio 2022

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by teobald** [comment]
Table:

CREATE TABLE `voucher` (
  `id` varchar(28) NOT NULL,
  `some_name` varchar(28) DEFAULT NULL,
  `has_something` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

Generated migration class contains this:
id = table.Column<string>(type: "varchar(28)", maxLength: 28, nullable: false),
some_name = table.Column<string>(type: "varchar(28)", maxLength: 28, nullable: false),
has_something = table.Column<int>(type: "int", nullable: false, defaultValue: 0)

Generated dbContext:
entity.Property(e => e.Id).HasMaxLength(28).HasColumnName("id");
entity.Property(e => e.SomeName).HasMaxLength(28).HasColumnName("some_name");
entity.Property(e => e.HasSomething).HasColumnName("has_something"); // I want .HasDefaultValue(0) here!

**Comment by teobald** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

See my updated comment

**Comment by cincuranet** [comment]
The reason you're not seeing the `HasDefaultValue` call is because `0` is default value for CLR type `int` and hence it isn't explicitly scaffolded (as it is the case with other default items).

I suggest trying it with default value of `1`. If it's not in the scaffolded code, then it is likely an issue with _MySql.EntityFrameworkCore_. I did quick check with _Microsoft.EntityFrameworkCore.SqlServer_ and the behavior is like expected (there might still be some bug on our side, in which case, please provide more detailed repro).
