### ISSUE TITLE
Short URL used in error message not definied: efcore-docs-sqlserver-save-changes-and-output-clause 

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/efcore#33519]
EF Core has this error message for the breaking change https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#sqlserver-tables-with-triggers that was introduced in EF Core 7.0:

_Could not save changes because the target table has database triggers. Please configure your table accordingly, see **https://aka.ms/efcore-docs-sqlserver-save-changes-and-output-clause** for more information._

However, this Short URL is not defined and leads to the home page of bing.com with no meaninful results.

### Solution

The Short URL should go to 
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#sqlserver-tables-with-triggers 

### Include provider and version information

EF Core version: 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows

**Comment by roji** [comment]
@ajcvickers I think this link change is because of the change from 7.0 (triggers) to 8.0 (UseSqlOutputClause)...

**Comment by ajcvickers** [comment]
Created the missing aka link.
