### ISSUE TITLE
The EntityFramework package is not installed on project  -Both Installed

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/efcore#3353]
I have a project that uses dnx46 only. It has both EntityFramework.Commands and EntityFramework.SqlServer added and working and a data context (IdentityDbContext)

When I try and run Enable-Migrations or Add-Migration I get the above error.

**Comment by bricelam** [comment]
Per #978, the NuGet Commands don't work on DNX projects. Please use the [DNX Commands](http://www.bricelam.net/2014/09/14/migrations-on-k.html) instead.

**Comment by JohnGalt1717** [comment]
Ok, well the documentation still references nuget, and the dnx commands above say "change directory into the project file" but I'm at a loss as to how you get to a command prompt that has the dnx commands because it doesn't tell you that and just going into either a developer command prompt or straight up and typing dnu or dnx results in command not found. (I'm using Vs.net)

**Comment by bricelam** [comment]
This will put `dnu` and `dnx` on the PATH:
```cmd
dnvm use default
```
We agree it's much harder to use than the NuGet Commands; we're [working with the NuGet](https://github.com/NuGet/Home/issues/1174) and Web Tooling team to enable the Package Manager Console on ASP.NET 5 projects.

**Comment by JohnGalt1717** [comment]
dnvm use default said I need to install default: dnvm install default.

I did that and got a Bad Request response. Don't mind the command prompt stuff, always thought using package manager was a little odd. 

The issue is that it says "command prompt" but doesn't elaborate and that doesn't work by default and there is no instructions on how to make it work and it doesn't work properly in the command window as claimed in Visual Studio with the latest bits.

It either needs to just work, and the documentation updated to tell people to use the command window in Vs.net or there needs to be instructions on how to make it work properly either from a regular command prompt, developer command prompt or from the command window.

**Comment by bricelam** [comment]
Yes, DNX can be hard to grok at times. :frowning: Here is their [getting started page](https://github.com/aspnet/Home). I encourage you to file bugs there and on the [dnx](https://github.com/aspnet/dnx), [dnvm](https://github.com/aspnet/dnvm), and [Tooling](https://github.com/aspnet/Tooling) repos about some of the usability issues you're encountering.

**Comment by JohnGalt1717** [comment]
Ok, now I at least have it working to the point where I can call dnx.  in EF 6 you just set it to your project with the dbcontext and ran it and it would automatically find the startup project (My entities are in a separate project where they belong so it isn't the hello world case).  It doesn't do this and says it can't find startup. When I pass the -s and the name of the start up project it says it was unable to resolve start-up project. But doesn't tell me anything about how it wants the project referenced with the command to work so I'm again stuck.  I'll file bugs like crazy but at the moment I'm just trying to grok how this is supposed to work given the huge lack of documentation. (And all of this stuff should be configured automatically by the tools installer so I don't have to do the whole unix thing just to do a migration... this is literally the reason I don't work on unix.)

**Comment by bricelam** [comment]
`--startupProject` was very broken, as you've found. It's been removed in Beta 8 and we'll bring it back with #2679 when we can make it work. The main issue was that DNX can't load assemblies that aren't listed in you dependencies, but you can't list you startup project as a dependency because it needs to depend on the DbContext and that would cause a circular dependency.

I promise I'll do my best to make the EF Commands not suck on DNX for the RC 1 release. :wink:

**Comment by JohnGalt1717** [comment]
Ok, so no way of making this work as it stands now in Beta 7 (or in beta 8 from what I can tell?)

**Comment by rowanmiller** [comment]
@bricelam to reply with a workaround

**Comment by bricelam** [comment]
@JohnGalt1717, Here is [one use's workaround](http://stackoverflow.com/a/32799213/475031) that might work for you.
