### ISSUE TITLE
Is it possible to opt into faster value reads by skipping null checks?

### ISSUE THREAD

**Issue by colfra-msft** [dotnet/efcore#33544]
I wrote a very simple test application that uses Microsoft.Data.Sqlite and reads from a very large (~130GB) sqlite database that I have locally on an SSD. I also wrote code to run a particular query using both the native sqlite api directly and run the same query in both. The query iterates over 203,375,404 rows, calling GetInt64 three times on each row. The native version of this code does this in 45.6 seconds, while the c# code using Microsoft.Data.Sqlite takes 1.4 minutes. Using the VS profiler I can see that a significant amount of time is checking if each value is NULL before returning the actual value, which I am not doing in the native code. In my database schema I can safely expect NULL to never occur, so is there a way to skip the null checks that are adding so much time, or avoid them some other way? 

![image](https://github.com/dotnet/efcore/assets/128108284/f275e028-58fb-4aee-a0ac-7b78755d4704)

**Comment by maumar** [comment]
There is no way to arbitrarily switch off the null checks, but they should only happen if EF thinks that the projected column is nullable.  Is the column in database marked as nullable, but all rows contain some data? If so you can "lie" about the nullability (by modifying the EF model, setting property to required, even if the database column stays nullable). 
If the value comes from left join, you can rewrite the query to inner join and that should get rid of the nullability as well.
