### ISSUE TITLE
SQLite provider returns 'different' decimal values from SqlServer.

### ISSUE THREAD

**Issue by foggerty** [dotnet/efcore#33543]
Hi all, not sure if this is a bug as such, but it's differing behavior between SQLServer (inc. in-memory) and SqLite (only with in-memory, as we're using it for tests) which is causing us some issues.

Essentially, decimal values come back from SqlServer with an exponent of 123 and a mantissa of 0.  From SqLite they come back with an exponent of 1230 and a mantissa of 1.  Yes, this is fine according to the IEEE spec, but we have a lot of code that assumes SqlServer's behavior, so that when we do something like:

```c#
decimal result = 123;     // pretend this is taken from a DB
return result.ToString(); // API result that will be sent as JSON
```

the user sees `123`.

With SQLite, the user will see `123.0`.  Now, users will never actually see this because it only happens in tests, but it is still breaking a lot of our tests if we want to use SQLite to test instead of the in-memory DB (which we DO).  Note that I'm seeing the same behavior with both .NET 6 and 8.

I thought it may have something to so with the `[Precision(9,0)]` attribute, but as the test below shows, that's not the case.  The output from this is:

```
Test1
123
123

bits[0] 123
bits[0] 0
bits[0] 0
bits[0] 0

Test2
123.0
123.0

bits[0] 1230
bits[0] 0
bits[0] 0
bits[0] 65536
```

```C#
// Packages used:
//      <ItemGroup>
//      	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
//      	<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.4" />
//      	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.4" />
//      	<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.4" />
//      </ItemGroup>


using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

var memContext = InMemoryContext()!;
var sqLiteContext = SQLiteContext()!;
var valFromApi = decimal.Parse("123");
var test = new TestEntity
{
    Id = 1,
    Val1 = valFromApi,
    Val2 = valFromApi,
};

memContext.Add(test);
memContext.SaveChanges();
memContext.ChangeTracker.Clear();

sqLiteContext.Add(test);
sqLiteContext.SaveChanges();
sqLiteContext.ChangeTracker.Clear();

var test1 = memContext.Set<TestEntity>().SingleOrDefault()!;
var test2 = sqLiteContext.Set<TestEntity>().SingleOrDefault()!;

PrintTest(test1, "Test1");
PrintTest(test2, "Test2");

Console.ReadLine();

void PrintTest(TestEntity entity, string header)
{
    Console.WriteLine(header);
    Console.WriteLine(entity.Val1);
    Console.WriteLine(entity.Val2);
    Console.WriteLine();

    var bits = decimal.GetBits(entity.Val1);

    Console.WriteLine($"bits[0] {bits[0]}");
    Console.WriteLine($"bits[1] {bits[1]}");
    Console.WriteLine($"bits[2] {bits[2]}");
    Console.WriteLine($"bits[3
/] {bits[3]}");
    Console.WriteLine();
}

DbContext InMemoryContext()
{
    var options = new DbContextOptionsBuilder<Ctx>()
        .UseInMemoryDatabase("MVR-InMemoryDB").Options;
    var ctx = new Ctx(options);
    
    ctx.Database.EnsureCreated();

    return ctx;
}

DbContext SQLiteContext()
{
    var connection = new SqliteConnection("Filename=:memory:");

    connection.Open();

    var options = new DbContextOptionsBuilder<Ctx>()
        .UseSqlite(connection)
        .Options;

    var ctx = new Ctx(options);
    
    ctx.Database.EnsureCreated();

    return ctx;
}

class TestEntity
{
    public int Id { get; set; }
    
    [Precision(9,0)]
    public decimal Val1 { get; set; }

    [Precision(9, 3)]
    public decimal Val2 { get; set; }
}

class Ctx : DbContext
{
    public Ctx(DbContextOptions options) : base(options) { }

    public DbSet<TestEntity> TestEntities { get; set; }
}
```

Microsoft.Data.Sqlite version: 7.0.18 / 8.0.4
Target framework: .NET 6 / .NET 8
Operating system: Windows 10

**Comment by ajcvickers** [comment]
@bricelam Any thoughts on this?

**Comment by bricelam** [comment]
I believe we had to serialize the “.0” part on SQLite to avoid some places where SQLite was interpreting the values as INTEGER causing incorrect results. I don’t remember the exact details, but I think it was for something basic like the division operator or something. But it might not be needed anymore since we started translating those operators to user-defined functions.

**Comment by bricelam** [comment]
Note, there are a few places in EF where we also assume these values will have the trailing .0 so be very careful if you decide to change this.

**Comment by cincuranet** [comment]
**EF Team Triage:** We're not going to change the behavior. The numbers are correct and compare correctly and when converting to string special care around formatting needs to be taken anyway. Also the change carries non-trivial risk and the reward does not seem to balance it. If other circumstances arise, we are open to reconsidering.
