### ISSUE TITLE
CAST added to every value when doing Contains

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [dotnet/efcore#33563]
Entity C# class.
```C#
[Table("blog")]
public class Blog
{
  [Column("id")]
  public long Id { get; set; }

  [Column("name")]
  public string Name { get; set; }
}
```

Usage,
```C#
public IEnumerable<Blog> GetBogs(List<long> ids)
{
  var blogs = await _dbContext.Blog.Where(x => ids.Contains(x.Id)).ToListAsync();
}
```

The SQL query has something like this,
```SQL
SELECT * FROM blog 
WHERE id in (CAST(1 as BIGINT), CAST(2 as BIGINT), CAST(3 as BIGINT))
```

I was expecting something like this,
```SQL
SELECT * FROM blog 
WHERE id in (1, 2, 3)
```

The data type of the parameter in `GetBlogs` method is `List<long>` and the column is of the same type so why is the `CAST as BIGINT` needed? Is there a way to prevent this?

### Version information

EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2022

**Comment by ErikEJ** [comment]
EF Core 5 is out of support. Have you tried with EF Core 8 - should be a radically different SQL query

**Comment by EmmanuelPonnudurai** [comment]
No. We have plans to upgrade but might take a while. I did read about how new version is using `OPENJSON` to make sure sql query plan cache is reused. In fact I tried to use RawSQL to do same openjson based query. 

I was just curious to understand this behavior and if there is something that I am doing wrong which causes this to happen. 

This is not a pressing issue, Im fine to close it with the said suggestion of moving to EF core 8.

**Comment by maumar** [comment]
EF 8 produces the same query here. EF has a simplistic approach here, it sees literal of type long and asks the type mapping (SqlServerLongTypeMapping) how to render the literal. 

Code there is as follows:

```cs
    protected override string GenerateNonNullSqlLiteral(object value)
        => $"CAST({base.GenerateNonNullSqlLiteral(value)} AS {StoreType})";
```

so that's where the casts are coming from. We are not smart about looking at the context in which the literal is being used. It is unlikely we will change that.
