### ISSUE TITLE
Get all entites of a certain owned entity type

### ISSUE THREAD

**Issue by Maskoe** [dotnet/efcore#33577]
I have this `LocalizedString` type
I configured it as an OwnedEntity. Im using ef core with postgresql and it gets serialized to jsonb nicely.
`modelBuilder.Entity<Question>().OwnsOne(x => x.Text, d => d.ToJson());`

This is probably stupid, but is there any way to query the DB for all "entities" of `LocalizedString`?
`context.Set<LocalizedString>` doesnt work, gives me this exception: https://github.com/dotnet/efcore/issues/29970.
`context.Set<LocalizedString>("LocalizedString")` does the same.

I guess I don't have to query the entire database. Ef knows where I use this type, what entity and what column. 
So it can work in theory, I think... but does it?

```cs
public class Question
{
    public Guid Id { get; set; }
    public LocalizedString Text { get; set; } = new();
}

public record LocalizedString
{
    public string De { get; set; } = "";
    public string En { get; set; } = "";
    public string Bg { get; set; } = "";
    //...
}
```

**Comment by maumar** [comment]
EF doesn't provide any functionality that would help here. You can configure all those entity types at once in the model using https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration, but for queries you need to construct them yourself.

**Comment by roji** [comment]
I might not be understanding the question correctly, but if the question is how to query out all the LocalizedStrings in the database, then you should be able to simply project them out as follows:

```c#
var localizedStrings = await context.Questions.AsNoTracking().Select(q => q.Text).ToListAsync();
```

Re your attempts to use `context.Set<LocalizedString>` - owned entities can only be accessed as part of their owner, and never independently via a DbSet.

**Comment by Maskoe** [comment]
I wanted all "records" of type LocalizedString, from all other entities in all other fields too.
```cs
public class Instruction
{
    public Guid Id { get; set; }
    public LocalizedString Description{ get; set; } = new();
    public LocalizedString Topic{ get; set; } = new();
}

public class Answer
{
    public Guid Id { get; set; }
    public LocalizedString Text { get; set; } = new();
}
```
So I wouldnt have to write 3 queries for this and extend it every time I add a new field or entity, but only one.

But yea, I guessed it wouldnt be possible.

**Comment by roji** [comment]
@Maskoe OK, in that case @maumar understood your question better, and that's indeed not possible. You should really think of owned entities as being part of their owners, so there's no way to reference them that's not via those owners.
