### ISSUE TITLE
Add ServiceCollection extension method for removing a DbContext or its options

### ISSUE THREAD

**Issue by michaeltg17** [dotnet/efcore#33571]
When creating integration tests for a project with ASP.NET Core, you probably want to modify the already registered DbContext with your options for testing. So for example, you may want to change the connection string or enable sensitve data logging.

To do so you you cannot just call again AddDbContext with your new options, as they are registered with TryAdd. You have to mess with serviceDescriptors and remove the options for that DbContext (once you know that removing the descriptor for DbContext is not what you need). 

Code sample:

```
        public static IServiceCollection RemoveDbContextOptions<TContext>(this IServiceCollection services) where TContext : DbContext
        {
            var serviceDescriptor = services.Single(d => d.ServiceType == typeof(DbContextOptions<AppDbContext>));
            services.Remove(serviceDescriptor);
            return services;
        }
```

```
                services.RemoveDbContextOptions<AppDbContext>();
                services.AddDbContext<AppDbContext>(options => options.EnableSensitiveDataLogging());
```

An extension method like the previous one could help in this case for removing DbContexts or its options when needed.

**Comment by ajcvickers** [comment]
@AndriySvyryd Is there any connection between this and the config changes you made for Aspire? I'm inclined to backlog this unless you think otherwise.

**Comment by AndriySvyryd** [comment]
Yes, https://github.com/dotnet/efcore/pull/32518 adds `ConfigureDbContext` that is meant for this scenario, it will override any existing conflicting configuration.
