### ISSUE TITLE
migrations options "-startupProject" is removed

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#3360]
In beta7 it was possible to specify an separate startup project for the application when running the `dnx ef migrations add Init -startupProject MyStartupProject`.

Today I tested with beta8-15922 and the `-startupProject` was not there any more. (Removed here: https://github.com/aspnet/EntityFramework/commit/448170f732116607bf4a464e627988f0874317dd#diff-b8c39a3f7fffa559788354a8e675e20eL186)

How can I use migrations with an db context that not exists in the same project as the startup/configuration code?

**Comment by bricelam** [comment]
It was mostly broken. It will be re-enabled with #2679
