### ISSUE TITLE
Issue with retrieving migrations in Microsoft.EntityFrameworkCore.Tools 8.0.1 and above

### ISSUE THREAD

**Issue by IlyaCherkasov1** [dotnet/efcore#33606]
In the provided code, both migrations and pendingMigrations variables will be empty collections, resulting in the Migrate() method not applying any migrations.

```C#
public class DatabaseEntriesInstaller : IServiceInstaller
{
    public void InstallServices(IServiceCollection services, IConfiguration configuration)
    {
        using var scope = services.BuildServiceProvider().CreateScope();
        var migrations = scope.ServiceProvider.GetService<ApplicationDbContext>()!.Database.GetMigrations();
        var pendingMigrations = scope.ServiceProvider.GetService<ApplicationDbContext>()!.Database.GetPendingMigrations();
        scope.ServiceProvider.GetService<ApplicationDbContext>()!.Database.Migrate();
    }
}
```

![image](https://github.com/dotnet/efcore/assets/51474856/6f9fa5a3-042a-4894-a252-1754cac8fd16)

However, if the Microsoft.EntityFrameworkCore.Tools version is, for example, 8.0.0, everything works as expected:
![image](https://github.com/dotnet/efcore/assets/51474856/693d0dea-2a3c-4bc1-9c19-5be09e8f227e)

### provider and version information

EF Core version: 8.0.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 8.0)
Operating system: JetBrains Rider 2024.1.1

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
