### ISSUE TITLE
Using OrderBy on property that was resolved using double ternary operator.

### ISSUE THREAD

**Issue by cts-tradeit** [dotnet/efcore#33607]
**Current behaviour**

Sample query from DebugView (the query is way bigger but this is the part that causes the problem):
```csharp
DbSet<AccountingJournal>()
    .Select(journal => new OverviewAccountingJournalMappingSource{ 
        Worker = journal.WorkerAccountingId != null ? <>c__DisplayClass1_0.workers
            .SingleOrDefault(w => w.AccountingId == journal.WorkerAccountingId) : journal.WorkerEnterpriseId != null ? <>c__DisplayClass1_0.workers
            .SingleOrDefault(w => w.EnterpriseId == journal.WorkerEnterpriseId) : null, 
    )
    .Select(dtoOverviewAccountingJournalMappingSource => new OverviewAccountingJournalWebDto{ 
        WorkerSurname = dtoOverviewAccountingJournalMappingSource.Worker.Surname, 
    }
    )
    .OrderByDescending($it => $it.WorkerSurname)
    .ThenBy($it => $it.Id)
    .Skip(TypedLinqParameterContainer<int>.TypedProperty)
    .Take(TypedLinqParameterContainer<int>.TypedProperty)
```

Produces:
System.InvalidOperationException: The LINQ expression 'DbSet<AccountingJournal>()
    .OrderByDescending(a => a.WorkerAccountingId != null ? DbSet<Worker>()
        .Where(w => w.AccountingId == a.WorkerAccountingId)
        .SingleOrDefault() : a.WorkerEnterpriseId != null ? DbSet<Worker>()
        .Where(w0 => w0.EnterpriseId == a.WorkerEnterpriseId)
        .SingleOrDefault() : null.Surname)' could not be translated

**Comment by cts-tradeit** [comment]
Provider being used is npgsql.

**Comment by roji** [comment]
@cts-tradeit please take the time to create a minimal, runnable code sample (e.g. a console program) - the above is a very partial snippet without a full exception etc.

**Comment by cts-tradeit** [comment]
sorry, i have been busy and forgot about this, will deliver by the end of this week

**Comment by cincuranet** [comment]
Closing as no repro was provided.
