### ISSUE TITLE
Can I add an arbitrary UPDATE statement within SaveChanges' transaction?

### ISSUE THREAD

**Issue by tyler-boyd** [dotnet/efcore#33617]
## Ask a question

I have a use case where I'm trying to update a related entry when saving. I tried doing this with an `ISaveChangesInterceptor` which sorta works but it appears that the update query is not run inside the transaction that SaveChanges creates.

For example:

```cs
public class PurchaseRecordUpdateSequenceInterceptor : ISaveChangesInterceptor
{
    public async ValueTask<InterceptionResult<int>> SavingChangesAsync(DbContextEventData eventData,
        InterceptionResult<int> result,
        CancellationToken cancellationToken = new())
    {
        if (eventData.Context is null) throw new InvalidOperationException("Somehow context is null");
        //Find any entities which are updated are type of IHasPurchaseId
        var modifiedPurchaseIds = eventData.Context.ChangeTracker.Entries()
            .Where(x => x is
            {
                Entity: IHasPurchaseId,
                State: EntityState.Added or EntityState.Modified or EntityState.Deleted
            }).Select(e => e.Entity as IHasPurchaseId).WithoutNulls().Select(s => s.SourcePurchaseId).Distinct().ToList();

        //Iterate through each modified entities Purchase Id
        foreach (var purchaseId in modifiedPurchaseIds)
        {
                await eventData.Context.Set<Purchase>()
                    .Where(p => p.SourcePurchaseId == purchaseId)
                    .ExecuteUpdateAsync(
                        b => b.SetProperty(p => p.RecordUpdateSequence, p => p.RecordUpdateSequence + 1),
                        cancellationToken: cancellationToken);
        }

        return result;
    }
}
```

Is there a way I can have my UPDATE query run within the same transaction as SaveChanges? Or is my only option to manually create a transaction (which is very complicated as a transaction may or may not exist, meaning we must create a transaction or a save point, right?)

### Include provider and version information

EF Core version: 8.0.4
Database provider: `Npgsql.EntityFrameworkCore.PostgreSQL` v8.0.0
Target framework: net8

**Comment by AndriySvyryd** [comment]
> Or is my only option to manually create a transaction (which is very complicated as a transaction may or may not exist, meaning we must create a transaction or a save point, right?)

Yes, this would be the recommended way of doing it.
