### ISSUE TITLE
The instance of entity type 'XXXX' cannot be tracked because another instance with the key value 'XXX' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

### ISSUE THREAD

**Issue by luisf350** [dotnet/efcore#33629]
I'm getting that particular issue trying to update an entity.
I try to add .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking) in DataContext but didn't work.
Also do same thing in Repository class. My can update the record the 1st time, but, if I want to perform anothe modification for same entity I got that error.

In other to analyze the issue, I create a WPF solution with same issue but, in this case, Im having the problem the 1st time trying to update:
![image](https://github.com/dotnet/efcore/assets/103292693/624d1370-4a35-4f70-bffa-9bb6d5ff188e)
[EFCore.zip](https://github.com/dotnet/efcore/files/15144178/EFCore.zip)

**Comment by archer87pl** [comment]
Do you have optional relationship defined? If yes then please take a look at https://github.com/dotnet/efcore/issues/33610

**Comment by luisf350** [comment]
Hi @archer87pl 
No. As you can see in the solution that I attach, there is only 1 entity defined so, no relationships on it

**Comment by ajcvickers** [comment]
@luisf350 The code creates a single instance of your `DbContext` type in `MainWindowViewModel` and then uses this for evermore. Instead, create a new context instance for each unit-of-work.

**Comment by luisf350** [comment]
Hi @ajcvickers 
In my code, I don't have any implementation of DbContext directly on MainWindowViewModel. I'm using the Domain, which also uses the Repository that uses the DbContext.
Now, I have changed the registration type for DbContext. Instead of having it as Singleton, I tried with Scoped and Transient to get the same result.
Were you able to perform an update with the given solution?

**Comment by ajcvickers** [comment]
@luisf350 The way you are using D.I. means that, as far as I can tell, you will never get more than one `DbContext` instance, because it is only (indirectly) requested from the service provider once.

**Comment by ajcvickers** [comment]
@luisf350 It's hard to say because you know what your intention is. All I would say is that, if you are going to do a repository, with or without D.I., then make sure it is set up so that it does not re-use the same context instance for multiple unit-of-work. Also, don't just call `Update` to mark everything as modified--this is rarely the best pattern. Consider reading [the docs on change tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more information.
