### ISSUE TITLE
Generalize the restriction on executing Include methods on query provider

### ISSUE THREAD

**Issue by cervengoc** [dotnet/efcore#33636]
There's a library called [MockQueryable](https://github.com/romantitov/MockQueryable) which supports mocking `IAsyncQueryable` instances, allowing us to write unit tests against business logic which uses EFCore queries. However, there's currently no way of catching `Include/ThenInclude` extension method calls, because the underlying query provider is only called when it's an instance of `EntityQueryProvider`.

Indeed this makes sense, as it won't do anything on a Linq-to-Objects query provider at runtime. Although, allowing a custom query provider to receive these calls would allow this testing library to capture the calls and for example make them assertable in a unit test.

I suggest introducing a simple marker interface like `IIncludableQueryProvider`, which would mark that a query provider can support these methods and it should receive these `CreateQuery` calls. Then check for this interface instead of the quite robust `EntityQueryProvider` base class. This would open the gates for custom query providers to still make use of these method calls.

In my fork I've prepared the simple commit to implement this change, I'm happy to add a pull request in case of approval.

**Comment by roji** [comment]
Any reason not to have your mocked provider simply extend EntityQueryProvider, rather than implement a special new interface?

**Comment by cervengoc** [comment]
@roji Thank you for the quick response. Inheriting from `EntityQueryProvider` was definitely an initial idea. However, it receives an `IQueryCompiler` as constructor argument, which receives a dozen other abstractions as dependencies, which are all wired up in the dependency injection integration. The referred library is kind of a lightweight mocking tool, and setting up an entire underlying EF is I think not a good option.

**Comment by roji** [comment]
> However, it receives an IQueryCompiler as constructor argument, which receives a dozen other abstractions as dependencies [...]

I'm probably missing something, but the idea would be to provide a mocked IQueryCompiler as well - which dependencies are you thinking of and where do they get in the way exactly?

**Comment by cervengoc** [comment]
I'll have another, deeper look into it. My guess was that the compiler instance is most likely widely used in the internal code of this base class, and using the real base class in this tool would probably introduce more difficoulties than success.

**Comment by cervengoc** [comment]
@roji Thank you for pointing me to the right direction. I've realized that the `EntityQueryProvider` class has all of its members as `virtual`, so it's indeed should be possible to inherit from that and still mock it in this sense.
