### ISSUE TITLE
Are Async Gets now the recommended standard?

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#33647]
Quick question came up when I noticed you example in #33644 @roji ...
Should we be "as best practice" using async for all EF interactions "at scale" now?

I have tended to use the synchronous variants historically except for actions that make changes to the DB (all but the R in CRUD).

I've seen various takes on this question but curious to hear your take on it.

**Comment by ajcvickers** [comment]
@TehWardy Yes, all interactions with the database should be async.

**Comment by TehWardy** [comment]
Thank you @ajcvickers :)
