### ISSUE TITLE
nullability wrong when select is used

### ISSUE THREAD

**Issue by ghosttie** [dotnet/efcore#33656]
If you query an entity with FirstOrDefaultAsync/SingleOrDefaultAsync/etc. the return value has the correct nullability

```C#
var value = await _context.Values
	.SingleOrDefaultAsync();
```

however if you use a Select, the return value is not nullable

```C#
var value = await _context.Values
	.Select(v => v.Id)
	.SingleOrDefaultAsync();
```

In my company we use the pattern of `.Where().Select(x => x.Id).SingleOrDefaultAsync()` a lot, and we still need to cast the id as `int?` in order for it to return the correct thing.  I had been hoping that when the LINQ operators had nullability added that this would be fixed.

EF Core version: 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.9.6

**Comment by roji** [comment]
What exact behavior are you expecting here? EF simply aligns with the regular LINQ-to-Objects behavior, where SingleOrDefaultAsync() returns the CLR default when nothing is found; that's null for `int?` and 0 for `int`. It's not possible for EF to return null for `int` since int isn't nullable.

**Comment by ghosttie** [comment]
I see your point.  I guess I've been treating it as SingeOrNull rather than SingleOrDefault

Wasn't there going to be an overload that let you specify what value to return if there was no result?

**Comment by roji** [comment]
Yes, there's such an overload in LINQ ([docs](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.singleordefault?view=net-7.0#system-linq-enumerable-singleordefault-1(system-collections-generic-ienumerable((-0))-system-func((-0-system-boolean))-0))), but it isn't (yet) supported in EF; see #17783. I'll go ahead and close this issue as part of that; in the meantime, it's usually reasonable to cast to e.g. `int?` and then coalesce to whatever value you want etc.
