### ISSUE TITLE
Query :: make DefaultSqlQueryGenerator more extensible

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#3366]
If one wants to tweak sql generation by overriding DefaultSqlQueryGenerator, they cant use a lot of building blocks since they are private. We should consider opening them up.
- VisitJoin method is private
- NullComparisonTransformingVisitor class is private
- _parameterValues field is private.

**Comment by AndriySvyryd** [comment]
@maumar Is this fixed now?

**Comment by smitpatel** [comment]
Not needed
