### ISSUE TITLE
Neater error message when context type is not explicitly specified.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#33680]
I am experimenting (as usual) with Ef Core.

First, I attempted to add migrations to assembly which does not contain DbContext, and I got a pretty explanationry message:
> No DbContext was found in assembly 'EfMigrationsBundle'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

Then I added a context without a factory, so operation executor is not able to instantiate it. And I got this error:
> Unable to create a 'DbContext' of type ''. The exception 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[AppDbContext]' while attempting to activate 'AppDbContext'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

Sorry, but this `of type ''` is not the best way to [tell me that I have not specified context type explicitly](https://github.com/dotnet/efcore/blob/c349de90d5730a6fea80c71827fa6e29e54bb637/src/EFCore.Design/Design/Internal/DbContextOperations.cs#L209C30-L209C43).

Btw, I agree, naming it as `contextTypeName` would be better =P
![image](https://github.com/dotnet/efcore/assets/9202028/578f2a58-3c77-4b75-b227-ba09cc13cda2)

P.S. Relevant story

A man comes to the doctor.
He greets the doctor and starts to undress. He takes off his shirt, folds it along the seams, fastens the buttons and puts it on the chair. He takes off his T-shirt, folds it neatly and puts it next to his shirt. He took off his shoes and put them under the chair. He took off his socks, smoothed them out and put them next to him. He smoothed out his pants by the arrows and hung them on the back of the chair, took off his underwear, smoothed out the seams too, put them next to his T-shirt and said:
-- You know, doctor, look, I have one testicle a little higher than the other.
-- What's the big deal?
-- What's the big deal?! **It's a little sloppy.**

**Comment by ajcvickers** [comment]
Fixed by #33700
