### ISSUE TITLE
How can i cancel the asp.net core field plus "s" behavior when I execute complex query 

### ISSUE THREAD

**Issue by LZzccc222** [dotnet/efcore#33693]
this is my table including "role","user","roleUser"
![image](https://github.com/dotnet/efcore/assets/60681523/24ac209d-31ab-427b-922a-ce3d9669a30c)
![image](https://github.com/dotnet/efcore/assets/60681523/ad280c07-b617-4183-b9c8-6ed5a6a1859b)
![image](https://github.com/dotnet/efcore/assets/60681523/aed0c21d-61dc-4d3b-8a50-3eb04f979db9)
I use dbfirst method to generate my model entity,I already predict that the generated models don't include skip navigation,,for example,my "User.cs" model doesn't include the Roles Navigation but RoleUsers Navigation,I guess the reason is that I create table "roleUser" add column "id",it doesn't matter for me.
![image](https://github.com/dotnet/efcore/assets/60681523/572eab60-b5bb-4ca1-93e2-2727b173b89b)
The key is that  after I add Roles Navigations mannunaly,I want to get the user related role data by roles navagation directyly,the sql generated by efcore seems that always plus "s" when executed correlated query,but my database field doesn't plus 's',which results the sql execution error.it bothers me very much!!
![image](https://github.com/dotnet/efcore/assets/60681523/0fc3765a-78f3-42e1-baf1-6dcc4cba4493)
![image](https://github.com/dotnet/efcore/assets/60681523/9d31cd61-0f9c-40c5-8c74-a97ad304ed0b)
this is my fluentApi settings about RoleUser.
![image](https://github.com/dotnet/efcore/assets/60681523/9fe4bf2e-b4af-4d82-bcf3-deec82de6193)
thanks for resolving my problem,it's mergency!!

**Comment by ajcvickers** [comment]
Hard to say what is happening without a repro, but it could just be that you have a `DbSet<>` property named "RoleUsers", which is then used by convention as the table name. If this isn't it, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by LZzccc222** [comment]
As picture shows,I generate "user"，"role"，"roleUser"entities  By my database and efcore's reverse engineering ,the entity "user" and "role"don't include mutual skiping navigation property like `    public virtual ICollection<Role> Roles { get; set; } = new List<RoleUser>();` and  `    public virtual ICollection<User> Users { get; set; } = new List<User>();`.
I guess that is caused by the efcore's reverse engineering behavior according to my table structure.But that doesn't matter.What I pay attention to is that I want to add skiping navigation in the '"user" and "Role" entity mannualy and keep the intermidate table navigation at the same time.
```
public partial class Role
{
    public int Id { get; set; }
    public virtual ICollection<RoleUser> RoleUsers { get; set; } = new List<RoleUser>();
}
```
```
public partial class RoleUser
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public int UserId { get; set; }

    public virtual Role Role { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}
```

```
public partial class User
{
    public int Id { get; set; }

    public virtual ICollection<RoleUser> RoleUsers { get; set; } = new List<RoleUser>();

}
```
↓this is code adding skipping navigation mannualy by me.
```
public partial class Role
{
    public int Id { get; set; }
        public virtual ICollection<User> Users{ get; set; } = new List<User>();
    public virtual ICollection<RoleUser> RoleUsers { get; set; } = new List<RoleUser>();
}
```
```
public partial class RoleUser
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public int UserId { get; set; }

    public virtual Role Role { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}
```

```
public partial class User
{
    public int Id { get; set; }
    public virtual ICollection<Role> Roles{ get; set; } = new List<Role>();
    public virtual ICollection<RoleUser> RoleUsers { get; set; } = new List<RoleUser>();

}
```
**the problem is that I use context in my service,when i get user's related role datas by **include()** method,I get error message as below describes ,the error message describes very thoroughly,it seems that the error is caused by  auto-generated sql query,the query add "s"  making "roleId" to be "rolesId" and "userId" to be "usersId," so how can I configure the code to cancel the  sql query? 


```
select * from role join roleUser on role.Id=roleUser.rolesId 
join user on roleUser.usersId=user.id;
```
↓I want auto-generated sql like below not above

```
select * from role join roleUser on role.Id=roleUser.roleId 
join user on roleUser.userId=user.id;
```


```

   public class UserService : IUserService
   {
       private CRMContext _context;
       public UserService(CRMContext context)
       {
           _context = context;
       }

       public User? GetUserInfo(int id)


       {
           var user = _context.Users.Include(u => u.Roles).ToList().SingleOrDefault();
           return user;
       }

   }

```
![image](https://github.com/dotnet/efcore/assets/60681523/7b9d9ff4-51e9-4b34-9c2d-17086c839c6c)
I've done my best to describe my problem,maybe only you can understand what happened and  resolve it .Thanks for resolving my problem!!!

**Comment by LZzccc222** [comment]
!!!!!!!!!

**Comment by ajcvickers** [comment]
@LZzccc222 A couple of things. First, it's notoriously difficult to customize the ASP.NET Core Identity model. It uses a lot of quite obscure mappings. See [Identity model customization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-8.0). I wrote the doc on it, and I still have to refer back to the doc if I need to do it. That being said, this may not be relevant if you're just trying to reverse engineer you own model.

Second, the documentation for mapping many-to-many relationships is here: [Many-to-many](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many). It looks like you're going to need [Many-to-many with navigations and changed foreign keys](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-with-navigations-and-changed-foreign-keys).

**Comment by LZzccc222** [comment]
@ajcvickers  I get what you mean.Thanks for your resolving,I have resolved this problem by referencing efcore doc.
