### ISSUE TITLE
Large performance difference with EF6 join vs EF7 include

### ISSUE THREAD

**Issue by jparish9** [dotnet/efcore#3370]
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-beta7, ASP.NET 6.0.0-beta7

I am seeing a large performance difference for a simple join in EF7 beta7 vs EF6.  Using these models:

``` c#
public class Blog
{
        public int BlogId { get; set; }

        [StringLength(100)]
        public String Name { get; set; }

        public DateTime DateStarted { get; set; }

        public String AuthorName { get; set; }

        public ICollection<Post> Posts { get; set; }
}
```

``` c#
 public class Post
 {
        public int PostId { get; set; }

        public int BlogId { get; set; }

        public Blog Blog { get; set; }

        public DateTime DatePosted { get; set; }

        public String PostHtml { get; set; }
  }
```

Join code for EF6:

``` c#
session.All<Post>().Join(session.All<Blog>(), b => b.BlogId, p => p.BlogId,
                (post, blog) => new TestModel {
                    Post = post,
                    Blog = blog
                }).ToList();
```

Which generates SQL:

``` sql
SELECT 
[Extent1].[PostId] AS [PostId], 
[Extent1].[BlogId] AS [BlogId], 
[Extent1].[DatePosted] AS [DatePosted], 
[Extent1].[PostHtml] AS [PostHtml], 
[Extent2].[BlogId] AS [BlogId1], 
[Extent2].[AuthorName] AS [AuthorName], 
[Extent2].[DateStarted] AS [DateStarted], 
[Extent2].[Name] AS [Name]
FROM  [dbo].[Post] AS [Extent1]
INNER JOIN [dbo].[Blog] AS [Extent2] ON [Extent1].[BlogId] = [Extent2].[BlogId]
```

vs. EF7 join code:

``` c#
_dbContext.Posts.Include(b => b.Blog).ToList();
```

Which generates SQL:

``` sql
SELECT [b].[PostId], [b].[BlogId], [b].[DatePosted], [b].[PostHtml], [b0].[BlogId], [b0].[AuthorName], [b0].[DateStarted], [b0].[Name]
FROM [Post] AS [b]
INNER JOIN [Blog] AS [b0] ON [b].[BlogId] = [b0].[BlogId]
```

Both have similar execution plans, and with test data of 100 blogs and 100 posts per blog, run in a fraction of a second from SQL Server Management Studio.  The EF6 query also runs in a fraction of a second.  However, the EF7 query takes several seconds and causes IIS to garbage collect a number of times while it is running.

Here is the SQL Server Profiler output.  The EF6 query is first, followed by the EF7 one:

![capture](https://cloud.githubusercontent.com/assets/3588675/10351986/1955a9d6-6d12-11e5-8b03-52f6b08fcb85.PNG)

Obviously this example is contrived, joining from many to few, but the actual code we have requires a similar join - starting from a cross-reference table and `.Include`ing to multiple source tables, where we are also seeing this performance issue.

**Comment by anpete** [comment]
@jparish9 Thanks for the detailed report.

Can you please try adding AsNoTracking() - That might tell us more about where the problem lies.

**Comment by jparish9** [comment]
@anpete That seems to be the culprit.

```c#
_dbContext.Posts.Include(b => b.Blog).AsNoTracking().ToList();
```

shows similar performance to EF6.

**Comment by rowanmiller** [comment]
@jparish9 we are already tracking this slow down as part of https://github.com/aspnet/EntityFramework/issues/3308. The benchmark that covers this scenario is https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Microbenchmarks/Query/SimpleQueryTests.cs#L182 and we are seeing a similar slowdown to the numbers you have posted here.

**Comment by jparish9** [comment]
Thanks for the update @rowanmiller, in the meantime we can work around it with `.AsNoTracking` where possible.

**Comment by rowanmiller** [comment]
@jparish9 `AsNoTracking()` should only be used when the results are read-only... the change tracker won't be tracking the objects, so no changes to any of the properties will be detected. For read-only queries AsNoTracking()` will always give you better performance since it avoids setting everything up in the change tracker.

**Comment by jparish9** [comment]
:+1: This is for a web API so most of the queries returning a large result set are read-only.  Thanks for the heads-up.

**Comment by ahmad-moussawi** [comment]
(y) I think Important note like this, should be mentioned on the docs
