### ISSUE TITLE
Translation for the SQL Server PATINDEX function

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#33702]
SQL Server has [`PATINDEX`](https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16&redirectedfrom=MSDN), which allows getting the index of a LIKE-like pattern (as opposed to just checking whether the pattern matches). EF6 had [`SqlFunctions.PatIndex`](https://learn.microsoft.com/en-us/dotnet/api/system.data.objects.sqlclient.sqlfunctions.patindex?view=netframework-4.8.1).

Raised by @irg1008 in #6159.

**Comment by roji** [comment]
Sure thing, feel free to submit a PR!

**Comment by Ricketiman** [comment]
Thank you @roji! I'd like to share my plan and hopefully receive feedback/insights on whether or not I'm on the right track. Based on the discussion on [6159](https://github.com/dotnet/efcore/issues/6159) and what I have learned from the codebase so far, I believe I should add a new `PatIndex` method to `DbFunctionsExtensions` and add a translation for that method in `SqlServerStringMethodTranslator`. Does that sound right?

**Comment by roji** [comment]
The PatIndex would go on SqlServerDbFunctionsExtensions, not DbFunctionsExtensions, as it's a SQL Server-specific thing. And yeah, implementing the translation in SqlServerStringMethodTranslator makes sense.

**Comment by smnsht** [comment]
Hi, @roji 

I have a working branch (ready for PR) for this issue with a decent number of unity tests. 
(started my work without announcing it) 

In my solution, "PATINDEX" resides with SqlServerFullTextSearchFunctionsTranslator, and handles queries like
```
var result = context.Employees
    .Where(
        c => EF.Functions.PatIndex("%London%", c.City) > 0
            && EF.Functions.PatIndex("%Manager%", c.Title, "Latin1_General_BIN") > 0)
    .FirstOrDefault();
```
I added unit tests similar to those that exist for `EF.Functions.FreeText`, replacing *language* with *collate*. All works.

*SqlServerStringMethodTranslator* translates string methods, like `str.Trim()`, `str.TrimLeft()`, etc...
Can you confirm it is **the place** for patindex?

Shall I move my changes to SqlServerStringMethodTranslator?

**Comment by roji** [comment]
> Shall I move my changes to SqlServerStringMethodTranslator?

Yes. "full text" in the SQL Server context means something very specific ([see docs](https://learn.microsoft.com/en-us/sql/relational-databases/search/full-text-search?view=sql-server-ver16)), and PATINDEX isn't part of that. In any case, where exactly the translator lives isn't very important.
