### ISSUE TITLE
Add analyzer for loading navigation

### ISSUE THREAD

**Issue by RamType0** [dotnet/efcore#33713]
When I am working with EFCore, most popular runtime exception I face is `NullReferenceException` caused by navigation property access.
Non-loaded navigation breaks null-safety C# language feature.
Defining navigation as nullable is not a suitable solution.
Even if navigation property was null, we could not distinguish whether it is just not loaded, or actually doesn't exist.

Code analyzer which checks access for navigation property and whether it is loaded will solve this issue.

**Comment by roji** [comment]
@RamType0 there's no way to reliably know whether a navigation is loaded via static analysis (not in the general case, anyway). For example, a method may receive some entity instance as a parameter; that method can be called from arbitrary call-sites, some of which may have loaded the navigation, others not. Static analysis has no way of understanding that.

IMHO the way to think about it, is that accessing an unloaded navigation is a programmer bug. C# itself allows assigning null to non-nullable reference properties (via the bang operator) - that doesn't "break" null-safety in C# per se; it's the programmers responsibility to track (for those cases) when something can be null and when it can't. Some of this is explained in [these docs](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#required-navigation-properties).

I'm going to go ahead and close this as what you're proposing unfortunately simply isn't possible; but please feel free to post back here and continue the conversation - if needed I can reopen.

**Comment by roji** [comment]
@RamType0 the above code simply implements a getter to throw an exception (InvalidOperationException) when the property isn't loaded; that's the pattern documented in [our docs](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#required-navigation-properties). You're free to do that if you wish, but that has nothing to do with any analyzer. See my comment above on why an analyzer here isn't possible.
