### ISSUE TITLE
dont' even use include method when model is in self-references  relationship

### ISSUE THREAD

**Issue by LZzccc222** [dotnet/efcore#33725]
it's a confusing problem,when I dont' use include method,it even include my "Departments" navigation and "ParentDepartment" navigation datas.So include method is redundant for self-references situation? 
``` 
public partial class Department
{
    public int Id { get; set; }


    public string Name { get; set; } = null!;

    public int? ParentDepartmentId { get; set; }



    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department? ParentDepartment { get; set; }



    public virtual ICollection<User> Users { get; set; } = new List<User>();
}
```
![image](https://github.com/dotnet/efcore/assets/60681523/fe7ea971-0594-4347-a91b-4f13a3fb5e57)

**Comment by ajcvickers** [comment]
@LZzccc222 Include causes related entities to be loaded in the query. For tracking queries, setting of references between entities happens whenever the related entity is tracked. See [Loading related data](https://learn.microsoft.com/en-us/ef/core/querying/related-data/) and [Change tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/).

**Comment by LZzccc222** [comment]
oh!thanks for your resolving,I got it solved. Thanks very much
