### ISSUE TITLE
Post Process / Translate SelectExpression's lack of table

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#33730]
I'm continuing work on this database provider. This particular proprietary database has a requirement to select from a table. An `.All ` query produces not exist(), and I need to append a `from <dummy table>`.

I've found old issues talking about letting it produce the expression tree, and in a `PostProcessor`, translate that to append the dummy table. 

What I did is while post processing `SelectExpression` check `if(selectExpression.Tables.Count() == 0)` but I'm not sure how to append the from. It looks like I could append a `TableExpression`, but it also seems like that would expect a genuine table, with its metadata. In looking at the other Derivatives, they all looked like they mapped to actual things in the database engine.

I've very familiar with the oracle provider, and have seen that it does this very thing,  (well appending from dual where necessary) but as it is closed source... I don't have any other efcore providers to use as reference (not sure how many other db engines require a dummy from statement if no table expression is provided).

EF Core version:
Database provider: (Custom based on efcore 6)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by roji** [comment]
@ronnyek there's [QuerySqlGenerator.GeneratePseudoFromClause](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L332) precisely for this reason - try overriding that.

**Comment by ronnyek** [comment]
@roji Thank you kindly, that got me going perfectly. Also thanks for all the work on npgsql efcore driver... I use that thing heavily =)

**Comment by roji** [comment]
My pleasure, good luck with your work on your provider!
