### ISSUE TITLE
How to fix `The 'X' property 'Y' on entity type 'Z' is configured with a database-generated default` warnings for existing database?

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#33769]
## Ask a question

Related: Probably the same solution as in https://github.com/dotnet/efcore/issues/27332 (add `ValueGeneratedNever()` to configuration - by @ajcvickers), but I don't know if this is correct.

How to fix `The 'X' property 'Y' on entity type 'Z' is configured with a database-generated default` warnings for existing database (initial migration was created with EF 6.2.0) after updating EF Core 7 to 8?

I have 24 warnings for this.

Full warning message:
`
The 'KatalogArtikelStatus' property 'Status' on entity type 'KatalogArtikel' is configured with a database-generated default, but has no configured sentinel value. The database-generated default will always be used for inserts when the property has the value 'Unbekannt', since this is the CLR default for the 'KatalogArtikelStatus' type. Consider using a nullable type, using a nullable backing field, or setting the sentinel value for the property to ensure the database default is used when, and only when, appropriate. See https://aka.ms/efcore-docs-default-values for more information.
`

### Include your code

```C#
public class KatalogArtikel
{
    public KatalogArtikelStatus Status { get; set; }
    public bool NichtRabattfaehig { get; set; }
}

```

```C#
public enum KatalogArtikelStatus
{
    Unbekannt = 0,
    Y,
    X,
}
```

```C#
public class KatalogArtikelConfiguration : IEntityTypeConfiguration<KatalogArtikel>
{
    public void Configure(EntityTypeBuilder<KatalogArtikel> entity)
    {
        entity.Property(e => e.Status).HasDefaultValueSql("((0))"); // FIXME: Add `ValueGeneratedNever()` here?? New warning in EFC8
        // For ValueGeneratedNever() see https://github.com/dotnet/efcore/issues/27332
        entity.Property(e => e.NichtRabattfaehig).HasDefaultValueSql("((0))").ValueGeneratedNever();
    }
}
```

```sql
CREATE TABLE [dbo].[KatalogArtikel](
	[Status] [int] NOT NULL,
	[NichtRabattfaehig] [bit] NOT NULL,
 (...)

ALTER TABLE [dbo].[KatalogArtikel] ADD  DEFAULT ((0)) FOR [Status]
GO

ALTER TABLE [dbo].[KatalogArtikel] ADD  DEFAULT ((0)) FOR [NichtRabattfaehig]
GO
```

### Include provider and version information

EF Core version: 8.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows
IDE: Visual Studio 2022 17.9.7

**Comment by cincuranet** [comment]
You can either hide the message using `optionsBuilder.ConfigureWarnings(x => x.Ignore(RelationalEventId.BoolWithDefaultWarning))` or (better) you can use `HasSentinel` to align with default value in database (`HasDefaultValueSql().HasSentinel()`).

[Here](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#sentinel-values-and-database-defaults) is great description of why you might want to use the sentinel value.
