### ISSUE TITLE
Add a seeding method that can be called form the cli

### ISSUE THREAD

**Issue by jepzen** [dotnet/efcore#33778]
I want to seed my database but not use a migration.
The problem is that if i use a Migration this will be executed on production as well

If i can call something like
     `dotnet-ef database seed `

Then I can develop what data I want to seed in my method. Example early development I want to add some AppUsers but i dont want them to be put in the the Production database and i dont want them to be part of the whole migration history. So i can just run the command to add these data on any db connection i want to seed.

You can also change the content of a seed method as you like without running migrations

This idea is inspired by Ruby On Rails
rails db:seed
https://ninjadevel.com/seeding-database-ruby-on-rails/

**Comment by AndriySvyryd** [comment]
This is now possible with the new `UseSeeding` option in EF 9. It will be called when you run `dotnet ef database update` even if no migration were applied. Would this be enough for your scenario?

**Comment by jepzen** [comment]
Looks like it could do it. Nice. Will try it out later after upgrading to EF9
