### ISSUE TITLE
Usefulness of TagWith() is diminished on SQL Azure "Query Performance Insights" UI - requesting workaround or feature to restore?

### ISSUE THREAD

**Issue by ChairmanMawh** [dotnet/efcore#33772]
I'm trying to use `TagWith()` in a way that is visible in the Azure management panel for tracking query performance

After using TagWith extensively but finding its comments conspicuously absent in Azure's Query Performance Insights pane, it seems to me that Azure is doing something to the query text before surfacing it up in the management panel

I've done a test using a query intensive enough to show in Azure:

![image](https://github.com/dotnet/efcore/assets/118385137/9e378522-6e82-4e85-ae7a-a60f563bf56a)

On the right is SSMS used to run the query. On the left, some minutes later is what Azure claims ran

Clearly we can see that Azure seems to be trimming/cropping some part of the query text off.. I think I've a Hawaiian snowball's chance of getting Azure to change that... 

..but i've noticed that comments make it through if theyre positioned after the SELECT

I think the Azure portal might use the `dm_exec_query_stats.statement_start_offset` etc to crop the query string, but this is only a guess. I find if I search the web, SO, or ask AI for a "how can i see long running queries in azure" the answers tend to have a construct that crops the string - perhaps the people at MS that wrote this part of azure do the same thing

Ergo..

This posting is either a question, or a feature request:

As a _question_:  what can I do right now, hacky as you like, to tweak the format of the generated SQL so that there is at least a SELECT (or some no-op) that defeats the cropping mechanism Azure seems to be apply? Can I use something like an interceptor right now, with no code changes from EF team, to alter the SQL text that is sent to the DB to move this comment?

As a _feature request_: could we have a nice easy way of defining/changing the order? A context options bool of "place tagwith after select keyword" ?

**Comment by cincuranet** [comment]
I'll bring the feature request up on team's design meeting.

Regarding the hacky way, probably easiest way is you can use `IDbCommandInterceptor` ([docs](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors)) and change the query text.

**Comment by ErikEJ** [comment]
Query Performance Insights relies on query store, and I am guessing it is by design that the query store avoids storing comments (to avoid bloat)

**Comment by roji** [comment]
This seems like basically the same issue as #20105, where SQL Server also strips leading comments (that's closed, not sure if there's another open issue tracking this). The suggested [workaround](https://github.com/dotnet/efcore/issues/20105#issuecomment-586717777) would be to simply move the comment to somewhere inside the SELECT (and possibly switch to /* */ commenting).

**Comment by cincuranet** [comment]
**EF Team Triage:** We're not going to change the implementation at the moment. We feel the workaround with `IDbCommandInterceptor` is good enough. We'll however ping relevant people around _Query Performance Insights_ for visibility.
