### ISSUE TITLE
Sqlite.FunctionalTests intermittently crash on MacOS

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#33785]
The test logs are not produced because the process is terminated.

Observed on macOS 11.7.10

 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/MSBuildTemprunner/tmpe990ec18cc40402fb44271051b7b73cd.exec.cmd: line 2: 12678 **Segmentation fault: 11**  "/Users/runner/work/1/s/.dotnet/dotnet" exec --depsfile "/Users/runner/work/1/s/artifacts/bin/EFCore.Sqlite.FunctionalTests/Release/net9.0/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.deps.json" --runtimeconfig "/Users/runner/work/1/s/artifacts/bin/EFCore.Sqlite.FunctionalTests/Release/net9.0/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.runtimeconfig.json" "/Users/runner/work/1/s/.packages/xunit.runner.console/2.6.7-pre.5/tools/netcoreapp2.0/xunit.console.dll" "/Users/runner/work/1/s/artifacts/bin/EFCore.Sqlite.FunctionalTests/Release/net9.0/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.dll" -noautoreporters -xml "/Users/runner/work/1/s/artifacts/TestResults/Release/EFCore.Sqlite.FunctionalTests_net9.0_x64.xml" -html "/Users/runner/work/1/s/artifacts/TestResults/Release/EFCore.Sqlite.FunctionalTests_net9.0_x64.html" > "/Users/runner/work/1/s/artifacts/log/Release/EFCore.Sqlite.FunctionalTests_net9.0_x64.log" 2>&1

**Comment by AndriySvyryd** [comment]
cc @ericsink in case this rings any bells

**Comment by ericsink** [comment]
That looks unfamiliar.  :-(

**Comment by ericstj** [comment]
> Observed on macOS 11.7.10

It might not be worth investigating since OSX 11 is not supported.  Any repros on newer OSX versions?

**Comment by maumar** [comment]
Upgrade to 12 did the trick, tests are now re-enabled - closing.
