### ISSUE TITLE
Full-Text Search not working with Global Query Filter

### ISSUE THREAD

**Issue by phlogan** [dotnet/efcore#33799]
Hello everyone.

Me and my team have been finding trouble to use Full-Text Search (Contains and Freetext) with Global Query Filters in EF Core 8.

For context, we have a web system running in .NET 8 and Entity Framework Core 8. Recently, we have applied a Global Query Filter, which filters all the entities by a "TenantId" in the database (for the record, this "TenantId" is setted dinamically according to the URL). This works just fine and we have now our system operating this way.

The problem is that now we want to use Full-Text Search in certain points and the Global Query Filter is stoping us. For example:
### Works:
**`Db.Product.Where(e => EF.Functions.FreeText(e.Name, search)).ToList()`**
The query generated is something like:
		```DECLARE @__ef_filter__TenantId_0 uniqueIdentifier = '[GUID]';```
		```DECLARE @__search_1 varchar(255) = '[PRODUCTNAMETOSEARCH]';```
		```SELECT [p].[ProductId], [p].Name```
		```FROM [Product] AS [p]```
		```WHERE ([p].[TenantId] IS NULL OR @__ef_filter__TenantId_0 = [p].[TenantId]) AND FREETEXT([p].[Name], @__search_1)```

### Don't works:
**`Db.StoreProduct.Where(e => EF.Functions.FreeText(e.Product.Name, search)).ToList()`**
The query generated is something like:
		`DECLARE @__ef_filter__TenantId_0 uniqueIdentifier = '[GUID]';`
		`DECLARE @__search_1 varchar(255) = '[PRODUCTNAMETOSEARCH]';`
		`SELECT [s].[StoreProductId], [...other columns]`
		`FROM [StoreProduct] AS [s]`
		`INNER JOIN (`
		`	SELECT [p].[ProductId], [p].[Name]`
		`	FROM [Product] AS [p]`
		`	WHERE [p].[TenantId] IS NULL OR @__ef_filter__TenantId_0 = [p].[TenantId]`
		`) AS [t] ON [s].[ProductId] = [t].[ProductId]`
		**`WHERE ([s].[TenantId] IS NULL OR @__ef_filter__TenantId_0 = [s].[TenantId]) AND FREETEXT([t].[Name], @__search_1)`**

As we can see, the generated query is trying to apply FREETEXT to a property that is not exactly the property it should at:
**`AND FREETEXT([t].[Name], @__search_1)`**.

Running this query throws following error:
**"Cannot use a CONTAINS or FREETEXT predicate on column 'Name' because it is not full-text indexed"**

And makes sense as far as **[t].[Name]** is not indexed, the indexed in this case is **[p].[Name]**. So much that if we rearrange the FREETEXT filter to the INNER JOIN, it works:
		`SELECT [s].[StoreProductId], [...other columns]`
		`FROM [StoreProduct] AS [s]`
		`INNER JOIN (`
		`	SELECT [p].[ProductId], [p].[Name]`
		`	FROM [Product] AS [p]`
		**`	WHERE [p].[TenantId] IS NULL OR @__ef_filter__TenantId_0 = [p].[TenantId] AND FREETEXT([p].[Name], @__search_1)`**
		`) AS [t] ON [s].[ProductId] = [t].[ProductId]`
		`WHERE ([s].[TenantId] IS NULL OR @__ef_filter__TenantId_0 = [s].[TenantId])`

We don't know if we did something wrong configuring the Query Filters, but we wonder if there is something that we can do to change this generated query and rearrange the FREETEXT or apply FREETEXT before the Query Filter.

Thanks!

EF Core: 8.0.0 (running in .NET 8)
Database provider: SQL Server
Operating system: Windows 10
IDE for .NET 8: VS 2022 17.8.3

**Comment by phlogan** [comment]
Certainly!

[Here is.](https://github.com/phlogan/EFCore8FullTextIssueExample)

Thank you!

**Comment by phlogan** [comment]
Hello everyone.

We've been using raw queries to overcome this problem, we would like to know if there is any news on this issue!

Thank you!

**Comment by roji** [comment]
This seems like a SQL Server limitation of the FREETEXT function - it is unable to "see through" the subquery and understand that its argument is in fact an indexed column.

The only suggestion that comes to mind is to rewrite the LINQ query in a way which does not result in that column coming out of a subquery. In other words, start your query from Products, apply the FREETEXT function, and then select out the associated StoreProducts:

```c#
Db.Product
    .Where(e => EF.Functions.FreeText(e.Name, search))
    .Select(p => p.StoreProduct)
    .ToList()
```
