### ISSUE TITLE
I want to keep the users navigation and roleUsers navigations at the same time not just users navigation

### ISSUE THREAD

**Issue by LZzccc222** [dotnet/efcore#33803]
I use EFCore reverse engineering to generate code about entity and dbcontext. As following shows,here is entities with role,user generated by reverse engineering ,their relationship is many-to-many .I have already knew that efcore 6.0 have supported implied joining entity types. 

```
public partial class Role
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<User> Users { get; set; } = new List<User>();


}
 
```
```
public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; } = null!;

    public string Name { get; set; } = null!;

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}


```
But now the key is  that I want to mannually add more navagations in Role.class and User.class to satisify this as following describes;

```
public partial class Role
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<RoleUser> RoleUsers { get; set; } = new List<User>();

}
 
```

```
public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; } = null!;

    public string Name { get; set; } = null!;

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();

    public virtual ICollection<RoleUser> RoleUsers{ get; set; } = new List<RoleUser>();
}


```

**Comment by cincuranet** [comment]
I'm not sure what you're asking about, because I don't see question here. But I can guess, and I think [this](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-and-join-table-with-payload) will help you get started with what you're trying to do.

**Comment by LZzccc222** [comment]
@cincuranet Thanks for responsing this for me so quicky,but the question I asked is confusing me very much.I want to descripbe this in more details. I have two entities "Role" and "User"  generated by reverse engineering.The two entites's relationship is many-to-many.But the reverse enginering doesn't include intermidiate entity class 'RoleUser' and so entity user doesn't include navigation 'roleUsers' and entity role doesn't include navigation 'roleUsers'.That is not I want.

**Comment by cincuranet** [comment]
Yes, that is expected from POV of reverse engineering. It is trying to do the minimal mapping. But you can customize your entities after reverse engineering.

**Comment by LZzccc222** [comment]
@cincuranet  So how can I configure the "roles" and "roleUsers" navigation in user.cs and "users" and "roleUsers" navigation in role.cs.It botherd me a lot.

**Comment by cincuranet** [comment]
That's described in the document I linked (you can ignore the `CreatedOn` there).

**Comment by LZzccc222** [comment]
![image](https://github.com/dotnet/efcore/assets/60681523/a1ff324f-f56a-444a-8899-71c4797b2a4e)

**Comment by LZzccc222** [comment]
@cincuranet  
the problem occured.
![image](https://github.com/dotnet/efcore/assets/60681523/4bd9c71c-3db3-48c4-9e1a-c1a483b9a59d)

**Comment by cincuranet** [comment]
If you want to use shared entity (like your dictionary, which would also add indexer properties into the mix), follow [this](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#custom-shared-type-entity-type-as-a-join-entity).
