### ISSUE TITLE
In-memory sqlite crash depending on connection string style

### ISSUE THREAD

**Issue by linde12** [dotnet/efcore#33800]
## In-memory SQLite crashes depending on connection string

I noticed that my in-memory sqlite database would crash occasionally with the following stack trace:

```
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Users'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at System.Data.Common.DbCommand.ExecuteScalarAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /home/<redacted>/Program.cs:line 25
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in /home/<redacted>/Program.cs:line 18
   at Program.<Main>(String[] args)
fish: Job 1, './Boom' terminated by signal SIGABRT (Abort)
```

This is after i've processed thousands of requests, executing the exact same query, towards the very same database.

Interestingly it only seems to happen when i build using `PublishReadyToRun=true`. Initially i tested with a "Web API" application, but then also created a "Console App" and the issue happened there as well.

I have provided a reproducible example below. Setting the environment variable `MODE` to `boom` will set the connection string to the format `SqliteConnectionStringBuilder.cs` prefers. Doing this will, on my machine, cause the application to crash with above exception after around 2.5k inserts with a "Console App" and 25k inserts with a "Web API" (which is also very weird!)

I am building with `dotnet publish myapp.csproj -c Release --os linux --self-contained -o dist`

Setting the `MODE` environment variable to anything other than `boom` will use the "traditional" URI style connection string (see "URI Filenames" at https://www.sqlite.org/c3ref/open.html) and it will, again on my machine, execute all 80k requests without any hiccups.

```C#
using Microsoft.Data.Sqlite;

var connectionString = Environment.GetEnvironmentVariable("MODE") == "boom" ?
    "Data Source=memdb;Mode=Memory;Cache=Shared" :
    "Data Source=file:memdb?mode=memory&cache=shared";

var db = new SqliteConnection(connectionString);
db.Open(); // keep connection open so that our db isnt wiped, see https://www.sqlite.org/inmemorydb.html#sharedmemdb

// setup table
var setupCmd = db.CreateCommand();
setupCmd.CommandText = "CREATE TABLE Users (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);";
setupCmd.ExecuteNonQuery();

// simulate 50k network requests (in reality it only takes a couple of thousands when using a simple Minimal API endpoint)
for (int i = 0; i < 80000; i++)
{
    using (var conn = new SqliteConnection(connectionString))
    {
        conn.Open();
        var insertCmd = conn.CreateCommand();
        insertCmd.CommandText = "INSERT INTO Users (Name) VALUES ('J') RETURNING Id";
        var id = (long)await insertCmd.ExecuteScalarAsync();
        Console.WriteLine(id);
    }
}
```

I am looking at the code over at `src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs` but i am not immediately spotting any issues. We are setting some flags (`flags |= SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE;`) which might be unnecessary (?) when using the [SQLITE_OPEN_URI](https://www.sqlite.org/c3ref/c_open_autoproxy.html) flag but other than that it looks normal to me.

I feel like i am on really thin ice. Is this a dotnet runtime issue? A compile time issue? A Microsoft.Data.Sqlite issue? A sqlite issue? I have no clue, please chime in or point me in the right direction if possible :-)

### Version/OS information

Microsoft.Data.Sqlite version: 8.0.5
Target framework: (e.g. .NET 6.0) .NET 8.0
Operating system: Void Linux

**Comment by bradmarder** [comment]
I can replicate this error consistently with windows and running `dotnet run -c release`. I have very little time to investigate, but here are my findings.

- `using` with `insertCmd` makes no difference
- using sync version `ExecuteScalar` makes no difference
- fails after about 270k iterations, give or take a few thousand
- Process gets stuck and requires killing it manually
- Heisenbug! Making minor unrelated changes makes it succeed 100% of the time, such as simply wrapping the `ExecuteScalar` in a try/catch, or including an if/then statement with `db.Handle?.IsClosed` inside the loop....

I'm going out on a limb and guessing a JIT bug.

**Comment by linde12** [comment]
@bradmarder thank you for verifying my sanity :smile: i agree, the more i think about it the more it makes sense that it would be related to AOT vs JIT with the `PublishReadyToRun=true`

**Comment by cincuranet** [comment]
The problem is that your `db` variable/connection is not used after the "setup" phase. And as the application is running, GC figures out it can dispose it (and it will). 

Simply changing the code to this, to keep `db` alive, fixes it (notice the `db.Close();` at the end).

```csharp
using Microsoft.Data.Sqlite;

var connectionString = Environment.GetEnvironmentVariable("MODE") == "boom" ?
    "Data Source=memdb;Mode=Memory;Cache=Shared" :
    "Data Source=file:memdb?mode=memory&cache=shared";

var db = new SqliteConnection(connectionString);
db.Open(); // keep connection open so that our db isnt wiped, see https://www.sqlite.org/inmemorydb.html#sharedmemdb

// setup table
var setupCmd = db.CreateCommand();
setupCmd.CommandText = "CREATE TABLE Users (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT);";
setupCmd.ExecuteNonQuery();

// simulate 50k network requests (in reality it only takes a couple of thousands when using a simple Minimal API endpoint)
for (int i = 0; i < 80000; i++)
{
    using (var conn = new SqliteConnection(connectionString))
    {
        conn.Open();
        var insertCmd = conn.CreateCommand();
        insertCmd.CommandText = "INSERT INTO Users (Name) VALUES ('J') RETURNING Id";
        var id = (long)await insertCmd.ExecuteScalarAsync();
        Console.WriteLine(id);
    }
}

db.Close();
```

**Comment by linde12** [comment]
@cincuranet yes i noticed if i kept using the original connection, e.g. querying every second or so, it would keep working, but its just weird that `PublishReadyToRun=true` tries to "help" you by killing it. Whats even more weird is why certain connection strings work "better" than other.

I didn't realize that i could just close it after `app.Run()` in my Web API :facepalm: 

Thanks for the help!

**Comment by cincuranet** [comment]
It's not R2R, I can replicate the behavior even without R2R images. For the connection string, maybe one has different defaults than other, I'm not sure from top of my head.

**Comment by cincuranet** [comment]
Provider is not using disposed connection. The example above uses 2 connection. But the first is needed to prevent to keep the inmemory DB, well, in memory.

**Comment by ajcvickers** [comment]
Thanks, got it!
