### ISSUE TITLE
List Of List to JsonB .Net 8

### ISSUE THREAD

**Issue by zN3utr4l** [dotnet/efcore#33805]
I opened this issue (https://github.com/npgsql/efcore.pg/issues/3172) on the github efcore.pg repository, I make a reference here in case there is some maintainer of the npgsql project here too.

there is also a mini repo that reproduces the error.

**Comment by zN3utr4l** [comment]
should I open this as a question?

**Comment by cincuranet** [comment]
This will be handled in _npgsql_'s repository and you already created issue there.
