### ISSUE TITLE
Sensitive data exception logging

### ISSUE THREAD

**Issue by oleksiifilatov236** [dotnet/efcore#33823]
Is it possible to avoid logging sensitive data when logging exceptions or detailed exception information?

When a unique constraint violation SQLException occurs, the message may contain sensitive data (such as email, login, etc.), and Entity Framework will log this information without any way to prevent it.

I have already tried to turn off `EnableSensitiveDataLogging` and `EnableDetailedErrors`, but they didn't help.

EF Core version: 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by ajcvickers** [comment]
@oleksiifilatov236 `SQLException` is not generated or thrown by EF Core--please report this to [SqlClient](https://github.com/dotnet/SqlClient).
