### ISSUE TITLE
Any release notes for 8.0.6 ?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/efcore#33830]
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/8.0.6

**Comment by roji** [comment]
The place to know about what happened in specific patch versions is github, i.e. search for issues closed for the corresponding milestone ([here's the search for 8.0.6](https://github.com/dotnet/efcore/issues?q=is%3Aissue%20state%3Aclosed%20milestone%3A8.0.6)).

I'll go ahead and close this, but post back if you have further questions etc.

**Comment by ajcvickers** [comment]
@SimonCropp As always, the release notes will go https://github.com/dotnet/efcore/releases/. As always, you will need to be patient. And, as Shay says, all the info is already available anyway.

**Comment by SimonCropp** [comment]
thanks guys
