### ISSUE TITLE
Query :: consider Api for include that would allow multiple ThenIncludes chained from a parent Include

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#3384]
When using Include/ThenInclude we always have to start from the root, e.q.

```
People
     .Include(person => person.Benefits)
          .ThenInclude(benefit => benefit.Dates)
     .Include(person => person.Benefits)
          .ThenInclude(benefit => benefit.Messages)
```

This is not ideal for more complex queries with multiple includes/then includes 

@emrs-jm  suggested something like this:

```
People
     .Include(person => person.Benefits)
          .ThenInclude(benefit => benefit.Dates)
          .WithInclude(benefit => benefit.Messages)
```

We should consider it, or something similar

**Comment by rowanmiller** [comment]
**Triage:** Discussed in triage and we feel this just overly complicates things. It also only works to back up a single level, but you still run into cases where you are four levels deep and you can't back up and continue including from the second level.

If we see customers wanting something like this then we would probably go with a nested-closure style API, but we suspect folks will be fine with the API we have.
