### ISSUE TITLE
.Net MAUI App sql Connection for edmx

### ISSUE THREAD

**Issue by hinalpandya** [dotnet/efcore#33863]
Hello,
I am new to .Net MAUI project and looking for suggestion for SQL connection from .Net MAUI app. Can I create Web Api and access it through MAUI app for storing and retrieving data?
you can also suggest any alternate way to0?

**Comment by ajcvickers** [comment]
@hinalpandya You're probably better off [asking the MAUI folks](https://github.com/dotnet/maui). Entity Framework is tricky to get working.
