### ISSUE TITLE
Runtime Relational Model created for both Model and RuntimeModel?

### ISSUE THREAD

**Issue by dsynclabsllc** [dotnet/efcore#33897]
My question has to do with The ModelInitializer creating the relational model for the mutable model - why is it doing that? It doesn't get used at all does it? All of the downstream systems would be reading from the runtime relational model. Any customization done by builders would be done during the mutable model build up, through annotations.

FYI - you can take the gloves off in your explanations as I am pretty familiar with a lot of EF core internals.

**Comment by dsynclabsllc** [comment]
So I accidently hit enter while typing part of the question title out... sorry about that. But my question has to do with The ModelInitializer creating the relational model for the mutable model - why is it doing that? It doesn't get used at all does it? All of the downstream systems would be reading from the runtime relational model. Any customization  done by builders would be done during the mutable model build up, through annotations.

FYI - you can take the gloves off in your explanations as I am pretty familiar with a lot of EF core internals.

**Comment by dsynclabsllc** [comment]
To clarify, I am talking specifically about these lines from the RelationalModelRuntimeInitializer - what benefit is there is running through the relational model here? And why would it be a runtime annotation? Wouldn't the mutable model only contain regular annotations?
```csharp
protected override void InitializeModel(IModel model, bool designTime, bool prevalidation)
{
    if (prevalidation)
    {
        model.SetRuntimeAnnotation(RelationalAnnotationNames.ModelDependencies, RelationalDependencies.RelationalModelDependencies);
    }
    else if (model.FindRuntimeAnnotation(RelationalAnnotationNames.RelationalModel) == null)
    {
        RelationalModel.Add(
            model,
            RelationalDependencies.RelationalAnnotationProvider,
            (IRelationalTypeMappingSource)Dependencies.ModelDependencies.TypeMappingSource,
            designTime);
    }
}
```

**Comment by AndriySvyryd** [comment]
That's a valid question. And it's why I changed it to be lazy in https://github.com/dotnet/efcore/commit/9527e8ac879e0209dfdc3d2da5c8b64699d2dc2c

**Comment by dsynclabsllc** [comment]
I take it this did not get merged into the final build. It looks like the change is not going to be integrated - what was the reason for skipping it? Did you find a design requirement that forced you to revert your changes?

**Comment by AndriySvyryd** [comment]
It's in 9.0.0: https://github.com/dotnet/efcore/blob/release/9.0/src/EFCore.Relational/Infrastructure/RelationalModelRuntimeInitializer.cs#L66-L72

It's still a runtime annotation because the model must be readonly to create the relational model.

**Comment by dsynclabsllc** [comment]
> It's in 9.0.0: https://github.com/dotnet/efcore/blob/release/9.0/src/EFCore.Relational/Infrastructure/RelationalModelRuntimeInitializer.cs#L66-L72
> 
> It's still a runtime annotation because the model must be readonly to create the relational model.

Ok, thanks. I was confused because the issue was listed as "Not Planned", so it threw me off.
