### ISSUE TITLE
Issue with Generating Migrations for Multiple Indexes with Different Filters

### ISSUE THREAD

**Issue by Astimus** [dotnet/efcore#33911]
When attempting to generate migrations for a DbContext containing two indexes with different filters but the same set of columns, only one of the indexes is included in the generated migration. 

```C#
modelBuilder.Entity<MyEntity>()
    .HasIndex(r => new { r.Identifier1, r.Identifier2, r.Identifier3, r.MyType })
    .HasDatabaseName("IX_MyEntities_Identifier1_Identifier2_Identifier3_MyType_User")
    .HasFilter($"{nameof(MyEntity.EntityType)} = {MyEntityType.User}");

modelBuilder.Entity<MyEntity>()
    .HasIndex(r => new { r.Identifier1, r.Identifier2, r.Identifier3, r.MyType })
    .HasDatabaseName("IX_MyEntities_Identifier1_Identifier2_Identifier3_MyType_Group")
    .HasFilter($"{nameof(MyEntity.EntityType)} = {MyEntityType.Group}");
```

According to documentation this issue has been resolved in EntityFramework 5.0. [From the documentation](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#index-obsolete):

> Multiple indexes are now allowed on the same set or properties. These indexes are now distinguished by a name in  the model. By convention, the model name is used as the database name; however it can also be configured independently using HasDatabaseName.

Entity Framework Core .NET Command-line Tools: 8.0.6
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 8.0.2
Target framework:  .NET 8.0
Operating system: macOS Sonoma 14.5
IDE: JetBrains Rider 2024.1.2

**Comment by roji** [comment]
HasDatabaseName() isn't what you're looking for; [as per the docs](https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#index-naming-and-multiple-indexes), try the following:

```c#
modelBuilder.Entity<MyEntity>()
    .HasIndex(r => new { r.Identifier1, r.Identifier2, r.Identifier3, r.MyType }, "Index1")
    .HasFilter($"{nameof(MyEntity.EntityType)} = {MyEntityType.User}");

modelBuilder.Entity<MyEntity>()
    .HasIndex(r => new { r.Identifier1, r.Identifier2, r.Identifier3, r.MyType }, "Index2")
    .HasFilter($"{nameof(MyEntity.EntityType)} = {MyEntityType.Group}");
```
