### ISSUE TITLE
Cannot use an interceptor with NetTopologySuite.EF for MSSQL

### ISSUE THREAD

**Issue by statler** [dotnet/efcore#33910]
Implementing any interceptor when using NetTopologySuite breaks on reading Geometry type properties. 
1. Remove the interceptor and the data operations perform as expected. 
2. Query non-spatial data and operations are as expected.

Is it something I need to add to my interceptor to use the NTT, or is it just a bug? If the latter, a more helpful message would be appreciated.

Appears to be similar  to #32707

```
Unable to cast object of type 'cpDataORM.Models.UtcDbDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.

System.InvalidCastException

Stack Trace:
   at lambda_method1391(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at cpDataServices.Services.PlanService.GetConfigsCore(Boolean sync, Int32 planId, Boolean inclData) in C:\Users\dennisg\source\repos\civilpro-api-development\cpDataServices\Services\PlanService.cs:line 351
   at cpDataServices.Services.PlanService.GetConfigsWithData(Int32 planId) in C:\Users\dennisg\source\repos\civilpro-api-development\cpDataServices\Services\PlanService.cs:line 347
   at CivilPro.UI.WinForms.Plans.popImageAnnotation.LoadConfigsFromDb() in C:\Users\dennisg\source\repos\civilpro-api-development\CivilPro.UI.Winforms\Plans\popImageAnnotation.cs:line 88
   at CivilPro.UI.WinForms.Plans.popImageAnnotation.RefreshFormDataSources() in C:\Users\dennisg\source\repos\civilpro-api-development\CivilPro.UI.Winforms\Plans\popImageAnnotation.cs:line 76
   at CivilPro.UI.WinForms.ControlsEf.cpForm_base.InitDataSources() in C:\Users\dennisg\source\repos\civilpro-api-development\CivilPro.UI.Winforms\ControlsEf\cpForm_base.cs:line 62
   at CivilPro.UI.WinForms.Plans.popImageAnnotation..ctor(Int32 PlanId) in C:\Users\dennisg\source\repos\civilpro-api-development\CivilPro.UI.Winforms\Plans\popImageAnnotation.cs:line 60
   at CivilPro.UI.WinForms.mdicPlans.GvPlan_DoubleClick(Object sender, EventArgs e) in C:\Users\dennisg\source\repos\civilpro-api-development\CivilPro.UI.Winforms\Plans\mdicPlans.cs:line 53
   at DevExpress.XtraGrid.Views.Base.BaseView.RaiseDoubleClick(EventArgs e)
   at DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.OnDoubleClick(MouseEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnDoubleClick(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnDoubleClick(EventArgs ev)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

```C#
using Microsoft.EntityFrameworkCore.Diagnostics;
using System;
using System.Collections;
using System.Data;
using System.Data.Common;
using System.Data.SqlTypes;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace cpDataORM.Models
{
    public class UtcInterceptor : DbCommandInterceptor
    {
        /// <summary>
        /// ProjectTimezone is used to set the timezone on the current thread for values returned from the database. It is only
        /// effective if DateTranslationSettingRead is set to DateTranslationEnum.ProjectTimezone
        /// </summary>
        ILoginContextAccessor _logincontext;
        TimeZoneInfo ProjectTimezone => _logincontext.Timezone;

        public UtcInterceptor(ILoginContextAccessor logincontext)
        {
            _logincontext = logincontext;
        }

        public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result, CancellationToken cancellationToken = default)
        {
            var _cx = eventData.Context as ICpContext;
            ReaderExecutingPreProcess(_cx, command);
            return base.ReaderExecutingAsync(command, eventData, result, cancellationToken);
        }

        public override InterceptionResult<DbDataReader> ReaderExecuting(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
        {
            var _cx = eventData.Context as ICpContext;
            ReaderExecutingPreProcess(_cx, command);
            return base.ReaderExecuting(command, eventData, result);
        }

        private static void ReaderExecutingPreProcess(ICpContext _cx, DbCommand command)
        {
            if (cpContext.ShouldTranslateDates && _cx.DateTranslationSettingQuery == DateTranslationEnum.UTC && command.CommandText.StartsWith("SELECT"))
            {
                foreach (DbParameter dbParameter in command.Parameters)
                {
                    if (dbParameter.Value is DateTime dtLocal)
                    {
                        if (dtLocal == SqlDateTime.MinValue.Value || dtLocal == SqlDateTime.MaxValue.Value) continue;
                        if (dtLocal.Kind != DateTimeKind.Utc)
                        {
                            dbParameter.Value = dtLocal.ToUniversalTime();
                        }
                    }
                }
            }
        }

        public async override ValueTask<DbDataReader> ReaderExecutedAsync(DbCommand command, CommandExecutedEventData eventData, DbDataReader result, CancellationToken cancellationToken = default)
        {
            var _cx = eventData.Context as ICpContext;
            await base.ReaderExecutedAsync(command, eventData, result, cancellationToken);
            if (result != null && !(result is UtcDbDataReader))
            {
                if (cpContext.ShouldTranslateDates && _cx.DateTranslationSettingRead != DateTranslationEnum.None)
                {
                    result = new UtcDbDataReader(result, ProjectTimezone, _cx.DateTranslationSettingRead);
                }
            }
            return result;
        }

        public override DbDataReader ReaderExecuted(DbCommand command, CommandExecutedEventData eventData, DbDataReader result)
        {
            var _cx = eventData.Context as ICpContext;
            base.ReaderExecuted(command, eventData, result);
            if (result != null && !(result is UtcDbDataReader))
            {
                if (_cx.DateTranslationSettingRead != DateTranslationEnum.None)
                {
                    result = new UtcDbDataReader(result, ProjectTimezone, _cx.DateTranslationSettingRead);
                }
            }
            return result;
        }


    }


    class UtcDbDataReader : DelegatingDbDataReader
    {
        DateTranslationEnum _dateTranslationSetting;
        TimeZoneInfo _projectTimezone;
        public UtcDbDataReader(DbDataReader source, TimeZoneInfo projectTimezone, DateTranslationEnum dateTranslationSetting) : base(source)
        {
            _dateTranslationSetting = dateTranslationSetting;
            _projectTimezone = projectTimezone;
        }
        public UtcDbDataReader(DbDataReader source) : base(source) { }
        public override DateTime GetDateTime(int ordinal)
        {
            if (_dateTranslationSetting == DateTranslationEnum.UTC)
                return DateTime.SpecifyKind(base.GetDateTime(ordinal), DateTimeKind.Utc).ToLocalTime();
            else if (_dateTranslationSetting == DateTranslationEnum.ProjectContext)
            {
                var dt = DateTime.SpecifyKind(base.GetDateTime(ordinal), DateTimeKind.Utc);
                return TimeZoneInfo.ConvertTimeFromUtc(dt, _projectTimezone);
                //return dt;
            }
            else return base.GetDateTime(ordinal);
        }
    }

    public abstract class DelegatingDbDataReader : DbDataReader
    {
        readonly DbDataReader source;
        public DelegatingDbDataReader(DbDataReader source)
        {
            this.source = source;
        }
        public override object this[string name] { get { return source[name]; } }
        public override object this[int ordinal] { get { return source[ordinal]; } }
        public override int Depth { get { return source.Depth; } }
        public override int FieldCount { get { return source.FieldCount; } }
        public override bool HasRows { get { return source.HasRows; } }
        public override bool IsClosed { get { return source.IsClosed; } }
        public override int RecordsAffected { get { return source.RecordsAffected; } }
        public override bool GetBoolean(int ordinal) { return source.GetBoolean(ordinal); }
        public override byte GetByte(int ordinal) { return source.GetByte(ordinal); }
        public override long GetBytes(int ordinal, long dataOffset, byte[] buffer, int bufferOffset, int length) { return source.GetBytes(ordinal, dataOffset, buffer, bufferOffset, length); }
        public override char GetChar(int ordinal) { return source.GetChar(ordinal); }
        public override long GetChars(int ordinal, long dataOffset, char[] buffer, int bufferOffset, int length) { return source.GetChars(ordinal, dataOffset, buffer, bufferOffset, length); }
        public override string GetDataTypeName(int ordinal) { return source.GetDataTypeName(ordinal); }
        public override DateTime GetDateTime(int ordinal) { return source.GetDateTime(ordinal); }
        public override decimal GetDecimal(int ordinal) { return source.GetDecimal(ordinal); }
        public override double GetDouble(int ordinal) { return source.GetDouble(ordinal); }
        public override IEnumerator GetEnumerator() { return source.GetEnumerator(); }
        public override Type GetFieldType(int ordinal) { return source.GetFieldType(ordinal); }
        public override float GetFloat(int ordinal) { return source.GetFloat(ordinal); }
        public override Guid GetGuid(int ordinal) { return source.GetGuid(ordinal); }
        public override short GetInt16(int ordinal) { return source.GetInt16(ordinal); }
        public override int GetInt32(int ordinal) { return source.GetInt32(ordinal); }
        public override long GetInt64(int ordinal) { return source.GetInt64(ordinal); }
        public override string GetName(int ordinal) { return source.GetName(ordinal); }
        public override int GetOrdinal(string name) { return source.GetOrdinal(name); }
        public override string GetString(int ordinal) { return source.GetString(ordinal); }
        public override object GetValue(int ordinal) { return source.GetValue(ordinal); }
        public override int GetValues(object[] values) { return source.GetValues(values); }
        public override bool IsDBNull(int ordinal) { return source.IsDBNull(ordinal); }
        public override bool NextResult() { return source.NextResult(); }
        public override bool Read() { return source.Read(); }
        public override void Close() { source.Close(); }
        public override T GetFieldValue<T>(int ordinal) { return source.GetFieldValue<T>(ordinal); }
        public override Task<T> GetFieldValueAsync<T>(int ordinal, CancellationToken cancellationToken) { return source.GetFieldValueAsync<T>(ordinal, cancellationToken); }
        public override Type GetProviderSpecificFieldType(int ordinal) { return source.GetProviderSpecificFieldType(ordinal); }
        public override object GetProviderSpecificValue(int ordinal) { return source.GetProviderSpecificValue(ordinal); }
        public override int GetProviderSpecificValues(object[] values) { return source.GetProviderSpecificValues(values); }
        public override DataTable GetSchemaTable() { return source.GetSchemaTable(); }
        public override Stream GetStream(int ordinal) { return source.GetStream(ordinal); }
        public override TextReader GetTextReader(int ordinal) { return source.GetTextReader(ordinal); }
        public override Task<bool> IsDBNullAsync(int ordinal, CancellationToken cancellationToken) { return source.IsDBNullAsync(ordinal, cancellationToken); }
        public override Task<bool> ReadAsync(CancellationToken cancellationToken) { return source.ReadAsync(cancellationToken); }
        public override int VisibleFieldCount { get { return source.VisibleFieldCount; } }
    }

    public enum DateTranslationEnum
    {
        None,
        UTC,
        ProjectContext
    }
}

```

### Include provider and version information

EF Core version: 7.0.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer)
Target framework:.NET 7.0
Operating system: win10
IDE: e.g. Visual Studio 2022 17.5

**Comment by roji** [comment]
You can define an interceptor, but you can't just return an arbitrary DbDataReader - EF expects it to be a SqlDataReader. If you're trying to change the DateTime Kind of values coming back from the database, a value converter is likely a much better way to achieve that - see [these docs](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#specify-the-datetimekind-when-reading-dates) for a similar sample.

**Comment by statler** [comment]
Thanks Roji

Leaving the question of valueconverters aside for the moment (my code runs common on an EF6 and EFCore instance and these aren't available for EF6 - which is not a problem for this ticket, just my reason for this not being my first choice)

1. You can return a DbDataReader and it works unless the NetTopologySuite types are being used. Is it just because of NTS?
2. If EF expects an SqlDataReader, how can this be supplied seeing as the docs state the class cannot be inherited?

**Comment by roji** [comment]
> Surely there is some kind of way to deal with the NTS specific issue?

Unfortunately not, as far as I'm aware. In the general case, EF may require provider-specific features from the DbDataSource, meaning that you can't always swap it out and expect everything to work.

I'd recommend reviewing the requirement for applying timezone conversions that vary based on the context instance - though I understand and appreciate that there are legacy considerations. Otherwise you can deal with this outside of EF, post-processing loaded instances.

Pinging @ajcvickers in case he has other ideas/solutions here.

**Comment by ajcvickers** [comment]
Agree with everything @roji said.

**Comment by statler** [comment]
> In the general case, EF may require provider-specific features from the DbDataSource

Yet, with the exception of one line of code in a single feature specific library (NTS), it doesn't. I have constructed an entire application over 10 years and multiple different version of EF and not had an issue using the dbdatareader. My code worked in EF6 and in EFCore right up until I tried to use NTS. A review of the EF Code base literally shows this single instance of an sqldatareader. Rather than locking it to an **uninheritable** class, why not use an interface?

If the code needs a provider-specific feature, surely this only requires a contract, not a specific immutable, un-substitutable and uninheritable class? Of all the options, that literally seems the worst.

> I'd recommend reviewing the requirement for applying timezone conversions that vary based on the context instance - though I understand and appreciate that there are legacy considerations. Otherwise you can deal with this outside of EF, post-processing loaded instances.

If this was 10 years ago, then I would agree. Both options are non-starters. This is a massive monolithic application with hundreds of entities, similar numbers of services. It serves to two UIs - one desktop and one Web. The latter isn't a problem for what dates get served, but the desktop editors (and there are 1000s of them) and the reporting for both all require datetime values based on the database. It simply isn't practical to refactor without committing massive resources to it. The path of least resistance here is seriously to fork my own version of EF which is a maintenance PITA.

The context in converters feature which is in the top 25 upvoted features would have been perfect and I have been looking at that as a better solution for a couple of years, but it isn't implemented and doesn't look like it will be anytime soon, so I can't really hang out for that. Its not often you arrive at a total dead end without even an ugly workaround, but here we are.

**Comment by statler** [comment]
OK - not going to get into the whys and wherefores except to suggest that maybe a contract would be a better way to do this - e.g. an interface rather than requiring an uninheritable, immutable and un-instantiable class like SqlDataReader? In my case I can actually create an explicit cast annotation to the dbdatareader, but unfortunately the NTS attempted cast mustn't be direct because it still throws an exception. Thought I had an easy out for a moment.

Could you advise where the attempt to cast the dbDataReader is actually happening in the NTS code so I can further explore my options? These will likely include forking the library and referencing the original SqlDataReader which is a property of my dbDataReader. In my case redesign just isn't an option. This is a monolithic app with 10 years of dev legacy. It feeds the API (which isn't an issue as it transmits in UTC anyway), a reporting and desktop UI. The latter are massive issues as there are hundreds of entity types, hundreds of forms and 94 reports, all of which need their datetime in a specific timezone. The only reliable way to do this until now without handwriting transformations for every date in every grid and editor in each form has been with a 1 page interceptor. It just makes no sense to introduce literally thousands of failure points and pages upon pages of boilerplate code to individually set the time every time a date is displayed.

I don't have the luxury of waiting for the addition of the context to the valueconverters which probably wont happen for years.

**Comment by roji** [comment]
> Could you advise where the attempt to cast the dbDataReader is actually happening in the NTS code so I can further explore my options?

The requirement is [here](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs#L25) in the EF NTS plugin for SQL Server; in a nutshell, the plugin reads SQL Server spatial data as raw bytes from SqlClient - via the SqlDataReader.GetSqlBytes() API; SqlClient unfortunately doesn't expose spatial types in a good way, so the EF plugin accesses the raw bytes data via SqlDataReader.GetSqlBytes() and hands it off to NetTopologySuite for parsing.

I'm not sure why GetSqlBytes() specifically is needed (and the SqlBytes type) rather than a simple byte[] - I suspect it has something to do with the SQL Server geometry types being a "user-defined type" (UDT) in SQL Server. If you can find a way to make this work by reading the spatial data as a simple byte[], then the regular, standard `DbDataReader.GetFieldValue<byte[]>()` API can be used instead, removing the need for SqlDataReader specifically. If that happens, I think we'd happily accept a PR removing this dependency.

> not going to get into the whys and wherefores except to suggest that maybe a contract would be a better way to do this - e.g. an interface around the SqlDataReader rather than requiring an uninheritable, immutable and un-instantiable class like SqlDataReader?

I don't really see what EF can do here, given that it needs to call SqlClient's SqlDataReader.GetSqlByte() method; SqlDataReader is part of SqlClient which isn't part of EF. If an ISqlDataReader existed inside SqlClient, we'd be able to use it, but that creates its own problems (e.g. adding a new method to SqlDataReader would require adding it to the interface too, at which point either all current users of ISqlDataReader are broken because they don't implement it, or there's a default implementation which throws, which also isn't good).

> The only reliable way to do this until now without handwriting transformations for every date in every grid and editor in each form has been with a 1 page interceptor.

To get more context, what exactly has been working until now and what has changed?

**Comment by statler** [comment]
Hi Roji

Thanks for your continued engagement on this. To answer the easy one first - the only thing that has changed in my application is that I have a new requirement to manage spatial data, so I added NTS and 'boom'.

I have actually got a modestly ugly hack that gives me a working solution for anyone just wanting to get this to work.  So no-one has to read through above, I summarize the options and the hack here.

**My preferred options to this hack would be:**
1. Use ValueConverters with context support. When this feature is available, I will definitely refactor my code to this solution (refer https://github.com/dotnet/efcore/issues/12205). This totally avoids this issue and the need for a [quite dicey] interceptor.
2. Refactor NTS to not require GetSqlBytes and thus remove the requirement on Microsoft.Data.SqlClient.SqlDataReader. I have not done this because a quick look at GetSqlBytes was _ugly_ and I don't have the resources to get into an alternative when I have a quick way out.

**The hack**
This only works because I actually do use SQL server, and my reader is of type SqlDataReader when passed into my interceptor.

1. Do the following to your dbDataReader class:
- Add a new field 
``` SqlDataReader sqlDataReader;```
- Add a new method
``` public SqlBytes GetSqlBytes(int i) => sqlDataReader?.GetSqlBytes(i);```
- Populate the new field in your constructor(s)
```if (source is SqlDataReader sdr) sqlDataReader = sdr;```

2. This is the ugly bit. I replace the service implementation for NTS. This messes with non-public APIs so is not upgrade safe and can be brittle. Use at your own risk.

```
using cpDataORM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using NetTopologySuite;
using NetTopologySuite.Geometries;
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Reflection;

public static class NTSReplacement
{
    /// <summary>
    /// When using an interceptor that replaces the dbdatareader, NTS will throw an exception. Refer https://github.com/dotnet/efcore/issues/33910
    /// This is a workaround that redirects the SqlDataReader required by NTS to the original SqlDataReader from the interceptor.
    /// The implementation works by replacing the SqlServerGeometryTypeMapping class with a descendant the overrides _getSqlBytes
    /// 
    /// To implement, instead of using b=>b.UseNetTopologySuite, call b=>NTSReplacement.AddNetTopologySuiteBuilder(b)
    /// 
    /// Note that this requires a public property in the interceptor as per the linked issue.
    /// 
    ///WARNING: This solution uses internal APIs and will need to be reviewed with each NTS update.
    public static void AddNetTopologySuiteBuilder(SqlServerDbContextOptionsBuilder builder)
    {
        builder.UseNetTopologySuite();
        builder.UseNetTopologySuiteHack();
    }

    public static SqlServerDbContextOptionsBuilder UseNetTopologySuiteHack(this SqlServerDbContextOptionsBuilder optionsBuilder)
    {
        DbContextOptionsBuilder optionsBuilder2 = ((IRelationalDbContextOptionsBuilderInfrastructure)optionsBuilder).OptionsBuilder;
        var extension = optionsBuilder2.Options.FindExtension<SqlServerNetTopologySuiteOptionsExtensionReplacer>() ?? new SqlServerNetTopologySuiteOptionsExtensionReplacer();
        ((IDbContextOptionsBuilderInfrastructure)optionsBuilder2).AddOrUpdateExtension(extension);
        return optionsBuilder;
    }
}

public class SqlServerNetTopologySuiteOptionsExtensionReplacer : SqlServerNetTopologySuiteOptionsExtension
{
    public override void ApplyServices(IServiceCollection services)
        => services.Replace(ServiceDescriptor.Transient<IRelationalTypeMappingSourcePlugin, SqlServerNetTopologySuiteTypeMappingSourcePluginReplacement>());
}

public class SqlServerNetTopologySuiteTypeMappingSourcePluginReplacement : SqlServerNetTopologySuiteTypeMappingSourcePlugin
{
    private readonly HashSet<string> _spatialStoreTypes = new(StringComparer.OrdinalIgnoreCase) { "geometry", "geography" };

    private readonly NtsGeometryServices _geometryServices;

    public SqlServerNetTopologySuiteTypeMappingSourcePluginReplacement(NtsGeometryServices geometryServices) : base(geometryServices)
    {
        _geometryServices = geometryServices;
    }

    public override RelationalTypeMapping? FindMapping(in RelationalTypeMappingInfo mappingInfo)
    {
        var clrType = mappingInfo.ClrType;
        var storeTypeName = mappingInfo.StoreTypeName;

        var _result = typeof(Geometry).IsAssignableFrom(clrType)
            || (storeTypeName != null
                && _spatialStoreTypes.Contains(storeTypeName))
                ? (RelationalTypeMapping)Activator.CreateInstance(
                    typeof(SqlServerGeometryTypeMappingReplacement<>).MakeGenericType(
                        clrType is null || clrType == typeof(SqlBytes) ? typeof(Geometry) : clrType),
                    _geometryServices,
                    storeTypeName ?? "geography")!
                : null;
        return _result;
    }
}

//Version updates [may] require refresh from
//https://github.com/dotnet/efcore/blob/release/7.0/src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
public class SqlServerGeometryTypeMappingReplacement<TGeometry> : SqlServerGeometryTypeMapping<TGeometry> where TGeometry : Geometry
{
    private static readonly MethodInfo _getSqlBytes
    = typeof(UtcDbDataReader).GetRuntimeMethod(nameof(UtcDbDataReader.GetSqlBytes), new[] { typeof(int) })!;

    public SqlServerGeometryTypeMappingReplacement(NtsGeometryServices geometryServices, string storeType)
        : base(geometryServices, storeType)
    {
    }

    protected SqlServerGeometryTypeMappingReplacement(
        RelationalTypeMappingParameters parameters,
        ValueConverter<TGeometry, SqlBytes>? converter)
        : base(parameters, converter)
    {

    }

    public override MethodInfo GetDataReaderMethod()
        => _getSqlBytes;
}
```

**Comment by roji** [comment]
Thanks for posting your workaround for this @statler.

I'll go ahead and close this issue at this point, as unfortunately I don't think there's anything actionable on our side (besides #12205). This is generally the result of problematic spatial support at the SqlClient level intersecting with what I'd consider a rather problematic requirement in your application (which I understand cannot be changed for legacy reasons etc.).
