### ISSUE TITLE
NET single powerful standard

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/efcore#33923]
EF, ADO, Dapper, etc Standardization in a single ef ? 
Is it possible to merge code branches into a single powerful standard?

**Comment by EvgenyPrikhodko** [comment]
For example, make a branch of EFCore or EF Life etc…

**Comment by EvgenyPrikhodko** [comment]
the goal is to put in order the minimum set of requirements. Enable the ability to use attributes in complex queries.

**Comment by roji** [comment]
@EvgenyPrikhodko I'm not sure what you're asking... EF, ADO and Dapper are three different APIs/products, which serve different needs - there's no intention to "unify" them. I also don't know what you're referring to with "EF Lite".

**Comment by EvgenyPrikhodko** [comment]
@roji The main problem is there is no single entry point. Third-party libraries live their own world.

**Comment by EvgenyPrikhodko** [comment]
@roji Since Microsoft specialists know the features of NET, I ask you to create a standard within the framework of EF

**Comment by roji** [comment]
@EvgenyPrikhodko I honestly am not sure what you're asking for here.

In general, I don't believe there should be "a single entry point" (nor am I sure what that means). For accessing databases, some people want a low-level API where they can write their own SQL - so they use Dapper or ADO. Others want a higher-level ORM which maps their .NET types and generates SQL for them - so they use EF. Different people and different scenarios have different solutions/products, and that's not a problem - it's a strength.

If you'd like to continue this conversation, please post a concrete suggestion. Saying "there
