### ISSUE TITLE
Migrations ignore IsRequred(true) in configuration (extending IdentityUser)

### ISSUE THREAD

**Issue by JohnyL** [dotnet/efcore#33929]
I'm extending IdentityUser by adding following properties:
```cs
public class AppUser : IdentityUser
{
  public string Locale { get; set; } = "en-GB";
  public string? OrgId { get; set; }
  public bool IsAdmin { get; set; }
}
```

Overriding `OnModelCreating`:
```cs
protected override void OnModelCreating(ModelBuilder builder)
{
  base.OnModelCreating(builder);
  builder.HasDefaultSchema("auth");
  builder.Entity<AppUser>(builder =>
  {
    builder
    .HasIndex(p => p.Locale)
    .IsUnique(false);
    builder
      .Property(p => p.Locale)
      .HasColumnName("Locale")
      .HasColumnType("nvarchar(10)")
      .IsRequired(true);
    builder
      .Property(p => p.IsAdmin)
      .HasColumnName("IsAdmin")
      .HasColumnType("bit")
      .IsRequired(true);
  });
}
```

However, in migrations `IsAdmin` and `Locale` are nullable.
```cs
migrationBuilder.CreateTable(
  name: "AspNetUsers",
  schema: "auth",
  columns: table => new
  {
    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
    Discriminator = table.Column<string>(type: "nvarchar(13)", maxLength: 13, nullable: false),
    Locale = table.Column<string>(type: "nvarchar(10)", nullable: true),
    OrgId = table.Column<string>(type: "varchar(100)", nullable: true),
    IsAdmin = table.Column<bool>(type: "bit", nullable: true),
    // ... other properties
  }
)
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 9.0.100-preview.4.24267.66
Operating system: Windows 10 Home x64 22H2 19045.4474
IDE: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.11.0 Preview 1.1

**Comment by ajcvickers** [comment]
@JohnyL This is because an inheritance hierarchy is being mapping with the default TPH strategy. Columns are made nullable to accommodate instances of types that do not have those properties. See [Entity type hierarchy mapping](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#entity-type-hierarchy-mapping) for more information.

**Comment by JohnyL** [comment]
Thanks! 🙂
