### ISSUE TITLE
Non-generic ValueComparer and ValueConverter

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/efcore#33952]
I'm using `PropertyBuilder<T>.HasConversion(ValueConverter<T, string> ValueComparer<T>)` to implement a custom JSON converter.

I'd like to be able to apply this without using generics, but there doesn't appear to be a non-generic version of ValueConverter and ValueComparer built in - it's just the generic version and then the abstract base class.

The specific use case is that every entity extending a certain interface has a JSON property, so I would like to do e.g.:

```
foreach (var type in builder.Model.GetEntityTypes())
{
    if (type.ClrType.IsAssignableTo(typeof(IExample)))
    {
        builder.Entity(type.ClrType)
            .Property(nameof(IExample.Data))
            .IsJson();
    }
```

But I can't easily write an IsJson extension method for `PropertyBuilder` like I did for `PropertyBuilder<T>` because I can't create instances of ValueConverter and ValueComparer without having the types at compile time.

It seems like ValueConverter<T, string> and ValueComparer could both have been implemented to extend a non-generic base class that accepts a Type parameter in its constructor.

**Comment by ajcvickers** [comment]
@DanielStout5 This is not supported. Value converters and comparers are always strongly typed so that they can be used without boxing.

**Comment by DanielStout5** [comment]
Thanks for the reply @ajcvickers  - do you have any suggestions for an alternative workaround to specify them at runtime?

**Comment by ajcvickers** [comment]
@DanielStout5 Use `MakeGenericType` or similar to construct the appropriate type at runtime.

**Comment by DanielStout5** [comment]
Here's how I ended up handling it:

```
var isJsonMethod = typeof(ModelBuilderExtensions)
    .GetMethod(nameof(ModelBuilderExtensions.IsJson))
    .MakeGenericMethod(typeof(Dictionary<string, object>));

var genericPropertyMethod = typeof(EntityTypeBuilder)
    .GetMethod(nameof(EntityTypeBuilder.Property), 1, new[] { typeof(string) })
    .MakeGenericMethod(typeof(Dictionary<string, object>));

foreach (var type in builder.Model.GetEntityTypes())
{
    if (type.ClrType.IsAssignableTo(typeof(IExample)))
    {
        var genericPropertyBuilder = genericPropertyMethod
            .Invoke(builder.Entity(type.ClrType), new[] { nameof(IExample.Data) });
        isJsonMethod.Invoke(null, new[] { genericPropertyBuilder });
    }
}
```
