### ISSUE TITLE
No relational provider - Entity annotation with default value based on DdContext property

### ISSUE THREAD

**Issue by GLuca74** [dotnet/efcore#33950]
I have a custom provider (no relational) for EFCore and I should add an annotation  on the EntityTypeBuilder. If the user use the annotation extension method, it sets the value and everything is ok, but if the user not set the value throught the extension method, the provider should set a value got from the DBSet property related to the EntityType. For example if the annotation is called Address :

```
public class City
{
	public Guid CityID { get; set; }	
	public string CityName { get; set; }
}

public class TestContextBase :DbContext
{
        protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
            modelBuilder.Entity<City>().HasKey(itm => itm.CityID);
	}

        public DbSet<City> Cities { get; }
}

```
If the user use the extensionMethod :
`            modelBuilder.Entity<City>().WithAddress("Address");
`
all is ok and simply, but If the user omits `WithAddress("Address")`, the provider have to add the annotation using the value got from the `DBSet<City>` property name, in this case `"Cities"`.

Can you please suggest wath is the best way to implement this? whitch service is the best to  override?

Many thanks

**Comment by roji** [comment]
@GLuca74 it's hard to help with so little information about your provider; but overall it sounds like you're looking for "conventions", which is logic that your provider can add to the model-building process which does things by default, but which can be overridden by explicit user configuration. As an example, take a look at [TableNameFromDbSetConvention](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs), which is the convention that derives the relational table name from the DbSet property (for SQL databases).

**Comment by GLuca74** [comment]
Thanks @roji , I had a quick look, in ProviderConventionSetBuilderDependencies I saw ICurrentDbContext so seems the good way.
Can you please let this thread  open so if I need some more help I can write here? If I will complete the task I will write.

Many thanks

**Comment by roji** [comment]
@GLuca74 I'll close this thread as there isn't anything actionable we need to track, but you can still post questions here after it's closed.
