### ISSUE TITLE
Querying all objects of a type hierarchy 

### ISSUE THREAD

**Issue by cronoxyd** [dotnet/efcore#33972]
Is is possible to get all objects of a type hierarchy by querying the base type?

## Background
**Note:** Due to intellectual property restrictions, I'm unable to share my exact code, so I'm providing example code that (hopefully) conveys the essentials.
I have a type hierarchy where the base type (non-abstract) has an explicit type discriminator property and deriving types with additional properties, e.g.:

```csharp
enum VehicleType
{
    Car,
    Truck
}

class Vehicle
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public VehicleType? Type { get; set; }
    public string VehicleIdentificationNumber { get; set; }
    public string ColorCode { get; set; }
}

class Car : Vehicle
{
    public int PassengerCount { get; set; }
}

class Truck : Vehicle
{
    public float CargoSpaceSquareMeters { get; set; }
}
```

I configure the model using the Fluent API:
```csharp
class DealershipContext : DbContext
{
    public DbSet<Car> Cars { get; set; }
    public DbSet<Truck> Trucks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Vehicle>()
            .Property(vehicle => vehicle.Type)
            .HasConversion(
                v => v.ToString(),
                v => Enum.Parse<VehicleType>(v)
            );
        
        modelBuilder
            .Entity<Vehicle>()
            .UseTphMappingStrategy()
            .HasDiscriminator(vehicle => vehicle.Type)
            .HasValue<Car>(VehicleType.Car)
            .HasValue<Truck>(VehicleType.Truck);
    }
}
```

Now if I attempt to get all objects that share the base type `Vehicle` the following exception is thrown:
```text
System.InvalidOperationException: The entity type 'Vehicle' has a discriminator property, but does not have a discriminator value configured.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateDiscriminatorValues(IEntityType rootEntityType)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateInheritanceMapping(IModel model, IDiagnosticsLogger`1 logger)
```

That makes sense, since it doesn't. However, for the convenience of my users I'd like to display all objects that share the base type `Vehicle` and then query the more specific type if and when requested.

My workaround would be to:
1. build a list of all deriving types (using reflection),
1. query all deriving types and then 
1. convert the objects to the base type.

However, I'd much rather configure EF Core to only query the properties required for the base type and instantiate objects of it, effectively ignoring the entire hierarchy (including the discriminator property).

### Provider and version information
EF Core version: 8.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Windows 11 (Enterprise)
IDE: Microsoft Visual Studio 2022 17.10.1

**Comment by roji** [comment]
EF already supports querying all objects of a type hierarchy - just executein `await context.Vehicles.ToListAsync()` should do that. If that's not working for you, we're going to need to see a minimal, runnable code sample - try putting together a simple console program that shows the error you're getting.

> However, I'd much rather configure EF Core to only query the properties required for the base type and instantiate objects of it, effectively ignoring the entire hierarchy (including the discriminator property).

If a row in the database corresponds to a specific Vehicle type - e.g. a Truck - then EF will instantiate a Truck for that; what you end up with is a .NET polymorphic list of Vehicles `List<Vehicle>`, where the actual instances are of varying types. A Truck cannot be instantiating just by querying the properties for the base type (Vehicle) - there are Truck-specific properties as well, and if EF didn't load them, you'd end up with incorrect/invalid Truck objects etc.

In addition, the code above uses TPH (table-per-hierarchy) inheritance mapping, which means that your query will only be querying a single table in any case; there's no particular cost in querying those Truck properties in that scenario, so I'm not sure why you're attempting to "only query the properties required for the base".

**Comment by cronoxyd** [comment]
Certainly, here is an example repo that reproduces the issue: https://github.com/cronoxyd/EFCoreTypeHierarchyExample

Regarding your last remark about the TPH mapping, my intent is to reduce database traffic and processing load. Unless I'm mistaken the following query and subsequent processing should have a lower cost than querying the entire table:
```sql
SELECT Id, Name, Type, VehicleIdentificationNumber, ColorCode
FROM Vehicles
```
Instead of:
```sql
SELECT *
FROM Vehicles
```

**Comment by roji** [comment]
> Regarding your last remark about the TPH mapping, my intent is to reduce database traffic and processing load. Unless I'm mistaken the following query and subsequent processing should have a lower cost than querying the entire table [...]

As I wrote above, EF generates a SELECT with a column list that contains all columns necessary to materialize any Vehicle type (including all of the subtypes). It sounds like you want to "partially" materialize subtypes, i.e. read Truck and Car instances that only have the common properties populated which can be found on Vehicle. In other words, if Truck has some Truck-specific property Foo, that property wouldn't be loaded, and Truck instances would therefore only be partially loaded (they wouldn't represent that actual data in the database).

If so, then EF does not support this. I'd also highly recommend carefully benchmarking rather than assuming that loading those extra  properties represents a meaningful difference in overall application performance. It's certainly possible in some cases, but from what we've seen, in most cases that's not going to be meaninful.

Assigning to @AndriySvyryd for the model-building error you reported above.

**Comment by cronoxyd** [comment]
Ah, I see my initial question was poorly worded. No, I don't want to partially materialize the subtypes. The intended outcome ist a `List<Vehicle>` of uniform type.

At the current stage of the original app, I agree that the difference between materializing the subtypes into a polymorphic list and a uniform List of Vehicle is negligible. But since there is an ASP.NET core host and Blazor client app involved I want to optimize early to achieve good scalability.

**Comment by roji** [comment]
> The intended outcome ist a List<Vehicle> of uniform type.

If something was saved as a Truck or Car to the database, then it cannot be read as a Vehicle. EF behaves here just like normal .NET: you cannot simply change the type of a Truck object to a Vehicle. You can create a new Vehicle instance and copy across the relevant portions, but this isn't something that will be done automatically for you either by EF or by .NET.

> But since there is an ASP.NET core host and Blazor client app involved I want to optimize early to achieve good scalability.

I'd really advise against premature optimization without clear numbers to back up your ideas, that's can lead to all sorts of wrong directions and problematic code.

In any case, if you want to optimize for the data being passed from the server to the Blazor client, the typical (and more robust) way to do that is to control the JSON payload getting sent. In other words, just load regular, full entity types from the database via EF, and then transform those .NET object to a JSON representation which matches your needs. This is better than trying to push that concern into your data layer.

**Comment by cronoxyd** [comment]
I see, thank you for explanation and background!

**Comment by cronoxyd** [comment]
Be advised that my code example and the repo had a mistake in the configuration of the discriminator values:
```diff
modelBuilder
                .Entity<Vehicle>()
                .UseTphMappingStrategy()
                .HasDiscriminator(vehicle => vehicle.Type)
                .HasValue<Car>(VehicleType.Car)
-               .HasValue<Car>(VehicleType.Truck);
+              .HasValue<Truck>(VehicleType.Truck);
```
The issue still persists though.

**Comment by AndriySvyryd** [comment]
If `Vehicle` isn't an instantiable type mark it as `abstract`. Otherwise, you need to define a discriminator value.

**Comment by cronoxyd** [comment]
So I would need to define a discriminator value for Vehicle to get all objects of the hierarchy, even though the database will never contain any objects of this base type?

**Comment by AndriySvyryd** [comment]
> So I would need to define a discriminator value for Vehicle to get all objects of the hierarchy, even though the database will never contain any objects of this base type?

Yes

**Comment by cronoxyd** [comment]
I tested marking the `Vehicle` class in [my example](https://github.com/cronoxyd/EFCoreTypeHierarchyExample) as `abstract`, and indeed it works.
