### ISSUE TITLE
How to re-use expressions in queries?

### ISSUE THREAD

**Issue by torgashov** [dotnet/efcore#33978]
Hello!
Please help to re-use expressions in ef core queries.
We need execute method on database server.
We have this expression:
ctx.Users.Select(i => ctx.UserInApps.First(u => u.UserId == i.UserId).AppCode).ToArray()
This query materialized to sql:
SELECT 
  (
    SELECT 
      "u"."APP_CODE" 
    FROM 
      "USER_IN_APP" AS "u" 
    WHERE 
      "u"."USER_ID" = "t"."USER_ID" 
    LIMIT 
      1
  ) 
FROM 
  "USER" AS "t"

We need extract sub expression into Method for re-using:
ctx.Users.Select(i => GetUserAppCode(i, ctx)).ToArray();
string GetUserAppCode(Models.TchAppUser i, Models.CatalogDbContext ctx)
 {
     return ctx.UserInApps.First(u => u.UserId == i.UserId).AppCode;
 }

This query materialized to sql:
SELECT 
  "t"."USER_ID",
  "t"."LOGIN"   
FROM 
  "USER" AS "t"

Please tell me what is wrong?
Is there any case to re-use part of exression as c# method?

**Comment by cincuranet** [comment]
The call to `GetUserAppCode` is regular function, not an expression (and because it is top level, it will be evaluated locally). Only expressions can be translated to SQL.

You could extract `u => u.UserId == i.UserId`, but not `.First(u => u.UserId == i.UserId).AppCode` nor `ctx.UserInApps.First(u => u.UserId == i.UserId).AppCode`. At least not easily, unless you want to start composing expression trees manually, which is fairly complex topic.

**Comment by torgashov** [comment]
When extract u => u.UserId == i.UserId to function, appears error: Unable to cast object of type 'System.Linq.Expressions.MethodCallExpression1' to type 'System.Linq.Expressions.LambdaExpression'.'

ctx.Users.Select(i => ctx.UserInApps.First(NewMethod(i)).AppCode).ToArray();

private static Expression<Func<Models.UserInApp, bool>> NewMethod(Models.TchAppUser i)
{
    return u => u.UserId == i.UserId;
}

**Comment by cincuranet** [comment]
Right, I missed the `i.UserId` which is from outside, hence you can't have it as a field. That means composing expression trees only.

**Comment by torgashov** [comment]
the same exception, when i use code:
ctx.Users.Select(i => ctx.UserInApps.First(NewMethod(i.UserId)).AppCode).ToArray()

private static Expression<Func<Models.UserInApp, bool>> NewMethod(long userId)
{
    return u => u.UserId == userId;
}

**Comment by torgashov** [comment]
Else one case:
        private static Expression<Func<Models.UserInApp, bool>> NewMethod(long userId)
        {
            return i => i.UserId == userId;
        }

this is works:

 long userId = 1;
 var r = ctx.Users.Select(u => ctx.UserInApps.First(NewMethod(userId)).AppCode).ToArray();

This is not work:

 var r = ctx.Users.Select(u => ctx.UserInApps.First(NewMethod(u.UserId)).AppCode).ToArray();

(Unable to cast object of type 'System.Linq.Expressions.MethodCallExpression1' to type 'System.Linq.Expressions.LambdaExpression)

What is wrong? I don't understand.

**Comment by cincuranet** [comment]
When it's a value - like in `long userId = 1;` then this value is known and it is in the tree. But when you use `u.UserId`, it's effectively a column and the expression tree that C# compiler produces is different (referencing this variable).

**Comment by ajcvickers** [comment]
@torgashov I'm not sure if you're aware, so I apologize if you are, but expression manipulation is a complex area, and not something most people should need to use. It might help to step back and consider if you could achieve this in some other way.

**Comment by torgashov** [comment]
Thank you for your answers.
I tried understand how to re-use expressions or parts of expressions. 
I will rethink ef core using in projects.
I thougth re-using expressions can replace stored procedure when migrate from database first conception to code first.
There was a hope to use expressisons methods, that can be used in complex expressions and generated later into sql when database execution.
Using expressions instead stored procedures.
I was wrong.

**Comment by ranma42** [comment]
@torgashov you might also want to look into some of the [EF Core Tools & Extensions](https://learn.microsoft.com/en-us/ef/core/extensions/).

I am using https://github.com/koenbeuk/EntityFrameworkCore.Projectables in some of my projects to reuse (projectable) query fragments.

Depending on your use case, https://github.com/axelheer/nein-linq might also be worth looking into.

**Comment by roji** [comment]
Duplicate of #31871
