### ISSUE TITLE
Ability to configure DbContextOptionsBuilder via IConfigureOptions/IConfigureNamedOptions

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/efcore#33977]
## Summary

I have tried to use the IConfigureOptions interface to abstract the database context options configuration that is present in the DbContextOptionsBuilder, instead of simply overriding the OnConfiguring method inside the database context, and there is an instance of the DbContextOptions<TContext> in the constructor of the database context class, and I am using the base keyword to use the constructor of the DbContextOptions class. At the moment, an exception is thrown, telling the user to override the OnConfiguring method. I am unsure if these optionsBuilder options, should be moved to the DbContextOptions class, potentially creating breaking changes.

## Motivation and goals

This will add an abstraction layer, that will reduce cyclomatic complexity of any classes that derive from DbContext classes.
Larger projects, with massive amounts of tables in one database will benefit from this.
 

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

N/A

## Risks / unknowns

Unsure.

## Examples

public sealed class ConfigureDbContextOptionsBuilder : IConfigureOptions<DbContextOptionsBuilder<AppDbContext>>
{
    public IConfiguration Configuration { get; }

    public ConfigureDbContextOptionsBuilder(IConfiguration configuration)
    {
        Configuration = configuration;
    }
    
    public void Configure(DbContextOptionsBuilder<AppDbContext> optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(Configuration.GetConnectionStringOrThrow("Default"), opt =>
            {
                opt.EnableRetryOnFailure();
                opt.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery);
            });
        }
    }
}

**Comment by ajcvickers** [comment]
@chris-briddock I'll bring it up with the team, but this looks like something that would be better implemented as an extension. EF is intentionally agnostic about how options are obtained by the app.

**Comment by chris-briddock** [comment]
I know EF is intentionally agnostic. However ot does not fit the design patterns within .NET. All other options classes can be configured with IConfigureOptions or named options. The OptionBuilder, does not actually build an instance of the options class, nor is there a Build method to give you a built version of the options class it is supposed to build.

Thanks,

Chris

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AndriySvyryd** [comment]
Assuming you are using DI, you can already do something like
```C#
.AddDbContext<DbContext>(
    (p, b) => b.UseSqlServer(p.GetRequiredService<IConfiguration>().GetConnectionStringOrThrow("Default"), opt =>
    {
        opt.EnableRetryOnFailure();
        opt.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery);
    })
```

And starting with EF Core 9.0 you can use `ConfigureDbContext` to add configuration to a previous `AddDbContext`. It works by registering `IDbContextOptionsConfiguration<TContext>` that are then applied in order of registration.

We haven't heard many requests to add built-in support for `IConfiguration`, but as @ajcvickers you should be able to create an extension that does it by leveraging the above building blocks.
