### ISSUE TITLE
When is the Find method used?

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/efcore#33987]
Source https://github.com/dotnet/efcore/issues/33986

**Comment by EvgenyPrikhodko** [comment]
Maybe it makes sense to mark it as Obsolete?

**Comment by roji** [comment]
@EvgenyPrikhodko no, Find has its uses; in some cases it's useful to get an entity by its ID, but return a locally cached version that entity was already loaded. That may not fit with what you're specifically doing in #33986.
