### ISSUE TITLE
Entity OwnsOne Value Object Change Tracking Problem

### ISSUE THREAD

**Issue by fahrigoktuna** [dotnet/efcore#33981]
Hi Everyone,

We have an entity named Customer which has a Name Property that is a value Object. I'm sharing the entity value object and their relations and configuration below.

My question is: When I started tracking a customer entity and change the value object property is not considered as modified. I have to force it by calling    (_customersDbContext.Set<BoilerPlate.SampleAPI.Core.Customer>()
.Entry(customer).Member("Name") as ReferenceEntry).TargetEntry.State = EntityState.Modified;

However its not solving my problem becase I need original values of Name field when I changed Name property OriginalValues and CurrentValues setted same values. I want to get original values as getting when I select with traccking records.

Let me sampling:

**### Step 1 (Getting customer Entity)**

```C#
 var  customer= await _customersDbContext.Set<BoilerPlate.SampleAPI.Core.Customer>()
     .FirstOrDefaultAsync(x => x.Id == 41)
```

Name property has firstname 1: lastname: 1 values.

**### Step 2 (Updating Name which is value object property)**

```C#
 customer.Update(
Gender.From(command.GenderId == null ? customer.Gender.Id : command.GenderId.Value),
Name.Of("2", "2"));
```

**### Step 3 (Cheking the original values)**

```C#
 var xxxx  = (_customersDbContext.Set<BoilerPlate.SampleAPI.Core.Customer>().Entry(customer)
     .Member("Name") as ReferenceEntry).TargetEntry.OriginalValues;
```

Firstname and Lastname orginal values are 2 not 1.

How to avoid this problem, please help me thanks in advance

////////

**### Customer.cs**

```C#
 public class Customer : Aggregate<CustomerId>,
{
   private Name _name;

   public Name Name => _name;
}
```

**### Name.cs**

```C#
public class Name : ValueObject
{
    private string _firstName;
    public string FirstName => _firstName;

    private string _lastName;
    public string LastName => _lastName;

    private string _fullName;
    public string FullName => _fullName;

    private Name() { }

    public static Name Of(
        [NotNull] string firstName,
        [NotNull] string lastName)
    {
        if (string.IsNullOrWhiteSpace(firstName) || firstName.Length is > 100 or < 2)
            throw new InvalidNameException(firstName);

        if (string.IsNullOrWhiteSpace(lastName) || lastName.Length is > 100 or < 2)
            throw new InvalidNameException(lastName);

        firstName = RemoveInlineSpaces(firstName);
        lastName = RemoveInlineSpaces(lastName);

        static string RemoveInlineSpaces(string text)
        {
            if (!string.IsNullOrEmpty(text))
                return Regex.Replace(text.Trim(), @" +", " ");
            return null;
        }

        Name customerName = new()
        {
            _firstName = firstName,
            _lastName = lastName,
        };

        customerName.SetFullName();

        return customerName;
    }
```

**### Entity Type Configuration .cs for Customer:**

```C#
builder.OwnsOne(
    x => x.Name,
    a =>
    {
        a.Property(p => p.FirstName)
            .HasColumnName(nameof(Customer.Name.FirstName).Underscore())
            .IsRequired()
            .HasField("_firstName")
            .HasMaxLength(EfConstants.Lenght.Long);

        a.Property(p => p.LastName)
            .HasColumnName(nameof(Customer.Name.LastName).Underscore())
            .IsRequired()
            .HasField("_lastName")
            .HasMaxLength(EfConstants.Lenght.Long);

        a.Property(p => p.FullName)
            .HasColumnName(nameof(Customer.Name.FullName).Underscore())
            .IsRequired()
            .HasField("_fullName")
            .HasMaxLength(EfConstants.Lenght.ExtraLong);
    });
```
EF Core Postgresql version : "Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.18"

Target Framework : .Net 7.0

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by fahrigoktuna** [comment]
Here is the attacthed sample code detailed wtih comment lines.
[EFCoreValueObjectsIssue.zip](https://github.com/user-attachments/files/15827396/EFCoreValueObjectsIssue.zip)

**Comment by ajcvickers** [comment]
@fahrigoktuna `Name` is mapped as an owned typed which means it is a form of entity type. Setting a new instance onto a navigation results in marking the old instance as `Deleted` and the new instance as `Added`. To do what you want with an owned type, you'll need to either mutate the instance, or manually set the values/states. This is why complex types are being introduced.

> But I need a solution for Ef Core 7 Versions

Note that [EF7 is out of support](https://learn.microsoft.com/en-us/ef/core/what-is-new/) as of May 14.

**Comment by fahrigoktuna** [comment]
Thank you @ajcvickers
