### ISSUE TITLE
SQL Server translation of strings in where expressions into parameters

### ISSUE THREAD

**Issue by logiclink** [dotnet/efcore#34000]
Linq ‘where’ statements are translated into SQL ‘where’ clauses with parameters except for string comparisons. In the case of strings the string is embedded in the SQL code without a parameter. This behaviour results in multiple execution plans for every string bloating the cache for plans on the SQL Server:

```C#
List<Post> l = await ctx.Posts.Where(p => p.Title == "can I configure a different theme per category in a BlogEngine.net blog?").ToListAsync();
```
The linq expression results in the SQL:

```SQL
dbug: 15.06.2024 19:05:24.380 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[AcceptedAnswerId], [p].[AnswerCount], [p].[Body], [p].[ClosedDate], [p].[CommentCount], [p].[CommunityOwnedDate], [p].[CreationDate], [p].[FavoriteCount], [p].[LastActivityDate], [p].[LastEditDate], [p].[LastEditorDisplayName], [p].[LastEditorUserId], [p].[OwnerUserId], [p].[ParentId], [p].[PostTypeId], [p].[Score], [p].[Tags], [p].[Title], [p].[ViewCount]
      FROM [Posts] AS [p]
      WHERE [p].[Title] = N'can I configure a different theme per category in a BlogEngine.net blog?'
```
In EF9 this behaviour can be circumvented by the EF.Parameter function:
```C#
List<Post> l = await ctx.Posts.Where(p => p.Title == EF.Parameter("can I configure a different theme per category in a BlogEngine.net blog?")).ToListAsync();
```
The linq expression with EF.Parameter results in a SQL statement with parameters:
```SQL
dbug: 15.06.2024 19:07:52.846 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[@__p_0='?' (Size = 250)], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[AcceptedAnswerId], [p].[AnswerCount], [p].[Body], [p].[ClosedDate], [p].[CommentCount], [p].[CommunityOwnedDate], [p].[CreationDate], [p].[FavoriteCount], [p].[LastActivityDate], [p].[LastEditDate], [p].[LastEditorDisplayName], [p].[LastEditorUserId], [p].[OwnerUserId], [p].[ParentId], [p].[PostTypeId], [p].[Score], [p].[Tags], [p].[Title], [p].[ViewCount]
      FROM [Posts] AS [p]
      WHERE [p].[Title] = @__p_0
```
Is there a reason for not using parameters for stings and it possible to make the parameterized translation the default translation like for integer or DateTime values?

Regards,

Marcus

**Comment by roji** [comment]
This behavior is by design; when you embed a constant/literal into the LINQ query, EF embeds it as a constant/literal in the SQL:

```c#
_ = await context.Blogs.Where(b => b.Id == 8).ToListAsync();
```

... and when you reference a variable, EF uses a SQL parameter:

```c#
var id = 8;
_ = await context.Blogs.Where(b => b.Id == id).ToListAsync();
```

This (roughly) means that for each LINQ query in your code, you get a single SQL, which works for the vast majority of scenarios. Note that embedding constants/literals in SQL can also have significant planning advantages, so just embedding parameters everywhere would be pretty bad for performance.

If you have a lot of different queries where the only difference is the literal string embedded inside, consider refactoring that out and embedding the string as a variable, at which point it'll get parameterized. Otherwise you can explicitly use EF.Parameter() in EF 9.0, or simply extract out a variable like in my example above.

> Is there a reason for not using parameters for stings and it possible to make the parameterized translation the default translation like for integer or DateTime values?

Strings aren't special in any way here, e.g. integers behave in exactly the same way.

**Comment by logiclink** [comment]
This makes absolutely sense as strings within a linq expression are constants thus, will never result in multiple execution plans. After extracting the string into a variable, the SQL uses a parameter by default:
```c#
string s = "can I configure a different theme per category in a BlogEngine.net blog?";
List<Post> l = await ctx.Posts.Where(p => p.Title == s).ToListAsync();
```
gets translated in EF8 and EF9 to
```SQL
dbug: 16.06.2024 10:21:17.917 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[@__s_0='?' (Size = 250)], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[AcceptedAnswerId], [p].[AnswerCount], [p].[Body], [p].[ClosedDate], [p].[CommentCount], [p].[CommunityOwnedDate], [p].[CreationDate], [p].[FavoriteCount], [p].[LastActivityDate], [p].[LastEditDate], [p].[LastEditorDisplayName], [p].[LastEditorUserId], [p].[OwnerUserId], [p].[ParentId], [p].[PostTypeId], [p].[Score], [p].[Tags], [p].[Title], [p].[ViewCount]
      FROM [Posts] AS [p]
      WHERE [p].[Title] = @__s_0
```
Moreover, string expressions with constant parts are translated to the parameterized SQL version also:
```c#
string c = "?";
List<Post> l = await ctx.Posts.Where(p => p.Title == "can I configure a different theme per category in a BlogEngine.net blog" + c).ToListAsync();
```
translates in
```SQL
dbug: 16.06.2024 10:26:23.590 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[@__p_0='?' (Size = 250)], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[AcceptedAnswerId], [p].[AnswerCount], [p].[Body], [p].[ClosedDate], [p].[CommentCount], [p].[CommunityOwnedDate], [p].[CreationDate], [p].[FavoriteCount], [p].[LastActivityDate], [p].[LastEditDate], [p].[LastEditorDisplayName], [p].[LastEditorUserId], [p].[OwnerUserId], [p].[ParentId], [p].[PostTypeId], [p].[Score], [p].[Tags], [p].[Title], [p].[ViewCount]
      FROM [Posts] AS [p]
      WHERE [p].[Title] = @__p_0
```
In consequence, EF should ensure for a minimal number of cached execution plans by default concerning where clauses. 
Many thanks for clarifying this behaviour.
