### ISSUE TITLE
Is it possible to "mark" given nullable field as indistinctive for nulls?

### ISSUE THREAD

**Issue by macias** [dotnet/efcore#34024]
This question is about defining tables and fields using `DBContext.OnModelCreating`.

When you create unique index in SQLite the nulls are treated a distinctive. There is a way at SQL level to create index using function, so you can effectively get the index with indistinctive nulls, like ` ifnull(MyField, 0) `.

Is there a way to express this on EF Core level? I hope to get it with such syntax:

```
entity
  .HasIndex(e => new {e.SrcWordId ?? 0, e.DstWordId ?? 0}, "src_dst_word_idx")
  .IsUnique();
```

But this does not compile. So, it there a way?

**Comment by roji** [comment]
Duplicate of #28360
