### ISSUE TITLE
Managing DbContext the right way with Entity Framework

### ISSUE THREAD

**Issue by reader-man** [dotnet/efcore#3402]
Hi, thank you for this great version.
It would be nice to have another level of easiness ans compactness, and more toward effeciency when contacting the DB, by having a look at Mr. Mehdi el Gueddari project and Idea:

http://mehdi.me/ambient-dbcontext-in-ef6

https://github.com/mehdime/DbContextScope

and contacting him to have some of his ideas in EF.

**Comment by rowanmiller** [comment]
**Triage:** We took a look over this component and while it may fit well with some users it's not a pattern we would want to recommend for the majority of our customers. The extension library model which it is currently following seems like a good fit.
