### ISSUE TITLE
It is not possible to set null on property null Json after SaveChanges

### ISSUE THREAD

**Issue by Alekseyya** [dotnet/efcore#34030]
## File a bug
[WorkingTask.zip](https://github.com/user-attachments/files/15902003/WorkingTask.zip)

### Include your code

I have model WorkingTaskEntity with CustomData = Json. 

```C#
public record WorkingTaskCustomData
{
    public string InboundFlightLegIdentity { get; set; }

    public string OutboundFlightLegIdentity { get; set; }

    public string DispatcherRemark { get; set; }

    public string StaffRemark { get; set; }
}

public sealed record WorkingTaskEntity: IdentityEntity
{
    public WorkingTaskData? CustomData { get; init; }
}
```
Settings DbContext.
```C#
modelBuilder.Entity<WorkingTaskEntity>().OwnsOne(c => c.CustomData, t => t.ToJson()).Navigation(o => o.CustomData).IsRequired(false);
```
The repository has two methods. One Add and Update. If you specify null for the Add method. In the CustomData property it will be null.
If you try to replace the non-empty class CustomData with null in the Update method. The current state of the object will remain the same as it was before the update. Remove EntityState.Detached doesn't help with the solution.
```C#
async Task AddInternalAsync(WorkingTaskModel workingTask, EventHandlingContext context)
{
    var ids = await GetRequiredIdsAsync(workingTask, context).ConfigureAwait(false);
    var entity = CreateEntity(workingTask, null, ids);
    var entry = dbContext.WorkingTasks.Add(entity);
    await dbContext.SaveChangesAsync(context.CancellationToken).ConfigureAwait(false);
    entry.State = EntityState.Detached;
}
async Task<bool> UpdateInternalAsync(WorkingTaskModel workingTask, WorkingTaskEntity exists, EventHandlingContext context)
{
    var entry = dbContext.WorkingTasks.Update(entity);
    await dbContext.SaveChangesAsync(context.CancellationToken).ConfigureAwait(false);
    entry.State = EntityState.Detached;
    return true;
}

```
What am I doing wrong?

EF Core version: 8.0.6
Database provider: 
Microsoft.EntityFrameworkCore.Sqlite 8.0.6
Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4
Npgsql 7.0.0
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by maumar** [comment]
related to https://github.com/dotnet/efcore/issues/33452
