### ISSUE TITLE
 Primitive collections support has not been enabled. where to enabled 

### ISSUE THREAD

**Issue by wxyer** [dotnet/efcore#34038]
Primitive collections support has not been enabled. 
dotnet-ef 8.06 
i dont how to switch

**Comment by roji** [comment]
@wxyer you need to provide more details - please include the full exception stack trace, and ideally a minimal, runnable code sample (e.g. project) that we can look at. It's impossible to know what's going from "has not been enabled".

**Comment by roji** [comment]
As far as I know, primitive collections haven't been implemented for MySQL, since there are issues with JSON support in that database. But in any case, the MySQL provider isn't maintained here - please open an issue in the repo of the maintainer (note that there are two MySQL providers).
