### ISSUE TITLE
Add-Migration in Package Manager Console never completes, breaking package manager until VS2022 exit

### ISSUE THREAD

**Issue by paultobey** [dotnet/efcore#34055]
## File a bug

* I have been using EF Core 6 for some years, so creating new migrations is a relatively common occurrence but since VS2022 17.10 (or so, certainly happens in 17.10.3), my ability to generate an initial migration for a new DbContext and my ability to generate a new migration for an existing DbContext are broken.
* The symptom is this in package manager console:
```
Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 6.10.1.5

Type 'get-help NuGet' to see all available NuGet commands.

PM> Add-Migration -Name InitalNPG -Project Database.Migrations.PostgreSQL -Context BloggingContext -Verbose
Using project 'Database.Migrations.PostgreSQL'.
Using startup project 'PackageManagerConsoleEFCore6Issue'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\PackageManagerConsoleEFCore6Issue\bin\Debug\net6.0\PackageManagerConsoleEFCore6Issue.deps.json --additionalprobingpath C:\Users\ptobey\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\PackageManagerConsoleEFCore6Issue\bin\Debug\net6.0\PackageManagerConsoleEFCore6Issue.runtimeconfig.json C:\Users\ptobey\.nuget\packages\microsoft.entityframeworkcore.tools\6.0.8\tools\netcoreapp2.0\any\ef.dll migrations add InitalNPG --json --context BloggingContext --verbose --no-color --prefix-output --assembly C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\PackageManagerConsoleEFCore6Issue\bin\Debug\net6.0\Database.Migrations.PostgreSQL.dll --project C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\Database.Migrations.PostgreSQL\Database.Migrations.PostgreSQL.csproj --startup-assembly C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\PackageManagerConsoleEFCore6Issue\bin\Debug\net6.0\PackageManagerConsoleEFCore6Issue.dll --startup-project C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\PackageManagerConsoleEFCore6Issue\PackageManagerConsoleEFCore6Issue.csproj --project-dir C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue\Database.Migrations.PostgreSQL\ --language C# --configuration Debug --working-dir C:\Users\ptobey\source\repos\PackageManagerConsoleEFCore6Issue --root-namespace Database.Migrations.PostgreSQL

```
I can see that the build succeeded and, with some reliability, the migration was actually added (about 50% of the time nothing appears in the migration location; the other 50% the migration is created), but the new migration file doesn't open as usual in the editor, and the PM console is now stuck. Ctrl-C, Ctrl+Break and the stop button on the window do not stop the process or complete the operation. I've waited an hour and this isn't just something that's "slow"; it doesn't finish.

I can close the console window, of course, but now the VS2022 menu won't let me reopen it:

![image](https://github.com/dotnet/efcore/assets/4228311/ddae6772-290f-433b-a799-61aeb1aadfc4)

I also can't use any of the NuGet tools (Manage NuGet Packages for a project or Manage NuGet Packages for Solution):

![image](https://github.com/dotnet/efcore/assets/4228311/402c431e-1717-4dc3-9d3e-8f8967be0525)
![image](https://github.com/dotnet/efcore/assets/4228311/a636421a-e0d6-4f3c-8c7f-02e1365b12ba)

I have tested this in multiple EF Core 6.0.8-based projects and the result is the same. The only way to recover "normal" operation is to exit VS2022 and reopen. Of course, if the migration isn't correctly generated, the only way to get back to normal is try again (and hope!)

I've tried clearing my NuGet cache, verifying that the correct version of the EF Core tools are installed, etc. I can't find anything wrong with what I'm doing (and as noted, this has been working for years without issues on this machine with these projects).

### Include your code

Sample project created to demonstrate the problem:

[PackageManagerConsoleEFCore6Issue.zip](https://github.com/user-attachments/files/15931932/PackageManagerConsoleEFCore6Issue.zip)

```
Add-Migration -Name InitalNPG -Project Database.Migrations.PostgreSQL -Context BloggingContext
```

### Include stack traces

N/A

### Include verbose output

See above.

### Include provider and version information

EF Core version: 6.0.8
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 6.0.7
Target framework: .NET 6.0
Operating system: Windows 10 (all updates as of 2024-06-21)
IDE: VS2022 17.10.3

**Comment by maumar** [comment]
I am unable to reproduce this (using 17.10.5).  Does using dotnet ef tool work? (https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#create-your-first-migration)

**Comment by paultobey** [comment]
@maumar Yes, the command line seems to be OK. That's how I was working around the problem with VS2022. Good to hear that it's better in 17.10.5; hope that it's not some mysterious configuration issue with my machine!

**Comment by maumar** [comment]
@paultobey it still might be a problem with your setup. I have not tried it with 17.10.3 (and then observed improvement in 17.10.5). Also, I would expect more people report this problem but we haven't seen those.

**Comment by paultobey** [comment]
@maumar There was a problem with NuGet in the early 17.10's. A breaking change that I was trying to get out from behind (our builds would not run with the change). There was a bug report for a similar error that I was hoping was the cause:

https://github.com/NuGet/Home/issues/13456

Not sure if that might be the root cause (the attempts to get out from behind the problem). I believe I did install or copy the NuGet.zip file suggested. The eventual root cause for that one did not match our case (no same-name projects in the solution), but could be related.

**Comment by AthilTech** [comment]
Hello, i have exactly the same problem, i'm using Vs2022 comunity, .net 8.0.3 (EF, tools, ...), after invistigation i found the problem related to my project, 
i use puppteerSharp on my project for generating PDF document from Html, so it lunch hiddenChromium browser instance, 
i found that in each EF tools command executed in PM it lunch a new browser instance ( i don't know why or how, but belive me it happen , i will invistagate on this later), so the PM stuck and i got exactly  the problem described by @paultobey , to resolve the problem i go to windows task manager and stop the browser instance task from runing , and i get back the PM work fine, 

sorry for the long text, hope it help some one
