### ISSUE TITLE
Indexes are created by default for foreign keys in non-relational databases

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#34053]
The convention is debatable even on a relational database, where the use of FKs in joins make this often a useful index to have. Doing it speculatively for non-relational databases seems a step too far.

They are ignored by the Cosmos and in-memory provider, so this should not be breaking.

**Comment by ErikEJ** [comment]
This seems like quite a breaking change if I understand correctly (I always appreciated that theses indexes were created)

**Comment by ajcvickers** [comment]
> I always appreciated that theses indexes were created

Can you explain more? Neither the Cosmos nor the in-memory provider used the indexes in any way.

**Comment by ErikEJ** [comment]
So I probably misunderstood - this only affects non-relational providers, you will still create indexes for relational providers?

**Comment by ErikEJ** [comment]
I am just looking at this comment in the PR: "Also stop adding indexes for foreign keys by convention for relational providers." - I think that is waht confused me...
