### ISSUE TITLE
EFC8 Contains with ROWGUIDCOL

### ISSUE THREAD

**Issue by MoishyS** [dotnet/efcore#34079]
When Querying contains on column with type `HasColumnType("UNIQUEIDENTIFIER ROWGUIDCOL")`  it includes the ROWGUIDCOL in the query, which errors out.

Query
```
var guids = new List<Guid>() { new Guid(), new Guid() };
var tests= await _db.Tests.Where(q => guids.Contains(q.TestId)).ToListAsync();
```

SQL
```
SELECT [q].[TestId]
FROM [Test] AS [q]
WHERE [q].[TestId] IN (
    SELECT [g].[value]
    FROM OPENJSON(@__guids_0) WITH ([value] UNIQUEIDENTIFIER ROWGUIDCOL '$') AS [g]
)
```

Error
` Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'ROWGUIDCOL'.`

Setting compat level to 120 solves this issue.

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 10

**Comment by ErikEJ** [comment]
How did it get that column type??

**Comment by MoishyS** [comment]
@ErikEJ  this was manually set to `UNIQUEIDENTIFIER ROWGUIDCOL` (i am not sure why we are using ROWGUIDCOL)

**Comment by ErikEJ** [comment]
Rowguidcol is usually used by replication, not sure why you need this to be part of your EF Core model.

**Comment by cincuranet** [comment]
I agree with @ErikEJ, the `ROWGUIDCOL` is usually used by replication and such column should be ignored by application code (and application should have its own PK for "regular" usage). 

That said, `ROWGUIDCOL` is not really a datatype, but rather a modifier. The fact that it works with `HasColumnType` is pure coincidence. It's same as doing `HasColumnType("int not null")`. It will work from point of view of migrations, but it will fail in other places.

I'd like to understand more what your scenario is. But I think the changes are slim we'll support something like that in EF.

**Comment by roji** [comment]
Agreed with @cincuranet.

We could add a modeling option to allow the user to specify on a property that its column is a ROWGUIDCOL (e.g. IsRowGuidCol() extension on the property builder), and then have migration SQL generator output ROWGUIDCOL in the proper place. But this definitely isn't part of the data type, which is why the above doesn't work.

**Comment by cincuranet** [comment]
@MoishyS If you feel something like `IsRowGuidCol` would be valuable, please create separate issue. We'll consider it for future releases. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

I'll close this now.
