### ISSUE TITLE
Allow use of SplitToView on an entity mapped to a table

### ISSUE THREAD

**Issue by BurningLights** [dotnet/efcore#34070]
I want to be able to have an entity where a couple properties are defined by calculations in a view, while the rest of the properties map to columns in a table. It is a similar concept to non-persisted properties in #14121 where an entity is mapped using ToView and ToTable, except that all the table columns would not need to be passed through the view for querying.

I would like to be able to do
```
modelBuilder.Entity<Blog>().ToTable("Blogs").SplitToView("BlogsView",  builder => {
    // View columns mapped here
});
```

**Comment by roji** [comment]
Non-persisted properties (#14121) is about properties not having any existence in the database (e.g. a view), i.e. which are calculated client-side.

If you're looking to map a properties to a value calculated in the database, why not simply use [computed columns](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns)? That's the natural way to do what you're trying to do here, usually.

**Comment by BurningLights** [comment]
So, should #24692 not be a duplicate of #14121 then? Because what #24692 is about is the kind of thing I’m looking for, where there are columns in the view that an entity is selected from, but not on the table where it is stored to. What I’m proposing here is being able to use SplitToView so that only the columns that need calculating can be on the view, instead of having to pass through all the table columns as well like is currently necessary with using ToView and ToTable on an entity.

Computed columns will not do what I need, because I need to be able to reference other rows and other tables for the values I’m calculating. Like, say a bank account with a balance calculated from a sum of transactions.

**Comment by roji** [comment]
#24692 seems to me like it's mixing several things. If a property is mapped to something in the database (a column in either a view or a table), then I don't think that's covered by #24692; #24692 is about when a property is computed on the client and has no existence in the database.

Regardless, what you're asking for indeed sounds similar to #24692, in that you want some properties which are mapped to view columns, but not to a table column; so they're readonly (not mapped to a table), but at the same time computed in the database (so not #24692). 

/cc @AndriySvyryd for continued triage, in case this isn't properly tracked elsewhere.

**Comment by AndriySvyryd** [comment]
This isn't something we plan to support. You'll have to pass through the properties in the view.
