### ISSUE TITLE
EF 8 Migrations adds AlterColumn to every column, for subsequent migrations

### ISSUE THREAD

**Issue by aplongh** [dotnet/efcore#34086]
I have an old application in .Net Core 3.1 and EF Core 3.1. I have succesfully migrated to .net 8 and EF Core 8. The migrations folder was HUGE, so I reset the migrations, deleting all records in the `[__EFMigrationsHistory]` table and deleted the migration folder (the migrations folder is in a separate project.

I succesfully ran the initial migration and EF created the class with all existing tables, columns, indexes, etc. As the Database already exists, I manually added the migrations record to the `[__EFMigrationsHistory]` table.

I then had to add a new table. When I ran the Add-Migration, the resulting class is HUGE (should have only contained the necesarry code for the new table). It includes code for (i think) every column in the database, such as the following:

```
            migrationBuilder.AlterColumn<Guid>(
                name: "TenantId",
                schema: "Common",
                table: "XrmOrganization",
                type: "uniqueidentifier",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldNullable: true)
                .Annotation("Relational:ColumnOrder", 300);
```

```

            migrationBuilder.AlterColumn<int>(
                name: "StatusCode",
                schema: "Common",
                table: "XrmOrganization",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true)
                .Annotation("Relational:ColumnOrder", 211);
```
Any migration I try to add, adds these hundrends (maybe thousands) of line of code, altering the columns. As a remedy, I have manually deleted all these lines of code, but I would like to know the root cause and how to solve this issue, as the migrations file has more than 110 thousand lines.

Any help will be GREATLY appreaciated.

### Include provider and version information

EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net 8
Operating system: Windows 10 Pro
IDE: Visual Studio 2022 17.8.5

**Comment by aloksharma1** [comment]
i think you you are misunderstanding model snapshot, as you said you have manually deleted all old migrations from previous version ef core cannot see it, the snapshot name in __EFMigrationsHistory is just the migration Id of previous migrations, so now that it cannot see those migrations (deleted code) it will treat whole model as a new database, now you have few options here to fix this issue:

1. manually opt-out of migrations for the existing tables (mark it ignored using ModelBuilder.Ignore Method)

2. let everything run once (whether you manually delete extra data/code you have to run atleast first migration for ef to make an actual snashot of existing database.

3. iirc i saw somewhere here or some other an incremental migration approach which you can use to divide your initial table migration in smaller code bases.

let me know how it goes.

**Comment by cincuranet** [comment]
We currently don't have out-of-box support for squashing migrations. The work is tracked in #2174. This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 9.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

However, with proper steps, you can do the squashing manually yourself. The steps are described [here](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations).
