### ISSUE TITLE
Missing IS NOT NULL statement from query

### ISSUE THREAD

**Issue by BerenOneHand** [dotnet/efcore#34084]
I have an issue with the current entity framework version where my query would not generate the "X IS NOT NULL" part of the query. 

The query that causes the issue:

            var workflowContext = dbContext.Set<Workflow>().AsNoTracking();

            var workflows = workflowContext.Where(w => w.ProductId == "x" && w.WorkflowId != null).Take(100).ToList();

My dbContext has a dbset
```C#
        public DbSet<Workflow> Workflows { get; set; }
```

The workflow model:
```C#
public class Workflow
{
[Required]
public string IsolationId { get; set; }
[Required]
public string WorkflowId { get; set; }
[Required]
public string ProductId { get; set; }

public string? WorkflowName { get; set; }

public string? WorkflowVersion { get; set; }

public string? WorkflowType { get; set; }

public string? AuthorDisplayName { get; set; }

public string? AuthorEmail { get; set; }
}
```

Here is the SQL query produced:
```SQL
SELECT `t`.`IsolationId`, `t`.`WorkflowId`, `t`.`ProductId`, `t`.`WorkflowName`, `t`.`WorkflowVersion`, `t`.`WorkflowType`, `t`.`AuthorDisplayName`, `t`.`AuthorEmail`
FROM `tbl_workflows_v2` as `t`
WHERE `t`.`ProductId` = 'x'
LIMIT @__p_0
```

Expected Query:

```SQL
SELECT `t`.`IsolationId`, `t`.`WorkflowId`, `t`.`ProductId`, `t`.`WorkflowName`, `t`.`WorkflowVersion`, `t`.`WorkflowType`, `t`.`AuthorDisplayName`, `t`.`AuthorEmail`
FROM `tbl_workflows_v2` as `t`
WHERE `t`.`ProductId` = 'x' AND `t`.`WorkflowId` IS NOT NULL
LIMIT @__p_0
```

EF Core version: 8.0.6
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: NET 8.0
Operating system: Windows
IDE: Visual Studio 2022 17.10

**Comment by ranma42** [comment]
I believe that is related to the `[Required]` attribute that is on the `WorkflowId` property: EFCore interprets it as an indication that the column cannot be `NULL` (see the [docs](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/mapping-attributes#requiredattribute)).

**Comment by cincuranet** [comment]
What @ranma42 said is correct. The `[Required]` attribute makes the property/column non-nullable for EF model and hence EF optimizes that `w.WorkflowId != null` away, because based on those facts it couldn't happen.

**Comment by BerenOneHand** [comment]
I did remove the [Required] attribute and it still did not add the IS NOT NULL.

**Comment by cincuranet** [comment]
You still have `string` there and looking at i.e. `string? WorkflowName`, you're using NRT. You need to change it to `string? WorkflowId`.

**Comment by BerenOneHand** [comment]
I did that as well. It still would not generate the IS NOT NULL.

I would not have added the bug here if i didnt try all avenues.

I just assume EF uses something along the lines of "EntityName+Id" matching and marks it as a key which cannot violate the nullable rule. 
However, the dataset i am working with has nullable Ids (BAD data)

**Comment by cincuranet** [comment]
Without seeing your model/configuration, it's hard to guess.

> However, the dataset i am working with has nullable Ids (BAD data)

That does not make much sense. Primary keys are always not null.

**Comment by BerenOneHand** [comment]
The data that comes in is not something I control. Its external data from clients. We dont want to lose any data, so we allow all entries in and deal with any null entries by notifying the clients.

**Comment by BerenOneHand** [comment]
Adding [Keyless] to the entity type works. Thanks.

**Comment by cincuranet** [comment]
Make sure you understand what [_Keyless entities_](https://learn.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations#keyless-entity-types-characteristics) do and don't do/support and validate whether it fits your needs.
