### ISSUE TITLE
Connection string keyword 'journal mode' is not supported in SQLite

### ISSUE THREAD

**Issue by schillc** [dotnet/efcore#34083]
Using the 'journal mode' keyword in the connection string for SQLite results in an ArgumentException. According to the [official Microsoft documentation](https://go.microsoft.com/fwlink/?linkid=2142181), 'Journal Mode' can be used in the connection string. However, when attempting to do so, the following error is thrown:

```
Unhandled exception. System.ArgumentException: 
Connection string keyword 'journal mode' is not supported. 
For a possible alternative, 
see https://go.microsoft.com/fwlink/?linkid=2142181.
```

### Steps to reproduce:

1. Create a new C# project with the following csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
    </ItemGroup>
</Project>
```

2. Use the following code to configure the DbContext:
```
using Microsoft.EntityFrameworkCore;

using var db = new ApplicationDbContext();

public class ApplicationDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=test.db;Journal Mode=Delete");
}
```

3. Run the application.

### Expected result:

The application should configure the SQLite database with the specified journal mode without throwing any exceptions.

### Actual result:

The application throws an ArgumentException with the message:

```
Unhandled exception. System.ArgumentException: 
Connection string keyword 'journal mode' is not supported. 
For a possible alternative, 
see https://go.microsoft.com/fwlink/?linkid=2142181.
```
### Include provider and version information

EF Core version: 8.0.6
Database provider: SQLite
Target framework:  .NET 8.0
Operating system: Windows 11 ARM
IDE: JetBrains Rider

**Comment by ajcvickers** [comment]
@schillc The documentation to linked to explicitly states that `Send PRAGMA journal_mode = <mode>` should be used because there is no connection string setting for it.
