### ISSUE TITLE
Support Shadow Properties in Bulk Updates

### ISSUE THREAD

**Issue by rjperes** [dotnet/efcore#34099]
Currently, because ExecuteUpdate is bould to the model, we can only update "physical" properties, not shadow properties. We should be able to, because EF Core fully supports that.

One possible solution would be to add an overload that takes strings instead of strongly typed expressions.

**Comment by roji** [comment]
You should be able to use EF.Property() to reference shadow properties in ExecuteUpdate - does that not work?

**Comment by rjperes** [comment]
No, because SetProperty is strongly typed:

`ctx.Set<Product>().Where(x => x.Reference == "xxxx").ExecuteUpdate(x => x.SetProperty(EF.Property(x, "IsDeleted"), true));`

Does not compile.

**Comment by roji** [comment]
Your ExecuteUpdate is mangled... Try this:

```c#
ctx.Set<Product>().Where(x => x.Reference == "xxxx").ExecuteUpdate(setters => setters.SetProperty(p => EF.Property(p, "IsDeleted"), true));
```

**Comment by rjperes** [comment]
Sorry, but no, doesn't compile (.NET 8):

The type arguments for method 'EF.Property<TProperty>(object, string)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by rjperes** [comment]
Ah, works if you set the template parameters:

ctx.Set<Product>().Where(x => x.Reference == "xxxx").ExecuteUpdate(setters => setters.SetProperty<bool>(p => EF.Property(p, "IsDeleted"), true));

Many thanks! You can close this!

**Comment by rjperes** [comment]
Already implemented, nothing needed.
