### ISSUE TITLE
Simplify HistoryRepository implementation

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#34090]
Leverage query pipeline for `GetAppliedMigrations`
Leverage update pipeline for `GetInsertScript` & `GetDeleteScript`

**Comment by roji** [comment]
@AndriySvyryd am wondering if it's worth the complexity of integrating with these pipelines for these simple SQLs...

**Comment by ErikEJ** [comment]
There were similar ideas around using an EF model to query SQL Server DatabaseModel metadata, and look where we are today.

**Comment by AndriySvyryd** [comment]
Totally fair.
I was just translating old TODO comments to issues, this shows the importance of doing it.
