### ISSUE TITLE
New EFCore Provider Translate Date addition/subtraction

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#34104]
I'm continuing work on our little custom efcore provider and have a question in implementing specification tests around date differences.

The test `Datetime_subtraction_TotalDays` test runs the following c#

``` cs
[ConditionalTheory]
[MemberData(nameof(IsAsyncData))]
public virtual Task Datetime_subtraction_TotalDays(bool async)
{
    var date = new DateTime(1997, 1, 1);
    return AssertQuery(
        async,
        ss => ss.Set<Order>().Where(o => o.OrderDate.HasValue && (o.OrderDate.Value - date).TotalDays > 365),
        entryCount: 267);
}
```

Ultimately that needs to translate to:
``` sql
select fields
from "Orders" o
where DATEDIFF(day,TIMESTAMP'1997-01-01 00:00:00', o.OrderDate) > 365
```

I currently get an exception saying unable to translate linq, re-write query etc. 

I have date filter working as with other date functions and translations. It seems like I'd need to be able to first translate that linq to treat `o.OrderDate - date` to be treated as a timespan, and then I could provide a timespan member translator to get days to the compare with the constant of 365.

Can the date math (date - otherdate) be handled to translate as a timespan, or is it possible to take the entire filter and say if we have date math on one side, and a comparison to a constant on the other, rewrite the entire thing to just use DATEDIFF method?

I looked at the SqlServer implementation of this, and it makes sense that there are dedicated functions people can add to the linq to explicitly call `DateDiff`, but didn't know if this is something I could handle, or if I should do like SqlServer does and implement FunctionExtensions and make sure i assert that these tests fail the way they are currently failing.

EF Core version:
Database provider: custom
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ronnyek** [comment]
Likewise I've also realized that I possibly need to translate date comparisons... so instead of translating
``` cs
.Where(x=>x.OrderDate = new DateTime.Now.Date)
```

To `where orderdate = date`, or doing `where datepart( 'date', orderdate))` (this db has a way to extract parts of dates, but not the whole date component).

In order to compensate, I'm thinking it might be smartest to translate an example date like `1997-01-01 04:00:00`
to a `where orderdate > 1997-01-01 00:00:00 and orderdate < '1997-01-01 23:59:59' ` or whatever?


Maybe I am just overcomplicating it. I could do translate the date to string parts and compare to the equivalent string with provided date, but I feel like that would cause a table scan at the very least.

**Comment by roji** [comment]
> Can the date math (date - otherdate) be handled to translate as a timespan, or is it possible to take the entire filter and say if we have date math on one side, and a comparison to a constant on the other, rewrite the entire thing to just use DATEDIFF method?

SQL Server has no actual type representing a TimeSpan (or "time interval"), which is why it's not possible to translate date subtraction directly; that's why DATEDIFF functions exist in the first place. PostgreSQL does have an `interval` part, so date subtraction works there, and then TotalDays can be translated on TimeSpan. If your database supports something like this, then it's generally better to have those two compositional translations (date subtraction yielding timespan/interval, followed by a simple TotalDays member translation on timespan). Otherwise, if there's no first-class interval type in your database, then you can implement a single, complex pattern-match for `(date1 - date2).TotalDays` and translate that whole thing to your DATEDIFF function.

> Likewise I've also realized that I possibly need to translate date comparisons

I don't know of any database which can't extract a date out of a timestamp... If that's really the case, then yeah, translating to `orderdate > 1997-01-01 00:00:00 and orderdate < '1997-01-01 23:59:59'` sounds reasonable, and you're right to think about index usage (which a string conversion would prevent).

**Comment by ronnyek** [comment]
@roji, do you have any general pointers or ideas about what I'd need to override to implement either of those things? Datediff exists here, and has a days interval, I just don't know where to do the "complex pattern match".  (I saw nothing obvious like this in the sql server implementation)

I imagine its going to need similar for the ability to translate date equality to the provideddate>= date and date <= last second of the day.  This db has a datepart extraction method, just doesn't have a parameter for returning date. (supports most of the other typical things)

I guess I've totally got an understanding of translating members/functions, and manipulating diff types of queries, just not how to manipulate queries for specific where criteria etc.

Finally, I appreciate all the pointers you've given. I use the npgsql variant of efcore on a daily basis.

**Comment by roji** [comment]
> do you have any general pointers or ideas about what I'd need to override to implement either of those things? Datediff exists here, and has a days interval, I just don't know where to do the "complex pattern match". (I saw nothing obvious like this in the sql server implementation)

This goes beyond the abilities of a simple IMethodTranslator, of course. You would be overriding the appropriate method in your provider's SqlTranslatingExpressionVisitor (like SqlServerSqlTranslatingExpressionVisitor), and implementing the pattern matching there, and performing the translation you want. Specifically, a pattern such as `(o.OrderDate.Value - date).TotalDays` would be identified in VisitMember (that's the TotalDays), where the MemberExpression's Expression is a BinaryExpression representing the subtraction. You can look around SqlTranslatingExpressionVisitor and its subclasses in the various providers for some examples.

> I imagine its going to need similar for the ability to translate date equality to the provideddate>= date and date <= last second of the day.

Yes. Method calls (MethodCallExpression) and member accesses (MemberExpression) are the only ones where there's an easier extensibility mechanism (IMethodTranslator/IMemberTranslator); for the rest (e.g. special you do the work directly inside your SqlTranslatingExpressionVisitor.

I'll go ahead and close this as there's nothing actionable on our side, but if you need further guidance post back here.

**Comment by ronnyek** [comment]
@roji, I think those comments make sense, and honestly might explain why SQL Server implementation has some things that probably could be translated into tsql implemented with SqlServerFunction extensions. Probably much easier to catch/translate that. 

I appreciate taking the time. I think it makes sense what I need to do now.

**Comment by roji** [comment]
> might explain why SQL Server implementation has some things that probably could be translated into tsql implemented with SqlServerFunction extensions

I actually do think we should be pattern-matching larger trees where that makes sense - but we traditionally haven't gone far in this direction.
