### ISSUE TITLE
EF Core Migration Issue: Column Already Exists

### ISSUE THREAD

**Issue by hadiki** [dotnet/efcore#34101]
Hello,

I'm encountering an issue with Entity Framework Core migrations in my project. When I try to apply a migration, I receive an error indicating that a column already exists in the database. Here are the details:

Error Message:

sql
Copy code
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE valuation ADD accrued_interest numeric;
Npgsql.PostgresException (0x80004005): 42701: column "accrued_interest" of relation "valuation" already exists
...
Entity Definition:

csharp
Copy code
public class Valuation : BaseEntity
{
    public Guid PortfolioId { get; set; }
    public Portfolio Portfolio { get; set; } = default!;
    public Guid AssetId { get; set; }
    public Asset Asset { get; set; } = default!;
    public decimal? Volume { get; set; }
    public decimal? Piece { get; set; }
    public decimal? ProfitAndLoss { get; set; }
    public decimal? ProfitAndLossBaseCcy { get; set; }
    public decimal? ProfitAndLossPercentage { get; set; }
    public decimal? ProfitAndLossPercentageBaseCcy { get; set; }
    [Obsolete($"Please use '{nameof(PercentNav)}'")]
    public decimal? Weight { get; set; }
    public bool IsTech { get; set; }
    public decimal? Return { get; set; }
    public decimal? Entry { get; set; }
    public decimal? PercentNav { get; set; }
    public required Opus Opus { get; set; }
    public List<Transaction> Transactions { get; set; } = [];
    public Guid? MainCategoryId { get; set; }
    public Category? MainCategory { get; set; }
    public int MainCategoryPosition { get; set; }
    public Guid? SubCategoryId { get; set; }
    public Category? SubCategory { get; set; }
    public int SubCategoryPosition { get; set; }

    #region Bond
    public decimal? AccruedInterest { get; set; }
    #endregion

    #region Future
    public decimal? NotionalValue { get; set; }
    public decimal? Balance { get; set; }
    #endregion

    // Additional methods...
}
Steps Taken:

Removed the faulty migration using dotnet ef migrations remove.
Verified the entity model reflects the correct schema.
Generated a new migration using dotnet ef migrations add AddColumnsToPortfolio.
Applied the migration using dotnet ef database update.
Despite these steps, the new migration still attempts to add the AccruedInterest column, which already exists in the database. How can I prevent EF Core from trying to add this column again?

Any help or guidance would be greatly appreciated!

**Comment by AndriySvyryd** [comment]
If this is because the schema got out-of sync with EF migrations you can manually remove the `AddColumn` operation from the new migration and then apply it.

If the next migration is still trying to add the same column then try to create a small repro project that shows this issue.

**Comment by roji** [comment]
Closing as the question seems resolved, but @hadiki if you have further trouble, post back and we'll revisit.
