### ISSUE TITLE
Widely-used DistinctBy workaround causes other errors

### ISSUE THREAD

**Issue by lonix1** [dotnet/efcore#34119]
Originally asked [on SO](https://stackoverflow.com/q/78680591/9971404) without resolution.

---

A query:
```cs
List<Guid> productCodes = GetProductCodes();  
var products = await _context
  .Products
  .Where(x => productCodes.Contains(x.ProductCode))
  .GroupBy(x => x.ProductCode).Select(x => x.First())    // workaround for `DistinctBy`
  .Select(x => new { SupplierId = x.Supplier.Id, WarehouseId = x.Warehouse.Id, x.ProductCode, x.Price, ... })
  .ToListAsync();
```

Result:
```
InvalidOperationException: The LINQ expression 'ProjectionBindingExpression: 0' could not
be translated. Either rewrite the query in a form that can be translated, or switch to
client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable',
'ToList', or 'ToListAsync'.
```

I use the `GroupBy/Select-First` workaround instead of `DistinctBy` which is currently [unsupported](https://github.com/dotnet/efcore/issues/27470).

I assume from the error message that the projection in `.Select()` is the problem; when I remove that the query works. I could perform the projection afterwards, but then I'd be fetching large quantities of data for nothing.

Is there a way to workaround this issue until there is DistinctBy support?

EF Core version: 7.0.16
Database provider: Npsql
Target framework: 7.0
Operating system: linux
IDE: vscode 1.90.2

**Comment by roji** [comment]
7.0 is out of support, please upgrade to 8.0 and confirm that the issue is still present there.
