### ISSUE TITLE
All PRs were merged on green, and yet the build was still broken

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#34139]
Figure out why the CI for PRs didn't catch this.

See also https://github.com/dotnet/efcore/issues/34137

<img width="729" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/ae1fd797-3e21-4d6c-814d-834ca842bdcc">

**Comment by ranma42** [comment]
The CI is not asserting that the baselines match for the compiled model tests. https://github.com/dotnet/efcore/pull/34111 fixes this.
