### ISSUE TITLE
Cannot constrain max length of a text field in a model

### ISSUE THREAD

**Issue by paulharv** [dotnet/efcore#34150]
## Description
I have a string field with, currently, no size constraint and I need to set it to a maximum size of 12000 characters. 
I attempted to use the StringLength and MaxLength annotations in the model to do this, but no error is thrown when I save > 12000 characters.

### Code
```
[StringLength(12000)] # I've also used [MaxLength(12000)]
public string Instructions { get; set; }
```

When I run `add-migration`, the migration file contains empty `Up()` and `Down()` methods. I've come to learn that this is expected, since any max value over 4000 results in a data type of `nvarchar(max)` - and our Instructions column already has that type.

The Model Snapshot does change...
```
b.Property<string>("Instructions")
    .HasMaxLength(12000) # <== this is the only thing changed in the Snapshot file
    .HasColumnType("nvarchar(max)");
```

However, as mentioned, I can still save strings longer than 12,000 characters.

This looks like a bug, but is it? Or am I misunderstanding the limits of using StringLength/MaxLength

### provider / version information
EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.10.2

**Comment by ajcvickers** [comment]
@paulharv EF Core does not do validation for you. EF6 had some validation, but it was rarely used and duplicated the validation already done by applications elsewhere. So EF uses the string length for database creation and for efficient parameter creation, but makes no attempt to validate your data for you.

**Comment by paulharv** [comment]
> @paulharv EF Core does not do validation for you. EF6 had some validation, but it was rarely used and duplicated the validation already done by applications elsewhere. So EF uses the string length for database creation and for efficient parameter creation, but makes no attempt to validate your data for you.

Ah, I see, got it. Thank you.
