### ISSUE TITLE
Why Unknown error 258 is not in SqlServerRetryingExecutionStrategy retryable error numbers.

### ISSUE THREAD

**Issue by malylemireflo** [dotnet/efcore#34154]
## Ask a question

I sometimes get this error when dtu are maxed out on azure hosted sql server database.

```
Microsoft.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Operation cancelled by user.
---> System.ComponentModel.Win32Exception: Unknown error 258
```

Why won't the SqlServerRetryingExecutionStrategy retry this by default?

EF Core version: 8.0.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Ubuntu
IDE: Visual Studio 2022 17.4

**Comment by AndriySvyryd** [comment]
That error can have a variety of causes, see https://github.com/dotnet/SqlClient/issues/1530
It's not an expected transient error and thus EF won't retry it by default, you can add it in the `EnableRetryOnFailure` call if you consider it to be safe to retry for your scenarios.
