### ISSUE TITLE
MinLength or custom CONSTRAINT or more Sentinels (?)

### ISSUE THREAD

**Issue by davidpodhola** [dotnet/efcore#3416]
I have class `NamedEntity` in my model. I am trying not to allow empty strings to be saved. 

```
    public partial class NamedEntity
    {
        public Int32 Id { get; set; }

        [Required]
        [StringLength(50)]
        [MinLength(1)]
        public String Name { get; set; }
    }
```

I know `MinLength` attribute is not supported and I am OK with that, however I would like to propagate this requirement to the model.

At the end (at least on the SQL Server) I need something like

```
ALTER TABLE [dbo].[YOUR_TABLE]
ADD CONSTRAINT [MinLengthConstraint] CHECK (DATALENGTH([your_column]) > 2)
```

to be generated.

What would be the best way to do this? I am also happy with adding some customizability to e.g. the SqlGenerator by myself.

**Comment by rowanmiller** [comment]
@davidpodhola the easiest way to do this would be to alter the column after it is created. Just edit one of your migrations to add a call to migrationBuilder.Sql("<statement to alter column>") after the column has been added.
