### ISSUE TITLE
dotnet ef dbcontext scaffold creates a property of the parent type in the child class

### ISSUE THREAD

**Issue by SCC-BDuncan** [dotnet/efcore#34169]
Is there a way to tell ef core not to create a method of the parent type in the child?

For example.  I have a Booking table with a foreign key to the BookingAddresses Table.  I expect a booking class (the parent) with a property of List<BookingAddresse>, which I get.  The problem is that the BookingAddress class (the child) has a property of type Booking, the parent.

**Comment by ajcvickers** [comment]
@SCC-BDuncan You can use [custom T4 templates](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) to change what is scaffolding. @ErikEJ's [EF Core Power Tools](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools) have more options for scaffolding than the EF commands, but I'm not sure that they support this.
