### ISSUE TITLE
Microsoft.Data.Sqlite - .NET8 iOS

### ISSUE THREAD

**Issue by Koub96** [dotnet/efcore#34182]
Hello everyone,

Due to migrating our Xamarin.iOS application to .NET 8, we moved away from Mono.Data.Sqlite and migrated to Microsoft.Data.Sqlite version 8.0.4.

Even though the changes needed to be made were minimal, we have encountered a certain breaking issue.

The SqlConnection seems to not support (at least by default) the serialized mode in order to avoid multithreading issues.
Serialized mode is pretty common for mobile applications, and I wanted to ask if it is supported on Microsoft.Data.Sqlite.

If not, is there an alternative for .NET 8 ?

Thank you in advance,

Konstantinos Koumpanakis

**Comment by ErikEJ** [comment]
Is serialized not the default? https://www.sqlite.org/threadsafe.html

**Comment by ajcvickers** [comment]
@Koub96 Note that `DbCommand` and `DbConnection`, the underlying types used by Microsoft.Data.Sqlite, are not thread-safe. In general, you cannot use `Microsoft.Data.Sqlite` objects concurrently from multiple threads.

**Comment by ajcvickers** [comment]
@Koub96 It's not about the SQLite serialized mode, it's about re-using .NET types. For example, don't share the same `DbConnection` instance across threads.

**Comment by Koub96** [comment]
We are only re-using a single SqliteConnection from which we construct the SqliteCommands.

So, we need to ensure that each thread will establish its own SqliteConnection to the database?

**Comment by ajcvickers** [comment]
> So, we need to ensure that each thread will establish its own SqliteConnection to the database?

Yep. But be aware that connection pooling is on by default, so a new SqliteConnection is pretty lightweight.

**Comment by Koub96** [comment]
@ajcvickers Due to certain use cases of our app, we had to disable pooling. Are you aware If that will impact performance when we create a new SqliteConnection ?

**Comment by ajcvickers** [comment]
@Koub96 Yes, it will likely have an impact.

**Comment by Koub96** [comment]
@ajcvickers Thank you for your help.
