### ISSUE TITLE
Cosmos: error when attempting to save entity with CLR default key value

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#34180]
The Cosmos provider does not, except in corner cases, generate key values by convention. However, people coming from a relational background may expect a key to be generated. We should error by default if the entity type still has the CLR default for the key value. This can be switched off, so that the CLR default can be saved as a normal value if this is needed, but it should be rarely used.

**Comment by roji** [comment]
It seems that this was implemented as a warning rather than an error.
