### ISSUE TITLE
Auto Aliasing is reusing same alias for two different tables causing a value comparison to return the wrong value.

### ISSUE THREAD

**Issue by firefing1** [dotnet/efcore#34193]
I am running into an issue where when I try to update a value from a different table if the two tables start with the same letter the alias sets them to be the same this makes it where the comparison fails.

```C#
await Context.Set<Fum>()
            .ExecuteUpdateAsync(set => set.SetProperty(
                fum => fum.FooId,
                fum => 
                   Context.Set<Foo>()
                      .FirstOrDefault(foo => foo.Name == fum.Name).Id
            )
);
```

Generates

```
      UPDATE "MySchema".fum AS f
      SET  = foo_id(
          SELECT f."Id"
          FROM "MySchema".foo AS f
          WHERE f.name = f.name
          LIMIT 1)
```

This causes the set to just update to whatever happens to be the first value it checked.

### provider and version information

EF Core version: 7.0.4
Database provider: Npgsql.EntityFrameWorkCore.PostgreSQL
Target framework: .Net 7.0
Operating system: Windows 11
IDE: Rider 2024.1.3

**Comment by ajcvickers** [comment]
@firefing1 Please try with EF Core 8.0. EF7 is [out of support](https://learn.microsoft.com/en-us/ef/core/what-is-new/).

**Comment by firefing1** [comment]
thanks for the quick response @ajcvickers

**Comment by roji** [comment]
@ajcvickers seems like this is fixed in 8? Closing but feel free to reopen if I've misunderstood...
