### ISSUE TITLE
Query: Join Elimination/Consolidation

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#3419]
We often join to the same table(s) multiple times, we should look at adding logic to consolidate these joins. One example is using the same nav prop in an `Include` and a `Where` call.

**Comment by anpete** [comment]
We should only gen a single join per nav prop in the multiple includes case.

**Comment by rowanmiller** [comment]
Cool, nice - I updated the description

**Comment by smitpatel** [comment]
ping @anpete

**Comment by smitpatel** [comment]
We don't join to same table multiple times except
- Asked by user explicitly by including multiple query roots
- Navigation was expanded and later condensed because of certain terminating operator like Distinct.
- Table splitting case

**Comment by smitpatel** [comment]
Closing as pending task is being tracked at #18869
