### ISSUE TITLE
Split mappings are not supported for hierarchies

### ISSUE THREAD

**Issue by Ukkie007** [dotnet/efcore#34190]
the one in the subject.

I was able to do so in Entity Framework 6, but not in EF Core. I had no performance issues, so migrating is for me no option at this moment.

**Comment by Ukkie007** [comment]
[EFCoreSplitTables.zip](https://github.com/user-attachments/files/16161882/EFCoreSplitTables.zip)

Database is included as a bacpac.
I have a working version in Entity Framework 6 with an identical database schema.

**Comment by AndriySvyryd** [comment]
Duplicate of https://github.com/dotnet/efcore/issues/27970
