### ISSUE TITLE
ef cache vs Redis

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/efcore#34204]
Hi, ef cache c Redis has a solution. For example, I have two hosts, I want a single cache between them?

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by EvgenyPrikhodko** [comment]
An EF cluster, for example, I have several services. 
Or I have several micro services and one database.

**Comment by EvgenyPrikhodko** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

How do I make a failover cluster?

**Comment by EvgenyPrikhodko** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.


For example, there is NHibernate.Caches.Redis, is there a similar solution in ef?

**Comment by roji** [comment]
@EvgenyPrikhodko you can absolutely use e.g. a Redis cache in front of your database access layer, in other words check the cache before you execute queries with EF. There's no built-in support for integrating this inside EF, as different caching solutions and requirements would have different needs here. So this is something you have to take care of in your own application.

**Comment by ErikEJ** [comment]
https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor

**Comment by roji** [comment]
I'm going to go ahead and close this issue now, as this is out of scope for EF, but feel free to post back if you have further questions.
