### ISSUE TITLE
how to invoke multiple call for onmodelcreating in dbcontext 

### ISSUE THREAD

**Issue by ARULKUMAR30024** [dotnet/efcore#34207]
public DynamicDbContext(DbContextOptions<DynamicDbContext> options, Type dynamicEntityType) : base(options)
    {
        _dynamicEntityType = dynamicEntityType;
       
    }
    public Type dynamicType { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Dynamically add the entity to the model
        if (_dynamicEntityType != null)
        {
            modelBuilder.Entity(_dynamicEntityType);
           
            
        }
    }
I need to trigger onmodelcreating method each time when i create a new instance of the dbcontext but it wont trigger after first time so i cant add my entity in dbcontext

**Comment by ajcvickers** [comment]
@ARULKUMAR30024 By default, the model is built once and cached based on the type of the `DbContext`. See [Alternating between multiple models with the same DbContext type](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model) to change this, but be aware that building a new model for each context instance will not have good perf.

**Comment by ARULKUMAR30024** [comment]
Thanks for your support. In my application there is a chance to change models schema on runtime so we can't change the model every time and give a build. So I created a dynamic crud operation without a datamodel or any predefined model I will remove the cache once its work done i hope performance will remain same
