### ISSUE TITLE
First class support for Elastic DB

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#3421]
We could provide some first class support for swapping shards, applying migrations to all shards, etc.

**Comment by shaulbehr** [comment]
Interested to hear how this feature is coming along?

**Comment by rowanmiller** [comment]
@shaulbehr we haven't started on this yet. It will be a post 1.0.0 feature, and there are some more fundamental features on the list ahead of it.

**Comment by KirteeM** [comment]
Is ElasticDB available for EF core?

**Comment by ajcvickers** [comment]
@KirteeM ElasticDB support isn't something the EF team is working on. You may be able to find some community efforts with a search, but I don't have any info on their implementation status.

**Comment by ajcvickers** [comment]
Closing this as we do not plan to implement and maintain an Elastic DB provider for EF Core. However, we would be supportive of a community effort to create such a provider.
