### ISSUE TITLE
Call a ThenBy on a non IOrderedQueryable

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/efcore#34212]
## Ask a question

I've this code:

```C#
var qry = db.Posts.OrderBy(x => x.Title).Select(x => new { x.Title, x.PostId }).OrderBy(x => x.PostId);
```

but the problem is, only the second OrderBy is handled by the database. But I cannot use ThenBy cause it is not a IOrderedQueryable after the Select any more. (The real query is complexer, but this shows the issue)

**Comment by maumar** [comment]
use orderby.thenby before (or after) the select, like so:

```cs
var qry = db.Posts.OrderBy(x => x.Title).ThenBy(x => x.PostId).Select(x => new { x.Title, x.PostId });
```

**Comment by roji** [comment]
Note that this question has nothing to do with EF: the same would hold with regular LINQ-to-objects (where the query runs in memory rather than against the database). This is just how LINQ operators function.

**Comment by jogibear9988** [comment]
@maumar this is not possible. It is possible in the sample, but not in my real application code.

@roji no it works with linq2objects, take a look:

https://dotnetfiddle.net/LJKGf1

<img width="688" alt="image" src="https://github.com/user-attachments/assets/2111b680-b36d-4c70-8530-cff344f664f1">

**Comment by jogibear9988** [comment]
It also works with linq2db at the moment (see https://github.com/linq2db/linq2db/issues/4557) but there are intends to remove it. And cause of that I wanted to know, if it works in EFCore.

**Comment by roji** [comment]
I don't see a ThenBy in your code - it's not clear what it is that you're asking. Can you please post a LINQ query which works in-memory but not with EF?

**Comment by jogibear9988** [comment]
It means, that the first orderby I use is not lost. the Orderby you use after is the main one, but the first is not ignored

**Comment by jogibear9988** [comment]
Bun in the SQL efcore creates the first orderby is not used at all

**Comment by jogibear9988** [comment]
look at this sample: https://dotnetfiddle.net/9KPYsj
the ret1 and ret4 are the same

**Comment by jogibear9988** [comment]
I need to check wich query it was on my side, but it was not possible to the sorting acordingly.

**Comment by roji** [comment]
@jogibear9988 I'm still not really sure exactly what problem you're running against - you'll have to post a minimal, runnable code sample.
