### ISSUE TITLE
Support bitwise NOT on boolean values

### ISSUE THREAD

**Issue by ranma42** [dotnet/efcore#34213]
For boolean expressions, bitwise `~` and logical `NOT` are generally the same, but in SqlServer the first can be applied on `BIT`s, while the second one is for boolean predicates.

Since #34080 the SqlServer provider avoids converting to a predicate when it just needs to negate a `BIT`, but it does so using `^ 1`.
A better translation could be emitted by translating to a `~`.

**Comment by roji** [comment]
Just noting that bitwise NOT is useful also for non-boolean types, so this would be useful beyond the specific SQL Server scenario we've been focusing on (and beyond SQL Server in general).

**Comment by ranma42** [comment]
Non-boolean types can already use the bitwise not:
https://github.com/dotnet/efcore/blob/73db4f0f5b5e599435a7e8cfda4a4066b8ada420/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L883-L885

The boolean case is explicitly treated as special:
https://github.com/dotnet/efcore/blob/73db4f0f5b5e599435a7e8cfda4a4066b8ada420/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L856-L874

The current encoding does not differentiate between bitwise and logical not (well, on boolean expressions it is always the logical not, on integer expressions it is always the bitwise not).

**Comment by ranma42** [comment]
I am thinking about working on this. My approach would be to extend `SqlUnaryExpression` to also allow `OnesComplement`.
In the first iteration, I would probably only use it in SqlServer to encode this specific not (changing other parts might needlessly affect other providers).
