### ISSUE TITLE
Missing nuget package Microsoft.EntityFrameworkCore.Relational.Specification.Tests

### ISSUE THREAD

**Issue by ChrisJollyAU** [dotnet/efcore#34221]
I'm busy trying to upgrade [EntityFrameworkCore.Jet](https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet) to the latest preview of efcore 9 - preview 6.

I'm getting stuck when trying to update the references for the tests. Specifically the tests reference the package `Microsoft.EntityFrameworkCore.Relational.Specification.Tests` but preview 3 is the latest available on nuget - see https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/

Is there a change in design that we need to reference a different nuget package or is this just something that got missed during the previews

Potentially this affects all third party ef core providers

**Comment by ajcvickers** [comment]
@SamMonoRT Looks like an issue with the build/publishing.

**Comment by SamMonoRT** [comment]
@rbhanda @leecow - would you know why this test package is stuck on Preview 3 -- https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/#versions-body-tab ?

**Comment by leecow** [comment]
It looks like that package is marked as non-shipping so doesn't get picked up by the publishing process. We should be able to manually push it to NuGet but you'll need to work out why it's not marked as "shipping".

**Comment by AndriySvyryd** [comment]
I don't know how it was "shipping" before, but we explicitly marked `EFCore.Specification.Tests` as shipping in ec29172d5a1a5f86aa07420d6592a01cbd9998ea, but missed `EFCore.Relational.Specification.Tests`

**Comment by ChrisJollyAU** [comment]
Thanks. Looks like that has done the trick. The packages are there now in nuget and have also now started appearing again in the dotnet9 daily build feed as of 9.0.0-preview.7.24366.1 with the previous package all the way back in April as 9.0.0-preview.4.24210.1

Just a bit of natural curiosity - All the other packages for preview 6 are with build number 24327, however this one you just pushed (Microsoft.EntityFrameworkCore.Relational.Specification.Tests) is 24322. Any particular reason? Only reason I picked it up was I was setting the version with `$(EFCoreVersion)`. Its easy enough to specify the exact version for that dependency and since the builds are so close together there shouldn't be anything incompatible
