### ISSUE TITLE
Add UpdateAsync method.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#34237]
Here's the xmldoc part of `Update` method:
>For entity types with generated keys if an entity has its primary key value set
then it will be tracked in the <see cref="EntityState.Modified" /> state. If the primary key
value is not set then it will be tracked in the <see cref="EntityState.Added" /> state.
This helps ensure new entities will be inserted, while existing entities will be updated.
An entity is considered to have its primary key value set if the primary key property is set
to anything other than the CLR default for the property type.

Effectively this means that `Update` is smart and behaves as `Add` in some cases. But then there's the same motivation for it to be async
like `Add` has async version: To account for id generation strategies which involve querying the store.

**Comment by ajcvickers** [comment]
@voroninp If you care about async Add, then you should be explicit about using `AddAsync` directly. We discussed this in the past, and decided not to further propagate the async here, partly because of #30957.
