### ISSUE TITLE
Multiple instances of same entity when using Include+AsNoTrackingWithIdentityResolution and retrieving entity directly

### ISSUE THREAD

**Issue by battbjorn** [dotnet/efcore#34235]
## Problem
I currently have a situation where I need to retrieve an entity 'Contract' from the database and perform a series of validation checks.
If the checks pass, we retrieve a list of 'BillingPeriods' that all reference the 'Contract'. The problem is that the Navigation properties all point to a wrong/new instance of the Contract instead of the one already received prior in the code. 

When the billing periods are retrieved, the Navigation property of Contract is included. The query is executed as a non tracking query. This is because we will perform domain logic to decided which item of the list should be selected to be used. This results in one billing period. The billing period is adjusted as needed.

```
var until = new DateOnly(2024, 07, 01);
var contract = context.ClientContracts.Single(c => c.Id == 1396);
// Perform logic on the contract. This logic might or might not update the contract's fields
// ..

// Retrieve billing periods and select the correct one using domain logic
var allBillingPeriodsForContract = context.BillingPeriods.AsNoTrackingWithIdentityResolution()
                                                         .Include(bp => bp.ClientContract)
                                                         .Where(bp => bp.ContractId == contract.Id
                                                                   && bp.EndDate <= until)
                                                         .ToList();

var specificBillingPeriod = GetSpecific(allBillingPeriodsForContract) // logic to determine the period, that uses the Contract Navigation property

// Adjust the billing period
specificBillingPeriod.Status = BillingPeriodStatus.Calculating;
//...

context.Update(specificBillingPeriod); // Will fail
```
Context.Add(billingPeriod) will throw an exception that the contract entity is tracked twice.
```
Unhandled exception. System.InvalidOperationException: The instance of entity type 'ClientContract' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached
```

 ## Question
Is there a way to have EF match the entities meant in .Include() to be drawn from the in memory context if available?
In the example above, let it get the same instance of the contract retrieved earlier? 

Currently, the Contracts in the 'allBillingPeriodsForContract' are all different instances if one uses `AsNoTracking`. If one uses `AsNoTrackingWithIdentityResolution` then the Contracts are the same instance, but still a different instance compared to the Contract retrieved directly.
![afbeelding](https://github.com/user-attachments/assets/1671c709-9961-4c11-a382-77b6e30d0c5a)

Using EF core 8.0.2

**Comment by ajcvickers** [comment]
> Is there a way to have EF match the entities meant in .Include() to be drawn from the in memory context if available?
In the example above, let it get the same instance of the contract retrieved earlier?

There isn't a way to do this and it's not something we will add. No tracking queries intentionally don't interact with tracked entities--that's one of the primary reasons for using them, for example to get database values after the tracked entity has been updated.
