### ISSUE TITLE
TakeWhile aggregate fulfills a condition?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#3426]
Hi,

``` C#
Consider the following entity:

    public class Product
    {
      public int Id { get; set; }
      public int Credit { get; set; }
      public DateTime Date { get; set; }
    }
```

Then:

``` C#
    var creditToDeduct = 15;
    var query = context.Products
                         .OrderBy(p => p.Date);
```

Now I want to iterate and start 'taking' products until I have enough products to deduct creditToDeduct from.

I've seen [this](http://stackoverflow.com/a/7402438/75500) answer on SO, but it targets LINQ to Objects.

What I would like to achieve, is a LINQ to Entities implementation of that.  
I'm sure it can be achieved with Expression Trees, can it? Where is the source code of the original `TakeWhile` ex. method for the SQL provider in the EF codes, I've been searching for it and couldn't find it.

How about implementing this feature out-the-box for next versions of EF?

**Comment by ajbeaven** [comment]
`SkipWhile` would also be helpful in order to support inclusive `TakeUntil`-like queries like so:

```
var items = context.Items;
var filteredItems = items.TakeWhile(i => i.IsEnd).Union(items.SkipWhile(i => i.IsEnd).Take(1));
```

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
