### ISSUE TITLE
Link https://aka.ms/efcore-docs-trimming is broken

### ISSUE THREAD

**Issue by optsing** [dotnet/efcore#34279]
If I enable trimming in a project with EFCore 8 I get warning:

`Using member 'Microsoft.EntityFrameworkCore.DbContext.DbContext()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. EF Core isn't fully compatible with trimming, and running the application may generate unexpected runtime failures. Some specific coding pattern are usually required to make trimming work properly, see https://aka.ms/efcore-docs-trimming for more details.`

https://aka.ms/efcore-docs-trimming doesn't work - it just opens Bing

EF Core version: 8.0.7
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 8.0.7
Operating system: Windows 11
IDE: Visual Stuio 17.11.0 Preview 5

**Comment by ajcvickers** [comment]
@roji @AndriySvyryd Is there a placeholder page we can point this to for now?

**Comment by roji** [comment]
@ajcvickers I think this can point to the new [NativeAOT and precompiled queries](https://learn.microsoft.com/en-us/ef/core/performance/nativeaot-and-precompiled-queries) page. That page doesn't deal with trimming per se, but I think at this point many people looking for trimming are probably doing NativeAOT? We can always incorporate trimming-specific information into that page later, if people request it.
