### ISSUE TITLE
ExecuteSqlRaw() works but ExecuteSql() no longer does

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#34277]
### Include your code

The below line of code with `ExecuteSql()` used to work without any issues. I noticed that it runs but has no actual effect, and I need to use `ExecuteSqlRaw()` instead for the SQL to actually execute.

What could cause this situation to occur?

```C#
context.Database.ExecuteSql($"delete from MyDb.dbo.MyTable where value1 = ‘{myValue}’ and value2 = {GetData().Value}”);
```

### Include provider and version information

EF Core version: 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows Server

**Comment by roji** [comment]
Try removing the single quotes around your first parameter (just like you don't have them around the second).

**Comment by mrlife** [comment]
Thanks, @roji. That worked, even though `myValue` is a string. Does EF Core add the single quotes for interpolated string values and is that a recent change at all?

**Comment by roji** [comment]
> Does EF Core add the single quotes for interpolated string values and is that a recent change at all?

No, that's not how parameterization works in SQL - the single quote is only there for string **literals**, and are not used with parameter placeholders. This is all shown in the samples of [our docs](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries), and has always been the case.
