### ISSUE TITLE
New Provider: Transaction management in specification tests

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#34294]
Still plugging away on this new implementation of efcore provide for a proprietary database. I've noticed while working through some of these tests, that if I encounter a test in some place, a query will result in an exception being thrown (which is fine and expected) but it appears the connection is reused across these tests, and because the transaction is associated with the connection... another test will execute that involves transactions (or perhaps db cleanup) every test after that will begin to fail because it attempts to create a new transaction.

I really don't think this is something I'll see in the real world all that often, but I am curious if anyone has ideas how best to handle this. As far as the specification test runs, I feel like it could make sense to just say if an exception was encountered, and transaction wasn't aborted, abort... but I don't know if this should be handled a different way.

If there is a way to have a test store essentially grab a new connection each time (we handle transaction cleanup when connection is closed) this could help here, and potentially still run nearly as fast... but I feel like that would be more of a bandaid on cancer rather than cutting out the cancer in the first place

EF Core version:
Database provider: custom
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
@ronnyek isn't that a problem with the ADO.NET provider being used? In other words, after a failure (exception) shouldn't the connection state be cleaned up properly so you can reuse it?

**Comment by ronnyek** [comment]
You know, I think you are right, and I do think that would be beneficial there. I'd assume the npgsql driver has an implementation that does that... I'll look around in there to get idea of how you all handle it

**Comment by roji** [comment]
Great - definitely try comparing to Npgsql/SqlClient and see if your ADO.NET provider is somehow misbehaving or lacking functionality. I'll go ahead and close this for now, but if you think we need to change something on the EF side (or just want to ask further questions), post back here.
