### ISSUE TITLE
Change default SQL Server compat level to 150 (SQL Server 2019)

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#34316]
We [discussed at length](https://github.com/dotnet/efcore/issues/30163#issuecomment-1500556463) what the default should be in EF8. The last statement on this was:

> Executive architect decision: we'll default to the latest compatibility level (currently 160, SQL Server 2022). In any case, we don't expect to use any super-new feature which would block users with slightly older databases.

But then we did this #22924, which only works from level 160, which SQL Server 2022 or later. This means anyone updating to EF9 will need to either have SQL Server 2022, or set the compat level explicitly.

Instead, we are changing our previous decision and making the default 150, or SQL Server 2019. This is not a breaking change because nothing generated by EF8 requires 160.

**Comment by ErikEJ** [comment]
Or make it even lower? Like 130?

**Comment by ranma42** [comment]
> We discussed at length what the default should be in EF8. The last statement on this was:

The discussion link points at this issue 🤔

**Comment by ajcvickers** [comment]
@ranma42 Fixed the link.
