### ISSUE TITLE
Net 8 Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 

### ISSUE THREAD

**Issue by Hoai-Phong** [dotnet/efcore#34322]
### Include provider and version information
When my version was on net 6 it was working fine, And after updating to Net 8 in the development environment it was working fine.
But when I deployed to the server this error occurred:

EF Core version:
![image](https://github.com/user-attachments/assets/4eff3852-3cc1-48ca-a0d6-adc9037e5bba)

```C#

2024-07-31 12:52:15.0381 ["88888195"] [18014398511092599104] [ERROR] Microsoft.EntityFrameworkCore.Database.Command Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`6.Log() Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [m].[ID], [m].[CreateDate], [m].[Restriction], [m].[TargetName], [m].[UpdateDate], [m].[UpdateUser]
FROM [MT_IDE_LEASE_TARGET] AS [m]
WHERE [m].[ID] = 2 
Log:
 Microsoft.EntityFrameworkCore.Query Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`3.Log() An exception occurred while iterating over the results of a query for context type 'xxx.xxx.IDEContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Object name 'MT_IDE_LEASE_TARGET' is invalid.

```
![image](https://github.com/user-attachments/assets/dd34e121-f60d-4059-99b4-215726190475)

Server setting :
![image](https://github.com/user-attachments/assets/ef76688e-189e-4fff-a6a7-a1c6c37a714b)
![image](https://github.com/user-attachments/assets/2846a40e-6fe4-444f-8ea2-c63a7b9dc77c)
![image](https://github.com/user-attachments/assets/5ebf6e5d-d65a-4ee3-8f33-14d7b39d93e9)

I tried to fix it but don't know why.

**Comment by ErikEJ** [comment]
@Hoai-Phong Are you connecting to the correct database in production?

**Comment by Hoai-Phong** [comment]
@ErikEJ  yes, i checked it already.
![Uploading 7-31-2024 1-22-33 PM.png…]()

**Comment by Hoai-Phong** [comment]
Thanks, when I solved the problem, When Publish it generated wrong desired connection string.
