### ISSUE TITLE
Microsoft.EntityFrameworkCore.SqlServer requires Microsoft.WindowsDesktop.App since 8.0.2

### ISSUE THREAD

**Issue by markusbettig** [dotnet/efcore#34331]
I've got a .NET Core project targeting Windows that was just upgraded to .NET 8 which now required Microsoft.WindowsDesktop.App to be installed. This previously wasn't the case. I've narrowed down the cause of this issue to the upgrade of Microsoft.EntityFrameworkCore.SqlServer from 8.0.1 to 8.0.2.

I've created a sample GitHub repo showing this behaviour (on ubuntu-latest, it actually causes the build to break):

https://github.com/markusbettig/EFCoreSqlServerDesktopAppIssue/

- Green build with 8.0.1, *not* requiring Microsoft.WindowsDesktop.App (see EFCoreSqlServerDesktopAppIssue.runtimeconfig.json in build artifact): https://github.com/markusbettig/EFCoreSqlServerDesktopAppIssue/actions/runs/10198901280
- Failing build with 8.0.2 on ubuntu-latest: https://github.com/markusbettig/EFCoreSqlServerDesktopAppIssue/actions/runs/10198957700
- Green build with 8.0.2 on windows-latest, requiring Microsoft.WindowsDesktop.App (see EFCoreSqlServerDesktopAppIssue.runtimeconfig.json in build artifact):
https://github.com/markusbettig/EFCoreSqlServerDesktopAppIssue/actions/runs/10199277884

**Comment by ErikEJ** [comment]
@markusbettig  why is that an issue for you?

**Comment by markusbettig** [comment]
> @markusbettig why is that an issue for you?

Because we're only deploying the hosting bundle, which does not include Microsoft.WindowsDesktop.App.

So should I expect this dependency to remain?

**Comment by ErikEJ** [comment]
How come are you targeting net8.0-windows and expecting a build to pass on Ubuntu?

It is an Azure.Identity bug/issue. Simple fix:

<PackageReference Include="Azure.Identity" Version="1.12.0" />

**Comment by markusbettig** [comment]
> How come are you targeting net8.0-windows and expecting a build to pass on Ubuntu?
> 
> It is an Azure.Identity bug/issue. Simple fix:
> 
> `<PackageReference Include="Azure.Identity" Version="1.12.0" />`

I simply forgot to change the runs-on setting at first, which is why I changed it later.

That did the trick, thank you very much, @ErikEJ!

**Comment by ErikEJ** [comment]
Great, thanks for confirming!
