### ISSUE TITLE
Big difference in execution between EF-linq and SSMS-Sql

### ISSUE THREAD

**Issue by domenicocanavero** [dotnet/efcore#34330]
I have a query to load my grid that it is quit slow.
I compared the execusion time between my source code with EF-linq to and sql script executed by SSMS

The database used is SQLExpress 2019 installed on my PC, an example of the times.

This is the linq query:

skip=34080
take=24

        var ll = await (from oH in dbcontext.HisOrderHeader
                        join lL in dbcontext.HisOrderLine on oH.Id equals lL.IdHeader
                        join cC in dbcontext.HisOHContainer on oH.Id equals cC.IdHisOrderHeader
                        join dD in dbcontext.HisOHCDivision on cC.Id equals dD.IdHisOhcontainer
                        orderby oH.EndScrap, cC.Id descending
                        select new
                        {
                            order = oH.NameOrder,
                        }
                        ).AsNoTracking().Skip(skip).Take(take).ToListAsync();

The query returns the last 11 records of my DS in **33 seconds**.

This is the log of the command execution:
            _Executing DbCommand [Parameters=[@__p_0='34080', @__p_1='24'], CommandType='Text', CommandTimeout='300']
                  
            SELECT [h].[NameOrder]
            FROM [M2FMetallurgy].[HisOrderHeader] AS [h]
            INNER JOIN [M2FMetallurgy].[HisOrderLine] AS [h0] ON [h].[Id] = [h0].[IdHeader]
            INNER JOIN [M2FMetallurgy].[HisOHContainer] AS [h1] ON [h].[Id] = [h1].[IdHisOrderHeader]
            INNER JOIN [M2FMetallurgy].[HisOHCDivision] AS [h2] ON [h1].[Id] = [h2].[IdHisOHContainer]
            ORDER BY [h].[EndScrap], [h1].[Id] DESC
            OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY_

This is the sql query executed with SSMS and the results:
![image](https://github.com/user-attachments/assets/ea1ad515-039d-461a-ad1a-9320bc10e0a8)

**Execution time is less then 1 sec.**

**33 sec. VS 1 sec.**
The difference is too much, what you think?

Thanks

My environment:
              EF Core version: 8.0.7
              Database provider: Microsoft.EntityFrameworkCore.SqlServer
              Target framework: .Net 8
              Operating system: Windows 10
              IDE: Visual Studio 2022 community 17.10.4)

**Comment by roji** [comment]
Can you please execute the SQL generated by EF exactly as-is in SSMS when comparing; for instance, with EF the OFFSET clause has parameters, whereas in the non-EF SQL they're constants (you can use EF's ToQueryString() to get the exact SQL to try to execute). This way we can be sure exactly what the difference is.

If indeed the only difference between the slow and fast SQL is the parameterization of the OFFSET arguments, then this looks like #28632.

**Comment by domenicocanavero** [comment]
I created and ran this table function:

        _USE [ApplicationsData]
        GO
        /****** Object:  UserDefinedFunction [M2FMetallurgy].[FnTab_GetHisContainers]    Script Date: 01/08/2024 15:56:00 ******/
        SET ANSI_NULLS ON
        GO
        SET QUOTED_IDENTIFIER ON
        GO
        
        -- =============================================
        -- Author:		<Author,,Name>
        -- Create date: <Create Date,,>
        -- Description:	<Description,,>
        -- =============================================
        ALTER FUNCTION [M2FMetallurgy].[FnTab_GetHisContainers]
        (	
        @skip	int,
        @take	int
        )
        RETURNS TABLE 
        AS
        RETURN 
        (
			        select OH.NameOrder from M2FMetallurgy.HisOrderHeader OH
			        inner join M2FMetallurgy.HisOrderLine LL ON OH.Id = LL.IdHeader
			        inner join M2FMetallurgy.HisOHContainer CC ON OH.Id = CC.IdHisOrderHeader
			        inner join M2FMetallurgy.HisOHCDivision DD ON CC.Id = DD.IdHisOHContainer
			        order by OH.EndScrap, CC.Id DESC
			        OFFSET @skip ROWS
			        FETCH NEXT @take ROWS ONLY
        )_

**Quickly, 1 sec.**


And then tried with this query:

            _DECLARE @skip int
            DECLARE @take int
            
            SET @skip = 34080
            SET @take = 24
            
            select OH.NameOrder from M2FMetallurgy.HisOrderHeader OH
            inner join M2FMetallurgy.HisOrderLine LL ON OH.Id = LL.IdHeader
            inner join M2FMetallurgy.HisOHContainer CC ON OH.Id = CC.IdHisOrderHeader
            inner join M2FMetallurgy.HisOHCDivision DD ON CC.Id = DD.IdHisOHContainer
            order by OH.EndScrap, CC.Id DESC
            OFFSET @skip ROWS
            FETCH NEXT @take ROWS ONLY_
            
**With this another result, 13 sec.**

I'm confused ...

**Comment by domenicocanavero** [comment]
I close this issue.
My initial question was poorly phrased and my example was wrong.
