### ISSUE TITLE
Enable EF.Parameter for forcing parameterization of collection parameters

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#34345]
#34344 will allow users to configure whether parameterized collections should parameterized by default (e.g. via OPENJSON, this is the current default), or constantized (as Contains did before 8.0); we are also considering changing the default mode back to constantization in 10.

If users choose to default to constantization, there should be a way to specify for specific collections of specific queries that they should be constantized. EF.Parameter was already introduced in 8.0 (#28151) as a way to force parameterization even when the query contains a constant; this can be useful for some scenarios of dynamic query tree construction, as well as F# where captured variables are always constantized.

We should make EF.Parameter also cause the parameterization of collection parameters, similar to how EF.Constant can cause them to get constantized.

**Comment by IanKemp** [comment]
@roji this should probably also be added to https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#mitigations-1, especially since https://github.com/dotnet/EntityFramework.Docs/issues/4817 is not yet done.

**Comment by roji** [comment]
@IanKemp I'm not sure how documenting EF.Parameter makes sense specifically in that breaking change note, which is about the Contains perf regression in 8.0; EF.Constant makes sense since it's a per-query mechanism for opting **out** of parameterizing the collection (which is the source of the performance regressions), but EF.Parameter is only useful for opting back **into** parameterization after having changed the default.

I do plan to do a query documentation push at some point - and https://github.com/dotnet/EntityFramework.Docs/issues/4817 would be a part of that - but documenting EF.Parameter doesn't seem terribly important until that happens.
