### ISSUE TITLE
Cosmos: incorrect result when projecting out-of-bounds element of an owned collection

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#34351]
query:

```
        => AssertQueryScalar(
            async,
            ss => ss.Set<JsonEntityBasic>().OrderBy(x => x.Id).Select(x => (int?)x.OwnedCollectionRoot[25].Number),
            ss => ss.Set<JsonEntityBasic>().Select(x => (int?)null));
```

this returns no results on cosmos. I'd expect to still see a result (presumably with value null)

**Comment by ajcvickers** [comment]
@maumar I believe this is by-design because of the way Cosmos SQL propagates undefined values and then they are excluded from the VALUE results. Can you post the SQL? (This is something we have discussed with the Cosmos folks already.)

**Comment by maumar** [comment]
```sql

SELECT VALUE c["OwnedCollectionRoot"][25]["Number"]
FROM root AS c
WHERE c["Discriminator"] == "Basic"
ORDER BY c["Id"] ASC
```
