### ISSUE TITLE
Allow an IConnSource on Entity Constructor to IOC custom secure string connector

### ISSUE THREAD

**Issue by ramoneeza** [dotnet/efcore#3435]
I'm using a IConnSource interface to enable custom connectionstring securing (Via AES and AD).

I think is a good Idea and could be enable in future versions of EF.

``` csharp
public interface IConnSource
    {
        string EFStrConn { get; }
        string StrConn { get; }
    }
```

**Comment by rowanmiller** [comment]
There shouldn't be anything preventing you from passing this into the constructor of your context (or having it resolved and passed in from DI) and then using it to control where you connect. If you are hitting issues with this perhaps you could share the exact situation that is not working?
