### ISSUE TITLE
Configuration of Entities using inheritance that add incoming relationships to a base entity without any real discriminator

### ISSUE THREAD

**Issue by thecrappycrapper** [dotnet/efcore#34368]
## Description 
I have an entity called "User" that is part of my Core.Domain project. The user entity is used across the entire solution, as it's being referenced by other entities. The user entity contains all fields from the USER table. 
There are two instances, in which the User is inherited from user entities of different Projects - "PermissionUser" and "Moderator". 
In both cases, the inheriting classes solely add references from other Tables (Entities) to the User table. 
In the case of the PermissionUser, this is done to have separate Security projects.
```C#
    public class PermissionUser : User, IAggregateRoot
    {
        public ICollection<PermissionGroup> PermissionGroups { get; set; }
    ....
```
In the case of Moderator, this is done to encapsulate functionality like relationships to Bookings and other booking-specific functionality from the core user in separate projects.
```C#
    public class Moderator : PermissionUser, IAggregateRoot
    {
        public ICollection<ModeratorAbsence> Absences { get; set; }
        public ICollection<Booking> Bookings { get; set; }
        public ICollection<BookingModeratorAssignment> BookingAssignments { get; set; }
        public ICollection<ModeratorOrgUnitAssignment> OrgUnitAssignments { get; set; }
    ....
```
As far as I know, in this case, there is no real discriminator that can be set. Previously, we had a rather illegal configuration that only seemed to work because Entity Framework didn't specifically prevent it. 
The user configuration looks somewhat like this: 

```C#
        public override void ConfigureTableName(EntityTypeBuilder<User> builder)
        {
            builder.ToTable("USER");
        }

        public override void ConfigureRelations(EntityTypeBuilder<User> builder)
        {
            builder.HasKey(x => x.Id);

            builder.HasOne(u => u.AssignedOrganizationalUnit)
                .WithMany(o => o.Employees)
                .HasForeignKey(u => u.AssignedOrganizationalUnitId);

            ....
        }

        public override void ConfigureProperties(EntityTypeBuilder<User> builder)
        {
            builder.HasNoDiscriminator();

            builder.Property(s => s.Id)
                .HasColumnName("U_ID");

            builder.Property(s => s.AssignedOrganizationalUnitId)
                .HasColumnName("OID");
           ....
        }
```
All of those methods get called in the Configure Method of an abstract class that implements IEntityTypeConfiguration<TEntity>

The PermissionUserConfiguration looks something like this
```C#
        public override void ConfigureRelations(EntityTypeBuilder<PermissionUser> builder)
        {
            builder
                .HasMany(g => g.PermissionGroups)
                .WithMany(u => u.Users)
                .UsingEntity<GenericManyToManyAssignment<PermissionGroup, PermissionUser>>(
                    ....
                    });
        }

        public override void ConfigureTableName(EntityTypeBuilder<PermissionUser> builder)
        {
            builder.ToTable("uSer");
        }
```
The dbcontext of the PermissionUserRepository gets the configurations for both the Core User entity and the permission user.

## Problem 
This configuration only works as long as the table case is different. If the ToTable call in the PermissionUserConfigration instead was 
builder.ToTable("USER"), this exception will arise. Removing the call to "builder.ToTable()" from the PermissionUserConfiguration will create the same exception.
```
InvalidOperationException: Both 'PermissionUser' and 'User' are mapped to the table 'USER'. All the entity types in a non-TPH hierarchy (one that doesn't have a discriminator) must be mapped to different tables. See https://go.microsoft.com/fwlink/?linkid=2130430 for more information.
```

Therefore, the configuration shouldn't really have worked in EntityFrameworkCore 5.0.17 and now that we are updating to .NET 8 with EntityFrameworkCore 8.0.7 it doesn't anymore. 
The first call to load a PermissionUser now throws this exception.
![image](https://github.com/user-attachments/assets/750343c6-c50c-442d-be90-5d5eef20f61c)

Even though the previous configuration was "illegal", it worked perfectly. 

## Question
My question now is, how do you expect a case like this to be configured properly?

**Comment by thecrappycrapper** [comment]
I was playing around with different versions of EfCore and found out that the latest version the configuration still works is Microsoft.EntityFramworkCore 6.0.32

**Comment by AndriySvyryd** [comment]
You can "trick" EF to not treat the derived types as being in the same hierarchy by calling `builder.HasBaseType((string)null)`. However, the base configuration will no longer be applied automatically, so you'd need to repeat it. Note that the relationships can only point to a single type, so any navigation pointing to `User` can't be used for `PermissionUser`.

Then, EF will allow both to be mapped to the same table through table splitting: `builder.HasOne<Operator>().WithOne().HasForeignKey<OperatorDetails>(x => x.Id)`. However, you won't be able to persist a new derived entity by itself until #15310 is implemented.

But taking a step back, both the above and your original approach come with many restrictions, because EF's model no longer matches well the types that you expose. So, an alternative solution is to only include the most derived type in the model - `Moderator`. And call
```C#
modelBuilder.Ignore<User>();
modelBuilder.Ignore<PermissionUser>();
```
Any relationships to `User` or `PermissionUser` would need to be configured from the `Moderator` side or by specifying the type explicitly:

```C#
modelBuilder.Entity<Project>().HasMany<Moderator>("Users")
        .WithOne(o => o.Project);
```

With this approach you would need to make sure that all instances are of type `Moderator`. The easiest way of doing this is by making `User` and `PermissionUser` abstract
