### ISSUE TITLE
Possible memory leak in relation to (larger) strings

### ISSUE THREAD

**Issue by MontyGvMC** [dotnet/efcore#34365]
## File a bug

A bug in the filter of our software (causing the full db to load) revealed something that seems like a memory leak in EFC to me.

The software loads 6 GB (mainly strings between 50KB and 150KB) from the DB and returns it as result.

My expectation would be that the 6 GB memory will be released at some point and memory goes down.
But this isn't the case. The memory consumption remains high.

![image](https://github.com/user-attachments/assets/cd3cb139-601b-44b8-9d00-3fd25fd81c8c)

Can anyone proof this is a memory leak because I am not able to find the data profiling the RAM (I am new to memory profiling).

Currently I don't know of any code I could call to release this memory.

### Include your code

[LargeStringMemoryLeak.zip](https://github.com/user-attachments/files/16507064/LargeStringMemoryLeak.zip)

I were able to create a small sample that reproduces the issue with random data.

Just start the downloaded application and click GET in Swagger.
This demonstrates the growth of memory and proofs the used RAM stays high.

Unfortunatly I haven't had the chance to test with the neweset version (cause I am currently not allowed to install new .NET version) on this machine.

### Include provider and version information

EF Core version: 6.0.32
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
Are you seeing an OutOfMemoryException at some point? If so, then this could indeed be a memory leak; if not, then there's no reason to suspect one. The .NET GC reclaims memory based on various considerations, and it's very possible it simply hasn't kicked in yet; a real memory leak is a case where memory cannot be garbage-collected - because it is still being referenced - and that should lead to an  OutOfMemoryException at some point.

**Comment by MontyGvMC** [comment]
I am not facing OutOfMemory exceptions but we are facing other side effects.
The issue occurs on an industrial PC hosting multiple services for our customer. 
The memory remains unusable for the other services causing ~95% (of 16GB)  memory usage in total.
5 to 8 GB are taken by the service reading the database.

Which not only causes issues on the effected system but also on the other services running on the system.

> and it's very possible it simply hasn't kicked in yet 

So for me it actually looks like GC never kicks in. since memory stays high till we restart the service.
Varying from a couple of hours or days depending on how fast we are called by the customer.

> because it is still being referenced 

So I did my best to create a reproducable sample where I ensured there are no references left over. (ifrom my side)

**Comment by roji** [comment]
> So for me it actually looks like GC never kicks in.

If the GC never kicked in, you would most definitely see an OutOfMemoryException; the fact that memory usage stays high is a natural way for .NET applications to behave, and has nothing to do with EF Core.

If you'd like to reduce the memory footprint of your application, I'd suggest trying out the GC's workstation mode; [read these ASP.NET docs on memory management](https://learn.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-8.0#workstation-gc-vs-server-gc), and possibly also [these](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc).
