### ISSUE TITLE
A very strange case of DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by dmitriy-dokshin** [dotnet/efcore#3437]
http://stackoverflow.com/questions/33149719/a-very-strange-case-of-dbupdateconcurrencyexception/33149720

**Comment by ajcvickers** [comment]
@divega @rowanmiller This no longer repros because a) we should get the parameter type correct now and b) we don't use this mechanism in the update pipeline anyway. Can we close, or at least remove from RTM milestone?

**Comment by rowanmiller** [comment]
If it's no longer an issue then closing is fine

**Comment by divega** [comment]
> This no longer repros because...

Yes. I came to the same conclusion last night. 

Closing.
