### ISSUE TITLE
Create default implementation of IDatabaseModelFactory

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3438]
It is maybe possible to provide a base implementation of IMetadataReader so that provider-writers only need to give us SQL queries to make reveng work. Use `INFORMATION_SCHEMA`

Related https://github.com/aspnet/EntityFramework/issues/1667

**Comment by rowanmiller** [comment]
We should look at using EF when we do this

**Comment by natemcmaster** [comment]
Made some discoveries from an attempted implementation in EF. 

Need to have:
 - https://github.com/aspnet/EntityFramework/issues/3945
 - https://github.com/aspnet/EntityFramework/issues/3943

Nice to have:
 - https://github.com/aspnet/EntityFramework/issues/3944
 - https://github.com/aspnet/EntityFramework/issues/3942
 - #621

**Comment by rowanmiller** [comment]
As a workaround to #3943 you should be able to put these things in shadow state and then after you execute the query run some additional logic to copy the values out of the change tracker into the annotations.

**Comment by divega** [comment]
@natemcmaster is the materialization hook you mention in #3943 a need to have in the sense that you cannot resolve this issue (#3438) without it? I would like to understand if it can be worked around.

**Comment by natemcmaster** [comment]
Listing the limitations above was more about minimizing workarounds and driving useful features in EF. They can all be worked around.

@divega #3943 can be a "nice to have" since we don't plan to support multiple rows => one entity (#3945).

> copy the values out of the change tracker

@rowanmiller this was my original approach. Of course this means I *have to* use the change tracker ( see https://github.com/aspnet/EntityFramework/issues/2282#issuecomment-161070921)

**Comment by rowanmiller** [comment]
@natemcmaster we agreed not to use EF for loading metadata, but is the more general scenario covered by this issue (providers just needing to provide SQL) done?

**Comment by natemcmaster** [comment]
This general scenario is not done. We still only have a Sql Server and SQLite implementation with no shared implementation.
