### ISSUE TITLE
EF Core memory leak

### ISSUE THREAD

**Issue by yoganr** [dotnet/efcore#34409]
We have memory leak in our application which grows over a week. Help would be appreciated on why Heap generation 2 grows and why ServiceProviderEngineScope is retaining so much memory. Here are dotmemory tracking,
 
![image](https://github.com/user-attachments/assets/b3b33b64-6089-4c13-ae38-82189f1433c3)

Here is the dominators map

![image](https://github.com/user-attachments/assets/fe92566e-8692-4e3b-ac23-d42df22e1fd9)

Thanks in advance

**Comment by RezaRahmatzadeh** [comment]
Consider the correct way of using `.AsNoTracking()` in your project whenever you don't need or want to edit or manipulate fetched data (it often happens in report usage scenarios)

**Comment by ajcvickers** [comment]
@yoganr Please post the `OutOfMemoryException` including stack trace.

**Comment by yoganr** [comment]
> @yoganr Please post the `OutOfMemoryException`, including stack trace.

We got it solved with memory leakage in our singleton class which was resolving Services from root scope, when we change it to create new scope seems to resolved the issue. Thanks for the help guys!
