### ISSUE TITLE
Reverse engineering error on scaffolding

### ISSUE THREAD

**Issue by matteomigliore** [dotnet/efcore#3440]
I followed <a href="http://stoutcloud.com/geek-out-entity-framework-7/geek-ef7-reverse-engineering-first-look">this article</a> to generate code first from an existing DB.

When I launch the command "dnx ef dbcontext scaffolding" I obtain the error:

<pre>
EntityFramework.SqlServer
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Data.Entity.Relational.Design.ReverseEngineering.IDatabaseMetadataModelProvider'
 while attempting to activate 'Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory,TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.DatabaseOperations.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, List`1 schemas, List`1 tables, Boolean useDataAnnotations, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass11_0.<<ReverseEngineerAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Commands.Program.Executor.<ExecuteAsync>d__13.MoveNext()
Unable to resolve service for type 'Microsoft.Data.Entity.Relational.Design.ReverseEngineering.IDatabaseMetadataModelProvider' while attempting to activate 'Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator'.
</pre>

My project.json:

``` json
{
    "webroot": "wwwroot",
    "version": "1.0.0-*",

    "dependencies": {
        "EntityFramework.Commands": "7.0.0-rc1-15945",
        "EntityFramework.SqlServer": "7.0.0-rc1-15886",
        "EntityFramework.SqlServer.Design": "7.0.0-rc1-15886",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta8-15609",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-rc1-15727"
    },

    "commands": {
        "web": "Microsoft.AspNet.Hosting --config hosting.ini",
        "ef": "EntityFramework.Commands"
    },

    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    },

    "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ],
    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ]
}
```

P.S.
Is there a designer?

**Comment by natemcmaster** [comment]
Upgrade your project.json to

```diff
   "dependencies": {
         "EntityFramework.Commands": "7.0.0-rc1-15945",
-        "EntityFramework.SqlServer": "7.0.0-rc1-15886",
-        "EntityFramework.SqlServer.Design": "7.0.0-rc1-15886",
+        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-15945",
+        "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-15945",
         "Microsoft.AspNet.Server.IIS": "1.0.0-beta8-15609",
```

Please respond if this solved the issue.

Another tip: when working with our nightly builds, make sure you are always using the exact same build number for all EF.* packages. These are all build against each other.

**Comment by natemcmaster** [comment]
PS - there is no designer.

**Comment by matteomigliore** [comment]
I change the project.json, now the error is:
<pre>
Unable to find provider assembly with name EntityFramework.SqlServer. Ensure the
 specified name is correct and is referenced by the project.
</pre>

My dependencies in project.json:
```json
	"dependencies": {
		"EntityFramework.Commands": "7.0.0-rc1-15945",
		"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-15945",
		"EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-15945",
		"Microsoft.AspNet.Server.IIS": "1.0.0-beta8-15609"
	}
```

Is there a roadmap for the designer?

**Comment by natemcmaster** [comment]
This is expected behavior. The command parameter asks for the assembly name, which is now EntityFramework.MicrosoftSqlServer. 

About the designer: EF7 is primary code-first (see [this blog post](http://blogs.msdn.com/b/adonet/archive/2014/10/21/ef7-what-does-code-first-only-really-mean.aspx)). There are no plans to port the EF6 designer to EF7. There may be some GUI tools later (no promises as I'm not aware any more details.)

**Comment by matteomigliore** [comment]
Ok, I found, now the command must be:
<pre>
dnx ef dbcontext scaffolding "Server=.;Database=DBName;Trusted_Connection=True;" EntityFramework.MicrosoftSqlServer
</pre>

But now I get the error:
<pre>
Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture
=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The syste
m cannot find the file specified.
</pre>

**Comment by matteomigliore** [comment]
Ok, everything works now.

It was a little bit difficult.

I executed many times the commands:
1. SET DNX_FEED=https://myget.org/F/aspnetcidev/api/v2
2. dnvm upgrade
3. dnvm install -r core clr latest
4. dnu restore

Thank you.

**Comment by natemcmaster** [comment]
@matteomigliore welcome to the fun world of working with nightly builds.

**Comment by matteomigliore** [comment]
@natemcmaster yes but... :sweat: 

Now I've another error opening the solution:
<pre>
Error	CS0433	The type 'HashSet<T>' exists in both 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	WebApplication1.DNX 4.5.1
</pre>

How can I fix?

**Comment by natemcmaster** [comment]
This happens when you have inconsistent package versions (likely due to your mix of beta8 and rc1 packages). Our CI tests that packages work together. When working with ASP.NET nightly builds, always pull a coherent set of packages. You can automate this by using the star placeholder, eg. `"7.0.0-*" `. (See https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/project.json)

**Comment by matteomigliore** [comment]
I removed the framework DNX 451 to compile, but I would not, otherwise I've the error above (HashSet...).

Now is possible to add a UnitTest project? It has not the project.json, I think it does now work with DNX right?

**Comment by audacity76** [comment]
EF Command (7.0.0-rc1-final) is:

dnx ef dbcontext scaffold "your connection string" EntityFramework.MicrosoftSqlServer
