### ISSUE TITLE
Create a docs link for Migrations locking

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#34428]
https://aka.ms/efcore-docs-migrations-lock

See https://github.com/dotnet/efcore/pull/34338

**Comment by ajcvickers** [comment]
@AndriySvyryd To what should it point?

**Comment by AndriySvyryd** [comment]
Just migrations docs for now

**Comment by ajcvickers** [comment]
@AndriySvyryd Done.
