### ISSUE TITLE
The message "An exception occurred while iterating over the results of a query for context type 'X'." can not be caught

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/efcore#34430]
### Include your code

Create a context, a database, and models. Then make a difference between the database and the EF Core model. Then run any code to read from the database:

```
using var context = new SomeContext();
var items = context.SomeItem.ToList();
```

You end up with an exception like this:

```
fail: 08/14/2024 07:29:05.687 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'SomeContext'.
```

No matter where I put try/catch blocks, I can't catch this message. It seems that this message is internal to the EF Core and it catches it internally, logs it, and then rethrows it.

I need to be able to extract the context name from this message. Either report back the name of the context, or somehow let us catch this exception.

### Include provider and version information

EF Core version: 8.0.2
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: net8.0
Operating system: Debian GNU/Linux 12 (bookworm)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Nefcanto** [comment]
@ajcvickers what is vague about it?

1. Create a simple model and database with a simple table with 2 or 3 columns (model-first or db-first, no difference)
2. Drop one of the columns of the table
3. Try to read using EF Core

What more information is necessary?

**Comment by ajcvickers** [comment]
@Nefcanto This bit: "No matter where I put try/catch blocks, I can't catch this message."

**Comment by Nefcanto** [comment]
@ajcvickers, now I understand. Thanks for clarifying. I encompassed the context instantiation with `try/catch`:

```
try
{
    using var someContext = new SomeContext();
    var data = someContext.SomeEntityType.ToList();
}
catch (Exception ex)
{
    // No trace of that sentence here
}
```

I expect to see the name of the context that caused the error to be in the `ex` thrown. But it's not. That sentence would be printed before the catch block hits.

**Comment by ajcvickers** [comment]
@Nefcanto I am not able to reproduce this. The test code below prints out:

```
Caught: Invalid column name 'Url'.
```

I've tried this with various providers, and I don't see any reason this would be provider-specific, but please report on the provider repo if you think it is an issue with the Pomelo provider.

Otherwise, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.


Attempted repro:

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    await context.Database.ExecuteSqlAsync($"ALTER TABLE Blog DROP COLUMN Url");

    try
    {
        context.Set<Blog>().ToList();
    }
    catch (Exception e)
    {
        Console.WriteLine($"Caught: {e.Message}");
    }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Data Source=localhost;Database=TestDb;Integrated Security=True;Trust Server Certificate=True;ConnectRetryCount=0")
            //.LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string? Url { get; set; }
}
```

**Comment by ajcvickers** [comment]
@Nefcanto I just realized, are you perhaps mistaking a log message such as, "An exception occurred while iterating over the results of a query for context type 'SomeContext'," as an exception message?

**Comment by Nefcanto** [comment]
@ajcvickers, that's a log message yes. But it belongs to an exception. The context could not be instantiated for any reason. The log message mentions the context name. But that name is lost when we want to catch the Exception.

What I get is:

```
Invalid column name 'SomeColumn'.
```

But where? We have an application with more than 100 modules each with its EF Core context. I need to be able to report the name of the context too for faster troubleshooting.

That log message is probably the result of an internal `try/catch` block. Am I right?

**Comment by Nefcanto** [comment]
@ajcvickers ideally we should be able to have this sentence:

```
Invalid column name 'SomeColumn' in 'SomeTableOrView' in 'SomeContext'
```

That's the full address.

**Comment by ajcvickers** [comment]
@Nefcanto We don't wrap exceptions thrown as part of query execution. I will discuss with the team whether we want to start doing it, but I very much doubt it, since it has been discussed many times in the past. As it stands, you get the exception from the database driver.

**Comment by Nefcanto** [comment]
@ajcvickers, first of all, thank you for your time. 
Second, the point is that we need to have more information in the exception thrown. However, I can't ask the database driver to add more info. All they can do is to add the table name. The EF Core context name is still on your side.

**Comment by ajcvickers** [comment]
We discussed this and decided to continue not wrapping query exceptions. The value of doing so, even if it is positive, is still not worth the breaking change.

@Nefcanto Consider using [interception or a diagnostic listener](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/) to obtain this information programmatically.
