### ISSUE TITLE
How does the ef core tool  find  services ?

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#34444]
## Ask a question

In previous version  ,  `dotnet-ef`  can look up for `Program.CreateWebHostBuilder()` (or `Startup)` and get the returned `IWebHostBuilder`  for get  DbContext type and other services and configuration.

but after the   minimal api  (eg. signle file entrypoint), there are no such  method, but `dotnet-ef` can still find the services and configuration.  How does this happened ?

**Comment by AndriySvyryd** [comment]
We use [HostFactoryResolver](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs#L122)
