### ISSUE TITLE
InMemory in Production

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#3446]
How would EntityFramework InMemory perform if it is use as web application object caching in production environment? I'm comparing with instantiating object graph collection and ef7. If looking at the code it should quicker to use ef7 inmemory.

**Comment by anpete** [comment]
Check out https://github.com/aspnet/Caching/tree/dev/src/Microsoft.Extensions.Caching.Memory

It is a proper cache that handles eviction etc.

**Comment by rowanmiller** [comment]
Just wanted to close the loop by saying our intent for EntityFramework.InMemory is purely for testing. If it works for you then you can certainly use it for other use-cases (we won't try and stop you :smile:)... but we're also not going to spend time fixing bugs, driving improvements, etc. that are outside out intended use case for it.
