### ISSUE TITLE
OPENJSON: Contains in string[]

### ISSUE THREAD

**Issue by LukeTOBrien** [dotnet/efcore#34475]
I have an existing project using EF6 (actually I am using [Entity Framework Classic](https://entityframework-classic.net/)) and I am now trying the update to EF Core 8.  

Today I have come across a rather strange one, my query is producing rather elaborate SQL using OPENJSON whereas in EF6 the query worked fine.  
I have just done a search for to see if anyone else had the same issue and I found: https://github.com/dotnet/efcore/issues/30946  
I have read the blog post explaining the change (https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/) but in my cause it is causing an issue and I would prefer not to use OPENJSON and just go back to something that works.

My query is:

```csharp
private static string[] licensedProducts = new string[]
{
    "ENTERPRO", "EnterPro Navigator", "ENTERPRO.WOTouchscreen", "ENTERPRO.RDTMenu", "ENTERPRO.POTouchscreenReceipts"
};
private static string[] licensedProductsToExclude = new string[]
{
    "ENTERPRO.Security", "EnterPro.RDT"
};
...
context.AuditUsers
           .Where(x => x.LogoutDateTime.HasValue == false &&
              licensedProductsToExclude.Contains(x.ProductName) == false && licensedProducts.Any(p => x.ProductName.Contains(p)))
           .Count();
```

And the resulting SQL is:

```sql
      SELECT COUNT(*)
      FROM [AuditUsers] AS [a]
      WHERE [a].[LogoutDateTime] IS NULL AND [a].[ProductName] NOT IN (
          SELECT [l].[value]
          FROM OPENJSON(@__licensedProductsToExclude_0) WITH ([value] nvarchar(128) '$') AS [l]
      ) AND EXISTS (
          SELECT 1
          FROM OPENJSON(@__licensedProducts_1) WITH ([value] nvarchar(128) '$') AS [l0]
          WHERE [l0].[value] IS NOT NULL AND (CHARINDEX([l0].[value], [a].[ProductName]) > 0 OR [l0].[value] LIKE N''))
```

The exception I am getting is:

`Incorrect syntax near '$'`

I should sayu that I think this line:

```csharp
 licensedProducts.Any(p => x.ProductName.Contains(p))
```

Is checking to see if any string in the licensedProducts array is LIKE (string.Contains) the product name.

When I set compatibility then I receive the error:

```
The LINQ expression '[Microsoft.EntityFrameworkCore.Query.ParameterQueryRootExpression]' could not be translated.
Additional information: EF Core's SQL Server compatibility level is set to 110; compatibility level 130 (SQL Server 2016) is the minimum for most forms of querying of JSON arrays.
```

So it's still trying to treat the query as JSON when all I want is for the provider to treat the query as EF6 did before.

I understand the reasoning behind using OPENJSON but TBH the SQL query generated looks weird and as the old saying goes "If it ain't broke then don't fix it".  
I would suggest that using OPENJSON is not a normal way to create a query, ie, if you were writing an SQL query yourself, you wouldn't think of using OPENJSON.  
So in my opinion this feature should be turned off by default and only use OPENJSON if the developer explicitly turns it on.

I might have to revert my changes back to EF6.

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system:
IDE: Visual Studio 2022 17.10.6

## Edit

I have just read https://github.com/dotnet/efcore/issues/32394#issuecomment-2266634632

> The plan for 9.0 is the following:
> Introduce global context options allowing users to set the default behavior here 

👌👍

**Comment by ErikEJ** [comment]
Did you really read the breaking changes docs? You database compatibility level is most likely below 130 and that is causing the error

**Comment by roji** [comment]
@LukeTOBrien as @ErikEJ wrote above, [please read this breaking change doc](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sqlserver-contains-compatibility).

**Comment by LukeTOBrien** [comment]
`Select @@version` says we are using:
```
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor)
```

I will wait until November then I can update to .NET 9 and use EF Core 9

**Comment by roji** [comment]
@LukeTOBrien please read the link above carefully; there is absolutely no need for you to wait for EF Core 9, you very likely have your SQL compatibility level set to an older version in your database. All you need to do is configure EF Core accordingly as follows:

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .UseSqlServer(@"<CONNECTION STRING>", o => o.UseCompatibilityLevel(120));
```

**Comment by stevendarby** [comment]
@roji, in his initial post he says he sets compatibility and then receives an error message, which he includes in the post

**Comment by roji** [comment]
@stevendarby thanks for the pointer. Apologies, I read this too quickly and mistakenly thought that this was about the (often complained-about) Contains() issue, where in fact the query does `licensedProducts.Any(p => x.ProductName.Contains(p))`.

EF Core indeed only supports such complex querying via OPENJSON. EF Core 9 will indeed allow the parameterized collection (licensedProducts) to be inlined as constants (so via a SQL `VALUES` expression instead of via `OPENJSON`), which should make this work.

Am curious, what SQL are you seeing for this query with Entity Framework Classic?

**Comment by LukeTOBrien** [comment]
Thanks,

I will wait until EF Core 9 until I update.  
(one day you will have to drop the Core and simply call it 'Entity Framework')

Here is the query generated by EF Classic (EF6):

```sql
SELECT
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT
        COUNT(1) AS [A1]
        FROM [dbo].[AuditUsers] AS [Extent1]
        WHERE (0 = (CASE WHEN ([Extent1].[LogoutDateTime] IS NOT NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END)) AND (0 = (CASE WHEN ([Extent1].[ProductName] IN (N'ENTERPRO.Security', N'EnterPro.RDT')) THEN cast(1 as bit) WHEN ( NOT ([Extent1].[ProductName] IN (N'ENTERPRO.Security', N'EnterPro.RDT'))) THEN cast(0 as bit) END)) AND ( EXISTS (SELECT
            1 AS [C1]
            FROM  (SELECT
                N'ENTERPRO' AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
            UNION ALL
                SELECT
                N'EnterPro Navigator' AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable2]
            UNION ALL
                SELECT
                N'ENTERPRO.WOTouchscreen' AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable3]
            UNION ALL
                SELECT
                N'ENTERPRO.RDTMenu' AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable4]
            UNION ALL
                SELECT
                N'ENTERPRO.POTouchscreenReceipts' AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable5]) AS [UnionAll4]
            WHERE ( CAST(CHARINDEX([UnionAll4].[C1], [Extent1].[ProductName]) AS int)) > 0
        ))
    )  AS [GroupBy1]
```

**Comment by roji** [comment]
Thanks for the EF Classic SQL! Yeah, EF 9.0 (we already call it that informally, without "core") produces a conceptually similar but better SQL construct (using VALUES instead of all the UNION ALLs).
