### ISSUE TITLE
Concurrency Handling in UpdateRange case

### ISSUE THREAD

**Issue by ps-nk** [dotnet/efcore#34481]
Hi,
I have implemented the typical concurrency scenario. [Resolving concurrency conflicts](https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=data-annotations#resolving-concurrency-conflicts)

```C#

try
    {
        // Attempt to save changes to the database
        context.SaveChanges();
        saved = true;
    }
    catch (DbUpdateConcurrencyException ex)
    {
        foreach (var entry in ex.Entries)
        {
            if (entry.Entity is Person)
            {
                var proposedValues = entry.CurrentValues;
                var databaseValues = entry.GetDatabaseValues();

                foreach (var property in proposedValues.Properties)
                {
                    var proposedValue = proposedValues[property];
                    var databaseValue = databaseValues[property];

                    // TODO: decide which value should be written to database
                    // proposedValues[property] = <value to be saved>;
                }

                // Refresh original values to bypass next concurrency check
                entry.OriginalValues.SetValues(databaseValues);
            }
            else
            {
                throw new NotSupportedException(
                    "Don't know how to handle concurrency conflicts for "
                    + entry.Metadata.Name);
            }
        }
    }

```

It also works for a simple update, for example. However, the whole thing as a bulk does not work for me. 
I thought I would get an entry in ex.Entries for all concurrent entities. However, there is always only one entry.

I thought the mass update with the support of concurrency configs could look like this:

```C#

try
{
    Context.UpdateRange(entities)
}
catch (DbUpdateConcurrencyException ex)
{
    foreach (var concurrencyCase in ex.Entries)
    {
      ...
    }
}

```

However, this does not work for me. Have I overlooked something?

### Include provider and version information

EF Core version: 8.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 8.0)
Operating system: Windows 11 x64
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
@AndriySvyryd Do you remember the status of what gets put in the `Entries` property of a `DbUpdateConcurrencyException` on failure? I couldn't find any issues tracking improvements on this, but I thought we had some...

**Comment by AndriySvyryd** [comment]
https://github.com/dotnet/efcore/issues/1002

**Comment by ajcvickers** [comment]
@ps-nk I don't expect anything to change here anytime soon. Yes, this should be documented--there are various docs issues tracking this.
