### ISSUE TITLE
is aspvnext feed still the one to use?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3448]
A number of new feeds are available on myget, and currently nothing has happened for a week on http://myget.org/gallery/aspnetvnext . Is this feed still the best one to use as a provider writer, that tries to keep up with the avalance of commits?

**Comment by rowanmiller** [comment]
@ErikEJ best to use https://www.myget.org/F/aspnetcidev (that is what we use for the packages our code base depends on).

**Comment by ErikEJ** [comment]
Aah! Thanks, for some reason I thought aspvnext was "official"

**Comment by Eilon** [comment]
`aspnetcidev` has *untested* builds. Everything is merely *compiled* and then pushed there.

`aspnetvnext` on the other hand is fully tested and signed.

So, `aspnetcidev` is certainly riskier, but if you need the latest builds, that's the one to use. There can  sometimes be a 24-48 hour delay to `aspnetvnext` if there are build infrastructure issues, or perhaps a large rename going on that broke something.

**Comment by ErikEJ** [comment]
Thanks @Eilon , I think I will stick to the aspvnext feed then, and just be patient!

**Comment by rowanmiller** [comment]
@ErikEJ our team works against aspnetcidev without very many issues, so I think you should be fine to use it. We run all our tests before we push, so it's only when we miss something (or are working on cross-repository changes) that things break.

**Comment by ErikEJ** [comment]
Got it, Rowan! Will give it a try.
