### ISSUE TITLE
"Unable to cast object of type 'System.String' to type 'System.Int32'"

### ISSUE THREAD

**Issue by FrankMartinezLSA** [dotnet/efcore#34521]
## Why is EF raising this exception when the primary key of the database table is a string and not an Int32?

I have an SQL table where the PK is a `varchar`. When I attempt to update a record via `dbContext.Entry(currentRecord).CurrentValues.SetValues(newRecord)`, I get an exception about trying to convert a string to an int. Walking thru the debugger, I see EF is trying to convert the PK string to an int32 blindly.

Curiously, updating another table with the same value as the PK raises no exception

I have checked the documentation for an explanation and found nothing useful.

I have searched the open and closed issues and found nothing useful.

I was able to step thru the EF code in my debugger and found the following command is attempting to be performed:
```Sql
SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
UPDATE [TableName] SET [Column1] = @p0, [Column2] = @p1, [Column3] = @p2, [Column4] = @p3, [Column5] = @p4
WHERE [PkColumn] = @p5;
SELECT @@ROWCOUNT;
```
Here is a code sample:
```C#
	    RecordType newRecord= new()
	    {
		Column1 = value1,
		Column2 = value2,
		Column3 = value3,
		Column4 = value4,
		Column5 = value5,
		PkColumn = PkValue,
	    };
	    dbContext.Entry(currentRecord).CurrentValues.SetValues(newRecord);
	    dbContext.SaveChanges();
```

### Stack Trace
```
Unable to cast object of type 'System.String' to type 'System.Int32'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int32() in Microsoft.Data.SqlClient\SqlBuffer.cs:line 338
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i) in Microsoft.Data.SqlClient\SqlDataReader.cs:line 1908
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader) in Microsoft.EntityFrameworkCore.Update\AffectedCountModificationCommandBatch.cs:line 248
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader) in Microsoft.EntityFrameworkCore.U
```

### Include provider and version information

EF Core version: v8.0.8
Database provider: This question is unclear and can be reasonably interpreted multiple ways.
Target framework: .NET 8.0
Operating system: Windows 11 Pro, Version 23H2, OS Build 22631.4037
IDE: Microsoft Visual Studio Enterprise 2022, Version 17.10.1

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by FrankMartinezLSA** [comment]
Wouldn't I also have to send my database in order for that project/listing to be meaningful?

**Comment by roji** [comment]
No; when reporting an issue, you need to be able to produce a minimal code sample - a console program - which replicates the problem in an isolated fashion. Usually, in the process of doing this, users find an error in their application code which is responsible for the problem; if not, they end up with a minimal console program that can be posted for us to investigate.

**Comment by FrankMartinezLSA** [comment]
We found the issue in the database.
