### ISSUE TITLE
Beta8 and migrations previously completed in Beta7

### ISSUE THREAD

**Issue by rhires** [dotnet/efcore#3453]
I have a project that I got started using Beta7, and using migrations, everything worked the way it was supposed to. I just upgraded to Beta8, and now my previously successful migrations are giving errors like the one below, which is preventing me from doing any more migrations. Similarly, VSCode tells me roughly the same thing as the error below. 

```
Migrations/20151011031107_FirstMigration.cs(17,60): DNX,Version=v4.5.1 error CS1739: The best overload for 'Column' does not have a parameter named 'isNullable'
```

Actually, here is the offending code from FirstMigration.cs:

```
PersonId = table.Column<int>(isNullable: false)
```

So what I wonder now is, am I missing some functionality in the using statements that Beta8 will put in that Beta7 didn't? 

---

Well, after creating a new project using Beta8, I see that the migration uses "nullable" instead of "isNullable". I'm sure that's in breaking changes somewhere, but I guess after going through this process to figure it out I'll share it with the world here, in case someone else needs to find it. To sum up: the migrations created in Beta7 need to have "isNullable" changed to "nullable" for the project to compile/work with Beta8.

**Comment by rowanmiller** [comment]
There are probably also other similar changes apart from this one. For pre-releases we don't guarantee that migrations from a previous pre-release will still work with a later pre-release. Our general guidance is to delete all migrations and start again.

Obviously this is not the case for stable releases where we put a lot of effort into ensuring things work between releases.
