### ISSUE TITLE
Improvements to domain model for schema

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3455]
Current implementation of our domain model for schema is very narrow, specially compared to the design found in http://entityframework.codeplex.com/wikipage?title=Schema%20Information.
Enabling features such as sequences, views, and stored procedures will require improvements to the model. 

Furthermore, we did not check how well the domain model suits other third-party providers. We may need to provide different abstractions to enable them to use our framework.

**Comment by rowanmiller** [comment]
We can deal with expanding it as required due to features and requests from our other providers.

BTW are we currently not handling sequences in reverse engineer? If so, can you open a new issue to track that as we should be scaffolding code for them.

**Comment by natemcmaster** [comment]
@rowanmiller I don't believe we have an issue to scaffold sequences, and I'm also not sure how we would actually do this, but here is the issue. https://github.com/aspnet/EntityFramework/issues/3510
