### ISSUE TITLE
UserOracle时以前3.1时 支持指定11g版本 现在怎么只有19c 及以上了 我该怎么升级 去解决

### ISSUE THREAD

**Issue by wangxb01** [dotnet/efcore#34573]
optionsBuilder.UseOracle(DBConnection.ConnectionString, i => i.UseOracleSQLCompatibility("11"))

public enum OracleSQLCompatibility
{
    DatabaseVersion19 = 1,
    DatabaseVersion21,
    DatabaseVersion23
}

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by wangxb01** [comment]
你好,就是第一行是我用3.1时的用法 当我升级到8.0时 他可接受类型已被换为了OracleSQLCompatibility 这个枚举 且内部判断只有19c 21 23了
    public virtual OracleDbContextOptionsBuilder UseOracleSQLCompatibility(OracleSQLCompatibility oracleSQLCompatibility)
    {
        if (oracleSQLCompatibility != OracleSQLCompatibility.DatabaseVersion19 && oracleSQLCompatibility != OracleSQLCompatibility.DatabaseVersion21 && oracleSQLCompatibility != OracleSQLCompatibility.DatabaseVersion23)
        {
            throw new ArgumentException();
        }

        return WithOption((OracleOptionsExtension e) => e.WithOracleSQLCompatibility(oracleSQLCompatibility));
    }
![image](https://github.com/user-attachments/assets/73b49e34-77f7-4f4a-9d5c-3bc4f1453220)
可以明白我的问题吗 旧版本还能兼容不 救救孩子把  谢谢

**Comment by roji** [comment]
@wangxb01 your question seems to be about a detail specific to the Oracle provider, which isn't maintained here - you'll have to open a support ticket with Oracle themselves.

**Comment by wangxb01** [comment]
好吧  thanks
