### ISSUE TITLE
Complex type with sparse columns leads to incorrect migration code.

### ISSUE THREAD

**Issue by Poltuu** [dotnet/efcore#34578]
EF.Core Migrations generates incorrect code when using `IsSparse()` on a column of a complex type.

The following configuration

```C#
builder.ComplexProperty(e => e.Address, p =>
{
   p.Property(n => n.PostalCode).HasMaxLength(10).IsSparse();
});
```

leads to the following code generation
```c#
    b.ComplexProperty<Dictionary<string, object>>("Address", "Employees.Models.PersonalRecord.Address#Address", b1 =>
        {

            b1.Property<string>("PostalCode")
                .HasMaxLength(10)
                .HasColumnType("nvarchar(10)");

            SqlServerPropertyBuilderExtensions.IsSparse(b1.Property<string>("PostalCode")); //<- error here
        });
```
Which fails with the following error during compilation
` cannot convert from 'Microsoft.EntityFrameworkCore.Metadata.Builders.ComplexTypePropertyBuilder<string>' to 'Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder'`

### Include provider and version information

EF Core version: EF 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system:  Visual Studio 2022

**Comment by AndriySvyryd** [comment]
The workaround is to manually replace `SqlServerPropertyBuilderExtensions.IsSparse` with `SqlServerComplexTypePropertyBuilderExtensions.IsSparse`

**Comment by cincuranet** [comment]
Miss clicked. :)
