### ISSUE TITLE
SQL Query Translation for !string.IsNullOrEmpty(MAPPED_DB_FIELD) Condition

### ISSUE THREAD

**Issue by ankitce** [dotnet/efcore#34585]
Below EFCore code snippet generates SQL query which doesn't work as desired in Oracle DB
```("a"."AC_ERR" IS NOT NULL) AND (LTRIM(RTRIM("a"."AC_ERR")) <> N'')```
```C#
var data = await dbContext
.Accounts
.Where(a => !string.IsNullOrWhiteSpace(a.AccountError))
.Select(s => new { s.Id })
.AsNoTracking()
.FirstOrDefaultAsync();
```

Could this either be translated to 
```("a"."AC_ERR" IS NOT NULL)```
or, could it produce error on use of IsNullOrWhiteSpace 

EF Core version: 6.0.20
Database provider: Oracle.EntityFrameworkCore
Target framework: .NET 6.0
Operating system: Windows 2019
IDE: Visual Studio 2022 17.11.1

**Comment by cincuranet** [comment]
The translation should be fixed in provider for Oracle. This is not something we control.
