### ISSUE TITLE
Is there any possible to add a api when select page data by condition then return value and the total count?

### ISSUE THREAD

**Issue by Austin-Patrician** [dotnet/efcore#34592]
_context.Set<T>().Where(expression).AsNoTracking();
T is wrapped data, is including the data <T> and toalcount num.  

add the overload implemented for where function ,accept two param , then we can use different optimizer

**Comment by cincuranet** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Austin-Patrician** [comment]
When we use the IQuerable search the database data, then want to make the return value <T> including two part, 1. count , 2. <V> values.

**Comment by cincuranet** [comment]
Such API does not exist at the moment. You may want to follow #33160 and possibly engage in discussion.
