### ISSUE TITLE
Cannot resolve symbol 'ToListAsync'

### ISSUE THREAD

**Issue by MiguelPayran** [dotnet/efcore#34599]
My References
`using workqueues.Domain;
using workqueues.Domain.Entities;
using workqueues.Infrastructure.Interfaces;
using Microsoft.EntityFrameworkCore;`

I notice removing this part: "(Func<WorkQueue, bool> func)" I can get the method ToListAsync. I'm not sure if is a bug or normal behavior.

` public async Task<List<WorkQueue>> GetWorkQueue(Func<WorkQueue, bool> func)
    {
        var workQueue =  _context.WorkQueues.Where(func).ToList();
        return workQueue;
    }`

I got the error
```
Cannot resolve symbol 'ToListAsync'
```

EF Core version: 8.0.8
Database provider: EntityFrameworkNpgsql
Target framework: .NET 8.0
Operating system: macOS Sonoma
IDE: Rider

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MiguelPayran** [comment]
I'm trying to pass a lambda expression in my repository.
`public async Task<List<WorkQueue>> GetWorkQueue( Func<WorkQueue, bool> func)
    {
        var workQueue =  _context.WorkQueues.Where(func).ToList();
        return workQueue;
    }`

Here when I call the function:
`var workWorkqueue = await workQueueRepository.GetWorkQueue(x => x.Id == workQueueId);`

I'm expecting to use `ToListAsync()` but  I get: Cannot resolve symbol 'ToListAsync'

so the unique way to call ToListAsync() is changing the code by:

` public async Task<List<WorkQueue>> GetWorkQueue(int id )
    {
        var workQueue =  await _context.WorkQueues.Where(x=>x.Id == id).ToListAsync();
        return workQueue;
    }`

It looks like when you pass a lambda expression as an argument in the `Where([expression here])`, `ToListAsync()` is not available.

**Comment by roji** [comment]
Your GetWorkQueue() does `ToList()` inside, which means it has already executed the query (synchronously). So it returns a `Task<List<WorkQueue>>`, and you can't do ToListAsync() on that. Doing ToListAsync() inside the function is the right way to do it - this is unrelated to the lambda.

**Comment by MiguelPayran** [comment]
Reading more about it, I found that if I want to use ToListAsync I have to change the code in this way:
` public async Task<List<WorkQueue>> GetWorkQueue(Expression<Func<WorkQueue, bool>> func)
    {
        var workQueue = await _context.WorkQueues.Where(func).ToListAsync();
        return workQueue;
    }`

By changing the parameter type to Expression<Func<WorkQueue, bool>>, the query remains as IQueryable, allowing EF Core to translate it into SQL and execute it on the database server asynchronously.
