### ISSUE TITLE
 Is it possible to connect a new .netcore project to a database that already has an EF implementation?

### ISSUE THREAD

**Issue by sgtWalker** [dotnet/efcore#34602]
Hi guys, how are you?
We have an API project in .Net Framework 4.8 with implementation of EntityFramework 6.4.4 in a SQL Server database.

We are rewriting this project with .Netcore 8 and I would like to know if it is possible to use the same database from the old API project (.NetFramework 4.8) in this new project in .NetCore 8.

The idea is to use EntityFrameworkCore in the new project but connecting to the database used by the previous project. Is this possible?

**Comment by ErikEJ** [comment]
Easy if you use Database First, yes.

**Comment by roji** [comment]
First, note that you can use the old, non-core Entity Framework 6 from a .NET 8.0 project. You can do this as a first migration step, i.e. first switch from .NET Framework to modern .NET, then do a transition from old EF6 to EF Core as a second step.

Beyond that, we have a [porting guide from EF6 to EF Core](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/); it's not as comprehensive as it could be but it should set you on the right path.

**Comment by sgtWalker** [comment]
> Easy if you use Database First, yes.
Thanks for answering my question. We use CodeFirst.

**Comment by sgtWalker** [comment]
> First, note that you can use the old, non-core Entity Framework 6 from a .NET 8.0 project. You can do this as a first migration step, i.e. first switch from .NET Framework to modern .NET, then do a transition from old EF6 to EF Core as a second step.
> 
> Beyond that, we have a [porting guide from EF6 to EF Core](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/); it's not as comprehensive as it could be but it should set you on the right path.

Thanks for answering my question.
We will try these indicated steps. When finished, I'll come here to give a report.

**Comment by sgtWalker** [comment]
> First, note that you can use the old, non-core Entity Framework 6 from a .NET 8.0 project. You can do this as a first migration step, i.e. first switch from .NET Framework to modern .NET, then do a transition from old EF6 to EF Core as a second step.
> 
> Beyond that, we have a [porting guide from EF6 to EF Core](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/); it's not as comprehensive as it could be but it should set you on the right path.

@roji, I managed to migrate to EF Core and use the old database that had migrations in EF 6.

Once again, thank you very much!
