### ISSUE TITLE
Feature request: ability to configure a default `CancellationToken` for `async` EF Core operations

### ISSUE THREAD

**Issue by tuespetre** [dotnet/efcore#34612]
When developing a web application that uses EF Core, it would be nice to be able to use `HttpContext.RequestAborted` as the `cancellationToken` parameter for `async` EF Core methods without having to explicitly pass it everywhere. One might also want something similar in a console application (using a `CancellationTokenSource` with `Console.CancelKeyPress`), or in an `IHostedService`. 

My first guess is that this feature could be implemented using some kind of `IDefaultCancellationTokenProvider` service, but a decision would have to be made for how "no cancellation token" is handled:
1. Use the `IDefaultCancellationTokenProvider` service when `CancellationToken.None` is received. If consumers wish to pass in a token that will not be cancelled, they must create a `CancellationTokenSource` pass in its `Token` instead of `CancellationToken.None` 
2. Change public APIs to take `CancellationToken?` instead of `CancellationToken` so a consumer could just pass in `CancellationToken.None` to override the `IDefaultCancellationTokenProvider`

Just spitballing, curious to see what your team thinks.

**Comment by roji** [comment]
HttpContext.RequestAborted is also just a cancellation token - you still must explicitly pass it to any .NET async methods that you want to invoke; in other words, it isn't some "implicit" cancellation token that's automatically picked up by .NET APIs, which is what you seem to be asking for. If you're asking for EF to do this, then why not .NET APIs such as FileStream, HttpClient, or basically any and every async method out there? How is EF special here?

**Comment by tuespetre** [comment]
There's the sanity I needed 😅
