### ISSUE TITLE
Shadow key property unknown when updating JSON document with a list and NoTracking behavior enabled

### ISSUE THREAD

**Issue by Sticcia** [dotnet/efcore#34616]
### Issue
We enabled the `NoTracking` query behavior on a Entity Framework DB Context.
Our setup heavily relies on entity tracking being disabled:
```Csharp
optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
```

We then add successfully  a new row containing a column with a JSON document with a list of a complex type:
```Csharp
public class Customer
{
	public required Guid Id { get; init; }

	public required List<Address> Addresses { get; set; }
}

public class Address
{
	public required string Street { get; set; }
}
```
Using the `ToJson` model builder:
```Csharp
modelBuilder.Entity<Customer>().OwnsMany(
	order => order.Addresses, ownedNavigationBuilder =>
	{
		ownedNavigationBuilder.ToJson();
	});
```

We then query the previously added document, and, after updating it, we are unable to save the changes in the database because of an unknown shadow key property in the list of complex objects.

We have tried to set the state of the object and of the elements in the list to `Modified` but found no difference:
```Csharp
context.Entry(customer).State = EntityState.Modified;
```

### Code
I created a simple project to replicate the issue:
https://github.com/Sticcia/EFCore8Test

###  Stack Trace
```
The value of shadow key property 'Address.Id' is unknown when attempting to save changes.
This is because shadow property values cannot be preserved when the entity is not being tracked.
Consider adding the property to the entity's .NET type.
See https://aka.ms/efcore-docs-owned-collections for more information.
```

### Provider and version information
EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.0

**Comment by AndriySvyryd** [comment]
You'd need to do something like this:
```C#
    context.Entry(customer).State = EntityState.Detached;

    var i = 1;
    foreach (var address in customer.Addresses)
    {
        context.Entry(customer).Collection(c => c.Addresses).FindEntry(address)!.Property("Id").CurrentValue = i++;
    }

    context.Entry(customer).State = EntityState.Modified;
```

The actual value for this property will not be sent to the database, it just needs to be unique within the collection.

This is one of the biggest pain points that https://github.com/dotnet/efcore/issues/31252 should remove.

**Comment by weitzhandler** [comment]
To me the culprit was mismanagement of a transaction.
