### ISSUE TITLE
Scaffold-DbContext: Missing [Name] property for data annotation [Key] and [FillFactor] property is mising for [Index]

### ISSUE THREAD

**Issue by MSulsters** [dotnet/efcore#34611]
Scaffold-DbContext: Missing [Name] property for data annotation [Key] and [FillFactor] property is mising for [Index] so with the Fluent API these are added like this:

```C#
entity.HasKey(e => e.Id).HasName("pk_id");
entity.HasIndex(e => e.SomeId, "ix_someid").HasFillFactor(100);
```

It would be nice if both definition where defined in the data annotaions itself (and removed from the Fluent API). 

EF Core version: 8.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 8.0
Operating system: Windows 2011
IDE: Visual Studio 2022 17.9.6

**Comment by cincuranet** [comment]
`KeyAttribute` lives in `System.ComponentModel.DataAnnotations`, thus we can't directly change it. `Name` for PK is also mostly relations DBs specific, while `KeyAttribute` is general concept for anything having "key". Can you maybe share your motivation?

`IndexAttribute` is database agnostic while `FillFactor` is something SQL Server provider specific. These specifics are exactly why we have extension methods on various builders, while attributes are kind of lowest common denominator and are aiming cover most common cases, not all possibilities.
