### ISSUE TITLE
Not able to Add non-nullable custom property in the ApplicationUserToken.

### ISSUE THREAD

**Issue by PANKAJBAJAJ045** [dotnet/efcore#34628]
## I am extending ApplicationUserToken  for that I added these properties
    
 public long Id { get; set; }
 public DateTime Expiration { get; set; }
 public bool IsRevoked { get; set; }   

 **But these properties are generated as Nullable due to this I am not able to set Id as Identity column.**

I added Required Attribute but the result are same.

```C#
   public class ApplicationUserToken : IdentityUserToken<long>
   {
       public long Id { get; set; }
       public DateTime Expiration { get; set; }
       public bool IsRevoked { get; set; }     
   }
**Migration code for the reference**

 migrationBuilder.CreateTable(
     name: "AspNetUserTokens",
     columns: table => new
     {
         UserId = table.Column<long>(type: "bigint", nullable: false),
         LoginProvider = table.Column<string>(type: "nvarchar(450)", nullable: false),
         Name = table.Column<string>(type: "nvarchar(450)", nullable: false),
         Value = table.Column<string>(type: "nvarchar(max)", nullable: true),
         Discriminator = table.Column<string>(type: "nvarchar(34)", maxLength: 34, nullable: false),
         Id = table.Column<long>(type: "bigint", nullable: true),
         Expiration = table.Column<DateTime>(type: "datetime2", nullable: true),
         IsRevoked = table.Column<bool>(type: "bit", nullable: true, defaultValue: false)
     },
     constraints: table =>
     {
         table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
         table.ForeignKey(
             name: "FK_AspNetUserTokens_AspNetUsers_UserId",
             column: x => x.UserId,
             principalTable: "AspNetUsers",
             principalColumn: "Id",
             onDelete: ReferentialAction.Cascade);
     });

Configuration file for the reference

public class ApplicationUserTokenEntityTypeConfiguration : IEntityTypeConfiguration<ApplicationUserToken>
{
    public void Configure(EntityTypeBuilder<ApplicationUserToken> entity)
    {
        entity.Property(x => x.IsRevoked)
              .HasDefaultValue(false);

        entity.Property(x => x.Id)                
              .IsRequired(); 
    }
}

package details
 <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
```

EF Core version: 8.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 8.0
Operating system: Window 10
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by AndriySvyryd** [comment]
You are adding a derived entity type and this uses [TPH mapping](https://learn.microsoft.com/ef/core/modeling/inheritance#entity-type-hierarchy-mapping) by default, so all derived properties are mapped to nullable columns. You also can't use a property on the derived type as a key.

**Comment by PANKAJBAJAJ045** [comment]
@AndriySvyryd
This is wired behavior, I extend the ApplicationUser and for this class whatever confiq I provided, according to that properties is generated.

public class ApplicationUser : IdentityUser<long>, IBaseAuditableEntity, IBaseEntity
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int? CardId { get; set; }
    public bool IsActive { get; set; }
    public string? ProfilePicturePath { get; set; }
    public long? TimeZoneId { get; set; }
    public TimeZone? TimeZone { get; set; }
    public DateTime EffectiveFrom { get; set; } = DateTime.UtcNow;
    public DateTime EffectiveTill { get; set; } = new DateTime(3999, 12, 31);  // Default value
    public List<UserModulePermission> UserModulePermissions { get; set; }
    public long CreatedByUserId { get; set; }
    public DateTime CreatedOnUtc { get; set; }     
    public long UpdatedByUserId { get; set; }
    public DateTime UpdatedOnUtc { get; set; }       
    public byte[] Version { get; set; }
}
![image](https://github.com/user-attachments/assets/6ffa6bd0-6737-4090-b6d0-c687d647e757)

We mostly extend the Identity Framework as per our need. I think EF core team need to look into this.

**Comment by AndriySvyryd** [comment]
Make sure that you are using your type as the generic argument:
`IdentityUserContext<ApplicationUser, long, ApplicationUserClaim, ApplicationUserLogin, ApplicationUserToken>`
