### ISSUE TITLE
Is it possible to add records in the join table with only the IDs?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#34629]
Hello:

I am using entity core 8 and I would like to know if it is possible to add records in the join table without the need to create the instances of the related entity.

As example, I have these two classes, Movie and Genre:

```
public sealed class Movie
{
    //Necesario para Entity Core.
    public Movie() { }



    public long Id { get; private set; }
    [Required]
    [StringLength(300)]
    public string Title { get; private set; }

    //another properies


    private List<long> _genresId = [];
    /// <summary>
    /// Los actores que trabajan en la película.
    /// </summary>
    public IReadOnlyCollection<long> GenresId => _genresId;




    public void SetTitle(string paramTitle)
    {
        Title = paramTitle;
    }

    public void AddGenre(long paramGenre)
    {
        _generosIds.Add(paramGenre);
    }

    public void AddGenres(IEnumerable<long> paramGenres)
    {
        _genresId.AddRange(paramGenres);
    }
}


public sealed class Genre
{
    public long Id { get; private set; }
    public long Name { get; private set; }
}
```

I wouldn't like to use a navigation property in Genre with the Movie, because i will set the relation when I will create the movie.

Also, I wouldn't like to use an entity for the join table.

To try to configure the relation in Fluent API, I am using this code:

```
paramConfiguracionMovie
        .HasMany<Genre>()
        .WithMany()
        .UsingEntity<Dictionary<string, object>>(
            "GenresOfMovies",
            j => j
                .HasOne<Genero>()
                .WithMany()
                .HasForeignKey("GenreId")
                .OnDelete(DeleteBehavior.Cascade),
            j => j
                .HasOne<Pelicula>()
                .WithMany()
                .HasForeignKey("MovieId")
                .OnDelete(DeleteBehavior.Cascade),
            j =>
            {
                j.HasKey("MovieId", "GenreId");
            });
```

But this doesn't create the records in the join table.

In another similar cases, in which in the collection I have the type instead of the ID, i can configure in Fluent API the relationship in this way:

```
movieConfiguracion
    .HasMany(x => x.Generes)
    .WithMany()
    .UsingEntity(
        "GenresOfMovies",
        //NOTA: los nombres de campos son case sensitive, por lo que no es lo mismo IDFactura que IdFactura. Lo correcto es
        //IDFactura que es nombre de la columna en la base de datos.
        l => l.HasOne(typeof(Genre)).WithMany().HasForeignKey("IDGenre").HasPrincipalKey(nameof(Genre.Id)),
        r => r.HasOne(typeof(Movie)).WithMany().HasForeignKey("IDMovie").HasPrincipalKey(nameof(Movie.Id)),
        j => j.HasKey("IDGenre", "IDMovie"));
```

But I would like to know if it is possible to avoid the needed to have a collection of genres in the movie, only to have a list of long (the Id of the genres), because in my Web API I get from the client a list of IDs, so if I could avoid to create the instance of the genre, the code could be a bit less complex.

So in sumary, I would like to know if it is possible to create the records in the join table with only a list of IDs or I would need to have a list of Genre.

Thanks.

**Comment by AndriySvyryd** [comment]
You should be able to do something like this to add a join entity without navigations:
```C#
context.Set<Dictionary<string, object>>("GenresOfMovies")
    .Add(new Dictionary<string, object>
    {
        ["GenreId"] = genreId,
        ["MovieId"] = movieId
    });
```

Why don't you want to have a collection navigation on `Movie`?
