### ISSUE TITLE
Compiled models generation doesn't create UnsafeAccessors

### ISSUE THREAD

**Issue by muzopraha** [dotnet/efcore#34652]
Compiled models don't generate UnsafeAccessors after running `dotnet ef dbcontext optimize -o Models -n Server.Persistence.Models`, yet they are expected in EntityTypes. When I add `--nativeaot` flag in the command, then the accessors are generated.

### Include provider and version information

EF Core version: 9.0.0-rc.1.24451.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: JetBrains Rider 2024.2

**Comment by ilmax** [comment]
to me something similar related is happening, `dotnet ef dbcontext optimize` generates code that uses unsafeaccessor but doesn't generate them, hence it generates code that doesn't compile.

Example model:

```chsarp
public class Blog
{
    public int BlogId { get; set; }
    public required string Url { get; init; }
    public required string Title { get; init; }
    public List<Post> Posts { get; init; } = new();
}

public class Post
{
    public int PostId { get; set; }
    public required string Title { get; init; }
    public required string Content { get; init; }
    public int BlogId { get; set; }
    public DateTimeOffset PublishedOn { get; set; }
}
```

EF Core version: 9.0.0-rc.1.24451.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 9.0

**Comment by AndriySvyryd** [comment]
This was fixed in https://github.com/dotnet/efcore/commit/2a6e5ae07e71cb5d52414277de4ee7a78d92dbf0 and will ship in RC2, for now please add `--nativeaot`
