### ISSUE TITLE
dotnet ef commands are not finding .NET in nixOS

### ISSUE THREAD

**Issue by danielb-boop** [dotnet/efcore#34653]
So I am trying to use entity framework to create the schema and use as my ORM for a .NET application. 

I installed the .NET sdk for .NET 8.0 using the config file. The unique thing about nixOS is that packages are installed either in the config file or through a dev shell. I chose to install this globally in my config file like so:

```
  environment.systemPackages = with pkgs; [
     ...
     dotnet-sdk_8 
  ];
```
This results in these responses to dotnet commands
```
> dotnet --version
8.0.303
> dotnet --list-sdks
8.0.303 [/nix/store/mh30q73z8bwp1qdrng7mx3zzxna0ll6b-dotnet-sdk-8.0.303/sdk]
> dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.7 [/nix/store/mh30q73z8bwp1qdrng7mx3zzxna0ll6b-dotnet-sdk-8.0.303/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.7 [/nix/store/mh30q73z8bwp1qdrng7mx3zzxna0ll6b-dotnet-sdk-8.0.303/shared/Microsoft.NETCore.App]
```
So it seems to be successfully installed

When I was installing entity framework as a dotnet tool, I did 

`dotnet tool install --global dotnet-ef` 

I initially ran into the issue that `${HOME}/.dotnet/tools` was not on my path but that was easy enough to fix using home-manager. 

When I was running `dotnet ef migrations add InitialCreate` I run into this issue. (This is with some additional information given by `COREHOST_TRACE = 1`)

```
--- Begin breadcrumb write
Directory core breadcrumbs [] was not specified or found
Fallback directory core breadcrumbs at [opt/corebreadcrumbs] was not found
Breadcrumb store was not obtained... skipping write.
Tracing enabled @ Mon Sep  9 23:11:50 2024 GMT
--- Invoked apphost [version: 8.0.7 @Commit: 2aade6beb02ea367fd97c4070a4198802fe61c03] main = {
/home/danielb/.dotnet/tools/dotnet-ef
migrations
add
InitialCreate
}
The managed DLL bound to this executable is: '.store/dotnet-ef/8.0.8/dotnet-ef/8.0.8/tools/net8.0/any/dotnet-ef.dll'
Using environment variable DOTNET_ROOT=[/nix/store/mh30q73z8bwp1qdrng7mx3zzxna0ll6b-dotnet-sdk-8.0.303/dotnet] as runtime location.
Looking for architecture-specific install_location file in '/etc/dotnet/install_location_x64'.
The install_location file ['/etc/dotnet/install_location_x64'] does not exist - skipping.
Looking for install_location file in '/etc/dotnet/install_location'.
The install_location file ['/etc/dotnet/install_location'] does not exist - skipping.
The required library libhostfxr.so could not be found. Searched with root path [/home/danielb/.dotnet/tools/.store/dotnet-ef/8.0.8/dotnet-ef/8.0.8/tools/net8.0/any/], environment variable [DOTNET_ROOT], default install location [/usr/share/dotnet], self-registered config location [/etc/dotnet/install_location_x64]
You must install .NET to run this application.
```

I ran

```
> whereis dotnet
dotnet: /nix/store/nrxjmby0zc5q0irm7075yq0ifygjjjx8-system-path/bin/dotnet
```

I define `DOTNET_ROOT` as ` /run/current-system/sw/bin/dotnet` for context. This is the answer I get when I run `which dotnet`

I hesitate to try and manually make a file at `/etc/dotnet/install_location` as I have gotten to the point where I don't know exactly what I am doing there. I also don't have the strongest grasp on nixOS (I am beginner to intermediate) so I am fairly certain that the install location could be dynamic to an extent. (It will always be in /nix/store/ at the very least as far as my understanding. 

Any help is appreciated.

**Comment by AndriySvyryd** [comment]
This doesn't seem to be specific to EF and would be better answered by the SDK team
