### ISSUE TITLE
Fix for #3103 breaks SQL CE provider

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3467]
The fix https://github.com/aspnet/EntityFramework/commit/c2b01796fbea1aba41c2f7e46f4a55b8b0a44550  causes SQL like the following to be generated, adn this way of nesting SELECTs is not supported by SQL CE:

``` SQL
SELECT [g].[FullName], [t].[Note]
FROM [Gear] AS [g]
INNER JOIN [CogTag] AS [t] ON [g].[FullName] = (
    SELECT TOP(1) [subQuery0].[FullName]
    FROM [Gear] AS [subQuery0]
    WHERE ([subQuery0].[Nickname] = [t].[GearNickName]) AND ([subQuery0].[SquadId] = [t].[GearSquadId])
)
```

This is similar to the pattern/issues reported in #3038 and #2626

**Comment by rowanmiller** [comment]
We'll handle this the same as the other ones... post RC we can help with guidance about how to override this for CE

**Comment by ErikEJ** [comment]
Thanks, Rowan
