### ISSUE TITLE
ExecuteUpdate/Delete attempt to update the view, not the table

### ISSUE THREAD

**Issue by ddashwood** [dotnet/efcore#34677]
## File a bug

According to [the documentation](https://learn.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#view-mapping):

> Mapping to a view will remove the default table mapping, but the entity type can also be mapped to a table explicitly. In this case the query mapping will be used for queries and **the table mapping will be used for updates.**

However, ExecuteUpdate does not respect this - it updates the view, not the table.

### Include your code

Instructions:

- Add Microsoft.EntityFrameworkCore.Sqlite Nuget package
- Add Microsoft.EntityFrameworkCore.Tools Nuget package
- Paste the code below into Program.cs in a console application
- Run `add-migration InitialCreate` followed by `update-database`
- Run the application

```C#
using Microsoft.EntityFrameworkCore;


using var db = new BloggingContext();

db.Database.ExecuteSql($"CREATE VIEW IF NOT EXISTS BlogsView AS SELECT * FROM Blogs");

var blog = new Blog { Url = "http://blogs.msdn.com/adonet" };
db.Add(blog);
db.SaveChanges();

blog.Url = "http://blogs.msdn.com/adonet2";
db.SaveChanges(); // Updates the Blogs table

// The following attempts to update the BlogsView view, not the Blogs table as expected.
// In SqLite, this throws an exception because views can not be updated.
// In Sql Server, it might succeed depending on the definition of the view
db.Blogs.ExecuteUpdate(properties => properties.SetProperty(b => b.Url, "http://blogs.msdn.com/adonet3"));


public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    public string DbPath { get; }

    public BloggingContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DbPath = System.IO.Path.Join(path, "blogging.db");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source={DbPath}");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .ToTable("Blogs")
            .ToView("BlogsView");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; } = "";
}

```

### Include stack traces

When running this against SqLite, the following exception is generated:

```
Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 1: 'cannot modify BlogsView because it is a view'.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.<>c.<NonQueryResult>b__13_0(DbContext _, ValueTuple`3 state)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.NonQueryResult(RelationalQueryContext relationalQueryContext, RelationalCommandCache relationalCommandCache, Type contextType, CommandSource commandSource, Boolean threadSafetyChecksEnabled)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at Program.<Main>$(String[] args) in C:\.......\Program.cs:line 18
```

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqLite
Target framework: .Net 8
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.3

**Comment by ErikEJ** [comment]
So you are mapping the same entity to both a table AND a view ???

**Comment by ddashwood** [comment]
> So you are mapping the same entity to both a table AND a view ???

Yes - according to the documentation, this should use the view for reading, and the table for updating. It's useful when you soft-delete data, and you have a view such as `CREATE VIEW ActiveObjects AS SELECT * FROM Objects WHERE Deleted = 0` - I want to always read from the view so that I don't read deleted data, but updating the view can cause issues (update the Deleted flag from 0 to 1 is particularly interesting...)

**Comment by ddashwood** [comment]
Although the current behaviour is not as described in the documentation, it would be interesting to discuss what the expected behaviour really ought to be.

If a row is excluded in the view, and ExecuteUpdate updated the table without reference to the view, would ExecuteUpdate be updating more rows than expected? Perhaps it is better to update the view in this case... but this won't work with some providers (e.g. SqLite)? Perhaps there should be a join between the table and the view, so that the table can be updated but only for rows that appear in the view?

**Comment by ddashwood** [comment]
That’s understand Andriy. Any chance of getting the documentation amended in the mean time?

**Comment by AndriySvyryd** [comment]
Generally, we don't mention known bugs in the documentation unless they affect the majority of our users, and this scenario seems to be uncommon.

**Comment by roji** [comment]
Confirmed, see minimal repro below.

* ExecuteDelete/Update take as input the SelectExpression that was translated so far, just prior to their appearance; that SelectExpression is assumed to be reading the tables, so references views rather than tables.
* Note that the query may reference multiples tables. The additional tables (not the one being mutated) **do** need to be views, as we're reading from them. But during translation, we don't know which table is being updated - the user can start from one root, and project out a navigation to be deleted. So we only know the target table at the end of translation.
* That means that the fix here is likely to add handling when translating ExecuteUpdate/Delete, to detect this case and swap out the view TableExpressionBase with the corresponding table TableExpressionBase.
* For ExecuteDelete, that's likely to be relatively easy - the query just before ExecuteDelete must project out an entity type, so we can just find its (only) table. For ExecuteUpdate things are probably a bit more complicated.

<details>
<summary>Minimal repro</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

// The following attempt to update BlogsView instead of Blogs
await context.Blogs.ExecuteDeleteAsync();
await context.Blogs.ExecuteUpdateAsync(s => s.SetProperty(b => b.Name, "foo"));

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .ToTable("Blogs")
            .ToView("BlogsView");
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>
