### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by satviktechie1986** [dotnet/efcore#34671]
Is there any way in ef core from where i can get details of DBContext timeout's in which i can find the entity is getting messed or entity is not released after some operation , i cant share the code as i have a microservice architecture using ef core  and it is difficult to find route cause of timeout in ef core .

**Comment by roji** [comment]
It's not clear exactly what you're asking; if a timeout occurs during a database operation (e.g. SaveChanges), EF has no way of knowing what caused it - nor any knowledge of any entity getting "messed" or not released.

If you provide more context on the specific trouble you're having - ideally including a code sample - we may be able to help further.

**Comment by satviktechie1986** [comment]
> It's not clear exactly what you're asking; if a timeout occurs during a database operation (e.g. SaveChanges), EF has no way of knowing what caused it - nor any knowledge of any entity getting "messed" or not released.
> 
> If you provide more context on the specific trouble you're having - ideally including a code sample - we may be able to help further.

thanks for your reply, 
let me explain 
Our project architecture is made up with 15+ microservices and each service contains separate dbcontext and separate database attached with each service. So in multiple cases we need to make call internally to different internal services, if any of the service call failed due to db operation we need to know excatly at what point the error occured.

**Comment by roji** [comment]
I'm still not sure what you're expecting here from EF. When a database timeout occurs, EF will raise the appropriate exception, which will contain the appropriate stack trace. You can catch this and log it, and if you include the proper information about where that happened (e.g. in which microservice), you should be able to understand where things happened. I don't know what else EF can do for you around this.

**Comment by satviktechie1986** [comment]
> I'm still not sure what you're expecting here from EF. When a database timeout occurs, EF will raise the appropriate exception, which will contain the appropriate stack trace. You can catch this and log it, and if you include the proper information about where that happened (e.g. in which microservice), you should be able to understand where things happened. I don't know what else EF can do for you around this.

Thanks for your reply i have already logged the error for timeout , 
anyway i will try to add more details of timeout
