### ISSUE TITLE
DbCommandInterceptors receives obsolete Command Source

### ISSUE THREAD

**Issue by ddashwood** [dotnet/efcore#34678]
## File a bug

The [CommandSource enum](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.commandsource?view=efcore-8.0) has a value called `CommandSource.BulkUpdate` which is marked as `Obsolete`, but is supplied to interceptors when an ExecuteUpdate is run. The value `CommandSource.ExecupteUpdate` would be more appropriate

### Include your code

Instructions:

- Add Microsoft.EntityFrameworkCore.Sqlite Nuget package
- Add Microsoft.EntityFrameworkCore.Tools Nuget package
- Paste the code below into Program.cs in a console application
- Run `add-migration InitialCreate` followed by `update-database`
- Run the application
- Note that the output is "Bulk Update", and not "ExecuteUpdate

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System.Data.Common;


using var db = new BloggingContext();

Console.WriteLine("Running ExecuteUpdate");
db.Blogs.ExecuteUpdate(properties => properties.SetProperty(b => b.Url, "http://blogs.msdn.com/adonet2"));


public class Interceptor : DbCommandInterceptor
{
    public override InterceptionResult<int> NonQueryExecuting(DbCommand command, CommandEventData eventData, InterceptionResult<int> result)
    {
#pragma warning disable CS0618 // Type or member is obsolete
        if (eventData.CommandSource == CommandSource.BulkUpdate)
#pragma warning restore CS0618 // Type or member is obsolete
        {
            Console.WriteLine("Bulk Update");
        }
        else if (eventData.CommandSource == CommandSource.ExecuteUpdate)
        {
            Console.WriteLine("Execute Update");
        }
        return base.NonQueryExecuting(command, eventData, result);
    }
}

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    public string DbPath { get; }

    public BloggingContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DbPath = System.IO.Path.Join(path, "blogging.db");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    { 
        options.UseSqlite($"Data Source={DbPath}");
        options.AddInterceptors(new Interceptor());
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; } = "";
}
```

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqLite
Target framework: .Net 8
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.3

**Comment by roji** [comment]
Thanks for raising, makes sense. Note that both are the same value, so this is purely a question of the enum label.

**Comment by roji** [comment]
Looking at this again, I don't think there's a bug here - EF itself doesn't reference CommandSource.BulkUpdate anywhere, only ExecuteUpdate/Delete. As I wrote above, ExecuteUpdate and BulkDelete are the same value, which is why your code above prints "Bulk Update" - if you remove that condition, you'll see the coe working for CommandSource.ExecuteUpdate.

Am going to go ahead and close this, but if I've misunderstood or somehow miss something, please post back and I'll take another look.
