### ISSUE TITLE
Combination of IgnoreQueryFilters with Max throws exception.

### ISSUE THREAD

**Issue by mpapadis** [dotnet/efcore#34682]
I have a dbset and and I need to find max id in table, including soft deleted entries. 
For Max I need to the Max(this IQueryable source, string predicate, params object?[] args)
If I don't use IgnoreQueryFilters I am getting the last not soft-deleted entry, as the true soft-deleted entry is excluded from setting HasQueryFilter(x => !x.IsDeleted) in the OnModelCreating sub of ModelBuilder.
When I use IgnoreQueryFilters then I get an exception.

```C#
var max = dbSet.IgnoreQueryFilters().AsNoTracking().Max(keyName);
```

The exception I am getting is the following
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The LINQ expression 'DbSet<Statement>()
    .Max(s => Invoke(CallSite<Func<CallSite, object, object>>.Target, CallSite<Func<CallSite, object, object>>, s))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute(Expression expression)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Execute(MethodInfo operatorMethodInfo, IQueryable source, Expression expression)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Execute(MethodInfo operatorMethodInfo, IQueryable source, LambdaExpression expression)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Max(IQueryable source, ParsingConfig config, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Max(IQueryable source, String predicate, Object[] args)
```

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework:  .NET 8.0
Operating system: Windows 11 Enterprise 22H2 22621.4169
IDE: Visual Studio 2022 17.11.3

**Comment by roji** [comment]
What's keyName? As always, a single line of code does not provide enough information to reproduce the issue. Please submit a minimal, runnable code sample.

**Comment by satviktechie1986** [comment]
> I have a dbset and and I need to find max id in table, including soft deleted entries. For Max I need to the Max(this IQueryable source, string predicate, params object?[] args) If I don't use IgnoreQueryFilters I am getting the last not soft-deleted entry, as the true soft-deleted entry is excluded from setting HasQueryFilter(x => !x.IsDeleted) in the OnModelCreating sub of ModelBuilder. When I use IgnoreQueryFilters then I get an exception.
> 
> ```cs
> var max = dbSet.IgnoreQueryFilters().AsNoTracking().Max(keyName);
> ```
> 
> The exception I am getting is the following
> 
> ```
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.InvalidOperationException: The LINQ expression 'DbSet<Statement>()
>     .Max(s => Invoke(CallSite<Func<CallSite, object, object>>.Target, CallSite<Func<CallSite, object, object>>, s))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
>    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
>    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute(Expression expression)
>    at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Execute(MethodInfo operatorMethodInfo, IQueryable source, Expression expression)
>    at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Execute(MethodInfo operatorMethodInfo, IQueryable source, LambdaExpression expression)
>    at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Max(IQueryable source, ParsingConfig config, String predicate, Object[] args)
>    at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Max(IQueryable source, String predicate, Object[] args)
> ```
> 
> EF Core version: Database provider: Npgsql.EntityFrameworkCore.PostgreSQL Target framework: .NET 8.0 Operating system: Windows 11 Enterprise 22H2 22621.4169 IDE: Visual Studio 2022 17.11.3

var max = dbSet.IgnoreQueryFilters().AsNoTracking().Max(s => EF.Property<object>(s, keyName));

try this, might works

**Comment by roji** [comment]
Please take the time to submit a verified, minimal console program.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
