### ISSUE TITLE
Question: Access shadow property collection

### ISSUE THREAD

**Issue by louislewis2** [dotnet/efcore#3468]
Hi, 
I am trying to see how one would after loading an entity from the database which
has shadow properties defined access a collection containing the shadow properties
and their values. I know we can access them one by one but is there a way in which
we could get access to the entire collection which we can then for example copy into 
a dictionary for returning to callers?

**Comment by rowanmiller** [comment]
Something like this would give you the shadow values:

```c#
var entry = context.Entry(myEntity);
var currentShadowValues = entry.Metadata.GetProperties().Where(p => p.IsShadowProperty).Select(p => entry.Property(p.Name).CurrentValue);
```

**Comment by louislewis2** [comment]
@rowanmiller Thanks for the answer, I did work it out in the mean time, but it feels even better when seeing that your code matches mine. :)

**Comment by rowanmiller** [comment]
So either "great minds think alike" or "fools never differ" :smile:
