### ISSUE TITLE
Dynamically loaded assemblies

### ISSUE THREAD

**Issue by ApertureDevelopment** [dotnet/efcore#34681]
Hello everyone reading this.

I am currently working on a project where I am trying to build a modular system that is able to load class libraries as modules. Now these modules need to be able to provide their own entities and add on top of already existing ones. The software user should have as little work as possible, meaning they should be able to drop in modules into the modules folder and not need to re-compile the entire project each time.

Let's say we have the following entities

User entity of our startup project
```cs
public class User {
    public int UserId { get; set; }
    public string Username { get; set; }
    public string Email { get; set; }
}
```

User entity extension by our dynamically loaded assembly
```cs
public class AdvancedUser : User {
    public DateTime Birthdate { get; set; }
}
```

How can I now create and run migrations that do not conflict with each other? I don't think having an additional table with attributes always linked to exactly one entity would be efficient. I also do not know which modules the user installs beforehand, so a centralized migration project is also not an option. 

Could anyone point me into the right direction? or do I need to use a different ORM since this is Out-of-Scope for EFCore?

Thank you for reading my rambling

## Environment info:
**EntityFramework Core version:** 8.0.2
**EntityFramework Data provider:** Pomelo.EntityFrameworkCore.MySql
**.Net Core major version:** 8

**Comment by roji** [comment]
It's not clear exactly what you're looking for, how the different entity types from the different assemblies fit together, or what tables you expect to be created exactly. Overall, if each module has its own DbContext and set of entity types, it's self-contained and can/should have its own set of migrations as well, which would e.g. be mapped to its own database. If you're trying to include entities from the different module in a single database and DbContext, the DbContext (or rather, the EF model) must include those entities.

More information on exactly what you're trying to achieve could help us help you further.

**Comment by ApertureDevelopment** [comment]
Hi, sorry about that.

I am currently trying to build a program whose functionality can dynamically be extended by dropping DLL files into a modules folder. These DLL files get dynamically loaded during the program startup, and a bootstrap script is executed. The issue I am facing is with these modules trying to manipulate or add to entities provided by the software itself ( e.g. User ) and extending these with additional properties ( like in the example given above ). Now when trying to generate migrations using ef tool for the module, it (understandably so ) doesn't account for already existing tables by our module loader. So when trying to run the modules migrations I get an error that the table Users already exists. My question is if there is a way to make ef-tool aware of pre-existing data structure from a different dependant assembly so that the generated migrations file only accounts for adding more columns to the tables, instead of creating the entire table. I hope that makes sense

**Comment by roji** [comment]
NHibernate's table-per-subclass corresponds to TPC (table-per-concrete type) in EF Core - [this is explained in our documentation](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-concrete-type-configuration). Have you tried using this and encountered any issues?

**Comment by ApertureDevelopment** [comment]
Let me try to explain my issue again, I think I am misexplaining what I am trying to achieve

In our project, we have a base entity defined in Assembly A, and a derived entity (which adds additional properties) defined in Assembly B. Both should map to the same database table (single-table inheritance). However, Assembly B is dynamically loaded at runtime and isn't hard-referenced by Assembly A.

When using EF Core migrations, the migration tool in Assembly B attempts to create a new table for the derived type, rather than recognizing the existing table created by the base entity in Assembly A. This causes migration conflicts because the table already exists, leading to errors.

**As a result:**

- The migrations in the assembly containing the derived type attempt to create a new table for that type, instead of recognizing the existing table created by the base type from the main assembly.

- This leads to errors during migration execution because the table already exists (created by the base type migration).

**Key Points:**

- Base entity: Defined in Assembly A.
- Derived entity: Defined in Assembly B (dynamically loaded).
- Assemblies: Assembly B is dynamically loaded at runtime and isn't hard-referenced by Assembly A.
- Current behavior: The migration in Assembly B tries to create a new table for the derived entity, even though Assembly A already created the table for the base entity.
- Expected behavior: Both base and derived entities should share the same table (single-table inheritance).
- Current behavior: EF Core is trying to create a new table for the derived type in Assembly B, even though the base type already created the table in Assembly A.

Because Assembly B is dynamically loaded, the migration tool in Assembly A doesn’t automatically know about the derived entities. So to try to solve the issue we have tried to generate migrations per dynamically loaded assembly. It seems that EF Core doesn't natively handle migrations across dynamically loaded assemblies in a way that respects the existing table structure.

**Question:**

Is there a way to configure EF Core’s migration system to handle this scenario? Specifically:

- How can we make the EF Core migration tool in Assembly B aware of the table created by Assembly A, so that it doesn’t try to create a new table for the derived type?
- Is there a strategy or pattern we can use to manage migrations when entities are spread across multiple assemblies, but should share the same database table?

**Comment by roji** [comment]
> single-table inheritance

OK, so you're trying to have a [table-per-hierarchy strategy (TPH)](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration) here.

> we have tried to generate migrations per dynamically loaded assembly

How would that work, what's the behavior you're expecting? Remember that when using TPH, the single table has to have columns defined for both A and B. Since EF has already created the table for A, and is now trying to apply migrations for B, are you expecting it to generate ALTER TABLE statements to add necessary columns from B to the table that's already in the database?

EF doesn't do that, and there are many potential interactions and problems here if it tried. In general, EF works with a single, fully-built model, where all the knowledge of the different entity types has already been finalized; since there are various interactions between tables, that's the reliable way to do things.

> Is there a strategy or pattern we can use to manage migrations when entities are spread across multiple assemblies, but should share the same database table?

Yes. It's perfectly fine to spread your entities over multiple assemblies (and load them dynamically); but you need to make sure they are all loaded and properly added to your model **before** the model is finalized and migrations are applied. In other words, this can work well as long as the dynamic assembly loading is part of your application startup; once you try adding additional entity types at arbitrary times after startup and after migrations have been applied, things become very complicated (and probably not possible to do well/reliably).
