### ISSUE TITLE
Memory growth on Linux with "journal_mode=memory"

### ISSUE THREAD

**Issue by IkerPSR** [dotnet/efcore#34695]
Hello,
I need help with a memory growth problem in **Microsoft.Data.Sqlite 8.0.8** on **Linux** (reproduced on linux-x64 and linux-arm64), and it doesn't happen on Windows.

Tested on a C# .NET8 project, the memory growth occurs when "**PRAGMA journal_mode=memory**" is used: in this mode, when executing commands (ExecuteNonQuery) that affect thousands of lines of a table (for example a DELETE), it is observed that the memory of the thread from which the command was executed, grows and is not released at the end of the command execution. Memory is permanently reserved for each thread that executes the command, so the total memory used by the process grows for each new thread launched.
This only happens on Linux. I have tested the same code on Windows and the memory is freed correctly after each command is executed.

I attach a sample project reproducing the problem:
[Sqlite_journal_mem.zip](https://github.com/user-attachments/files/17027271/Sqlite_journal_mem.zip)

On Windows, the memory is released after command execution
![image](https://github.com/user-attachments/assets/3d34c464-8efe-4aee-a3af-8c104ccb6e9a)

On Linux the memory grows for each thread
![image](https://github.com/user-attachments/assets/a377fd99-0dd4-4767-99c3-a196b369e732)

Am I missing something?

Microsoft.Data.Sqlite version: 8.0.0
Target framework: .NET 8
Operating system: Reproduced on
 - (linux-x64) Ubuntu 20.04.6 LTS 
 - (linux-arm64) linux embedded (Yocto Scarthgap) linux kernel 6.6.3

Thanks in advance

**Comment by roji** [comment]
@IkerPSR do you ever see an actual OutOfMemoryException? If not, this is probably just the normal behavior in a garbage collection language - the GC only kicks in and reclaims memory when it needs to, or based on various parameters. You may want to look into switching from [GC server to workstation mode](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc).

**Comment by IkerPSR** [comment]
Yes, in linux-arm64, the memory grows and grows until it takes up all the system memory and the SO kills the process.
Currently the application is running in GC workstation mode.

**Comment by roji** [comment]
@IkerPSR OK, thanks for confirming. It's quiter unlikely that Microsoft.Data.Sqlite itself could produce a memory leak that's only on Linux - this could be something lower-level...

@cincuranet interested in taking a look?

**Comment by cincuranet** [comment]
@roji I'll have a 👀.

**Comment by IkerPSR** [comment]
Hello,

I have been investigating with  dotnet debugging tools and I see something very strange with the memory after executing DELETE several times
The working set displayed by "dotnet counters monitor" is 372MB,
but the dump ("dotnet dump collect") only shows 649,517 bytes in "dumpheap -stat". Where is the memory going to?
I´m not an expert on memory debugging tools, but it seems very strange...

![image](https://github.com/user-attachments/assets/d609e1fc-3e0c-468f-801d-8c8f605a0b1d)

**Comment by IkerPSR** [comment]
UPDATE: I noticed that when doing the dump, the working set increases, so I ran the test again:
First I monitored the counters (before doing the dump)
![image](https://github.com/user-attachments/assets/cccbab93-ae1c-42a1-bf1d-7e490b8a9005)


and then I made the dump
![image](https://github.com/user-attachments/assets/9d6d5860-e9fe-4d40-add7-5f3807313a2d)

Well, the numbers changed, but the problem is still the same:
The working set is much bigger than the memory reported by the dump...

**Comment by IkerPSR** [comment]
Hello again,

Could the problem be related to glibc-malloc?
and with these environment variables?
 - MALLOC_ARENA_MAX
 - MALLOC_TRIM_THRESHOLD_
I've found these cases:
[](https://github.com/dotnet/runtime/issues/49317#issuecomment-1719135974)
[](https://github.com/dotnet/runtime/issues/13301#issuecomment-535641506)
[](https://github.com/prestodb/presto/issues/8993#issue-258322547)
[](https://github.com/dotnet/diagnostics/issues/4139#issuecomment-1669794989)

After setting the following values
MALLOC_ARENA_MAX=2
MALLOC_TRIM_THRESHOLD=40960
The memory remains estable over 200MB.

I have invented the values ​​and I don't know what they really mean.
@cincuranet Does this make any sense to you?

**Comment by IkerPSR** [comment]
@cincuranet Here it is the captured eeheap, and the real working set is about 350MB...
![image](https://github.com/user-attachments/assets/fe76e835-57fd-4212-a37e-56ab8b29e9b8)

I am currently using the latest version of Microsoft.Data.Sqlite (v8.0.0)

**Comment by cincuranet** [comment]
This gives me the confidence that this is not in managed world, but rather native memory. You can try, again "just in case", run on .NET 9 runtime.

Either way, there's not much we can do here in terms of `Microsoft.Data.Sqlite`. What is left is to figure out whether it is a runtime thing or SQLite thing (or both). Unfortunately we here don't have capacity to do the investigation for you. Feel free to tag me though in whatever place you continue this.
