### ISSUE TITLE
EF Core 9 Native AOT

### ISSUE THREAD

**Issue by olegsavelos** [dotnet/efcore#34705]
Could anyone clarify what is the plan for EF Core 9 / .NET Native AOT?
It is not clear to me if it will be supported fully, partially or not at all.

Thanks!

**Comment by roji** [comment]
There will be preliminary, experimental support for NativeAOT in EF Core 9.0 - this is something we invested considerable effort for 9, but at the moment we built up the infrastructure to hopefully make it into a working feature in 10. We'll be publishing docs on the 9.0 support soon.

**Comment by olegsavelos** [comment]
Will native AOT still be in experimental state in .NET10 ?

**Comment by roji** [comment]
Yes.

**Comment by irunjic** [comment]
Will native AOT also be in experimental state for .NET11 ?

**Comment by roji** [comment]
@irunjic yes. But significant work is underway on NativeAOT, we hope to deliver a new, better story for 12.
