### ISSUE TITLE
Support nested transactions

### ISSUE THREAD

**Issue by VeselovAndrey** [dotnet/efcore#3470]
Hi.
Is nesting transactions supported?

I'm trying to implement 2 following scenarios with nested transactions:
1)

```
var rootTransaction = context.Database.BeginTransaction();
// Add 1st part of data to DB 
var innerTransaction = context.Database.BeginTransaction();
// Add 2nd part of data to DB 
innerTransaction.Rollback();
rootTransaction.Commit();
```

In this case all will be ok. In DB will be stored 1st part of data only.

2) 

```
var rootTransaction = context.Database.BeginTransaction();
// Add 1st part of data to DB 
var innerTransaction = context.Database.BeginTransaction();
// Add 2nd part of data to DB 
innerTransaction.Commit();
rootTransaction.Rollback();
```

I assume that all data should be removed from DB as I made rollback root transaction.
But 2nd part of data still exist in DB.

How to implement nested transactions?

**Comment by rowanmiller** [comment]
Assigning to RTM to review and determine what we want to support here... and throw for things we don't want to support.

**Comment by roji** [comment]
From a PostgreSQL perspective, note that nested or autonomous transactions aren't supported (see [discussion](https://wiki.postgresql.org/wiki/Autonomous_subtransactions), although [savepoints are](http://www.postgresql.org/docs/9.4/static/sql-savepoint.html).

I'm not sure what kind of cross-provider behavior you're aiming for with this, it may be acceptable to simply allow nested transactions at the API level (Begin within Begin), and providers not supporting this would bomb. This is how things work at the ADO.NET level.

**Comment by divega** [comment]
@roji Thanks! This is exactly the kind of information we need. I agree that idealy we would  let the provider handle it or fail. However we need to track the current transaction for the connection (which in ADO.NET isn't available) using a very simplistic approach. In order to work with nesting we would need to switch to using a stack of transactions. That seems doable but competes with many other things so for RTM we need to decide between doing the work to block this scenario or the work to make it function correctly.

**Comment by ShadySadek** [comment]
Hi All, 
Please let me know if there is any fix or work around for this issue, i am struggling in creating transction in EF 6, i need it for writing integration test

Thanks so much for your help

**Comment by ajcvickers** [comment]
@ShadySadek Using transactions in EF6 is documented here: https://msdn.microsoft.com/en-us/data/dn456843
This issue is about transactions in EF Core.

**Comment by ShadySadek** [comment]
Thanks @ajcvickers for your reply
Just to give you more context, in the following code i am assuming that for-each will be executed twice:
_-first loop will be executed successfully and commit the inner transaction._
_-second loop will fail  and Rollback the inner transaction._

**I am expected to find the added rows by the first transaction before rollback the outer transaction but looks like what is happening is rolling back second loop will roll back also first loop**

looks like using **BeginTransaction** within **TransactionScope** has some issues in addition to the issues with nested transaction in EF6

Any thoughts on this? 

```
 using (var OuterTransactionScope = new TransactionScope())
            {
                using (DbContext = new DbContext())
                {
                    foreach (var x in list) // assume this will be executed twice 
                    {
                        try
                        {
                            var innerTransaction = DbContext.Database.BeginTransaction(isolationLevel);
                            DbContext.SaveChanges(); //Add row
                            DbContext.SaveChanges(); //Add row
                            innerTransaction.Commit();
                        }
                        catch (Exception ex)
                        {
                            innerTransaction.Rollback();
                        }
                    }
                    //Expecting to find two rows here but Actually no data get added
                }
```

**Comment by StrangeWill** [comment]
Kind of mixed on this -- nested transactions can be really useful. Mostly for automated tests. I like setting up a database in a state, starting a transaction, running a test, then rolling it back. Makes integration tests really nice.

But some of our more complex stuff uses transactions itself, then it explodes due to nested transactions.

Pondering if I have other options but a nested transaction would make this work really well.

**Comment by AndriySvyryd** [comment]
@StrangeWill As long as your tests don't involve rolling back the transaction before the test ends you can still wrap the whole test in a transaction and flow it through to all the contexts used to avoid creating new (nested) transactions. We have a helper method for this in our tests: https://github.com/aspnet/EntityFrameworkCore/blob/229c3645433e430673ea85558f9c76ac364f9aa9/src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs#L491

**Comment by ajcvickers** [comment]
After further thought, the complexity of doing this, especially in a database agnostic way, is very high. Therefore, for now, we are closing this as something we don't intend to work on. However, we would of course reconsider this based on sufficient and compelling feedback.

**Comment by SoftCircuits** [comment]
> @ShadySadek Using transactions in EF6 is documented here: https://msdn.microsoft.com/en-us/data/dn456843 This issue is about transactions in EF Core.

Unfortunately, this article doesn't appear to offer any suggestions about when transactions are nested. Or how to correctly have nested transactions in the code, even if they are not truly nested by the database.
