### ISSUE TITLE
Including a view with nested properties

### ISSUE THREAD

**Issue by luukvnes** [dotnet/efcore#34721]
Hi, I was wondering whether it is possible to create a view that contains nested properties. (Example below). The issue is that keyless entity types are not allowed to have nested properties. However I would like the view to be one single table in the database containing all the information, once the information is queried I would like to be able to access proprties using navigation instead of one large c# class that contains all the data similarly to the table.

```
[Keyless]
public class Order
{
    public StreetAddress ShippingAddress { get; set; }
}
[Owned]
public class StreetAddress
{
    public string Street { get; set; }
    public string City { get; set; }
}

modelBuilder.Entity<Order>(
            eb =>
            {
                eb.ToView("View_orders");
            });
```

EF Core version: 8 (newest)
Database provider: Npgsql
Target framework: 8.0
Operating system: linux
IDE: vscode

**Comment by ajcvickers** [comment]
@luukvnes The best way to do this is with [complex types](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#value-objects-using-complex-types). In your example, change `[Owned]` to `[ComplexType]`.
