### ISSUE TITLE
EF 9 Compiled model generate code with errors

### ISSUE THREAD

**Issue by gaglia** [dotnet/efcore#34723]
Hi,

I was trying to run some tests with the pre-compiled model with the latest version 9.0.0-rc.1.24451.1 to analyze the performance issues already reported in this issue: https://github.com/dotnet/efcore/issues/33483

As even in our application we encounter big problems in the creation times of the first instance of our model.

The problem is that trying to create the precompiled model with the command:

```
dotnet ef dbcontext optimize --output-dir MyCompiledModels --namespace MyCompiledModels
```

It generates code with a compilation error, for example:

"The name 'UnsafeAccessor_CompiledModelTest_Blog0000_Tags_Get' does not exist in the current context"

If I use the command with the new experimental option --nativeaot
```
dotnet ef dbcontext optimize --output-dir MyCompiledModels --namespace MyCompiledModels--nativeaot
```

The generated code has no compilation errors.

I used the same project created by @ajcvickers
https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Miscellaneous/CompiledModels

Can you verify ?
Thanks

### Include provider and version information

EF Core version: 9.0.0-rc.1.24451.1
Target framework: .NET 9.0
Operating system:
IDE: Visual Studio 2022 17.12.0 Preview 2.0

**Comment by roji** [comment]
@AndriySvyryd seems like a potential 9.0 servicing bug...

**Comment by AndriySvyryd** [comment]
This was fixed in https://github.com/dotnet/efcore/commit/2a6e5ae07e71cb5d52414277de4ee7a78d92dbf0 and will ship in RC2, for now please add --nativeaot
