### ISSUE TITLE
The SaveChanges can't track items created by Enumerable.Repeat

### ISSUE THREAD

**Issue by armintodev** [dotnet/efcore#34747]
I have a problem with AddRange() entity in the database that was created by Enumerable.Repeat to avoid creating entities by the `for` keyword. but Enumerable.Repeat will make a pointer instead of creating a real object with a different reference.

piece of Code:
```C#
var cargoCar = new CargoCar(arg1, arg2, arg3);
var cargoCars = Enumerable.Repeat(cargoCar, count).ToArray();

await cargoCarRepository.AddRangeAsync(cargoCars, CT);

await unitOfWork.SaveChangesAsync(ct);
```

It also won't track real objects created by:
```C#
Enumerable.Range(0, 4).Select(i => cargoCar).ToArray();
```

The EF will create one entity in DB.
What's the best solution for creating copy objects without `for`

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: macOS

**Comment by roji** [comment]
@armintodev Enumerable.Repeat() returns an enumerable with the same CargoCar (reference equality), not different instances of CargoCars which have the same contents. It's as if you add the same instance multiple times - it's still the same instance, and so only one thing gets added to the database.

It's up to you to create copies of your CargoCar instances - doing so depends on your implementation. For example, you could do something like the following:

```c#
var count = 3;
context.Blogs.AddRange(Enumerable.Range(0, 3).Select(_ => new CargoCar(arg1, arg2, arg3)));
```

**Comment by armintodev** [comment]
@roji Yes, I know about the same reference. I think it would be better to create a new brand method for just EfCore to create a new instance in the Repeat() method
