### ISSUE TITLE
Update Microsoft.CodeAnalysis.Workspaces.MSBuild dependency

### ISSUE THREAD

**Issue by sebastienros** [dotnet/efcore#34757]
This has a vulnerable transitive dependency. 
![image](https://github.com/user-attachments/assets/89a9b744-d982-4bf9-8e63-4e2b6b4bca28)

The newer versions don't have this dependency.

**Comment by roji** [comment]
Duplicate of #34649

**Comment by roji** [comment]
@sebastienros yeah, we fixed this post-rc.1 - rc.2 should be completely warning-free.
