### ISSUE TITLE
Using ToString() on a value object causes unnecesssary case expression in query

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/efcore#34750]
I posted issue [34749](https://github.com/dotnet/efcore/issues/34749) concerning a created query. In this context I experienced another issue.

In the projection I access properties that are custom types using value objects:
```
danceCoverImage.Language == null ? null : danceCoverImage.Language.Tag,
danceCoverImage.ScreenSize == null ? null : danceCoverImage.ScreenSize.Value,
```
This produces a query with the correct fields. 

By accident I used ToString() in one projection.
```
danceCoverImage.Language == null ? null : danceCoverImage.Language.ToString(),
danceCoverImage.ScreenSize == null ? null : danceCoverImage.ScreenSize.ToString(),
```
As a result additional `CASE` statements are added to all those fields in the `SELECT` statements, i.e.:
```
CASE
    WHEN [l0].[Language] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END AS [c],
[l0].[Language],
```
I don't understand why this extra flag is created in the query.

When I use the property of the value object, the problem doesn't occur, so it is currently no issue for me, but I wanted to report this strange behavior. 

---
EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Win 11
Visual Studio 2022 17.11.4

**Comment by roji** [comment]
@KillerBoogie can you please test this with 9.0.0-rc.1? Some optimizations to query generation have been made in 9.0 (especially around CASE/WHEN) and this may already look better.

**Comment by KillerBoogie** [comment]
When testing with 9.00-rc.1 the case statements did not show up again! The referenced issue 34749 still exists.

P.S.: It was quite difficult to test with 9.00-rc.1. I first installed the .Net 9 SDK, but the compiler in Visual Studio complained that it is not installed. I had to install Visual Studio 17.12 preview 2, too. After the updates of the nuget packages to 9.00 I received a bunch of errors that for example System.Text.Json 7.0.3, Microsoft.Identity.Client 4.56.0 and Azure.Identity 1.10.3 had vulnerabilities. I got those errors despite that they were not referenced in the project file! They must be used by other packages, but I couldn't find out which one used it. I had to manually update each one for each project. Also the upgrade for Microsoft.AspNetCore.Mvc.Testing failed until all vulnerabilities were solved..

**Comment by roji** [comment]
@KillerBoogie thanks for testing, and happy to hear the CASE/WHEN was optimized way.

Yes, we're aware of the vulnerability warnings in 9.0.0-rc.1 - these are also fixed in the latest daily builds, and so will not happen in rc.2.

**Comment by KillerBoogie** [comment]
> Yes, we're aware of the vulnerability warnings in 9.0.0-rc.1 - these are also fixed in the latest daily builds, and so will not happen in rc.2.

It would have been nice to warn me and save me wasted hours.

**Comment by roji** [comment]
Sorry you wasted time on this... This kind of thing can unfortunately happen when using prerelease software.
