### ISSUE TITLE
How to extract projection logic into separate methods

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/efcore#34751]
I posted issue [34749](https://github.com/dotnet/efcore/issues/34749) concerning the same projection. My question here is: how can I extract projection logic into separate methods to make the code cleaner? 

The projection:

```
List<LocationMLResponse> Locations;

var query = dbContext.Location.AsNoTracking()
           .Select(location => new LocationMLResponse(
            location.Id.Value,
            location.Name.ToStringDictionary(),
            location.CoverImages
                .Join(dbContext.Image.AsNoTracking(),
                danceCoverImage => danceCoverImage.ImageId,
                image => image.Id,
                (danceCoverImage, image) => new ImageItemResponse(
                    danceCoverImage.ImageId.Value,
                    danceCoverImage.DisplayOrder,
                    danceCoverImage.Language == null ? null : danceCoverImage.Language.Tag,
                    danceCoverImage.ScreenSize == null ? null : danceCoverImage.ScreenSize.Value,
                    danceCoverImage.FocusPointX,
                    danceCoverImage.FocusPointY,
                    image.Uri.ToString(),
                    image.MetaData.Width,
                    image.MetaData.Height
                )).ToList(),
            location.Address.MapToDto(),
            location.Created,
            location.LastModified,
            location.Version
            ));

Locations = await query.ToListAsync();
```
I tried to make the code more readable and extracted methods for the mapping:

```
var query = dbContext.Location.AsNoTracking()
           .Select(location => MapToLocationResponse.MLResponse(dbContext, location));

internal static class MapToLocationResponse
{
    public static LocationMLResponse MLResponse(VCDbContext dbContext, Location location)
    {
        return new LocationMLResponse(
            location.Id.Value,
            location.Name.ToStringDictionary(),
            location.CoverImages
                .Join(dbContext.Image.AsNoTracking(),
                danceCoverImage => danceCoverImage.ImageId,
                image => image.Id,
                (danceCoverImage, image) => Mappings.MapToImageItemResponse(danceCoverImage, image)).ToList(),
            location.Address.MapToDto(),
            location.Created,
            location.LastModified,
            location.Version
            );
    }
}

internal static partial class Mappings
{
    public static ImageItemResponse MapToImageItemResponse(ImageItem imageItem, Image image)
    {
        return new ImageItemResponse(
            imageItem.ImageId.Value,
            imageItem.DisplayOrder,
            imageItem.Language == null ? null : imageItem.Language.ToString(),
            imageItem.ScreenSize == null ? null : imageItem.ScreenSize.ToString(),
            imageItem.FocusPointX,
            imageItem.FocusPointY,
            image.Uri.ToString(),
            image.MetaData.Width,
            image.MetaData.Height
        );
    }
}
```

This code creates the query:
```
     SELECT [l].[LocationId], [l].[Created], [l].[CreatedBy], [l].[CreatedInNameOf], [l].[LastModified], [l].[LastModifiedBy], [l].[LastModifiedInNameOf], [l].[Name], [l].[TId], [l].[Version], [l].[Address_City], [l].[Address_CountryId], [l].[Address_CountryName], [l].[Address_DeliveryInstruction], [l].[Address_State], [l].[Address_Street], [l].[Address_StreetAffix], [l].[Address_StreetNumber], [l].[Address_ZipCode], [l0].[TId], [l0].[DisplayOrder], [l0].[FocusPointX], [l0].[FocusPointY], [l0].[ImageId], [l0].[Language], [l0].[LocationId], [l0].[ScreenSize]
     FROM [VC].[Location] AS [l]
     LEFT JOIN [VC].[LocationCoverImage] AS [l0] ON [l].[LocationId] = [l0].[LocationId]
     ORDER BY [l].[LocationId]
```
The join to the Image table and the selection of the fields is missing.

I tried nesting only one mapping:
```
 List<LocationMLResponse> Locations;

 var query = dbContext.Location.AsNoTracking()//.AsSplitQuery()
            .Select(location => new LocationMLResponse(
             location.Id.Value,
             location.Name.ToStringDictionary(),
             location.CoverImages
                 .Join(dbContext.Image.AsNoTracking(),
                 danceCoverImage => danceCoverImage.ImageId,
                 image => image.Id,
                 (danceCoverImage, image) => Mappings.MapToImageItemResponse(danceCoverImage, image)).ToList(),
             location.Address.MapToDto(),
             location.Created,
             location.LastModified,
             location.Version
             ));

 Locations = await query.ToListAsync();
```
This  projection creates the same query as if with the full projection on top.

How can I split the logic so that EF Core still produces the correct query? I have many entities that have a property of type `List<ImageItem>`. Therefore, I don't want to repeat the code for every entity.

---
EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Win 11
Visual Studio 2022 17.11.4

**Comment by KillerBoogie** [comment]
Can anyone give me an answer?

**Comment by KillerBoogie** [comment]
Since the mapping methods are static, I expected EF Core to be able to analyze those methods. Apparently, this does not work. It seems that EF Core only handles expressions. 

I further realized that when I used the nesting for the Join
`(danceCoverImage, image) => Mappings.MapToImageItemResponse(danceCoverImage, image)`
the created query fetches every field of the joined Image table and not just the projected ones. 

```
 SELECT [s].[ImageId], [s].[DisplayOrder], [s].[Language], [s].[ScreenSize], [s].[FocusPointX], [s].[FocusPointY], [s].[Uri], [s].[c], [s].[c0], [l].[LocationId]
 FROM [VC].[Location] AS [l]
 INNER JOIN (
     SELECT [l3].[ImageId], [l3].[DisplayOrder], [l3].[Language], [l3].[ScreenSize], [l3].[FocusPointX], [l3].[FocusPointY], [i0].[Uri], CAST([i0].[MetaData_Width] AS bigint) AS [c], CAST([i0].[MetaData_Height] AS bigint) AS [c0], [l3].[LocationId]
     FROM [VC].[LocationCoverImage] AS [l3]
     INNER JOIN [VC].[Image] AS [i0] ON [l3].[ImageId] = [i0].[ImageId]
 ) AS [s] ON [l].[LocationId] = [s].[LocationId]
 ORDER BY [l].[LocationId]
```

With the help of [stackoverflow](https://stackoverflow.com/questions/79054913/ef-core-linq-projection-with-nested-extracted-logic-does-not-work#79055941) I got this solution:

```
public async Task<Result<LocationsResponse>> GetLocations()
{
    List<LocationMLResponse> Locations;
    
    var baseQuery = dbContext.Location.AsNoTracking().AsSplitQuery();
    
    IQueryable<LocationMLResponse> query = MapToLocationResponse.MLResponse(dbContext, baseQuery);
    
    Locations = await query.ToListAsync();
    
    ...
}

internal static class MapToLocationResponse
{
    public static IQueryable<LocationMLResponse> MLResponse(VCDbContext dbContext, IQueryable<Location> query)
    {
        return query.Select(location => new LocationMLResponse(
                location.Id.Value,
                location.Name.ToStringDictionary(),
                location.CoverImages.AsQueryable()
                    .Join(dbContext.Image.AsNoTracking(),
                    locationCoverImage => locationCoverImage.ImageId,
                    image => image.Id,
                    Mappings.MapToImageItemResponse()).ToList(),
                location.Address.MapToDto(),
                location.Created,
                location.LastModified,
                location.Version
                ));
    }
}

internal static partial class Mappings
{
    public static Expression<Func<ImageItem, Image, ImageItemResponse>> MapToImageItemResponse()
    {
        return static (danceCoverImage, image) => new ImageItemResponse(
                        danceCoverImage.ImageId.Value,
                        danceCoverImage.DisplayOrder,
                        danceCoverImage.Language == null ? null : danceCoverImage.Language.Tag,
                        danceCoverImage.ScreenSize == null ? null : danceCoverImage.ScreenSize.Value,
                        danceCoverImage.FocusPointX == null ? null : danceCoverImage.FocusPointX.Value,
                        danceCoverImage.FocusPointY == null ? null : danceCoverImage.FocusPointY.Value,
                        image.Uri.ToString(),
                        image.MetaData.Width,
                        image.MetaData.Height);
    }
}
```

Adding `AsQueryable()` to `location.CoverImages.AsQueryable()` was crucial for the code to compile. Why is this necessary? Is this the recommended solution or is there a better way to extract LINQ sections into separate methods?

Independent from this solution, I still don't understand why in my example above EF Core created just a query for the location data.

**Comment by ilmax** [comment]
> Since the mapping methods are static, I expected EF Core to be able to analyze those methods. Apparently, this does not work. It seems that EF Core only handles expressions.

Where does this expectation comes from?

This [article](https://learn.microsoft.com/en-us/ef/core/querying/client-eval) should help you understand why you're running into the issue

**Comment by KillerBoogie** [comment]
I did not extract a lambda, just the constructor of the DTO. Since it is a static method and a static return, I expected the compiler to produce the same result as if wrote it directly and therefore not affecting EF Core. The lambda variables of the LINQ were passed into the method.

**Comment by KillerBoogie** [comment]
Thanks.

> The linked article explains you the difference about server vs client evaluation and that's what causing your unexpected behaviour above.

I'm aware of the difference. As I said I didn't expect the static calls to be a problem.

> If you want to put mapping logic in separate method, you can do it similar to this pseudo

I'm also aware of composing the LINQ expression with IQueryable. I use the same logic for the select code that is identical for single and list requests.

>/*  your mapping logic here, with no other method calls */

That's the critical part. I return a nested structure and the nested object (`List<ImageItemResponse>`) is returned for many different requests. So I need a technique that allows me to use other method calls inside the `Select`. For this (common) problem the stated article didn't provide any information and I didn't find any information or examples in the EF Core documentation.

**In my post above I stated a solution that works**. You can extract the call as an expression. An example like this should be in the EF Core documentation.

>You need to be careful of what's in your Linq query, especially if the inner workings of EF are not very familiar.

I find this a major problem in the documentation. There is way too little information about the why and many examples are just simple ones. One needs to view courses and extra articles, e.g. by Julie Lerman that explain the why. EF Core is supposed to make things easier, but to my experience it does the opposite. Too many hidden conventions, magic behaviors, and bugs. With raw SQL I would have not wasted so much time :-)

**Comment by ilmax** [comment]
> There is way too little information about the why

I actually think this is the easiest part to understand in my case, how you translate a method that has unknown semantics in SQL? easy, you can't.

> and many examples are just simple ones

I can see your point here, that's why the community write blog posts about additional use cases, but discoverability of those blog posts is an issue. EF documentation can be expanded but it will never be able to cover all possible usages, that's simply impossible.

> You can extract the call as an expression. An example like this should be in the EF Core documentation.

That's a good idea, I'm sure the team is also more than happy if you give it a shot and will guide you towards getting the additional documentation merged.

> With raw SQL I would have not wasted so much time :-)

Bear in mind that EF is not an all-or-nothing tool, I think EF shines on the write side and it's doing a good job on the reading side as well, but if it gets in your way too much, you can always use something like dapper, roll your own RAW SQL and call it a day.

**Comment by KillerBoogie** [comment]
> That's a good idea, I'm sure the team is also more than happy if you give it a shot and will guide you towards getting the additional documentation merged.

I don't have time right now, but how could I add something to the documentation? Is there a document about that?

The extracted expression works!

**Comment by ilmax** [comment]
> but how could I add something to the documentation

A PR to this repo https://github.com/dotnet/EntityFramework.Docs should do

> The extracted expression works!

Great!

**Comment by pszeder** [comment]
I think the [EntityFrameworkCore.Projectables](https://github.com/koenbeuk/EntityFrameworkCore.Projectables) package does exactly what you were looking for.
