### ISSUE TITLE
In SQLite, EF converts the DateTime value "" to 0001-01-01 00:00:00, not null

### ISSUE THREAD

**Issue by z505985755** [dotnet/efcore#34773]
![image](https://github.com/user-attachments/assets/b1af70d5-37b6-4c8b-bbfb-a0fabbfde137)
The consequence of this is that when the value in sqlite is "", the value obtained by EF is inconsistent with the database. If IsConcurrencyToken is configured, the update will fail. Although the value created or updated by EF is null in the database, the value in the database can be set to "" by other means. I noticed that it is defined as DateTime type in EF, but it is TEXT type in sqlite. I don't know why this happens.

As shown in the figure, the fourth row of data is converted to null, but the third row of data is converted to 0001-01-01 00:00:00

**Comment by TortillaZHawaii** [comment]
> I noticed that it is defined as DateTime type in EF, but it is TEXT type in sqlite. I don't know why this happens.

SQLite does not have a DataTime type. See https://www.sqlite.org/datatype3.html#date_and_time_datatype

**Comment by z505985755** [comment]
> > I noticed that it is defined as DateTime type in EF, but it is TEXT type in sqlite. I don't know why this happens.
> 
> SQLite does not have a DataTime type. See https://www.sqlite.org/datatype3.html#date_and_time_datatype

"" to 0001-01-01 00:00:00 Is this by design?

**Comment by cincuranet** [comment]
I don't know whether we can call "" resulting in 0001-01-01 00:00:00 as by design. But it looks bit incorrect to me. I think we should throw exception.

**Comment by cincuranet** [comment]
@z505985755 I can't replicate it. Here's my code. Can you make it reproduce the behavior you're describing?

```csharp
using Microsoft.EntityFrameworkCore;

using var db = new MyContext();
db.Database.OpenConnection();
db.Database.EnsureCreated();
db.Database.ExecuteSqlRaw("insert into DTs values (1, null)");
db.Database.ExecuteSqlRaw("insert into DTs values (2, '11/08/2024 19:33:29')");
db.Database.ExecuteSqlRaw("insert into DTs values (3, '')");
foreach (var item in db.DTs)
{
    Console.WriteLine($"{item.Id}|{item.DateTime}");
}

class MyContext : DbContext
{
    public DbSet<DT> DTs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite();
    }
}
class DT
{
    public int Id { get; set; }
    public DateTime? DateTime { get; set; }
}
```

On my side it results in exception on 3rd item:

```text
Unhandled exception. System.FormatException: String '' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
```
