### ISSUE TITLE
EFCore does not respect [MaxLength] if it came on a field from an interface

### ISSUE THREAD

**Issue by AlexBaggett** [dotnet/efcore#34778]
## File a bug

I'm not sure if this a bug or more a missing feature. But either way, EF doesn't function in way the api consumer expects here.

### Include your code

```C#
    public interface IReferenceData
    {
        [MaxLength(512)]
        public string ReferenceId { get; set; }
    }
    public class MyEntity: IReferenceData
    {
       public required string ReferenceId {get; set;}
    }
```

EF will generate a migration for that has ReferenceId as nvarchar(max)

### Include provider and version information

EF Core version: 8.202
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 8.202
Operating system: Windows
IDE: (e.g. Visual Studio 2022 17.10.3

**Comment by maumar** [comment]
dupe https://github.com/dotnet/efcore/issues/34779
