### ISSUE TITLE
Unable to Download Microsoft.EntityFrameworkCore Libraries in Visual Studio 2022

### ISSUE THREAD

**Issue by khan2132-coder** [dotnet/efcore#34784]
I'm experiencing issues downloading Microsoft.EntityFrameworkCore libraries in Visual Studio 2022 using NuGet Package Manager.

Details:
- Visual Studio version: 2022
- .NET version: [Insert .NET version]
- Entity Framework Core version: [Insert Entity Framework Core version]
- Operating System: [Insert Operating System]
- Error message: [Insert error message, if any]

Reproduction Steps:

1. Create a new project in Visual Studio 2022.
2. Search for Microsoft.EntityFrameworkCore in NuGet Package Manager.
3. Attempt to install.
4. Download fails.

Expected Behavior:
Microsoft.EntityFrameworkCore libraries should download successfully.
Actual Behavior:
Download fails.
Labels:

- Entity Framework Core
- Visual Studio 2022
- NuGet Package Manager
- Download Issue## Ask a question

Remember:

* Please make your question as clear and specific as possible.
* Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include verbose output when asking questions about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by maumar** [comment]
This is likely a problem on your end, things work fine for me, and I would expect multiple people reporting the issue if it was something on our end. As is, there is not enough information for us to take any meaningful action. Please provide more details if you are still hitting the problem.
