### ISSUE TITLE
Problems .Net8 Microsoft.EntityframeworkCore.Design 8.0.8 with ReportViewerCore.NETCore 15.1.19 or upper

### ISSUE THREAD

**Issue by jvsancho80** [dotnet/efcore#34782]
When I add the NuGet package  ReportViewerCore.NETCore 15.1.19 or upper I have a conflict.

![image](https://github.com/user-attachments/assets/6beb4fc2-c90e-49c2-b6b3-e8076be47420)

I asked ReportViewerCore.NETCore and said this https://github.com/lkosson/reportviewercore/issues/192

I don't understand why Microsoft.EntityFreameworkCore.Design 8.0.8 not use this version and use Microsoft.CodeAnalisys.Common 4.5.0

**Comment by AndriySvyryd** [comment]
EF Core 8.0.8 references 4.5.0 for compatibility with VS 17.5, see https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022

You can reference [Microsoft.CodeAnalysis.CSharp.Workspaces](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/) 4.8.0 in your project explicitly to avoid this warning
