### ISSUE TITLE
Don't require connection string during migration remove

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#34788]
I'm looking to remove a migration I created in a class library.  I was able to create it without requiring a viable `DbContext`, yet when I go to remove the last migration I just created, the EF Core tools crash because they aren't being triggered from a project that configures the context.

Ideally, I'd like to just be able to use the CLI tools without having any notion of a running database be presumed, as that's just not a necessity.

**Comment by AndriySvyryd** [comment]
You can already use `dotnet ef migrations remove --force`

**Comment by AndriySvyryd** [comment]
Making it the default would remove most of the value (i.e. noone would use the inverted option)
See https://github.com/dotnet/efcore/issues/24271 for more discussion
