### ISSUE TITLE
EF Core 8.0 fails choosing the right constructor when creating entities from DB having multiple constructors

### ISSUE THREAD

**Issue by SetTrend** [dotnet/efcore#34783]
**EF Core 8.0 Fails Choosing The Right Constructor When Creating Entities From DB Having Multiple Constructors**

In my test case, the `Model.Lookups.ProjectItem` entity provides three different constructors, each validating their constructor arguments:

```c#
public ProjectItem(int id, bool isRequired, ItemDataType dataType);
public ProjectItem(int id, bool isRequired, ItemDataType dataType, byte precision);
public ProjectItem(int id, bool isRequired, ItemDataType dataType, KnowledgeCategory knowledgeCategory);
```

## Current Situation

When reading data from the database, EF Core 8.0 does not use the proper constructor.

With this data:

|Id|IsRequired|DataType|Precision|KnowledgeCategory|
|-|-|-|-|-|
|3|0|6||0|

… EF Core 8.0 fails to select constructor #3. It, instead, chooses constructor #1.

## Desired Situation

EF Core should select the right constructor from …

1. Number of non-nullable constructor parameters matching number of non-null column values,
   ordered by number of constructor parameters, descending
1. parameter data type
1. parameter name (if parameter data type alone cannot be uniquely matched)

If a row has more non-null columns than constructor parameters available, these surplus values ought to be set using property initializers then.

## Minimum Reproducible Example

https://github.com/SetTrend/EFC-Constructor-MRE

**Comment by maumar** [comment]
Currently all constructor binding is static and non-configurable. Improvements to that area are tracked here: https://github.com/dotnet/efcore/issues/10789

Also some documentation on what's currently possible: https://learn.microsoft.com/en-us/ef/core/modeling/constructors
