### ISSUE TITLE
Exclude individual enum values

### ISSUE THREAD

**Issue by Atulin** [dotnet/efcore#34789]
EF now encourages using sentinel properties for value types like `int` or various `enum`s. Currently, there are two ways to use a sentinel value with EF:

1. Use an `Invalid` enum value

```cs
public enum ShipmentStatus
{
    Invalid = 0,
    Completed = 1,
    Sent = 2,
    Delivered = 3,
    Cancelled = 4,
}
```
```cs
.HasSentinel(ShipmentStatus.Invalid)
```
```cs
if (x.Status != ShipmentStatus.Invalid)
```

2. Set the sentinel to a value that does not occur in the enum

```cs
public enum ShipmentStatus
{
    Completed = 0,
    Sent = 1,
    Delivered = 2,
    Cancelled = 3,
}
```
```cs
.HasSentinel((ShipmentStatus)(-1))
```
```cs
if ((int)x.Status != -1)
```

but both have their issues. The first solution creates an `invalid` value of the enum in the database, which makes it a de facto **valid** value. The second solution meanwhile, loses type safety. Not that there is much type safety to be had with C# enums in the first place, but we lose last shreds of it.

Ideally, I would like some sort of attribute, like `[EnumSentinel]` that would keep that value on C# side, but would **not** create it in the database. That way, it would actually make for a sentinel, and access to it would be fully type-safe.

```cs
public enum ShipmentStatus
{
    [EnumSentinel] Invalid = 0,
    Completed = 1,
    Sent = 2,
    Delivered = 3,
    Cancelled = 4,
}
```
```cs
.HasSentinel(ShipmentStatus.Invalid)
```
```cs
if (x.Status != ShipmentStatus.Invalid)
```
```sql
CREATE TYPE shipment_status AS ENUM ('completed', 'sent', 'delivered', 'cancelled');
```

**Comment by roji** [comment]
> Ideally, I would like some sort of attribute, like [EnumSentinel] that would keep that value on C# side, but would not create it in the database. That way, it would actually make for a sentinel, and access to it would be fully type-safe.

So what should be saved to the database when the .NET enum value is the sentinel?

**Comment by Atulin** [comment]
That's a good point, actually.

I think that the sentinel should be sent, and since the database should not accept it, the query should throw. Same as what happens when trying to insert `'trimethyloxonium_tetrafluoroborate'` as shipment status. Same as trying to insert `(ShipmentStatus)(-9999)`, which is a thing that can easily be done due to how C# enums work.

**Comment by roji** [comment]
Well, EF currently reflects exactly what you do in .NET in the database - just like .NET doesn't throw for "invalid" numbers, neither does EF.

It sounds like you're maybe looking for [EFCore.CheckConstraints](https://github.com/efcore/EFCore.CheckConstraints) (specifically the [enum constraints](https://github.com/efcore/EFCore.CheckConstraints?tab=readme-ov-file#enum-constraints) feature); this will add check constraints ensuring that your database only contains values which correspond to your .NET enum labels. At that point you can have a .NET enum definition as follows:

```c#
public enum ShipmentStatus
{
    Completed = 1,
    Sent = 2,
    Delivered = 3,
    Cancelled = 4,
}
```

Note that the default value for the enum is 0, which doesn't have a corresponding enum label and therefore would have a check constraint error if you try to insert it.

**Comment by Atulin** [comment]
Ah, I guess that would indeed work, with sentinel value set to `default(ShipmentStatus)`. Or not even set, since the `default` value is the, well, default sentinel.

**Comment by roji** [comment]
Yep, exactly.
