### ISSUE TITLE
Modelbuilder.Model.GetEntityTypes() does not return mapped type T if there is not DbSet<T> defined in the context class

### ISSUE THREAD

**Issue by mnissl** [dotnet/efcore#34791]
In `OnModelCreating()`, `modelBuilder.Model.GetEntityTypes()` does not return a mapped type `T` if the context class does not have a corresponding `DbSet<T>` property defined.

Is this by design?

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by maumar** [comment]
@mnissl I'm unable to reproduce this on my end. Here is the code I'm trying out. Please modify it in a way that reproduces the problem for in your environment.


```cs

    using var ctx = new MyContext();
    await ctx.Database.EnsureDeletedAsync();
    await ctx.Database.EnsureCreatedAsync();

    public class MyContext : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MyEntity>();

            var ets = modelBuilder.Model.GetEntityTypes();

            Assert.Equal(1, ets.Count());
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro34791;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public decimal Number { get; set; }
    }
```

**Comment by mnissl** [comment]
I guess I can explain the behaviour and that is most probably by design: if you have a `DbSet<T>` property in your class, this type `T` is then already known at the beginning of `OnModelCreating()`, even before any mapping statements like `modelBuilder.Entity<T>()`.

I had the following code at the beginning of `OnModelCreating()`:

```cs
    foreach (var entityType in modelBuilder.Model.GetEntityTypes())
    {
      entityType.SetTableName(entityType.DisplayName()); // table names in singular
      entityType.UseSqlOutputClause(false);
    }
```

And I was faced with the fact that `UseSqlOutputClause(false)` did not work for types where I had not defined their `DbSet` properties. (Those types were also in another schema, so I had `ToTable()` calls which fixed the issue with table name in singular.)

That's why I got the impression that those properties are necessary to define, while the true solution is to have this code at the end of `OnModelCreating()`.
