### ISSUE TITLE
Investigate rising use of memory which may indicate a leak

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#34809]
See https://github.com/dotnet/efcore/issues/34028#issuecomment-2179190429

**Comment by roji** [comment]
@enanhgon can you please confirm whether you're actually getting an OutOfMemoryException via your repro?

**Comment by renanhgon** [comment]
Hi @roji,

I was only able to reproduce the issue when running the application in containerized environments with specific memory limits. 
When running it locally and pinging the mentioned route, I noticed a gradual increase in memory usage through diagnostic tools. However, even when applying the same memory limits locally as used in my pods, I couldn’t reproduce the OutOfMemoryException.

**Comment by roji** [comment]
Whether you run the application in a containerized environment shouldn't have an impact here, aside from the memory limits that entails. I'll go ahead and close this for now as we don't have a repro or evidence of a problem - a gradual increase of memory usage is normal, as explained in #34028 - the GC will kick in as needed, according to its own considerations etc.
