### ISSUE TITLE
ChangeTracker.HasChanges() returns false even when entries are marked for deletion

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet/efcore#34804]
HasChanges might return null when there are pending changes.

This does not really match the documentation which says that
 ```
Checks if any new, deleted, or changed entities are being tracked
such that these changes will be sent to the database if <see cref="DbContext.SaveChanges()" /> is called
```

The issue was detected when adding a new check for "ChangeTracker.HasChanges()" and doing an early return when overriding SaveChangesAsync in a custuom DbContext. The following sample is based on a unit test which failed.

### Expected behaviour
The expected behaviour is that EITHER 
a. the changetracker does not know of *entity* (it is unchanged, possible with an exception when changing the entry) 
b. OR it is marked for deletion (present in `Entries()` as today) **AND** `HasChanges()`  returns `true`

### Actual behaviour
- The entity *IS marked for deletion* and is part of `Entries()`,  but `HasChanges()`  returns `false`

## Sample code

The following sample is based on a unit test which failed when using trying to use `ChangeTracker.HasChanges()` to detect if save logic needs to run.

Create a new console application (net8.0) and paste the contents.
It will fail with the exception starting with ""BOOM"

```C#
// See https://aka.ms/new-console-template for more information

using System.Diagnostics;
using Microsoft.EntityFrameworkCore;


var entity = new Entity() { Id = 1000 };

var ctx = new SampleContext();
var entry = ctx.Entry(entity);
entry.State = EntityState.Added;

if (!ctx.ChangeTracker.HasChanges()) throw new Exception("This works");

ctx.ChangeTracker.Clear();

entry.State = EntityState.Deleted;

Console.WriteLine($"EFCore version {typeof(DbContext).Assembly.GetName().Version}");

if (!ctx.ChangeTracker.DebugView.ShortView.Contains("Deleted")) 
    throw new Exception("The DebugView correctly shows the entry as deleted");

if (ctx.ChangeTracker.Entries().Where(e => e.State == EntityState.Deleted).Count() != 1)
    throw new Exception("The deleted entry is returned from ChangeTracker.Entries()");

// Calling ctx.ChangeTracker.DetectChanges() has no effect
if (!ctx.ChangeTracker.HasChanges())
    throw new Exception("BOOM - HasChanges should be true if there are deleted entities");

class SampleContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("MyDatabase");
    }

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
    public virtual DbSet<Entity> Entities { get; set; }
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
}

internal class Entity
{
    public int Id { get; set; }
}

```

### Include provider and version information

EF Core version:
- Tested on 6.0, 7.0, 8.0 and 9.0-rc.1
Target framework: (e.g. .NET 8.0)

**Comment by Daniel-Svensson** [comment]
**Note** / Workaround: 

Replacing "entry.State = EntityState.Deleted;" with `ctx.Entry(entity).State = EntityState.Deleted;` seems to solve the issue.

Is it somehow related to all EntityEntry beeing abandoned/invalidated on certain ChangetTracker changes ?

**Comment by AndriySvyryd** [comment]
`ctx.ChangeTracker.Clear();` removes all entries from the change tracker, invoking methods on the now-disconnected objects is no-op. The above workaround is the correct way of changing the state.

**Comment by Daniel-Svensson** [comment]
@AndriySvyryd is changetracker clear the **only** what that happens, or is there any other call that have a similar effect (such as savechanges/acceptchanges or similar

If clear is the only way then the solution seems safe. Otherwise i am jot sure we dare to use haschanges in order to decide if need to setup transactions and call save changes.

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd is changetracker clear the only what that happens, or is there any other call that have a similar effect (such as savechanges/acceptchanges or similar

`.Clear()` and `context.Dispose()` are the only methods that do this. The other ones just change the state of all entries to `Unchanged`

**Comment by bluebaroncanada** [comment]
```cs
gwce.Entry(coverageTermsAndConditionsPdf).State = EntityState.Modified;
```

```
Unable to track an instance of type 'CoverageTermsAndConditionsPdf' because it does not have a primary key. Only entity types with a primary key may be tracked.
```

Ahhh.  Makes sense.
