### ISSUE TITLE
How to use System.Transactions with SqlRetryingExecutionStrategy?

### ISSUE THREAD

**Issue by Xriuk** [dotnet/efcore#34825]
According to this page https://learn.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions
`TransactionScope` is supported on its own, and it works, I tested it.

Now if I use a retry strategy like:
```csharp
var options = new DbContextOptionsBuilder<BloggingContext>()
  .UseSqlServer(connection, builder => builder.EnableRetryOnFailure())
  .Options;
```
I get an exception like this:

> The configured execution strategy 'SqlRetryingExecutionStrategy' does not support user-initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.

So I retrieved the execution strategy as suggested and called `ExecuteAsync()`, `ExecuteInTransactionAsync()`, I tried them all, but they all throw the same exception as above.
Apparently `Execute*` methods do not like a parent `TransactionScope` around them but inside the delegate it seems to work. But that's not what I need since I have other services in the transaction which I don't want to retry in case of EF Core transient failures.

My question is if this is even a feasible scenario at all? Having a parent `TransactionScope` with a retry-able EF core sequence of operations inside it, which if cannot be retried rolls back the parent scope.

**Comment by AndriySvyryd** [comment]
> My question is if this is even a feasible scenario at all? Having a parent `TransactionScope` with a retry-able EF core sequence of operations inside it, which if cannot be retried rolls back the parent scope.

No. Any exception (retryable or not) will rollback the transaction. But if it's a retryable exception then the ExecutionStrategy won't be able to retry any operations in the transaction that were executed prior to invoking `Execute*`. All transactions need to be scoped inside the retryable unit.
