### ISSUE TITLE
UseAzureSql is missing

### ISSUE THREAD

**Issue by vengi83644** [dotnet/efcore#34820]
I am trying to use this method from the SqlServerDbContextOptionsBuilderExtensions.

It's available in https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs#L403

However, it's not available from the NuGet package.

I am thinking the package published is from the below source code,
https://github.com/dotnet/dotnet/blob/main/src/efcore/src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs

Can someone clarify the differences between these sources?

Thanks,
R. Venkatesan

**Comment by vengi83644** [comment]
![image](https://github.com/user-attachments/assets/576cf4b0-a26c-4be6-8a7f-29429dae712b)


![image](https://github.com/user-attachments/assets/b83c2c10-6cb6-48a3-9a80-d4ecb7467716)

**Comment by cincuranet** [comment]
What version are you using? RC1 on NuGet (`9.0.0-rc.1.24451.1`) has all `UseSqlServer`, `UseAzureSql`, `UseAzureSynapse` methods.

**Comment by vengi83644** [comment]
I tried 8.0.8
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.8

**Comment by cincuranet** [comment]
These methods were introduced in EF Core 9, hence you will not find these in 8.x.

**Comment by vengi83644** [comment]
Oops my bad.,.,
