### ISSUE TITLE
System.Data.SqlClient is out of date

### ISSUE THREAD

**Issue by turkmvc** [dotnet/efcore#34856]
Hello, I am developing a project with .Net 8. When I upload the files I published to hosting, it says that the System.Data.SqlClient 5.2 version is not continuous. Can you please update the package? It gives errors in my layered architecture projects such as WebAPI or Clean Architecture.

**Comment by fredrikcarlbom** [comment]
As discussed elsewhere, for example #34227, SqlClient 5.2 isn't a version with long term support (LTS) while EF Core 8 is, so my understanding is that EF Core 8 will continue reference SqlClient 5.1 while EF Core 9 should reference SqlClient 5.2, but [that's currently not the case](https://github.com/dotnet/efcore/blob/release/9.0/Directory.Packages.props#L42), I can't explain why.

**Comment by roji** [comment]
As @fredrikcarlbom wrote above, LTS versions of EF indeed can't depend on non-LTS versions of SqlClient, since the latter would go out of support before the former.

However, you are free to take a dependency on newer versions of SqlClient yourself, in your own project, if you wish.
