### ISSUE TITLE
Json Entity

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#3486]
It would be good if we have an entity type that we write a class like any other and store in the master entity as string in json format, while it could be serialize & deserialize;
_Entity:_

```
public class Person
{
    [Key]
    public int Id { get; set; }
    public DateTime Birthday { get; set; }
    [Json]
    public Name Name { get; set; }
}

public class Name
{
    public string Firstname { get; set; }
    public string Lastname { get; set; }
}
```

_Json:_

```
{
  "Firstname": "Sarin",
  "Lastname": "Na Wangkanai"
}
```

Right now this solution would make ef7 not be able to create a model i think it fall under complex type where you need to define a key.
`The entity type 'EF7.Name' requires a key to be defined.`
- I'm not sure what is EF7 planned idea of complex type is a separated table which is just not having a key (#246)? 
- or is it the idea mention above?

**Comment by rowanmiller** [comment]
In EF6 we had a column in the parent table for each property in the complex type but we agree that serializing the values into a single column is also a neat idea. We probably want to have options to select different strategies and I added a note to #246 to consider this when we design the feature.
