### ISSUE TITLE
[Microsoft.Data.Sqlite] Version of NuGet dependency SQLitePCLRaw.bundle_e_sqlite3 does not correspond with source code

### ISSUE THREAD

**Issue by espenrl** [dotnet/efcore#34860]
Source code defines `2.1.10` (latest) and NuGet-package refers to `>= 2.1.6`

https://www.nuget.org/packages/Microsoft.Data.Sqlite/8.0.10#dependencies-body-tab

![Image](https://github.com/user-attachments/assets/4e691fce-3cd8-490d-99a4-7ebbcc0e90c7)

https://github.com/search?q=repo%3Adotnet%2Fefcore+SQLitePCLRawVersion&type=code

![Image](https://github.com/user-attachments/assets/61329617-dbe1-47b9-b34a-efcbf3681727)

Can't find any traces of the number 2.1.6 in the source code https://github.com/search?q=repo%3Adotnet%2Fefcore+%222.1.6%22&type=code

**Comment by AndriySvyryd** [comment]
You searched on the `main` branch, the 8.0.x versions are produced from the `release/8.0` branch, see
https://github.com/dotnet/efcore/blob/release/8.0/src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj#L43
