### ISSUE TITLE
"The entity type" "is mapped to the stored procedure" "however the store-generated properties" "are not mapped to any output parameter or result column."

### ISSUE THREAD

**Issue by CLHower** [dotnet/efcore#34863]
I am getting the message "The entity type" "is mapped to the stored procedure" "however the store-generated properties" "are not mapped to any output parameter or result column."  

Technically, this message is accurate. However, the property in question is not an output parameter or a result column. It is an input parameter for the input stored procedure. I have noticed that the property in question is a foreign key property to another entity. I have another entity that has it's primary key made up of the foreign keys of two other entities. This does not seem to be a problem. The difference seems to be that the entity in question also has an Identity property that is an output parameter in the insert procedure.

Please tell me how to prevent this message or fix net8.0 ef core so that this is not a problem.

I am very new to GitHub so I don't know if I am pursuing this problem correctly. Please let me know how to better accomplish this.

Thank you.

**Comment by AndriySvyryd** [comment]
If the property in question shouldn't have its value to be generated by the database you can mark it as such by using
```C#
modelBuilder.Entity<MyEntity>(
    b =>
    {
        b.Property(e => e.MyProperty).ValueGeneratedNever();
    });
```

To get the best answers on GitHub create a small runnable console project with just enough code to show your issue, zip it and attach to your question.
