### ISSUE TITLE
Is MariaDB supported?

### ISSUE THREAD

**Issue by robertsilen** [dotnet/efcore#34867]
Is MariaDB supported? Any reason not to add a mention of it to the README?

**Comment by roji** [comment]
We don't maintain a MySQL or MariaDB in this repo - but you can check out [Pomelo.EntityFrameworkCore.MySql/](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/) which does support MariaDB.

**Comment by robertsilen** [comment]
Thanks, since [Pomelo.EntityFrameworkCore.MySql/](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/) supports MariaDB, I suggest with PR https://github.com/dotnet/efcore/pull/34885 to add MariaDB to the README

**Comment by ChrisJollyAU** [comment]
@robertsilen There is a comprehensive list of providers at https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli which does list MariaDB for Pomelo MySql

@roji Had a though as I was typing the above. What about in the readme just below the above mentioned change we add something like `For the full list of providers and databases supported see https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli`

**Comment by roji** [comment]
This is just the very first readme sentence - I don't think there's a need to be exhaustive or point people to the relevant docs at that point specifically... I'd personally rather just keep it short.
