### ISSUE TITLE
EFCore 9 rc1 - sql server - Problem with type mapping during linq to sqlexpression translation

### ISSUE THREAD

**Issue by PrgOrcl** [dotnet/efcore#34900]
When running the  CaseOpWhen_predicate() test in efcore\9.0\test\EFCore.SqlServer.FunctionalTests\Query\NullSemanticsQuerySqlServerTest.cs.  The sql that should be generated is

```sql

SELECT [e].[Id], [e].[BoolA], [e].[BoolB], [e].[BoolC], [e].[IntA], [e].[IntB], [e].[IntC], [e].[NullableBoolA], [e].[NullableBoolB], [e].[NullableBoolC], [e].[NullableIntA], [e].[NullableIntB], [e].[NullableIntC], [e].[NullableStringA], [e].[NullableStringB], [e].[NullableStringC], [e].[StringA], [e].[StringB], [e].[StringC]
FROM [Entities1] AS [e]
WHERE CASE CASE
    WHEN [e].[StringA] = N'Foo' THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
    WHEN 1 THEN 3
    WHEN 0 THEN 2
END = 2
```

The 1 and 0 in the two when clauses (  WHEN 1 THEN 3 and   WHEN 0 THEN 2 ) in the case expression are supposed to represent boolean true and false.  While debugging we noticed that the type mapping of the sqlConstantExpression ("0" and "1") in the when clause is Microsoft.entityFrameworkCore.Storage.BoolTypeMapping. It is not the provider specific type mapping.

In such case, a providers will not be able to generate provider specific boolean values( such as true and false instead of 0 and 1).
For example, on running the above test using sqlServer-

![Image](https://github.com/user-attachments/assets/28de9c7b-5394-4143-aa58-f6652ceec889)

If you expand the computed value of visitedExpression and look at left -> whenClause -> test -> typeMapping , you shall find it is Microsoft.entityFrameworkCore.Storage.BoolTypeMapping

Is this the expected behavior or should the typeMapping be provider specific?

EF Core version: 9.0.0-rc.1.24451.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system: windows
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by roji** [comment]
@PrgOrcl unless I'm mistaken, this specific CASE/WHEN is added in a SQL Server-specific visitor (SearchConditionConvertingExpressionVisitor), so I'm not sure there's an impact here on other providers. Are you seeing an actual problem in any other provider? Are you saying that the behavior was different in 8.0?

/cc @ranma42 - you worked on this stuff recently.

**Comment by ChrisJollyAU** [comment]
No its not part of the SearchConditionConvertingExpressionVisitor. Its part of the tests in NullSemanticsQueryFixtureBase.

You have this in the `OnModelCreating`
```
modelBuilder.HasDbFunction(
    typeof(NullSemanticsQueryFixtureBase).GetMethod(nameof(BoolSwitch)),
    b => b.HasTranslation(
        args => new CaseExpression(
            operand: args[0],
            [
                new CaseWhenClause(new SqlConstantExpression(true, typeMapping: BoolTypeMapping.Default), args[1]),
                new CaseWhenClause(new SqlConstantExpression(false, typeMapping: BoolTypeMapping.Default), args[2]),
            ]))
);
```
Thats where it gets the basic (non-provider specific) BoolTypeMapping. The default behaviour of that is to generate a `1` or `0` not `TRUE` or `FALSE`

I actually picked this up on EFCore.Jet - mostly as with that TRUE is actually `-1`. See https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/commit/f199d04cbae66a0806e9a0a72c1bb35b8936838f

**Comment by ranma42** [comment]
I wrote that test to check that a boolean value can correctly be used as value in a `CASE/WHEN` expression (ideally regardless of the specific provided).
Note that I don't know the providers API deeply, but I assumed that each provider took care of translating the (supported) types. For example the SqlServer has some logic to translate (default-mapped) `true` to `CAST(1 AS bit)` or `1 = 1` depending on the context (respectively, value vs predicates).

Assuming boolean values are consistently translated using the default type mapping (unless the user asks for a different mapping), the test should still pass as intended, as args[0] will have a matching type mapping.

If that is not the case, what would be the appropriate way to construct the translation for `BoolSwitch` (in a cross-provider compatible way)?
@roji Can we omit the type mapping while constructing the `WHEN` clauses and rely on the SqlFactory to fill them in?

**Comment by roji** [comment]
@ChrisJollyAU just to be sure I understand the urgency of this, are you seeing an actual provider problem, or is this just a test issue? If it's the former, is it a new problem introduced in 9 (i.e. a regression)?

**Comment by ChrisJollyAU** [comment]
Honestly the way I see this is its mostly a very minor issue.

It's basically the difference of in this case outputting a `0` or `1` based on the `BoolTypeMapping` (as specified in the test base) versus using a provider specific (e.g. `SqlServerBoolTypeMapping` or any other) where it will use `TRUE` or `FALSE` as default. 

In terms of query results it shouldn't make a difference. Off the top of my head most databases can understand 0 and 1 for boolean as well as any named constants

I had to fix mine but that's just MS Access being different

The only reason you see this slight difference in what string literal is produced is that the base `BoolTypeMapping` is specifically hard-coded for that in the test

**Comment by ranma42** [comment]
If I understood the issue, it is simply caused by the test having some strict assumptions about the provider type map.
I pushed https://github.com/dotnet/efcore/pull/34906 which should make the test use the same type mapping as `args[0]` in the `WHEN` clauses (passing `null` is not sufficient, it fails with `System.InvalidOperationException : Expression 'True' in the SQL tree does not have a type mapping assigned.`).
