### ISSUE TITLE
InvalidOperationException: More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework

### ISSUE THREAD

**Issue by blink2linkme** [dotnet/efcore#34918]
## Ask a question : InvalidOperationException: More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework.
I am trying to work with PostgreSQL Enum Data Types using Npgsql and have added the NpgsqlDataSourceBuilder to my existing code. While registering the service for the Database Context, I am encountering the following warning:

More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework.

### Include your code
Startup.cs
```
var dataSourceBuilder = new NpgsqlDataSourceBuilder();
var connectionString = configuration.GetConnectionString("NpgConnectionString");
services.AddDbContext<ApplicationDbContext>((provider, options) =>
{
    var dbCredentials = provider.GetRequiredService<HashicorpVaultService>().GetCredentials();
    dataSourceBuilder.ConnectionStringBuilder.ConnectionString = connectionString.Replace("Username", dbCredentials.Username).Replace("Password", dbCredentials.Password) ?? throw new Exception("DB Connection String Invalid");
    dataSourceBuilder.MapEnum<Status>("Status");
    var dataSource = dataSourceBuilder.Build();

    options.UseNpgsql(dataSource);
});
```
### Include Stack Trace
```
System.InvalidOperationException: 'An error was generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.ManyServiceProvidersCreatedWarning': More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling 'UseLoggerFactory' passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. This may lead to performance issues; consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built. This exception can be suppressed or logged by passing event ID 'CoreEventId.ManyServiceProvidersCreatedWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
```

### Include provider and version information
Database provider : Npgsql: 8.0.4, Npgsql.EntityFrameworkCore.PostgreSQL: 8.0.8
Target framework: (.NET 8.0)
Operating system:
IDE: (Visual Studio 2022 17.11.4)

Additional Context
I suspect that the way I am configuring the NpgsqlDataSourceBuilder might be causing multiple IServiceProvider instances to be created. How can I resolve this issue?

**Comment by roji** [comment]
By default, the options lambda passed to AddDbContext is executed for each request; this means that you're creating a data source for each incoming web request, which is very likely not what you want to do (this means that e.g. connection pooling is effectively disabled). Note also that you're never disposing all these data sources, so you're leaking database connections.

If your intent is to create a single data source for the application (which is the recommended thing), you can tell EF to have the options as a singleton as follows:

```c#
services.AddDbContext<ApplicationDbContext>((provider, options) =>
{
    // ...
}, optionsLifetime: ServiceLifetime.Singleton);
```

**Comment by ChrisJollyAU** [comment]
Also, isn't this the same as #34889

**Comment by roji** [comment]
@ChrisJollyAU yep, thanks for pointing that out - posted a comment on #34889.

**Comment by toiyabe** [comment]
This is very helpful information to know, I'm wondering if the Microsoft Docs might need to be updated so people know about the option?
Question, does the EF for SQL Server have the same issue?

**Comment by blink2linkme** [comment]
Thanks @roji & everyone. The issue is similar to #34889. 
Will the use of singleton DBContext, optionsLifetime: ServiceLifetime.Singleton, be useful in Dynamic/Rotational DB Credentials Scenario? We are using dynamic secrets which is handled by Hashicorp, so is there any other way to address this ?

**Comment by blink2linkme** [comment]
Also, will there be any concurrency issues and needs to be handled separately ?

**Comment by roji** [comment]
A single NpgsqlDataSource can rotate auth tokens/passwords ([see docs](https://www.npgsql.org/doc/security.html?tabs=tabid-1)), so that shouldn't be a problem.

**Comment by blink2linkme** [comment]
Thank you @roji

**Comment by magoogli** [comment]
Hi @roji, I have been following this issue and others relating to the 'More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework' exception, and was hoping that when I upgraded to Npgsql.EntityFrameworkCore.PostgreSQL 9 the exception would go away. I think I am doing everything as recommended ( using a single long lived NpgsqlDataSource per tenant ), but I am still getting the exception thrown.

Am I understanding your comment below correctly when I say that different instances of NpgsqlDataSource should not cause this issue?

> Most configuration options do not cause a new EF internal service provider to be created; passing an NpgsqlDataSource to UseNpgsql() does cause this currently - but in the upcoming version 9 no longer does. There are possibly a few options for SQL Server which cause this, but I don't know OTOH which they are.

Below is a unit test which reproduces the exception being thrown. Have I misunderstood something?

Thanks for an awesome library!

```csharp
public class TenantIdService
{
    public string TenantId { get; set; }
}

public class DataSourceRegistry
{
    private ConcurrentDictionary<string, NpgsqlDataSource> DataSources = new ConcurrentDictionary<string, NpgsqlDataSource>();
    public DataSourceRegistry()
    {
        for (int i = 0; i < 21; i++)
        {
            var tenantId = $"Tenant{i}";
            var x = new NpgsqlDataSourceBuilder($"Host=localhost;Database={tenantId};Include Error Detail=true;Username=admin;Password=admin");
            DataSources[tenantId] = x.Build();
        }
    }

    public NpgsqlDataSource GetDataSource(string tenantId)
    {
        if (DataSources.TryGetValue(tenantId, out var dataSource))
        {
            return dataSource;
        }
        throw new Exception("Data source not found");
    }
}

public class TestDBContext : DbContext
{
    public TestDBContext(DbContextOptions options) : base(options)
    {
    }
}

public class UnitTest1
{
    [Fact]
    public void TestMoreThan20TenantDatabasesWork()
    {
        var serviceCollection = new ServiceCollection();
        serviceCollection.AddScoped<TenantIdService>();
        serviceCollection.AddSingleton<DataSourceRegistry>(new DataSourceRegistry());

        serviceCollection.AddDbContext<TestDBContext>((sp, options) =>
        {
            var dataSourceRegistry = sp.GetRequiredService<DataSourceRegistry>();
            var tenantService = sp.GetRequiredService<TenantIdService>();
            var tenantId = tenantService.TenantId;
            var dataSource = dataSourceRegistry.GetDataSource(tenantId);
            options.UseNpgsql(dataSource);
        });

        var serviceProvider = serviceCollection.BuildServiceProvider();

        for (int i = 0; i < 21; i++)
        {
            using (var scope = serviceProvider.CreateScope())
            {
                var tenantIdService = scope.ServiceProvider.GetRequiredService<TenantIdService>();
                tenantIdService.TenantId = $"Tenant{i}";
                var db = scope.ServiceProvider.GetRequiredService<TestDBContext>();
            }
        }
    }
}

**Comment by roji** [comment]
@magoogli yeah, that's right - in EFCore.PG 9.0, you should be able to pass different NpgsqlDataSource instances to UseNpgsql() without that triggering a new EF service provider being created (and therefore the "more than 20" error).

Can you please open an issue in the EFCore.PG repo with the repro, so I can take a look?

**Comment by magoogli** [comment]
@roji Thank you for your super fast response. I have opened an issue - see [https://github.com/npgsql/efcore.pg/issues/3498](url) which includes a link to a repo which hopefully reproduces the issue your side.

Thanks again.
