### ISSUE TITLE
Efbundle.exe doesn't automatically exit

### ISSUE THREAD

**Issue by Azlon** [dotnet/efcore#34930]
# Setup

* Running .NET 8 on Windows 11 , connecting to a sqlexpress server
* Created an ef core bundle on a project with a few entities using  _dotnet ef migrations bundle_
* Runing efbundle.exe alongside an appsettingsfile.json will update the database, but won't exit. 
* Running the efbundle.exe again, informs me that _No migrations were applied. The database is already up to date._ but won't exit 
* killing efbundle.exe or ctrl c will shut down the process. 
* Running efbundle.exe --verbose does not print exceptions or other useful information

# Question

What resources could prevent the process from ending gracefully?

**Comment by AndriySvyryd** [comment]
@Azlon Can you share a small repro project that exhibits this issue?

**Comment by fuegans4213** [comment]
I have created an efbundle.exe running .NET 8 on Windows 11 and did not have any issues, 

The migration was applied and a log folder with a log file was created where you run your `.exe`

**Comment by Azlon** [comment]
Found the issue eventually. In program.cs I use a custom logger that apparently keeps the efbundle from exiting properly. 
Disabling the logger returns the efbundle to it's normal operation. 
(also, issue was not limited to efbundle, 'dotnet ef migrations bundle' or adding migrations blocked as well. Should have seen this earlier. 
Thanks anyway.
