### ISSUE TITLE
EF Core shadow properties incurs a 255 column limitation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#34931]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF-Core-shadow-properties-incurs-a-255-c/10756203)._

---
[severity:Other]
Our multi tenant web service has to support user fields in the main tables
To do so we implemented EF Core Shadow Properties
That is working well, however we recently discovered that Shadow Properties incur a limit of 255 total columns in the associated table
Is there a way to increase the support from 255 to a higher number of total columns, for instance up to 512?
We are currently in Core8, could go to Core9 if that would help

---
#### Feedback Bot on 10/3/2024, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by RedWingBB** [comment]
We chased it further and realized the problem is in the way we are handling ad hoc queries with dynamic fields
Refactored to use parametrized sql
This can be closed
