### ISSUE TITLE
EF9 Auto-compiled models EFStartupProject & multiple "startup" projects

### ISSUE THREAD

**Issue by christophwille** [dotnet/efcore#34935]
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew#msbuild-integration

What-if the EF context is used in multiple "startup" projects? Example: One API project, and one worker project. How is this to be handled properly?

**Comment by AndriySvyryd** [comment]
That page needs to be updated. We actually removed the ability to specify a startup project using this feature as it introduced build dependency cycles that were hard to diagnose and impossible to resolve in some more complex solutions.

This means that the context project needs to be autosuficient in terms of configuration, so if your app normally configures the context using a host builder you'd need to implement [IDesignTimeDbContextFactory<TContext>](https://learn.microsoft.com/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-a-design-time-factory) in the context project.
