### ISSUE TITLE
Deleted column won't go away

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#34942]
I have deleted a column from my model class, but EF Core fails to recognize that it's been deleted. I will acknowledge that I'm making many other model changes at the same time, but I don't understand what I've done to get things out of sync.

The column in question is `PdfTemplateId` in my `Company` entity.

    public class Company : ISoftDelete
    {
        public int Id { get; set; }

        [Required]
        [StringLength(120)]
        public string Name { get; set; }

        [Display(Name = "Company Code")]
        [Required]
        [StringLength(80)]
        public string CompanyCode { get; set; }

        //[Display(Name = "Default PDF Template")]
        //public int PdfTemplateId { get; set; }
        //public PdfTemplate PdfTemplate { get; set; }

        // Additional code...

    }

    public class CompanyConfiguration : IEntityTypeConfiguration<Company>
    {
        public void Configure(EntityTypeBuilder<Company> builder)
        {
            builder.HasMany(c => c.Facilities)
                .WithOne(f => f.Company)
                .OnDelete(DeleteBehavior.NoAction);
            builder.HasMany(c => c.Products)
                .WithOne(p => p.Company)
                .OnDelete(DeleteBehavior.NoAction);
            builder.HasMany(c => c.Customers)
                .WithOne(c => c.Company)
                .OnDelete(DeleteBehavior.NoAction);
        }
    }

But the property remains.

![Image](https://github.com/user-attachments/assets/b5d2aaf4-93d1-4a7a-ac30-c9b18f882483)

When I do a new `add-migration`, there are no changes. Below is part of my *ApplicationDbContextModelSnapshot*.

    modelBuilder.Entity("PegasusEntities.Models.Company", b =>
    {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

        b.Property<string>("CompanyCode")
            .IsRequired()
            .HasMaxLength(80)
            .HasColumnType("nvarchar(80)");

        b.Property<DateTime?>("DeletedOnUtc")
            .HasColumnType("datetime2");

        b.Property<bool>("IsDeleted")
            .HasColumnType("bit");

        b.Property<bool>("IsLimited")
            .ValueGeneratedOnAdd()
            .HasColumnType("bit")
            .HasDefaultValue(false);

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(120)
            .HasColumnType("nvarchar(120)");

        b.Property<int?>("PdfTemplateId")
            .HasColumnType("int");

        b.HasKey("Id");

        b.HasIndex("PdfTemplateId");

        b.ToTable("Companies", (string)null);
    });

Unfortunately, I'm really not sure how I can troubleshoot this and get things back in sync.

#### Update

Note that my `PdfTemplates` table does have a foreign key to my `Companies` table (a foreign key going the other way). So I wondered if this could be causing confusion. So I removed this and generated a new migration. In this case, it dropped the unneeded properties but then created a completely new table not in my code `CompanyPdfTemplate`. But I cannot for the life of me figure out what is causing this.

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "FK_Companies_PdfTemplates_PdfTemplateId",
            table: "Companies");

        migrationBuilder.DropForeignKey(
            name: "FK_PdfTemplates_Companies_CompanyId",
            table: "PdfTemplates");

        migrationBuilder.DropIndex(
            name: "IX_PdfTemplates_CompanyId",
            table: "PdfTemplates");

        migrationBuilder.DropIndex(
            name: "IX_Companies_PdfTemplateId",
            table: "Companies");

        migrationBuilder.DropColumn(
            name: "CompanyId",
            table: "PdfTemplates");

        migrationBuilder.DropColumn(
            name: "PdfTemplateId",
            table: "Companies");

        migrationBuilder.AlterColumn<bool>(
            name: "IsLimited",
            table: "Companies",
            type: "bit",
            nullable: false,
            oldClrType: typeof(bool),
            oldType: "bit",
            oldDefaultValue: false);

        migrationBuilder.CreateTable(
            name: "CompanyPdfTemplate",
            columns: table => new
            {
                CompaniesId = table.Column<int>(type: "int", nullable: false),
                PdfTemplatesId = table.Column<int>(type: "int", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_CompanyPdfTemplate", x => new { x.CompaniesId, x.PdfTemplatesId });
                table.ForeignKey(
                    name: "FK_CompanyPdfTemplate_Companies_CompaniesId",
                    column: x => x.CompaniesId,
                    principalTable: "Companies",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "FK_CompanyPdfTemplate_PdfTemplates_PdfTemplatesId",
                    column: x => x.PdfTemplatesId,
                    principalTable: "PdfTemplates",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_CompanyPdfTemplate_PdfTemplatesId",
            table: "CompanyPdfTemplate",
            column: "PdfTemplatesId");
    }

#### Update 2

Since the `PdfTemplates` table might seem involved, below is my definition for that table.

    /// <summary>
    /// Represents a PDF template for generating custom PDF files.
    /// </summary>
    /// <remarks>
    /// This entity could be expanded to store PDF templates for other document types
    /// in the future. Just add a new enum column to indicate the type.
    /// </remarks>
    public class PdfTemplate
    {
        /// <summary>
        /// Delimiter used to combine replacement field names in <see cref="ReplacementFields"/>.
        /// </summary>
        public const string ReplacementFieldDelimiter = "||";

        public int Id { get; set; }

        [DisplayName("Company")]
        public int? CompanyId { get; set; }
        public Company Company { get; set; }

        [Required]
        [StringLength(80)]
        public string Name { get; set; }

        [Required]
        [DataType("NVARCHAR(MAX)")]
        public string Template { get; set; }

        /// <summary>
        /// Contains the names of all replacement fields in the document.
        /// This can be used to improve efficiency of validation replacement fields.
        /// </summary>
        [StringLength(512)]
        public string ReplacementFields { get; set; }

        /// <summary>
        /// <para>
        /// Signifies this template is a default template. For example, this property
        /// is true for templates that were copied from the system defaults when a
        /// new company is created.
        /// </para>
        /// <para>
        /// Templates with this property set to true are displayed in the list of truck
        /// templates on the Edit Purchase Order page, in additional to the templates
        /// associated with purchase orders with <see cref="PurchaseOrder.IsBolTemplate"/>
        /// set to true.
        /// </para>
        /// </summary>
        [DefaultValue(false)]
        public bool IsDefault { get; set; }

        /// <summary>
        /// Signifies this template is for trucks that arrive loaded (inbound loaded).
        /// If false, this template is for trucks that arrive empty (outbound loaded).
        /// </summary>
        [DefaultValue(false)]
        public bool IsInboundLoaded { get; set; }

        public ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public ICollection<PdfTemplateField> PdfTemplateFields { get; set; }
        public ICollection<Company> Companies { get; set; }
    }

    public class PdfTemplateConfiguration : IEntityTypeConfiguration<PdfTemplate>
    {
        public void Configure(EntityTypeBuilder<PdfTemplate> builder)
        {
            builder.HasOne(t => t.Company)
                .WithMany(c => c.PdfTemplates)
                .OnDelete(DeleteBehavior.NoAction);

            // Deleting PdfTemplate does not delete PurchaseOrder
            builder.HasMany(t => t.PurchaseOrders)
                .WithOne(o => o.PdfTemplate)
                .OnDelete(DeleteBehavior.NoAction);

            // Deleting PdfTemplates does deletes PdfTemplateFields
            builder.HasMany(t => t.PdfTemplateFields)
                .WithOne(f => f.PdfTemplate)
                .OnDelete(DeleteBehavior.Cascade);
        }
    }

EF Core version: 8.08
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.5

**Comment by SoftCircuits** [comment]
I tried uncommenting the deleted column, adding a migration, then deleting it again and adding another migration.

Unfortunately, I do not get a `DropColumn` in the second migration. I get the following migration instead.

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "FK_Companies_PdfTemplates_PdfTemplateId",
            table: "Companies");

        migrationBuilder.AlterColumn<int>(
            name: "PdfTemplateId",
            table: "Companies",
            type: "int",
            nullable: true,
            oldClrType: typeof(int),
            oldType: "int");

        migrationBuilder.AddForeignKey(
            name: "FK_Companies_PdfTemplates_PdfTemplateId",
            table: "Companies",
            column: "PdfTemplateId",
            principalTable: "PdfTemplates",
            principalColumn: "Id");
    }

**Comment by cincuranet** [comment]
I guess the column is introduced because it is part of association. 

Otherwise this issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by SoftCircuits** [comment]
@cincuranet That is literally impossible. I have never seen this issue before--EF Core usually just works. So how would I reproduce the exact same sequence of changes that caused EF Core to get confused?

What would be tremendously helpful are some suggestions on what to in order to troubleshoot this and get things back in sync.

**Comment by ErikEJ** [comment]
Have a look a the DebugView to understand how EF Core interprets your model...

**Comment by SoftCircuits** [comment]
@ErikEJ Could you elaborate on that a little more? What sort of things would I be looking at in my model class? Given that these classes have little to no code, I would think they are very straight forward. Or is there something else I'd be looking at?

**Comment by SoftCircuits** [comment]
I also tried adding a new column with the same name and a different type.

     public DateTime PdfTemplateId { get; set; }

Here is the output:

    Build started...
    Build succeeded.
    Microsoft.EntityFrameworkCore.Model.Validation[10625]
    The foreign key property 'Company.PdfTemplateId1' was created in shadow state because a conflicting property with the simple name 'PdfTemplateId' exists in the entity type, but is either not mapped, is already used for another relationship, or is incompatible with the associated primary key type. See https://aka.ms/efcore-relationships for information on mapping relationships in EF Core.
    Microsoft.EntityFrameworkCore.Model.Validation[10625]
    The foreign key property 'Company.PdfTemplateId1' was created in shadow state because a conflicting property with the simple name 'PdfTemplateId' exists in the entity type, but is either not mapped, is already used for another relationship, or is incompatible with the associated primary key type. See https://aka.ms/efcore-relationships for information on mapping relationships in EF Core.

And here is the migration.

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "FK_Companies_PdfTemplates_PdfTemplateId",
            table: "Companies");

        migrationBuilder.DropIndex(
            name: "IX_Companies_PdfTemplateId",
            table: "Companies");

        migrationBuilder.AlterColumn<DateTime>(
            name: "PdfTemplateId",
            table: "Companies",
            type: "datetime2",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
            oldClrType: typeof(int),
            oldType: "int",
            oldNullable: true);

        migrationBuilder.AlterColumn<bool>(
            name: "IsLimited",
            table: "Companies",
            type: "bit",
            nullable: false,
            oldClrType: typeof(bool),
            oldType: "bit",
            oldDefaultValue: false);

        migrationBuilder.AddColumn<int>(
            name: "PdfTemplateId1",
            table: "Companies",
            type: "int",
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "IX_Companies_PdfTemplateId1",
            table: "Companies",
            column: "PdfTemplateId1");

        migrationBuilder.AddForeignKey(
            name: "FK_Companies_PdfTemplates_PdfTemplateId1",
            table: "Companies",
            column: "PdfTemplateId1",
            principalTable: "PdfTemplates",
            principalColumn: "Id");
    }

Clearly, I still have some shadow properties going on here.

**Comment by ErikEJ** [comment]
A DebugView is a textual representation of your model. You can get it in code and save it.

**Comment by SoftCircuits** [comment]
@cincuranet If you can't offer any suggestions at all, can you tell me what you would need in a small project?

Right now, my entities are in a separate project, but it relies on my main app for database configuration.

Thos would take me hours, and I worry the work will fix the problem. Could you give me an idea what would be needed?
