### ISSUE TITLE
Cascading saving Nth level changing child

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/efcore#34941]
I have a persistent class mapping in which one of the instances is recently added to its parent-child collection. My _File > Save_ operation starts from the top most instance in the hierarchy, whereas the child in question is below separated by perhaps 2-3 parent-children relationships.

I am seeing in the (postgres) logs, the top level instance is evaluating itself for changing, appropriately so, but finds none, so no further action occurs. Children are not being evaluated down the hierarchy as well, which brings my to my overall question.

```csharp
private void OnSave()
{
    var repository = Services.GetService<IRepository>();
    repository.Save(Target); // Target being the top level instance.
}
```

Does not matter what `Target` is for sake of discussion, just that it is the top level object being mapped into persistence.

And which `Save` basically does some work to either `Add` or `Update` in terms of database persistence conditions.

Neither here nor there, `Mutate` maybe not the best name, named as such for purposes of wrapping the whole affair in a database transaction. i.e. mutating the database state.

```csharp
public static IReadOnlyCollection<T> Save<T>(this IRepository repository, params T[] entities)
    where T : class, IModel
{
    static void OnMutateSaveOrUpdate(DbSet<T> set, T entity)
    {
        // TODO: may need more of a check i.e. on the set, but for now 'ispersistent' will work...
        if (entity.IsPersistent)
        {
            set.Update(entity);
        }
        else
        {
            set.Add(entity);
        }
    }

    return repository.Mutate(OnMutateSaveOrUpdate, entities);
}
```

Anyway... long story short, I do not think my question is to do with the repository pattern, saving, updating, or mutating. But rather, do I need to navigate the parent-children, and _'save'_ each of the children throughout the navigation? Especially in cases where we have a new Nth level child being introduced.

Unless there is perhaps an easier way to comprehend the parent-children, perhaps a _cascading save or update_ feature.

**Comment by mwpowellhtx** [comment]
What I could come up with is something like this, along these lines, which seems to do the trick... BUT... I wonder if there is a cascading option I can provide my context, options, or what have  you.

```csharp
var repository = Services.GetService<IRepository>();

void Save<T>(params T[] entities)
    where T : class, IModel
    => repository.Save(entities);

Save(Target);

Save([.. Target.Servers]);

foreach (var server in Target.Servers)
{
    Save(server.EventManager);

    Save([.. server.EventManager.Meets]);

    foreach (var meet in server.EventManager.Meets)
    {
        Save([.. meet.Lanes]);
    }
}
```

**Comment by cincuranet** [comment]
As long as the entities have proper associations between each other (references/collections), EF will traverse and save those automatically.

Otherwise this issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by mwpowellhtx** [comment]
@cincuranet 

> Otherwise this issue is lacking enough information for us to be able to fully understand what is happening.

The save, or in this case update, halts at the top most instance (_User Profile_)., where as the changes that need to apply, either added or updated, are deep in the _Lanes_ (above). Note, the instances are effectively disconnected from a prior repository context (internally `DbSet<T>`); necessarily so because they subsequently inform WPF _view model target instances_, i.e.

```
class ViewModel<T>
    where T : class, IModel
{
    public virtual T Target { get; set; }
}
```

Which to me somewaht stands to reason.

So the question is, how to force a cascading add or update, other than having to navigate the hierarchy manually as I have done. Or maybe that is the only recourse.

**Comment by cincuranet** [comment]
If you are working in disconnected scenario, you might want to check [`TrackGraph` method](https://learn.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#custom-tracking-with-trackgraph) and handle the callbacks accordingly. But again, without a specific code that shows the unexpected behavior, it is difficult to provide any answers.

**Comment by mwpowellhtx** [comment]
Fair enough, thanks. I will check that out.
