### ISSUE TITLE
System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data.

### ISSUE THREAD

**Issue by aleksvujic** [dotnet/efcore#34960]
### Bug description

We are using .NET 8, [Microsoft.EntityFrameworkCore.Design 8.0.4](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/8.0.4) and [Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/8.0.4). Our database is PostgreSQL 10.23.

We have a simple PostgreSQL table which was created and populated using the following SQL query:

```sql
CREATE TABLE fit3.product (
    id serial4 NOT NULL,
    config jsonb,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
INSERT INTO fit3.product(config) VALUES (null);
INSERT INTO fit3.product(config) VALUES ('null');
INSERT INTO fit3.product(config) VALUES ('{"CPU": "ARM"}');
```

We are using database-first approach - we scaffolded the database to obtain the following C# model:

```cs
[Table("product", Schema = "fit3")]
public partial class Product
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("config", TypeName = "jsonb")]
    public string? Config { get; set; }
}
```

We also defined the following 2 classes which represent JSON for the configuration:

```cs
public partial class Product
{
    public Config? ConfigJSON { get; set; }
}

public class Config
{
    public string? CPU { get; set; }
}
```

We performed the mapping from jsonb column to our `Config` C# class inside `OnModelCreatingPartial`:

```cs
partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Product>(entity =>
    {
        entity.OwnsOne(x => x.ConfigJSON, t =>
        {
            t.ToJson("config");
        });
    });
}
```

However, when we perform the following simple query ...

```cs
var products = _fitDBContext.Products.ToList();
```

... the following exception is thrown:

```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.NetworkInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Model.Validation: Warning: Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT p.id, p.config, p.config
FROM fit3.product AS p
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'FitView.Data.Fit.Models.FitDBContext'.
System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at lambda_method89(Closure, QueryContext, Object[], JsonReaderData)
   at lambda_method88(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()

System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at lambda_method89(Closure, QueryContext, Object[], JsonReaderData)
   at lambda_method88(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Exception thrown: 'System.Text.Json.JsonReaderException' in Microsoft.EntityFrameworkCore.Relational.dll
```

### Provider and version information

EF Core version: 8.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4
Target framework: .NET 8
Operating system: Windows 11 x64
IDE: Visual Studio Professional 64-bit 17.11.5

**Comment by maumar** [comment]
Same thing happens on SQL server as well. Problem is with 

```SQL
INSERT INTO fit3.product(config) VALUES ('null');
```

Given that owned entity should be stored there, we expect either a JSON object or null value.

**Comment by roji** [comment]
@maumar isn't `null` is valid JSON (just like the null in `{ "a" : null }`? I guess this means that we don't support the top-level owned JSON entity itself being optional - as opposed to owned JSON entities nested within other owned JSON entities (where we do support this?). I'm not sure if this is already tracked somewhere.

Note that it's technically possible to also have something like `[1, 2, 3]`, or even `3` or `true`. These would be perfectly valid JSON, but of course would be invalid for EF in a place where we expect an owned entity (in that context, only a JSON object or null are valid). This again is the same regardless of whether the invalid value appears at the top-level JSON entity, or nested (e.g. `{ "a": 8 }` where `a` is modeled in EF to be an owned entity).

**Comment by aleksvujic** [comment]
Exactly what @roji said - there are 2 ways to represent null values (relational NULL and JSON null).

Is the behavior that I described a bug in EF Core? Are there any workarounds so that we are still able to query the data without any exceptions being thrown?

**Comment by maumar** [comment]
Yeah, you are right @roji @aleksvujic "null" does render as `JsonTokenType.Null` but we don't have any special processing for it when including json entity.

wrt workaround, projecting JSON entity works just fine (method for materializing Json entity on top level contains the logic that checks for null value), so you could project all the properties of `Product` separately and then stitch them into an entity on the client. But that loses you tracking, so the workaround is not great.

```cs
        var projection = await ctx.Products.AsNoTracking().Select(x => new { x.Id, x.ConfigJSON }).ToListAsync();
        var products = projection.Select(x => new Product { Id = x.Id, ConfigJSON = x.ConfigJSON }).ToList();
```

**Comment by aleksvujic** [comment]
@maumar Thank you for the workaround idea, but projecting all the fields in a class with 30+ properties (database columns) and then mapping them back to the original type can become very unmaintainable and tedious. If there are no other options, we will wait for an official fix.
