### ISSUE TITLE
Analyser issue with FindAsync

### ISSUE THREAD

**Issue by scott-david-walker** [dotnet/efcore#34966]
I'm not sure if this belongs here or in Roslyn.

Using the `FindAsync` DbSet method allows a cancellation token to be passed as a part of the params arguments [See Issue](https://github.com/dotnet/efcore/issues/22667).

However, when using this approach, both my IDE and Sonar give a warning that I'm not passing my cancellation token

![Image](https://github.com/user-attachments/assets/ac722243-bf32-42f6-9feb-7cfd048b2d46)

EF Core version: 8.0.10
Database provider: (e.g.NpgSql.EntityFrameworkCore.PostgresSQL)
Target framework: (e.g. .NET 8.0)
Operating system: Linux Mint 21.3 Cinnamon
IDE: Rider 2024,2,6

**Comment by cincuranet** [comment]
I think this is more of a Roslyn side, because we don't provide such analyzer ourselves. But I can't replicate it. Here's my test code, can you modify it to make it show the warning?

```csharp
using Microsoft.EntityFrameworkCore;

using var cts = new CancellationTokenSource();
using var context = new MyContext();
var foo = await context.Foos.FindAsync([1], cts.Token);

class MyContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }

    override protected void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite();
    }
}

class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

**Comment by roji** [comment]
Probably related to #22667 (but we still need a repro)

**Comment by stevendarby** [comment]
Remove square brackets around 1

**Comment by maumar** [comment]
with square brackets removed, compiler prefers the 

```cs
public virtual ValueTask<TEntity?> FindAsync(params object?[]? keyValues)
```

method, although no analyzer warning on my box (visual studio)


![Image](https://github.com/user-attachments/assets/fbe8293d-378e-49ec-9032-d6ae0173eb24)


Looks like we encountered this issue before, as the method taking object array has logic extracting cancellation token from the object array: `ValidateKeyPropertiesAndExtractCancellationToken`

**Comment by alainkaiser** [comment]
Same issue on my end working with Rider (if this matters).

How I did it:
![Image](https://github.com/user-attachments/assets/ae4a1cb1-b455-410e-ae54-890b32a751fb)

This way, you get a "Warning" that you should pass a Cancellation Token:
![Image](https://github.com/user-attachments/assets/f3e3c8e9-7651-43ee-ba6e-447bb23ba1f6)

I can resolve it when doing it like this:
![Image](https://github.com/user-attachments/assets/141bfb3e-164d-4c74-9f3a-b1e2f4192f41)

What I am asking myself: What is the current recommendation?

**Comment by cincuranet** [comment]
C# compiler has its rules for selecting overload and we cannot enforce one overload over the other from EF's side. For me, using collection expressions here (aka `[` and `]`) seems to be a good fit and still nicely readable code.
