### ISSUE TITLE
Improve test coverage for Remove and SaveChanges

### ISSUE THREAD

**Issue by mikary** [dotnet/efcore#3496]
There have been a number of issues(#1111, #1371, #2890) relating to removing entities from the context and saving changes. While there is fairly extensive coverage for `DbSet<T>.Add`, (Explicitly and through test model seeding) the coverage for `DbSet<T>.Remove` is relatively low.

Investigations have been showing these issues being resolved as a side effect of other changes/fixes, but we should avoid regressions in this area by adding tests to cover removing from models with various shapes and relationships, i.e. the Gears Of War model.

**Comment by ajcvickers** [comment]
Have you looked at GraphUpdatesTest? That's where most of the coverage for removing entities is. It would be useful to know which scenarios are missing from here.

**Comment by rowanmiller** [comment]
Waiting to triage until question from @ajcvickers is answered.

**Comment by mikary** [comment]
I missed the GraphUpdateTest tests when I was initially investigating, but it looks like these tests provide appropriate coverage. The history indicates that many of the Remove tests were added between beta7 and beta8, and it's likely the related changes resolved #2890.
