### ISSUE TITLE
Temporary primary keys and actual primary keys cannot be the same

### ISSUE THREAD

**Issue by JanCotar** [dotnet/efcore#34989]
# The Problem

If a newly attached entity does not have a primary key (PK) already set, Entity Framework (EF) assigns it a temporary PK. For example, if a PK is of type `Int16`, it will be assigned a temporary PK with the value `Int16.MinValue`. The next such entity will have `Int16.MinValue + 1` up to `Int16.MaxValue`, and then it overflows back to negative. There is a counter that holds and provides this value. However, the counter is static and applies to all entities of the same type, regardless of the context. So, after the context is disposed, the counter resumes where it left off for the next context. It can only be safely reset by restarting the service.

The problem arises when the counter reaches positive numbers (as PKs are usually set to start with positive values in a database). Now, a new entity gets a positive temporary PK, and if an entity already committed in the database is attached to the same context, its actual PK and the temporary PK of the other entity cannot be the same.

I understand that this counter has to be static as multiple contexts can share the same entity, ensuring the uniqueness of the entity. However, it fails to differentiate between actual PKs and temporary ones, partly defeating the purpose.

I stumbled upon this while playing with EF and trying to understand its inner workings more closely. I don’t believe it’s a big problem as not much about it can be found online, but I still think it should be paid some attention.

# Solution

Simple: Make the counter only negative. However, if the database is set to have negative PKs, then this solution does not actually change anything.
Proper: Entity Framework (EF) should differentiate between temporary and actual PKs.

EF Version: 7.0.9
OS: Docker
IDE: VS 2022 17.6.5

Regards

**Comment by ilmax** [comment]
Off topic: It's nice to see you back @ajcvickers
