### ISSUE TITLE
FromSql(): Allow SqlCommand-like type as an overloaded method parameter

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/efcore#34990]
Guard the FromSql() method from improperly crafted raw SQL statements from string literals.

Define FromSql() with an overload that accepts an object of the SqlCommand-like type as its parameter, to protect against improperly crafted raw SQL statements from string literals. The EF query processor can deduce the actual SQL string that is to be executed.

**Comment by egvijayanand** [comment]
This will be quite like this.
```cs
// EfCommand is a lite version of SqlCommand.
// The properties from SqlCommand pertinent to the EF Core context should be supported here.
var command = new EfCommand();
command.CommandText = "GetMostPopularBlogsForUser"; // SP name
command.CommandType = CommandType.StoredProcedure;
command.Parameters.AddWithValue("user", "johndoe"); // In case of multiple parameters, it can be defined in any order

// FromSql() method should be overloaded to take a parameter of the type EFCommand
//  EFCore query processor should deduce and execute the query from the command object instance.
// By doing this way, it's safe from SQL Injection attacks and easy to maintain as it's object-based instead of disconnected string literals.
var blogs = context.Blogs
    .FromSql(command) // Pass the command object here
    .ToList();
```

**Comment by roji** [comment]
FromSql is already safe from SQL injection attacks, since it accepts a FormattableString and not a regular string; [see the docs](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries?tabs=sqlserver#passing-parameters).
