### ISSUE TITLE
New Provider: Appropriate mechanism for injecting query hints

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#35009]
I'm continuing work on a provider for a proprietary database engine. Things have been working and am able to run most of microsoft tests. Recently I was made aware of a need in certain situations to provide a query hint. 

The hint for the query would be in the form of a comment to ultimately be rendered directly after the select clause like so:
```
select /* some hint */ col1, col2, col3 from  table
```

To support this, I was initially thinking of overriding `VisitSelect` in the `QuerySQLGenerator` where I can easily detect the specific condition, and it seems like I should be able to call `_relationalCommandBuilder.Append(<hint>)` directly after appending `SELECT `.

The problem I'm running into is that in order to override `VisitSelect` I essentially have to reproduce how the base `QuerySQLGenerator` initializes the relational command builder (as its private and not protected) (essentially copying `GetCommand` and `VisitSelect` except incorporating that minor change. When I've attempted to do this, it seem like it tends to break other methods in the `QuerySqlGenerator`, like its interfering with `_relationalCommandBuilder` that other methods in the base QuerySqlGenerator that aren't overridden

I'm now wondering if there is a place to simply manipulate the SQL itself just before execution, or if anyone has ideas about a simpler way to inject that hint directly after using the builder to append the "SELECT ".

I could almost see the need for specialized `SelectExpression` that had a concept of hint, that I could populate prior, and then visit select would simply just check additional property for whether it had a hint, and render that.

So I guess the question is....

Does EFCORE already have some mechanism to provide arbitrary text to be rendered at a certain point, an easy way to transform SQL, or does it seem to make sense to do this in a `QuerySQLGenerator` subclass in the `VisitSelect` method? If there is a better way, I'm interested to hear other ideas about how to support this.

Also, as a side question, is there documentation on the internals and architecture of efcore... even just the sequence things run in (from linq, to expression tree, to transformers, to generators etc)? I'd love to look at diagrams or documentation, and think that it may help reduce number of questions I come here with.

EF Core version:
Database provider: custom provider in development
Target framework: e.g. .NET 6.0
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by ChrisJollyAU** [comment]
To me the QuerySqlGenerator sounds like the best place to do this. Anything after and you would just have the sql string without any expression tree.

With regards to overriding the `VisitSelect` that should be relatively easy. While it's true you don't have access to `_relationalCommandBuilder` you can just replace that with `Sql` which a property that you can use to access the private `_relationalCommandBuilder`. In fact if you look at other providers (Sql Server and Sqlite just to name 2) you will see that they also use `Sql` to add to the generated sql

In fact, I've done the same thing with EFCore.Jet - completely override the `VisitSelect`. Have a look at https://github.com/ChrisJollyAU/EntityFrameworkCore.Jet/blob/1de9eb43829fb236a10d473e3e0075656bdf0e7b/src/EFCore.Jet/Query/Sql/Internal/JetQuerySqlGenerator.cs#L78. Naturally yours would be a bit different as I've had to handle some MS Access specific stuff there as well.

As to your question about documentation, I don't believe there is any like what you are asking for.  Would have probably saved me some time as well.

**Comment by ronnyek** [comment]
You know what, I'm dumb =), its been a while since I've been working in this provider, and just realized I'm already using sql object to append sql all over the place in my custom QuerySqlGenerator already... no idea why I didn't recognize that. 

Appreciate it =)
