### ISSUE TITLE
Removing HierarchyId with existing migrations breaks compilation

### ISSUE THREAD

**Issue by LadislavBohm** [dotnet/efcore#35022]
## File a bug

If you have a project and add an entity that contains HierarchyId column and create a migration then the migration contains static type reference to HierarchyId type. Later if you decide that you no longer want to use HierarchyId and remove it from entity and also remove reference to HierarchyId package then compilation does not work for existing migrations because they can no longer find HierarchyId type.

### Include your code

Here is my migration that got created automatically after I added HierarchyId to my entity

```C#

using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.SqlServer.Types; //THIS IS PROBLEM LINE

#nullable disable

namespace Application.Migrations
{
    /// <inheritdoc />
    public partial class AddHierarchyIdToMilestone : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "HierarchyLevel",
                table: "MilestoneTemplates");

            migrationBuilder.AddColumn<SqlHierarchyId>( //THIS IS PROBLEM LINE
                name: "HierarchyPath",
                table: "MilestoneTemplates",
                type: "hierarchyid",
                nullable: false,
                defaultValue: Microsoft.SqlServer.Types.SqlHierarchyId.GetRoot()); //THIS IS PROBLEM LINE
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "HierarchyPath",
                table: "MilestoneTemplates");

            migrationBuilder.AddColumn<int>(
                name: "HierarchyLevel",
                table: "MilestoneTemplates",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}


```

When you remove the column and reference to package:

      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.HierarchyId" Version="8.0.8" />

You code no longer works and you have to either keep the package or manually edit the migrations in some way.
I marked lines that statically reference the package with comments.

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system: Windows
IDE: Rider

**Comment by maumar** [comment]
same thing goes for spatial properties using NetTopologySuite. This problem will be solved by migration squashing (https://github.com/dotnet/efcore/issues/2174) - for now you need to manually modify the migrations or do the squashing "by hand" before removing the package reference.
