### ISSUE TITLE
Should I use required modifier with navigations?

### ISSUE THREAD

**Issue by oasaleh** [dotnet/efcore#35031]
It's not very clear in the docs whether I should use `required` with navigations or not. 
Please note that NRT is enabled.
```csharp
// Principal (parent)
public class Blog
{
    public int Id { get; set; }
    public BlogHeader? Header { get; set; } // Reference navigation to dependent
}

// Dependent (child)
public class BlogHeader
{
    public int Id { get; set; }
    public required int BlogId { get; set; }
    public required Blog Blog { get; set; }
}
```

Would that require me to include `Blog` and `BlogId` in the header when saving it to the DB? 
What about the one-to-many relationship? Should I use `required` on the dependent like so?

```csharp
// Principal (parent)
public class Blog
{
    public int Id { get; set; }
    public ICollection<Post> Posts { get; } = new List<Post>(); // Collection navigation containing dependents
}

// Dependent (child)
public class Post
{
    public int Id { get; set; }
    public required int BlogId { get; set; }
    public required Blog Blog { get; set; }
}
```
Finally, just as a confirmation, it doesn't make sense for me to use `required` with a nullable property, correct?

Thanks!

**Comment by roji** [comment]
EF itself doesn't care about `required` - it only looks at the nullable annotation on the property to determine whether a value must be provided or not. `required` only has an effect on the C# compiler (not EF), with the the effect of forcing initialization of the property when you instantiate the type in C#, and thereby removing the need to have it initialized in the constructor (or via an initializer on the property). So yeah, it can be a good fit with required (non-nullable) properties, where the user is forced to initialize them to some non-null value.

> Finally, just as a confirmation, it doesn't make sense for me to use required with a nullable property, correct?

Right, in general that isn't very useful - unless you want to force callers to explicitly initialize the property. Again, EF doesn't care about `required` in any way.

**Comment by oasaleh** [comment]
@roji, thank you for your reply and clarification. Would you say using `required` is safer/better than using `null!`?

**Comment by roji** [comment]
If it's acceptable to force all instantiation sites to explicitly initialize the property in question, then yes.

**Comment by ChrisJollyAU** [comment]
> If it's acceptable to force all instantiation sites to explicitly initialize the property in question, then yes.

But don't forget, `required` can be initialized to `null`. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required
