### ISSUE TITLE
Unable to create a migration for OracleDB

### ISSUE THREAD

**Issue by adam440** [dotnet/efcore#35030]
Hello,
I've found a bug while trying to create a migration for OracleDB using the newest version of EFCore available on NuGet (9.0.0-rc.2.24474.1). When I try to create a migration using the following command:

```
"C:\Program Files\dotnet\dotnet.exe" ef migrations add --project MigrationsTestInConsole\MigrationsTestInConsole.csproj --startup-project MigrationsTestInConsole\MigrationsTestInConsole.csproj --context OracleBlog.Program+BloggingContext --configuration Debug --verbose init --output-dir Migrations
```

I get the following error:

```
Unable to create a 'DbContext' of type 'BloggingContext'. The exception 'Method 'get_LockReleaseBehavior' in type 'Oracle.EntityFrameworkCore.Migrations.Internal.OracleHistoryRepos
itory' from assembly 'Oracle.EntityFrameworkCore, Version=8.0.23.1, Culture=neutral, PublicKeyToken=89b483f429c47342' does not have an implementation.' was thrown while attempting
to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

I tried to downgrade Oracle.EntityFrameworkCore library, but to no avail. Only after I changed the version of Microsoft.EntityframeworkCore to 8.0.10 was I able to proceed with the migration (note, that I haven't tried other 9.x versions of EFCore). Since it's the Microsoft library, that is breaking the program, I am posting it here and not on Oracle forums. In the attachment, you'll find an example code with a minimal setup (taken from example project from Oracle) that should get you the same error.

For reference, I'm on Windows 11 Pro 23H2 (build 22631.4317) using JetBrains Rider 2027.2.7 (build #RD-242.23726.100).

Feel free to ask me any questions regarding the reproduction of the bug.

Attached project:
[MigrationsTestInConsole.zip](https://github.com/user-attachments/files/17602073/MigrationsTestInConsole.zip)

**Comment by ChrisJollyAU** [comment]
Hi

With EFCore, both EFCore itself and the respective provider (Oracle in your case) need to match each other.

In your case you are using a EF Core 9 build for Microsoft.EntityFrameworkCore (`9.0.0-rc.2.24474.1`) but your version for `Oracle.EntityFrameworkCore` is `8.23.60`. This is clearly a version that matches against EF Core 8.

The method `get_LockReleaseBehavior` is part of a new feature in EF Core 9 and as such any provider targeting a lower version of EF Core will not have it and yu will get the above error.

I've just looked at nuget and it doesn't appear to be anything for EF Core 9 yet (not even a preview)

Downgrading back to EF Core 8 (which will match what Oracle is targeting) will solve the problem.
If you want to use EF Core 9, you will need to wait until Oracle release a new version compatible with EF Core 9.
