### ISSUE TITLE
Nullable foreign key generates not nullable column on postgres

### ISSUE THREAD

**Issue by rmsilva1973** [dotnet/efcore#35039]
The code below should allow column AppUserId for table Race to be nullabe. However the generated table has "NOT NULL" on AppUserId column.

```c#
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using RunGroopWebApp.Data.Enum;

namespace RunGroopWebApp.Models
{
    public class Race
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
        public RaceCategory RaceCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }

    }
}
```

dotnet version: 6.0.427
dotnet-ef: 6.0.35
postgres: 17.0

**Comment by roji** [comment]
Originally opened as https://github.com/npgsql/efcore.pg/issues/3344

**Comment by AndriySvyryd** [comment]
Does this still happen with EF 8 or 9?

**Comment by rmsilva1973** [comment]
@AndriySvyryd just tested here. With EF 8.0.10 it doesn't happen.

**Comment by rmsilva1973** [comment]
@AndriySvyryd If I propose a PR to fix this in version 6, is there a possibility that it will be merged?

**Comment by AndriySvyryd** [comment]
@rmsilva1973 No, EF Core 6 goes out of support in a couple of days, so there are no more releases planned for it.
