### ISSUE TITLE
Source Generators

### ISSUE THREAD

**Issue by cliedeman** [dotnet/efcore#35057]
## Ask a question

I am looking for any existing samples on integrating EfCore with source generators. 

https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md

Goal:
Generate graphql data loaders that take advantage of the information embedded in the app db context snapshot. 

I have looked through the ef core commands and did not find anything. I also resorted to parsing the db context snapshot syntax tree but I hope there is an easier way

Another idea is an intermediary step that generates a json version of the snapshot that can be consumed by the generator

**Comment by roji** [comment]
What sort of information do you need exactly for your GraphQL data loader? A source generator only knows about the C# code syntax/semantics, and does not have access to the full EF model which gets calculated behind the scene (e.g. the various ways that a property is configured). To get the full model, you need to write a .NET program (not a source generator) that would get the EF model from your DbContext, and then generate whatever C# code you want based on that.

More information on exactly what you're trying to achieve and what exact information you need would help understand you need better here.

**Comment by cliedeman** [comment]
Hi @roji 

I would only need the type of the Key and then the foreign key/navigation information. Which are both available.

```csharp
modelBuilder.Entity("Example.Child", b =>
    b.HasKey("Id");
    ...
    b.HasOne("Example.Parent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .IsRequired();
   ...
   });
```

This is the method I would like to eliminate/generate

```csharp
[Node]
[ExtendObjectType<Child>]
public class ChildExtensions
{
   ...
    public Task<Barcode> GetParent(
        IParentByIdDataLoader loader,
        [ID(nameof(Parent))] int id)
    {
        return loader.LoadAsync(id);
    }
   ...
}
```

**Comment by cliedeman** [comment]
Thanks for the detailed reply @roji 

I have used the context model in a another use case: Automatically removing all the foreign key fields from the graphql schema. Which is an ideal use case, mostly because its all done at runtime.

I think I will settle on a middleground approach where I generate an intermediary json file contaning details about the model and then feed that into a source generator. The developer experience with source generation is just too good to pass up.

**Comment by roji** [comment]
> The developer experience with source generation is just too good to pass up.

Sure, though source generators really are powerful when stuff gets generated as a result of code changes, i.e. you edit your code and some other code gets generated live as a result. But here, the (latest) context snapshot only changes when you generate a new migration, which is a very explicit, external action; so I think the value really isn't that great (how hard is it to just run another command to generate the loaders after running the command to generate the migration...).

But in any case, I agree that having the source generator use a JSON that's programmatically generated from EF's model is a much better approach than trying to actually parse the snapshot's C# code directly via the source generator.
