### ISSUE TITLE
How can I update a Many to Many with Payload joining table

### ISSUE THREAD

**Issue by Gregory-Lange** [dotnet/efcore#35064]
Here is my situation:

I have two tables one being a User and another being Location.  In my configuration I am using the whole withmany/hasmany/usingentity but I had to add an item to the join table that would be should it be excluded when searching.  I setup the default value but if I want to update it I am not sure how I would do that.

```c#
public class User
{
    public Guid Id {get;set;}
    public string FullName {get; set;}
    public virtual ICollection<Location> Locations {get;set;}
}

public class Location
{
   public Guid Id {get;set;}
   public string LocationName {get;set;}
   public virtual ICollection<User> Users {get;set;}
}

public class UserLocation
{
   public Guid LocationId {get;set;}
   public Guid UserId {get;set;}
   public bool IsExcluded {get;set;}
   public virtual Location Location {get;set;}
   public virtual User User {get;set;}
}
```

in configuration file UserConfiguration.cs
```c#
public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        // base configuration items

        _ = builder.HasMany(m => m.Locations)
           .WithMany(m => m.Users)
           .UsingEntity<Entity.UserLocation>("UserLocations",
              r => r.HasOne(ul => ul.Location).WithMany().HasForeignKey(ul => ul.LocationId).HasPrincipalKey(l => l.Id),
              l => r.HasOne(ul => ul.User).WithMany().HasForeignKey(ul => ul.UserId).HasPrincipalKey(u => u.Id),
              j => {
                   j.HasKey(ul => new {ul.UserId, ul.LocationId});
                   j.Property(p => p.IsExcluded).HasDefaultValueSql("0");
              }
    }
}
```

I do not have the UserLocaiton as a DBSet item in my context due to its only used for joining and the whole UsingEntity created it and allows for a clean setup for if I add or remove items from a user.  But now I do not know how to edit the joining table to change the whole IsExcluded from false to true.  Any help would be gratefully appreciated.

How i add things to a user:

```c#
//pull location from database
Location location = _Context.Locations.Where(w => w.Id == PassedInId).FirstOrDefault();

//add location to user
_Context.Users.Locaitons.Add(location);

//save changes
_Context.SaveChanges();
```

This will auto add the data required to the join table without having to touch it, but like what I was getting at if I want to keep that there because I need to but do not want him to show up on a dropdown how do I update the joining tables payload of IsExcluded to be true instead of false.

**Comment by roji** [comment]
> I do not have the UserLocaiton as a DBSet item in my context due to its only used for joining and the whole UsingEntity created it and allows for a clean setup for if I add or remove items from a user.

Having UserLocation as a join entity - and specifying it via UsingEntity - does not exclude you from also having a DbSet, allowing you to query and modify it directly; you can do that to modify the payload (IsExcluded) on your UserLocation.

As an alternative, you can add navigation properties from your User and Location entity types to the UserLocation - in addition to the direct (skip) navigations between User and Location to each other; [see this section in the docs](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-with-navigations-to-join-entity) for an example. This can allow you to load e.g. a User and its Locations, and then to update the payload on the UserLocations you wish.
