### ISSUE TITLE
Does a release version (e.g. 8.0.10) require the same .NET runtime version?

### ISSUE THREAD

**Issue by HugCoder** [dotnet/efcore#35063]
## Question: If I upgrade e.g. Microsoft.EntityFrameworkCore.SqlServer to 8.0.10, will I also need the same runtime version .NET 8.0.10 on the server I publish to?
This might be a more general question about versioning in .NET and Microsofts packages relating to it overall, but I tried to search for the answer to this but cannot narrow it down. Since my server host/provider often might be a few 0.0.x version behind, it's quite relevant if I can upgrade to latest dependencies and still have it run or not.

Is there perhaps even some tool or dotnet command one can run to determine which .NET Runtime is required to run an app?

**Comment by roji** [comment]
@HugCoder you can check out which target framework (TFM) is supported by a given Nuget package; the [frameworks tab](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer#supportedframeworks-body-tab) on nuget.org shows you exactly which version of .NET is supported.

**Comment by HugCoder** [comment]
I did check the tab and it only says "net8.0", nothing about subversions, like 8.0.8 or 8.0.10. But perhaps you mean that as long as I target net8.0 on publish and on project, it will compile to run even if the server only has e.g. 8.0.1 runtime installed?

**Comment by roji** [comment]
Yes. Patch versions (8.0.0 vs. 8.0.1) don't matter here - you can use any patch version of EF with any patch version of .NET. The thing that matters is the TFM, which is `net8.0`; there are no patch versions there, since there are no .NET API changes in patch versions. But of course, it's always recommended to be on the latest patch versions of both .NET and EF.

**Comment by HugCoder** [comment]
Ah, I see, thanks a lot for answering! Really good to know. I haven't seen that being mentioned or discussed before, so I'm sure I'm not the only one who may come to the "conclusion" that runtime and package version could be linked somehow since they follow each other's version.

I really like your and Arthur's videos on youtube on EF etc. btw, I hope some new ones are to come with the launch of .NET 9. Thanks for all your work! :)
