### ISSUE TITLE
build initialize error

### ISSUE THREAD

**Issue by msincenselee** [dotnet/efcore#3506]
Writing lock file C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityF
ramework.Core.FunctionalTests\project.lock.json
Restore complete, 11566ms elapsed
Total time 18417ms

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Core.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Commands.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.InMemory.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.CrossStore.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.InMemory.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.MicrosoftSqlServer.Design.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Microbenchmarks\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.MicrosoftSqlServer.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Microbenchmarks.Core\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Microbenchmarks.EF6\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.MicrosoftSqlServer.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.MicrosoftSqlServer.Design.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Relational.Design.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Relational.Design.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Relational.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Relational.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Sqlite.Design.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Sqlite.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Sqlite.Design.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Sqlite.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Commands.Tests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

Errors in C:\Users\Incense\Documents\GitHub\EntityFramework\test\EntityFramework
.Core.FunctionalTests\project.json
    Unable to locate Dependency Microsoft.Dnx.TestHost >= 1.0.0-rc1-15775

NuGet Config files used:
    C:\Users\Incense\AppData\Roaming\NuGet\nuget.config
    C:\Users\Incense\Documents\GitHub\EntityFramework\nuget.config

Feeds used:
    https://www.nuget.org/api/v2/
    https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/
    https://api.nuget.org/v3-flatcontainer/
fail: Exit code 1 from cmd
fail: Stack trace:
   at View3f3267f26f93481d82fcb16d2876c461.<RenderViewLevel0>b__ca() in c:\Users
\Incense\AppData\Local\Temp\17007e0be7964756b3e9159220a8407d-1.cs:line 10061
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View3f3267f26f93481d82fcb16d2876c461.StartingTarget(String name) in c:\Use
rs\Incense\AppData\Local\Temp\17007e0be7964756b3e9159220a8407d-1.cs:line 3739
   at View3f3267f26f93481d82fcb16d2876c461.<RenderViewLevel0>b__89() in c:\Users
\Incense\AppData\Local\Temp\17007e0be7964756b3e9159220a8407d-1.cs:line 4314
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by msincenselee** [comment]
Environment: windows 10, vs 2015 community

**Comment by rowanmiller** [comment]
Can you try again now. We have an incomplete set of packages published to the CI MyGet feed yesterday... should be resolve now.
