### ISSUE TITLE
SQL Server: translate `dateOnly.ToDateTime(timeOnly)` to `DATETIMEFROMPARTS`

### ISSUE THREAD

**Issue by IanKemp** [dotnet/efcore#35076]
As title.

Transform to

```c#
EF.Functions.DateTimeFromParts(
    dateOnly.Year, dateOnly.Month, dateOnly.Day,
    timeOnly.Hour, timeOnly.Minute, timeOnly.Second, timeOnly.Millisecond)
```

which would then translate (using the current mapping of `EF.Functions.DateTimeFromParts`) to the SQL

```sql
DATETIMEFROMPARTS(
    DATEPART(year, dateOnly), DATEPART(month, dateOnly), DATEPART(day, dateOnly),
    DATEPART(hour, timeOnly), DATEPART(minute, timeOnly), DATEPART(second, timeOnly), DATEPART(millisecond, timeOnly))
```

**Comment by roji** [comment]
Putting in the backlog as a possible translation. One problem with this kind of translation is that it duplicates its argument (in this many times over); this is OK if the argument is a simple value (column), but if it's e.g. a complex scalar subquery, that would reevaluate the subquery many times over. At least at first, I'd not perform the translation in that case.

**Comment by mseada94** [comment]
@roji 
I would like to work on this method translation.
I am new to the repo, I will try to understand the translation and then start working on the code.
I think this PR would be a good reference to understand the method translation #31180

**Comment by roji** [comment]
@mseada94 sure thing, go ahead.

**Comment by mseada94** [comment]
@roji 
Should I perform the translation for SQL Server Only and skip SQLite considering the issue #18844 ?

**Comment by roji** [comment]
@mseada94 please submit a PR rather than posting implementation questions here - I'll review the PR (though it may take some time).

**Comment by mseada94** [comment]
I created the PR as draft
- The translation is done as expected
- I have an issue in comparison between datetime and string, I need to cast const value as datetime `please guide where to look`
- TODO: add support for `DateOnly` as constant with `TimeOnly` Property
