### ISSUE TITLE
Facing this issue on EF core 8.0

### ISSUE THREAD

**Issue by 3gi-shekh-ajhar** [dotnet/efcore#35070]
![Image](https://github.com/user-attachments/assets/48716ebe-03c0-4611-9589-cd08d84b9ee0)

**Comment by roji** [comment]
@3gi-shekh-ajhar you're most likely mixing versions of EF packages (e.g. 8.0 and 9.0) - this is not supported. Make sure you're using the same versions of EF packages in your csproj, and if you're still running into issues, post your csproj.

On a side note, please refrain from posting screenshots in issues, and always post a repro; a simple error is not enough information, and does not allow maintainers to understand what you're doing and help you.
