### ISSUE TITLE
collection-based materialization interceptor

### ISSUE THREAD

**Issue by jorge-olive-dp** [dotnet/efcore#35109]
`ValueConverters `and `IMaterializationInterceptor `are commonly recommended for handling decryption tasks. However, with the increasing use of Encryption as a Service (EaaS) solutions, such as HashiCorp Vault's [Transit API](https://developer.hashicorp.com/vault/tutorials/encryption-as-a-service/eaas-transit), performing decryption on a field-by-field or single-entity basis can become very inefficient, especially as it requires out-of-process operations. To address this performance concern, I would leverage a mechanism that enables batch processing for these types of operations.

I would like a lifecycle hook or interceptor that provides access to the **entire collection** of materialized entities from a query, just before the IQueryable completes and returns the final result that might allow the entities to be modified without necessarily alter its related change tracker state.

**Comment by roji** [comment]
@jorge-olive-dp matierlization in EF generally happens with the assumption that entities are being streamed; there isn't necessarily a phase where they're all present in a collection that can be handed off to an interceptor.
