### ISSUE TITLE
Filtered Include with Owned Entities

### ISSUE THREAD

**Issue by ma-cote** [dotnet/efcore#35112]
I know that you can't use IgnoreAutoIncludes() on owned entities and I understand why, but I'm wondering if I can use filtered includes instead in specific owned-entity update scenarios. 

In my example below, the distributor has many shipping centers. When I want to update a single shipping center, I'm forced to load them all before applying the changes, unless I use this Include() trick shown below. This works in my tests. My questions:

1. Is this a supported scenario?
2. Will this work in future versions of EF Core?

Thank you.

```C#
public class Distributor
{
    public int Id { get; set; }
    public ICollection<StreetAddress> ShippingCenters { get; set; }
}

modelBuilder.Entity<Distributor>().OwnsMany(p => p.ShippingCenters);

var distributor = context.Distributors
    .Include(d => d.ShippingCenters.Where(sc => sc.Id == <some id>))
    .FirstOrDefault();
distributor.ShippingCenters.Single().Street = "123";

context.SaveChanges();
```

EF Core version: 8
Database provider: Npgsql
Target framework: 8
Operating system: Any

**Comment by roji** [comment]
OK, opened #35135 to track erroring for filtered includes over owned entity types. @ma-cote if you're hitting any issues with ExecuteUpdate, please open a separate issue with a minimal repro.

**Comment by ma-cote** [comment]
@roji Since both are currently working for me (filtered include + ExecuteUpdate), I dont have any issue besides the fact that I now know that I need to replace my filtered include code 😄.

What's happening in my app is that I need to sync the aggregate data including owned entities and the amount of owned entities leads to performance and memory problems. That's why I tried a few things and was surprised that my filtered include code was working.

I can continue using the aggregate if I use ExecuteUpdate to update the data. However, I face a challenge when dealing with new owned entities, as there's no equivalent like ExecuteInsert. Do you know if there’s a way to insert a new owned entity into an aggregate without loading all the data into memory?

Thanks again.

**Comment by roji** [comment]
> Do you know if there’s a way to insert a new owned entity into an aggregate without loading all the data into memory?

Unfortunately not - in order to insert a new owned entity, you must load the entire aggregate and update it... Of course, you can use SQL to manually do INSERT yourself if you really need to avoid the performance hit.
