### ISSUE TITLE
"Microsoft.CodeAnalysis.Common (= 4.8.0)" conflicts with other packages using newer versions.

### ISSUE THREAD

**Issue by NinjataWRLD** [dotnet/efcore#35143]
**Summary**
EF Core Design's dependency on `Microsoft.CodeAnalysis.Common (= 4.8.0)` causes conflicts with other libraries, which use the newest version (4.11.0). This results in warnings about dependency mismatches:

`Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Workspaces.MSBuild 4.8.0 requires Microsoft.CodeAnalysis.Common (= 4.8.0) but version Microsoft.CodeAnalysis.Common 4.11.0 was resolved.`

While the app compiles and runs without errors, this could lead to runtime issues in scenarios where EF Core Design or the conflicting library requires specific features or behaviors from their respective versions of `Microsoft.CodeAnalysis.Common`.

**Proposed Solution**
Consider updating EF Core Design's dependency constraints to `>= 4.8.0` instead of `= 4.8.0`, or update to a newer version compatible with the latest libraries.

**Steps to Reproduce**
1. Create a project with EF Core Design v9.0 and Wolverine 3.3 (or any other library with a dependency on Microsoft.CodeAnalysis.Common v4.11).
2. Observe the dependency conflict warning during restore or build.

**Impact**
This restrictive dependency constraint creates avoidable warnings and potential runtime issues in projects integrating multiple libraries.

Thank you for considering this improvement!

**Comment by gpsd7-dbilli** [comment]
Another option is to suppress the warning by adding this to your project file:

```
	<PropertyGroup>
	    <NoWarn>$(NoWarn);NU1608;</NoWarn>
	</PropertyGroup>
```
As discussed here:

[Suppress a warning by editing the project file](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2022#suppress-a-warning-by-editing-the-project-file)

**Comment by AndriySvyryd** [comment]
> Another option is to suppress the warning by adding this to your project file:
> 
> ```
> 	<PropertyGroup>
> 	    <NoWarn>$(NoWarn);NU1608;</NoWarn>
> 	</PropertyGroup>
> ```
> 
> As discussed here:
> 
> [Suppress a warning by editing the project file](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2022#suppress-a-warning-by-editing-the-project-file)

In case of `Microsoft.CodeAnalysis.*` you really shouldn't ignore this warning. You will get runtime exceptions if you have mismatched versions.

**Comment by gpsd7-dbilli** [comment]
>
> 
> In case of `Microsoft.CodeAnalysis.*` you really shouldn't ignore this warning. You will get runtime exceptions if you have mismatched versions.

Thanks for the clarification.  

I'm targeting .NET 9, so here are the packages I had to reference to make the warnings disappear:

```
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>

  <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.12.0" />
  <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" />
  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.12.0" />
  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.12.0" />
```

**Comment by itsarisid** [comment]
I have installed updated version of `Microsoft.CodeAnalysis.Common`  and then other packages and no more conflicts

**Comment by bc3** [comment]
i indeed has a sortalike issue, what i did was explictely added the newer versions, and then my build warning were gone. 

We are on .net framework 8

```
 <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
```

**Comment by NinjataWRLD** [comment]
An alternative fix I found to the issue was this:

Separate the entry project (which should be the one holding the EF Core package for adding migrations and updating database) into two:

- One true/main entry project, holding the full DI logic and everything, but without that one package (thus no conflicts between EF Core and any other packages)
- One separate/secondary entry project, only containing the logic related to EF Core, and also that package (don't forget to fill in your environmental variables, they're different for all entry projects)

Use the first for a normal run of the server/app, and the second for adding migrations/updating database. This way no NuGet conflict arises, and there's better Separation of Concerns. Best of all - it works!

If you don't like the idea of going through that hussle, enforcing the newer version works too, so no worries - I prefer the other way though.
