### ISSUE TITLE
PendingModelChangesWarning exception thrown when upgrading to .NET 9

### ISSUE THREAD

**Issue by sebastianbk** [dotnet/efcore#35158]
We just migrated from .NET 8 to .NET 9, following the [migration guide](https://learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-9.0&tabs=visual-studio) provided by the ASP.NET Core team.

After having completed the steps of the guide and upgraded all SDK and package references to `9.0`, we ran into the following exception when running the app.

```
Unhandled exception. System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'WasDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.PendingModelChangesWarning(IDiagnosticsLogger`1 diagnostics, Type contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Program.<Main>$(String[] args) in /Users/<REDACTED>/Program.cs:line 220
```

The exception is thrown in the following code block, which sits in `Program.cs` after the `var app = builder.Build();` statement.

```csharp
using (var scope = app.Services.CreateScope())
{
    var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<WasDbContext>>();
    using (var context = dbFactory.CreateDbContext())
    {
        // Apply any outstanding migrations
        context.Database.Migrate();
    }
}
```

The code block above has worked without any issues from .NET 6.0 through .NET 8.0.

There are no outstanding changes/migrations in our project. We branched out from our main branch (on .NET 8), which builds without any issues, so we are very puzzled by this error.

Is this a bug in the newly released version of EF Core or are we missing something in our migration?

---

EF Core version: 9.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 9.0.1
Target framework: .NET 9.0
Operating system: macOS Sonoma 14.6.1
IDE: JetBrains Rider 2024.3

**Comment by wstaelens** [comment]
same with sql server,       await context.Database.MigrateAsync();
after updating from .net 8 to .net 9.

**Comment by wstaelens** [comment]
@sebastianbk 

when doing this:

```
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder.ConfigureWarnings(warnings => warnings.Log(RelationalEventId.PendingModelChangesWarning));

        }
```

the `update-database` works again

taken from here:

https://github.com/dotnet/efcore/issues/34431#issuecomment-2413845935

**Comment by sebastianbk** [comment]
Hi @wstaelens. I tried that and it works. Thanks for that.

However, I still believe there is an underlying bug here. This exception is not supposed to be thrown in the first place. There are not pending model changes.

**Comment by ChrisJollyAU** [comment]
See also #35110

**Comment by AndriySvyryd** [comment]
Can you provide a runnable repro project?

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by wstaelens** [comment]
*rant*
Ah @AndriySvyryd the Microsoft solution, like the [printing issues](https://github.com/dotnet/runtime/issues/78629): ignore, 'close' or 'future-version'-label and ignore for ±10years. 

Not every developer has time to investigate, create a repro, ...
sometimes it happens in big projects that would take days/weeks to just isolate the code, hoping you can extract it and that it will repo in a new solution.  

imho if many people signal that there is something wrong this should not be simply closed.
*/rant*

**Comment by AndriySvyryd** [comment]
@wstaelens I understand your frustration. But we are also a small team - 5 devs. We need to manage our time efficiently, so we close the issues that are not actionable. We've tried to find the root cause, but could not do it in a reasonable amount of time. If there are so many users affected, then one of them should be able to create a repro and we'll reopen the issue.
I'm improving the exception message in https://github.com/dotnet/efcore/pull/35221 to at least offer more information.

**Comment by JeremyJeanson** [comment]
Hi all,

I have the same Exception just after .net 8 to .net 9 migration.

I have a public project to reproduce it here :
https://github.com/JeremyJeanson/MyBlog.netcore

Download and run test. With .net 8 it work fine (you will only have some functionnal error during the first run, but nothing to take care).
Repro steps : Target .net 9, upgrade packages, and run unit test :
``` System.TypeInitializationException : The type initializer for 'MyBlog.Engine.Tests.TestsSetvices' threw an exception.
---- System.InvalidOperationException : An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'DataContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

**Comment by AndriySvyryd** [comment]
@JeremyJeanson You just need to add another migration.

**Comment by JeremyJeanson** [comment]
Thank you @AndriySvyryd 

OK, I understand the exception message. But why should I do that.

I have made many .net upgrades and never had to create an EF core Migration without real database changes. Except the move from the .net framework EF.

Please, could we have some explains? Should we create EF migration after all upgrades from .net 8 to.net 9?

**Comment by Pikeman** [comment]
Hi, we're also getting this exception for several projects on EF Core 9.

I don't have a full repro to share, but I wanted to share an observation: We're getting different results on different machines.

* First example: on machine A the call to `Migrate` fails. We then create a migration, and the call then returns successfully. However, on machine B (for example a production server) the call to `Migrate` still fails with this exception.
    * Applying the new migration manually (`dotnet ef migrations script ...`) does not make the exception go away.
* Second example: on machine A the call to `Migrate` succeeds without any new migration for EF Core 9. However, on machine B the call fails.

All machines on .NET 9.0.0 and same app source code, of course. We don't understand now what parts of our models "sometimes" have pending changes, and we don't have our source core or EF tools on all of these machines (neither do we want to, preferably).

**Comment by AndriySvyryd** [comment]
> I have made many .net upgrades and never had to create an EF core Migration without real database changes. Except the move from the .net framework EF.
> Please, could we have some explains? Should we create EF migration after all upgrades from .net 8 to.net 9?

You've made model changes since the last time a migration was added. But since there might be changes to how the model is built between major EF versions adding a new migration is, in general, also a good way to see whether your app was affected.

**Comment by Pikeman** [comment]
> I don't have a full repro to share, but I wanted to share an observation: We're getting different results on different machines.

Just chiming in with an update on our observation: Using `IMigrationsModelDiffer` at runtime, we found that the `Migrate` call was failing because it wanted to drop and recreate some indexes _in some environments_. We guess that this is because of us having hand-tweaked indexes in some places directly on the database. So I take it the differ here looks closely at the actual database as well, i.e. not just the differences between the classes and the model snapshot.

Diagnostic code:

```csharp
DbContext db = ...;
IServiceProvider services = ((IInfrastructure<IServiceProvider>)db).Instance;
IMigrationsModelDiffer _migrationsModelDiffer = services.GetRequiredService<IMigrationsModelDiffer>();
IModelRuntimeInitializer _modelRuntimeInitializer = services.GetRequiredService<IModelRuntimeInitializer>();
IMigrationsAssembly _migrationsAssembly = services.GetRequiredService<IMigrationsAssembly>();
IDesignTimeModel _designTimeModel = services.GetRequiredService<IDesignTimeModel>();
IReadOnlyList<MigrationOperation> differences = _migrationsModelDiffer
    .GetDifferences(
        _modelRuntimeInitializer
            .Initialize(_migrationsAssembly.ModelSnapshot.Model)
            .GetRelationalModel(),
        _designTimeModel.Model
            .GetRelationalModel());
```

We will proceed with either ironing out those environment inconsistencies or ignoring the warning. Cheers.

**Comment by AndriySvyryd** [comment]
> Just chiming in with an update on our observation: Using `IMigrationsModelDiffer` at runtime, we found that the `Migrate` call was failing because it wanted to drop and recreate some indexes _in some environments_. We guess that this is because of us having hand-tweaked indexes in some places directly on the database. So I take it the differ here looks closely at the actual database as well, i.e. not just the differences between the classes and the model snapshot.

That should not be the case. Model differ only looks at the snapshot. Make sure that the tool versions are the same across the different environments. And if you are still getting this behavior try to create a small report for that environment.

**Comment by Pikeman** [comment]
> That should not be the case. 

Very true!

Our version numbers look correct, so we dug deeper into the differ output and found some old code that caused variability in the model. Not any date or GUID data, but some other environmentally sensitive things. I suspect that this can explain all or most of the exceptions that we've seen so far on our end.

We'll keep upgrading. I want to emphasize that being able to easily access the `IMigrationsModelDiffer` has been very useful here. Cheers

**Comment by roji** [comment]
Note: we've just published #35285 which provides more background and explanations around the new PendingModelChangesWarning; anyone still having trouble should go read that - hopefully it should help.

**Comment by jasonmueller** [comment]
@AndriySvyryd I have a simple repro for this one (not necessarily small, but simple).  I just created a new solution using dotnet CLI commands, primarily, so one could start from the ground up and get to the same place.

Here's the stack:

 * Npgsql
 * ASP.NET Core Identity
 * Aspire

Note that everything works just fine until the following lines are added to the web project:

```
builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<IssueReproDb>();
```

After doing that, the pending changes error happens in the Web project startup every time you launch the AppHost, whether you've already applied migrations to the database. 

If you create a new migration to catch the differences, it shows up as an empty up and down.  Note that I don't have any entities, outside of those provided as part of the IdentityDbContext for ASP.NET Identity and no database seeding or anything.

Repro is at https://github.com/jasonmueller/ef9-pendingchanges-repro

**Comment by AndriySvyryd** [comment]
@jasonmueller In your case the warning is correct, though not very useful. Since you have `DatabaseContextFactory` it's used to create the context when running EF tools to add a migration and it doesn't include the additional Identity configuration. To create a migration that your application is expecting you'd need to do something like this:

```C#
public class DatabaseContextFactory : IDesignTimeDbContextFactory<IssueReproDb>
{
    public IssueReproDb CreateDbContext(string[] args)
    {
        var services = new ServiceCollection();
        services
            .AddDbContext<IssueReproDb>(options => options.UseNpgsql("Data Source=blog.db"))
            .AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
            .AddEntityFrameworkStores<IssueReproDb>();

        var serviceProvider = services.BuildServiceProvider();

        var scope = serviceProvider.CreateScope();
        return scope.ServiceProvider.GetRequiredService<IssueReproDb>();
    }
}
```

**Comment by jasonmueller** [comment]
@AndriySvyryd Thank you. I appreciate your solving my issue so I can continue to leave the exception in place for the warning.

I am surprised that those lines are required as I walked through those extension methods and didn't see anything that would have modified the DbContext (the entity mappings or any seeding).  Nonetheless, I appreciate the help.

**Comment by Frydex** [comment]
Before the 8th version of dotnet, I had the following option enabled:

`AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`

As soon as I removed this piece of code, the problem described in the post went away and now the migrations are working as before.
I hope I helped :)

**Comment by Malkmus** [comment]
We also have one project where we get the "'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'SourceDbContext' has pending changes. " when calling `await context.Database.MigrateAsync();` after upgrading from .NET 8 to .NET9. We are using Npgsql.EntityFrameworkCore.PostgreSQL 9.0.4.

We have two DbContexts and have added empty migrations after the upgrade to ensure that there are no updates in the schemas. Migrations are running fine on one of the dbcontexts, but the other one where we create the dbcontext through a factory, we get the error when running the migrations. Debugging with this:

`var pending = await context.Database.GetPendingMigrationsAsync();`

shows that there are no pending changes, but running `await context.Database.MigrateAsync();` fails with the message above.

Setting `optionsBuilder.ConfigureWarnings(warnings => warnings.Ignore(RelationalEventId.PendingModelChangesWarning));` makes the migrations run, but even after rinng the migrations and commenting this out again, we get the same error.

The error can be reproduced in the following project:
[https://github.com/Malkmus/dot-net-9-upgrade](url)

**Comment by roji** [comment]
@Malkmus I unfortunately don't have time to dive into your repro and investigate, but I recommend reading https://github.com/dotnet/efcore/issues/35285 thoroughly.

**Comment by stevendarby** [comment]
@Malkmus a starting point is that `GetPendingMigrationsAsync` "gets all migrations that are defined in the assembly but haven't been applied to the target database."

The error you're getting is that you have changes to your model that you haven't created a migration for yet. The migration is not defined in the assembly. 

Like roji said, worth reading through that post to understand the non-obvious reasons EF can think there is a change that you haven't created a migration for yet. Just making clear that not getting any results when you run `GetPendingMigrationsAsync` is not an indication that you shouldn't get this error.

**Comment by Malkmus** [comment]
I can't figure out what is causing the problem. I have tried recreating the model snapshot, but am still getting the error. I find it strange to get this error when adding a new migration results in an empty migration.

**Comment by stevendarby** [comment]
@Malkmus I had a look at your code. The way you are injecting `IDbContextSchema schema` into your migrations seems suspicious to me. Could this return different schemas in the two different scenarios: generating migrations and applying migrations? This could cause the issue.

edit: Yes, it looks like you apply the migrations to multiple contexts, each with a different schema. But the migrations are generated with one fixed schema. I don't know if there's a better way to handle that, or if this is a case where you would just have to configure to ignore the error.

**Comment by Malkmus** [comment]
@stevendarby  Yes, we loop through config of database connections and apply the same migrations on multiple schemas

**Comment by stevendarby** [comment]
So do you understand why you're getting the error? When migrating, it compares the model of context being migrated with the model captured by migrations in your assembly. The schema differs so it errors. That's my best guess anyway.

**Comment by AndriySvyryd** [comment]
@Malkmus if you apply the original migrations without injecting the schema and don't get the warning then it's safe to ignore the warning for the case where you change the schema as that's just outside of the basic migration workflow.

**Comment by Malkmus** [comment]
@stevendarby @AndriySvyryd Aha, I didn't get the part where the schema was used in the model. I updated the code to inject the schema to the model and then migrations run fine without the `optionsBuilder.ConfigureWarnings(warnings => warnings.Ignore(RelationalEventId.PendingModelChangesWarning));`. We just have to make sure that we update the modelsnapshot with this code to inject the schema every time we add a new migration.

**Comment by mwpastore** [comment]
> Before the 9th version of dotnet, I had the following option enabled:
> 
> `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`
> 
> As soon as I removed this piece of code, the problem described in the post went away and now the migrations are working as before

It doesn't matter whether EnableLegacyTimestampBehavior is set to true or false, per se; it matters what it's set to at design time vs. what it's set to when you call `context.Database.Migrate()`. They have to be in alignment.
