### ISSUE TITLE
EntityFrameworkCore SqlServer Ver. 9.0.0 NuGet package with Vulnerable System.Private.Uri Ver. 4.3.0 transitive package.

### ISSUE THREAD

**Issue by apvassiliou77** [dotnet/efcore#35167]
This NuGet package Microsoft.EntityFrameworkCore.SqlServer (version 9.0.0) contains a reference to System.Private.Uri (version 4.3.0) which has the following known Vulnerabilities:

[Known Vulnerability No1](https://github.com/advisories/GHSA-5f2m-466j-3848)
[Known Vulnerability No2](https://github.com/advisories/GHSA-xhfc-gr8f-ffwc)
[Known Vulnerability No3](https://github.com/advisories/GHSA-x5qj-9vmx-7g6g)

An update to Version 4.3.2 is suggested.

Thank you in advance.

**Comment by apvassiliou77** [comment]
I Have a .NET8 Console Application with the Microsoft.EntityFrameworkCore.SqlServer package installed and in NuGet package Manager I get this vulnerabilty.

![Image](https://github.com/user-attachments/assets/753f0224-0188-4fec-b7ff-a1ec9fd4df2d)

So I presumed that this is caused by the Microsoft.EntityFrameworkCore.SqlServer package.

**Comment by apvassiliou77** [comment]
Trying to uninstall the Microsoft.EntityFrameworkCore.SqlServer package and reinstalling it again I get following changes.

![Image](https://github.com/user-attachments/assets/3cb1c14f-13db-4b04-90d0-29e07a5a82ac)

As you can see the last package to be installed is System.Private.Uri. 
I get the same changes even if I clear the NuGet packages V3 Cache. My Visual Studio Version is 17.12.0.

**Comment by ErikEJ** [comment]
@apvassiliou77 Please share your .csproj file contents

**Comment by apvassiliou77** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="log4net.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="log4net" Version="3.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.0" />
  </ItemGroup>

</Project>

```

Here is my .csproj file contents.

**Comment by cincuranet** [comment]
In this case it comes from the runtime/SDK., not from us. Good approach to handle it is described [here](https://github.com/dotnet/sdk/issues/42651#issuecomment-2372410311).

cc @AndriySvyryd

**Comment by apvassiliou77** [comment]
> You should remove this:
> 
> `<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />`
> 
> and maybe replace with:
> 
> `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />`

I replaced the package you suggested and the warnings still exist.

**Comment by apvassiliou77** [comment]
> In this case it comes from the runtime/SDK., not from us. Good approach to handle it is described [here](https://github.com/dotnet/sdk/issues/42651#issuecomment-2372410311).
> 
> cc [@AndriySvyryd](https://github.com/AndriySvyryd)

I managed to remove the warnings after I removed the following line from my .csproj file.

<RuntimeIdentifier>win-x64</RuntimeIdentifier>

Thanks for your help.
