### ISSUE TITLE
InvalidCastException When Reading Property with Inconsistent Column Types Across Multiple Databases

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/efcore#35161]
I'm encountering an InvalidCastException in Entity Framework 8 when attempting to read the `MessageStatus` property from the DeviceEvent entity. This issue arises because the MessageStatus column type varies across different instances of my database.
Specifically, some databases define MessageStatus as Int32, while others use Int16.

Database: MSSQL 2008

My current Entity Framework configuration expects MessageStatus to be an Int16, which leads to the following error when the column is actually an Int32:
`An error occurred while reading a database value for property 'DeviceEvent.MessageStatus'. The expected type was 'System.Int16' but the actual value was of type 'System.Int32'.`

> [!NOTE]
> This is an implementation over a legacy system and I can't change DB schemas.

```
public enum MessageStatus : short
{
    Pending = 1,
    Sent = 2,
    Failed = 3
}

public class DeviceEvent
{
    public int Id { get; set; }
    public MessageStatus MessageStatus { get; set; }
    // Other properties...
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<DeviceEvent>(config =>
    {
        config.Property(b => b.MessageStatus)
            .HasColumnName("MessageStatus")
            .HasConversion(
                v => v,
                v => (MessageStatus)Convert.ToInt16(v)
            );
    });
}
```

I've tried several solutions:
- removing HasConversion and specifying .HasColumnType to smallint (the database with Int32 complains)
- removing HasConversion and specifying .HasColumnType to int (the database with Int16 complains)
- changing the enum type to int (default)

Nothing seems to work.
I'm stuck and nothing seems to help fix the problem, what's the solution to this kind of issues?

**Comment by cincuranet** [comment]
Well, you have different schemas and you're trying to fit it into one model. _SqlClient_ is not going to do implicit conversion from `Int32`/`Int16` to `Int16`/`Int32` for you. Given that you can't fix the schema (which is really the correct solution), a quick and dirty workaround would be to do the casting in SQL and use `ToSqlQuery` in your `OnModelCreating`.

```csharp
modelBuilder.Entity<DeviceEvent>(config =>
{
    config.Property(b => b.MessageStatus)
        .HasColumnName("MessageStatus");
    config.ToSqlQuery("select Id, cast(MessageStatus as smallint) as MessageStatus from DeviceEvent");
});
```

Fair to say, now inserts/updates/deletes are "unknown", so you'd have to use SPs or similar workaround (another).

Another workaround would be to have conditional model.

```csharp
public class MyContext : DbContext
{
    readonly Type _messageStatusType;

    public MyContext(Type messageStatusType)
    {
        _messageStatusType = messageStatusType;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.LogTo(Console.WriteLine, events: [RelationalEventId.CommandExecuting]);
        optionsBuilder.UseSqlServer("Data Source=2001:67c:d74:66:5cbb:f6ff:fe9e:eefa;Database=test;User=sa;Password=Pa$$w0rd;Connect Timeout=10;ConnectRetryCount=0;TrustServerCertificate=true");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DeviceEvent>(config =>
        {
            config.Ignore(b => b.MessageStatus);
            config.IndexerProperty(_messageStatusType, "MessageStatusBacking")
                .HasColumnName("MessageStatus");
        });
    }

}
public enum MessageStatus
{
    Pending = 1,
    Sent = 2,
    Failed = 3
}
public class DeviceEvent
{
    public int Id { get; set; }
    public MessageStatus MessageStatus
    {
        get => (MessageStatus)this[nameof(MessageStatus)];
        set => this[nameof(MessageStatus)] = value;
    }

    Dictionary<string, object> properties = [];
    public object this[string name]
    {
        get => properties[name];
        set => properties[name] = value;
    }
}
```

**Comment by cincuranet** [comment]
> What puzzles me is that the write is working (so EF is able to write a declared int property into a smallint (the value is always within smallint range) and viceversa can store a short into an int, but the read fails.

I'm not an expert on `SqlClient`, but I guess on write implicit type conversions happen, but that's not the case for `GetInt32`/`GetInt16`.

**Comment by roji** [comment]
Yeah, the important thing to understand is that these questions aren't related to EF, but rather to the lower-level database driver it uses (SqlClient in this case).
