### ISSUE TITLE
Could not load type AdHocMapper after upgrading from 8 to 9

### ISSUE THREAD

**Issue by rwb196884** [dotnet/efcore#35179]
Unit test project using in memory database (`Microsoft.EntityFrameworkCore.InMemory`).

Working in net8.

Updated to net9 and updated packages and now it's stopped working.

```
Message: 
System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.AdHocMapper' from assembly 'Microsoft.EntityFrameworkCore, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

  Stack Trace: 
EntityFrameworkRelationalServicesBuilder.TryAddCoreServices()
SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection serviceCollection)
SqlServerOptionsExtension.ApplyServices(IServiceCollection services)
ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
DbContext.ctor(DbContextOptions options)
XxxDbContext.ctor(DbContextOptions`1 options) line 64
<26 more frames...>
DelegatedWebApplicationFactory.CreateHost(IHostBuilder builder)
WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
WebApplicationFactory`1.EnsureServer()
WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
TestBase.ctor(XxxWebApplicationFactory`1 factory, Boolean passTroughSecurity) line 54
SomeTests.ctor(XxxWebApplicationFactory`1 factory) line 13
InvokeStub_SomeTests.ctor(Object, Span`1)
MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by lucasdelsilva** [comment]
Bro, I had the same problem with versions, I was having this same error after the update, unfortunately version 9 is still in preview "Basically", so the most advisable thing is to go back to version 8.11 and continue until they fix this error...

In my case it was this...

Before with the Error (V9):
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />

After without the error (V8.11):
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />

**Comment by SimonCropp** [comment]
My assumption is that Pomelo.EntityFrameworkCore.MySql is using an internal API of EF, and needs to be updated to EF V9

Probs better to close this and add a comment this this thread https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1841

**Comment by rwb196884** [comment]
I do not use `MySQL`.

**Comment by rwb196884** [comment]
Looks like I don't use net9 either

**Comment by rwb196884** [comment]
Can't even get a net9 example working.

Here's a net8 example that breaks when you update to net9.

**Comment by rwb196884** [comment]
How do you upload a zip file?

**Comment by rwb196884** [comment]
FFS what is the poing asking for an example when it's impossible to upload one?

**Comment by rwb196884** [comment]
[WebApplication1.zip](https://github.com/user-attachments/files/17918252/WebApplication1.zip)

**Comment by ajcvickers** [comment]
@rwb196884 Thanks for the repo--this is tracked by #35126. The original exception posted above is almost certainly due to mixing EF8 and EF9 packages.

**Comment by rwb196884** [comment]
With that `WebApplication1.zip`
It's `net8` and it works.
When you change the two projects to `net9` **and** update all of the packages it stops working.
What have I missed?

**Comment by ajcvickers** [comment]
@rwb196884 Your repro demonstrates a regression bug in EF9 that is tracked by #35126. There isn't a fix available yet.

**Comment by JimJohnston77** [comment]
I was really surprised that the changing to "PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11"  fixed this issue for me.

**Comment by rwb196884** [comment]
So as far as I can tell EF9 is completely broken and you mustn't 'upgrade'.

**Comment by ericwood8** [comment]
I got this issue as well when going from EF Core 8 to 9:
  System.TypeLoadException: 'Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.AdHocMapper' from assembly 'Microsoft.EntityFrameworkCore, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

**Comment by Fuxuan-CN** [comment]
same as me.

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.AdHocMapper' from assembly 'Microsoft.EntityFrameworkCore, Version=9.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by Rype69** [comment]
In case it's relevant, I managed to resolve this in my scenario.

I removed direct references to packages Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Sqlite from my project. I suspect there's a transitive reference to Microsoft.EntityFrameworkCore and there was a version mismatch.

I hope this helps.

**Comment by Fuxuan-CN** [comment]
> 如果它是相关的，我设法在我的场景中解决了这个问题。
> 
> 我从我的项目中删除了对包 Microsoft.EntityFrameworkCore 和 Microsoft.EntityFrameworkCore.Sqlite 的直接引用。我怀疑存在对 Microsoft.EntityFrameworkCore 的传递引用，并且存在版本不匹配。
> 
> 我希望这有帮助。

you can try this:
deupgrade this to ver 8.0.11, you can build successful.
![Image](https://github.com/user-attachments/assets/36fb653a-07eb-4e8c-a790-0a36f94d43c2)

**Comment by Fuxuan-CN** [comment]
this ploblem is solved in my program: https://github.com/Fuxuan-CN/HertaFramework

**Comment by IvanArantes** [comment]
Same happening here after i migrated from 8 to  MySql.EntityFrameworkCore 9.0.3

**Comment by roji** [comment]
Everyone, if you're hitting the error `System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.AdHocMapper'`, you are almost certainly mixing versions in your csproj files in a way which is incompatible. Please ensure that you're using **only** 9.0 versions of EF (this include any sort of transitive dependencies).

If you can't find an issue, please post a minimal, runnable repro which includes your csproj, otherwise we can't help you.

**Comment by SimonCropp** [comment]
@IvanArantes while a full repo would be best. it may be possible to work out if you share your csproj files. and you Directory.Packages.props if u r using central package management

**Comment by rwb196884** [comment]
> ...you are almost certainly...

Fucking brilliant guesswork.
