### ISSUE TITLE
Cosmos DateTime Serialization

### ISSUE THREAD

**Issue by cliedeman** [dotnet/efcore#35189]
## File a bug

Cosmos Provider DateTime Serialization does not serialize in the expected format: `yyyy-MM-ddTHH:mm:ss.fffffffZ`

### Include your code

Create any model that contains a DateTime and save it to cosmos

```C#
class Document {
  public Guid Id { get; set; }

  public DateTime Timestamp {get;set;}
}
```

```json
{
    "id": "cd081158-d474-43aa-b115-150f1d162e1d",
    "_ts": 1732385644,
    "$type": "Document",
    "_etag": "d401e28f-58dd-43df-895f-cf02b9cc2e18",
    "_self": "dbs/cosmosdb/colls/Document/docs/cd081158-d474-43aa-b115-150f1d162e1d/",
    "Timestamp": "2021-01-01T02:00:00+02:00",
}
```

The serialized timestamp does not follow the cosmos recommendations:

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/working-with-dates#storing-datetimes.

Related to https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4904 but I dont believe the ef core cosmos provider uses Json Serialization

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by roji** [comment]
In what way is the serialization not in the expected format? Are you referring to the lack of the `.fffffff` component? If so, then AFAIK ISO9601 allows omitting it when it's zero; try setting your DateTime to a timestamp which contains a sub-millisecond component, and you should see it serialized.

Otherwise, if I haven't understood what you're saying, please provide more details/context.

**Comment by cliedeman** [comment]
Hi @roji I figured out my issue.

The DateTime kind was local and not UTC. After changing it to UTC it was saved in the expected format.

The other issue is that the date in question is not valid according to the dotnet date format

```csharp
DateTimeOffset.ParseExact(
            "2021-01-01T02:00:00+02:00",
            "yyyy-MM-ddTHH:mm:ssZ",
            CultureInfo.InvariantCulture);
```

fails with 

```
String '2021-01-01T02:00:00+02:00' was not recognized as a valid DateTime.
```

where as 

```csharp
DateTimeOffset.ParseExact(
            "2021-01-01T02:00:00Z",
            "yyyy-MM-ddTHH:mm:ssZ",
            CultureInfo.InvariantCulture);
```

passes.

Atleast to my understanding if the `Z` is present in the format only Z will be accepted and not an offset
