### ISSUE TITLE
RelationalQueryableMethodTranslatingExpressionVisitor now accepts RelationalQueryCompilationContext and not QueryCompilationContext

### ISSUE THREAD

**Issue by stan-solovyov** [dotnet/efcore#35226]
In our .net library with ef core (both of version 8.0) we use the following code to provide our custom StringEnumExpressionVisitor.
```C#
public class StringEnumQueryableMethodTranslatingExpressionVisitorFactory :
        IQueryableMethodTranslatingExpressionVisitorFactory
    {
        private readonly QueryableMethodTranslatingExpressionVisitorDependencies
            dependencies;
        private readonly RelationalQueryableMethodTranslatingExpressionVisitorDependencies
            relationalDependencies;

        public StringEnumQueryableMethodTranslatingExpressionVisitorFactory(
            QueryableMethodTranslatingExpressionVisitorDependencies dependencies,
            RelationalQueryableMethodTranslatingExpressionVisitorDependencies relationalDependencies)
        {
            this.dependencies = dependencies;
            this.relationalDependencies = relationalDependencies;
        }

        public QueryableMethodTranslatingExpressionVisitor Create(
            QueryCompilationContext queryCompilationContext)
        {
            return new StringEnumQueryableMethodTranslatingExpressionVisitor(
                this.dependencies,
                this.relationalDependencies,
                queryCompilationContext, 
                new StringEnumExpressionVisitor());
        }
    }
```

```C#
public class StringEnumQueryableMethodTranslatingExpressionVisitor :
        RelationalQueryableMethodTranslatingExpressionVisitor
    {
        private readonly StringEnumExpressionVisitor visitor;

        public StringEnumQueryableMethodTranslatingExpressionVisitor(
            QueryableMethodTranslatingExpressionVisitorDependencies dependencies,
            RelationalQueryableMethodTranslatingExpressionVisitorDependencies relationalDependencies,
            RelationalQueryCompilationContext queryCompilationContext,
            StringEnumExpressionVisitor visitor)
            : base(dependencies, relationalDependencies, queryCompilationContext)
        {
            this.visitor = visitor;
        }

        protected override ShapedQueryExpression TranslateWhere(
            ShapedQueryExpression source,
            LambdaExpression predicate)
        {
            return base.TranslateWhere(
                source,
                (LambdaExpression)this.visitor.Visit(predicate));
        }

        protected override ShapedQueryExpression TranslateOrderBy(
            ShapedQueryExpression source,
            LambdaExpression keySelector,
            bool ascending)
        {
            return base.TranslateOrderBy(
                source,
                (LambdaExpression)this.visitor.Visit(keySelector),
                ascending);
        }
    }
```
Everything worked as expected. After updating ef core  and .net to version 9 we faced with the issue that the type of queryCompilationContext parameter of RelationalQueryableMethodTranslatingExpressionVisitor class has been changed from QueryCompilationContext to RelationalQueryCompilationContext. 

What is a proper way to get it out of QueryCompilationContext or maybe we need to implement some other interface than IQueryableMethodTranslatingExpressionVisitorFactory?

Database provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by roji** [comment]
On SQL Server, the QueryCompilationContext **is** a RelationalQueryCompilationContext; I don't know how you're currently getting your QueryCompilationContext (the above snippet doesn't contain a lot of context) but you should at the very least be able to cast it down to RelationalQueryCompilationContext (though that shouldn't really be necessary).

> maybe we need to implement some other interface than IQueryableMethodTranslatingExpressionVisitorFactory

That I think is the more interesting question here, and there's a good chance you shouldn't need to. If the idea is to run your StringEnumExpressionVisitor over expressions, is that something you really want to do only for Where/OrderBy (what about Skip, GroupBy and others)? You may simply be looking for [expression tree interception](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#linq-expression-tree-interception), which is a user-facing API (no need to replace EF services) which allows you to do stuff over the entire expression tree, early in the pipeline. I'd recommend looking at that, but I don't have enough on context on what you're doing to know for sure.

**Comment by stan-solovyov** [comment]
Hi Shay,

Thanks for the advice to have a look at expression tree interception. We already use it for default sorting.

>  I don't know how you're currently getting your QueryCompilationContext (the above snippet doesn't contain a lot of context)

We just replacing IQueryableMethodTranslatingExpressionVisitorFactory default implementation with our own. Here is the code:
```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder
        .ReplaceService<IModelCacheKeyFactory, FilteredModelCacheKeyFactory>()
        .ReplaceService<
            IQueryableMethodTranslatingExpressionVisitorFactory,
            StringEnumQueryableMethodTranslatingExpressionVisitorFactory>()
        .ReplaceService<
            IMigrationsSqlGenerator,
            ClientMigrationsSqlGenerator>()
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
        .AddInterceptors(new DefaultSortInterceptor());

    base.OnConfiguring(optionsBuilder);
}
```
So basically we use some default QueryCompilationContext that we get in our StringEnumQueryableMethodTranslatingExpressionVisitorFactory class in create method.
As you mentioned the easiest way would be just to cast to RelationalQueryCompilationContext, but I decided in the beginning that this is not a good solution and it's better to clarify.  
And regarding your point why we used this approach with overriding IQueryableMethodTranslatingExpressionVisitorFactory  instead of interception in the first place  I guess this is because this "Interception to modify the LINQ expression tree before a query is compiled" functionality appeared only in ef core 7, therefore it wasn't available at that time.

**Comment by roji** [comment]
> And regarding your point why we used this approach with overriding IQueryableMethodTranslatingExpressionVisitorFactory instead of interception in the first place I guess this is because this "Interception to modify the LINQ expression tree before a query is compiled" functionality appeared only in ef core 7, therefore it wasn't available at that time.

Sure. So I'd definitely recommend switching then. As I wrote, your current implementation above seems to only process Where and OrderBy clauses, whereas the expression tree interception would of course work everywhere (and you indicated you already use it).
