### ISSUE TITLE
Add dependency injection support to `IEntityTypeConfiguration` when using `ApplyConfigurationsFromAssembly`

### ISSUE THREAD

**Issue by julealgon** [dotnet/efcore#35233]
## Problem
We have a multi-tenant solution and have decided to model it in EF by passing the `TenantId` to the `DbContext` and using that value for both grabbing the tenant-specific connection string (inside of the `OnConfiguring` method), as well as for declaring a global filter on each entity.

At the same time, we are using dedicated `IEntityTypeConfiguration` implementations for each of our entities, to keep code more manageable (vs putting everything in the `DbContext`'s `OnModelCreating` method), and leveraging the `ApplyConfigurationsFromAssembly` method to automatically find and apply all such instances.

In this scenario, we are unable to specify the global filter inside of each `IEntityTypeConfiguration` implementation, because there is no way to transfer the `tenantId` value from the `DbContext` instance to the configuration classes when using that scanning/auto-construction approach.

We currently have a dependency injection-based mechanism to provide tenant information to classes in our codebase, by injecting a `ITenantContext` abstraction in the constructor.

We can provide the `tenantId` to the `DbContext` this way, since it supports DI, but the same cannot be done for the underlying `IEntityTypeConfiguration` classes since they are not resolved by DI. Instead, `IEntityTypeConfiguration` instances are created using the raw `Activator.CreateInstance` method, which in turn require the classes to have parameterless constructors.

https://github.com/dotnet/efcore/blob/d1e1dfa531dbf2d90df4a42ba71890ed5025dffd/src/EFCore/ModelBuilder.cs#L538

This feels like an arbitrary and confusing limitation: if DI is used when resolving dependencies in the context, it should be used by the configuration class instances as well.

In essence, we'd like for this change to work:
```diff
public sealed class SomeDbContext(ITenantContext tenantContext) : DbContext
{
    public DbSet<Customer> Customers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(tenantContext.TenantConnectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(this.GetType().Assembly);
-
-       modelBuilder.Entity<Customer>().HasQueryFilter(d => d.TenantId == tenantContext.TenantId);
    }
}

public sealed partial class Customer
{
-   private sealed class EntityConfiguration : IEntityTypeConfiguration<Customer>
+   private sealed class EntityConfiguration(ITenantContext tenantContext) : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> builder)
        {
            builder
                .ToTable("Customers", "someSchema")
                .HasKey(c => c.RandomCustomerId);
+
+           builder.HasQueryFilter(d => d.TenantId == tenantContext.TenantId);
        }
    }
}

```

## Proposal
The proposal is that `ApplyConfigurationsFromAssembly` is changed to rely on `ActivatorUtilities.CreateInstance` (or equivalent) instead of on the non-DI `Activator.CreateInstance` method for constructing the configuration classes, so that we can inject dependencies into the `IEntityTypeConfiguration` implementations.

In our particular use case, we want to be able to inject tenant-specific abstractions for declaring a tenant-limiting global filter on the entity as per above.

## Workaround
We have 2 less-than-ideal ways to work around this limitation today.

1. Manually provide each implementation of `IEntityTypeConfiguration` and propagate the `ITenantContext` via constructor argument this way
    ```csharp
    modelBuilder.ApplyConfiguration(new Customer.EntityConfiguration(tenantContext));
    ```
    This of course breaks down today, since the implementation is an inner `private` class on the entity class. This not only would force us to add each class manually but also change our organization and start exposing the configuration implementation to the `DbContext`.

2. Create our own scanning extension that uses `ActivatorUtilities` in conjunction with `IServiceProvider` to construct the configuration instances
This is probably what we'll eventually end up doing but we'd rather the built-in method just did it for us so we didn't have to maintain such custom extension. And since we don't control the `DbContext` base dependencies, we are forced to manually pass `IServiceProvider` this way:
    ```csharp
    modelBuilder.ApplyConfigurationsFromAssemblyCustom(this.GetType().Assembly, serviceProvider);
    ```

**Comment by ajcvickers** [comment]
Note for team: we have always recommended people do their own implementations for these types of thing.

**Comment by AndriySvyryd** [comment]
Closures of types derived from `DbContext` are special-cased and will be replaced with the current instance:

```C#
    private sealed class EntityConfiguration : IEntityTypeConfiguration<Customer>
    {
        private readonly SomeDbContext _context;
        public void Configure(EntityTypeBuilder<Customer> builder)
        {
            builder
                .ToTable("Customers", "someSchema")
                .HasKey(c => c.RandomCustomerId);
            
            builder.HasQueryFilter(d => d.TenantId == _context.TenantId);
        }
    }
```

As for the feature request, we decided to not extend the functionality of `ApplyConfigurationsFromAssembly`, it is only provided as sugar and developers can have their own tailored implementations.

**Comment by AndriySvyryd** [comment]
> I'm not sure I understand what you mean here. Who exactly is setting the _context field here? It's not clear to me if you are proposing this as a workaround or not. Does it actually work this way? If so, how? Checking the code for ApplyConfigurationsFromAssembly I don't see how this would work seeing as the instance is being constructed with Activator and then right after that the interface method is called on it.

> Can you elaborate a bit?

Sure, the lambda passed to `HasQueryFilter` is not invoked directly. It's stored as an expression tree in the model. Later, when a query on this type is called EF [incorporates the filter expression tree](https://github.com/dotnet/efcore/blob/321d5c66f6bbf9a37ed9dd21f8a16dcbec37f8b9/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs#L1753) into the query expression tree, then translates it to SQL. During the translation when it finds an expression node containing a closure normally it would evaluate it to the referenced value and translate the value, but if it's of a type matching the current context type it [will be replaced with the current context](https://github.com/dotnet/efcore/blob/321d5c66f6bbf9a37ed9dd21f8a16dcbec37f8b9/src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs#L2318) in the dynamically compiled lambda representing the query.

And yes, the posted code works right now.

> I personally feel like that is a bad decision as you end up with an overall inconsistent API as DbContext supports full DI but the config classes suddenly don't. When a framework supports DI, it usually does so throughout its entire extension layer.

`IEntityTypeConfiguration` and related methods is not an extension mechanism, it is just sugar for a common pattern used to split `OnModelCreating`, there is no inherent benefit from using them instead of implementing a different pattern that's better suited to your scenario.

**Comment by julealgon** [comment]
> > I'm not sure I understand what you mean here. Who exactly is setting the _context field here? It's not clear to me if you are proposing this as a workaround or not. Does it actually work this way? If so, how? Checking the code for ApplyConfigurationsFromAssembly I don't see how this would work seeing as the instance is being constructed with Activator and then right after that the interface method is called on it.
> 
> > Can you elaborate a bit?
> 
> Sure, the lambda passed to `HasQueryFilter` is not invoked directly. It's stored as an expression tree in the model. Later, when a query on this type is called EF [incorporates the filter expression tree](https://github.com/dotnet/efcore/blob/321d5c66f6bbf9a37ed9dd21f8a16dcbec37f8b9/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs#L1753) into the query expression tree, then translates it to SQL. During the translation when it finds an expression node containing a closure normally it would evaluate it to the referenced value and translate the value, but if it's of a type matching the current context type it [will be replaced with the current context](https://github.com/dotnet/efcore/blob/321d5c66f6bbf9a37ed9dd21f8a16dcbec37f8b9/src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs#L2318) in the dynamically compiled lambda representing the query.
> 
> And yes, the posted code works right now.

Ok. This is both fascinating and scary at the same time 😅. If I were to put such code in our classes I would likely have to add a sizeable comment explaining the sorcery behind it. Having an uninitialized field suddely "get a value" later from the outside like this is _super_ criptic behavior.

Is this actually documented somewhere on microsoft.learn? If so, I must've completely missed that capability.

I do appreciate you sharing that option though, even if we might not end up using it due to the extreme obscurity.

> > I personally feel like that is a bad decision as you end up with an overall inconsistent API as DbContext supports full DI but the config classes suddenly don't. When a framework supports DI, it usually does so throughout its entire extension layer.
> 
> `IEntityTypeConfiguration` and related methods is not an extension mechanism, it is just sugar for a common pattern used to split `OnModelCreating`, there is no inherent benefit from using them instead of implementing a different pattern that's better suited to your scenario.

I guess we'll agree to disagree on this one. To me, any interface that a framework exposes for consumers to implement is most definitely an extension point/hook, almost by definition. Now suddenly some extension points in EF support DI while others don't. That's the inconsistency I'm not fond of and I think it degrades the quality of the library overall when such inconsistencies exist.

**Comment by AndriySvyryd** [comment]
> Ok. This is both fascinating and scary at the same time 😅. If I were to put such code in our classes I would likely have to add a sizeable comment explaining the sorcery behind it. Having an uninitialized field suddely "get a value" later from the outside like this is super criptic behavior.
> Is this actually documented somewhere on microsoft.learn? If so, I must've completely missed that capability.
> I do appreciate you sharing that option though, even if we might not end up using it due to the extreme obscurity.

It's not documented because it's a bit of a happy accident. The primary reason we do it is because the context instance used to build the model might not be the same one running the query, as the model itself is cached.

> I guess we'll agree to disagree on this one. To me, any interface that a framework exposes for consumers to implement is most definitely an extension point/hook, almost by definition. Now suddenly some extension points in EF support DI while others don't. That's the inconsistency I'm not fond of and I think it degrades the quality of the library overall when such inconsistencies exist.

I'm not a fan of `IEntityTypeConfiguration` and would remove it if it was up to me. But many developers like it the way it is. 🤷

**Comment by julealgon** [comment]
> It's not documented because it's a bit of a happy accident. The primary reason we do it is because the context instance used to build the model might not be the same one running the query, as the model itself is cached.

I see. Have you considered explicitly providing the DbContext instance as an argument to the expression, then?

We could then use it like this:
```csharp
builder.HasQueryFilter((entity, context) => entity.TenantId == context.TenantId);
```

The caveat of course would be that you'd need to provide the context type on the model builder:

```csharp
private sealed class EntityConfiguration : IEntityTypeConfiguration<Customer, SampleDbContext>
{
    private readonly SomeDbContext _context;
    public void Configure(EntityTypeBuilder<Customer, SampleDbContext> builder)
    ...
```

I feel like this design would get you the same capabilities, but in a much more explicit and expected way.

> I'm not a fan of `IEntityTypeConfiguration` and would remove it if it was up to me. But many developers like it the way it is. 🤷

How do you handle managing, say, dozens of types in the same DbContext? The reason why I personally use this interface is to decouple the code a bit and split the configuration in a more manageable way. It gets unwieldy to handle everything in the same centralized method. Do you just put all your configuration there, or do you create your own abstraction to split it up?

**Comment by AndriySvyryd** [comment]
> The caveat of course would be that you'd need to provide the context type on the model builder:

Yes, we've considered it and this was the reason we decided against it.

> Do you just put all your configuration there, or do you create your own abstraction to split it up?

Yes, just create your own abstraction. There are multiple ways you can refactor this code and you should use what best fits your codebase.

**Comment by roji** [comment]
> The caveat of course would be that you'd need to provide the context type on the model builder:

Just mentioning that the specific overload of HasQueryFilter that supports referencing the context could be generic, i.e.:

```c#
builder.HasQueryFilter<MyContext>((entity, context) => entity.TenantId == context.TenantId);
```

FWIW I do agree that the above would be a bit cleaner and less magical than our current thing. On the other hand, @julealgon consider that the current API does look quite nice when the model is defined inside the context type, which is the usual way EF is set up:

```c#
public class BlogContext : DbContext
{
    private readonly int _tenantId;
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Post>().HasQueryFilter(p => p.TenantId == _tenantId);
    }
}
```

Requiring users to explicitly specify BlogContext as a type parameter within a generic overload seems clunky and unnecessary here - even if it does seem a bit odd when the HasQueryFilter is in an external type etc.

**Comment by julealgon** [comment]
@roji 
> > The caveat of course would be that you'd need to provide the context type on the model builder:
> 
> Just mentioning that the specific overload of HasQueryFilter that supports referencing the context could be generic, i.e.:
> 
> builder.HasQueryFilter<MyContext>((entity, context) => entity.TenantId == context.TenantId);
> FWIW I do agree that the above would be a bit cleaner and less magical than our current thing. On the other hand, [@julealgon](https://github.com/julealgon) consider that the current API does look quite nice when the model is defined inside the context type, which is the usual way EF is set up:
> 
> public class BlogContext : DbContext
> {
>     private readonly int _tenantId;
>     
>     protected override void OnModelCreating(ModelBuilder modelBuilder)
>     {
>         modelBuilder.Entity<Post>().HasQueryFilter(p => p.TenantId == _tenantId);
>     }
> }
> Requiring users to explicitly specify BlogContext as a type parameter within a generic overload seems clunky and unnecessary here - even if it does seem a bit odd when the HasQueryFilter is in an external type etc.

Do keep in mind the `HasQueryFilter` call with 2 parameters (context and entity) could just be an overload. Then, your code would still be basically just as simple, with a super small change:

```diff
public class BlogContext : DbContext
{
    private readonly int _tenantId;
    
-   protected override void OnModelCreating(ModelBuilder modelBuilder)
+   protected override void OnModelCreating(ModelBuilder<BlogContext> modelBuilder)
    {
        modelBuilder.Entity<Post>().HasQueryFilter(p => p.TenantId == _tenantId);
    }
}
```

Such design could even allow you to completely decouple the model creation from the `DbContext` if you wanted to (which I personally think would be an interesting change in and of itself, especially as you guys already have different lifetimes for the model and the context, as pointed out earlier).
