### ISSUE TITLE
Regression in EF9 for CosmosDb, 'CountAsync' broken

### ISSUE THREAD

**Issue by mip1983** [dotnet/efcore#35245]
In my project I have a function to do a paged database search of some entities e.g.

```cs
public async Task<PagedDataResult<EnquiryDisplayModel>> SearchEnquiriesAsync(EnquiryFilter filter)
{
    var result = new PagedDataResult<EnquiryDisplayModel>(filter.Skip, filter.Take);
    var query = this.cosmosDbContext.Query<Enquiry>(filter.CustomerId.ToString()).AsQueryable();
    
    if (!string.IsNullOrWhiteSpace(filter.Search))
    {
    	query = query.Where(e => e.Title.ToLower().Contains(filter.Search.ToLower()));
    }
    
    if (filter.ProjectId.HasValue)
    {
    	query = query.Where(e => e.ProjectId == filter.ProjectId.Value);
    }
    
    if (filter.From.HasValue && filter.To.HasValue)
    {
    	query = query.Where(e => !(e.From < filter.From.Value && e.To > filter.To.Value));
    }
    
    result.TotalRecords = await query.CountAsync();

    if (filter.Skip != null && filter.Skip > 0)
    {
    	query = query.Skip(filter.Skip.Value);
    }
    
    if (filter.Take != null && filter.Take > 0)
    {
    	query = query.Take(filter.Take.Value);
    }

    var enquiries = await query.ToListAsync();
    var enquiryModels = await ToEnquiryDisplayModel(enquiries, filter.CustomerId);

    result.Items = enquiryModels;
    
    return result;
}
```

This was working fine before with EF8, with EF9 it still runs without error, but I've just noticed pagination is broken. Looking into it:

```cs
result.TotalRecords = await query.CountAsync();
```

CountAsync is returning 0. I've changed it to:

```cs
result.TotalRecords = query.Count();
```

And this works. Seems the async method has been broken.

### Include provider and version information

EF Core version: 9.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: (e.g. .NET 9.0)
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.12.2)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
