### ISSUE TITLE
Why are owned types required to use ToJson feature?

### ISSUE THREAD

**Issue by ktownsend-personal** [dotnet/efcore#35259]
## Question
Why are owned types required to use the ToJson feature?
I suspect this has been asked, but I cannot find any discussion of it.

## Scenario
I have a scenario where I am keeping a draft version of an entity as a child property of the entity and stored as JSON. Because the child and the parent are the same type, the property type cannot be owned with `OwnsOne` or `OwnsMany`. This is from an `MVC5` project I am converting to `EF Core 8`. 

## Failed Attempt
I attempted subclassing the entity type so it could be owned, which didn't quite work out. I have two list properties that had to be hidden in the new subclass with new versions of the properties using a subclass of the type in the lists. While it compiled and ran, it created a big complication for my business logic that treats the entity and the draft as the same base type, as it would not see the new properties unless I detect the true type and cast to that type conditionally to reach the right properties. Yuck.

## More Questions
I solved my problem by using the tried and true `ValueConverter` trick, but it left me wondering:
1. why owned types are required for the ToJson feature in the first place?
1. why does it matter that the type is used elsewhere in the model? 
1. is this capability planned for a future update?

**Comment by ajcvickers** [comment]
@ktownsend-personal The answer to all your questions is basically the same--for the most common uses of JSON, owned types are not a good fit. The team recognizes this, which is why we are implementing complex types, which have value-object semantics--and we will then [support mapping to JSON from complex types](https://github.com/dotnet/efcore/issues/31252).

**Comment by ktownsend-personal** [comment]
@ajcvickers that is excellent news. I am looking forward to that feature. Thanks for the link so I could catch up on the discussions.
