### ISSUE TITLE
Issues with EF Tools (9.0.0) and MS.CodeAnalysis.WorkSpaces.MSBuild (4.8.0)

### ISSUE THREAD

**Issue by WalterB-MAMC** [dotnet/efcore#35258]
I first upgraded my working project to .NET 9.0 and started to see this isssue and then tracked it down with a test project. What I have found is that the Microsoft.EntityFrameworkCore.Tools (9.0.0) installs Microsoft.CodeAnalysis.Workspaces.MSBuild (4.8.0) when .NET 9.0 seems to be using (4.11.0). For me in particular, I am using Telerik UI for ASP.NET Core and it is .NET 9.0 ready and wants version MSBuild (4.11.0). So what I end up with is warning symbols in my solution explorer and warnings in my build window on build. When I manually add the package Microsoft.CodeAnalysis.Workspaces.MSBuild (4.11.0) to my project, then the warnings go away but then I get linked folders in my project named BuildHost-net472 and BuildHost-netcore.

This picture shows MSBuild installed and the BuildHost folders present but no warnings.
![Image](https://github.com/user-attachments/assets/39a1e40e-e11e-441c-a275-00a262b820ae)

This picture shows EF Tools and Telerik installed causing the warnings for the MSBuild issue. MSBuild 4.11.0 is not installed so the warnings are present.
![Image](https://github.com/user-attachments/assets/4593238d-83df-40f9-bd4d-9e9fe84cd1ff)

This show what is installed when installing the EF Tools 9.0.0, notice the Microsoft.CodeAnalysis.Workspace.MSBuild.4.8.0 as this seems to be causing the issue.
![Image](https://github.com/user-attachments/assets/7a5a785c-78bd-4fe0-856e-5f302d4b6974)

When I remove the MSBuild 4.11.0 and only have EF.Tools installed in the project or Telerik installed in the project there is no warning. Only when the two are together.

**Comment by ajcvickers** [comment]
@WalterB-MAMC 

> Microsoft.CodeAnalysis.Workspaces.MSBuild (4.11.0) to my project, then the warnings go away but then I get linked folders in my project named BuildHost-net472 and BuildHost-netcore.

I believe this is expected, because Microsoft.CodeAnalysis.Workspaces.MSBuild [has two target platforms](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.MSBuild/4.11.0#supportedframeworks-body-tab).

![Image](https://github.com/user-attachments/assets/6d574e0e-b293-4e1c-90ed-b4d8558d80c4)

This means the NuGet package carries to assemblies, one which is used when you build for .NET Framework, and one when you build with modern .NET (aka .NET Core).

**Comment by WalterB-MAMC** [comment]
I get that it can target multiple frameworks, but I have never seen it add linked BuildHost-{version} folders to a project before. This is the first time I have ever seen this behavior. I use libraries all the time that target multiple frameworks. Just seems odd that using the latest version of MSBuild and EF creates this behavior.

**Comment by AndriySvyryd** [comment]
@WalterB-MAMC The BuildHost-{version} folders is normal behavior you get when using Microsoft.CodeAnalysis.Workspaces.MSBuild >= 4.9.x

https://github.com/dotnet/roslyn/blob/main/src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj#L89
