### ISSUE TITLE
Why is a type discriminator not supported in TPT mapping strategy?

### ISSUE THREAD

**Issue by gumbarros** [dotnet/efcore#35286]
While configuring an EF Core entity using Table-per-Type (TPT) mapping strategy, I attempted to set up a type discriminator for easier identification of the derived entity types. However, it seems this feature is not supported when using TPT. Below is the configuration code I used:

```csharp
modelBuilder.Entity<MenuItemEntity>()
    .ToTable("MenuItem", Schema)
    .UseTptMappingStrategy()
    .HasDiscriminator<MenuItemType>("Type")
    .HasValue<FileMenuItemEntity>(MenuItemType.File)
    .HasValue<FolderMenuItemEntity>(MenuItemType.Folder)
    .HasValue<FormElementMenuItemEntity>(MenuItemType.FormElement)
    .HasValue<PluginMenuItemEntity>(MenuItemType.Plugin)
    .HasValue<PowerBIMenuItemEntity>(MenuItemType.PowerBI)
    .HasValue<ReportMenuItemEntity>(MenuItemType.Report)
    .HasValue<UrlMenuItemEntity>(MenuItemType.Url);
```

Upon running the application, the configuration fails, and after reviewing the documentation, it seems TPT does not allow a discriminator column.  

```cs
System.InvalidOperationException: The mapping strategy 'TPT' specified on 'MenuItemEntity' is not supported for entity types with a discriminator.
``` 
This raises the following questions:  

1. Why is a discriminator column not supported when using the TPT mapping strategy?   I want to have this discriminator column at `MenuItemEntity` for SQL reports outside my app.
2. Are there any underlying technical limitations or design decisions behind this?  

Understanding the rationale behind this limitation would be helpful for designing better solutions or workarounds for applications that need TPT with type discriminators.

**Comment by roji** [comment]
TPT means that you get a "table per type", i.e. each CLR type has its own table in the database. That means the table in which the row is present is enough to know which type is represented by the row, and a discriminator column isn't necessary. A discriminator column in necessary in TPH, where multiple entity types are mapped to the same table, and therefore need to be distinguished (or discriminated).

Why exactly are you looking to use a discriminator with TPT?

**Comment by gumbarros** [comment]
> TPT means that you get a "table per type", i.e. each CLR type has its own table in the database. That means the table in which the row is present is enough to know which type is represented by the row, and a discriminator column isn't necessary. A discriminator column in necessary in TPH, where multiple entity types are mapped to the same table, and therefore need to be distinguished (or discriminated).
> 
> Why exactly are you looking to use a discriminator with TPT?

My coworker wants to query (using pure SQL outside of .NET) a polymorphic `MenuItem` and he wants to know what kind it is without the 'ugly' query generated by EF Core:
```cs
DECLARE @__menuId_0 uniqueIdentifier = '3893d510-d370-45fa-89c1-4c7f93628c62';

SELECT [m].[Id], [m].[IconId], [m].[IsNew], [m].[Name], [m].[NewUntil], [m].[Order], [m].[ParentId], [m0].[Behavior], [m0].[SelectedFileId], [m1].[ExpandedByDefault], [m1].[IsGrouper], [m2].[DefaultState], [m2].[ElementName], [m3].[PluginMenuItemId], [m4].[ConnectionId], [m4].[Filter], [m4].[ReportId], [m4].[WorkspaceId], [m5].[ReportId], [m6].[Behavior], [m6].[Url], CASE
    WHEN [m6].[Id] IS NOT NULL THEN N'UrlMenuItemEntity'
    WHEN [m5].[Id] IS NOT NULL THEN N'ReportMenuItemEntity'
    WHEN [m4].[Id] IS NOT NULL THEN N'PowerBIMenuItemEntity'
    WHEN [m3].[Id] IS NOT NULL THEN N'PluginMenuItemEntity'
    WHEN [m2].[Id] IS NOT NULL THEN N'FormElementMenuItemEntity'
    WHEN [m1].[Id] IS NOT NULL THEN N'FolderMenuItemEntity'
    WHEN [m0].[Id] IS NOT NULL THEN N'FileMenuItemEntity'
END AS [Discriminator]
FROM [Infinity].[MenuItem] AS [m]
LEFT JOIN [Infinity].[MenuItemFile] AS [m0] ON [m].[Id] = [m0].[Id]
LEFT JOIN [Infinity].[MenuItemFolder] AS [m1] ON [m].[Id] = [m1].[Id]
LEFT JOIN [Infinity].[MenuItemDataDictionary] AS [m2] ON [m].[Id] = [m2].[Id]
LEFT JOIN [Infinity].[MenuItemPlugin] AS [m3] ON [m].[Id] = [m3].[Id]
LEFT JOIN [Infinity].[MenuItemPbi] AS [m4] ON [m].[Id] = [m4].[Id]
LEFT JOIN [Infinity].[MenuItemReport] AS [m5] ON [m].[Id] = [m5].[Id]
LEFT JOIN [Infinity].[MenuItemUrl] AS [m6] ON [m].[Id] = [m6].[Id]
WHERE [m].[Id] = @__menuId_0
```
Using a type discriminator would help querying outside of EF and _maybe_ would help improve TPT performance inside of EF if it used that column internally and didn't have to do all the LEFT JOINs.

**Comment by ajcvickers** [comment]
@gumbarros Can you provide an example of a actual query where using the discriminator is useful?

**Comment by gumbarros** [comment]
> [@gumbarros](https://github.com/gumbarros) Can you provide an example of a actual query where using the discriminator is useful?

```sql
    SELECT 
    U.FirstName, 
    'Menu' Tipo, 
    M.Name, 
    null RoleId 
    FROM Infinity.Users as U WITH (NOLOCK)
    INNER JOIN Infinity.MenuUserClaims as UC WITH (NOLOCK) 
    ON UC.Id = U.Id
    INNER JOIN Infinity.MenuItem as M WITH (NOLOCK) 
    ON M.Id = UC.PermissionId

    UNION ALL

    SELECT 
    U.FirstName, 
    'Menu' Tipo, 
    M.Name, 
    UR.RoleId 
    FROM Infinity.Users as U WITH (NOLOCK)
    INNER JOIN Infinity.UserRoles as UR WITH (NOLOCK)
    ON UR.UserId = U.Id
    INNER JOIN Infinity.MenuRoleClaims as MUR WITH (NOLOCK)
    ON MUR.Id = UR.RoleId
    INNER JOIN Infinity.MenuItem as M WITH (NOLOCK)
    ON M.Id = MUR.PermissionId
```

The query is a lot larger and complex, but this is just a part of it. At `'Menu' Tipo,` we want to recover the type of the menu (File, Folder, FormElement, Plugin, PowerBI, Report, Url). We don't want to do a `LEFT JOIN` in every possibility just to know its type, make a lot more sense a discriminator column.

**Comment by gumbarros** [comment]
About what I said about performance, I looked at the existing issues and I believe it is related to this issue #24483. When we get a List<MyBaseClass> I agree that Joins are necessary, but when we retrieve a single record from MyBaseClass, the discriminator column would perhaps help EF.

**Comment by roji** [comment]
@gumbarros can you post the exact LINQ query you have in mind, which would translate to the above? Especially to understand what you mean by "but when we retrieve a single record from MyBaseClass"?

**Comment by gumbarros** [comment]
> [@gumbarros](https://github.com/gumbarros) can you post the exact LINQ query you have in mind, which would translate to the above? Especially to understand what you mean by "but when we retrieve a single record from MyBaseClass"?

This is the equivalent LINQ:
```cs
    public async Task<MenuItem?> GetAsync(Guid menuId)
    {
        var menuItem = await dbContext
            .MenuItems
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.Id == menuId);
        return menuItem;
    }
``` 

The equivalent SQL is this:
```cs
DECLARE @__menuId_0 uniqueIdentifier = '3893d510-d370-45fa-89c1-4c7f93628c62';

SELECT [m].[Id], [m].[IconId], [m].[IsNew], [m].[Name], [m].[NewUntil], [m].[Order], [m].[ParentId], [m0].[Behavior], [m0].[SelectedFileId], [m1].[ExpandedByDefault], [m1].[IsGrouper], [m2].[DefaultState], [m2].[ElementName], [m3].[PluginMenuItemId], [m4].[ConnectionId], [m4].[Filter], [m4].[ReportId], [m4].[WorkspaceId], [m5].[ReportId], [m6].[Behavior], [m6].[Url], CASE
    WHEN [m6].[Id] IS NOT NULL THEN N'UrlMenuItemEntity'
    WHEN [m5].[Id] IS NOT NULL THEN N'ReportMenuItemEntity'
    WHEN [m4].[Id] IS NOT NULL THEN N'PowerBIMenuItemEntity'
    WHEN [m3].[Id] IS NOT NULL THEN N'PluginMenuItemEntity'
    WHEN [m2].[Id] IS NOT NULL THEN N'FormElementMenuItemEntity'
    WHEN [m1].[Id] IS NOT NULL THEN N'FolderMenuItemEntity'
    WHEN [m0].[Id] IS NOT NULL THEN N'FileMenuItemEntity'
END AS [Discriminator]
FROM [Infinity].[MenuItem] AS [m]
LEFT JOIN [Infinity].[MenuItemFile] AS [m0] ON [m].[Id] = [m0].[Id]
LEFT JOIN [Infinity].[MenuItemFolder] AS [m1] ON [m].[Id] = [m1].[Id]
LEFT JOIN [Infinity].[MenuItemDataDictionary] AS [m2] ON [m].[Id] = [m2].[Id]
LEFT JOIN [Infinity].[MenuItemPlugin] AS [m3] ON [m].[Id] = [m3].[Id]
LEFT JOIN [Infinity].[MenuItemPbi] AS [m4] ON [m].[Id] = [m4].[Id]
LEFT JOIN [Infinity].[MenuItemReport] AS [m5] ON [m].[Id] = [m5].[Id]
LEFT JOIN [Infinity].[MenuItemUrl] AS [m6] ON [m].[Id] = [m6].[Id]
WHERE [m].[Id] = @__menuId_0
``` 

With a discriminator, maybe EF can create a shortcut and just query `MenuItemReport` without the JOINs for example.

**Comment by gumbarros** [comment]
> [@gumbarros](https://github.com/gumbarros) So then you are suggesting that we translate your single LINQ query into two SQL queries with two round-trips to the database?

If the benchmarks show that it's more effective, yes.

But the biggest reason to have the discriminator column for TPT is in reports that query the base type table to show what type the entity is without lots of LEFT joins.

**Comment by roji** [comment]
> But the biggest reason to have the discriminator column for TPT is in reports that query the base type table to show what type the entity is without lots of LEFT joins.

The question is, in what querying scenarios would this be helpful **other** than when you split your LINQ query into two SQLs as you suggested above. If you have anything else in mind please go ahead and post it.

Re splitting the query, doing two roundtrips can have quite a bit of overhead - but then so can a bunch of unnecessary left joins; what's better is going to depend on lots of factors (network latency, data in the joined table...). In theory there could be scenarios where splitting to get the discriminator first would make sense, but the user would have to make that decision (since in some cases it's a great idea, in others it's a terrible one); and I'm not sure this kind of decision-making is something we'd want to burden the user with. 

Compare this with the regular query splitting that EF already supports, to avoid cartesian explosion with collection joins: here the decision generally seems more straightforward, being a pure function of the cardinality in the joined table. In that case it's sometimes possible to batch the two queries (depending on the style of query splitting), whereas with the proposed TPT splitting that's not possible.

To summarize, I can definitely see TPT scenarios where an opt-in here could help, and some advanced user might be happy to take advantage of it (as a somewhat niche feature). But overall, TPT as an inheritance strategy will remain problematic in terms of performance and joins. Even if we implement the above, most queries would still need to perform a large number of joins; for example, if you simply query without filtering on the type, all tables must be consulted anyway (whereas with TPH there's just one table).

In other words, if you've chosen TPT, you've opted into what is largely an inefficient way to model your data in the database; sure, the above suggestion can mitigate that **for some scenarios** - and **only** when the query filters on the type - but doesn't change the basic inefficient modeling of TPT. If performance and JOIN avoidance is a priority, I'd highly recommend considering a different inheritance strategy; TPH may have its own disadvantages (e.g. lots of empty columns), but I'd recommend mitigating those rather than trying to get TPT to be more efficient.

**Comment by gumbarros** [comment]
> > But the biggest reason to have the discriminator column for TPT is in reports that query the base type table to show what type the entity is without lots of LEFT joins.
> 
> The question is, in what querying scenarios would this be helpful **other** than when you split your LINQ query into two SQLs as you suggested above. If you have anything else in mind please go ahead and post it.
> 
> Re splitting the query, doing two roundtrips can have quite a bit of overhead - but then so can a bunch of unnecessary left joins; what's better is going to depend on lots of factors (network latency, data in the joined table...). In theory there could be scenarios where splitting to get the discriminator first would make sense, but the user would have to make that decision (since in some cases it's a great idea, in others it's a terrible one); and I'm not sure this kind of decision-making is something we'd want to burden the user with.
> 
> Compare this with the regular query splitting that EF already supports, to avoid cartesian explosion with collection joins: here the decision generally seems more straightforward, being a pure function of the cardinality in the joined table. In that case it's sometimes possible to batch the two queries (depending on the style of query splitting), whereas with the proposed TPT splitting that's not possible.
> 
> To summarize, I can definitely see TPT scenarios where an opt-in here could help, and some advanced user might be happy to take advantage of it (as a somewhat niche feature). But overall, TPT as an inheritance strategy will remain problematic in terms of performance and joins. Even if we implement the above, most queries would still need to perform a large number of joins; for example, if you simply query without filtering on the type, all tables must be consulted anyway (whereas with TPH there's just one table).
> 
> In other words, if you've chosen TPT, you've opted into what is largely an inefficient way to model your data in the database; sure, the above suggestion can mitigate that **for some scenarios** - and **only** when the query filters on the type - but doesn't change the basic inefficient modeling of TPT. If performance and JOIN avoidance is a priority, I'd highly recommend considering a different inheritance strategy; TPH may have its own disadvantages (e.g. lots of empty columns), but I'd recommend mitigating those rather than trying to get TPT to be more efficient.

Thanks for the detailed response, I will talk with my team about your points and see if its worth migrating from TPT to TPH. Feel free to close the issue if the discriminator column is out of scope for future versions.

**Comment by roji** [comment]
Sure thing - thanks for proposing this and engaging. I'll indeed go ahead and close this as this most likely isn't something we'll be implementing; however, we're interesting in any other feedback/insights around this, and we can always revisit if other arguments are made or many other users request this.
