### ISSUE TITLE
Scaffolding with required modifier for nullable enabled projects

### ISSUE THREAD

**Issue by 5andr0** [dotnet/efcore#35291]
Can you please implement the required modifier for scaffolding db models?
Nullable enabled projects are quite standard now but required modifier is not yet available when scaffolding.

If you implement it, please drop the required modifier for non null db generated fields, that have ValueGenerated.OnAdd

As a workaround I modded EntityType.t4 with following lines:

```
        var needsNullable = Options.UseNullableReferenceTypes && property.IsNullable && !property.ClrType.IsValueType;
        var needsRequired = Options.UseNullableReferenceTypes && !property.IsNullable && !property.ValueGenerated.HasFlag(ValueGenerated.OnAdd);
#>
    public <#= needsRequired ? "required " : "" #><#= code.Reference(property.ClrType) #><#= needsNullable ? "?" : "" #> <#= property.Name #> { get; set; }
```

It probably doesn't cover all cases, but is sufficient for me

**Comment by cincuranet** [comment]
@5andr0 Required and NRT are two unrelated features. I'm not sure how we could detect `required` when scaffolding from database. Can you give me some ideas?

Looking at your `var needsRequired = Options.UseNullableReferenceTypes && !property.IsNullable && !property.ValueGenerated.HasFlag(ValueGenerated.OnAdd);` I don't think it is correct. For example, I can have nullable property and still want `required` modifier on it. And not sure what role `ValueGenerated.OnAdd` plays there.

**Comment by 5andr0** [comment]
> [@5andr0](https://github.com/5andr0) Required and NRT are two unrelated features.

I know, I just combined the needsRequired check for convenience in my case, just to give an idea. If you implement it, please separate.

> I'm not sure how we could detect required when scaffolding from database. Can you give me some ideas?
> 
> Looking at your `var needsRequired = Options.UseNullableReferenceTypes && !property.IsNullable && !property.ValueGenerated.HasFlag(ValueGenerated.OnAdd);` I don't think it is correct. For example, I can have nullable property and still want `required` modifier on it. And not sure what role `ValueGenerated.OnAdd` plays there.


Using required should be an argument option of the scaffolding command. You can also check there if the c# version supports it.  
The whole idea behind `required` is to make sure your IDE gives warnings, when you try to add a new model instance without setting a non nullable field. This was not the case so far with the current implementation of setting all properties to `null!`.  

So I don't understand the statement why you'd want to have a required mod on a db nullable property. That's a custom case and people can add the required mod however they see fit after code generation.  

But for scaffolding it should only make non nullable fields required.  

The role of `ValueGenerated.OnAdd` is for db non nullable properties with default values or auto increments.
So lets say auto generated identity PKs are non nullable and would receive the required mod, but the required mod is not desired/necessary because the property is generated by the db if set to null.

**Comment by cincuranet** [comment]
> But for scaffolding it should only make non nullable fields required.

Do you think making all (minus database generated) non nullable properties required on all entities using a command line switch is a worthy idea compared to already having an option of customizing the template? Just command line switch is probably going to be too coarse and adding more fine grained tuning is not significantly easier than editing the template, especially given the template gives you almost infinite flexibility.

Can you elaborate more on your scenario?

**Comment by 5andr0** [comment]
> > But for scaffolding it should only make non nullable fields required.
> 
> Do you think making all (minus database generated) non nullable properties required on all entities using a command line switch is a worthy idea compared to already having an option of customizing the template? Just command line switch is probably going to be too coarse and adding more fine grained tuning is not significantly easier than editing the template, especially given the template gives you almost infinite flexibility.
> 
Yeah I think it's a worthy idea. Required mod has become standard now and should therefore definitely be integrated to be used easily, like setting a cli switch or config file entry.
I don't think it's too coarse, because the use case is always the same for non nullable fields except auto generated ones.
Having fine tuneable t4 is nice, but adds significant research time and frustration!


> Can you elaborate more on your scenario?

Let's say we have following postgres table:
```pgsql
CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text NOT NULL,
    mail text
)
```

The default scaffolded model would be this:

```csharp
public class User
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public string? Mail { get; set; } = null!;
}
```

Now when inserting new values we can do this:
`db.Users.Add(new User { })`
This compiles without any warning and will result in a runtime exception when the non nullable property name is not set.

With the required mod on and dropping the default null! initializer:
```csharp
public class User
{
    public int Id { get; set; } // required not set because it's db generated, even though the property is NOT NULL
    public required string Name { get; set; };
    public string? Mail { get; set; }; // ? should still be set with nullable ref types, but the null! initializer can be dropped
}
```
Now the compiler warns us that Name is not set and forces us to initialize it:
`db.Users.Add(new User { Name = "TestUser" })`

I think this is crucial and using required should be gold standard

**Comment by ajcvickers** [comment]
#28400

**Comment by cincuranet** [comment]
Thanks @ajcvickers. I knew such issue surely exists, I just wasn't able to find it.

**Comment by 5andr0** [comment]
> [#28400](https://github.com/dotnet/efcore/issues/28400)

@cincuranet Sorry for also not seeing that issue, but it was discussed when the required modifier was brand new.
Now it's widely used and should be reconsidered. I would like to see more discussion. Some input from @roji maybe?
Doesn't have to be default, but at least as an option. Efcore should comply with new C# features

Using required is definitely the recommended way now to use with db models and the user shouldn't have to research how to use t4 to implement this

**Comment by cincuranet** [comment]
Can you point me to such recommendation?
