### ISSUE TITLE
Unable to cast and similar exceptions should include property and entity name when feasible.

### ISSUE THREAD

**Issue by danroot** [dotnet/efcore#35306]
As a developer working with a large EF Core db context and complex queries, I would like EFCore exceptions to include the name of the entity and property that the exception is related to whenever possible, so that I can more quickly debug issues.

As one example, I have a EF query like this:

```
   var commissionDetails = db.CommissionDetails
          .Include(x => x.Commission).Include(x => x.Salesperson).Include(x => x.SalespersonStore)
          .Where(x => x.Commission.InventoryItem.Id == inventoryItemAfterUpdate.Id && !x.IsDeleted && !x.Commission.IsDeleted).ToList();
```
Somehow the model and the db schema got out of sync (how is not important for scope of this issue - I'm sure it's my fault and will debug).  When this query runs, I get this exception:

```
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
    at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method11935(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

As it stands, I have to go through every field on CommissionDetails, Commission, SalesPerson, SalespersonStore and guess which is the problem, then tinker until I figure out the culprit.   I might debug and get the executed sql to help, but still don't know exactly what is the culprit.  On large entities, this can be pretty time consuming, and it seems like both entity and property name are things EF already knows or could know at the point this exception is thrown.  Debugging this could be made _so_ much easier if the entity and property were included in the exception message, something like:

```
DbQueryException: Unable to cast object of type 'System.Int32' to type 'System.String' for property Foo on entity CommissionDetail
  at lambda_method11935(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
...with an innerexception that contains the original issue.

In this case, the issue is a LINQ query, but similar can obviously occur in SqlRaw queries and certain db updates.

**Comment by ajcvickers** [comment]
@danroot You can use [EnableDetailedErrors](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#getting-detailed-messages) for this. See also #30397 and #23038

**Comment by danroot** [comment]
Ah, of course.  Thanks- this gets me past the immediate need and looks like a duplicate.  Closing.
