### ISSUE TITLE
[Q] Map JSON column to both string and strongly-typed data

### ISSUE THREAD

**Issue by lonix1** [dotnet/efcore#35313]
I already [asked on StackOverflow](https://stackoverflow.com/q/79265234/9971404) without resolution.

## Ask a question

A `Person` entity:
```cs
public class Person     // the entity
{
  // both of these properties should refer to same jsonb column
  public string ContactsJson { get; }
  public Contacts Contacts { get; }
}

public class Contacts   // for binding JSON
{
  public string Tel { get; }
  public string Fax { get; }
}
```

One can map the JSON column to a string:
```cs
modelBuilder.Entity<Person>()
  .Property(x => x.ContactsJson)
  .HasColumnType("jsonb")
  .IsRequired();
```

One can map the JSON column to [strongly-typed data](https://learn.microsoft.com/en-gb/ef/core/what-is-new/ef-core-7.0/whatsnew#mapping-to-json-columns):
```cs
modelBuilder.Entity<Person>()
  .OwnsOne(x => x.Contacts, b => {
    b.ToJson();
    b.Property(c => c.Tel).IsRequired();
    b.Property(c => c.Fax).IsRequired(false);
  });
```

If one uses both of those snippets then obviously EF will create two columns. But I want just one jsonb column, `Contacts`, which is mapped to both a string and strongly-typed data.

Is that possible?

Also, I assume having two properties refer to the same column can cause issues if I update one property and not the other. How does one deal with that scenario?

### Include provider and version information

EF Core version: 8
Database provider: Postgres
Target framework: NET 8
Operating system: linux
IDE: vscode

**Comment by ajcvickers** [comment]
@lonix1 This not possible with EF8/9. It might be supported in the future using complex types, but I think that is quite unlikely.

**Comment by roji** [comment]
One possible way to achieve that today is to map the string property to a computed column which simply returns the other column.

**Comment by roji** [comment]
PostgreSQL doesn't currently support non-stored computed columns unfortunately... If you really want to, you can define an updatable view over the table which adds the virtual column, and then tell EF to map to that view instead. That should give you the same effect.
