### ISSUE TITLE
Unneeded sorted subquery with Skip()

### ISSUE THREAD

**Issue by rgroenewoudt** [dotnet/efcore#35316]
When I have a query that does a OrderBy() combined with a Take(), EFCore generates an unneeded subquery with additional sort, resulting in 2 times ORDER BY. This has a negative impact on performance and breaks queries on large tables.

```
context.Test
            .Select(x => new
            {
                x.TestID,
                x.Name,
                Category = x.Category.Name
            })
            .OrderByDescending(x => x.TestID)
            .Take(10)
```
results in
```
SELECT [t0].[TestID], [t0].[Name], [c].[Name] AS [Category]
  FROM (
      SELECT TOP(@__p_0) [t].[TestID], [t].[CategoryID], [t].[Name]
      FROM [Test] AS [t]
      ORDER BY [t].[TestID] DESC
  ) AS [t0]
  INNER JOIN [Category] AS [c] ON [t0].[CategoryID] = [c].[CategoryID]
  ORDER BY [t0].[TestID] DESC
```

Expected SQL:
```
SELECT TOP(@__p_0) [t].[TestID], [t].[Name], [c].[Name] AS [Category]
FROM [Test] AS [t]
INNER JOIN [Category] AS [c] ON [t].[CategoryID] = [c].[CategoryID]
ORDER BY [t].[TestID] DESC
``` 

Using latest EFCore 9 with SQL Server 2022.

Minimum project for reproduction [EFCore9Bug.zip](https://github.com/user-attachments/files/18096607/EFCore9Bug.zip)

Are there any known workarounds?

**Comment by roji** [comment]
Unfortunately there are no workarounds for this; we indeed intend to work on improving SQL quality in cases like this, but at the moment that's the SQL that EF generates.

I'm actually curious that this specific case would produce a big perf regression: can you please post the plans for the two SQLs?
