### ISSUE TITLE
EF8/EF9 Bug - cannot update database including migrations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#35344]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF8EF9-Bug---cannot-update-database-inc/10798134)._

---
[regression]
An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'AppDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

---
#### Feedback Bot on 11/24/2024, 08:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by Penetrasyoncu** [comment]
Hello, I updated to EF Core 9 version, but the problem persists.

**Comment by roji** [comment]
@Penetrasyoncu please see #35285 for more information on this error, what it means and how it can be mitigated. If you think you have a case that isn't covered by this, please open a new issue with a minimal, runnable repro.
