### ISSUE TITLE
Column name mismatch when adding new derived type to TPH

### ISSUE THREAD

**Issue by tjaz-brelih** [dotnet/efcore#35352]
When a new derived type with an identical property to an existing derived type is added to `DbContext`, migration will incorrectly handle the duplicated property.

### Steps to reproduce

Consider the following simplified model and context:
```C#
public class ModelBase
{
    public int Id { get; set; }
}

public class ModelA : ModelBase
{
    public string? T { get; set; }
}
```

```C#
public class Context : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<ModelBase>().ToTable("Models");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer(ConnectionString);
    }

    public DbSet<ModelA> ModelsA { get; set; }
}
```

The initial migration for above configuration creates three database columns: `Id`, `Discriminator` and `T`.
Below is the relevant `ModelA` configuration snippet from `ContextModelSnapshot.cs`:

```C#
modelBuilder.Entity("EfCoreInheritanceBug.ModelA", b =>
{
    b.HasBaseType("EfCoreInheritanceBug.ModelBase");

    b.Property<string>("T")
        .HasColumnType("nvarchar(max)");

    b.HasDiscriminator().HasValue("ModelA");
});
```

Later we create another model and add it to our `DbContext`.
**The new model contains the same property T as `ModelA` (same property name and type):**

```C#
public class ModelB : ModelBase
{
    public string? T { get; set; }
}
```

```C#
public DbSet<ModelB> ModelsB { get; set; }
```

With new model created and added as `DbSet` to our context we create a new migration. The newly created migration contains the following:

```C#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AddColumn<string>(
        name: "ModelA_T",
        table: "Models",
        type: "nvarchar(max)",
        nullable: true);
}
```

The relevant portion of the updated `ContextModelSnapshot`:

```C#
modelBuilder.Entity("EfCoreInheritanceBug.ModelA", b =>
{
    b.HasBaseType("EfCoreInheritanceBug.ModelBase");

    b.Property<string>("T")
        .HasColumnType("nvarchar(max)");

    b.ToTable("Models", t =>
        {
            t.Property("T")
                .HasColumnName("ModelA_T");
        });

    b.HasDiscriminator().HasValue("ModelA");
});

modelBuilder.Entity("EfCoreInheritanceBug.ModelB", b =>
{
    b.HasBaseType("EfCoreInheritanceBug.ModelBase");

    b.Property<string>("T")
        .HasColumnType("nvarchar(max)");

    b.HasDiscriminator().HasValue("ModelB");
});
```

Before the second migration `ModelA` used column `T` to store and read data for property `ModelA.T`.
After the second migration a new column named `ModelA_T` is created and is mapped to `ModelA.T`. The existing column `T` is mapped to `ModelB.T`.

This leads to incorrect data mapping for all database rows inserted before the second migration was created.

### Workaround
To keep `ModelA.T` mapped to column `T` we can explicitly set column name for the property in `OnModelCreating` before creating the second migration:
```C#
modelBuilder.Entity<ModelA>().Property(x => x.T).HasColumnName("T");
```

The migration will then create a new column `ModelB_T` and properly map it to `ModelB.T`.

We could also move property `T` to `ModelBase` or configure it as a shared column.

### Additional information

EF Core version: 9.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 9.0
Operating system: Windows 11 23H2
IDE: Visual Studio 2022 17.12.3

**Comment by roji** [comment]
Confirmed, see simplified repro below.

I'm not sure what exactly we can do here, since EF builds the target model (with ModelsB) without any knowledge of the source model (the past), so cannot take the previous existence of ModelsA (and non-existence of ModelsB) into account when mapping properties to columns... @AndriySvyryd have we seen this before, any ideas?

<details>
<summary>Minimal repro</summary>

```c#
await using var context = new Context();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

public class Context : DbContext
{
    public DbSet<ModelA> ModelsA { get; set; }
    
    // Uncomment the following for the 2nd migration:
    // public DbSet<ModelB> ModelsB { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ModelBase>().ToTable("Models");
    }
}

public class ModelBase
{
    public int Id { get; set; }
}

public class ModelA : ModelBase
{
    public string? T { get; set; }
}

public class ModelB : ModelBase
{
    public string? T { get; set; }
}
```

</details>

**Comment by AndriySvyryd** [comment]
This is a known limitation, though I don't think we've documented it explicitly. The workaround above is the recommended way of handling it.
