### ISSUE TITLE
Modifying elements in a foreach loop

### ISSUE THREAD

**Issue by Mr0N** [dotnet/efcore#35364]
Why can't normalize the execution of such code to allow modifying elements in a foreach loop during iteration?
The database is too large, and downloading, for example, a million elements using ToList is not feasible.
For instance, could we add a feature to SaveChanges that generates a new connection and updates the database using that new connection, or implement something similar

```


namespace Service
{
    public class Main(InfoDbContext dbContext) : IMain
    {

        public void Execute()
        {

            var response = dbContext.Table.Where(a => a.UpdateTitleInfo != null);
            Console.WriteLine("Start");
            int count = 0;
            foreach (var item in response)
            {

                Console.WriteLine($"Title:{count++}");
                item.Title = "text";
                dbContext.SaveChanges();
            }
    
        }
    }
}

```

**Comment by roji** [comment]
@Mr0N I can't understand from the above what it is that you're asking for - what does "normalize the execution of such code" mean? What exact API are you looking for?

**Comment by Mr0N** [comment]
> [@Mr0N](https://github.com/Mr0N) I can't understand from the above what it is that you're asking for - what does "normalize the execution of such code" mean? What exact API are you looking for?

To be able to set when creating a DbContext instance the number of connections that the instance can create to the database, if for example two connections are set, then when foreach does in the example above. EF did not throw an error, but opened this one connection and updated the database

**Comment by Mr0N** [comment]
Well, like, it’s possible to open another connection and update the database if one connection is currently busy.

**Comment by roji** [comment]
@Mr0N if we did that, your code as it looks above would suffer from the N+1 problem: it would do a database roundtrip for each and every item it queries, resulting in very bad performance.

Your options are:
* Use ExecuteUpdateAsync to update everything in the database without loading it at all. [See these docs](https://learn.microsoft.com/en-us/ef/core/saving/) to understand how ExecuteUpdate and SaveChanges compare to each other. If ExecuteUpdateAsync if possible, that's the ideal, best-performing solution.
* Do ToList() in your query, to load all the rows from the database before you start saving changes. As you've noted, this approach can be problematic if you have a really huge number of rows in the database - but in many cases is perfectly OK.
* Otherwies, have two DbContexts, using one for the querying, and then attaching and each entity to the other one, marking the  changes.

No matter what you do, it's highly recommend to not perform SaveChanges for each row, but rather to accumulate all changes and then save them via one SaveChanges batch.

I'll go ahead and close this issue as the question has been answered, but if you have further thoughts/questions you can continue posting here.

**Comment by Mr0N** [comment]
> [@Mr0N](https://github.com/Mr0N) if we did that, your code as it looks above would suffer from the N+1 problem: it would do a database roundtrip for each and every item it queries, resulting in very bad performance.

I changed the code like this, but it’s not very pleasant to write such code. It would be easier to just write a "foreach" and modify the data. As for SaveChanges on each iteration, that was just for an example.

![Image](https://github.com/user-attachments/assets/e0a27e84-8d41-42f6-8ef7-b55e004ec866)

**Comment by Mr0N** [comment]
> would suffer from the N+1 problem

Well, now there is the same load on the database, a lot of updates that change the data in the database

**Comment by roji** [comment]
@Mr0N as I wrote above, this looks like an ideal case for ExecuteUpdateAsync, something like:

```c#
await dbContext
    .Where(a => a.UpdatetitleInfo != null)
    .ExecuteUpdateAsync(s => s.SetProperty(a => a.Title, "NewTitle");
```

Otherwise, if some reason you can't use ExecuteUpdateAsync (which really is the best and most efficient solution), then depending on what exactly you're doing, you should be able to use a single context as follows:

```c#
foreach (var item in context1.Blogs)
{
    item.Title = "foo";
}

await context1.SaveChangesAsync();
```

This streams the database rows, marks each one for a change, and then saves all changes in a single batch at the end. Note that EF ends up keeping all the rows in memory, since the query is a tracking query. If that's too much and you want to do multiple batches, then you can do more or less what your code sample above shows - but take a look at the [pagination docs](https://learn.microsoft.com/en-us/ef/core/querying/pagination) for a more efficient way to do this (Skip and Take are generally not efficient).

**Comment by Mr0N** [comment]
> [@Mr0N](https://github.com/Mr0N) as I wrote above, this looks like an ideal case for ExecuteUpdateAsync, something like:
> 
> await dbContext
>     .Where(a => a.UpdatetitleInfo != null)
>     .ExecuteUpdateAsync(s => s.SetProperty(a => a.Title, "NewTitle");
> Otherwise, if some reason you can't use ExecuteUpdateAsync (which really is the best and most efficient solution), then depending on what exactly you're doing, you should be able to use a single context as follows:
> 
> foreach (var item in context1.Blogs)
> {
>     item.Title = "foo";
> }
> 
> await context1.SaveChangesAsync();
> This streams the database rows, marks each one for a change, and then saves all changes in a single batch at the end. Note that EF ends up keeping all the rows in memory, since the query is a tracking query. If that's too much and you want to do multiple batches, then you can do more or less what your code sample above shows - but take a look at the [pagination docs](https://learn.microsoft.com/en-us/ef/core/querying/pagination) for a more efficient way to do this (Skip and Take are generally not efficient).

Well, the problem with doing ExecuteUpdateAsync is that half of the program logic is executed by the C# program code, that is, the program generates information that needs to be written to the database.

**Comment by Mr0N** [comment]
> > [@Mr0N](https://github.com/Mr0N) as I wrote above, this looks like an ideal case for ExecuteUpdateAsync, something like:
> > await dbContext
> > .Where(a => a.UpdatetitleInfo != null)
> > .ExecuteUpdateAsync(s => s.SetProperty(a => a.Title, "NewTitle");
> > Otherwise, if some reason you can't use ExecuteUpdateAsync (which really is the best and most efficient solution), then depending on what exactly you're doing, you should be able to use a single context as follows:
> > foreach (var item in context1.Blogs)
> > {
> > item.Title = "foo";
> > }
> > await context1.SaveChangesAsync();
> > This streams the database rows, marks each one for a change, and then saves all changes in a single batch at the end. Note that EF ends up keeping all the rows in memory, since the query is a tracking query. If that's too much and you want to do multiple batches, then you can do more or less what your code sample above shows - but take a look at the [pagination docs](https://learn.microsoft.com/en-us/ef/core/querying/pagination) for a more efficient way to do this (Skip and Take are generally not efficient).
> 
> Well, the problem with doing ExecuteUpdateAsync is that half of the program logic is executed by the C# program code, that is, the program generates information that needs to be written to the database.

And if, for example, you change one object, the object is updated in the database through an Update request, if you change 10 thousand objects, you get 10 thousand update requests, this is the problem, it turns out that you need to execute 10 thousand requests to change 10 thousand strings, this request that I propose will be generated once and the database will normalize it and execute it many times faster than it does now, in fact, it executes “Where” 10 thousand times, when you can do it once
