### ISSUE TITLE
Using `.Count` on a `ICollection<T>` does not produce `EXISTS` as it does when using `List<T>`

### ISSUE THREAD

**Issue by alaatm** [dotnet/efcore#35365]
In the whats new in .net 9, it says that queries using `.Count` are now optimized to use `EXISTS` instead of `COUNT`. However, this seems to be true for collections of type `List<T>`. We use `ICollection<T>` in our projects and we would love to replace `.Any()` with `.Count > 0` but this optimization isn't applied as shown below

```C#
public class Blog
{
    public int Id { get; set; }
    public ICollection<Post> Posts { get; set; } = default!;
}

public class Post
{
    public int Id { get; set; }
}

context.Blogs.Where(b => b.Posts.Count > 0);
```

produces:

```SQL
SELECT [b].[Id]
FROM [Blogs] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [Post] AS [p]
    WHERE [b].[Id] = [p].[BlogId]) > 0
```

Using `context.Blogs.Where(b => b.Posts.Count != 0);` will make it even worse:

```SQL
SELECT [b].[Id]
FROM [Blogs] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [Post] AS [p]
    WHERE [b].[Id] = [p].[BlogId]) <> 0 OR (
    SELECT COUNT(*)
    FROM [Post] AS [p]
    WHERE [b].[Id] = [p].[BlogId]) IS NULL
```

EF Core version: 9.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by roji** [comment]
@cincuranet interested in giving this a look?

**Comment by ChrisJollyAU** [comment]
@roji See `QueryableMethodNormalizingExpressionVisitor` line 73/74

https://github.com/dotnet/efcore/blob/f16328984e1d514a846b7ccd5c52b367b1f50337/src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs#L73

`GetInterfaces` only gets those inherited/implemented. Normally fine but if the type is also an interface that is NOT returned as part of the list. So in this case `member.DeclaringType` is an `ICollection`, however `GetInterfaces` only returns `IEnumerable` and its generic version.

Changing that section to the following should do the trick
```
when (member.DeclaringType.GetGenericTypeDefinition() == typeof(ICollection<>) || member.DeclaringType.GetGenericTypeDefinition().GetInterfaces().Any(
    x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(ICollection<>)))
```

**Comment by roji** [comment]
@ChrisJollyAU thanks for looking into it... Are you interested in submitting a PR?

**Comment by ChrisJollyAU** [comment]
Sure. I haven't got a test sorted yet so will do that sometime

**Comment by roji** [comment]
@ChrisJollyAU if we have other changes that already ensure this won't regress, then no, I think it's fine to submit without an additional test.
