### ISSUE TITLE
WeakReference Class

### ISSUE THREAD

**Issue by Mr0N** [dotnet/efcore#35388]
I propose modifying the implementation of ChangeTracker to use the WeakReference class for storing references to objects. Currently, the GC cannot clean up objects that are otherwise inaccessible because EF Core holds strong references to them.

The ChangeTracker is designed to track changes in objects and write those changes to the database. If an object is no longer accessible anywhere in the system except through EF Core, it cannot be modified, but it can be  removed.

The GC removes objects that have no references anywhere and cannot be modified.

https://learn.microsoft.com/en-us/dotnet/api/system.weakreference?view=net-7.0
```
  public void Test()
  {
      foreach (var item in Enumerable.Range(0, 1000000)
                                     .Select(a => new Link() { Uri = a.ToString() }))
      {
          dbContext.Links.Add(item);//this link is not available for the code, now it can only be obtained from EF and cannot be changed anymore
      }
      //But it's not deleted from memory, because EF keeps a link to it
      dbContext.SaveChanges();
  }

```

```
class Test<T> where T : class
{
    public T ValueObj { get=> Value?.Target as T; set => Value = new WeakReference(value); }
    public WeakReference Value { get; set; }
}
```

**Comment by Mr0N** [comment]
Well, yes, there is a problem that everything needs to be saved to the database after SaveChanges. But you can store the data in two fields: one normal and the other as a WeakReference object. After saving, you can remove the regular reference and keep only the WeakReference.

**Comment by Mr0N** [comment]
It would be possible to add an option in EF Core settings to specify whether to use WeakReference or the standard EF Core logic.

**Comment by roji** [comment]
> The ChangeTracker is designed to track changes in objects and write those changes to the database. If an object is no longer accessible anywhere in the system except through EF Core, it cannot be modified, but it can be removed.

That's incorrect. It's perfectly valid, for example, to Add a new object (i.e. schedule it for insertion for the next SaveChanges), and then not have any reference to it (beyond the reference from EF's change tracking). For example, consider the following code:

```c#
for (var i = 0; i < 10; i++)
{
    context.Add(new Blog { Name = "Blog" + i });
}

await context.SaveChangesAsync();
```

The above snippet - which is very basic and common - simply inserts ten blogs into the database. If EF's change tracking used weak references, the above would no longer work.

**Comment by Mr0N** [comment]
Well, it really won't work very well. Ideally, this would work properly if, during SaveChanges, it were possible to determine whether any other objects still have a reference to this object. If no one else has a reference, it could be deleted. But in .NET, I don’t know how to determine whether other objects still have references to the object in the ChangeTracker.

**Comment by roji** [comment]
I think you have an incorrect mental model here. The instances tracked by EF are accessible to users, and some people use this; for example, you may insert some objects into the database - without having any additional reference to them - and after doing SaveChanges, access them via the change tracker ([see docs](https://learn.microsoft.com/en-us/ef/core/change-tracking/entity-entries)) and then e.g. do another SaveChanges.

In other words, the fact that someone does SaveChanges does **not** mean that the objects are no longer needed and can be garbage collected. The context continues tracking them by-design, and additional operations with the same context and its tracked objects can be done.

Ordinarily, none of this is needed: once you do SaveChanges, you can simply dispose your DbContext and then remove the reference to it; at that point, the context and everything it tracks becomes unreachable, and can get garbage collected. If you really don't need the tracked objects after SaveChanges, simply dispose the context and everything works well.

If you do want to keep the context for some reason but get rid of the tracked objects, you can call `context.ChangeTracker.Clear()` to do that explicitly (though again, we generally recommend disposing the context).

**Comment by Mr0N** [comment]
> **t** mean that the objects are no longer needed and can be garbage collected

Well, if it's not accessible anywhere, then it's not needed; it can't be changed or interacted with in any way.

**Comment by Mr0N** [comment]
> Ordinarily, none of this is needed: once you do SaveChanges,

Well, it depends on the task. If it’s an ASP.NET Core application, then yes. But if it’s some other program that modifies or changes the database, it’s not that simple to remove contexts. You’d need to write a lot of code for that.

**Comment by ErikEJ** [comment]
@Mr0N Why.? You can use standard .NET Dependency injection with any type of app.

**Comment by roji** [comment]
> Well, if it's not accessible anywhere

The objects **are** accessible - read [the doc page](https://learn.microsoft.com/en-us/ef/core/change-tracking/entity-entries) I linked to earlier.

**Comment by Mr0N** [comment]
> , you can call context.ChangeTracker.Clear() to clear the change tracker.

Yes, but it's so inconvenient: forgot to clear it, and the PC's RAM is already full.

**Comment by Mr0N** [comment]
> [@Mr0N](https://github.com/Mr0N) Why.? You can use standard .NET Dependency injection with any type of app.

I constantly use DI, but there are, for example, small applications where it simply doesn't make sense to use it. Well, there are different kinds of applications.

**Comment by roji** [comment]
> the PC's RAM is already full

It's not "already full" - it simply continues holding on the references from before the SaveChanges, until the context is disposed - that  really should happen very quickly afterwards in any case. There's no increased memory usage, only that the memory can be garbage collected slightly after SaveChangesAsync instead of immediately,

> I constantly use DI, but there are, for example, small applications where it simply doesn't make sense to use it. Well, there are different kinds of applications.

If you're not using DI, things are even simpler: you directly control when the context is created and disposed in your code:

```c#
await using (var context = new MyContext())
{
    // ... do stuff
    await context.SaveChangesAsync();
} // disposal happens here, everything can be garbage-collected - just after calling SaveChangesAsync
```

**Comment by roji** [comment]
> Well, here you also need to add a connection string to the database, and maybe a bunch of other settings. Sure, you could create another method where everything is initialized. But the downside is that it will probably keep opening a new connection to the database every time.

That's why you should have a factory of DbContexts (IDbContextFactory) - it already contains the connection string and other options, and can also do pooling for better performance. Just have the factory available wherever you need a context, create one and then immediately dispose it.
