### ISSUE TITLE
EF.Commands does not work on WinRT types

### ISSUE THREAD

**Issue by mtycholaz** [dotnet/efcore#3543]
Create a Universal Windows **class library** project and paste this into a file

```
public class MyContext : DbContext
    {
        public DbSet<Message> Messages { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string databaseFilePath = "test.db";
            try
            {
                databaseFilePath = Path.Combine(ApplicationData.Current.LocalFolder.Path, databaseFilePath);
            }
            catch (InvalidOperationException)
            { }

            optionsBuilder.UseSqlite($"Data source={databaseFilePath}");

        }
    }

    public class Message : IMessage
    {
        public string Name { get; set; }
    }
```

Add a new Universal Windows **Runtime Component** project to your solution. Add this code to a file

```
public interface IMessage
    {
        string Name { get; set; }
    }
```

Build and compile, then try to run the `add-migration "mymigration"` command from powershell window. Should be greeted by this error `System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

You can change the output type of the **Windows Runtime Component** to **Class Library** and then everything works fine.

Here's the JSON file

```
{
  "dependencies": {

    "EntityFramework.Commands": "7.0.0-beta8",
    "EntityFramework.SQLite": "7.0.0-beta8",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by rowanmiller** [comment]
@natemcmaster to dig into this and make a recommendation

**Comment by natemcmaster** [comment]
Windows Runtime (WinRT) Components compile to a winmd file, which is not the same thing as a .NET assembly. Metadata from a WinRT component can only be fetched through COM interfaces. Currently, EF.Commands only reads .NET assemblies. 

However, we could improve commands to handle this case with a better error message. Stack trace:
```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Data.Entity.Design.DbContextOperations.GetContextTypes() in \ef\src\EntityFramework.Commands\Design\DbContextOperations.cs:line 88
```

**Comment by bricelam** [comment]
This is similar to #1058

**Comment by rowanmiller** [comment]
We decided we are not going to try and support this yet. If we get customer feedback that this is important then we will consider supporting it in the future.
