### ISSUE TITLE
Generic Collection Table naming convention

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#3544]
I have tested out generic collection with the following code and see the weird name on the table generated up in sql like: `Progress<Risk>` for the table name. Is this by design or just by luck?
![generix-collection](https://cloud.githubusercontent.com/assets/10666633/10709277/be75aa38-7a50-11e5-9ed8-89f12b3de2d6.png)

```
public class Program
{
    public void Main(string[] args)
    {
        var context = new GenericCollectionContext();
        var card = new Card();
        card.Risk.Add(new Progress<Risk>() { State = Risk.High });
        card.State.Add(new Progress<State>() { State = State.New });
        context.Cards.Add(card);
        context.SaveChanges();
    }
}

public class GenericCollectionContext : DbContext
{
    public DbSet<Card> Cards { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=GenericCollection;Trusted_Connection=True;");
    }
}

public class Card
{
    public int Id { get; set; }
    public Collection<Progress<State>> State { get; set; } = new Collection<Progress<State>>();
    public Collection<Progress<Risk>> Risk { get; set; } = new Collection<Progress<Risk>>();
}

public class Progress<T>
{
    // Waiting for complex type
    public int Id { get; set; }
    public T State { get; set; }
    public DateTime Stamp { get; set; } = DateTime.Now;
}
public enum State
{
    Active,
    Closed,
    New,
    Removed,
    Resolved
}
public enum Risk
{
    Low,
    Medium,
    High
}
```

But I have to say that the c# programming paradigm logic work as expected.

**Comment by divega** [comment]
I believe it is all by-design. Starting on the only DbSet in your DbContext we walk the graph and find two generic entity types. The table names are based on the simple names of the CLR types of those entities.

**Comment by rowanmiller** [comment]
I agree... I'm actually kind of impressed that this flows through the stack so well :smile:. Given they are valid names for the table I don't think we need to do anything special.
