### ISSUE TITLE
From_sql_queryable_simple_projection_composed isn't portable

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3548]
It sends the following SQL:

``` sql
SELECT *
FROM Products
WHERE Discontinued <> 1
AND ((UnitsInStock + UnitsOnOrder) < ReorderLevel)
```

PostgreSQL issues:
- Identifiers must be quoted (to preserve case)
- Discontinued is a bool, which needs to be checked with `= TRUE`

The first is easy enough, for the second you can either remove the WHERE clause altogether, or expose an overridable property that would provide the SQL.

**Comment by smitpatel** [comment]
Duplicate of #9228
