### ISSUE TITLE
Is there any way to set on delete cascading as default?

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#3550]

**Comment by rowanmiller** [comment]
Yes, it is now the default for required relationships (in RC1)

**Comment by Kagamine** [comment]
Oh thanks!

**Comment by Kagamine** [comment]
@rowanmiller I'm using EntityFramework.MicrosoftSqlServer rc2 latest, but it still on delete is `no actions`

**Comment by rowanmiller** [comment]
That is the default for non-required relationships (i.e. where the foreign key property is nullable). You can change it though:

```c#
modelBuilder.Entity<Blog>()
    .HasMany(b => b.Posts)
    .WithOne(p => p.Blog)
    .ForeignKey(p => p.BlogId)
    .WillCascadeOnDelete();
```
