### ISSUE TITLE
dnx ef migrations add System.TypeLoadException: Could not load type 'Microsoft.Data.Entity.Internal.CoreStrings'

### ISSUE THREAD

**Issue by angelsix** [dotnet/efcore#3557]
Beta 7 works fine. Beta 8 running:
dnx ef migrations add InitialMigration

Generates:
System.TypeLoadException: Could not load type 'Microsoft.Data.Entity.Internal.CoreStrings' from assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.Data.Entity.Utilities.Check.NotEmpty(String value, String parameterName)

I've cleaned solution, restored, deleted migrations folder, tried many other things. Nothing does anything. Same error all the time.

Calling dnx ef migrations shows the help listing commands like add, remove, script etc...

Running dnx ef migrations remove also throws exactly the same error.

**Comment by angelsix** [comment]
I fixed that if I explicitly specified beta8 for references.

{
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "dependencies": {
    "EntityFramework.SqlServer": "7.0.0-beta8",
    "EntityFramework.Commands": "7.0.0-beta8",
    "EntityFramework.Core": "7.0.0-beta8",
    "Microsoft.AspNet.Identity": "3.0.0-beta8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
  },
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "EntityFramework7.Npgsql": "3.1.0-beta8"
      }
    },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-*",
        "System.Collections": "4.0.11-*",
        "System.Linq": "4.0.1-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-*"
      }
    }
  },
  "commands": {
      "ef":  "EntityFramework.Commands"
  }
}


However then once it generates the migrations file it no longer builds as the migrations file fails as the generated file is invalid, it contains the following for table ID values for example:

migrationBuilder.CreateTable(
    name: "AspNetUsers",
    columns: table => new
    {
        Id = table.Column<IEquatable`1>(nullable: false),
    },

And fails to build as '1 doesnt exist.

It also states CS0115 '<invalid-global-code>.Down(MigrationBuilder)': no suitable method found to override	...\Migrations\20151026080531_InitialMigration.cs	137... and that function is:

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable("AspNetRoleClaims");
            migrationBuilder.DropTable("AspNetUserClaims");
            migrationBuilder.DropTable("AspNetUserLogins");
            migrationBuilder.DropTable("AspNetUserRoles");
            migrationBuilder.DropTable("AspNetRoles");
            migrationBuilder.DropTable("AspNetUsers");
        }

**Comment by angelsix** [comment]
Also if I manually change the generated migration files, removing where it added IEquatable'1 ID values to the actual real model values (string), the migration files then work fine and everything works.

So it seems the issue is with the EF Commands library not creating the migrations files correctly for ID properties. That is all it affects.

**Comment by rowanmiller** [comment]
It sounds like there is an issue with miss-matched versions of assemblies. Are you able to reproduce this with a project created from scratch (if so can you post the detailed steps so that we can reproduce and debug it). If not, is it possible to give us access to the project that is failing?

**Comment by angelsix** [comment]
Just tried it again and its working. Must of been some kind of temporary or cached references as I havent added, removed or edit any references only wrote more code and rebuild a few times.

**Comment by rowanmiller** [comment]
@angelsix thanks for confirming
