### ISSUE TITLE
My Seed Data is not adding to Database

### ISSUE THREAD

**Issue by EmpeRoar** [dotnet/efcore#3560]
Hi Guys,

I have a problem with the initial data I added to my Migration Configuration Seed.

CrmCoreApplicationHelpers crmHelper = new CrmCoreApplicationHelpers();
var customerList = new List<Customer>
{
    new Customer { .. data here ..  },
};
customerList.ForEach(x => context.Customers.AddOrUpdate(y => y.Firstname, x));
context.SaveChanges();

when I run update-database, there are no errors.
But my Customers table is not updated with data.

**Comment by rowanmiller** [comment]
Hey,

This site is for EF7, for EF6 please file an issue on http://entityframework.codeplex.com/. There isn't really enough info here for us to reproduce the issue. If you open an issue on CodePlex can you be sure to include a code listing that we can run to reproduce the issue.

~Rowan
