### ISSUE TITLE
Unable to locate Dependency EntityFramework.InMemory >= 7.0.0-beta8

### ISSUE THREAD

**Issue by boyarincev** [dotnet/efcore#3574]
Can't add "EntityFramework.InMemory" dependency in project.

```
  "dependencies": {
     "xunit.runner.aspnet": "2.0.0-aspnet-beta8",
     "EntityFramework.InMemory": "7.0.0-beta8"
 },
```

Output:

PATH=.\node_modules.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\maste_000.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe "C:\Users\maste_000.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\maste_000\Documents\Visual Studio 2015\Projects\GetHabitsAspNet5App\test\GetHabitsASPNET5App.Tests" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858
Restoring packages for C:\Users\maste_000\Documents\Visual Studio 2015\Projects\GetHabitsAspNet5App\test\GetHabitsASPNET5App.Tests\project.json
Unable to locate Dependency EntityFramework.InMemory >= 7.0.0-beta8
Writing lock file C:\Users\maste_000\Documents\Visual Studio 2015\Projects\GetHabitsAspNet5App\test\GetHabitsASPNET5App.Tests\project.lock.json
Restore complete, 3773ms elapsed
Errors in C:\Users\maste_000\Documents\Visual Studio 2015\Projects\GetHabitsAspNet5App\test\GetHabitsASPNET5App.Tests\project.json
    Unable to locate Dependency EntityFramework.InMemory >= 7.0.0-beta8
NuGet Config files used:
    C:\Users\maste_000\AppData\Roaming\NuGet\nuget.config
Feeds used:
    C:\Program Files (x86)\Microsoft Web Tools\DNU

NuGet.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources>
    <add key="nuget.org" value="true" />
  </disabledPackageSources>
</configuration>
```

**Comment by rowanmiller** [comment]
Interesting that it is only listing `C:\Program Files (x86)\Microsoft Web Tools\DNU` under the `Feeds used:`. It makes sense that it can't find the package since that one isn't included "in the box" with the web tooling... but it is on NuGet.org.

**Comment by boyarincev** [comment]
Why package may searches in "C:\Program Files (x86)\Microsoft Web Tools\DNU" but not on Nuget.org ?

**Comment by boyarincev** [comment]
Reason in:
      <disabledPackageSources>
        <add key="nuget.org" value="true" />
     </disabledPackageSources>

I commented this, and package downloaded from NuGet.org
I don't know how this appear in NuGet.config

**Comment by rowanmiller** [comment]
Totally missed that when you posted the NuGet.config contents... I guess that answers the question then :smile:
