### ISSUE TITLE
Design suggestions for RelationalTypeMapper

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3575]
Here are some design observations from some work on NpgsqlTypeMapper:

First, it seems like `GetMapping(IProperty)` and `FindMapping(IProperty)` contain logic that should hold for any relational provider implementing a type mapper. This includes the NotSupportedException, but also (and more importantly) the logic which gets the property's logic type, parses it, etc. It also seems cleaner for `FindMapping(IProperty)` to call `GetMapping(string)` for the case where a string column is specified on the property. It may be a good idea to remove IRelationalTypeMapper and make RelationalTypeMapper a mandatory base class with this logic.

Second, RelationalTypeMapping contains an optional DbType for the store type. PostgreSQL (and almost any other database, I suspect) supports some types which aren't covered by the common DbType, so Npgsql has as a NpgsqlDbType. For this reason, I can see very little use for the DbType feature - it seems better for every provider to inherit their own RelationalTypeMapping and use their specific *DbType enum.

If either of the above sounds good I can submit a PR.

**Comment by ajcvickers** [comment]
@roji We are following a pattern where all services resolved from DI by constructor injection have an interface that defines the contract for the service. We have found this gives good clarity for the service contract together with the most flexibility for replacement of the service both in product code and in testing. So we wouldn't want to remove IRelationalTypeMapper, even though we expect all provider writers to extend the base class.  (Interestingly, it looks like FindMapping should not be public, or should be moved to the interface.)

I think it would be fine for FindMapping(IProperty) to call GetMapping(string) if this makes the code cleaner and as long as the differences in behavior are retained or don't matter--for example, parenthesis are handled differently and FindMapping should never throw.

I don't think there is a single common good solution for the DbType issue. Quite often the correct thing to do is to not set any type--SQL Server does this a lot and SQLite always does this. Sometimes setting the DbType will work--SQL Server sometimes does this. And then for some types in some providers it may be necessary to set the provider-specific type. The design allows for this latter case while not requiring it for those providers  that don't need it. (e.g. SQL Server and SQLite).

**Comment by roji** [comment]
OK, thanks for the patient explanation. The reasoning for the interface makes total sense.

Regarding the DbType, I may be wrong, but it seems to me that if a provider needs to set DbType, there's no reason for it not to use its specific enum instead (SqlDbType, NpgsqlDbType) which covers more types. In other words, DbType is the provider-independent enum, but here we're operating within a specific provider for a specific database, and therefore the provider-specific enum (SqlDbType) seems more appropriate).

So it might make sense to remove DbType from RelationalTypeMapping and let providers subclass and do what they want. In the Npgsql implementation the DbType is useless since I want to cover PostgreSQL-specific types not available in DbType.

Anyway, it's not terribly important, I'll close this.
