### ISSUE TITLE
Update-Database fails to run Seed against correct connectionstring

### ISSUE THREAD

**Issue by eric-newton** [dotnet/efcore#3578]
When running the `update-database` command, it appears that something is awry with the EF checking mechanism.

The issue reared up because I had pulled from source control, and entities needed to update my "current" database so it was out-of-sync with the code-first entities.  (So FYI, normally, developers pull from their DVCS, Updates their working copy, runs Update-Database with everything configured for the current web.config, etc. and that works.)

However, if you pull new entity changes from DVCS, and want to run `update-database` on a different server than the "current", ie, specifying a connectionstring to `update-database`, and just before `Seed()` is called, it appears to run the initial model check against "current" configuration, instead of the specific one passed in via connection, with the following error message:

> "The model backing the 'ArborContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269)."

When you call `update-database` bare, then run `update-database -connectionstring "[connectionstring]"` with the target connectionstring, it appears to work "better" but I'm still encountering some oddities.

Attached is a log file (pasted from Package Manager Console)

Repro steps (assuming EF already running)
[Dev1] update-database
[Dev2] update-database
[Dev1] updates an entity, adding "DateTimeStamp" to an entity.
[Dev1] run `update-database`
[Dev1] run application, verifies DateTimeStamp column is now being persisted correctly by EF
[Dev1] commit changes to source control + push to origin
[Dev2] pull from origin
~~[Dev2] update-database~~ _skip this step to reproduce_
[Dev2] update-database -connectionstring "[some other server besides webconfig specified server]"

Actual experience:
Update fails with 

> The model backing the 'ArborContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269).

Expected experience:
Update succeeds, updating the specified database mentioned in the connectionstring presented to update-database command.

EDIT: couldnt attach file so I uploaded it here: https://gist.github.com/eric-newton/e358b117bec3d1f7e1f3

**Comment by eric-newton** [comment]
My bet is with `update-database` command not fully communicating the specified connectionstring parameter content to all various places

**Comment by rowanmiller** [comment]
Hey,

This is an EF6 related issue which actually belongs on http://entityframework.codeplex.com/. That said, I think I can answer it for you straight away...

Looking at the stack trace for the error, it looks like there is logic in your seed method that is calling a helper method which creating a new instance of the context. EF will take care of making sure the context that is passed into Seed has the right connection string set... but if your code (or code in a helper you call) is creating new instances of a context then you'll need to make sure they are targeting the right database. 

Here is the section from the stack trace that I am talking about. My guess is that UserManager is not using the same context that was passed into the seed method (and therefore it just points to whatever database the app is setup to use when it runs).

> 264    at Microsoft.AspNet.Identity.AsyncHelper.RunSync[TResult](Func`1 func) 
265    at Microsoft.AspNet.Identity.UserManagerExtensions.Create[TUser,TKey](UserManager`2 manager, TUser user, String password) 
266    at SharingMemoriesWeb.Migrations.Configuration.CreateUser(String roleName) in c:\Projects\ArborMemorial\sharing-memories\SharingMemoriesWeb\Migrations\Configuration.cs:line 121 
267    at SharingMemoriesWeb.Migrations.Configuration.CreateUsers() in c:\Projects\ArborMemorial\sharing-memories\SharingMemoriesWeb\Migrations\Configuration.cs:line 103 
268    at SharingMemoriesWeb.Migrations.Configuration.Seed(ArborContext context) in c:\Projects\ArborMemorial\sharing-memories\SharingMemoriesWeb\Migrations\Configuration.cs:line 41 
269    at System.Data.Entity.Migrations.DbMigrationsConfiguration`1.OnSeed(DbContext context) 
270    at System.Data.Entity.Migrations.DbMigrator.SeedDatabase() 
271    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.SeedDatabase() 
272    at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) 
273    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) 
274    at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration) 

~Rowan

**Comment by eric-newton** [comment]
I guess that’s likely due to Dependency injection (Unity).  Just another gotcha with DI and object instance lifetimes and reference equality.

Eric
t. +1 (321) 293 0500

**Comment by divega** [comment]
Are you using Unity to create the UserManager? In this particular case you would need to flow the DbContext instance from the Seed method to the UserStore constructor and the UserManager.

**Comment by eric-newton** [comment]
Yes, we're using Unity.  My thoughts were similar, that somehow we're not correctly flowing the dependency through.

I'll look into it around those suggestions.

**Comment by divega** [comment]
As far as I remember migrate.exe has usability issues like you describe, e.g. it won't find the assemblies so it might better to copy it and run it to a folder where it will find them. You can also roll your own code to execute migration commands using the DbMigrator class. 

cc @bricelam @rowanmiller in case they can provide a better recommendation.

**Comment by rowanmiller** [comment]
Yep migrate.exe is very fragile... here is guidance on how to get it work https://msdn.microsoft.com/en-us/data/jj618307
