### ISSUE TITLE
Exception Messages: Name of entityType

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#3583]
We have inconsistencies in what do we use for name of entity type when throwing exception. At present we use `EntityType.Name` and `EntityType.DisplayName()` both with no fixed guideline which one to use for particular case. We need to make it consistent or define rules when one is preferred over the other.

**Comment by divega** [comment]
Clearing up milestone so that we can see this in triage and determine its priority.

**Comment by rowanmiller** [comment]
Dupe of https://github.com/aspnet/EntityFramework/issues/734
