### ISSUE TITLE
Make the Property indexes lazy

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#3587]
`Index`, `ShadowIndex` and `OriginalValueIndex` are not used while building the model so they don't need to be calculated at that point. Also they are only stored in the model for perf so they should be accessed through an optional interface instead of an annotation.

**Comment by rowanmiller** [comment]
Closing as we can just try this as part of https://github.com/aspnet/EntityFramework/issues/3640 and see if it makes a difference.

**Comment by ajcvickers** [comment]
@AndriySvyryd @rowanmiller I'm about to send out a pull request that contains this change anyway.

**Comment by rowanmiller** [comment]
Nice :smile:
