### ISSUE TITLE
Design meeting notes - October 28, 2015

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#3590]
# DNX Commands and Startup Projects

The original design of the DNX commands was that you would invoke it on the target project (e.g. MyApp.Data) and pass in the startup project (e.g. MyApp) using the `--startupProject`. However, DNX is not able to load an assembly that isn't referenced by the current project, and referencing it would result in a circular dependency since the reference needs to go the other direction (e.g. MyApp needs to reference MyApp.Data).

In order to fix this, we're swapping the two projects. The commands will now need to be invoked on the ***startup***
project, and a `--targetProject` option will be provided.

For example, to add a migration you would use the following commands.

```cmd
cd src\MyApp
dnx ef migrations add MyMigration --targetProject MyApp.Data
```

This will add a new migration to the MyApp.Data project using MyApp as the startup project.

# Discussion

Please comment on this issue to provide feedback, ask questions, etc.

**Comment by aconstant** [comment]
Just a note about the wiki page, the command :
dnx ef migrations add MyMigration --targetProject MyApp.Data

Should be : (on the latest version 1.0.0-rc2-16317) 
dnx ef migrations add MyMigration --target-project MyApp.Data

**Comment by rowanmiller** [comment]
@aconstant design meeting notes (and other design docs) are just a point in time thing and we don't keep them updated as the product evolves. Our docs for actually using EF are at docs.efproject.net and we keep those updated with each release.

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
