### ISSUE TITLE
RevEng and Migrations: Consider testing schema roundtripability 

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#3599]
While EF will always only understand about a subset of the database constructs, 
we have done work to improve the fidelity of database reverse engineering, e.g. in https://github.com/aspnet/EntityFramework/pull/3579 we made sure that names of indexes were preserved in the model. From https://github.com/aspnet/EntityFramework/issues/2840#issuecomment-151241655:

> Thinking on this some more. If we want the model to be as "round-trippable" as possible, we will need to specify at least the index's name for all indexes. The name we would otherwise generate through migrations is not likely to be the same as it depends on whatever tool the DBA used to create the index in the first place (@lajones)

I would like to propose that we deliberately test how good the experience is when the user:
1. Points reverse engineering to an existing database to produce an EF model
2. Points migrations using the resulting model back to the database to make changes

Note that I don't think the goal of this should be to achieve 100% fidelity but to understand the gaps and possibly identify low hanging fruit that we can tackle to improve both reverse engineering and migrations.

cc @Eilon

**Comment by divega** [comment]
We could consider adding an automated end-to-end test for a database that we know roundtrips in this way. It could help detect regressions, but I am not sure about the cost/benefit.

**Comment by ErikEJ** [comment]
Great idea, I will do that for the SQLCE provider!

**Comment by ajcvickers** [comment]
Closing this for now, with the understanding that we will likely have similar things to test as part of update-model-from-database, and we should do what we need to do in the context of that feature.
