### ISSUE TITLE
EF got confused between ConfigurationName and DatabaseName

### ISSUE THREAD

**Issue by uadnan** [dotnet/efcore#3608]
![error](https://cloud.githubusercontent.com/assets/8841282/10839157/1ee15d4a-7ef2-11e5-94b0-a2c328404a74.png)

Not all the time but some times EF got confused between ConfigurationName and DatabaseName. See attached image for more detail.

When that happens:
- A project was loaded in VS and in package manager console I executed Update-Database for that project.
- I switched to new TFS workspace and opened new solution from new workspace from Team Explorer
- Created Database in MSSQLEXPRESS instance.
- Changed ConnectionString to target new database
- Rebuild solution
- Execute Update-Database in Package Manager Console

In last Update-Database command EF got confused with DefaultConnection connection string name name and database name. Database is created inside 'MSSQLLocalDB' instance by EF. 

I'm using Code-First migrations with whole database initialization in Seed method of migration Configuration.

**Comment by Anderman** [comment]
This looks like an EF6 issue? Is that correct? you can open an issue on CodePlex project http://entityframework.codeplex.com/. This GitHub project is for EF7 onwards.

**Comment by rowanmiller** [comment]
As mentioned, EF6 issues should be logged on CodePlex - http://entityframework.codeplex.com/. To be able to do anything with this issue though we would need steps to be able to reproduce it.

BTW one possible reason we could see this happening is if you are calling the base constructor if DbContext that takes a string and passing in "DefaultConnection" and then somehow using the context when the Web.config file is not available (i.e. using it from another project, using the migrations commands when the project with Web.config is not the startup, etc.). If you want to protect against this, you can pass "name=DefaultConnection" to the base constructor which tells EF that it must be a string from the config file and you are not just specifying a database name.
