### ISSUE TITLE
RevEng - unable to add EF.Relational.Design package

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3622]
Attempting to install the EF.Relational.Design package build 16182 from aspnetcidev fails with:

Attempting to gather dependencies information for package 'Microsoft.CodeAnalysis.CSharp.1.1.0-rc1-20151014-07' with respect to project 'design\EntityFramework.SqlServerCompact40.Design', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.CodeAnalysis.CSharp.1.1.0-rc1-20151014-07' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.CodeAnalysis.CSharp.1.1.0-rc1-20151014-07'
Resolved actions to install package 'Microsoft.CodeAnalysis.CSharp.1.1.0-rc1-20151014-07'
Adding package 'Microsoft.CodeAnalysis.Analyzers.1.0.0' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.CodeAnalysis.Analyzers.1.0.0' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.CodeAnalysis.Analyzers.1.0.0' to 'packages.config'
Executing script file 'C:\Code\EntityFramework7.SqlServerCompact\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0\tools\install.ps1'...
Successfully installed 'Microsoft.CodeAnalysis.Analyzers 1.0.0' to EntityFramework.SqlServerCompact40.Design
Install failed. Rolling back...
Package 'Microsoft.DiaSymReader.Native 1.2.0-rc' does not exist in project 'EntityFramework.SqlServerCompact40.Design'
Removed package 'Microsoft.CodeAnalysis.Analyzers 1.0.0' from 'packages.config'
Executing script file 'C:\Code\EntityFramework7.SqlServerCompact\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0\tools\uninstall.ps1'...
Package 'Microsoft.DiaSymReader.Native 1.2.0-rc' does not exist in folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removing package 'Microsoft.CodeAnalysis.Analyzers 1.0.0' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removed package 'Microsoft.CodeAnalysis.Analyzers 1.0.0' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
**Could not install package 'Microsoft.DiaSymReader.Native 1.2.0-rc'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**
========== Finished ==========

**Comment by bricelam** [comment]
Hmm, it looks like that package requires a project.json based solution. There might be a NuGet or package bug here--I don't think it should block install. This is just one more reason to do #3602

**Comment by ErikEJ** [comment]
But it does block install now :sad: - removing Roslyn sounds like a healthy approach in the long term

**Comment by bricelam** [comment]
File a bug on [NuGet/Home](https://github.com/NuGet/Home) saying that you can't install `Microsoft.CodeAnalysis.Common` into a `net451` project, and see where that goes...

**Comment by ErikEJ** [comment]
No SQLCE scaffolding for RC1 then, I guess...

**Comment by ErikEJ** [comment]
@bricelam Bug was already filed in the Roslyn repo https://github.com/dotnet/roslyn/issues/6495

**Comment by rowanmiller** [comment]
We are going to go ahead with https://github.com/aspnet/EntityFramework/issues/3602 (and try to get it into RC1)
