### ISSUE TITLE
Where is source for the 6.* versions?

### ISSUE THREAD

**Issue by togakangaroo** [dotnet/efcore#3623]
I realize that this repo is for 7..\* but its been several days since I've asked [in the recommended location on StackOverflow](http://stackoverflow.com/questions/33382943/where-is-source-for-ef-6-1-3) (with bounty even) and on the [codeplex issue tracker](https://entityframework.codeplex.com/workitem/2847#) and haven't so much as received a single response. Do yall know the answer here?

**Comment by ErikEJ** [comment]
I have replied on StackOverflow

**Comment by rowanmiller** [comment]
I also replied on CodePlex :smile:
