### ISSUE TITLE
Query :: fix ExpressionPrinter after shapers refactoring

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#3631]
Shapers body no longer shows up in query plan after https://github.com/aspnet/EntityFramework/pull/3628/
so the printer needs to be updated

**Comment by rowanmiller** [comment]
We can do this if we hit a scenario where we really need it (or customers want it).

**Comment by maumar** [comment]
I find it pretty useful for debugging, customers are not likely to need it, but I would still like this in at some point. Not super high priority though

**Comment by divega** [comment]
@maumar Then I would be fine with either keeping this issue open in the backlog or to keep it closed and you can still do it any time it will help you.

@rowanmiller any strong preference one way or the other?

**Comment by rowanmiller** [comment]
We should close it since it's not something that really matters if we fix or not and therefore we don't need to track, prioritize, triage, load-balance etc. @maumar if you decide to fix it because it is helpful to you then that's fine.

**Comment by maumar** [comment]
@rowanmiller @divega  works for me
