### ISSUE TITLE
how to debug EntityFramework6 source code ?

### ISSUE THREAD

**Issue by xinyebs** [dotnet/efcore#3636]
1.When I debug EntityFramework6 souce code , Created a problem:

2.It's Says:" Failed to load file or assembly“EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”Or one of its dependencies.Strong name validation fails"

3.My app.config file like this:
 section name="entityFramework"type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral"
               requirePermission="false"

**Comment by divega** [comment]
I assume you are building from source. Are you following these steps? 

http://entityframework.codeplex.com/wikipage?title=Getting%20and%20Building%20EF%20Runtime

**Comment by divega** [comment]
In particular you will have to do this once:

```
build /t:EnableSkipStrongNames
```

**Comment by xinyebs** [comment]
@divega  Thank you for your answer.
