### ISSUE TITLE
Logging broken (for me) after latest Command Execution changes

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3654]
Command execution is now wrapped in IRelationalCommand. After adjusting to this here: https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.MicrosoftSqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs I can see from this test: MaxLengthAttribute_throws_while_inserting_value_longer_than_max_length() that the INSERT statement that is causing an exeception is no longer logged. 

I am sure I am doing something wrong, but fail to see exactly what - wonder if anyone on the team can guide me in the right direction

Notice that I construct an additional IRelationalCommand for use with IDENTITY inserts, due to the fact that SQL CE only supports a single SQL statement per DbCommand.

And all other tests pass after my changes in order to accommodate the command execution changes.

**Comment by rowanmiller** [comment]
@mikary could this be related to the changes you made?

**Comment by mikary** [comment]
I think what might be going on here is something related to #3611 and the RelationalCommand execution changes.

The latest changes eliminated the ISqlStatementExecutor, which previously was responsible for 'opening' and 'closing' the IRelationalConnection (internally the connection maintains counts so an actual Open/Close might not happen).

Logging was also moved into the RelationalCommand, but it was originally done when the DbCommand instance was created. The log operation was moved into the method that performs the actual execution in 3d74c12fff857dd208c8855c21110ff0706b8d70.

The command was still logged before execute was called until in  7f0abffc10dbe4d3feae17330049c210f2c9f7b2 where the execution time was added to the DbCommand log. If there is an exception thrown but it isn't showing up in the log, it is possible that it's a result of this change.

It is possible to intercept the DbCommand before execution occurs by registering a diagnostic listener for the BeforeExecuteCommand event.

@anpete Does this seem like a reasonable explanation and is this the expected/desired behavior now?

**Comment by ErikEJ** [comment]
Thanks, notice that the logging works as expected with the SQL Server provider

**Comment by ErikEJ** [comment]
Thanks to your help, @mikary I figured out what the issue is: If an error occurs during command execution, EF disposes of the failed command: https://github.com/aspnet/EntityFramework/blob/d660658f9ab55ed4af26bb98bba4b460a670d639/src/EntityFramework.Relational/Storage/Internal/RelationalCommand.cs#L131 

This causes any loggable information to disappear from the DbCommand. This is not the case for SqlCommand, but SqlCeCommand behaves differently.

I have added a test that demonstrates the issue here: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/SqlCeCommandDisposeTest.cs

**Comment by rowanmiller** [comment]
Hey,

As discussed we aren't planning to do anything in EF since it seems like this is very specific to SQL Compact. If there are other providers that do this too then we would consider re-architecting things in EF. We would be willing to take a contribution though if there is something we could do to make it easier for compact to work better here.

~Rowan

**Comment by ErikEJ** [comment]
@rowanmiller Makes sense. Is there any way currently to enable logging of the SQL statements before execution (this will help with the debugging "invalid" SQL Compact commands before execution)

**Comment by anpete** [comment]
@ErikEJ We do raise a DiagnosticSource event ("BeforeExecuteCommand") before command execution. Perhaps you could use that?

**Comment by ErikEJ** [comment]
Sounds promising, are there any samples of how to enable that and subscribe to the events from a desktop app?

**Comment by anpete** [comment]
cc @avanderhoorn who may have an example.

I think if you just pull the DiagnosticListener from DI, you can subscribe to the notification.

**Comment by ErikEJ** [comment]
@anpete Thanks, finally figured out how to do that: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/BasicEndToEndScenario.cs#L18
