### ISSUE TITLE
Persisting the credentials while running EntityFramework.MicrosoftSqlServer.FunctionalTests

### ISSUE THREAD

**Issue by saurabh500** [dotnet/efcore#3658]
While running the tests in EntityFramework.MicrosoftSqlServer.FunctionalTests after changing the config.json to point to a SqlServer, the password is not used for all test runs. 
As a result, many tests throw a login failed exception.

Can this be modified to either persist the credentials or to use the credentials from config.json everytime the tests are run?

**Comment by bricelam** [comment]
Re-opening to triage. This may be indicative of bigger issues.

**Comment by rowanmiller** [comment]
You can hit this in some scenarios because we clone the connection. Shouldn't happen in common app patterns but given this is from our tests that is ok.
