### ISSUE TITLE
Scaffolding: document the DatabaseModelFactory

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3663]
Explain what goes in the DatabaseModel object and how that affects the ScaffoldingModel generation.

What goes in `TableModel.Indexes`? Should PK indexes be included or ignored? Does ForeignKeyModel.Name need to be unique? etc.

**Comment by natemcmaster** [comment]
cc @ErikEJ

**Comment by rowanmiller** [comment]
Moved to docs repo https://github.com/aspnet/EntityFramework.Docs/issues/61
