### ISSUE TITLE
Handle redundant PK indexes in RelationalScaffoldingModelFactory

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3664]
Most databases contain a unique index to represent primary key constraint. Currently, SqlServer and Sqlite filter these indexes at the DatabaseModelFactory so that RelationalScaffoldingModelFactory does not add these to the scaffolding model. It would be more useful to prevent adding this redundant indexes to the ScaffoldingModel in our base implementation (RelationalScaffoldingModelFactory).

**Comment by natemcmaster** [comment]
cc @lajones Did you already start work on something similar to this?

**Comment by lajones** [comment]
@natemcmaster sorry, no, can't find anything on that.

**Comment by smitpatel** [comment]
Currently Sqlite doesn't filter Indexes defined on PK (#3642) unless it has been fixed.

**Comment by ErikEJ** [comment]
@natemcmaster Actually I did not filter them out, and it did not affect Fluent API scaffolding!?

**Comment by rowanmiller** [comment]
Created a [task to look at the all-up design around indexes](https://github.com/aspnet/EntityFramework/issues/3710) (and listed this as an item that needs attention).

**Comment by lajones** [comment]
Note: we do filter out indexes which match the PK properties much later in the process in `ModelConfiguration.AddIndexConfigurations()`. This applies to all providers - but note the SQL Server provider has already removed them in `SqlServerDatabaseModelFactory.GetIndexes()`.

**Comment by ErikEJ** [comment]
Great, as noted this works fine for me!
