### ISSUE TITLE
LINQ to Entities only supports casting EDM primitive or enumeration types

### ISSUE THREAD

**Issue by michaltalaga** [dotnet/efcore#3666]
as posted here:
http://stackoverflow.com/questions/33549942/linq-to-entities-only-supports-casting-edm-primitive-or-enumeration-types-after

This has worked for me for years. After Updating to VS2015 Update 1 RC  AND later downgrading to CTP it now doesn't work on any version I try it. Vanila 2015, Update 1 CTP or Update 1 RC.

**Comment by rowanmiller** [comment]
One of our team members has replied to your StackOverflow question
