### ISSUE TITLE
InvalidCast while Multi-Level Eager Load (Include method)

### ISSUE THREAD

**Issue by buraktamturk** [dotnet/efcore#3671]
Hello,

I use ASP.NET 5 and EF6 on my simple blog. I wanted to port it to EF7.

I have posts table, revisions table and authors table. Each post and revision have an author. I want to load posts with its revisions alongside revision authors.

``` csharp
var a = db.posts.Include(a => a.revisions.Select(b => b.author)).ToList();
```

throws InvalidCastException (of type SubQueryExpression to type MemberExpression).

whereas

``` csharp
var a = db.posts.Include(a => a.revisions).ToList();
```

and

``` csharp
var a = db.revisions.Include(a => a.author).ToList();
```

works fine. Is it not implemented yet or am I doing something seriously wrong here?

Thanks,

**Comment by maumar** [comment]
@buraktamturk the way to do it in EF7 is:

```
var a = db.posts.Include(p => p.revisions).ThenInclude(r => r.author)).ToList();
```
