### ISSUE TITLE
Insert a data, how to obtain the Entity Framework automatically increase the primary key

### ISSUE THREAD

**Issue by xinyebs** [dotnet/efcore#3672]
Insert a data, how to obtain the Entity Framework automatically increase the primary key?

thanks!

**Comment by rowanmiller** [comment]
By default EF will create an auto-incrementing column (IDENTITY on SQL Server) for any integer primary keys. As an example see the [model used in our getting started walkthrough](http://ef.readthedocs.org/en/latest/getting-started/full-dotnet.html#create-your-model). In that model, `Blog.BlogId` and `Post.PostId` are both auto-incrementing.

**Comment by doublnt** [comment]
This page does not exist yet.http://ef.readthedocs.io/en/latest/getting-started/full-dotnet.html#create-your-model

**Comment by ajcvickers** [comment]
@doublnt It moved here: https://docs.microsoft.com/en-us/ef/core/modeling/

**Comment by doublnt** [comment]
I got it ,Thanks @ajcvickers
