### ISSUE TITLE
-p Broken in last 24 hours?

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#3677]
I ran this project yesterday successfully:

```
https://github.com/dneimke/effoo
```

Today I updated my DNX version to rc2-16107 and EF versions to rc2-16275 and all of a sudden I can't run --target-project command anymore.  

Specifically, this command:

https://github.com/dneimke/EFFoo/blob/develop/src/EFFoo/CreateMigrations.bat

Did this regress?

**Comment by ChristineBoersen** [comment]
Could this be related to https://github.com/aspnet/EntityFramework/issues/3590 which specifies some retooling that was being discussed?

**Comment by rowanmiller** [comment]
We tested on the latest bits and this seems to be working now. Feel free to reopen if it still fails for you. If you do re-open, please include detailed steps on how we can reproduce the error you are seeing.
