### ISSUE TITLE
How to Eager Load multiple Sibling Entities

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#3692]
With EF7 we get ThenInclude to include entity members off of a collection.  E.g. I can do the following

```
BlogPost.FindAll()
    .Include(b => b.Authors)
        .ThenInclude(a => a.Address);
```

This will return a collection of BlogPosts, with the Authors collection and the address of each Author eagerly loaded.

How would I eager load multiple entities off of the Authors collection?  E.g.

```
BlogPost.FindAll()
    .Include(b => b.Authors)
        .ThenInclude(a => a.Address)
        // I also want to include a => a.Spouse
```

Do I do something like this?

```
BlogPost.FindAll()
    .Include(b => b.Authors.Select(a => new { a.Address, a.Spouse })
```

**Comment by tjendra** [comment]
```
BlogPost.FindAll()
    .Include(b => b.Authors)
        .ThenInclude(a => a.Address)
    .Include(b => b.Authors)
        .ThenInclude(a => a.Spouse)
```

**Comment by dneimke** [comment]
Thx

**Comment by tinchou** [comment]
@rowanmiller do you think we could add this to the docs? I was looking for this but couldn't find any examples here https://docs.microsoft.com/en-us/ef/core/querying/related-data

Also, I have to load five entities related to a nested one and it'd be great to have some syntactic sugar.

Thanks!

**Comment by rowanmiller** [comment]
PR created to the docs https://github.com/aspnet/EntityFramework.Docs/pull/351
