### ISSUE TITLE
RevEng: Identity Columns not handled Properly

### ISSUE THREAD

**Issue by anandmukundan** [dotnet/efcore#3693]
When reverse engineering from a table where an column is marked as identity, the property generated for this should not be settable. 

Currently it has both get/set and when adding a record with the column set results in an Update Exception, "The Column cannot be modified". Update works fine if the code does not set the property.

[Using SQLServerCompact40/C#/VS 2015/ 7.0.0.0 Beta 8]

**Comment by ErikEJ** [comment]
Thanks for reporting this, could you share the generated class code, and the CREATE TABLE statement for the table in question

**Comment by anandmukundan** [comment]
Below is the Create Table script

CREATE TABLE Student (
  [Id] int IDENTITY (1,1) NOT NULL
, [Name] nvarchar(100) NOT NULL
, [ClassId] int NOT NULL
);

And the Class def generated.

 public class Student
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        [Required]
        public string Name { get; set; }

        [ForeignKey("ClassId")]
        [InverseProperty("Student")]
        public virtual ClassMaster Class { get; set; }
    }

As you can see the ID column is marked Identity, but the property has get and set.
Also I see that though the ID is not null, it is not marked as [Required], which is fine for an identity column.

**Comment by ErikEJ** [comment]
Re "Required" - not needed, as it is an int column (othewise it would have been an int? column, ie nullable)

**Comment by anandmukundan** [comment]
Re "Required" - That makes sense...
