### ISSUE TITLE
Cannot install latest EF7 nightly - nuget error

### ISSUE THREAD

**Issue by davidroth** [dotnet/efcore#3694]
I get the following error from nuget (asp nightly source, EntityFramework.Core.7.0.0-rc1-16147)

`Failed to add reference to 'System.Collections'. Please make sure that it is in the Global Assembly Cache.`

Any solution?

**Comment by ErikEJ** [comment]
Use a more volatile feed: http://myget.org/gallery/aspnetcidev and if the error persists, remove all references to EF from packages.config and your references.

**Comment by davidroth** [comment]
Thx, this feed works.
