### ISSUE TITLE
Proposal: First-class support for Mixins

### ISSUE THREAD

**Issue by Antaris** [dotnet/efcore#3696]
Hi Team,

I've been prototyping another experiment using EF7 based around your work with shadow properties. What I've been working on is support for a mixin-style extension to EF, whereby you can use static typing over the `EF.Property(...)` syntax. I've documented my experiments on [my blog](http://www.inversionofcontrol.co.uk/experimental-entity-mixins-via-shadow-properties-in-entity-framework-7/) and have created [a repo here on GitHub](https://github.com/Antaris/EntityFrameworkMixins).

Broadly with mixin support we can transform queries like this:

```
from u in context.Users
where EF.Property<string>(u, "GooglePlusProfile") != null
select u;
```

To the following:

```
from u in context.Users
where u.Mixin<Author>().GooglePlusProfile != null
select u;
```

Having the ability to provide static typing instead of magic strings would help developers and avoid a few bugs. Under the hood, this experiment is a visitor that replaces `entity.Mixin<Type>().Property` with calls to `EF.Property<PropertyType>(entity, "PropertyName")`.

I've also added support for `select entity.Mixin<Type>()` which is translated into an object initializer such like `select new EntityType() { PropertyName = EF.Property<string>(entity, "PropertyName") }`.

To declare mixins as part of your model builder, I've created a custom builder type that forwards to a parent `EntityTypeBuilder`, so you get a similar syntax as using the fluent type builder:

```
var entity = builder.Entity<User>();
var mixin = entity.Mixin<Author>();

mixin.Property(u => u.GooglePlusProfile).HasMaxLength(100);
```

This simply chains calls to the parent entity type builder, using the mixin type name as a prefix for the shadow property name.

Lastly, I've also started playing around with change detection, by creating a base type which is assigned a `Func<string, PropertyEntry>` delegate when the parent entity entry is created by the state manager. But this then requires mixins to extend a base type and the getter/setters have to be chained to the delegate so when you update a mixin, it invisibly updates the change tracker-stored value:

```
var user = (from u in context.Users select u).FirstOrDefault();
var author = user.Mixin<Author>();
author.GooglePlusProfile = "value";

context.SaveChanges();
```

I'm mostly happy with what I've managed to uncover, but I am unsure of the next direction, is it worth investigating this further, because I feel it would need more integral support from the stack to make it cleaner and simpler to implement for the app developer?

Interested to know your thoughts/advice on this.

**Comment by Antaris** [comment]
Cool, thanks for the feedback. I'd like to continue working on this, I think there will be some changes I will investigate around the change tracker, I'd like to make the support for Mixins more POCO-like, so I think that's where I'll start.

Did you want to keep this issue open for reference?

**Comment by rowanmiller** [comment]
I think we can close this out. We'll just handle any changes you want to make as Pull Requests.
