### ISSUE TITLE
SQLite Migrations: Preserve column max length

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#3698]
Currently, SQLite has a very trivial type mapping so `string` properties are always mapped to `TEXT` columns. We could preserve the `HasMaxLength()` metadata in the database schema if we wanted. The column would map to something like `TEXT(30)`. SQLite effectively ignores any length/precision/scale values, but we could still honor their semantics during reverse engineer.

**Comment by AdamJachocki** [comment]
This should be opened. Migrations in .NET5.0 don't work anymore on SQLite. An exception is thrown: SQLite Error 1: 'near "max": syntax error'

**Comment by ErikEJ** [comment]
@AdamJachocki are you using SQL Server migrations with SQLite?

**Comment by roji** [comment]
@AdamJachocki assuming you're not accidentally trying to apply SQL Server migrations on SQLite as suggested above by @ErikEJ, please open a new issue with a full repro (i.e. a Sqlite database schema which fails to be scaffolded).

**Comment by roji** [comment]
@AdamJachocki many users are successfully using migrations on Sqlite - you're going to have to open a new issue and share your model and migration.
