### ISSUE TITLE
Migrations: Obscure AlterColumn operations

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#3700]
If unspecified, we bind to the migration's model to determine the store type of a column. There is metadata in the model used to influence the column type that aren't stored the Migrations operations:
- Whether it's a primary/alternate/foreign key column
- Whether it's a concurrency token and a value is generated on add or update
- It's maximum length
- Any other provider-specific metadata providers may use
#3699 updated the model differ to detect any changes to these "facets", but it results in an obscure migration being generated.

For example, if you change the max length of a column from 15 to 30, you get a migration with the following operation.

``` C#
migrationBuilder.AlterColumn<string>(
    table: "Person",
    name: "Name",
    nullable: false);
```

As you can see, the operation has nothing to do max length. This is because that information is read from the model snapshot stored in the migration when the SQL script is generated.

**Comment by rowanmiller** [comment]
We'll do nothing for now but may add some explanation later if folks are confused by this
