### ISSUE TITLE
Designer Tool for EF7

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#3708]
Cannot find any way of creating the models based on database. Is there any tool for reverse engineer using EF7?

**Comment by ThomasGugler** [comment]
EF Power Tools Beta4 can be modified to work with EF7:
http://thedatafarm.com/data-access/installing-ef-power-tools-into-vs2015/

**Comment by pantonis** [comment]
Thanks,

Tried this. Seems to work with a console project not with an asp.net 5 though. Entity framework context menu is missing. Any idea?

**Comment by pantonis** [comment]
No console project does not work either.
It does not produce code that works for EF7

**Comment by ErikEJ** [comment]
See http://stackoverflow.com/questions/32377984/entity-framwork-7-reverse-engineer-from-existing-db-code-first

**Comment by rowanmiller** [comment]
At the moment it is just available at the command line.

In ASP.NET 5 you want: `dnx ef dbcontext scaffold`

In all other project types there is a `Scaffold-DbContext` command registered in Package Manager Console in Visual Studio.
