### ISSUE TITLE
Will EF7 run in Windows 8.1 apps?

### ISSUE THREAD

**Issue by flagbug** [dotnet/efcore#3709]
Hi, I just wanted to ask if there are any plans to make EF7 available on the Windows 8.1 platform?

Cheers,
Dennis

**Comment by rowanmiller** [comment]
Hey,

Probably not, at this stage we are just focusing on UWP/Windows 10. When we are done we may look at 8.1 and enable it if the work is minimal... but we suspect it will be non-trivial.

~Rowan

**Comment by bricelam** [comment]
FYI, I dug into this a while ago and our dependency on Caching was the first roadblock I hit--`AsyncLocal` isn't available the older platforms.
