### ISSUE TITLE
Cleanup C# syntax utilities and internal APIs

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3711]
We should unify our C# syntax logic. We removed Roslyn in #3645 which required adding to our code a list of keywords. We now have 2 classes that contain this logic. `CSharpUtilities` and `CSharpHelper`.

In addition, we should re-visit our internal APIs related code-gen C#. `CSharpUniqueNamer` and `CSharpUtilities.GenerateCSharpIdentifier` that provide similar API.

**Comment by natemcmaster** [comment]
cc @lajones

**Comment by bricelam** [comment]
Part of #1671

**Comment by rowanmiller** [comment]
We'll handle as part of #1671
