### ISSUE TITLE
Dynamic type (EF 7)

### ISSUE THREAD

**Issue by GVX111** [dotnet/efcore#3719]
@divega  How select object without declare in Dbset. I have Datacontext like this:

<pre>public class DataContext : DbContext
    {
        public DataContext()
        {
            Database.Migrate();
        }
        public void AddTable(Type type)
        {
            Tables.Add(type.Name, type);
        }

        public Dictionary<string, Type> Tables = new Dictionary<string, Type>()
        {
            {"News", MyTypeBuilder.CompileResultType("News") }
        };
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=sqltest\\test2;Database=ERP; User Id=sa; Password=Musha2005; MultipleActiveResultSets=true");
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.HasDefaultSchema("ITN");
            foreach (var table in Tables)
            {
                foreach (var pi in table.Value.GetProperties())
                {
                    if (pi.Name == "Id")
                        builder.Entity(table.Value).HasKey("Id");
                }
            }

        }
    }</pre>

I'm creating Entity Type with CompileResultType and it's working great. 
How to write selection of object (I have not declared in DataContext)
MyTypeBuilder.CompileResultType this creating Type dynamic.

**Comment by GVX111** [comment]
Full Code
<pre>  public class DataContext : DbContext
    {
        public DataContext()
        {
            Database.EnsureCreated();
            Database.Migrate();
        }
        public void AddTable(Type type)
        {
            Tables.Add(type.Name, type);
        }

        public Dictionary<string, Type> Tables = new Dictionary<string, Type>()
        {
            {"News", MyTypeBuilder.CompileResultType("News") }
        };
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=sqltest\\test2;Database=ERP; User Id=sa; Password=Musha2005; MultipleActiveResultSets=true");
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.HasDefaultSchema("ITN");
            var entityMethod = builder.GetType().GetMethod("Entity", new Type[] {  });
            foreach (var table in Tables)
            {
                entityMethod.MakeGenericMethod(table.Value).Invoke(builder, new object[] { });
                foreach (var pi in table.Value.GetProperties())
                {
                    if (pi.Name == "Id")
                        builder.Entity(table.Value).HasKey("Id");
                }
            }

        }
    }

    public static class MyTypeBuilder
    {
        public static void Test()
        {
            var db = new DataContext();
            var instance = db.Tables["News"];
            var tss = db.Tables["News"].Name;
            var asd = db.Tables["News"].ToString();
            var ts = db.GetType();
            var t = db.Entry(db.Tables["News"]);
        }
       
        private static readonly Dictionary<string, string> fields = new Dictionary<string, string>()
        {
            {"Id","int"},
            {"EmployeeID","int"},
            {"EmployeeName","String"},
            {"Designation","String"}
        };
        public static void CreateNewObject()
        {
            var myType = CompileResultType("Test");
            var myObject = Activator.CreateInstance(myType);
        }
        public static Type CompileResultType(string typeName)
        {
            TypeBuilder tb = GetTypeBuilder(typeName);
            ConstructorBuilder constructor = tb.DefineDefaultConstructor(MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName);

            // NOTE: assuming your list contains Field objects with fields FieldName(string) and FieldType(Type)
            foreach (var field in fields)
                CreateProperty(tb, field.Key, GetTypeFromSimpleName(field.Value));

            Type objectType = tb.CreateType();
            return objectType;
        }

        private static TypeBuilder GetTypeBuilder(string typeName)
        {
            var typeSignature = typeName;
            var an = new AssemblyName(typeSignature);
            AssemblyBuilder assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(an, AssemblyBuilderAccess.Run);
            ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule("MainModule");
            TypeBuilder tb = moduleBuilder.DefineType(typeSignature
                                , TypeAttributes.Public |
                                TypeAttributes.Class |
                                TypeAttributes.AutoClass |
                                TypeAttributes.AnsiClass |
                                TypeAttributes.BeforeFieldInit |
                                TypeAttributes.AutoLayout
                                , null);
            return tb;
        }

        private static void CreateProperty(TypeBuilder tb, string propertyName, Type propertyType)
        {
            FieldBuilder fieldBuilder = tb.DefineField("_" + propertyName, propertyType, FieldAttributes.Private);

            PropertyBuilder propertyBuilder = tb.DefineProperty(propertyName, PropertyAttributes.HasDefault, propertyType, null);
            MethodBuilder getPropMthdBldr = tb.DefineMethod("get_" + propertyName, MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.HideBySig, propertyType, Type.EmptyTypes);
            ILGenerator getIl = getPropMthdBldr.GetILGenerator();

            getIl.Emit(OpCodes.Ldarg_0);
            getIl.Emit(OpCodes.Ldfld, fieldBuilder);
            getIl.Emit(OpCodes.Ret);

            MethodBuilder setPropMthdBldr =
                tb.DefineMethod("set_" + propertyName,
                  MethodAttributes.Public |
                  MethodAttributes.SpecialName |
                  MethodAttributes.HideBySig,
                  null, new[] { propertyType });

            ILGenerator setIl = setPropMthdBldr.GetILGenerator();
            Label modifyProperty = setIl.DefineLabel();
            Label exitSet = setIl.DefineLabel();

            setIl.MarkLabel(modifyProperty);
            setIl.Emit(OpCodes.Ldarg_0);
            setIl.Emit(OpCodes.Ldarg_1);
            setIl.Emit(OpCodes.Stfld, fieldBuilder);

            setIl.Emit(OpCodes.Nop);
            setIl.MarkLabel(exitSet);
            setIl.Emit(OpCodes.Ret);

            propertyBuilder.SetGetMethod(getPropMthdBldr);
            propertyBuilder.SetSetMethod(setPropMthdBldr);
        }
        public static Type GetTypeFromSimpleName(string typeName)
        {
            if (typeName == null)
                throw new ArgumentNullException("typeName");

            bool isArray = false, isNullable = false;

            if (typeName.IndexOf("[]") != -1)
            {
                isArray = true;
                typeName = typeName.Remove(typeName.IndexOf("[]"), 2);
            }

            if (typeName.IndexOf("?") != -1)
            {
                isNullable = true;
                typeName = typeName.Remove(typeName.IndexOf("?"), 1);
            }

            typeName = typeName.ToLower();

            string parsedTypeName = null;
            switch (typeName)
            {
                case "bool":
                case "boolean":
                    parsedTypeName = "System.Boolean";
                    break;
                case "byte":
                    parsedTypeName = "System.Byte";
                    break;
                case "char":
                    parsedTypeName = "System.Char";
                    break;
                case "datetime":
                    parsedTypeName = "System.DateTime";
                    break;
                case "datetimeoffset":
                    parsedTypeName = "System.DateTimeOffset";
                    break;
                case "decimal":
                    parsedTypeName = "System.Decimal";
                    break;
                case "double":
                    parsedTypeName = "System.Double";
                    break;
                case "float":
                    parsedTypeName = "System.Single";
                    break;
                case "int16":
                case "short":
                    parsedTypeName = "System.Int16";
                    break;
                case "int32":
                case "int":
                    parsedTypeName = "System.Int32";
                    break;
                case "int64":
                case "long":
                    parsedTypeName = "System.Int64";
                    break;
                case "object":
                    parsedTypeName = "System.Object";
                    break;
                case "sbyte":
                    parsedTypeName = "System.SByte";
                    break;
                case "string":
                    parsedTypeName = "System.String";
                    break;
                case "timespan":
                    parsedTypeName = "System.TimeSpan";
                    break;
                case "uint16":
                case "ushort":
                    parsedTypeName = "System.UInt16";
                    break;
                case "uint32":
                case "uint":
                    parsedTypeName = "System.UInt32";
                    break;
                case "uint64":
                case "ulong":
                    parsedTypeName = "System.UInt64";
                    break;
            }

            if (parsedTypeName != null)
            {
                if (isArray)
                    parsedTypeName = parsedTypeName + "[]";

                if (isNullable)
                    parsedTypeName = String.Concat("System.Nullable`1[", parsedTypeName, "]");
            }
            else
                parsedTypeName = typeName;

            // Expected to throw an exception in case the type has not been recognized.
            return Type.GetType(parsedTypeName);
        }
    }</pre>

**Comment by rowanmiller** [comment]
We aren't 100% sure we understand exactly what you are asking. If you are asking about how to query data, you would use `DbContext.Set<T>()` - you would need to use MakeGenericMethod to call it.

**Comment by GVX111** [comment]
I early solved  problem thank you @rowanmiller
