### ISSUE TITLE
Add() behavior with graphs does not handle properly 1:1 child entities

### ISSUE THREAD

**Issue by Yanal-Yves** [dotnet/efcore#3724]
Steps to reproduce:
- Create a Child entity (ex: https://github.com/Yanal-Yves/ConsoleApp2/blob/master/src/ConsoleApp2/Model/ChildA.cs)
- Create a Parent entity that has a reference to the Child entity (ex: https://github.com/Yanal-Yves/ConsoleApp2/blob/master/src/ConsoleApp2/Model/Parent.cs#L23)
- Add the parent to context with GraphBehavior.IncludeDependents flag set (ex: https://github.com/Yanal-Yves/ConsoleApp2/blob/master/src/ConsoleApp2/Program.cs#L41)
- Call  context.SaveChanges(); https://github.com/Yanal-Yves/ConsoleApp2/blob/master/src/ConsoleApp2/Program.cs#L46

Issue:
- The child entity is not saved in the database

Expected result:
- As Child is a dependent entity and parent has been added to the context with GraphBehavior.IncludeDependents flag set, I expecte entity Framework to store the child entity in the storage when context.SaveChanges() is called

**Comment by rowanmiller** [comment]
The issue is that Child was actually the principal and Parent was the dependent. Julie's PR showed one way to reverse this.

**Comment by Yanal-Yves** [comment]
Julie showed me how to make it work in this commit https://github.com/Yanal-Yves/ConsoleApp2/commit/c99e3f2dcc444ddf21a1eda5d48a8ed83889f358 on the sample I provided. 

@rowanmiller in your comment you are saying that Julie showed "one way" to reverse this, suggesting there are other options. What other options do we have?

**Comment by rowanmiller** [comment]
@dneimke can you open a new issue and include the code for your entity classes and context. From the code you posted I can't tell if it is the same issue.

**Comment by rowanmiller** [comment]
@Yanal-Yves I would probably recommend the change Julie made, but if you really want to leave the classes un-modified then you could introduce a shadow state foreign key property on `ChildA` and then use the Fluent API to let EF know how the relationship should be setup:

```c#
modelBuilder.Entity<ChildA>()
    .Property<int>("ParentId);

modelBuilder.Entity<Parent>()
    .HasOne(p => p.ChildA)
    .WithOne()
    .HasForeignKey<ChildA>("ParentId");
```

BTW if you wanted to use the primary key of `ChildA` as the foreign key, then that is possible too:

```c#
modelBuilder.Entity<Parent>()
    .HasOne(p => p.ChildA)
    .WithOne()
    .HasForeignKey<ChildA>(c => c.ChildAId);
```

**Comment by dneimke** [comment]
Thanks @Yanal-Yves I got it working.  I didn't have the relationship configured - as I thought EF would pick it up via convention.
