### ISSUE TITLE
Migrations: DefaultValue created for new column that is a PK

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#3725]
This may be a weird scenario and not worthy of an issue but instead a "really, Julie?" for me. Take your pick. :)

I defined a one to one relationship the "old" way where I had the "dependent" class using its key as the FK to it's principal.
This resulted in a table with a PK FK column as expected.
Then, when I learned that in EF7 we can have our cake and eat it too, Since my original PK was not named using convention, I wanted this to remain an FK and then I added in a conventional key property named ID. 
Then I added a migration..

The migration removed the PK from the original property (it was not named using convention so became the obvious FK).
And then it created a new PK field. But the PK field was defined more fully than it would normally be and included the defaultvalue . When I tried to apply the migration, Sql server complained about a default value on a PK. Here is that bit from the migration.

```
migrationBuilder.AddColumn<int>(
            name: "Id",
            table: "SecretIdentity",
            nullable: false,
            defaultValue: 0)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        migrationBuilder.AddPrimaryKey(
            name: "PK_SecretIdentity",
            table: "SecretIdentity",
            column: "Id");
    }
```

If I edit the migration to remove the defaultvalue, it's fine. But then isn't my snapshot out of sync? (different question, I know...sorry)

**Comment by julielerman** [comment]
just for clarity, if I rolled migrations and the database to before I added that class and just created a migration that read the class that had separate PK and FK, the migration is perfectly fine. It was just that strange adjustment that I made from having a single property be both PK and FK then migrating that to the two separate properties.

**Comment by bricelam** [comment]
Good bug. We set a default value for any column that gets added and isn't nullable. This is just a Migrations thing and isn't part of the model metadata, so the model snapshot should remain valid.

It looks like SQL Server should ignore the default value for primary keys. It will only work end-to-end if there are no rows in table unless you write a custom step to copy the old key values.

**Comment by julielerman** [comment]
nothing like a bizarre edge case ;)

**Comment by julielerman** [comment]
..does beg the question about manually editing migrations though (wrt snapshots). Is that covered somewhere? Obviously doesn't belong hidden in this thread.

**Comment by bricelam** [comment]
Migrations are intended to be editable. The database *should* more-or-less match the model you've defined, but there's nothing enforcing that but you.

For example, required properties could map to nullable columns, foreign key constraints could be removed for better performance, etc. So long as the *data* EF reads in is consistent with the model you've defined everything will work. :smile:

I think we have issues in our docs repo to write more documentation on Migrations.

**Comment by rowanmiller** [comment]
We don't really expect folks to hit this, but we will fix in the future if we see customers hitting it.
