### ISSUE TITLE
Logging: Suggest silencing normal EF operations at `LogLevel.Warning`

### ISSUE THREAD

**Issue by dougbu** [dotnet/efcore#3731]
Logging in RC1 generally looks good with `loggerFactory.AddConsole(minLevel: LogLevel.Verbose)` or  `LogLevel.Information`. However see a few messages at `LogLevel.Warning` for normal situations. Suggest moving the following messages from that level (past `Information`) to `Verbose`:

```
warn: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[0]
      => RequestId:0HKNB4IP8TMEU RequestPath:/ => MusicStore.Controllers.HomeController.Index => Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor
      The LINQ expression 'orderby {[a].OrderDetails => Count()} desc' could not be translated and will be evaluated locally.
warn: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[0]
      => RequestId:0HKNB4IP8TMEU RequestPath:/ => MusicStore.Controllers.HomeController.Index => Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[0]
      => RequestId:0HKNB4IP8TMEU RequestPath:/ => MusicStore.Controllers.HomeController.Index => Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor
      The LINQ expression 'Take(6)' could not be translated and will be evaluated locally.
```

In the MusicStore app, these messages seem to appear only on the first request. But why output this information as warnings?

**Comment by ErikEJ** [comment]
This is important information, that parts of your queries do not run on the database server, and should not require verbose logging.  One could argue that they should even throw execeptions if enabled via a flag.

**Comment by dougbu** [comment]
:ok: how 'bout `Information` since it's up to the developer to decide whether executing everything inside the SQL engine is mandatory?

**Comment by rowanmiller** [comment]
I think you already got this.... but this isn't logging all SQL statements, just ones where we are actually doing client eval (which can be pretty bad in some cases). We did talk about having a flag to remove the warnings... would that make you happier if the message said ("you can stop us warning you about this by changing this flag...")

**Comment by dougbu** [comment]
@rowanmiller yup :smiley:

**Comment by anpete** [comment]
@dougbu Have you tried rewriting the LINQ queries to not require client-eval? This should be the first step, especially in a sample. We want to understand why client-eval is required here..

**Comment by dougbu** [comment]
@anpete I was testing w/ the MusicStore app. Doubt I'll get back to it soon. IOW better you than me :smiley_cat:

**Comment by rowanmiller** [comment]
Opened https://github.com/aspnet/EntityFramework/issues/3773 to track the ability to silence warnings (assigned to RTM release)
