### ISSUE TITLE
Generate better identifier names in SQL

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#3733]
Here's a typical EF6 query:

```
exec sp_executesql N'SELECT TOP (1) 
    [Project1].[C1] AS [C1], 
    [Project1].[MigrationId] AS [MigrationId], 
    [Project1].[Model] AS [Model], 
    [Project1].[ProductVersion] AS [ProductVersion]
    FROM ( SELECT 
        [Extent1].[MigrationId] AS [MigrationId], 
        [Extent1].[Model] AS [Model], 
        [Extent1].[ProductVersion] AS [ProductVersion], 
        1 AS [C1]
        FROM [dbo].[__MigrationHistory] AS [Extent1]
        WHERE [Extent1].[ContextKey] = @p__linq__0
    )  AS [Project1]
    ORDER BY [Project1].[MigrationId] DESC',N'@p__linq__0 nvarchar(4000)',@p__linq__0=N'EntityFrameworkTest.Migrations.Configuration'
```

I assume that's still representative for EF7. Names such as `Project1, Extent1, @p__linq__0` obfuscate the query a bit. Often, it is necessary to look at the generated SQL in various forms (profiler, server monitoring) and for various purposes (optimization, validation, understanding).

Can we make EF generate more reasonable names? For example `table1.Select(...)` should pick the table alias `table1` in SQL. Applying a `Where` to that should not change the name.

Naming aliases after the physical operator ("projection") does not seem useful. Try to heuristically generate smarter names. It does not have to work in all cases.

Maybe we can fix indenting as well (e.g. `FROM ( SELECT`). Also,there often seems to be unnecessary query nesting. On SQL Server this never has a performance impact but it obfuscates the query further and leads to people mistakenly claiming that EF is generating inefficient T-SQL.

Also, is it really necessary to bracket-escape all strings? For compatibility reasons no new T-SQL keywords can be introduced. Therefore, all safe names that are not in some well-known blacklist do not need to be bracketed. The blacklist is stable in the face of future SQL Server versions.

**Comment by ErikEJ** [comment]
I think your assumptions about EF7 are wrong...

**Comment by GSPP** [comment]
@ErikEJ then I hope that as much as possible of this feedback carries over to EF7.

**Comment by rowanmiller** [comment]
@GSPP EF7 is a completely new code base, so nothing from EF6 carries over. SQL generation is way cleaner in EF7, here are a few examples I just ran on RC1.

**Simple Query with Filter**

```c#
db.Posts
    .Where(p => p.Title == "Introducing EF7")
    .ToList();
```

```sql
SELECT [p].[PostId], [p].[BlogId], [p].[Content], [p].[Title]
FROM [Post] AS [p]
WHERE [p].[Title] = 'Introducing EF7'
```

**Including Related Data**

```c#
db.Posts
    .Include(p => p.Blog)          
    .Where(p => p.Title == "Introducing EF7")
    .ToList();
```

```sql
SELECT [p].[PostId], [p].[BlogId], [p].[Content], [p].[Title], [b].[BlogId], [b].[Url]
FROM [Post] AS [p]
INNER JOIN [Blog] AS [b] ON [p].[BlogId] = [b].[BlogId]
WHERE [p].[Title] = 'Introducing EF7'
```

If you have specific cases on EF7 where you think generation can be improved, then feel free to open issues with specific details.

**Comment by GSPP** [comment]
That's great news! I did not realize that.
