### ISSUE TITLE
DBContext.Table.Add() actually modifies the table before SaveChanges()

### ISSUE THREAD

**Issue by kennyrulez** [dotnet/efcore#3744]
Hello again!
Context: MVC6 and EF7 Beta8, SQLite backstore

I have a customer table and a linked table called CustomerAddress
Please view #3743 as reference for database schema.

When I need to update the CustomerAddresses, I'll move as follow

```
var customer = await _db.Customers.Include(c => c.CustomerAddresses).SingleOrDefaultAsync(c => c.Id == model.Id);
// select addresses to update
var updatedAddresses = model.CustomerAddresses.Intersect(customer.CustomerAddresses, new Utils.KeyEqualityComparer<CustomerAddress>(t => t.Id));
// select addresses to delete
var deletedAddresses = customer.CustomerAddresses.Except(model.CustomerAddresses, new Utils.KeyEqualityComparer<CustomerAddress>(t => t.Id));
// select addresses to add
var newAddresses = model.CustomerAddresses.Except(updatedAddresses, new Utils.KeyEqualityComparer<CustomerAddress>(t => t.Id));

foreach (var na in newAddresses)
{
    na.Customer = customer;
    _db.CustomerAddresses.Add(na);
}
....
```

During debug, when the code hit 

```
_db.CustomerAddresses.Add(na)
```

this actually updates the table. In fact, if I use shitf+f9 on the "customer" I can see that Customer.CustomerAddresses has 1 more entry (or more, in case the foreach has multiple elements).
And  SaveChanges() still has to be hit.
This behavior lead a problem: if I cycle through updatedAddresses, I see the recently added one(s) from the foreach, wasting resources.

Send help!!!
Thank you
Valerio

**Comment by smitpatel** [comment]
When you add an entity to DBSet by `_db.CustomerAddresses.Add(na)`, EF will start tracking that entity and appropriately all dbsets will be updated hence `customer.CustomerAddresses` will contain that newly added entity. These are local changes, `SaveChanges()` just propagate this local changes to the database server. So you are expected to see updates happening in the local data.

The issue you are hitting can be result of `Enumerable` as you have used linq methods, the return value is `Enumerable` type which will be evaluated when you actually enumerate. So when you go through updatedAddresses, you will see the recently added one(s) from previous foreach loops. Using `ToList()` after `Intersect` & `Except` methods should fix the issue.

**Comment by kennyrulez** [comment]
Thank you @smitpatel
Is this a change from ef6? I don't remember this behaviour on the previous builds

Thanks again.
