### ISSUE TITLE
Issue Specifying Indexes

### ISSUE THREAD

**Issue by eriksendc** [dotnet/efcore#3747]
I've tried adding [Index] as an annotation of a column, and a fluent api code snipit:

```
modelBuilder 
    .Entity<Person>() 
    .Property(t => t.Name) 
    .HasColumnAnnotation( 
        "Index",  
        new IndexAnnotation(new IndexAttribute("IX_Name") { IsUnique = true }));
```

In either case I cannot get IndexAnnotation to resolve. Is this going to come out in the EF7 RC? If not, how do we define indexes via Code First?

**Comment by rowanmiller** [comment]
Here are the docs on specifying indexes - http://ef.readthedocs.org/en/latest/modeling/configuring.html#indexes

**Comment by rowanmiller** [comment]
```
modelBuilder 
    .Entity<Person>() 
    .Index(t => t.Name);
```

**Comment by eriksendc** [comment]
Thanks, Rowan!!!!
