### ISSUE TITLE
Scratch databases not disposed during testing

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3749]
![image](https://cloud.githubusercontent.com/assets/2696087/11153815/5d0a703a-89f0-11e5-86cf-799a90824399.png)

**Comment by ErikEJ** [comment]
What is the problem ? :smile:

**Comment by natemcmaster** [comment]
If testing fails, the following run will also fail because it does not start with a clean db file. Example: 

![image](https://cloud.githubusercontent.com/assets/2696087/11153995/5b54f278-89f1-11e5-8beb-b6bbc4644615.png)

**Comment by ErikEJ** [comment]
Maybe use inmemory? https://sqlite.org/inmemorydb.html

**Comment by bricelam** [comment]
@ErikEJ We'd have to use named, shared-cache, in-memory databases and manage the lifetime in our testing framework because once all the connections are closed, the database goes away. It was just easier to use an on-disk database for now.

**Comment by natemcmaster** [comment]
This is not longer limited to SQLite. Remarking for triage as SQL Server tests fail often because the previous run failed to cleanup the scratchdb.mdf file.

![image](https://cloud.githubusercontent.com/assets/2696087/11385464/fc382f36-92cd-11e5-94f5-b834461cb15c.png)

**Comment by smitpatel** [comment]
Most EF builds on CI are failing due to this flakiness.

**Comment by AndriySvyryd** [comment]
Even though the scratch dbs are deleted the localdb issue is still present, I've opened a different issue to track it: #3902
