### ISSUE TITLE
options.UseSqlServer (Full .NET App - WPF)

### ISSUE THREAD

**Issue by HClausing** [dotnet/efcore#3767]
Sorry for this post. I know this isn't a help fórum, but I have installed beta 8 on my sample WPF application for learning purposes and I can't found a method 'UseSqlServer' like many tutorials over here on ModelConfiguring override.

What I'm doing wrong?

Instaled: EntityFramework.SqlServer beta 8 and it' dependecies and EntityFramework.Commands.

**Comment by ErikEJ** [comment]
Add

    using Microsoft.Data.Entity;

**Comment by HClausing** [comment]
Thanks for the quick answer, but I already tried it.

This is my DbContext class (written in vb.net):

Imports Microsoft.Data.Entity

Namespace Domain.Contexts

    Partial Public Class AdventureWorks
        Inherits DbContext

        Public Overridable Property Product As DbSet(Of Classes.Product)
        Public Overridable Property ProductCategory As DbSet(Of Classes.ProductCategory)

        Protected Overrides Sub OnConfiguring(optionsBuilder As DbContextOptionsBuilder)
            optionsBuilder.UseSqlServer()   '<--- 'UserSQLServer' not found..
            MyBase.OnConfiguring(optionsBuilder)
        End Sub

    End Class

End Namespace

**Comment by rowanmiller** [comment]
You need to pass a connection string to `UseSqlServer`, could that be the issue? There is no parameter-less overload.

**Comment by HClausing** [comment]
I have tried too, here's a screenshot:

![usesqlservererror](https://cloud.githubusercontent.com/assets/15158923/11227962/980761b0-8d70-11e5-96e1-b60e204c8644.png)

**Comment by divega** [comment]
Have you installed the EntityFramework.SqlServer package? In EF6 this was included in the default EntityFramework package but in EF7 you need to install the provider in order to get access to SQL Server databases.

**Comment by divega** [comment]
I see now in your original message that you said you had it installed, however the provider package missing is the only explanation I can think of for this error.

**Comment by HClausing** [comment]
Thanks again. You answer very fast!

Screenshots of referencies and Packages (on a .NET 4.6 WPF Application):

![usesqlservererror2](https://cloud.githubusercontent.com/assets/15158923/11228894/697731e8-8d77-11e5-8138-922a4b2e56f6.png)
![usesqlservererror3](https://cloud.githubusercontent.com/assets/15158923/11228893/69735370-8d77-11e5-9cb4-846c0841797b.png)

**Comment by Joe4evr** [comment]
The EF7 package was renamed to EntityFramework.MicrosoftSqlServer since beta7. See aspnet/Announcements#85

**Comment by HClausing** [comment]
Ok thanks, but searching on nuget packages online I can't found any called 'EntityFramework.MicrosoftSqlServer', and the package 'EntityFramework.SqlServer' is instaled at version 7.0.0-beta 8 (see https://www.nuget.org/packages/EntityFramework.SqlServer/7.0.0-beta8)

"Include Prereleases" is checked.

**Comment by HClausing** [comment]
Update: Installing EntityFramework.InMemory (beta 8) I can see the '.UseInMemoryDatabase' method. I believe that's a EntityFramework.MicrosoftSqlServer package missing on nuget, or the available EntityFramework.SqlServer (beta 8) maybe is using old assemblies?

Sorry if I'm boring you, I'm just trying to help, testing EF7 with Sql Server.

**Comment by ErikEJ** [comment]
You are mixing version 6 and 7 packages in your project. Remove all NuGet packages and install:

     EntityFramework.MicrosoftSqlServer

(RC1 available today!)

**Comment by HClausing** [comment]
Thanks again. That's a very good News! Now I can see the  EntityFramework.MicrosoftSqlServer package on nuget, but I have this error whrn trying to install:

```
Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.
```

I have removed ALL the packages on Project and tried again. No sucess.

**Comment by HClausing** [comment]
Status: SOLVED by manually add 'System.Collections.Concurrent.dll' reference from:

<user_foldedr>\Documents\Visual Studio 2015\Projects\<solution_folder>\packages\System.Collections.Concurrent.4.0.11-beta-23516\lib\dotnet5.4

After it, Nuget package installs correctly.

So many thanks for all. God bless you all.
