### ISSUE TITLE
Are nested entity relationships not supported?

### ISSUE THREAD

**Issue by jhrendon40** [dotnet/efcore#3788]
If I do something like:

 var results = await _context.ChartDocumentTypes.Include(v=>v.ChartDocumentSubTypes.Where(c=>c.IsActive))
                .Where(d => d.PracticeId == practiceId && d.IsActive)
                .OrderBy(d => d.Description)
                .ToListAsync();

I get:

An unhandled exception has occurred: Unable to cast object of type 'Remotion.Linq.Clauses.Expressions.SubQueryExpression' to type 'System.Linq.Expressions.MemberExpression'.

**Comment by jhrendon40** [comment]
I am using  Beta8  ...

{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Domain.Entities.MainBC": "1.0.0-*",
    "EntityFramework.Core": "7.0.0-beta8",
    "EntityFramework.Commands": "7.0.0-beta8",
    "Domain.MainBoundedContext": "1.0.0-*",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8"
    
  },

   "commands": {
        "ef":   "EntityFramework.Commands"
    },

  "frameworks": {
    "dnx451": {
      "dependencies": {

      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.11-beta-23409",
        "System.Linq": "4.0.1-beta-23409",
        "System.Threading": "4.0.11-beta-23409",
        "Microsoft.CSharp": "4.0.1-beta-23409"
      }
    }
  }
}

**Comment by maumar** [comment]
@jhrendon40 Include method can only accept member access expression, which can be nested in case of references, e.g.

```
customers.Include(c => c.Detail.Address)
```

Filtering and other operations on the included navigation is not supported.
