### ISSUE TITLE
Join object then sum error

### ISSUE THREAD

**Issue by GunterGlad** [dotnet/efcore#3791]
When I try to run this linq expression:
         var list5 = context.Contacts.Select(x =&gt; new
         {
            Customer = x.Customer.Name,
            PaymentTotal = x.Customer.Payments.Sum(p =&gt; p.PaymentAmount)
         }).ToList();

I get this error:
//Error:variable 't0' of type 'Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.Data.Entity.Storage.ValueBuffer,Microsoft.Data.Entity.Storage.ValueBuffer]' referenced from scope '', but it is not defined 

Here is my context:

public class AppDBContext: DbContext, { 
  public DbSet&lt;Contact&gt; Contacts { get; set; } 
  public DbSet&lt;Customer&gt; Customers { get; set; }
  public DbSet&lt;Payment&gt; Payments { get; set; }
}

Here are my classes:
public class Contact 
   {
      #region Customer
      public int CustomerID { get; set; }
      public virtual Customer Customer { get; set; }
      #endregion 
   }

public class Customer 
   {
      public string Name { get; set; }
      public virtual ICollection&lt;Contact&gt; Contacts { get; set; }
      public virtual ICollection&lt;Payment&gt; Payments { get; set; }
  }

public class Payment 
   {
      #region Customer
      public int CustomerID { get; set; }
      public virtual Customer Customer { get; set; }
      #endregion Customer

```
  public decimal PaymentAmount { get; set; }
```

  }

**Comment by GunterGlad** [comment]
FYI: EF7.0.0-RC2-16332

**Comment by maumar** [comment]
Looks very similar to #3499. Possibly the fix was not complete or its not in build 16332 yet. Will investigate.

**Comment by maumar** [comment]
@GunterGlad this works in current bits
