### ISSUE TITLE
How do I disable OneToMany and ManyToMany Cascade Delete as of rc1?

### ISSUE THREAD

**Issue by cda-1** [dotnet/efcore#3815]
In EF6, I could do:
builder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
builder.Conventions.Remove<ManyToManyCascadeDeleteConvention>();

In previous iterations of EF7 it wasn't supported. But now that it's supported, I can't figure out how to turn it off globally.

**Comment by aconstant** [comment]
Wondering too.

I have disabled it manually on some relationships :

    builder.Entity<Site>().HasOne(e => e.Person)
      .WithMany(x => x.Sites).Metadata.DeleteBehavior = DeleteBehavior.Restrict;

**Comment by rowanmiller** [comment]
If you want to change the delete behavior for all relationships, then you can use this code in `OnModelCreating(...)` to bulk set it for all relationships in your model.

```
foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
{
    relationship.DeleteBehavior = DeleteBehavior.Restrict;
}
```

**Comment by cda-1** [comment]
Excellent, thank you!

**Comment by darekjk** [comment]
thanks.

**Comment by she2** [comment]
Thanks @rowanmiller. That's a nice work around

**Comment by Andrioden** [comment]
Here is how you default to Restrict for all except Identity Entities

```
List<IMutableEntityType> identiyEntities = new List<IMutableEntityType>
{
    modelBuilder.Model.FindEntityType(typeof(User)),
    modelBuilder.Model.FindEntityType(typeof(IdentityRole)),
    modelBuilder.Model.FindEntityType(typeof(IdentityUserRole<string>)),
    modelBuilder.Model.FindEntityType(typeof(IdentityUserClaim<string>)),
    modelBuilder.Model.FindEntityType(typeof(IdentityUserLogin<string>)),
    modelBuilder.Model.FindEntityType(typeof(IdentityUserToken<string>)),
    modelBuilder.Model.FindEntityType(typeof(IdentityRoleClaim<string>)),
};
foreach (var relationship in modelBuilder.Model.GetEntityTypes().Except(identiyEntities).SelectMany(e => e.GetForeignKeys()))
    relationship.DeleteBehavior = DeleteBehavior.Restrict;
```

**Comment by diegoernestofarias** [comment]
@rowanmiller one little fix to your answer.

After the `GetEntityTypes()` method, is neccesary to add `.Where(e => !e.IsOwned())`, if not, the complex objects of the entity will not be deleted. #10179 

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder) {
        foreach (var relationship in modelBuilder.Model.GetEntityTypes().Where(e => !e.IsOwned()).SelectMany(e => e.GetForeignKeys())) {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
        }
}
```

**Comment by TehWardy** [comment]
Don't do what i just did and forget to regenerate the migration too.
For some odd reason EF Core doesn't have the "telepathy extension" yet ... dam lazy devs!!!

Do what i mean and not what I write dam you !!!

**Comment by raygao** [comment]
**Doesn't work any more, there is not .Where or .SelectMany method in the using Microsoft.EntityFrameworkCore;  I am getting compilation errors. Could someone please help?**

Data/SpmDbContext.cs(15,78): error CS1061: 'IEnumerable<IMutableEntityType>' does not contain a definition for 'SelectMany' and no accessible extension method 'SelectMany' accepting a first argument of type 'IEnumerable<IMutableEntityType>' could be found (are you missing a using directive or an assembly reference?)

**Comment by Andrioden** [comment]
@raygao 

`using System.Linq;`

**Comment by raygao** [comment]
I have that include, and it still does not work.
My code is below. All I want to do is to set global restrict instead of disabling cascading delete per entity.
        // protected override void OnModelCreating(ModelBuilder modelBuilder)
        // {
        //     foreach (var entity in modelBuilder.Model.GetEntityTypes())
        //     {
        //         foreach (var relationship in entity.GetProperties().SelectMany(t => t.GetContainingForeignKeys()))
        //         {
        //             relationship.DeleteBehavior = DeleteBehavior.Restrict;
        //         }
        //     }

        //     base.OnModelCreating(modelBuilder);
        // }
