### ISSUE TITLE
Trying to serialize an entity with a circular dependency causes a "HTTP Error 502.3 - Bad Gateway" error page.

### ISSUE THREAD

**Issue by cda-1** [dotnet/efcore#3818]
I have HttpPlatformHandler 1.2 installed. I get the error in both IISExpress and IIS proper on Windows 10.

If I do a GET against my API that returns an entity without a circular dependency, it comes right up. If I GET one with a circular dependency, I see the Bad Gateway error.

Of course, this is my own darn fault and is resolved by using models without such circular dependencies, or this config:

```
        services.AddMvc().AddJsonOptions(options => {
            options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
        });
```

However, it seems odd to get the Bad Gateway page. Should be a 500 error, right, not a 502?

**Comment by jemiller0** [comment]
Why are you posting this under EntityFramework?

**Comment by cda-1** [comment]
Sorry, I'm new here. 

I searched the web for the error message I experienced and found [this discussion](https://github.com/aspnet/Home/issues/1000). An ostensibly experienced user there [recommended](https://github.com/aspnet/Home/issues/1000#issuecomment-158231801) that I post the issue here.

What is the best place to report this, in your opinion? Maybe KestrelHttpServer?

**Comment by rowanmiller** [comment]
Hey,

I read through the other issue and I don't see anything that would indicate EF is in the picture. You say you are getting the entities from the database using EF, but my understanding from the discussion is that the exception is happening during serialization rather than while EF is fetching the entities. Is this correct?

~Rowan

**Comment by cda-1** [comment]
I suspect that I could repeat this issue with a circular dependency in viewmodels, completely outside EF, so I think you are probably correct. The issue isn't so much that there's an exception, but rather the error message itself. I guess it's a Kestrel issue? Or would it actually be a JSON.NET issue?

**Comment by rowanmiller** [comment]
I suspect JSON.NET, but I could be wrong

**Comment by cda-1** [comment]
I'll keep digging. Thanks!
