### ISSUE TITLE
Error Message from ModelValidator

### ISSUE THREAD

**Issue by SergeBerwert** [dotnet/efcore#3823]
Got this error Message from ModelValidatur:

The entity type 'object' requires a key to be defined.

I think i should say the Entity type instead of object.

**Comment by rowanmiller** [comment]
@SergeBerwert can you share the model that threw this exception? It could well be that we were trying to map `object` as part of your model.

**Comment by SergeBerwert** [comment]
Hi Rowan in the meantime I fixed issues on my model, but it looks like I accidently mapped the System.Attribute class instead of an Entity with the name Attribute.

**Comment by rowanmiller** [comment]
That makes sense. `System.Attribute` has a `TypeId` property that is of type `object`, so we are trying to include that in the model (via navigation property traversal).
