### ISSUE TITLE
Migrations: Using migrations when DBContext is in other class library wont find migrations or update database

### ISSUE THREAD

**Issue by kellerd** [dotnet/efcore#3840]
Repro here: https://github.com/kellerd/EPhotoGallery/tree/EF7RC1

Have a [ASP.NET 5 RC1](https://github.com/kellerd/EPhotoGallery/tree/EF7RC1/src/MVC6) project referencing EF7RC1 and EF.Commands.
Also have a [Class Library](https://github.com/kellerd/EPhotoGallery/tree/EF7RC1/src/PhotoLibrary/) storing the DBContext.

Adding a migration correctly puts a new migration in the migrations folder.  [MVC6/Migrations](https://github.com/kellerd/EPhotoGallery/tree/EF7RC1/src/MVC6/Migrations)
Calling migrations list, finds no migrations.
Calling ef database update, creates an empty database. With the correct name specified in the DBContext.
Calling ef database update Init, does not find migration 'Init' created previously

C:...Projects\MVC6\src\MVC6> dnx ef migrations add Init
Done. To undo this action, use 'ef migrations remove'
C:...Projects\MVC6\src\MVC6> dnx ef migrations list
No migrations were found
C:...Projects\MVC6\src\MVC6> dnx ef database update
Done
C:...Projects\MVC6\src\MVC6> dnx ef database update Init
The migration 'Init' was not found.

Moving the [DBContext file](https://github.com/kellerd/EPhotoGallery/tree/EF7RC1/src/PhotoLibrary/PhotoInfo.cs) to the ASP.NET project makes all the above commands work.

**Comment by bricelam** [comment]
We need some good documentation on splitting things into separate projects...

You can add `.MigrationsAssembly("MVC6")` after your call to `UseSqlServer`.

**Comment by kellerd** [comment]
Cheers. Maybe a case of a Builder not needing an expicit Build() method made me trip before falling into the 'pit of success'. Close if ticket unnecessary.

**Comment by bricelam** [comment]
If nothing else, we could probably warn if the migrations assembly isn't the one you're adding migrations to.

**Comment by rowanmiller** [comment]
We are tracking all these scenarios via https://github.com/aspnet/EntityFramework/issues/3879
