### ISSUE TITLE
Consider DbContext.SchemaValidate for integration test purposes

### ISSUE THREAD

**Issue by YehudahA** [dotnet/efcore#3841]
Please consider to provide something like `DbContext.SchemaValidate()` that throws an exception when the model is not is sync with the DB, so I can write an Integration test:

``` csharp
[Fact]
public void ContextSchemaTest()
{
    dbContext.SchemaValidate();
}
```

**Comment by rowanmiller** [comment]
What do you want it to do? I'm not trolling :smile:... there are various ways to reason about the model/database being in-sync. There are some low level components you can use to ensure that there are no pending model changes that have not been written to a migration. Currently, EF does not reason about the actual schema of the database though.

**Comment by YehudahA** [comment]
My goal is to write a test that checks whether the model is in-sync.
Whether I use database first or code first, the test method should not be aware of it.

I can do that through a loop on all the properties of the DbContext class, and test each of them using FirstOrDefault.

Is there a simpler way? I'll be happy to know.

**Comment by rowanmiller** [comment]
That's probably the easiest way at the moment. You could look at using the reverse engineer components to get a model that represents the database and then do a comparison... more work, but potentially very interesting as a third party extension to EF :smile:

**Comment by YehudahA** [comment]
I  hope someone will pick up the gauntlet that thrown by @rowanmiller , because it is beyond my ability.

meanwhile, I wrote the following code.


**DbContextTestHelper class:**

``` csharp
public static class DbContextTestHelper
{
    public static void TestDbContext<TContext>(TContext context) where TContext : DbContext
    {
        var getFirstMethod = typeof(DbContextTestHelper).GetMethod("GetFirstObject", BindingFlags.Static | BindingFlags.NonPublic);
        var dbSetTypeList = GetDbSetTypeList<TContext>();

        foreach (var dbSetType in dbSetTypeList)
        {
            var genericMethod = getFirstMethod.MakeGenericMethod(dbSetType);
            var obj = genericMethod.Invoke(null, new object[] { context });
        }
    }

    private static List<Type> GetDbSetTypeList<TContext>() where TContext : DbContext
    {
        var dbSetTypeList = new List<Type>();
        var contextType = typeof(TContext);
        foreach (var property in contextType.GetProperties())
        {
            if (!property.PropertyType.IsGenericType
                || property.PropertyType.GetGenericTypeDefinition() != typeof(DbSet<>))
                continue;

            var dbSetType = property.PropertyType.GetGenericArguments()[0];
            dbSetTypeList.Add(dbSetType);
        }

        return dbSetTypeList;
    }

    private static TEntity GetFirstObject<TEntity>(DbContext context)
        where TEntity : class
    {
        var dbset = context.Set<TEntity>();
        return dbset.AsNoTracking().FirstOrDefault();
    }
}
```

**Usage:**
``` csharp
[Fact]
public void TestMyContext()
{
    // Arrange
    var context = new MyContext();

    // Act
    // Assert: if model not in sync then exception will be thrown.
    DbContextTestHelper.TestDbContext(context);
}
```
