### ISSUE TITLE
Build error: unable to locate Microsoft.Extensions.CommandLineUtils.Sources

### ISSUE THREAD

**Issue by jonnybee** [dotnet/efcore#3846]
Downloaded latest bits and tried to run "build.cmd": 

D:\Github\aspnet\EntityFramework>build > log.txt
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*
Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*

Errors in D:\Github\aspnet\EntityFramework\test\EntityFramework.Commands.Tests\project.json
    Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*

Errors in D:\Github\aspnet\EntityFramework\src\EntityFramework.Commands\project.json
    Unable to locate Dependency Microsoft.Extensions.CommandLineUtils.Sources >= 1.0.0-*

Also tried to run "build initilalize" before open source in VS2015 and this also failed with the same errors.

**Comment by rowanmiller** [comment]
@natemcmaster can you take a look at this one

**Comment by natemcmaster** [comment]
@jonnybee which commit are you trying to build? `Microsoft.Extensions.CommandLineUtils.Sources` is available on http://myget.org/gallery/aspnetcidev, so it is possible your project did not download this correctly.

**Comment by jonnybee** [comment]
I'm trying to build commit 459c862. I cloned the repository using Sourcetree and everything is clean inside the project folder.

**Comment by natemcmaster** [comment]
@jonnybee can you execute this command from Command Prompt in the project root directory?
```dnu feeds list```.

This should display something like:

```
C:\Users\user\dev\ef>dnu feeds list
Feeds in use:
    https://api.nuget.org/v3/index.json
      Origin: C:\Users\user\AppData\Roaming\NuGet\nuget.config
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
      Origin: C:\Users\user\dev\ef\.\nuget.config
    https://api.nuget.org/v3/index.json
      Origin: C:\Users\user\dev\ef\.\nuget.config

NuGet Config files in use:
    C:\Users\user\AppData\Roaming\NuGet\nuget.config
    C:\Users\user\dev\ef\nuget.config
    C:\Users\user\dev\ef\.\nuget.config
```

Also, could you post the full log.txt file? (Drag+drop your log into a new [gist](http://gist.github.com) and post a link here.)

**Comment by jonnybee** [comment]
Hmmm, I deleted all my custom NuGet sources in Visual Studio, cleaned all packages and rerun build. 

Now the build completes and reports OK.

**Comment by natemcmaster** [comment]
NuGet sources can be fickle. Glad you got it fixed. Welcome to developing EF!
