### ISSUE TITLE
Building EF7 database model (beta 8) fails under x64 but works under x86

### ISSUE THREAD

**Issue by KarlAndenmatten** [dotnet/efcore#3848]
We have in our uwp-application now installed EntityFramework.Sqlite 7, Beta8 and have dicovered (by chance) a strange problem:
Our EF-model works fine under x86 but crashes under x64, very strange.

Under x64 we get the following error:
"System.InvalidOperationException: The navigation property 'ArticleConnections' cannot be added to entity type 'Opacc.Mof.Client.Service.DataModel.Article' 
because its CLR type 'System.Collections.Generic.List`1[[Opacc.Mof.Client.Service.DataModel.ArticleConnection, Opacc.Mof.Client.Service.DataModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' 
does not match the expected CLR type 'Opacc.Mof.Client.Service.DataModel.ArticleConnection'.

It looks like that under x64 EF wants to create a Article. ArticleConnections as ArticleConnection instead ofIList<ArticleConnection>

The exactly same model works when we build it under x86.
For me this sounds very strange but perhaps somebody has an idea for this ‚bug‘ (or ever seen some differences between x86/x64).

In my git-repository https://github.com/KarlAndenmatten/Source-Code you find the zip-file 'EF7BugWhenBuildx64.zip' which reproduces the problem. The solution includes our two database-access projects and is therefore a little bit large but this shouldn't be bothersome.

**Comment by poke** [comment]
> But i don't know how to attach here zip-files

You can just create a new repository under your account where you push your example project and then people can look at it.

**Comment by KarlAndenmatten** [comment]
Thanks poke for the hint, i have now under my account a repository created and uploaded the example solution which reproduces the bug.

**Comment by rowanmiller** [comment]
@KarlAndenmatten we fixed some issues related to x64/x86 in RC1, can you retry on the latest preview and see if the issue still exists.

**Comment by KarlAndenmatten** [comment]
@rowanmiller I have now installed RC1 and it seems that the bug is fixed, thanks!
