### ISSUE TITLE
Scaffolding tries to load your project before dumping models.

### ISSUE THREAD

**Issue by NullVoxPopuli** [dotnet/efcore#3849]
The command I'm using:

```
dnx ef dbcontext scaffold "Server=computer\me;Database=mydb;Trusted_Connection=True;" EntityFramework.MicrosoftSqlServer --outputDir DatabaseModels
```

Issue:

I have a database where I don't have control over when it gets changed, so I've decided to abstract the generated models, so if the database changes, I just re-generate the scaffolded models and that's it.
My problem is that once my program starts using the scaffolded models and I delete the folder the models are outputted in before regenerating, `dnx ef` seems to load my whole program, which has errors, cause I deleted the db models directory.

The order of what I did: 
1. Delete DatabaseModels folder
2. run scaffold command
3. I am required to comment out all references to everything isside the DatabaseModels folder.
4. run scaffold command again -- this time it works
5. run scaffold command a second time, to see if the problem still exists -- it works just fine
6. run `dnx run` I get an error about `DbSet<User>` not containing a definition for `find` 
7. I try running the scaffold command again -- this time it errors, saying that it couldn't load my namespace (specifically only on the User model)
8. I rename my Models/User abstraction to CurrentUser (different from DatabaseModels/User)
9. same as 6
10. same as 7.

So.. what's going on?

I can't show my repository, as it's kinda closed source, but Here is some of the code I have:

Program.cs

``` csharp
﻿using System;
using Microsoft.Data.Entity;
using SomeNamespace.DatabaseModels;

namespace SomeNamespace
{
    public class Program
    {
        public static void Main()
        {
            var context = new ScaffoldedDbContext();
        }
    }
}
```

Models/CurrentUser.cs

``` csharp
using System;
using System.Dynamic;
using System.Collections.Generic;
// NOTE: This may need to be commented out when regenerating the Database Models
using UserFromDb = SomeNamespace.DatabaseModels.User;
// this is based off the database name, so the actual
// context class name is subject to change
// NOTE: This may need to be commented out when regenerating the Database Models
using MyContext = SomeNamespace.DatabaseModels.ScaffoldedDbContext;

namespace SomeNamespace.Models
{
  public partial class CurrentUser : DynamicObject
  {
    public readonly long Id;
    public readonly MyContext Db;
    public readonly UserFromDb Me;


    public CurrentUser(long id)
    {
      this.Id = id;

      // instantiate our interface to the database
      this.Db = new MyContext();

      // find the database user
      Me = this.Db.User.FirstOrDefault(u => u.UserId == Id);
    }

    #region Dynamic Access to UserFromDb and Nested Objects

    // Ran before a property access
    public override bool TryGetMember(
      GetMemberBinder binder,
      out object result)
    {
      result = false;
      return true;
    }

    // Ran before a method call
    public override bool TryInvokeMember(
      InvokeMemberBinder binder,
      object[] args,
      out object result)
    {
      result = false;
      return true;
    }

    #endregion
  }
}

```

and DatabaseModels/User.cs:

``` csharp
using System;
using System.Collections.Generic;

namespace SomeNamespace.DatabaseModels
{
    public partial class User
    {
        public User()
        {
          // ton of property setting
        }

        // ton of fields
        // ton of relationships

    }
}

```

In the scaffolded context:

``` csharp
modelBuilder.Entity<User>(entity =>
{
... 
})
```

**Comment by rowanmiller** [comment]
@NullVoxPopuli can you post the command line output that you are seeing.

**Comment by poke** [comment]
The `ef` commands require the project to build without errors; I believe this is mostly because the EF configuration is read from the project prior to the execution. So if you remove classes from your project which are referenced elsewhere, those references will break, making the project no longer compile, and as such stop the `ef` commands from working.

Of course, for the scaffolding command this only makes limited sense since you are required to specify the whole connection on the command line anyway, but I guess that’s just a sideeffect from being the otherwise same thing that executes the script.

You could try using the `--output-dir` argument to scaffold the database into a different folder, so that you can keep the previous version where it is until you generated the new files. And then you can replace the original ones.

**Comment by rowanmiller** [comment]
@poke agreed - but as you said we really have everything we need for reverse engineering, without needing to load code from the project.

**Comment by lajones** [comment]
Unfortunately this is a `dnx` limitation rather than `ef` specifically. Running any `dnx` command kicks off the build step. If build fails you never get as far as running the command :-(

**Comment by rowanmiller** [comment]
Does reverse engineer overwrite files if they exist? i.e. can you just run it with the existing code in place?

**Comment by lajones** [comment]
Yes, provided the files are writeable - otherwise you'll get an error. But the whole project needs to be building successfully first before any command can run.

**Comment by rowanmiller** [comment]
@NullVoxPopuli that should solve your scenario, you can re-scaffold without deleting the original model files.

BTW I opened https://github.com/aspnet/EntityFramework/issues/3856 as we probably shouldn't overwrite files without a -force flag.

**Comment by NullVoxPopuli** [comment]
thanks for answering my question :-)

**Comment by rowanmiller** [comment]
@bricelam will the need for the project to build (when we aren't interested in the assemblies) go away with the upcoming changes to commands?

**Comment by rowanmiller** [comment]
Scrap that, you always need to be able to build as we will discover services from your project.

**Comment by rowanmiller** [comment]
BTW we may try and improve this in the future if it causes a lot of pain... but we expect it to be difficult/expensive to implement.
