### ISSUE TITLE
Rc1 added "cascade delete" to all of my relationships

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#3851]
After upgrading to RC1 from Beta8, when I generate a new migration, it wants to drop all of my FK's and recreate them with a cascade delete.
How can I disable this as the default behavior?

**Comment by smitpatel** [comment]
@joshmouch - Migration drops and recreates all FKs due #3751 
By conventions EF will set cascade delete for all the require foreign keys. If you don't want "cascade delete" then you should make your foreign key not required. You can read about it in the docs at http://ef.readthedocs.org/en/latest/modeling/relationships.html

**Comment by rowanmiller** [comment]
If you want to change the delete behavior, then you can use this code in `OnModelCreating(...)` to bulk set it for all relationships in your model.

```
foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
{
    relationship.DeleteBehavior = DeleteBehavior.Restrict;
}
```

**Comment by joshmouch** [comment]
@rowanmiller Thanks for the prompt reply!  The problem with that default behavior is that somehow now I have cyclical deletes.  I'll run the code you gave me.
