### ISSUE TITLE
dbcontext scaffold - One Table

### ISSUE THREAD

**Issue by ms-denver** [dotnet/efcore#3859]
Is it possible to run scaffolding against a database for ONE table only?

When I run it against my entire database I get errors related to no primary key.

**Comment by rowanmiller** [comment]
Yes `--table dbo.Products`

**Comment by jdiapps** [comment]
Any way around this problem:

Identity value generation cannot be used for the property 'p_id' on entity type 'table' because the property type is 'Decimal'. Identity value generation can only be used with signed integer properties.

**Comment by rowanmiller** [comment]
@jdiapps I'm closing out this issue as we have dealt with the original topic of the issue (scaffolding for a single table). Feel free to open a new issue for the follow up issue. You'll need to include some more info for us to be able to debug the issue (the database schema you are reverse engineering from, the code that encounters the exception, and the full stack trace would be useful).
