### ISSUE TITLE
Can't update datebase correctly when define the DbContext class in other project.

### ISSUE THREAD

**Issue by Tiscs** [dotnet/efcore#3873]
## Steps:
1. Create asp.net 5 project `Sample`;
2. Create Class Library (Package) `Sample.Core` and create a DbContext class `MainDbContext`, then add an Entity class `Logs`, reference this project on project `Sample`;
3. Execute `dnx ef migrations add AddLogs` on project `Sample`, output message `Done. To undo this action, use 'ef migrations remove'`;
4. Execute `dnx database update` on project "Sample", output message `Done.`, and the target database just contains a empty table `__EFMigrationsHistory`;
5. Execute `dnx ef migrations list` on project `Sample`, output message `No migrations were found`;
6. Move codes from project `Sample.Core` to project `Sample`, then redo step 3 & 4, table `Logs` added to database correctly.

**Comment by Tiscs** [comment]
After read the code file [EntityFramework.Commands/Commands/Program.cs](https://github.com/aspnet/EntityFramework/blob/7e59dfcb26ca6c5952d54ead8c1cbd2a4df2a54e/src/EntityFramework.Commands/Commands/Program.cs), I tried to execute ```ef migrations``` or ```ef database``` command with an other option ```-p Sample.Core``` (```-p``` is short for ```--target-project```, means ""), database structure & script generate correctly.

But I want to define DbContext class in project ```Sample.Core``` and generate migrations in project ```Sample```(Because I want to create a modular system, the web project ```Sample``` is just a shell which used to load modules), can I do that?

**Comment by c1rus** [comment]
i ran into the same problem...

**Comment by c1rus** [comment]
look at this: https://github.com/aspnet/EntityFramework/issues/3840

**Comment by rowanmiller** [comment]
@bricelam can you share some thoughts on this one

**Comment by bricelam** [comment]
@c1rus is right, just like in #3840, you need to call `MigrationsAssembly`
