### ISSUE TITLE
Sentinel Value of a property is gone without a mention of it anywhere

### ISSUE THREAD

**Issue by janpieterz** [dotnet/efcore#3874]
I just updated from beta8 to rc1 and cannot find a way to set the sentinel value of a property.
Checked the announcements repo + the documentation but neither of them mention it as far as I could find.

**Comment by poke** [comment]
Sentinel values were removed completely. So if you previously had to set the sentinel metadata to support existing elements with that value, you no longer need to do that. You can just remove the `.Metadata.Sentinel = x` part and it should work.

The only thing you might want to add for key properties is `ValueGeneratedNever()` which will prevent those values from being auto-generated when the value equals to the type’s default value. But you only need to do that when you insert an item with the default value in a key property (e.g. `0` for an `int` key).

**Comment by janpieterz** [comment]
Awesome, that clears it up, thanks for your explanation.

**Comment by brent-russell** [comment]
It would be nice if this were mentioned in the release notes somewhere. Not using sentinel values represents a large shift in the way some application and database design happens, and is an important piece of knowledge.
