### ISSUE TITLE
EnsureCreated() and Migrate() are a pretty confusing combination

### ISSUE THREAD

**Issue by Mertsch** [dotnet/efcore#3875]
The documentation states the following

```
/// <summary>
/// Ensures that the database for the context exists. If it exists, no action is taken. If it does not
///                 exist then the database and all its schema are created. If the database exists, then no effort is made
///                 to ensure it is compatible with the model for this context.
/// </summary>
/// <returns>
/// True if the database is created, false if it already existed.
/// </returns>
public virtual bool EnsureCreated()
```

In my thinking this lead to the following code

```
if (db.Database.EnsureCreated())
{
    log.Info("Database created successfully.");
}
else
{
    db.Database.Migrate();

    log.Info("Database migrated successfully.");
}
```

And in THEORY this works, but it does not because
`EnsureCreated()` does not do a Migration and populate the `__EFMigrationsHistory` table.
This will lead to all failing consecutive calls to `Migrate()`

Now this leaves us with two options
- Successfully Create and Migrate a (non)existing database
- Successfully Create a database with non-working migrations

Is this really the intended behavior?

1.0.0-rc1-final + MSSQL Server

**Comment by rowanmiller** [comment]
You would either call `EnsureCreated()` or `Migrate()`. `EnsureCreated()` is an alternative that completely skips the migrations pipeline and just creates a database that matches you current model. It's good for unit testing or very early prototyping, when you are happy just to delete and re-create the database when the model changes.

You can just replace all your code with `db.Database.Migrate();`

**Comment by Mertsch** [comment]
@rowanmiller Thank you, I do understand that now.
That is also the reason why I titled it "confusing", because (at least for me) a migration means something different then creating a DB.

The confusion may be increased in my personal case, as I was not aware that Migrate also creates the DB and I am not sure if that worked in beta 7 when I started using EF7 (or EF at all).

I don't really have an Idea on how to have a better name for the API, but if the primary use is for testing / development, maybe the ```EnsureCreated()``` API should be exposed in a separate interface which does not confuse the first time user?

**Comment by rowanmiller** [comment]
When I get to writing better API doc comments for the Database extensions in the relational package, I'll be sure to call out that it creates the database if needed.

One other thing to make this more complex is that Migrations is specific to relational database, on other database (such as Azure Table Storage) `EnsureCreated()` is fine for everything, not just testing/prototyping (and there is no such thing as migrations).

**Comment by Mertsch** [comment]
@rowanmiller Ah, ok that makes sense. Thank you for the information and update of the doc.

Some brainstorming: Maybe it would be an option, to completely get rid of the wording migration in the API and have something like
```DataBase.EnsureReadyForUse()```, which is ```Migrate()``` for relational and ```EnsureCreated()``` for non-relational
```DataBase.EnsureReadyForUse(Options.CreateWithoutManagement)```, which is ```EnsureCreated()```
I guess there are some people coming up with something even better

**Comment by rowanmiller** [comment]
Discussed in triage and decided to leave these as they are. The use case for each will be well covered in the documentation.
