### ISSUE TITLE
Query :: support projection from set with Include

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#3878]
Something like:

```
customers.Include(c => c.Orders).Select(c => new { c.Id, Orders = c.Orders })
```

Currently when we apply Include we assume the entire entity will be returned - we don't support projections of the subset of the fields. This could be very useful if the entity contains a large field (i.e. image) that is not needed for a particular query. At the moment the query will work but the projection will be done on the client, producing N+1 trips to the database, which is very inefficient.

Concrete example of such a scenario can be found here:

https://github.com/aspnet/EntityFramework/issues/3758

**Comment by asoet** [comment]
An addition: with a basetype it's not queriying the discriminator

**Comment by rowanmiller** [comment]
@anpete in triage you thought we may already have an issue tracking handling navigation translation in projections. I couldn't find it, could you take a quick look?

**Comment by rowanmiller** [comment]
Include is orthogonal here since that just means "when you materialize a Customer, include their orders" and there are no customer instances materialized here. Opened https://github.com/aspnet/EntityFramework/issues/4007 to track improved translation of nav props in projections.
