### ISSUE TITLE
SQLite Encryption Support

### ISSUE THREAD

**Issue by austindimmer** [dotnet/efcore#388]
It would be nice to be able to easily specify an encrypted connection for SQLite. I'd love to see built in support for some of the popular encryption providers for SQLite

http://www.hwaci.com/sw/sqlite/see.html
http://sqlite-crypt.com/index.htm
http://sqlcipher.net/ 

My experience of using these technologies in conjunction with EF6 CodeFirst has been pretty underwhelming. With SqlCE it was much easier, but now that we are migrating away from SqlCE and towards SQLite it would be nice for encryption support to be just as easy as it used to be with SqlCE.

**Comment by teh-sHr0oMaN** [comment]
So given that https://github.com/aspnet/Microsoft.Data.Sqlite/issues/13 has been completed, is there now some encryption support for SQLite using EF? Perhaps via a library?

**Comment by bricelam** [comment]
```ps1
Install-Package 'Microsoft.EntityFrameworkCore.Sqlite.Core'
Install-Package 'SQLitePCLRaw.bundle_sqlcipher'
```

```C#
connection.Open();

var command = connection.CreateCommand();
command.CommandText = "PRAGMA key = 'password';";
command.ExecuteNonQuery();

var db = new MyDbContext(connection);
```

**Comment by PulkitSethi1984** [comment]
This does not seem to work with Xamarin Forms, in a .Net 2.0 standard project. I am testing this code in OnConfiguring method

**Comment by bricelam** [comment]
You may need to update your SQLitePCL.raw packages to the latest version
