### ISSUE TITLE
SQLite encryption request

### ISSUE THREAD

**Issue by brunoklein99** [dotnet/efcore#3883]
Currently I am on the first stage of a new project, which requires a small database. I first thought of SQLite. The problem is that database encryption is a requirement. Currently `Microsoft.Data.Sqlite` does not provide it. [natemcmaster](https://github.com/natemcmaster) [suggested](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/177) I created this request here.

**Comment by natemcmaster** [comment]
Clarification: there are [numerous extensions](http://stackoverflow.com/a/5877130/2526265) that allow encrypting SQLite database files. `System.Data.Sqlite` uses something (not clear what) to provide encrytion. `Microsoft.Data.Sqlite` offers nothing.

**Comment by bricelam** [comment]
FYI, System.Data.SQLite uses a [wincrypt-enabled codec](http://system.data.sqlite.org/index.html/artifact/45a3c2b7eeacb6e2) which (I believe) only works on Windows.

**Comment by rowanmiller** [comment]
Moved to https://github.com/aspnet/Microsoft.Data.Sqlite/issues/184
