### ISSUE TITLE
Why isn't ApplicationUser loading as a relation?

### ISSUE THREAD

**Issue by rykr** [dotnet/efcore#3885]
I have a class Division defined as the following.

This code will populate the League relation but not the DivisionRep one.  Any idea why?

```
  Division division = _context.Divisions.Single(m => m.Id == id);
```

In order to get DivisionRep populated I have to do this:

```
  Division division = _context.Divisions.Include(m=>m.Teams).Single(m => m.Id == id);
```

but then that doesn't work when I'm trying to load another object that has a list of divisions as a property like this:

```
  League league = _context.Leagues.Include(m => m.Divisions).Single(m => m.Id == id);
```

The divisions array is loaded but each one of the division objects doesn't have it's rep property set.  How can I do this?

  public class Division
  {
    public int Id { get; set; }

```
[ForeignKey("LeagueId")]
public virtual League League { get; set; }

[Required]
public int LeagueId { get; set; }

[Required]
public string Name { get; set; }

[Display(Name="Week Night Of Play")]
public DayOfWeek NightOfPlay { get; set; }

[DataType(DataType.Time)]
[Display(Name="Start Time Of Play")]
public TimeSpan StartTime { get; set; }

[ForeignKey("DivisionRepId")]
[Display(Name="Division Rep")]
public virtual ApplicationUser DivisionRep { get; set; }

[Required]
public string DivisionRepId { get; set; }

public List<Team> Teams { get; set; }
```

  }

**Comment by rowanmiller** [comment]
You want the `ThenInclude` method to specify additional levels of related data to include

```
_context.Leagues
    .Include(m => m.Divisions).ThenInclude(d => d.DivisionRep)
    .Single(m => m.Id == id);
```

**Comment by rykr** [comment]
Mnay thanks for you response.  I'll try that out.  But it begs the question why do I have some relations that seem to load "automagically" (without .Include())  while others don't.  So some FK (like integer based) auto load?

For example my Division class above has two FK props (League and DivisionRep).  League loads automatically without needing to use .Include().

Division division = _context.Divisions.Single(m => m.Id == id);

After using this line  division.League is populated whereas DivisionRep is not.  What am I missing?

**Comment by maumar** [comment]
@rykr did you query for the League entities earlier? EF will automatically hook up navigations between entities it knows about.

**Comment by rykr** [comment]
That must be it because I haddd queried the League entities earlier.  That was what I was missing.  Thanks!
