### ISSUE TITLE
Error when upgrading .NET 4.5.1 class library from rc1-final to rc2-16429

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3891]
Keep having issues with moving forward from rc1 to rc2 packages.

On upgrading EF.Realtional:

Added package 'Microsoft.Extensions.Logging.1.0.0-rc2-15865' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Install failed. Rolling back...
...
Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.

Workaround is to remove all packages that EF7 depends on - but it would be nice to see this resolved close to RTM...

**Comment by rowanmiller** [comment]
This seems like an issue with NuGet dependency resolution, can you open up an issue over on the NuGet repo https://github.com/NuGet/Home.

**Comment by ErikEJ** [comment]
Thanks- I will start by trying out NuGet 3.3
