### ISSUE TITLE
Question: Adding Multiple DbContexts From Separate Assemblies 

### ISSUE THREAD

**Issue by ToddThomson** [dotnet/efcore#3895]
My application may have optional modules/assemblies which add data services ( and sql database tables ). With EF6, I used a DbContext class implemented in each module/assembly ( a dll class library ). These modules were dynamically discoverable and I had my own DI to allow the data services to be used throughout my app. I want to do the same with ASP.NET 5 DI and EF7, but I am not sure how to achieve this. Do I need to roll my own AddDbContext()?

**Comment by ToddThomson** [comment]
Also, it appears that dbcontext configuration will need to be built within each module.

**Comment by ToddThomson** [comment]
OK. Prob. can use EntityFrameworkServicesBuilder class and AddDbContext() in the class library.

**Comment by rowanmiller** [comment]
@ToddThomson that would be my recommendation - run whatever logic is needed to discover them in Startup and then just put them all in DI.
