### ISSUE TITLE
AmbiguousMatchException: Ambiguous match found.

### ISSUE THREAD

**Issue by himadrinath** [dotnet/efcore#3904]
running mvc 6 in 1.0.0-rc1-final also have 2 different Class Library added as reference in this project. one of them class library used for maintain sqlserver data model with identity and another is for maintain sqlite data model. after creating relationship between models and updating database every thing works fine. and then when i created a mvc form which has 3 entities one parent entity (a) and other two (b) and (c) both of them has  one-to-one relationship with entity (a)

<b>builder.Entity&#60;a&#62;()
          .HasOne(u => u.b)
          .WithOne(t => t.a)
          .HasForeignKey&#60;b&#62;(b=> b.pubID).IsRequired()
          .OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Cascade);</b>

<b>builder.Entity&#60;a&#62;()
            .HasOne(u => u.c)
            .WithOne(u => u.a)
            .HasForeignKey&#60;c&#62;(b => b.pubID).IsRequired()
            .OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Cascade);</b>

and the post controller <b>public async Task&#60;IActionResult&#62; Create(A a)</b>
every thing works fine but when i submitting i getting an error. i can't figure it out. i tried to debug using break point but no luck. 

[System.Reflection.AmbiguousMatchException.txt](https://github.com/aspnet/EntityFramework/files/44981/System.Reflection.AmbiguousMatchException.txt)

**Comment by divega** [comment]
Hi @himadrinath, from what I see in the stack the exception is thrown from MVC model binding. The issue might have to do with the shape of your entities, although not with EF. Could check if this is a known issue and otherwise file a bug in the [MVC repo](https://github.com/aspnet/Mvc)?
