### ISSUE TITLE
Migrations going to the wrap folder

### ISSUE THREAD

**Issue by santanaguy** [dotnet/efcore#3906]
Not sure what i'm doing wrong here...
I created a new solution with a class library. Then i added a new project from ASP.NET 5 RC1 WebAPI template. I installed EF7 in the class library project, because i want EF there, and then added EF.Commands to the ASP.NET 5 project to be able to run commands.
After that i modified the Startup class to add EF to the services and it looks like this 

```
public void ConfigureServices(IServiceCollection services)
{
            // Add framework services.
            services.AddMvc();
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<Context>(opt => opt.UseSqlServer("Data Source=(localdb)\v11.0;Initial Catalog=Test;Integrated Security=True;"));
}
```

Now comes the part that confuses me. I run the command dnvm upgrade like i saw in the asp.net 5 docs and then i tried to add a migration to the class library project with the -p parameter.

The migration gets added to the "wrap" folder and is not added to my class library project. Is this a bug, or am i doing something wrong here?

Thanks

**Comment by bricelam** [comment]
The wrap folder is no longer a thing in the .NET Core CLI. I'll be sure to verify this scenario, however, as we implement the changes coming to our tooling.
