### ISSUE TITLE
SQLite provider doesn't create indexes on foreign key columns

### ISSUE THREAD

**Issue by bojanrajkovic** [dotnet/efcore#3914]
The SQLite provider claims it creates indexes on foreign key columns (http://ef.readthedocs.org/en/latest/modeling/indexes.html#conventions), but it actually doesn't in practice.

**Comment by bricelam** [comment]
Dupe of #700?

**Comment by bojanrajkovic** [comment]
Seems like it, though this is specific to the SQLite provider. Not sure if the other providers do this correctly.
