### ISSUE TITLE
DbContext package reference issue

### ISSUE THREAD

**Issue by takazm** [dotnet/efcore#3916]
I  am getting the following error on the context class after updating packages to RC2:
The type 'DbContext' exists in both 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' and 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by rowanmiller** [comment]
@takazm it looks like you somehow have both the signed and unsigned versions of EF7 there (presumably RC1 and RC2). This is likely a DNX or NuGet issue - depending on what type of project you are using. Are you able to consistently reproduce it, or is it just in the one project? And is it an ASP.NET 5 project?

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details
