### ISSUE TITLE
We need an update of this page https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext

### ISSUE THREAD

**Issue by SychevIgor** [dotnet/efcore#3919]
https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext
Signatures are not valid anymore.

**Comment by rowanmiller** [comment]
That one is a design doc and we typically don't keep those up to date... we do probably need to replace it with some real docs on our doc site though - http://docs.efproject.net.

**Comment by rowanmiller** [comment]
Moved to https://github.com/aspnet/EntityFramework.Docs/issues/90
