### ISSUE TITLE
Getting errors after removing EF beta 8 from project and installing EF RC1

### ISSUE THREAD

**Issue by gmartinezsan** [dotnet/efcore#3920]
I have an existing project with EF beta 8 which works fine. After I uninstall the package using nuget (package manager) inside Visual Studio 2015, I typed install-package EntityFramework.Core -Pre but throws the following error:

Install-package: Failed to add reference to 'System.Collection.Concurrent'. Please make sure it is in the Global Assembly Cache.

A screenshot of the error is on this link:

https://twitter.com/gabrymartinez/status/668178392735334401/photo/1

I could not add this way the package so I managed to add it manually.

Thanks for your attention.

**Comment by ErikEJ** [comment]
Happens to me all the time #3891 - workaround is to remove all DNX/ASP.NET 5 packages and add the .Relational or .Core package

**Comment by rowanmiller** [comment]
@gmartinezsan did removing and re-installing the packages work? This is an issue with NuGet. Given this is a pre-release to pre-release upgrade, we aren't going to try and workaround this in our packages.

**Comment by gmartinezsan** [comment]
@rowanmiller my WA was to add the packages manually to the csproj.

**Comment by rowanmiller** [comment]
@gmartinezsan given you got this working (and it's a pre-release to pre-release upgrade) I'm going to close this one out.
