### ISSUE TITLE
InMemory provider Thread Safety

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#3926]
While running some tests on the build server yesterday using xunit, we experienced behavior where the tests wouldn't complete.  Nothing was reported, xunit would discover the tests and queue them, they just never executed.  Net effect was that our builds were hanging.

After a bit of discovery, it appeared that the culprit was that our tests were running in a Parallel.ForEach and that, specifically, we had 2 test classes that were both attempting to access the same in-memory Table of data.

Are there currently any tests around the thread-safety of In-Memory DbSet access?   And, should it be thread-safe by design?

**Comment by rowanmiller** [comment]
@dneimke can you share some code that reproduces the issue? InMemory should be thread-safe... we were wondering if this could be a result of using the same context instance on multiple threads (rather than separate context instances targeting the same InMemroy store).

**Comment by dneimke** [comment]
Hi @rowanmiller, I'll try to produce a repro this morning and will post you a link when done.

**Comment by dneimke** [comment]
I'm going to park this for now.  I couldn't repro in a canonical xunit test project using multiple test classes but I can repro it on our build server (AppVeyor) - so it's not an EF threading issue per se but something in the build process.

**Comment by rowanmiller** [comment]
I'll close this for now, feel free to re-open if you identify something EF related.
