### ISSUE TITLE
SQL Server Migrations: Batch migrations commands

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#3928]
(This came up in a hallway conversation a while ago; filing to track.)

We implemented #2739 to help providers that don't support batching, but we could (if we wanted to) update our providers to continue batching commands.

Here are some of my original arguments for removing it that are also relevant to this issue:

> Its value-add seems minimal. We'd have to add API to MigrationBuilder for ending batches.

**Comment by balivo** [comment]
I don't know if it helps or if it is interesting to include in the "core" of the EF7...
But I created a "shortcut" method for executing SQL statements from a file of "Resource", follows:

<code>
public static void ExecuteSqlFromEmbeddedResource(MigrationBuilder pMigrationBuilder, string pResourceName)
        {
            var _assembly = Assembly.GetExecutingAssembly();

            var _resourceName = _assembly.GetManifestResourceNames().FirstOrDefault(lbda => lbda.EndsWith(pResourceName));

            using (var _stream = _assembly.GetManifestResourceStream(_resourceName))
            {
                if (_stream != null)
                {
                    using (var _reader = new StreamReader(_stream))
                    {
                        pMigrationBuilder.Sql(_reader.ReadToEnd());
                    }
                }
            }
        }
</code>

"pResourceName" is the name of (file) in resource, generally I use the name of Migration.

**Comment by bricelam** [comment]
Marking for re-triage. Doing this would be a good way to validate the APIs added in #4917.

**Comment by bricelam** [comment]
I prototyped this, and #5610 includes the breaking changes necessary to enable us to implement this later.

**Comment by bricelam** [comment]
I agreed that the actual implementation of this should wait until post-RTM when we have more time to verify it.

**Comment by bricelam** [comment]
On a side note, implementing this will create **much cleaner** idempotent scripts. We currently put `IF` statements around each command. Implementing this would put them all inside the same `IF` statement.

**Comment by bricelam** [comment]
Prototyped in [bricelam:batch](https://github.com/aspnet/EntityFrameworkCore/compare/master...bricelam:batch)
