### ISSUE TITLE
DbContext fails on Windows 10 UAP

### ISSUE THREAD

**Issue by 0pd** [dotnet/efcore#3935]
I have an issue similar to #2184. Context with simple model fails on any usage. On Database.Migrate(), trying to use DbSet, etc.
# Model

```
public class Book
{
    public int Id { get; set; }
    public string Title { get; set; }
    public bool Done { get; set; }
}

public class Movie
{
    public int Id { get; set; }
    public string Title { get; set; }
    public bool Done { get; set; }
}

public class Context : DbContext
{
    public DbSet<Book> Books { get; set; }
    public DbSet<Movie> Movies { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Filename=db.db");
    }
}
```
# App.xaml.cs

It's almost empty!

```
public sealed partial class App
{
    public App()
    {
        InitializeComponent();

        using (var db = new Context())
        {
            db.Database.Migrate(); // exception occures here
        }
    }
}
```
# Error

> System.InvalidOperationException occurred
>   HResult=-2146233079
>   Message=The API 'System.Reflection.MemberInfo.get_MetadataToken()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.
>   Source=mscorlib
>   StackTrace:
>        at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by natemcmaster** [comment]
@llvk can you post more of the stack trace so we can see what is calling `RuntimeMethodInfo.Invoke`?

**Comment by llvk** [comment]
@natemcmaster sure. I use EF7 RC1.

>System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.InvokeWorker(object[] args)   
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Invoke(object[] args) 
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame)   
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.Interpreter.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame) 
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.LightLambda.Run(object[] arguments) 
[Lightweight Function]  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinderExtensions._cctor.AnonymousMethod__13(System.Reflection.MemberInfo m1, System.Reflection.MemberInfo m2)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinderExtensions.HasSameMetadataDefinitionAs(System.Reflection.MemberInfo mi1, System.Reflection.MemberInfo mi2) 
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.BuildDeclarationChain.AnonymousMethod__5(System.Reflection.MethodInfo m)    
System.Linq.dll!System.Linq.Enumerable.WhereArrayIterator<System.Reflection.MethodInfo>.MoveNext()  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.BuildDeclarationChain(System.Type callingType)  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(System.Type originalType)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(System.Type type, Microsoft.CSharp.RuntimeBinder.Semantics.AggregateSymbol agg)  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(System.Type originalType)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.AddMethodToSymbolTable(System.Reflection.MemberInfo member, Microsoft.CSharp.RuntimeBinder.Semantics.AggregateSymbol callingAggregate, Microsoft.CSharp.RuntimeBinder.Semantics.MethodKindEnum kind)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.SymbolTable.AddPredefinedMethodToSymbolTable(Microsoft.CSharp.RuntimeBinder.Semantics.AggregateSymbol type, Microsoft.CSharp.RuntimeBinder.Syntax.Name methodName)  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.LoadMethod(Microsoft.CSharp.RuntimeBinder.Semantics.AggregateSymbol type, int[] signature, int cMethodTyVars, Microsoft.CSharp.RuntimeBinder.Syntax.Name methodName, Microsoft.CSharp.RuntimeBinder.Semantics.ACCESS methodAccess, bool isStatic, bool isVirtual)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.LoadMethod(Microsoft.CSharp.RuntimeBinder.Semantics.PREDEFMETH method)  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.EnsureMethod(Microsoft.CSharp.RuntimeBinder.Semantics.PREDEFMETH method)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.GetMethod(Microsoft.CSharp.RuntimeBinder.Semantics.PREDEFMETH method)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.GetPreDefMethod(Microsoft.CSharp.RuntimeBinder.Semantics.PREDEFMETH pdm)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.VisitBOUNDLAMBDA(Microsoft.CSharp.RuntimeBinder.Semantics.EXPRBOUNDLAMBDA anonmeth)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch(Microsoft.CSharp.RuntimeBinder.Semantics.EXPR pExpr) 
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.Dispatch(Microsoft.CSharp.RuntimeBinder.Semantics.EXPR expr)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Visit(Microsoft.CSharp.RuntimeBinder.Semantics.EXPR pExpr)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.Rewrite(Microsoft.CSharp.RuntimeBinder.Semantics.EXPR expr, Microsoft.CSharp.RuntimeBinder.Semantics.ExprFactory expressionFactory, Microsoft.CSharp.RuntimeBinder.Semantics.SymbolLoader symbolLoader)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateExpressionTreeFromResult(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> parameters, Microsoft.CSharp.RuntimeBinder.RuntimeBinder.ArgumentObject[] arguments, Microsoft.CSharp.RuntimeBinder.Semantics.Scope pScope, Microsoft.CSharp.RuntimeBinder.Semantics.EXPR pResult)  
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(System.Dynamic.DynamicMetaObjectBinder payload, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> parameters, System.Dynamic.DynamicMetaObject[] args, out System.Dynamic.DynamicMetaObject deferredBinding)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(System.Dynamic.DynamicMetaObjectBinder payload, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> parameters, System.Dynamic.DynamicMetaObject[] args, out System.Dynamic.DynamicMetaObject deferredBinding)    
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(System.Dynamic.DynamicMetaObjectBinder action, Microsoft.CSharp.RuntimeBinder.RuntimeBinder binder, System.Collections.Generic.IEnumerable<System.Dynamic.DynamicMetaObject> args, System.Collections.Generic.IEnumerable<Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo> arginfos, System.Dynamic.DynamicMetaObject onBindingError)   
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.CSharpBinaryOperationBinder.FallbackBinaryOperation(System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject arg, System.Dynamic.DynamicMetaObject errorSuggestion)    
System.Dynamic.Runtime.dll!System.Dynamic.DynamicMetaObject.BindBinaryOperation(System.Dynamic.BinaryOperationBinder binder, System.Dynamic.DynamicMetaObject arg)  
System.Dynamic.Runtime.dll!System.Dynamic.BinaryOperationBinder.Bind(System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args)  
System.Dynamic.Runtime.dll!System.Dynamic.DynamicMetaObjectBinder.Bind(object[] args, System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.ParameterExpression> parameters, System.Linq.Expressions.LabelTarget returnLabel)   
System.Dynamic.Runtime.dll!System.Runtime.CompilerServices.CallSiteBinder.BindCore<System.Func<System.Runtime.CompilerServices.CallSite, object, object, object>>(System.Runtime.CompilerServices.CallSite<System.Func<System.Runtime.CompilerServices.CallSite, object, object, object>> site, object[] args)  
System.Dynamic.Runtime.dll!System.Runtime.CompilerServices.CallSiteOps.Bind<System.Func<System.Runtime.CompilerServices.CallSite, object, object, object>>(System.Runtime.CompilerServices.CallSiteBinder binder, System.Runtime.CompilerServices.CallSite<System.Func<System.Runtime.CompilerServices.CallSite, object, object, object>> site, object[] args)  
[Native to Managed Transition]  
[Managed to Native Transition]  
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.InvokeWorker(object[] args)   
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Invoke(object[] args) 
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame)   
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.Interpreter.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame) 
System.Linq.Expressions.dll!System.Linq.Expressions.Interpreter.LightLambda.Run(object[] arguments) 
[Lightweight Function]  
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteConnection.AdjustForRelativeDirectory(string path)    
Microsoft.Data.Sqlite.dll!Microsoft.Data.Sqlite.SqliteConnection.Open() 
EntityFramework.Relational.dll!Microsoft.Data.Entity.Storage.RelationalConnection.Open()    
EntityFramework.Sqlite.dll!Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open() 
EntityFramework.Relational.dll!Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute<System.__Canon>(Microsoft.Data.Entity.Storage.IRelationalConnection connection, System.Func<System.Data.Common.DbCommand, Microsoft.Data.Entity.Storage.IRelationalConnection, System.__Canon> action, string executeMethod, bool openConnection, bool closeConnection) 
EntityFramework.Relational.dll!Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteScalar(Microsoft.Data.Entity.Storage.IRelationalConnection connection, bool manageConnection)    
EntityFramework.Relational.dll!Microsoft.Data.Entity.Migrations.HistoryRepository.Exists()  
EntityFramework.Relational.dll!Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(string targetMigration)   
EntityFramework.Relational.dll!Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.Migrate(Microsoft.Data.Entity.Infrastructure.DatabaseFacade databaseFacade) 
MyApp.exe!MyApp.App.App() Line 30   C#
MyApp.exe!MyApp.Program.Main.AnonymousMethod__0_0(Windows.UI.Xaml.ApplicationInitializationCallbackParams p) Line 24    C#

**Comment by rowanmiller** [comment]
Moved to https://github.com/aspnet/Microsoft.Data.Sqlite/issues/190

**Comment by danielgary** [comment]
Is this fixed in the current nuget package?  I'm still seeing it in a very simple model.

**Comment by rowanmiller** [comment]
@danielgary it's not fixed, it is being tracked at https://github.com/aspnet/Microsoft.Data.Sqlite/issues/190
