### ISSUE TITLE
Outdated docs in "Writing an EF7 Provider" doc section

### ISSUE THREAD

**Issue by GiancarloLelli** [dotnet/efcore#3936]
Hi guys,
Is an update to this section scheduled now that EF7 has reached RC1?
https://github.com/aspnet/EntityFramework/wiki/Writing-an-EF7-Provider 

Cheers,
Giancarlo

**Comment by natemcmaster** [comment]
Docs are a WIP. We plan to provide better provider-writer docs for RTM. See https://github.com/aspnet/EntityFramework.Docs/issues/61

cc @rowanmiller
