### ISSUE TITLE
Many-To-Many self referencing Type intersection object

### ISSUE THREAD

**Issue by cspaniard** [dotnet/efcore#3937]
I looked and I cannot find similar issues. Sorry if dup.

I followed the example in the docs and Many-To-Many relations work just fine and the DB tables are generated as expected, if the relating tables are different. For example: Category and Product -> CategoryProduct (intersection object). This works great.

The problem is when Product is referencing Product in a Many-To-Many relationship. For example, Product and RelatedProducts -> ProductRelatedProduct (intersection object).

If this is the case, the fields generated in the table don't seem consistent and using the POCO object seems to work backwards.

```
builder.Entity<ProductRelatedProduct>()
    .HasKey(productRelatedProduct => new { productRelatedProduct.ProductId, productRelatedProduct.RelatedProductId });

builder.Entity<ProductRelatedProduct>()
    .HasOne(productRelatedProduct => productRelatedProduct.Product)
    .WithMany(product => product.RelatedProducts)
    .HasForeignKey(productRelatedProduct => productRelatedProduct.ProductId);

builder.Entity<ProductRelatedProduct>()
    .HasOne(productRelatedProduct => productRelatedProduct.RelatedProduct)
    .WithMany(relatedProduct => relatedProduct.RelatedProducts)
    .HasForeignKey(productRelatedProduct => productRelatedProduct.RelatedProductId);
```

```
public class ProductRelatedProduct
{
    public int ProductId { get; set; }
    public virtual Product Product { get; set; }

    public int RelatedProductId { get; set; }
    public virtual Product RelatedProduct { get; set; }

    public int SortOrder { get; set; }
}
```

The created table fields are:

```
[dbo].[ProductRelatedProduct] (
    [ProductId]        INT NOT NULL,
    [RelatedProductId] INT NOT NULL,
    [ProductProductId] INT NULL,
    [SortOrder]        INT NOT NULL
);
```

I wonder if I am doing something wrong or if this is an issue with self referencing types.

**Comment by rowanmiller** [comment]
The results from trying to setup an invalid relationship. The issue is that you are trying to use product.RelatedProducts as the navigation property at both ends of the relationship. This is not supported by EF, you need to use separate navigations.

```
public class Product
{
    public int ProductId { get; set; }

   public virtual List<RelatedProduct> RelatedTo { get; set; }
   public virtual List<RelatedProduct> RelatedFrom { get; set; }
}
```
