### ISSUE TITLE
Support materialization hook

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3943]
Add a hook for customizing the ValueBuffer => ClrType materialization step.

Just one usage scenario among many possibilities:
Materializing an `Annotatable`. I want to put shadow properties into annotations.

**Comment by rowanmiller** [comment]
Think this is a dupe of https://github.com/aspnet/EntityFramework/issues/240

**Comment by rowanmiller** [comment]
BTW I think you don't actually want shadow properties right... you want a property that is stored in the CLR type but to get/set the value you don't use a property getter/setter.

**Comment by natemcmaster** [comment]
Yes can be solved by #240. This could also be solved by https://github.com/aspnet/EntityFramework/issues/2968. I was aware of these issues when filing, but  still think a materialization extension point could be useful.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/EntityFramework/issues/2968#issuecomment-161463855
