### ISSUE TITLE
Reverse engineering PostgreSQL sequence-driven IDs

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3966]
First, some details on PostgreSQL and auto-increment. PostgreSQL implements auto-increment columns via sequences (i.e. there's no equivalent for SqlServer's identity). A shorthand syntax for creating auto-increment columns is supported: if, when creating a table, a column's type is specified `serial`, a sequence with the name `<table>_<column>_seq` is created, and the column's default value set to `nextval('<table>_<column>_seq'::regclass)` (simple function call which gets the next value of the sequence).

In EF7, a property determined to be an id implicitly gets ValueGenerated.OnAdd. Much like the Sqlite provider, Npgsql currently checks OnAdd in NpgsqlMigrationsAnnotationProvider, and passes a `Serial` annotation to NpgsqlMigrationsSqlGenerator, which in turn creates the column with type `serial`.

However, when reverse engineering things get a bit tricky. Unlike with Sqlite and SqlServer, where identity/autoincrement columns are clearly marked in the table/column metadata, in PostgreSQL all you get is a column with a default value, which happens to get the next value of a sequence; there's no simple way to distinguish between id/OnAdd columns and columns which simply have a default value.

My current Npgsql reverse engineering provider parses the column's default expression to check whether it happens to correspond to the `nextval('<table>_<column>_seq'::regclass)`, and if so, it sets ValueGenerated to OnAdd and removes the default value. This feels extremely hacky but achieves the expected results. I expect that reverse engineering an SqlServer table using sequences as an identity strategy will create similar issues.

Am I misunderstanding/missing something? Does the hack above seem reasonable?

**Comment by natemcmaster** [comment]
Without seeing code, the hack seems reasonable. (Could you provide link to your branch?) If you find yourself needing to undo too much of what `RelationalScaffoldingModelFactory` provides, we can probably adjust this base implementation.

In SQL Server, I don't believe we can reverse engineer sequences directly into value generation on properties because sequences could be used by a number of columns and tables. (e.g. we won't be generating `PropertyBuilder.ForSqlServerUseSequenceHiLo()`).

**Comment by roji** [comment]
Thanks for the feedback @natemcmaster. I just merged the reveng code to the Npgsql develop branch, [the relevant code is here](https://github.com/npgsql/npgsql/blob/develop/src/EntityFramework7.Npgsql.Design/NpgsqlDatabaseModelFactory.cs#L105). Please feel free to comment!

Note that this code targets EF7 rc1, I will be syncing up with rc2 soon as well.

**Comment by divega** [comment]
@roji curious, are additional steps needed to manage the sequence object on the database? E.g. what would happen if a table that depended on a sequence gets dropped and then recreated? Won't the sequence remain after the table is dropped and then cause a failure on the table creation? Or is PostgreSQL smart/resilient to this. Other than possibly (depending on PostgreSQL's behavior) having danglingb sequence objects in the database, the shortcut and the hack sound great.

**Comment by roji** [comment]
@divega, PostgreSQL is smart about this: when a sequence is implicitly created as part of a `serial` column, the sequence is owned by the table; this causes the sequence to be automatically dropped when its owning table is dropped. This prevents dangling objects and failure on table drop/recreate. I'm not sure if the notion of a sequence being owned by a table is PostgreSQL-specific or not. You can read about serial and sequence [in the docs](http://www.postgresql.org/docs/current/static/datatype-numeric.html), section 8.1.4.

Thanks for the feedback on this guys, I'll go ahead and close this but please don't hesitate to continue the conversation here.
