### ISSUE TITLE
incorrect sql query

### ISSUE THREAD

**Issue by genusP** [dotnet/efcore#3977]
``` c#
context.TestEntities.Select(Param_0 => Param_0.Id == 1)
```

generate sql^

``` sql
SELECT [t].[Id] = 1
FROM [TestEntity] AS [t]
```

this query rase error in Ms SQL

**Comment by rowanmiller** [comment]
Probably a dupe of https://github.com/aspnet/EntityFramework/issues/3703 (and a few other issues we have around conditional/Boolean expressions in projections)
