### ISSUE TITLE
Running dnx ef update database creates empty db

### ISSUE THREAD

**Issue by lasrol** [dotnet/efcore#3981]
I currently have an issue where i create a migration with dnx ef migrations add init. It creates the migrations as expected, but when i try to run dnx ef database update i just creates an empty database with the ef migrations history table. 

I have reproduced this issue in this [repository](https://github.com/lasrol/EmptyDB).

I am running db update from EmptyDB.Migrations project. Not sure if my way of doing it is wrong, but i guess it should give me some kind of error of its wrong.

**Comment by megust42** [comment]
I'm having the same issue.
Migration creation seems to work fine, but running 'dnx ef database update' just creates the migration history table.
When I run 'dnx. ef migrations list' it says 'No migrations were found'

**Comment by techcap** [comment]
I have the same issue, too.

**Comment by techcap** [comment]
I found the solution.
https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(October-28,-2015)

**Comment by lasrol** [comment]
It is not quite the samme issue. I have a custom startup.cs file in my migration project, that refrences the data project. This actually are creating the migration files as expected, but for some reason it does not update my database. Just creates a empty db.

**Comment by techcap** [comment]
Did you do on EmptyDB.Migrations project folder with the command?

dnx ef migrations add Init --targetProject EmptyDB.Data

**Comment by lasrol** [comment]
As i write above in first post and second post, and you can see in the repository provided, I dont have a problem generating the migration. 

The issue occurs when i try to update the database, list migrations or generate sql script. It cannot find any of my MIgrations previously created. I run the command from EmptyDB.Migration project, but that should(if i am not misunderstanding some thing) work since i have reference to data project and i have the startup file created in that project.

**Comment by techcap** [comment]
The migration script should be generated in the project which has DbContext, EmptyDB.Data, not in EmptyDB.Migrations or EmptyDB. Without --targetProject option, migration scripts are generated in the project in which dnx runs, and it will generate empty db.

**Comment by megust42** [comment]
But shouldn't the question be, why you have to put your migrations in the same project as the DbContext?
Personally I don't see any reason to put your migrations in a separate project, but I'm sure people can come up with one.
And being able to generate migrations in a project of your choice, but then being unable to run the DB updates if there is no DbContext in the same project as the migrations is a bit confusing.

If this is the expected behaviour I would at least expect an Error/Info message when I generate migrations in a project with no DbContext, or when I try to run a DB update with Migrations and a DbContext in separate projects.

**Comment by lasrol** [comment]
Yes that's my point as well. If its by design that's fair enough, but i would still be curious to why its that way. I also agree that even if it is by design it should shown an error/info message.

**Comment by rowanmiller** [comment]
We know we need to improve this and that work is tracked by https://github.com/aspnet/EntityFramework/issues/3879. For the moment, did you specify `--targetProject EmptyDB.Data` to the update command too?

**Comment by rowanmiller** [comment]
Also opened https://github.com/aspnet/EntityFramework/issues/4008 as a helpful enhancement that came up while we were discussing this.

**Comment by lasrol** [comment]
Yes tested with ```dnx ef database update --targetProject EmptyDB.Data ``` that also created an empty db.

**Comment by rowanmiller** [comment]
Thanks for confirming. 

Chaining a call to `.MigrationsAssembly("EmptyDB.Data")` [after the call to UseSqlServer in Startup.cs](https://github.com/lasrol/EmptyDB/blob/master/src/EmptyDB/Startup.cs#L20) should make things work.

**Comment by lasrol** [comment]
In my repo i have the migration files in EmptyDB.Migrations, so i ùsed ``` .MigrationsAssembly("EmptyDB.Migrations") ``` this is also where i have a extra startup.cs but that did indeed work when correcting to the migrations project.

**Comment by rowanmiller** [comment]
@lasrol thanks for confirming.

@bricelam is there anything here that you want to track in addition to #3879, or can I close this one out?

**Comment by bricelam** [comment]
No, I think everything is tracked by other issues.
