### ISSUE TITLE
EF7 how to create multiple database files, and create a corresponding database table in each database file

### ISSUE THREAD

**Issue by zhosn** [dotnet/efcore#3983]
Hello!
I use  EF7 bate8 and Sqlite database.

Use EF7， how to create multiple database files, and create a corresponding database table in each database file?

**Comment by zhosn** [comment]
I'm new,Whether the entity framework can create multiple tables  or a table in the same database file.

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This isn't a bug report or feature request. It also isn't specific to Entity Framework. For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). Questions about how to use Entity Framework (and many other technologies) are best asked on [StackOverflow](http://stackoverflow.com/).

Perhaps start by looking at our getting started content http://docs.efproject.net/en/latest/getting-started/index.html. You can create multiple tables in the same file. If you want to use the same model/schema in multiple files then you can point the same context at different database files by changing the connection string.
