### ISSUE TITLE
Support for indices on arbitrary expressions

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3986]
PostgreSQL supports indices on expressions, as opposed to simple columns. A trivial example is something like:

``` sql
CREATE UNIQUE INDEX index_users_on_email ON users (lower((email)::text));
```

I'm not sure how PostgreSQL-specific this feature is... Are there any plans to support this?

These could be defined via the fluent API on the DbContext with an arbitrary SQL expression (a bit like a column's default value). In reveng the IndexModel could be extended with a similar SQL expression property which would then be rendered into the context.

Any comments? Let me know if you'd accept a PR on this.

**Comment by roji** [comment]
Looking at this again after some time, I'm wondering whether you think anything has to happen in EFCore to support this. In contrast with partial/filtered indexes (#6866), this seems like it may be a purely PostgreSQL-specific feature that belongs in Npgsql only (in which case this can be closed).

**Comment by smitpatel** [comment]
Clearing milestone to re-evaluate based on referenced PostgreSQL.

**Comment by roji** [comment]
Note: revisiting this in #28360
