### ISSUE TITLE
No mapping to a relational type can be found for the CLR type 'SqlParameter'

### ISSUE THREAD

**Issue by carlosalcantara2668** [dotnet/efcore#3992]
int id_return = 0;
            var xfolio = new SqlParameter
            {
                ParameterName = "@id",
                Value = 0,
                SqlDbType = SqlDbType.Int,
                Direction = ParameterDirection.Output
            };

```
        HotelDB.Database.ExecuteSqlCommand("exec test @id output ",id_return);
```

**Comment by rowanmiller** [comment]
The raw SQL APIs do not currently support passing DbParameter instances - this will be changed, and is being tracked by https://github.com/aspnet/EntityFramework/issues/3115.
