### ISSUE TITLE
Migrations: How to have multi tenant application with same model in different schemas

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#4004]
I have a multi tenant application, where the same dbcontext, TenantDbContext is used for each tenant, and where each tenant uses a different schema.
I am doing this by specifying the schema name in the TenantDbContext constructor, and in `OnModelCreating` setting `modelBuilder.HasDefaultSchema(TenantSchema)`. When I use the TenantDbContext this is silently hidden by a custom DI factory for the context.

The problem comes when I want to do migrations, as I only have one DbContext seen from "dnx ef dbcontexts list", namely the general one.

I was wondering if it is possible somehow to make a placeholder for the schemaname when the migration is added, which is later replaced during the individual database updates.

I was thinking along the way:

```
dnx ef migrations add aMigration
dnx ef database update --replace-schema "dbo" "tenant1"
dnx ef database update --replace-schema "dbo" "tenant2"
```

etc. The `--replace-schema` should, when applying the migration, take all objects in the migration on `dbo` and do the migration on the `tenant1` schema instead.

This would meen that the same migration is applied multiple times to the same database which might be a problem.

Any input on how to accomplish this, or maybe something similar?

**Comment by MaximBalaganskiy** [comment]
If you let an instance of a web site run `context.Database.Migrate()` at that moment context would already be constructed with the correct schema. If you want to manually run migrations for all tenant I think a custom command is the answer.

**Comment by rmja** [comment]
@MaximBalaganskiy I've tried that, but the problem is that migrations do not honor the `modelBuilder.HasDefaultSchema(TenantSchema)` that I have in `OnModelCreating()`, and so the migrations are applied to the dbo schema instead of the default schema specified on the instance of the db context.

**Comment by rowanmiller** [comment]
I've [moved this one over to our docs repo](https://github.com/aspnet/EntityFramework.Docs/issues/96), because we will put together documentation on how to do this. We haven't built out a full example of this yet... so it may drive specific improvements in the code base too.

**Comment by unlimitedcoders** [comment]
Did we get the answer to this?

**Comment by rmja** [comment]
No. Maybe @rowanmiller has an update?

**Comment by rowanmiller** [comment]
Some discussion about how to do this in https://github.com/aspnet/EntityFramework/issues/4410

I'm working away at the list of docs at the moment, so I should have some proper docs on this in the next couple of weeks

**Comment by smbadiwe** [comment]
In case you landed here via search, I posted a simple working solution to this problem at https://github.com/dotnet/EntityFramework.Docs/issues/96#issuecomment-974349203
