### ISSUE TITLE
Internal logging observations

### ISSUE THREAD

**Issue by mguinness** [dotnet/efcore#4014]
It's great to have EF internal methods logging.  However, below are some issues which should be considered if possible.

The open and close connection logging show the entire connection string, including passwords.  I know these are debug level, but is there a way to obscure the password?
`Microsoft.Data.Entity.Storage.Internal.SqlServerConnection: Opening connection 'Server=(local);Database=Portal;User Id=test;Password=pass'.`
`Microsoft.Data.Entity.Storage.Internal.SqlServerConnection: Closing connection 'Server=(local);Database=Portal;User Id=test;Password=pass'.`

When SQL is sent to the server we see the command which is very useful, but the actual parameter values are missing (? placeholder).  Is there any possible way to inject the actual values?
`Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory: Executed DbCommand (5ms) [Parameters=[@__path_0='?', @__id_1='?'], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [c].[Path], [c].[Section] FROM [Content] AS [c]
 WHERE ((([c].[Path] = @__path_0) AND [c].[Path] IS NOT NULL) AND ([c].[Section] = @__id_1))`

**Comment by Anderman** [comment]
I Agree. It would be nice if you can copy and paste the sql. The parameters could be written as DECLARE sql statements with the type and actual value

**Comment by anpete** [comment]
You can get the parameter values in the logs by calling this config API: https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/DbContextOptionsBuilder.cs#L89

**Comment by mguinness** [comment]
@anpete - thanks, that works as described!  Maybe the open/close connection could work in a similar fashion w/ regards to password.
