### ISSUE TITLE
Async Query Throws TaskCanceledException  7.0.0-rc1-final

### ISSUE THREAD

**Issue by ArieJones** [dotnet/efcore#4022]
We are performing a simple request for a record during an update operation 

`var existing = await _context.Patients.Where(p => p.UID == patient.UID).FirstOrDefaultAsync();`

This leads to a TaskCancelledException with the only thing in the log being an entry for 

```
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Error: An exception occurred in the database while iterating the results of a query.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Data.Entity.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
```

However, when we change the same query to use the regular ol' FirstOrDefault

`var existing = _context.Patients.Where(p => p.UID == patient.UID).FirstOrDefault();`

Everything goes through and the object is pulled correctly. 

We are currently using the following 

```
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework.Relational.Design": "7.0.0-rc1-final"
```

**Comment by rowanmiller** [comment]
Hey,

Any chance you can share a project that we can use to reproduce the issue? We haven't been able to reproduce it with the info provided.

~Rowan

**Comment by ArieJones** [comment]
Rowan,
I will try to put together a simpler project in order to demonstrate....

Aj

**Comment by rowanmiller** [comment]
Closing as we have not heard back with details

**Comment by justinyoo** [comment]
@rowanmiller I've got the same issue. Mine is happening on ToListAsync() method. If I run this on my local machine, console app and web app, it works fine but not in WebJob.

**Comment by rowanmiller** [comment]
@justinyoo can you open a new issue with details of the code you are executing etc. and a full stack trace of the exception.
