### ISSUE TITLE
Relations - Entry.Property("xxx").IsLoaded?

### ISSUE THREAD

**Issue by LonDat** [dotnet/efcore#4029]
Hi,

may I ask you, how I get info, if some reference is NULL because "DbNull" or just not loaded (because no Include()?)
It's not request for lazy-loading, but I need to know, if some property is empty or not loaded. CurrentValue and OriginalValue is null on entry.Property("xxx") in both scenarios.

Is it ok, that something like "IsLoaded" property missing on entry.Property("xxx")?

Thx for answer/check,
Milan

**Comment by rowanmiller** [comment]
We are going to add IsLoaded, but it's not currently implemented. The work is tracked by https://github.com/aspnet/EntityFramework/issues/1201, so I'll close this issue out. Currently there is no way to emulate this behavior, but if you have foreign key properties in your class then you could just check if the foreign key property has a value assigned (if it does, but the navigation property is null, then the data has not been loaded).

~Rowan

**Comment by markusvt** [comment]
Just a question for that "IsLoaded" property: are you implementing that only on a Single Property or also on List (so that i can see if a 1:n Relation is loaded)?
