### ISSUE TITLE
Serializing EntityType properties causing Getter error

### ISSUE THREAD

**Issue by JosephGarrone** [dotnet/efcore#4034]
The following code:

```
public IActionResult GetTableInfo(string table)
{
    // GetEntity just calls this.Model.FindEntityType(table)
    var entity = ProductionContext.GetEntity(table);
    var result = new
    {
        Entity = entity,
        Properties = entity.GetProperties(),
        Navigations = entity.GetNavigations(),
        Keys = entity.GetKeys(),
        Indexes = entity.GetIndexes(),
        ForeignKeys = entity.GetForeignKeys(),
        Annotations = entity.GetAnnotations()
    };

    return new ObjectResult(result);
}
```

Causes an error when `ObjectResult` attempts to serialize the result. The error is:

`Newtonsoft.Json.JsonSerializationException: Error getting value from 'Getter' on 'Microsoft.Data.Entity.Metadata.Internal.Property'. ---> System.NullReferenceException: Object reference not set to an instance of an object.`

This error can be removed by removing all properties except for `Annotations` and `Entity`.

My current work around is to do the following:

```
public IActionResult GetTableInfo(string table)
{
    // GetEntity just calls this.Model.FindEntityType(table)
    var entity = ProductionContext.GetEntity(table);
    var result = new
    {
        Entity = entity,
        Properties = entity.GetProperties().Select(q => new { Name = q.Name, Type = TypeHelper.GetBaseTypeName(q.ClrType), Nullable = TypeHelper.IsNullableType(q.ClrType) }),
        Navigations = entity.GetNavigations().Select(q => q.Name),
        Keys = entity.GetKeys().Select(q => q.SqlServer().Name),
        Indexes = entity.GetIndexes().Select(q => q.SqlServer().Name),
        ForeignKeys = entity.GetForeignKeys().Select(q => q.SqlServer().Name),
        Annotations = entity.GetAnnotations().Select(q => q.Name)
    };

    return new ObjectResult(result);
}
```

I am not 100% sure if this an error or not, but it would seem like something that people might want to be able to do.

This was using ASP.Net 5, MVC 6 and Entity Framework 7 all at RC1 and an MSSQL 12.0 database.

**Comment by rowanmiller** [comment]
These types are not designed to be serializable, projecting out to a purpose built serializable object is the right thing to do.
