### ISSUE TITLE
Modify query expression

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4048]
Hi,

how to modify the expression before executing ?

Regards.

**Comment by rowanmiller** [comment]
@mfernandezruiz do you want to modify the raw SQL or the query tree?

**Comment by mfernandezruiz** [comment]
The query tree

**Comment by rowanmiller** [comment]
cc @maumar @anpete  - any pointers you can give?

**Comment by mfernandezruiz** [comment]
I am implementing a soft delete feature, and need to modify the query tree
before IQueryProvider.Execute is invoked so I can then add conditions to
the query tree as needed. The purpose is to obtain an outcome of the query
where those entities with the flag IsDeleted set to true, are removed.

Merry xmas !

2015-12-23 22:51 GMT+01:00 Rowan Miller <notifications@github.com>:

**Comment by rowanmiller** [comment]
@anpete to provide some pointers

**Comment by santiag0sc** [comment]
Hello all !

I am pretty interested on the subject. As a gent reminder, do we have any news around this topic ?

VBRegards.
Santiago.

**Comment by anpete** [comment]
@mfernandezruiz @santiag0sc The easiest place right now to intercept the LINQ expression tree is probably [IQueryCompiler](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/Query/Internal/IQueryCompiler.cs).

The general approach would be to register a custom impl. of IQueryCompiler (likely a subclass or decorator of our concrete QueryCompiler class), and perform the interception around the various Execute methods.

**Comment by anpete** [comment]
Here are the docs for custom service registration: https://docs.efproject.net/en/latest/miscellaneous/internals/services.html
