### ISSUE TITLE
Ignored Property causes StackOverflowException

### ISSUE THREAD

**Issue by mjeanrichard** [dotnet/efcore#4049]
The following Code causes a StackOverflow (after quite some time...):

``` CSharp
    internal class Program
    {
        private static void Main(string[] args)
        {
            DbContextOptionsBuilder optionsBuilder = new DbContextOptionsBuilder();
            optionsBuilder.UseSqlServer(@"Server=.;Database=Test;Integrated Security=True;");

            Data data = new Data();

            TestContext context = new TestContext(optionsBuilder.Options);
            context.Jobs.Add(data);
            context.SaveChanges();
        }
    }

    public class TestContext : DbContext
    {
        public DbSet<Data> Jobs { get; set; }

        public TestContext(DbContextOptions options)
            : base(options)
        {}

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Data>().ToTable("Jobs");
            modelBuilder.Entity<Data>().Ignore(j => j.ParsedXml);
        }
    }

    public class Data
    {
        public int Id { get; set; }
        public XmlDocument ParsedXml { get; set; }
    }

```

If I remove the XmlDocument Property then everything works as expected.

**Comment by smitpatel** [comment]
Which version of EF are you using?
I was not able to reproduce the stackoverflow
but with `rc1-final` I hit the exception same as #3894 
And in latest codebase it is working perfect.

**Comment by mjeanrichard** [comment]
I am using EF7 RC1 final, .Net Framework 4.6 in VS2015 as well.
I will check on Monday if Ignoring the XmlDocument Type will help (as suggested in #3894).

**Comment by mjeanrichard** [comment]
It does not help if I ignore ```XmlDocument```. I verified that I am getting a StackOverflow with ```rc1-final``` and the code above. I have not tried with the current code base. Is there a way to get the current code base as a nuget package?

**Comment by smitpatel** [comment]
@mjeanrichard - for nightly build, add appropriate feed from http://myget.org/gallery/aspnetcidev

**Comment by mjeanrichard** [comment]
With the current code base everything works as expected. Thanks for your help!
