### ISSUE TITLE
Generated migration cannot update SQLite database.

### ISSUE THREAD

**Issue by delautour** [dotnet/efcore#4060]
When making a code first change which adds a relationship between models,
 `dnx ef migrations add xyz` creates a migration file which causes `dnx ef database update` to fail with `System.NotSupportedException: SQLite cannot support this migration operation.`

[A comment in SqliteMigrationsSqlGenerator](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Sqlite/Migrations/SqliteMigrationsSqlGenerator.cs#L146) would appear to indicate the issue in in migration generation.

For example, see [the second commit](https://github.com/Amerdrix/SQLite-Migration/commit/4d5f8ff5c85a666da91b281e141844a86f711b5b) of  [https://github.com/Amerdrix/SQLite-Migration](https://github.com/Amerdrix/SQLite-Migration). Note that all migrations have been committed as generated by tooling.

**Comment by bricelam** [comment]
This requires #329. SQLite doesn't support dropping columns, altering columns, adding constraints, dropping constraints, etc.

**Comment by ErikEJ** [comment]
SQL Compact does, though...

**Comment by rowanmiller** [comment]
**Triage:** This is just a limitation of using SQLite, we have https://github.com/aspnet/EntityFramework.Docs/issues/32 tracking documenting these limitations.

**Comment by faridhuseynov** [comment]
I fixed this with dropping the whole database, then deleting the whole migrations folder and then just building database with adding new "InitialCreated" database. The worst part will be if you already had some input data (not from template seed file). Then you will lose this all, which in my case wasn't there.

**Comment by DevbMindfire** [comment]
> I fixed this with dropping the whole database, then deleting the whole migrations folder and then just building database with adding new "InitialCreated" database. The worst part will be if you already had some input data (not from template seed file). Then you will lose this all, which in my case wasn't there.

But it seems to be a problem if we are going to create big structure and start loosing our data in each set

**Comment by Galaxs** [comment]
Thanks @faridhuseynov It worked for me too, this is a limitaion tracked in the [docs.](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations#migrations-limitations) But have some work arrounds.

> You can workaround some of these limitations by manually writing code in your migrations to perform a rebuild. Table rebuilds involve creating a new table, copying data to the new table, dropping the old table, renaming the new table. You will need to use the Sql(string) method to perform some of these steps.
