### ISSUE TITLE
Add-Migration dont work in VB?

### ISSUE THREAD

**Issue by marcioqmaciel** [dotnet/efcore#4064]
Project: C# Console, EF7-RC1 + SQLite, all right. DB created, tables created, first migration created.

Project: VB Console, EF7-RC1 + SQLite
- DB created;
- table __EFMigrationsHistory created;
- generated code in CS, with my model;
- dont created my table.

No EF7 to VBNet?

**Comment by midnait** [comment]
my model:

Imports Microsoft.Data.Entity
Public Class Pessoa
    Public Property Id As Integer
    Public Property Nome As String
    Public Property Idade As Integer
End Class

Public Class TesteContext
    Inherits DbContext

    Public Property Pessoas As DbSet(Of Pessoa)
    Protected Overrides Sub OnConfiguring(optionsBuilder As DbContextOptionsBuilder)
        optionsBuilder.UseSqlite("Filename=testevb.db3")
    End Sub
End Class

After Add-Migration:
* generated file 20151213225008_CriarBD.cs

using System;
using System.Collections.Generic;
using Microsoft.Data.Entity.Migrations;

namespace Teste_VB_EF7_SQLite.Migrations
{
    public partial class CriarBD : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Pessoa",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true),
                    Idade = table.Column<int>(nullable: false),
                    Nome = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pessoa", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable("Pessoa");
        }
    }
}

* generated file 20151213225008_CriarBD.Designer.cs

using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Data.Entity.Metadata;
using Microsoft.Data.Entity.Migrations;
using Teste_VB_EF7_SQLite;

namespace Teste_VB_EF7_SQLite.Migrations
{
    [DbContext(typeof(TesteContext))]
    [Migration("20151213225008_CriarBD")]
    partial class CriarBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc1-16348");
            modelBuilder.Entity("Teste_VB_EF7_SQLite.Pessoa", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd();
                    b.Property<int>("Idade");
                    b.Property<string>("Nome");
                    b.HasKey("Id");
                });
        }
    }
}

* and generated snapshot file

using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Data.Entity.Metadata;
using Microsoft.Data.Entity.Migrations;
using Teste_VB_EF7_SQLite;

namespace Teste_VB_EF7_SQLite.Migrations
{
    [DbContext(typeof(TesteContext))]
    partial class TesteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc1-16348");

            modelBuilder.Entity("Teste_VB_EF7_SQLite.Pessoa", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd();
                    b.Property<int>("Idade");
                    b.Property<string>("Nome");
                    b.HasKey("Id");
                });
        }
    }
}

after builds and F5, I have 1 file testevb.db3
- just 1 table, __EFMigrationsHistory
- columns MigrationId and ProductVersion

tks a lot, and sorry my poor english

Hugs from Brasil

**Comment by ErikEJ** [comment]
VB is currently not supported, you could add a C# class lib to your project - https://github.com/aspnet/EntityFramework/issues/3417

**Comment by bricelam** [comment]
Or if you *truly* :heart: VB, you could implement a VB version of [MigrationsCodeGenerator](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/Migrations/Design/MigrationsCodeGenerator.cs).

**Comment by rowanmiller** [comment]
BTW EF will support VB.NET on the same timeline as ASP.NET 5 - https://github.com/aspnet/Home/wiki/Roadmap#future-work

**Comment by HClausing** [comment]
Generanting a c# class with migration (03 files), will work if manually create 03 vb.net classes and translate migration code?

**Comment by bricelam** [comment]
@HClausing Yep, that'll work.

**Comment by HClausing** [comment]
Thanks!
