### ISSUE TITLE
Should dnx use framework from project.json

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/efcore#4067]
I have removed clr support as I have a dependency that needs full framework

My project.json extract

"frameworks": {
    "dnx451": {
        "dependencies": {
            "hiqpdf": "8.10.0"
        }
    }
  },

If I run migrations I get

C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>dnx database update
-c Applicationdbcontext
System.InvalidOperationException: The current runtime target framework is not co
mpatible with 'Reports2'.
Current runtime target framework: 'DNXCore,Version=v5.0 (dnxcore50)'
 Version:      1.0.0-rc1-16231
 Type:         CoreClr
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.1
 Runtime Id:   win7-x86

Please make sure the runtime matches a framework specified in project.json

Should dnx use framework from project.json automatically to avoid this error and save me setting the default manually with dnvm?

**Comment by mikes-gh** [comment]
> I have removed clr support as I have a dependency that needs full framework

Should read

I have removed core support as I have a dependency that needs full framework

**Comment by davidfowl** [comment]
Then you should use the right dnx. Look at your command line. IT looks like you're running the dnx based on .NET Core instead of the one based on .NET Framework.

**Comment by mikes-gh** [comment]
Ah OK I thought dnx was purely a bootstrapper and common to all frameworks and it could somehow change frameworks based to project.json.
But I see now it is a different binary for core vs clr thanks for your help.
