### ISSUE TITLE
Unable to load application or execute command 'EntityFramework.Commands'

### ISSUE THREAD

**Issue by blueskybcl** [dotnet/efcore#4068]
run command 'dnx ef' of new project
show error
'Error: Unable to load application or execute command 'EntityFramework.Commands'. Available commands: web, ef.'

please help me!

**Comment by bricelam** [comment]
Is `EntityFramework.Commands` listed in your `dependencies`?

**Comment by blueskybcl** [comment]
@bricelam Thank you,i forget add EntityFramework.Commands to dependencies

**Comment by furrybaer** [comment]
I have it in my dependencies and my "commands", but I still get the error...anything else I can do???

**Comment by Faeldor** [comment]
I am getting the same error with EntityFramework.Commands listed as a dependency.

**Comment by 1podProgrammer** [comment]
The more simplistic the easier to break. I've spent hours trying to resolve this. EntityFramework.Commands listed as a dependency. Jumped through all the hoops with dnu restore and tried other solutions. Far too cleaver, but fails on a KISS.
When will a fix be done?

**Comment by rowanmiller** [comment]
@1podProgrammer commands have a major overhaul in RC2, so things should be a lot easier once that ships.
