### ISSUE TITLE
Identity Schema (FKs) Remove/Create always added in Migrations when add new migration to project

### ISSUE THREAD

**Issue by balivo** [dotnet/efcore#4079]
I create a new Web App Project with Identity.

So, when I add "MyModel" class to "Models" folder, add to "ApplicationDbContext" too and execute "dnx ef migrations add MigrationName" command, migrations operations for Remove and Create Identity foreign keys is included in my "MigrationName"...

If I repeat the operation, the same behavior occurs.

Any suggestions?

**Comment by rowanmiller** [comment]
This was fixed in https://github.com/aspnet/EntityFramework/pull/3756 and will ship in RC2. In the meantime you can either remove the extra calls... or if your just prototyping you can leave them in and let EF drop and create the FKs all the time.
