### ISSUE TITLE
PropertyMappingValidationConvention BUG

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#4089]
When a entity implement a interface, on model creating, error has occurred

``` javascript
public interface ITreeNode
{
     IEnumerable<ITreeNode> Children { get; }
}

partial class A: ITreeNode
    {
       public ICollection<A> Children{ get; set;}

        IEnumerable<ITreeNode> ITreeNode.Children
        {
            get
            {
                return this.Children;
            }
        }
    }
```

InvalidOperationException: The property 'ITreeNode.Children' on entity type A has not been added to the model or ignored.

"PropertyMappingValidationConvention" brings a lot of BUG.

**Comment by smitpatel** [comment]
What is the code for `OnModelConfiguring`?

**Comment by rowanmiller** [comment]
@endink in addition to just the ` OnModelConfiguring` code, could you post a complete code listing that we can use to reproduce the issue (context and entity classes)? The code snippet you posted doesn't seem to be valid C# as `IA.Children` is not a valid name for a property.

**Comment by endink** [comment]
@rowanmiller 
sorry , i had edited my post, the bug is :when an entity implements a interface and hava a explicit internface members (property), EF validate this property and throw InvalidOperationException: The property IXXX.XXXX' on entity type XXXX has not been added to the model or ignored.

**Comment by rowanmiller** [comment]
@endink ok that makes sense. The problem is that the navigation property is defined as the interface, but EF needs to know what concrete type to use for `ITreeNode` when it's trying to work with the `Children` property. 

@divega @AndriySvyryd I think you can make this work in the current code base right? Can you share the fluent API code you need to write to make it work.

**Comment by AndriySvyryd** [comment]
To ignore the explicit property do this:
```
modelBuilder.Entity<A>().Ignore(e => ((ITreeNode)e).Children);
```

**Comment by rowanmiller** [comment]
@AndriySvyryd I thought there was a way to actually make EF7 work with a navigation property that was typed as an interface (provided you tell EF what concrete type to use). Note, that is separate from the fact that the nav prop is defined as an explicit interface implementation.

**Comment by AndriySvyryd** [comment]
@rowanmiller Yes, but it's not needed it this case because the non-explicit `Children`, that's typed as `ICollection<A>` can be used.

If it wasn't present something like this could be used to define the relationship:
```
modelBuilder.Entity<A>().HasMany(typeof(A), "Children").WithOne();
```

**Comment by divega** [comment]
FWIW, the other pattern that I have seen work (besides a bug in `ThenInclude`) and that I believe @rowanmiller was referring to looks like somewhat like this: 

``` C#
  // for A.IBs of type ICollection<IB> and B: IB 
  modelBuilder.Entity<A>().HasMany(a => (ICollection<B>)a.IBs).WithOne();
```
