### ISSUE TITLE
Consider implications of new ADO.NET schema API vis-à-vis RevEng

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#4091]
In CoreCLR the old DataSet/DataTable API has been removed. Since ADO.NET's current schema API returned schema data with these classes (DbConnection.GetSchema(), DbDataReader.GetSchema()), the ADO.NET team is now working on a new schema API for CoreCLR (see https://github.com/dotnet/corefx/issues/3423).

Now, the new ADO.NET schema API would be an almost complete duplication of the EF7 reverse-engineering database model - both describe a database, along with its tables, columns, etc. Since a new API is now in the process of being created, it seems to be a great opportunity to join the two efforts into one, and have one single schema API at the ADO.NET level. EF7's reverse engineering would them simply call the new ADO.NET GetSchema() API and start working from there.

I know it's a pretty considerable change from the direction things have taken until now, but if you miss this opportunity now you probably won't get another chance at it...

**Comment by ErikEJ** [comment]
@Roji What makes you think the CoreCLR team is working on this?

**Comment by roji** [comment]
@ErikEJ see the issue I mentioned above: https://github.com/dotnet/corefx/issues/3423, following discussions in https://github.com/dotnet/corefx/issues/1039.

See also related discussion about the ADO.NET interfaces here: https://github.com/dotnet/corefx/issues/3480

**Comment by ErikEJ** [comment]
@roji Yes, I see a lot of passionate discussions, but I cannot see "ADO.NET team is now working on a new schema API for CoreCLR"

**Comment by roji** [comment]
@ErikEJ yes these issues generated lots of... passion...

Start reading from https://github.com/dotnet/corefx/issues/3423#issuecomment-164618819 and down. @saurabh500 seems to be the Microsoft engineer currently assigned to designing the new schema API. Any feedback from you would be great as well...

**Comment by saurabh500** [comment]
@roji I looked at the EF's reverse engineering direction. 
Thanks for pointing this out. I have started a follow up with EF internally. 

To capture the bigger effort of modeling a strongly typed schema for ADO.NET I have opened the an issue at https://github.com/dotnet/corefx/issues/5024

Can we close this issue now and continue discussion on the above issue?

**Comment by roji** [comment]
@saurabh500 thanks, I'm happy this process is happening.

For me, this issue is more about what happens to EF7's RevEng API once the strongly-typed ADO.NET schema is implemented. Ideally, EF7 IDatabaseModelFactory could even be removed entirely (along with the model classes such as TableModel, ColumnModel, ForeignKeyModel..) - the new strongly-typed ADO.NET features and model classes would be used instead.

I'm not sure if this would be possible though, and would like to keep this issue open for that discussion if possible...

**Comment by saurabh500** [comment]
Sounds good. 
We will see how the discussion proceeds on the ado.net schema definition.

**Comment by rowanmiller** [comment]
Closing this for the moment as it does not look like the timing will help us out for RTM of EF7 - which means we need to roll our own solution for the moment anyways. We may re-evaluate in the future if the feature does get implemented in ADO.NET and would work well for EF. This may simply replace the model we have all together... or we can have a translator if there is a valid reason for the two models to not line up exactly.
