### ISSUE TITLE
When using InMemory Provider for unit testing the data inserted is not isolated within one DbContext

### ISSUE THREAD

**Issue by KlausEvenEnevoldsen** [dotnet/efcore#4092]
### Title

When using InMemory Provider for unit testing the data inserted is not isolated within one DbContext.
### Functional impact

When I run my unit tests one at a time they pass, but when Test Explorer runs them, some of them fail. It seems that data inserted in one unit test appears in other tests. I have a lot of tests that count how many rows that are inserted after the call to SaveChanges.

I suspect that when Test Explorer runs the unit test then it runs them concurrently and not sequentially. When that happens then it appears that the rows that are inserted in one unit test also appears in another unit test, causing my unit tests to fail.
### Minimal repro steps
1. Create a project that uses the InMemory Provider with unit tests.
2. Create a lot of unit tests that insert rows and test the count of rows to validate the functionality.
3. Run the unit tests with Test Explorer.
### Expected result

I would expect that the InMemory Provider isolates the data create in each instance of the DbContext.
### Actual result

It appears that the data is shared between the different instances of the DbContext.
### Further technical details
1. xUnit for testing
2. ASP.NET 5 RC1 Update 1
3. Visual Studio 2015 Update 1
4. Windows 10 Pro

**Comment by slamidtfyn** [comment]
I just tried this. It seems to be by design - You are working on an InMemory db, that persists data just like if it was connected to an real database

code: https://github.com/slamidtfyn/BugInEF7

**Comment by KlausEvenEnevoldsen** [comment]
Maybe, the InMemory provider is only for testing. With the SQL provider I can change the connection string and in that sense change my store, with the InMemory provider I am not able to do that.

**Comment by slamidtfyn** [comment]
Look at the commit comment here:
https://github.com/aspnet/EntityFramework/commit/e2d0ff3bcb121f1736dee4f55644b29e51dae23f

Also i found a workaround by calling

db.Database.EnsureDeleted();
db.Database.EnsureCreated();

during init of the context in test

**Comment by rowanmiller** [comment]
> I just tried this. It seems to be by design - You are working on an InMemory db, that persists data just like if it was connected to an real database

True.

> Maybe? The InMemory provider is only for testing. With the SQL provider I can change the connection string and in that sense change my store, with the InMemory provider I am not able to do that.

Also true... the InMemory database is scoped to the DI service provider. We may have the idea of named instances in the future, but in the meantime you can manually setup a service provider and get what you are after.

Here is a small console app that shows that in action...

```
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder();
            optionsBuilder.UseInMemoryDatabase();
            var options = optionsBuilder.Options;

            var serviceCollection = new ServiceCollection();
            serviceCollection
                .AddEntityFramework()
                .AddInMemoryDatabase();

            using (var db = new SampleContext(serviceCollection.BuildServiceProvider(), options))
            {
                db.Blogs.Add(new Blog { Url = "Test" });
                db.SaveChanges();
                Console.WriteLine(db.Blogs.Count());
            }

            using (var db = new SampleContext(serviceCollection.BuildServiceProvider(), options))
            {
                db.Blogs.Add(new Blog { Url = "Test" });
                db.SaveChanges();
                Console.WriteLine(db.Blogs.Count());
            }
        }
    }

    public class SampleContext : DbContext
    {
        public SampleContext(IServiceProvider serviceProvider, DbContextOptions options)
            : base(serviceProvider, options)
        { }

        public DbSet<Blog> Blogs { get; set; }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }
}
```

Or you can clean things up a little if you resolve the context from the service provider...

```c#
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection
                .AddEntityFramework()
                .AddInMemoryDatabase()
                .AddDbContext<SampleContext>(c => c.UseInMemoryDatabase());


            using (var db = serviceCollection.BuildServiceProvider().GetService<SampleContext>())
            {
                db.Blogs.Add(new Blog { Url = "Test" });
                db.SaveChanges();
                Console.WriteLine(db.Blogs.Count());
            }

            using (var db = serviceCollection.BuildServiceProvider().GetService<SampleContext>())
            {
                db.Blogs.Add(new Blog { Url = "Test" });
                db.SaveChanges();
                Console.WriteLine(db.Blogs.Count());
            }
        }
    }

    public class SampleContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }
}
```

**Comment by rowanmiller** [comment]
BTW opened https://github.com/aspnet/EntityFramework.Docs/issues/95 to track documenting this
