### ISSUE TITLE
How to achieve full text search using entity framework 7

### ISSUE THREAD

**Issue by AshishMoradiya** [dotnet/efcore#4112]
Hello,

Previously I was using EntityFramework 6 with MVC5. Now I am planning to migrate application to MVC6 with EntityFramework 7. Our application has full text search feature of SQL Server. Application need to fire full text search query to take advantage of full text search like link below:
https://msdn.microsoft.com/en-us/library/ms142583.aspx

With EntityFramework 6 we were managing generate full text search query using IDbCommandInterceptor. (Modifying query before it goes to SQL server) see below link:
http://www.entityframework.info/Home/FullTextSearch

Now, in EntityFramework 7, there is no more IDbCommandInterceptor exist, can anybody suggest me that how I can achieve full text search using EntityFramework 7?

Thank you,
Ashish

**Comment by ErikEJ** [comment]
You can use FromSQL with a TVF that use the Fulltext search functions, as demonstrated here: https://github.com/rowanmiller/Demo-Temp/blob/master/FromSql/Program.cs
