### ISSUE TITLE
Rewrite query to achieve full text search using EF Core

### ISSUE THREAD

**Issue by AshishMoradiya** [dotnet/efcore#4119]
Hello,

I am developing MVC6 application with EF7, I want to use full text search(SQL server feature). full text feature requires special type of query with 'CONTAINS' or 'FREETEXT' keyword. For more details see [this](https://msdn.microsoft.com/en-us/library/ms142583.aspx)

EF does not generate query that is supported by full text search. that is why I need to rewrite query before it goes to execution to SQL Server. Previously with EF6 I was using [Interception](http://entityframework.codeplex.com/wikipage?title=Interception) to rewrite the query. See [example here](http://www.entityframework.info/Home/FullTextSearch).

I have noticed that IDbCommandInterceptor interface is removed from EF7. So, I need to find out way for EF7. I have seen there are many classes to handle raw SQL functionality in DI. we might need put something on DI? (see attached picture)
![img_17122015_214614](https://cloud.githubusercontent.com/assets/16162527/11870128/ed35b1dc-a4ea-11e5-844b-2ffe65231117.png)

I have also considered [RelationalCommand](https://github.com/aspnet/EntityFramework/pull/3210) and [SqlStatementExecutor](https://github.com/aspnet/EntityFramework/pull/3399). RelationalCommand has similar functionality. we want to customize it to rewrite query.
Any solution to achieve this goals?

Thank you,
Ashish

**Comment by zabulus** [comment]
Maybe it should be supported via SqlServer provider via extension method for DbContext?

**Comment by rowanmiller** [comment]
We have https://github.com/aspnet/EntityFramework/issues/1590 tracking proper support for full text search. In the meantime, the best way to do this is with `FromSql`. You can now compose on top of this with LINQ, so you aren't restricted to raw SQL even though you used raw SQL to initiate the query.

Here is an example that is using a TVF with full text search and then composing on the query with LINQ https://github.com/rowanmiller/UnicornStore/blob/master/UnicornStore/src/UnicornStore/Controllers/ShopController.cs#L92

**Comment by intergleam** [comment]
come on, why would I use `FromSql`? I have a 3 page query generated by EF and I just need to replace `LIKE` to `CONTAINS`

**Comment by intergleam** [comment]
BTW the http://www.entityframework.info/Home/FullTextSearch is dead

**Comment by bbrandt** [comment]
@rowanmiller How would the suggestion to use `RawSql()` work if the predicate was against a property of a navigation property of the entity?

**Comment by ajcvickers** [comment]
@bbrandt You are commenting on an old closed issue here. Full text search was implemented in EF Core 3.1, as tracked in #11484.
