### ISSUE TITLE
What is the equivalent of DbContextConfiguration in EF 7 and how to enable LazeLoading?

### ISSUE THREAD

**Issue by Sally-Xu** [dotnet/efcore#4121]
What is the equivalent of DbContextConfiguration in EF 7 ? I mainly want to know how to config DbContext to use LazeLoading. 

Don't know if this belongs to issues or not, but I have no where to ask this question other than here.

**Comment by alaatm** [comment]
Lazy-loading isn't implemented in EF7 (yet). See this issue: https://github.com/aspnet/EntityFramework/issues/3797

**Comment by Sally-Xu** [comment]
Is "Include" syntax supported in the EF7 "7.0.0-rc1-final" release? Without LazeLoading nor "include" syntax support, is there a way to get children back with one query?

**Comment by Sally-Xu** [comment]
OK, I found out eager loading with "include" is already implemented according to the EF7 roadmap:
https://github.com/aspnet/EntityFramework/wiki/Roadmap#high-priority-features ".

I was getting build errors when try to use "include", after I added using Microsoft.Data.Entity namespace, the compiler error is gone.

**Comment by rowanmiller** [comment]
Closing this issue as it seems all questions have been answered now
