### ISSUE TITLE
Migrations: Possibility for supporting Index renames with SQL CE

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#4129]
As per the discussion here (for EF6): https://entityframework.codeplex.com/workitem/2442  - would it be possible to support Drop/Create - my question here is: How do I get the Create operation created with the proper columns @bricelam ?

**Comment by bricelam** [comment]
You would lookup the index in the model that gets passed to the generate method. It's primarily there for rebuilds like this.

**Comment by bricelam** [comment]
There are already a few helper methods for looking up entities/properties based on table/column names. The logic would be similar.

**Comment by ErikEJ** [comment]
Thanks, Brice. Where would I find those helper methods?

**Comment by bricelam** [comment]
RelationalMigrationsSqlGenerator, GetEntity and GetProperty ...or something like that. :smile:

**Comment by ErikEJ** [comment]
Thanks :smile:
