### ISSUE TITLE
No DbContext was found. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

### ISSUE THREAD

**Issue by Carpi68** [dotnet/efcore#4149]
I saw already several blogs about this, but I still got not a solution.

I'm using Visual Studio 2013 for a WPF application and my DbContext is in a different assembly than the startup class.

When typing the following in the Package manager Console:
PM> Add-Migration InitialMigration
I get:
No DbContext was found. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

Is there a way to get around this?

My assembly with the startup class: WpfApplication
M yassembly with the DbContexts: ProjectData

Thanks!

**Comment by rowanmiller** [comment]
@Carpi68 any chance you could share your project? From the generic details here there isn't enough info to work out what is happening.

**Comment by Carpi68** [comment]
@rowanmiller sorry for placing a question which was not clear enough.
In the meantime I found already half of the solution and I guess the rest would be a feature request.

This is what I'm using for my migrations:
Add-Migration -Name MyMigration -OutputDir MyMigrationDir -Context MyContext -Project MyProject -StartupProject MyStartupProject

What I would like to specify in addition is the -OutputProject to collect all migration in a separate project.
The reason for this is that I'm using XML comments in Visual Studio. And Having the migrations in the same projects than the DbContext is causing some "Missing XML comment" warnings.

Thanks!

**Comment by rowanmiller** [comment]
@bricelam I think this is possible right?

**Comment by bricelam** [comment]
Yes, after generating the first migration, move it and the snapshot into the desired project. Then use that project for the `-Project` argument.

**Comment by bricelam** [comment]
Or if your context is discoverable from the startup project, you can just use the desired project to begin with.

**Comment by rowanmiller** [comment]
Closing out as I don't think there is anything for us to do here. We are going to be documenting all these patterns, so that there will be proper guidance. Feel free to re-open if you experience issues getting it to work.

**Comment by Carpi68** [comment]
@bricelam, @rowanmiller 
Thank you very much for your help. I checked both version and have the following comments:

The first version is working like a charm. Thanks a lot for letting me know.

The second version is not working out of the box. There I get `No DbContext named 'xxx' was found`. But if I "attach" my context via `Add As Link` to my startup project, then I can use any project for the `-Project` argument to host the migrations.

Thanks again, I'll use the latter one.

**Comment by mziyabo** [comment]
Did a dotnet migrate on my project and migrations using the cli are generating the error in this thread:
i.e. No DbContext was found in assembly 'ef'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

My Environment is as follows: running dotnet --info
------------------------------------------------------------------------------------------------------------
 Command Line Tools (1.0.0-preview4-004233)
 Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7
 Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-preview4-004233

Running dotnet ef add InitialMigration -p EF.csproj -c MFIDataContext
-------------------------------------------------------------------------------------------------------

Using project 'EF.csproj'.
Using startup project '/home/mziyabo/Documents/Projects/MFI/EF/EF.csproj'.
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpC126Ta.tmp /verbosity:quiet /nologo EF.csproj
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpLZL4k4.tmp /verbosity:quiet /nologo /home/mziyabo/Documents/Projects/MFI/EF/EF.csproj
dotnet build /home/mziyabo/Documents/Projects/MFI/EF/EF.csproj /verbosity:quiet /nologo
dotnet exec --depsfile /home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1/EF.deps.json --additionalprobingpath /home/mziyabo/.nuget/packages --runtimeconfig /home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1/EF.runtimeconfig.json /home/mziyabo/.nuget/packages/microsoft.entityframeworkcore.tools.dotnet/1.0.0/tools/netcoreapp1.0/ef.dll migrations list --assembly /home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1/EF.dll --startup-assembly /home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1/EF.dll --project-dir /home/mziyabo/Documents/Projects/MFI/EF/ --content-root /home/mziyabo/Documents/Projects/MFI/EF/ --data-dir /home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1/ --verbose --root-namespace EF
Using assembly 'EF'.
Using startup assembly 'EF'.
Using application base '/home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1'.
Using content root '/home/mziyabo/Documents/Projects/MFI/EF/'.
Using root namespace 'EF'.
Using project directory '/home/mziyabo/Documents/Projects/MFI/EF/'.
Using data directory '/home/mziyabo/Documents/Projects/MFI/EF/bin/Debug/netcoreapp1.1/'.
Finding DbContext classes...
Microsoft.EntityFrameworkCore.Design.OperationException: No DbContext was found in assembly 'ef'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.GetMigrations(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrationsImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No DbContext was found in assembly 'ef'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

----------------------------------------------------------------------------------------------------------------------------------

**Comment by smitpatel** [comment]
@mziyabo - Please file a new issue with details of your project, context classes/startup etc.

**Comment by luciferlhd** [comment]
i think : we are click select .Entityframeworkcore.DBMigration or   .Entityframeworkcore

And after that   write code  : Add-migration "" 
finally  write code : update-database 
#.net core 
Hà Nôi: 12/11/2021  Đức zoro

**Comment by mohammedmhd** [comment]
(No DbContext was found in assembly 'NexIT.CMS.DmsService.HttpApi.Host'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.)
