### ISSUE TITLE
SqlHierarchyId

### ISSUE THREAD

**Issue by blanceok** [dotnet/efcore#4152]
InvalidCastException: can't type is "Microsoft. Essentially. Types. The SqlHierarchyId" object "System. The String" cast to type. 

Under the EF7 can achieve? Or alternative 

How under EF7 execute SQL query, and returns the result?

**Comment by mafshin** [comment]
@blanceok, I doubt that neither of EF versions do support `hieararchyid` as of now. The closest you can get is via [this package](https://www.nuget.org/packages/EntityFrameworkWithHierarchyId/)

**Comment by rowanmiller** [comment]
Hierarchy Id is currently not supported, we have an item on our backlog to support it https://github.com/aspnet/EntityFramework/issues/365
