### ISSUE TITLE
stored procedure created insead of plain sql statement

### ISSUE THREAD

**Issue by ilogixxDE** [dotnet/efcore#4153]
We do have a model that has string based field which are used in where Statement to filter data.
If we do this, EF7 emitts a stored procedure instead of a plain SQL. Example:

 iChats.Where(Function(C) C.SenderName.Contains(filter))

SenderName is a string field in the Chat. According documentation the SenderName.Contains creates a LIKE, as expected.
But unfortunately, the full Statement is enclosed in as 

exec sp_executesql .....

Having this, the retreivel of data from SQL is magnitudes slower than with a plain SQL Statement.

Why does EF7 create the stored procedure?

Additionally, in case of this:

 iChats.Where(Function(C) C.SenderName.Contains(filter) or C.Sender.Contains(filter))

no LIKE is generated at all and the whole table is loaded and filtered in Memory and not in the database.

**Comment by ErikEJ** [comment]
Could you show some SQL statements?

**Comment by ilogixxDE** [comment]
Yes,

the emitted SQL for a LIKE case as above is:

exec sp_executesql N'SELECT TOP(100) [Entry].[ID], [Entry].[AgentID], [Entry].[AgentName], [Entry].[ChannelType], [Entry].[ConversationID], [Entry].[End], [Entry].[LanguageID], [Entry].[PreviewText], [Entry].[Sender], [Entry].[SenderName], [Entry].[SkillID], [Entry].[Start], [Entry].[TicketID]
FROM [Chat] AS [Entry]
WHERE [Entry].[Sender] LIKE (''%'' + @__$VB$Local_Sender_0) + ''%''',N'@__$VB$Local_Sender_0 nvarchar(4000)',@__$VB$Local_Sender_0=N'test'

Running this is very slow, tried in SQL Management Studio.

I would expect a stetment like this

SELECT TOP(100) [Entry].[ID], [Entry].[AgentID], [Entry].[AgentName], [Entry].[ChannelType], [Entry].[ConversationID], [Entry].[End], [Entry].[LanguageID], [Entry].[PreviewText], [Entry].[Sender], [Entry].[SenderName], [Entry].[SkillID], [Entry].[Start], [Entry].[TicketID]
FROM [Chat] AS [Entry]
WHERE [Entry].[Sender] LIKE '%test%'

which executes much faster.

First one  took abot 3 seconds, second one some milliseconds.

Does this help?

**Comment by ErikEJ** [comment]
Does the first one also take 3 seconds the second time you run it?

**Comment by ilogixxDE** [comment]
yes, every time :-(

**Comment by ErikEJ** [comment]
What is the create table statement for the Entry.Sender column?

**Comment by ilogixxDE** [comment]
It is a Code first model. So, the line creating that column is:

 Key .Sender = table.Column(Of String)(nullable:=True),

the Index for that column is created like this

migrationBuilder.CreateIndex("Chat.Sender", "Chat", "Sender")

Do you Need anything else?

**Comment by rowanmiller** [comment]
This is actually done by SQL Client and is transparent to EF. I believe it is always done when parameters are present.

**Comment by ilogixxDE** [comment]
This is not true. 
When I create a where that holds Parameters the resulting SQL I see in the SQL Server is a pretty normal SQL Statement that has a where clause as expected.
Only in case I do have a where that Looks up a varchar or nvarchar in the database that has something like
    ColA.Contains("Bla") or ColB.Contains("Bla")
than EF emits a procedure. 
In case I use only something like 
   ColA.Contains("Bla")
EF emits the expected SQL where clause and no procedure is created.
The Impact on Performance is considerably high, so it would be much better to have a Standard SQL where insead of a proceure.
So, this might be something the should be improved.

**Comment by rowanmiller** [comment]
Whether or not we create a parameter depends on how the value is passed. In RC1, no parameter is created for this:

```c#
context.Blogs.Where(p => p.Id == id);
```

```SQL
SELECT [p].[Id], [p].[Url]
FROM [Blog] AS [p]
WHERE [p].[Id] = 5
```

But one is created for this:

```c#
var id = 5;
context.Blogs.Where(p => p.Id == id);
```

```sql
exec sp_executesql N'SELECT [p].[Id], [p].[Url]
FROM [Blog] AS [p]
WHERE [p].[Id] = @__id_0',N'@__id_0 int',@__id_0=5
```

**Comment by rowanmiller** [comment]
BTW you can see this behavior in SQL Client without EF in the picture by running the following code:

```c#
var conn = new SqlConnection(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
var cmd = conn.CreateCommand();
cmd.CommandText = "SELECT Count(*) FROM dbo.Blog WHERE Id = @p0";
cmd.Parameters.Add(new SqlParameter("p0", 5));


conn.Open();
var count = cmd.ExecuteScalar();
conn.Close();
```

The query sent to the database by SQL Client is:

```SQL
exec sp_executesql N'SELECT Count(*) FROM dbo.Blog WHERE Id = @p0',N'@p0 int',@p0=5
```
