### ISSUE TITLE
Allow ADO.NET Data Services to return non-entity POCO types

### ISSUE THREAD

**Issue by rustd** [dotnet/efcore#4158]
Porting this suggestion from ASP.NET UserVoice site. Please triage as appropriate
https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/487712-allow-ado-net-data-services-to-return-non-entity-p

Right now it seems I can only return entity types or entity framework simple types. I would like to return IQueryable<MyType> from a custom resource method.

**Comment by rowanmiller** [comment]
This looks more like a [Data Services request](http://dataservices.mswish.net/) than an EF feature request.
