### ISSUE TITLE
Smart Entities

### ISSUE THREAD

**Issue by rustd** [dotnet/efcore#4161]
Porting suggestion from ASP.NET UserVoice. Please triage as needed
https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/5336605-entity-framework-related
How about something like Smart Entities , which hold all the information within itself like its datacontext , where to save, validations, Validation errors and many more. On the consumer side it should expose very simple methods or properties.

**Comment by rowanmiller** [comment]
This is not something we are planning to do
