### ISSUE TITLE
Adding Entity to DbContext cause the identity column to change to negative number

### ISSUE THREAD

**Issue by as14220808** [dotnet/efcore#4165]
I'm not sure what's happening but suddenly every time that I use add function to add entity to DbContext, it caused my entity's identity column to change to negative number (i.e. -1). Does anyone encounter the same problem? Is it a bug?

**Comment by rowanmiller** [comment]
@as14220808 I'm guessing you worked this out (since you closed the issue)... but that is a temporary key we give the entity. It is then replaced by the real key value when the database generates one during SaveChanges.
