### ISSUE TITLE
Table's column generation for readonly fields with Migrations

### ISSUE THREAD

**Issue by sonyks** [dotnet/efcore#4174]
Why EntityFramework 7 generates new column in database for read-only field "FullName" for sample below .

```
public class Student
{
    [Key]
    public int Id { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string FullName
    {
        get
        {
            return FirstName + " " + LastName;
        }
    }
}
```

The same code in EntityFramework 6 doesn't generated new column in database.

**Comment by Vasimovic** [comment]
Try adding [NotMapped] attribute to FullName

**Comment by sonyks** [comment]
[NotMapped] attribute solved this issue but Entity Framework 7 not supposed to generate code for properties with only get-accessor. I think that is bug.

**Comment by rowanmiller** [comment]
We were experimenting with automatically mapping all properties in recent pre-releases (for getter only properties we would look for a backing field). This has caused more confusion that good though, so we are going back to just getter and setter properties in RC2 (the change is already in our nightly builds).
