### ISSUE TITLE
How can I pass table valued parameter to a stored procedure? EF7

### ISSUE THREAD

**Issue by carlosalcantara2668** [dotnet/efcore#4176]
How can I pass table valued parameter to a stored procedure? EF7

**Comment by rowanmiller** [comment]
At this stage you can't. You would need to get the `DbConnection` from the context and use ADO.NET directly. Once we have https://github.com/aspnet/EntityFramework/issues/3115 you'll be able to use the raw SQL APIs that are exposed on the context.
