### ISSUE TITLE
Generated properties & DateTime vs. current public docs

### ISSUE THREAD

**Issue by mkontula** [dotnet/efcore#4180]
According to this: http://ef.readthedocs.org/en/latest/modeling/generated-properties.html#data-annotations

We're supposed to be able to use Created or Modified DateTime -fields with entities. With rc1-final and base class like: 

```
public abstract class EntityBase
{
    public long Id { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]        
    public DateTime Created { get; set; }

    public long CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime LastModified { get; set; }

    public long LastModifiedBy { get; set; }
```

}

And derived class like: 
    public class Customer : EntityBase
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Code { get; set; }
        public List<Company> Companies { get; set; }  
    }

I got the following error while saving changes: 
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[Address], [c].[Code], [c].[Created], [c].[CreatedBy], [c].[LastModified], [c].[LastModifiedBy], [c].[Name]
      FROM [Customer] AS [c]
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (2ms) [Parameters=[@p0='?', @p1='?', @p2='?', @p3='?', @p4='?'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT OFF;
      INSERT INTO [Customer]([Address], [Code], [CreatedBy], [LastModifiedBy], [Name])
      OUTPUT INSERTED.[Id], INSERTED.[Created], INSERTED.[LastModified]
      VALUES (@p0, @p1, @p2, @p3, @p4);
fail: Microsoft.Data.Entity.DbContext[1]
      An exception occurred in the database while saving changes.
      Microsoft.Data.Entity.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Created', table 'fina-vnext-dev.dbo.Customer'; column does not allow nulls. INSERT fails.

Obviously this doesn't work for DateTime -fields as they are not getting inserted in the first place and the columns won't support nulls. This kind of functionality would be greatly appreciated since handling modified & created stamps for magnitude of entities isn't actually business logic. What's the future of DatabaseGenerated attribute and/or fluent api? Is this kind of functionality going to make to RTM? Or if not, is there any plans for hooks or events which one could attach common operations related to entity lifecycle?

**Comment by ErikEJ** [comment]
You could use Shadow Properties for this: http://ef.readthedocs.org/en/latest/modeling/shadow-properties.html

**Comment by mkontula** [comment]
Shadow properties would do the trick, but I'd fancy keeping this kind of information on the base class and sort of forgetting it there until it's needed for trouble shooting etc. If DatabaseGenerated properties would function as described in the article. Some kind of official statement would be nice to know - that is - will the generated properties support documented features or not.

**Comment by rowanmiller** [comment]
@mkontula for DateTime properties the SQL Server doesn't automatically setup value generation.. by calling ValueGeneratedOnAdd etc. you are just letting EF know that a value will be generated, but you still need to setup the actual value generation. I have a change out for review at the moment to clarify this in the docs you referred to https://github.com/aspnet/EntityFramework.Docs/pull/88.

You could either do this in the database (with default values and triggers) or client side by overriding SaveChanges.

**Comment by mkontula** [comment]
@rowanmiller Thanks a million! This : https://github.com/aspnet/EntityFramework/issues/3955 pretty much solved my case. Override of SaveChanges serves the purpose perfectly.
