### ISSUE TITLE
Using ToString in LINQ filter does not yield a WHERE clause

### ISSUE THREAD

**Issue by toddlucas** [dotnet/efcore#4186]
This was originally filed under issue #3807. I have repro'd this on rc1-final using the Npgsql provider. I found what I believe is the underlying cause but I'm not sure if it's expected behavior or not. It may have something to do with how the expression evaluator is handling the `ToString()` method. If this is expected behavior, please close. Thanks.

``` csharp
enum Color
{
    Red,
    Blue,
    ...
}

class MyTable
{
    public int id { get; set; }
    public string color { get; set; } // Contains "Red", etc.
}

// Yields no WHERE clause:
var color = Color.Red;
context.MyTableSet.Where(t => t.color == color.ToString());

// Generates a WHERE clause, as expected.
var color = Color.Red;
var colorString = color.ToString();
context.TableSet.Where(t => t.color == colorString);
```

**Comment by maumar** [comment]
This is expected. We don't know how to translate ToString method to SQL so the entire filer is performed in memory. Workaround is as you mentioned - perform the client operations outside the query and pass the result in form of closure.
