### ISSUE TITLE
Defining Entity Key in Derived Class not working.

### ISSUE THREAD

**Issue by Robban1980** [dotnet/efcore#4187]
I am trying to use EF 7 wtih IdentityManager and MembershipReboot. However i am having issues where the Entity key is defined in the derived classes instead of the root class, this is causing issues throws a "The derived type 'RelationalUserClaim' cannot have keys other than those declared on the root type 'UserClaim'." (Just an example of the entities i recieve errors on.) 

Is it possible of will it be possible to overwrite convention and specify Primary key on an Entity that is not the Root object but a derived object?

**Comment by rowanmiller** [comment]
@Robban1980 not if the root entity is included in the model. EF uses a single key space for all entities in a hierarchy, therefore they have to have the same key properties.

**Comment by Robban1980** [comment]
@rowanmiller thank you. I do not explicitly include the base class in the model, but i will investigate if they get included because some properties reference the base class on one entity.

**Comment by rowanmiller** [comment]
Feel free to re-open if you find this is happening when the base type should not be part of the model.
