### ISSUE TITLE
`dnx ef database update` not modifying database

### ISSUE THREAD

**Issue by ealsur** [dotnet/efcore#4188]
We are using EntityFramework.MicrosoftSqlServer version 7.0.0-rc1-final. Running on dnx 1.0.0-rc1-final (Windows).

We followed the procedure described on https://ef.readthedocs.org/en/latest/getting-started/aspnet5/new-db.html
When we run `dnx ef migrations add` we can see the files being created in the **Migrations** folder. Upon inspecting them, we can see that it's indeed creating our tables for our database (**Azure SQL DB**).

But if I run `dnx ef migrations list` we see **no migrations listed**.

![capture](https://cloud.githubusercontent.com/assets/1633401/12034470/29ec8366-ae10-11e5-867e-8fa0dea0c49d.PNG)

So when we run `dnx ef database update` we only get a Done message but the database contains none of our tables and only an empty **__EFMigrationsHistory**.

Tried it with a local db on a SQL Express but the same thing happened.

Our DBContext is on a Class Library project being referenced but all the namespacing of the generated migration files seem ok.

Any way this can be debugged?

**Comment by ealsur** [comment]
Ok, I cloned the EF repo and found out that the problem was on https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Migrations/Internal/MigrationsAssembly.cs#L33

It's reading the Assembly from the Context (which in my case is another referenced project) but the Migrations file was created running the command on the project that actually uses the Context (the one with the Startup.cs file).

On that same line, it's trying to parse some Option that might define the Assembly, but I found no commandline options for that on the `dnx ef database update`.

**Comment by ealsur** [comment]
As a workaround, I copied all the Migration files created on my Api project to the Context project and adjusted the namespace on them.

The `dnx ef database update` command worked perfectly afterwards.

**Comment by bricelam** [comment]
This experience may have been improved by #4098

**Comment by ealsur** [comment]
@bricelam awesome :)
I found [#3879](https://github.com/aspnet/EntityFramework/issues/3879) to be almost exactly what I went through but from the other side, I ran the ef command on the Web/Api (because I was following all the examples) and they ran it on the DbContext project (and added a Startup.cs bootstrap).

In this scenario, the Migration files should be inside the DbContext project, but that leads to a DbContext project needing Mvc dependencies to have a Startup.cs file, which doesn't sound too "clean".

From your reference I understand that I'd get a Throw if I ran the migration command on the Web/Api project once that gets merged and part of a released version, is that correct?

**Comment by bricelam** [comment]
The root problem was that you could add migrations to a project that wasn't configured as your migrations project. Then when you try to apply those migrations they can't be found. This stops you from doing that and instructs you either to add them to a different project or configure you migrations project to be the one you're trying to add them to.

**Comment by bricelam** [comment]
Ultimately, your Startup, DbContext & Migrations classes can each be in their own project. You just need to configure the migrations assembly, invoke the command on the startup project specifying the target project.

**Comment by markusvt** [comment]
I ran into the same Problem. How can I configure the migrations assembly?

**Comment by dougludlow** [comment]
I've been beating my head against the keyboard for the past couple hours over this same problem and then finally came across this issue. I got it working thanks @bricelam's last comment.

So given two separate projects, say a web project and a class library, if you have a separate context in each an you run commands from the web project (the one with the Startup.cs)...

`dnx ef migrations add ClassLibraryMigration -c ClassLibraryContext -p ClassLibrary`

Will put the migration in the ClassLibrary project.

`dnx ef database update -c ClassLibaryContext`

Will apply the migration to the database.

**Comment by ealsur** [comment]
Awesome @dougludlow I was trying to achieve it but couldn't find the correct `dnx ef migrations add` syntax.

I'll close this issue now.

**Comment by koenigsbier** [comment]
@dougludlow I've been looking for this for hours now. Thank you so much!

**Comment by dougludlow** [comment]
:+1:

**Comment by ishaklive** [comment]
Hi, My Migration class are not creating in my class library project. all the migrations codes are moving to **wrap** folder  
../WebApplication2\ **wrap** \ClassLibrary1\Migrations 

--EF Command Line Output

```
`F:\Developemnt\ASP.NET 5\WebApplication2\src\WebApplication2>dnx ef migrations add Init -p ClassLibrary1 -c DBContext -v

Finding DbContext classes... 

Using context 'DBContext'.

Writing migration to 'F:\Developemnt\ASP.NET 5\WebApplication2\wrap\ClassLibrary1\Migrations\20160514092805_Init.cs'. 

Writing model snapshot to 'F:\Developemnt\ASP.NET 5\WebApplication2\wrap\ClassLibrary1\Migrations\DBContextModelSnapshot.cs'.
Done. To undo this action, use 'ef migrations remove'`

F:\Developemnt\ASP.NET 5\WebApplication2\src\WebApplication2>dnx ef database update -c DBContext -p ClassLibrary1 -v
Finding DbContext classes...
Using context 'DBContext'.
Using database 'SchoolDB' on server 'AHAMEDISHAK-D'.
Done.

```

So  `dnx ef database update -c DBContext -p ClassLibrary1 -v` is still not working. 

Ones I copied the Migration Folder from wrap folder  to ClassLibrary Project then it works fine   

What's i'm doing wrong ?
