### ISSUE TITLE
Value generated on add (or update)

### ISSUE THREAD

**Issue by Asesjix** [dotnet/efcore#4189]
I have a problem with the function "ValueGeneratedOnAdd" and "ValueGeneratedAddOrUpdate".
Now I have repeatedly read through the documentation [Generated Properties](https://ef.readthedocs.org/en/latest/modeling/generated-properties.html#value-generated-on-add).
 I just do not get out of the type DateTime or DateTimeOffset trigger a generation.

Both Fluent Api methods not working:

```
b.Property(p => p.Created).ValueGeneratedOnAdd();

b.Property(p => p.Created).ValueGeneratedOnAdd().HasDefaultValueSql("SYSDATETIMEOFFSET()");
```

What am I doing wrong? or is it a bug?

**Comment by rowanmiller** [comment]
Not sure if you saw the recent point of clarification that I added to the docs (I only pushed it late yesterday)...

> How the value is generated for added entities will depend on the database provider being used. Database providers may automatically setup value generation for some property types, but others may require you to manually setup how the value is generated.

> For example, when using SQL Server, values will be automatically generated for GUID properties (using the SQL Server sequential GUID algorithm). However, if you specify that a DateTime property is generated on add, then you must setup a way for the values to be generated (such as setting default value SQL of GETDATE(), see Default Values).

Here is an example that shows it working with a default value:

```c#
using Microsoft.Data.Entity;
using System;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Blogs.Add(new Blog { Url = "sample.com" });
                db.SaveChanges();
            }

            using (var db = new BloggingContext())
            {
                Console.WriteLine(db.Blogs.First().Created);
            }
        }
    }

    class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
                .Property(b => b.Created)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("GETDATE()");
        }
    }

    class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public DateTime Created { get; set; }
    }
}
```

**Comment by Asesjix** [comment]
Hey rowanmiller your example works for Created.
But for the reason that is set to the value "getDate()" as the default column value.

An example of LastUpdated and the function "ValueGeneratedAddOrUpdate" will not work.
For the reason that here "getDate ()" by the function "HasDefaultValueSql ()" only a default column value is set.

The functions themselves appear to have no effect.
At least not with the MS SQL provider that I use currently.
Another I have not tried.

**Comment by Asesjix** [comment]
Here's an example:

```
using Microsoft.Data.Entity;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ValueGeneratedExample
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
                
                db.Blogs.Add(new Blog { Url = "sample.com" });
                db.SaveChanges();        
            }

            using (var db = new BloggingContext())
            {
                var blog = db.Blogs.First();
                Console.WriteLine("Updated Value after Add: " + blog.Updated);

                Task.Delay(5000).Wait();

                db.Blogs.Update(blog);
                db.SaveChanges();
            }

            using (var db = new BloggingContext())
            {
                var blog = db.Blogs.First();
                Console.WriteLine("Updated Value after Update: " + blog.Updated);
            }

            Console.ReadKey();
        }
    }

    class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
                .Property(b => b.Created)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("GETDATE()");

            modelBuilder.Entity<Blog>()
                .Property(b => b.Updated)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("GETDATE()");
        }
    }

    class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }
    }
}
```

**Comment by ErikEJ** [comment]
@Asesjix You must set the value in code in SaveChanges or use triggers for setting the "Updated" value

**Comment by Asesjix** [comment]
@ErikEJ  Please Do not understand me wrong...
But what is the point then a function named "ValueGeneratedAddOrUpdate" and the first sentence in the documentation of the following is?

> Value generated on add or update means that a new value is generated every time the record is saved (insert or update).
> http://docs.efproject.net/en/latest/modeling/generated-properties.html#value-generated-on-add-or-update

**Comment by ErikEJ** [comment]
@Asesjix Did you see the Caution box below that?

"However, if you specify that a DateTime property is generated on add or update, then you must setup a way for the values to be generated (such as a database trigger)."

**Comment by rowanmiller** [comment]
@Asesjix as @ErikEJ mentioned, just saying that the value is generated on add/update is not enough... you need to also say how to generate the date values (EF doesn't know that you want the current date set on each update). The way default values work in SQL Server is that they are used when you initially insert data, but they don't get re-calculated each time you update the data... for that you need a trigger or something similar.

**Comment by rowanmiller** [comment]
BTW I can see value in the future of having some kind of sugar method in EF that setups up a date time property to "assign the current date/time each time I update the row", then the database provider could work out the best way to achieve that... but at the moment that does not exist.

**Comment by Asesjix** [comment]
That would be great, because I think in almost every application is something like this requires.
It would be a great idea to support database triggers with the Entity Framework! ;-)

**Comment by kgrashad** [comment]
Hi @rowanmiller,

When I tried the following:
modelBuilder.Entity<Message>()
                .Property(m => m.CreatedAtUtc)
                .ValueGeneratedOnAdd()
                .HasDefaultValue("GETDATE()");

I got the following exception when creating a new migration:
System.InvalidOperationException: Cannot set default value 'GETDATE()' of type 'System.String' on property 'CreatedAtUtc' of type 'System.DateTime' in entity type 'Message'.   

I am on v 1.0.1. Am I missing anything?

**Comment by im1dermike** [comment]
@rowanmiller Your example is directly applicable to my situation.  I see you've configured your `Created` like so:

    modelBuilder.Entity<Blog>()
        .Property(b => b.Created)
        .ValueGeneratedOnAdd()
        .HasDefaultValueSql("GETDATE()");

What if I want to define my default value outside of EF (perhaps in the CREATE TABLE SQL definition) or otherwise don't want EF to know _how_ I'm setting the default date?  Omitting the `HasDefaultValueSql()` configuration and just using `ValueGeneratedOnAdd()` does not seem to work.

**Comment by ajcvickers** [comment]
@im1dermike HasDefaultValueSql does two things:
* It tells Migrations or Database.EnsureCreated what to set on the column.
* It tells SaveChanges that there is default for the column so that it can do the correct thing on inserts.

If you are managing the database outside of EF, then the first point doesn't apply. For the second point, SaveChanges actually never uses the string passed to HasDefaultValueSql, and so you could put "foo" or anything in there, and it would still work.

However, seeing your question made me think we should have a parameterless overload of HasDefaultValueSql--I'll file an issue on that.

**Comment by im1dermike** [comment]
@ajcvickers Thanks!  Related, but off topic question... If you're using `ValueGeneratedOnAdd()` and `HasDefaultValueSql()` as described, does the property and database column need to be nullable?  That seems to be the case based off my current testing.

**Comment by ajcvickers** [comment]
@im1dermike If the property has a value set, then it will be inserted. If the property is the CLR default, then it will get the value from the database default. It is common to use nullable properties such that the CLR default is null, but this is not required. It is also possible to change this behavior and force the database value to always be used by dropping down to lower-level metadata and setting ValueGeneratedAlways to true. (e.g. `.Property(b => b.Created).Metadata.ValueGeneratedAlways = true;`)

If this is not working for you, then please create a new issue with repro code so that we can investigate.

**Comment by im1dermike** [comment]
@ajcvickers #7886
