### ISSUE TITLE
Transaction Support for Repository Pattern

### ISSUE THREAD

**Issue by LifeguardConcepts** [dotnet/efcore#4190]
Is there or what is the expected support for handling transactions across multiple repositories via a service layer?  It appears that TransactionScope is no longer supported and from my experience there is a lot left to the developer in order to attempt supporting BeginTransaction across multiple repositories.

**Comment by rowanmiller** [comment]
Per discussion on https://github.com/aspnet/EntityFramework/issues/4147 we are investigating whether TransactionScope may just work on the platforms where it is available (it's not available on CoreCLR). It may be that it just works (even though we start and explicit transaction in SaveChanges), in which case we will stop explicitly blocking it. Folks would need to be aware that it doesn't necessarily work correctly with async operations - but that is a general issue with TransactionScope and not specific to EF. This work is being tracked by #4147.

Also opened https://github.com/aspnet/EntityFramework.Docs/issues/108 to create some docs on how to achieve this when TransactionScope does not exist (ASP.NET 5 on CoreCLR, UWP, etc.).
