### ISSUE TITLE
Add support for Microsoft.OData.Edm.Library.Date

### ISSUE THREAD

**Issue by arontsang** [dotnet/efcore#4193]
As per title

**Comment by rowanmiller** [comment]
This would be covered by https://github.com/aspnet/EntityFramework/issues/242. We wouldn't want to take a dependency on Microsoft.OData.Edm.Library.Date directly, but #242 will allow you to control how the database data is converted to/from CLR types.

**Comment by mj1856** [comment]
Hopefully a future version of OData will replace their custom `Date` and `TimeOfDay` types with the types of the same name being added to the `System` namespace with the `System.Time` package in [corefxlab](https://github.com/dotnet/corefxlab)

EF7's type mapping feature should *hopefully* support them both without much hassle, along with `LocalDate` and `LocalTime` types from [Noda Time](http://nodatime.org)

**Comment by rowanmiller** [comment]
@mj1856 agreed, the ability to use EF with Noda Time types is a common request
