### ISSUE TITLE
Add connectionstring for using dll repository library(based on EF6)  in ASP.NET5.0 with EF7

### ISSUE THREAD

**Issue by sdluhaibing** [dotnet/efcore#4194]
If it is EF7 DbContext, configure as:
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

How about configure the connectionstring for EF6 DbContext?

**Comment by rowanmiller** [comment]
In EF6 the connection string is a parameter to the constructor of DbContext.

**Comment by sdluhaibing** [comment]
Yes, you are right. That is what I mentioned the repository dll library. It is based on EF6.  Proviously, if any project needs to refer to this library, just need to add the connectionstring element in the config file of the project. But ASP.NET5.0/EF7 project is totally different. How can I add the connectionstring in the configuration of ASP.NET5.0/EF7 project?

**Comment by rowanmiller** [comment]
@sdluhaibing the code you originally posted is getting the connection string from the config file (appsettings.json). Do you not want to have the context registered in services in Startup.cs?

**Comment by sdluhaibing** [comment]
The code I posted is the dbcontext based on EF7. I know how to register. Actually I want to register the connection string only in the startup.cs .The connection string is used for another repository dll library which I referred in the aspnet 5.0 project.  The db context in the dll library is based on EF6. Please check my above comment, thanks so much.

**Comment by rowanmiller** [comment]
Ah, I get you (sorry that took me a while to grok your scenario).

Have the connection string on your context constructor:

```c#
public class MyContext : DbContext
{
    public MyContext(string connectionString)
        : base(connectionString)

...

}
```

Register that context in DI too:

```c#
services.AddScoped<MyContext>(() => new MyContext(Configuration["Data:DefaultConnection:ConnectionString"]));
```

That way you can resolve your EF6 context from DI, the same as you would for an EF7 context.

Does that answer your question?

**Comment by sdluhaibing** [comment]
Yes. Finally, I have to change DbContext constructor in the repository library and it works now. Thanks so much. Following https://docs.asp.net/en/latest/data/entity-framework-6.html
