### ISSUE TITLE
Changing Type of The Column from UniqueIdentifier to Long (or int)

### ISSUE THREAD

**Issue by mesuttalebi** [dotnet/efcore#4195]
This error raises when trying to run "Update-datebase"  command in Migrations.
Change datatype of column to bigint from uniqueidentifier,

According to this... http://stackoverflow.com/a/11115463, we cannot convert uniqueidentifier to int or long directly and we need to convert it to varchar(nvarchar) and then convert to long. So In Generated Migrations  Up method: it should be something like this: 

 AlterColumn("dbo.TableName", "FieldName", c => c.String(nullable: false));
 AlterColumn("dbo.dbo.TableName", "FieldName", c => c.Long(nullable: false));

 or it may do this in backend.

**Comment by rowanmiller** [comment]
**Team Triage:** we don't really make any attempt to convert types in migrations, we leave it up to the database provider to work out whether the conversion can happen safely. In situations like this, you can edit the scaffolded migration to either use an intermediary type, or use raw SQL commands, to do the conversion.
