### ISSUE TITLE
Are instances of DbContext intended to be database vendor specific?

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#4198]
I've been wiring together some projects to use Entity Framework 7 and it dawned on me that my `DbContext` instances end up being database vendor specific.  Looking at the [getting started guide](http://ef.readthedocs.org/en/latest/getting-started/full-dotnet/new-db.html), we can see the following code:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
    optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;");
}
```

Seemingly harmless, but shouldn't something like this really be provided as part of the setup in `Startup.cs`, perhaps in `Configure`?

What I'm taking away at this point is that if a project were to ever support multiple database vendors, it would have one instance of `DbContext` for each vendor.  Which would give us somewhere to encapsulate any vendor specific tweaks for the schema.

So, if the answer to this question-ticket is _'yes'_, would it be worthwhile to specifically highlight the nature of the `DbContext` file in the documentation?

If the answer is _'no'_, perhaps there's an architectural oversight here?

**Comment by atrauzzi** [comment]
After a bit more digging, I found this page: https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext#dependency-injection-scenarios

Although I'd still love to get an answer on my question, maybe this worthwhile documentation to include in any getting started guides?

**Comment by rowanmiller** [comment]
@atrauzzi doing things inline in OnConfiguring is really just a convenience for the 90-something-percent of apps that only target one provider. If you are targeting multiple providers, then you can easily pass DbContextOptions to the constructor of DbContext instead. Alternatively, you could also write conditional logic in OnConfiguring.

BTW if you are using Startup.cs with DI etc. then the recommended pattern is not to use OnConfiguring at all, but to do this config in Startup - http://docs.efproject.net/en/latest/getting-started/aspnet5/new-db.html#register-your-context-with-dependency-injection.

**Comment by atrauzzi** [comment]
Thanks @rowanmiller! :)
