### ISSUE TITLE
Support for string based Include, ThenInclude and Set

### ISSUE THREAD

**Issue by FailHair** [dotnet/efcore#4201]
Will string based `Include`, `ThenInclude` and `Set` be supported anytime soon in EF7, like it is EF6?

I've tried so many things to build up an `IQueryable` dynamically, but it's currently impossible in EF7 because everything needs a generic type...

I have also considered to use EF6 instead. But EF6 doesn't really work well with vs2015. Especially when you try to use EF6 Migrations...

The entire .NET framework is building towards a more dynamic style of coding, and yet EF7 is getting more strict with its generic types. I really don't understand why the EF team is moving towards that direction..?

Anyway, is there any info if and when this feature will be added?

**Comment by rowanmiller** [comment]
String based include is already tracked by https://github.com/aspnet/EntityFramework/issues/3921. It won't be in the initial 7.0.0 release (purely due to time constraints).
