### ISSUE TITLE
Need way of reading table schema using EF 7

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4202]
I would like to read column names & attributes (Sqlite) using EF 7 without resorting to directly accessing the db using ADO.Net. Currently my work-around is to use reflection to read the entity class properties : 

``` c#
var entity = Type.GetType("TestNamespace.Models." + SelectedEntityName);
if (entity == null)
    return;

var entityProps = entity.GetMembers().Where(x => x.MemberType == memberTypes.Property).ToList();
if (entityProps.Any())
    entityProps.ForEach(x => Fields.Add(x.Name));
```

But I hate to do it like this, as it _feels_ wrong, I have to put my entities in a single namespace, seems brittle and it does not provide me with info such as if its a primary key etc.

Using these commands manually gets me the info I need :

Table Names:

``` SQL
SELECT * FROM sqlite_master WHERE type='table'; // not sqlite_sequence or __EFMigrationsHistory
```

Column Info:

``` SQL
PRAGMA table_info(Customer);
```

But like I said, I see no way of running these and getting the results using EF 7 (that I know of). This would _not_ work since it cannot return the results: 

``` c#
db.Database.AsRelational().ExecuteSqlCommand("EXEC MySproc");
```

The reason I need to do this is so I can implement an import mechanism that allows me to _map_ the import file columns to the target table columns.

Thank you.
Keep up the good work.

**Comment by rowanmiller** [comment]
@salafsoft are you trying to find the column names for a given entity type? If so, here is some code that you can run that will give you the property name, and corresponding column name, for a type in your model.

```c#
context.Model
    .FindEntityType(typeof(Blog))
    .GetProperties()
    .Select(p => new
    {
        PropertyName = p.Name,
        ColumnName = p.SqlServer().ColumnName
    });
```

**Comment by salafsoft** [comment]
@rowanmiller That is just what I wanted thanks.

**Comment by salafsoft** [comment]
How would I be able to detect if the property (using the method above) was an `autoincrement` like the traditional id field?

I can find out if it was a `primary key`, but that does not mean it will `autoincrement`. The reason I would like that information is so that I can flag up a validation error in my application if a value is not supplied for that field, however if its an `autoincrement` I do not need to error since the DB will handle that.

**Comment by ErikEJ** [comment]
Something like:

                IsIdentity = (p.ValueGenerated == ValueGenerated.OnAdd) && (p.ClrType == typeof(int))
