### ISSUE TITLE
Serializing database object with many-to-many relationships causes infinite loop.

### ISSUE THREAD

**Issue by piotrek-k** [dotnet/efcore#4203]
I'm stuck. I'm trying to get data from database in my WebAPI app. Code:

``` csharp
//Controller:
[HttpGet("/api/notes/suggested")]
    public JsonResult GetSuggestedNotes(string searchText)
    {
        JsonResult result = null;
        try {
            List<Note> n = db.Notes.Include(x => x.NoteTags).ToList();

            result = Json(n);
        }
        catch(Exception e)
        {
            Console.WriteLine(e);
        }
        return result;
    }

//Entity Framework Model:
public class Note
    {
        public Note()
        {
            CreationDate = DateTime.Now;
            NoteTags = new HashSet<NoteTag>();
            Parts = new HashSet<Part>();
        }

        public int ID { get; set; }
        public virtual ICollection<NoteTag> NoteTags { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
        public DateTime? CreationDate { get; set; }

        [NotMapped]
        public string TagsToAdd { get; set; }

        [NotMapped]
        public string TagsAsSingleString {
            get
            {
                string result = "";
                foreach(var nt in NoteTags)
                {
                    result += nt.Tag.Name + " ";
                }
                return result;
            }
        }
    }

public class NoteTag
    {
        public int NoteId { get; set; }
        public virtual Note Note { get; set; }

        public int TagId { get; set; }
        public virtual Tag Tag { get; set; }
    }
```

**WebAPI responds with 502 http error**. I haven't got any details from compiler, no errors at all, but **I suspect that's connected with something what's called "infinite loop" or "recursion"** during serialization. "Note" class has "NoteTags" object which then has "Note" which has "NoteTags"... and so on.

I found some solutions in internet, but they doesn't satisfy me. [[This one]](http://stackoverflow.com/a/10899483/1804027) advise me to use "Select" property and specify what variables do I really need. I thinks it's not a good way to solve it, in this case creating Model like "Note" will loose any sense. Every little change I will make in "Note" structure will have to be done also in all of these controllers (and I would have to do it manually). It's not bad when I would have one controller, but what if my app grow?

[[Others]](https://msdn.microsoft.com/en-us/data/jj574232.aspx#lazyOff) advice to disable Lazy Loading, but as far as I know there isn't anything like that in EF 7 (at least there are no such properties available to use). I've also tried making properties "non-virtual". No effect.

**So, what should I do to make this finally work?**
PS: Can you recommend me some examples of asp.net 5 apps, here on github? I can't find anything interesting. I need something to model on.

**Comment by MightyBurn** [comment]
If I understand your problem correctly you just need to add JSON serialization options.

In Startup.cs, in ConfigureServices when adding MVC add the AddJsonOptions:
            services.AddMvc().AddJsonOptions(
                o =>
                {
                    o.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    o.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                }
             );

There are good exemples of what different types of settings do here.
http://stackoverflow.com/questions/23453977/what-is-the-difference-between-preservereferenceshandling-and-referenceloophandl/23461179

**Comment by rowanmiller** [comment]
Closing this out as it's really a serialization issue rather than anything in EF (and @MightyBurn already answered the question). Feel free to re-open if you feel there is anything EF is doing incorrectly.
