### ISSUE TITLE
Calling ThenInclude within DbContext.Set<>

### ISSUE THREAD

**Issue by techyian** [dotnet/efcore#4204]
Hey,

Sorry if this has already been raised prior, but I've ran into an issue while building a dynamic IQueryable. 

I'm able to access DbContext.Set<> and call Include without issue which populates the relevant relations, but when I try to include a relation with ThenInclude, this results in the relation being null. 

Just to clarify the steps I'm taking, I begin by including the relations I need in an IQueryable via DbContent.Set<> , and then based on different scenarios, call .Where(), finally calling Take().ToList() to carry out the operation.

This is different to the usual steps I'd take, where I'd first call .Where() and chain .Include() from that.

Please let me know if there's any code or SQL dumps I can supply for you.

Thanks,

Ian.

**Comment by rowanmiller** [comment]
@nocommonsense can you provide a complete code listing (or project) that we can run to reproduce and debug the issue you are seeing.

**Comment by nocommonsense** [comment]
Hey @rowanmiller 

Please put this one down to user error! Sorry for wasting your time.

Ian.

**Comment by rowanmiller** [comment]
no problem :smile:
