### ISSUE TITLE
Logging example for desktop application

### ISSUE THREAD

**Issue by NoFear23m** [dotnet/efcore#4206]
Hy @all 

Is there any example how to log entity framework querys in a dektop application like WPF?
I have try to use logging but i failed. ;-(
Have everyone an example or can write anyone a wiki article about logging?

thanks in advance
Sascha

**Comment by ErikEJ** [comment]
I have implemented a simple logger here: 
https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/src/Provider40/Extensions/SqlCeDatabaseFacadeExtensions.cs

Sample usage here: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/BasicEndToEndScenario.cs#L24

**Comment by rowanmiller** [comment]
I also opened an issue in our docs repo to add a page on this topic https://github.com/aspnet/EntityFramework.Docs/issues/102

**Comment by rowanmiller** [comment]
@NoFear23m @ErikEJ I just wrote up some docs on how to do this http://docs.efproject.net/en/latest/miscellaneous/logging.html. There is still plenty of room for improvement... but it shows how to make it work with RC1.

**Comment by ErikEJ** [comment]
Thanks, very similar to my implementation...
