### ISSUE TITLE
Azure + Database.Migrate() create empty database

### ISSUE THREAD

**Issue by as14220808** [dotnet/efcore#4208]
I'm not sure what did I do wrong but Database.Migrate() does not work on azure db. It creates an empty database. However, in localdb, Database.Migrate() works fine.

**Comment by rowanmiller** [comment]
We probably need some more info to be able to help with this one. We have a sample application that uses Migrate against an Azure database and it work correctly, so there must be something specific to your scenario that is causing it to break. Are you able to share a project etc. that we can use to reproduce the issue?

**Comment by rowanmiller** [comment]
Closing as we have not heard back with the requested details
