### ISSUE TITLE
RC1 dnxcore50 Could not load file or assembly System.Data.SqlClient 

### ISSUE THREAD

**Issue by dianecawley** [dotnet/efcore#4209]
I built a web API project using DNX 4.5.1, DNX Core 5.0 using the default template for Web API.  I did not want to use EF, so I manually added the dependencies below to the project.json file.

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.Runtime": "4.0.21-beta-23516",
        "System.Data.Common": "4.0.1-beta-23516",
        "System.Data.SqlClient": "4.0.0-beta-23516"
      }
    }
  },

With this configuration, as soon as my Data Access class is requested, I get the error above.  

NOTE:  when I added the dependencies for EF 7 --- this error was resolved.

Is it intentional that you must load EF 7 in order to have access to SQL?

**Comment by rowanmiller** [comment]
@dianecawley SQL Client should work just fine without EF. SQL Client is managed as part of the http://github.com/dotnet/corefx project (our EF project builds on top of it) - could open up an issue over there.
