### ISSUE TITLE
Use EF7 in library projects (non-DNX projects)

### ISSUE THREAD

**Issue by balivo** [dotnet/efcore#4211]
It's possible use EF7 in a Class Library Project?

**Comment by ehalsey** [comment]
Did you see this?
http://stackoverflow.com/questions/30868968/entity-framework-7-migration-scaffolding-in-class-library-with-configuration

**Comment by balivo** [comment]
Thanks for reply @ehalsey but the link isn't related to my question. I'm going to describe my situation.

To use the EF7 in a separate project (DLL) I need, necessarily, add "Class Library (Package)" project to my "Solution".

I can use the EF7 in "Class Library" project?

**Comment by rowanmiller** [comment]
> I can use the EF7 in "Class Library" project?

Yes. Feel free to reply if you hit any specific issues.

**Comment by balivo** [comment]
Tks again @rowanmiller... I tried again include EF7 in non-DNX Project and Works fine.
But Identity.EntityFramework not... I post a new issue at Security repository.
Thanks.
