### ISSUE TITLE
Crash in System.Data.Entity

### ISSUE THREAD

**Issue by aarff** [dotnet/efcore#4215]
0:011> !PrintException 000000cb9db0bc30 

Exception object: 000000cb9db0bc30

Exception type: System.BadImageFormatException

Message: Could not load file or assembly 'Microsoft.SqlServer.Types, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The module was expected to contain an assembly manifest.

InnerException: <none>

StackTrace (generated):

SP IP Function

000000CBB840D150 0000000000000000 mscorlib_ni!System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)+0x1

000000CBB840D150 00007FFB60AF158A mscorlib_ni!System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)+0xea

000000CBB840D200 00007FFB60B3C162 mscorlib_ni!System.Reflection.Assembly.Load(System.Reflection.AssemblyName)+0x42

000000CBB840D250 00007FFB0330D8BF System_Data_Entity!System.Data.SqlClient.SqlTypesAssembly.BindToLatest()+0x8f

000000CBB840D2A0 00007FFB0330B8E1 System_Data_Entity!System.Data.Common.Utils.Singleton`1[[System.__Canon, mscorlib]].get_Value()+0x21

000000CBB840D2E0 00007FFB0330D6AC System_Data_Entity!System.Data.Spatial.DbSpatialServices.LoadDefaultServices()+0x2c

000000CBB840D310 00007FFB0330B8E1 System_Data_Entity!System.Data.Common.Utils.Singleton`1[[System.__Canon, mscorlib]].get_Value()+0x21

000000CBB840D350 00007FFB0330B335 System_Data_Entity!System.Data.Spatial.DbGeometry.FromText(System.String)+0x35

000000CBB840D380 00007FFB0330A872 System_Data_Entity!System.Data.Mapping.Update.Internal.Propagator+ExtentPlaceholderCreator.InitializeTypeDefaultMap()+0x2e2

000000CBB840D3E0 00007FFB0330A55F System_Data_Entity!System.Data.Mapping.Update.Internal.Propagator+ExtentPlaceholderCreator..cctor()+0xf

StackTraceString: <none>

HResult: 80131018

**Comment by rowanmiller** [comment]
Looks like this is EF6 - if so, the issue tracker for EF6 is at https://entityframework.codeplex.com/

**Comment by rowanmiller** [comment]
Closing this out as it's actually already logged as an issue in an internal bug tracker with more info.
