### ISSUE TITLE
Using Entity Framework from a WCF Service

### ISSUE THREAD

**Issue by christiannagel** [dotnet/efcore#4217]
Error loading System.Threading, Version 4.0.10.0 when using Entity Framework 7 from a WCF Service.

I have a .NET 4.6 class library with EntityFramework.Core (7.0.0-rc2-16649) and EntityFramework.MicrosoftSqlServer. Using this class library from a Console application, adding entities and saving changes is running fine. However, using this library from a WCF host, I get this exception: 
Could not load file or assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
In the output Window I'm seeing this trace output:
Exception thrown: 'System.IO.FileNotFoundException' in EntityFramework.Relational.dll

The exception occurs on adding a new entity to the context.

How can I use Entity Framework 7 from a WCF Service?

Thanks,
Christian

**Comment by rowanmiller** [comment]
@christiannagel you should be able to use EF7 in a WCF service without doing anything special. Can you provide a sample project (or detailed steps and code listings) we can use to reproduce the issue you are seeing.

**Comment by christiannagel** [comment]
@rowanmiller 
[RoomReservation.zip](https://github.com/aspnet/EntityFramework/files/83079/RoomReservation.zip)
A ZIP file is attached. The entity type RoomReservation is defined in RoomReservationContracts. The data context is defined in RoomReservationData. With the client application defined in TestApp everything works as expected. Using the service (RoomReservationService) and the RoomReservationClient calling the service, an exception occurs when adding entities to the context from the EntityFrameworkRelational.dll: cannot find a file (a library).
Thanks,
Christian

**Comment by rowanmiller** [comment]
@christiannagel this may be due to the mismatched versions of EF you have installed. RoomReservationHost has `7.0.0-rc2-16647` where as RoomReservationData has `7.0.0-rc2-16647`. Let me know if that does not fix the issue and I will keep investigating.

**Comment by christiannagel** [comment]
@rowanmiller I checked and consolidated all to the 7.0.0-rc2-16647 version, the same issue. Then I updated all to the 7.0.0-rc2-16649 version, the same issue - could not load file or assembly System.Threading 4.0.10.0.

**Comment by rowanmiller** [comment]
The "could not load file or assembly System.Threading 4.0.10.0" issue is due to these binding redirects in the app.config file. They are trying to redirect to the 4.0.10.0 version of System.Threading... but that isn't present in your reference. I'm not sure what added these, I installed the latest version of our packages and it does not result in NuGet adding them... but it's entirely possible that an earlier build of our package had different dependencies that resulted in NuGet adding the redirects.

The solution is to delete them. After deleting them, your app worked and I got the "reservation ok" dialog from the client.

```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.10.0" newVersion="4.0.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.Debug" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.10.0" newVersion="4.0.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.10.0" newVersion="4.0.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.10.0" newVersion="4.0.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Globalization" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.10.0" newVersion="4.0.10.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.37.0" newVersion="1.1.37.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by christiannagel** [comment]
That's greats! Thank you! I missed the redirects. Yes, it must have been an earlier build which added these.
