### ISSUE TITLE
Perf: Improve bulk insert with server-generated values on SqlServer

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#4218]
When inserting entities with some properties set and the rest to be generated by the server, the generated values need to be sorted to match up with the inserted enitites, because the insertion order is non-deterministic. The way it's currently implemented is not optimal. The are several approaches that could improve performance:
1. Try to find columns that form a natural key to be used for the join with INSERTED if no primary or alternate keys are being inserted. If there is no set of columns that forms a natural key for the set partition the set in one of two ways, whichever produces less insert statements:
   1. Partition the set into subsets so that the chosen columns form a natural key in each subset
   2. Partition the set into subsets so that all columns have the same values in each subset, the order in which the generated values are propagated in the subsets becomes unimportant
2. Add a column to each table to hold the temporary key if the PK is server-generated. Optionally views can be generated to somewhat hide the temporary key column from the user. Then either:
   1. Sort the enitities to be inserted by temporary key and sort the generated values to be returned by temporary key as well.
   2. Return the temporary key and use it to match to the inserted entities
3. Avoid any ordering on the server, instead return enough of the specified columns to match up to the inserted entities, this transfers the workload to the client, so the overall perf might not improved.

**Comment by divega** [comment]
I think we should also consider the possibility of falling back to issuing multiple INSERTs in a batch instead of multiple rows in a single INSERT VALUES statement when the key is store generated. That would make the SQL easier to understand even if it is not always the most efficient.

**Comment by AndriySvyryd** [comment]
Bulk insert has been reimplemented in a different way
