### ISSUE TITLE
Invalid object name "ClassName" when trying to seed data

### ISSUE THREAD

**Issue by huytnd** [dotnet/efcore#4219]
My scenario: I'm using EF 7 RC1, I created an empty database in SQL Management Studio and set credentials for it, and defined it in the appconfigs.json file (connection string node). My dbcontext class is very simple

```
public DbSet<Category> Categories { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Category>().ForSqlServerToTable("Category").HasKey(c => c.CategoryId);


        }
```

When calling Initialize method, I got this exception.
![invalid-table-name](https://cloud.githubusercontent.com/assets/2102905/12111757/6505e2e8-b3ca-11e5-9fd8-0d2974259e7c.jpg)

**Comment by smitpatel** [comment]
The exception message occurs in `context.Categories.Any()` which will trigger query on `Category` table. Looking at the message, it seems that the table `Category` does not exist in the database.
When you created empty database, did you create the tables inside it? You can run `context.Database.EnsureCreated()` to make sure that the tables exist.

**Comment by huytnd** [comment]
I didn't create the table Category for the empty database. By adding an if statement```if(context.Database.EnsureCreated())``` before ```context.Categories.Any()```, now the data is seed. Thank you.

**Comment by rowanmiller** [comment]
BTW if you are using migrations, then you would run `context.Database.Migrate()` rather than `EnsureCreated()`
