### ISSUE TITLE
AddToProjection does not check the Name of ColumnExpression

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/efcore#4221]
If i create a column expression without using the ctor with IProperty and then add two expression of the same Type to the same Select expression the second one will be exclude, because the check in 

https://github.com/aspnet/EntityFramework/blob/179e3e96dd30e71b7e9474f205a3df4ba93c5ad8/src/EntityFramework.Relational/Query/Expressions/SelectExpression.cs#L411

Only takes the instance of IProperty into considerations when extracting the previously added ColumnExpression (now AliasExpression) but not its name.

I would expect the ColumnExpression are also identified by their name, as long as they have a ctor that allows creation without an IProperty instance.

EDIT: Corrected line number

**Comment by LunicLynx** [comment]
Code to reproduce

`class Program
    {
        class QSGF : IQuerySqlGeneratorFactory
        {
            public IQuerySqlGenerator CreateDefault(SelectExpression selectExpression)
            {
                throw new NotImplementedException();
            }

            public IQuerySqlGenerator CreateFromSql(SelectExpression selectExpression, string sql, Expression arguments)
            {
                throw new NotImplementedException();
            }
        }

        class QS : IQuerySource
        {
            public string ItemName { get; }
            public Type ItemType { get; }
        }

        static void Main(string[] args)
        {
            var x = new SelectExpression(new QSGF());
            var table = new TableExpression("T", "dbo", "t", new QS());
            x.AddToProjection(new ColumnExpression("A", typeof (int), table));
            x.AddToProjection(new ColumnExpression("B", typeof (int), table));
            Debug.Assert(x.Projection.Count == 2);
        }
    }

**Comment by rowanmiller** [comment]
@LunicLynx it would be helpful to better understand the scenario you were trying to achieve when you hit this issue. In general, we spend less time with defensive code paths on the lower level building blocks. But if you have a scenario that application developers are likely to hit, then we can look at improving things here.

**Comment by LunicLynx** [comment]
I don't think that anyone using EF will hit this issue.
I tried to use the SqlGenerator on a custom dynamic model, and this was a part of it. In the meantime i decided against proceeding with this idea because it doesn't seem feasible.

**Comment by rowanmiller** [comment]
Closing out since we generally don't put this much effort into protecting invalid scenarios in lower level components that are not intended to be used by app developers.
