### ISSUE TITLE
Injecting UserManager into AllowAnonymous controller causes nested properties to be null

### ISSUE THREAD

**Issue by techyian** [dotnet/efcore#4225]
Hey,

Please note this issue occurs within a razor view:

I've found that if you mark a controller as AllowAnonymous, but are logged in when accessing one of the routes, nested properties are not populated when I do the following within razor after injecting the UserManager service: 

`await UserManager.FindByNameAsync(User.Identity.Name)`

However, if I mark the controller as Authorize, the relations are populated. Is there any reason for this? 

Thanks,

Ian.

**Comment by rowanmiller** [comment]
Hey,

This sounds like it's more about ASP.NET Identity than EF? If so, it probably belongs in https://github.com/aspnet/Identity.

~Rowan

**Comment by nocommonsense** [comment]
Thanks @rowanmiller, wasn't too sure where this one belonged. 

Will re-raise there.

Ian.
