### ISSUE TITLE
MS SQL Server : Applicaton Role

### ISSUE THREAD

**Issue by jim-thomas** [dotnet/efcore#4234]
In our DB First environment using MS SQL Server all access is based on application role. Does EF7 provide any current mechanism for queries using app role? (I assume 'simple interception' will provide that capability at some future date, since it is listed as a high priority, but my question is what will be available with EF7 RTM.)

**Comment by rowanmiller** [comment]
Application roles are enabled on a per-connection basis by executing `sp_setapprole`. To this end, it should simply be a matter if executing some raw SQL when an instance of a context is created.

I just tried this with EF7 RC1 and it worked...

```
public class MyContext : DbContext
{
        public MyCotnext()
        {
            this.Database.ExecuteSqlCommand("EXEC  sp_setapprole <role> <password>");
        }

...
```

**Comment by jim-thomas** [comment]
Thank-you, that's seems like a great solution but unfortunately it did not work for me. I get a 'Select permission denied' as if the query is not using the app role.

Here is the dbcontext:
```c#
public StaffContext()
{
    try
    {
        this.Database.ExecuteSqlCommand("EXEC sp_setapprole 'foxgl', 'psw'");
    }
    catch (Exception exception)
    {
        Console.WriteLine("App Role exception: " + exception.Message);
    }
}
protected override void OnConfiguring(DbContextOptionsBuilder options)
{
    options.UseSqlServer(@"Server=sql21devf;Database=Staff;Trusted_Connection=True;Pooling=false;");
}	
```
and here is the query code which generates the 'Select permission denied error' :
```c#
using (var db = new StaffContext())
{
    List<TopProject> projects = (from row in db.TopProject select row).ToList<TopProject>();
}
```
I also have a database role, is_developer, which grants me select access. When that access is granted this code works great. When I turn off select access on is_developer, this code fails to use the app role (which definitely has 'select' granted) and reports the denial. (Permissions are set using SQL Server Management Studio/table/Properties/Permissions). 

I trust this is enough detail for you to tell me what you did differently that made your code work.

**Comment by jim-thomas** [comment]
I have gotten it to work by assuming the connection was closed after the sp_setapprole executed meaning the next query would open a new connection. Explicitly opening the connection prevents EF from closing the connection (as was true with previous versions of EF):
``` 
public StaffContext()
    {
        try
        {
            db.Datadase.OpenConnection();
            this.Database.ExecuteSqlCommand("EXEC sp_setapprole 'foxgl', 'psw'");
        }
````
I would like to know how you got your query to work without this explicit OpenConnection(), e.g. is there some connection string magic or other config that keeps the connection open?

**Comment by rowanmiller** [comment]
@jim-thomas I didn't actually verify it worked end-to-end, just that executing the stored procedure worked. I didn't realize the app role would be lost when the connection was closed and re-opened. What you are doing is a good solution for the moment. When we have some better interception points (coming in the future) then we should be able to make this a lot cleaner for you.

**Comment by rowanmiller** [comment]
**Note for triage:** I don't think we need to do anything to specifically support app roles but we have seen a folks wanting to use several database feature now that require sending some pre-amble type SQL to the database before issuing any SQL. When we do the high level interception points, I think a relational specific OnDbConnectionOpened hook would be very helpful.

**Comment by jim-thomas** [comment]
Thanks for your guidance - it got us to a solution. I googled this topic many times and found no other info. I am surprised anyone else hasn't encountered it but perhaps EF7 is too new. App Roles have to be one of the easiest ways to protect data from the plethora of database access tools out there which don't enforce the business rules an enterprise application is built to do.

**Comment by rowanmiller** [comment]
Added a note about this scenario to our Lifecycle Hooks issue https://github.com/aspnet/EntityFramework/issues/626
