### ISSUE TITLE
EF 7 Install Issues

### ISSUE THREAD

**Issue by craigbern** [dotnet/efcore#4236]
I had so many issues installing EF7, I didn't know how to more specifically categorize them.

Here's my scenario (VS 2015):
- Created ASP.Net 5 project using Windows Auth.
- Added a Data project (Class library) to the solution
- Attempted to NuGet EF 7 into Data project. Not found. Even when I checked "Prerelease". I was told on Twitter it was on myGet. But, it's in RC! Shouldn't the prerelease checkbox take care of that? 
- Used myGet to install. Got errors that it wasn't compatible with .Net 5.4 (5.4? that's strange)
- Backed out Data project. Added a Data folder to web project.
- Used myGet to install EF7 into web project.
- Rebuilt. Error message: "Dependencies in project.json were modified. Please run dnu restore to generate a new lock file". 1) Why didn't the myget install update project.json? 2) I couldn't find any documentation on how to run dnu restore.

IMO, when the install doesn't work, I'm not sure I'm ready to take the plunge and use it. I have no idea what's lurking down inside.

**Comment by rowanmiller** [comment]
@craigbern it's on NuGet (MyGet is just for our nightly builds). Where you trying to install the EntityFramework.MicrosoftSqlServer package, or a different provider?

**Comment by craigbern** [comment]
@rowanmiller Hi Rowan. Nice to see you here. Searching for Entity Framework on NuGet didn't return acceptable results. I could get the current release version but when I checked "Prerelease" it didn't provide anything useful.

**Comment by rowanmiller** [comment]
Hey,

This is mostly due to the pre-release nature of our product. Our package names have changed a few times etc. so you really need to be explicitly installing the pre-release package you want to use. Once we reach stable release, the package names will remain the same and increasing download counts will give them a better ranking in search results.

**Comment by ErikEJ** [comment]
@rowanmiller Maybe lack of support for nuget tags in project.json makes the search sub-optimal?

**Comment by ewahner** [comment]
I have installed / uninstalled numerous times and still get the error that "The EntityFramework package is not installed on project etc...'  This was working before and sometimes when I uninstall / reinstall it works.  Other times it totally crashes VS 2015 when I run the "Update-Database" command.  I am currently using v7.0.0-rc1-final.  Any idea why it cannot find the package? Is there a more reliable way of running these ps commands that won't crash my VS IDE?

**Comment by ewahner** [comment]
Just as a followup to band-aid this problem I resorted to just creating a powershell script that ran the init.ps1 and install.ps1 and saved the script in my solution root directory.  Now when I have this problem in the Package Manager Console, I just type "ef7" the name of my script and it reruns those 2 powershell scripts and lets me work again.
