### ISSUE TITLE
Support "IgnoreChanges" on migrations

### ISSUE THREAD

**Issue by giggio** [dotnet/efcore#4237]
There is no equivalent for `IgnoreChanges` when generating migrations right now. Not on powershell, or using `ef migrations add`. This needs to come to EF7 and is a fundamental part of the migration work, specially for apps that are working with existing tables.

**Comment by bricelam** [comment]
See also #2167

**Comment by rowanmiller** [comment]
This is probably just stating the obvious... but as a workaround for the moment you can generate a migration and then delete the code from the Up/Down methods.

**Comment by rowanmiller** [comment]
**Team Triage:** Reopened the more general issue (https://github.com/aspnet/EntityFramework/issues/2167) to take a look at this and other existing database related functionality in migrations.

**Comment by giggio** [comment]
@rowanmiller #2167 is still closed...

**Comment by rowanmiller** [comment]
@giggio thanks - guess I moved it but didn't reopen... fixed now
