### ISSUE TITLE
Add exceptions to xml doc comments for common APIs

### ISSUE THREAD

**Issue by vmsgsp** [dotnet/efcore#4244]
Documentation: 
The current Entity Framework 7 API documentation does not specify which exceptions are thrown by the EF7 methods. This documentation is important, because then users of EF7 can design their exception handlers accordingly. 

Design: 
Currently EF7 does not wrap SqlExceptions into dedicated EF7 exception types. When DbContext.SaveChanges() is called and a connection to the database is not possible (wrong server name or missing network connection) a pure SqlException is thrown. This should be wrapped by EF7 into an EF7 exception type which is provider independent. At least EF6 ("six") wraps this SqlException into an System.Data.Entity.Core.EntityException.

This also leads to the question of how EF7 will differ from EF6 in terms of the exception design. One example of a difference already found between EF6 and EF7 for example is that EF7.DbUpdateExcption directly inherits from System.Exception, whereas EF6.DbUpdateException inherits from  System.Data.DataException.

Are there any estimates when the documentation of exceptions in Entity Framework 7 will be available?

**Comment by rowanmiller** [comment]
Agreed on the documentation. When we throw an EF specific exception that can be helpful to catch and handle in user code, then we should document it in the xml doc comments.

> Currently EF7 does not wrap SqlExceptions into dedicated EF7 exception types. When DbContext.SaveChanges() is called and a connection to the database is not possible (wrong server name or missing network connection) a pure SqlException is thrown. This should be wrapped by EF7 into an EF7 exception type which is provider independent. At least EF6 ("six") wraps this SqlException into an System.Data.Entity.Core.EntityException.

In EF7 we only wrap where we can provide additional value. For example, when an exception occurs saving a particular row of data, then we wrap in a `DbUpdateException` and provide the corresponding state entries. However, if the database connection fails to open etc. then there is nothing useful for us to add to the exception. Another way of looking at this, if you just want to handle any exception from `SaveChanges`, then there is no advantage to us providing a dedicated exception type to catch (with no additional details) vs. you just catching `Exception` in your code.

> This also leads to the question of how EF7 will differ from EF6 in terms of the exception design. One example of a difference already found between EF6 and EF7 for example is that EF7.DbUpdateExcption directly inherits from System.Exception, whereas EF6.DbUpdateException inherits from System.Data.DataException.

`DataException` is specific to ADO.NET but the core of EF has no dependency on ADO.NET (or relational databases for that matter). Given `DbUpdateExcption` is part of core, it can not depend on an ADO.NET specific type.

**Comment by divega** [comment]
Clearing up milestone of this issue so that we can determine its priority in triage.

**Comment by vmsgsp** [comment]
This item has been closed. But I cannot see any "justification" for closing it.
Does this mean that the documentation of EF will not be improved with regards to exceptions?
Or is this postponed?

**Comment by rowanmiller** [comment]
We decided that in general we don't see much value in doing this. We may chose to selectively do this as we document things, but we are not going to spend the time adding them to most APIs.
