### ISSUE TITLE
Multiple relations for the same Entity => wrong SQL

### ISSUE THREAD

**Issue by ahmad-moussawi** [dotnet/efcore#4245]
Consider the following models

```
class Grade {
 public int Id {get; set;}
 public List<Fee> Fees {get; set;}
 public List<AdmissionFee> AdmissionFees {get; set;}
}

class Fee {
 public int Id {get; set;}
 public string Name {get; set;}
}

class AdmissionFee : Fee {
 public int YearId {get; set;}
}

```

The generated SQL will be 

```
      SELECT "f"."Id",  "f"."Description",
       "f"."Discriminator",
       "f"."GradeId", --  ✅
       "f"."Name",            
       "f"."YearId",
       "f"."GradeId1" --  ❌
      FROM "Fee" AS "f"
      INNER JOIN (
          SELECT DISTINCT 
           "x"."Id"
          FROM "Grade" AS "x"
      ) AS "x" ON "f"."GradeId" = "x"."Id"
      WHERE (("f"."Discriminator" = 'AdmissionFee') OR ("f"."Discriminator" = 'Fee'))))
```

There is no Column named `GradeId1`

**Comment by rowanmiller** [comment]
You need to let EF know what the column is called. Given you don't have foreign key properties in your model, EF is introducing them by convention and giving them names that it picks. By default it's the primary key name, but since there are multiple it needs to de-dupe them.

```c#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Grade>()
                .HasMany(g => g.Fees)
                .WithOne()
                .HasForeignKey("GradeId");

            modelBuilder.Entity<Grade>()
                .HasMany(g => g.AdmissionFees)
                .WithOne()
                .HasForeignKey("<whatever the other FK column is called>");
        }
```

**Comment by ahmad-moussawi** [comment]
It's working !  😀 many thanks,

But why not picking the Primary Key always ? I can't imagine a scenario where generating virtual column is useful (e.g. `GradeId1`)

**Comment by rowanmiller** [comment]
> But why not picking the Primary Key always ?

I'm not sure what you mean by this. Because you don't have any foreign key properties in your model EF is introducing two foreign key columns for you (`GradeId` and `GradeId1`). If EF were generating the database for you then this would work and both columns would be added and setup with FK constraints. Because you are mapping to an existing database, you need to let EF know what the column names are (either by including corresponding properties in your class, or setting the names of the shadow state foreign key properties).

**Comment by ahmad-moussawi** [comment]
Actually my real models are slightly different than what I have provided above, So I've tried to reproduce the issue on a separate project, noting that:
 - I am generating the db from the models (Code first)
 - Developing on Mac, using the `1.0.0-rc1-update1    coreclr x64          darwin`
 - Using Sqllite as db

My models

```c#
public class Fee {
    public int Id { get; set; }
    public float Value { get; set; }
    public int? GradeId { get; set; }
    public Grade Grade { get; set; }
}

public class AdmissionFee : Fee {}

public class Grade {
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Fee> Fees { get; set; }
    public List<AdmissionFee> AdmissionFees { get; set; }
}
public class ApplicationDbContext : IdentityDbContext<ApplicationUser> {
    public DbSet<Grade> Grades { get; set; }
    public DbSet<AdmissionFee> AdmissionFees { get; set; }
    public DbSet<Fee> Fees { get; set; }
}
```
The generated table `Fee` has now the following columns: `Id`, `Discriminator`, `GradeId`, `Value`, `GradeId1`.

# 1 (Failed to reproduce, so you can ignore it for now)
For the main Issue I have opened it seems that I am doing something wrong since the generated db is now containing the `GradeId1` (Maybe I have changed the models without regenerating the db by mistake), anyway I will try to investigate more, to see how it happened

# 2 (Enhancement)
My Second question was why it generates the second column `GradeId1` when `GradeId` alone is sufficient since `AdmissionFee` and `Fee` cannot be set in the same row according to TPH.

So instead of 

Id | Discriminant | GradeId | GradeId1
------------ | ------------- | ------------- | ------------- 
1 | Fee | 1 | null
2 | AdmissionFee | null | 1

Suggested schema

Id | Discriminant | GradeId
------------ | ------------- | -------------
1 | Fee | 1
2 | AdmissionFee | 1

# 3 GradeId1 is always null when inserting data (Bug)

Here is how am inserting data

```c#
var grades = Enumerable.Range(1, 10).Select(x => new Grade {
  Name = $"Grade {x}"
});

foreach(var g in grades){
    
  db.Grades.Add(g);

  db.Fees.Add(new Fee {
     GradeId = g.Id,
     Value =  g.Id * 100
  });

  db.AdmissionFees.Add(new AdmissionFee {
     GradeId = g.Id,
     Value =  g.Id * 50
  });
}

return db.SaveChanges();
```

and here is a snapshot of the table

Id | Discriminant | GradeId | Value | GradeId1
------------ | ------------- | ------------- | ------------- | ------------- 
1 | Fee | 1 | 100 | null
2 | AdmissionFee | 1 | 50 | null

And Always it's returning as their is no admission fees

```c#
return db.Grades
    .Include(x => x.Fees)
    .Include(x => x.AdmissionFees)
    .ToList();
```

returns 

```json

  [
  {
    "id": 1,
    "name": "Grade 1",
    "fees": [
      {
        "id": 1,
        "value": 100.0,
        "gradeId": 1
      },
      {
        "id": 18,
        "value": 50.0, // <-- this should be admission fee and not regular fee
        "gradeId": 1
      }
    ],
    "admissionFees": [
       // <--- there is no admission fees
    ]
  },
// ....
]
```

**Comment by rowanmiller** [comment]
Ah, I think I see what the point of confusion is now. I think what you really want is just one relationship that can contain both `Fee` and `AdmissionFee`. What you are getting though, is two separate relationships:

* `Grade.Fees` give you a relationship where a `Grade` can have many `Fee`s (either `Fee` or `AdmissionFee`.
* `Grade.AdmissionFees` gives you a second relationship where a `Grade` can have many `AdmissionFees`.

Because there are two relationships, there have to be two separate FK columns in the database. To demonstrate this, here is some code that adds several different Fees to the two different navigation properties:

```c#
db.Grades.Add(new Grade
{
    Name = "New Grade",
    Fees = new List<Fee>
    {
        new Fee {  Value = 10 },
        new AdmissionFee {Value = 20 }
    },
    AdmissionFees = new List<AdmissionFee>
    {
        new AdmissionFee {Value = 30 }
    }
});

db.SaveChanges();
```

And here is the resulting data in the database:

Id | Discriminator | GradeId | Value | GradeId1
------------ | ------------- | ------------- | ------------- | ------------- 
1 | AdmissionFee | NULL | 30 | 1
2 | Fee | 1 | 10 | NULL
3 | AdmissionFee | 1 | 20 | NULL

As you can see `GradeId` identifies which `Grade` it is related to via the `Grade.Fees` collection and `GradeId1` identifies which `Grade

**Comment by rowanmiller** [comment]
BTW you could always leave the `Grade.AdmissionFees` property and just make it a wrapper over the `Fees` property:

```c#
public class Grade
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Fee> Fees { get; set; }

    [NotMapped]
    public IEnumerable<AdmissionFee> AdmissionFees
    {
        get { return Fees.OfType<AdmissionFee>();
    }
}
```

**Comment by rowanmiller** [comment]
Closing out as I am confident we have got to the bottom of this one. But feel free to re-open or comment if you do not agree :smile:

**Comment by ahmad-moussawi** [comment]
Many thanks, Yes I can follow the approach for now `.OfType<AdmissionFee>()` but actually here I am filtering at the app level and not the db level.

Anyway no doubt that EF7 is going to a next level, great job guys, this is the first time that I feel that am really satisfied with ASPNET !! <3
