### ISSUE TITLE
HasForeignKey().OnUpdate() needed to disable a cascade Update in a self referencing table

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4249]
Otherwise you will get the following error when applying the migrations:

Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

**Comment by rowanmiller** [comment]
This is a SQL Server specific restriction. When targeting SQL Server, you would need to disable cascade delete on this relationship:

http://docs.efproject.net/en/latest/modeling/relationships.html#id2

```c#
            modelBuilder.Entity<Employee>()
                .HasOne(e => e.Manager)
                .WithMany(e => e.Reports)
                .HasForeignKey(e => e.ManagerId)
                .OnDelete(DeleteBehavior.Restrict);
```
