### ISSUE TITLE
Cleanup code generated in ModelSnapshot (extra line breaks, etc.)

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#4253]
For almost all entities model snapshot scaffolds the table name. If there is nothing else generated after `ToTable` call then blank line is added. If there are entity type annotations generated then there are 2 blank lines before HasAnnotation call.

```
builder.Entity(""Microsoft.Data.Entity.Commands.Migrations.ModelSnapshotTest+DerivedType"", b =>
    {
        b.HasBaseType(""Microsoft.Data.Entity.Commands.Migrations.ModelSnapshotTest+BaseType"");

        b.ToTable(""DerivedType"");

    });
```

**Comment by smitpatel** [comment]
`ToTable` are removed with #4654 
copied from https://github.com/aspnet/EntityFramework/pull/4673#issuecomment-191456078
The current way still leaves space for additional line breaks.
 Configurations in entity type always adds line above but does not add below. This avoids un-necessary line break at the end. There are 2 exceptions to this.
 1. First property does not add line above since there is nothing before (in the absence of base type)
 2. BaseType does not add line above since it always comes first but it adds line before to compensate for the first property.

Now in this whole setup if there are some configurations not declared then it will leave extra line breaks.
 If there are no properties (of course in derived type) but any other configuration then extra line breaks will occur between those 2. If Base type is the only thing then there will be extra line at the end.
 Since they are not much frequent and does not create merge issues for model snapshot its very low priority.

**Comment by smitpatel** [comment]
one solution would be keep track of line added previously and next function behaves accordingly.
cc: @bricelam

**Comment by ajcvickers** [comment]
@bricelam Do we still need to keep this open?

**Comment by bricelam** [comment]
No, probably not. It doesn't have to be pretty so long as it merges cleanly.

**Comment by ajcvickers** [comment]
Closing this as we're not planning to do anything here. However, we would likely accept well-written community PRs that did this. The bottom line is that whatever we do, we should not compromise the ability to diff the file when comparing to previous versions in source control.
