### ISSUE TITLE
EF7 License information, Redistrubition 

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/efcore#4256]
Hi @rowanmiller , @divega 

We are developing an EF7 provider and had to use some of the code which is  made generally available by the following GitHub repository
https://github.com/aspnet/EntityFramework

We would like to know if  the EF7  code licensed under Apache License v2 enables us for:

1) Deriving/Reusing/Modifying the available code specific to our provider needs.
2) Building and Redistributing the binaries from this derivative work for commercial purposes.

Thanks,
Prashanth

**Comment by rowanmiller** [comment]
cc @Eilon 

I'm not sure that any of us here can give you a definitive legal analysis of the Apache 2.0 license... but your ability to do those things is definitely our intent with using the Apache 2.0 license.

**Comment by Eilon** [comment]
@PrashanthIBM unfortunately we cannot provide any legal advice or guidance. The source code is fully licensed under the Apache 2.0 license, so as long as you comply with that license, you are good to go.

You can find more information on this site: http://www.apache.org/licenses/LICENSE-2.0.html
