### ISSUE TITLE
Are circular dependencies supported?

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#4261]
Are the following entity and code supported by the latest version of Entity Framework?

I realize the update and delete triggers need to be configured correctly, and I realize it would require two save operations on the database.  

However, In the older version of Entity Framework I was able to use a TransactionScope to do this easily with multiple calls to SaveChanges at different places in the business services.  However, with the new Transaction model, I'm finding it hard to write code that accomplishes the following inside a single transaction.

```
public class Person {
    public virtual Person NextVersion { get; set; }
    public virtual Person PreviousVersion { get; set; }
}
```

```
var personCurrent = new Person();
var personPrevious = new Person() {
  NextVersion = personCurrent,
};
personCurrent.PreviousVersion = personPrevious;

dataContext.Add(personCurrent);
dataContext.Add(personPrevious);
dataContext.SaveChanges();

```

**Comment by rowanmiller** [comment]
@joshmouch this works in a single save operation because there isn't anything circular in the data. Assuming that there is a `NextVersionPersonId` foreign key column in the database then `personPrevious` can be inserted first (because it's `NextVersionPersonId` will be null) and then `personCurrent` can be inserted with the FK values set to the value assigned to `personPrevious`. If the FK was the other way around (i.e. `PreviousVersionPersonId`) then the inserts would work the other way around.

**Comment by joshmouch** [comment]
OK, then I must be doing something wrong.  Here is a model configuration that results in a circular dependency error when I try to save:

````

			entity.HasOne(t => t.PreviousVersion)
				.WithMany()
				.HasForeignKey(t => t.PreviousVersionId)
				.HasPrincipalKey(t => t.Id)
				;

			entity.HasOne(t => t.NextVersion)
				.WithMany()
				.HasForeignKey(t => t.NextVersionId)
				.HasPrincipalKey(t => t.Id)
				;
````

And here is the top level of the error:

````
An unhandled exception occurred while processing the request.
InvalidOperationException: A circular dependency was detected: 
'ENTITYNAMEHERE' {'NextVersionId'} -> 'ENTITYNAMEHERE' {'Id'}, 
'ENTITYNAMEHERE' {'PreviousVersionId'} -> 'ENTITYNAMEHERE' {'Id'}.
Microsoft.Data.Entity.Internal.Multigraph`2.BatchingTopologicalSort(Func`2 formatCycle)

````

**Comment by rowanmiller** [comment]
Hmmm... wouldn't `previous` and `next` be inverse navigations of the same relationship, rather than two separate relationships? I.e. If `personPrevious.Next` points to `personCurrent` then shouldn't `personCurrent.Previous` point back to `personPrevious`.

**Comment by joshmouch** [comment]
When I try it that way, I get a different error when I try to migrate the database.

````

			entity.HasOne(t => t.PreviousVersion)
				.WithOne(t => t.NextVersion)
				.HasForeignKey<Person>(t => t.PreviousVersionId)
				.HasPrincipalKey<Person>(t => t.NextVersionId)
			;
````

Error:
````
The navigation property '' cannot be added to the entity type 'Person' because a navigation property with the same name already exists on entity type 'Person'.
````

**Comment by rowanmiller** [comment]
That would be https://github.com/aspnet/EntityFramework/issues/4069 which is fixed in our nightly builds and will ship in RC2.

**Comment by joshmouch** [comment]
Perfect, thanks!  Until then, I added some crazy code in the DbContext.OnSave to split the save into two parts.

Just to confirm, the first model configuration isn't/shouldn't be supported?

**Comment by smitpatel** [comment]
There exist a circular dependency. `personCurrent.PreviousVersionId` takes value from `personPrevious.Id` & `personPrevious.NextVersionId` takes value from `personCurrent.Id`. The exception message looks bit confusing since there is only one entity, its just different instances causing error.
