### ISSUE TITLE
EF7 Reverse Engineer Existing DB - Timout error

### ISSUE THREAD

**Issue by zoinkydoink** [dotnet/efcore#4272]
I have already logged it on stackoverflow but no responses so I thought I would try here

http://stackoverflow.com/questions/34712605/ef7-reverse-engineer-existing-db-timout-error

**Comment by mikes-gh** [comment]
My commandline for comparism is

`dnx ef dbcontext scaffold "Server=myserver;Database=mydatabase;Trusted_Connection=True;MultipleActiveResultSets=true" EntityFramework.MicrosoftSqlServer --context ReportingDbContext --output-dir Models`

Run from the root of my project directory

**Comment by rowanmiller** [comment]
My guess is that this is probably something specific to your environment. Searching around it seems like folks hit this when there is an issue with network configuration ([this post on StackOverflow for example](http://stackoverflow.com/questions/551282/semaphore-timeout-period)). Are you able to try from a different machine and with a different instance of the database server?

If you are able to share your schema, then I'm also happy to see if I can reproduce the issue at our end.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details. Feel free to re-open if you are able to provide steps for us to reproduce the issue.
