### ISSUE TITLE
Where is IDbSet? I need it for mocking & unit testing my context

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4273]
In EF 6 I was using `IDbSet` to mock out my db context using `moq`. I would do something like: 

``` c#
var mockContext = new Mock<IGeographyContext>();

// COUNTRIES
var countries = new List<Country>
{ 
    new Country { Id = 1, Name = "A", Code = "AAA" },
    new Country { Id = 2, Name = "B", Code = "BBB" },
    new Country { Id = 3, Name = "C", Code = "CCC" }
}
.AsQueryable();

var mockCountries = new Mock<IDbSet<Country>>();
mockCountries.Setup(m => m.Provider).Returns(countries.Provider);
mockCountries.Setup(m => m.Expression).Returns(countries.Expression);
mockCountries.Setup(m => m.ElementType).Returns(countries.ElementType);
mockCountries.Setup(m => m.GetEnumerator()).Returns(() => countries.GetEnumerator());
mockContext.Setup(x => x.Countries).Returns(mockCountries.Object);
```

Now I try to use `IDbSet` and it cannot be found. Where is it? If its not available then how do I mock out a context like above using EF 7?

**Comment by davidroth** [comment]
Just use `DbSet<TEntity>` instead. Its abstract and all methods are virtual, so full mocking is possible.
I would also have a look at the new InMemoryProvider which allows more advanced testing scenarios.

**Comment by rowanmiller** [comment]
@davidroth's comments apply to EF6 as well. Interfaces suffer from the "any new member we add breaks existing code" problem. So we made it so that you can mock DbSet directly in EF6 (or maybe it was 6.1). InMemory is new in EF7 though... and much simpler :smile:.
