### ISSUE TITLE
Two entities with a 1- many and 1-1 relationship requires two saves.

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#4274]
I have two entities.

1.Customer
2.address 

With two relationships
1.Customer has multiple addresses
2. Customer has 1 primary location picked out of the previous relationship.

This creates the correct structure but requires that I manually save the first relationship before I can save the second.

This is a duplicate of http://entityframework.codeplex.com/workitem/list/basic?keywords=DevDiv%20[Id=110648]

**Comment by rowanmiller** [comment]
I think this is expected. From your description, each Address has an FK that points to the Customer and Customer has an FK that points to the primary address. You can't save this in one go in a relational database (at least not with store-generated keys and/or foreign key enforcement on).

**Comment by Tarig0** [comment]
The only reason why I disagree is that previously the comments have been a general consensus of; The pattern is a good case to handle in one go, but we can't get it in this release.

**Comment by rowanmiller** [comment]
@Tarig0 fair (I guess I did write that comment :smile:). At least at this stage it's not something we are planning to implement in EF7.
