### ISSUE TITLE
No DbContext named 'SomeDbContext' was found.

### ISSUE THREAD

**Issue by huytnd** [dotnet/efcore#4276]
My scenario: I created a separate asp.net class library for my DAL using EF7.0.0-RC1, and the code for my dbcontext was very simple like this.

```
public class MediaDbContext : DbContext
    {
        public string connectionString { get; set; }
        public DbSet<AlbumCategory> AlbumCategories { get; set; }

        public MediaDbContext(DbContextOptions<MediaDbContext> options) : base(options)
        {
            connectionString = options.FindExtension<SqlServerOptionsExtension>().ConnectionString;
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(connectionString);
        }


    }
}
```

I had a separate asp.net 5 web application with a call to use EF service in the Startup.cs file like this.

```
services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<MediaDbContext>(options =>
                {
                    options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
                });
```

The ConnectionString was defined in the appsettings.json file. I wanted to add a migration to my dbcontext using this command for the class library project above

```
dnx ef migrations add Initial -c MediaDbContext
```

And I got this error message
![no_context](https://cloud.githubusercontent.com/assets/2102905/12245019/f5fae93e-b8d8-11e5-8ace-2b1f275f39fd.jpg)
So, did I miss to configure something, or did I do wrong?

**Comment by bricelam** [comment]
#4084 should improve this experience

**Comment by rowanmiller** [comment]
As @bricelam mentioned, we've made some improvements to help get you on the right path in RC2. In the meantime, invoke the command on your startup project and specify your data access project with the `-targetProject` parameter.

**Comment by huytnd** [comment]
I used ```-targetProject``` as you mentioned, and got these message.
![targetproject](https://cloud.githubusercontent.com/assets/2102905/12284779/5ee540ae-b9e5-11e5-87de-b5229f992402.jpg)
Is it only available in RC2 version, and I need to upgrade EF?
