### ISSUE TITLE
Is MARS supported in EF RC1

### ISSUE THREAD

**Issue by minteractive** [dotnet/efcore#4278]
I see mixed responses online so just wanted to see if MARS is implemented and supported in RC1. This is going to drive us whether to move to EF 7 or EF 6.

**Comment by natemcmaster** [comment]
On Linux, MARS is buggy. See https://github.com/dotnet/corefx/issues/4273. This was fixed with https://github.com/dotnet/corefx/pull/4486 which will be in RC2 and is currently in the coreclr nightlies.

On Windows there are no known issues with MARS in RC1.

**Comment by minteractive** [comment]
Thanks, I am actually running this is on Windows machine. 
I am trying some code before we decide on which version to adapt and below is the code I am trying to execute a stored proc, how to change this to retrieve multiple entities returned by the proc?

_dbContext
 .Set<Student>()
 .FromSql("dbo.GetStudentsAndCourses")
 .AsNoTracking()
 .ToList();

GetStudentAndCourses returns multiple result set and don't know how to retrieve the second result set. I saw few examples to do that with EF6 which uses Translate on the Context and Data Reader instance but that API is missing in EF7.

**Comment by rowanmiller** [comment]
I don't think you can really make that work on EF7 (at least not with a large amount of work to re-use a bunch of internal components).
