### ISSUE TITLE
Query: Better diagnostics/errors/exceptions on failed queries

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#4289]
Because query is so perf sensitive we don't do much defensive checking of results etc. which can result in exceptions that are difficult to debug. We don't want to add these defensive checks, since that would have a significant impact on performance, but once a query fails we could run some additional logic to try and provide some guidance on why the error may have happened. In EF6 we would re-run parts of the query pipeline in a "slow but defensive" mode to try and get a better error. We don't necessarily want to take the same approach in EF7... we may just want to run some analysis on the results/model to suggest what issues could be the result of errors.

For example:
- If the database returns a null value for a column that is configured as non-nullable in the model, EF doesn't defensively check this and you get a NullReferenceException with no helpful details (see https://github.com/aspnet/EntityFramework/issues/4120). 
- If the data type of a value in the result set can not be cast to the data type configured in the model, then an InvalidCastException with no helpful details (see https://github.com/aspnet/EntityFramework/issues/3923).

**Comment by divega** [comment]
Clearing milestone to have a chance to discuss this again in triage. During app week I had to work with an existing database and hit this kind of issue multiple times. The way EF Core crashed when there was a type mismatch or an unexpected null value was not helpful at all and diagnosing the cause of the error was very time consuming.

**Comment by rowanmiller** [comment]
talk with @anpete  and @divega about some ideas of how we do this
