### ISSUE TITLE
Ability to cascade delete immediately (rather than on SaveChanges)

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#4290]
This could be useful for data binding scenarios etc.

There are a few ways this could be implemented:
- An `ApplyCascadeDeletes()` API on `ChangeTracker`
- A new `CascadeImmediately` value in the `CascadeBehavior` enum
- A context wide setting for when cascade deletes are processed (on delete or on save)

**Comment by ajcvickers** [comment]
Closing as duplicate of #10114 since that issue has more details.
