### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by nrkarthick** [dotnet/efcore#4293]
The Oracle .NET team is evaluating EF Core support, but have not announced any timing. **You can vote on the [Oracle EF Core Provider feature request](https://apex.oracle.com/pls/apex/f?p=18357:39:105422858407495::NO::P39_ID:28241)**.

Please direct any questions about this provider, including the release timeline, to the [Oracle Community Site](https://community.oracle.com/).

**Comment by erikbullens** [comment]
Hi,
Did you connect to Oracle with EF7?

**Comment by ErikEJ** [comment]
Oracle support for EF7 should be addressed with Oracle support https://community.oracle.com/message/13562069#13562069

**Comment by nrkarthick** [comment]
@erikbullens .. yes i successfully connect to oracle but with EF 6.1.3.. My problem here is, that the Identity 3.0 is not supporting EF 6.1.3..

**Comment by erikbullens** [comment]
So you don't use the version 7?

**Comment by nrkarthick** [comment]
Yes..

**Comment by erikbullens** [comment]
When are you planning to use it?

**Comment by rowanmiller** [comment]
@nrkarthick we have reached out to our provider writers about creating providers for EF7. Historically, our team has only implemented the SQL Server provider and the database vendors (or third parties) have implemented the providers for their database engines. We have been working with Oracle, but sharing anything along the lines of commitments/plans/timelines/etc. is really up to their team and not something I can comment on.

**Comment by rowanmiller** [comment]
Closing out as I don't think there is anything else to answer here. Feel free to re-open if you disagree :smile:

**Comment by nrkarthick** [comment]
@rowanmiller Thanks for the update..  Oracle is one of the most widely used databases on earth. Not sure why an oracle provider is not included in Beta stage itself.. Expecting the team to include as early as possible.

**Comment by jasonwilliams200OK** [comment]
@alexkeh (Oracle Corp.), could you please provide some sort of hint whether Oracle team is interested in / working on delivering the EF7 provider sometime around the EF7 RTM (which is pretty soon now)? Is there anything the community can do to expedite this feature request?

**Comment by alexkeh** [comment]
Hi Peter,
The Oracle .NET team is evaluating EF7 support, but we have not 
announced any timing.

The community can vote for the Oracle EF7 feature request here:
https://apex.oracle.com/pls/apex/f?p=18357:39:105422858407495::NO::P39_ID:28241

That will help us prioritize the feature.

**Comment by nrkarthick** [comment]
@alexkeh.. Any updates from your team.. ?

**Comment by alexkeh** [comment]
@nrkarthick No new info announced yet.

**Comment by csmith93** [comment]
@alexkeh Anything new? If not, is there a place to check?

**Comment by alexkeh** [comment]
@nrkarthick No new info. I do have a follow up question that you and anyone else that reads this thread can answer.

Which platforms are you looking to use EF Core on: Windows, Linux, and/or Mac? If Linux, which Linux OSes?

**Comment by csmith93** [comment]
Windows here. In particular, attempting to connect to a PeopleSoft Database.

**Comment by jasonwilliams200OK** [comment]
@alexkeh, preferably all of them, but if the work is out in open, maybe community members such as myself can chime in and help you guys figuring out the entire dotnet-cli+project.json ecosystem.

If there already exists a GitHub repo where EF7 port is going on, please post the link and I would be happy to jump in. :swimmer:

**Comment by alexkeh** [comment]
@jasonwilliams200OK There are no current plans to open source Oracle EF7 provider support. 

I understand you want all OSes supported. Do you have a priority list?

**Comment by jasonwilliams200OK** [comment]
Thanks for clarification Alex!

> Do you have a priority list?

Personally and going by CoreCLR platform support priority:

* Windows 8.1, Windows 10
* Ubuntu 14.04, Ubuntu 16.04
* OS X 10.11
* CentOS 7.1
* Debian 8.4
* Fedora 23
* Red Hat 7.2
* openSUSE 13.2
* FreeBSD 10.1

see: https://github.com/dotnet/coreclr#build-status & https://github.com/dotnet/corefx#build--test-status

@mmitche, @ellismg could you guys please confirm the CoreCLR platform support priority list for Oracle engineers (@alexkeh et al.)?

**Comment by mmitche** [comment]
@jasonwilliams200OK @leecow Is the right person to answer that question.

**Comment by jasonwilliams200OK** [comment]
@mmitche, @leecow, for the context:
* https://community.oracle.com/people/Alex%20Keh%20-%20Product%20Manager-Oracle?customTheme=otn
* https://community.oracle.com/message/13562069#13562069

 and this post from the beginning.

**Comment by leecow** [comment]
@jasonwilliams200OK @alexkeh - Here's the official list we're working toward. 

Windows - 32bit and 64bit
- Windows Server 2012 R2 (Full and Server Core)
- Windows Server 2012 SP1 (Full and Server Core)
- Windows Server 2008 R2 SP1 (Full and Server Core)
- Windows Server 2016 (Full, Server Core, and Nano)
- Windows 7 SP1
- Win 8.1
- Win 10
- UWP

Linux - 64bit only
- CentOS 7.1+
- Debian 8.2+
- Fedora 23
- Linux Mint 17+
- openSUSE 13.2
- Oracle Linux 7.1+ 
- Red Hat Enterprise Linux 7.2+
- Ubuntu 14.04 LTS
- Ubuntu 16.04 LTS

Mac - 64bit only
- OS X 10.11+

**Comment by alexkeh** [comment]
@leecow That appears to be a somewhat alphabetical list. Do you have a priority for which OSes should be certified first?

**Comment by leecow** [comment]
@alexkeh The list is alphabetical for convenience and is the set of distros we are bringing up for the release of .NET Core, ASP.NET Core and EF Core 1.0.0.

**Comment by alexkeh** [comment]
@leecow Ok. You're a MS PM and you provided the official planned support list. I initially thought you were a customer.

Thanks for the list. My team will take it under advisement. We're glad to see Oracle Linux is planned. ;-)

**Comment by jasonwilliams200OK** [comment]
> We're glad to see Oracle Linux is planned.

True, Oracle Linux is one of the official runtime targets and has series of RIDs listed here: https://github.com/dotnet/corefx/blob/4ddf773/pkg/Microsoft.NETCore.Platforms/runtime.json (all the `ol*` IDs are of Oracle Linux: [runtime.json#L203-L236](https://github.com/dotnet/corefx/blob/4ddf773/pkg/Microsoft.NETCore.Platforms/runtime.json#L203-L236))

**Comment by jasonwilliams200OK** [comment]
@leecow, 1.0 RTM is  announced. I can't find Oracle Linux package of dotnet core at https://www.microsoft.com/net/download#core. Is it yet to arrive?

**Comment by rowanmiller** [comment]
Oracle has not released a provider for .NET Core/EF Core as yet. You could follow up with Oracle at https://community.oracle.com/ and add your voice to the request for a provider. I can't share any plans with you as it is up to their team what they make public etc.

**Comment by jasonwilliams200OK** [comment]
@rowanmiller, the status of Oracle Provider is and should be very obvious to me if you follow the conversation on this thread. My question to @leecow wasn't about the provider, I was referring to his comment above https://github.com/aspnet/EntityFramework/issues/4293#issuecomment-224981380 which indicates that "Oracle Linux" is one of the target distros for v1.0 RTM of .net core.

**Comment by rowanmiller** [comment]
@jasonwilliams200OK sorry about that, you're right, it was pretty obvious (I was skim reading)

**Comment by leecow** [comment]
@jasonwilliams200OK - Use the CentOS packages for Oracle Linux. Step by step is available at https://www.microsoft.com/net/core#centos. I'll have the folks also add an appropriate row to the download table at https://www.microsoft.com/net/download#core

**Comment by jasonwilliams200OK** [comment]
Thanks; would be nice to enlist it in the table :)

**Comment by nrkarthick** [comment]
@leecow .. expecting the EF7 Oracle provider (for windows) will be released before July 2016.. :)

**Comment by leecow** [comment]
Thanks @nrkarthick !

**Comment by flts** [comment]
@nrkarthick Any news / ETA on a version of the EF Core Oracle provider?
Thanks!

**Comment by nrkarthick** [comment]
@flts  I am also waiting for the EF Core Oracle provider.  @alexkeh/@leecow  may answer your question...

**Comment by alexkeh** [comment]
@nrkarthick @flts No new info to report. When an announcement is ready, you'll see it tweeted out at @oracledotnet https://twitter.com/oracledotnet

**Comment by nate98** [comment]
I saw a new update to Oracle Developer Tools for VS 2015 dated Sept 17th, but still no mention of EF 7 support.  Can we hope to hear an announcement coming out of this week's OOW conference?

**Comment by nrkarthick** [comment]
@nate98 , whether EF7 supported in the latest update ? Have u tried ?

**Comment by nate98** [comment]
I tried the latest update.  It does not work.  Here is the error I see after adding references in my project:
<img width="500" alt="screen shot 2016-09-29 at 10 28 21 am" src="https://cloud.githubusercontent.com/assets/22380312/18960490/94ed13a4-862f-11e6-9bfd-373a92df6178.png">

**Comment by alexkeh** [comment]
@nate98 The 9/17 release does not include EF7 support.

**Comment by nrkarthick** [comment]
@alexkeh .. thank you..  but Devart released the paid version of the provider ([read here)](https://www.devart.com/news/2016/dotconnects-ef7.html) .. and finally requesting the Oracle team to release atleast the beta version of Oracle EF core..

**Comment by nrkarthick** [comment]
@rowanmiller Hi.. why the name changed ?

**Comment by csmith93** [comment]
@nrkarthick Probably because it's already in the aspnet/EntityFramework repo. Additionally, EF 7 was renamed EF Core months ago.

**Comment by nrkarthick** [comment]
ok..

**Comment by nrkarthick** [comment]
Hi folks .. any updates ?..

**Comment by vilinski** [comment]
any updates for Oracle on .NET Core?

**Comment by csmith93** [comment]
@nrkarthick, @vilinski this was closed as it's a vendor issue, not a EF Core issue. It's Oracle's responsibility to make their platform work with EF, not the other way around. @alexkeh has mentioned in this thread where you can find updates, and you can also request this to be prioritized here: https://apex.oracle.com/pls/apex/f?p=18357:39:105422858407495::NO::P39_ID:28241.
