### ISSUE TITLE
Migrations: Unnecessary index filter

### ISSUE THREAD

**Issue by OlsonDev** [dotnet/efcore#4294]
I'm using `SQL Server Express LocalDB 12.0.2000.8` and `Entity Framework 7.0.0-rc1-final`.

I have this line of configuration in my `OnModelCreating`:

``` c#
modelBuilder.Entity<ProjectUrl>().HasIndex(pu => new { pu.ProjectId, pu.Url }).IsUnique();
```

It generated this index:

``` sql
CREATE UNIQUE NONCLUSTERED INDEX [IX_ProjectUrl_ProjectId_Url] ON [project].[ProjectUrl]
(
    [ProjectId] ASC,
    [Url] ASC
)
WHERE ([ProjectId] IS NOT NULL AND [Url] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
```

The interesting thing is `ProjectId` is a `Guid` and `Url` is a `[Required] string`, thus they're both `NOT NULL`, thus the filter is 100% redundant.

I'm not sure if SQL Server optimizes that filter away internally but I'd rather not have to figure that out -- an index without the filter would be better.

**Comment by rowanmiller** [comment]
**Note for Triage:** The SQL in the description looks like a reverse engineer from SQL Management Studio. Here is the actual SQL we send to the database:

```SQL
CREATE UNIQUE INDEX [IX_ProjectUrl_ProjectId_Url] ON [ProjectUrl] ([ProjectId], [Url]) 
WHERE [ProjectId] IS NOT NULL AND [Url] IS NOT NULL;
```

**Comment by bricelam** [comment]
Looks like [we always do this](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.MicrosoftSqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L191-L212) for unique, nonclustered indexes. We could be smarter, but we'd have to search for the corresponding CreateColumn operation or property in the model to see if the columns are required.

**Comment by rowanmiller** [comment]
It would take some non-trivial changes to flow the nullability information for columns to the CreateIndex model in migrations. We would certainly consider doing this if there was a negative impact of having the redundant `IS NOT NULL` clause. However, it doesn't seem there will be any performance impact etc. in having the redundant clause.

Feel free to reopen if you are seeing negative side effects of having the redundant clause.
