### ISSUE TITLE
Is there a way to customize the patterns that the scaffold generates?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dotnet/efcore#4300]
for example, for foreign key relationships, it generates something like `UserId_OwnerNavigation`,
and I'd like to just be `Owner` which I could do by replacing everything before and including the `_` and delete `Navigation`.

Is that possible? or something so that I can make the relationships a little less awkward?

**Comment by natemcmaster** [comment]
This looks similar to https://github.com/aspnet/EntityFramework/issues/4038.

**Comment by rowanmiller** [comment]
Yes, this is exactly what #4038 is about (this is one of the key scenarios for manipulating the model before it is sent to templating). There isn't really any way to do it at the moment - unless you want to start mucking around in the low-level provider components and even then I don't know that you can do it without effectively writing a wrapping provider.
