### ISSUE TITLE
"build initialize" fails with latest source 

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#4305]
Nuff said:

C:\Code\EntityFramework>build initialize
Package "Sake.0.2.2" is already installed.
Package "xunit.runner.console.2.1.0" is already installed.
dotnet_install: Preparing to install .NET Tools to C:\Users\eejj\AppData\Local\M
icrosoft\dotnet
dotnet_install: Downloading dotnet-win-x64.latest.zip from https://dotnetcli.blo
b.core.windows.net/dotnet/dev/Binaries/Latest
dotnet_install: Extracting zip
mv : Access to the path 'C:\Users\eejj\AppData\Local\Microsoft\dotnet\cli_new'
is denied.
At C:\Code\EntityFramework.build\KoreBuild-dotnet\build\dotnet-install.ps1:81
char:1
- mv "$InstallDir\cli_new" "$InstallDir\cli"
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (C:\Users\eejj\A...\dotnet\cli_new:D
    irectoryInfo) [Move-Item], IOException
  - FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Co
    mmands.MoveItemCommand

**Investigation**

Changing line 81 has no effect: 

```
  mv "$InstallDir\cli_new" "$InstallDir\cli" -Force
```

Adding this line above line 81 makes the process complete:

```
 sleep -s 10
```

Assume this means that the script is not robust enough to survive on-access virus scanners. Using McAfee VirusScan Enterprise 8.8

**Comment by ErikEJ** [comment]
Restarting my PC actually seems to have fixed this...

**Comment by rowanmiller** [comment]
@ErikEJ anything for us to look at here... or is it resolved?

**Comment by ErikEJ** [comment]
I will reopen if required
