### ISSUE TITLE
Running tests with project.json based projects - how to?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#4307]
TestDriven.NET in VS no longer works for me - how do I run tests with the new project system?

I can also see that all test Projects seem unable to resolve references to product code/objects. What am I doing wrong?

**Comment by divega** [comment]
cc @bricelam

**Comment by natemcmaster** [comment]
Make sure you have RC1 aspnet tooling installed. When you first open the solution, trigger a build. When a build completes successfully, this should kick off the "TestHost" discovery. This can take >30 seconds. Discovered tests will appear in "Test Explorer"

**Comment by ErikEJ** [comment]
"Test Explorer" is back! Where do I get the "RC1 aspnet tooling" - maybe worth linking in this thread?

**Comment by ErikEJ** [comment]
Looking under the "References" node in the test project, there are no reference to the product Projects !?

**Comment by natemcmaster** [comment]
AspNet5.ENU.RC1_Update1.exe
https://go.microsoft.com/fwlink/?LinkId=627627

**Comment by natemcmaster** [comment]
@Erikej lots of things could be going wrong. Xproj can take a while to restore packages.  TestHost can take a while to discover. Perhaps you need a newer version of DNX. It's a pain, but we're struggling with the tooling too.

FWIW if you see this yellow bar, it means package restore hasn't finished and build won't work yet.
![image](https://cloud.githubusercontent.com/assets/2696087/12333062/d92a0da6-baa6-11e5-8f01-31273c55dc8a.png)

**Comment by ErikEJ** [comment]
How do I get the latest DNX: "build initialize" or ?

**Comment by natemcmaster** [comment]
`build initialize` or `dnvm upgrade -u`

**Comment by bricelam** [comment]
Things will be painfull over the next few weeks as we transition off DNX and wait for everything (UWP, NuGet, Web Tools, xUnit.net, CLI, etc.) to converge.

**Comment by ErikEJ** [comment]
@natemcmaster @bricelam Thanks for all you help here on the bleeding edge. Doing a new clone, being more patient and disabling Resharper fixed my issues!
