### ISSUE TITLE
DbContext and Async/Await

### ISSUE THREAD

**Issue by ac-esousa** [dotnet/efcore#4310]
I started using EF7 with SQL Server in a WebAPI projector following the Async/Await pattern.

For retrieving data I am using `ToListAsync` extension method, and `SaveChangesAsync` to save data.

In a method that reads and writes data this way, using the same DbContext, I often get the following error:

```
New transaction is not allowed because there are other threads running in the session
```

I've tried scoping the work into a EF transaction, but I also got some other errors, due to the Context being used in different threads.

It seems that EF7 SQL Server driver is not able to handle DbContext being used in different threads, which is what happens in a ASPNET project following the Async/Await pattern.

I was able to get it working creating a new SynchronizationContext to force everything to run in same thread. But this will go against Async/Await goals.

**Comment by divega** [comment]
@ac-esousa DbContext instances are not thread safe but it should be possible to use them in different threads as long as the access is not concurrent.

Without a repro it is hard to be sure if there is a problem in EF7 or in the way you are using it, but the particular exception you mention is known to arise when using SQL Server if you try to start a new database transaction while you still have an open resultset from a query in the same connection. 

In terms of EF, this exception usually appears if you call `SaveChanges()` inside a loop that is consuming results from an EF query on the same DbContext: 

- The EF query is backed a `SqlDataReader` and that `SqlDataReader` will remain open until you finish consuming the results 
- `SaveChanges()` will try to initiate a SqlTransaction. 

There are [a few threads in StackOverflow.com](http://stackoverflow.com/search?q=New+transaction+is+not+allowed+because+there+are+other+threads+running+in+the+session) that describe the issue (usually in the context of previous versions of EF) and the solution.

**Comment by ac-esousa** [comment]
The way I am using DbContext with async, there is no concurrent use of the same DbContext. But operations might get continued in different threads.

All data retrieval I am doing prior to `SaveChangesAsync`, is done by one of the following methods:
* `FirstOrDefaultAsync`
* `SingleOrDefaultAsync`
* `ToListAsync`

_All from Microsoft.Data.Entity.EntityFrameworkQueryableExtensions_

Is it possible for one of these methods to be leaving a SqlDataReader opened?

**Comment by divega** [comment]
The reader should be closed as soon as the Task returned by each method is completed (e.g. you have to use `await` on each individual call to async methods). That is, unless we have a bug somewhere, in which case it would be useful if you could provide:

1. The exact version of the EF7 bits you are using.
2. The full stack trace of the exception.
3. A complete code listing or application we can use to repro the issue on our end.

**Comment by ac-esousa** [comment]
Sorry for this post.

After some debugging, I found one `FirstOrDefaultAsync` which did not had `await` on it, cause the query to be running on background while `SaveChanges` was being called.

That was the reason for my issue

**Comment by divega** [comment]
@ac-esousa no worries! Glad you found where the issue was in your code and glad to help!

**Comment by kieranfoot** [comment]
I get this error when using async methods in UserManager called from Startup.Configure. They are there to ensure certain data exists within the database. 

`public static void EnsureUsersHaveRoles(this IApplicationBuilder app)
        {
            var context = app.ApplicationServices.GetService<ApplicationDbContext>();
            if (context.AllMigrationsApplied())
            {
                var userManager = app.ApplicationServices.GetService<UserManager<ApplicationUser>>();
                DbSet<ApplicationUser> users = context.Users;
                foreach (ApplicationUser user in users)
                {
                    if (user != null)
                    {
                        Task<IList<string>> rolesTask = userManager.GetRolesAsync(user);
                        rolesTask.Wait();
                        List<string> roles = new List<string>(rolesTask.Result);

                        if (roles.Count == 0)
                        {
                            Task<IdentityResult> addRoleTask = userManager.AddToRoleAsync(user, Roles.DefaultRole);
                            addRoleTask.Wait();
                            Debug.WriteLine($"*** ADDED USER [{user.UserName.ToUpper()}] TO GROUP [{Roles.DefaultRole.ToUpper()}] ***");                            
                        }
                        else
                        {
                            Debug.WriteLine($"*** USER [{user.UserName.ToUpper()}] HAS GROUP [{roles[0].ToUpper()}] ***");
                        }

                        if (string.IsNullOrWhiteSpace(user.PrimaryRole))
                        {
                            user.PrimaryRole = roles[0];
                            Task<IdentityResult> updateTask = userManager.UpdateAsync(user);
                            updateTask.Wait();
                        }
                    }
                }
            }
        }`

As far as I can see, I'm waiting in all the right parts, but I'm still getting the error.

**Comment by rowanmiller** [comment]
@kieranfoot I think you need a `ToList()` on the query you are using to iterate over users:

```c#
var users = context.Users.ToList();
foreach (ApplicationUser user in users)
{
```

Without that, you have an active query until the for loop has completed... then you are spinning off other operations within the for loop.

**Comment by kieranfoot** [comment]
Indeed, I guess I should have figured that. Context is the still working.
Thanks for the help.

**Comment by bidianqing** [comment]
At the same time, a CbContext can only execute an asynchronous method
