### ISSUE TITLE
Dacpac/SSDT Integration

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#4321]
There are a couple of scenarios here:
- Generate a model from an existing database project (#1186)
- Rather than using EF Migrations, translate model changes to schema changes in a database project
- Generate a dacpac from an existing model

Note that I don't think we should look at integrating migrations and dacpac/SSDT in anyway - we should allow folks to use dacpac/SSDT **instead** of migrations. The main reason for this is that they use fundamentally different approaches to how schema changes are tracked. Migrations is very explicit and has a step by step process to take a schema thru a well ordered set of states (i.e. no schema comparison is done when applying migrations, we just run the exact steps recorded in each migration). Dacpac/SSDT takes a target schema and some other info (like refactor log) to calculate the changes during deployment.

**Comment by rowanmiller** [comment]
BTW here is some info on the API for interacting with dacpac http://blogs.msdn.com/b/ssdt/archive/2013/12/23/dacfx-public-model-tutorial.aspx

**Comment by ErikEJ** [comment]
The latest daily build of "EF Core Power Tools" allows you to reverse engineer from a Dacpac https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by kant2002** [comment]
Link to DacPac public model now is here:
 https://devblogs.microsoft.com/ssdt/dacfx-public-model-tutorial/

**Comment by bricelam** [comment]
I turned Erik's code into a package. Now you can do this too:
```sh
dotnet add package ErikEJ.EntityFrameworkCore.SqlServer.Dacpac
dotnet ef dbcontext scaffold My.dacpac ErikEJ.EntityFrameworkCore.SqlServer.Dacpac
```

**Comment by syndicatedshannon** [comment]
@bricelam Thank you for that. I think we're pretty far past that in our development. That will only work for early dev, right? I think we'll find that not everything will be representative, need to apply attribute/fluent overrides, and then not be able to run scaffold again without losing our work.

I'm still holding out hope that EF team will get to [this](https://github.com/dotnet/efcore/issues/4321) / #1186 issue. A little less hopeful when I see attempts to [adapt code-first to DACPAC tasks](https://github.com/dotnet/efcore/issues/19587), though...

Anyway, you've become a staple in my work life, through this window on you. Thanks for the work you've done!

**Comment by ajcvickers** [comment]
Functionality is covered by EF Core Power Tools. We don't plan to implement anything here.

**Comment by ErikEJ** [comment]
@AliFayazbakhsh You can create a SQL script from the current model using EF Core Power Tools, and import that into the database project

**Comment by AliFayazbakhsh** [comment]
@ErikEJ 
Thank you,
I look for some more automated way, such as compile pipeline generator or CLI command to use in post build script (similar to https://github.com/dotnet/efcore/issues/4321#issuecomment-582646096).

**Comment by ErikEJ** [comment]
`dotnet ef dbcontext script` ?

and then some `sqlpackage` command perhaps?

**Comment by AliFayazbakhsh** [comment]
@ErikEJ 
Yes, It is what I'm looking for.
Although the script that generated by  `dotnet ef dbcontext script` is not fully compatible by SSDT, for example in SCHEMA creating. I'm working to fix it with some PowerShell script but it can be an option or switch in CLI.
