### ISSUE TITLE
'Program' type missing from EF Command with latest packages

### ISSUE THREAD

**Issue by jruckert** [dotnet/efcore#4323]
When running "dnx ef" on our core project, it returns with: (7.0.0-rc2-16740)

'EntityFramework.Commands' does not contain a 'Program' type suitable for an entry point

We have noticed that this has only occurred over the last couple of days. Do we have to transition to the dotnet cli now, if so how would we run it?

**Comment by rowanmiller** [comment]
Our code base is in an interim state while we cut over to .NET CLI. You won't be able to run commands on the nightly builds while all the pieces fall into place.

**Comment by jruckert** [comment]
Can I bump back to a specific version to get me over the line?

**Comment by jruckert** [comment]
I've swapped back over to the vnext feed for this package, this seems to be OK.

**Comment by rowanmiller** [comment]
If you get the build from https://www.myget.org/F/aspnetvnext then you should be fine for the moment. Packages won't get published to there until the unit tests for every repository pass on a single set of packages - that should be a while as we stabilize the .NET CLI integration :smile:

**Comment by jruckert** [comment]
Yep - totally understand that we are playing with fire. :smile: :fire:

**Comment by bricelam** [comment]
Feature work is being tracked by #3925

**Comment by rowanmiller** [comment]
Closing as we already have an item tracking making this work
