### ISSUE TITLE
How to use ISensitiveDataLogger to log parameters

### ISSUE THREAD

**Issue by ShiroYacha** [dotnet/efcore#4324]
Hi,
I have searched a bit on this repository, trying to find a way to let the logger include parameter data (not displayed as "?"). I have implemented `ISensitiveLogger` and passed it to the `ILoggerFactory` and its provider but still I get parameters as "?" when I call `DbContext.SaveChanges()`.

I would like to know what is the correct way of using this. Btw, I am using EntityFramework.Sqlite but I don't think provider is relevant here? 

Thanks!

**Comment by ErikEJ** [comment]
Maybe you need to enable it in OnConfiguring https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/BasicEndToEndScenario.cs

**Comment by rowanmiller** [comment]
As @ErikEJ pointed out, call `options.EnableSensitiveDataLogging()` in the `OnConfiguring` method of your context (or in the `AddDbContext` call in `Startup.cs` if you are using ASP.NET Core).

**Comment by simeyla** [comment]
@ShiroYacha If you came up with a class you could share I'd very much like to do see what you came up with. Thanks.

**Comment by ajcvickers** [comment]
@simeyla There really shouldn't need to be any reason to implement this interface. Sensitive data logging is turned on or off by the call on DbContextOptionsBuilder.
