### ISSUE TITLE
EF7 TPH inheritance pattern doesnt work

### ISSUE THREAD

**Issue by bartekkois** [dotnet/efcore#4326]
EF7 doesn't properly create table structure when using TPH inheritance pattern under Visual Studio 2015 Community edtion with ASP.NET5-RC1 installed. 

```
namespace TestEFMigration.Models
{
    public abstract class ServiceItem
    {
        [Key]
        public int Id { get; set; }

        public string AbstractServiceItem { get; set; }
    }

    public class InstallationServiceItem : ServiceItem
    {
        public string ClassInstallationServiceItem { get; set; }
    }

    public abstract class SubscriptionServiceItem : ServiceItem
    {
        public string ClassSubscriptionServiceItem { get; set; }
    }

    public class InternetSubscriptionServiceItem : SubscriptionServiceItem
    {
        public string ClassInternetSubscriptionServiceItem { get; set; }
    }

    public class PhoneSubscriptionServiceItem : SubscriptionServiceItem
    {
        public string ClassPhoneSubscriptionServiceItem { get; set; }
    }

    public class DataDbContext : DbContext
    {
        public DbSet<ServiceItem> ServiceItems { get; set; }
    }
}
```

The code above is translated during migration into:

```
namespace TestEFMigration.Migrations.DataDb
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ServiceItem",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    AbstractServiceItem = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ServiceItem", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable("ServiceItem");
        }
    }
}
```

which does not include properties from inheriting classes and Dicriminator property.

**Comment by smitpatel** [comment]
That is because none of other entities are included in the model. The DbContext has DbSet for `ServiceItem` hence it is added as entity type in the model. But there is no code to tell EF to include other types as entity type in the model. Either include DbSet for other classes as well or use `modelBuilder.Entity<ClassName>();` in `onModelConfiguring` method of DbContext. That will include those subclasses and conventions will wire up everything as expected.

**Comment by bartekkois** [comment]
This is a different approach. I like to use so called Table per Hierarchy with common table and Discrimator property and according to this tutorial http://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-1-table-per-hierarchy-tph only the base class should be included.

**Comment by smitpatel** [comment]
That information is out of date and was applicable to an older version of EF.
For inheritance in EF7, please visit http://ef.readthedocs.org/en/latest/modeling/inheritance.html

**Comment by bartekkois** [comment]
Now it works ok. Thanks for help.
