### ISSUE TITLE
Optimistic Concurrency  can not get current DatabaseValues

### ISSUE THREAD

**Issue by ligaku** [dotnet/efcore#4332]
on the process of DbUpdateConcurrencyException 
how  to get  current DatabaseValues

**Comment by rowanmiller** [comment]
We will add APIs like we had in EF6 - this is already tracked by https://github.com/aspnet/EntityFramework/issues/1200

In the meantime, a NoTracking query can be used to get a copy of the entity with the current database values:

```c#
var databaseVersion = context.Blogs.AsNoTracking().Single(b => b.Id == blogId);
```
