### ISSUE TITLE
Type converters

### ISSUE THREAD

**Issue by SiarheiTatarchanka** [dotnet/efcore#4333]
Didn't find possibility to use type converters.

As an example: 
in a DB I have a column with varbinary(char(1)) type. And this should be converted into boolean in entity.

In **Telerik Open Access** I have possibility to use something like the below:

```
HasProperty(x => x.SomeProperty).WithConverter<BitTypeToBooleanConverter>();
```

Do we have something like that in EF7?

**Comment by rowanmiller** [comment]
This isn't supported yet... but we have https://github.com/aspnet/EntityFramework/issues/242 tracking this scenario (which is part of a bigger area of work tracked by https://github.com/aspnet/EntityFramework/issues/240)
