### ISSUE TITLE
Automate UWP/.NET Native tests

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#4336]
We manually test EF support for UWP (.NET Native). We should automate this in our testing infrastructure.

**Comment by natemcmaster** [comment]
To automate WACK tests:

Some info I found on using appcert.exe from the command line:

Using the command line

Example for testing a Store app: c:\Program Files (x86)\Windows Kits\10\App Certification Kit>appcert.exe test -resettesting -reportoutputpath %localappdata%\Microsoft\appcertkit\report.xml -appxpackagepath c:\packages\pathToAppx.appx -testid [38,45] [-noinstallappx -bundlearchitecture ]
Parameters:

"-resettesting": needed in order to overwrite previous results, otherwise you get an error that you need to run the entire kit again
"-testid": if specified it will execute only those tests. If omitted all tests will be executed
"-noinstallappx": if specified it will not deploy the app, but rather unpack it using makeappx
"-bundlearchitecture": if specified it will test the package for the given architecture in the bundle. Used only in conjunction with "-noinstallappx"

**Comment by AndriySvyryd** [comment]
See https://xunit.github.io/docs/getting-started-devices-uwp.html for how to create a testing app

**Comment by bricelam** [comment]
>  If your tests are in other assemblies, add a project reference and modify the `App.xaml.cs` to include the assembly containing your tests

Sweet.
