### ISSUE TITLE
Inspect usage of MakeGenericMethod/Type

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#4337]
We make extensive use of `MethodInfo.MakeGenericMethod`, `Type.MakeGenericType`, and `Expression.Lambda` (which calls MakeGenericType under the hood). The are the primary source of crashes on .NET Native.

We should inspect our usages of these troublesome APIs and reduce usage where possible, especially in commonly used paths e.g. `QueryCompiler.CompileQuery`

**Comment by rowanmiller** [comment]
@anpete can you take a look at `QueryCompiler.CompileQuery`

**Comment by rowanmiller** [comment]
We should just focus on things that are blocked... not removing ones that we have already enabled to work.
