### ISSUE TITLE
The basic one-to-many example in the EF7 docs doesn't work

### ISSUE THREAD

**Issue by strich** [dotnet/efcore#4341]
Following the basic Blog and Post model example in the EF7 docs here doesn't quite work.

The first key issue is that the example doesn't even go over the Post model, controller and view. Which is arguably the most important part in seeing a typical one-to-many example. Luckily the VS2015 templates do a lot of the work for you - If you scaffold generate the Controllers for the Blog and Post Models things work except for one key problem:

The Views\Post\Create.cshtml doesn't correctly populate the Blog ID dropdown box. It contains nothing and so the developer cannot see a working implementation of the one-to-many system.

The automatically generated Views\Post\Create.cshtml form:

``` html
<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="BlogId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="BlogId" class ="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>
```

**Comment by rowanmiller** [comment]
@strich does the intro not work, or it just doesn't demonstrate as much as you would like?

Regarding the scaffolded views/controllers not working with the relationship. This was an issue in the RC1 release and the ASP.NET scaffolding team is fixing it for RC2.

My plan is to swap the docs over to use ASP.NET scaffolding (rather than manually adding controller/views) for RC2 - since a lot of issues are resolved in RC2.

**Comment by strich** [comment]
I've finally worked out the core of my issues - It all basically came down to the fact that EF7 no longer supports lazy-loading and I had spent literally a couple of days coming to that conclusion thinking it was bugged (I am a novice ASP.NET dev). I'm sure you're aware of the discussion happening in its thread here https://github.com/aspnet/EntityFramework/issues/3797.

Regardless of the outcome of lazy-loading I would suggest adding some notes to the example ASAP on the use of `Include()` to make one-to-many actually work. Its a big gotcha for novices given that googling the problem turns up EF6 and below solutions, which of course have the feature.

With regards to the above issue specifically though - The intro is fine if you don't use the current scaffolding yeah. The scaffolding doesn't appear to work seemlessly with the intro demo however. Sounds like it'll resolve itself in RC2.

**Comment by rowanmiller** [comment]
Thanks, sounds like we already have things coming in RC2 to address this so I will close this issue out.

**Comment by strich** [comment]
Just curious - Whats the approx. ETA for RC2?

**Comment by rowanmiller** [comment]
@strich we're following the [same schedule as ASP.NET Core](https://github.com/aspnet/Home/wiki/Roadmap) - RC2 will be next month (Feb)

**Comment by rowanmiller** [comment]
And based on the amount of churn about to happen EF/ASP.NET code bases for renames etc... you can probably deduce that it will not be the first half of the month :smile:
