### ISSUE TITLE
Multiproject issue about Add-Migration command

### ISSUE THREAD

**Issue by snys98** [dotnet/efcore#4361]
```
PM> Add-Migration FirstMigration
Add-Migration : 使用“8”个参数调用“CreateInstanceAndUnwrap”时发生异常:“未能加载文件或程序集“EntityFramework.Commands”或它的某一个依赖项。系统找不到指定的文件。”
所在位置 行:1 字符: 1
+ Add-Migration FirstMigration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException,Add-Migration
```

Which means

```
Add-Migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'EntityFramework.Commands' or one of its dependencies. File not found.
```

This happens  when I'm trying to use the "Add-Migration" command to my test console application with the startup project set to another asp.net 5 project. I got a lot of efforts to find why this happened and after half an hour I got use **"-verbose"**(forgive me QAQ) and **it turned out to be that the NuGet package manager's default project setting seems to be of no use in this condition, this command is still trying to "Add-Migration" in my startup project, ignoring the NuGet package manager's setting**.

```
PM> Add-Migration FirstMigration -Verbose
Using startup project 'src\WebApplication1'.
Using project 'ConsoleApplication1'
Build started...
Build succeeded.
Using application base 'D:\workspace\WebApplication1\src\WebApplication1\..\..\artifacts\bin\WebApplication1\'.
No configuration file found.
```

If this problem isn't of the necessity to be treat as a bug, please at least add something to the tutorial doc. Thanks, please forgive my poor English, I hope that descriptions will be understandable

**Comment by rowanmiller** [comment]
Hey,

Unfortunately Package Manager Console commands are not supported with ASP.NET 5 (a.k.a ASP.NET Core) projects. This should be enabled in RC2 (it requires NuGet Init.ps1 support being added to xproj) and is tracked by https://github.com/aspnet/EntityFramework/issues/978.

See http://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html#create-your-database for info on how to use the `dnx ef` commands for ASP.NET 5 projects in RC1.

~Rowan
