### ISSUE TITLE
How to get the current time of sql server?

### ISSUE THREAD

**Issue by linqingfeng** [dotnet/efcore#4362]
Hi,

In EF6, we get sql server current time, like this

DateTime currentDateTime = db.Database.SqlQuery <DateTime> ("SELECT GETDATE ();"). FirstOrDefault ();

But EF7, Database.SqlQuery does not exist, how to solve?

[Notes]

We can not use the following code:

DateTime currentDateTime = db.Users.Select (q => DateTime.Now) .FirstOrDefault ();

or

DateTime currentDateTime = db.Set <Role> () Select (q => DateTime.Now) .FirstOrDefault ().;

Since the beginning of our DbContext not contain any Entity, so ...how to solve?

thank you very much!

**Comment by rowanmiller** [comment]
Until we have the ability to query for non-entity results (tracked by #1862) you would need to write something like this.

```c#
var con = db.Database.GetDbConnection();
var cmd = con.CreateCommand();
cmd.CommandText = "SELECT GETDATE()";
con.Open();
var datetime = (DateTime)cmd.ExecuteScalar();
con.Close();
```

**Comment by rowanmiller** [comment]
Closing this out as I think that answers your question and we already have #1862 tracking the feature that you really want in order to do this cleanly. Feel free to re-open if you disagree :smile:.

**Comment by AndriySvyryd** [comment]
As a side note it is highly suggested to use UTC time instead of the local time by using `GETUTCDATE` to avoid having to deal with time zones, daylight savings time and so on.

**Comment by linqingfeng** [comment]
Thank you very much!

**Comment by mohammadfiroozi** [comment]
`DataTime getServerTime = context.CreateQuery<DateTime>("CurrentDateTime() ").AsEnumerable().FirstOrDefault();`
