### ISSUE TITLE
Why does ChangeTracking.EntityEntry.State not revert back to Unchanged?

### ISSUE THREAD

**Issue by mehrt** [dotnet/efcore#4363]
I tried this with v7.0.0-rc2-16649. I'm using the simplest of models, based on the [console example](http://ef.readthedocs.org/en/latest/getting-started/full-dotnet/new-db.html), and an extension method on the DbContext, based on [this SO answer](http://stackoverflow.com/a/32600309):

```
public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Visual Studio 2015 | Use the LocalDb 12 instance created by Visual Studio
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=ChangeStateTest;Trusted_Connection=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Make Blog.Url required
        modelBuilder.Entity<Blog>()
            .Property(b => b.Url)
            .IsRequired();
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
}

public static class Extensions
{
    public static bool CheckStateChanged<T>(this DbContext context, T b) where T : class
    {
        var entry = context.Entry(b);
        if (entry == null) return false;
        foreach (var property in entry.Metadata.GetProperties())
        {
            var originalValue = entry.Property(property.Name).OriginalValue;
            var currentValue = entry.Property(property.Name).CurrentValue;

            if (!originalValue.Equals(currentValue))
                return true;
        }
        return false;
    }
}
```

If I then do the following ...

```
using (var db = new BloggingContext())
{
    Blog b = new Blog { Url = "http://blogs.msdn.com/adonet" };
    db.Blogs.Add(b);
    var count = db.SaveChanges();
    Console.WriteLine("{0} records saved to database", count);
    Console.WriteLine("Change state of Blog: {0}", db.Entry(b).State);
    b.Url = "http://www.dortcon.de";
    Console.WriteLine("Change state of Blog after change: {0}", db.Entry(b).State);
    b.Url = "http://blogs.msdn.com/adonet";
    // This makes no difference:
    // db.ChangeTracker.DetectChanges();
    Console.WriteLine("Change state of Blog after reverting change: {0}", db.Entry(b).State);
    Console.WriteLine("Change state via function: {0}", db.CheckStateChanged(b));
    Console.ReadLine();
}
```

... the Output I get is:

> 1 records saved to database
> Change state of Blog: Unchanged
> Change state of Blog after change: Modified
> Change state of Blog after reverting change: Modified
> Change state via function: False

Is this by design, am I doing something wrong, or am I expecting too much? My expectation was that the change state is based on comparison with the original values, but that doesn't seem to be the case. If it's not, what is it doing, and why does it behave like this? I would actually like to use it to mark a grid row as modified, but currently I can't do that. The extension method works, but seems to be more hassle than should be necessary.

**Comment by rowanmiller** [comment]
We've had this behavior in EF since it's first release and we haven't really heard folks say that they want it changed. We could add the additional logic in EF to handle it, but my guess is that you hardly ever hit this situation in a real application. Given that we've not seen many folks want it changed, and it would be additional logic to implement, test, performance tune, etc. we aren't planning to change it.

We would of course reconsider this if we see a number of folks hitting issues due to this behavior.

**Comment by mehrt** [comment]
@rowanmiller Thanks, that explains it ... I know nothing about earlier versions of EF.

So if I'd like to see the "real" change state of an entity, I have to resort to using the comparison of CurrentValue / OriginalValue then? That should reliably work once #4375 is fixed ... I'll have to do that, since I need the real change state to colour grid rows as I described above.

**Comment by rowanmiller** [comment]
@mehrt BTW you can set IsModified on a property back to false, so maybe loop over and reset it to false when the original and current are the same.

**Comment by EEaglehouse** [comment]
@mehrt It looks like your value is not being "reverted", but changed twice: once before the SaveChanges() and once after. I would expect to see the state as Modified. The newer version of EFs, as I've experienced it working, keep modification flags about properties and entities that are changed and the actual property values are not compared. If you want the property or entity to revert to an unchanged status, the obvious choice is to set the State to Unchanged.
