### ISSUE TITLE
Startup.cs Main entry point and EFF

### ISSUE THREAD

**Issue by kscott5** [dotnet/efcore#4367]
It's one thing to change the release but its unacceptable that there's a lack of documentation to support the changes. It not worth the effort to maintain a code base where there's a lack of stability with the release candidate 1, 2 or update...

![capture](https://cloud.githubusercontent.com/assets/132991/12497156/a61dc72c-c05f-11e5-8bbf-c910ea590084.PNG)

[Green Shelter Code Repository](http://github.com/kscott5/GreenShelter)

Any suggestion on how best to fix this and many other issues. Such as pull a specific version of an assembly that's no longer available.

dnu install System.Diagnostics.DiagnosticSource 4.0.0-rc2-23629

or Strong Name errors!!!!

**Comment by bricelam** [comment]
What's in your `project.json`? It looks like you're mixing incompatible versions of `Hosting` and `EntityFramework.Commands`...

**Comment by bricelam** [comment]
Hmm, the `project.json` of referenced repository looks fine. There is a ton of churn in the nightly builds right now as we transition off of DNX and onto the .NET Core CLI. For some semblance of stability, you may want consider using the RC1 packages until the dust settles.

**Comment by rowanmiller** [comment]
> For some semblance of stability, you may want consider using the RC1 packages until the dust settles.

Agreed, we don't maintain documentation etc. for nightly builds (and things are going to be very rough for the next few weeks while a whole bunch of renames etc. happen). If you opt into using nightly builds then you can expect pain :smile:. When it comes time for RC2 then we will provide details on how to upgrade from RC1 etc.

BTW your point about this not being as stable as RC software should be is valid :smile:.

**Comment by kscott5** [comment]
@rowanmiller I'm not alone, and I'm not crazy! Well, crazy a little cause I still enjoy da code.

Thanks for your reply. I will continue to use but any help with EF would be appreciated.

@bricelam or anyone,

What's recommend way to reference assemblies in the project.json?
How does referencing the targeted SDK (RC1) affect the global.json and projects as whole?
What's the recommend way to reference and register strongly type options (such as SessionOptions) in the Startup.cs? This is important considering dependency injections of SessionOptions has to load an enumerated property.

**Comment by bricelam** [comment]
To use RC1, just make sure the nightly MyGet feed is not active in your `NuGet.config`.

I don't understand the issues your having related to strong-naming. Can you post the steps, code, expected result, etc. of the issue you're seeing?

**Comment by kscott5** [comment]
My GreenShelter github repo has the code segment.  It's in the ConfigureServices method located in Startup.cs file. It stopped running after the Main method was introduced as the WebApplication entry point of execution.  Take and provide any suggestions and/or coding best practices.




Sent from my T-Mobile 4G LTE Device


-------- Original message --------
From: Brice Lambson
Date:01/22/2016 4:47 PM (GMT-06:00)
To: aspnet/EntityFramework
Cc: Karega Scott
Subject: Re: [EntityFramework] Startup.cs Main entry point and EFF (#4367)


To use RC1, just make sure the nightly MyGet feed is not active in your NuGet.config.

I don't understand the issues your having related to strong-naming. Can you post the steps, code, expected result, etc. of the issue you're seeing?

-

**Comment by rowanmiller** [comment]
We've opened up https://github.com/aspnet/EntityFramework/issues/4546 to track the high level need to revisit how we interact with Startup.cs.
