### ISSUE TITLE
Assembly version and GAC

### ISSUE THREAD

**Issue by JakeGinnivan** [dotnet/efcore#4370]
A number of our developers just had issues with their applications failing to start because EF has locked the assembly version at 6.0.0.0 and strong named, then the EF tools for visual studio apparently GAC EntityFramework.dll

This caused us to get a `MissingMethodExeception` because the version in the GAC is older than what is installed via NuGet. 

EF should version the assembly properly and bump the version whenever the public API changes or stop GACing the assembly in installers.

**Comment by divega** [comment]
@JakeGinnivan As for the assembly version, we froze it intentionally in EF 6.x to enable many programs (tools in VS among others) to work with the newer compatible versions without the need of binding redirects. This is not an uncommon practice, e.g. this post summarizes why JSON.NET did the same: http://james.newtonking.com/archive/2012/04/04/json-net-strong-naming-and-assembly-version-numbers

Could you explain how you arrived to the conclusion that the EF Tools for Visual Studio registers EntityFramework.dll in the GAC? I agree if that was the case it would be a bug, but I doubt it is. We have been recommending against doing that for a long time and as far I know none of our installers do it.
