### ISSUE TITLE
Question: Order by error: At least one object must implement IComparable.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#4374]
I'm doing (using RC1-final):

```

public class SomeClass {
    public SomeClass(List<YearEvents> events) {
        var orderedList = events.YearEvents.OrderBy(e => new { e.Year, e.Month, e.Day });
    }
}
```

Where events is a list of this class

```
public class YearEvent {
    public int Id { get; set; }
    // ...
    public int Year { get; set; }
    public int? Month { get; set; }
    public int? Day { get; set; }
}
```

I'm getting the following error:
`ArgumentException: At least one object must implement IComparable.`

if I do 

```
context.YearEvents.OrderBy(e => new { e.Year, e.Month, e.Day });
```

I get:

`An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
 Incorrect syntax near ''.`

doing `.OrderBy(e=> e.Year)` (by year only) it works fine.

how should I do an order by those values? why is this error triggered? Is it a missing feature of EF or (most likely) i'm doing something very obviously wrong ?

**Comment by anpete** [comment]
@Bartmax Use the [ThenBy](https://msdn.microsoft.com/library/system.linq.queryable.thenby(v=vs.100).aspx) method when you want to order by multiple expressions.

**Comment by Bartmax** [comment]
Thanks, it works. 

Not sure if I like it (from an api point of view), looks like hacking Linq, code reads great tho.

I may be biased because it was very 'hidden' on the api and error msg (at least for me).

**Comment by rowanmiller** [comment]
Closing out as this is just how LINQ works. In the sample code shown, EF isn't even in the picture (note that `events` is a `List<T>` so even if the data comes from a context, EF has fully materialized it at this point and LINQ to Objects is in play).

```
    public SomeClass(List<YearEvents> events) {
        var orderedList = events.YearEvents.OrderBy(e => new { e.Year, e.Month, e.Day });
    }
```

**Comment by Bartmax** [comment]
@rowanmiller I was showing that with LINQ to Objects and EF because both throw errors and I recall using it that way before on EF5 (I may be wrong).

I'm good with `ThenBy` method (applying to the context directly and not to the List).

Thanks for the help.
