### ISSUE TITLE
CLI Commands: Expose Scaffold-Directives

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#4377]
Should we expose a .NET Core CLI equivalent of the `Scaffold-Directives` NuGet command?

Maybe something like `dotnet ef dbcontext scaffold-directives`...

**Comment by rowanmiller** [comment]
I don't think we need it yet. You currently only need directives for UWP... and almost everyone doing that is going to be using VS and has PMC commands available. Of course, if .NET Native becomes more prevalent then that will change :cry:

**Comment by natemcmaster** [comment]
I think this is still generally useful. I personally don't like PMC. Plus, this could make it possible (in theory) for a user to automate rdxml gen on CI server or with version control hooks.

**Comment by bricelam** [comment]
Closing. The command was removed by #4621
