### ISSUE TITLE
About table field is "VARCHAR" problem

### ISSUE THREAD

**Issue by linqingfeng** [dotnet/efcore#4384]
Hi,

In EF6, if the table field is "VARCHAR", requires the following code:

``` c#
modelBuilder.Entity<User>()
     .Property(e => e.Password)
     .IsUnicode(false);
```

However, in EF7, no "IsUnicode", "IsUnicode" is not without manual settings?

thank you very much!

**Comment by smitpatel** [comment]
dup of #3420
