### ISSUE TITLE
Deleting all migrations and the DB causes subsequent new migrations to never create tables

### ISSUE THREAD

**Issue by strich** [dotnet/efcore#4385]
Still in the middle of development so on occasion I remove all the migrations and completely wipe the DB itself and make a new Initial migration.

It appears that at the moment I can get myself into a situation where after doing so the generated Initial migration doesn't have any CreateTable methods and so it never makes the tables of my own models. The `database update` command succeeds, but its just not complete.

The project consists of only 4 models as well as the Identity template, and some of the models have one-to-many relationships. But that's it.

This is my ApplicationDbContext:

``` CSharp
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);

            builder.Entity<Agent>();
            builder.Entity<Job>();
            builder.Entity<Team>().HasMany(t => t.TeamMembers).WithOne(u => u.Team);
            builder.Entity<Team>().HasMany(t => t.Agents).WithOne(u => u.Team);
            builder.Entity<Team>().HasMany(t => t.Projects).WithOne(u => u.OwnerTeam);
            builder.Entity<Project>().HasMany(t => t.JobHistory).WithOne(u => u.ParentProject);
        }

        public DbSet<Team> Teams { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Agent> Agents { get; set; }
    }
```

Then I run a migration:

```
PS > dnx ef migrations add Initial -v

Finding DbContext classes...
Using context 'ApplicationDbContext'.
Writing migration to 'D:\Programming\Projects\GameRigger\src\GameRigger\Migrations\201
60123234619_Initial.cs'.
Writing model snapshot to 'D:\Programming\Projects\GameRigger\src\GameRigger\Migration
s\ApplicationDbContextModelSnapshot.cs'.
```

The Initial.cs migration in [this gist here](https://gist.github.com/strich/9fe7141c1d904dd16a89). You can see there are no table creations nor barely any mention of my models at all.

If I try to run a `database update` it fails as it cannot find any of the tables that are referenced a little in the Initial migrations (Like Agents).

**Comment by rowanmiller** [comment]
@strich do you also delete the model snapshot file that is alongside the migration files? This is what EF uses to compare the current model to in order to detect what changed. If you didn't delete this, then that would explain the empty initial migration.

**Comment by strich** [comment]
Yep that was the problem.
