### ISSUE TITLE
error : ILT0005 when I compile UWP (.NET Native)

### ISSUE THREAD

**Issue by fatterbetter** [dotnet/efcore#4387]
I use the EFGetStarted.UWP.sln
 (Link: https://github.com/aspnet/EntityFramework.Docs/tree/master/docs/getting-started/uwp/sample) 
 this project can compile both DEBUG and RELEASE. But after I add some class and DbSet, it failed when I compile in Release.

Repro steps:

1. Add 4 classes to the Model.cs

``` csharp:Model.cs
    public class BlogA
    {
        public int BlogAId { get; set; }
    }


    public class BlogB
    {
        public int BlogBId { get; set; }
    }


    public class BlogC
    {
        public int BlogCId { set; get; }
    }


    public class BlogD
    {
        public int BlogDId { set; get; }
    }
```

2. Add 4 DbSet to the BloggingContext in Model.cs

``` csharp:Model.cs
        public DbSet<BlogA> BlogAs { get; set; }
        public DbSet<BlogB> BlogBs { get; set; }
        public DbSet<BlogC> BlogCs { get; set; }
        public DbSet<BlogD> BlogDs { get; set; }
```

3. Compile in Release model, I got error like this:

```
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(1129,5): error : ILT0005: “C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\Tools\nutc_driver.exe ……
```

I want use EF7 in my store app. Can someone help me?

**Comment by ViktorBergman** [comment]
I was struggling with this issue for days and days and finally realized there was an issue with RC1 that has been fixed with the nightly builds of RC2 (using this nuget source: https://www.myget.org/F/aspnetcidev/api/v3/index.json) . So try upgrading to the latest build of RC2 and it should compile.

**Comment by fatterbetter** [comment]
I update ef to `7.0.0-rc2-16769`, and add `System.IO 4.1.0-rc2-23722`, then compile in debug model, but I get the `error APPX1101`.

```
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1151,5): error APPX1101: C:\Users\lchao\.nuget\packages\EntityFramework.Commands\7.0.0-rc2-16769\lib\dotnet5.4\EntityFramework.Commands.dll
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1151,5): error APPX1101: C:\Users\lchao\.nuget\packages\EntityFramework.Commands\7.0.0-rc2-16769\lib\net451\EntityFramework.Commands.dll
```

So, I remove the `EntityFramework.Commands\7.0.0-rc2-16769\lib\net451\EntityFramework.Commands.dll`, then it can compile in DEBUG.

But when I compile in RELEASE,  there is 

```
1>C:\Users\lchao\.nuget\packages\EntityFramework.Core\7.0.0-rc2-16769\build\netcore50\EntityFramework.Core.targets(8,9): error : Missing Properties/EntityFramework.g.rd.xml. This file is necessary for .NET Native to execute correctly. Generate this file by executing 'Scaffold-Directives' command from the Package Manager Console. See http://go.microsoft.com/fwlink/?LinkId=722449 for more details.
```

So I run `Scaffold-Directives`, in RELEASE, it can not be run.

```
PM> Scaffold-Directives
Cannot run in 'Release' mode because 'Compile with the .NET Native tool chain' is enabled. Disable this setting or use a different configuration and try again.
```

I change back to DEBUG, run `Scaffold-Directives`, also get some error:

```
Scaffold-Directives : 使用“8”个参数调用“CreateInstanceAndUnwrap”时发生异常:“未能从程序集“EntityFramework.Commands, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60”中加载类型“Microsoft.Dat
a.Entity.Design.OperationExecutor”。”
所在位置 行:1 字符: 1
+ Scaffold-Directives
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Scaffold-Directives], MethodInvocationException
    + FullyQualifiedErrorId : TypeLoadException,Scaffold-Directives
```

**Comment by ViktorBergman** [comment]
Commands don't work for me either so I had to remove it, I guess it will be fixed in coming releases... until then I have to live without migrations. I'm not qualified enough to provide an answer for getting Commands to work, just that I manage to compile in release without it :)

**Comment by fatterbetter** [comment]
I removed `EF.Commands`, then added `EntityFramework.g.rd.xml` to Properties folder manually  using [this file](https://gist.github.com/natemcmaster/fa49b7978de5b467fd5c), and added `System.IO.Compression v4.1.0-rc2-23722`.

But I got another error in RELEASE like this:

```
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(887,5): error : Internal compiler error: Unable to cast object of type 'Microsoft.Cci.MutableCodeModel.VectorTypeReference' to type 'Microsoft.Cci.INamedTypeReference'.
```

**Comment by rowanmiller** [comment]
RC2 is still a work in progress, so it's not too surprising that you are hitting issues with the commands not working property there.

Regarding the ILT0005 issue you are hitting on RC1, could it be that you have non ASCII characters in your profile path? [Other .NET Native users have reported the same error in this case](http://stackoverflow.com/questions/32395802/error-ilt0005-during-compilation-with-net-native-tool-chain).

**Comment by fatterbetter** [comment]
I am sure that all path does not contain any non-ASCII characters.

Looking forward to the RC2 final.

**Comment by natemcmaster** [comment]
Some of these issues are what https://github.com/aspnet/EntityFramework/pull/4358 is meant to fix

**Comment by fatterbetter** [comment]
Upgrade to RC2-16789, it can compile and run.

Thanks very much.

**Comment by natemcmaster** [comment]
Fixed with https://github.com/aspnet/EntityFramework/pull/4358

**Comment by imbushuo** [comment]
I wonder whether you compiled `rc2-16789` by yourself since I couldn't find that version on ASP.NET CI's MyGet source.

**Comment by bricelam** [comment]
@imbushuo There are various MyGet feeds:
* https://www.myget.org/F/aspnetvolatiledev - Unsigned, may have inconsistent dependencies across products
* https://www.myget.org/F/aspnetcidev - Unsigned but consistent
* https://www.myget.org/F/aspnetvnext - Signed and consistent
