### ISSUE TITLE
Scaffolding Controller in VS2015 gives Errir messagebox

### ISSUE THREAD

**Issue by SamJongenelen** [dotnet/efcore#4388]
When trying to scaffold via Add Controller (Add > New Scaffolded item > Web API 2 Controller with actions, using Entity Framework)

I fill in the data (which is correct):
![image](https://cloud.githubusercontent.com/assets/3382443/12536481/093e0206-c2a7-11e5-8c13-282574abf76c.png)

But get the following messagebox:
![image](https://cloud.githubusercontent.com/assets/3382443/12536474/d870cb22-c2a6-11e5-832a-610232d8f7af.png)

I guess it cant read the new EF7 version. Is this the proper location to report a bug?

**Comment by rowanmiller** [comment]
Hey,

You are correct that ASP.NET 4 scaffolding does not support EF Core (formerly EF7). You could open up a request on the ASP.NET 4 repo to ask for support http://aspnetwebstack.codeplex.com/.

~Rowan
