### ISSUE TITLE
Unable to cast object of type 'Microsoft.Cci.MutableCodeModel.VectorTypeReference' to type 'Microsoft.Cci.INamedTypeReference'.

### ISSUE THREAD

**Issue by fatterbetter** [dotnet/efcore#4391]
I use the get_start.uwp.sln, and update the EF7 to the nightly rc2, but I can not compile in RELEASE with the error:

```
Unable to cast object of type 'Microsoft.Cci.MutableCodeModel.VectorTypeReference' to type 'Microsoft.Cci.INamedTypeReference'.
```

What I missed?

**Comment by rowanmiller** [comment]
The process for compiling UWP apps in release mode is changing quite a bit between RC1 and RC2. You need to install the EntityFramework.Commands package and run the `Scaffold-Directives` command in Package Manager Console before trying to compile in release mode. This work was only just check in though... so no guarantees it will work properly yet./

**Comment by fatterbetter** [comment]
Upgrade to RC2-16789, it can compile and run.

Thanks very much.
