### ISSUE TITLE
Adding new non-key column causes FK to get dropped then readded

### ISSUE THREAD

**Issue by rhires** [dotnet/efcore#4405]
I'm adding a new column to a table (Role), but in doing the migration, EF wants to drop the FK from a separate join table (PersonRole) - really, both keys, the one pointing at the Person table, and the other pointing at the Role table - and then add it back after after the new column is added. This causes SQLite to complain that it can't do this. I've figured a work-around by just commenting out the offending code, and SQLite doesn't seem to have any issues. 
My question is whether my work-around is the right way to do it, and whether EF needs to drop then re-add the FK the way it does.

**Comment by smitpatel** [comment]
If there is any changes in the relationship then EF needs to drop & re-add the FK. Though it is highly likely that you are hitting the bug in model snapshot which was present in RC1 release.
Bug report: #3751 
The bug has been fixed by #3756 & #4349. It will be shipping in RC2 release.

**Comment by rhires** [comment]
Ah, ok. It would seem that my research was a bit lacking before I posted. Thanks!
