### ISSUE TITLE
EntityFramework.Commands - not working

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#4406]
EF.Commands have not worked on the CIDev release channel for nearly two weeks.  

Attempting to run EntityFramework.Commands returns the following error message:

```
> dnx ef
> Error: Unable to load application or execute command 'EntityFramework.Commands'.  Available commands: web, ef.
```

Any updates about when we will have access to Commands again?

**Comment by divega** [comment]
DNX is being removed and EF Commands are being reworked into a .NET CLI based tool. You can use #3925 to track our progress on that. In the meanwhile you will have to go back to a build in which commands are still functional, probably RC1. 

cc @bricelam in case he wants to suggest other workarounds.
